### ISSUE TITLE
[FE] Payment Info V2: Implement updated copay card design and logic

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#47764]
## Background
After speaking with the benefits-team-2 we learned that the debts portal only shows the most recent copays owed at each facility. They have no way of knowing if the user has paid off their copay therefore, they only show the most recent copay owed and do not include additional copays that may exist for that user. Since My VA is showing all copays and aggregating them we need to update our designs and logic to match the debt portal so we are consistent between the two pages for our users. This [Slack thread](https://dsva.slack.com/archives/CPE4AJ6Q0/p1664557969007349) explains the background for this ticket as well.  

[Anchor to the section of the updated FE documentation for copays is here.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/outstanding-debts-FE-documentation.md#copays-card)

## Tasks
- [x] Update copay card so the H2 on the card no longer shows a dollar amount and shows the number of copay bills (statements) that a user has on the copay balances page
- [x] Eliminate the H3 on the card to match designs
- [x] Change "due by" date to "Updated on" date and pull the most recent date that any copay bill has been updated on the copay balances page
- [x] PM to validate in staging with user 36

## Acceptance Criteria
- [x] Code matches new design of copay card
- [x] Copay data on My VA matches what is shown in the debt portal (a number of most recent copays for each facility)

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_
- _How can this work be validated?_ log in with user 36, validate copay information matches what is in the debt portal

**Comment by ericasauv09** [comment]
Identifyed a bug during validation which is being resolved in #48195

**Comment by ajakabcin** [comment]
Putting this in blocked until #48195 is resolved

**Comment by ericasauv09** [comment]
unblocking and closing now that #48195 is complete
