### ISSUE TITLE
[Design] Create Final Wireframe for API Error Messages

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47787]
## Tasks
- [ ] Create final mockups with callouts for these error messages
    - System error (claim did not go through, something bad happened)
    - No response error (claim may or may not have been submitted)
- [x] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [ ] UI review meeting with product/UX team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.

**Comment by kellysmith1008** [comment]
@zach-park I was looking through the design language system today, and I'd like to suggest the following two alerts - pending review of the flow with you tomorrow:
- System error (claim did not go through, something bad happened)
Title: We've run into a problem
Message content: We're sorry. Something went wrong on our end. Please try again.
(alert box component, error state state, above page title location)

No response error (claim may or may not have been submitted - but user can still proceed)
Title: We've run into a problem
Message content: We're sorry. Something went wrong on our end. You can try again now, or move on to the next step and come back later to complete this.
(alert box component, warning alert state, above page title location)

**Comment by loripusey** [comment]
I don't think you will be able to come back later to complete the travel claim as the applicable will block you from attempting to check-in again and there is no mechanism to submit a claim outside of the check-in workflow.
@zach-park @kellysmith1008 @benbrasso-agile6

**Comment by benbrasso-agile6** [comment]
We have a ux meeting to chat this through later today

**Comment by benbrasso-agile6** [comment]
Removed mural from ticket. Not related.

**Comment by benbrasso-agile6** [comment]
Pulled some existing examples of error message within the PCI app:

“We’re sorry. We can’t check you in online. We
need to review your health insurance information
with you. Ask a staff member for help.”

“We’re sorry. We can’t check you in online. Ask a
staff member for help.”

“We apologize, but our automated system was
unable to check you in to your VA appointment.
Please proceed to the clinic to check in with one of
our staff.”

“We’re sorry. We couldn’t match your information
to our records. Please try again.”

“We couldn’t check you in.
We’re sorry. We couldn’t match your information
to our records. Please ask a staff member for
help.”

“Sorry, we can’t complete pre-check-in.
We’re sorry. Something went wrong on
our end. Please try again.”

**Comment by zach-park** [comment]
[Abstract collection link](https://share.goabstract.com/cc1baa9a-d05e-402c-a2c7-90fd14f5460e?collectionLayerId=9421e29d-1565-4e6a-9ae5-0ca507077a80&mode=design): https://share.goabstract.com/cc1baa9a-d05e-402c-a2c7-90fd14f5460e?collectionLayerId=9421e29d-1565-4e6a-9ae5-0ca507077a80&mode=design

**Comment by benbrasso-agile6** [comment]
Looks good. Thanks

**Comment by benbrasso-agile6** [comment]
I don't think we need to run by accessibility or sitewide content right now. The message is so similar messages we're already using in the app.
