### ISSUE TITLE
Update "Faith Owusu-Sekere" to "Faith Arthur"

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#47783]
## User Story
As a VFS team member I want to be able to find the correct person for ATO orientation so that I don't have to reach out for help/assistance.

Assignee: @allison0034 
Peer Reviewer: @it-harrison 

## Description
"Faith Owusu-Sekere" has changed her name to "Faith Arthur". The purpose of this ticket is to update Faith's name in all of the VFS-facing guidance she is mentioned in.

## Impacted Artifacts
[ATO orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-ATOorientation)
[New VFS Team gh template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team%2C+analytics-insights&template=new-vfs-team.md&title=New+VFS+Team+%5BInsert+team+name+here%5D)

## Tasks
- [x] Change Faith's last name from "Owusu-Sekere" to "Arthur" on the ATO orientation page
- [x] Change Faith's last name from "Owusu-Sekere" to "Arthur" in the New VFS Team gh template

## Peer Review
- [x] Ticket reassigned to peer reviewer when ready for peer review
- [x] Peer Reviewer: Completes review and validates user story/Acceptance Criteria are met

## Acceptance Criteria
- [x] VFS teams know to look for Faith Arthur re: ATO orientation

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [ ] Ticket has been discussed as a team at Planning.
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [ ] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by it-harrison** [comment]
> @it-harrison this is ready for review

looks good!
