### ISSUE TITLE
FE | Profile | Document Error Codes

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#47781]
## Background

Currently we have some info on error codes and error messaging sprinkled throughout our GitHub Profile section but would like to build a repository that houses this information across the product portfolio and includes error codes, messaging, end-points, screenshots and the like. This is information will be helpful to everyone on the team and improve our ability to quickly identify and rectify issues.

The first part related to the back-end was recently completed and can be found in the sensitive repo: [profile errors document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/profile_errors.md)  and added to the sensitive repo.

## Tasks
- [x] Create a table that shows the following information for each section of the Profile section
     - End-points called
     - Error codes returned
     - Description of error code

## Acceptance Criteria
- [x] Create in a shareable file (ie Google docs)
- [x] Let PM know when completed and ready for review with FE
## Tasks
- [ ] Conduct Unit tests 
- [ ] Run E2E tests covering current code and regression
- [ ] All axe checks pass
- [ ] Notify PM if this needs to be deployed to Staging behind feature flag
  

## Acceptance Criteria
- [ ] Complete all unit testing
- [ ] End-to-end tests showing 0 violations
- [ ] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [ ] Confirm PM has opened a new ticket to deploy changes to Production using feature flag, if needed

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)?
- How can this work be validated?
- What updates need to be made (e.g. product outline, use cases, contact center guide)

## Associated Tickets
- #

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by adamwhitlock1** [comment]
@SKasimow I have added Frontend error documentation and links to the page: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/profile_errors.md

I also added another appendix on blocking network requests in devtools

I realized that we don't have FE docs for Account Security. Probably need to get a ticket made for that.
