### ISSUE TITLE
Content review of 911/emergency note on MHV secure messaging tool

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#47794]
## Issue Description

The health apartment team needs us to review content on the new secure messaging tool about what to do in an emergency. They need to have this content finalized before they go into their usability study. 

When reviewing and editing this content, we should look at the language we use in other areas on the site when mentioning 911 and what to do in an emergency. Once we have our finalized content, we need to post it for the product team in the initial intake ticket.

Here is the PDF of the full page but the only content to focus on is the Note.[https://app.zenhub.com/files/133843125/66cdaad9-6af8-4141-a21e-ecde5e4a3c45/download](https://app.zenhub.com/files/133843125/66cdaad9-6af8-4141-a21e-ecde5e4a3c45/download)

The intake request for background is #47747

## Tasks
- [x] Rework note (Aliyah)
- [x] Edit (Laura)
- [x] OCTO-DE review (Danielle)
- [x] Copyedit (Megan)
- [x] Post final content for product team in ticket #47747 (Laura/Megan)

## Acceptance Criteria
- [x] Product team has finalized content

**Comment by aliyahblackmore** [comment]
Hi @laurwill - passing this doc to you ahead of our sync! 

[Content review of 911 emergency note_AB_10.3.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9717194/Content.review.of.911.emergency.note_AB_10.3.docx)


Some notes:

1. I did a quick scan across VA pages and found some content on 911/emergency contact info on the [secure messaging ](https://www.va.gov/health-care/secure-messaging/)page, on the [Veteran Suicide Prevention](https://www.va.gov/health-care/health-needs-conditions/mental-health/suicide-prevention/) page, and on the screen when you select the red Veterans Crisis Line banner (“Talk to the Veterans Crisis Line”) on the top right side of the VA website.

2. As I mentioned yesterday, while working on this, wondering if this text can be moved outside of a Note, as the content feels a bit crowded here and there are more details to be included for the three contact options. 

3. I've included 2 options in the document. I am leaning towards Option 2, as it lists out the three ways to be in touch with the  Veterans Crisis Line and I felt it would be best to keep the information on the page, instead of linking out, as the original intake request mentions. 

4. I have a question about this note from the original intake request: “When the user selects the 911 link, their browser will prompt them to choose which app they want to open to make the call. The Veterans Crisis line will open the same modal as the red Veterans Crisis Line banner at the top of every page.”  On this note, I’m wondering if linking out would be best – thinking along the lines of placing the burden of extra steps on Veterans or having the information up front/listed on this page. Open to thoughts here! Additionally, across pages we include the 988 number, so I wonder if that would be more recognizable for Veterans.

5. And one other question - when they say “which app they want to open to make the call” what is meant by this? From an iPhone usually the number will show up and go straight to the phone function on the device. Not sure if this is also the case on Androids.

6. I changed "VA Call center" to be VA health facility, as this is used across pages.

**Comment by aliyahblackmore** [comment]
Hi @laurwill - wanted to move this along a bit. Following our chat with Danielle, we made some updates to Option 1 of the 911/emergency content. 
[Content review of 911 emergency note_AB_10.5.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9718762/Content.review.of.911.emergency.note_AB_10.5.docx)

**Comment by laurwill** [comment]
Thanks for updating, Aliyah! I just made the swap from the crisis line modal link to the 988 number.

@DanielleThierryUSDSVA , did you want to look at this again before we pass off to the secure messaging team?

[Info alert] 
**How do I talk to someone right now?**
**If you think your life or health is in danger,** call 911 or go to the nearest emergency room. 
**If you’re in crisis and need to talk with someone right away,** call 998, then select 1.
**If you have an urgent question for your VA care team,** call your VA health facility.
[Find your nearest VA health facility](https://www.va.gov/find-locations)

**Comment by DanielleThierryUSDSVA** [comment]
This is great, @laurwill @aliyahblackmore!

My only question is should the "How do I talk to someone right now?" be more like "When to get help right away"? I think the goal is to tell folks when they should not use secure messaging but rather get help right now by other means so I think that declarative might work better as the alert header. Thoughts?

**Comment by laurwill** [comment]
Thanks @DanielleThierryUSDSVA ! I agree, the declarative is more direct here.

@megzehn could you give this a copyedit before we pass off to the product team? Thank you!
[Info alert] **When to get help right away**
**If you think your life or health is in danger,** call 911 or go to the nearest emergency room.
**If you’re in crisis and need to talk with someone right away,** call 988, then select 1.
**If you have an urgent question for your VA care team,** call your VA health facility.
[Find your nearest VA health facility](https://www.va.gov/find-locations)

**Comment by RLHecht** [comment]
Closing out this ticket.
