### ISSUE TITLE
Ensure Shared Support team members have access to Platform docs/tools

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#47806]
## User Story
As an accessibility specialist on the Shared Support team, I need to ensure that I have access to the necessary Platform tools/guidance so that I can support the Collaboration Cycle Staging Review.

## Description
Accessibility specialists on the Shared Support team need access to Confluence (where Collaboration Cycle Staging Review guidance is stored) and to the Staging Revew Google Drive folder (where the DraftingTemplate is stored) so that they are able to complete Staging Reviews if/when necessary.

## Impacted Artifacts
[Collaboration Cycle guidance on Confluence](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748860945/Collaboration+Cycle)
[Staging Review Google Drive folder](https://drive.google.com/drive/folders/1u9HVzUn4Id0p1SbzTt8J6z6bSoQLYOud)

## Tasks
- [x] Ask Andrea Hewitt to add Eli, Angela, Tiffany and DK to Platform Confluence
- [ ] Validate access to Confluence:
   - [x] Eli
   - [ ] Angela
   - [x] DK
   - [x] Tiffany
- [x] Add Eli, DK and Tiffany to Staging Reviews Google Drive folder (Angela should already have access) 
   - request submitted. Waiting on confirmation. 
- [x] Validate access to Google Drive folder:
   - [x] Eli
   - [x] Angela
   - [x] DK
   - [x] Tiffany

## Acceptance Criteria
- [x] Shared Support has access to Confluence
- [x] Shared Support has access to Google Drive Staging Review folder

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [ ] Ticket has been discussed as a team at Planning.
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.

**Comment by shiragoodman** [comment]
hey @eli-oat - can you verify that DK and Angela have access to Confluence and the Google Drive folder?

**Comment by eli-oat** [comment]
Sorry for the delay -- chasing this down ASAP.
