### ISSUE TITLE
DraftingTemplate training for Staging Review

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#47807]
## User Story
As the PM for Governance team, I want to train Shared Support on the Staging Review DraftingTemplate so that they can fill in for Brian on the Staging Review, if/when needed.

As an a11y specialist on Shared Support, I want to be trained in the Staging Review DraftingTemplate so that I can help fill in for Brian on the Staging Review/, if/when needed.

Assignee: @shiragoodman 

## Description
DK, Tiffany, Eli and Angela need to learn how to use the Staging Review DraftingTemplate so that they are able to help fill in for Brian in the Staging Review. The purpose of this ticket is to schedule and host a training session so they can become familiar with the tool and guidance.

## Impacted Artifacts
[Staging Review Google Drive](https://drive.google.com/drive/folders/1u9HVzUn4Id0p1SbzTt8J6z6bSoQLYOud)

## Tasks
- [x] Eli to provide dates/times for training session.
   - 2 PM Monday 10/10
   - **2:30 PM Tuesday 10/11**
   - 1 PM Wednesday 10/12
   - 2 PM Wednesday 10/12
- [x] Shira to schedule training session for 10/11
   - [x] invite Brian as optional 
- [x] Training session completed
- [x] Shared Support team members ask any follow up questions

## Acceptance Criteria
- [x] Shared Support has received training on the DraftingTemplate

## How to prepare this issue
- [x] Attach story to appropriate Initiative or Quarterly Tech-Debt Epic.
- [x] Add User Story, description, tasks, and Acceptance Criteria
- [x] Add any [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization).
- [x] Once all above items are checked, add the 'Ready' label.
- [ ] Ticket has been discussed as a team at Planning.
- [x] Ticket has been sized as a team.
- [x] Ticket has been assigned to a Sprint.
- [x] Once assigned to the upcoming or current Sprint, move to the Planned pipeline.
- [x] Once assigned to the upcoming or current Sprint, add assignee and specify Peer Reviewer.
