### ISSUE TITLE
Day of check in content changes as a result of travel pay midpoint review

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#47805]
## Description

As a result of midpoint review for travel pay, we received feedback that impacts the check in app, not just travel pay. Here are the updates for day of check in app. 

## Tasks

- [x] The h1 on the confirmation page needs to end with a period punctuation. You're checked in.
- [x] Update design of the "check in now" box to comply with DS team. Check for resolution here - https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/47567 
    - Screenshot from updated wireframe
    - Update font to be sans-serif
![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/f7b162ee-ca46-4710-9be6-a5efd8030335)
- [x] Although we're following the format for the card from VA DS, we have an inconsistency in terms of font format with another page as shown in the example below (e.g., **Type of care: Primary care** vs **Time:** 9:26 a.m.). The inconsistency needs to be addressed. TLDR here is to unbold the values and keep the titles bold
![Screen Shot 2022-10-05 at 9.31.44 AM.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/3cf30cf3-9bcf-4262-b591-deb999e89bff) ![Screen Shot 2022-10-05 at 9.32.37 AM.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/8dcb5501-fe20-4377-a2f9-8ab63d636aae)

**Comment by kristenmcconnell** [comment]
If and when we refocus our attention to the card design again, then we will want to look at the status within a card documentation that the DS team just added. This design along with the unbold comment from Allison might help us redesign the card to be more in alignment with the DS.

**Comment by loripusey** [comment]
@brianseek this should be unblocked now as @zach-park has finished the wireframe (see [ticket](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/47836))

**Comment by brianseek** [comment]
@zach-park this is ready to validate on stage also here are the screenshots:
![Day-of-check-in--Confirmation.png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/eb3d1e00-3cac-4ed5-b523-fb023e019e6d)
![Day-of-check-in--Appointments.png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/07bcc7cc-9375-4a0e-b830-2aa8483156d8)

**Comment by loripusey** [comment]
LGTM!

**Comment by benbrasso-agile6** [comment]
Looks good

**Comment by zach-park** [comment]
LGTM
