### ISSUE TITLE
[FE] Display Check-in Info when Using Pre-Check-in Link on Day of Appointment but BEFORE Check-in Window

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47813]
## User Story
As a Veteran, when I click on my Pre-Check-in link on the **day of my appointment**, but **BEFORE** the check-in window. because I think that this is how I need to check-in, I would like to see a message that tells me what I need to do to check-in.

## User Flow
- Given I
    - Have a Pre-Check-in link that was sent to me and for which there is still a UUID in LoROTA
- When I
    - Click on my Pre-Check-in link on the **day of my appointment** but **BEFORE** the check-in window (i.e. prior to 30 minutes before my appointment)
- Then 
    - I see the following error message
        - TBD on wireframe

## Tasks
- [ ] Add the new error message
- [ ] Create unit tests
- [ ] Create e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
