### ISSUE TITLE
[BE] Setting up Monitors in VA Gov Datadog

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#47811]
## User Story
As an on-call engineer in CIE team, I want to get alerted in CIE Slack APM channel if any user request fails in production so that I can work on mitigating the issue

Blocked with no access for creating monitor in VAGov Datadog Instance: https://github.com/department-of-veterans-affairs/va.gov-team/issues/47030

## Tasks
- [ ] [BE] Create monitors in vagov datadog instance
- [ ] [BE] Set up alerts to notify in slack apm channel

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by kanchanasuriya** [comment]
Monitors for notifying API latency level issues created.  Will handle error log level monitors in a separate ticket
