### ISSUE TITLE
[FE] Need Help Section Updates for Day-of Check-in

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#47827]
## Release
This will be in a branch separate from the rest of the travel pay work, which is behind a feature flag.

## Description
Update Footer on day of pages to match footer in linked mock.
update footer for check-in confirmation page to have additional travel pay information.
  
## Wireframes
- [abstract](https://share.goabstract.com/6b69924f-904b-4d78-b5a1-4c40ed65e4d2?collectionLayerId=bbf2ae3b-a0fc-4ce5-a4bc-52c0fa60f0af&mode=design) **_insert link to sketch file_**

## Tasks
- [ ] [FE] Update day-of footer with new content
- [ ] [FE] Add additional content for check-in complete page
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [x] Read ticket details and verify that ACs are met
- [x] Review code in PR
- [x] Run branch locally
- [x] Check that new and updated translations use new keys
- [x] Check for hardcoded strings

**Comment by wullaski** [comment]
@loripusey, @zach-park here's screenshots of the changes running locally:

![Screen Shot 2022-10-11 at 11 29 54 AM](https://user-images.githubusercontent.com/2982977/196181623-eb1e2c36-3aac-4bd6-bbb2-17cde89bc184.png)
![Screen Shot 2022-10-11 at 11 04 18 AM](https://user-images.githubusercontent.com/2982977/196181630-1229677d-a2af-4b41-99e2-decad573dbac.png)

**Comment by zach-park** [comment]
@wullaski They look great. I just wanted to be sure that all "Need Help?" should have the content from the first screenshot except the confirmation pages (all three confirmation pages should show the content from the second screenshot). Could you please confirm? Thank you!

**Comment by wullaski** [comment]
@zach-park I just checked the three confirmation pages for the longer content and can confirm it is there. The short content from the first screenshot shows everywhere else. We have unit tests in place to test that functionality as well.

**Comment by zach-park** [comment]
@wullaski , thanks so much!

**Comment by loripusey** [comment]
@wullaski has this been released to production yet?
