### ISSUE TITLE
Current employment not populating in VHA FSR

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#47824]
## Issue Description
VHA has found a case where they can see two employment histories but only the past was present within the FSR PDF.

---
## Tasks
- [ ] Replicate use case
- [ ] Fix to fill current employment

## Acceptance Criteria
- [ ] We show all employment history on PDF 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
