### ISSUE TITLE
[FE] [TECH DEBT] - data persistence and place saving

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#47828]
## Description
Currently when a user reloads the app at any point before completion, they are taken back to the start and none of their answers are remembered. With Travel Pay adding 4 additional answers, we may want to look at ways to persist answer data for a session.

Mark had done a POC that also retained data for the full-auth edit work: https://github.com/department-of-veterans-affairs/vets-website/pull/20673

## Tasks
- [ ] [FE] determine the best way to keep data with session
- [ ] [FE] implement persistence architecture
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
