### ISSUE TITLE
Content of additional information in FSR is getting cut off

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#47821]
## Issue Description
Determine the max character length achievable in this field and specify.

---
## Tasks
- [x] Determine max character length
- [x] Update PDF fill with specification
- [x] Test VBS API submissions with max content

## Acceptance Criteria
- [ ] We accept large bodies of content within additional information
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
VBS testing whether newlines break CSV formatting
