### ISSUE TITLE
Always use SSN for File No field in FSR for VHA

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#47822]
## Issue Description
VHA has requested to use SSN for the file number field as they do not use VA file numbers.

---
## Tasks
- [ ] Update VHA submission to contain SSN for every request
- [ ] Keep VA file number for DMC

## Acceptance Criteria
- [ ] VHA submissions always contain SSN in file number section
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
