### ISSUE TITLE
Other income populating for Veteran & Spouse

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#47820]
## Issue Description
We've noticed instances of the income populating for both a veteran and a spouse when it should just be for the Veteran. This seems to only happen with manually inputted data and has happened when the Veteran doesn't have a spouse.

---
## Tasks
- [x] Determine cause for duplication
- [x] Only show income for Veteran

## Acceptance Criteria
- [ ] We have removed duplicate value from spouse column
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
