### ISSUE TITLE
[Design] Create Final Wireframes for Card Style at Tablet Width

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47836]
## Tasks
- [x] Create final mockups with callouts 
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [ ] UI review meeting with product/UX team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.

**Comment by zach-park** [comment]
@loripusey @kristenmcconnell @benbrasso-agile6 @kellysmith1008 @ytsaoca 
The wireframe is ready for product/UX review: 
https://share.goabstract.com/1f908534-6f25-4f79-8ea6-66a69cdbb7b6?collectionLayerId=0d1a6176-edf6-4c27-b726-df6143829bfe&mode=design

**Comment by loripusey** [comment]
Looks great and well laid out!

**Comment by loripusey** [comment]
@zach-park So, is the only difference from what we have now is the drop shadow?

**Comment by loripusey** [comment]
Looks good to me

**Comment by benbrasso-agile6** [comment]
Added a couple comments for consideration https://app.abstract.com/projects/ab30c34e-e2f9-4d3e-bb96-3b683b006c24/branches/d66b288e-e77e-40ca-8cfe-5f2df811f4be/commits/8f4c19138d11f4fd06c754af7efb1a42442b4398/files/585436fe-2120-45f4-b4f7-fbae01d258d9/layers/00960AB5-9C2A-4E5A-AD8D-8B08C880469C?collectionId=b9470981-9390-403e-aa85-29f94971518b&collectionLayerId=0d1a6176-edf6-4c27-b726-df6143829bfe&mode=design

Thanks

**Comment by zach-park** [comment]
@benbrasso-agile6 @loripusey , just had another idea that I'm running by the DS team at the moment.  Thank you.

**Comment by loripusey** [comment]
Wasn't the point of this ticket just to get our wireframes to match the DS component specs?
@zach-park @benbrasso-agile6

**Comment by zach-park** [comment]
@loripusey Yes, you're right.

**Comment by loripusey** [comment]
@zach-park are we done with the wireframes so that @brianseek can do his ticket or do we need to wait until you check with the DS?

**Comment by kristenmcconnell** [comment]
@zach-park I added one comment in about the width of cards.

**Comment by zach-park** [comment]
@kristenmcconnell , could you include the link to the source? I had an additional follow-up question. Thank you!
