### ISSUE TITLE
FE | Profile | DD | Fiduciary Flag Needs to Gate All of Profile

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#47841]
## Background

Currently if a user is flagged with a deceased/fiduciary/incompetent flag they are unable to access the Direct deposit section of their account. However, we should be blocking access to the rest of the Profile site since any changes made won't actually get updated when this flag is in place.

More background can be found here:

> VA Profile currently blocks this information from getting saved as follows.
> From the [#va-profile Slack on 5.27.20](https://dsva.slack.com/archives/C7TE0PFTL/p1590608988100):
>Joshua Lindsey Today at 3:49 PM: @Samara (She/Her) - just another view to make sure that the fudiciary scenario response is complete. If VBA (VBA Corporate) has a person identified as having a fiduciary. VA Profile will not update the VBA Corporate record. This logic is bi-directional, VA Profile also does not accept those changes to that record from Corporate. DB either. Example, If the address is sent from va.gov to VA Profile. VA Profile will accept the address but will exclude it from what is shared with VBA Corporate.

## Tasks
- [x] If a fiduciary flag is in place and DD access is prevented, apply this same logic to all features in the profile 
- [x] New mocks here: ([Desktop](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/a/PG4Pm2j) and [Mobile](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/a/g09lryk)) 
 - [ ] Include TTY in the aria label
- [x] Conduct Unit tests 
- [x] Run E2E tests covering current code and regression
- [x] All axe checks pass
- [x] Notify PM if this needs to be deployed to Staging behind feature flag
  

## Acceptance Criteria
- [x] Complete all unit testing
- [x] End-to-end tests showing 0 violations
- [x] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [ ] Confirm PM has opened a new ticket to deploy changes to Production using feature flag, if needed

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)? PM or Design
- How can this work be validated? Staging
- What updates need to be made (e.g. product outline, use cases, contact center guide)
     - CC guide
     - Use Cases
     - Product Outline

## Associated Tickets
- #48151

## Staging User
-  Vet61

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
Here is the present day mock shown when we get a fiduciary flag while user tries to access direct deposit:

![Screen Shot 2022-11-07 at 2.08.59 PM.png](https://images.zenhubusercontent.com/5fb57aafa11eae0592a15cb1/c08dc461-a19e-498c-8368-f84446b5c8c4)

**Comment by adamwhitlock1** [comment]
@SKasimow the PR for this has been merged and is ready for validation. I have confirmed the functionality on staging myself with test users 0, 61, and 65.

there is a feature toggle in place for this and it is named `profile_block_for_fiduciary_deceased_or_incompetent`

![Screen Shot 2022-11-28 at 10.32.00 AM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/44af7000-0a9f-4172-a696-752177278191)

**Comment by SKasimow** [comment]
@adamwhitlock1 - worked as well for me.

QQ - I noticed that the message here has "dashes" instead of the words "through" and "to" as in the military alerts John is working on. If making these changes doesn't require you to spin up a new PR, I'll confirm that the changes should be made here as well.

If it is another PR, I'll just note it as backlog item.

**Comment by andaleliz** [comment]
@adamwhitlock1 can you please let me know when this will be on prod? I'll publish the new use case docs once that happens. Thanks!

**Comment by SKasimow** [comment]
There's a ticket in the backlog to review messages for consistency. May be able to have design work on that in next sprint

**Comment by adamwhitlock1** [comment]
Going to push this to prod now.

**Comment by adamwhitlock1** [comment]
Checked in prod with my account and had @tmitchellgcio also check his prod account and both are loading, so we can at least assume on production that accounts without the flag are definitely not gated. Will close this now.
