### ISSUE TITLE
Add messaging on Contact Us page about Ask VA being down

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#47846]
## Issue Description

Ask VA is currently down and there's no estimate of when it will be working again. We need to add messaging on our [Contact us](https://www.va.gov/contact-us/) page to alert users. 

We need to work with Chante and the contact center team on this.

## Tasks
- [x] Create alert content for Contact Us page (Danielle)
- [x] Add to Drupal (Laura)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Messaging about Ask VA is on live site

**Comment by laurwill** [comment]
Update: We removed the entire Ask VA section from the Contact Us page for now. 

We're not sure if messaging about the outage will be necessary — waiting to see if the Ask VA team can put up outage messaging on the Ask VA site instead.

**Comment by laurwill** [comment]
Hi @megzehn ,
Small updates to 2 pages ready for you to copyedit and prepub — just hold on pushing live till I confirm one thing:
- Contact us (added AVA alert and replaced chatbot alert with new H2): http://preview-prod.vfs.va.gov/preview?nodeId=8472
- Ask VA R&S page (added AVA alert and removed AVA CTA link): http://preview-prod.vfs.va.gov/preview?nodeId=34313

Noting that Danielle got AVA team's approval for the alert language, and Ian and Luciana from chatbot team approved the move from alert to H2.

**Comment by laurwill** [comment]
Thanks so much Megan! I made one little tweak after chatting with Beth and then published the alert and the 2 pages.

**Comment by RLHecht** [comment]
This is live. Closing ticket and will open another one for the backlog for removing the alert when Ask VA is up again.
