### ISSUE TITLE
MDT- Accessories - select an item(s)

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#4786]
## User Story:
As a Veteran, I need to be able to select & unselect  an accessory item(s) so that I can choose my item(s).

## Tasks
- [ ] create a check box that displays a selected item
- [ ] The check box should be able to be selected and unselected
- [ ] veterans can select up to 1 or more items
- [ ] Determine Ajax calls as need 
- [ ] write unit test for above items

## Acceptance Criteria:
Given that the veterans accessory items are displayed
when the veteran see the item(s) they want
Then the selector (the checkbox)  on the screen will indicate (checked) selected.

## Next steps
- Confirm happy path 

## Blocker
- n/a
