### ISSUE TITLE
MDT- Accessories - Display Table

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#4787]
## User Story:
As a Veteran, I need to be able to see all my previous accessory item(s) so that I can choose my item(s).

## Tasks
- [ ] create a table to displays a past 2 year accessories item.
- [ ] Table headers mach that from the DLC document and requirement doc
- [ ] unit test the code for the button is correct.
- [ ] determine Ajax calls as need 
[https://app.zenhub.com/files/133843125/91474d7f-2ae7-4fe3-8620-ad816d2da7ea/download](https://app.zenhub.com/files/133843125/91474d7f-2ae7-4fe3-8620-ad816d2da7ea/download)

## Acceptance Criteria:
Given that the veterans has logged in successfully
When the accessory page is displayed
Then the veteran should see all their accessories that were ordered from the last 2 years

## Next steps
- Confirm happy path 

## Blocker
- Back-end

**Comment by mr0sari0** [comment]
I am working on this ticket
