### ISSUE TITLE
[FSR] Add quick reference guide for income and expenses

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#47886]
## Issue Description

VHA SME, David Adcock suggested we add a link to the **[Quick Reference Guide: Income and Expenses](https://www.va.gov/healthbenefits/resources/publications/IB10-454_Reference_Guide_Income_and_Expenses.pdf )** on the FSR online experience to provide Veterans with additional clarity on what types of income and expenses the VA is looking for when reviewing an FSR submission. 

---
## Tasks
- [x] Design team to review and mock up potential location to share with stakeholders. Share with @denisecoveyduc and if approved we will integrate it into the experience. 
- [x] Create PR with intro page changes

## Acceptance Criteria
- [x] Design mockup including link
- [ ] Intro page with changes has been merged into production
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mgleo** [comment]
https://www.va.gov/healthbenefits/resources/publications/IB10-454_Reference_Guide_Income_and_Expenses.pdf

**Comment by denisecoveyduc** [comment]
1/14/25- Confirming that yes this information is up to date and should be added to the portal to help Veterans understand what types of income and assets the VA is looking for when reviewing an FSR submission. Please procced to provide a link to the portal.

**Comment by josephrlee** [comment]
Great, we can bring this into the next sprint!

cc: @Tom-Davis @mgleo

**Comment by josephrlee** [comment]
@denisecoveyduc, I looked at where this could potentially go, and I think the intro page might make the most sense. 

Here's a [mockup of what it could potentially look like:](https://www.figma.com/design/ea8baIDr09ncgr1P4Rfh8i?node-id=2503-64845#1109918126) 
<img width="601" alt="Image" src="https://github.com/user-attachments/assets/2dc5c881-bd70-48b3-8db2-f7ae2c99f171" />

I've added additional context on the figma comment. 

cc: @charlottecesana @mgleo

**Comment by josephrlee** [comment]
@denisecoveyduc, here's an updated draft that's more accurate from a content standpoint:  
<img width="615" alt="Image" src="https://github.com/user-attachments/assets/b9094141-f7e1-4934-b6f2-e150196da375" />

**Comment by josephrlee** [comment]
@denisecoveyduc, thanks for the response! I'll go ahead and get a PR for these changes drafted and also let UX team know that we want to test the "Why do we ask for this information" alert on mobile eventually.

**Comment by josephrlee** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/34479) is up for review! 

cc: @denisecoveyduc @Tom-Davis @mgleo @dhill802
