### ISSUE TITLE
MDT- Confirm address step- primary address displayed

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#4788]
## User Story:
As a ___Veteran_______, I need ___to be able to see my current address___ so that I can ____choose my where I would like my items sent.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] displays a current address
- [ ] Address: Residence street, and #, city, state, zip
- [ ]  Unit test the code
- [ ] Make backend calls as need 

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
Given that the veterans is logged in
When the veteran is asked to confirm address
Then their primary residency is displayed

## Next steps
- Confirm happy path 

## Blocker
-tbd
