### ISSUE TITLE
Update Pay.gov details for copays 

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#47890]
## Issue Description
Update information presented to Veterans when a link to pay.gov is available on the debt portal.

## Details 
Veterans can pay their copay bills online via pay.gov. We provide a link on the portal for Veterans to link over to **[pay.gov](https://www.pay.gov/public/home)** for their information. The current state (see below) has limited information and doesn't provide Veterans with enough information for them to clearly understand what information they will need once they log in.  It is also not clear to that this site is for **[copay bills](https://www.pay.gov/public/form/start/25987221)** and not benefit debts at this time. 

# Current State on the Debt Portal

> ![image.png](https://images.zenhubusercontent.com/5f7f60ca14e26c658f77b9f5/0690f614-3c67-4d3d-93e7-d5105245f6b5)

# pay.gov Information
## Information to consider including in updated copy. 
1. Veterans can pay medical care and prescription copayments billed on their monthly statements for services provided by a VA medical center or clinic.on pay.gov.
2. Incorrect information or wrong form used will delay payment posting.
3. Details required to complete form and submit payment including:
- Verify Veteran name
- The VA account number and payment amount 
- Accepted Payment Methods: Bank account (ACH) and Debit or credit card

## Reference Site
[pay.gov URL](https://www.pay.gov/public/home)
[Copay Link from pay.gov homepage](https://www.pay.gov/public/form/start/25987221)

## Information Veterans  need to submit on pay.va.gov (for Reference)
> ![image.png](https://images.zenhubusercontent.com/5f7f60ca14e26c658f77b9f5/ba92194d-e1ac-4691-bb7d-6e9c01a6171c)

---
## Tasks
- [ ] Mockup designs with new content 

## Acceptance Criteria
- [ ] Once approved, hand over to FE for development
---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
Talking to Jill it sounds like we need clarity on what information we need to present to Veterans and where that information is and how we make it available to the Veteran. 

Jill said...

> The account number will change for each station.  So a Veteran would have a statement in Minneapolis VAMC, with an account number.  They need to use that account number to make a payment for bills at VAMC Minneapolis.  If they also have bills at Miami VAMC, they will have a statement with a different account number.  They need to use that number to make their Miami VAMC payment. If they are using Huron at those locations, they will have additional account numbers.

**Comment by HeatherRienks** [comment]
@denisecoveyduc - will follow up with Jill.
