### ISSUE TITLE
SME feedback to incorporate for education rates pages

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#47891]
## Issue Description
I received SME feedback from Cinda Quattrini. We'll need to make updates across the pages based on her feedback. Here's the list:

<h2>On both the Fry rates page (node 49549) and the Post-9/11 GI Bill (Chapter 33) rates (node 1009) pages:</h2>

Preview links: 
Post-9/11 GI Bill rates: http://preview-prod.vfs.va.gov/preview?nodeId=1009
Fry rates: http://preview-prod.vfs.va.gov/preview?nodeId=49549

_First, clarify with Cinda that we are correct to make all these changes to Ch. 33 as well as Fry. Ch. 33 is the only other place we have "all tuition and fees"_

1/
- In the first accordion, called "Tuition and fees," we need to change "all tuition and fees" where it appears in the first bullet point to "net tuition and mandatory fees."

- _Question for Cinda:_ : For the other 5 bullet points, do we need to word it similarly? Or what did she intend where she highlighted "actual net cost"

- Flip the order of the sentences about private vs public school. In other words, move the last sentence for the last 3 bullet points: "We'll pay all in-state tuition and fees." (and delete, as she indicates, "At a public school") * Check with Cinda to make sure this is a good change.*

- _Question for Cinda:_ We need a definition/more info on "mandatory fees."

- [x] Check here when "all tuition and fees" is updated for that first bullet. (KF)
- [x] Check here when the private/public school edits have been made for the 3 bullets. (KF)

2/ Accelerated pay is only available for Chapter 30 (MGIB-AD) and Chapter 1606 (MGIB-SR). So, in the stack of 5 accordions on both Post-9/11 and Fry, open the last accordion, "Added payments." Remove this text: 

**If you’re enrolled in a high-technology program,** you may be able to get a single higher payment to help cover the cost of your program.
[Learn more about accelerated payments for high-technology programs]

- [x] Check here when this text has been removed from both pages.(KF)

3/ Remove the tuition assistance top-up text.

It's in the "Added payments" accordion. You'll need to remove the bullet point, which will leave us with only one bullet. This isn't our style. So work the Yellow Ribbon Program into the preceding sentence. You'll also have to remove the tuition assistance top-up text link.

- [x] Check here when this update has been made on both pages. (KF)

4/  _Question for Cinda:_ (I don't understand this--from the first part of her email): "Fry and 33 can get paid based on the remaining net T&Fs after the amount paid by tuition assistance is deducted."

<h2>On both the MGIB-AD page (node 5355) and MGIB-SR page (node 5449):</h2>

Preview links:
MGIB-AD: http://preview-prod.vfs.va.gov/preview?nodeId=5355
MGIB-SR: http://preview-prod.vfs.va.gov/preview?nodeId=5449

1/ Move the co-op training info under the institutions of higher learning H3. 

On MGIB-AD: Create 2 new H4s (and on MGIB-SR, you'll only need to create the co-op training H4 since the in-state tuition info isn't on that page): 

**H4: If you're in a co-op training program**

If you’re part of a full-time approved college or university co-op training program, we'll pay you up to $2,210 each month to help you cover some of your costs (like books, tuition, and housing). The amount we’ll pay depends on the type of approved school you’re attending.
[Learn more about co-op training]

**H4: In-state tuition rates**
You may be able to get in-state tuition rates at a public school even if you haven't lived in the state where the school is located. [Learn more about in-state tuition rates]

Place the "Learn more about getting an undergraduate or graduate degree" text link before the new H4s. Let's see how that works. 

- [ ] Check here when co-op training has been relocated and new H4s created. (KF)

2/ _Question for Cinda:_ In the first section after the intro paragraph called “How we determine your rate,” there’s a bullet that says, “If you’re getting on-the-job training, correspondence training, or flight training…” I added “co-op training.” You’ll see that addition when you click the preview links. Am I right to include that? 

3/ _Question for Cinda:_ On MGIB-AD only, should the section of content called "MGIB-AD rates for Vietnam era Veterans with remaining entitlement" stay on the page?

<h2>On Chapter 35 rates page (node 5496)</h2>

_Question for Cinda:_ Ask Cinda if we should take out "For farm co-op training," "For non-farm co-op training," and SRT sections altogether. Or should move them to nest under IHL or keep anywhere else on the page? 

<h2> $600 Buy-up</h2>

Show Cinda this page. Discuss whether we should move the info to the Post-9/11 GI Bill page. 

---
## Tasks
- [ ] Edit per above notes.
- [ ] 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by katherine-fung** [comment]
### Post-9/11 GI Bill rates and Fry rates pages

current Post-9/11 GI Bill rates
http://preview-prod.vfs.va.gov/preview?nodeId=1009

2022 Post-9/11 GI Bill rates
http://preview-prod.vfs.va.gov/preview?nodeId=49728

current Fry Scholarship rates 
http://preview-prod.vfs.va.gov/preview?nodeId=49549 

2022 Fry Scholarship rates
http://preview-prod.vfs.va.gov/preview?nodeId=49719 

**changes**

1st accordion ("Tuition and fees")
- replaced "tuition and fees" with "net tuition and mandatory fees"
- removed "trade school" from foreign school bullet point
- removed distinction between private and public schools in bullet points

5th accordion ("Added payments") 
- added work study info 

Related links 
- updated link summary for GI Bill Comparison tool 

### MGIB-AD rates pages

current MGIB-AD rates page
http://preview-prod.vfs.va.gov/preview?nodeId=5355

2022 MGIB-AD rates page
http://preview-prod.vfs.va.gov/preview?nodeId=49445 

**changes**

- removed "co-op training" from "How we determine" section
- removed "For co-op training" rates section 
- removed section for Vietnam Era Veterans with remaining entitlement

Related links 
- updated link summary for GI Bill Comparison tool 

### MGIB-SR rates pages 

current MGIB-SR rates page
http://preview-prod.vfs.va.gov/preview?nodeId=5449

2022 MGIB-SR rates page
http://preview-prod.vfs.va.gov/preview?nodeId=49449

**changes**

- removed mention of "co-op training" from "How we determine" section
- removed "co-op training" rates section 

Related links 
- updated link summary for GI Bill Comparison tool 

### DEA rates pages 

current DEA rates page
http://preview-prod.vfs.va.gov/preview?nodeId=5496 

2022 DEA rates page
http://preview-prod.vfs.va.gov/preview?nodeId=49484 

**changes**

- removed mention of farm and non-farm co-op from "How we determine your rate" 
- removed farm and non-farm co-op sections

**Comment by bethpottsVADEPO** [comment]
@mnorthuis @heyjoni tagging you here on this comment since I've been digging into something Mikki raised when she was putting together her IA document with guidance for Education rates--whether we should also create rates pages for other programs/scholarships than the main program benefits. All the programs/scholarships listed here have the same rates as Chapter 33 (Post-9/11 GI Bill). Wanted to get your gut check on having 4 additional pages that all repeat the Chapter 33 rates (Fry, STEM, VET TEC, and TOE). I don't think that particularly matters as the audience for each is unique, but I wanted to pose the question and see if you have thoughts or concerns. Thanks! @RLHecht, @katherine-fung, and @laurwill for awareness

Summarizing details for STEM, VET TEC, and TOE:
We discussed with Cinda whether to also create rates pages for these benefits--she thought we should address these somehow:

## Edith Nourse Rogers STEM Scholarship
https://www.va.gov/education/other-va-education-benefits/stem-scholarship/
**Summary:** This scholarship provides up to 9 months (or $30,000) of benefits for training in high-demand fields. 
**Audience:** It's for Veterans and dependents using the Post-9/11 GI Bill or Fry Scholarship.
**Same rates as this program:** Chapter 33
**Differences, if any, from Chapter 33:** ASK CINDA AND JODIE

Current language on the tier 1 page:

### What benefits can I get with this scholarship?
If we approve your application, you’ll get up to 9 months of added benefits (or $30,000, whichever comes first). Your monthly benefits will be the amount you received through the Post-9/11 GI Bill or Fry Scholarship.

### What are the scholarship rates for private schools?
The Chapter 33 rates for private or foreign schools apply to the STEM scholarship as well. We update these rates each academic year.
[Review current education benefit rates] 

## Veterans technology education courses
https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/
**Summary:** With VET TEC, you can get:

- Tuition for a full-time high-tech training program
- Money for housing during your training

**Note:** If you’re on active duty, you’re not eligible to receive a housing allowance.

**Audience:** service members and Veterans
**Same rates as this program:** Chapter 33
**Differences, if any, from Chapter 33:** ASK CINDA AND JODIE

Current language on the tier 1 page:

**What benefits can I get through this program?**
With VET TEC, you can get:

- Tuition for a full-time high-tech training program
- Money for housing during your training

**Note:** If you’re on active duty, you’re not eligible to receive a housing allowance.

If you attend your training program in person, your housing stipend will be equal to the monthly military Basic Allowance for Housing (BAH) for an E-5 with dependents. This is based on the zip code where you attend your training.

If you participate in an online program, your stipend will be half of the BAH national average for an E-5 with dependents.

**Note:** If you don’t attend a training for a full month, we’ll prorate your housing payment for the days you train.

## Transfer your Post-9/11 GI Bill benefits
https://www.va.gov/education/transfer-post-9-11-gi-bill-benefits/
http://preview-prod.vfs.va.gov/preview?nodeId=44698
**Summary:** If you’re a spouse or dependent child of a Veteran or service member, you may be able to use transferred Post-9/11 GI Bill benefits for your education and training.
**Audience:** spouses and dependent children
**Same rates as this program:** Chapter 33
**Differences, if any, from Chapter 33:** ASK CINDA AND JODIE

Current language on the tier 1 page:

**What benefits can I get?**
You may be able to get help paying for:
Tuition
Housing
Books and supplies
Test fees

**Comment by heyjoni** [comment]
Thanks, @bethpottsVADEPO. I think creating the additional 4 pages is okay given that each audience is different. Having these individual pages will make each program easier to find via search or navigation.

**Comment by bethpottsVADEPO** [comment]
Thanks @heyjoni ! I'll let you know how we proceed with this after we discuss with our stakeholders this week. What I'd like to do is roll out these additional 3 pages as a "rates launch phase 2" in December so we don't delay getting this first chunk of main program rates pages out the door. Anyway, I'll circle back with you about this.

**Comment by bethpottsVADEPO** [comment]
@RLHecht @katherine-fung @megzehn Questions for our next meeting with Cinda and Jonie:
- Any update on the $600 Buy-Up program and whether this is still active?

Need feedback from her on the following:
- Both MGIB pages
- Post-9/11 GI Bill program page: Review together the language for MHA. Is it accurate?
- We'd like to create separate pages for STEM, VET TEC, and TOE. If we clone the Post-9/11 GI Bill page as we did to create the Fry page, what tweaks will we need to make for each? Specifically related to MHA.

**Comment by katherine-fung** [comment]
updating to note that copy editing for the education rates pages is happening in this ticket: 

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/43553

**Comment by RLHecht** [comment]
Work completed in various other rates tickets. Closing!
