### ISSUE TITLE
EKS Upgrade to 1.22

### ISSUE THREAD

**Issue by little-oddball** [department-of-veterans-affairs/va.gov-team#47909]
## Problem Statement 
Amazon has a defined strategy and release plan for their EKS Kubernetes product which is defined [here](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar). An impact derived from this strategy is the Platform team needs to be aware of what version of Kubernetes they are running as well as understand when a version being run reaches End of Support. This awareness is important due to Amazon’s policy of automatically upgrading any clusters that are not running a current version and the potential negative impact this could have on the platform.

Due to this, the Platform team looks at upgrading the control plane on a regular interval to be a critical on-going support item. The exact schedule and timing should be driven by the Kubernetes release timeline ( provided in the link above ) which is currently on a ~6 month cadence.

## User Impact
This could impact all users as if the work is not performed AWS will automagically upgrade the control planes regardless of potential breakage. It would block all users from accessing the platform/

## Where was this problem reported?
This was a problem that has been being tracked by the Infrastructure team.

## What do we not know about the problem space?
We know quite a bit about the problem is it is well documented in the AWS documentation, which is linked above. The area where more discovery might be needed are around the actual performing of the updates and seeing what the LOE is and if/what areas of efficiency we can gain. Additionally, in this [documentation](https://vfs.atlassian.net/wiki/spaces/~623dda1d761efb0069cef710/pages/2381643777/EKS+AWS+Control+Plane+and+Supporting+Items+Upgrade) there is some potential of alternate proposals to approach possibly short or longer term.

## What (if any) research or discovery has been done?
Mentioned and referenced above.

## What is the acceptance criteria?

- [x] Platform EKS/AWS clusters are current with version that is within End Of Support.
- [x] Platform clusters are running as expected with no issues related to upgrading
- [x] Documentation is created that aids in outlining (step by step as it makes sense) the specifics of the process
- [Link to board where work was tracked](https://app.zenhub.com/workspaces/eks-cluster-upgrade-122-63ac666ee48f24b9480ed2ca/board)
- [Original plan proposal](https://vfs.atlassian.net/wiki/spaces/~623dda1d761efb0069cef710/pages/2381643777/EKS+AWS+Control+Plane+and+Supporting+Items+Upgrade)
- [Implementation details](https://vfs.atlassian.net/wiki/spaces/~623dda1d761efb0069cef710/pages/2381643777/EKS+AWS+Control+Plane+and+Supporting+Items+Upgrade)
- [x] The process followed to upgrade this should be documented  from 1.21 to earliest supported version. (1.22) 
- [x] A plan for semi-automation that will get us from 1.22 to 1.23 by May when 1.22 is EOL. 

## TODOs
- [ ] Convert this issue to an epic

**Comment by ph-One** [comment]
Prior epic created that may provide more information

https://app.zenhub.com/workspaces/platform-infrastructure-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/va.gov-team/32804

**Comment by ph-One** [comment]
https://vfs.atlassian.net/wiki/spaces/OT/pages/1549041761/Infrastructure+Roadmap+WIP there are also some EKS items from initial Q4 planning that could be pulled into this

**Comment by mchelen-gov** [comment]
- What is our current EKS version?
- What is the target EKS version?
- Is this a blocker for https://github.com/department-of-veterans-affairs/va.gov-team/issues/46779 ?

**Comment by little-oddball** [comment]
@mchelen-gov - I don't have all the answers but do have a few...

> * What is our current EKS version?

1.21

> * When is End of Support for our current version?

Referenced in AWS documentation above - 2/15/2023

> * What is the target EKS version?

We should discuss but would say ideally 1.24 (which would give us a year)

> * Is this a blocker for [Move Vets-api to EKS #46779](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46779) ?

This does not block #46779. However this would be required to ensure VA.gov is up and functioning.

> * What applications and environments would be impacted?
> * What applications are currently running in EKS production?

@ph-One - can you weigh in on the 2 items above and any other additions or corrections from what I have added.

**Comment by BillChapmanUSDS** [comment]
It seemed from some of the slack thread responses that there was a sense of "we don't know what will break" and each app may use deprecated or changed EKS APIs.   

 
- What is the current effort or existing documentation that will identify these concerns? 
- Is there an existing EKS running for integration and app compatibility testing at the latest or recent point releases of EKS? If no, what do we need to do to help make that happen?

**Comment by ph-One** [comment]
@BillChapmanUSDS I have put together a list of all the applications and services that need compatibility checks that can be leveraged. The EKS clusters were largely "build during take-off", which is a big part of why former-infra wanted a rewrite to address missed use cases, such as having _n_ clusters and being able to dynamically spin them up [for many reasons, including testing out Kubernetes _Next_].

Let me get back to you about spinning up a new cluster. That said, there are tools that you can do initial testing with, such as `kubeconform`. It will test a manifest against the API server spec of any version. It will not work with CRD's iirc, which we use a lot of, but it's a start.

**Comment by little-oddball** [comment]
> The EKS clusters were largely "build during take-off", which is a big part of why former-infra wanted a rewrite to address missed use cases

@ph-One @BillChapmanUSDS - And to be clear, that work never got prioritized to the level where we were able to take it on in the previous setup. I would suggest if this is desired we should re-surface those tickets through the CoP, get them refreshed and we can get them onto the PO board for Bill and other OCTODE to weigh in on.

**Comment by andreahewitt-odd** [comment]
@ph-One @little-oddball Can you link the work for this to this project?

**Comment by andreahewitt-odd** [comment]
@little-oddball Can you check the AC and make sure this doesn't have to be broken into another project too? Or break out the other project if it needs to

**Comment by andreahewitt-odd** [comment]
https://app.zenhub.com/workspaces/eks-cluster-upgrade-122-63ac666ee48f24b9480ed2ca/board
