### ISSUE TITLE
Create content for last step in education wizard

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#47907]
## Issue Description
After talks with Tammy Hurley, we may need to provide new content for the last step in the education wizard found on the [how to apply](https://www.va.gov/education/how-to-apply/) page. 

If a user answers no to all the questions provided when , we need to determine what info we should be giving the user and where to point them. Currently we are sending users to apply for a TOE but that's not correct. 

Because this content is in a wizard, we'll need to provide Public Websites with the final approved content for them to add.

## Tasks
- [ ] Create content for final step in widget
- [ ] Review (Laura)
- [ ] Send to Tammy for stakeholder approval
- [ ] Copyedit
- [ ] Provide Public Websites with final approved content (Laura/Randi)

## Acceptance Criteria
- [ ] Wizard is directing users to the right place if they've answered no to all the questions
