### ISSUE TITLE
[FE] Payment info v2: Update secondary link logic on outstanding debts when an error occurs

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#47902]
## Background
While running through test cases for payment info v2, I noticed that we aren't handling secondary links consistently between Outstanding debts and Benefit payments when an error occurs.

Per the designs, when there’s an error in Outstanding debts, we show the secondary link for “Learn about VA debt” as a  right-aligned link, across from the error:
![Screen Shot 2022-10-05 at 3 56 10 PM](https://user-images.githubusercontent.com/45603961/194157857-3ebd8ef4-381d-4c66-b9c7-9d38715fa93e.png)

But when there's an error in Benefit payments, we show the two secondary links for "Manage your direct deposit information" and "View your payment history" as left-aligned, immediately below the error:
![Screen Shot 2022-10-05 at 3 56 21 PM](https://user-images.githubusercontent.com/45603961/194157904-788ecaf2-59be-489a-bdef-5a9fdd3cacc8.png)

## Solution 
Update logic in Outstanding debts section so that when an error occurs _and there is no additional info to show in the section_ (i.e. the user has no copays or no debts, depending on which API failed triggering the error), left-align the secondary link below the error message. Leave the Benefit payments section as is.

## Tasks
- [ ] Update conditional logic around secondary links in the Outstanding debts section
- [ ] Test
- [ ] Work with PM or Design to create scenarios for validation

## Acceptance Criteria
- [ ] When an error occurs on the debts api and the user has no copays to show, then the secondary link is left-aligned below the error message
- [ ] When an error occurs on the copays api and the user has no debts to show, then the secondary link is left-aligned below the error message
- [ ] When an error occurs on the debts api and the user _has_ copays to show, then the secondary link is right-aligned across from the error message and copays card
- [ ] When an error occurs on the copays api and the user _has_ debts to show, then there is no secondary link at all

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ PM/APM
- _How can this work be validated?_ Work with FE dev to trigger errors and validate behavior in acceptance criteria

**Comment by tmitchellgcio** [comment]
I've been trying to research and reproduce this and I can't. Can you tell me what test user this is?
![Screenshot 2022-10-07 135534.png](https://images.zenhubusercontent.com/60ad368786f922a382c8b16b/518fe8fa-7843-44e4-8bc3-fa1f18e02b87)

**Comment by tmitchellgcio** [comment]
Closing as after a lot of testing it's working as intended as is
