### ISSUE TITLE
SalesForce Sub Category Product Mapping

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/va.gov-team#47900]
## Issue Description
Utilizing the [VFS Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory), we will map as many products as possible to existing SalesForce Sub Categories. We will also identify gaps and propose sub category creation if necessary.

---
## Tasks
- [x] Identifyactive VFS Products
- [x] Map SalesForce Sub Categories to active VFS Products

## Acceptance Criteria
- [x] Product mapping document will be created
- [x] As many of the existing sales force sub categories will be mapped
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
[Here is a document](https://docs.google.com/spreadsheets/d/15j1WKu2bl134FD81sVifp1_CMCAaKr-5JN4C5IhfgyI/edit#gid=0) outlining existing VFS Products, their status and PMs.

There are only 31 products that are currently Live (not counting MVPs) and have a VFS PM assigned. These 31 products are spread over 12 VFS PMs and 5 OCTO Crews.

**Comment by ianMcCullough-ob** [comment]
[Mapping doc](https://vfs.atlassian.net/wiki/spaces/Contact/pages/2419359848/VA411+Sub-Category+and+VFS+Product+Mapping)
