### ISSUE TITLE
MDT- Prosthetic socks - display table

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#4791]
## User Story:
As a Veteran, I need to be able to see all my previous prosthetic sock item(s) so that I can choose my item(s).

## Tasks
- [ ] create a table to displays a past 2 year sock items.
- [ ] Table headers mach that from the DLC document and requirement doc
- [ ]  Determine Ajax call
- [ ] create unit test for items above

## Acceptance Criteria:
Given that the veterans has logged in successfully
When the sock page is displayed
Then the veteran should see all their sock that were ordered from the last 2 years

## Next steps
- Confirm happy path 

## Blocker
-Back-end

**Comment by mr0sari0** [comment]
I am working on this ticket
