### ISSUE TITLE
BQ Cost Analysis

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#47918]
## Issue Description
Our BQ bills have increased significantly since ~Dec 2021.  Why?  What changed then in our BQ environment that is resulting in this huge jump in monthly cost?  

[BQ Report](https://files.slack.com/files-pri/T1ZD0UBMZ-F040TCB0PJ8/image.png)

The cost seems to be based on the number of calls to the data per day or queries being ran per day.  It goes off data storage, querying and streaming, storage is super low so it has to be either querying on streaming
---
## Tasks
- [ ] Get access to BQ data tables and reports
- [ ] Analyze data to determine what was introduced in Q4 of last year.  (2 things to think about are Standardized Dashboards were released and Product Directory work by the QA team began)
- [ ] Identify the cost factors are 
- [ ]  Determine what if any actions can be taken to lower (it may just be a growing data warehouse?)

## Acceptance Criteria
- [ ] When we determine what is driving the changes and what actions we may take based on learnings.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
