### ISSUE TITLE
[UX][Product] Update Test Cases

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47912]
## Tasks
- [x] Update and/or add to our Test Cases GitHub [document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/qa/test-cases.md) so that they are up-to-date as of the creation of this Epic
- [x] Validate with UX
- [x] Create a Shared-Support-QA Test Plan ticket ([reference](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/engineering/qa/manual-ui-testing-process.md))

## Acceptance Criteria
- [x] Test case are up-to-date with the Epic (& production)
- [x] Shared-Support-QA Test Plan ticket has been created

**Comment by loripusey** [comment]
https://dsva.slack.com/archives/C02GXKL8WM6/p1666183165876539
