### ISSUE TITLE
Bug Fix - Reverting use of VA Modal back to Modal in  SessionTimeOut Component. 

### ISSUE THREAD

**Issue by acaruso-oddball** [department-of-veterans-affairs/va.gov-team#47924]
## Issue Description
Use of VA-Modal has caused bug on VA.gov platform.
![image.png](https://images.zenhubusercontent.com/62bb44b0333e66b3ca2ce7ec/f9c9b8b7-cb22-41fc-a98c-0155c59e5b6c)

## Tasks
- [ ] Revert VaModal back to Modal.
- [ ] Report bug to Design System team.

## Acceptance Criteria
- [ ] When SessionTimeOut model is in use, it opens an actual modal, as intended.
