### ISSUE TITLE
Remove Ask VA warning alert from Contact us page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#47921]
## Issue Description
Once Ask VA is back up, we need to remove the warning alert we added to the [Contact us](https://www.va.gov/contact-us/) page in ticket #47846.

When we remove the alert we need to add back in the original content on the page:

H2: Contact us online through Ask VA
Ask VA (AVA) is our new online tool that replaced the Information Routing & Inquiry Service (IRIS) and the GI Bill Help Portal. Use Ask VA to send us your questions, updates, and documents online.

Note: We should check about whether we can remove the word "new" from that content as Ask VA has been up for a while now.

## Tasks
- [x] Remove alert (Laura)
- [x] Add back content to Drupal (Laura)
- [x] Copyedit (Randi)
- [x] Publish (Randi)

## Acceptance Criteria
- [x] Contact us has Ask VA content and no warning alert

**Comment by RLHecht** [comment]
This page was updated and published now that Ask VA is back online.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
