### ISSUE TITLE
MDT prosthetic sock- select item

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#4792]
## User Story:
As a Veteran, I need to be able to select & unselect  an sock items so that I can choose my items.

## Tasks
- [ ] create a check box that displays a selected item
- [ ] The check box should be able to be selected and unselected
- [ ] Determine back-end Ajax call
- [ ] unit test the code

## Acceptance Criteria:
Given that the veterans sock items are displayed
When the veteran see the item(s) they want
Then the selector (the checkbox)  on the screen will indicate (checked) selected.

## Next steps
- Confirm happy path 

## Blocker
- Back-end Ajax call
