### ISSUE TITLE
External COP Task: Discuss E2E Allow-list Notifications

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#47937]
# Description
The E2E Stress Test would report notifications to the QA Standards Notifications channel, but due to the fact that the QA Standards no longer exists, and in light of some tweaks and updates to the E2E Stress Test, we need to update how notifications for the Stress Test are handled.

# Tasks
- [x] Get guidance from Clint on how/where the notification should be handled
- [x] Communicate intent to update notifications through Slack channels
- [x] Make update to the notification

# Acceptance Criteria
- [x] The notification has been updated and is successfully reporting to #vfs-all-teams

**Comment by CBonade** [comment]
After many iterations of the message and much testing, this is merged and will hit #vfs-all-teams on Monday at noon (providing my math is correct on the timing!)

**Comment by pjhill** [comment]
Hooray for revised messaging around this system -- now to measure engagement!
