### ISSUE TITLE
[FE] Add questions/page(s) for gender identity (SIGI) to 10-10EZ

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#47938]
## User Story
> As a Veteran, it is clear I can choose to or not to disclose my gender identity on my health care application. 

> Add the additional question(s) and pages for gender identity to the Veteran Information 

Previous design ticket
- [[Design] 10-10EZ - SIGI: Confirm current content and make any necessary updates #46904](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46904)

## Related Documentation

> Sketch files

-  [Gender identity page 1 (yes/no share question) - Desktop](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/qemoRK2)
- [Gender identity page 1 - Mobile](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/Jn4075k)
- [Gender identity page 2 (select) - Desktop](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/wLkE92q)
- [Gender identity page 2 - Mobile](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/ZOYPb93) 

## Description
Page 1
> Gender identity (header)
> What to know before you decide to share your gender identity (additional info component)
>(additional info content)
> Sharing your gender identity on this application is optional. This information can help your health care team know how you wish to be addressed as a person. It can also help your team better assess your health needs and risks. We also use this information to help make sure we're serving the needs of all Veterans. 
But you should know that any information you share here goes into your VA-wide records. VA staff outside of the health care system may be able to read this information. 
> We follow strict security and privacy practices to keep your personal information secure. But if you want to share your gender identity in your health records only, talk with your health care team.

> Do you want to share your gender identity? (*Required)
> Yes
>No

Page 2
> Gender identity
> Select your gender identity
> (options) (Man, Non-binary, Transgender man, Transgender woman, Woman, Prefer not to answer, A gender not listed here)

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] %Add any tasks%
- [ ] Create unit tests
- [ ] Create e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by jessicastump** [comment]
Opened duplicate tasks - [#47939](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47939) 

Closing this one
