### ISSUE TITLE
[SMS] Define Content for SMS Confirmation Message with Claim Number

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#47930]
## Tasks
- [x] Define Content for SMS Message with Claim Number
- [x] Review other [text message responses](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md), as needed
- [x] Review the [wireframe](https://share.goabstract.com/3f25b4c0-4404-4079-a938-367f40c4903b?collectionLayerId=5ee6e284-5da0-49b3-9839-2b2d15c06ca0&mode=design) that Zach and Ben worked on at an earlier phase that included the travel reimbursement claim number, for reference
- [x] Consider SMS message when API fails or is unavailable (https://share.goabstract.com/cc1baa9a-d05e-402c-a2c7-90fd14f5460e?collectionLayerId=9421e29d-1565-4e6a-9ae5-0ca507077a80&mode=design)
- [ ] UX come up with some URL options. E.g., could include claim number to make it more meaningful. 
- [ ] Talk to Adrian about what's possible for friendly/short url
- [ ] Ask Ben Williams and Daryl if you can deep link into a specific claim. Run a couple ideas by them on what the url in sms could be to see if they have feedback. 
- [ ] Pass off to PCI/API team (formerly known as CHIP)

https://dvagov-btsss.crm9.dynamics.com/

**Comment by benbrasso-agile6** [comment]
@loripusey should this be in the enhancement epic or mvp? Also, I'm going to update the description to potentially include an error message response too.

**Comment by loripusey** [comment]
It's in both, I think the faster we can get it defined and on PCI/API team's roadmap the better.

**Comment by benbrasso-agile6** [comment]
Makes sense

**Comment by benbrasso-agile6** [comment]
@loripusey where did we land on where our source of truth is for text messages? API Team manages the source of truth for these? And our team won't document them anywhere outside of product guides and anywhere in Abstract that we deem appropriate?

**Comment by benbrasso-agile6** [comment]
Oh right, I found this in [Git](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md)

**Comment by loripusey** [comment]
Sounds like a question for @Hortonio

**Comment by benbrasso-agile6** [comment]
Think I have what I need for now, unless the link in the repo I mentioned above is out of date

**Comment by Hortonio** [comment]
@benbrasso-agile6 You found it, this is the source of truth we are currently utilizing for PCI API team. The last update is showing to be June 16th which aligns with the last messaging changes we made in [937](https://app.zenhub.com/workspaces/pci-api-6149f6401b0b3c001219802f/issues/department-of-veterans-affairs/chip/937). Content should be up-to-date with current production deployment but please be sure to let us know if you catch anything out of place. Thanks!

**Comment by benbrasso-agile6** [comment]
@loripusey we may think about (re)adding the claim number to the VA.gov confirmation page as well when we implement the text message. Maybe we write the content (but not the wireframe) for this within this ticket? Thoughts

**Comment by loripusey** [comment]
Perhaps, I seem to recall the discussion was around the fact that without a way to save that confirmation number on the confirmation page that it was really not useful to have it there and having it there would give the user anxiety that they need to write it down; I thought that texting it to them was our way around showing it to them and causing that anxiety

**Comment by loripusey** [comment]
If I run into a confirmation number on my phone and no way to save it I just take a picture of my screen, but I'm not sure if anyone would think to do that in this scenario

**Comment by benbrasso-agile6** [comment]
Right. I guess my point is, it wouldn't hurt to have it in both places. That way, you "see" it quickly on VA.gov, and then it's simultaneously sent/saved as a text message to your phone. I feel like seeing the claim/confirmation number on a confirmation page, which will be inaccessible once you navigate away from it, is quite common across many industries. E.g., food service orders, booking plane ticket, etc.

**Comment by kellysmith1008** [comment]
I like the idea of having it in both places, and agree it's similar to other site functionality when dealing with confirmation numbers.

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 
What if, for the SMS message, we go with something like this:
"We've received your travel claim for your visit on MM/DD/YYYY. Your confirmation number is 123XYZ. You can check the status of your travel claim online 24/7 on the Beneficiary Travel Self Service System. 

Check your travel claim now. (This is a link, that links out to BTSSS)

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 nice, good start

Couple suggestions to think about: 

1) Might be good to include "VA" somewhere to better communicate who is sending the text message. E.g., "Your travel reimbursement claim has been received for your VA appointment on MM/DD/YYYY."

2) I might recommend using "claim number" instead of "confirmation number." And, the claim number will be in the format of TC202207000011666. 

3) Maybe think about breaking up into multiple paragraphs when topics change to make for easier reading. For example, maybe a paragraph break after the claim number. 

4) Might recommend phrasing the link as, "... on the Beneficiary Travel Self Service System (BTSSS) through the AccessVA travel claim portal: https://eauth.va.gov/accessva/?cspSelectFor=oauth.BTSSS&targetPath508=cspSelectFor%3Dhttps%253A%252F%252Ffed.eauth.va.gov%252Fisam%252Fsaml20SPFed%252Fsaml20%26ForceAuthn%3Dfalse&foiaUrl=https%3A//www.va.gov/foia/&nonce=wAgV5olUxtVXF0HKzldSWFbceFooqprj " 

We'll need to have a discussion about a URL shortener. Maybe we PL it tomorrow with engineers, since we're using a shortener already somewhere. 

And, want to think about creating another text message for the error state that is mentioned in the task list above?

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 
"We've received your travel claim for your VA appointment on MM/DD/YYYY. Your claim number is TC202207000011666.

You can check the status of your travel claim online 24/7 on the Beneficiary Travel Self Service System through the [AccessVA travel claim portal](https://eauth.va.gov/accessva/?cspSelectFor=oauth.BTSSS&targetPath508=cspSelectFor%3Dhttps%253A%252F%252Ffed.eauth.va.gov%252Fisam%252Fsaml20SPFed%252Fsaml20%26ForceAuthn%3Dfalse&foiaUrl=https%3A//www.va.gov/foia/&nonce=wAgV5olUxtVXF0HKzldSWFbceFooqprj). 

How's that? Per the Design Language System and for accessibility, we can't just put the URL in there without a descriptor sentence, regardless of length. I'm still researching the "something went wrong" message - but will post it soon-ish

**Comment by benbrasso-agile6** [comment]
Does SMS support a descriptive link? We haven't done that before within Patient Check In. Example - https://share.goabstract.com/633e7703-933c-4dc6-a864-f687ad264817?collectionLayerId=30897749-932a-4737-80a4-d3b3a91a2fc0&mode=design&sha=latest

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 
Ah, yes - I went a little overboard in my descriptor requirement! So yes,it should be something that describes what the link is going to do or lead to, but SMS doesn't support descriptive linking. Sorry for that error! So what about:

"We received your travel claim for your VA appointment on MM/DD/YYYY. Your claim number is TC202207000011666.

You can check the status of your travel claim online 24/7 on the Beneficiary Travel Self Service System through the AccessVA travel claim portal: [https://go.usa.gov/xxxx](https://go.usa.gov/xxxx)."

**Comment by benbrasso-agile6** [comment]
@acrollet @DanielleThierryUSDSVA @kristenmcconnell if we want to send a confirmation SMS to all Veterans that successfully submit a travel reimbursement claim during check in, which includes a non-unique link to the [AccessVA travel claim portal](https://eauth.va.gov/accessva/?cspSelectFor=oauth.BTSSS&targetPath508=cspSelectFor%3Dhttps%253A%252F%252Ffed.eauth.va.gov%252Fisam%252Fsaml20SPFed%252Fsaml20%26ForceAuthn%3Dfalse&foiaUrl=https%3A//www.va.gov/foia/&nonce=wAgV5olUxtVXF0HKzldSWFbceFooqprj), how would we go about discussing, selecting and creating a short URL to use in the SMS message? 

Assuming it would direct to: 
https://eauth.va.gov/accessva/?cspSelectFor=oauth.BTSSS&targetPath508=cspSelectFor%3Dhttps%253A%252F%252Ffed.eauth.va.gov%252Fisam%252Fsaml20SPFed%252Fsaml20%26ForceAuthn%3Dfalse&foiaUrl=https%3A//www.va.gov/foia/&nonce=wAgV5olUxtVXF0HKzldSWFbceFooqprj

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 looks good

**Comment by benbrasso-agile6** [comment]
Other tasks to complete

- [ ] UX come up with some URL options. E.g., could include claim number to make it more meaningful. 
- [ ] Talk to Adrian about what's possible for friendly/short url
- [ ] Ask Ben Williams and Daryl if you can deep link into a specific claim. Run a couple ideas by them on what the url in sms could be to see if they have feedback. 

https://dvagov-btsss.dynamics365portasl.us/

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 
 https://go.usa.gov/claims
 https://go.usa.gov/TC202207000011666
 https://go.usa.gov/myclaims
Any of these strike your fancy? I like the idea of using the claim number in the link itself - makes it much more meaningful, so I totally support using the claim number if we can!

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 nice. Yeah, I like the claim number appended to the link as well. Sounds like we have a couple options: 

1) We use the go.usa.gov domain as a shortener for https://dvagov-btsss.crm9.dynamics.com/. @acrollet any idea if we're (or who's) able to create redirects off that domain? Suppose we'd need to work out some logistics with whoever manages that. For example, we might need our own directory. E.g., /btsss/TC202207000011666 

2) If go.usa.gov is an option (per above), we give that to Daryl and the travel office team as an example and ask if there's another domain that they use for shorter links. 

Or, is there another option we're not thinking of? @acrollet

**Comment by benbrasso-agile6** [comment]
Also, I messaged patrick and mark about this to see what url shortener we are using today

**Comment by benbrasso-agile6** [comment]
In speaking with patrick and mark, going to create a spike ticket to expand url shorterner to include other domains

**Comment by acrollet** [comment]
Unfortunately [go.usa.gov is no longer supported](https://go.usa.gov).

**Comment by acrollet** [comment]
A spike is probably the best idea, I don't know if we can/should create a url shortener under va.gov that redirects to a non .gov site.

**Comment by benbrasso-agile6** [comment]
Added spike https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/49881

Closing ticket for now
