### ISSUE TITLE
[FE] Add gender identity question (SIGI) to 10-10EZ

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#47939]
## User Story
> As a Veteran, it is clear I can choose to or not to disclose my gender identity on my health care application. 

> Add the additional question(s) and pages for gender identity to the Veteran Information 

Previous design ticket
- [[Design] 10-10EZ - SIGI: Confirm current content and make any necessary updates #46904](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46904)

## Related Documentation

> Sketch file links here

## Description

> Final content here

## Tasks

> this is a list of technical tasks that need for this ticket

- [ ] %Add any tasks%
- [ ] Create unit tests
- [ ] Create e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

> when is the ticket done

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by markfallows** [comment]
Repurpose ticket for updating the content of the SIGI after it's been confirmed.

**Comment by markfallows** [comment]
Closing as a duplicate.
