### ISSUE TITLE
[DLD] Create new Feature Flag

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#47953]
## Background
We need to create a feature flag to hide the decision letter link / page from different environments while we do our staged rollout of the new feature

## Tasks
- [x] Add new feature_toggle to backend
- [x] Add new feature_toggle to frontend
- [x] Use new feature_toggle to conditionally hide the link to claim letters in closed claim details
- [x] Use new feature_toggle to conditionally hide the claim letters page
