### ISSUE TITLE
[FE] My VA Health care: Updates to Health care section w/drupal replacement (deprecation of `isCerner` flag)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#47956]
## Background
As explained in #46419 - the public websites team is planning to deprecate the Cerner hard coded data process by EOY (2022) in favor of a Drupal-driven API. As Taylor noted in the research ticket, the public websites team created a drop-in replacement that will require thorough testing. The replacement will also need to be done in every instance where we use it. The selectors we are currently using will be changed to use the drupal source of truth connectors.

_Must be done by release of new API on 12/1_

## Tasks
- [x] Replace code the pulls in hard-coded text for the Cerner alert that displays when we detect that a Veteran receives care at a Cerner facility with Drupal API ("drupal source of truth API")

## Acceptance Criteria
- [ ] My VA Health care section is able to dynamically display the Cerner alert depending on the users' status in relation to Cerner facilities 
- [ ] The Cerner alert dynamically displays the applicable cerner facilities

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ any team member
- _How can this work be validated?_ See updated logic via Cerner alert with staging users, test with multiple cerner accounts with different facilities

## Resources
- [Public Website's documentation around drupal solution](https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-opt-in-to-drupal-as-the-source-of-truth-for)

**Comment by tmitchellgcio** [comment]
This seems to be having an issue during testing. Items won't load properly so I'm still working on figuring out why this is the case.

**Comment by tmitchellgcio** [comment]
Just merged give this about 30 min. If you need my help let me know

**Comment by tmitchellgcio** [comment]
@ericasauv09 this is in staging now and I'm excited to say it works and is not broken...this time

**Comment by ajakabcin** [comment]
@ericasauv09 and @tmitchellgcio This looks right to me as well! I did some additional checks with other Cerner users from [this set ](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-cerner.md)of test users. @ericasauv09 let's still reach out to public websites and see if they would be able to do another test with us, add a new facility and check that things update properly on our side. I don't see why they wouldn't given what we're seeing now with this implementation but good to double check. Can you take care of that? Thanks!

cc @Samara-Strauss
