### ISSUE TITLE
MDT- Comment step- adding buttons

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#4795]
## User Story:
As a Veteran, I need a comment box so that I can address other items with the DLC.

## Tasks
- [ ] create a button that enables additional comment box
- [ ] create cancel button to remove comment
- [ ] create a save button to save the comments
- [ ] unit test the code for the button is correct.
- [ ]  submit data will need to be send to back-end

## Acceptance Criteria:
Given that the veterans has the ability to add a comment
When the veteran selects the add a comment button
Then a input box will be displayed for the veteran to add inputs.

## Next steps
- Confirm happy path 

## Blocker
- Back-end call
