### ISSUE TITLE
MDT comment step- enabling input box

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#4796]
## User Story:
As a Veteran, I need a comment box so that I can additional items offered by the DLC.

## Acceptance Criteria:
Given that the veterans has the ability to add a comment
When the veteran selects the add a comment button
Then a input box will be displayed for the veteran to add inputs.

## Tasks
- [ ] create and display input box for veterans to write message
- [ ] limit characters to "400~"  
- [ ] unit test the code

## Next steps
- Confirm happy path 

## Blocker
-tbd
