### ISSUE TITLE
[Research] Planning for Baseline Usability for Tasks on 10-10EZ

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#47972]
## Issue Description
There are bits and pieces of key findings from past research and usability studies. With upcoming design enhancements in the works, the research question arose of how to compare before and after qualitatively. This baseline research will include pre-work of coming up with key product tasks and use cases that can be tested repeatedly with the first round being this test.

This will be an end-to-end usability test of the 10-10EZ Health Care Application in staging.

---
## Tasks
- [x] 10-10 Team to collaborate to determine top tasks to test
- [x] Write / proofing of task questions & rating criteria 
- [x] Create Task/Use Case Documentation on GitHub & Sketch Wireflow 
- [ ] Wireflow w/ all applicable research to date
- [x] [Create research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/research/2023-01-Baseline%20Task%20Research)
- [x] [Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2023-01-Baseline%20Task%20Research/research-plan.md)
- [x] [Conversation Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2023-01-Baseline%20Task%20Research/conversation-guide.md) 
- [x] Submit for Research Review 
 
## Acceptance Criteria
- [ ] All planning and prep tasks are complete and this is ready to go begin research review 
---
