### ISSUE TITLE
Thumbnail mapping 2nd iteration

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#4797]
## User Story:
As a  Designer, I need to create a second iteration of our thumbnail map so that I can _incorporate feedback from the first iteration.

## Tasks
- [x] Create a new  thumbnail map iteration based comments form DLC's/BAM2 regarding our first iteration.
- [x] Present the new  thumbnail iteration for BAM2 to review
- [x] Present the new  thumbnail iteration for the DLC to review

## Acceptance Criteria:
Given: That the DLC objective is to create a User's process flow
When: The team has a understanding of what steps are need/required to complete a order
Then: The team can finalizes on 1 flow and start wire-framing based of the agreed thumbnail map.

## Next Steps
- Present 2ND iteration to BAM2
- Present 2ND iteration to DLC
- Incorporate any feedback given from both the BaM2 and DLC teams (#4798)

## Blockers
- n/a

**Comment by rebeccawalsh** [comment]
New deliverables and outcomes/feedback were included in this README on github: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/thumbnail-mapping/README.md

The final design intent checkin (with Content) is scheduled to happen 1/24 @ 2-3pm EST.
