### ISSUE TITLE
Investigate EVSS DocumentUpload Job

### ISSUE THREAD

**Issue by rjohnson2011** [department-of-veterans-affairs/va.gov-team#47991]
## Description
In an investigation of the longest-running Sidekiq jobs, [EVSS DocumentUpload](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/workers/evss/document_upload.rb) was the longest. Look into determining the cause of these long runs, and evaluate options for optimization. 

## Tasks
- [x] Reach out to prior code contributors of DocumentUpload to discuss the long-running jobs
  - Previous contributors are no longer on the project/platform.
- [x] Analyze & evaluate the source code
- [x] Research alternative methods (i.e. chunking) that could cut down on job time

## Acceptance Criteria
- [x] _Complete the above tasks and provide a recommendation for possible DocumentUpload optimization_

**Comment by rjohnson2011** [comment]
Cloned the backend repo & researched the DocumentUpload job. Currently EVSS and disability claims documents are uploaded to AWS S3 via Carrierwave gem. The process includes a virus scan & validation for proper files type/size. 

The documentation regarding revision history states the last updates were made April 12, 2017. Continuing to dive into the codebase, specifically looking for potential optimizations.

**Comment by ericboehs** [comment]
Manual instrumentation was added in [#10900](https://github.com/department-of-veterans-affairs/vets-api/pull/10900) to determine if the upload (HTTP post) was the majority of the time.

It was determined that upload was 99%+ of the duration.

Some other notes:
- The upload limit for EVSS PDFs [is 150MB](https://github.com/department-of-veterans-affairs/vets-api/pull/5346).
- The timeouts were originally 3 minutes but has been [increased](https://github.com/department-of-veterans-affairs/vets-api/pull/6435) ([twice](https://github.com/department-of-veterans-affairs/vets-api/pull/5911)) to 8 minutes.
- These are read/write/open timeouts and not a [global timeout](https://janko.io/httprb-is-great/#global-timeout) for the call.
- This job is appropriately [in the low-priority queue](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/workers/evss/document_upload.rb#L9).
- Users **are not** waiting on this job to finish their interaction.

## Proposed next steps

[Traces in Datadog indicate](https://vagov.ddog-gov.com/apm/traces?query=%40_top_level%3A1%20env%3Aproduction%20%40duration%3A%3E%3D8min%20resource_name%3A%22EVSS%3A%3ADocumentUpload%22&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&historicalData=true&messageDisplay=inline&sort=desc&spanType=service-entry&start=1666099644673&end=1666114044673&paused=true) 59 EVSS::DocumentUpload jobs ran longer than 8 minutes in a 4-hour period.

The 8-minute timeout for open and read/write chunks is high. I think our goal here is a maximum/global timeout for the entire upload. Faraday and HTTPClient do not seem to support this. Adding something like Ruby's Timeout or [safe_timeout](https://github.com/david-mccullars/safe_timeout) around the upload call should solve this.

I suspect the setting of our Faraday's timeouts is also flawed. We [set the timeout](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/evss/base_service.rb#L56-L58) differently compared to every other Faraday timeout in our app (e.g. [VaNotify::Configuration](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/va_notify/lib/va_notify/configuration.rb)) and compared to [Faraday's docs](https://lostisland.github.io/faraday/usage/customize).


## Tasks

- [ ] Add logging of file size so we can correlate file upload times with file size.
- [ ] Change EVSS::BaseService to use request argument for setting timeouts.
- [ ] Increase minimum retry wait time for DocumentUpload jobs to 1 hour.

**Comment by ericboehs** [comment]
We could also look into benchmarking the chunks using [Faraday's `on_data` callbacks](https://github.com/lostisland/faraday/issues/1071).

Perhaps this is something we keep in mind as we debug other Faraday-based issues.

**Comment by rjohnson2011** [comment]
Working on implementing the above tasks. Set up the development environment on `vets-api` to be able to run tests locally rather than in production to pass CI & Rubocop. Will reach out if any blockers are encountered.

**Comment by rjohnson2011** [comment]
Have all tasks implemented except the final 5 minute timeout. Working on adding completing this final task & getting all CI tests to pass. Anticipate putting in a PR later this day.

**Comment by rjohnson2011** [comment]
Closed & merged the following PR -> https://github.com/department-of-veterans-affairs/vets-api/pull/10980
