### ISSUE TITLE
Graceful Degredation - Develop a better way to support downtime notifications  during scheduled and unexpected events

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#4799]
## High Level User Story/ies
As a VSP leader, I need a way to ensure end-users see proper downtime messaging when using va.gov during scheduled or unexpected downtime events that take down vets-api.

## OKR
O1: Customers have a delightful experience building on the platform

### What must be true in order for you to consider this epic complete? 

- Scheduled Downtime
  - Global messaging is required on each page that informs the user of the downtime.
      - Ahead of scheduled downtime
      - During the scheduled downtime
  - Login Modal
    - Messaging should be added to the login modal informing the user of the downtime.
      - Ahead of scheduled downtime
      - During the scheduled downtime
    - Login buttons should be disabled during actual downtime if login is affected
  - Forms
     - Messaging should be added to the form informing the user of the downtime.
  - Messaging language
    - Should be agreed upon beforehand.
       - Include a time window

- Unexpected Downtime
  - Global messaging is required on each page that informs the user of the downtime.
  - Login Modal
    - Messaging should be added to the login modal informing the user of the downtime.
  - Forms
    - Messaging should be included within forms that informs the user of the downtime

### Notes from discovery

- Some apps like the profile page can function without all of their services available
- Most forms are not configured to display downtime messaging
- Many apps have custom messaging and styling for their downtime messaging
- Some downtime messaging appears as result of an API error and may not represent a real downtime
- Some non-forms applications are gated using a static page widget that does no support downtime
- Sitewide downtime messaging is not triggered by the same calls / infrastructure as app level messaging

#### Low effort

- [ ] Configure downtime for all of the forms
- [ ] Remove custom downtime messaging for forms
- [ ] Need to check for this as part of collaboration cycle

#### Medium effort

- [ ] Update DowntimeNotification component to meet design specifications
- [ ] Mandate usage of DowntimeNotification component (no custom downtime display behavior)
- [ ] Fix upcoming downtime behavior on forms
- [ ] Add downtime behavior to static pages signin widget
- [ ] Provide trigger for sitewide messaging (i.e. integrate it with the pager duty global downtime, remove manually configured dates from promo banner)
- [ ] Update sitewide messaging to meet design specifications
- [ ] Consolidate downtime triggers (i.e. apps should use a single config published to S3)
