### ISSUE TITLE
Investigate DocumentUpload

### ISSUE THREAD

**Issue by rjohnson2011** [department-of-veterans-affairs/va.gov-team#47990]
## Description
In an investigation of the longest-running Sidekiq jobs, DocumentUpload was the longest. Look into determining the cause of these long runs, and evaluate options for optimization. 

## Tasks
- [ ] _Reach out to prior code contributors of DocumentUpload to discuss the long-running jobs_
- [ ] _Analyze & evaluate the source code_
- [ ] _Research alternative methods (i.e. chunking) that could cut down on job time_

## Acceptance Criteria
- [ ] _Complete the above tasks and provide a recommendation for possible DocumentUpload optimization_

**Comment by rjohnson2011** [comment]
This is an accidental duplicate of  https://app.zenhub.com/workspaces/platform-tech-team-3-6335ab9b1901b99243ce7601/issues/department-of-veterans-affairs/va.gov-team/47991
Closing out.
