### ISSUE TITLE
Address concerns with as-is QA Standards

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#48009]
## User Story
As a Governance team member, I want to make sure the concerns identified with the QA standards are resolved so that VFS expectations are clear and Governance team can build a process that supports the QA standards.

Assignee: @it-harrison 
Peer Reviewer: @shiragoodman 

## Description
In ticket #47529, Governance team members @it-harrison and @shiragoodman identified concerns surrounding the recently published[ Quality Assurance (QA) standards. ](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards). In this ticket, Governance team will come up with solutions for addressing the concerning issues.

## Impacted Artifacts
[QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards)

## Tasks
- [x] Complete the 'Identified issues and their solution' section below
- [x] Once all questions have been addressed, share with @little-oddball for review and approval
   - Clint - do you think we'll need to get OCTO buy-in for any of the proposed changes? Should we plan to attend Platform Office hours?
- [x] Once approved by Clint, update the QA Standards page with the necessary changes
- [x] Submit for peer review with @shiragoodman  
- [x] Shira will share with OCTO for review/approval

## Identified Issues and their solution

1. Regression Test Plan, Test Plan, Unit Test Coverage, and Lighthouse Accessibility Rating areas use the word must in their Description columns; however, none of these areas are required for product launch. Therefore, changing the word must to should is recommended to avoid confusion as to whether these elements are blockers for launching a new product.
 - keep it "must" to align with VA.gov Experience Standards. 
2. For all Areas except E2E Test Participation, how will the Remediation Plan be operationalized? When and how are the teams warned?
   - Shira's thoughts: Agree with [@it-harrison](https://github.com/it-harrison) 's concerns re: the Remediation Plan. Platform Governance will NOT be periodically checking in so this field should be modified.
   - Remove the Remediation Plan column
3. For the E2E Test Participation area, the timing mentioned in the Remediation Plan is unclear; does the 30 days start at the Staging Review? Further, the text suggests that the team can release to production during this 30 day period even though they have no E2E tests. Is this right? Or should all launches be blocked?
 - VFS teams are blocked from launch until they meet the e2e test participation standard
4. Several Areas mention that teams need to use TestRail but this has not a requirement previously.
- Remove all references to TestRail from the standards
5. Why is there a discrepancy between Regression Test Plan and Test Plan areas with respect to the Violation Description text, i.e. which point in the Collab Cycle that the respective plan is checked for?
- re: the Violation description, remove column. Add message to top stating "VFS teams will be evaluated whether or not they are meeting these standards at the Collab Cycle Staging Review"
6. The Description for the Traceability Reports area could be tightened up a bit - the Coverage for References bullet should not be split into two bullet points. Also, it would be nice to indicate precisely what the Coverage for References and Summary are, a report of some kind.
 - reword the Traceability Reports description to align with the other standard descriptions. Remove the bullets.
7. Security Level: warning implies that Platform will continue to check for this QA standard, when (at this time) we will only be verifying at Staging Review
- Change "Type" to "Severity". All standards with "Warning" should be "Warning, Not launch-blocking" E2e standard will state "launch-blocking"
8. Link to QA Product Dashboard guide should be removed as it points to Confluence
 - re: warning message, "These artifacts and data are stored in TestRail and Domo, so you will need access to these tools.
See [Quality assurance artifacts](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-artifacts) and [QA Product Dashboard guide](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2151317518/QA+Product+Dashboard+guide) for additional information." check with @pjhill as we cannot point VFS teams to Confluence. See if information is available on Platform Website.
9. [Frontend support dashboard](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/lighthouse-performance-report/) (used for validating the Lighthouse Accessibility rating) is not complete. Unsure if we should have this as a standard if it can't be used/applicable to all VA.gov products
   - I can look into why not all apps are included here. Teams can run lighthouse by themselves, though.
   - propose to remove the Lighthouse accessibility rating standard as it is duplicative of what Accessibility is requesting of VFS teams and reviewing at Staging Review.
10. Review 'How to check for compliance and address remediation' for E2E test participation. Unsure if it makes sense for a non-techie (like me)
    - this is clear for an engineer or somebody familiar with the `vets-website` repo. I'm not sure if the average PM would be able to verify this without consulting an engineer.
11. The 'How to check for compliance and address remediation' for Regression Test Plan, Test Plan and Traceability Reports is very basic and 100% specific to TestRail. How do we validate if the VFS team does not use TestRail?
    - I think this is a good point. But one thing we might want to mention is that the test plan should cover the user stories.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have modified the QA Standards to address the previously identified concerns
- [x] We have OCTO approval on the proposed changes

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer
"

**Comment by it-harrison** [comment]
Hi @shiragoodman:

- changes to Q/A standards are in bold in [this document](https://vfs.atlassian.net/wiki/spaces/~853060520/pages/2403237889/Proposed+Changes+to+QA+Standards).
- thoughts on "How to check for compliance and address remediation" section, I put some notes in your summary of the issue in this ticket above ^.

**Comment by it-harrison** [comment]
@shiragoodman I have updated the [QA standards draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2403237889/Proposed+Changes+to+QA+Standards) to take into account the conclusions from our meeting with Clint.

**Comment by shiragoodman** [comment]
@it-harrison I completed my review and added some comments to the draft. Please address my comments, then verify that all, "Identified Issues and their solution" have been addressed above. Once met, ask @little-oddball to review. Thank you!

**Comment by shiragoodman** [comment]
@it-harrison I added a couple minor comments to the draft page, but I think it's ready to go once those small changes are addressed. Did you send over to @little-oddball for his review?

**Comment by it-harrison** [comment]
> @it-harrison I added a couple minor comments to the draft page, but I think it's ready to go once those small changes are addressed. Did you send over to @little-oddball for his review?

@shiragoodman, no but I will as soon as finish those changes

**Comment by shiragoodman** [comment]
@it-harrison I checked with Jason Woodman, our product lead, on whether or not this should go through Office hours again. He thinks that we don't need to, but we should still connect with Ray and Chelen to make sure they're on board with our changes before continuing on with the initiative. Once Clint is done reviewing, please let me know and I'll get the post ready for our team Slack channel.

**Comment by shiragoodman** [comment]
@it-harrison no additional comments from OCTO, so this should be good to close. Please check off remaining tasks and AC, then close.
