### ISSUE TITLE
[FE] Health Care Section: Bug- VAOS duplicate API Call

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#48002]
## Background
Katherine Lawyer reached out because the VAOS team noticed we are making duplicate calls to retrieve health care appointment information. There is a Slack thread [here](https://dsva.slack.com/archives/C909ZG2BB/p1665506024729369) with background information. This is hidden behind a feature flag so we believe it is only impacting Staging. We also have a V0 and V2 version of the VAOS API that we are calling and we are making duplicate calls to both. Mark Dewey created a PR to fix this however he is unsure if merging the PR will break any tests and wants someone to validate that.

## Tasks
- [x] Review Mark's PR and ensure it will not break and CI tests
- [x] Inform Mark that we are good to Merge, if that is the case
- [x] Inform VAOS team and confirm they are set on their end - PM

## Acceptance Criteria
- [x] We are no longer making duplicate calls for health care appointment scheduling data

**Comment by tmitchellgcio** [comment]
CI looks fine. Don't know what Tugboat is. That's new, but I think this is fine. Code LGTM. We just have to wait until @mdewey takes it out of Draft and I can Approve it.
