### ISSUE TITLE
Promote Vets-API Server with EKS to Dev

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#48001]
**PROBLEM STATEMENT**
Vets-api server needs to be migrated to EKS, opening the doors for a micro service based infrastructure.

**DEFINITION OF DONE**
- [x] Manifest Files: All of the necessary files for the deployment will exist in the appropriate repo
- [x] Software Repositories: 
       (1)Necessary infrastructure exists so app (vets-api server) can exist within EKS 
       (2)Vets-api server is packaged so the app can exist in the EKS environment 
       (3)ECR repo exists 
       (4)Docker file exists in the primary app repo
- [x] CI/CD tools and pipelines: 
       (1)GHAs exist that will build the images and push to ECR
       (2)ArgoCD configuration that will auto-sync the app
- [x] Container registry: A registry exists for the specific images in ECR pertaining to the app
- [x] Container Orchestration: EKS works automatically by unifying the infrastructure components 
- [x] Deployment Management: ArgoCD provides a UI for developers to see the application and manages the deployment by checking the desired state against the deployed state (auto-syncs when needed)
- [ ] Testing
       (1) Conditional routing of traffic to EKS is ready so testing is accurate
       (2) A/B routing is complete
       (3) Synthetic testing is complete
- [ ] Deprecation planning
       (1) 
- [ ] [Documentation](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines)
       (1) Internal facing documentation that accounts for all the above items
       (2) VFS-facing documentation that accounts for all the above items
       (3) Necessary diagrams have been completed (mermaid)
       (4) Anticipated maintenance items, including timeframes if known

**Comment by laineymajor** [comment]
Note from mtg on 10.19: Should we add ECR repo as a step in the process? @LindseySaari for visibility...

**Comment by laineymajor** [comment]
Add to process:
git_revision

**Comment by laineymajor** [comment]
Add to process:
https://adhoc.slack.com/archives/C045LCF8WU8/p1668527519522729

**Comment by laineymajor** [comment]
Add to process:
https://adhoc.slack.com/archives/C045LCF8WU8/p1668527199009159
