### ISSUE TITLE
[BE] Notification Letter performance tracking and monitoring

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#48017]
Using standard tracking and monitoring tools like Sentry, Datadog, Grafana, and/or PagerDuty, enable the team to identify fail states and to know whether we are reaching our performance benchmarks or not. 

### Back End (pair with Kyle from squad 2 and estimated at a 4-5)

- [x] add code for failure event pushed to sentry or datadog for API call to pull list of letters that includes the failure reason and status code
- [x] add code for failure event pushed to sentry or datadog for API call to pull list of letters that includes the failure reason and status code
- [x] add code for failure event pushed to sentry or datadog for API call to pull a single letter

# Acceptance Criteria 

Monitoring:

- [x] Error logs allow us to conduct root cause analysis to determine the reason behind critical fail states
- [x] Team receives notifications for critical fail states, such as application failing to load for end users
- [x] Able to distinguish performance between the two distinct API calls being made

Tracking

- [ ] Create event(s) that allow us to track successful API calls that generate the list of notification letters
- [ ] Create event(s) that allow us to track successful API calls that denote when a user actually downloads their notification letter
- [ ] Create an event that allows us to count critical application failures.

**Comment by sortizsh** [comment]
companion ticket to https://github.com/department-of-veterans-affairs/va.gov-team/issues/48211

**Comment by kjduensing** [comment]
Something I just remembered is that Datadog is apparently just for Platform teams. I think there were plans to do an incremental rollout to VFS teams like ours, but that's not in the works yet AFAIK.

**Comment by kjduensing** [comment]
I [confirmed that the DataDog blockage is an access problem](https://dsva.slack.com/archives/CBU0KDSB1/p1667843683267589). Sounds like VFS teams have read-only access, even with an account.

There is an infra epic to track who needs access and why. We could create a separate ticket for datadog and link them.

Additionally, @kylesoskin [apparently no longer has write access since changing over to a VFS team](https://app.zenhub.com/workspaces/platform-infrastructure-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/va.gov-team/46872).
