### ISSUE TITLE
Auth Exp | FE | Send user to top of page when landing on notification settings from contact information

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#48011]
In research sessions recently, we noticed that when a user clicks the "Add your mobile number" link from the notification settings page success alert, adds a mobile number, and then clicks the "manage text notifications" link in the saved confirmation alert, the viewport is scrolled to the same point the person was on in the contact information screen.  This causes the footer to take up most of the view, and people to immediately have to scroll up and orient themselves to where they are. 

Video demonstration below:

https://user-images.githubusercontent.com/55992116/194949052-3a4dfa35-4246-4f85-875c-a3acd4bfe22d.MP4

Can we take people to the top of the page like it would load if you were visiting it for the first time from a regular site (vs a SPA)?

**Tasks**

- [ ] Determine if this is feasible
- [ ] Update the behavior if so

**Acceptance Criteria**

- [ ] The notification settings page loads so the top of the page is in view when a person goes from the "manage text notifications" alert on Contact information to the notification settings page.

**Comment by andaleliz** [comment]
@SKasimow here's another one that came out of research for you to assign/plan for as you have time :)

**Comment by adamwhitlock1** [comment]
@SKasimow This is live on staging and can be validated. 

I validated it myself specifically by going to the site on mobile and removing the mobile number, visiting the notifications and following the link to go back to the contact info page. Then I updated the mobile number and followed the update success alert link to verify that the user arrived at the top of the notification settings page after clicking on that link.
