### ISSUE TITLE
Update the instructions on Collaboration Cycle Kickoff - Moderator Responsibilities

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#48023]
## User Story
As a governance team member, I want to be able to respond to CC kickoff requests so that I can recommend the correct touchpoints to a team.

Assignee: @CherylEvans 
Peer Reviewer: @briandeconinck 

## Description
It was discovered while working on #47825 that the instructions for the Collaboration Cycle Kickoff - Moderator Responsibilities need some updating.

## Impacted Artifacts
[Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)

## Tasks
- [x] Add "Black out columns I though AX" to Step 3
- [x] In step 4, add a new step 1 to comment out the “If your product is already on VA.gov, please verify in Product Directory”. See GH ticket #47462 as an example. This will reorder the following steps
- [x] Read the document and confirm that the steps and process make sense and are ordered correctly

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team members understand the instruction in the Collaboration Cycle Kickoff - Moderator Responsibilities
- [x] Governance team members can recommend the correct touchpoints to teams

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
@CherylEvans I think the change from the second task isn't quite right. @allison0034 can confirm but I read it as meaning: Add an instruction for the moderator to comment out the product directory question in the CC ticket. That's a little different than what you did here. But I might also be misunderstanding?

**Comment by CherylEvans** [comment]
@briandeconinck @allison0034 I am not sure - step 1 to comment out the “If your product is already on VA.gov, please verify in Product Directory”. Does "comment out" mean delete?  I looked at the example, and noticed that there was nothing in the example reference the Product Directory.  Are you able to provide some additional guidance Allison?  :-)

**Comment by CherylEvans** [comment]
@briandeconinck @allison0034 I have edited to hopefully, get the intended message/action across.  Thoughts?
[Collaboration Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)

**Comment by briandeconinck** [comment]
I made one minor edit -- changed the formatting of the text to match the code format used in the other steps. Otherwise this looks good!

**Comment by CherylEvans** [comment]
@briandeconinck Thank you so much!!

**Comment by CherylEvans** [comment]
@briandeconinck I believe the AC has been met.  Are you good with my closing the ticket?
