### ISSUE TITLE
Fix headings in research findings template

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#48024]
## User Story
As a VFS researcher, I want to use templates that have proper heading hierarchy so that the completed artifact flows properly and meets our document expectations. 

Assignee: @CherylEvans 
Peer Reviewer: @allison0034 

## Description
The sections of the [research findings template ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/sharing-research/research-findings-template.md)all have h1 headings, except the Appendix section. The title should be the h1 and the rest of the headings should be h2's. 

## Impacted Artifacts
[Research Findings template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/sharing-research/research-findings-template.md)

## Tasks
- [x] Fix the headings in the document so they meet heading hierarchy expectations

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The research findings template has proper heading hierarchy

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
@allison0034 I assigned myself this ticket because I didn't understand the other 2 Tech-debt, Ready.  
I know this isn't tech-debt, it was easy.  :-)
PR - [48472](https://github.com/department-of-veterans-affairs/va.gov-team/pull/48472)
Do you mind doing a quick review?

**Comment by CherylEvans** [comment]
@allison0034 All headings now have h2 hierarchal headings, except the title, which has an h1 hierarchal heading.

**Comment by allison0034** [comment]
@CherylEvans awesome... looks good to me!

**Comment by CherylEvans** [comment]
@shiragoodman @allison0034 Thank you!

**Comment by shiragoodman** [comment]
@CherylEvans yes! Go for it. sorry for the delayed response.

**Comment by CherylEvans** [comment]
@shiragoodman Thank you!!
