### ISSUE TITLE
Create Automation for KMS Key Rotation/Record Re-encryption

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#48031]
## Issue Description
On a yearly cadence, AWS KMS keys are automatically rotated. An [alert is fired ](https://dsva.slack.com/archives/CQHBJ5U06/p1665493214364009)in the platform-console-services channel.

The automatic AWS KMS key rotation has NO effect on the existing records that it protects, so we need to manually re-encrypt existing database records in our Postgres database.

[This is the current documentation](https://vfs.atlassian.net/wiki/spaces/VI/pages/1982136325/Rotating+DB+Records+via+Sidekiq) for rotating records. BUT this was created on the initial implementation of adopting KMS.

---
## Tasks
- [ ] Split the records evenly across 5 (or more.. need to reassess) jobs. [See step one here](https://vfs.atlassian.net/wiki/spaces/VI/pages/1982136325/Rotating+DB+Records+via+Sidekiq)
- [ ] IMPORTANT: [Review this verified_decryptable_at ](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/workers/kms_encryption_verification_job.rb#L10)(Is this still a good solution??) [See this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33617), we had some issues with updated_at columns being touched, which caused claims to be sent in for re-processing
- [ ] Update the where clause here. The query will need to change because after the initial rotation, all records WILL have an encrypted_kms_key.

## Acceptance Criteria
- [ ] [Verify](https://vfs.atlassian.net/wiki/spaces/VI/pages/1982136325/Rotating+DB+Records+via+Sidekiq#Verifying-Rotation) that the rotation task completed successfully

**Comment by holdenhinkle** [comment]
Lindsey Hattamer:
I had a sec to dig in bit and the new where clause will most likely need to be something like `model.where("encrypted_kms_key NOT LIKE 'v2:%' AND encrypted_kms_key IS NOT NULL")` where I THINK (hard emphasis on think) v2 should be the new key version. So you'll want to rotate everything that isn't encrypted with the new key.

**Comment by oseasmoran73** [comment]
Verified in cloudtrail that keys have been rotated. Updated confluence documentation to view RotateKey page

**Comment by LindseySaari** [comment]
I worked with @holdenhinkle to flesh out some of the details around how to approach the record rotation. As stated above, @oseasmoran73, verified that the keys were in fact rotated on 10-11-2022. Since automatic KMS key rotation has **no effect** on the data that the KMS key protects, we will need to rotate the data keys manually.

Thankfully, the kms_encrypted gem provides a [rotation method](https://github.com/ankane/kms_encrypted#key-rotation) `.rotate_kms_key!` to re-encrypt existing database records. **Important:** Unfortunately, while testing in the dev environment, calling `.rotate_kms_key!` updates the updated_at timestamp of a record. In the previous rotation attempt using `.save`, SavedClaim records were marked for reprocessing when their `updated_at` columns were touched. We may need to [monkey patch this save method](https://github.com/ankane/kms_encrypted/blob/master/lib/kms_encrypted/model.rb#L183) to save(touch: false) to avoid  unintentional behavior. In Rails 5, by passing `touch: false` as an option to save, we can update the object without updating timestamps.

Todo:
1. Create a job that rotates the keys. **Important** keep in mind that we may need to [monkey patch this method](https://github.com/ankane/kms_encrypted/blob/master/lib/kms_encrypted/model.rb#L183) to use (touch: false) to avoid updating the record timestamps and unintentionally sending records back in for reprocessing. 

Example pseudocode
```
models.map(&:constantize).each do |m|
    m.rotate_kms_key!
end
```

2. Split the records evenly across jobs
3. Run the jobs via sidekick 

Unknowns/Issues
1. While testing in dev, we noticed while creating new records that the encrypted_kms_key (data key) is still prefixed with v1. We imagined that this would be prefixed with v2 since the keys in AWS KMS have now been rotated.

**Comment by holdenhinkle** [comment]
## How to delete all batches in Sidekiq

Start a `rails c` session and run the following:

```
require 'sidekiq/api'

Sidekiq::BatchSet.new.each do |batch|
  batch.delete
end
```

**Comment by holdenhinkle** [comment]
## How to delete EVERYTHING from Sidekiq

```
require 'sidekiq/api'

# Clear all queues
Sidekiq::Queue.all.each(&:clear)

# Clear retries and scheduled sets
Sidekiq::RetrySet.new.clear
Sidekiq::ScheduledSet.new.clear

# Clear batches
Sidekiq::BatchSet.new.each(&:delete)

# Clear unique jobs
if defined?(SidekiqUniqueJobs)
  SidekiqUniqueJobs::Digests.new.clear
end

# Clear job stats and history (Enterprise feature)
if defined?(Sidekiq::JobHistory)
  Sidekiq.redis {|conn| conn.del('stat:history')}
  Sidekiq::JobHistory::JobSet.new.clear
  Sidekiq::JobHistory::Cleaner.purge
end

# Clear rate limits (Enterprise feature)
if defined?(Sidekiq::Limiter)
  Sidekiq.redis {|conn| conn.keys('limit:*').each {|key| conn.del(key)}}
end

# Clear periodic cron jobs
if defined?(Sidekiq::Cron)
  Sidekiq::Cron::Job.destroy_all!
end

# Clear processed and failed stats
Sidekiq::Stats.new.reset

puts "Sidekiq has been cleared."
```
