### ISSUE TITLE
Update intro paragraph on STEM Scholarship page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#48033]
## Issue Description
Stakeholder Terry Warren asked us to update the intro paragraph on the [Edith Nourse Rogers STEM Scholarship page](https://www.va.gov/education/other-va-education-benefits/stem-scholarship/) to the following:

The Edith Nourse Rogers Science Technology Engineering Math (STEM) Scholarship allows eligible Post-911 GI Bill Veterans and Fry Scholars in high-demand fields to receive up to 9 months (or $30,000) of additional benefits. Read below to find out if you’re eligible.

He explained that the GAO has said that our original phrasing is misleading in that this is NOT an extension of the Post-9/11 GI Bill program, but is a stand-alone program.

We need to edit the provided content so that it meets plain language standards and adheres to our style guide. 

## Tasks
- [x] Rewrite and add content to Drupal
- [x] Review (Laura)
- [x] Send to stakeholder for approval (Laura)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Intro is updated on live site

**Comment by katherine-fung** [comment]
Hi @laurwill, I edited the intro paragraph, and 2 of the questions that mention "extending" GI Bill benefits. 

Here's the preview: 
http://preview-prod.vfs.va.gov/preview?nodeId=6860 

Here's the revision comparison: 
https://prod.cms.va.gov/node/6860/revisions/view/685715/689949/visual_inline

**Comment by katherine-fung** [comment]
Hi @laurwill, I edited the intro paragraph, and 2 of the questions that mention "extending" GI Bill benefits. 

Here's the preview: 
http://preview-prod.vfs.va.gov/preview?nodeId=6860 

Here's the revision comparison: 
https://prod.cms.va.gov/node/6860/revisions/view/685715/689949/visual_inline

**Comment by laurwill** [comment]
Thanks @katherine-fung ! I like the way you adjusted to avoid the "Post 9/11 GI Bill Veteran" phrasing, and I think what you did will work. But it's also possible that we need to avoid classifying these benefits as "additional GI Bill or Fry benefits" and more as "Nourse benefits for people who were using GI Bill or Fry" instead. But this is a question for the stakeholder! So I'll send an email to Terry today to confirm.

I also tweaked the into to shorten the first sentence — I see why you moved the "9 months or $30,000" there, but it makes that sentence too long.

Also noting that once Terry confirms that this language works, we'll need to make similar changes on these pages that mention Nourse:
- https://www.va.gov/education/other-va-education-benefits/ 
- https://www.va.gov/education/about-gi-bill-benefits/
- https://www.va.gov/education/about-gi-bill-benefits/post-9-11/ (more info box at bottom)
- https://www.va.gov/education/survivor-dependent-benefits/fry-scholarship/ (more info box at bottom)
- https://www.va.gov/resources/getting-a-gi-bill-extension/ (I think we can suggest phrasing here to make clear it's not an extension, but another way to get additional benefits)

**Comment by RLHecht** [comment]
Update: Laura sent the content to stakeholders 10/25 for approval.

**Comment by katherine-fung** [comment]
- [ ] https://www.va.gov/education/other-va-education-benefits/
No changes to this page since January 2022, so I didn't revert. 

I added the new approved language about the STEM scholarship. 

I made a small tweak because this page lists each program with a sentence, "If you ___, you may be eligible." I added: "If you use the Post-9/11 GI Bill or the Fry Scholarship and you've worked towards a STEM degree, you may be eligible." [I used "you've worked" to cover undergrads and those who have already gotten STEM degrees, which are both eligible groups.]

[Noting that this page also says people can check their eligibility for the National Call to Service program if we do end up changing/removing info about it from the site. ]

- [ ] https://www.va.gov/education/about-gi-bill-benefits/
- [ ] https://www.va.gov/education/about-gi-bill-benefits/post-9-11/ (more info box at bottom)
- [ ] https://www.va.gov/education/survivor-dependent-benefits/fry-scholarship/ (more info box at bottom)
- [ ] https://www.va.gov/resources/getting-a-gi-bill-extension/ (I think we can suggest phrasing here to make clear it's not an extension, but another way to get additional benefits)

**Comment by laurwill** [comment]
Thanks so much @katherine-fung ! As we chatted, I slimmed down some of the changes to related pages to avoid overly long blurb paragraphs. See some notes back to you in bold above.

Hi @megzehn ,
We're good to go on these changes — you can copyedit and publish. We told them these would go live by next week, so you can fit these in as you have time.

On the main page, we made changes to intro paragraph and "What benefits can I get?" H3 farther down the page. I also made small tweaks to link formatting, adding TTY, etc.
http://preview-prod.vfs.va.gov/preview?nodeId=6860

Pages with changes only to the STEM scholarship sections:
- Other VA benefits: http://preview-prod.vfs.va.gov/preview?nodeId=945
- GI Bill: http://preview-prod.vfs.va.gov/preview?nodeId=915
- Post-9/11 GI Bill: http://preview-prod.vfs.va.gov/preview?nodeId=935
- Fry Scholarship: http://preview-prod.vfs.va.gov/preview?nodeId=951
- GI Bill extension: http://preview-prod.vfs.va.gov/preview?nodeId=41926

Also noting again here that some of these pages were reverted due to links to unpublished rates pages — could you double check the revision logs and any link alerts to make sure we're only publishing STEM scholarship changes? 

Once these are live, next step will be to restore the rates changes on those pages. Thank you!

**Comment by megzehn** [comment]
Thanks, @laurwill! 

I will check off this list as these get published:

- [ ] Main page: http://preview-prod.vfs.va.gov/preview?nodeId=6860
- [ ] Other VA benefits: http://preview-prod.vfs.va.gov/preview?nodeId=945
- [ ] GI Bill: http://preview-prod.vfs.va.gov/preview?nodeId=915
- [ ] Post-9/11 GI Bill: http://preview-prod.vfs.va.gov/preview?nodeId=935
- [ ] Fry Scholarship: http://preview-prod.vfs.va.gov/preview?nodeId=951
- [ ] GI Bill extension: http://preview-prod.vfs.va.gov/preview?nodeId=41926

**Comment by megzehn** [comment]
Hi @RLHecht! Confirming that these all have been reviewed and published. 

Thanks @laurwill and @katherine-fung!

**Comment by RLHecht** [comment]
These are all live. Closing ticket.

**Comment by megzehn** [comment]
Confirming that I reverted the Fry and Post-9/11 pages and added back in the changes we made.
