### ISSUE TITLE
Update the Design System Staging Review

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#48039]
## User Story
As a governance team member, I want to be able to respond to design system staging review requests so that I can finish scheduling the meeting.

Assignee: @allison0034 
Peer Reviewer: @sterkenburgsara 

## Description
While working on #47825, it was discovered that the Design System Staging Review document was out of date and the instructions are no longer correct.

## Impacted Artifacts
[Design System Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1936490517/Design+System+Staging+Review)

## Tasks
- [x] The whole “pre-schedule” section needs to be updated for Calendly. Reference the moderator responsibilities doc for staging.
- [x] Remove Rachael Roueche from Step 3
- [x] Remove the Design System attendees listed in the github ticket
- [x] Change #vsp-collaboration-cycle to #platform-collaboration-cycle
- [x] Review the page as a whole to see if the instructions make sense

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team members understand how to finish scheduling a design system staging review

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@allison0034 @sterkenburgsara I decided to add this to the sprint after our planning meeting. Please review and let me know if you have any questions.

**Comment by allison0034** [comment]
@sterkenburgsara [the draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2422145025/48039+-+Allison+-+Design+System+Staging+Review) is ready for a peer review. It might be easiest to walk thru this on Zoom since you are still new, let me know.

**Comment by sterkenburgsara** [comment]
@allison0034 Thanks for walking through it with me. Everything looks good.
