### ISSUE TITLE
Modify process to connect Shared Support if/when additional support may be needed

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#48043]
## User Story
As a Governance team member, I want to be able to reach out to Shared Support team when I identify a VFS product in need of accessibility help so that Shared Support team is able to make that connection and provide necessary support.

As a Shared Support team member, I want to know when VFS teams may need additional accessibility support so that I may connect with them and provide the necessary support. 

Assignee: @allison0034 @sterkenburgsara 
Peer Reviewer: @it-harrison 

## Description
Shared Support team is partnering with Governance team to help provide more dedicated accessibility support to VFS teams. Platform Leadership has asked that this connection to VFS teams be completed through the Collaboration Cycle. Opposed to inviting Shared Support to all scheduled Collaboration Cycle reviews, it has been decided that post Design Intent (and post Midpoint Review, if necessary) that Governance team, through the Accessibility Feedback ticket, connect the VFS team to the Shared Support team. 

## Impacted Artifacts
[How to provide feedback for a Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1934426130/How+to+provide+feedback+for+a+Design+Intent)
- NOTE: at this time, there is no document for 'how to complete an accessibility review for a Design Intent' (work to be completed in epic #39744). Because of this, at this time we will just add a note for Accessibility specialists in the above guidance document.
How to provide feedback for a Midpoint Review

## Tasks
- [x] Shira to meet with Eli to define preferred process
- [x] Agreed upon process:
   - Governance team member to add `Shared Support Team` label to the Accessibility Feedback ticket
   - Governance team member to tag @eli-oat under 'Consider' in the body of the a11y feedback ticket and say, "The Shared Support team is able to provide additional accessibility support. FYSA @eli-oat " 
- [x] Connect with @briandeconinck for his awareness

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Shared Support team is contacted by Governance team via the Accessibility Feedback ticket at Design Intent and Midpoint Review if/when it is identified that the VFS team needs accessibility support

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@allison0034 I met with Eli today and we documented an agreed upon process for how we will connect the VFS to the Shared Support team. Please let me know if you have any questions!

**Comment by allison0034** [comment]
@it-harrison this is ready for a peer review. The tasks have been added under step 3, if you have feedback.

**Comment by it-harrison** [comment]
@allison0034 looks good!
