### ISSUE TITLE
Testing: vets-api server to EKS in dev

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#48045]
Step 7 of the vet-api server migration [process](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2451767319/Promote+Vets-API+Server+with+EKS+Process+Outline).

**DEFINITION OF DONE**
- [x] Review and test each health checks to ensure we can properly access each health check
- [x] Add/edit health checks as needed (per testing)
- [x] Conditional routing of traffic to EKS is ready so testing is accurate.
- [x] A/B routing is complete 
- [ ] Manual testing complete
- [ ] Synthetic testing is complete
- [ ] Load testing
