### ISSUE TITLE
Define relationship between teams

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#48042]
## User Story
As a team member supporting Governance team or Shared Support team, I want to understand the roles/responsibilities of each team and the relationship between both teams so that I may provide appropriate support and guidance.

Assignee: @shiragoodman @eli-oat 
Peer Reviewer: @allison0034 

## Description
Shared Support team is partnering with Governance team for accessibility. The purpose of this ticket is to define the relationship, including roles and responsibilities of each team, so that each team is able to provide support to VFS in an appropriate manner. The artifact that is produced from this definition should be shared and should be visible and easily available to both teams.

## Impacted Artifacts
New artifact - [see draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2403041503/48042+-+Shared+Support+Governance+relationship+draft)

## Tasks
- [x] @shiragoodman and @eli-oat to work together to draft artifact
- [x] Artifact should include:
   - [x] mission of Governance
   - [x] mission of Shared Support
   - [x] roles/responsibilities of Governance
   - [x] roles/responsibilities of Shared Support
   - [x] links to related guidance
- [x] artifact is shared with Shared Support and Governance team members
- [x] Shared Support and Governance team members to review and respond with any questions/concerns
- [x] Changes made, if necessary
- [x] Artifact shared with @raywangoctova, @humancompanion-usds and @artsymartha68 for review/approval
- [x] Artifact published in public space, available to both teams 

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Shared Support and Governance team members know and understand the working relationship between their teams

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
Hi @shiragoodman @briandeconinck this document makes sense, but I do have a few comments:

1. Why does it have TL;DR,?
2. The flow is a bit weird to me. Breaking it into a mission statement for each, then Dependencies and Roles & Responsibilities for each. If I am a Governance team member and reading this I feel like I start to understand it and then get side tracked by the Shared Support information, then back to Governance team information. But maybe that is just me.
3. It feels very sterile. That is not necessarily a bad thing, but it is written very different from our other documentation.

But like I said, I understand what this document is about.

**Comment by shiragoodman** [comment]
@allison0034 I reordered the doc a bit so it groups all of Governance and all of Shared Support. I also changed "TLDR" to, "summary".

**Comment by allison0034** [comment]
Flows better thank you!

**Comment by shiragoodman** [comment]
Modified artifact per OCTO feedback and published to new location: https://vfs.atlassian.net/wiki/spaces/PPS/pages/2432663602/Shared+Support+and+Governance+Team+Partnership

**Comment by allison0034** [comment]
This looks good... thank you Shira!
