### ISSUE TITLE
Midpoint Review [Sitewide Homepage, VA.gov homepage redesign]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#48041]
# NOTE
This template is being deprecated. If your kickoff meeting took place after May 26, 2022, you should be following the guidance specified in the Collaboration Cycle Rquest per the [May 26, 2022 change history post](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Change-history.1846870032.html) instead. If you are unsure if this applies to you, please reach out to the Governance Team on the vfs-platform-support Slack channel.

# Steps to complete Midpoint Review 

## Before meeting

**VFS Product Manager**
- [x]  Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees). 
- [x] Notify the Collaboration Cycle team of this ticket with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)). 
- [ ]  Add artifacts listed below to the ticket at least 2 days before scheduled meeting. 

**Platform**
- [ ] Add the Platform reviewers to scheduled meeting
- [ ] Add Zoom information to scheduled meeting (if synchronous)
- [ ] Create feedback tickets and link to the Midpoint Review epic (if no feedback, please comment stating that). 

## After meeting
**VFS Product Manager**
- [ ] Respond to feedback tickets.
- [ ] Close this ticket when review is complete and feedback has been addressed.  

**Platform**
- [ ] Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 

### Has your team met with the Sitewide Content team for content support? 
- [x] Yes*
- [ ] No

\*If yes, please include any relevant content artifacts.
Ryan and Danielle met and made real time content changes to the [Sketch file (Round 2)](https://www.sketch.com/s/3aa40506-4be2-46cc-876b-93f1a9f3a857/p/DD9CFAD9-2A54-41AB-9149-DD1BAC2EB1AF/canvas)

## Artifacts

Provide links or documents for the following: 
- [x] Implementation is currently live (and held) in staging at https://staging.va.gov/homepage-test/
- [x] [Homepage Redesign Initiative Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/home-page-redesign-initiative/initiative-brief.md#home-page-redesign-initiative-brief)
- [x] [Finalized design prototype or mockup - Sketch file (Round 2)](https://www.sketch.com/s/3aa40506-4be2-46cc-876b-93f1a9f3a857/p/DD9CFAD9-2A54-41AB-9149-DD1BAC2EB1AF/canvas)

Veteran top task moderated/unmoderated sessions and an initial round of usability research informed this latest design iteration which will be tested with Veterans and other beneficiaries the week of October 24th

Artifacts for previous research
- [x] [Moderated research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/research/Veteran-tasks/moderated/research-findings.md) | June 2022
- [x] [Unmoderated top task findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/research/Veteran-tasks/unmoderated/research-findings.md) | June 2022
- [x] [Usability findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/research/redesign-usability/research-findings.md) | July 2022

Artifacts for upcoming research (which will focus on mobile/smart phone and screenreader participants) 
- [x] [Research plan - Redesign Usability Round 2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/research/2022-09-redesign-usability-round2/research-plan.md) | October 2022
- [x] [Conversation guide - Redesign Usability Round 2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/research/2022-09-redesign-usability-round2/conversation-guide.md) | October 2022

### Content artifacts 

- [x] Your product’s content source of truth - _The staging implementation is currently hard-coded static content. The content was provided/approved by Danielle and incorporated into the Sketch file. Links below are for tasks to "drupalize" the content blocks, moving much of the page to using Drupal as the source of truth._
- [x] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
      - [Drupalize new Homepage components](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10626)
      - [Design iteration feedback#10982](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10982)
 
### QA artifacts

[Learn more about QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [x] [Link to test cases/test plan in TestRail (draft OK)](https://dsvavsp.testrail.io/index.php?/runs/view/3824&group_by=cases:section_id&group_order=asc&group_id=4473)

## Asynchronous review option
Would you like this review to be asynchronous? 

Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review.
- [x] Yes
- [ ] No

## Scheduling
- You will need to use Calendly to schedule both synchronous and asynchronous reviews (asynchronous reviews will not have a Zoom link).
- Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information
Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Midpoint Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) on Platform website for more information about the Collaboration Cycle.

FYI: @shiragoodman

**Comment by mmiddaugh** [comment]
Async review scheduled 2:00pm - 2:30pm, ET Friday, October 21, 2022

**Comment by shiragoodman** [comment]
@sterkenburgsara [here is the Design Intent ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/39038)from March 2022.

**Comment by CherylEvans** [comment]
No Content feedback at this time.  Looks great!

**Comment by mmiddaugh** [comment]
@shiragoodman is there any feedback from Design or Accessibility?

**Comment by shiragoodman** [comment]
Have you seen the IA and QA feedback?

**Comment by mmiddaugh** [comment]
my view isn't showing any linked issues...I'll look for them another way. Thank you for the heads up

**Comment by shiragoodman** [comment]
I know a lot of folks have been having issues with ZenHub lately. You should be added as an assignee to the feedback tickets so you can easily find. You can filter on the `collab-cycle-feedback`, `sitewide` and `VA.gov homepage` labels.
