### ISSUE TITLE
[Support] Analytics Implementation and QA for Vimeo Tracking

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#4806]
# Analytics Implementation or QA Request
As a content producer, I want to understand the engagement of Vimeo hosted videos that appear on the va.gov domain.

## Description
- Is this request for Google Analytics implementation or QA?
Implementation

- Who is this request for?
David Watson at MHV

    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
MHV
    
- Provide the Domain where Google Analytics needs to be implemented
    Across Modernized and legacy content [Use WBC and Modernized Google Tag Manager containers]
    
    _Identify if PII is passed in URL or title tag_
    
    - [Provide Domain here]
- Please publish by 01/15/2020

- Typical Website Interactions to Track:

 - Video Plays, Pause, and Stops
 - Percentage watched

## Acceptance Criteria
- [ ] Implement within modernized and WBC containers
- [ ] QA has been completed

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
cc: @nedierecel @joanneesteban 

Tracking is staged for publishing in the 'Vimeo Tracking' workspace

Waiting to here from David Watson via email on if small gaps between Vimeo-Youtube will suffice for tomorrow's promotion. [Testing page used here](https://www.myhealth.va.gov/mhv-portal-web/ss20180620-understanding-acute-chronic-pain)

Vimeo tracking as it stands will cover: 
- Plays
- Pauses
- Unpauses
- Percentage watched 25/50/75
- Completed
- Video title as custom dimension

**Comment by jonwehausen** [comment]
David has confirmed the above functionality will support this request.

**Comment by jonwehausen** [comment]
Story has been published within both modernized and brand consolidation containers.
