### ISSUE TITLE
Add GitHub team name to VFS Team Roster

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#48107]
## User Story
As a Platform team member, I want to add Github team name to the VFS team Roster so that I may be able to provide better, quicker support to VFS teams.

Assignee: @allison0034 
Peer Reviewer: @briandeconinck 

## Description
@mchelen-gov has asked that we add the Github team name to the VFS team roster. In addition to adding a column, we will also need to a) modify the New VFS team process to request the github team name, and b) connect with existing VFS teams on the roster to capture their github team name.

## Impacted Artifacts
[New VFS Team gh ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team%2C+analytics-insights&template=new-vfs-team.md&title=New+VFS+Team+%5BInsert+team+name+here%5D)
[VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665) - VFS Teams tab

## Tasks
- [x] Modify the[ VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2444951)/VFS Teams tab to add a new column titled, "GitHub Team Name"
   - Note: the column will be blank for now. Shira is going to create another ticket for collecting this information from VFS teams. 
- [x] Modify the[ New VFS Team template ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team%2C+analytics-insights&template=new-vfs-team.md&title=New+VFS+Team+%5BInsert+team+name+here%5D)to request the GitHub Team Name

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] The VFS Team Roster reflects the gh team name
- [ ] The New VFS Team template requests the gh team name

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
@briandeconinck this si ready for review and PR is linked.

**Comment by shiragoodman** [comment]
Backfill missing GitHub team name information in VFS Team Roster.

**Comment by briandeconinck** [comment]
@allison0034 Approved and merged the PR.
