### ISSUE TITLE
[FE] Display Error Message when there is a BTSSS API Error

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#48104]
## User Story
When the BTSSS API returns an error message, we should let the user know that we are unable to file their claim and give them information about how to file a claim later.
 
## Wireframes
See wireframes attached to this [ticket](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/47787)

## Tasks
- [ ] [FE] add an error page
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
