### ISSUE TITLE
[CST]: Update CST code to work with Lighthouse Claims Status API endpoint (EVSS to Lighthouse migration)

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#48118]
As part of the upcoming migration away from EVSS to Lighthouse APIs, we need to update CST to call Lighthouse end points instead of EVSS. 

# Tasks

### Preliminary
- [x] #49505
- [x] #49503
- [x] #49508
- [x] #50028
- [x] #50030

### Administrative

- [x] #50986

### Frontend Only
- [x] #50036
- [x] #51603

### Backend Only
- [x] #50032
- [x] #50031
- [x] #50029
- [x] #49504

### Frontend and Backend
- [x] #49863 
- [x] #50034
- [ ] #50038
- [x] #50037 
- [x] #50076

### Devops
- [x] #51458
- [x] #51591

# Acceptance Criteria

- [ ] Swap EVSS end point URLs with new Lighthouse URLs
- [ ] CST is ready for functional testing using new API services
- [ ] Necessary feature flags in place to enable functional testing in appropriate environments
- [ ] In coordination with Lighthouse, verify, jointly, all services are working correct and calls are successfully made.
- [ ] Verify that the correct attributes are being sent back via the end user UI.

# open questions
- is this a staged rollout? 25/50/75
- How are we supporting the 5013 waiver? Are we supporting it at all?

**Comment by jacobworrell** [comment]
@samcoforma @jerekshoe please break apart this ticket into workable slices.
