### ISSUE TITLE
COVID FAQ updates — facility status messages

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#48112]
## Issue Description
We need to update the [Covid FAQ page](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/#claims-and-applications) to align with work on [Covid facility status levels](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45855#event-7423230107)

We'll adjust the alert at top of page and the health protection levels section.

We need to confirm timing for launch of new facility status messages with David Shannon before we can make these updates.

---
## Tasks
- [ ] Update Drupal (Laura)
- [ ] Review (Danielle)
- [ ] Copyedit (Megan)
- [ ] Prepub and publish (Megan)

## Acceptance Criteria
- [ ] FAQ page is updated to reflect new facility status messages

**Comment by mistymg** [comment]
Ticket was moved to Closed column but not actually closed.
