### ISSUE TITLE
[Analytics] Discovery for the Profile team: Are we tracking the "I live on a United States military base outside of the United States." checkbox?

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#48111]
### Background

@michelle-dooley -- I know you all are swamped right now, and this is a non-urgent request. Feel free to put this in your backlog and prioritize when you're eventually able.

The VA.gov profile team needs help answering the following question: Are we currently tracking how many people save a `Mailing address` or `Home address` with the "I live on a United States military base outside of the United States." checkbox checked? This can be found at https://www.va.gov/profile/contact-information.

![image](https://user-images.githubusercontent.com/34068740/195192667-7b3c394c-361e-4231-a5ad-d2f2afd14170.png)
![image](https://user-images.githubusercontent.com/34068740/195192600-f5ecd06f-5fa3-48be-85a3-31ef90bc5a26.png)

If so, great! If not, let us know. We'd create a separate ticket for implementation.

### Tasks

- [ ] Investigate whether we are tracking how many people save a `Mailing address` or `Home address` with the "I live on a United States military base outside of the United States." checkbox checked
- [ ] Report back to our team
- [ ] Determine next steps (if not tracking, we'll create a ticket for implementation)

**Comment by Samara-Strauss** [comment]
cc/ @SKasimow and @tpharrison that I created this ticket. In order for us to understand how serious of a bug #48040 is, we need to understand how many people who check "I live on a United States military base outside of the United States." are going through address validation. The first part of that is determining if we are even tracking how many people submit the mailing address forms with "I live on a United States military base outside of the United States." checked.

Just a heads-up that Michelle is extremely short-staffed on their team, so it may take a few weeks before they have bandwidth for this.

**Comment by SKasimow** [comment]
I'll pop into office hours tomo and see if they can walk me through how to do this myself.

**Comment by Samara-Strauss** [comment]
Thanks @SKasimow! We may not be tracking this checkbox, so if we're not, our next step would be to create a formal request to add tracking when the analytics team has bandwidth.

**Comment by Samara-Strauss** [comment]
Update: Adam confirmed we are not tracking this checkbox in analytics, so our team doesn't need anything else at this point. Thanks!
