### ISSUE TITLE
[Research] 10-10CG - Facilities (and baseline): Run Facilities/Usability Research Sessions for 10-10CG

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#48127]
## Issue Description
Conduct the usability research sessions on the 10-10CG for overall tasks and new facilities updates.

## Resources
- [Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/research/2023-04-Facilities%20and%20Overall%20Usability%20Research/research-plan.md)
- [Conversation Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/research/2023-04-Facilities%20and%20Overall%20Usability%20Research/conversation-guide.md)
- [ ] Link to Research Review ticket once opened
- [ ] Link to item on Research Repo

---
## Tasks
- [Platform Research Checklist - Conduct Sessions](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist#ResearchChecklist-5.Conductsessions)

## Acceptance Criteria
- [ ] Moderate all sessions scheduled 
- [ ] Complete tasks for before, during and after research sessions

---
