### ISSUE TITLE
Create keyword to auto response mappings

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#48137]
### Tasks
- [ ] Create a list of keywords about the deployment process would result in accompanying information we already have instructions in this section: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2401239503/2022+Q4+Include+Platform+Content+into+Slack+Support+Bot

- [ ] Map keywords to appropriate URLs on a spreadsheet

- [ ] Request to add those auto-responses to our existing slack support bot form

**RISKS**
If we link to our existing support documentation within the "About the Platform" section of Confluence and the customer is a VFS team member, they will NOT be able to access it.

**Comment by johnny-jesensky-adhoc** [comment]
As part of the icebox [audit ticket](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/69802) in Sprint 41, moving this to the backlog. Will need some additional refinement.

**Comment by johnny-jesensky-adhoc** [comment]
This key-word to documentation mapping already exists as part of [this spreadsheet](https://docs.google.com/spreadsheets/d/1TItdfPMH_TiXEhgMKEqxIW2e5EaMKy4cHaBhaeQ7drU/edit#gid=604576535). There is an opportunity to improve the accuracy of these auto-responses, though that should live in a separate ticket as part of collaboration work being done with the Support Team. 

Will be closing this, and working with Joe Knipes and Alyssa to determine opportunities to improve accuracy of Support Bot doc recommendations.
