### ISSUE TITLE
Supplemental Claims | Select Claimant type

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#48135]
## Value Statement
**_As a_** Veteran
**_I want to_** designate myself as the claimant
**_So that_** I can file a supplemental claim on VA.gov.

---
## Background Context
For MVP, we are only supporting Veterans as the claimant. Those who do not identify as a Veteran will need to either fill out the PDF or go to an authorized representative to file their claim. 

## Acceptance Criteria
- [ ] The user must select either **Veteran** or **Other** to progress by choosing **Continue**
- [ ] If the user selects **Other**, they cannot complete the form.
- [ ] If the user selects Back, they are redirected to the previous screen.
- [ ] Complete E2E tests
- [ ] Complete unit tests 

## Designs and Build Notes
- [DRAFT DESIGNS (NOT APPROVED)](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/v/zOgln5/p/41CB25C6-4BB6-4613-967E-AA5BCF0713E0/canvas?posX=-3714.186279296875&posY=-75.44134521484375&zoom=0.6182108521461487)

## Out of scope
- Other claimant roles

## Open questions
- Where is the user directed if they select **Other**?
- What are the accessibility criteria?

## Tasks
- [ ] Add here
- [ ] Add here

## Definition of Ready
- [ ] _Clear value description_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
@joshkimux Hey! What would be the best way to get accessibility AC written into this story?

**Comment by joshkimux** [comment]
@saderagsdale great question! My gut would say to go for process based acceptance criteria (if that's a thing 😅 ) as opposed to design specific criteria (which may depend on the context)

Review select claimant type with an a11y specialist...
- [ ] As low-fidelity wireframes before the design intent or as soon as possible
- [ ] As high-fidelity wireframes before engineering handoff
- [ ] As a staging prototype

If a11y specialist documents a11y issue(s) in any of the reviews:
- [ ] Fix the identified issue(s)
- [ ] Review with the a11y specialist that the issue(s) have been fixed
- [ ] Close the identified issue(s)

If usability testing takes place:
- [ ] Test with disabled Veterans who use assistive technology (like screen readers)
