### ISSUE TITLE
Supplemental Claims | Build the Form

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#48138]
## Value Statement
**_As a_** team
**_We want to_** define the development work for MVP Supplemental Claims
**_So that_** we can build the form incrementally.

---
## Background Context
This epic of epics aims to track the development work required to build the form. Here you'll find helpful documentation, attachments of epics related to various sections of the form, and other way-finding materials. 

[Product development guide](https://docs.google.com/document/d/1qPB2yZf_TXz8n8X7c9dADYmIwSl1LvOuH5S8ocAz6RE/edit#)

## <span id="use-cases">MVP Use Cases</span>

- As a Veteran, I want to quickly understand if a supplemental claim is the right appeal pathway for me, so that I can choose the best pathway for my needs.
- As a Veteran, I want to access all standard footer dropdowns, so that I have a consistent navigation experience.
- As a Veteran, I want the ability to file for disability compensation benefits, so that I can pursue a more favorable decision. 
- As a Veteran, I want to file a supplemental claim on VA.gov, so that I can avoid using the paper form for submission.
- As a Veteran, I want my personal info to be pre-filled, so I don't have to add info the VA already has on file. 
- As a Veteran, I want to add issues to my claim, so the VA knows which issues to compare my new and relevant evidence to.
- As a Veteran, I want to review the issues I'm claiming and be able to edit and correct my choices.
- As a Veteran, I want to opt into the AMA process so that my claims can benefit from faster processing.
- As a Veteran, I want to confirm that I understand the evidence necessary to substantiate a claim for disability compensation benefits so that I can file my claim quickly and efficiently. 
- As a Veteran, I want the VA to help me retrieve evidence from a VA-operated treatment center, so I can use it to pursue a favorable decision.
- As a Veteran, I want to upload evidence from a VA treatment center, so I can use it to pursue a favorable decision.
- As a Veteran, I want to submit VA forms [21-4142](https://www.va.gov/find-forms/about-form-21-4142/) and [21-4142a](https://www.va.gov/find-forms/about-form-21-4142a/), so I can authorize the VA to get medical provider information from a non-VA source like a private doctor or hospital.
- As a Veteran, I want the VA to help me retrieve evidence from a private treatment center, so I can use it to pursue a favorable decision.
- As a Veteran, I want to upload evidence from a private treatment center, so I can use it to pursue a favorable decision.
- As a Veteran, I want to upload supporting evidence documents that support my claim.
- As a Veteran, I want to review the evidence I am requesting or uploading to support my claim and make corrections to location, date, or document.
- As a Veteran, I want my signature to be applied upon submission, so I don't have to worry about making a mistake in the signature section.

## Definition of Done (product)

To complete the MVP version of Supplemental Claims, we'll meet the following criteria:

- [x] Working in staging and production.
- [x] Passed usability testing
- [x] Passed E2E testing (90% coverage)
- [x] Passed unit testing (90% coverage)
- [x] Passed accessibility testing (launch blockers)
Documentation we must have:
- [x] Staging URL and staging test-user information
- [x] Product outline
- [x] Release plan with the "Planning" sections completed
- [x] Content source of truth
- [x] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
- [x] Product test cases/test plan in TestRail with test execution logs
- [x] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12
- [x] [Summary(Defects) reports in TestRail](https://dsvavsp.testrail.io/index.php?/reports/view/14)
Accessibility artifacts
- [x] [Completed TestRail Platform accessibility test plan](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc). (Preferred) OR a list of known issues
- [x] The final product is tested and code complete under a feature toggle set to 0% for incremental release.

## Definition of Done (user story) 

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

## Designs and Build Notes
- [MVP use cases](https://docs.google.com/spreadsheets/d/105EJZLOW5r1PuCG0rzm6nLjh32Aa1Zgktsi9JnoecSY/edit#gid=0)
- [DESIGN](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89)
- [CONTENT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/sourceofcontenttruth.md)
- [Prototype](https://www.figma.com/proto/JveclTFbNNSmx4eiYwbZdZ/Supplemental-Claims?node-id=70%3A5676&scaling=scale-down&page-id=10%3A1697&starting-point-node-id=70%3A5676)

## Out of scope
- Non-Veteran roles
- Homeless flash
- Benefit types other than disability compensation
- Routing claims to MAS
- Integrating form 4138 (buddy statement)
- Automating supplemental claims

---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
