### ISSUE TITLE
FE | Profile | Custom Analytics Implementation for Multiple Errors on Address Validation

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#48147]
## Background

We want to determine how frequently a user may run into multiple address validation errors when adding or updating their home or mailing address. This may be especially problematic for screenreader users as the screenreader typically reads out only the first or last error.

To implement tracking we will use a GA custom event to track the number of address additions or updates along with # of address validation errors shown upon submit.

## Tasks

- [x] Set up custom event as follows: 
- Event Action: Status: {{Address Validation - Multiple Errors;#} - Title: {{}}- Click Text: {{}}

- [x] Conduct Unit tests 
- [x] Run E2E tests covering current code and regression
- [x] All axe checks pass
- [ ] Test with PM in staging and review reporting
  

## Acceptance Criteria
- [x] Complete all unit testing
- [x] End-to-end tests showing 0 violations
- [x] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)?
- How can this work be validated?
- What updates need to be made (e.g. product outline, use cases, contact center guide)

## Associated Tickets
- #46731

**Comment by adamwhitlock1** [comment]
I've got this up and running on prod and events are being fired. Here are 2 examples of the events being sent:

![Screen Shot 2022-10-27 at 9.48.41 AM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/1511c4a0-2661-4363-bf47-97725fb8a722)

![Screen Shot 2022-10-27 at 9.48.07 AM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/ee18ec1d-0ad4-40e7-a163-058effafda37)

**Comment by SKasimow** [comment]
Hey @adamwhitlock1 - Looks good; I set up a widget [here](https://analytics.google.com/analytics/web/#/dashboard/3Z1vT6SlQqevdav1s72QwA/a50123418w177519031p176188361/) if you want to take a look and then we can close.
