### ISSUE TITLE
Announce new research artifacts in #research-ops channel

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#48140]
## Description
Announce 3 new research-related artifacts now available on the Platform Website/Research space.

Assignee: @naomimarcussen 

## Impacted Artifacts
#41696, #41667, & #41709

## Tasks
- [ ] Announce in the #research-ops Slack channel the 3 new guidance docs on Platform Website

## Acceptance Criteria
- [ ] VFS teams are notified via #research-ops Slack channel of new guidance on PW

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@naomimarcussen since both the inclusive research and discovery research tickets are on hold, I am removing the dependencies for them. However, we still need to announce the new synthesis guidance once published.
