### ISSUE TITLE
Supplemental Claims | Select Benefit Type

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#48142]
## Value Statement
**_As a_** Veteran
**_I want to_** file a supplemental claim for disability compensation benefits
**_So that_** I can receive a favorable decision.

---
## Background Context
For MVP, we are only enabling Veterans to file for disability compensation. For other benefit types, Veterans need to either fill out the PDF or go to an authorized representative to file their claim. 

## Acceptance Criteria
- [ ] The user must select either **Disability compensation** or **Another type of claim** to progress by choosing **Continue**
- [ ] If the user selects **Another type of claim**, they cannot complete the form online, and they are redirected to the PDF download option.
- [ ] If the user selects Back, they are redirected to the previous screen.
- [ ] Unit tests complete (90% coverage)
- [ ] E2E tests complete
- [ ] Accessibility testing complete
- [ ] Reviewed and approved by product and/or design

## Designs and Build Notes
- [DESIGN](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/v/Mdvgll/p/0454C07B-0B34-46F7-9287-200FD43F78D5/canvas?posX=-586.8563232421875&posY=-56.14762878417969&zoom=0.9312365055084229)
- [CONTENT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/sourceofcontenttruth.md)
- [Prototype](https://www.figma.com/proto/JveclTFbNNSmx4eiYwbZdZ/Supplemental-Claims?node-id=70%3A5676&scaling=scale-down&page-id=10%3A1697&starting-point-node-id=70%3A5676)

## Out of scope
- Other benefit types

## Tasks
- [X] Design approved
- [X] Content approved

## Definition of Ready (user story)
- [x] _Clear value description_
- [x] _Testable acceptance criteria_
- [x] _Accessibility added to acceptance criteria_
- [x] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [x] _Estimated to fit within the sprint_
- [x] _Dependencies and blockers linked_

## Definition of Done (user story) 

- [ ] Meets acceptance criteria
- [x] Passed E2E testing (90% coverage)
- [x] Passed unit testing (90% coverage)
- [x] Passed integration testing (if applicable)
- [x] Code reviewed (internal)
- [x] Submitted to staging
- [x] Reviewed and approved by product and/or design
---

**Comment by thehastingsp** [comment]
design approved, content still in progress.

**Comment by thehastingsp** [comment]
Added prototype to ticket

**Comment by thehastingsp** [comment]
@Mottie [content approved](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/sourceofcontenttruth.md).

**Comment by Mottie** [comment]
This work has been merged and should be available in staging soon.
