### ISSUE TITLE
Profile Team | Sprint 86 | Nov 2 - Nov 15 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#48149]
## PTO/OOO/Unavailable

- **Adam**: 11/11, 11/14
- **Christina**:  
- **Sharon**:  11/11
- **Tom**:  
- **Samara**:  11/11
- **Liz**:  
- **John**: 11/8, 11/11
- **Erica**:  Nov 4

**Note: Veteran's Day Nov 11th**

## Retro Board is open!:
- [ ] [Sprint 85](https://www.reetro.app/board/6203c8f3edfa6100174612bb/633c701adb1fde17f3c8b447)

---

## Sprint Priorities:
- Continue accessibility work
- Recommendations for Address Validation

---

#### PM - Sharon
- [x] #49251 Epic to support Notification settings/mobile flow changes

#### FE - Adam
- [x] #48263 Nametag - add Landmark-role (2 pts)
- [ ] #48753 Research Recommendations | Notifications Settings Spacing (2 pts) **(Liz to validate)**

#### Design - Liz
- [x] #48537 Research Recommendations | Address Validation (8 pts)

#### Design - Christina 
- [x] #47299 Account settings / screenreaders (4 pts)

#### BE - Tom
- [x] #48894 User Auth | Update BE docs (2 pts)

#### FE - Adam
- [x] #47781 Error Matrix (3 pts)

#### Design - Liz

- [x] #49007 Notification  Preferences | Next Steps (3 pts)

#### FE  -  John
- [ ] ~#48782 Link for DD214 on Military Page (2 pts)~ (moved to sprint 87 for tracking)
- [ ] ~#31410 Update alert for when a user is editing a section (2 pts)~ (moved to sprint 87 for tracking)
- [x] #47473 Remove Feature Flags for Notifications (3 pts)
- [x] #47477 Military/Alert updates (2 pts) - pending text tweaks (moved from sprint 86 for tracking)

#### FE - Adam
- [x] #48501 Update "Not in MPI" Error Alert (1 pts) 
- [x] #48011 Notification Settings/Bottom of page (bug) (1 pt)

#### BE - Tom
- [x] #49408 Direct Deposit Info Unmasked 2 pts) Unplanned work.
- [ ] BLOCKED - #43996 Datadog Access Request (2 pts)
- [ ] ~#48695 Notifications | Multiple Requests Issue (2 pts)~ (moving to Sprint 87)
- [x] #48022 BGS Caching | Ch33 Banking Requests (3 pts)
- [x] #48539 MyVA | Feature Flag Turning Off (2 pts)

#### PM - Sharon
- [ ] ~#43481 Fraud alerts (BGS) - on hold~
- [x] #49352 CC Guide | Updates to Account Security - Error Messaging

#### Design - Christina
- [x] #48306 Nametag - update designs to match use cases in staging/prod (4 pts)
- [x] #48990 Nametag-Full Name and Disability Rating | Content and IA Review (2 pts)

**Comment by Samara-Strauss** [comment]
@SKasimow once you're ready to groom this epic, can you please add #48862 for Tom for sprint 86? Thanks!

**Comment by SKasimow** [comment]
will do!

**Comment by Samara-Strauss** [comment]
@SKasimow sorry for the last minute change, but can we push #48862 back a sprint? I also posted in that ticket. I need some of those links to remain as-is for the next couple weeks.

**Comment by jcatergovy** [comment]
I am off on Veterans Day.
