### ISSUE TITLE
Design | Profile | Fiduciary Flag across Profile

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#48151]
## Background

Currently if an account has a fiduciary flag we block access for the Direct Deposit feature.
We should block the ability to view/update additional features since any changes to a flagged account will not actually be recorded/changed by VA Profile. 

We need to draft the UI and content for the additional features we want to block (or entire Profile):
- Personal info
- Contact info
- Military info 
- Notification settings
- Account security
- Connected apps

## Tasks
- [x] Create mocks showing where the alert will be placed and content (for each page if it varies)
- [x] Review with team and incorporate any agreed upon changes

## Acceptance Criteria
- [ ] Team agrees on design approach
- [ ] Content signs off on text

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)?
- How can this work be validated?
- What updates need to be made (e.g. product outline, use cases, contact center guide)

## Associated Tickets
- #47841

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by cgednalske** [comment]
@samara -- from the documentation + background I received from Liz, it's clear we need to block _editing_ information for all of Profile, but do you know if there is any use case where the fiduciary would still need read access?

**Comment by Samara-Strauss** [comment]
I think this is a good approach. You are totally right that it makes no sense to separately block all sections if people have this flag. I agree that only showing the account settings section with an alert makes sense.

I do wish we could show more helpful copy, though, just in case it's a mistake or it is the fiduciary logging in. I'm honestly not sure what we can or can not say, though, and I don't have anyone to go to for guidance. I think this is OK for now.

Related: @SKasimow I would be curious if we can get GA tracking on how many people see this state when they log in. I don't believe we have any tracking now on the direct deposit fiduciary alert.

**Comment by SKasimow** [comment]
@Samara-Strauss - Tom is checking. If he can't see this in logs, I can check with VA Profile to see if they can pull.

On a related note, once we put in the new messaging to block all section of Profile, I can create a ticket to track instances going forward.

**Comment by Samara-Strauss** [comment]
VA Profile has nothing to do with direct deposit. EVSS manages direct deposit for comp & pen. Idk if they will be able to tell us anything, but you can ask. But VA Profile does not send us this flag and won't bee able to tell us anything.

> I can create a ticket to track instances going forward.

Sounds good! This could be added to [our existing direct deposit for comp & pen dashboard.](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/naG_-UneTxy50WvvIH0GGQ/a50123418w177519031p176188361/)

**Comment by cgednalske** [comment]
Hi @Samara-Strauss and @SKasimow -- I've created mockups ([Desktop](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/a/PG4Pm2j) and [Mobile](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/a/g09lryk)) for this in the Account security Sketch files. I know they were initially DD-based, but seeing as the alert is in the Account security section it seems like it would be pretty confusing if they go in DD (but let me know if you think otherwise).

Danielle's only change was to update the phone number (with a note that TTY should be included in the aria label), so if this all looks ok I think we're set on this for now.

A remaining question here is how the nametag behaves in this situation. I believe it would not show at all but can confirm and update that in my ticket for next sprint when I'll take a look at all our mockups and the corresponding nametag states.

**Comment by Samara-Strauss** [comment]
> I've created mockups ([Desktop](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/a/PG4Pm2j) and [Mobile](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/a/g09lryk)) for this in the Account security Sketch files. I know they were initially DD-based, but seeing as the alert is in the Account security section it seems like it would be pretty confusing if they go in DD (but let me know if you think otherwise).

Agree with moving it out of direct deposit since it now covers the whole profile. When this goes live, let's update the documentation in Github accordingly, which will mean linking the DD docs over to the Account security page for this use case. @SKasimow can you create a ticket to update documentation once this update goes out?

**Comment by SKasimow** [comment]
@cgednalske - think we can close this ticket, correct?

Also, I opened a ticket for documentation once FE is underway (#49118)

**Comment by cgednalske** [comment]
@SKasimow Yep! This is all complete. 👍

**Comment by SKasimow** [comment]
@Samara-Strauss - unfortunately, Tom doesn't have visibility to metrics for the fiduciary flag. I'll open a ticket to add tracking and then create a widget for the comp&pen dashboard.

> Related: @SKasimow I would be curious if we can get GA tracking on how many people see this state when they log in. I don't believe we have any tracking now on the direct deposit fiduciary alert.

**Comment by Samara-Strauss** [comment]
Great, yes, thank you. Reminder that the analytics team is a skeleton crew right now, so it might be some time before they can get to this request.
