### ISSUE TITLE
Update 3 disability pages to align with VA style

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#48157]
## Issue Description

In preparation for translating pages in the disability benefits hub, we made edits in a Word doc to 3 pages to better align with more recent VA style updates and so that the content could be translated more easily.

We need to now make these updates in Drupal to the English pages. We should send to stakeholders for awareness before publishing.

The 3 pages to work on:

- [Eligibility for VA disability benefits](https://www.va.gov/disability/eligibility/)
- [How to file a VA disability claim](https://www.va.gov/disability/how-to-file-claim/)
- [The VA claim process after you file your claim](https://www.va.gov/disability/after-you-file-claim/)

Here's the Word doc to use:
[https://app.zenhub.com/files/133843125/66d21263-2457-41e6-bf63-554e609b935e/download](https://app.zenhub.com/files/133843125/66d21263-2457-41e6-bf63-554e609b935e/download)

## Tasks
- [x] Make changes to Drupal nodes (Aliyah)
- [x] Copyedit
- [x] Send to stakeholders for awareness (Randi/Danielle)
- [x] Publish

## Acceptance Criteria
- [ ] Updated disability pages are live

**Comment by aliyahblackmore** [comment]
Hi @RLHecht these are ready for whenever you have a moment!

As discussed due to the CMS migrator publishing, these pages were reverted to these versions:
09/22/2022 - 6:14pm (Published)
10/04/2022 - 9:17am  (Published) 
10/04/2022 - 9:17am (Published)

Preview links and notes (where needed): 

[Eligibility for VA disability benefits](https://www.va.gov/disability/eligibility/)
**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=871
**Notes:** On the current live page, there is a react widget for question "Can I file my claim online." This content has changed ("How do I file a claim?")  so we need to send this over to PW to have them update the text. If this can come out of the react widget, happy to remove and add the text in as a Q&A! 

[How to file a VA disability claim](https://www.va.gov/disability/how-to-file-claim/)
**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=905

[The VA claim process after you file your claim](https://www.va.gov/disability/after-you-file-claim/)
**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=870
**Notes**: There were no new changes on this page.

**Comment by RLHecht** [comment]
Per our check-in with Danielle, for now we are going to remove the link on the eligibility page under the list of conditions since it's currently being redirected to the wrong page. We also need to add "such as" the lead-in sentence for the second group of bullets. @aliyahblackmore could you go in and make these changes? Thanks!

**Comment by aliyahblackmore** [comment]
Thanks @RLHecht! I added in "such as" to the lead-in statement for the second group of bullets and removed the link. 

For translation purposes, I wonder if we should use "such as these" instead? Just a thought here!

**Comment by RLHecht** [comment]
Thanks @aliyahblackmore I changed it to "like these." I went back to check the word doc and we had already updated it there so it should now match and should have already been translated!

I've reviewed all three of these pages and will confirm with Danielle at our next call if we need to send to stakeholders for awareness before we publish.

**Comment by aliyahblackmore** [comment]
Hi Randi - these pages are ready for you again!

Eligibility for VA disability benefits
**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=871
Notes: I reverted to the most recent drafted version with your change to "such as" to "like these" to match what was in the word doc.  Currently the page has a link to a page that a Veteran should use to determine if they would complete VA Form 21-526EZ. Our new content has two links, neither are an action link.

How to file a VA disability claim 
**Preview link:**  http://preview-prod.vfs.va.gov/preview?nodeId=905
Notes: We previously reverted this page to the last published version in order to add the average number of days, ahead of sending this to SME. I reverted this back to the version with the new edits (the 10/19/22 at 4:15pm version) and added the average number of days for November (104.8). I believe that note in header "How do I file my claim" re: Spanish interpretation is only for the translated page - that is not included on this page.

The VA claim process after you file your claim 
**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=870
Notes: I changed the "Track the status of your claim" button to be a default link button (blue).

**Comment by RLHecht** [comment]
@megzehn We got the go ahead to publish these pages so that we can also publish our translated pages. Since we've reverted these several times for other work, it would be a good idea for you to do another copyedit of these before publishing. Thank you!

**Comment by megzehn** [comment]
Thank you @aliyahblackmore and @RLHecht! 

Confirming that these 3 pages have been copy edited and published!

**Comment by RLHecht** [comment]
Confirming these are live. Closing ticket.
