### ISSUE TITLE
GA4:  Data, Dashboard & Report - Updates

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#48154]
## Problem Statement 
As part of the GA4 migration we will need to update/create new BQ data tables based on the GA4 data model.  We will then need to update our Domo dashboards to reflect the new data and determine how to present UA and GA4 data in conjunction with each other.

## Hypothesis or Bet
If we update our data sources and dashboards with the new GA4 data we will motivate VFS teams to fully migrate their usage to GA4 and will be able to ultimately sunset the UA product.  

## We will know we're done when... ("Definition of Done")
- [x] GA4 property is connected to BQ
- [x] BQ data is translated/merged/mapped to current/or new data tables to support analytics
- [x] Domo dashboards are updated with the new GA4 data source
- [x] GA4 report set up support
- [x] Supporting documentation is completed and provided to VFS teams.

## Known Blockers/Dependencies 
GA4 events FE implementation and testing 

## Projected Launch Date
2023

**Comment by johnny-jesensky-adhoc** [comment]
Our final QC efforts have gotten all of our Domo dashboards to a stable place -- marking this epic as _**Done**_.

@Blivaditis, @ChristineYoungZA, @dorseypa1  -- Great work on this.

FYI @raywangoctova, @humancompanion-usds
