### ISSUE TITLE
Supplemental Claims | Feature Flag

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#48165]
## Background
We need to create a feature flag to hide the Supplemental Claim link / page from different environments while we do our staged rollout of the new feature

## Tasks
- [x] Add new feature_toggle to frontend
- [ ] Use new feature_toggle to conditionally hide the link to Supplemental Claims (part of #48808)
- [x] Use new feature_toggle to conditionally hide the Supplemental Claims intro page

**Comment by Mottie** [comment]
This work has been merged and is available for testing in staging.

**Comment by Mottie** [comment]
Oh, oops, not the WIP alert.

**Comment by Mottie** [comment]
_Now_ everything is merged in and available for testing in staging.
