### ISSUE TITLE
DOMO SF Mapping

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/va.gov-team#48162]
## Issue Description
Utilize the [VFS Product Mapping Doc](https://docs.google.com/spreadsheets/d/15j1WKu2bl134FD81sVifp1_CMCAaKr-5JN4C5IhfgyI/edit#gid=0) to map products and 411 sub-categories within DOMO

---
## Tasks
- [x] Add product mapping to the DOMO ETL
- [x] Post mapping document to confluence

## Acceptance Criteria
- [x] Has the mapping been completed and tested?
- [x] Has a confluence document been created that shows how products and categories are mapped?

**Comment by ianMcCullough-ob** [comment]
[Confluence doc has been created](https://vfs.atlassian.net/wiki/spaces/Contact/pages/2419359848/VA411+Sub-Category+and+VFS+Product+Mapping)
