### ISSUE TITLE
Supplemental Claims | Feature Flag

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#48166]
## Background
We need to create a feature flag to hide the Supplemental Claim link / page from different environments while we do our staged rollout of the new feature

## Tasks
- [ ] Add new feature_toggle to backend
- [ ] Add new feature_toggle to frontend
- [ ] Use new feature_toggle to conditionally hide the link to Supplemental Claims
- [ ] Use new feature_toggle to conditionally hide the Supplemental Claims intro page
