### ISSUE TITLE
Supplemental Claims | Select and add issues

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#48163]
## Value Statement
**_As a_** Veteran
**_I want to_** select and add issues to my supplemental claim 
**_So that_** I can submit new and relevant evidence for these issues. 

---
## Background Context
The code for this work is already in place, it was copied from HLR/NOD, but the content may need to be updated and unit tests and e2e tests may need to be copied from HLR/NOD

## Acceptance Criteria
- [x] User may multi-select displayed issues 
- [x] When a user adds a new issue, they may select from suggested issue names _or_ manually type in the name
- [x] When a user adds a new issue, they must include a name and decision date
- [x] User may edit new issues
- [x] User must apply at least one issue before selecting **Continue**
- [x] Unit tests complete (90% coverage)
- [x] E2E tests complete
- [x] Accessibility testing complete
- [x] Reviewed and approved by product and/or design

## Designs and Build Notes
- [DESIGN](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/p/C22CAF85-3AE8-4837-9C8F-0C7145740CC1/canvas#Version)
- [CONTENT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/sourceofcontenttruth.md)
- [Prototype](https://www.figma.com/proto/JveclTFbNNSmx4eiYwbZdZ/Supplemental-Claims?node-id=70%3A5676&scaling=scale-down&page-id=10%3A1697&starting-point-node-id=70%3A5676)

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [x] _Design approved_
- [x] _Content Approved_

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by thehastingsp** [comment]
design approved, content still in progress

**Comment by thehastingsp** [comment]
[Content approved](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/sourceofcontenttruth.md) @Mottie @rocio-desantiago @data-doge

**Comment by saderagsdale** [comment]
@Mottie Looks good to me. I checked off the last task for product to review.
