### ISSUE TITLE
Update MHV Inherited proofing doc to include api errors

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#48167]
## Issue Description
Please update the [MHV Inherited Proofing documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Inherited%20Proofing/MHV%20Inherited%20Proofing/inherited-proofing-interface.md) to include all possible error responses.

Once completed inform the logingov team of the update in [this](https://dsva.slack.com/archives/C02SYNUGRLN/p1665675128283129) slack thread

### Auth
- `IdentityDocumentMissingError`: thrown when correlation ID or or MPI-sourced "Identity Documents" are not found
- `Common::Client::Errors::ClientError`: thrown for MPI requests that fail
  - `correlation_id_api_request`
  - `verification_info_api_request`
- `MHVIdentityData` validations: user_uuid, code, data

### User Attributes
- JWT validations (from `authenticate_access_token`)
  - `AccessTokenSignatureMismatchError`
  - `AccessTokenExpiredError`
  - `AccessTokenMalformedJWTError`
  - `AccessTokenMissingRequiredAttributesError`
- `UserAttributesFetcher` (from Redis cache)
  - `MHVIdentityDataNotFoundError`
  - `UserNotFoundError`
  - `UserMissingAttributesError`

### Callback
- `PreviouslyVerifiedError`

## Tasks
- [x] update documentation with `auth` errors
- [x] update documentation with `user attributes` errors
- [x] update documentation with `callback` errors

**Comment by bramleyjl** [comment]
The [documentation has been updated](https://github.com/department-of-veterans-affairs/va.gov-team/commit/2edc438b2df57a8630ebdcf1e6ab0cf6808f4df3) has been updated to detail existing inherited_proofing errors. A followup ticket #50740 has been created to handle improvements in inherited_proofing error handling.
