### ISSUE TITLE
Investigate ClamAV Virus Scan Gem

### ISSUE THREAD

**Issue by rjohnson2011** [department-of-veterans-affairs/va.gov-team#48186]
## Description
During an [investigation of the longest-running Sidekiq jobs](https://app.zenhub.com/workspaces/platform-tech-team-3-6335ab9b1901b99243ce7601/issues/department-of-veterans-affairs/va.gov-team/47991), the virus scan portion of the DocumentUpload process was discovered to use a [deprecated gem](https://github.com/jschroeder9000/clam_scan) `clam_scan`. The [actively-supported alternative ClamAV interface](https://github.com/kobaltz/clamby) is `clamby`.

Discover the workload required to sunset `clam_scan` in favor of `clamby` (i.e. how many clam_scan dependencies exist throughout the app and would need modification to clamby? what does the refactor process entail?)

## Tasks
- [x] Review the README for the installation process of `clamby`.
- [x] Note the number of `clam_scan` dependent methods that would require refactoring, and complexity of doing so.

## Acceptance Criteria
- [x] Complete the above tasks and provide a time estimate to complete the gem swap.

**Comment by rjohnson2011** [comment]
Upon reviewing the documentation for Clamby, and the implementation of ClamScan, there are a number of changes that would need to be made to the application to swap these gems:

- Most concerning is a ClamScan configuration file which sets the `client_location` to `Settings.binaries.clamdscan`. Within the Clamby documentation, there is not an equivalent method, so a suitable replacement would have to be found which could require an even greater refactor.
- There are 5 spec files that utilize ClamScan, with a total of 19 different specs which would all need to be rewritten.
- A docker-compose file that using ClamScan in binaries settings `docker-compose.yml` would likewise need to be modified.

From the perspective of API latency, both ClamScan and Clamby are ruby wrappers that utilize an underlying ClamAV daemon. While [ClamScan](https://github.com/jschroeder9000/clam_scan) was last updated in 2015 and is at risk for potentially breaking changes in upcoming Ruby/Rails updates, it does not appear that the virus scan speed would be notably improved via changing the gem to Clamby. 

Therefore, I would make this gem update a recommendation to a backend team rather than utilize it for an API latency effort.
