### ISSUE TITLE
[FE] Payment Info V2: Bug - Number of Copays Not Displayed Correctly

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#48195]
## Background
Currently we are not displaying the correct number of copays for users. This issue was found in Staging with user 36 who should have 2 copays but is displaying in My VA as having 3 copays. We reached out to the benefits team on Slack and they informed us in this [thread](https://dsva.slack.com/archives/CPE4AJ6Q0/p1665685144323159) that we should be using the number of facilities that the user has outstanding copays with to pull in the number of copays.

This bug was identified in #47764

## Tasks
- [x] Update the copay card to show the number of facilities they owe copays too
- [x] Validate the number of copays is now correct with user 36 - PM

## Acceptance Criteria
- [x] Number of copays is displayed correctly

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_
- _How can this work be validated?_ log in with user 36 and user 80 and validate that the number of copays matches what is shown in the debt portal

**Comment by tmitchellgcio** [comment]
Just merged give it 30 min to deploy

**Comment by ericasauv09** [comment]
validated with user 36:
![Screen Shot 2022-10-17 at 14.06.48.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/09414c28-6fb8-4367-a304-eaf6f331c891)

and user 80:
![Screen Shot 2022-10-17 at 14.08.23.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/8c6713d4-e30d-4371-a8e2-748a3a3159de)
