### ISSUE TITLE
Facility Locator Audit

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#482]
## High Level User Story
As an accessibility tester, I want to review and close out findings from the recent Facility Locator audit.

## Goals
I would like to see two outcomes from this epic:

1. The facility locator be compliant with respect to Section 508
2. The auditor to re-test and close issues in their finding

## Objectives
_Which VSP Objectives does this body of work push forward?_ (`Support`)

## Definition of Done
- [x] **Labeled with Team** (`triage`)
- [x] **Labeled with Practice Area** (`frontend`, `508/Accessibility`)
- [x] **Labeled with `Epic`**

**Comment by Karak888** [comment]
We are moving these to our Facility Locator General Epic, do we need to keep your audit ticket open on our end still?

**Comment by 1Copenut** [comment]
@Karak888 No, the audit can be closed with issues being moved to your General epic. Thank you!

**Comment by 1Copenut** [comment]
Moving to close as the audit has been completed and new work is underway.
