### ISSUE TITLE
FE | Profile | Create Feature Flag for new BVA Notification

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#48202]
## Background

We need to create a new feature flag for the new BVA notification which will send people text message updates when there is a status change with their appeal.

## Tasks
- [x] Create a feature flag for the new BVA notification using "id 6" to reference
- [x] Conditionally display the notification based on the feature toggle
- [x] write tests for feature toggle based functionality

## Acceptance Criteria
- [x] End-to-end tests showing 0 violations
- [x] Notify Product Manager that the change is ready to be validated on Staging

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)? PM
- How can this work be validated?
- What updates need to be made (e.g. product outline, use cases, contact center guide)

## Associated Tickets
- #47441

**Comment by adamwhitlock1** [comment]
@SKasimow this is live in staging, but the api doesn't have this notification data, so not exactly sure how we would validate this.

I did write end to end tests specifically for this feature toggle and have also tested it locally for what its worth

**Comment by adamwhitlock1** [comment]
I'm going to close this issue and we just need to track once VA Profile starts testing this notification setting in lowers we can then validate this further.
