### ISSUE TITLE
[DDL FE] Notification Letter performance tracking and monitoring

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#48211]
Using standard tracking and monitoring tools like Sentry, Datadog, Grafana, and/or PagerDuty, enable the team to identify fail states and to know whether we are reaching our performance benchmarks or not. 

### Front end (estimated at a 3-4)

- [ ] add code for failure event pushed to Google Analytics for API call to pull list of letters that includes the failure reason and status code 
- [ ] add code for failure event pushed to sentry for API call to pull list of letters that includes the failure reason and status code
- [ ] add code for success event pushed to Google Analytics for API call to pull a list of letters

# Acceptance Criteria 

Monitoring:

- [ ] Error logs allow us to conduct root cause analysis to determine the reason behind critical fail states
- [ ] Team receives notifications for critical fail states, such as application failing to load for end users
- [ ] Able to distinguish performance between the two distinct API calls being made

Tracking

- [ ] Create event(s) that allow us to track successful API calls that generate the list of notification letters
- [ ] Create event(s) that allow us to track successful API calls that denote when a user actually downloads their notification letter
- [ ] Create an event that allows us to count critical application failures.
- [ ] Create an event that allows us to count downloads by doc ID

**Comment by sortizsh** [comment]
companion to BE ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/48017
