### ISSUE TITLE
BE | Profile | Military Service History | Discovery for Clarifying Display of Multiple Military History Dates

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#48225]
## Background

In an effort to understand what additional military info for Veterans can be made available to us through VA Profile, Tom has put together a document depicting all the fields here: [Military History Fields doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/military_info/vaprofile_response_fields.md)

As a next step, we would like to see if we can supplement the current data displayed when a Veteran has multiple service records with nothing to differentiate them except for the dates. This can be confusing as we heard and saw in the example referenced below:

https://dsva.slack.com/archives/D03BLJF9N92/p1665086463074049

## Tasks

- [x] Reach out to VA Profile team and inquire about which fields would help clarify history records.
- [x] Review Military Personnel Domain Data Dictionary on the VA Max Confluence site

## Acceptance Criteria

- [x] Create additional tickets (if necessary)

## Associated Tickets
- #47929

**Comment by SKasimow** [comment]
Hi @tpharrison - I started this ticket; can you take a look and see what else could be added or clarified?

**Comment by tpharrison** [comment]
Spoke with Dan Ramunda from VA Profile.

He suggested I look at the Military Personnel Domain Data Dictionary on the VA Max Confluence site.

https://community.max.gov/display/VAExternal/VADIR+Master+Schema+Data+Dictionary

I have requested access and waiting to hear back.

**Comment by tpharrison** [comment]
| Branch | Organization                                               | Service Type       | Beg Date   | End Date   | Character of Discharge                       | Reason for Separation                        | Termination Reason                                 |
|--------|------------------------------------------------------------|--------------------|------------|------------|----------------------------------------------|----------------------------------------------|----------------------------------------------------|
| Army   | Army MILPERCEN DEERS Population: Eligible Army Active Duty | Active duty member | 1991-04-07 | 2000-01-03 | Under honorable conditions (general)         | UNKNOWN                                      | Separation from personnel category or organization |
| Navy   | Navy Reserve DEERS Population: Eligible Navy Reserve       | Reserve member     | 1980-04-07 | 1989-01-23 | Unknown                                      | UNKNOWN                                      | Separation from personnel category or organization |
| Navy   | Navy Reserve DEERS Population: Eligible Navy Reserve       | Reserve member     | 2001-04-07 |            | Value is not applicable for this record type | Value is not applicable for this record type | Not applicable                                     |

**Comment by tpharrison** [comment]
@SKasimow [This document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/military_info/sample_data.md) provides some example data for us to review.

**Comment by SKasimow** [comment]
@tpharrison ok, can we cover when we meet on Thurs?

**Comment by SKasimow** [comment]
Also, should we close this?
