### ISSUE TITLE
[FE] Minor Content Changes

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#48237]
## Changes
- Change h1 to: You're checked in. And we received your travel claim
    - [Wireframe](https://share.goabstract.com/5c39328b-c6c1-452f-93f8-390b3698dd82?mode=design&sha=d1bbc36f2c43a6aa4bca0685e667bf07b092eed5)
- In the yellow box, add the word "travel" immediately before the word "reimbursement." So, it should read, "... travel reimbursement claim for you now."
    - [Wireframe](https://share.goabstract.com/4ab2a1a6-d54a-4e52-81b9-f218ddba2311?mode=design&sha=d1bbc36f2c43a6aa4bca0685e667bf07b092eed5)

## Tasks
- [x] [FE] **make changes**
- [x] Create or update unit tests
- [x] Create or update e2e tests
- [x] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [x] Passes Accessibility checks using axe
- [x] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [x] not necessary
  - [ ] scheduled

## Code Review Steps
- [x] Read ticket details and verify that ACs are met
- [x] Review code in PR
- [x] Run branch locally
- [x] Check that new and updated translations use new keys
- [x] Check for hardcoded strings

**Comment by brianseek** [comment]
@loripusey / @zach-park / @benbrasso-agile6 These updates are now in on stage. See screenshots[https://app.zenhub.com/files/133843125/05ee9f86-cf05-43bd-b57c-15ffb08d8340/download](https://app.zenhub.com/files/133843125/05ee9f86-cf05-43bd-b57c-15ffb08d8340/download).
