### ISSUE TITLE
Spanish translation of updated claim exams Q&A on COVID FAQs page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#48230]
## Issue Description
We reworked a Q&A about claim exams on the [coronavirus FAQs](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/#claims-and-applications) that we need to also update on the Spanish version of the page.

Doc sent to translators: [https://app.zenhub.com/files/133843125/0e5af6a1-206e-4ac1-84f3-947950361902/download](https://app.zenhub.com/files/133843125/0e5af6a1-206e-4ac1-84f3-947950361902/download)

## Tasks
- [x] Send content to translators (Randi)
- [x] Update Spanish page (Aliyah)
- [x] Copyedit
- [x] Publish

## Acceptance Criteria
- [x] Newest translated content is on Spanish page

**Comment by RLHecht** [comment]
@aliyahblackmore Here's the content back from the translators: 

[https://app.zenhub.com/files/133843125/e4844ea9-6b7e-4da7-a110-f89806ec7b70/download](https://app.zenhub.com/files/133843125/e4844ea9-6b7e-4da7-a110-f89806ec7b70/download)

**Comment by megzehn** [comment]
Thank you, @aliyahblackmore! Confirming that this page is published. 

CC @RLHecht

**Comment by RLHecht** [comment]
These changes are live. Closing ticket
