### ISSUE TITLE
Tagalog translation of updated claim exams Q&A on COVID FAQs page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#48231]
## Issue Description
We reworked a Q&A about claim exams on the [coronavirus FAQs](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/#claims-and-applications) page. We need to update this on the Tagalog version of the page as well. 

Doc sent to translators: [https://app.zenhub.com/files/133843125/20e03fb5-d12a-4521-a488-4af1a99c5cea/download](https://app.zenhub.com/files/133843125/20e03fb5-d12a-4521-a488-4af1a99c5cea/download)

## Tasks
- [x] Send text to translators (Randi)
- [x] Update Tagalog page (Aliyah)
- [x] Copyedit 
- [x] Publish

## Acceptance Criteria
- [x] Tagalog page is live with newest content

**Comment by RLHecht** [comment]
@aliyahblackmore Here's the content back from the translators. [https://app.zenhub.com/files/133843125/a3869bbc-0007-47e5-9c0e-de946efae553/download](https://app.zenhub.com/files/133843125/a3869bbc-0007-47e5-9c0e-de946efae553/download)

**Comment by RLHecht** [comment]
I reviewed and published this. Moving to validate.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
