### ISSUE TITLE
[FE] Payment info V2: Update error messages to red alert styling

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#48236]
## Background
While implementing the audit UX updates to the Claims and appeals section on My VA, Taylor noticed a discrepancy in how alerts were being handled in that section vs the new Outstanding debts and Benefit payments sections. 

Yellow alert styling that needs to be updated:
![Screen Shot 2022-10-14 at 10 58 22 AM](https://user-images.githubusercontent.com/45603961/195878383-375dda67-ac96-45b4-b577-b0d69b5e949c.png)

**We need to update the Outstanding debts and Benefit payments section to be consistent with what was decided in the audit.** 

## Tasks
- [x] Update styling of error messages in the Outstanding debts section to be the red alert styling
- [x] Update styling of error messages in the Benefit payments section to be the red alert styling

## Acceptance Criteria
- [x] Error messages in the Outstanding debts and Benefit payments sections matches error styling in Claims and appeals (as determined in audit)

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ provide screenshot of error in PR for team member to review, or spoof error in staging 

## Resources
**Red alert styling**
![Screen Shot 2022-10-14 at 10 57 35 AM](https://user-images.githubusercontent.com/45603961/195878218-bd1b7943-90bd-4ae3-b7f7-000c8470b5a4.png)

**Comment by tmitchellgcio** [comment]
Will need a title with the red style @aagosto90 I believe

**Comment by aagosto90** [comment]
> Will need a title with the red style @aagosto90 I believe

@tmitchellgcio @ajakabcin @ericasauv09 
Updated the mockups and FE documentation to have headers since we know platform team will suggest this.
[FE documentation for outstanding debts errors](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/outstanding-debts-FE-documentation.md#error-states)
[FE documentation for benefit payments error](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/benefit-payments-FE-documentation.md#error-states)

**Comment by tmitchellgcio** [comment]
This is on staging and ready for deployment

**Comment by ericasauv09** [comment]
validated in Staging with user 21: ![Screen Shot 2022-10-17 at 13.01.34.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/6682d74d-1e6d-410a-8568-b4a78aac4d8d)

I didn't find any users with errors under the payment section, not sure if we can/want to validate that as well or if we are ok with the validation above? @ajakabcin @tmitchellgcio
