### ISSUE TITLE
Design | Profile | Nametag - Full Name and Disability Rating | Discovery

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#48264]
## Background

As part of ticket #47266, we determined that the Nametag info was important enough that including full name and disability rating in the main sections of Profile would be beneficial for screen reader users or anyone else who might miss this info in the name tag.

## Tasks
- [x] Consider placement options for Nametag info 
- [x] Review viability and ease of implementation with FE 
- [x] Create 2 - 3 mock-ups for review
- [ ] Review options with team (and update mocks if needed)

## Acceptance Criteria
- [ ] Align on design
- [ ] Notify PM when ready for FE implementation

## Associated Tickets
- #47266

**Comment by SKasimow** [comment]
Hi @cgednalske - can you review and point?

**Comment by cgednalske** [comment]
Hi @SKasimow! This looks good to me 👍 I just changed to title to include Full Name and Disability Rating so it's easier to find and know what it's for than general Nametag. I added a 4 because I think this will need to be decently thorough, but I'm not super sure about that estimate. 🤔

**Comment by cgednalske** [comment]
Hi @Samara-Strauss and @SKasimow -- Here's a [mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1666278971896/e40f7917f9908c9190d6c01d7edacd07e4fce24c?sender=u28f508d646c449cc1afe4873) of the design explorations for how disability rating and full name can be incorporated into the main part of Profile. I've discussed considerations and feasibility with Liz and Adam and would definitely recommend adding these as fields in personal info section, as there doesn't seem to be a strong reason we'd need to show additional info for disability rating in it's own section/page. And if we did want to show more info, we could always consider including an FAQ dropdown in the field. 

I'm very interested to hear your thoughts and am also happy to meet and go over this, but I'm having trouble finding a good time that works for all three of us in the next few days. Looks like tomorrow right before grooming at 12:30pm EST / 9:30am PST could work, or Thursday at 11:30am EST / 8:30am PST. Let me know if it'd be helpful to meet during one of these times!

One remaining question: If this approach sounds good, I'll need to solidify how the disability rating field would change (if at all) if **a)** we cannot show disability rating or **b)** someone does not have a disability rating. Currently, if someone does NOT have a disability rating, does it still show as 0% disability rating in the nametag? Or does the rating disappear?

**Comment by Samara-Strauss** [comment]
Thanks for this! I think we are going in the right direction. Some thoughts:

- I'd review this with IA and content as soon as possible. IA can help us confirm this is the right place for this piece of information, and content can help us with the copy (duh). The My VA half of the team recently got some feedback about removing "service connected" from the disability rating, so we'd want to solidify how we should display that and link off to the ratings tool.
- The page does start to feel pretty long once we add pronouns and sexual orientation, but I don't think we should worry much about that now since those fields aren't live. Thanks for mocking this up, though!
- What does someone see in the profile if they do not have a disability rating?

> One remaining question: If this approach sounds good, I'll need to solidify how the disability rating field would change (if at all) if a) we cannot show disability rating or b) someone does not have a disability rating. Currently, if someone does NOT have a disability rating, does it still show as 0% disability rating in the nametag? Or does the rating disappear?

The name tag is a shared element with My VA, so please don't remove the disability rating for now.

**Comment by Samara-Strauss** [comment]
All of this sounds good to me! Thanks, Christina!

**Comment by SKasimow** [comment]
Looks good...just one question on the use case for people who were never in the military and don't have a disability rating.
Is the thought to leave the disability rating field in place and indicate "no rating" or remove the field entirely as we do in the Nametag? 

>What does someone see in the profile if they do not have a disability rating?

>I'll work on this next based on your answer below. 👍 So that we're not changing up the page or removing fields in a way users wouldn't expect, I'd imagine we'll want to keep the field as is and change the text to denote a blank field and convey "you don't have a disability rating" + a link to learn more.

**Comment by cgednalske** [comment]
@SKasimow the thought is to leave the disability rating field in place and indicate "no rating." Still finishing up this part of the exploration, but we probably don't want to remove it if there's a chance it might be needed - also because it'd be hard to differentiate between who doesn't have a rating and might need one and who doesn't have a rating and will never need one. So likely our best approach is to always have the field and show "no rating" in some way, along with more info in case it's a mistake or they haven't started the process of getting one yet.

**Comment by Samara-Strauss** [comment]
> So likely our best approach is to always have the field and show "no rating" in some way, along with more info in case it's a mistake or they haven't started the process of getting one yet.

Agreed. It's impossible to differentiate between someone who is not a veteran and logs in (like us) who will never have a rating, and veterans who have not yet applied for disability compensation that may do so at some point.

**Comment by SKasimow** [comment]
Thanks for clarifying!

**Comment by cgednalske** [comment]
Hi @Samara-Strauss @SKasimow -- I mentioned this briefly in our Thursday standup, but I spoke with Danielle during her office hours about disability rating and PACT Act info, and I now have some explorations we can talk through based on what came out of the discussion. (**Note**: Erica created a [new ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48990#event-7705367718) for this that will go into next sprint since the discovery and design is an add on to what this ticket initially included)

Danielle said what we have for the initial content (no additional info) looks good for for both, but brought up the possibility of adding some PACT Act info to the disability rating field, as it's something that can increase disability rating for some Veterans and provide one one for the first time for others. It sounds like she is looking at any ways we can create awareness with a low lift, and also provided some preliminary language to try out. 

What do we think about possibly included something related to this? I've put together a [Mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1666278971896/e40f7917f9908c9190d6c01d7edacd07e4fce24c?sender=u28f508d646c449cc1afe4873) with explorations of different ways we might be able to include some or all of this info, but I also feel it'd be helpful to meet and have a conversation about the possibilities.

**Comment by Samara-Strauss** [comment]
I am so torn on this. On one hand, PACT Act is super important, and it's a priority both to Veterans and VA. On the other, this adds a lot of content to the field, and I think it'll make the page really long on mobile. We already have more content than I'd like in our fields, especially for mobile, so I'm not sure how to resolve that. I definitely want to balance presentation with the fact that PACT Act is something we should be elevating across the site.

**Comment by cgednalske** [comment]
@Samara-Strauss Agreed. It's a tricky one. I can do more exploration to see if there's a way to make this even more minimal that might work better with the page. It doesn't seem like any of the design system components really apply in a way that would help shorten things, but between that and the content itself, there definitely might be something I haven't considered yet.

**Comment by SKasimow** [comment]
@cgednalske - think we can close this one as well since you're continuing with #48890 but wanted to check :)

**Comment by cgednalske** [comment]
@SKasimow I agree! I think this content (+ IA) exploration can continue in the other, more specialized ticket 👍
