### ISSUE TITLE
PM | Profile | BAI | Documentation

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#48272]
## Background

With the launch of the bad address indicator the product outline for Contact info and the BAI project outline needs to be reviewed and updated.

## Tasks

- [x] Review Contact info product outline
- [x] Review the BAI info project outline
- [x] Update as needed

## Acceptance criteria

- [x] Bad address indicator outline is up to date.
