### ISSUE TITLE
FE | Profile | BAI | Documentation

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#48273]
## Background

Update documentation for the Contact info product section in GitHub and BAI project outline and add/update relevant FE documentation.

## Tasks
- [x] Add analytics documentation on what events we are firing and where in the code they come from.
- [x] Document Api calls and how they are set up in the FE code
- [x] Map what error codes that might surface for a particular feature and the alert/messaging it maps to

## Acceptance Criteria
- [x] Analytics documentation on what events we are firing and where in the code they come from added
- [x] Document Api calls and how they are set up in the FE code added
- [x] Map what error codes that might surface for a particular feature and the alert/messaging it maps to completed

**Comment by adamwhitlock1** [comment]
I have updated the FE docs to include more information regarding BAI. Sections have been added to the Contact Information and Personal Information docs since both pages show BAI related UI.

https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/contact_information/frontend_documentation.md#bad-address-indicator

https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/personal_information/frontend_documentation.md#bad-address-indicator

**Comment by adamwhitlock1** [comment]
@SKasimow fyi
