### ISSUE TITLE
[FSR] - bug - Installment contract values & calculations

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#48277]
## Issue Description
Investigate and fix required inconsistencies with installment contracts on current form. 
> We had multiple submissions that were missing the `originalAmount` key from their installment contract. Some that were missing `creditorName` . And one submission where the only thing that was filled out was `purpose`

We need to either make these fields required or handle when they are not complete/incorrectly filled out. 

---
## Tasks
- [ ] Investigate if these installment contracts should be required
- [ ] Update requirements and include additional error handling so good data is being received. 

## Acceptance Criteria
- [ ] Installment contracts no longer receive blank or NaN values where appropriate 
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
