### ISSUE TITLE
Design | Profile | BAI | Documentation

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#48271]
## Background

With the launch of the Bad Address Indicator we need to update our design documentation for the Contact info product outline and the BAI project outline.  

## Tasks
- [x] Update use cases for this feature
- [x] Update user flows
- [x] Update screen mocks and text

## Acceptance Criteria
- [x] Post to appropriate sections of GitHub and sketch
- [x] Check that links from product outline are up to date

**Comment by SKasimow** [comment]
Hi @cgednalske - can you review/edit if needed and then point this?

**Comment by cgednalske** [comment]
@SKasimow I've updated the bad address indicator [use case](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/use-cases/address-marked-as-bad.md) and [user flow](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/7yPo0rZ) throughout our documentation. I also double-checked the images and text in the contact center guide as well, and they're already up to date from our previous update. 👍

**Comment by SKasimow** [comment]
@cgednalske - yay! Thank you. I'll close this out :)
