### ISSUE TITLE
Combined multiple last names for valid FSR filename

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#48282]
## Issue Description
Bug where Veteran has multiple space separated last names produced an invalid filename for SharePoint.

---
## Tasks
- [ ] Combine the multiple last names with an underscore

## Acceptance Criteria
- [ ] The API produces a valid SharePoint filename for this edge case
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
