### ISSUE TITLE
Design | Profile | Nametag - update designs to match use cases in staging/prod

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#48306]
## Background

The nametag component may not be accurately reflected in certain use cases throughout Profile. We ran across this while working on the [Account security MPI alert](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47350).  

We should make sure the nametag is updated to correct version ([see Angela Agosto's nametag audit](https://app.mural.co/t/vsa8243/m/vsa8243/1648129585496/d22080eb307aac8bda5ba1153e013a386b7f1396?sender=u28f508d646c449cc1afe4873)) to match different use cases throughout Profile.

_Note: this should all be correct in staging/prod, but it appears the designs may not accurate reflect nametag behavior._

## Tasks
- [x] Review designs to check nametag use across Profile
- [ ] Update to match LOA3 use cases from Angela's audit

## Acceptance Criteria
- [x] Designs have been reviewed and updated to match nametag use cases across Profile

## Associated Tickets
- #47350

**Comment by cgednalske** [comment]
Hi @SKasimow -- I made this ticket to check/update the nametag in the designs to make sure our mockups are accurately showing what actually happens to the name tag in different LOA1 and LOA3 use cases (discussed in our ticket for the [Account security alert work](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47350#issuecomment-1280891130)).

Not sure how urgent this is to do (don't believe it's urgent), but wanted to make sure it's all documented. If needed, I could add this to my next sprint or whenever there's time, but let me know if/how this fits into the schedule.

**Comment by SKasimow** [comment]
Hi @cgednalske - adding to Sprint 86; can you point it?

**Comment by cgednalske** [comment]
@SKasimow 👍 starting with a 4 and will see how it's looking when I start. This applies to ALL of our Profile files so could be a longer one if I run into odd use cases. If it turns out we've figured most of our use cases in the recent Account security alert work, could also be shorter 🙃

**Comment by cgednalske** [comment]
Hi @SKasimow - for this one, I believe our plan is to have a new ticket for next sprint to create a Sketch file for nametag states and add documentation to Github as well. Do we already have a ticket for this? And if this all sounds correct, we should be able to close this one 😃  The LOA1 screens and relevant LOA3 screens have all had the nametag updated.

**Comment by SKasimow** [comment]
Hi @cgednalske - that's correct. I have a note to create a ticket for this but will see if @ericasauv09 can get to it today :)

**Comment by SKasimow** [comment]
Hi @cgednalske - we opened #49616 for the balance of this work so you are free to close this out
