### ISSUE TITLE
Communicate about new Platform website orientation

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#48318]
### Tasks

- [x] Announce at Team of Teams meeting about new orientation for new team members but available for anyone interested.

- [x] Vicky will let other PMs know at an upcoming Platform Huddle sync meeting

- [x] Vicky will let team know if there are any existing team members interested to schedule their orientation
