### ISSUE TITLE
Draft and post Slack announcements for archiving #platform-confluence

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#48321]
### Tasks

- [x] Create the first pre-change Slack announcement
- [x] Create the second pre-change Slack announcement
- [x] Create a post-chance Slack announcement
- [x] Post Jan 25 announcements
- [x] Post Jan 31 announcements
- [x] Post Feb 1 announcements

### Task Info:
Create a Slack announcement about the following things:

- The #platform-confluence Slack channel will be archived on xx/xx/xxxx
- We will transition the Monday-Thursday Platform website deployment announcements to #platform-content Slack channel.
- If you follow this channel, we recommend that you join the #platform-content channel.
- If you need support from the Platform Content team, reach out to us via #vfs-platform-support or #platform-content

- [x] Coordinate when to post each announcement based on when we start making deployment announcements on #platform-team.

Slack message should go on:
- #platform-confluence
- #vfs-change-announcements

### Slack announcement format/template:
- Use this past Slack announcement as an example:: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2413264910/Communication+Plan+for+Slack+Support+Change

### Timeline:

- Post pre-change announcement (#platform-confluence & #vfs-change-announcements) on Wednesday, Jan 25
- Post pre-change announcement (#platform-confluence & #vfs-change-announcements) on Tuesday, Jan 31
- Archive #platform-confluence on Wednesday, February 1
- Post post-change announcement (#platform-content & #vfs-change-announcements) on Wednesday, February 1

### Lauren's drafts:

- https://vfs.atlassian.net/wiki/spaces/CIT/pages/2492661777/Slack+Archival+Slack+Announcements

**Comment by laucon** [comment]
@vbellissimo hey! You wrote "Post post-change announcement (#platform-confluence & #vfs-change-announcements) on Wednesday, February 1" How would it be physically possible to do the first of those 2 steps? Post a message on a channel that has already been archived? Shouldn't we post this last message on #platform-content & #vfs-change-announcements? Also, should we still post all the previous messages on #platform-content & #vfs-change-announcements? That I think we should do.

**Comment by vbellissimo** [comment]
@laucon Yes, the final announcement (post-change) for February 1, should go on #vfs-change-announcements & #platform-content. I will edit the instructions above.

As for sharing on other relevant channels, there's a way to basically link to the original post. This is how you could do that. Here's an example of how I shared one of Samara's posts without copying and pasting her original content: https://dsva.slack.com/archives/CJRQ85PQB/p1673284628039539

**Comment by laucon** [comment]
@vbellissimo Thanks! And just to clarify, on Jan 25 and also Jan 31, we should post to #platform-confluence, NOT #platform-content, correct?

**Comment by vbellissimo** [comment]
@laucon correct!

**Comment by laucon** [comment]
@vbellissimo awesome! thanks!
