### ISSUE TITLE
[BE] Add configuration for BTSSS endpoints and secrets for staging and production

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#48328]
## User Story
As a Veteran who is using eCheck-in to check-in for an appointment, I want to have the option to submit a claim for travel reimbursement when I check-in so that I don't have to later fill out a form or visit the Travel Office.

## Tasks
- [ ] [BE] Work with @mdewey to get config settings (incl secrets) from BTSSS team
- [ ] [BE] Add configuration settings to devops and other repos
- [ ] [BE] Add keys/values to AWS

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by randomsync** [comment]
Currently in staging, I'm getting this error:
`{"data":{"error":true,"code":"CLM_010_CLAIM_SUBMISSION_ERROR","message":"Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription."},"status":401}`
