### ISSUE TITLE
Minor updates to age eligibility for COVID boosters

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#48323]
## Issue Description
We made changes to the main COVID page and the boosters page around age eligibility. We need to get the content approved and published.

## Tasks
- [x] Updates to main page and booster page (Danielle)
- [x] Review (Laura)
- [x] Send to stakeholders (Randi)
- [x] Copyedit and publish (Randi)

## Acceptance Criteria
- [x] New updates are live on production

**Comment by RLHecht** [comment]
These changes are live. Closing this ticket and will send out the translation work in a follow-up ticket.
