### ISSUE TITLE
Update link and remove content on National Call to Service page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#48336]
## Issue Description
A product team working on removing the online 22-1990n online form opened an intake request with our team to do some work on the [National Call to Service program](https://www.va.gov/education/other-va-education-benefits/national-call-to-service-program/) page.

Under the H2 How do I get these benefits? We need to remove the "Apply now" link and replace it with a link to the 22-1990n find a form using our standard "Get VA Form XX-XXXX to download" text. 

We also need to remove the entire Get more information section so there's no longer a broken link. 

Original intake request for reference: #48280

## Tasks
- [ ] Update text link (Katherine)
- [ ] Remove Get more information section (Katherine)
- [ ] Review (Laura)
- [ ] Copyedit (Randi) 
- [ ] Publish (Randi)

## Acceptance Criteria
- [ ] Updates are live on production

**Comment by katherine-fung** [comment]
Hi @laurwill @RLHecht, 

Here's the updated page: http://preview-prod.vfs.va.gov/preview?nodeId=946 

I updated the link text. For the "more information" section, I tried to find another page on va.gov with information about the program. I could only find another PDF which repeated the information already on the page (https://www.benefits.va.gov/BENEFITS/factsheets/education/NCTS.pdf) so I opted to remove the section.

**Comment by RLHecht** [comment]
@katherine-fung The other part of this ticket, which I mentioned in standup is removing the online form section on the find forms landing page. Here's the page to work from: https://www.va.gov/find-forms/about-form-22-1990n/ Thanks!

**Comment by laurwill** [comment]
Hey @katherine-fung , your changes to the first page look great, but it looks like we have some previous draft changes on that page related to education rates. So to do this work, you'll need to revert, remake these changes, then put the rates draft stuff back in after we publish.

When you do that, could you also make the line break before the link a full return? Thanks!

**Comment by katherine-fung** [comment]
Hi @laurwill @RLHecht, 

For the National Call to Service program page, I reverted to the last published page and made the changes there. 

When the changes are published, I'll revert to the revision from 10/18/2022 - 2:11 pm. 

I removed the online tool link and information from the form page. 

Program page: http://preview-prod.vfs.va.gov/preview?nodeId=946
Form page: http://preview-prod.vfs.va.gov/preview?nodeId=6122

**Comment by laurwill** [comment]
Thanks Katherine! I just changed the "Get form to download" link to use the node instead of the url. 

@megzehn , these are ready to copyedit/publish.

**Comment by katherine-fung** [comment]
Hi @laurwill! I updated this page per today's standup: 

http://preview-prod.vfs.va.gov/preview?nodeId=946

**Comment by laurwill** [comment]
Thanks @katherine-fung ! I tweaked the mailing instruction a bit to note that you choose the regional office for your school or home. I sent the updates to Cinda for review along with a question about one of the form instructions, and copied you so you can follow any feedback.

**Comment by katherine-fung** [comment]
Update: Per Cinda's response, I updated the mailing instructions to say "regional processing office," and removed the note about not qualifying for MGIB. 

We're waiting for Cinda's response about the DoD note. 

Page: http://preview-prod.vfs.va.gov/preview?nodeId=946

**Comment by katherine-fung** [comment]
Update: Per Cinda's response, I updated the mailing instructions to say "regional processing office," and removed the note about not qualifying for MGIB. 

We're waiting for Cinda's response about the DoD note. 

Page: http://preview-prod.vfs.va.gov/preview?nodeId=946

**Comment by katherine-fung** [comment]
update from 10/25: 

- Cinda says we can get rid of DoD note. 

- Beth will follow up with Cinda to clarify the status of the National Call to Service program (and whether we should consider retiring this page).

**Comment by RLHecht** [comment]
@megzehn Can you copyedit and publish the find form part of this ticket even though we're still waiting to hear back from Cinda on the program page? Thanks!

**Comment by megzehn** [comment]
Thanks, @RLHecht! Confirming that I copy edited and published the [find form page.](http://preview-prod.vfs.va.gov/preview?nodeId=6122)

**Comment by laurwill** [comment]
Hi @megzehn ,

Cinda said we can go ahead and publish the updates to the NCS page. She's waiting to hear back from a DoD POC about whether NCS is still accepting any new enlistments, but we're reasonably sure this is mostly past tense. We'll update again if we get new info, but we can publish the page to take down the online form now.
