### ISSUE TITLE
[Product] Send QA Screenshots to the State Department

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#48342]
## Tasks
- [x] Create workflow documents that contain screenshots for the Epic/feature
- [x] Submit documents to the Randi Hecht 

## Acceptance Criteria
- [x] Workflow documents have been submitted to Randi Hecht for forwarding to the State Department

**Comment by loripusey** [comment]
Sent QA screenshots to Randi for forwarding to the SD translators. 
[File sent](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/translations/tagalog-round-2/Tagalog%20-%20Round%202_2022-11-21_20-22-54.pdf)
