### ISSUE TITLE
[Product] Send QA Screenshots to the State Department

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#48340]
## Tasks
- [ ] Create workflow documents that contain screenshots for the Epic/feature
- [ ] Submit documents to the Randi Hecht 

## Acceptance Criteria
- [ ] Workflow documents have been submitted to Randi Hecht for forwarding to the State Department
