### ISSUE TITLE
Invert SiS default on USiP. 

### ISSUE THREAD

**Issue by acaruso-oddball** [department-of-veterans-affairs/va.gov-team#48358]
## Issue Description
This issue addresses how use of SiS is determined on the Unified Sign-In Page. When feature toggles are in use, a percentage of users are routed to SiS, and by default the rest are routed to SSOe. 

## Tasks
- [x] Update the USiP to use SiS by default.

## Acceptance Criteria
- [x] Navigating to the Unified Sign in Page (USiP) `/sign-in` **SHOULD** add the `oauth=true` query parameter immediately on mount
- [x] Navigating to the USiP `/sign-in/?oauth=<value>` with the `oauth=<true|false>` query parameter **SHOULD NOT** cause the component to reload, or change the value of the query parameter
- [x] Navigating to the USiP `/sign-in/?application=<unauthorized OAuth app>` with the `application=<ebenefits|mhv>` query parameter SHOULD change the `oauth` query parameter's value to `false` in all cases
- [x] Navigating to the USiP `/sign-in/?application=<authorized OAuth app>` with the `application=<vamobile|vaoccmobile|*undefined>` by default SHOULD add the `oauth=true` query parameter
- [x] Navigating to the USiP `/sign-in/?application=<authorized OAuth app>&oauth=<true|false>` SHOULD NOT cause the component to reload, or change the `oauth=<value>` query parameter

**Comment by AGarcia-Clarity** [comment]
Unit tests complete, In Review
