### ISSUE TITLE
Supplemental Claims | 4142/4142(a) form integration work

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#48364]
@kylesoskin commented on [Mon Sep 19 2022](https://github.com/department-of-veterans-affairs/vets-website/issues/22218)

## Value Statement

**_As a_** Veteran
**_I want to_** authorize medical providers to disclose my medical records
**_So that_** I can submit those records as evidence to support my claim. 

---
## Background Context
- Forms [4142](https://www.va.gov/find-forms/about-form-21-4142/)/[4124a](https://www.va.gov/find-forms/about-form-21-4142a/) will be submitted with the supplemental claim form, enabling medical providers to disclose records for a claim. 
- Code to do this exists already for form 526ez. The assumption is we can easily reuse that code, and just need some bridge/connectors to those existing classes/methods. 

## Acceptance Criteria
- [ ] When a user authorizes the release of VA medical records, form 4142 is instantiated and stored in the Veteran's e-folder.
- [ ] When a user authorizes the release of non-VA (private) medical records, form 4142a is instantiated and stored in the Veteran's e-folder.
- [ ] If the user does not authorize release of medical records, then no form is created, sent, or stored. 

## Designs and Build Notes
- @thehastingsp 

## Out of scope
- Add here

## Open questions

- [x] Is the code in the 526 reusable? (Sort of,  but not totally)
- [x] How much refactoring is required? (A good bit)
- [ ] Are these forms currently stored in the Vet's e-folder? Where else? (Do we care about this? Like who wrote the acceptance criteria and why does it specify the e-folder specifically? We send to central mail currently, and that is all I am planning to do, same as form526, if that is not the same as " stored in the Veteran's e-folder." and that is an actual requirement, then this will have a much larger scope and much more discovery needed) 

## Tasks
- [ ] ~~Move code to submit form4142 outside of current form526 location, generalize it~~
- [ ] ~~Refactor form526 to use it, test/confirm it still works as expected for form526~~
- [ ] ~~Make new code to make supp claim submission use broken out code~~

- [x] Copy/paste relevant code chunks
- [x] Confirm it makes a pdf
- [x] Confirm it sends pdf to central mail
- [ ] Confirm this is sufficient 

---

@kylesoskin commented on [Wed Oct 05 2022](https://github.com/department-of-veterans-affairs/vets-website/issues/22218#issuecomment-1268800575)

Beginning looking into backend code for this now. 

---

@kylesoskin commented on [Wed Oct 05 2022](https://github.com/department-of-veterans-affairs/vets-website/issues/22218#issuecomment-1268833073)

It looks like there is code to submit a 4142, not seeing anything for 4142a. Might just need some more details/clarification on this, still looking into it. 

---

@kylesoskin commented on [Thu Oct 06 2022](https://github.com/department-of-veterans-affairs/vets-website/issues/22218#issuecomment-1270183193)

This will take some more vigorous refactoring. We can't use the current `Form4142Processor` and surrounding code because it all depends on a form526 submission id and stored form data in the db. We wont have any of that for supplemental claims (unless we want to? maybe we should?). 

So Ill need to pull out the relevant submission chunks, refactor existing form526 code to use the pulled out chunks the same way as before, and then create code for supplemental claims to use it how it wants to. Still investigating though.

---

@saderagsdale commented on [Thu Oct 06 2022](https://github.com/department-of-veterans-affairs/vets-website/issues/22218#issuecomment-1270637249)

@saderagsdale @sortizsh Add a separate ticket for e2e, unit testing, accessibility testing.

---

@kylesoskin commented on [Tue Oct 11 2022](https://github.com/department-of-veterans-affairs/vets-website/issues/22218#issuecomment-1274575230)

Instead of pulling everything out and refactoring 526, just copy/pasting/reusing the relevant snippets. Favoring stability of 526 and quickness, over code quality for now.

this is completed, just needs more testing 

---

@saderagsdale commented on [Wed Oct 12 2022](https://github.com/department-of-veterans-affairs/vets-website/issues/22218#issuecomment-1276574424)

@saderagsdale @Mottie FE work will be consolidated into this ticket and tested as one piece of functionality. 

---

@saderagsdale commented on [Mon Oct 17 2022](https://github.com/department-of-veterans-affairs/vets-website/issues/22218#issuecomment-1281112215)

@saderagsdale Move to our repo.

**Comment by saderagsdale** [comment]
@Mottie @kylesoskin I copied this ticket into our repo and closed the one in the other repo.
