### ISSUE TITLE
Create dashboards for Redis monitoring in DataDog

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va.gov-team#48372]
## Description
Redis monitoring is connected to our DataDog instance via the ElastiCache integration. The template dashboard can be seen [here](https://vagov.ddog-gov.com/screen/integration/149/aws-elasticache-redis). Since we have ElastiCache monitoring connected, we want to create separate dashboards for monitoring specific clusters, primarily: 
- `dsva-vagov-prod-rails-cache-002`
- `dsva-vagov-prod-sidekiq-002`
- `app-data`

- potentially others like staging, dev, sandbox

These dashboards should contain metrics on the hit rate, swap usage, CPU utilization, downtime...

## Tasks
- [ ] Create a dashboard for the `dsva-vagov-prod-rails-cache-002` cluster
- [ ] Create a dashboard for the `dsva-vagov-prod-sidekiq-002` cluster

## Acceptance Criteria
- [x] Dashboards for monitoring individual Redis clusters are available.

## How to configure this issue
- [ ] _Attach a Milestone_
- [ ] _Story points_
- [ ] _Sprint assigned if pulling into sprint_
- [x] _Epic assigned_
- [x] _Team label assigned_

**Comment by oseasmoran73** [comment]
Should we also include `dsva-vagov-utility-platform-console-api`?

Looks like the naming conventions are dsva-vagov-*-rails-cache & dsva-vagov-*-sidekiq. We can probably create a variable and filter that way.

Curious what about the dsva-vagov-*? Do we want to bring those in as well?
