### ISSUE TITLE
[task] Contention Mapping | Historical DB pull from va.gov

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#48375]
## Value Statement
**_As a_** team 
**_I want to_** review data we got from the VA.gov
**_So that_** we can determine which codes from that data are in the updated mapping list.

---

## Tasks
- [ ] _DB pull of a bunch of va.gov-submitted claims.

- Submission date
- Benefit claim ID (not the va.gov submission ID, the one we get back from EVSS when a successful submission goes through)
- Contention name text
- If the contention name was chosen from the dropdown or typed freely. (so we can get the percentage mentioned above)
- Classification (but it sounds like this is always the same as the contention name currently?)
- Increase or new?
- Diagnostic code associated with the claim, if available (i believe those would only be available for increases)
- Pull data for a 1 year period minimum, max back to 2019
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
@kylesoskin second ticket for the data request Emily made.

**Comment by kylesoskin** [comment]
Pulled a 30 day set of data, pulling more will require more time to develop a more advanced script (that is multithreaded and supports throttling, as to not bring down prod, but be able to get the data faster). 

Provided to Emily and she said this is good for now and we will revisit later if we need more
