### ISSUE TITLE
FE | Profile | Documentation | Connected Apps

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#48381]
## Background

Review Contact Info ection in GitHub and add/update relevant FE documentation.

## Tasks
- [x] Add analytics documentation on what events we are firing and where in the code they come from (if applicable)
- [x] Document Api calls and how they are set up in the FE code
- [x] Map what error codes that might surface for a particular feature and the alert/messaging it maps to

## Acceptance Criteria
- [x] Analytics documentation on what events we are firing and where in the code they come from added
- [x] Document Api calls and how they are set up in the FE code added
- [x] Map what error codes that might surface for a particular feature and the alert/messaging it maps to completed

**Comment by adamwhitlock1** [comment]
I have published the docs for Connects Apps at

https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/connected_apps/frontend_documentation.md

I have also updated the main outline to include that link.

**Comment by SKasimow** [comment]
woot-woot! thank you!
