### ISSUE TITLE
FSR Review Page - Updates 

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#48384]
## Issue Description
_Discuss path forward for the FSR Review Page. Make updates to present to Platform team._

---
## Tasks
- [x] _Discuss path forward with team_
- [x] _Make updates to review page sections_

## Acceptance Criteria
- [x] _Upload in progress design for FSR Review Page_

**Comment by mgleo** [comment]
Discussed with team on 10/19. We will keep edit functionality on the review page as there are not accessibility concerns with this. When the edit button is being developed there needs to be an ARIA label applied to it that describes what the user is editing.

**Comment by mgleo** [comment]
_Design patterns displayed below are not final._ 

- Discussed button/link best practices with Platform on 11/1/22.
- Reviewing [Review page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/pst-forms-library/research/review-page-round-two/round-2-research-findings.md) research mentioned by Platform.
- More talks with Platform and possibly some experimental design pattern submissions.

![C7P1: Review application - Separate employment and deductions.jpg](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/6c8348ae-06aa-4bd3-a818-bcfb495f1910)
