### ISSUE TITLE
Design for FSR Summary Page ("Mini Summary"

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#48388]
## Issue Description
Once a user enters a custom generated item (example: credit card bill), they will be asked if they have another credit card bill to add. We want to show the user the user the previous credit card bills that they have just entered on this screen. 

---
## Tasks
- [x] _Create mockup for summary pages_
- [x] Mockups needed for the following sections of the FSR (need to validate there aren't any other applications)

- Work History 
- Installment contracts and other debts 
- Other living expenses 
- Household Assets 

## Acceptance Criteria
- [x] _[Link summary page](https://miro.com/app/board/uXjVPLXv9MA=/)_

**Comment by mgleo** [comment]
Received feedback on mockups from Platform on on 11/1/22.
