### ISSUE TITLE
[BE] Onsite notifications: Documentation review/update

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#48383]
## Background
Post launch of onsite notifications MVP we should review all of our design, FE and technical documentation to make sure everything is up to date and reflects the current implementation of the MVP. This is a joint effort from all team members, though we have specific tasks for each of us.

**For backend, we need to make sure we have thorough documentation on the API and VA Notify integration.**

## Tasks
- [x] Consult with Taylor, and review and update (as needed) the [My VA onsite notification flow](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/backend/My%20VA%20On-site%20Notification%20Flow.md)
- [x] Review and update (as needed) [Onsite Notifications Technical Overview](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/backend/onsite-notifications-tech-overview.md) (follow link to sensitive repo)
- [x] Review and update (as needed) [Backend support for notifications on VA.gov](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/backend/technical-diagrams.md)
- [x] Review with PMs/PO

**Comment by tpharrison** [comment]
@ajakabcin - let me know when you want to discuss.

**Comment by tpharrison** [comment]
@ajakabcin @tmitchellgcio 

I've looked over the documents, and it looks like all the information is there.  I think we should condense the three documents into a single doc.

Let me know if you agree and I'll go ahead and combine them.
