### ISSUE TITLE
[Design] Onsite Notifications: Documentation review/update

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#48389]
## Background
Post launch of onsite notifications MVP we should review all of our design, FE and technical documentation to make sure everything is up to date and reflects the current implementation of the MVP. This is a joint effort from all team members, though we have specific tasks for each of us.

## Tasks
- [x] Meet with Liz to go over documentation structure from Profile team
- [x] Review [frontend documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/frontend-documentation/notifications-frontend-documentation.md) (including copy) and ensure documentation aligns with final mvp implementation
- [x] Create user flows
- [ ] Review with PMs/PO

**Comment by Samara-Strauss** [comment]
This is perfect and exactly what we need. Great job!

**Comment by ajakabcin** [comment]
@aagosto90  that flow looks amazing! thank you!

**Comment by ajakabcin** [comment]
@aagosto90 I think this ticket can be called complete - I moved the the use case documentation task over to the PM ticket for documentation updates. Thanks!
