### ISSUE TITLE
[FE] Onsite notifications: Documentation review/update

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#48382]
## Background
Post launch of onsite notifications MVP we should review all of our design, FE and technical documentation to make sure everything is up to date and reflects the current implementation of the MVP. This is a joint effort from all team members, though we have specific tasks for each of us.

## Tasks
- [x] Consult with Adam to see how he crafted and structured technical documentation for Profile initiatives
- [x] Create technical documentation in github outlining how the frontend works, was implemented and how it connects to the backend API.
- [x] Consult with Tom, and review and update (as needed) the [My VA onsite notification flow](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/backend/My%20VA%20On-site%20Notification%20Flow.md)
- [ ] Review with PMs/PO

**Comment by ajakabcin** [comment]
technical FE documentation published in the [Frontend](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/README.md#frontend) section of the product outline

**Comment by tmitchellgcio** [comment]
@ajakabcin anything else you think we need to do to this or do you think it's good to close?

**Comment by ajakabcin** [comment]
hey @tmitchellgcio per our conversation earlier I think this is good to go now - I'll share with Samara for review shortly and we'll let you know if there are any updates needed.

**Comment by tmitchellgcio** [comment]
@ajakabcin should I close this one?

**Comment by ajakabcin** [comment]
@tmitchellgcio sorry yes - all good here. I'll close now
