### ISSUE TITLE
Design | Profile | Research Recommendations | Notification Settings Language

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#48396]
## Background

Describe the issue background and scope

## Tasks
- [ ] Conduct Unit tests 
- [ ] Run E2E tests covering current code and regression
- [ ] All axe checks pass
- [ ] Notify PM if this needs to be deployed to Staging behind feature flag
  

## Acceptance Criteria
- [ ] Complete all unit testing
- [ ] End-to-end tests showing 0 violations
- [ ] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [ ] Confirm PM has opened a new ticket to deploy changes to Production using feature flag, if needed

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)?
- How can this work be validated?
- What updates need to be made (e.g. product outline, use cases, contact center guide)

## Associated Tickets
- #

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
Hi @andaleliz - here's he first ticket; can you add points please.

cc/ @ericasauv09

**Comment by andaleliz** [comment]
I've updated the Sketch files as much as I can on this - now blocked until we get BVA approval on #47441

**Comment by andaleliz** [comment]
@SKasimow and @ericasauv09, FE can go ahead and clean up spacing. The language updates will come through the API so no FE work there.

Spacing has been updated in the Sketch files, and I created [this mock-up](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/jg8yMMb) to make it more clear how far away elements should be from each other. 

We also need to update the link copy to say "update mobile number" in the Sketch files; it currently says something else on production.

I'm leaving this ticket open and blocked for myself until we hear back from BVA on the updated group/item names.

**Comment by andaleliz** [comment]
We heard back from BVA a while ago and I forgot to close this ticket.
