### ISSUE TITLE
Supplemental Claims | Opt into the AMA decision review process

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#48397]
## Value Statement
**_As a_** Veteran
**_I want to_** opt into the AMA decision review process
**_So that_** potentially get a faster decision. 

---
## Background Context
This page is in place, it should only need:
- Content updates
- Check and/or add unit tests
- Add e2e test for this page

## Acceptance Criteria
- [ ] Users may check the box OR skip in order to press **Continue**
- [ ] Page isn't shown if the user has no legacy issues
- [ ] Users may leave this step in the form and return to their saved progress
- [ ] Unit tests complete (90% coverage)
- [ ] E2E tests complete
- [ ] Accessibility testing complete
- [x] Reviewed and approved by product and/or design

## Designs and Build Notes
[DESIGN](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/p/05B84E72-A361-4CB3-B1A3-EC5FF2BE3260/canvas)
[CONTENT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/sourceofcontenttruth.md)
[Prototype](https://www.figma.com/proto/JveclTFbNNSmx4eiYwbZdZ/Supplemental-Claims?node-id=70%3A5676&scaling=scale-down&page-id=10%3A1697&starting-point-node-id=70%3A5676)

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [x] _Design approved_
- [x] _Content approved_

## Definition of Ready
- [ ] _Clear value description_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [x] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by thehastingsp** [comment]
Design approved, content still in progress

**Comment by thehastingsp** [comment]
[content approved](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/sourceofcontenttruth.md)

**Comment by Mottie** [comment]
This work is ready to be reviewed in staging. Please note that the URL is now https://staging.va.gov/decision-reviews/supplemental-claim/file-supplemental-claim-form-20-0995 - if you get a page not found message, remove the /introduction from the URL

**Comment by thehastingsp** [comment]
looks good from design/content.
