### ISSUE TITLE
Supplemental Claims | Acknowledge the VA's duty to assist

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#48399]
## Value Statement
**_As a_** Veteran
**_I want to_** acknowledge that I have received the notice of evidence required to substantiate a claim for disability benefits
**_So that_** I can fulfill this step in the claim process without having to leave the form. 

---
## Background Context
- Add here

## Acceptance Criteria
- [ ] User must check the box to press **Continue**

## Designs and Build Notes
- [DRAFT DESIGN (NOT APPROVED)](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/p/9872C53A-62DB-47BB-87D4-3480519D4B45/canvas)

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready
- [ ] _Clear value description_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by thehastingsp** [comment]
design and content approved

**Comment by Mottie** [comment]
This work is ready to be reviewed in staging. Please note that the URL is now https://staging.va.gov/decision-reviews/supplemental-claim/file-supplemental-claim-form-20-0995 - if you get a page not found message, remove the /introduction from the URL

**Comment by thehastingsp** [comment]
hey @Mottie I'm expecting to see this after AMA opt-in, but don't. I see evidence choice?

**Comment by thehastingsp** [comment]
the design, content and error state look good otherwise.

**Comment by thehastingsp** [comment]
sounds good! @eileen-coforma I'll ask you to keep an eye on this one please

**Comment by saderagsdale** [comment]
@Mottie also confirming that I don't see this after the AMA opt-in.

**Comment by Mottie** [comment]
Do we want to fix this before we close this ticket?

**Comment by saderagsdale** [comment]
@Mottie Yeah let's get it in the right place if it's a straightforward fix.

**Comment by Mottie** [comment]
[Opened this PR to move the pages around](https://github.com/department-of-veterans-affairs/vets-website/pull/22660)

**Comment by Mottie** [comment]
Ready for review, with updated page order

**Comment by saderagsdale** [comment]
@Mottie looks good to me.
