### ISSUE TITLE
Supplemental Claims | Review and submit

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#48403]
## Value Statement
**_As a_** Veteran
**_I want to_** review and submit the information I shared related to my claim
**_So that_** I can confirm I've added all relevant info before proceeding. 

---
## Background Context
- Add here

## Acceptance Criteria
- [ ] User may edit sections of the form without losing their progress

## Designs and Build Notes
- [DRAFT DESIGNS (NOT APPROVED)](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/a/uuid/F532A91E-2914-4701-9D08-09B1B448E4E2)

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready
- [ ] _Clear value description_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by thehastingsp** [comment]
@saderagsdale @Mottie added final design to this ticket as well as a prototype link.

**Comment by thehastingsp** [comment]
Content approved

**Comment by eileen-coforma** [comment]
@data-doge @Mottie Updated the design, and added a form submission error alert for this page. Also added that to the AC requirements. 

Error is for any (hopefully minor cases) where the form can not be submitted, possibly due to payload/json schema violations that are out of vet control. [Supp Claims Error Responses 422 and 429](https://developer.va.gov/explore/appeals/docs/decision_reviews?version=current) Possible resolution is for veteran to resubmit the form on another day.

Let me know if there are restrictions on this page that could prevent us from showing this alert.

Alert message is not finalized, reviewing it with Beth before EoD (hopefully)

**Comment by Mottie** [comment]
Work complete and ready for testing in staging.

**Comment by eileen-coforma** [comment]
@Mottie The limit information section is not showing up accurate on review and submit. It's stuck on the default 'no i don't want to limit' even when I add an limitation.

**Comment by Mottie** [comment]
Fixed in staging. Ready for review.

**Comment by saderagsdale** [comment]
![Screen Shot 2023-01-12 at 11 34 00 AM](https://user-images.githubusercontent.com/90406121/212138522-c20d1618-7219-48c0-b707-c397d5602064.png)
 Finished product in staging should match this design snapshot.

**Comment by rocio-desantiago** [comment]
@saderagsdale text updated in this ticket [#49553](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49553). Can this ticket be closed since those are related to the other ticket?

**Comment by saderagsdale** [comment]
Will add download link as a separate ticket.

**Comment by saderagsdale** [comment]
@eileen-coforma any concerns with me closing this one?

**Comment by eileen-coforma** [comment]
@saderagsdale This can be closed :)
