### ISSUE TITLE
Supplemental Claims | Authorize the release of my records

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#48408]
## Value Statement

**_As a_** Veteran
**_I want to_** authorize medical providers to disclose my medical records
**_So that_** I can submit those records as evidence to support my claim. 

---
## Background Context
- partner to [#22218](https://github.com/department-of-veterans-affairs/vets-website/issues/22218)
- Forms [4142](https://www.va.gov/find-forms/about-form-21-4142/)/[4142a](https://www.va.gov/find-forms/about-form-21-4142a/) will be submitted with the supplemental claim form, enabling medical providers to disclose records for a claim. 
- Code to do this exists already for form 526ez. The assumption is we can easily reuse that code, and just need some bridge/connectors to those existing classes/methods. 

## Acceptance Criteria
- [ ] Unit tests complete (90% coverage)
- [ ] E2E tests complete
- [ ] Accessibility testing complete
- [ ] Reviewed and approved by product and/or design

## Designs and Build Notes
- [Approved design](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/v/5Ony3d/p/274ABD98-987B-4C4D-BB93-8FCE3DD6C3DE/canvas?posX=-3716.9970703125&posY=-77.50830078125&zoom=0.5)
- [CONTENT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/sourceofcontenttruth.md)

## Tasks
- [ ] write end to end tests and perform qa/smokes for https://github.com/department-of-veterans-affairs/vets-website/issues/22218
- [x] Copy/paste relevant code chunks
- [x] Confirm it makes a pdf
- [x] Confirm it sends pdf to central mail
- [ ] Confirm this is sufficient 

## Definition of Ready
- [x] _Clear value description_
- [x] _Testable acceptance criteria_
- [x] _Accessibility added to acceptance criteria_
- [x] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [x] _Estimated to fit within the sprint_
- [x] _Dependencies and blockers linked_

## Definition of Done (user story) 

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by thehastingsp** [comment]
Design approved, content still in progress.

**Comment by thehastingsp** [comment]
Content approved.
