### ISSUE TITLE
[FE] [BUG] Confirmation page has incorrect title when using app in Spanish

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#48414]
## How to reproduce

* start app in spanish
* answer "Si" to all questions
* check in to an appointment

The title is not modified to include the travel reimbursement content, and the travel pay success message is not shown.

## Notes

@brianseek said that the answers are stored in spanish in redux.

## Tasks
- [ ] Add e2e tests for travel reimbursement flows in spanish

## Acceptance Criteria
- [ ] travel reimbursement flows work correctly in spanish
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
