### ISSUE TITLE
[Design] [UX] Create Final Wireframes for Needs Information Updated Scenarios

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#48411]
## Tasks
- [ ] Create final mockups with callouts for these scenarios
    - Need to Update Contact Info & needed - Choose to NOT file
Updates needed - Claim filed/
Updated needed - Claim NOT filed
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [ ] UI review meeting with product/UX team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.
