### ISSUE TITLE
[Design] [UX] Create Final Wireframes for Needs Information Updated Scenarios

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#48412]
We need to talk through whether we will offer the option to submit a travel reimbursement for the scenario where the Veteran needs to update their contact information and will need to check-in with a staff member.

Current h1 is Check in with a staff member

Midpoint review branch in abstract is most recent: https://share.goabstract.com/3f25b4c0-4404-4079-a938-367f40c4903b?collectionLayerId=4199b42f-0af0-4d35-9d34-fba11f982815&mode=design

## Tasks
- [x] Check if the content is different for "No" to contact information, EC, Next of kin 
- [ ] Create final mockups with callouts for these scenarios
    - Need to Update Contact Info & Choose to NOT file a travel claim (3 wires, one for cc, ec, next of kin) 
    - Need to Update Contact Info & Choose to file a travel claim & it was Filed (3 wires, one for cc, ec, next of kin) 
    - Need to Update Contact Info & Choose to file a travel claim & it could NOT be Filed (3 wires, one for cc, ec, next of kin) 
- [x] Add final content in [Google document](https://docs.google.com/document/d/1tSuRWQ-dveIh5NwWVKSVY6ZC4bAL70exV0axJjfAVhM/edit?usp=sharing)
- [ ] Tell Lori when content is finalized in order to hand over to state dept.
- [x] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [ ] UI review meeting with product/UX team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Wireframe available in abstract branch
- [ ] Lori notified of finalized content
- [x] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 I added the "existing" content in the [Google document ](https://docs.google.com/document/d/1tSuRWQ-dveIh5NwWVKSVY6ZC4bAL70exV0axJjfAVhM/edit?usp=sharing)for when a Veteran says "No" to either confirming their contact information, emergency contact information or next of kin. We'll want to keep some of that content for these new scenarios.

**Comment by benbrasso-agile6** [comment]
@loripusey does this scenario: 

> Need to Update Contact Info & Choose to file a travel claim & it could NOT be Filed (3 wires, one for cc, ec, next of kin)

Assume that there's one test case for, 1) they answered No to a question, and 2) the API returned an error? Or should those be split up into two scenarios?

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 wrote the new content. Being routed to Danielle for review. https://docs.google.com/document/d/1tSuRWQ-dveIh5NwWVKSVY6ZC4bAL70exV0axJjfAVhM/edit# 

Danielle has confirmed she has time to review this week.

**Comment by loripusey** [comment]
These are all the possible combinations that I can see. Have we decided if we should allow them to file if they have updates to their contact info?

<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

  | All Contact Correct | Demo Not Correct | EC Not Correct | NOK Not Correct | Demo & EC Not Correct | Demo & NOK not correct | EC & NOK Not Correct | Demo, EC, & NOK Not Correct
-- | -- | -- | -- | -- | -- | -- | -- | --
WANT to file & MEETS criteria & Claim Filed Successfully | X | X | X | X | X | X | X | X
WANT to file & MEETS criteria & General API Error | X | X | X | X | X | X | X | X
WANT to file & MEETS criteria & Claim Exists Error | X | X | X | X | X | X | X | X
WANT to file & MEETS criteria & Multiple Appts Error | X | X | X | X | X | X | X | X
WANT to file & DOES NOT meet criteria | X | X | X | X | X | X | X | X
DOES NOT want to file | X | X | X | X | X | X | X | X


</body>
</html>

**Comment by benbrasso-agile6** [comment]
So far, yes, we are proceeding with allowing them to file. The content seemed to support a good Veteran experience.

**Comment by benbrasso-agile6** [comment]
@loripusey here is a good example (I think) for a branch that should be kept separate, considering it likely won't be in MVP

**Comment by loripusey** [comment]
that makes sense

**Comment by zach-park** [comment]
@kellysmith1008 @benbrasso-agile6 (cc: @loripusey), the wireframes are ready for UX review:
https://share.goabstract.com/4ba88b6d-7dbe-4060-9aac-80c0a72e7dba?collectionLayerId&mode

**Comment by kellysmith1008** [comment]
LGTM, @zach-park !

**Comment by benbrasso-agile6** [comment]
@zach-park I would recommend the yellow box (instead of blue box) for the 3rd and 4th wireframe. This is what we used in the main travel pay branch.

**Comment by benbrasso-agile6** [comment]
@loripusey suppose we wait until the end of the next sprint to send content in the state department, since we need to still do the additional error wirefames

**Comment by loripusey** [comment]
I already sent it; we can send again, there is no limit to how many times we can make a request to them

**Comment by zach-park** [comment]
The infobox component is updated (on thrid and fourth wireframe) as Ben mentioned.
