### ISSUE TITLE
Investigate getting staging environment to pull injected header / footer from staging rather than from the production S3 bucket

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-team#48415]
## Description
During a recent failure of the injected header ([header injected into TeamSite sites](https://depo-platform-documentation.scrollhelp.site/developer-docs/teamsite-overview) and subsites it was discoved that the staging environment pulls the injected header and footer from prod.  This makes it impossible to fully test without releasing to prod first.
## Tasks
- [ ] Research why staging pulls injected code from prod, rather than staging
- [ ] Determine course of action to make staging pull code from staging so that proper testing can be done.
  - [ ] Create related issues

## Acceptance Criteria
- [ ] Issues are created that when completed, would allow for staging to pull the injected header and footer from staging.

## How to configure this issue
- [ ] ?

**Comment by kscoulter** [comment]
@department-of-veterans-affairs/cms-team please see the most recent postmortem involving this issue https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/913

**Comment by FranECross** [comment]
This ticket belongs to the CMS team. I'm removing the link to our epic, and will be closing that epic. I'll reference the [epic](https://app.zenhub.com/workspaces/vagov-sitewide-product-team-6645154188a81a1f7a0a9464/issues/gh/department-of-veterans-affairs/va.gov-cms/11242) here for an audit trail.
