### ISSUE TITLE
[FE] [BUG] Content flashes on check-in confirmation page

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#48413]
## How to Reproduce

* Answer "yes" to all questions
* Check in to an appointment

the confirmation page shows very briefly with the non-travel content, then shows the loading message, then shows the travel content.

## Tasks
- [ ] Prevent incorrect initial content from being shown
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [x] Read ticket details and verify that ACs are met
- [x] Review code in PR
- [x] Run branch locally
- [x] Check that new and updated translations use new keys
- [x] Check for hardcoded strings
