### ISSUE TITLE
Design | Profile | Research Recommendations | Notifications - Add Mobile Number Flow

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#48410]
## Background

During the recent research sessions we observed that users were disrupted by having to leave the notifications preference page to add their mobile number. We want to review the design for this flow and specifically the link text "manage text notifications" as many users missed that this would take them back to the notifications preferences page.

Detailed findings [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2022-09-profile-editing-evaluation/findings-summary.md#5-6-of-11-participants-were-disrupted-by-having-to-leave-the-notification-settings-page-to-add-a-mobile-number)

## Tasks
- [x] Explore alternatives adding or updating a mobile number from the notification settings page
- [x] Review design options with accessibility 
- [x] Review design options with FE 
- [x] Review design options with PM and PO 
- [x] Create new sketch files/update existing ones where applicable
  

## Acceptance Criteria
- [x] Approvals received
- [ ] Documentation updated
- [x] Notify PM that it is ready for FE implementation

**Comment by andaleliz** [comment]
@ericasauv09 👏 awesome job writing this up, the AC is especially great. Thank you!

**Comment by andaleliz** [comment]
@Samara-Strauss, @ericasauv09 and @SKasimow I have a concept for this and set up a meeting for us to review on Monday.

**Comment by andaleliz** [comment]
We reviewed three options (screenshots below, [link to Mural](https://app.mural.co/invitation/mural/vsa8243/1666560614852?sender=lizlantz1528&key=c2645042-710b-4a4a-b48b-8bc8a6cafed7)). Ultimately, we feel option 3 is the best UX, but want to pursue moving forward with option 1 for now, since we know the notification settings page will grow in complexity and we'll have more opportunity to test a bigger change (option 3) when we revisit the rest of the page.

As a next step, we want to get some details from our FE team on option 1.  

---

**Option 1**
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/55992116/197594335-e29944c5-c202-400f-8387-2719949a9ae9.png">

The concept with this option is that we would keep the UX largely as-is, with the following changes:
1. Have the relevant section open in "edit" mode instead of "read" mode like it does today.  I think the first field would get focus, need to check with a11y.
2. Update button would save the form _and_ redirect people back to notification settings page.
3. Add a save confirmation alert to the top of the notification settings page.
4. Cancel button would return the contact page to "read" mode, and redirect people back to notification settings

@adamwhitlock1 and @jcatergovy this is a little different than what I wrote in Slack; I don't think we need to worry about controlling the viewport if the form is open.

Samara would like to get an idea of the LOE (1 sprint? 2+ sprints?) from your perspectives to implement this, and how reliable this solution is. It relies on redirects solving the problem of people struggling to get back to notification settings, and conditional logic to open the mobile section in edit mode, and display an alert.

What are your thoughts? Any "gotchas" I'm not thinking of? We don't want to implement this if it's janky and not really an improvement over what we have.

---

**Option 2**

<img width="626" alt="image" src="https://user-images.githubusercontent.com/55992116/197594452-b98cc3ba-0d52-4f01-8bdb-0ecc70d91ed4.png">

This option is the least scalable of the 3, so we're going to scrap it for now.

---

**Option 3**

<img width="817" alt="image" src="https://user-images.githubusercontent.com/55992116/197594531-98a5be89-f5ac-4a3c-8fb2-f95973734f11.png">

This is the clearest UX, but we'll save this for later when we revisit the rest of the page.

---

**Comment by SKasimow** [comment]
We can also cover in grooming once you can join Liz if that is helpful for Adam + John

**Comment by andaleliz** [comment]
FYI [here's some background](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26914) on this issue overall (editing contact info in the middle of another task), as well as [a doc I wrote up outlining various related use cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/research/improving-editing-mid-task.md).

**Comment by andaleliz** [comment]
We had a very productive meeting ([notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/meeting-notes/10.27.22_IA-a11y-FE-subtask-discussion.md)) and determined a way forward.  We decided to move forward w/ a single URL and leverage query parameters for dynamic content. 

The mock-ups are ready to go:

- [Mobile form](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/v8ej4q3)
- [Desktop form](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/wLGk4J9)
- [Mobile page w/ confirmation message](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/4al7YGJ)
- [Desktop page w/ confirmation message](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/WKLzddk)

This is ready for FE exploration! I'm going to hold off on updating documentation since this isn't live yet.  Once we have this on staging, can you open a documentation ticket for me please @SKasimow ?

**Comment by Samara-Strauss** [comment]
Fantastic! Thank you, Liz!!
