### ISSUE TITLE
[FE] Display Error Message when General BTSSS API Error Encountered

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#48426]
## Description
When we attempt to submit a travel claim and receive a general BTSSS API error, we should display a message to the user letting them know that we could not submit their claim.

## Wireframes
[Wireframe](https://app.abstract.com/projects/ab30c34e-e2f9-4d3e-bb96-3b683b006c24/branches/ac31709b-2855-41d4-a01c-be1c01d7356c/commits/26ba433f99f8b2576e21d58be4616f452ebd3dcc/files/585436fe-2120-45f4-b4f7-fbae01d258d9/layers/9C059432-24E0-4E89-971E-90EFA44BC078?collectionId=57d1d456-eaea-4ad2-9f62-8e2c91ec31ca&collectionLayerId=9421e29d-1565-4e6a-9ae5-0ca507077a80&mode=design)

## Tasks
- [ ] [FE] **display an error message if there is a BTSSS API error**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [x] Read ticket details and verify that ACs are met
- [x] Review code in PR
- [x] Run branch locally
- [x] Check that new and updated translations use new keys
- [x] Check for hardcoded strings
