### ISSUE TITLE
[eFSR] Other Assets Enhancement

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#48438]
## Issue Description
Add Checklist to input list and mini summary options for other assets.

~~[Other assets uxpin (old design)](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145084980/specification/sitemap?mode=i)~~

[Mural for mini summary design update](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1671734127581/dc254b12e788570c946af60bc55338b0045aea03?invited=true&sender=87471762-a55a-4514-88d1-4cb4b90f7fb6)

**NOTE:** Be sure to use Mural for up to date mocks, the following screenshots are just for quick reference.
<details><summary>Checkbox Page (click to expand):</summary>

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/0b0b7805-050a-45e4-b6a5-efedfcac3cec)
</details>

<details><summary>Input List Page (click to expand):</summary>

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/11f8c335-a7a0-43fa-83bc-23fd63771e0b)
</details>

<details><summary>Mini Summary Page (click to expand):</summary>

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/4ce66ed9-87ad-447c-8a1c-371fb90fd668)
</details>

<details><summary>New Asset Page (click to expand):</summary>

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/d31677df-a944-4902-aba3-729303af8346)
</details>

---
## Tasks
- [ ] Add the following pages:
  - [ ] Checkbox page 
  - [ ] Input list page
  - [ ] Mini Summary page
  - [ ] New Asset inputs
- [ ] Show list in final review page
- [ ] Update efsr specific e2e testing
  - [ ] Include item removal and addition

## Acceptance Criteria
- [ ] Page matches design and functionality
- [ ] All new and existing tests are passing

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
Moving back to ready as a part of planning/reordering

**Comment by Dr-Pongo** [comment]
Updated post midpoint review with new designs!
