### ISSUE TITLE
[Design] Profile 2.0: Navigation exploration

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#4843]
## User Story

As a user, I need to be able to easily find and manage my personal information.

## Background

@rtwell is working on navigation explorations for VA.gov as a whole and we want to figure out how the Profile 2.0 work fits into that in the long and short term.

## Tasks
- [x] @tressaellen and @rtwell regroup on the Profile 2.0 navigation.
- [x] Tressa and Ryan figure out an approach for the Profile 2.0 design.

## Acceptance Criteria:
- [x] Navigation is finalized for Profile 2.0
