### ISSUE TITLE
[FE] Do Not Allow User to File a Travel Claim when they have More Than One Appointment for Today

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#48431]
## Description
The BTSSS API will not allow a claim to be filed when the Veteran has more than one appointment for the day. We need to NOT show the travel questions to a Veteran who has more than 1 appointment for today.

## Tasks
- [ ] [FE] **DO NOT show the travel questions to a Veteran who has more than 1 appointment for today**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
