### ISSUE TITLE
PM | Profile | Research Recommendations | Review Analytics For Editing Addresses

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#48439]
## Background

During the recent research sessions we observed that some users were confused by the address validation process. One issue noted was that during the editing process if a user does not save or cancel their changes they will see a modal that informs them that they are in the middle of editing and need to save their changes (see screenshot below). 

We want to determine how many users see this modal during the address validation/editing flow but do not properly save or cancel their changes. Analytics can help inform us on the severity of this issue.

Detailed findings are [here.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2022-09-profile-editing-evaluation/findings-summary.md#3-in-the-contact-information-section-we-observed-some-usability-hurdles-that-slowed-multiple-people-down)

**Screenshot:**

![Screen Shot 2022-10-21 at 1.44.45 PM.png](https://images.zenhubusercontent.com/5fb57aafa11eae0592a15cb1/9d519a49-b2be-4e84-9e48-9309c03d48ad)

## Tasks
- [x] Utilize GA to pull metrics around the address validation flow
- [ ] Share findings with team/design
- [ ] Attend Analytics office hours if needed

## Acceptance Criteria
- [ ] Metrics around address validation flow are shared with team

**Comment by SKasimow** [comment]
[https://app.zenhub.com/files/133843125/45c8eea6-6a62-41ae-9f36-c7ee38527664/download](https://app.zenhub.com/files/133843125/45c8eea6-6a62-41ae-9f36-c7ee38527664/download)

**Comment by andaleliz** [comment]
Hey @SKasimow have you completed your analysis of this? Looking at that screenshot it does not appear that we're seeing a similar % of users on the live site do this as we did in the study (~36% did in the research study). Do you agree?

**Comment by SKasimow** [comment]
It's definitely a much smaller percentage in the general population; runs about 7% month over month. I suspect you saw 36% given that 1) the audience you used was **much** smaller and 2) the demo that was targeted for these sessions.

However, 7% still feels like there is room for improvement and now that we have a baseline would be interesting to see if we can decrease this and try to get under 5% (I think 3% would be a a good stretch goal!).

LMK if you want to discuss further!

**Comment by andaleliz** [comment]
We discussed further in sprint planning and learned a few things:
- This happens because of a technical limitation in the form system; essentially we can only have one set of form fields on a page.  It may be a non-issue when we get a new form system
- Because contact info editing is an important task, we should see what we can do to improve this UX, as a backlog item (not urgent)
- It would be helpful to look at the metrics from a couple of different angles:
   - how many sessions have multiple instances of viewing this alert, compared to those that have 1 or none?
   - instead of comparing to overall page views, could we compare the modal metric to "page views with a click of the edit button (indicating someone tried to edit something)"

**Comment by SKasimow** [comment]
Closing this ... new ticket opened for act'l research #49193
