### ISSUE TITLE
PM | Profile | Research Recommendations | Explore Analytics Around Adding Mobile Number Flow

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#48437]
## Background

During the recent research sessions we observed that users were disrupted by having to leave the notifications preference page to add their mobile number. We want to review the analytics for this flow and specifically the link text "manage text notifications" as many users missed that this would take them back to the notifications preferences page. By understanding the metrics around this flow and determining how many users see the "manage text notifications" link but do not engage with it, we can determine if this flow needs to be adjusted.

## Tasks
- [x] Use GA to determine if it is possible to analyze this flow
- [x] Pull specific metrics re: "manage text notifications" link
- [x] Share findings with team
- [ ] Attend analytics office hours if needed
  

## Acceptance Criteria
- [ ] Metrics around the add mobile number flow are pulled, where possible and shared with design

## Associated Tickets
- #48410

**Comment by ericasauv09** [comment]
So far I have found that only 132 users clicked on the "add a mobile number to your profile" modal in the Not Settings page in a 2 month period. In addition about 1400 users clicked on the "manage text notifications" modal after adding their mobile number in that same 2 month period. However about 32,000 users added a mobile number to their profile during that time period.

**Comment by andaleliz** [comment]
That's ok, no worries. A few questions/thoughts:

1. There's a couple of points where you reference a modal, but there isn't a modal in this UX.  Just want to be sure the events you looked at did NOT say "modal" anywhere in them? I think they're usually tagged.

2. I'm having a hard time making sense of these numbers (possibly because I have not yet finished my coffee). A person should only see the "manage text notifications link" after adding their mobile number if they came from the notification settings page.  The difference between the 132 and 1,400 number is 1,268. Does that means that 1,268 navigated from notif. settings to contact info via some other way besides the "add a mobile number" link in the alert? 

3. Is the 32,000 number related to notification settings at all, or is that just overall, how many people added a number?

Thanks for helping me understand this!

**Comment by ericasauv09** [comment]
@andaleliz 

1. You are correct, the events do not say "modal" that was just my wording, sorry for the confusion - this is the event I am referring to in GA: "Navigation - Alert Box - Link Click - warning - We don't have your mobile phone number - (not set) -  Add a mobile number to your profile"

2. I thought that was odd as well so I tested it with my own account and if you navigate to the Notf Settings page and see the "you don't have a mobile number" alert and then navigate to the "contact info" page and add a mobile number you will see the "manage text notifications" link. So I am assuming that is why there is such a great difference, users may just be navigating to the contact info page themselves rather than using the "we don't have your mobile number" link. That is just my theory. Here is the event for that: "Navigation - Alert Box - Link Click - success - Update saved. Now you can manage text notifications - (not set) - manage text notifications"

3. That number is just the # of users who have added a mobile number to their profile, I thought it would be helpful to compare how many users have added a # vs how many have utilized the "add a mobile number to your profile" link from the notification settings page.

**Comment by andaleliz** [comment]
>I thought that was odd as well so I tested it with my own account and if you navigate to the Notf Settings page and see the "you don't have a mobile number" alert and then navigate to the "contact info" page and add a mobile number you will see the "manage text notifications" link. So I am assuming that is why there is such a great difference, users may just be navigating to the contact info page themselves rather than using the "we don't have your mobile number" link. That is just my theory. Here is the event for that: "Navigation - Alert Box - Link Click - success - Update saved. Now you can manage text notifications - (not set) - manage text notifications"

This is weird, I'm not sure what to make of this. I guess what we need to evaluate to figure out if this is a problem is to see how many people overall followed the navigation path of Notification Settings > Contact info during that period. And then we could compare that number to the 1400 people who clicked the `manage text notifications` link.  I _think_ that would tell us if there's a big breakdown in going back to the notification settings page or not.  Do you agree?

**Comment by ericasauv09** [comment]
Yea that is what we were hoping to be able to pull originally but I could not figure out how to pull analytics on user flows or if it was possible, we can attend analytics office hours and see if they have any ideas on how to pull this. @SKasimow what do you think?

**Comment by andaleliz** [comment]
I think I know! When you are looking at info for a page under the Site Content section, you can click on "Navigation Summary" next to the "Explorer" tab and see what the next page path is. 

<img width="1498" alt="image" src="https://user-images.githubusercontent.com/55992116/200936745-09d1d7e1-e7db-4666-a608-1cb8478c8d20.png">


If you can tell me the date range you used, I can look at the report myself. We could also do it on a call (tomorrow?) so you can learn too.

**Comment by ericasauv09** [comment]
Wooow, I spent like 2 hrs trying to figure that out and I could have just asked you lol! I used Aug 1st - Oct 20th for my date range, so looks like there was 16,060 page views from contact info to notification settings during that time

**Comment by andaleliz** [comment]
Oh no! I'm so sorry, I didn't realize you didn't know how to do that. 

Looking at that date range for contact information, I see the notification settings was the previous page path for ~21,000 pageviews, and the next page path for ~16,000 page views. So there's a 4,000 page view drop off. Ah, but honestly I'm not sure if that's really significant. Analytics is hard :( 

If you think pulling updated numbers on the manage text notifications link will help, please do! I tried to go in and look at how many times that event occurred in a session and compare it to the pageviews and just confused myself even more. Womp womp.

**Comment by ericasauv09** [comment]
lol no worries! I didn't think to ask and I learned a lot by digging around in GA. 

We can jump on a call tomorrow if you want and discuss more, I think the page flow is helpful but it still is hard to correlate that back to how many users are seeing the alert to add a mobile # vs how many are interacting with it and then returning via the "manage text notifications" link.

**Comment by andaleliz** [comment]
The day got away from me but I set something up for us tomorrow. I don't think it matters as much if they see that alert to add a mobile number, since they wouldn't see "manage text notifications" unless they came from the notification settings page.  

I guess the real question we're trying to answer is "how many people get that manage text notifications link, and don't use it?"
