### ISSUE TITLE
[eFSR] Content changes - Part 2

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#48446]
## Issue Description
Extracting content changes still outstanding from #47357

---
## Tasks
- [ ] Update content changes to reflect what the mockups show. 
[Design ticket reference](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/46160)

## Content changes include:

- [x] [Retirement accounts](https://app.uxpin.com/edit/8974674?_gl=1*1isa1do*_gcl_aw*R0NMLjE2NjA2NjQ5ODcuQ2owS0NRandnTzJYQmhDYUFSSXNBTnJXMlgyXzZXRE8yRVFZaHBNcXZPQk5peTZKZW93NzN4VjFMc2ktdlJ1TVVNSWN0ZjBZdHhuOW50Y2FBbXQtRUFMd193Y0I.#?id_page=145084977) - add "TSP"
- [x] [Retirement accounts](https://app.uxpin.com/edit/8974674?_gl=1*1isa1do*_gcl_aw*R0NMLjE2NjA2NjQ5ODcuQ2owS0NRandnTzJYQmhDYUFSSXNBTnJXMlgyXzZXRE8yRVFZaHBNcXZPQk5peTZKZW93NzN4VjFMc2ktdlJ1TVVNSWN0ZjBZdHhuOW50Y2FBbXQtRUFMd193Y0I.#?id_page=145084977) - clarify brokerage account for stocks and bonds?
- [x] [Monetary assets](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145084977/comment/sitemap,comments/6330c943e6ed8d007267d225?mode=i) - Change "the following" to"these" 
- [x] [Confirmation](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/146487721/comment/sitemap,comments/6330cde2ddb307014e208c86) - Change to: Login.gov, ID.me, DS Logon, or My HealtheVet. Change "Once you're signed in" to "After you sign in" *Controlled by Platform :(*
- [x] [Veteran Information](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145021777/simulate/sitemap?mode=i) - Change Note text to match uxpin
- [x] [VA Benefits](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/146446311/simulate/sitemap?mode=i) - Change info text to match.

#### Pending new FE ticket for implementation:
- [ ] [Add a medical bill](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145482544/comment/sitemap,comments/6330cb1eddb307014e208c85) Change "one medical bill below" to "one medical bill here"
- [ ] [Other debt selection](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145482546/comment/sitemap,comments/6330cb84681b28013416e68f) - Change "debt below" to "debt here"

### Effort covered in other tickets:
- [x] [Spouse's Payroll](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145842699/comment/sitemap,comments) - change "the following" to "these" Included in: [#48750](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/48750)
- [x] [Vehicle value](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145354965) - "This includes vehicles with a loan." Included in: [#46688](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/46688)
- [x] [Real estate value](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4?_gl=1*uewksx*_gcl_aw*R0NMLjE2NjA2NjQ5ODcuQ2owS0NRandnTzJYQmhDYUFSSXNBTnJXMlgyXzZXRE8yRVFZaHBNcXZPQk5peTZKZW93NzN4VjFMc2ktdlJ1TVVNSWN0ZjBZdHhuOW50Y2FBbXQtRUFMd193Y0I.#/pages/146385053/comment/comments,sitemap) - "This includes properties with a mortgage." Included in [#48752](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/48752)
- [x] [Payroll](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145842699/comment/sitemap,comments) - change "the following" to "these" Included in [#46674](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/46674)
- [x] [Add a credit card bill](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145377492/comment/sitemap,comments/6330caca660304002288c5c5?mode=vid) - change "bill's" to "bill" Included in: [#46668](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/46668)
- [x] [Housing expenses](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145022052/comment/sitemap,comments/6330ca8c8b556b003b931c4b?mode=i) Change "the following expenses" to"these expenses" Included in: [#48440](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/48440)
- [x] [Utility bills](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145111152/comment/sitemap,comments/6330caa7f6cbe90097241cd5?mode=i) - Change "the following" to"these" Included in: [#48507](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/48507)
- [x] [Real estate](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/146385053/comment/sitemap,comments/6330c98ea2db6a007203aebd) - Change "regarding your request" to "on your request". Delete "in order". Included in [#48752](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/48752)

## Global Content Changes include: 
_(want to ensure they are handled everywhere)_
- [ ] Global - new breadcrumb text: Home  ›  Manage your VA debt   ›  Request financial help (VA Form 5655)
- [x] Global - new header: Request help with VA debt for overpayments and copay bills
- [x] Global: Need Help? section: change "VA debt" to "VA debt related to benefit overpayments" 
Make sure to include the "TTY:' in the aria label too.

## Acceptance Criteria
- [ ] All content changes match markup
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by OptionSelect** [comment]
Marked https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/48446 off due to being changed in current employment history work.

**Comment by Dr-Pongo** [comment]
Medical and other debts section will be in their own tickets when implemented, and breadcrumbs appears to be platform dependent, so that work will move out to an investigatory ticket.
