### ISSUE TITLE
Need additional aws access.

### ISSUE THREAD

**Issue by CBMR** [department-of-veterans-affairs/va.gov-team#48447]
Abdiel Fernandez, 
I work for Oddball Inc
I'm on team Koala which is part of the lighthouse platform

## Description
I need additional access to AWS services. At the moment, I need access to SSM and ECS but preferebly please provide me the same access as @iriteshp or @kevingin9.

## Background/context 
My team is now owning the maintenance of Kong Api Gateway which is hosted on AWS ECS
---
## Tasks
- [ ] _What things need to happen?_

## Acceptance Criteria 
- [ ] Similar access to the rest of my team members

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by oseasmoran73** [comment]
Please fill out appropriate form https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Coperations%2Cops-access-request&template=aws-access-request.yml&title=AWS+access+for+%5Bindividual%5D

Closing ticket
