### ISSUE TITLE
Design | Profile | Research Recommendations | Review Button Pair Options

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#48441]
## Background

During our recent research sessions we observed that some users were confused by the button options for "saving" and "updating" their information. We want to reevaluate the button pairs in the cancel confirmation modal and the remove modal. Specifically we should look into why we chose "update" over "save."

Detailed findings are [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2022-09-profile-editing-evaluation/findings-summary.md#improve-the-user-experience-for-buttons-in-profile)

## Tasks
- [x] Investigate why we chose "update" and if that is the current standard
- [x] Should we offer more options as choices between Yes or No
- [x] Re-visit "cancel or continue editing" wording
- [x] Remove address or phone number?
- [x] Evaluate button pairs and develop recommendations for alternatives
- [x] Share findings/recommendations with team

## Acceptance Criteria
- [x] New recommendations for button pairs are established

**Comment by andaleliz** [comment]
- Danielle and I reviewed the "update" label vs "save" and agree that "save" is the way to go.
- In the modal that appears when someone hits the "remove" button, I've proposed we update "Cancel" to "No, keep my information" to improve clarity. Waiting on confirmation from Danielle.
- I think all the other buttons are OK as-is.

**Comment by andaleliz** [comment]
Hi @Samara-Strauss, @SKasimow, @ericasauv09 and @cgednalske (for awareness). After reviewing the button pairs with Danielle, we have determined to:
- change `Update` to `Save`. Save is more conventional, and aligns better to the use case of people adding info for the first time 
- In the modal that appears when someone hits the "remove" button, change the `Cancel` label to `No, cancel this change` which aligns with another button pair we have (when a person cancels unsaved changes) and is more clear about what the outcome will be.

I reviewed the button pair for address change messaging, and canceling unsaved changes, and I think those are fine as is.  We didn't see people confused by that.

The sketch files have been updated, and this is ready for FE!

@cgednalske does this button label change from update to save qualify as an "iteration" we should preserve on our iterations page?

**Comment by Samara-Strauss** [comment]
Thank you, @andaleliz!!

**Comment by SKasimow** [comment]
@andaleliz - can you send me the links to the sketch files with changes? thanks!

**Comment by andaleliz** [comment]
@SKasimow for the update > save label change, the changes are across many screens in multiple sections, but here are the links to the main sketch files where the changes can be seen:
- [Personal information](https://sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565)
- [Contact information](https://sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655)
- [Direct deposit](https://sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131)

I think the FE devs will be able to do their task w/out the mock-ups.

For the modal button change, [here is the mock-up](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/YGaqMKL).

**Comment by Samara-Strauss** [comment]
This is great! Thank you!

I didn't go over this with a fine-tooth comb, but I did happen to notice there was one screen in the personal info section that was still using update:

![image](https://user-images.githubusercontent.com/34068740/200335529-b7e5775a-8b9d-4068-81f5-fa4562b8ec29.png)

**Comment by andaleliz** [comment]
Oh good catch! I'll go through again and see if there are any other stray "updates" floating around.
