### ISSUE TITLE
Various discrepancies between Huron and SharePoint FSR Submissions

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#48449]
## Issue Description
Ashlie provided a list of various discrepancies between SharePoint submissions and what they've received on Huron. 

---
## Tasks
- [ ] Use provided IDs to determine possible cause
- [ ] Communicate with necessary teams to see source
- [ ] Draft document response about discrepancy reasoning's

## Acceptance Criteria
- [ ] Response about submission discrepancies has been provided to Huron
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
