### ISSUE TITLE
(spike) Supplemental Claims | Logging and monitoring

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#48453]
## Value Statement
**_As a_** Veteran
**_I want to_** understand the cause of errors that occur during my claim journey
**_So that_** I can get a quick resolution to my problem. 

---
## Background Context
This tickets covers logging and monitoring needs for the Supplemental Claim form.

## Acceptance Criteria
- [ ] We've defined the use cases for which logging and monitoring need to be in place and list them here.
- [ ] We know how to view our logging and monitoring and have a plan to set that up. 
- [ ] We know how we will communicate / action on issues as they come up in production. 

## Designs and Build Notes
- Add here

## Out of scope
- We may break out separate tickets for the setup work. 

## Tasks
- [ ] Write use cases for logging and monitoring. 
- [ ] List tools we'll need to setup for tracking and monitoring those cases. 
- [ ] Confirm with team/Matt.
- [ ] Write additional stories as needed.
