### ISSUE TITLE
Create swagger spec document for copay notifications endpoint

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#48450]
## Issue Description
Providing a swagger spec for VBS so they have required knowledge for how to integrate with copay notifications endpoint.

---
## Tasks
- [ ] Determine structure (headers, body, response) of endpoint
- [ ] Create swagger document that matches structure

## Acceptance Criteria
- [ ] We can provide swagger doc to VBS to start endpoint integration
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
