### ISSUE TITLE
Remove vets-api UserIdentity class - Issue Research

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#48451]
## Issue Description
[Relevant Slack thread](https://dsva.slack.com/archives/C019S3NSSAD/p1665770026803579)

vets-api user attributes for SSOe logins are currently sourced from both [the ISAM headers](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/saml/user_attributes/ssoe.rb) and a subsequent [MPI call](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/mpi/responses/profile_parser.rb). Originally the Identity team planned to [fully phase out the MPI sourcing of user attributes](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32272), the reasoning being that ISAM also sources the attributes it sends from MPI and vets-api necessarily makes the ISAM call before the MPI call.

However, with the creation of the [Sign-in Service](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Sign-In%20Service#sign-in-service-sis) we now believe that opposite approach, defaulting to the MPI-sourced attributes, is the better approach. SiS only consumes a few key attributes (name, SSN, DOB, etc.) that are required to query MPI, refactoring the SSOe attributes sourcing to match this pattern would bring the two in line and make future maintenance easier.

---
## Tasks
- [x] Investigate extent of UserIdentity class usage in vets-api
- [x] Identify deprecation roadmap/steps
- [x] Write individual issue tickets

## Acceptance Criteria
- [x] Identity team will be ready to proceed with UserIdentity deprecation

**Comment by bramleyjl** [comment]
## UserIdentity Usages
### Authentication
* SiS `UserCreator`: the `UserCreator` that is called at the end of a successful `/callback` uses `UserIdentity` twice: first to manage CSP-passed attributes & call MPI for the full attributes lookup, and again after the MPI calls to be set to the newly created `User`.
* SiS `current_user`: If `@current_user` hasn't been set a new `UserIdentity` is instantiated from user ids stored in the session object and used to create a User that is set to `@current_user`
* SSOe `UserSessionForm`: The `UserIdentity` is created from normalized user attributes in the SSOe SAML payload, then saved to the user to carry the attributes over.

### Other
 * `UserRelationship`: used to query MPI for full attributes
 * `Form1010cg`: used to query MPI for ICN
 * `StatusService` module: used to query MPI for the MPI profile, which is then used to query EMIS for a veteran's service status
 * `MVI.rake`: used to query a user from attributes (raketask)

## User Model Attributes delegated to UserIdentity
```
  delegate :multifactor, to: :identity, allow_nil: true
  delegate :authn_context, to: :identity, allow_nil: true
  delegate :mhv_icn, to: :identity, allow_nil: true
  delegate :idme_uuid, to: :identity, allow_nil: true
  delegate :logingov_uuid, to: :identity, allow_nil: true
  delegate :verified_at, to: :identity, allow_nil: true
  delegate :person_types, to: :identity, allow_nil: true, prefix: true
  delegate :sign_in, to: :identity, allow_nil: true, prefix: true
  delegate :email, to: :identity, allow_nil: true
  delegate :loa3?, to: :identity, allow_nil: true
```

**Comment by bramleyjl** [comment]
After reviewing where and how we use `UserIdentity` I'd say it performs three primary functions in vets-api:
1. It is an object that allows us to more easily query MPI by user attributes (SSN, DOB, first & last names) instead of passing in a cumbersome string or hash of arguments.
2. It is a store of the same identifying user attributes that can be instantiated and used before an actual `User` is. This is useful in the process of authentication where we are managing these attributes but have not authenticated the user yet.
3. It holds the attributes that the User class accesses, uses, and presents to the rest of the application

Most of the motivating reasons for removal are primarily concerning #3, the confusion between it and MPI as the source of truth for User attributes, as well as the differences between SSOe and SiS user attribute sourcing. It makes sense that the `user_identity || mpi_data` sourcing for attributes in the User model should be consolidated to just reference MPI, and the delegated attributes moved over as well.

For #1 & #2 `UserIdentity` is acting as a relatively small hash object with some validations, but I don't see the value in removing the class and replacing it with actual objects. SiS & SSOe will continue to need to handle a few identifying user attributes given to them by the CSP before they query MPI for the full list of attributes (and the authoritative source for the ones they already have), perhaps the best thing to do here is to shrink `UserIdentity` in size and implementation so that it is only handling the SiS shortlist of CSP-provided attributes in the callback authentication process & a few places where there is no authenticated session?

In that case, the proposed issue tickets might look something like this:
1. Move `UserIdentity`-delegated attributes & ids to `MPIData`, completely removing UserIdentity from User attribute sourcing.
2. Update MPI queries using `UserIdentity` to go through the `User` model and call `current_user.identity` where the current user is available. Some queries will continue to instantiate a `UserIdentity` from attributes as they occur outside of authentication.
3. Update SSOe authentication to more closely resemble SiS - use several identifying user attributes from ISAM headers to instantiate a `UserIdentity` & query MPI for the full set of user attributes.
4. Remove unneeded `UserIdentity` attributes.

**Comment by alyssagallion** [comment]
Chatting about on engineering meeting tomorrow and scoping out afterward.

**Comment by bramleyjl** [comment]
Updated Work Order

1. Remove UserIdentity entirely from User attribute sourcing
2. Reduce SSOe flow to use as few attributes as necessary to query MPI (perhaps just ICN)
3. Shrink UserIdentity class to its bare minimum of attributes
4. Reduce UserIdentity usage to just MPI querying & pre-authentication attribute management
