### ISSUE TITLE
Rework secure messaging tool page with new content pattern

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#48464]
## Issue Description

We need to apply our new content pattern to our [VA Secure Messaging](https://www.va.gov/health-care/secure-messaging/) tool page. Currently the health care tool pages are all in react widgets, so this work needs to be done in Word docs rather than in Drupal.

The initial work was completed in a different ticket that contained all the health tool landing pages. We are now separating each page out to better keep track of the work. 

We are also reevaluating the secure messaging page to determine if any of the FAQs should move to the new secure messaging app. 

Once we have final approved content, we need to give it to Public Websites to redo the react widgets. We will send them all the health tool pages at once. 

Here's the work completed in the previous ticket:

Hi @laurwill ! Here is the drafted secure messaging page. I've included a few comments and questions in the Non-Cerner  and Cerner versions of the page. 

**Non Cerner version** 
[VA Secure Messaging Non Cerner Version _AB_7.22.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9266279/VA.Secure.Messaging.Non.Cerner.Version._AB_7.22.docx)
(Note 8/3: I was back in the doc while working on the prescription page and made two small edits this! This is an updated version)

**Cerner version**
[VA Secure Messaging Cerner Version_AB_7.26.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9266277/VA.Secure.Messaging.Cerner.Version_AB_7.26.docx)

## Tasks
- [x] Rework page (Aliyah)
- [ ] Review (Laura)
- [ ] OCTO-DE review (Danielle)
- [ ] Copyedit (Megan)

## Acceptance Criteria
- [ ] Content is ready to go to Public Websites

**Comment by aliyahblackmore** [comment]
Update 10/25: We are pausing on this work as we reach out to another writer!
