### ISSUE TITLE
[FE] Payment info v2: Implement overpayment debt card design changes

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#48468]
## Background
After speaking with the benefits-team-2 we learned that the debts portal only shows the most recent overpayment debts owed at each facility. They have no way of knowing if the user has paid off their debts therefore, they only show the most recent debt owed and do not include additional debts that may exist for that user. Since My VA is showing all debts and aggregating them we need to update our designs and logic to match the debt portal so we are consistent between the two pages for our users. 

We also noticed that the "Manage your VA debt" and "Manage your VA bills" links in the debts and copays cards are not bolded. They should follow the [active link style](https://design.va.gov/storybook/?path=/docs/components-va-link--default#active) and be bolded like the "View your payment history link in the benefit payment cards. See [sketch](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/rb3RzvK) vs screenshot from staging below (user 81) :

![Screen Shot 2022-10-20 at 10 59 04 AM](https://user-images.githubusercontent.com/45603961/196985929-c117b895-ab72-4c6e-b28d-cddfe387debd.png)

## Resources
- [Slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1666200902229529) for reference
- [Updated overpayment debt card design](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/Omwvmqv)
- [FE documentation for overpayment debts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/outstanding-debts-FE-documentation.md#debts-card)

## Tasks
- [x] Update overpayment card so the H2 on the card no longer shows a dollar amount and shows the number of overpayment debts (statements) that a user has on the overpayment debt balances page
- [x] Eliminate the H3 on the card to match designs
- [x] Change "due by" date to "Updated on" date and pull the most recent date that any overpayment debt has been updated on the overpayment debt balances page
- [x] Ensure "Manage your VA bills" and "Manage your VA debt" links are bolded per [designs] (https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/rb3RzvK) (follow [active link style](https://design.va.gov/storybook/?path=/docs/components-va-link--default#active))
- [x] PM to validate in staging with users 1, 11, 39, or 81 

## Acceptance Criteria
- [x] Code matches new design of overpayment debt card
- [x] Overpayment debt data on My VA matches what is shown in the debt portal

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_
- _How can this work be validated?_ log in with test users 1, 11, 39, or 81 and validate functionality and data

**Comment by ericasauv09** [comment]
validated with user 1:![Screen Shot 2022-10-21 at 14.49.12.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/4544459c-be79-4dd7-a0d6-83c52f7edb73)

user 11:
![Screen Shot 2022-10-21 at 14.50.33.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/40c9436d-9f6f-4b6e-99aa-0af3425996f7)

and user 81:![Screen Shot 2022-10-21 at 14.52.50.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/d50c38bb-e2b8-4baf-868f-380c9451cb5c)
