### ISSUE TITLE
[Design] Payment info V2: create alternate design for simplified overpayment debt card

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#48461]
## Background
After speaking with the benefits-team-2 we learned that the debts portal only shows the most recent overpayment debts owed at each facility. They have no way of knowing if the user has paid off their debts therefore, they only show the most recent debt owed and do not include additional debts that may exist for that user. Since My VA is showing all debts and aggregating them we need to update our designs and logic to match the debt portal so we are consistent between the two pages for our users. 

[Slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1666200902229529) for reference

## Tasks
- [x] Update overpayment debt card design and logic to only include most recent debts owed at each facility, and remove the debt amount.
- [x]  Update FE documentation
- [x] Share with team

## Acceptance Criteria
- [x] New design and logic for overpayment debt card is created
