### ISSUE TITLE
Design | Profile | Account Security | Updates to Contact Center Guide

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#48460]
## Background

We recently made updates to the Account Security Alert section of Profile and we need to update all documentation around the alerts and add another section of the contact center guide for the second MPI (Master Person Index) alert.

## Tasks
- [x] Make updates to the current alert documentation and the contact center guide
- [x] Add a new section for the second alert
  

## Acceptance Criteria
- [x] Contact center guide updates and documentation are complete for the Account Security Alert updates

**Comment by ericasauv09** [comment]
@cgednalske let me know if this is ok and covers the work you are doing - Also please add an estimate when you get a chance. Thanks!

**Comment by cgednalske** [comment]
@ericasauv09 this looks great and covers everything 👍  Thanks so much!

**Comment by cgednalske** [comment]
Hi @SKasimow - I added the new Account security alert images and info to this [shared doc](https://docs.google.com/document/d/1tBR0CUVilPDw8dBQt9xDlolVvpNdMxxYRASiNA-yyfY/edit#) so we can confirm everything first like we did for the last contact center guide update. I also updated the verify identity alert. Could you check if any changes or additional details are needed before we add these updates to the full guide doc? Thanks! 🙂

**Comment by SKasimow** [comment]
@cgednalske - I sure will. Will put on my "to-do" list for today 👍

**Comment by SKasimow** [comment]
Looks good @cgednalske! Are you adding to CC guide or should I do that?

**Comment by SKasimow** [comment]
I don't think so...how about you add the updates and I'll fix the TOC and post the updated version to GitHub and reach out to CC (can show you how to do ToC - it's easy once you know it).

**Comment by SKasimow** [comment]
hi - I didn't forget this but didn't manage to get to today; will def check Monday!

**Comment by SKasimow** [comment]
Hi @cgednalske - doc looks good. I updated the name and table to version 5.2.1 (since this was a minor change) and will update Github and CC next.

Version [5.2.1](https://docs.google.com/document/d/1CGkJtItjQAX9yvutpAfHZ65nki9tijgy/edit#heading=h.gjdgxs)

**Comment by SKasimow** [comment]
Closing this and will be opening another ticket to submit to CC.
