### ISSUE TITLE
[FE] Display Error Message when Multiple Appointments BTSSS API Error Encountered

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#48474]
## Description
The BTSSS API will not allow a claim to be filed if the Veteran has multiple appointments for the day for which they want to file a claim.  We need to display an error message to the Veteran if this is encountered.

## Wireframe
UX decision is to show the following general error message when we get a multiple appointments error back from the BTSSS API.
[Wireframe](https://app.abstract.com/projects/ab30c34e-e2f9-4d3e-bb96-3b683b006c24/branches/ac31709b-2855-41d4-a01c-be1c01d7356c/commits/26ba433f99f8b2576e21d58be4616f452ebd3dcc/files/585436fe-2120-45f4-b4f7-fbae01d258d9/layers/9C059432-24E0-4E89-971E-90EFA44BC078?collectionId=57d1d456-eaea-4ad2-9f62-8e2c91ec31ca&collectionLayerId=9421e29d-1565-4e6a-9ae5-0ca507077a80&mode=design)

## Tasks
- [ ] [FE] **Display error when multiple appointments response is received from the BTSSS API**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [x] Read ticket details and verify that ACs are met
- [x] Review code in PR
- [x] Run branch locally
- [x] Check that new and updated translations use new keys
- [x] Check for hardcoded strings

**Comment by loripusey** [comment]
@wullaski closing this, we can validate as part of our QA tickets
