### ISSUE TITLE
Rework the prescription tool page with new content pattern

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#48473]
## Issue Description

We need to apply our new content pattern to our [Refill and track VA prescriptions](https://www.va.gov/health-care/refill-track-prescriptions/) tool page. Currently the health care tool pages are all in react widgets, so this work needs to be done in Word docs rather than in Drupal.

The initial work was completed in a different ticket that contained all the health tool landing pages. We are now separating each page out to better keep track of the work. 

Once we have final approved content, we need to give it to Public Websites to redo the react widgets. We will send them all the health tool pages at once. 

**Non Cerner version**
[Refill and Track Prescriptions Non Cerner Version _AB_8.1.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9270331/Refill.and.Track.Prescriptions.Non.Cerner.Version._AB_8.1.docx)

**Cerner version**
[Refill and Track Prescriptions Cerner Version_AB_8.4.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9270333/Refill.and.Track.Prescriptions.Cerner.Version_AB_8.4.docx)

## Tasks
- [x] Rework page (Aliyah)
- [ ] Review (Laura)
- [ ] OCTO-DE review (Danielle)
- [ ] Copyedit (Megan)

## Acceptance Criteria
- [ ] Content is ready to go to Public Websites

**Comment by aliyahblackmore** [comment]
Going to unassign myself from this for now. This is part of the MHV work that Laura is supporting.

**Comment by mistymg** [comment]
Moved to closed but not actually showing up as closed on board.
