### ISSUE TITLE
Rework lab and test results tool page with new content pattern

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#48471]
## Issue Description

We need to apply our new content pattern to our [View your VA lab and test results online](https://www.va.gov/health-care/view-test-and-lab-results/) tool page. Currently the health care tool pages are all in react widgets, so this work needs to be done in Word docs rather than in Drupal.

The initial work was completed in a different ticket that contained all the health tool landing pages. We are now separating each page out to better keep track of the work. 

Once we have final approved content, we need to give it to Public Websites to redo the react widgets. We will send them all the health tool pages at once. 

Here's the work completed in the previous ticket:

non-Cerner [https://app.zenhub.com/files/133843125/df36dd85-ccf1-44e5-b81f-f6faebcccb1c/download](https://app.zenhub.com/files/133843125/df36dd85-ccf1-44e5-b81f-f6faebcccb1c/download)

Cerner 
[https://app.zenhub.com/files/133843125/64f835c1-0d9f-4839-93dc-2984ca3cd1a4/download](https://app.zenhub.com/files/133843125/64f835c1-0d9f-4839-93dc-2984ca3cd1a4/download)
 
## Tasks
- [ ] Rework page (Katherine)
- [ ] Review (Laura)
- [ ] OCTO-DE review (Danielle)
- [ ] Copyedit (Megan)

## Acceptance Criteria
- [ ] Content is ready to go to Public Websites

**Comment by mistymg** [comment]
Moved to closed but not actually showing up as closed on board.
