### ISSUE TITLE
Design Discovery: Changing contact info on Veteran's profile

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#48475]
## Issue Description
Allowing Veterans to update their contact information as part of their VA profile instead of just for the FSR submission that does not persist. 

## Background 
As part of #48384, the design team questioned why the experience does not transfer to the Veteran's profile. 
Currently on FSR: 
![Screen Shot 2022-10-18 at 11.04.43 AM.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/5cbb2eb1-150d-498e-af2a-8b19b06f6f60)

Any reason not to change Personal information section to something like this? ([screenshot from Supplemental Claims](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/p/665AA990-66CC-4CD9-9B1D-62D737DA2223/canvas))
![Screen Shot 2022-10-18 at 11.06.02 AM.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/dd75e633-ab9d-466e-80f2-b712515fa28b)

---
## Tasks
- [x] Investigate feasibility of implementing the ability for the Veteran to change their contact info on the portal. 

## Acceptance Criteria
- [x] Identify and document a path forward for implementation (first step; connect with Supplemental Claims team) 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
@mgleo @Dr-Pongo  these two seem to be related. #46669 and this one #48475. Do we need both?

**Comment by mgleo** [comment]
This ticket is a more of a discovery ticket to find out if a design update (and eventually dev update) is possible. 46669 is a dev ticket. So they're tickets for different things.

**Comment by mgleo** [comment]
Current way the form works according to Scott: **"...we initially auto populate contact information using vet 360 (VA Profile API) and if they make changes it will only impact the form data"**

FSR will need to **WRITE** to VA Profile API in order to allow the user to make an update that will impact all of their profile information. 

Liz (Profile team): **"The VA Profile API updates the “Master Person Index” (MPI), which many systems pull from.
VA systems that use MPI, and the VA Profile API will be updated if someone updates their info in the VA.gov profile."**

Dev team will need time to investigate how to write to VA Profile API.
