### ISSUE TITLE
Continued discovery for the streamlined waiver

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#48482]
## Issue Description
Product and Design both need time to understand the decision tree and spreadsheet that VHA has provided. It is a complicated process that has major implications on the user experience. Before the design team can move forward with the User Scenarios/Flow for the experience certain questions need to be answered. 

---
## Tasks
- [x] Meet with Mike Dewey to better understand the discrepancies between the decision tree and spreadsheet
- [x] Gain a better understanding of the equation used on the spreadsheet and the information needed for the decision to be made.
- [x] Determine where that information can be collected across the portal experience. Is there any backend development needed to collect this information?
- [x] Identify outstanding questions and gain a clearer understanding of next steps and requirements to move forward. 

## Acceptance Criteria
- [x] Product and design have a clear sense of what is needed to unblock the User Scenarios/Flow design work.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mgleo** [comment]
Will create user personas based on how we understand the Streamlined Waiver.
