### ISSUE TITLE
FE | Profile | Update "Not in MPI" Error Alert 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#48501]
## Background

While reviewing the security alerts in staging and comparing to our mocks, we found that the alert we are showing when we can't match records in MPI needs to be updated. 

## Tasks
- [x] Update the alert used for when users sign in and MPI can not match the records to these designs:
[Desktop](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/a/AxG3GRz) and [Mobile](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/a/jgY3M2G)
- [x] Conduct Unit tests 
- [x] Run E2E tests covering current code and regression
- [x] Notify PM if this needs to be deployed to Staging behind feature flag
  

## Acceptance Criteria
- [x] Complete all unit testing
- [x] End-to-end tests showing 0 violations
- [x] All axe checks pass
- [x] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [ ] Confirm PM has opened a new ticket to deploy changes to Production using feature flag, if needed

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)? PM or Design
- How can this work be validated? Testing in staging
- What updates need to be made (e.g. product outline, use cases, contact center guide)
     - Sketch files
     - User flows
     - Contact Center guide
     - Check product outline

## Associated Tickets
- #47350

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by adamwhitlock1** [comment]
@SKasimow this is ready to validate

**Comment by cgednalske** [comment]
@SKasimow I don't think so because I initially was only to get information about this from Adam. I couldn't recreate it myself... And looks like our [Profile staging users & test cases doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-profile.md) says "test locally."

**Comment by SKasimow** [comment]
@adamwhitlock1 - can you take a screenshot locally? Doesn't seem like there is a way for me to validate

**Comment by adamwhitlock1** [comment]
Here are some screenshots on how it looks now.

![Screen Shot 2022-11-18 at 11.43.02 AM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/42386cfe-4033-4e38-bb53-f7b7edb82d80)

![Screen Shot 2022-11-18 at 11.42.10 AM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/ddd19c45-b8b5-4042-bf19-8f329232c3c6)

Spacing of the icon / content is slightly different, but mostly just because of the way the design system component renders alerts by default, otherwise should be up to date with new content

**Comment by SKasimow** [comment]
Thanks...looks good to me. Closing....
