### ISSUE TITLE
[eFSR] Utility Bills Enhancements

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#48507]
## Issue Description
Add Checklist to input list and mini summary options for Utility Bills. 

- [Utility bills (original mockup)](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145111152/specification/sitemap?mode=i)

Checklist Options (Exclude Other):
![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/b9dc4f53-9f47-4ec9-821a-38ee0b135aee)

---
## Tasks
- [ ] Add the following pages:
  - [ ] Checkbox page 
  - [ ] Input list page
  - [ ] Mini Summary page
  - [ ] New Utility input
- [ ] Show list in final review page
- [ ] Update efsr specific e2e testing
  - [ ] Include item removal and addition

## Acceptance Criteria
- [ ] Page matches design and functionality
- [ ] All new and existing tests are passing
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
