### ISSUE TITLE
[eFSR] Other Living Expenses Enhancement

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#48510]
## Issue Description
Add Checklist to input list and mini summary options for other living expenses. 

~~[Other living expenses (old design)](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/146358669/specification/sitemap?mode=i)~~

[Mural for mini summary design update](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1671734127581/dc254b12e788570c946af60bc55338b0045aea03?invited=true&sender=87471762-a55a-4514-88d1-4cb4b90f7fb6)

**NOTE:** Be sure to use Mural for up to date mocks, the following screenshots are just for quick reference.
<details><summary>Checkbox Page (click to expand):</summary>

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/1fe5cb6c-0f39-45a5-aea3-b7693de2f107)
</details>

<details><summary>Input List Page (click to expand):</summary>

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/b3e832be-0719-46fb-b94c-dbf465197742)
</details>

<details><summary>Mini Summary Page (click to expand):</summary>

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/cedc2247-2e63-4df6-a738-b98cd2d7e936)
</details>

<details><summary>New Asset Page (click to expand):</summary>

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/637fc48f-d8fa-4458-b4c7-fff726b20607)
</details>

---
## Tasks
- [x] Add the following pages:
  - [x] Checkbox page 
  - [x] Input list page
  - [x] Mini Summary page
  - [x] New Expense inputs
- [ ] Show list in final review page
- [ ] Update efsr specific e2e testing
  - [ ] Include item removal and addition

## Acceptance Criteria
- [ ] Page matches design and functionality
- [ ] All new and existing tests are passing
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
Updated post midpoint review with new designs!

**Comment by denisecoveyduc** [comment]
March 24 - pulled into Sprint 95 as unplanned work since utility bill enhancements stood no chance against @Dr-Pongo 💪

**Comment by Dr-Pongo** [comment]
Got clarification on data, ticket is ready to jam again!

**Comment by Dr-Pongo** [comment]
This became unblocked mid sprint and got pushed back. Work is 80-90% complete and I should be able to wrap (hopefully) early in sprint 97!

**Comment by HeatherRienks** [comment]
Great- thanks for the update!
