### ISSUE TITLE
[FE] Remove marriage date validation & update content

### ISSUE THREAD

**Issue by nicko-amida** [department-of-veterans-affairs/va.gov-team#48524]
## Description

The marriage date validation has been removed from the household section per #41904. The validation is replaced with an error message that prompts the applicant to check the date, but does not prevent them from continuing through the application.

## Tasks

- [ ] Remove "required" validation from marriage date field
- [ ] Update error state with the new content

## Mockups

- [Link to the spouse's information page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/PG4nmov)
- Screenshots:
![image.png](https://images.zenhubusercontent.com/606dcfcdf37170580d2e39f0/59739524-bf5d-4ae4-93c0-7f28ee082e3a)

## Acceptance Criteria

- [ ] Current marriage date error state logic remains the same
- [ ] Marriage date no longer a required field

**Comment by longmd** [comment]
@nicko-amida , we will need to do some research on this. I'm not sure we can mark the field as invalid, but still allow them to continue with the application.

**Comment by longmd** [comment]
@nicko-amida , you can validate on a non-required field, but it will block the application from continuing until the field is valid. Can't have our cake and eat it, too. 😜
