### ISSUE TITLE
BE | MyVA | Feature Flag Turning Off

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#48539]
## Background
The `profile_user_claims` feature flag is being turned off intermittently in staging.  Other teams have noticed this issue with other flags.  The team has also noticed that the flag is is missing from the list, but then reappears a short time later.

We're not seeing these issues in production.

The following support ticket was opened - https://dsva.slack.com/archives/CBU0KDSB1/p1666112449634839

## Tasks
- [ ] Do some research to find out if there are any logs related to flag status updates.
- [ ] Query the `feature_toggle_events` table the next time  the flag is turned off.
- [ ] Report any findings to the team.

**Comment by tpharrison** [comment]
It looks like this issue has been resolved by the Platform team - https://dsva.slack.com/archives/CBU0KDSB1/p1666304911369149?thread_ts=1666274946.055029&cid=CBU0KDSB1.

Updating to 1 point and closing.
