### ISSUE TITLE
Rework Higher-Level Reviews static page to match VA.gov style

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#48533]
## Issue Description

We are reworking the decision reviews section to make sure the static pages match the voice and style of VA.gov. These pages were originally put on the site without much collaboration from the Sitewide Content and IA team. We need to make sure it meets our plain language standards and follows the same patterns as our other benefit detail pages.

This ticket is for the [Higher-Level Reviews](https://www.va.gov/decision-reviews/higher-level-review/) page. 

## Tasks
- [ ] Rework page (Katherine)
- [ ] Review (Laura)
- [ ] Post in ticket # for Beth to review (Laura) 

## Acceptance Criteria
- [ ] Page is ready for OCTO-DE review

**Comment by katherine-fung** [comment]
I started work on this. 

Preview: http://preview-prod.vfs.va.gov/preview?nodeId=3003

**Comment by katherine-fung** [comment]
Hi @laurwill, 

This page is ready for your review: http://preview-prod.vfs.va.gov/preview?nodeId=3003 

I made re-organized some of the information, and made other changes throughout the page to align it with the style of the [Supplemental Claims page](https://www.va.gov/decision-reviews/supplemental-claim/).

**Comment by laurwill** [comment]
Thanks @katherine-fung ! 

I'm actually going to pull in @aprocik1 to review this page — A, this is the second of 3 decision reviews pages we're updating to follow a new style/approach. I think a good first step would be to go into the Drupal revision history for the Supplemental Claims page and compare the previously published version to Katherine's recent updates, or do a quick sync together so you have context for these changes.

Then after you've reviewed, you and I can talk through any questions you have or edits you suggest. Let me know if you have questions about this as you get started!

**Comment by aprocik1** [comment]
@katherine-fung and @laurwill: I updated the Higher-Level Reviews page to match the style of the Supplement Claims page. Here's the [preview](http://preview-prod.vfs.va.gov/preview?nodeId=3003). Any and all feedback welcome.

Note: The preview contains unpublished edits from Danielle and Katherine. Before sharing the preview with partners, Laura will connect with Danielle to ensure we can move forward with her edits. Thanks!

**Comment by aprocik1** [comment]
I moved this ticket to blocked because we're waiting on Danielle's approval to publish her draft edits or share them with stakeholders. Here's the Slack thread for reference: https://dsva.slack.com/archives/C03MP8MEPCN/p1695840530748999

**Comment by aprocik1** [comment]
Update: Danielle made another round of health care related updates to this page. She reverted to the version of this page before the updates on this ticket were made. After this page is published with Danielle's edits, we should revert it to Chelsea's draft on 1/17/2024 at 2:55 pm ET. Then we should reincorporate Danielle's edits and get stakeholder approval.

This ticket is still blocked, because the page hasn't been published with Danielle's edits.

**Comment by aprocik1** [comment]
Update: This ticket is no longer blocked. The HLR page has been published with Danielle's edits. There aren't any remaining draft edits in Drupal. I'm moving this ticket to in progress.

@katherine-fung and I met today to re-start this work. She's going to draft an updated HLR page that matches content patterns on the Board Appeals and Supplement Claims pages. I started this work in October 2023 in this [SharePoint document](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/EefzQeuuBMhNtgEOKjthw54BmnQiJn3Q_5dPJttQpPdXrA?e=dcUqOI).

**Comment by katherine-fung** [comment]
Hi @aprocik1, 

Here's the preview of the HLR static page for your review: http://preview-prod.vfs.va.gov/preview?nodeId=3003

Thanks!

**Comment by aprocik1** [comment]
Update: @bethpotts is going review this page. Here's the Drupal preview: http://preview-prod.vfs.va.gov/preview?nodeId=3003
