### ISSUE TITLE
[Discovery] Breaking vets-api into micro-services

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#48538]
## Description

Relevant Ticket: #3853 

In order for us to follow bulkhead pattern effectively, we need to break vets-api into micro-services. Given that work itself is most likely will need to be an Epic, purpose of this ticket is to do research on effort involved

## Tasks
- [ ] Research effort involved (more details)

## Acceptance Criteria
- [ ] Tickets spun up (if applicable)
- [ ] Information documented (if applicable)

**Comment by npeterson54** [comment]
Removing tech team 3 label, we won't be working on it.

**Comment by rjain21** [comment]
Closing as not a priority right now. If it does become a priority in the future, we shall create another ticket. The ticket is over 2 years old!
