### ISSUE TITLE
[EKS] Update EKS for vets-api to create separate deployments

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#48542]
## Description
If we wish to move towards bulkhead pattern, some work will need to be done in EKS

## Tasks
- [ ] Update deployment per location
  - [ ] TBD (update list with external-services/location/microservices)
- [ ] Update hpa per location
  - [ ] TBD (update list with external-services/location/microservices)
- [ ] Update service per location
  - [ ] TBD (update list with external-services/location/microservices)
- [ ] Create ingressroute per location pointing to service
  - [ ] TBD (update list with external-services/location/microservices)

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

## How to configure this issue
- [ ] _Attach a Milestone_
- [ ] _Story points_
- [ ] _Sprint assigned if pulling into sprint_
- [ ] _Epic assigned_
- [ ] _Team label assigned_

Relevant Ticket: #3853

## Acceptance Criteria
- [ ] TBD

**Comment by oseasmoran73** [comment]
Closing in favor of #49837
