### ISSUE TITLE
[Development] Create VSA End-Point for 526 Claims that Uses MVI

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#4855]
## User Story:
As a veteran, I need to be able create a profile so I can file a new, first time claim for a disability compensation.

Once we have completed the MVI integration testing (#4848, #2034) we will be able to actually remove the gating and add some back end code to create an endpoint for our FE developers.  The back-end endpoint will do the dirty work of integrating with MVI and will allow us to fully remove the gating question.  

## Tasks
- [x] Determine "business logic" for the end-point.  Will it have to do anything special or will it simply have to hit the MVI endpoint without a care in the world about whether it's original or 1000th claim. - calls to `GET /v0/in_progress_forms/{id}` will trigger "proxy add" => `mvi add person` calls if form id is "21-526EZ" and user is missing participant id
- [x] Code it up
- [x] Test it, provide FE info on how to use your endpoint - not a new endpoint, FE will have to remove gating an check for error thrown for edge case (`ValidationErrors, 'No birls_id while participant_id present'`)

## Acceptance Criteria:
- [x] FE engineer has an endpoint to use - see above

## Configuration
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by SMLuthi** [comment]
```  def mvi_add_person
    search_response = MVI::OrchSearchService.new.find_profile(user)
    if search_response.ok?
      @mvi_response = search_response
      add_response = mvi_service.add_person(user)
      clear_cache if add_response.ok?
    else
      add_response = MVI::Responses::AddPersonResponse.with_failed_orch_search(
        search_response.status, search_response.error
      )
    end
    add_response
  end

private

  def clear_cache
    Mvi.delete(user.uuid)
    @mvi_response = nil
  end
```

**Comment by SMLuthi** [comment]
Heres some notes for the `in_progress_forms_controller.rb` changes

```
    before_action :proxy_add, only: :show

  private

  def proxy_add
    # Check if user has these identifiers. user.birls_id, user.participant_id
    # make the add call if both are missing, or if participant id is missing
    # But if birls_id is missing but p_id exists, thats a fail case

    # to run the actual user.mvi_add_person
  end
```
