### ISSUE TITLE
Investigation: Keycloak UI Availability randomly spikes about once per day

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#48565]
## Description
@td-usds is wondering why this is spiking every day and would like us to investigate
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ]  An explanation is given as to why the spikes happen

## How to configure this issue
- [ ] _Attach a Milestone_
- [ ] _Story points_
- [ ] _Sprint assigned if pulling into sprint_
- [ ] _Epic assigned_
- [ ] _Team label assigned_

**Comment by td-usds** [comment]
@kylesoskin postulated that it's probably related to resource constraints in the dev cluster (that being said, I am seeing this in the utility cluster as well, e.g. https://dsva.slack.com/archives/C02GQ27HXQW/p1666053658128839, https://dsva.slack.com/archives/C02GQ27HXQW/p1665826196055489, ...)

**Comment by npeterson54** [comment]
Looks like we have an answer
