### ISSUE TITLE
[Development] Use New 526 Claims End-Point

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#4856]
## User Story:
As a veteran, I need to be able create a profile so I can file a new, first time claim for a disability compensation.

Once we have completed the new endpoint which utilizes MVI (#4855) we will be able to actually remove the gating on the FE and avoid asking about having any previous claims.

## Tasks
- [ ] Talk to Silvio and make sure you understand the end-point.  Make sure he documents something :)
- [ ] Modify the FE code to call the new endpoint
- [ ] Modify the FE to remove the gating
- [ ] Test it

## Acceptance Criteria:
- [ ] Gating is removed
- [ ] We have a new end-point being used

## Configuration
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by luke-gcio** [comment]
OBE - captured in #6217.
