### ISSUE TITLE
Adding Novavax booster content to 2 COVID pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#48567]
## Issue Description

Now that Novavax has been approved for boosters in some cases we need to update content on the main [COVID-19 vaccines at VA](https://www.va.gov/health-care/covid-19-vaccine/) page and the [COVID-19 booster shots](https://www.va.gov/health-care/covid-19-vaccine/booster-shots-and-additional-doses/) page. 

## Tasks
- [ ] Add new content to pages (Laura)
- [ ] Copyedit (Megan)
- [ ] Send to stakeholder for approval (Laura)
- [ ] Final copyedit (Megan)
- [ ] Publish (Megan)

## Acceptance Criteria
- [ ] New Novavax booster content is on the live site

**Comment by laurwill** [comment]
Hey @megzehn , these are ready for copyedit:
- Main vax page (updates in blue box only): http://preview-prod.vfs.va.gov/preview?nodeId=11463
- Booster page (updates in When to get your booster): http://preview-prod.vfs.va.gov/preview?nodeId=34054

**Comment by megzehn** [comment]
Thanks, @laurwill! These are both copyedited.
