### ISSUE TITLE
Design | Profile | Audit Alerts for Consistency

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#48566]
## Background

There were some variances noted recently in the Profile alerts that don't seem to match recent design and/or content guidance. For example, "please" is used in a few places, though this is something we've been asked to avoid. There are also a few different versions of similar instructions, such as "please try again later" and "please refresh this page or try again later" vs. "please check back soon." Sometimes we say "something went wrong" and sometimes we don't.

This work will be to conduct an audit to look at the alerts and update the language as needed. Design should leverage the [style guide guidance ](https://design.va.gov/content-style-guide/) to evaluate messages, and work with FE to: 
- note which alerts or portions of alerts can be made repeatable and used in multiple places.
- identify any alerts that might be on production that are not currently in the Sketch files

## Tasks

- [x] Review the alerts currently in use and identify any discrepancies. It'll be best to start with Sketch files for each section of profile since they should match production; there is a possibility of some stray alerts in production that aren't in the Sketch files. FE can help with that.
- [ ] ~~Review any changes with content team (Thus office hours) and/or design as needed for any approvals~~
- [x] Share findings with PM and PO (scheduled for 10/2)
- [ ] ~~Update sketch files, use cases as needed. Note that use cases don't need to be updated if the only thing that changed was copy~~
- [ ] ~~Work with PM to update contact center guide (in the past, design provides screenshots and PM handles other updates, publishing, etc)~~
- [ ] ~~Let PM know any changes needed in production~~

## Acceptance Criteria
- [x] Review completed
- [x] we're ready to break down the work into new FE and design tickets 

## Validation
-  Design or PM can review any work

## Associated Tickets
- #47350

**Comment by SKasimow** [comment]
Hi - was just thinking this might need to be broken up into multiple tickets. Once we pull this in for grooming, lmk if it is too big for a single ticket and I will break-up into separate tickets for discovery and updates.

**Comment by andaleliz** [comment]
@Samara-Strauss I've assigned this to myself - looks like it was something Christina was slated to work on. Not sure if you are aware of this ticket, flagging it in case you want it put it in an upcoming sprint.

**Comment by Samara-Strauss** [comment]
Thanks, Liz!

**Comment by mtcA6** [comment]
@andaleliz is this something that our new joiner could work on next sprint? this feels like it would help someone new work through a wide range of pages to check for consistency. what are your thoughts? 
CC: @BerniXiongA6

**Comment by andaleliz** [comment]
I [posted a question in #sitewide-content-ia](https://dsva.slack.com/archives/C01K37HRUAH/p1683645576097369) to see if the style guide has accurate recommendations about what messages should say.  I think it's out of date, so that will make this work a little bit trickier.

**Comment by mtcA6** [comment]
Style guide is about to be updated, they're meeting 5/18/23, @andaleliz is going to ask during their office hours how long it might be before we see the output from their meeting/review for their proposed changes to alerts.

**Comment by andaleliz** [comment]
Danielle said she hoped they'd have guidance published within the next 6 weeks, so sprint 12 or 13 feels like a good call.

**Comment by pamela-drouin** [comment]
Started working on this in here (very early stages): https://docs.google.com/spreadsheets/d/1c07vM_RSrCdCBMfyYY8JY33mXM4ZVRT_WCBVv5vqazs/edit#gid=0

**Comment by pamela-drouin** [comment]
Wound up moving to Sketch to do the inventory/audit, though I may pick up the spreadsheet again depending on how the auditing goes.

Sketch page links
- [inventory](https://www.sketch.com/s/31fad8ed-d754-4b12-9185-95bc5a7d1d1f)
- [audit](https://www.sketch.com/s/31fad8ed-d754-4b12-9185-95bc5a7d1d1f/p/47AAC84A-7F48-41F1-9632-94EE978DEA50/canvas)

**Comment by pamela-drouin** [comment]
Met with @laurwill at content office hours today to share the alerts audit. Here are my notes from that meeting:

CAIA has started the process of collaborating with teams to update the error message section of the style guide. It’s not ready to be re-published, they are still working on getting more examples and additional tips. In general, the style guide is helpful, but Laura shared more of the updated guidance here in office hours.

Content recommendations:
- Move away from `Please` = remove unneeded word (“We’re working to fix this, check back later.”)
- Move away from generic messages -- instead of `Please provide a response`, instead, repeat what’s being asked: `Enter a 9 digit number` 
- Be *even* more specific -- Instead of `Our forms can only accept a-z, 0-9` , adjust it to say more directly what the user can enter in this field: `Enter letters and numbers only or letters, numbers, and dashes only`
- Look into outlier alerts that could be more specific as well, such as Fraud alert. It could be good to talk about in more detail so it is more accurately describing on the back end.

She suggested bringing the updated audit to another content office hours to identify the highest impact types of changes we see needing to make. Because the size of the audit is a manageable size, it will be easy to do together. 

My next steps are to:
- Take advice above and make edits
- Bring to office hours again to narrow down to most impactful changes to implement
- Implement!

**Comment by pamela-drouin** [comment]
A question I have for content office hours is whether there is a preferred way of asking someone to do something again.

Some variations we have in Profile alert messages:
- Refresh this page or try again later
- Try again later
- Check back later

**Comment by mtcA6** [comment]
@pamela-drouin is this one still blocked?

**Comment by pamela-drouin** [comment]
@mtcA6 oh yes -- thanks for the reminder. I need to message CAIA. Will do that today!

**Comment by mtcA6** [comment]
@pamela-drouin how do we unblock this ticket? Would it be helpful if I setup an hour for us to break this down into a series of tickets to begin working through?

**Comment by pamela-drouin** [comment]
@mtcA6 I think breaking down the work into a series of tickets is the next best step!

**Comment by mtcA6** [comment]
I'm going to close this ticket, I updated the acceptance criteria and crossed off some of the tasks since those more appropriately belong in our next tickets!  We'll figure those out on 10/2 during out call to review
