### ISSUE TITLE
Update NCA Scheduling Office hours on Schedule a burial page-HOLD TO PUBLISH UNTIL 11/7

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#48579]
## Issue Description

The National Cemetery Scheduling office's hours are changing as of November 7, 2022. We need to make updates to the [Schedule a burial for a Veteran or family member](https://www.va.gov/burials-memorials/schedule-a-burial/) page to reflect this change. 

Stakeholder Lisa Hollenbeck provided suggested content to update the paragraph below step 3 of the subway map. We'll need to review and edit the content for plain language and for it to match VA.gov style. 

Note that these hours don't change until November 7, so we should hold to publish until then.

Suggested content to add:

The National Cemetery Scheduling Office is open Monday - Friday from 8 a.m. to 7:30 p.m. ET and Saturday from 9 a.m. to 5:30 am ET. The Scheduling Office is closed on Sundays in addition to the Fourth of July, Memorial Day, Labor Day, Thanksgiving Day, Christmas Day, and New Year's Day.

Interments at national cemeteries are conducted Monday thru Friday. When a federal holiday falls on a Monday or Friday, cemeteries will open for interments for one day over the holiday weekend as a service to Veterans and their families. The Scheduling Office will have the most current schedule of available interment times for each cemetery.

## Tasks
- [x] Rewrite content in VA.gov style and add to Drupal
- [x] Review (Laura)
- [x] Send to stakeholder for review 
- [x] Copy edit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] New content with revised hours is on live page

**Comment by aliyahblackmore** [comment]
Hi Laura - thanks for the temp check sync earlier! 

10/25 update to have a record of this work moving along: 

We're still confirming which version I should work from in Drupal to make these more immediate changes (as there are a series of drafted changes from 1/25/22 to 1/26/22). As discussed, I'll make the following changes to the page and we'll wait to hear back from Beth on any other changes, as well as review the previous draft changes. 

1. The information about hours and burial schedules will be moved from the paragraph after the process list (step 3), as this information applies to those who do **and** do not have the pre-need decision letter.  
2. I'll include the hours after the telephone numbers in the headers "If you have a pre-need decision letter that confirms eligibility" and "If you don’t have a pre-need decision letter." 
3. The information regarding burials will be placed in a separate H2 titled "When can I schedule a burial?" 
4. "closed on Sundays..." was not included, as we list the hours that they are open.

**Comment by laurwill** [comment]
Thanks Aliyah! I like how you organized this — including the phone number multiple times feels appropriate here because of the structure of the page. In the future, we could probably restructure to streamline things, but since we're doing minimal updates now, I think what you have works. 

I don't think we need to repeat the holiday closures everywhere — one note is enough, and I don't think people would expect the office to be open on those major holidays.

And thanks for calling out that strange "prepare" line. I took that sentence out — the first 2 steps are about gathering the info you need, so I don't think we need to repeat that you need to gather that info. 

@megzehn , since we made some more substantial updates, could you copyedit only the revisions before we send to stakeholders? http://preview-prod.vfs.va.gov/preview?nodeId=861

**Comment by megzehn** [comment]
Thanks, @laurwill and @aliyahblackmore! 

I reviewed the changes and made some tweaks that we talked about on standup. It's still in drafts, but it has been copy edited.

**Comment by laurwill** [comment]
Hi @megzehn ,
We now have changes to 4 pages ready for you to copyedit and prepub. Please hold to publish on Monday morning, 11/7, when the hours are slated to change.

Schedule a burial page: http://preview-prod.vfs.va.gov/preview?nodeId=861 
- Might be helpful to do compare revisions for changes we made here, we're not trying to open up the entire page, just make the changes needed immediately related to office hours. Randi's on the email thread for this if you have questions!

3 related pages with change to cemetery office hours only:
- Pre-need eligibility (2 times on page): http://preview-prod.vfs.va.gov/preview?nodeId=862 
- After you apply for eligibility (2 times on page): http://preview-prod.vfs.va.gov/preview?nodeId=863 
- Helpful VA phone numbers: http://preview-prod.vfs.va.gov/preview?nodeId=8427 

Thank you!

**Comment by megzehn** [comment]
@RLHecht These pages have all been reviewed and they are ready to go live on Monday a.m.!

**Comment by RLHecht** [comment]
These are published! Moving to validate.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
