### ISSUE TITLE
Add "Forms" Filter to Medalia Dashboard in DOMO

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#48582]
## Issue Description
_The new Forms team on VA.gov want to view survey feedback data for their products._

---
## Tasks
- [x] _Add a `Forms` filter to the Medallia Dashboard in DOMO_

## Acceptance Criteria
- [x] _`Forms` is a filter in the Medallia DOMO Dashboard_
- [x] _Filtering by `Forms` displays only forms related data_
- [x] _The Forms team PM is told this is live_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
