### ISSUE TITLE
[EPIC] MHV to VA.gov: MR: Immunizations: Gather requirements

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#48595]
**Purpose of this epic:**
To gather and centralize requirements related to the data fields for Immunizations that need to be represented on VA.gov, UX design strategy that can be articulated, and any feedback from SMEs or other stakeholders that needs to be defined.

**Process:**
- [x] Create a Immunizations brief that describes: required data fields, Use cases, UX considerations, Questions to answer, and any additional notes that might be helpful @rbsingleton and ByLight designer
- [x] Review brief with @jonathanjnelson, identify any questions to be answered, resolve any confusion or errors

**Deliverables**
- [x] [Immunizations brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records/data-domains/immunizations/immunizations-brief.md)
