### ISSUE TITLE
KM Article Audit and Update

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#48609]
## Issue Description
_As part of our VEO KM article audit, we will be making regular updates to KMs. Our goal for this sprint is to review and update at least 1 KM._

---
## Tasks
- [ ] _Review and update at least 1 KM_

## Acceptance Criteria
- [ ] _At least 1 KM is updated_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by starlow00** [comment]
For this sprint, working on KM 5889—ID.me Resources, Member Support, and Response

**Comment by starlow00** [comment]
For sprint 14, on schedule after edits to large KM (5889). Breaking into multiple future KMs, but keeping basics for this sprint

**Comment by Kimberley2019** [comment]
Meeting with Marlee Gilbert from VEO team next week to review and provide feedback on the KM article that Steven has created thus far.

**Comment by starlow00** [comment]
The meeting with Marlee went well. She approved of the direction I'm taking with the document audit. Preparing to present the project to the larger VEO group on 12/8.

**Comment by starlow00** [comment]
On track for Sprint: Dec 7 - Dec 20, 2022 with KM 5445 - VA.gov Tech Support—Confirmation Email

NOTE: Going forward, KMs will be broken down into individual tickets. Closing this for archival purposes.

**Comment by starlow00** [comment]
Audited KM 5445 VA.gov Tech Support—Confirmation Email for spring ending 12/20.

**Comment by starlow00** [comment]
Updating- On schedule for Sprint 18, title TBA

**Comment by starlow00** [comment]
For Sprint 18, KM 5446 VA.gov Tech Support—Reset Password, Choose Login Service. 
Audit is currently in progress.

**Comment by starlow00** [comment]
Moving to next KM for current sprint, GI Bill field

**Comment by ATMiddleton** [comment]
@starlow00 will create a template for individual KM Article Audits subsequent to collaboration with VEO team.
