### ISSUE TITLE
VBMS Letters Data Issue

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#48606]
## Issue Description
October 21, 2022 we received notice from our stakeholders that there was a potential data breach on one of the VBMS letter that were downloaded on the debt portal. While the case is being investigated we have turned the feature off. 

---
## Tasks
- [ ] Toggle VBMS Letter download off while incident is being investigated
- [ ]  Upon stakeholder approve, Toggle VBMS Letter download back on 

## Acceptance Criteria
- [ ] Issue has been resolved and feature has been turned back on
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
Stakeholder have decided not to leverage VBMS Letters going forward and therefore this capability will not be turned back on. Alternative solutions are being explored.
