### ISSUE TITLE
Design Discovery for FSR Progress Indicator Bar

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#48607]
## Issue Description
FSR progress indicator is not that useful for our users and does not clearly identify how many additional pages there are remaining for them to complete

![image.png](https://images.zenhubusercontent.com/5f7f60ca14e26c658f77b9f5/325c6548-a104-4261-a6aa-b916144e30b0)

---
## Tasks
- [ ] Design discovery to identify more useful or different approaches for the progress indicator

## Acceptance Criteria
- [ ] Design has thoughts or recommendations on how to move forward either with additional discovery or experience changes.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
