### ISSUE TITLE
KM Article Audit and Update

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#48608]
## Issue Description
_As part of our VEO KM article audit, we will be making regular updates to KMs. Our goal for this sprint is to review and update at least 1 KM._

---
## Tasks
- [x] _Review and update at least 1 KM_

## Acceptance Criteria
- [x] _At least 1 KM is updated_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
