### ISSUE TITLE
Staging Review [Authenticated Experience My VA - Payment Info V2]

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#48603]
# NOTE
This template is being deprecated. If your kickoff meeting took place after May 26, 2022, you should be following the guidance specified in the Collaboration Cycle Rquest per the [May 26, 2022 change history post](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Change-history.1846870032.html) instead. If you are unsure if this applies to you, please reach out to the Governance Team on the vfs-platform-support Slack channel.

# Steps to complete Staging Review

## Before meeting

**VFS Product Manager**
- [x]   Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees).
- [x]   Notify the Collaboration Cycle team of this ticket and scheduled date/time in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).
- [x]  Add artifacts listed below to the ticket at least 4 days before scheduled meeting.
- [x]  Ensure you've provided staging access information for the tool or feature. (Don't put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.)
- [ ]  If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the experimental-design label and schedule a meeting with DSC to present the research findings.
- [ ]  Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory)

 **Platform**
 
- [x] Add the Platform reviewers to scheduled meeting
- [ ] Add Zoom information to scheduled meeting
- [ ] Create feedback tickets and link them to the Staging Review epic 

## After meeting

**VFS** 
- [ ] Respond to Platform feedback tickets.
- [ ] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.
- [ ] Update Staging Review ticket with the product’s launch date after it has gone live.
- [ ] Close Staging Review ticket when the review is complete and the product has launched.
- [ ] Communicate any and all known Accessibility issues that are not addressed prior to launch to the VA 508 Office via [Audit Request](https://depo-platform-documentation.scrollhelp.site/developer-docs/Instructions-for-VA-508-Office-document-review.1857913061.html#HowtorequestsupportfromtheVA508Office-AuditRequest). 

**Platform**

- [ ] [Update Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts

Provide links or documents for the following: 

- [x] Staging url: staging.va.gov/my-va
- [x] [Test case documentation](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva-payment-info-v2.md#my-va---outstanding-debts-and-benefit-payments-sections-test-cases) and [test user summary table](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva-payment-info-v2.md#Test-User-Summary-Table)
- [x] [Test case documentation a11y format](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva-payment-info-v2-a11y.md)

- [x] [Payment info v2 project outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/payment-history#v2-updating-payments-and-debts-to-address-usability-issues-may-2022---current-1) (section within full product outline)
 
  

- [x] [Release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/launch-materials/payment-info-v2-release-plan.md#oustanding-debts--benefit-payments-release-plan) with the "Planning" sections completed 

 

### Content artifacts 

- [x] [Outstanding debts frontend documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/outstanding-debts-FE-documentation.md) (includes sketch links)
- [x] [Benefit payments frontend documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/benefit-payments-FE-documentation.md) (includes sketch links)

### QA artifacts
[Learn more about QA test plans](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)
- [x] Product test [cases](https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=8197)/test [plan](https://dsvavsp.testrail.io/index.php?/plans/view/3426) in TestRail with test execution logs.  **NOTE**: Error-state test-cases were not run -- Staging API-errors proved a challenge to mock for specific test-users.
- For error-states, local automated tests were run instead of manual testing.  Results are in TestRail:
  - [x] [Outstanding-debts error-states e2e-test results](https://dsvavsp.testrail.io/index.php?/runs/view/4195)
  - [x] [Benefit-payments error-states e2e-test results](https://dsvavsp.testrail.io/index.php?/runs/view/4202)
- [x] [Coverage for References report](https://dsvavsp.testrail.io/index.php?/reports/view/377) 
- [x] [Summary(Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/376)

### Accessibility artifacts 

- [x] [Completed TestRail Platform accessibility test plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/launch-materials/payment-info-v2-a11y-staging-review-prep.md) (complete)

## Scheduling

- Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Staging Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) on Platform website for more information about the Collaboration Cycle.

 FYI: @shiragoodman

**Comment by ajakabcin** [comment]
@shiragoodman We're not quite ready to even get this scheduled yet, but I wanted to get the ticket started so I could drop the artifacts in as we get them. I'll message in the platform channel when this is ready to go, but in the meantime I'll leave it in my name. Thank you!

**Comment by shiragoodman** [comment]
@ajakabcin Do you have the Design Intent and/or Midpoint Review tickets for this work? Just trying to make it easier for my team to review (when it's ready) and I don't see "Payment Info V2" anywhere in the [Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886)

**Comment by ajakabcin** [comment]
Hi @shiragoodman - yes we do! The name has evolved as we've gone through the collab cycle so that's probably why it's not coming up, and this initiative is still on the old template 🙃  - apologies for the confusion! 

- Design intent - #40551
- Midpoint review 1 - #43068
- Midpoint review 2 (we had to make some fairly significant changes from our first midpoint review and we felt we needed to come back) - #44469

**Comment by shiragoodman** [comment]
thank you @ajakabcin ! This is super helpful. I'll rename it in the tracker so it's up to date with your current language.

**Comment by tlei123** [comment]
@shiragoodman , QA test-runs now completed\*.  Test-cases & test-plan links are above in main description.

**NOTE**: Error-state test-cases were not run &mdash; Staging API-errors proved a challenge to mock for specific test-users.

cc @ajakabcin

**Comment by shiragoodman** [comment]
thanks @tlei123 ! FYI @it-harrison is our new QA.

**Comment by ajakabcin** [comment]
Requested next Thursday 11/3 at 2pm et

**Comment by tlei123** [comment]
@it-harrison , for the error-states QA test-cases [not manually run against Staging], we've posted local automated test-results links above in main description.

**Comment by ajakabcin** [comment]
Hey @shiragoodman, just a heads up for folks as they review the feature ahead of staging review on Thursday: you may see some unusual things with Benefit Payment data. Since this is staging/test data, some payments that come through from BGS are for $0.00 and at times are missing data points, so things may not match _exactly_ between the payment history page and the payment card seen on My VA (this will make sense when looking through our test cases). Posting about this today as it's the first of the month and recurring payments (even $0.00 ones) will have come through over night. Let us know if you have any questions!

**Comment by ajakabcin** [comment]
Also, we had three issues come out of QA, none of which are severe/launch blocking though they will be addressed before launch. Linking below for reference:

- #48809 (may be due to wonky staging data)
- #48810 (may be due to wonky staging data)
- #48812

**Comment by shiragoodman** [comment]
[Zoom Recording](https://oddball-io.zoom.us/rec/share/EHwcRR8idKwZweEwyes8sQqDzTfKYI7s3qI1kkVs88btAXlJk_-sQT5ayFuhKxsr.nVBLXGclqU-izTvn)
Passcode: a+gMH1M$

**Comment by ajakabcin** [comment]
#60637 will resolve #49264, then we can close this staging review ticket

**Comment by ajakabcin** [comment]
Closing this out - all reported issues are resolved 🎉
