### ISSUE TITLE
[Design, FE] Payment info v2: Run a11y scans for Staging review 

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#48605]
## Background
In preparation for staging review we need to perform accessibility tests on Outstanding debts and Benefit Payments on My VA. This will be a joint effort from Design and FE to perform these tests and Product to ensure everything is documented to submit the request. 

[A11y staging review preparation](https://depo-platform-documentation.scrollhelp.site/developer-docs/prepare-for-an-accessibility-staging-review) documentation for reference. 

Additional reference: examples of same tests/process done for staging reviews of 
- [My VA 2.0 launch](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/staging-review/accessibility-test-prep.md) and [notification preferences](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/staging-review/accessibility-test-prep.md) 
- [Onsite notifications](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/launch-materials/onsite-notifications-mvp-a11y-staging-review-prep.md)

## Tasks
- [x] Design and FE to perform the accessibility tests as documented [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/launch-materials/payment-info-v2-a11y-staging-review-prep.md)
- [ ] PM/APM to assist as needed and track progress in staging review artifact documentation

## Acceptance Criteria
- [x] Accessibility tests are ready for Staging Review
