### ISSUE TITLE
[BE] Save icn to appointment identifiers

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#48604]
## User Story
As a Veteran who is using eCheck-in to check-in for an appointment, I want to have the option to submit a claim for travel reimbursement when I check-in so that I don't have to later fill out a form or visit the Travel Office.

## Tasks
- [x] [BE] serialize icn to be saved in redis with appointment identifiers

## Acceptance Criteria
- [x] Deployed to staging
- [x] Tested on staging
