### ISSUE TITLE
Update Qualitative Data Issue Template

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#48610]
## Issue Description
_The qualitative data issue template has had issues retaining assignees, causing us to miss several requests. We also got some feedback on how we can make the template more flexible for different use cases such as research data requests._

---
## Tasks
- [x] _Ensure assignees don’t get dropped_
- [x] _Add description text_
- [x] _Make intuitive for research data requests_

## Acceptance Criteria
- [x] _Updates are made and tested to ensure automatically assigned assignees do not get dropped_
- [x] _Description text is added to clarify elements of the template_
- [x] _Option is added for research data requests_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
Adjustments made:
- Provided definitions for "Survey" and "Support" for Data Type Requested
- Added text indicating terms can be requested in addition to URLs
- Added text stating that data CANNOT be shared with any non-va email addresses
- Added a new field that requests the user ensure the right labels and assignees are assigned. If I fail to get assigned, the field includes my name in the comment, which will alert me when published.

Kimberly submitted a test ticket where I was removed as the assignee, and I still received an email notification that I was mentioned.

The only remaining potential solution is something with GitHub actions. But for now I think this should be sufficient.

**Comment by jwoodman5** [comment]
@ianMcCullough-ob Now that you're done, one other update would be to remove me as an assignee and add Anita.
