### ISSUE TITLE
Integrate QA with other practice areas at Staging Review

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#48617]
## User Story
As a Governance team member supporting QA in the Collaboration Cycle, I want to be able to document my Staging Review findings alongside IA, a11y, design and content so that my product-specific findings can align to the VA.gov Experience Standards.

Assignee: @it-harrison @shiragoodman 
Peer Reviewer: @CherylEvans 

## Description
In the Benefits Team 1 - Certificate of Eligibility Staging Review on 10/14, Ian used the [Collab Cycle Feedback for Staging ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-feedback%2C+Staging&template=collab-cycle-feedback-staging.md&title=VA.gov+category+issue+-+VA.gov+Issue+Description+%28Category+Number.Issue+Number%29) gh template which is the back-up template IA, design, a11y and content use for aligning their feedback to the VA.gov Experience Standards, and in case they miss the opportunity for documenting feedback in the DraftingTemplate. This was somewhat of a happy accident, as it is possible for QA to notice issues with the VFS product and not just issues with the QA process used by the VFS team.

Because of this, QA will now be given the opportunity to document their findings alongside the other practice areas in the DraftingTemplate. The purpose of this ticket is to update the DraftingTemplate to add QA, introduce the DraftingTemplate to @it-harrison and begin documenting the process for how QA completes a Staging Review, product issues only.

## Impacted Artifacts
[DraftingTemplate folder location](https://drive.google.com/drive/folders/1u9HVzUn4Id0p1SbzTt8J6z6bSoQLYOud)
New document - How to complete a QA review for Staging Review (product issues only, process issues will be addressed later on when the QA standards are finalized)

## Tasks
- [x] Shira to add @it-harrison to DraftingTemplate
- [x] Shira to host training session for Ian to teach him how to use the DraftingTemplate (invite @sterkenburgsara )
   - Scheduled for Monday 10/31 at 2:30pm ET
- [x] Ian to review [How to document feedback for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+feedback+for+Staging+Review) and follow up if there are any questions/concerns
- [x] Draft new "How to complete a QA review for Staging Review" as a child page under [How to document feedback for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+feedback+for+Staging+Review) and follow up if there are any questions/concerns- this can be a rough draft as the document will be revised later on.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Ian/QA is part of the DraftingTemplate and is able to document product-specific feedback found during the QA review at Staging Review
- [x] QA is aligned with the other practice areas at the Staging Review

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@it-harrison how is the rough draft of the  "How to complete a QA review for Staging Review" going? Please connect with @CherylEvans to get this done. As a reminder, we only need a rough version put together - we will come back to this guidance in a later sprint and revise so don't feel any pressure now to get it 100% right.

**Comment by it-harrison** [comment]
> @it-harrison how is the rough draft of the "How to complete a QA review for Staging Review" going? Please connect with @CherylEvans to get this done. As a reminder, we only need a rough version put together - we will come back to this guidance in a later sprint and revise so don't feel any pressure now to get it 100% right.

@shiragoodman I completed a draft yesterday and pinged Cheryl. She has given me some feedback already and may give more I think.

**Comment by it-harrison** [comment]
@shiragoodman [here is a link to the draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2428010558/How+to+complete+a+QA+review+for+Staging+review+touchpoint).

**Comment by shiragoodman** [comment]
@it-harrison thank you! This is great so far. Because this is an Operational doc, we can move it over to the Platform Products and Services folder once you and Cheryl are done reviewing/making changes. @CherylEvans can help you with the location.

Please try and have this closed out by EOD today.

**Comment by CherylEvans** [comment]
@it-harrison @shiragoodman I will help Ian with the location.  It looks good for now, but definitely will need to reflect the actual QA methodology used for touchpoint reviews. I understand it's a work in progress.
