### ISSUE TITLE
DDL: Pagination

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#48614]
## Value Statement
**_As a_** veteran looking for a notification letter
**_I want to_** be able to click through pagination if I have more than ten notification letters
**_So that_** I am not overwhelmed by a huge list and can't find what I'm looking for

---
## Background Context

We need to add pagination to the DDL listview

## Acceptance Criteria
- [x] Pagination appears when there are more than 10 notification letters available for view
- [x] Ten letters to a page
- [x] Conforms to approved designs

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready
- [x] _Clear value description_
- [x] _Testable acceptance criteria_
- [x] _Accessibility added to acceptance criteria_
- [x] _Approved designs attached_
- [x] _Sample data provided where appropriate_
- [x] _Estimated to fit within the sprint_
- [x] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
