### ISSUE TITLE
Audit use of react widget for Ask VA links

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#48611]
## Issue Description
When we link to Ask VA, we usually use a react widget to preserve the signed in state for users who have already signed in. Some pages link directly to Ask VA without the widget. And some pages link to the Ask VA section on the Contact us page (which has the react widget).

This isn't a high priority because the link still works without the widget. But when time allows, we should do an audit to standardize our approach to Ask VA links.

---
## Tasks
- [ ] Audit pages to find Ask VA links without the widget 
- [ ] Decide how to handle different types of Ask VA links 
- [ ] Update pages as needed
- [ ] Copyedit/publish updated pages 

## Acceptance Criteria
- [ ] We link to Ask VA in a consistent and intentional way across site
