### ISSUE TITLE
Update VIC page

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#48613]
## Issue Description
We recently updated the VHIC page, and stakeholder Tarsha noted that the photo rules on the [VIC page](https://www.va.gov/records/get-veteran-id-cards/vic/) should probably match the VHIC rules. We also need to make updates to the VIC page to align with tool landing page content pattern.

Katherine started this work when a stakeholder requested we add a note about VIC going all digital, but we paused on larger changes due to timing. We can pick up from her draft changes here.

---
## Tasks
- [ ] Suggest content updates to VIC page (Katherine)
- [ ] Review (Laura)
- [ ] Copyedit (Megan)
- [ ] Send to stakeholder (Katherine)
- [ ] Prepub and publish (Megan)

## Acceptance Criteria
- [ ] Live VIC page is updated

**Comment by laurwill** [comment]
We got a request from Tanekwa to update this page — a Veteran reached out to the call center for help using the online VIC request tool. The Veteran reported that these instructions were missing from the VIC page, but we'll need to talk with Melissa to confirm whether these requirements apply:
- The request has to be submitted using Chrome.
- The photo has to have a background that is “plain” white or beige with no door frames, etc.
- The photo has to be a certain size and no larger.

I'll email Melissa to figure out what updates we may need here.

**Comment by RLHecht** [comment]
I don't think this work was completed. @laurwill is this something we still need to do?

**Comment by laurwill** [comment]
Update: Melissa never answered the request for more information, and the Veteran status card is now slated to (eventually) replace the VIC card. So I think we should close this and leave the VIC page alone until we're ready to archive it.
