### ISSUE TITLE
Research Request: prep and meet with Tech Team 2 (Jesse)

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#48619]
## Issue Description
A Research [Request ](https://dsva.slack.com/archives/CPCGRR7F1/p1666381261475809)has been made and our team needs to review and consider it.

From Jesse:  We’d like to gather info from VFS teams regarding their needs for platform monitoring tools. We hope the understand the use cases and how VFS teams might use Datadog for monitoring.
I’d be happy to collab with your team on technical surveys/interviews/etc to collect the info we’re interested in. 

[Research Intake Doc](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2417524758/Research+Intake+Document+DRAFT)

Research request [mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1666630906186/d0ea57ee847ffd0b57d49abf4224a1d27a1531ec?sender=u4397b715dc3690a417b71483)

## Tasks
- [x] Team:  Discuss request
- [x] Schedule meet-up
- [x]  [Generate initial questions](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1666630906186/d0ea57ee847ffd0b57d49abf4224a1d27a1531ec?sender=u4397b715dc3690a417b71483) to help with understanding the ask/scope
- [x] Team:  Meet w/ PM of Tech Team (Jesse)
- [x] schedule internal workshop - (pushed out further due to OoO conflicts)
- [x] Team members:  clean up any notes in mural above
- [x] Responded to requestor (Jesse).  He feels like he has a good idea of what he wants to pursue and how to go about it.  I share our Synthesized mural above to help with his own clarity on what he is after.  

Will create an additional ticket to get specific on next steps.

## Acceptance Criteria
- [x] A response has been made to the request
