### ISSUE TITLE
Create Success Metric Dashboard for Review Environments

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#48618]
## Issue Description
With success metrics validated, we will want to create a dashboard to track and reflect those metrics for current Review Instances.

**NOTE** - This dashboard will need to be updated when a new Preview Environment is created and additional metrics are available for tracking.

---
## Tasks
- [x] Create a dashboard for Review Instance metrics in Domo
- [x] Collect the metrics into a dataset for use in the dashboard
- [x] Create a visual for each one of the metrics
- [x] Review internally on the team to refine
- [x] Review w/ Product Owner

## Acceptance Criteria
- [x] A preview environment metrics dashboard is available in Domo
- [x] The dashboard contains visualizations for each of the metrics identified

**Comment by CBonade** [comment]
This dashboard has been created and is located here: https://va-gov.domo.com/page/241111776?userId=825144754 .  Access is currently granted to Joe and Peter, and can be granted to anyone else as necessary. 

The cards in this dashboard run off of two data sets:
[Review Instance Baseline Metrics](https://va-gov.domo.com/datasources/40d2b4b0-3e09-488b-ad13-05efaabc7844/details/overview)
[Review Instance Access Logs](https://va-gov.domo.com/datasources/b692ec6a-1bfe-4911-9e24-bacd9c1275e7/details/overview)

The first data set covers metrics surrounding review instance deployments, while the second measures the interactions of users with review instances. This has lead us to being able to display 4 metrics:

1) Review instnaces launched per day - how many of these review instances are being launched daily?
2) Review Instance Usage - of the ones that are launched, how many of them are ever accessed by a user vs how many of them sit untouched just tying up resources?
3) Review Instances Default vs Custom config - the default configuration for review instances is to use your feature branch from whatever repository is doing the deployment as well as the main/master branch of the other repositories. However, there is a custom Jenkins workflow that allows it to be triggered with a custom branch for each repository. This shows how many of these instances had the default configuration vs someone picking each branch themselves.
4) Review Instance deployment status - this tracks how many of the review instances spin up successfully vs how many run into an error during deployment.

**Comment by JoeTice** [comment]
Base dashboard is completed as specified, a small set of visual tweaks will be captured in another ticket
