### ISSUE TITLE
Table work and other content updates to VA home loan funding fee page

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#48612]
## Issue Description
We recently adjusted the bullets in the eligibility section on the [VA home loan funding fee page](https://www.va.gov/housing-assistance/home-loans/funding-fee-and-closing-costs/). This page also has tables and some other outdated content styling we need to adjust. 

---
## Tasks
- [ ] Assess tables and other page content and suggest updates 
- [ ] Review (Laura)
- [ ] Copyedit (Megan)
- [ ] Send to stakeholder Raleigh (Laura)
- [ ] Prepub checklist and publish (Megan)

## Acceptance Criteria
- [ ] Live page is updated for current site style
