### ISSUE TITLE
Tagalog translation for Novavax booster updates on 10/21/22

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#48623]
## Issue Description
We made updates to 2 COVID-19 pages about Novavax booster eligibility that we need to have translated in Tagalog.

Word doc sent to translators: [https://app.zenhub.com/files/133843125/75e34646-267f-445c-a327-f094a5502cc6/download](https://app.zenhub.com/files/133843125/75e34646-267f-445c-a327-f094a5502cc6/download)

Note that on the Booster shots page we also removed content, which isn't reflected in the Word doc. We also have 2 sentences that are the same on both pages so I only asked for it to be translated once. The same content will need to be added to both pages. Make sure to look at the revisions tab in Drupal to see everything that was changed. 

## Tasks
- [x] Send text to translators
- [x] Update Drupal pages (Aliyah)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Tagalog page is updated on the live site

**Comment by RLHecht** [comment]
@aliyahblackmore here is the tagalog translation we got back[https://app.zenhub.com/files/133843125/3b9657dc-af5f-4fc7-a3a3-f7000b60b2b2/download](https://app.zenhub.com/files/133843125/3b9657dc-af5f-4fc7-a3a3-f7000b60b2b2/download)

**Comment by aliyahblackmore** [comment]
Hi @megzehn - these updates are ready on the [main COVID-19](https://www.va.gov/health-care/covid-19-vaccine/) and [Booster pages](https://www.va.gov/health-care/covid-19-vaccine/booster-shots-and-additional-doses/).

Noting here that, as I mentioned, the pages were reverted to the most recent published version (to correct the CMS migrator issue). Additionally, some of this content correlates to previous content that we didn't get back in this word document. I've noted that where it is the case and if there is still something that we need back. I sent back what we still need translated to Randi via email.

This is the document from the previous work order:
[2cf80230-20e5-46e4-8bd3-25917d911960.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9924271/2cf80230-20e5-46e4-8bd3-25917d911960.docx)



COVID-19 Vaccines at VA page 
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=16413

Notes:
1. I removed this sentence because it is no longer on the live English page: “Darating na ang mga makabagong booster na iniksyon sa VA at maaaring matanggap sa halos lahat ng pangkalusugang pasilidad ng VA simula ng linggo ng Setyembre 12, 2022”
2. We are missing “Call before you come in to make sure the facility has the booster you want” from the translation – this wasn’t highlighted in the featured content box from the doc sent in this ticket.  It looks like we sent this to the translators in another [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47672) (we didn’t get this content back) and didn't get it back.  CC: @RLHecht 
3. In the translated content that we got back, I noticed that the word “Note” is translated differently than it is on the current live page and as it has been in the past. We’ve usually gotten “Paalala.” Can we ask which word should be used for “Note” so that is it consistent throughout the page . Or is this an instance of the word choice depending on context? cc: @RLHecht 
4. Under “Primary vaccines” I removed the bullet that starts with “Ang COVID-19 na bakunang Novavax ay awtorisado nang ibigay sa mga taong hindi bababa…” as this is no longer on the live English page and I removed the bullet style here.
5. In the accordion “Can I get a COVID-19 vaccine and a flu vaccine at the same time?” there is content in here that we still need back from the translator that was sent and is in this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47672). “Only Veterans who are enrolled in VA health care can get flu shots at VA health facilities. Call before you come in to make sure the facility has both vaccines.” This is also on the boosters page. Cc: @RLHecht 
6. In the accordion “Ano ang gagawin kung ikaw ay nabakunahan laban sa COVID-19 sa labas ng VA” (What to do if you get a COVID-19 vaccine outside of VA), the sentence “It’s your choice where you’d like to go to get a vaccine” still needs to be translated. @RLHecht 


Booster page
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=34394

Notes:
1. In the Header “Pagkuha ng booster na iniksyon” (Getting your booster shot), we sent a content change to the age in the batch of translations that didn’t come back, in this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47673),. I went ahead and changed the number to 5, as there isn’t Tagalog content that we need here.
2. In this same header we needed the text that begins with “We offer updated COVID-19 vaccine booster shots at no cost” as this was sent in [a previous work order](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47673) that we didn’t get back. I noticed that this is already on the main COVID-19 Vaccines at VA page, so I pulled the text from there. We are still missing this text: Not sure if you’re eligible? [Find out who can get a COVID-19 vaccine at VA](https://www.va.gov/health-care/covid-19-vaccine/#who-can-now-get-a-covid-19-vac)
3. In the note I pulled “You can get it 6 months after your primary vaccine series if you haven’t gotten any boosters yet. Novavax is not updated to protect against the Omicron variant.” from the COVID-19 page as it was translated there.
4. Under the header “If you’re a Veteran who receives care through VA” we need this translated “Only Veterans who are enrolled in VA health care can get flu shots at VA health facilities. Call before you come in to make sure the facility has both vaccines.” translated. This also exists later on this page and on the COVID-19 Vaccines page.
5. Also noting that in the previous work order “If you’re a Veteran who receives care through VA
If you’re eligible to get a booster shot, contact your local VA health facility to find out how you can get your shot” was highlighted, but that content actually already existed on our page.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
