### ISSUE TITLE
Spanish translation for updated Novavax booster information from 10/21/22

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#48622]
## Issue Description
We made updates to 2 COVID-19 pages about Novavax booster eligibility that we need to have translated in Spanish.

Word doc sent to translators: [https://app.zenhub.com/files/133843125/75e34646-267f-445c-a327-f094a5502cc6/download](https://app.zenhub.com/files/133843125/75e34646-267f-445c-a327-f094a5502cc6/download)

Note that on the Booster shots page we also removed content, which isn't reflected in the Word doc. We also have 2 sentences that are the same on both pages so I only asked for it to be translated once. The same content will need to be added to both pages. Make sure to look at the revisions tab in Drupal to see everything that was changed. 

## Tasks
- [ ] Send text to translators
- [ ] Update Drupal pages (Aliyah)
- [ ] Copyedit (Megan)
- [ ] Publish (Megan)

## Acceptance Criteria
- [ ] Spanish page is updated on the live site

**Comment by RLHecht** [comment]
@aliyahblackmore here is the content back from the translators. Please let me know if there are any issues with it![https://app.zenhub.com/files/133843125/36f872cf-db96-4bb8-b33b-7ff5916e11d3/download](https://app.zenhub.com/files/133843125/36f872cf-db96-4bb8-b33b-7ff5916e11d3/download)

**Comment by aliyahblackmore** [comment]
Hi @megzehn! These pages are ready for you, with some notes! 

**COVID main page** 
**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=16359

As an FYI, in the translated doc, you’ll see sections **that were not** highlighted that were re-translated. In some instances, these were sections that are already on the live Spanish page and we did not need to be re-translated. Randi gave the okay that we just focus on the sections of text that we highlighted/asked to be translated. If there was an instance of something being pulled in, I’ve noted it here.

1.	In the doc sent back to us, ”Booster shots” was changed to “Vacuna de refuerzo” We didn’t ask for this to be translated. The text on the current page has “Vacunas de refuerzo,” which is correct.  Wondering if the translators can provide a reason for why this may have been changed. I’ve left it as “Vacunas de refuerzo” for now. cc @RLHecht 
2.	On the doc sent to translators this sentence wasn’t highlighted: “Call before you come in to make sure the facility has the booster you want.” The translators did send this back in the document anyways and we did need this to be translated -  so I included it on the page! 
3.	Randi, I believe similar to the Tagalog page, we still need the content from 9/23/22 and 10/17/22 re: flu shots and COVID-19 vaccines for this page (from this ticket – https://github.com/department-of-veterans-affairs/va.gov-team/issues/47670) – right now, in the accordion “¿Puedo recibir la vacuna COVID-19 y la vacuna contra la gripe al mismo tiempo?” we are missing this sentence: **Note: Only Veterans who are enrolled in VA health care can get flu shots at VA health facilities. Call before you come in to make sure the facility has both vaccines.**

**COVID-19 Booster page**
**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=34408

This page was impacted by the linkies, so I reverted to the last published (10/3/22 – at 2:22pm) version and made changes there. Also, like the main COVID-19 page, there is text that was not highlighted that was re-translated by the translators. We are only adding in the content that we asked for and pulling in any content where necessary or needed.

1.	We didn’t highlight/ask the first sentence in the first header to be translated again, but we actually did need to change the age to 5 here. I used the sentence that the translators sent back to us and I noticed that they used “El CDC” instead of “Los CDC.” We used “los” on the main COVID-19 page. For consistency, can we ask the translator whether we should use “los” or “el?”  I’ve left this as is for the time being. CC: @RLHecht 
2.	We didn’t highlight/ask the translators to re-translate the header “Cuando recibir la vacuna de refuerzo actualizada” but they did translate this again and use “su” instead of “la.” “Su” would be correct as a translation of “your” so I put this on the page for the time being. They also added “su” in the sentence after.  @RLHecht - could we confirm with the translators whether “su” or “la” should be used, as these parts of the page were previously translated by them and not highlighted this time around. We also have “su” on other parts of this page that were previously translated, for example in the community care section, “obtiene su vacuna.”
3.	Similar to the Tagalog page, we had some text on the main COVID-19 page (in the featured content box) that was previously translated that wasn’t highlighted in what was sent to the translators for the booster page this time around. The text begins with “We offer updated COVID-19 vaccine booster shots at no cost” and then the bulleted list. This content was re-translated on the main covid page in this doc sent to us (not highlighted) but, as Randi confirmed, I did not change it there because we didn’t ask for it to be translated. The section of content on the English page is the same on the booster page (and it was re-translated here as well).  I went ahead and added the text that was already on the live main COVID page and pulled it in here. @RLHecht  – let me know if you’d like to have the translators confirm which text should be used, seeing as this was not highlighted.  
4.	The text “Not sure if you’re eligible? [Find out who can get a COVID-19 vaccine at VA](https://www.va.gov/health-care/covid-19-vaccine/#who-can-now-get-a-covid-19-vac)”  wasn’t highlighted in the doc sent to the translators, but they did translate in the document that was sent back to us, so I pulled this on to the page. 
5.	For the note that begins with “En casos limitados, las personas mayores de 18 años pueden” we only highlighted this sentence in the document sent to them, but they translated both sentences. We did actually need the second sentence as well, so I added this to the page.

**Comment by megzehn** [comment]
Thank you, @aliyahblackmore for all these changes and for the notes! 

Confirming that both pages have been reviewed and published.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
