### ISSUE TITLE
Create a Service Blueprint diagram for a Preview Environment 

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#48620]
## Issue Description
With an understanding of existing pain points, and the user and technical flows of the current state of Review Instances, we will want to diagram the planned approach to a proposed solution.

---
## Tasks
- [x] Include a table matrix that defines which pain points will be addressed
- [x] Include a basic mapping of testing environments
- [x] Include a comparison of Review Instances and Preview Environments
- [x] Include a mapping of the user flow
- [x] Include a technical flow/architecture
- [x] Include a mapping of the user flow
- [x] Include a service blueprint
- [x] Review w/ Platform Engineering Lead
- [ ] Review w/ Product Owner

## Acceptance Criteria
- [x] A finished flow diagram is completed and available on Confluence

**Comment by JoeTice** [comment]
Final service blueprint available for review here: https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1666011911859/c0bf24d69db1638ccb56bf090acc1487ea9431c7?sender=uc4d00ea50beebdfad05a4846
