### ISSUE TITLE
Modify Design Intent script to add time limit for VFS team

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#48625]
## User Story
As a VFS designer or PM presenting on my product at the Design Intent, I want to know how much time I have to present so that I don't take up all of the 30 minute meeting.

Assignee: @briandeconinck 
Peer Reviewer: @CherylEvans 

## Description
As the Design Intent on 10/14, @allison0034 told the VFS team, after completing reading the script out loud, how much time the VFS team had to present their product. This is so that we can allow enough time for the Governance team to provide feedback on the product within the 30 minute meeting.

The purpose of this ticket is to modify the Design Intent script to add a pre-determined time limit for each and every VFS team.

## Impacted Artifacts
[Design Intent page on PW (script)](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Moderatorscript)
[Moderator Responsibilities for Design Intent (script)](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Moderator+Responsibilities)

## Tasks
- [x] Determine how much time the VFS team should have to present for every Design Intent
   - Shira's thoughts: 10 minutes? That'll leave 15 minutes or so for us to provide feedback (since the script takes a minute to read and we don't always start on time)
   - Brian's thoughts: 10 minutes seems good. I went back and rewatched some old DIs, and Allison was cutting people off in the 12-15 minute range. I feel like saying 10 and enforcing a 12ish cutoff for people who go over is reasonable.
- [x] Update the script in a draft doc and have peer reviewed
   - [Draft script](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2478276682/48625+-+Design+Intent+moderator+script)
- [x] once approved, update the 2 impacted artifacts above

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] VFS teams are notified how much time they have to present their product at Design Intent

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
@CherylEvans [Updated script](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2478276682/48625+-+Design+Intent+moderator+script) ready for review.

**Comment by CherylEvans** [comment]
@briandeconinck I have reviewed your changes, and they are perfect.  :-)

**Comment by briandeconinck** [comment]
I have updated the script on:
- [Design Intent - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Moderator+Responsibilities)
- [Design intent](https://vfs.atlassian.net/wiki/spaces/CC/pages/1782153235/Design+intent) (Platform website)

Changes should be published to Platform website later today. Once that's verified I'll close out this ticket!

**Comment by CherylEvans** [comment]
@briandeconinck Looks great, feel free to close! :-)

**Comment by briandeconinck** [comment]
Platform website changes published for [Design Intent page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent), closing as completed!
