### ISSUE TITLE
Conduct research with research participants 

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#48639]
## User Story
As a Governance team member, I plan to conduct user research with multiple VFS team members who have recently undergone the orientation process  so that I can get a fresh understanding of pain points, frustrations, and successes with their experience onboarding to platform. 

As a Governance team member, I want to conduct user research with platform orientation hosts who have regularly conducted orientation sessions for several months, so that I can understand challenges with hosting. 

Assignee: @sterkenburgsara @allison0034 

## Description
The goal of this ticket is to complete moderated stakeholder interviews (virtually) with several VFS team members across practice areas, teams, and levels of expertise (a few managers), but primarily focusing on folks who have very recently been onboarded (within the past 3 months) to the VA. These interviews will take place between December 5-15, 2022.

Each interview should span about 35 minutes with Allison and Sara alternating as necessary between the roles of moderator and notetaker. We will request permission to record all interviews for transcription and reference later, but will destroy the interviews once they have been transcribed and anonymized. 

## Impacted Artifacts
- Interview notes

## Tasks
- [x] Consult the [Research Plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2425978881/Platform+Orientation+Discovery+Platform+Research+Plan) 
- [x] Consult conversation guides
   - [VFS Team Members](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2432172044/Conversation+Guide+VFS+Team+members)
   - [Orientation hosts](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2437546120/Conversation+Guide+Orientation+hosts)
- [x] Recruit and schedule VFS team members for interview sessions
   - [Calendly Link](https://calendly.com/vsp-research/30-minute-meeting-clone)
- [x] Dry-run with @naomimarcussen 
- [x] Interview at least two FE engineers
- [x] Interview at least two BE engineers
- [x] Interview at least two designers or researchers
- [ ] Interview at least two product managers (12/19 - only interviewed one PM)
- [x] Interview at least two interview hosts/Platform team members
- [ ] Compile notes from each interview to be used in research synthesis (12/19 - we have notes, but they will be more detailed as we compile synthesis)

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Minimum number of user interviews are complete
- [x] Notes/transcriptions for user interviews are complete and accessible to governance team (notes used in next ticket: synthesizing user research)

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by sterkenburgsara** [comment]
@allison0034 Calendly schedule has been set up (linked under Tasks section above). I compared our calendars, but could you take a peek and verify that the dates available work with your schedule?

**Comment by sterkenburgsara** [comment]
@allison0034 @shiragoodman is there a good tool for us to record interview notes, which will eventually be full interview transcriptions?

**Comment by sterkenburgsara** [comment]
@allison0034 Calendly had been updated (with 9:00a EST time slots removed). Duplicative screener question (per survey you sent out) also removed. 

I currently have one Calendly set up for scheduling both VFS Teams and Platform Orientation hosts. Let me know if you prefer we split it up and I can set up a second Calendly invitation for the latter group.

**Comment by allison0034** [comment]
@sterkenburgsara looks good to me!
