### ISSUE TITLE
Research Medallia Reports for VFS Team Engagement

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#48646]
## Issue Description
_We have a lot of meaningful data being captured through our Medallia surveys and want to increase engagement with VFS teams who's product can be improved through understanding what Veterans like and don't like about those products._

---
## Tasks
- [x] _Research Medallia report in their UI_
- [x] _Identify which report(s) can be most valuable to share with VFS teams_
- [ ] _Update VFS engagement plan with the reports we plan to share_

## Acceptance Criteria
- [ ] _New reports in Medallia are identified and added to the VFS data engagement plan_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
Dropping a note in here so I don't forget—I'd imagine if we expect VFS teams to interact with this data within Medallia itself, we're going to need to add a process for Medallia access (submit a ticket?) and add that process to the engagement plan. 

I'm in the process of scheduling a discussion with Sarkis for next week (week of 10/31) to review reporting capablilites, I'll ask about the process of adding users to determine if that process can be ironed out this sprint or next.

**Comment by jwoodman5** [comment]
Initially, Sarkis said the VSignal contract did not include access outside of Medallia administrators/facilitators like us (and a few key personnel). My initial thought with this was we would find easier ways to provide them with more meaningful data, but if it makes sense for them to access Medallia themselves, that could save a lot to time for our team.

**Comment by ianMcCullough-ob** [comment]
Working with Sarkis on adding the Word Cloud module to the reports. This searches for word frequency and adds sentiment to it (good, bad, neutral). Will, hopefully, be able to filter by term and URL as well.

**Comment by ianMcCullough-ob** [comment]
Met with Sarkis and sent off an official request to implement that Word Cloud.

**Comment by ianMcCullough-ob** [comment]
Word cloud has been implemented in the staging instance, working on getting in the prod instance.

**Comment by ianMcCullough-ob** [comment]
Word cloud has been added and seems to be functioning properly.
