### ISSUE TITLE
Manually remove old feature toggles

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#48641]
## Description
We would like to automate the process of removing old feature toggles, but first, need to go through the process manually to determine how to best do that.  

## Tasks
- [x] Compile a list of features to disable
  - [x] Consider how might this be automated / workflow
- [x] Create PR and reach out to respective teams
  - [x] Consider how might this be automated / workflow
- [x] Verify features disabled from PR

## Acceptance Criteria
- [x] We have manually gone through the process of removing old old feature toggles and have determined if it is possible to do it in an automated way. 
  - [x] Spin up ticket / link findings

**Comment by oseasmoran73** [comment]
FeatureToggleEvent gives multiple events. Need to figure out a way to filter it more cleanly

**Comment by oseasmoran73** [comment]
Try to see if you can do a `git blame` [Slack](https://dsva.slack.com/archives/C045C97V7N1/p1666985223398379?thread_ts=1666973523.146979&cid=C045C97V7N1)

**Comment by oseasmoran73** [comment]
Played about bit with API (from octokit and graphQL). While it does have blame, it does not provide a date range. Only as a form as integrer

One thing that I did encounter is if done via CLI, it can be done on a specific line. What I am thinking is:
  1. Find out line for feature
  2. Create a map for it
  3. git blame those line numbers
  4. parse string of returned output to map
  5. logic to compare

**Comment by oseasmoran73** [comment]
Worked with Eric on some potential solution for the automation

Reached out to team to and did not realize how involved some of these PRs can be. Might cause an issue when it comes to automating. But based on discussion with Eric, first portion of automation should be to at least generate something like an excel sheet with all the information

**Comment by oseasmoran73** [comment]
Reached out to teams to let them know of feature toggles. Some have done internal investigation and others are pending. Tracked of those I reached out, but should x-ref their excel with the one I am using to get a clearer image

**Comment by oseasmoran73** [comment]
Shared excel sheet with Eric & Nate

**Comment by oseasmoran73** [comment]
Reached to Eric for assistance on some of the ones I was unable to find. Currently blocked as I am not sure who to reach out. [Slack](https://dsva.slack.com/archives/C045C97V7N1/p1668103413565269)

**Comment by oseasmoran73** [comment]
Talked to a few more folks after going deep into slack. A few more remain and some that have not replied. Will try and follow up with those
