### ISSUE TITLE
Tier 3 Tracking Process

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#48653]
## Issue Description
_In order to optimize our tier 3 support handling, we need to be able to track the process._

---
## Tasks
- [ ] _Document our tier 3 tracking process in Confluence_
- [ ] _Identify any gaps to tracking data and include in document (potential work needed)_

## Acceptance Criteria
- [ ] _Tier 3 tracking process is documented in Confluence_
- [ ] _Trackable and untrackable metrics are documented_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
https://docs.google.com/document/d/13oN_4VjrXZmlNX9ONXKY-1WmNXCtVuEdzKkmy9IVTOI/edit?usp=sharing

**Comment by clantosswett** [comment]
@Kimberley2019 I reviewed the document. It looks great! I made some comments so feel free to reach out if you have questions.

**Comment by Kimberley2019** [comment]
Thank you @clantosswett I will update the doc accordingly and share with Jeremy Haas for his input.
The goal is to implement next sprint.

**Comment by Kimberley2019** [comment]
Approval from Jeremy Haas has been received to move forward with this process.  All finalization has been completed and this will go into effect as of 11/14/22.

From: Haas, Jeremy T. <jeremy.haas@va.gov>
Date: Thu, Nov 10, 2022 at 1:44 PM
Subject: RE: [EXTERNAL] Tier 3 Process
To: Kimberley Daniels <kimberley.daniels@adhocteam.us>
Cc: Lantos-swett, Chanteclaire E. (she/her/hers) <Chante.LantosSwett@va.gov>

**Comment by Kimberley2019** [comment]
![Benefits_Tier2_Tier3_Support_Flow.png](https://images.zenhubusercontent.com/5d3b2f7176f8655a8ad39ace/037b490b-5079-4500-a140-a22ad6edf721)
![Benefits_Tier2_Tier3_Support_Flow-Simplified.png](https://images.zenhubusercontent.com/5d3b2f7176f8655a8ad39ace/a4084c49-fb96-43d0-bebe-536e367a0468)

**Comment by Kimberley2019** [comment]
Final task before closing ticket is to add all documentation to confluence.
