### ISSUE TITLE
Create and Implement New Support Coverage Plan

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#48651]
## Issue Description
_We have had a general support ownership coverage plan in the past, but with new team members and working practices in place now, we need an new, more comprehensive coverage plan created and implemented_

---
## Tasks
- [ ] _Create support (tier 2, tier 3, AVA, inbox) coverage plan_
- [ ] _Document new coverage plan in Confluence_
- [ ] _Reference & link new coverage plan in Tier 2 & 3 Ownership document [here](https://vfs.atlassian.net/wiki/spaces/Contact/pages/2169208967/Support+Ownership+by+Tier+Type)_
- [ ] _Update Tier 2, tier 3, AVA, inbox ownership doc to align with new coverage plan_
- [ ] _Review new coverage plan with entire team and confirm alignment_

## Acceptance Criteria
- [ ] _New tier 2, tier 3, AVA, inbox coverage plan is documented in confluence_
- [ ] _Tier 2, tier 3, AVA, inbox ownership doc is updated to align ^ and docs or referenced/linked_
- [ ] _Entire team has reviewed and is aligned on new plan_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jkwontheso** [comment]
@jwoodman5 Once Ervin gets added to this story (I might refer to story as issue at times, sorry in advance) I'll provide whatever support I can.

**Comment by jwoodman5** [comment]
@jkwontheso Either works. I do the same thing. Thanks for being willing to jump in and help figure it out. If nothing else, maybe you can coordinate updates to this issue from Ervin since I still can't seem to add him as an assignee...?

**Comment by ATMiddleton** [comment]
Created, shared and approved by team members.
