### ISSUE TITLE
Migration of legacy CSP users to Login.gov

### ISSUE THREAD

**Issue by pscruz** [department-of-veterans-affairs/va.gov-team#48670]
There is an opportunity to bind an LOA2 VA credentials to Login.gov IAL1 so it can at least be used within VA without requiring initial additional identity proofing. The end goal is to simplify the migration process for existing users.

## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/login.gov-adoption/products/legacy%20CSP%20migrations)

## High Level User Story/ies
**As a** user of government services
**I want** to utilize a modern, secure credential
**So that** I can safely access government services

# User Experience
## Acceptance Criteria (Eligible User)
- [ ] On login, check user for eligibility
- [ ] If user is eligible account is flagged as Eligible
- [ ] On next login, user is presented a [page/modal] indicating eligibility and can proceed or decline
- [ ] On decline, user is taken back to previous location
- [ ] On accept, user is presented with page explaining what will happen
- [ ] User is taken to Login.gov to create/sign-in with their account
- [ ] User is returned to VA.gov on a page explaining they have now linked their Login.gov account
- [ ] If user tries to login with legacy credentials later, they are prompted to use Login.gov

# Technical
## Acceptance Criteria
- [ ] All tasks in Frontend Epic completed
- [ ] All tasks in Backend Epic completed
- [ ] All tasks in Security Epic completed
- [ ] DAST Scan

**Comment by elizabethkochBT** [comment]
replaced with #52654
