### ISSUE TITLE
BE | Profile | Notifications | Multiple Requests Issue

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#48695]
## Background
There’s a scenario where communication permissions requests are being re-sent multiple times.

More details here - https://dsva.slack.com/archives/C909ZG2BB/p1666709447101449?thread_ts=1666296364.149259&cid=C909ZG2BB

## Tasks
- [x] Investigate and determine root cause.
  

## Acceptance Criteria
- [x] Determine cause of issue.
- [x] Create tickets for fix.

**Comment by tpharrison** [comment]
See [example](http://sentry.vfs.va.gov/organizations/vsp/discover/platform-api:0ba9f6c5f5d0494a968ff8ae50d12e27/?display=daily&field=url&field=error.value&field=timestamp&name=Errors+by+URL&query=event.type%3Aerror+controller_name%3Acommunication_preferences&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1).

**Comment by tpharrison** [comment]
Was able to reproduce the errors in staging with my account.  I am currently in discussions with VA Profile about this.
