### ISSUE TITLE
[FE] My VA Audit UX Improvements: Update Copy in Healthcare Section

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#48705]
## Background
Based on Midpoint review feedback from content we need to update the copy in the Healthcare Section of My VA. Related to Design ticket #48701 

Feedback on this topic can be found in these tickets:
* #48624 -- Must feedback 
* #48155 ([comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48155#issuecomment-1288336945))

## Tasks
- [x] Update all instances of "view" to "review
- [x] Update copy of appointments error message to read “We can’t access your appointment information” (removes phrase “right now” to match claims and appeals”
- [x] Validate

## Acceptance Criteria
- [ ] Copy in the Healthcare section is updated

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_
- _How can this work be validated?_ Log into Staging and check if copy matches new designs

**Comment by tmitchellgcio** [comment]
Just pushed give it 30min to an hour to hit staging

**Comment by ericasauv09** [comment]
@tmitchellgcio based on Angela's comment [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48701#issuecomment-1303978456). We want to remove the "right now" wording from the Healthcare error, ill update the tasks in this ticket and we can move this back to in progress when you are ready to work on it.

**Comment by ericasauv09** [comment]
validated with user Judy Morrison: ![Screen Shot 2022-11-08 at 11.13.58.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/a3d81db2-6154-4f4b-a295-17e9f03868ce)

**Comment by ericasauv09** [comment]
User Judy Morrison looks good now: 
![Screen Shot 2022-11-08 at 16.49.12.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/fb5cb2a6-e92c-4548-aaa9-fd33cdadc849)
