### ISSUE TITLE
[Design] My VA Audit UX Improvements: Update LOA1 State Designs

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#48706]
## Background
During Midpoint Review we received feedback around our design of the LOA1 state on My VA. Feedback is documented [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/MidpointReview.md). This ticket is to update the designs for LOA1 based on content feedback.

Feedback on this topic can be found in these tickets:
* #48624 -- Must feedback 
* #48655  -- Must feedback

## Tasks
- [x] Use em dash instead of plain dash in this sentence “We need to make sure you're you—and not someone pretending to be you—before we can give you access to your personal and health-related information.” (longer dash, this – vs - )
- [x] Update Sketch files and FE Documentation
- [ ] PM to check FE tickets and update accordingly

## Acceptance Criteria
- [ ] New designs for LOA1 State are complete

**Comment by aagosto90** [comment]
Link to updated [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/LOA1-state-FE-documentation.md) and [Sketch file](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/32BCF55D-35A5-4A17-9F37-3DCA903B7A50).

**Comment by ericasauv09** [comment]
created #49558 to address the FE changes for this
