### ISSUE TITLE
[Design] My VA Audit UX Improvements: Copy Updates Based on Midpoint Review Feedback

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#48701]
## Background
During Midpoint Review we received feedback around some of our copy on the My VA page. Feedback is documented [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/MidpointReview.md). This ticket is to update copy based on content feedback.

Feedback on this topic can be found in these tickets:
* #48624 -- Must feedback 
* #48155 ([comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48155#issuecomment-1288336945))

## Tasks
- [x] Update all instances of "view" to "review"
- [x] Capitalize GI Bill and GI Statement of Benefits
- [x] Update Claims and Appeals error state: update copy to “We can't access your claims or appeals information right now” to be consistent with error on appointments in Health care section: “We can’t access your appointment information”
- [x] Health care error state: update copy of appointments error message to read “We can’t access your appointment information right now” (adds phrase “right now” to match claims and appeals”
- [x] Update all Sketch files and FE documentation with new copy
- [x] PM to check that all FE tickets are updated

## Acceptance Criteria
- [x] All new copy based on Content feedback is updated

**Comment by ajakabcin** [comment]
This ticket also addresses feedback we received in #48155

**Comment by aagosto90** [comment]
Making a record of what instances of "view" needed to be changed to "review" in the Sketch file and FE documentation:
- Benefit payments: Link in card changed to "Review your payment history"
- Benefit payments: Secondary link for payment history when a user has no recent payments to show but has had payments in the past changed to "Review your payment history"
- Claims and appeals: Link in card changed to "Review details"
- Health care: Messages notifications link changed to "Review your messages"

**Comment by aagosto90** [comment]
> Health care error state: update copy of appointments error message to read “We can’t access your appointment information right now” (adds phrase “right now” to match claims and appeals”

I realized as I was making this update that Claims & Appeals is the only section that says "right now" at the end of the error message. Therefore instead of updating the health care error state to say "right now", I took "right now" out of the Claims & Appeals error and updated the designs and documentation. I don't think those two words are necessary and now we have consistency which was the goal of the content suggestion.

**Comment by tmitchellgcio** [comment]
@aagosto90 Benefit payments also says it. Do we need to remove it from claims and appeals as well as payments?

**Comment by aagosto90** [comment]
> @aagosto90 Benefit payments also says it. Do we need to remove it from claims and appeals as well as payments?

Does it say "right now" in the headline of the error or just the body copy? In my mockups it doesn't say "right now" in the header of the benefit payments error.

**Comment by tmitchellgcio** [comment]
oh sorry the body copy

**Comment by aagosto90** [comment]
Ah okay; well that's fine as is then. Looks like most of them have some reference to "right now" in the body copy. Thank you for flagging it though!

**Comment by ericasauv09** [comment]
Updated #47683 to include task to capitalize GI Bill and created #49513 and #49514 to update "view" instances to "review."
