### ISSUE TITLE
[FE] My VA audit UX improvements: update Health Care section "unread messages" notification with new notification component

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#48719]
## Background
Per feedback from Midpoint review, we learned we can use the notification component that Angela designed and submitted to the design system (it was approved!). This ticket is to update the "unread messages" notification within the Health care section on My VA (where we currently use the "warning alert component") to use the new notification component. (Build of the component was done in [48726](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48726))

[Onsite notifications FE documentation can be found here.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/frontend-documentation/notifications-frontend-documentation.md)

[In-line notifications FE documentation is within the health care FE documentation, found here.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/health-care-FE-documentation.md#if-a-user-has-unread-messages-from-a-health-care-providers)

Feedback on this topic can be found in these tickets:
* #48655 -- Should section 

## Tasks
- [ ] Update code/replace warning alert component with new notification component in the Health Care section when user has unread messages 
- [ ] Update tests
- [ ] Move to validate and inform PMs and designer that it's ready for validation

## Acceptance Criteria
- [ ] New notification component is being used in the Health Care section on My VA 
- [ ] New component is implemented correctly (per design system specs and recommendations)

## Validation
- **_Who can validate this ticket? (FE, BE, Design, PM)?_** PMs and Designer
- **_How can this work be validated?_** Log into staging and confirm that the new notification component is being used instead of the "warning alert component"

**Comment by ajakabcin** [comment]
Closing this ticket - when the notification design system component is complete we will NOT be replacing the current unread messages alert with the component.
