### ISSUE TITLE
[EPIC] Ensure session management contininuity for OAuth

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#48711]
## Description
Several different applications and teams are utilizing the `fetchAndUpdateSSOeSession` as their applied global `fetch` in order to update the SSOe session.  Because this implementation relies solely on SSOe, the newer initiative to enable OAuth on VA.gov currently breaks sessions for other applications not already implementing the `apiRequest` function.

## Definition of done
All implementations of `fetchAndUpdateSSOeSession` should be changed to use `apiRequest` to refresh the OAuth access and refresh tokens when a 403 comes back.  Additionally, unit tests and Cypress (E2E) tests should be updated as well to ensure complete code coverage of new session managment

## Tasks
- [x] Pensions (2 calls, last touched 5 years ago)
- [x] Pre-needs (2 calls, last touched 5 years ago)
- [x] Save in Progress forms (4 calls, last touched 20 months ago x3, 4 years ago for x1)
- [x] GI Bill (7 calls, anywhere between 9 months ago and 6 years ago)
- [x] Financial Status (6 months ago)
- [x] Facility locator (2 calls, last touched 3-4 years ago)
- [x] Claims Status (last touched 6 years ago)
- [x] Disability Benefit [2346] (last touched 2 years ago)
