### ISSUE TITLE
[FE] My VA audit UX improvements: Update secondary link logic in Claims and appeals section

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#48713]
## Background
Per feedback from Midpoint review, we need to revise our logic around secondary links and how they display in the **Claims and appeals** section on My VA. Currently we right-align secondary links when there is potential for the user to have _something_ to display on the left, immediately below the section header. Feedback from Design and A11y is to maintain right-aligned position (on desktop).

Feedback on this topic can be found in these tickets:
* #48655 -- Must feedback, 4th bullet point
* #48676 -- Thoughts/questions section, 1st bullet point

## Tasks
- [ ] Change logic around secondary links in the Claims and appeals section so that they are always right-aligned 
- [ ] Update tests
- [ ] Move to validation and notify PMs or Designer that it's ready for validation

## Acceptance Criteria
- [ ] Secondary links in the Claims and appeals section on My VA are right-aligned in all states/use cases

## Validation
- **_Who can validate this ticket? (FE, BE, Design, PM)?_** any team member
- **_How can this work be validated?_** log into staging and confirm secondary links are right aligned for all states: when user has a recently updated claim, when a user does not have a recently updated claim, and error state

**Comment by aagosto90** [comment]
Something to consider that I thought of and wanted to note here is we're now adding a section that doesn't contain any dynamic content (education and training) so if all secondary links will appear on the right all the time, we have to think of what we would display on the left for that section. @ajakabcin @ericasauv09

**Comment by ajakabcin** [comment]
Cancelling this - not making this change
