### ISSUE TITLE
[Design] My VA audit UX improvements: Update designs/docs to use new notification design system component in health care section on My VA

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#48718]
## Background
Per feedback from Midpoint review, we learned we can use the notification component that Angela designed and submitted to the design system (it was approved!). This ticket is to update designs and documentation to indicate use of new notification component instead of "warning alert component" on My VA in the Health care section. (_I believe the health care section is the only "in-line" location where the "warning alert component" is currently used._)

Feedback on this topic can be found in these tickets:
* #48655 -- Should section 

## Tasks
- [x] Update designs/sketch files to show new design system notification component (instead of "warning alert component") for in-line notifications
- [x] Update FE documentation to show and explain use of new design system notification component (instead of "warning alert component")for in-line notifications
- [x] PM's to make sure corresponding FE tickets not already in flight/complete are updated as needed to reflect updated notification component

## Acceptance Criteria
- [x] Sketch files and documentation are updated to indicate use of new notification component (instead of "warning alert component") for in-line notifications

## Validation
- **_Who can validate this ticket? (FE, BE, Design, PM)?_** any team member
- **_How can this work be validated?_** check documentation see that it's updated

**Comment by aagosto90** [comment]
Just FYI because I'm not sure if all of you are aware of how this process works for new components and I just learned this information - Taylor can code the new notification component and use it on our page and it doesn't need to be totally perfect and design system ready. Once the platform team is able to work on this, they will utilize his code to add it to the design system and make any variations and modifications they deem necessary. @tmitchellgcio If you want to chat with an engineer who has coded new components before, let me know and I'll connect you with someone!

CC @ajakabcin @ericasauv09 @Samara-Strauss

**Comment by ajakabcin** [comment]
Thanks @aagosto90 ! Definitely helpful info to know, I'm sure that will factor into @tmitchellgcio 's thinking when we groom/estimate this tomorrow

**Comment by aagosto90** [comment]
[Onsite notifications documentation updated here.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/frontend-documentation/notifications-frontend-documentation.md)
[Inline notifications for health care messages updated here.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/health-care-FE-documentation.md#if-a-user-has-unread-messages-from-a-health-care-providers)
I also updated Taylor's tickets to include these links but will keep this ticket open until you can validate that he has everything he needs in his implementation tickets @ajakabcin @ericasauv09

**Comment by ajakabcin** [comment]
Looks good @aagosto90 ! Confirmed the corresponding FE tickets are good to go - thank you!
