### ISSUE TITLE
[Design, FE] My VA Audit UX Improvements: Confirm Flow of My HealtheVet Link

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#48710]
## Background
Based on Midpoint Review feedback we want to confirm that the “Visit My HealtheVet” link that appears in error state for Health care section opens in a new tab (I believe that is the correct/expected behavior). If it doesn’t, make that change in the FE. Ensure documentation reflects this behavior

## Tasks
- [ ] Confirm if My HealtheVet Link opens a new tab
- [ ] If not, make changes to ensure it does open a new tab
- [ ] Update documentation - design

## Acceptance Criteria
- [ ] The My HealtheVet link opens a new tab so users can easily navigate back to My VA

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_
- _How can this work be validated?_ Validate in Staging if possible

**Comment by aagosto90** [comment]
Updated [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/health-care-FE-documentation.md#error-state-1-the-health-care-api-call-fails-cant-tell-if-user-has-va-health-care-or-not)
