### ISSUE TITLE
[Design] Payment info v2: Revise logic around secondary links

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#48716]
## Background
Per feedback from [My VA audit UX improvements' Midpoint review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42601), we need to revise our logic around secondary links and how they display. Currently we right-align secondary links when there is potential for the user to have _something_ to display on the left, immediately below the section header. Feedback from Design and A11y is to maintain right-aligned position (on desktop).

Feedback on this topic can be found in these tickets:
* #48655 -- Must feedback, 4th bullet point
* #48676 -- Thoughts/questions section, 1st bullet point

## Tasks
- [ ] Update designs/sketch to show secondary links right-aligned in all states for Outstanding debts and Benefit payments sections
- [ ] Update FE documentation to indicate secondary links right-aligned in all states
- [ ] PMs update test case documentation

## Acceptance Criteria
- [ ] Sketch files and documentation are updated to show right-aligned secondary links

## Validation
- **_Who can validate this ticket? (FE, BE, Design, PM)?_** any team member
- **_How can this work be validated?_** check documentation see that it's updated
