### ISSUE TITLE
[FE] My VA audit UX improvements: Update secondary link logic in Health care section

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#48714]
## Background
Per feedback from Midpoint review, we need to revise our logic around secondary links and how they display in the **Health care** section on My VA. Currently we right-align secondary links when there is potential for the user to have _something_ to display on the left, immediately below the section header. Feedback from Design and A11y is to maintain right-aligned position (on desktop).

Feedback on this topic can be found in these tickets:
* #48655 -- Must feedback, 4th bullet point
* #48676 -- Thoughts/questions section, 1st bullet point

## Tasks
- [ ] Change logic around secondary links in the Health care section on My VA so that they are always right-aligned 
- [ ] Update tests
- [ ] Move to validation and notify PMs or Designer that it's ready for validation

## Acceptance Criteria
- [ ] Secondary links in the Health care section on My VA are right-aligned in all states/use cases

## Validation
- **_Who can validate this ticket? (FE, BE, Design, PM)?_** any team member
- **_How can this work be validated?_** log into staging and confirm secondary links are right aligned for all states in the Health care section: when user has a upcoming appointment, when they don't have an upcoming appointment, when they have messages, when they don't have messages, and error states

**Comment by ajakabcin** [comment]
Cancelling this - not making this change
