### ISSUE TITLE
[Design] Onsite Notifications: Update designs and documentation to use new notification design system component instead of "warning alert component"

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#48725]
## Background
Per feedback from [My VA audit UX improvement Midpoint review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42601), we learned we can use the notification component that Angela designed and submitted to the design system (it was approved!). This ticket is to update designs and documentation to indicate use of new notification component instead of "warning alert component" for onsite notifications on My VA.

Feedback on this topic can be found in these tickets:
* #48655 -- Should section 

## Tasks
- [x] Update designs/sketch files to show new design system notification component (instead of "warning alert component")
- [ ] ~Update FE documentation to show and explain use of new design system notification component (instead of "warning alert component")~ FE documentation updates tracked in #48389 

## Acceptance Criteria
- [x] Sketch files and documentation are updated to indicate use of new notification component (instead of "warning alert component")

## Validation
- **_Who can validate this ticket? (FE, BE, Design, PM)?_** any team member
- **_How can this work be validated?_** check documentation see that it's updated

**Comment by aagosto90** [comment]
[Updated documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/frontend-documentation/notifications-frontend-documentation.md)
