### ISSUE TITLE
[FE] Notification design system comp.: Build new notification component

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#48726]
## Background
Per feedback from [My VA audit UX improvement Midpoint review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42601), we learned we can use the notification component that Angela designed and submitted to the design system (it was approved!). **This ticket is to build the component. Implementing the component for onsite notifications is in separate ticket ([54812](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54812))**

**Documentation references:**
- [Onsite notifications FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/mvp/frontend-documentation/notifications-frontend-documentation.md)
- [Design system submission - #1181](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1181)
- [Sketch design file](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/BE3AD487-CCBD-4DAB-96F2-18A5F90D063F)

**Feedback on this topic can be found in these tickets:**
* #48655 -- Should section 
* #46536

## Tasks
- [ ] Build new component (see Angela's [note](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48718#issuecomment-1290905598))
- [ ] Update tests
- [ ] Move to validate and inform PMs and designer that it's ready for validation
- [ ] Submit to design system library for review 

## Acceptance Criteria
- [ ] New notification component is submitted to design system for review

## Validation
- **_Who can validate this ticket? (FE, BE, Design, PM)?_** any team member
- **_How can this work be validated?_** log into staging with users 11 or 220 to validate use of new component

**Comment by ajakabcin** [comment]
Need to do together with #48719

**Comment by allisonlu** [comment]
i've completed the styles of the component, but still wrangling with the dismissal logic (state management w Redux, handling multiple notifications, removing entire Notifications section when there are no more notifications)

**Comment by allisonlu** [comment]
![Screenshot 2023-04-07 at 5 14 04 PM](https://user-images.githubusercontent.com/8542413/231493595-24c18c75-bc4d-4fc6-b94b-979c08cb3a84.png)

**Comment by allisonlu** [comment]
hey @humancompanion-usds! i've included a screenshot of what i've built/styled so far. i'm going to work on ironing out the "mid-stack" logic in [another ticket for our upcoming sprint](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56767). just wanted to keep you in the loop with what the My VA team is up to!

cc: @ajakabcin
