### ISSUE TITLE
[eFSR] Your VA Benefits Enhancement

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#48742]
## Issue Description
Update VA Benefit information page with the ability to edit listed benefits. 

~~[Old Design](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/146446310/simulate/sitemap?mode=i)~~

[Mural for edit functionality](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1671734127581/dc254b12e788570c946af60bc55338b0045aea03?invited=true&sender=87471762-a55a-4514-88d1-4cb4b90f7fb6)

**NOTE:** Be sure to use Mural for up to date mocks, the following screenshots are just for quick reference.
<details><summary>Overview Page (click to expand):</summary>

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/0b7ed1c8-f3ca-4e6f-aeb7-ca3ba034d356)
</details>

<details><summary>Edit Page (click to expand):</summary>

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/4113354d-4d8a-458f-b26e-6017e9997c58)
</details>

---
## Tasks
- [ ] Add the following pages:
  - [ ] Overview page 
  - [ ] Edit page
- [ ] Update efsr specific e2e testing
  - [ ] Include edit loop

## Acceptance Criteria
- [ ] Page matches design and functionality
- [ ] All new and existing tests are passing

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by denisecoveyduc** [comment]
@Dr-Pongo @Option Select Please review #24403

**Comment by HeatherRienks** [comment]
Let's move to sprint 92

**Comment by Dr-Pongo** [comment]
Updated and moved to ready column with new sizing and requirements
