### ISSUE TITLE
Profile Team | Sprint 87 | Nov 16 - Nov 29 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#48746]
## PTO/OOO/Unavailable

Sharon: 11/16, 11/17, 11/24  + 11/25
Erica: 11/24
Liz: 11/23 - 11/25; 11/29 (1/2)
Christina: 11/24 - 11/25
Adam: 11/24
John: 11/24 (Thanksgiving)
Tom: 11/24 - 11/25
Samara: 11/23 - 11/25

## Retro Board is open:

[Sprint 86](https://www.reetro.app/board/6203c8f3edfa6100174612bb/63582aad20452ba44e70fcfa)

#### FE - John
- [x] #46195 Use TTY Prop in Telephone Component (1 pt) (will also look for any act'l screens where TTY needs to be updated #49843)
#### Design - Liz
- [x] #49464 Error States Mocks (3 pts)
- [x] #49589 Notify Settings | Mobile # + Screenreader (1 pt)

## General/Tech Debt

- [x] **#31410 Update alert for when a user is editing a section (2 pts) (moved over from Sprint 86)**
- [x] #49385 Military Info| Update FAQ (1 pt)
- [x] #49835 Military information: Update NoServiceHistoryAlert (added 11/18) (1 pt)

#### FE - Adam
- [x] #49468 React RadioButtons Deprecated (3 pts)
- [x] #49344 Analytics Dashboard | Events for Contact info (1 pt)
- [x] #49647 Remove BAI Feature Flag (and others) (3 pts)
- [x] #47841 Fiduciary Flag Needs to Gate all of Profile (3 pts)

#### Backend - Tom
- [x] #49653 Discovery | Connect Local Environment to Staging (5 pts)
- [x] #48695 Notifications | Multiple Requests Issue (2 pts) 
- [x] #49901 Personal Information returning 400 Bad Request (2 pts)

#### Design - Christina
- [x] #49615 Account Security mocks (part 2 of  #47299) (3 pts)
- [x] #49616 Nametag | Update Documentation (4 pts)
- [x] #48785 Military page | DD214 - documentation updates (1 pt)
