### ISSUE TITLE
[eFSR] Resolution Option Explainer Enhancement

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#48749]
## Issue Description
Add Resolution option explainer to FSR that matches [the design](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/150789024/simulate/sitemap?mode=i)

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/6aa36599-b525-4561-8303-5971288bdb6d)

---
## Tasks
- [ ] Add Resolution option explainer page behind feature flag

## Acceptance Criteria
- [ ] Resolution option explainer page added behind enhancement feature flag
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by OptionSelect** [comment]
This is rolling over due to finishing the work on Employment History.
