### ISSUE TITLE
[BE] Modify Claims Service Object to get PatientICN from Redis

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#48740]
## Description
Currently, the BTSSS Claims API service object gets `patientICN` from the controller. As part of this task, modify the service object to read `patientICN` from redis

## Tasks
- [ ] Change method input parameters
- [ ] Read `patientICN` from Redis
- [ ] Define common interface to read `patientICN` from Redis

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
