### ISSUE TITLE
[eFSR] Bankruptcy History Enhancements 

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#48748]
## Issue Description
Update FSR Bankruptcy Page to match new design
[UXPin](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/146487297/simulate/sitemap?mode=i)

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/3e68349a-d94d-413d-a130-768ab59a030c)

---
## Tasks
- [ ] Update Bankruptcy Details Page

## Acceptance Criteria
- [ ] Bankruptcy Details page matches new design (behind Enhancement Flag)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
