### ISSUE TITLE
[Platform Tech Team 2] Onboarding checklist for Lee Warrick

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#48755]
## Overview
Welcome to the VA.Gov Platform.  This ticket is a checklist and guide to help you get access to communications, documentation, and tools used by technical project teams. 

### EQIP / PIV / RA

_EQIP - Electronic Questionnaires for Investigations Processing
PIV - Personal Identity Verification
RA - Remote Access_

**If you're new to the VA, an EQIP submission is needed to obtain VA credentials and a PIV card**
- [x] Submit EQIP 
- [x] Obtain PIV card
Note: AWS access can be granted once the EQIP has been submitted _before the PIV card is received_
- [x] Set up [TMS](https://www.tms.va.gov/secureauth35/SecureAuth.aspx) account and take required trainings
- [x] Ensure COR submits a request on your behalf for RA to the VA network 

### Communications 

**Platform coordination**
- [x] Share your calendar with VSP teams: va-vsp-team@oddball.io and  vsp-team.group@adhocteam.us
- [x] Ensure you're in Google Groups [va-vsp-team](https://groups.google.com/a/oddball.io/g/va-vsp-team) and [va-vsp-engineering](https://groups.google.com/a/oddball.io/g/va-vsp-engineering). 
- [x] Use `/support` in #vfs-platform-support to request access.
- [x] Ensure you have access to the Google Drive folder ["VSP team"](https://drive.google.com/drive/u/0/folders/0AJ6yVhfytxhFUk9PVA)
- [x] DSVA Slack Workspace
  - [x] #platform-cop-devops
  - [x] #platform-team
  - [x] #vfs-all-teams

**Team coordination**
- [x] [Meet the team](https://vfs.atlassian.net/wiki/spaces/TT2/pages/2401796102/Team+Charter+WIP#Meet-the-team)
- [x] [How we work](https://vfs.atlassian.net/wiki/spaces/TT2/pages/2401796102/Team+Charter+WIP#How-we-work-together)
- [x] [Current project](https://app.zenhub.com/workspaces/platform-tech-team-2-633efe4ca5a428e5294d7ade/issues/department-of-veterans-affairs/va.gov-team/47043)
- [x] [ZenHub Kanban Board](https://app.zenhub.com/workspaces/platform-tech-team-2-633efe4ca5a428e5294d7ade/board?repos=133843125,194202180) for Platform Tech Team 2

### Documentation
- [x] [Request access to tools](https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html) documentation on the Platform Website
- [x] [Confluence](https://vfs.atlassian.net/wiki/home)
  - [x] [Platform Tech Team 2 space](https://vfs.atlassian.net/wiki/spaces/TT2/)
  - [x] [VA.Gov Platform Manual](https://vfs.atlassian.net/wiki/spaces/OT/pages/2354315287/Platform+Infrastructure+Manual+WIP)

**Platform overview and design**
- [x] [Overview of the VA.Gov Platform](https://depo-platform-documentation.scrollhelp.site/getting-started/Welcome.1255276574.html)
- [x] [VA.Gov Platform system design and architecture](https://vfs.atlassian.net/wiki/spaces/OT/pages/2354315287/VA.Gov+Platform+Manual+WIP#System-design-and-architecture)

### Developer tools 
- [x] GitHub
  - [x] Join the ['department-of-veterans-affairs' organization ](https://github.com/department-of-veterans-affairs)
  - [x] Get access to the [devops repo](https://github.com/department-of-veterans-affairs/devops)
- [x] [SOCKS](https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html) - _for remote access to the following apps:_
  - [x] [Jenkins](http://jenkins.vfs.va.gov/)
  - [x] [Sentry](http://sentry.vfs.va.gov/)
  - [x] [Grafana](http://grafana.vfs.va.gov/)
  - [x] [Argo CD](http://argocd.vfs.va.gov/)
  - [x] [Prometheus](http://prometheus-prod.vfs.va.gov:9090/prometheus/graph?g0.range_input=1h&g0.expr=&g0.tab=0) - _not used directly but can be useful to understand legacy metrics gathering_
- [x] [Pagerduty](https://dsva.pagerduty.com/) - _ask a team member for access_
- [x] [Keybase](https://keybase.io/)
- [x] [Datadog](https://vfs.atlassian.net/wiki/spaces/OT/pages/2233598117/Get+access+to+Datadog) - _ask your PM or TL to submit a request on your behalf_
- [x]  [AWS access request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Coperations%2Cops-access-request&template=aws-access-request.yml&title=Access+for+%5Bindividual%5D) - _can be submitted early, but won't be approved until EQIP submission is verified_

_Once your PIV card has been obtained:_ 
- [x] [Citrix Access Gateway (CAG)](https://citrixaccess.va.gov/vpn/index_citrix_splash.html)
- [x] [Venafi](https://vfs.atlassian.net/wiki/spaces/OT/pages/1719009302/Venafi+Gain+access+to+manage+internal+TLS+certificates)

**Comment by jhouse-solvd** [comment]
@mynar7 - Here's the ticket w/ onboarding items that might be helpful for you. Let me know if you come across things that aren't listed. Thank you!

cc: @ph-One

**Comment by jhouse-solvd** [comment]
@mynar7 and I went through these together, and he's all set! If we run into issues w/ CAG, we'll open a new ticket. 

This can be closed.
