### ISSUE TITLE
FE | Profile | Research Recommendations | Notifications Settings Spacing

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#48753]
## Background

Based on the designs Liz created in this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48396) we need to update the spacing in the notifications settings page. The design mock up can be found [here](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/jg8yMMb)

## Tasks
- [ ] Make Changes based on designs
- [ ] Conduct Unit tests 
- [ ] Run E2E tests covering current code and regression
- [ ] Notify PM if this needs to be deployed to Staging behind feature flag
  

## Acceptance Criteria
- [ ] Complete all unit testing
- [ ] End-to-end tests showing 0 violations
- [ ] All axe checks pass
- [ ] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [ ] Confirm PM has opened a new ticket to deploy changes to Production using feature flag, if needed

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)? Anyone
- How can this work be validated? 
- What updates need to be made (e.g. product outline, use cases, contact center guide)

## Associated Tickets
- #48396

**Comment by SKasimow** [comment]
@andaleliz - can you validate this follows the specs you laid out? Thx

**Comment by andaleliz** [comment]
I took a look at this on staging and it's _so close_.  There are a couple of things I'm wondering if we can tweak, @adamwhitlock1 :

1. Can the "update mobile phone" link be on its own line?
2. Is it possible to move the "manage your health care email notifications on MHV" link so it aligns with the health care heading, and isn't nested like the notification items are?  This is less important than the first item. If it's more involved than moving the link outside it's parent, or applying an existing utility class, don't worry about it.

**Comment by adamwhitlock1** [comment]
I tweaked the update link in staging now and it should be good to go now.

Note on adjusting the spacing akak #2 of the comment request

That one unfortunately isn’t going to be easy to adjust the spacing on. It is inside the main container so inherits that padding. I tried to add negative margin on it to push it out on the x axis, but it wasn’t displaying correctly. So not going to mess with that just the update link.

Here is what user 15 in staging looks like in mobile view

![Screen Shot 2022-11-29 at 5.54.00 PM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/b6f07c80-2c0e-48a7-87e1-1f2d5cb24761)

**Comment by SKasimow** [comment]
@andaleliz @adamwhitlock1 - can we close this? Sounds like Adam made the changes he could for now...

**Comment by andaleliz** [comment]
Yes, from my perspective it's good to go.

**Comment by SKasimow** [comment]
@adamwhitlock1 - is "update" supposed to be on its own line (seeing below in prod and staging):

![Screen Shot 2022-12-09 at 3.38.26 PM.png](https://images.zenhubusercontent.com/5fb57aafa11eae0592a15cb1/93f2cef2-90f5-4242-907e-cc9898fcbc6b)
