### ISSUE TITLE
[eFSR] Real Estate Enhancements 

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#48752]
## Issue Description
Update Real Estate pages to match [the new design](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/146385053/simulate/sitemap?mode=i)

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/34ca0cf0-a643-48a3-9eff-bad804c5dde1)

---
## Tasks
- [ ] Update Real Estate pages to match new design

## Acceptance Criteria
- [ ] New Real Estate pages are implemented behind feature flag
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
@OptionSelect - I know you mentioned this ticket might need to be bumped up from a 3 to a 5. Adding as a FYI for @denisecoveyduc. 
Any updates you have would be great! Thx!

**Comment by OptionSelect** [comment]
Updated this ticket to 5 per our convo. Level of effort was more than expected due to nature of CustomPage in our form system.

**Comment by OptionSelect** [comment]
Ticket rolling due to the following reasons. Back end issues throughout last week, missing a day for closing on house. 

I am close to the end, Andrew rightfully noticed some issues on review page I'm finishing off. Tests pass and behavior exists it just doesn't look right at the tail end!
