### ISSUE TITLE
Design | UI Alerts for Editing Contact Info | Update Design Files

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#48757]
## Background  

Per comment in ticket #31410 we are updating the content for one of the alerts on the contact page to this:

- [Desktop](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/v/waVZjj/a/OmlnPxp)
- [Mobile](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/v/dMz8DZ/a/pamAp4p/r/bWjPW0)

## Tasks
- [x] Update sketch files 
- [x] Update use cases
- [x] Update user flows
- [x] Update CC guide

## Acceptance Criteria
- [x] Above tasks are complete
- [ ] Notify PM to send updated CC guide to poc

**Comment by andaleliz** [comment]
Hi @SKasimow - what needs to be updated about the design files? Otherwise I'm clear on what the tasks are.

**Comment by SKasimow** [comment]
@andaleliz - just using a standard list of what needs to be updated so if Sketch is all set, just ignore - or put a checkmark :)

**Comment by andaleliz** [comment]
Hey @SKasimow and @ericasauv09 this is all complete. I updated the text and screenshots in the contact center guide for this since it was such a small change.  Good to go.

**Comment by SKasimow** [comment]
Thanks Liz!
