### ISSUE TITLE
Remove broken link from education hub landing page and left nav

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#48778]
## Issue Description

We have a broken link on the [education hub landing](https://www.va.gov/education/) page and in the left nav that we need to remove. 

On the landing page, in the More information and resources section, we want to remove the entire content and link for "My Story—how Veterans and service members use the GI Bill."

![Screen Shot 2022-10-26 at 10.15.19 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/20a9672c-0fc9-44fc-8698-9253b21c6990) 

In the left nav, we need to remove the link "How others use the GI BIll" under the More resources section.
![Screen Shot 2022-10-26 at 10.16.20 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/ca367a07-8561-49c3-b0aa-aaa0c016cdfb)

## Tasks
- [x] Remove text and link from hub landing page
- [x] Uncheck the enabled box in the education menu to remove link from left nav
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Broken link is no longer on live site

**Comment by megzehn** [comment]
I reviewed the changes and re-published nodeID=71. 

CC @RLHecht 

Thanks!

**Comment by RLHecht** [comment]
This is complete. Closing ticket!
