### ISSUE TITLE
FE | Profile | Add Link for DD214 on Military Page

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#48782]
## Background

["DD214" is the second most searched term from the profile](https://analytics.google.com/analytics/web/?authuser=0#/report/content-site-search-pages/a50123418w177519031p176188361/_u.date00=20200101&_u.date01=20200707&_.useg=builtin1&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.searchStartPage:www.va.gov~2Fprofile~2F/). It's reasonable to assume that users expect to see information about their DD214 in the profile under "Military information." While we can't add the DD214 itself because we don't have access to it, we can at least link to information that helps guide users on how to get it.

## Tasks

- [x] Update the Military info page to match the following mocks:
[Desktop](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/a/g0YO03a) & [Mobile](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/a/DPDA8Wk)
- [x] Link should go to [records page](https://www.va.gov/records/get-military-service-records/)
- [x] Conduct Unit tests 
- [x] Run E2E tests covering current code and regression
- [x] All axe checks pass

## Acceptance Criteria
- [x] Complete all unit testing
- [x] End-to-end tests showing 0 violations
- [ ] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated

## Validation

** Related Ticket: Design #11053 and Update FAQ for DD214 #46564

**Comment by jcatergovy** [comment]
@SKasimow @cgednalske This has been merged and should hit staging this afternoon

**Comment by SKasimow** [comment]
Hi @jcatergovy - I just tested with staging user 36 and don't see DD214 on Military page; did the PR go through for this?

**Comment by SKasimow** [comment]
Hey @jcatergovy - I see the DD214 link in staging now but looks like the FAQ that should be above it (says: What if I don't think my military information is correct) is no longer there:

![Screen Shot 2022-11-21 at 6.12.01 PM.png](https://images.zenhubusercontent.com/5fb57aafa11eae0592a15cb1/128fbc19-8502-459d-b9a4-9024f648ff44)

**Comment by jcatergovy** [comment]
@SKasimow That screenshot is from a user that generates a NoServiceHistoryAlert where the FAQ doesn't display.  Here's a screenshot of it without an alert.  ![image.png](https://images.zenhubusercontent.com/632e0024b571f3ae02607148/f6133829-0e0c-4eb1-8dbc-859ec3834a51)

**Comment by SKasimow** [comment]
Oh - that's interesting! I didn't realize the FAQ was conditional. Thanks for clarifying...guess we can close this out now.

**Comment by Samara-Strauss** [comment]
Posting some exciting stats:

- In the week after launch, the military info page got about 13K views, and over 10% of those views interacted with the new link. I would say this bears out our hypothesis that people expected to find this information here.
![image](https://user-images.githubusercontent.com/34068740/204644558-d1e19348-8a49-42d5-9db4-9db6438514e6.png)
- Also, searches for "DD214" ranked in the [number 1 spot the week before launch](https://analytics.google.com/analytics/web/?authuser=0#/report/content-site-search-pages/a50123418w177519031p176188361/_u.date00=20221115&_u.date01=20221121&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=50&_r.drilldown=analytics.searchStartPage:www.va.gov~2Fprofile~2Fmilitary-information~2F/), and [dropped to number 18 the week after launch](https://analytics.google.com/analytics/web/?authuser=0#/report/content-site-search-pages/a50123418w177519031p176188361/_u.date00=20221122&_u.date01=20221128&explorer-table.plotKeys=%5B%5D&explorer-table.rowStart=0&explorer-table.rowCount=50&_r.drilldown=analytics.searchStartPage:www.va.gov~2Fprofile~2Fmilitary-information~2F/).
