### ISSUE TITLE
Schedule Platform Orientation in Calendly for 2023

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#48787]
## User Story
As a Governance team member supporting Platform Orientation, I want to make sure the teams responsible for orientation are signed off on the orientation timeslots for 2023 so that I can commit to the changes in Calendly.

Assignee: @shiragoodman 
Peer Reviewer: @CherylEvans 

## Description
Calendly is the tool we use for scheduling the Platform Orientation sessions. Although Calendly allows us to specify a time of day and day of the week, we need to go in and manually opt out of the weeks orientation will not be hosted. For example, if General Orientation is the 1st Tuesday of the month at 3:00pm, then the 2nd, 3rd and 4th Tuesdays need to be marked as unavailable.

## Impacted Artifacts
[Orientation Sessions](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2062024864/Orientation+Sessions) confluence page
[Orientation Sessions](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions) Platform Website page 

## Tasks
- [x] Confirm with Meeting/Zoom host (documented in [Orientation Session Confluence page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2062024864/Orientation+Sessions)) that monthly date/time still works for 2023 for each Orientation session: 
   - [x] General Orientation
   - [x] Design & Research Orientation
   - [x] Accessibility Orientation
   - [x] QA Orientation
   - [x] Analytics Orientation
   - [x] Design System/Forms Library Orientation
   - [x] Back-end Orientation
   - [x] Front-end Orientation
**Note:** General, QA and Accessibility Orientation will have Shira as Zoom host for all, then Shira, Ian and Brian as meeting host, respectively.
- [x] Once complete, update the [Orientation Sessions](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2062024864/Orientation+Sessions) confluence page and the [Orientation Sessions](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions) Platform Website page.
- [x] Notify @shiragoodman of any changes so she can make the changes to Calendly.
- [x] Shira to update Calendly Orientation Sessions for 2023.
- [x] After Calendly is up to date, contact all Zoom/orientation hosts and ask meeting/zoom host to verify if any 2023 orientation sessions would fall on a holiday. If so, find an alternate time (typically the week before or the week following, same time, same day of the week). If not, ask them to sign up for their Orientation session for the full year.
- [x] Point all Orientation session hosts to the [Roles & Responsibilities section](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2062024864/Orientation+Sessions#Roles-and-Responsibilities) of the Confluence Orientation Sessions page for their review/reminder

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] All 2023 orientation sessions are scheduled 
- [ ] VFS teams are able to sign up for their necessary orientation sessions on the correct date.

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@CherylEvans you're assigned as peer reviewer, but I'm not sure what there is for you to peer review since you can't access Calendly. Any concerns/issues if I just close this out?

**Comment by CherylEvans** [comment]
@shiragoodman No concerns/issues whatsoever. Feel free to close it out.  :-)
