### ISSUE TITLE
Add Sara Sterkenburg to Contact Us page and remove Jim

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#48786]
****Assignee:** @sterkenburgsara 
**Peer Reviewer:**** @allison0034 

## Description
Add Sara Sterkenburg to Contact Us page as the IA for Governance team. Remove Jim Ryan.

## Impacted Artifacts
[Contact Us](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/contact-us)

## Tasks
- [x] Edit the page to remove Jim and add Sara

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Sara is listed as the IA for Governance team on Platform Website

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by sterkenburgsara** [comment]
FYI @shiragoodman Also updated [this page](https://vfs.atlassian.net/wiki/spaces/PPST/overview).

**Comment by sterkenburgsara** [comment]
@allison0034 I published, but it hadn't synced to Platform yet (that's why I didn't tag you). Just saw on #platform-confluence channel that it is now live.

**Comment by allison0034** [comment]
Looks good! You can close.
