### ISSUE TITLE
Add IA design as requested artifact at Midpoint and Staging

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#48780]
## User Story
As a Governance team member supporting IA for the Collaboration Cycle Staging Review, I want to see the IA design for the VFS product so that I can be sure to validate the products IA against the IA design.

As a Governance team member supporting IA for the Collaboration Cycle Midpoint Review, I want to see the current IA design for the VFS product, even if it's incomplete, so that I can be sure to align my feedback with the IA design.

Assignee: @sterkenburgsara 
Peer Reviewer: @allison0034 

## Description
The IA for Sitewide creates all IA designs for VFS teams and saves them in the [IA Reviews github folder.](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/information-architecture/ia-reviews) Although  IA for Governance is able to review this folder for the current design, we'd like to hold the VFS team accountable for sharing their IA design and ask them to submit it as a requested artifact at Midpoint Review and Staging Review.  The purpose of this ticket is to modify VFS facing guidance to request the IA design at both touchpoints

## Impacted Artifacts
[Platform Website Midpoint Review touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)
[Platform Website Staging Review touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)
[Midpoint Review code block](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities#Midpoint-Review-code-block)
[Staging Review code block](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities#Staging-Review-code-block)

## Tasks
- [x] Modify Midpoint Review and Staging Review touchpoint pages to add IA design as requested artifact
   - [x] Also remove ":" at the end of the bullets under QA and Content artifacts for Midpoint Review
- [x] Modify both code blocks using the same formatting 
- [x] Review existing Collab Cycle Request tickets and modify (if necessary) to add new IA artifacts for Midpoint and Staging

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS teams are asked to share their IA design at Midpoint and Staging Review

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
FYI @sterkenburgsara @allison0034 more unplanned sprint work. Please review and let me know if you have any questions.

**Comment by sterkenburgsara** [comment]
@shiragoodman re: the GH folder containing example IA reviews - should we request an update to this page to read "sitewide content & IA" (vs. The VSP IA Team) and update the IA point-person to @heyjoni?

**Comment by shiragoodman** [comment]
@sterkenburgsara I wouldn't worry too much about [this page](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/information-architecture) as it is not being maintained, and Platform does not direct VFS teams to it. There are many things wrong with the page aside from the team name and point person. If you're concerned, we can put a warning at the top stating that this page is no longer maintained and sections of the page may be incorrect. Ideally we'd move the IA designs folder so it's no longer nested under this page (and the Platform folder) but moving md files in github is a huge pain, and I'm not really sure if it's worth the effort (especially since all the url links where the IA design has been shared with VFS teams would change). Let me know if you'd like to discuss further.

**Comment by sterkenburgsara** [comment]
@shiragoodman thanks - sounds good.

**Comment by sterkenburgsara** [comment]
@allison0034 I have draft pages of [midpoint review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2422964225/48780+Sara+Draft+Copy+of+Midpoint+review) & [staging review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2423685121/48780+Sara+Draft+Copy+of+Staging+review) ready for your editing eyes.

**Comment by allison0034** [comment]
Hi @sterkenburgsara , all the info is correct but I would rec trimming down the content a little. The reason being is that we know from user testing that our cc request ticket is a very long ticket with lots of info. We have trimmed back where we can to try to reduce overwhelming the PMs or even us when we have to read through these. You could always work with Cheryl or look at the way we have written the other artifacts (QA/Accessibility ), but I think you could cut unnecessary words out pretty easily.

- IA artifacts
If your team has worked with Sitewide Content & IA and undergone an IA review, please include a link to any IA artifacts created as part of that process (user flows, diagrams, plans for site structure, wayfinding/navigation changes, anticipated redirects, etc.)

**Comment by sterkenburgsara** [comment]
@allison0034 Editing & consulting Cheryl. I'll send you another draft soon, thank you!

**Comment by sterkenburgsara** [comment]
@allison0034 Fixed. Does this look better?

**Comment by sterkenburgsara** [comment]
@allison0034 @CherylEvans I wasn't sure, but Cheryl says yes. I know less about the environment of knowledge / what VFS teams expect than you all do. Thoughts?

**Comment by sterkenburgsara** [comment]
@allison0034 I edited the text (after consulting Joni Chan - sitewide IA), and published to platform. Could you review the changes when time allows? See here: [Midpoint review](https://vfs.atlassian.net/wiki/spaces/CC/pages/1781039167/Midpoint+review) and [staging review](https://vfs.atlassian.net/wiki/spaces/CC/pages/1810137181/Staging+review).

**Comment by shiragoodman** [comment]
@sterkenburgsara I didn't review the published page, but FYI, we do not mention any individuals by name outside of the Contact Us page. So if you're mentioning Joni on these pages, please edit it so it references her team and not her as an individual. Thanks!

**Comment by sterkenburgsara** [comment]
@shiragoodman it does not mention anyone by name :)

**Comment by allison0034** [comment]
@sterkenburgsara looks good! I think you need to update the code blocks still correct?
Midpoint Review code block
Staging Review code block

**Comment by sterkenburgsara** [comment]
@allison0034 no, these should be updated already.

**Comment by sterkenburgsara** [comment]
@allison0034 yes, just did that. Thanks!

**Comment by sterkenburgsara** [comment]
@shiragoodman modified all collaboration cycle tickets in the pipeline [to include IA artifact request] that are awaiting midpoint review or are before that stage. Did not update any tickets that are currently past midpoint review.
