### ISSUE TITLE
Draft a process flow for Intake of Mapping requests

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#48793]
## Issue Description
Draft a process flow for intake of mapping requests.

From A= a user thinks they might need some mapping done, to K= the required information has been submitted, to Z = the SDT team has prioritized this work.

Note: Explanation of A is out of scope, just that it exists.

[Mural for process brainstorming](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1666886472220/c097801ce764cd7e763461f50646f57f2e1c6f9d?sender=u4f7db1750f2355f805e60296)

## Tasks
- [x] Draft the steps involved in receiving a request through prioritizing the (understood) work
- [x] Validate brainstormed steps

## Acceptance Criteria
- [x] First draft is ready to share
