### ISSUE TITLE
[FE] Payment info v2: Implement/update analytics tags for GA tracking

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#48792]
## Background
We need to implement one new tag for GA tracking on payment info v2 and update the tag on the "manage your va debt" link. See [guidance](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48598#issuecomment-1292498848) in #48598 

## Tasks
- [x] Add tagging on the "Manage your VA bills" link within the copay card using the following

> event: 'dashboard-navigation'
> dashboard-action: 'view-link'
> dashboard-product: 'view-manage-va-bills'

- [x] Update tagging on "Manage your VA debt" link within the outstanding debts card using the following

> event: 'dashboard-navigation'
> dashboard-action: 'view-link'
> dashboard-product: 'view-manage-va-debt'

- [x] Coordinate with PM to request analytics team's assistance to QA the tagging (and make sure tagging on benefit payment section is working properly from previous implementation)
- [x] PM to work with analytics team to confirm we can see tracking flow through on our dashboard (GA and domo)

## Acceptance Criteria
- [x] Tags are implemented, tested and we can see analytics captured in GA and domo

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ Work with analytics team to confirm tags are implemented properly and that we can locate metrics coming through in GA and domo

**Comment by ajakabcin** [comment]
Not needed - implementation will be tracked in #48598

**Comment by tmitchellgcio** [comment]
Just merged please give about 30 min for this to show in staging

**Comment by ajakabcin** [comment]
requested validation yesterday from analytics team on this in the implementation request ticket - #48598

**Comment by ericasauv09** [comment]
Went to Analytics office hours and the events are coming through however they are not tagged properly and are missing the "view-manage-va-bills" and "view-manage-va-debt" tag in the event. Taylor found the issue and is going to make a fix for it asap and then we can revalidate.
