### ISSUE TITLE
Update Restore your GI Bill benefits link

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#48804]
## Issue Description

Stakeholder Tammy Hurley told us that they are moving a benefits.va.gov page that we currently link to on the [education hub landing page](https://www.va.gov/education/) as well as in the left nav. We need to update the link in both places.

The link to update is the last link in the Manage your Veterans education benefits section: Apply to restore your GI Bill benefits.

The new link should be: https://www.benefits.va.gov/GIBILL/Restoration.asp

## Tasks
- [x] Update link on landing page
- [x] Update link in left nav
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] New link is live on the site

**Comment by aliyahblackmore** [comment]
Hi @megzehn ! The link on the education hub landing page is ready for you! 

**Preview link**: http://preview-prod.vfs.va.gov/preview?nodeId=71

The left nav link still needs to be changed. Randi sent a message to CMS support about an error screen that appears when trying to edit. Will make the change once we have a solution!

**Comment by megzehn** [comment]
Thanks, @aliyahblackmore! I reviewed the changes and re-published nodeID=71.

**Comment by RLHecht** [comment]
These changes are now both live. Closing ticket!
