### ISSUE TITLE
Add Medallia Feedback Button to VA.gov Homepage

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#48805]
## Issue Description
_When we moved the the Medallia Feedback button to bottom of main on VA.gov pages earlier this year, there was an issue with the VA.gov homepage template that prevented us from adding it there. That template has been updated and the Public Websites team is requesting we add the Feedback button on the homepage._

---
## Tasks
- [ ] _Add Medallia Feedback button to VA.gov Homepage template at bottom of main_
- [ ] _Test functionality and design compliance_

## Acceptance Criteria
- [ ] _Medallia Feedback button is on VA.gov homepage and functioning/displaying correctly_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
In production 11/8/22
