### ISSUE TITLE
Create Tugboat Proof of Concept

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#48802]
## Issue Description
Iterating on the Tugboat discovery ticket,  attempt a basic implementation on the  vets-website repository. Create simplest  image possible viable to produce any  level preview image and notification from Tugboat.  

---
## Tasks
- [x] Add Tugboat config.yml  and  any other project settings to a branch of vets-website 
- [x] Get a working image of said vets-website in Tugboat 
- [x] Attempt/create a RI from the PR
- [x] Document process.
- [x] Document any side effects to repository or workflow

## Additional Tasks
- [x] Find out/Test if Tugboat creates a new or updated RI when a PR is updated (feature parity)

## Acceptance Criteria
- [x] A PR of vets-website with Tugboat
- [x] A Tugboat generated RI or records of specific points of failure
- [x] Confluence document with steps to replicate process
- [ ] Tugboat generated environments are deployed to EKS

**Comment by rmessina1010** [comment]
NOTES:

-  Tugboat RI  update automatically when the PR is updated, in addition, the comment with the instance link is also updated.  This feature is configurable.

**Comment by rmessina1010** [comment]
Tugboat PR: https://github.com/department-of-veterans-affairs/vets-website/pull/22376

- Reconfigured GH settings to point to CMS' onsite Tugboat set up, [https://tugboat.vfs.va.gov/](https://tugboat.vfs.va.gov/), as the SaaS version does NOT fit our needs.
- Default tugboat config  file
- Updated tugboat config  so as to get vets-website a RI with vets-website apps: see first successful RI : [https://pr22376-e8fwu2ti6w00krn31ycs6bjspb7dsdsx.tugboat.vfs.va.gov/](https://pr22376-e8fwu2ti6w00krn31ycs6bjspb7dsdsx.tugboat.vfs.va.gov/)
- Notes [https://vfs.atlassian.net/wiki/spaces/TT4/pages/2422112428/Tugboat+POC](https://vfs.atlassian.net/wiki/spaces/TT4/pages/2422112428/Tugboat+POC)

Next Steps
- How can we fetch cache from F3?
- Web Socket on Dev
- CORS/ Configure to use HTTPS (for tugboat)  instead of HTTP

**Comment by rmessina1010** [comment]
It looks like we might be  able to incorporate work done  by  RTT  with codeSpaces  to help us  with Drupal caches/content-build and vet-api. I am looking into this, but may need more expertise on Docker/Shell.

Reference:
[https://github.com/department-of-veterans-affairs/vets-website/blob/feature/30478-activate-codespaces-in-vets-website/.devcontainer/codespaces-create.sh](https://github.com/department-of-veterans-affairs/vets-website/blob/feature/30478-activate-codespaces-in-vets-website/.devcontainer/codespaces-create.sh)

**Comment by rmessina1010** [comment]
In order to confirm  that  Tugboat environment was accessible without SOCKS, I attempted to reach the Preview image via  the following methods:
terminal:
`curl: (6) Could not resolve host: tugboat-test-zfwxnkr6sllqtyhwkgkzeiobz5wqgepl.tugboat.vfs.va.gov`
Mobile and alternate machine(non-va), got "This site can’t be reached" errors.

Leading me to the conclusion  that, at least  the current hosting of Tugboat, is and works  behind  the proxy.

**Comment by rmessina1010** [comment]
As most issues have been addressed I am closing this ticket.
Notes for future tickets:
• Tugboat does NOT  export to EKS; Tugboat’s source images are not configured to be used in production environments which stands to reason as Tugboat purpose is specifically to deploy previews. (work arounds/change goals?)
• Could we reconfigure Tugboat to use other VPCs (as it is within its capabilities)
