### ISSUE TITLE
Run SiS locally with as little of vets-api as possible

### ISSUE THREAD

**Issue by ianhundere** [department-of-veterans-affairs/va.gov-team#48818]
## Description
In our attempts to move SiS out of BRD and into EKS, the first task is to get SiS running with as little of `vets-api` as possible.

options:
- start with more
  - stand `vets-api` up and begin removing unnecessary dependencies
- start with less
  - try and get just what is we need to get SiS up and running 

## Acceptance Criteria
- [ ] SiS runs albeit not fully working
- [ ] Document process for getting there
- [ ] Document anything else relevant to getting SiS pulled pulled of BRD

## More Info
[SPIKE: Research SiS Controller / Viability of moving SiS to a microservice](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/46952)

**Comment by ianhundere** [comment]
additional notes to componentize a Ruby controller for EKS:

1. Break down the controller into smaller, more manageable chunks of logic by extracting methods and classes.
2. Use dependency injection to decouple the controller from its dependencies, such as the model or service classes it uses.
3. Use a Ruby gem like Dry-Container to manage the dependencies for the controller.
4. Use a Ruby gem like Dry-AutoInject to automatically inject the dependencies into the controller.
5. Use a Ruby gem like Hanami-Controller to create a more modular and reusable controller structure.
6. Test the controller using a testing framework like RSpec to ensure that it still functions correctly after being componentized.
7. Deploy the controller to EKS using a containerization tool like Docker and a deployment tool like Kubernetes.

**Comment by ianhundere** [comment]
created a basic ruby app that connects to postgre (rds) and redis (elasticache) that provides the following info via the LB url: 
- ![screenshot.png](https://images.zenhubusercontent.com/624b40ac4980d90d75917e4c/41a985b8-0a28-4685-9476-bd4ad055395f)
