### ISSUE TITLE
Remove Feedback Button from Check-in Pages

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#48811]
## Issue Description
_The check-in team requested the Feedback button/survey be removed from their pages last year. They (Adrian Rollett) discovered it is still displaying on several of their pages (listed below). We need to remove it._

---
## Tasks
- [ ] _Remove the Medallia Feedback button/survey from the pages listed below:_
* {env.va.gov}/health-care/appointment-check-in/ and all sub-paths/query params
* {env.va.gov}/health-care/appointment-pre-check-in/ and all sub-paths/query params

## Acceptance Criteria
- [ ] _The Medallia Feedback button and survey are no longer visible and/or accessible on the 2 pages listed above_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
@aubreyarcangel to update situation here.

**Comment by aubreyarcangel** [comment]
This has been completed and will deploy today. https://github.com/department-of-veterans-affairs/content-build/pull/1355

**Comment by aubreyarcangel** [comment]
> This has been completed and will deploy today. [department-of-veterans-affairs/content-build#1355](https://github.com/department-of-veterans-affairs/content-build/pull/1355)

PR for Pre-checkin page https://github.com/department-of-veterans-affairs/va.gov-team/issues/48811
