### ISSUE TITLE
Logistics planning for on-site travel pay research

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#48824]
## Tasks

- [ ] Get data from Patrick on clinics under station's 637, 552, 756
- [ ] Determine location for trip
- [ ] Price out travel for two people
- [ ] Send to Sarah for approval

**Comment by benbrasso-agile6** [comment]
@sarahknoppA6 @loripusey 

https://docs.google.com/spreadsheets/d/1efDv0SriqY1rXQNlzU6xlupeRxOAvwLxcfdQF97NPm0/edit#gid=1543874242

For 1 person (Ben) to travel 12/12-12/15 = $1,267.53

For 1 person (Ben) to travel 1/3-1/6 = $1,205.53

The 12/12-12/15 cost assumes a couple things: 1) we've released travel pay by that time, and 2) flights haven't increased cost because of holiday. 

It might be a better approach to go roughly 30 days after travel pay release in order to hear from staff how things are going. So, maybe assume an early January trip to Dayton, OH. 

I feel like it's a doable trip with 1 person, but I'm also okay if we want to include 2 persons. If we want to estimate 2 persons for now, I'd recommend doubling the estimate (and then add some in case flight costs is more based on their distance). E.g., $1,205 + $1,600 = $2,805

**Comment by benbrasso-agile6** [comment]
Asking UX team if anyone would like to attend

**Comment by benbrasso-agile6** [comment]
@sarahknoppA6 here is the [estimate](https://docs.google.com/spreadsheets/d/1efDv0SriqY1rXQNlzU6xlupeRxOAvwLxcfdQF97NPm0/edit?usp=sharing)

@kellysmith1008 and I will be traveling.

The dates in the spreadsheet are of course tentative. I would think sometime in early to mid January is accurate.

**Comment by sarahknoppA6** [comment]
Thanks Ben. I am awaiting a template from Booz Allen Hamilton in order to submit the estimate. They also mentioned something about needing to know if the travel dates are before or after January 10th. Do we have confirmed dates at this time? @benbrasso-agile6 @kellysmith1008

**Comment by benbrasso-agile6** [comment]
We do not. I think our options are either: 1) we may need a few weeks to make that determination (and will then submit the estimate), or 2) if we need to submit the estimate now, then we could agree to travel past the 10th.

**Comment by loripusey** [comment]
what is the significance of January 10th?

**Comment by sarahknoppA6** [comment]
The BAH rep was uncertain as well- is going to get more information and get
back to me. It sounded like it may pertain to a funding deadline of some
sort, but I do not yet have more information.

**Comment by sarahknoppA6** [comment]
I will see if we can just submit what we have and go from there. Thanks all!
