### ISSUE TITLE
Tagalog translations for PACT Act updates on 10/26/22

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#48822]
## Issue Description

We made updates to the PACT Act R&S article about hazardous materials and presumptive conditions. We need to get these updates translated into Tagalog.

Word doc sent to translators: [https://app.zenhub.com/files/133843125/2f0ecdf0-26a8-475b-aa90-55af5e7dcfee/download](https://app.zenhub.com/files/133843125/2f0ecdf0-26a8-475b-aa90-55af5e7dcfee/download)

## Tasks
- [x] Send text to translators (Randi)
- [x] Update Tagalog page (Aliyah)
- [x] Review (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Tagalog page has most recent updates

**Comment by RLHecht** [comment]
@aliyahblackmore here's the content back from the translators:

[https://app.zenhub.com/files/133843125/370814d7-d8f2-446a-a95c-c8c0eaf6df1d/download](https://app.zenhub.com/files/133843125/370814d7-d8f2-446a-a95c-c8c0eaf6df1d/download)

**Comment by aliyahblackmore** [comment]
Thanks Randi! 
This is ready for you @megzehn
**Preview link**: http://preview-prod.vfs.va.gov/preview?nodeId=48613

### 
Notes:
1. There is a sentence in this accordion, "Anong mga bagong presumptive condition sa Agent Orange ang idadagdag ng VA?" that we didn't highlight but it came back slightly different in the doc sent to us. This is the sentence:**Kung sa tingin mo ay eligible ka para sa VA health care at mga benepisyo, hinihikayat ka naming mag-apply na ngayon.**  As discussed, I left in what we already have on the live page and we can flag with the translators whether there's a need to update the text that was previously translated by them. cc: @RLHecht 

2. We have the same accordion/content in two places on the live English page (in the Gulf War and Vietnam sections).
I was sure to add the in both places. This is the accordion: **Mayroon pa bang higit pang mga presumptive condition na nauugnay sa pagkahantad?**

3. It looks like we don't have any translated content for this question on the live PACT Act page  "Am I eligible for VA health care as a Vietnam Veteran?" cc: @RLHecht do we need to send this over to the translators? I don't see this text in any of the tickets.

**Comment by megzehn** [comment]
Thanks so much, @aliyahblackmore!! Confirming this is published now. CC @RLHecht

**Comment by RLHecht** [comment]
Changes are live. Going to send the live page to the translators for QA. Will close the ticket and reopen if they have any changes.
