### ISSUE TITLE
Updates to PACT Act page 10/27/22

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#48820]
## Issue Description
Danielle made updates to the [PACT Act](https://www.va.gov/resources/the-pact-act-and-your-va-benefits/) page about hazardous materials and presumptive conditions. Our team needs to copyedit and publish these changes. 

Word doc with Danielle's changes: [https://app.zenhub.com/files/133843125/a3a0d545-38d5-4e16-a2d4-5e01ee74d38f/download](https://app.zenhub.com/files/133843125/a3a0d545-38d5-4e16-a2d4-5e01ee74d38f/download)
 
## Tasks
- [x] Copy edit (Megan)
- [x] Publish (Megan)
- [x] Create ticket for translation work (Randi)

## Acceptance Criteria
- [x] New PACT Act content is live on the site.

**Comment by RLHecht** [comment]
@megzehn here's the ticket to keep track of the PACT Act work you did with Danielle. I think it's complete but can you confirm?

**Comment by megzehn** [comment]
Yes! Confirming that we updated, reviewed, and published these nodes.

**Comment by RLHecht** [comment]
Thanks! Closing this out!
