### ISSUE TITLE
Provide design system team with error message examples from different categories

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#48825]
## Issue Description
 
The design system team is working on a pattern for helping users recover from error messages. Danielle separated out the error messages into 5 categories:

1. **System:** Alerts the user of important system-related issues or status. It’s initiated by the system and it’s not a result of the user’s actions.
2. **Engagement:** Nudges the user to enter or update data in the system. It can be initiated by either the system or another user.
3. **Access:** Appears when the user tries to access an item that’s not available to them. It may be because the record has been deleted, the user doesn't have access, etc.
4. **Feedback:** The application’s response when the user is interacting with it. The majority of create, read, update, delete (CRUD) actions will result in feedback messaging.
5. **Sign in and identity verification**

We need to look for 1 or 2 error message examples in each of these categories and give the list to the design system team.

## Tasks
- [ ] Search for error message examples in each of the categories above
- [ ] Review (Laura)
- [ ] Post the final list in this ticket and tag Natalie Hill

## Acceptance Criteria
- [ ] Design system team has at least 1 example of each error message category

**Comment by aliyahblackmore** [comment]
11/2 update: I will come back to this work on Monday and continue to compile different examples. Also noting that in our call with Danielle, Laura flagged the related error messages content ticket that may loop in to this work.

**Comment by aliyahblackmore** [comment]
Hi Laura! These error message examples are ready for you to review!  

As discussed with Danielle, we confirmed that for the time being I look at the [error message dictionary](https://design.va.gov/content-style-guide/error-messages/) and matrix [https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/error-messaging/error-code-matrix.md] and make language changes/suggestions as needed. The goal was to give a general idea of our style - we don't have to worry about whether matrix or dictionary content was most up to date. 

I included 1 to 2 examples for each category and included a few changes (i.e. using "We're sorry..." were it seemed appropriate, etc.). I found that the error message dictionary was most helpful and referenced it while I compiled these.

**Comment by megzehn** [comment]
Pulling this ticket out from the grave for an update. 

We changed direction and focused on some more general updates on the DST pattern for Recover from errors. Here are notes from Laura:

> [Recover from errors pattern](https://design.va.gov/patterns/help-users-to/recover-from-errors): 
> 
> We want to suggest moving much of the content guidance out of this pattern page. Much of it is about other types of alerts (not about error messages) and we want to centralize content guidance for errors in the style guide. We’re suggesting that we narrow this pattern page down to 2 streamlined sections:
>
> - How to structure an error message (1. Explain problem 2. Explain how to fix it)
> - Common contact options for error message recovery steps (standardized text for VA hotline numbers and guidance for when to use each o
> - Here's a rough in-process draft of the suggested updates: [Recover from errors.docx](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/EXnXlt2InG5NgbSymwKVRnIBvUPFojkFGfAEE23zW7spCg?e=sYsQec)
>
> [Error messages section of style guide](https://design.va.gov/content-style-guide/error-messages/): 
>
>We want to restructure this section to acknowledge that much of the guidance and dictionary content is actually for info, success, and warning alerts, and not only for error messages. We also want to consider changing the 4 categories of error messages to better align with how designers and product teams think about different types of alerts and errors.
> - Rename the page to "Alert and error messages"
> - Move all general language and style guidance for alerts and errors to this page (from "recover from errors" pattern and elsewhere)
> - Build out updated examples of the most basic and common error messages (and then work with customer support team to add the more complicated ones)
> - Replace the existing 4 categories of error messages (System, Access, Engagement, Feedback) with new categories for types of alerts. Error messages will be one type of alert, with its own examples.
> Here's a rough in-process draft: [Alerts and error messages.docx](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/EXJtIaUIbkJNtYNAq_VSHAsBfCJ4NwnkvpDrEGz3Z958GQ?e=X2D7MQ)

For the first step of this work, @laurwill [overhauled this DST pattern](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3182/) and got this initial version approved by Danielle, Mikki, and Chante. 

Matt just reviewed and [merged it, so it's live in the DST.](https://design.va.gov/patterns/help-users-to/recover-from-errors)

Our next step will be to keep working on the next iteration of the [Error messages part of the style guide](https://design.va.gov/content-style-guide/error-messages/). And then to share these updates with the larger CAIA and design teams.

**Comment by mistymg** [comment]
Shared in [our Slack](https://dsva.slack.com/archives/C03MP8MEPCN/p1757082290637859) the 500 error standardization work Tori did for MHV tools.

**Comment by DanielleThierryUSDSVA** [comment]
Some suggestions in Word doc. Thanks so much for this, @laurenvocke-va!

**Comment by laurenvocke-va** [comment]
@DanielleThierryUSDSVA I sent the PRs for the alert messages to you for review! Thanks!

- System: [#5301](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/5301)
- Engagement: [#5382](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/5382)
- Access: [#5387](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/5387)
- Feedback: [#5415](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/5415)
