### ISSUE TITLE
Wireframes for Wizard Rework

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#48837]
## Issue Description
Updating the wizard designs to be one question per page for copay path

---
## Tasks
- [x] Create wireframes

## Acceptance Criteria
- [x] Wireframes are ready for review
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by josephrlee** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VSA---Debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/48837?planning-poker) with Zenhub @josephrlee @mgleo

**Comment by mgleo** [comment]
Previous user flow (2021): [https://salientcrgt.sharepoint.com/:w:/r/sites/VSATeam/_layouts/15/Doc.aspx?sourcedoc=%7B8B3A764A-D917-4EAA-BEF7-3C25C44D8654%7D&file=MCP%20Wizard%20Mapping.docx&action=default&mobileredirect=true}](https://salientcrgt.sharepoint.com/:w:/r/sites/VSATeam/_layouts/15/Doc.aspx?sourcedoc=%7B8B3A764A-D917-4EAA-BEF7-3C25C44D8654%7D&file=MCP%20Wizard%20Mapping.docx&action=default&mobileredirect=true})

Content updates from Danielle (2022) (Word download): [https://app.zenhub.com/files/133843125/a571c8a5-7961-46c2-93c6-a932f35c0106/download](https://app.zenhub.com/files/133843125/a571c8a5-7961-46c2-93c6-a932f35c0106/download)

**Comment by mgleo** [comment]
Issues with wizard: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/399

**Comment by mgleo** [comment]
Best practices for dynamic content added by radio buttons, checkboxes and select elements https://docs.google.com/document/d/12MctcX8uGg5iKEl8BedXWpsz1wSQY7ZPxW741RhHqsQ/edit?usp=sharing
