### ISSUE TITLE
Work with Forms team to add link to wizard from 5655 Form Page

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#48846]
## Issue Description
Work with the forms team to add a link to the wizard from the VA 5655 Form page
https://staging.va.gov/find-forms/about-form-5655/

![image.png](https://images.zenhubusercontent.com/5f7f60ca14e26c658f77b9f5/4e398c5a-e99a-4361-b65b-4819f5fa3774)

---
## Tasks
- [ ]  Identify and connect with the team responsible for adding urls to the wizard from the forms page.
- [ ] Assist with copy as needed to enhance the form page 
- [ ] Identify next steps and actions as needed
- [ ] Validate link has been added and is live in production

## Acceptance Criteria
- [ ] Link to the online wizard is available for Veterans from the 5655 page. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
@MarciMcGuire Any idea who would be the right contact to discuss adding a link to the online experience on the form page?

**Comment by MarciMcGuire** [comment]
Yep! Public Websites team, Pat Siebenlist.

**Comment by jilladams** [comment]
Spoke with Heather & Denise and @wesrowe . Process-wise, a CMS editor will need to: 

- Click "Content" in the top nav bar
- Search for your form name (VA5655): https://prod.cms.va.gov/admin/content?title=VA5655&type=All&moderation_state=All&owner=All
- Click Edit for the form: https://prod.cms.va.gov/node/6079/edit
- And add the link to the Online Tool link field:
![Screenshot 2023-02-28 at 11 00 30 AM](https://user-images.githubusercontent.com/85581471/221955351-27064853-584a-437c-80b0-21875445829c.png)

Heather & Denise do not have editor users, so Public Websites can help with this when the online tool is ready to be published to the forms page. Just give us the greenlight!

**Comment by denisecoveyduc** [comment]
Thanks @jilladams. This is the link to the online tool for the FSR (Financial Status Report - VA Form 5655) The tool is available today and ready to link to from the form page.  Let us know what other info you may need. Thanks!

https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/introduction
https://va.gov/manage-va-debt/request-debt-help-form-5655/introduction

cc: @wesrowe @HeatherRienks

**Comment by jilladams** [comment]
Great, thanks! I'm double checking with CMS Helpdesk that they're ok with me editing this content, vs. going through a support request with them. https://dsva.slack.com/archives/CDHBKAL9W/p1677621605762009 Should hear tomorrow and can go from there!

**Comment by jilladams** [comment]
Online form link has been added to the VA form with standard copy that appears on other forms with online tools: "You can submit your request online instead of filling out and sending us the paper form."

This will go live with the next content release. Please keep an eye and let us know if you have any issues!

**Comment by denisecoveyduc** [comment]
@jilladams Thanks for all your help team! This looks great! 


## Screenshots
Capturing before and after for future reference.

| Before      | After |
| ----------- | ----------- |
|<img width="661" alt="image" src="https://images.zenhubusercontent.com/5f7f60ca14e26c658f77b9f5/984291a8-a728-4c8b-931d-8f62e560c5a7"> |<img width="661" alt="image" src="https://images.zenhubusercontent.com/5f7f60ca14e26c658f77b9f5/ab7fd1e8-877e-44a4-85dd-3dfae41caa57">

**Comment by HeatherRienks** [comment]
Yes, thanks so much @jilladams and @wesrowe !
