### ISSUE TITLE
Sprint 13 Objectives (1/15 - 1/28)

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#4884]
## Sprint 13 (1/15 - 1/28)

Sprint 13 is 9 days with the MLK Day holiday.

### Order of priorities

**Required to meet sprint objectives**

1. Get address validation ready for QA
2. Share, refine, and finalize designs for Profile 2.0
3. Monitoring, maintenance, bug fixes, hardening, 508, etc.
4. Refactor Vet360 profile components 
5. Hand off APO/FPO/DPO tickets to benefits and memorials teams

**If needed**

1. Technical discovery questions for Profile 2.0

**Other things to note**

- Lihan will be with our team half time and helping out Apps team #2 the other half of the time since we do not have enough backend work in our backlog. Lihan will (likely) start the sprint with the other team, and then rejoin us when VA Profile has gotten us the new endpoint and resolved the ADDRVAL112 error issues.

### Address validation

- New validation endpoint: VA Profile is targeting Tuesday, 1/21.
- ADDRVAL112 error will either be resolved with the new endpoint or shortly after

**Necessary code fixes**

- [x] Sometimes we get validation keys but can't force the addresses through #4278 
  - **Note**: Dependent on VA Profile fixes. Will address this once those are complete.
- [x] Update for address validation where there is only one option #4632
- [x] Address Validation Error State not resetting #4837
- [x] Address validation: Implement the new endpoint from VA Profile #5080

**Enhancements**

- [x] Make "edit address" text clickable in address validation alert texts #4484

**QA**

- [x] Go/No-go
  
### Profile 2.0

- [x] Settle on final design direction #4759
- [x] Navigation exploration #4843
- [ ] (If applicable) Answer any additional technical discovery questions #2455
- Refactor Vet360 Profile form components to use SchemaForm #4068
  - [x] [FE] Refactor VA Profile: Background research to determine scope #4930
  - [ ] Convert profile address form to use SchemaForm #5078

### Monitoring, maintenance, bug fixes, hardening, 508, etc.

- [x] [SCREENREADER]: Text Appointments - Focus must be managed when users press Delete in the modal dialog #2430
- [x] [ZOOM]: Text Appointments - Need a space between input and label in modal window #2435
- [x] Formation - CSS issue for checkboxes and radio inputs, text should be inset #4489
- [ ] Clean up "dashboard" references in code throughout repo #2270

### APO/FPO/DPO

- [x] Hand off tickets for application updates #4374

### Error Matrix

- [x] Justin to implement Lisa's feedback from [#3892](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3892#issuecomment-565577038)
