### ISSUE TITLE
Collaboration Cycle for [Modernized Check-in, eCheck-in & Pre-Check-in, Simplified VA Header/Footer]

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#48859]
### VFS team name

Modernized Check-in

### Product name

eCheck-in & Pre-Check-in

### Feature name

Simplified VA Header/Footer

### GitHub label for product

HCE-Checkin

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>
### When did/will you start working on this product/feature?

December 2022

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Static pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

No

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/README.md

### Notify the Collaboration Cycle team of this ticket in the vfs-platform-support Slack channel.

- [X] I acknowledge that I must notify \#vfs-platform-support after submitting this issue.
- </details>
### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- Navigate to reference link: [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent)
- [x] Schedule your Design Intent when ready:
   - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders 
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [x] Link all artifacts **ONLY** in the Design Intent artifacts section below at least two days before the scheduled Design Intent.  **Do NOT add artifacts to Comments section**
  
**Design Intent artifacts**

- [x] [Wireframe with simplified header/footer and progress bar - segmented (Sketch)](https://www.sketch.com/s/a720996f-5ebb-4092-8e5d-8e3dcff50dc7/prototype/a/E50121F2-F405-46C7-9FE6-8505525F7010)
- [x] [Wireframe to show no progress bar because it's fewer than 3 steps (Sketch)](https://www.sketch.com/s/a720996f-5ebb-4092-8e5d-8e3dcff50dc7/prototype/a/29396E62-4DCD-4779-9065-3C69021F930C)
- [x] [Wireframe for desktop simplified header/footer (Sketch)](https://www.sketch.com/s/a720996f-5ebb-4092-8e5d-8e3dcff50dc7/a/L0LVoDQ)
- [x] [User flow (Mural)](https://app.mural.co/t/vfscie8528/m/vfscie8528/1668453754472/d0ee71372e957dae8b3051726d29e74921e1b417?sender=u83bc52d7fa73658f84f27755)
- [ ] Research plan
- [x] [Problem Statements.docx](https://app.zenhub.com/files/133843125/ce0fcd91-9cc8-4e39-9881-6bc47ac47360/download)  
- [x] [Experimental Design Simplified VA Header and Footer request ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1339)
- [x] [Experimental Design Progress Bar - Segmented request ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1333)
- [x] [Header and footer GA events for patient check in.xlsx](https://app.zenhub.com/files/133843125/f8125ff7-dba9-4842-9421-6c8648593dbd/download)
- [x] [Page 10 - Eliminating Veteran Confusion at Check In.pdf](https://app.zenhub.com/files/133843125/d95d096d-afa2-4309-98cf-bb394e2f4802/download) 
- [x] [Existing prototype without progress bar (for comparison) (Sketch)](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/prototype/a/9F9F9F9F-E205-4F5E-9177-DD4AD750828C)

##### Platform actions
- [x] Follow Moderator Responsibilities guidance for Design Intent
- [x] Meeting date/time: Monday, Nov 21 @ 330pm ET
  
##### Platform actions

- [ ] If you have feedback, create feedback tickets and link to this epic. Once you have completed you review, check the box next to your practice area
  - [x] Accessibility has completed the review
  - [x] Design has completed the review
  - [ ] IA has completed the review
- [x] Update this ticket with the Zoom recording
  - Recording URL: [Zoom link](https://oddball-io.zoom.us/rec/share/UY1j5Y6wu7VuJAdomkVt00QJh_PU1_V-D0FWcvNcGyjKytktWw77Mm124pf-CFtK.OdGdJy5Gn58QlPZY)
  - Password: U1SJ?By!
  
##### VFS actions

- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Sitewide Content and IA Intake Request
<details>
  <summary>Toggle Sitewide Content and IA Intake Request</summary>

##### VFS actions
- [ ] Complete the [sitewide content and IA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-Content-and-IA-intake-request.2124906551.html)
- [ ] Link to the Sitewide Content and IA Intake Request ticket below

</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [x] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)
     - NOTE: we presented the research at DSC

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
**NOTE: midpoint and design intent were consolidated into one meeting**
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [ ] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

Provide links or documents for the following:

- [ ] Finalized design prototype or mockup
- [ ] Specify which pages are included in the review 
- [ ] Research plan
- [ ] Conversation guide
 
**Content artifacts**
  
- [ ] Your product’s content source of truth: 
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable): 

**IA artifacts**

- [ ] Please include a link to any [Sitewide Content & IA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including an IA review document or intake form.

**QA artifacts**
[Learn more about QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [x] Regression test plans (if there isn't already a regression test plan for this feature in TestRailProduct): 
- [x] Link to test cases/test plan in TestRail (draft OK): 
    - [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/4437)
    - [Regression Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/4440)
  
##### Platform actions
- [ ] Follow Moderator Responsibilities guidance for Midpoint Review
- [ ] Meeting date/time:

##### Platform actions

- [ ] If you have midpoint review feedback, create feedback ticket and link to this epic. Once you have completed your review, check the box next to your practice area
  - [ ] Design has completed the review
  - [ ] Accessibility has completed the review
  - [ ] IA has completed the review
  - [ ] Content has completed the review
  - [ ] QA has completed the review
- [ ] Update this ticket with the Zoom recording
  - Recording URL: 
  - Password: 
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [ ] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [ ] Link to the Analytics Implementation and QA Request ticket below

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [ ] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [ ] Link to the Contact Center review request ticket below

</details>

### Staging Review
  <details>
  <summary>Toggle Staging Review</summary>

##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [x] Schedule your Staging Review when ready: 02/07/2023 11:30 am - 12:00 pm ET
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [x] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.

[Experimental design ticket
](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1339) - Reviewed on 1/13 at DSC
[Pull request for simplified header
](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/1425/commits/50494600ba0829e7305de6d38bc504957223bc74) - Reviewed on 1/20 at DSC
[Pull request for simplified footer 
](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/1431/commits/22f7b5c090a4138d9eb8af40615105531c5ddac0) - Reviewed on 1/20 at DSC

[Test and evaluation plan with Veterans](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/49895#issuecomment-1398558060) 

- [x] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [x] I confirm the environment is available and test users have been provided. 
- [x] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
 
**Staging Review artifacts**
  
  Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts)
  
**Product artifacts** 
- [x] Review env URL

[The VA simplified header and footer can be reviewed in the review environment](http://d13daffe92166e2dd824118270cf37e4.review.vetsgov-internal/health-care/appointment-check-in/error?error=no-token). Because the VA header and footer code sits outside of our applications, we cannot feature flag or create a staging environment with it enabled for our application. In addition, appointments can not be scheduled to view in the review environment. Therefore, accessing the review environment will show an error message because a unique URL wasn't used to access the application. 

SOCKS must be enabled to access the [review environment](http://d13daffe92166e2dd824118270cf37e4.review.vetsgov-internal/health-care/appointment-check-in/error?error=no-token). 

Also, there is an [issue with the review environment ](https://dsva.slack.com/archives/CBU0KDSB1/p1674832178377869) that causes it to get wiped in 1-2 days. If the review environment is not available, please [request a new link in Slack via #check-in-experience](https://dsva.slack.com/archives/C022AC2STBM/p1675437090216129?thread_ts=1675375113.205119&cid=C022AC2STBM), and then we'll update the review environment link in this ticket.  

This feature is a new version of the VA.gov header and footer. Therefore, this feature can be seen in the wrapper that's present on all pages of our pre-check-in and check-in apps. There have been no user flow, design or content changes to our application as part of this feature. 

[View video of the simplified header and footer running along with our application in the review environment.]( https://images.zenhubusercontent.com/133843125/552591fc-10c6-40a0-9497-0fe44fec4527/screen_recording_2023_01_31_at_16_36_37.mov)

- [x] Staging test user information         

Staging test users have not been provided because this code is not part of our application.
  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**
- [x] None at this time for this feature 
  
**IA artifacts**

- [x] Please include a link to any [Sitewide Content & IA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including an IA review document or intake form.

No content & IA changes to the PCI app with this feature. 

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [x] [Regression Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/4440) 
- [x] [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/4437)
- [x] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/394)
- [x] [Summary(Defects) reports](https://dsvavsp.testrail.io/index.php?/reports/view/393)
- [x] E2E tests
   - day-of: https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/check-in/day-of/tests/e2e
   - pre-check-in: https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/check-in/pre-check-in/tests/e2e
   - shared: https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/check-in/tests/e2e/pages
- [x] Code coverage

| Application | Lines | Functions | Statements | Branches | Link |
| - | - | - | - | - | - |
| Day-of | 92% | 90% | 92% | 66% | [application folder](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/check-in) ( unit tests are co-located with components, pages) |
| Pre-check-in | 67% | 63% | 67% | 56% | [application folder](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/check-in) ( unit tests are co-located with components, pages) |

  
**Accessibility artifacts**
  
- [x] [Completed accessibility testing artifact](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/52512)
  
##### Platform actions
- [x] Follow Moderator Responsibilities guidance for Staging Review
- [ ] Meeting date/time: ~~**Tuesday, January 31 at 11:30AM Eastern**~~
- [ ] Create feedback tickets and link to this epic
  - [ ] Design feedback provided
  - [ ] Accessibility feedback provided
  - [ ] IA feedback provided
  - [ ] Content feedback provided
  - [ ] QA feedback provided

##### Platform actions

- [ ] Update this ticket with the Zoom recording
  - Recording URL: 
  - Password:
  
##### VFS actions
  
- [x] Review feedback tickets and comment on the ticket if there are any questions or concerns
- [x] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions

No changes were made to our application as part of this collab cycle. Therefore, we did not initiate this step. 

- [ ] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
necessary
- [ ] Link to the Readiness Review ticket below

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>
