### ISSUE TITLE
[EPIC] MHV to VA.gov: MR: Notes: Low-Fi Design & Refinement

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#48853]

**Comment by rbsingleton** [comment]
Low-fi artifacts to hand-off: 
- [ ] Low-fi user flow
- [ ] Low-fi screen/ prototype
- [ ] Documentation around design decisions, technical considerations, and questions to be answered (with perhaps suggestions on how to answer the questions)

Low-fi content = some content will be there but it's just a first pass (ByLight will work with content team to refine)

Low-fi visuals = could be mix of gray with some use of color

Low-fi interaction = not everything will be clickable - just basic elements to give an understanding of experience

Potential technical blocker - there’s a lot of questions around what’s going to be possible until MHV starts FHIRizing to get a better handle on the limitations of their implementation, namely the fields available around filtering/sorting/searching
