### ISSUE TITLE
Create guidance for banner usage for facilities

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#48861]
## Issue Description

The sitewide facilities team opened a content intake request for us to create guidance for editors on the banners that facilities use. Some facilities use multiple banners on one page and others create lengthy ones that take up a good chunk of the top of the page. 

We need to help define when banners should be used vs. when to use facility status alerts and guide editors in creating short, plain language banners. 

It might be helpful to reach out to the product team for more background. We should ask if this guidance is going to be shared as a knowledge base article or in some other format. 

Initial intake request to review: #48331

## Tasks
- [ ] Research and create content for banner guidance (Aliyah)
- [ ] Review (Laura)
- [ ] OCTO-DE review (Danielle)
- [ ] Copy edit (Megan)
- [ ] Post final content in intake ticket for product team (Aliyah/Laura)

## Acceptance Criteria
- [ ] Product team has final content for banner guidance

**Comment by dsinla** [comment]
Thanks @RLHecht 
The key info here is that the Facilities team is planning to modify the current behavior to allow an author to have only one banner on a page at a time. Editors will receive an error if they try to create a second one. It's a little complicated because the logic will also allow a VISN-level banner to be _cascaded_ down to the system - so it would be possible that a Veteran visiting the site sees two banners.  We also plan on limited the amount of text in a banner, to enforce that it should be more like a tweet, directing the reader to another page for long-form info.
I have started an [audit of the current KBs](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11141#issuecomment-1297360314), to determine how best to modify/restructure them.

**Comment by aliyahblackmore** [comment]
**Update 11/2:** Content team is pausing on this work while the Facilities team does more digging on how banners are currently used/misused and provide recommendations.

**Comment by dsinla** [comment]
@RLHecht and @aliyahblackmore wanted to ping you that we're making progress on the work we are doing internally, and should likely have our first draft of recommendations ready for your input/review after Sprint 72. Please let me know how to best coordinate timing based on your other priorities. Thanks!
