### ISSUE TITLE
Production AWS access for [John Bramley]

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#48860]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

John Bramley

### Your Email

john.bramley@adhocteam.us

### Team, Role, and Company of the target individual

Identity, Backend Engineer, Ad Hoc LLC

### Product Manager (PM) name and email

Alyssa Gallion

### Product Owner (PO) name and email

John Rahaghi

### Desired AWS Access

I need (read-only) access to `dsva-vagov-prod-deployment-vets-api-server` EC2 instances. As a backend engineer on the Identity team I am sometimes needed to query a specific user to assist in a support request. Alternatively I could just use the same permissions as @bosawt, the other backend engineer on the Identity team.

### Access Expiration

ongoing

### Additional Notes

Access to production is needed to assist in individual support requests - no end date.

COR: Ray Wang

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by joeniquette** [comment]
John Bramley already has Identity AWS related access as a backend engineer on the Platform Identity team. What we are asking for in this case is to add more permissions to his AWS access to allow for production EC2 vets-api instance access. Both backend engineers on our team have a requirement from time to time to review production user accounts information on accessible by SSM'ing directly onto a running prod instance. These use cases include an official Fraud Waste and Abuse investigation, troubleshooting a production level authentication bug, and production deploy verification of settings. There are no exposed methods of these due to the sensitivity of such a solution would provide. We would like to develop a solution which would not require production EC2 instance access for these use cases.

Trevor Bosaw already has this exact access level and is a peer of Johns. We are trying to build in redundancies so that when Trevor is not available John can complete the required tasks. Please direct any specifics around the use case to myself, and any of the PO questions to John Rahaghi.

**Comment by td-usds** [comment]
@joeniquette thank you for the explanation; 
Either Joe or @bramleyjl  could you provide me with your VOR contact information as well?

**Comment by td-usds** [comment]
Requested access approved

**Comment by bramleyjl** [comment]
Confirmed I have production access to vets-api in production

**Comment by bramleyjl** [comment]
Confirmed I have production access to vets-api in production
