### ISSUE TITLE
[FE] Clean up check_in_experience_lorota_deletion_enabled feature toggle

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#48879]
## Description
Clean up feature toggle `check_in_experience_lorota_deletion_enabled` in the frontend. Check to see if backend is still using it before removing from vets-api.

Remove client side validation attempts storage and logic leaving just the server side handling.

## Tasks
- [ ] [FE] Remove feature flag
- [ ] [FE] Clean up code around the flag and remove client side validation attempts logic
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by sarahknoppA6** [comment]
duplicate
