### ISSUE TITLE
BE Discovery | Profile | Direct Deposit | Fiduciary Flag

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#48881]
## Background
Currently, we aren't looking for data to tell us when to display a fiduciary flag when someone attempts to edit their direct deposit info. Additionally, would it be possible to read the fiduciary before we make an attempt to send data back and prevent users from even getting to the point of editing. We would instead show the fraud error when they hit the profile.

## Tasks
- [ ] Review BGS response in vets-api
- [ ] Get a count on how many records are flagged
- [ ] Determine flag availability (is it being returned now; if not, when?)
- [ ] Create/estimate ticket for development work
  

## Acceptance Criteria
- [ ] Review development tickets with team

**Comment by SKasimow** [comment]
We can't determine this thru logs; will open a ticket to track via GA.
