### ISSUE TITLE
BE | Profile | User Auth | Update BE docs

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#48894]
## Background
Update BE docs to include how a user data is populated.

## Tasks
- [ ] Specify how `/v0/user` response data is populated (profile, va_profile, vet360_contact_information).

## Acceptance Criteria
- [ ] Add document to secure repo.
- [ ] Share update with team.
