### ISSUE TITLE
DDL: Distinguishing Intent to File in listview

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#48908]
## Value Statement
**_As a_**  veteran looking for a claim letter
**_I want to_** be able to distinguish my "intent to file" letter from other letters in the list view
**_So that_** I can more easily find that document without having to download and open other documents.

---
## Background Context
Intent to file documents seem to have a value in the subject attribute that we can use to distinguish these files from other items in the claims letters list view. 

## Acceptance Criteria
- [ ] Description in the list view allows a user to distinguish the Intent to File letter from other letters.
- [ ] Solution conforms to accessibility guidelines.
- [ ] Design solution is future-forward in that a similar approach could be used to swap in language for other letter types as new use cases emerge

## Designs and Build Notes
![dld-m3 copy 8](https://user-images.githubusercontent.com/95102058/199335065-1eda6a81-5c42-4dcd-ba10-fd9a8249451f.png)

## Open questions
- Add here

## Tasks
- [ ] Confirm design approach
- [ ] Confirm approach to relying on subject line values from the identified attribute
- [ ] Implement solutions approach on staging

## Definition of Ready
- [ ] _Clear value description_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by skylerschain** [comment]
Added mock to design section. Full spec visible [here](https://www.sketch.com/s/8b025901-295d-4929-95cc-8dbeb28454b3/p/CAA1846C-79ED-4BDB-94B9-BA0EBE74EC5B/canvas).
