### ISSUE TITLE
DDL: Include Ratings Decisions in listview

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#48916]
## Value Statement
**_As a_**  veteran looking for a claim letter
**_I want to_** be able to find my "Rating Decision" letter and distinguish it from other letters in the list view
**_So that_** I have access to the document that provides the most comprehensive explanation for my rating decision.

---
## Background Context
The Rating Decision is a different document type with a distinct number value associated with it. We should be able to lean on that value to include Ratings Decisions in the claims letters list view.  

## Acceptance Criteria
- [x] Ratings Decisions are visible in the claims letters list view
- [x] We can distinguish Ratings Decision letters from other document types
- [x] Design solution is future-forward in that a similar approach could be used to swap in language for other letter types as new use cases emerge

## Designs and Build Notes
- @skylerschain to add

## Open questions
- Add here

## Tasks
- [ ] Confirm design approach
- [ ] Confirm approach to relying on doc type values from the identified attribute
- [ ] Implement solutions approach on staging

## Definition of Ready
- [ ] _Clear value description_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by skylerschain** [comment]
Added mock to design section. Full spec can be found [here](https://www.sketch.com/s/8b025901-295d-4929-95cc-8dbeb28454b3/p/CAA1846C-79ED-4BDB-94B9-BA0EBE74EC5B/canvas).
