### ISSUE TITLE
[EPIC] MHV to VA.gov:MR: Labs and Tests: Requirements gathering

### ISSUE THREAD

**Issue by JasmineYohannan** [department-of-veterans-affairs/va.gov-team#48917]
**Purpose of this epic:**
To gather and centralize requirements related to the data fields for Labs and Tests that need to be represented on VA.gov, UX design strategy that can be articulated, and any feedback from SMEs or other stakeholders that needs to be defined. 

**Process:**
- [x] Create a Labs and Tests brief that describes: required data fields, Use cases, UX considerations, Questions to answer, and any additional notes that might be helpful @rbsingleton and ByLight designer
- [x] Review Labs and Tests brief with @jonathanjnelson, identify any questions to be answered, resolve any confusion or errors

**Deliverables:**
- [ ] [Labs and Tests strategic brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records/data-domains/Labs-and-tests/labs-and-tests-brief.md)
