### ISSUE TITLE
PM | Profile | Grooming Status of Backlog Tickets | Not in a Sprint

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#48926]
#### General/Tech Debt

**Frontend**
- [ ] #49550 Adjust Placement of In-line Error Alert and Text (3 pts)
- [ ] #34012 Display error message for any type of issue encountered when disconnecting an app
- [ ] #37077 Address Validation E2E Test Missing Suggestion UI
- [ ] #49550 Bug | Adjust Placement of Update Alert + Text
- [ ] ~#49983 Update Custom Radio Button Component | Tech Debt (future work)~

---

#### General/Tech Debt

**Frontend**
- [ ] #48006 Bug: zoom with gesture disabled for modals on iOS (3 pts)
- [ ] #32963 Connected app content falls outside container (2 pts)
- [ ] #47754 Emoji's in email address (2 pts)
- [ ] #37363 Connected apps (2 pts)
- [ ] #44532 Update Phone #'s to correct error responses (3 pts)
- [ ] #21587 Remove FE usage of `AsyncTransaction::Vet360::*` strings (1 pt)
- [ ] #47666 Scroll to Top after Successful Update (2 pts)

---

#### Accessibility Audit/Research Tickets

**Frontend**

- [ ] #49459 Notif Settings | New Page for Mobile Flow
- [ ] #49436 Create Feature Flag for New Mobile Flow
- [ ] #49319 Update the Notifications flow when adding a Mobile number
- [ ] #49652 Address Validation Improvements (draft) 
- [ ] #49651 Personal page | Add Nametag Field
- [ ] #47721 Focus Area (defect-2) - _needs more clarification from accessibility team_
- [ ] #37041 Semantic Lists and headers (related to #19618) (defect-4) _Test this the next time we do screen reader testing to see how big of an issue it is for people._
- [ ] #40593 Screenreader Accessibility Issue | Sections of Profile are above the H1 (5 pts) - deferred/on hold
