### ISSUE TITLE
[EPIC] MHV to VA.gov:MR: Knowledge transfer for remaining MR domains to ByLight

### ISSUE THREAD

**Issue by JasmineYohannan** [department-of-veterans-affairs/va.gov-team#48924]
## Tasks
- [x] Review user interview findings, recommendations, and provide links to documentation and related Murals
- [x] Review low-fi mockups
- [x] Provide links to mockups, decision logs, domain brief, comparative analysis, and any other pertinent design documents or assets

## Domains to Include
- [x] Labs and Tests
- [x] Clinical Notes
- [x] Health Issues
- [x] Vitals
- [ ] Demographics
- [x] Allergies
- [ ] DoD Information
- [x] Printable Reports (BB/Heath Summary)

**Comment by MarciMcGuire** [comment]
@jonathanjnelson @coultonbunney-usds Do we need to leave this issue open?  What was decided about Demographics?  Thx!
