### ISSUE TITLE
Prepare for User Research for Yellow Ribbon MVP

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#4892]
[_Reference: VSA Delivery Front Door (issue templates and examples)_](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/delivery#vsa-delivery)
## User Story:
As a product team, we need to better understand Veteran's needs and behaviors around utilizing their Yellow Ribbon benefits so we can provide an improved front-end solution

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [x] Submit plan and guide - Liz
- [x] Schedule participants - Perigian
- [x] Recruit notetakers - Liz - .5 hours
- [x] Complete pilot sessions - Liz 2 hours
- [x] Refine conversation guide

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
* All steps above taken to prepare for research with participants

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
