### ISSUE TITLE
Yellow Ribbon Research Synthesis

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#4893]
[_Reference: VSA Delivery Front Door (issue templates and examples)_](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/delivery#vsa-delivery)
## User Story:
As a designer/developer, I need user feedback so that I can iterate and provide an improved FE solution.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [x] Research synthesis and recommendations - Liz - 12 hours

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
* Share out synthesis with team

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MickinSahni** [comment]
Sent out top-line summary for review from stakeholders. Meanwhile working on wireframes.

**Comment by MickinSahni** [comment]
2020-02-06 PW Standup
- No explicit feedback yet reviewing later today

**Comment by andaleliz** [comment]
[Topline Summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/yellow-ribbon-mvp/research/yellow-ribbon-mvp-topline-summary.md)
[Research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/yellow-ribbon-mvp/research/research-findings.md)
