### ISSUE TITLE
[Development] Add Claims with Docs End-Point

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#4894]
[_Reference: VSA Delivery Front Door (issue templates and examples)_](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/delivery#vsa-delivery)
## User Story:
As a veteran, I need to be able to go to the claims tool and upload files and see them listed so that I can verify my uploads have gone through correctly.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [x] Add new endpoint integration to EVSS claims service.
- [x] Update EVSS claims async job to take advantage of the new service endpoint.
- [x] Get on a staging box, verify connection exists, and create a new cassette.

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
* Allow uploaded files to be displayed correctly on the claims status tool

## Configuration
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by SMLuthi** [comment]
This has been completed. Changes have been verified to be working correctly on the staging site. This will deploy to production next Monday (1/20/20)
