### ISSUE TITLE
Create interactive prototype for Yellow Ribbon MVP

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#4896]
[_Reference: VSA Delivery Front Door (issue templates and examples)_](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/delivery#vsa-delivery)
## User Story:
As a researcher, I need an interactive prototype so that I can test with users.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] wire up clickable prototype in InVision - Liz, 2 hours
- [ ] Review conversation guide to ensure details line up w prototype - Liz, 2 hours

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
* Testable prototype

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by andaleliz** [comment]
[Mobile](https://vsateams.invisionapp.com/share/XBVON0YMJ4Y)

[Desktop](https://vsateams.invisionapp.com/share/X5VOMBG2YP4)
