### ISSUE TITLE
[EPIC] MHV to VA.gov: Immunizations: Low-fi design & refinement

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#48967]
Break down into issues and add tasks and AC

**Comment by rbsingleton** [comment]
Low-fi artifacts to hand off: 
- [ ] Low-fi user flow
- [ ] Low-fi screen
- [ ] Documentation around design decisions, technical considerations, and questions to be answered (with perhaps suggestions on how to answer the questions)

Low-fi content  = some content will be there but it’s just a first pass (they will work with content team

Low-fi visuals = could be am mix of gray with some use of color

Low-fi content = some content will be there but it’s just a first pass (ByLight will work with content team to finalize)

**Comment by rbsingleton** [comment]
Potential blocker: technical discovery 
- For the technical aspect there’s a lot of questions around what’s going to be possible until MHV starts FHIRizing to get a better handle on the limitations of their implementation, namely the fields available around filtering/sorting/searching
