### ISSUE TITLE
Research AuthN / AuthZ Schemes for Preview Environments

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#48979]
# Description
Given that one of the potential issues with making preview environments reachable from the the public internet is the ability of unauthenticated users to access the environments running unapproved code. How might we authenticate and authorize legitimate users for preview environments?

# Tasks
- Answer some research questions --
  - [x] Does authenticating users wishing to access a preview environment resolve an issue with operating preview environments at publicly reachable addresses?
  - [x] Is basic auth good enough for a preview environment?
  - [x] What authentication schemes are available beside basic authentication?
  - [x] How might we automate authentication / authorization to preview environments?
  - [x] Do users need to authenticate before creating a preview environment _and_ before accessing a preview env? 

# Acceptance Criteria
- [ ] We understand whether publicly available preview environments must be behind authentication 
- [ ] (If required) We understand how users will authenticate to the preview environments

**Comment by rmtolmach** [comment]
Confluence page in progress: https://vfs.atlassian.net/wiki/spaces/TT4/pages/2424832263/Research+Auth+Schemes+for+Preview+Environments

**Comment by rmtolmach** [comment]
Moving this to the "review" column. 

Not all questions can be answered at this time, but we'll have the discovery confluence page to guide us with our architecture.

**Comment by pjhill** [comment]
Thanks for writing all of this out into a research document. I think we have enough information to propose an architecture to the architecture working group. With this research and our plan to propose a draft architecture to the architecture working group, I am confident that we will be able to create a Preview Environment solution that satisfies Platform security goals.
