### ISSUE TITLE
[Design] Better visualize steps of checking in within Pre Check In

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#48985]
## Description

In [exploring the use of the progress bar and task list components](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/48069) to help solve the problem of helping Veterans better understand the steps of check in and pre check in (and understanding the differences between them), we realized that there may be too few steps within pre check in alone to justify the use of either component. 

However, what we could do to help solve the problem is to better communicate, and visualize, the steps of pre check in and check in on either (or both) the introduction pre check in page and the completion pre check in page. 

Shawn has provided some materials for reference from Kaiser (which Stephen has seen as well). 

![image (2).png](https://images.zenhubusercontent.com/62264cddfdd7546d65710eff/43b9575a-121e-4f95-89a5-fd9d5372f164)

Secondarily, if changes ensue on the introduction pre check in page, look for opportunities to decrease the exit rate on the page. Over the [last 30 days, the exit rate is 6.75%](https://analytics.google.com/analytics/web/#/report/content-exit-pages/a50123418w177519031p176188361/_u.dateOption=last30days&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22RE%22,%22appointment-pre-check-in%22,0%5D,%5B0,%22analytics.pagePath%22,%22PT%22,%22error%22,1%5D,%5B0,%22analytics.pagePath%22,%22PT%22,%22introduction%22,0%5D%5D&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=50/), which is slightly higher than other pages within pre check in. Is there a potential that Veterans are not finding the link to progress in the work flow? 
 
## Tasks

- [ ] If needed, get additional screenshots from Shawn or have conversation (he mentioned he may have more screenshots) 
- [ ] Explore re-imagining of introduction page and completion page
- [ ] Create wireframe(s)
- [ ] Add content to document (can be Google doc) so Lori has for translations
- [ ] Review with Danielle, if needed
- [ ] Review with CIE Team
- [ ] Consider creating a new ticket for identifying success metrics or tracking 
- [ ] Discuss how this change might affect the R&D page on VA.gov

**Comment by ytsaoca** [comment]
Inspirations: https://app.mural.co/t/vfscie8528/m/vfscie8528/1668464016140/a8f03a79e1a68dbf0c58154efccf7a9bd7a1d5ba?sender=u70b8b2930b03d3ef317d2520
