### ISSUE TITLE
[Design] Payment Info: Design "historical debt" for Outstanding Debts section

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#48984]
## Background
During the My VA audit we found that it may be useful to show a link for users to view their historical debt. In [42329](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42329), Angela determined that Benefit Team 2 (debt team) doesn't currently have a way of knowing whether a debt is resolved which would be critical for showing "historical resolved debt." In the interim, our team could show historical letters (overpayment debts) and statements (medical copay statements).

**Reference**
- [Discussion with Benefit team 2 about historical debt](https://dsva.slack.com/archives/CPE4AJ6Q0/p1666282723576959)
- [UXPin mockup of debt letters](https://preview.uxpin.com/29cd8f525781fa231d16f5b50905ad15a99cbf01#/pages/149089100/simulate/sitemap?mode=i)

## Tasks
- [ ] Create design for showing historical debt letter and statements
- [ ] Review with team

## Acceptance Criteria
- [ ] Design for historical debt exists

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_
- _How can this work be validated?_

## Resources
- optional: links, screenshots, etc.

**Comment by ajakabcin** [comment]
Questions to consider from backlog review Dec 12, 2022:

1. What should we elevate beyond what's available on debt portal?
2. Is this a link or something more comprehensive than what's on debt portal?
3. Are we doing enough on My VA, and then let debt portal perform its job.
