### ISSUE TITLE
[A11y Maintenance Audit]: Your VA Payment History

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#48987]
## Auditor(s)

Josh Kim

## Automated

- [x] Run axe checks on every page or unique state (required)
- [ ] Run WAVE on every page if time allows. WAVE is more visual than axe or axe-coconut, but offers some excellent ways to identify nested headings and HTML5 landmark tags.

## Manual

- [x] Color contrast checks (recommend using whocanuse.com for beyond compliance reports)
- [x] Color blindness checks
- [x] Zoom layouts to 400% and inspect them for readability. If layouts break at 400%, I will start reducing them until they become stable, and log the zoom ratio when things started breaking.
- [x] Keyboard navigation

## Screen Reader

- [ ] Firefox and NVDA
- [ ] Edge and JAWS
- [x] iOS Safari and VoiceOver (Mobile)
- [x] Safari and Voiceover (Desktop)
- [ ] Chrome and Talkback

## Staging or Production Link

https://staging.va.gov/va-payment-history/

## Prototype Link

[Adobe XD Mockups](https://xd.adobe.com/view/5f609803-b045-428a-510e-1754e404af3e-2951/) (Jim was the original designer, but is no longer with us)

## Test Users
- vets.gov.user+228@gmail.com
- [Find password](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)

**Comment by joshkimux** [comment]
Maintenance audit is complete!
