### ISSUE TITLE
SEO research on decision reviews and appeals terms

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#48992]
## Issue Description
Now that "decision reviews" has been VA's term for "appeals" for a while now, we need  to see if search patterns have changed and Veterans have started to search "decision reviews" more than "appeals."

We'll need to do SEO research on both "decision reviews" and "appeals." Once we have results we can decide whether we should be removing the word "appeals" from certain places on VA within the decision reviews hub and other next steps. This will need to be a conversation with decision reviews stakeholders.

## Tasks
- [ ] Do SEO research on "decision reviews" and "appeals"
- [ ] Talk through results with Beth to determine next steps

## Acceptance Criteria
- [ ] SEO research complete

**Comment by bethpottsVADEPO** [comment]
@RLHecht The term "decision review" isn't even on the radar for MSV. But we need to add this term since it's the name of the process now. "Appeals" is still how people are searching, so we'll keep that term. I don't think there's any more work to do with SEO at the moment, so I'm closing this ticket.
