### ISSUE TITLE
[Research] Payment Info V2: Submit for research/review begin recruitment

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#48993]
## Background
We need to submit all research artifacts for the payment info v2 research/usability testing.

Pre-requisites:
- [ ] Dev needs to be complete
- [ ] Research plan/documentation needs to be complete

## Tasks
- [ ] Submit materials to research repo
- [ ] Message research ops in slack to let them know you've submitted the materials
- [ ] Perform any followup tasks that research team requests
- [ ] Let PM/APM know so they can make sure the [collab cycle epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42601) is updated as needed

## Acceptance Criteria
- [ ] Materials are submitted and recruiting for our study has started

## Validation
- **_Who can validate this ticket? (FE, BE, Design, PM)?_** NA
- **_How can this work be validated?_** NA

**Comment by aagosto90** [comment]
Submitted to research repo 11/9 ([GH ticket](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/191)) ([Slack thread](https://dsva.slack.com/archives/C0216PL32HJ/p1668016910249809))
