### ISSUE TITLE
Research RI Customization Use Case

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#48996]
## Issue Description
Based on initial measurements of success metrics we can see that very few users are have created non-standard Review Instances since we began collecting data ~10/19/2022. Let's discover who the user(s) are and contact them to understand their use case.

---
## Tasks
- [x] Contact recent Review Instance users who deployed non-default review instances
- [x] Determine why they used non-default deployments

## Acceptance Criteria
- [x] We understand the use case for non-standard review instance deployments

**Comment by CBonade** [comment]
https://docs.google.com/spreadsheets/d/1sR_TM6EtAUx7f_-Q5M8aNoqmAlFfr_LmL3Cfi95w9Ks/edit#gid=0

Here's all documented uses we have on record of review instances that have been launched with custom branch setups. There's a total of 2 users: Josh Mills and Mark Dewey.

**Comment by CBonade** [comment]
https://vfs.atlassian.net/wiki/spaces/TT4/pages/2428764373/Review+Instances+Custom+Setup+Use+Cases Ongoing confluence page to track the responses from the users. Messages have been sent to both,

**Comment by CBonade** [comment]
All responses are in. The findings lead to an investigation about an unknown feature and those findings are also recorded. It's worth noting that this may impact our future initiative, as it seems this is a feature we may not have accounted for.

**Comment by pjhill** [comment]
Thanks for adding some context to these customization instances. And, the feature that detects identically named resources and automatically uses them is an interested discovery!
