### ISSUE TITLE
Research RI Usage Impact

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#48998]
## Issue Description
Review Instances are created when a PR is created, based on our current metrics, it seems that only about 15% of those Review Instances are being used. We would like to look into whether there is an impact in having 85% of those Review Instances unused.

---
## Tasks
- [x] Analyze the cost to create a review instance (start up costs)
- [x] Analyze the cost to operate an unused review instances
- [x] Analyze the cost to operate an average used review instance
- [x] Apply the analysis to known usage measurements to determine an average monthly cost for review instances

## Acceptance Criteria
- [x] We understand the current cost to operate the review instance system and the percentage of that cost going to unused review instances

**Comment by CBonade** [comment]
Added data collection to our metrics for the launch date of the instance to have a base to calculate off how long the instance has been open for and what their approximate cost is. However, its currently based on full days which is not the way we want this to go. I'm going to dig a little deeper tomorrow to see if i can't get this a bit more intricate.

https://va-gov.domo.com/datasources/36d311c6-04f7-433d-9e04-73ff46e9bc16/details/data/table New data set in domo here (was requested to keep separate from the old data set.

**Comment by CBonade** [comment]
https://va-gov.domo.com/page/600769572 Here's a new dashboard that contains this information. 

In regards to the points listed in the ticket:

`Analyze the cost to create a review instance (start up costs)`:

I could not find any startup costs associated with EC2 instances when they're in an on-demand format (which i believe is what we use). They only have an hourly cost.

`Apply the analysis to known usage measurements to determine an average monthly cost for review instances`:
We don't have a month's worth of data yet, so have it showing daily for the time being, as well as reflecting an overall average of all collected data that meets the criteria.

Other points are depicted as requested.

**Comment by CBonade** [comment]
Bumped the estimate on this to account for the data ingestion of this data and dashboarding as well, which were not listed in the ticket but were the easiest way to record this data in a way that keeps everything together.

**Comment by pjhill** [comment]
Thanks for this! We have a great baseline understanding of the cost of review instances to go with our other success metrics now. This is great information for making all sorts of decisions about behaviors and user experiences!
