### ISSUE TITLE
Update RI Dashboard

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#48997]
## Issue Description
Need to add some details as text on the dashboard to help frame the info more effectively

---
## Tasks
- [x] Review dashboard and make a list of suggested tweaks
- [x] Provide the list to Team 4 member for implementation of corrections
- [x] Review updated version and provide description of additional tweaks as necessary

## Acceptance Criteria
- [x] Dashboard corrections have been implemented

**Comment by CBonade** [comment]
On Friday (11/4) we made a few tweaks here regarding how the costs were displayed in the Review Instance Usage by Day chart. The total number was updated to reflect a total cost of all review instances as opposed to the number of hours that instances had been running for. We also discussed changing the charts to all 14 day intervals, however we decided to hold off on that. Awaiting finalized list of changes to be made before pushing this to done.

**Comment by JoeTice** [comment]
A couple items from our review...
- Update the name/timeframe of the Cost of Launched Review Instances card
- Drop the daily avg cost cards (x2)
- Add a card for total cost of review instances
- Adjust layout as discussed.

**Comment by CBonade** [comment]
- [ ] Update the name/timeframe of the Cost of Launched Review Instances card
- [ ] Drop the daily avg cost cards (x2)
- [ ] Add a card for total cost of review instances
- [ ] Adjust layout as discussed.

All data sets that power these cards are no longer showing data before 11/4 as requested. There is one caveat that for whatever reason Domo shows the date visually as Nov 3 - current, but the earliest data charted is correctly Nov 4.

**Comment by pjhill** [comment]
Indeed the updates are published. Perhaps we can demo this dashboard page in the future.
