### ISSUE TITLE
Design | Profile | Nametag-Full Name and Disability Rating | Content and IA Review

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#48990]
## Background

Review design changes for disability rating and full name being added to the main sections of profile. We will need to discuss these changes with the content and IA folks and get their feedback, then make adjustments to the design as necessary.

Also, determine if we should only show this if we know user is a Veteran or always show.

## Tasks
- [ ] Review designs with Content/IA
- [ ] Document feedback
- [ ] Adjust designs as necessary
  

## Acceptance Criteria
- [ ] Designs for full name/disability rating are reviewed by content and IA

## Associated Tickets
- #48264

**Comment by cgednalske** [comment]
Hi @Samara-Strauss -- For possible PACT Act info to add to disability rating, I shortened the content down to use only links and then worked with Danielle in her office hours this morning to get the wording down to pretty succinct versions compared to before. 

Here are some options we're playing around with and would love to get your feedback on. These new versions have definitely removed the bulkiness of the other versions, so hoping we're getting closer to an option that might make sense for the page 🤞 

Pictured are some format options with the first link either next to or under the related info. We're playing around with the following wording options:

**Link one:**
Read about your VA disability rating
Learn more about your disability rating

**Link two:**
Pact Act: Eligibility updates based on toxic exposures
PACT Act: Expanded eligibility based on toxic exposures

<img width="1182" alt="Screen Shot 2022-11-03 at 10 19 54 AM" src="https://user-images.githubusercontent.com/79372956/199795791-ad212ed5-918c-4ea5-a160-b2c91cde8ded.png">

<img width="1152" alt="Screen Shot 2022-11-03 at 10 45 35 AM" src="https://user-images.githubusercontent.com/79372956/199796268-2132b063-4eba-449c-b30d-53fdb5cf10c1.png">

**Comment by cgednalske** [comment]
Hi @Samara-Strauss and @SKasimow - just wanted to check back in on this. Any thoughts on the condensed version above using only links? Thanks!

**Comment by cgednalske** [comment]
Hi @Samara-Strauss and @SKasimow - another update for this work. I just met with Joni Chan, one of the IA specialists, to talk through the Disability rating and full name additions. 

She said that this placement is a bit tricky, but ideally disability rating would go in it's own Disability rating section or health-related section (if at any point health info is added), both because it doesn't feel completely right in Personal info and because a new section would make it more accessible for screen reader users. 

If we don't want to create a new section, however, she said Personal information could work, but she'd suggest moving Disability rating to the bottom below the biographical info (pictured). 

Are we interested in further considering a new section for Disability rating or would we like to stick with Personal info addition? 

<img width="583" alt="Screen Shot 2022-11-08 at 11 35 15 AM" src="https://user-images.githubusercontent.com/79372956/200649140-21d10ba2-570b-4dd8-8c3e-b2a78c160a89.png">

**Comment by cgednalske** [comment]
@Samara-Strauss no problem! Thank you! That all sounds great to me. 👍  I'll move forward with the two links on separate lines and then move disability rating to the bottom of the page. I'll also start adding this to our main files (currently in the discovery section).

**Comment by SKasimow** [comment]
Hi @cgednalske - can you send me the sketch links to finals so I can get the FE ticket ready to groom?

**Comment by cgednalske** [comment]
Hi @SKasimow - here are the links to the Sketch files. I'm currently finishing up making sure these fields are adding throughout all files/screens, but these should be the only two that need to be referenced. Also working on if there needs to be a separate screen with an alert for if disability rating doesn't connect/can't show in general.

User does not have rating ([Desktop](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/dlVxdm3) & [Mobile](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/ZODxr23))
User has rating ([Desktop](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/zxoPk34) & [Mobile](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/JnVgElk))

**Comment by cgednalske** [comment]
@SKasimow in addition to the screens above, here is the mockup showing an alert ([Desktop](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/09bLrWy) & [Mobile](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/jgR3QKa)) for if there's a connection error for disability rating and we can't show that information.

**Comment by SKasimow** [comment]
Thanks! I'll take a look at this in a bit and ping if I have any q's :)

**Comment by SKasimow** [comment]
Hi @cgednalske - I want to make sure I have the correct links for the UI.

1. Should "Learn more..." go here: va.gov/disability/view-disability-rating/rating)
2. Does Pact Act link here: va.gov/resources/the-pact-act-and-your-va-benefits/)

**Comment by SKasimow** [comment]
Thanks - closing this out now!
