### ISSUE TITLE
Implement CI Pipeline feature for vagov.ddog-gov.com

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-team#49000]
## Issue Description
When VA.gov was still using commercial Datadog, we had access to Datadog's CI visibility feature: https://www.datadoghq.com/product/ci-cd-monitoring/

This gave us clear insight into the status of our GHA workflows, allowing us to see at a glance their health and also set up monitors on their metrics.

If it is available, it would be extremely useful for this feature to be enabled for vagov.ddog-gov.com as well.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] GHA Workflow metrics are available for viewing with Datadog's CI Visibility feature.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alyssagallion** [comment]
We are creating a DOMO dashboard. This is no longer relevant, closing.
