### ISSUE TITLE
Pipeline Automation for Terraform Applies

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#49056]
## Description
We should consider the possibility of moving to automation for Terraform applies vs applying from our local machines.

## Background/context 
https://dsva.slack.com/archives/C0229UT3HSR/p1667237945004299

## Technical notes
Automation already exists for posting a plan of the Terraform changes upon pull request submission: https://github.com/department-of-veterans-affairs/devops/blob/master/.github/workflows/terraform.yml. Decision is mostly about if we want to go this route and how we want to achieve it. There are a couple options that come to mind, both with their own pros and cons:
 - Terraform apply upon merge to master (Occasionally, a plan can look clean and things can go wrong during the apply. Perhaps rare enough to not matter here)
 - Terraform apply based on a comment on the pull request (i.e. `/terraform apply`. Risk here would be that anyone with `write` access could technically kick off an apply)

---
## Tasks
- [ ] Work with the DevOps Community of Practice across the platform to decide the best path forward
- [ ] Potentially implement a solution for applying Terraform in an automated fashion instead of applying from local machines

## Acceptance Criteria 
- [ ] Decision made on path forward
- [ ] Solution implemented in not pit falls are found / risk is not too large

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by mchelen-gov** [comment]
I suggest prioritizing this as it would reduce toil and risk of human error.

**Comment by pjhill** [comment]
Before work on this ticket can begin, we need to evaluate the maturity of the Terraform apply process. We will create a Discovery ticket to detail the gaps in the Terraform contribution process.

There is substantial risk to developing an automated pipeline for terraform applies.

**Comment by pjhill** [comment]
Per recommendation from Kyle, this change represents a substantial risk to the Platform. There are numerous prerequisite efforts that need to be completed before we can address this. Once those efforts have been completed, we will re-asses this effort once the prerequisite tasks are completed.
