### ISSUE TITLE
Investigate Strange Form Behavior

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4906]
## Bug
Continuing the form drops you at the unmarried children page, even if you previously reached the review and submit page.

## Considerations
This might be affected by another team

## Tasks
- [ ] Check and see if this continues or changes after the other issues are addressed

## Acceptance Criteria
- [ ] Define and document in GitHub the issue mentioned above for future use as applicable and/or,
- [ ] Address the issue if possible
