### ISSUE TITLE
Internal - Profile Edge Case - Discovery

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#49063]
## Issue Description
This ticket is to track discovery work to be completed as part of the [Profile Edge Case Request](
---https://github.com/department-of-veterans-affairs/va.gov-team/issues/46861)

## Tasks
- [] Review product outline and other resources provided by team
- [ ] Review current Domo and GA reports
- [ ] Identify meaningful KPIs and creating tracking sheet
- [ ] Review findings/recommendation with Profile team

## Acceptance Criteria
- [ ] When we have completed.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chloedotbrown** [comment]
Sharing the link to the [Profile KPI Discovery spreadsheet](https://docs.google.com/spreadsheets/d/15NKyGxXm9d43iGUoWMxKmo0NZv4gW3dX1sFIeVhGt_I/edit#gid=2091635579) - Samara was very specific in the metrics they wanted included here, so in the interest of getting them what they want, I've broken from our usual KPI framework. 

However, I'm just not seeing some of the events they requested in the their [request ](https://docs.google.com/spreadsheets/d/1TOZ4HNLc-TXjPl32ISvdQ4tq_a7fOpayg8wY6mL2SOE/edit#gid=615520209)or attached GA dashboards. I'm going to reach out to them on their original request to get clarity.

In the meantime, I'd recommend we wrap a mockup in to the discovery phase of this work. I'd be able to work on that even while we're waiting for event specs.

**Comment by chloedotbrown** [comment]
@michelle-dooley - sharing the [Profile mockup](https://docs.google.com/presentation/d/1zzFSi5ZfIDqy5buQZX1NwRjvCA-dwPTDYOaSidCwZlw/edit?usp=sharing) for your review. The metrics in Highlights are the only ones that were explicitly [requested](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46861#issuecomment-1242253959), though the sections below would be supported by the same data and I think would be quite useful. 

Let me know if you have any edits! Alternatively, I could imagine the information in the two outcome charts being broken into several gauges, though I think there's a benefit in the current layout also.

**Comment by michelle-dooley** [comment]
Meeting with team on 11/29. Work will continue on data ticket after mock up sign off from team.
