### ISSUE TITLE
[FE] Pass Users to Check-in when Access Pre-Check-in Link on Day of Appointment During the Check-in Window

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#49077]
## Dependency
[PCI/API Ticket](https://app.zenhub.com/workspaces/pci-api-6149f6401b0b3c001219802f/issues/department-of-veterans-affairs/chip/1330)

## User Workflow
- Given I
    - Click on a Pre-Check-in link on the day of my appointment during the check-in window
- When I
    - Click on the link
- Then I
    - Am automatically taken to the verification page for eCheck-in instead
 
## Implementation

Flow for redirecting will be as follows:
-  user accesses pre-checkin and successfully validates
- show loading screen
- FE calls GET pre_check_ins and fetches appt data
- if within the check-in window for the earliest appointment
   - call TBD vets-api endpoint to upgrade lorota data to check-in
   - if endpoint returns 200, redirect user to day-of check-in with same uuid
   - if endpoint fails, show existing error message
- if not within the check-in window for the earliest appointment
   - show existing error message

## Tasks
- [ ] [FE] Pass Users to Check-in when Access Pre-Check-in Link on Day of Appointment During the Check-in Window
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by acrollet** [comment]
@kanchanasuriya @randomsync @brianseek @wullaski I've added an implementation section with the flow we discussed, please review when you're able. Thanks :-)

**Comment by kanchanasuriya** [comment]
Thanks for adding in the details @acrollet.  I feel we might have to quickly sync up to decide on spinning up a new endpoint vs using the existing vets-api/PatientCheckinsController endpoint with a query parameter.

**Comment by kanchanasuriya** [comment]
Based on the discussion in [Slack thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1677006797771329?thread_ts=1677000411.497189&cid=C02G6AB3ZRS), we will use existing vets-api/PatientCheckinsController GET endpoint with query parameter for hand-off
