### ISSUE TITLE
[BE] Update Travel Claim Submission Controller to call service object 'submit_claim' method

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#49083]
## User Story
As a Veteran who is using eCheck-in to check-in for an appointment, I want to have the option to submit a claim for travel reimbursement when I check-in so that I don't have to later fill out a form or visit the Travel Office.

## Tasks
- [ ] [BE] Update Travel claim submission controller to call the service object's submit_claim method and return appropriate response, add/update specs

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
