### ISSUE TITLE
[Research] Create Conversation Guide

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#49080]
## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- Platform [research process](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html) and [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)

## Description
- Create the conversation guide for testing with users

## Tasks
- [x] Create new folder for this specific test in this [overall research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research).
- [x] Create conversation guide (template in research checklist above)

## Acceptance Criteria
- [x] Review conversation guide with team (particularly product, Kristen, and Patrick)
- [x] Post finalized conversation guide to GitHub folder

**Comment by benbrasso-agile6** [comment]
[Veteran intercept research plan 
](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/2022-11%20Patient%20Check%20In%20Travel%20Reimbursement%20Veteran%20Intercept%20at%20Dayton%20VAMC/research-plan.md)
[Veteran intercept conversation guide
](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/2022-11%20Patient%20Check%20In%20Travel%20Reimbursement%20Veteran%20Intercept%20at%20Dayton%20VAMC/conversation-guide.md)

[Staff interviews research plan 
](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/2022-11%20Patient%20Check%20In%20Travel%20Reimbursement%20Staff%20Interviews%20at%20Dayton%20VAMC/research-plan.md)
[Staff interviews conversation guide (MSAs and travel office staff) ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/2022-11%20Patient%20Check%20In%20Travel%20Reimbursement%20Staff%20Interviews%20at%20Dayton%20VAMC/conversation-guide.md)
