### ISSUE TITLE
[Design] My VA Audit UX Improvements: Create Designs for My VA page Full Page Loading Error

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#49088]
## Background
We discovered that if My VA can not connect to the MPI (Master Persons Index) the entire page may not load and therefore we need to ensure we have designs for an error in the event this happens to our users.

## Tasks
- [x] Create full page error state designs and mockups
- [x] Share designs with team
- [x] Update FE documentation

## Acceptance Criteria
- [x] New designs are created for My VA full page loading error

**Comment by aagosto90** [comment]
@ajakabcin @tmitchellgcio Before I update the FE documentation to include this full page error, wanted to run the mockups by you. [Taylor said](https://dsva.slack.com/archives/C909ZG2BB/p1667936574218559) it looks perfect and confirmed nothing else would load on the page. [I checked with the platform team](https://dsva.slack.com/archives/C01DBGX4P45/p1667850428768479) about what type of error message this should be and they recommended an access message. I also saw [another VA designer asking about a related error message](https://dsva.slack.com/archives/C01K37HRUAH/p1666120954850829?thread_ts=1666117689.238609&cid=C01K37HRUAH) and within that chain realized it doesn't seem like other teams are using alerts for this but are using plain text as is recommended in the content guidelines, so that's the design route I went for this. AJ, let me know if you think I should proceed with FE documentation. Thank you!

**Comment by ajakabcin** [comment]
Hi @aagosto90 - thanks for the rundown here and for being so thorough! I like this approach as well - clean and simple :) Please proceed with the FE documentation when you can!

 Dropping the design you shared in slack in this ticket for context for anyone following along :) 
![My VA Desktop Full Page Error](https://user-images.githubusercontent.com/45603961/201417821-5e2694a0-48a1-49ce-b252-040ed115e65a.jpg)

**Comment by aagosto90** [comment]
I created FE documentation for this [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/full-page-error-FE-documentation.md). It didn't make sense to go within any other FE documentation so I made a new file and put it with the rest of the audit FE documentation. Hope that's a good place for it but I'll move it if not!
