### ISSUE TITLE
[Design] 10-10CG - Improve Facility Selection: Review current designs with team

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#49084]
## Background
Initial designs have been created some time ago on how we should improve the Facility Selection page on the 10-10CG, within the Veteran information section.  
We need to review the current designs, discuss options and technical constraints, propose changes, and decide on a path forward.

This should be a collaboration between Design and Engineers.

## Tasks
- [x] Review current designs with the team
- [x] Document discussions and decisions
- [x] Update designs as needed
- [x] Share updates with the team

## Acceptance Criteria
- Designs will be reviewed and a decision will be made on a design proposal

## Ideas
- Include additional filtering
  - Current idea: filter by city
  - Can potentially filter on additional pieces of metadata that's available
- Create easy-to-read cards to display facility information
- Add link to facility selection page

**Comment by jessicastump** [comment]
Working/review session with 1010 team recap and next steps:
Met 1/13/23 to review current and past designs in [Sketch file here](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/p/D741171D-81BD-4CEF-A7A2-69A548C8D346/canvas#About)

Next steps: 
- Meet with accessibility and design system team about card options using secondary buttons vs radio buttons with address label for any concerns before design refinement
- Limit content on cards/radio labels to facility name, street address, remove any other links or miles away references
- Search for facilities needs to be by state or zip with a narrowing filter of city - unless there are options to map coords for city search via back end
- Refine to 3 options for initial concept testing
- Explore possible testing on coded designs/accessibility
- Work on revising research plan and convo guide to a/b/c test only the facility question(s) and if the participant can clearly understand what is being asked and how the info will be used/the impact to them as caregivers

**Comment by jessicastump** [comment]
Found out the process right now for accessibility help is to join Collab Cycle office hours, signed up for next Wednesday 1/18 at 11:30am ET/8:30am PT. @nicko-amida I added you to the invite
