### ISSUE TITLE
[DESIGN] Create Prototype for Household Section in UXPin

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#49089]
## Issue Description
Create the prototype in UX Pin to use during the household information section initial research. Create the unauthenticated path of all pages/questions from the standard introduction page through to the end of the household information section (step 4 of 6 of the 10-10EZ Form)

---
## Tasks
- [x] Create [desktop prototype ](https://preview.uxpin.com/6a98bfd8c3a76816b8695fbdc6883bd477610024#/pages/159024257)of all screens through the end of the household section
- [x] Create [mobile prototype](https://preview.uxpin.com/0d51ae969e349ebcf115f993fe29af216eccd6d9#/pages/159616318) of all screens through the end of the household section

## Acceptance Criteria
- [ ]  There is a functioning prototype to use during usability tests on the household section.

**Comment by nicko-amida** [comment]
@jessicastump The desktop and mobile prototype for the household sections are in place! I think I would still like to run through them to catch any bugs, and adjust the convo guide if needed to account for how we want to guide people through the prototype.

**Comment by jessicastump** [comment]
@nicko-amida Meeting scheduled for us tomorrow to do a walk-through so we have time to make the changes we just talked about today: mobile header, additional dependent, remove gender identity question.
