### ISSUE TITLE
[FE][TECH DEBT] - Refactor API calls to use a query builder for params.

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#49082]
## Description
A great suggestion from Mark in the data persistence PR was to use a library to manage query params. This ticket is to apply that to all of our API fetching utilities. 

appendQuery is already installed and works well.

## Tasks
- [ ] [FE] update query param building to use appendQuery.
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Closing since there is no further validation to be done.
