### ISSUE TITLE
Increase spacing around form navigation buttons

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#49092]
## Description

The back and continue form navigation buttons are in close proximity (around 8px) to the "Finish this application later" link above and save-in-progress status alert below.

<img width="557" alt="finish this application later in very close to the top of the form back button and the top of the save in progress alert is very close to the bottom of the back button" src="https://user-images.githubusercontent.com/136959/199312602-933b820c-508f-40fe-bfd5-7af9598d30d0.png">

We should at least double this spacing.

Additionally, the space between the "Finish this application later" and "Open save-in-progress menu" links need to be doubled.

## Tasks

- [ ] Add vertical spacing around the form navigation buttons
- [ ] Add horizontal spacing between the finish this application and save-in-progress menu links

## Definition of done

- [ ] Spacing added
- [ ] Design review of result
