### ISSUE TITLE
Design | Profile | Fiduciary Flag Alert Across Profile

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#49118]

**Comment by SKasimow** [comment]
## Background

Update all relevant product documentation once #48151 is in progress/completed.

## Tasks
- [ ] Update sketch files 
- [ ] Update use cases
- [ ] Update user flow (if needed)
- [ ] Update call center guide

## Acceptance Criteria
- [ ] All tasks have been completed
- [ ] Notify PM that call center guide is updated

**Comment by andaleliz** [comment]
FYI @SKasimow I'm picking this up for the current sprint.

**Comment by andaleliz** [comment]
@Samara-Strauss I'm not going to publish the use case doc until the feature is live, but here's a draft. Can you please let me know if this reads OK to you? I grabbed the user info from the direct deposit fiduciary use case (which I'll point to this new page once it's created).

--- 

# Profile: User with a blocked account attempts to access any section of profile

**Last updated**: November 28, 2022

Currently, we block access to sections other than Account Security if a person has a flag on their account.  We get these flags from the endpoint. A flag could be present if a person:
- has a fiduciary
- has been deemed incompetent
- is marked as deceased

When an account is blocked, we show an alert on the account security page. The original implementation of this blocking started with direct deposit and was expanded to all of profile in November 2022. Please read the  [documentation from 2.24.20 in the sensitive repo](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2020/2020-02-21%20Direct%20Deposit%20Fiduciary%20Issue.md)  for more background information.

## UX
- When a user with a blocked account navigates to profile, they’ll only see the Account Security page; no other pages in profile are available from the profile navigation menu.
- If they click a URL that leads directly to any specific page under `/profile/` they're redirected to `/profile/account-security`.
- [Desktop mock-up](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/v/vqA79n/a/PG4Pm2j)
- [Mobile mock-up](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/a/g09lryk)

## How to reproduce
1. Log into staging with any of the following users:
* User 0
* Incompetent, no fiduciary: User +61
* Incompetent + fiduciary: User +65
* Deceased: User +33

2. Navigate to profile or update the URL in your browser to point to `/profile/direct-deposit` or any other section of profile aside from `/profile/account-security`

**Comment by Samara-Strauss** [comment]
This looks great! Thank you, Liz!

**Comment by andaleliz** [comment]
This is complete. I created a new use case document for blocked accounts, and updated use cases for:
- [Account security](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/account-security/use-cases/README.md)
- [Direct deposit](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/use-cases/flag-fiduciary.md)

I also removed the mock-ups from direct deposit showing the alert in that section, and [documented the change in the iterations page for that Sketch file](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/1Kbn7Oa).

**Comment by Samara-Strauss** [comment]
This all looks great! Thank you, Liz!
