### ISSUE TITLE
Allow for successful submission page with FSR background processing

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#49110]
## Issue Description
The submission page right now is coupled with the statuses we get back from VHA and VBA for GA events. Since this processing is being moved to the backend we need to account for these statuses not being available

---
## Tasks
- [x] Strip references to VHA and VBA status
- [x] Assure that GA events will still be triggered

## Acceptance Criteria
- [ ] Page remains working as intended but with events happening asynchronously
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
