### ISSUE TITLE
[UX] Handoff as Kristen Transitions off the Team

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#49136]
## Tasks
- [X] Export or move Murals
- [x] Move VSignals spreadsheet to someone else's OneDrive
- [x] List of UX contacts on other teams
- [x] Document ideas for making appt info consistent with VAOS
- ~Off-boarding ticket for Platform?~

**Comment by loripusey** [comment]
k, did a strike out

**Comment by kristenmcconnell** [comment]
Ben and I met and moved over two still relevant Murals to the A6 space.

**Comment by kristenmcconnell** [comment]
List of contacts send to Ben and Lori via Slack.

**Comment by kristenmcconnell** [comment]
I updated the VSignals directions with more details after talking to @benbrasso-agile6. Ben is going to move the VSignals folder to his OneDrive space. I'm adding him to this ticket, so he can mark when that task is done.

**Comment by benbrasso-agile6** [comment]
This has been copied over to my drive. I shared the folder with Lori and Kelly. What are these two files at the root of that folder? Do I need them? 

<img width="846" alt="Screen Shot 2022-11-10 at 9 58 16 AM" src="https://user-images.githubusercontent.com/101129355/201126325-23ae6a06-7354-4114-84ae-b3c637131d5a.png">

**Comment by kristenmcconnell** [comment]
@benbrasso-agile6 Ask @kellysmith1008  if she is done with the 11 7 file. She created it earlier this sprint when she started analysis. We talked about doing everything in the main file, so the 11 7 file should be able to be removed if she agrees.

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 I gave you access to the "new" folder in my one drive. I would recommend saving those two orphan files into the new new folder when you're at a good stopping point.

**Comment by kristenmcconnell** [comment]
[Proposal on how check-in can become more consistent with VAOS.](https://app.zenhub.com/files/133843125/90eff2e0-5d39-4380-97d1-8a42e569d9f0/download)
@loripusey @benbrasso-agile6 Let me know if you have any questions or want to meet to review/discuss.

**Comment by loripusey** [comment]
I think the ideas are worth exploring
