### ISSUE TITLE
Supplemental Claims | User Analytics

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#49138]
## Value Statement
**_As a_** Veteran
**_I want to_** submit a claim that is likely to receive a favorable outcome
**_So that_** I can get disability compensation benefits. 

---
## Background Context
This story covers analytics for the supplemental claim form. AC are TBD.

## Tasks
- [x] Review and refine draft metrics with the internal team
- [x] Review and refine draft metrics with the Alejandro
- [x] List product URL(s), including any unauthenticated landing pages that precede Supp Claims
- [x] Schedule time with the Analytics team to confirm if/how to track desired metrics

**Comment by saderagsdale** [comment]
Waiting for Alejandro to reply with their availability to review the data analysis and dashboard he created. Sent a follow-up on 10/31 and again on 11/7.

**Comment by saderagsdale** [comment]
Sent another follow-up today.

**Comment by saderagsdale** [comment]
Meeting with Michelle later today.

**Comment by saderagsdale** [comment]
Robin will ping us when it's time to meet with Michelle again.

**Comment by Mottie** [comment]
Analytics updated in staging (using #50625 as ticket). We can ask Michelle to review the analytics.
