### ISSUE TITLE
Migrate blue boxes under "Top tasks" into the design system repo

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#4913]
### Description
The blue boxes under "Top tasks" are a common component on the website, so we should put them in our shared component library (the design system [repo](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools)) so that other engineers can see they're available on our [client doc site](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/). I didn't know these blue boxes are already on Pittsburgh Health Care, so I ended up recreating it for Find Forms and wasting some time.

Note - This doesn't make it available on design.va.gov, but if we choose to add it there, then that'll be easy once this is done.

##### Find Forms
https://dev.va.gov/find-va-forms-beta/

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/062e70ff-c27a-4216-b05c-07b077e4ebe4)

##### Pittsburgh
https://www.va.gov/pittsburgh-health-care/health-services/

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/a54c15f6-56cd-42de-a467-0b793ff2ae7c)

### Tasks
- [ ] Move code from vets-website repo to design system repo (1 hour)
- [ ] Update code to align with design system standards (4 hours)
- [ ] Publish new Formation version containing component
- [ ] Update vets-website to use new Formation version
- [ ] Update references to blue box component to use design system HTML/React component

### Acceptance criteria
- [ ] Blue boxes have been published into shared code repo

**Comment by kevwalsh** [comment]
In case it's helpful here's a screenshot of the editorial experience for /pittsburgh-health-care/health-services version of this component  

![Edit_VAMC_system_VA_Pittsburgh_health_care___VA_gov_CMS](https://user-images.githubusercontent.com/643678/72473563-fc9cd900-37b4-11ea-92d0-0a5df24a139d.jpg)

It's definitely MVP, when we implemented this we knew that there would be more of these coming along.

**Comment by jenniferlee-dsva** [comment]
@kevwalsh is the blue box/card Pittsburgh component AX available on pages outside Pittsburgh site?  Here is the page @RLHecht built in Drupal: https://prod.cms.va.gov/find-va-forms

**Comment by jenniferlee-dsva** [comment]
@kevwalsh - Would like to close this item one way or the other. Are these blue card components (used on Pittsburgh VAMC site) available to use on VA.gov Drupal ax? 

If so, we want to move these out of the REACT component and move them in to Drupal body content.

**Comment by MickinSahni** [comment]
@kevwalsh hey kevin, do you have an update? we'd like close this out as we move forward with the launch of form search mvp.

**Comment by ncksllvn** [comment]
Blocked, because the Featured Content content model was designed specifically for the Health Services page, so it isn't re-useable for us.

**Comment by kevwalsh** [comment]
Hi @MickinSahni i responded in a [thread on slack](https://dsva.slack.com/archives/CDHBKAL9W/p1582573551001300).  This wouldn't be a big lift, but it will require some discovery and we'll need to figure out how to support it across multiple content types / products.

**Comment by MickinSahni** [comment]
Thanks, @kevwalsh! Do you have a super rough estimate of how long that might take?

@AkucherGCIO @ncksllvn @jenniferlee-dsva - I'll leave it to you to decide. Jen's question a couple weeks ago lends me to believe that this isn't required quite yet.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/4913#issuecomment-582479866

**Comment by jenniferlee-dsva** [comment]
^ Correct, thanks @MickinSahni. @kevwalsh @AkucherGCIO @ncksllvn   - it's not needed to launch the search page. 
But for ongoing maintenance, the content that's currently inside those blue boxes should be accessible and editable in Drupal, the way that component is today on the Pittsburgh site.

**Comment by kevwalsh** [comment]
@MickinSahni It's hard to say. i'd recommend a meeting with few product designers to discuss this component, including someone from VSA-facilities to represent the VAMC system product, and from Benefits Hubs (your team), and possibly the design system. I can imagine that in the benefits hubs re-design slated for later this year, some version of this will be leveraged. it would be worth looking for some use cases in that content. 

We have to determine if this is a single consistent component, several different components, or a single component with several variants.  It's also very consistent in structure, content-wise, to the existing "list of link teasers", it's just the display that's quite different. The question is: what are the rules that should drive the use of one over the other?

**Comment by kevwalsh** [comment]
@MickinSahni adding to that: I wouldn't expect the actual drupal and front end implementation to take that long!  It would only get expensive if we don't get it right the first time.

**Comment by AkucherGCIO** [comment]
03/04/20 PW Grooming
This item will not affect the Launch of Find VA Forms - Search.

**Comment by AkucherGCIO** [comment]
03/11/20 Sprint 17 Planning
A task that Beth from CMS team can work on - not a super high priority.

**Comment by jenniferlee-dsva** [comment]
Not a high priority but getting it out of icebox for visibility for Beth Jacobson. @beeyayjay 

@rtwell to please lead getting this into the design system (the blue cards with text and link). 
Ryan, we can talk about the [question re requirements/design and content specs](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/4913#issuecomment-591081599) that Kevin raises above. Since this is identical to what Pittsburgh uses, I think we can easily reuse the same without adding a lot of complexity. Maybe make it able to accomodate a button instead of a link.

**Comment by ncksllvn** [comment]
@swirtSJW or @kevwalsh I'm guessing this is still awaiting implementation in Drupal? Thinking about iceboxing it

**Comment by kevwalsh** [comment]
@ncksllvn are you thinking about this in the context of Forms or some other PW product?

**Comment by ncksllvn** [comment]
It would be an improvement to Forms but I think this would make the blue boxes available globally

**Comment by kevwalsh** [comment]
@ncksllvn i discussed this with @jenniferlee-dsva briefly this morning, it's in the icebox for now.

**Comment by MarciMcGuireGCIO** [comment]
Pulling this out of the Post-Launch MVP since there are too many unknowns.    Moving back to icebox.
