### ISSUE TITLE
[FSR] Review Page Design Discovery

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#49159]
## Issue Description

Technical ticket #58552 contains details on available data that still needs to be included.

#57484 was a precursor to the above ticket and is an audit of the review page containing the missing features in the eFSR compared to the FSR.

Review Page Research:

- [Monday design meeting presentation](https://dsva.slack.com/archives/C0NGDDXME/p1661188702394559?thread_ts=1661173201.128189&cid=C0NGDDXME)
- [Research findings report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/pst-forms-library/research/review-page-round-two/round-2-research-findings.md)

References: 

- Aaron's [Dependent review page PR Slack thread](https://dsva.slack.com/archives/CPE4AJ6Q0/p1683322426802949)
- [Inline errors](https://dsva.slack.com/archives/C01DBGX4P45/p1681138571443339) Adapt [supplemental claims form solution.](https://sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89)

---
## Tasks
- [x] _Review past research on review pages_
- [x] Create mockups for MVP version of each section of the Review page 
- [x] Create userflow with MVP version and ideal version of review page flow
- [x] Attend design office hours and ask about best practices on 06/13
- [x] Meet with the engineering team to discuss the feasibility of editing in place vs editing back into the form.
~~Design [clear error messaging](https://github.com/department-of-veterans-affairs/vets-website/pull/24467) and figure out how content should be grouped together on the review page.~~

## Acceptance Criteria
- [x] Clear mockups for what the engineering team needs to implement
- [x] Clear user flows to show where the edit section buttons should take you back into the form and how to get back to the review page
- [x] Met with platform on 06/13
- [x] Design files show how to present the information on on the review page and what fields should be grouped together.

**Comment by HeatherRienks** [comment]
Per Backlog Refinement mtg on 5/3, let's discuss this further in Design Sync on 5/9. 

cc: @charlottecesana @josephrlee @mgleo

**Comment by HeatherRienks** [comment]
Per 6/6/23 Design meeting, we need to discuss editing the Review page with Platform. Do they have any suggestions/requirements?

Will discuss the scope of this work in Sprint Planning on 6/7/23.

**Comment by mgleo** [comment]
@HeatherRienks @Tom-Davis Closing and continuing work on #60560

**Comment by HeatherRienks** [comment]
As of 6/20/23, we will close this ticket and create new ticket (Link to be added) to finalize FE discovery work.
