### ISSUE TITLE
Intermittent 403 with staging copays users

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#49158]
## Issue Description
We are intermittently running into issues with copay errors due to staging users missing EDIPI among other values. This at first glance appears to be an identity data or MPI issue.

---
## Tasks
- [x] Start conversation with identity team to discuss missing data
- [ ] Depending on conversation, take steps to fill in data
- [ ] Possibly create LETT ticket to add values to MPI 

## Acceptance Criteria
- [ ] Intermittent errors are resolved
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Awaiting confirmation that updating EDIPI through MPI will not break current identity for these users

**Comment by ScottyRJames** [comment]
PCE has been removed from EDIPI MPI suffix
