### ISSUE TITLE
[BE] Set up Error Log monitors in Datadog

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#49181]
## User Story
As an on-call engineer in CIE team, I want to get alerted for sentry errors in CIE Slack APM channel if any user request fails in production so that I can work on mitigating the issue

## Tasks
- [ ] [BE] Stream sentry errors to datadog
- [ ] [FE] Setup error log monitors

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by kanchanasuriya** [comment]
Investigated error events streamed to datadog from sentry.  Most of 4XX errors were related to expired data or authentication error.  Error status code 500 thrown for Internal server error, were actionable and worth getting notified.

Discussing with @acrollet and @brianseek, [sentry 500 monitor](https://vagov.ddog-gov.com/monitors/102168) set up to notify error in apm slack channel.
