### ISSUE TITLE
PM | Profile | Address Validation | Adt'l Analytics

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#49193]
## Background

During the recent research sessions we observed that some users were confused by the address validation process. One issue noted was that during the editing process if a user does not save or cancel their changes they will see a modal that informs them that they are in the middle of editing and need to save their changes (see screenshot below). 

We want to determine how many users see this modal during the address validation/editing flow bc they have not saved or canceled their changes. Analytics can help inform us on the severity of this issue.

**Screenshot:**
![Screen Shot 2022-10-21 at 1.44.45 PM.png](https://images.zenhubusercontent.com/5fb57aafa11eae0592a15cb1/9d519a49-b2be-4e84-9e48-9309c03d48ad)

## Tasks
- [x] Utilize GA to pull metrics around the address validation flow including:
- how many sessions have multiple instances of viewing this alert, compared to those that have 1 or none?
- compare the modal metric to "page views with a click of the edit button (indicating someone tried to edit something)"
- [x] Share findings with team/design
- [x] Attend Analytics office hours if needed

## Acceptance Criteria
- [x] Metrics around address validation flow are shared with team
- [ ] Open Design ticket to address improvements

Associated Ticket: #48439

**Comment by SKasimow** [comment]
## Background

During the recent research sessions we observed that some users were confused by the address validation process. One issue noted was that during the editing process if a user does not save or cancel their changes they will see a modal that informs them that they are in the middle of editing and need to save their changes (see screenshot below). 

We want to determine how many users see this modal during the address validation/editing flow but do not properly save or cancel their changes. Analytics can help inform us on the severity of this issue.

**Screenshot:**
![Screen Shot 2022-10-21 at 1.44.45 PM.png](https://images.zenhubusercontent.com/5fb57aafa11eae0592a15cb1/9d519a49-b2be-4e84-9e48-9309c03d48ad)

## Tasks
- [x] Utilize GA to pull metrics around the address validation flow
- [ ] Share findings with team/design
- [ ] Attend Analytics office hours if needed


## Acceptance Criteria
- [ ] Metrics around address validation flow are shared with team


Associated Ticket: #48439

**Comment by SKasimow** [comment]
Attaching analysis on 1) how often the modal is displayed on average and 2) the percent of sessions (unique events) that view the modal after clicking "edit":

[https://app.zenhub.com/files/133843125/be267974-e996-4ff4-9220-f7fa2261823d/download](https://app.zenhub.com/files/133843125/be267974-e996-4ff4-9220-f7fa2261823d/download)
