### ISSUE TITLE
[FE] Enable Datadog RUM in prod

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#49198]
## Background
Once @stephenBarrs has approved moving forward, we should deploy RUM in production.

## Tasks
- [ ] [FE] Create devops PR to enable CSP for datadog in prod (following the [lower envs PR](https://github.com/department-of-veterans-affairs/devops/pull/12165)) and request revproxy deploy from Ops
- [ ] [FE] Enable `check_in_experience_browser_monitoring` ff for prod
- [ ] [FE] confirm that RUM is sending data from prod
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by acrollet** [comment]
@stephenBarrs reviewed existing practice and policy and gave the go-ahead for this.

**Comment by acrollet** [comment]
Devops PR is [here](https://github.com/department-of-veterans-affairs/devops/pull/12192)

**Comment by acrollet** [comment]
Requested revproxy deploy, it will go out Monday: https://dsva.slack.com/archives/CBU0KDSB1/p1667574912271139
