### ISSUE TITLE
Curl MPI Documentation

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#49194]
## Tasks
* [x] cURL MPI instructions
* [x] cURL MPI sample request
* [x] rails console MPI interaction
