### ISSUE TITLE
[Design] My VA Payments v2: Use case documentation 

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#49196]
## Background
As part of the recent implementation of payments v2, we need to make sure all of My VA use cases are documented and up to date in github.

[Use case documentation folder in gh](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/use-cases)

## Tasks
- [x] Create use case documentation 
- [x] Review with PMs/PO

## Acceptance Criteria
- [x] Uses cases for My VA benefit payments and outstanding debts are captured in github and follows the correct document structure.

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ PMs
- _How can this work be validated?_ review documentation in github and confirm structure and contents are accurate before requesting PO review

**Comment by aagosto90** [comment]
Thank you so much for taking the time to review everything and provide feedback @Samara-Strauss !

- I added an overview of [outstanding debts](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/use-cases/outstanding-debts-use-cases) and [benefit payments](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/use-cases/benefit-payments-use-cases) to each use case landing page.
- Yes, [added a sentence about that and linked it to the no outstanding debts use case.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/use-cases/outstanding-debts-use-cases/overpayment-debts.md#ux)
- Yes, good point! I added links to [mockups for when a user has both overpayment and copay debts.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/use-cases/outstanding-debts-use-cases/copay-debts.md#ux)
- So [there's a section in here for no payments ever](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/use-cases/benefit-payments-use-cases/no-recent-payments.md#user-has-never-received-payments-from-va) since that also means they haven't received a payment in the last 60 days, but I could split this up into two use cases:
* User has not received a payment from VA in the last 60 days but has in the past
* User has never received payments from VA
I don't have a strong preference so let me know if you think that'd be more clear to outsiders.

**Comment by Samara-Strauss** [comment]
> So [there's a section in here for no payments ever](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/use-cases/benefit-payments-use-cases/no-recent-payments.md#user-has-never-received-payments-from-va) since that also means they haven't received a payment in the last 60 days, but I could split this up into two use cases:

It looks like you already split it up, and I like the way you have it!

Everything else is great. Thank you!!

**Comment by aagosto90** [comment]
Awesome, thanks Samara! Closing this ticket then.
