### ISSUE TITLE
[Design, PM] Payment info v2:  Documentation review/updates for Payments v2 (within My VA outline)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#49197]
## Background
Post launch of My VA payments v2 we need to review all of our design, FE and technical documentation to make sure everything is up to date and reflects the current implementation of My VA. This is a joint effort from all team members, though we have specific tasks for each of us.

## Tasks
- [x] Write [use cases](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/use-cases)
- [x] Create user flows
- [x] Updates to Product Outline (PM)
- [x] Review with PMs/PO

**Comment by ajakabcin** [comment]
reviewed use cases and project outline. I added a brief description in the "[feature overview](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/README.md#feature-overview)" section of the guide leveraging similar language from Angela's use cases for consistency. Done!
