### ISSUE TITLE
[DISCOVERY] Research and document all data required in Lebanon, PA System in order to build Facilities web pages [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#4920]
## User Story or Problem Statement
As a Veteran Web user, I want to see the local Faculties page, so that it highlights travel, parking, lodging, local amenities, hours of operation, health services, and non-health services offered. 

## Goal
_Highlight the Individual FACILITY'S Page with veteran needed information_

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran traveling to each facility_
- _Reduce Click through count by_Highlighting top stories_

## Tasks
_Complete moves from legacy websites to CMS Stories, News Releases, and Events to include:_
- * Create a spread sheet highlighting all of the Lebanon, PA facilities:
- [x] Lebanon VA Medical Center
- [x] Berks County VA Clinic
- [x] Cumberland County VA Clinic
- [x] Landcaster County Va Clinic
- [x] Schuylkill County VA Clinic
- [x] Yourk VA Clinic
- * Spreadsheet must highlight the main areas of information:
- [x] Parking
- [x] Transportation
- [x] Visitor hours and Info
- [x] Lodging
- [x] Dining and Retail
- [x] Special non-health services 
- [x] Confirm social media accounts (facebook, twitter, etc)

## Acceptance Criteria

* Create spreadsheet with the required facility page information.
* Confirm an special non-health services
* Document is published in Share Drive and named by Facility

**Comment by EdwardBoehme05** [comment]
Stan, here is the link to my facilities spreadsheet (VAMC_Site_Playbooks, Lebanon_PA, Facilities_Lebanon_v04.xlsx  :
https://drive.google.com/open?id=1-XXwCMbsV9eKf9RSY4_J2XFCkYVCzlqS
