### ISSUE TITLE
Fix bullets in Must, Should, Consider Framework for Feedback

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#49218]
## User Story
As a VFS team member, I want to understand how to interpret feedback from Governance team received at the Design Intent and Midpoint Review so that I know how to respond and/or take action with my product.

Assignee: @CherylEvans 
Peer Reviewer: @it-harrison 

## Background
Authenticated Experience came to the Collab Cycle Office Hours on 11/2 and challenged some of the _must_ feedback that had been provided in the [Design Feedback ticke](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48655)t at the previous weeks Midpoint Review. In reviewing their PM's follow up comments on the ticket, we recognized that the VFS team interpreted the _must_ feedback as launch-blocking feedback. This is because the current [Must, Should, Consider Framework for Feedback](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback) guidance on Platform Website states that _must_ feedback, if not addressed, will likely result in a launch-blocking issue. This is not true.

## Description
The [Must, Should, Consider Framework for Feedback](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback) guidance on Platform Website is incorrect, specially for _must_ feedback. _Must_ feedback, if not addressed, may result in a documented issue at Staging Review. Whether that issue is launch-blocking or not is dependent on the standard the issue violates. The purpose of this ticket is to update the bullets under Must, Should and Consider to accurately state whether or not this will result in a documented issue at Staging Review if not addressed. All references to launch-blocking or non-launch-blocking should be removed from the Must, Should, and Consider bullets. 

This ticket will also add a clarifying sentence to the intro paragraph stating that this guidance will only help VFS teams determine if the identified issue will result in a documented issue at Staging Review. Whether or not the documented issue is launch-blocking will depend on the severity of the VA.gov Experience Standard that the issue is in violation of.

## Impacted Artifacts
[Must, Should, and Consider Framework for Feedback](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback)

## Tasks
- [x] Under Must, delete bullet, "Must be brought into alignment with the design principles before launching on VA.gov"
- [x] Under Must, modify bullet, "If not fixed before Staging Review, would likely be flagged as a major issue and block the release of the product." to state, "If not fixed before Staging Review, would likely be flagged as an issue violating the VA.gov Experience Standards." 
- [x] Under Should, modify bullet, "If not fixed before Staging Review, could be flagged as a major issue and block the release of the product" to state "If not fixed before Staging Review, could be flagged as an issue violating the VA.gov Experience Standards." 
- [x] Under Consider, modify bullet, "If not fixed before Staging Review, likely won’t be flagged as a major issue or block release of the product, but may adversely affect user experience." to state, "If not fixed before Staging Review, likely won’t be flagged as an issue violating the VA.gov Experience Standards, but may adversely affect user experience."
- [x] Move entire "Why feedback matters" section AFTER Consider section. This excludes the sentence starting with, "After the Design Intent and Midpoint Review..." as this is the intro paragraph
- [x] To the intro paragraph, add a new sentence, "The Must, Should, Consider Framework for Feedback does not indicate whether an issue will be launch-blocking at Staging Review. Whether or not the documented issue is launch-blocking will depend on the severity of the VA.gov Experience Standard that the issue is in violation of." (feel free to wordsmith)
- [x] Change section heading, "The three feedback categories are detailed below:" to "The three feedback categories" - no colon
- [x] Draft a post for Slack and Change history

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS teams understand how to interpret must, should, and consider feedback at the Midpoint Review and Design Intent
- [x] VFS teams understand that the must, should, and consider feedback does not indicate whether or not the issue will be launch-blocking at Staging Review

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
@it-harrison Hi Ian.  Here is the [Draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2430468266/49218+-+Cheryl+Draft+-+Copy+of+Must+Should+and+Consider+Framework+for+Feedback) for Must, Should, and Consider Framework for Feedback.  Please see the tasks above to see what was changed.  You will notice that I changed some of the recommended verbiage because I felt that it sounded better.  Let me know if you have any questions or concerns.  Thank you!

**Comment by it-harrison** [comment]
@CherylEvans Looks good!

**Comment by CherylEvans** [comment]
@shiragoodman @it-harrison Please review my [Draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2434007041/49218+-+Draft+Cheryl+Copy+of+Copy+of+Change+history) Change History post, and recommend changes/edits.  Thank you!!

**Comment by it-harrison** [comment]
@CherylEvans the Draft Change History Post looks good - just think you want to change December -> November.

**Comment by shiragoodman** [comment]
@CherylEvans i made some suggestions to the change history draft.
