### ISSUE TITLE
Make content changes to vaccine CLP to keep info up to date

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#49216]
## Issue Description
We have some outdated information on the [COVID-19 vaccine CLP](https://www.va.gov/initiatives/have-questions-before-you-get-your-covid-19-vaccine/) that needs to be revised. 

In the accordion "Will the vaccines work for new forms (variants) of the coronavirus?" we still have content about the Delta variant and the "new" Omicron variant that needs to be removed and updated. We have more current content on our health care pages that we can use in its place.

We could also add a question about how Novavax is more of a standard vaccine. We recently added this information to our main vaccine and booster pages as well and can use that same content. 

While we are making these changes, we should also do a read through the CLP to ensure there isn't other outdated content that should be removed or updated.

## Tasks
- [ ] Review CLP to determine what outdated information should be changed/removed (Aliyah)
- [ ] Add FAQ about Novavax (Aliyah)
- [ ] Review (Laura)
- [ ] OCTO-DE review (Danielle)
- [ ] Copyedit (Megan)
- [ ] Publish (Megan)

## Acceptance Criteria
- [ ] CLP is live with most updated vaccine information

**Comment by aliyahblackmore** [comment]
Wanted to circle back to this ticket and add a few some notes after doing a review of this page! I'll add these as drafted changes after we publish the 2/6 video swap! 

1. **In accordion "Will the vaccines work for new forms (variants) of the coronavirus?"** I'd suggest that we leave in the text in the beginning and remove the current bulleted list and add in this text from the COVID-19 Booster page: 

Here’s what we know from the Omicron surge:

    People who were vaccinated were much less likely to get very sick or die compared to people who weren’t vaccinated.
    People who had a booster shot had even better protection.

The updated (bivalent) boosters protect against both the original virus strain and the Omicron variant. An updated booster will protect you even more against COVID-19.

I'm wondering if we can remove the sentence that begins with "We don’t yet know how strong the current vaccines' protection will be against the new Omicron variant." 

I think that we'd want to link out to this section on the main COVID-19 vaccine page: "How to get a COVID-19 vaccine at VA" Link text:  Learn how to get your vaccine at VA 

2. **Regarding adding in info about Novavax**, I wonder if we'd consider this a standard vaccine or if we'd just want to share that this is now an FDA vaccine option? From the main COVID-19 vaccine featured content box, there is information about Novavax also being authorized as a first booster for people ages 18 and older in limited cases.  I'm wondering if we'd want to pull in a question about the currently available vaccines, or if we'd want to include content specific to Novavax. 

For info on currently available vaccines, I'd suggest we pull in content from the main vaccine page in section **Before you get your vaccine** in accordion "Currently available COVID-19 vaccines"

3. **Other changes:** 

Download more helpful resources:
I think we need updated fact sheets - for example, the 8 important facts PDF has no information about Novavax.

**Comment by aliyahblackmore** [comment]
Hey @RLHecht - are we okay to close this ticket?

**Comment by RLHecht** [comment]
yes, thank you! Closing!
