### ISSUE TITLE
[PM] 10-10EZ - Military Branches: Review Service Branch Lists

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#49214]
Quoted from Patrick:
> as you may recall, a new service branch — space force — was created a few years back. persons are now separating from the space force and applying for VA benefits and services. we've been asked to look for and update any content that mentions service branches (e.g., army, navy, etc...) to include space force.

We need to review any lists of service present in the 10-10EZ to ensure that Space Force is listed in there, as well as confirming if any branches are missing.

![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/0516f908-7c95-4084-8088-9e7dbfe35074)

## Tasks
- [x] Review list of service branches on Service History page on the 10-10EZ
- [x] Confirm all branches listed are eligible for VA health care
- [x] Determine if any branches are missing
- [x] If any branch is missing, inform PM and plan to implement update, if no branch is missing, make a comment and close ticket.

## Acceptance Criteria
- The list of eligible service branches on the 10-10EZ Service History page is complete and accurate.

**Comment by hdjustice** [comment]
Check out National Guard, should it be here???

**Comment by jadon1979** [comment]
I spoke with Josh Faulkner regarding this.  The list is actually smaller as we only use the main US branches.  ES does not have validations for the service branch.  Suggestion is to leave the list as is.
