### ISSUE TITLE
Optimize UsersController to Reduce Number of Timeouts

### ISSUE THREAD

**Issue by rjohnson2011** [department-of-veterans-affairs/va.gov-team#49239]
### Background
Both web & mobile UsersControllers have 15 seconds timeouts that are triggering repeatedly, causing request/responses to take upwards of 1 minute each.

![image.png](https://images.zenhubusercontent.com/5fb40598d06a06671e842a63/ff30b4dd-3bbf-4394-8b3b-8c5062406ef8) 

Looking deeper into the timeout request shows the following endpoint triggering the timeout:

![image.png](https://images.zenhubusercontent.com/5fb40598d06a06671e842a63/8a30d177-6dd8-4d3e-bb8e-ad0503590b01)

### Tasks

- [ ] Reach out to MHV API team to discuss our latency findings and look for issues that may be causing timeouts.
- [ ] Establishing contact w/ who maintains server and chat about scaling up dynamically.
- [ ] Look into documentation and codebase for MHV to discover any possibility for optimizations.
- [ ] Implement any additional monitoring or potential improvements.

**Comment by rjohnson2011** [comment]
Reached out to the #mhv-secure-messaging channel regarding the read timeouts being hit via the UsersController https://dsva.slack.com/archives/C03ECSBGSKX/p1667493888830439

Have still not heard back from anyone. Will discuss during standup if there's a particular point of contact to reach out regarding this issue.
