### ISSUE TITLE
FE  | Profile | Notification Settings| Update flow for adding a Mobile #

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#49251]
## Background
During the recent research sessions we observed that users were disrupted by having to leave the notifications preference page to add their mobile number. We re-visited the existing design for this flow and considered a few alternatives. 

After discussions with the team, I/A and others, we have decided to move forward w/ a single URL: ` /profile/edit/`

#### Outline of user experience:

<img width="817" alt="image" src="https://user-images.githubusercontent.com/55992116/197594531-98a5be89-f5ac-4a3c-8fb2-f95973734f11.png">

#### The mock-ups are below:

- [Mobile form](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/v8ej4q3)
- [Desktop form](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/wLGk4J9)
- [Mobile page w/ confirmation message](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/4al7YGJ)
- [Desktop page w/ confirmation message](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/WKLzddk)

## Tasks
- [ ] Review mocks and identify the work required for FE 
- [ ] Identify whether there will be any work outside of FE needed
- [ ] Define high-level stories that can be used to create tickets with appropriate Tasks and AC
- [ ] Determine rough LOE

## Acceptance Criteria
- [ ] Tickets are created in support of this work
- [ ] Work is ready to be scheduled into a sprint

## Associated Tickets
- #48952

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by andaleliz** [comment]
Hi - want to call out that I updated the mocks today to reflect the hiding of the profile menu on this page, to help users stay focused on their task. This should apply for mobile and desktop versions.

**Comment by Samara-Strauss** [comment]
This likely needs to be an epic with smaller tickets.

- Feature toggle
- Build a new page in the profile that can host an editing experience of any field
- Build the new page for the mobile # 
- Potential for additional tickets to follow (testing?)

**Comment by andaleliz** [comment]
> Potential for additional tickets to follow (testing?)

This flow incorporated into this most recent round of usability testing since people had to do that as part of the tasks - I'll be sure to pay attention to findings around that as I go through the videos! Not to say we don't ever need to test it again but it's nice to have a captured data around it now. I can't recall off the top of my head what data we have so far.

**Comment by Samara-Strauss** [comment]
Thanks, Liz! Sorry, my original comment wasn't clear -- I was referring to potential for a ticket around code testing specifically. I'm glad this was thoroughly covered in usability testing so we can feel confident implementing it as-is (unless you recommend changes).

**Comment by andaleliz** [comment]
Ah, that makes more sense!  

No changes recommended at this point :)
