### ISSUE TITLE
Field Mapping of All Remove Dependent Workflows

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#4925]
## Goal
Ensure that each field required in the 21-686c paper form is cross-checked for accuracy and properly represented in the VA.gov form with either 1:1 coverage or material field coverage.  

## Workflows
- Report a divorce
- Report a stepchild is no longer part of household
- Report death of a dependent
- Report the marriage of a child under 18
- Report a child over 18 has stopped attending school

## Considerations
Some fields will simply transfer exactly, where others will collect information differently (e.g. addresses using individual fields vs. single field entry). The paper form has a potentially non-linear flow; whereas the VA.gov form system requires linear, or looped data entry.

## Tasks
- [x] Break-out fields in paper form to visualize relationships of required information  
- [x] Confirm all required data is collected within digital workflow
- [x] Identify paper form fields by number in the mapped workflow

## Acceptance Criteria
- [x] Fields for this section are confirmed and accounted for; fields are mapped to digital workflow by number

**Comment by sporeboy** [comment]
Fields mapped to 21-686c 'Remove Dependents' workflows. List/Loop button added to Stepchild screens.
