### ISSUE TITLE
Remove White House VA hotline from helpful VA phone numbers R&S article

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#49268]
## Issue Description

The White House VA hotline is being renamed to the "VA hotline" but is now going through MyVA 411. We need to remove this entry from the [Helpful VA phone numbers](https://www.va.gov/resources/helpful-va-phone-numbers/) page. 

We also need to ask PW to do an audit for references on any other VA.gov pages. If they find other mentions, we can open a new ticket to address those.

## Tasks
- [x] Remove content from page 
- [x] Create audit ticket for PW
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Live page no longer has White House hotline number

**Comment by RLHecht** [comment]
@megzehn I removed this from the page. Since we are publishing the NCA phone number hours change on this page on Monday morning, we can publish this at the same time.

**Comment by RLHecht** [comment]
I published this with the NCA scheduling office changes.

**Comment by RLHecht** [comment]
This is now live. Closing ticket.
