### ISSUE TITLE
[Monitoring] Create documentation that summarizes graphs and monitors 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#49260]
## Description

As a platform operator, I want to understand the meaning and purpose of platform metrics and monitors. 

When looking at graphs or monitors for the first time, it can be hard to know what metrics are being tracked and why they are important. There should be documentation that helps operators get acquainted with platform monitors to use the information effectively. 

## Background/context 
- [Platform Monitors and Alerts dashboard](https://vagov.ddog-gov.com/dashboard/9dk-y7n-6vf/platform-monitors--alerts?from_ts=1667493106553&to_ts=1667496706553&live=true) in Datadog 
- [Platform Alerting: Tools and Workflow documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1833500703/Alerting+tools+and+workflow) in Confluence

## Technical notes
- The notes and links widget (discussion [here](https://adhoc.slack.com/archives/C044WM9PBMY/p1667510436013339) might be a good way to implement this) 

---
## Tasks
- [ ] _What things need to happen?_

## Acceptance Criteria 
- [ ] Information exists to explain: 
  - [ ] a brief description of each graph
  - [ ] the metric(s) being displayed
  - [ ] and how to interpret the graph

**Comment by jhouse-solvd** [comment]
Suggest that we add this to a broader epic that includes reviewing existing documentation _and_ investigating the best approach to documentation: 

Investigate monitoring and alerting documentation - We want to review existing documentation and explore Datadog features that provide contextual information about metrics and graphs. The goal is to ensure that operators have the information they need to understand and interpret the information being presented.

**Comment by jhouse-solvd** [comment]
- which component(s) is being monitored / displayed
- which service(s) is being monitored / displayed
- what metric(s) is being monitored / displayed
- why is this metric important
- what are the thresholds / formulas being used
- where can I find out more about this component / service
- what specific actions to take when this monitor warns/alerts

**Comment by jhouse-solvd** [comment]
In a conversation w/ the team, this likely needs to be broken down further, though it seems valuable for the MVP.

**Comment by jhouse-solvd** [comment]
This has been satisfied by #51766 and notes that live with each monitor, explaining what metrics are being displayed and why. 

Additional follow-up issues may be created as we received feedback from Platform Operators after the upcoming release.
