### ISSUE TITLE
Add Optimal Workshop to Platform Tools page

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#49302]
## User Story
As a VFS team member, I want to be made aware of all of the Design/research tools available to me, including Optimal Workshop, so that I may use the tool if/when needed.

Assignee: @CherylEvans 
Peer Reviewer: @sterkenburgsara 

## Description
The [Design and Research tools](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-tools#Platformtools-Designandresearchtools) section of the Platform Tools page on Platform Website doesn't include any reference to Optimal Workshop, a user research tool. The purpose of this ticket is to add a new row for Optimal Workshop to the table with information VFS teams need to know about the tool.

## Impacted Artifacts
[Design and Research tools](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-tools#Platformtools-Designandresearchtools) section of the Platform Tools page on Platform Website 

## Tasks
- [x] Before editing the page, identify what content/links will be included in the following:
   - Tool
   - Description
   - Links 
      - [OptimalWorkshop.com](https://www.optimalworkshop.com)
      - anything else? Do we have any guidance on how to get access to this tool?
- [ ] Confirm content with @naomimarcussen. Make any changes she requests.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS teams are made aware of Optimal Workshop as a Platform tool

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by naomimarcussen** [comment]
@CherylEvans I left comments on the [Confluence draft page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2456682508/49302+-+Cheryl+Copy+of+Platform+tools).

**Comment by sterkenburgsara** [comment]
@CherylEvans I see this in the QA column. Based on Naomi's comments, is plan to publish this new row for Optimal Workshop under tools on the research & design section as-is? (I do see the comment about another ticket for adding the it to the "Request Access to Tools" page). If so, it looks good to me and I have no suggested changes.

**Comment by CherylEvans** [comment]
@sterkenburgsara Hi Sara.  This was for Naomi to review, and I am so sorry I didn't tag you earlier and let you know. :-(
I also should have moved it back over to In Process. lol.  Oops!  I know it's all sorted out now, so all is good.  I will tag you when I finish with the other ticket and tune this one up a bit.  :-)

**Comment by CherylEvans** [comment]
@sterkenburgsara I finished the dependency ticket [50685](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/gh/department-of-veterans-affairs/va.gov-team/50685), so this ticket should be good to go.  I am going to publish and close if you are good with it. :-)

**Comment by sterkenburgsara** [comment]
@CherylEvans yes, looks great!
