### ISSUE TITLE
526ez | Remove PTSD stressor statement from BDD

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#49301]
## Value Statement
**_As a_** Veteran
**_I want to_** skip the PTSD stressor statement screens if my claim is received 180 to 90 days before discharge
**_So that_** I can submit my claim with less effort. 

---
## Background Context
Per email from Barrett Cooper and Matt Self:

- The BDD program (claims received 180 to 90 days before discharge) no longer requires a stressor statement to submit a BDD claim.  Therefore, we need the below PTSD stressor statement screens (starting with the below and attached screenshot) removed from VA.gov, EVSS (eBenefits, SEP, etc.) and D2D.  
- **This only applies to BDD claims received 180 to 90 days before discharge.**  BDD-excluded (BDDE), claims received 1 to 89 days before discharge, will still be required to submit a stressor.

<details open>
<summary>Screen shot of page(s) to remove:</summary>
<br>
<img width="709" alt="Screen Shot 2022-11-03 at 2 50 15 PM" src="https://user-images.githubusercontent.com/90406121/199820241-93dfc239-bd84-4b7e-8551-e9edfcda6e43.png">
<img width="864" alt="Screen Shot 2022-11-15 at 10 30 02 AM" src="https://user-images.githubusercontent.com/111457818/201977634-6095905c-e754-4406-be52-b679e1502623.png">
<img width="812" alt="Screen Shot 2022-11-15 at 10 36 02 AM" src="https://user-images.githubusercontent.com/111457818/201977730-d71d4c77-ebbf-4e68-a623-f1c32043c9b2.png">
<img width="803" alt="Screen Shot 2022-11-15 at 10 36 12 AM" src="https://user-images.githubusercontent.com/111457818/201977786-ca0f6b9d-93f5-4f9d-a6ab-042e1477da6b.png">
<img width="786" alt="Screen Shot 2022-11-15 at 10 36 28 AM" src="https://user-images.githubusercontent.com/111457818/201977800-ab8bc584-096d-419d-bc7f-5b73289ddf23.png">
</details>

## Acceptance Criteria
- [ ] Claims received 180 to 90 days before discharge no longer requires a stressor statement to submit a BDD claim, so the screens are not shown to users. 
- [ ] Claims received 1 to 89 days before discharge, will still be required to submit a stressor, so the screens are shown to users. 

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by saderagsdale** [comment]
@eileen-coforma Hey Eileen - we got this request from Matt and another VA stakeholder. Can you review and post any questions here so we can cover them in refinement?

**Comment by eileen-coforma** [comment]
@saderagsdale 
- Is this the correct staging link? https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction
- Is there more context on why stressor statements are removed for veterans applying 180-90 days before discharge?
- Is the stressor statement the same thing as Claim for Service Connection for Post-Traumatic Stress Disorder (VA Form 21-0781) or the subsequent screens that ask for details of the event?
- Page currently only triggers when someone selects PTSD as a condition. Are we removing the entire PTSD details flow, or only the stressor statement?

**Comment by saderagsdale** [comment]
@eileen-coforma @saderagsdale Get snapshots of screens being removed, and confirm with Barrett and Matt.

**Comment by saderagsdale** [comment]
@eileen-coforma Any luck getting a look at the screens we'd need to remove?

**Comment by eileen-coforma** [comment]
@saderagsdale I met with @Mottie, and confirmed that PTSD flow still exists in BDD. 

He was able to access it through staging, and took 4 screenshots to show the main pages that would need to be removed. 

There are about 10+ pages for the flow (asking for details for each type of PTSD), but they won't be triggered as long as the pages in the screenshots are removed. This should be good enough for confirmation.

**Comment by saderagsdale** [comment]
@Mottie Hey there - we just got a request for a level of effort to remove these from the BDD flow. Can you let me know your thoughts?

**Comment by Mottie** [comment]
This work _should_ be relatively easy to implement. I'd say it's worth about 2 story points of work.

**Comment by Mottie** [comment]
This fix is ready to be tested in staging. It will be automatically deployed into production at 3pm ET today.

**Comment by eileen-coforma** [comment]
@Mottie Is this blocked using service history by the account, or the service history that the veteran enters in the 526ez?
I just tested this in staging with user-236, and it's still showing me the PTSD screener. Is there a specific user I should be testing with?
https://www.loom.com/share/3dd3ab815a924cc9ab90bd6069bac8d3

**Comment by Mottie** [comment]
Sorry, I should have mentioned how to test this...

- Log into any user (I prefer 228)
- From the intro page, use the "start
- From the wizard, choose active duty and enter a date 90-180 days in the future (like June 1 2023)
- Start the form. Make sure the title of the for is BDD and remains BDD throughout
- When you get to the military history page, make sure that the same future end date is included/used
- Add a separation location
- In new disabilities, add "PTSD"
- Proceed through form making sure we skip all form 781/781a questions

**Comment by eileen-coforma** [comment]
I don't think it's in scope to question why there are 4 different options for PTSD, but I tested it with user 236 with the instructions Robin gave, and I don't see the PTSD screeners anymore.

This is good to go.

**Comment by saderagsdale** [comment]
@eileen-coforma yeah the business did not ask to remove the number of PTSD options, just the follow-up screens.

**Comment by saderagsdale** [comment]
Also went through the flow and did not see the additional screens. I updated Matt on the status @Mottie.
