### ISSUE TITLE
EPIC | Profile | Editing as a Sub-Task

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#49319]
## Background
During the recent research sessions we observed that users were disrupted by having to leave the notifications preference page to add their mobile number. We re-visited the existing design for this flow and considered a few alternatives. 

After discussions with the team, I/A and others, we have decided to move forward w/ a single URL: ` /profile/edit/`

#### Outline of user experience:

<details><summary>Details</summary>
<p>

<img width="817" alt="image" src="https://user-images.githubusercontent.com/55992116/197594531-98a5be89-f5ac-4a3c-8fb2-f95973734f11.png">

</p>
</details> 

#### The mock-ups are below:

- [Mobile form](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/v8ej4q3)
- [Desktop form](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/wLGk4J9)
- [Mobile page w/ confirmation message](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/4al7YGJ)
- [Desktop page w/ confirmation message](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/WKLzddk)

## Important Documents 

- [Feature Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/editing-as-a-subtask) 
- [Initiative Brief ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/editing-as-a-subtask/mobile-phone-edit-flow/README.md)
- [Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/default-send/releasePlan/defaultSendReleasePlan.md)
- [QA ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/notification-preferences/default-send/QA)
- [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/Research/2023-09-UAT-edit-as-subtask-default-send-checkbox-ui)

## Tasks

<details><summary>Completed Phases</summary>

```[tasklist]
### Design Intent through Midpoint Review
- [x] Review mocks and identify the work required for FE
- [ ] #57820
- [x] #53547
- [ ] #59158
- [x] schedule midpoint review
- [ ] #57408
- [ ] #59728
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/61088
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/61212
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/61214
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/59987
```

```[tasklist]
### Staging Review Prep
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62091
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/61112
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/63550
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/63278
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/63198
```

</details> 

```[tasklist]
### QA
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62606
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/63333
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62629
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/63770
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65407
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65410
- [x] schedule staging review
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/58231
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65645
```

```[tasklist]
### UAT
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62610
- [ ] #62915
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/64343
- [ ] #63880 
- [ ] #63881
```

```[tasklist]
### Staging Review Feedback
- [ ] #67069
- [ ] #67071
- [ ] #67070
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/67384
``` 

```[tasklist]
### Launch
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62928
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62921
```

```[tasklist]
### Post Launch
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/68878
- [ ] #48952
- [ ] #53549
```

```[tasklist]
### [Future Opportunities](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/editing-as-a-subtask#future-places-to-use-this-feature)
- [ ] Update Bad address Indicator workflow to use Editing as a Subtask (https://github.com/department-of-veterans-affairs/va.gov-team/issues/64818#issuecomment-1714753774)
- [ ] Direct deposit CTA #76326
```

## Acceptance Criteria
- [ ] the work has been deployed to production 
- [ ] we've removed toggles and cleaned up the code 
- [ ] documentation has been updated
