### ISSUE TITLE
Update how to check in for appointments R&S page with new check-in window time-HOLD TO PUBLISH UNTIL 11/29

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#49315]
## Issue Description

The check-in window for appointments is changing from 30 minutes to 45 minutes. We need to update this on the [How to check in with your smartphone for some VA appointments](https://www.va.gov/resources/how-to-check-in-with-your-smartphone-for-some-va-appointments/) R&S page. 

This is showing in step 2 of the subway map in both the bold text and in the note. 

This change takes effect in December 2022, so we should hold to publish until we know the exact date.

**Update:** Product team said to publish on 11/29.

Original intake request: #49262

## Tasks
- [x] Update content (Katherine)
- [x] Copyedit (Megan)
- [x] Publish (Megan)
- [ ] Post in original intake ticket that changes are live (Randi)

## Acceptance Criteria
- [ ] Updated R&S article is live on the site

**Comment by katherine-fung** [comment]
Hi @megzehn! 

This page is ready for copyedit. We'll need to hold to publish until we can confirm the date the change goes into effect:

HOLD TO PUBLISH - http://preview-prod.vfs.va.gov/preview?nodeId=44490

I updated check-in window for appointments 30 minutes to 45 minutes;
added a hard return to the link in the note in the very last section

**Comment by megzehn** [comment]
Thanks, @katherine-fung! This has been reviewed and published.

**Comment by megzehn** [comment]
@RLHecht this is ready for you to validate. Thanks!

**Comment by RLHecht** [comment]
This is live. Closing ticket!
