### ISSUE TITLE
Medallia Product Mapping in DOMO

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/va.gov-team#49311]
## Issue Description
Utilize the [VFS Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory) to map the root URLs to products to use as filters within DOMO

---
## Tasks
- [x] Map root URLs to live products within [the mapping document](https://docs.google.com/spreadsheets/d/15j1WKu2bl134FD81sVifp1_CMCAaKr-5JN4C5IhfgyI/edit#gid=0)
- [x] Add the new mappings to the existing Medallia Product Mapping ETL

## Acceptance Criteria
- [x] Has the product mapping document been updated?
- [x] Has the ETL been updated?
- [x] Has the new filters been tested?
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
Medallia VFS product mapping has been completed and tested. URLs were added based on the VFS product directory.
