### ISSUE TITLE
Search.gov Access for Kelson Adams and Kara Kemahli

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#4932]
### **Access Request**
As a member of the VA.gov Public Website Product Team I need access to search.gov so that I can explore the system's functionality and metrics to improve the ability for Va.gov to work with this technology.

### Tasks
- [x] Check to see if non va.gov email addresses can be used
- [ ] --If non-va emails are able to be used, invite kadams@governmentcio.com and kara@adhocteam.us--
- [ ] if va emails only, obtain va.gov emails for team members who need them (separate issue?)
- [ ] using Search.gov, issue invitations to users to search.gov
- [ ] Validate invited users are able to log in

- [ ] Change nick.sullivan@adhocteam.us to VA.gov email address

**Acceptance Criteria:**
- [ ] Kelson Adams can access VA.gov search.gov dashboard
- [ ] Kara Kemahli can access VA.gov search.gov dashboard
- [ ] Nick Sullivan has new account using VA.gov email address

**Comment by davidconlon** [comment]
@Karak888 do we have a task tracking yours and @kelsonic getting va.gov accounts?
I checked and we prefer to use va.gov emails/accounts for search.gov.

**Comment by Karak888** [comment]
Yes we have been waiting forever for GCIO to help facilitate.  Earlier this week I inquired about it again, but I have submitted paperwork 4 separate times now and gone to get fingerprinted 2 times.  The person who was doing it on their end is no longer on the program and they just hired someone new. it is for both myself, Kelson and 3 content team members.  @ncksllvn does have a va.gov account.

**Comment by Karak888** [comment]
@davidconlon just requested status again, but they always handled that on the side but I will move to task tracking as it is very ridiculous.

**Comment by Karak888** [comment]
I am sure we can bring in backup help if you feel it is needed. I assume you have heard that I am going through some difficult times with  family issues, so I will work that out this week so you have the best resources to work with in this.

Thanks,

Kara

**Comment by Karak888** [comment]
@YanaRoy I am assigning this request to you just to keep things moving, as it doesn't appear that @julieRamirez is in GH yet, and we have an urgent need to get VA.gov email access for those listed above to be able to access Search.gov. I can email her with a link but if she can't access I guess that won't work and I know she is new to the program.  Please contact @davidconlon or myself in the event that I am out for any reason. Thanks!
