### ISSUE TITLE
Create new VALife benefit detail page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#49320]
## Issue Description

The VALife life insurance program is launching on January 1, 2023. We need to create a new benefit detail page similar in structure to our other life insurance program pages. 

There's currently a [VALife benefits.va.gov page](https://www.benefits.va.gov/insurance/valife.asp) we can use to pull the information from but we should model our page off of our other modernized pages in the life insurance hub. We can also reach out to the stakeholder Steve Fital if we need more information.

The S-DVI insurance program will stop enrolling new members on December 31, 2022. We need to figure out if it's best to add this information to the new VALife page or rework the [current S-DVI page](https://www.va.gov/life-insurance/options-eligibility/s-dvi/).

Because this page needs to launch at the beginning of the year, it's a tight turn-around to get it written, approved, and published. We've let Steve know that we need approval fairly quickly when we send it to them. 

Since this is a brand-new page, we'll set up a separate ticket for copyediting and publishing.

## Tasks
- [x] Write new VALife benefit detail page (Aliyah)
- [x] Edit (Laura)
- [x] OCTO-DE review (Beth)
- [x] Send to stakeholder for feedback (Aliyah/Laura)

## Acceptance Criteria
- [x] VALife page is approved by stakeholder

**Comment by aliyahblackmore** [comment]
Hi Laura! As we chatted, here is a draft of the VALife page for your review. 

[VALife_AB_11.7.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9976172/VALife_AB_11.7.docx)

As mentioned in the ticket, the page was roughly built using the current life insurance page structures (i.e. the[ S-DVI page](https://www.va.gov/life-insurance/options-eligibility/s-dvi/)) with updates based on more current VA patterns and standards.

I left in some of my additional questions and notes for you/the stakeholder in comments (i.e. whether we should include cash value details, etc.) and made note of sections that we still need information for or whether certain headers should be included.  

**One question that came up as I was writing this ticket reply**: we don't currently have a section on life insurance pages specific to beneficiaries - would it be worth including that on this page as an H2 (and potentially using H3s for the questions after)?

Additionally, as you mentioned, the premium rates were not included in this document but added some notes on how we may structure this (based on our 11/9 sync). We'll add the table(s) once we are in Drupal.

Also, for awareness and something that I noticed:
Across legacy pages that there are references to _**VA Life Insurance**_ (this seems to be different than the new program) that is an umbrella term for different life insurance programs through VA. I know that the goal is to migrate a bulk of pages to the current VA site, but just flagging in case we need to  confirm with the stakeholder how this may be differentiated when the program launches? 

For example from the main Life Insurance home page, on the left nav menu there is “Other VA Life Insurance” and if you select “[Other VA Life Insurance page](https://www.benefits.va.gov/insurance/select.asp)” you’ll get some information regarding other types of life insurance like United Stated Government life insurance, etc.

From the home page there is also a right nav menu for Resources that lists a link “[Celebrating 100 years of VA Life Insurance](https://www.benefits.va.gov/insurance/insurance100.asp)” which brings you to a page with “Insurance Infographics.”

**Comment by aliyahblackmore** [comment]
Hey @laurwill ! 

Passing back the word doc with some updates following standup - including the H2 re: what should Veterans do if they have S-DVI and the note re: the premiums waiver. 

The last H2 is still blank as we'll need the contact information from the stakeholder.

Thank you!!

[VALife_AB_11.10.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/9983954/VALife_AB_11.10.docx)

**Comment by laurwill** [comment]
Thanks so much @aliyahblackmore ! I started getting this into Drupal on Friday — could you finish up by adding the rates tables and the info alert? Let me know if you have questions about the tables. I set up the first one but we may be able to shorten the headers even more. 

http://preview-prod.vfs.va.gov/preview?nodeId=51018

**Comment by aliyahblackmore** [comment]
Thanks so much, Laura! 

The rates tables and info alert are on the page!
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=51018

As discusses, I also did a quick review of the page and the changes you made look great. One flag: I noticed that the beneficiaries text is still in parenthesis. I noted in a comment in the word doc that’d we need to incorporate this someplace and suggested adding it to the sentence like this:

_If you die before the 2-year waiting period is over, we’ll pay the people you picked to get the money from your life insurance policy (called beneficiaries) the amount you paid in monthly premiums, plus interest._

I also added in the aria label for the contact number and TTY: 711 (in the last accordion)

To confirm/answer your questions re: the tables: 
1. We likely wouldn’t bold the text down the column for age and the gray is only used on in the table headers! 
I went ahead and added in “(in U.S. dollars)” to the page. Randi confirmed that the decision was made a while back to put this at the top of the table so that "$" isn’t used throughout the table. This is another life insurance page with the "in U.S. $" included -  https://www.va.gov/life-insurance/options-eligibility/vgli/

While chatting with Katherine I played around with the placement and using it in the table column header felt too crowded (given the coverage amount text). For the time being I landed on placing it in the sentence above the table amount. Wondering if it's a hard rule to have this is the column headers or if it can be in the sentence that comes before the accordions?

**Comment by laurwill** [comment]
Thanks so much @aliyahblackmore ! 
- For "beneficiaries," I just took the sentence out of the parentheses. I think it's okay to have it in a separate sentence, rather than making that first sentence longer.
- I'm torn about putting "U.S. $" in the column headers vs somewhere else — I tried it out in the first table and it's long, but it doesn't look too too crazy to me. And I think it would be better to keep that closer to the actual rate amounts. @megzehn , want to see what you think when you get in there?
- Thanks for calling out the "rates" question — I think we do want "rates" in that sentence and in the table headers. 

@megzehn , this is ready for your copyedit! Couple notes:
- We're trying out more statement headers here, as opposed to using question headers throughout
- For consistency with other life insurance content, I used "apply" rather than "enroll" (which is what the VALife source page says). We'll ask the SMEs to confirm this word choice.

I'll also be posting related changes to the S-DVI page and a couple other pages [in this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49327#event-7742458354). If you're able to look at those next, it might be easier for SMEs to review as a single batch. 

Let me know if you have questions when you get in there!

**Comment by laurwill** [comment]
Thanks so much Megan! Noting that Aliyah sent the draft page for SME review.

**Comment by aliyahblackmore** [comment]
Noting that Laura and I will be meeting tomorrow to review the feedback from SME!

**Comment by aliyahblackmore** [comment]
Noting that Laura and I reviewed SME feedback this morning and I passed her a doc with edits this afternoon.

**Comment by laurwill** [comment]
Thanks so much Aliyah! I made a few more adjustments to the alert and the sections about S-DVI conversion and filing a claim. Let me know if you have any questions about my changes!
[VALife_Updates after SME feedback_12.2.22.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10143484/VALife_Updates.after.SME.feedback_12.2.22.docx)

@bethpotts this is ready for you to take a look — here's a couple specific questions:
- SME linked to a DocuSign version of the claim form — we haven't previously linked to DocuSign, so wanted to see if you have concerns or if we need additional approvals before we do this
- SME added the "Can I change from S-DVI to VALife?" section to the S-DVI page draft — I think it makes sense to include this in both places, but wanted to confirm it's okay to treat this as pseudo-COPE content even though it won't technically be reusable.
- I tracked a couple of style points on slack — "service-connected" before disability rating and "premium" vs "premium rate"

Let me know if you want to chat about anything! And very open to any feedback you have beyond the SME edits.

**Comment by aliyahblackmore** [comment]
Hi Laura - the Drupal preview is ready for you! 
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=51018

**As we chatted, I did these things on the page:**

1. Added the edits from [your word document] (https://github.com/department-of-veterans-affairs/va.gov-team/issues/49320#issuecomment-1335663097).

2. I changed the age ranges in the tables (SME request) 

3. I adjusted the monthly header and content before the tables, and added the annual header and accordions for the age groups. I reworked my initial suggestion re: the insurance age and placed it in the text before the tables. I landed on this rework of the text - please feel free to re-arrange! 

4. For the annual rates, I only added 1 row (as discussed) for the 18 to 30 age group - just so the SME have a sample of what this table configuration would look like.

**Comment by aliyahblackmore** [comment]
**Update 12/9:** Added the yearly rates, adjusted the insurance age language, and the beneficiaries secure online upload link language.

**Comment by laurwill** [comment]
Thanks so much @aliyahblackmore ! I made some more adjustments in Drupal and also updated the Word doc to send back to SMEs. We can prep the email together in our noon call and get this out the door.

**Comment by aliyahblackmore** [comment]
**Updates:** 

- Sent an email to SMEs with preview links and word docs for VALife and S-DVI 

- Completed the accessibility test (ticket 50636) and added it to the collab ticket (ticket 50211)

**Comment by laurwill** [comment]
Update: We have final approved content for this page and we're now tracking final copyedit and prepub steps in this [consolidated ticket for all the January 3rd changes for VALife](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49327). 

@RLHecht should we close this one out?
