### ISSUE TITLE
Updates to current pages in connection with VALife launch

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#49327]
## Issue Description

Stakeholder Steve Fital drafted changes to several different VA.gov pages we need to make when VALife starts opening enrollment on January 1, 2023. We'll need to review his changes and make edits for plain language and to match VA.gov style. 

We'll need to hold on publishing these changes until January, but we should start making the updates to get approval beforehand. 

Word doc with changes to be made: [https://app.zenhub.com/files/133843125/bc1cffe0-1ea6-429f-a43b-0bd5c6721544/download](https://app.zenhub.com/files/133843125/bc1cffe0-1ea6-429f-a43b-0bd5c6721544/download)

Pages to update:

- [Change your address on file with VA](https://www.va.gov/resources/change-your-address-on-file-with-va/#change-your-address-by-contact)
- [About VA insurance options and eligibility](https://www.va.gov/life-insurance/options-eligibility/)
- [Access your VA life insurance policy online](https://www.va.gov/life-insurance/manage-your-policy/)
- [S-DVI](https://www.va.gov/life-insurance/options-eligibility/s-dvi/)
- [Non-compensable disabilities](https://www.va.gov/resources/non-compensable-disability/)
- [After you get a disability rating](https://www.va.gov/disability/about-disability-ratings/after-you-get-a-rating/)
- Promo on life insurance hub landing page: Change link to go to our page and remove "that takes effect January 1, 2023" from promo sentence.

We will set up a separate ticket for publishing these pages among others on January 3.

## Tasks
- [x] Update static pages (Aliyah)
- [x] Review (Laura)
- [x] Send to stakeholder (Aliyah/Laura)
- [x] Copyedit and prepub (Megan)
- [x] Publish pages on Jan 3 
- [x] Update promo on insurance hub page

## Acceptance Criteria
- [x] All pages are live with updates
- [x] Promo on life insurance hub is updated
- [ ] Redirects from legacy VALife pages are live

**Comment by laurwill** [comment]
Hi @megzehn ,
Here's the Word doc with tracked changes for you to copyedit — I think it might be easier to send these back to Steve all in the same doc. 
[VALife edits.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10015992/VALife.edits.docx)

But I updated the Drupal node for the S-DVI page, since that had more substantial changes. If you'd rather copyedit that page in Drupal, I can transfer any edits into the Word doc: http://preview-prod.vfs.va.gov/preview?nodeId=766

**Comment by megzehn** [comment]
Thank you, @laurwill and @aliyahblackmore! 

I've attached a version with a few copy edits. 

[VALife.edits_MZ.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10032570/VALife.edits_MZ.docx)

**Comment by laurwill** [comment]
Thanks Megan! Noting that we ended up drupaling these after all, so the nodes are all ready for final copyedit and publishing on 1/3, once we get SME approvals. Aliyah sent our suggested edits to SMEs today, along with the new VALife page.

**Comment by laurwill** [comment]
Updates here: I found 2 more pages that mention S-DVI and realized we'll have to update the VALife link in the feature box on the life insurance hub landing page as well. Added these to the top of this ticket. 

Here's the full list of preview nodes for final copyedit. @megzehn I'll reassign this to you once we have final SME approval on the S-DVI page. Can you plan to do final edit and prepub steps on all of these next week before our holiday break? Then we'll need to publish all of these along with the VALife page on the morning of Jan 3.

Nodes for copyedit/prepub:
- [ ] S-DVI page: http://preview-prod.vfs.va.gov/preview?nodeId=766
- [ ] About VA insurance options: http://preview-prod.vfs.va.gov/preview?nodeId=764
- [ ] Access your life insurance policy: http://preview-prod.vfs.va.gov/preview?nodeId=763
- [ ] Change your address: http://preview-prod.vfs.va.gov/preview?nodeId=8473 
- [ ] Non-compensable disabilities: http://preview-prod.vfs.va.gov/preview?nodeId=26912 & http://preview-prod.vfs.va.gov/preview?nodeId=26918 (this is a single Q&A on an FAQ page]
- [ ] After you get a disability rating: http://preview-prod.vfs.va.gov/preview?nodeId=867

**Comment by laurwill** [comment]
Hi @megzehn ! At long last, we have final content for **all VALife-related updates**. I'm listing everything here and closing the separate VALife ticket, so that it's all in one place. 

All of these nodes are now ready for final copyedit and prepub steps. We'll publish them all first thing on January 3.

**New pages/major changes:**
- [ ] VALife page: http://preview-prod.vfs.va.gov/preview?nodeId=51018
- [ ] S-DVI page: http://preview-prod.vfs.va.gov/preview?nodeId=766 **(we'll revert to the version you already copyedited for this one)**
- [ ] Access your life insurance policy: http://preview-prod.vfs.va.gov/preview?nodeId=763 

**Smaller changes to mention VALife instead of S-DVI:**
- [ ] About VA insurance options: http://preview-prod.vfs.va.gov/preview?nodeId=764
- [ ] Change your address: http://preview-prod.vfs.va.gov/preview?nodeId=8473 
- [ ] Non-compensable disabilities: http://preview-prod.vfs.va.gov/preview?nodeId=26912 & http://preview-prod.vfs.va.gov/preview?nodeId=26918 (this is a single Q&A on an FAQ page]
- [ ] After you get a disability rating: http://preview-prod.vfs.va.gov/preview?nodeId=867
- [ ] VR&E through IDES: http://preview-prod.vfs.va.gov/preview?nodeId=728 (more info box at bottom)

**Comment by megzehn** [comment]
Hi @laurwill! Confirming that these all have been copy edited. 

Thank you for all this work!!

**Comment by megzehn** [comment]
All of these have been published! 

- [ ]  VALife page: http://preview-prod.vfs.va.gov/preview?nodeId=51018
- [ ]  S-DVI page: http://preview-prod.vfs.va.gov/preview?nodeId=766 (we'll revert to the version you already copyedited for this one)
- [ ]  Access your life insurance policy: http://preview-prod.vfs.va.gov/preview?nodeId=763

- [ ]  About VA insurance options: http://preview-prod.vfs.va.gov/preview?nodeId=764
- [ ]  Change your address: http://preview-prod.vfs.va.gov/preview?nodeId=8473
- [ ]  Non-compensable disabilities: http://preview-prod.vfs.va.gov/preview?nodeId=26912 & http://preview-prod.vfs.va.gov/preview?nodeId=26918 (this is a single Q&A on an FAQ page]
- [ ]  After you get a disability rating: http://preview-prod.vfs.va.gov/preview?nodeId=867
- [ ]  VR&E through IDES: http://preview-prod.vfs.va.gov/preview?nodeId=728 (more info box at bottom)

**Comment by RLHecht** [comment]
These changes are live. Redirects will happen tomorrow. Closing ticket!
