### ISSUE TITLE
FE | Auth Profile | Analytics Dashboard | Events for Contact info (Discovery)

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#49344]
## Background

The Analytics team is building a dashboard for Profile which includes all sections.
To do so, they need to know the "event actions" we use for Contact information (see sections with "?" marks in table below).

Initially we thought that `API Request - GET /v0/user - successful` was the missing the event action.

However, Analytics advised:

> I'm a little suspicious whether `API Request - GET /v0/user - successful` is actually the event action we need here. There don't seem to be any `started|failed` variations in GA, so we couldn't actually use this to track failures or failure rates for this group of retrievals. In addition, this event seems to exist on many of the other VA Profile pages where retrievals do have information-specific API call events configured that we're using instead.

---

Profile information | Page | "Retrieve" events | "Save" events| 
-------|------|-------------------|--------------
Preferred name | /profile/personal-information/ | `API Request - GET /profile/personal_information - (started/successful/failed)`| 'API Request - PUT /profile/preferred_names- (started&#124;successful&#124;failed)' |
Gender identity | /profile/personal-information/ | `API Request - GET /profile/personal_information - (started/successful/failed)` | 'API Request - PUT /profile/gender_identities - (started&#124;successful&#124;failed)'
Military information | /profile/military-information/ | 'API Request - GET /profile/service_history - (started&#124;failed)', 'API Request - GET /profile/service_history Source: api.va_profile - successful' | _(not requested)_
Mailing address | /profile/contact-information/ | ❓ | 'Profile - Form Submit - Mailing Address', 'Profile Save Failure - Mailing Address'
Home address | /profile/contact-information/ | ❓ | 'Profile - Form Submit - Home Address', 'Profile Save Failure - Home Address'
Home phone | /profile/contact-information/ | ❓ | 'Profile - Form Submit - Home Telephone Number', 'Profile Save Failure - Home Telephone Number'
Mobile phone | /profile/contact-information/ | ❓ | 'Profile - Form Submit - Mobile Phone Number', 'Profile Save Failure - Mobile Phone Number'
Work phone | /profile/contact-information/ | ❓ | 'Profile - Form Submit - Work Telephone Number', 'Profile Save Failure - Work Telephone Number'
Contact email | /profile/contact-information/ | ❓ | 'Profile - Form Submit - Email Address', 'Profile Save Failure - Email Address'
Direct deposit (disability comp & pension) | /profile/direct-deposit/ | 'Profile - Direct Deposit Retrieval Successful', 'Profile - CNP Direct Deposit Retrieval Successful', 'Profile - Direct Deposit Retrieval Failed', 'Profile - CNP Direct Deposit Retrieval Failed' | Successful saves - `Profile - Form Submit - CNP Direct Deposit Information`; Failed saves - `Profile Save Failure - CNP Direct Deposit Information`  ([this report](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/naG_-UneTxy50WvvIH0GGQ/a50123418w177519031p176188361/))|
Direct deposit (education benefits) | /profile/direct-deposit/ | 'Profile - EDU Direct Deposit Retrieval (Started&#124;Successful&#124;Failed)' | Successful saves - `Profile - Form Submit - EDU Direct Deposit Information`; Failed saves -` Profile Save Failure - EDU Direct Deposit Information` ([this report](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/qEpkRFroTOSTpgaBDHXK4A/a50123418w177519031p176188361/))
Notifications | /profile/notifications/ | 'API Request - GET communication_preferences - (started&#124;successful&#124;failed)' | 'API Request - POST communication_preferences - (started&#124;successful&#124;failed)'

## Tasks
- [ ] Review API calls and determine whether we are tracking GETs for contact information (addresses, phone numbers, email address).
- [ ] Provide PM with this information, OR
- [ ] Work with PM to define the tasks needed to remediate
- [ ] Work with PM to create new issues and estimate

## Acceptance Criteria
- [ ] Analytics has info needed to complete dashboard work, OR
- [ ] PM has necessary information to open a ticket to schedule work needed

## Associated Tickets
- #46861

**Comment by SKasimow** [comment]
Closing...opening a new ticket for FE work per discussion Adam and I had with Analytics.
