### ISSUE TITLE
Create POC of Docker Image Build and Deploy w/ EKS

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#49343]
## Issue Description

Given existing review instances use Docker images for `vets-website` and `vets-api`, is it possible to use the same Docker images to deploy using EKS?

Research into how we might use EKS to deploy preview environments has been previously collected [here](https://vfs.atlassian.net/wiki/spaces/TT4/pages/2416935044/Research+Preview+Environments+in+EKS).

## Tasks
- [x] Experiment with storing the Docker images in ECR at the end of the existing workflow
- [x] Is it possible to use a workflow in GitHub Actions to generate the Docker images?
- [x] Create a POC workflow that deploys the Docker images via EKS to the ~`vagov-staging`~ `dsva-vagov-dev` VPC
- [x] Meet with Kyle / devops stakeholders to discuss best practice for EKS deployments and go over our POC

## Acceptance Criteria
- [x] We understand to what extent it will be possible to lift the Docker image building process from Jenkins and EC2 and shift it over to GHA and EKS

**Comment by rmtolmach** [comment]
I (along with Ray and Peter) met with Kyle on Thursday 11/10. The pod with all the right docker containers exists:
![image.png](https://images.zenhubusercontent.com/61dcb2c3a1419ace503f1509/6bcad735-28c0-43f4-b2a2-3a345b8727bf)
BUT, the `vets-website` container is unhappy. It’s trying to spin up on port 80, but that’s where `vets-api` is, because that’s what httpbin uses.  

Link to ArgoCD: https://argocd.vfs.va.gov/applications/preview-environment-dev?view=tree&conditions=false&resource=&operation=false
Our endpoint: http://preview-environment-hello-world-dev.vfs.va.gov/ (not currently working as desired)

**Comment by rmtolmach** [comment]
* The port problem I noted yesterday was fixed by Kyle ✅ 
* Ignore preview-environment endpoint I linked yesterday

Our POC, http://ri-peter-dev-platform-api.vfs.va.gov/, is alive (but returns a `404` for now). The hosted zone is `vfs.va.gov` which is behind the SOCKS proxy. We are specifying `vfs.va.gov`, so next step is changing that to our desired VPC, `dsva-vagov-staging-vpc`.

**Comment by rmtolmach** [comment]
From my previous comment ☝️ 
> next step is changing that to our desired VPC, `dsva-vagov-staging-vpc`.

Not quite. We _do_ want to move away from `vfs.va.gov`, but the public-facing option is `*api.va.gov` (which is not in our control). 

Met with Kyle (and Peter) again and took some notes. https://vfs.atlassian.net/wiki/spaces/TT4/pages/2436628750/Kyle+Conversation+11+17+regarding+EKS+Deployment+Process

We went over the Design section of the RFC with Kyle

> Is it possible to use a workflow in GitHub Actions to generate the Docker images?

Searching "generate docker images in a github action" gives lots of good-looking results, so I'm saying "yes!"

Our POC is in `dsva-vagov-dev-vpc`. EKS + dev is functional, but EKS + staging is not.

**Comment by rmtolmach** [comment]
On pushing images to and pulling images from ECR:
* Seems like a common task
* https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-push-ecr-image.html
* https://aws.plainenglish.io/build-a-docker-image-and-publish-it-to-aws-ecr-using-github-actions-f20accd774c3
* Pulling an image: https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-pull-ecr-image.html

**Comment by pjhill** [comment]
This looks good. I think this sufficiently informs us around the image creation and deployment aspect of our solution. We can close this ticket for now, and refer to the content generated here when we do the MVP implementation.
