### ISSUE TITLE
526 EZ Confirmation Page Error Message Update

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#49357]
# User Story
As a Veteran I want to make sure that if there is some information that I need to get to the VA regarding my disability claim submission that I can get that information to the correct person.

# Background
On the 526 EZ confirmation page an error message appears that states It's taking us longer than expected to submit your claim.. This error is triggered in the code by three conditions, submissionStatuses.retry: , case submissionStatuses.exhausted:, and case submissionStatuses.apiFailure: None of these cases have anything to do with how long it is taking to submit the claim and two of them are actually caused on the EVSS side by either EVSS being down OR data missing in an upstream data service, meaning that no matter how many times the Veteran waits or retries this claim it will not go through. 

The error message indicates that if the Veteran sits there long enough the claim will go through and many of the call center issues surrounding this error message start off something like "I have been sitting here forever waiting for this to go through" or "I have tried several times on several devices and it never goes through". Can we come up with some better error massaging around these, and we most likely want to split these out into different error messages since these three cases can be dramatically different

## Tasks
- [ ] Create different error messages for the three different scenarios that prevent the application from being submitted.
- [ ] Update the error message
- [ ] Submit a PR for review and merge

## Acceptance criteria
- [ ] The error messages reflect the actual problem and the correct solution given the problem

**Comment by aubreyarcangel** [comment]
To be clear, this is the full error message that appears for the three error states:

1.  submissionStatuses.retry 
2.  submissionStatuses.exhausted 
3.  submissionStatuses.apiFailure

```
export const retryableErrorContent = props =>
  template(
    props,
    "It's taking us longer than expected to submit your claim.",
    <div>
      <p className="vads-u-font-size--base">
        This delay should be resolved within a few hours. We’ll keep trying to
        submit your claim. You can check the status of your claim online after
        24 hours.
      </p>
      <p className="vads-u-font-size--base">
        <a href="/track-claims">Check the status of your claim</a>
      </p>
      <p className="vads-u-font-size--base">
        <strong>
          If you don’t see your disability claim online after 24 hours,
        </strong>{' '}
        please call Veterans Benefits Assistance at{' '}
        <va-telephone contact={CONTACTS.VA_BENEFITS} />, Monday through Friday,
        8:00 a.m. to 9:00 p.m. ET and provide this reference number{' '}
        {props.jobId}.
      </p>
    </div>,
    checkLaterMessage(props.jobId),
    'warning',
  );
  ```

**Comment by starlow00** [comment]
@aubreyarcangel, I have a copy draft at https://docs.google.com/document/d/1CwnQb840FD8qfVYDMFswUjiyou7LO9Ylh4Uyj2lyDP0/edit

**Comment by clantosswett** [comment]
@saderagsdale this is an old issue that was created by Jesse Cohn related to update the generic disability claims application submission error message that is being shown to veterans and contains inaccurate information. Based on the write up by Jesse, it looks like the same error message is shown for three different triggers. We need support from the benefits team to determine the exact cause of the different triggers so we can write an error message that provides the right details and next steps the veteran should take.

**Comment by starlow00** [comment]
Access granted, @clantosswett

**Comment by aubreyarcangel** [comment]
definitions of `submissionStatuses`:

-   submissionStatuses.pending:  Submitted to EVSS, waiting response
-   submissionStatuses.retry: ???
-   submissionStatuses.succeeded: Submitted to EVSS, received response
-   submissionStatuses.exhausted: EVSS is down or something; ran out of retries
-   submissionStatuses.failed: EVSS responded with some error
-   submissionStatuses.apiFailure: When the api serves a failure

**Comment by clantosswett** [comment]
@starlow00 can you provide me with editing access to the google doc? I have some questions and suggested edits. Thanks!

**Comment by ATMiddleton** [comment]
Still under review 
Meeting 1/11/23 - Aubrey/Kimberley/Steven 
Blockers
Complete PR Review

**Comment by aubreyarcangel** [comment]
Still not ready for review. Updating format to error messages and writing tests.

[PR for this work can be found here](https://github.com/department-of-veterans-affairs/vets-website/pull/23103/)

**Comment by saderagsdale** [comment]
@clantosswett there will be a new team taking over the 526. They can pick this up after they complete onboarding if the work is still needed.

**Comment by ATMiddleton** [comment]
@aubreyarcangel will complete to be PR review ready awaiting further engagement.

**Comment by ATMiddleton** [comment]
Awaiting the onboarding of the new Benefits team

**Comment by ATMiddleton** [comment]
Moving to Backlog until Benefits team is in place
