### ISSUE TITLE
Create Flipper Index Mute

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#49351]
## Issue Description
When authenticating the `FeatureTogglesController`'s `index` method is called, resulting in an enormous amount of Rails logs generated as each individual flipper feature is looked up and creates 2 Rails log lines. This wall of logs makes finding any other Rails logs that are generated during authentication difficult to find, and should be able to be muted.

## Tasks
- [x] create `flipper.mute_logs` configuration setting with a default `false` value
- [x] enable `FeatureTogglesController.index` muting, controlled by a `vsp_environtment: localhost` & `flipper.mute_logs: true` settings
- [ ] update feature_toggles_controller_spec to cover new mute functionality
