### ISSUE TITLE
Update phone number on 526-EZ alert 

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#49356]
# User Story
As a Veteran I want to make sure that if there is some information that I need to get to the VA regarding my disability claim submission that I can get that information to the correct person.

# Background
On the 526-EZ form we make a check before the Veteran begins the form to make sure we can set up an EDIPI or a BIRLS ID for the Veteran because without one of these they cannot submit a claim. If we are unable to establish one of these we show the Veteran a message that we need more information shown here -

![image (1).png](https://images.zenhubusercontent.com/5d643dbea77bcf04870bc424/878dd8ff-6afc-4a48-b531-7ca93ce2cede)

The phone number shown on this message is incorrect as it routes the Veteran to the general help desk but they are unable to help with an EDIPI or a BIRLS ID.

The correct phone number we need on this error message is 800-698-2411, that is the number for the Tier 1 Contact Center which can route issues like this to the EVSS help desk.  They are available 24 hours a day, 7 days a week.

## Tasks
- [ ] Update the phone number on the alert
- [ ] Notify Tier 1 Group of the change with added training
- [ ] Submit a PR for review and merge

## Acceptance criteria
- [ ] The correct phone number now shows on the alert message referenced above

**Comment by clantosswett** [comment]
Updated language should read... "To update your account, please call 800-698-2411 (TTY: 711). We're here 24/7.

**Comment by ATMiddleton** [comment]
Still in draft PR - need to update description prior to submission for review.

**Comment by ATMiddleton** [comment]
@clantosswett there will be a new team taking over the 526. They can pick this up after they complete onboarding if the work is still needed. aubrey will continue to work until PR review ready.

**Comment by ATMiddleton** [comment]
Awaiting the onboarding of the new Benefits team

**Comment by ATMiddleton** [comment]
Moving to backlog until Benefits team is in place.

**Comment by RakshindaAslam** [comment]
Pulling this work into disability-experience team's backlog.

**Comment by christinec-fftc** [comment]
@RakshindaAslam #57110 is complete. Can we close this out?

**Comment by RakshindaAslam** [comment]
This work is completed through https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/57110. Please review and close this ticket.
