### ISSUE TITLE
FE | Profile | Research Recommendations | Update Button Pairs

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#49374]
## Background

During our recent research sessions we observed that some users were confused by the button options for "saving" and "updating" their information. 

We need to make the following changes:

> 1. Change Update to Save. Save is more conventional, and aligns better to the use case of people adding info for the first time.
> 2. In the modal that appears when someone hits the "remove" button, change the "Cancel" label to "No, cancel this change" which aligns with another button pair we have (when a person cancels unsaved changes) and is more clear about what the outcome will be.

## Tasks

- [x] Change "Update" to "Save" as depicted in the sketch files below:
- [Personal information](https://sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565)
- [Contact information](https://sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655)
- [Direct deposit](https://sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131)
(**Note** the changes affect many screens in multiple sections, but these are the links to the main sketch files where the changes can be seen) 
- [x] Change the modal button from "Cancel" to "No, cancel this change"  [here is the mock-up](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/YGaqMKL)
- [x]  Change the modal button from "Cancel" to "No, cancel this change" [Connected apps](https://www.sketch.com/s/479aa6d6-a7a7-4d82-acf1-c06a6699655e/a/JnmMD8G)
- [x] Conduct Unit tests 
- [x] Run E2E tests covering current code and regression
- [x] Notify PM if this needs to be deployed to Staging behind feature flag
  

## Acceptance Criteria
- [x] Complete all unit testing
- [x] End-to-end tests showing 0 violations
- [x] All axe checks pass
- [x] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [ ] Confirm PM has opened a new ticket to deploy changes to Production using feature flag, if needed

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)? Design, PM
- How can this work be validated? In staging
- What updates need to be made (e.g. product outline, use cases, contact center guide) 
     - adt'l sketch files?
     - Use cases
     - Contact Center guide

## Associated Tickets
- #48441

**Comment by SKasimow** [comment]
Hi @ericasauv09 - can you open a design ticket to update any act'l sketch files, user cases, user flows and the CC guide once this is implemented?

**Comment by ericasauv09** [comment]
@SKasimow all set, I created #49382

**Comment by SKasimow** [comment]
Thank you!

**Comment by adamwhitlock1** [comment]
This is ready to verify @Samara-Strauss. All buttons should now read Save instead of Update, and the remove modal button text has also been updated.

**Comment by Samara-Strauss** [comment]
Validated! Checked user 80 and 378 (for the edu direct deposit form), and all buttons have been updated as outlined.
