### ISSUE TITLE
Add OCTO reviewer's gh handle to "Collab Cycle feedback" ticket if feedback came directly from them

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#49384]
## User Story
As a VFS team member, I want to know which individuals from Governance and OCTO were involved when documenting Design Intent and Midpoint Review feedback tickets so that I can follow up with the correct individual if needed.

Assignee: @CherylEvans 
Peer Reviewer: @allison0034 

## Description
For the [Authenticated Experience Midpoint Review for their Audit UX improvements](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42601), the Design Feedback ticket had must, should and consider feedback from both @allison0034 and @humancompanion-usds , however it was written in a way where the Auth Exp team interpreted the feedback to only be from Allison. 

The purpose of this ticket is to modify our Design Intent and Midpoint Review operational guidance so that if/when OCTO provides feedback to the VFS team, the Governance team member is @ mentioning them in the feedback ticket so the VFS team member can see who all was involved.

## Impacted Artifacts
[How to provide feedback for a Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1934426130/How+to+provide+feedback+for+a+Design+Intent)
[How to provide feedback for a Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1945239838/How+to+provide+feedback+for+a+Midpoint+Review)
[How to document feedback for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+feedback+for+Staging+Review) (There are no actual changes to this document however, the DraftingTemplate Outline link is located in this document and that document will change.)
[DraftingTemplate Outline](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2385248274/DraftingTemplate+Outline)

## Tasks
- [x] For DI and MPR, add a step for tagging the OCTO reviewers gh handle in your feedback ticket if the feedback came directly from them. For example:
   - @octohandle: Use this design element instead.
- [x] For Staging Review, add a note to the Additional Information column of the **Issue Details** and **Recommendation** sections of the Individual Feedback worksheet of the DraftingTemplate Outline guidance. The notes should say to tag the OCTO reviewer's github handle if the feedback came directly from them.

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] VFS teams are notified if/when OCTO provides direct feedback at the DI, MPR and SR feedback tickets

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
@allison0034 Hi Allison. :-) This is ready for your review.  I have changed the source pages as opposed to creating copies, as the changes are somewhat minor. 
[How to provide feedback for a Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1934426130/How+to+provide+feedback+for+a+Design+Intent)
[How to provide feedback for a Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1945239838/How+to+provide+feedback+for+a+Midpoint+Review)
[How to document feedback for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+feedback+for+Staging+Review) (There are no actual changes to this document however, the DraftingTemplate Outline link is located in this document and that document will change.)
[DraftingTemplate Outline](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2385248274/DraftingTemplate+Outline)

**Comment by CherylEvans** [comment]
@allison0034 I incorporated all of the recommended changes. I completely agree with the placement.  It definitely makes more sense!
 
[How to provide feedback for a Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1934426130/How+to+provide+feedback+for+a+Design+Intent)
[How to provide feedback for a Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1945239838/How+to+provide+feedback+for+a+Midpoint+Review)
[How to document feedback for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+feedback+for+Staging+Review) (There are no actual changes to this document however, the DraftingTemplate Outline link is located in this document and that document will change.)
[DraftingTemplate Outline](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2385248274/DraftingTemplate+Outline)

**Comment by allison0034** [comment]
Thanks @CherylEvans ! I still see the "e" not included in the link on @octohandle for DI and MP.

**Comment by CherylEvans** [comment]
@allison0034 Thanks!  I forgot about those 2, doh!  Should be good now. :-)
