### ISSUE TITLE
FE | Profile | Military Info| Update FAQ

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#49385]
## Background

We need to update the FAQ section on the Military info page - both the question and the dropdown info have changed.

## Tasks
- [ ] Conduct Unit tests 
- [ ] Run E2E tests covering current code and regression
- [ ] Notify PM if this needs to be deployed to Staging behind feature flag
  

## Acceptance Criteria
- [ ] Complete all unit testing
- [ ] End-to-end tests showing 0 violations
- [ ] All axe checks pass
- [ ] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [ ] Confirm PM has opened a new ticket to deploy changes to Production using feature flag, if needed

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)?
- How can this work be validated?
- What updates need to be made (e.g. product outline, use cases, contact center guide)

## Associated Tickets
- #46564

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by jcatergovy** [comment]
Updated per the sketch but changed TTY to the new requirements in #49483.  @SKasimow @cgednalske 
![image.png](https://images.zenhubusercontent.com/632e0024b571f3ae02607148/c8dc955c-e72c-4e61-8592-523983f41bdf)

**Comment by SKasimow** [comment]
@jcatergovy - good catch on 711.

I am seeing some differences with the lay-out above compared to the sketch file but not sure if this is actual format or you just wanted us to review the content for accuracy?

**Comment by cgednalske** [comment]
Noticed a couple things in staging. It looks like the dropdown part of the FAQ still has some of the older language. The new language doesn't include "seeing" anymore and then there are two paragraph spaces we're missing after each mention of DEERS. 

And then I think we actually are supposed to have the TTY included as part of the link per [design system guidelines](https://design.va.gov/content-style-guide/dates-and-numbers).

Here's the Sketch image and text below for easy reference.

<img width="538" alt="Screen Shot 2022-11-30 at 12 38 39 PM" src="https://user-images.githubusercontent.com/79372956/204892504-6fae27da-3710-474f-8b10-d2836283be39.png">

> Some Veterans have reported that their military service information in their VA.gov profiles doesn’t seem right. When this happens, it’s because there’s an error in the information we’re pulling into VA.gov from the Defense Enrollment Eligibility Reporting System (DEERS).
> 
> If you don’t think your military service information is correct here, call the Defense Manpower Data Center (DMDC). They’ll work with you to update your information in DEERS.
> 
> You can call the DMDC at 800-538-9552 (TTY: +711). They're available Monday through Friday (except federal holidays), 8:00 a.m. to 8:00 p.m. ET.

**Comment by cgednalske** [comment]
EDIT TO ABOVE: Ignore the + for +711 though - I need to remove that from the Sketch files! (@SKasimow is that correct?)

**Comment by SKasimow** [comment]
@cgednalske : yes it should just be 711. 

I also noticed that the title for the dropdown is a diff size and background color vs the sketch file (which is why I was asking above whether the screenshot from @jcatergovy still needed to be formatted)

**Comment by cgednalske** [comment]
@SKasimow The gray background is just showing a different state (focus + hover), so that part is fine. I'm not sure about the yellow box. It looks like John's is matching what is shown on the design system site, but that's not what the design system Sketch library has. 

What he's done also matches the rest of Profile so I think that is fine as is, though I do want to check with the design system team to see why the site vs. their Sketch library is a bit different.

**Comment by SKasimow** [comment]
Ok thanks @cgednalske !

**Comment by jcatergovy** [comment]
Thank you for the feedback.  Does this look right?
![image.png](https://images.zenhubusercontent.com/632e0024b571f3ae02607148/2d529afb-14ac-4488-8a3c-9efd7f6edfab)

**Comment by SKasimow** [comment]
@jcatergovy - looks like you have some text in the wrong spot at end "if you have hearing loss, call."

**Comment by jcatergovy** [comment]
Ack!  Thank you @SKasimow , I'll fix that ASAP!

**Comment by SKasimow** [comment]
@jcatergovy - I am seeing you removed the extra text but still needs some other changes (using the old "seeing" content, "hearing loss). I think you may be looking at the sketch file in the ticket but not clicking on the "see latest version" button in orange at the top of the page. Here's the link to the version you should use (or CG pasted it a couple of comments above if that's easier): [new sketch file](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/v/b43pJZ/a/25Da5yp).

**Comment by jcatergovy** [comment]
@SKasimow This is now fixed in staging

**Comment by cgednalske** [comment]
Everything looks good except it looks like there's one last thing we hadn't caught yet ☹️ . In the updated, the last part about calling the DMDC is split up into two sentences like below. I only just noticed that difference, but I think that's the only thing that doesn't match the design. 

> You can call the DMDC at 800-538-9552 (TTY: 711). They're available Monday through Friday (except federal holidays), 8:00 a.m. to 8:00 p.m. ET.

**Comment by jcatergovy** [comment]
@cgednalske good catch.  I'll get that fix out ASAP.

**Comment by jcatergovy** [comment]
@cgednalske @SKasimow ready for validation in staging
