### ISSUE TITLE
Create user flow for current platform orientation

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#49383]
## User Story
As a Governance team member, I want to understand how people navigate the different orientations for VA Platform so that I am able to identify their pain points.

Assignee: @allison0034 @sterkenburgsara 

## Description
The goal of this ticket is to create a high-level user flow that diagrams the current scope of what people do (and in what order) as part of their Platform Orientation.
[Previous Platform Orientation Research](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1816985754/Platform+Orientation+Research?NO_SSR=1)
[Platform Orientation - current state service blueprint useful](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1634334965737/bf671d055e1072a001d00cd1d6b7dc89b0987bfc?sender=naomimarcussen8901)
[Platform Orientation User Flows](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2091057177/Platform+Orientation+User+Flows)

How will we measure the success of of Platform Orientation?

## Impacted Artifacts
- [Platform orientation swim lanes](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1668529634868/a5b8ecb4ac2acabc00f51215ad4ed5521941ec0a?sender=u045df875f30f7e9f34339908)

## Tasks
- [x] Review [onboarding checklist](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team%2C+analytics-insights%2C+analytics-request&template=orientation-epic.md&title=Platform+Orientation+Template+%5BYour+name+here%5D)
- [x] Review any existing user flows ([platform orientation blueprint](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1634334965737/bf671d055e1072a001d00cd1d6b7dc89b0987bfc?sender=b5d989c4-ad85-4df8-bdea-5e0e6d7e35da))
- [x] Document other steps of onboarding 
- [ ] Document who attends which orientation sessions and when (PM, designer, researchers, developers) (11-15: we are staying high level for this effort and will get more granular with journey maps)
- [x] Create a user flow/swim lane for platform orientation

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team members have a clear understanding how of users currently navigate Platform Orientation
- [x] Governance team members understand when users attend Platform Orientation and how long the orientation process takes

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
@sterkenburgsara can you take another look at this? I included Shira's comments.

**Comment by sterkenburgsara** [comment]
@shiragoodman @allison0034 question - does opening a ticket trigger the VFS Platform team to add them to VFS Team Roster & GH repos? Or do they need to close/submit the ticket.

This is nitpicky, but before the "opens platform orientation template" step happens for a VFS Team Member, they interact with the Platform Website guidance first, correct? I want to make sure we get all of our artifacts/touchpoints in this flow 

For Platform - feels like "run orientation sessions" is not connected to onboarding folks to GH repos, but I don't have a knee-jerk reaction on a better way to visually display that work as disconnected from the other tasks. I'll think on this.

I would also like to see us add a time spectrum to this process (how long can these steps take? Does step one happen in week 1?

**Comment by allison0034** [comment]
@sterkenburgsara there are labels on the ticket so it is automatically added to our backlog. That should be captured with "Sees new template on backlog and confirms "Share your info" is complete". Do you think I need to specifically say the label is already on the ticket?

**Comment by allison0034** [comment]
> For Platform - feels like "run orientation sessions" is not connected to onboarding folks to GH repos, but I don't have a knee-jerk reaction on a better way to visually display that work as disconnected from the other tasks. I'll think on this.

I agree. The sessions are not really on a time line except they are run at the same time once a month. I will remove the arrow and put it below that flow but still within our team.

> I would also be curious to see a time spectrum for this process (possibly running along the bottom of the table) that helps us understand how long these steps can take.

That would be nice, but also tricky bc they complete these things in their own individual time. We can't say something takes a week, or a month. It is totally up to them and we honestly do not know IF they even complete these things.

**Comment by shiragoodman** [comment]
@allison0034 looks like you got the responses covered. If you or @sterkenburgsara are unsure of anything, just let me know.

**Comment by sterkenburgsara** [comment]
> > does opening a ticket trigger the VFS Platform team to add them to VFS Team Roster & GH repos? Or do they need to close/submit the ticket.
> 
> @sterkenburgsara there are labels on the ticket so it is automatically added to our backlog. That should be captured with "Sees new template on backlog and confirms "Share your info" is complete". Do you think I need to specifically say the label is already on the ticket?

No, I think it's good - thank you for clarifying.

**Comment by sterkenburgsara** [comment]
> > For Platform - feels like "run orientation sessions" is not connected to onboarding folks to GH repos, but I don't have a knee-jerk reaction on a better way to visually display that work as disconnected from the other tasks. I'll think on this.
> 
> I agree. The sessions are not really on a time line except they are run at the same time once a month. I will remove the arrow and put it below that flow but still within our team.

> 
> > I would also be curious to see a time spectrum for this process (possibly running along the bottom of the table) that helps us understand how long these steps can take.
> 
> That would be nice, but also tricky bc they complete these things in their own individual time. We can't say something takes a week, or a month. It is totally up to them and we honestly do not know IF they even complete these things.

Agreed on both counts - I like the updates you made - it feels very accurate to me!

**Comment by shiragoodman** [comment]
@sterkenburgsara @allison0034 I created an Artifacts heading in the[ Platform Orientation Discovery initiative ticket.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/29671) Please be sure to link the user flow there, and moving forward, link any other artifacts created during the discovery process. ty!
