### ISSUE TITLE
[Research] Payment Info V2: Conduct UAT

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#49386]
## Background

Hold UAT sessions for the Payment Info V2 feature.

## Tasks
- [x] Coordinate with FE to ensure feature flag is flipped for the appropriate users
- [x] Conduct UAT/Usability Sessions
- [ ] Document testing/findings

**Comment by aagosto90** [comment]
There's another ticket for documenting findings so I'm closing this one out
