### ISSUE TITLE
Research getting mock data into PEs

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#49397]
## Issue Description
Preview environment users may prefer to use mock data for their preview environment instance. In order to accommodate a mock data workflow, the preview environment will need to be created with `vets-api-mockdata` in place and configured.

---

## Tasks
- [ ] Research a method for configuring a preview environment to use mock data instead of lower environments
- [ ] Assess how to get `vets-api-mockdata` pulled and installed on the backend image

## Acceptance Criteria
- [ ] A preview environment can be configured to use live lower environment endpoints or mocked data
- [ ] A preview environment configured to use mocked data responds to user interactions with mocked data from `vets-api-mockdata`

**Comment by pjhill** [comment]
This ticket presumed that the user would be able to select either mocked data or live integrations with lower environment endpoints. Other discovery efforts indicate that our MVP for Preview Environments will only allow the users to use a default configuration of Preview Environments that includes `vets-api-mockdata` every time.

Since there are no configurations to be made, there isn't really any research into how to create logic that generates a BE with mocked data some of the time.
