### ISSUE TITLE
Team members: Review first draft of Mapping Intake process

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#49413]
## Issue Description
Review the draft that was assembled to described the process for a potential Mapping Intake request

From A= a user thinks they might need some mapping done, to K= the required information has been submitted, to Z = the SDT team has prioritized this work.

Note: Explanation of A is out of scope, just that it exists.

[Draft](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2424668161/Mapping+Request+Intake+Features+and+Process) of process

## Tasks
- [x] Review draft and make comments/edits (Bryan)
- [x] Review draft and make comments/edits (Taylor)
- [ ] Review draft and make comments/edits (Nicole) (Removed due to OoO conflicts)

## Acceptance Criteria
- [x] First draft is reviewed by all
