### ISSUE TITLE
Spanish translation for PACT Act toxic exposure screening Q&A

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#49427]
## Issue Description
We recently added a new Q&A to the [PACT Act](https://www.va.gov/resources/the-pact-act-and-your-va-benefits/) article about toxic exposure screenings at VA. We need to get this content translated in Spanish and added to the Spanish version of the page.

Word doc sent to translators: [https://app.zenhub.com/files/133843125/4efe93fd-2eab-43df-8428-fbb9532e8557/download](https://app.zenhub.com/files/133843125/4efe93fd-2eab-43df-8428-fbb9532e8557/download)

## Tasks
- [x] Send content to translators (Randi)
- [x] Update Drupal page (Aliyah)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] New content is on the live Spanish page

**Comment by RLHecht** [comment]
@aliyahblackmore Here is the translation back from the state department: [https://app.zenhub.com/files/133843125/9906afc5-1a4f-450d-85ae-ba2d1967080e/download](https://app.zenhub.com/files/133843125/9906afc5-1a4f-450d-85ae-ba2d1967080e/download)

**Comment by aliyahblackmore** [comment]
Hi @megzehn this is ready for you! 
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=48330

As mentioned in the 10.26 ticket, these can all be published at the same time!

**Comment by RLHecht** [comment]
This content is now live. Will send the live link for QA but will close this for now.
