### ISSUE TITLE
FE | Profile | Notification Settings | Create Feature Flag for New Mobile Flow

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#49436]
## Background

As part of the effort to improve the experience of adding a mobile number for users setting up their Notification preferences, we need to create a feature toggle in support of the new page and new flow.

## Tasks
- [ ] Create feature flag in support of the upcoming change in Notification settings/mobile number
- [ ] Implement at 100% to prevent this from showing in prod
- [ ] Smoke test in staging
- [ ] Validate in staging with PM and PO

## Acceptance Criteria

- [ ] Feature flags created for new mobile flow
- [ ] Tested in staging
- [ ] Validated in staging with PM 

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)? FE, PM
- How can this work be validated?  Staging
- What updates need to be made (e.g. product outline, use cases, contact center guide) n/a

## Associated Tickets
- #49251

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
@adamwhitlock1 - here's the first of 3 tickets we discussed yesterday. Please review and lmk if I need to make any changes or additions. Thanks!

**Comment by adamwhitlock1** [comment]
I'm closing this issue as it is the same as ongoing work which kicked off with this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/53545
