### ISSUE TITLE
Publish and announce QA Standards to VFS teams

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#49433]
## User Story
As a VFS team member, I want to be made aware of the new QA Standards so that I can ensure my team is meeting the standards when they are enforced in Staging Review. 

Assignee: @it-harrison 
Peer Reviewer: @sterkenburgsara 

## Description
OCTO approved the [Proposed Changes to QA Standards](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2403237889/Proposed+Changes+to+QA+Standards), so now we must move forward with publishing them to Platform Website for VFS teams to view and understand.

This work will also include announcing the new QA Standards on Slack and in the Collab Cycle change history page.

## Impacted Artifacts
Current [QA Standards page](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards) on PW
[Proposed Changes to QA Standards](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2403237889/Proposed+Changes+to+QA+Standards)
[Change history page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/change-history)

## Tasks
- [x] Edit the [QA Standards page](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2375909428/Quality+assurance+standards) and replace with the content from the Proposed Changes to QA Standards page
- [x] Confirm the page is updated/published to Platform Website
- [x] Draft a change history post in the Governance team/Documentation Drafts page announcing the new QA Standards. 
   - The announcement should state that the QA Standards are available now but Governance team will not uphold them in the Collaboration Cycle until January 3, 2023. The post should include a link to the QA standards. See [Change History](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/change-history) page for previous posts - typically the first sentence is in bold and states the change that was made. The following sentences include additional details and links, etc.
- [x] Shira will peer review post and suggest changes
- [x] Once Shira approves, publish to Platform Website.
- [x] Once published to PW, share on #vfs-all-teams and #vfs-change-announcements Slack channels following the [Platform Communication Playbook/Change Communication Guide](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2317647873/Change+Communication+Guide)
- [x] Change should also be communicated in Team of Teams, so notify Shira once all above is published/complete

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Revised QA Standards have been published on Platform Website
- [x] VFS teams have been made aware of the new QA Standards
- [x] VFS teams understand that Platform will not evaluate their products for the QA Standards until January 9, 2023

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
@shiragoodman @sterkenburgsara  I have a [draft of the change history document](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2435153921/Copy+of+Change+history+-+QA+Standards) for you to review.

**Comment by CherylEvans** [comment]
@it-harrison Hey there Ian.  I reviewed your draft, and made grammatical changes to include using "active" voice as opposed to "passive" voice.  :-). Great job, it looks good to me!

**Comment by sterkenburgsara** [comment]
@it-harrison just looked as well and I don't have any feedback. It appears already published to Platform Website to me, but I did look at the version history, and have to say this table is much more clear! I think it's a big improvement.

**Comment by shiragoodman** [comment]
@it-harrison I took a look as well and added a comment. Please let me know if you have any questions.

@sterkenburgsara I looked on the Change history page on Platform Website and I don't see that this post has been published. Can you show me where you saw that?

**Comment by sterkenburgsara** [comment]
@shiragoodman I should have clarified - I was referencing the QA Standards, which appear published on Platform, not Ian's change history announcement.

**Comment by shiragoodman** [comment]
np @sterkenburgsara! thank you.

@it-harrison I added 1 more comment to the change history post re: date change but after that, it should be good to go! Once the change history page is updated tomorrow, we can post the messages to Slack.

Thank you!

**Comment by it-harrison** [comment]
Hi @shiragoodman the change history has been published. I have drafted a notice to post on slack...could you give it a look and see if it is ok?

QA Standards Updated
Today, 11/18/2022, Governance team has released an updated [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards). The Standards clarify what the Governance team will expect of VFS teams launching new products through the Collaboration Cycle, starting January 9th, 2022. If you have any questions, please reach out to the Governance team on #vfs-platform-support.

**Comment by shiragoodman** [comment]
Thanks @it-harrison. Have you seen the[ Post-Change Slack Communication template](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2317647898/Change+Communication+Plan#Post-Change-Slack-Communication%3A)? This is how Service Design wants us to structure change announcements. Could you reformat your post to fit this template?

**Comment by it-harrison** [comment]
Hi @shiragoodman I have reformatted the notice:

Attention: VFS teams

QA Standards have been updated

Today, 11/18/2022, Governance team has released an updated QA Standards. 

Impact: The Standards clarify what the Governance team will expect of VFS teams launching new products through the Collaboration Cycle, starting January 9th, 2022.

Documentation:  See [the QA Standards page](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).

Questions: Please post ay questions in thread or reach out to the Governance team on #vfs-platform-support.

**Comment by shiragoodman** [comment]
**Attention:** VFS teams

**QA Standards have been updated.** 

**On 11/17/2022, Governance team** has released the updated QA Standards. See the [Collaboration Cycle Change history page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/change-history) for more information on what's been updated. 

**Impact:** The standards clarify what the Governance team will expect of VFS teams launching new products through the Collaboration Cycle, starting January 9th, 2023.

**Documentation:** [QA Standards page](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards) on Platform Website

**Questions:** Please thread any questions or reach out to the Governance team on #vfs-platform-support.

**Comment by shiragoodman** [comment]
@it-harrison I made some changes above. if possible, please get this posted today - thanks Ian!

**Comment by it-harrison** [comment]
@shiragoodman - the notice has been posted
