### ISSUE TITLE
KMS Key Rotation - Implementation (phase 1)

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#49447]
## Issue Description

Following the completion of the solutioning phase for the annual KMS key rotation, we are now ready to implement the strategies devised. This involves the execution of the job failure strategy, setting up the record distribution among Sidekiq workers, enabling automatic key rotation in AWS, and potentially incorporating Sidekiq Batches.

## Tasks

- [x] Implement the strategy to manage job failures, ensuring the process can resume from where it stopped.
- [x] Establish the system to divide table records evenly among a predetermined number of Sidekiq workers.
- [x] Enable automatic key rotation for existing KMS keys in AWS.
- [x] Depending on the insights gathered from the solutioning phase, incorporate the usage of Sidekiq Batches.
- [x] Write a rake task to kick off the KMS key rotation process.

## Acceptance Criteria

- [x] The job failure strategy is implemented, allowing the process to resume from the point of failure.
- [x] The system is set up to distribute table records among a given number of Sidekiq workers effectively.
- [x] Automatic key rotation for existing KMS keys in AWS is enabled and functioning as expected.
- [x] If applicable, Sidekiq Batches are implemented.
- [x] A rake task is written and successfully initiates the KMS key rotation process.

**Comment by holdenhinkle** [comment]
To-do:
- [ ] update `encryption_updated_at` in the monkeypatch file
- [ ] create rake task
- [ ] write tests
- [ ] add `encryption_updated_at` field to models in each env

**Comment by holdenhinkle** [comment]
I've got this all coded up, sans tests. I haven't run it yet.

I'll try to run it locally tomorrow. I'll pick a table that needs to be updated, add the new `encryption_updated_at` column to it, and see if I can run this locally. When i say 'see if I can run this locally', i mean, will calling `rotate_kms_key!` on a record work locally?

**Comment by holdenhinkle** [comment]
Update code to use `Sidekiq::Client.push_bulk` - https://github.com/mperham/sidekiq/wiki/Batches#huge-batches

**Comment by holdenhinkle** [comment]
Didn't have much time to work on this today. Just did a little clean up at the end of the day. Hoping to run, debug and write tests on Monday.

**Comment by holdenhinkle** [comment]
I finally had some time to circle back to this today. I got the code running up to the point where we query the db for records that need to be updated. That query looks for records where `encryption_updated_at` is nil or within the last 11 months. I need to add that column to the following tables for the following models next:

```
[
  DecisionReviewEvidenceAttachment (call 'DecisionReviewEvidenceAttachment.connection' to establish a connection)
  HCAAttachment (call 'HCAAttachment.connection' to establish a connection)
  SupportingEvidenceAttachment (call 'SupportingEvidenceAttachment.connection' to establish a connection)
  Form1010cg::Attachment (call 'Form1010cg::Attachment.connection' to establish a connection)
  Preneeds::PreneedAttachment (call 'Preneeds::PreneedAttachment.connection' to establish a connection)
  AppealSubmission (call 'AppealSubmission.connection' to establish a connection)
  SavedClaim::Burial (call 'SavedClaim::Burial.connection' to establish a connection)
  SavedClaim::DependencyVerificationClaim (call 'SavedClaim::DependencyVerificationClaim.connection' to establish a connection)
  SavedClaim::EducationCareerCounselingClaim (call 'SavedClaim::EducationCareerCounselingClaim.connection' to establish a connection)
  SavedClaim::Pension (call 'SavedClaim::Pension.connection' to establish a connection)
  SavedClaim::Ask (call 'SavedClaim::Ask.connection' to establish a connection)
  SavedClaim::CaregiversAssistanceClaim (call 'SavedClaim::CaregiversAssistanceClaim.connection' to establish a connection)
  SavedClaim::CoeClaim (call 'SavedClaim::CoeClaim.connection' to establish a connection)
  SavedClaim::DependencyClaim (call 'SavedClaim::DependencyClaim.connection' to establish a connection)
  SavedClaim::DisabilityCompensation::Form526AllClaim (call 'SavedClaim::DisabilityCompensation::Form526AllClaim.connection' to establish a connection)
  SavedClaim::DisabilityCompensation::Form526IncreaseOnly (call 'SavedClaim::DisabilityCompensation::Form526IncreaseOnly.connection' to establish a connection)
  SavedClaim::EducationBenefits::VA0993 (call 'SavedClaim::EducationBenefits::VA0993.connection' to establish a connection)
  SavedClaim::EducationBenefits::VA0994 (call 'SavedClaim::EducationBenefits::VA0994.connection' to establish a connection)
  SavedClaim::EducationBenefits::VA10203 (call 'SavedClaim::EducationBenefits::VA10203.connection' to establish a connection)
  SavedClaim::EducationBenefits::VA1990 (call 'SavedClaim::EducationBenefits::VA1990.connection' to establish a connection)
  SavedClaim::EducationBenefits::VA1990e (call 'SavedClaim::EducationBenefits::VA1990e.connection' to establish a connection)
  SavedClaim::EducationBenefits::VA1990n (call 'SavedClaim::EducationBenefits::VA1990n.connection' to establish a connection)
  SavedClaim::EducationBenefits::VA1990s (call 'SavedClaim::EducationBenefits::VA1990s.connection' to establish a connection)
  SavedClaim::EducationBenefits::VA1995 (call 'SavedClaim::EducationBenefits::VA1995.connection' to establish a connection)
  SavedClaim::EducationBenefits::VA5490 (call 'SavedClaim::EducationBenefits::VA5490.connection' to establish a connection)
  SavedClaim::EducationBenefits::VA5495 (call 'SavedClaim::EducationBenefits::VA5495.connection' to establish a connection)
  SavedClaim::VeteranReadinessEmploymentClaim (call 'SavedClaim::VeteranReadinessEmploymentClaim.connection' to establish a connection)
  EducationStemAutomatedDecision (call 'EducationStemAutomatedDecision.connection' to establish a connection)
  Form1095B (call 'Form1095B.connection' to establish a connection)
  Form526Submission (call 'Form526Submission.connection' to establish a connection)
  Form5655Submission (call 'Form5655Submission.connection' to establish a connection)
  GibsNotFoundUser (call 'GibsNotFoundUser.connection' to establish a connection)
  InProgressForm (call 'InProgressForm.connection' to establish a connection)
  PersistentAttachments::DependencyClaim (call 'PersistentAttachments::DependencyClaim.connection' to establish a connection)
  PersistentAttachments::LgyClaim (call 'PersistentAttachments::LgyClaim.connection' to establish a connection)
  PersistentAttachments::PensionBurial (call 'PersistentAttachments::PensionBurial.connection' to establish a connection)
  AsyncTransaction::VAProfile::AddressTransaction (call 'AsyncTransaction::VAProfile::AddressTransaction.connection' to establish a connection)
  AsyncTransaction::VAProfile::EmailTransaction (call 'AsyncTransaction::VAProfile::EmailTransaction.connection' to establish a connection)
  AsyncTransaction::VAProfile::InitializePersonTransaction (call 'AsyncTransaction::VAProfile::InitializePersonTransaction.connection' to establish a connection)
  AsyncTransaction::VAProfile::PermissionTransaction (call 'AsyncTransaction::VAProfile::PermissionTransaction.connection' to establish a connection)
  AsyncTransaction::VAProfile::TelephoneTransaction (call 'AsyncTransaction::VAProfile::TelephoneTransaction.connection' to establish a connection)
  AsyncTransaction::Vet360::AddressTransaction (call 'AsyncTransaction::Vet360::AddressTransaction.connection' to establish a connection)
  AsyncTransaction::Vet360::EmailTransaction (call 'AsyncTransaction::Vet360::EmailTransaction.connection' to establish a connection)
  AsyncTransaction::Vet360::InitializePersonTransaction (call 'AsyncTransaction::Vet360::InitializePersonTransaction.connection' to establish a connection)
  AsyncTransaction::Vet360::PermissionTransaction (call 'AsyncTransaction::Vet360::PermissionTransaction.connection' to establish a connection)
  AsyncTransaction::Vet360::TelephoneTransaction (call 'AsyncTransaction::Vet360::TelephoneTransaction.connection' to establish a connection)
  Veteran::Service::Representative (call 'Veteran::Service::Representative.connection' to establish a connection)
  HealthQuest::QuestionnaireResponse (call 'HealthQuest::QuestionnaireResponse.connection' to establish a connection)
  CovidVaccine::V0::ExpandedRegistrationSubmission (call 'CovidVaccine::V0::ExpandedRegistrationSubmission.connection' to establish a connection)
  CovidVaccine::V0::RegistrationSubmission (call 'CovidVaccine::V0::RegistrationSubmission.connection' to establish a connection)
  ClaimsApi::AutoEstablishedClaim (call 'ClaimsApi::AutoEstablishedClaim.connection' to establish a connection)
  ClaimsApi::EvidenceWaiverSubmission (call 'ClaimsApi::EvidenceWaiverSubmission.connection' to establish a connection)
  ClaimsApi::PowerOfAttorney (call 'ClaimsApi::PowerOfAttorney.connection' to establish a connection)
  ClaimsApi::SupportingDocument (call 'ClaimsApi::SupportingDocument.connection' to establish a connection)
  AppealsApi::HigherLevelReview (call 'AppealsApi::HigherLevelReview.connection' to establish a connection)
  AppealsApi::NoticeOfDisagreement (call 'AppealsApi::NoticeOfDisagreement.connection' to establish a connection)
  AppealsApi::SupplementalClaim (call 'AppealsApi::SupplementalClaim.connection' to establish a connection)
]
```

Doing that now...

**Comment by holdenhinkle** [comment]
I finally had some time to circle back to this today. I got the code running up to the point where we query the db for records that need to be updated. That query looks for records where `encryption_updated_at` is nil or within the last 11 months. I need to add that column to the following tables for the following models next:

```
[
  DecisionReviewEvidenceAttachment (call 'DecisionReviewEvidenceAttachment.connection' to establish a connection)
  HCAAttachment (call 'HCAAttachment.connection' to establish a connection)
  SupportingEvidenceAttachment (call 'SupportingEvidenceAttachment.connection' to establish a connection)
  Form1010cg::Attachment (call 'Form1010cg::Attachment.connection' to establish a connection)
  Preneeds::PreneedAttachment (call 'Preneeds::PreneedAttachment.connection' to establish a connection)
  AppealSubmission (call 'AppealSubmission.connection' to establish a connection)
  SavedClaim::Burial (call 'SavedClaim::Burial.connection' to establish a connection)
  SavedClaim::DependencyVerificationClaim (call 'SavedClaim::DependencyVerificationClaim.connection' to establish a connection)
  SavedClaim::EducationCareerCounselingClaim (call 'SavedClaim::EducationCareerCounselingClaim.connection' to establish a connection)
  SavedClaim::Pension (call 'SavedClaim::Pension.connection' to establish a connection)
  SavedClaim::Ask (call 'SavedClaim::Ask.connection' to establish a connection)
  SavedClaim::CaregiversAssistanceClaim (call 'SavedClaim::CaregiversAssistanceClaim.connection' to establish a connection)
  SavedClaim::CoeClaim (call 'SavedClaim::CoeClaim.connection' to establish a connection)
  SavedClaim::DependencyClaim (call 'SavedClaim::DependencyClaim.connection' to establish a connection)
  SavedClaim::DisabilityCompensation::Form526AllClaim (call 'SavedClaim::DisabilityCompensation::Form526AllClaim.connection' to establish a connection)
  SavedClaim::DisabilityCompensation::Form526IncreaseOnly (call 'SavedClaim::DisabilityCompensation::Form526IncreaseOnly.connection' to establish a connection)
  SavedClaim::EducationBenefits::VA0993 (call 'SavedClaim::EducationBenefits::VA0993.connection' to establish a connection)
  SavedClaim::EducationBenefits::VA0994 (call 'SavedClaim::EducationBenefits::VA0994.connection' to establish a connection)
  SavedClaim::EducationBenefits::VA10203 (call 'SavedClaim::EducationBenefits::VA10203.connection' to establish a connection)
  SavedClaim::EducationBenefits::VA1990 (call 'SavedClaim::EducationBenefits::VA1990.connection' to establish a connection)
  SavedClaim::EducationBenefits::VA1990e (call 'SavedClaim::EducationBenefits::VA1990e.connection' to establish a connection)
  SavedClaim::EducationBenefits::VA1990n (call 'SavedClaim::EducationBenefits::VA1990n.connection' to establish a connection)
  SavedClaim::EducationBenefits::VA1990s (call 'SavedClaim::EducationBenefits::VA1990s.connection' to establish a connection)
  SavedClaim::EducationBenefits::VA1995 (call 'SavedClaim::EducationBenefits::VA1995.connection' to establish a connection)
  SavedClaim::EducationBenefits::VA5490 (call 'SavedClaim::EducationBenefits::VA5490.connection' to establish a connection)
  SavedClaim::EducationBenefits::VA5495 (call 'SavedClaim::EducationBenefits::VA5495.connection' to establish a connection)
  SavedClaim::VeteranReadinessEmploymentClaim (call 'SavedClaim::VeteranReadinessEmploymentClaim.connection' to establish a connection)
  EducationStemAutomatedDecision (call 'EducationStemAutomatedDecision.connection' to establish a connection)
  Form1095B (call 'Form1095B.connection' to establish a connection)
  Form526Submission (call 'Form526Submission.connection' to establish a connection)
  Form5655Submission (call 'Form5655Submission.connection' to establish a connection)
  GibsNotFoundUser (call 'GibsNotFoundUser.connection' to establish a connection)
  InProgressForm (call 'InProgressForm.connection' to establish a connection)
  PersistentAttachments::DependencyClaim (call 'PersistentAttachments::DependencyClaim.connection' to establish a connection)
  PersistentAttachments::LgyClaim (call 'PersistentAttachments::LgyClaim.connection' to establish a connection)
  PersistentAttachments::PensionBurial (call 'PersistentAttachments::PensionBurial.connection' to establish a connection)
  AsyncTransaction::VAProfile::AddressTransaction (call 'AsyncTransaction::VAProfile::AddressTransaction.connection' to establish a connection)
  AsyncTransaction::VAProfile::EmailTransaction (call 'AsyncTransaction::VAProfile::EmailTransaction.connection' to establish a connection)
  AsyncTransaction::VAProfile::InitializePersonTransaction (call 'AsyncTransaction::VAProfile::InitializePersonTransaction.connection' to establish a connection)
  AsyncTransaction::VAProfile::PermissionTransaction (call 'AsyncTransaction::VAProfile::PermissionTransaction.connection' to establish a connection)
  AsyncTransaction::VAProfile::TelephoneTransaction (call 'AsyncTransaction::VAProfile::TelephoneTransaction.connection' to establish a connection)
  AsyncTransaction::Vet360::AddressTransaction (call 'AsyncTransaction::Vet360::AddressTransaction.connection' to establish a connection)
  AsyncTransaction::Vet360::EmailTransaction (call 'AsyncTransaction::Vet360::EmailTransaction.connection' to establish a connection)
  AsyncTransaction::Vet360::InitializePersonTransaction (call 'AsyncTransaction::Vet360::InitializePersonTransaction.connection' to establish a connection)
  AsyncTransaction::Vet360::PermissionTransaction (call 'AsyncTransaction::Vet360::PermissionTransaction.connection' to establish a connection)
  AsyncTransaction::Vet360::TelephoneTransaction (call 'AsyncTransaction::Vet360::TelephoneTransaction.connection' to establish a connection)
  Veteran::Service::Representative (call 'Veteran::Service::Representative.connection' to establish a connection)
  HealthQuest::QuestionnaireResponse (call 'HealthQuest::QuestionnaireResponse.connection' to establish a connection)
  CovidVaccine::V0::ExpandedRegistrationSubmission (call 'CovidVaccine::V0::ExpandedRegistrationSubmission.connection' to establish a connection)
  CovidVaccine::V0::RegistrationSubmission (call 'CovidVaccine::V0::RegistrationSubmission.connection' to establish a connection)
  ClaimsApi::AutoEstablishedClaim (call 'ClaimsApi::AutoEstablishedClaim.connection' to establish a connection)
  ClaimsApi::EvidenceWaiverSubmission (call 'ClaimsApi::EvidenceWaiverSubmission.connection' to establish a connection)
  ClaimsApi::PowerOfAttorney (call 'ClaimsApi::PowerOfAttorney.connection' to establish a connection)
  ClaimsApi::SupportingDocument (call 'ClaimsApi::SupportingDocument.connection' to establish a connection)
  AppealsApi::HigherLevelReview (call 'AppealsApi::HigherLevelReview.connection' to establish a connection)
  AppealsApi::NoticeOfDisagreement (call 'AppealsApi::NoticeOfDisagreement.connection' to establish a connection)
  AppealsApi::SupplementalClaim (call 'AppealsApi::SupplementalClaim.connection' to establish a connection)
]
```

Doing that now...

**Comment by holdenhinkle** [comment]
Here are the tables that need to be updated for those ^ models:
```
form_attachments
appeal_submissions
saved_claims
education_stem_automated_decisions
form1095_bs
form526_submissions
form5655_submissions
gibs_not_found_users
in_progress_forms
persistent_attachments
async_transactions
veteran_representatives
health_quest_questionnaire_responses
covid_vaccine_expanded_registration_submissions
covid_vaccine_registration_submissions
claims_api_auto_established_claims
claims_api_evidence_waiver_submissions
claims_api_power_of_attorneys
claims_api_supporting_documents
appeals_api_higher_level_reviews
appeals_api_notice_of_disagreements
appeals_api_supplemental_claims
```

**Comment by holdenhinkle** [comment]
I got to work on this a little bit today again. I'm ready to test it. It looks like there isn't any seed data, so I'll create some tomorrow to test locally.

**Comment by holdenhinkle** [comment]
`Sidekiq::Client.push_bulk` takes an `args` argument which needs to be an array of array:

```
          # args must be an array of arrays:
          # error: ArgumentError (Bulk arguments must be an Array of Arrays: [[1], [2]])
          # docs - https://github.com/mperham/sidekiq/wiki/Batches#huge-batches
```

What's super annoying is that it converts the value in each sub array to a string:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/cc2679b4-a6a3-4278-8f6f-3a71c154b7c2)

Looks like I can't use `Sidekiq::Client.push_bulk`.

WIP commit - https://github.com/department-of-veterans-affairs/vets-api/pull/11117/commits/be4014cb0190001601923921a55e1a4c62c2a304

**Comment by holdenhinkle** [comment]
Ah, so this is the way Sidekiq works! 

> The arguments you pass to perform_async must be composed of simple JSON datatypes: string, integer, float, boolean, null, array and hash. The Sidekiq client API uses JSON.dump to send the data to Redis. The Sidekiq server pulls that JSON data from Redis and uses JSON.load to convert the data back into Ruby types to pass to your perform method. Don't pass symbols or complex Ruby objects (like Date or Time!) as those will not survive the dump/load round trip correctly.

Right, the Ruby object can't be saved to Redis as an object.

So we'll have to save the model name and the id and do another query...

**Comment by holdenhinkle** [comment]
Was able to spent some time on this again today.

I have everything working except for monkey patching `module KmsEncrypted::Model`. I put a `byebug` in `#define_method` but it isn't being picked up, so I don't think this monkey patch file itself is being picked up.

The monkey patch is suppose to:

- prevent `updated_at` value from being updated
- update `encryption_updated_at`

**Comment by npeterson54** [comment]
@holdenhinkle Can this be closed out?

**Comment by npeterson54** [comment]
added to sprint for COP work

**Comment by holdenhinkle** [comment]
I resurrected the branch and PR for this and merged in master, etc.

I reacquainted myself with the problem and the code.

Now I just have to figure out how I was testing the code locally as I was writing it. I think I ran the rake task which queues jobs in Sidekiq, and then Sidekiq executes them one by one. When I run vets-api using the `foreman start -m all=1,clamd=0,freshclam=0` command so Sidekiq runs, I keep getting a `Constant not initialized` error when this line executes in `KmsKeyRotation::UpdateRecordsJob`

`record_identifiers['model'].constantize.find(record_identifiers['id']).rotate_kms_key!`

`record_identifiers['model'].constantize` is returning that error. 

I'm wondering if the class of whatever instance `record_identifiers['model']` is has been initialized. Oh, I know how to test that I think. I'll do it first thing tomorrow.

**Comment by holdenhinkle** [comment]
The problem is classes are not eager loaded in dev. I updated the following so I can develop and test this locally:

File - `config/environments/development.rb`

```
  # Do not eager load code on boot.
  config.eager_load = false
```

I set `config.eager_load` to `true`.

**Comment by holdenhinkle** [comment]
It's working!

Existing record which was never updated so `encryption_updated_at` is `nil`. Also note the `updated_at` value:
```
=> #<SavedClaim::Burial id: 5001, created_at: "2023-06-27 18:19:21.853928000 +0000", updated_at: "2023-06-27 18:19:21.853928000 +0000", form_id: "21P-530", guid: "fbe0dce0-7cab-461c-af1b-5ed47873f83c", form: [FILTERED], encrypted_kms_key: "v1:insecure+data+A6ZHEyVTVBbmVPRnU0RDRmVkdjckRJRDI...", verified_decryptable_at: nil, encryption_updated_at: nil>   
```

Same record. Note:

- the `updated_at` value is the same
- the `encrypted_kms_key` value has been updated
- the `encryption_updated_at` has been set with the datetime in which `encrypted_kms_key` was updated:

```
=> #<SavedClaim::Burial id: 5001, created_at: "2023-06-27 18:19:21.853928000 +0000", updated_at: "2023-06-27 18:19:21.853928000 +0000", form_id: "21P-530", guid: "fbe0dce0-7cab-461c-af1b-5ed47873f83c", form: [FILTERED], encrypted_kms_key: "v1:insecure+data+A6R2wwb09YU3JLSEJYdzN1b01JVWlwOE1...", verified_decryptable_at: nil, encryption_updated_at: "2023-06-27 18:26:24.785610000 +0000">   
```

**Comment by holdenhinkle** [comment]
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/316c40b0-8b5a-417b-8e1c-49107714d298)

**Comment by holdenhinkle** [comment]
`KmsKeyRotation::Batcher.on_complete` isn't being called so it's not looping through the records and creating a new batch after a batch is completed. This is because the `Sidekiq::Batch::Middleware` middleware is missing. I'm having trouble adding it. Every time I do, puma crashes on startup when I run the app using the `foreman` command.

**Comment by holdenhinkle** [comment]
Huh - https://github.com/sidekiq/sidekiq/wiki/Batches

>Don't ever disable retries in a batch job. If the job fails, it disappears and the batch will never succeed. You need retries to diagnose and fix the job so the batch succeeds.

**Comment by holdenhinkle** [comment]
I fixed this:

>KmsKeyRotation::Batcher.on_complete isn't being called so it's not looping through the records and creating a new batch after a batch is completed. This is because the Sidekiq::Batch::Middleware middleware is missing. I'm having trouble adding it. Every time I do, puma crashes on startup when I run the app using the foreman command.

That wasn't the issue. The issue was with how I was setting the batch callbacks.

It's working well now - it's updating all the records in the db that need to be re-encrypted, batching them along the way, until they've all been updated.

**Comment by holdenhinkle** [comment]
I started working on accounting for records that are in the Sidekiq retries queue because we cannot disable retries for Batched jobs.

The idea is to store all batch ids in a class instance variable that can be updated by each instance of the class.

Before we grab a bunch of records to batch off to Sidekiq, we first grab all of the jobs in retries and see if any of them have a batch id that we're tracking. When we're grabbing a new bunch of records to batch off to Sidekiq we check to make sure they're not being retried; if they are we skip the record because we don't want it in any of the Sidekiq queues twice.

I'm not sure if this is work perfectly.

So notes I put in the code:
```
# Reties for a job cannot be disabled in a batch job, therefore we need to
# handle retries ourselves. If we don't, a record could be queued to be updated
# multiple times.

# Will tracking the batch ids (bids) in a class instance variable work in EKS?
# What if this script is running and vets-api is redeployed and the vets-api instance
# this is running gets torn down? We'll loose these bid values.
```

Also, I'm guessing there might be race conditions between what Sidekiq is processing and what retries are returned when we query for them.

I'm not sure that will matter though? The worst case scenario is that a record will be re-encrypted twice.

To be continued tomorrow.

**Comment by holdenhinkle** [comment]
To-do (will break into other tickets):

- Finalize implementation for using Sidekiq Batch callbacks so the script continues to loop until all records are updated
- Finalize implementation for storing jobs that are in retries so their associated records can be skipped when grabbing new records to batch to Sidekiq (is current method of storing a hash in memory okay?)
- Write tests
- Test on dev or staging
- Work with DevOps and @LindseySaari to create a plan to safely run this against the production database
- Work with DevOps and @LindseySaari to run the script against the production database
