### ISSUE TITLE
KMS Key Rotation - Solutioning

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#49445]
## Issue Description

We are working on automating the KMS key rotation annually. As we progress, we need to find effective solutions to address some challenges that include dealing with potential job failures, distributing table records among Sidekiq workers, and navigating the nuances of AWS KMS key rotation.

## Tasks

- [x] Draft a strategy for managing potential job failures that allows us to resume from the point of failure.
- [x] Conceptualize a method to distribute table records evenly among an arbitrary number of Sidekiq workers.
- [x] Analyze the details and implications of enabling automatic key rotation for existing KMS keys in AWS.
- [x] Research on Sidekiq Batches as per Lindsey's suggestion.
- [x] Explore mechanisms to cancel the job if necessary.

## Acceptance Criteria

- [x] A defined strategy is in place to deal with job failures, enabling the process to resume from where it left off.
- [x] A proposed method for dividing table records among a given number of Sidekiq workers is available.
- [x] A clear understanding of enabling automatic key rotation for existing KMS keys in AWS is achieved.
- [x] Insights are gathered on the usage of Sidekiq Batches.
- [x] A mechanism is outlined to cancel the job when needed.

References:

- [Rotating AWS KMS keys](https://docs.aws.amazon.com/kms/latest/developerguide/rotate-keys.html)
- [Sidekiq Batches](https://github.com/mperham/sidekiq/wiki/Batches#overview)

**Comment by holdenhinkle** [comment]
Docs:

- From previous 'research' ticket - https://docs.google.com/document/d/1kJBpyB7IdOxV-tgs2VaqbtHf1nGV96v0OiaNWh4Y02w/edit#
- Solutioning doc -https://docs.google.com/document/d/1cY44u6Jujc8_1c4ae099Epr6KEJhGfDhzDzE3V2EDHU/edit#heading=h.fgre1o8y77bf
