### ISSUE TITLE
FE | Profile | Design System | React RadioButtons Deprecated

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#49468]
## Background

We are currently using the old component on the Notification settings page and will need to update:

> The VA Design System Team has deprecated the RadioButtons React component. We encourage all teams using the RadioButtons React component to upgrade to the va-radio web component. We have changed the ESLint warning to an ESLint error and have removed the documentation about the React RadioButtons component from Storybook.
> On Wednesday, December 7th, we will remove the React RadioButtons component from the component library.

## Tasks
- [x] Conduct Unit tests 
- [x] Run E2E tests covering current code and regression
- [x] Notify PM if this needs to be deployed to Staging behind feature flag
  

## Acceptance Criteria
- [x] Complete all unit testing
- [x] End-to-end tests showing 0 violations
- [x] All axe checks pass
- [x] Notify Product Manager that the change is ready to be validated on Staging
- [x] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [x] Confirm PM has opened a new ticket to deploy changes to Production using feature flag, if needed

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)?
- How can this work be validated?
- What updates need to be made (e.g. product outline, use cases, contact center guide)

## Associated Tickets
- #

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by adamwhitlock1** [comment]
After researching the current Radio Button usage on the Profile I have come to the following conclusions:

We are not currently using the soon to be deprecated RadioButtons React component on the Profile. The only area where a similar input is being used is on the Notification Settings page, but the code is instead using a custom built input component.

For reference, the custom radio button is called [NotificationRadioButtons](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/profile/components/notification-settings/NotificationRadioButtons.jsx)

This ticket can be closed as won't do, and a new ticket should be create to address this custom component in the future and would be considered tech debt, since it is not using any Design System component at it's core and should adhere to that system for overall maintainability.

**Comment by SKasimow** [comment]
Opened #49983 for future work
