### ISSUE TITLE
Design  | Profile | New Edit Sub-task  page | Error States Mocks

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#49464]
## Background

As part of the upcoming changes to the Notification settings/ add mobile # flow, we plan to introduce a new page for editing; this will eventually support other types of editing within the Profile.

As a next step, we'll need to identify the error conditions that may occur on this new page beginning with the changes to the notification settings/add mobile # flow and create mocks in support of this.

The error states include:
- ~user goes directly to URL and is not signed in (falls under Sitewide pattern)~
- user goes directly to URL and is signed in as LOA1
- user goes directly to URL and is signed in as LOA3 with an existing mobile phone # 
- user goes directly to URL and is signed in as LOA3 without an existing mobile phone # 
- save failure
- ~session ends while viewing page (Adam is checking on this one)~
- system down

## Tasks

- [x] Design and document error message state mockups and copy noted above (if needed)
- [x] Ready for review with team, PM and PO

### Acceptance criteria
- [ ] Notify PM when ready for FE
- [ ] Provide links to new sketch files for error messages

## Associated Tickets
- #49459

**Comment by andaleliz** [comment]
@SKasimow and @Samara-Strauss, I've completed this work. Danielle has reviewed and approved the content in the mock-ups.  I _think_ we're holding off on use case documentation for these, but if that's not correct, please go ahead and assign me a ticket for that.

>user goes directly to URL and is signed in as LOA1

This would be the same behavior as any other part of profile, where it would go straight to account security, and only display that part of profile. [Here's a mobile version](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/a/zx0boLr) of that page for reference.

--- 

> user goes directly to URL and is signed in as LOA3 with an existing mobile phone #
> user goes directly to URL and is signed in as LOA3 without an existing mobile phone #

For these two use cases, the behavior would be normal on the page, if the query parameter was present in the URL. If they do have a phone number, it would display in the input field.  This is why we have "add or update" as part of the h1.

- [mobile](https://www.sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d/a/7yv0O82) 
- [desktop](https://www.sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d/a/L0L5AaQ)

---

A use case that wasn't listed in the description is:
- user goes directly to URL **without a query parameter** and is signed in as LOA3

In this case, I think they're showing some intent of wanting to edit by going to the URL. But, we don't know what they're trying to edit since there is no query parameter.  To solve for this, we can present them with a list of the profile sections that could be edited. 

I purposely left off connected apps because that's not something you'd ever edit as part of this sub-task flow.  Although the other sections aren't technically using this today, they do all ahve "edit" buttons associated with them where a person could make a mental connection back to this page.
- [mobile](https://www.sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d/a/yg23exo)
- [desktop](https://www.sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d/a/ZOzGKLZ)

---

>save failure

We have two kinds of save failures in other parts of profile:
- Change can't be saved when user presses submit 
   - [mobile](https://www.sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d/a/9PekD8M) 
   - [desktop](https://www.sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d/a/zxM9l5a)
- Change still can't be saved after repeated attempts. In other parts of profile, we kick them back to read mode and display a message. We don't have a "read mode" in this case, and so I propose an alert on the same page.  I'm not 💯 sure this use case is legit but we have a design for it if so. 
  - [mobile](https://www.sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d/v/Gb2QLv/a/PGPr7kd)
  - [desktop](https://www.sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d/a/Jnw1PO9)

---

> system down
- [mobile](https://www.sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d/v/Gb2QLv/a/g0lp4dx)
- [desktop](sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d/a/4azRmdJ)

**Comment by Samara-Strauss** [comment]
> I think we're holding off on use case documentation for these, but if that's not correct, please go ahead and assign me a ticket for that.

Correct. We are only updating documentation for functionality that is live and in production.

Otherwise, all of the Sketch links are giving me a message that they are private, and I don't have access. Not sure if this is a permissions issue or a public/private link issue.

The system down `desktop` link is giving me a Github 404.

**Comment by andaleliz** [comment]
@Samara-Strauss can you try the links again (including the system down desktop error) please? I didn't realize I needed to update permissions on a per-file basis (thought it was at the team level).  Hopefully it works now.

**Comment by Samara-Strauss** [comment]
Links all working now! Thank you!
