### ISSUE TITLE
Create detailed draft of Guide for the mapping process

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#49465]
## Issue Description
Document the mapping process, drafting the specific steps involved

Should result in an internal guide that a SDT member can follow.

Practical by Design [SB Process tips](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2431746066/Nice+Breakdown+of+SB+process+from+Practical+by+Design)

NNG SB Course [notes](https://docs.google.com/document/d/16UT5GysDO6-4Mx2dXQkVBctLpN5_QkLxTj28Alvd2p0/edit?usp=sharing)

## Tasks
- [x] Shape major steps into a specific [guide](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2436169729/How+To+Service+Blueprint+a+Process+-+the+SDT+way)
- [x] Use [workshop data](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1666623990109/dba477fdf13b9e403ef4e67d39d246c973dd6b29?sender=u4397b715dc3690a417b71483) and research to delineate specific steps within each phase
- [x] Refine w/ team input

## Acceptance Criteria
- [x] Process is documented in an internal guide format.
