### ISSUE TITLE
Schedule recurring Zoom meetings for all CC timeslots

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#49478]
## User Story
As a Governance team member, I want to schedule recurring Zoom meetings for all CC timeslots so that the Zoom information is consistent week to week, meaning no more confusion with who owns the meeting and who has permissions to records, host, screen share, etc.

Assignee: @shiragoodman 
Peer Reviewer: @allison0034 

## Description
There are 7 timeslots each week for Collab Cycle reviews to occur. Instead of setting up a Zoom on demand (as we have been doing since 2020), we will schedule recurring Zoom meetings for each timeslot, so that each week the Zoom information is consistent. This will alleviate issues that we've had in the past such as permission recording and permission to screen share. Also, the Zoom host will no longer necessarily be the meeting host.

The Zoom details for each recurring meeting will be captured in the Zoom information for Collab Cycle meetings guidance.

## Impacted Artifacts
[Zoom information for Collab Cycle meetings](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2454585540/Zoom+information+for+Collab+Cycle+meetings)

## Tasks
- [x] Schedule a recurring Zoom meeting for the following CC timeslots:
   - Monday at 3:30pm ET
   - Tuesday at 11:00am ET
   - Tuesday at 11:30am ET
   - Thursday at 1:30pm ET
   - Thursday at 2:00pm ET
   - Friday at 11:30am ET
   - Friday at 2:00pm ET
- [x] Ensure @allison0034 and @naomimarcussen are added as alternative hosts for all meetings
- [x] Recurring meetings have an end date. Choose the latest possible date.
- [x] Title each meeting "Collaboration Cycle meeting - day of the week, time of the day"
- [x] Ensure Allow participants to join anytime is checked (test this feature vs. Allow participants to join before host)
- [x] Capture all Zoom meeting info in the _Zoom information for Collab Cycle meetings_ guidance

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Recurring Zoom meetings exist for all Collab Cycle timeslots
- [x] Governance team has access to all recurring Zoom meeting information
- [x] Alternative hosts are set up for all recurring Zoom meetings

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@allison0034 this is ready for your review. [Zoom information for Collab Cycle meetings](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2454585540/Zoom+information+for+Collab+Cycle+meetings)

**Comment by shiragoodman** [comment]
FYI none of these Zoom events should be used until January 2023

**Comment by allison0034** [comment]
Looks good, thank you!

**Comment by shiragoodman** [comment]
@allison0034 I added H3s to the doc per your comments in standup today. What do you think?

**Comment by allison0034** [comment]
Looks good!

**Comment by shiragoodman** [comment]
awesome. Closing this.
