### ISSUE TITLE
Remove use of `set-output` in GitHub Actions

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#49475]
## Description
`set-output` is set to deprecate May 31, 2023. This message is being seen in the workflows that use it:

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

That github link ^^ explains the fix.

## Background/context 
`set-output` is used widely across the org.

## Technical notes
See PRs linked to this issue for examples.

---
## Tasks
- [x] content-build/script/github-actions/check-broken-links-blocks.js
- [x] content-build/script/github-actions/check-broken-links.js
- [x] devops/scripts/pst-access-management/check_roster.rb
- [x] va.gov-team/.github/workflows/application-onboarding-or-promotion-automation.yml
- [x] va.gov-team/.github/workflows/ops-application-onboarding-or-promotion-form.yml
- [x] vsp-infra-argocd-events/.github/workflows/mirror-images.yaml
- [x] vsp-infra-argocd-events/.github/workflows/update-manifests.yaml
- [x] vsp-infra-argocd/.github/workflows/application-onboarding-helm-template.yaml
- [x] vsp-infra-argocd/.github/workflows/capture-onboarding-or-promotion-task.yaml
- [x] vsp-infra-argocd/.github/workflows/mirror-images.yaml
- [x] vsp-infra-argo-notifications-controller/.github/workflows/mirror-images.yaml
- [x] vsp-infra-argo-rollouts/.github/workflows/mirror-images.yaml
- [x] vsp-infra-argo-workflows-server/.github/workflows/mirror-images.yaml
- [x] vsp-infra-aws-node-termination-handler/.github/workflows/mirror-images.yaml
- [x] vsp-infra-aws-node-termination-handler/.github/workflows/update-manifests.yaml
- [x] vsp-infra-calico/.github/workflows/mirror-images.yaml
- [x] vsp-infra-calico/.github/workflows/update-manifests.yaml
- [x] vsp-infra-goldilocks/.github/workflows/mirror-images.yaml
- [x] vsp-infra-goldilocks/.github/workflows/update-manifests.yaml
- [x] vsp-infra-helm/.github/workflows/mirror-images.yml
- [x] vsp-infra-k8s-datadog-agent/.github/workflows/mirror-images.yaml
- [x] vsp-infra-k8s-datadog-agent/.github/workflows/update-manifests.yaml
- [x] vsp-infra-k8s-datadog-private-location/.github/workflows/mirror-images.yaml
- [x] vsp-infra-k8s-datadog-private-location/.github/workflows/update-manifests.yaml
- [x] vsp-infra-k8s-external-dns/.github/workflows/mirror-images.yaml
- [x] vsp-infra-k8s-external-dns/.github/workflows/update-manifests.yaml
- [x] vsp-infra-keda/.github/workflows/mirror-images.yaml
- [x] vsp-infra-kubernetes-autoscaler/.github/workflows/mirror-images.yaml
- [x] vsp-infra-kubernetes-autoscaler/.github/workflows/update-manifests.yaml
- [x] vsp-infra-loki-canary/.github/workflows/ci.yml
- [x] vsp-infra-loki-canary/.github/workflows/mirror-images.yaml
- [x] vsp-infra-traefik/.github/workflows/ci-cd.yaml
- [x] vsp-infra-traefik/.github/workflows/mirror-images.yaml
- [x] vsp-infra-kubernetes-metrics-server/.github/workflows/mirror-images.yaml
- [x] vsp-infra-kubernetes-metrics-server/.github/workflows/update-manifests.yaml

## Acceptance Criteria 
- [x] All tasks are checked off and linked to this issue.

**Comment by oseasmoran73** [comment]
Might make sense to look under the hood of app-manifest & argocd as well. I am not sure where else we use GHA, but will need bit of house cleaning 🕵️

**Comment by laineymajor** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Tech-Team-1-633af4074573d06c3cda142a/issues/department-of-veterans-affairs/va.gov-team/49475?planning-poker) with Zenhub @rmtolmach

**Comment by LindseySaari** [comment]
Rebecca's priority is the deprecation ticket and will focus on this next

**Comment by rmtolmach** [comment]
Today I worked on removing `set-output` from `scripts/pst-access-management/check_roster.rb` in the devops repo. Since it's a ruby file and not yaml, it's complicated. I've been testing by running the [workflow_dispatch](https://github.com/department-of-veterans-affairs/devops/actions/workflows/pst-amt-roster-check.yml) on my branch (`remove_set_output`) using a fake SOCKS request (https://github.com/department-of-veterans-affairs/va.gov-team/issues/54043).

**Comment by laineymajor** [comment]
Rebecca is working on the final repo. Then this will be complete.

**Comment by rmtolmach** [comment]
Devops PR: 
* https://github.com/department-of-veterans-affairs/devops/pull/12593
argocd PR:
* https://github.com/department-of-veterans-affairs/vsp-infra-argocd/pull/189
vagov-team repo
* https://github.com/department-of-veterans-affairs/va.gov-team/pull/54083

**Comment by hgbarreto** [comment]
The following seem to have already been addressed by this [PR](https://github.com/department-of-veterans-affairs/content-build/pull/1476)
content-build/script/github-actions/check-broken-links-blocks.js
content-build/script/github-actions/check-broken-links.js

**Comment by rmtolmach** [comment]
Nice work Kyle and Hector (and me lol). Closing!
