### ISSUE TITLE
Review new page: Accessing and Utilizing Contact Center Data

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#49470]
Per Office Hours on Nov 8, 2022

**Tasks:**

- [x] Review page created and provided by the Contact Center team: https://vfs.atlassian.net/wiki/spaces/PWD/pages/2419359870/Accessing+and+Utilizing+Contact+Center+Data

- [x] Document any recommendations, changes and/or question for content editor (Ian)

- [x] Update the document according to recommendations and sign off with content editor

- [x] Place new document in according to where in the IA agreed upon, ready to deploy

**Comment by ianMcCullough-ob** [comment]
I wonder if we can add a 4th page under “[Reporting & Insights](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/reporting-insights)” for Contact Center Data. We also have two how-to pages ([How to use Contact Center data](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/how-to-use-contact-center-data-in-domo) in DOMO and [How to use Medallia Data in DOMO](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/how-to-use-medallia-data-in-domo)) that live under “Platform data sources,” perhaps those can be moved to live under the Contact Center Data section.

I also think the "How to use Contact Center data in DOMO" should be renamed to either "How to use MyVA411 data in DOMO" or "How to use Call Center data in DOMO" to avoid confusion.

**Comment by taylojill** [comment]
Hello @ianMcCullough-ob Sounds good! We will make the following changes. Let me know if this is accurate.
cc @vbellissimo 

- Add a 4th page under "Reporting & Insights". The page title will be "Accessing and Utilizing Contact Center Data"
- Rename the "How to use Contact Center data in DOMO" page to "How to use MyVA411 data in DOMO"
- Move the renamed page and the "How to use Medallia Data in DOMO" page under "Accessing and Utilizing Contact Center Data" (as child pages)
- Correct hyperlinks as required.

**Comment by taylojill** [comment]
11/14/22 - Follow up message sent to Ian via Slack.

**Comment by ianMcCullough-ob** [comment]
Hello @taylojill, thanks for the follow up. These changes look great!

**Comment by taylojill** [comment]
Thanks @ianMcCullough-ob I'll start working on the changes, and hope to have them published by COB Thursday 11/17.
cc @vbellissimo

**Comment by taylojill** [comment]
11/16/22 - New/updated pages published today. Ticket closed.
cc @vbellissimo
