### ISSUE TITLE
Modify Governance Team onboarding guidance

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#49484]
## User Story
As a new team member, I want to make sure I'm included in the On Support schedule and familiar with the guidance so that I can help support Governance team support requests.

Assignee: @CherylEvans 
Peer Reviewer: @sterkenburgsara 

## Description
Now that we are introducing an On support schedule, any new team members that join Governance team will need to be added to the schedule and will need to be made familiar with the guidance. The purpose of this ticket is to update our Onboarding guidance to introduce the On Support schedule and add tasks for the new team member to complete to ensure they're able to respond to support requests.

## Impacted Artifacts
Platform Governance - [Onboarding](https://vfs.atlassian.net/wiki/spaces/PPST/pages/1953169694/Onboarding)

## Tasks
- [x] Add a new On Support Section to the How We Work section of the Onboarding doc
- [x] Create a checklist of items the new person must complete (or request to be completed) in order to support On Support

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The new Governance team member is familiar with our On Support guidance and has a checklist of items to complete

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
@briandeconinck Hi Brian.  Happy New Year!  I have incorporated Shira's recommendations, and am ready for you to review my [draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2454093924/On-Support+guide) page.  I have resolved Shira's comments, but would ask that you go back and look at her comments to ensure that I made the changes that she requested.  Thanks again Brian!  Please reach out if you have any questions or concerns.

**Comment by CherylEvans** [comment]
@shiragoodman [Draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/1953169694/Onboarding#On-Support) created.

**Comment by CherylEvans** [comment]
@sterkenburgsara Hi Sara.  Would you mind giving [this](https://vfs.atlassian.net/wiki/spaces/PPST/pages/1953169694/Onboarding) an initial review before I tag Shira to review?  There weren't many specific tasks to complete, but I think this is a good start!  Thank you!!

**Comment by sterkenburgsara** [comment]
@CherylEvans The only minor edit I see is unrelated to what you were working on. There is a Confluence section at the bottom of the page and under the To-Do list, it specifically says you will get a Confluence account notification via Nancy Smith to your Oddball email account. I think we should remove "Oddball" there and keep it generic. 

As we continue to add new things to this document, my general feedback is that it is pretty overwhelming and at some point we could discuss breaking it into "Onboarding Phase 1" and "Onboarding Phase 2" or something, but I think all the on-support content is there for now and it looks good!

**Comment by shiragoodman** [comment]
thanks for catching that Sara! In addition to removing Oddball, we also want to update Nancy Smith to Andrea Hewitt as she is the new Program Director

**Comment by CherylEvans** [comment]
@shiragoodman Do you mind taking a look at my [draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/1953169694/Onboarding#On-Support) as well?  I am unsure whether or not to include some of the tasks on the To Do checklist.  I also think that a new person should feel well-grounded and comfortable in their role before they take on the On-Support duties.  Thoughts?

**Comment by CherylEvans** [comment]
@shiragoodman @sterkenburgsara I made Sara's recommended changes. :-)

**Comment by shiragoodman** [comment]
@CherylEvans I agree. I don't think this is something that should happen right away, but they should be introduced to it.

I reviewed and added comments. Let me know if you have any questions.

Similar to Sara, I also added some comments to the Onboarding doc that were outside the scope of this ticket. Can you please take a look at those and address? ty!

**Comment by CherylEvans** [comment]
@shiragoodman I have incorporated all of your recommendations, including the out-of-scope ones.  Thank you for your input!

**Comment by sterkenburgsara** [comment]
@CherylEvans looks good to me! Peer review complete.

**Comment by CherylEvans** [comment]
@shiragoodman @briandeconinck Woo-Hoo!  Awesome.  Thank you both for your guidance and patience.  :-)
