### ISSUE TITLE
Revise Moderator Responsibility docs for DI, MPR and SR

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#49480]
## User Story
As a Governance team member, I want to be able to follow the guidance for completing scheduling of the Design Intent, Midpoint Review and Staging Review using the new default Zoom meeting information.

Assignee: @briandeconinck 
Peer Reviewer: @CherylEvans 

## Description
In ticket #49478 we scheduled recurring Zoom meetings to be used in Collab Cycle touchpoint meetings for the 2023 year. Now we need to update our moderator responsibility docs to instruct team members to use the pre-scheduled Zoom meeting information opposed to adding their own to the meeting invite.

Note: The pre-scheduled Zoom meetings begin in January 2023 and end December 15, 2023. Any touchpoint meetings schedule prior to January 2023 should continue using the former process.

## Impacted Artifacts
[Design Intent - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Moderator+Responsibilities)
[Midpoint Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Moderator+Responsibilities)
[Staging Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review+-+Moderator+Responsibilities)
[Zoom information for Collab Cycle meetings](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2454585540/Zoom+information+for+Collab+Cycle+meetings)

## Tasks
- [x] Update the guidance for DI, MPR and SR to include referencing the Zoom information for Collab Cycle meetings doc 

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] All Collab Cycle meetings beginning in January 2023 are scheduled with the pre-scheduled Zoom meeting info
- [x] Governance team guidance is updated to reflect the new process

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@briandeconinck what is the status of this? Have you begun to make changes?

**Comment by briandeconinck** [comment]
@CherylEvans Ready for review. Step 2 of the "Schedule" section for each touchpoint has been updated.

- [Design Intent - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Moderator+Responsibilities)
- [Midpoint Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Moderator+Responsibilities)
- [Staging Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review+-+Moderator+Responsibilities)

I kept the instructions short and sweet -- but let me know if anything is unclear.

**Comment by CherylEvans** [comment]
@briandeconinck I like what you wrote, and I had no difficulty following the instructions. :-). I did remove the word "of" as I felt it wasn't needed.  Looks great!

**Comment by briandeconinck** [comment]
@CherylEvans Per the [Slack discussion](https://dsva.slack.com/archives/GNF5GSD9N/p1672843750911059?thread_ts=1672764145.551459&cid=GNF5GSD9N) with @shiragoodman, I have updated the instructions for sharing the Zoom recordings. The only edits were in the post-meeting section, step 3 for each touchpoint.

- [Design Intent - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Moderator+Responsibilities)
- [Midpoint Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Moderator+Responsibilities)
- [Staging Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review+-+Moderator+Responsibilities)

Let me know if that looks good to you and I can close out the ticket!

**Comment by CherylEvans** [comment]
@briandeconinck I just reviewed and only have one recommendation for changes to "Post meeting", step 2 in all documents.
I recommend removing the word "currently," as it isn't needed and is clunky.  Other than that, it looks great!!

**Comment by briandeconinck** [comment]
Done! Closing this out.
