### ISSUE TITLE
[FE] Deprecate day-of demographics flag

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#49485]
## Background

We [don't anticipate needing to turn off the demographics questions for day-of check-in](https://dsva.slack.com/archives/C022AC2STBM/p1667941451327819?thread_ts=1667939197.898429&cid=C022AC2STBM), so we should remove the flag and any associated logic. 
  
## Tasks
- [ ] [FE] remove feature flag and associated logic/tests
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
closing ticket since there is nothing to validate for this ticket.
