### ISSUE TITLE
[DESIGN][DISCOVERY]  File upload component updates

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#49495]
## Issue Description
Discovery work to see what content and other changes are needed to align both the 10-10EZ (Discharge papers) and the 10-10CG (Representative Docs) to the latest design system guidance. 

Addressing "File" vs "Document" language

https://design.va.gov/components/form/file-input

---
## Tasks
- [x] Review the Design System for file upload language/content
- [x] Review with Content team on current content on the forms
- [x] Determine what changes may be needed for each form

## Acceptance Criteria
- Any content changes needed will be determined and additional tickets can be created
---

**Comment by jessicastump** [comment]
[Content running ticket link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25350#issuecomment-1342982260) - met with Danielle during content hours, sent her examples and will circle back during next content session.

**Comment by eflaherty** [comment]
sorry, hit the close button as I'm getting familiar in Zenhub. Reopened :)

**Comment by jessicastump** [comment]
Looking through design system guidance -- [component](https://design.va.gov/components/form/file-input), [pattern](https://design.va.gov/patterns/ask-users-for/files) and in [Storybook](https://design.va.gov/storybook/?path=/docs/components-va-file-input--default) -- we should be consistent and use language "Upload file" for button action. The button label does change to "Delete file" after upload. Additionally, found [this ticket in the Icebox around inconsistent content](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27415) and also updated content bullets around uploading a file. 

[EZ Sketch File](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/8A6DDE5C-6153-4ABC-8D0F-3037EF353475/canvas) (Step 3 Military Information > Discharge Papers)
[CG Sketch File](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/p/FCFAB0B2-1554-4AB8-B49F-72AC84FF2C58/canvas) (Step 4 Representative Documents > Upload Docs) 

Next steps: Review with content and team determine if changes are needed before opening FE ticket

**Comment by jessicastump** [comment]
@hdjustice - I left a comment in this old ticket here [#27415](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27415) on what next steps are for final content review, didn't want to open another content ticket if it is not necessary since there are already two. 
Would like to get this resolved :) and on to development.

**Comment by jessicastump** [comment]
Discovery phase complete. Discussed during bi-weekly content call to close the old style guide ticket and this discovery one. Content has a ticket opened on their side and once we have approved content, will adjust Sketch files and open FE ticket. 

[Old content style guide ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27415) 

We will work off the [content ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60053 opened and will add comments / changes to the Sketch file as needed.
Sketch file links:
CG: [what is live today](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/8y8LWYa), a [draft](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/p/FCFAB0B2-1554-4AB8-B49F-72AC84FF2C58/canvas)
EZ: [what is live today](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/m1VE9rV#Version) , a [draft](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/8A6DDE5C-6153-4ABC-8D0F-3037EF353475/canvas#Version)
