### ISSUE TITLE
GA4:  Gap Analysis - Web & Form vs Custom VFS Events 

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#49502]
## Issue Description

Review web components and form library vs VFS custom components to determine where custom components could be replaced by "standard".  If they can the team should move to those, if they do not provide what they need then custom code for them to implement will be provided.  Goal is to minimize the amount of custom work needed in GA4 if the standard product offering can satisfy VFS team needs.

---
## Tasks
- [ ] Review [all events](https://docs.google.com/spreadsheets/d/1R0I5_dglyXEXYl0uESUTsSfsyIcBAk2lr7DVrRsx3qY/edit?pli=1#gid=343262001) and identify high use custom events not using web components
- [ ] Meet with VFS teams to review
- [ ] Determine if a web component exists to replace custom event and if so replace
- [ ] Define list of custom events to be migrated 

## Acceptance Criteria
- [ ] List of custom events to be migrated has been completed, reviewed and approved by VFS teams

**Comment by johnny-jesensky-adhoc** [comment]
Closing this ticket out, as was creating factoring an older GA4 transition workflow. Will be tracking this work through other tickets.

FYI @jestutt
