### ISSUE TITLE
GA4: Discovery/Audit related to BigQuery Cost During Migration Phase

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#49506]
### Description
With GA4 migration work impacting BigQuery, the primary goal of this ticket is to determine whether or not they'll be an increase in BQ costs during the migration phase. 

The goal of this ticket is to create a hypothesis for if we will see a spike in BQ costs, and if possible, by how much.

### Tasks
- [x] Review historical cost usage, and general options for more closely measuring/managing costs.
- [x] Determine a hypothesis for cost impact during GA migration (we suspect it will go up by X%...go down by Y%, etc.)
- [x] Communicate hypothesis findings with Dave, Erika, + Andrea, and provide recommendations for Cost Controls to manage this appropriately.

### Acceptance Criteria
- [x] Findings from review/spike have been documented in this ticket, in **Spike Findings** section below
- [x] Findings/hypothesis on cost impact have been shared with Dave, Erika, and Andrea.
- [x] Next steps (if any) have been identified, and have been created as cards in the _**Backlog**_.
---
### Spike Findings
Johnny and Phil connected on _Thursday, February 8th_, to talk about the predicted impact that the GA4 migration would have on BigQuery costs. We have been operating under an $11,000/month budget, and outlined if we would see an uptick in cost, and if so, by approximately how much. 

We've documented our findings below:

- **Predicted Cost Impact:** While the GA4 migration process will involve some ETL work in BigQuery, the number of _bytes process_, (which determines the cost), will be relatively small compared to our budget. Assuming that the Mobile Team's usage goes down as expected, we wouldn't expect to approach the budget threshold for any of these months. 
- Based on our understanding of what needs to be done, Phil estimates that any BQ jobs that would need to be run would be closer to 1gb. For reference, the jobs we were seeing from the Mobile Team were as high as >2 TB, significantly higher than these jobs.
- Ultimately, there would be an increase in the number of manual jobs run than there would be otherwise, but the impact would likely not create a risk for exceeding our budget, (again, assuming the Mobile Team's usage would drop).
- **Time Range of Potential BQ Cost Increase:** March - June 30th
- **Controls in Place** Any new BigQuery jobs associated with the GA4 migration will be performed _manually_ by Phil, as opposed to having something that will be scheduled on an automated, or recurring schedule. This will give us greater control and predictability of costs, as we will be able to see the impact of a query before we run it, allowing us to optimize.

**Comment by michelle-dooley** [comment]
Hey @dorseypa1 I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [Zenhub](https://www.zenhub.com)_

**Comment by johnny-jesensky-adhoc** [comment]
@dorseypa1, I summarized the results of our conversation around predicted BigQuery cost changes during the migration phase (now - June 30th). See the _Spike Findings_ section in the ticket. 

**Can you take a look and let me know if I've missed anything?** Other than sharing our findings with Dave, I don't think there are any immediate next steps we'll need to take, or follow-up cards for our backlog.

**Comment by johnny-jesensky-adhoc** [comment]
Shared findings with Dave on this in our PO sync on 2/13. No further action or tickets needed for this one - moving this to _Done_.

FYI @dorseypa1
