### ISSUE TITLE
[EVSS to Lighthouse] Map attributes

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#49508]
## Background
We need to map attributes ahead of writing FE code.

## Tasks
- [x] Map attributes

## Acceptance Criteria
- [x] Claims attributes for vets-api features and documents service mapped
- [x] Lighthouse reviews and approves mapping documentation
- [ ] Mobile reviews and approves mapping documentation

**Comment by kjduensing** [comment]
From Jerek: [Mobile_attributes_map.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/10134076/Mobile_attributes_map.pdf)
