### ISSUE TITLE
[Design] My VA Audit UX Improvements: Explore Designs for Incorporating multiple open Claims

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#49509]
## Background
As detailed in this [slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1668004758040209), users may have multiple open claims at one time and currently we only show them their most recent one the My VA dashboard. We want to explore design options for showing users all of their open claims.

## Tasks
- [ ] Create design options for open claims
- [ ] Review designs with team
- [ ] PM to create any follow up FE tickets if needed

## Acceptance Criteria
- [ ] Design options for multiple open claims are reviewed

**Comment by ajakabcin** [comment]
@aagosto90 moving this back to backlog since we have the notification center discovery work for you this sprint - if there's bandwidth we can pull it back in 

cc @BerniXiongA6
