### ISSUE TITLE
Design Considerations for Structuring Language Toggle, Progress Bar & Navigation Links

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#49523]
## Tasks

- [ ] Explore if order of language toggle, back navigation, progress bar and h1 need to be reordered. Identify and document issues with the current order.  
- [ ] Create wireframe for new solution. 
- [ ] Share solution with UX team. 
- [ ] Share solution with product and CIE team. 
- [ ] If desired, discuss with platform design team. E.g., Carol, Matt, etc. 
- [ ] [Create experimental design system request ticket ](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update#new-component-or-pattern)

## AC

- [ ] Wireframe is added to abstract
- [ ] Share solution with UX team
- [ ] Share solution with product and CIE team. 
- [ ] Submit experimental design system request ticket to platform design team

**Comment by loripusey** [comment]
I'm taking this out of the simplified header footer epic and putting in ideas; if we want to move forward later we can
