### ISSUE TITLE
Update NADL rate-HOLD TO PUBLISH UNTIL 11/21

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#49525]
## Issue Description
We need to update the rate on our [Native American Direct Loan](https://www.va.gov/housing-assistance/home-loans/loan-types/native-american-direct-loan/) page. This number should change to **6.75%**

We need to hold to publish until 11/21.

## Tasks
- [x] Update page (Aliyah)
- [x] Copyedit (Megan)
- [x] Publish (Megan)
- [x] Notify stakeholder that changes are live (Randi)

## Acceptance Criteria
- [x] New rate is live on the site

**Comment by aliyahblackmore** [comment]
Hi @megzehn this is ready to publish on 11/21! 
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=758

**Comment by RLHecht** [comment]
Just published this. I'll close this and let Raleigh know once it's live.

**Comment by RLHecht** [comment]
This is now live. Closing ticket.
