### ISSUE TITLE
[PM] My VA Audit UX improvements: Prep for analytics request

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#49535]
## Background
In preparation to submit our analytics request for My VA audit improvements we need to review our existing analytics and create an inventory of what we have tracked in the current implementation/existing tags to determine what new tags we need to add and which ones we need to rename to correctly reflect what they're tracking.

## Tasks
- [x] Review GA tags to see what we have in place
- [x] Document which tags need to be renamed
- [x] Document which additional tags we need
- [x] Review with Samara

## Acceptance Criteria
- [x] Inventory and plan for analytics tagging is documented and shared with PO
