### ISSUE TITLE
[PM] My VA Audit UX improvements: test case documentation

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#49534]
## Background
We need to get all test cases documented in Github for the audit improvements

## Tasks
- [x] Document test cases in GH
- [x] Designer to add sketch files for use cases
- [x] Create test user summary table (if time permits)
- [x] Review with APM/Design

## Acceptance Criteria
- [x] Test cases are documented in github with corresponding test users and sketch files for visual check
- [x] (Stretch) User summary table is in github
