### ISSUE TITLE
[BE] Remove LoROTA api_key from vets-api config

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#49533]
## Background

In order to avoid confusion/doubt during security audits, we should remove the LoROTA dev [api_key stored in `config/settings.yml`](https://github.com/department-of-veterans-affairs/vets-api/blob/1c27aaf8687eab1b488997848c55b320f3da3305/config/settings.yml#L1348) and replace with something like `fake_key`.

https://dsva.slack.com/archives/C01CJV0L9PS/p1668086994665709 for more background.

## Tasks
- [ ] [BE] lorota `api_key` is not stored in VC.

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by acrollet** [comment]
@randomsync @kanchanasuriya should we also consider parameterizing the keys for lower envs in the devops repo?
