### ISSUE TITLE
Supplemental Claims | Submit VA Medical Evidence

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#49536]
## Value Statement
**_As a_** Veteran
**_I want to_** submit VA medical evidence
**_So that_** I can have it reviewed in support of my claim. 

---
## Background Context

The evidence flow for VA medical evidence was previously using an all-in-one page list loop pattern. We have a new one (sorta) question per page pattern to reduce the complexity & cognitive load of the page.

## Acceptance Criteria
- [x] User must select Yes or No when asked if they want the VA to request their medical records on their behalf.
- [x] If the user selects No, they proceed to the private evidence section.
- [x] User must enter at least one location before pressing Continue
- [x] For each location, the user must enter the VA facility, issues treated, and first and last treatment date before pressing Continue
- [x] The add another location action link will allow adding additional locations
- [x] Using the back button will either navigate through all added locations, or go back to the 5103 notice page
- [x] Clicking the back button, add location link, or Continue on an incomplete additional location page (not the first one) will trigger a modal to ask if they want the location saved
- [x] After adding several locations and navigating back to the 5103 page, using continue will navigate through each location page in sequence
- [ ] Unit tests complete (90% coverage)
- [ ] E2E tests complete
- [ ] Accessibility testing complete
- [ ] Reviewed and approved by product and/or design

## Designs and Build Notes
[DESIGN](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/v/Mdd1Wz/p/274ABD98-987B-4C4D-BB93-8FCE3DD6C3DE/canvas?posX=-943.4193115234375&posY=-487.5298156738281&zoom=0.49364808201789856)

## Out of scope
- Connecting to BRD endpoint

## Open questions
- Lighthouse: Is the Facilities API endpoint exhaustive? Should the user have the option to type in the location?

## Tasks
- [ ] Add VA evidence yes/no question page
- [ ] Add custom add location page with custom form navigation button behavior 
- [ ] Add unit tests
- [ ] Add e2e tests
- [ ] Accessibility testing of new pages

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by saderagsdale** [comment]
@Mottie Is this ready to review in staging?

**Comment by Mottie** [comment]
Not yet, the PR has not yet been merged. It's awaiting review and it's a lot of code to look at.

**Comment by Mottie** [comment]
Updated story points because writing unit and end-to-end tests took 4 days to complete.

**Comment by Mottie** [comment]
Merged and available for [testing in staging](https://staging.va.gov/decision-reviews/supplemental-claim/file-supplemental-claim-form-20-0995) - log in with one of the decision review users (I've been using 233 Cara).

**Comment by eileen-coforma** [comment]
Huddled with @Mottie on removing the modal that pops up for continue for the first location (va-medical-records?index=0).
Reasoning: Modal exists to remind the veteran that they have an incomplete location entry, and gives them an option to remove it (to handle additional locations added by mistake). It does not make sense to give the option to clear a location entry, on the first and only location.

@saderagsdale Acceptance criteria says _User must select Yes or No when asked if they want the VA to request their medical records on their behalf._ but the question is not required. I believe the initial thought process is that since a veteran does not have to choose to add VA medical records, they can continue without answering the question, which is equivalent to answering _No_. Is there any other reason this acceptance criteria should be kept, or can we remove it?

**Comment by eileen-coforma** [comment]
There's a styling issue with the field legend for the radio buttons due to restrictions within the design system.
Since CSS styling is currently not allowed within the legend, the form's question _Would you like us to request your VA medical records for you_ becomes less legible and skimmable, especially if the veteran answers _No_ and immediately moves to Private Medical Evidence, where the question looks almost exactly the same.

@Mottie [opened a PR that'll allow CSS styling of the va-radio](https://github.com/department-of-veterans-affairs/component-library/pull/582) to hopefully let us match the visual styles of an H3.

**Comment by saderagsdale** [comment]
@eileen-coforma My only pause is that when this is shown in the evidence summary section it will appear as blank? I would think it makes more sense for the Veteran to acknowledge whether or not they want this rather than leave it to chance.

**Comment by eileen-coforma** [comment]
@saderagsdale We discussed this, and agreed that yes / no will be required for the user to continue
@Mottie Let us know when this change is done
Thanks!

**Comment by eileen-coforma** [comment]
@Mottie The only thing left on this AC is to make the yes/no question required.

I noticed that the progress name for this section is wrong. It's supposed to be 'Step 3 of 4: New and relevant evidence'. Should we open another ticket for copy review, since there are also copy changes for Step 1 and 2? 'Step 1 of 4: Veteran information' (sentence-case) 'Step 2 of 4: Issues for review'?

**Comment by eileen-coforma** [comment]
Everything looks good for this section.

**Comment by sortizsh** [comment]
@saderagsdale does this look ok to you to close?
