### ISSUE TITLE
Supplemental Claims | Submit Private Medical Evidence

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#49539]
## Value Statement
**_As a_** Veteran
**_I want to_** submit private medical evidence
**_So that_** I can have it reviewed in support of my claim. 

---
## Background Context

The evidence flow for private medical evidence was previously using an all-in-one page list loop pattern. We have a new one (sorta) question per page pattern to reduce the complexity & cognitive load of the page.

## Acceptance Criteria
- [x] User must select Yes or No when asked if they want the VA to request their medical records on their behalf.
- [x] User may authorize the VA to collect private medical records on their behalf. 
- [x] If user does not authorize VA to collect private medical records they will get an warning that redirects them to upload evidence.
- [x] User must enter at least one location before pressing Continue
- [x] For each location, the user must enter the VA facility, issues treated, and first and last treatment date before pressing Continue
- [x] Clicking the back button, add location link, or Continue on an incomplete additional location page (not the first one) will trigger a modal to ask if they want the location saved
- [x] User may limit the type of information the VA collects. 
- [ ] Unit tests complete (90% coverage)
- [ ] E2E tests complete
- [ ] Accessibility testing complete
- [ ] Reviewed and approved by product and/or design

## Designs and Build Notes
[DESIGN](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/v/Mdd1Wz/p/274ABD98-987B-4C4D-BB93-8FCE3DD6C3DE/canvas?posX=-3491.79345703125&posY=-467.2724304199219&zoom=0.49364808201789856)
[CONTENT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/sourceofcontenttruth.md#step-3-of-4-new-and-relevant-evidence-3)

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] Add lead-in question page
- [ ] Add lead-in question page unit test
- [ ] Update mock data with lead-in question values
- [ ] Check lead-in page passing e2e tests
- [ ] Add HIPAA question page
- [ ] Add HIPAA question page unit test
- [ ] Update mock data with HIPAA question values
- [ ] Add custom private records list-loop page
- [ ] Add limit consent page
- [ ] Update unit tests for all pages
- [ ] Check passing e2e tests for all pages
- [ ] Accessibility testing completed for all pages

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by thehastingsp** [comment]
@saderagsdale user won't submit in this section of the flow - that is a distinct step.

**Comment by eileen-coforma** [comment]
For the 'Private limit consent' page, we removed the checkbox and consolidated the copy as directions for the text area. We also removed the character limit. New copy has been approved. Design has been updated.

**Comment by saderagsdale** [comment]
@Mottie Reassigned to eng to work on this AC: _If user does not authorize VA to collect private medical records they will get an error that redirects them to upload evidence._

**Comment by Mottie** [comment]
Required tags, authorization warning alert visibility, and limiting consent changes in place. Another PR was just opened with more content updates.

**Comment by eileen-coforma** [comment]
Did a copy and functionality check. Everything looks good to me.
