### ISSUE TITLE
Supplemental Claims | Error Handling 

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#49541]
## Value Statement
**_As a_** Veteran
**_I want to_** understand how to correct errors
**_So that_** I can quickly submit my claim. 

---
## Background Context
Catch all for sections of the form that have already been built. Error handling will be included in future user stories. 

## Acceptance Criteria
- [ ] Inline errors do not include the word "please"
- [ ] Form errors appear with correct copy, style, and placement

## Designs and Build Notes
- Error handling for PDF upload errors (be sure we help them recover) [DESIGN](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/a/ELDLeDR)
- Error handling for not adding an issue [DESIGN](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/a/l1mq4bo)
- Error handling for not adding any evidence [DESIGN](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/a/nR1OPvz)
- Error handling for not authorizing release of medical records [DESIGN](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/a/nR1OPvz)
- [Inline Errors: Content Source of Truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/sourceofcontenttruth.md#error-messaging)

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [x] Write copy [Content Source of Truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/sourceofcontenttruth.md#error-messaging)
- [x] Review copy
- [x] Add error messaging to design files

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by saderagsdale** [comment]
@thehastingsp @eileen-coforma added a placeholder for error messages that cover anything we've already built for Supp claims. feel free to drop design notes and context here.

**Comment by eileen-coforma** [comment]
@saderagsdale I reviewed this with @thehastingsp and this covers the errors we haven't addressed yet. 
Everything else should be able to be treated as inline error messages.

**Comment by saderagsdale** [comment]
@eileen-coforma yep, that aligns with what we previously chatted about. Can you let me know when the content for the error messages is ready and linked to the ticket?

**Comment by eileen-coforma** [comment]
@saderagsdale submitted a ticket to content team for review, as shown linked above. Will be talking to Beth this week.

**Comment by saderagsdale** [comment]
@Mottie Can you let me know if you have any questions about the context/scope of this ticket?

**Comment by Mottie** [comment]
No questions. Thanks!
