### ISSUE TITLE
DDL: Write Cypress tests

### ISSUE THREAD

**Issue by jaredcunha** [department-of-veterans-affairs/va.gov-team#49542]
## Value Statement

**_As a_** front end developer
**_We want to_** make sure that all the DDL code has e2e testing coverage
**_So that_** we can ensure we're releasing a quality product

## Background Context

DDL is getting closer to release, we need to ensure all important flows have e2e test coverage, including keyboard-only testing

## Tasks
- [x] Write all e2e tests for DDL

## Definition of done

- [x] All tasks complete
- [x] All tests passing

**Comment by sortizsh** [comment]
relates to https://github.com/department-of-veterans-affairs/va.gov-team/issues/49849
