### ISSUE TITLE
Supplemental Claims | Submit supporting evidence

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#49540]
## Value Statement
**_As a_** Veteran
**_I want to_** submit supporting evidence
**_So that_** I can have it reviewed in support of my claim. 

---
## Background Context
- Add here

## Acceptance Criteria
- [ ] User may upload multiple documents.
- [ ] User must upload files that meet size and type criteria. 
- [ ] User must select the document type before selecting Continue.
- [ ] Unit tests complete (90% coverage)
- [ ] E2E tests complete
- [ ] Accessibility testing complete
- [ ] Reviewed and approved by product and/or design

## Designs and Build Notes
[DESIGN](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/v/Mdd1Wz/p/274ABD98-987B-4C4D-BB93-8FCE3DD6C3DE/canvas?posX=-6177.91748046875&posY=-562.4820556640625&zoom=0.49364808201789856)

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by saderagsdale** [comment]
@saderagsdale Add BE work from #49231

**Comment by eileen-coforma** [comment]
@rocio-desantiago (cc @jaredcunha for visibility, since you're helping)
We had to make some copy changes, which results in a slight design change to the this page. We're removing a line of copy from the top of the page, and moving the "required" tag to the header. Design file has been updated with the change.

**Comment by saderagsdale** [comment]
@Mottie Looks good on my end. @eileen-coforma any feedback from your perspective?

**Comment by eileen-coforma** [comment]
@Mottie There is [new copy ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/sourceofcontenttruth.md#step-3-of-4-new-and-relevant-evidence-7) for the additional info section on the yes/no screen.

We were trying to auto-open the 'evidence upload instructions' additional info section on first upload, and close it for additional uploads. Was this not possible with the component?

Couldn't test uploading and document type selection in staging... I got the this error:

> We’re sorry. We’re unable to connect to VA.gov. Please check that you’re connected to the Internet, so we can save your application in progress.

**Comment by rocio-desantiago** [comment]
@eileen-coforma Not sure if it's doable due to the limitations of the VA component. It's out of scope for this ticket. @Mottie should we create a new ticket to explore this?

**Comment by Mottie** [comment]
Rocio is correct, we can't auto-open an additional-info web component. I'll get the error messages updated.

**Comment by eileen-coforma** [comment]
@rocio-desantiago 
I noticed a few inline errors in the PDF upload page that I don't have in the content document, can you catalog these errors, so I can edit them to remove the word "please"?
Example:
> Please provide a password to decrypt this file

**Comment by eileen-coforma** [comment]
@rocio-desantiago Do you know if the PDF password validation is suppose to work on staging? I tried uploading a passworded PDF, and the password field popped up, but it says there's an error when I provide the correct password.

**Comment by eileen-coforma** [comment]
@rocio-desantiago 
I think you're still working on the copy edits I left above, but here are a few other things I'm noticing in staging now:

- On the 'Do you want to upload your records or other documents to support your claim?' y/n page, the question needs to be required. Right now, it's allowing me to continue without answering y/n.
- Copy under 'Types of supporting evidence' was updated in the [content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/sourceofcontenttruth.md#step-3-of-4-new-and-relevant-evidence-7) that I've directly linked.

**Comment by Mottie** [comment]
- Making the evidence questions required will be available after merging in PR [#22946](https://github.com/department-of-veterans-affairs/vets-website/pull/22946)
- Content updates, if not already in place will still need to be done

**Comment by rocio-desantiago** [comment]
@eileen-coforma @Mottie Will push content updates separately. Still investigating PDF password error.

**Comment by saderagsdale** [comment]
@kylesoskin will look into the issue (in case it's a backend prob)

**Comment by rocio-desantiago** [comment]
> @rocio-desantiago I noticed a few inline errors in the PDF upload page that I don't have in the content document, can you catalog these errors, so I can edit them to remove the word "please"? Example:
> 
> > Please provide a password to decrypt this file

@eileen-coforma For these does the "Please" get replaced with "You must"?

**Comment by eileen-coforma** [comment]
@rocio-desantiago Can you give me a comprehensive list of uncatalogued errors that pop up?
So far we are replacing "Please" with "You must", but I'd still want to run them with the copy team to be sure.

**Comment by rocio-desantiago** [comment]
@eileen-coforma will do 👍

**Comment by saderagsdale** [comment]
@eileen-coforma add accessibility edit

**Comment by eileen-coforma** [comment]
@rocio-desantiago 
Expose the first paragraph from the additional information.
Design with additional information closed (default): https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/a/AxyKgM5
Design with additional information open: https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/a/DPgyWMk

**Comment by rocio-desantiago** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/23143) submitted

**Comment by eileen-coforma** [comment]
@Mottie Not sure if this just broke, or if we didn't catch it initially. I'm allowed to continue when I haven't uploaded anything, despite it being required.

**Comment by eileen-coforma** [comment]
Robin couldn't duplicate, and when I used a different test account, I also couldn't duplicate the issue. Treating it as a non-issue right now.
Everything looks good, otherwise.
@saderagsdale we can close this.
