### ISSUE TITLE
Supplemental Claims | Submission Confirmation Page

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#49553]
## Value Statement
**_As a_** Veteran
**_I want to_** receive a confirmation when I submit my form
**_So that_** I know if my form was submitted successfully. 

---
## Acceptance Criteria
- [ ] User receives a confirmation for successful submission.
- [ ] User no longer sees successfully submitted Supplemental Claims as still in-progress
- [ ] Unit tests complete (90% coverage)
- [ ] E2E tests complete
- [ ] Accessibility testing complete
- [ ] Reviewed and approved by product and/or design

## Designs and Build Notes
[DESIGN](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/a/zxga7zl)
[CONTENT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/sourceofcontenttruth.md#thank-you-for-filing-a-supplemental-claim)

## Out of scope
- How status and confirmation appears on My VA?

## Open questions
- How can we connect this to My VA or the Claim Status tool?
- How long does it take for a successful form submission to show up on My VA?
- What are next steps veterans can take after submitting their form?

## Tasks
- [x] Design confirmation page
- [ ] Review design
- [x] Review copy

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
@saderagsdale @thehastingsp 
Made a ticket for the confirmation page. 
This still needs design, so I've put it in the Design pipeline for now, and assigned myself to it. 
Will work on it, and most likely finish, by next week.

Please review the open questions, and see if I've captured everything.

**Comment by eileen-coforma** [comment]
Copy approved.

**Comment by eileen-coforma** [comment]
@Mottie @rocio-desantiago I updated the design file to reflect copy changes requested by Beth. 

Please let me know if the featured content unit can be styled the way that's shown, because there has been a change in header hierarchy and includes an additional link below the button.

**Comment by eileen-coforma** [comment]
I removed the 'User receives a notice for unsuccessful submissions.' acceptance criteria for this page, because the error message won't appear here, it would appear on the Review and Submit page instead.

**Comment by eileen-coforma** [comment]
@rocio-desantiago 
A few things aren't matching the design.

1. Missing a link with icon for 'Download your completed claim (PDF)' that lets the veteran to download a completed copy of their claim.
@saderagsdale This might be considered as a new functionality that is not part of our original acceptance criteria. It was a request that came from the copy team, as part of the confirmation page template change they're doing site-wide.

2. Button copy: 
- First button copy should say 'Print this page'
- Second button copy should say 'Track the status of your claim'

**Comment by rocio-desantiago** [comment]
@eileen-coforma Fixing the text on those buttons, but yes we don't have the capability to download a PDF, so we'll need to create a backend ticket for that first and implement it once that's ready.

**Comment by eileen-coforma** [comment]
Button copy looks good.

@saderagsdale The ability to download a copy of your claim is not part of the initial MVP requirements/ask. Is there somewhere we can keep track of things we would want to revisit post-launch?
