### ISSUE TITLE
FE | Profile | Bug | Adjust Placement of In-line Error Alert and Text

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#49550]
## Background

The text used for the in-line error messages on the Contact info page should be placed above the buttons. 

Specifically since this alert is templated in a section of a component that doesn't include the buttons, it can't just be moved as is, and will need to move to a more 'global' component that is higher in the component tree. The associated ticket #47757  has more information about why this is limited needs further work to move into the correct place.

Additionally, the text needs to be changed from "Please check back later." to "Try again later." Mock-up below:

<img width="373" alt="image" src="https://user-images.githubusercontent.com/55992116/195820017-1b2474c1-502e-4466-a651-ab6aba5f5cb1.png">

## Tasks
- [x] Adjust placement of in-line error alert (applies to all fields: home, work and mobile phone numbers as well as mailing address and home address)
- [x] Update alert to reflect new copy as show in mock above 
- [x] Conduct Unit tests 
- [x] Run E2E tests covering current code and regression
- [ ] Validate
  
## Acceptance Criteria
- [x] Complete all unit testing
- [x] End-to-end tests showing 0 violations
- [x] All axe checks pass
- [x] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)? PM or Design
- How can this work be validated? Validate in Staging
- What updates need to be made (e.g. product outline, use cases, contact center guide) All documentation that references this alert.

## Associated Tickets
- #47757

**Comment by SKasimow** [comment]
@ericasauv09 - I'm taking this section out of the ticket bc the confirmation messages shows the correct text and placement. We just need to update error placement and associated text.

1. In the discussion for #47757 we decided that the "edit saved" alert should be placed between the address and edit/remove buttons in the mailing address section of the contact information page. This was discussed in this [thread](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47757#issuecomment-1304052361).  
![image](https://user-images.githubusercontent.com/97113607/201169935-32f157cd-3d0a-46ac-ad86-f7c672fd3610.png)

**Comment by Samara-Strauss** [comment]
Adam -- \will this be done by tomorrow? OK, if not, but wondering if I should move it into the next sprint. Thanks!

**Comment by adamwhitlock1** [comment]
@Samara-Strauss I guess this ticket will have to move over to next sprint :( the work is done and the PR has actually been merged, but somehow again some flakey tests in another application have been merged into main and it has actually prevented this code from getting to staging today for validation.

You can see it being merged here https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard but unfortunately the broken tests are going to prevent it from making it to staging and dev environments.

I have raised this concern in the status-vets-website channel and will also be creating a support request in the morning.

**Comment by Samara-Strauss** [comment]
Totally fine! I'll move it over. Thanks for letting me know.

**Comment by adamwhitlock1** [comment]
@Samara-Strauss and @BerniXiongA6 This fix has been deployed and can be tested now.

Steps to validate would include 
- opening the address update UI for either home or mailing address on the Contact Information page
- block requests through the devtools network tab via the steps here:
  - https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/profile_errors.md#appendix-simulate-a-slower-network-connection
  - instead of setting it to a slower speed, instead just set the throttling to 'offline'
- attempt to save an address update
- verify that error message displays and is now right above the buttons in the UI

**Comment by Samara-Strauss** [comment]
Thanks for the detailed steps on how to validate! They were so helpful.

The error is appearing in the right place, but there is a period missing after "Try again later". Once that's added, this should be good to go.

![image](https://user-images.githubusercontent.com/34068740/216392309-2ae7ef2a-2dbc-4ac9-9367-cd9ed8312468.png)

**Comment by adamwhitlock1** [comment]
@Samara-Strauss and @BerniXiongA6 Fixed the missing period in the alert and confirmed that it has deployed to staging.

![Screenshot 2023-02-06 at 1.27.17 PM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/6e2ca032-ecb5-4f01-83ca-43f6c5753431)

**Comment by Samara-Strauss** [comment]
Validated! This should be good to close once it's pushed to prod.
![image](https://user-images.githubusercontent.com/34068740/217086882-6f353efc-2a4d-420c-91f7-522aefa0b773.png)

**Comment by adamwhitlock1** [comment]
Verified that it is now in prod. Closing
