### ISSUE TITLE
[BE] Enable and add mocks for Travel Claim Submission endpoints

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#49556]
## User Story
As a developer for Travel Claims submission, I want to be able to use the mocked responses when testing locally.

## Tasks
- [ ] [BE] Enable betamocks for Travel Claims by adding configs in service_config
- [ ] [BE] Add mocked responses to vets-api-mockdata repo

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
