### ISSUE TITLE
[FE] [TECH DEBT] Replace remaining react component with web component

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#49554]
## Background 

We have one remaining react component in our codebase. (Modal [here](https://github.com/department-of-veterans-affairs/vets-website/blob/d60edf1aa4503bf542c58f46ddcaca37dd20aaf1/src/applications/check-in/pre-check-in/pages/Introduction/IntroductionDisplay.jsx#L6))

## Tasks
- [ ] [FE] component has been replaced
- [ ] [FE] functionality/design are confirmed unchanged
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by acrollet** [comment]
@brianseek here's the ticket. @loripusey this was brought up by the DS team, this will be a blocker to us using v3 components.

**Comment by loripusey** [comment]
I have to wait for staging tool to start working again

**Comment by acrollet** [comment]
@loripusey it should be working, please refresh and let me know if it's not working for you.

**Comment by loripusey** [comment]
ID10T error; forgot to start my VPN this morning; 
validated
