### ISSUE TITLE
DLD: Create Swagger docs in vets-api

### ISSUE THREAD

**Issue by samcoforma** [department-of-veterans-affairs/va.gov-team#49562]
## Issue Description
In order to fulfill the platform requirement of providing URLs to any swagger documentation, and to provide easy discovery and integration of our endpoints, we must create Swagger 2.0 documentation and integrate it into the main va.gov swagger document.

---
## Tasks
- [x] Create Swagger docs for vets-api DLD code.
- [x] Integrate DLD Swagger docs to main Swagger UI page
- [x] Add integration tests to support responses described in the DLD Swagger docs

## Acceptance Criteria
- [x] I can navigate to the [main swagger docs page](https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/). When I search the page for "claim letters", I should see a "claim_letters" section with 2 nested routes
- [x] I can navigate to [#/claim_letters/getClaimLetters](https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/claim_letters/getClaimLetters) and see a detailed description of the responses and any request parameters
- [x] I can navigate to [#/claim_letters/downloadPDFClaimLetter](https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/claim_letters/downloadPDFClaimLetter) and see a detailed description of the responses and any request parameters
