### ISSUE TITLE
[BE] Handing BTSSS Claims API Error Response 

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#49563]
## User Story
As a Frontend engineer, I want to receive unique error codes from the backend so that I can display the appropriate error page to the veteran

## Tasks
- [ ] [BE] Modify response object to parse claims API error message
- [ ] [BE] Construct error message with unique error code

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
