### ISSUE TITLE
Develop Page Structure for Platform Research Guidance

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#49588]
## User Story
As a governance team member, I want to understand the page structure for platform research guidance, so that I know where to put new and/or updated documentation.

Assignee:
Peer Reviewer:

## Description
The current governance team backlog has several tickets regarding user research that need to move from Github to the platform website. Some of these are related to research techniques, others are about approach (trauma informed research, inclusive research). Rather than ping the sitewide team for help finding a home for each research page, it would be helpful to work together to develop a high-level page structure for user research. 

## Impacted Artifacts
- User research pages on platform website

## Tasks
- [ ] Review user research guidance currently on platform website
- [ ] Consult user research tickets in pipeline that need to move over
- [ ] Work together with sitewide content & IA team to develop a page structure (keeping structure as flat as possible per [VA.gov standards](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-best-practices.md))
- [ ] Move any affected user research pages on platform website to fit within new page structure

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ]  User research guidance on platform website is easy to navigate
- [ ] Platform teams know where to put new or updated user research guidance

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@naomimarcussen would you take a look at this ticket to see if this work is still needed ? please let us know.

**Comment by naomimarcussen** [comment]
Based on [this study](https://vfs.atlassian.net/wiki/spaces/DCP/pages/3420160001/Results+Platform+website+-+research+content), we've reorganized the IA of the Research at VA section. We can close this ticket.
