### ISSUE TITLE
DDL: Write unit tests

### ISSUE THREAD

**Issue by jaredcunha** [department-of-veterans-affairs/va.gov-team#49594]
## Value Statement

**_As a_** front end developer
**_We want to_** make sure that all the DDL code has unit testing coverage
**_So that_** we can ensure we're releasing a quality product

## Background Context

DDL is getting closer to release, we need to ensure all components have unit test coverage, including keyboard-only testing where necessary

## Tasks
- [x] Write all unit tests for DDL

## Definition of done

- [x] All tasks complete
- [x] All tests passing

**Comment by kjduensing** [comment]
@jerekshoe , can you please comment on this ticket with the name of the FE unit test branch?

**Comment by jerekshoe** [comment]
@kjduensing Frontend branch: `49594-ddl-unit-tests`
