### ISSUE TITLE
[Design] My VA Benefit Payments: Review Links for "Never Had a Payment" Use Case

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#49605]
## Background
We want to review what links we show users who have never received a payment from the VA. Specifically we want to determine if we need to show any links at all or if this can be simplified to match what we show users who have not had payments in the past 60 days. Currently a user who has not received a payment in the last 30 days will see two links "Manage your Direct Deposit" and "Review your payment history." A user who has never received a payment will only see the "Manage your Direct Deposit link."

## Tasks
- [ ] Review designs and determine new designs if necessary
- [ ] Review changes/recommendations with team
- [ ] Review changes/recommendations with Benefits 1 team
- [ ] Update any sketch files and FE documentation as necessary
- [ ] Update use case documentation

## Acceptance Criteria
- [ ] Decision is made on whether to remove/edit/ or keep links for "never had a payment" use case and documentation is updated as appropriate

**Comment by ericasauv09** [comment]
@ajakabcin We do currently have two separate use cases for users who have never received a payment vs users who haven't received a payment in the last 60 days, so this ticket would be to determine if we want to simplify that: 
No payments past 60 days: ![Screen Shot 2022-12-12 at 16.18.27.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/40a2b58f-0c33-4abc-b8fb-0b08741524ea)

No payments ever: ![Screen Shot 2022-12-12 at 16.18.06.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/712f4dd4-3b5e-4d15-acff-05797f777a84)
