### ISSUE TITLE
Spanish translation for Vietnam Veteran health care Q&A on PACT Act page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#49613]
## Issue Description
We added a new Q&A about Vietnam Veteran health care eligibility to the PACT Act page that we need translated in Spanish. 

Content sent to translators: [https://app.zenhub.com/files/133843125/cce5e74c-c5ac-4904-b8e3-0a552d274862/download](https://app.zenhub.com/files/133843125/cce5e74c-c5ac-4904-b8e3-0a552d274862/download)

## Tasks
- [x] Send text to translators (Randi)
- [x] Update page (Aliyah)
- [x] Copyedit (Megan)
- [x] Publish (Megan)
- [x] Send live page to translators for QA (Randi)

## Acceptance Criteria
- [x] Live page has newest content

**Comment by RLHecht** [comment]
@aliyahblackmore here is the translation back from the State Department:

[https://app.zenhub.com/files/133843125/184e48bb-81b3-4727-8278-0302b8c93f3d/download](https://app.zenhub.com/files/133843125/184e48bb-81b3-4727-8278-0302b8c93f3d/download)

**Comment by aliyahblackmore** [comment]
Hi @megzehn - this last change is also ready for you! 

**Preview link**: http://preview-prod.vfs.va.gov/preview?nodeId=48330

**Note:**  
The bullet points in this accordion do have periods at the end. That is the case across the Spanish page - and I believe this is a grammar choice. Noting this in case you want to flag it with the translators! 

Thank you!

**Comment by megzehn** [comment]
This looks good! Thanks so much, @aliyahblackmore! This page is now published. 

CC @RLHecht

**Comment by RLHecht** [comment]
This is now live. Sending the live link to the translators for QA.
