### ISSUE TITLE
Design | Profile | Screenreader Accessibility Issue | Account Security Part 2

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#49615]
## Background

Continuation of #47299 

To look into:

Accessibility - is this dishonest if we create this clear order if it is not a required order?
Featured content box - Is this box necessary for sign in once signed in?
LOA1 - create mockups
Sign in information - check related links (I believe we confirmed this together already)

## Tasks
- [x] Review/update designs based on feedback above
- [x] Create/update sketch files and relevant documentation

## Acceptance Criteria
- [ ] Documentation updates
- [ ] Notify PM when ready for FE implementation

## Associated Tickets
- #47299

**Comment by SKasimow** [comment]
Hi @cgednalske  - can you point this? I have some other documentation tickets I'll be sending over for pointing as well; want to can make sure I don't overload you next sprint!

**Comment by cgednalske** [comment]
@Samara-Strauss @SKasimow -- Here the [mockup](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/a/ELoLJDg) for what the LOA1 version would look like following the new approach for Account security. (The terms and conditions step does not show for LOA1, but everything else does.) What are your thoughts on this layout?

Btw, the text in red for Verify your identity step would need to be confirmed/worked on with Danielle. For now, I've included a brief description. 

<img width="510" alt="Screen Shot 2022-11-18 at 8 34 49 AM" src="https://user-images.githubusercontent.com/79372956/202773267-0c8429d7-6cc1-4f8c-b4f2-814cd56edc7d.png">

**Comment by Samara-Strauss** [comment]
This looks great! Re: the mockup -- you can remove the nametag since we confirmed nametags don't show in the LOA1 state.

**Comment by cgednalske** [comment]
I've finished the mockups for both [desktop](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc) and [mobile](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/p/E79E0419-8D9A-4CF2-A052-EEBA8274E418/canvas). As mentioned, I've left the current screens as they are and added the new one in addition - rather than replacing them since future work is up in the air.

@SKasimow for the documentation mentioned here, I feel like we should also leave that until work moves forward since it may be a while until this is implemented. What do you think?

I also added [iterations](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/p/2C161C3E-B7C6-4348-B295-0DCE9AD75E34/canvas) in Account security for the removal of the blue featured content box and the new approach with the process list.

**Comment by Samara-Strauss** [comment]
These look good to me! Thanks, @cgednalske!

I noticed that for the "Current" mocks, the blue box has been removed. Is this update happening prior to the contract ending? I would love if it did, but not sure if a ticket has been created for that yet. If this update can happen before the contract ends, great. If not, you need to add the blue box back to the mocks to show that it is still on the site.

**Comment by cgednalske** [comment]
@Samara-Strauss yep! Unless I'm misremembering, in grooming on Wednesday I believe we confirmed the blue box can be removed very soon because it's a quick change for Adam. @SKasimow is that accurate?

**Comment by SKasimow** [comment]
Yup - I opened #50007 for this and plan is to include in Sprint 88 (1 pt)

**Comment by Samara-Strauss** [comment]
Thank you both! This sounds good to me, and everything looks good to go.

**Comment by cgednalske** [comment]
Closing this out! I'll be taking a small piece of content to Danielle on Thursday so content is completely approved for future work (no ticket for that - just noting it here).

**Comment by Samara-Strauss** [comment]
Frontend ticket #51085
