### ISSUE TITLE
Create workflow diagram of Project Intake

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#49610]
## Issue Description
Use the workflow that Ray built, along with early discussion on the Project Intake proposal, to create a workflow diagram.

In our Sync, Ray later shared the Design Systems intake board  https://github.com/orgs/department-of-veterans-affairs/projects/779/views/1

he likes the “by priority” option and boards in general
## Resources
[Proposal notes](https://vfs.atlassian.net/wiki/spaces/~622b5b63932f0f00716bdfd6/pages/2400846510/Project+Creation+Process+and+SDT)

## Tasks
- [x] build [diagram](https://lucid.app/lucidchart/e2d771f0-6d82-4f13-8411-9e983ec0687d/edit?viewport_loc=-301%2C-137%2C7464%2C3531%2C0_0&invitationId=inv_fc1e26fe-e5c7-4a42-902d-2999a568b8b6)
- [x] Refine w/ team input

## Acceptance Criteria
- [x] initial version of diagram is complete
