### ISSUE TITLE
Launch "View your VA combined disability ratings" to Production

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4961]
## Goal
These are the tasks that are involved in launching the Rated Disabilities or "View your VA combined disability ratings" tool page into production, provide a venue for UAT, and make the tool page publicly available.

## Considerations
Using the [UAT plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-rated-disabilities/UAT/release-plan.md) to accompany this.

### Monthly Views  
www.ebenefits.va.gov/ebenefits/about/feature?feature=disability-compensation
Jan 5 - 11: **35,391**
Jan 12 - 18: **29,993**
Jan 19 - 25: **27,493**
(Release) Jan 26 - Feb 1: 
Feb 2 - 8:

www.va.gov/disability/view-disability-rating/rating
Feb 2 - 8:
Feb 9 - 15:
Feb 16 - 22:

## Tasks
- [x] Update the [basic auth yml file](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/react_routes.yml#L13) to gate the tool page with two new lines:
```
- path: /disability/view-disability-rating/rating
  protected: yes
```
- [x] Submit a PR for the tool page to be moved to production (url: /disability/view-disability-rating/rating)
- [x] Send a request to **#vsa-public-websites** that the unauthenticated landing page be made live from draft in Drupal (url: /disability/view-disability-rating)
- [x] [UAT plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-rated-disabilities/launch/uat.md)
  - [x] Contact two known veteran users and ask them to view it and give feedback
---
- [x] Let #vsa-public-websites know that we are ready for the "Manage" section in the disability spoke to link to the unauthenticated page.

## Acceptance Criteria
- [x] The tool page is publicly available to all LOA1/3 users and if applicable, displaying their own rated disabilities.
