### ISSUE TITLE
Design | Profile | Nametag | Update Documentation

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#49616]
## Background

After completing #48306 we want to ensure all Sketch files are updated to reflect the Nametag states and that we have these new designs and states documented in  our Git repository.

## Tasks
- [x] Update sketch files as applicable
- [ ] Update CC guide
- [ ] Update use cases as applicable
- [ ] Update/create Git documentation
  

## Acceptance Criteria
- [ ] Documentation is complete for the Nametag section 

## Associated Tickets
- #48306

**Comment by SKasimow** [comment]
Hi @cgednalske - here's another one for you to point :)

**Comment by SKasimow** [comment]
@cgednalske - another one for points!

**Comment by cgednalske** [comment]
@Samara-Strauss @SKasimow here's the [Sketch file](https://www.sketch.com/s/bca53b50-8797-44fa-8c37-2b13c24c626c) I've created for the nametag + updates to the [existing documentation in GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/nametag.md). Any thoughts on the setup and if there are any further updates needed that would be helpful? And because this is a file both My VA and Profile teams need to access, is there somewhere else we should move the GitHub doc that would be more helpful?

One thing we're still checking on is fiduciary/deceased/incompetent flag should affect the nametag behavior. I ran these by Adam and he confirmed that the entire nametag currently shows, but we're wondering if it would make more sense to show just full name. I just started [this thread](https://dsva.slack.com/archives/C909ZG2BB/p1669653325291299) in the team channel so we can discuss this.

**Comment by Samara-Strauss** [comment]
> here's the [Sketch file](https://www.sketch.com/s/bca53b50-8797-44fa-8c37-2b13c24c626c) I've created for the nametag

Great, thank you!

> updates to the [existing documentation in GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/nametag.md).

These need to be moved out of the My VA 2.0 project folder, since we do not and should not be updating documentation from old projects. I would recommend talking to Liz and Angela about where this documentation should live. This should likely also be linked to from our profile product outline, so that people can easily find it.

> One thing we're still checking on is fiduciary/deceased/incompetent flag should affect the nametag behavior. I ran these by Adam and he confirmed that the entire nametag currently shows, but we're wondering if it would make more sense to show just full name. I just started [this thread](https://dsva.slack.com/archives/C909ZG2BB/p1669653325291299) in the team channel so we can discuss this.

I'll reiterate what I said in Slack -- I don't think we need to make any adjustments to the nametag in the fiduciary state for now.

**Comment by Samara-Strauss** [comment]
Hey -- I was just thinking that it probably makes sense to have the nametag docs live in either the [My VA folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va) or the [Profile folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile), and then we can cross link to whatever folder the documentation does not live in.

**Comment by cgednalske** [comment]
@Samara-Strauss ok! That sounds good to me. I went with the Profile folder because many of the use cases are more Profile-related. I created a new nametag folder to house the doc because it didn't seem to fit well in an existing folder, but let me know if you'd prefer elsewhere. I've also linked to the doc from both the My VA and Profile product outlines. 

Here's the new [GitHub doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/nametag/README.md) and the [Sketch file](https://www.sketch.com/s/bca53b50-8797-44fa-8c37-2b13c24c626c) both with updated info for the Blocked Profile use case.

Do you prefer I revert the older nametag documentation in the My VA 2.0 project folder back to the earlier version, remove it completely, or leave as is with the updated info?

**Comment by Samara-Strauss** [comment]
Thank you, Christina! This is great. I made a few small edits to clarify some things, but this is otherwise great and all set.

> Do you prefer I revert the older nametag documentation in the My VA 2.0 project folder back to the earlier version, remove it completely, or leave as is with the updated info?

No need to revert. No one should be checking this documentation at this point.

**Comment by cgednalske** [comment]
@Samara-Strauss awesome! Sounds great - thank you. I think this is all set to close out then 🙂
