### ISSUE TITLE
Fix local vets-api Docker setup

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#49617]
## Issue Description
It was reported by several engineers that there are problems running `vets-api` locally using the Hybrid and the Docker setup.

Essentially, a periodic sidekiq job was [implemented here](https://github.com/department-of-veterans-affairs/vets-api/pull/11076/files). Periodic jobs are a feature of sidekiq enterprise, which is enabled in the live environments BUT isn't a requirement for local development. This causes vets-api server to fail on boot. Periodic jobs was used in this case to mitigate/correct duplicate jobs possibly being caused from the current third party "recurring jobs"

We should investigate if wrapping the periodic job definition in a conditional is acceptable, or if moving the job to the sidekiq_scheduler is a better solution.

Support request link - https://dsva.slack.com/archives/CBU0KDSB1/p1668437233213309

Note: According to [this doc](https://www.mikeperham.com/2015/08/06/sidekiq-enterprise/), it recommends registering a periodic job in the current way in which it's registered (in the initializer)

---
## Tasks
- [ ] Read sidekiq enterprise doc - discover recommended solution for periodic job definitions
- [ ] Implement solution

## Acceptance Criteria
- [ ] vets-api can start up locally via docker and native setup
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by holdenhinkle** [comment]
The problem:

> Platform support
APP Today at 9:47 AM
From 
@Kevin Duensing
: Good morning! I'm trying to get vets-api running locally with the hybrid docker/native approach. I've followed the instructions and I'm having some trouble. I'll list both ways that I've tried to run it with associated error messages in the thread. Would someone mind taking a look with me? Thanks!

He continues:


Kevin Duensing
  4 hours ago
First approach
`Command: foreman start -m all=1,clamd=0,freshclam=0`
```
Error:
09:46:38 job.1       | E, [2022-11-14T09:46:38.914594 #29110] ERROR -- : Coverband: view_tracker failed to store, error NoMethodError
09:46:39 job.1       | exited with code 1
09:46:39 system      | sending SIGTERM to all processes
```

Kevin Duensing
  4 hours ago
Second approach:
Command: `rails server`
Error in browser after `hitting http://localhost:3000/v0/status:`
```
{"git_revision":"MISSING_GIT_REVISION","db_url":null}
I also get this error in the browser [2022-11-14T09:50:32.753643 #30556] ERROR -- : Coverband: view_tracker failed to store, error NoMethodError, but it's not a fatal error
```

***

The solution:

Scott James
  1 hour ago
Ran into this this morning as well running on docker
First approach
Command: `foreman start -m all=1,clamd=0,freshclam=0`
```
Error:
09:46:38 job.1       | E, [2022-11-14T09:46:38.914594 #29110] ERROR -- : Coverband: view_tracker failed to store, error NoMethodError
09:46:39 job.1       | exited with code 1
09:46:39 system      | sending SIGTERM to all processes
```

Digging into the development.log I saw this message

```
2022-11-14 17:40:35.924229 D [11:75680] Rails -- undefined method `periodic' for Sidekiq:Module excluded from capture: DSN not set
```

Line source
`sidekiq.rb`

```
    config.periodic do |mgr|
      mgr.register('0 5 * * 1', 'AppealsApi::WeeklyErrorReport')
    end
```

Scott James
  1 hour ago
When commenting that out I got the server to run with my docker setup

**Comment by aaronyoung-tw** [comment]
I can confirm Scott James solution fixed my issues running the back end in native as well as hybrid

**Comment by AGarcia-Clarity** [comment]
There could be a [rogue Sideqik process](https://github.com/mperham/sidekiq/issues/4968) running somewhere

**Comment by bosawt** [comment]
@holdenhinkle I just saw this, that `config.periodic` should actually be removed from the initializer, and the job should go inside `sidekiq_scheduler.yml`. People are probably seeing errors with this on localhost when they don't have Sidekiq Enterprise installed (which should not be a prerequisite for localhost development): https://github.com/mperham/sidekiq/wiki/Ent-Periodic-Jobs

**Comment by michelpmcdonald** [comment]
I added that......we are trying to use enterprise periodic jobs to get around the double running we and other are hitting using the 3rd party "recurring jobs" scheduler.

How about if I guard that code with ~if defined?(Sidekiq::Enterprise).
We already have a sidekiq "pro" guard in sidekiq.rb

**Comment by LindseySaari** [comment]
After following up with the commenters in the ticket, it was determined that the specific behaviors from periodic job are needed in this particular case to avoid duplicate jobs. Wrapping the periodic job defintion is acceptable in this case because the suggestion to move the job to the sidekiq_scheduler isn’t a solution that will work. Sidekiq Enterprise periodic jobs are necessary as they will correct the duplicate job behavior and scale across all the Sidekiq processes. 

Wrapping the periodic job definition in the conditional will allow developers to develop locally without the need for sidekiq enterprise. The conditional solution has fixed local development for both docker and native setup.

**Comment by michelpmcdonald** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-api/pull/11192) for the fix
