### ISSUE TITLE
Tagalog translation for Vietnam Veteran health care Q&A on PACT Act page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#49614]
## Issue Description
We added a new Q&A about Vietnam Veteran health care eligibility to the PACT Act page that we need translated in Tagalog. 

Content sent to translators: [https://app.zenhub.com/files/133843125/cce5e74c-c5ac-4904-b8e3-0a552d274862/download](https://app.zenhub.com/files/133843125/cce5e74c-c5ac-4904-b8e3-0a552d274862/download)

## Tasks
- [ ] Send text to translators (Randi)
- [ ] Update page (Aliyah)
- [ ] Copyedit (Megan)
- [ ] Publish (Megan)
- [ ] Send live page to translators for QA (Randi)

## Acceptance Criteria
- [ ] Live page has newest content

**Comment by RLHecht** [comment]
@aliyahblackmore Here is the translation back from the State Department:

[https://app.zenhub.com/files/133843125/99b3ca32-904d-4d20-b21e-88bb93e36011/download](https://app.zenhub.com/files/133843125/99b3ca32-904d-4d20-b21e-88bb93e36011/download)

**Comment by aliyahblackmore** [comment]
Hi @megzehn - this is ready for you! This was the additional change that needed to be made to this page. 
Thank you!

**Preview link**: http://preview-prod.vfs.va.gov/preview?nodeId=48613

**Comment by RLHecht** [comment]
I reviewed these and published. Moving to validate.
