### ISSUE TITLE
Provide Intro for Brian, new team member

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#49622]
### Tasks:

- [x] Schedule meeting (1 hour) for all team members, including Brian
- [x] Provide overview what our team does

- the Platform website
- our team meetings
- github/zenhub/slack
- website deployment process
- customer support processes (Slack & platform website footer)
- how initiatives are created and how we work on them
- other Platform teams

- [x] Provide him with pages from Confluence that he can read through on his own time

- [x] Answer any questions he has
