### ISSUE TITLE
[BE] Update Exception handling to return an appropriate error response to front-end

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#49628]
## User Story
As a Veteran submitting Travel Claim when using eCheck-in, I want to see an appropriate error response when there is an error with submission.

## Tasks
- [ ] [BE] **Add error mapping to excpetions.yml**
- [ ] [BE] **Update travel_claim client to return an appropriate response**
- [ ] [BE] **Update response handler to return an appropriate exception**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
