### ISSUE TITLE
FE | Profile | Remove BAI Feature Flag (and others)

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#49647]
## Background

We need to remove any feature flags that are no longer needed in all affected environments.
One known flag that should be removed is the one created for BAI (show BAI and force BAI). There are also a few others that were recently called to our attention:

> direct_deposit_cnp
> direct_deposit_edu
> direct_deposit_vanotify

## Tasks
- Remove the FE code used for the feature flags below:
- [x] BAI (show and force)
- [ ] > direct_deposit_cnp
- [ ] > direct_deposit_edu
- [ ] > direct_deposit_vanotify
- [x] Remove the flag from local, staging, and prod environments using the Flipper UI
- [x] Update/cleanup Cypress tests

## Acceptance Criteria
- [x] Complete successful testing
- [ ] Features are working in production
- [x] Events are logged appropriately

**Comment by adamwhitlock1** [comment]
I have a PR ready for removing the BAI feature toggles (2), but when looking at the code for the FE there is no reference to the direct deposit toggles (3) so those toggles strictly gate data/feature on the BE.

@tpharrison Wanted to get you eyes on this ticket and see if you can create a corresponding ticket for BE work. I did notice that there were a couple places that were using the direct deposit feature toggle values in relation to logic that would return data on endpoints.

One example being the ppio policy here https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/policies/ppiu_policy.rb#L18

**Comment by tpharrison** [comment]
@adamwhitlock1 Opened [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50019) to remove any BE references to these flags.  I'll start working on this today.

cc/ @SKasimow

**Comment by SKasimow** [comment]
Got it -- added Tom's ticket to current sprint (sprint 87). thx

**Comment by adamwhitlock1** [comment]
I have removed the BAI indicator flags and the feature still works as expected. @SKasimow you can validate in staging now. 

I validated that for test user 5 the bai ui does show

Test user 36 should not see the BAI at all (control case)

**Comment by SKasimow** [comment]
Tested and confirmed same...closing
