### ISSUE TITLE
Update special benefit allowances rates with rates for 2023

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#49646]
## Issue Description
The rates on the [special benefit allowances rates](https://www.va.gov/disability/compensation-rates/special-benefit-allowance-rates/) page change as of December 1, 2022. 

We need to update this page with the new content and create a past rates page. 

New rates:  [https://app.zenhub.com/files/133843125/29ad607d-b67e-4ac9-bde7-d91b6e68795b/download](https://app.zenhub.com/files/133843125/29ad607d-b67e-4ac9-bde7-d91b6e68795b/download)

Here is guidance on how to clone and create new rates pages: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/how-to-update-rates-pages.md

## Tasks
- [x] Clone page to create past rates page
- [x] Update current rates page with new rates
- [x] Copyedit past rates page (Megan)
- [x] Copyedit current rates page (Megan)
- [x] Publish both pages (Megan)
- [x] Add newest past rates page and remove oldest rates page from left nav (Megan)

## Acceptance Criteria
- [x] 2023 special benefit allowances rates are live
- [x] 2022 past rates page is live
- [x] Left nav is updated

**Comment by katherine-fung** [comment]
Hi @megzehn, 

I created a past rates page, and updated the live rates page with the new rates for 2023. 

Current rates page: http://preview-prod.vfs.va.gov/preview?nodeId=990 
Past rates page: http://preview-prod.vfs.va.gov/preview?nodeId=51211 

FYI we had done some earlier work to take these rates out of tables, but the changes aren't published yet. We still need to run the table work by stakeholders. So I reverted back to the tables, and made the updates there.

**Comment by laurwill** [comment]
I checked these pages, ready to publish on Monday

**Comment by RLHecht** [comment]
I published these and added to the left nav. Moving to validate.

**Comment by RLHecht** [comment]
These are now live. Closing ticket.
