### ISSUE TITLE
[Accessibility Testing]: 526ez | Update military service options

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#49655]
### Auditor(s)

Josh Kim

### Automated

- [X] Run axe checks on every page or unique state (required)
- [X] Run WAVE on every page if time allows. WAVE is more visual than axe or axe-coconut, but offers some excellent ways to identify nested headings and HTML5 landmark tags.

### Manual

- [X] Color contrast checks (recommend using whocanuse.com for beyond compliance reports)
- [X] Color blindness checks
- [X] Zoom layouts to 400% and inspect them for readability. If layouts break at 400%, I will start reducing them until they become stable, and log the zoom ratio when things started breaking.
- [X] Keyboard navigation

### Screen Reader

- [ ] Firefox and NVDA
- [ ] Edge and JAWS
- [ ] iOS Safari and VoiceOver (Mobile)
- [ ] Safari and Voiceover (Desktop)
- [ ] Chrome and Talkback

### Test Users

```bash
1.
2.
3.
...
```
