### ISSUE TITLE
Upgrade Ruby from 2.7 EOL

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#49669]
## Issue Description
Need to upgrade prior to EOL and manage potential BRD/EKS blockers during the upgrade as they arise.

`vets-api` is currently running Ruby `2.7.6`. According to [Ruby's historical EOL cadence](https://www.ruby-lang.org/en/downloads/branches/), it looks like Ruby `2.7` will hit EOL at the end of March or early April, 2023, just a little over 5 months from now.

The current version of Ruby is `3.2`.

Ruby versions - https://www.ruby-lang.org/en/downloads/releases/

***

The Backend CoP discussed the needed upgrade and agreed it would be best to upgrade to the next major version first, `3.0`, and then upgrade incrementally from there (i.e. 3.0, 3.1, 3.2, etc.)

BRD and EKS blockers are unknown.

---
## Tasks
- [x] #51827
- [x] Create plan of attack for upgrading apps and create tickets to reflect
- [x] Perform Discovery to try and assess breaking changes and estimate lift

## Acceptance Criteria
- [x] Have all BE Ruby apps running and tests passing for 3.1

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by andreahewitt-odd** [comment]
Took the project label off of this and nested it under the project
