### ISSUE TITLE
Update Veterans disability compensation rates page with rates for 2023

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#49666]
## Issue Description
The rates on the [Veterans disability compensation rates](https://www.va.gov/disability/compensation-rates/veteran-rates/) page change as of December 1, 2022. 

We need to update this page with the new content and create a past rates page. 

New rates: [https://app.zenhub.com/files/133843125/82c5146b-3f70-4d50-8421-9d1b91340829/download](https://app.zenhub.com/files/133843125/82c5146b-3f70-4d50-8421-9d1b91340829/download)

Here is guidance on how to clone and create new rates pages: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/how-to-update-rates-pages.md

## Tasks
- [x] Clone page to create past rates page
- [x] Update current rates page with new rates
- [x] Copyedit past rates page (Megan)
- [x] Copyedit current rates page (Megan)
- [x] Publish both pages (Megan)
- [x] Add newest past rates page and remove oldest rates page from left nav (Megan)

## Acceptance Criteria
- [x] 2023 Veterans disability compensation rates are live
- [x] 2022 past rates page is live
- [x] Left nav is updated

**Comment by katherine-fung** [comment]
Hi @megzehn! These are ready for copyedit.  

Current Veterans disability compensation rates page: 
http://preview-prod.vfs.va.gov/preview?nodeId=986 

Past rates page:

**Comment by laurwill** [comment]
Thanks @katherine-fung !

I checked the rates and it looks like the **with dependents, 70% to 100%** table changes didn't save — so I updated those, but I think we should have someone else check just that table before we publish. 

After that step, these are all set to pub on Monday.

**Comment by RLHecht** [comment]
These changes are live. Closing ticket.
