### ISSUE TITLE
[FE, BE] [Bug] Payment info v2: Investigate + resolve Outstanding debts error in prod

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#49663]
## Background
We are seeing an error in the Outstanding Debts section in production. Usually when we see this error it's something with the debts API and not My VA, however we aren't seeing any errors in the debt portal and need to determine if there's something wrong on My VA.
![Screen Shot 2022-11-15 at 9 57 27 AM](https://user-images.githubusercontent.com/45603961/201952581-f713d03b-f037-4c24-bb1b-247bceb463b7.png)

## Tasks
- [ ] Investigate the issue
- [ ] Determine if it's something for our team to fix or if we need assistance from another team
- [ ] Depending on level of effort implement the fix
- [ ] Validate

## Acceptance Criteria
- [ ] Error on Outstanding Debts is resolved

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ Log into prod and confirm error is not appearing in outstanding debts

**Comment by tpharrison** [comment]
Just looked at my account in prod, and I see the following...

![image](https://user-images.githubusercontent.com/653787/201975110-4602a861-3656-46a2-a99a-612a041a9011.png)

I don't see any errors with onsite-notifications calls to the API.

**Comment by tmitchellgcio** [comment]
No errors on my end either

**Comment by tmitchellgcio** [comment]
Findings: We assumed that there would not be a 403 for these which from now on should be the wrong assumption when we show sections all of the time. We will need to check the claims attribute on the user profile in order to tell if we can call these services before we call them. Tom says the `military_history` and `rating_info` claims are there, but `appeals` and `medical_copays` are not.  He'll open a ticket to add these.  These 403s shouldn't be causing any issues with outstanding debts though.
