### ISSUE TITLE
Update birth defect compensation rates page with rates for 2023

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#49665]
## Issue Description
The rates on the [birth defect compenssation rates](https://www.va.gov/disability/compensation-rates/birth-defect-rates/) page change as of December 1, 2022. 

We need to update this page with the new content and create a past rates page. 

Here is guidance on how to clone and create new rates pages: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/how-to-update-rates-pages.md

## Tasks
- [ ] Clone page to create past rates page
- [ ] Update current rates page with new rates
- [ ] Copyedit past rates page (Megan)
- [ ] Copyedit current rates page (Megan)
- [ ] Publish both pages (Megan)
- [ ] Add newest past rates page and remove oldest rates page from left nav (Megan)

## Acceptance Criteria
- [ ] 2023 birth defect compenssation rates are live
- [ ] 2022 past rates page is live
- [ ] Left nav is updated

**Comment by RLHecht** [comment]
@katherine-fung I added the newest rates to the top of this ticket. Since we have to clone the page to create a past rates page as well, can you do the work for the decimal points in this ticket? So make sure you clone the page before putting in the new rates. We can also chat about this in standup too if the directions are confusing!

**Comment by laurwill** [comment]
I checked these pages, ready to publish on Monday.

**Comment by RLHecht** [comment]
I published both of these pages and set up the left nav. Moving to validate.

**Comment by RLHecht** [comment]
These pages are live. Closing ticket.
