### ISSUE TITLE
[BE] My VA: Update User Claims

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#49689]
## Background
Add `appeals` and `medical_copays` to user claims.  See [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49663) from more information.

## Tasks
- [x] Add `appeals` to user claims.
- [x] Add `medical_copays` to user claims.
  

## Acceptance Criteria
- [ ] Ensure that `appeals` and `medical_copays` are includes in the `v0/user` response in staging.
