### ISSUE TITLE
Migrate Vet Center Veteran-facing legacy content and onboard Vet Center editors into Drupal

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#49680]
## Story
As a Veteran, I need a single-source-of truth for all appeal and decision review content that's easy to find, understand, and act on.

As VA, we need a single-source-of truth for all appeal and decision review content that the VA.gov content team and Vet Center team can collaborate on together to so that we can deliver consistent, accurate, plain language content to Veterans across channels.

## How we'll know when this work is complete

- [ ] All new pages are launched in the modernized VA.gov
- [ ] All relevant legacy pages and retired and redirected to modernized pages
- [ ] Vet Center authors are onboarded in Drupal and understand the new process for managing content in the modernized environment
