### ISSUE TITLE
Update Collab Cycle/Accessibility for WCAG 2.2

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#49681]
## User Story
_"As a VFS team member, I want to get accurate information from Platform about current accessibility requirements, so that my product is accessible for everyone."_

_"As an accessibility specialist on Governance team, I want my reviews to be consistent with industry best practices, so that I can provide VFS teams with good information."_

Assignee: @briandeconinck 
Peer Reviewer: @it-harrison 

## Description
[WCAG 2.2](https://www.w3.org/TR/WCAG22/) was officially recommended by the W3C in October 2023. It is now accepted as the industry standard for web accessibility.

@TiffanyPender [assessed the impact of WCAG 2.2 on VA.gov in 2022](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/shared-support/accessibility/projects/wcag-2.2/va.gov-and-wcag-2.2.md), and @eli-oat [mapped the impact to specific teams in 2024](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/Deliverables/CAIA/migrating-to-wcag-2.2.md#takeaways-and-vagov-considerations):

> **Considerations for VFS delivery teams**
> - Generally teams using the design system should be unaffected by a move to WCAG 2.2
> - The item most relevant to delivery teams will most likely be 3.3.7 Redundant Entry, and will likely require back end teams to also consider the accessibility of the data being collected, and when
>    - There is also a reading of this that would suggest redundant entry across forms -- this may require coordination from VA POs or even contracts to find ways to reduce the number of times a specific question is asked.
> 
> **Considerations for the Design System Team**
> - It is believed that the current focus state is in compliance with WCAG 2.2, but the Design System Team should confirm
> - It is believed that the design system doesn't currently include any drag-able elements, but the Design System Team should confirm
> - It is believed that the minimum target sizes are appropriate to WCAG 2.2, but there is uncertainty about this on mobile web. We suggest that this is validated when/if mobile testing becomes more prevalent within OCTO
> 
> **Considerations for Governance and CAIA supporting the Collaboration Cycle**
> - Key elements to look out for will be 3.3.7 Redundant Entry, and 2.5.8 Target Size
> - All other items will hopefully be well addressed by the Design System and the consistent use of static templates for the placement of header and footer elements

The purpose of this ticket is to update all accessibility guidance for the Collaboration Cycle and related processes to adhere to the new WCAG 2.2 changes. Based on Eli's work, we should:
1. Update references to WCAG 2.1 on VFS-facing resources (Platform website and VA Design System website).
2. Update internal guidance on conducting accessibility reviews to:
   - Reference WCAG 2.2
   - Check for new target size requirements
   - Assess products for redundant entry requirements
3. Update the new VA.gov experience standards
   - Add descriptive tags for the new WCAG success criteria
   - All WCAG descriptive tag reference links should point to WCAG 2.2

Making an assumption here that the pilot of the new VA.gov experience standards will be a success and that documentation supporting the old standards won't need to be updated.

## Impacted Artifacts
- [Tools and resources for QA testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/tools-and-resources-for-qa-testing)
- [QA Product Dashboard guide](https://depo-platform-documentation.scrollhelp.site/developer-docs/qa-product-dashboard-guide)
- [VADS Button component](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/35d676b3de36453055d271b00599d1711355f7cc/src/_components/button/index.md?plain=1#L119)
- [VADS Experimental Design Template](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/35d676b3de36453055d271b00599d1711355f7cc/src/_components/experimental-design-template.md?plain=1#L53)
- [VADS Additional Info component](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/35d676b3de36453055d271b00599d1711355f7cc/src/_components/additional-info.md?plain=1#L100)
- [VADS component checklist definitions](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/35d676b3de36453055d271b00599d1711355f7cc/src/_data/component-checklist/definitions.yml#L12)
- [How to complete an Accessibility review for Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2611511338/How+to+complete+an+Accessibility+review+for+Design+Intent)
 - [How to complete an Accessibility Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2492727318/How+to+complete+an+Accessibility+Midpoint+Review)
- [How to complete an Accessibility review for Staging review touchpoint](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2059763776/How+to+complete+an+Accessibility+review+for+Staging+review+touchpoint)

- [Revised Experience Standards descriptive tags](https://docs.google.com/spreadsheets/d/1q6UGLEd8re94B5o69EFDz2HNMHw6WvdAHl46FHYsA9s/edit#gid=500057009)
- [Drafting Template 2.0 descriptive tags](https://docs.google.com/spreadsheets/d/1dOAJNKYIFQOW5NGNtZ3l0PPEy5MNQHOl0zWEB2cl20E/edit#gid=605465842)
- [Drafting Template 2.0 - DST descriptive tags](https://docs.google.com/spreadsheets/d/1hMcbGxX95gxwEtqxDpJgdDzjeGXSRQxh6iiq9enYp44/edit#gid=605465842)

## Artifacts Not Impacted (Even Though It Seems Like They Should Be)
- [Daily accessibility scan for VA.gov static content](https://depo-platform-documentation.scrollhelp.site/developer-docs/daily-accessibility-scan-for-va-gov-static-content) -- References WCAG 2.1, should not be updated to 2.2 because the scan hasn't been updated (and isn't currently running). Something to return to if the scans start again.
- [VA.gov content management system overview](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-gov-content-management-system-overview) -- Checked in with Laura Flannery and Steve Rancour. The accessibility parts of this page are out of date and need a bigger revision. Leaving it alone rather than updating old content that's just going to get rewritten.
- [Add accessibility test cases in TestRail](https://depo-platform-documentation.scrollhelp.site/developer-docs/add-accessibility-test-cases-in-testrail)
   - We will have to determine whether we want to update the TestRail cases (see task below). We no longer mention the TestRail accessibility template in the Collab Cycle but it's still hanging around as a "you can use it if you find it useful" resource. We could either commit to owning this and update it, or we could cut it loose. Probably need to see how many VFS teams are actually using it.
   - **Update:** Determined that it's not worth updating. This hasn't been submitted by any teams as a staging artifact since at least December 2022 and (as far as I can tell) has only been used once in the last calendar year. The TestRail template also has links to outdated documentation in GitHub, which means bringing this up to standard would be a much bigger lift than just adding the new WCAG 2.2 test cases. Recommend deleting it from TestRail.

## Tasks
- [x] Determine whether it's worth updating the TestRail accessibility template
   - **Decision:** Not worth updating 
- [x] Platform website updates
   - [x] [Tools and resources for QA testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/tools-and-resources-for-qa-testing)
      - [Draft Tools and resources for QA testing](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2999713812/49681+-+Tools+and+resources+for+QA+testing) 
   - [x] [QA Product Dashboard guide](https://depo-platform-documentation.scrollhelp.site/developer-docs/qa-product-dashboard-guide)
      - [Draft QA Product Dashboard guide](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2999451671/49681+-+QA+Product+Dashboard+guide) 
   - [ ] ~~[Add accessibility test cases in TestRail](https://depo-platform-documentation.scrollhelp.site/developer-docs/add-accessibility-test-cases-in-testrail) (if necessary)~~
      - Recommend deleting this from Platform website 
   - [x] Change history post and announcement
      - [Draft change history post and Slack announcement](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3013214318/49681+-+Change+history+post+and+announcement) 
- [x] Internal guidance/tooling updates
   - [x] [How to complete an Accessibility review for Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2611511338/How+to+complete+an+Accessibility+review+for+Design+Intent)
      - [Draft How to complete an Accessibility review for Design Intent](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2999713858/49681+-+How+to+complete+an+Accessibility+review+for+Design+Intent) 
   - [x] [How to complete an Accessibility Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2492727318/How+to+complete+an+Accessibility+Midpoint+Review)
      - [Draft How to complete an Accessibility Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2999713889/49681+-+How+to+complete+an+Accessibility+Midpoint+Review) 
   - [x] [How to complete an Accessibility review for Staging review touchpoint](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2059763776/How+to+complete+an+Accessibility+review+for+Staging+review+touchpoint)
      - [Draft How to complete an Accessibility review for Staging review touchpoint](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2999451813/49681+-+How+to+complete+an+Accessibility+review+for+Staging+review+touchpoint) 
   - [x] [Revised Experience Standards descriptive tags](https://docs.google.com/spreadsheets/d/1q6UGLEd8re94B5o69EFDz2HNMHw6WvdAHl46FHYsA9s/edit#gid=500057009)
      - Also updated the [source of truth spreadsheet](https://docs.google.com/spreadsheets/d/1y9hjr9WYqDrTJEAnhDKCAgf4izQ8sOLg511tinAE_jU/edit#gid=500057009) @erinrwhite is using for #76875 
   - ~~[ ] [Drafting Template 2.0 descriptive tags]~~(https://docs.google.com/spreadsheets/d/1dOAJNKYIFQOW5NGNtZ3l0PPEy5MNQHOl0zWEB2cl20E/edit#gid=605465842)
      - Will be updated as part of Erin's work in #76875
   - ~~[ ] [Drafting Template 2.0 - DST descriptive tags]~~(https://docs.google.com/spreadsheets/d/1hMcbGxX95gxwEtqxDpJgdDzjeGXSRQxh6iiq9enYp44/edit#gid=605465842)
      - Will be updated as part of Erin's work in #76875
- [x] VA Design System updates
   - Changes proposed in department-of-veterans-affairs/vets-design-system-documentation/pull/2575 
   - [x] [VADS Button component](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/35d676b3de36453055d271b00599d1711355f7cc/src/_components/button/index.md?plain=1#L119)
   - [x] [VADS Experimental Design Template](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/35d676b3de36453055d271b00599d1711355f7cc/src/_components/experimental-design-template.md?plain=1#L53)
   - [x] [VADS Additional Info component](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/35d676b3de36453055d271b00599d1711355f7cc/src/_components/additional-info.md?plain=1#L100)
   - [x] [VADS component checklist definitions](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/35d676b3de36453055d271b00599d1711355f7cc/src/_data/component-checklist/definitions.yml#L12)
      - Was already updated by DST!

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS-facing guidance references WCAG 2.2
- [x] Internal guidance updated with new WCAG 2.2 checks, and references to WCAG 2.1 updated
- [x] Collab Cycle / VA.gov experience standard reference links and descriptive tags updated for WCAG 2.2

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@briandeconinck feel free to add anything to this. We'll keep it on the backlog as a reminder.

**Comment by briandeconinck** [comment]
Commenting here that I've discussed this with @eli-oat on CAIA since he's in the process of putting stuff together for Martha. I requested (and he agreed, since he's great) that the document outline how new items in WCAG 2.2 will impact:
- The design system and the DST
- What VFS teams build and what we review in the Collab Cycle
- Something/someone else (eg. all the new authentication stuff)

Once Eli has that together, I will update this ticket with appropriate tasks for Collab Cycle and Platform documentation. cc @shiragoodman

**Comment by eli-oat** [comment]
I'm aiming to have this done by end of this week, Friday, Jan. 26.

**Comment by shiragoodman** [comment]
thank you both!!

**Comment by shiragoodman** [comment]
@eli-oat have you received the feedback you were expecting?

@briandeconinck per your earlier comment, are you able to begin updating this ticket based off Eli's draft? I imagine we can start this now and modify if needed.

**Comment by eli-oat** [comment]
@shiragoodman yes, I have now received some feedback. I will update the doc to its final form by the end of this week, Friday, Feb. 9

**Comment by briandeconinck** [comment]
@shiragoodman Ticket description, user stories, acceptance criteria, impacted artifacts, and tasks now updated based on @eli-oat's work. Feel free to make edits as needed!

cc @artsymartha68

**Comment by shiragoodman** [comment]
Per discussions on 2/19, @briandeconinck will determine how many teams and how recently teams have used the accessibility test cases in Test Rail, and will check in with Laura and Steve from Sitewide to see  the impacts of updating the CMS guidance.

**Comment by briandeconinck** [comment]
Chatted with Laura and Steve, moving that CMS page to the "not impacted" list. The accessibility testing section on that page is  out of date and needs bigger revisions, going to leave it alone rather than update something that'll be rewritten.

**Comment by briandeconinck** [comment]
Update: Moved the TestRail test cases to the Not Updated section, and I recommend we delete the TestRail template and delete the page about it on Platform website.

The TestRail tests haven't been submitted by any teams as a staging artifact since at least December 2022 and (as far as I can tell) the template has only been used once in the last calendar year. The TestRail template also has links to outdated documentation in GitHub, which means bringing this up to standard would be a much bigger lift than just adding the new WCAG 2.2 test cases. Doesn't seem worth keeping.

**Comment by briandeconinck** [comment]
@it-harrison I think this is ready for review!

**Comment by shiragoodman** [comment]
@briandeconinck I agree re: your assessment of the TestRail test cases.

**Comment by it-harrison** [comment]
@briandeconinck everything looks good (I approved the [vets-design-system-documentation PR](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/2575))

**Comment by briandeconinck** [comment]
Updates to Platform website are queued up and announcement post is ready for Slack once it's all published. Closing.
