### ISSUE TITLE
[UX] [PRODUCT] Complete Functional Testing/QA of eCheck-in Workflow with Travel Reimbursement

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#49713]
## TO DO
Get test data & access to API in staging
Add 500 and 530 as stations to the allow list (NOTE: it is still TBD on whether we are doing facility or clinic level)

## Resources
[Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/4249)
[Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/2134&group_by=cases:section_id&group_order=asc&display_deleted_cases=0) - See eCheck-in with Travel: MVP
[User Workflow](https://app.mural.co/t/vfscie8528/m/vfscie8528/1667222840454/ada0c417b71c922895f1750cd32d869f6213e129?sender=ud3aa760e30b39bcf436d4473)
 [Presentation wireframes](https://app.abstract.com/projects/ab30c34e-e2f9-4d3e-bb96-3b683b006c24/branches/3c784fa2-f86a-42b7-b1e4-f0fd5f3c1aa3/commits/005790a0202eed0e984eb6e87c8d183d090d945f/files/585436fe-2120-45f4-b4f7-fbae01d258d9/layers/9B61B462-73BA-45CF-ABA4-215FD07B6D5A?collectionId=3e7034be-0a0a-4895-8cf2-246a3d3ecb52&collectionLayerId=11842933-81f3-4651-86c5-220d77e2c649&present=true&preview=false&sha=005790a0202eed0e984eb6e87c8d183d090d945f)

## Tasks
- [x] [Research] Complete the *[Pre-Staging Review Functional Test Run - Research](https://dsvavsp.testrail.io/index.php?/runs/view/4250)* test run 
- [x] [Design] Complete the *[Pre-Staging Review Functional Test Run - Design](https://dsvavsp.testrail.io/index.php?/runs/view/4293)* test run 
- [x] [Product] Complete the *[Pre-Staging Review Functional Test Run - Product](https://dsvavsp.testrail.io/index.php?/runs/view/4294)* test run

**Comment by kellysmith1008** [comment]
5 test users for testing. https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/beneficiary-travel/engineering/test.data.md

**Comment by kellysmith1008** [comment]
Research functional test is complete - blocked on 2nd subtest (info complete and successful travel pay submission) by BTSSS. I demoed the test rail run to the design team. @zach-park is going to live demo the design test rail test with @cgednalske .

**Comment by kellysmith1008** [comment]
Research functional test is complete - blocked on 2nd subtest (info complete and successful travel pay submission) by BTSSS. I demoed the test rail run to the design team. @zach-park is going to live demo the design test rail test with @cgednalske .

**Comment by zach-park** [comment]
@loripusey @kellylein , I found a couple of screens in the steps that were inconsistent with the design (such as font styles and content) in one of the tests. Should I mark the test be marked as passed or failed?

**Comment by zach-park** [comment]
@loripusey, @kellysmith1008, here are the screenshots with annotations:

![step7.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/b1498a99-082c-4910-b511-80c6f71e8839)

![Step 8.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/a41611c0-2227-4f3d-8bc7-3467f42c6263)

**Comment by zach-park** [comment]
@loripusey @kellysmith1008.  
For now, I marked it as failed. Please let me know if that is not right. Thank you!

**Comment by benbrasso-agile6** [comment]
> Back to today's appointments

You can add that into the wireframes. 

You will want to make a FE ticket to work on those other changes.

**Comment by loripusey** [comment]
yes, I would log bug tickets for each of those. I don't know that they are related to the Travel work. Go ahead and pass the tests

**Comment by zach-park** [comment]
@loripusey, all design functional test is completed with exception of the 2nd subtest (as Kelly's research test due to the BTSSS blockage). 
Cc: @benbrasso-agile6 @kellysmith1008 @cgednalske @ytsaoca

**Comment by zach-park** [comment]
@loripusey @benbrasso-agile6 the design test rail is now complete (i.e., including the 2nd subtest).
