### ISSUE TITLE
Establish Graphana Metric Tracking

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#49726]
## Issue Description
Establish metric tracking in Grafana to track successful counts, failures, DMC, etc

---
## Tasks
- [ ] Add counts for tracking statistics
- [ ] Configure Grafana dashboard for those stats 

## Acceptance Criteria
- [ ] Metrics have been established and are ready for use
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
Deprioritizing given audit requirement of #49993

**Comment by ScottyRJames** [comment]
Redundant to Datadog metric tracking
