### ISSUE TITLE
Use VCR for unit tests

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#49729]
## Issue Description
To better replicate external service interactions within our testing suite, it would be ideal to use VCR recordings to play back previous responses and test off of. 

---
## Tasks
- [x] Build appropriate requests that match our use cases
- [x] Record results of the requests
- [x] Replace rspec mocking of requests with using cassettes 

## Acceptance Criteria
- [x] Our debt tests suites use VCR for HTTP interactions
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kjsuarez** [comment]
This ticket was intended to span multiple sprints, 1st as a discovery ticket and then as one denoting code changes.

**Comment by HeatherRienks** [comment]
@kjsuarez & @ScottyRJames  - do we have an idea of how many additional sprints we should plan for? Or,should we break this into a few smaller tickets?

cc: @Tom-Davis

**Comment by ScottyRJames** [comment]
@HeatherRienks I can look to break it up into smaller tickets by service

**Comment by ScottyRJames** [comment]
Ticket was still intended to span over sprints and copay notification and VHA FSR email issues were higher priority

**Comment by ScottyRJames** [comment]
Working on wrapping up PR and documentation, will rollover
