### ISSUE TITLE
Preneeds: Update mail/fax content

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#49723]
## Background
We have been asked by our VA stakeholders to update the content around
mailing/faxing additional evidence for preneeds applications. Here is the new
content:

<img width="1283" alt="Screen Shot 2022-11-15 at 10 59 54 AM (1)" src="https://user-images.githubusercontent.com/13838621/202225979-8ba57526-644f-4c48-a023-3b82923c6dfe.png">

## Tasks
- [x] Update content to reflect requested changes

## Acceptance Critieria
- [x] Content has been updated to reflect requested changes
- [x] A PR is ready for approval/merging

**Comment by jacobworrell** [comment]
Jerek also found the same incorrect Mail and Fax language on the confirmation page that appears after the form is submitted. That information has also been changed.
