### ISSUE TITLE
Determine which external services have downtimes

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#49728]
## Issue Description
Determine which external services have downtimes that would apply towards #26509

---
## Tasks
- [x] Determine which external services have downtimes

## Acceptance Criteria
- [x] Understanding of  which external services have downtimes and update #26509
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
@ScottyRJames is awaiting a response from Mike McDougall from VBS.

**Comment by ScottyRJames** [comment]
DMC and VBS do not scheduled maintenance. If they have upcoming downtimes we will need communication from their team and update pager duty with the window set manually
