### ISSUE TITLE
Discovery for 'BGS::PeopleService::VAFileNumberNotFound'

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#49725]
## Issue Description
Discovery work for #29864

---
## Tasks
- [ ] Determine what is needed to progress #29864

## Acceptance Criteria
- [ ] Have identified action items to resolve #26864 forward
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Rolling over due to priority of [#49993](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49993)

**Comment by ScottyRJames** [comment]
Rolling over due to priority of [#49993](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49993)

**Comment by ScottyRJames** [comment]
This is being captured during initialization of debts service. This is not causing any issues currently due to having a rescue operator and fallback to user ssn. Will want to verify with BGS if this is an expected behavior and if so, handle how it is logged to Sentry (e.g. reduce severity from `error` to `info`)
