### ISSUE TITLE
[FE] Payment info v2: Assist with UAT

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#49737]
## Background
We'll need a developer available to assist with UAT in the event that there are problems and need to troubleshoot.

**As of 11/16, UAT sessions are scheduled for Thursday 11/17, Friday 11/18 and Monday 11/21, with four sessions each day, same times each day:**
1. 9:00 am
2. 10:30 am
3. Noon
4. 1:30 pm

## Tasks
- [ ] Check your calendar to see when all UAT sessions are being held
- [ ] Confirm/accept or decline what you can attend
- [ ] For those you cannot attend coordinate with another dev for backup
- [ ] Attend sessions as planned
