### ISSUE TITLE
[CDP] Configure redirects for legacy medical copays and debt letters

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#49743]
## Issue Description
Configure redirects for legacy medical copays and debt letters.

---
## Tasks
- [ ] Set up redirects for legacy debt page
- [ ] Set up redirects for legacy copay page

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
[IA Ticket with redirect lists](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/debt-portal.md#redirects)

[GH Redirect request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=content-ia-team%2C+ia&template=redirect-request.md&title=Redirect+Request)

**Comment by Dr-Pongo** [comment]
[Submitted redirect ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50159)
