### ISSUE TITLE
Add MHV Basic Auth error code 108

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#49747]
## Description
An additional error (code `108`) needs to be added to the AuthApp error renderings due to an error regarding the My HealtheVet credential when it comes to an `mhv_verified` account and feature gating only `loa2` (which is an MHV Premium account) and above without requiring the user to go through the ID.me verification again.

## Tasks
- [ ] Add code `108` in the `authentication/errors.js` file
- [ ] Update the error content to display how to upgrade from a Basic to Premium MHV account
- [ ] Update the documentation for troubleshooting (include screenshot as well as why it occurs)

## Acceptance criteria
- [ ] Navigating to `{environment}/auth/login/callback/?code=108` will return the appropriate content
  - [ ] Content includes how to upgrade from a Basic to Premium account (VA.gov side)
  - [ ] Content includes link to above content
  - [ ] Content includes how to upgrade from a Basic to Premium account (MHV side)

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
