### ISSUE TITLE
Update QA Orientation slide deck

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#49758]
## User Story
As a VFS team member, I want to know what is expected of me and my team with regards to QA as I complete the QA Orientation session. 

Assignee: @it-harrison 
Peer Reviewer: @CherylEvans 

## Description
The QA Orientation slide deck currently contains information on the following subjects:

- Getting started with QA
- Manual testing and test planning
- End-to-end testing
- Unit testing
- Load testing
- Questions and discussion

While some of this information may still be relevant, the purpose of this ticket it to pivot the QA Orientation slide deck so that it prepares VFS teams for meeting and upholding the QA Standards. 

## Impacted Artifacts
[QA Orientation slide deck](https://docs.google.com/presentation/d/1zK5tcBGHl_J-H0z_Dj8JmCF-ybkFxZYDWt7-8ZU-pE8/edit#slide=id.g115bccfb0f4_0_0)

## Tasks
- [ ] TBD

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] The QA Orientation slide deck is organized to help introduce and prepare teams for supporting the QA Standards

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
Hi @CherylEvans I have a [draft of the revised slide deck](https://docs.google.com/presentation/d/1GURbE15ON6ihxjXqFUjMXOYh8tUEmCrTN4FQPgvf5-c/edit#slide=id.g115bccfb0f4_0_528) when you get a chance to take a look - thanks!

**Comment by CherylEvans** [comment]
@it-harrison Looking at it now. :-)

**Comment by it-harrison** [comment]
thanks @CherylEvans - one question: the link you posted above goes to the old deck as opposed to[ the revised deck](https://docs.google.com/presentation/d/1GURbE15ON6ihxjXqFUjMXOYh8tUEmCrTN4FQPgvf5-c/edit?usp=sharing). Just wanted to make sure you had seen the revised deck.

**Comment by CherylEvans** [comment]
@it-harrison Seems I have been making changes to the old deck.  I never saw your link for some reason.  Let me take a look at the real draft.  I assumed it was the doc from Impacted Artifacts above.

**Comment by CherylEvans** [comment]
@it-harrison I have made edits to the [revised draft](https://docs.google.com/presentation/d/1GURbE15ON6ihxjXqFUjMXOYh8tUEmCrTN4FQPgvf5-c/edit#slide=id.g115bccfb0f4_0_479) with regard to grammar and formatting. 
Please go through the document to ensure that the first use of each acronym is spelled out in this format example: Quality Assurance (QA)>
Please tag me when you're done and I will give it another once-over.  I deleted the last "Thank you" slide because it's not needed.  
Thanks, Ian.  :-)

**Comment by it-harrison** [comment]
@CherylEvans I think I got all the acronyms. Thanks!

**Comment by CherylEvans** [comment]
@it-harrison Slide 26, acronym CD.  Other than that it looks great!! Once that one is done, I am finished with my review.

**Comment by it-harrison** [comment]
@CherylEvans good catch - fixed - thanks for the thorough review!

**Comment by CherylEvans** [comment]
@it-harrison You are quite welcome! :-)

**Comment by it-harrison** [comment]
@shiragoodman I have published the changes to slide deck linked to the orientations session page.
