### ISSUE TITLE
Update and remove VRRAP content—HOLD TO PUBLISH UNTIL 12/11/22

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#49766]
## Issue Description

The VRRAP program will stop accepting new applicants on December 11, 2022. The education team opened an intake request to have us remove all mentions of Form 22-S900 and VRRAP information on various VA pages and to retire the [Veteran Rapid Retraining Assistance Program](https://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/) page. 

Original intake ticket: #49776

To remove:
- Remove the section "Education and training benefits during the COVID-19 pandemic" from the [Other VA education benefits](https://www.va.gov/education/other-va-education-benefits/) page
- Archive the [VRRAP](https://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/) page
- Remove VRRAP from the left nav

We should assess whether we need messaging on the [other VA education benefits landing page](https://www.va.gov/education/other-va-education-benefits/) about the program ending. It may be confusing if someone is looking for it and it's no longer there.

We also need the CMS team to do an audit of VA.gov to learn if VRRAP is mentioned on any other pages. And we need to reach out to Tammy Hurley to remove the mentions on the school administrators page.

We will need to also set up a redirect for the page we're retiring and determine what we should be redirecting to. @heyjoni will help us with this.

**Note that none of these changes can go live until 12/11/22.**

## Tasks
- [x] Remove content from Other VA education benefits page
- [x] Assess if messaging needs to be added to the page about program going away
- [x] Open audit ticket with CMS team (Randi) ([link to ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11647))
- [x] Create redirect ticket ([link to ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11642))
- [x] Notify stakeholder about school administrators page (Randi)
- [ ] Review content changes (Laura)
- [ ] Copyedit (Megan)
- [ ] Publish (Megan)
- [ ] Remove page from left nav

## Acceptance Criteria
- [ ] VRRAP page and mentions are no longer on live site

**Comment by RLHecht** [comment]
Noting here that we also have VRRAP content on the [COVID FAQs](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/#benefit-payments-claims-claim-) page in the question "If I lost my job due to COVID-19, can I get education or job training from VA?" that needs to be changed.

**Comment by laurwill** [comment]
On Other education benefits, I removed the VRRAP content and added an info alert to the top of the page — we chatted with Joni about using an info alert so that this is near the top of the page when folks get redirected from VRRAP page. We can leave this up for 6 months and then remove.

http://preview-prod.vfs.va.gov/preview?nodeId=945 

@RLHecht since Megan is busy with rates, want to review the info alert? That way we can get this off to stakeholders. Also noting that 12/11 is a Sunday, so we'll need to ask if it's okay to publish Monday morning 12/12.

Question: How does this work with redirect timing, since that's not immediate?

**Comment by RLHecht** [comment]
Update: Laura sent content to stakeholders on 12/2.

**Comment by laurwill** [comment]
Terry approved this content and said Monday is fine — we just need to confirm timing of the redirect.

@megzehn these are ready for copyedit/pre-pub ahead of publishing (likely first thing Monday morning):
- http://preview-prod.vfs.va.gov/preview?nodeId=945 (removed VRRAP section and added info alert)
- http://preview-prod.vfs.va.gov/preview?nodeId=3014 (only change was removing the VRRAP question)

**Comment by laurwill** [comment]
Hi @megzehn , Terry approved this new plan — you can go ahead and publish these updates. 

On Monday morning, I'll adjust the alert with the past tense version and tag you to republish.

**Comment by megzehn** [comment]
Thanks, @laurwill! I reviewed and published these!

**Comment by laurwill** [comment]
Hi @megzehn , I updated the VRRAP alert to past tense — could you review and publish? I don't think we need to wait for the redirect to take effect, since it should be past tense now no matter where it's appearing.

We'll also need to remove VRRAP from the left nav. Want to do that at the same time as you publish the alert? Let me know if you want second eyes on the left nav change!

**Comment by laurwill** [comment]
Amazing! I notified the stakeholder. @RLHecht I'm going to go ahead and close this since you're OOO, but noting that for your tracking purposes.
