### ISSUE TITLE
Summarize VBMS Data issue and historical events

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#49761]
## Issue Description
DEPO PO has asked for a summary of our teams involvement in the VBMS Letter issues. 

---
## Tasks
- [x] Outline summary and historical details of VBMS issue involvement

## Acceptance Criteria
- [ ] Send summary to Matt Self
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
VBMS Historical Events

- September 7th, 2022 - Made aware of PII leak within debt letters from VBMS dating back to August 18th and shut down access on the portal
- VODA works to retrieve Veteran identifications that may have downloaded impacted letters. 
-  September 14th – Delivered identity findings including Veteran ICN and EDIPI values to Matt Self
- September 16th – Delivered list of downloaded document IDs over the time period to Jared Mrozinksi and Daniel Smith
- October 7th  - VBMS letters are back available for access on portal 
- October 21st – Aware of another data breach with VBMS letters and access is turned off once again
- VODA investigates depth of VBMS document logs dating back to initial launch in January 2021
