### ISSUE TITLE
Prescribe timing guidance for Change Communication

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#49771]
## Issue Description
Ray spoke about the Feature Toggle issue from this week.

His concern was about the What and When getting adequately communicated from the Platform team to VFS teams

We discussed that our Communication Playbook doesn’t specify times, as historically the idea was to leave that to the fixed technical teams who more expert about the need.  Given that these have changed, prescribing lead-time guidelines is a useful idea.

Here are the times we should consider recommending within the [Guide](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2317647873/Change+Communication+Guide) for use in the VFS-Change-Communications channel:

Additional discussion w/ Jason:
Even if the date gets pushed, the day-before reminder should still suffice, and tamp down on too many updates, (instead of updating about mid-stream changes after the initial announcement).

**- 1 week before launch:  Announce that the change is coming and ask for feedback**
**- 1 day before launch:  Remind users that the change will take place the following business day**
**- Day of Change:  Announce that change has taken place**

## Tasks
- [x] Update Confluence space w/ new guidance
- [x] Schedule message to Platform Teams channel with the new guidance

## Acceptance Criteria
- [x] Confluence page has been updated
- [x] Change has been communicated in Slack
