### ISSUE TITLE
Discovery: Bulkhead requirement gathering 

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#49779]
## Description
As part of implementing bulkhead deployments, we need to fist do some discovery around how we want to tackle this. 
## Tasks
- [x]  Stories are created and a path is defined about how we want to tackle this.
- [x] Meet with tech-team-1 to see if any infra is being changed in vets-api dev
- [x] Meet with tech-team-2 if they will be implementing datadog for VFS teams
- [x] Gather all VFS and VSP (if any) routings 
- [x] Meet with Kyle || COP
  - [x] Input best practice implementation (DS)

## Acceptance Criteria
- [x]  all tasks are completed and we have a clear understanding of how we want to move forward.
- [x] Tasks are documented somewhere (TBD)

## How to configure this issue
- [ ] _Attach a Milestone_
- [ ] _Story points_
- [ ] _Sprint assigned if pulling into sprint_
- [ ] _Epic assigned_
- [ ] _Team label assigned_

**Comment by oseasmoran73** [comment]
New vets-api instance found [here](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/vets-api/dev)

**Comment by oseasmoran73** [comment]
Tech-team-2 priority is currently monitoring/logging for support team. While there is overlap, proposed we meet sometime (most likely are the holidays) to also include potential known/unknown

Jesse will also be meeting with Brian, service design team, to talk about DD for VFS team & potentially having research on things. May be a good opportunity for us to compile a list so we can include as well

**Comment by oseasmoran73** [comment]
I believe I have compiled entire list of routings. Stored locally for the time being (until transferred somewhere internally)

**Comment by oseasmoran73** [comment]
[History](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/752/files?show-viewed-files=true&file-filters%5B%5D=)

**Comment by oseasmoran73** [comment]
Spoke with Lindsey via Slack to show new helm parent-child relationship. File ref found [here](https://github.com/department-of-veterans-affairs/vets-api/blob/parent-helm-charts/chart/templates/ingress_route.yaml)

**Comment by oseasmoran73** [comment]
Here is a thought:

1. Ingress template in vets-api, create another conditional statement underneath to not override what is currently implemented (which we probably could, but for now, lets not mesh with current work that tech-team-1 is doing) -- conditional statement perhaps?
2. In app-manifest, create a new structure with the following information:
  a. `{ service-name, path }` (was initially thinking array, but if developer accidentally appends incorrectly, can cause big no no)
3. Iterate over new section of ingress template in vets-api, and append in `Path({{ .Values.ingress.route.path}})` and `vets-api-{{ .Values.ingress.route.services.service-name }}-web`

**Comment by oseasmoran73** [comment]
Doing some of the implementations stated above (initial work), and it seems like it will get dirty real quick. Path of least resistance would be to append what the current ingressroute template is and go from there

**Comment by oseasmoran73** [comment]
Closing as AC has been met
