### ISSUE TITLE
[FE] My VA 2.0: Verify loading dial behavior

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#49770]
## Background
My VA seems to get stuck in certain scenarios (such as an LOA3 non-Veteran) preventing the page from loading, leaving the user in a permanent "loading dial" state on My VA. The page gets stuck in this case because it's looking for military history to display in the name tag but that information doesn't exist.

We need to do some additional testing/validation to see if there are other scenarios where this will occur and then document the behavior and technical functionality thoroughly. We also need to implement very specific tests in the code to check for these things.

## Tasks
- [ ] Test for scenarios to ensure that the loading bar gets removed based on various access in the claims attribute in profile
- [ ] Write specific tests to catch these scenarios
- [ ] Update technical documentation 

## Acceptance Criteria
- [ ] My VA loads for LOA3 users who are not veterans
- [ ] _potentially additional scenarios/states to add_

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member using an LOA3 non-veteran account
- _How can this work be validated?_ Use an LOA3 non-veteran account to validate behavior (potentially other scenarios as well depending on testing)

**Comment by ajakabcin** [comment]
Closing this - if this becomes an issue later or we see it again we'll revist.
