### ISSUE TITLE
Create Centralized "Status" board of the state of SB's

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#49773]
## Issue Description
Ray asked us to create an initiative to “Centralize” all blueprints, and their status of Complete, In-Progress, Out of date, etc.

Shared the page we setup for existing blueprints User Journeys and Service Blueprints, but wasn't what he was looking for.

Ray said instead he maybe wants a table of all of the services/scenarios we are looking to blueprint, along w/ the status of each.  (What is being worked on and what is complete, is it current).

## Tasks
- [ ] Discuss what to include in this space
- [ ]  Create the space

## Acceptance Criteria
- [ ] Space is created
