### ISSUE TITLE
[BE] Handle 404 'Appointment not found.' error response from BTSSS

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#49786]
## User Story
As a check in experience user, I want to see an appropriate error message when the travel claim returns 'appointment not found'

## Tasks
- [ ] [BE] handle 404 error response from BTSSS

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
