### ISSUE TITLE
Perform Monthly Session Key Rotation for Vets API

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#49783]
## Issue Description
For security, the session keys for vets-api should be rotated monthly, following these instructions - https://vfs.atlassian.net/wiki/spaces/VI/pages/1766621207/Session+Key+Rotation+for+Vets+API

---
## Tasks
- [ ] Update the necessary files in the `devops` repo
- [ ] Update the necessary files in the `vsp-infra-application-manifests` repo

## Acceptance Criteria
- [ ] The necessary files in the `devops` repo have been updated
- [ ] The necessary files in the `vsp-infra-application-manifests` repo have been upated

**Comment by holdenhinkle** [comment]
devops repo PR - https://github.com/department-of-veterans-affairs/devops/pull/12252
vsp-infra-application-manifests repo pr - https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1073

**Comment by holdenhinkle** [comment]
I'll merge this later this afternoon after the deploy, then I'll kick off the autodeploy tomorrow morning around 6am EST. Lindsey told me to do it early in the morning, just in case it affects users' sessions.

**Comment by holdenhinkle** [comment]
PRs were merged. Build was created. I'll kick off auto-deploy in the morning.

**Comment by holdenhinkle** [comment]
I kicked off the deploy and all lights (er ugly Jenkins squares) are green.

This is done. Moving it to review.
