### ISSUE TITLE
Implement better tracking of completed Collab Cycle touchpoints

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#49785]
## User Story
As the Governance PM, I want to show OCTO accurate completion of Collaboration Cycle touchpoints without disrupting VFS teams so that Platform can transition to the Zenhub burndown reports and retire the Google Drive Sprint reports.

Assignee: @shiragoodman 
Peer Reviewer: @CherylEvans 

## Description
OCTO is preparing to switch from Sprint Reports being documented within a Google Drive doc, to Sprint Reports utilizing the Zenhub burn down reports. If/when this takes place, Governance team will need to more accurately show which Collaboration Cycle touchpoints have been completed in the sprint. We'll also need to add story point estimates for better accuracy with the burndown report.

The purpose of this ticket is to modify our operational process for each Collaboration Cycle touchpoint (post-touchpoint) to ensure this information is correctly captured

## Solution
When a VFS team completes a Collaboration Cycle touchpoint, an issue ticket will be created showing the touchpoint was completed. The issue ticket will have:
- Title: Completed: Touchpoint Name - VFS team - VFS product/feature
- Body of ticket: "This ticket is for Platform tracking purposes only. There is no VFS action needed."
- Labels: `governance-team`
- Sprint: Sprint in which the Collaboration Cycle Touchpoint took place
- Estimate:
   - For Kickoff: 1
   - For Design Intents: 5
   - For Midpoint Reviews : 8 
   - For Staging Reviews: 8
- Epics: 
   1. The VFS teams Collaboration Cycle Request ticket
   2. The Governance teams Collaboration Cycle Support epic (currently for FY23-Q1, ticket #47486)

The ticket should be opened and closed the day of the completed Collaboration Cycle touchpoint.

## Impacted Artifacts
[Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)
[Design Intent - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Moderator+Responsibilities)
[Midpoint Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Moderator+Responsibilities)
[Staging Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review+-+Moderator+Responsibilities)

## Tasks
- [x] Update the above impact artifacts to include a step for implementing the Solution
   - Note: DI, MPR and SR should all be in the "post-touchpoint" section. Kickoff should be the final step of the guidance.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Completed Collaboration Cycle touchpoints are captured correctly for the Zenhub burndown report

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@CherylEvans I have created drafts of all 4 guidance docs, available in this [Documentation Drafts](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2434728438/49785+-+Implement+better+tracking) folder. I commented where the new guidance/changes were. 

Let me know if you have any questions!

**Comment by CherylEvans** [comment]
@shiragoodman Will do!  Taking a look at them now.

**Comment by CherylEvans** [comment]
@shiragoodman I had one [question](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2446131241/Copy+of+Midpoint+Review+-+Moderator+Responsibilities) for clarification regarding attaching to epic(s), but otherwise, they look great!

**Comment by shiragoodman** [comment]
@CherylEvans I am going to publish - any concerns?

**Comment by CherylEvans** [comment]
@shiragoodman No concerns whatsoever.  You did a great job laying it all out.  I don't see any issues with publishing.  :-)
