### ISSUE TITLE
Depricate the Questionnaire Appliction from VA.gov

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#49788]
## Description 

The questionnaire app was a prototype that is no longer being tested. To keep the code base clean we will remove the application 

## Tasks

- [ ] remove from registry.json
- [ ] remove from vets-webiste
- [ ] remove database
- [ ] remove module
- [ ] remove anything else from vets-api
- [ ] remove reverse proxy
- [ ] remove redirects
- [ ] document PRs in the docs repo

## links
- https://dsva.slack.com/archives/CBU0KDSB1/p1667835842987949
