### ISSUE TITLE
Create conversation guides

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#49784]
## User Story
As a Governance team member, I want to have a conversation guide for stakeholder interviews so that we can provide consistent interviewee experiences and compare/contrast the resulting feedback.
 
Assignee: @sterkenburgsara @allison0034 

## Description
There is a [Platform-specific template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md) for teams to use for Platform conversation guides. The goal of this ticket is to complete the conversation guide for each type of interviewee, consulting with other teams as necessary.

## Impacted Artifacts

- [Conversation guide: VFS Team Members (recent hires)](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2432172044/Conversation+Guide+VFS+Team+members+recent+hires)
- [Conversation guide: Orientation hosts](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2437546120/Conversation+Guide+Orientation+hosts)

## Tasks
- [x] Analyze any feedback we already have: [platform satisfaction survey](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2194964673/Platform+Satisfaction+Survey), slack searches for "orientation" as keyword and see if that informs any questions we want to ask
- [x] Brainstorm interview questions and come to consensus on 5-8 high level questions to ask (with follow-on questions as needed). [See mural board](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1668743350622/b2bb49216c419d3be2fa8511b28ca828eebbcbb6?sender=u792eff8ef82f499a192a4934)
- [x] Create conversation guide for VFS team members who have recently undergone the orientation process
- [x] Create conversation guide for Platform orientation hosts who regularly offer orientation sessions to new team members

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Conversation guides are complete and has been reviewed/approved by Platform Design Lead (@naomimarcussen )

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by sterkenburgsara** [comment]
@shiragoodman can you look over the bones of this this new user research ticket that I'm moving into this sprint?

**Comment by shiragoodman** [comment]
looks good @sterkenburgsara ! I upped the story points to a 3 as I imagine it will be the same amount of work (similar complexities, similar unknowns) as the research plan.

**Comment by sterkenburgsara** [comment]
@shiragoodman okay, sounds good. I was debating between 2-3 points. Thank you so much!

**Comment by sterkenburgsara** [comment]
@naomimarcussen @allison0034 conversation guides are ready for your review.

**Comment by naomimarcussen** [comment]
@sterkenburgsara I've reviewed and left comments for both conversation guides. Looks great overall!

**Comment by sterkenburgsara** [comment]
@naomimarcussen Great. I see your comments and have implemented all of this feedback. Thank you!

**Comment by sterkenburgsara** [comment]
@allison0034 can you take a final look at these when time allows?

**Comment by allison0034** [comment]
@sterkenburgsara these look great!
