### ISSUE TITLE
[EKS][Bulkhead] Centralized dashboard/monitoring

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#49782]
## Description

For Platform/VFS teams to see overall state of external service/nodes/pods. If an outage were to occur of an service, it will reflect on dashboard accordingly

## Tasks
- [x] Implement Dashboard
- [ ] Determine if more logs need to be added to get correct data

## Acceptance Criteria
- [ ] Dashboard reflects accordingly

## How to configure this issue
- [ ] _Attach a Milestone_
- [ ] _Story points_
- [ ] _Sprint assigned if pulling into sprint_
- [ ] _Epic assigned_
- [ ] _Team label assigned_

**Comment by oseasmoran73** [comment]
Follow [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33081) ; TLDR: 2/21 is when VFS users will begin onboarding to DD

As of now, dashboard exists that outlines how many pods, but not the most "aesthetically pleasing" so might be something to iterate or add more resources on filtering

**Comment by npeterson54** [comment]
Removing tech team 3 label from story as we will not be working on this
