### ISSUE TITLE
Implement HPA bulkhead pattern for routing

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#49781]
## Description
Based on the routing discovered in the #49779 we need to implement HPA for those routes to scale appropriately.
## Tasks
- [x] Modify HPA.yml 
- [x] Based on the discovery, modify those services accordingly 

## Acceptance Criteria
- [x] All routes are updated and working properly 

## How to configure this issue
- [ ] _Attach a Milestone_
- [ ] _Story points_
- [ ] _Sprint assigned if pulling into sprint_
- [ ] _Epic assigned_
- [ ] _Team label assigned_

**Comment by LindseySaari** [comment]
Hi! Just popping in here! I just wanted to add a comment to the ticket for a reminder to create documentation around how the bulkhead deployments work + "How To" instructions for new modules that will be their own deployment or other future bulkhead deployment needs, etc. cc @laineymajor @RachalCassity

**Comment by oseasmoran73** [comment]
HPA is reflecting in Argo. Will spin up ticket for some tickets for some testing as well as some documentation as stated by Lindsey above

**Comment by oseasmoran73** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/53078 created for tracking documentation

**Comment by oseasmoran73** [comment]
Closing ticket given HPA is reflects in Argo. The actual scaling portion will be done in this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49839)
