### ISSUE TITLE
E2E Stress Test not generating GitHub Issues

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#49799]
## Issue Description
The intended functionality of the [E2E Stress Test](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2379120641/E2E+Stress+Test+and+Allow+List) was when a test fails and is disallowed on the allow list, that it would open an issue in [va.gov-team](https://github.com/department-of-veterans-affairs/va.gov-team). This issue creation process would tag the issue with `e2e-flaky-test` and if able to determine the team associated with the test by using the [VFS Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory), it would tag the team as well. However, tests are being disabled and no issues are being created in va.gov-team. This is leading to tests being disabled without notifying anyone, and as such they are not being fixed.

Relevant Links:
[E2E Stress Test Workflow](https://github.com/department-of-veterans-affairs/vets-website/blob/main/.github/workflows/e2e-stress-test.yml)
[QA Standards Dashboard Data Repo](https://github.com/department-of-veterans-affairs/qa-standards-dashboard-data) (handles some of the processing)
[Allow List BQ Table](https://console.cloud.google.com/bigquery?project=vsp-analytics-and-insights&pli=1&ws=!1m5!1m4!4m3!1svsp-analytics-and-insights!2svsp_testing_tools!3svets_website_e2e_allow_list)
[Allow List Changelog BQ Table](https://console.cloud.google.com/bigquery?project=vsp-analytics-and-insights&pli=1&ws=!1m5!1m4!4m3!1svsp-analytics-and-insights!2svsp_testing_tools!3svets_website_e2e_allow_list_change_log)
[Vets Website Test Selection Process](https://github.com/department-of-veterans-affairs/vets-website/blob/main/script/github-actions/select-cypress-tests.js)

## Tasks
- [x] Diagnose and fix the cause of the issues not being created.
- [x] Test that an issue is created correctly by forcing a failure in a test and running the [E2E Stress Test Workflow](https://github.com/department-of-veterans-affairs/vets-website/blob/main/.github/workflows/e2e-stress-test.yml)

## Acceptance Criteria
- [x] Issues are created every time the stress test disables a spec.
---

**Comment by CBonade** [comment]
Did a bit of digging into this today and made a number of discoveries about the current state of this tool:

- It's still working the way it was designed
- The lack of follow-up maintenance has hindered our test suite (currently 43 specs disabled).
- The stress test has been failing due to timeouts for some time now
- The Slack message for it has also been failing due to character limits.
- The allow list is supposed to generate issues 

The first thing I addressed today was opening a PR to shorten the number of times the stress test runs each spec to try and get it under the timeout. We have plenty of room to keep lowering it if it does not fix the problem going from 25x to 20x per test. The PR for this is here: https://github.com/department-of-veterans-affairs/vets-website/pull/22720 just awaiting approval.

Looking further into the issue creation it's unclear why this is only happening sometimes. We have two possible scenarios based on how it's creating the issues. One scenario is there is a team able to be assigned by referencing the VFS Product Directory. The other scenario is when there's no team label so it just labels it as a flaky test. Both of these have succeeded intermittently which points me to possibly an issue on the GitHub side. 

That being said, without a dedicated team to assign these issues to or dedicated people (prior, they were being assigned to the PM and tech lead of QA Standards), I don't know that issues make sense anymore as we cannot get them to the appropriate teams. We also have a page that is regularly published to confluence and a Slack notification that calls attention to the page. The slack notification is currently being delivered to a channel that is no longer monitored (qas-notifications). My proposed solution is:

1) The daily M-F status notification can be moved to the frontend COP channel for visibility.
2) Frontend COP assumes responsibility for routine following up with teams who have not fixed long-disabled test specs
3) We create a cleanup job to address an edge case where test specs that were disabled on the allow list, are removed from the vets-website code, therefore never having an opportunity to be removed from the allow list.

@jhonnyoddball I'd love to chat about this more in depth if more context is needed for the original functionality of the project. I don't know if the additional items would be more appropriate to be part of this ticket, or a separate ticket of their own.

**Comment by CBonade** [comment]
https://vfs.atlassian.net/wiki/spaces/pilot/pages/2372895484/Currently+Disallowed+Cypress+Test+Specs+on+VA.gov

As step 2 of this issue, we decided on adding the team responsible (when able to be assessed) to the platform website page that publishes the allow list. This is the link to the confluence page that drives it, showing the extra column. I also added a timestamp, showing the last time specifically the page was updated, at the request of a VFS team member for clarity on what state of tests the list reflects.

The PR to merge this is here and awaiting approval: https://github.com/department-of-veterans-affairs/qa-standards-dashboard-data/pull/200

**Comment by CBonade** [comment]
The above referenced PR has been merged and a new version of the page will be publshed to platform website today.

**Comment by CBonade** [comment]
Some steps have been taken to improve this process. When looking into why this list was growing and not being addressed, it was found that many of the tests on this list no longer existed, therefore had no way to get removed from the list. I created a script that will run once daily and remove any tests that no longer exist from the list to keep it clean.

Additionally, the page that is linked to in the notification was altered to display the team repsonsible for the failing test if it is able to be determined via the product directory.

This ticket is just awaiting a decision on long term notification destination and/or a long term maintenance plan for following up with teams that do not address their failing tests after a certain time.

**Comment by CBonade** [comment]
The original cause of issues not being created was not able to be determined. No errors seemed to be reported in this process and all the data being sent seemed correct. It is possible there's a permissions error that is not allowing these issues to be created cross-repository. In the event that's the case, we need to have an alternative plan of action for addressing these issues. We've brainstormed a number of ideas, and come up with a few solutions that have been implemented:

A cleanup job has been added to remove test specs from the allow list if their location has moved in vets-website or the file no longer exists. As tests are recorded by file path, them being moved would cause there to be a duplicate entry, with a different file path, one of which no longer exists. This job runs once a day and deletes any entries that are no longer relevant.

Additionally, the team responsible, if able to be determined via the product directory, is now added to the output page. This should help identify repsonsible parties for followup purposes.

The last task we have outstanding is to decide a new home for the notifications, and what the procedure will be long-term for following up with teams who have a test that's been disabled for an extended period of time.

**Comment by CBonade** [comment]
The original cause of issues not being created was not able to be determined. No errors seemed to be reported in this process and all the data being sent seemed correct. It is possible there’s a permissions error that is not allowing these issues to be created cross-repository. In the event that’s the case, we need to have an alternative plan of action for addressing these issues. We’ve brainstormed a number of ideas, and come up with a few solutions that have been implemented:

A cleanup job has been added to remove test specs from the allow list if their location has moved in vets-website or the file no longer exists. As tests are recorded by file path, them being moved would cause there to be a duplicate entry, with a different file path, one of which no longer exists. This job runs once a day and deletes any entries that are no longer relevant.

Additionally, the team responsible, if able to be determined via the product directory, is now added to the output page. This should help identify repsonsible parties for followup purposes.

The last task we have outstanding is to decide a new home for the notifications, and what the procedure will be long-term for following up with teams who have a test that’s been disabled for an extended period of time.

**Comment by JoeTice** [comment]
Comment from @CBonade  (Entering it on his behalf due to ZenHub issues)

The original cause of issues not being created was not able to be determined. No errors seemed to be reported in this process and all the data being sent seemed correct. It is possible there’s a permissions error that is not allowing these issues to be created cross-repository. In the event that’s the case, we need to have an alternative plan of action for addressing these issues. We’ve brainstormed a number of ideas, and come up with a few solutions that have been implemented:
A cleanup job has been added to remove test specs from the allow list if their location has moved in vets-website or the file no longer exists. As tests are recorded by file path, them being moved would cause there to be a duplicate entry, with a different file path, one of which no longer exists. This job runs once a day and deletes any entries that are no longer relevant.
Additionally, the team responsible, if able to be determined via the product directory, is now added to the output page. This should help identify repsonsible parties for followup purposes.
The last task we have outstanding is to decide a new home for the notifications, and what the procedure will be long-term for following up with teams who have a test that’s been disabled for an extended period of time.

**Comment by CBonade** [comment]
The original cause of issues not being created was not able to be determined. No errors seemed to be reported in this process and all the data being sent seemed correct. It is possible there’s a permissions error that is not allowing these issues to be created cross-repository. In the event that’s the case, we need to have an alternative plan of action for addressing these issues. We’ve brainstormed a number of ideas, and come up with a few solutions that have been implemented:

A cleanup job has been added to remove test specs from the allow list if their location has moved in vets-website or the file no longer exists. As tests are recorded by file path, them being moved would cause there to be a duplicate entry, with a different file path, one of which no longer exists. This job runs once a day and deletes any entries that are no longer relevant.

Additionally, the team responsible, if able to be determined via the product directory, is now added to the output page. This should help identify repsonsible parties for followup purposes.

The last task we have outstanding is to decide a new home for the notifications, and what the procedure will be long-term for following up with teams who have a test that’s been disabled for an extended period of time.

**Comment by CBonade** [comment]
https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/47937

Ticket to cover moving of the notification covered here. This is done.

**Comment by pjhill** [comment]
@CBonade -- When you get a moment, would you please add some details about how this ticket was resolved. Are there any relevant PRs? Docs updated? Anything tried and failed?
