### ISSUE TITLE
Set up config file in DevOps

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#49804]
## Issue Description
In order to retrieve the default configuration for preview environments, we need to create and store the settings in a configuration file in a commonly accessible repository where infrastructure code is often stored such as `devops`.

See gray-colored section in the top left corner of [this mural board](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1667317702925/3fb899bacd4392745957638f2e3d74be0491899c?sender=6b32c5a3-83bd-4063-a4c5-50af2aabe608).

---

## Tasks
- [x] Determine where to store the configuration file -- `devops` repository seems good
- [x] Create a configuration file schema
- [x] Create the config file
- [x] Merge the config file pull request to main
- [ ] Verify the config file is available. It can be retrieved with automated processes from GitHub Actions

## Acceptance Criteria
- [x] A config file containing preview environment defaults exists in the `devops` repository `main`

**Comment by JoeTice** [comment]
![SystemArchDiagram_2022-12-02_19-41-49.png](https://images.zenhubusercontent.com/5f8def8722a02916623f5de1/914a80e7-5706-48c8-b54d-710920de99ee)

Diagram of currently expected attributes to the config file

**Comment by cyriltech** [comment]
I have created a config.json file in the Devops repo, below is the URL "https://github.com/department-of-veterans-affairs/devops/blob/Feature/config/config.json"
Please validate the Schema and provide the default values.

**Comment by pjhill** [comment]
Thanks for the update! I'll record my informal feedback via DM about the initial draft here for future reference --

1. I understand why you split dev and staging out into different objects, but for the defaults, we won't need staging and dev objects within the config. that can be an attribute like `hostingEnvironment` with the default value of `dev` as you have in the dev object already
1. You can find the git repository URLs by searching those repo names in the DSVA org
1. The commit SHA probably doesn't need to be specified at this point as I don't think we'll have a cause to use it for MVP, so that value can be anything like HEAD
1. For test data, the test-harness object can probably consist of two attributes, userdata and enabledServices

**Comment by pjhill** [comment]
Merged! Thanks for knocking out this task. We may need to iterate on the config file specs in the future, but we have a starting point!
