### ISSUE TITLE
Create workflow to create front-end Docker image and store in ECR

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#49807]
## Issue Description
In order to always have an up-to-date image of the current state of `main`, create a new GHA workflow in `vets-website` and `content-build` triggered by a merge to main event that creates a new Docker image for the front-end. The workflow will need to store the new Docker image as the "front-end-latest" in ECR.

---
## Tasks
- [x] Create a new GHA workflow present in `vets-website` and `content-build` that executes when a merge to main event occurs within the repository
- [x] Create a Docker image that contains the latest code from `main` for both `content-build` and `vets-website`
- [x] Store the Docker image in ECR in the `front-end` repository using the name `front-end-latest`

## Acceptance Criteria
- [ ] The latest code merged into main for `content-build` and `vets-website` is available from the `front-end` repository in ECR

**Comment by pjhill** [comment]
FYI, Curt is working on creating a scaffold of the workflow(s) that will be triggered by the PR creation event and kickoff the deployment.

https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/department-of-veterans-affairs/va.gov-team/49805

**Comment by rmessina1010** [comment]
Working on  docker image (not GHA workflow; will eventually need to coordinate with Curt).

Initial attempt here:
https://github.com/department-of-veterans-affairs/vets-website/pull/22928
(am attempting to reverse engineer the vets-website image we currently use for testing to create one that more closely conforms to our needs)

**Comment by rmessina1010** [comment]
Working on  docker image (not GHA workflow; will eventually need to coordinate with Curt).

Initial attempt here:
https://github.com/department-of-veterans-affairs/vets-website/pull/22928
(am attempting to reverse engineer the vets-website image we currently use for testing to create one that more closely conforms to our needs)

**Comment by rmessina1010** [comment]
Working on  docker image (not GHA workflow; will eventually need to coordinate with Curt).

Initial attempt here:
https://github.com/department-of-veterans-affairs/vets-website/pull/22928
(am attempting to reverse engineer the vets-website image we currently use for testing to create one that more closely conforms to our needs)

**Comment by rmessina1010** [comment]
I have created a separate Dockerfile and docker-compose, so far it looks promising in that the image builds, however the container starts, but does not yet run successfully, with the following error:
` [dumb-init] script/preview-env-entrypoint.sh: Permission denied`

**Comment by cyriltech** [comment]
Docker image build and push successfully for vets-website
PR to merge [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/23019) 
GHA workflow for content-build is in progress

**Comment by cyriltech** [comment]
Docker image build and push successfully for vets-website 
Docker image build and push successfully for content-build
All codes validated and merged with main.

**Comment by cyriltech** [comment]
ref [vets-website](https://github.com/department-of-veterans-affairs/vets-website/blob/main/.github/workflows/build.yml)

ref [content-build](https://github.com/department-of-veterans-affairs/content-build/blob/main/.github/workflows/build.yml)

**Comment by rmessina1010** [comment]
I tried a different approach, starting from nearly scratch instead basing my docker file on the RI docker file that’s currently in use.  I still  start with the same node image, but  checkout  copy the source code  then clone directories directly from GitHub ( for now) and I basically follow the setup up instructions from here:
https://depo-platform-documentation.scrollhelp.site/developer-docs/setting-up-your-local-frontend-environment

I tho it’s still not working as desired,  I have progressed much further using this method.

• The first difficulty I encountered was the process stoping  (with exit code 137, which is an out of resources error.) This was similar to what we encountered setting up Tugboat (vets-website is a resource  intensive build!). 
THE SOLUTION  to this was to allocate more resources via the CLI :
sudo docker run --memory="16g" --memory-swap=“4g" -p 3001:3001 <image-name>
or by adjusting setting in the docker app. 
This is something we may need to look into further once it is put on the cloud. Please note that 16GB and 4GB are the max resources my laptop allows.

After this, web pack build ran to completion, altho  I still get a strange behavior “localhost didn’t send any data”  but if I use the navigate back then forth button I can see the vets-website  spinner only. To me this indicates a glitched, but functioning build process.

**Comment by pjhill** [comment]
I think this probably can't be called ready for review quite yet. We have the workflow in place to build and store the Docker images -- thanks Cyril! -- but, we are still working on getting a image that contains a functional Dockerized front-end.

**Comment by rmessina1010** [comment]
In an attempt to expose  vets-website from inside the container  I used the following  CLI command: 
` docker run -it  -p 127.0.0.1:3001:3001 -e BIND_ADDR=0.0.0.0:3001 simple-test`
While  this  does change the  host port, it did not succeed in exposing `vets-website` as expected
```

            "Ports": {
                "3000/tcp": null,
                "3001/tcp": [
                    {
                        "HostIp": "127.0.0.1",
                        "HostPort": "3001"
                    }
                ]
            },
```

**Comment by rmessina1010** [comment]
https://github.com/department-of-veterans-affairs/vets-website/commit/dd37b83e3babf4d9beab3273a32ca7af78d43b72

Resolves the issue with  exposing ports.  The solution was to change the IP that the server script, the one  used by the docker container, to 0.0.0.0;  this was  done in the CMD part of the dockerfile  by passing --port=3001 --host=0.0.0.0

The PR  now has a working dockerized version of  the vets-website ( apps)  repo. 
Content build and Drupal cache remains  to be  integrated,  to I expect to be able to use the same methods.

**Comment by pjhill** [comment]
Neat! Works for me with a -- 
`docker build -f Dockerfile-PE-simple.Dockerfile . -t simple-test:latest`

followed by a --
`docker run simple-test:latest -p 3001:3001`

**Comment by rmessina1010** [comment]
https://github.com/department-of-veterans-affairs/vets-website/commit/5e04081ccaa2210b46bd5228ca96853eb3b1690c
This  commit adds content-build and drupal cache. 
The run command  should reflect the change in ports.
`docker run simple-test:latest -p 3002:3002`

There  is still an issue  with downloading assets during build. eg.:
`Error while fetching http://main-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/sites/default/files/2022-11/Engagement-Determination%20Checklist_508_0.pdf. FetchError: request to http://main-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/sites/default/files/2022-11/Engagement-Determination%20Checklist_508_0.pdf failed, reason: connect ECONNREFUSED 127.0.0.1:2001 Retries remaining: 1`

I am not 100% sure, but this maybe because the asset protocol URL uses http instead of https.

**Comment by cyriltech** [comment]
Per @JoeTice this ticket should be move to review and sub tickets created for content-build and drupal cache

**Comment by pjhill** [comment]
Given that we reduced the scope of this ticket to just be `vets-website` -- we can close this one out now.  Thanks for taking it this far, Ray!

I will create a new ticket for adding `content-build` and Drupal cache into the FE Docker image.
