### ISSUE TITLE
Staging Review [Sitewide homepage - Redesigned homepage]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#49802]
### VFS team name

Sitewide

### Product name

VA.gov Homepage

### Feature name

Redesigned homepage

### GitHub label for product

`VA.gov homepage`

### Staging Review - redesigned homepage

<details>
  <summary>Toggle Staging Review - redesigned homepage </summary>

# NOTE
This template is being deprecated. If your kickoff meeting took place after May 26, 2022, you should be following the guidance specified in the Collaboration Cycle Rquest per the [May 26, 2022 change history post](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Change-history.1846870032.html) instead. If you are unsure if this applies to you, please reach out to the Governance Team on the vfs-platform-support Slack channel.

# Steps to complete Staging Review

## Before meeting

**VFS Product Manager**
- [x]   Create this issue and schedule meeting via Calendly (you are responsible for adding the VFS attendees).
- [x]   Notify the Collaboration Cycle team of this ticket and scheduled date/time in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).
- [x]  Add artifacts listed below to the ticket at least 4 days before scheduled meeting.
- [x]  Ensure you've provided staging access information for the tool or feature. (Don't put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.)
- [ ]  If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the experimental-design label and schedule a meeting with DSC to present the research findings.
- [x]  Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory)

 **Platform**
 
- [x] Add the Platform reviewers to scheduled meeting
- [x] Add Zoom information to scheduled meeting: **December 15 @ 1:30pm ET**
- [x] Create feedback tickets and link them to the Staging Review epic 

## After meeting

**VFS** 
- [ ] Respond to Platform feedback tickets.
- [ ] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.
- [ ] Update Staging Review ticket with the product’s launch date after it has gone live.
- [ ] Close Staging Review ticket when the review is complete and the product has launched.
- [ ] Communicate any and all known Accessibility issues that are not addressed prior to launch to the VA 508 Office via [Audit Request](https://depo-platform-documentation.scrollhelp.site/developer-docs/Instructions-for-VA-508-Office-document-review.1857913061.html#HowtorequestsupportfromtheVA508Office-AuditRequest). 

**Platform**

- [x] Zoom recording: https://oddball-io.zoom.us/rec/share/xPRvRSOdVGuluJVyvy2mSf3BAhtnyD1nm5NLhjcC9wZooBuKMTdGDeo3wo9SqXxu.XAabiarAZxW4TiLM
Passcode: =60A&.#m

## Artifacts

Provide links or documents for the following: 
- **this review excludes the modal designed to redirect users to experience the redesigned homepage (which will be the subject of a staging review on 12/22)**
- [x] Staging URL and staging test-user information
       - no test-user information is needed for this unauthenticated experience 
       - url: https://staging.va.gov/new-home-page/
- [x] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/home-page-redesign-initiative/initiative-brief.md)
- [x] [Release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/home-page-redesign-initiative/release-plan.md) with the "Planning" sections completed 

### Content artifacts 

- [x] Your product’s content source of truth
       - Drupal for benefit promo, news promo, link menu and other search tools menu
- [x] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
      - [Super Epic- VA.gov Homepage redesign#40845](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/40845)
      - [CMS Epic: Harden Homepage design refresh for production launch department-of-veterans-affairs/va.gov-team#8877](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/8877)

### QA artifacts

[Learn more about QA test plans](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [x] Product test [cases](https://dsvavsp.testrail.io/index.php?/runs/view/4311&group_by=cases:section_id&group_order=asc&group_id=8662)\*/test [plan](https://dsvavsp.testrail.io/index.php?/plans/view/4309) in TestRail with test execution logs 
- [x] [Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/385)
- [x] [Summary for References (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/387) [Summary (Defects) report generation still erroring-out in TestRail]
- [x] [Regression test cases in Testrail](https://dsvavsp.testrail.io/index.php?/suites/view/1260/&group_by=cases:section_id&group_id=8677)

\***C16773 Hero portraits** [default Hero-content] test-case not run &mdash; we have PACT-Act promo-content there, covered with **[C16778 Benefit promo](https://dsvavsp.testrail.io/index.php?/cases/view/16778)**.

### Accessibility artifacts 

- [x] Completed accessibility testing artifact department-of-veterans-affairs/va.gov-team#50360
- [x] List of known issues:

Issue | Status
--- | ---
Duplicate HTML ID tag [#11747](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/11747) |  RESOLVED as of 12/7 |
[Bug] Redesigned Homepage (R3) - Email sign-up - No invalid-input error-display [#50624](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50624)|  RESOLVED as of 12/13
[Bug] Redesigned Homepage (R3) - Search box - Spaces-only query triggers search & inaccurate error-message [#50583](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12073) | This behavior can be recreated with the Search component in the header and with the component on the Search page itself. This will be moved to the Public Websites board and addressed holistically there.
[Bug] Redesigned Homepage (R3) - Account Sign-up - Learn-more link broken [#50578](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50578) | PENDING - This page is not yet available in Resources and Support so the link is not in place but expected to be available soon. I will keep this open so we can confirm once the URL is in place.

## Scheduling

- Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses. 
- Click Schedule Event

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Staging Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) on Platform website for more information about the Collaboration Cycle.

 FYI: @shiragoodman

 </details>

### Staging Review - MODAL
<details>
  <summary>Toggle Staging Review - modal</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [x] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [x] I confirm the environment is available and test users have been provided.
- [x] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
 
**Staging Review artifacts**
  
Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts)
  
Provide links or documents for the following: 

- [x] Staging URL and staging test-user information
       - **this review is limited to the modal designed to redirect users to experience the redesigned homepage (which was the subject of the staging review on 12/15)**
       - no test-user information is needed for this unauthenticated experience 
       - url: https://staging.va.gov/new-home-page/ -- ***Clarification: the modal is present at https://staging.va.gov/***
- [x] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/home-page-redesign-initiative/initiative-brief.md)
- [x] [Release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/home-page-redesign-initiative/release-plan.md) with the "Planning" sections completed 

### Content artifacts 

- The soft-launch modal content is hard-coded

**QA artifacts**

[Learn more about QA artifacts](https://depo-platform-documentation.scrollhelp.site/developer-docs/Quality-assurance-artifacts.1906999390.html)
- [X] [Modal-specific use cases in GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/home-page-redesign-initiative/modal-use-cases.md)
- [x] [Modal-specific test cases/test plan in TestRail with test execution logs](https://dsvavsp.testrail.io/index.php?/cases/view/30974&group_by=cases:section_id&group_id=8662&group_order=asc&display_deleted_cases=0)
- [ ] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/392)
- [ ] [Summary (Defects) reports in TestRail](https://dsvavsp.testrail.io/index.php?/reports/view/391)
       -  QA testing of the RI last week surfaced 2 defects, which are documented below in the Known Issues table

**Accessibility artifacts**
  
- [x] Completed accessibility testing artifact - [#50684](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50684)

### Known issues
Issue | Status
--- | ---
Modal collisions [#49518](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49518) | A pre-existing potential for competing modals (including Medallia intercept) has been noted but the impact is not limited to this redesigned homepage experience modal. It is being investigated as a global issue. The conflict will be a temporary issue related to the redesigned homepage during the soft-launch phase only
Modal is re-displayed upon returning to current/existing homepage using Back button [va.gov-cms-#11978](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11978) |  Closed
Modal styling [va.gov-cms-#11979](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11979) | Closed. Observed discrepancies were due to designs which had not been updated in Sketch 
Homepage modal: Using a screen reader when closing modal announces header before skip link [va.gov-cms-#12008](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12008) | In progress
Homepage modal: manage focus on modal close / skip link [va.gov-cms-#12045](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12045) | In progress
Update component-library version to 13.5.1 to resolve homepage modal / megamenu z-index collision [va.gov-cms-#11975](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11975) | Closed

  
##### Platform actions
- [x] Follow Moderator Responsibilities guidance for Staging Review
- [x] Meeting date/time: **12/22/22 at 2:00 EST**
- [x] Create feedback tickets and link to this epic
  - [x] Design feedback provided
  - [x] Accessibility feedback provided
  - [x] IA feedback provided
  - [x] Content feedback provided
  - [x] QA feedback provided

##### Platform actions

- [ ] Update this ticket with the Zoom recording
  - Recording URL: [Zoom recording](https://oddball-io.zoom.us/rec/share/v4iCHZOL8BkL050V-BlodNZ1RTXYq8vh8lzSDOaepBndtbNG4GbTt6GmBIpfJ92H.NCa4mIFdxt1egRzn)
  - Password: K+.Rf236
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

**Comment by mmiddaugh** [comment]
Scheduled for 11:30am - 12:00pm MT, Thursday, December 15, 2022

**Comment by shiragoodman** [comment]
FYI @mmiddaugh the Staging Review artifact section has been updated to reflect the new accessibility testing artifact. thanks!

**Comment by tlei123** [comment]
QA test-runs now done.  Test-cases & test-plan links updated above in main description.

Once reports are successfully generated in TestRail, I'll also update the report links.

cc @mmiddaugh

**Comment by tlei123** [comment]
[Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/385) generated successfully.  Link also updated above in main description.

**Comment by tlei123** [comment]
QA Summary (Defects) report generation still erroring-out.  Just started a third one [see [Reports page](https://dsvavsp.testrail.io/index.php?/reports/overview/56) in TestRail].  :::fingers crossed:::

cc @mmiddaugh

**Comment by wesrowe** [comment]
Note that the modal is now available in Staging: staging.va.gov. Url is updated in the artifacts section above.

**Comment by wesrowe** [comment]
Update for modal staging review tomorrow – we are just now adding a staged rollout approach to our soft-launch modal. Will discuss tomorrow.

Also, TestRail artifacts are being updated momentarily.

**Comment by jilladams** [comment]
Modal Staging Review feedback: 
* QA: no feedback
* 508: 3 issues
  1. Launch blocking: #51155 , aka https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12008. @laflannery @briandeconinck to discuss offline, as this may not be within our purview to fully fix.
  2. Not launch blocking: #51142 . After tabbing through all modal elements, focus goes back to the X to close BUT in the background: entire homepage auto scrolls to the footer. If you then click X to close, page jumps back to page top. _Should_ fix if possible. 
    * **AR:** cut tracking ticket in CMS repo 
  4. Not launch blocking: #51161 . On Mac, shrink browser <576px, zoom to >=175%, link text overlaps chevron on new home page CTA. 
    * Might be due to link within modal, which is not a common pattern. 
    * Might be a design system issue. @briandeconinck to confirm whether this is ours or a design system issue. 
    * Low sev, edge casey, backlog item.

**Comment by shiragoodman** [comment]
linking [Midpoint Review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48041) for reference

**Comment by jilladams** [comment]
The homepage has launched. Closing.
