### ISSUE TITLE
Write dynamically generated environment definition to app manifest

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#49809]
## Issue Description

In order to trigger the deployment of the resources required for a preview environment, we need to assemble the preview environment definition based on user inputs and write the definition to the app manifest.

Givens:
* It may be possible to introduce conflicts if, multiple workflows kick off at close enough times where the commit from the first workflow to trigger has not yet resolved. For example,
   1. Both workflows have `app_manifest_v1` in their input
   1. Workflow1 attempts to append `app_manifest_v1` with its PE
   1. Workflow2 attempts to append `app_manifest_v1` with its PE
   1. Git sees a merge conflict when Workflow2 pushes the commit
   1. Now what?
* It may be necessary to develop a queueing mechanism to avoid conflicts when multiple automated processes attempt to commit to `main`

---
## Tasks

- [x] Create an integration for GitHub Actions to write the preview environment definition to the app manifest file in `vsp-infra-application-manifests`

## Acceptance Criteria

- [x] Preview environment deployment GitHub Action workflow contains an integration with the repository containing the app manifest
- [x] The workflow commits directly to `vsp-infra-application-manifests` `main` app manifest

**Comment by CBonade** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/12426 The PR is open here for writing the GHA-driven values to the values.yaml file and pushing it accordingly. This utilizes our alternate approach we discussed of having a file per environment, to keep everything neat and tidy. The filenames follow the convention of values-[source_repo]-[branch_name].yaml. This will make them easy to associate with the URLs (that follow a similar pattern), easy to decommission, and easy to search as necessary if desired.

The next step will be figuring out the method of looping those files in the deployment yaml for ArgoCD. Bumping the estimate on this ticket as after our discussions the scope of it has changed to include some deployment reworking.

**Comment by pjhill** [comment]
Hooray for pod annotations -- this is a good framework to build on as we need it!
