### ISSUE TITLE
Scan for existing docker images

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#49806]
## Issue Description
When possible, the preview environment workflow should re-use Docker images. For example, if a back-end Docker image is still current to `main` and the new preview environment needs to use `main` then the deployment workflow re-uses the image instead of creating a new one that contains identical back-end code.

---

## Tasks
- [ ] Create a mechanism that operates within GitHub Actions to scan AWS ECR for images and image characteristics
- [ ] Create logic that evaluates whether an existing image can be re-used for the new preview environment
- [ ] Create logic that causes the existing re-usable image to be used for the creation of a new preview environment

## Acceptance Criteria
- [ ] When a new preview environment is created, if an existing Docker image can be re-used for the portion of the preview environment without new code then the preview environment is built with the re-usable image

**Comment by pjhill** [comment]
I believe this is OBE due to design changes in other tickets.

**Comment by pjhill** [comment]
Since we have a workflow that will be rebuilding the `latest` image for a FE and a BE whenever a branch is merged to main, we will not need to attempt reuse of images. The changed "half" of the instance will always be rebuilt, and the unchanged "half" will always use the `latest` image.
