### ISSUE TITLE
Create new Q&A about sign-in

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#49814]
## Issue Description

The chatbot team opened an intake request for the content team to create a page about the importance of having a VA.gov login via one of the four sign-in account providers, as well as the differences between them. After discussion with Danielle, we determined we'll need to determine whether we should create 2 new R&S Q&As or one R&S Q&A with this content.

- The 4 different sign-in options and the benefits of using any of these to sign in to VA.gov.
- Why a Veteran should create an account sign in to VA.gov.

Original intake request: #49575

## Tasks
- [x] Create Q&A or page about different sign-in options and/or an additional page about why to create an account (Aliyah)
- [x] Review Q&As (Laura)
- [x] OCTO-DE review (Danielle)
- [x] Copyedit (Megan)
- [x] Send to chatbot product team (Aliyah)
- [x] Send to homepage team (Aliyah)
- [x] Publish (Megan)

## Acceptance Criteria
- [ ] (2) new Q&A(s) are live on the site

**Comment by aliyahblackmore** [comment]
Hi @DanielleThierryUSDSVA - my drafted page about why someone should create an account and the four different sign in options is ready for you to review. As we discussed yesterday, I decided to make this one page and included additional comments and questions in the document. 

I look forward to chatting more about this. My plan is to continue to work through the chatbot content ready for review from their team as well as draft up some content about this new page.

[Why should I create an account_AB_11.28.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10126088/Why.should.I.create.an.account_AB_11.28.docx)

**Comment by aliyahblackmore** [comment]
Just noting here that the sign in doc is here: 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/49815#issuecomment-1341367618

**Comment by aliyahblackmore** [comment]
Updating: Just noting that there seemed to be a glitch with the sharepoint doc earlier this afternoon. Comments were not appearing (though tracked changes were). I restored to the last edited version (Wednesday afternoon) and comments are showing again.

**Comment by aliyahblackmore** [comment]
**Update 12/13:** Danielle and I will chat with John tomorrow (12/14) and flag a few questions that we have (I compiled these today). 

I resolved some of our comments on the SharePoint doc, made a few more edits, and added the content to Drupal.

**This is the Drupal preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=51915

**Comment by aliyahblackmore** [comment]
Hi @megzehn! This new Creating an account to sign in to VA.gov page is ready for you to copy edit. When you're done with the copy edit, let me know and I'll confirm when we should publish. Either tomorrow or early next week! 

**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=51915

**Comment by megzehn** [comment]
Thank you, @aliyahblackmore! I finished my copy edits, and the page looks good!

http://preview-prod.vfs.va.gov/preview?nodeId=51915

@DanielleThierryUSDSVA , I've left this in drafts for now, but let us know if you'd like us to publish. Thanks again!

**Comment by aliyahblackmore** [comment]
Thank you @megzehn ! We'll plan to publish this by EOD tomorrow (12/16) or on Monday morning (12/19).

And to keep track here, confirming that I've done these things: 

1. Passed this to Michelle (on the home page team) via the sitewide homepage slack  channel. 
2. Passed this to John via email 
3. Passed to the chatbot team via the [original intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49575).

In my messages I summarized for why we created this page ( to meet chatbot and homepage needs) and I let the chatbot folks know that we can publish single Q&As, if needed. 

I'll circle back with the publish date details.

**Comment by megzehn** [comment]
Thanks, @aliyahblackmore! Confirming that this has been published!

**Comment by RLHecht** [comment]
This page is now live. Closing ticket!
