### ISSUE TITLE
Add research findings to collab cycle ticket

### ISSUE THREAD

**Issue by mikeprusaitis** [department-of-veterans-affairs/va.gov-team#49818]
## Description
We need to add write up our research findings following the [Collaboration Cycle guidance](https://depo-platform-documentation.scrollhelp.site/research-design/research-synthesize-and-share). Here's the [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist#ResearchChecklist-7.Shareyourfindingswithcolleagues).

## Tasks
- [x] Review [template for writing research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/sharing-research/research-findings-template.md)
- [x] Make a copy of the template and add to our repository – [Login.gov Adoption Discovery Research Findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/research/discovery/login.gov%20adoption%20discovery%20research%20findings.md)
- [x] Add goals, questions, methodology
- [x] Add hypotheses and conclusions
- [x] Add findings
- [x] Add recommendations
- [x] @tygindraux share for review by @samarawa @kit-casey 
- [x] Update the research repo board
- [x] Is there anything else we need to do to ensure we've followed the Collab Cycle guidance and close this ticket? @mikeprusaitis

**Comment by pscruz** [comment]
I see this Epic @tygindraux

**Comment by tygindraux** [comment]
@elizabethkochBT – Should this be an epic or should we update this to an issue?

**Comment by tygindraux** [comment]
Here's our research findings document (copied from the template): https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-product-team/research/discovery/login.gov%20adoption%20discovery%20research%20findings.md
