### ISSUE TITLE
Modify CI workflow to dispatch a new common back-end workflow

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#49811]
## Issue Description
Create an additional action in the CI workflow in `vets-api` that dispatches a new “common back-end workflow”, passing the common workflow information including `vets-api` branch, `vets-api-mockdata` branch, and the source repository. Dispatch the `devops` workflow to define the preview environment and request deployment.

---
## Tasks
- [x] Add an additional action to the CI workflow in `vets-api`
- [ ] Add an additional action to the CI workflow in `vets-api-mockdata`

## Acceptance Criteria
- [x] The CI workflow in `vets-api` dispatches a common back-end workflow once the CI checks have passed
- [ ] The CI workflow in `vets-api-mockdata` dispatches a common back-end workflow once the CI checks have passed

**Comment by CBonade** [comment]
Here's the PR for the vets-api workflow (just awaiting approval): https://github.com/department-of-veterans-affairs/vets-api/pull/11380 

Discussing this as a team we decided that the mockdata repo does not need a PE every time the content is updated, so we decided to exclude that from this ticket. If that decision is changed later, it's an easy update that can be done on the fly.

**Comment by pjhill** [comment]
Yeah, this is correct. We do not need to create a deployed preview environment for updates to the `vets-api-mockdata`. No user requested this, and it does not seem useful per our discussions.
