### ISSUE TITLE
ArgoCD configured to read app manifest changes and deploy

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#49810]
## Issue Description
When the application manifest for preview environments is updated to include specification for a new preview environment, we need ArgoCD / EKS to detect that change and immediately begin the process of deploying the specified preview environment.

For reference, the proof of concept of an ArgoCD defined application deployed to EKS is [here](https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/department-of-veterans-affairs/va.gov-team/49343).

App manifests are stored in the [vsp-infra-application-manifests repo](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests).

Givens:
* It is not possible to auto-merge a PR due to organization settings which we can't change
* We will need to commit manifest changes directly to main as a result of ^^
* Multiple workflows attempting to commit manifest changes to `main` will execute at the same time
* An automated process that removes a preview environment specification from the app manifest will also be committing manifest changes directly to `main`

We need to understand how the `vsp-infra-application-manifests` repository will respond to automated processes committing manifest changes to `main` simultaneously.

---
## Tasks
- [x] Document the process for updating the app manifest so that new resources are deployed
- [x] Use the dynamic URL creation logic designed in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50149) to assign the preview environment a URL
- [x] Configure ArgoCD to deploy app manifest changes to the correct VPC (`vagov-dev`)
- [x] Create a Confluence document that summarizes the analysis of ArgoCD and how it might work with a GHA that alters the application manifest. Include a recommendation for how to proceed with using application manifests to create each PE as an independently functioning instance within the "PE app".

## Acceptance Criteria
- [x] A document describing the process by which PEs are deployed within ArgoCD is available in our team Confluence space
- [x] A document describing the analysis of how ArgoCD can work in concert with GHA to deploy independently operating VA.gov preview instances within a single "PE app"

**Comment by JoeTice** [comment]
Blocked due to AWS access

**Comment by pjhill** [comment]
@cyriltech -- now that you have AWS access are you able to verify that ArgoCD is configured correctly in accordance with the aspects described in the ticket?

**Comment by cyriltech** [comment]
I'm creating a new application and branch for testing purposes, and if everything goes well, I'll implement it with the main branch.
waiting for write access to the repo.
@Curt Bonade is working on task 2 to assign preview environment a url

**Comment by pjhill** [comment]
Sorry @cyriltech , did we ever resolve your permissions issue with `vsp-infra-application-manifests`? Or, was the permission issue with `devops`?

**Comment by pjhill** [comment]
Thanks for all the effort spinning up research on this fairly specific need for the PE system. I think we have what we need documented in these two Confluence docs.  In a future effort, we will need to have a brainstorming session with others on the team in order to make sure the details are all here and there are no issues.
