### ISSUE TITLE
Modify CI workflows to dispatch a new common front-end workflow

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#49812]
## Issue Description
Create an additional action in the CI workflow in `vets-website` and `content-build` that dispatches a new “common front-end workflow”, passing the common workflow information including `content-build` branch, `vets-website` branch, and the source repository. In turn, the common front-end workflow will dispatch the `devops` workflow to define the preview environment and request deployment.

---
## Tasks
- [ ] Add an additional action to the CI workflow in `vets-website`
- [ ] Add an additional action to the CI workflow in `content-build`

## Acceptance Criteria
- [ ] A workflow in `vets-website` dispatches a common front-end workflow once the CI checks have passed
- [ ] A workflow in `content-build` dispatches a common front-end workflow once the CI checks have passed

**Comment by pjhill** [comment]
Refinement questions and answers:
1. Do we want to give the users a button to decommission the preview environment?
A: No, not in the MVP. This might be prioritized for post-MVP
1. Do we want to update a UI somewhere with the preview instance decommission status?
A: If we **can** update the deployment status in the PR for example, that would be a good place to indicate that the PE is no longer available.

**Comment by CBonade** [comment]
Satisfied by https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/50517

We ended up deciding that we would not have CI trigger this, but have it as it's own workflow.

**Comment by pjhill** [comment]
Much of this work was completed as part of these tickets:
1. https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/49805
1. https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/50517

Let's consider closing this ticket.

**Comment by pjhill** [comment]
Each repository that we want to trigger the creation of a preview environment has a workflow in place to pass off the appropriate values / artifact references to the workflow in `devops` that will finalize the spec for the preview environment. This ticket's AC have been satisfied.
