### ISSUE TITLE
Internal - Chatbot Edge Case - Data Modeling

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#49825]
## Issue Description
This ticket is a follow up to the [Discovery ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45159) for the [Chatbot edge case request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45159).

The purpose of this ticket is to complete the date modeling needed to create the new datasets for the Chatbot KPIs.  Chloe to lead, Phil to support and train.

[KPI Discovery worksheet](https://docs.google.com/spreadsheets/d/1Tf9hcqwXySDtnm13oZ3frJdMUsuBGLFzEdV_4YoMPA8/edit#gid=1059164360)
[New Dataset Request Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=obrienjulie&labels=analytics-insights&template=analytics-internal-dataset-request.md&title=Analytics+Internal+-+New+Dataset+Request+Template)

---
## Tasks
- [x] Complete mock up based on agreed upon KPIs in support of this ticket
- [x] Define data needs (nd complete data request ticket as part of standard process)
- [x] Create BQ tables/views/dataset as needed 
- [x] QA data

## Acceptance Criteria
- [x] Datasets have been completed and handed off to analyst to created dashboards
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chloedotbrown** [comment]
Sharing [Chatbot mockup draft](https://docs.google.com/presentation/d/1DUiOmHx-I2fbGmTF_D2pYeAbbMrHfsh8JsAdNySh6eA/edit#slide=id.g195acf0ac8c_0_207) - @michelle-dooley feel free to take a look and send notes or set a meeting with the team to discuss any edits. Thanks~!

**Comment by chloedotbrown** [comment]
## Hit-level Chatbot view - BQ QA
Created a `chatbot` and `chatbot_yesterday` view in the analytics_testing folder in BigQuery. Separate `TEST_chatbot` created for QA to test full week of data (11/20-11/26). Note that any metrics requiring new session-level dataset will be created separately and QA'ed in a new comment.

_Reference: [BigQuery QA instructions](https://vfs.atlassian.net/wiki/spaces/AT/pages/2215870977/How+to+QA+data+in+BigQuery)_

## Structure tests

### Uniqueness
✅ **Passed!** Total rows is the same value as the count of distinct hit IDs (combination of session and hit number). 

Total rows | Unique IDs
 -- | -- 
 63,953 | 63,953

<details> 
  <summary>Expand for test code</summary>

```sql
select 
  count(*) as total_rows,
  count(distinct hit_id) as total_uuid
from `vsp-analytics-and-insights.analytics_testing.TEST_chatbot`
```
</details>

### Nulls
✅ **Passed!** All null rates had reasonable explanations consistent with other dataset stats or GA validation

Column | Null rate  | Explanation
 -- | -- | -- 
`event_label` | 92% | ✅ Consistent with total pageview hits (58,541)
`event_action` | 92% | ✅ _(see above)_
`entrance_page` | 85% | ✅ Consistent with event hits + previous page is not null (54,541)
`exit_page` | 72% | ✅ Consistent with event hits + next page is not null (45,798)
`seconds_on_page` | 37% | ✅ Consistent with event hits + next page is null (23,567)
`next_page_url` | 28% | ✅ Consistent with exit page is not null, events are empty string (18,155)
`next_page_name` | 28% | ✅ _(see above)_  
`prev_page_url` | 15% | ✅ Consistent with entrance page is not null, events are empty string (9,367)
`prev_page_name` | 15% | ✅ _(see above)_ 
`resource_link` | 8% | ✅ Consistent with event hits where label != 'chatbot-resource-link-click' (4,901)
 

<details> 
  <summary>Expand for test code</summary>

```sql
with chatbot_nulls as (
  select
    col_name, 
    count(1) total_nulls,
    'a' as join_key
  from `vsp-analytics-and-insights.analytics_testing.TEST_chatbot` t,
    unnest(regexp_extract_all(to_json_string(t), r'"(\w+)":null')) col_name
  group by col_name 
),

chatbot_all as (
  select 
    'a' join_key,
    count(*) as total_rows
  from `vsp-analytics-and-insights.analytics_testing.TEST_chatbot`
)

select
  col_name,
  total_nulls,
  round((total_nulls/total_rows), 2) as pct_null
from chatbot_nulls
left join chatbot_all using (join_key)
order by total_nulls desc
```
</details>

### Completeness
✅ **Passed!** Checked row distributions for pageviews and events.

<details> 
  <summary>Expand for test code</summary>

```sql
/**************************************
   NOTE: Highlight and run separately
**************************************/

# Check all pages in table are present
select 
  page_name,
  count(*) as total_rows
from `vsp-analytics-and-insights.analytics_testing.TEST_chatbot`
where hit_type = 'PAGE'
group by 1
order by 2 desc

# Check all events in table are present
select 
  page_name,
  event_type,
  count(*) as total_rows
from `vsp-analytics-and-insights.analytics_testing.TEST_chatbot`
where hit_type = 'EVENT'
group by 1,2
order by 1,3 desc

```
</details>

## Accuracy tests
For metrics not calculated in GA, the values used to calculate the rates are provided instead. Session-based values and values not possible to replicate with GA components are not included in this phase of QA. For more details on GA comparison methodology or explanations of differences above 2%, please see [dashboard build spreadsheet](https://docs.google.com/spreadsheets/d/1Tf9hcqwXySDtnm13oZ3frJdMUsuBGLFzEdV_4YoMPA8/edit#gid=907744366).

### Highlights

Page | BQ | GA| Δ% | Pass/Fail
-- | -- | -- | :--: | :--: 
Sessions to "Contact Us" page | 33,662 | 34,164 | 1.47% | ✅
Sessions to "VA Chatbot" page | 1,989 | 2,028 | 1.92% | ✅
Sessions where "Send text" button clicked | 1,236	| 1,236 | 0.0% | ✅
Sessions where "Go to Chatbot" link on "Contact Us" was clicked	| 1,355 | 1,355 | 0.0% | ✅

### Task Completion

Page | BQ | GA| Δ% | Pass/Fail
-- | -- | -- | :--: | :--: 
Total events for "send text" button	hit-level | 2,051 | 2,051 | 0.00% | ✅
Sessions where "start chat" button clicked | 1,323 | 1,323 | 0.00% | ✅
Top 20 links to next pages clicked on from bot - (1) Contact Us - https://www.va.gov/contact-us/ | 73 | 73 | 0.00% | ✅
Top 20 links to next pages clicked on from bot - (2) Ask VA - https://ask.va.gov/ | 70 | 69 | 1.45% | ✅
Top 20 links to next pages clicked on from bot - (3) Helpful VA Phone Numbers - https://www.va.gov/resources/helpful-va-phone-numbers/ | 65 | 65 | 0.00% | ✅
Sessions where user clicked a resource link | 466 | 466 | 0.00% | ✅

### Ease of Use

Page | BQ | GA| Δ% | Pass/Fail
-- | -- | -- | :--: | :--: 
Total logged in Chatbot pageviews | 1,093 | 1,085 | 0.74% | ✅

### Findability

Page | BQ | GA| Δ% | Pass/Fail
-- | -- | -- | :--: | :--: 
Previous page - (1) "Contact Us" | 1,873 | 1,873 | 0.00% | ✅
Previous page - (2) "(entrance)" | 118 | 118 | 0.00% | ✅
Previous page - (3) "VA Chatbot" | 103 | 103 | 0.00% | ✅
Device category used by session - desktop | 1,221 | 1,245 | 1.93% | ✅
Device category used by session - mobile | 728 | 735 | 0.95% | ✅
Device category used by session - tablet | 47 | 48 | 2.08% | ✅
Browser used by session - (1) Chrome | 1,073 | 1,091 | 1.65% | ✅
Browser used by session - (2) Safari | 535 | 539 | 0.74% | ✅
Browser used by session - (3) Edge | 314 | 322 | 2.48% | ✅

**Comment by chloedotbrown** [comment]
## Session-level Chatbot view - BQ QA
Created a `TEST_chatbot_sessions` view in the analytics_testing folder in BigQuery. 


_Reference: [BigQuery QA instructions](https://vfs.atlassian.net/wiki/spaces/AT/pages/2215870977/How+to+QA+data+in+BigQuery)_

## Structure tests

### Uniqueness
✅ **Passed!** Total rows is the same value as the count of distinct session IDs. 

Total rows | Unique IDs
 -- | -- 
 123,809 | 123,809

<details> 
  <summary>Expand for test code</summary>

```sql
select 
  count(*) as total_rows,
  count(distinct session_id) as total_uuid
from `vsp-analytics-and-insights.analytics_testing.TEST_chatbot_sessions`
```
</details>

### Nulls
✅ **Passed!** All null rates had reasonable explanations consistent with business logic.

Column | Null rate  | Explanation
 -- | -- | -- 
`seconds_engagement` | 97% | ✅  Consistent with sessions that had no "Start chat" events or exited from Chatbot page (120,987 rows)

**Engagement time null breakdown:**
- 119,985 – Null because no "Start chat" events (tagging added in Nov.)
- 980 – Null because all Chatbot pages were exits (no next page timestamp)
- 22 – Null because multiple Chatbot pages, and "Start chat" event occurred on exit pageview (spot-checked hit data for these sessions)
- 120,987 – TOTAL

<details> 
  <summary>Expand for test code</summary>

```sql
with chatbot_nulls as (
  select
    col_name, 
    count(1) total_nulls,
    'a' as join_key
  from `vsp-analytics-and-insights.analytics_testing.TEST_chatbot_sessions` t,
    unnest(regexp_extract_all(to_json_string(t), r'"(\w+)":null')) col_name
  group by col_name 
),

chatbot_all as (
  select 
    'a' join_key,
    count(*) as total_rows
  from `vsp-analytics-and-insights.analytics_testing.TEST_chatbot_sessions`
)

select
  col_name,
  total_nulls,
  round((total_nulls/total_rows), 2) as pct_null
from chatbot_nulls
left join chatbot_all using (join_key)
order by total_nulls desc
```
</details>

### Completeness
✅ **Passed!** Made sure no calculated fields had only zeros.

<details> 
  <summary>Expand for test code</summary>

```sql

select
  date,
  sum(case when started_chat > 0 then 1 else 0 end) as chat_sessions,
  sum(case when sent_text > 0 then 1 else 0 end) as text_sessions,
from `vsp-analytics-and-insights.analytics_testing.TEST_chatbot_sessions`
group by date
order by date

```
</details>

## Accuracy tests
Because these metrics are not possible to recreate in GA, accuracy tests cannot be run against GA reports. Luckily, this view is based on a hit-level dataset that _has_ been QA'ed against GA. Instead, these tests check key components of Chatbot product logic.

✅ **There must always more daily sessions where the "Start chat" button was clicked than sessions where text was submitted.**
<details> 
  <summary>Expand for test code</summary>

```sql

select
  date,
  sum(case when started_chat > 0 then 1 else 0 end) as chat_sessions,
  sum(case when sent_text > 0 then 1 else 0 end) as text_sessions,
from `vsp-analytics-and-insights.analytics_testing.TEST_chatbot_sessions`
--Nov. 15 first day "Start chat" tagging fully implemented
where date > '2022-11-14'
group by date
--Should return no rows
having chat_sessions < text_sessions
order by date

```
</details>

✅ **No users should have more than one "new" session on the Chatbot page.**
<details> 
  <summary>Expand for test code</summary>

```sql

select 
  user_id,
  count(*) as total_rows
from `vsp-analytics-and-insights.analytics_testing.TEST_chatbot_sessions`
where session_status = 'new'
group by user_id
order by total_rows desc

```
</details>

**Comment by chloedotbrown** [comment]
All three new datasets needed to support this dashboard have been created in Domo, shared with the Analytics user group, and co-owner status granted to the Analytics Domo Account. These include:

- [BQ - Chatbot hits](https://va-gov.domo.com/datasources/13c5d5c4-66af-4b5a-9123-1be484fe96e6/details/overview)
- [BQ - Chatbot sessions](https://va-gov.domo.com/datasources/c7267427-d218-4ea1-b0fb-992a9bf75c3a/details/overview)
- [[Output] Medallia Chatbot Surveys](https://va-gov.domo.com/datasources/a69c1255-70cf-42b5-9429-c63e680369a4/details/overview)

QA records for both BigQuery datasets are in comments above. The ETL for Chatbot Surveys can be considered QA'ed because the row-count matches that of the base dataset when filtered for the Chatbot Medallia form (761 vs. 761). All tabs on the [build tracker spreadsheet](https://docs.google.com/spreadsheets/d/1Tf9hcqwXySDtnm13oZ3frJdMUsuBGLFzEdV_4YoMPA8/edit#gid=1325615287) have been updated as well.

Closing ticket as work is complete.
