### ISSUE TITLE
Update vets-api routing in EKS for bulkhead -- Dev

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#49837]
## Description

Update ingressroute and deployment based off routing for current [config](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/templates/nginx_api_server.conf.j2) in BRD

## Tasks
- [x] Update routing in ingress file
- [x] Server deployment file
- [x] Service
- [x] Testing
  - [x] Environment is working as intended
  - [ ] Routings working as intended (if applicable)

## Acceptance Criteria
- [ ] Routings are working as intended
- [x] Environment still working as intended

**Comment by oseasmoran73** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/49779#issuecomment-1322536021

**Comment by oseasmoran73** [comment]
Route template are rendering correctly. Will need to add all other routes

**Comment by oseasmoran73** [comment]
Finished tempalte of the server-deployment. Seems very bloated, wondering if it can live in app-manifest rather than vets-api? Will do some more investigation and talk to Lindsey. 

The other unknown currently if we need to update the external DNS. The ports will remain the same, only routing per pod. Will discuss with Kyle

**Comment by oseasmoran73** [comment]
Routes populated. Trying to figure out optimization so we won't have duplicate code to maintain

**Comment by oseasmoran73** [comment]
Priority of team Charlie has changed. Moving into backlog

Latest PR's have been closed & cleanup will be handled by Rachel (aid wherever she needs help -- but will decouple deployment file into separate one).

**Comment by oseasmoran73** [comment]
Bulkhead implementation was finalized and polished by Rachel. Will spin up need tickets accordingly for further testing

**Comment by oseasmoran73** [comment]
Closing this ticket as implementation was finished and reflect accordingly. Tickets spun up are the following:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/53082
https://github.com/department-of-veterans-affairs/va.gov-team/issues/53078
