### ISSUE TITLE
Isolate claims-status application

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#49830]
## Background
In order to speed up development on vets-website applications, platform has started using yarn workspaces. These workspaces allow us to build our app independently of the rest of the applications in vets-website. In order to use yarn workspaces, one of the prerequisites is that we need to be added to the allowlist for single-app builds. To be added to the allow list, we must make sure that our app is isolated from the other applications. This requires us to make sure that  we are not importing from other applications, and other application are not importing from CST. Currently CST is not importing from other applications, but `Personalization` is importing from CST. We need to fix this.

## Tasks
- [x] Update the `Personalization` app to not import from CST

## Acceptance Criteria
- [x] `Personalization` is not importing from CST
- [x] CST is ready to be added to the single-app build allowlist
