### ISSUE TITLE
[Testing] Mimic service outage for External Service

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#49839]
## Description

Mimic service outage to ensure that if one external service is affected, the remaining services are still working as intended.  

Actual: Only specific service is affected with their pods
Actual: HPA scales accordingly in an effort to prevent latency

## Tasks
- [ ] Traffic is routed accordingly + verified
- [ ] Service unreachable
  - [ ] Only service is affected
  - [ ] Other Pods are not affected
- [ ] Resource consumption
  - [ ] HPA is working as intended
  - [ ] (Exploration) If HPA hits max, what is the correct course of action?
- [ ] Dashboard reflects accordingly both during testing process
- [ ] Think of other testing scenarios

## Acceptance Criteria
- [ ] Tasks listed above are tested + documented (if applicable)
- [ ] Fix issues and spin up tickets accordingly (if applicable)

**Comment by npeterson54** [comment]
Removing tech team 3 label from story as we will not be working on this

**Comment by rjain21** [comment]
Adding to Watchtower SRE Program board
