### ISSUE TITLE
CST: Add application to single-app build allowlist

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#49834]
## Background
Single-app builds allow us to have much faster turnaround on builds when updating our applications because the applications that are part of the single-app build allowlist are built individually as opposed to being built as part of the whole website. In order to be part of the allowlist we need to ensure 2 things:
1) Our application is isolated from other apps ✅ 
    * This means that CST is not importing from any other applications, and vice versa
2) Our application passes the header test ✅ 
    * This is a yarn script provided as part of vets-website
3) We have a slack group that we can receive application error messages in ✅ 
    * We have a slack group in the DSVA slack called `benefits-apps-builds`

## Helpful info
The snippet below will need to be added to `config/changed-app-builds.json`
```json
{
  "rootFolder": "claims-status",
  "slackGroup": "@benefits-app-builds"
}
```

## Tasks
- [x] Ensure that all of the requirements have been met for getting CST added to the allowlist
- [x] Add the JSON entry above to the `config/changed-app-builds.json` file
- [x] Create PR / Request review

## Acceptance Criteria
- [x] CST meets all requirements to be added to allowlist
- [x] CST has been added to allowlist (`config/change-app-builds.json`)
- [ ] PR has been merged
