### ISSUE TITLE
FE | Profile | Analytics - KPI Dashboard | Addition of Start/Failed to API

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#49847]
## Background

The Analytics team is building a dashboard for all sections within Profile.

We are missing the "event actions" we use for Contact information and determined we'll need to add in `started|failed` variations to track failures or failure rates for this group of retrievals.

The action responsible for this is located in the platform code here: https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/user/profile/actions/index.js in refreshProfile function.

## Tasks
- [x] Add started / failed events for the `/user` endpoint api call
- [x] Conduct Unit tests 
- [x] Run E2E tests covering current code and regression
- [x] Notify PM if this needs to be deployed to Staging behind feature flag
  

## Acceptance Criteria
- [x] Complete all unit testing
- [x] End-to-end tests showing 0 violations
- [x] All axe checks pass
- [x] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [ ] Confirm PM has opened a new ticket to deploy changes to Production using feature flag, if needed

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)?
- How can this work be validated?
- What updates need to be made (e.g. product outline, use cases, contact center guide)

## Associated Tickets
- #49344

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by adamwhitlock1** [comment]
@SKasimow this is ready to validate in staging. I'm not exactly sure the best way to trigger this though as usually the user endpoint works, so tracking failures will be somewhat unique to outages and other times when the API isnt working as expected.

Regardless this will be in prod after today's daily deploy, so if a GA dashboard widget is set up, then it should start seeing data hopefully tomo, if failures do occur.

**Comment by SKasimow** [comment]
Hi @chloedotbrown - this work has been completed and we're seeing traffic for successes captured (failures may take awhile longer; we don't expect to see many).

LMK if you have any questions!

**Comment by chloedotbrown** [comment]
Thanks so much, @SKasimow! I'll confirm this on the request ticket so Phil and Michelle know as well, and we can start modeling your data.

**Comment by SKasimow** [comment]
Thanks! Closing this ticket out...
