### ISSUE TITLE
Enhance FL's detail pages for Vet Centers

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#4984]
## High Level User Story
As the Facility Locator team, we need to work with the VHA to enhance the content delivered on Facility Locator's Vet Center detail pages so that Veterans are more prepared to to visit a facility. 

NOTE: Vet Centers do not currently have their own web pages so it is difficult for Veterans to find the information that they seek. 

## Hypothesis or Bet
**If** the Facility Locator offers more detailed and meaningful information about Vet Centers, **then**:
- We expect Veterans to feel more prepared to visit Vet Centers
- We expect Veterans to view the Facility Locator as a trusted source of information

## Objectives
- Objective #2: Deliver meaningful facility information
KEY RESULT: Vet Center Detail pages display complete and accurate list of services by (August 30, 2020?). 

## Definition of done
The following milestones have been successfully completed (or determined to be unnecessary for this work)

- [ ] Project Kickoff 
- [ ] Design Intent Collaboration 
- [ ] Usability Testing Prep
- [ ] Research Plan Review 
- [ ] Information Architecture (IA) Request 
- [ ] Analytics Request 
- [ ] Contact Center Review
- [ ] Staging Review
- [ ] Privacy and Security Review 
- [ ] Full Accessibility and 508 Office Audit
- [ ]  Post-launch Check-in
