### ISSUE TITLE
FE| Profile | Determine if any adt'l updates needed for TTY #s

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#49846]
## Background

As discussed in this [Slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1668557327761619?thread_ts=1668552564.907969&cid=C909ZG2BB) we need to review sketch files and determine if there are any errors or alerts that use TTY numbers that need to be updated to use 711. 

We are aware of 2 instances, described in ticket #49845.

## Tasks
- [ ] Review as working on #49846
- [ ] Notify PM of any errors/alerts that need to be updated
  

## Acceptance Criteria
- [ ] TTY updates are identified, tested and documented

## Associated Tickets
- #49845 (Design updates)
- #49843

**Comment by SKasimow** [comment]
Closing...looking for adt'l alerts to update for TTY will be done as part of #48926
