### ISSUE TITLE
[BE] Add statsd metrics to Travel Claim code (controller/client)

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#49848]
## User Story
As a developer/stakeholder, I want to be able to see accurate metrics for Travel Claims code so I can have a better idea of usage/performance

## Tasks
- [ ] [BE] Add statsd metrics for controller and client methods

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
