### ISSUE TITLE
Design | Profile |  TTY Design Updates

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#49845]
## Background

As discussed in this [Slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1668553118343919?thread_ts=1668552564.907969&cid=C909ZG2BB) we need to update the designs for the "How to fix an error in your name or DOB FAQ" and "What if my military info doesn't look right" screens with the 711 number.

## Tasks
- [x] Update Sketch files
  

## Acceptance Criteria
- [x] New designs for the two pages mentioned above are created
- [x] Notify PM that this is ready for FE ticket

## Associated Tickets
- #49843

**Comment by SKasimow** [comment]
@cgednalske - I believe all the associated design updates are complete but wanted to confirm...thanks!

**Comment by cgednalske** [comment]
@SKasimow - Military info is all good, but I'm not sure about the other sections. Will check through and make sure they're up-to-date 👍

**Comment by cgednalske** [comment]
@SKasimow Looks like most Direct deposit screens do not have the right format for the phone + TTY numbers (missing underline + blue text). I can start updating that today or Monday. 

All other sections look good.

**Comment by SKasimow** [comment]
@cgednalske - ok thanks for checking! I will assign this ticket to you and add to epic for Sprint 88 :)

**Comment by cgednalske** [comment]
@SKasimow ok great, sounds good - thanks! 👍

**Comment by cgednalske** [comment]
Hi @SKasimow - TTY numbers throughout Direct Deposit have been updated ([Desktop](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131) & [Mobile](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/p/837E4048-F554-48CA-B877-2C1007AB5D43/canvas)). There were a few places that weren't using the 711 yet (in the blue boxes in particular). Do we need a FE ticket for the backlog to double check that everything matches there too or was Direct Deposit covered in John's recent TTY updates?

**Comment by SKasimow** [comment]
Hi @cgednalske - I believe @jcatergovy said he'd be able to get everything updated but if they weren't already using 711 I don't think those would be included. Do you happen to recall any instances where we weren't showing 711 and I can double-check? If not, I can play around and see if I can find any that don't have 711...

**Comment by SKasimow** [comment]
I spot checked a few staging accounts and viewed the DD page; so far am seeing the 711 showing correctly however, I did notice that the users for the Use Cases [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/use-cases/payments-detected-partial-setup.md) need to be updated. Just spot checking and noticed that these users don't appear in the list of [staging users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)
> Log into staging with Judy Morrison ([staging user info](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv))
> Log into staging with users 379, 380, 381, 382 ([staging user info](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv))

**Comment by cgednalske** [comment]
I think that Liz had mentioned something with the user Judy Morrison... @andaleliz do you the status of the staging users for Direct Deposit? I'm not sure I'm up to speed with that.

@SKasimow that's good to hear that the Direct Deposit TTY info is all showing up correctly on staging. I'll check it out too, but sounds like we're in the clear 👍

**Comment by andaleliz** [comment]
Ah, good catch! Judy Morrison is a VAOS staging users, and those others are specific to DD. I updated the use case docs to point to those places.

**Comment by SKasimow** [comment]
I spot checked a few more DD use cases and am seeing 711 displaying correctly. I think we can close this out now?

**Comment by cgednalske** [comment]
@SKasimow yep! Looks good to me too 👍
