### ISSUE TITLE
Map VA.gov homepage top tasks to search best bets

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#49856]
## Description
As a Veteran or beneficiary, I want to be able to easily complete tasks required to learn about or manage my VA benefits and services. 
As the Sitewide homepage team, we need to make sure that search best bets are a method for supporting Veterans and beneficiaries in information discovery and task completion from the homepage. 

## Tasks
- [x] Map top tasks for current/existing homepage to search best bets
- [x] Map top tasks on redesigned homepage to search best bets
- [x] Identify gaps in best bets
- [x] Work with content team for search term recommendations for gaps
- [x] Reference recommendations from usability research

**Comment by mmiddaugh** [comment]
Task	|	Link	|	Current homepage	|	Redesigned 	|	In best bets	|	Keyword values	|	Usability recommendations
---	|	---	|	---	|	---	|	---	|	---	|	---
Apply for education benefits	|	va.gov/education/how-to-apply	|	X	|		|	X	|		|	"benifits"
Apply now for VA health care	|	va.gov/health-care/apply/application	|	X	|		|	X	|	["10 10 ez","1010ez","form 1010ez","health care application"] ["10-10EZ"]	|	
Change your address	|	https://www.va.gov/change-address	|	X	|		|	X	|	["change address","profile","update address"] ["20-572","Form 20-572","VA 20-572","VA Form 20-572"]	|	
Change your current education benefits	|	https://www.va.gov/education/change-gi-bill-benefits	|	X	|		|	X	|	["1995","22-1995","22-5495","5495","form 22-1995","va 22-1995","va form 22-1995"]	|	"benifits"
Check your claim or appeal status	|	https://va.gov/claim-or-appeal-status/	|	X	|	X	|	X	|	["claim status","historical claims","status","va file number"]	|	
Compare GI Bill benefits	|	https://www.va.gov/education/gi-bill-comparison-tool	|	X	|	X	|	X	|	["gi bill","schools that accept gi bill"]	|	"benifits"
Download your benefit letters	|	https://www.va.gov/records/download-va-letters	|	X	|		|	X	|	["award letter","award letters","disability letter","letter","letters","statement of benefits"]	|	"benifits"
File for a VA disability increase	|	https://www.va.gov/disability/file-disability-claim-form-21-526ez/	|	X	|		|	X	|	["21-526","21-526ez","526","526ez","form 21-526ez","va 21-526ez","va form 21-526ez"]	|	
File for disability compensation	|	https://www.va.gov/disability/file-disability-claim-form-21-526ez/	|	X	|	X	|	X	|	["21-526","21-526ez","526","526ez","form 21-526ez","va 21-526ez","va form 21-526ez"]	|	
Get mental health care	|	https://va.gov/health-care/health-needs-conditions/mental-health/	|	X	|		|	X	|	["mental health programs","mental health services","war veterans mental health"]	|	"therapist", "counselor", and "therapy"
Get reimbursed for travel pay	|	https://va.gov/health-care/get-reimbursed-for-travel-pay/	|		|	X	|	X	|	["10-3542","beneficiary travel","travel pay","travel reimbursement"]	|	
Get Veteran ID cards	|	https://www.va.gov/records/get-veteran-id-cards	|	X	|		|	X	|	["apply for id","id","id card","id card application","identification card","va id","va id card","veterans id card"]["id card","vic application","vic"]	|	
Get your VA medical records	|	https://va.gov/health-care/get-medical-records/	|	X	|	X	|	X	|	["blue button","medical records","release of information","request veteran medical records"]	|	
Refill and track your prescriptions	|	https://www.va.gov/health-care/refill-track-prescriptions	|	X	|	X	|	X	|	["pharmacies","pharmacy","prescriptions","refill","rx"]	|	
Request your military records (DD214)	|	https://www.va.gov/records/get-military-service-records	|	X	|		|	X	|	["214","dd 214","dd-214","dd214","form dd214","sf 180","sf-180","sf180","va dd214","va form dd-214","va form dd214"]	|	
Review or update your dependents	|	https://va.gov/view-change-dependents	|	X	|		|	X	|	["declare","dependent","dependents"]	|	"spouse" and "dependent"
Schedule and manage health appointments	|	https://www.va.gov/health-care/schedule-view-va-appointments	|	X	|	X	|	X	|	["appointment","make an appointment","make appointment","schedule an appointment","schedule appointment"]	|	
Send a secure message to your health care team	|	https://www.va.gov/health-care/secure-messaging	|	X	|		|	X	|		|	
Upload evidence to support your claim	|	https://www.va.gov/disability/upload-supporting-evidence	|	X	|		|	X	|	["21-4138","4138","form 21-4138","statement in support of claim","va 21-4138","va form 21-4138","va form21-4138"]	|	
View your lab and test results	|	https://www.va.gov/health-care/view-test-and-lab-results	|	X	|		|	X	|		|	
View your payment history	|	https://www.va.gov/va-payment-history	|	X	|	X	|		|		|	
View disability rates	|	https://va.gov/disability/compensation-rates/veteran-rates/	|		|		|		|		|	disability rates

**Comment by mmiddaugh** [comment]
Created best bet requests: 

- "View your payment history" #49893
- "Mental health" #49894
- "Disability compensation rates" #49897

**Comment by mmiddaugh** [comment]
[https://app.zenhub.com/files/133843125/24eb3f2b-9b9e-47a6-8c8b-9d90471d1322/download](https://app.zenhub.com/files/133843125/24eb3f2b-9b9e-47a6-8c8b-9d90471d1322/download)
