### ISSUE TITLE
Discovery: Determine if Loki is root cause of latency issues within Vets API

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#49854]
Wednesday, the 16th, Loki was down which caused Vets API logs to back up and slow all Vets API traffic. Once Loki was back online, everything recovered.

We suspect other latency events were caused by logs falling behind. Latency events of this nature started approximately when we added Loki in 2021.

## Tasks

- [ ] Investigate system resources when logs are backing up
- [ ] Determine if Semantic Logger is appropriately logging asynchronously
- [ ] Work with Kyle to attempt reproducing issues with Loki

**Comment by atovar-va** [comment]
Reviewed on 07/10 - Ok to close.
