### ISSUE TITLE
526ez | Technical Discovery for Re-routing Errors

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#49850]
## Value Statement
**_As a_** Veteran
**_I want to_** ensure that my claim is established when I submit it through VA.gov 
**_So that_** I can have my claim processed with no interruptions.

---
## Acceptance Criteria
The goal of this discovery is to complete the following:

- [x] Understand how EVSS handles 526 form data such that it can be added to the pdf version of the form and submitted through Lighthouse. 
- [x] Validate that our solution for resolving 526 errors that fall under these scenarios is feasible.

## Tasks
- [x] Figure out all current components of 526 that we handle
- [x] Evaluate our ability to replicate EVSS’s data handling to completely fill out the form
- [x] Evaluate the effort to fill them all out
- [x] Schedule time with Michael Harlow to discuss changes to error details and to review the implementation approach
- [x] Talk to EVSS, find out if they can quickly give us an endpoint that returns a PDF version of the 526 form
- [x] Figure out the best method of Centralized Mail submission (one payload total or one per attachment)

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Reviewed and approved by product and engineering

**Comment by saderagsdale** [comment]
@kylesoskin can you add an estimate to this one?

**Comment by saderagsdale** [comment]
Update from 11/30 call @kylesoskin:
- Kyle to send sample payload through test environment to show Centralized Mail how the tw options appear on their end
- Molly to clarify if incoming documents are indexed before processing (to help determine if we should send one payload or two)

**Comment by kylesoskin** [comment]
All of these are done, Validate tomorrow that we are good, then close.
