### ISSUE TITLE
[BE] Modify BTSSS Claims client interface header for production

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#49855]
## Description
In production environment, BTSSS ``ClaimIngest`` API expects couple of subscription key in header as below,
```
      {
        'Content-Type' => 'application/json',
        'OCP-APIM-Subscription-Key-E' => subscription_key_1,
        'OCP-APIM-Subscription-Key-S' => subscription_key_2
      }
```

## Tasks
- [ ] [BE] Modify BTSSS ClaimIngest API client interface `claims_default_header` method
- [ ] [BE] rspecs

## Acceptance Criteria
- [ ] Deployed to prod
- [ ] Tested on prod
