### ISSUE TITLE
CST: Use `startApp` in favor of `startReactApp`

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#49861]
## Background
All new apps use the `startApp` method to start their applications. CST is doing much of the work that `startApp` is doing already so it makes sense to migrate to using the platform-supported method. This will ensure that our app continues to start up properly as we move forward.

## Considerations
Currently we are adding a listener to the react-router `history` object to fire a redux action creator every time the page changes. The action creator keeps track of the last page visited as well as a running log of all routes visited within the CST application.

It isn't 100% clear what purpose this is done for, but until we can evaluate it at some point in the future, it's better to keep the functionality working.

* We will need to get a copy of the router in the `<ClaimStatusApp>` component and attach a listener to it from there.
* The router can be injected as a prop into the `<ClaimStatusApp>` component by using the `withRouter` HOC provided by the `react-router` package (make sure to use `react-router` and not `react-router-dom`.

## Tasks
- [x] Move routes into the existing `routes.jsx` so that all routes are in one place
- [x] Replace the code in `claims-status-entry.jsx` with a call to `startApp`
- [x] Attach a listener to the `router` object in the `<ClaimStatusApp>` component

## Acceptance Criteria
- [x] CST is calling `startApp` instead of custom startup code
- [x] `SET_LAST_PAGE` redux action is still being fired
