### ISSUE TITLE
[EVSS to Lighthouse] Create feature toggle for EVSS to Lighthouse claims migration

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#49863]
## Background
We need to create a feature toggle to block access to the new claims components that will be using the Lighthouse version of the API

## Considerations
**Feature toggle name:** `cst_use_lighthouse`

There is are two components to this request: frontend and backend.

#### src/platform/utilities/feature-toggles/featureFlagNames.js
* Add a new key-value pair to the list of feature toggles

#### src/applications/claims-status/selectors/index.js
* Create a selector for the new feature toggle

#### config/features.yml
* Add a new entry for the feature toggle

## Tasks
- [x] Create frontend PR based on considerations above
- [x] Create backend PR based on considerations above

## Acceptance Criteria
- [x] Frontend and Backend PRs are created
- [ ] Frontend and Backend PRs are merged
