### ISSUE TITLE
Update rates for survivors DIC for 2023

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#49872]
## Issue Description
DIC rates for spouses and dependents change on December 1, 2022. We need to update our [Survivors DIC](https://www.va.gov/disability/survivor-dic-rates/) rates page with this new information. We'll also need to clone the current rates page to create a past rates page. 

2023 rates to input: [https://app.zenhub.com/files/133843125/9f0fefcd-b910-4a16-97c1-591950a34dc1/download](https://app.zenhub.com/files/133843125/9f0fefcd-b910-4a16-97c1-591950a34dc1/download)

## Tasks
- [x] Clone page to create past rates page
- [x] Update current rates page with new rates
- [x] Copyedit past rates page (Megan)
- [x] Copyedit current rates page (Megan)
- [x] Publish both pages (Megan)
- [x] Add newest past rates page and remove oldest rates page from left nav (Megan)

## Acceptance Criteria
- [x] 2023 survivor DIC rates are live
- [x] 2022 past rates page is live
- [x] Left nav is updated

**Comment by laurwill** [comment]
Hi @RLHecht , this is ready for copyedit and publishing on Monday.
Past rates: http://preview-prod.vfs.va.gov/preview?nodeId=51270 
Current rates: http://preview-prod.vfs.va.gov/preview?nodeId=1012

One question: I don't see a separate line in the new rates document for "Surviving dependent child of a Veteran, when the Veteran has no surviving spouse" — I used the number from the next category for helpless child, since those 2 numbers are the same on the live rates page. But want to confirm this is right!

And as you've already noted in the editorial calendar, we'll need to remove language about the SBP offset later this month. I'm thinking we may want to replace that whole section with a note about how the offset was phased out — maybe we can work that into the next sprint so it's ready ahead of the holidays!

**Comment by katherine-fung** [comment]
Hi @RLHecht, 

I checked the numbers, and these pages ready to publish: 

current rates: http://preview-prod.vfs.va.gov/preview?nodeId=1012 

past rates: http://preview-prod.vfs.va.gov/preview?nodeId=51372 
(different than link above) 

re: Laura's question above -- I believe we have these numbers right. We took them from the section of the source file marked "Children's Rates - No Surviving Spouse Entitled."

**Comment by RLHecht** [comment]
These have been published. Moving to validate.
