### ISSUE TITLE
Update Survivors Pension rates page for 2023

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#49875]
## Issue Description
Survivors Pension benefit rates change on December 1, 2022. We need to update our [Survivors Pension](https://www.va.gov/pension/survivors-pension-rates/) rates page with this new information. We'll also need to clone the current rates page to create a past rates page. 

## Tasks
- [ ] Clone page to create past rates page
- [ ] Update current rates page with new rates
- [ ] Copyedit past rates page (Megan)
- [ ] Copyedit current rates page (Megan)
- [ ] Publish both pages (Megan)
- [ ] Add newest past rates page and remove oldest rates page from left nav (Megan)

## Acceptance Criteria
- [ ] 2023 Survivors Pension benefit rates are live
- [ ] 2022 past rates page is live
- [ ] Left nav is updated

**Comment by katherine-fung** [comment]
Hi @megzehn! 

I updated the live page with the 2023 rates for VA Survivors Pension, and created the 2022 past rates page. They're ready for copyedit. 

2023 current rates page: 
http://preview-prod.vfs.va.gov/preview?nodeId=589 

past 2022 rates page: 
http://preview-prod.vfs.va.gov/preview?nodeId=51249

Thanks!

**Comment by laurwill** [comment]
I checked these pages — also ready to publish on Monday.

**Comment by RLHecht** [comment]
These pages are published. Moving to validate.

**Comment by RLHecht** [comment]
These changes are live. Closing ticket.
