### ISSUE TITLE
Implement Phase 1 of Medallia

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#4987]
## Problem Statement
How might we stand up the digital instance of Medallia so we can begin to implement surveys on VA.gov that can indicate specific product success or improvements?

## Goal
Stand up the digital instance of Medallia: VSP users should be able to use the Medallia application to create surveys on VA.gov without dependency on Front End engineering.

## Issue Acceptance Criteria
- [ ] Schedule kickoffs with VBA's engineering leads and VSP Front End POCs
- [ ] Medallia digital instance implemented

## Medallia Acceptance Criteria for Phase 1 (Medallia Digital Instance)
(VSP referred to here as 'users')
- [ ] Role access (maintenance, view-only, etc.) can be assigned
- [ ] Users can create surveys (with unique survey questions) on Medallia
- [ ] Users can assign surveys to different URLs and can trigger surveys based on VA.gov user behavior
- [ ] Users can display surveys on VFS team applications - users can embed, add surveys as additional layers, or add survey buttons on a VA.gov URL.

## Details
- VSignals [initial VA discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/vsignals.md)
- VBA kickoff [meeting notes](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4649#issuecomment-576377268)

**Phase 1 & 2: 2-3 sprints**
- Phase 1: Stand up Medallia digital instance
- Phase 2: Integrate Medallia Experience Cloud
- Phase 3: VSP Analytics & Insights takes over survey implementation. ForeSee turns over to Medallia.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
# 1/23/20 Meeting Summary

**VSP is blocked on integrating Medallia until the tool's infrastructure, security & configuration is complete.**

The Medallia rollout is edited to include the additional beginning phases, which have not yet been started:

| Phase                          | Office                                                                       |
|--------------------------------|------------------------------------------------------------------------------|
| 1. Infrastructure              | Medallia                                                                     |
| 2. VA Configuration            | Halfaker                                                                     |
| 3. Website Integration         | Veteran-facing Services Platform: VSP Analytics & Insights & Front End Tools |
| 3a. Stand Up Digital Instance  | Veteran-facing Services Platform: VSP Analytics & Insights & Front End Tools |
| 3b. Integrate Experience Cloud | Veteran-facing Services Platform: VSP Analytics & Insights & Front End Tools |
| 4. Survey Implementation       | VSP Analytics & Insights                                                     |                                              |

**Comment by rianfowler** [comment]
Next steps
- give medallia reps email address 
- review implementation documentation

**Comment by joanneesteban** [comment]
`VA.gov A11 Questionnaire` has been published via Medallia Digital - VA Sandbox for testing in staging. We may need to update the CSS to reflect the design system.

**Comment by joanneesteban** [comment]
A rough draft of the A11 survey was added to Staging, but I'll need to validate its design first.

## Next Steps

1. Joanne will meet with Product Support to determine any design changes in the beginning of Sprint 33.
2. Joanne to send over suggestions for CSS changes (help or review CSS). 
3. Joanne to validate survey in Staging - tentative end of Sprint 33. Verify with FE (asynchronously if we can) if anything else is needed.
4. Joanne to verify with DEPO and we can remove the environment flag.

([Old Medallia test CSS](http://medallia.s3.amazonaws.com/Vets/va-vets-custom-styles-v5.css))

@meganhkelley

**Comment by meganhkelley** [comment]
@joanneesteban do you anticipate needing much more support from FE Tools for this? If not, we'd like to remove it from our board (remove our team label)

**Comment by joanneesteban** [comment]
@meganhkelley Thanks for reviewing! Actually, there's another digital embed code for production (literally just a 2 for production instead of a 5 for sandbox). Can this get added to prod? We're good to close out after that.

![image](https://user-images.githubusercontent.com/48964695/92791301-8f106f00-f37a-11ea-8c0a-aad71c472b8f.png)

**Comment by billfienberg** [comment]
@joanneesteban, these are the URLs, correct?

Prod: https://resource.digital.voice.va.gov/wdcvoice/2/onsite/embed.js
Staging: https://resource.digital.voice.va.gov/wdcvoice/5/onsite/embed.js

**Comment by billfienberg** [comment]
References

- Host Medallia CSS #13287
- Add padding to bottom of Medallia form [`vets-website` PR #14483](https://github.com/department-of-veterans-affairs/vets-website/pull/14483)

**Comment by joanneesteban** [comment]
Thanks, @billfienberg ! Yup, those are the correct URLs.

**Comment by meganhkelley** [comment]
Current status: FE Tools team is waiting to hear from Analytics/Insights about usability testing before doing any further work on Medllia. cc @joanneesteban

**Comment by meganhkelley** [comment]
@jwoodman5 @JoeTice @billfienberg I removed FE Tools label from this ticket, not sure if ticket is still relevant or can be closed

**Comment by billfienberg** [comment]
My gut says this can be closed, but I'd check with the Medallia PM to be safe.

**Comment by jonwehausen** [comment]
Closing.
