### ISSUE TITLE
[FE] Add screenshots to capture travel path BTSSS errors

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#49877]
## User Story
As a developer, I want to automate taking screenshots of the travel path error states

## Tasks
- [ ] [FE] Update the travel unhappy path tests to take screenshots of different BTSSS error states.

## Acceptance Criteria
- [ ] Takes a screenshots of general error
- [ ] Takes a screenshot of claim already exists error

**Comment by brianseek** [comment]
@wullaski I think this one is good to close since there isn't any additional validation needed.
