### ISSUE TITLE
Update rates for Parents DIC for 2023

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#49873]
## Issue Description
DIC rates for parents change on December 1, 2022. We need to update our [VA DIC rates for parents](https://www.va.gov/disability/parent-dic-rates/) rates page with this new information. We'll also need to clone the current rates page to create a past rates page. 

2023 rates to input: [https://app.zenhub.com/files/133843125/e1de3097-1b36-457d-82b5-6b8f1661b5b9/download](https://app.zenhub.com/files/133843125/e1de3097-1b36-457d-82b5-6b8f1661b5b9/download)

## Tasks
- [x] Clone page to create past rates page
- [x] Update current rates page with new rates
- [x] Copyedit past rates page (Megan)
- [x] Copyedit current rates page (Megan)
- [x] Publish both pages (Megan)
- [x] Add newest past rates page and remove oldest rates page from left nav (Megan)

## Acceptance Criteria
- [x] 2023 parents DIC rates are live
- [x] 2022 past rates page is live
- [x] Left nav is updated

**Comment by katherine-fung** [comment]
past rates - http://preview-prod.vfs.va.gov/preview?nodeId=51270

**Comment by laurwill** [comment]
Thanks @katherine-fung ! You had mostly finished these rate changes. Here's what I did:
- Created new accordions for 9,000 and 10,000 ranges in the "only 1 parent" alive section
- Applied rate change to step by step instructions at bottom 

http://preview-prod.vfs.va.gov/preview?nodeId=1013

@RLHecht these are mostly ready to publish on Monday, but I'd like to have someone check/confirm these pieces before we pub:
- Double check my math in the step by step
- Double check the 8,000, 9,000, and 10,000 tables in "only 1 parent alive" section
- Confirm that the thresholds for monthly vs. quarterly etc payments haven't changed — I didn't see new thresholds in the rates doc, but I wasn't sure if these are constant

**Comment by RLHecht** [comment]
These have been checked and the pages were published. Moving to validate.

**Comment by RLHecht** [comment]
These pages are live. Closing ticket.
