### ISSUE TITLE
Submit request to acquire a permanent subdomain to host Preview Environments

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#49878]
# Description
Given the outcome of the [PE EKS POC](https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/department-of-veterans-affairs/va.gov-team/49343) and the [conversation with infrastructure SMEs](https://vfs.atlassian.net/wiki/spaces/TT4/pages/2436628750/Kyle+Conversation+11+17+regarding+EKS+Deployment+Process), it is prudent for our team to get access/approval to a sub-domain for use in `dev`. This subdomain will make preview environments directly routable from the public internet without requiring us to piggyback on the use of an existing subdomain by defining paths and using the revproxy.

**Consider** using the subdomain `preview.va.gov`

# Tasks
- [x] Research the requirements for acquiring a subdomain
- [x] Gather approvals for the access/use of the subdomain from required approvers
- [x] Define the use and scope of the subdomain

# Acceptance Criteria
- [x] A request has been submitted to request a subdomain for use with preview environments

**Comment by rmtolmach** [comment]
The former Cloud Isolation team went through a process to get the subdomain `platform-api.va.gov`. Andrea Singh provided some information on that process. They did an in-scope ESECC request (instead of starting from scratch) which let them piggyback on an existing RFC.

Here is some documentation that explains how to request a subdomain: [ESECC-Public-URL-process.md](https://github.com/department-of-veterans-affairs/devops/blob/master/docs/ESECC-Public-URL-process.md). It looks like it was mostly written by Boris Ning. 

Confluence documentation of the process Andrea's team when through: [ESECC Request - Cloud Isolation](https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2231926890/ESECC+Request+-+Cloud+Isolation).

Both of these documents look helpful.

**Comment by rmtolmach** [comment]
I'm documenting our investigation here: https://vfs.atlassian.net/wiki/spaces/TT4/pages/2443444492/Subdomain+for+preview+environments

**Comment by rmtolmach** [comment]
related: 
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/49878

**Comment by rmtolmach** [comment]
We have edited the VA web registry for `preview.va.gov`.
Next up, but needs to be submitted by Ray Wang:
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/50151

**Comment by pjhill** [comment]
This request was submitted and processed. We need to submit an alternate request which will be worked under a new ticket.
