### ISSUE TITLE
Update Veterans Pension rates for 2023

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#49874]
## Issue Description
Veterans Pension rates change on December 1, 2022. We need to update our [Veterans Pension](https://www.va.gov/pension/veterans-pension-rates/) rates page with this new information. We'll also need to clone the current rates page to create a past rates page. 

2023 rates to input: [https://app.zenhub.com/files/133843125/73628b81-eb4f-4151-bdef-1b06a8553b7a/download](https://app.zenhub.com/files/133843125/73628b81-eb4f-4151-bdef-1b06a8553b7a/download)

## Tasks
- [x] Clone page to create past rates page
- [x] Update current rates page with new rates
- [x] Copyedit past rates page (Megan)
- [x] Copyedit current rates page (Megan)
- [x] Publish both pages (Megan)
- [x] Add newest past rates page and remove oldest rates page from left nav (Megan)

## Acceptance Criteria
- [x] 2023 Veterans Pension rates are live
- [x] 2022 past rates page is live
- [x] Left nav is updated

**Comment by katherine-fung** [comment]
created past rates page: 

http://preview-prod.vfs.va.gov/preview?nodeId=51251

**Comment by RLHecht** [comment]
I published both of these. Moving to validate until they are live.

**Comment by RLHecht** [comment]
changes are live. closing ticket.
