### ISSUE TITLE
Update protected disability and death pension rates for 2023

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#49876]
## Issue Description
Protected disability and death pension rates change on December 1, 2022. We need to update our [Protected disability and death pension](https://www.va.gov/pension/protected-pension-rates/) rates page with this new information. We'll also need to clone the current rates page to create a past rates page. 

2023 rates to input: [https://app.zenhub.com/files/133843125/3c81e5a7-1d29-4ef5-a909-7dc7a71e3b13/download](https://app.zenhub.com/files/133843125/3c81e5a7-1d29-4ef5-a909-7dc7a71e3b13/download)

## Tasks
- [x] Clone page to create past rates page
- [x] Update current rates page with new rates
- [x] Copyedit past rates page (Megan)
- [x] Copyedit current rates page (Megan)
- [x] Publish both pages (Megan)
- [x] Add newest past rates page and remove oldest rates page from left nav (Megan)

## Acceptance Criteria
- [x] 2023 protected disability and death pension rates are live
- [x] 2022 past rates page is live
- [x] Left nav is updated

**Comment by katherine-fung** [comment]
Hi @megzehn, 

I posted the 2023 rates for protected disability and death pension, and created a past rates page. They're ready for copyedit. Thanks!!

2023 rates page: 
http://preview-prod.vfs.va.gov/preview?nodeId=5090

past 2022 rates page: 
http://preview-prod.vfs.va.gov/preview?nodeId=5090

**Comment by laurwill** [comment]
I checked these — ready to publish on Monday.

@RLHecht , there's also an info alert on this page that would be good to review in that new process. It seems like it could become permanent page content, but if we keep it as an alert we should update for current site style.

**Comment by RLHecht** [comment]
Published these pages. Moving to validate.

**Comment by RLHecht** [comment]
These are live. Closing!
