### ISSUE TITLE
(Samara) Product Definitions page: #49879

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#49884]
### Tasks:

- [x] Review the ticket request: https://github.com/department-of-veterans-affairs/va.gov-team/issues/49879
- [x] Define questions for either the customer and/or Jason, Ray
- [x] Document any recommendation from the Platform Content team

**Comment by vbellissimo** [comment]
@vicky.bellissimo
 
@Jill Taylor
 
@Lauren.Conrad
 
@Brian Smolensky
 My initial recommendation is to create another page that has a link for both the product directory glossary and the VFS product terms and definition. Or simply add what's on the GitHub VFS terms doc to the VFS Platform product directory doc.  I think linking directly to the GitHub maybe troublesome for some that may have access issues or if something may happen to GitHub as far as our future use of it.  My only observable question for the requester is some inconsistencies in the GitHub doc with providing a resource under one of the headings.  What is everyone else's thought?

**Comment by vbellissimo** [comment]
@Samara 'Sam' Simmorins
 I like your idea of creating a new page for this information and housing it near or next to the Product Directory page. And then linking to this new page from the Product Directory.
If everyone else agrees to that, I would recommend you reach out to Ryan Smith and Jason Woodman to let them know that is our recommendation and ask if they are okay with us going forward with doing that?
