### ISSUE TITLE
[Design] VA simplified footer: Update Final Wireframes

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#49891]
## Tasks
- [x] Update final wireframes so that legal links remain in the VA simplified footer
- [x] Update simplified header content to be Appointment check-in (for check in) and Appointment pre-check-in (for pre-check-in)

## AC

- [x] Abstract branch for pre check in provided
- [x] Abstract branch for check in provided 

## Deliverable
- Check-in: https://share.goabstract.com/3033a7fe-ebfc-4335-966c-dba88c5b3e0d?collectionLayerId&mode
- Pre-check-in: https://share.goabstract.com/c8e02754-a7ea-4694-b2ca-e3989357c289?collectionLayerId&mode

**Comment by benbrasso-agile6** [comment]
Updated task list to include updating header content

**Comment by zach-park** [comment]
@loripusey @benbrasso-agile6 @kristenmcconnell @kellysmith1008 , the VA simplified footer and header are updated and ready.

**Comment by benbrasso-agile6** [comment]
For check in, I don't see the correct name in the header. 

For pre check in, I don't see the correct header. 

>Update simplified header content to be Appointment check-in (for check in) and Appointment pre-check-in (for pre-check-in)

**Comment by loripusey** [comment]
Why does pre-check-in still have the sign-in button and hamburger menu? 
@zach-park @benbrasso-agile6

**Comment by zach-park** [comment]
@loripusey @benbrasso-agile6 , apologies! I updated them with the correct header.

**Comment by benbrasso-agile6** [comment]
looks good

**Comment by loripusey** [comment]
@zach-park please address this comment and have it ready to turn over to engineering for implementation by 12/15 EOD by the latest. Thanks.
@benbrasso-agile6

**Comment by zach-park** [comment]
@loripusey , the menu icon should've been resolved. I'll check again, sorry.

**Comment by loripusey** [comment]
Thanks @zach-park
