### ISSUE TITLE
Metrics tracking

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#49895]
## Tasks

- [x] Identify metrics to track (that gauge success and/or feedback from Veterans) 

Metrics: 

- Did the number of clicks increase (i.e., percentage of clicks vs. visits) for navigating away from PCI? (We're monitoring to make sure they don't.)
     - Pre check in
          - ID verification page
     - Check in
          - ID verification page
          - See staff page
          - Your Appointments page
- Was there an increase (i.e., percentage of clicks vs. visits) in Veteran feedback about "log in" or "log on" or "sign in" from VSignals? (We're monitoring to make sure they don't.)

(Need to chat a bit more with Adrian this morning, but I think in this initial release, we don't expect to see a decrease in page load speed.) (Confirmed)

- [x] Circulate metrics with check in team
- [x] Make sure GA events (or clicks, bounce rates) are set up to track interactions. If needed, add widget to GA dashboard to track success. Or, provide link to GA view on where metrics will be tracked. 
- [x] Document rollout plan
- [x] Circulate rollout plan with check in team 
- [ ] Send metrics and rollout plan to platform design system team and add comments to tickets - [header and footer ](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1339)
- [x] Track performance during rollout
- [x] Update platform design system with performance during rollout
- [ ] Comment on experimental tickets with performance during rollout
- [ ] Create ticket in VA research repo with findings from test with Veterans
- [ ] Add the VA research repo ticket to the two experimental tickets 

## AC

- [x] Metrics identified
- [x] CIE team signed off on metrics
- [x] CIE team signed off on rollout plan 
- [x] Received feedback or acknowledgment from platform design system team on metrics and rollout plan
- [ ] VA research repo with performance data submitted

**Comment by benbrasso-agile6** [comment]
Pulling this in. Probably need to look at this to prepare for staging review.

**Comment by benbrasso-agile6** [comment]
- Did the number of clicks increase for navigating away from PCI?
     - Pre check in
          - ID verification page
     - Check in
          - ID verification page
          - See staff page
          - Your Appointments page
- Was there an increase in Veteran feedback about "log in" or "log on" or "sign in" from VSignals?

(Need to chat a bit more with Adrian this morning, but I think in this initial release, we don't expect to see a decrease in page load speed.)

**Comment by benbrasso-agile6** [comment]
https://analytics.google.com/analytics/web/#/dashboard/jdNx2VfCSDO6xD6_XLtUdA/a50123418w177519031p176188361/_u.dateOption=last7days/

Monitor data for a bit

**Comment by benbrasso-agile6** [comment]
Moving to closed. Metrics are doing well. [https://app.zenhub.com/files/133843125/252395e0-d8ac-4247-adeb-83f4444be058/download](https://app.zenhub.com/files/133843125/252395e0-d8ac-4247-adeb-83f4444be058/download)
