### ISSUE TITLE
[FE] Build the New Simplified Footer

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#49890]
## Release Notes
This ticket is for the footer only because the header has been split out into another ticket.

**NOTE: we would like to release this gradually over time** (i.e. certain % initially and gradually increase it as we monitor the metrics)

**NOTE: Matt Dingee needs to be kept in the loop know how we architect this**

**NOTE: We need to coordinate with Dave Conlon**

We can meet almost all of the requested UI changes by doing the following:

submit a PR to content-build and vets-website to allow suppressing all except the legal links in the footer, to also be configured with the application registry

## Wireframes
- TBD

## Tasks
- [ ] Add an option to simplify the VA footer
- [ ] [FE] **Swap out the VA footer to use the new simplified footer**
- [ ] (determine if this is still needed) Work with Josh Kim to make sure all the HTML semantics look right when it goes to code (Feedback from design intent meeting)
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by benbrasso-agile6** [comment]
Added item to task list  "Work with Josh Kim to make sure all the HTML semantics look right when it goes to code (Feedback from design intent meeting)"

**Comment by loripusey** [comment]
Meeting on 12/16 to discuss with DS

**Comment by brianseek** [comment]
resolution from spike ticket: In discussion with the team we are going to make contact with the team(s) that manage header and footer to get an idea of what is possible. From the PL in standup on 12/19 we determined that we want to take the fastest path of least resistance, the minimal approach outlined in the spike ticket.

From chat:
08:50:07 From Kristen McConnell to Everyone:
From what I know from my discussions with Matt Dingee, we would need to talk to Public Websites and Matt Self.

08:50:39 From Ben Brasso to Everyone:
Carol and Matt are the folks that we need to speak with about being part of the component conversation

08:51:31 From Kristen McConnell to Everyone:
Carol and Matt are the platform group, but public websites controls that current component.

08:54:55 From Kristen McConnell to Everyone:
Wait…not Matt Self. Dave Conlon on the sitewide crew is who Matt Dingee mentioned too.

**Comment by acrollet** [comment]
The PR to fix content-build has been merged: https://github.com/department-of-veterans-affairs/content-build/pull/1425

Next step for the header (in progress) is to test the [vets-website PR](https://github.com/department-of-veterans-affairs/vets-website/pull/23054) with the content-build PR merged and document and submit the PR.

**Comment by acrollet** [comment]
The PRs for [content-build](https://github.com/department-of-veterans-affairs/content-build/pull/1436) and [vets-website](https://github.com/department-of-veterans-affairs/vets-website/pull/23135) have been updated to show only the logo (and VCL banner on mobile) per the DSC meeting and submitted for review.

**Comment by acrollet** [comment]
The PRs for [content-build](https://github.com/department-of-veterans-affairs/content-build/pull/1436) and [vets-website](https://github.com/department-of-veterans-affairs/vets-website/pull/23135) have been merged.
