### ISSUE TITLE
[FE] My VA Healthcare: Documentation for Cerner Drupal Changes

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#49892]
## Background
Now that we have completed #47956 we want to ensure all FE documentation is updated to reflect this new implementation with Drupal API. This documentation should include information about the change and be added in GIT, PM can create a folder to store the documentation when we are ready.

## Tasks
- [x] Add Drupal/Cerner documentation to GIT
- [x] APM to make sure documentation is added in the right location

## Acceptance Criteria
- [x] Documentation for Drupal implementation is added to GIT repo

**Comment by tmitchellgcio** [comment]
Placed in https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/health-care-section.md under the cerner alert section
