### ISSUE TITLE
Finish Roadmap for Infrastructure overhaul work

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#4990]
## User Story or Problem Statement
As a Ops Eng, I need clear understanding of where my work is going so I can be strategic about how we build the new infrastructure.

## Goal
_Have an Agile Roadmap for the  Infrastructure overhaul work_

## Acceptance Criteria
- [ ] _Create Roadmap with team_
- [ ] _Team approves of roadmap_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
