### ISSUE TITLE
Test appointments list with screenreader users

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#49903]
## Task Description
- Test the appointments list proof of concept with Veterans who use screen readers

## Resources
- [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/2022-appt-list-usability-screenreader/conversation-guide.md)
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/2022-appt-list-usability-screenreader/Research-plan.md)
- [Accessibility support ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55380#issuecomment-1478821894)

## Acceptance Criteria
- [x] Devs have completed proof of concept. Includes dummy data and working detail pages
- [x] Proof of concept can be accessed via a test user on staging
- [x] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/2022-appt-list-usability-screenreader/Research-plan.md) and [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/2022-appt-list-usability-screenreader/conversation-guide.md) are complete
- [x] Test is complete

**Comment by outerpress** [comment]
We're waiting for the POC to be accessible before moving forward with testing.

**Comment by outerpress** [comment]
Next steps:
- @outerpress asked for support for an accessibility expert in this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55380)
- @Cieramaddox will schedule time with @outerpress to do a pre-pilot study
- @Cieramaddox will schedule a pilot participant
