### ISSUE TITLE
Infra Overhaul: Devise & Test

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#4991]
## Problem Statement
We need to let users know what the changes we'd like to make to the infrastructure would look like and discuss how that affects them.

## Goal
Devise, build and socialize a low-effort hackable model that reflects what we would like the VSP infrastructure to look like.  Revise this model based on feedback from VSP platform service owners.

## Acceptance Criteria
- [ ] Have a diagram that illustrates stack, deploy, and infrastructure changes
- [ ] Have a low effort model people can play with
- [ ] Establish a focus group consisting of ops, be-tools, fe-tools, cms, and gids teams to review the model and diagrams

## Diagram Implementation
- Diagram current and desired tech stack, infra layout, deploy flow

## Model Implementation
- build a single node Vagrant file using Ubuntu 
- install docker
- install consul, vault, and nomad with configs and run them in "dev" mode
- create a fake app that builds with CNCF Buildpacks
- add sample deployment files to fake app
- write demo-quality deployment script and fake "trigger" via GH deployment api
- demo this with docs on how to use this model

## Feedback Implementation
- Get a rep from each team in a slack channel
- Setup a meeting to demo the model and show the diagrams
- Help folks with model, answer questions, etc.. take in feedback and adjust model for a few days
- Setup another meeting to discuss with goal to find and eliminate blockers or problems so that we can start real implementation

**Comment by ricetj** [comment]
@nathanhruby forgot I made this epic. The ticket under it can be closed or reworked anyway you like.

**Comment by nathanhruby** [comment]
did demo and sent recording to focus group along with supporting material
