### ISSUE TITLE
Create R&S page: Convert SGLI, VGLI, or FSGLI to a commercial policy

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#49932]
## Issue Description
As part of the migration work for life insurance, we're migrating this page: https://www.benefits.va.gov/INSURANCE/converting.asp

We'll need to:
- Create a new R&S page to explain the conversion process for all 3 programs (SGLI, VGLI, FSGLI)
- Remove the specific conversion info from the SGLI, FSGLI, VGLI pages

Source content for this work includes the legacy page and [this PDF](https://www.benefits.va.gov/INSURANCE/forms/SGL-133.pdf). (A previous content team worked on a [benefit hub page ](http://preview-prod.vfs.va.gov/preview?nodeId=5678 )for this content, but that was before R&S existed and I think it's likely easier to start from scratch here.)

---
## Tasks
- [ ] Draft R&S 
- [ ] Update SGLI, FSGLI, VGLI pages to remove detailed content and link to new R&S
- [ ] Review (Laura)
- [ ] Copyedit (Megan)
- [ ] Send to stakeholders
- [ ] Prepub/pub
- [ ] Set up redirect from legacy page

## Acceptance Criteria
- [ ] Legacy page is redirected to new R&S

**Comment by laurwill** [comment]
Noting that we'll pause on this until Danielle/Mikki confirm if this will move to R&S

**Comment by mistymg** [comment]
Moved to closed but not actually showing up as closed on board.
