### ISSUE TITLE
Finalize details and Publish landing

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#49931]
## Issue Description
Establish the landing page(s) for teams wanting SDT assistance in Mapping of a task, journey, or experience

Should we also consider broader intakes (research guidance, SD guidance, etc?)

[Draft in team Confluence space](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2429157514/Request+mapping+support)

## Tasks
- [x] Add to [questions brainstorming document](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2441707529/Brainstorming+for+intake+form+questions) by end of Tuesday 29 Nov
- [x] Team review of brainstorm doc
- [x] Workshop w/ team
- [x] Publish landing

## Acceptance Criteria
- [x] Required information for assistance is specified.
- [x] Landing allows user to learn what type of help is available
- [x] Landing allows user to understand what is needed to begin
- [x] Landing allows user to understand what sort of timetable is involved
