### ISSUE TITLE
Create R&S page: How to file a VA life insurance claim

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#49943]
## Issue Description
We need to migrate this legacy page: https://www.benefits.va.gov/INSURANCE/file_death_claim.asp 

We'll create a new R&S page with info on how to file for each type of life insurance program. Then we'll remove the detailed info about filing claims/links to claim forms from the benefit hub pages, and add links to this new page.

(A previous content team started a Drupal draft here: http://preview-prod.vfs.va.gov/preview?nodeId=6210. We can take useful content from there, but we don't need to follow their model.)

---
## Tasks
- [ ] Draft R&S
- [ ] Update related pages to link to R&S
- [ ] Review
- [ ] Copyedit
- [ ] Send to stakeholders
- [ ] Publish
- [ ] Set up redirect

## Acceptance Criteria
- [ ] Legacy page redirects to new R&S

**Comment by laurwill** [comment]
Pause until Danielle/Mikki confirm if this moves to R&S

**Comment by coforma-terry** [comment]
Rolled into life insurance migration when that picks up again
