### ISSUE TITLE
Consolidate User factories

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#49949]
## Description
Currently multiple vets-api modules use their own `User` factory files to create mocked users for unit specs. These should be turned into traits in the main `/spec/factories/users.rb` so that user creation for unit tests are consolidated in one place.

## Tasks
- [ ] refactor `modules/vaos` User factory into main User factory
- [ ] refactor `modules/health_quest` User factory into main User factory
- [ ] find any additional User factories within vets-api modules & refactor into main User factory
