### ISSUE TITLE
FE | Profile | Account Security | Documentation

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#49951]
## Background

Review Account Security product section in GitHub and add/update relevant FE documentation.

## Tasks
- [ ] Add analytics documentation on what events we are firing and where in the code they come from.
- [ ] Document Api calls and how they are set up in the FE code
- [ ] Map what error codes that might surface for a particular feature and the alert/messaging it maps to

## Acceptance Criteria
- [ ] Analytics documentation on what events we are firing and where in the code they come from added
- [ ] Document Api calls and how they are set up in the FE code added
- [ ] Map what error codes that might surface for a particular feature and the alert/messaging it maps to completed

**Comment by adamwhitlock1** [comment]
Since there was no FE docs for the Account Security page, I have added that page here:

https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/account_security/frontend_documentation.md

I added all of the main FE docs for that general page and have also added a section in the 'Extra Features' to document the Fiduciary Flag / Blocked Profile feature.
