### ISSUE TITLE
Profile Team | Sprint 88 | Nov 30 - Dec 13 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#49952]
## PTO/OOO/Unavailable

Sharon: 
Erica: 
Liz: 11/30
Christina: 
Adam: 
John: 12/12 & 12/13
Tom: 
Samara: 

## Retro Board is open:
[Sprint 87 - Part 1](https://www.reetro.app/board/6203c8f3edfa6100174612bb/63582b1820452ba44e70ff2b)
[Sprint 87 - Part 2](https://www.reetro.app/board/6203c8f3edfa6100174612bb/63582bf120452ba44e7104a4)

#### FE - John
- [ ] ~#49374 Update Button Pairs (2 pts)~ - **(removing from sprint due to JC OOTO for 2 days)**
- [x] #46195 Use TTY Prop in Telephone Component (roll-over from sprint 87)
- [x] #49843 Updates to TTY (roll-over from Sprint 87 needs validation)

#### FE - John
- [x] #50007 Account Security screen | Remove Blue Box (1 pt)
- [ ] #45872 Add Headings back into Alerts (2 pts)

#### FE - Adam

- [x] #49847 KPI Dashboard | Addition of Start/Failed to AP (1 pt)
- [x] #49963 Fiduciary Flag | Set up Custom Analytics (2 pts)

#### Backend - Tom
- [x] #50019 Remove FF (2 pts)
- [x] #50085 Login to Local Setup (2 pts)

#### Backend - Tom
- [ ] #49654 Onboarding Document for BE dev (3 pts)
- [x] #50131 Review Backend Documentation (2 pts)
- [x] #50516 Update Swagger and Docs for MHV endpoint (2 pts)

#### Frontend - Adam
- [x] #49951 Account Security | Documentation (2 pts)
- [x] #50130 Review Frontend Documentation (2 pts)

#### Design - Liz
- [x] #49118 Documentation | Fiduciary Flag Alert Across Profile (3 pts)
- [x] #50124 Review Design Documentation (? pts)

#### Design - Christina
- [x] #47478  Update Documentation for Military Alerts 
- [x] #50124 Documentation | Review Design Documentation
- [ ] #49845 TTY Design Updates

#### Product - Sharon, Erica
- [x] #50269 Documentation | Review Test Cases for User 36
- [ ] #50686 Contact Center Review for Profile - Misc Updates

#### PM  - Sharon
- [x] #48739  Update Post Launch Metrics (after Dec 1)

**Comment by SKasimow** [comment]
@SKasimow - testing GitHub notifications
