### ISSUE TITLE
Caregiver MVP

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#4996]
## High Level User Story
As a Caregiver, or a Veteran with a Caregiver, 
I want it to be easier to apply for the Program of Comprehensive Assistance for Family Caregivers (PCAFC)
So the caregiver can receive training, benefits, and support from the VA.

## Hypothesis or Bet
**If** _we digitize the 1010-CG form_ **then** _more Caregivers will apply to the program with confidence in the process_.

## OKR
Increasing the number of applications to the Caregiver program.

### Launch MVP on VA.gov

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## Plan
- [] ~**[Define] Kickoff-Intent**~ happened before VSP Collaboration Cycle rollout
- [x] **[Define] Design intent** - #(ticket)
- [x] **[Discover] Usability Testing Prep** - #(ticket)
- [x] **[Discover] Research Plan Review** - #(ticket)
- [x]  **[Discover] IA Request** - #6939
- [x] **[Discover] Analytics Request** - #8081
- [ ] **[Build] Contact Center Review** - #(ticket)
- [x] **[Build] Privacy/Security Review** - See [va.gov-tem-sensitive ticket](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team-sensitive/117)
- [ ] **[Build] Staging Review** - #(ticket)
  - [ ] Release plan - #(ticket)
  - [ ] QA test plan - #(ticket)
  - [ ] [Accessibility checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#required-accessibility-checklist-for-staging-review) - #(ticket if necessary)
- [ ] **[Validate] Post-launch checkin** - #(ticket)
- [ ] **[Validate] Launch Full A11y Review** - #(ticket)

## Acceptance Criteria
- Determine what's necessary/what's not and the associated timeline

## Reference
- [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)
- [Accessibility staging review preparation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation)

## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team**

**Comment by meganhkelley** [comment]
Current status of Caregiver MVP <> VSP Collaboration Cycle: 

As of 7/17/20, the following VSP reviews are required before the Caregiver MVP is launched to users _(this info is also captured in checklist above)_:

- [ ] Contact Center review 
- [ ] Staging review (includes review of content, design, QA, accessibility, release plan, and IA) 

The Caregiver MVP is currently in development; final designs & implementation have not yet been approved by VSP or VSP's DEPO leads — this is expected at this stage and will be addressed during the staging review.

VSP understands that the VSA Caregiver team has strict requirements for the MVP driven by the Caregiver program team. The approach we will take for the staging review is as follows: 

- Full user flow & implementation will be reviewed by VSP as part of a [standard staging review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review)
- Required VSP feedback (such as discrepancies between form and design system) will be addressed by VSA Caregiver team before MVP launch
- Any required VSP feedback that the VSA Caregiver team cannot address before launch will be bubbled up to VSP's DEPO lead to grant an exception as applicable, which will be documented on this issue ticket or the one for the staging review
- If the VSA Caregiver team makes significant changes to the MVP between staging review and launch, the team will connect with VSP to discuss whether additional review is warranted

This approach has been viewed and approved by
- [X] VSA Caregivers Product Manager: @ala-yna 
- [ ] VSA Caregivers DEPO Product Owner: @ccgongie 
- [ ] VSP Collaboration Cycle Wrangler: @mandifrances 
- [ ] VSP Product lead @andreahewitt-odd 
- [X] VSP DEPO lead: @KevinMHoffmanUSDS
