### ISSUE TITLE
[FE] Update Staging Tool to Honor the Change in the Early Guardrail

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#49968]
## Tasks
- [x] [FE] **Update Staging Tool to Honor the Change in the Early Guardrail**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by acrollet** [comment]
no issues have been reported, closing this out.
