### ISSUE TITLE
FE | Profile | Fiduciary Flag | Set up Custom Analytics

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#49963]
## Background

We want to be able to see how frequently the fiduciary flag is being used to block access to a Profile account on VA.gov.

To implement tracking we will need to set up GA custom event tracking (includes deceased, incompetent and fiduciary) and roll under the umbrella term of "Fiduciary Flag" for reporting purposes.

## Tasks

- [x] Set up custom event as follows: 
- Event Action: Status: {{Fiduciary Flag Views} - Title: {{We can't show your information}}- Click Text: {{}}
- [x] Conduct Unit tests 
- [x] Run E2E tests covering current code and regression
- [x] All axe checks pass
- [ ] Test with PM in staging and review reporting
  

## Acceptance Criteria
- [x] Complete all unit testing
- [x] End-to-end tests showing 0 violations
- [x] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)? PM
- How can this work be validated? Google Analytics
- What updates need to be made (e.g. product outline, use cases, contact center guide) - updates noted in original dev ticket

## Associated Tickets
- [#47841](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47841)

**Comment by adamwhitlock1** [comment]
I've got this up in staging now @SKasimow 

the event looks like this in data slayer:

![Screen Shot 2022-12-07 at 9.18.17 AM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/a73f08cb-3513-499e-8986-71dd612b9de2)

**Comment by SKasimow** [comment]
Set up widget and seeing events come through....closing
