### ISSUE TITLE
[FE] - refine long translation keys

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#49966]
## Description
Some of our keys are super long, do an audit of the long ones and refine them to be shorter.

Give list of changed keys to Lori to communicate to state dept.

## Tasks
- [ ] [FE] make list of long keys to change
- [ ] [FE] update keys to shorter version
- [ ] [FE] send list to Lori
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Here is a list of changed keys:
| **Before**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | **After**                                                              |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------|
| for-questions-about-how-to-fill-out-your-pre-check-in-tasks-or-if-you-need-help-with-the-form                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | for-questions-or-help-with-pre-check-in                                |
| if-you-dont-live-at-a-fixed-address-right-now-well-help-you-find-the-best-way-to-stay-connected-with-us                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | if-you-dont-live-at-a-fixed-address                                    |
| online-check-in-isnt-available-for-this-appointment-check-in-with-a-staff-member                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | online-check-in-isnt-available-check-in-with-a-staff-member            |
| this-appointment-isnt-eligible-for-online-check-in-check-in-with-a-staff-member                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | this-appointment-isnt-eligible-check-in-with-a-staff-member            |
| we-ask-you-to-provide-the-information-in-this-questionnaire-to-help-with-your-medical-care-under-law-38-u-s-c-chapter-17-its-your-choice-if-you-want-to-provide-this-information-if-you-choose-not-to-provide-this-information-it-may-make-it-harder-for-us-to-prepare-for-your-visit-but-it-wont-have-any-effect-on-your-eligibility-for-any-va-benefits-or-services-we-may-use-and-share-the-information-you-provide-in-this-questionnaire-in-the-ways-were-allowed-to-by-law-we-may-make-a-routine-use-disclosure-of-the-information-as-outlined-in-the-privacy-act-system-of-records-notice-in-24va10a7-patient-medical-record-va-and-following-the-veterans-health-administration-vha-notice-of-privacy-practices | privacy-act-statement-text                                             |
| we-can-better-follow-up-with-you-after-your-appointment-when-we-have-your-current-information                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | we-can-better-follow-up-with-when-we-have-your-current-information     |
| well-come-get-you-from-the-waiting-room-when-its-time-for-your-appointment-to-start                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | well-get-you-from-waiting-room-when-time-for-your-appointment          |
| were-sorry-we-couldnt-match-your-information-to-our-records-please-ask-a-staff-member-for-help                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | were-sorry-we-couldnt-match-your-information-please-ask-for-help       |
| your-appointment-started-more-than-15-minutes-ago-we-cant-check-you-in-online-ask-a-staff-member-for-help                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | your-appointment-started-more-than-15-minutes-ago-ask-for-help         |
| youre-also-responsible-for-protecting-your-personal-health-information-if-you-print-or-download-your-information-or-share-it-electronically-with-others-youll-need-to-take-steps-to-protect-it                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | youre-also-responsible-for-protecting-your-personal-health-information |
| during-pre-check-in-you-can-review-your-personal-emergency-contact-and-next-of-kin-information-and-confirm-its-up-to-date-this-helps-us-better-prepare-for-your-appointment                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | during-pre-check-in-you-can-review-your-contact-information            |
| sorry-we-couldnt-find-an-account-that-matches-that-last-name-or-date-of-birth-please-try-again                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | sorry-we-couldnt-find-an-account-that-matches-last-name-or-dob         |
| your-provider-will-call-you-at-your-appointment-time-you-may-need-to-wait-about-15-minutes-for-their-call-thanks-for-your-patience                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | **your-provider-will-call-you-at-your-appointment-time**               |

**Comment by brianseek** [comment]
@loripusey ^^

**Comment by loripusey** [comment]
I forwarded these changed and deprecated keys to Randi to forward to the State Department on 12/19; 
A copy of these changed & deprecated keys can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/translations)

**Comment by sarahknoppA6** [comment]
closed per standup update
