### ISSUE TITLE
Update VA Form 28-1900 name on VA.gov static pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#49980]
## Issue Description

The name of VA Form 28-1900 has changed to Application for Veteran Readiness and Employment For Claimants with Service-Connected Disabilities (Chapter 31, Title 38, U.S.C.). We need to update this on the [How to apply for VR&E](https://www.va.gov/careers-employment/vocational-rehabilitation/how-to-apply/) page.

This is also on the Find Forms page, but we can't access that part of the page and another team is handling it. 

We should also do a search to confirm that this is not on other VR&E or career static pages.  

## Tasks
- [x] Update page (Katherine)
- [x] Copyedit (Megan)
- [x] Publish (Megan)
- [x] Notify stakeholder that changes are live

## Acceptance Criteria
- [x] New form name is live on the site

**Comment by RLHecht** [comment]
@laurwill Can you update the form name on the Find a Form page too? We got the go ahead to make these changes ahead of the online form so we can publish the 2 pages tomorrow.

**Comment by laurwill** [comment]
Done! Ready for you to review and publish tomorrow.

**Comment by RLHecht** [comment]
I reviewed and published this. moving to validate.

**Comment by RLHecht** [comment]
These pages are both live. I'll notify the stakeholder. Closing ticket.
