### ISSUE TITLE
FE | Profile | Update Custom Radio Button Component | Tech Debt

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#49983]
## Background

After researching, dev found the following:

> We are not currently using the soon to be deprecated RadioButtons React component on the Profile. The only area where a similar input is being used is on the Notification Settings page, but the code is instead using a custom built input component.
> 
> For reference, the custom radio button is called [NotificationRadioButtons](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/profile/components/notification-settings/NotificationRadioButtons.jsx)
> 
> This ticket is to address this custom component in the future and would be considered tech debt, since it is not using any Design System component at its core and should adhere to that system for overall maintainability.

## Tasks
- [ ] Conduct Unit tests 
- [ ] Run E2E tests covering current code and regression
- [ ] Notify PM if this needs to be deployed to Staging behind feature flag
  

## Acceptance Criteria
- [ ] Complete all unit testing
- [ ] End-to-end tests showing 0 violations
- [ ] All axe checks pass
- [ ] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [ ] Confirm PM has opened a new ticket to deploy changes to Production using feature flag, if needed

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)?
- How can this work be validated?
- What updates need to be made (e.g. product outline, use cases, contact center guide)

## Associated Tickets
- #49468

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by mtcA6** [comment]
closed appears to be a duplicate
