### ISSUE TITLE
Internal - Profile Edge Case - Data Modeling

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#49994]
## Issue Description
This ticket is a follow up to the [Discovery ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49063) for the [Profile edge case request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46861).

The purpose of this ticket is to complete the data modeling needed to create the new datasets for the Profile KPIs.

[KPI worksheet](https://docs.google.com/spreadsheets/d/15NKyGxXm9d43iGUoWMxKmo0NZv4gW3dX1sFIeVhGt_I/edit#gid=2091635579)
[Mock up](https://docs.google.com/presentation/d/1zzFSi5ZfIDqy5buQZX1NwRjvCA-dwPTDYOaSidCwZlw/edit#slide=id.g11b31d375b2_0_0)
[New dataset request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=obrienjulie&labels=analytics-insights&template=analytics-internal-dataset-request.md&title=Analytics+Internal+-+New+Dataset+Request+Template)

---
## Tasks
- [x] Complete mock up based on agreed upon KPIs in support of this ticket - meeting 11/29 to finalize)
- [ ] Define data needs (nd complete data request ticket as part of standard process)
- [ ] Create BQ tables/views/dataset as needed 
- [ ] QA data

## Acceptance Criteria
- [ ] Datasets have been completed and handed off to analyst to create dashboards.
---

**Comment by chloedotbrown** [comment]
_(Cross-posting, since we have both internal and external tickets for this work)_

@dorseypa1 and @michelle-dooley - Sharon confirmed on ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/49847 that her team has completed this implementation, meaning we can begin modeling work.

Phil, for complete list of events, please see the most recent table in Sharon's comments above. If you have any questions, please feel free to reach out!

**Comment by dorseypa1** [comment]
Thanks Chloe, I'll review the request.

**Comment by michelle-dooley** [comment]
This work will be continued in #51415
