### ISSUE TITLE
Write VA blog content brief to prepare for meeting with VEO

### ISSUE THREAD

**Issue by tygindraux** [department-of-veterans-affairs/va.gov-team#49991]
## Description
We need to write a content brief so we're clear on the purpose of the blog (to raise awareness of Login.gov) and can work with or support the VEO. The blog will be posted on the [VA blog](https://news.va.gov/).

The VEO (Veterans Experience Office) will help us shape this content using the VA content approach, and we'll be able to pull what we need from it (or at least that's what we think right now). Our meeting with the VEO is on Wednesday, 30 November.

## User Story
As a Veteran, I need to understand what Login.gov and its benefits, so that I know why I should set up Login.gov as my primary or additional credential.
As a Veteran, I need to understand how to set up Login.gov, so that I can try and set up Login.gov on my own terms.
As a Veteran, I need to know where to go for help if I face an issue while setting up Login.gov, so that I can finish setting up Login.gov.

## Tasks
- [x] @CarlDickerson, @tygindraux: Fill in content pitch template [on Mural](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1661981795206/320d5e5f8c4c2cd0a4e6b757d5830c42110d1414?wid=0-1669160071197)
- [x] @elizabethkochBT: Answer questions to help us fill out content pitch template [on Mural](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1661981795206/320d5e5f8c4c2cd0a4e6b757d5830c42110d1414?wid=0-1669160071197)
- [x] @CarlDickerson, @tygindraux, @elizabethkochBT: Meet to sync before meeting with VEO on Wednesday, November 30
- [x] @tygindraux move brief to Github (from Google Doc)

## Definition of done
- [x] Content brief has been written
- [x] Preparation for meeting is complete
- [x] Content brief is in Github

**Comment by tygindraux** [comment]
@elizabethkochBT – Can you tie this to the appropriate epic?

**Comment by tygindraux** [comment]
Content brief is [drafted](https://docs.google.com/document/d/1wLaUZjvlG3YxCsoaLNHU79XrtMEJAoq2PmZkqCVII2o/edit?usp=sharing). We need to move this to Github before we complete this task.
