### ISSUE TITLE
Aggregate VBMS logs since launch

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#49993]
## Issue Description
We need to provide VBMS and leadership teams with the logs VA.gov has tracked since debt letters has launched

---
## Tasks
- [x] Aggregate logs in AWS
- [x] Aggregate logs in Grafana
- [x] Create script to extract desired information
- [x] Hand over to appropriate contact

## Acceptance Criteria
- [x] Leadership has received the data they need from VODA
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
Stakeholders informed us on Friday, November 18 that their leadership does want an audit of VBMS Letter downloads.  Full details will be discussed in a meetings set up for Nov 29th this work is to aggregate the logs we have available ahead of that discussion. This work will take priority over other assigned sprint work.

**Comment by ScottyRJames** [comment]
Rolling over due to collecting reporting FSR numbers and bug discovery
