### ISSUE TITLE
FE | Profile | Account Security screen | Remove Blue Box

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#50007]
## Background

Modifications to the Account Security screen for users [sketch file](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/a/Jn41Kgk).

Change requested is to remove the "blue box" near bottom of the page and text "Have questions about signing in to VA.gov".

## Tasks
- [x] Remove "blue box" at bottom of page for **all** user types (eg LOA1, LOA3)
- [x] Conduct Unit tests 
- [x] Run E2E tests covering current code and regression
- [x] Notify PM if this needs to be deployed to Staging behind feature flag
  

## Acceptance Criteria
- [x] Complete all unit testing
- [x] End-to-end tests showing 0 violations
- [x] All axe checks pass
- [x] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [ ] Confirm PM has opened a new ticket to deploy changes to Production using feature flag, if needed

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)?
- How can this work be validated?
- What updates need to be made (e.g. product outline, use cases, contact center guide)

## Associated Tickets
- #

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
@cgednalske  looks good to me; no longer see the blue box. Do you want to double-check before I close?

**Comment by cgednalske** [comment]
@SKasimow I tried a few different staging users and it looks good there!

**Comment by SKasimow** [comment]
I just checked prod using my LOA3 account and LOA1 account...not a blue box in sight. Think we can call this done!
