### ISSUE TITLE
BE | Profile | Remove Feature Flags

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#50019]
## Background
Remove the following unused feature flags for the Profile page:
- [x] BAI
- [x] direct_deposit_cnp
- [x] direct_deposit_edu
- [x] direct_deposit_vanotify

Original Ticket and comment...
https://github.com/department-of-veterans-affairs/va.gov-team/issues/49647#issuecomment-1329222139

## Tasks
- Remove any BE references to the flags listed above from local, staging, and prod environments.

## Acceptance Criteria
- Ensure features are working correctly in staging and production.
