### ISSUE TITLE
[EVSS to Lighthouse] Get sandbox credentials to enable testing

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#50028]
## Background
All of the backend devs will need to request sandbox credentials from lighthouse in order to work on this project. Having sandbox credentials will allow us to make requests to lighthouse's sandbox environment

## Considerations
* Request sandbox credentials [here](https://developer.va.gov/onboarding/request-sandbox-access)
* Make sure to select the `Benefits Claims API` checkmark under the `Client Credentials Grant APIs` section. Check any other APIs that you may be interested in having access to (I would recommend the Benefits Reference Data, Benefits Intake, and VA Forms APIs under the `Standard APIs` section and Benefits Claims API under the `Authorization Code Flow APIs` section)
* I used these 4 commands to generate the requested OAuth public key:
```sh
# Generate a private key
openssl genrsa -out key.pem 2048

# Generate the public/private key pair
openssl rsa -in key.pem -outform PEM -pubout -out public.pem

# Generate the jwk key pair
step crypto jwk create jwk.pub.json jwk.json --from-pem key.pem --alg RS256

# Copy the public jwk key to clipboard
pbcopy < jwk.pub.json
```

## Tasks
- [x] @samcoforma has sandbox credentials
- [x] @jerekshoe has sandbox credentials
- [x] @kjduensing has sandbox credentials

**Comment by kjduensing** [comment]
In addition to the commands Jerek provided above, I had to generate a private key as well with

`openssl genrsa -out lhkey.pem 2048`

**Comment by jerekshoe** [comment]
> In addition to the commands Jerek provided above, I had to generate a private key before running the first step with:
> 
> `openssl genrsa -out lhkey.pem 2048`

Good call. I added that to the description above
