### ISSUE TITLE
[EVSS to Lighthouse] we're storing claims in the postgres db, figure out why and if we need to do so in v2 as well

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#50032]
## Background
The current implementation of the EVSS claims service is storing claims in the `vets-api` database. We need to determine what the reason for this is and if we need to do this as well. Preferably we would not be storing claims in the DB. 

## Tasks

- [x] Look around in our own code to see if we can deduce the "why"
- [x] Determine whether additional investigation and/or collaboration with other teams is needed. 
- [x] Discuss with Lighthouse their uptime commitments

## Acceptance Criteria

- [x] We understand why claims are currently being stored in the DB
- [x] We can determine whether we need to store claims in the DB as part of v2
- [x] Document potential PII violations of the current approach
- [ ] Arrive at consensus decision with Lighthouse

**Comment by samcoforma** [comment]
Claims are saved in the db so that Sidekiq can be used to send them over asynchronously.

I spoke with Michel McDonald and Kyle Soskin, and some points were brought up:

* "The downstream systems involved in submitting a claim make it unfeasible to NOT save off the claims like we do.  Sidekiq has an automatic retry system in place...so for example if one of the downstream systems is down, sidekiq will automatically retry running submission job in the future."
* "having that claim data is just invaluable. Sometimes we hit bugs in our code that prevent the claim from being submitted.  Having the claim saved, we can fix the code and resubmit it."
* "Also, for answering ad hoc questions.  Frequently, leadership would turn to me to answer questions...for example I was somewhat involved in the hypertension fast track initiative.  Originally, fast track claims targeted hypertension only claims.....so by having that claim data, i was able to provide some counts around how many single issue hypertension only claim were historically submitted.  There is no VA API that I know about to go after those kind of counts, so having that data in postgress is very useful for that sort of thing."
* "Also, for debugging patterns...really hard to talk specifically about this, but sometimes we find a bug and we can find other users that might have hit the same bug using the saved claim."
* "if we did not save it off like we do, developers lives would be harder and we would be saying NO a whole bunch more to questions like "Can you help this vet get his 526 submitted?", "what went wrong?" "How many claims have this issue\are from the state of Cali\...all that stuff""
* "Also, if we didn't save it, users would have to fill out the whole form all over again to resubmit if something goes wrong.  It's pretty well established that for some number of vets, filling out that form is traumatic, vets are encouraged not to hold back and to put all kind of details in those claims, recalling those and writing out those details IS A BARRIER to them submitting and getting help.... If I had to argue for saving it, this would be my #1 argument"
* "after the recent issues with 526 submissions that I have surfaced, the VA is glad we have that info at the moment"
* "ability to troubleshoot is easier (but so would only deleting info after a success if we implemented)"
* "the ability to determine trends and mine data, such as the "prediction model" for contentions that team/squad 3 is trying to make"

Also, @kylesoskin requested that we leave this ticket as an open conversation for now if we can. So, I'm going to hold off from closing it for the moment.

**Comment by samcoforma** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/124

**Comment by samcoforma** [comment]
To-do: reach out to Michael Harlow to see if there are additional reasons for caching EVSS claims.

**Comment by samcoforma** [comment]
From Michael: "Will your V2 implementation be using the Lighthouse claims status endpoint? If so, we should ask the LH team if they think consumers caching is required. If you will still be hitting EVSS in V2, then I think the current cache mechanism will be needed."

**Comment by jacobworrell** [comment]
Lighthouse is on board with not caching.
