### ISSUE TITLE
[EVSS to Lighthouse] Figure out who else is using our existing services, and start communicating with them. Let them know what's changing and what they need (mobile, etc)

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#50030]
## Background
Once we have created a mapping between the existing claims status API endpoints and the new Lighthouse ones, we need to communicate this information to any other teams that are using our service

## Context
* The mobile team has already reached out to ask for information on the new service
* The other consumer of our service is the RRD service that fast tracks benefits claims based on specific claim types

## Tasks
- [x] Create attribute mapping document
- [x] Send to mobile and request feedback

## Acceptance Criteria
- [x] Attribute mapping document has been created
- [x] Document has been sent to mobile
- [x] Feedback has been dealt with

**Comment by jacobworrell** [comment]
@saderagsdale do you know who manages the RRD service?

**Comment by saderagsdale** [comment]
@jacobworrell Check in [#benefits-rrd-health-evidence](https://dsva.slack.com/archives/C01BVF2A3V0)
