### ISSUE TITLE
[EVSS to Lighthouse] clean up old code after release for Claim Status end points

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#50037]
## Background
After we have completed our launch of the new Lighthouse-backed APIs, we need to remove the old code that holds up the existing service as it will no longer be needed at that point and will only clutter up the codebase

## Considerations
* This will include any tests, specs and mocks that are in the `vets-api-mockdata` repo`

## Tasks
- [ ] Remove any code associated with the old service
- [ ] Remove tests associated with the old service code
- [ ] Remove mocks from the `vets-api-mockdata` repo
- [ ] Remove feature toggle

## Acceptance Criteria

- [ ] Any trace of old service removed from code base (referring to the inventory we created)

**Comment by jacobworrell** [comment]
@jerekshoe did we ever do this or does this still need to be done?
