### ISSUE TITLE
[EVSS to Lighthouse] determine what code is associated with/inventory the code that is associated with claim status so we can get rid of it in the future

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#50031]
## Background
Make a list of all the files associated with the EVSS version of the api so we can remove it. 

## Tasks

- [x] identify and record all files associated with EVSS version

## Acceptance Criteria

- [x] Thorough list of files we would like to eliminate

**Comment by kjduensing** [comment]
/modules/claims_api/app/controllers/claims_api/
v1/
application_controller.rb:86 - instantiates service, phsyical
claims_controller:
17 - evsserror, physical
29,31,32,33,35,37 - reference to AutoEstablishedClaim model, physical
36 - comment, logical
55,56 - EVSS error handling, physical
59 - error message, logical
64 - method name, logical
V2/

**Comment by kjduensing** [comment]
Switch to surround comments for easy parsing/deletes

**Comment by kjduensing** [comment]
Frontend routes to check and tag:
- [ ] `/claim_letters`
- [ ] `/appeals`
- [ ] `/evss_claims_async`
- [ ] `/evss_claims_async/{id}`
- [ ] `/v0/evss_claims/${id}/request_decision`
- [ ] `/v0/education_benefits_claims/stem_claim_status`

**Comment by jacobworrell** [comment]
Awaiting internal review from @jerekshoe
