### ISSUE TITLE
[EVSS to Lighthouse] modify FE code for list view to use feature toggle

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#50036]
## Background
We will need to update the FE code for the list view of CST to use different components based on the value of the feature toggle. This will require creating copies of a few different containers/components and updating them to reflect the new attribute mapping

## Tasks
- [x] Create copies of necessary components and update them
- [x] Selectively show the correct versions of the components based on the feature toggle value
- [x] Use the feature toggle value to determine which API is called (Lighthouse or EVSS)

## Acceptance Criteria
- [ ] Copies of components are created
- [ ] Correct version of components are shown based on feature toggle value
- [ ] Correct API is being called based on feature toggle value
- [ ] Add new tests

**Comment by jacobworrell** [comment]
Break into two tickets, one for list and one for details.
