### ISSUE TITLE
Roadmap and Sprint Planning for CARMA Integration

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#5004]
## User Story:
As the Caregiver team, we need to come up with a plan to integrate with CARMA so that we can coordinate with that team.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] Identify Technical point person
- [ ] Work with technical person to build roadmap
- [x] Write tickets in Zehhub
- [x] Add detail to https://app.zenhub.com/workspaces/vsa-5dcabe208aade000013aafba/issues/department-of-veterans-affairs/va.gov-team/5326

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
* Tickets are created
* Roadmap is documented in Github

## Configuration
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinmirc** [comment]
Hey @ala-yna,

Below are the tickets (with sizes) for completing the CARMA integration. I've put them in an order that I consider would be most appropriate for implementing them (assumes no veteran validation).
- #5453 (Zenhub Link)[https://app.zenhub.com/workspaces/vsa-5dcabe208aade000013aafba/issues/department-of-veterans-affairs/va.gov-team/5453]
- #5454 (Zenhub Link)[https://app.zenhub.com/workspaces/vsa-5dcabe208aade000013aafba/issues/department-of-veterans-affairs/va.gov-team/5454]

Please keep in mind that I'm assuming CARMA will expose a Salesforce apexrest service interface, similar to the what the other salesforce connections in vets-api have (VIC and GIBFT). This would allow me to reuse an existing Salesforce Client for authenticating (reducing our scope). Requirements and scope may change if these were incorrect assumptions. Still waiting to hear back from the CARMA about:
- What the endpoints are for each environment.
- What my auth credentials are for consuming the endpoints.
- What the data contract will look like (for successful and invalid submissions).
