### ISSUE TITLE
[FE] Healthcare: Launch Drupal API Changes

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#50043]
## Background
Release Durpal API changes that were completed in #47956  for Cerner information in coordination with Public Websites team. Their launch is planned for 12/14. We should confirm the launch is still on for that day and release our changes accordingly. 

## Tasks
- [x] PM to confirm Public Websites team will launch on 12/14
- [x] FE to release changes

## Acceptance Criteria
- [ ] Drupal API implementation is in Production

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_
- _How can this work be validated?_
