### ISSUE TITLE
CST: Determine why last page visited is being tracked

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#50048]
## Background
Currently the CST keeps track of the last page that has been visited within the application. We need to determine what this is being used for and if it can be removed.

## Tasks
- [ ] Determine what this functionality is used for
- [ ] Determine if it can be removed or if it serves a useful purpose

## Acceptance Criteria
- [ ] The purpose of this functionality has been determined
- [ ] Functionality has been removed, if deemed unnecessary

**Comment by pmclaren19** [comment]
This ticket is related to https://github.com/department-of-veterans-affairs/va.gov-team/issues/94937. We can probably close one of these. Thoughts @jerekshoe ?
