### ISSUE TITLE
Address validation: End-to-end testing

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5005]
## Background
We need to create a test script for some browser-based end-to-end testing that demonstrates the functionality that came out of the research.  This includes making sure we go through possible edge-cases.

## Tasks
- [ ] Write tests for end-to-end testing for address validation
- [ ] Conduct end-to-end testing
- [ ] Work with VSP to make sure these get into the regression suite (if applicable)

## Acceptance Criteria:
- [ ] All tests pass end-to-end testing.

**Comment by bradl3yC** [comment]
PR #11790
