### ISSUE TITLE
Update special monthly compensation rates for 2023

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#50053]
## Issue Description
The rates on the [special monthly compensation rates](https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/) page change as of December 1, 2022. 

We need to update this page with the new content and create a past rates page. 

New rates:  

Here is guidance on how to clone and create new rates pages: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/how-to-update-rates-pages.md

## Tasks
- [x] Clone page to create past rates page
- [x] Update current rates page with new rates
- [x] Copyedit past rates page (Megan)
- [x] Copyedit current rates page (Megan)
- [x] Publish both pages (Megan)
- [x] Add newest past rates page and remove oldest rates page from left nav (Megan)

## Acceptance Criteria
- [x] 2023 special monthly compensation rates are live
- [x] 2022 past rates page is live
- [x] Left nav is updated

**Comment by RLHecht** [comment]
@laurwill Here is the 2023 page: http://preview-prod.vfs.va.gov/preview?nodeId=991

And here is the past rates page: http://preview-prod.vfs.va.gov/preview?nodeId=51365

For some reason I can't copy the spreadsheet into this ticket for you to check against so I'm going to slack it to you.

**Comment by laurwill** [comment]
Looks good @RLHecht ! Ready to publish. 

And you can disregard my slack about the table headers — I realized that we already have this high-level backlog ticket that will encompass this: https://github.com/department-of-veterans-affairs/va.gov-team/issues/46060#event-7236478625

**Comment by RLHecht** [comment]
These pages are published. Moving to validate.

**Comment by RLHecht** [comment]
These changes are live. Closing ticket.
