### ISSUE TITLE
Schedule new Platform member (Lillian Boot) for orientation

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#50065]
### Tasks

First day was Monday, Jan 30.

- [x] Determine the best office hours day 3 weeks from their first day. (Tuesday, February 21)

- [x] Message Lillian on Slack on (February 12 or 13) to let them know we will be meeting with them on that day.

- [x] Zoom invite changes:
- Add new team member to invite
- Change all Platform Content attendees to regular (vs optional)
- Update meeting title to: Platform Content Orientation for [enter new team member name]
- Update meeting body to the following: 

Hi [enter new team member name],

Welcome to the Platform! You do not need to prepare anything for this meeting. We are looking forward to introducing our team, the Platform Content team, to you and meeting you.  If you have any questions in the meantime, feel free to drop by our Slack channel #platform-content or to say hello. See you then. Thanks!

Zoom link: https://us06web.zoom.us/j/84651883090?pwd=YmdhM0dDemRmZWpVRUdHVmxRaG1Tdz09
