### ISSUE TITLE
[FE] Clarify Message when using Pre-Check-in on Day-of Appointment after Check-in Window

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#50083]
## Wireframe
[wireframe](https://share.goabstract.com/5db20262-46ec-4f94-9ca1-58bffbdc1789)

## Tasks
- [ ] [FE] **Add blue info box with content (see wireframe)**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [x] Read ticket details and verify that ACs are met
- [x] Review code in PR
- [x] Run branch locally
- [x] Check that new and updated translations use new keys
- [x] Check for hardcoded strings

**Comment by loripusey** [comment]
@wullaski I thought you released this already?

**Comment by acrollet** [comment]
@zach-park to validate this issue, @wullaski will post screenshots.
