### ISSUE TITLE
Add link to instructions to request research repo access to Orientation ticket 

### ISSUE THREAD

**Issue by naomimarcussen** [department-of-veterans-affairs/va.gov-team#50081]
## User Story
_"As a VFS researcher, I want to be able to add my research studies to the research repo, so that other researchers and designers can learn from my findings."_

Assignee: 
Peer Reviewer: 

## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
The [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist) asks researchers to add their study to the research repo, but we don't clearly provide instructions for how to request access to the repo. It would be helpful to add a link to the [Request access to tools document](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-VAResearchRepository) from the [Orientation ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team%2C+analytics-insights%2C+analytics-request&template=orientation-epic.md&title=Platform+Orientation+Template+%5BYour+name+here%5D) in the Practice area for designers & researchers.

[See Slack thread.](https://dsva.slack.com/archives/C0216PL32HJ/p1669739638089409)

## Impacted Artifacts
[Request access to tools](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-Additionalaccessforresearchersanddesigners) 
[Orientation ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team%2C+analytics-insights%2C+analytics-request&template=orientation-epic.md&title=Platform+Orientation+Template+%5BYour+name+here%5D)

## Tasks
- [ ] Add a link in the Additional access for researchers and designers section of the [Orientation ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team%2C+analytics-insights%2C+analytics-request&template=orientation-epic.md&title=Platform+Orientation+Template+%5BYour+name+here%5D) that goes to the Additional access for researchers and designers section of the [Request access to tools](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-Additionalaccessforresearchersanddesigners).

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Make sure links working

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
No longer necessary as the research repo has been added to the vets.gov-write gh team
