### ISSUE TITLE
Content changes to NADL page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#50082]
## Issue Description

Stakeholder Raleigh Contreras asked us to make content edits to the [Native American Direct Loan](https://www.va.gov/housing-assistance/home-loans/loan-types/native-american-direct-loan/) page. 

These updates include adding new H2 sections to the page and adding more info to the "How do I get an NADL?" section.

Before we make these edits, we need to assess whether these changes are Veteran-facing, aren't already on this page or another housing page, and are needed. We will also need to edit for plain language and VA.gov voice and style.

Content provided: [https://app.zenhub.com/files/133843125/9a53dd12-b87f-46bc-86d1-89fc675420cd/download](https://app.zenhub.com/files/133843125/9a53dd12-b87f-46bc-86d1-89fc675420cd/download)

## Tasks
- [ ] Assess content
- [ ] Rewrite in plain language
- [ ] Review (Laura)
- [ ] Send to stakeholder for approval
- [ ] Copyedit (Megan)
- [ ] Publish (Megan)

## Acceptance Criteria
- [ ] Updated content is live on the NADL page

**Comment by laurwill** [comment]
Update: I emailed Raleigh to share our suggested approach. We can start this work in the upcoming sprint.
