### ISSUE TITLE
[QA] Address Validation: Create test plan

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5010]
## Background

Epic #3948

## Tasks
- [x] Make a list of all scenarios (test cases)
- [x] Have Samara review/approve test cases
- [x] Have Erik review/approve test cases

## Acceptance Criteria:

- [x] Test Plan reviewed, complete, and ready to be used to run QA.

**Comment by Samara-Strauss** [comment]
@tzelei I've made #3948 into an epic and created separate tickets for tracking the test plan for QA and the actual QA itself. For this ticket, we'll track the test plan. When you get a chance, can you send me the test cases/spreadsheet you have so far?

**Comment by tlei123** [comment]
@Samara-Strauss , I should have Test Plan ready for review by next Tuesday.

Sorry, was gonna try finalizing them tomorrow but got blindsided by another team's urgent test-run request.

P.S.  I'll first be sharing a preview of my **online** Test Plan with you & @erikphansen, and if you're satisfied with that we'll do away with spreadsheets.

**Comment by Samara-Strauss** [comment]
All sounds good, @tzelei! Looking forward to reviewing the test plan.

**Comment by tlei123** [comment]
@Samara-Strauss, would you mind scheduling a meeting w/ @erikphansen & me to go over my test-cases?

My availabilities are \[in EST]:
* Tuesday - before 1:00 pm, & 3:30 pm-4:30 pm
* Wednesday - all day
* Thursday - before 1:00 pm, after 2:30 pm

I tried to schedule one but couldn't see your availabilities.

Thanks much!

P.S.  Thanks again for working w/ Erik to start providing per-case addresses!  :)

**Comment by Samara-Strauss** [comment]
@tzelei how is immediately after sprint planning tomorrow? So that would be 3:00 ET unless we finish sprint planning earlier. I'll create an invite and we can shuffle it around if necessary.

**Comment by tlei123** [comment]
@Samara-Strauss @erikphansen , the [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/28) is ready for your final review.

VSA shared-account credentials have been emailed to you separately.

Pls. add a Comment here with your feedback/approval, and if approved please check-off the item in task-list at the top.

Feel free to ping me on Slack as needed/desired.

Thanks much!

P.S.  I forgot to confirm with you that the online Test Plan on TestRail is a satisfactory replacement of our legacy spreadsheets, so if you still want a spreadsheet just let me know.

**Comment by Samara-Strauss** [comment]
Hey @tlei123 ! This is amazing! Thank you for all your hard work. Here are my updates:

**All test cases**

- Reminder: You can take out all the use cases that start with “not overridable” since all use cases are now overridable – even garbage addresses. So you can remove C177, C171, and C172 from the list.

**Copy & Layout**

- You can remove test numbers 4, 5,  and 6 since we no longer need to account for “not overridable” cases.

> I forgot to confirm with you that the online Test Plan on TestRail is a satisfactory replacement of our legacy spreadsheets, so if you still want a spreadsheet just let me know.

TestRail is great! It was easy to see all the cases and review them. No need for a spreadsheet!

**Comment by tlei123** [comment]
@Samara-Strauss , thx for the feedback!  I've made all the necessary changes...

Here's a [deeper link right into the Test Run](https://dsvavsp.testrail.io/index.php?/runs/view/158&group_by=cases:section_id&group_order=asc), in case you want a 2nd look -- here you won't see any irrelevant Test Cases that weren't selected for the Run.  \[Copy-&-layout checks have now moved into the Overridable cases (Step 2's Expected Results), so we don't need that separate Copy & Layout case anymore.]

Sorry for the confusion about the Test Cases tab -- that's sort of a "rabbit hole" there!  That tab lists ALL Test Cases for the entire VSA-Authd-Exp Project, and doesn't imply any associations with specific Test Runs.  Think of the tab as "all the available Test Cases you can select when creating a Test Run."

Feel free to ping me on Slack if the above sounds confusing.  I can do a screen-share if you want.  :)

cc @erikphansen

**Comment by Samara-Strauss** [comment]
This looks great. Thanks @tzelei!

**Comment by Samara-Strauss** [comment]
Do we need to do anything else here? @erikphansen were you planning to review? I've already taken a look at it and approved so we probably don't need another review unless you want to give things a look regardless.

**Comment by Samara-Strauss** [comment]
Also, @tlei123 can you please give this ticket an estimate when you get a chance?

**Comment by erikphansen** [comment]
LGTM. I added my checkmark.

**Comment by Samara-Strauss** [comment]
Great! I'll close this out, then.
