### ISSUE TITLE
Supplemental Claims | Include additionalDocuments fields for evidence upload in schema

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#50109]
## Value Statement
**_As a_** developer who wants to submit supplemental claims
**_I want to_** know the schema of a supplemental claim
**_So that_** I can submit supplemental claims in a valid format, with all require or optional fields.

---
## Background Context
- I previously added form4142 stuff, but Robin noticed it shows up messed up in the docs, need to fix that one
- Need to add additional references to the schema for the evidence payload 

## Acceptance Criteria
- [x] schema shows up in swagger docs with no issues in staging
- [x] schema has form4142 refs
- [x] schema has additionaDocuments refs

## Tasks
- [ ] fix schema
- [ ] check schema locally
- [ ] merge
- [ ] check schema in staging

## Definition of Done

- [ ] Meets acceptance criteria

**Comment by saderagsdale** [comment]
@kylesoskin add details

**Comment by kylesoskin** [comment]
@saderagsdale Details added and ticket refined to have accurate tasks and criteria

**Comment by saderagsdale** [comment]
@kylesoskin 🙏🏽

**Comment by kylesoskin** [comment]
https://github.com/department-of-veterans-affairs/vets-json-schema/pull/750

Merged. Waiting for staging deployment, will check/confirm then and then close.

**Comment by kylesoskin** [comment]
![image.png](https://images.zenhubusercontent.com/62067253500f33af56810776/7296e8f7-39ba-4098-9f4d-6f9ef68f7d2c)

Still needs some tweaking.... :(
