### ISSUE TITLE
Supplemental Claims | Evidence Upload linking code

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#50107]
## Value Statement
**_As a_** veteran who uploads evidence with my supplemental claim
**_I want to_** ensure that that documents get uploaded to the VA and associated with my supplemental claim
**_So that_** my claim has a better chance of a favorable outcome, and a shorter time-to-completion. 

---
## Acceptance Criteria
- [x] Test case exists that submits payload with additionalDocuments that confirms it gets processed/uploaded
- [x] Unit tests complete (90% coverage)
- [x] Confirmed working in staging

## Designs and Build Notes
- The code to actually submit the evidence is already in-place and merged. Just need to add code to controller to say "if submission has evidence, queue it to be uploaded" 

## Tasks
- [x] code complete
- [x] test
- [x] merge
- [ ] confirm working in staging

## Definition of Done

- [ ] Meets acceptance criteria
- [x] Submitted to staging

**Comment by saderagsdale** [comment]
@kylesoskin add details plz

**Comment by kylesoskin** [comment]
@saderagsdale this one is technically already started/in-progress but should be finished/focused on in the upcoming sprint. Ticket has been refined.
