### ISSUE TITLE
FE | Profile | Documentation | Review Frontend Documentation

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#50128]
## Background

Review all frontend documentation related to each section of Profile and ensure things are up to date and accurate. We recently updated documentation so this ticket is just to double check all documentation to ensure nothing was missed. This can include: Adding analytics documentation on what events we are firing and where in the code they come from (if applicable), Documenting Api calls and how they are set up in the FE code, Map what error codes might surface for a particular feature and the alert/messaging it maps to

## Tasks
- [ ] Review/update Personal Information docs
- [ ] Review/update Contact Information docs
- [ ] Review/update Military Information docs
- [ ] Review/update Direct Deposit docs
- [ ] Review/update Notification Settings docs
- [ ] Review/update Account Security
- [ ] Review/update Connected Apps

## Acceptance Criteria
- [ ] All tasks are completed

**Comment by SKasimow** [comment]
closing dupe ticket
