### ISSUE TITLE
[QA] Address Validation: Run QA  and create bug tickets

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5012]
## Background

Epic #3948
Test Plan #5010

## Tasks
- [x] Run QA for address validation.
- [x] Create bug tickets for anything that came up in QA and assign to Samara for triage.

## Acceptance Criteria:

- [ ] QA is complete and all bug tickets have been added to Github.

**Comment by Samara-Strauss** [comment]
@tlei123 can you please give this ticket an estimate when you get a chance?

**Comment by tlei123** [comment]
@Samara-Strauss , I've completed all test-runs, and here's the [Test Plan Summary Report](https://dsvavsp.testrail.io/index.php?/reports/view/40) for your review.

You should already have the VSA shared-account credentials, but if you can't find them just ping me on Slack.

Please do one of the following:

- If satisfied with Report and you don't want any re-testing after bugfixes, Close this ticket;
- If satisfied with Report and you do want to request re-testing after bugfixes, add a Comment here to let me know.
- If NOT satisfied with Report, add a Comment here with your feedback and any further questions/issues/requests.

Thanks much!

**Comment by Samara-Strauss** [comment]
@tzelei THANK YOU! This is great. I would love if you could validate the bug fixes after they are tested. Thank you again for all of your help!

**Comment by Samara-Strauss** [comment]
Actually, @tzelei — I am going to close this, BUT I still will need your help with validating #5505  and #5553 when they're fixed. I can @-you on those tickets when they are ready. But this ticket is done as defined so we can close it out.
