### ISSUE TITLE
Design | Profile | Documentation | Review Design Documentation

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#50121]
## Background

Review all design documentation related to each section of Profile and ensure things are up to date and accurate. We recently updated documentation so this ticket is just to double check all documentation to ensure nothing was missed. This includes reviewing sketch files, use cases, user flows, and the call center guide.

One thing to note is that user 36 is now marked "deceased" and will not have Profile information, any use cases or documentation around this user should be updated.

## Tasks
- [ ] Review/update Personal Information docs
- [ ] Review/update Contact Information docs
- [ ] Review/update Military Information docs
- [ ] Review/update Direct Deposit docs
- [ ] Review/update Notification Settings docs
- [ ] Review/update Account Security
- [ ] Review/update Connected Apps
  

## Acceptance Criteria
- [ ] All tasks have been completed
- [ ] Notify PM if/when contact center guide is updated

**Comment by SKasimow** [comment]
Closing ... using 1 ticket for Design documentation
