### ISSUE TITLE
Create designs for unfiltered clinic page

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#50126]
## Task Description
* Currently the clinic page shows only clinics the Veteran has attended in the past 12 or 36 months - this is determined by the facility in VATS.
* This filter will be removed, so all clinics will display.
* Update clinic page so that Veterans can easily find and select a clinic. Even in a longer list that may include clinics the Veteran has never been seen at.

## References
* We will still be able to surface clinics a Veteran has been seen at. 
* How does that data come back? A specific date? A general range?

## Acceptance Criteria
- [ ] Design files showing clinic page update 
- [ ] Mobile, tablet, and desktop designs

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by outerpress** [comment]
@Cieramaddox here are the first pass designs, use this file pls: https://www.figma.com/file/PXCcXDMSukH5O6BFKQ3Ctr/Unfiltered-clinic-list?node-id=2%3A4&t=tInoxBev3T1ZA0TR-1

**Comment by Cieramaddox** [comment]
@ldelacosta We are still waiting to hear if the last visited information is accessible. Any updates on that?

**Comment by outerpress** [comment]
Not prioritized for PI8, moving to Icebox.
