### ISSUE TITLE
Design | Profile | Documentation | Review Design Documentation

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#50124]
## Background

Review all design documentation related to each section of Profile and ensure things are up to date and accurate. We recently updated documentation so this ticket is just to double check all documentation to ensure nothing was missed. This includes reviewing sketch files, use cases, user flows, and the call center guide.

One thing to note is that user 36 is now marked "deceased" and will not have Profile information, any use cases or documentation around this user should be updated.

## Tasks
- [x] Review/update Personal Information docs - Christina
- [x] Review/update Contact Information docs - Liz
- [x] Review/update Military Information docs - Christina
- [x] Review/update Direct Deposit docs - Liz
- [x] Review/update Notification Settings docs - Liz
- [x] Review/update Account Security - Christina
- [x] Review/update Connected Apps - Liz
- [x] Review/update test case documentation - Liz
  

## Acceptance Criteria
- [ ] All tasks have been completed
- [ ] Notify PM if/when contact center guide is updated

**Comment by SKasimow** [comment]
Hi @cgednalske - I added Liz to this ticket per our discussion to just use the 1 ticket.

**Comment by andaleliz** [comment]
@ericasauv09 and @SKasimow are one of you planning on updating the [test case documentation](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-profile.md)? Looks like there are lots of references to user 36 here.

**Comment by SKasimow** [comment]
Thanks @andaleliz . I'll open a ticket for us to review the test cases anyway and make sure they are all updated.

**Comment by cgednalske** [comment]
@andaleliz @SKasimow closing! 🎉
