### ISSUE TITLE
BE | Profile | Documentation | Review Backend Documentation

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#50131]
## Background

Review all backend documentation related to each section of Profile and ensure things are up to date and accurate. We recently updated documentation so this ticket is just to double check all documentation to ensure nothing was missed.

## Tasks
- [x] Review/update Personal Information docs
- [x] Review/update Contact Information docs
- [x] Review/update Military Information docs
- [x] Review/update Direct Deposit docs
- [x] Review/update Notification Settings docs
- [x] Review/update Account Security
- [x] Review/update Connected Apps
  

## Acceptance Criteria
- [x] All backend documentation for Profile is update/reviewed

**Comment by tpharrison** [comment]
Reviewed all BE documentation.  Made some of the referencing links more consistent.
