### ISSUE TITLE
[Discovery] Download VA Benefit Letters 

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#50142]
## Issue Description
Stakeholder have decided to remove the use of VBMS for letter downloads. Their raised this [Download VA Benefit Letters | Veterans Affairs](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.va.gov%2Frecords%2Fdownload-va-letters%2F&data=05%7C01%7Cdenise.coveyduc%40govcio.com%7C56ab6c5b78f3489ebefc08dab91d6fe2%7C6499e3f51d3e4f099ad352b9e2f67fb8%7C1%7C0%7C638025833344051477%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BkrCp1qsI51rWkjITJ1TSZFNZTHpjNLhgMXZBmkBViU%3D&reserved=0) and suggested that we may want to explore this functionality and meet with the team responsible. This could be a good solution to provide letters for Veterans in the future. 

---
## Tasks
- [ ] Discovery work to validate team working on this functionality. Current understanding it is the Benefits Team 1. 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
