### ISSUE TITLE
[eFSR] Veteran Contact information Discovery

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#50155]
## Issue Description
Creating a discovery ticket to track investigatory work done for implementing contact information - Ticket #46673 

---
## Tasks
- [ ] Investigate Veteran Contact information implementation on other forms to allow for profile info editing. 

## Acceptance Criteria
- [ ] Have a clear plan for implementing updating veteran contact information in form and profile
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
