### ISSUE TITLE
BE | Profile | Notification Preferences | Issue when creating preference that already exists

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#50154]
## Background

In some cases, when a user makes changes to their notification preferences, a _create_ request is sent when an _update_ request should be sent.  When this happens, the request will be rejected with the response:

```
{
  code: CP406, 
  key: PermissionItemChannelComboExists, 
  severity: ERROR, 
  text: A Permission with for VA Profile ID ... already exists for Item 1 and Channel 1 
  combo.
}
```

See original ticket for more background info: 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/48695

## Tasks
- [ ] Create a few users in staging to simulate issue.
- [ ] Determine if an update request can/should be used in all scenarios.
- [ ] Apply fix
  

## Acceptance Criteria
- [ ] Review fix with team.\
- [ ] Test in staging
