### ISSUE TITLE
Append scope of RFC 965 to include `preview.va.gov`

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#50151]
# Description
Given our understanding of the sub-domain creation process [here](https://vfs.atlassian.net/wiki/spaces/TT4/pages/2443444492/Subdomain+for+preview+environments), we need to seek approval to append our desired sub-domain, `preview.va.gov` to the existing RFC that defines the public routes currently operated by the VA.gov platform.

# Tasks
- [x] Determine a plan of action for appending the additional sub-domain to RFC965
- [x] Get approval to append the scope of RFC965
- [x] Submit the scope change to RFC 965

# Acceptance Criteria
- [x] Operation of `preview.va.gov` has been added to the scope of RFC 965 permitting the VA.gov platform to operate this sub-domain and create a publicly accessible route

**Comment by pjhill** [comment]
Details of RFC965 are [available in the va.gov-team-sensitive repo](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/platform/engineering/preview_environments/RFC965_details) just in case there is something sensitive listed within the ticket.

**Comment by rmtolmach** [comment]
Thanks for those screenshots, Peter! I am going through each section and making new tickets, as needed. I am also documenting what will need to be done in the [In-scope change to RFC 965](https://vfs.atlassian.net/wiki/spaces/TT4/pages/2443444492/Subdomain+for+preview+environments#In-scope-change-to-RFC-965) section of the "Subdomain for preview environments" Confluence doc.

**Comment by rmtolmach** [comment]
Plot twist! I used to not have access to the [ESECC portal](https://esecc.va.gov/), but now when I go there, it takes me directly to this page: Now esecc.va.gov/CGWeb/CGClient/SSP/Index.html I'm in!

**Comment by rmtolmach** [comment]
Met with @JoeTice @pjhill and @raywangoctova today and Ray submitted the in-scope change on our behalf.

**Comment by rmtolmach** [comment]
https://github.com/department-of-veterans-affairs/devops/blob/master/docs/ESECC-Public-URL-process.md#submitting-the-request

**Comment by pjhill** [comment]
The certificate request portion is [here](https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/51360).

Closing this ticket since the scope of this ticket ends with the submission. If we need to address any questions we can work that with a new ticket.

Thanks for wrangling all of this, Rebecca!

**Comment by rmtolmach** [comment]
1/6 update:
No changes. [RFC-965](https://esecc.va.gov/CGWeb/MainUI/Changemanagement/StaffRFC.aspx?boundtable=IChangeManagementTicket&CloseOnPerformAction=false&ID=965) is still in the "Pending Approval" state. None of the nine approvers have approved it. There are no additional comments left.
