### ISSUE TITLE
Define approach to preview environment routing

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#50150]
# Description
Given that preview environment URLs will also need to be routable from the public internet, how might we create routes to dynamically generated addresses and URLs?

# Tasks
- [x] Determine how traffic originating in the public internet can be routed to a dynamically generated URL and machine address within the `dev` VPC
- [x] Consider that `preview.va.gov` will need to route for the subdomain to the `dev` VPC

# Acceptance Criteria
- [x] An approach to defining routes to preview environments with dynamically created URLs from the public internet

**Comment by cyriltech** [comment]
Made some changes to the host path. [PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1334)

**Comment by JoeTice** [comment]
@cyriltech - the work of this ticket seems to be done, please check off the tasks, and acceptance criteria, and move it to the 'Review' column on the board.

**Comment by cyriltech** [comment]
At the moment routing is pointing to a single value.yaml file that contains a dynamic generated url of vets-website-test-branch.preview.va.gov .
environment-values.yaml will be configured on this other [ticket](https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/51637)

**Comment by pjhill** [comment]
@cyriltech -- This PR is good, but do we have an approach for reading the URL from multiple values files? Is the approach basically to use the method in your PR, but apply it across multiple `values.yaml` files in the same manor that we loop all other values in this [ticket](https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/51637)?

**Comment by cyriltech** [comment]
Yes @pjhill. The second part is to dynamically loop across multiple value.yaml files and parse dynamic urls which is in progress via the other ticket.

**Comment by pjhill** [comment]
Sounds good -- thanks for wrapping this up!
