### ISSUE TITLE
Content review of secure messaging screens

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#50161]
## Issue Description

As part of the work we're doing for the Health Apartment team, we need to do a content review of the secure messaging tool. We'll track the work internally for our team in this ticket but group the work into chunks, looking at 7-8 screens at a time. 

Screens to review (this is taken from the original intake request #42428:

- Link to prototype or mockups: **Note - These screens and flows are currently being tested/subject to change**
     - [Desktop prototype](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/prototype/a/0C5CF38D-3AAC-477B-A479-B14220AA3503)
     - [Mobile prototype](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/prototype/a/0606632E-EBD2-4B8C-876D-64593DF9E556)

**Landing pages:**
- [x] Inbox  [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/My9L2Wl) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/dlJRdPm)
- [x] Trash [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/48AEB8C4-6AAA-4610-B819-21A289118A90) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/054AAC94-4802-40FF-8A94-A2955AEB54AF)
- [x] Drafts [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/053AF4BA-4003-44B3-B502-494E381553F5) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/E99F6FBF-849E-4DAD-971E-C8CAEE0A3980)
- [x] Sent [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/FA90EDA7-7DAB-46B9-AB38-32A4983950EA) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/D739D6E9-E557-45B7-BB12-CAD2F92F0318)
- [x] My Folders landing page [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/BB9455C9-0F63-4A5E-8245-D94C0456FE11)
- [x] Custom folder (nested within My Folders) [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/F8233DF0-67BB-449D-81E8-9D03EB604C76) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/A666D229-A06A-49C6-A519-C309BFE0964D)
- [x] Search messages [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/2BBDC720-664E-4C6F-8EC6-915FB49AB978) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/97149C2D-1E28-4F3F-9D17-5D52893E9D40)
- [x] Advanced Search form [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/54D6116C-E062-4875-BA8E-EBC7DEE2FE8E) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/9DA8242E-E067-41B3-A5CC-786CF6436633)
 
**Detail pages:**
- [x] Inbox message detail [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/E407174B-56A5-4FD5-8EE7-E3250E4A3E23) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/YGejDvd)
- [x] Compose message detail view [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/1D42D2C4-859E-40EE-99FA-CEB9939865D4) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/6EF72EFE-D73B-4214-A184-2EB17E6207FF)
- [x] Edit draft message detail view (draft of a reply) [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/702EAC7E-FB05-4E4C-8611-0782B05F7DE9) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/432DE2C8-230F-4C6A-84E6-F02A4966CA12) 
- [x] Edit draft message detail view (draft of a New Message) [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/E1D8B12B-DCF5-4A04-BA20-C40637513CD2) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/33437166-C54A-4913-A343-C639EC87F5A8)
- [x] Sent message detail view [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/C3D8D126-84D2-4950-ACF4-7F6DFFF08774) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/D739D6E9-E557-45B7-BB12-CAD2F92F0318)
- [x] Search results [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/C2008170-C3E4-4924-899D-4C7FE99431C0) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/237F8A88-6AE5-49DE-A40F-E644DBCBDEDA)
- [x] Deleted message detail view [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/1570663C-093D-4ECC-99D7-9B5EFBC8001C) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/5BD11B6F-4BC1-4645-91B0-AAA9EFA98B8C)
- [x] Reply to message detail view [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/4550B031-AB89-4A93-AAF9-C201AA28D47D) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/93733CC4-442D-4504-A85D-BE71D24C3C34)
- [x] [Empty Inbox ](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/D7BD84EF-7A26-4C82-8AE3-0B9C770FE0BC)
- [x] Empty Drafts/Sent/Trash Folder [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/DB42EFA7-0954-4CAE-86A4-8B098663CB68) | [Mobile](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/1D5587B6-055E-416D-B35F-805EBB430E9B)
- [x] [Empty My Folders landing Page](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/8CAEA70F-39F4-490A-846C-8A3ED425C20D)
- [x] [Search results details](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/4azZq0A#Version)
- [x] [Reply with attachments](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/bgeA2VZ#Version)
- [x] How to attach a file [expanded text](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/v/rjQ9nA/a/My1Dp1z#Version)

**Messaging actions (modals):**

- [x] [Confirm send message to trash](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/91D9AFE4-FBDF-46FB-8299-019EB88AAE69)
- [x] [Confirm discard draft](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/5418A7EC-62D2-4F28-A8E3-6C5F958834E5)
- [x] [Can't save attachments to drafts](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/43E42C46-E8C2-469D-AF90-B14F114C57BA)
- [x] [Cant save or send draft - incomplete fields](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/694472F3-95A4-4D93-A7B2-C3CC58174A1B)
- [x] [Move conversation](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/2DACB267-7B0C-4CB6-A999-4E1D9F817C19)
- [x] [Print message](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/AF29D60B-B4A2-4990-A6AF-D9AA0DC92E8A)
- [x] [Create new folder](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/131FBF82-CB49-4320-9768-0EF8057A38E1)
- [x] [Edit folder name](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/B8FF4AA5-2524-46E0-BB83-F21742D82600)
- [x] [Remove folder](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/28FAFCEE-DD86-4FB2-BB02-D9CE5903BA4F)

**Alerts:**
- [x] [Successfully deleted/removed folder ](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/18933DF7-4460-49C6-B05A-BF4ACA03E0AE)
- [x] [Successfully renamed folder](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/68894BF7-6438-492A-BD0F-77F4819D4A1C)
- [x] [Can't reply to message because it is older than 45 days](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/0791E242-E0CF-47CB-8261-D1DFB6CA309F)
- [x] [Success and error alerts for Deleting a message (thread); saving/discarding a draft; sending a message; moving a message; and when the user tries to enter an unacceptable character. ](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/594A1A57-04E6-45BC-92CA-E87F3DEF6464)

### New and updated screens for content review 1.25.23
- [x] Updated [labels on cards for folders/filter component/attachment card](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/11CE4319-EC87-49D2-A3F3-86963A4EBB18)
- [x] [Modal: Attachments can't be saved](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/xrYLRp8) (when user navigates away from draft that is savable but they added an attachment which the system can't save. "Ok" lets user navigate away while "Continue editing" keeps them on page so they don't lose their draft/attachment)
- [x] [Modal: Move conversation ](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/B9B83D25-690C-4343-B395-7B3DC56B3F82)(when user initiates moving a conversation using the "Move" button)
- [x] [Modal: Can't save message](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/F5A3CCF1-FE08-445A-8CA4-A74D0B66AD30) (when user tries to navigate away from draft but not enough info to save/autosave)
- [x] [Static Banner: Can't send message ](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/39AB5C61-95E0-4CCA-8358-18CAECA443C6)(when user presses "send" button, but required information is missing)
- [x] [Static Banner: Can't save draft ](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/D626EE26-A58B-4DD5-A57B-3B0C819F43E5)(when user presses "Save draft" button, but required info is missing)
- [x] Phase 0 landing page [Desktop](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/ygOglEq) | [Mobile landing page ](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/3904F65C-F602-4BEB-A802-DDA4514FE4C9) **— see Word doc in comment**
- [x] Further updates on ["Blocked Triage Group" static banner ](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/092BEDB9-93AC-4F1C-AA1E-38FCC056C2AB)(finalized text after meetings and discussions about flow/what's possible for Phase 0)
- [x] [In-line attachment errors](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/8yloPQ8?annotation=10f5a130-8d23-4a5f-a0a8-927b0b21c123#Version)
- [x] [0 matches for filters ](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/8yl990w#Version)

**Pending for now [Blockers in brackets]:**
- [x] [Modal: Edit List ](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/5472D8A2-B675-4E4B-B241-577B01A25F1F)(when user needs to go back to Legacy to change visibility of Triage Groups in dropdown list) [Waiting for developer input]
- [ ] [Modal: Invalid search error ](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/uuid/B28F222B-88C5-46C9-BAAA-2A0DF02BD5BF)[UCD needs to be discussed for use case and redesigned]
- [ ] [Message categorization](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/9PORbKP?annotation=8ece7a40-c8f6-4dfb-8b8e-e7129ed2d1fd) (Big Questions) [May need to be discussed with Business, unsure of next steps and who makes these decisions]

## Tasks
- [x] Content review 
- [x] Provide product team with final content

## Acceptance Criteria
- [ ] Final content has been given to product team in original intake request.

**Comment by laurwill** [comment]
Hi @alexiawunder , since there's a lot going on in the main intake ticket, i'm tracking our progress on the content review here — screens I've checked off have our comments ready for you.

**Comment by laurwill** [comment]
@jerobertso and Joel (who I can't seem to tag!), I've provided comments on all the outstanding screens listed above, except for the blocked items. 

And here's a doc with the updated landing page content. See comments for remaining questions and suggestions: 
[Messages.phase.0.landing.page_updated_1.31.23.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10551902/Messages.phase.0.landing.page_updated_1.31.23.docx)

And noting we'll need to update the landing page content again based on:
- Findings from safety message testing
- Joel's conversation with dev team about the user flow to send people back to MHV to change settings

**Comment by laurwill** [comment]
Hello @jerobertso @alexiawunder and Joel, 

Here are the remaining pieces of content for secure messaging: 
- Updated landing page content with post-testing safety message — updated sections in yellow highlight:
[Messages.phase.0.landing.page_updated_2.14.23.docx.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10735148/Messages.phase.0.landing.page_updated_2.14.23.docx.docx)
- Edit list modal content — 2 versions for teal and magenta flows: 
[Edit list content_2.14.23.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10735309/Edit.list.content_2.14.23.docx)
- Updated comments on in-line error and success messages (including "secure" version): https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/258a28J/

Let us know if you have questions or need anything else! 

Also, we assumed that there would be a final SME review of the updated content for key pieces like the landing page — is Patty or another SME planning to look at the updated designs?

**Comment by RLHecht** [comment]
Closing this out. If the product team needs further support from us we can open a new ticket.
