### ISSUE TITLE
[FE] My VA Healthcare: Separate Drupal Changes from Audit Work

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#50173]
## Background
The Drupal API changes need to be released on 12/14 and the Audit Healthcare changes likely won't be released until Q1 of 2023 so we need to separate the Drupal API changes and add a feature flag so it can be released on 12/14.

## Tasks
- [x] Separate Code
- [x] Create Feature flag
- [x] Have APM validate the changes again in Staging 

## Acceptance Criteria
- [x] Drupal API changes for Cerner information is able to be released on 12/14 separate from the Audit healthcare changes

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_
- _How can this work be validated?_ Ensure cerner message is still accurate once code has been separated
