### ISSUE TITLE
Conduct analysis of preview.va.gov setup

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#50206]
# Description
Conduct an analysis of the current setup of preview.va.gov to help us determine if/how the setup needs to be modified to support an approach to Preview Environments.

# Tasks
- [ ] How would we take control of this sub-domain?
- [ ] Currently the only DNS record appears to be an `MX` and `TXT`. If we register an `A` what would we point it to? The TIC for our `vagov-dev' VPC? The F5?

# Acceptance Criteria
- [x]  We know what we need to change about how `preview.va.gov` is configured

**Comment by rmtolmach** [comment]
I am not sure how to find out more information about `preview.va.gov`. The request to add the domain to RFC-965 has been submitted. I'm wondering if we will find out if anything needs to be modified during the approval process. Progress of the approval process can be found in the RFC (accessible via the CAG): https://esecc.va.gov/CGWeb/MainUI/Changemanagement/StaffRFC.aspx?boundtable=IChangeManagementTicket&CloseOnPerformAction=false&ID=965

**Comment by pjhill** [comment]
We have incidentally collected information about the configuration changes we need to make and who can make those changes through work in other tickets.
