### ISSUE TITLE
Review Project Intake process status w/ OCTO and Platform leads

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#50218]
## Issue Description
Use the workflow that Ray built, along with early discussion on the Project Intake proposal, to create a workflow diagram.

In our Sync, Ray later shared the Design Systems intake board  https://github.com/orgs/department-of-veterans-affairs/projects/779/views/2

he likes the “by priority” option and boards in general
## Resources
[Proposal notes](https://vfs.atlassian.net/wiki/spaces/~622b5b63932f0f00716bdfd6/pages/2400846510/Project+Creation+Process+and+SDT)

## Preliminary Work
Lucidchart [workflow](https://lucid.app/lucidchart/e2d771f0-6d82-4f13-8411-9e983ec0687d/edit?invitationId=inv_fc1e26fe-e5c7-4a42-902d-2999a568b8b6&page=0_0#) to capture existing process along with clarifications/simplifications

## Tasks
- [x] Discuss state of Projects w/ Jason and get his take on ideas generated during workshop (scheduled for 12/15)
- [x] Discuss state of Projects w/ Ray and get his take on ideas generated during workshop

## Acceptance Criteria
- [ ] Updated on where Leadership sees it currently
