### ISSUE TITLE
Demo:  New Guidance on Change Communication timing

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#50219]
## Issue Description
We discussed that our Communication Playbook doesn’t specify times, as historically the idea was to leave that to the fixed technical teams who more expert about the need.  Given that these have changed, prescribing lead-time guidelines is a useful idea.

Additional discussion w/ Jason:
Even if the date gets pushed, the day-before reminder should still suffice, and tamp down on too many updates, (instead of updating about mid-stream changes after the initial announcement).

## [When to prepare your communication plan](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2317647873/Change+Communication+Guide#When-to-prepare-your-communication-plan)
It is important for users to receive timely updates about matters that will affect their work. As the launch of the change itself draws near, we recommend formulating and sharing communications early so that teams have adequate time to respond to upcoming changes.

Using the channels described above, the following schedule is recommended:
**1 week before launch:  Announce that the change is coming and ask for feedback**
**1 business day before launch:  Remind users that the change will take place the following business day**
**Day of change:  Announce that the change has taken place**

## Tasks
- [x] Prepare the [presentation](https://docs.google.com/presentation/d/1g638PNOXRXgdwVDYFBQqaRJqCmXmDCpN1dWt7r8iz2k/edit#slide=id.gcd567e2ae4_0_432)
- [x] Share the [new guidance](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2317647873/Change+Communication+Guide#When-to-prepare-your-communication-plan) at Demo day

## Acceptance Criteria
- [x] Change has been communicated in Demo Day
