### ISSUE TITLE
[Analytics] Research "Erie, PA" Facilities information required for facilities web page [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#5022]
## User Story or Problem Statement
As a Veteran web user, I need to know the specific details and services of the local facilities related to my area, so I can better plan my journey to the specific factility and location. 

## Goal
_Compile all the data required to build out a clear facility(ies) page for each facility listed in this Medical Center System_

## Objectives or Key Results this is meant to further
- _Reduce click through count_
- _Document pages that can be created in a scalable manner_

## Resources - Tools - Documentation
[Altoona Legacy Web Page](www.erie.va.gov)
[Example Facility pages at Pittsburgh](https://www.va.gov/pittsburgh-health-care/locations/)
[VISN_4_Medical_Systems_and_Clinics_List](https://drive.google.com/drive/folders/1f_PRAt67ccYNm5DkJiAKwINsSX_S5_4o)

## Tasks
_Compile all the following that are applicable for each Facility page:_
_Prepare for your visit:_
- [ ] Parking
- [ ] Transportation Services
- [ ] Visitor Hours and information (MC only)
- [ ] Lodging for patients and families (overnight facilities only)
- [ ] Dining and retail
- [ ] Any Special (non-medical) services offered (e.g. Library, Chaplin)
- [ ] Facility, Campus, or building Maps available (only if available)

## Acceptance Criteria
_Confirm all have been reviewed and provided IF APPLICABLE_
* Parking
* Transportation Services
* Visitor Hours and information (MC only)
* Lodging for patients and families (overnight facilities only)
* Dining and retail
* Any Special (non-medical) services offered (e.g. Library, Chaplin)
* Facility, Campus, or building Maps available (only if available)

**Comment by EdwardBoehme05** [comment]
Requires PAO to validate and provide some info. Spreadsheet at https://drive.google.com/drive/folders/12r3SWiQPCulkz2xOA06wGywQu5oWPArD
