### ISSUE TITLE
[FE] Use Redux store for all errors before routing to error page

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#50222]
## Description

Issue created from this [spike](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45795)

Store all errors as strings in Redux state. ie. dispatch the setError action when an error occurs, usually in a side effect like an API call.
`dispatch(setError('bad-token'));`

Create a higher order component to wrap the application and handle errors by routing the application to the error page. Later this could include more robust error reporting using GA, Sentry or Datadog. This also give us the flexibility to create other side effects like add more information to the state object for more complicated error messaging.

    useEffect(
      () => {
        if (error) {
          goToErrorPage(error);
        }
      },
      [error],
    );

The router utility goToErrorPage will use the error string to add a query string to the url for GA tracking. This gives us more flexibility to get creative with the URL parameters.

Replace utility functions like appointmentWasCanceled in the Error page for pre check in with a check against the error string in the Redux store. `if( error === 'appointment-cancelled')`

## Tasks
- [ ] On error dispatch setError action
- [ ] Create HOC for routing and other side effects
- [ ] Modify goToErrorPage to use error type instead of full url parameter
- [ ] Replace redundant use of utility functions with error type from state
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
