### ISSUE TITLE
Evaluate requested QA artifacts at Staging Review

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#50244]
## User Story
As a Governance team member supporting QA in the Collab Cycle Staging Review, I want to make sure the artifacts we request of VFS teams are in line with what is needed to verify the QA Standards are met.

As a VFS team member, I want to know the necessary QA artifacts for Staging Review so that I can be sure to provide them and not delay my review bc I didn't provide what was asked.

Assignee: @it-harrison 
Peer Reviewer: @briandeconinck 

## Description
The QA Standards will begin to be enforced started 1/9/23 in the Staging Review. In order to ensure we are giving the best guidance to VFS teams for ensuring the standards are met, we need to evaluate what we ask of VFS wrt QA at the Collab Cycle Staging Review. 

The purpose of this ticket is to review what is requested at Collab Cycle Staging in both the Staging Review touchpoints page and the Staging Review code block of the Collab Cycle request ticket. 

## Impacted Artifacts
[Staging Review touchpoints page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review) on PW
[Staging Review code block](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities#Staging-Review-code-block) in Collab Cycle Request ticket

## Tasks
- [x] Review what is requested in both the code block and touchpoint page (should be identical)
- [x] Identify if those artifacts are sufficient enough to verify if QA Standards are met
- [x] If not, modify the request in both places (create a documentation draft)
- [x] In the current guidance, we direct VFS teams to "[Learn more about QA artifacts](https://depo-platform-documentation.scrollhelp.site/developer-docs/Quality-assurance-artifacts.1906999390.html)" - is this still relevant? Should we be directing VFS teams elsewhere? Would it be more valuable for VFS teams if we linked to [this page?](https://depo-platform-documentation.scrollhelp.site/developer-docs/qa-and-accessibility-testing)

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS teams are asked to provide QA artifacts at Staging Review that allow for Governance team to verify if QA standards are met

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
hi @briandeconinck this ticket is ready for review. There is a [draft touchpoints page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/edit-v2/2456682607) and the code block in the [Collab Cycle Request ticket](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2461433857/Copy+of+Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities+-+QA+artifacts+modified). I also recommend not linking to the [QA Artifacts page](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-artifacts) and I changed this to link to the QA Standards.

**Comment by briandeconinck** [comment]
@it-harrison I left a couple of comments on the draft staging review page. Minor wording stuff.

I'm not seeing any changes to the Collab Cycle moderator page code block -- possible that it didn't save, or am I looking in the wrong place?

100% agree on linking to QA Standards instead of QA Artifacts.

**Comment by it-harrison** [comment]
hi @briandeconinck - my mistake I have published the changes to the [code block now](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2461433857/Copy+of+Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities+-+QA+artifacts+modified#Staging-Review-code-block).

@shiragoodman I updated the Midpoint Review staging block to be consistent with the Staging Review code block. It didn't make sense for them to be different even though that was not part of this ticket. Or we might want to remove the mention of QA from the Midpoint Review code block since we have talked about including QA at the Midpoint Review.

**Comment by briandeconinck** [comment]
@it-harrison Changes look good! I'll defer to Shira on the Midpoint code block, but otherwise this looks ready to publish.

**Comment by it-harrison** [comment]
@shiragoodman does the[ draft touchpoints page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2456682607/Copy+of+Staging+review) good? I ask because one of the tasks in #47535 is that the staging touchpoints page references the new QA artifacts.

**Comment by shiragoodman** [comment]
@it-harrison the draft page looks great. I think it's simple and to-the-point. You are good to publish and can check off the task in #47535 once published.

**Comment by shiragoodman** [comment]
hey @briandeconinck - it doesn't look like @it-harrison was able to publish before taking OOO time. As his peer reviewer, would you be able to move forward with publishing the changes to the touchpoint page and code block?

**Comment by briandeconinck** [comment]
Published changes to the [moderator responsibilities code blocks](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities). @shiragoodman I'm seeing Ian's changes to the staging review touchpoint page already published to Platform website, so no changes made there.

**Comment by briandeconinck** [comment]
Assuming I didn't miss something with the staging review touchpoint page, this looks to be complete and ready to close.

**Comment by shiragoodman** [comment]
I noticed earlier today that the Staging Review code block wasn't published, so i assumed the touchpoint page wasn't either. All good. thanks for confirming!

**Comment by shiragoodman** [comment]
this can be closed.
