### ISSUE TITLE
Change VCL number back to 988 on several alerts and drupal pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#50252]
## Issue Description

When 988 wasn't working for the Veterans Crisis Line we made edits to several alerts and static pages to change the number to a 10-digit working one. Now that 988 is back up, we need to revert these changes. 

When updating the alerts, make sure you do it in the actual alert node and publish as opposed to changing it within a specific page. This will ensure it gets updated everywhere the alert is.

These are the pages to work on:

- [x] https://prod.cms.va.gov/block/2?destination=/admin/content/alerts (you can check that it's changed on this page: http://preview-prod.vfs.va.gov/preview?nodeId=23) 
- [x] https://prod.cms.va.gov/block/24?destination=/admin/content/alerts
- [x] https://prod.cms.va.gov/block/40?destination=/admin/content/alerts
- [x] http://preview-prod.vfs.va.gov/preview?nodeId=37196 (the number is in both the alert and on the page itself

## Tasks
- [x] Update Drupal nodes to point to 988 instead of the 10-digit number
- [x] Review
- [x] Publish

## Acceptance Criteria
- [x] 988 is showing again on the live site

**Comment by RLHecht** [comment]
These changes are live. Closing ticket.
