### ISSUE TITLE
Bug - Save in Progress forms

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#50258]
## Issue Description
A bug with the Save in Progress forms was detected https://dsva.slack.com/archives/C5AGLBNRK/p1669993898534329 here.  Where the `PUT` request to update data was returning a 500 error.  After investigating with the benefits team, I noticed the default Content-Type when the 500 errors came back was a `text/plain` instead of the expected `application/json`.  It was an oversight with expecting the `apiRequest` mechanism to have a default Content-Type

## Tasks
- [ ] Investigate `v0/in_progress_forms` 500 error
- [ ] Update the default Content-Type to `application/json` so that requests response appropriately

## Acceptance Criteria
- [ ] The `v0/in_progress_forms` work as expected
