### ISSUE TITLE
PM | Profile | Documentation | Review Test Cases for User 36

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#50269]
## Background

Review all design documentation related to each section of Profile and ensure things are up to date and accurate. We recently updated documentation so this ticket is just to double check all documentation to ensure nothing was missed. This includes reviewing sketch files, use cases, user flows, and the call center guide.

One thing to note is that user 36 is now marked "deceased" and will not have Profile information, any test cases or documentation around this user should be updated.

## Tasks
- [x] Review/update Personal Information docs 
- [x] Review/update Contact Information docs 
- [x] Review/update Military Information docs 
- [x] Review/update Direct Deposit docs 
- [x] Review/update Notification Settings docs 
- [x] Review/update Account Security 
- [x] Review/update Connected Apps 
- [ ] Review/update test case documentation 
  

## Acceptance Criteria
- [ ] All tasks have been completed

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)? PM, Design
- How can this work be validated? Staging

## Associated Tickets
- #

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
Hi Erica - I thought we could do what Christina and Liz are doing - that is have 1 ticket and just tick off what  you are working on so we don't duplicate each other. I think one of the easier ones might be for Connected App so you can start there :)

**Comment by ericasauv09** [comment]
sure I will take a look @SKasimow

**Comment by ericasauv09** [comment]
I found one test case that uses user 36 under [Notifications Settings](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-notification-preferences.md#test-cases-for-notifications---feature-eligibility). Do we have an alternative we should replace it with or should i just note that user 36 is deceased @SKasimow ?

**Comment by ericasauv09** [comment]
@SKasimow I also found use cases in the [Direct Deposit documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/direct-deposit) that reference user 36, I marked the user as deceased.

**Comment by SKasimow** [comment]
Hi @ericasauv09 - hmmmm looks like haven't I been getting notifications longer than I thought :(

I did find a replacement for user 36 and added it into Notify Settings that used to point to user 36.
I'll see if I can find one for DD but if I don't will just leave your note in place. Thanks!!

**Comment by SKasimow** [comment]
Other than that looks you got through everything; if so let's close out!
