### ISSUE TITLE
DDL: Sentry error when VBMS cannot find file number

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#50264]
## Background
When a veteran's file number isn't recognized by VBMS we get back a `500` error. We don't want to raise this error to Sentry, but handle the error more gracefully. Also if the user goes to the Claim Letters page and encounters this error they see a message telling them to reload the page or try again later, which for this error won't ever do anything. It's better to show them a message telling them that they don't have any claim letters, because that is a more likely scenario than them refreshing or coming back letter and seeing letters.

## Sentry error
[Link](http://sentry.vfs.va.gov/organizations/vsp/issues/164691/?environment=staging&project=3&query=ClaimLetters&statsPeriod=14d)

## Context
It is assumed that this error occurs when a veteran hasn't made any benefits claims before, though we aren't completely sure why VBMS would be unable to find the veterans file number in their system

The error returned has type: `VBMS::FilenumberDoesNotExist`

## Tasks
- [x] Handle error gracefully
- [x] Return an empty array as the response
- [x] On the FE, show the `NoLettersContent` component instead of the `ServerErrorContent` component

## Acceptance Criteria
- [x] VBMS::FilenumberDoesNotExist error don't get logged to Sentry anymore for this feature
- [x] When this error occurs the FE shows a message indicating that the user doesn't have any Claim letters
