### ISSUE TITLE
[BE] Fix BTSSS API failure in Staging

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#50260]
## Description
Currently vets-api call to BTSSS claims ingest API fails in staging.  

Reason behind: Faraday instance was cutting off a portion of the URL after `/` and the request was sent to `https://nonprod.integration.d365.va.gov/ClaimIngest/submitclaim` instead of `https://nonprod.integration.d365.va.gov/EC/ClaimIngestSvc/api/ClaimIngest/submitclaim`. 

## Tasks
- [ ] [BE] **Modify vets-api code to fix the url sent to Faraday instance**
- [ ] [BE] **Modify devops code for staging/prod fix the endpoint url**
- [ ] [BE] **Modify vsp-infra-application-manifests code to fix the endpoint url**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
