### ISSUE TITLE
[COPY-EDIT] Review content of "LEBANON, PA - ABOUT" for plain language and insertion into CMS/VA facility web page [COPY-EDITOR]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#5028]
## User Story or Problem Statement
As a Veteran Web user, I need a need a plain language description of services in the "ABOUT", web page for LEBANON, VA Health Care System website so I can quickly understand the services and service location for my needs.

## Goal
_Efficient and clear content describing local Work With US Page?_

## Objectives or Key Results this is meant to further
- _Reduced word count and improved plain language._

##Copy Locations
_Where copy is stored and where it will be placed for review_
[Content Tracker](https://drive.google.com/drive/folders/1w6O8JZ42Jkp1Sa9QOt9Lv4R9WjJFEp3O)
[VAMC Share Drive](https://drive.google.com/drive/folders/1w6O8JZ42Jkp1Sa9QOt9Lv4R9WjJFEp3O)
[VAMC SharePoint Documents](https://dvagov.sharepoint.com/sites/VHADigitalMedia/vamc-upgrade-project/Shared%20Documents/Forms/AllItems.aspx)
[Document location](https://drive.google.com/drive/folders/1JRZ2jDCP2InRoxT8qn88MQ6DkN1T4ZS1)

## Resources - Tools - Documentation
[Required VAMC WebPage Listing and Drupal Example](https://drive.google.com/drive/folders/1f_PRAt67ccYNm5DkJiAKwINsSX_S5_4o)
[Legacy Lebanon About Page](https://www.lebanon.va.gov/about/index.asp)

## Tasks
_The steps that must be complete before hand off to PAO/Product Lead review_
- [ ] Check Content Tracker for Stories in Zenhub, move to Editing for specific page into Copy Edit
- [x] Download Page for review on local computer (in Word)
- [x] Review copy for content and confirm copy will fit in CMS standard size(s) (See Resources above)
- [x] "Approve or Reject" Content and then document in Tracker
- [x] Update Zenhub story/issue to include Drupal-Copy Editor
- [x] Content is uploaded to appropriate CMS medical system page
- [x] List PREVIEW URL in word document and uploaded to Share Drive (See link above) 
- [ ] Update Tracker 
- [ ] Move story to Validate for PO to confirm all parties are informed and for closure of story

## Acceptance Criteria
_The steps that must be complete before hand off to PAO/Product Lead review_
*  Review copy for content and confirm copy will fit in CMS standard size(s) (See Resources above)
*  "Approve or Reject" Content and then document in Tracker
*  Update Zenhub story/issue to include Drupal-Copy Editor
*  Content is uploaded to appropriate CMS medical system page
*  List PREVIEW URL in word document and uploaded to Share Drive (See link above)

**Comment by LouCarlozo63** [comment]
Got it! Will discuss on our call today.

**Comment by LouCarlozo63** [comment]
Hi Randi: This is now ready for your final copy edit and approval! It is in a folder on the VAMC share drive named Copy Edit Review Complete. This should be the URL: https://drive.google.com/drive/u/1/folders/1_nTEX_RdTM-598yzkEZNNob8wEt6HeW-
Lou

**Comment by RLHecht** [comment]
@SgardnerPMP The Lebanon About us page is now built in Drupal. I left in TK for the text under the Research and development H3. Also, I was unsure whether all these subheads should be H2s or H3s so I only did one H2, which means the "On this page" only has one item. Let me know if this should be changed. Word doc is also uploaded to Sharepoint with the preview link added at the top. Take a look at it all and let me know if I did these steps correctly. Thanks!

**Comment by RLHecht** [comment]
@LouCarlozo63 Here is a copy of my tracked changes so you can see what other copy edits I made. A few reminders: numbers (besides one if alone in a sentence) are always written as numerals and we try to use first and second person as much as possible rather than "Veterans." Let me know if you have any questions.[https://app.zenhub.com/files/133843125/e84b23db-15a7-4f40-8c4d-34d924085a64/download](https://app.zenhub.com/files/133843125/e84b23db-15a7-4f40-8c4d-34d924085a64/download)
