### ISSUE TITLE
Evaluate TAP Curriculum to increase Login.gov adoption amongst newly transitioning Veterans

### ISSUE THREAD

**Issue by elizabethkochBT** [department-of-veterans-affairs/va.gov-team#50283]
## Issue Description
The TAP ([Transition Assistance Program](https://www.dol.gov/agencies/vets/programs/tap)) curriculum needs to be updated to reflect up-to-date information about sign in and credentials for VA services and benefits. This includes the need to:
- add encouragement or recommendation that Veterans set up Login.gov as their primary credential for use with VA services
- if we're unable to remove DS Logon (because Veterans need to use it to access other things), can we make it more clear what it's for/not for
- add clear step-by-step information about how to set up Login.gov
- add clear step-by-step information about how to use Login.gov to access VA services
- include visuals and examples (for example, of which IDs are acceptable)

At this phase, the discovery team has audited the existing curriculum and tracked recommendations in the roadmap for further research and comparative auditing against the newer curriculum. 

There are likely other areas where we can have an impact on an improved curriculum that supports the VA's mission for a single sign on with Login.gov as the recommended credential. Besides updates to the content, our review might include service design related recommendations or recommendations for future research studies we should conduct. For example, during discovery we recommended:
- further research with TAP instructors to better understand the day-of training when Login.gov is introduced
- have physical examples available when necessary, for example, security keys
- extend and promote in-person assistance as an option during or following TAP session
- considering how to promote Login.gov before TAP

There are unknowns for this work, including, a lack of contact points and relationships and a lack of general knowledge about TAP. There is an opportunity to align with VEO and the work they are doing on the Veteran journey.

---
## Tasks
- [x] Review [latest TAP curriculum](https://drive.google.com/file/d/1VR6xesibGuArUSJznxanj0kqZGMpFBfe/view?usp=sharing) released January 2023
- [x] Review opportunities [mural](https://app.mural.co/invitation/mural/innovationboards1199/1666809748438?sender=u258844ddcb06996a24bf4390&key=5ddb8415-cafa-4534-aa9a-f1a344a4ed57)
- [x] Create list of suggestions for changes to the content based on discovery recommendations
- [x] Create list of suggestions for other next steps, which might include future research studies or other service design related tasks based on discovery recommendations
- [x] Share suggestions with PO/PMs for review
- [ ] @elizabethkochBT share final suggested changes to Dr. Hill

## Acceptance Criteria
- [ ] Suggested changes have been sent to Dr. Hill

**Comment by skirkman16** [comment]
Added a new section for opportunities of improvement on the mural board and marked pages for design and MHV content updates

**Comment by skirkman16** [comment]
[https://app.zenhub.com/files/133843125/5d818336-cc76-4a25-a6d0-62b3910b3044/download](https://app.zenhub.com/files/133843125/5d818336-cc76-4a25-a6d0-62b3910b3044/download)

**Comment by skirkman16** [comment]
TAP Recommendations May 2023 [https://app.zenhub.com/files/133843125/0b116091-fac3-4b07-9078-193cfd5909bc/download](https://app.zenhub.com/files/133843125/0b116091-fac3-4b07-9078-193cfd5909bc/download)

**Comment by skirkman16** [comment]
We will share the recommendations (prev. comment) in the next sprint demo on 5/10/2023
