### ISSUE TITLE
[BE] Address validation: Load testing

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5032]
## Tasks
- [x] Write tests for load testing for address validation
- [x] Conduct load testing

## Acceptance Criteria:
- [x] Address validation feature passes load testing.

**Comment by lihanli** [comment]
how many users per day are expected for this feature?

**Comment by Samara-Strauss** [comment]
Let me get back to you on that — I know we track how many updates there are to the mailing address form, but not 100% sure where. I'll track this down.

**Comment by Samara-Strauss** [comment]
Looks like there are ~4700 form submissions of the mailing address form per week.

https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventLabel:profile-transaction,analytics.eventAction:Profile%20-%20Form%20Submit%20-%20mailing-address/

**Comment by lihanli** [comment]
ok thanks
