### ISSUE TITLE
Publish blog about why security is an evolving priority

### ISSUE THREAD

**Issue by elizabethmkoch** [department-of-veterans-affairs/va.gov-team#50333]
## Description 
The VA should utilize traditional and non-traditional methods of education/awareness to help users understand the future of security, and why security standards are evolving and should be a priority. It's more than just preventing someone from stealing your identity. Education methods can include informal moments like Facebook reels or social media that feel relatable.

As a Veteran, I need to be aware of changing security landscapes and my role so I can make informed decisions.

## Acceptance Criteria
- [ ] Blog has been submitted to Mike Molina for publishing

## Tasks
- [ ] @CarlDickerson submit blog to be published
- [x] @CarlDickerson revise blog content based on feedback

**Comment by skirkman16** [comment]
Feedback from CEDAR team and John have been implemented. Waiting for feedback from Sitewide and will implement it before sending the blog to Jordene Chabuk, Ron Haskell, and Tim Hudak (CC) for publishing. Goal is to send blog by Friday 5/19.

**Comment by alevindecanini** [comment]
Per sprint demo on 5/25:

> Goal:
To drive awareness, we have drafted blog post about why security is an evolving priority for Veterans
Gives context of changing security landscape, tying Login.gov in as a secure sign-in option
Supports user stories:
As a Veteran I need to know that the VA recommends I setup a Login.gov credential over others, so I can set up the right credential from the start.
As a Veteran I need to become aware of the changing security landscape and requirements so I understand why the VA is focused on migrating Veterans to Login.gov

>Next Steps:
Discuss the feedback on this blog post with Tim Hudak
Make adjustments to our blog and collab with Danielle Thierry
Share content across VA outlets:
VA Blog
VetResources Newsletter
Social Media Channels

**Comment by alevindecanini** [comment]
Call tomorrow with Danielle will determine path forward

**Comment by lmorris3** [comment]
Closing, meetings with OCTO leads are clarifying these channels (Sitewide/Content will likely own these communications).
