### ISSUE TITLE
Targeted communications based on segmentation and likely path of migration/adoption

### ISSUE THREAD

**Issue by elizabethmkoch** [department-of-veterans-affairs/va.gov-team#50337]
Leverage data around user segmentation for paths of migration to curate targeted communication.

Email content, modal, banners, etc.

Tasks:
 - [ ] targeted communications for users with existing id.me or login.gov (reactivation)
 - [ ] targeted communications for users without existing id.me or login.gov (organic adoption)
 - [ ] targeted communications for users without existing id.me or login.gov  with DS Logon or MHV Premium(DIP)
