### ISSUE TITLE
Campaign landing page about Login.gov

### ISSUE THREAD

**Issue by elizabethmkoch** [department-of-veterans-affairs/va.gov-team#50338]
## Summary

A space where the VA can answer questions posted by Veterans, respond to issues, and be more proactive/responsive to Veteran conversations.

Post the most up-to-date info on credential updates across security, MFA, access to new/other government services.

Link to relevant help resources internal and at Login.gov.

Authenticated view: Consider personalization to Veteran based on where they live—proofing locations if needed (USPS) or VA in-person help options

## User story
As a Veteran, I need a centralized hub for all Login.gov-related resources, enabling me to easily access answers and support.

## Tasks
 - [x] Request campaign landing page (Dave Conlon) ([Example](https://www.va.gov/initiatives/veteran-trust-in-va/))
 - [x] Work on a new blog post (Mike Molina)
 - [ ] Create standard blog responses, and links to the campaign page
 - [ ] SCOD content
 - [ ] Create outreach materials (Tim Hudak - how-to guides from app vs web)
 - [ ] Create an account creation video (Tim Hudak)
 - [ ]  Reach out to Eric.thomas7@va.gov to discuss kms content for login.gov
 - [ ] Based on the previous blog, review key findings and create content focused on the struggles found.
 - [ ] CLP [Content for each panel](https://prod.cms.va.gov/help/campaign-landing-pages/how-to-manage-campaign-landing-pages#undefined)

## Acceptance Criteria
 - [ ] Publish campaign page

**Comment by skirkman16** [comment]
Focus on requesting a landing page first. We can put links to blog post and video first.

**Comment by skirkman16** [comment]
Sofia will share how-to doc with accessibility specialists from Sitewide IA. (Hold on updating until Sprint 19)

**Comment by skirkman16** [comment]
Carl will start next awareness blog post and partner with Amber (Sprint 18)

**Comment by skirkman16** [comment]
Revisit creating a video in Sprint 19. Video can be more focused on the process of binding. since the page is for a campaign it doesn't have to be evergreen
