### ISSUE TITLE
Create Slack announcement for Style Guide Checklist

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#50354]
### Tasks

- [x] Draft a communications announcement for the new style guide checklist, similar to what Bryan Ivie posted on here: https://dsva.slack.com/archives/CJRQ85PQB/p1670269688079519

- [x] Post the draft on #content-chats Slack channel for input

- [x] Decide when to post it (day and time)

- [x] Post it on #platform-team Slack channel

**Comment by BSmolensky** [comment]
Received.
