### ISSUE TITLE
Draft presentation for VAOS 2023 improvements

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#50357]
## Task Description
* Capture ideas for VAOS 2023 improvements in a document.

## References
* None

## Acceptance Criteria
- [ ] Document/presentation exists
- [ ] All asks from Product for changes resolved

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by outerpress** [comment]
Duplicate, closing
