### ISSUE TITLE
Prep  and send 10-10CG form for Spanish translation

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#50377]
## Issue Description

As part of the work we're doing to have more translated content on VA.gov, we are going to publish a Spanish-language version of the 10-10CG online form. 

We need to send a JSON file of the form. 

The product team opened an intake request with this content in issue #49840.

Word doc they supplied: [https://app.zenhub.com/files/133843125/e991c76b-3e39-403a-959b-1cc793c02ab6/download](https://app.zenhub.com/files/133843125/e991c76b-3e39-403a-959b-1cc793c02ab6/download)

## Tasks
- [x] Prep JSON file for translation (Randi)
- [x] Send JSON file to translators (Ana)

## Acceptance Criteria
- [x] Translation team has JSON file

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA I made some updates to the intro page to get it ready to send to translators. 

[https://app.zenhub.com/files/133843125/48e94efb-4a46-4d52-9d96-3de5abb11da7/download](https://app.zenhub.com/files/133843125/48e94efb-4a46-4d52-9d96-3de5abb11da7/download)

**Comment by RLHecht** [comment]
Thanks @shiragoodman I had 2 numbers reversed. Fixed!

**Comment by RLHecht** [comment]
I added the note about translators to the json file wherever we list a phone number. Ana will send this with the landing page to the State Department next week.

**Comment by RLHecht** [comment]
@ABeltran77 Here's the JSON file we want to send to the State Department along with the landing page in ticket #53967.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/Form%20Language%20Translation/10-10CG%20content.json

 Danielle confirmed that we should give them the word counts when we send the files.
