### ISSUE TITLE
Discovery: Determine SLI for vets-api Monitoring and Tools epic

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#50375]
## Description

In addition to the monitoring and tools being developed for vets-api, SLI should be set in place

## Task

- [x] Research SLI's and best practice
- [x] Define SLI's for vets-api

## Acceptance criteria

- [x] SLI ideas defined in this ticket

**Comment by oseasmoran73** [comment]
Doing some research, stumbled upon [lighthouse expectation](https://developer.va.gov/api-publishing/expectations) which can be good guidance on potential SLI's

**Comment by oseasmoran73** [comment]
Four golden signals

**Comment by npeterson54** [comment]
Some ideas from "Ryan"

1. API request latency 2. API availability 3. API throughput 4. API error rate 5. Database query latency 6. Database query throughput 7. Logging and alerting for API errors 8. Number of API calls 9. API response times 10. API response codes

**Comment by ericboehs** [comment]
Some ideas from me:

Top 5:
1. Availability (uptime as measured by DD synthetics)
2. Throughput (number of requests per second)
3. Latency (average response time for a request)
4. Capacity vs Concurrency (number of available workers vs provisioned)
5. Error Rate (percentage of non-successful HTTP requests)

Some more to consider:
- Exception Rate (percentage of requests)
- Log Type Rate (percentage of logs by level)
- External Availability (uptime of external services)
- Job Capacity vs Concurrency (Sidekiq stats)
- Server & DB Saturation (instance/process metrics as well as postgres/redis)
- Login Success Rate (are Veterans able to log in?)

**Comment by rjohnson2011** [comment]
I like Eric's list of SLIs. In terms of displaying these on a dashboard, looks like the following are currently being generated in the APM section of DD:

Throughput:
![image.png](https://images.zenhubusercontent.com/5fb40598d06a06671e842a63/1771733c-0b2f-4051-95ce-10a2a6660c4c)

Latency:
![image.png](https://images.zenhubusercontent.com/5fb40598d06a06671e842a63/94033636-7bf6-4e82-9e75-c95c1190ae4e)

Error Rate:
![image.png](https://images.zenhubusercontent.com/5fb40598d06a06671e842a63/9b451ad0-96a5-4464-ae97-8f11c0b73510)

**Comment by oseasmoran73** [comment]
@rjohnson2011 IMO it makes sense to isolate specifically vets-api. I do think there should be a reference for APM for more specific details, but you can see in synthetic monitor screenshot it is making reference to CMS, OPS, and other stuff

An isolation something like [this](https://vagov.ddog-gov.com/dashboard/t29-k8v-ctv/vets-api-dashboard?from_ts=1670937407984&to_ts=1670941007984&live=true) is where I think its handy from a VSP/PO perspective, and then go into details, then check APM

**Comment by oseasmoran73** [comment]
@rjohnson2011 It might make sense to copy those over first onto the dashboard, then we can probably clean up the APM section later

**Comment by BillChapmanUSDS** [comment]
Sorry for the delay in reviewing this. I was onsite in DC last week. 

Some thoughts: 

Keep it simple in our first pass. As long as we handle the "golden signals" in a simple way in our first effort I think we'll be off to a good start and anything else we add or continue using can be a matter of operational need, I'm assuming everything we have now is there because someone already needed it. I'd like to map a very short list of SLO's to the following on the first pass. 

**Latency**
      Ryan an Eric both mention this. We want to define a simple latency metric. But let's start with what we should measure the latency of. We have two purposes for this SLI.   We want to meet the SLO and the first version of this will probably been average latency across the entire api is less than N. Let's say 150ms for discussion sake. 

So we have an SLI of average latency across all endpoints, and an SLO of average latency < 150ms.  But the second need we have (maybe not on day one) is granularity of observability.   What do we want to observe?  

- average latency by successful request over entire api
- average latency by unsuccessful request over entire api. 
- average latency by successful request and by endpoint
- average latency by unsuccessful request and by endpoint

I think we'll also need to eventually track latency across all service boundaries in the same way. But whether or not we can or will define SLO here will depend on how much influence we have over that external system. 

- average latency by request to service A. 
- average latency by request to service B


**Traffic** 
 The lists above mention throughput, and we can roughly equate that here. Let's say HTTP requests per second. But this is a measure of load on a system and not the load **capability** of the system. We need to convert that to an SLO and that can be tricky. For that we can keep it simple, The api as a whole should be able to handle a specific number of requests per second across the board without pushing other SLIs out of range. I'm still thinking on this one here.   

**Errors**
 Also mentioned above, which is great, we are well aligned.  Errors in production should trend to zero over time. If we have a high error rate we will have to start just below that number for SLO definition purposes and ratchet it down as we improve any delivery process. 

For observability we'll want to see overall errors and errors by endpoint. The SLO will get more aggressive over time. 

Outside of SLO, we'll want to know every time an external service returns a response that we interpret as an error (500, or 200 with error message etcc) 

**Saturation**
   This is partially covered in capacity that is mentioned above.  Normally I'd start with some simple measures of capacity as an SLI and the SLO would be that we want to maintain a specific level of saturation of those resources.  We can break it out by individual resource or we can come up with a value that represents an aggregate of those resources. 

With all that said,  even with the golden signals, while they are almost always useful, we want to focus on those metrics that we think are going to give us the most insight in to current operational issues. 

This is just a first collection of thoughts, any and all feedback appreciated. 

I'm looking forward to these discussions.

**Comment by npeterson54** [comment]
The final 4:
Availability (uptime as measured by DD synthetics)
Latency (average response time for a request)
Capacity vs Concurrency (number of available workers vs provisioned)
Error Rate (percentage of non-successful HTTP requests)
