### ISSUE TITLE
Refactor location and genericLocation properties

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#5038]
## Goal
**Remove redundant code:**
After work done in previous sprints to fix the JSON schema issues with the form 686 we realized there is a lot of redundant code as well as code that does not follow best practices in the form 686 config and schema files and needs to be removed. The two properties this redundant code centers around is the `location` property and the `genericLocation` Property. 

## Considerations
`location`
For the location property we have created one set of schema that the form data will be validated against, though currently the code has a schema using a set of three subschemas (two of which are now not needed). We need to refactor this so that instead of using the `oneOf` schema with three subschemas, we simply have one schema with no subschemas and reference that one schema.

We also changed the schemas so that the `marriages`, `spouseMarriages`, and `childRelationship` properties in `form.js` now all reference the same data structure to validate against. To refactor this we should create a single data structure inside the schema file and instead reference that so that we reduce redundant code.

`genericLocation`
In the past sprints we added, then removed the `genericLocation` property from the schema file, we need to search through both the schema file and the `form.js` file and make sure all remnants of this `genericLocation` are removed and no longer used.

## Tasks
- [ ] Refactor `location` property
- [ ] Remove `genericLocation` propoerty from the schema file and the form.js file

## Acceptance Criteria
- [ ] Code has been cleansed
