### ISSUE TITLE
Bump rubocop-rails from 2.17.2 to 2.17.3

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#50389]
## Issue Description
Bump rubocop-rails from 2.17.2 to 2.17.3

PR - https://github.com/department-of-veterans-affairs/vets-api/pull/11288

---
## Tasks
- [ ] Fix all new Rubocop issues

## Acceptance Criteria
- [ ] All new Rubocop issues are fixed.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by holdenhinkle** [comment]
I fixed a few issues today when I had the time.

Here are the remaining files Rubocop is complaining about:

```
modules/appeals_api/spec/factories/supplemental_claims.rb:9
modules/claims_api/spec/factories/power_of_attorney.rb:9
modules/claims_api/spec/factories/supporting_documents.rb
modules/claims_api/spec/models/auto_establish_claim_spec.rb:458:9
modules/claims_api/spec/models/power_of_attorney_spec.rb
modules/claims_api/spec/models/supporting_document_spec.rb
modules/claims_api/spec/requests/v1/disability_compensation_request_spec.rb
modules/claims_api/spec/requests/v1/disability_compensation_request_spec.rb
modules/claims_api/spec/requests/v1/power_of_attorney_request_spec.rb
modules/claims_api/spec/requests/v1/rswag_disability_compensation_request_spec.rb
modules/claims_api/spec/workers/claim_uploader_spec.rb
modules/claims_api/spec/workers/claim_uploader_spec.rb
modules/claims_api/spec/workers/claim_uploader_spec.rb
modules/mobile/spec/request/claims_document_upload_spec.rb:
spec/controllers/v0/financial_status_reports_controller_spec.rb
spec/factories/evss_claims.rb:8
spec/factories/form526_submissions.rb
spec/factories/form5655_submission.rb
spec/factories/rubysaml_settings.rb
spec/jobs/education_form/create_daily_spool_files_spec.rb
spec/jobs/facilities/access_data_download_spec.rb
spec/jobs/facilities/facility_location_download_job_spec.rb
spec/jobs/facilities/pssg_download_spec.rb
spec/lib/debt_management_center/financial_status_report_service_spec.rb
spec/lib/debt_management_center/sharepoint/request_spec.rb
spec/lib/evss/documents_service_spec.rb
spec/lib/sftp_writer/factory_spec.rb
spec/requests/documents_spec.rb
spec/requests/id_card_attributes_request_spec.rb
spec/requests/swagger_spec.rb
spec/serializers/evss_claim_detail_serializer_spec.rb
```

**Comment by holdenhinkle** [comment]
We've decided to merge this. Going forward, if other engineers experience this cop complaint, they can follow the pattern I used here to spread an array of path strings into args or disable the cop.
