### ISSUE TITLE
Implement Dashboard which displays SLIs

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#50418]
## Description
Implement a dashboard so that our customers can see the status/health of Vets-API 

## Tasks
- [x]  Configure Datadog Dashboard to configure SLIs
- [x] Create a wireframe to define the layout
- [x] Test the dashboard to ensure it is functioning properly
- [x]  Setup correct Permissions

## Acceptance Criteria
- [x]  Dashboard is able to display all available SLIs 
~~Dashboard is defined in Terraform~~ [Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50415#issue-1479887390)

## How to configure this issue
- [x] _Attach a Milestone_
- [x] _Story points_
- [x] _Sprint assigned if pulling into sprint_
- [x] _Epic assigned_
- [x] _Team label assigned_

**Comment by oseasmoran73** [comment]
Looks like information is not being gathered for vets-api in ELB2. Will need to do some debugging if we want this information (as I would presume we would)

**Comment by oseasmoran73** [comment]
Sidekiq is now live in EKS for dev. [Slack](https://dsva.slack.com/archives/C04CYC4LMU6/p1671040694605669) for confirmation

We will need to monitor for those + BRD

**Comment by oseasmoran73** [comment]
Need to figure out why sidekiq in dev is not being picked up via DD now that it is in EKS

**Comment by oseasmoran73** [comment]
@rjohnson2011 Currently pending:

- [ ] EC2 Instances (from 2nd ASG)
- [ ] Sidekiq data for dev (reported from EKS)
- [ ] Throughput
- [ ] Exception rate
- [ ] Login Success Rate

**Comment by oseasmoran73** [comment]
@rjohnson2011 can you review any last bit of details, task & AC, then move to review column if its been met

**Comment by oseasmoran73** [comment]
Met with Bill Chapman before the holidays and got first pass and looked okay with current implementation. Working on SLO's implementation. Moving to the review column

**Comment by oseasmoran73** [comment]
> Documentation for the dashboard is easily accessible and understandable

@npeterson54 Do you recall the specificity of this task? Where would you like this documented?

**Comment by oseasmoran73** [comment]
@npeterson54 Which confluence page do I put it in? Tech team 3? Tech Support?

**Comment by mchelen-gov** [comment]
Reminder that DD config should make its way to Terraform.

**Comment by oseasmoran73** [comment]
Spoke to @npeterson54 regarding documentation and said that it will most likely be a collaboration with Bill (including where it will live).

Moving to review state

**Comment by npeterson54** [comment]
Since the docs will be its own story @BillChapmanUSDS Have you created one yet for that living document?  I think we are good to close this one out.

**Comment by oseasmoran73** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/53432 for documentation portion. Moving to review state

**Comment by npeterson54** [comment]
Looks good to me, closing out.
