### ISSUE TITLE
Define schedule and process, and begin drafting On Support guidance

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#50412]
## User Story
As a Governance team member, I want to define a schedule and process for implementing an On Support schedule/rotation so that we can begin using it as soon as possible and no longer have confusion on who's responsible for responding to support requests.

Assignee: @CherylEvans 
Peer Reviewer: @briandeconinck 

## Description
In ticket #49477, Governance team decided to not move forward with utilizing PagerDuty for implementing a Governance team On Support schedule. Instead, Governance team will utilize existing tools (Confluence, Slack, Email) to define a schedule and process for being "On Support." This ticket will also include drafting On Support guidance to be published in the Governance team Confluence space.

## Impacted Artifacts
- ["On Support" guide](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2454093924)
   - no need to create a draft first. Feel free to edit this page directly

## Tasks
- [ ] Identify what information Governance team members would need to know when On Support
   - brain storming session 12/8?
- [ ] Update the "On Support" guide (feel free to change the name) to include necessary information  

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] On Support guidance has been drafted
- [ ] An On Support schedule has been drafted and shared with Governance team

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Things we need to add to On Support guide:

- team members need to make sure they're available the days/week they're on support
- process for changing the schedule if needed
- definitions of On Support vs. Backup
- notifying your backup person if you're stepping away for a few imagine
- expectation for time it takes to respond to a support request
- emoji respond with the eyes when you see the request
- respond within 2 hours or less

**Comment by shiragoodman** [comment]
@briandeconinck @CherylEvans I have reviewed the on-support guide and made some comments. Please review and let me know if you have any concerns.

**Comment by shiragoodman** [comment]
what is the status of this? I made comments on 12/19 and have not seen any updates on this ticket since then.

**Comment by CherylEvans** [comment]
@briandeconinck Hi Brian. Happy New Year! I have incorporated Shira's recommendations, and am ready for you to review my draft page. I have resolved Shira's comments, but would ask that you go back and look at her comments to ensure that I made the changes that she requested. Thanks again Brian! Please reach out if you have any questions or concerns.

**Comment by CherylEvans** [comment]
@shiragoodman I have been making steady progress on this document and implemented your recommendations. I have submitted to @briandeconinck  for review.

**Comment by briandeconinck** [comment]
@CherylEvans Flagged a couple of accessibility improvements for the page and commented on one spot where there's some ambiguity. But otherwise I think this is pretty clear.

It might still be worth it for us to meet again and do another walkthrough.

**Comment by CherylEvans** [comment]
@briandeconinck I incorporated your recommendations into the [draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2454093924/On-Support+guide).  Thank you for recommending the accessibility changes as those are not typically on my radar.  :-) 
Please look it over, and I will schedule some time for us this week to walk through.  Should we include @shiragoodman in the meeting, or wait until we give it another run-through?

**Comment by briandeconinck** [comment]
Updated version all looks good to me! I don't remember where we landed in stand-up, still want to do a run-through?

**Comment by CherylEvans** [comment]
@briandeconinck I made a few more minor changes this morning based on Shira's previous comments.  Will you take another quick look, and let me know if you're good with it.  If you are, I will tag Shira and get her input.  I don't see any reason to do another run-through at this point.  I think it is close! :-)

**Comment by CherylEvans** [comment]
@shiragoodman Brian and I have both gone over the [draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2454093924/On-Support+guide) and would like to get your recommendations before we make any additional changes.

**Comment by shiragoodman** [comment]
@CherylEvans I made quite a few comments. Please take a look and let me know if you'd like to set up a meeting to discuss.

**Comment by CherylEvans** [comment]
@shiragoodman I incorporated many of your recommendations; however, I would like to get together and discuss a few.  Once we meet and discuss these few items, we will be just a few days from wrapping this up!

**Comment by CherylEvans** [comment]
@shiragoodman @briandeconinck Hi Shira. I made the changes from our meeting, then Brian looked them over and made additional recommendations. I have made the edits, and it is ready for your review, fingers crossed.!! [Draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2454093924/On-Support+guide)

**Comment by shiragoodman** [comment]
@CherylEvans I provided a couple additional comments. All minor. Feel free to close this out once addressed and I'll move forward with scheduling the training.

**Comment by CherylEvans** [comment]
@shiragoodman I have incorporated your recommendations and will close the ticket.
