### ISSUE TITLE
Research Request - Tech Team 2 - Step 2

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#50410]
## Issue Description
A Research [Request ](https://dsva.slack.com/archives/CPCGRR7F1/p1666381261475809)was made and our team met w/ TT2 to hear out their thinking.

_From Jesse:  We’d like to gather info from VFS teams regarding their needs for platform monitoring tools. We hope the understand the use cases and how VFS teams might use Datadog for monitoring.
I’d be happy to collab with your team on technical surveys/interviews/etc to collect the info we’re interested in._ 

For Reference: Template [Research Intake Doc](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2417524758/Research+Intake+Document+DRAFT)

The following mural was the result of that meeting, w/ key ideas organized within.
Research request [mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1666630906186/d0ea57ee847ffd0b57d49abf4224a1d27a1531ec?sender=u4397b715dc3690a417b71483)

[initial thoughts/questions for participants and important research logistics](https://vfs.atlassian.net/wiki/spaces/~318780155/pages/2446295046/Discovery+w+TT2)

## Tasks
- [x] Create survey in Optimal Workshop
- [x] Pilot survey with tech lead and 1 VFS engineer
- [x] [Launch survey](https://ows.io/qs/ns7w5ro0)

## Acceptance Criteria
- [x] Survey is launched to VFS teams
