### ISSUE TITLE
Set Alerts/Notifications for SLOs

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#50419]
## Description
Now that we have defined our Service Level Objectives (SLOs) for the Vets API, it's important to set up alerts so that we can monitor the API's performance and be notified if any of the SLOs are not being met. In this ticket, we will work on configuring alerts for the SLOs we have defined, including specifying the thresholds that will trigger an alert and the methods for delivering the alert (e.g. email, Slack, etc.)

## Tasks
- [x] Review the defined SLOs and associated target values
- [x] Identify the thresholds that will trigger an alert for each SLO
- [x] Configure the alerting system to deliver notifications when the thresholds are breached
- [x] Test the alerting system to ensure it is working correctly

## Acceptance Criteria
- [x] The alerting system is correctly configured and delivers notifications when the specified thresholds are breached
- [x] The alerts are delivered via the specified methods (e.g. email, Slack, etc.)
~~[ ] The alerts include the necessary information to understand the issue and take appropriate action (e.g. API endpoint, performance metric, target value, etc.)~~
- [x] The alerting system is tested and confirmed to be working correctly.

**Comment by oseasmoran73** [comment]
I don't think we have defined our SLOs have we?

**Comment by npeterson54** [comment]
> I don't think we have defined our SLOs have we?

Our SLOs are what we are currently performing at in Vets-API per @BillChapmanUSDS @mchelen

**Comment by BillChapmanUSDS** [comment]
We have not yet defined specific SLO but I'm pushing to keep them simple and a short list based on the Golden Signals. I have some thoughts on that in [This Link](https://app.zenhub.com/workspaces/platform-tech-team-3-6335ab9b1901b99243ce7601/issues/department-of-veterans-affairs/va.gov-team/50375)

**Comment by oseasmoran73** [comment]
@npeterson54 Regarding what was discussed in standup, for alert of these notifications, what channel should they alert?

My two cents, depending on how much more alerts/notifications we are going to be sending (outside of SLO), it may be a good idea to create a new channel to send them. Thoughts?

**Comment by npeterson54** [comment]
I think a new channel would be a good idea.  Thoughts @mchelen @BillChapmanUSDS

**Comment by BillChapmanUSDS** [comment]
I think a channel focused on alerts and notification, and maybe even periodic summaries of SLO's makes sense.  SLO tracking is not the same as operational/firefighting response and alert tracking so the idea that those alerts might get missed because they are not in an active channel might not be a problem. So any alerts that indicate a failure scenario would need to be delivered to the approprate place. But a notification that are just informational about SLO targets being missed, or summaries of how we might have done in a given period?  It would be quite nice to give them a home. @mchelen  thoughts on getting that channel created?

**Comment by oseasmoran73** [comment]
2/4 of the SLO have been created and alerting as intended. Given that some of them are metrics, it looks like we cant create alerts for them. Investigating some alternatives for the time being or to convert them into synthetics to achieve the information we would like to alert

**Comment by oseasmoran73** [comment]
More to be spun up accordingly as we gather more metrics

**Comment by npeterson54** [comment]
@BillChapmanUSDS @mchelen-gov Thoughts on getting a permanent channel created for these alerts?

**Comment by mchelen-gov** [comment]
I'd be fine with #platform-slo-alerts for the reasons Bill mentioned.

**Comment by oseasmoran73** [comment]
Given that we have some data on SLO's reporting, the following tasks are required:

- [ ] Modified AC
- [ ] Spin up new tickets from what was learned + gathered from SLOs reporting
- [ ] Spin up new ticket for specific action items

CC @npeterson54 

Will move ticket to `review` column upon creating tickets

**Comment by npeterson54** [comment]
Closing out, looks good to me.
