### ISSUE TITLE
Migrate existing backend/console_service synthetics as IaC

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#50415]
## Description

We should follow best practice and write them as IaC for synthetic tests

## Task
- [x] Review current synthetic that pertained to BE/Console service that are not written and IaC and create additional tasks
- [x] Create folder (if it does not exists) in devops repo for vets-api TF
- [x] Migrate [test](https://vagov.ddog-gov.com/synthetics/details/3an-kpt-ep7?live=1d)
- [x] Migrate [feature_toggle](https://vagov.ddog-gov.com/monitors/88917)

## Acceptance Criteria
- [ ] Platform synthetic tests written previously by CS/BE folks are IaC

**Comment by oseasmoran73** [comment]
Migrate [Vets-api logs](https://vagov.ddog-gov.com/monitors/101922)

**Comment by oseasmoran73** [comment]
Ensure correct service tag is in the followings: 
https://vagov.ddog-gov.com/monitors/88865
https://vagov.ddog-gov.com/monitors/88889
https://vagov.ddog-gov.com/monitors/88867
https://vagov.ddog-gov.com/monitors/88854

**Comment by oseasmoran73** [comment]
Now that most of the base of vets-api dashboard has been creating, I still say we should have it all as IaC

**Comment by oseasmoran73** [comment]
Recreated one in [TF](https://vagov.ddog-gov.com/synthetics/details/sar-yc8-pi2) and will observe for the time being to ensure no drift
