### ISSUE TITLE
Update unit tests on form 686

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#5041]
## Goal
After the recent work we have done on the form 686 to fix schema issues and refactor those fixes is finished, some of our unit tests now need to be updated to reflect the changes so they pass. 

## Tasks
- [ ] fix all broken unit tests for form 686 config

## Acceptance Criteria
- [ ] Unit test are fixed and completed

## Next Steps
- [ ] End to end tests will need be addressed after as well
