### ISSUE TITLE
FY23 Initiatives Planning

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#50423]
## Purpose
Discuss and identify the Initiatives to work on in FY2023

## Tasks
- [x] Prep concepts & draft frameworks
- [x] Prep [planning Mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1672762257243/5e02c5e2723da6e1e191480ae13ee657449a9f1b?sender=u4397b715dc3690a417b71483) (Bryan)
- [x] Insert leading ideas to pursue (open to all)
- [x] schedule Planning Session 1 (Bryan)
- [x] workshop: Planning Session 1
- [x] check w/ Naomi about the IA initiative
- [x] Get PO signoff on Initiatives
- [x] schedule followup session (Bryan)
- [x] workshop: followup

## Acceptance Criteria
- [x] Mural is readied w/ formatting and initial ideas
- [x] Main Initiatives are decided upon
- [x] Main Initiatives are translated into Epics

**Comment by steel36** [comment]
Naomi didn't feel the team needed to devote its attention this right now.
