### ISSUE TITLE
FY23 Tasks Scheduling

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#50426]
## Purpose
Schedule the tasks to accomplish FY2023 Initiatives

## Tasks
- [x] schedule session
- [x] establish potential positioning for work
- [x] workshop to move tasks into sprints to plan work (Thursday)

## Acceptance Criteria
- [x] Tasks are moved to intended Sprints and reviewed
