### ISSUE TITLE
Add messaging for revproxy error rate

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#50433]
## Description
The "revproxy error rate high" happens fairly frequently and the incident commander is paged. Add a section to alerts.md so the IC will know how to debug.

---
## Tasks
- [x] alerts.md in the sensitive repo is updated
- [x] the alert itself is updated with a link to the new messaging in alerts.md.

## Acceptance Criteria 
- [x] PRs to sensitive repo and devops repo are merged.

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by rmtolmach** [comment]
PR to sensitive repo:
* https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/654
PR to devops repo:
* https://github.com/department-of-veterans-affairs/devops/pull/12323

Hitting some blockers in the devops PR. The terraform state in the datadog environment is dirty. Working to resolve it with Kyle tomorrow.
