### ISSUE TITLE
[COPY-EDIT] Review content of "ALTOONA, PA - ABOUT" for plain language and insertion into CMS/VA facility web page [COPY-EDITOR]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#5043]
## User Story or Problem Statement
As a Veteran Web user, I need a need a plain language description of services in the "ABOUT", web page for Altoona VA Health Care System website so I can quickly understand the services and service location for my needs.

## Goal
_Efficient and clear content describing local Work With US Page?_

## Objectives or Key Results this is meant to further
- _Reduced word count and improved plain language._

##Copy Locations
_Where copy is stored and where it will be placed for review_
[Content Tracker](https://drive.google.com/drive/folders/1w6O8JZ42Jkp1Sa9QOt9Lv4R9WjJFEp3O)
[VAMC Share Drive](https://drive.google.com/drive/folders/1w6O8JZ42Jkp1Sa9QOt9Lv4R9WjJFEp3O)
[VAMC SharePoint Documents](https://dvagov.sharepoint.com/sites/VHADigitalMedia/vamc-upgrade-project/Shared%20Documents/Forms/AllItems.aspx)
[Document location](https://drive.google.com/drive/folders/1JRZ2jDCP2InRoxT8qn88MQ6DkN1T4ZS1)

## Resources - Tools - Documentation
[Required VAMC WebPage Listing and Drupal Example](https://drive.google.com/drive/folders/1f_PRAt67ccYNm5DkJiAKwINsSX_S5_4o)
[Legacy Altoona, PA About Page](https://www.altoona.va.gov/about/index.asp)

## Tasks
_The steps that must be complete before hand off to PAO/Product Lead review_
- [ ] Check Content Tracker for Stories in Zenhub, move to Editing for specific page into Copy Edit
- [x] Download Page for review on local computer (in Word)
- [x] Review copy for content and confirm copy will fit in CMS standard size(s) (See Resources above)
- [ ] "Approve or Reject" Content and then document in Tracker
- [x] Update Zenhub story/issue to include Drupal-Copy Editor
- [x] Content is uploaded to appropriate CMS medical system page
- [x] List PREVIEW URL in word document and uploaded to Share Drive (See link above) 
- [ ] Update Tracker 
- [ ] Move story to Validate for PO to confirm all parties are informed and for closure of story

## Acceptance Criteria
_The steps that must be complete before hand off to PAO/Product Lead review_
*  Review copy for content and confirm copy will fit in CMS standard size(s) (See Resources above)
*  "Approve or Reject" Content and then document in Tracker
*  Update Zenhub story/issue to include Drupal-Copy Editor
*  Content is uploaded to appropriate CMS medical system page
*  List PREVIEW URL in word document and uploaded to Share Drive (See link above)

**Comment by LouCarlozo63** [comment]
In your hands Randi; in the same folder as Lebanon, which I copy edited and assigned to you earlier. Lou

**Comment by RLHecht** [comment]
@SgardnerPMP The Altoona page is now built in Drupal and the Word doc is uploaded to SharePoint with the Preview URL in there. I had the same questions as with Lebanon about whether headers should be H2s or H3s.

**Comment by RLHecht** [comment]
@LouCarlozo63 Here's a copy of my tracked changes in Altoona for you to look at. Let me know if you have any questions.[https://app.zenhub.com/files/133843125/37f7a0a7-922b-4c9b-b445-af4e80c2cef6/download](https://app.zenhub.com/files/133843125/37f7a0a7-922b-4c9b-b445-af4e80c2cef6/download)
