### ISSUE TITLE
Form Library | Add CustomPage missing properties

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#50437]
## Description

While adding a `CustomPage` and `CustomPageReview` combo to our Supplemental Claim form, I noticed the 
following:

- `CustomPageReview` is rendered on the review and submit page in review mode (edit button showing)
- `CustomPage` is rendered on the review & submit page while in edit mode

The problem is that the `CustomPage` component is not passed the `setFormData` property within the `ReviewCollapsibleChapter` component.

In the documentation, it shows that the `setFormData` is an expected parameter, so adding this will match what is expected.

## Tasks

- [ ] Pass `setFormData` to `CustomPage` component
- [ ] Add unit tests

## Acceptance criteria

- [ ] All tasks completed
- [ ] All tests passing
