### ISSUE TITLE
Form Library | Add CustomPage missing properties

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#50432]
## Description

While adding a `CustomPage` and `CustomPageReview` combo to our Supplemental Claim form, I noticed the 
following:

- `CustomPageReview` is rendered on the review and submit page in review mode (edit button showing)
- `CustomPage` is rendered on the review & submit page while in edit mode

The problem is that the `CustomPage` component has no indication that the component is in edit mode - we need to hide the page navigation buttons, etc.

I propose adding a new edit mode state boolean value.

## Tasks

- [ ] Pass edit mode status to `CustomPage` component
- [ ] Add unit tests
- [ ] Update documentation

## Acceptance criteria

- [ ] All tasks completed
- [ ] All tests passing
