### ISSUE TITLE
VAMC Custom Survey Data Visualization

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#50449]
## Issue Description
The VAMC custom survey went live on December 5, 2022. Currently, we are gathering all the answers but don't have an visual representation of the answers that can be shared with the VHA digital and VA.gov sitewide team. 

---
## Tasks
- [x] Determine strategy for data visualization of survey answers (i.e. in Medallia or Domo or both?)
- [x] Build out visualizations in Domo or by request in Medallia
- [ ] Share with VHA Digital and VA.gov sitewide team for feedback and use

## Acceptance Criteria
- [ ] An accepted data visualization for the VHA digital and VA.gov sitewide team
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
Reviewed initial design by Sarkis, will demo to team soon.

**Comment by ATMiddleton** [comment]
Sarkis will build.
