### ISSUE TITLE
Salesforce Email Implementation Roll Out

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#50450]
On December 15th, Salesforce will be rolling out a new email capability that will allow the Tier 2 team to email to users directly from Salesforce. This will change some of our processes and require training to ensure all team members know how to use this new functionality. 

## Tasks
- [ ] Determine processes for new salesforce email feature and document within confluence
- [ ] Conduct a training for all Tier 2 team members. Record and store on confluence

## Acceptance Criteria
- [ ] Tier 2 team is prepared to use new email functionality at launch and there is documentation that clearly sets the guidelines for how this tool should be used for reference and future team additions. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
Email to case functionality is active
