### ISSUE TITLE
Create and publish TOE rates page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#50455]
## Issue Description
Now that we've migrated our main GI Bill program rates pages we need to create a similar rates page for the [Transfer of Entitlement](https://www.va.gov/education/transfer-post-9-11-gi-bill-benefits/) program. 

First we need to research if the rates information is similar to the Post-9/11 GI Bill rates. If it is, we can clone the page and make changes specific to this program throughout. Once we've made the changes we'll need to get approval from the stakeholders before publishing.

## Tasks
- [x] Research TOE rates info (Katherine)
- [x] Clone Post-9/11 rates page if needed (Katherine)
- [x] Update page with current rates info (Katherine)
- [x] Review (Beth)
- [x] Send to stakeholder for approval (Katherine)
- [x] Copyedit (Megan)
- [x] Set up menu items and url (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [ ] TOE rates page is live on the site

**Comment by katherine-fung** [comment]
Page preview here: http://preview-prod.vfs.va.gov/preview?nodeId=51816 

I met with Cinda and Jodie today to get more info about TOE rates. I still need to update the related links on this page.

**Comment by katherine-fung** [comment]
I showed this page to Beth yesterday, and will show it to SMEs tomorrow.

**Comment by katherine-fung** [comment]
I made another round of edits based on feedback today, and sent them off to SMEs.

**Comment by katherine-fung** [comment]
Jodie responded with 2 comments about the draft, and I've updated the page accordingly. 

Now we're waiting for her and Cinda to decide whether a detail about eligibility tiers should be on the page.

**Comment by katherine-fung** [comment]
We've sent this page to Cinda and Jodie for approval re: the MHA language. If they're ok with it, they'll forward the preview to stakeholders at the Buffalo processing office for their review.

**Comment by megzehn** [comment]
Noting here that I copy edited this page and left it in drafts until we get further approval. I also changed the URL to match the pattern we have on Post-9/11, but @RLHecht, please correct if that's wrong!

/education/benefit-rates/transferred-post-911-gi-bill-benefit-rates

Thanks for working on this @katherine-fung !

**Comment by RLHecht** [comment]
Moving to blocked until we get OK to publish.

**Comment by katherine-fung** [comment]
Hi @megzehn, 

At long last, the TOE rates page is ready to copy edit and publish: 
http://preview-prod.vfs.va.gov/preview?nodeId=52955

This can wait if there's more urgent work on your plate. 

We should work on this together with the VET TEC rates page in ticket #50456.

**Comment by katherine-fung** [comment]
Once we close #50455 and #50456, we can also close ticket #57953.
