### ISSUE TITLE
Refactor terraform.yml and Remediate Datadog Terraform environment automation

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#50452]
## Description
The terraform automation fails in a PR that has changes to anything in the Datadog environment.

![image](https://user-images.githubusercontent.com/10993987/206224249-cbc5abd4-3682-4bbe-9594-0265a24f72e7.png)

## Background/context 
- https://dsva.slack.com/archives/C04CYC4LMU6/p1670358721408579?thread_ts=1670282756.823439&cid=C04CYC4LMU6
- This PR was started, but abandoned because it wasn't a full fix https://github.com/department-of-veterans-affairs/devops/pull/12329

## Technical notes
- Different sets of terraform envs/folders use different versions
- use `.terraform-version` file if present, otherwise default to `0.13.7` (i.e. whatever is set for the tf-setup gha)
- currently the tf gha used for PRs etc is massive, 1073 lines. it would be nice to dry this up.

---
## Tasks
- [x] add `.terraform-version` file(s) for local applies
- [x] refactor w/ composite action

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [x] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)

**Comment by ianhundere** [comment]
```
          TF_ENV="${$TF_FOLDER##*/}"
          echo $TF_ENV
```
this works locally to grab the environment / value we'll use for the path change gha.

will try sending that to github env:
`echo TF_ENV="${${{ env.TF_FOLDER }}##*/}" >> $GITHUB_ENV`

**Comment by ianhundere** [comment]
and it works:
```
      # test
      - run: |
          TF_ENV="${TF_FOLDER##*/}"
          echo $TF_ENV
          echo "TF_ENV=$TF_ENV" >> $GITHUB_ENV
      - run: echo ${{ env.TF_ENV }}
```

**Comment by ianhundere** [comment]
successful run with action; will now:
-[ ] create necessary jobs for the appropriate envs etc
-[ ] update any actions that need to be updated

**Comment by ianhundere** [comment]
now running into an issue whereby an if condition is always evaluated as true when expression syntax is used:
https://github.com/actions/runner/issues/1173

**Comment by ianhundere** [comment]
i have a working solution, but just going over some things to ensure there's no other way.

**Comment by ianhundere** [comment]
ran into another issue whereby the plan output could be too long. i've fixed that, just need to do more testing against all envs.

**Comment by ianhundere** [comment]
tfenv caused too many issues with plan output. i've included the tf version files for when people do local applies to ensure the appropriate version is used, but will not include it in the pipelines.

**Comment by ianhundere** [comment]
final bit will be to have the path filter gha at the top of the workflow to avoid spinning up multiple runners.
