### ISSUE TITLE
Upgrade Cypress to latest version (12.0.1)

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#50451]
# Description
Cypress needs to be upgraded from 10.8 to 12.0.1 in `vets-website` (as of the time of the creation of this ticket. Versions move fast!)

# Tasks
- [ ] Read through the Cypress changelog
- [ ] Upgrade to the latest version in `vets-website`
- [ ] Verify that there are no regressions in the e2e test suite

# Acceptance Criteria
- [ ] `vets-website` is operating the latest version of Cypress

**Comment by pjhill** [comment]
Current version is now 12.3.
Draft PR [here ](https://github.com/department-of-veterans-affairs/vets-website/pull/23201)-- waiting on CI outcome

**Comment by CBonade** [comment]
Needs to be done and need to check latest version.

**Comment by caw310** [comment]
DST will add this to Sprint 29 plan.

**Comment by CBonade** [comment]
duplicate ticket, other is in progress, closing.
