### ISSUE TITLE
Create and publish VET TEC rates page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#50456]
## Issue Description
Now that we've migrated our main GI Bill program rates pages we need to create a similar rates page for the [VET TEC](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/). 

First we need to research if the rates information is similar to the Post-9/11 GI Bill rates. If it is, we can clone the page and make changes specific to this program throughout. Once we've made the changes we'll need to get approval from the stakeholders before publishing.

## Tasks
- [x] Research VET TEC rates info (Katherine)
- [x] Clone Post-9/11 rates page if needed (Katherine)
- [x] Update page with current rates info (Katherine)
- [x] Review (Beth)
- [x] Send to stakeholder for approval (Katherine)
- [x] Copyedit (Megan)
- [x] Set up menu items and url (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] VET TEC rates page is live on the site

**Comment by katherine-fung** [comment]
I've created the VET TEC rates page: 

http://preview-prod.vfs.va.gov/preview?nodeId=52956 

I need to go back in and update the related links.

**Comment by katherine-fung** [comment]
I showed this page to Beth yesterday, and will show it to SMEs tomorrow.

**Comment by katherine-fung** [comment]
I made another round of edits based on feedback today, and sent them off to SMEs.

**Comment by katherine-fung** [comment]
I made another round of edits based on feedback today, and sent them off to SMEs.

**Comment by katherine-fung** [comment]
Cinda gave her last update to this page. She wants to send the page preview to the Buffalo regional processing office for approval. We'll send the link together with the STEM rates page when that's ready.

**Comment by katherine-fung** [comment]
We've sent the STEM and VET TEC rates pages to Cinda and Jodie. We're waiting for feedback on MHA language on the STEM rates page. Once she ok's that language, she can go ahead and forward the preview pages to the Buffalo team for approval.

**Comment by megzehn** [comment]
Noting here that I reviewed what we have on this page so far! 

FYI, @RLHecht, I also adjusted this URL to /education/benefit-rates/vet-tec-rates 

Could you make sure that's correct? 

Thank you, @katherine-fung!

**Comment by RLHecht** [comment]
Moving to blocked until we get confirmation to publish.

**Comment by katherine-fung** [comment]
Hi @megzehn, 

At long last, the VET TEC rates page is ready to copy edit and publish: 
http://preview-prod.vfs.va.gov/preview?nodeId=52956

This can wait if there's more urgent work on your plate. 

We should work on this together with the transferred rates page in ticket #50455.

**Comment by katherine-fung** [comment]
Once we close #50455 and #50456, we can also close ticket #57953.

**Comment by katherine-fung** [comment]
Once we close #50455 and #50456, we can also close ticket #57953.

**Comment by katherine-fung** [comment]
Hi @megzehn, 

Here are the pages for copy edit: 

Current rates VET TEC: 
http://preview-prod.vfs.va.gov/preview?nodeId=59419

Past rates VET TEC: 
http://preview-prod.vfs.va.gov/preview?nodeId=52956


VET TEC program page - I just added a cross link to the current rates page: 
http://preview-prod.vfs.va.gov/preview?nodeId=930

**Comment by megzehn** [comment]
Update: we're publishing these all on August 1 when the rates officially change.

**Comment by megzehn** [comment]
These are published. Moving to validate.

**Comment by katherine-fung** [comment]
These pages are live. Closing the ticket
