### ISSUE TITLE
INTL - Sitewide Home Dashboard Update - Data Modeling

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#50475]
## Issue Description
The purpose of this ticket is to complete the date modeling needed to create the new/update datasets for the [Sitewide homepage update request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49618) to their [Domo dashboard](https://va-gov.domo.com/page/80919003) .

Phil to lead, Chloe to support and train.

[KPI Discovery worksheet](https://docs.google.com/spreadsheets/d/1Tf9hcqwXySDtnm13oZ3frJdMUsuBGLFzEdV_4YoMPA8/edit#gid=1059164360)
[New Dataset Request Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=obrienjulie&labels=analytics-insights&template=analytics-internal-dataset-request.md&title=Analytics+Internal+-+New+Dataset+Request+Template)

---
## Tasks
- [ ] Define data needs
- [ ] Create BQ tables/views/dataset as needed 
- [ ] QA data

## Acceptance Criteria
- [ ] Datasets have been completed and handed off to analyst to created dashboards
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
