### ISSUE TITLE
[CST] Migrate from `react-router` to `react-router-dom`

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#50486]
## Background
We are using `react-router` V3 currently. `react-router-dom` is the new version of `react-router` and we are using v6 of that. We need to migrate from using `react-router` to `react-router-dom` as there is no longer documentation for `react-router`

## Considerations
[Primer document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/benefits-portfolio/benefits-management-tools/engineering/primers/react-router-v6-notes.md)

## Tasks
- [x] Use the `react-router-dom` version of `startApp`
- [x] Update routes to work with `react-router-dom`
- [x] Update imports from `react-router` to `react-router-dom`

## Acceptance Criteria
- [x] CST is using the `react-router-dom` version of `startApp`
- [x] Routes are updated to work with `react-router-dom`
- [x] Imports are update from `react-router` to `react-router-dom` in the CST code

**Comment by jerekshoe** [comment]
**Update (10/23):** We are beginning to wind down our migration to LH Benefits Claims API, so I'm hoping we will be able to start removing some of the duplicated component code and move forward with this effort
