### ISSUE TITLE
Procure a subdomain for Preview Environment use

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#50484]
# Description
In order to host the Preview Environment capability we will need an address that we can use in order for users to access it. This epic will contain work related to understanding and navigating the process for acquiring a long term subdomain, as well as potentially temporary solutions that may be easier to achieve in the near term.

Desired long term subdomain: 'preview.va.gov' - This subdomain will make preview environments directly routable from the public internet without requiring us to piggyback on the use of an existing subdomain by defining paths and using the revproxy.

# Tasks
- [ ] Understand and complete process to secure a long term location for hosting Preview Environments
- [ ] _Optional_ - Understand and complete the process to secure a temporary location for hosting Preview Environments

# Acceptance Criteria
- [ ] A permanent subdomain is available
- [ ] _Optional_ - A temporary subdomain is available in the interrim
