### ISSUE TITLE
Supplemental Claims | PACT Act Discovery

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#50488]
## Value Statement
**_As a_** Veteran
**_I want to_** file a PACT Act eligible claim 
**_So that_** I can receive benefits for new presumptive conditions in this category.

---
## Acceptance Criteria
The goal of this discovery is to complete the following:

- [x] We understand how PACT Act claims are processed. 
- [x] We confirm that we have all policy requirements.
- [x] We know which kinds of benefits can be filed under the PACT Act.
- [x] We know whether or not we can use the existing flash in BGS.
- [x] Lighthouse is aware of changes required on their end.
- [ ] We have validated the frontend and backend requirements.

## Tasks
- [ ] Discuss policy requirements with Alejandro M. and Matt Self
- [ ] Discuss backend with Nicholas Bastian

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Reviewed and approved by product, design, and engineering

**Comment by eileen-coforma** [comment]
Added the [research strategy](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/Research/1222-PACT-Act/research-strategy.md) we worked on into Github

**Comment by saderagsdale** [comment]
Next up: team brainstorming for recommendations. Eileen and Sade to huddle on next steps.

**Comment by saderagsdale** [comment]
Meeting with VBA and our PO today to review design and confirm we're headed in the right direction

**Comment by saderagsdale** [comment]
Still waiting for LH to send a list of questions for VBA SMEs. Sent a reminder on 1/17 and 1/18.
