### ISSUE TITLE
Document and Define the BGS "View Dependent" Endpoints

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#5048]
## Story
As an eBenefits Team member, I want to be able to define what endpoints for View Dependents are being used so I can send them to the frontend so we can connect them.

## Considerations
- There are two endpoints: `View dependents` and `Update dependents` but here we will focus on the view task
- [Link to rainbows doc](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Disability/Declare%20Dependent%20686/Discovery/bgs-sample-requests/Benefits%20Gateway%20Services%20(BGS)%20Web%20Services.doc)
- Discuss with other engineers about documentation

## Tasks
- [x] Identify the service or stack that may house the endpoint(s) for `View dependents`
- [x] Define those endpoints and discuss with other team members

## Acceptance Criteria
- [x] Document the endpoints in [GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/engineering/686-back-end-research.md) and share with team

## Note
Following up with ESCP for getting into BGS
