### ISSUE TITLE
Supplemental Claims | Prep for testing in staging

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#50493]
## Value Statement

**_As a_** Veteran
**_I want to_** file a Supplemental Claim
**_So that_** I can get disability compensation benefits.

## Background Context
We want to fully test the submission process for:
- No evidence supplemental claims
- Evidence included supplemental claims

We've tested previous submissions to their endpoint in the past, but we need to re-do those.

## Tasks
- [x] Lists the different user states we want to test
- [x] Find/prep the logins for those cases
- [x] Loop in Lighthouse and VBA teams to help with testing

## Definition of done
- [ ] All tasks complete
- [x] All tests passing

**Comment by saderagsdale** [comment]
Reached out to VBA for the names of people who will review test submissions for us.
