### ISSUE TITLE
Build and edit Download VA education letters page in Drupal

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#50494]
## Issue Description

As part of the education letters app launch, our team needs to create a static landing page in Drupal as an entry point for the tool. 

Beth reviewed this content when this work was previously started by another team so it should be close to final. The team created the page in staging and we can use that content to build the page in Drupal. 

Staging link: https://staging.va.gov/education/download-letters/

We also need to provide the product team with final content for the sign-in modal that's at the top of the page. They'll create a react widget for us to add to the page. 

Once the page is built, we'll need to put it through the collab cycle and wait to publish until the product launches.

## Tasks
- [x] Build page in Drupal from staging link
- [x] Provide product team with content for react widget
- [x] Add react widget to page
- [ ] Copyedit (Megan)
- [x] Open collab cycle ticket (Randi)

## Acceptance Criteria
- [x] Content is ready for staging review

**Comment by RLHecht** [comment]
@katherine-fung I built this in drupal. Here's the preview link: http://preview-prod.vfs.va.gov/preview?nodeId=51823

I noticed that the text is slightly different from what Beth originally supplied in ticket #37492 so I want to ask her about which version we should go with. 

You'll also need to write updated content for the sign-in widget, which will be added to the page when the product team supplies us with the code (we'll need to give them the content first). I noticed we need to bold terms and we don't usually link to them there.

**Comment by katherine-fung** [comment]
Hi @RLHecht - 

I spoke to Beth and she said she doesn't need to look at the widget content. She also confirmed that the widget should list "My HealtheVet" as a sign-in option. 

Once the tool offers other types of education letters, we'll need to ask the product team to tweak the header of the widget. 

Here's the widget text for the product team: 

[sign in widget] 

[H3] Sign in to get your VA education decision letter

Sign in with your existing **Login.gov**, **ID.me**, **DS Logon**, or **My HealtheVet** account. If you don’t have any of these accounts, you can create a free **Login.gov** or **ID.me** account now.

[Green button] Sign in or create an account

**Comment by katherine-fung** [comment]
Hi @btruongafs! Could you help us create a sign in widget for download letters tool? 

The text inside the widget is as follows: 

[H3] Sign in to get your VA education decision letter

Sign in with your existing **Login.gov**, **ID.me**, **DS Logon**, or **My HealtheVet** account. If you don’t have any of these accounts, you can create a free **Login.gov** or **ID.me** account now.

[Green button] Sign in or create an account

**Comment by katherine-fung** [comment]
Hi @btruongafs! Could you help us create a sign in widget for download letters tool? 

The text inside the widget is as follows: 

[H3] Sign in to get your VA education decision letter

Sign in with your existing **Login.gov**, **ID.me**, **DS Logon**, or **My HealtheVet** account. If you don’t have any of these accounts, you can create a free **Login.gov** or **ID.me** account now.

[Green button] Sign in or create an account

**Comment by katherine-fung** [comment]
Thanks @btruongafs, 

Here's the revised copy: 

[H3] Sign in to get your VA education decision letter

Sign in with your existing **Login.gov** or **ID.me**. If you don’t have one of these accounts, you can create a free **Login.gov** or **ID.me** account now.

[Green button] Sign in or create an account

cc @bethpottsVADEPO @RLHecht

**Comment by katherine-fung** [comment]
Hi @btruongafs - I'm sorry, I had a typo in the widget text. 

Can you please correct the letters widget to the text below? Please let me know when you see this: 

[H3] Sign in to get your VA education decision letter

Sign in with your existing **Login.gov** or **ID.me** account. If you don’t have one of these accounts, you can create a free **Login.gov** or **ID.me** account now.

[Green button] Sign in or create an account

**Comment by btruongafs** [comment]
@RLHecht @bethpottsVADEPO @katherine-fung we created the react widget. PR ready for approval at https://github.com/department-of-veterans-affairs/vets-website/pull/22999

We didn't see where the copy was available to be updated.

**Comment by btruongafs** [comment]
@RLHecht @bethpottsVADEPO @katherine-fung the PR was approved. let us know if there is anything else.

**Comment by RLHecht** [comment]
@btruongafs can you provide us with the react code so we can add the widget into our drupal page? Thanks!

**Comment by RLHecht** [comment]
@bethpottsVADEPO @katherine-fung I added the react widget to the page but because we have the alert at the top we're going to need an H2 in between the 2 components.

**Comment by katherine-fung** [comment]
Thanks @RLHecht! 

We're waiting for an update from Bobby on tweaking the widget copy to remove DS Logon and MyHealtheVet. 

I'll work on adding an H2 above the widget. 

Beth and I also discussed some other changes that I'm making to this page.

**Comment by katherine-fung** [comment]
Hi @bethpottsVADEPO, 

I'm attaching a Word doc that has edits for the content in the download letters tool. 
[Uploading... letters static page edits KF.docx]

**Comment by RLHecht** [comment]
This work is complete. We'll track the copyediting and publishing in #50499

**Comment by katherine-fung** [comment]
Hi @btruongafs, 

The widget header for this tool should not have punctuation at the end, or the words "verify" or "please." 

Please update the widget header to say the following: 

Sign in to download your VA education decision letter

**Comment by btruongafs** [comment]
@katherine-fung widget copy has been updated

**Comment by katherine-fung** [comment]
Beth and I are requesting updates to the content for the tool (outside of the static page).

**Comment by katherine-fung** [comment]
I'm closing this ticket because the widget copy on the static page is now correct. cc @RLHecht
