### ISSUE TITLE
Final copyedit and publishing of education letters landing page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#50499]
## Issue Description

Once the education letters tool launches, we need to publish the new landing page and add all entry points from the IA doc.

IA doc to follow: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/edu-inbox-p1.md

Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=51823

## Tasks
- [x] Final copyedit of static landing page (Megan)
- [x] Add content to education hub page (Katherine)
- [x] Set up menu item and url (Megan)
- [x] Publish landing page (Megan)
- [x] Set up left nav (Megan)
- [x] Copyedit and publish education hub page (Megan)

## Acceptance Criteria
- [x] New education letters landing page is live on the site

**Comment by katherine-fung** [comment]
@megzehn I added the entry point/link for the tool static page to the education hub page. Mikki [confirmed over Slack](https://app.slack.com/client/T03FECE8V/C03MP8MEPCN/thread/C03MP8MEPCN-1677706999.214469) that the link should go after the "Verify enrollment" link. 

cc @RLHecht

**Comment by RLHecht** [comment]
These pages and the left nav work are now live. Closing.
