### ISSUE TITLE
Build and edit school enrollment verification page in Drupal

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#50497]
## Issue Description

As part of the school enrollment verification app launch, our team needs to create a static landing page in Drupal as an entry point for the tool. 

The team created the page in staging and we can use that content to build the page in Drupal. This content hasn't been looked at by our team yet so we'll need to make plain language and VA.gov style updates and do a full review.

Staging link: https://staging.va.gov/education/verify-school-enrollment/

We also need to provide the product team with final content for the sign-in modal that's at the top of the page. They'll create a react widget for us to add to the page. 

Once the page is built, we'll need to put it through the collab cycle and wait to publish until the product launches.

## Tasks
- [x] Build page in Drupal from staging link (Katherine)
- [ ] Review (Laura)
- [x] Provide product team with content for react widget (Katherine/Randi)
- [x] Add react widget to page (Katherine)
- [ ] Copyedit (Megan)
- [x] Open collab cycle ticket (Randi)

## Acceptance Criteria
- [ ] Content is ready for staging review

**Comment by katherine-fung** [comment]
Hi @RLHecht , 

I spoke with Beth about this ticket today and since I've passed VEText along, I'll work on the content for the school enrollment verification page today and Monday. The plan is to meet with Beth again early next week if I need to, and to have this page ready by next Wednesday. 

In the meantime, she said she doesn't need to look at the widget text. Here's the widget text you can pass along to the product team:

[H3] Sign in to verify your school enrollments

Sign in with your existing **Login.gov**, **ID.me**, **DS Logon**, or **My HealtheVet** account. If you don’t have any of these accounts, you can create a free **Login.gov** or **ID.me** account now.

[Green button] Sign in or create an account

**Comment by katherine-fung** [comment]
Hi @bethpottsVADEPO! 

I've been working on the draft for the "Verify your school enrollment" page. Here is the draft in Drupal: http://preview-prod.vfs.va.gov/preview?nodeId=51828 

I have a few questions. 

1. The draft uses the plural of enrollment, i.e. "Verify your school enrollments." Is that accurate/intentional? I changed to the singular "enrollment" for now, but I can change it back if we need to. 

2. We'll need to confirm with the stakeholder that what education benefits people can use this tool to verify their benefits for. Is it only Post-9/11 GI Bill? Are there plans to allow people to verify other types of education benefits using this tool? 

3. The draft of this page has a section "
Verify your enrollment for other education benefits." This section lists out how to verify your enrollment for MGIB, DEA, etc. This information is already on another VA.gov page (https://www.va.gov/resources/gi-bill-wave-faqs/). 

Should we remove the info from the tool page, and replace it with a link to that other page? 

OR if we leave the information there, should we change the header to "What if I need to verify my enrollment for other education benefits?"   

4. Do we need a section that addresses "How do I verify my school enrollment?" once someone has signed in and is using the tool? Like "We'll ask you to..." in the tool. I don't think I'm able to access the tool to see what information people might need to enter.

**Comment by katherine-fung** [comment]
@bethpottsVADEPO  I futzed with this page a bit more. 

On question #3 above, I went ahead and removed that information about how people using other types of education benefits should verify their enrollment. I replaced with a link to the R&S article about how people should verify their enrollment in different programs. 

On question #4 above, I went ahead and listed other ways to verify your enrollment for Post-9/11 GI bill benefits. I don't know if we'll keep this, but if we do, we'll still need to confirm those other methods are still valid.

**Comment by katherine-fung** [comment]
Hi @bethpottsVADEPO, 

Thanks for linking me to the context around this tool in [this ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/33863)!

I've gone back into Drupal and made some changes to the static page. 

http://preview-prod.vfs.va.gov/preview?nodeId=51828 

1. After seeing the prototype of the tool and seeing that it's possible to verify enrollment at more than one institution, I changed "enrollment" back to the plural "enrollments" throughout the page. 

2 & 3. I see now that the tool is for verifying enrollment for Post-9/11 GI Bill benefits only. But per Mikki, we should provide an entry point to WAVE for MGIB verification, and info about verifying for other edu benefits. I put this information back in. 

4. I don't know what the alternatives are to using the online tool to verify for Post-9/11 GI Bill. If the other ways still exist (text, email, phone), we'll need more info about how they'll work. Some of the info on the [legacy page](https://benefits.va.gov/gibill/isaksonroe/verification_of_enrollment.asp) may not be accurate once the online tool launches. i.e. will you still automatically get a text to opt-in to verification by text? 

5. I added an H3 "How can I use the online tool?" section under the widget with a few details about what you can do in the tool. I'm not sure if we want to keep this.

**Comment by katherine-fung** [comment]
Hi @btruongafs! Could you help us create a sign in widget for the verify enrollment tool?

The text inside the widget is as follows:

[H3] Sign in to verify your enrollment for Post-9/11 GI Bill benefits

Sign in with your existing **Login.gov**, **ID.me**, **DS Logon**, or **My HealtheVet** account. If you don’t have any of these accounts, you can create a free **Login.gov** or **ID.me** account now.

[Green button] Sign in or create an account

**Comment by btruongafs** [comment]
@katherine-fung @bethpotts our app does not officially support DS Logon or My HealtheVet account. We need to remove that from the copy.

@RLHecht we pending more info how to develop the react widget

@TamGIBill @ericks24 @cesaresantiago

**Comment by katherine-fung** [comment]
Thanks @btruongafs, 

Here's the revised copy: 

[H3] Sign in to verify your enrollment for Post-9/11 GI Bill benefits

Sign in with your existing **Login.gov** or **ID.me**. If you don’t have one of these accounts, you can create a free **Login.gov** or **ID.me** account now.

[Green button] Sign in or create an account

cc @bethpottsVADEPO @RLHecht

**Comment by katherine-fung** [comment]
Hi @btruongafs, I'm sorry - I had a typo in the widget text. 

Can you please correct the school verification widget text to the text below? Please respond to let us know you saw this.  

[H3] Sign in to verify your enrollment for Post-9/11 GI Bill benefits

Sign in with your existing **Login.gov** or **ID.me** account. If you don’t have one of these accounts, you can create a free **Login.gov** or **ID.me** account now.

[Green button] Sign in or create an account

**Comment by bethpottsVADEPO** [comment]
@katherine-fung Things to talk with Tammy and Eddie about:
- Will all the existing enrollment verification options remain that are on your TeamSite page currently? 
- If so, are there any changes to the existing process for opt-in through text messaging? As in, will all students still automatically receive a text informing them that they've been registered to receive texts for enrollment verification? 
- If you opt out of verification by text message, do you still get automatically enrolled in email verification?
- We need to get all this info onto the new static unauth page because once it's live, we'll redirect the page on TeamSite to this new page. 

**Note:** You'll need to verify with Bobby that they corrected the widget text because I'm not sure he noticed that it was just one word that you added in when you mentioned the typo in the widget text.

**Comment by RLHecht** [comment]
@bethpottsVADEPO @katherine-fung I added the react widget to this page.

**Comment by katherine-fung** [comment]
Thanks @RLHecht! 

We're waiting for an update from Bobby on tweaking the widget copy to remove DS Logon and MyHealtheVet. 

I'll work on adding an H2 above the widget.

**Comment by katherine-fung** [comment]
@bethpottsVADEPO 

On the enrollment verification page, I made the changes we talked about in the meeting:
- removed the bullet points about what else you can do in the online tool
- tweaked the copy to say "credit or clock hours"
- moved the phone number down wherever we list it as an option

Before I email the preview link over to everyone, do you want to take a look at the section "Other ways to verify your enrollment for Post-9/11 GI Bill benefits" and see what you think of the copy I re-worked?

http://preview-prod.vfs.va.gov/preview?nodeId=51828 

I almost wonder if you know you're going to verify online from now on, do we need to give people an option to opt out of text and email? Otherwise you're getting texts every month, and if not texts, then emails every month.

**Comment by katherine-fung** [comment]
Beth made some additional tweaks to this page. We're waiting for Cinda and team to answer one question about what payments are affected by enrollment verification. 

I've also reviewed the content in the tool itself. I put my edits into 2 Word docs. I think there's one more staging review screen that I haven't been able to see - the one when you have enrollment verifications, and you have the option to verify a new month. 

enrollment verification page when user has enrollments on the page (but payments have paused) 
[https://app.zenhub.com/files/133843125/5f16101c-963a-44df-a227-ad84d4768341/download](https://app.zenhub.com/files/133843125/5f16101c-963a-44df-a227-ad84d4768341/download)

enrollment verification page when user doesn't have any enrollments 
[https://app.zenhub.com/files/133843125/13aec87e-4f16-4261-a5b2-c0d7db8d685b/download](https://app.zenhub.com/files/133843125/13aec87e-4f16-4261-a5b2-c0d7db8d685b/download)

**Comment by btruongafs** [comment]
@katherine-fung i replaced the 3rd user with another one that works. let me know if you need anything else

**Comment by btruongafs** [comment]
@katherine-fung I just noted your earlier comment (https://github.com/department-of-veterans-affairs/va.gov-team/issues/50497#issuecomment-1384421207). Are you requesting app content changes? If so, creating a separate ticket would be helpful to track.

**Comment by katherine-fung** [comment]
@btruongafs we're not requesting any changes to the content in the tool at this time. 

However, could you have your team update the header for the sign-in widget on the static page? The header ("Sign in to verify your school enrollment") should be an H3. It's currently an H1.

http://preview-prod.vfs.va.gov/preview?nodeId=51828 

(This issue came to light in the staging review for another tool - ticket #52674)

Thank you!

**Comment by btruongafs** [comment]
@katherine-fung thanks for clarifying and phew! thought we had alot more content to work on.

we'll take a look into https://github.com/department-of-veterans-affairs/va.gov-team/issues/52674
