### ISSUE TITLE
Change action link on pre-check-in intro page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#50505]
## Description

Although it doesn't have an incredibly higher bounce rate compared to other pages in pre-check-in, do an A/B test to see if the bounce rate decreases on the /introduction page by making the Get Started link more visually prominent. Right now, it uses the [action link component](https://design.va.gov/components/link/action). Look to see if there's another acceptable component to use and test. 

[Documentation of form library
](https://design.va.gov/templates/forms/)

[documentation on button in ds library
](https://design.va.gov/components/button/)

Examples

https://www.va.gov/health-care/how-to-apply/
https://www.va.gov/health-care/apply/application/introduction (Good example of two buttons) (these buttons aren't materially honest - because these buttons most often are linking to a new url.)
https://www.va.gov/disability/file-disability-claim-form-21-526ez/introduction
https://www.va.gov/education/how-to-apply/

[Pre check in intro page](https://share.goabstract.com/4f416207-0fd1-4b05-8ba5-21b6e688e75a?collectionLayerId=2b0235d1-b68a-4a9f-a8db-515c403c391c&mode=design&sha=latest)

Shawn mentioned this on a call on 12/7/2022. 

Exist numbers and % over last 30 days: 

![Screen Shot 2022-12-08 at 10.37.30 AM.png](https://images.zenhubusercontent.com/62264cddfdd7546d65710eff/ee2ed617-98d9-4180-8fc8-30105b5b8141)

## Tasks 

- [ ] Message design system team (Allison, what are other teams using right now, buttons or actions links?) to show solution and mention A/B test. Get approval to move forward without full collab cycle. What's the latest feeling from Allison on if teams are reverting back to the buttons or still using action links. 
- [ ] Create wireframe (Potentially, change the component, plus add button at the top, since other teams are often doing that too.) 
- [ ] Create wireframe that explores other options outside of the button component.
- [ ] Prepare wireframe for engineers
- [ ] Determine test plan. E.g., A/B. Add test plan info and timeline to ticket for engineers to evaluate whether feature toggle can be used, identify other concerns, etc. 

## AC

- [ ] Branch in abstract with wireframe
- [ ] Test plan documented and questions documented for engineers 
- [ ] Approval from Matt Dingee, Carol Wong, or Natalie, etc.

**Comment by loripusey** [comment]
Is this the component to which we are referring? If so, I agree we should investigate it, however, given the fact that we are now doing discovery work for a "unified" PCI & CI experience, I don't want to waste a lot of time doing A/B testing. I think if, as a team, we can agree on a better & more visible component, then we could quickly move forward with making that happen.
![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/659af693-1024-4157-b966-c5443290bb51)

**Comment by loripusey** [comment]
That being said, if UX has the capacity to very quickly get A/B testing using a prototype set up and completed then I'd be ok with that effort.

**Comment by ytsaoca** [comment]
Exemplar: [Uploading... Screen Shot 2022-12-23 at 10.44.05 AM.png]

**Comment by ytsaoca** [comment]
Exemplar: ![Screen Shot 2022-12-23 at 10.44.05 AM.png](https://images.zenhubusercontent.com/6148b41faabf78b679dbacff/2d5c2c8f-a400-4c8d-9238-dbdd8a3f8875)

**Comment by ytsaoca** [comment]
https://www.apple.com/accessibility/
![Screen Shot 2022-12-23 at 12.00.05 PM.png](https://images.zenhubusercontent.com/6148b41faabf78b679dbacff/8ec8f767-58cc-414b-aecd-71542dbaea12)

**Comment by ytsaoca** [comment]
started a [conversation](https://dsva.slack.com/archives/C01DBGX4P45/p1672254458048469) with the design system team and DK (accessibility) for feedback.

**Comment by ytsaoca** [comment]
started a [conversation](https://dsva.slack.com/archives/C01DBGX4P45/p1672254458048469) with the design system team and DK (accessibility) for feedback.

**Comment by ytsaoca** [comment]
According to Allison Christman:
The pages (Examples) that have the old buttons are going to be fixed as those pages are worked on. I know Matt has talked to accessibility and tried to push the bounds of using a link that is visually similar to a button and that idea is always turned down.


https://www.va.gov/health-care/how-to-apply/
https://www.va.gov/health-care/apply/application/introduction (Good example of two buttons) (these buttons aren't materially honest - because these buttons most often are linking to a new url.)
https://www.va.gov/disability/file-disability-claim-form-21-526ez/introduction
https://www.va.gov/education/how-to-apply/

**Comment by ytsaoca** [comment]
Recommendation for now:
We could try Allison's idea to [have two action links](https://share.goabstract.com/9ad55c9c-fc58-4242-a712-3a65457dc218?collectionLayerId=cf1015de-d115-4cb7-b4aa-101c629ee872&mode=design) instead and create a ticket to have more discussion/audit with Josh.

All options explored: https://share.goabstract.com/9ad55c9c-fc58-4242-a712-3a65457dc218

**Comment by loripusey** [comment]
I like the idea of repeating the link at the top (more visibility and letting the user know they have something to do without having to scroll down). If we feel like changing the control is problematic, I would be in favor of @ytsaoca 's idea to repeat the link at the top.

**Comment by benbrasso-agile6** [comment]
I like the action link at the top as well. And, that was also Allison's suggestion. 

@ytsaoca One question I have is, would it be better if the action link is below that first sentence? For example: 

```
Answer pre-check-in questions (h1)

Your answers will help us better prepare for your needs. 

> Start answering questions (action link)
```

The reason I think this is worth considering is because it's a good conversational structure. For example, it provides the added value to the user followed by the action we want them to take. For example, if a screen reader was used to read this page and they clicked the action link, they won't have ever understood why we want them to take action. This might be something to get some second opinions on from the rest of the UX team.

**Comment by loripusey** [comment]
@ytsaoca what needs to happen to finish up this ticket?
@benbrasso-agile6 @sarahknoppA6

**Comment by ytsaoca** [comment]
Josh's feedback:
- 2 action links is not good for screen reader users because they would hear 2 identical items if they listen to a list of links.
- He suggested to try out adding a underline and background color to improve visibility but do not make it looks like a buttun.

**UX team decision:**
Move the action link to the top of the content and do a A/B test with the current design. If bounce rate  is not improve, we would like to explore more link UI design.

New mockups:
https://share.goabstract.com/1030e909-2693-4afc-b5b3-b4ee2211089c

**Comment by ytsaoca** [comment]
Josh's feedback:
- 2 action links is not good for screen reader users because they would hear 2 identical items if they listen to a list of links.
- He suggested to try out adding a underline and background color to improve visibility but do not make it looks like a buttun.

**UX team decision:**
Move the action link to the top of the content and do a A/B test with the current design. If bounce rate  is not improve, we would like to explore more link UI design.

New mockups:
https://share.goabstract.com/1030e909-2693-4afc-b5b3-b4ee2211089c

**Comment by benbrasso-agile6** [comment]
Looks nice! Good work and glad you explored the different options.

@brianseek @acrollet @loripusey this is a new option for our pre check in intro page to see if we can impact/increase the click through rate to the demographics page. We will want to have this is a feature toggle in order to do a slow rollout and check the data in GA. I suppose this also means that we'll need a way to have a unique GA event for this version vs. the current version. I.e., where the only change is the positioning of the action link. We'll probably need to stub out some tickets when we're ready. I can help, but will be next week. 

@ytsaoca Do you think we should make the action link text more natural language vs. generic text? Although, I guess if we changed the text, it would no longer be a straightforward A/B test since the link text in production is "Start answering questions." Maybe our next A/B test after this can be testing two versions of the link text :) 

[Content considerations around natural vs. generic](https://design.va.gov/components/link/#content-considerations)

**Comment by acrollet** [comment]
> We will want to have this is a feature toggle in order to do a slow rollout and check the data in GA. I suppose this also means that we'll need a way to have a unique GA event for this version vs. the current version. I.e., where the only change is the positioning of the action link.

I think this should be relatively straightforward.

**Comment by loripusey** [comment]
Created new [epic ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52054)to track the work

**Comment by benbrasso-agile6** [comment]
Thanks!
