### ISSUE TITLE
Content updates in sketch and abstract

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#50502]
## Description

Get Abstract and Sketch updated to be able to use screenshots for product guides, when needed. 

## Tasks

- [x] Co-work with Zach to get familiar with Sketch. Prepare for where to make changes in Sketch and creating branches in Check In and Pre Check In. 
- [x] Make content updates. (No need for full audit at this time, but focus on small changes.) Includes, add tagalog into language switcher, and remove the < > characters that aren't used in production. 
- [ ] Work with Zach to merge branches to master (including Check In and Pre Check In)
- [ ] Validate the master branch
- [ ] Work with Zach to make sure Sketch prototypes are updated and action links work correctly. [Sketch prototypes for production are here. ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin#production-wireframes-in-va-sketch-cloud)

## AC

- [ ] Validate work in abstract and sketch 
- [ ] Changes are pushed to VA sketch cloud 
- [ ] Someone else in UX or product validate that abstract masters are up to date
- [ ] Someone else in UX or product validate that sketch prototypes are up to date

**Comment by loripusey** [comment]
@benbrasso-agile6 what is the intent of this ticket? does it represent ongoing work? It's in the current sprint but not in our sprint goals, we should either take it out of the backlog or break it down into chunks that can be completed in a sprint; I'd like to get away from our sprint backlog turning into a reminder list
@sarahknoppA6

**Comment by benbrasso-agile6** [comment]
That sounds fine. There were a few specific items I pointed out that should be added into master: 

> add tagalog into language switcher, and remove the < > characters that aren't used in production

In order to 

> Get Abstract and Sketch updated to be able to use screenshots for product guides, when needed
