### ISSUE TITLE
Populate Mapping Log with current data

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#50501]
## Issue Description
The PO has signed off on [this log](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2445312001/Service+Mapping+artifacts+and+Status+Log) conceptually.

It now needs to be populated with existing/past SB's and CJM's

Use cases:
- A requester of work can check in to see the state of progress of their requested work
- A potential requester can see if SDT has done similar work in the past
- A potential requester can see SDT's anticipated workload so that they can estimate when they can see a deliverable
- A PO can gauge how SDT has been producing

## Tasks
- [x] Update log w/ existing artifacts
- [x] Determine location for space, and Finalize the page
- [x] Review of readability, follow up with Naomi if info is correct

## Acceptance Criteria
- [x] All existing artifacts are reflected in log

**Comment by steel36** [comment]
Here is the existing placeholder (https://vfs.atlassian.net/wiki/spaces/SDT/pages/2090074524/Customer+Journey+Maps+and+Service+Blueprints#Mapping-Log%3A).  It seems appropriate
