### ISSUE TITLE
Final copyedit and publishing of enrollment verification tool landing page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#50500]
## Issue Description

Once the enrollment verification tool launches, we need to publish the new landing page and add all entry points from the IA doc.

Preview link of new page: http://preview-prod.vfs.va.gov/preview?nodeId=51828

IA doc to follow: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/edu-enroll-verification.md

## Tasks
- [x] Final copyedit (Megan) 
- [x] Add content to education hub page (Katherine)
- [x] Add link and teaser to View your VA payment history page (Katherine)
- [x] Set up menu item and url (Megan)
- [x] Publish landing page (Megan)
- [x] Set up left nav (Megan)
- [x] Copyedit and publish entry point pages (Megan)

## Acceptance Criteria
- [x] New enrollment verification landing page is live on the site

**Comment by katherine-fung** [comment]
@megzehn - I went ahead and updated the entry point for "Verify your school enrollment" on the education hub page. It's ready for copy edit: 

http://preview-prod.vfs.va.gov/preview?nodeId=71 

- I changed the link so it goes to the new static page for "Verify your school enrollment" 
- I changed the link summary to reflect the new page 
- I bumped the link up to the 3rd link in this section, per the IA doc

**Comment by megzehn** [comment]
Thanks, @katherine-fung! @RLHecht, I copy edited the [education hub page](http://preview-prod.vfs.va.gov/preview?nodeId=71) with this change.

**Comment by RLHecht** [comment]
Thanks, Meghan! I sent this to Tammy. I'll leave this ticket in the backlog for when we are ready to work on the rest of this when the tool launches.

**Comment by katherine-fung** [comment]
Hi @megzehn, I added the link for the enrollment verification page to the "View your VA payment history" page. The page is ready for copy edit.

Here's the preview: 

"View your VA payment history"
http://preview-prod.vfs.va.gov/preview?nodeId=714

Thank you! 

cc @RLHecht

**Comment by megzehn** [comment]
Thanks, @katherine-fung! I reviewed the changes and published nodeID=714. CC @RLHecht.

**Comment by RLHecht** [comment]
Changes are live to that last page. Closing ticket!
