### ISSUE TITLE
Deployment workflow commits to infra main

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#50503]
# Description
Once the deployment workflow has altered the manifest file, it needs to commit and push the updated file to the https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests. Early testing of this has resulted in authentication issues that prevent the bot from pushing this code. We will need to try alternate methods including: Using a different GitHub action, using the GitHub API, and triggering a third workflow in the chain.

# Tasks
- [x] Experiment with the best method to overcome our authentication issues with pushing the updated manifest to the https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests repository.
- [x] Implement the best solution.

# Acceptance Criteria
- [x] Every time this workflow runs the manifest gets updated in https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests

**Comment by CBonade** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/12366 In for review! Workflow pushes all changes without fail and made some other optimizations along the way.

**Comment by pjhill** [comment]
Merged -- hooray! The most minor of modifications for the moment, but this mechanism should do the trick when we are populating that file with real preview environment specs.
