### ISSUE TITLE
Draft a "content tip of the sprint" message for Slack

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#50510]
### Background information
Ideas:
How do we provide constant guidance via Slack?
- Provide a tip of the day/week/sprint on Slack?
Content Tip of this Sprint
- Which Slack channel? #platform-content, #platform-team, etc.
#platform-content
- Who posts it?
One person per sprint; rotation candence
- How do we measure success?
URL pageviews after the "tip" was posted
Fewer launch-blocking issues on deployment date
Comments within that post from other Platform team members

### Tasks

- [x] Pick something from the style guide
- [x] Draft a "tip of this sprint" content guidance to post on Slack, including a hyperlink to the Style Guide that talks about it
- [x] Get feedback and approval of final messaging from rest of Content Team. 

### LINK TO DRAFT
https://thesocompany.slack.com/archives/C02LYB7QXS5/p1671825588801869

**Comment by BSmolensky** [comment]
Link to DRAFT: https://thesocompany.slack.com/archives/C02LYB7QXS5/p1671825588801869
