### ISSUE TITLE
Define SLOs for Vets-API

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#50512]
## Description
Should reflect our current performance, not something we are trying to achieve.  WIll help us set alerts for when these thresholds are not met.  

## Tasks
- [x]  Determine current baseline values for our SLIs

## Acceptance Criteria
- [x] All tasks are completed

## How to configure this issue
- [ ] _Attach a Milestone_
- [x] _Story points_
- [x] _Sprint assigned if pulling into sprint_
- [x] _Epic assigned_
- [x] _Team label assigned_

**Comment by oseasmoran73** [comment]
Met with Bill recently and the following has been asked:

- [ ] Define 4-5 SLOs
  - [ ] Latency 
  - [ ] Error : Defined. See confluence notes
  - [ ] Availability
  - [ ] Puma backlog : average rate per month

**Comment by oseasmoran73** [comment]
I was reviewing the current SLO we have for "availability" and believe that this might me more along the lines of error. Given that team is out for the holidays, will resync with them when they get back

**Comment by oseasmoran73** [comment]
SLI's shifted accordingly to Bill's feedback. Posted question in internal channel regarding question above

**Comment by oseasmoran73** [comment]
@npeterson54 Removing myself from assigned given I will be working on EKS for some time

**Comment by oseasmoran73** [comment]
Reassigned self as EKS upgrade turned out shorter than expected (wahoo for perfect scenario!!)

**Comment by oseasmoran73** [comment]
Spoke to @ericboehs regarding some of the discover from Friday. Will make those modification once finalization of EKS upgrade

[Slack](https://dsva.slack.com/archives/C045C97V7N1/p1672780728711239)

**Comment by ericboehs** [comment]
Bill has started a doc for this [in Confluence](https://vfs.atlassian.net/wiki/spaces/~63618f93fc0cc7a600b041f2/pages/edit-v2/2482864365).

**Comment by oseasmoran73** [comment]
Baselines have been defined and implemented. Iterations will most likely need to occur and should have they own tickets spun up https://github.com/department-of-veterans-affairs/va.gov-team/issues/53425 https://github.com/department-of-veterans-affairs/va.gov-team/issues/53427

Documentation for them + vets api dashboard moving over to this ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/53432
