### ISSUE TITLE
Add triggering workflow to 3 repos for deployment

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#50517]
When code is pushed to `vets-website`, `content-build`, or `vets-api`, a workflow should fire off that sets two variables of `source-repo` and `source-ref` (branch) and sends them along to the workflow that starts the preview environment deployment process in the devops repo. This workflow, once created, needs to be copied to all 3 of these repositories and merged in to the main branch.

### Tasks

- [x] Develop workflow that is triggered on push that sets `source-repo` and `source-ref` and triggers the Preview Environment Deployment workflow in the devops repository.
- [ ] Add this workflow to `vets-website`, `content-build` and `vets-api` accordingly.

### Acceptance Criteria

- [x] All source repos kick off preview environment deployment workflows when code is pushed.

**Comment by CBonade** [comment]
- Vets Website has had a workflow added to it that pushes the branch and repo to devops
- Content build has had a workflow added to it that triggers the above mentioned workflow and pushes it to devops
- Have confirmed that devops receives the correct values from both of these workflows.

Vets api is all that's left!

**Comment by CBonade** [comment]
These are all complete. The vets-website and content-build ones are merged. The vets-api one is awaiting an approval here: https://github.com/department-of-veterans-affairs/vets-api/pull/11380

**Comment by pjhill** [comment]
This is awesome -- thanks so much for pushing through all the shenanigans!
