### ISSUE TITLE
Create content for Supplemental Claims react widget and place in Drupal

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#50527]
## Issue Description

The Supplemental Claims online form will have a phased rollout. So we need to create content for a react widget we will place on the static page so that users who don't have access to the online tool will see the original entry points and those who do have access will see the online option as well.

We need to provide final content in the product team's intake request so they can create the react widget. They'll then supply our team the react code to place into Drupal. 

We have to hold publishing of the page until the online tool has launched. Once the tool is at 100% we'll open another ticket to remove the react widget and place the content directly into Drupal.

## Tasks
- [x] Create content for both versions of the widget: with the online tool and without 
- [x] Copyedit (Megan)
- [x] Post final content for product team in ticket #50515 
- [x] Add react code to Supplemental Claims static page
- [x] Publish page (Megan)

## Acceptance Criteria
- [ ] Supplemental Claims static page is live with react widget

**Comment by katherine-fung** [comment]
Hi @megzehn, 

Here's the copy for the widgets for copy edit: 
[https://app.zenhub.com/files/133843125/da99b24b-8020-4ba8-bb6c-7bd9b3a27b16/download](https://app.zenhub.com/files/133843125/da99b24b-8020-4ba8-bb6c-7bd9b3a27b16/download)

**Comment by katherine-fung** [comment]
After discussing this with the team, I've updated the widget copy in Word. Each version of the page will require a widget with distinct content. 

Widget for page **with** online tool: [https://app.zenhub.com/files/133843125/0fdfddc8-4511-4985-8ac5-1aba334fba51/download](https://app.zenhub.com/files/133843125/0fdfddc8-4511-4985-8ac5-1aba334fba51/download)


Widget for page **without** online tool: 
[https://app.zenhub.com/files/133843125/78d0c675-f582-4046-86d3-b436d702882b/download](https://app.zenhub.com/files/133843125/78d0c675-f582-4046-86d3-b436d702882b/download)

**Comment by megzehn** [comment]
Thanks, Katherine! I reviewed and copy edited these pages. 

[supplementalclaim_copyedited.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10449564/supplementalclaim_copyedited.docx)
[supplementalclaims_noonlinetool_copyedited.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10449565/supplementalclaims_noonlinetool_copyedited.docx)

**Comment by megzehn** [comment]
@RLHecht, should I go ahead and drop these copy edited pages for the [product team in this ticket? ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50515)

**Comment by Mottie** [comment]
@megzehn Yes please! We need to get any changes in ASAP

**Comment by RLHecht** [comment]
We've given the product team this content. Moving this to backlog until we have the react code to add to our Drupal page.

**Comment by Mottie** [comment]
The React widget content has been updated and is available in staging. It won't be available in production until production deployment later today

**Comment by saderagsdale** [comment]
@Mottie is this one good to close?

**Comment by saderagsdale** [comment]
@RLHecht checking on this one again

**Comment by megzehn** [comment]
Hi @saderagsdale, Randi's out this week, but we published this page with the react widget last week, so I'll go ahead and close this out. 

CC @RLHecht
