### ISSUE TITLE
Create an Unauthenticated Landing Page for "View Dependents"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#5054]
## Story
As a Veteran approaching the Dependents workflow, I want an opportunity to learn more about the process and be able to login if not already and move forward with View Dependents.

## Considerations
This will be laid out by us but handed off to the **vsa-public-websites** team for login/redirect widget building in Drupal.

## Tasks
- [x] Build a mockup for **vsa-public-websites** to review and start building
- [ ] Share with Content (Peggy Gannon) for approval

## Acceptance Criteria
- [ ] The unauthenticated landing page has been prepared for **vsa-public-websites** for creation

**Comment by sporeboy** [comment]
Landing page built, initial copy in-place. XD link: https://xd.adobe.com/view/8cdfe895-c907-4662-7234-305056778b2a-faee/

**Comment by jason-gcio** [comment]
Looks great @sporeboy - I have some thoughts to consider, hopefully before content review:

**Under “Am I eligible to use this tool?”**  
- Should we link to the Rated Disabilities tool page, or would that be too scattered.

**Under “How do I add a dependent to my benefits?”**  
- The first sentence might need to replace “could” with “able to”?
- Should there be a comma after parent in that same sentence?
- Also, does that last sentence referring to finding out more need to link or refer to something?

**Under “To file a claim for additional disability compensation for a dependent parent”**  
- Should we use the term “the VA” as opposed to simply “VA”?
