### ISSUE TITLE
[FSR] BUG - Feature Flag not updating when choosing to restart form

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#50564]
## Issue Description
Feature Flags for Copay inclusion (combined fsr), and FSR Enhancements are not updating when the user exits the form, and selects "start new application" option. This is causing users to engage the 'old' experience. 

Solution:
Identified a `isStartingOver` flag the form system utilizes when "Start new application" is selected. Using that flag to update Feature Flags appropriately since the initial form data is wiped when restarting. 

---
## Tasks
- [x] Identify why the flags are not updating
- [ ] Resolve issue with flags not updating

## Acceptance Criteria
- [ ] Feature flags update appropriately when starting the application over.  
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
