### ISSUE TITLE
[FE] My VA Health care section: Bug - VAOS timezone issue

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#50561]
## Background
With the new V2 version of VAOS they are passing us the appointment time with the timezone included, however we are not showing the timezone on My VA dashboard for our end users. We need to determine why the timezone is not showing and ensure we are showing the user the proper time and timezone for them.

## Tasks
- [x] Dig into timezone issue and determine cause
- [x] Implement fix
- [x] Validate in coordination with VAOS team

## Acceptance Criteria
- [ ] Timezone and time are showing properly for users

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_
- _How can this work be validated?_ validate with VAOS team, they can confirm time/timezone is correct
