### ISSUE TITLE
Copyedit and publish 4 Community Care R&S articles

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#50573]
## Issue Description

We have 4 new Community Care articles that were built in Drupal and are now ready for copyediting. 
- [x] [Eligibility for community care outside VA](http://preview-prod.vfs.va.gov/preview?nodeId=51544)
- [x] [Getting emergency care at non-VA facilities](http://preview-prod.vfs.va.gov/preview?nodeId=51616)
- [x] [How to get community care referrals and schedule appointments](http://preview-prod.vfs.va.gov/preview?nodeId=51545)
- [x] [About our VA community care network and covered services](http://preview-prod.vfs.va.gov/preview?nodeId=51643)

Once these are copyedited, Danielle will send to stakeholders for final signoff and then we can publish once OK'ed.

## Tasks
- [x] Copyedit pages (Megan)
- [x] Send to stakeholders for approval (Danielle)
- [x] Publish pages (Megan)
- [x] Complete R&S post-publishing tasks

## Acceptance Criteria
- [x] New R&S pages are live on the site

**Comment by megzehn** [comment]
Hi @DanielleThierryUSDSVA!

Confirming that these pages have been copy edited. I have a few notes and questions: 

[Eligibility for community care outside VA](http://preview-prod.vfs.va.gov/preview?nodeId=51544)
- Heads up that Laura and I made some larger changes to the "Examples" headers to try to get them within 70 characters. Let me know if you notice any issues. 

[Getting emergency care at non-VA facilities](http://preview-prod.vfs.va.gov/preview?nodeId=51616)
- Re: this line "We must get the notification within 72 hours of when you got to the emergency department." Is there a more specific word that we could add to "got to"? Maybe "got admitted to" or something? 

[About our VA community care network and covered services](http://preview-prod.vfs.va.gov/preview?nodeId=51643)
- Do we want to keep "About our" in this H1? Is it too redundant with the categorization on the [R&S page](https://www.va.gov/resources/health-care/)?
- Just flagging that I added a line to help connect the intro with the region accordions. ("Select the region you live in to learn which third-party administrator manages the community care network for your region.") Let me know if there are any issues.

Thank you!!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @megzehn. Notes from my review: 

**Eligibility for community care outside VA**

- I added in a few bullets that were in the Word doc but missing from the Drupal page. Which tells me going forward that I should share the Word doc with you and ask you to do a check against that as well for these pages that program teams are building.
- Do H3s need to be within 70 characters? I thought that was just H2s?

**Comment by RLHecht** [comment]
With SMEs for review

**Comment by DanielleThierryUSDSVA** [comment]
@megzehn Great news! We got the go-ahead to publish these pages. I've let the community care team know we'll publish on Thursday, June 6, and then I'll work with Jenny and Kristin and the community care team to redirect the legacy pages. I'm going to move this ticket back to in progress and you and I can sync by slack to coordinate publishing.

@coforma-terry

**Comment by megzehn** [comment]
Confirming these are published! After they're live, I'll add them to our R&S docs for the post-publish steps.

**Comment by megzehn** [comment]
Moving this back to in progress until we finish redirecting the legacy pages!

**Comment by megzehn** [comment]
Since we have the epic open and the migration in progress, I think it's OK to close this one out, @strelichl!
