### ISSUE TITLE
DOMO OKR Tracking

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/va.gov-team#50575]
## Issue Description
In order to accurately track our OKRs, we need to track our DOMO and Performace dashboard views.

---
## Tasks
- [x] Add DOMO dash tracking by Quarter
- [x] Add GA pageviews to track va.gov/performance-dashboard views
- [x] Add performance dashboard views visualizations
- [x] If possible, add quarter-over-quarter comparison percentages.

## Acceptance Criteria
- [x] Have DOMO dash quarter-by-quarter visualizations been added?
- [x] Has GA pageviews been added as a data source?
- [x] Is the above data source updating properly
- [x] Have GA pageview visualizations been added?

**Comment by ianMcCullough-ob** [comment]
I added two additional sections to the internal dashboard data tracking dashboard: one looking at DOMO dash views by quarter with current Q goals and goal progress, and another with the same content but with performance dashboard views.

[Dashboard link](https://va-gov.domo.com/page/1949678928)

## DOMO Dash section
![Screen Shot 2022-12-20 at 9.51.14 AM.png](https://images.zenhubusercontent.com/5f8db741ece9322d39872b91/7e1c293b-8ea2-4c7b-b191-c3b62223abd3)

## Performance Dash section
![Screen Shot 2022-12-20 at 9.51.24 AM.png](https://images.zenhubusercontent.com/5f8db741ece9322d39872b91/4e5bc22d-6b5e-4c4e-9bd8-763da38256c1)
