### ISSUE TITLE
Remove link to legacy page from TSGLI page

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#50595]
## Issue Description
As part of life insurance migration, we're redirecting a legacy page about TSGLI retroactive benefits to our modernized TSGLI page ([see redirect ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11918)). The only change we need to make to our page is removing a link to this legacy page. 

SME Steve Fital confirmed that all needed info is already on our modernized page.

---
## Tasks
- [x] Remove link to legacy page about retroactive TSGLI (Laura)
- [x] Prepub and publish (Megan)

## Acceptance Criteria
- [ ] Link is removed from our page in preparation for redirect of legacy URL

**Comment by laurwill** [comment]
@megzehn I removed the link in Drupal (it was at the bottom of the blue feature box) — this is ready to review and publish. 

http://preview-prod.vfs.va.gov/preview?nodeId=768

**Comment by laurwill** [comment]
Update: We'll also need to remove this link from the left nav. You can go ahead and do that when you publish!
![image](https://user-images.githubusercontent.com/104158104/207152070-159091f4-b2c4-4f9d-94da-8db81fdf2f7a.png)

**Comment by megzehn** [comment]
Thanks, @laurwill! Confirming that I reviewed and published this page and removed "Retroactive benefits questionnaire" from the menu.

**Comment by RLHecht** [comment]
This work is complete. Closing ticket.
