### ISSUE TITLE
[UX] Create user flows and use cases for unified experience

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#50608]
## Tasks

- [x] Review [mural](https://app.mural.co/t/vfscie8528/m/vfscie8528/1669731782910/5095a4e5369ea68631e36d9a6cb2ae243e238ac9?sender=u83bc52d7fa73658f84f27755)
- [x] Document list of all or some of our use cases (for using the app and/or how Veterans may arrive at the app). E.g., pull from test cases from TestRail. Documenting the results, maybe in the same workspace as the user flows. 
- [x] Create user flows for those use/test cases. I.e., low-fidelity. 
- [x] Document open questions and concerns or assumptions. Hand over questions to engineers for inclusion in their engineering spike. 

## AC

- [x] Use cases are documented
- [x] User flows documented and shared with product to set up share with team 
- [x] Documented open questions and/or scope assumptions

**Comment by benbrasso-agile6** [comment]
Blocked for the moment. [Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1671118922621369)

**Comment by benbrasso-agile6** [comment]
Unblocking this. Here's how we're thinking about proceeding: 

Create happy path user flow for unified app using current authentication and rules

Create happy path user flow for unified app using brand new authentication and rules 

... in order to have a conversation/dialogue with the rest of the CIE team.

**Comment by benbrasso-agile6** [comment]
Moving into validate. User flows all set and ready for discussion tomorrow.
