### ISSUE TITLE
Create Template for Public Website Team Content Intake Process

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#5060]
### **Tasks**

- [x] Outline of things to include on Intake form Request by External Teams - @Karak888 - Estimate 1.5 hours
- [x] Get draft template into GH with proposed fields to be filled out by for FE, Content, shared resources- @Karak888 - Estimate 1 hour
- [x] Circulate Draft form to @jenniferlee-dsva, etc. for edits to fields and get feedback - @Karak888 @jenniferlee-dsva - estimate 1.5 hours
- [x] Make updates to form following review - @Karak888 Estimate - 1 

### **AC**
- [x] Draft intake form published with internal feedback incorporated

**Comment by MickinSahni** [comment]
Draft here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/public-websites-intake.md

**Comment by jenniferlee-dsva** [comment]
Hi @MickinSahni –Let’s review together at our Monday sync.  (This is the time Kara and I have usually been meeting.) I don’t actually see any  internal team feedback incorporated since the last edits I provided or with feedback/comments from Nick and Kelson. (If they said they don't need any details in the intake, then that section with internal question/note should be removed.)

**Comment by MickinSahni** [comment]
> Hi @MickinSahni –Let’s review together at our Monday sync. (This is the time Kara and I have usually been meeting.) I don’t actually see any internal team feedback incorporated since the last edits I provided or with feedback/comments from Nick and Kelson. (If they said they don't need any details in the intake, then that section with internal question/note should be removed.)

Followed up in planning, but using #5218 for any follow-up feedback to incorporate—internal and external.
