### ISSUE TITLE
[FE] My VA Health care: Bug - Appointments not showing properly

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#50601]
## Background
The VAOS team informed us that multiple Staging users are showing inaccurate health care appointment information on My VA. We seem to be pulling in appointments that have been cancelled or have already occurred rather than appointments that are upcoming. Here are some examples:

or the two users in MyVA dashboard:
[cathedris.l.mitulski@id.me](mailto:cathedris.l.mitulski@id.me) displays a cancelled appointment
[grethel.g.petryniec@id.me](mailto:grethel.g.petryniec@id.me) displays a past appointment
For the two users in VAOS app:
[cathedris.l.mitulski@id.me](mailto:cathedris.l.mitulski@id.me) shows the appointment as canceled
[grethel.g.petryniec@id.me](mailto:grethel.g.petryniec@id.me) appointment from today that occurred will be shown in the Past list the next day.

## Tasks
- [x] Determine why we are pulling in appointments this way
- [x] Implement a fix
- [x] Validate with VAOS team

## Acceptance Criteria
- [ ] We are only showing upcoming health care appointments to our users

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_
- _How can this work be validated?_ Validate with the VAOS team that we are showing appt information accurately.

**Comment by tmitchellgcio** [comment]
This is based on V2, however it's not filtering V2 data correctly. I'm going to have to pull in some of their services
