### ISSUE TITLE
Review support ticket and document next steps #50590

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#50603]
### Tasks

- [x] Review the ticket in detail: https://github.com/department-of-veterans-affairs/va.gov-team/issues/50590
- [x] Document recommendation (below)
- [x] Ask support about a tech SME to reach out to; Slack convo: https://dsva.slack.com/archives/CBU0KDSB1/p1670860983586219

**Comment by vbellissimo** [comment]
Recommendation:

Once we have a SME, ask the following:

- Do instructions exist anywhere on how to get an account to TestRail? Either on the Platform website or otherwise.
- Who can edit the TestRail logging page? If we can edit, we can do any of the following:
1. Re-word the intro paragraph to remove that they will get instructions on how to get an account.
_For example: Please visit the VA.gov Platform website to learn some best practices for working with TestRail._
2. Add a hyperlink to the existing paragraph that links them to _how_ to get an account to TestRail.
3. If the instructions do not exist on the Platform website, create them!

**Comment by jwoodman5** [comment]
@vbellissimo [This](https://depo-platform-documentation.scrollhelp.site/developer-docs/integrate-testrail-with-github) is where TestRail login screen should link to. I believe @pjhill would be able to make that update as part of the QA Standards CoP. 

However, on that linked page, there needs to be an update. The 2nd sentence under `Before You Begin` currently reads, "If you do not have a TestRail account, request help from the Testing Tools team in #vfs-platform support." It should read, "If you do not have a TestRail account, request help in #vfs-platform support." (we would be removing _request help from the Testing Tools team_)

A similar update needs to made on [this](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-project-in-testrail) page as well. Under `Before You Begin`, #1 reads "Request access to the Platform TestRail instance from the QA standards team in #vfs-platform support.". It should read, "Request access to the Platform TestRail instance in #vfs-platform support." (we would be removing _from the QA standards team_)

**Comment by pjhill** [comment]
I have updated the help page that we link to from the TestRail landing page to this [link](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-project-in-testrail) per the support request / conversation [here](https://dsva.slack.com/archives/CBU0KDSB1/p1670959525304789).
