### ISSUE TITLE
[Design] [Content] Create wireframes for unified experience

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#50616]
## Tasks

- [ ] Review outcome of [user flow decisions](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/50608)
- [ ] Draft content for most complex path + simple path (e.g., checking in for telephone appt) 
- [ ] Draft wireframes for most complex path + simple path (e.g., checking in for telephone appt) 
- [ ] Set meeting to present to team 

## AC

- [ ] Wireframes drafted and collection created in abstract
- [ ] Meeting set up to present to team

**Comment by benbrasso-agile6** [comment]
Consider using this ticket instead, which I created immediately after meeting on 12/22 - https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/51174

**Comment by benbrasso-agile6** [comment]
Closing
