### ISSUE TITLE
[FE] Update e2e testing Error page class validatePageLoaded method

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#50614]
## Description
- Update the E2E testing Error page validatePageLoaded method so that it is passed arguments that make sense given the current use cases.

## Tasks
- [ ] [FE] Remove or change the arguments passed to the method.
- [ ] Update e2e tests

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
