### ISSUE TITLE
Fill out information for Design Intent

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#50613]
## Tasks

- [x] Schedule design intent for VAOS/appt redesign
- [x] Fill out design intent in collab cycle ticket. Call out the differences from VAOS. Include information from Ciera and Peter about what Veteran testing has been done and link to it. 

## AC

- [x] Scheduled meeting with platform
- [ ] Items updated in collab cycle ticket for design intent

**Comment by benbrasso-agile6** [comment]
Done https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/50817
