### ISSUE TITLE
cleanupAmisAndEbsSnapshots Lambda monitor failing

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#50623]
## Description
`cleanupAmisAndEbsSnapshots` has triggered four times this month. History: https://dsva.pagerduty.com/incidents/Q1CX4XDTRDT443/past. It happened six months ago but I'm not sure how it was resolved.

## Background/context 
* Python script: https://github.com/department-of-veterans-affairs/devops/blob/master/utilities/lambda/cleanup/cleanup_amis_and_ebs_snapshots/cleanupAmisAndEbsSnapshots.py
* Lambda function: https://console.amazonaws-us-gov.com/lambda/home?region=us-gov-west-1#/functions/cleanupAmisAndEbsSnapshots?tab=code
* Cloudwatch Log stream for this alarm: https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252FcleanupAmisAndEbsSnapshots
  * See the log from 2022/12/12 for the failure. Search for `[ERROR]`.

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [ ] Investigate why this is alerting
- [ ] Fix the problem

## Acceptance Criteria 
- [ ] `cleanupAmisAndEbsSnapshots` is no longer alerting.

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) (operations, devops, and needs-grooming will automatically be applied as part of the template)
- [ ] Please connect to an epic (this will typically be done by the Platform Operations PM or TL)
