### ISSUE TITLE
Confirm redirects for life insurance migration

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#50620]
## Issue Description
In 2019, Mikki planned redirects for the legacy life insurance pages ([see old ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/2213)). This was before Resources and support existed, so now that we're restarting this migration work, we need to confirm whether some of the planned benefit hub pages should now live in R&S.

I created a new Sharepoint document for the redirect plans here: ​docx icon[ Life insurance redirect updates.docx](https://dvagov-my.sharepoint.com/:w:/g/personal/laura_willwerth_va_gov/EfPClmI5_dhHsZyABRzC-x8BCDj3_7hhtkj64bEm_M9o1g?e=V3Pybm)
- I added notes about moving some pages to R&S based on the placement criteria. But several of these seem like edge cases, so want to confirm
- I also added the VALife URLs (which didn't exist in 2019), and 3 other pages we link to from our left nav that didn't appear in the 2019 redirects ticket.

If there's a better way to collaborate on this than a Sharepoint doc, let me know and I can transfer!

---
## Tasks
- [ ] Post redirects document with notes about R&S placement
- [ ] Review redirect plans (Beth, Danielle, Mikki, Joni)
- [ ] Create tickets for new pages to draft based on confirmed redirect plans (Laura)
- [ ] Create redirect tickets on a rolling basis as we migrate content to new pages (Laura)

## Acceptance Criteria
- [ ] All legacy pages are redirected

**Comment by mnorthuis** [comment]
@laurwill Went through your very thorough document and added comments. I didn't have anything to contribute that's not already indicated.  One note regarding this one odd pop-up:

https://www.benefits.va.gov/INSURANCE/popups/non-payPOC.htm 

I am not sure why it was specified to redirect this to the "Convert to commercial policy" page and can't find any reference to it in old documentation.  My thought is that it was possibly linked to from the legacy convert policy page at one point and the intent was to incorporate that content onto the page.  That said, I don't know by looking at the page now if it's correct or relevant and can't find where it was originally linked to.

**Comment by DanielleThierryUSDSVA** [comment]
Just confirming that all my comments are also in this doc. Thanks, @laurwill!

**Comment by mnorthuis** [comment]
@laurwill should this one go back in the backlog for now, or is it in the plan for an upcoming sprint?

**Comment by laurwill** [comment]
Oh! This is now blocked, waiting for input from life insurance partners. I'll move it to blocked now.

**Comment by kristinoletmuskat** [comment]
Hey @laurwill , checking if this is still blocked?
