### ISSUE TITLE
Research Request - Tech Team 2 - Step 4

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#50641]
## Issue Description
A Research [Request ](https://dsva.slack.com/archives/CPCGRR7F1/p1666381261475809)was made and our team met w/ TT2 to hear out their thinking.

_From Jesse:  We’d like to gather info from VFS teams regarding their needs for platform monitoring tools. We hope the understand the use cases and how VFS teams might use Datadog for monitoring.
I’d be happy to collab with your team on technical surveys/interviews/etc to collect the info we’re interested in._ 

## Tasks
- [x] Recruitment / scheduling
- [x] Progress check-in, discuss Datadog access use case, and next steps (scheduled 1/11/23 with Jesse)
- [x] Schedule + invite TT2 and SDT to group synthesis
- [x] Prep mural board for group synthesis

## Acceptance Criteria
- [x] optimal amount of participants recruited
- [x] Interviews are scheduled
