### ISSUE TITLE
[PM] My VA Audit UX Imrovements: QA Go/No Go

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#50645]
## Background
We need to confirm that we are ready to proceed with our internal QA. 

## Tasks
- [x] Ensure feature is done
- [x] Review the feature and functionality
- [x] Complete [readiness checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/my-va-audit-improvements-QA-readiness-checklist.md) with the team

**Comment by ajakabcin** [comment]
QA go/no-go completed 2/15 at the end of sprint planning - we're ready to proceed with internal QA
