### ISSUE TITLE
[PM] My VA Audit: Submit QA Request

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#50644]
## Background
Submit formal QA request for the My VA Audit project.

## Tasks
- [x] Update Test Cases
- [ ] ~Meet with Tze (if needed)~
- [x] Submit [QA Request Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=tlei123&labels=Shared+Support+Team%2C+QA%2C+PTEMS%2C+qa-test-plan&template=ptems-qa-test-plan.md&title=%5BProduct%2FFeature%5D+PTEMS-QA+Test+Plan) for QA to occur ideally in ~sprint 4 (starts 2/15)

## Acceptance Criteria
- [x] QA Request is submitted

**Comment by Samara-Strauss** [comment]
Since we aren't running research until next sprint, QA will likely happen some time mid-February.

**Comment by ajakabcin** [comment]
Finalizing test cases. QA request submitted (#52008) - will reach out to Tze to let him know we're looking at mid Feb/sprint 4
