### ISSUE TITLE
Add OptimalWorkshop guidance to Platform Request Access to Tools page 

### ISSUE THREAD

**Issue by CherylEvans** [department-of-veterans-affairs/va.gov-team#50685]
## User Story
_As a VFS team member, I want to be made aware of OptimalWorkshop guidance directing me to request access from my team's design lead, so that I may use the tool if/when needed_

Assignee: @CherylEvans 
Peer Reviewer: @naomimarcussen 

## Description
_The Design and Research tools section of the Platform Tools page on Platform Website doesn't include any guidance for Optimal Workshop, with regard to the team's Design lead being responsible for requesting access for team members._

## Impacted Artifacts
[Request Access to tools](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-Additionalaccessforresearchersanddesigners)

## Tasks
- [x] _Add OptimalWorkshop guidance to the Request Access to tools page_
- [x] _Add specific guidance in the OptimalWorkshop section that the Design lead is responsible for providing access to this tool_
## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] _VFS team members are aware that they need to coordinate with their Design lead to gain access to OptimalWorkshop tool_

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
@naomimarcussen I hope you don't mind, but I added you as the peer reviewer for this ticket since we are both working on this.  I am ready for your review of my [draft page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2459795457/50685+-+Cheryl+Copy+of+Request+access+to+tools) whenever you have a chance.  Thanks in advance!

**Comment by CherylEvans** [comment]
Added OptimalWorkshop [guidance](https://vfs.atlassian.net/wiki/spaces/GS/pages/969605215/Request+access+to+tools) to Request access to tools page.  Once published, I will close this ticket.
