### ISSUE TITLE
Connect BE Endpoints to FE for "View Dependents"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#5069]
## Goal
As we move towards code completion, we want to ensure that the backend endpoints are connected and display user data as intended.

## Tasks
- [ ] Coordinate endpoint integration and display (with both frontend and backend)
  - [ ] Update the endpoint
  - [ ] Potentially update the data structure, use mockdata as needed
  - [ ] Create a unit test

## Acceptance Criteria
- [ ] Upon testing, a test user has their specific data displayed.

**Comment by kathleencrawford** [comment]
created PR so that FE has access to the lighthouse-bgs changes required for testing

https://github.com/department-of-veterans-affairs/vets-api/pull/3855
