### ISSUE TITLE
Onboarding new team members

### ISSUE THREAD

**Issue by elizabethkochBT** [department-of-veterans-affairs/va.gov-team#50692]
- [x] [Jay Tanner](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49409)
- [x] [Carolyn Williams](https://github.com/department-of-veterans-affairs/va.gov-team/issues/40008) 
- [x] [Ksenia Coulter](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49767)
- [x] [Carl Dickerson](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34204)
- [x] Michael Antiporta @porta-antiporta
- [x] [Anthony Levin-Decanini](https://github.com/department-of-veterans-affairs/va.gov-team/issues/51843) @alevindecanini 
- [x] [Melissa Miller](https://github.com/department-of-veterans-affairs/va.gov-team/issues/51940) @holytoastr
- [x] [Sofia Kirkman](https://app.zenhub.com/workspaces/logingov-adoption-team-632280b31e745000136a61fc/issues/gh/department-of-veterans-affairs/va.gov-team/55366)
