### ISSUE TITLE
[BE] My Health: Medical Records: Collaborate with MHV API team on FHIR progress

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#50703]
## User Story
As a Veteran, I want to be able to view my medical records information regardless of the system behind the scenes so that I can stay informed about my health

## Tasks
- [ ] [BE] Keep in contact with MHV API team on FHIR progress & documentation on what FHIR profile will include

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by rbsingleton** [comment]
Recurring touch base w/ Boomer being led by Eric. Will touch base w/ Mike Moyer to share info.

**Comment by MarciMcGuire** [comment]
Closing this issue as FHIR API work is still in progress and this team is pivoting to focus on the landing page and integration
