### ISSUE TITLE
Define minimum viable security ongoing service

### ISSUE THREAD

**Issue by raywangoctova** [department-of-veterans-affairs/va.gov-team#50710]
## LOE
Need new LOE because I changed it to Define what the service should entail

## Problem Statement 
In fall of 2022, funding for our security team expired and was not renewed. In December 2023, Thomas left OCTODE who was the security SME and hands on helping with security initiatives on Platform. 

We now have 1 FTE working on ATO and a 1/2 time resource working on security. We need to determine 1. What the minimum viable security ongoing service entails that we can do with the current staffing 2. What falls outside of that that we believe we should be doing. 

## User Impact
Much more potential for security issues on VA.gov

## Where was this problem reported?
Platform leadership escalated this, OCTODE also realizes it's an issue

## What do we not know about the problem space?
https://app.zenhub.com/workspaces/platform-security-615c86f78b52bf0014e79606/board <- we have clarity in the security and in done column of what the team has historically done. 

We know what we are contractually obligated to perform

## What (if any) research or discovery has been done?
None

## What is the acceptance criteria?

- [ ] The minimum of what we can and should accomplish each quarter/year for security with our current staffing is documented
- [ ] Everything we think is important and should be done outside of the minimum is documented and value is clear

## How should we measure success?
None -- this is mostly paperwork. Not actual engineering. 

## TODOs
- [ ] Convert this issue to an epic

**Comment by raywangoctova** [comment]
OBE since we have a very staffed security team now.
