### ISSUE TITLE
[BE] Deprecate check_in_experience_lorota_deletion_enabled Feature Flag

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#50739]
## Description
Deprecate feature flag `check_in_experience_lorota_deletion_enabled` 

## Tasks
- [ ] [BE] Remove feature flag `check_in_experience_lorota_deletion_enabled`
- [ ] [BE] Confirm `check_in_experience_lorota_deletion_enabled` not used in Front end
- [ ] [BE] Remove feature flag code reference

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by kanchanasuriya** [comment]
Duplicate
