### ISSUE TITLE
[FE] Payment info v2: Documentation review/updates

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#50737]
## Background
Post launch of My VA payments v2 we need to review all of our design, FE and technical documentation to make sure everything is up to date and reflects the current implementation of My VA. This is a joint effort from all team members, though we have specific tasks for each of us.

## Tasks
- [x] Review technical documentation and diagrams (linked in Resources section)
- [x] Update/create documentation as needed
- [x] Review with PMs/PO

## Resources
- Create a "Frontend" section in the [feature outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/payment-history#backend) providing overview of technical frontend (similar to what you did for [Onsite Notifications](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications#frontend))

**Comment by tmitchellgcio** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/README.md

**Comment by ajakabcin** [comment]
Thanks @tmitchellgcio ! I moved the section up just above Backend. Looks great 👍 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/README.md#frontend
