### ISSUE TITLE
Publish 3 Foreign Medical Program pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#50748]
## Issue Description

Danielle sent stakeholders the previews for the 3 FMP pages we worked on in ticket #42044. 

Since ~2~1 of these are benefit detail pages, we'll need to take them through the collab cycle and do a staging review before publishing. We should wait for stakeholder feedback and make and content changes before opening the collab cycle ticket.

IA documentation for new pages: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/migration-comm-care.md

**New static page url:** www.va.gov/health-care/foreign-medical-program
**Hub landing page and left nav:** Within the "Get benefits" spoke, place after "After you apply" and before "Family and caregiver benefits"

New pages to publish:
- [Foreign Medical Program (FMP)](http://preview-prod.vfs.va.gov/preview?nodeId=50826)
- [Getting care through the Foreign Medical Program](http://preview-prod.vfs.va.gov/preview?nodeId=50969)
- [How to file a VA Foreign Medical Program claim](http://preview-prod.vfs.va.gov/preview?nodeId=49685)

Updated page to publish:
- VA health care hub landing page

## Tasks
- [ ] Incorporate stakeholder feedback
- [x] Open collab cycle ticket for ~2~ 1 static pages (Randi)
- [ ] Open redirect ticket (Randi)
- [ ] Add entry point to benefit hub page
- [ ] Final copyedit (Megan)
- [ ] Set up url for benefit page and left nav order
- [ ] Publish (Megan)
- [ ] Follow post-publishing checklist for R&S articles

## Acceptance Criteria
- [ ] 3 new pages are live on the site
- [ ] Hub landing page changes are live

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht @laurwill We have SME approval for these pages and can go to staging review. I did notice that we need to fix some of the aria links on some phone numbers...I think @megzehn had noted that we needed to follow up on those though because they're numbers outside the U.S.

**Comment by megzehn** [comment]
Thanks for flagging that, @DanielleThierryUSDSVA!

Noting that I fixed the aria links on this page, based on the feedback from the accessibility channel:
[How to file a VA Foreign Medical Program claim](http://preview-prod.vfs.va.gov/preview?nodeId=49685)

And I reviewed these 2 pages as well for aria links:
[Getting care through the Foreign Medical Program](http://preview-prod.vfs.va.gov/preview?nodeId=50969) 
[Foreign Medical Program (FMP)](http://preview-prod.vfs.va.gov/preview?nodeId=50826)

**Comment by mnorthuis** [comment]
Hi all, final IA direction for the FMP page is documented in the IA ticket: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/gh/department-of-veterans-affairs/va.gov-team/52096

**Comment by RLHecht** [comment]
Thanks, Mikki! @megzehn I added the IA info to the top of this ticket. We'll need to set the url and place it in the left nav when we publish the new page.

@mnorthuis Question on the IA documentation: Since we have 2 R&S pages I want to confirm where the second community care page is redirecting to: the "How to file a VA Foreign Medical Program claim" or "Getting care through the Foreign Medical Program." I think the first but want to confirm before I set up the redirect ticket.

**Comment by DanielleThierryUSDSVA** [comment]
Well, after much delay due to additional layers of approval, we are ready to launch these 3 pages - yay!


[Foreign Medical Program main page on VA.gov](https://preview-prod.vfs.va.gov/preview?nodeId=50826)
[How to file a VA Foreign Medical Program claim]http://preview-prod.vfs.va.gov/preview?nodeId=49685)
[Getting care through the Foreign Medical Program]https://preview-prod.vfs.va.gov/preview?nodeId=50969)

@megzehn These are the pages I mentioned yesterday. They need an errors-and-omissions-only review and then we need to add the URLs and menu links to the 2 pages that live in the health care hub per IA documentation, as Randi noted above. Feel

**Comment by laurwill** [comment]
Closing this ticket — these pages are live
