### ISSUE TITLE
[Design, PM] Payment Info: Review Content/IA tickets from staging review

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#50744]
## Background
With payment info v2 now live we need to look back at the tickets in our backlog from staging review of our mvp to see if there are any tickets that can now be closed. Combined effort with PMs.

## Tasks
- [x] Review the open Content/IA Strategy tickets linked in the [staging review ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/gh/department-of-veterans-affairs/va.gov-team/38376)
- [x] Determine how to proceed: close, leave in backlog, bring forward for prioritization

## Acceptance Criteria
- [x] Tickets are reviewed

## Resources
In case there are issues with zenhub/GH and that integration linking those open tickets here as well:
- [x] #39480
- [x] #39470
- [x] #39476
- [x] #39475 
- [x] #39477
