### ISSUE TITLE
[PM, Design, FE] My VA Audit UX Improvements: Internal testing

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#50743]
## Background
In preparation for QA we need to some internal testing/validation and "kicking of the tires" on all the work done on My VA with the UX improvements post-audit.

## Tasks
- [x] Run through [test case documentation](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myvaaudit.md#Education-and-training-section) to ensure all basic cases are functioning properly
- [x] Test additional edge case scenarios - look for anomalies or strange behavior that we may have missed 
- [x] Share findings with PMs

## Acceptance Criteria
- [x] Test cases have been reviewed and tested as well as edge case scenarios
