### ISSUE TITLE
[BE] Deprecate feature flag check_in_experience_lorota_security_updates_enabled

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#50742]
## Description
Deprecate feature flag `check_in_experience_lorota_security_updates_enabled` 

## Tasks
- [ ] [BE] Remove feature flag `check_in_experience_lorota_security_updates_enabled`
- [ ] [BE] Confirm `check_in_experience_lorota_security_updates_enabled` not used in Front end
- [ ] [BE] Remove feature flag code reference

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by kanchanasuriya** [comment]
Duplicate
