### ISSUE TITLE
CST: Add mock for new scenario

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#50755]
## Background
We have seen a scenario that we were unaware of in production. It is possible for a claim to be "open", but have the decisionLetterSent flag set to `true`. We did not account for this scenario when we were designing the DDL feature and this would be a good scenario to add a new mock for so that we can simulate it locally later.

## Context
When a veteran files a claim that includes multiple issues, it is possible that some of the issues get decided on before others, effectively leaving the claim in an "open" state, but with a decision letter ready for them to view.

## Relevant info
[Original Thread (Reddit)](https://www.reddit.com/r/VeteransBenefits/comments/zlfwif/status_is_in_review_of_evidence_but_i_checked)

![image](https://user-images.githubusercontent.com/13838621/207691074-86eb369b-6d5e-4c81-be2e-6404b690d5a2.png)

## Technical considerations
We should create a new mock for this scenario:
* Mock JSON files are in `src/applications/claims-status/tests/e2e/fixtures/mocks/mock-api/claims`
* Copy one of the other claims, but make sure to update the `data.id` field. This is normally a number, but we use human-readable strings here to provide clarity around what situation the claim is meant to simulate

## Tasks
- [x] Add a new mock to `src/applications/claims-status/tests/e2e/fixtures/mocks/mock-api/claims`
- [x] Name the file `phase3-decision-mailed.json`
- [x] Update the `data.id` attribute to be `phase3-decision-mailed`
- [x] Update the `claims-list.json` JSON file to include the new mock
- [x] Update any other fields needed to simulate the scenario described above

## Acceptance Criteria
- [x] A new mock file has been created
- [ ] The new mock accurately simulates the scenario described in the `Background` section

**Comment by samcoforma** [comment]
@jerekshoe it seems like you did most of this before I got to it, but here it the PR for it: https://github.com/department-of-veterans-affairs/vets-website/pull/22952

Is there anything I'm missing to recreate this scenario other than adding it to claims-list and setting the "decisionLetterSent" flag to true (which I did)?

**Comment by jerekshoe** [comment]
Yes, there is one other JSON file that needs to be updated, I’ll let you guess what it is. Hint: All I did in my previous PR was copy the `phase3.json` file, I didn’t make any modifications to the copy

**Comment by samcoforma** [comment]
@jerekshoe well, that's odd, because it looks updated: https://github.com/department-of-veterans-affairs/vets-website/blob/cst-mock-for-new-claim-scenario/src/applications/claims-status/tests/e2e/fixtures/mocks/mock-api/claims/phase3-decision-mailed.json#L15

**Comment by jerekshoe** [comment]
Well darn, I thought I switched it back to false. Fine, you caught me. That should be all the changes you need then

**Comment by samcoforma** [comment]
![image](https://user-images.githubusercontent.com/105806934/208184108-c52617ab-77e8-44d3-a0d8-c077b99efae3.png)

https://github.com/department-of-veterans-affairs/vets-api/pull/11368

@kjduensing can you checkout branch `cst-dld-dated-filenames` and confirm you see the same thing that's in the screenshot above?

**Comment by samcoforma** [comment]
![image](https://user-images.githubusercontent.com/105806934/208184917-8d79d18b-3222-472f-a30c-f7f3517d07af.png)


[cst-mock-for-new-claim-scenario](https://github.com/department-of-veterans-affairs/vets-website/tree/cst-mock-for-new-claim-scenario)

@kjduensing can you pull branch `cst-mock-for-new-claim-scenario` and confirm that you see what's in the screenshot above?
