### ISSUE TITLE
Create workflow that purges old PE

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#50769]
## Issue Description
Preview environments for which the branch has been deleted need to be decommissioned. Use the method defined in the [research ticket](https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/52451) to decommission unneeded Preview Environments.

---
## Tasks
- [x] Create the workflow(s) where required
- [x] Verify the workflow runs when a branch is deleted, identifies preview environments related to the deleted branch, and decommissions the preview environment

## Acceptance Criteria
- [x] A GitHub Actions workflow has been created to detect preview environments that should be decommissioned and decommission them

**Comment by CBonade** [comment]
The portion of the workflow that deletes values files when a branch is deleted has been completed.

Next step will be the job to clean up based on an expiry time.

**Comment by CBonade** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/12522 Second portion of the workflow is written, however I need to merge in some test data to be able to test that it works properly. This merge is awaiting approval. Moving on to anther ticket while I wait.

**Comment by CBonade** [comment]
vets-website portion of this is done and verified working correctly. Will be copying this out to the other repositories next. Vets-website portion is also awaiting PR approval.

**Comment by CBonade** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/23297 vets-website PR
https://github.com/department-of-veterans-affairs/content-build/pull/1470 content-build PR
https://github.com/department-of-veterans-affairs/vets-api/pull/11756 vets-api PR

These 3 PRs are not yet approved, but satisfy our cleanup job requirements for all preview environments. Additionally as part of this effort, multiple commits were merged into the devops repository.

As the complexity of this expanded as it went along, going to bump up the story estimate accordingly.

**Comment by CBonade** [comment]
PRs are merged! Good to go here

**Comment by pjhill** [comment]
Heck yes, awesome work on this! It's great to have this in place for MVP.
