### ISSUE TITLE
[Monitoring] Datadog for VFS Teams (Read-Only access): Release Plan

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#50774]
## Description
This document captures the release plan for providing VFS teams with read-only access to Datadog. 

## Goal 
The goal is to promote a straightforward process VFS teams can use to onboard and use the tool. 

### Overview 

- Changes will be communicated through recommended channels and processes 
- Users will be invited to begin using the tool  
  - DOTS will provision Okta/Datadog accounts
  - Platform Tech Support Team will verify that the user has access and is assigned read-only privileges in Datadog 
- Tools, resources, and documentation will be made available through the VA.Gov Platform Website 
- Documentation (user-facing) will include instructions, guidance, recommendations, and best practices
- There will be a feedback loop for VFS teams to suggest updates to documentation 
- Documentation (operational) will be updated for Platform personnel with instructions needed to support 

## Acceptance Criteria 
- [x] Datadog is listed as an available tool on the Platform Website - #51457 
- [x] Documentation is published on the Platform Website related to the following topics: 
  - [x] How to request access to Datadog - #51509 
  - [x] How to log in to Datadog and view resources - ie _"Welcome, here's what to expect..."_ #51511
  - [x] A list of available Platform Dashboards - #52863
- [x] The change is communicated to VFS users following the [Change Communication Plan](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2317647898/Change+Communication+Plan) 
  - [x] #51581
  - [x] #53670
  - [x] #53672
- [x] The launch is announced in Team of Teams #51710
- [x] The Platform Support Team has the info needed to support VFS teams w/ Datadog requests #51709
  - [x] The 'Offboarding Request' template is updated to include removing VFS team members from Datadog #51701
  - [x] The 'Offboarding Request' template is updated to include removing VFS team members from Okta #51561
  - [x] VFS Teams know how and where to request support #51705
  - [x] VFS Teams know where to submit feedback for documentation #51706
  - [x] VFS Teams know where to submit feedback for the tool #51707

**Comment by jhouse-solvd** [comment]
@mchelen-gov & @ph-One - Please review the acceptance criteria and comment on this issue with feedback or changes.

**Comment by mchelen-gov** [comment]
@jhouse-solvd This is looking good! The one other thing is addition to offboarding ticket.

**Comment by jhouse-solvd** [comment]
> @jhouse-solvd This is looking good! The one other thing is addition to offboarding ticket.

Added to overview and AC above.

**Comment by jhouse-solvd** [comment]
@jwoodman5 - Roping you in on this discussion. 

We're discussing a read-only release of Datadog to VFS teams in January.

**Comment by jhouse-solvd** [comment]
From a conversation w/ Platform Tech Team 2: We might want to consult w/ the Platform Tech Support Team before beginning to work on this issue. 

- Jesse can discuss this w/ Platform Support to gauge readiness on their part.

**Comment by jhouse-solvd** [comment]
With the transition of Datadog ownership from DOTS to ECC, we may need to re-evaluate some of these steps, processes, and documentation.

**Comment by jhouse-solvd** [comment]
Things that are top of mind for us regarding publishing docs to the platform website: 
- this can be a collaborative affair along w/ the platform content team 
- we need to put documentation on the platform website in the right place 
- publishing process: put docs draft space, then platform content will review, then publish according to schedule
- if we have any recommendations as to where it should live (ie IA), please let the platform content team know
- changes are typically published M-Th by EOD 
_- Note: something to take a look at for : [Platform Content Orientation Takeaway](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2502852652/Platform+content+orientation+takeaway)_. This has some great info on publishing workflow, style guides, etc. 

The high-level plan is as follows: 
- have docs in draft space by 2/14
- respond to feedback 2/14-2/20
- publish 2/20 EOD 

cc: @vbellissimo @laucon

**Comment by jhouse-solvd** [comment]
Docs have been copied to the Platform website drafts space in Confluence in preparation for publishing. 

See the [discussion thread in the Platform Content channel in DSVA Slack for more info](https://dsva.slack.com/archives/CL181NRJQ/p1676335996677379?thread_ts=1676304349.700119&cid=CL181NRJQ). 

Pending any feedback or recommended changes, we plan to have the documentation published by EOD on Monday, February 20, 2023.

**Comment by jhouse-solvd** [comment]
Email communication was sent to DOTS on 2/14 regarding bulk invites. We're coordinating with DOTS to ensure we're set for the upcoming release next Tuesday. I'll be sure to follow up to share additional info from that conversation as soon as I have it.

**Comment by jhouse-solvd** [comment]
DOTS responded and said to send over the list in XLS/CSV w/ the following info: 

- First name
- Last name
- Email address 

I'm planning to do that today.

**Comment by jhouse-solvd** [comment]
The acceptance criteria have been met and all associated issues have been closed. 

This epic can be closed.
