### ISSUE TITLE
Determine method for reporting deployment success/failure and update status

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#50770]
## Issue Description
Users need to understand the status of the deployment of their preview environment. We will update the status of the deployment in the relevant pull request. Statuses should be "In Progress", "Deployed", and "Decommissioned".

Example of deployment status widget in PR:
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/08f3b56c-881e-43c7-b7a2-bf8676c5790a)

---
## Tasks
- [x] Determine how to update the pull request with the status of the deployment from EKS / ArgoCD.
- [x] Is this possible? -- When the workflow reached the point where the deployment kicks off, update the pull request deployment status widget with the "In progress" status
- [x] Is this possible? -- When the workflow fails, update the pull request deployment status widget with the "Failed" status
- [x] Is this possible? -- When the workflow succeeds, update the pull request deployment status widget with the "Success" status
- [x] Each possible status is ingested into BigQuery along with the workflow ID and the triggering pull request ID

## Acceptance Criteria
- [ ] A description of the method to update the deployment status of a preview environment in the pull request is available in the [Discovery section](https://vfs.atlassian.net/wiki/spaces/TT4/pages/2396323867/Discovery) of TT4 Confluence
- [ ] A description of the method to warehouse deployment statuses in BigQuery for subsequent analysis is available in the [Discovery section](https://vfs.atlassian.net/wiki/spaces/TT4/pages/2396323867/Discovery) of TT4 Confluence

**Comment by CBonade** [comment]
https://vfs.atlassian.net/wiki/spaces/TT4/pages/2529821652/Updating+Deployments Page that covers these items. I don't have a definitive answer on ArgoCD's ability to communicate backwards with GitHub actions as my research was not able to locate this. I've put an inquiry out with devops, however, have not yet heard back.
