### ISSUE TITLE
Update GitHub Actions Workflow files to address recently deprecated commands

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#50790]
## Issue Description
GitHub announced that they're [deprecating some GitHub Actions commands](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/). It's important that vets-api stays update to date with GitHub Actions api.

---
## Tasks
- [ ] Review all GitHub Actions files in vets-api and update all deprecated commands.

## Acceptance Criteria
- [ ] All vets-api GitHub Actions files don't contain any deprecated commands.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by holdenhinkle** [comment]
Related Slack thread - https://dsva.slack.com/archives/C04CYC4LMU6/p1671032891648409

**Comment by rmtolmach** [comment]
- Done in https://github.com/department-of-veterans-affairs/va.gov-team/issues/55037
