### ISSUE TITLE
Overwrite Existing PE Spec for a Branch

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#50795]
# Description
In order to maintain a 1:1 relationship between a branch in a monitored repository and the corresponding preview environment, we need to ensure that the preview environment specification is maintained in a single `values` file using a naming scheme that incorporates the source repository and the branch name.

# Tasks
- [x] Update `devops` repository deployment workflow to write PE specs to a `values` file named after the source repository and the sanitized branch name
- [x] Configure the `devops` workflow to overwrite the singular `values` file when a change is pushed to the corresponding feature branch

# Acceptance Criteria
- [x] When users push code to a feature branch, the preview environment redeploys to replace the existing preview environment for the feature branch

**Comment by pjhill** [comment]
The details of this ticket will need to change once we have finalized the implementation for the `deployment.yaml`. Are we looping a set of values? Are we reading in one `values.yaml` per PE? Etc.

**Comment by pjhill** [comment]
Updated the body of the ticket to reflect the updated method for pushing the PE spec and deploying.

**Comment by CBonade** [comment]
I've confirmed this is working this way. The file, if coming from the same repo/branch combo, is overwritten with a new file containing up-to-date information and the deploy workflow runs again.

**Comment by pjhill** [comment]
Once we have image building, storage, and use down then we'll need to re-test this functionality to be sure that the overwritten values files are correctly re-read and used. That said, we are good for now!
