### ISSUE TITLE
DDL: Update `va-alert` copy

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#50808]
## Background
The copy inside the `va-alert` that shows in the UI on a closed claim with `decisionLetterSent` set to true needs to be updated.

## Screenshots
<details><summary>va.gov</summary>

![Screen Shot 2022-12-14 at 2 30 46 PM](https://user-images.githubusercontent.com/13838621/207940709-5e17a533-95e0-479e-b652-eaad0e0db22b.png)
</details>

<details><summary>Mockup</summary>

![Screen Shot 2022-12-14 at 2 32 47 PM](https://user-images.githubusercontent.com/13838621/207940758-5dd9a7ef-bf96-441e-b4f7-ac4807913845.png)
</details>

## Considerations
The component that needs to be updates is located at: `src/applications/claims-status/components/ClaimsDecision.jsx`

## Tasks
- [x] Update copy in `va-alert`

## Acceptance Criteria
- [x] Copy matches mockup
- [x] PR has been created / requested for merging

**Comment by jerekshoe** [comment]
@kjduensing I would suggest doing this one before the testing one btw

**Comment by jerekshoe** [comment]
@samcoforma Is there a PR for this ready to be reviewed?
