### ISSUE TITLE
DESIGN | Profile | Update Account security content

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#50801]
## Background

Danielle Thierry provided some content updates for the Account security section. Her updates are based on the [new proposed design](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/v/dGy30b/a/DPkdo1q) (using the process list), but should be updated on/adapted to [all screens for both the new and current designs](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc) (new designs will not go into production for a while). Both desktop and mobile screens need to be updated.

#### In verify identity modal:
- **Header:** Change "view" to "access"

- **1st sentence:** Change the hyphens to em dashes and close up the spaces around them so it reads: you—and not someone pretending to be you—before

- **We can make the last sentences 2 shorter ones:** 

> This helps us keep your information safe. It helps us prevent fraud and identity theft.

#### In sign in information section:
- **Header:** Add hyphen in Sign-in

- **1st sentence:** Add hyphen in Sign-in

- **1st sentence:** Change "view" to "access"

#### Account setup section:

- **Step 1:** Change "view" to "access"

- **Step 2:** Change to:

> **Add multifactor authentication**
> Add an extra layer of protection called multifactor authentication (or 2-factor authentication). This helps to make sure only you can access your account—even if someone gets your password.

## Tasks
- [x] Update content in current and new (proposed) Account security mockups (both Desktop and Mobile
- [x] Validate with PM and PO

## Acceptance Criteria

- [x] Content updated on desktop and mobile mockups 
- [x] Validated with PM and PO

**Comment by Samara-Strauss** [comment]
This will likely require a frontend ticket to update the account security updates Adam is working on in sprint 2.

**Comment by andaleliz** [comment]
@Samara-Strauss and @BerniXiongA6 (in lieu of a PM, per the AC), the content has been updated - you can review the screens to validate if you'd like:
- [Mobile](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/p/E79E0419-8D9A-4CF2-A052-EEBA8274E418/canvas)
- [Desktop](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc)

Once it's validated, please feel free to close it out, since I'll be gone all next week. Thanks!

**Comment by Samara-Strauss** [comment]
Looks good to me! @BerniXiongA6 -- will you please create a frontend implementation ticket for this work, and link that ticket here? I will wait to close this ticket until the frontend ticket has been created.

**Comment by BerniXiongA6** [comment]
@Samara-Strauss Ticket #53574 has been created for FE implementation -- labeled "needs grooming" to further refine the ticket. Thanks!

**Comment by Samara-Strauss** [comment]
Great, thank you!
