### ISSUE TITLE
Search parameters determined by user interaction with map

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#5081]
## User Story:
As a Veteran, I need to change my search parameters using the map so that I can find a facility in the area I specify.

Specific use case: Veteran has performed a search which legitimately resulted in no results. Want to enable the ability for the Veteran to change search parameters and search again. 

## Questions
- Do we have a default zoom level now for the rest of the locator options?
- What are our different zoom levels and, if we queried PPMS for each of those, what would the response look like speed-wise?
- What are the most common PPMS categories searched on?
- How frequently/with what categories could we assume a user to encounter null results requiring the veteran to change parameters? (What's the best way to research this?) 
- Can we check the service category data as one measure and perhaps a litmus test on a few areas of the country?
- What does this (large/max) zoom level look like to the user?
- What is a user's expectation on mobile for search radius/behavior?

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] First thing we need to do - x hour(s) - Owner
- [ ] Second thing we need to do - y hour(s) - Owner
- [ ] Third thing we need to do - z hour(s) - Owner
- [ ] etc

## Acceptance Criteria:
[ ] Map does not automatically zoom out to find facilities
[ ] The user can interact with the map to change search area.
[ ] The user is required to trigger new search after adjusting map ("Search here" button or similar)
[ ] Search results reflect new search parameters
[ ] User is made aware of option to change parameters, interact with map, etc. 

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Removing the User research block. @arickalewis1 included the following [recommendations](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/FL-Search-march2020/research-findings.md) related to this issue:

> Add “search this area” functionality to map
> If user moves map, require them to re-search

**Comment by mmiddaugh** [comment]
This issue is resolved by our recent map enhancement release
