### ISSUE TITLE
Create Address Component & Implement directions link to facilities 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#50825]
## Description 

In many apps across VA health, facilities often include a directions that, which populates the address in Google for directions. Here is an example on public web: 

https://www.va.gov/maryland-health-care/locations/baltimore-va-clinic/

The VAOS team has implemented this feature as follows: 

> VAOS is pulling the facility from the API response and populating the address in Google for the directions. 

```
<NewTabAnchor
        href={`https://maps.google.com?saddr=Current+Location&daddr=${address}`}
        aria-label={`Directions to ${location.name ||
          location.providerPractice}`}
      >
        Directions
</NewTabAnchor>
```

Here is a [slack thread](https://dsva.slack.com/archives/CMNQT72LX/p1671056347710829) to continue this conversation with VAOS, as needed. 

Facilities API example: https://developer.va.gov/explore/facilities/docs/facilities?version=current
## Tasks

- [ ]

## AC
- [ ] Displays Address
- [ ] Conditionally displays directions link
- [ ] Check with the CMS team to see if they do additional validation with the address/directions link- should we incorporate that?
- [ ] update mocks
- [ ] add unit tests

**Comment by brianseek** [comment]
This work is merged. Closing this ticket since it will get validated with the rest of the VAOS work.
