### ISSUE TITLE
Left nav, copyediting, and publishing work for TOE - HOLD TO PUBLISH UNTIL DAY OF LAUNCH

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#50830]
## Issue Description

When the new authenticated TOE tool launches, we need to do a final copy edit and publish the new static landing page along with updates to existing pages. We'll also need to add entry points to the left nav. 

Final copyedit:
- [x] [New static landing page](http://preview-prod.vfs.va.gov/preview?nodeId=44698 )
- [x] Updated [Transfer your Post-9/11 GI Bill benefits](https://www.va.gov/education/transfer-post-9-11-gi-bill-benefits/)
- [x] Updated [VA education benefits for survivors and dependents](https://www.va.gov/education/survivor-dependent-benefits/) (We added a link to the new TOE page)
- [x] Updated [Find a form](https://www.va.gov/find-forms/about-form-22-1990e/) page

Publish:
- [x] [New static landing page](http://preview-prod.vfs.va.gov/preview?nodeId=44698 )
- [x] Updated [VA education benefits for survivors and dependents](https://www.va.gov/education/survivor-dependent-benefits/)
- [x] Updated [Transfer your Post-9/11 GI Bill benefits](https://www.va.gov/education/transfer-post-9-11-gi-bill-benefits/)
- [x] Updated [Find a form](https://www.va.gov/find-forms/about-form-22-1990e/) page

**Left nav work:**

Order of "Survivor and dependent benefits" section should be:

- Dependents education assistance (DEA)
- Fry Scholarship
- [Transferred education benefits for family members](www.va.gov/education/survivor-dependent-benefits/transferred-benefits/)
- [Apply for dependent benefits](www.va.gov/education/apply-for-education-benefits/application/5490/)
- [Apply to use transferred benefits](www.va.gov/education/survivor-dependent-benefits/apply-for-transferred-benefits-form-22-1990e/)

IA document for reference: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/edu-1990e-authenticated.md

## Tasks
- [x] Final copyedit of new static page (Megan)
- [x] Final copyedit of 2 other updated pages (Megan)
- [x] Publish all new and updated pages (Megan)
- [x] Implement left nav work (Megan)

## Acceptance Criteria
- [x] All pages are live on the site
- [x] Left nav is showing correctly

**Comment by RLHecht** [comment]
These pages and left nav work are all live now. Closing ticket.
