### ISSUE TITLE
Final updates + design specs to wireframes

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#50839]
## Description 

There is a meeting to share this work as a presentation scheduled for Tuesday afternoon. 

## Tasks

- [x] Review comments in abstract and make changes to check in and pre check in. These comments were based on Ciera and Peter's feedback. 
- [x] Hide or version out the previous and next feature. This is something that product wanted to push out to a future sprint since it's not something in the VAOS work. 
- [x] Add design specs. Design specs should include: field names, content variations (e.g., what to use when provider name isn't available), and aria label value for the details link (which should use same values seen here in [VAOS](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=1468%3A67095&t=dSOtTwKKLmiAFv7w-0)
- [x] UX team has reviewed and provided feedback
- [x] Feedback implemented into sketch/abstract

## AC

- [x] Comments in abstract are completed
- [x] All design specs are completed
- [x] UX team has reviewed and approved
- [x] Post wireframe links to ticket and move to validate column 
- [ ] Close ticket after any feedback from product and engineering team has been implemented 

## Deliverable
- [Pre-check-in (in Abstract)](https://share.goabstract.com/04c09d9c-4153-4a14-b034-2e1ca094ebb0?collectionLayerId&mode)
(https://share.goabstract.com/04c09d9c-4153-4a14-b034-2e1ca094ebb0?collectionLayerId&mode)
- [Check-in (in Abstract)](https://share.goabstract.com/4ff1e88b-7dd0-4aac-812c-1276630ffa7f?collectionLayerId&mode)
(https://share.goabstract.com/4ff1e88b-7dd0-4aac-812c-1276630ffa7f?collectionLayerId&mode)
- [A sketchcloud version](https://www.sketch.com/s/aa8d5fd0-7da2-4771-8b56-230d6308f71c) for the collab. cycle review

**Comment by benbrasso-agile6** [comment]
Looks nice, @zach-park. [Added some comments here for you. ](https://share.goabstract.com/04c09d9c-4153-4a14-b034-2e1ca094ebb0?collectionLayerId=69b4f976-44bd-4ae9-9526-42f29312ce3e&mode=design&sha=9d6460d6657fc90361f4ef65dc8c165e9298fab3)

**Comment by zach-park** [comment]
@benbrasso-agile6 @loripusey @kellysmith1008 , the annotations are ready for PO review. The links are attached in the AC area. 
- @loripusey , please ignore the collab. cycle review version.

**Comment by benbrasso-agile6** [comment]
Looks great. We are all set to present tomorrow.

**Comment by loripusey** [comment]
I love the annotations, great job @zach-park ! We can get feedback from the frontend engineers to see if this makes things clear for them.
