### ISSUE TITLE
Service user flow v1

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#5083]
## User Story:
As a Veteran, I want to be able to search by service so that I can find a facility near me offering the service I seek.

## Tasks
- [ ] Create service user flow v1 
- [ ] Consider which information is found on cards vs facility detail page

## Acceptance Criteria:
[ ] Veteran can use service-first user flow to search for high priority services such as urgent care, emergency care, pharmacy, gastroenterology, diagnostic imaging and PTSD/SUD.
[ ] Search results will be organized around service offerings, rather than facility types.
[ ] Cards displayed in search results will contain information about the services offered at the location.
[ ] Design includes "escape hatch" triggers for certain services,  e.g. "Emergency" (If this is an emergency, Go to your nearest ER) or "Mental Health" (If you or someone you know is in crisis...)
[ ] Design includes method for preparing the Veteran for the visit, agnostically. The specifics may be based on facility type (such as referral information or Urgent care eligibility link)

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by arickalewis1** [comment]
https://app.mural.co/t/vsa8243/m/vsa8243/1580762031776/bfa7b3d900a5671a1ab4caac56062008ced09806
