### ISSUE TITLE
Update health copay rates with 2023 info

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#50845]
## Issue Description

Health care copay rates change as of January 1, 2023. We need to update some of the information and dates we have on our [VA health care copay rates](https://www.va.gov/health-care/copay-rates/) page. 

To do this, we'll need to follow our steps for creating new rates pages and creating a past rates page (like we do for disability and pension). Here are directions to follow: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/how-to-update-rates-pages.md

2023 info provided by stakeholder: 

![Screen Shot 2022-12-16 at 10.43.27 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/fd9bc9a6-eb14-48ed-b736-ed3aecd539ad)

![Screen Shot 2022-12-16 at 10.43.57 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/d45fad81-4059-474f-93b9-4838af745c99)

Once we've updated the page, we need to send to stakeholders for their signoff.

## Tasks
- [x] Clone rates page to create past rates page
- [x] Update 2023 rates
- [x] Send to stakeholders
- [x] Final copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] 2023 rates are live on the site
- [x] 2022 past rates page is live on the site

**Comment by RLHecht** [comment]
I created the past rates page and updated the rates for 2023. @megzehn Could you check my work before I send to stakeholders? Thanks!

Past rates: http://preview-prod.vfs.va.gov/preview?nodeId=52037
Current rates: http://preview-prod.vfs.va.gov/preview?nodeId=703

**Comment by megzehn** [comment]
Thanks, @RLHecht! Confirming that I reviewed these.

**Comment by RLHecht** [comment]
@megzehn The stakeholder approved these changes so we can publish the current and past rates pages. Thanks!

**Comment by megzehn** [comment]
Thanks, @RLHecht! Confirming that these pages have been published!

**Comment by RLHecht** [comment]
These pages are live. I also added the link to the new R&S page and a link to the pharmacy page Cindy asked us to add. Closing ticket.
