### ISSUE TITLE
Publish instructions for adding a product entry to the VFS Product Directory

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#50846]
## User Story
As a VFS team member, I want to be able to add new products to the VFS Product Directory so that I can be sure the Product Directory stays accurate.

Assignee:
Peer Reviewer:

## Description
The VFS Product Directory includes instructions to VFS teams re: how to update an existing entry, but does not instruct VFS teams how to add their new VA.gov products to the directory. There is a process, so the purpose of this ticket is to document the process and publish it to the VFS Product Directory User Guide. 

## Impacted Artifacts
[VFS Product Directory User Guide](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory-user-guide)

## Tasks
- [ ] TBD

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] VFS teams are able to add their new VA.gov products to the VFS Product Directory.

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by holdenhinkle** [comment]
This thread has some info regarding removing a a product from the product directory -https://dsva.slack.com/archives/CBU0KDSB1/p1680098098808479

**Comment by rmtolmach** [comment]
Worked with Holden and Curt on this. A section on this page explains this process: https://vfs.atlassian.net/wiki/spaces/GS/pages/2332885004/VFS+Product+Directory+User+Guide. However, the process is to ask in #vfs-platform-support, so Curt made the page more clear.

**Comment by CBonade** [comment]
Frontend COP is currently working on a solution that would allow users to directly request an addition or removal of a product. The feature is still in planning stages, but it's in progress. The documentation for this will be updated as soon as the feature is available for users. Until then, all requests to add products are requested to be sent to the front end COP via frontend support (already spoke with support about this) and we will process them once the actual method has been finalized.

**Comment by holdenhinkle** [comment]
Let's call this done. We updated the documentation to reflect the current state, which is what we wanted. Please create a new ticket to update documentation when a new solution is implemented.
