### ISSUE TITLE
[PM] Address validation: Create call center guide

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5084]
## User story

As a veteran, I may have questions about updating my address of VA.gov if I'm told there is a potential problem with the address I've entered.

As a call center employee, I need to understand the address validation/profile updates well enough to field any questions that may com in from veterans.

## Background

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/call-center/request-contact-center-review.md

## Tasks

- [x] Create call center guide.
- [x] Review with Chante.

## Acceptance Criteria

- [x] Call center guide has been approved by Chante.

**Comment by Samara-Strauss** [comment]
@clantosswett I have a new call center guide for the address validation feature we are adding to the profile. It's below. Please let me know if you have any feedback.

Also, I don't think the call center has an adequate guide for the whole profile based on what I found in GitHub. The doc I found from a couple years ago is woefully inadequate. We can provide a full, totally updated guide when we release the Profile 2.0 work in the spring. Given that there will be a total UI overhaul at that point, I don't think there's much point in proving new documentation before then. When we get out that new guide in the spring, we can roll the address validation content into it.

[Address validation call center guide.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4199410/Address.validation.call.center.guide.docx)

**Comment by Samara-Strauss** [comment]
cc/ @mshea0606 — here is the call center guide ticket for address validation. Feel free to subscribe!

**Comment by clantosswett** [comment]
@Samara-Strauss This looks great! I made some slight edits to increase the size of the images but otherwise this is good to go and we will pass along to the contact center. Quick question. Should this fix the issue that we see users have with updating their address and it just won't save? I am assuming yes but wanted to double check. Also, do you have a timeline for when this will go live in prod? 

[Address.validation.call.center.guide.cls.edits.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4200561/Address.validation.call.center.guide.cls.edits.docx)

**Comment by Samara-Strauss** [comment]
> Quick question. Should this fix the issue that we see users have with updating their address and it just won't save? I am assuming yes but wanted to double check.

What issue? I need more information on how to duplicate it so we can see the bug and put in a ticket for it.

**Comment by Samara-Strauss** [comment]
> What issue? I need more information on how to duplicate it so we can see the bug and put in a ticket for it.

Regrouped offline: This is the issue with some particularly unique addresses not being recognized/savable. Address validation should hopefully fix this by allowing override.
