### ISSUE TITLE
[PM] Address validation: Create release plan

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5085]
## Background

This is part of the project pre-launch checklist.

## Tasks

- [x] Determine KPIs for the project and how we will measure them.
- [x] [Complete release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/change-address/address-validation/release-plan.md)

## Acceptance Criteria

- [x] Release plan is complete and saved in the candidate address folder on Github.

**Comment by Samara-Strauss** [comment]
Reopening to revisit and update the release plan.

**Comment by Samara-Strauss** [comment]
[Release plan updated](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/change-address/address-validation/release-plan.md). Closing again.
