### ISSUE TITLE
[FE] Deprecate check_in_experience_lorota_deletion_enabled Feature Flag

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#50855]
## Description
Remove `check_in_experience_lorota_deletion_enabled` usage in vets-website for moving forward with feature flag deprecation

## Tasks
- [ ] [FE] Modify code using check_in_experience_lorota_deletion_enabled 
- [ ] Create or update unit tests
- [ ] Create or update e2e tests

## Acceptance Criteria
- [ ] Deployed to staging.
- [ ] Tested on staging

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
closing since this is merged and there are no further validation steps
