### ISSUE TITLE
DEV Manual testing: Platform Endpoints

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#50864]
**PROBLEM STATEMENT**
We complete manual testing before synthetic tests to ensure we are aware of the routes, and ensure the routes are accurate (including the perimeters).

**TASKS**
- [x] (Lainey to include in VFS comms) Endpoint ownership: define who owns the endpoints [[document](https://docs.google.com/spreadsheets/d/14iNeWOyaMe0aqVtgfCqTE7cl3xAfQ7YJDsjRbADOXCk/edit?pli=1#gid=1482742543)]; review document as teams have changed.
          - [ ] (Dependent on endpoint ownership confirmation) Discover test users
          - [ ] (Dependent on endpoint ownership confirmation) Discover available test data; can use test suite
          - [x] (Lainey) Determine standard form of communication with VFS teams (this will be in the form of tickets with a deadline; Lainey and Lindsey to meet)
- [ ] Test [platform-owned endpoints ](https://docs.google.com/spreadsheets/d/1pj8D4cXtHta8VsO53Q3AUKBHwbjRmo3v0BJHUFuU-c0/edit#gid=1929878634)

- [ ] (all) Record all findings

**Comment by LindseySaari** [comment]
Looking at TestRail to poke around for VFS endpoint testing

**Comment by laineymajor** [comment]
@laineymajor break this ticket out into VFS manual testing vs Platform manual testing

**Comment by LindseySaari** [comment]
1/5 - I started working through the document to determine ownership

**Comment by LindseySaari** [comment]
1/10 - I started working through [this doc](https://docs.google.com/spreadsheets/d/1pj8D4cXtHta8VsO53Q3AUKBHwbjRmo3v0BJHUFuU-c0/edit#gid=1929878634) on the items that have a ⚠️ symbol. If a test cannot be completed via a synthetic (browser or http test) I'm recording results in Test Rail. [Example test for /flipper/features](https://dsvavsp.testrail.io/index.php?/cases/view/33191&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=8784)

**Comment by LindseySaari** [comment]
I should also note that I'm working through some postman tests to record a platform test suite. This could be a standard for VFS teams as well since they don't have access to Datadog

**Comment by LindseySaari** [comment]
1/11: I started on a postman test suite and will discuss auth with Joe and Trevor today. I also created [a testing guidelines](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2485518367/EKS+Endpoint+Testing) doc for VFS teams to reference

**Comment by laineymajor** [comment]
LH meeting with Joe and Trevor to discuss additional options

**Comment by LindseySaari** [comment]
1/12: 

1. Trevor suggested having each team create dedicated test users for their teams use. To get familiar with this process, I'm walking through the test user creation process. I created ID.me user `vets.gov.user+2023@gmail.com`. There's an issue, so waiting to hear back from Trevor

2. I created the EKS Testing doc with info around postman testing, user creation and MVI mocking

3. When obtaining an access token via the SiS flow (from the EKS testing doc), a refresh token is also returned. We could use the refresh token/save as a variable in Postman so that it gets us some more testing room (45 days) instead of always having to re-authenticate. Will look into this after the test user issue in item #1.

**Comment by LindseySaari** [comment]
1/17: Turns out that we can't login with client_id=mobile, confirmed with Trevor.` client_id=mobile` would use the mobile applicationcontroller, which won't work in our case :( . Waiting to hear from Trevor on the cookie solution and then will rewrite the Endpoint Testing doc Auth section

**Comment by laineymajor** [comment]
Lindsey continuing to sync with Trevor

**Comment by laineymajor** [comment]
Updated docs

**Comment by LindseySaari** [comment]
1/20: I've made some more headway on a few of the "Platform endpoints" from the[ endpoints sheet.](https://docs.google.com/spreadsheets/d/1pj8D4cXtHta8VsO53Q3AUKBHwbjRmo3v0BJHUFuU-c0/edit#gid=1929878634). We should continue to ping vfs teams about in_progress_forms and who "owns" the various form_ids

**Comment by laineymajor** [comment]
I have this on my slide for ToT. I'll also just add the question to the tickets I'm about to send out for testing... @LindseySaari

**Comment by LindseySaari** [comment]
1/24: I've completed testing for all [platform endpoints](https://docs.google.com/spreadsheets/d/1pj8D4cXtHta8VsO53Q3AUKBHwbjRmo3v0BJHUFuU-c0/edit#gid=1929878634) (Synthetic and Postman). There are a few endpoint ownership questions, all in which are documented/highlighted in yellow on the bottom of the Platform sheet.

**Comment by LindseySaari** [comment]
1/24: I've completed testing for all [platform endpoints](https://docs.google.com/spreadsheets/d/1pj8D4cXtHta8VsO53Q3AUKBHwbjRmo3v0BJHUFuU-c0/edit#gid=1929878634) (Synthetic and Postman). There are a few endpoint ownership questions, all in which are documented/highlighted in yellow on the bottom of the Platform sheet.

**Comment by LindseySaari** [comment]
Working on identifying form_id owners

**Comment by laineymajor** [comment]
Sending out tickets today to newly found owners :)

**Comment by LindseySaari** [comment]
Owners found for all forms and all platform endpoints are testing in some fashion (synthetic or manual/postman)

**Comment by laineymajor** [comment]
@LindseySaari should I go ahead and close this out?
