### ISSUE TITLE
Synthetic testing

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#50863]
**PROBLEM STATEMENT**
38 tests that verify the approp response from the endpoints that we are testing for the vets-api server migration to EKS in DEV.

**TASKS/questions**
- [x] (Igor) VFS aka "Inside" testing (near complete as of 12.19) *Rachal to review*
- [x] (Igor) revproxy aka "Outside" testing (start with the ones that are working)
- [x] (Lainey) Destinations need to be ok'd by the appropriate teams (need to send out this communication)
- [ ] Validation (second set of eyes; Rachal and Lindsey)

**Comment by considerable** [comment]
The dev test can be reviewed [here](https://vagov.ddog-gov.com/synthetics/tests?query=tag%3A%28%22team%3ATT1%22%29&page_size=50) (not tuned for the alert message recepients yet)

**Comment by laineymajor** [comment]
Per Igor: Currently all alerts go to test channels.

**Comment by LindseySaari** [comment]
Nice work @considerable! I reviewed the [non-revproxy synthetics](https://vagov.ddog-gov.com/monitors/manage?q=vfs-dev&id=104605) and the [revproxy synthetics](https://vagov.ddog-gov.com/monitors/manage?q=revproxy-dev&id=104605) in the UI along with the terraform. Looks really nice and the terraform is a great way to standardize the tests as code.

**Comment by LindseySaari** [comment]
1/5 - I started working through Datadog browser tests for /v0/welcome which is an authenticated endpoint. I got it to pass, but want to look into some issues when params are needed for api requests

**Comment by LindseySaari** [comment]
1/11: I'm meeting with Joe and Trevor to explore Datadog Synthetic options and talk about a possible mock auth solution.

**Comment by LindseySaari** [comment]
1/12: I met with Joe and Trevor for a GREAT meeting! They saw the issue that we were running into in Datadog and are going to either explore options with Datadog or add this as an item for their team to take a look at. We walked through several browser and http test examples. There's just no way to get an access token without going through the browser, so the first few steps are unfortunately manual

**Comment by LindseySaari** [comment]
1/12: I met with Joe and Trevor for a GREAT meeting! They saw the issue that we were running into in Datadog and are going to either explore options with Datadog or add this as an item for their team to take a look at. We walked through several browser and http test examples. There's just no way to get an access token without going through the browser, so the first few steps are unfortunately manual

**Comment by rmtolmach** [comment]
(I deleted duplicated comments ☝️)

**Comment by laineymajor** [comment]
Lindsey continuing to sync with Trevor to determine some better paths moving forward.

**Comment by laineymajor** [comment]
Joe requested more test capacity. 
Looking into mock auth solution with Trevor and team.

**Comment by LindseySaari** [comment]
1/20: [The Identity team has created a ticket](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/52278) to discuss mock auth solutions for testing.

**Comment by LindseySaari** [comment]
[latest message here](https://dsva.slack.com/archives/C01U8EYHSEM/p1673981190539099?thread_ts=1673467389.412039&cid=C01U8EYHSEM): Waiting for a reply

**Comment by LindseySaari** [comment]
Still waiting for a DOTS reply

**Comment by laineymajor** [comment]
Waiting.

**Comment by LindseySaari** [comment]
Still waiting for a DOTS reply. Some changes being made to vagov datadog, waiting to see if this applies to Synthetic testing

**Comment by laineymajor** [comment]
We are currently blocked by DOTS; limited by what's available via datadog.

FYI @BillChapmanUSDS we are currently blocked here...

**Comment by laineymajor** [comment]
@LindseySaari any progress with DOTS? Probably need to start discussions for plan b.

**Comment by laineymajor** [comment]
We _think_ the DOTS team is requesting to bump the limit to 200; revisit in 6 months and discuss if more is needed.

**Comment by laineymajor** [comment]
Per Bill, @agmurphy check with identity team to see if there are any tests they are not using.

**Comment by LindseySaari** [comment]
[Datadog has increased our test limit to 500](https://oddball.slack.com/archives/C0498A63YGM/p1675967668663119) (even beyond the 200 increase that we had originally asked for). I think this is enough of a cushion for all teams to test what they need.

**Comment by laineymajor** [comment]
@LindseySaari does this ^^^ mean we should be good to close this ticket by COB tomorrow (1.14)?

**Comment by laineymajor** [comment]
There are a few platform endpoints that do not yet have synthetic tests. This has been indicated in the endpoint document.

**Comment by LindseySaari** [comment]
I've added the [remaining dev GET endpoints as Datadog synthetic browser tests](https://vagov.ddog-gov.com/monitors/manage?q=creator%3A%22Lindsey%20Hattamer%22). The rest (e.g. POST or PUT endpoints) are covered via manual (Postman) tests. The added tests are browser based tests (not stored in Terraform) because we need to utilize the login flow from the frontend (vets-website) and the access_token is stored in a cookie to be sent along with API requests. Our simple GET tests (not behind auth) are stored in Terraform (See [vets-api](https://github.com/department-of-veterans-affairs/devops/blob/f509fc2ce796bbe2819d3aa81c3714df60f9ec39/terraform/environments/datadog/catalog/synthetics/vets-api.yaml) and [platform-endpoints](https://github.com/department-of-veterans-affairs/devops/blob/f509fc2ce796bbe2819d3aa81c3714df60f9ec39/terraform/environments/datadog/catalog/synthetics/platform-endpoints.yaml) Terraform) 


Link to the Datadog tests - [vfs (behind socks no revproxy) ](https://vagov.ddog-gov.com/monitors/manage?q=vfs-dev) and [revproxy based tests](https://vagov.ddog-gov.com/monitors/manage?q=%5BSynthetics%5D%20revproxy-dev)

See [spreadsheet for all status for Platform endpoints](https://docs.google.com/spreadsheets/d/1pj8D4cXtHta8VsO53Q3AUKBHwbjRmo3v0BJHUFuU-c0/edit?pli=1#gid=1929878634).

Identity team is still working through mock auth so that we can use pure Datadog HTTP tests to hit the API instead of having to login via the frontend via a browser based test. There is currently no way to hit the API in an automated fashion without passing auth based cookies (that eventually expire) for the access_token and session.
