### ISSUE TITLE
Evaluate options on pivoting form Survey and/or morphing Survey to NPS

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#50873]
## Issue Description
Change is org structure means that half of the Platform teams are no longer responsible for distinct Products or Spaces.  Thus, collecting Insights each quarter for those teams to review, digest, and apply is no longer aligned with their operation.

Our discussions on this issue have led to consider the following pivots:
1. Moving toward a continuous feedback portal instead of the survey
2. Altering the survey to be an NPS indicator, potentially with multiple spaces inquired about

## Tasks
- [x] Frame advantages/challenges of [these options](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1671487217436/322aeea584fb5920457198d781279f6be2def0c6) (async brainstorm Mural in progress)
- [x] Team Discussion 1 - review options as a team
- [x] Team Discussion 2- continue reviewing options as a team

## Acceptance Criteria
- [x] decisions are [documented]
