### ISSUE TITLE
FE | Profile | Notifications| Remove FF for BVA Status Update Notifications

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#50889]
## Background

We need to remove the feature flag for the new BVA status update notification preference.

There is one with name `profile_show_appeal_status_notification_setting` and one with name `profile_show_appeal_status_notification_setting'` (has an erroneous ' at the end) and both should be removed

## Tasks
- [x] Remove the flag from local, staging, and prod environments using the Flipper UI
- [x] Investigate why the `profile_show_appeal_status_notification_setting'` is still showing although it has been removed in the BE code already
- [x] Update/cleanup Cypress tests

## Acceptance Criteria
- [x] confirm in feature toggle admin that these no longer appear

**Comment by Samara-Strauss** [comment]
Hey Adam! Will this be done by tomorrow? OK, if not, but wondering if I should move it into the next sprint. Thanks!

**Comment by adamwhitlock1** [comment]
Yes, I believe I will be able to get this done by tomorrow. Have a branch prepped for FE and just need to revisit the BE toggle side to finish this out and get it in PR

**Comment by adamwhitlock1** [comment]
PR is open for the BE api toggle removal now that staging has been validated as working as expected.

**Comment by Samara-Strauss** [comment]
Great! Thank you for the update! Let me know when the backend flag is removed, and then I can check things in production.

**Comment by adamwhitlock1** [comment]
So the toggles for this ticket have been removed and no longer show up in staging, but are still present in production.
Tom and I are looking into why the production ones are sticking around, but we can confirm that the actual code for them has been removed. Most likely the database table for the toggles needs to be refreshed/cache busted for this in some way on the BE.

**Comment by Samara-Strauss** [comment]
Got it. Thank you! Keep me posted as you figure out what might be going on with the feature toggle table.

**Comment by Samara-Strauss** [comment]
All frontend work is done. @tpharrison will open a ticket for any further investigation into why things are sticking around on the backend.
