### ISSUE TITLE
Assess home loan fact sheets to determine placement on VA.gov

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#50882]
## Issue Description

Tanewka sent us 2 fact sheets about home loans for us to assess and determine if and where they should be placed on VA.gov. Once we assess the content, we can create another ticket to implement whatever work we will do.

Fact sheets to assess:

[https://app.zenhub.com/files/133843125/8217538c-eaf6-4b61-8a8a-d24843fe9989/download](https://app.zenhub.com/files/133843125/8217538c-eaf6-4b61-8a8a-d24843fe9989/download)

[https://app.zenhub.com/files/133843125/c3db6062-44e2-4dd2-93af-b3520455d22f/download](https://app.zenhub.com/files/133843125/c3db6062-44e2-4dd2-93af-b3520455d22f/download)

## Tasks
- [ ] Assess content in fact sheets
- [ ] Create new tickets for follow-up work (Randi)
- [ ] Notify Tanekwa of work plan

## Acceptance Criteria
- [ ] Fact sheets have been assessed and follow-up work determined

**Comment by RLHecht** [comment]
Taking this out of Sprint 91 and we will pull this in when we have capacity in a future sprint. Tanekwa said they created pages for these since the team wanted this info placed online quickly. We'll eventually assess where we can add this info in the home loans section.

https://benefits.va.gov/homeloans/temporary-buydown.asp
https://benefits.va.gov/homeloans/escape-clause.asp
