### ISSUE TITLE
[Spike] DDL: error message for maintenance downtime

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#50885]
## Value Statement
**_As a_** veteran
**_I want to_** know when my claims letters are not available for download due to scheduled maintenance
**_So that_** it's clear to me that I'll be able to download my letters once the maintenance period is over

---
## Background Context
- VBMS goes down for maintenance sometimes and during that time, claim letters will not be available for download. Currently, users just see a standard error message. 

## Acceptance Criteria
- [ ] Design for message is accessible
- [ ] Error messages shows up whenever VBMS is undergoing maintenance

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
- Is it possible to know and show the timeframe for maintenance so users know when they can come back to get their letters? 
- Can we use a similar approach we use for forms to check for downtime? 

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jacobworrell** [comment]
Spike: take a look and see if we can use the same implementation approach we use on forms.
