### ISSUE TITLE
Update Research Repo guidance on Platform Website

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#50884]
## User Story
As a VFS team member needing access to the research repo, I don't want to have to take any superfluous or unnecessary steps in order to gain access to the research repo.

Assignee: @CherylEvans 
Peer Reviewer: @allison0034 

## Description
The Platform Website guidance on requesting access to the VA research repository still guides VFS teams to reach out to Shane Strassberg on the #research-ops Slack channel. This is no longer the correct process and the Platform Website page must be updated.

## Impacted Artifacts
[Request Access to Tools page - VA Research Repository section](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-VAResearchRepository)

## Tasks
- [x] Delete the current guidance under VA Research Repository and replace it with:

> Access to the [VA.gov research repository](https://github.com/department-of-veterans-affairs/va.gov-research-repository/projects/1) is granted through [Platform Orientation.](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-orientation)
- [x] Confirm language with @naomimarcussen. Questions to ask Naomi:
   - This guidance no longer mentions Shane  - is that ok?
   - This guidance no longer names the research Slack channel - is that ok?

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS teams are no longer directed to reach out to Shane to receive access to the research repo

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
@naomimarcussen  Good morning Naomi. :-)
I am working on ticket [50884](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/gh/department-of-veterans-affairs/va.gov-team/50884) and would like your guidance as to the changes I am making in this section.  If you go to the ticket and look under the “Tasks” tab, there are a few questions for you.  Please let me know your thoughts/recommendations and I will implement soonest.  However, if you are good with the changes, I will publish.  Thank you!!

**Comment by naomimarcussen** [comment]
I commented on the Confluence page. I think this language works. If we see folks having trouble getting in we could add something about how to get help. Not sure who that would be though.

**Comment by CherylEvans** [comment]
@naomimarcussen I agree.  Thank you for reviewing and providing your fb.  :-)

**Comment by shiragoodman** [comment]
@CherylEvans please be sure to link your draft Confluence page to this ticket. thank you!

**Comment by CherylEvans** [comment]
@naomimarcussen [Draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2468249601/50884+-+Cheryl+Draft+-+Copy+of+Request+access+to+tools) Confluence page.

**Comment by CherylEvans** [comment]
@naomimarcussen @shiragoodman  VA.gov research repository [link](https://github.com/department-of-veterans-affairs/va.gov-research-repository/projects/1) is broken and goes to 404 error page.  I went to the platform page and confirmed that the link research repo link is in fact broken.  Please advise.  Thank you!

**Comment by shiragoodman** [comment]
the link isn't broken, it just doesn't direct you to the page unless you have access. I am able to access it w/o issue. 

Can you try again and make sure you're logged into gh? You should also have access to it.

**Comment by CherylEvans** [comment]
@shiragoodman DOH!!  Thank you for the reminder.  It works just fine.
@naomimarcussen Just published draft changes to [source page](https://vfs.atlassian.net/wiki/spaces/GS/pages/969605215/Request+access+to+tools).

**Comment by CherylEvans** [comment]
The user story and acceptance criteria have been satisfied and the changes are published to platform website.

**Comment by CherylEvans** [comment]
@allison0034 Naomi has already reviewed, and it has been published to the Platform website.  Please review when you get a chance, and then I will close.  [Link](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2468249601/50884+-+Cheryl+Draft+-+Copy+of+Request+access+to+tools) Also, you have to be logged into GH for the Research repo link to work.  :-) Thank you!!

**Comment by allison0034** [comment]
@CherylEvans @naomimarcussen @shiragoodman after doing user research with people on platform orientation I feel I am extra sensitive to content and "access" issues. That being said, I am not sure if...

VA Research Repository
Access to the [VA.gov research repository](https://github.com/department-of-veterans-affairs/va.gov-research-repository/projects/1) is granted through [Platform Orientation.](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-orientation)

...is clear enough. That link goes to the orientation page which does not mention getting access. If I was new and needed access I would be wondering do I have to contact someone on platform orientation? Do I attend a session? Fill out a form?

My suggestion would be to add exactly what needs to happen to get access. Something like...

Access to the [VA.gov research repository](https://github.com/department-of-veterans-affairs/va.gov-research-repository/projects/1) is granted through [Platform Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-orientation). Opening a new [Platform Orientation GitHub template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team%2C+analytics-insights%2C+analytics-request&template=orientation-epic.md&title=Platform+Orientation+Template+%5BYour+name+here%5D) will automatically start the process to grant you access.

Or whatever that detail is. What do you all think? I just know we heard a lot about dead end loops for access and this seems like one of them.

**Comment by CherylEvans** [comment]
@allison0034 @naomimarcussen @shiragoodman You make a great point, Allison.  Unless anyone has any objections, I will change the verbiage to align more with your recommendations and tag for your review.

**Comment by CherylEvans** [comment]
@allison0034 What are your thoughts on this [verbiage](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2468249601/50884+-+Cheryl+Draft+-+Copy+of+Request+access+to+tools)? 
I want to make sure this is detailed as well as factually correct.

**Comment by allison0034** [comment]
@CherylEvans there are multiple sessions, and I don't think attending is what gives you access. @shiragoodman @naomimarcussen do you know exactly how they get access?

**Comment by CherylEvans** [comment]
@allison0034 Does their attendance provide them with the guidance to gain access?

**Comment by CherylEvans** [comment]
@allison0034 Once we know the particulars of getting access I will rewrite!  :-)

**Comment by CherylEvans** [comment]
@allison0034 I think [this](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2468249601/50884+-+Cheryl+Draft+-+Copy+of+Request+access+to+tools) should work.  There is similar verbiage used elsewhere on the page.

**Comment by allison0034** [comment]
Looks good, thank you!

**Comment by shiragoodman** [comment]
I have one request. Please don't link the template directly. I would prefer if folks found the template by visiting the Platform Orientation page. Could we try:

[VA.gov research repository ](https://github.com/department-of-veterans-affairs/va.gov-research-repository/projects/1)access is managed through the [Platform Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-orientation) process.[
Opening a new Platform Orientation GitHub template, accessible via the ](https://depo-platform-documentation.scrollhelp.site/getting-started/guidance-for-new-teams-and-team-members)Guidance for new teams and team members page, will automatically start the process to grant you access.

**Comment by CherylEvans** [comment]
@shiragoodman @allison0034 Sounds great and makes sense!  Thank you both for your input and recommendations!

**Comment by CherylEvans** [comment]
Published to PW.

**Comment by naomimarcussen** [comment]
Thank you for these edits @CherylEvans and @allison0034. I like where this landed.
