### ISSUE TITLE
[SSL Certificates] Replace `/ssl/design.va.gov` BEFORE 2023-02-16

### ISSUE THREAD

**Issue by ianhundere** [department-of-veterans-affairs/va.gov-team#50900]
## Description
Replace SSL certificates before they expire. (See alerts below)

## Resources
- Alerts from [#devops-deploys](https://dsva.slack.com/archives/C37M86Y8G/p1669049781914579):
```
ATTENTION: /ssl/design.va.gov-2023.crt expires in less than 60 days: 2023-02-16T23:59:59+00:00
ATTENTION: /ssl/design.va.gov.chained-2023.crt expires in less than 60 days: 2023-02-16T23:59:59+00:00
```
- Jenkins expiry scanner [link here](https://dsva.slack.com/archives/C37M86Y8G/p1671468982584919)

- Instructions on renewing publicly signed SSL certificates [HERE](https://github.com/department-of-veterans-affairs/devops/blob/master/docs/StandardOperatingProcedures/PublicSSLCertificateProcesses.md)

## Tasks 
- [ ] Request and install certs for all listed hosts/environments
- [ ] Test by connecting to the endpoints and ensuring that the updated certificates are returned (if applicable)
- [ ] Delete certs that have been replaced

## Acceptance criteria
- [ ] Services are up and running using new cert
- [ ] Cert is replaced at the TIC (if applicable)
- [ ] Cert is replaced on the fwdproxy or revproxy alb (if applicable)
- [ ] Cert is replaced in the fwdproxy or revproxy (if applicable)

**Comment by laineymajor** [comment]
@considerable will be taking this on after our double sprint. @ianhundere can he have support from someone in the CoP (this will be his first cert upgrade). Thanks!

**Comment by considerable** [comment]
https://vfs.atlassian.net/wiki/spaces/OT/pages/2354315287/VA.Gov+Platform+Manual+WIP#SSL%2FTLS is the new (confluence) location of the [PublicSSLCertificateProcesses.md (Instructions on renewing publicly signed SSL certificates) ](https://github.com/department-of-veterans-affairs/devops/blob/master/docs/StandardOperatingProcedures/PublicSSLCertificateProcesses.md) in the `Resources` section of the tkt `Desctiption`.
