### ISSUE TITLE
Fix broken links on DS Logon FAQs page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#50907]
## Issue Description

A VA partner reached out to let us know there is a broken link on our [DS Logon FAQs](https://www.va.gov/resources/ds-logon-faqs/) page. The CTA link for " Read more FAQs on the DS Logon website" is broken and should be removed.

There's also a broken link for Create a new password on the DS Logon website. We should point users to https://www.dmdc.osd.mil/identitymanagement/app/login, which is the main DS Logon page, since you can't access anything further without logging in.

## Tasks
- [x] Remove broken CTA link
- [x] Update password link
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Broken links are no longer on the site

**Comment by RLHecht** [comment]
@megzehn I removed the broken CTA link and updated the other link. This is ready to copyedit and publish. Thanks!

**Comment by megzehn** [comment]
Thanks, @RLHecht! Confirming that I reviewed and published these changes.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
