### ISSUE TITLE
Plan a Platform website orientation for VFS team members

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#50915]
## Product Outline
[Link](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2516877313/Product+outline+-+Content+orientation+for+VFS+teams)

## High Level User Story/ies
As a new VFS team member,
I need to understand how the Platform website is maintained,
so I can make suggestions to the content of the website.

As a Platform Content team member,
we need to clarify to document clear instructions on how VFS team members can provide or suggest new content for the Platform website,
so they are encouraged to contribute content that’s important to them,
so they continue to use the Platform website as their primary source of information,
so they reference the Platform website before seeking help from the #vfs-platform-support channel,
so the accuracy of the website content is maintained,
so the Platform website continues to be useful for VFS team members.

## Hypothesis or Bet
**If** we provide a proper introduction of the Platform website to VFS team members,
**then** they will understand how the website is maintained; and
they will be more likely to engage with us in the future; and
we will have more updated content on the Platform website

## OKR

- The Platform Content team will receive more feedback from VFS customers about content on the website
- More content suggestions for the Platform website will be provided by VFS teams

## Definition of done

- [x] A mechanism to deliver the Platform website orientation to new VFS team members will be defined (in-person, slides, video, etc.)
- [x] Topics to focus the orientation on will be defined (Website IA, how to report an issue, how to suggest new content, how to provide feedback)
- [x] A plan for how to provide this new Platform website orientation will be agreed upon with the Governance team.

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## Artifacts
Product outline: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2516877313/Product+outline+-+Content+orientation+for+VFS+teams

1-minute video: https://www.youtube.com/watch?v=yzl6nyLmqkA

**Sharing with new VFS team members**

The Governance team will be adding a link to the video on:

- The [orientation slide](https://docs.google.com/presentation/d/1xZMmHtsa65fJ1nMMfFC2PWFBDhBmBWmx1EqQQlPdsVc/edit#slide=id.gf08689d579_0_58) they use for the Platform orientation for VFS team members
- The [orientation GitHub checklist](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=analytics-insights%2C+analytics-request%2C+governance-team%2C+platform-orientation&template=orientation-epic.md&title=Platform+Orientation+Template+%5BYour+name+here%5D) VFS team members use. [Link to template here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/orientation-epic.md).
- ZenHub [ticket here](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/gh/department-of-veterans-affairs/va.gov-team/54824).

**Sharing with existing VFS team members**

- The video was also shared with existing VFS team members via Slack [through this post](https://dsva.slack.com/archives/C03R5SBELQM/p1678385139716529).

- Shared at Team of Teams on March 14, 2023

**Comment by vbellissimo** [comment]
We've met our definition of done for this initiative and officially closing this card now.
