### ISSUE TITLE
[Ongoing Service] Platform Content Customer Support: FY2023 Q2

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#50918]
## User Stories
As a VFS team member,
I need to report an issue, provide feedback, or provide content suggestions for the Platform website,
so that I can contribute to the quality of the content of the site.

As a Platform team member,
I need help from the Platform Content team,
so that I can report an issue, ask a question or contribute to the content of the Platform website.

As a Platform Content team member,
I need to support any team asking for help,
so I don't become a blocker and can enable teams to iterate on their content quickly.

## Support Mediums
1. Slack channels: #platform-content and #vfs-platform-support

2. Office Hours: every Tuesday at 2:30pm EST

3. Platform content orientations

## Definition of done
- [x] All Slack inquiries are acknowledged and replied-to in the channels listed above in FY2023 Q2
- [x] All office hours attendees are documented in FY2023 Q2
- [x] Host all necessary Platform website/content orientation for new team members in FY2023 Q2
- [x] All new content on the Platform website is reviewed and announced to VFS teams in FY2023 Q2
