### ISSUE TITLE
Seek SMEs for Remaining Confluence URLs Replacements

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#50912]
### Tasks

- [x] Reach out to Jason and Clint via the #vfs-platform-support channel
- [x] Provide them auditing spreadsheet
- [x] Ask for a SME for each of the remaining sections that need a URL replacement
- [x] Update auditing spreadsheet, as needed
