### ISSUE TITLE
Continue edits to Accessing Internal Tools page

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#50924]
### Tasks

For this page: https://github.com/department-of-veterans-affairs/va.gov-team/issues/50079
- [x] Reach out to Eric again to ask remaning question
- [x] Finalize edits based on Eric's feedback
- [x] Review page again with Jason and Clint, before scheduling for deploy
- [x] Move from drafts to final IA before scheduled day

**Comment by SSimmorins** [comment]
Lauren will reach out to SME after holiday break in Jan 2023
