### ISSUE TITLE
[Design] Add error page(s) that are missing in sketch/abstract

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#50920]
## Tasks

Add or update error page(s) that are missing in sketch/abstract for:
- [x] CI-error-general (Add) - See attached screens in the comment section.
- [x] PCI-error-UUID (Update) - See attached screens in the comment section.
- [x] PCI-error-15mins after (Update) - See attached screens in the comment section.

## AC
- [x] [CI-error-general](https://share.goabstract.com/180000a5-f1fe-43f4-a519-c9c88d4e600c?mode=design&sha=39e1cfed3c1de41f603f3dd2b70db615661ae006) (Abstract link)
- [x] [PCI-error-UUID](https://share.goabstract.com/22079e8b-5092-467d-a773-5846f128f89a?mode=design&sha=f877408100d8cdc2284f340dfa9fa86a71b5958d) (Abstract link)
- [x] [PCI-error-15mins after](https://share.goabstract.com/58dd8e6b-51f7-40c7-8704-0dd86017a437?mode=design&sha=f877408100d8cdc2284f340dfa9fa86a71b5958d) (Abstract) link
- [x] Published to sketch/abstract masters

**Comment by zach-park** [comment]
**CI-error-general** 
![CI-error-general.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/6d5e5c0f-5c18-4bf4-9403-001de585b9d6)

**Comment by zach-park** [comment]
**PCI error UUID**
![PCI-error-UUID.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/17c5390d-f670-493c-bf54-f5d203523900)

**Comment by zach-park** [comment]
**PCI error 15 minutes after appt.**
Update the existing wireframe for this usecase
![After 15 mintues after the appointment start.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/b2c1d531-d28d-4e16-9dae-6aba9049a52e)

**Comment by zach-park** [comment]
@loripusey @benbrasso-agile6 , wireframes were updated to match the stg. and released to the SketchClouds.
