### ISSUE TITLE
[FE] [STAGING APPT TOOL] Allow creating appointments for dev (station 500)

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#50925]
## User Story
As a developer, I want to be able to easily test check-in workflows on the dev infrastructure, so that I may more efficiently develop bug fixes and new features.

## Implementation

This could be implemented as a station selection or possibly a separate URL for dev appointments. Either way, it should be clear to the user for which station they're viewing and booking appointments.

## Tasks
- [ ] Allow booking appointments at station 500 as well as station 530
  - [ ] current station is clearly displayed
  - [ ] correct user and clinic names are displayed for the current station
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
