### ISSUE TITLE
(Samara) Create Terms and Definitions page in Confluence

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#50922]
### Tasks

- [x] Create new page in Confluence for this content: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/octo/product/terms%20and%20definitions.md / may need to clean up the formatting, add introduction, etc.
- [x] Review new page with Ryan Smith
- [x] Determine where in the Product Directory section of the IA this page will live
