### ISSUE TITLE
[UX] Create SMS Message for Canceled Appointment in Day of Check-in

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#50929]
As a Veteran, I would like to know that I'm checking in for an appointment that has been canceled.

# Tasks
- [ ] Double check with PCI API team that this scenario is technically possible and to just let them know that we are thinking about this.
- [ ] Create new SMS message within the day of workflow to let a Veteran know their appointment was canceled. Work with sitewide content if need be.

# Acceptance Criteria
- [ ] Wording is documented
- [ ] Wording is shared with PCI API team.

# Details
The current SMS, which covered canceled appointments, is found at: https://github.com/department-of-veterans-affairs/chip/blob/master/docs/chip-messaging.md

**Comment by loripusey** [comment]
Question: does the Veteran actually get a confirmation for a cancelled appointment? Not sure why this would happen. Since this confirmation is when they get their first Pre-check-in link, does this actually happen? (I'm ignoring how we might do things with the unified experience).
@benbrasso-agile6 @kristenmcconnell

**Comment by benbrasso-agile6** [comment]
> Question: does the Veteran actually get a confirmation for a cancelled appointment? Not sure why this would happen

It likely depends on the modality (e.g., vetext, phone, vaos, MHV, etc.) + there's a human factor involved sometimes. E.g., if they remember to send a cancelation message to the Veteran. 

To be more specific, the scenario this ticket is for is: 

Veteran schedules an appt
Someone cancels the appt
Veteran texts check in to 53079
Veteran (should) receive a text response back from VEText that their appt has been cancelled 

Currently, there's only a VEText message that says, "sorry, we can't check you in." 

This scenario will be rare, but possible.

**Comment by loripusey** [comment]
too old, closing
