### ISSUE TITLE
Create and publish R&S page for Tier 1 medications list

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#50931]
## Issue Description

When updating the health care copay rates for 2023, we learned that we need to have a list of Tier 1 copay medications on the site. Because the original list is in a PDF, we need to create a new R&S page with the same info so that it's more accessible. We'll link to the new R&S page from the rates page.

PDF with info to use: https://www.pbm.va.gov/PBM/Tiered_Copay/Tier_1_CO-PAY_MEDICATION_LIST.pdf

## Tasks
- [x] Create page (Danielle)
- [x] Copyedit (Megan)
- [x] Send to stakeholders for approval (Randi)
- [x] Publish

## Acceptance Criteria
- [x] New R&S article is live on the site

**Comment by RLHecht** [comment]
Danielle started this article already: http://preview-prod.vfs.va.gov/preview?nodeId=52081

We need to add a sentence or two to the intro about what tier 1 medications are.

**Comment by RLHecht** [comment]
@megzehn This is ready for you to copyedit.

**Comment by laurwill** [comment]
@RLHecht this is copyedited.

**Comment by RLHecht** [comment]
Just sent this to the stakeholder

**Comment by RLHecht** [comment]
This is live. Closing ticket.
