### ISSUE TITLE
Hold On Support launch meeting to address questions/concerns

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#50939]
## User Story
As a Governance team member, I want to know and understand the new On Support guide and the overall process so that I can be confident in my ability to uphold the process..

Assignee: @shiragoodman 

## Description
Governance team is about to introduce a new process for responding to support requests on the #vfs-platform-support Slack channel, hosting Collab Cycle meetings and completing post-Collab Cycle meeting tasks. In order to ensure the full team is familiar and on board with the new process, we'll host a training session to walk the team through the new guidance and answer any questions or concerns they may have.

## Impacted Artifacts
[On-Support guide](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2454093924/On-Support+guide)

## Tasks
- [x] Schedule 1 hour training session with impacted team members (Brian, Allison, Sara, Cheryl and Ian)
   - Training session scheduled for Friday 1/20 at 10:30am ET 
- [x] Session walk through the On-Support guide and ensure everything is clear
- [x] Vote/discuss as a team the 2 existing comments in the guidance
- [x] Make changes to the guidance if necessary
- [x]  communicate on #platform-governance-team slack Channel when this on-support schedule is fully launched

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team members have been introduced to the new On-Support guide
- [x] Governance team members are familiar with their roles and responsibilities for supporting Governance team processes

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
On Support meeting held with Governance team on 1/20. We walked through the new [On-Support guide](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2454093924/On-Support+guide), made some minor adjustments, and agreed to launch the new process on Monday 1/23.
