### ISSUE TITLE
[FE] Allow Veteran to Cancel their Appointment during Pre-Check-in

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#50933]
## User Story
As a Veteran who has a Pre-Check-in link, I would like to cancel my appointment because I no longer need the appointment.
 
## Wireframes
- TBD

## Tasks
- [ ] [FE] Implement new feature
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
Closing; No longer doing this feature
