### ISSUE TITLE
[Research] Conduct 526EZ Heuristic Review (part 2 of 3)

### ISSUE THREAD

**Issue by Evafloyd** [department-of-veterans-affairs/va.gov-team#50961]
## Description
At the end of this ticket, our team will have conducted a heuristic review for the 526EZ experience. 

## Conduct heuristic review

- This is the meat of it, 2-4 reviewers per product using the[ documented heuristics](https://docs.google.com/spreadsheets/d/1L6MLFqAnn7FcK4LU4Nh1PCD04lhSZnu84XqHkamEp7E/edit#gid=0)

- Combine average scores and highlight areas of focus
This step allows us to remove some level of bias by having multiple people review the issues. Once notes have been compared and discussed, we’ll decide as a group which items are most critical for improvement.

### Tasks
- [ ] Conduct heuristic review (Skyler)
- [ ] Conduct heuristic review (Eva)
- [ ] Combine average scores and highlight areas of focus

## Measures 
In order to take a measured approach to our analysis, we'll employ a quantitative scale to provide quick visualization of how well an application “works.” By providing a scale for this work, we enhance the usefulness of our review. We use the gradations of degree to highlight the overall area. While there isn’t an exact line of demarcation among the values, we want to show more than mere pass or fail; for example, the application might just barely be acceptable in terms of findability, but it could be best in class in terms of clarity.

- Aligns system and real word
- Valuable
- Findable
- Clear
- Trustworthy
- Controllable
- Learnable
- Prevents Errors
- Frictionless

These areas have been adapted from Abby Coverts [Information Architecture Heuristics](https://abbycovert.com/ia-tools/ia-heuristics/), NNGs, and Service Design Heuristics.

### Scale
As you complete the evaluation of your product or service, change the value of the 'Assessment' field for each measure. This field controls the Actual Score and Score %. Possible values for the measure include:

- Unusable: imperative to fix Unusable (0)
- Major issue: Important to fix with high priority Critical (1)
- Minor issue: should be given low priority Moderate (2)
- Cosmetic issue only Minor (3)
- Meets Criteria No Issues (Default Value) (4)

When we create a report, we concentrate on the evaluation of the main areas. We review the application in as best a manner as we can, scanning it several times from each of the areas. We take a lens-like focus on each area. 
As part of the analysis, we will also provide key examples for each area. However, we generally don’t provide an exhaustive list of every indication of positive or improvable areas.
