### ISSUE TITLE
Support: Mon-Thur Deploy (S17)

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#50970]
### User stories
As a Platform team member who just contributed to the Platform website,
I need my content published,
so that I can share my content updates with the intended audience.

As a content team,
we need to review any new content changes made on the platform,
so that we can deploy every Tuesday and Thursday of the week.

### Tasks
Someone from our team will use Scroll Viewport to publish changes to the website after 3pm EST on:

- [x] Wednesday (12/21) - Samara
- [x] Thursday (12/22) - Jill
- [x] Monday (12/26) - NO DEPLOY
- [x] Tuesday (12/27) - Brian (may need Lauren's help)
- [x] Wednesday (12/28) - Samara
- [x] Thursday (12/29) - Jill
- [x] Monday (1/2) - NO DEPLOY
- [x] Tuesday (1/3) - Brian (may need Lauren's help)

### Other Info
Rotating schedule:
https://vfs.atlassian.net/wiki/spaces/CIT/pages/2405171201/Deployment+rotation+schedule

Data tracking info:
https://vfs.atlassian.net/wiki/spaces/CIT/pages/2282979860/KPIs+-+Content+Support
