### ISSUE TITLE
Meet with Governance to discuss orientation for VFS customers

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#50978]
### Tasks

- [x] Schedule a meeting with Shira about task to create a Platform website orientation for VFS customers
- [x] Ask her opinion on how to integrate this with the existing orientation for VFS team members
- [x] Document meeting highlights and next steps/action items

### Info
Team initiative notes: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2477621264/FY2023+Q2+Platform+website+orientations

1/24/23 meeting takeaways:

- Look through general orientation deck for current information about the Platform website: https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions
- Governance is trying to move away from slide decks format and transition to something else.
- We (platform content) will be video guinea pigs; If content is too long, break up topics into smaller chunks
- For informational knowledge, we can attend the next general orientation: Tuesdays, February 14
- Circle back with Shira about how to incorporate our video as part of their VFS orientation takeaway documents, process.
- Look through Confluence for YouTube guidance: https://vfs.atlassian.net/wiki/spaces/LEAD/pages/1847820659/Platform+YouTube+channel
