### ISSUE TITLE
Pass along sanitized branch name from vets-website and vets-api PE workflows

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#50987]
## Issue Description
We'll be using the branch name to construct preview environment URLs. However, as branches are user-entered, they may contain unfavorable characters when it comes to URLs. We should pass along an additional sanitized branch name in the [vets-website](https://github.com/department-of-veterans-affairs/vets-website/blob/main/.github/workflows/preview-environment-deployment.yml) and [vets-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.github/workflows/preview_environment_deployment.yml) workflows to be used in URL construction. This can be handled in the existing script that sets the branch and source repo names. This data should then be passed to the [devops workflow](https://github.com/department-of-veterans-affairs/devops/blob/master/.github/workflows/preview-environment-deployment.yml)

---
## Tasks
- [x] Implement a third variable being set in the script in vets-website to define a sanitized branch name.
- [x] Implement a third variable being set in the script in vets-api to define a sanitized branch name.
- [x] Add this variable to the data that is passed to the devops workflow in the vets-website workflow
- [x] Add this variable to the data that is passed to the devops workflow in the vets-api workflow
- [x] Update the devops workflow to receive this variable from the client payload and set it to the environment.

## Acceptance Criteria
- [x] A sanitized branch name, containing no unsafe characters for URLs is being passed to every devops PE launch workflow.

**Comment by CBonade** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/23003 vets-website
https://github.com/department-of-veterans-affairs/devops/pull/12382 devops
https://github.com/department-of-veterans-affairs/vets-api/pull/11428 vets-api

These branches are ready to merge once they receive approvals. The new sanitized branch name will be available in the devops workflow defined on the environment as: `SOURCE_REF_SANITIZED`. This can be utilized in the construction of the manifest or wherever else we might need the url constructed.

**Comment by pjhill** [comment]
All merged and squared away, nice!
