### ISSUE TITLE
[SPIKE] [FE] Improve testing and validation with staging and screenshots

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#50989]
TIMEBOXED to 2 DAYS

## User Story
As a stakeholder, I want to easily see recent changes made to the app so that I can verify that those changes are correct and keep design artifacts up to date.

## Tasks
- [ ] Contact platforms to discuss possibility of capturing and storing screenshots on deployments
- [x] Investigate cypress tool for doing visual regression testing
- [x] Create issue(s) for adding workspace isolated cypress visual regression tests

**Comment by loripusey** [comment]
@wullaski it doesn't look like we got to this over that last 2 sprints, ok if I put it back on the backlog?
cc: @sarahknoppA6

**Comment by wullaski** [comment]
I created a [proof of concept](https://github.com/department-of-veterans-affairs/vets-website/tree/check-in/50989/visual-regression-testing) where the code and testing is isolated within our app and not part of integration testing. It is implemented within our workspace so it doesn't install any new Node packages globally.

The FE team could use this to check for any unintended visual changes before pushing code.

### Use Cases
- Testing an update to the design system
- Catching bugs caused by component library changes
- Checking for any unintended visual changes due to a large refactor
- Validate work by quickly and easily seeing what changed
- Quickly generating only the necessary screenshots for validation instead of all of them
