### ISSUE TITLE
Update booster age content on COVID-19 booster shots page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#50988]
## Issue Description

A stakeholder reached out with changes to our [COVID-19 booster shots](https://www.va.gov/health-care/covid-19-vaccine/booster-shots-and-additional-doses/) page we need to make about the age when people are eligible for boosters.

The recommended update is to change the first sentence under the H2 "Getting a booster shot" to the following:

The CDC recommends that most everyone who is at least 6 months and older get an updated (bivalent) booster shot. 

We should review for plain language and VA.gov style before publishing.

## Tasks
- [x] Update content in Drupal
- [x] Copyedit (Megan)
- [x] Publish (Megan)
- [x] Open translation ticket (Randi)

## Acceptance Criteria
- [x] New content is live on the site

**Comment by RLHecht** [comment]
@laurwill I made this update but I tweaked the language slightly from what the stakeholder had suggested. Let me know if you think it looks OK. Thanks!

**Comment by RLHecht** [comment]
Laura published this. Will send translators updated sentence.

**Comment by RLHecht** [comment]
I sent the translators an email with the new sentence. Closing ticket.
