### ISSUE TITLE
Design | Profile | Notification settings | Finish research plan for adding email channel

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#50999]
## Background

As our list of notification groups and options grows, users will have to scroll through a lengthy page to get a sense of the notifications that are available. We need to evaluate how our current design serves users as the list grows. This issue covers the completion of a research plan for our study.

- [Research brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/discovery-and-research/usability-study-add-email-jan-2023/README.md)
- [Research plan draft](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/discovery-and-research/usability-study-add-email-jan-2023/research-plan.md)

## Tasks
- [x] Finish draft of research plan
- [x] Review with PO
- [x] Incorporate edits
  

## Acceptance Criteria
- [x] Plan complete and ready for submission

## Associated Tickets
- #51007
- #51000
- #51001
- #51002 
- #51003 
- #51004 
- #51005 
- #51006

**Comment by andaleliz** [comment]
Hi @Samara-Strauss, the draft of the [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/discovery-and-research/usability-study-add-email-jan-2023/research-plan.md) is ready for your review. From there, you'll find links to the prototype and conversation guide too. 

After estimating the time for each task, I think we're in great shape to evaluate the following, even in a screenreader session.
- current auto-save pattern
- a read/edit version
- the flow of adding an email address

My plan is to alternate which prototype people see first so we don't end up wondering if people prefer the same one over the other just because they saw it first.

As you go through the conversation guide, start with the read/edit prototype and follow that path.  I'm still tweaking the autosave version and may or may not be done when you get to it.

I'm excited for your feedback - thanks in advance!

**Comment by Samara-Strauss** [comment]
### Research plan

Looks great! No real notes, though I would be interested in a little larger of an age range. Personally, I think it makes sense to test people that are both younger and older to see if that makes a difference, but if you feel strongly about 55+ only, it's not a requirement that you change that.

### Convo guide

Also looks great!! 😃😃😃

### Prototypes

These look great, too, but I noticed that they don't have the explicit opt-out option any more. Can you please check with Bev and Melanie about whether explicit opt-out is required? This would definitely change the pattern if we need to keep it.

**Comment by andaleliz** [comment]
@Samara-Strauss I don't feel super strongly about the age range as along as we get _some_ participants over 55. I'll update that piece.

I talked to Bev and Melanie about that back in July ([notes here, see number 7](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/discovery-and-research/default-send/july-2022-notes.md)) and will confirm with them that these notes are still accurate. Definitely changes things if not.

**Comment by Samara-Strauss** [comment]
> I talked to Bev and Melanie about that back in July ([notes here, see number 7](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/discovery-and-research/default-send/july-2022-notes.md)) and will confirm with them that these notes are still accurate. Definitely changes things if not.

Thank you for refreshing my memory on this! I completely forgot. This is great news. One point based on your notes:

> If we use the new default send flag in combination with the permission value for a notification (communication item), we can determine whether or not a person has explicitly opted out.

We haven't updated notification preferences to consume the default opt-in indicator yet, so I will make sure this gets into long-term planning since it's a dependency for updating the designs in the way you've outlined (which I think is an intuitive pattern that people will expect, and the direction we should go).

**Comment by andaleliz** [comment]
> We haven't updated notification preferences to consume the default opt-in indicator yet, so I will make sure this gets into long-term planning since it's a dependency for updating the designs in the way you've outlined (which I think is an intuitive pattern that people will expect, and the direction we should go).

Awesome! Yes, I figured that hadn't been implemented yet. Good idea to get it into the plan.

Also, you should be aware that the read/edit pattern in the prototype is not technically possible right now. The way the API works, it can only save one notification at a time, so we wouldn't be able to manage two notification channels (email and text) with one save button. I figured we should go ahead and get feedback; that way if we determine the read/edit pattern IS better for Veterans, we have some user data to back up the request for VA Profile to update their API.

I'm thinking we can go ahead and submit all of this to kick off recruiting with Perigean. The plan and conversation guide would stay the same if we do need to add the explicit opt-out back, and we'll have plenty of time to make any necessary updates to the prototype.

Can you please confirm you're ok with that? Once I hear back I'll close this out and submit everything to Shane.

**Comment by Samara-Strauss** [comment]
I am OK with this. Once we get feedback, we can talk to VA Profile about it. We'd need to fill out an intake for them to make this kind of update, but that's OK. They'll prioritize it accordingly in their backlog, and we can work with them to make sure it's updated by the time we need it on the frontend.

**Comment by andaleliz** [comment]
Makes sense to me. I've submitted the plan to kick off recruiting.

**Comment by Samara-Strauss** [comment]
Great! Thank you!
