### ISSUE TITLE
[Evidence Service to Lighthouse]: Epic

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#50991]
As part of the upcoming migration away from EVSS to Lighthouse APIs, we need to update the Evidence Service to Lighthouse
# Tasks

### Preliminary
- [x] #49503
- [x] #49505
- [ ] #49508
- [x] #50028
- [ ] #50030

### Administrative

- [ ] #50986

### Frontend Only
- [ ] #50036

### Frontend and Backend
- [x] #49863 
- [ ] #50034
- [ ] #50038
- [ ] #50037 
- [ ] #50076

# Acceptance Criteria

- [ ] Swap EVSS end point URLs with new Lighthouse URLs
- [ ] CST is ready for functional testing using new API services
- [ ] Necessary feature flags in place to enable functional testing in appropriate environments
- [ ] In coordination with Lighthouse, verify, jointly, all services are working correct and calls are successfully made.
- [ ] Verify that the correct attributes are being sent back via the end user UI.

# open questions
- is this a staged rollout? 25/50/75
- How are we supporting the 5013 waiver? Are we supporting it at all?
