### ISSUE TITLE
[Letters app to Lighthouse]: Epic

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#50994]
As part of the upcoming migration away from EVSS to Lighthouse APIs, we need to update the Letters App to Lighthouse
# Tasks

### Preliminary
- [ ] [Evidence Service to Lighthouse] Backend code review
- [ ] [Evidence Service to Lighthouse] Get to the point we can make a request to Lighthouse in sandbox
- [ ] [Evidence Service to Lighthouse] map attributes
- [ ] [Evidence Service to Lighthouse] get sandbox credentials to enable testing
- [ ] [Evidence Service to Lighthouse] determine who is using our existing services

### Administrative
- [ ] [Evidence Service to Lighthouse] co-create release plan with Lighthouse

### Frontend Only
- [ ] [Evidence Service to Lighthouse] modify FE code to use feature toggle

### Frontend and Backend (do we need these)
- [ ] [Evidence Service to Lighthouse] Create feature toggle for Evidence Service to Lighthouse claims migration
- [ ] [Evidence Service to Lighthouse] create fixtures
- [ ] [Evidence Service to Lighthouse] testing/qa, unit tests for all endpoints
- [ ] [Evidence Service to Lighthouse] clean up old code after release
- [ ] [Evidence Service to Lighthouse] sentry and datadog monitoring

# Acceptance Criteria

- [ ] Swap Evidence Service end point URLs with new Lighthouse URLs
- [ ] CST is ready for functional testing using new API services
- [ ] Necessary feature flags in place to enable functional testing in appropriate environments
- [ ] In coordination with Lighthouse, verify, jointly, all services are working correct and calls are successfully made.
- [ ] Verify that the correct attributes are being sent back via the end user UI.

# open questions
- is this a staged rollout? 25/50/75
- How are we supporting the 5013 waiver? Are we supporting it at all?

**Comment by jerekshoe** [comment]
@sortizsh You can just copy this across to the other ticket. These should be about right
