### ISSUE TITLE
[BE] - Send reason for appointment data to the front end

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#50996]
## BLOCKED
The work that the PCI/API team needs to do is a lot priority right now.

## PCI/API Ticket
[Dependent ticket](https://app.zenhub.com/workspaces/pci-api-6149f6401b0b3c001219802f/issues/gh/department-of-veterans-affairs/chip/1487)

## Summary
Send reason for visit data to the frontend in the appointment payload. This is for the new details display.
[pre-check-in abstract](https://app.abstract.com/projects/d9d1d6b4-192b-4ee6-95ab-e7cf42a1ac03/branches/1bd0608c-d162-4fc7-82dd-cee391cdb173/collections/ede93220-c041-47f2-8d32-bb53f3139dde?collectionLayerId=&mode=)
[day-of abstract](https://app.abstract.com/projects/ab30c34e-e2f9-4d3e-bb96-3b683b006c24/branches/0240c5f8-14e4-4b87-8cde-cd1de046993f/collections/a7738beb-2c4a-44ad-b7f4-4ec19cbbe51a?collectionLayerId=&mode=)

## Tasks
- [ ] [BE] Modify serializer for sending Reason for visit & booking note to the front end
- [ ] [BE] Add rspecs for the changes

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by loripusey** [comment]
chances of this happening are very low, closing for now
