### ISSUE TITLE
[FE] - Pre-check-in create new details page and design updates

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#50993]
## Summary
Using the feature toggle `check_in_experience_vaos_details` add new components for the VAOS design updates and details page. 

For the appointment details it may make sense to set an active appointment key in state and then select all of the appointments from redux and display the data from the matching key on the details page. Rather than setting a whole appointment in state like the check-in page on day-of does. This should make paging through appointments easier if we decided to add that in the future.

Here is some info from Ben relating to the directions link:
In many apps across VA health, facilities often include a directions that, which populates the address in Google for directions. Here is an example on public web: 

https://www.va.gov/maryland-health-care/locations/baltimore-va-clinic/

The VAOS team has implemented this feature as follows: 

> VAOS is pulling the facility from the API response and populating the address in Google for the directions. 

```
<NewTabAnchor
        href={`https://maps.google.com?saddr=Current+Location&daddr=${address}`}
        aria-label={`Directions to ${location.name ||
          location.providerPractice}`}
      >
        Directions
</NewTabAnchor>
```

Here is a [slack thread](https://dsva.slack.com/archives/CMNQT72LX/p1671056347710829) to continue this conversation with VAOS, as needed. 

## Links
[abstract](https://app.abstract.com/projects/d9d1d6b4-192b-4ee6-95ab-e7cf42a1ac03/branches/1bd0608c-d162-4fc7-82dd-cee391cdb173/collections/ede93220-c041-47f2-8d32-bb53f3139dde?collectionLayerId=&mode=)
## Tasks
- [ ] [FE] - Create new introduction page components
- [ ] [FE] - Create new complete page components
- [ ] [FE] - Create details page
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
this work is merged but there is still outstanding work with new fields and other minor details. Will bring up validation as PL tomorrow.
