### ISSUE TITLE
[FE] - Create feature toggle check_in_experience_updated_appt_presentation

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#50992]
## Summary
Create  a feature toggle for the new VAOS style appointment details work.

## Tasks
- [ ] [FE] - Create feature toggle
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by acrollet** [comment]
@brianseek I changed the ff name to avoid someone thinking that we were pulling in details from vaos or the like.

**Comment by acrollet** [comment]
backend PR is here: https://github.com/department-of-veterans-affairs/vets-api/pull/11431

**Comment by brianseek** [comment]
@acrollet good call on the name change!

**Comment by acrollet** [comment]
PR has been merged, not really anything to validate at this time so I've closed this.
