### ISSUE TITLE
[FE] - Day of check-in create new details page and design updates

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#50995]
## Summary
Using the feature toggle `check_in_experience_vaos_details` add new components for the VAOS design updates and details page. 

Re-use components from the [pre-check-in work](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/50993) if possible.

## Links
[abstract](https://app.abstract.com/projects/ab30c34e-e2f9-4d3e-bb96-3b683b006c24/branches/0240c5f8-14e4-4b87-8cde-cd1de046993f/collections/a7738beb-2c4a-44ad-b7f4-4ec19cbbe51a?collectionLayerId=&mode=)

## Tasks
- [ ] [FE] - Create new appointments page components
- [ ] [FE] - Create details page
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
this work is merged but there is still outstanding work with new fields and other minor details. Will bring up validation as PL tomorrow.
