### ISSUE TITLE
Design | Profile | Notification settings | Final logistics for adding email channel

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#51002]
## Background

As our list of notification groups and options grows, users will have to scroll through a lengthy page to get a sense of the notifications that are available. We need to evaluate how our current design serves users as the list grows. This issue covers the final logistics of setting up the study before we begin research

## Tasks
- [x] Submit research plan
- [x] Meet with Perigean to discuss recruitment criteria
- [x] Confirm recruiting has been kicked off
- [x] Create observer Mural board
- [x] Schedule debrief sessions w/ team
  

## Acceptance Criteria
- [ ] All tasks are complete

## Associated Tickets
- #50999
- #51000
- #51001
- #51003
- #51004
- #51005 
- #51006

**Comment by andaleliz** [comment]
Met with Perigean and we are aligned on criteria. @Samara-Strauss just FYI I updated the criteria in two ways:
1. Reduced requirement for cognitive impairment from all participants to 8 of 12. Hopefully this will speed up recruiting
2. Asked that 6 participants identify as other than caucasian, so we have a diverse group of people. We didn't have any criteria around this previously (my bad).
