### ISSUE TITLE
Design | Profile | Notification settings | Create conversation guide for adding email channel

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#51000]
## Background

As our list of notification groups and options grows, users will have to scroll through a lengthy page to get a sense of the notifications that are available. We need to evaluate how our current design serves users as the list grows. This issue covers the creation of a conversation guide for our study.

## Tasks
- [x] Draft conversation guide
- [x] Review with PO
- [x] Incorporate edits
  

## Acceptance Criteria
- [ ] Guide complete and ready for submission

## Associated Tickets
- #50999
- #51001
- #51002
- #51003

**Comment by andaleliz** [comment]
Complete. https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/discovery-and-research/usability-study-add-email-jan-2023/conversation-guide.md
