### ISSUE TITLE
Design | Profile | Notification settings | Share research for adding email channel

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#51006]
## Background

As our list of notification groups and options grows, users will have to scroll through a lengthy page to get a sense of the notifications that are available. We need to evaluate how our current design serves users as the list grows. This issue covers the sharing of research once we've published our final report

## Tasks
- [x] Create presentation deck
- [x] Share findings with product team
- [x] Share findings with stakeholders (MHV team? VA Profile? VA Notify?)
- [x] Get on schedule for Monday design meeting
  

## Acceptance Criteria
- [ ] All tasks complete

## Associated Tickets
- #50999
- #51000
- #51001
- #51002
- #51003
- #51004
- #51005

**Comment by andaleliz** [comment]
[2023-profile-add-email-channel-findings-summary.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/10699117/2023-profile-add-email-channel-findings-summary.pdf)
