### ISSUE TITLE
Sentry Data - Discovery

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#51026]
## Issue Description
We want to add more data sources to our dashboards to make them more robust and provide additional insights to our VFS teams.  Sentry is one data source under consideration. Our first step is discovery to determine what data is available, can/how do we access and is it meaningful to our VFS teams.  If we decide to move forward we will create another ticket for implementation.

Resources:
[Sentry.io](https://sentry.io/welcome/)
[Data platforms overview](https://docs.google.com/spreadsheets/d/1ucM62P8HQrpn7uO6s45k3jNKECwcwT5tw1kOLpCx3ZA/edit#gid=2497302)
[Slack convo with Bentley]( https://dsva.slack.com/archives/C1Q4294JJ/p1671555885492779)
[Domo datasets](https://va-gov.domo.com/datacenter/datasources)

---
## Tasks
- [ ] Get Sentry access 
- [ ] Review Sentry - what it is, how we us it, what data does it collect
- [ ] Document findings and recommendations

## Acceptance Criteria
- [ ] We have reviewed Sentry and have information needed to decided if we should move forward with implementation.
---

**Comment by AdamOye** [comment]
Closin. Reason: Old request from 2022
