### ISSUE TITLE
Domo/GH Connector

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#51028]
## Issue Description
The github_issues dataset in BQ is feeding 3 domo dashboards  [Platform Github Tickets](https://va-gov.domo.com/page/835197588), [Collaboration Cycle](https://va-gov.domo.com/page/1340527018) and [Platform Website](https://va-gov.domo.com/page/189282309) unfortunately there is no longer a owner of this data.  We need to determine how we can pull in and own/manage the GH datasets in support of these dashboards.  This will allow us to make updates as needed (for example add 'Pipelines' and 'Milestones' fields to dataset as requested in this ticket #60605)  without dependencies on other teams.  

What is the best way to bring this data in? 
Domo GH connector? And bypass BQ?
Update current configuration in BQ and take over ownership? (Ryan Johnson would be the person to direct you on how to do that)

---
## Tasks
- [ ] Review [GH Connector](https://www.domo.com/appstore/app/github-quickstart/overview)
- [ ] Determine if we should use or not use based on findings - if no what should we use?
- [ ] Share findings (https://dsva.slack.com/archives/C1Q4294JJ/p1671555885492779)
- [ ] Set up data based on findings

## Acceptance Criteria
- [ ] Set up new GH data flow
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by dorseypa1** [comment]
I'll get started on it

**Comment by michelle-dooley** [comment]
@dorseypa1 - can you also confirm @ChristineYoungZA has all the same admin rights as you and I  for BQ, Domo and Google Cloud.  Your's are same as mine so you can grant her anything else she may need so she can set up these connections too. 

https://vfs.atlassian.net/wiki/spaces/AT/pages/1446084757/How+to+-+BigQuery+Permission+Granting

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/93597659/8686797e-273e-4063-8f41-8df7b54b0382)


https://console.cloud.google.com/iam-admin/iam?project=vsp-analytics-and-insights

https://console.cloud.google.com/bigquery?project=vsp-analytics-and-insights&ws=!1m5!1m4!4m3!1svsp-analytics-and-insights!2svsp_sites!3svw_forms_engagement
https://va-gov.domo.com/admin/people

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/93597659/3f74e294-207e-4e02-9cea-ce92bc9be3a4)

**Comment by dorseypa1** [comment]
Will do

**Comment by michelle-dooley** [comment]
Sprint update: not completed, will move to another sprint.

**Comment by AdamOye** [comment]
This item can be deleted, Reason: Completed/outdated
