### ISSUE TITLE
Review past production incidents for alerting effectiveness

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#51036]
## User Story
As a CIE stakeholder, I wish to know the percentage of incidents that have been identified by automated alerting, so that I may plan for optimal production support.

## Tasks
- [ ] Review production incidents for the past month and determine the percentage that were identified by:
  - automated alerting
  - field reports
  - proactive monitoring by humans
  - other
- [ ] Summarize on this ticket and socialize with the CIE team
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
