### ISSUE TITLE
Automate day-end summaries

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#51034]
## User Story
As a CIE stakeholder, I wish to receive an accurate and timely summary of check-in success rates on a daily basis, so that I may easily understand how the application is performing.

## Background

We have a [script](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/analytics/scripts/day_end_summary/summary.py) available to do the day-end summary. This task is to automate running the script and posting output to the production support Slack channel every day at 2000 ET.

## Tasks
- [ ] Automate posting
- [ ] Automate infra deployment [with terraform](https://dsva.slack.com/archives/C02UP02HHGX/p1671565738012689?thread_ts=1671553507.738249&cid=C02UP02HHGX) if possible
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
