### ISSUE TITLE
Datadog Data - Discovery

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#51038]
## Issue Description
We want to add more data sources to our dashboards to make them more robust and provide additional insights to our VFS teams.  Datadog is one data source under consideration. Our first step is discovery to determine what data is available, can/how do we access and is it meaningful to our VFS teams.  If we decide to move forward we will create another ticket for implementation.

Resources:
[Datadog Confluene docs](https://vfs.atlassian.net/wiki/spaces/OT/pages/2236612646/Monitor+things+with+DataDog)
[datadoghq.com](
https://www.datadoghq.com/)
[Access Datadog dashboards](https://vfs.atlassian.net/wiki/spaces/AMT/pages/2290155533/Access+Datadog+dashboards)
[Datadog dashboard links](https://vfs.atlassian.net/wiki/spaces/TT2/pages/2430599197/Datadog+Dashboards)

---
## Tasks
- [ ] Get [Datadog access](https://vfs.atlassian.net/wiki/spaces/OT/pages/2233598117/Get+access+to+Datadog)
- [ ] Review Datadog - what it is, how we us it, what data does it collect
- [ ] Review Datadog dashboards - Should we pull data into Domo or provide link within Domo to access?
- [ ] Document findings and recommendations

## Acceptance Criteria
- [ ] We have reviewed Datadog and have information needed to decided if we should move forward with implementation.

**Comment by AdamOye** [comment]
Closing this issue out we have ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/109110 In replacement
