### ISSUE TITLE
Domo Data & Dashboard - Clean Up

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#51086]
## Issue Description
The Platform Analytics team has been building dashboards in Domo for nearly 3 years, encompassing many versions of the team and its data practices. There are many dashboards built in the early days of Domo that are either 1) no longer used or 2) should no longer be used, due to lack of quality checks of the data. In addition, the large and unwieldy menu of dashboards in Domo can be overwhelming to the constant stream of new VFS teams and team members, who struggle to find what resources are available and how useful they may be.

We want to KEEP:
- Standardized Forms, Search, Content dashboards
- Edge Case dashboards created after standardization initiative (summer 2021)
- High-level dashboards and reports currently sent to VA stakeholders
- Dashboards created by other Platform teams for internal or VFS use

We want to DELETE:
- Pre-standardization initiative custom dashboards for VFS or VA stakeholders
- Dashboards built for temporary purposes

Artifacts:
[Domo Dashboard Engagement](
---https://docs.google.com/spreadsheets/d/17jiWEsN0plZXitlRnp45TSvnu2DWk-r3zKcP3GZFIfM/edit#gid=0)
[Domo Dashboard Engagement Data Source](https://va-gov.domo.com/datasources/5006297e-5cc6-4655-90f6-c1a2cc2bab49/details/overview)
[KPI dashboard request flowchart](https://docs.google.com/presentation/d/16mRcslbkWtW44rlsfQGXZnHtQ3GoLjn6GpFnd3Gvva8/edit#slide=id.p)

## Tasks
- [ ]  Identifying which dashboards count as out of data and should be deleted.
- [ ] Research into Activity Log data to determine whether these dashboards are currently being used and if so, by whom.
- [ ] Outreach to teams or individuals currently using dashboards to be deleted, including:  Explanation of why this dashboard is being sunset, instructions for how to get an up-to-date dashboard (i.e. do they qualify for standardized, edge case, etc.), date when dashboards will be deleted. 
Note:  Dashboards not currently in use can likely be deleted without outreach, as this may cause confusion for VFS teams who didn’t know about them in the first place. (However, Analytics team may choose to reach out anyway for engagement reasons)

## Acceptance Criteria
- [ ] We have removed/sunset datasets and dashboards as applicable based on above and we have organized the remaining as applicable.
---

**Comment by michelle-dooley** [comment]
began work on this but waiting on Domo to provide additional data for us to complete.
