### ISSUE TITLE
My VA: Sprint 6 (3/15/23 - 3/28/23)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#51093]
## Priorities
_At the end of this sprint, what do we want to have accomplished/delivered?_
1. My VA Audit: All outstanding QA and Google Analytics issues are resolved
2. My VA Audit: Recruiting for UAT underway
3. Notification Center discovery: research review + planning

## My VA Audit UX Improvements (#41934)
**PM**
- [x] #50646 
- [x] #54517
- [x] #53000 (in validation with PM)
- [ ] #51823

**Design/Research**
- [ ] #55171 (only when all QA and Google Analytics issues are resolved)

**FE**
- [x] #54437 _from previous sprint_
- [ ] #54387 _from previous sprint_
- [x] #54391 _from previous sprint_
- [x] #54394 _from previous sprint_
- [ ] #49094 
- [x] #54786
- [x] #54792
- [x] #54778

## On-site Notifications (#50758)
**PM**
- [x] #52916
- [x] #55186

**Design/Research**
- [x] ~#55189~
- [ ] #55246
- [x] #55245

## My VA 2.0 General Enhancements (#31611)
**FE**
- [x] #54402 _from previous sprint_

**Comment by ajakabcin** [comment]
Hi team - here is the order of operations for the sprint based on priorities:

In general, we need to prioritize all development work for My VA audit first so that we can get the UAT process started. All other feature work comes after that.

## Engineers
@allisonlu 
- Resolve QA items from previous sprint: [54437](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54437) and [54387](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54387)
- Move to GA event tag ticket(s): [54786](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54786) (shadow with Derrick)
- Error state on messaging endpoint [54778](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54778)
- Start new component build [48726](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48726)

@dellerbie 
- Shadow with Allison on [54786](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54786)
- Fix GA event tag issue on "Review your messages" link [54792](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54792)
- Implement full page error state [49094](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49094)
- Finish review of E2E tests [54402](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54402)

## Research/Design
@aagosto90 
- Start notification discovery prep work: [55246](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55246) and [55245](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55245)
- Design intent on notification component (if needed, but unlikely it will be): [55189](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55189)
- _When QA and GA issues are complete, and team completes UAT go/no-go, then ok to proceed with_ [55171](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55171)

cc @BerniXiongA6

**Comment by Samara-Strauss** [comment]
Great job on completing sprint goals, Team!
