### ISSUE TITLE
My VA: Sprint 4 (2/15/23 - 2/28/23)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#51091]
## Priorities
_At the end of this sprint, what do we want to have accomplished/delivered?_
1. Complete QA for My VA Audit Updates (and resolve any findings) 
2. Build Backlog for Onsite Notifications v2

PTO
-  Presidents' Day Monday, 2/20 - federal holiday, Samara and A6 off 
- **AJ:** 2/16 - 2/20
-  **Samara**: In Austin and mostly unavailable 2/21 - 2/24

## My VA Audit UX Improvements (#41934)
**PM**
- [x] #50645
- [x] #53341
- [x] #50647
- [x] #53705
- [ ] #50646 

**Design/Research**
- [x] #53341
- [x] #53706
- [ ] #53000 (continue work as time permits)
- [ ] Address any findings from QA - _will create tickets as needed_

**FE**
- [x] #53341
- [x] #53706 
- [x] #53744
- [x] #53765
- [ ] Address any findings from QA - _will create tickets as needed_

## On-site Notifications v2 (#50758)
_Majority of the work in this section is pending information we receive from our partners on VA Notify and Vetext_

**PM**
- [ ] #51423
- [ ] #53707
- [ ] #52916 (from previous sprint)

**Research & Design**
- [ ] #52928

## My VA Payment Info V2 (#43332)

**PM**
- [x] #51809 (from previous sprint)

## General 
- [x] #51896 
- [x] #52619 (from previous sprint - validation only)
- [ ] #52899

**Comment by ajakabcin** [comment]
Hi @allisonlu  and @aagosto90! Here's an order of operations based on priorities for this sprint, please let me know if you have any questions!

**Frontend** - Allison
1. Knock out the drupal code/flag clean-up so we don't block Public Websites: #51896 
2. GA event investigation/implementation: #53744 + #53765 
3. QA My VA Audit improvements: #53341 
4. A11y staging review prep work: #53706 

**Research/Design** - Angela
1. QA My VA Audit improvements: #53341 
2. Finish My VA use case documentation & flows: #53000
3. QA My VA Audit improvements: #53341 
4. Design & copy updates for onsite notifications v2: #52928
