### ISSUE TITLE
My VA: Sprint 12 (6/7/23 - 6/20/23)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#51100]
## Priorities
_At the end of this sprint, what do we want to have accomplished/delivered?_
1. Notification Component: Complete QA, staging PSIR reviews
2. Notification Center: Design intent (stretch - FE documentation)
3. Claims status EVSS > Lighthouse: implementation 

PTO
- Juneteenth Federal Holiday (6/19)
- AJ 6/12 - 6/13

# Onsite Notifications

## Notification Component (#59398)
**PM**
- [ ] #59037 (_from previous sprint_)
- [x] #58779 (_from previous sprint - waiting for response from platform_)
- [ ] #58778 (_from previous sprint_)
- [ ] #59692

**FE**
- [x] #57714 (_from previous sprint_)
- [ ] #59544
- [ ] #54812 (_from previous sprint_)

## Notification Center (#58425)
**PM**
- [x] #58427

**Design/Research**
- [x] #58921
- [x] #58427
- [ ] #58419

**BE**
- [x] #58316 (_from previous sprint_)

**FE**
- [x] #58634 (_from previous sprint_)

## Onsite Notifications v2 (#50758) 
- [x] #60315 

# My VA

## Claim Status EVSS > Lighthouse (#54403)
**FE**
- [ ] #59410 

## My VA Audit UX Improvements (#41934)
**PM**
- [x] #57991 (_from previous sprint - open for validation purposes only_)

**FE**
- [x] #59400
- [x] #59054 

## Payment Info v2 (#43332)
**FE**
- [x] #47243 (_from previous sprint_)

**Comment by ajakabcin** [comment]
Dev order of operations based on priorities 😎 

@allisonlu 
- Finish payment info v2 code cleanup ticket #47243 
- Fix notification component bug re "close" text #59544 
- While waiting for DS and vets website deployment, continue with notification center technical discovery ticket #58634 
- Implement component on My VA #54812 

@dellerbie 
- Finish health care component unit tests ticket #59054 
- Resolve the claims and appeals event tags issue #59400 
- Claims status EVSS > Lighthouse #59410
