### ISSUE TITLE
Implement & Track Metrics

### ISSUE THREAD

**Issue by sarahknoppA6** [department-of-veterans-affairs/va.gov-team#51109]
Info in this ticket was copied from another metrics ticket. Please validate and update tasks accordingly before starting on the work.

## Tasks

- [x] Identify metrics to track (that gauge success and/or feedback from Veterans) 
- [x] Circulate metrics with check in team
- [x] Make sure GA events (or clicks, bounce rates) are set up to track interactions. If needed, add widget to GA dashboard to track success. Or, provide link to GA view on where metrics will be tracked. 
- [x] Add events into [GA event spreadsheet](https://docs.google.com/spreadsheets/d/1BPOlI6vzH-tMTswvUrci3Q0NkBmfIIfo8Cgj_nM10gk/edit#gid=0)
- [x] Document rollout plan
- [x] Circulate rollout plan with check in team 
- [x] Track performance during rollout

## AC

- [x] Metrics identified
- [x] CIE team signed off on metrics
- [x] CIE team signed off on rollout plan

**Comment by sarahknoppA6** [comment]
@benbrasso-agile6 please look this one over so we can get it pointed and ready for next sprint- thank you!

**Comment by benbrasso-agile6** [comment]
GA Metrics

Pre-check-in:
% change (compared to current appts design) of /intro pageviews vs. clicks on "get started" link

Secondary metrics to monitor: detail page pageviews, clicks on directions and phone number on detail pages

Check in:
% change (compared to current appts design) of Your Appointments page vs. successful check ins

Secondary metrics to monitor: detail page pageviews, clicks on "check in now" button and phone number from detail pages

And then, we'll plan to do daily readouts to monitor the % change and increase rollout from there.

**Comment by loripusey** [comment]
can we close this @benbrasso-agile6

**Comment by benbrasso-agile6** [comment]
I'd like to keep it open and track success in here once we release this to production

**Comment by benbrasso-agile6** [comment]
Need to set up a widget in GA or make sure we have a way of easily viewing success

**Comment by benbrasso-agile6** [comment]
nav-check-in-pre-check-in-viewed-introduction-VAOS-design

nav-check-in-pre-check-in-started-in-person-VAOS-design
nav-check-in-pre-check-in-started-phone-VAOS-design


nav-check-in-pre-check-in-viewed-introduction-non-VAOS-design

nav-check-in-pre-check-in-started-in-person
nav-check-in-pre-check-in-started-phone




nav-check-in-check-in-viewed-appointment-list-VAOS-design

nav-check-in-check-in-viewed-appointment-list-non-VAOS-design

Then, look for API success

**Comment by benbrasso-agile6** [comment]
Will need FE to take this ticket - https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/54608

**Comment by benbrasso-agile6** [comment]
Tracking here https://docs.google.com/spreadsheets/d/11f1nNU7vIuPCTp6a7841721qQnZTdUgW9S-He7-MVu0/edit#gid=0
