### ISSUE TITLE
[BE] Profile: Discovery -- Migrating direct deposit for comp & pen integration to Lighthouse

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#51103]
### Background

[Project outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit/evss-lighthouse-migration#readme)

Eventually, EVSS will be retired. Support for direct deposit for comp & pen has been moved to the Lighthouse platform, so we need to migrate our direct deposit integration. This ticket intends to capture discovery around this work, so we can scope it and plan the effort.

### Tasks

(This likely needs to be groomed and may need to be broken into smaller tickets)

- [x] Review [project outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit/evss-lighthouse-migration#readme) and [Slack thread](https://dsva.slack.com/archives/C02CQP3RFFX/p1670963804155299)
- [x] Regroup with developers from Lighthouse (we can determine who)
- [x] [Review documentation on deverloper.va.gov](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit/evss-lighthouse-migration#readme) and [API documents on max.gov](https://community.max.gov/pages/viewpage.action?pageId=2286748585)
- [x] [Request sandbox access](https://developer.va.gov/onboarding/request-sandbox-access)
- [x] Determine scope of backend work
- [x] Determine if backend data would come back differently enough that it would affect design/frontend
- [x] Create tickets to support this work
- [x] Discuss scope/timeline estimate with product PM and Samara

### Acceptance criteria

- [x] Work has been appropriately scoped and ticketed.

**Comment by Samara-Strauss** [comment]
Estimate: 8

**Comment by Samara-Strauss** [comment]
@tpharrison can I close this out? I know not all tickets have been created, but since you made a list of them in #51900, you can work with Berni over time to get them created as needed.
