### ISSUE TITLE
My VA: Sprint 14 (7/5/23 - 7/18/23)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#51102]
## Priorities
_At the end of this sprint, what do we want to have accomplished/delivered?_
1. Notification Component: Position notification component for release (resolve launch blocking issues, wait for analytics work from DST)
2. Notification Center: MVP accessible on staging
3. My VA CST: finish dev, test, PSIRR

PTO
_Samara returns from parental leave! (7/11)_
- Tom 7/5 - 7/6, 7/14
- Angela 7/10 - 7/14

# Onsite Notifications

## Notification Component (#59398)
**Design**
- [x] #61388

**FE**
- [ ] #61399
- [x] #60661 (_validation only_)
- [ ] #60845 (_validation only - dependent on DST team's [1803](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1803)_)

## Notification Center (#58425)
**BE**
- [x] #60454 (_from previous sprint_)
- [ ] #60639

**FE**
- [x] #60398 (_from previous sprint - blocking 60399_)
- [ ] #60399 (_from previous sprint_)
- [ ] #60400
- [ ] #60438 

# My VA

## Claim Status EVSS > Lighthouse (#54403)
**PM**
- [ ] #61313
- [x] #54714

**FE**
- [x] #59410 (_from previous sprint_)
- [x] #54714

## My VA Audit UX Improvements (#41934)
**Design**
- [x] #57394

**FE**
- [x] #60625
- [ ] #60637

## General
**Design**
- [x] #39066

**FE**
- [x] #47291

**Comment by ajakabcin** [comment]
Order of operations for sprint 14 😎 

**Design/Research** 
@aagosto90 
1. Design and documentation updates to address notification component staging review launch blockers: #61388
2. Review My VA alerts/errors to make updates once notification component is released: #39066 


**Engineering**
@allisonlu 
1. (While waiting for the staging review design ticket from Angela) Finish application page set up and mock server tickets for notification center: #60398 and #60399 
2. Make FE updates to address findings from staging review: #61399 
3.  Mock data ticket for notification center: #60400 

@dellerbie 
1. Finish the CST lighthouse migration: #59410
2. Finish BE support ticket for notification center: #60454
3. Pagination BE support for notification center: #60639 
4. Header updates to the Benefit application drafts and Payment info cards: #60625 and #60637 
5. My VA redirect code cleanup: #47291 
6. _Additionally, I may need assistance from you and @tpharrison completing the PSIR review for the CST migration work, but should be mostly async._
