### ISSUE TITLE
GA4: Web Comps & Forms Events - Implementation & Testing 

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#51114]
## Problem Statement 
As part of the GA4 migration we need to configure the web and form system (global) components in GTM and provide the FE code to the FE(s) to deploy.  Once deployed we will work with FE on testing and validation to ensure all components are working as expected.

## Hypothesis or Bet
If we implement the Design & Form System (global) components we will complete are large portion of the GA4 migration and help reduce the number of VFS custom implementations needed.  

## We will know we're done when... ("Definition of Done")
When we complete the following tasks
- [x] Configure/map web components and gtags in GTM for GA4 (IN PROCESS)
- [x] Configure/map form (global) components and gtags in GTM for GA4 (IN PROCESS)
- [ ] Provide front end code to Design System team
- [ ] Work with FE engineers to implement code
- [x] Test/QA components (validate against current UA360 property)
- [x] Deploy to Prod upon validation

## Known Blockers/Dependencies 
We are dependent upon Design System teams to implement the code in order to complete this work.

## Projected Launch Date
FY 2023 Q4

```[tasklist]
### Tasks
```

**Comment by johnny-jesensky-adhoc** [comment]
Web and form components have been fully implemented in GA4. Moving this epic to _**Done**_.

FYI @jestutt
