### ISSUE TITLE
Collaboration Cycle for [VFS MHV Secure Messaging, MHV Secure Messaging, Secure Messaging]

### ISSUE THREAD

**Issue by bryan-riley-va** [department-of-veterans-affairs/va.gov-team#51115]
### VFS team name

VFS-MHV-Secure-Messaging

### Product name

MHV Secure Messaging

### Feature name

Secure Messaging

### GitHub label for product

MHV-Secure-Messaging

### GitHub label for feature

N/A

## Kickoff questions

<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

May 2022

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Both

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/173fd334ca61d2a8c45aeec45879287472040ebe/products/health-care/digital-health-modernization/mhv-to-va.gov/secure-messaging/product/README.md

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/digital-health-modernization/mhv-to-va.gov/secure-messaging/product

### Notify the Collaboration Cycle team of this ticket in the vfs-platform-support Slack channel.

- [X] I acknowledge that I must notify \#vfs-platform-support after submitting this issue.

</details>

### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

#41827
  
</details>

### Sitewide Content and IA Intake Request
<details>
  <summary>Toggle Sitewide Content and IA Intake Request</summary>

##### VFS actions
- [x] Complete the [sitewide content and IA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-Content-and-IA-intake-request.2124906551.html)
- [x] Link to the Sitewide Content and IA Intake Request ticket below

</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [x] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [ ] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

Provide links or documents for the following:

- [x] Finalized design prototype or mockup  (https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/p/E5673574-64BF-4BAF-97E3-263CA59EF092/canvas?annotation=25b2b4e3-8bfc-4c48-8667-586202b3c3b4&annotationStatus=all#Comment)
- [x] Specify which pages are included in the review - The 'Phase 0 page' is the most updated/relevant set of designs. When navigating click on 'Versions' in upper right and go to the most recent version.
- [x] Research plan  
Round 1: (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/secure-messaging/research/SecureMessaging_Round1_Usability/research-plan.md)
Round 2: (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/secure-messaging/research/2022-09-usability_testing_2/research-plan.md)
- [x] Conversation guide  
Round 1: (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/secure-messaging/research/SecureMessaging_Round1_Usability/conversation_guide.md)
Round 2: (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/secure-messaging/research/2022-09-usability_testing_2/conversation-guide.md)

Findings:
Round 1: (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/secure-messaging/research/SecureMessaging_Round1_Usability/Final_Report.md)
Round 2: (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/secure-messaging/research/2022-09-usability_testing_2/research-findings.md)
 
**Content artifacts**
  
- [X] Your product’s content source of truth 
- [X] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
See Content and IA ticket links when expanding the IA artifacts section directly below.

Tickets below under IA artifacts are related to both content and IA.

**IA artifacts**

- [X] Please include a link to any [Sitewide Content & IA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including an IA review document or intake form.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/42428
https://github.com/department-of-veterans-affairs/va.gov-team/issues/50161
https://github.com/department-of-veterans-affairs/va.gov-team/issues/49690
https://github.com/department-of-veterans-affairs/va.gov-team/issues/47747
https://github.com/department-of-veterans-affairs/va.gov-team/issues/47794
https://github.com/department-of-veterans-affairs/va.gov-team/issues/29582

**QA artifacts**
[Learn more about QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)

- [ ] Regression test plans (if there isn't already a regression test plan for this feature in TestRailProduct)
- [x] Link to test cases/test plan in TestRail (draft OK)
https://dsvavsp.testrail.io/index.php?/suites/view/1953
Look for regression test folder
  
##### Platform actions
- [ ] Follow Moderator Responsibilities guidance for Midpoint Review
- [x] Meeting date/time: January 10, 2023 11:30 am ET

##### Platform actions

- [ ] If you have midpoint review feedback, create feedback ticket and link to this epic. Once you have completed your review, check the box next to your practice area
  - [x] Design has completed the review
  - [ ] Accessibility has completed the review
  - [x] IA has completed the review
  - [ ] Content has completed the review
  - [ ] QA has completed the review
- [ ] Update this ticket with the Zoom recording
  - Recording URL: [Zoom recording](https://oddball-io.zoom.us/rec/share/eB2s9-DWPrPayBLJCq1MikHj5P07TZuQajHDCMOhk1eT56lSJWeRvmsNM5vqLLMR.7k1q08D7p5WlP6Od)
  - Password: *Yw^v3NQ
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [X] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [X] Link to the Analytics Implementation and QA Request ticket below
https://github.com/department-of-veterans-affairs/va.gov-team/issues/48627

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [x] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [x] Link to the Contact Center review request ticket below
https://github.com/department-of-veterans-affairs/va.gov-team/issues/48628
</details>

### Staging Review
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [ ] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [ ] I confirm the environment is available and test users have been provided.
- [ ] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).

**Staging Review artifacts**
  
  Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts)
  
**Product artifacts** 
- [x] Staging URL https://staging.va.gov/my-health/secure-messages/
- [x] Specify which pages are included in the review         
"/my-health/secure-messages/folders" 
"/my-health/secure-messages/compose" 
"/my-health/secure-messages/message/:messageId" 
"/my-health/secure-messages/thread/:threadId" 
"/my-health/secure-messages/reply/:replyId" 
"/my-health/secure-messages/search/results" 
"/my-health/secure-messages/draft/:draftId" 
"/my-health/secure-messages/sent/:messageId" 
"/my-health/secure-messages/trash/:messageId" 
'/my-health/secure-messages/inbox', 
'/my-health/secure-messages/sent', 
'/my-health/secure-messages/trash', 
'/my-health/secure-messages/drafts', 
'/my-health/secure-messages/folder/:folderId'

- [x] Staging test user information         <!-- Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository. Use this accessible staging account template to do so: 
[LINK](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/sm/test-accounts.md)
  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**
- [x] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/50161#event-7923258428
https://github.com/department-of-veterans-affairs/va.gov-team/issues/47747 
 
**IA artifacts**
- [x] Please include a link to any [Sitewide Content & IA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including an IA review document or intake form.
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/my-health-secure-messaging.md

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [x] [Regression test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-regression-test-planRegressionTestPlan) -(https://dsvavsp.testrail.io/index.php?/suites/view/1953&group_by=cases:section_id&group_id=8178&group_order=asc&display_deleted_cases=0)
- [x] [Test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-test-planTestPlan) - https://dsvavsp.testrail.io/index.php?/runs/view/4617&group_by=cases:section_id&group_order=asc
- [x] [Coverage for References](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports) - See Stories to Test Cases.xlsx attached in the comments
- [x] [Summary(Defects) reports](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports) - Two defects found during regression test run: 
https://vajira.max.gov/browse/MHV-45118
https://vajira.max.gov/browse/MHV-45121

- [x] [E2E tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-e2e-test-participationE2ETestParticipation) (provide a link to the product’s code)
https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/mhv/secure-messaging/tests/e2e
- [x] [Code coverage](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-unit-test-coverageUnitTestCoverage) (provide a link to the product’s code)  
https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report
  
**Accessibility artifacts**
  
- [x] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D). For details, see [Prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).       BR - requests (more than 4 days given the size of our effort) need to request as soon as final MUST accessibility item is done
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/54823 - final code being committed 5/16/23
  
##### Platform actions
- [ ] Follow Moderator Responsibilities guidance for Staging Review
- [x] Meeting date/time: Thursday, June 1, 2023, 1:30 pm to 2:00 pm ET.
- [x] [Slack Link](https://dsva.slack.com/archives/CBU0KDSB1/p1684250541210189) 
- [ ] Create feedback tickets and link to this epic
  - [x] Design feedback provided
  - [x] Accessibility feedback provided
  - [ ] IA feedback provided
  - [ ] Content feedback provided
  - [ ] QA feedback provided

##### Platform actions

- [x] Update this ticket with the Zoom recording
  - [Zoom recording](https://oddball-io.zoom.us/rec/share/La8ie0nZyDpgL97C2YsOVd9c97RWURVSuDWQa1QfQEJVUExJREG48lZuXuuPxBdS.A4kcW8rpoVNERNTw)
  - Passcode: yck43d!1
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [ ] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [ ] Link to the Readiness Review ticket below
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/620

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by bryan-riley-va** [comment]
Tickets to review from Midpoint:
QA - https://github.com/department-of-veterans-affairs/va.gov-team/issues/51661
IA - https://github.com/department-of-veterans-affairs/va.gov-team/issues/51738
Design - https://github.com/department-of-veterans-affairs/va.gov-team/issues/51753
Accessiblity - https://github.com/department-of-veterans-affairs/va.gov-team/issues/51913
Content - https://github.com/department-of-veterans-affairs/va.gov-team/issues/50161

**Comment by Asterix22** [comment]
[Stories to Test Cases Mapping.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11478985/Stories.to.Test.Cases.Mapping.xlsx)

**Comment by artsymartha68** [comment]
I opened a ServiceNow ticket for the VA 508 Office audit. https://yourit.va.gov/va?id=sc_request&is_new_order=true&table=sc_request&sys_id=f0155aea1bcc7150d11ccbf7624bcba3

**Comment by bryan-riley-va** [comment]
All touchpoints for this Collab Cycle ticket have been completed.  Feedback from various reviews is logged in GH as well as JIRA.
