### ISSUE TITLE
Update Best Practices for QA testing page

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#51120]
## User Story
As a VFS team member working on a product entering the collab cycle I want to have accurate information on satisfying the QA Standards so that my product can launch without delays.

Assignee: @it-harrison 
Peer Reviewer: @CherylEvans 

## Description
The [Best Practices for QA testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/best-practices-for-qa-testing) page needs to be updated to reflect changes in the QA Standards and Platform documentation:

## Impacted Artifacts
The [Best Practices for QA testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/best-practices-for-qa-testing) page

## Tasks
- [x] change reference to "90%" frontend unit test coverage to "75%" coverage to be consistent with the QA Standards
- [x] replace reference to the QA Artifacts page (to be archived) with the QA Standards page

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The [Best Practices for QA testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/best-practices-for-qa-testing) page has been updated

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
@CherylEvans [this ticket](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2078474309/Best+practices+for+QA+testing) is ready for review

**Comment by CherylEvans** [comment]
@it-harrison The user story and acceptance criteria have been met.  Looks good!  Review complete. :-)
