### ISSUE TITLE
Request design review for "Add Dependents" VA From 21-686c

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#5117]
### Checkpoint Stage

- [x]  **Design Intent** (for early discussions about needs, priorities, concepts, research planning, and direction)

- [ ]  **Pre-usability testing Review** (for prototype and testing validation of best practices, alignment with VA design system, and inclusive research best practices)

- [x]  **Design Review** (for design work validation of best practices and alignment with the va design system)

### Where in the process is this? 

- [x] Initial concept

- [ ] Initial mockup

- [ ]  Final mockup

## Considerations
Our team is migrating eBenefits dashboard features to VA.gov. Currently the only digital version of the 21-686c available to Veterans is the dependents dashboard--and it is based on the June 2014 iteration of the form which is no longer in use. Our work includes updating the form as we move from the eBenefits implementation to the VA.gov form system.

Our work includes:
- Determining user workflows for a multi-purpose form
- Mapping all new fields to VA.gov form elements
- Implementing rudimentary MVP form logic
- Positioning supporting instructions and examples within the form
- Simplifying/streamlining a potentially confusing multi-purpose form

We would like guidance with:
- Conventions for multi-purpose forms
- Gating strategy for multiple workflows
- Clarification on standardized form 'blocks' (e.g. Address)

## Design links or mockups
XD walkthrough available here: https://xd.adobe.com/view/ffffe536-2ba5-47c6-4c4b-ac1679179973-89ce/

### Point of contact

Jim Adams / Design
Jason Wolf / Product

### Preferred times

January 30  |  morning or after 2:30 EST
January 31  |  9:00 to 5:00 EST

**Comment by 1Copenut** [comment]
@sporeboy Can this issue be closed? It's pretty old at this point.

**Comment by sporeboy** [comment]
I think so... Thanks!
