### ISSUE TITLE
[Design] [Content] Create wireframes for option 1

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#51174]
## Tasks

- [ ] Once workflow diagram has been created, identify which interactions (SMS and wireframes) require updated content and/or wireframes. 
- [ ] Create wireframes for option 1 ([Mural](https://app.mural.co/t/vfscie8528/m/vfscie8528/1671459379892/bfa34b32cc12d8655715e493c9cffb93bbdbaacb?sender=u83bc52d7fa73658f84f27755))
- [ ] Create new SMS content for PCI API team 
- [ ] Run the content by Sitewide
- [ ] Review with UX team
- [ ] Review with the CIE team 
- [ ] Review with the other Check-In Teams

Look into changing messaging to "confirm your appointment" or "complete check in tasks" instead of "start pre check in." 

## AC 

- [ ] Abstract branch created with wireframes
- [ ] Reviewed with UX team
- [ ] Reviewed with CIE team 
- [ ] Content written for new SMS messages and handed over to PCI API team

**Comment by kristenmcconnell** [comment]
Brainstorm session scheduled for 1/16.

**Comment by kellysmith1008** [comment]
[Adding my mural](https://app.mural.co/t/vfscie8528/m/vfscie8528/1673552327872/08c72343a4fe2a16f1c464d8009e65284be6129c?sender=u4f51c3ab811a3cc570d34701) in here with my comments for ideas around content

**Comment by sarahknoppA6** [comment]
closing because we are proceeding with option 2- @benbrasso-agile6 to create tickets for that.
