### ISSUE TITLE
[UX] [Research] Create research plan for moderated research study

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#51183]
## Description 
How might we better study how Veterans respond to our prototypes for the unified experience

## Tasks 
- [x] Create research plan and folder in git
- [ ] Get sign off from VA stakeholders and POs
- [ ] Submit to research repo for Shane review 
- [ ] Complete kickoff with Perigean, if needed 

## AC
- [x] Research plan created
- [ ] Approved by VA stakeholders and POs
- [ ] Submitted to Shane
- [ ] Kickoff completed with Perigean, if needed

**Comment by benbrasso-agile6** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/2023-04%20Unified%20Check-In%20Experience%20Usability%20Study/research-plan.md

https://docs.google.com/document/d/1SDmtVXlOPi7miNJVRYQnWE7GUhvjO05d-yKq2BnFUJ4/edit?usp=sharing
