### ISSUE TITLE
[SPIKE] Investigate how to send one check-in link that's good for a day

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#51187]
## Background

One potential improvement that has come out of the unified check-in discovery work would be to proactively send a single link at the beginning of the day to Veterans with at least one appointment eligible for online check-in on that day. We need to investigate the technical feasibility and answer the following questions, keeping in mind that the existing check-in workflow should continue to work as-is:

- what modifications need to be made to VEText to allow this to work?
- what modifications need to be made to CHIP (and/or LoROTA) to allow this to work?
- what modifications need to be made to the front end to allow this to work?
- what modifications need to be made to the back end to allow this to work?

## Tasks
- [ ] Answer questions
- [ ] Socialize answers
- [ ] Create any necessary follow-on tickets
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
