### ISSUE TITLE
Migrate 3 CHAMPVA pages

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#51199]
## Issue Description
We're migrating the CHAMPVA content to VA.gov:
- [CHAMPVA FAQ](https://www.va.gov/COMMUNITYCARE/programs/dependents/champva/index.asp)
- [File a claim](https://www.va.gov/COMMUNITYCARE/programs/dependents/champva/champva_claim.asp)
- [CITI program ](https://www.va.gov/COMMUNITYCARE/programs/dependents/champva/CITI.asp)(becoming part of FAQ)

---
## Tasks
- [ ] Draft new pages
- [ ] Send to SMEs

## Acceptance Criteria
- [ ] New pages are live on VA.gov and legacy pages are redirected

**Comment by laurwill** [comment]
Hi @DanielleThierryUSDSVA , setting up a ticket here for our champva work. Here's my working draft of the file a claim page with a few questions for you: 
[How to file a CHAMPVA claim.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10298710/How.to.file.a.CHAMPVA.claim.docx)

I haven't put this in the template yet because I wasn't sure if we were building this one in the benefit hub or sending to Kelly to build in R&S. I can put it in the template if needed when I'm back!

**Comment by laurwill** [comment]
Hi @DanielleThierryUSDSVA ,
Here are some dependent pages ready for your review and next steps: 
- [CHAMPVA FAQs](https://dvagov-my.sharepoint.com/:w:/r/personal/danielle_thierry_va_gov/Documents/Community%20care%20R%26S%20pilot%20shared%20folder/Working%20content%20drafts/RS13%20-%20CHAMPVA%20Q%26As_for%20Drupal.docx?d=w9b822a332ad64ddfb254366fcc47c10d&csf=1&web=1&e=xbhcjZ) — See tracked changes with updates related to Meds by Mail
- [How to file a CHAMPVA claim](https://dvagov-my.sharepoint.com/:w:/r/personal/danielle_thierry_va_gov/Documents/Community%20care%20R%26S%20pilot%20shared%20folder/Working%20content%20drafts/RS11_File%20a%20CHAMPVA%20claim.docx?d=w4c3a7664a2ab46d68877c511e21ae06b&csf=1&web=1&e=NY2UtT) — new R&S page draft 
- [Meds by Mail](https://dvagov-my.sharepoint.com/:w:/r/personal/danielle_thierry_va_gov/Documents/Community%20care%20R%26S%20pilot%20shared%20folder/Working%20content%20drafts/RS15_Meds%20by%20Mail.docx?d=w22bf61cb0ff046a68ba6112d7aa8b9ed&csf=1&web=1&e=3aRI3W) — new R&S page draft
- Prescription Q&As for CWVV and spina bifida pages — I already passed these to you over Slack, just documenting here [https://app.zenhub.com/files/133843125/c0f0a295-e4e1-43ff-96c5-145a0417bb97/download](https://app.zenhub.com/files/133843125/c0f0a295-e4e1-43ff-96c5-145a0417bb97/download)

**Comment by coforma-terry** [comment]
Downgraded to normal from high as it's been almost a year.
