### ISSUE TITLE
Certificate of Eligibility | Prepare production environment for 1/19/2023 soft launch of COE 

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#51193]
## Issue Description

We have a soft launch for COE planned for 1/19/2023, where we will give a small number of VA employees and contractors access to the COE form, for testing purposes. 

---
## Tasks
- [x] Get `app_id`, `api_key`, and `base_url` for LGY's production environment.
- [x] Add these keys to AWS key store.
    - I've added all but `base_url` to LGY's prod environment. I've asked platform for support on configuring `base_url`. See https://dsva.slack.com/archives/CBU0KDSB1/p1671821716375209; https://dsva.slack.com/archives/CBU0KDSB1/p1671823747448789; https://dsva.slack.com/archives/CBU0KDSB1/p1673017944397909.
- [x] Update vets-api prod settings to include these keys.
    - See previous bulletpoint and https://github.com/department-of-veterans-affairs/devops/pull/12397.
- [x] Setup SSL
- [x] Figure out how to turn COE on for individual users
    - [x] Add myself as a flipper admin. (See https://github.com/department-of-veterans-affairs/vets-api/pull/11545)
    - From Jerek: "If you go to the page for the individual toggle, there is a section on the bottom right that you can enter [their VA] emails in"

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
Can close after Eugene confirms they are a flipper admin.

**Comment by saderagsdale** [comment]
will also write tickets for 25% launch

**Comment by data-doge** [comment]
@saderagsdale I have access! Closing this ticket.

![image](https://user-images.githubusercontent.com/7520103/212420619-289b98bd-9dfc-4b2a-98a3-291e5f0d5bd5.png)
