### ISSUE TITLE
[CDP] Coordinate URL changes 

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#51209]
## Issue Description
Coordinate with platform to conform new URL routing changes are functional and we are no longer seeing traffic on 'legacy' medical-copay and debt-letters applications. 

---
## Tasks
- [x] Update devops react_routes.yml so redirects can take effect.

## Acceptance Criteria
- [x] Navigating to any previous mcp or debt url will result in a redirect to the new combined experience 
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
