### ISSUE TITLE
[EKS Upgrade] Upgrade Dev Control Plane to 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51217]
# Description
Upgrade the EKS Dev control plane to version 1.22

# Tasks
- [ ] Upgrade the EKS control plane to 1.22 (this can be done in the AWS Console)
- [ ] Update IaC references to match the desired version 1.22 (you will _not_ apply these changes with terraform, just updating the src to be accurate)

# Acceptance Criteria
- [x] EKS Dev Control Plane is running version 1.22
- [x] Infrastructure as Code reflects that EKS is running 1.22

**Comment by ph-One** [comment]
![image.png](https://images.zenhubusercontent.com/622146ffd0422cdb4d9fdd52/b262f18d-f300-4fd4-bcf6-f25a2acb08da)

**Comment by ph-One** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/12408
