### ISSUE TITLE
[FE] Convert profile email address form to use SchemaForm

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5121]
## Background

Epic #4068

## Tasks
- [ ] Make a new version of the email address component that wraps a `SchemaForm` component and does not use any `Errorable` form components

## Acceptance Criteria:
- [ ] Should function the same as the existing email address component.
- [ ] Needs to be able to live alongside the existing email address form (ie, behind a feature flag or some other method so the form can be put on staging but not prod)

**Comment by Samara-Strauss** [comment]
@erikphansen just checking in on this one — is it still in progress?

**Comment by erikphansen** [comment]
This one has been merged. I've validated it and it seems to work with a couple caveats I documented here that I'll address https://github.com/department-of-veterans-affairs/va.gov-team/issues/5704

**Comment by Samara-Strauss** [comment]
Great! Will close this then and mark as done for the sprint.
