### ISSUE TITLE
[EKS Upgrade] Upgrade Staging Control Plane to 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51227]
# Description
Upgrade the EKS Staging control plane to version 1.22

# Tasks
- [x] Upgrade the EKS control plane to 1.22 (this can be done in the AWS Console)
- [ ] Update IaC references to match the desired version 1.22 (you will _not_ apply these changes with terraform, just updating the src to be accurate)

# Acceptance Criteria
- [x] EKS Staging Control Plane is running version 1.22
- [ ] Infrastructure as Code reflects that EKS is running 1.22

**Comment by ph-One** [comment]
IaC was updated for all clusters already
