### ISSUE TITLE
[EKS Upgrade] Build & Deploy EKS 1.22 AMI for EKS Sandbox

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51223]
# Description
EKS cluster nodes need to be upgraded to 1.22 in order to match the version of the Control Plane

# Tasks
- [x] Build AMI (Packer) for Kubernetes 1.22 Nodes
- [x] Deploy new AMI to EKS Sandbox

# Acceptance Criteria
- [x] EKS Sandbox Nodes are running Kubernetes 1.22, matching the Control Plane
