### ISSUE TITLE
[EKS Upgrade] Upgrade Utility Control Plane to 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51237]
# Description
Upgrade the EKS Utility control plane to version 1.22

# Tasks
- [ ] Upgrade the EKS control plane to 1.22 (this can be done in the AWS Console)
- [ ] Update IaC references to match the desired version 1.22 (you will _not_ apply these changes with terraform, just updating the src to be accurate)

# Acceptance Criteria
- [ ] EKS Utility Control Plane is running version 1.22
- [ ] Infrastructure as Code reflects that EKS is running 1.22
