### ISSUE TITLE
[EKS Upgrade] Upgrade Production Control Plane to 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51232]
# Description
Upgrade the EKS Production control plane to version 1.22

# Tasks
- [x] Upgrade the EKS control plane to 1.22 (this can be done in the AWS Console)
- [x] Update IaC references to match the desired version 1.22 (you will _not_ apply these changes with terraform, just updating the src to be accurate)

# Acceptance Criteria
- [x] EKS Production Control Plane is running version 1.22
- [x] Infrastructure as Code reflects that EKS is running 1.22
