### ISSUE TITLE
[Bug] 526: Issues with Claim Tracking and Status

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#5123]
## What happened?
Update: See comment added to GitHub on January 30th below.

From an email : 

> I’m hoping to improve our customers’ experiences by bringing these issue to your attention in case you weren’t aware of them before.
>  
> 1)	Under “What happens next?” on the “File a Supplemental Claim with new evidence” page (https://www.va.gov/decision-reviews/supplemental-claim/), there’s a “Track the status or your claim” button.  But, after clicking the button and landing on the “Check your claim or appeal status” page (https://www.va.gov/track-claims/your-claims), the system says something along the lines of “We do not know the status of your claim.” It says this from the time VBA enters our claims into their system up to the time a decision is made. I confirmed with staff at (800) 827-1000 that this message is displayed to all Veterans with appeals claims under review. Yet, they were able to tell me the status of my claim.
>  
> 2)	Similarly, under “What happens next?” on the “File a Supplemental Claim with new evidence” page (https://www.va.gov/decision-reviews/supplemental-claim/), there is a hyperlink (“Find out what happens after you request a decision review” - https://www.va.gov/decision-reviews/after-you-request-review/) that leads to an “After you request a decision review” page. That page provides a “Track the status or your claim or appeal” button. But, after clicking the button and landing on the same “Check your claim or appeal status” page (https://www.va.gov/track-claims/your-claims), we see the same non-status status.
>  
> 3)	Under “After your VA claim exam,” on the “After you request a decision review” (https://www.va.gov/disability/va-claim-exam/) page, the page says “Call us at 800-827-1000 and request an appointment to view your file,” but, according to the folks at that number, we cannot schedule an appointment with VA to view our files. However, I did find out through my VSO that we can view our files by visiting our VSO’s office at the RO (appointments may be required – I needed one). Also, the “Track the status of your claim or appeal” button is present there, too, which leads to the non-status status page.

## Specs:
Not known, came in through an email. 

## Steps to Reproduce
N/A - we can likely not reproduce even based on the email from David

## Desired behavior
You will be able to see your status and tracking info.  More details may be added here as we investigate the bugs.

## Tasks
- [ ] Look in the `getStatusContents` method in `appeals-v2-helpers.jsx` to see if there are any existing statuses that are not being checked.
- [ ] Determine (either through a test or research) whether any new statuses are coming back from VBMS

## Acceptance Criteria
- [ ] We have spent 2-3 hours to see if new VBMS status or existing status can be conditionally checked for an updated status message to the veteran.

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by luke-gcio** [comment]
We had a call with David Haas to go over what he was seeing.  Overall, this is very difficult issue to debug. However, we did decide that we would look at the status coming back from VBMS to see if there is any differences and whether we can update the default message in certain cases to provide more details.

In this case, it seemed like there may have been a "limbo" state between his claim closing and getting the updated information in the claims status tool.

@ndsprinkle identified these as the methods where we check for the status back from VBMS.

The function is `getStatusContents` and the file is `appeals-v2-helpers.jsx`

**Comment by Mottie** [comment]
If I had to guess (what I'm doing), I think the problem is either:

* A missing or modified status in the front-end code ([current list](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/claims-status/utils/appeals-v2-helpers.jsx#L97-L132))
* Or, the information isn't being sent by EVSS API (the url is: https://staging-api.va.gov/v0/evss_claims_async), but I can't find any info on it. Maybe @SMLuthi can point us in the right direction for this?

**Comment by ndsprinkle** [comment]
@Mottie I've been looking at this too, and one other possibility I could think is that the `status` object isn't in the proper format sometimes? The function that determines the status message is looking at `appeal.attributes.status.type`, but I'm not sure if `appeal.attributes.status` is always an object. In this sample data @camerontesterman sent me a few weeks ago:

```
{
  "data": {
    "id": "8347210",
    "type": "claims_api_claims",
    "attributes": {
      "evss_id": "8347210",
      "date_filed": "2018-06-04",
      "min_est_date": "2019-06-04",
      "max_est_date": "2019-09-04",
      "open": true,
      "waiver_submitted": false,
      "documents_needed": false,
      "development_letter_sent": false,
      "decision_letter_sent": false,
      "requested_decision": false,
      "claim_type": "Compensation",
      "contention_list": [
        "abnormal heart (New)"
      ],
      "va_representative": "AMERICAN LEGION",
      "events_timeline": [
        {
          "single_event": {
            "type": "filed",
            "date": "2018-07-30"
          },
          "tracked_item": {
            "tracked_item_id": "12345",
            "file_type": "Disability Benefits Questionnaire (DBQ) - Veteran Provided",
            "document_type": "L702",
            "filename": "DBQ form.pdf",
            "upload_date": "2017-06-01",
            "type": "other_documents_list",
            "date": "2017-06-01"
          }
        }
      ],
      "status": "Claim recieved"
    }
  }
}
```
`status` is actually just a string and not an object. This may have just been test data in a strange format, but I'm not sure. If it were in this format of just being a string and not an object, that would also cause this default message to appear.

**Comment by ndsprinkle** [comment]
Status pulled from `appeals.attributes`: [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/claims-status/utils/appeals-v2-helpers.jsx#L290)

Type pulled from `status.type` (assuming it's an object): [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/claims-status/utils/appeals-v2-helpers.jsx#L284)

Switch statement checking `statusType` (`status.type` from above): [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/claims-status/utils/appeals-v2-helpers.jsx#L290)

**Comment by ndsprinkle** [comment]
So if `status` is a string and `status.type` is called, the result will be `undefined` automatically causing the switch statement to go to the default case, which outputs the string "We don’t know your status", which is what the user saw in this ticket.

**Comment by luke-gcio** [comment]
Yeessssss @ndsprinkle now that's quality debugging!  Seems like a nice easy fix to add some data validation/fixes before we get to the switch.

**Comment by Mottie** [comment]
I tried to find a [list of available statuses](https://dsva.slack.com/archives/CBU0KDSB1/p1581088208070200), but the data isn't easily accessible. Maybe @SMLuthi can help us?

**Comment by ndsprinkle** [comment]
Yeah if @SMLuthi could provide that list, that would help enormously :) For now, I'll just go ahead and create a PR for the code to check the situation I described above. If we discover more from the list of statuses, then we can make changes accordingly.

**Comment by SMLuthi** [comment]
Getting caught up on this issue.
