### ISSUE TITLE
[EKS Upgrade] Evaluate Traefik Helm Chart for Kubernetes 1.22 Support

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51246]
# Description
Evaluate if Traefik is compatible with Kubernetes 1.22

# Notes
- Platform Helm charts can be found, https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps
- Do not upgrade unless absolutely necessary

# Tasks
- [ ] Evaluate if the Helm chart requires an upgrade to be compatible with Kubernetes 1.22
- [ ] If no upgrade is required, close the "Upgrade Traefik" ticket with a comment stating no upgrade is needed
- [ ] If an update is required, comment on the "Upgrade Traefik" ticket stating the version to upgrade to

# Acceptance Criteria
- [x] It is known whether or not Traefik requires and upgrade to be compatible with Kubernetes 1.22
- [ ] A comment has been left on the "Upgrade Traefik" ticket

**Comment by ph-One** [comment]
No changes are needed. Deploy to 1.22 as-is.
