### ISSUE TITLE
[EKS Upgrade] Evaluate External DNS Helm Chart for Kubernetes 1.22 Support

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51243]
# Description
Evaluate if External DNS is compatible with Kubernetes 1.22

# Notes
- Platform Helm charts can be found, https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps
- Do not upgrade unless absolutely necessary

# Tasks
- [x] Evaluate if the Helm chart requires an upgrade to be compatible with Kubernetes 1.22
- [x] If no upgrade is required, close the "Upgrade External DNS" ticket with a comment stating no upgrade is needed
- [x] If an update is required, comment on the "Upgrade External DNS" ticket stating the version to upgrade to

# Acceptance Criteria
- [x] It is known whether or not External DNS requires and upgrade to be compatible with Kubernetes 1.22
- [x] A comment has been left on the "Upgrade External DNS" ticket

**Comment by ph-One** [comment]
Requires upgrade >= 0.10.0

![image.png](https://images.zenhubusercontent.com/622146ffd0422cdb4d9fdd52/764bcb44-ade2-4e80-81e2-5cb5604d8479)
