### ISSUE TITLE
[EKS Upgrade] Upgrade & Deploy External DNS to EKS Dev 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51258]
# Description
Upgrade and deploy External DNS to the EKS Dev 1.22 cluster

# Notes
- Platform Helm charts can be found, https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps

# Tasks
- [ ] Upgrade the External DNS Dev helm chart version in the Chart.yaml file
- [ ] Perform a sync in with Argo and see that the External DNS is deployed
- [ ] Verify that External DNS is running as expected

# Acceptance Criteria
- [ ] The upgraded External DNS helm chart is running as expected in EKS Dev 1.22

**Comment by ph-One** [comment]
Requires upgrade to >= 0.10.0

![image.png](https://images.zenhubusercontent.com/622146ffd0422cdb4d9fdd52/c4dfaf79-2efc-4184-8048-1654b3dd093b)

**Comment by ph-One** [comment]
We are currently running version 0.12.x and are okay to leave this as-is
https://github.com/department-of-veterans-affairs/vsp-infra-k8s-external-dns/blob/main/versions.json#L6
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/external-dns/dev/values.yaml#L54
