### ISSUE TITLE
[EKS Upgrade] Upgrade & Deploy External Secrets to EKS Dev 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51259]
# Description
Upgrade and deploy External Secrets to the EKS Dev 1.22 cluster

# Notes
- Platform Helm charts can be found, https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps

# Tasks
- [ ] Upgrade the External Secrets Dev helm chart version in the Chart.yaml file
- [ ] Perform a sync in with Argo and see that the External Secrets is deployed
- [x] Verify that External Secrets is running as expected

# Acceptance Criteria
- [x] The upgraded External Secrets helm chart is running as expected in EKS Dev 1.22

**Comment by ph-One** [comment]
No changes are needed. Deployed to 1.22 as-is.
