### ISSUE TITLE
[EKS Upgrade] Upgrade & Deploy Traefik to EKS Dev 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51261]
# Description
Upgrade and deploy Traefik to the EKS Dev 1.22 cluster

# Notes
- Platform Helm charts can be found, https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps

# Tasks
- [ ] Upgrade the Traefik Dev helm chart version in the Chart.yaml file
- [ ] Perform a sync in with Argo and see that the Traefik is deployed
- [x] Verify that Traefik is running as expected

# Acceptance Criteria
- [x] The upgraded Traefik helm chart is running as expected in EKS Dev 1.22

**Comment by ph-One** [comment]
No changes are needed. Deployed to 1.22 as-is.
