### ISSUE TITLE
[EKS Upgrade] Upgrade & Deploy ArgoCD to EKS Sandbox 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51269]
# Description
Upgrade and deploy ArgoCD to the EKS Sandbox 1.22 cluster

# Notes
- Platform Helm charts can be found, https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps

# Tasks
- [ ] Upgrade the ArgoCD Sandbox helm chart version in the Chart.yaml file
- [ ] Perform a sync in with Argo and see that the ArgoCD is deployed
- [ ] Verify that ArgoCD is running as expected

# Acceptance Criteria
- [ ] The upgraded ArgoCD helm chart is running as expected in EKS Sandbox 1.22

**Comment by ph-One** [comment]
Not applicable
