### ISSUE TITLE
[EKS Upgrade] Upgrade & Deploy Vets API to EKS Dev 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51268]
# Description
Upgrade and deploy Vets API to the EKS Dev 1.22 cluster

# Notes
- Platform Helm charts can be found, https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps

# Tasks
- [ ] Upgrade the Vets API Dev helm chart version in the Chart.yaml file
- [ ] Perform a sync in with Argo and see that the Vets API is deployed
- [x] Verify that Vets API is running as expected

# Acceptance Criteria
- [ ] The upgraded Vets API helm chart is running as expected in EKS Dev 1.22

**Comment by ph-One** [comment]
No changes are needed. Deployed to 1.22 as-is.
