### ISSUE TITLE
[EKS Upgrade] Upgrade & Deploy Loki to EKS Dev 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51265]
# Description
Upgrade and deploy Loki to the EKS Dev 1.22 cluster

# Notes
- Platform Helm charts can be found, https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps

# Tasks
- [ ] Upgrade the Loki Dev helm chart version in the Chart.yaml file
- [x] Perform a sync in with Argo and see that the Loki is deployed
- [x] Verify that Loki is running as expected

# Acceptance Criteria
- [ ] The upgraded Loki helm chart is running as expected in EKS Dev 1.22

**Comment by ph-One** [comment]
No changes are needed. Deployed to 1.22 as-is.
