### ISSUE TITLE
[EKS Upgrade] Upgrade & Deploy Promtail to EKS Dev 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51266]
# Description
Upgrade and deploy Promtail to the EKS Dev 1.22 cluster

# Notes
- Platform Helm charts can be found, https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps

# Tasks
- [ ] Upgrade the Promtail Dev helm chart version in the Chart.yaml file
- [ ] Perform a sync in with Argo and see that the Promtail is deployed
- [x] Verify that Promtail is running as expected

# Acceptance Criteria
- [ ] The upgraded Promtail helm chart is running as expected in EKS Dev 1.22

**Comment by ph-One** [comment]
No changes are needed. Deployed to 1.22 as-is.
