### ISSUE TITLE
[EKS Upgrade] Upgrade & Deploy Datadog Private Location to EKS Sandbox 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51272]
# Description
Upgrade and deploy Datadog Private Location to the EKS Sandbox 1.22 cluster

# Notes
- Platform Helm charts can be found, https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps

# Tasks
- [ ] Upgrade the Datadog Private Location Sandbox helm chart version in the Chart.yaml file
- [ ] Perform a sync in with Argo and see that the Datadog Private Location is deployed
- [ ] Verify that Datadog Private Location is running as expected

# Acceptance Criteria
- [ ] The upgraded Datadog Private Location helm chart is running as expected in EKS Sandbox 1.22
