### ISSUE TITLE
[EKS Upgrade] Upgrade & Deploy Loki Canary to EKS Sandbox 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51279]
# Description
Upgrade and deploy Loki Canary to the EKS Sandbox 1.22 cluster

# Notes
- Platform Helm charts can be found, https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps

# Tasks
- [ ] Upgrade the Loki Canary Sandbox helm chart version in the Chart.yaml file
- [ ] Perform a sync in with Argo and see that the Loki Canary is deployed
- [ ] Verify that Loki Canary is running as expected

# Acceptance Criteria
- [ ] The upgraded Loki Canary helm chart is running as expected in EKS Sandbox 1.22
