### ISSUE TITLE
[EKS Upgrade] Upgrade & Deploy Metrics Server to EKS Sandbox 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51275]
# Description
Upgrade and deploy Metrics Server to the EKS Sandbox 1.22 cluster

# Notes
- Platform Helm charts can be found, https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps

# Tasks
- [ ] Upgrade the Metrics Server Sandbox helm chart version in the Chart.yaml file
- [ ] Perform a sync in with Argo and see that the Metrics Server is deployed
- [ ] Verify that Metrics Server is running as expected

# Acceptance Criteria
- [ ] The upgraded Metrics Server helm chart is running as expected in EKS Sandbox 1.22
