### ISSUE TITLE
[EKS Upgrade] Upgrade & Deploy Cert Manager to EKS Sandbox 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51270]
# Description
Upgrade and deploy Cert Manager to the EKS Sandbox 1.22 cluster

# Notes
- Platform Helm charts can be found, https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps

# Tasks
- [ ] Upgrade the Cert Manager Sandbox helm chart version in the Chart.yaml file
- [ ] Perform a sync in with Argo and see that the Cert Manager is deployed
- [ ] Verify that Cert Manager is running as expected

# Acceptance Criteria
- [ ] The upgraded Cert Manager helm chart is running as expected in EKS Sandbox 1.22
