### ISSUE TITLE
[EKS Upgrade] Upgrade & Deploy External Secrets to EKS Sandbox 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51274]
# Description
Upgrade and deploy External Secrets to the EKS Sandbox 1.22 cluster

# Notes
- Platform Helm charts can be found, https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps

# Tasks
- [ ] Upgrade the External Secrets Sandbox helm chart version in the Chart.yaml file
- [ ] Perform a sync in with Argo and see that the External Secrets is deployed
- [ ] Verify that External Secrets is running as expected

# Acceptance Criteria
- [ ] The upgraded External Secrets helm chart is running as expected in EKS Sandbox 1.22
