### ISSUE TITLE
[EKS Upgrade] Upgrade & Deploy Goldilocks to EKS Sandbox 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51277]
# Description
Upgrade and deploy Goldilocks to the EKS Sandbox 1.22 cluster

# Notes
- Platform Helm charts can be found, https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps

# Tasks
- [ ] Upgrade the Goldilocks Sandbox helm chart version in the Chart.yaml file
- [ ] Perform a sync in with Argo and see that the Goldilocks is deployed
- [ ] Verify that Goldilocks is running as expected

# Acceptance Criteria
- [ ] The upgraded Goldilocks helm chart is running as expected in EKS Sandbox 1.22
