### ISSUE TITLE
[EKS Upgrade] Upgrade & Deploy Promtail to EKS Sandbox 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51281]
# Description
Upgrade and deploy Promtail to the EKS Sandbox 1.22 cluster

# Notes
- Platform Helm charts can be found, https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps

# Tasks
- [ ] Upgrade the Promtail Sandbox helm chart version in the Chart.yaml file
- [ ] Perform a sync in with Argo and see that the Promtail is deployed
- [ ] Verify that Promtail is running as expected

# Acceptance Criteria
- [ ] The upgraded Promtail helm chart is running as expected in EKS Sandbox 1.22
