### ISSUE TITLE
[EKS Upgrade] Upgrade & Deploy Datadog Private Location to EKS Staging 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51287]
# Description
Upgrade and deploy Datadog Private Location to the EKS Staging 1.22 cluster

# Notes
- Platform Helm charts can be found, https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps

# Tasks
- [ ] Upgrade the Datadog Private Location Staging helm chart version in the Chart.yaml file
- [ ] Perform a sync in with Argo and see that the Datadog Private Location is deployed
- [x] Verify that Datadog Private Location is running as expected

# Acceptance Criteria
- [x] The upgraded Datadog Private Location helm chart is running as expected in EKS Staging 1.22
