### ISSUE TITLE
[EKS Upgrade] Upgrade & Deploy Cert Manager to EKS Staging 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51285]
# Description
Upgrade and deploy Cert Manager to the EKS Staging 1.22 cluster

# Notes
- Platform Helm charts can be found, https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps

# Tasks
- [ ] Upgrade the Cert Manager Staging helm chart version in the Chart.yaml file
- [ ] Perform a sync in with Argo and see that the Cert Manager is deployed
- [x] Verify that Cert Manager is running as expected

# Acceptance Criteria
- [x] The upgraded Cert Manager helm chart is running as expected in EKS Staging 1.22
