### ISSUE TITLE
[EKS Upgrade] Upgrade & Deploy External Secrets to EKS Staging 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51289]
# Description
Upgrade and deploy External Secrets to the EKS Staging 1.22 cluster

# Notes
- Platform Helm charts can be found, https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps

# Tasks
- [ ] Upgrade the External Secrets Staging helm chart version in the Chart.yaml file
- [ ] Perform a sync in with Argo and see that the External Secrets is deployed
- [x] Verify that External Secrets is running as expected

# Acceptance Criteria
- [x] The upgraded External Secrets helm chart is running as expected in EKS Staging 1.22
