### ISSUE TITLE
[EKS Upgrade] Upgrade & Deploy External DNS to EKS Staging 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51288]
# Description
Upgrade and deploy External DNS to the EKS Staging 1.22 cluster

# Notes
- Platform Helm charts can be found, https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps

# Tasks
- [ ] Upgrade the External DNS Staging helm chart version in the Chart.yaml file
- [ ] Perform a sync in with Argo and see that the External DNS is deployed
- [x] Verify that External DNS is running as expected

# Acceptance Criteria
- [x] The upgraded External DNS helm chart is running as expected in EKS Staging 1.22
