### ISSUE TITLE
[EKS Upgrade] Upgrade & Deploy Sentry to EKS Staging 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51297]
# Description
Upgrade and deploy Sentry to the EKS Staging 1.22 cluster

# Notes
- Platform Helm charts can be found, https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps

# Tasks
- [ ] Upgrade the Sentry Staging helm chart version in the Chart.yaml file
- [ ] Perform a sync in with Argo and see that the Sentry is deployed
- [ ] Verify that Sentry is running as expected

# Acceptance Criteria
- [ ] The upgraded Sentry helm chart is running as expected in EKS Staging 1.22

**Comment by ph-One** [comment]
Not applicable
