### ISSUE TITLE
[EKS Upgrade] Upgrade & Deploy Traefik to EKS Staging 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51291]
# Description
Upgrade and deploy Traefik to the EKS Staging 1.22 cluster

# Notes
- Platform Helm charts can be found, https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps

# Tasks
- [ ] Upgrade the Traefik Staging helm chart version in the Chart.yaml file
- [ ] Perform a sync in with Argo and see that the Traefik is deployed
- [ ] Verify that Traefik is running as expected

# Acceptance Criteria
- [ ] The upgraded Traefik helm chart is running as expected in EKS Staging 1.22
