### ISSUE TITLE
[EKS Upgrade] Upgrade & Deploy Grafana to EKS Production 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51308]
# Description
Upgrade and deploy Grafana to the EKS Production 1.22 cluster

# Notes
- Platform Helm charts can be found, https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps

# Tasks
- [ ] Upgrade the Grafana Production helm chart version in the Chart.yaml file
- [ ] Perform a sync in with Argo and see that the Grafana is deployed
- [ ] Verify that Grafana is running as expected

# Acceptance Criteria
- [ ] The upgraded Grafana helm chart is running as expected in EKS Production 1.22

**Comment by ph-One** [comment]
Not applicable
