### ISSUE TITLE
[EKS Upgrade] Upgrade & Deploy Goldilocks to EKS Production 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51307]
# Description
Upgrade and deploy Goldilocks to the EKS Production 1.22 cluster

# Notes
- Platform Helm charts can be found, https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps

# Tasks
- [ ] Upgrade the Goldilocks Production helm chart version in the Chart.yaml file
- [ ] Perform a sync in with Argo and see that the Goldilocks is deployed
- [x] Verify that Goldilocks is running as expected

# Acceptance Criteria
- [x] The upgraded Goldilocks helm chart is running as expected in EKS Production 1.22

**Comment by ph-One** [comment]
No changes are needed. Deploy to 1.22 as-is.
