### ISSUE TITLE
[EKS Upgrade] Upgrade & Deploy Loki Canary to EKS Production 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51309]
# Description
Upgrade and deploy Loki Canary to the EKS Production 1.22 cluster

# Notes
- Platform Helm charts can be found, https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps

# Tasks
- [ ] Upgrade the Loki Canary Production helm chart version in the Chart.yaml file
- [ ] Perform a sync in with Argo and see that the Loki Canary is deployed
- [x] Verify that Loki Canary is running as expected

# Acceptance Criteria
- [x] The upgraded Loki Canary helm chart is running as expected in EKS Production 1.22

**Comment by ph-One** [comment]
No changes are needed. Deploy to 1.22 as-is.
