### ISSUE TITLE
[EKS Upgrade] Upgrade & Deploy External DNS to EKS Utility 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51318]
# Description
Upgrade and deploy External DNS to the EKS Utility 1.22 cluster

# Notes
- Platform Helm charts can be found, https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps

# Tasks
- [ ] Upgrade the External DNS Utility helm chart version in the Chart.yaml file
- [ ] Perform a sync in with Argo and see that the External DNS is deployed
- [ ] Verify that External DNS is running as expected

# Acceptance Criteria
- [ ] The upgraded External DNS helm chart is running as expected in EKS Utility 1.22

**Comment by ph-One** [comment]
No changes are needed. Deploy to 1.22 as-is.
