### ISSUE TITLE
[EKS Upgrade] Upgrade & Deploy Datadog Agent to EKS Utility 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51316]
# Description
Upgrade and deploy Datadog Agent to the EKS Utility 1.22 cluster

# Notes
- Platform Helm charts can be found, https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps

# Tasks
- [ ] Upgrade the Datadog Agent Utility helm chart version in the Chart.yaml file
- [ ] Perform a sync in with Argo and see that the Datadog Agent is deployed
- [ ] Verify that Datadog Agent is running as expected

# Acceptance Criteria
- [ ] The upgraded Datadog Agent helm chart is running as expected in EKS Utility 1.22
