### ISSUE TITLE
[EKS Upgrade] Upgrade & Deploy Traefik to EKS Utility 1.22

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#51321]
# Description
Upgrade and deploy Traefik to the EKS Utility 1.22 cluster

# Notes
- Platform Helm charts can be found, https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps

# Tasks
- [ ] Upgrade the Traefik Utility helm chart version in the Chart.yaml file
- [ ] Perform a sync in with Argo and see that the Traefik is deployed
- [ ] Verify that Traefik is running as expected

# Acceptance Criteria
- [ ] The upgraded Traefik helm chart is running as expected in EKS Utility 1.22

**Comment by ph-One** [comment]
No changes are needed. Deploy to 1.22 as-is.
