### ISSUE TITLE
Research NPS utility, pros, cons for our purposes

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#51339]
## Issue Description
We're considering how and if to continue with an NPS as it currently exists in the Qtrly Satisfaction Survey.  This could take the form of multiple questions about areas/spaces/tasks.

What are the pros to NPS?
Cons?
What questions can NPS answer? Are those the questions Leadership and/or Platform need answered?
Is it relevant given the fixed audience of the Platform?

[Confluence page](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2471592053/Notes+on+NPS)

## Tasks
- [x] Research topic
- [x] Generate Confluence page with key learnings

## Acceptance Criteria
- [x] Confluence page reflects actionable takeaways

## For Review
- [x] Do the analysis and conclusions pass review by teammates?
- [x] What is missing from Pros and Cons?
