### ISSUE TITLE
Testing with VFS Teams for vets-api server from BRD to EKS

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#51346]
**INFORMATION TO BE INCLUDED IN TICKETS NESTED IN THIS EPIC**

**What’s happening?**
- As part of the testing process for vets-api server migration to EKS, we’ve tested healthcheck paths. Certain paths need to be fixed per testing. 
- We also need help testing endpoints (outside of the healthchecks). 

**Why is this important?**
- We want to verify expected behaviors from the endpoints, so the expected behavior(s) translate from BRD to EKS.
- It is important to have owners test their endpoints as you know these endpoints the best. This will also help speed up the process of moving from BRD to EKS.

**As a VFS/Platform Team, what do I need to do?**

**1. REVIEW [ENDPOINT OWNERSHIP DOCUMENT](https://docs.google.com/spreadsheets/d/1pj8D4cXtHta8VsO53Q3AUKBHwbjRmo3v0BJHUFuU-c0/edit?usp=sharing)**
- [ ] If there is anything that needs to change, this should be noted as a **comment** in this ticket
- [ ] **Within the comments of this ticket**, list out ALL of the endpoints associated with your app(s) listed in Column A.
- [ ] If the information is correct AND complete, please note in the comment section of **this ticket**

**2. VERIFY DEV SYNTHETIC TESTS VIA [DATADOG UI](https://vagov.ddog-gov.com/synthetics/tests?query=tag%3A%28%22team%3ATT1%22%29) and in [vets-api.yaml @ GitHub](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/datadog/catalog/synthetics/vets-api.yaml)**
- [ ] Verify the test from the inside of TIC firewall aka vfs-dev (if you do not have SOCKS access, please note in this ticket)
- [ ] Verify the test from the outside of TIC firewall aka revproxy-dev (going through the [Reverse Proxy](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594232/Reverse+Proxy))
- [ ] Check for missing tests or duplicated tests
- [ ] Note any issues with lack of test data and/or users in the comments section of this ticket.

**3. IF NEED, PERFORM MANUAL TESTING**
- [ ] Setup team account in [TestRail](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail)
- [ ] Upload test plans for manual testing
- [ ] Perform the testing and record test results in TestRail

----
Updated ticket info [1.19.23]
----

**What’s happening?**
We are in the process of migrating vets-api server to EKS (Amazon's K8 service), which will bring us one step closer to microservices. 
- As part of the testing process for vets-api server migration to EKS, we’ve tested healthcheck paths. 
- We also need help testing endpoints. This is where you come in!

**Why is this important?**
- We want to verify expected behaviors from the endpoints, so the expected behavior(s) translate from BRD to EKS.
- It is important to have owners test their endpoints as you know these endpoints the best. This will also help speed up the process of moving from BRD to EKS.

**As a VFS/Platform Team, what do I need to do? BY COB 2.1.2023**

**1. REVIEW [ENDPOINT OWNERSHIP DOCUMENT](https://docs.google.com/spreadsheets/d/1pj8D4cXtHta8VsO53Q3AUKBHwbjRmo3v0BJHUFuU-c0/edit?usp=sharing)**
- [ ] If there is anything that needs to change, this should be noted as a **comment** in this ticket and tag @ laineymajor
- [ ] If the information is correct AND complete, please check the box associated with this action item

**2. VERIFY DEV SYNTHETIC TESTS**
- [ ] Verify the test from the inside of TIC firewall aka vfs-dev (if you do not have SOCKS access, please note in this ticket)
- [ ] Verify the test from the outside of TIC firewall aka revproxy-dev (going through the [Reverse Proxy](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594232/Reverse+Proxy))
- [ ] Check for missing tests or duplicated tests
- [ ] Note any issues with lack of test data and/or users in the comments section of this ticket

**3. PER YOUR JUDGEMENT, IF NEEDED, PERFORM MANUAL TESTING**
- [ ] Complete necessary manual testing
- [ ] Link documentation, in the comments of this ticket, showing the completion of any manual testing

**4. Is your team the 'owner' of any of the following?If so, tag @ laineymajor in the comments**
As Tech Team 1 works on the migration of vets-api server to EKS, we are looking for the owners of the following forms:
- [ ] /v0/in_progress_forms/{id}
- [ ] v0/in_progress_forms#show
- [ ] v0/in_progress_forms#update,
- [ ] v0/in_progress_forms#destroy

**Comment by laineymajor** [comment]
While the preferred testing method for vets-api endpoints in EKS is Datadog Synthetics, VFS members don't currently have access to Datadog. To keep testing uniform and consistent, we are encouraging VFS teams to create a [Postman](https://www.postman.com/product/tools/) suite to hold their tests. Alternatively, you can record manual test run results in [Test Rail](https://dsvavsp.testrail.io/index.php?/dashboard).

Screenshots for instructions![Screen Shot 2023-01-11 at 8.22.09 AM.png](https://images.zenhubusercontent.com/61ba3abb874c1c3d7c47bf01/53a771e4-df8d-4907-b96b-1b64254f0060).

**Comment by laineymajor** [comment]
migration complete. good to close.
