### ISSUE TITLE
Get feedback on content strategy from partners

### ISSUE THREAD

**Issue by tygindraux** [department-of-veterans-affairs/va.gov-team#51351]
### Problem statement
The Login.gov Adoption team needs to communicate the legacy credential migration and DS Logon sunset to Veterans.

### Initiative
We have created a plan for how we communicate the migration to Veterans which needs to be shared with other partners, including VEO, MHV and eBen. We need to gather their feedback and update the strategy.

### Acceptance criteria
- [x] Strategy has been shared with VEO and feedback has been received
- [x] Strategy has been shared with MHV and feedback has been received
- [x]  Strategy has been shared with eBen and feedback has been received
- [x] Strategy has been updated based on feedback

### Tasks
- [x]   @CarlDickerson Iterate on content strategy as necessary (in partnership with VEO, Sitewide Content and MHV)
