### ISSUE TITLE
[Evidence Service to Lighthouse] get sandbox credentials to enable testing

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#51366]
## Background
All of the backend devs will need to request sandbox credentials from lighthouse in order to work on this project. Having sandbox credentials will allow us to make requests to lighthouse's sandbox environment and test with semi-real data

## Considerations
* Request sandbox credentials [here](https://developer.va.gov/onboarding/request-sandbox-access)
* For 'Organization name' I would put VA.gov
* Make sure to select the `VA Letter Generator API` checkmark under the `Client Credentials Grant APIs` section
* I used these 4 commands to generate the requested OAuth public key:
```sh
# Generate a private key
openssl genrsa -out key.pem 2048

# Generate the public/private key pair
openssl rsa -in key.pem -outform PEM -pubout -out public.pem

# Generate the jwk key pair
step crypto jwk create jwk.pub.json jwk.json --from-pem key.pem --alg RS256

# Copy the public jwk key to clipboard
pbcopy < jwk.pub.json
```

## Tasks
- [ ] @samcoforma has sandbox credentials
- [x] @jerekshoe has sandbox credentials
- [x] @kjduensing has sandbox credentials

**Comment by kjduensing** [comment]
Not sure what Lighthouse API corresponds to the evidence service - thinking it's benefits intake, but sent a slack message to @jerekshoe to confirm

**Comment by kjduensing** [comment]
It appears that the [document service](https://staging-developer.va.gov/explore/benefits/docs/benefits-documents?version=current) is only available in Lighthouse's staging environment. We're blocked from getting access to the sandbox env until this service is made available by lighthouse on the prod site: developer.va.gov/explore/benefits/docs/benefits-documents

**Comment by kjduensing** [comment]
https://dsva.slack.com/archives/C02CQP3RFFX/p1686156232563299

It's out of the hands of the API team, they're expecting to release it any day now.

**Comment by kjduensing** [comment]
I was told by Christopher Stone that one option would be to send an email requesting access with the last 5 characters of my existing client id. I used the one for the letters app sandbox client id:

```shell
Subject: Sandbox Access Request: Document Service API
Body:
Hello,

I was asked to provide the last 5 credentials of my client ID so that I could begin using the Sandbox Benefits Documents API.

Last 5 of client ID: xxxxx
API Requested: Benefits Documents API
<https://staging-developer.va.gov/explore/benefits/docs/benefits-documents>
Highest Access Requested: Sandbox

Thank you,
Kevin Duensing
```

**Comment by kjduensing** [comment]
Basis for comment above in [this Slack thread](https://dsva.slack.com/archives/C02CQP3RFFX/p1686156232563299)

**Comment by kjduensing** [comment]
@samcoforma @jerekshoe if y'all want to get this ticket checked off your lists, the above template in an email is the way to go. The Lighthouse team helped me out in under 24 hours.
