### ISSUE TITLE
[Evidence Service to Lighthouse] determine who is using our existing services

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#51367]
## Background
We should take some time and determine who is currently using the EVSS version of the service so that we can contact/coordinate with them

## Considerations
So far we are aware of 1 consumer: The mobile App. They will be using our service once it has been created

## Tasks
- [ ] Identify any other consumers of our existing service
- [ ] Reach out to mobile and send them our attribute mapping

## Acceptance Criteria
- [ ] Other consumers of the service are identified
- [ ] Those consumers have been contacted
- [ ] We have sent our attribute mapping to the mobile team
- [ ] Feedback has been dealt with
