### ISSUE TITLE
[Evidence Service to Lighthouse] map attributes

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#51365]
## Background
We should take some time to compare the existing `vets-api` endpoints and compare their outputs to the schema for the new VA Evidence Service API. It would be beneficial to document any changes so that we can potentially pass them on to any other consumers of our app

## Tasks
- [x] Identify any changes made to the request and response between EVSS and Lighthouse versions of the API
- [x] Document those changes so that we can pass easily pass those changes along to other consumers

### Changes:
Lighthouse requires parameters and file binary data to be uploaded as `multipart/form-data`

- Lighthouse supports an array of **tracked item IDs**, where as EVSS supports only a single tracked item ID
- Lighthouse requires a `systemName`
- Lighthouse requires a `fileNumber`

#### Lighthouse Upload Metadata Schema
```js
{
  trackedItemIds: [Int64],
  systemName: string,
  docType: string,
  fileNumber: string,
  claimId: Int64,
  filename: string
}
```

## Considerations
Are we going to have to use sidekiq if/when we migrate from ligthhouse?

## Acceptance Criteria
- [ ] Changes have been identified
- [ ] Changes have been documented
