### ISSUE TITLE
[Evidence Service to Lighthouse] modify FE code to use feature toggle

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#51369]
## Background
Once the feature toggle has been created, we can start modifying the FE to use the feature toggle to selectively show/hide components based on whether it is enabled or not. Most likely this will involve making copies of some of the components / functions and modifying them to work with the new letter-generator endpoints

## Tasks
- [x] Identify components/functions that need to be selectively shown/hidden based on the feature toggle value
- [x] Create duplicates of those components/functions
- [x] Modify the duplicates to work with the new evidence service endpoints
- [ ] Write new e2e/unit tests as needed

## Acceptance Criteria
- [ ] Components/functions that need to be duplicated are identified
- [ ] Appropriate duplicates have been created
- [ ] Duplicates have been modified to work with the new evidence service endpoints
- [ ] e2e tests / unit tests have been written as needed
- [ ] PRs have been created/requested for review

**Comment by HeatherWidmont** [comment]
@jerekshoe will review

**Comment by HeatherWidmont** [comment]
Annie reviewed & left comments, @samcoforma to work on this today

**Comment by HeatherWidmont** [comment]
@jerekshoe to review this probably by Wednesday

**Comment by HeatherWidmont** [comment]
Platform is reviewing right now
