### ISSUE TITLE
Request DNS Configuration for Internal VA Users

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#51362]
# Description
_To be done after https://github.com/department-of-veterans-affairs/va.gov-team/issues/51360_

This step is required so that traffic is routed properly while traversing the internal domain URL pathways.

The new `*preview-api.va.gov` domains will NOT automatically be available from locations within the VA network. The reason for this is that the VA has "Split DNS" implemented, which means that there are different DNS servers resolving DNS from within the network vs. outside of the network (i.e. external/public facing DNS):
1. Public users will resolve DNS on va.gov domains using the VA F5 devices as the authoritative DNS servers.
2. Internal VA users (CAG, GFE on VPN) will resolve DNS on va.gov domains using the VA domain controllers (which are essentially Windows servers) as the authoritative DNS servers.

To enable internal DNS resolution, the "VA Active Directory/Domain Controller team" will need to add a set of CNAMEs that point to the domains to the appropriate load balancers. To request this change, we needed to submit a Service Now (SNOW)/YourIT request to have these CNAMEs set up.

Text copied from: https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2231926890/ESECC+Request+-+Cloud+Isolation#Internal-DNS-Request

# Tasks
- [x] Submit a Service Now (SNOW)/YourIT request to have the CNAMEs set up. See instructions in [Confluence document](https://vfs.atlassian.net/wiki/spaces/CLOUD/pages/2231926890/ESECC+Request+-+Cloud+Isolation#Internal-DNS-Request).
- [x] Verify DNS resolution by issuing an nslookup command in a VA network-internal location. Instructions in the same Confluence document.

# Acceptance Criteria
- [x] DNS resolution is verified

**Comment by JoeTice** [comment]
Task was deprioritized for Sprint 20 based on additional time and focus and a change of direction required on [51937](https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/51937)

**Comment by CBonade** [comment]
![image.png](https://images.zenhubusercontent.com/60aa993146d844d86f494162/8601e167-a112-4cb2-8525-c3341dde3b83)

Tested and confirmed working! This is done.

**Comment by pjhill** [comment]
Looks good as far as we can tell -- once we have a preview environment up and running we can do some additional testing. Nicely done!
