### ISSUE TITLE
[Evidence Service to Lighthouse] sentry and datadog monitoring

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#51374]
[first-to-know] Set up sentry and datadog alerting for evidence service: Adds automation to our monitoring - if there's a problem, we'll be notified.

## Acceptance Criteria

- [ ] Ensure all team members are receiving Sentry alerts for Evidence Service
- [ ] Identify additional opportunity areas for tracking and monitoring evidence submissions
- [ ] Alerts integrated with Slack

## Task

- [ ] Set up issue ownership with Sentry
- [ ] Work with Steve Albers to set up DataDog monitor that has Slack integration.
