### ISSUE TITLE
[Letters App to Lighthouse] map attributes

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#51377]
## Background
We should take some time to compare the existing `vets-api` endpoints and compare their outputs to the schema for the new VA Letter Generator API. It would be beneficial to document any changes so that we can potentially pass them on to any other consumers of our app

## Considerations
* Lighthouse has a list of changes that have been made in Confluence and should be sending those over to us
* From looking at what vets-api returns and the Lighthouse API documentation, the main difference that has been noted so far by our team is that the Lighthouse `eligible-letters` endpoint seems to combine the responses that we would normally get from 2 different EVSS endpoints ('/' and '/letterBeneficiary`)

## Tasks
- [x] Identify any changes made to the response between EVSS and Lighthouse versions of the API
- [x] Document those changes so that we can pass easily pass those changes along to other consumers

## Result
The Lighthouse endpoint does indeed subsume beneficiary and letters info. The key differences are:

#### Letters field casing
```diff
# EVSS
"letters": [
   {
-     "name": "Benefit Summary Dependent",
-     "letter_type": "BENEFIT_SUMMARY_DEPENDENT"
   }
]

# Lighthouse
"letters": [
  {
+    "letterName": "Benefit Summary Dependent",
+    "letterType": "BENEFIT_SUMMARY_DEPENDENT"
  }
]
```

#### Full name structure
Notice that full name is within a new, LH-only block: `letterDestination`

```diff
# EVSS
-"full_name": "John A Smith"

# Lighthouse
+"letterDestination": {
+  "country": "USA",
+  "addressLine1": "2476 MAIN STREET",
+  "addressLine2": "STE # 12",
+  "addressLine3": "West",
+  "city": "RESTON",
+  "state": "VA",
+  "zipCode": "12345",
+  "fullName": "John A Smith"
+}
```

#### Military service
Military service info stays in the same structure, with casing differences. Also note, **the time format has changed**.

Field name casing:
```diff
# EVSS
-"military_service": [
  {
    "branch": "Army",
+    "character_of_service": "HONORABLE",
+    "entered_date": "1965-01-01T06:00:00.000+00:00",
+    "released_date": "1972-10-01T05:00:00.000+00:00"
}
# Lighthouse
+"militaryServices": [
  {
    "branch": "Army",
+    "characterOfService": "HONORABLE",
+    "releasedDateTime": "2016-02-04T17:51:56Z",
+    "enteredDateTime": "2016-02-04T17:51:56Z"
  }
]
```

Time format:
```diff
# EVSS
-"entered_date": "1965-01-01T06:00:00.000+00:00"
-"released_date": "1972-10-01T05:00:00.000+00:00"

# Lighthouse
+"enteredDateTime": "2016-02-04T00:00:00Z"
+"releasedDateTime": "2016-02-04T00:00:00Z"
```

### Benefit Information

**Field Names**: 
```diff
# EVSS
-"benefit_information": {
-  "monthly_award_amount": 0.0,
-  "service_connected_percentage": 100,
-  "award_effective_date": "2022-01-01T06:00:00.000+00:00",
-  "has_chapter35_eligibility": true,
-  "has_non_service_connected_pension": false,
-  "has_service_connected_disabilities": true,
-  "has_adapted_housing": false,
-  "has_individual_unemployability_granted": false,
-  "has_special_monthly_compensation": true
-}

# Lighthouse
+"benefitInformation": {
+  "serviceConnectedPercentage": 2,
+  "awardEffectiveDateTime": "2016-02-04T17:51:56Z",
+  "monthlyAwardAmount": {
+    "value": 2673,
+    "currency": "USD"
+  },
+  "serviceConnectedDisabilities": true,
+  "nonServiceConnectedPension": false,
+  "individualUnemployabilityGranted": false,
+  "chapter35Eligibility": true,
+  "specialMonthlyCompensation": false,
+  "adaptedHousing": false,
+  "chapter35EligibilityDateTime": "2016-02-04T17:51:56Z",
+  "hasDeathResultOfDisability": false,
+  "hasSurvivorsIndemnityCompensationAward": false,
+  "hasSurvivorsPensionAward": false
+}
```

**Monthly award structure**:
```diff
# EVSS
-"monthly_award_amount": 0.0

# Lighthouse
+"monthlyAwardAmount": {
+  "value": 2673,
+  "currency": "USD"
+}
```

**Field Additions**:
```diff
# EVSS
## N/A

# Lighthouse
+"chapter35EligibilityDateTime": "2016-02-04T17:51:56Z",
+"hasDeathResultOfDisability": false,
+"hasSurvivorsIndemnityCompensationAward": false,
+"hasSurvivorsPensionAward": false
```

### Additional info in Lighthouse
- messages array
- letter destination block

## Acceptance Criteria
- [ ] Changes have been identified
- [ ] Changes have been documented

**Comment by kjduensing** [comment]
@samcoforma I assigned us to this one - looks like a good pairing candidate

**Comment by kjduensing** [comment]
Lighthouse Letters API: https://developer.va.gov/explore/verification/docs/va_letter_generator?version=current

**Comment by kjduensing** [comment]
2 differences in available letter types appear to be:
1. Lighthouse specifies `VA benefit summary/award for dependents` where VA.gov does not list this for user 228
2. VA.gov lists Certificate of Eligibility for user 228 where Lighthouse does not. _NOTE: this is the one we should worry about, because Lighthouse specifically says that they don't generate this and to go to VA.gov to download this letter type_

**Comment by samcoforma** [comment]
EVSS `service.get_letters` example response (for user 228):

`{
  "status": 200,
  "letters": [
    {
      "name": "Commissary Letter",
      "letter_type": "commissary"
    },
    {
      "name": "Proof of Service Letter",
      "letter_type": "proof_of_service"
    },
    {
      "name": "Proof of Creditable Prescription Drug Coverage Letter",
      "letter_type": "medicare_partd"
    },
    {
      "name": "Proof of Minimum Essential Coverage Letter",
      "letter_type": "minimum_essential_coverage"
    },
    {
      "name": "Service Verification Letter",
      "letter_type": "service_verification"
    },
    {
      "name": "Civil Service Preference Letter",
      "letter_type": "civil_service"
    },
    {
      "name": "Benefit Summary Letter",
      "letter_type": "benefit_summary"
    },
    {
      "name": "Benefit Verification Letter",
      "letter_type": "benefit_verification"
    }
  ],
  "full_name": "Causes Tux Errors Jr"
}`

**Comment by samcoforma** [comment]
It looks like a new feature of the Lighthouse Letters API is its ability to return JSON formatted letter contents, in addition to PDF versions. Perhaps an opportunity to build out new ways to view letters online? https://developer.va.gov/explore/verification/docs/va_letter_generator?version=current

**Comment by samcoforma** [comment]
Currently it looks like the EVSS Beneficiary endpoint returns JSON that can be displayed inline on the front-end (Which refers to it as "Benefits Summary"), which suggests that we'd want to use the Lighthouse JSON endpoint to maintain that aspect of the functionality.

**Comment by samcoforma** [comment]
Example of EVSS beneficiary endpoint response (for user 228):

```{
  "status": 200,
  "benefit_information": {
    "monthly_award_amount": 0.0,
    "service_connected_percentage": 100,
    "award_effective_date": "2022-01-01T06:00:00.000+00:00",
    "has_chapter35_eligibility": true,
    "has_non_service_connected_pension": false,
    "has_service_connected_disabilities": true,
    "has_adapted_housing": false,
    "has_individual_unemployability_granted": false,
    "has_special_monthly_compensation": true
  },
  "military_service": [
    {
      "branch": "Army",
      "character_of_service": "HONORABLE",
      "entered_date": "1965-01-01T06:00:00.000+00:00",
      "released_date": "1972-10-01T05:00:00.000+00:00"
    }
  ]
}"

**Comment by kjduensing** [comment]
Maybe interesting to note that `Mobile::V0::LettersSerializer` appears to be doing some transformations on the Lighthouse response

**Comment by kjduensing** [comment]
(implying that they are currently using the Lighthouse letters API)

**Comment by kjduensing** [comment]
Yeah check out `Mobile::V0::LettersController`

**Comment by samcoforma** [comment]
Just a note based on what @jerekshoe told us: Mobile started implementing usage of Lighthouse API, but paused it and it's not being used yet.

**Comment by kjduensing** [comment]
The lighthouse response from `/eligible-letters`:
```json
{
  "messages": [
    {
      "key": "letterGeneration.letterEligibilityError",
      "text": "string",
      "severity": "WARN"
    }
  ],
  "letters": [
    {
      "letterName": "Benefit Summary Dependent",
      "letterType": "BENEFIT_SUMMARY_DEPENDENT"
    }
  ],
  "letterDestination": {
    "country": "USA",
    "addressLine1": "2476 MAIN STREET",
    "addressLine2": "STE # 12",
    "addressLine3": "West",
    "city": "RESTON",
    "state": "VA",
    "zipCode": "12345",
    "fullName": "John A Smith"
  },
  "militaryServices": [
    {
      "branch": "Army",
      "characterOfService": "HONORABLE",
      "releasedDateTime": "2016-02-04T17:51:56Z",
      "enteredDateTime": "2016-02-04T17:51:56Z"
    }
  ],
  "benefitInformation": {
    "serviceConnectedPercentage": 2,
    "awardEffectiveDateTime": "2016-02-04T17:51:56Z",
    "monthlyAwardAmount": {
      "value": 2673,
      "currency": "USD"
    },
    "serviceConnectedDisabilities": true,
    "nonServiceConnectedPension": false,
    "individualUnemployabilityGranted": false,
    "chapter35Eligibility": true,
    "specialMonthlyCompensation": false,
    "adaptedHousing": false,
    "chapter35EligibilityDateTime": "2016-02-04T17:51:56Z",
    "hasDeathResultOfDisability": false,
    "hasSurvivorsIndemnityCompensationAward": false,
    "hasSurvivorsPensionAward": false
  }
}
```

**Comment by kjduensing** [comment]
As the ticket says in the description, the 2 EVSS endpoints we call can be reduced to a single call from lighthouse.
