### ISSUE TITLE
[Evidence Service to Lighthouse] create fixtures

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#51371]
## Background
In order to easily facilitate development work for the FE portion of the evidence service app, we will need to create mock data that can be used by the backend to return responses that mimic the ones we would expect to receive in production. Because most of the external services we call (in this case Lighthouse) require appropriate credentials to authenticate with, it makes sense to return mock data from vets-api in most scenarios. Developers should not have to connect to the actual services unless they are doing BE work that requires it.

## Considerations
Repositories involved:
* https://github.com/department-of-veterans-affairs/vets-api-mockdata

## PR
department-of-veterans-affairs/vets-api-mockdata#269

## Tasks
- [ ] Identify what types of data need to be mocked
- [ ] Create/record the mock data files as needed

## Acceptance Criteria
- [ ] Data that needs to be mocked has been identified
- [ ] Mock data files have been created/recorded as needed
- [ ] PR(s) have been created / requested for review
