### ISSUE TITLE
[Evidence Service to Lighthouse] Create feature toggle for Evidence Service to Lighthouse claims migration

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#51370]
## Background
We are currently planning on releasing the Lighthouse version of the evidence service in phases, and in order to achieve that we will need to create a new feature toggle.

## Considerations
Feature toggle name: `evidence_service_use_lighthouse`

[Platform Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles)

Repos that will need updates:
* https://github.com/department-of-veterans-affairs/vets-api
* https://github.com/department-of-veterans-affairs/vets-website

## Tasks
- [ ] (BE) Create a new feature toggle named `evidence_service_use_lighthouse`
- [ ] (FE) Update the platform code to recognize the new feature toggle
- [ ] (FE) Create selectors in the evidence service app to select the feature toggle

## Acceptance Criteria
- [ ] Feature toggle is created
- [ ] FE platform code is updated to recognize the new feature toggle
- [ ] FE selectors created to get the value of the feature toggle
