### ISSUE TITLE
[Letters App to Lighthouse] get sandbox credentials to enable testing

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#51378]
## Background
All of the backend devs will need to request sandbox credentials from lighthouse in order to work on this project. Having sandbox credentials will allow us to make requests to lighthouse's sandbox environment and test with semi-real data

## Considerations
* Request sandbox credentials [here](https://developer.va.gov/onboarding/request-sandbox-access)
* For 'Organization name' I would put VA.gov
* Make sure to select the `VA Letter Generator API` checkmark under the `Client Credentials Grant APIs` section
* I used these 4 commands to generate the requested OAuth public key:
```sh
# Generate a private key
openssl genrsa -out key.pem 2048

# Generate the public/private key pair
openssl rsa -in key.pem -outform PEM -pubout -out public.pem

# Generate the jwk key pair
step crypto jwk create jwk.pub.json jwk.json --from-pem key.pem --alg RS256

# Copy the public jwk key to clipboard
pbcopy < jwk.pub.json
```

## Tasks
- [x] @samcoforma has sandbox credentials
- [x] @jerekshoe has sandbox credentials
- [x] @kjduensing has sandbox credentials
