### ISSUE TITLE
[Evidence Service to Lighthouse] testing/qa, unit tests for all endpoints

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#51372]
## Tasks
- [ ] Write RSpec tests for the service and the controller 

## Acceptance Criteria
- [ ] Test cases have been written for happy paths
- [ ] Test cases have been written for sad paths
