### ISSUE TITLE
[Letters App to Lighthouse] Determine who is using the existing service

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#51379]
## Background
We should take some time and determine who is currently using the EVSS version of the service so that we can contact/coordinate with them

## Considerations
So far we are aware of 1 consumer: The mobile App. They will be using our service once it has been created

## Tasks
- [x] Identify any other consumers of our existing service
- [x] Reach out to mobile and send them our attribute mapping

## Acceptance Criteria
- [ ] Other consumers of the service are identified
- [ ] Those consumers have been contacted
- [ ] We have sent our attribute mapping to the mobile team
- [ ] Feedback has been dealt with

**Comment by jacobworrell** [comment]
@kjduensing please do a quick search through the codebase to see if you can identify any other team using this service.

**Comment by kjduensing** [comment]
@jacobworrell after looking through the backend codebase, it looks like only mobile is using the `EVSS::Letters` service
