### ISSUE TITLE
[Letters App to Lighthouse] modify FE code to use feature toggle

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#51381]
## Background
Once the feature toggle has been created, we can start modifying the FE to use the feature toggle to selectively show/hide components based on whether it is enabled or not. Most likely this will involve making copies of some of the components / functions and modifying them to work with the new letter-generator endpoints

## Tasks
- [ ] Identify components/functions that need to be selectively shown/hidden based on the feature toggle value
- [ ] Create duplicates of those components/functions
- [ ] Modify the duplicates to work with the new letter-generator endpoints
- [ ] Write new e2e/unit tests as needed

## Acceptance Criteria
- [ ] Components/functions that need to be duplicated are identified
- [ ] Appropriate duplicates have been created
- [ ] Duplicates have been modified to work with the new letter-generator endpoints
- [ ] e2e tests / unit tests have been written as needed
- [ ] PRs have been created/requested for review
