### ISSUE TITLE
Update number of days to complete disability-related claims for December 2022

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#51387]
## Issue Description
We need to update the number of days it takes to complete disability related claims. Sitewide content needs to email Tanekwa Bournes on the first of the month to get the number from the previous month and input into Drupal.

This needs to be done on the following pages:
https://www.va.gov/disability/after-you-file-claim/
https://www.va.gov/disability/how-to-file-claim/

## Tasks
- [x] Email Tanekwa for most recent number (Randi)
- [x] Input number and new month into both Drupal pages (Aliyah)
- [x] Review and publish (Megan)

## Acceptance Criteria
- [x] Most current number of days is on live site.

**Comment by RLHecht** [comment]
@aliyahblackmore Tanekwa emailed the info for December. Please update both pages to 110.0. Thanks!

**Comment by aliyahblackmore** [comment]
Hi @megzehn these pages are ready for you!

The VA claim process after you file your claim
**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=870
**Notes**: I left the current revision (published 12/2/22 - 2:12 pm)  made changes. I believe we'd need to revert back to last drafted version and add the number for December after we publish (this is a 12/5/22 - 3:54pm draft version).

How to file a VA disability claim 
**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=905
**Notes:** I left the current revision (published 12/2/22 - 2:08 pm) and made the changes. I believe we'll need to revert back to the last drafted version and add that number for December after we publish (this is a 12/5/22 - 2:34pm draft version).

**Comment by megzehn** [comment]
These are now both published! Thanks, @aliyahblackmore and @RLHecht.

**Comment by RLHecht** [comment]
These changes are live. Closing ticket.

**Comment by aliyahblackmore** [comment]
Updating: Now that this is published, I reverted to the 10/19/2022 - 4:15pm draft version and added the December number. This version had our changes that we need stakeholders to review.

**Preview link**: http://preview-prod.vfs.va.gov/preview?nodeId=905
