### ISSUE TITLE
[Letters App to Lighthouse] Create feature toggle for Letters service to claims migration

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#51382]
## Background
We are currently planning on releasing the Lighthouse version of the letters service in phases, and in order to achieve that we will need to create a new feature toggle.

## Considerations
Feature toggle name: `letter_generator_use_lighthouse`

[Platform Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles)

Repos that will need updates:
* https://github.com/department-of-veterans-affairs/vets-api
* https://github.com/department-of-veterans-affairs/vets-website

## Tasks
- [x] (BE) Create a new feature toggle named `letter_generator_use_lighthouse`
- [x] (FE) Update the platform code to recognize the new feature toggle
- [x] (FE) Create selectors in the letters app to select the feature toggle

## Acceptance Criteria
- [x] Feature toggle is created
- [x] FE platform code is updated to recognize the new feature toggle
- [x] FE selectors created to get the value of the feature toggle
