### ISSUE TITLE
Update names on Platform website after personnel changes

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#51391]
## User Story
As a VFS team member, I want to know who the correct point of contacts are so that I am not attempting to reach someone who is no longer involved with the VA.gov Platform. 

Assignee: @briandeconinck 
Peer Reviewer: @shiragoodman 

## Description
Thomas Delrue left OCTO-DE on 12/16/2022. He is still listed as the Platform Security lead on the [Collaboration Cycle Contact Us](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/contact-us#Contactus-OCTOPracticeAreaLeads) page and must be removed. This ticket will also verify that he is not listed elsewhere on Platform Website. 

## Impacted Artifacts
[Contact Us](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/contact-us#Contactus-OCTOPracticeAreaLeads) - OCTO Practice area leads

## Tasks
- [x] Remove Thomas' name from the Contact Us page and replace with "TBD"
- [x] Remove Jason Woodman's name from the Contact Center team as PM and replace with Anita Middleton
- [x] Remove Joni Chan's name from the Sitewide Content & IA team and replace with "TBD"
- [x] Search all other pages of Platform Website for Thomas' name. If found, document where below:
   - No other instances found

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Thomas Delrue has been removed from Platform Website
- [ ] Jason Woodman has been removed from the Contact Center section and replaced with Anita Middleton
- [ ] Joni Chan has been removed from the Sitewide Content & IA section and replace with TBD

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
This is ready for review @shiragoodman. Changes made to Platform website, should be published later today.

**Comment by shiragoodman** [comment]
@briandeconinck your changes look good, however I noticed today that we still have Joni listed as IA under Sitewide Content & IA team. Could you replace her name with "TBD" ? Thank you!

**Comment by briandeconinck** [comment]
@shiragoodman Joni has been removed from the [Contact Us page](https://vfs.atlassian.net/wiki/spaces/CC/pages/1764524036/Contact+us), should be published to Platform website later today.

I've also updated the tasks, acceptance criteria, and title of this ticket to reflect the work done!

**Comment by briandeconinck** [comment]
Platform website changes published: [Contact Us](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/contact-us).
