### ISSUE TITLE
Migrate content about SGLI increase to $500,000

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#51402]
## Issue Description
Steve Fital asked us to add a link to [this legacy page](https://www.benefits.va.gov/INSURANCE/SGLI-increase-faqs.asp) about an upcoming SGLI coverage increase. The increase will happen on March 1, 2023. Veterans can opt out of the coverage starting on that date. 

First we'll make evergreen updates on March 1. Then we'll assess how to migrate the FAQ content to our modernized pages and redirect the legacy page.

---
## Tasks
- [x] Add new rates to SGLI and VGLI pages (Katherine)
- [x] Review (Laura)
- [x] Send to Steve for review (Laura)
- [x] Copyedit/prepub (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] 2 pages are updated with new rates

**Comment by laurwill** [comment]
Update: As a first step, we'll add an info alert to the top of the SGLI page about the increase and link to the existing legacy FAQ. 

Next steps:
- Make evergreen updates to SGLI and VGLI pages for March 1
- Assess which questions from the FAQ to migrate, if any
- Redirect FAQ to SGLI page after the end of March

**Comment by laurwill** [comment]
Hi @megzehn ,
I added an info alert to the SGLI page as the initial step in this work — could you copyedit before I send over to Steve?

http://preview-prod.vfs.va.gov/preview?nodeId=767

**Comment by megzehn** [comment]
Hi @laurwill, this looks good! Confirming I copy edited the info alert.

**Comment by RLHecht** [comment]
Moving this to the backlog until we're ready to pick up the second part of this work for March 1.

**Comment by laurwill** [comment]
Update: Katherine input the March 1 rate changes, I made additional edits for March 1 changes, checked the rates, and sent to Steve for accuracy review. Changes included:
- Updated info alert on SGLI page
- New rates in tables on both pages 
- Small content changes to "What benefits can I get" sections to match new rates

@megzehn just getting this on your radar for early next week — we'll need to copyedit the updates to these 2 pages and publish the morning of March 1 (next Wednesday).

After we publish these updates, we'll open a new ticket to migrate the FAQ content that's still relevant after March 31, if any.

**Comment by laurwill** [comment]
Hi @megzehn , Steve approved changes, so these 2 pages are ready for copyedit. But please **hold to publish until March 1**. 
SGLI: http://preview-prod.vfs.va.gov/preview?nodeId=767
VGLI: http://preview-prod.vfs.va.gov/preview?nodeId=769

And a couple notes: 
- I already checked the rates numbers against the source, so no need to do that step
- These pages have some older content on them. If you see smaller incremental changes you want to make, I think that's okay — but let's hold off on more substantive changes since we're doing an audit/migration in the life insurance section. 

Let me know if you have questions. Thank you!

**Comment by laurwill** [comment]
Also noting re: the potential migration task for the SGLI increase FAQ — the teamsite SGLI FAQ page had 14 total page views since Jan 1 of this year. And term "SGLI increase" had 8 total volume in site search for that same period. So it seems not many people are currently using this content.

I'll plan to check analytics again in March to see if this changes.

**Comment by megzehn** [comment]
Thanks, @laurwill. Confirming I copy edited these changes and published today. CC @RLHecht.

**Comment by RLHecht** [comment]
Pages are live. Closing ticket.
