### ISSUE TITLE
Modify asynch Midpoint Review response and appointment

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#51401]
## User Story
As a VFS team member, I want to be given current, accurate guidance on asynch midpoint reviews so that I'm not completing unnecessary tasks. 

Assignee: @sterkenburgsara 
Peer Reviewer: @allison0034 

## Description
The Slack response for asynch Midpoint review requests is the same as synchronous Midpoint Review requests. It states:

> Your review is confirmed for January 5, 2023 1:30 pm ET. Check off the VFS actions in the ticket including:

- > If needed, add any additional VFS attendees, including accessibility and POs, to the invite on your calendar
- > Link all artifacts ONLY in the Midpoint Review artifacts section at least two days before the scheduled Midpoint Review. Do NOT add artifacts to Comments section
- > Specify which which pages in the prototype are included or excluded from the review

> Note: if you do not provide artifacts or we do not know which pages are included in the review at least two days prior, we will reschedule the review.

The first bullet is not applicable for a midpoint review and the operational guidance should be modified so Governance team members are not stating that for asynch.

In addition, the appointment that gets sent out still has "Zoom Meeting" in the location of the appointment. This is default from Calendly and should be deleted when the appointment is sent out to the Midpoint Review distribution list.

## Impacted Artifacts
[Midpoint Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Moderator+Responsibilities)
[Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)

## Tasks
- [x] Remove first bullet "If needed, add any additional VFS attendees, including accessibility and POs, to the invite on your calendar" from Slack message template on Confluence.
- [ ] Modify language in [midpoint code block](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities) on Collab Cycle Kickoff Moderator Responsibilities page: edit the "before meeting" VFS actions to indicate that the "add guests" step is not applicable for asynchronous reviews. (2/15/23 - per conversation in comments of this ticket, decided against this step).
- [x] Provide directions within moderator responsibilities for Midpoint that on-support person should delete Zoom information before sending out an invitation to an asynchronous midpoint (added Step 3). 
- [x] Edit Slack reply message for [midpoint](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Moderator+Responsibilities) to indicate that the async review has been schedule & no meeting will take place.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS teams scheduling asynch Midpoint Reviews are not given unapplicable directions
- [x] The Midpoint Review appointment does not imply that there is a Zoom meeting.

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@sterkenburgsara please be sure to document your tasks and/or steps taken. And feel free to modify the AC if you feel it does not correctly capture the goal of the modification.

**Comment by sterkenburgsara** [comment]
@shiragoodman also adding the GH ticket as an additional artifact to modify. We will need to provide some messaging in the first checkbox under "VFS actions" in midpoint section to indicate that inviting additional attendees is only a requirement for a synchronous midpoint review.

**Comment by shiragoodman** [comment]
sounds good, @sterkenburgsara !

**Comment by sterkenburgsara** [comment]
@allison0034 ready for your review

**Comment by allison0034** [comment]
@sterkenburgsara @shiragoodman  I have a question. For this task...

Modify language in [midpoint code block](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities) on Collab Cycle Kickoff Moderator Responsibilities page: edit the "before meeting" VFS actions to indicate that the "add guests" step is not applicable for asynchronous reviews.

I am wondering if they may want to add guests to the invite so everyone on their team knows when their review is. Just like we add our group email still, even tho we do not attend. What do you think? I do not think we have heard anyone complain about async reviews and this being an issue? Maybe we could change the language but I do not think we need to since we say no meeting will take place.

**Comment by allison0034** [comment]
@sterkenburgsara @shiragoodman I would also add something to the Slack thread reply. I know Matt Dingee asked why we still scheduled the async reviews. Maybe something like...

Your asynchronous review is confirmed. No meeting will take place. Governance team members will provide feedback by EOD on Date, Time. Check off the VFS actions in the ticket including:

- Link all artifacts ONLY in the Midpoint Review artifacts section at least two days before the scheduled Midpoint Review. Do NOT add artifacts to Comments section
- Specify which which pages in the prototype are included or excluded from the review

Note: if you do not provide artifacts or we do not know which pages are included in the review at least two days prior, we will reschedule the review.

**Comment by sterkenburgsara** [comment]
@allison0034 These are great insights. To Matt's point about why we even schedule async midpoint, honestly it's a valid question. I agree that is confusing! But if we are going to edit and say in Slack message that no meeting will take place, isn't it odd then to have a calendar invite & ask the team to invite people?

**Comment by allison0034** [comment]
@sterkenburgsara yeah maybe we add more to it like this is a placeholder or something. I think the whole team would want to know when the review is happening so they know when to expect feedback. They wont know when the meeting is happening unless they have it on their calendar. Think of it as a reminder, not an event.

Same reason we add our group to the invite even tho there is no meeting.

**Comment by allison0034** [comment]
@sterkenburgsara I guess you could remove it and just assume the PM will forward the invite to anyone they want to get the reminder

**Comment by sterkenburgsara** [comment]
@allison0034 that makes sense. I'll follow your recommendations.

**Comment by sterkenburgsara** [comment]
@allison0034 I removed the text about "inviting guests to the review" not being applicable so that teams can decide for themselves like you suggested. Also updated Slack message guidance per your suggestion. Can you review again?

**Comment by allison0034** [comment]
@sterkenburgsara looks good, you can close!
