### ISSUE TITLE
Consider Implement Accessibility Feedback for "View Dependents" (Description List)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#5140]
## Goal 
For "View Dependents" on staging, consider some accessibility improvements so the application has more clarity for those with cognitive issues.

## Considerations
- [Link to XD mockup](https://xd.adobe.com/view/8cdfe895-c907-4662-7234-305056778b2a-faee/)
- [Detailed notes on feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4664)
- Do some research on nesting within the `<dl>` (15 minutes with Jennifer and Platform)
  - This could have implications on other future cards - is there a process for this to be implemented within the design pattern

## Tasks
- [x] Collaborate with Jennifer Strickland on accessibility improvements
- [x] Incorporate feedback into staging, if applicable

## Acceptance Criteria
- [x] Jennifer Strickland has been notified of changes noted below

**Comment by jenstrickland** [comment]
For the individual dependents, recommend using a `<dl>` for the whole list of them. Each dependent would be marked up as:

```HTML
<dl>
  <dt>
    <dfn class="screen-reader-only-class">Name: </dfn> Dependent A's Actual Name
  </dt>
  <dd>
    <dfn>Label: </dfn> Data 
  </dd>
  <dd>
    <dfn>Label: </dfn> Data 
  </dd>
  <dd>
    <dfn>Label: </dfn> Data 
  </dd>
  <dt>
    <dfn class="screen-reader-only-class">Name: </dfn> Dependent B's Actual Name
  </dt>
  <dd>
    <dfn>Label: </dfn> Data 
  </dd>
  <dd>
    <dfn>Label: </dfn> Data 
  </dd>
  <dd>
    <dfn>Label: </dfn> Data 
  </dd>
  <dt>
    <dfn class="screen-reader-only-class">Name: </dfn> Dependent C's Actual Name
  </dt>
  <dd>
    <dfn>Label: </dfn> Data 
  </dd>
  <dd>
    <dfn>Label: </dfn> Data 
  </dd>
  <dd>
    <dfn>Label: </dfn> Data 
  </dd>
</dl>
```

**Comment by cohnjesse** [comment]
@jenstrickland I have a question about this implementation of  definition list, the area that renders the list is dynamic, meaning that it may render a list of dependents or it may render a simple set of paragraphs saying that there are no dependents to list. The list itself wraps this area, meaning in your currently suggestion the rendered HTML if there were no dependents on the list would look like this 

```
<h# aria-described="id-of-the-dl">That heading above</h#>
<dl id="id-of-the-dl">
  <dt>
    You have no dependents on this list
  </dt>
</dl>
```

Would that be ok? It seems like it would not be semantic at that point since it is not a list at that point but rather a single thing.

**Comment by jenstrickland** [comment]
@cohnjesse That does not look ideal. I wonder if the logic could be established at the start of the content the content block? 

For page 5 of the XD mockup, I wonder if the structure would be as follows:

```html
<h1>Your VA dependents</h1>
<dl>
    <dt>We don't have dependents information on file for you</dt>
    <dd>We can't find any dependents added to your…<!-- etcetera --></dd>
    <dd><a href="#link">Find out how to add… <!-- etcetera --></a></dd>
</dl>
```

For page 9 of the XD mockup, perhaps:
```html
<h1>Your VA dependents</h1>
<p class="va-introtext">
    Below is a list of dependents we have on file… <!-- etcetera -->
</p>
<button>Add or remove a dependent</button>

<h2>Dependents on your VA benefits</h2>
<p>The following dependents– <!-- etcetera --></p>
<p><a href="#link">Learn more about adding… <!-- etcetera --></a></p>
<p>We have no record of dependents on your VA benefits.</p>

<h2 aria-described="id-of-the-dl">Dependents not on your VA benefits</h2>
<p>The following… <!-- etcetera --></p>
<p><a href="#link">Learn more about… <!-- etcetera --></a></p>
<dl id="id-of-the-dl">
    <dt>Taylor Smith</dt>
    <dd><dfn>Relationship:</dfn> Child</dd>
    <!-- etcetera -->

```

**Comment by cohnjesse** [comment]
@jenstrickland Yes, we can change the logic to make this happen. Thanks!
