### ISSUE TITLE
Survey:  create the new survey

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#51416]
## Issue Description
Given the discussions and learnings of previous tickets, draft a new potential Survey to replace the existing one.  It should take input based on a scale, and might ask questions about multiple areas.

The questions to include are in #51973.

We may also investigate a second vector to capture how serious a respondent feels about each input.

If we continue the survey, it makes sense to pivot away from the NPS vernacular and more toward a “Happiness” or “Experience” scale of this 1-5 range.

Note that even Confluence is using a "Happiness Scale", represented by smiley faces of varying degrees.

Note: this is definitely an item that is a Bet, and we will learn and pivot as needed.

[Mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1674750854583/b90ca64265b003af9d8f80b9b4452f1f5947adae?sender=u4f7db1750f2355f805e60296) on ideating how to deliver the questions in a "where they grumble" way

## Tasks
- [x] Create new Survey in Optimal Workshop (or alternate choice)
 [Team will review](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2548498463/Survey+Tool+Comparison)
- [x] Bryan
- [x] Nicole
- [x] Dan
- [x] Run a pilot test with a VFS team member

## Acceptance Criteria
- [x] Reviewers can read the survey questions and understand the scale
- [x] Pilot test with at least 1 VFS team member has been completed

**Comment by twoangstroms** [comment]
Added a few options to visualize how this might work: https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1673368733345/b7836c53bbea7296f9a3ed20f2abf04bbaf57029?sender=u4f7db1750f2355f805e60296

**Comment by twoangstroms** [comment]
[Recommendations on how to format questions](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2491383911/Quant+Measure+Options+Likert+Scales+and+Others)

**Comment by twoangstroms** [comment]
Updated [Quant Measurements](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2491383911/Quant+Measure+Options+Likert+Scales+and+Others) page

**Comment by twoangstroms** [comment]
Added [Notes on Stripe's journey with this](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2499936498/Continuous+feedback+notes+from+Stripe+s+Rebecca+Murphey)

**Comment by steel36** [comment]
Resources reallocated due to team members being OoO unexpectedly this sprint.

**Comment by twoangstroms** [comment]
[Conditional formatting for questions in Airtable](https://support.airtable.com/docs/conditional-form-fields)
