### ISSUE TITLE
[UX] [SPIKE] Accessing expired pre-check-in link

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#51411]
## Tasks

Note: [day of check in conversation thread is here ](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/49521)

- [x] Review and confirm the error message that appears when a Veteran re-opens their browser and pre-check-in loads
- [x] Determine if the error message is succinct
- [x] Confirm issue and/or resolution with engineers (e.g., through brainstorm) 
- [x] Determine with engineers how GA might be amended 
- [x] Create new wireframe with content 
- [ ] Add new wireframe to Abstract in new branch 
- [x] Determine if sitewide content should review new content

## AC

- [ ] New wireframe and content are in Abstract
- [x] Determine if sitewide content should review new content
- [ ] Solution reviewed with engineers
- [x] Determined next steps for how GA might be amended

**Comment by kellysmith1008** [comment]
Sketch for check-in can be found in #49521 - might be able to use similar wording for pre-check-in, but need to investigate more the reasons people would land here.

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 @brianseek @acrollet Sorry to tag all three of you on the ticket, but I'd like to see if I could schedule a quick meeting with you over this error wording? Unlike with check-in, there's no number for a Veteran to text for pre-check-in if they arrive here and the error displays. In that case, would we want to redirect them to the SMS link? Reload the page? Close the browser? I'd like to have a quick meeting just to discuss some options. I'll set something up - but if you can't make it, feel free to skip and just provide input here :) Thanks!

**Comment by kellysmith1008** [comment]
Ahhh sugarcrap! I'll try and fix it but I included 3 options via pdf as well in the meantime. Sorry about that!

[PCI End of interactions.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/10459720/PCI.End.of.interactions.pdf)

**Comment by benbrasso-agile6** [comment]
Having things to look at during the meeting is awesome. Thanks for doing that.

**Comment by kellysmith1008** [comment]
After meeting with Ben, Brian, and Adrian, we are opting for updating the current error message to be similar to the check-in end of interaction, and we will keep the error URL the same. Ben is aware of what needs to change in GA and [the new wireframe has been created in sketch. ](https://www.sketch.com/s/b9c1f8ff-a09b-44d4-b8e0-245b4e0d4136). Moving this to validate for review by @benbrasso-agile6 and @loripusey

**Comment by benbrasso-agile6** [comment]
When you say the new wireframe has been created... who is working on it? I think we will want to assign this ticket to Ya-ching and give her the content to be able to create the wireframe. Right?

**Comment by kellysmith1008** [comment]
I created it. I copied one that @ytsaoca worked on for check-in and edited it.

**Comment by benbrasso-agile6** [comment]
Ok. Can you check the link? It is taking me to the original 3 options.

**Comment by kellysmith1008** [comment]
Did you refresh? It's been altered since last save - if you wouldn't mind trying again, and I'll add a screenshot here too:
![image.png](https://images.zenhubusercontent.com/63346ebd45ab78d62eea3201/4003c1f0-2ae3-47da-af69-21b113b51d93)

**Comment by benbrasso-agile6** [comment]
Let's chat about it in the am :)

**Comment by ytsaoca** [comment]
A quick question. We already had an error for expired link. Errors - Link Expired - No UUID
![Errors - Link Expired - No UUID.jpg](https://images.zenhubusercontent.com/6148b41faabf78b679dbacff/4f4cb46b-89f1-4fa1-a71a-afcda9097e4e)

Is this ticket a new and separate page or is the new version for this Errors - Link Expired - No UUID and I need to update the H1?

**Comment by kellysmith1008** [comment]
@ytsaoca @benbrasso-agile6 may be able to add more insight, but this is different than a no-token error message. This is when there's a previous "active" session and the Veteran lands on an error message because it's not reading a new session. So what we're trying to convey to them is that they haven't done anything wrong. Where Ben might be able to provide more information in terms of how this is tracked in GA is if we need both messages since they cover 2 different scenarios or if updating the H1 on this message will work. I don't know enough about how he's tweaking the GA report - sorry!

**Comment by ytsaoca** [comment]
@kellysmith1008 Now worries. Thanks for the response. 
I've created the mockup on abstract. https://share.goabstract.com/638e1b8d-413a-4924-aca5-2936eba4dd0d?collectionLayerId=6e8b6892-b277-42d7-a725-58357865be23&mode=design

@benbrasso-agile6  Just let me know if we need both messages or if we just keep the new one.

**Comment by ytsaoca** [comment]
@kellysmith1008 Now worries. Thanks for the response. 
I've created the mockup on abstract. https://share.goabstract.com/638e1b8d-413a-4924-aca5-2936eba4dd0d?collectionLayerId=6e8b6892-b277-42d7-a725-58357865be23&mode=design

@benbrasso-agile6  Just let me know if we need both messages or if we just keep the new one.

**Comment by ytsaoca** [comment]
According to @benbrasso-agile6 , we're updating the H1, and we won't use the old mockup. Marked the old one as unused and here's the new one: the mockup on abstract. https://share.goabstract.com/638e1b8d-413a-4924-aca5-2936eba4dd0d?collectionLayerId=6e8b6892-b277-42d7-a725-58357865be23&mode=design

'cc @loripusey

**Comment by loripusey** [comment]
I copied the wireframe link to this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52492)

**Comment by loripusey** [comment]
can we close this ticket now @ytsaoca ?

**Comment by ytsaoca** [comment]
@loripusey  Yes!
