### ISSUE TITLE
Internal - Profile Edge Case - Data Modeling (continued)

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#51415]
## Issue Description
This ticket is a continuation of #49994 as the follow up to the [Discovery ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49063) for the [Profile edge case request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46861).

The purpose of this ticket is to complete the data modeling needed to create the new datasets for the Profile KPIs.

[KPI worksheet](https://docs.google.com/spreadsheets/d/15NKyGxXm9d43iGUoWMxKmo0NZv4gW3dX1sFIeVhGt_I/edit#gid=2091635579)
[Mock up](https://docs.google.com/presentation/d/1zzFSi5ZfIDqy5buQZX1NwRjvCA-dwPTDYOaSidCwZlw/edit#slide=id.g11b31d375b2_0_0)
[New dataset request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=obrienjulie&labels=analytics-insights&template=analytics-internal-dataset-request.md&title=Analytics+Internal+-+New+Dataset+Request+Template)

---
## Tasks
- [x] Complete mock up based on agreed upon KPIs in support of this ticket - meeting 11/29 to finalize)
- [ ] Define data needs (nd complete data request ticket as part of standard process)
- [ ] Create BQ tables/views/dataset as needed 
- [ ] QA data

## Acceptance Criteria
- [ ] Datasets have been completed and handed off to analyst to create dashboards.
---
