### ISSUE TITLE
Login.gov adoption team: Sprint 11 (1/5/23 - 1/18/23) 

### ISSUE THREAD

**Issue by elizabethkochBT** [department-of-veterans-affairs/va.gov-team#51412]
## PTO/availability

- Federal holiday 1/16
- Elizabeth 1/16-1/17
- Ksenia 1/9-1/20
- Steve 1/5-1/6

## Sprint 11 Priorities

Legacy Credential Migration:
- Create and introduce milestones across the migration roadmap
- Define measurements across migration content strategy
- Get feedback on content strategy from VEO, MHV, eBen and update strategy as needed
- Define potential user flows for grandfathering in partnership with IAM
- Present to Login.gov
- Present to OCC
- Gather data to provide a baseline of DS Logon and develop metrics to measure against
 
## Retro Board

[Sprint 10](https://easyretro.io/publicboard/lAyuCkdXHCTaEpAy9ZH11t3Orhc2/be9314d0-06b2-45af-81d2-2f05beaa616c)
### Discussion Topics/Retro Action Items
- [x] Review team charter and set norms.
- [x] Finalize team roles and responsibilities.

### Onboarding
- [x] Adding [Melissa Miller] to DSVA Slack #51621
- [x] Add User to Org: [Melissa Miller] [#13964](https://github.com/department-of-veterans-affairs/github-user-requests/issues/13964)
- [x] Add User to Org: [Anthony Levin-Decanini] [#13941](https://github.com/department-of-veterans-affairs/github-user-requests/issues/13941)

### Legacy credential migrations & Login.gov proactive adoption
 - [ ] Get feedback on content strategy from partners #51351
 - [x] Draft migration comms/content strategy #51349
 - [ ] High-level user flows for grandfathering solution #51506
 - [ ] Design Datadog dashboard #51023
 - [x] Define potential user flows for grandfathering #51500
 - [x] Gather the number of existing accounts by credential #51018
 - [x] Create and introduce milestones across the migration roadmap #51890
 - [x] Prepare presentation for OCC Jan 12 at 1-2pm EST #51082
 - [x] Prepare presentation for Login.gov on January 24 (time TBD) #50690

**Comment by tygindraux** [comment]
Update: I've shared the roles and responsibilities exercise on Slack again, with a Monday 11 am EST deadline for those who haven't already completed the second part of the exercise to do so async.
