### ISSUE TITLE
[PM] Onsite Notifications v2: Collab cycle kick-off

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#51423]
## Background
To begin onsite notifications v2 we'll need to begin the collaboration cycle by requesting a kick-off. Information about the collaboration cycle and kick-off process can be found [here](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/collaboration-cycle-kickoff).

## Tasks
- [ ] Gather materials for kick-off
- [ ] Submit [kick-off ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-review%2Ccollaboration-cycle%2CCC-Request&template=collaboration-cycle-request.yml&title=Collaboration+Cycle+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D)
- [ ] Perform any follow-up items from kick-off

## Acceptance Criteria
- Kick-off is submitted and completed

**Comment by ajakabcin** [comment]
Moving to backlog until mid-April when we can resume conversations with partners about prescription shipment notifications.

**Comment by ajakabcin** [comment]
Closing out - this work was paused indefinitely
