### ISSUE TITLE
Update or add unit tests for global platform utilities

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#51429]
## Issue Description
As part of the Postmortem work for https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/674.  An increase in unit tests for globally available platform utilities to ensure appropriate changes do these files do not break or cause bugs. (This can be part of an ongoing epic to add)

## Tasks
- [ ] Add unit tests for `platform/utilites/api/index.js` to ensure good code coverage
- [ ] Add unit tests to other platform available/imported code to ensure good code coverage

## Acceptance Criteria
- [ ] Unit tests are added to platform-wide utility and helper functions that are imported in other applications (example: `apiRequest`
