### ISSUE TITLE
Update NADL rate-HOLD TO PUBLISH UNTIL 1/9/23

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#51426]
## Issue Description

The interest rate on our [NADL page](https://www.va.gov/housing-assistance/home-loans/loan-types/native-american-direct-loan/) is changing as of 1/9/23. The new number is **6.00%**

We need to update the page and publish on the morning of 1/9.

## Tasks
- [x] Update interest rate (Aliyah)
- [x] Copyedit (Megan)
- [x] Publish (Megan)
- [x] Notify VA partner that change is live (Randi)

## Acceptance Criteria
- [x] New interest rate is live on the site

**Comment by aliyahblackmore** [comment]
Hi @megzehn this is ready for you to review and publish on 1/9/23! 
**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=758

**Comment by RLHecht** [comment]
I published this. I changed 6.00 to 6. The decimal for the percent seems unnecessary since there aren't any other numbers we're listing.

**Comment by RLHecht** [comment]
change is live. Closing ticket.
