### ISSUE TITLE
Updates to How to apply for a burial allowance page-HOLD TO PUBLISH UNTIL 1/5/23

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#51428]
## Issue Description

Angie sent us changes that need to be made to our [How to apply for a Veterans burial allowance](https://www.va.gov/burials-memorials/veterans-burial-allowance/) page. We need to add a new row to one of the charts with information as of January 5, 2023. 

Content to update: [https://app.zenhub.com/files/133843125/a2789e9e-c5f3-47ad-b5d1-2f939187b07a/download](https://app.zenhub.com/files/133843125/a2789e9e-c5f3-47ad-b5d1-2f939187b07a/download)

We need to publish this the morning of 1/5/23. 

**Note:** This may be a page that has draft changes that can't be published yet. If so, we need to revert to a previous version before making the changes.

## Tasks
- [x] Update burials page
- [x] Copyedit (Megan)
- [x] Publish (Megan)
- [x] Notify VA partner that changes are live (Randi)

## Acceptance Criteria
- [x] New info is live on the site

**Comment by aliyahblackmore** [comment]
Update: **Waiting to hear back about Note placement. New content was added to the table in Drupal.**

**Comment by RLHecht** [comment]
These changes were published and are now live. Closing ticket.
