### ISSUE TITLE
Add LSGS contact info to VA claim exam page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#51439]
## Issue Description

Tanekwa sent us a request to add contact information for Loyal Source Government Services (LSGS) in 2 places on the [VA claim exam](Loyal Source Government Services) page.

The info to add: For Loyal Source Government Services (LSGS), call 833-832-7077. 

Accordions to add it to:
- What if I need to change the day or time of my scheduled claim exam?
- Will VA pay for my travel to and from a claim exam?

This should be added as the first bullet point so that these stay in alphabetical order.

## Tasks
- [x] Update drupal page
- [x] Copyedit (Megan)
- [x] Publish (Megan)
- [x] Notify Tanekwa that changes are live (Randi)

## Acceptance Criteria
- [x] New info is live on the page

**Comment by aliyahblackmore** [comment]
Hi @megzehn ! This is ready for you.  

I added in the 711 number as well, but I'm wondering if we'd only want to have it added in one instance considering those phone numbers are in close proximity?

**Preview link**: http://preview-prod.vfs.va.gov/preview?nodeId=914

**Comment by megzehn** [comment]
Thanks, @aliyahblackmore! I deleted the second reference of 711 so it's just listed on the first number in each Q&A. 

I confirmed the number and published the page. Ready for you @RLHecht!

**Comment by RLHecht** [comment]
These changes are live. Closing ticket.
