### ISSUE TITLE
Swap out videos in COVID CLP-HOLD TO PUBLISH UNTIL WEEK OF 1/17

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#51432]
We need to swap out the videos in the stories section of the CLP to these 2 Veterans:

Robert Bonner: https://www.youtube.com/watch?v=wMVj5kYn8ps
Ronald Pipkins: https://www.youtube.com/watch?v=jpykh5DMZb8

Drupal Page: Have questions before you get your COVID-19 vaccine? http://preview-prod.vfs.va.gov/preview?nodeId=19578

Documentation for how to swap videos: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/covid-19-biweekly-video-swap-process.md

## Tasks
- [ ] Replace text and videos (Aliyah)
- [ ] Review and publish (Randi)
- [ ] Create new ticket for next update (Randi)

## Acceptance Criteria
- [ ] New videos and text are live on the page

**Comment by aliyahblackmore** [comment]
Hi @RLHecht this is ready for you! 
**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=19578

**Comment by RLHecht** [comment]
published and created backlog ticket. Moving to validate.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
