### ISSUE TITLE
Content work for COMPACT Act

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#51433]
## Issue Description

We made updates to our [suicide prevention](https://www.va.gov/health-care/health-needs-conditions/mental-health/suicide-prevention/) page in connection with the COMPACT Act. We need to get SME approval on the changes and publish in coordination with a press release that is going out on 1/17.

Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=20

## Tasks
- [x] Add content about COMPACT Act (Danielle)
- [x] Send to SMEs (Danielle)
- [x] Copy edit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Page is live with updates

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht This work happened quickly and ended up being updates to our suicide prevention page for the immediate need.

I've made the updates and our communications partner is taking this to SMEs for approval now. Final steps will be incorporating any feedback and copy editing for a projected launch on 1/17/23.

Here's the preview of the page: http://preview-prod.vfs.va.gov/preview?nodeId=20

**Comment by RLHecht** [comment]
@megzehn Danielle needed to publish this so I did a copyedit pass for errors an omissions and published the page. But we want you to do a more thorough copyedit and we can make any other changes needed and republish. Thanks!

**Comment by megzehn** [comment]
Thank you, @RLHecht! I made a few more copy edits and pinged Danielle. I left the changes in drafts for now, but if she's OK with them, then I'll re-publish.

**Comment by RLHecht** [comment]
This work is complete. Closing ticket.
