### ISSUE TITLE
Prep and send VA DIC page for Spanish translation

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#51435]
## Issue Description

As part of our effort to provide multilingual content to Veterans, we need to translate our [About VA DIC for spouses, dependents, and parents](https://www.va.gov/disability/dependency-indemnity-compensation/) page into Spanish.

We'll use the [checklist for content readiness for translation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/editorial-resources/preparing-content-for-translation-checklist.md) to prepare the content for the translators and then send to them in a Word doc.

**Note:** Be sure to include the metadescription when sending content. 

## Tasks
- [x] Prep content for translation (Randi)
- [x] Review (Ana)
- [x] Send to translators (Ana)

## Acceptance Criteria
- [x] VA DIC content has been sent to translators

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA I prepped this page for the translators. [https://app.zenhub.com/files/133843125/3faedc23-2ebf-48a0-916a-27935fca1088/download](https://app.zenhub.com/files/133843125/3faedc23-2ebf-48a0-916a-27935fca1088/download)

**Comment by RLHecht** [comment]
@ABeltran77 We're going to take Danielle out of these and have you review the work I already did and then you can send to the translators. We can chat more about this and I can give you some background. Thanks!

**Comment by ABeltran77** [comment]
Sounds good!

**Comment by ABeltran77** [comment]
Reviewed About VA DIC for spouses, dependents, and parents](https://www.va.gov/disability/dependency-indemnity-compensation/ 
One comment was made for feedback:
[3faedc23-2ebf-48a0-916a-27935fca1088.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11319500/3faedc23-2ebf-48a0-916a-27935fca1088.docx)

**Comment by RLHecht** [comment]
Thanks, @ABeltran77 . Can you accept all changes on the word doc and send to Stephanie from your VA email? You can cc me and Danielle. You can let her know that this is another page for Spanish translation that lies in our disability benefits hub. Afterward, I'll close this ticket and set up a separate one for when the content comes back. Thanks!

**Comment by ABeltran77** [comment]
Changes have been accepted. Sending email now.

[3faedc23-2ebf-48a0-916a-27935fca1088.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11325191/3faedc23-2ebf-48a0-916a-27935fca1088.docx)

**Comment by RLHecht** [comment]
Translation sent. Closing ticket.
