### ISSUE TITLE
[FE] [BUG] Fix text input error so that it translates the error message

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#51440]
## User Story
As a veteran, I want to see the error message on the login page translated when I toggle the language so that I can understand what the problem is.

## Related issue
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1350

## User Workflow
- Given I
    - attempt to log in and receive and error message on an input
- When I
    - toggle the language
- Then I
    - should see that the error message is translated

## Tasks
- [ ] [FE] refactor so that the translated string is passed to the error attribute of the VATextInput component

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [x] Read ticket details and verify that ACs are met
- [x] Review code in PR
- [x] Run branch locally
- [x] Check that new and updated translations use new keys
- [x] Check for hardcoded strings
