### ISSUE TITLE
[FE] Onsite Notifications v2: Technical discovery for adding new notifications

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#51447]
## Background
Once we have finished our scoping of onsite notifications v2 we need to do some initial technical discovery for adding new notifications. We'll need to coordinate with VA Notify and leverage Angela's initial research around notification availability with VA Notify.

Three "levels" to consider:
1. Basic/lightest: "your prescription has shipped, go here to manage it"
2. Mid-tier: need LOE from VA Notify to update our integration to bring in additional variables
3. Top-tier?: need LOE from VA Notify to update our integration to bring in the entire text/email notification 

_For this ticket, your focus should be on the basic/lightest option._

## Tasks
- [x] Review documentation and notification templates  (linked in resources)
- [x] Consult with VA Notify team (specifically developers) and Tom (our BE dev) to understand what we'll need in place to add new notifications
- [x] Draft technical approach/plan for adding new notifications

## Acceptance Criteria
- Technical plan/approach drafted in github (does not need to be final version of documentation)
- Things to consider covering in the document: items that come up in privacy and security reviews, outstanding technical questions

## Resources
- [Project outline: Scaling onsite notifications](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications/notifications-v2#project-outline-scaling-onsite-notifications-onsite-notifications-v2)
- [ MVP documentation: Backend technical notes](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications#backend)
- [MVP documentation: Frontend technical notes](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications#frontend)
- [Shared notes: existing notifications review for onsite notifications](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/notifications-v2/product/shared-notes-existing-notifications-to-review.md#shared-notes-existing-notifications-to-review-for-onsite-notifications)
- [VA Notify email templates](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/notifications-v2/product/VANotify-template-screenshots.md)

**Comment by allisonlu** [comment]
Here's my initial technical discovery documentation: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/notifications-v2/fe-tech-discovery-adding-new-onsite-notification.md

I'll be adding to this file when I find more helpful while spelunking 🔍
