### ISSUE TITLE
[UX] Create additional aria labels for appt list page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#51449]
## Tasks

- [ ] Write aria labels for new appts list page (to hand off to FE engineers)
- [ ] Consult with VAOS team (who is or has implemented the appt list page) and/or Brian or Josh from accessibility team
- [ ] Provide to engineers
