### ISSUE TITLE
Remove content on education benefits for survivors and dependents page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#51443]
## Issue Description

Our EDU partners asked us to remove content on the [VA education benefits for survivors and dependents](https://www.va.gov/education/survivor-dependent-benefits/) because the information isn't correct for both types of benefits (DEA and Fry). 

We need to remove the H2 "What benefits can I get?" and the bullet points underneath. Since we list the specific benefits on each of the child pages, we don't need to also have them here. 

## Tasks
- [ ] Remove content in Drupal (Katherine)
- [ ] Send to VA partners for approval (Laura)
- [ ] Copyedit (Megan)
- [ ] Publish (Megan)

## Acceptance Criteria
- [ ] Page is updated on live site

**Comment by katherine-fung** [comment]
I emailed the stakeholders about removing this section, and am waiting to hear back. 

I reverted to the table version of this page, removed the "What benefits can I get?" section, and saved the page as a draft.

**Comment by katherine-fung** [comment]
Terry Warren ok'ed the change. 

@megzehn - can you copy edit and publish? 

http://preview-prod.vfs.va.gov/preview?nodeId=984 

We removed a section called "What benefits can I get?"

**Comment by megzehn** [comment]
This is copy edited and published. Thanks @katherine-fung!

**Comment by katherine-fung** [comment]
Thanks @megzehn! The change is live, and I've emailed the link to stakeholders. We can close this ticket @RLHecht.

**Comment by RLHecht** [comment]
Thanks all! Closing ticket!
