### ISSUE TITLE
Update accessibility orientation based on 2022 EOY changes

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#51444]
## User Story
_"As a new VFS team member, I want to have accurate information about accessibility processes and resources, so I can build the most accessible product possible."_

Assignee: @briandeconinck 
Peer Reviewer:

## Description
Two major accessibility changes happened near the end of 2022:
- The Governance team launched the accessibility testing artifact to help VFS teams complete foundational testing.
- The Shared Support team disbanded as a result of contract changes. Among other things, this means weekly accessibility office hours will no longer be held as Angela has rolled off.

The accessibility orientation presentation needs to _start_ talking about the new testing artifact, and _stop_ talking about office hours (at least until its future is determined).

## Impacted Artifacts
- [Accessibility orientation slides](https://docs.google.com/presentation/d/1rJLur5iIB0H47JVoTTUKd39U6TbvP12KbxICXgXNu0w/edit)

## Tasks
- [x] Update slides
   - [Current version of slides](https://docs.google.com/presentation/d/1rJLur5iIB0H47JVoTTUKd39U6TbvP12KbxICXgXNu0w/edit)

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The accessibility orientation slides no longer reference accessibility office hours
- [x] The accessibility orientation slides introduce the testing artifact and how to use it

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
There was an extra set of `( )` that snuck into the markdown link syntax when I copy/pasted that link. Not sure what I did there. But yes, it's also the same link as under Impacted Artifacts. Link is now fixed.

**Comment by shiragoodman** [comment]
@briandeconinck I added 1 comment to Slide 27. Other than that, looks good! Once fixed, this can be closed.

**Comment by briandeconinck** [comment]
Comment resolved, closing!
