### ISSUE TITLE
[UX] Create additional aria labels for appt list page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#51450]
## Tasks

- [ ] Write aria labels for new appts list page (to hand off to FE engineers)
- [ ] Consult with Brian or Josh from accessibility team. [Here is the feedback in Slack that Brian has provided](https://dsva.slack.com/archives/C02GXKL8WM6/p1672851477734379). What should the labels be, and how do we make the information clear?
- [ ] Provide to engineers

**Comment by ytsaoca** [comment]
Problem: 
Because the original design has labels 
![Screen Shot 2023-01-18 at 4.04.15 PM.png](https://images.zenhubusercontent.com/6148b41faabf78b679dbacff/f695b3fd-eab5-4ebd-9379-a81d6634aaf8)and the new design removed it.
![Screen Shot 2023-01-18 at 4.19.00 PM.png](https://images.zenhubusercontent.com/6148b41faabf78b679dbacff/cdf37b7a-1bba-4e3d-96bc-402a15d753d1)

@brianseek brought up the question whether we want to add aria labels to make them specific. 

- After talking to Josh, we assume that user won't feel confuse without the aria labels. 
- We would like to add aria labels to detail links just like what VAOS did.

Also, it's better to think through how screen reader read the list, which we want to explore in [this ticket](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/52173).

**Comment by ytsaoca** [comment]
@brianseek 
After UX sync, we decided to add aria labels to detail links: "**[TIME] appointment details**"
Documentation:
[Ccheck-in](https://share.goabstract.com/4ff1e88b-7dd0-4aac-812c-1276630ffa7f?collectionLayerId=e5982697-1fd2-4b3d-8af0-e34b3cb33be5&mode=design&sha=latest)
[Pre-check-in](https://share.goabstract.com/04c09d9c-4153-4a14-b034-2e1ca094ebb0?collectionLayerId=69b4f976-44bd-4ae9-9526-42f29312ce3e&mode=design&sha=latest)

'cc @zach-park

**Comment by ytsaoca** [comment]
@brianseek 
After UX sync, we decided to add aria labels to detail links: "**[TIME] appointment details**"
Documentation:
[Ccheck-in](https://share.goabstract.com/4ff1e88b-7dd0-4aac-812c-1276630ffa7f?collectionLayerId=e5982697-1fd2-4b3d-8af0-e34b3cb33be5&mode=design&sha=latest)
[Pre-check-in](https://share.goabstract.com/04c09d9c-4153-4a14-b034-2e1ca094ebb0?collectionLayerId=69b4f976-44bd-4ae9-9526-42f29312ce3e&mode=design&sha=latest)

'cc @zach-park
