### ISSUE TITLE
[EVSS to Lighthouse] Add settings to devops repo

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#51458]
## Background
In order to configure settings for the different environments (dev, staging, prod) we need to add the different settings to the devops configs

## Context
[Dev config](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/dev-settings.local.yml.j2)
[Staging config](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/staging-settings.local.yml.j2)
[Prod config](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/prod-settings.local.yml.j2)

## Tasks
- [ ] Add settings to appropriate environment configs
- [ ] Request PR
- [ ] PR Approved / Merged

## Acceptance Criteria
- [ ] Settings have been added to the appropriate config files
- [ ] PR has been requested / merged

**Comment by jacobworrell** [comment]
Awaiting BE PR review, platform team.

**Comment by jerekshoe** [comment]
This has taken a bit longer than expected. There are 2 repos that need to be updated as part of this work: the devops repo and the [vsp-infra-application-manifests](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests) repo. The changes for all environments have been merged to the devops repo, but only staging and dev have been updated for the `vfs-infra-application-manifests` repo. Originally I had merged changes for all environments into the `vfs-infra` repo, but there were issues with some of the AWS Parameter Store Parameter values that caused the deployment to break. The next step is to put together a new PR for the Production environment and get it approved
