### ISSUE TITLE
MDT- Veteran Personal info step- Error Message

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5146]
## User Story:
As a veteran, I need notified when I make an error so that I can I can take the appropriate step to correct the error.

## Tasks
- [ ] Meet with Design/Content teams to finalize content for error messages
- [ ] get template from content team - tbd
- [ ] Code message from content team -tbd.

## Acceptance Criteria:
- Message is displayed when errors are made.

## Next Steps 
- TBD

## Dep/Blockers
- content team
