### ISSUE TITLE
Execute and Document changes from Project Intake and Feature Request combining

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#51464]
The working goal for Project Intake appears to be a unified backlog that contains both Projects and Feature Requests that are technical in nature. We will need to look at what adjustments need to be made to documentation and workflows.

As Leadership refines their approach, we will make the necessary adjustments.  This process is still under development.

## Blockers
- Leadership is in the process of refining their intentions
- Once planned approach for Project Intake is in place, SDT can evaluate necessary changes to FRP, as well as recommend any combined workflows.

## Tasks
- [ ] Communicate with leadership to understand current state intentions
- [ ] Document changes in workflow
- [ ] Document changes in Platform Documentation guidance
- [ ] Document changes in Confluence-based Platform team user guidance

## Acceptance Criteria
- [ ] Documentation reflects updated process
