### ISSUE TITLE
MDT- Veteran Personal info step- code

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5147]
## User Story:
As a developer, I need to code the Veteran personal step screen so that I can complete step 2 of the MDT ordering process.

## Tasks
- [ ] code the veteran address
- [ ] confirm design from the Design team. 
- [ ] code page elements. 
 
## Acceptance Criteria:
Veteran correct address is displayed: 
UI is approved by the design team
UI matches the UI elements in the Design library system. 
Get url of components??
UI is approved by the DLC team

## Next Steps
- 2 PR
- FE review
