### ISSUE TITLE
MDT- Veteran Personal info step- Error Handling

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5148]
## User Story:
As a Frontend developer, I need confirm the error handling with the BE support so that I can 
my JavaScript errors are caught during rendering,

## Tasks
- [ ] Connect with BE and review what is needed for error handling.
- [ ]  create error boundaries
- [ ] confirm error boundaries is in accordance with the VA error handling system

## Acceptance Criteria:
- [ ]  no error should be shown when rendering the components. 

## Dep/Blockers
