### ISSUE TITLE
Logged-in IA/nav generative research: Find and update tool inventory

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#51498]
### Background

To support the generative logged-in IA/navigation research, Mikki is going to find the existing tools inventory so we know all of the tools that require a person be signed in to use.

### Tasks

- [ ] Find tool inventory
- [ ] Update if needed
- [ ] Link to [research initiative outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ia-and-navigation/2023-generative-logged-in-research/README.md#research-activities)
