### ISSUE TITLE
Logged-in IA/nav generative research: Define goals and questions for research review 

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#51507]
### Background

We plan on conducting a review of previous research to see what we already know about how people navigate the logged-in experience, and to determine what questions would be helpful to answer in other research (eg. analytics review, user research).

[Research review doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ia-and-navigation/2023-generative-logged-in-research/research-review.md#previous-research-to-review)

### Task

- [x] Draft goals and questions for research review
- [x] Discuss as team
- [x] Finalize goals and questions for research review

### Acceptance criteria

- [x] Samara, Chante, and Mikki agree on the scope of the research review and what we hope to get out of it.
- [x] This work is defined well-enough that someone could get started on it.

**Comment by Samara-Strauss** [comment]
We reviewed research goals earlier today. This work is ticketed for Liz in #51750.
