### ISSUE TITLE
Logged-in IA/nav generative research: Define goals and questions for analytics review

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#51508]
### Background

We plan on conducting an analytics review to see what we already know about how people navigate the logged-in experience, and to determine what questions would be helpful to answer in user research.

[Analytics review doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ia-and-navigation/2023-generative-logged-in-research/analytics-review.md)

### Task

- [x] Draft goals and questions for analytics review
- [x] Discuss as team
- [x] Finalize goals and questions for analytics review

### Acceptance criteria

- [x] Samara, Chante, and Mikki agree on the scope of the analytics review and what we hope to get out of it.
- [x] This work is defined well-enough to submit to the analytics team.

**Comment by Samara-Strauss** [comment]
Completed 1.27.23. Notes [in this doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ia-and-navigation/2023-generative-logged-in-research/analytics-review.md).
