### ISSUE TITLE
MDT- Veteran Personal info step- VSA frontend review

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5150]
## User Story:
As a Frontend, I need send my code to the VSA frontend review so that I can get it ready for staging.

## Tasks
- [ ] send it to VSA frontend review
- [ ]  include Tze of our work. 
- [ ]  Add QA to the epic Veteran Personal info 

## Acceptance Criteria:
Review is completed and code is sent to staging

## Dep/Blockers
see dep ticket

**Comment by mojaray2k** [comment]
@wygonikGCIO This should not be a ticket
