### ISSUE TITLE
Define potential user flows for grandfathering

### ISSUE THREAD

**Issue by tygindraux** [department-of-veterans-affairs/va.gov-team#51500]
### Problem statement
Users need to go through a series of steps in order to migrate their account to Login.gov through a grandfathering approach. This will happen from different entry points.

### Initiative
We will create a shared working document in Mural. The document will help define the different user flows needed for a Veteran to migrate to Login.gov through grandfathering.

### Acceptance criteria
- [x] A set of defined, potential user flows for Veterans to migrate their accounts to Login.gov through grandfathering

### Tasks
- [x] @tygindraux: Create shared [Mural board](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1671554156732/bb8f2948581f649bf8fd8ad9816224d93818992d?sender=u397f6dbbaed1b5b67b956658)
- [x] @tygindraux @sdickson-gt: Initial conversation to align on understanding of grandfathering
- [x] @tygindraux: Sketch initial flows, including user interaction and existing design status
- [x] @tygindraux: Share initial flows with @sdickson-gt for feedback
- [x] @tygindraux: Updates to flows based on feedback
- [x] @tygindraux: Share at mid-sprint review for feedback from PO
- [x] @tygindraux @sdickson-gt: Consider additional or missing user flows eg. fail pathways

**Comment by SrfFshn** [comment]
@tygindraux Who should review the User Flows? Porta?
