### ISSUE TITLE
Draft new content tip (S19)

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#51504]
### Tasks

- [x] Pick a content tip idea from the style guide

- [x] Draft a content tip Slack post, similar to the first one posted on Thurs, Jan 5: https://dsva.slack.com/archives/CL181NRJQ/p1672938003050849

- [x] If needed, get feedback from rest of Content team

- [x] Copy and paste the team-approved announcement of our Tip of the Sprint in to the platform-content slack channel.

- [x] Schedule for 1pm EST on the first Monday of the sprint.

Reminder: Add a line to engage with the post if they find the tip helpful.

Link to DRAFT: https://thesocompany.slack.com/archives/C02LYB7QXS5/p1674144173994369
