### ISSUE TITLE
Draft High-level user flows for grandfathering solution

### ISSUE THREAD

**Issue by elizabethkochBT** [department-of-veterans-affairs/va.gov-team#51506]
### Problem statement
Users with existing LOA2 credentials will be migrated to login.gov IAL1 accounts. When accessing the VA ecosystem they need to maintain current access permissions. 

### Initiative
We're working towards building a high-level flow that can define the organizational boundaries and requirements for different teams and partners as far as what needs to be built (to get grandfathering implemented).

### Acceptance criteria
- [x] A high-level user flow for Veterans to migrate their accounts to Login.gov through grandfathering. (Binding)

### Tasks
- [x] Initial conversation with IAM to align on understanding of grandfathering
- [x] Create diagram
- [x]  Draft binding document
- [x] Add documentation to github
- [x] Review diagrams with Joe & other stakeholders (with experience on consuming IAM binding service)
