### ISSUE TITLE
[FE] My VA Health care: Update personalization code to use drupal source of truth

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#51517]
## Background
The switch from `isCerner` to the drupal source of truth to determine whether a VAMC System uses VistA or Cerner as its EMHR system was partially done in [47956](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47956). We need to complete the work as the personalization code is still referencing the hard coded method which is actively being deprecated.

## Tasks
- [x] Review previous tickets to understand what was done and what is still remaining to switch to the drupal source of truth
- [x] Complete the work in the personalization code
- [x] Test

## Acceptance Criteria
- [x] No code within My VA calls the old method of `isCerner` to determine whether a VAMC System uses VistA or Cerner as its EMHR system

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_  Another dev who can check the code
- _How can this work be validated?_ code does not reference `isCerner` method 

## Resources
- [Slack thread from public websites](https://dsva.slack.com/archives/C52CL1PKQ/p1672939719325459)
- [Drupal documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-opt-in-to-drupal-as-the-source-of-truth-for)
- Previous drupal tickets: #47956, #50043, #50173

**Comment by jilladams** [comment]
(Sub for updates.)

**Comment by adamwhitlock1** [comment]
@ajakabcin I have completed this work and it is deployed on staging.

I checked a couple cerner users and verified that I do see the facility names listed in the healthcare content CTA as they were before, so I do believe that everything is working as expected.

**Comment by ajakabcin** [comment]
Awesome thank you @adamwhitlock1

**Comment by ajakabcin** [comment]
Confirmed with public websites team and Adam that this is looking good - if anything else comes up we'll open a new ticket
