### ISSUE TITLE
Logged-in IA/nav generative research: Define goals and questions for Medallia and call center data review

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#51514]
### Background

We plan on conducting a review of Medallia feedback and call center data to determine what issues people have with navigating the logged-in experience, and to determine what questions would be helpful to answer in user research.

### Task

- [x] Draft goals and questions for Medallia/call center review
- [x] Discuss as team
- [x] Finalize goals and questions for Medallia/call center review

### Acceptance criteria

- [x] Samara, Chante, and Mikki agree on the scope of the Medallia/call center review and what we hope to get out of it.
- [ ] This work is defined well-enough for Chante's team to get started.

**Comment by Samara-Strauss** [comment]
Done! [Here is the outline for the Medallia/Call Center review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ia-and-navigation/2023-generative-logged-in-research/medallia-call-center-review.md).
