### ISSUE TITLE
INTL - Sitewide Homepage Dashboard - Medallia cards

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#51529]
## Issue Description
Create new cards for the Medallia data to be added to their [Domo dashboard](https://va-gov.domo.com/page/80919003).   See [project notes](
https://vfs.atlassian.net/wiki/spaces/AT/pages/2428338517/Chloe+Project+Background+Notes) step 3 for further details.

This ticket is the next step after [data modeling](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50475) ticket.
---
## Tasks
- [x] Create cards
- [x] QA cards

## Acceptance Criteria
- [x] Cards have been added to their dashboard.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelle-dooley** [comment]
2 of 3 cards created.  https://va-gov.domo.com/datasources/e7264e76-4d8d-4419-8167-f1fc3059e278/details/cards
