### ISSUE TITLE
INTL - Sitewide Home Dashboard - Medallia cards

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#51528]
## Issue Description
Create new cards for the Medallia data to be added to their [Domo dashboard](https://va-gov.domo.com/page/80919003).   See [project notes](
https://vfs.atlassian.net/wiki/spaces/AT/pages/2428338517/Chloe+Project+Background+Notes) step 3 for further details.

This ticket is the next step after [data modeling](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50475)
---
## Tasks
- [ ]Create cards
- [ ] QA cards

## Acceptance Criteria
- [ ] Cards have been added to their dashboard.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
