### ISSUE TITLE
INTL - Sitewide Homepage Dashboard - Time to first interaction card

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#51531]
## Issue Description
Create new Domo card on their [dashboard](https://va-gov.domo.com/page/80919003) for 'time to first interaction'.  See [project notes]( https://vfs.atlassian.net/wiki/spaces/AT/pages/2428338517/Chloe+Project+Background+Notes)   step 2 for further details.  Pending sign off from @dorseypa1  on data validation.
---
## Tasks
- [x] Create new card
- [x] QA new card

## Acceptance Criteria
- [x] card is created and added to dashboard.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelle-dooley** [comment]
Created the card.  Need to do some format edits. https://va-gov.domo.com/kpis/details/1043309691
