### ISSUE TITLE
Add Team of Teams as checklist item for New VFS Team template

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#51556]
## User Story
As a Platform team member, I want to make sure new VFS teams are made aware of Team of Teams (ToT) and invited to the weekly event so Platform and other VFS teams can be familiar with what they're working on.

As a new VFS team, I want to be include in the weekly ToT meeting so that I can be familiar with what's happening across VA.gov.

Assignee: @CherylEvans 
Peer Reviewer: @briandeconinck 

## Description
VFS teams who are new to VA.gov are asked to participate in the weekly Team of Teams (ToT) meeting hosted every Tuesday. Unfortunately, teams that are contracted outside of OCTO aren't always made aware of the ToT meeting and aren't even aware of the meeting and/or asked to attend.

If we add the Team of Teams information to the New VFS Team template, then new VFS teams will be made aware of the ToT meeting and will be more likely to attend and participate. 

## Impacted Artifacts
[New VFS Team gh template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=analytics-insights%2C+governance-team&template=new-vfs-team.md&title=New+VFS+Team+%5BInsert+team+name+here%5D)

## Tasks
- [x] Reach out to Julia Badillo and/or Erica Robins on Slack, preferably the #team-of-teams-slide-collection channel
- [x] Share with them our objective, and ask what their preferences are for new teams being added to the Team of Teams meeting
- [x] Create PR of the template with proposed changes

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] New VFS teams are made aware of ToT via the New VFS Team gh template

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
Reached out to Julia and Erica on Wednesday 2/1: Good afternoon! :slightly_smiling_face:  I am the Content specialist from the Governance team. We would love your assistance with a ticket we are working on.
We want to ensure new VFS teams are aware of Team of Teams (ToT) and invited to the weekly event so Platform and other VFS teams can be familiar with what they're working on. We are adding ToTs as a checklist item for the "New VFS Team" template. As a new VFS team, I want to be included in the weekly ToT meeting so I can be familiar with what's happening across VA.gov.
What are your preferences for adding new teams to the Team of Teams meeting? Once you provide this information, I will add it to the New VFS Team template. We would certainly appreciate your recommendations and guidance in this endeavor.
I received no response so Shira reached out 2/3 for f/u: lagging this again. Please let me and my team know if you're able to help. Right now I just direct folks to ToT through 1:1's I have, but we'd really like to formalize the process to ensure no one get's skipped. let us know if you have any questions or concerns

**Comment by CherylEvans** [comment]
Met with Erica, Julia, Shira, and Brian to discuss the needed changes to the New VFS Team ticket.  Submitted a pull request with the proposed changes.  Waiting for input.

**Comment by CherylEvans** [comment]
Erica approved my proposed changes to the ticket:
## ToT (Team of Teams)
 - [ ] Join the #team-of-teams-slide-collection channel
- [ ] Contact @Julia Badillo and/or @Erica Robbins [GovCIO_VetsPS] to receive Team of Teams Agenda and Protocol for reference
- [ ] Introduce yourself with your name, team, and crew
- [ ] #vfs-all-teams channel provides a Slack-Bot reminder 5 minutes prior to all Team of Teams meetings and includes a Zoom link
 - [ ] Use the #vfs-all-teams channel Zoom link provided to create your own calendar invite to attend all Team of Teams meetings

**Comment by CherylEvans** [comment]
Changes squashed and merged in gh.

**Comment by shiragoodman** [comment]
this looks great - thank you @CherylEvans !
