### ISSUE TITLE
Set up autoforwarding of Zoom recording emails

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#51564]
## User Story
As the Governance team PM, I want my team to be able to view and share Collaboration Cycle meeting recordings so that I'm not a blocker if I'm unable to get to it right away.

Assignee: @shiragoodman
Peer Reviewer: @briandeconinck 

## Description
We set up the [Zoom information for Collab Cycle meetings](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2454585540/Zoom+information+for+Collab+Cycle+meetings) so that all Collaboration Cycle weekly meetings use the same Zoom information. This happens to be the Zoom account for PM Shira Goodman, meaning all Zoom recording's are emailed to her email address. Currently, she is the only person on Governance team capable of posting the Collaboration Cycle touchpoint recording to the VFS teams Collaboration Cycle Request ticket. By setting up auto forwarding, the Governance team member on-support is able to add the recording to Collab Cycle Request ticket, no longer making Shira a blocker.

## Impacted Artifacts
[Design Intent - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Moderator+Responsibilities)
[Midpoint Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Moderator+Responsibilities)
[Staging Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review+-+Moderator+Responsibilities)

## Tasks

- [x] Set up Google group for Governance team members
   - asked Oddball IT for assistance
   - new group: va.gov-governance@oddball.io
- [x] Follow [How to Automatically Forward Specific Emails in Gmail ](https://www.howtogeek.com/735233/how-to-automatically-forward-specific-emails-in-gmail/)guidance
- [x] Create filter for Zoom recordings
   - from: no-reply@zoom.us
   - contains: "Cloud Recording - Collaboration Cycle Meeting"
- [x] auto forward filter to new google group
Filters set up for auto forward:
![image.png](https://images.zenhubusercontent.com/5f62315e822e9b2aa88b1f1c/742eb391-9433-4147-8292-ccb93bfd7854)
- [x] confirm auto-forward works correctly after ~~Design Intent on 1/9, Staging Review on 1/12,~~ Staging Review on 1/26
- [x] update all 3 moderator responsibilities docs in the post-meeting section. 
    - Previous guidance was that Shira would post the recording. New guidance should state that Zoom email will be auto forwarded to Governance team email and the recording and passcode can be captured from the email 

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Governance team members on-support are able to share the Zoom meeting recording of the completed Collaboration Cycle touchpoint to the VFS teams Collaboration Cycle Request ticket 

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Auto-forwarding has been set up, however I ran into an issue with the Zoom meeting names changing once the event is scheduled. Looking into now. May have to change the filter for auto forwarding

**Comment by shiragoodman** [comment]
@briandeconinck I do think I fixed the filter in my gmail. Can you please verify if you receive the Zoom recording email after the Staging Review on 1/26?

**Comment by briandeconinck** [comment]
I posted in Slack but I'll verify here as well that I received the 1/26 recording email!

**Comment by shiragoodman** [comment]
thanks @briandeconinck ! Could I ask you to complete this ticket? All that's left is updating the Moderator Responsibilities docs for DI, MPR and SR to change it from "Shira will add the recording" to "you should receive a forwarded email from Shira with the Zoom info." Please let me know if you have any questions or if you're unable to complete this work. Thanks!

**Comment by briandeconinck** [comment]
Moderator responsibilities updated:
- [Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Moderator+Responsibilities#Step-2.2)
- [Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Moderator+Responsibilities#Step-2.3)
- [Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review+-+Moderator+Responsibilities#Step-2.5)

@shiragoodman If this looks good to you then I think we can close this ticket!
