### ISSUE TITLE
MDT- Address step- error handling

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5157]
## User Story:
As a Frontend developer, I need confirm the error handling with the BE support so that I can 
my JavaScript errors are caught during rendering,

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [x] Connect with BE and review what is needed for error handling.
- [ ]  create error boundaries
- [ ] confirm error boundaries is in accordance with the VA error handling system

## Acceptance Criteria:
- [ ]  no error should be shown when rendering the components. 

## Dep/Blockers
