### ISSUE TITLE
CST: remove estimated decision date language

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#51579]
## Value Statement
**_As a_** veteran
**_I want to_** not be presented with incorrect information that builds false expectations regarding decision wait times
**_So that_** I am not disappointed when those expectations are not met 

---
## Background Context
There is clear administrative value to not displaying estimated decision dates to veterans. Those dates are often interpreted as promises and too often those expectations are not met. Currently, there is information that blames the inability to provide accurate estimation dates on matters related to COVID. Those explanations are no longer legitimate, nor do they encapsulate the many reasons a decision might be delayed that have nothing to do with COVID. 

We are going to remove the estimated decision date field and associated alert text and not build an expectation that we'll be able to better estimate claims decision dates in the future. 

## Acceptance Criteria
- [ ] Estimated decision date field is removed from CST
- [ ] Alert message explaining why COVID has affected decision timelines is removed

## Designs and Build Notes
Here's a screenshot of the content to be removed: 

<img width="800" alt="Screen Shot 2023-01-06 at 11 40 35 AM (1)" src="https://user-images.githubusercontent.com/10838260/211085085-ca769d65-9c7d-4bee-9d4e-44c76410b998.png">

## Open questions
- Add here

## Tasks
- [ ] Squad 1 removes content.
- [ ] Jacob notifies Kelly Lein

## Definition of Ready 

- [x] Clear value description
- [x] Testable acceptance criteria
- [x] Accessibility added to acceptance criteria
- [x] Approved designs attached
- [x] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jacobworrell** [comment]
Should be good to merge.
