### ISSUE TITLE
Incorrect Data presented on portal

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#51578]
## Issue Description
Veterans are reporting that they are seeing incorrect data presented on the portal and support calls are getting a handful of inquiries of the Debt Portal not providing correct balances within the last couple months for different debt types

## Examples
- "Veteran stated he received his 100 letter in the mail, but when he went to his VA account on the debt portal, it states he doesn’t have a debt. "

- “ I have a VA debt balance, but when I log into the VA website, it says there is no debt on file. I would like to be able to view my total balance before paying. Last response stated that due to system changed there would be times that veterans wouldn’t be able to see debt in debt management. This is not due to system changes. Whenever I login (everyday), the system still says they I have no debt, but I do and want to see the balance without having to make a phone call or submit an inquiry.”

- "Veteran sent an email stating his balance has not updated on the portal with the last two months’ payments of $300.00 each paid via Compensation benefits on 11/21/22 and 12/21/22. He states the debt portal balance reflects $3,661.81 when VAMS shows $3,061.81.  He was concerned we were not applying the payments.

## Considerations from VA representative reporting issue

- Is it possible any updates on account balances have not been updating? Was it 2 months ago when the letters were stopped?- I’m thinking there is a correlation with the letters being turned off and balances not updating.
---

## Tasks
- [ ] Look into the affected data points of the VA.gov portal
- [ ] Determine possible cause from API or UI
- [ ] Reach out to DMC about data discrepancies 

## Acceptance Criteria
- [ ] We gain an understanding of why these values are not accurately represented
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
1/10/23 - @ScottyRJames sent an email to the DMC team. Awaiting Pavan's response. It is anticipated this will roll over to Sprint 91 as more time will be needed to investigate and determine why Veterans are seeing incorrect data.

**Comment by denisecoveyduc** [comment]
1/12 - Jeff Chant (Project Manager for DMC team) has requested that we create a Service Now incident, including file numbers etc. to identify the Veterans known to be affected. Once we have a SNow ticket, he will then assign a developer to analyze the veteran’s records to determine what the problem is.

Jill can request those file numbers and will share with @ScottyRJames once available.   (Denise reminded her again on 1/17 that they are needed to move forward)

**Comment by HeatherRienks** [comment]
@ScottyRJames - Are we still waiting for Jill to provide file numbers to us? 

cc: @denisecoveyduc

**Comment by ScottyRJames** [comment]
Most recent update is that Jill is still waiting on a few file numbers and contact info but would like to reach out to the Veteran first before opening a Service Now ticket to assure they are still having problems.

**Comment by denisecoveyduc** [comment]
1/24.- Denise to reach out to Jill to determine if file numbers are available and if she has opened a SNow ticket for this issue.

**Comment by HeatherRienks** [comment]
@denisecoveyduc  and @ScottyRJames - do we have any info on this one?

**Comment by denisecoveyduc** [comment]
I actually just reached out to Jill on Friday about this one to see if she has heard of recent issues. At the moment I think the problem has resolved itself but I'd like to confirm.

**Comment by HeatherRienks** [comment]
Great news!

**Comment by denisecoveyduc** [comment]
Feb 21 update on this one.. I chatted with Jill about this. She is reaching out the an impacted Veteran for more information. Our hope is that we can close this one out after we validate the issues have been resolved or have clarity on what's they are still seeing.

**Comment by denisecoveyduc** [comment]
I am closing this one out until we hear about future issues.. currently incorrect data issues have been resolved
