### ISSUE TITLE
MDT- Address Step- VSA frontend review

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5159]
## User Story:
As a Frontend, I need send my code to the VSA frontend review so that I can get it ready for staging.

## Tasks
- [ ] Send it to VSA frontend review
- [ ] Include Tze of our work. 
- [ ] Add QA to the epic Veteran Personal info 

## Acceptance Criteria:
Review is completed and code is sent to staging
