### ISSUE TITLE
Establish Relationship with ID.me POC

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#51607]
## Issue Description
_The call center team receives cases from AVA and the VEO call center regarding users being unable to log into their VA.gov account.  In many instances, the issue may lie with the CSP or credentialing service provider.  In order to provide the best service to VA.gov users, a relationship must be established with CSPs._

_ID.me is a provider that allows or prohibits individuals into their VA.gov accounts.  Building a bridge to work in partnership to offer faster service for login issues is vital._

---
## Tasks
- [ ] _Create a process for getting callers to ID.me for better/faster results._
- [ ] _Obtain details on how to determine ID.me issues._
- [ ] _Gather details to modify/create new templates regarding ID.me_
- [ ] _Establish meeting cadence for knowledge sharing._
- [ ] _Share any relevant information with VEO tier 1 agents._

## Acceptance Criteria
- [ ] _A decrease in cases concerning ID.me login issues_
- [ ] _An opportunity to use this experience as a blueprint to begin establishing intentional relationships with other CSPs and call centers_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
In being proactive, last month I reached out to ID.me concerning a particular issue and also advised that I would like to set up a meeting in the new year to start developing a relationship and set up meetings.

Jess McClure and Kyle Fairbanks are the current POCs that I have bene connecting with and are open to this.

**Comment by ATMiddleton** [comment]
The ID.me team is OOO.  @Kimberley2019 Will continue in current Sprint.

**Comment by ATMiddleton** [comment]
Jess McClure and Kyle Fairbanks are currently attending off site meetings.  Discussions will continue next sprint.

**Comment by Kimberley2019** [comment]
As of 3/1/23 monthly meeting has been established with VA.gov contact center group and ID.me.
Meeting will be held 3rd Wednesday of each month from 10:00-10:30AM ET.

Required: Jess McClure, Grace Johnson, Kimberley Monroe-Daniels
Optional:  Anita Middleton, Chante Lantos-Swett, Kyle Fairbanks, Steven Tarlow
Meeting Agenda: We will utilize this time to discuss top issues, outstanding matters, etc.

**Comment by Kimberley2019** [comment]
[https://app.zenhub.com/files/133843125/563d4f4f-8566-463f-89c9-8191db4f7542/download](https://app.zenhub.com/files/133843125/563d4f4f-8566-463f-89c9-8191db4f7542/download)
