### ISSUE TITLE
Respond to ESECC Requests / Feedback

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#51606]
# Description
We need to address the feedback / requests from ESECC in order to process our `preview.va.gov` and `dev-preview.va.gov` related request.

Feedback from ESECC is here:

> Tech review comments - Needs ESECC discretion
This should technically be a new RFC, not an in scope change request.
Not sure why the platform-api.va.gov domain web flows were allowed to be in scoped for this RFC as no obvious relationship with "design" domain. Request is for new inbound web flows for preview.va.gov and dev-preview.va.gov. Technically implementable but the new domains do not show a relationship with the original web flow request for design.va.gov domain. No port requirements for these 2 new web flows listed and we should not assume they want port 80 and 443 where port 80 redirects to https 443 as with the previous flows...this must be specified on the request, whether ESECC allows this to be submitted on this RFC or if a new RFC is to be submitted. Suggest attending one of the weekly ESECC meetings that occur on Wednesday and Thursday at 10:00 AM EST to discuss.

## Context for the request
Given the outcome of the [PE EKS POC](https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/department-of-veterans-affairs/va.gov-team/49343) and the [conversation with infrastructure SMEs](https://vfs.atlassian.net/wiki/spaces/TT4/pages/2436628750/Kyle+Conversation+11+17+regarding+EKS+Deployment+Process), it is prudent for our team to get access/approval to a sub-domain for use in `dev`. This subdomain will make preview environments directly routable from the public internet without requiring us to piggyback on the use of an existing subdomain by defining paths and using the revproxy.

# Tasks
- [x] Review feedback
- [x] Collect information necessary to submit a new request
- [x] Work with Ray W. to resubmit request (Or other OCTO personnel in Ray's absence)

# Acceptance Criteria
- [ ] A request is resubmitted for the subdomain

**Comment by JoeTice** [comment]
This is associated to the original request - https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/49878

**Comment by pjhill** [comment]
Chasing down creating a new request I see a [Network ESECC: Submit a Webserver Internet Connection Request Checklist](https://www.amazon.com/dp/B097P8562D?psc=1&ref=ppx_yo2ov_dt_b_product_details).

**Comment by pjhill** [comment]
Checklist items --

- [ ] Create va.gov fully qualified domain names (FQDN) and register them in Web Registry
- [ ] WASA scan
- [ ] Validate and document the data being transmitted
- [ ]

**Comment by pjhill** [comment]
New request submitted -- RFC 9630 -- https://esecc.va.gov/cgweb/MainUI/MainFrame.aspx?ID=12622&moduleName=Change

I've added a comment to RFC965 indicating we have created a new request, and that we should be able to close RFC965 again without appending the scope.
