### ISSUE TITLE
[EVSS to Lighthouse] modify FE code for detail view to use feature toggle

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#51603]
## Background
We will need to update the FE code for the detail view of CST to use different components based on the value of the feature toggle. This will require creating copies of a few different containers/components and updating them to reflect the new attribute mapping

## Tasks
- [ ] Remove representative details from details page
- [ ] Create copies of necessary components and update them
- [ ] Selectively show the correct versions of the components based on the feature toggle value
- [ ] Use the feature toggle value to determine which API is called (Lighthouse or EVSS)

## Acceptance Criteria
- [ ] Representative details are no longer seen in UI
- [ ] Copies of components are created
- [ ] Correct version of components are shown based on feature toggle value
- [ ] Correct API is being called based on feature toggle value
