### ISSUE TITLE
MDT- Veteran Personal info step- Personal detail confirmation page - default state, v1

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5161]
## User Story:
As a veteran, I need to be able to see that my personal information as the first step so that I can confirm my information is correct.

## Tasks
- Create a high fidelity mockup of the personal detail confirmation page
- Upload mockup to Invision and indicate initial focus point as a comment

## Acceptance Criteria:
- [x] The Veteran’s personal details are displayed
- [x] Mockup aligns with VA.gov’s design system
- [x] There is information on who to contact to fix any incorrect info 
- [x] The screen’s initial focus is incorporated
- [x] Sketch artboards are uploaded to Invision and linked in this ticket as a comment

## Next Steps
- design review
- content review.

## Dep/Blockers
- Unsure if there are any conditional states, this may need to be a technical research ticket if no one else on the team knows the answer
- API is not set up so we aren’t 100% sure what data is being passed through

**Comment by rileyorr** [comment]
First pass of this design can be found [here](https://vsateams.invisionapp.com/share/2FVSYCEPT7E). 
I put some comments with questions about different sections. We will need to find out this information and update the mockup (likely as a v2 ticket?).

**Comment by rileyorr** [comment]
@mojaray2k Here is the first page of the _Veteran information_ chapter. Let me know if you have any questions!
