### ISSUE TITLE
Configure PE Deployment File to Loop All values.yaml Files in a Directory

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#51637]
# Description

In order to independently maintain a preview environment for a given branch, we need to create an app of apps. Each app within the app of apps can be created and destroyed independently. Each app will be generated from an independent `values` file. ArgoCD will be provided a list of values files to deploy.

# Acceptance Criteria
- [ ] Each branch generates a unique `values` file via GHA workflows, upload the file to the manifests repo, and provide an updated list of `values` files to a single file that contains the list of `values` files

# OLD
```
# Description
In order to independently define and update preview environments for a given branch, we need the Preview Environment `deployment.yaml` file to loop through a dynamic list of files retrieved from a folder in the `infra-application-manifests` repo. Preview environments that are currently deployed should not be interrupted when a new preview environment definition is published.

# Tasks
- [x] Explore the use of flow control for looping the `deployment.yaml` file
- [x] Experiment with the GHA described [here](https://github.com/marketplace/actions/helm-deploy)
  - [x] Is Devops COP OK with use using GHA to deploy resources to EKS?
  - [ ] Do we need to find a plugin for ArgoCD that monitors multiple values.yaml files for us?

# Acceptance Criteria
- [x] The `deployment.yaml` is configured to read in specifications from multiple preview environments and deploy only the preview environments that have changed or are new
```

**Comment by cyriltech** [comment]
#!/bin/bash

for file in <helmchart>/values*.yaml; do
  helm install --generate-name --values $file <helmchart>
done

**Comment by cyriltech** [comment]
The above script will loop through values.yml file, I just need the correct GHA workflow to execute the script.

**Comment by cyriltech** [comment]
I tried to loop values with this [GHA](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/actions/runs/4003230260/jobs/6871142362). Devops COP is not OK with using GHA to deploy resources to EKS, Platform method is to use Argo. Looking into how to achieve this.

**Comment by cyriltech** [comment]
project: preview-environment-dev
source:
  repoURL: >-
    GITHUB URL
  path: apps/preview-environment/dev
  targetRevision: HEAD
 helm:
    releaseName: preview-environment
    version: v3
    valueFiles:
    - {{ range .Files }}
      - apps/preview-environment/dev/environment-values/{{ . }}
      {{ end }}
destination:
  eks cluster'
  namespace: preview-environment
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - Validate=true
    - CreateNamespace=true
  retry:
    limit: 5
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 3m

**Comment by cyriltech** [comment]
Looping values file with concept of argocd apps of app [poc](https://vfs.atlassian.net/wiki/spaces/TT4/pages/2520846546/Configure+PE+Deployment+File+to+Loop+All+values.yaml+Files+in+a+Directory)

**Comment by cyriltech** [comment]
I have raised a [PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1478) merge is necessary for testing.

**Comment by cyriltech** [comment]
![image.png](https://images.zenhubusercontent.com/6385292bddbc0cbb14b84a51/6f44a84c-38e1-47d0-bd79-748957548227)
Implemented POC but there were some issues with syncing deployment. Reached out to kyle and he advised that I changed deployment ns to match that of Preview-environment. He also mentioned that "just for the record, anything that's vets api is going to need to use the vets api IAM, which requires that the ns be vets-api*
not sure if you all have thought that far out -- you cannot deploy a vets api pod and have it work as expected without IAM, and there are requirements for that to happen, you could instead setup your project and deployments to use vets-api-pe for the ns (or something along those lines)" For the completion of MVP we need to make sure we are deploying within vets-api ns. I have make some changes and created a [PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1487). Waiting for merge to monitor changes.

**Comment by JoeTice** [comment]
Sprint 20 Status Update: In Progress, troubleshooting solution has extended this task into next sprint, work will continue in Sprint 21.

**Comment by cyriltech** [comment]
@pjhill I will touch base with Kyle with your Questions

**Comment by cyriltech** [comment]
Yesterday, Feb 15, I worked with Kyle to further troubleshot. Per his recommendation we changed the destination cluster to "https://kubernetes.default.svc" Also planning to change project to OPS since that is where every other application is deployed. Still facing Sync issues. Further Troubleshooting is required.

**Comment by cyriltech** [comment]
![image.png](https://images.zenhubusercontent.com/6385292bddbc0cbb14b84a51/64f2c2e4-2d90-4b9b-8771-68b0be6c77cc)
I was able to implement POC by isolating preview-environment and creating PE app of apps. At the moment Preview-environments are deployed for each values-file, currently using two. Will sync up with Curt about what he needs to parse on his scripts to push multiple values.

**Comment by pjhill** [comment]
@cyriltech -- is the idea here that the POC can be promoted to our live App of Apps solution for PEs once the configuration is settled?

Also, I think this task has evolved quite a bit since we first detailed it. I think the current goalposts are to have the POC detect all values files in the monitored folder and deploy them as distinct "application" objects in the "app-of-preview-environments" app.  Are we at that point currently? Or, are there more bits of work to accomplish before we can call that done?

**Comment by cyriltech** [comment]
@pjhill yes, we are at the point where POC detect all values files in the monitored folder and deploy them as distinct "application" There are some shared resources conflict which I am working on, after which we can consider it done.

**Comment by cyriltech** [comment]
All my corrections are done for this task. We can loop multiple values for each preview environment.

**Comment by pjhill** [comment]
Awesome -- would you be able to demo the behaviors in ArgoCD at some point today in order to verify that we have all everything squared away?

**Comment by pjhill** [comment]
Alright, thanks for sticking to this multiple values file concept. It seems like the app of apps is the way to go. I must admit that I'm having trouble navigating the ArgoCD setup for this. I'm trying to get terminal access to the `vets-api` container and it's not going well, but I see the two PEs listed.  Progress!
