### ISSUE TITLE
[PM, FE] 10-10EZ - Household Optimization: Complete End-to-End & Regression testing

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#51645]
## Background
As development has been completed and QA is in progress, we need to perform Regression QA.
- Access [TestRail Regression test plan](https://dsvavsp.testrail.io/index.php?/plans/view/4298) for each scenario

## Tasks
- [x] Perform Regression QA, per [TestRail test plan](https://dsvavsp.testrail.io/index.php?/plans/view/4298)
- [x] Document all results in Test Rail
- [ ] Ensure plan and results are complete to generate report in #51641
- [ ] Create End-to-End and Unit Test artifacts as required in the QA standards ([guidance on Platform page](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-e2e-test-participationE2ETestParticipation))

## Acceptance Criteria
- End-to-End and Regression QA has been completed and ready for Staging review

**Comment by hdjustice** [comment]
@longmd - Hi Matt, I added a task for a couple artifacts we need, and I may need your help on creating them
- Create End-to-End and Unit Test artifacts as required in the QA standards ([guidance on Platform page](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-e2e-test-participationE2ETestParticipation))

**Comment by longmd** [comment]
I guess I'll have to ask around for the "artifact" part of this. We have these tests already in-place and running. I have zero clue what we would need to provide as evidence of that. There is no "report" that gets generated to prove it exists. I'll ask around and circle back.

**Comment by longmd** [comment]
Here is what I have for the artifacts: 

**Cypress (e2e) Test Coverage for Household V2 section**
![HCA Household V2 Cypress Test Report](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/6cfb51ac-28f8-4455-a3f1-8e05929cfb72)

**Cypress (e2e) Test Coverage for Regression Test (Household v2 disabled)**
![HCA Regression Cypress Test Report](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/2760bf17-e978-4765-8604-63edcb63ff77)

**Comment by hdjustice** [comment]
This is awesome!  thank you so much!
