### ISSUE TITLE
[PM] 10-10EZ - Household Optimization: End-to-End testing with ES

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#51642]
## Background
Internal QA has been completed.  We need to have End-to-End testing completed to ensure that the Enrollment system can still receive the data with no issues.
**Note: End-to-End testing will be completed on Friday June 30.**

### Details on testing
- We will use the same [use cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Household%20section%20redesign/Staging%20Review_QA/Household%20Section%20Optimization%20Use%20Cases.md), except we only need to run 3 of them
     - [Use case B ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Household%20section%20redesign/Staging%20Review_QA/Household%20Section%20Optimization%20Use%20Cases.md#use-case-b)
     - [Use Case F ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Household%20section%20redesign/Staging%20Review_QA/Household%20Section%20Optimization%20Use%20Cases.md#use-case-f)
     - [Use Case H](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Household%20section%20redesign/Staging%20Review_QA/Household%20Section%20Optimization%20Use%20Cases.md#use-case-h)
- As far as data:
     - You can test Authenticated ([Users 3, 11 or 150](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)) or Unauthenticated
          - If testing Unauthenticated, please use a unique name (Ex: first name=Household, last name=UsecaseB) that can be searched in Enrollment System when confirming transmission
     - We need to select "Washington" as the Facility State, and the "Spokane" facility
          - The application will not flow to the Enrollment system if we do not select the right facility
- Expected Results:
     - We are able to submit the application successfully
     - We confirm with Joshua Faulkner that the Enrollment System has received the application successfully
          - We will provide him with the Name used in the Application
          - Let Heather know once you begin, then when you have submitted.  Heather will contact Joshua F to confirm transmission.

## Tasks
- [ ] Reach out to Joshua Faulkner on testing needs
     - Confirmed with Joshua F that they do not need to perform testing since there is no new functionality
- [ ] Perform E-2-E test runs (2-3 Happy Path use cases [no dep, spouse, mult dep)
- [ ] Confirm successful transmission of data from test runs has been completed

## Acceptance Criteria
- End-to-end testing is completed successfully

**Comment by hdjustice** [comment]
Ran several tests and confirmed with Joshua Faulkner that the test runs were processed in ES successfully.
See the [confirmation ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Household%20section%20redesign/Staging%20Review_QA/E-2-E%20testing%20confirmation.md)(via Slack) for reference.
