### ISSUE TITLE
[PM] 10-10EZ - Household Optimization: Complete QA on the new changes

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#51641]
## Background
Ad development wraps up, we need to begin QA on the changes to the Household section of the 10-10EZ

### Resources
- FE Ticket #52960
- [Use cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Household%20section%20redesign/Staging%20Review_QA/Household%20Section%20Optimization%20Use%20Cases.md)
- [Staging Review preparation guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)
- [QA Standards guidance](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards)
- [TestRail Test Runs](https://dsvavsp.testrail.io/index.php?/runs/view/4540&group_by=cases:section_id&group_order=asc)

## Tasks
- [ ] Coordinate QA schedule
- [ ] Use TestRail to perform QA, using test cases/test runs to track and document results
- [ ] Communicate any defects found to the team for resolutions
     - May need create tickets for these
- [ ] Generate the following artifacts (after defect resolutions and retesting):
     - [Regression test plans](https://dsvavsp.testrail.io/index.php?/runs/view/4303&group_by=cases:section_id&group_order=asc) - Ticket #51645
     - [Accessibility test plan](https://dsvavsp.testrail.io/index.php?/runs/view/4420&group_by=cases:section_id&group_order=asc) - Ticket #51644
     - [Household section optimization Test plan](https://dsvavsp.testrail.io/index.php?/runs/view/4540&group_by=cases:section_id&group_order=asc&group_id=9384)
     - Coverage for References
     - Summary(Defects) reports
     - E2E tests (provide a link to the product’s code)
          - These are the engineer's End-to-end testing, but we also have a [ticket with Stakeholders for further End-to-end testing](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/51642))
     - Code coverage (provide a link to the product’s code)

## Acceptance Criteria
- QA is fully completed before Staging review

**Comment by hdjustice** [comment]
Test Case A: Noticed that the lead sentences in the confirmation box is not in BOLD font, as it is in the design.

Staging:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/c1160260-6fc1-4111-8e3c-01b64795d769)

Design File:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/9b05d370-3871-4bac-8345-8b046c527d65)

**Comment by hdjustice** [comment]
Test Case B: the Financial Disclosure prep page lists "2022" - Is the expectation that this needs to be updated every year?

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/a1c2d9fc-6180-49e0-9dbe-e1acf92f28b8)

**Comment by hdjustice** [comment]
Use Case C: The Spousal financial support question is prompting, even though I answered YES that the spouse lived with the Veteran last year and has the same address

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/0e1169de-7282-461e-9bef-b350f25ed4a0)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/dcd48f7c-6d73-4fe1-b2eb-9fa47124aa82)

**Comment by jessicastump** [comment]
I put some content edits found so far during a first review of staging and new content edits that we have still been getting to this ticket: [[FE] 10-10EZ Content changes household section - Post QA #57959](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57959)
Let me know if I should put edits here and keep that ticket only for new things the content team gives us.

**Comment by hdjustice** [comment]
@jessicastump - No, let's keep those content edits in that ticket.  This one can be for functionality defects.  I could actually move my "bold" comments to that ticket

**Comment by mkerns1** [comment]
<table>
        <tr>
          <th>#</th>
          <th>Test Case ID</th>
          <th>Test Description</th>
          <th>Pass/Fail</th>
          <th>Bug ID (if any)</th>
          <th>Comments</th>
        </tr>
        <tr>
          <td>A</td>
          <td>TC-A</td>
          <td>Applicant does not want to disclose their financial information</td>
          <td>Pass</td>
          <td></td>
          <td>On the confirmation step, the button says "Confirm" not "continue.</td>
        </tr>
        <tr>
          <td>B</td>
          <td>TC-B</td>
          <td>Applicant wants to disclose their financial information, is not married, and has no dependents</td>
          <td>Pass</td>
          <td></td>
          <td>Looks good to me!</td>
        </tr>
      <tr>
          <td>C</td>
          <td>TC-C</td>
          <td>Applicant wants to disclose their financial information, is married, and has no dependents; lives with spouse</td>
          <td>Fail</td>
          <td>BUG-001</td>
          <td>When selecting yes to both spouse questions the next step in the form indicates conflicting information. I selected "yes" i lived with my spouse all of 2022 and the next step is the spouse's financial support.</td>
        </tr>
      <tr>
          <td>D</td>
          <td>TC-D</td>
          <td>Applicant wants to disclose their financial information, is married, and has no dependents; does not live with spouse, does not provide financial support</td>
          <td>Pass</td>
          <td></td>
          <td>Why are the Income data points note formatted but the Deductible expenses data points are?</td>
        </tr>
      <tr>
          <td>E</td>
          <td>TC-E</td>
          <td>Applicant wants to disclose their financial information, is married, and has no dependents; does not live with spouse, does provide financial support
          </td>
          <td>Pass</td>
          <td></td>
          <td>Looks good to me!</td>
        </tr>
      <tr>
          <td>F</td>
          <td>TC-F</td>
          <td>Applicant wants to disclose their financial information, is married, and has two dependents; lives with spouse
          </td>
          <td>Fail</td>
          <td>BUG-002</td>
          <td>After adding Dependents Annual Income information and clicking continue the form breaks and reveals this error message in the console: instrument.js:109 TypeError: Cannot read properties of undefined (reading 'first')</td>
        </tr>
      <tr>
          <td>G</td>
          <td>TC-G</td>
          <td>Applicant wants to disclose their financial information, is married, and has at least one dependent; does not live with spouse, does not provide financial support
          </td>
          <td>Fail</td>
          <td>BUG-002</td>
          <td>After adding Dependents Annual Income information and clicking continue the form breaks and reveals this error message in the console: instrument.js:109 TypeError: Cannot read properties of undefined (reading 'first')</td>
        </tr>
      <tr>
          <td>H</td>
          <td>TC-H</td>
          <td>Applicant wants to disclose their financial information, is married, and has at least one dependent; does not live with spouse, does provide financial support, does not live with dependent, does provide financial support
          </td>
          <td>Fail</td>
          <td>BUG-002</td>
          <td>After adding Dependents Annual Income information and clicking continue the form breaks and reveals this error message in the console: instrument.js:109 TypeError: Cannot read properties of undefined (reading 'first')</td>
        </tr>
      <tr>
          <td>I</td>
          <td>TC-I</td>
          <td>Applicant wants to disclose their financial information, is not married, and has at least one dependent
          </td>
          <td>Fail</td>
          <td>BUG-002</td>
          <td>After adding Dependents Annual Income information and clicking continue the form breaks and reveals this error message in the console: instrument.js:109 TypeError: Cannot read properties of undefined (reading 'first')</td>
        </tr>
      </table>

**Comment by jessicastump** [comment]
I went through  the form a couple of times (most cancelled out in error mentioned below, but was able to submit one app successfully with one dependent) and could not replicate error below on screen but realizing the note said "is in console"...so perhaps it was occurring. 

> **message in the console**: instrument.js:109 TypeError: Cannot read properties of undefined (reading 'first')

What I did encounter: when in the modals and canceling adding/editing a dependent, the page would blank out and I would have to start the application over. See screenshot below. 
![screencapture-staging-va-gov-health-care-apply-application-household-information-v2-dependent-information-2023-05-22-12_08_13](https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/b3cce058-fd22-4c2d-98d1-c761dc456020)

### Additional notes 
- **Confirming BUG-001** on the spouse information and the financial support question should only show when No is selected for having the same address question.
- **Child educational expenses:** Can the page be conditional based on birthdate entered? Since it is referring to a specific age range in the question. 
- Odd things with date input - noticed some numbers on years and such changing and jumping around after input (using mac laptop, keyboard and tab and trackpad to navigate)

**Comment by hdjustice** [comment]
We have had reports from previous research participants that the date numbers jump around/change unintentionally after input.  We haven't talked much about the "Memorable date" component, but I think we might have decided that it would be a whole-form change and should not be part of this work.

**Comment by hdjustice** [comment]
and to confirm that the "blank" screen (that you captured above) is what @mkerns1 described exactly.  It appears we have a few bugs to create here.  I will work on that this week and we can review next week when @longmd returns.

**Comment by hdjustice** [comment]
Use Case F:
- I entered the second dependent, on that page i mistyped the birth month and corrected it on the same screen, however the next screen is prompting me with an error on a field I have only just now seen.  **Could this be due to the URL not changing for the dependent info?**
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/38bd55fd-a4d1-4541-848d-1551a4d59ef5)

**Comment by hdjustice** [comment]
QUESTION:
If the dependents are edited, originating from the Review Page, and the applicant DOES NOT hit the Update Page button on the Review page after making edits, do they take affect still or revert back to the original input?

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/89ec1738-3e34-428b-8e1c-c0dcef989c38)

**Comment by hdjustice** [comment]
Ok cool, I was thinking about folks who may not notice that Update page button as something to be done.  Thank you!

**Comment by hdjustice** [comment]
All QA has been completed and all defects have been resolved.
