### ISSUE TITLE
FE | Profile | Boilerplate Prototype | Create template

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#51657]
## Background

In anticipation of using coded prototypes in future research studies, we'd like to create a boilerplate codepen prototype we can form for future projects.  This prototype should be responsive, and include:
- VA.gov styles
- VA.gov header and footer (without crisis line, we don't want anyone to come across it and have it not work, and we don't need that functionality for profile research)
- Profile navigation

## Tasks
- [ ] Create va-testing codepen account, or something similar so we have cleaner URLs. va-gov-profile could work?
- [ ] Create template
- [ ] Share with team
  

## Acceptance Criteria
- [ ] We have a forkable template we can use for research
