### ISSUE TITLE
[eFSR] Update submission analytics to show type of submission

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#51650]
## Issue Description
We'd like to track VBA vs VHA vs Combined submissions, so we should update the FSR successful submission event to include that additional information. 

---
## Tasks
- [ ] Update FSR submission event to include type of debt selected. 
- [ ] Update [this issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47442) with proposed changes for approval

## Acceptance Criteria
- [ ] Can track VBA vs VHA vs Combined FSR submissions
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
Changes have been merged,[ updated ticket with new tags](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47442), and analytics is starting to track. Waiting for feedback before closing out to make sure everything works

**Comment by Dr-Pongo** [comment]
[Merged PR with label name updates based on feedback](https://github.com/department-of-veterans-affairs/vets-website/pull/23174)

[Updated thread with new details](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47442#issuecomment-1400527647)

Moving to validate, will close out after final round of feedback on GA dashboard side of things

**Comment by Dr-Pongo** [comment]
Closing out as tracking is in place!
