### ISSUE TITLE
Investigate ongoing NaN issue

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#51653]
## Issue Description
The  Huron team has reached out as they continue to see issues with NaN coming thru on the FSR files. 
## Details
- From Ashlie 1/3/23: "We have implemented a fix on our end that will allow staff to access the Veteran submissions coming from VODA with NaN instead of a numerical value. Previously staff would receive an error when clicking on the bill in the Huron tool due to the broken code. We are still seeing the NaN come across in numerous submissions, and while staff are able to access some of the Veterans 5655 information from the worklist view, the necessary income/expenses are not visible because they do not exist in the file. Has a resolution been determined yet? Also is there a status on the file number issue?" 
- Ashlie has offered "I am happy to share examples of what we are seeing as well as Veteran Services."

---
## Tasks
- [ ] Investigate root cause of issue
    - Type casting
    - Mismatched addition types
- [ ] Find other possible occurrences of NaN in types 

## Acceptance Criteria
- [ ] FSR payload no longer contains NaN values and we have communicated the fix to Huron 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
