### ISSUE TITLE
FE | Profile | Add email channel research]| Update prototype

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#51658]
## Background

For our upcoming research effort, we need to refine a [Codepen prototype](https://codepen.io/moose62712/full/mdjOGga) so it more closely matches profile's notification settings feature.

## Tasks
- [x] Update stying for save success so the green border is applied to the input
- [x] Update form inputs so they are all checkboxes
- [x] Wire up the "update saved" feedback alert so it works correctly w/ each input
- [ ] (If time) add the VA.gov header and footer
  

## Acceptance Criteria
- [ ] Prototype is ready to use

**Comment by adamwhitlock1** [comment]
I messed around a little last night and created a testing account for us on codepen @andaleliz 

https://codepen.io/va-authenticated-exp-testing/pen/qBymxJp

This is the newest prototype. If we want to use this new account for the research, then that should be good to go in the most part. I will try to add the header and footer as time permits.

**Comment by Samara-Strauss** [comment]
Can we close this ticket? I am assuming this was already done before Liz's research started.

**Comment by andaleliz** [comment]
I don't need anything else from Adam on this.
