### ISSUE TITLE
MDT- Email step- Veteran contact details - edit details, v1

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5166]
## User Story:
As a veteran, I need to be able to edit my email so that I can update or correct information.

## Tasks
- Create a high fidelity mockup depicting how a veteran might edit address and contact details
- Upload exports to Invision and indicate initial focus point as a comment

## Acceptance Criteria:
- [x] Mockup aligns with VA.gov’s design system
- [x] Veteran is able to edit their email address
- [ ] The screen’s initial focus is incorporated
- [ ] Sketch artboards are uploaded to Invision and linked in this ticket as a comment
