### ISSUE TITLE
[SPIKE] [DDL] "down for maintenance" message

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#51669]
## Value Statement
**_As a_** veteran looking for a claim letter
**_I want to_** see some kind of message that lets me know when the service is down
**_So that_**  I'm not surprised when when I go to download a letter and the application just doesn't work

---
## Background Context
Our calls to VBMS are getting a response "DownForMaintenace" on occasion. When this occurs, veterans are unable to download their claim letters. Ideally, when that response is returned, we would have a message that told the veteran the service was down and that they should check back later. The duration of the downtime due to maintenance since launching this service, has been less than an hour each time it has occurred. 

### Related resources
[vbms_connect known errors list](https://github.com/department-of-veterans-affairs/connect_vbms/blob/master/lib/vbms/errors.rb)

## Acceptance Criteria
- [x] Outstanding questions are answered
- [x] Recommendation made [Recommendation](https://github.com/department-of-veterans-affairs/benefits-team-1-docs/discussions/4)
- [x] Implementation ticket created

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
Here are the things I'd want to look into before estimating this ticket:

1. What (if any) is the correlation between the `417` error and the `500` error?
  - There's not always a 417 (Expect error, VBMS::DownForMaintenance) paired with every 500 (Server Error), or even a 417 for a group of 500s, but when there are 417s there are also 500s. There were 121 417 errors within the same timeframe that there were only 30 500 errors.
  - We saw 417s from Jan 8th - 10th, but none after that, but clearly there was a problem from Jan 13th - 15th
2. Does the `DownForMaintenance` error only occur on `#index`? Can it also happen on `#show`?
  - `DownForMaintenance` has been triggered on both `#index` and `#show`
3. Are the `DownForMaintenance` errors and `Internal Server Errors` the only errors that affect the Veteran?
   1. What about those `302: Redirect` errors we saw?
     - It looks like an issue with the redirect because VBA/VBMS was down for maintenance.
   2. Are there more?
     - [vbms_connect known errors list](https://github.com/department-of-veterans-affairs/connect_vbms/blob/master/lib/vbms/errors.rb)
5. Do we care what the difference is between a `DownForMaintenance` and an `Internal Server Error`? 
   1. I care from a technical curiosity perspective, but is there a way we can word the message to be more generic? IE, do we _need_ a "System down for maintenance" message, specifically?
     - A DownForMaintenance error seems more useful than a generic 500 Internal Server Error, because it can be coupled with instructions for a user to return at a later time.
   4. Isn't the message pretty generic now? How can we differentiate? Should we differentiate?
     - As long as we provide actionable instructions ("check back later", or "try x, then try y"), then a veteran probably doesn't care about the specifics.

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jerekshoe** [comment]
@kjduensing About 2: I see it for both #show and #index in Sentry

**Comment by kjduensing** [comment]
@jacobworrell At stand up we talked about breaking this ticket into a spike ticket and an implementation ticket - thoughts?

**Comment by jacobworrell** [comment]
@kjduensing sounds good to me.

**Comment by kjduensing** [comment]
Not all errors during downtime are 417s

Possible solutions:
- always 500 with text that say perhaps down
    - Always say "down for maintenance"
- Check Amt of 500s in a row OR a 417 and display down for paint
- Always just display the correct message

Errors:
504: GatewayTimeout
service: VAFileNumber not found
service: EoF error
417: DownForMaintenance
500: VBMS::Unknown
302: Redirect

**Comment by kjduensing** [comment]
[Recommendation](https://github.com/department-of-veterans-affairs/benefits-team-1-docs/discussions/4)

**Comment by samcoforma** [comment]
I like the recommendation you drafted, it covers a lot of ground without being too clever (and possibly brittle).
