### ISSUE TITLE
Update Custom Tracks flow 

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#51672]
## User Story
As a Governance team member, I want to have all of my operational guidance in alignment so that I am easy able to follow the guidance without questioning which guidance is correct and/or introducing confusion.

As a Governance team member, I want to make sure the operational guidance is clear and does not include any unnecessary steps so that I am not doing extra, unneeded work.

Assignee: @CherylEvans 
Peer Reviewer: @allison0034 

## Description
We modified the Collaboration Cycle kickoff questions in May of 2021 when we launched the new Collaboration Cycle Request ticket. At the time, we overlooked the fact that the Custom Tracks flow, which is used to determine what recommended touchpoints each VFS product/feature should have, was not updated to reflect the change in kickoff questions. 

The primary purpose of this ticket is to modify the flow so that it aligns with the current kickoff questions in the Collaboration Cycle Request ticket. The secondary purpose of this ticket is to remove the unnecessary information that is still lingering from the first iteration of the Custom Tracks flow. Retired touchpoints, practice area involvement and artifacts can all be removed from the flow as they are no longer contingent on the product, feature and/or track.

## Impacted Artifacts
[Custom Tracks Flow](https://lucid.app/lucidchart/c99ee20a-3cc9-4390-a54b-64fbd9d7596b/edit?page=0_0&invitationId=inv_a90dcf81-58ab-443e-b799-6f363696be78#) in LucidChart (AKA "Wizard V5")
[Custom Tracks Flow Confluence page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1872822276/Custom+Tracks+Flow)

## Tasks
- [x] @shiragoodman to share Lucid Chart diagram with Cheryl and Allison via email
- [x] The language "Required Collaboration Cycle touchpoints" should be reworded to "Recommended Collaboration Cycle touchpoints"
- [x] Delete all references to "Practice Areas involved"
- [x] Delete all references to "Required VFS artifacts"
- [x] The following questions are no longer part of kickoff and can be removed from the flow:
   - Are you making changes to the visual design?
   - Are you making changes to the user flow?
   - Are you making changes to urls, navigation, or entry points?
   - Did you answer "Yes" to any of the 3 previous questions?
- [x] The Contact Center Review in Track 3 should fall under "Recommended Collaboration Cycle touchpoints" by default
- [x] New/iteration is no longer an explicit question in the kickoff. However, it can be determined by the VFS Product Directory. If the product is in the VFS Product Directory, it's an iteration. If the product is not in the VFS Product Directory, it's new.
- [x] Once all changes have been made to the Lucid Chart Custom Tracks flow, the diagram will need to be embedded in the Custom Tracks Flow page on Confluence. At the time this ticket was written, @shiragoodman was getting this error below. We may need to reach out to Platform Content team for assistance.
![image.png](https://images.zenhubusercontent.com/5f62315e822e9b2aa88b1f1c/097721ff-1a7d-4019-b939-53d35f70c830)

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The Custom Tracks flow aligns with our expectations for Collaboration Cycle kickoff response

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
@shiragoodman I have made all of the changes to the CTF, but have a question.  Does this task (New/iteration is no longer an explicit question in the kickoff. However, it can be determined by the VFS Product Directory. If the product is in the VFS Product Directory, it's an iteration. If the product is not in the VFS Product Directory, it's new.) need to be added to the verbiage on the CTF doc?  If so, where? I suggest adding succinct verbiage in the place of "Is your work a new product/feature or an iteration to an existing product/feature."  Thoughts?  Just sent you the edited link.

**Comment by shiragoodman** [comment]
@CherylEvans yea, that's a good suggestion. I don't have a preference, so whatever you think makes the most sense.

**Comment by CherylEvans** [comment]
@shiragoodman Cool!  I will make the changes and then share with you for final approval. I will tag you here as well.

**Comment by CherylEvans** [comment]
@shiragoodman I have completed my edits to CTF.  [Link](https://lucid.app/lucidchart/c99ee20a-3cc9-4390-a54b-64fbd9d7596b/edit?viewport_loc=-188%2C813%2C1512%2C756%2C0_0&invitationId=inv_a90dcf81-58ab-443e-b799-6f363696be78) 
If you're good with it I will embed the diagram in the Custom Tracks Flow page on Confluence.  If I have issues with this I will reach out to Platform Content team for assistance.

**Comment by shiragoodman** [comment]
it looks like the Contact Center Review under Track 3 is in the wrong place. It should be after 'End' as a default touchpoint for this track.

Could you also try condesing it a bit? Right now, Track 3 takes up a lot of physical space in the flow.. could we move it all up?

**Comment by CherylEvans** [comment]
@shiragoodman I will correct and condense!! :-)

**Comment by CherylEvans** [comment]
@allison0034 Confluence [Custom Tracks Flow page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1872822276/Custom+Tracks+Flow), We ended up deleting the Lucidchart diagram and embedding a screenshot of the updated diagram.  Unbeknownst to Shira and I, and according to Andrea, who is the Confluence admin, we don't currently use Lucidchart anymore.  That is why we couldn't embed the new LC diagram into Confluence.  Long story short, the screenshot looks great and the diagram is now updated and ready for your review.  Sorry for the novel!  Let me know if you have any questions or concerns. :-)

**Comment by allison0034** [comment]
@CherylEvans this does not match the kickoff questions we ask. My suggestion would be to...

- Remove "If your product is not in the product directory...", we do not ask that so it should not affect the flow as it isn't in the flow chart
- Change "Content changes" to match the question "Will your work involve changes to." and then have 3 track options to match, 
  - Tools & applications
  - Static pages
  - Both
- Track 3 is missing a bunch of touchpoints, I only see research and analytics, is that correct? Same with track 4. And I am not sure how you get to those tracks bc we do not ask the question that puts you down those tracks.
- I also think we need to be more clear about if you answer yes or no in track 3. 

Maybe we can chat about this and I can explain better.

**Comment by CherylEvans** [comment]
@shiragoodman @allison0034 Here is the embedded diagram on the [Custom Tracks Flow confluence page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1872822276/Custom+Tracks+Flow).
Allison worked her Design magic and made it look great!  It is clear, concise, and easy to read/understand.

**Comment by allison0034** [comment]
Looks good to me! : )

**Comment by CherylEvans** [comment]
@allison0034 Thank you!  I'm going to close. :-)

**Comment by shiragoodman** [comment]
The new flow looks great! Thank you both so much for working on this.

One concern I have, that is outside of the scope changes you made, is that we recommend a Privacy and Security review for the iteration of the static page, but not for the new static page. I am going to add this as a ticket for the new Collaboration Cycle - Privacy, Security, Infrastructure Readiness Review (PSIRR) improvements (#52419) initiative bc I don't think we have the knowledge/experience to make that decision.
