### ISSUE TITLE
CANCELED**Create baseline measure of Login.gov Adoption

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#51678]
## Description
As part of the Inherited Proofing process, this Epic will track the body of work that captures the current state of AVC/IVC accounts on VA.gov as described in this document: [Inherited Proofing - Measure progress](https://docs.google.com/document/d/10Il1nZg3ZEDDHAzXHk2nq_kkuwfDM6BwtmPKTEU2_n0/edit)

**Note:** We need to add in a way to measure the progress of users who are visiting VA.gov that either have Login.gov or an ID.me account

### Terms
- AVC: appropriately verified credential. For example, a Login.gov IAL2 AAL2 is an AVC
- IVC: ID.me verified credential. On VA.gov an IVC is LOA3 AAL2
- Identity Proofed Credential: a credential which has completed the process of producing document to prove they are who they claim to be. This can currently be completed remotely through login.gov and ID.me. There is no other method to remotely proof a credential which meets IAL2 or LOA3 standards. The goal of VA.gov is to move all users who actively access sensitive information on VA.gov to utilize an Identity proofed credential.

### Requirements
The summary of the requirements are:

- [ ] Milestone 1 - Creation of AVC table + functionality when user authenticates
- [ ] MIlestone 2 - Backfill AVC table with lots of data for a baseline, (eg create reporting)

#### Milestone 1
**Table schema and steady-state performance**

- [ ] Table for AVC, IVC
  - Entry for each user
  - Columns:
    - User_account
      - On Authentication, query by user_account, create new record if it doesn’t exist
    - AVC
      - On authentication, determine if user has a verified login.gov credential, set to true if so, false otherwise
    - IVC
      - On authentication, determine if user has a verified id.me credential, set to true if so, false otherwise
- [ ] Add column on user_verification
  - Reference to credential email table
- [ ] Credential email table
  - Does this need to be encrypted? (Yes)
  - This will be updated whenever a user authenticates
  - We will overwrite the existing email with whatever is current in the credential
- [ ] Logs 
  - Upon authentication, log user account, and whether they had an AVC or IVC

#### Milestone 2
**Table Backfill**
- [ ] Write a raketask
  - For every existing user_account
    - Determine if user has an AVC or IVC by seeing if it has an equivalent login.gov or id.me user_verification
    - Users won’t necessarily have updated credential email (this will require them authenticating to update properly)

**Reporting**
- [ ] Create a CRON Sidekiq job
  - Periodically queries AVC table, returns how many users have AVC, IVC
    - How many users don't have an AVC or IVC
      - Based on each CSP
    - How many accounts do not have an AVC or IVC
      - ID.me
      - Login.gov
      - DS Logon
      - MHV Premium
- [ ] Datadog Monitor that watches the logs from the Sidekiq job

**Comment by joeniquette** [comment]
Diagram outlining how this will work: https://lucid.app/lucidchart/52e77cd8-956c-4ff3-9c4d-da5ec1308264/edit?beaconFlowId=141F4DC910593F11&invitationId=inv_80b0d060-e875-40c7-a707-04e9137920df&page=0_0#
