### ISSUE TITLE
[UX] Update Product Artifacts for Release

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#51692]
## Description
Update various product artifacts, as necessary, based on the feature release.

## Tasks
- [ ] Update the Pre-Check-in Product Guide, including content and screenshots, if necessary
- [x] Update the eCheck-in Product Guide, including content and screenshots, if necessary
- [x] Update user flow diagrams, if necessary
- [x] Send updated screenshots to Danielle Thierry for the Resources & Support (R&S) articles in VA.gov, if necessary

## Acceptance Criteria
- [ ] Product Guides are up-to-date and ready to be pushed to production (content & screenshots)
- [ ] ALL screenshots are of the highest quality possible
- [ ] [User flow diagrams are up-to-date](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/3Op54Vm) and ready to be pushed to production
- [ ] R&D articles are up-to-date

**Comment by loripusey** [comment]
@kellysmith1008 will we be done with this by the end of the sprint?
cc @benbrasso-agile6 @sarahknoppA6

**Comment by kellysmith1008** [comment]
@loripusey Admittedly, I'm a bit confused as to if the VAOS redesign is going out at the same time as the simplified header and footer. But I can get these done with what's currently in staging by the end of this sprint, yes ma'am!

**Comment by loripusey** [comment]
@kellysmith1008 it depends on when engineering will be done, which should happen this next sprint; however, we should be able to use the sketch files to snapshot for product guides (is that correct @benbrasso-agile6 ?) The idea is that the product guides get pushed to GitHub the same day we release the code to production.

**Comment by benbrasso-agile6** [comment]
It's tough. It really depends on the feature we're updating. It's probably best to leave it up to the person doing the product guide updates to determine when they can be worked on and completed. 

For example, design and engineering work is still happening. So, it's possible we have all the assets needed to update the product guides. But, it's also just as possible we need to wait for staging to be in a good place to get the correct screenshots. 

And, of course, if we're in a rush to get the product guides completed... there are other options to consider. For example, edit a wireframe quickly in sketch that's needed, add the appropriate screenshot a few days later to the product guide, etc. 

Sort of a chicken before the egg conversation. 

For this one, I would try to get as much work done completed for now. Then, when engineering is done, grab the remaining screenshots that are needed.

**Comment by benbrasso-agile6** [comment]
Is the VAOS feature flag even turned on right now in staging?

**Comment by loripusey** [comment]
good question, will ask at stand up

**Comment by kellysmith1008** [comment]
I have completed check-in with what's in abstract and will start working on pre-check-in now. Will verify and update as needed once feature flag is lifted on staging

**Comment by kellysmith1008** [comment]
I checked just now and staging doesn't show VAOS update. @brianseek Would you mind throwing screenshots for:
"Answer pre-check-in questions" 
"You've completed pre-check-in"
and
an appointment details page?

**Comment by kellysmith1008** [comment]
I've photoshopped some screenshots for pre-check-in and will make a note to update them once VAOS design is on staging
