### ISSUE TITLE
Add product/feature definitions page as reference in Collab Cycle guidance

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#51711]
## User Story
As a VFS team member, I want to ensure my products and/or features align with the OCTO definitions so that I can be sure I am meeting the expectations of all teams building on VA.gov.

Assignee: @sterkenburgsara 
Peer Reviewer: @briandeconinck 

## Description
OCTO Product team members have created the [Product operations terms and definition](https://depo-platform-documentation.scrollhelp.site/getting-started/product-operations-terms-and-definition) guidance and published it on Platform Website. In order to ensure VFS teams are familiar with these definitions and labeling their work in accordance with these definitions, Governance team has been asked to reference/link this guidance within the Collaboration Cycle. 

## Impacted Artifacts
[Collaboration Cycle Request template ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-review%2Ccollaboration-cycle%2CCC-Request&template=collaboration-cycle-request.yml&title=Collaboration+Cycle+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D)(aka kickoff)
[Collaboration Cycle Kickoff page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/collaboration-cycle-kickoff) on Platform Website
[Product operations terms and definition](https://depo-platform-documentation.scrollhelp.site/getting-started/product-operations-terms-and-definition) 

## Tasks
- [ ] On the CC kickoff touchpoint page, add a footnote after "product/feature" in the heading, "Questions about your product/feature"
   - similar to question #3 re: static pages
   - The footnote should link out to the [Product operations terms and definition](https://depo-platform-documentation.scrollhelp.site/getting-started/product-operations-terms-and-definition) guidance
- [x] Similar changes should be made to the CC Request template, however it's not as cut/dry as the kickoff page as to where the reference should be linked.
   - options include "VFS product information" but changing it to "VFS product/feature information" and adding the footnote after "product/feature"
   - Other options include linking from the form entry points:
![image.png](https://images.zenhubusercontent.com/5f62315e822e9b2aa88b1f1c/6bdb4c04-31b5-41c0-98f4-476892cbd1db)
   - NOTE: the Collaboration Cycle Request template is a YAML template. @briandeconinck has been assigned peer reviewer as he has YAML experience and can help assist if needed. Please be sure to create a pull request and assign Brian as the reviewer. 
- [ ] Please feel free to modify and/or update the language or organization of content as you see fit. You are welcome to consult with other Governance team members as well, if you'd like.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS team members are able to view the OCTO Product operations terms and definitions as they as submitting their Collaboration Cycle kickoff.

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@CherylEvans has been removed as peer reviewer, and @briandeconinck has been added as replacement. This is bc this ticket involves changes to a YAML template and Brian is the only Governance team member with experience working in YAML. Please let me know if you have any questions.

**Comment by shiragoodman** [comment]
@sterkenburgsara @briandeconinck  - I made updates to the ticket. Please let me know if you have any questions. Thanks.

**Comment by sterkenburgsara** [comment]
Pull request made to edit the CC Request template (yaml) on 1/19 - @briandeconinck listed as reviewer

**Comment by briandeconinck** [comment]
Reviewed PR and left comments.

**Comment by sterkenburgsara** [comment]
@briandeconinck [draft confluence page with edits](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2501050369/Copy+of+Collaboration+cycle+kickoff+Sara+-+Ticket+51711) is ready for review.

**Comment by briandeconinck** [comment]
@sterkenburgsara left a comment for you on the Confluence draft.

**Comment by sterkenburgsara** [comment]
@briandeconinck Thanks. I saw your comment and removed the latter half of the sentence regarding features vs. products that said "decide which is most accurate."

**Comment by sterkenburgsara** [comment]
@shiragoodman can you take a look at this [YAML ticket on my personal repo](https://github.com/sterkenburgsara/sandbox/blob/main/.github/ISSUE_TEMPLATE/collab-cycle.yml) with the proposed edits and see what you think?

**Comment by shiragoodman** [comment]
@sterkenburgsara this looks great. Thank you. Great idea linking from the subtext below the heading.

I do have a small addition that needs to be made to the ticket, and since it's still in draft, what better time than now?

![image.png](https://images.zenhubusercontent.com/5f62315e822e9b2aa88b1f1c/8f634c8c-75bd-4e1a-893d-0b9fa6e53694)
The above section of the template has been challenging for VFS teams to complete. You may have seen it come up in [this Slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1674773371625739) recently. We want teams to look at the directory and either 1)confirm the info is correct, 2) submit a ticket to make changes or 3) submit a ticket for adding their product if it's not currently listed (this one is still in progress). However in the template, we have a required field for the VFS that asks them to confirm their info is correct. If they follow option 2 or 3 above, the required checkbox doesn't make any sense.

Can we update the required checkbox to read something like, "I have reviewed the VFS Product Directory and either confirmed my products information is correct or taken the appropriate action to update my products information." Feel free to wordsmith. 

In addition, the directory's formal name is "VFS Product Directory" - can you make sure the surrounding content is accurate?

thank you! Let me know if you have any questions.

**Comment by sterkenburgsara** [comment]
@shiragoodman [YAML ticket](https://github.com/sterkenburgsara/sandbox/blob/main/.github/ISSUE_TEMPLATE/collab-cycle.yml) updated with the changes above re: VFS product directory. Can you take a look and approve before I submit a merge request to the master template? // cc @briandeconinck

**Comment by shiragoodman** [comment]
looks perfect - thanks @sterkenburgsara !

**Comment by briandeconinck** [comment]
Reviewed, approved, and merged in #52269!
