### ISSUE TITLE
Automate updating the component usage data

### ISSUE THREAD

**Issue by Andrew565** [department-of-veterans-affairs/va.gov-team#51721]
## Issue Description

See [this discovery ticket](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/va.gov-team/51537) for full details. In summary, it is desirable to automate updating the component usage data so that we don't "oops, forgot" constantly.

---
## Tasks
- [ ] Get API access approval and details from the Analytics and Insight Platform Support team (in Slack)
- [ ] Create a script that will update the vets-website and content-build repos/content (`git pull && yarn`)
- [ ] Create a new script that will take the results of the existing `yarn report` command and upload it to BigQuery using the API access details from the above task
- [ ] Create a new command to call the update script, then `yarn report`, then upload to BQ
- [ ] Figure out how to call this new command and get it to work properly using Github Actions and/or a cron job

## Acceptance Criteria
- [ ] Component usage data stored in BigQuery is updated automatically once a week without direct user intervention
