### ISSUE TITLE
[Research] Share HLR Heuristic Review (part 3 of 3)

### ISSUE THREAD

**Issue by Evafloyd** [department-of-veterans-affairs/va.gov-team#51736]
## Share Heuristic Review Findings

This ticket is to create a simple 1-page report concentrated on the main heuristic areas. 

## Tasks
- [ ] Combine average scores and highlight areas of focus
- [ ] ID key measures for future analytic tracking

## Acceptance Criteria
- [ ] Review review with the team (particularly product)
- [ ] Publish findings to final location (TBD)

**Comment by uxgary** [comment]
Hey @Evafloyd  I think this ticket is referring to the [HLR Summary of findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/higher-level-review/research/heuristic-review-summary-of-finding.md) If so, can we close this?
