### ISSUE TITLE
Sunset Pact

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#51793]
## Product Outline
After the Circle CI secret leak, we’ve decided to sunset our PACT Broker service as it’s not providing enough value to maintain.

The most recent Pact test was written over two years ago. Engineers aren't writing Pact tests because writing them was never enforced.

When Pact was announced, engineers weren’t happy about the idea of having to write more tests. And some didn’t like the idea of contract tests altogether.

Because it hasn't been used at all, in over 2 years, we've decided to sunset it.

## High Level User Story/ies
As a _____, I need _____ so I can _____.

## Hypothesis or Bet
**If** _we make this change_ **then** _we expect this to happen_.

## OKR
_Which Objective / Key Result does this epic push forward?_

## Definition of done
- [x] All pact files have been removed from vets-api repo
- [x] All pact files have been removed from vets-website repo
- [x] All pact files have been removed from product-directory repo
- [x] All pact settings have been removed from AWS Parameter Store
- [x] All pact files have been removed from Confluence (and the Platform docs)
- [x] BigQuery queries for contract test results have been removed
- [x] All references to Pact/contract tests have been removed from the QA Standards dashboards in DOMO
- [x] All references to Pact/contract tests have been removed from the Product Dashboards in DOMO

**Comment by npeterson54** [comment]
Holden gave instructions to close
