### ISSUE TITLE
Explore additional empty states post Dec 9th fix

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#51794]
## Issue Description
FSR Submission bug was resolved on December 9, 2022. A safety net has been established to catch any submissions so they are routed to VBA appropriately. Since Dec 9th we have seen submissions come in (see data chart). Additional testing is required to track down any remaining issues.
![image.png](https://images.zenhubusercontent.com/5f7f60ca14e26c658f77b9f5/fad08616-913b-46f2-a029-5e6eb99d0d38)

---
## Tasks
- [ ] Conduct additional testing to identify remaining issues and define next steps

## Acceptance Criteria
- [ ] Issue has either been resolved or next steps are identified and documented for future implementation.
---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
This bug is caused from save in progress not containing updated feature flags. Forcing the flags to update mid form could cause additional issues, so the solution is to wait for the save in progress forms with the old feature flag values to expire or be submitted. If they are submitted, BE its tracking and appropriately routing so the submissions are still going through. We shouldn't see any more instances of this happening after any remaining save in progress forms expire after [the fix applied on December 9](https://github.com/department-of-veterans-affairs/vets-website/pull/22901). This logging can be removed after a few weeks after Feb 9 (60 days after patch), and we are no longer seeing any empty submissions. 

I'm closing this ticket out since it is being tracked and I will be opening a new ticket for identifying affected veterans. 

CC: @denisecoveyduc @ScottyRJames @OptionSelect

**Comment by denisecoveyduc** [comment]
I have updated our analytics tracking with the following note to ensure that we understand how many submissions are coming our way before the save in progress files expire. If any additional bugs are discovered we will open a new issue to track. 

> **Empty states the result of a bug that was caused from save in progress not containing updated feature flags. This forced the flags to update mid-form, causing this issue. We will not see any empty states once any current ‘save in progress’ forms expire on Feb 9,2023. If a Veteran completes a saved in progress form and submits it, we are tracking them on the backend and appropriately routing to VBA. Therefore any submissions are being tracked as VBA submissions.
