### ISSUE TITLE
[Desk Research] Refresh on HLR Desk Research

### ISSUE THREAD

**Issue by Evafloyd** [department-of-veterans-affairs/va.gov-team#51805]
## Description
In preparation of additional HLR work, revisit past HLR research, journey maps, recent Reddit articles, etc to form a current base understanding of the Veteran experience as it relates to HLR. 

## Resources
Product repo: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/decision-reviews/higher-level-review
Domo: https://va-gov.domo.com/page/447193050

## Tasks
- [ ] ID source/reference materials
- [ ] ID existing OKRs, data sources, and metrics available 
- [ ] Review materials
- [ ] [Document](https://docs.google.com/document/d/1RjWZoCO1t0IO9YYSytZpvOpR3hA9KFGfUNWJTuXkOdM/edit?usp=sharing) topline findings and share with the team; including potential areas of improvement, forming hypotheses and additional research questions.

**Comment by saderagsdale** [comment]
@Evafloyd @uxgary Hey both! is this done?
