### ISSUE TITLE
BE | Profile | Military History | Update data source in response

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#51811]
## Background
The service history response from VA Profile contains a `data_source` field that should be removed.

## Tasks
- [x] Remove `data_source` field from response.
- [x] Update any affected specs

## Acceptance Criteria
- [x] Test in staging environment - ensure field is removed.

**Comment by tpharrison** [comment]
@adamwhitlock1 The `data_source` field has been removed from the `v0/profile/service history` response.
