### ISSUE TITLE
[FE] Update analytics success event to not include 'Source' data

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#51813]
# User story

As a product team, we should have a more generic success event that is firing to GA when the `service_history` endpoint is successfully fetched.

## Description

The action used to create an event with an event that was used for tracking the eMIS to Profile transfer, but is no longer needed. The event can now just be `successful` without any additional info appended to the end.

Code is here:
https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/profile/actions/index.js#L106

## Tasks

- [x] Update event name
- [x] Deploy to staging and verify that event is firing correctly

## Acceptance Criteria

- [x] Events fire as 'successful' 
- [x] Verified in GA

**Comment by adamwhitlock1** [comment]
@Samara-Strauss  and @BerniXiongA6 should be good to validate now.

Events look to be firing correctly now, starting Jan 21 events started coming in as just success without source being added:

![Screenshot 2023-01-23 at 10.29.14 AM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/3ef43789-6be9-4e95-ade2-6638fb0b6ba3)

**Comment by Samara-Strauss** [comment]
Validated! Thank you!
