### ISSUE TITLE
[Research] Military info discovery: Kickoff research and gather background info

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#51818]
### Background

[Research outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/military-information/discovery-and-research/2023-military-info-discovery/README.md#research-outline-expanding-the-military-information-section-of-the-vagov-profile)

I'd like us to do some discovery on veterans' needs around military information on VA.gov. Currently, we have a very brief section of the profile dedicated to military info, but we've never really talked to users about it and assessed whether it meets their needs and expectations, or how we could improve it. We've never even asked them if the profile is where they'd expect to find military information. We have a lot to learn.

### Tasks

In order to get ready to conduct some research, you should:

- [x] [Review the research outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/military-information/discovery-and-research/2023-military-info-discovery/README.md#research-outline-expanding-the-military-information-section-of-the-vagov-profile)
- [x] Regroup with Samara and Berni to discuss this work
- [x] Review the military info section of the profile (Use user 80)
- [x] [Understand what the DD214 is and why it is important](https://www.benefits.com/veterans-benefits/form-dd-214#:~:text=Form%20DD214%20is%20a%20Department%20of%20Defense%20document,proof%20of%20service.%20Information%20Included%20on%20Form%20DD214)
- [x] [Understand the PACT Act at a high level](https://www.va.gov/resources/the-pact-act-and-your-va-benefits/)

### Acceptance criteria

- [x] Have enough of an understanding of research goals and military information to be able to start on a research plan

--------

### Associated tickets

- #51818
- #51821
- #52010
- #51822
- #51886
- #51887
- #51888
- #51889

**Comment by fmccaf1** [comment]
For staging user 80 - JESUS BARRETT - it seems there is no military info on file (or at least nothing is populating in his profile). Here's a screenshot:

![image.png](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/eb6ebc7d-84e7-4317-bb26-2950a2dec04c)

I'll just start going down the list of staging users and trying to find one unless you have another one that you think is likely to have military info, @Samara-Strauss

**Comment by Samara-Strauss** [comment]
@fmccaf1 I should have explained how we number staging users! It's not based on their row in that spreadsheet; it's based on the number in their email address. So, user 80 has the following email address:

![image](https://user-images.githubusercontent.com/34068740/213019907-dd03784f-1ed2-49f5-8dbb-ab40947a6f60.png)

The user's name is Oscar Jones, line 82 in the spreadsheet. I'm not posting any other info here since that info is sensitive, and we should not post passwords in this repo since it is public.
