### ISSUE TITLE
Sprint 14 objectives (1/29 - 2/11)

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5181]
### Long term planning

- Tressa out: Feb 9 – 19
- Erik out: Feb 7
- Samara: 1/2 day 1/31

### Order of priorities

1. Address validation — QA & bug fixes
2. Profile 2.0 — Create states for all screens; Form refactoring
3. Maintenance & documentation
4. (If time) Profile 2.0 — Copy updates

#### QA

**Tze**

- [x] Finalize QA spreadsheet and QA test cases #5010
- [x] Run QA and add bug tickets based on QA. #5012

**Samara**

- [x] Help manage the QA process #5209
 
**Brad**

- Work on bug fixes and 508 review updates as they come in.
- [x] Address validation - can't select entered address with validation key #5178
- [x] Address validation - Still getting validation keys that don't work #5180

#### 508 Review

- [ ] [Request 508 Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/vsa-accessibility-review-process.md) #5323

#### Other

- [x] Add documentation to address validation code in vets-api #3796
- [x] Address validation: Load testing #5032

### Profile 2.0

Design
- [x] Design review #5061
- [x] Finish Contact information #5264

Frontend
- [x] Convert profile address form to use SchemaForm #5078
- [ ] Convert profile phone number form to use SchemaForm #5118
- [x] Convert profile email address form to use SchemaForm #5121

### Monitoring, maintenance, bug fixes, hardening, 508, etc.

- [ ] Remove lodash/fp from front-end application code #5257 (will go into next sprint)
- [x] [BE] Direct Deposit: Review product outline and update if needed #5251
- [x] [FE] Direct Deposit: Review product outline and update if needed #5252
- [x] [BE] Address validation: Review product outline and update if needed #5254
