### ISSUE TITLE
[Research] Military info discovery: Write conversation guide

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#51822]
### Background

[Research outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/military-information/discovery-and-research/2023-military-info-discovery/README.md#research-outline-expanding-the-military-information-section-of-the-vagov-profile)

[Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/military-information/discovery-and-research/2023-military-info-discovery/research-plan.md)

[Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/military-information/discovery-and-research/2023-military-info-discovery/conversation-guide.md)

Currently, we have a very brief section of the profile dedicated to military info, but we've never really talked to users about it and assessed whether it meets their needs and expectations, or how we could improve it. We've never even asked them if the profile is where they'd expect to find military information. We have a lot to learn.

## Tasks
- [x] Get conversation guide template
- [x] Discuss any questions about drafting a conversation guide with Liz
- [x] Draft conversation guide
- [x] Have Liz review
- [x] Incorporate edits
- [x] Have Samara review
- [x] Incorporate edits

## Acceptance Criteria
- [x] Conversation guide complete and ready for submission

--------

### Associated tickets

- #51818
- #51821
- #52010
- #51822
- #51886
- #51887
- #51888
- #51889

**Comment by fmccaf1** [comment]
Okay, @Samara-Strauss, I've incorporated all of Liz's edits. Now it's your turn, when you're ready. [Conversation guide linked here.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/military-information/discovery-and-research/2023-military-info-discovery/conversation-guide.md)

**Comment by Samara-Strauss** [comment]
### Accessing and using service history information - 35 minutes

> Where were you?

I don't think I would understand what you were asking if I were the veteran. I'd be more straightforward with this question based on whatever their response was to "Tell me about a time when you needed your service information for any reason."

> What specific information was needed as a part of that process?

I might also clarify that you are looking for what *military information* was needed as part of that process, because many processes will require a lot more than military info, and I could see this going down a rabbit hole in a way that derails from the scope of our research.

> What did you do to obtain those pieces of information?

Again, I would just be sure to clarify that you are looking for info on who they obtained documentation on their military service history.

> Do you also have a DD214?

Most people will have a DD214, though there are some other discharge papers. Whether they physically have a copy of it is a different question. What are you trying to assess with this question?

> Are there any other formal documents that you have received from the VA that might have the same info as the DD214?

What is the goal of this question?

### Expectations/hopes for finding service info - 8 minutes

> Let's imagine that you could easily find your service information online, using your browser. Pause. What is your immediate response to that idea?

> Would accessing your service history information online be easier or more difficult than ________ (your current way of accessing that information)? Why?

What are the goals of these questions? I would imagine that most people would love to easily access military info online, so I want to make sure I understand what kind of insights you're hoping to capture.

> If that information were on VA.gov, where on that site would you expect to find your service information?

I'd like to see them navigate the site. Maybe this was already the plan, but if not, I think we'll get better information if they're actually able to show us their thinking.

---

Generally, I still think we'd get helpful insights from having a conversation about the military history section of the profile after the interview portion of the call. I'm curious if the section is useful to them (guessing no), and if not, what could we do to make it more useful? This is one of the main objectives of the research -- at least, from my perspective -- and while I appreciate the holistic approach you take in the initial interview portion, I'm nervous we wouldn't walk away with meaningful insights on how we might improve VA.gov. From the interview, I think we'll walk away with an understanding of when veterans are asked for their military service history and how they might use their DD214, but I do worry that this might be too high-level to extrapolate to the VA.gov interface. I don't want to lose an opportunity to get feedback on the profile.

**Comment by fmccaf1** [comment]
@Samara-Strauss 

> **Do you also have a DD214?** Most people will have a DD214, though there are some other discharge papers. Whether they physically have a copy of it is a different question. What are you trying to assess with this question?

> **Are there any other formal documents that you have received from the VA that might have the same info as the DD214?** What is the goal of this question?

For both of these questions: I'm looking to open the door to other possible use cases we haven't already defined for the Military Info section of the profile. If there is another form with that info, or if someone didn't receive their DD214 at first, and had to use other shortcuts, I think we'd want to know that. It could lead us to good reasons to add more info to the Military Info section, for example. And I've learned from a little discovery that the when and how of receiving one's DD214 is not so cut and dry. Does that make sense?

> **Let's imagine that you could easily find your service information online, using your browser. Pause. What is your immediate response to that idea?** **Would accessing your service history information online be easier or more difficult than ________ (your current way of accessing that information)? Why?** What are the goals of these questions? I would imagine that most people would love to easily access military info online, so I want to make sure I understand what kind of insights you're hoping to capture.

I'm again opening the door for more possible info, which is generally how I try to do generative research. It's definitely possible that we don't learn something useful, but we will be able to learn if participants are aware of digital access to their service history online that we (or I) are not yet aware of. Also, I'm curious if all veterans would react the same to this idea, or if some would respond at least initially with fear about their private info being online. If we get some negative feelings in their initial reaction, it could potentially help us effectively counter that immediate reaction in designs. Let me know if this is helpful for understanding my thinking here.

> Generally, I still think we'd get helpful insights from having a conversation about the military history section of the profile after the interview portion of the call. I'm curious if the section is useful to them (guessing no), and if not, what could we do to make it more useful? This is one of the main objectives of the research -- at least, from my perspective -- and while I appreciate the holistic approach you take in the initial interview portion, I'm nervous we wouldn't walk away with meaningful insights on how we might improve VA.gov. From the interview, I think we'll walk away with an understanding of when veterans are asked for their military service history and how they might use their DD214, but I do worry that this might be too high-level to extrapolate to the VA.gov interface. I don't want to lose an opportunity to get feedback on the profile.

I'll just share my opinion, but please know that if you'd prefer a more evaluative research approach, I'd be happy to go in that direction instead. If we're looking at the research goal of identifying what would make the military info section of the profile more useful, I think this is the exact methodology that will get us there. Generally as a researcher, I think we want to 1) identify the context(s) for when the need arises to view, use, change this info and 2) inspect those contexts to understand what info exactly the veteran needs and how it should be displayed to make their task easy, quick, and painless. If for example, every time a veteran needs this info, they're filling out a form, we can look at all the forms and make sure every detail that comes up in a form is in that section of the profile. In my experience, participants struggle to articulate what they would hypothetically need when we put them on the spot in an interview. I think we can do that work for them! 

Since the interviews are at this point only 45 minutes long, I could add a 10 minute evaluative portion to the end, where we look at the military info section together and talk about it. Would that feel satisfactory to you? Let me know.

**Comment by Samara-Strauss** [comment]
Summarizing what we just talked about over Zoom:

> Do you also have a DD214? Most people will have a DD214, though there are some other discharge papers. Whether they physically have a copy of it is a different question. What are you trying to assess with this question?
> 
> Are there any other formal documents that you have received from the VA that might have the same info as the DD214? What is the goal of this question?

We talked about rewording these questions to something like "What discharge papers did you receive?" and "Do you have a physical copy of them?"

> Let's imagine that you could easily find your service information online, using your browser. Pause. What is your immediate response to that idea? Would accessing your service history information online be easier or more difficult than ________ (your current way of accessing that information)? Why? 

We agreed this should be left as-is, and will be handled as needed based on what has already come up in the interview.

> Since the interviews are at this point only 45 minutes long, I could add a 10 minute evaluative portion to the end, where we look at the military info section together and talk about it. Would that feel satisfactory to you? Let me know.

We agreed a short, <10 minute section at the end to look at the profile and ask some questions would be worthwhile.

Thanks, Florence!!
