### ISSUE TITLE
[Research] Military info discovery: Write research plan

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#51821]
### Background

[Research outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/military-information/discovery-and-research/2023-military-info-discovery/README.md#research-outline-expanding-the-military-information-section-of-the-vagov-profile)

[Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/military-information/discovery-and-research/2023-military-info-discovery/research-plan.md)

Currently, we have a very brief section of the profile dedicated to military info, but we've never really talked to users about it and assessed whether it meets their needs and expectations, or how we could improve it. We've never even asked them if the profile is where they'd expect to find military information. We have a lot to learn.

## Tasks
- [x] Get research plan template
- [x] Discuss any questions about drafting a research plan with Liz
- [x] Draft research plan
- [x] Have Liz review
- [x] Incorporate edits
- [x] Have Samara review
- [x] Incorporate edits
  

## Acceptance Criteria
- [ ] Plan complete and ready for submission

--------

### Associated tickets

- #51818
- #51821
- #52010
- #51822
- #51886
- #51887
- #51888
- #51889

**Comment by fmccaf1** [comment]
<img width="762" alt="image" src="https://user-images.githubusercontent.com/106624475/214068578-5e44755d-fbbd-44db-9fcd-bb710fd425be.png">

**Comment by fmccaf1** [comment]
<img width="762" alt="image" src="https://user-images.githubusercontent.com/106624475/214068739-c49b437c-8689-4f69-b0aa-edb0542b4dfb.png">

**Comment by fmccaf1** [comment]
@Samara-Strauss You're up next! Could you take a look at the research plan and let me know any feedback you might have? I included some screenshots from conversation with Liz to this ticket in case you have similar questions.

**Comment by Samara-Strauss** [comment]
I think you're good to go to start on the conversation guide! I'll move it into this sprint. 

### Hypotheses

> Military information often (always?) must be provided when Veterans apply for various VA benefits. This product could play a helpful role in the benefit application process.

This is something you can probably answer in your own discovery -- how many of the applications on VA.gov require a DD214 to be uploaded/added to the application?

### Methodology

> Semi-structured interviews that help us to understand what Veterans need from this product without asking them directly about the product and what they'd expect the product to show or look like.

Personally, I think it's OK to show them the profile section and have a conversation about it. I see your conversation and rationale with Liz above, but I still think it's OK to use this as part of a structured interview. Even if people ask for 50 new fields, that doesn't mean we'll necessarily add them. I trust us to do the product thinking after these calls to determine what is essential and what is not.

### Recruitment criteria

We can go with what you have, but just a heads-up that sometimes we do need to loosen our desired criteria based on who Perigean can find. Let's see how they do with what you've proposed, and then we can adjust if necessary.

**Comment by Samara-Strauss** [comment]
One more thing I was just thinking about -- we should gather information on where people expect to find their military history info online. Is it even in the profile? What would they expect to see/happen on VA.gov? This is important both for this and broader IA/nav considerations we'll be exploring throughout the year.

**Comment by fmccaf1** [comment]
@Samara-Strauss Thanks for the feedback! Are you saying that you think the best route would be to show the profile as part of the interviews?

**Comment by Samara-Strauss** [comment]
I'm saying I think you can show the profile without harming your research findings. In your chat with Liz above, it seemed like you felt that showing this section would be too much of a primer for folks, and they might start asking for a bunch of things they don't really need. I don't think you need to show the profile immediately -- you can certainly have a conversation before/if you do -- but I was just saying that I don't think this will overly prime people or cause too much bias. But I won't mandate whether you show the profile or not. Final decision is up to you.

**Comment by Samara-Strauss** [comment]
@fmccaf1 can we close this out? You can close this before you submit the plan since the actual submission is part of #51886.

**Comment by fmccaf1** [comment]
Almost, @Samara-Strauss There's one last thing I've noted for myself to close it out, which is to confirm a test participant for a mock interview.

**Comment by Samara-Strauss** [comment]
Got it! Thanks for letting me know :)
