### ISSUE TITLE
BE | Profile | Personal Information | Update Docs for Preferred Name and Gender Identity

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#51842]
## Background
There are some limitations imposed on users when managing preferred name and gender identity. For example, users can add a preferred name and update preferred name, but they cannot delete it, and gender identity does not accept custom values.

Update the documentation to explain how these reasons influenced the current behavior of the system.

## Tasks
- [ ] Update preferred name documentation
- [ ] Update gender-identity documentation
  

## Acceptance Criteria
- [ ] Review with team

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by tpharrison** [comment]
Duplicate

**Comment by mtcA6** [comment]
@tpharrison should this be linked to [EPIC | Profile | Backend | API Improvements #54241](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54241) is this a swagger doc update? 

Should we break this into two tickets? Preferred Name is in production but Gender Identity is not and we can put the gender identity items in the icebox?
