### ISSUE TITLE
Change all life insurance PDF form links to form landing pages

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#51850]
## Issue Description
Our life insurance pages have PDF form links that we can now update to form landing pages. Many of these links may be broken, so we should update asap.

We need to:
- Check all form links on all pages in the life insurance section
- Replace PDF links with form landing page links — either from the VA forms library or from this list of life insurance forms: https://www.benefits.va.gov/INSURANCE/resources-forms.asp
- Update link text to "Get XYZ form to download
- Ask Steve Fital for any replacement links we can't find ourselves

Also noting for Megan: We'll be making more changes to the life insurance pages soon, so no need to spend a lot of time on style updates. If you see small things you want to change that's great, but the goal here is to fix broken links as quickly as possible.

---
## Tasks
- [ ] Check all life insurance form links and replace as needed 
- [ ] Copyedit/prepub (Megan)
- [ ] Publish (Megan)

## Acceptance Criteria
- [ ] All form links in life insurance section work and go to form landing pages instead of PDFs

**Comment by laurwill** [comment]
Hi @megzehn ,
Here are the updated pages, ready for you to copyedit just the link changes and publish: 
- FSGLI: Changed link for form 8700: http://preview-prod.vfs.va.gov/preview?nodeId=765 
- TSGLI: Changed download link text for consistency: http://preview-prod.vfs.va.gov/preview?nodeId=768 
- VLGI: Changed links for forms 8714, 8721, 8284: http://preview-prod.vfs.va.gov/preview?nodeId=769
- Totally disabled: Changed download link text to indicate landing page instead of pdf: http://preview-prod.vfs.va.gov/preview?nodeId=771

**Comment by megzehn** [comment]
Thanks for making those changes, @laurwill! Confirming that these have been reviewed and published.

**Comment by laurwill** [comment]
Thanks @megzehn ! Steve just approved the info alert and said he would update the form link on the SGLI form landing page — so you can publish the updated SGLI page now: http://preview-prod.vfs.va.gov/preview?nodeId=767 

Then we can close this out.

**Comment by megzehn** [comment]
Thanks, @laurwill! [SGLI is now published.](http://preview-prod.vfs.va.gov/preview?nodeId=767) @RLHecht we can close this one.

**Comment by RLHecht** [comment]
Confirmed these are live. Closing!
