### ISSUE TITLE
[FE] [PRE-CHECKIN] Update canceled appointment behavior & messaging

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#51862]
## Background

We [learned yesterday](https://dsva.slack.com/archives/C02UP02HHGX/p1673458292082829) that patient appointments are often canceled and rebooked at the same time rather than being edited. At this time, those appointments will all be put in LoROTA for a given pre-checkin UUID. Since we currently show the "appointment canceled" messaging if any appointment in the list is canceled, Veterans sometimes see that message when they actually have a valid appointment at that time.

## Changes

1. Only show the "Your appointment is canceled" messaging if _all_ appointments in LoROTA are canceled. (current `appointment-canceled` error case)
2. If one but not all appointments are canceled, show the [generic error page](https://app.abstract.com/projects/d9d1d6b4-192b-4ee6-95ab-e7cf42a1ac03/branches/main/commits/d90db68c5faaa10cdf19883c3ce1abaf18c7c359/files/db5cbb64-bed3-48f8-9512-2e2eef457dd1/layers/DDD7A7F4-887E-4141-892A-49AD380E345A?collectionId=336838b5-e55e-4aeb-9b4f-6d26bd66c110&collectionLayerId=6e6d1582-8dd0-4a1b-b7f8-a25f0d72ba80&mode=design&sha=d90db68c5faaa10cdf19883c3ce1abaf18c7c359)

![Screenshot 2023-01-12 at 10.03.36.png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/17f6e2d5-22dc-4f37-a2cc-3fd542f73dd1)

## Tasks
- [ ] Update mocks & e2e tests with new scenarios
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Canceled appointment message and information is shown only if all appointments are canceled
- [ ] Generic error message is shown if some appointments are canceled
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [x] Read ticket details and verify that ACs are met
- [x] Review code in PR
- [x] Run branch locally
- [x] Check that new and updated translations use new keys
- [x] Check for hardcoded strings

**Comment by benbrasso-agile6** [comment]
lgtm

**Comment by acrollet** [comment]
@brianseek @wullaski let's talk about maybe pulling this in at our sync today.

**Comment by sarahknoppA6** [comment]
@wullaski to reverify and close

**Comment by wullaski** [comment]
@sarahknoppA6, @acrollet, I'm not sure of a way to validate this on staging or prod but highly confident(famous last words) that the functionality will work based on the cypress tests using mock data.
