### ISSUE TITLE
Analyze data retrieved from IAM

### ISSUE THREAD

**Issue by elizabethkochBT** [department-of-veterans-affairs/va.gov-team#51860]
## Issue Description
The login.gov adoption team, stakeholders, and VA leadership don't have data surrounding counts of users currently logging in with DSLogon CSP. We need to gather data to provide a baseline of DS Logon credentials and analyze CSP counts and CSP methods to identify Veterans who will need to migrate from DSLogon.
IAM Data of User accounts SR-3634

## User Story
As a Product Owner
I want to know the total user counts by CSP accessing the va.gov ecosystem
So that we have a baseline of account totals to target for migration/grandfathering.

---
## Tasks
- [x] Analyze data retrieved from IAM &Reconcile discrepancies in baseline data
- [x] Work with Joe on authentication numbers to resolve VA data & IAM data 
- [x] Double check interpretation of [ID.M](http://id.me/)E accounts (not shell/MFA-only) via IAM team
- [x] # of identities: ask Joe whether we can get it on time, and what view it will be in 
- [x] Proofing evidence for premium users with overlap: Get list of SEC IDs, highlight ~300k with overlapping, send to MHV
- [x] Meet with IAM re: missing email data (from original service request). Get all for DSL & MHV. (Or Damian can pull via Tookit, if it's a small number.)Then analyze this new data. 
- [ ] Request Toolkit access

## Acceptance Criteria
- [x] Create a report of CSP counts and accepted baseline data.
---

**Comment by sdickson-gt** [comment]
1. Working with MHV and IAM/Danny to reconcile MHV total accounts.
2. Reviewed the authentication data with Joe N.  Didn't dive into specifics but it is expected to vary from VA.gov.  The IAM "IDME_" prefix in IAM Authentication reports is only coming from VA.gov so we can correlate those numbers to validate.  The "IDME" prefix in IAM is based on authentications from multiple application sources, where VA.gov is roughly 55%.
3. Revisiting the IAM data to identify the IDME MFA authentications, and updated counts accordingly.
4. Core team has implemented change to start tracking IDME vs IDME MFA in counts for total authentications and total identities.  The total identity counts start as of 1/1/2022
5. Have requested from MHV the proofing data for the overlapping "elibigible" DSL and MHV accounts.
6. Have requested emails associated with IAM data and Danny acknowledged.

Report of counts are updated on google drive.
