### ISSUE TITLE
VAMC template handling for null wait time data

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#5188]
## User Story:
As a Veteran, I need accurate wait time information so that I can make decisions about where to receive care.

**Current behavior:**
If wait time data is available for Existing Patients, but not for New Patients, then only the content block for Existing Patients is displayed. Likewise, for the reverse. 

**New additional expected behavior:**
If data is not available for either Existing or New, the entire content block should not display. 

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] First thing we need to do - x hour(s) - Owner
- [ ] Second thing we need to do - y hour(s) - Owner
- [ ] Third thing we need to do - z hour(s) - Owner
- [ ] etc

## Acceptance Criteria:
[ ] If wait time data is available for Existing Patients, but not for New Patients, then only the content block for Existing Patients is displayed. 
[ ] If wait time data is available for New Patients, but not for Existing Patients, then only the content block for New Patients is displayed. 
[ ] If data is not available for either Existing or New, the entire content block should not display. 

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
