### ISSUE TITLE
[Research] Military info discovery: Write conversation guide

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#51882]
### Background

[Research outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/military-information/discovery-and-research/2023-military-info-discovery/README.md#research-outline-expanding-the-military-information-section-of-the-vagov-profile)

Currently, we have a very brief section of the profile dedicated to military info, but we've never really talked to users about it and assessed whether it meets their needs and expectations, or how we could improve it. We've never even asked them if the profile is where they'd expect to find military information. We have a lot to learn.

## Tasks
- [ ] Submit research plan
- [ ] Meet with Perigean to discuss recruitment criteria
- [ ] Confirm recruiting has been kicked off
- [ ] Create observer Mural board
- [ ] Schedule debrief sessions w/ team
  
## Acceptance Criteria
- [ ] All tasks are complete
