### ISSUE TITLE
[Research] Military info discovery: Research synthesis

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#51889]
## Background

[Research outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/military-information/discovery-and-research/2023-military-info-discovery/README.md#research-outline-expanding-the-military-information-section-of-the-vagov-profile)

[Findings summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/military-information/discovery-and-research/2023-military-info-discovery/findings-summary.md)

Currently, we have a very brief section of the profile dedicated to military info, but we've never really talked to users about it and assessed whether it meets their needs and expectations, or how we could improve it. We've never even asked them if the profile is where they'd expect to find military information. We have a lot to learn.

## Tasks
- [x] Draft final synthesis
- [x] Review with PO and incorporate edits
- [x] Publish final report
  
## Acceptance Criteria
- [x] Final report published

--------

### Associated tickets

- #51818
- #51821
- #52010
- #51822
- #51886
- #51887
- #51888
- #51889

**Comment by BerniXiongA6** [comment]
Hi @fmccaf1 -- we'll carry this over to Sprint 5 -- thanks!

**Comment by fmccaf1** [comment]
The long awaited [draft for findings summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/military-information/discovery-and-research/2023-military-info-discovery/findings-summary.md) is now ready for review. Thanks @andaleliz @aagosto90 for reviewing/providing any feedback when you have time (though I am hoping to close this ticket out at end of sprint).

**Comment by Samara-Strauss** [comment]
@fmccaf1 this is absolutely outstanding. Seriously. You really went above and beyond.

This is a very small request. For quotes, can you use the quote markdown? It's the `>` symbol with a space before a line of text.

I need time to digest this before thinking about next steps, but thank you again for being so thorough and doing some seriously great research.

**Comment by Samara-Strauss** [comment]
@fmccaf1 -- I had a chance to re-read your report with fresh eyes this morning, and I did some thinking around next steps. [I fully outlined my thinking here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/military-information/product/next-steps-after-2023-research.md) if it's helpful, but this is the TL;DR of that doc:

- The big question right now is what *should* we do vs. what *could* we do? This is that place where we combine design and product thinking into a path forward.
- Based on the level of need/usage on VA.gov compared with other tasks, I think we can put immediate next steps on hold for now. However, I don't think we should leave this alone forever, plus I've already had other teams ask me about expanding this section.
- Things I'm interested in doing:
  - Elevating military info in some way to see if it gets more traction (exact approach TBD)
  - Adding one or two pieces of info to the military info section
  - No matter what we do, we should try to do these as quick, "easy" experiments  to see if we move any metrics. Based on the outcome, it may or may not support further work.
- Re: adding the DD214 to the profile -- I wish we could, but this starts to get into organizational stuff outside of our control. DoD owns the DD214, and I don't even know if they have digital copies, or if they only mail people copies. Broadly speaking, I know we'd love to have access to this, but it would be a much bigger effort than our team.

Let me know if you have thoughts. I'm also happy to meet to discuss, but wanted to get you my thoughts asap.

**Comment by fmccaf1** [comment]
Thanks for your thoughts @Samara-Strauss! 

It was interesting in the research to hear participants talk about getting access to digital/downloadable versions of their 214 on eBenefits. The reason why I included that as a suggestion is: if the 214 is available to some through eBenefits, it'd be nice to continue offering that when eBenefits goes away. Even if we can't do this in the short term, it's nice to have as a longterm goal for the military information section since it does seem like it'd provide the most value to veterans (or at least to those participants I spoke to). 

Also, to be clear, I think we should add discharge status to the profile, at a minimum as an opportunity to help veterans understand what their discharge status means and how to change it. I'd be curious about your thoughts on this. 

Let's keep talking! :)

**Comment by andaleliz** [comment]
@fmccaf1 sorry for the delay in providing any feedback, but I just finished and wanted to echo Samara's kudos - this is excellent! Interesting findings, and solid recommendations. It's thought provoking wrt to military information, but also the research process and writing up a findings doc. 
- I found it helpful that you included the specific number of participants for the majority of the points throughout the doc
- I noticed that you used "I" instead of "we" which makes me wonder where I picked up that habit 😆 and if I should just be using "I" instead of making it sound like a group worked on something
- I'm conflicted about the recommendation to include people with memory issues from generative research. You raise a good point about the humanity of it, but the idea of excluding a particular group makes me pause.  I wonder if instead there might be a different way to approach/phrase generative research questions with this group so their experience can still be included. Maybe not. I'll be noodling on that for sure.

**Two side notes:**
- There was a typo and formatting thing I found so I just fixed them while I was in the doc
- I really like that one quote from the participant talking about how they had their veteran status added to their drivers license, and it made it easy to show when celebrating Veterans day. That was smart, and it made me happy.

**And finally, in response to @Samara-Strauss:** 

You said 
>I've already had other teams ask me about expanding this section.

Are their requests/asks documented anywhere? I'd be curious to know what other teams are looking for. Apologies if I've missed this somewhere along the way

>Re: adding the DD214 to the profile -- I wish we could, but this starts to get into organizational stuff outside of our control. DoD owns the DD214, and I don't even know if they have digital copies, or if they only mail people copies. Broadly speaking, I know we'd love to have access to this, but it would be a much bigger effort than our team.

This would totally be an MVP (bandaid?) solution, but one idea could be to allow Veterans to scan/upload their copy and store it in their profile, so they at least have a consistent place online they can access it.  Kind of like a DD214 cloud storage in the profile.

**Comment by fmccaf1** [comment]
I love that bandaid solution idea for the 214, @andaleliz.

And yes, I was really curious to hear your thoughts on that recommendation re: including/excluding people with memory issues on generative research. With the two individuals who expressed having trouble remembering things, I just felt bad asking them over and over to remember things! But would love to not exclude people from research, especially since this seems like a relatively common issue among Veterans (and their POVs and experiences matter). Let's both keep thinking and talking about this.

Thanks for reviewing this, for your notes/feedback and for fixing the typo and formatting issues!

**Comment by Samara-Strauss** [comment]
@fmccaf1 @andaleliz 

> It was interesting in the research to hear participants talk about getting access to digital/downloadable versions of their 214 on eBenefits.

I'm not able to log into eBenefits right now (I'm worried our one path to eBenefits may no longer work), but I'm skeptical people were actually able to download the DD214 from there. I'm 100% sure we would have already ported that functionality to VA.gov if it were accessible. Unfortunately, since I can't get into eBenefits, I'm not exactly sure what functionality is available.

> Are their requests/asks documented anywhere? I'd be curious to know what other teams are looking for. Apologies if I've missed this somewhere along the way

Re: other teams asking me about military info -- no, I haven't documented these discussions anywhere, but there have also been no formal requests. Noted, though, that we don't have a good intake process, and that makes it hard for anyone else but me to get visibility into what other teams have asked for (even if a lot of those things end up going nowhere for various reasons).

> This would totally be an MVP (bandaid?) solution, but one idea could be to allow Veterans to scan/upload their copy and store it in their profile, so they at least have a consistent place online they can access it. Kind of like a DD214 cloud storage in the profile.

This starts to get into larger discussions around eFolders and where veterans could potentially store documents on VA.gov. I think there's always been interest in creating a space like this on the site, but never the people to fully investigate, implement, and maintain the work. I agree, though, that it would be ideal if people could upload a copy of this and other documents on VA.gov for easy access.

**Comment by Samara-Strauss** [comment]
Following up on this, as I was finally able to get into staging eBenefits via the VA network. I've confirmed that you can not download your DD214 on eBenefits. While there is a CTA...

![image](https://user-images.githubusercontent.com/34068740/226353412-8811d819-e07e-49a6-b36a-492519de555b.png)

It sends you to milConnect, which is what VA.gov does (unfortunately, I can't view milConnect, hence the error):

![image](https://user-images.githubusercontent.com/34068740/226353539-130900ef-d26c-474c-99ac-8968edb398f7.png)

**Comment by fmccaf1** [comment]
One participant walked me through this flow as part of an interview and she seemed to think this was something that had changed (the redirect). For me, the CTA is evidence that at least at one time Veterans could download their DD214.
