### ISSUE TITLE
Supplemental Claims | Accept submissions without evidence

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#51891]
## Value Statement
**_As a_** Veteran
**_I want to_** submit my claim without evidence
**_So that_** I can quickly begin the review process without the burden of providing evidence. 

---
## Background Context
Due to the PACT Act, the VBA has changed it's process for reviewing all supplemental claims. As of January 1, 2023, claimants may submit supplemental claims without providing evidence. Claims processors will manually review all claims, regardless of PACT eligibility, to determine if evidence is needed. If so, they will reach out to the claimant directly for more information. 

The scope of this ticket is backend changes to the current endpoint. 

## Acceptance Criteria
- [ ] User may submit their claim without evidence
- [ ] User receives a notice for unsuccessful submissions
- [ ] Unit tests complete (90% coverage)
- [ ] E2E tests complete
- [ ] Accessibility testing complete
- [ ] Reviewed and approved by product and/or design

## Designs and Build Notes
- [Design (NOT APPROVED)](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/a/agLe8Aq)
- [COPY](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/sourceofcontenttruth.md#pact-act-copy-changes)

## Tasks
- [ ] Update endpoint to accept submissions without evidence
- [ ] Test load handling to determine evidence threshold 

## Definition of Ready
- [ ] _Clear value description_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
@Mottie @saderagsdale 
- Updated the design link to the final (copy approved with exception of legal) versions of the screens.
- Linked directly to the section where the content currently lives in Content doc (everything is on the bottom of that markdown).

**Comment by Mottie** [comment]
Updates have been merged in. They may not be available in staging for a bit. Also, the form will show an error on the review & submit page if you try to submit a form with no evidence for now; until the backend has been updated

**Comment by saderagsdale** [comment]
@kylesoskin @Mottie is this one in Validate waiting for something from LH, or just here until it's tested?

**Comment by Mottie** [comment]
We are [waiting for this Lighthouse PR to get merged](https://github.com/department-of-veterans-affairs/vets-json-schema/pull/745)

**Comment by Mottie** [comment]
The PR was merged! I'm not sure how long we need to wait before the backend starts checking the updated schema. Maybe just an hour.

**Comment by Mottie** [comment]
Ready for testing in staging!

**Comment by saderagsdale** [comment]
@saderagsdale @eileen-coforma test and close

**Comment by saderagsdale** [comment]
@Mottie I couldn't actually submit in staging. The form let me pass and notified me that I didn't upload evidence, but the submission failed, saying "Your decision review request didn’t go through
We’re sorry. We’re working to fix the problem, but it may take us a while. Please try again tomorrow."

Is this just a staging thing I can skip?

**Comment by kylesoskin** [comment]
The issue was with the length of one of the fields
```
[10:12](https://adhoc.slack.com/archives/D03RVBZM9LK/p1677683578142439)
{\"title\":\"Invalid length\",\"detail\":\"'Degenerative arthritis - 20% - Service connection for Degenerative arthritis is granted with an evaluation of 20 percent effective November 3, 2019.' did not fit within the defined length limits\",\"code\":\"142\",\"source\":{\"pointer\":\"/included/0/attributes/issue\"},\"status\":\"422\",\"meta\":{\"max_length\":140,\"min_length\":1}}]},
```

```
  "included": [
    {
      "type": "contestableIssue",
      "attributes": {
        "issue": "Degenerative arthritis - 20% - Service connection for Degenerative arthritis is granted with an evaluation of 20 percent effective November 3, 2019.", <- this ....
        "decisionDate": "2022-03-02",
        "ratingIssueReferenceId": "142953"
      }
    }
  ],
  ```


@Mottie will add truncation or enforce char limits where applicable in the frontend to confirm to the schema requirements on this page: https://developer.va.gov/explore/appeals/docs/decision_reviews?version=current

**Comment by saderagsdale** [comment]
@eileen-coforma @Mottie any concerns with closing this one?

**Comment by Mottie** [comment]
No concerns from me
