### ISSUE TITLE
[Research] Military info discovery: Support Florence 

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#51897]
## Background

[Research outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/military-information/discovery-and-research/2023-military-info-discovery/README.md#research-outline-expanding-the-military-information-section-of-the-vagov-profile)

Currently, we have a very brief section of the profile dedicated to military info, but we've never really talked to users about it and assessed whether it meets their needs and expectations, or how we could improve it. We've never even asked them if the profile is where they'd expect to find military information. We have a lot to learn.

Florence is going to run this study, but given that it's her first, she'll likely need some light-touch help throughout. This ticket is to capture any help you might need to give Florence through the first sprint of this research (sprint 2, 1.18 - 1.31). In this first sprint, Florence will be familiarizing herself with the military information space, creating a research plan, and creating a convo guide as a stretch goal.

## Tasks

- [x] Go over research protocol with Florence
- [x] Make sure Florence has research templates 
- [ ] Offer support as needed

--------

### Associated tickets

- #51818
- #51821
- #52010
- #51822
- #51886
- #51887
- #51888
- #51889

**Comment by andaleliz** [comment]
@fmccaf1 is there anything else I can help you with before you start running sessions? I feel like now that recruiting has kicked off, we can close this ticket. I can continue to support you as an observer in research (and back up moderator when I return from PR) as any teammate would :)

**Comment by fmccaf1** [comment]
I think you're right that you can close the ticket. Thanks for all your support!

**Comment by andaleliz** [comment]
You're welcome! Happy to help :)
