### ISSUE TITLE
Add step for communicating published Staging Review tickets

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#51901]
## User Story
As a Governance team member, I want to be made aware of the documented/published Staging Review tickets prior to the Staging Review meeting so that I can familiarize myself with the github ticket number for smoother presentation during the meeting

Assignee: @briandeconinck 
Peer Reviewer: @it-harrison 

## Description
At the 1/12 Staging Review, @shiragoodman notified the team post bulk-upload of the quantity of issue tickets, including how many were launch-blocking. She asked the Governance team to familiarize themselves with the tickets so it would be easy to present at Staging Review, since typically only 1 person screen shares. This was a huge improvement to the flow and cadence of the meeting. Significantly less time was spent looking for the ticket being discussed.

The purpose of this ticket is to add a step to the Generate Issue tickets section of the Moderator Responsibilities for Staging Review for the team PM (or whoever is generating the ticket) to notify the team when the tickets are created and tag the team members who created the `launch-blocking `tickets, if applicable. 

## Impacted Artifacts
- [Staging Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review+-+Moderator+Responsibilities)

## Tasks
- [x] Update the Staging Review - Moderator Responsibilities to add a step to notify the team when the tickets are created
   - [New Step 10 in the "Generate issue tickets" section](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review+-+Moderator+Responsibilities#Step-10)

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team members are notified pre-Staging Review of the generated issue tickets and asked to familiarize themselves with them
- [x] Governance team members are notified pre-Staging Review of the  launch-blocking issue tickets 

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
@it-harrison This is ready for review! I've added a new [Step 10 to the "Generate issue tickets" section](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review+-+Moderator+Responsibilities#Step-10) of the Staging Review Moderator Responsibilities. Feel free to comment or to make edits directly if anything is unclear.

Thanks!

**Comment by it-harrison** [comment]
Hi @briandeconinck  everything looks good!

**Comment by briandeconinck** [comment]
Thanks Ian! Closing as completed.

**Comment by shiragoodman** [comment]
@briandeconinck assuming you meant to close this?

**Comment by briandeconinck** [comment]
I sure did! Apparently I clicked the wrong button? Actually closing now.
