### ISSUE TITLE
EPIC | Profile | Direct Deposit C&P Migration from EVSS to Lighthouse

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#51900]
> [!Note] 
> Open Items migrated to [76474](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76474)

## Background
The VA.gov Profile currently uses Enterprise Veterans Self Service (EVSS) to manage direct deposit information for comp & pen.  Support for direct deposit for comp & pen has been moved from EVSS to the Lighthouse platform.

The following vets-api endpoints (and supporting services) will be replaced:
  - GET `/v0/ppiu/payment_information`
  - PUT `/v0/ppiu/payment_information`

This Direct Deposit Management API offers functionality to:
- Return, create, or update direct deposit banking information for disability and pension compensation
- Support payments to Veterans, spouses, and other beneficiaries
- Determine eligibility for direct deposit management including detection of payments
- Validate routing information
- Auto-populate payment info into the online 526 claim process

This API does not perform the following direct deposit tasks:
- Set up direct deposit for VA travel pay reimbursement.
- Change direct deposit information for education benefits.

## Contacts, Channels, and Documentation
**Lighthouse Contacts:**
- [Nichole Harris](https://dsva.slack.com/team/U01KHNYLNR5) (Product Manager - Lighthouse VA APIs)
- [David Lennon](https://dsva.slack.com/team/USANRG2Q6) (Technical Lead)

**Slack Channels:**
- [#api-direct-deposit-management](https://dsva.slack.com/archives/C03P6C3FYMR)

**Supporting Documentation:**
- [Project Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit/evss-lighthouse-migration#readme)
- [Discovery Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/51103)
- [Direct Deposit: Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/products/identity-personalization/direct-deposit)
- [Direct Deposit Management API](https://developer.va.gov/explore/benefits/docs/direct-deposit-management?version=current)
- [Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/evss-lighthouse-migration/direct-deposit-release-plan.md)
- [Testing spreadsheet](https://docs.google.com/spreadsheets/d/1xflLNJhUSVslzLbVQtMkYkzsBGAhIccnmYW0GL_Ihd0/edit#gid=0)
- [Privacy,Security,and Infrastructure Review Prep](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/direct_deposit/lighthouse/psir_prep.md)
- - [Privacy,Security,and Infrastructure Review ticket ](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1059)
- [UAT findings](https://github.com/department-of-veterans-affairs/va.gov-team/issues/51900#issue-1531263040)
- [Data Dog Dashboard ](https://vagov.ddog-gov.com/dashboard/gra-npe-h52/authenticated-experience-cp-direct-deposit?refresh_mode=sliding&from_ts=1695131443208&to_ts=1695736243208&live=true)

## Scope of Work
**Estimates** _(does not include QA/UAT testing_)**:**
- Total Points:  ~ 36 points
- Total Sprints: ~ 4 sprints
- Total Weeks: ~ 8 weeks

<details>
<summary>Completed Work</summary>

**Backend Development:** 
| Ticket | Description | Estimate | Status |
| ------ | ------------ | ------ | ------ |
| [51956: Sandbox access and configuration](https://github.com/department-of-veterans-affairs/va.gov-team/issues/51956) |  OAuth 2.0 Client Credentials Grant is used to access the API in the sandbox environment.  This has been configured but not tested.   | 3  |  Done  |  
| [51976: Build Client Authentication](https://github.com/department-of-veterans-affairs/va.gov-team/issues/51976) | In order for the vets-api to communicate with the Lighthouse API, client authentication mechanisms need to in place.  | 5  | Done |  
| [Migrate GET Direct Deposit Info](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52500) | Add functionality to retrieve direct deposit information from the Lighthouse API.  This includes configuration, specs, attribute mapping, error handling, and logging. | 5 | Done |  
| [Migrate POST Direct Deposit Info](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53714) | Add functionality to add/update direct deposit information from the Lighthouse API.  This includes configuration, specs, attribute mapping, error handling, and logging.  | 5 | Done |  
| [Create Comp and Pen Controller](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54051) | This controller will replace the PPIU controller.  This includes specs, error handling, and swagger docs  | 3  |  Done  |  
| [Configure and Test Staging access](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54054) | Configure staging access for the vets-api. | 3 | Done |  
| [Update BE Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54762) | Update BE documentation.  | 3 | Done |  

**Cross-team Team Coordination:**
| Ticket | Description | Estimate | Status |
| ------ | ------------ | ------ | ------ |
| [Review changes with Mobile App Team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54763) | Andrew Herzberg reached out and stated that his team is migrating to the Letters API.  We are going to identify any common services (authentication, error handling, logging, etc.) that can be shared by both teams.  This should help reduce code duplication and the total effort across teams.  | 2 | Done |
| [51978: Review existing code with Benefits Team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/51978) | Identify any common services that have already been built that our team can leverage. | 2 | Done |

_Note: The My-Education Benefits team retrieves education direct deposit information for one of their forms so it can be submitted for claims processing. Changes related to this epic are for C&P only and should not affect their team, but I will follow up with Bradley Bergerson just to be sure._

**Front End Integration and Testing:**
| Ticket | Description | Estimate | Status |
| ------ | ------------ | ------ | ------ |
| [Vets-API Review with FE](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54769) | Review changes with FE engineer (Adam Whitlock).  We have already discussed the basics, but we will review the final changes.  | 2  |  Done |  
| [Integration Testing between FE and BE (Staging)] | Identify staging users and coordinate testing between FE and BE; this does not include QA or UAT. This work was done over several tickets and completed prior to sprint 13 | 4  | Completed |  

**Pre-Production**
| Ticket | Description | Estimate | Status |
| ------ | ------------ | ------ | ------ |
| [Increase Rate Limit](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55294) | Request an increase to the current rate limit imposed on the Lighthouse DD API (60 requests per minute). <per the ticket/investigation we're well under the number of requests and at this time it doesn't make sense to proceed w this request | 2 | Done/Rejected | 

_Note:  There are always small changes that need to be made at this point in the process so additional tickets may be opened to address any outstanding changes/issues._
```[tasklist]
### Integration Work (finishing sprint 12ish)
- [ ] #54893
- [ ] #59910
- [ ] #54896
```

**6/16/2023**
Tom discussed with the Benefits Debt Resolution team their experience in production w/their Lighthouse endpoint migration, as a result we've added the following items to work through ideally in sprint13  - (60481, 60477, 60478, 60483) 
```[tasklist]
### Prod prep
- [x] **Sprint 13: 6/21-7/4**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/60481
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/60477
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/60478
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/60483
- [ ] #60694
- [ ] #54870
```

```[tasklist]
### QA
- [x] **Sprint 14: 7/5-7/18** - QA Testing:
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/60939
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/61252
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/61800
- [x] **Sprint 15: 7/19-8/1** - QA Fixes and privacy review:
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/54771
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/60945
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1059
```

```[tasklist]
### UAT
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/54999
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/55000
- [x] **Sprint 15: 7/19-8/1** - UAT Prep and initiatiion :
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/60942
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/61199
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62512
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/61165
- [ ] https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/349
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/61177
- [x] **Sprint 16: 8/2-8/15** - Finish UAT, Initiate Release:
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/61170
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/63029
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62626
```

```[tasklist]
### Release
- [x] **Sprint 17: 8/16-8/29** Progress through the launch
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/63616
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/63323
- [x] **Sprint 18: 8/30-9/12** Continue Release/Resolve Launching Errors
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/64364
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/64875
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65067
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/64981
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/64360
- [x] **Sprint 19: 9/13-26** Continue Release
- [x] **Sprint 20: 9/27-10/10** Continue Release and Bug Remediation
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/60782
- [x] **Sprint 21:**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65502
```

</details> 

```[tasklist]
### Blocked
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/63717
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/66315
```

```[tasklist]
### Post Launch
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/63633
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62628
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/63256
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/69602
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/71150
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/72306
```

**Comment by tpharrison** [comment]
@Samara-Strauss @bernixionga6
This is the epic I created for our DD migration sync meeting tomorrow.

**Comment by Samara-Strauss** [comment]
Thank you, @tpharrison! Looking forward to discussing tomorrow.

**Comment by Samara-Strauss** [comment]
Looks like @BerniXiongA6 has officially been added to our repo, so she should be able to help with ticket creation at this point!

**Comment by tpharrison** [comment]
I'm having issue with updating records in the Sandbox environment.  Updates are returning with a status code of `200`, but the record isn't updated with the changes.

Reached out to David Lennon explaining the issue and I'm waiting to hear back.

**Comment by Samara-Strauss** [comment]
Thanks, @tpharrison. I've added #55294 to this sprint. I also have a couple questions:

1. Is there anything we can help with?
2. Are you still feeling like the work slated for this sprint is manageable? Should we push anything back or adjust timelines?

**Comment by tpharrison** [comment]
@Samara-Strauss 

#55294 can be moved to sprint 8.

I think the work slated for this sprint is ok from an effort standpoint.  My concern is around little delays that keep popping up.  For example, right now, I'm waiting on...
- Review/approval of my PR for staging configuration (its been over 24 hrs)
- Review/approval of my latest PR for vets-api changes (its been over 24 hrs).  There has been a problem with the deployment that is holding up all PRs.
- Sandbox/Staging data needs to be updated so we can test more use cases (I only made the request a few hrs ago)

If all goes well with the above, then I'm ok, but if there are any issues, then it may cause delays since I'll have to re-submit the PRs and get them reviewed/approved again.

I think my biggest concern at this point is staging data.  Do you have a few minutes to meet tomorrow to discuss this?

**Comment by Samara-Strauss** [comment]
> #55294 can be moved to sprint 8.

Noted, and added to sprint 8!

> If all goes well with the above, then I'm ok, but if there are any issues, then it may cause delays since I'll have to re-submit the PRs and get them reviewed/approved again.

Noted, and just keep us posted.

> I think my biggest concern at this point is staging data. Do you have a few minutes to meet tomorrow to discuss this? I can also give you an update from the Lighthouse meeting.

Yes. Are you available some time between 11:30 - 3:00?

**Comment by tpharrison** [comment]
I'm available between 11:30 - 2:00 ET.

**Comment by Samara-Strauss** [comment]
Call added for 11:30 tomorrow!

**Comment by BerniXiongA6** [comment]
Sorry I missed the comments till now with my meeting heavy schedule today. @Samara-Strauss could you add me to the  call w/ @tpharrison so I can be a fly on the wall?

**Comment by tpharrison** [comment]
@BerniXiongA6 I just added you to the call.

**Comment by Samara-Strauss** [comment]
@BerniXiongA6 sorry, I should have added you originally! I see Tom did. See you at 11:30 ET!
