### ISSUE TITLE
[FE] Profile: Inventory all instances in which we use the "We can't load all the information..." error

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#51902]
## Background

A separate conversation came out of #49651 around the "We can't load all the information in your profile error" and whether it is needed anymore. This error originated when the direct deposit section of the profile showed conditionally, but since it now shows persistently for everyone, it's unlikely we need this error anymore. However, we know there are other instances in which we started using this error, so we need to determine all of the use cases in which this error shows in order to determine if we can eliminate it or need to take additional steps before doing so.

![image](https://user-images.githubusercontent.com/34068740/212170470-91513152-69c4-4381-8ffb-8c892ba6f6af.png)

## Tasks

- [x] Look in the code and determine all instances in which we still use this alert
- [x] Post a list of those instances in this ticket
- [x] Have Liz/Florence review the list to determine whether there are any instances in which this error is still necessary, or in which we'd need a design update (eg. an inline error) in order for us to be able to remove the "We can't load all the information..." error.

## Acceptance criteria

- [ ] Depending on the outcome of the inventory, we are either in a position to remove the error (we'll create another ticket if that's the case) or create tickets to update use cases where we need an inline error or better solution in order to be able to remove the "We can't load all the information..." error.

**Comment by adamwhitlock1** [comment]
I am under the impression that this alert could be removed altogether, but here are the instances where it displays:

- The personal information endpoint fails to load and contains errors (this would be if the api is down for that endpoint in general)
  - This is duplicative as there is a unique alert just for that page that is displayed when an api error is present.
- The full_name data doesn't load and it's api endpoint had error data returned.
  - If this api endpoint fails, then by default the nametag section of the profile will not be shown, so I think this alert doesn't serve much of a purpose really.

@andaleliz or @fmccaf1 what do yall think? Should we just remove this alert altogether since each page has its own respective alert for loading errors anyway?

**Comment by Samara-Strauss** [comment]
@adamwhitlock1 my vote is to remove the alert altogether since it's duplicative in one place and the nametag is designed to fail gracefully and not need error messages. If everyone agrees, we can get a ticket for removal into the backlog.

**Comment by andaleliz** [comment]
🖐️ I vote for removing it altogether

**Comment by Samara-Strauss** [comment]
Per standup, @adamwhitlock1 is going to remove this alert as part of this ticket 🎉

**Comment by Samara-Strauss** [comment]
@adamwhitlock1 -- did this update go out??

**Comment by adamwhitlock1** [comment]
Yes, sorry I meant to ping you @Samara-Strauss and @BerniXiongA6, but I have been so deep in the build CI pipeline issues that I had forgotten. This should be good to go and ready to validate.

**Comment by Samara-Strauss** [comment]
@adamwhitlock1 is there a way to fudge something in the dev tools so we can validate? Otherwise, I don't know that we can validate since it's caused by a backend issue.

**Comment by adamwhitlock1** [comment]
I think the easiest way to test this in staging is:

- Log in to a user with LOA3
- Open the chrome developer tools
- Load profile, then open the network tab of the developer tools and right click on the full_name request in the list of requests that have loaded and block that request.

![Screenshot 2023-02-14 at 10 56 35 AM](https://user-images.githubusercontent.com/8332986/218819348-c400cbb1-ca3f-4e7a-b123-2b0f1da8b063.png)

- Reload the profile, and the personal info page should look like this, without the global load error alert present:

![Screenshot 2023-02-14 at 10 59 41 AM](https://user-images.githubusercontent.com/8332986/218819554-fc6bb546-f1b7-4800-be75-cb6bfecf5091.png)

I have validated in staging myself with user 75 in this manner.

**Comment by Samara-Strauss** [comment]
@adamwhitlock1 for some reason, the whole user is blocked when I follow the steps you've outlined above, not just the full name. It's unclear to me what's going on -- I tried in Chrome on both PC and a Mac in case there was an issue with Chrome on PC. Any thoughts?

**Comment by Samara-Strauss** [comment]
Done! Validated with user 80. This is good to go to production!

<img width="533" alt="image" src="https://user-images.githubusercontent.com/34068740/218870070-b8f35c6e-f180-4323-b8bb-e84f4a047510.png">
