### ISSUE TITLE
Profile: Sprint 3 (2.1.23 - 2.14.23)

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#51903]
## Sprint Retro
- [Sprint 2 retro board](https://easyretro.io/board/f4051524-d7be-43a4-8c50-f43d887f3a7f/a8e80c56-a999-4fb3-b38a-eee0797eee30)
## PTO

- **Tom**: 2/6 - 2/10 (Lihan will backfill for Tom in case of emergency)
- **Samara**: 2/10
- **Liz**: 2/13 - 2/17
- **Florence**: 2/9 - 2/13

## Goals

- Accessibility updates
- Direct deposit EVSS > Lighthouse migration
- Notification preferences research
- Military info research

## General

**FE - Adam**

- [x] #51902

## Accessibility

**Design - Florence**

- [x] #52637

**Design - Liz**
- [x] #52064
- [x] #52502

**FE - Adam**
- [x] #49550 - Moved over from last sprint
- [x] #51085 - Moved over from last sprint
- [x] #37041
- [x] #49652

## Direct deposit EVSS > Lighthouse migration
**BE - Tom**
- [x] #51976 - Moved over from last sprint
- [ ] #52500

## Notification preferences
**Design - Liz**
- [x] #51005
- [ ] #51006

## Military info research

**Design - Liz**

- [x] #51897

**Design - Florence**
- [x] #52010 - Moved over from last sprint
- [x] #51886
- [ ] #51887

## Unplanned work

- [ ] #53038
