### ISSUE TITLE
[FE] Address validation flow to save / validate 

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#5191]
## User Story:
As a veteran, I need to have clear address validation so I do not spend a lot of time wondering why my address is not being accepted.

In order to do the above, we have identified a technical debt item that would reduce the risk of a bad validation (and simplify testing)

We currently have two methods to do address validation and likely can have one to reduce testing and complexity.

## Tasks
- [ ] Investigate the two methods and determine whether a single method makes sense and doesn't break anything else.
- [ ] Regression testing - checking where else this is being used.
- [ ] Code up the simplified/consolidated solution

## Acceptance Criteria:
* Address validation still works but with new sexy code

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
