### ISSUE TITLE
[PM, Research] Onsite Notifications v2: Align on notifications spreadsheet

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#51928]
## Background
VA Notify shared an inventory of notification/notification candidates with our team. We would like to discuss it with them and ask questions at our next recurring meeting on 1/24 so we need to review the spreadsheet and align internally ahead of that meeting. 

## Tasks
- [x] [Review notifications spreadsheet individually](https://docs.google.com/spreadsheets/d/1E7JupFC2i6XUzlOxbWwTbIJZ6AxRUz-m/edit#gid=1231731113)
- [x] Add questions/comments to shared [GH notes doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/notifications-v2/product/shared-notes-existing-notifications-to-review.md)
- [x] Discuss with VA Notify partners on 1/27

## Resources
- [Project outline: Scaling onsite notifications](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications/notifications-v2#project-outline-scaling-onsite-notifications-onsite-notifications-v2)
- [ MVP documentation: Backend technical notes](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications#backend)
- [MVP documentation: Frontend technical notes](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications#frontend)

**Comment by Samara-Strauss** [comment]
@ajakabcin @aagosto90 -- [I've added my questions to the Github doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/notifications-v2/product/shared-notes-existing-notifications-to-review.md#samaras-questions). Mostly, my questions are "What is this? Does it link anywhere?", so I am wondering if it would actually be a good use of our time to go into the VANotify self-service platform to investigate some of this ourselves before talking to VANotify. Some of this might be clear just from reading the messages themselves.
