### ISSUE TITLE
[PM] Onsite Notifications v2: Workshop intake process w/VA Notify

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#51927]
## Background
As part of v2 of onsite notifications we need to establish a governance process for how onsite notifications are added to My VA. We need to establish/refine the intake process for notification requests in partnership with VA Notify.

## Tasks
- [x] Schedule working session with PM from VA Notify
- [x] Review existing in-take process
- [x] Refine as needed
- [x] Come to an agreement on process
- [x] Circulate new process (messaging as a work in progress/experiment) in ToTs and via Slack.

## Resources
- [Project outline: Scaling onsite notifications](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications/notifications-v2#project-outline-scaling-onsite-notifications-onsite-notifications-v2)
- [ MVP documentation: Backend technical notes](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications#backend)
- [MVP documentation: Frontend technical notes](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications#frontend)

**Comment by ajakabcin** [comment]
Berni and I met with Melanie yesterday 1/30 to talk through the intake process. VA Notify owns the more formal, broader intake process for notifications, and then once a team/feature reaches the point where the notification is going to be implemented imminently, then Melanie and Beverly will loop the My VA team in via a formal slack thread. They will use guidance we provide to determine if the new notification should also become an onsite notification. The questions/criteria are tbd and need to be formalized by My VA but then will be shared with VA Notify.
