### ISSUE TITLE
Discovery: Capture metrics of health endpoints in Vets API

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#51938]
## Description

It might make sense to capture metrics of external services and their availability

## Tasks
- [x] Do we have a synthetic monitor for external services?
- [x] Do we want to capture services in Sentry?
  - [x] Sync up with Eric/Lindsey
- [ ] (Potential) pull this information into an "overall page" for VFS users to see
- [ ] (Potential) synthetic monitor / dashboard of services can be created into SLI --> SLO
- [ ] (Potential) Documentation for new services being worked on to be added to monitor/dashboard for metric tracking

## Acceptance Criteria
- [x] New stories spun up (if possible)
- [x] Document this in Confluence

## How to configure this issue
- [ ] _Attach a Milestone_
- [ ] _Story points_
- [ ] _Sprint assigned if pulling into sprint_
- [ ] _Epic assigned_
- [ ] _Team label assigned_

**Comment by holdenhinkle** [comment]
See the Synthetic Tests sheet in [this Google Doc](https://docs.google.com/spreadsheets/d/1-ty49As0WEgEf91LUhlD9ASimKrPUOsxmoMphYwx95k/edit#gid=525679545).

Pic:
![Image](https://user-images.githubusercontent.com/9326247/216070410-44916189-db12-483a-b63b-c0129da12d5e.png)


Tests _might_ exist for EVVSS/Claims.

None of the other services have tests.

**Comment by holdenhinkle** [comment]
## Regarding Sentry
We’re already logging service exceptions errors to Sentry. Common::Client errors are defined here - https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/common/client/errors.rb

**Comment by holdenhinkle** [comment]
# Document this in Confluence
See https://vfs.atlassian.net/wiki/spaces/TT3/pages/2512977989/Capture+metrics+of+health+endpoints+in+Vets+API+51938

**Comment by holdenhinkle** [comment]
New stories:

- https://app.zenhub.com/workspaces/platform-tech-team-3-6335ab9b1901b99243ce7601/issues/gh/department-of-veterans-affairs/va.gov-team/52918
- https://app.zenhub.com/workspaces/platform-tech-team-3-6335ab9b1901b99243ce7601/issues/gh/department-of-veterans-affairs/va.gov-team/52921
- https://app.zenhub.com/workspaces/platform-tech-team-3-6335ab9b1901b99243ce7601/issues/gh/department-of-veterans-affairs/va.gov-team/52922
