### ISSUE TITLE
[FE] Conditional rendering of the address validation form is somewhat cumbersome

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#5193]
## User Story:
As a veteran, I need to have performant and easy address validation, therefore my coders to be able to maintain the code.

Rendering decisions within the conditional section is written as a hard to maintain piece of code and we would like to clean it up to improve readability and maintainability. 

## Tasks
- [ ] Talk to Kelson to do a quick code review
- [ ] Redesign new address validation visual component form element rendering
- [ ] Code it up, regress, PR and all the normal stuff.

## Acceptance Criteria:
* Component behaves the way it was laid out in the AC
* Code is cleaner and performance >= previous

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bradl3yC** [comment]
@Samara-Strauss had Kelson review from Public Website, he did not see any glaring changes that need to be made.

**Comment by Samara-Strauss** [comment]
Noted, thanks!
