### ISSUE TITLE
Discovery: Potential solution for external service timeout within Vets API

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#51935]
## Description
In this discovery, we want to explore a potential solution to external services behaving badly with the potential use of breakers.  

## Tasks
- [x] Familiarize ourselves with breakers 
- [x] Does it listen to all external services? 
     - [x] What current services are being listened to within the breaker
     - [x] Do we need to add any additional services
- [x] What is the current threshold and do we need to config it? 
     - [x] Can the reroute be handled by breakers/nginx

## Acceptance Criteria
- [x] Document this within our Confluence page
- [x] stories are created 

## How to configure this issue
- [x] _Attach a Milestone_
- [x] _Story points_
- [x] _Sprint assigned if pulling into sprint_
- [x] _Epic assigned_
- [x] _Team label assigned_

**Comment by holdenhinkle** [comment]
Personal notes about [breakers](https://github.com/department-of-veterans-affairs/breakers):
- While a service is marked as down, requests will continue to flow through occasionally to check if it has returned to being alive.
- `seconds_before_retry` - The number of seconds to wait before sending a new request when an outage is reported. Every N seconds, a new request will be sent, and if it succeeds the outage will be ended. Defaults to 60.
  - Are these requests the occasional user requests that are allowed through? Or does breakers ping the service on it's own?
- `error_threshold` - The percentage of errors over which an outage will be reported. Defaults to 50.
  - If a service is down, it sounds like some users will still experience timeouts until the `error-threshold` is reached.
    - Is this what we want?

Breakers to-do:
- [ ] Check if we can redirect direct users to a general _service you requested is down_ page using by [changing the outage response ](https://github.com/department-of-veterans-affairs/breakers#changing-the-outage-response)
- [ ] Check if we can create a [plugin](https://github.com/department-of-veterans-affairs/breakers#plugins) that will redirect users to a general _service you requested is down_ page

**Comment by holdenhinkle** [comment]
vets-api isn't using the plugin feature of breakers:
```
class ExamplePlugin
  def on_outage_begin(outage); end

  def on_outage_end(outage); end

  def on_error(service, request_env, response_env); end

  def on_success(service, request_env, response_env); end
end
```

And it's using the default outage response:
```
Breakers.outage_response = { type: :status_code, status_code: 503 }
```

---

This file lists all the services configured to be handled by breakers - `config/initializers/breakers.rb`

```
  services = [
    DebtManagementCenter::DebtsConfiguration.instance.breakers_service,
    Caseflow::Configuration.instance.breakers_service,
    DecisionReview::Configuration.instance.breakers_service,
    Rx::Configuration.instance.breakers_service,
    BB::Configuration.instance.breakers_service,
    EMIS::MilitaryInformationConfiguration.instance.breakers_service,
    EMIS::PaymentConfiguration.instance.breakers_service,
    EMIS::VeteranStatusConfiguration.instance.breakers_service,
    EVSS::ClaimsService.breakers_service,
    EVSS::CommonService.breakers_service,
    EVSS::DisabilityCompensationForm::Configuration.instance.breakers_service,
    EVSS::DocumentsService.breakers_service,
    EVSS::Letters::Configuration.instance.breakers_service,
    EVSS::PCIUAddress::Configuration.instance.breakers_service,
    EVSS::GiBillStatus::Configuration.instance.breakers_service,
    EVSS::Dependents::Configuration.instance.breakers_service,
    EVSS::ReferenceData::Configuration.instance.breakers_service,
    Gibft::Configuration.instance.breakers_service,
    Facilities::AccessWaitTimeConfiguration.instance.breakers_service,
    Facilities::AccessSatisfactionConfiguration.instance.breakers_service,
    GI::Configuration.instance.breakers_service,
    HCA::Configuration.instance.breakers_service,
    MHVAC::Configuration.instance.breakers_service,
    MPI::Configuration.instance.breakers_service,
    Preneeds::Configuration.instance.breakers_service,
    SM::Configuration.instance.breakers_service,
    VAProfile::ContactInformation::Configuration.instance.breakers_service,
    VAProfile::Communication::Configuration.instance.breakers_service,
    Search::Configuration.instance.breakers_service,
    SearchTypeahead::Configuration.instance.breakers_service,
    SearchClickTracking::Configuration.instance.breakers_service,
    Okta::Configuration.instance.breakers_service,
    VAOS::Configuration.instance.breakers_service,
    IAMSSOeOAuth::Configuration.instance.breakers_service,
    CovidVaccine::V0::VetextConfiguration.instance.breakers_service,
    VEText::Configuration.instance.breakers_service,
    PagerDuty::Configuration.instance.breakers_service
  ]
```

**Comment by holdenhinkle** [comment]
Submitted frontend support request to find out how vets-website handles 503 status codes - https://dsva.slack.com/archives/CBU0KDSB1/p1674841019041429

**Comment by holdenhinkle** [comment]
## What is the current threshold and do we need to config it?
I'm pretty sure the current threshold is the default because `error_threshold` isn't set anywhere.

Default:
> It will track all requests and will stop sending requests to it for one minute when the error rate reaches 50% over a two minute period.

**Comment by holdenhinkle** [comment]
I had a conversation with Ray Massina about this today and he bought up what I think is a good point: 

Some VFS engineers might have handled 503 requests already so if we make a global redirect we will bypass their solutions without them knowing.

This seems like it could be a larger architectural decision.

---

I searched vets-website and see that only a few apps mention 503 in their tests, but I think that might be a separate internal code for something vets-related. I'd have to spend more time lookin at this.

Also, some apps might not handle 503 errors specifically and instead check for 5xx errors which would be difficult to find by text search because that can be implemented in any number of ways.

I looked at the FE Platform docs and didn't see any recommendations or conventions anywhere for how to handle http status errors.

**Comment by holdenhinkle** [comment]
List of external services (10 months old/probably hasn't changed much) - https://docs.google.com/spreadsheets/d/1-ty49As0WEgEf91LUhlD9ASimKrPUOsxmoMphYwx95k/edit#gid=855746174

**Comment by holdenhinkle** [comment]
Confluence doc - https://vfs.atlassian.net/wiki/spaces/TT3/pages/2510913715/Potential+solution+for+external+service+timeout+within+Vets+API

**Comment by ericboehs** [comment]
Holden and I discussed this issue. Here are some problems we discussed:

- Breakers does not check if a service is slow. If a service eventually returns a non-500, it [marks it as a success](https://github.com/department-of-veterans-affairs/breakers/blob/e404392da16ebb1ab413ad091d3d078b647b5302/lib/breakers/uptime_middleware.rb#L67).
- We need to make sure all HTTP connections are timing out. open/read/write timeouts [aren't enough](https://gist.github.com/ericboehs/4dcca8f5d73872d903811af41e729568). We need [global timeouts](https://janko.io/httprb-is-great/#global-timeout).

**Comment by holdenhinkle** [comment]
I’ve been trying to familiar myself with the the client part of the vets-api code base.

It looks like we’re using the default `net::http` timeout which is 60 seconds:
https://github.com/lostisland/faraday/issues/708#issuecomment-477614664

I think we can adjust timeouts in `https://github.com/department-of-veterans-affairs/vets-api/tree/master/lib/common/client` or set a new default timeout value in the general `#request` method or each corresponding http method which calls `#request`

See [Faraday > Customizing the Request](https://lostisland.github.io/faraday/usage/customize#custom-serializers)

**Comment by holdenhinkle** [comment]
We're using the [rack-timeout](https://github.com/zombocom/rack-timeout) gem.

>Abort requests that are taking too long; an exception is raised.
>
>A timeout of 15s is the default. It's recommended to set the timeout as low as realistically viable for your application. You can modify this by setting the RACK_TIMEOUT_SERVICE_TIMEOUT environment variable.

Disclaimer:
> Rack::Timeout is not a solution to the problem of long-running requests, it's a debug and remediation tool. App developers should track rack-timeout's data and address recurring instances of particular timeouts, for example by refactoring code so it runs faster or offsetting lengthy work to happen asynchronously.

See [Risks and shortcomings of using Rack::Timeout](https://github.com/zombocom/rack-timeout/blob/main/doc/risks.md)

vets-api [rack-timeout config](url):
```ruby
# frozen_string_literal: true

# Adds a global timeout for all requests
if !Rails.env.test? && Settings.rack_timeout
  # @see https://github.com/zombocom/rack-timeout/blob/main/doc/settings.md
  Rails.application.configure do |config|
    config.middleware.insert_before(
      Rack::Runtime, Rack::Timeout,
      # Default of 0 disables rack timeout unless the ENV variable is set
      service_timeout: Settings.rack_timeout.service_timeout || 0,
      wait_timeout: Settings.rack_timeout.wait_timeout || 0,
      wait_overtime: Settings.rack_timeout.wait_overtime || 0
    )
  end

  Rack::Timeout::Logger.disable
end

```

**Comment by holdenhinkle** [comment]
Here's the Http.rd Faraday adapter - https://github.com/lostisland/faraday-http

**Comment by holdenhinkle** [comment]
Confluence doc - https://vfs.atlassian.net/wiki/spaces/TT3/pages/2510913715/Potential+solution+for+external+service+timeout+within+Vets+API

**Comment by holdenhinkle** [comment]
Stories created:

- https://app.zenhub.com/workspaces/platform-tech-team-3-6335ab9b1901b99243ce7601/issues/gh/department-of-veterans-affairs/va.gov-team/52924
- https://app.zenhub.com/workspaces/platform-tech-team-3-6335ab9b1901b99243ce7601/issues/gh/department-of-veterans-affairs/va.gov-team/52930
- https://app.zenhub.com/workspaces/platform-tech-team-3-6335ab9b1901b99243ce7601/issues/gh/department-of-veterans-affairs/va.gov-team/52927
