### ISSUE TITLE
Create a Service Design issue template in github

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#51939]
## Purpose
Create a template that allows for swift issue creation that's customized for our team.

## Tasks
- [x] draft template
- [x] commit in new branch
- [x] merge to main

## Acceptance Criteria
- [x] Template is available in Zenhub for SDT use
