### ISSUE TITLE
Add image references to the values files 

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#51932]
# Description
In order for ArgoCD to deploy the appropriate image for a given preview environment, we need to pass the path to the Docker images into the `values.yaml` file.

Other values derived from GHA and used in the ArgoCD deployment are passed through pod annotations -- see this PR for reference: https://github.com/department-of-veterans-affairs/devops/pull/12426. This seems like the appropriate place to pass the path to the Docker images as well.

There are preceding workflows in the source repositories that will need to collect the path to the images as they are created.

# Tasks
- [x] Update GHA workflows to record the path to the Docker images needed for the PE in their respective ECR repositories
- [x] Update the script that creates the values files to include the Docker image paths
- [x] Update the deployment workflow in the `devops` repo

# Acceptance Criteria
- [ ] The values.yaml file for each PE environment contains the path to the appropriate FE and BE Docker images

**Comment by powellkerry** [comment]
Worked on getting my bearings on this task. I think I have a good understanding of what needs to happen, I just need to figure out how the path is exposed and how to reference it so that it can be passed.

**Comment by powellkerry** [comment]
Most of this effort has been done by previous work. The only changes that need to be made are in the devops repo in the pe-update-manifest.js file. There are 2 questions that I need to answer still:
- What should the data key be called? I'm thinking `docker_image_uri`, or is it something specific that ArgoCD looks for?
- What should the URI be? The URI's in ECS look like: https://008577686731.dkr.ecr.us-gov-west-1.amazonaws.com/dsva/preview-environment/${process.env.SOURCE_REPO}:${process.env.SOURCE_REF}. Is this a static domain that can be hardcoded?

**Comment by powellkerry** [comment]
Pull Request: https://github.com/department-of-veterans-affairs/devops/pull/12482
