### ISSUE TITLE
Define Approach for Backend Docker Image

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#51943]
# Description
The Docker image that we will use for Preview Environments will need to support `vets-api` + `vets-api-mockdata`.

1. How might we go about deploying these two resources to a single Docker container?
1. Will we be able to use the Docker file that is already in `vets-api` and recommended in documentation for local deployment?
1. Does the existing Docker image contain a deployment of `vets-api-mockdata` already?
   1. If `vets-api`'s existing Docker image does not contain `vets-api-mockdata` should we modify the existing image to also deploy that, or should we create an additional Docker file that also deploys mock data? 
1. What does the production deploy use?
1. What does `vets-api` CI use?

# Tasks
- [x] Answer all of the above questions
- [x] Create a Confluence document with a description of the propose approach
- [x] Discuss the proposed solution with the team to collect feedback
- [x] Analyze and discuss the Docker rework done by Lainey's team

# Acceptance Criteria
- [ ] An approach for creating a backend image for use in Preview Environments is available in a Confluence document and includes feedback from Tech Team 4 and other Platform stakeholders

**Comment by powellkerry** [comment]
Answers:

1. The current docker-compose.yml used for local development includes vets-api-mockdata as a volume in the docker image.
2. Further investigation needed to answer.
3. The docker image does bundle the vets-api-mockdata in a volume, but its reference is relative to the vets-api directory on a local machine.
i. We may be able to modify the definition in volumes (docker-compose.yml) to work off of an environment variable.
ii. There is a docker-compose.test.yml (last updated Sep 27, 2021), I don't know what this is used for or if we should use this file instead. Should there be a seperate docker-compose.yml file for test and stage or for preview environments?
4. Production build and deploy is ran through Jenkins?

**Comment by pjhill** [comment]
@powellkerry -- Per a recent convo with other platform teams, the Docker image for `vets-api` required major rework in order to operate in K8s. I'm not sure where that rework is available because we couldn't dive too deeply into the discussion, but that may affect the research you've already done!

**Comment by powellkerry** [comment]
@pjhill I started a confluence doc to document my findings and questions and have linked to Dockerfile, build.yml, and deploy-template.yml used in the new k8s branch.

https://vfs.atlassian.net/wiki/spaces/TT4/pages/2490761493/Vets-API+Docker+Image

**Comment by powellkerry** [comment]
It appears that including vets-api-mockdata will be problematic as there is no clear way to include it using this github action:  docker/build-push-action@v2

It may be possible to develop a new docker-compose file for preview environments that includes vets-api-mockdata as a volume, but I am unaware of how to include this as a step in the GHA build. See [this](https://github.com/peter-evans/docker-compose-actions-workflow) example.

Also unclear is, if we were to figure out the custom docker-compose file option, how to reference/checkout the contents of the vet-api-mockdata repo in the volumes definition of the docker-compose file.

**Comment by pjhill** [comment]
Thanks for the updates on progress - I'm moving this to `in-progress` for the current sprint.

I believe we have some examples of Docker images that clone additional repos and deploy those resources.

**Comment by powellkerry** [comment]
Refined answers to the description:

1. How might we go about deploying these two resources to a single Docker container? We will need a new Dockerfile that clones the mockdata repo into the docker image.

2. Will we be able to use the Docker file that is already in vets-api and recommended in documentation for local deployment? No, because the mockdata repo will need to be referenced and cloned into the Dockerfile

3. Does the existing Docker image contain a deployment of vets-api-mockdata already? Yes, but it references mockdata assuming that the local machine already has a cloned version of the repo that is locates in the same directory as vets-api.
i. If vets-api's existing Docker image does not contain vets-api-mockdata should we modify the existing image to also deploy that, or should we create an additional Docker file that also deploys mock data? A conditional could be written to only clone mockdata if the environment is not prod or local. This is a question of code organization, if there is a lot of custom logic that may be written for PEs now or in the future it may be worth creating a new Dockerfile

4. What does the production deploy use? The new production deploy will use an updated Dockerfile and GHAs for deployments to k8s. Currently the deploy is done in Jenkins

5. What does vets-api CI use? Currently all test and builds are done in Jenkins


I have update [this](https://vfs.atlassian.net/wiki/spaces/TT4/pages/2490761493/Vets-API+Docker+Image) confluence doc with a proposed solution. The solution assumes a new custom Dockerfile will be used, this doesn't need to be the case as explained above.
