### ISSUE TITLE
What should the SB Showroom look like/include?

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#51957]
## Purpose
We want a showcase that reflects the rigor and value of the resultant artifacts

Do we need a naming convention for better findability?

How to factor in this [new epic](https://app.zenhub.com/workspaces/platform-service-design-61bcbaf174a70100154e22e7/issues/gh/department-of-veterans-affairs/va.gov-team/52507) also?

Relationship between [Log](https://app.zenhub.com/workspaces/platform-service-design-61bcbaf174a70100154e22e7/issues/gh/department-of-veterans-affairs/va.gov-team/51953) and Showroom? Hypothesis: Mapping projects that are planned or in progress are monitored in the Log; once completed, they're presented (links, context) in the Showroom and the Log links to them in the Showroom.

[Product Outline - Aggregation and Publishing of platform-produced mappings and workflows](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2503376909/Product+Outline+-+Aggregation+and+Publishing+of+platform-produced+mappings+and+workflows)

Please review [this page](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2527004248/Showroom+demo)

## Tasks
- [x] Determine a concept for showcasing SBs 
  - [x] Who are the audiences?
  - [x] What can they access?
  - [x] What do they want to learn?
- [x] Create MVP of the space conceived
- [x] Bryan review
- [x] Nicole review
- [x] Taylor review

## Acceptance Criteria
- [x] The Showroom is easy to access
- [x] The Showroom is easy to find
- [x] The Showroom makes the purpose and offering of each SB evident

**Comment by twoangstroms** [comment]
Created [draft/test page](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2514026511/SB+Showroom+labels+test) to build various options to evaluate

**Comment by twoangstroms** [comment]
[Mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1675451535799/ec18e85ec1f1ec8cbed0e25289a7858af286b39a?sender=u4f7db1750f2355f805e60296) for working on a taxonomy of categories/labels

**Comment by twoangstroms** [comment]
Held back, currently blocked by the need for admin assistance in setting up and testing a user macro.

**Comment by twoangstroms** [comment]
Created [macro test page](https://vfs.atlassian.net/wiki/spaces/SDT/pages/edit-v2/2523561985)

**Comment by twoangstroms** [comment]
Fixed column order issue on [demo](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2527004248/Showroom+demo)

**Comment by twoangstroms** [comment]
Moving to Closed and ready to deploy.
