### ISSUE TITLE
Establish Prioritization criteria

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#51955]
## Purpose
How might we prioritize?
Do we look ahead to see what project teams will be working on?  (i.e. check the Project Planning Board)
Decide where to start when selecting a scenario (do we use what we already know? do we perform additional exploration?)

[Platform Service Strategy](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1643329677759/f0c03174224cb481282894a584fac63449ef9469?sender=u4397b715dc3690a417b71483)

[Scenario Organizer](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2504327255/Scenario+organizer+for+VFS+top+tasks)

## Tasks
- [x] What criteria should inform how we prioritize scenarios?
- [x] Research/try out some scoring methods (see [this experiment](https://docs.google.com/spreadsheets/d/11FIihW9Vn-QJbhwryG9dZ_YQxzI030nAWSwpfX6e-1Y/edit#gid=0))
- [x] [Review options with team](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2504327255/Scenario+organizer+for+VFS+top+tasks#Prioritization) and decide on the method to use

## Acceptance Criteria
- [x] Criteria established

**Comment by tayism** [comment]
Added my thoughts/comments to the [confluence page](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2504327255/Scenario+organizer+for+VFS+top+tasks#Prioritization).

**Comment by steel36** [comment]
Reviewed the excellent confluence page.

**Comment by steel36** [comment]
Work was not completed; rolled over to next sprint.
