### ISSUE TITLE
BE | Profile | Direct Deposit | Sandbox access and configuration

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#51956]
## Background
OAuth 2.0 Client Credentials Grant is used to access the API in the sandbox environment. This has been configured but not tested.

Instructions can be found [here](https://dev-developer.va.gov/explore/authorization/docs/client-credentials?api=claims).

## Tasks
Write a script that:
- [x] Generates a JSON web token (JWT) and sign it using private key.
- [x] Use the signed JWT as a client assertion to receive an access token.
- [x] Use the returned access token to authorize requests to the Lighthouse. 

## Acceptance Criteria
- [x] Make authorized requests to Lighthouse Direct Deposit API Sandbox environment from local machine.
