### ISSUE TITLE
[FSR] Identify affected veterans from non routed forms

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#51950]
## Issue Description
Debt team identified a bug causing veterans to navigate a previous version of the FSR (a version where we are not displaying copays) while completing the form and resulted in the form not being submitted to the DMC. A fix has been put in place so any FSR submitted will be now correctly routed.  

We need a way to identify affected veterans so DMC can can contact them and inform them. We have their uuid's but will likely need to provide emails so DMC can touch base.

---
## Tasks
- [x] Coordinate with Identity team to bulk fetch data of affected veterans
- [x] Provide list of affected veterans

## Acceptance Criteria
- [x] Necessary information has been passed along to DMC 
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
[Added BE ticket to gather UUID information to provide to identity team](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/52790)

**Comment by HeatherRienks** [comment]
FYI- @Dr-Pongo to follow up with @ScottyRJames - what does DMC need to contact Veterans?

**Comment by Dr-Pongo** [comment]
[Slack thread on data discussion ](https://dsva.slack.com/archives/CPE4AJ6Q0/p1676995747329419)for what data DMC needs to contact affected veterans.

**Comment by HeatherRienks** [comment]
@Dr-Pongo & @ScottyRJames  - Any updates from Joe Niquette running the script for us (per Slack thread above?)

**Comment by joeniquette** [comment]
Im still waiting to get the data I would need to get you the list of email addresses, once I have the ICNs or uuids then I can try to get the emails for each person.

**Comment by HeatherRienks** [comment]
@joeniquette - sounds good.  Just curious, who are we getting the data from? Just looking for an ETA. Thanks!

cc: @denisecoveyduc

**Comment by joeniquette** [comment]
Not sure honestly, whomever wants to give it to me :D

**Comment by ScottyRJames** [comment]
Added [ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54316) for checking for resubmissions

**Comment by ScottyRJames** [comment]
Resubmissions have been filtered out and emails of non submitted Veterans have been communicated to DMC
