### ISSUE TITLE
Pivot to a specific Initiative format and associated tasks for upcoming SB

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#51963]
## Purpose
Instead of pursuing SB's under an Ongoing Service, we will create an Epic for each individual SB, and tailor the tasks and goals to it.

## Tasks
- [x] Create epic
- [x] create tasks associated to the epic
- [x] Update epic with information specific to the selected SB

## Acceptance Criteria
- [x] Epic is available
- [x] tasks are created and associated to it
- [x] Epic is updated to reflect chosen SB and its particulars

**Comment by steel36** [comment]
Still blocked by #51958.  Should be pursued next sprint
