### ISSUE TITLE
Create space/doc for recording answers/feedback from SMEs

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#51965]
## Purpose
We'll need a document or board for interviewer(s) and notetaker(s) to record responses and associated observations.  

Also, HWE categorize criticality?

## Tasks
- [ ] Determine best way to record these for future synthesis/analysis
- [ ] create the resource and make available

## Acceptance Criteria
- [ ] Recording resource can be accessed by team
