### ISSUE TITLE
Archive previous Platform & Confluence pages associated w/ the Survey

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#51975]
## Purpose
Because we are changing the survey, we need to archive the previous pages for historical reference, and possible future use.  

## Tasks
- [x] Platform page should be archived and stored in SDT Confluence.  Perhaps a new archive section.
- [x] Confluence page should be archived and stored in SDT Confluence.  Perhaps a new archive section.

## Acceptance Criteria
- [x] Both sites are available in Archive section.
