### ISSUE TITLE
BE | Profile | Direct Deposit | Build Client Authentication

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#51976]
## Background
In order for the vets-api to communicate with the Lighthouse API, client authentication mechanisms need to in place.

## Tasks
- [x] Add JWT Generator to vets-api. 
- [x] Add CCG Service and Configuration to vets-api

## Acceptance Criteria
- [x] JWT Generator code reviewed.
- [x]  CCG Service and Configuration reviewed.

**Comment by Samara-Strauss** [comment]
At risk of not getting done because of a last minute need from the platform team for Tom to complete #52354.

**Comment by tpharrison** [comment]
@Samara-Strauss I am planning on finishing up the development work on this ticket today, but even if I do, the PRs are probably going to take a couple of days to be accepted.  So this ticket will need to be moved into next sprint.

**Comment by Samara-Strauss** [comment]
Thank you, @tpharrison!
