### ISSUE TITLE
Modify the Push-driven GHA Workflow to Tag and Store FE Image in ECR

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#51983]
# Description
Using our existing minimal FE Docker image while we work on a revised image, modify the preview environment GHA workflow driven by push events to the FE repositories to include an action that [tags ](https://docs.aws.amazon.com/AmazonECR/latest/userguide/ecr-using-tags.html)and [stores ](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-push.html)the Docker image using the [SOURCE_REPO]-[BRANCH_NAME] convention that we have used elsewhere.

- Keep in mind that we will be using an ECR lifecycle policy to clean up Docker images.

# Tasks
- [ ] Verify that the required ECR repositories are in place
- [ ] Use appropriate AWS credentials to push the Docker image to ECR
- [ ] Modify the GHA workflow to tag and store the image
- [ ] Verify the contents of the ECR repository after a test run

# Acceptance Criteria
- [x] When users push code to their feature branches, a GHA workflow generates a Docker image of the frontend, tags it appropriately, and stores it in ECR
- [x] Preview environment deployment processes are able to retrieve the images from ECR

**Comment by CBonade** [comment]
https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/51983 PR for this is here, with the code currently commented out as there is no dockerfile to generate this image for testing, therefore we don't want this to run.

**Comment by CBonade** [comment]
https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/51983 PR for this is here, with the code currently commented out as there is no dockerfile to generate this image for testing, therefore we don't want this to run.

**Comment by CBonade** [comment]
This has been merged. The steps are commented out in the workflow until we have a working docker image that we plan to use for this.

**Comment by pjhill** [comment]
That PR link in the comment is a link to this ticket. I believe this is the PR: https://github.com/department-of-veterans-affairs/vets-website/pull/23217

**Comment by pjhill** [comment]
The code that satisfies the AC is technically commented out for the time being until we are ready to turn the system on. That said, in testing we verified that the image is successfully stored in ECR.  Hooray for shaking out some bugs with that ahead of time!
