### ISSUE TITLE
Update Confluence documentation w/ new Survey info

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#51989]
## Purpose
Because we are changing the survey, we need to speak to the change and establish the key differences the new one will bring to the table. This is for the SDT Confluence space. The top-level content will be the same as for the Platform Site, but also include child pages with archived results links, schedule, and how to launch information.

- [x] Draft content (should be same as #51988)
         - Format of the survey (change from: "The survey is a relatively short, five-question survey...")
    - Timing
- [x] Team review content

## Acceptance Criteria
- [x] Site should speak to new makeup of survey

Overview page
-- Schedule (with links to artifacts such as decks and Murals)
-- How to [launch the Survey](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1445724309/How-to+Launch+the+Platform+Satisfaction+Survey) (tools and steps)
-- Aggregated results of themes per survey

Reference material:
[Product Outline](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2487091201/Product+Outline+-+Platform+Feedback+portal)

## Tasks
- [x] Adjust changed content within updated Confluence page

## Acceptance Criteria
- [x] Site should speak to new makeup of survey

**Comment by steel36** [comment]
@twoangstroms saw that you took this one and realized it should have had the dependency of another ticket.  Essentially, the existing pages need to be archived before we update this to a newer revision.

**Comment by steel36** [comment]
@twoangstroms I've archived both now so this ticket is good to proceed.

**Comment by twoangstroms** [comment]
@steel36 Thanks! I wasn't sure of the order of operations, so I was proceeding on getting the content thinking lined up.

**Comment by twoangstroms** [comment]
[Draft of existing Survey page with alert box on plans to move to continuous model](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2538078209/Draft+of+Platform+Satisfaction+Survey).

**Comment by steel36** [comment]
Blocked until #51416 is completed.
