### ISSUE TITLE
Update the Platform documentation site w/ new Survey info

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#51988]
## Purpose
Because we are changing the survey, we need to speak to the change and establish the key differences the new one will bring to the table. This is to update the [Platform Site page](https://depo-platform-documentation.scrollhelp.site/support/platform-satisfaction-survey).

The content 
## Tasks
- [x] Draft content (should be same as #51989)
    - Format of the survey (change from: "The survey is a relatively short, five-question survey...")
    - Timing
- [x] Update in "Support" space of Platform's Confluence area for upload to Platform Site

## Acceptance Criteria
- [x] Site should speak to new makeup of survey

**Comment by steel36** [comment]
Blocked until #51416 is completed.
