### ISSUE TITLE
Prepare and Launch Quarterly Platform Satisfaction survey

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#51997]
## Purpose
Step through the tasks to prep, launch, run, and synthesize the quarterly survey

## Tasks
- [x] Prepare [Survey](https://airtable.com/shrKpir00TnjDUBRS)
- [x] Update Confluence Documentation
- [x] Update Platform website documentation
- [x] Launch Survey
- [x] Confirm Survey's visibility & data funneling

## Acceptance Criteria
- [x] Confluence documentation is updated
- [x] Platform website documentation is updated
- [x] Survey is live
