### ISSUE TITLE
Test portal (internally & externally)

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#51999]
## Purpose
Test the portal to make sure it works as intended

## Tasks
- [x] Test main site's path
- [x] Test Slack bookmark path
- [x] Test ourselves to verify 
- [x] Recruit Platform and VFS team members
- [x] Test w/ other Platform team members
- [x] Test w/ VFS team members

## Acceptance Criteria
- [ ] VFS teams can understand and access the portal

**Comment by gopixelsgo** [comment]
Discussion: We may want to break this into 2 and separate out internal and external.

**Comment by steel36** [comment]
Note: I think we need "Designer" as one of the role options in the form

**Comment by twoangstroms** [comment]
Good catch! Added.


Dan Turner

Sr. UX Designer II, Ad Hoc
***@***.***

￼
