### ISSUE TITLE
Could platform-support channel feed it as well?  Should it?

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#51995]
## Purpose
  (Might be a good funnel due to its widespread use) or could selecting "Provide Feedback on ---" within the channel lead the user to the portal itself?

Can we figure out a decision tree: "when should I post in platform-support and when should I use feedback portal"?

## Tasks
- [x] Review what the current intake process is for the platform-support channel (review internal/external docs, any user flows, step through actual process)
- [x] Mini workshop with team
- [x] Determine whether feedback should come in via the Support channel as well
- [x] If yes, [what does the decision tree look like](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1679607880960/dcb763f273a49ef82a47a45b6e83cfd3fd935065?sender=u9ea6bd3ca12795949b606150)?

## Acceptance Criteria
- [x] Document [decision and plan](https://app.zenhub.com/workspaces/platform-service-design-61bcbaf174a70100154e22e7/issues/gh/department-of-veterans-affairs/va.gov-team/55729)
