### ISSUE TITLE
Set up main landing on Platform doc site

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#51998]
## Purpose
If the Support workflow leads to a form of sorts, where should a landing for the portal live on the Platform site?
Q: Are any requirements for this already captured? For content? Constraints on location?

[Documenting content and form](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2609119236/Portal+Page+brainstorming)

[Documenting location thinking/options](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2610004175/Portal+Page+location+in+Platform+Site)

## Tasks
- [x] Craft [initial version](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2612592951/Portal+Page+for+Platform+Doc+Site+draft) of these pages in Service Design space  (would house the Survey and Feedback portal.  FRP may be included, depending upon direction) 
- [x] Discuss changes w/ Platform Content team
- [x] Team review - Bryan
- [x] Team review - Taylor

## Acceptance Criteria
- [x] Preliminary landing is built out
- [x] Initial comments captured and discussed
- [x] Feedback from Platform Content on proposed location (see [here](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2610004175/Portal+Page+location+in+Platform+Site))

**Comment by twoangstroms** [comment]
Capturing and working with new information will have this carry over to next sprint

**Comment by twoangstroms** [comment]
@steel36 @tayism [Document on location](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2610004175/Portal+Page+location+in+Platform+Site) available for review

**Comment by twoangstroms** [comment]
@steel36 @tayism [Draft of page content](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2612592951/Portal+Page+for+Platform+Doc+Site+draft
) (no images yet) available for review
