### ISSUE TITLE
Update Confluence documentation w/ new portal info

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#52000]
## Purpose
Update internal documentation to reflect new approach.  May need to update pages related to Survey also.

## Tasks
- [x] Confluence pages updated
- [x] any new links included
- [x] any new workflows explained

## Acceptance Criteria
- [x] Updated page reflects new approach
