### ISSUE TITLE
Describe Major Product Milestones & Timelines

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#5200]
## Goal
We want to be able to not only describe the full migration process as fully as possible, but apply what we have learned in our past efforts and be able to project time estimations more accurately in the future for our next line of products and features.

## Tasks
- [x] Outline the major milestones encountered in working on the VFS platform.
- [x] Assign time estimations at the sprint level, taking into account the order of operations and overlap.

## Acceptance Criteria
- [x] The major milestones have been defined and documented [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/strategy/milestone-estimation.md) for refinement and estimation
