### ISSUE TITLE
Set up portal itself (Airtable form)

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#52002]
## Purpose
Determine and create the content of the form itself.

### Form Content
Probably set up a Confluence page to workshop content:
1. What questions do we want to ask? (Possibilities below)
a. What are you giving feedback about?
b. Please explain the issue you're having, (give plenty of detail; we want to understand the situation and how it affects your work)
c. Beyond identifying the pain point itself, do you have a suggestion for a fix?

### Workflow details
2. What's the title for the Slack Workflow?
3. What's the title of the Form itself?

## Tasks
- [x] Determine questions to ask, headings, etc
- [x] Determine any closing remarks to user (NOTE: Not available in Free plan)
- [x] Determine where the user ends up after submitting form (NOTE: Not available in Free plan; Free allows users to see a message that their responses were submitted)
- [x] Create form (example title: "Provide Feedback about the Platform") in Airtable. [Draft](https://airtable.com/shromU8aG2H95jCvO)
- [x] Set up Workflow, links out to Form
 - [ ] FEEDBACK REQUESTED: How do you feel about the Workflow making Slackbot DM the Workflow user, or send the message with an @-mention to the channel?
- [ ] Team Review

## Acceptance Criteria
- [x] Airtable form lives

**Comment by steel36** [comment]
I experienced that DM from the Slackbot and it felt like a disjointed experience.

**Comment by steel36** [comment]
Thanks for including the learnings about capability w/i the Free Plan in this ticket
