### ISSUE TITLE
Certificate of Eligibility | Post-launch monitoring

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#52015]
## Issue Description

In https://github.com/department-of-veterans-affairs/va.gov-team/issues/51193, we prepped the COE app for a 1/19 pilot launch to a small group of veterans within the VA. Once we've worked out the kinks that appear during the pilot, we will be releasing COE to 25% of vets on VA.gov. In preparation for that release, we'll need to:

---

## Tasks

- [x] ~~Set up Sentry alerts in Production~~
  - Too annoying to set this up in Sentry. I can just set a daily reminder to monitor Sentry.
- [x] Come up with plan for LGY timeouts and outages
  - LGY will send me emails when they go down for maintenance
- [x] Set up downtime notifications: https://depo-platform-documentation.scrollhelp.site/developer-docs/downtime-notifications.
- [x] ~~Set up health-check endpoint for LGY~~
  - I don't think we need this or want this. See https://dsva.slack.com/archives/CBU0KDSB1/p1675888563398179. If LGY goes down, we would display an error on the front end at submission time and would log sentry errors for any failed requests. Also, if LGY were to go down intermittently, then I wouldn't want to pause all LGY traffic. No need for that.
- [x] Figure out how to interface with contact center
  - They'll reach out to us.
- [x] Remember to notify `@RLHecht` when we launch to 25%. See https://github.com/department-of-veterans-affairs/va.gov-team/issues/43901#issuecomment-1364337765. (Done already. Turns out we didn't have to wait until we hit 25%).

---

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
Will talk to LGY about planned outage messaging. Unplanned outages will get generic messaging.

**Comment by saderagsdale** [comment]
Next steps: 

- Talk to LGY about downtime notifications.
- Ask platform how to use health check endpoint (we have one from LGY).

**Comment by data-doge** [comment]
@saderagsdale All questions answered! I think we can close this ticket. If any new issues crop up (so far it's looking like that won't happen) then we could re-open this ticket or create a new ticket.
