### ISSUE TITLE
Load Testing Plan

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#52017]
[Load test tools ](https://depo-platform-documentation.scrollhelp.site/developer-docs/load-tests#LoadTests-LoadTestTools)

**PROBLEM STATEMENT**
Need to create a load testing plan so that we can appropriately scale the vets-api in the different environments.

**STEPS/DEFINITION OF DONE**
- [x] Discovery on how this was done in the past.  (review documentation in devops repo)
- [x] Lessons learned from platform teams' load testing in the past.
- [x] What kind of load is needed?
- [x] Who are the test users? (might have been a script in the past that could be run)
- [ ] Script that can be replicated for load testing
- [x] Test plan that can be used for load testing 

*All documentation should be combined on team [confluence page in designated area](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2492301335/Load+Testing+Plan)

**Comment by RachalCassity** [comment]
I've seen the [Ruby-Jmeter](https://github.com/flood-io/ruby-jmeter) gem has been used by a few people for load testing.

**Comment by laineymajor** [comment]
@considerable to do some research on ruby-jmeter...
@rmtolmach review old thread from Joe N about load testing (thread included TL from fka QA standards team)

Determine and document what exactly needs to be tested. There is some info on this in the load test directory in the devops repo

**Comment by rmtolmach** [comment]
Slack thread about Loadtesting from Aug. 2022: https://dsva.slack.com/archives/C01CHAY3ULR/p1661352961067139

Loadtest directory in devops repo: https://github.com/department-of-veterans-affairs/devops/tree/master/loadtest

**Comment by laineymajor** [comment]
@considerable to update the plan with pros and cons of historical products used/recommended by platform
***make sure to look at WHAT IS ALREADY IN PLACE. let's not start spinning up new instances.**

**Comment by considerable** [comment]
Brainstorming for stress-test setup in EKS by CoP DevOps - https://dsva.slack.com/archives/C04CYC4LMU6/p1674524303379429

**Comment by LindseySaari** [comment]
@considerable - Conversation going to deploy Locust to utility cluster to target other clusters for loading. 

We can reach out to Peter and Ryan (prior commit history) for some load testing investigation.

@RachalCassity - Load Testing looks to be broken currently. Let's talk to people who have already run these tests in the past. We already have code and documentation for Locust. 

Next steps:
1. Spin through [Locust documentation](https://github.com/department-of-veterans-affairs/devops/tree/793326c6d6a6075ecaee746a129203da6f0a2dfe/loadtest) locally and document findings (Go through load tests already set up) - @considerable @rmtolmach 
2. Reach out to Peter Hill and Ryan Johnson - (scripts already set up, why is this broken?) - @RachalCassity @rmtolmach 
3. Deploy Locust to utility - @considerable @rmtolmach 
4. @considerable - Reach out to Kyle Crockett about DoS question.

**Comment by laineymajor** [comment]
Locust is something that's been used. @considerable looking into getting the server and tests running (next 3 days). Potential to demo the hello world (test against search).

@RachalCassity first investigating errors more -> reach out to peter and ryan after.

@rmtolmach review Locust documentation (linked above) --- also review information linked at the very top of this ticket (developer docs)

**Comment by LindseySaari** [comment]
@considerable Started the initial [conversation around how to slice these tests into categories](https://oddball.slack.com/archives/C045LCF8WU8/p1675097669663859?thread_ts=1675092002.928739&cid=C045LCF8WU8). [Example test run results](https://oddball.slack.com/archives/C045LCF8WU8/p1675099659181449?thread_ts=1675092002.928739&cid=C045LCF8WU8)

Next steps: @considerable Stand this up in the utility cluster.

**Comment by laineymajor** [comment]
@considerable had a meeting with Kyle yesterday about locust, will meet again on Friday after kyle has time to research. Will bring results of meeting back to team on Friday.

Found endpoint test scripts that can be run in locust (Igor found the results)

**Comment by laineymajor** [comment]
@considerable @rmtolmach any progress to note on this? I know we've ben putting out fires, but I just want to check on this...

**Comment by laineymajor** [comment]
existing tests in devops repo should be good. will continue to look into using that.
Todo
- [ ] Igor: update current workflow to ensure working with current image
- [ ] Igor: undo half onboarded locust application
*reach out to rebecca if needed

**Comment by laineymajor** [comment]
@considerable please provide update on the to do items from yesterday. Thanks!

**Comment by laineymajor** [comment]
@considerable @rmtolmach where is this work being documented?

**Comment by laineymajor** [comment]
Igor circling back to this soon... once helm101 is gone

**Comment by laineymajor** [comment]
Likely carryover to next sprint. This is taking longer due to the issues that required resolution when dialing up EKS traffic in staging to 100.

**Comment by laineymajor** [comment]
@considerable  primary focus until complete. Needs to be completed by end of the day on Monday.

**Comment by laineymajor** [comment]
Today will
- [ ] complete documentation on locust 
- [ ] trying to find balance between ideal and what is currently in place

**Comment by laineymajor** [comment]
https://github.com/department-of-veterans-affairs/vets-api-locust/blob/main/README.md#select-testing-tools-comparison

Remaining tasks
- [ ] review above link with team
- [ ] complete document re locust
- [ ] finish comparison table (for future iterations)

**Comment by laineymajor** [comment]
[Next steps](https://adhoc.slack.com/archives/C045LCF8WU8/p1676915015758779) discussed after reviewing Igor's draft of the load testing plan. @considerable please review the linked information and list out your next steps.

**Comment by considerable** [comment]
* Discovery on how this was done in the past. 
  - A number of [backend loadtest/\*/*\.py testing scripts for Locust](https://github.com/department-of-veterans-affairs/vets-api-locust/tree/main/loadtest) might be still good in today's load testing. The teams might suggest which of those scripts are still good.
  - A number of [frontend E2E testing scripts for Cypress](https://depo-platform-documentation.scrollhelp.site/developer-docs/end-to-end-testing-with-cypress) might be a fit for today's load testing. The teams might suggest which of them if any.
* Lessons learned from platform teams' load testing in the past.
  - Load testing in the past was meant to be done only upon big changes, which still makes sense now
  - Locus load test reports from the past were stored in GitHub with the commits dated 2 or 4 years back from now
  - Test reports from 4 years ago were accompanied with performance metrics reports captured from Prometheus
* What kind of load is needed?
  - Test reports are useful when correlated with performance metrics reports captured at the same time 
  - New tests must be visualized and correlated with performance metrics in DataDog, current Observability tool
  - We need the current tests to be capable of comparison to the old tests apple-to-apple
* Who are the test users? (might have been a script in the past that could be run)
  - Test users are the teams that make changes to the code and the teams that change the way the system scales
  - The teams staging a big change want to know of any performance bottle neck before real-time production
* Script that can be replicated for load testing
  - The table [Select Testing Tools Comparison](https://github.com/department-of-veterans-affairs/vets-api-locust/blob/main/README.md#select-testing-tools-comparison) has the links to different load test software, of which Apache JMeter looks like a tool that can deliver a DataDog solution with the least effort. Good to have the teams provide any comments on that.
* Test plan that can be used for load testing
  - Test Plan 1: sequential run of all the test scripts from the teams, each high-rate as they run one-after-another.
  - Test Plan 2: parallel run of all the test scripts from the teams, each low-rate as they run at the same time.

**Comment by LindseySaari** [comment]
@considerable Demo'd up the[ jMeter dashboard](https://vagov.ddog-gov.com/dash/integration/276/jmeter-overview?from_ts=1677092670398&to_ts=1677096270398&live=true) and we can clone it to make it our own. We discussed some other metrics that would be useful such as puma backlog, Sidekiq, external services (breakers), CPU, Error rates, Response Times/Latency, etc

**Comment by RachalCassity** [comment]
@LindseySaari @considerable Here is the cloned [Jmeter Dashboard](https://vagov.ddog-gov.com/dashboard/bu2-7t9-cja?tpl_var_env%5B0%5D=eks-dev&tpl_var_kube_cluster_name%5B0%5D=dsva-vagov-dev-cluster&tpl_var_kube_deployment%5B0%5D=vets-api-web&tpl_var_kube_namespace%5B0%5D=vets-api&from_ts=1677189133806&to_ts=1677192733806&live=true)

**Comment by considerable** [comment]
Visual presentation of the test plan we have designed:
![jmeter_datadog_loadtest.svg](https://images.zenhubusercontent.com/616758e4c5e87dce2146cdcf/38ed0e29-573a-4d0b-9649-6a0e093ab206)

**Comment by considerable** [comment]
The plan is to translate from Locust into JMeter and execute some or all of the following scenarios. First, low-rate in dev. Then, high-rate in staging. 
[ ] devops/loadtest/EWIS/ewis_locust.py
[ ] devops/loadtest/address_validation/address_validation_locust.py
[ ] devops/loadtest/appealsv2/appealsv2_locust.py
[ ] devops/loadtest/benefits_intake_v1/benefits_intake_locust.py
[ ] devops/loadtest/claimsv1/claims_locust.py
[ ] devops/loadtest/covid_registry/covid_registry_1-4_locust.py
[ ] devops/loadtest/covid_registry/covid_registry_locust.py
[ ] devops/loadtest/education_benefits_claim_0994_vettec/form0994_locust.py
[ ] devops/loadtest/education_benefits_claim_10203_stem/form10203_stem_locust.py
[ ] devops/loadtest/education_benefits_claim_stem_status/stem_claim_status_locust.py
[ ] devops/loadtest/facilities_api/locustfile.py
[ ] devops/loadtest/feature_toggle/locustfile.py
[ ] devops/loadtest/form526/form526_locust.py
[ ] devops/loadtest/form686/686c_locust.py
[ ] devops/loadtest/form686/va_file_number_check_locust.py
[ ] devops/loadtest/gibct/gibct_locust.py
[ ] devops/loadtest/hca_ee/hca_ee_locust.py
[ ] devops/loadtest/internal-auth/auth_locust.py
[ ] devops/loadtest/letters/letters_locust.py
[ ] devops/loadtest/pension_burial/pension_burial_locust.py
[ ] devops/loadtest/ppiu/ppiu_locust.py
[ ] devops/loadtest/preneed/preneed_locust.py
[ ] devops/loadtest/preneed/vic_locust.py
[ ] devops/loadtest/profile/dashboard_locust.py
[ ] devops/loadtest/profile/profile_locust.py
[ ] devops/loadtest/rated_disabilities/rated_disabilities_locust.py
[ ] devops/loadtest/search/search_locust.py
[ ] devops/loadtest/search/search_random_queries_locust.py
[ ] devops/loadtest/va_payment_history/va_payment_history_locust.py
[ ] devops/loadtest/vet360/vet360_locust.py
[ ] devops/loadtest/vic/vic_locust.py
[ ] devops/loadtest/vic/vic_locust_doc_small.py
[ ] devops/loadtest/vic/vic_locust_flow.py
[ ] devops/loadtest/vic/vic_locust_img.py
[ ] devops/loadtest/vre/28-1900/1900_locust.py
[ ] devops/loadtest/vre/28-8832/8832_locust.py
[ ] devops/loadtest/yellow_ribbon/locust.py

**Comment by laineymajor** [comment]
Are these ^^ the scripts? @considerable 
Is the plan done? Can you please link the plan?

**Comment by considerable** [comment]
@laineymajor please see the plan here - https://vfs.atlassian.net/wiki/spaces/TT1/pages/2492301335/Load+Testing+Plan
the scripts, if i am working alone, might take a script a day, i.e. 36 days as one of those scripts (#27) is done already.

**Comment by laineymajor** [comment]
@considerable we need to find an alternative solution as that timeline will **not** work. We do not have 36 days to do this. What are your other findings/ideas? If you need to schedule time to brainstorm with me and @LindseySaari  to brainstorm, please schedule that ASAP... but come with your initial ideas.

**Comment by laineymajor** [comment]
close per igor
