### ISSUE TITLE
Investigate Huron reported submission issues

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#52019]
## Issue Description
1/13/2023- VHA Stakeholders have reported issues for what they believe is happening from what VODA provides to what Huron pulls.

Issue 1 - Veteran possibly submit multiple times
Issue 2  -Same form multiple submissions
Issue 3 - No signature on the form

---
## Tasks
- [x] Backend team to investigate each issue 

## Acceptance Criteria
- [x] Provide feedback to stakeholder and document any future action required.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Issue 1: Veteran only submitted once on (11/24). Just one PDF uploaded on SP. Possibly duplicate within CSV file from VBS

Issue 2: Veteran submitted through portal multiple times (both on 10/25)

Issue 3: We can add the signature date to the FSR submission PDFs. Ticket created [here](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/52864)
