### ISSUE TITLE
Certificate of Eligibility | Distinguish LGY documents using `documentType`

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#52018]
## Issue Description

In https://github.com/department-of-veterans-affairs/vets-api/pull/11335 and https://github.com/department-of-veterans-affairs/vets-api/pull/11338, I started adding an `ATTACHMENT` tag to the `description` of vet-uploaded documents, to distinguish between vet-uploaded documents and notification letters. It was a hacky solution permissible at the time (and arguably still permissible). But since then, LGY has started setting the `documentType` of vet-uploaded documents to `Veteran Correspondence`. Given that, I'd like to retire our hacky solution, just in case LGY pushes some update or runs a data migration that overwrites my `ATTACHMENT` tags.

---
## Tasks
- [ ] We rely on `documentType` to distinguish between vet-uploaded documents and notification letters.

## Acceptance Criteria
- [ ] Vet-uploaded docs should _still_ be hidden from the COE status page.†

† For now, we are hiding vet-uploaded docs from the COE status page, because that page is currently designed to display notification letters _only_.  However, in the future, we will be re-designing that page to _also_ show the vet the documents they uploaded. Both now and then, we will still need to distinguish between the two types of documents, using `documentType`.

---

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
@data-doge Hey! Is this one done already?

**Comment by data-doge** [comment]
@saderagsdale Not yet, though should be a quick one once I get around to it
