### ISSUE TITLE
Add steps to push-driven workflow in vets-website to build PE image

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#52012]
## Issue Description
A [workflow](https://github.com/department-of-veterans-affairs/vets-website/blob/main/.github/workflows/preview-environment-deployment.yml) was created in vets-website to deploy a preview environment on push or repository_dispatch from content-build. We left an empty space knowing later on we would need to add steps to build a docker image here. It's time to scaffold those docker image steps and get this to upload the image to ECR before proceeding. This should also pass the docker-image name along to the devops repo, so it can be added to the values file.

---
## Tasks
- [x] Add step to log in to ECR
- [x] Add step to build and push to ECR
- [x] Construct the image names and paths in the devops workflow and write them to the manifest values file.

## Acceptance Criteria
- [x] An image is created, uploaded to ECR, and passed along to be added to the PE's values file.

**Comment by CBonade** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/12509 PR open for this here. The first two steps were already done on this. The third, ended up changing what approach we were taking and constructing it directly in the devops workflow instead of passing it.

**Comment by pjhill** [comment]
Looking good!
