### ISSUE TITLE
Change H1 of Get help filing your claim or appeal page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#52020]
## Issue Description

VBA has a new PACT-act related PSA about finding an accredited rep to help Veterans file claims. We've created a vanity url for our [Get help filing your claim or appeal](https://www.va.gov/disability/get-help-filing-claim/) page for the campaign. 

To better align the page with the vanity url, we are going to update the H1 to the page. We'll eventually make further updates to the page and look at relocating it in the IA--this work will happen in a separate ticket. 

We also need to update the teaser text on the disability hub landing page so that it aligns with the new H1.

We need to update the H1 and publish the changes before the vanity url goes live (as of now that's 1/26). If we learn this work won't be done by then, we need to let PW know in their ticket (#51910) to hold off on the redirect. 

## Tasks
- [x] Update Drupal page to the new H1: Get help from an accredited representative
- [x] Update teaser text on disability hub landing page
- [x] Copyedit new H1 and hub landing page change (Megan)
- [x] Publish 2 pages (Megan)

## Acceptance Criteria
- [x] Page is live with new H1

**Comment by mnorthuis** [comment]
@RLHecht Yes, it may depending on how much you modify the H1.  Please also review the hub page for the link and teaser text there.

**Comment by RLHecht** [comment]
Thanks, @mnorthuis The new H1 will be: Get help from an accredited representative

**Comment by RLHecht** [comment]
@bethpottsVADEPO Should we update this text on the hub page so it better matches the H1?

![Screen Shot 2023-01-24 at 9.32.35 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/baf62640-146b-4ad1-b4f9-17ec7830c73a)

If so, do we want to switch the order in the description so accredited rep comes first?

**Get help from an accredited representative**
Connect with an accredited Veterans representative or a Veterans Service Organization (VSO) for help applying for benefits.

**Comment by bethpottsVADEPO** [comment]
@RLHecht 
1/ Yes, let's use the exact H1 text for this text link label on the hub page.
2/ Please also change the left nav label to match the H1.

Thanks!

**Comment by RLHecht** [comment]
@megzehn These are ready for you. We want to make sure we publish these today as the redirect should be going live tomorrow. I changed the menu title in the Drupal node though it wasn't showing up as different in the left nav in preview. So just confirm in the menu section of drupal as well. It should match the new H1: Get help from an accredited representative

**Comment by megzehn** [comment]
Thank you, @RLHecht! 

Confirming I published both pages with the updated H1 (detail page), plus the link text and teaser text (hub landing page).

**Comment by RLHecht** [comment]
Thanks! These pages are both live with the changes. Closing!
