### ISSUE TITLE
[Cursory A11y Audit]: Supplemental Claims

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#52045]
### Auditor(s)

joshkimux

### Automated

- [ ] Run axe checks on every page or unique state (required)
- [ ] Run WAVE on every page if time allows. WAVE is more visual than axe or axe-coconut, but offers some excellent ways to identify nested headings and HTML5 landmark tags.

### Manual

- [ ] Color contrast checks (recommend using whocanuse.com for beyond compliance reports)
- [ ] Color blindness checks
- [ ] Zoom layouts to 400% and inspect them for readability. If layouts break at 400%, I will start reducing them until they become stable, and log the zoom ratio when things started breaking.
- [ ] Keyboard navigation

### Screen Reader

- [ ] Firefox and NVDA
- [ ] Edge and JAWS
- [ ] iOS Safari and VoiceOver (Mobile)
- [ ] Safari and Voiceover (Desktop)
- [ ] Chrome and Talkback

### Staging or Production Link

[Supplemental Claims, Dev Environment](https://dev.va.gov/decision-reviews/supplemental-claim/file-supplemental-claim-form-20-0995/start)

### Test Users

1. Cara, User 223, vets.gov.user+233@gmail.com
2. [Passwords can be found here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)
