### ISSUE TITLE
Create and publish future rates page for Chapter 33 rates-HOLD TO PUBLISH

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#52048]
## Issue Description

The education business line publishes Chapter 33 rates for the coming school year (that go into effect in August) in February so that students can have the information ahead of time. 

Now that we have the education rates on our modernized pages, we need to create a separate rates page with this information explaining that these are for the future school year. 

We need to work with Mikki to figure out the IA for these pages and where they'll live within the rates section. 
**Update:** Future rates IA info here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/52049#issuecomment-1402333685

Eventually we'll move these rates to our current rates page and change the information on the future rates page to tell users to check back to this page soon for upcoming rates.

## Tasks
- [x] Get future rates from EDU stakeholders
- [x] Open IA intake request ticket #52049
- [x] Create Drupal page and input rates
- [x] Review
- [x] Send to stakeholders for approval
- [x] Copyedit
- [x] Publish

## Acceptance Criteria
- [x] New future rates page is live

**Comment by katherine-fung** [comment]
I cloned the past rates page to create the future rates page. I updated the dates and language to reflect future rates. Now waiting for the updated rates from SMEs. 

Link: http://preview-prod.vfs.va.gov/preview?nodeId=52939

**Comment by megzehn** [comment]
Great catch, @katherine-fung!! I published the updated dates and fixed them on the past rates page for Fry scholarship as well.

**Comment by RLHecht** [comment]
Moving to blocked while waiting for the new rates to add to the page.

**Comment by RLHecht** [comment]
@katherine-fung Here are the rates to enter: 

[https://app.zenhub.com/files/133843125/bd007344-2781-48b4-88e5-ea4794db733d/download](https://app.zenhub.com/files/133843125/bd007344-2781-48b4-88e5-ea4794db733d/download)

**Comment by katherine-fung** [comment]
I've entered the new rates on the future rates page. 

Future Post-9/11 GI rates page: http://preview-prod.vfs.va.gov/preview?nodeId=52939

The test fees page also needs review: 
http://preview-prod.vfs.va.gov/preview?nodeId=926

The test fees info hasn't changed, but I did add a detail to the test fees page from the future rates info for clarification. While VA reimburses up to $2000 for licensing and certifications, there's no limit on how much they reimburse for national standardized tests like the SAT. 

I tweaked the copy and headers to add this sentence: 

"If you’re a Veteran or service member and you qualify for the GI Bill, we’ll pay for as many national tests as you take." 

The test fees page hasn't been updated in a while. The header style is a bit funky on this page, but I mostly left it alone and just made the change we need for this ticket.

**Comment by RLHecht** [comment]
IA work is shown in ticket #52049

**Comment by katherine-fung** [comment]
@bethpottsVADEPO - there's 1 area of this page I'd love your feedback on. (link to the inline comparison of the changes here: https://prod.cms.va.gov/node/52939/revisions/view/749509/751687/visual_inline) 

1. I added a detail about test fees. 

While VA reimburses up to $2000 for licensing and certifications, there's no limit on how much they reimburse for national standardized tests like the SAT. The Post-9/11 GI Bill currently lumps licensing/certifications/national tests under a $2000 limit, but the source file suggests this is wrong. 

Here's the copy I proposed: 

"[H2] Full rates for testing fees
Effective August 1, 2023, to July 31, 2024

Check to make sure we cover any tests before you take them. We cover only tests we approve for the GI Bill.

Learn what tests we approve for the GI Bill

[H3] Licensing and certification test fees
We’ll pay up to $2,000 for qualifying licensing and certification test fees.

We’ll charge your entitlement at the rate of 1 month for every $2,262.59 in fees we pay for licensing and certification tests. 

[H3] National tests
There's no limit on how much we'll reimburse you for national test fees. 

We’ll charge your entitlement at the rate of 1 month for every $2,262.59 in fees we pay for national tests."

And FYI I put the MHA language that we drafted for the STEM rates page here too. If Cinda and Jodie come back with changes, I'll update the future rates page in Drupal.

**Comment by bethpottsVADEPO** [comment]
Content looks good to go @katherine-fung as we discussed in slack...

**Comment by katherine-fung** [comment]
Thanks @bethpottsVADEPO! 

@RLHecht - this page is ready for copyedit. Thank you!! 

http://preview-prod.vfs.va.gov/preview?nodeId=52939 

Note: Jodie sent her feedback yesterday, on 3/13, and I made those changes to the MHA sections of the page.

**Comment by RLHecht** [comment]
I copyedited this, set the url and left nav and published. Moving to validate.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.

**Comment by katherine-fung** [comment]
Hi @megzehn and @RLHecht, 

Jodie reviewed the live link and found a few other things to change. I updated the following: 

- Under courses and training, I added "and enrollment period" to the section about "Money for books and supplies" 
- I updated "Money to help you move from a highly rural area" to match VA's definition of a rural area 
- Under on-the-job-training/apprenticeships, I removed details that aren't applicable for monthly housing allowance 
- Under on-the-job-training/apprenticeships, I corrected the timing of money for books and supplies 

Can you please review these changes? Sorry to re-open this ticket, and thank you!! 

http://preview-prod.vfs.va.gov/preview?nodeId=52939

I can forward you the email thread with Jodie if that's helpful.

**Comment by megzehn** [comment]
Thanks, @katherine-fung! I reviewed these changes and verified that they were updated in the past and current rates pages. 

@RLHecht I think this is OK to close again.
