### ISSUE TITLE
[epic] Accessibility Testing for [DR Team Supplemental Claims]

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#52046]
## Product information

- [X] Team name, product name, and feature name have been added to the title of this issue.
- [X] Team label, product label and feature label (if applicable) have been added to this issue.

### Test Users, Login, and More

1. Cara, User 223, vetsgov+test233@id.me
2. [Passwords can be found here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-HLR.md)
3. [Supplemental Claims, Staging Link](https://staging.va.gov/decision-reviews/supplemental-claim/file-supplemental-claim-form-20-0995/introduction)
4. [Build notes](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48138)
5. [Testing plan (google sheets)](https://docs.google.com/spreadsheets/d/157gfgClyIoIMGrQky-KKvtaoug-Z5TSbBIguWAyr8zg/edit#gid=1370873395)
6. All testing was completed by @joshkimux 

## Color and contrast
- [x] All text of 20px or smaller has a 4.5:1 contrast ratio to its background (or better)
- [x] All text of 20px or larger has a 3:1 contrast ratio to its background (or better)
- [x] Non-text elements have a 3:1  contrast ratio to their background and to neighboring elements (or better)
- [x] Color is not the only way to distinguish links from other text (eg. links are underlined)
- [x] Any charts, maps, infographics, and tables convey all information without only relying on color
- [x] Content does not refer to color, especially when providing user instructions (eg. "Click the blue button")

## Axe scans
- [x] Each page has been scanned using axe (results shared below)
- [x] axe is integrated into your end-to-end testing

## Content and rezoom
- [x] All page elements are readable and usable at 200% zoom
- [x] All page elements are readable and usable at 300% zoom
- [x] All page elements are readable and usable at 400% zoom

## Keyboard navigation
- [x] Each link, button, form input, checkbox, radio button, select menu, and custom element can receive keyboard focus
- [x] Each link, button, form input, checkbox, radio button, select menu, and custom element responds to expected keys
- [x] All elements under focus have a visible focus indicator
- [x] The order of [Tab] stops made sense and was appropriate for completing tasks

### Back button vs go back to link
<img width="363" alt="Screenshot 2023-02-27 at 11 28 59 AM" src="https://user-images.githubusercontent.com/14154792/221621995-497c953f-a766-434e-bf9a-139f7fe6cac7.png">

You may notice that there is a back button (in the starting flow) and "go back to" link (on the introduction page). We did not flag this as an inconsistency as:

- In the future, we will be adding more questions to that flow
- Because this a single page application subtask, and technically still a part of the "form" where the URL is not changing, we are doing an "action" hence "back button"

## Screen reader testing

- Tested on iOS/Safari and NVDA/Chrome

## Known issues that are out of scope or DST related
- [ ] **Decision reviews and appeals** heading above the [secondary navigation on the supplemental claims homepage](https://dev.va.gov/decision-reviews/supplemental-claim/) belongs to a DST component. It is a `h4` that comes before the `h1` on the page.
- [ ] [Memorable date, old date bug and NVDA bug](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1593)
- [ ] [Hint text issues (not programmatically linked, low contrast)](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1334#issuecomment-1451913743)
- [ ] ["Step" language is confusing](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1538) 
  - [ ] -_Visible_ focus halo does not exist for headings inside of web components, which causes inconsistency when it comes to most headings having a visible halo and a few not having the visible halo.
- [ ] Focus is lost when uploading a new file on NVDA, among other upload issues with the upload component (design system issue, haven't logged this as a bug yet)
- [ ] Design system team should do a UI inventory audit on buttons when it comes to primary/secondary placement
- [ ] Smooth scrolling is particularly worse on the medical records request page; <del>[a ticket exists here that has yet to be resolved](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6701).</del> [Update, I've created a DST issue.](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1604)

**Comment by saderagsdale** [comment]
@joshkimux Hey Josh! Hows this one going?

**Comment by joshkimux** [comment]
@saderagsdale about 25% complete, but I’ve caught some of the more major issues in the spreadsheet which Robin and Jared are aware of. I’ve also looped in the platform a11y specialist ahead of time 😊

Will need 2-4 more days to wrap this up when I get back from moving (a little longer than usual given the length and supporting the shared support transition).

**Comment by saderagsdale** [comment]
[Link to tickets from audit](https://docs.google.com/spreadsheets/d/157gfgClyIoIMGrQky-KKvtaoug-Z5TSbBIguWAyr8zg/edit#gid=0).

**Comment by saderagsdale** [comment]
Josh will write tickets for major issues.

**Comment by eileen-coforma** [comment]
@joshkimux Noticed that the testing plan was an archive sheet, so I updated it to the one we're working off of.

**Comment by joshkimux** [comment]
@briandeconinck heads up that this audit has been completed! We'll be aiming to resolve most of the `defect-2`s before the staging review.

**Comment by saderagsdale** [comment]
@joshkimux moving this to the epic backlog since the remaining tickets are not actionable.

**Comment by joshkimux** [comment]
@saderagsdale appreciate it! This may be the fastest resolution of an accessibility epic I've seen in my entire career ❤️
