### ISSUE TITLE
Design pattern for page headings as input labels

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#52050]
## Task Description
In a one-thing-per-page workflow, there's often a single input on a page. Design for the use-cases where the heading may act as an input label, including marking requiredness.

## References
- [Slack thread on using inputs as headings](https://dsva.slack.com/archives/C01DBGX4P45/p1669734367545789)
- [Outreach to platform design system](https://dsva.slack.com/archives/C01DBGX4P45/p1672951140102929)
- [Design explorations WIP](https://www.figma.com/file/yknNdT9fcgBNb8mvz3cGIu/Optionality-Markers-Pattern?node-id=2%3A4)
- [Experimental design ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1446)

## Acceptance Criteria
- [x] Design file created
- [x] ED ticket created
- [ ] Platform decision recorded
- [ ] Dev spec created

**Comment by outerpress** [comment]
[ED ticket ](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1446)has been created, will present to design council on the 27th

**Comment by outerpress** [comment]
Notes from design council are [here](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1446#issuecomment-1407101613)

Next steps are for devs to work on implementation. Once they have a proof of concept, we'll get feedback from platform accessibility.

**Comment by outerpress** [comment]
Not prioritized for PI 8, moving to Icebox

**Comment by outerpress** [comment]
This has been implemented, closing
