### ISSUE TITLE
[UX][Research] Create Widget for GA Dashboard to Measure Success

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#52056]
## Tasks
- [x] Work with FE to define how we are capturing this metric via GA
    - Look at the scroll-depth GA event 
- [x] Add events to Google sheets document
- [x] Create widget & add to GA dashboard

**Comment by benbrasso-agile6** [comment]
Left adrian a comment here https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/52055

**Comment by benbrasso-agile6** [comment]
Added a widget into dashboard https://analytics.google.com/analytics/web/#/dashboard/DgeEvA4JTruKLAW444xXOg/a50123418w177519031p176188361/

Updated GA spreadsheet of events https://docs.google.com/spreadsheets/d/1BPOlI6vzH-tMTswvUrci3Q0NkBmfIIfo8Cgj_nM10gk/edit#gid=0

**Comment by benbrasso-agile6** [comment]
Closing
