### ISSUE TITLE
[FE] Move Action Link on Pre-Check-in Intro Page

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#52055]
## User Story
Based on our analytics, we are finding high bounce rates on the Pre-Check-in landing page leading to Veterans not completing their Pre-Check-in tasks. We theorize that because the action link is presented further down on the page that some Veterans may not know that it is there. We propose moving it to the top of the page and doing a progressive roll-out to determine if the move shows lower bounce rates.

## User Workflow
- Given I
    - Am a Veteran who was sent a Pre-Check-in link
- When I
    - Click on my Pre-Check-in link
    - Verify my identity
- Then I
    - See the action link that prompts me to answer questions at the top of the page
  
## Wireframes
https://share.goabstract.com/1030e909-2693-4afc-b5b3-b4ee2211089c

## Tasks
- [ ] [FE] Move Action Link on Pre-Check-in Intro Page per the wireframes but do so in a manner that will allow a certain percentage of users to see it where it exists today and a certain percentage to see it in the new location so that we can perform an A/B test
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by acrollet** [comment]
vets-api feature flag PR here: https://github.com/department-of-veterans-affairs/vets-api/pull/11750

**Comment by benbrasso-agile6** [comment]
@acrollet How are you thinking about (rather, how did you implement) loading the different versions of the /introduction page? 

Reason being, I think I'll need to way to track pageviews of each version AND clicks on the get started link, which currently has a GA event of: 

nav-check-in-pre-check-in-started-in-person
nav-check-in-pre-check-in-started-in-phone

**Comment by acrollet** [comment]
@benbrasso-agile6 I'm actually working on that this morning 🙂  Would it make the most sense to add a dimension for the link placement, rather than expanding the number of events? Not sure if we would have to get that set up by the analytics team.

**Comment by acrollet** [comment]
Hmm, I'm seeing suggestions that a custom dimension may not be approved. Could we:

1. add a pageview event when arriving on the introduction page, something like nav-check-in-pre-check-in-introduction-{top-link,bottom-link}
2. create [segments](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/google-analytics#GoogleAnalytics-Segments) based on the pageview events?

**Comment by benbrasso-agile6** [comment]
Notes: 

Interactions	Navigation - Unknown 	nav-check-in-pre-check-in-started-in-person-top-position
Interactions	Navigation - Unknown 	nav-check-in-pre-check-in-started-phone-top-position
1:53
nav-check-in-pre-check-in-viewed-introduction-top-position
nav-check-in-pre-check-in-viewed-introduction-bottom-position

**Comment by acrollet** [comment]
@benbrasso-agile6 @ytsaoca  I've set up these events and this is ready for review here: http://996867024757805a0fcac2c5fb5f2397.review.vetsgov-internal/health-care/appointment-pre-check-in/?id=38fe851f-73ae-4250-a286-17bb64741af8 (use patient twentysix to validate)

Let me know if this is good to merge and test on staging :-)

**Comment by benbrasso-agile6** [comment]
Shoot, I checked in to that appointment. Didn't mean to.

**Comment by benbrasso-agile6** [comment]
Created this bug ticket for FE. Not sure if it's specific to this feature. Doubtful, but FYI. https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/53562

**Comment by benbrasso-agile6** [comment]
@acrollet Can we review the GA events together? I feel like the implementation is different than what I'm used to, but I could be reading it incorrectly.

**Comment by acrollet** [comment]
@benbrasso-agile6 thanks for the catch, I don't think it's specific to this feature.

**Comment by acrollet** [comment]
@ytsaoca  Here's a new pre-checkin link, same validation instructions: http://996867024757805a0fcac2c5fb5f2397.review.vetsgov-internal/health-care/appointment-pre-check-in/?id=4b5631a2-3e50-468e-89ee-9650394a214b

**Comment by acrollet** [comment]
I went ahead and merged this - happy to do an update PR if we need any visual changes, the feature won't launch until we turn on the feature flag :)

**Comment by ytsaoca** [comment]
Hi @acrollet 
I couldn't open this link: http://996867024757805a0fcac2c5fb5f2397.review.vetsgov-internal/health-care/appointment-pre-check-in/?id=4b5631a2-3e50-468e-89ee-9650394a214b

**Comment by acrollet** [comment]
@ytsaoca @zach-park this can be tested on staging.va.gov now 🙂

**Comment by acrollet** [comment]
thanks @ytsaoca !
