### ISSUE TITLE
[UX] Update Product Artifacts for Release

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#52066]
## Description
Update various product artifacts, as necessary, based on the feature release.

## Tasks
- [ ] Update the Pre-Check-in Product Guide, including content and screenshots, if necessary
- [ ] Update the eCheck-in Product Guide, including content and screenshots, if necessary
- [ ] Update the Poster, if necessary
- [ ] Update user flow diagrams, if necessary
- [ ] Send updated screenshots to Danielle Thierry for the Resources & Support (R&S) articles in VA.gov, if necessary

## Acceptance Criteria
- [ ] Product Guides are up-to-date and ready to be pushed to production (content & screenshots)
- [ ] Poster is up-to-date and ready to be pushed to production
- [ ] ALL screenshots are of the highest quality possible
- [ ] [User flow diagrams are up-to-date](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/3Op54Vm) and ready to be pushed to production
- [ ] R&D articles are up-to-date

**Comment by kellysmith1008** [comment]
Testing location: https://vigilant-couscous-ab7fb4a4.pages.github.io/?baseUrl=http://fb317e98ddfef98bee03cab1cd5a3384.review.vetsgov-internal

**Comment by kellysmith1008** [comment]
I need to configure SOCKS on my computer for this update. Will complete configuration on Monday

**Comment by kellysmith1008** [comment]
Waiting for [my github ticket for SOCKs access](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52838) to be approved

**Comment by loripusey** [comment]
@kellysmith1008 Can you get the frontend folks to get you screenshots? We are planning to release on or about 2/8
cc @benbrasso-agile6 @sarahknoppA6

**Comment by benbrasso-agile6** [comment]
Brian can probably export a bunch of screenshots via cypress

**Comment by kellysmith1008** [comment]
@loripusey Yes ma'am - I'll ask. I'm meeting with Adrian and Christina today to see if we can get the SOCKs issue resolved. If not, I will reach out to @brianseek for screenshots and have the product guides ready to go by 2/8.

**Comment by kellysmith1008** [comment]
@loripusey We still aren't able to access SOCKs on our computers. @acrollet Would you mind posting the screenshots here for simplified header and footer so I can update the product guides?

**Comment by acrollet** [comment]
@kellysmith1008 no problem! mobile & desktop below, let us know if you need anything else 🙂 

![Screenshot 2023-02-06 at 13 24 28](https://user-images.githubusercontent.com/101649/217077469-5bb3d9a2-0bb6-432e-8af0-d91b9ed7c0ac.png)

![Screenshot 2023-02-06 at 13 24 38](https://user-images.githubusercontent.com/101649/217077458-2d771afc-dd06-453f-91a8-5d486afc66cd.png)

**Comment by kellysmith1008** [comment]
@loripusey The pre-check-in guide is complete. I will complete the check-in guide first thing tomorrow morning and close this ticket.

**Comment by kellysmith1008** [comment]
Pre-check-in and check-in guides for simplified header and footer are complete. Will publish on release
