### ISSUE TITLE
EKS deploy based on passing CI

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#52068]
## Issue Description
Currently vets-api EKS is deployed from [the k8s branch]( https://github.com/department-of-veterans-affairs/vets-api/tree/k8s). Currently the CI for deploying vets-api (ECR push and manifest update) still proceed, even if test/CI fails. We should make the “deploy” (ECR, manifest update) dependent upon successfully CI. This _IS_ already in place [here](https://github.com/department-of-veterans-affairs/vets-api/blob/k8s/.github/workflows/build.yml#L6-L9) and [here](https://github.com/department-of-veterans-affairs/vets-api/blob/k8s/.github/workflows/deploy.yml#L8-L11), but apparently conditional GHA ONLY works on the `master` branch . Since the EKS `“master”` branch is the `k8s` branch, we will just have to be mindful of this behavior during deprecation planning. It’s also possible that there’s another workaround, but from what I can tell, there isn’t.

---
## Tasks
- [x] (Ryan) Discover conditional CI solutions. 
- [ ] Put deprecation planning in place

## Success Metrics
- [ ] ADD SUCCESS METRICS HERE

## Acceptance Criteria
- [ ] The deploy and manifest update GHA's are dependent upon passing CDI
---

**Comment by laineymajor** [comment]
This needs to be completed post-golive of production.

**Comment by laineymajor** [comment]
Reviewing in sprint 26 for bandaid solution... then optimize in future project!

**Comment by laineymajor** [comment]
Needs to wait until K8s is merged in to master.

**Comment by rjohnson2011** [comment]
The best approach would likely be a conditional Github Action rendering since GHA are already integrated into our CI process and commonly used as an org-wide best practice. The following code block is a representation of what could be done:
```
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run CI tests
        run: <command to run CI tests>

      - name: Deploy to EKS
        if: ${{ success() }}
        run: <command to deploy to EKS>
```

**Comment by laineymajor** [comment]
This will carryover into next sprint. 
Blocked by merging K8s into master...
