### ISSUE TITLE
Create wireframe for check in confirmation page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#52072]
How might we... update the check in confirmation page to be consistent with the VAOS design? 

## Description 

A wireframe will need to be created for the check in confirmation page. Should it include the details link? Should it look more like the details page design? How might the introduction of travel reimbursement impact this decision? If the details link is included, what will the "back" navigation that links back to the confirmation page read? E.g., back to last screen, back to confirmation, etc. 

- "Back to today's appointments" the new wording for “Go to another appointment”
## Tasks

- [ ] Create wireframe(s). Could be 1 or 2 wireframes depending on the decision around the inclusion of the details link. 
- [ ] Added wireframe to existing branch. 
- [ ] Provide to CIE team for review. 

## AC 

- [ ] Wireframe(s) complete
- [ ] Wireframe(s) added to existing branch
- [ ] Approved by CIE team

**Comment by ytsaoca** [comment]
Mockups for review: https://share.goabstract.com/09599f96-94b9-43b8-bc3a-14aa0e2a737c

@zach-park @benbrasso-agile6

**Comment by zach-park** [comment]
Hi @ytsaoca , the confirmation page looks great. Regarding the details page, please note that the card design is being revised so it may need to be updated. (cc: @benbrasso-agile6 )

**Comment by benbrasso-agile6** [comment]
@ytsaoca awesome job making a decision on what should be included on that page. I left some comments in Abstract with some small content changes.

**Comment by zach-park** [comment]
Removed me as an assignee as @ytsaoca is leading on this task.

**Comment by benbrasso-agile6** [comment]
@ytsaoca how are the final revisions coming along for this ticket? It might be a good idea to prioritize finishing this ticket so engineering can complete the sprint/epic.

**Comment by ytsaoca** [comment]
Wireframes: https://share.goabstract.com/09599f96-94b9-43b8-bc3a-14aa0e2a737c

**Comment by ytsaoca** [comment]
Wireframes: https://share.goabstract.com/09599f96-94b9-43b8-bc3a-14aa0e2a737c

**Comment by benbrasso-agile6** [comment]
Left a couple comments in abstract

**Comment by loripusey** [comment]
@ytsaoca have @benbrasso-agile6 's comments been addressed? @brianseek is working on this and if we have changes we need to communicate them ASAP
cc @benbrasso-agile6 @sarahknoppA6

**Comment by benbrasso-agile6** [comment]
I don't think so yet. Ya-ching, can you check these: 

https://share.goabstract.com/779be73c-6954-4e54-ae61-d4dfa52d5fbc?commentId=df039364-618f-40c8-8875-d41a54363869&sha=1ece2fd1914a62b968f0eea794c1b116776f346f

https://share.goabstract.com/09599f96-94b9-43b8-bc3a-14aa0e2a737c?collectionLayerId=82596b54-458a-449d-a0b3-ab8734399331&mode=design

**Comment by ytsaoca** [comment]
@benbrasso-agile6 and @zach-park 

Updated the need help section of both confirmation page and the detail page. 
https://share.goabstract.com/cc52c8d4-6f30-4c96-9661-a410b7ce92aa?collectionLayerId&mode

**Comment by ytsaoca** [comment]
@benbrasso-agile6 and @zach-park 

Updated the need help section of both confirmation page and the detail page. 
https://share.goabstract.com/cc52c8d4-6f30-4c96-9661-a410b7ce92aa?collectionLayerId&mode

**Comment by loripusey** [comment]
@brianseek I believe you are currently working on the confirmation page? can you see @ytsaoca 's changes?

**Comment by benbrasso-agile6** [comment]
@ytsaoca looks good. During midpoint review, they asked us to add a period in the h1 on https://app.abstract.com/projects/ab30c34e-e2f9-4d3e-bb96-3b683b006c24/branches/a3583788-5f65-4962-aae2-668a5fbc14fd/commits/latest/files/585436fe-2120-45f4-b4f7-fbae01d258d9/layers/66FBBDC0-C4F9-4B7D-8E28-A8C85384BA69?collectionId=57e3f3ac-da49-4fb0-a8f1-c475407a73f1&collectionLayerId=5fc7acb6-bbcf-43f6-8972-8202437b5660

I would recommend making that update. 

You're checked in.

**Comment by ytsaoca** [comment]
@benbrasso-agile6 I thought that @kellysmith1008 confirmed that we only add a period in the h1 when there were 2 or more sentences, and we don't need a period when there is only one sentence?

**Comment by ytsaoca** [comment]
@benbrasso-agile6 I thought that @kellysmith1008 confirmed that we only add a period in the h1 when there were 2 or more sentences, and we don't need a period when there is only one sentence?

**Comment by kellysmith1008** [comment]
@ytsaoca I had seen that somewhere, but @benbrasso-agile6 pointed out there are already existing locations where this principle isn't in place. So to keep consistency, we should all the period here too.

**Comment by ytsaoca** [comment]
@benbrasso-agile6 and @kellysmith1008 

If we are adding a period for this page, do we also a period for all other pages, including sign-in page and the error pages, to keep them consistent?

**Comment by benbrasso-agile6** [comment]
Potentially. I remember Danielle provided some more specific feedback on when to use periods and when not to. So, I can pull up that documentation. 

But, I think we can review those other pages at another time.

**Comment by ytsaoca** [comment]
@benbrasso-agile6  Sure! Added a period. I'll close this ticket

'cc @loripusey

**Comment by ytsaoca** [comment]
@benbrasso-agile6  Sure! Added a period. I'll close this ticket

'cc @loripusey
