### ISSUE TITLE
[FE] Update Confirmation Page

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#52075]
## Assumptions
- We assume that we need to include both styling and the details page

## Wireframes
Wireframes: https://share.goabstract.com/09599f96-94b9-43b8-bc3a-14aa0e2a737c

## Tasks
- [ ] [FE] Update Confirmation Page per the wireframe
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by benbrasso-agile6** [comment]
@brianseek updated wireframes for check in confirmation page and details page https://share.goabstract.com/cc52c8d4-6f30-4c96-9661-a410b7ce92aa

One thing I did want to point out is, when accessing the details page from the confirmation page, you'll see a "You're checked in." alert. (See link above.) However, from the Your Appointments page, if an appointment has eCheck-in complete, then the message (currently in production) reads, "You checked in at xx:xx a.m. ET."

**Comment by brianseek** [comment]
@loripusey this is ready for validation on stage. The VAOS design changes are on in stage now. Not sure if you want to just close this ticket in favor of testing everything as a whole.

**Comment by loripusey** [comment]
I'll take a look now but we can close this ticket as there are testing tickets w/ TestRail test cases in the sprint as well.
