### ISSUE TITLE
[Support] Implement Tracking for VET TEC Preferred Provider Filters on GIBCT

### ISSUE THREAD

**Issue by nedierecel** [department-of-veterans-affairs/va.gov-team#521]
## User Story
As an Education platform team member, I need to navigate our analytics filters so I can understand how veterans are using my site.

## Goal
Education stakeholders wish to measure the impact of the new VET TEC 

## Acceptance Criteria

- [ ] Jon: Implementation requirements provided to BAH Front-End team for interactions on [GIBCT Landing Page]( https://staging.va.gov/gi-bill-comparison-tool)

| User Interaction | KPI | Implementation Approach | 
| --- | --- | --- |
| Count of “VET TEC Providers” as Institution Type | Unique and Total Events | See screenshot of gibct-form-change event in Resources as Example |
| Clicks to Learn More about VET TEC Training Providers | Unique and Total Events | See screenshot of gibct-learn-more event | 

- [ ] Implementation on [GIBT Search Results](https://staging.va.gov/gi-bill-comparison-tool/search?name=Atlanta&vetTecProvider=true) 

| User Interaction | KPI | Implementation Approach | 
| --- | --- | --- |
| VET TEC user engages with advanced search filters on Search Results Page | Site Search Categories | <Jon> | 
| Clicks with Learn More near Preferred Provider | Total Events, Unique Events | <Jon> |

- [ ] Implementation on [GIBCT Provider Page](https://staging.va.gov/gi-bill-comparison-tool/profile/2V000232)

| User Interaction | KPI | Implementation Approach | 
| --- | --- | --- |
| User views Preferred Provider Page | Unique Pageviews of Profile by User and Session | Custom Dimension and Custom Metric | 
| Interactions with Learn More Scholarships, Tuition & Fees, Housing Allowance | Total Events, Unique Events | Suggested dataLayer Naming Conventions: `event:gibct-learn-more, gibct-modal-displayed:<value> - Though the links are not executed via modals, that variable is available if you want to leverage it. See [GTM for GIBCT](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/639)|
| Interactions with Applications that Lead to VA links | Total Events, Unique Events | There is a `nav-` event, [Click Tag](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/639), and [Navigation Action Lookup table](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/639) in GTM |

- [x] Jon - Initial QA, Send GTM container for review
- [x] Nedie - Final QA and Publish
- [ ] Nedie - Share results with stakeholders via GA Reporting 

## Definition of Done
- [x] **Attached to a Milestone** 
- [x] **Attached to an Epic** 
- [x] **Labeled with Team** 
- [x] **Labeled with Practice Area** 
- [x] **Labeled with Type** 

## Resources
- This ticket is a follow up from https://github.com/department-of-veterans-affairs/va.gov-team/issues/477 
- InVision Screens: https://bahdigital.invisionapp.com/share/SFIAB2DX84W#/screens/296017563
- Example of dataLayer event standard for GIBCT Learn More Modals:
![GIBCT-Learn-More_Modal_Displayed.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/dc5e8dfd-8c53-4022-b78b-1327beabb769)
- Placements of Learn More on Profile Pages:
![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/18621537-2713-46d3-a872-11ad88659897)

**Comment by nedierecel** [comment]
@jonwehausen FYI - I am going to shift the milestone to the next sprint since it is due on 8/1/2019.

**Comment by jonwehausen** [comment]
Requested dataLayer insert for Landing Page.

**Comment by jonwehausen** [comment]
@amyknox 

Per our discussion, the Vet Tec learn more modal on the [comparision tool landing pag](https://staging.va.gov/gi-bill-comparison-tool/)e should populate with vetTec upon click with the following value in the dataLayer. 

```javascript
{
   event: "gibct-learn-more"
   gibct-modal-displayed: "vetTec"
}
```

**Comment by amyknox** [comment]
Thanks @jonwehausen - I opened a new issue on the BAH side (https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19384) for this update.

**Comment by nedierecel** [comment]
@jonwehausen Please see my round 1 of QA:

1. On landing page:
- When clicking on "Learn More" (without selecting the radio button yet), a `gibct-form-change` event is also triggered, which seems unexpected. See screenshot (recording also available that I couldn't attach here): 

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/13b431df-6e58-4016-b520-445456d0cb53)

2. On search results:
- `gibct-form-change` - Accurately tracking radio button on left rail
- `gibct-learn-more` - Accurately tracking "Learn More" on left rail

**Comment by jonwehausen** [comment]
@amyknox Screenshot above also representing the impact of the UX on dataLayer / tagging functionality.

**Comment by jonwehausen** [comment]
@amyknox @nedierecel 

Amy confirmed the newly expected behavior will be to ONLY display the modal upon 'Learn More' click (and not toggle the radio button). This should result in the learn-more dataLayer push and radio button toggle push being independent.

**Comment by nedierecel** [comment]
@jonwehausen Confirming I am seeing the following accurately trigger:

1. standardVetTecProvider: https://staging.va.gov/gi-bill-comparison-tool/profile/2V000122

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/f99ef79e-c0ce-4077-bd4c-ae6b2ac02e09)

2. preferredVetTecProvider: https://staging.va.gov/gi-bill-comparison-tool/profile/2V000305
![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/1f7f757c-a6cf-438a-8ed6-ac6250c803c0)

3. nonVetTecProvider: https://staging.va.gov/gi-bill-comparison-tool/profile/25386332
![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/6167eff6-63e2-4add-8473-85bcb0244689)

**Comment by jonwehausen** [comment]
Submitted approval for GTM publish @nedierecel.

**Comment by nedierecel** [comment]
@jonwehausen This has been published. I'm leaving in QA for post-launch validation.
