### ISSUE TITLE
Create Wireframe to Move icon inside the card

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#52106]
How might we... move the icon inside the card component. 

## Description 

Allison and Matt at design council asked that the icon in the card component variation be moved inside the card with the blue background that was proposed to the VAOS team. 

## Tasks

- [x] Adjust wireframe
- [x] Get approval from Matt and Allison via Slack 
- [ ] Update any experimental tickets as needed per Matt and Allison
- [x] Update the branch 
- [x] Share with CIE team and make sure the engineers are up to date
- [x] Share the change with VAOS team once Matt and Allison have approved

## AC

- [x] Wireframe created
- [x] Abstract branch updated
- [x] Matt and Allison approved 
- [ ] Updated any experimental tickets as needed per Matt and Allison
- [x] Sent to VAOS team as FYI 

## Deliverable

The card icon is updated based on the review with DS team (Matt, Allison) and VAOS team (Peter, Ciera). The latest style is committed to the latest VAOS abstract branch.

PCI version:
https://share.goabstract.com/04c09d9c-4153-4a14-b034-2e1ca094ebb0?collectionLayerId=69b4f976-44bd-4ae9-9526-42f29312ce3e&mode=design

CI version:
https://share.goabstract.com/4ff1e88b-7dd0-4aac-812c-1276630ffa7f?collectionLayerId=e5982697-1fd2-4b3d-8af0-e34b3cb33be5&mode=design

**Comment by zach-park** [comment]
The card icon is updated based on the review with DS team (Matt, Allison) and VAOS team (Peter, Ciera). The latest style is committed to the latest VAOS abstract branch. @benbrasso-agile6, @ytsaoca, @cgednalske, @kellysmith1008

**Comment by benbrasso-agile6** [comment]
@zach-park looks like you're using a different color for pre-check-in vs check-in. Would a Veteran expect them to be the same?

**Comment by benbrasso-agile6** [comment]
Looks good now. LGTM

**Comment by zach-park** [comment]
Sounds great, @benbrasso-agile6. And yes they should be the same color (I think there might have been a delay with the browser cache).

**Comment by zach-park** [comment]
@benbrasso-agile6 could you let me know if we need to update the experimental tickets for this task also?

**Comment by zach-park** [comment]
@acrollet @brianseek , please note the style change to the card UI (e.g., the bg color of the icon is updated to #112e51).

**Comment by benbrasso-agile6** [comment]
Yeah, I was thinking about that Zach. If you want to just leave this in Validate for now, I'll give it some more thought.

**Comment by loripusey** [comment]
LGTM

**Comment by loripusey** [comment]
@benbrasso-agile6 find out from Matt if we need to update the experimental ticket
