### ISSUE TITLE
[PM] Authenticated experience: Documentation audit

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5210]
## Background

Our documentation has not been updated in the last few months. We need to go through the authenticated experience documentation, figure out what needs to be updated and by whom, and get our documentation in order.

## Tasks

- [x] [Create a spreadsheet of all documentation that we need to update](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/product-management/Auth%20exp%20documentation%20audit_Feb%202020.xlsx).
- [x] Determine who should update documentation and when.
- [x] Create tickets as necessary for people to update the documentation.

## Acceptance criteria

- [x] Documentation is reviewed, and there is a plan in place to get it updated.
