### ISSUE TITLE
[FE] Move Icon inside of Card

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#52114]
## Wireframes
The card icon is updated based on the review with DS team (Matt, Allison) and VAOS team (Peter, Ciera). The latest style is committed to the latest VAOS abstract branch.

PCI version:
https://share.goabstract.com/04c09d9c-4153-4a14-b034-2e1ca094ebb0?collectionLayerId=69b4f976-44bd-4ae9-9526-42f29312ce3e&mode=design

CI version:
https://share.goabstract.com/4ff1e88b-7dd0-4aac-812c-1276630ffa7f?collectionLayerId=e5982697-1fd2-4b3d-8af0-e34b3cb33be5&mode=design

## Tasks
- [ ] [FE] Move icon inside of card
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
