### ISSUE TITLE
[FE] Display Facility Address with Other Appointment Information

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#52132]
## Tasks
- [ ] Display Facility Address with Other Appointment Information
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [x] Review code in PR
- [x] Run branch locally
- [x] Check that new and updated translations use new keys
- [x] Check for hardcoded strings

**Comment by loripusey** [comment]
@wullaski is this out in production? I saw it's been merged but this is still in progress. Wanted to know if I can do a release note for it or not.

**Comment by loripusey** [comment]
LGTM
@benbrasso-agile6 did you want to validate this?

**Comment by benbrasso-agile6** [comment]
How are we testing? Which clinics in staging have a facility address?

**Comment by wullaski** [comment]
@benbrasso-agile6  I checked earlier for clinic 451
![staging va gov_health-care_appointment-pre-check-in_appointment-details_38355-530](https://user-images.githubusercontent.com/2982977/235475907-fa8360e6-eef1-4ef5-84da-3529dd477c42.png)

**Comment by benbrasso-agile6** [comment]
Found one... looks good. 

Wondering if we could get back into posting in slack when a ticket is ready to validate? That will allow other team members to, 1) validate, and 2) be aware of the work.

**Comment by loripusey** [comment]
We can also call out things that are ready to validate during stand up.
