### ISSUE TITLE
[FE] Profile | Mobile App | Copy updates to Gender Identity Screen

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-team#52130]
## Background

The Mobile team is adding 2 lines of copy to their gender identity field (after the screen title) to help address the issue of a person not being able to remove this field (go back to null).

Danielle has approved this copy and asked for the Mobile team to share with Profile team so that VA.gov can be aligned w/ the mobile app. 

Here's the Slack thread containing that request: https://dsva.slack.com/archives/C909ZG2BB/p1673975468384139

Here's a screenshot of the mobile app Gender Identity screen: 
![Screen Shot 2023-01-17 at 11.48.03 AM.png](https://images.zenhubusercontent.com/60d0d1089008de03071a6d10/5103770b-a074-4332-8feb-430247faf2b9)

Here's a screenshot of the additional info accordion for Gender Identity (expanded view):
![image (4).png](https://images.zenhubusercontent.com/60d0d1089008de03071a6d10/3e7be05e-f9c9-4631-b840-207165a7870a)
(collapsed view):
![image (5).png](https://images.zenhubusercontent.com/60d0d1089008de03071a6d10/041544c6-a1a7-45d2-9a96-e17ffe4c1d39)
## Tasks
- [ ] FE: please add tasks as appropriate

## Acceptance Criteria
- [ ] Design updates have been implemented in the front end - [see Design ticket # 52129](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/gh/department-of-veterans-affairs/va.gov-team/52129)
- [ ] Please add other AC, as appropriate

**Comment by Samara-Strauss** [comment]
Noting that all Sketch files have been updated in #52129, though I don't think that should affect this implementation ticket.

Actually, @andaleliz when you are back, can you drop the copy into this ticket so it's copy/pasteable? I don't want Adam to have to try to type out the copy from screenshots.

**Comment by andaleliz** [comment]
@Samara-Strauss sure can! 

> You can change your selection at any time. If you decide you no longer want to share your gender identity, select Prefer not to answer.

> Sharing your gender identity in your VA.gov profile is optional. If you get health care at VA, this information can help your care team better assess your health needs and risks. 
But you should know that any information you share in your VA.gov profile goes into your VA-wide records. VA staff outside of the health care system may be able to read this information.
We follow strict security and privacy practices to keep your personal information secure. But if you want to share your gender identity in your health records only, talk with your health care team.

**Comment by mtcA6** [comment]
@andaleliz is the gender identity feature in production? I feel like in one of the onboarding sessions it was mentioned that it was on hold.

**Comment by andaleliz** [comment]
@mtcA6 I'm honestly not sure off the top of my head, but the use case docs should always reflect whatever is live on the site. Logging into staging is also a safe way to check 99% of the time (the 1% exception is when something is on via a feature flag, but that's rare). Do you need me to pull up those links for you?

**Comment by mtcA6** [comment]
@andaleliz oh right, I forgot the use cases exist on those pages from the orientation ticket. Thanks for the reminder!

**Comment by andaleliz** [comment]
Sure thing! Let me know if anything is unclear or you have more questions about it.

**Comment by adamwhitlock1** [comment]
Pronouns and Sexual Orientation fields are on hold until further notice. We launched Gender Identity and Preferred Name for the original MVP of personal info page.

**Comment by adamwhitlock1** [comment]
@mtcA6 This is ready to validate.

Design file to reference is [here](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/4ajJxKZ)

Staging looks like this right now:
![Screenshot 2023-08-10 at 8.10.35 AM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/7c2bed78-c8a5-4aaa-b0d9-b15bc3a2e961)

**Comment by mtcA6** [comment]
Can we make the "Prefer not to answer" bold?

**Comment by adamwhitlock1** [comment]
We can but that is not what our current design spec has present.

![Screenshot 2023-08-10 at 12 24 39 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/047a9ccf-15e5-475f-8a83-40a9593e34ea)

If @pamela-drouin or @andaleliz wants to make the call as to whether or not it should be bolded, then I can make it so.

**Comment by mtcA6** [comment]
![image.png](https://images.zenhubusercontent.com/643d7b45c9629eadf8090613/08f74a86-a647-4648-b8af-aa00ab8ba30f)

we should match to what the mobile team is doing i think

**Comment by Samara-Strauss** [comment]
I agree with the bolding to be consistent across platforms. @pamela-drouin could you make this update in the mocks?

**Comment by pamela-drouin** [comment]
@Samara-Strauss Happy to make the update!

**Comment by pamela-drouin** [comment]
@adamwhitlock1 both desktop and mobile mocks have been updated!

**Comment by adamwhitlock1** [comment]
I have updated the code and it is now available on staging.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZU09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5a05743d95a22bba614a352551bc30d8c3d1bcf4/Screenshot%202023-08-11%20at%205.28.42%20PM.png)

**Comment by Samara-Strauss** [comment]
Validated with user 226! Looks great!

**Comment by adamwhitlock1** [comment]
I will close this now.
