### ISSUE TITLE
[FE] Active Appointment Selection

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#52131]
## Tasks
- [x] Explore how to make the back button for appt details pages & for the confirmation page on day-of check-in
- [x] Use router and appointment ID `/appointments/:appointmentId` to display appointment details
- [x] Remove the `setSelectedAppointment` dispatch handler
- [ ] Avoid passing router down into component tree by creating a hook to handle appointment Check In button click and pass that to the `CheckInButton` component on the list and details views
- [x] Create or update unit tests
- [x] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Discussed in slack DM between John and myself: We should look at moving the check-in click call to a util and pass the onClick handler in an effort to remove need for the `appointmentActionVaos` component all together. Moving the appointmentIen to the url should eliminate the need for a dispatch.

**Comment by brianseek** [comment]
I'm going to move the above comment and this task `Avoid passing router down into component tree by creating a hook to handle appointment Check In button click and pass that to the CheckInButton component on the list and details views` to its own ticket since the changes already in the ticket were far reaching

**Comment by brianseek** [comment]
new ticket: https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/53050

**Comment by brianseek** [comment]
@loripusey this is ready for validation. Not sure if there is anything to really validate beyond that everything is working since there are no visible changes. Feel free to close this or if you want to validate you can run through pre-check-in and day-of and verify that it works and that you can reload the page at the complete page. Also that the url has the appointmentIen-stationNo in the url at complete

**Comment by loripusey** [comment]
closing
