### ISSUE TITLE
KM Article Audit and Update

### ISSUE THREAD

**Issue by starlow00** [department-of-veterans-affairs/va.gov-team#52149]
## Issue Description
_As part of our VEO KM article audit, we will be making regular updates to KMs. Our goal for this sprint is to review and update at least 1 KM._

---
## Tasks
- [ ] _ Review and update at least 1 KM_

## Acceptance Criteria
- [ ] _At least 1 KM is updated_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x ] **Attached to an Epic** (what body of work is this a part of?)
- [x ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by starlow00** [comment]
closed, duplicate

**Comment by starlow00** [comment]
Incorporating VEO suggestions, on schedule for GI Bill KM for current sprint

**Comment by starlow00** [comment]
This project is temporarily shifting to Quick Reference Guides per VEO request; will revive this in a future sprint
