### ISSUE TITLE
[Design] 10-10CG - Facilities: Refined A/B/C desktop and mobile mock-ups

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#52140]
## Issue Description
After meeting with 1010 team and getting accessibility feedback, create desktop and mobile designs 
[#49084](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49084)

---
## Tasks
- [x] Meet with Accessibility: Collab Cycle Office hours, Wed 1/18
- [x] Review if card selection, style variations and selected states have accessibility concerns.
- [x] Based on feedback, meet with team and decide directions to use in A/B/C test
- [x] Update Sketch designs for mobile and desktop to include all states/filters/pages of the facility questions
- [x] Create user flow/wireflow of options that will be included in test
- [x] Prep all files for Design Intent

## Acceptance Criteria
- [ ] Design artifacts ready for Design Intent / Collab Cycle
---

**Comment by nicko-amida** [comment]
We learned in our collab cycle office hours meeting that we have a [tiled radio button component](https://design.va.gov/storybook/?path=/docs/components-va-radio--default#tiled) already in Storybook - this is a likely pattern update.

**Comment by jessicastump** [comment]
Updates post meeting 2/21/23:

- [Wireflow](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/dlyed5l) of updated direction

- Search input - [mobile design](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/dlyemEb) and [desktop design](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/jgnAQyo)
- Search results - [mobile design](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/DP3J1EJ) and [desktop design](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/zx9e3Yb)
- Search selected - [mobile design](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/v8VZMbM) and [desktop design](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/zx9e3Yb)
- Confirmation - [mobile design](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/eKPGDyq) and [desktop design](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/4aRZWrd)
