### ISSUE TITLE
Remove practice area check boxes for Staging Review

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#52143]
## User Story
As a Governance team member, I don't want to have to check a separate box in the Staging Review section of the Collaboration Cycle Request template confirming that I completed by Practice Area review. 

Assignee: @sterkenburgsara 
Peer Reviewer: @allison0034 

## Description
The practice area checkboxes under Staging Review in the Collaboration Cycle Request template feel a bit redundant. We should remove the checkboxes (which are often overlooked and forgotten) ~~and explore new ways of communicating to the VFS team that each practice area completed their review.~~
Note: team decided that no replacement solution was necessary

## Impacted Artifacts
* Staging review template

## Tasks
- [x] Remove practice-area specific checkboxes from [staging review code block](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities) in the Collaboration Cycle Kickoff Moderator Responsibilities guidance

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team knows that submitting their feedback to the Drafting Template and checking the box within the template is sufficient for communication completion of review internally
- [x] VFS teams no longer see individual practice area review checkboxes in their Staging Review codeblock

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by sterkenburgsara** [comment]
@allison0034 I removed practice-area check boxes from the staging review code block. Can you review and okay this when time allows? Thank you!

**Comment by allison0034** [comment]
@sterkenburgsara looks good to me! If this has not been assigned an estimate or to this sprint please do so and then close the ticket. : )
