### ISSUE TITLE
Draft new content tip (S20)

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#52154]
### Tasks

- [x] Pick a content tip idea from the style guide

- [x] Draft a content tip Slack post, similar to the first one posted on Thurs, Jan 5: https://dsva.slack.com/archives/CL181NRJQ/p1672938003050849

- [x] If needed, get feedback from rest of Content team

- [x] Copy and paste the team-approved announcement of our Tip of the Sprint in to the platform-content slack channel.

- [x] Schedule for first Monday of the sprint at 1pm ET

Reminder: Add a line to engage with the post if they find the tip helpful.
