### ISSUE TITLE
(Samara) Update team deploy docs with #platform-content info

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#52163]
### Tasks

Based on the recent change to archive #platform-confluence:

- [x] Decide when to start posting deployment announcements on #platform-content

- [x] Start updating announcement on #platform-content

- [x] Update any internal team instructions from #platform-confluence to #platform-content found here: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2098200622/Platform+Content+team+deployment+instructions
