### ISSUE TITLE
Refine Staging Review QA operational guidance

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#52166]
## User Story
As a Governance team member, I want to have be able to see a clear, documented process of how QA completes a Staging Review so that we can ensure the process is repeated consistently for each Staging Review.

Assignee: @it-harrison 
Peer Reviewer: @CherylEvans 

## Description
The Document Feedback section of the How to complete a QA review for Staging review touchpoint guidance is not complete. The 3rd bullet is no longer applicable, and the first bullet needs to be expanded upon. The statement, "Always document whether the team has met the QA Standards by completing a [QA Collab Cycle Feedback for Staging](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-feedback%2C+QA%2C+Staging&template=collab-cycle-qa-feedback-staging.md&title=QA+Standards+-+VFS+Team+-+VFS+Product) ticket." is not sufficient. There is no information about adding labels, linking to the epic, inputting team and product information etc. This should all be documented in our operational guidance.

Note: I am aware that there are instructions in the [QA Collab Cycle Feedback for Staging](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-feedback%2C+QA%2C+Staging&template=collab-cycle-qa-feedback-staging.md&title=QA+Standards+-+VFS+Team+-+VFS+Product) gh template, however these are still not complete. I would prefer if more detailed, but parallel, guidance was added to the Confluence guidance.

## Impacted Artifacts
[How to complete a QA review for Staging review touchpoint](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2428010558/How+to+complete+a+QA+review+for+Staging+review+touchpoint)
[QA Collab Cycle Feedback for Staging](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-feedback%2C+QA%2C+Staging&template=collab-cycle-qa-feedback-staging.md&title=QA+Standards+-+VFS+Team+-+VFS+Product) gh template

## Tasks
- [ ] Document a step by step approach for completing the gh ticket
- [ ] Ensure there are steps for adding all applicable labels, including the` launch-blocking` label
- [x] Establish a QA Standards label that will be added to all QA Standards feedback tickets
- [ ] Confirm that the directions in the gh template and the Confluence guidance are in parallel and there are no inconsistencies
   - [ ] The gh template guidance may also need to be updated

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] The QA process for completing a Staging Review and documenting adherence to QA standards is clear and can be repeated consistently for each Staging Review

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
Hi @CherylEvans this issue is ready for review - here is a [link to a draft of the How to Complete a Staging touchpoint](https://vfs.atlassian.net/wiki/spaces/~853060520/pages/2497970177/Copy+of+How+to+complete+a+QA+review+for+Staging+review+touchpoint) and here is an [updated gh template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-feedback%2C+QA%2C+Staging&template=collab-cycle-qa-feedback-staging.md&title=QA+Standards+-+VFS+Team+-+VFS+Product)

**Comment by CherylEvans** [comment]
@it-harrison I made some recommendations for your [draft](https://vfs.atlassian.net/wiki/spaces/~853060520/pages/2497970177/Copy+of+How+to+complete+a+QA+review+for+Staging+review+touchpoint) How to complete a staging touchpoint. Since the guidance from your draft above directly impacts the changes to the gh template, I will hold off reviewing that until we get the confluence guidance ironed out.  Please let me know your thoughts, or if you'd like to discuss. :-)

**Comment by it-harrison** [comment]
@CherylEvans I have incorporated your feedback into the [draft](https://vfs.atlassian.net/wiki/spaces/~853060520/pages/edit-v2/2497970177). Thanks!

**Comment by CherylEvans** [comment]
@it-harrison Thank you, Ian. I capitalized a few more bullets that were still lowercase.  Should Manual Testing be an H2?  You have it as an H3. I wasn't sure.  I tweaked a few things, but the [draft](https://vfs.atlassian.net/wiki/spaces/~853060520/pages/2497970177/Copy+of+How+to+complete+a+QA+review+for+Staging+review+touchpoint) looks good.  Please let me know when the gh template is ready to review. :-)

**Comment by it-harrison** [comment]
@CherylEvans I meant for the Manual Testing to be an H3 because it is a step in the Conduct your Review section. The [gh template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-feedback%2C+QA%2C+Staging&template=collab-cycle-qa-feedback-staging.md&title=QA+Standards+-+VFS+Team+-+VFS+Product) has also been updated. Thanks!

**Comment by CherylEvans** [comment]
@it-harrison I capitalized the last bullet on the gh template (Launch-blocking label...) Should be good to go!
Thanks, Ian.

**Comment by it-harrison** [comment]
Thanks @CherylEvans - closing as completed.

**Comment by CherylEvans** [comment]
@it-harrison Just a reminder to check off all of the boxes above before closing a ticket.  I checked them for you. :-)
