### ISSUE TITLE
Add documentation to onboarding docs about how to get access to Mural

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#52174]
## User Story
As a person onboarding to VA.gov product teams , I need to know how to get access to Mural so I can use that tool for my product work.

Assignee:
Peer Reviewer:

## Description
We need to add documentation to the onboarding docs about how to be added as a member to the VA Enterprise Mural account.

**Here's the process:**
- A DOTS request needs to be submitted via this URL:[vajira.max.gov/servicedesk/customer/portal/1/create/18](http://vajira.max.gov/servicedesk/customer/portal/1/create/18)
  - I tried logging into DOTS with my email address but I have no idea what my password would be so I'm only able to get in with a PIV card. Idk if PIV is actually required to do this, but a va.gov email address most definitely is.
- It's ideal if the person requesting access submits the request so they can be notified of updates, but someone can do it on their behalf.
- A person will need access to their va.gov email address to be added as a member.
- The request needs to include the va.gov email address, and the person's full name.
- Expected turnaround time on the DOTS request is a few business days.
- Once a person is added, they'll get an email from Mural saying they've been added and they can set up their account that way.

NOTE: once process above is confirmed, we will modify this ticket to include information for updating Platform Website.

## Tasks
- [ ] _Placeholder task_

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Docs about getting access to Mural are published so new team members can access them
- [ ] This is included in the "request for tools" part of onboarding (either docs and/or issue template)

**Comment by andaleliz** [comment]
@shiragoodman I got all the info from Angela, and have the process outlined.  Can you (or someone on your team) see if you can log into that website w/out a PIV card? I'm not sure if it's actually required or if it's just me.

**Comment by shiragoodman** [comment]
thanks, @andaleliz . We'll look into this.

@allison0034 would you be able to test out the process Liz outlined above? Please let me know!

**Comment by allison0034** [comment]
@shiragoodman I do not have access to that site.

**Comment by andaleliz** [comment]
@allison0034 even with your piv card? Can you try [this one](https://login.max.gov/cas/login?service=https%3A%2F%2Fportal.max.gov%2Fhome%2Flogin%2Fcas) with your PIV (or email if you know what the PW would be)?

If you can get into the 2nd one, and then click the first link, it should take you to a form.

**Comment by allison0034** [comment]
I tried with the PIV card and this is the screen I get.
<img width="991" alt="Screen Shot 2023-01-26 at 2 19 12 PM" src="https://user-images.githubusercontent.com/72398073/214929615-8d3a6145-2175-4fb9-9d09-c5a06046f61c.png">

**Comment by andaleliz** [comment]
Oh ok - I don't remember going through a registration process but it's been a long time since I first got access. If you're comfortable with it, can you give it a try and see if that allows you to get in?

**Comment by allison0034** [comment]
@andaleliz I am still working on this : (  it asking lots of registration stuff, let me chat with Shira and I will get back to you.

**Comment by shiragoodman** [comment]
@andaleliz The [Mural](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-Mural) section was added to Request access to Platform Tools on the Platform Website. I believe this satisfies your original request. If you have further questions, please contact @naomimarcussen as she likely has more context.
