### ISSUE TITLE
Create Metrics page for tracking VFS-Change-Announcements channel usage and learnings

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#52176]
## Purpose
Schedule the tasks to accomplish FY2023 Initiatives

## Tasks
- [x] create [page](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2491613369/Metrics+for+the+VFS-Change-Announcements+slack+channel)
- [x] create layout, establishing prose
- [x] begin to set out desired metrics and spaces for them
- [x] begin to consider insights

## Acceptance Criteria
- [x] Metrics page is available to SDT
- [x] Metrics are compiled
- [x] Insights section is established
