### ISSUE TITLE
Remove alert from download debt letter page.

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#52177]
## Issue Description
Alert highlighting incorrect repayment plans can now be removed. 
![Screenshot 2023-01-18 at 11.46.12 AM.png](https://images.zenhubusercontent.com/5f7f60ca14e26c658f77b9f5/3c7fdf62-f2a5-4b7b-9c3e-71720e8d9b04)

**Alert can be found on the debt-balance/letters page:**
https://staging.va.gov/manage-va-debt/summary/debt-balances/letters
https://va.gov/manage-va-debt/summary/debt-balances/letters

![Screenshot 2023-01-18 at 11.45.44 AM.png](https://images.zenhubusercontent.com/5f7f60ca14e26c658f77b9f5/618cf377-1784-42bf-a845-0623f0ab65fa)

---
## Tasks
- [ ] remove alert component

## Acceptance Criteria
- [ ] Alert has been removed and screen no longer appears in production.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
