### ISSUE TITLE
Asynch discovery of Midpoint Review challenges

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#52170]
## User Story
As a Governance team member, I want to spend time reviewing the Midpoint Review process and documenting any challenges I may face so that my team can come up with a plan for prioritizing and addressing the known issues. 

## Description
A few of the identified issues in the Governance team [initiative for refining and improving guidance for the Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/40002) were also applicable to the Midpoint Review. However, there are unique challenges to the Midpoint Review that need to be addressed.

The purpose of this ticket is to complete an asynch discovery session for the Midpoint Review in order to identify the top challenges Governance team members, and potentially VFS, are facing.

After the challenges are identified, similar challenges will be grouped, voted on, and then solutions will be proposed.

## Impacted Artifacts
[Midpoint Review - asynch workshop](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1673977851275/ed5f4d14afab24df552905158b06374adead0cc3?sender=u0574179b1d97118ccc0e3591) Mural board

## Tasks
- [x] Shira to share the board on the #platform-governance-team Slack channel
- [x] From 1/19-1/27, spend at least 15-20 minutes documenting in the Mural board above the challenges you have observed and/or faced with regards to the Midpoint Review process.
   - Note: the different sections, colored cards, etc. in the mural are not set up as strict guidelines. Their only purpose is to help inspire thought. There is no requirement to add a card to each section, and it is very likely there will be overlap between various sections.
- [x] On 1/30, @shiragoodman will group similar challenges
- [ ] Prioritize, and propose solutions for addressing the challenges
   - 1/31 note: due to limitations in schedule, prioritizing and proposing solutions will take place at a later 
date.
   - 2/13 note: workshop scheduled for 2/17 at 10:30am ET
## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have a prioritized list of problems and proposed solutions for the Midpoint Review.

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by humancompanion-usds** [comment]
My unsolicited $.02 thoughts for your consideration. As a designer, when I present my work I make a point of articulating what I want feedback on. I've noticed some teams do this and some do not at different stages. (The opposite of this is the "Real Estate" tour where the designer just names all of the things on the page.) Usually design intent has requests for more targeted feedback and midpoint, less so. That seems like a natural progression. However, I still find it useful if teams check back in with what they might still be struggling with at midpoint review. How might we encourage all teams to be clear about where they really want focus and do that consistently? I personally would find it helpful to have this in advance of reviewing the work. Not that I won't look at all of the work. But if I know to focus in on particular things then that feels more useful for all involved parties. This seems to happen organically at the moment. Is there a way to make that part of the process (perhaps it is and I'm just not aware). Anyway, curious what others think.

**Comment by shiragoodman** [comment]
thanks for sharing, @humancompanion-usds ! I added your "how might we" question to our mural board with a link to the full comment.

**Comment by CherylEvans** [comment]
@shiragoodman I have added my input to the mural board.

**Comment by it-harrison** [comment]
@shiragoodman feedback added

**Comment by allison0034** [comment]
My feedback has been added.

**Comment by shiragoodman** [comment]
Prioritization workshop scheduled with team for Friday 2/17. During this workshop, grouped pain points will be prioritized, and problem statements and solutions will be proposed. This will help us identify next steps for the overall initiative.

**Comment by shiragoodman** [comment]
The scope of this ticket has grown. In order to not enable scope creep, the "prioritize and solution proposal" steps of this ticket will be moved to another ticket - #53694.
