### ISSUE TITLE
[Design] [Content] Change headings in check in and pre check in to better support screen readers

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#52173]
How might we... update our apps (with a focus on headings) to better support screen readers? 

## Description 

Specifically, look to update the headings to be more semantic on the appointment list pages across both check in and pre check in. 

## Tasks

- [ ] Update wireframes with new heading styles
- [ ] Create documentation for code that needs to be included on pages
- [ ] Create new abstract branch
- [ ] Review it with Josh Kim
- [ ] Share with CIE team 

## AC 

- [ ] Wireframes created
- [ ] Documentation created that engineers will use
- [ ] Abstract branch is created
- [ ] Josh Kim has reviewed
- [ ] CIE team has reviewed 
- [ ] Lori to create tickets for FE

**Comment by ytsaoca** [comment]
I'm not sure if user want to go back to VA home page. Prefer not include the 2 links to make the page clean.

Any thoughts?
![Error (General) Copy.png](https://images.zenhubusercontent.com/6148b41faabf78b679dbacff/d556eace-e60c-4a86-91f1-257adc183c1a)![Error (Expired) Copy.png](https://images.zenhubusercontent.com/6148b41faabf78b679dbacff/7655bb42-d4cb-4d4b-b9c7-a64cd8b1e7e5)

**Comment by benbrasso-agile6** [comment]
I think this is the wrong ticket. But, it looks like you’re using content from an older version that Kelly worked on. She has a newer version. Maybe you guys can work together on it tomorrow.

**Comment by ytsaoca** [comment]
Yes, realized that I posted in the wrong ticket so I deleted the message.🤣
