### ISSUE TITLE
Incorporate feedback on Public Websites intake form

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#5218]
## Background
Teams come to the VSA Public Websites teams with a variety of requests. Managing this

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [x] Obtain PW internal (content, tools)
- [ ] Obtain and incorporate feedback from external teams:
  - [x] Benefits & Memorials 1 
  - [ ] Benefits & Memorials 2
  - [x] eBenefits
  - [ ] Facilities 
  - [ ] BAH
 -  [ ] Peggy/VSP Content

## Acceptance Criteria:
* Approved intake form is live as a template request in ZH, and circulated with external teams

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/public-websites-intake.md

**Comment by MickinSahni** [comment]
Won't estimate this one even though we're gonna solicit feedback from folks on the PW team.

**Comment by MickinSahni** [comment]
@LouCarlozo63 this is the template we're circulating for your awareness
