### ISSUE TITLE
Medallia/Contact Center Data Review for VA.gov IA and Navigation

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#52186]
## Issue Description

[Research initiative outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/ia-and-navigation/2023-generative-logged-in-research#readme)

An OCTO cross-team effort is working to improve the IA and navigation of VA.gov, particularly for authenticated users. To inform this work, an analysis will be created of Medallia and Contact Center data to learn what challenges people report have navigating/finding tasks and tools on VA.gov, especially while signed in. 

More details on the goals of the Medallia/Contact Center data review can be [found here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ia-and-navigation/2023-generative-logged-in-research/medallia-call-center-review.md).

---
## Tasks
- [x] Generate Medallia dataset focused on keywords and sentiment analysis
- [x] Generate contact center dataset based on identified categories 
- [x] Conduct analysis on responses
- [x] Document analysis to share with broader IA research effort

## Acceptance Criteria
- [ ] Create Github document with findings and recommendations in the 2023-generative-loggedin-research folder.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
@clantosswett do we have any idea on call center categories we want to pull from?

I attached a screenshot of all the sub-categories we have listed in DOMO.

![Screen Shot 2023-01-19 at 9.04.03 AM.png](https://images.zenhubusercontent.com/5f8db741ece9322d39872b91/fe51bdfb-e1ae-4ead-90dd-99a32651ded9)

**Comment by Samara-Strauss** [comment]
@clantosswett my two cents -- include categories of tasks/tools on VA.gov in case people report that they couldn't find them or they were hard to find.

**Comment by ianMcCullough-ob** [comment]
@Samara-Strauss, sounds good! I'll do some digging and see what makes the most sense.

**Comment by ATMiddleton** [comment]
@ianMcCullough-ob in the process of completing audit.  More information to follow

**Comment by ianMcCullough-ob** [comment]
[WIP audit](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/contact-center/medallia-audits/IA-navigaion.md)

**Comment by Samara-Strauss** [comment]
Thank you for this, @ianMcCullough-ob! This is super helpful so far. Since you mentioned it's still a WIP, do you have an estimate on when this will be wrapped up?

**Comment by ianMcCullough-ob** [comment]
@Samara-Strauss There are a few minor tweaks I need to make, but it's primarily WIP due to the fact that I'd like to review it with Chante. However, I'd say it's 99% done. I did make a few additions to the DOMO dashboard that I'd like to review in person. Would you like to meet to review the final audit and dashboard soon?

**Comment by Samara-Strauss** [comment]
Sure! Could we meet Monday or early next week?

**Comment by ATMiddleton** [comment]
@clantosswett will schedule meeting to continue discussion.

**Comment by ATMiddleton** [comment]
@clantosswett - awaiting Chante's review and approval.

**Comment by ATMiddleton** [comment]
Awaiting additional resource assignment.  Team member to be identified.

**Comment by ATMiddleton** [comment]
@ianMcCullough-ob met with Liz and reviewed all data.  Will continue to work with @clantosswett to close ticket.

**Comment by ATMiddleton** [comment]
Complete and close.
