### ISSUE TITLE
Add new assignee to the Privacy, Security, Infrastructure, Readiness Review gh ticket and update PW linke

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#52183]
## User Story
As a VFS team member, I want to be sure the Privacy and Security gh ticket is assigned to the correct person so that I am not blocked and/or delayed from launch.

Assignee:
Peer Reviewer:

## Description
Gary Fallon will be supporting the Privacy, Security, Infrastructure, Readiness Review within the Collaboration Cycle. We need to ensure he is made aware of any new requests, so the purpose of this ticket is to add his gh handle to the template and update the link on PW.

## Impacted Artifacts
[Privacy, security, infrastructure readiness review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/privacy-security-infrastructure-readiness-review) touchpoint page
[Privacy, Security, & Infrastructure Readiness Review ](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/new?assignees=td-usds%2C+troymosher&labels=security-review&template=privacy-and-security-review.md&title=Readiness+Review+%5BTeam-Name%2C+Feature-Name%5D)gh ticket

## Tasks
- [ ] Assign Gary Fallon to the gh template and publish to master 
   - @andreahewitt-odd please notify us when Gary has been added to the VA Gh Org and is a member of vets.gov-write. Please also share his gh handle
- [ ] When published, copy the url/link to the template with Gary as assignee
- [ ] Update the link to the template on the touchpoint page with the new link. Publish to Platform Website

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Gary is the assignee on any new  Privacy, Security, Infrastructure, Readiness Review tickets

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@briandeconinck has been removed as the peer reviewer, and @CherylEvans has been added as his replacement. Explanation is provided in the[ comment of ticket #51711. ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/51711#issuecomment-1397105355)

**Comment by allison0034** [comment]
@andreahewitt-odd I want to confirm Gary Fallon has been added to  vets.gov-write and his GH handle is gary-fallon. Is this correct?

**Comment by shiragoodman** [comment]
gary-fallon is correct. And yes, he's been added to vets.gov-write

**Comment by allison0034** [comment]
@CherylEvans this is ready for your review. You can review the change on [this page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/privacy-security-infrastructure-readiness-review).

**Comment by CherylEvans** [comment]
@allison0034 I have verified the url/link to the template with gary-fallon as assignee, looks great. Peer review complete.
