### ISSUE TITLE
[eFSR] Cards, Mini Summary, Add - Midpoint Review Updates

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#52196]
## Issue Description
Midpoint Review feedback from 1/17/23
Design #52052, IA #52104 and Content #52103
---
## Tasks
**Design**
- [x] Update how card is styled to [card styles explorations](https://www.sketch.com/s/be292806-8dbf-4201-bfa7-0edbba103347/p/8E62D47D-F38C-4727-8E27-B5DF3424F12F/canvas)
- [x] Back button chevrons should be primary blue
- [x] We have recently updated the multiple responses guidelines, use the actionlink for adding another item instead of a question.
- [x] Put the list of values in the same order as previous list and add “value” to all items

**Content**
- [x] Step 3 of 7 Household assets > Your other assets > Select any other item of value (called assets) you own, not including heirlooms:
clarify to the user what constitutes an "heirloom".
I recommend clarifying to the user what constitutes and "heirloom", or simply don't use the word heirloom, and instead use the definition of heirloom. The same verbiage should apply to the entire list. ~~The items in the list are all somewhat subjective. I recommend using a "threshold". For instance you could say, "anything valued at over $200", or something similar.~~ _[Not needed](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/52196#issuecomment-1404162799)_
Updated to:
_**"Select any other items of value (called assets) you own, not including items passed down in your family for generations:"**_
- [x] Step 3 of 7 Household assets > You have added these assets > "Precious metals and coins value", is the first entry for added items. The next added item simply says "Antiques". This is incongruent formatting.
- [x] I recommend using the same formatting and verbiage for each asset entry.I recommend removing "value" from "Precious metals and coins value, and changing the verbiage from "How much is each of your assets worth?", to "What is the value of each of your assets?"
## Acceptance Criteria
- [x] _Changes discussed with Design System team_
- [x] _[Sketch](https://www.sketch.com/s/79aa4a84-fef1-4c06-9495-e0431a6390bd) Files updates_
- [x] _[UXPin](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages//comment/sitemap?mode=i) Files updates_
- [x] _[Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1671734127581/dc254b12e788570c946af60bc55338b0045aea03?sender=ua78f969c4cddcbfe56b27885) Files updates_
- [x] _FE Ticket Created #52496_

**Comment by mgleo** [comment]
@denisecoveyduc @HeatherRienks Form stakeholder question for Household Assets: Is there a threshold for the value of assets? (example: anything over $200?)

From the following feedback: The items in the list are all somewhat subjective. I recommend using a "threshold". For instance you could say, "anything valued at over $200", or something similar.

**Comment by HeatherRienks** [comment]
@mgleo - I will defer to @denisecoveyduc on this, but your recommendation makes sense to me!

**Comment by denisecoveyduc** [comment]
@mgleo I have confirmed with stakeholders that there is no threshold for the assets that a Veteran may include on their Financial Status Report (FSR) They are able to include any asset that they feel is pertinent to their waiver request. As a result no content changes are needed in relation to the question brought up during Midpoint review. 
cc: @HeatherRienks

**Comment by mgleo** [comment]
FE Ticket Created #52496

**Comment by denisecoveyduc** [comment]
Thanks @mgleo for summarizing the midpoint review feedback so clearly for the FE team!
