### ISSUE TITLE
[PM] Get design files for APO/FPO/DPO and bad address indicator work

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5220]
## Background

Hey @luke-gcio — Arthur left without leaving his design files for the bad address indicator work or the APO/FPO/DPO work. Is there any way you can help us track those down?

## Tasks

- [x] Send Samara Sketch files for APO/FPO/DPO work
- [x] Send Samara Sketch files for bad address indicator work

## Acceptance Criteria

- [x] Samara has both sets of design Sketch files

**Comment by MickinSahni** [comment]
hey @Samara-Strauss just a heads up that i associated this with the existing candidate address epic
