### ISSUE TITLE
[FE] - Remove anchor link with no target on language picker

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#52205]
## Description
Wave is reporting a warning on the language picker.

![Screen Shot 2023-01-18 at 4.17.54 PM.png](https://images.zenhubusercontent.com/62ace7e07463ea93483c002a/c3c66d7f-b2ed-4f69-a77b-8d43cf52f65a)

## Tasks
- [ ] [FE] Change them to just the # sign

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by wullaski** [comment]
@brianseek Getting a linting error when I attempt to do this. Which is more important the eslint or the wave plugin? 😅  https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/HEAD/docs/rules/anchor-is-valid.md

**Comment by brianseek** [comment]
eslint in my opinion is more important. The wave tool is flagging this as an html issue rather than an accessibility issue. Its kind of the nature of our single page application. The real fix would be to have a button style that is a link, but that also brings up accessibility issues and is also not part of DS

**Comment by wullaski** [comment]
This is getting addressed in another ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/52360
