### ISSUE TITLE
Demo:  Metrics on vfs-change-announcements channel usage

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#52217]
## Issue Description
Since the channel was launched it's seen strong initial usage.  Let's share what we're seeing, what we want to encourage, and what we want to change/improve.

## Tasks
- [x] Add content to [this deck](https://docs.google.com/presentation/d/13IMH1JbvZKhVJ4LslHrv9TgK-X0Buw93ByAQLRTVsb0/edit#slide=id.gcd567e2ae4_0_432)  for sharing purposes
- [x] Share [Metrics ](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2491613369/Metrics+for+the+VFS-Change-Announcements+slack+channel)at Demo day
      - Encourage having team members join
      - Encourage use of the recommended format

## Acceptance Criteria
- [x] Communicated metrics at Demo Day
