### ISSUE TITLE
Certificate of Eligibility | Display uploaded documents

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#52213]
## Value Statement
**_As a_** Veteran applying for a home loan
**_I want to_** see the documents that I shared when applying for my CoE
**_So that_** I can quickly reference them when corresponding with a loan assistant.

---
## Background Context
LGY requested this functionality for us cases when a Veteran needs to quickly see what they shared with a loan assistant, so they can identify missing documents easily. 

## Acceptance Criteria
- [ ] When a Veteran uploads a document, it appears in the appropriate section of the page.
- [ ] When a Veteran clicks on an uploaded document, they can view the contents of the document. 

## Designs and Build Notes
- Add here

## Tasks
- [ ] Refine internally
- [ ] Discuss  use cases with LGY 

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
@uxgary Tagging you in a ticket for the work we briefly chatted about for the Certificate of Eligibility. We'll refine it tomorrow.

**Comment by steele-lm** [comment]
@saderagsdale question from @ohgreatkate... Are there any other UX design links available outside of UX pin?

**Comment by Midge-dev** [comment]
@tblackwe this appears to have already been implemented to some degree. (I logged into staging w/ 228)
[https://staging.va.gov/housing-assistance/home-loans/request-coe-form-26-1880/upload-supporting-documents](https://staging.va.gov/housing-assistance/home-loans/request-coe-form-26-1880/upload-supporting-documents)
<img src="https://images.zenhubusercontent.com/64679f5ee8120a31820a0a33/fed9958c-f430-45fe-a2ca-0667f4661bda" width="500">

**Comment by saderagsdale** [comment]
@steele-lm Nope - that's what the previous team used. Design will have to remake the files if they want the originals to be stored.
