### ISSUE TITLE
Create Tip of Sprint Archive 

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#52226]
### TASKS

- [x] Create a new confluence page in the Platform Content Team Folder
- [x] Gather the Tips of Sprint slack posts to date
- [x] Paste them in the confluence page with date of post and author. 

Link to Page: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2493743148/TIP+OF+THE+SPRINT+-+Archrive
