### ISSUE TITLE
Review crisis language content on Veteran survey tool for Contact Center team

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#52228]
## Issue Description
The contact center team opened an intake request asking for a content review of new crisis language content they want to add to the Medallia Veteran survey tool. Currently there isn't language there telling Veterans not to fill out the form if they are in crisis. 

This word doc is draft introductory language the team created based on the text used for the chatbot. We need to do an edit for plain language and to make sure it adheres to VA.gov style standards.

[https://app.zenhub.com/files/133843125/a997dccb-a38a-4452-82eb-939e6cb94497/download](https://app.zenhub.com/files/133843125/a997dccb-a38a-4452-82eb-939e6cb94497/download)

Original intake request for reference: #52172

## Tasks
- [ ] Edit content for plain language (Aliyah)
- [ ] Review (Laura)
- [ ] Copy edit (Megan)
- [ ] Post final content in intake ticket #52172

## Acceptance Criteria
- [ ] Contact center team has final content

**Comment by aliyahblackmore** [comment]
Hi @laurwill - this is my Word document with some initial suggestions and questions for this content.
Looking forward to chatting through this in our sync tomorrow.
[Contact center crisis text_AB_1.19.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10680419/Contact.center.crisis.text_AB_1.19.docx)

### **A few general notes/question:**
• The intake request mentions content needs for crisis language, but the word document that they attached includes additional language about personal information and confidentiality (included in the [mockup from the VEO stakeholders](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52172#issue-1538255569)). I’ve made content suggestions to the language in from their document (including the crisis content) and added comments regarding placement, etc.
• Can we or should we make any other content suggestions on this feedback form? These are some additional thoughts and questions.
**For example:** 
1. Should there be any sort of H1 on this feedback screen? Noting this because when someone selects “Feedback” from a VA.gov page this screen pops up, but there isn’t any introduction to this new page. 
2. I would maybe consider other words for the satisfaction rating and changes to content for statements like “Estimated burden,” and the how the date is written out (i.e. would we use the full Month, Day, and year - February 7, 2023 - or is this survey screen considered an application form and would we use the [mm/dd/yyyy format](https://design.va.gov/content-style-guide/dates-and-numbers#dates-and-years)).
3. Where will the crisis content appear in the survey form? In the mock up it is placed before the questions, but if we can suggest a H1 and if there is any additional content about the feedback form (for example, “Thank you for completing this survey”), can this exist after the additional content and before the questions?
4. Will the information about estimated time and expiration need to come after the crisis content or can that be towards the end of the survey? There is also information about the OMB number and estimated time towards the end of the mockup. I’m wondering if this should be earlier on the page? The intake request mentions that the product is already launched, but I wasn't able to find the OMB information and estimated time info on the current feedback form on the live site – this wasn’t mentioned in the intake request as a content need.
5. Are there any content suggestions needed for the information at the end of my mock up about the Paperwork Reduction Act?
• This is a version of the current feedback form on the website.
<img width="443" alt="Feedback:Survey on VA gov" src="https://user-images.githubusercontent.com/102090263/217382758-2f57efe2-42be-456f-96f6-573f5389f243.png">

**Comment by aliyahblackmore** [comment]
**Update here:** 
I included a few questions for Chante in the intake request and let her know via Slack.

**Comment by aliyahblackmore** [comment]
Hi @laurwill - this is the word document with some updates after our call.

[Contact center crisis text_AB_2.9.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10702225/Contact.center.crisis.text_AB_2.9.docx)

Also re-sharing some questions that we'll need to confirm (a few from my [previous comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52228#issuecomment-1421665417): 

- Can we suggest any sort of H1 on this feedback screen? Noting this because when someone selects “Feedback” from a VA.gov page this screen pops up, but there isn’t any introduction to this new page.

- Confirmation: Do we need to do a content review of those OMB, Paperwork Reduction Act, and estimated time details? These aren't on the current live survey and aren't in the word document in the intake request.

I'll plan to send these over to Chante in the morning.

**Comment by aliyahblackmore** [comment]
Hi @laurwill - I updated some content suggestions based on the replies from Chante and feedback from the crisis research for SM. I also included a few comments and questions and I'm happy to put any additional questions you may have in the intake request.
[Crisis content for Contact Center_2.14_AB.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10737441/Crisis.content.for.Contact.Center_2.14_AB.docx)

**Calling out this question:**

Do we need to confirm whether changes on this survey may also impact changes on any form pages that include the same type of information re: the OMB number, estimated time, and expiration date?

**Comment by aliyahblackmore** [comment]
**Update here:** Their team will likely have a mock up for us next week!

**Comment by aliyahblackmore** [comment]
**Update:** I followed up with Chante in the intake request re: the mock up and the legal text.

**Comment by aliyahblackmore** [comment]
**Update here:** I followed up with Chante on the intake request. Sara Smith attended a meeting this afternoon about some of the technical issues blocking the launch of the modal with the crisis content. 

[This is the modal is staging](https://staging.va.gov/health-care/eligibility/) (the layout changed over a few minutes)

These are screen captures as well 
![Screen Shot 2023-07-13 at 2 59 27 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/102090263/ccc895af-401b-4d55-8d2b-c3e90b834bd5)

![Screen Shot 2023-07-13 at 3 48 15 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/102090263/390db204-f336-49a2-b04f-fd8ec1d66538)


I flagged a few of the last opencquestions and some adjustments to the modal based on the current versions in staging.

**Comment by laurwill** [comment]
There's crisis language live in the Medallia feedback survey on VA.gov. Moving this to validate.
