### ISSUE TITLE
Seek OCTO approval on static pages not being held to QA Standards

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#52257]
## User Story
As a Governance team member, I want to show to OCTO that static pages (created by the Sitewide Content and IA team) should not be held to the same QA Standards as VFS tools/products so that I can update our operational and VFS-facing guidance to set expectations

Assignee: @it-harrison 
Peer Review: @shiragoodman 

## Description
The [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards) have been upheld in the Collaboration Cycle since 1/9/2023. However, the Governance team has had several Staging Review's for static pages. These are typically landing pages that serve as entry points to other tools and services. See [The difference between static and dynamic pages on VA.gov](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/static-and-non-static-page-documentation.md) for more information on what qualifies as a static page vs. a dynamic page (typically a VFS tool or product with functionality). 

Since static pages are static, are not authenticated, and do not include any functionality (such as a form, or search tool would), the QA Standards aren't really applicable. 

## Tasks
- [x] Write brief explanation as to why _test plans_ shouldn't be applicable to static pages
- [x] Write brief explanation as to why _regression test plans_ shouldn't be applicable to static pages
- [x] Write brief explanation as to why _traceability reports_ shouldn't be applicable to static pages
- [x] Write brief explanation as to why _E2E test participation_ shouldn't be applicable to static pages
- [x] Write brief explanation as to why _unit test coverage_ shouldn't be applicable to static pages
- [x] @shiragoodman will summarize findings 
- [x] @shiragoodman will contact Platform OCTO leads for their review and approval
- [x] If OCTO approves, create additional ticket(s) for implementing changes and communicating in guidance

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have communicated to OCTO why static pages should not be held to the QA standards

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@it-harrison FYI. Feel free to add to or edit the ticket if you feel there is something missing.

**Comment by it-harrison** [comment]
@shiragoodman [here is a draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2515992950/Proposal+to+exempt+static+pages+from+QA+Standards)

**Comment by shiragoodman** [comment]
@it-harrison this is fantastic. Thank you so much for putting this together. You did an excellent job.

I will share with Ray via our team channel for his review and feedback. If/when he approves, please create a ticket to implement these changes in our operational process and VFS-facing guidance. I can work with you when I return to complete the ticket and ensure we're making the changes in the right place.

**Comment by it-harrison** [comment]
Hi @shiragoodman I have created two issues:
* #53673
* #53722

**Comment by shiragoodman** [comment]
Thank you @it-harrison !

The [proposal](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2515992950/Proposal+to+exempt+static+pages+from+QA+Standards) for static pages being exempt from QA Standards was shared with Ray Wang for review and approval on 2/6 and the proposal was approved.
