### ISSUE TITLE
Platform Orientation - Introduce asynchronous Orientation Sessions

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#52273]
## Problem Statement 
In the [Platform Orientation - Discovery research around VFS challenges](https://github.com/department-of-veterans-affairs/va.gov-team/issues/29671) initiative, Governance team completed research to uncover the top pain points and challenges VFS team members face while completing Platform Orientation. There was a recurring theme with the following 3 findings:

1. Waiting for orientation sessions is frustrating and extends the length of orientation significantly.
2. Most new hires prefer asynchronous options for orientation sessions, but would value the opportunity to put faces to names and ask questions down the line.
3. Orientation information comes at you all at once like "drinking from a firehose," but it takes much longer to digest.

How might we shorten the time it takes for VFS teams to complete orientation?
How might we allow VFS teams to partake in asynchronous sessions yet still connect with Platform team members for support?
How might we allow VFS team members to participate in orientation at their own pace?

## Hypothesis or Bet
By introducing asynchronous options for the Orientation Sessions, we could allow VFS team members to shorten the length of time currently required by orientation, remove frustration around waiting, cater to VFS team member request of asynchronous options, and would allow VFS team members to learn at their own pace.

## We will know we're done when... ("Definition of Done")
*What requirements does this project need to meet for you to finish this initiative?*
- [x] New VFS team members are able to attend orientation on their own timeline
- [ ] New VFS team members have the opportunity to connect with Platform for questions
- [x] New VFS team members are able to intake orientation materials in small, manageable chunks

## Known Blockers/Dependencies 
The scope of this initiative may be limited to just 1 orientation session (for example, General Orientation) or may be limited to the orientation sessions owned and maintained by Governance team (General, Design & Research, Accessibility and QA). This decision is solution dependent.

## Projected Launch Date
* When do you expect to be completed rolling out this initiative*

## Solution
The solution for introducing asynchronous orientation sessions was defined in ticket #56473.

The Platform Orientation sessions will move from once a month to once every 3 months. When they do occur, the meeting will be recorded with closed captioning and transcripts enabled. The recorded meeting will be uploaded to YouTube and then shared via the Orientation Sessions page on Platform Website. This solution will be applicable to the 8 orientation sessions that are currently hosted monthly (excluding ATO orientation). VFS teams will have the option to attend the live, recorded session or watch a previously recorded session. ~~If they have questions about the content covered in the orientation session, they will be encouraged to attend an applicable office hours session.~~ (7/18 Note: this part of the solution has been pulled from the initiative and will be addressed in new initiative #62176)

## Launch Checklist
<details><summary>Toggle launch checklist</summary>
### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my Platform initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given Platform initiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1912569976/Platform+Product+terminology?atlOrigin=eyJpIjoiM2VmNzY2MTZkZWE4NGY2NmJmNjk2YWIwMmJhMGZiZmYiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ) for details._

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [Platform Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Configure your communication to teams about your work using the [Change Communication Guide](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2317647873/Change+Communication+Guide)
- [ ] Conduct a [go/no-go](https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic
- [ ] Add this initiative to the [Digital Experience Product Board](https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform) using [these instructions](https://vfs.atlassian.net/wiki/spaces/AP/pages/2120974387/Platform+Initiative+Guidelines+for+Digital+Experience+Product+Board)
</details>

**Comment by shiragoodman** [comment]
@humancompanion-usds this ticket is ready to close. The only AC/DoD we did not meet was, "New VFS team members have the opportunity to connect with Platform for questions." The plan here was to have an office hours affiliated with each orientation session. Some of these are easy 1-to-1 matches:

- Folks attending Analytics Orientation can ask questions at [Analytics Office Hours](https://calendly.com/platform-office-hours/analytics?month=2023-07)
- Folks attending Design & Research Orientation can attend [Design Office Hours](https://calendly.com/platform-office-hours/design-office-hours?month=2023-07) or [Research Office hours](https://calendly.com/platform-office-hours/research-operations?month=2023-07)

There's some that are _almost_ good matches that I think could make work with cooperation from the teams involved:
- Folks attending Design System Orientation can attend Design Office hours
- Folks attending QA orientation can attend Collab Cycle Office hours*
- Folks attending Accessibility Orientation can attend Collab Cycle Office hours*
- Folks attending General Orientation can attend Collab Cycle Office hours*
_*It might be a good idea to pivot "Collab Cycle Office hours" to "Governance team office hours" so that it can cover both Governance team products_

As far as I know, there are no office hours affiliated with Backend and Frontend orientation. 

Am I good to close this initiative? I can create a separate initiative for providing new VFS team members an "opportunity to connect with Platform for questions." I will link here when ticket is created.

**Comment by humancompanion-usds** [comment]
Sure. Close this one and open the new open. Thanks!
