### ISSUE TITLE
[FSR] Replace soon-to-be deprecated Radio Button components

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#52277]
## Issue Description

`<RadioButtons .../>` is being deprecated and needs to be replaced in the FSR. 
`va-radio` appears to be the most up to date and [the storybook can be found here](https://design.va.gov/storybook/?path=/docs/components-va-radio--default)

[Here's a good reference of a similar update](https://github.com/department-of-veterans-affairs/vets-website/pull/22843) - note the import of react-bindings that can help with react events! Potentially creating a reusable component like they did could be cool too. 

---
## Tasks
- [ ] Replace the <RadioButtons .../> react component in the following locations:
  - [x] `/src/applications/financial-status-report/components/ResolutionDebtCards.jsx`
  - [x] `src/applications/financial-status-report/wizard/pages/Decision.jsx`
  - [x] `src/applications/financial-status-report/wizard/pages/Recipients.jsx`
  - [x] `src/applications/financial-status-report/wizard/pages/Reconsider.jsx`
  - [x] `src/applications/financial-status-report/wizard/pages/Repayment.jsx`
  - [x] `src/applications/financial-status-report/wizard/pages/Request.jsx`
  - [x] `src/applications/financial-status-report/wizard/pages/Start.jsx`
- [ ] Confirm these changes do not affect unit/e2e tests

## Acceptance Criteria
- [ ] All RadioButtons instances have been replaced
- [ ] All tests continue passing.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
Background info re: this ticket from Carol Wong on the Design System Team (see below).

_"Hi. I’m the PM for the Design System Team and you may have seen my reminders in ToT that we are deprecating the React radio button. The engineer working on that discovered that there are still many instances of React Radio buttons on apps your teams work on.
Claims & appeals (Benefits Team 10) - 14 instances
CTO Health Products - 5 instances
VSA Debt - 7
My Education Benefits Team - 2
Would you be able to have your engineers migrate to the radio button web component so we can move forward with deprecation? We will delay for a few weeks to give you all time."_

We agreed to add this work into Sprint 92

**Comment by amponce** [comment]
merged
