### ISSUE TITLE
[Letters App to Lighthouse] Create letter-generator service

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#52287]
## Background
Before creating the endpoints, it makes sense to setup the infrastructure needed. In this case the necessary building blocks would be a new service and a new configuration to support that endpoint. Since the new API uses CCG, it's recommended to use the `lib/lighthouse/auth/client_credentials/jwt_generator.rb` service to generate access tokens.

## Considerations
Suggested files:
- `lib/lighthouse/letter-generator/configuration.rb`
- `lib/lighthouse/letter-generator/service.rb`

## Tasks
- [x] Create the new configuration/service
- [ ] PR has been created / review requested

## Acceptance Criteria
- [ ] New configuration/service has been created
- [ ] Preliminary steps to controller creation completed
