### ISSUE TITLE
[Letters App to Lighthouse] Create letter JSON interpretation endpoint

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#52284]
## Background
Need to write the necessary code to act as a proxy for the `letter-contents/{letterType}` endpoint that is part of the Lighthouse VA Letter Generator API

## Open Questions
Will mobile be using the same end point?

## Tasks
- [ ] Develop code needed for the letter JSON contents endpoint
- [ ] Write tests for this endpoint

## Acceptance Criteria
- [ ] Code has been developed for letter JSON content endpoint
- [ ] Tests have been created for new endpoint
- [ ] PR has been requested for merging

**Comment by kjduensing** [comment]
Let's bring it up at planning

**Comment by kjduensing** [comment]
the upshot being: it's new functionality available in Lighthouse, and our most important task is to migrate the existing functionality from relying on EVSS to Lighthouse

**Comment by jacobworrell** [comment]
I am going to convert this ticket to a user story.
