### ISSUE TITLE
526ez | Update and re-enable e2e tests

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#52298]
## Value Statement
**_As a_** developer
**_I want to_** re-enable form 526's e2e tests
**_So that_** we can ensure we maintain the form functionality. 

---
## Background Context

The platform team has been disabling flaky end-to-end (e2e) tests behind the scenes to ensure production builds are performed in a timely manner.

According to the ["Currently Disallowed" page](https://depo-platform-documentation.scrollhelp.site/developer-docs/currently-disallowed-cypress-test-specs-on-va-gov), _all_ of the form 526 e2e tests have been disabled for nearly 2 months. The continuous integration (CI) stress test is used to determine if the e2e test needs to be added to the disallowed list. And the only way to restore the e2e test is to modify the test.

In order prevent all tests from becoming disabled, the 8 existing e2e tests should be separated into separate files instead of one file to test all situations.

## Acceptance Criteria
- [ ] Flaky tests have been fixed
- [ ] Modify e2e test so CI can re-run the stress test
- [ ] All e2e tests passing

## Tasks
- [ ] Find and fix potential e2e test failures causing it to fail the stress test
- [ ] Split up the 8 e2e tests into different files to maximize CI load balancing
- [ ] Find and fix potential e2e test failures causing it to fail the stress test

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing
