### ISSUE TITLE
[Letters App to Lighthouse] Update devops configs across environments

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#52296]
### Background
The settings needed for the new letter-generator service will be vary across the different environments (dev, staging, prod). We need to update the devops configs to configure these settings

## Considerations
The RSA keys have been added to the AWS parameter store already. These are the paths:
* **Staging** - `/dsva-vagov/vets-api/staging/lighthouse/letter_generator/access_token/rsa_key_ORIGINAL`
* **Prod** -` /dsva-vagov/vets-api/prod/lighthouse/letter_generator/access_token/rsa_key_ORIGINAL`

We will be creating new parameters based of these that have values formatted correctly for the YAML configs used in vets-api

## Tasks
- [ ] Create a list of parameters that will be needed
- [ ] Create the needed parameters in the AWS Parameter Store
- [ ] Update the devops configs to use the appropriate settings across the appropriate environments
- [ ] Update the vsp-infra-application-manifests configs to use the appropriate settings across the appropriate environments

## Acceptance Criteria
- [ ] Needed parameters have been added to the AWS Parameter Store
- [ ] devops configs have been updated
- [ ] vsp-infra-application-manifests configs have been updated
- [ ] PRs have been created / requested for merging
