### ISSUE TITLE
[Spike][Letters App to Lighthouse] Create new policy for Lighthouse letter-generator

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#52314]
## Background
We currently have a Pundit policy in place for EVSS. One of the sub-policies is related to EVSS letters access. We will want to create a new Lighthouse policy to emulate this

## Considerations
* The EVSS letters policy can be found [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/policies/evss_policy.rb#L12-L19)
* The current policy requires that the Veteran in question has the following IDs:
  * EDIPI
  * SSN
  * PARTICIPANT ID
* We will most likely only need to check that they have a PARTICIPANT ID for this service
* There should be a policy created for Lighthouse already [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/policies/lighthouse_policy.rb)
* This service will need to be added to the list of backend services [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/backend_services.rb)
* In order for the new backend service to show up in the list of a users authorized services, the appropriate code will need to be added [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/services/users/services.rb#L19-L34)
* There are a few specs that will also need to be updated as well

## Open Questions

- [ ] Is this work still necessary or relevant?

## Tasks
- [ ] Determine what information needs to be part of the Veterans account in order for them to access letters
- [ ] Create the new sub-policy
- [ ] Add the policy to the list of backend services
- [ ] Update the list of a users authorized services
- [ ] Update any specs as needed

## Acceptance Criteria
- [ ] Required Veteran IDs have been identified
- [ ] A new sub-policy has been created
- [ ] The appropriate code has been written so that the new service shows up in the list of authorized services for the given user
- [ ] Specs have been updated as needed
- [ ] A PR has been created/requested for review

**Comment by kjduensing** [comment]
We do not need a separate policy for the letters app. We can (and are) simply using the exiting lighthouse policy.
