### ISSUE TITLE
Update language in Veterans Crisis Line modal and Veteran in crisis alerts

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#52331]
## Issue Description

We currently have language in the Veterans Crisis Line modal and the "How do I talk to someone right now?" alert that's not consistent with some of our new style standards. For example, we no longer mention "if you have hearing loss" when listing a TTY number and we have added "select 1" after listing the 988 number. 

We need to update the content in the alert and in the modal and make sure this is consistent anywhere else on the site as well. We'll need to have the VCL team approve any content changes to the modal and we'll need Public Websites' help in making those changes since they aren't in Drupal. 

When we are ready to pick up this work, we'll need to alert PW so they can account for it in an upcoming sprint.

## Tasks
- [ ] Revise content (Megan)
- [ ] Review (Danielle)
- [ ] Send to stakeholders for approval (Danielle/Megan)
- [ ] Copyedit
- [ ] Send revised content to PW to update modal
- [ ] Publish Drupal changes

## Acceptance Criteria
- [ ] Modal and alerts are updated on live site

**Comment by briandeconinck** [comment]
Just noting that I've added an extra task (Verify TTY contact number) to the task list per @artsymartha68's [request in Slack](https://dsva.slack.com/archives/C023ZKDJJK1/p1677788273963739?thread_ts=1651591137.570409&cid=C023ZKDJJK1).

Backstory: VCL modal currently lists the TTY number as `800-799-4889` but the VCL website says "For TTY users: Use your preferred relay service or dial 711 then 988." Uncertain if the 800 number is still an active TTY relay for VCL.

**Comment by RLHecht** [comment]
Confirming here that when we make these changes we should update the TTY to 711. I'll update this at the top of the ticket as well.

**Comment by megzehn** [comment]
Hi @RLHecht and @DanielleThierryUSDSVA, I'm finally coming back to this ticket that somehow fell through the cracks. Eek, I'm sorry.  

Do these edits look OK for VCL alerts on Drupal? For the TTY language, I shortened what we currently have on the [VCL website](https://www.veteranscrisisline.net/get-help-now/call/): "For TTY users: Use your preferred relay service or dial 711 then 988."

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBellhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--254a9c4213b47803ceb2c4bb802066b1a53bc4e8/image.png)

If the language above looks OK, we could make the same change on the modal that's linked to in the footer:

- **For TTY, dial 711 then 988.** 

@RLHecht, let me know if there's someone I should connect with on the VCL team to get approval for these changes. And then should I connect with Jill Adams to actually make the modal change? 

Thank you both for your help!

**Comment by RLHecht** [comment]
yep, looks like it's complete!
