### ISSUE TITLE
[FE] - Improve functional links by adding url parameters

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#52360]
## Description

Add URL parameters to functional links. 

### The language picker
The language picker is switching the language of the app but not navigating anywhere. In this case have the onClick for the language picker push state to the history object to add `?lang=es` when switching to spanish.

### Back to appointments link button
Add the path to the appointments page from the URLs util object.

### Back button
since the action is a prop, we should add another prop for the href location. in most cases we could get previous page from window object and use that as the prop to populate the href

### pre-check-in start button
determine next page from form and populate href with that.

## privacy modal trigger
ideally would be a button, but could add a url param of ?modal=open or something

## Tasks
- [ ] [FE] Add `?lang=${lang}` to the url when switching languages without refresh
- [ ] [FE] Add url paramters when navigating back to 
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
