### ISSUE TITLE
Weekly BE CoP Duties

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#52388]
## Issue Description
Performed a number of BE CoP duties.

---
## Tasks
- [x] Closed most of the tickets that were created more than a year ago (1/15/22). I left tickets that we already reviewed and added to the backlog.
- [x] Did weekly check for backlog tickets that have been 1) picked up or 2) completed
- [x] Added recurring events to the platform calendar
- [x] Hosting BE CoP meeting
- [x] Wrote up meeting minutes
- [x] Completed the action items assigned to me that came out of the meeting (mostly checking in with others about the status of old tickets we reviewed)

## Acceptance Criteria
- [x] All tasks are done
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by holdenhinkle** [comment]
BE CoP meeting minutes notes - https://vfs.atlassian.net/wiki/spaces/BCP/pages/2496397414/1+20+23+Meeting+Minutes
