### ISSUE TITLE
Copyedit VA mobile app release notes

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#52389]
## Issue Description

Misty opened an intake request for us to do a copy edit of new content that will appear in the "What's new" section of the iOS/Google Play app stores.

Here's the copy to review:

We’ve updated where you find tools and information in the app.

When you sign in, you’re taken to a new Home screen. At the bottom of the app for most screens you’ll find 4 buttons: Home, Benefits, Health, and Payments. Here’s what’s in each section:

- The Home section shows your name and branch of service. It also includes links for how to contact us, find VA locations, and get updated information on COVID-19.
- The Benefits section includes your disability rating, claims and appeals, and VA letters.
- The Health section includes your VA health care appointments, secure messages, and vaccine records.
- The Payments section includes your VA payment history and direct deposit information.

We moved the Profile section to the top right area of the Home screen. Your Profile section includes your personal, contact, and military information. You can also manage the app’s settings in the Profile section.

Original ticket for more info: #52219

## Tasks
- [x] Copy edit content
- [x] Post final content in intake ticket

## Acceptance Criteria
- [x] Content ready for product team

**Comment by megzehn** [comment]
Thanks, @RLHecht! I posted updated copy in the original ticket and alerted Misty. I think we can close this one out.

**Comment by RLHecht** [comment]
Thanks! Closing!
