### ISSUE TITLE
Craft language for future education rates pages for when no future rates are available

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#52387]
## Issue Description

Throughout the year, we will be creating and publishing "future rates" pages for the different education benefits. For each of these, there will be several months of the year where we don't have future rates to display because it's too far from when they will go into effect. During that time, we'll need to remove all the content showing rate information and instead put some kind of language on the page explaining that future rates will be coming soon and to check back around X date. 

We should be able to draft the same language for each of the different education benefits except for specific dates and program names.

## Tasks
- [x] Draft "placeholder" language for future rates page (Katherine)
- [x] Review (Beth)
- [x] Copyedit (Megan)
- [x] Create ticket to add language to future rates page (Randi)

## Acceptance Criteria
- [ ] Final placeholder language ready to add to future rates pages

**Comment by RLHecht** [comment]
@katherine-fung @bethpottsVADEPO I just added this to next sprint since the future rates for Fry and Post-9/11 will become current rates as of August 1.

**Comment by bethpottsVADEPO** [comment]
@coforma-terry This will need to be in the next sprint for @katherine-fung. Just wanted to flag that here ahead of sprint planning.

**Comment by coforma-terry** [comment]
@bethpottsVADEPO - added to next sprint also :)

**Comment by laurwill** [comment]
Hi @katherine-fung , just noting here that for now, we only need Post-9/11 GI Bill and Fry language. I chatted with Beth about this — we discussed doing either just an intro blurb (maybe running to 2 brief paragraphs), or keeping some of the sections about how we calculate rates. But since we don't want people to read down the page expecting to find the actual rates, a short intro blurb seems like the way to go. 

Let me know if you want to chat about this!

**Comment by laurwill** [comment]
Hi @katherine-fung , Beth and I tweaked this slightly — if this looks good, want to make the same change to the GI Bill version?

Check back in March 2024 for the future Fry Scholarship rates. This page will list rates for the academic year from August 1, 2024, to July 31, 2025. We'll provide rates for tuition, housing, and books and supplies. 

Are you trying to find the current rates for the Fry Scholarship? Check current rates instead

**Comment by katherine-fung** [comment]
Thanks so much @laurwill. I've sent the language to the stakeholders to review, and asked them to get back to me by end of day today.

**Comment by katherine-fung** [comment]
Cinda approved this language. Megan will copy edit the language in ticket #62599.
