### ISSUE TITLE
Update Design Artifacts for Release

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#52395]
## Description
Update sketch wireframes so that they match what we are releasing and prepare them for merging to Abstract main and VA Sketch Cloud.

## Tasks
- [ ] Validate that final sketches (and/or poster) match what we are pushing to production. For example, a wireframe or content may have gotten out of date. 
     - [ ] If sketch files aren't up to date and what engineering is pushing to production is correct, update sketch files to match what we're going to release to production with
     - [ ] Notify FE if they missed something in that's in sketch that's supposed to be in production. Create a ticket and post it in Slack to notify them. 
- [ ] Prepare Abstract wireframe (and/or poster) collection so that it can be merged when we go to production
- [ ] Prepare [production prototype links](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/product#production-wireframes-in-va-sketch-cloud)

**Comment by ytsaoca** [comment]
Need to wait for @zach-park to add the new wireframe to this collection: https://app.abstract.com/share/04c09d9c-4153-4a14-b034-2e1ca094ebb0

**Comment by ytsaoca** [comment]
Need to wait for @zach-park to add the new wireframe to this collection: https://app.abstract.com/share/04c09d9c-4153-4a14-b034-2e1ca094ebb0

**Comment by loripusey** [comment]
@ytsaoca do the other 3 designers not have access to be able to do this in Zach's absence? 
cc: @benbrasso-agile6

**Comment by ytsaoca** [comment]
@loripusey Nope. Only the one who created the collection can edit it.

**Comment by acrollet** [comment]
Pre-check-in screenshot:

![www.va.gov_health-care_appointment-pre-check-in__id=c602cb43-7af6-4702-9837-d47ff9a1f2ee.png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/8e21b80d-c4bd-4645-9a33-c2afc7106ed8)

**Comment by zach-park** [comment]
@ytsaoca , screenshot above by Adrian seems to differ from our discussion. It looks like you would need to create a child brand to add that wireframe. So please let me know if you need my help. Thank you!

**Comment by ytsaoca** [comment]
The wireframe is in this [collection](https://app.abstract.com/projects/d9d1d6b4-192b-4ee6-95ab-e7cf42a1ac03/branches/db3bf6e1-3015-42cb-b262-bc1d1f2133a1/collections/b563d3e6-ea0d-4b80-ad29-cdbbce1fa21b).
