### ISSUE TITLE
[FE] New Message for Expired Link on Day-of Check-in

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#52393]
## User Story
As a Veteran, when I use an expired link, I need to have a message that accurately describes the issue and what to do next so that I am not confused.

## User Workflow
- Given I
    - Access an expired day-of Check-in link (either the token has been deleted or does not exist)
- When I
    - Open the link
- Then I
    - See the message per this [wireframe](https://app.abstract.com/projects/ab30c34e-e2f9-4d3e-bb96-3b683b006c24/branches/d7b2d5d4-6106-4121-8cc7-5b810d5aab76/commits/latest/files/585436fe-2120-45f4-b4f7-fbae01d258d9/layers/C5C5CB9F-2446-4119-988C-2DB697EFE249?collectionId=ce2ab010-49da-4326-98f8-3fed65bdc8ed&collectionLayerId=5c155f8f-6208-41d9-9f38-92645474cd48) 
  
## Wireframes
[wireframe](https://app.abstract.com/projects/ab30c34e-e2f9-4d3e-bb96-3b683b006c24/branches/d7b2d5d4-6106-4121-8cc7-5b810d5aab76/commits/latest/files/585436fe-2120-45f4-b4f7-fbae01d258d9/layers/C5C5CB9F-2446-4119-988C-2DB697EFE249?collectionId=ce2ab010-49da-4326-98f8-3fed65bdc8ed&collectionLayerId=5c155f8f-6208-41d9-9f38-92645474cd48)
 
## Tasks
- [ ] [FE] Change the message when a Check-in link with a missing or expired token is accessed
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by acrollet** [comment]
@ytsaoca @benbrasso-agile6 should the 53079 number or whole sentence be linked to open in the user's text client? (As from the poster)

**Comment by benbrasso-agile6** [comment]
Lol, @kellysmith1008 had an idea to make this action more of a "hey click here," which would pop open the user's text client. At the time, I said, let's do the basics now and make that a future enhancement. 

For me, because this version reads as informational, I wouldn't expect it to do anything. 

But, curious what others think.

**Comment by wullaski** [comment]
@benbrasso-agile6 should this handle the situation if a veteran reloads an old tab? For example: If they already completed check in and they go back to the tab after the appointment and hit refresh. Or would that be a separate ticket? I see there is a [ticket](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/53862) to handle going to the details view after 15 minutes but I'm not sure if there is one for on reload.

**Comment by benbrasso-agile6** [comment]
I believe this ticket is about the scenario you just described, yes

That new ticket might be solved when we implement this ticket :)

**Comment by wullaski** [comment]
@loripusey Validated thread here https://dsva.slack.com/archives/C02G6AB3ZRS/p1677772245791939

**Comment by benbrasso-agile6** [comment]
Left a message in here - https://dsva.slack.com/archives/C02G6AB3ZRS/p1678201408465069?thread_ts=1677772245.791939&cid=C02G6AB3ZRS

**Comment by benbrasso-agile6** [comment]
I would close this, but I think we might need to reopen a new ticket to more directly tackle the initial problem identified. I'll set up a meeting as a next step.

**Comment by loripusey** [comment]
Let's close and start and start a new epic. I'm not understanding what the initial problem was.
