### ISSUE TITLE
Profile: Sprint 4 (2.15.23 - 2.28.23)

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#52405]
## EasyRetro Board
Thank you for an awesome Sprint 3, here's the [EasyRetro board](https://easyretro.io/board/f4051524-d7be-43a4-8c50-f43d887f3a7f/712ca5ef-299b-4e9b-8e43-beb421d8bcc5) for our Sprint Retro.

## PTO

- Samara at OCTO offsite: 2/21 - 2/25
- Liz: 2/15 - 2/17
- AJ: 2/20
- Adam: 2/22
- VA + A6 + Friends closed for Federal holiday: 2/20

## Goals
- Onboarding Derrick 
- Accessibility updates
- Direct deposit EVSS > Lighthouse migration
- Notification preferences
- Military info research

## Onboarding
- [ ] Onboard Derrick Ellerbie (new full stack developer) #50940 -- (Derrick ended up starting on My VA team, we can move his onboarding ticket to My VA Sprint 5 epic)

## General
BE - Tom
- [x] #52717 (Time sensitive, needs to be done by COB 2/28)
- [x] #53208
- [x] #53038 (still Blocked, VA profile is not ready yet, but this is a 1-pointer once unblocked)

## Accessibility updates
FE - Adam
- [ ] #53357
- [x] #53630

## Direct deposit migration
BE - Tom
- [x] #52500 (carrying over, 1-day away from being done)
- [x] #53714

## Notification preferences
Design - Liz
- [x] #51006
- [x] #53529

FE - Adam
- [x] #53541

## Military info research
Design - Florence
- [x] #51887
- [x] #51888
- [ ] #51889

## Unplanned work
FE - Adam 
- [ ] #53474

**Comment by Samara-Strauss** [comment]
Moving #53545 out of this sprint in favor of accessibility/semantic list work.

**Comment by BerniXiongA6** [comment]
Carrying over 5 pts for 51889 for Sprint 5.

**Comment by Samara-Strauss** [comment]
Great work, team!!
