### ISSUE TITLE
Login.gov adoption team: Sprint 12 (1/19/23 - 2/1/23)

### ISSUE THREAD

**Issue by elizabethkochBT** [department-of-veterans-affairs/va.gov-team#52401]
[Sprint 12 Demo](https://app.zenhub.com/files/133843125/ae638e98-ff91-4401-974b-bdb9429f17fe/download)

## PTO/availability

- Carolyn 1/25

## Sprint 12 Priorities

Legacy Credential Migration:
- Design migration dashboard
- Reconcile data discrepancies
- Begin to develop detailed content pieces (in partnership with VEO, Sitewide Content and MHV)
- Iterate on content strategy as necessary (in partnership with VEO, Sitewide Content and MHV)
- Draft content and design for key moments in grandfathering user flow
- Draft plan to test organic Login.gov account creation with a limited number of users
- Surge team collaboration preparations and kickoff
 
## Retro Board

[Sprint 11](https://easyretro.io/publicboard/lAyuCkdXHCTaEpAy9ZH11t3Orhc2/2e09889b-94fd-4797-b905-7c4e85e12c07)

### Discussion Topics/Retro Action Items
 - [x] Assign owner for product tasks
 - [x] Consider capacity as part of sprint planning
 - [x] Add detail to the internal roadmap

### Legacy credential migrations & Login.gov proactive adoption
 - [x] Analyze data retrieved from IAM #51860
 - [ ] High-level user flows for grandfathering solution #51506
 - [ ] Begin to develop detailed content pieces (in partnership with VEO, Sitewide Content and MHV) #51043
 - [ ] Get feedback on content strategy from partners #51351
 - [x] Draft key design moments in grandfathered user flows #52074
 - [x] Draft plan to test organic Login.gov account creation with a limited number of users #52334
 - [ ] Metrics dashboard design #52336

## Collab Cycle Tasks 
- [ ] [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent)
- [ ] [Sitewide content and IA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-Content-and-IA-intake-request.2124906551.html)
@CarlDickerson @MOStudioCarolyn @tygindraux

**Comment by elizabethkochBT** [comment]
[https://app.zenhub.com/files/133843125/ae638e98-ff91-4401-974b-bdb9429f17fe/download](https://app.zenhub.com/files/133843125/ae638e98-ff91-4401-974b-bdb9429f17fe/download)
