### ISSUE TITLE
[Design] Update Final Wireframes

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#52411]
## Description
We need to update the sketch files to remove the legal links in the VA footer now that the decision has been made to NOT include them.

## Tasks
- [x] Create final mockups with callouts (CI & PCI)
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?
- [x] Remove the legal links in the VA footer 
- [x] Remove the title label in the VA header

## Acceptance Criteria
- [x] UI review meeting with product/UX team for feature capabilities
- [x] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.

## Deliverable

[PCI version](https://share.goabstract.com/c8e02754-a7ea-4694-b2ca-e3989357c289?collectionLayerId&mode): 
https://share.goabstract.com/c8e02754-a7ea-4694-b2ca-e3989357c289?collectionLayerId&mode

[CI version](https://share.goabstract.com/3033a7fe-ebfc-4335-966c-dba88c5b3e0d?collectionLayerId&mode): 
https://share.goabstract.com/3033a7fe-ebfc-4335-966c-dba88c5b3e0d?collectionLayerId&mode

**Comment by benbrasso-agile6** [comment]
@cgednalske may be good to pair with zach

**Comment by zach-park** [comment]
@benbrasso-agile6 @loripusey, does this ticket also include removing the text label in the header as shown in the demo yesterday (attached below)? (cc: @cgednalske )

![Screenshot 2023-01-25 at 9.01.36 AM.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/3d2a8734-ad45-42dc-b5f2-712356c5cdf5)

**Comment by benbrasso-agile6** [comment]
Yes

**Comment by zach-park** [comment]
Hi @loripusey @benbrasso-agile6 (cc: @acrollet @brianseek @wullaski @ytsaoca @cgednalske @kellysmith1008 ), the simplified header & footer (aligned with prod.) is ready now for the review:

PCI: https://share.goabstract.com/c8e02754-a7ea-4694-b2ca-e3989357c289?collectionLayerId&mode

CI: https://share.goabstract.com/3033a7fe-ebfc-4335-966c-dba88c5b3e0d?collectionLayerId&mode

**Comment by benbrasso-agile6** [comment]
There are a bunch of wireframes in that check in link that are not in the abstract master link today, and therefore, we're no longer using. 

I think pre-check-in looks to be a copy of the two collections in master. So, those look good.

**Comment by zach-park** [comment]
Hi @benbrasso-agile6 , can you please check the check-in collection again? Apologies, I just finished updating the wireframes shown in that collection. Thank you!

**Comment by benbrasso-agile6** [comment]
Yes, that now reflects the wires in check in master

lgtm

**Comment by benbrasso-agile6** [comment]
Validated
