### ISSUE TITLE
Provide debt lettter user data to stakeholders

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#52418]
## Issue Description
DMC has determined that getting the user identifiers (ssn, email, etc) has become a requirement to their portion of the security audit regarding debt letter downloads. We will need to work with identity and platform BE team to extract this information from MPI using user uuids

---
## Tasks
- [ ] Extracts list of user uuids from logs
- [ ] Connect with MPI for justification for batch processing
- [ ] Extract user data from MPI for list
- [ ] Pass data securely to DMC contacts

## Acceptance Criteria
- [ ] DMC has the user data they need to progress forward with the audit
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Jill Anderson from Debt Management Center (DMC) and her leadership team had a meeting with Congress today 1/23 and one of the questions their team was anticipating was "how soon will we get the information needed to conduct analysis (to determine impacted Veterans of letters)". This has become a high priority to provide this information to leadership teams.

**Comment by HeatherRienks** [comment]
FYI @denisecoveyduc - def for Sprint 92 :)

**Comment by denisecoveyduc** [comment]
As per discussion with Scott, he is working with the identity team to attempt to collect SSN data if possible for the individuals identified.

**Comment by ScottyRJames** [comment]
Ticket #CMDMRP-4081 has been opened in the Information Technology Request Portal

**Comment by ScottyRJames** [comment]
Moving to blocked while we are waiting action from IAM team

**Comment by ScottyRJames** [comment]
Danny from IAM reported that ~600 CSPIDs were not found in MPI. We requested a file of the IDs to investigate provider and any other knowledge. Also inquired if they could still gather the 45k records of found Veterans. Waiting on a response
