### ISSUE TITLE
Collaboration Cycle - Privacy, Security, Infrastructure Readiness Review (PSIRR) improvements

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#52419]
## Problem Statement 
The ownership of the Privacy, Security, Infrastructure Readiness Review (PSIRR) in the Collaboration Cycle has recently changed hands. @gary-fallon and @joeniquette of the Multi Factor Authentication/Surge team have been asked to support the touchpoint and complete all future reviews. The following problems about the current process have been identified:

1. The points of contact are incorrect.
2. The VFS-facing guidance may be outdated and in need of updates.
3. The PSIRR reviewers would benefit from being informed of the product/feature improvements earlier in the teams build process.

How might we help the PSIRR reviewers get involved earlier on in the Collaboration Cycle journey without burdening and/or inconveniencing the VFS team?
How might we introduce a solution that doesn't increase the burden on Governance team and/or make Governance team commitments more difficult?
How might we improve the PSIRR experience for VFS teams?

## Hypothesis or Bet
If we involve the PSIRR reviewers earlier in the Collaboration Cycle process, then VFS teams will have less hurdles to tackle later on at the PSIRR touchpoint.
If we involve the PSIRR reviewers earlier in the Collaboration Cycle process, then PSIRR reviewers will be able to more easily and efficiently complete the PSIRR touchpoint.

## Solution
The solution was proposed in ticket #54910 and the implementation plan was created in ticket #55947.
[Implementation plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2581037220/Collaboration+Cycle+-+Privacy+Security+Infrastructure+Readiness+Review+PSIRR+improvements+52419+Implementation+plan)
[User flow](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1679931482327/06fd157166c87a681db5c82f27d6e972f5a05ba3?sender=u0574179b1d97118ccc0e3591)

## We will know we're done when... ("Definition of Done")
- [ ] The PSIRR reviewers are getting the information they need from the VFS team about the product/feature being brought through the Collaboration Cycle to easily and efficiently complete the PSIRR touchpoint. 
- [ ] VFS team members are not burdened by any changes introduced to the PSIRR process

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed*

## Projected Launch Date
* When do you expect to be completed rolling out this initiative*

### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my Platform initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given Platform initiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1912569976/Platform+Product+terminology?atlOrigin=eyJpIjoiM2VmNzY2MTZkZWE4NGY2NmJmNjk2YWIwMmJhMGZiZmYiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ) for details._

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [Platform Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Configure your communication to teams about your work using the [Change Communication Guide](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2317647873/Change+Communication+Guide)
- [ ] Conduct a [go/no-go](https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic
- [ ] Add this initiative to the [Digital Experience Product Board](https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform) using [these instructions](https://vfs.atlassian.net/wiki/spaces/AP/pages/2120974387/Platform+Initiative+Guidelines+for+Digital+Experience+Product+Board)

**Comment by shiragoodman** [comment]
@humancompanion-usds are you okay with us closing this initiative? It has been open for over 18 months, and I believe bringing PSIRR into the Engineering & Security track will supersede the work outlined in this epic. Please lmk - thanks!

**Comment by humancompanion-usds** [comment]
Yes, let's close it.
