### ISSUE TITLE
BRD Deprecation DEV

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#52427]
TT1 is in the process of migrating vets-api server to EKS. Instrumental part of this process is the [deprecation planning](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2493906959/WIP+BRD+Deprecation+Plan) AND deprecation of BRD. 

Definition of done:
- [x] BRD server and worker deploy deprecated in DEV
- [ ] Archive any dev BRD documentation related to DEV  **documentation will be done at a later date**
- [x] Statds Custom exporter mapping complete for DEV
