### ISSUE TITLE
Add error messaging to `check-vets-api-secrets` GitHub Action

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#52430]
As a developer submitting a PR to the `vsp-infra-application-menifests` repo, I want to easily find out why a check failed and how to resolve it. 

Ticket came out of this support request: https://dsva.slack.com/archives/CBU0KDSB1/p1674491989944309

GitHub Action: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/.github/workflows/validate-vets-api-manifest-parameters.yaml

Suggested wording:
> Did you remember to add the following to the secrets.yml files? ${VALUE_PARAMETERS}

**Tasks:**
- [x] error messaging for `Check secret names` section
- [x] error messaging for `Check value names` section
- [x] error messaging for `Check values and secrets` section

**Comment by rmtolmach** [comment]
fixed in 
* https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1297
