### ISSUE TITLE
DEV BRD Deprecation: Prometheus, Pagerduty, Datadog [discovery]

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#52434]
Any Prometheus, Pagerduty, Datadog alerts for BRD server and worker 
- [Example alert here](https://dsva.slack.com/archives/C30LCU8S3/p1673973857835569)

Note: Some of these alerts are standard and one specific app can’t be removed

Tasks
- [x] discovery to understand what all the alerts are in dev? have any alerts already been migrated?
- [ ] make note of important things for higher environments
**pending discovery, might need to break up the ticket (could be one ticket per alert that needs to be migrated)
- [ ] migrate current alerts to datadog (if they are applicable)

**Comment by laineymajor** [comment]
rebecca is working on finishing up access issues for lindsey and rachal
running a terraform
THEN focus on this work

**Comment by laineymajor** [comment]
need to reach out to devops CoP about the terraform (listed above)

**Comment by rmtolmach** [comment]
That example alert in the description is only for prod, so I don't think that's applicable... unless I'm missing something.

> Some of these alerts are standard and one specific app can’t be removed

True. Many alerts will evaluate many "apps" or "components" with `vets-api` or `vets-api-server` or `-worker`, but if the EC2 instances don't exist, they can no longer be evaluated, so this should be fine. 

### Current relevant `vets-api` alerts:
`terraform/environments/datadog`
* `sidekiq.yaml` - only prod alerts. no update needed for `dev` deprecation. **We will need to modify this alert for EKS**

`ansible/deployment/config/prometheus/`
* `script-exporter-vagov-dev.yml.j2` - I wonder if this and `prometheus-vagov-dev.yml` need to be removed or the functionality moved to datadog?? Not sure about this.
* `rules/cluster.rules` - It's my opinion that we don't need to modify these alerts. Since there aren't any deployments of vets-api-server or worker, they won't be alerted on. There's no use excluding `dev` worker and server deployments from the alert because they're excluding themselves by not existing. **A similar alert should be created in Datadog for EKS.**
* `rules/application.rules` - `ApiErrorRateWarning` and `ApiErrorRateCritical` need to be evaluated. I thought `ApplicationMetricsWarning` would need to as well, but I don't see any evidence of `dev` alerts in Slack for this one, so I don't think anything needs to be done with that one.
* `rules/node.rules` - these alerts are all about the health of instances, but since we took out worker and server instances out of EC2, I think we don't have to do anything with these. **Although, we'll probably need similar alerts in Datadog for EKS**

As far as I can tell, none of these alerts have been migrated to EKS alerts in Datadog. 

### Existing EKS alerts:
There is one file, `terraform/environments/datadog/catalog/eks.yaml` that has two alerts in it, "[EKS] Containers out of memory (by pod)" and "[EKS] Pod restarting" but "Pod restarting" is only for the utility cluster. There's another file, `external-secrets.yaml` that has an EKS alert (although that does need to be updated per https://github.com/department-of-veterans-affairs/va.gov-team/issues/52572).

**Comment by rmtolmach** [comment]
In terms of deprecating BRD alerts for `dev`, there's nothing to rip out, but there are somethings to move over or modify.

**Legend:**
➡️ = Higher env. work
🧹 = small update
🟡 = moderate update 
❔ = Not sure, yet!

### Migrate alerts to Datadog
* ❔ `DeploymentHostCountCritical` - What would the EKS version of this be?
* ❔ `DeploymentInstanceCyclingWarning` - I think the equivalent of this would be "[EKS] Pod restarting" (see below).
* ❔ `InstanceEntropyLowCritical` -
* ❔ `InstancePredictedEntropyDepletionCritical` - 

### Modify existing EKS Datadog alerts
* `eks.yaml`
    * 🧹 "[EKS] Containers out of memory (by pod)" - Add action items to the message. What needs to be done to resolve or investigate? If the "what to do" message is long, add a section to [alerts.md](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/OnCall/alerts.md) and link to it in the alert message.
    * 🟡 "[EKS] Pod restarting" - this one is _very_ noisy, so the metric probably needs adjusting. The alert is being sent to #platform-datadog-alerts-test. Once the metric is adjusted, it should be directed at #devops-alerts. Add action items to the message. What needs to be done to resolve or investigate? If the "what to do" message is long, add a section to [alerts.md](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/OnCall/alerts.md) and link to it in the alert message.
* `sidekiq.yaml`
    * ➡️ These will need to be updated for prod.

**Comment by laineymajor** [comment]
Will consolidate all the above info into tickets; nested in this epic.

**Comment by laineymajor** [comment]
This ticket grew much larger after the discovery. I have created an epic, and nested this ticket under the larger deprecation epic as the discovery portion is complete.

**Comment by rmtolmach** [comment]
I edited my previous comment to add links to all of the issues that came out of this discovery. I also added them to the epic.
