### ISSUE TITLE
QA COP: Add fields/columns to the VFS Product Directory page

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#52445]
# Description
Add additional columns & data to the VFS Product Directory listing page to ensure that it is more useful when trying to find products

# Tasks
- [x] Get guidance from Dan/Lisa on the additional columns/data they would like to have on the page
- [x] Make modification to the Product Directory Listing page

# Acceptance Criteria
- [x] Modifications have been made to the Product Directory listing page
- [x] Product operations personnel have confirmed that this meets their needs

**Comment by JoeTice** [comment]
Info request from Dan Kosko on 1/26/23

**Comment by JoeTice** [comment]
Confirmation received 1/31/23, the additional columns they would like to see are:
- OCTO Product Owner
- VFS PM
- Link to Product Outline

**Comment by JoeTice** [comment]
Ticket is in progress, there's been issues getting the fix to publish to the Confluence page

**Comment by CBonade** [comment]
The changes to the code to produce this updated version of the page have been done for quite some time now. The Confluence API has presented some unpredictable roadblocks. Every request to update this page has resulted in a "success" from the API side, however, the page does not update. Through process of elimination, it has been narrowed down to trying to create custom links to the product sub-pages. 

Prior, this was being done using a Confluence macro that automatically created a list of links to all child pages of the page it's on. However, there is no way to add "more" to that macro, so in order to convert to a multi-column format, we had to generate our own list. When the URLs are removed from the equation, the column publishes as plain text just fine. I've been dividing up the set into smaller chunks, trying different formats of URLs, etc to try and nail down the problem since there is no error to inform me of what it's not accepting to publish. So far, I've made over 100 attempts to update the page and while I have more information than I did originally, I'm not at a resolution yet. I feel confident we can get there, it's just a matter of figuring out how.

**Comment by CBonade** [comment]
https://github.com/department-of-veterans-affairs/product-directory/pull/655 PR is open for this change here. I've asked Ryan Smith to review it, as he's the original author of the code and has the most knowledge of what the changes encompass here. Will merge it as soon as the approval arrives.

The error, which was uninformative, was ```'com.atlassian.confluence.api.service.exceptions.BadRequestException: Content body cannot be converted to new editor format'```. This ended up translating into that ampersands in the URLs were not able to be processed by the API. This unfortunately took a lot of trial and error, as well as finally reaching out to Ryan Smith to find out if he had run into a similar problem (which he had and thankfully, was able to suggest the solution to replace them with encoded ampersands).

Once this is merged, the regular publish job will publish this page instead.

**Comment by CBonade** [comment]
Per feedback from Joe, another column needed to be added so that is now complete. Additionally, I fixed a bug where the N/As in the Product Outline column were being linked to nothing (now they don't link at all, as they shouldn't). This is merged to main and should go out to platform website accordingly with the next publish.

**Comment by pjhill** [comment]
Looking good -- thanks for knocking this out! Our stakeholders should be happy with the changes.
