### ISSUE TITLE
QA COP: Add variations of the VFS Product Directory listing page

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#52447]
# Description
In discussions with members of the Product-Operations group, it was expressed that being able to view the list or products in different ways - by Platform Crew, by Product Lead, for example would be helpful for them.

# Tasks
- [ ] Get guidance from Dan/Lisa on the additional views they would like to have
- [ ] Discuss w/ Platform Content team to determine the best way to set up multiple versions of the same page/content
- [ ] Create additional view based on requests

# Acceptance Criteria
- [ ] Additional Pages have been created and are available
- [ ] Product operations personnel have confirmed that this meets their needs

**Comment by JoeTice** [comment]
Info request from Dan Kosko on 1/26/23

**Comment by JoeTice** [comment]
Marking as a stretch goal for Sprint 21

**Comment by JoeTice** [comment]
The specific changes called out in this ticket have been effectively addressed by [#52445](https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/52445)

Closing this ticket
