### ISSUE TITLE
Add Gary and Joe to Design Intent distribution list for shadowing

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#52464]
## User Story
As a Platform Security Engineer supporting the PSIRR in the Collaboration Cycle, I want to be included in the Design Intent meeting so that I can see if it helps me learn information about the product/feature that'll later help me in completing the PSIRR.

Assignee: @shiragoodman 

## Description
Gary and Joe believe that if they were to have an earlier touchpoint in the Collaboration Cycle, that they would be better prepared to support VFS teams and their product/features when they need the Privacy, Security, Infrastructure Readiness Review. Instead of moving forward with creating a new touchpoint, @shiragoodman thought that they might be able to get what they need from the Design Intent touchpoint. 

The purpose of this ticket is for Governance to add Gary and Joe to the Design Intent distribution list so that they may have the opportunity to listen in, shadow and ascertain if the Design Intent touchpoint will meet their needs.

## Tasks
- [x] Add both Gary and Joe to the Design Intent distribution list.
- [x] Confirm Gary and Joe receive invite to next Design Intent meeting (date TBD)

## Acceptance Criteria
- [x] Gary and Joe are invited to all future Design Intent meetings.

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer
