### ISSUE TITLE
Update Contact Us page

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#52466]
## User Story
As a Platform Security Engineer supporting the Privacy, Security Infrastructure Readiness Review, I want to make sure VFS teams know to expect support from me if/when needed.

Assignee: @allison0034 
Peer Reviewer: @CherylEvans 

## Description
Gary Fallon and Joe Niquette are now supporting the Privacy, Security, Infrastructure Readiness Review in the Collab Cycle. The Contact Us page, which includes all Collab Cycle POCs, needs to be updated to add both Joe and Gary.

## Impacted Artifacts
[Contact Us ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/contact-us)page on Platform Website

## Tasks
- [x] Remove Clint Little as Platform Engineering Lead under Platform Security
- [x] Add replacement text:
 Platform Security Engineers: Joe Niquette & Gary Fallon
- [x] Spell check!

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] The correct people supporting the PSIRR in the Collaboration Cycle are reflected within the Contact Us page

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@allison0034 per your request for more work at yesterday's standup. Let me know if you have any questions.

**Comment by allison0034** [comment]
@CherylEvans this should be ready to review this afternoon after confluence updates.

**Comment by CherylEvans** [comment]
@allison0034 I forgot that platform-content doesn't run SVP on Fridays.  I will verify this on Monday! :-)

**Comment by allison0034** [comment]
Doh! So did I!

**Comment by CherylEvans** [comment]
@allison0034 Everything looks good; my review is complete. :-)
