### ISSUE TITLE
Step Up Functionality 

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#52476]
---

## Problem Statement

This will be a product offering for applications that use USiP or are on VA.gov to be able to request additional security related checks regarding the user before sensitive actions are permitted to occur within their application. The first version of this service would allow the application to request a code be sent to the users registered email address to confirm the user who is logged into the application is who they say they are by proving control over the registered email. This capability could be an opt in per user function or blanket for all activities within the application. From there we would collect feedback about the capability and iterate on other options of the step up functionality.

Refer to Joe Niquette for additional context. 

## Desired User Outcomes/Business Use Case

Why would a user want to use this?
With this problem solved, what should users be able to do/achieve that they couldn't before?

## Measures of Success 

What data (qual or quant) will you look at to understand if your initial set of functionality is meeting your desired user and business outcomes, and not bringing about the undesired outcomes?
What are the most important metrics that track with this product/initiative's success?

## Hypothesis or Bet
**If** _we make this change_ **then** _we expect this to happen_.

## OKRs/Initiatives
_Which Objective / Key Result / Initiative does this epic push forward?_

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## Tasks to Complete

- [ ] Add task here
- [ ] Add task here
- [ ] Add task here
- [ ] Add task here
- [ ] Add task here
- [ ] Etc.
