### ISSUE TITLE
Fill out sitewide IA request 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#52489]
## Description 

How might we....

1. Make pre-check-in and check-in look like one app?
2. While still focusing on highlighting any primary actions that Veterans need to be complete
3. And, allow Veterans to view all of their appointments (like VAOS does with their appointments list), including future and past

## Tasks

- [ ] Fill out sitewide content and IA request ticket in order for sitewide to review new content and userflow 
- [ ] Meet with Sitewide content and IA 
- [ ] Document next steps after feedback has been received. For example, if design tickets need to be created, create those tickets. 

## AC 

- [ ] Request filled out 
- [ ] Received feedback from sitewide content and IA
- [ ] Created any tickets needed based on feedback

**Comment by loripusey** [comment]
not creating tickets for Collab Cycle steps
