### ISSUE TITLE
Ideate and Create User Flows for Option 2

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#52482]
## Description 

How might we....

1. Make pre-check-in and check-in look like one app? 
2. While still focusing on highlighting any primary actions that Veterans need to be complete
3. And, allow Veterans to view all of their appointments (like VAOS does with their appointments list), including future and past

## Tasks

- [x] Create one or more user flows to help visualize what step(s) the appointments list becomes accessible to Veterans
- [x] Review with UX team
- [x] Share with CIE team (either through slack share or meeting share) 

## AC

- [x] Create one or more user flows to help visualize what step(s) the appointments list becomes accessible to Veterans
- [x] UX team has reviewed
- [x] Has been presented or shared with CIE team

**Comment by benbrasso-agile6** [comment]
4 variations with pros and cons created and shared with UX team for feedback

Meeting scheduled with larger team on monday

**Comment by benbrasso-agile6** [comment]
Posted in slack
