### ISSUE TITLE
Create wireframes for app with appointments list 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#52486]
## Description 

How might we...

1. Make pre-check-in and check-in look like one app?
2. While still focusing on highlighting any primary actions that Veterans need to be complete
3. And, allow Veterans to view all of their appointments (like VAOS does with their appointments list), including future and past

[Userflow options](https://app.mural.co/t/vfscie8528/m/vfscie8528/1674839426683/003e6f3c9bd04bab8a3c63f9e6111c61e4060a5e?sender=u83bc52d7fa73658f84f27755)

[Userflow v3 that maps out the alerts + appt information](https://app.mural.co/t/vfscie8528/m/vfscie8528/1676493431709/08ad3a6359fd71e1bf3b0e7fdcf2b5356dac31af?sender=u83bc52d7fa73658f84f27755)

We will want to map closely to VAOS's design, working with Ciera and Peter: 

[Appointments list (in progress, not in production)](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=2161%3A54658&t=ozPJVFdUUnGMmh5O-0)
[Detail page (in progress, not in production)](https://www.figma.com/file/RcDljBwThbwVDkNrDH2xiA/Appointment-Details-Redesign?node-id=2%3A4&t=h95Wpz1byxh3g35L-0)
[User flow (in production)](https://www.figma.com/file/xRs9s6QWoBPRhpdYCGc3cV/User-Flow?node-id=155%3A30915&t=QcWPluoTOZbGm79Y-0) 

## Tasks

- [ ] Create wireframes
- [ ] Create any additional wireframes needed for moderated testing, for example, if two versions need to be tested with Veterans
- [ ] Review with UX team
- [ ] Review with CIE team 

## AC 

- [ ] Wireframes completed
- [ ] Branch in abstract was created 
- [ ] Reviewed with UX team
- [ ] Reviewed with CIE team

**Comment by benbrasso-agile6** [comment]
Zach

**Comment by benbrasso-agile6** [comment]
Closing. Will open new tickets for next sprint.
