### ISSUE TITLE
Brainstorm research methods for collecting feedback on when to receive day of text messages

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#52484]
## Description 

How might we... 

Quickly find out from Veterans when they'd prefer to receive text messages on the day of their appointments. For example, do Veterans prefer one text message on the morning of or 45 minutes before each appointment? 

Does this feedback include findings from Veterans with cognitive disabilities, as well as other underserved groups? 

## Tasks

- [ ] Determine what we're looking to learn about. Is there something we want answered now that can't wait for a larger research study, for example? 
- [ ] Determine the research method. For example, there's a process to do more rapid testing with Perigean. Should we talk to Shane, for example? 
- [ ] Create next steps. For example, if we need to create a ticket to create a research plan for this, create those tickets that are needed. 

## AC

- [ ] Determine what questions we're looking to have answered now vs. later. 
- [ ] Determined research method (and has some level of approval from Shane, if applicable) 
- [ ] Next steps have been documented. E.g., tickets have been created.

**Comment by benbrasso-agile6** [comment]
@loripusey i moved this out of sprint, i think you took it out sprint goals, fyi

**Comment by benbrasso-agile6** [comment]
We have determined that we can do unmoderated
