### ISSUE TITLE
Schedule team meeting for VFS orientation

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#52494]
### Tasks

- [x] Schedule team meeting
- [x] Plan out strategy to create orientation video for VFS team members
- [x] Vicky to document meeting takeaways

### Info
Team initiative notes: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2477621264/FY2023+Q2+Platform+website+orientations

**1/24/23 meeting with Shira takeaways:**

- Look through general orientation deck for current information about the Platform website: https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions
- Governance is trying to move away from slide decks format and transition to something else.
- We (platform content) will be video guinea pigs; If content is too long, break up topics into smaller chunks
- For informational knowledge, we can attend the next general orientation: Tuesdays, February 14
- Circle back with Shira about how to incorporate our video as part of their VFS orientation takeaway documents, process.
- Look through Confluence for YouTube guidance: https://vfs.atlassian.net/wiki/spaces/LEAD/pages/1847820659/Platform+YouTube+channel

**1/26/23 team meeting notes:**
https://vfs.atlassian.net/wiki/spaces/CIT/pages/2476998712/Platform+content+orientation+for+VFS+teams
