### ISSUE TITLE
Make sense of the user research backlog

### ISSUE THREAD

**Issue by tygindraux** [department-of-veterans-affairs/va.gov-team#52501]
### Problem statement
The larger identity team needs to know of any research needs already identified across the different identity projects.

### Initiative
We'll review what's in the current backlog, map to the 4 projects and identify gaps.

### Acceptance criteria
- [x] Research backlog has been reviewed, mapped to the 4 projects and documented as research questions in Github.

### Tasks
- [x] @tygindraux review the current backlog
- [x] @tygindraux map whatever is in the backlog to the 4 projects
- [x] @tygindraux identify any gaps based on what we know about the 4 projects
- [x] @tygindraux write up in Github
- [x] @tygindraux share overview with team

**Comment by tygindraux** [comment]
I've moved my working document to Github: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/research/implementation/research%20questions.md
