### ISSUE TITLE
Design | Profile | Accessibility | Update documentation for personal information and account security

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-team#52502]
## Background

 These sections need to be reviewed/updated now due to completed accessibility work:

- Personal information
- Account security once docs are launched

## Tasks
- [x] Update account security ["all tasks" complete docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/account-security/use-cases/complete-tasks-loa3.md) so content reflects changes, and links point to latest Sketch files
- [x] Review other account security sections to determine what needs to be updated
- [x] Review personal information section and update accordingly
- [x] Make the the identified updates
- [x] add user 11 to fiduciary use case

## Acceptance Criteria
- [x] All personal info docs are updated
- [x] All account security docs are updated

## Validation
Anyone on team can validate the docs

**Comment by andaleliz** [comment]
@BerniXiongA6 Oooh, this is an interesting ticket and a great chance to share a bit about how documentation has been handled in the past.  I'll set up some time to talk about that with you, and drop a comment here about the specific ticket.

I'm aware we've made some updates to these sections, but it'd be helpful in estimating if we can outline what changes you're referring to that need to be captured in the docs. Maybe adding a brief summary, or linking to a related epics or ticket?

If the ask is to update use case docs for 3 sections w/ specific details about what changed, I'd estimate it at a 1 or 3. If it's "cross-check all documentation, recent FE work, and Sketch files and make sure everything is up to date" it'd be an 8 because of all the leg work involved to figure out what's what.

I see the AC is to "review all use cases" so maybe it is the latter. But just want to be sure

**Comment by BerniXiongA6** [comment]
@andaleliz Based on our 1:1, I'm making notes here for us. Seems as though Account Security documentation has some screen shots and links that need to be updated and could be included in the scope of this ticket. If that's the case, this particular documentation update could be a quick ticket. And, I also saw an opportunity for another ticket (possibly an epic) to be created for a future sprint to audit the current "use case documentation updating process" so we can favor evergreen content/avoid having to perform too much maintenance when UI updates are made. Happy to bring this up for discussion in Grooming and/or future sprint planning. Thanks!

**Comment by andaleliz** [comment]
@BerniXiongA6 you captured our 1:1 notes wonderfully, thank you. The Account Security documentation does indeed need to be updated (I added some details above to make it more specific) but it's likely some other things need to be as well. 

If no one else on the team has a sense of the specific updates that need to be made (I do not, though I don't think we've updated Connected Apps or Notification settings since the last big doc update), then I believe this is large effort that will essentially audit all of the documentation across our products. 

As discussed in our 1:1, this is a great learning opportunity for new folks on the team to become familiar w/ things - maybe Florence and/or the new PM could take it on, or help me, depending on the urgency of this work. Since it would probably go across 2 sprints, and hopefully have collaborators, it might be wise to create a ticket to audit each section of the profile that needs to be reviewed. What do you think? If so, this particular ticket could be the account security one.

Definitely agree w/ you on the opportunity to audit the current updating process, and that's a great way for the team to align and figure out how we can each contribute to the process.

**Comment by BerniXiongA6** [comment]
Thanks for the great ideas @andaleliz and for updating the details. Will definitely bring this up at grooming and before planning.

**Comment by Samara-Strauss** [comment]
Sections I know that need to be reviewed/updated now due to completed accessibility work:

- Personal information
- Account security **if Adam finishes and launches updates this sprint**. If not, this can wait since we don't update docs until changes are launched to prod.

Things that might need updates, but not sure:

- Sketch files and documentation links to where we show TTY numbers (see #49843)
- Sketch files and documentation links to any screens that show open form fields. Button pairs changed from Update/Cancel to Save/Cancel recently (see #49374). All screens may have been updated in the Sketch files, but it is worth confirming.

This could probably be broken into two or three tickets, I'm thinking something like this might be helpful:

- This ticket can be used for the personal info/account security updates
- Another ticket to review Sketch files for TTY updates, then review links in our documentation
- Another ticket to review Sketch files for Save/Cancel button updates, then review links in our documentation

I'm not prescribing that's how things be broken down, but I wanted to throw that out there in case it's helpful.

**Comment by andaleliz** [comment]
@Samara-Strauss that makes sense and it super helpful to see that outline. I'll break it out into 2 tickets - I'm 99% sure the work in the third bullet is complete and won't take much time.

Adding @fmccaf1 as an assignee in case she can get to this first, or wants to follow along for awareness

**Comment by andaleliz** [comment]
@Samara-Strauss I see a note in the Sketch file from Christina about the new pattern in account security that says "this design has not gone through collab cycle"

Did it ever? Should it have? Just curious.

**Comment by andaleliz** [comment]
> TBH now that it has launched, I don't know that there is much of a point in doing the process

That makes sense. It was reviewed with Angela for sure, so we can be confident it's accessible.

**Comment by andaleliz** [comment]
@adamwhitlock1 when you get a chance, can you confirm with me that [the mock-ups for this use case](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/account-security/use-cases/system-cant-access-records.md) and [this one](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/account-security/use-cases/system-cant-match-user-information.md) are accurate? Just want to be sure that we do still show the sign in information + 2FA section if we can't access records or find someone in MPI.

**Comment by adamwhitlock1** [comment]
> @adamwhitlock1 when you get a chance, can you confirm with me that [the mock-ups for this use case](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/account-security/use-cases/system-cant-access-records.md) and [this one](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/account-security/use-cases/system-cant-match-user-information.md) are accurate? Just want to be sure that we do still show the sign in information + 2FA section if we can't access records or find someone in MPI.

@andaleliz These look great! Since there are a combination of apis that get used to pull user info for profile, there _might_ be a slightly more 'expanded' account security list than just the 'add 2 factor` item, but overall I don't think that really would affect the mockups in that regard.

**Comment by andaleliz** [comment]
Awesome, thanks for checking that @adamwhitlock1!
