### ISSUE TITLE
MDT- Introduction page- Form introduction page - default state, v1

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5250]
## User story: 
As a Veteran interested in reordering medical device resupply items, I need an introduction about the ordering process so I know what to expect before placing my order. 

## Tasks: 
- Create a high fidelity mockup of the order flow introduction page 
- Upload mockup to Invision and indicate initial focus point as a comment 

## Acceptance criteria: 
- [x] Mockup aligns with VA.gov’s design system 
- [x] There is an alert notifying the Veteran that they are logged in
- [x] The subway map contains all of the steps the Veteran can expect during the order flow
- [x] (Optional) Any additional helpful content for the Veteran is included 
- [x] The screen’s initial focus point is incorporated
- [x] Sketch artboards are uploaded to Invision and linked in this ticket as a comment

## Next Steps 
- content review
- design review

## Dependencies: 
No currently known dependencies

**Comment by rileyorr** [comment]
Prototypes: [Desktop](https://vsateams.invisionapp.com/share/6CVSW1NTJB4) | [Mobile](https://vsateams.invisionapp.com/share/TKVSW1W9C3G)

**Comment by mr0sari0** [comment]
@rileyorr The desktop and mobile prototypes look good and conform to the VA's design system and I don't see any technical blockers.

I think this may be a yes but asking just in case. For the mobile prototype, would the expanded view of the accordions be a list of links similar to the footer of the desktop prototype?

Also for the mobile, do you know if the contact us accordion would have the same contact info listed in the need help section? If it is, would it be beneficial for the Veteran to have the same info listed more than once?

**Comment by rileyorr** [comment]
@mr0sari0 Thanks for taking a look at the screens and providing some feedback! I haven't used any accordions in the design. Would it be helpful to sync and review the screens together?

**Comment by rileyorr** [comment]
@mojaray2k Here's the _form introduction_ mockup. Let me know if you have any questions!

**Comment by mojaray2k** [comment]
@rileyorr Let's review the screens together.
