### ISSUE TITLE
[FE] Loading component is read aloud twice by Voice Over

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#52509]
## Summary

Loading information is read aloud twice with Voice Over on a Mac.

## Steps to reproduce
- Have Voice Over enable
- Log in to day of check in and you will hear "Loading Loading your appointments for today Loading Loading your appointments for today".

Note the fact that "loading" is immediately followed by "Loading your appointments for today" is a separate issue addressed by this ticket in the design system.

https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1457

## Tasks
- [ ] [FE] Fix repetition in Voice Over
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Voice Over reads "Loading, Loading your appointments for today"
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
@wullaski this ticket is in the current sprint, were you planning to pick this up?

**Comment by wullaski** [comment]
@loripusey, @brianseek and I determined that this is a bug with the design system. I'm updating the [design system issue](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1457) description with our findings. This can be closed.

**Comment by loripusey** [comment]
Great! thanks @wullaski ; closing
