### ISSUE TITLE
BE | Profile | Direct Deposit | Migrate GET Direct Deposit Info

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#52500]
## Background
Add functionality to retrieve direct deposit information from the Lighthouse API. This includes configuration, specs, attribute mapping, error handling, and logging.

## Tasks
- [x] Create Configuration
- [x] Create Service
- [x] Create Service Specs

## Acceptance Criteria
- [x] Service specs passing.
- [ ] PR reviewed and approved.

**Comment by Samara-Strauss** [comment]
Hey Tom! Checking in on the status of this ticket for planning purposes. How's it going?

**Comment by tpharrison** [comment]
Hi @Samara-Strauss.  I'm a bit behind on this ticket - I'll need to push this into the next sprint.  I should be able to move it to validation tomorrow (Thursday latest).

**Comment by Samara-Strauss** [comment]
Thank you for letting me know!
