### ISSUE TITLE
Change new FMP page from benefit detail page template to R&S

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#52504]
## Issue Description

After iterating on the content we are migrating for the Foreign Medical Program, we need to change the File a Foreign Medical Program claim from a benefit detail page to an R&S article in Drupal. 

Drupal page to work from: http://preview-prod.vfs.va.gov/preview?nodeId=49685

## Tasks
- [x] Create new R&S article with content from benefit detail page (Aliyah)
- [x] Review (Laura)
- [x] Copyedit (Megan)
- [ ] OCTO review (Danielle)
- [ ] Publish (Megan)

## Acceptance Criteria
- [ ] New R&S article is live

**Comment by aliyahblackmore** [comment]
Hi @laurwill this is ready for you! 
I change this FMP page from a benefit detail page template to a R&S detail page. 

**This is the preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=53151

**A few notes:** 

1. The benefits details page didn't have a CTA, wondering if we'd want to include CTA links to the other FMP pages? 

Find out how to get care through the Foreign Medical Program - http://preview-prod.vfs.va.gov/preview?nodeId=50826 

Learn how to Register for FMP - http://preview-prod.vfs.va.gov/preview?nodeId=50969

2. It looks like there isn't a featured content box (blue box) component for R&S articles. I included the information on the page as the first H2. 

3. I included the Getting care through the Foreign Medical Program page as the related information link.

**Comment by laurwill** [comment]
Thanks Aliyah! This looks great — I just added CTAs for the 2 related FMP pages to align with how the "Getting care through FMP" page does the CTAs. Then I added "Eligibility for VA disability" as the related link.

@megzehn , this is ready for you.

**Comment by megzehn** [comment]
Hi @laurwill and @aliyahblackmore, I finished copy editing [this FMP R&S page](http://preview-prod.vfs.va.gov/preview?nodeId=53151). 

One question: Under the **What to know before you file an FMP claim** H2, I added a jump link to "[Learn more about what care and services we cover through FMP](http://preview-prod.vfs.va.gov/resources/getting-care-through-the-foreign-medical-program#care-and-services-we-cover-thr)" to expand on the note a bit. Does that work?

**Comment by laurwill** [comment]
Yes! That works @megzehn . Thanks for adding that.

**Comment by laurwill** [comment]
Hi @DanielleThierryUSDSVA , I updated the 3 FMP pages in Drupal based on SME feedback. Would you like to review before we send back to SMEs for a final pass?

A few notes for you:
- In the eligibility language on the main page, their note was to put a bolded "or" between the 2 eligibility options. I don't think we want "or" there, but do we need the bolded "and"? I think this might be clearer with no bolded connector in between. (I changed "or" to "and" within the second bullet as SMEs requested.)
- We had a note to "consider a nod to privacy" related to the email option on the FMP form. Since our page doesn't list the email option, I decided not to add this and risk drawing more attention to that option.
- For the switch to lead with the main mailing address/fax options and then list Canada second, I left the H4 "If you live in Canada" because that seemed to scan best. But can switch to a note or a bolded intro phrase if you prefer.
- On the Getting care page, the link we originally had to travel.state.gov for info on covid vaccines in other countries is broken — it seems that page no longer exists, and I wasn't able to quickly find an alternative. I removed the sentence and link. I think it's okay without it.

**Comment by laurwill** [comment]
We did the work in this ticket — we'll continue tracking the FMP migration in this [Publish 3 FMP pages ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50748). Closing this out.
