### ISSUE TITLE
Move IA sitemaps from Moqups to Mural

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#52524]
To improve access and collaboration with teams, we are moving all IA documentation currently living in Moqups to Mural.  

Definition of done
- [x] An open room in Mural that includes all site maps is available to anyone to view, and available to the IA group for editing
- [x] A private workspace is available in Mural for draft/working files that all IAs have edit access to, and can be shared for collaboration as needed
- [x] All site maps currently in Moqups have been moved to the Mural open room
- [-] ~All draft and working files currently in Moqups have been moved to Mural or have been exported for future reference~
- [x] Each public site map has a global key/legend 
- [x] Each public site map has a navigation "feature" is available so visitors can easily move between different site maps
- [x] A work flow is established for when and how core site maps are updated as features are in development and launched
- [x] All internal comments and notes are removed from Mural site maps, and they are facilitator locked

**Comment by mnorthuis** [comment]
@kristinoletmuskat @jennymayoco Created this epic to track the work to move the site maps to Mural.  As you work on a site map, you can grab the issue and assign yourself, that way we will know who is working on which one. 

There is also a ticket to create a global key/legend to apply to each sitemap - I started one in Mural based on what I used in Moqups, but might be good to finalize that early on so we don't have to do a bunch of reformatting.  Keep in mind that the key can't be based on color alone to account for those that are colorblind. 

The other sort of global ticket is to create a means to navigate between the site maps, so as we build out these site maps they utilize essentially the same formatting key and have navigation options.

**Comment by mnorthuis** [comment]
All site maps complete and communicated out.
