### ISSUE TITLE
Create Mapped Mockup of 21-674 Workflow

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#5253]
## Goal
Create mockups to visualize the 21-674 sub-workflow within the larger 21-686c form workflow. Map fields to paper form to ensure all data is properly collected.

## Considerations
- For Jennifer Lee - you can submit both of these forms at once in some places, should we have a seperate form available for the 674?
- [Link to form](https://www.vba.va.gov/pubs/forms/VBA-21-674-ARE.pdf)

## Tasks
- [x] Create 21-674 mockups that only includes part I
- [x] Map all form fields to workflow mockups
- [x] Present mockups to team

## Acceptance Criteria
- [x] Mockups for 21-674 workflow are available to Frontend Engineering for implementation.

**Comment by sporeboy** [comment]
Workflow blocked-out and mapped to paper form. XD workflow begins here: https://xd.adobe.com/view/ffffe536-2ba5-47c6-4c4b-ac1679179973-89ce/screen/69053c5c-3aa3-41a8-8035-ff940a036995/Apply-Dependents-Add-Student-1
