### ISSUE TITLE
[Epic] Content and IA Request for vaccines domain and health history landing page from mhv-medical-records

### ISSUE THREAD

**Issue by alexiawunder** [department-of-veterans-affairs/va.gov-team#52547]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [x] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [x] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
TBD, but current estimate is 2024.
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: [Medical Records Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records)
- Link to or attach user flows:
     - [User flow](https://www.sketch.com/s/0803544d-e78c-423a-a70e-7db01a9a31c7/a/MybMyWw) This is tentative, pending IA research findings. 
- Link to prototype or mockups (these will be adjusted continuously until usability testing; more screens may be added later):
     - Health history (Medical records) landing page [Desktop](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/MybDm39)
     - Vaccines list page [Desktop](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/8B956FE2-A63F-48C8-B8F1-FF93329ACE0E)
     - Selected vaccine details page [Desktop](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/D898C623-9070-42F2-841A-A859BFC98D09)
     - [Modal: Choosing the file type to download
](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/D3F34518-813E-48BD-8367-48868DB4EB4E)
     - [Download success/fail alerts](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/E9BD7A74-E456-4DB3-AD2F-18CF8814E73F)
- Link to any epics/issues that may be helpful: TBD

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: TBD - this is only one domain out of the larger medical records product. 
- Estimated staging review date: TBD - this is only one domain out of the larger medical records product. 
- Content and IA work needed by: We'd like to conduct usability testing with approved content, which should happen late February at the earliest.

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: mhv-medical-records
-	OCTO-DE product owner: Lauren Alexanderson 
-	Product manager: Bryan Riley
-	Designer: Alexia Wunder, Bobby Bailey
-	FE engineer: Mike Moyer
-	Product/team Slack channel: #mhv-medical-records

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by alexiawunder** [comment]
Updated sketch links on 2/1

**Comment by alexiawunder** [comment]
Updated Sketch links on 2/3, as we had to split the original document into two separate files. For content purposes, please review the "[For Developers and Content](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/p/A47501F8-078B-42CF-977B-7BF9A31B3976/canvas#Version)" page. Please note, some of the buttons aren't rendering on the browser version correctly, so if you see a button with text on two lines, we are aware.

**Comment by alexiawunder** [comment]
Added link to the Product outline.

**Comment by laurwill** [comment]
Hi @alexiawunder ,
Documenting some updates and remaining questions here for vaccines:
- Here's a Word document with suggested teaser text for each domain: [https://app.zenhub.com/files/133843125/bef04a93-cc1b-412a-ab9e-a897afb267bd/download](https://app.zenhub.com/files/133843125/bef04a93-cc1b-412a-ab9e-a897afb267bd/download)
- Added some questions to the [download success/errors screen ](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/4aROkyA)
- Added new comments in the list and detail screens, including a suggested approach to the "disclaimers" text.

Remaining questions for vaccines screens: 
- Can we get sample data for the series field? We're wondering if that will need more explanation.
- How common is it for users to self-enter vaccine records? We haven't included links to the allergy domain or notes about reactions appearing there, after conversation with @coultonbunney-usds about waiting until we get more information about this.

**Comment by bryan-riley-va** [comment]
No longer needed
