### ISSUE TITLE
Content changes to education letters tool 

### ISSUE THREAD

**Issue by katherine-fung** [department-of-veterans-affairs/va.gov-team#52549]
## Issue Description
Hi Bobby, 

Thanks for your collaboration as we continue to work on the education tools. As @bethpottsVADEPO mentioned, we have some content changes to the education letters tool to bring it into alignment with the static page and to ensure consistent terminology for education letters. 

I’m providing here the reworked content we’d like to request and a breakdown of the reasoning behind the changes. I’ll also note that these changes will address all 5 content-related collab cycle tickets as well as some accessibility tickets. So there will be much less follow-up work for your team post-launch.

### Breakdown

**For the entire tool** (addresses tickets #51872 and #51868) 

Our reworked content refers to “education decision letters” in subheads and link text. Until this tool includes more types of letters, we want to be clear that this specific letter is what can be downloaded at this time. The H1 will remain “Your VA education letter” to match the breadcrumb and the static page H1.

In running text, we’ve used the shortened "decision letters."  We think this shorter phrase is sufficiently clear in running text that's nested under headers.

**For the screen where there is a letter available**

1.	(addreseses tickets #51868, #51869 and #51878) We’ve placed the information that was in the info alert “COE Decision Letter Update” in a note below the information about the user’s letter. The reworked content ensures consistent terminology (this was the only place COE was mentioned in the tool). It also consolidates the content in one place—the use of the info alert unnecessarily separated the messaging.  
  
2.	The reworked content accounts for the fact that the user may have a denial letter. 

3.	(addresses ticket #51879) The only change to the subway map is to remove the headers, so it’s all plain text. 

### Here's the re-worked content (Updated the content for "no award or denial letter" on 2/2/23): 

**Page with no award or denial letter for download**

[H1]Your VA education letter

[INTRO] Check this page for your education decision letter for Post-9/11 GI Bill benefits.

[information alert] [H2] Your education decision letter isn’t available

If you applied for Post-9/11 GI Bill benefits on VA.gov but didn't receive an instant decision, your decision letter may not be available here yet. It can take us up to 30 days to make a decision after you submit your application. Check back soon to find out if your decision letter is available.

You won't be able to get your decision letter through this tool if 1 of these is true for you:

- We made a decision on your Post-9/11 GI Bill benefits before August 20, 2022, **or**
- You're a family member or a dependent of a Veteran

You can get your decision letter by contacting us online through Ask VA instead.

[Link] [Request your education decision letter through Ask VA](https://ask.va.gov/)

[H2] What if I have other questions?

You can contact us online through Ask VA.

[Link] [Contact us online through Ask VA](https://ask.va.gov/)

**Page with decision letter for download**

[H1] Your VA education letter

[INTRO] Check this page for your education decision letter for Post-9/11 GI Bill benefits.

[H2] Your education decision letter is available

This decision letter is for the claim you submitted for Post-9/11 GI Bill benefits on the date listed here.

You applied for benefits on Month Date, Year.

[Link] Download your education decision letter (PDF)

Note: If we asked you for more information and you’ve submitted it, this may not be the most recent decision letter. We'll send you a new decision letter by mail. 

[H2] How do I download and open my education decision letter?
[Change this one sentence that starts with "Note: If the PDF form opens in your browser automatically..." to 

"Note: If the PDF letter opens in your browser automatically"...

Keep the rest of the text as is, just show plain text instead of headings for each step]

[H2] What if my education decision letter isn’t here?

This tool has decision letters for decisions we made on or after August 20, 2022. If we decided your claim before this date or if you want to request a different type of letter, contact us through Ask VA.

[Link] [Contact us online through Ask VA](https://ask.va.gov/) 

---
## Tasks
- [ ] Update the tool content to reflect the re-worked content 

## Acceptance Criteria
- [ ] The tool uses consistent terminology for letters
- [ ] A note replaces the COE info alert
- [ ] The screen with a letter to download accounts for denial letters
- [ ] The instructions for how to download a letter are plain text without headings

**Comment by btruongafs** [comment]
@katherine-fung we already completed the changes you noted in the word document on https://github.com/department-of-veterans-affairs/va.gov-team/issues/50494#issuecomment-1382645729. Is this request different than that?

**Comment by katherine-fung** [comment]
Hi @btruongafs - yes, these changes are different. 

Apologies but the Word doc in #50494 was a draft meant for @bethpottsVADEPO to review. The content team uses tickets to share suggested content so we can get each other's feedback, before it's ready to publish. In future, you can disregard any similar Word docs unless we tell the product team that it's the final content. 

Sorry for the inconvenience!

**Comment by TamGIBill** [comment]
@bethpottsVADEPO @btruongafs @katherine-fung 
We need to add additional content as the first bullet here:

Your decision letter isn’t available here for 1 of these 2 reasons:
• We made a decision on your Post-9/11 GI Bill benefits before August 20, 2022, or
• You're a family member or a dependent of a Veteran

Content to add:
You did not receive an immediate decision on your most recent Post-9/11 GI Bill benefits application. A decision can take up to 30 days after you submitted your application. Please return to this page to check for your decision letter.

**Comment by katherine-fung** [comment]
Thank you @TamGIBill! That's a helpful addition. We'd like to suggest a slight variation, for site style and plain language. cc @btruongafs @bethpottsVADEPO  

Your decision letter may not be available here for 1 of these 3 reasons:

- You applied for Post-9/11 GI Bill benefits within the last 30 days and we haven't made a decision yet, **or**
- We made a decision on your Post-9/11 GI Bill benefits before August 20, 2022, **or**
- You're a family member or a dependent of a Veteran

**Comment by TamGIBill** [comment]
@katherine-fung the first one is the only one where they can check back and have a decision letter available.  I would like to make that clear.
@btruongafs @bethpottsVADEPO

**Comment by btruongafs** [comment]
@katherine-fung  can you weigh in on the feedback today? we would like to implement this changes asap

**Comment by katherine-fung** [comment]
Hi @btruongafs @TamGIBill , here's the content for that page.   

**Page with no award or denial letter for download**

[H1]Your VA education letter

[INTRO] Check this page for your education decision letter for Post-9/11 GI Bill benefits.

[H2] Your education decision letter isn’t available here

If you applied for Post-9/11 GI Bill benefits within the last 30 days, we may not have made a decision yet. Check back soon to find out if your decision letter is available.

You won't be able to get your decision letter through this tool if 1 of these is true for you:

- We made a decision on your Post-9/11 GI Bill benefits before August 20, 2022, or
- You're a family member or a dependent of a Veteran

You can get your decision letter by contacting us online through Ask VA instead.

[Link] Request your education decision letter through Ask VA 

[H2] What if I have other questions?

You can contact us online through Ask VA.

[Link] Contact us online through Ask VA

**Comment by TamGIBill** [comment]
@katherine-fung @btruongafs @bethpottsVADEPO 

This isn't correct.  

"If you applied for Post-9/11 GI Bill benefits within the last 30 days, we may not have made a decision yet. Check back soon to find out if your decision letter is available."

They will have to have submitted their application online through the MEB tool, which this is implying. "You did not receive an immediate decision on your most recent Post-9/11 GI Bill benefits application."

**Comment by bethpottsVADEPO** [comment]
@TamGIBill I'm not sure I'm understanding the use case. Are you wanting this to say that the user doesn't have a decision letter available in the tool at this time because they didn't receive an immediate decision when they submitted their Post-9/11 GI Bill application?

**Comment by bethpottsVADEPO** [comment]
@TamGIBill And one more thing: They should check back because it will become available in this tool?

**Comment by TamGIBill** [comment]
@bethpottsVADEPO Yes, it is not here because it wasn't decided through the automation process but it will be available once a VCE reviews it and makes a decision.  Once that decision has been made, it will be available.

**Comment by bethpottsVADEPO** [comment]
Thanks @TamGIBill -- I think I get it now:

If you applied for Post-9/11 GI Bill benefits on VA.gov but didn't receive an instant decision, your decision letter may not be available here yet. It can take us up to 30 days to make a decision after you submit your application. Check back soon to find out if your decision letter is available.

**Comment by bethpottsVADEPO** [comment]
@TamGIBill If you can verify that this messaging is accurate, I think this may be the last detail we need to wrap up!

**Comment by TamGIBill** [comment]
That works

**Comment by btruongafs** [comment]
@katherine-fung @bethpottsVADEPO  can you modify the original requested with the final edits? Just want to make sure its all in one place

**Comment by btruongafs** [comment]
@katherine-fung @bethpottsVADEPO one more clarification. Are we removing the info alert (shown [here](https://share.goabstract.com/4153d410-1183-4818-9c69-8c338c526b1b?collectionLayerId=ce7c707d-c93c-43db-b76a-1324496659ba&mode=design&present=true)) all together?

**Comment by katherine-fung** [comment]
Hi @btruongafs, I updated the original request with the new messaging. 

I've also now noted that the content is inside an info alert. 

cc @TamGIBill @bethpottsVADEPO

**Comment by btruongafs** [comment]
@katherine-fung I think you just updated the comment: https://github.com/department-of-veterans-affairs/va.gov-team/issues/52549#issuecomment-1409265964 and not the ticket itself

**Comment by bethpottsVADEPO** [comment]
@btruongafs I just updated the top of the ticket with the latest version. I think that's what you meant?

**Comment by btruongafs** [comment]
@bethpottsVADEPO yes! thank you. just want it all in one place to be referenced and clarify the final copy.

**Comment by btruongafs** [comment]
Content was updated. Let us know if it all looks good.

**No Letter Available**
![image](https://user-images.githubusercontent.com/111913467/217099250-060fc047-331a-4a11-a46f-bf297b328d82.png)

**Letter Available**
![image](https://user-images.githubusercontent.com/111913467/217099429-1ec81536-5051-43a9-83f7-f19fb3aad6e4.png)

**Comment by TamGIBill** [comment]
@katherine-fung @btruongafs 
Content looks good.

**Comment by katherine-fung** [comment]
I'm sorry all, one more small tweak to this. 

In the screen with a letter available, we use the phrase "PDF form" but it should say "PDF letter" 

I'll update the original ticket with this change so it will be reflected in the requested content.

**Comment by btruongafs** [comment]
No problem the content tweak has been updated with https://github.com/department-of-veterans-affairs/vets-website/pull/23320
