### ISSUE TITLE
Mockup and Content for Redesigned View Dependents/Add Dependents Landing Page

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#5255]
## Goal
Create mockup of landing page for View Dependents/Add Dependents. Revise layout and content of existing Add dependents page to include entry point(s) to View and Add. Edit content to address page length and added links to View and Add.

## Considerations
- Here is the [IA Recommendation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-view-dependents.md)

## Tasks
- [x] Create landing page mockup
- [x] Edit copy, writing new content as needed
- [x] Submit to Peggy for copy edits

## Acceptance Criteria
- [x] Mockup for Add Dependents landing page created and available for content team and IA review

**Comment by sporeboy** [comment]
Copy and design revisions are underway. Each workflow is broken-out here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design

**Comment by sporeboy** [comment]
Final IA review and recommendations are here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-dependents.md

**Comment by sporeboy** [comment]
Initial edits in place for landing page here: https://xd.adobe.com/view/8cdfe895-c907-4662-7234-305056778b2a-faee/
