### ISSUE TITLE
Alerting for failed deploys

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#52560]
## Description
No one is alerted when a deploy posts a failure message in #devops-deploys. Should someone, or some team, be monitoring the channel for failures? Should an `@here` notification alert the channel when certain deploys fail, as is done in #vfs-platform-builds for `vets-api`?

## Background/context 
This issue is an action item from the Postmortem
* https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/689

If someone had noticed the failed vets-api-worker and server deploys, the issue could have been caught earlier and would have likely prevented this outage from occurring.

---
## Tasks
- [x] Maybe talk to Clint to determine who is responsible for keeping an eye on #devops-deploys? 
- [x] and/or re-configure the messaging to `@here` on failed deploys in #devops-deploys. 

## Acceptance Criteria 
- [x] A failed deploy is a LOUD event (something happens. people know quickly)

**Comment by laineymajor** [comment]
This is related to BRD. Might no longer be relevant. 
There is potentially another ticket that will replace this one. 

@LindseySaari will look into this ^^

**Comment by LindseySaari** [comment]
I cannot find the ticket I thought existed. But anywho, I think we want to change this ticket to be titled as "Alert for sync failures" cc @laineymajor

**Comment by LindseySaari** [comment]
I created a manifest failed to generate error here. Going to continue to look for failed sync errors. https://vagov.ddog-gov.com/monitors/122396

**Comment by LindseySaari** [comment]
[Created a failed to sync monitor here](https://vagov.ddog-gov.com/monitors/122404), but want to figure out how to include the name (which includes the env) as info in the alert

**Comment by laineymajor** [comment]
With Rebecca.
