### ISSUE TITLE
[FE] Address validation: Review product outline and update if needed

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5256]
## Background

We need to update the address validation documentation since it hasn't been maintained through the project.

## Tasks

- [ ] Review the How to Access and Test, Error Handling, Service Level Objective, and API Calls and Dependent Systems sections of the [candidate address validation product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/change-address/address-validation/product-outline.md#error-handling).
- [ ] Update these sections as necessary
  - Note: if no updates are needed beyond what is there, please comment on this thread and let me know.

## Acceptance criteria

- [ ] The sections of the product outline listed above have been reviewed and updated as necessary.

**Comment by MickinSahni** [comment]
Associated this with Sprint 15

**Comment by bradl3yC** [comment]
@Samara-Strauss had Kelson review from Public Website, he did not see any glaring changes that need to be made.

**Comment by Samara-Strauss** [comment]
Great! We can close this out, then.
