### ISSUE TITLE
Update and link AWS Parameter Store doc

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#52565]
## Description
Update and link Platform documentation for developers who add things to AWS Parameter Store and do look-ups in their code.
**Platform documentation**:
https://depo-platform-documentation.scrollhelp.site/developer-docs/store-a-secret-in-parameter-store
**Editable here**:
https://vfs.atlassian.net/wiki/spaces/pilot/pages/1474595172/Store+a+secret+in+Parameter+Store

Some content in that page is outdated, so we should polish it up before sharing it widely. Include a section about spacing, especially with regards to RSA keys.

With automation, link the documentation in a PR that includes an `ssm` lookup. This could be done in a GitHub Action.

## Background/context 
This issue is an action item from the Postmortem
* https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/689

An improperly-formatted RSA key in AWS was the culprit of the outage.

---
## Tasks
- [x] Update Platform website
- [x] Create automation to link the documentation during code review process

## Acceptance Criteria 
- [x] Docs updated and verified by another human
- [x] Automation is merged and working as desired

**Comment by laineymajor** [comment]
Adding to current sprint --- vets api documentation related

**Comment by LindseySaari** [comment]
The automation piece is documented in another ticket and seems outside of the scope of documentation updates.

**Comment by LindseySaari** [comment]
I added a Formatting Caveats section to the Parameter store doc: https://vfs.atlassian.net/wiki/spaces/pilot/pages/1474595172/Store+a+secret+in+Parameter+Store#Formatting-Caveats

**Comment by LindseySaari** [comment]
The automated GHA to remind users of the formatting can be found here: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/.github/workflows/alert-aws-rsa-format.yaml
