### ISSUE TITLE
[eFSR] Mini Summary Card Component

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#52569]
## Issue Description
Create a reusable react component to display/edit/delete items in a list to be used for the "mini summary" pages. 

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/3a0ff047-2457-4388-946e-4d2e2f72baa2)

Component needs to take in header, text content, and event handlers for edit and delete. Delete button styling may be tricky as it includes some custom stuffs:
![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/1276131f-4418-4606-8e24-db73b7f8cd5b)

Functionality is more important than styling here since other tickets depend on this, so we can always circle back with a styling ticket to update. 

---
## Tasks
- [ ] Create reusable component 
- [ ] Test functionality 

## Acceptance Criteria
- [ ] Component matches design and functionality

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
Rolling over once more to focus on testing for Other Assets ticket that covered the mini summary page. Base card is in place, but styling isn't totally complete. Need to get smaller sized card to act appropriately, and confirm Link functionality is the best choice that will work in a majority of cases.

**Comment by mgleo** [comment]
@Dr-Pongo [Notes from Design System meeting on Fri](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/52774#issuecomment-1456409338)

**Comment by Dr-Pongo** [comment]
Closed out with https://github.com/department-of-veterans-affairs/vets-website/pull/23548
