### ISSUE TITLE
Alert for failed sync in ArgoCD for `vets-api-*`

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#52572]
## Description
If there is a failed sync in ArgoCD for `vets-api`, get alerted, similar to the external secret failed to sync alert ([external-secrets.yaml](https://github.com/department-of-veterans-affairs/devops/blob/890d9a02f4c120cb4ac04722059cf269b4d12975/terraform/environments/datadog/catalog/external-secrets.yaml)). Currently, someone only sees the alert if they're looking for it. Routing the alert might need to be different based on environment. 

Make sure the alert isn't spammy. The messaging in the alert needs to be actionable. What needs to be done to resolve this alert or what needs to be investigated? If the action items are verbose, add a section to [alerts.md](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/OnCall/alerts.md) and link to it in the alert's message.

## Background/context 
This issue is an action item from the Postmortem
* https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/689 

*[High-level Datadog Confluence documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/2236612646/Monitor+Applications+and+Infrastructure+with+Datadog)

---
## Tasks
- [ ] Write Datadog alert (using terraform)
- [ ] Update alerts.md and add link in alert messaging (if applicable).
- [ ] After the PR has been approved, get a DevOps eng to run the terraform and merge the PR.

**Comment by rmtolmach** [comment]
There might be an Argo/Slack integration that we can use to get alerted.

**Comment by rmtolmach** [comment]
I will come back to this once higher priority items are complete

**Comment by rmtolmach** [comment]
This is BIG and can have lots of causes. @oseasmoran73 thinks that breaking this alert up into the _reasons_ why the pods are failing to sync is the best option. The reasons are: db migrate failing (#55297), containers failing to start (#54253), and pods not running (https://github.com/department-of-veterans-affairs/va.gov-team/issues/54255). 

Let's close this ticket since we are creating alerts for the smaller reasons a sync would have failed. 

@LindseySaari FYI ^^
