### ISSUE TITLE
Enforce environment-specific PRs

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#52570]
## Description
In `vsp-infra-application-manifests` repository, require PRs to be submitted for each environment developers want to update. They can submit them all at once, but reviewers need to review and merge them as individual units and make sure the code from the lower environments don't cause anything to break before moving on to each higher environment. This could be a gha that checks paths to make sure it's just one env. Another feature creep idea is to check the number of lines added to secrets.yaml to see if it's over a certain number. We could limit it to a certain number. 

Is it possible to validate the PRs in the manifests repo before the related `devops` PR is merged?

## Background/context 
This issue is an action item from the Postmortem
* https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/689

In this incident, all envs were merged at once. dev and staging were fixed, but prod was not.

---
## Tasks
- [x] GHA to enforce since environments per PR
- [x] make lower envs go out together; keep prod separate 
- [x] when we are on tier 2, and are reviewing PRs, place the vets-api tag on the PR
- [x] update the GH pr template to include the vets-api pr

## Acceptance Criteria 
- [x] GHA is reviewed and merged

**Comment by laineymajor** [comment]
Revisit the need to enforce env specific PRs if secrets are being updates with a GHA.

**Comment by laineymajor** [comment]
notes from LT/LH meeting: per Lindsey, if you are changing anything in a lower env, you cannot also have a prod pr.

**Comment by LindseySaari** [comment]
Working on the GHA piece of this ticket

**Comment by LindseySaari** [comment]
All PRs are merged!
