### ISSUE TITLE
[Development] Remove lodash/fp from front-end application code

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#5257]
## User Story:
Remove all instances / usages of lodash/fp in an attempt to help minimize lodash bundle size being sent to all visitors of va.gov.  This will, in turn, reduce load times and potentially optimize performance of other components previously leveraging this library.

## Tasks
- [ ] Research whether lodash sends a new object/immutability issue
- [ ] Use platform helper methods / native javascript / lodash to replace lodash/fp where applicable
- [ ] Verify all unit tests pass in place without modification

## Acceptance Criteria:
* Bundle size has shrunk
* Regression testing completed - site still works as before

## Configuration
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Samara-Strauss** [comment]
Platform team is reviewing. Leaving open for now until we determine if they need anything else from Brad.

**Comment by bradl3yC** [comment]
See issue #13253 for progress on breaking up this PR / merging.  Auth exp work on this has been completed
