### ISSUE TITLE
Develop local script to check syntax of Parameter Store values

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#52585]
## Description
It would be handy to have a script that PR reviewers could run locally that checks the syntax of Parameter Store values. @ph-One has a script that could be expanded on. We would not want to run this as a GitHub Action because of security concerns. 

## Background/context 
This issue is an action item from the Postmortem
* https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/689

We relied on visual validation of the RSA key, which ended up failing us (and `vets-api`). A syntax checker could have saved the day!

---
## Tasks
- [ ] Talk to @ph-One about developing a script
- [ ] Write up a doc on how to run it

## Acceptance Criteria 
- [ ] script is successful in finding improperly-formatted Param Store values.

**Comment by RachalCassity** [comment]
aws ssm get-parameters --name 'aws-paramater-path' --with-decryption

**Comment by laineymajor** [comment]
We need to determine a process to get all of these things done in collaboration with kyle and the devops cop

**Comment by laineymajor** [comment]
@RachalCassity do you think we still need this?
