### ISSUE TITLE
ArgoCD and EKS training for vets-api

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#52580]
## Description
Develop documentation and training related to `vets-api` in ArgoCD and EKS for Platform developers, especially Tech Support Team developers. As the Platform moves `vets-api` from BRD to EKS, more people will need to be well-versed in debugging in ArgoCD. 

[WIP] Content should answer the following questions:
1. Why do I care?
2. When will I interact with ArgoCD?
3. What does a healthy and an unhealthy `vets-api` look like in ArgoCD?
4. How do I find the errors?
5. What are some common errors? 

## Background/context 
This issue is an action item from the Postmortem
* https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/689

`vets-api`'s move from BRD to EKS is accelerating and it's clear Tech Team 1 aren't the only people who should monitor the health of `vets-api` in EKS.

---
## Tasks
- [ ] Documentation and/or training developed
- [ ] Documentation updated with clarity and specificity 
- [ ] Orientation updated

## Acceptance Criteria 
- [ ] Training has been done

**Comment by rmtolmach** [comment]
This will likely fit into our Documentation phase of the EKS migration.

**Comment by laineymajor** [comment]
@laineymajor put in documentation epic

**Comment by laineymajor** [comment]
Moving all doc updates to end of the project so we do not duplicate our own efforts.

**Comment by laineymajor** [comment]
This has been included in the backend orientation with speaker notes.
