### ISSUE TITLE
[Design] HLR: Update Higher Level Review Design Artifacts After Usability Testing Research

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#5259]
## User Story:
As a veteran, I need a submit requests for higher level review in an easy to navigate and understand fashion so that I can successfully get my benefits.

After the usability testing research, we have a number of redesigns that will occur.  This story is a placeholder until we get a chance to review the finding fully.  Some of the high level suggestions from the readout include:

* Intro page: #5347
* Opt Out page: #5351
* Add Notes page: #5611
* Same Office page: Participants  are confused about this page. Users want the contextual  info to be available upfront. Reading the info, users think their choice will not matter. (“VA will do what they want”.)
* Informal conference page: Users think they are scheduling the conference here. They assume they will receive a call the next couple of days with a time for the conference. Users want to choose day(s) of week,  a range of dates, an option to contact both representative and themselves, and an option to  add an alternate phone number.

## Tasks
- [x] Update InVision wireframes.
- [x] Split off stories for different design changes (possibly) from research findings

## Acceptance Criteria:
* Delivered updated wireframes
* Design reviewed and accepted

## Configuration
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
Changes to informal conference page as well as same office page were completed as part of this ticket and can be found here:

Same Office: https://vsateams.invisionapp.com/share/W5U21BDFTQK#/404630136_HLR_Contested-Issues-Same-Office

Informal Conference: https://vsateams.invisionapp.com/share/W5U21BDFTQK#/404685158_HLR-Request-Informal-Conference-2
