### ISSUE TITLE
Update fiduciary page with new info from SMEs

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#52598]
## Issue Description
Angie Smith sent us requested changes for the fiduciary claims page. In the future, we'll migrate all the legacy fiduciary content to our pages. For now, we'll make smaller updates to add the requested info about Supplemental Claims for fiduciary claims.

Word doc with requested revisions:
https://app.zenhub.com/files/133843125/c1b4da81-fbb1-464b-957a-b8fe0f36cef8/download

Change request form: https://app.zenhub.com/files/133843125/92480e57-3ac7-4e27-a5c1-c938cf652b1f/download

---
## Tasks
- [ ] Suggest updates
- [ ] Review and send to SMEs
- [ ] Copyedit and publish (Megan)

## Acceptance Criteria
- [ ] Fiduciary page is updated with new info

**Comment by laurwill** [comment]
Hi @strelichl @RLHecht , we made the immediate accuracy updates to clarify that you can file a Supplemental Claim for a fiduciary claim, but we didn't add all the detailed info about evidence for fiduciary claims that Angie provided in the first doc linked above. So this is half done. 

I think the question now is: Are we migrating the rest of the fiduciary program content anytime soon, and could we roll this in with that? Or do we put it in icebox, since it's no longer an urgent accuracy issue?
