### ISSUE TITLE
Assess existing pages with T&C, terms of use, or privacy policy content

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#52596]
## Issue Description
To prepare for the launch of the [unified terms of use page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/51681), we need to identify existing pages that have terms of use content and assess whether we need to retire or update these pages.

Pages include:
- Medical T&C page (looks to be an orphan): https://www.va.gov/health-care/medical-information-terms-conditions/ 
- sign-in modal: https://www.va.gov/?next=loginModal 
- privacy policy page: https://www.va.gov/privacy-policy/

---
## Tasks
- [ ] Audit pages to find terms of use language
- [ ] Confirm with T&C team whether these pages need updates
- [ ] Update or retire pages

## Acceptance Criteria
- [ ] Pages with outdated terms content are updated or retired

**Comment by aliyahblackmore** [comment]
Hi @laurwill -  as we chatted last week I worked on the following: 
 
- I did a review of the first two links under "Terms & Conditions / terms and conditions" to determine areas of overlap with the launch of the unified terms of use page content (you shared the SharePoint doc via slack). The remaining pages have links and checkboxes - you flagged that at this time we don't need to do a review/comparison of those pages.
-  On each page I highlighted the sections that seem to overlap with content in the unified terms of use and used comments to note the specific sections or content in the terms of use.


[This is a SharePoint document for the digital notifications terms and conditions page ](https://dvagov-my.sharepoint.com/:w:/g/personal/aliyah_blackmore_va_gov/ERZ2Ytb9qZtOiV4pE1MK_CEBG7X2PjPkJ2DLL2q4mjd24A?e=rjhH46)
[This is a SharePoint document for the Privacy, policies, ad legal information page ](https://dvagov-my.sharepoint.com/:w:/g/personal/aliyah_blackmore_va_gov/EZT8C8Lsxf1Bj3ksSjlRCMYB5qhBw2FosxrPchzjelAjOA?e=QNq3Gw)

- Both pages have a few sections and pieces of additional information that aren't included in the terms of use. 

As a next step, we'll determine with Danielle if this content will get replaced by the new terms of use or if we'll maintain these pages because they have additional or different information that's not included in the terms of use.

**Comment by laurwill** [comment]
Update: We won't make any changes to Privacy policies or Digital notifications pages at this time. We'll follow up in 2024 about any potential changes to those pages.

**Comment by laurwill** [comment]
Hi @aliyahblackmore , when you have a moment, could you update the link text in the 3 education pages in the list to specify "GI Bill trademark terms of use" rather than just "our terms of use"? That's the only update we need to make directly for this phase of the work. Then you can pass to Chelsea or Megan to check and publish.

Also documenting here that Danielle will reach out to the Sitewide Facilities team to coordinate communication with medical centers about sign-in and ToU-related content on their facility pages. No next steps for us on those pages.

@strelichl after Aliyah does the education pages in the list, I think we can close this ticket and open a low priority backlog ticket to assess additional changes to the Privacy, policies, and legal information page after the ToU launch.

**Comment by aliyahblackmore** [comment]
Thanks @laurwill !

I changed the link text on the 3 education pages to be "Read our GI Bill trademark terms of use" 

@megzehn or @chelsealevinson these pages are ready for you all to review and publish.

**Pages:** 
[Montgomery GI Bill Selected Reserve (MGIB-SR)](https://preview-prod.vfs.va.gov/preview?nodeId=934)
[Montgomery GI Bill Active Duty (MGIB-AD)](https://preview-prod.vfs.va.gov/preview?nodeId=932)
[Post-9/11 GI Bill (Chapter 33)](https://preview-prod.vfs.va.gov/preview?nodeId=935)

**Comment by chelsealevinson** [comment]
Confirming I reviewed changes and published all three pages. Thank you both!
