### ISSUE TITLE
[loadtest-locust] Application onboarding requirements checklist

### ISSUE THREAD

**Issue by considerable** [department-of-veterans-affairs/va.gov-team#52599]
## Description of application
Locust is a scalable load-testing tool written in Python (https://github.com/locustio/locust/)

### Basic info:
**Team Name:**   platform-tech-team-1
**Application Name:**  loadtest-locust
**Functionality:**  load generator for app stress-testing
**Language/Stack:**  Python
**Ports/Networking needed:**   "8089,5557" for web-port and master-port
**Other infrastructure needed:**  n/a

### Background/Context/Resources
Load Testing Plan https://github.com/department-of-veterans-affairs/va.gov-team/issues/52017

### Technical Notes
- https://aws.amazon.com/blogs/containers/load-testing-your-workload-running-on-amazon-eks-with-locust/
- https://github.com/department-of-veterans-affairs/devops/tree/master/loadtest

---

### Application repository and container 
- [x] **GitHub repo:** https://github.com/department-of-veterans-affairs/loadtest-locust
Note: app should conform to the 12 factor app methodology | [Docs](https://12factor.net/)   
_Requesting team_  
- [x] **Dockerfile:** https://github.com/department-of-veterans-affairs/loadtest-locust/blob/main/Dockerfile | [Example](https://github.com/department-of-veterans-affairs/platform-console-api/blob/master/Dockerfile) | [Docs](https://docs.docker.com/engine/reference/builder/)  
_Requesting team_  

### Application delivery pipeline (CI/CD)
- [x] **AWS service account for GitHub actions** `svc-gha-testingteam-user` | [Request here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=operations%2C+devops%2C+needs-grooming&template=ops_issue_template.md&title=)  
_Infrastructure Team_
- [ ] **AWS Elastic Container Registry (ECR) repository for the app container:** Submit PR to add your application name to the "all-repos" section of [this page](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/ecr.tf)  
_Requesting team_  
- [ ] **Add semantic release configuration (a `.releaserc` file) to your repo** | [Example](https://github.com/department-of-veterans-affairs/vsp-infra-calico/blob/main/.releaserc) | [Docs](https://semantic-release.gitbook.io/semantic-release/)    
_Requesting team_  
- [ ] **Automation to push the app's container to ECR with a semantic version number** | [Example](https://github.com/department-of-veterans-affairs/vsp-infra-calico/blob/main/.github/workflows/mirror-images.yaml)    
Note: Use `sha` or semver. Don't use default "latest" tag. The release system uses modified container image tags to synchronize automation.  
_Requesting team_  

### Application secrets and parameters
- [x] **AWS SSM Parameter Store path created for your team or app,**  `/dsva-vagov/testing-team/` | [Request here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=operations%2C+devops%2C+needs-grooming&template=ops_issue_template.md&title=)  
_Infrastructure Team_
- [x] **AWS SSM Parameter Store parameters that the app needs to run,** ie `/dsva-vagov/testing-team/common/svc-gha-testingteam-user/AWS_*` | [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/Store-a-secret-in-Parameter-Store.1474595172.html)  
_Requesting team_

---
Once the checklist is complete, you will be ready to onboard your application. Visit [Manage applications in EKS](https://vfs.atlassian.net/wiki/spaces/OT/pages/2348909545/Manage+applications+in+EKS) to get started.

### Notes 
- Please add comments to this issue as checklist items are completed, and...
- Tag the Infrastructure Team's product manager and product owner to help expedite the process

**Comment by considerable** [comment]
[Application to Onboard: [loadtest-locust] #52678](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52678)

**Comment by laineymajor** [comment]
@considerable @LindseySaari from my understanding, we aren't going in this direction anymore, correct? Can we close or move this to the backlog? Thanks!

**Comment by considerable** [comment]
Yes, let us please close it.
