### ISSUE TITLE
[FE] My VA Audit Improvements: Implement design updates to Saved Applications section

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#52619]
## Background
Per #52618, we need to make some updates to the design of the Saved Applications section to provide more clarity around what applications actually are and when/why Veterans would see applications in this section.

[FE documentation for Benefit Application Drafts section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/applications-FE-documentation.md)

## Tasks
- [x] Implement the changes: change section name from "Saved applications" to "Benefit application drafts"
- [x] Implement changed text for empty state to "You have no benefit application drafts to show."
- [x] Test
- [x] Move to validate and notify PMs that's it ready for testing once on staging

## Acceptance Criteria
- [ ] The updated design is visible on staging and matches the sketch file and specs per Angela's guidance in #52618 

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_  Any team member
- _How can this work be validated?_ 
           1. Log into staging with test user 10
           2. Scroll to the Benefit application drafts section on My VA
           3. See that the section matches the Sketch file

**Comment by ajakabcin** [comment]
created by mistake

**Comment by allisonlu** [comment]
Wanted to note that the one of the [test case intended outcomes](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva.md#applications-in-progress) on the `va.gov-team-sensitive` repo needs to be updated. Should I open a PR for this or can I edit this directly?

**Comment by ajakabcin** [comment]
Thanks for flagging @allisonlu ! I have that on my to-do list for QA prep. But for future reference you're able to edit directly yourself - no pr needed :)

**Comment by ajakabcin** [comment]
Confirmed with user 15 on staging (no drafts in progress) and user 150 (draft application) - great work!
