### ISSUE TITLE
Create content to alert DS Logon users about Login.gov transition

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#52626]
## Issue Description
Carl Dickerson reached out to determine the best way to alert people who are still using DS Logon that they'll need to create a Login.gov account. 

One idea we talked about is creating a modal or interstitial page that only appears when users select DS Logon in the sign in modal. This content would tell them we noticed they're using DS Logon and explain the next steps to create a Login.gov and start using that to authenticate for VA tools.

Estimated timing for publishing this content is May 2023.

Questions to answer:
- Can we show this content only to users who select DS Logon?
- Would it appear before or after users go to DS Logon site to authenticate?
- Is a modal or interstitial page the best approach here? Or would an alert be better—and where would the alert appear?

---
## Tasks
- [ ] Assess the best content approach
- [ ] Share with identity group
- [ ] Coordinate with PW to create content (if needed)

## Acceptance Criteria
- [ ] Content is live on VA.gov to alert DS Logon users that they need to switch to Login.gov

**Comment by CarlDickerson** [comment]
@laurwill @aliyahblackmore attached are links to the Figma files
- [Asking a Veteran to set up a Login.gov IAL1 account after they sign in to a VA service (modal)](https://www.figma.com/file/8vobVoSl1UqLnXsni3rcvO/Login.gov-Migration%3A-Grandfathering-IAL1-Flow?node-id=1%3A13&t=BeCxsGkNWYMfn4Rn-1)
- [Success message after Login.gov account binding complete](https://www.figma.com/file/8vobVoSl1UqLnXsni3rcvO/Login.gov-Migration%3A-Grandfathering-IAL1-Flow?node-id=2%3A2608&t=pEvlZIVkdYva0hXD-1): 
- [Asking a Veteran to upgrade to a Login.gov IAL2 account1](https://www.figma.com/file/8vobVoSl1UqLnXsni3rcvO/Login.gov-Migration%3A-Grandfathering-IAL1-Flow?node-id=2%3A2664&t=BeCxsGkNWYMfn4Rn-1)
- [Generic error state](https://www.figma.com/file/8vobVoSl1UqLnXsni3rcvO/Login.gov-Migration%3A-Grandfathering-IAL1-Flow?node-id=2%3A2647&t=BeCxsGkNWYMfn4Rn-1)

**Comment by laurwill** [comment]
Update: We started reviewing these, had a meeting today to connect this work with IA and accessibility, and will provide more detailed content feedback once we've confirmed the user flows here.

**Comment by laurwill** [comment]
Hi @CarlDickerson ! Thanks so much for making time to sync on this content yesterday. 

I'm attaching a Word doc here that shows the suggested content for the 3 screens (create Login.gov account, success, and general error) that we talked about together on that call. I made a few more tweaks after today's sync with design and dev, and left you some comments.

[DS Logon bound accounts interrupted flow screens](https://app.zenhub.com/files/133843125/67fb08a4-63ff-43db-8bf2-0494953fa988/download)

I still have questions about whether the 4th screen (verify identity again) needs to be a modal that interrupts a user's task. Let's confirm how that step will happen before digging into the content for that screen.

I'm also attaching the related content we talked about for the new Terms of use flow, for reference. 

[Terms of use screens](https://app.zenhub.com/files/133843125/3dec4155-4941-4830-8d07-2601a5cf7dac/download)

We can share updated content with the broader team as well, just wanted to pass along for your review first. Let me know if you have questions or want to chat about anything!

Oh, and do you have links to the email version of this flow? We'd also want to make sure that content aligns with updates we make to the interrupted-flow version. Thank you!

**Comment by laurwill** [comment]
Hi @CarlDickerson ,
Thanks for talking through the above concerns last week — I'm attaching a Word doc here with some suggestions for both the interrupted binding flow modal and the email for the binding flow. Some notes and questions here:
- We think "VA-only" is the clearest framing, so suggest testing with this term and with other content that clarifies the limitations of the account (see notes in doc)
- Since we aren't able to say anything definite about the temporary nature of this account, or if or when VA might require these users to re-verify, what if we focus on the "VA-only" limitations rather than the temporary piece?
- And similar to my comment in the organic flow ticket, wondering if you've considered any messaging about Login.gov being the last or final account change we'll ask people to make, or if we aren't able to say that with confidence. 

Let me know if you have questions or want to chat before our Thursday sync! And of course let us know if any of these suggestions don't make sense from a product perspective.

[DS Logon binding flows_Updated 3.14.23](https://app.zenhub.com/files/133843125/a9e16a8a-2a64-4948-b5a1-12bd1119b23d/download)

**Comment by laurwill** [comment]
Hi again @CarlDickerson ! Based on your answer to my question about the email flow here, the ["redirecting" page](https://www.figma.com/file/8vobVoSl1UqLnXsni3rcvO/Login.gov-Migration%3A-Grandfathering-IAL1-Flow?node-id=234%3A1470&t=duLCqhJ316bmE82n-0) is needed in the email flow. (Apologies for confusion there!)

To avoid the passive "be redirected," what if we skipped the word "redirect" altogether? I think redirect is usually an automatic process, where here we're giving the user a choice to go or stay, so that word could probably come out. See what you think:

**Continue to Login.gov to create an account**

Once you’ve created your **Login.gov** account, we’ll bring you back to VA.gov.

Continue to Login.gov

Stay on VA.gov

**Comment by laurwill** [comment]
Oh, and one screen we haven't reviewed together yet is the[ upgrade modal](https://www.figma.com/file/8vobVoSl1UqLnXsni3rcvO/Login.gov-Migration%3A-Grandfathering-IAL1-Flow?node-id=2%3A2664&t=FQ2EqO4Zk9H2aCM0-0) — if this screen is going to testing as part of the flow, we'd suggest similar updates there.

Here's a Word doc with some suggestions in comments — happy to chat about this one as well!

[Upgrade modal in binding flow](https://app.zenhub.com/files/133843125/616d0788-6912-4782-bdb8-ecf4e4b341d3/download)

**Comment by aliyahblackmore** [comment]
Just tracking the additional change to the [DS Logon binding flow ](https://www.figma.com/file/8vobVoSl1UqLnXsni3rcvO/Login.gov-Adoption%3A-Design-Flows?node-id=1-13&t=UA0DReObwakrAU1L-0)here. 

@CarlDickerson as we chatted on the call this morning, these are the suggested changes to provide more context for "VA digital tools." I also shared these via Slack with you:

**DS Logon** will stop working for VA digital tools soon. You can use VA digital tools to apply for and manage
 your VA benefits, health care, and information.

**Comment by RLHecht** [comment]
Closing out this ticket. They are currently in usability testing. If they need more support afterward we can open a new ticket.
