### ISSUE TITLE
[PM, Research] My VA audit improvements: QA discovery

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#52635]
## Background
We need to figure out how we will conduct QA now that we do not have a dedicated resource expert to rely on. 

## Tasks
- [x] Determine what is absolutely required for staging review (from QA perspective) by platform
- [x] Determine if we need to use testrail
- [x] If we need to use testrail - get access and support to use it
- [x] Establish process for manual team-run QA

## Resources
- Staging review [QA artifacts overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review#Stagingreview-QAartifacts)
- [QA standards documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards)
- [Test Rail guide](https://depo-platform-documentation.scrollhelp.site/developer-docs/testrail-guide)
- [Example of non-Test-Rail QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/my-education-benefits/enrollment-verification/test-scripts)

**Comment by ajakabcin** [comment]
determined that we will not use test rail for this feature - will use a spreadsheet to track test results and browserstack as a tool for operating system and browser testing
