### ISSUE TITLE
Design | Profile | Accessibility | Review Sketch files and make necessary updates

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#52637]
## Background

We need to review Sketch docs across profile, and make sure they reflect the most recent accessibility changes.

## Tasks
- [x] Sketch files and documentation links to where we show TTY numbers (see FE | Profile | Updates to TTY  #49843)
- [x] Sketch files and documentation links to any screens that show open form fields. 
     - Button pairs changed from Update/Cancel to Save/Cancel recently (see https://github.com/department-of-veterans-affairs/va.gov-team/issues/49374). All screens may have been updated in the Sketch files, but it is worth confirming.
  

## Acceptance Criteria
- [x] Sketch files reflect all the latest changes

## Validation
- Anyone on team can validate the docs

**Comment by Samara-Strauss** [comment]
The question here is whether there is work to do or not on this ticket. First step is to review the Sketch files to see if changes have already been made or not. If not, then we'd proceed with updating the files accordingly.

**Comment by Samara-Strauss** [comment]
@fmccaf1 what's the update on this? Were all files already updated? Did you need to make updates? Did you need to update any links in our profile documentation?

**Comment by fmccaf1** [comment]
@Samara-Strauss There were no issues with the TTY phone numbers that I could find, so no changes there. I did need to make a few changes for the button pairs from update/cancel to save/cancel. Those were in the Personal Information - Mobile  screens and Contact Info - both Mobile and Desktop (but behind a modal/within a greyed out area, so not super important, but still made those changes).

**Comment by Samara-Strauss** [comment]
@fmccaf1 I'm realizing this was not totally clear from the listed tasks, but did you need to update any links [in our use case documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/use-cases#readme) as a result of the sketch file updates? If you didn't end up reviewing those, I can create another ticket to do so.

**Comment by fmccaf1** [comment]
@Samara-Strauss I'm sorry, I did not review those!

**Comment by Samara-Strauss** [comment]
Created #53408 to review the documentation, which means we are all set on this ticket.

**Comment by andaleliz** [comment]
I actually wasn't clear on this either - at the time, I thought it was just the Sketch files, and not the documentation since I always make updates on the same artboards so links don't break. I didn't realize Christina didn't follow that same protocol at the writing of this ticket, which means it IS possible links got broken. We're all learning together!

**Comment by Samara-Strauss** [comment]
Totally fine! Thank you for taking the lead on initial ticket creation!!
