### ISSUE TITLE
Announce shadowing of Design Intent to VFS teams

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#52646]
## User Story
As a VFS team member, I want to know who is going to be involved/participating in the Design Intent so that there is full transparency and I can be prepared to answer questions.

Assignee: @sterkenburgsara 
Peer Reviewer: @CherylEvans 

## Description
Per ticket #52464, Joe and Gary will be attending the Design Intent meeting(s) if/when scheduled for a set period of time. VFS teams need to be made aware that security engineers will be present at their Design Intent so that there is full transparency between teams and in case they are asked to answer questions about their product. The purpose of this ticket is to announce to VFS teams that this shadowing will take place.

## Impacted Artifacts
N/A

## Tasks
- [x] Draft message communicating that Joe and Gary, the Platform Security Engineers, will be shadowing Collaboration Cycle Design Intents in order to determine if the information shared at Design Intents helps them better prepare for the PSIRR. Also share that the goal is to improve the PSIRR experience for VFS teams so that the review runs smoother, is more valuable for Platform and helps them better prepare for what's ahead.
- [x] Share [draft message](https://docs.google.com/document/d/1J-B8NQw31kLV14ImTlhAdBTXuqGNJyoFWQ6CNWA0scU/edit) with @joeniquette and @gary-fallon for their review and approval
- [x] Make any requested changes.
- [x] Post message (or ask Shira to) on #vfs-change-announcements channel per [Platform Communication Playbook](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2165473911/Platform+Communications+Playbook)guidelines - change communication

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS teams are made aware in ToT that Platform Security Engineers will be attending their Design Intents
- [x] VFS teams are made aware via Slack (#vfs-change-announcements) that Platform Security Engineers will be attending their Design Intents

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@sterkenburgsara assigning this to you now bc it would be ideal if we could announce this prior to the DI on Friday. If you can't make Friday, nbd. Please let me know if you have any questions. CC @CherylEvans

**Comment by sterkenburgsara** [comment]
@CherylEvans Can you review [draft text on this google doc](https://docs.google.com/document/d/1J-B8NQw31kLV14ImTlhAdBTXuqGNJyoFWQ6CNWA0scU/edit?usp=sharing)?

**Comment by CherylEvans** [comment]
@sterkenburgsara I made a few more changes that I overlooked the first time. I am good with your sending it to Joe & Gary for further review. :-)

**Comment by sterkenburgsara** [comment]
@joeniquette @gary-fallon We've drafted an announcement re: shadowing design intent meetings to help with PSIRR. Can you peek at [this document](https://docs.google.com/document/d/1J-B8NQw31kLV14ImTlhAdBTXuqGNJyoFWQ6CNWA0scU/edit) and suggest any changes? We'll post to #vfs-change-announcements once approved. Thanks!

**Comment by shiragoodman** [comment]
@sterkenburgsara I'd recommend reaching out to Joe and Gary via Slack in the #platform-collaboration-cycle channel

**Comment by sterkenburgsara** [comment]
@shiragoodman done! They have approved and I just posted in #vfs-change-announcements channel. Can you speak to whether teams were notified of this change in ToT (so I can check off that acceptance criteria box & close this out)?

**Comment by shiragoodman** [comment]
@sterkenburgsara yup! I let them know at yesterday's ToT meeting
