### ISSUE TITLE
Evaluate whether PSIRR is needed for static pages

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#52647]
## User Story
As a member of the Sitewide Content and IA team, I want to know if Platform requires static pages to complete a PSIRR so that I understand what is expected of me.

As a Governance team member, I want to know if I need to make updates and/or modifications to the static paths of the Custom Tracks flow so that I can be sure to recommend the correct touchpoints for VFS teams.

Assignee: @sterkenburgsara 
Peer Reviewer: @it-harrison 

## Description
Governance team recently updated the Custom Tracks flow and noticed that the path for iteration to static pages states a PSIRR is required, while the path for new static pages states the PSIRR is not required. We'd like to confirm with the Platform Security Engineers what the Platform expectations are so that we can update the Custom Tracks and make accurate recommendations to VFS teams.
 
## Impacted Artifacts
Custom Tracks flow

## Tasks
- [x] Define the problem statement 
- [x] Reach out to Joe and Gary, share the problem statement and ask for their thoughts/opinions
- [x] If they do think static pages need a PSIRR review, is there a modified template they can and should complete? The current template may be overkill for a static page. (No, static pages do not need a review unless personalized data loads on any of the pages. Currently this does not happen in any scenarios - 02/07/23)
- [x] If it is determined that additional actions may be needed to support PSIRR's for static pages, create a ticket for the backlog and link to this issue ticket. (N/A based on previous bullet point - 02/07/23)

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We know whether static pages, whether new or iteration, need a PSIRR in the Collaboration Cycle.

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by sterkenburgsara** [comment]
@it-harrison I drafted the question/problem statement for Gary + Joe [here](https://docs.google.com/document/d/1NI2AXVTOR-pNfmA3Y0TdYwk-tJlUJwWaYcG4uSGJObE/edit?usp=sharing). Ready for your review (feel free to edit directly).

**Comment by it-harrison** [comment]
@sterkenburgsara the question/problem looks good - I just added a link (please double check it links to what you are referencing).

**Comment by sterkenburgsara** [comment]
@it-harrison Great! - the link does go to the current PSIRR review as expected. I'll go ahead and reach out to Gary/Joe with the message. Thank you.

**Comment by sterkenburgsara** [comment]
Per @joeniquette on 2/7/23, static pages (or any updates to static pages) do not need to undergo a PSIRR review since there are no scenarios where those pages will load personalized data based on log-in. If that changes, we will have to review this policy. [See Slack thread here](https://dsva.slack.com/archives/G01DXP10GCA/p1675782559529119).
