### ISSUE TITLE
Create access request for vets-api terminal access in ArgoCD

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#52644]
## Description
In order to access the terminal on a vets-api pod in ArgoCD, we are requiring that they are on the Platform _or_ VFS roster and an E-QIP has been submitted for the requesting individual (?is this accurate? This is what's required for AWS.) Make an access request template specifically for this access request.

If a user already has AWS access, their request for Argo terminal access should be approved automatically since they've already been through this process. We need to have them link their AWS access ticket, or provide their AWS user name, or something. 

Similar examples:
[AWS Access Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/aws-access-request.yml)
[SOCKS Access Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/socks-access-request.yml)

There is documentation for the person approving the request [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1800601685/Approve+AWS+access) which probably needs updated. 

There is documentation for the AWS Access process [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request).

Issue template pro-tip: Markdown does not get submitted with the form. Meaning, anything in the `- type: markdown` section will only be seen as the user is filling out the form, but not _after_ it's submitted. For example, the Instructions at the top of the SOCKS and AWS requests won't be seen in an open access request (example: https://github.com/department-of-veterans-affairs/va.gov-team/issues/52632).

## Tasks
- [x] Create new issue template within va.gov-team repo.
- [x] Update Platform website EKS Access section. ([Confluence link](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2452193284/Vets+API+on+EKS#Access))
- [x] Update or add more documentation for the Tech Support team and the approvers so they know how to process these issues. 
- [ ] Determine who will process these requests and transfer the knowledge to that individual. 

## Acceptance Criteria
- [ ] New template is reviewed and merged
- [ ] Platform website is updated
- [ ] Other Confluence docs are updated
- [ ] Knowledge transfer and expectations are passed on to whoever is responsible for processing these requests.

**Comment by rmtolmach** [comment]
PR up for review
- https://github.com/department-of-veterans-affairs/va.gov-team/pull/54352

**Comment by rmtolmach** [comment]
✅ Section, "Handle vets-api ArgoCD terminal access" added to the Backend Support Responsibilities doc: https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access

✅ I updated the Platform Website: https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-Access (should be updated by EOD 3/2)

✅ Shared information in #platform-tech-team-support (and x-posted in #platform-cop-backend): https://dsva.slack.com/archives/C02RLAUM2LV/p1677770737256629
