### ISSUE TITLE
Update and publish new PACT Act alerts on the Gulf War Illnesses pages 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#52645]
## Issue Description

While we work on combining the 2 Gulf War Illnesses pages as part of our PACT Act efforts, we need to create and publish an alert on each page to explain that we are updating the pages.

Danielle has created the alert and we need to copyedit and publish them:

http://preview-prod.vfs.va.gov/preview?nodeId=884
http://preview-prod.vfs.va.gov/preview?nodeId=885

## Tasks
- [x] Copyedit alert (Megan)
- [x] Publish pages with alerts (Megan)

## Acceptance Criteria
- [ ] Alerts are live on the site

**Comment by RLHecht** [comment]
This work was already completed when I created the ticket. Closing!
