### ISSUE TITLE
[Design] Profile 2.0: Create mockups of the Contact Information screen

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5264]
## User story

As a veteran, I need to be able to easily find and update my contact information so the VA can reach me at the right places.

## Additional background

Epic #5092

## Tasks

- [x] Create desktop mockups of the Contact information screen.
- [x] Create mobile mockups of the Contact information screen.

## Acceptance Criteria

- [ ] All mockups have been produced

**Comment by tressaellen** [comment]
![Contact Mobile](https://user-images.githubusercontent.com/58752772/73483114-27159700-435c-11ea-9ffa-dcf7406115be.jpg)
![Contact](https://user-images.githubusercontent.com/58752772/73483115-27159700-435c-11ea-9236-cdd928c2ab09.jpg)

**Comment by Samara-Strauss** [comment]
@tressaellen looking good! Here's my feedback:

- There are some inconsistencies between the mobile and desktop views:
  - In the mobile view, the Contact information heading and "Which of my benefits..." FAQ are on a gray background, but not on desktop. I would expect to see them on a white background like they are in the desktop view.
  - In the mobile view, I would expect to see the same line outlines around each field, eg. Mailing address, Home address, Home (phone), etc, that I see in the desktop view.
- Since the background in the main content area is no longer gray, I would no longer expect to see the thick, gray divider lines between Address/Phone numbers/Email address in the mobile view.
- All headings only capitalize the first word unless there are additional proper nouns in the heading. So, please change Phone Numbers to Phone numbers and Email Address to Email address in your desktop mockup.

**Comment by tressaellen** [comment]
Here's the updated screens

![Contact Mobile](https://user-images.githubusercontent.com/58752772/73490801-7fec2c00-436a-11ea-9083-f9017d61f5e0.jpg)
![Contact](https://user-images.githubusercontent.com/58752772/73490802-7fec2c00-436a-11ea-8d4f-9901032ae7c8.jpg)

**Comment by Samara-Strauss** [comment]
Looks good! One more thing — Can we put the Edit links in the mobile view back under the field content?

**Comment by tressaellen** [comment]
![Contact Mobile](https://user-images.githubusercontent.com/58752772/73671356-0608bb00-4668-11ea-87d8-7687b3028fc5.jpg)
![Contact](https://user-images.githubusercontent.com/58752772/73671358-0608bb00-4668-11ea-8c16-e9508a50d132.jpg)

**Comment by Samara-Strauss** [comment]
Awesome. This looks great.

**Comment by tressaellen** [comment]
These are just fixing the alignment

![Contact Mobile](https://user-images.githubusercontent.com/58752772/73688542-825fc600-4689-11ea-9cc6-05022882f246.jpg)
![Contact](https://user-images.githubusercontent.com/58752772/73688544-82f85c80-4689-11ea-8328-01b82f6f861e.jpg)

**Comment by Samara-Strauss** [comment]
Also: don't forget to show how "Edit" interaction will work for each address/phone number/email address.

**Comment by Samara-Strauss** [comment]
ALSO, don't forget to show what it looks like if someone doesn't have an address/phone number/email. You can see that on staging.

**Comment by Samara-Strauss** [comment]
OK, summary of things we're looking for by EOD Friday:

- Revised header
- Revised nav — Looks like we're gonna go with the side nav
- Empty state for at least one of the pieces of contact info 
- What an error looks like on this page
- What it looks like when info is saved (do we still need the "we're in the process of saving this..." interaction? or can saving be complete before the modal closes?) or fails to save
- What it looks like if we can't retrieve someone's profile info

Let's get this done for this one page, and then we can come back to the other pages when you get back.

**Comment by tressaellen** [comment]
Sounds good!

**Comment by tressaellen** [comment]
This should be everything on the list! Let me know if there needs to be any changes. 

![Contact Edit Mailing 2](https://user-images.githubusercontent.com/58752772/73994913-5e63e500-4914-11ea-9534-657dd7a19cb9.jpg)
![Contact Edit Mailing 3](https://user-images.githubusercontent.com/58752772/73994915-5e63e500-4914-11ea-8aa1-aba0fecee4fa.jpg)
![Contact Edit Mailing 4](https://user-images.githubusercontent.com/58752772/73994916-5efc7b80-4914-11ea-9c6e-ca79f10336ff.jpg)
![Contact No Seal](https://user-images.githubusercontent.com/58752772/73994919-5f951200-4914-11ea-8240-1871e0376c6b.jpg)
![Mobile 3](https://user-images.githubusercontent.com/58752772/73994921-602da880-4914-11ea-86ee-6340bb610702.jpg)
![Contact Mobile](https://user-images.githubusercontent.com/58752772/73994918-5f951200-4914-11ea-9bbf-bccd0ef38bad.jpg)
![Contact Edit Mobile](https://user-images.githubusercontent.com/58752772/73994917-5efc7b80-4914-11ea-90cf-190efed66691.jpg)
![Contact Cant retrieve](https://user-images.githubusercontent.com/58752772/73995300-653f2780-4915-11ea-8d3a-f12f52022dcb.jpg)

![Contact 1](https://user-images.githubusercontent.com/58752772/73994904-59069a80-4914-11ea-8e8b-a9bf2863f973.jpg)
![Contact Edit Email](https://user-images.githubusercontent.com/58752772/73994907-5c9a2180-4914-11ea-88ec-9ae68427a3f5.jpg)
![Contact Edit Home](https://user-images.githubusercontent.com/58752772/73994909-5d32b800-4914-11ea-8289-73880ed89ec7.jpg)
![Contact Edit Mailing 1](https://user-images.githubusercontent.com/58752772/73994911-5dcb4e80-4914-11ea-8d8a-a4b61f327dbc.jpg)

**Comment by Samara-Strauss** [comment]
These look great!! Amazing work, @tressaellen! A few notes:

1. I really like showing the save pending/failure in the modal. This feels more intuitive to me — once the form closes, I would assume I'd see my new info and everything would already be saved.
2. The "saved" confirmation is a new style, so we'll need to run that by platform folks for approval.
3. For the mobile nav, can you duplicate the pattern as-is with how it functions live on the site today? Let's at least test it and then we can determine if we need to make any modifications from there. Since the menu is sticky, I think it might actually be OK the way it is.
4. The checkbox for mobile text messages — I *think* we need to leave that editable in the read-only view of the profile (or at least there's an argument that we should). Can you show that and also show it represented in the edit form?
5. It may be possible that we can retrieve personal information but not contact information. We might need to show what it looks like if there's an error for one by not the other. The personal info for a vet comes from MVI and the contact info comes from VA Profile, which is why that can happen. [Here's an old mockup of how we do that in the current profile](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Identity/Personalization/Profile/Design/Profile-04-errors-section.png).
6. There is also an error for if we can find someone at all in MVI (which means they wouldn't be able to have a profile) and [this is what that looks like](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Identity/Personalization/Profile/Design/Profile-10-not-in-MVI.png) (note the existing copy has been modified to say VA.gov and not Vets.gov). I don't think you need to represent this because we don't need to change it, but just wanted you to know it existed.

Great work! Really excited about this. :)

**Comment by tressaellen** [comment]
Here are all the updates for these pages. I ended up renaming the section 'Profile and contact information' - it makes more sense in general.  Especially if one part of the section can't be retrieved.  I'm working on all the mobile states now.

![Contact 1 Checkbox](https://user-images.githubusercontent.com/58752772/74061191-c6640b00-49a8-11ea-9d4f-1843a5d56df9.jpg)
![Contact 1 No Contact](https://user-images.githubusercontent.com/58752772/74061196-c95efb80-49a8-11ea-8b4f-90b998b6ed5d.jpg)
![Contact 1 No Personal](https://user-images.githubusercontent.com/58752772/74061198-c9f79200-49a8-11ea-94c5-7a22402b7d38.jpg)
![Contact 1](https://user-images.githubusercontent.com/58752772/74061199-ca902880-49a8-11ea-9d1e-39f58f2de7ce.jpg)
![Contact Edit Checkbox](https://user-images.githubusercontent.com/58752772/74061200-cb28bf00-49a8-11ea-8482-625f3259c1fb.jpg)
![Contact Edit Email](https://user-images.githubusercontent.com/58752772/74061201-cbc15580-49a8-11ea-94bb-12d4ada2b95a.jpg)
![Contact Edit Home](https://user-images.githubusercontent.com/58752772/74061202-cbc15580-49a8-11ea-945f-d55c800a1fa8.jpg)
![Contact Edit Mailing 1](https://user-images.githubusercontent.com/58752772/74061205-cc59ec00-49a8-11ea-8e99-12518575bbba.jpg)
![Contact Edit Mailing 2 Copy](https://user-images.githubusercontent.com/58752772/74061207-cc59ec00-49a8-11ea-9f49-1c1401e0e265.jpg)
![Contact Edit Mailing 2](https://user-images.githubusercontent.com/58752772/74061208-ccf28280-49a8-11ea-8adf-1d5f3c203b56.jpg)
![Contact Edit Mailing 4](https://user-images.githubusercontent.com/58752772/74061209-cd8b1900-49a8-11ea-941d-c22500da47c2.jpg)
![Contact Edit](https://user-images.githubusercontent.com/58752772/74061210-ce23af80-49a8-11ea-9dd5-6f8293b3214e.jpg)
![Contact Mobile Nav](https://user-images.githubusercontent.com/58752772/74061212-cebc4600-49a8-11ea-921f-4df2d1e6936b.jpg)
![Contact Mobile](https://user-images.githubusercontent.com/58752772/74061213-cf54dc80-49a8-11ea-8c75-07cb5e5531a5.jpg)
![Contact No Seal](https://user-images.githubusercontent.com/58752772/74061215-cf54dc80-49a8-11ea-8229-a81f2f18cc41.jpg)

**Comment by Samara-Strauss** [comment]
This looks awesome! I don't have any additional feedback right now. Great work!

**Comment by tressaellen** [comment]
Here's all the mobile states as well as the updated nav on the desktop. 

![Contact 1 Checkbox](https://user-images.githubusercontent.com/58752772/74066271-12687d00-49b4-11ea-944c-2ecc03a406d0.jpg)
![Contact 1 No Contact](https://user-images.githubusercontent.com/58752772/74066280-16949a80-49b4-11ea-9be4-dbb10f282108.jpg)
![Contact 1 No Personal](https://user-images.githubusercontent.com/58752772/74066282-172d3100-49b4-11ea-9a6c-e21f2e785bba.jpg)
![Contact 1](https://user-images.githubusercontent.com/58752772/74066284-185e5e00-49b4-11ea-9fb8-c37ba267db09.jpg)
![Contact Edit Checkbox](https://user-images.githubusercontent.com/58752772/74066286-18f6f480-49b4-11ea-83fb-8c21084e1ab5.jpg)
![Contact Edit Email](https://user-images.githubusercontent.com/58752772/74066289-18f6f480-49b4-11ea-83d6-0a48b54ad2b6.jpg)
![Contact Edit Home](https://user-images.githubusercontent.com/58752772/74066290-198f8b00-49b4-11ea-88b8-78e3d10e6977.jpg)
![Contact Edit Mailing 1](https://user-images.githubusercontent.com/58752772/74066291-198f8b00-49b4-11ea-832f-3a9a1a7960f6.jpg)
![Contact Edit Mailing 2 Copy](https://user-images.githubusercontent.com/58752772/74066292-1a282180-49b4-11ea-975f-809f4d620588.jpg)
![Contact Edit Mailing 2](https://user-images.githubusercontent.com/58752772/74066293-1a282180-49b4-11ea-8678-cd1a93c2b454.jpg)
![Contact Edit Mailing 4](https://user-images.githubusercontent.com/58752772/74066295-1ac0b800-49b4-11ea-8e4e-21bca9bd3425.jpg)
![Contact Edit](https://user-images.githubusercontent.com/58752772/74066296-1ac0b800-49b4-11ea-8e35-e3597f1f9be3.jpg)
![Contact Mobile Checked](https://user-images.githubusercontent.com/58752772/74066299-1b594e80-49b4-11ea-9de5-807af6ef2471.jpg)
![Contact Mobile Copy 6](https://user-images.githubusercontent.com/58752772/74066302-1bf1e500-49b4-11ea-8d29-707dbd7b0fee.jpg)
![Contact Mobile Edit Address 2](https://user-images.githubusercontent.com/58752772/74066304-1bf1e500-49b4-11ea-99ab-fa1ce2dcc7d0.jpg)
![Contact Mobile Edit Address 3](https://user-images.githubusercontent.com/58752772/74066311-1d231200-49b4-11ea-8742-d1eeeca2cca5.jpg)
![Contact Mobile Edit Address](https://user-images.githubusercontent.com/58752772/74066313-1d231200-49b4-11ea-82c7-d8d9017e82b1.jpg)
![Contact Mobile Edit Email](https://user-images.githubusercontent.com/58752772/74066315-1d231200-49b4-11ea-8e2f-457dbbbca17a.jpg)
![Contact Mobile Edit Home Phone](https://user-images.githubusercontent.com/58752772/74066320-1dbba880-49b4-11ea-8e93-f5dbc321b247.jpg)
![Contact Mobile Edit Phone 2](https://user-images.githubusercontent.com/58752772/74066327-1e543f00-49b4-11ea-96c0-92402cc4891e.jpg)
![Contact Mobile Nav](https://user-images.githubusercontent.com/58752772/74066329-1eecd580-49b4-11ea-8b63-70602aa5b11c.jpg)
![Contact Mobile No Check](https://user-images.githubusercontent.com/58752772/74066331-1f856c00-49b4-11ea-9662-83e60161bff2.jpg)
![Contact Mobile No Contact](https://user-images.githubusercontent.com/58752772/74066334-1f856c00-49b4-11ea-82f3-bfd8062799e5.jpg)
![Contact Mobile No Personal](https://user-images.githubusercontent.com/58752772/74066337-201e0280-49b4-11ea-94fb-93d305283689.jpg)
![Contact Mobile No Seal](https://user-images.githubusercontent.com/58752772/74066339-201e0280-49b4-11ea-8495-8953e24333a3.jpg)
![Contact Mobile Saved Address](https://user-images.githubusercontent.com/58752772/74066341-20b69900-49b4-11ea-9e37-1bc55f1081ab.jpg)
![Contact Mobile](https://user-images.githubusercontent.com/58752772/74066342-20b69900-49b4-11ea-9861-409a898950b9.jpg)
![Contact No Seal](https://user-images.githubusercontent.com/58752772/74066343-214f2f80-49b4-11ea-86e1-a040fd302148.jpg)

**Comment by Samara-Strauss** [comment]
Thanks for this!

In the future, you don't need to post ALL of the same states in the mobile view. Maybe just one of the page/app in a mobile view, and then any meaningful screens that are notably different from the desktop (eg. the mobile nav). That'll make things easier for you and easier in the review process.

Great work! Have a great vacation!

**Comment by tressaellen** [comment]
Haha, noted. That will definitely cut down on scrolling. Thanks!

**Comment by tressaellen** [comment]
<img width="421" alt="Saved Notification" src="https://user-images.githubusercontent.com/58752772/75172414-75fbe580-56ea-11ea-9b9f-1eee648cff61.png">

**Comment by Samara-Strauss** [comment]
Nice! that looks great. Thanks for this.
