### ISSUE TITLE
Update GitHub Actions/Workflows to deal with save-state and set-output deprecation

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#52653]
## Issue Description
[GitHub is announced in 10/2022](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) that the `save-state` and `set-output` commands are going to be deprecated soon.

The following warning appears several times in the vets-api `Tests` workflow in the `Build Docker Image` job:
```
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
``` 

Example link - https://github.com/department-of-veterans-affairs/vets-api/actions/runs/4019180151/jobs/6905698878

Note: I searched vets-api for `save-state` and nothing came up so I'm not exactly sure why we're seeing this warning.

---
## Tasks
- [ ] Replace all instances of `save-state` and `set-output` with the new commands

## Acceptance Criteria
- [ ] All instances of `save-state` and `set-output` have been handled and the warning noted in the description above no longer appears in any of the logs in any vets-api GitHub Actions.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LindseySaari** [comment]
It appears that the parent actions that we use utilize save-state under the hood. Hoping that bumping the versions will clear up the warnings.

**Comment by LindseySaari** [comment]
PR here: https://github.com/department-of-veterans-affairs/vets-api/pull/11693

**Comment by laineymajor** [comment]
@LindseySaari what's remaining here?

**Comment by laineymajor** [comment]
In review
