### ISSUE TITLE
Sara to request Domo access

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#52651]
## User Story
_"As a governance team member, I want to have access to the Domo Dashboard tool, so that I can engage with additional tickets in this epic and support my team with initiative work to expand our analytics using Domo.

Assignee: @sterkenburgsara 

## Description
Follow guidance here: https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/getting-started-with-platform-analytics-insights

## Impacted Artifacts
- Domo dashboard (Sara will have access)

## Tasks
- [x] Follow [guidance on requesting Domo access](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/getting-started-with-platform-analytics-insights)
- [x] Submit GH ticket requesting access
- [x] Follow up with Slack message to #vfs-platform-support (Analytics/Insights request) with details as requested in GH ticket
- [x] Receive Domo access and setup

## Acceptance Criteria
- [x] Has received Domo access and set up credentials
- [x] Can view/use Domo for governance team initiative work

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer
