### ISSUE TITLE
Add additional procedural notes to platform support documentation

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#52650]
## Issue Description
As I member of platform support, I need to know how to better handle support requests so the person requesting support know that I've seen their request and managers know which requests have been handled and closed out.

---
## Tasks
- [x] Add documentation about setting the eyes and checkmark emojis to support requests
- [x] Add documentation about how to handle the corresponding GitHub issue that's created for each support request

## Acceptance Criteria
- [x] Clear documentation about setting emojis has been added
- [x] Clear documentation about how to handle the support request GitHub issues has been added

**Comment by holdenhinkle** [comment]
Documentation was added - https://vfs.atlassian.net/wiki/spaces/PTST/pages/2502426757/Responsibilities

I also rearranged the Platform Tech Support Team docs a little bit.

**Comment by holdenhinkle** [comment]
Btw, the points on this should be a 1, but only 0 and 2 were available in the dropdown.
