### ISSUE TITLE
[Design] Profile 2.0: Create mockups of the Military Information screen

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5265]
## User story

As a veteran, I need to be able to easily see my military information to make sure it's accurate.

## Additional background

Epic #5092

## Tasks

- [x] Create desktop mockups of the military information screen.
- [x] Create mobile mockups of the military information screen.

## Acceptance Criteria

- [x] All mockups have been produced

**Comment by tressaellen** [comment]
![Military Mobile](https://user-images.githubusercontent.com/58752772/73671425-246eb680-4668-11ea-99bc-efb8701c0e5a.jpg)
![Military](https://user-images.githubusercontent.com/58752772/73671426-246eb680-4668-11ea-9dc4-29b151a0152e.jpg)

**Comment by Samara-Strauss** [comment]
Looks great!

Re: Military service lists — this is what Brad found: https://github.com/department-of-veterans-affairs/va.gov-team/issues/2455#issuecomment-573147657

Also, can we see a version of a header without the seal in case we can't find one for someone?

**Comment by tressaellen** [comment]
These are just fixing the alignment

![Military Mobile](https://user-images.githubusercontent.com/58752772/73688454-517f9100-4689-11ea-89a6-cc0d5e2e2d3d.jpg)
![Military](https://user-images.githubusercontent.com/58752772/73688456-517f9100-4689-11ea-9beb-aa72f4499c1b.jpg)

**Comment by tressaellen** [comment]
![Military Information](https://user-images.githubusercontent.com/58752772/74067647-f3b7b580-49b6-11ea-99c9-7e7540f35def.jpg)
![Military Mobile](https://user-images.githubusercontent.com/58752772/74067650-f6b2a600-49b6-11ea-905d-b4c3026894a4.jpg)

**Comment by MickinSahni** [comment]
associating with sprint 15

**Comment by tressaellen** [comment]
![Military Information 2](https://user-images.githubusercontent.com/58752772/75171977-c0309700-56e9-11ea-941b-949ac5582e4b.jpg)
![Military Information 3](https://user-images.githubusercontent.com/58752772/75171984-c292f100-56e9-11ea-9773-df21fedba01e.jpg)
![Military Information](https://user-images.githubusercontent.com/58752772/75171985-c3c41e00-56e9-11ea-99c9-f58cd0e24379.jpg)
![Military Mobile 2](https://user-images.githubusercontent.com/58752772/75171992-c45cb480-56e9-11ea-8743-9000763af4a1.jpg)
![Military Mobile](https://user-images.githubusercontent.com/58752772/75171993-c45cb480-56e9-11ea-93ca-195938f50e7b.jpg)

**Comment by Samara-Strauss** [comment]
Looks good to me!

**Comment by Samara-Strauss** [comment]
Does this still need to be open? Can we close this?
