### ISSUE TITLE
[Design] Profile 2.0: Create mockups of the direct deposit section

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5266]
## User story

As a veteran, I need to be able to easily find and update my direct deposit information so I can receive my disability and pension payments.

## Additional background

Epic #5092

## Tasks

- [ ] Create desktop mockups of the direct deposit information screen.
- [ ] Create mobile mockups of the direct deposit information screen.
- [x] Figure out how saved state works.

## Acceptance Criteria

- [ ] All mockups have been produced

**Comment by tressaellen** [comment]
![Direct Deposit Mobile](https://user-images.githubusercontent.com/58752772/73671466-39e3e080-4668-11ea-8d27-6be6189f69df.jpg)
![Direct Deposit](https://user-images.githubusercontent.com/58752772/73671468-39e3e080-4668-11ea-86e5-7e008307c2c4.jpg)

**Comment by Samara-Strauss** [comment]
Hey! This is looking great!

- Can you reorder the account information so the order is Bank name/Account number/Account type? This is the order in the form to edit these fields so we should keep it consistent.
- Can you stack these items (Bank name/Account number/Account type) in the desktop view? I think this might be easier to program.

**Comment by tressaellen** [comment]
![Direct Deposit Mobile](https://user-images.githubusercontent.com/58752772/73682592-e2506f80-467d-11ea-9089-68a73550534d.jpg)
![Direct Deposit](https://user-images.githubusercontent.com/58752772/73682593-e2506f80-467d-11ea-9995-951f387bba41.jpg)

**Comment by Samara-Strauss** [comment]
Looks great!

**Comment by tressaellen** [comment]
These are just fixing the alignment

![Direct Deposit Mobile](https://user-images.githubusercontent.com/58752772/73688498-6b20d880-4689-11ea-8911-c3c23a54f739.jpg)
![Direct Deposit](https://user-images.githubusercontent.com/58752772/73688499-6b20d880-4689-11ea-9da6-f934a5365eec.jpg)

**Comment by Samara-Strauss** [comment]
Also: don't forget to show how "Edit" interaction will work for the direct deposit field.

**Comment by tressaellen** [comment]
![Direct Deposit Mobile](https://user-images.githubusercontent.com/58752772/74067703-10ec8400-49b7-11ea-9584-0aa16b49425b.jpg)
![Direct Deposit](https://user-images.githubusercontent.com/58752772/74067709-134ede00-49b7-11ea-8858-8b86b3a054a0.jpg)

**Comment by Samara-Strauss** [comment]
Looks awesome 😍

**Comment by MickinSahni** [comment]
associating with sprint 15

**Comment by tressaellen** [comment]
![Direct Deposit 1](https://user-images.githubusercontent.com/58752772/75268903-57aeec00-57b5-11ea-86b1-5cd3d003383e.jpg)
![Direct Deposit 2](https://user-images.githubusercontent.com/58752772/75268910-5a114600-57b5-11ea-86a9-88250cf93f2f.jpg)
![Direct Deposit 3](https://user-images.githubusercontent.com/58752772/75268912-5aa9dc80-57b5-11ea-94de-ec33058e2374.jpg)
![Direct Deposit 4](https://user-images.githubusercontent.com/58752772/75268915-5b427300-57b5-11ea-848a-56653d912268.jpg)
<img width="577" alt="Screen Shot 2020-02-25 at 9 55 10 AM" src="https://user-images.githubusercontent.com/58752772/75268948-65fd0800-57b5-11ea-8379-bd505799c63a.png">
<img width="569" alt="Screen Shot 2020-02-25 at 9 55 16 AM" src="https://user-images.githubusercontent.com/58752772/75268954-67c6cb80-57b5-11ea-8cfc-7e9573ef0eba.png">
![Direct Deposit Mobile 1](https://user-images.githubusercontent.com/58752772/75268917-5b427300-57b5-11ea-893c-404d2a2b9aa9.jpg)
![Direct Deposit Mobile 3](https://user-images.githubusercontent.com/58752772/75268919-5bdb0980-57b5-11ea-9ab9-6c197d12afbc.jpg)
![Direct Deposit Mobile](https://user-images.githubusercontent.com/58752772/75268924-5bdb0980-57b5-11ea-962d-cdef3113f9fe.jpg)

**Comment by Samara-Strauss** [comment]
Looks good to me! Can we close?
