### ISSUE TITLE
Update VFS-facing product directory guide to reflect how to add a product

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#52664]
## Issue Description
While onboarding procedures for an application do point users to the Yeoman Application Generator, which adds products to the directory by default, there's been a few cases where applications are created without that. The absence of an explanation in the user guide has led to numerous support requests. The documentation should be updated to reflect what a user can do if they do not see their product in the product directory.

---
## Tasks
- [x] Update the VFS-facing user guide to reflect the process for adding a product to the product directory.
- [x] Include a screenshot of a manifest.json file as an example for context

## Acceptance Criteria
- [x] The platform website VFS-facing user guide has a comprehensive explanation of steps a user can take to get their product added to the product directory.

**Comment by pjhill** [comment]
I see that the changes have been published to the Platform Website [here](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory-user-guide).

I see an example manifest and I see a new "Help" section. Looks good -- thanks for making these improvements!
