### ISSUE TITLE
Create new page on Platform website

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#52669]
### User Story

**As a VFS team member,**
I want to know how to provide or suggest new content to the Platform website,
so that I know what is expected from me,
so that I can contribute to accurate and/or update-to-date content on this website.

**As a Platform Content team,**
I want to provide simple instructions to VFS team members on how to provide or suggest new content to the Platform website,
so that they are encouraged to help us maintain the Platform website,
so that there are clear instructions on the Platform website we can point to whenever VFS teams ask about the process,
so that we gain a perspective on what VFS teams believe the Platform website needs.

### Tasks

- [x] Create a new page in the Confluence drafts section named "Provide or Suggest New Content for Platform Website"

- [x] Create the instructions for how to do this. Instructions have been pre-written in a section called "Provide or Suggest New Content for Platform Website" on this page: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2476998712/Platform+content+orientation+for+VFS+teams.

- Feel free to style/enhance these instructions as per our Platform website voice and style guide.

- [x] Share the draft with team for any feedback
- [x] Make any updates necessary based on team's feedback
- [x] Schedule the edited page for deployment under the "[support](https://depo-platform-documentation.scrollhelp.site/support/)" section of the Platform website.

Confluence page: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2518548510/DRAFT+How+to+Provide+and+Suggest+New+Content+for+Platform+Website
