### ISSUE TITLE
Investigate Adding Page URL to Support Intake Form 

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#52676]
## User Stories
As a Platform Content team member,
I would like to see what page URL a website footer support request was created from,
So that I have some context about what page (or section of the website) they were in before seeking help.

As a VFS or platform team member,
I would like to create an entry for Platform website content support from the website footer of a page without having to manually enter a page URL,
so that it's a faster way to request support from them.

- **Current Github Footer Template:** https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/platform-website-footer-feedback.md

## Tasks

- [ ] Explore options around Github Query Parameters
- [ ] Review implementation options, along with steps to implementation
- [ ] Create test template to experiment with functionality in the Sandbox Platform Website
- [ ] Document findings and plan for implementation in Production

## Acceptance Criteria

- [ ] Test template has been created to use on the Sandbox version of the Platform Website
- [ ] Steps have been outlined to implement on the Production version of the Platform Website 
- [ ] Those steps have been logged in another ticket (linked here)

**Comment by mchelen-gov** [comment]
Github supports prefilling issue parameters by attaching query parameters: https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue#creating-an-issue-from-a-url-query

So for example on a given page such as: https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools
Clicking "Create an issue ticket" could have a link that populates the Topic and/or  Body fields with some information about the page.
For example:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=vbellissimo&labels=documentation-support%2C+platform-content-team%2C+pw-footer-feedback&template=platform-website-footer-feedback.md&title=Page%20Feedbak:%20"Request%20access%20to%20tools"&body=Page%20URL:%20https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools

**Comment by johnny-jesensky-adhoc** [comment]
As part of the [icebox audit ticket](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/69802) in Sprint 41, moving this from the icebox to the backlog. Needs an additional level of refinement.

**Comment by jknipes** [comment]
cc: @CBonade

**Comment by jknipes** [comment]
Curt Bonade and k15t agree this is not possible to achieve with the current content system. Closing as done.
