### ISSUE TITLE
[Design] Profile 2.0: Create mockups of the Account security screen

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5268]
## User story

As a veteran, I need to be able to easily verify my identity, add 2FA, or find and update my login information with the VA to keep my account information updated, safe, and secure.

## Additional background

Epic #5092

## Tasks

- [x] Create desktop mockups of the Account security screen.
- [x] Create mobile mockups of the Account security screen.

## Acceptance Criteria

- [x] All mockups have been produced

**Comment by tressaellen** [comment]
![Account Security Mobile](https://user-images.githubusercontent.com/58752772/73696528-b511ba80-4699-11ea-8c3f-d7ee7fed5a6e.jpg)
![Account Security](https://user-images.githubusercontent.com/58752772/73696529-b511ba80-4699-11ea-927f-e6f0460f6b1e.jpg)

**Comment by Samara-Strauss** [comment]
Hey! So there are a couple states that I did not have represented in my mockups that we need to represent here:

**Identity verification**

We need to show what it looks like if someone has not yet verified their identity. To see what that looks like:

1. Go on to staging and sign up for an account with ID.me.
2. Don't go through the identity verification process. This will create an LOA1 (not identity verified account).
3. Go to the Account page once you're logged in via the personalized menu in the upper right corner. You'll see the prompt to verify your identity so you can recreate it in your mockups.

**2FA**

Likewise, we need to show what it looks like if you already have 2FA set up. To see what that looks like:

1. Go to staging and sign in with any of the staging users we have.
2. Go to the Account page once you're logged in via the personalized menu in the upper right corner. All of the staging users have 2FA set up, so you'll see the confirmation message to include in the mockups.

**Comment by tressaellen** [comment]
![Account 1](https://user-images.githubusercontent.com/58752772/73995356-93246c00-4915-11ea-9ff4-77748e6c869f.jpg)
![Account 2](https://user-images.githubusercontent.com/58752772/73995363-961f5c80-4915-11ea-91bb-f6143817e3bd.jpg)
![Account Disconnect](https://user-images.githubusercontent.com/58752772/73995364-96b7f300-4915-11ea-81c3-e9101ff2ecea.jpg)
![Account Mobile](https://user-images.githubusercontent.com/58752772/73995365-97508980-4915-11ea-98e3-c3819cce5023.jpg)

**Comment by Samara-Strauss** [comment]
Looking good!! 

1. I forgot to mention on the Personal info mock how much I LOVE the name block header area. I think there's definite potential for that to carry over to the logged in homepage once we get to design that 😃 . 
2. Don't forget to show what it looks like if someone has not verified their identity.
3. Also still need to show what it looks like when they have 2FA set up.
4. Just so you know, the FAQs for connected accounts are not actually live yet. The team that was supposed to do that never got them done/published, so let's remove that gray block from the mocks we hand off to Erik and Brad. BUT do keep a version of it somewhere because we should get those FAQs up as follow on work after the new profile goes live.
5. What about renaming this section to something like "Account settings" or "Your account" or something?

**Comment by tressaellen** [comment]
Verified/unverified identity and 2FA set up/not set up are swapped on Account 1 and 2. Thanks so much for looking over these!

![Account 1](https://user-images.githubusercontent.com/58752772/74063024-d1b93580-49ac-11ea-97d2-97a661fd52cd.jpg)
![Account 2](https://user-images.githubusercontent.com/58752772/74063031-d54cbc80-49ac-11ea-99e5-adcacad2d641.jpg)
![Account Disconnect](https://user-images.githubusercontent.com/58752772/74063033-d67de980-49ac-11ea-9477-e5131ebb80d0.jpg)
![Account Mobile](https://user-images.githubusercontent.com/58752772/74063055-e85f8c80-49ac-11ea-8d09-0a63b3fa9413.jpg)

**Comment by Samara-Strauss** [comment]
Nice! Looks great!

**Comment by MickinSahni** [comment]
associating with sprint 15
