### ISSUE TITLE
[Design] Profile 2.0: Create mockups of the Connected accounts screen

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5269]
## User story

As a veteran, I need to be able to manage the apps I've let access my VA.gov information.

## Additional background

Epic #5092

## Tasks

- [ ] Create desktop mockups of the Connected accounts screen.
- [ ] Create mobile mockups of the Connected accounts screen.

## Acceptance Criteria

- [ ] All mockups have been produced

**Comment by tressaellen** [comment]
![Connected accounts mobile](https://user-images.githubusercontent.com/58752772/73696599-ce1a6b80-4699-11ea-9810-32c36e61ce43.jpg)
![Connected accounts](https://user-images.githubusercontent.com/58752772/73696600-ce1a6b80-4699-11ea-9ce8-79c91aebd07c.jpg)

**Comment by Samara-Strauss** [comment]
Hey! We'll need to show what the "disconnect" interaction looks like. I did *not* have anything to do with the design of this section, so I don't quite have the expertise I do on the rest of the profile. This feature is currently not visible in staging unless someone has a connected account, but you can view the original design here https://www.figma.com/file/dilFghdYw73TtVDxN7um2nfc/VA.gov-Connected-Accounts?node-id=0%3A1

**Comment by MickinSahni** [comment]
associating with sprint 15

**Comment by tressaellen** [comment]
We are combining 'Account' and 'Connected Accounts' into one section - refer to #5268
