### ISSUE TITLE
Education and training hub: Migrate IA Moqups to Mural

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#52724]
## Issue Description

We need to move our education and training IA documentation from Moqups to Mural as part of our migration effort.

## Tasks
- [x] Migrate Moqups
- [x] Cross-reference with VA.gov
- [x] Review journey map
- [x] Review map and comment

## Acceptance Criteria
- [x] Education and training IA documentation migration complete

**Comment by RLHecht** [comment]
Work complete. Closing ticket.
