### ISSUE TITLE
Life insurance hub: Migrate IA Moqups to Mural

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#52728]
## Issue Description

We need to move our life insurance IA documentation from Moqups to Mural as part of our migration effort.

## Tasks
- [x] Migrate Moqups
- [x] Cross-reference with VA.gov
- [x] Review journey map
- [x] Review map and comment

## Acceptance Criteria
- [x] Life insurance IA documentation migration complete

**Comment by RLHecht** [comment]
Work complete. Closing ticket.
