### ISSUE TITLE
Burials and memorials: Migrate IA Moqups to Murals

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#52729]
## Issue Description

We need to move our burials and memorials IA documentation from Moqups to Mural as part of our migration effort.

## Tasks
- [x] Migrate Moqups
- [x] Cross-reference with VA.gov
- [x] Review journey map
- [x] Review map and comment

## Acceptance Criteria
- [x] Burials and memorials IA documentation migration complete

**Comment by RLHecht** [comment]
Work complete. Closing ticket.
