### ISSUE TITLE
Disability hub: Migrate IA Moqups to Mural

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#52723]
## Issue Description

We need to move our disability hub IA documentation from Moqups to Mural as part of our migration effort.

## Tasks
- [x] Migrate Moqups
- [x] Cross-reference with VA.gov
- [x] Review journey map
- [x] Review map and comment

## Acceptance Criteria
- [x] Disability IA documentation migration complete

**Comment by RLHecht** [comment]
Work completed. Closing.
