### ISSUE TITLE
Housing hub: Migrate IA Moqups to Mural

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#52727]
## Issue Description

We need to move our housing IA documentation from Moqups to Mural as part of our migration effort.

## Tasks
- [x] Migrate Moqups
- [x] Cross-reference with VA.gov
- [x] Review journey map
- [x] Review map and comment

## Acceptance Criteria
- [x] Housing IA documentation migration complete

**Comment by kristinoletmuskat** [comment]
Note: there are no journey maps for the housing hub that I could find.

**Comment by RLHecht** [comment]
Work complete. Closing ticket.
