### ISSUE TITLE
Pension hub: Migrate IA Moqups to Mural

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#52726]
## Issue Description

We need to move our pension IA documentation from Moqups to Mural as part of our migration effort.

## Tasks
- [x] Migrate Moqups
- [x] Cross-reference with VA.gov
- [x] Review journey map
- [x] Review map and comment

## Acceptance Criteria
- [x] Pension IA documentation migration complete

**Comment by RLHecht** [comment]
Closing ticket. Work completed.
