### ISSUE TITLE
Careers and employment hub: Migrate IA Moqups to Mural

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#52725]
## Issue Description

We need to move our careers and employment IA documentation from Moqups to Mural as part of our migration effort.

## Tasks
- [ ] Migrate Moqups
- [ ] Cross-reference with VA.gov
- [ ] Review journey map
- [ ] Review map and comment

## Acceptance Criteria
- [ ] Careers and employment IA documentation migration complete
