### ISSUE TITLE
Draft 1st grandfathering user flow in Figma

### ISSUE THREAD

**Issue by tygindraux** [department-of-veterans-affairs/va.gov-team#52734]
### Problem statement
Veterans need to make migrate their DS Logon accounts to Login.gov through grandfathering, which allows them to defer identity proofing.

### Initiative
We have drafted the user flow in Mural where a Veteran signs in to VA.gov and a modal pops-up asking them to migrate their account. This sprint, we need to move this to Figma and build the first clickable end-to-end prototype.

This will involve collaborating with frontend engineering in order to work through technical constraints that aren't already present in the high-level diagrams.

### Acceptance criteria
- [x] User flow has been created in Figma
- [x] Feedback has been received and updates have been made based on comments

### Tasks
- [x] @MOStudioCarolyn draft user flows in Sketch, based on design system and [high-level flow](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1671554156732/bb8f2948581f649bf8fd8ad9816224d93818992d?wid=426-1673385361809)
- [x] @CarlDickerson add in content
- [x] @MOStudioCarolyn share with team for review
- [x] @CarlDickerson ask content team for feedback
- [x] @CarlDickerson make updates to content based on feedback from team, John and Sitewide Content
- [x] @MOStudioCarolyn update prototype with correct use of links and buttons
- [x] @MOStudioCarolyn add [2 missing screens](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1671554156732/bb8f2948581f649bf8fd8ad9816224d93818992d?wid=0-1675889970906) (between login.gov flow and redirect to VA)
- [x] @tygindraux meet with Steve to decide whether we build the prototype for testing or continue with a Figma prototype
- [x] @CarlDickerson review [IA feedback on design intent ticket](https://app.zenhub.com/workspaces/logingov-adoption-team-632280b31e745000136a61fc/issues/gh/department-of-veterans-affairs/va.gov-team/53254) and make updates based on feedback
- [ ] @all review [accessibility feedback](https://app.zenhub.com/workspaces/logingov-adoption-team-632280b31e745000136a61fc/issues/gh/department-of-veterans-affairs/va.gov-team/53333) on design intent ticket and make updates

**Comment by tygindraux** [comment]
Suggest moving midpoint review to Feb 22nd based on Tyler and Carolyn's availability in Sprint 13.

**Comment by tygindraux** [comment]
@CarlDickerson once we have updated content can you coordinate with Sara Sterkenburg (Platform team, Information Architect) to review? She asked on the Design Intent ticket. Not sure if Sara is already part of the regular content meeting you attend.

**Comment by tygindraux** [comment]
We need to add these 2 screens: https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1671554156732/bb8f2948581f649bf8fd8ad9816224d93818992d?wid=0-1675889970906

**Comment by MOStudioCarolyn** [comment]
https://www.figma.com/file/8vobVoSl1UqLnXsni3rcvO/Login.gov-Migration%3A-Grandfathering-IAL1-Flow?node-id=0%3A1&t=WYklv9k5o3CiTdku-0
