### ISSUE TITLE
Records: Migrate IA Moqups to Murals

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#52730]
## Issue Description

We need to move our records IA documentation from Moqups to Mural as part of our migration effort.

## Tasks
- [x] Migrate Moqups
- [x] Cross-reference with VA.gov
- [x] Review journey map
- [x] Review map and comment

## Acceptance Criteria
- [x] Records IA documentation migration complete

**Comment by RLHecht** [comment]
Work completed. Closing ticket.
