### ISSUE TITLE
Create R&S article about verifying enrollment for DEA 

### ISSUE THREAD

**Issue by katherine-fung** [department-of-veterans-affairs/va.gov-team#52738]
## Issue Description
We need to create a R&S article with instructions for how to verify your enrollment to keep getting payments under the DEA program. 

This information isn't going on the static page for enrollment verification for Post-9/11 GI Bill benefits. 

---
## Tasks
- [x] Create new R&S article for enrollment verification for DEA (Katherine)
- [x] Review with Beth 
- [x] Copy edit and publish (Megan) 

## Acceptance Criteria
- [x] R&S article for enrollment verification for DEA is live

**Comment by katherine-fung** [comment]
pasting DEA info here: 

[remove: For DEA
If you get Survivors’ and Dependents’ Educational Assistance (DEA) and you’re enrolled in a non-college degree program, you’ll need to verify your enrollment each month in 1 of these 2 ways:

Option 1: By mail 
You’ll need to fill out and send us a Student Verification of Enrollment (VA Form 22-8979).

Get VA Form 22-8979 to download

Option 2: By phone 
Call us at 888-442-4551 (TTY: 711). Then press 1 to verify your enrollment. We’re here Monday through Friday, 8:00 a.m. to 7:00 p.m. ET.

Note: If you get DEA benefits and you’re enrolled in a college degree program, you don’t need to verify your enrollment.]

**Comment by katherine-fung** [comment]
Hi @bethpottsVADEPO, 

I created this page and I have questions about 2 things: 

1. I thought about whether to specify who needs to verify their enrollment in the intro, or in a separate section on this page. I tried both ways, and putting this info in the intro seemed like a lot. So I broke it off into a section. 

Here are the 2 approaches: 

requirements in the first section: 
http://preview-prod.vfs.va.gov/preview?nodeId=53598 

requirements in the intro (this is a previous revision just for illustration purposes - I've updated the content for accuracy since then):
https://prod.cms.va.gov/node/53598/revisions/748740/view  

2. If someone is verifying their enrollment by mail, they're supposed to mail it to 1 of 2 addresses depending on which state they live in (according to the education call center). This creates an issue we've seen before, of how to present the right address for 50 states. I think we should confirm with Cinda and Jodie that what the education call center is right (and that there's not a single address where people are supposed to send this form). I can email her and Jodie.

**Comment by katherine-fung** [comment]
I confirmed issue #2 with Cinda yesterday. 

Here's the draft of this page: 
http://preview-prod.vfs.va.gov/preview?nodeId=53598

**Comment by katherine-fung** [comment]
Hi @bethpottsVADEPO, maybe we can try to fit this into tomorrow's discussion too.

**Comment by bethpottsVADEPO** [comment]
@katherine-fung I made some edits in the drupal file, and you can bring this to the SMEs now for review! Thanks so much.

**Comment by katherine-fung** [comment]
Beth and I have made a few changes to this page based on the feedback that we got from stakeholders yesterday. 

The page is now ready for copy edit: 

http://preview-prod.vfs.va.gov/preview?nodeId=53598 

I'm confirming that there shouldn't be a CTA on the page. Once this page is published, I can go back to the [main enrollment verification page](https://www.va.gov/education/verify-school-enrollment/) and include a link for this page. Do I also need to update the[ resources and support landing page](https://www.va.gov/resources/) (unless it pre-populates with R&S pages as they're published)?

**Comment by RLHecht** [comment]
I published this article. @katherine-fung I'll set up a separate ticket for you to add the link to the enrollment verification page. No need to do anything with the resources and support landing page. The article is automatically added to the list of education articles. It won't show on the landing page unless we want to sub one of the current articles out.

**Comment by katherine-fung** [comment]
Hi @megzehn, 

I'm sorry to re-open this ticket! Beth asked us to make some small tweaks to this page. 

1. I changed the sub-head "Online" to "Online through Ask VA"
2. I changed the phrase "Send us" to "Upload"

Could you give it a quick look when you have a chance? Thank you! 

cc @rlhecht

**Comment by katherine-fung** [comment]
Hi @megzehn, 

I'm sorry to re-open this ticket! Beth asked us to make some small tweaks to this page. 

1. I changed the sub-head "Online" to "Online through Ask VA"
2. I changed the phrase "Send us" to "Upload"

Could you give it a quick look when you have a chance? Thank you! 

cc @rlhecht

**Comment by megzehn** [comment]
Thanks, @katherine-fung! I reviewed the changes and published the pages!
