### ISSUE TITLE
Make Design Intent request for grandfathering user flow

### ISSUE THREAD

**Issue by tygindraux** [department-of-veterans-affairs/va.gov-team#52737]
### Problem statement
Veterans need to make migrate their DS Logon accounts to Login.gov through grandfathering, which allows them to defer identity proofing.

### Initiative
We have drafted a high-level user flow for grandfathering which needs to be reviewed by the Platform team as part of the Collaboration Cycle.

#### Collaboration Cycle touchpoint
[Design intent](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent): Request this touchpoint when you've an idea of how to solve your problem statement and have drafted a lo-fi prototype and/or wireframe. Design Intent reviews require a 2 day lead time.

Synchronous 30-minute meeting. This is the first opportunity for OCTO-DE and Platform to view your product. You’ll introduce your new work initiative and discuss existing solutions in the problem space. You’ll present your wireframe/prototype and walk through the user flow.

To get feedback on the user experience and your product’s overall design, as well as guidance on how to meet VA.gov standards. Both OCTO-DE and Platform use this meeting to gain an early understanding of the product/feature, including the goals/direction of the product, the intended user flow, and the overall scope of the initiative.

VFS Product Manager (@elizabethkochBT) completes the Before Meeting/VFS Actions in the Design Intent section of their [Collaboration Cycle Request ticket](https://app.zenhub.com/workspaces/logingov-adoption-team-632280b31e745000136a61fc/issues/gh/department-of-veterans-affairs/va.gov-team/50773).

### Acceptance criteria
- [x] [Design intent](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) has been scheduled

### Tasks
- [x] @tygindraux mock up high-level user flow on Mural
- [x] @elizabethkochBT make [Design intent](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) request in our [Collaboration Cycle Request ticket](https://app.zenhub.com/workspaces/logingov-adoption-team-632280b31e745000136a61fc/issues/gh/department-of-veterans-affairs/va.gov-team/50773).

**Comment by tygindraux** [comment]
Can we schedule this for sometime 6 - 10 February?

(Ideally, but if it needs to be the following week then @MOStudioCarolyn can attend in my absence).

**Comment by tygindraux** [comment]
Reminder for myself to do this:

"You can request an Accessibility Specialist during the Collaboration Cycle Design Intent checkpoint. They can help you write and review your research plan and conversation guide before submitting your study for a formal research review."

**Comment by tygindraux** [comment]
@CarlDickerson: "Include Laura Willwerth and Aliyah Blackmore from the Sitewide Content Team on the invite for the design intent - they'd like to sit in just to know."

**Comment by tygindraux** [comment]
I've created a document to prepare for this meeting: https://docs.google.com/document/d/1LD5GoF52IPiWHy8PLz4_d00gHJlO9d8DLAOxl3xcA10/edit#
