### ISSUE TITLE
Facility sites: Migrate IA Moqups to Mural

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#52746]
## Issue Description

We need to move our facility sites IA documentation from Moqups to Mural as part of our migration effort.

## Tasks
- [x] Migrate Moqups
- [x] Cross-reference with VA.gov
- [x] Review journey map
- [ ] Review map and comment

## Acceptance Criteria
- [x] Facility sites IA documentation migration complete

**Comment by RLHecht** [comment]
Work complete. Closing ticket.
