### ISSUE TITLE
Create research plan and conversation guide for 1st round of testing the grandfathering flow

### ISSUE THREAD

**Issue by tygindraux** [department-of-veterans-affairs/va.gov-team#52747]
### Problem statement
Veterans need to make migrate their DS Logon accounts to Login.gov through grandfathering, which allows them to defer identity proofing.

### Initiative
We need a plan for how we test the end-to-end grandfathering flow with Veterans.

### Research timeline 
Before February 21: Submit prototype for Midpoint Review
Before February 27: Submit artifacts for Research Review
Before March 3: Prototype is ready
March 6-10: Pilot session [Need to update with details]
March 13-17: Research sessions
March 20-22: Analysis
March 22-24: Share findings

### Acceptance criteria
- [x] Research plan, screener and conversation guide have been drafted and reviewed by the team

### Tasks
- [x] @tygindraux set up research checklist
- [x] @tygindraux draft research plan
- [x] @tygindraux draft screener questions
- [x] @tygindraux share plan for review by team
- [x] @tygindraux reach out to Shane about recruitment criteria/screener comments
- [x] @tygindraux draft conversation guide
- [x] @tygindraux share conversation guide for review by team
- [x] @tygindraux share plan and guide with John for review
