### ISSUE TITLE
Decision reviews: Migrate IA Moqups to Mural

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#52745]
## Issue Description

We need to move our decision reviews IA documentation from Moqups to Mural as part of our migration effort.

## Tasks
- [x] Migrate Moqups
- [x] Cross-reference with VA.gov
- [x] Review journey map
- [x] Review map and comment

## Acceptance Criteria
- [x] Decision reviews IA documentation migration complete

**Comment by RLHecht** [comment]
Work complete. Closing ticket.
