### ISSUE TITLE
Conduct research sessions for Yellow Ribbon MVP

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#5275]
[_Reference: VSA Delivery Front Door (issue templates and examples)_](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/delivery#vsa-delivery)
## User Story:
As a product team, we need to better understand Veteran's needs and behaviors around utilizing their Yellow Ribbon benefits so we can provide an improved front-end solution

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] 8 sessions - 8 hours
- [ ] Debrief sessions - 3 hours
- [ ] Synthesis - 16 hours 
- [ ] Share findings - 1 hour

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
*  Sessions complete
* Synthesis shared out

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by andaleliz** [comment]
Mural board for observer notes: https://app.mural.co/t/vsa8243/m/vsa8243/1580227554996/832a03121ffa258ffda200ed56827cbde06d88e8
