### ISSUE TITLE
Present orientation video idea at leadership office hours

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#52752]
### Tasks

- [x] Schedule us into the agenda for February 14

- [x] Product manager and team members to attend Platform leadership office hours

- [x] Document meeting takeaways and create new zenhub tasks for them
