### ISSUE TITLE
Collaboration Cycle for Forms-Digitize, Form 26-4555

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#52759]
### VFS team name

Forms Audit Digitize

### Product name

Form 26-4555

### Feature name

26-4555

### GitHub label for product

forms-audit-digitize

### GitHub label for feature

26-4555

## Kickoff questions

<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

1/26/2023

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

No

### Will your work involve changes to...

Tools, applications and dynamic pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline

https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/26-4555/Product%20Outline.md

### Notify the Collaboration Cycle team of this ticket in the vfs-platform-support Slack channel.

- [X] I acknowledge that I must notify \#vfs-platform-support after submitting this issue.

 ## Recommended Collaboration Cycle touchpoints

</details>

### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- Navigate to reference link: [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent)
- [x] Schedule your Design Intent when ready: 02/03/2023 2:00 pm Eastern
   - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders 
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [x] Link all artifacts **ONLY** in the Design Intent artifacts section below at least two days before the scheduled Design Intent.  **Do NOT add artifacts to Comments section**
  
**Design Intent artifacts**

- [x] [Whiteboard sketch or other lo-fi prototypes or wireframes](https://www.sketch.com/s/55cd7fae-eca1-4515-b460-0779f54eff60/p/5C807B24-B423-4109-9BC4-7230F0E21AEB/canvas)
- [ ] User flow
- [ ] Research plan
- [ ] Any other artifacts you have so far
- [x] [Source of truth](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/26-4555/UX/sourceoftruth.md)
  
##### Platform actions
- [x] Follow Moderator Responsibilities guidance for Design Intent
- [ ] Meeting date/time:
  
##### Platform actions

- [ ] If you have feedback, create feedback tickets and link to this epic. Once you have completed you review, check the box next to your practice area
  - [x] Accessibility has completed the review
  - [x] Design has completed the review
  - [x] IA has completed the review
- [x] Update this ticket with the Zoom recording
  - Recording URL: [Link](https://oddball-io.zoom.us/rec/share/VASBkXf0DCqCUqlkY62Gphsi9dGJCxBUcEIxz_LwR6cqOK_i5_OAbT_zb3NR2Ig.xcMchrP4TChJNfXd)
  - Password: *w0TiFA^
  
##### VFS actions

- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Sitewide Content and IA Intake Request
<details>
  <summary>Toggle Sitewide Content and IA Intake Request</summary>

##### VFS actions
- [x] Complete the [sitewide content and IA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-Content-and-IA-intake-request.2124906551.html)
- [x] Link to the Sitewide Content and IA Intake Request ticket below
[Ticket](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/53077)

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [x] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [x] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

- [x] [Finalized design prototype or mockup](https://sketch.com/s/55cd7fae-eca1-4515-b460-0779f54eff60) Pages to look at: SAHG - Authenticated - Not sending to profile &  SAHG - Inauthenticated
 
**Content artifacts** 
  
- [x] Your product’s [content source of truth ](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/26-4555/UX/sourceoftruth.md)
- [x] [Sitewide CAIA Support ticket for 26-4555](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53092) Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable) 

**IA artifacts**

- [x] Please include a link to any [Sitewide CAIA Support ticket for 26-4555](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53092)  [Sitewide Content & IA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including an IA review document or intake form.

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [ ] [Regression test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-regression-test-planRegressionTestPlan)
- [ ] [Test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-test-planTestPlan)
- [ ] [Coverage for References](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [ ] [Summary(Defects) reports](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [ ] [E2E tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-e2e-test-participationE2ETestParticipation) (provide a link to the product’s code)
- [ ] [Code coverage](https://github.com/department-of-veterans-affairs/vets-website/pull/23480) (provide a link to the product’s code)
  
##### Platform actions
- [x] Follow Moderator Responsibilities guidance for Midpoint Review
- [x] Meeting date/time: **Thursday, March 2, 2023 at 2:00PM Eastern**

##### Platform actions

- [ ] If you have midpoint review feedback, create feedback ticket and link to this epic. Once you have completed your review, check the box next to your practice area
  - [x] Design has completed the review
  - [ ] Accessibility has completed the review
  - [x] IA has completed the review
  - [x] Content has completed the review
- [ ] Update this ticket with the Zoom recording
  - Recording URL: [Zoom meeting](https://oddball-io.zoom.us/rec/share/RutVkPmLuF5Xv-AZyzc2ZkN-lBw8Vd-Zc_7L7VbnakYRC3nrni8zNZqWGgRh5skj.LZUqeP6iH0Pabyv4)
  - Password: fqQ+6U5T
  
##### VFS actions
  
- [x] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [ ] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [x] Link to the Analytics Implementation and QA Request ticket below
[Analytics Ticket ](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/53146)

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [x] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [x] Link to the Contact Center review request ticket below
[Contact Center Review Ticket](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/53800)

</details>

### Staging Review 
 
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [ ] I confirm the environment is available and test users have been provided.
- [x] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
 
**Staging Review artifacts**
  
  Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts)
  
**Product artifacts** 
- [x] [Staging URL](https://staging.va.gov/housing-assistance/disability-housing-grants/adapted-housing/introduction)
- [x] All Pages
- [x] [Staging test user information ](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/26-4555/test%20accounts.md)        
  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
  
**IA artifacts**
- [x] Please include a link to any [Sitewide Content & IA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53077#issuecomment-1452307197) feedback you received, including an IA review document or intake form.
[Sitewide Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53077#issuecomment-1452307197)

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [x] [Regression test plan](https://dsvavsp.testrail.io/index.php?/milestones/view/1159)
- [x] [Test plan](https://dsvavsp.testrail.io/index.php?/milestones/view/1154)
- [x] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/399)
- [ ] [Summary(Defects) reports](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [x] [E2E tests](https://github.com/department-of-veterans-affairs/vets-website/pull/23501) (provide a link to the product’s code)
[Unit Tests](https://github.com/department-of-veterans-affairs/vets-website/pull/23480)
[Unit Tests](https://github.com/department-of-veterans-affairs/vets-website/pull/23501)
- [x] [Code coverage](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-unit-test-coverageUnitTestCoverage) (provide a link to the product’s code)  [Back end Tests](https://github.com/department-of-veterans-affairs/vets-api/tree/master/modules/forms_api/spec)
  
**Accessibility artifacts**
  
- [x] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D). For details, see [Prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).
[Accessibility Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54583)
  
##### Platform actions
- [x] Follow Moderator Responsibilities guidance for Staging Review
- [x] Meeting date/time: Friday, March 24, 2023 at 2.00 PM EST

##### Platform actions

- [ ] Update this ticket with the Zoom recording
  - Recording URL: [Zoom recording](https://oddball-io.zoom.us/rec/share/zqpl8NT3UoVt3HXAn7QaGzBw7D_GOMvqH1bnb99N9mBqvppW3WltG47s_EPJuWBl.BGUS7BFwFlwNavkd)
  - Password: K+=5G18N
  
##### VFS actions
  
- [x] Review feedback tickets and comment on the ticket if there are any questions or concerns
- [x] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [x] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [x] Share ServiceNow ticket number here: _req9149854_____
- [x] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete

</details>

### [Privacy, Security, Infrastructure Readiness Review](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/867)

<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [x] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)

- [x] [Release Plan](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/26-4555/Release%20Plan.md)

- [x] [Product Outline](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/26-4555/Product%20Outline.md)

- [x] [Link to the Readiness Review ticket below
](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/867)
#### Platform actions
- [x] Privacy, security, infrastructure readiness review is complete

</details>
