### ISSUE TITLE
Delete placeholder static education pages from staging environment

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#52761]
## Issue Description
We need to make sure the correct versions of static pages go live with the EDU product launches in March. The correct static pages live in drupal (not staging), and the content team will set those to go live on the product team's signal. But 2 placeholder static pages still exist in the staging environment. We don't want there to be any chance that those go live, so they need to be deleted.

**Note:** I believe the 3rd EDU product (TOE) that will also go live in March didn't ever have a placeholder static page created in staging. @btruongafs can you confirm that's true?

---
## Tasks
- [x] Delete https://staging.va.gov/education/verify-school-enrollment/
- [x] Delete https://staging.va.gov/education/download-letters

## Acceptance Criteria
- [ ] The above listed staging pages have been deleted.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by btruongafs** [comment]
@bethpottsVADEPO correct for TOE. we just have the application form intro page https://staging.va.gov/education/survivor-dependent-benefits/apply-for-transferred-benefits-form-22-1990e/introduction
