### ISSUE TITLE
Fix header levels on burial eligibility page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#52767]
## Issue Description

Laura Flannery opened an intake request ticket to fix a header hierarchy issue on the [Eligibility for burial in a VA national cemetery](https://www.va.gov/burials-memorials/eligibility/) page. 

Currently, within the single accordion "Read about Veterans, service members, and family members who aren’t eligible for burial in a VA national cemetery" the headers are H3s but the accordion header level is an H4. 

Since we don't want to go down to H5s, we may need to rework this section and set up the accordions differently. We should talk through the best way to rework this before making changes in Drupal. 

Original intake request: #52666

## Tasks
- [x] Assess how to restructure section to fix headers issue
- [x] Update page in Drupal
- [ ] Send to stakeholders for review
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Page is live with correct header hierarchy

**Comment by laurwill** [comment]
I fixed the headers this Drupal node. Since this was only a header level update with minimal content tweaks, I don't think we need to send to stakeholders — I'm confident I didn't change meaning.

@megzehn , want to review my updates and publish if this looks good to you?

**Comment by megzehn** [comment]
Thanks for making those changes, @laurwill!! 

I reviewed and published the changes.

**Comment by RLHecht** [comment]
These changes are now live. Closing ticket.
