### ISSUE TITLE
Group Peer review of Practice Area operational guidance

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#52771]
## User Story
As a Governance team member, I want to review other practice area's operational guidance so that I understand the process they take for each review.

Peer Reviewer: All

## Description
Last sprint we created first drafts of practice area operational guidance for Midpoint Review. We will now review each other's practice areas and suggest any changes. We're looking for gaps, inconsistencies, misaligned expectations and note where extra coordination is needed (if needed).

## Impacted Artifacts
[How to complete an accessibility review for Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2492727318/How+to+complete+an+Accessibility+review+for+Midpoint+Review)
[How to complete a content review for Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2491613360/51906+-+Draft+-+How+to+complete+a+Content+review+for+Midpoint+review+touchpoint)
[How to complete a design review for Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2492563471/How+to+complete+a+Design+review+for+Midpoint+Review)
[How to complete an IA review for Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2492727325/How+to+complete+an+information+architecture+midpoint+review)

## Tasks
- [ ] Review the 4 impacted artifacts in Confluence
- [ ] Comment on anything that is concerning (eg. does not align across practice areas, expectations of what a specific practice area should be doing, gaps, overlaps, inconsistencies, coordination across practice areas, etc.)
- [ ] Check your name in the box below to indicate you have completed your review
- [ ] **Please complete all reviews by EOD February 8, 2023**

## Peer Review
- [x] All Governance team members review each practice area guidance
  - [x] Allison
  - [x] Brian
  - [x] Cheryl
  - [x] Sara

## Acceptance Criteria
- [x] We have reviewed Governance team proposed guidance for each practice area at Midpoint Review

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@sterkenburgsara reach out to Allison, Brian and/or Cheryl if you have questions or concerns about this ticket.
