### ISSUE TITLE
[eFSR] Cards, Add + Mini Summary for additional sections

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#52773]
## Issue Description
Cards, Add + Mini Summary for:

- Vehicles
- utility bills
- Other debts (installment contracts)
- Employment history

---
## Tasks
- [x] _Additional mockups created in Sketch_

## Acceptance Criteria
- [x] _Mockups available in [Sketch](https://www.sketch.com/s/79aa4a84-fef1-4c06-9495-e0431a6390bd)_
- [x] Mockups uploaded to [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1671734127581/dc254b12e788570c946af60bc55338b0045aea03?sender=ua78f969c4cddcbfe56b27885) _~~UXPin~~ Will be updating UXPin if we regain access_

**Comment by mgleo** [comment]
Additional sections and updates made to Sketch and [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1671734127581/dc254b12e788570c946af60bc55338b0045aea03?sender=ua78f969c4cddcbfe56b27885). 
Installment contracts/debt: Updated to list categories instead of asking users to select a category as a check box
Vehicle section: Updated to include new list loop
Employment: Updated to include new list loop
Utility bills: Updated to include new list loop
