### ISSUE TITLE
Restructure Practice Area Operational Guidance

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#52772]
## User Story
As a Governance team member, I want to ensure that all of our practice area operational guidance for Midpoint Review has a consistent flow, tone and voice so that Governance team products uphold our expectations of VFS teams.

Assignee: @CherylEvans 
Peer Reviewer: @allison0034 

## Description
In ticket #52771, Governance team members peer reviewed the practice area Midpoint Review operational guidance for design, content, IA and accessibility to ensure there were no gaps, overlaps and/or inconsistencies across practice areas when it comes to how we approach and complete a Collaboration Cycle Staging Review. Now that we are confident that the content in the 4 guidance docs is complete, we want to make sure that each guidance doc flows similarly, and meets our content standards for tone, voice and grammar/formatting.

## Impacted Artifacts
[How to document feedback for a Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1945239838/How+to+document+feedback+for+a+Midpoint+Review)

## Tasks
- [ ] Review feedback from ticket #52771 and follow up with team members for clarification if needed
- [x] Ensure all guidance docs are written in a consistent voice, tone, use plain language and use consistent language
- [x] Reorganize headings/sections so all docs have the same flow
- [x] Incorporate [How to document feedback for a Midpoint Review ](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1945239838/How+to+document+feedback+for+a+Midpoint+Review) into all 4 practice area docs.
   - Note: Governance team members should utilize both their practice-area specific guidance and the How to document feedback for a Midpoint Review guidance. It is important that the document feedback guidance and practice area guidance flow and read as 1 piece of guidance. This means, that anything in the document feedback guidance does not need to be in the practice area guidance. Anything that is applicable across the board, regardless of practice area, should be in the document feedback guidance.
   - If changes need to be made to the document feedback guidance, then capture them here and a new ticket will be created for implementation of those changes.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] All practice area specific guidance for Midpoint Review has consistent content and flow.
- [x] Governance team members are able to refer to their specific practice area guidance for MPR for completing a MPR

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
@allison0034 The drafts ([Content](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2491613360/How+to+complete+a+Content+Midpoint+Review), [IA](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2492727325/How+to+complete+an+Information+Architecture+Midpoint+Review), [Design](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2492563471/How+to+complete+a+Design+Midpoint+Review), and [Accessibility](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2492727318/How+to+complete+an+Accessibility+Midpoint+Review)) are ready for your review.

**Comment by allison0034** [comment]
@CherylEvans looks good to me!

**Comment by CherylEvans** [comment]
@allison0034 Thank you!  I made the recommended changes in the Content doc, so it should be good to go as well. :-)
