### ISSUE TITLE
Propose removing QA from the Midpoint Review

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#52783]
## User Story
As a Governance team member, I want to remove QA as a practice area from Midpoint Review as it is not valuable to VFS teams and Governance so that Governance QA can focus on other priority items.

Assignee: @it-harrison 
Peer Reviewer: @shiragoodman 

## Description
In ticket #47534, Governance team reviewed the last 10 Midpoint Reviews to show what QA artifacts have or have not been provided by VFS teams. In 50% of the Midpoint Reviews, the VFS did not provide any QA artifacts. In the other 50%, the feedback received from Governance team was the same: "provide missing QA Standards artifacts." Since QA's purpose on the Governance team has been redefined to only determining whether or not QA standards have been met, and not evaluating the quality of the QA artifacts provided, it no longer seems beneficial for QA to be part of the Midpoint Review. The purpose of this ticket is to provide reasoning and documentation for removing QA from the Midpoint Review and to request approval from OCTO.

## Tasks
- [x] Add on to Ian's [Review of recent Midpoint Review QA feedback](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2502852633/Review+of+recent+Midpoint+Review+QA+feedback) to include a purpose, evidence, and a proposal of what we're seeking
- [x] Rename Confluence page and move to Governance/Ideas (instead of Doc Drafts)
- [x] Share with OCTO for review and approval
   - Shared with Ray via Slack on 2/14. Awaiting approval and/or feedback.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have presented to OCTO our proposal for removing QA from the Midpoint Review

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
@shiragoodman here is a [draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2520449479/Proposal+to+remove+QA+from+the+Midpoint+Review).

**Comment by shiragoodman** [comment]
@it-harrison this looks great. I made 1 comment in the draft. Please address and let me know when it's complete. I will tag Ray for his review and approval.

**Comment by it-harrison** [comment]
@shiragoodman I tweaked the sentence - hopefully it is clear now.

**Comment by it-harrison** [comment]
@shiragoodman I have created issues:
* #53725
* #53726

**Comment by shiragoodman** [comment]
Proposal submitted to Ray for review and approval on 2/14. Awaiting feedback.
