### ISSUE TITLE
BE | Profile | Address Validation | Issue: Province populated on U.S. Territory Addresses

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#52786]
## Background
The mobile team discovered an issue when updating an address for a U.S. territory.   A U.S. territory should have an an `address_type` of `domestic`, but when saving, the `province` field (which should not be populated) is being populated which is causing a validation error.  

There is a validation rule in `lib/va_profile/models/base_address.rb` that explicitly prohibits provinces in domestic addresses so it is not clear how this is happening.

The following are some logs that the mobile team has provided that shows some occurrences of this issue...
```
2023-01-26 18:10:27	payload={"province":"Puerto Rico","address_type":"DOMESTIC"}
2023-01-26 17:52:55	payload={"province":"PR","address_type":"DOMESTIC"}
2023-01-26 17:00:38	payload={"province":"GU (Guam)","address_type":"DOMESTIC"}
2023-01-26 16:49:37	payload={"province":"GU (Guam)","address_type":"DOMESTIC"} 
```

References:
- [Slack Thread](https://dsva.slack.com/archives/CSFV4QTKN/p1674841062061699)
- [Address Validation API](https://developer.va.gov/explore/verification/docs/address_validation?version=current)

## Tasks
- [ ] Write specs to test this scenario to see if it can be reproduced.
- [ ] Reach out to VA Profile to determine if this may be caused by their system.
- [ ] Follow up with mobile team.
  
## Acceptance Criteria
- [ ] Determine what is causing the issue and open the necessary tickets to fix the issue.

**Comment by tpharrison** [comment]
@aherzberg This is the ticket I'll be using for the issue.  Please review and let me know if I captured everything correctly.  Thanks!

**Comment by tpharrison** [comment]
@Samara-Strauss @BerniXiongA6 

@aherzberg and I discussed [the issue](https://dsva.slack.com/archives/CSFV4QTKN/p1674841062061699) that he brought up last Friday.

**Comment by Samara-Strauss** [comment]
@tpharrison thank you! 

Question -- how urgent is this? Can it wait a sprint or two, or does it need to be prioritized.

**Comment by tpharrison** [comment]
@Samara-Strauss The mobile team does have a temporary patch in place, but they are still seeing some errors.  I spoke with Andrew Herzberg and stated that we can work on this in either Sprint 3 or Sprint 4.  He is okay with this.

cc/ @BerniXiongA6

**Comment by aherzberg** [comment]
This looks good! I'll just note that we get validation errors when trying to validate a address change that is domestic and has a province but haven't seen a validation error from the address coming from the user object. but since there's an explicit validation of no province on domestic, then I think it would cause an error.

**Comment by Samara-Strauss** [comment]
@tpharrison I will add this to sprint 4 since you are out all of next week.

**Comment by BerniXiongA6** [comment]
Per @tpharrison lower priority, let's push out a sprint. cc: @Samara-Strauss

**Comment by Samara-Strauss** [comment]
Sounds good! I'll move it back.

**Comment by tpharrison** [comment]
Reached out to Josh Lindsay (VA Profile team) to ask if there is an officially sanctioned list of international military base addresses or any docs that explain how to format those address types for validation.

Josh stated that the VA Profile team uses the [USPS site](https://faq.usps.com/s/article/How-Do-I-Address-Military-Mail) for this.

**Comment by tpharrison** [comment]
The issue appears to be related to [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46388#issuecomment-1242408260).

**Comment by tpharrison** [comment]
@Samara-Strauss @BerniXiongA6 
I've been unable to reproduce this issue in staging (or using my account in prod).  I spoke with Andrew Herzberg from the mobile team and he has not been able to reproduce the issue in staging either.  Unfortunately, the production logs above don't have enough information in them to allow us to reproduce the requests.

My suspicion is that VA Profile may be modifying the record when saving.  We seen this before (see the ticket referenced above).

Andrew is going to try and reproduce again on Monday.  In the meantime, I'm going to update the status to blocked.

**Comment by Samara-Strauss** [comment]
@tpharrison do you need to regroup with Josh Lindsey again re: the possibility VA Profile is modifying records when saving?

And if Andrew can't reproduce, does it make sense to keep this issue open or close it out?

**Comment by tpharrison** [comment]
@Samara-Strauss I didn't want to reach out to Josh until I was able to reproduce the issue because I wouldn't have much for him to go on.  

If Andrew can't reproduce on Monday, then I'll close it out (if that's okay with you).

Just FYI - I asked Andrew if he knew how many users this is affecting.  Here is his response...
> _so looks like the the issue isn't super common. Only 472 for mobile only in the last week. Having a hard time to get a raw number out of how many logins we had to compare to that number but in the last 15 minutes there were 2095 logins and only 3 of them had domestic address with a province._

**Comment by Samara-Strauss** [comment]
If Andrew is unable to reproduce, I think it's OK to close out. It seems low priority, and not worth your time right now to dig into this if it ends up being un-reproduceable.

**Comment by tpharrison** [comment]
We weren't able to reproduce this in staging.
