### ISSUE TITLE
Certificate of Eligibility | View uploaded documents

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#52781]
## Value Statement
**_As a_** Veteran
**_I want to_** see the documents I submitted with my application
**_So that_** I can quickly and easily recall what I've shared. 

---
## Background Context
LGY application processors sometimes need to request additional documentation from Veterans. It's helpful for Veterans to see what they've already shared to minimize friction in the application process. 

## Acceptance Criteria
- [ ] Veterans can see their documents. 
- [ ] The name of the document appears as saved. 
- [ ] Content language reflects the functionality on the page.

## Designs and Build Notes
- [Link to previous design documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/apply-for-home-loan-COE/coe-transition-design.md)

## Out of scope
- We are building MVP functionality

## Tasks
- [ ] Sync with LGY stakeholders and users.
- [ ] Draft design.

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
@uxgary Hey Gary - can you post a link to the draft design for review ahead of backlog refinement tomorrow?

**Comment by uxgary** [comment]
Here's a link what I have in draft so far. https://sketch.com/s/b3237bfe-9e5c-4b5d-a958-66632d9a7fe3

**Comment by saderagsdale** [comment]
@uxgary review existing patterns on VA.gov, schedule design collab reivew.

**Comment by saderagsdale** [comment]
@uxgary will bring this up in design office hours.

**Comment by saderagsdale** [comment]
Sade to find ticket template for collab cycle.

**Comment by saderagsdale** [comment]
Moving to icebox

**Comment by Midge-dev** [comment]
Closing duplicate

https://app.zenhub.com/workspaces/benefits-non-disability-645913c7d909c20011380ae8/issues/gh/department-of-veterans-affairs/va.gov-team/52213

**Comment by saderagsdale** [comment]
@Midge-dev @steele-lm This is not a dupe, just FYI. The scope of this ticket is different than the current functionality. Today Veterans can see what they're uploading, but they can't revisit it. The scope of this ticket is to enable Veterans to review what they've uploaded after submission. We put this stakeholder feature request on hold because it was a lower priority at the time.

**Comment by steele-lm** [comment]
@saderagsdale The AC in #55213 includes the ability to view document contents, so I think that's where the confusion might have originated. It sounds like that AC should be removed from 55213 because it's covered in this ticket -- is that correct?

**Comment by saderagsdale** [comment]
@steele-lm If your team has picked this back up, then we may want to have a refinement discussion so I understand the context of what you're doing.
