### ISSUE TITLE
Build Form from Scratch

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#5278]
## Goal
We want to get our feet wet with what we think is the next best steps for the 686 and building out a form from scratch would be informative.  Scaffolding out the 686 from scratch with a workflow to validate the assumption that not moving forward with the rainbows work.

## Tasks
- [x] Run the Form Generator
  - [x] Adjust some configurations 
- [ ] Incorporate a workflow or two (hardest one?)
  - [ ] Breakout into seperate, smaller tickets

## Acceptance Criteria
- [ ] Share results with the team and discuss as needed (Monday at standup)

**Comment by micahchiang** [comment]
Commenting here for visibility. Submitted a draft PR for work that adds the chapters related the wizard and the report a death workflows.

https://github.com/department-of-veterans-affairs/vets-website/pull/11624
