### ISSUE TITLE
Logged-in IA/nav generative research: Complete analytics review

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#52796]
## Background

[Analytics review doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ia-and-navigation/2023-generative-logged-in-research/analytics-review.md)

As part of the logged-in IA/nav research, we want to take a look at some analytics and see what we can learn before going into user research.

## Tasks

- [x] Pull and document analytics outlined in the doc above
- [x] If there are analytics we don't know how to find, make note of that
- [ ] Review with Samara to determine next steps

## Acceptance criteria

- [ ] Analytics have been reviewed with Samara, and no further work is needed

**Comment by andaleliz** [comment]
I've reviewed this ticket and updated the estimate from a 3 to a 5 to account for "gotchas" and weird challenges that come up when digging into these reports.

Offhand, do you know if there are already events in place to determine this one, @Samara-Strauss?

> What is the % breakdown of people who click sign in CTAs vs. "Create Account" CTAs?

**Comment by andaleliz** [comment]
@BerniXiongA6 or @Samara-Strauss, I realize I'm not clear on what "best bets" means within the context of Search. Are those the type ahead suggestions?

**Comment by Samara-Strauss** [comment]
@andaleliz I believe these are best bets, but can you confirm with @mnorthuis? 
![image](https://user-images.githubusercontent.com/34068740/221855425-b101c2f9-621b-4ca9-b19e-1c077e98cf59.png)

**Comment by Samara-Strauss** [comment]
> Offhand, do you know if there are already events in place to determine this one, @Samara-Strauss?
> 
> What is the % breakdown of people who click sign in CTAs vs. "Create Account" CTAs?

I do not actually know this. I was going to say -- if there are stats we can't get or don't have events for yet, don't worry about and just note that in the document. I know analytics is swamped right now, and unless they can help us get stuff set up quickly (which I doubt since they are a skeleton crew), we should get what we can and note where there are still holes or questions.

**Comment by andaleliz** [comment]
Thank you Samara!  I'll check with @mnorthuis on that one - I think you're right too.

Adding another question related to "For the [top ten?] most popular logged in tasks, how many clicks/page visits does it take for people to get to those pages?"

To answer this, we first need to define/reconfirm what are the most popular logged in tasks. 

1. **How are we defining a task?**  

2. **Do we assume most popular tasks are 1:1 to the most popular pages a person can complete a task on?** I think it's more nuanced than that because there are a few claim related pages that are in the top 25 pages, but those are all about the task of checking a claim status.

**Comment by andaleliz** [comment]
@Samara-Strauss, for the questions that ask to list the top pages, are tables OK or do you want that presented in some other format? I've [written a draft](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ia-and-navigation/2023-generative-logged-in-research/analytics-review.md), which you can peek at to see what I mean about the tables.

I've taken this as far as I can on my own and set up time for Thursday to discuss the outstanding questions I have for the analytics team (outlined at the top of the doc).

**Comment by Samara-Strauss** [comment]
Thank you for this, @andaleliz. I've given this a quick glance, and I am hoping to give this a more thorough review as I'm able.

Also cc'ing @mnorthuis and @clantosswett for awareness that Liz has been pulling analytics for the logged-in IA/nav research.

**Comment by andaleliz** [comment]
You're welcome @Samara-Strauss. It's very much a work in progress, I wouldn't normally share it with anyone for review at this stage. But since you and Mikki are both out for a bit, I figure I better get some eyes on it sooner rather than later.

I plan answer each question with a brief summary, a link to a relevant report, and then whatever data might make sense to display in a table.

For many of the "top page" questions, I decided on the top 25, because in the top 10 there were various flavors of the same page/task e.g. claims. I think the information is a little richer if we look past those top 10 tasks.

Once I meet with Michelle, I will also get all those outstanding questions answered.

**Comment by Samara-Strauss** [comment]
All of this sounds great. Thank you, Liz!!

**Comment by andaleliz** [comment]
Hi @Samara-Strauss, (cc @clantosswett and @mnorthuis for awareness) I've finally got all the questions answered in [my report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ia-and-navigation/2023-generative-logged-in-research/analytics-review-findngs.md) - at least those that are answerable right now. I've noted those that aren't.

How would you like to proceed as a next step? I see a task here is to review with you and determine next steps.  Not sure if you'd like to do an async review, or set up a time for me to walk you through the doc. Either way works for me.

A clear next step for me is to start working on the research plan, which I will begin as I await your comments :) Thanks!

**Comment by Samara-Strauss** [comment]
@andaleliz this is truly incredible. Such a great resource.

Only one request -- can you put the time period for each report in the Github file so we don't have to click into the individual reports to get that information? That way, it'll be clearer what's a quarterly report vs. a year-long report.

And one note on that -- I clicked into one report that was quarterly, and the time period was Feb 1, 2022 - May 1, 2022 or something. For anything quarterly, can you run those reports for the last 90 days, not the first 90 days of the entire last year?

**Comment by andaleliz** [comment]
@Samara-Strauss YAY! I'm glad you think so. This was a challenging bit of work for me - in a good way.  Too bad GA4 is going to destroy everything I know about GA 🥴 

Yes - I can definitely move the time periods to each report (there's one reference at the top, but I can see how its more helpful with each report) and double check that they're using most recent quarter.

**Comment by clantosswett** [comment]
@andaleliz this is awesome! So much information to digest so I would propose finding a time to meet about this and maybe talk through a bit, that is if people feel like they have the bandwidth to do that. But I am going to try to spend some time reviewing more of this and will make note of questions or comments here to be answered or just to keep track if/when we do chat. 

Thanks!

**Comment by clantosswett** [comment]
This is probably a dumb question but is /index.html the homepage? My assumption is yes but just want to make sure.

**Comment by andaleliz** [comment]
I've updated the findings w/ the date range for each report, and also updated the names so the kind of report is ultra clear. That'll also prob be better for screen readers who likely don't want to hear "link - report" repeated 25 times on the page.

**Comment by Samara-Strauss** [comment]
Thank you, @andaleliz! It's up to you whether you want to close this ticket out, or wait until after our meeting on Monday. Fantastic work all around!

**Comment by andaleliz** [comment]
You're welcome @Samara-Strauss! I'll leave this open since one of the tasks was a review + determining next steps, and our meeting will take place during the sprint.

**Comment by mnorthuis** [comment]
Unfortunately search.gov does not have impression data on best bets - that would have been helpful info. However, they did send over data on number of clicks for current best bets for the.  This report is a 30 day view (not just for the month of March).

[VA Best Bets Export - March 2023.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10961468/VA.Best.Bets.Export.-.March.2023.xlsx)

**Comment by andaleliz** [comment]
Thanks Mikki, that's too bad about the impression data.  If we want that moving forward, I know it is technically feasible to fire an event in Google Analytics when something loads, so you could (or whoever is in charge of search) ask for this to be added, and then it could be cross-referenced with the click event we already have to measure engagement.

**Comment by andaleliz** [comment]
The team met today and we are aligned on the next step of using these analytics to inform the conversation guide for upcoming user research.
