### ISSUE TITLE
Overview of BGS Endpoints

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#5279]
## Goal
We want to become more familiar with the BGS endpoints in Rational and learn more about what is happening for the 686 submission process when a Veteran updates info.  The EVSS sustainment team should be able to help us.

## Tasks
- [x] Schedule a time with the EVSS Sustainment team (Mike Walker is active in #evss-prod in Slack) to go over:
  - where the source code is located
  - how it is accessed

## Acceptance Criteria
- [x] A meeting with a member of the EVSS Sustainment Team has been scheduled  
- [x] Draft plan notes in GH (686 engineering research repo)

**Comment by kathleencrawford** [comment]
Discussed this with Mike Walker via Slack and was told that in order to access the source code, we need to request access from the Rational Tools team to download Eclipse w/ integrated Rational plugin.

I submitted a request on Thursday, Jan 30, to the Rational tools team and a ticket was created for me by Bob Henrikson.

**Comment by kathleencrawford** [comment]
Eclipse w/ Rational plugin installed and configured.  Meeting with EVSS Sustainment team scheduled for this coming Thursday.

**Comment by kathleencrawford** [comment]
Initial plan notes/draft documented here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/engineering/bgs-vnp-integration.md
