### ISSUE TITLE
Address Questions in ESECC Ticket

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#52808]
# Description
Raw feedback from ESECC is below --

> Tech review comments -- Needs clarifications.
Request is for 2 inbound web flows using the same GWW ELB AWS FQDN for a real server pool member. Originally this was requested using port 443 (HTTPS) in a different RFC.  This RFC is asking for following as ports:  3000: HTTPS; 3001: HTTPS.  Not clear if PORT 443 HTTPS is needed in addition to port 3000 and 3001 or if the non-standard ports are being used in place of port 443 for some reason.  It may be best to put this in a spread sheet and attach it to the RFC for review.  Using non-standard ports are a red flag and should be discussed in the weekly ESECC RFC review calls on Wednesday and Thursday mornings with ENSTT review.  Justification for the non-standard ports not shown in the RFC.  Also, a POAM is required for open medium risk in WASA report.  Attach the PIA and PTA for this request.

Parsing out these requests / issues looks like this:
1. Confirm port usage with Devops COP
   1. ESECC prefers standard HTTPS port config
   1. If using non-standard ports we will need to provide justification in the ticket
1. Create spreadsheet with requested flows listed, justified, and explained in more detail
1. Check the WASA scan that was attached to the ticket for open POAM
   1. Attach correct WASA scan
   1. Or, attach remediation proof for POAM

# Tasks
- [x] Process requests for additional information described above

# Acceptance Criteria
- [x] All open issues from ESECC are responded to

**Comment by pjhill** [comment]
1. Attached a worksheet to address more detailed mapping of FQDN and ports
2. Pushed back on the WASA scan a bit. The WASA scan attached to the ticket describes a "low" risk, and the risk has been remediated. I described the remediation in a bit more detail in a comment on the ESECC ticket.

# To do
- [ ] Update docker image creation tickets to include configuration of standard HTTPS port 443

**Comment by pjhill** [comment]
* Approvals for ESECC request have been granted.
* Another level approval remains with Chris Johnston
* Joe has made Ray aware of the approval needed from Chris Johnston

**Comment by pjhill** [comment]
Created[ this placeholder](https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/53608) to address the need to configure our FE to use port 443 in order to comply with ESECC's request and the traffic flow that they will be creating.
