### ISSUE TITLE
Create R&S page: Beneficiary financial counseling and will prep

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#52815]
## Issue Description
We need to migrate this legacy life insurance page: https://www.benefits.va.gov/insurance/bfcs.asp

This will go in the R&S section of the site.

---
## Tasks
- [ ] Draft R&S
- [ ] Review (Laura)
- [ ] Copyedit (Megan)
- [ ] Send to Steve for review (Laura)
- [ ] Prepub/publish (Megan)
- [ ] Request redirect (Laura)

## Acceptance Criteria
- [ ] New page is live and legacy is redirected

**Comment by RLHecht** [comment]
Pausing on this migration work for now. Moving to the backlog

**Comment by laurenvocke-va** [comment]
@bethpottsVADEPO @RLHecht to review

**Comment by mistymg** [comment]
@DanielleThierryUSDSVA will put this in life insurance epic when created.
