### ISSUE TITLE
[eFSR] Spouse - Benefit Information Page

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#52819]
## Issue Description
Update Spouse benefit information page to [match design](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages/145868500/specification/sitemap?mode=i). Good news is that we can use standard VAFS functionality without any super custom logic. 

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/18dca195-1bc3-448a-8309-c981240d340a)

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/3e6fca00-c201-4d86-8a61-5b38c494c79b)

---
## Tasks
- [x] Add Spouse Benefit information radio option page 
- [x] Add Spouse Benefit information page with inputs
- [x] Add / Update unit tests for new page
- [x] Add / Update end to end tests for new page

## Acceptance Criteria
- [x] Spouse Benefit information page matches design and is hidden behind EFSR feature flag
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
Closed out[ larger ticket ](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/48750)with these smaller ones: 
- [Employment History](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/52818)
- [Other Income](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/52820)

**Comment by amponce** [comment]
Confirmed that these changes have already been implemented on the eFSR form:

![Screenshot 2023-02-22 at 2 49 10 PM](https://user-images.githubusercontent.com/3916436/220778374-697928b3-36d8-4184-bda9-c0d6da807598.png)


![Screenshot 2023-02-22 at 2 48 57 PM](https://user-images.githubusercontent.com/3916436/220778285-4ceed7bd-1609-4c21-b140-3de3d49f4306.png)
