### ISSUE TITLE
Create R&S page: SGLI online enrollment system

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#52816]
## Issue Description
We need to migrate this legacy life insurance page: https://www.benefits.va.gov/INSURANCE/SOES.asp

This will go in R&S.

---
## Tasks
- [ ] Draft R&S
- [ ] Review (Laura)
- [ ] Copyedit (Megan)
- [ ] Send to Steve for review (Laura)
- [ ] Prepub/publish (Megan)
- [ ] Request redirect (Laura)

## Acceptance Criteria
- [ ] New page is live and legacy is redirected

**Comment by katherine-fung** [comment]
@laurwill - I'm working on a draft of this page. I have some questions for life insurance SMEs in the meantime: 

Questions about SGLI:

1. For this section on the legacy page: 

"What if Servicemembers don't have access to a computer?
Members can complete paper elections using the SGLV 8286 and provide it to their Personnel Office to ensure their wishes are known. When computer access is obtained, go into SOES and make the appropriate elections/updates." 
What does this mean? If someone submits a paper form, do they still need to make changes online?

2. For this section

"Can a Servicemember’s beneficiary make a claim for SGLI benefits through SOES?
No, beneficiaries will need to contact the Casualty Office to make a claim."

What is the contact info for the "Casualty Office"? (also is there another name for them?) 
 
3. on the legacy page, we say that certain changes to coverage will only be visible online the first day of the new month ("Until that date passes, the member will continue to see the previous coverage amount."). But the page also reads:

"How will Servicemembers know that the changes have been made to their SGLI coverage?
After confirming and certifying the changes, a Servicemember can view his/her updates in SOES. Pending changes will be noted on the home screen. Members may also view, print, save or email the SGLI Certificate of Coverage on-line to see changes."

Can we get clarity on which updates will show in SOES, which changes will show as pending, and which won't show until the 1st day of the next month? 

4. What's the reasoning for having this information on the legacy page? 
"If a Servicemember is deployed and wants to make changes to beneficiaries or coverage through SOES, can someone do it on their behalf?
A Servicemember must make his/her own elections and changes in SOES. No third party currently has the ability to make changes to a Servicemember’s account."

Also, this section seems irrelevant because you can't use SOES to enroll in VGLI. What's the reasoning for having it on the page? Could we explore removing it? 
"Will beneficiaries and coverage amounts automatically transfer to VGLI with SOES?
Coverage amounts will not be automatically transferred to VGLI when a Servicemember separates from service. Beneficiary designations will transfer for only 60 days after the effective date of VGLI coverage. When applying for VGLI, separating Servicemembers are asked to name a beneficiary and can update that beneficiary at any time once the coverage is in effect. However, in limited situations with legally-mandated time frames, such as when the separating Servicemember is incompetent, the SGLI beneficiary designation listed in SOES will be the VGLI designation of record."

5. Confirming that we don't say "VA Form" for Prudential forms (based on this page: https://www.va.gov/resources/change-your-address-on-file-with-va/)

**Comment by katherine-fung** [comment]
We're pausing work on this page for now, per Beth and Danielle. 

Here's the draft in progress, for when we start work on this again: 
[https://app.zenhub.com/files/133843125/5cdb8330-1977-4bcf-853f-2d893df75bed/download](https://app.zenhub.com/files/133843125/5cdb8330-1977-4bcf-853f-2d893df75bed/download)

**Comment by RLHecht** [comment]
Moving this to the backlog as we're pausing on this effort for now.

**Comment by mistymg** [comment]
Still pausing on this until we turn to migration efforts related to this.
