### ISSUE TITLE
Clarify "Moderator script" intent and purpose on touchpoint pages

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#52812]
## User Story
As a VFS team member, I want to understand what the Moderator Script is and why it's included on the touchpoint page so that I know how to interpret this information and better prepare for my upcoming touchpoint. 

Assignee: @briandeconinck 
Peer Reviewer: @CherylEvans 

## Description
All 3 touchpoint pages on Platform Website (DI, MPR, and SR) include the Moderator Script, however there is no context as to what this is, why it's here or why its valuable. It's also not clear that this is the script we will read at the meeting.

The purpose of this ticket is to add some guidance around the moderator script within the 3 touchpoint pages.

## Impacted Artifacts
Moderator scripts for:
[Design Intent touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent)
[Midpoint Review touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)
[Staging Review touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)

## Tasks
- [x] Create draft pages of all 3 documents
   - [Draft pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2519498790/52812+-+Moderator+script+context)
- [x] Add some additional informational test below each "Moderator Script" heading explaining what this is, why it's here and why it's valuable. Keep it brief.
- [x] Alter the existing Moderator Script so it is clear this is a script
   - options: italicize, put in quotes, put a box around the text, etc.
   - Using the Confluence "Quote" design element, which maps to HTML `blockquote`. The Scroll Viewport color palette for Platform website isn't *great* here but the `blockquote` meets WCAG AA minimums. But that's maybe something to explore more in #51108 some day.
- [x] All 3 pages should be consistent

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS teams understand what the Moderator script is and why it's published to the touchpoint pages for DI, MPR, and SR

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
@CherylEvans [Draft updates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2519498790/52812+-+Moderator+script+context) are ready for review. All changes are in the Moderator Script section on each page.

**Comment by CherylEvans** [comment]
@briandeconinck I like what you have written and feel that it satisfies the user story for content.  However, contextually I feel that it belongs **before** the actual script.
"Each Design Intent meeting begins with the Governance team moderator reading the Moderator script.
This script ensures that everyone participating in the meeting and watching the recording after the meeting understands why the meeting takes place, how it will proceed, and how teams should expect to receive feedback from Platform." 
And the script would go below this.  What are your thoughts?
Also, I changed the verbiage very slightly. :-)

**Comment by briandeconinck** [comment]
@CherylEvans I like your suggested edits! I've updated the draft pages and the actual touchpoint pages in Confluence. Changes should be published to Platform website on Monday.

- [Design Intent touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent)
- [Midpoint Review touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)
- [Staging Review touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)

**Comment by CherylEvans** [comment]
@briandeconinck Thank you, Brian!  I am starting my review.

**Comment by CherylEvans** [comment]
@briandeconinck All 3 drafts for ticket 52812 (DI, MPR, and SR) look great! Peer review complete.

**Comment by shiragoodman** [comment]
@briandeconinck please find time today to publish the approved changes before End of Sprint. If you have anything blocking you, please let me know ASAP. thank you!
