### ISSUE TITLE
[eFSR] Spouse - Employment Information Loop

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#52818]
## Issue Description
Spouse employment history needs to be updated to match veteran employment history loop. 

Adding history flow should match veteran history along with design. Similar to below:
![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/d300a5a6-a9bc-48a5-b369-928157921bc9)

The cards and radio button will likely change after design review.

---
## Tasks
- [ ] Add The following pages:
  - [ ] Employment mini summary 
  - [ ] Employment history information 
  - [ ] Current employment income 
  - [ ] Current employment deductions checklist 
  - [ ] Current employment deductions input
- [ ] Add/Update necessary unit tests for these page additions
- [ ] Add/Update necessary end to end tests for these page additions

## Acceptance Criteria
- [ ] Spouse employment history loop matches veteran history loop
- [ ] Spouse employment history is hidden behind EFSR feature flag
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
