### ISSUE TITLE
[eFSR] Spouse - Other Income 

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#52820]
## Issue Description
Update Spouse Other income page(s) to follow veteran other income page:
![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/5b5beaf4-60b2-46a4-9ee7-b806fc1c91ff)

---
## Tasks
- [ ] Add the following pages:
  - [ ] Other income checklist
  - [ ] Other income input list
- [ ] Add / Update unit tests for new page(s)
- [ ] Add / Update end to end tests for new page(s)

## Acceptance Criteria
- [ ] New pages match design and are hidden behind EFSR feature flag

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
Closed out[ larger ticket ](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/48750)with these smaller ones: 
- [Employment History](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/52818)
- [Benefit Information](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/52819)

**Comment by OptionSelect** [comment]
Rolling over due to being out for a half day and dealing with weird bug in git.
