### ISSUE TITLE
Content changes to Request financial hardship assistance page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#52847]
## Issue Description

We have a request to for content changes to our [Request financial hardship assistance](https://www.va.gov/health-care/pay-copay-bill/financial-hardship/) page. We need to update this page to accommodate the new debt portal. We previously added an alert but now we need to incorporate the info further. Danielle said the SME for debt had reached out to her fellow SMEs for any specific considerations, but she hasn't seen anything come in from them. So the writer will need to connect with our SME to get considerations and take the next step. 

We want to keep this scoped in terms of not reimagining everything, but just making sure that everything is accurate and up to date.

## Tasks
- [x] Connect with SME (Aliyah)
- [x] Review user flow with PM (Aliyah)
- [x] Update page in Drupal (Aliyah)
- [x] Edit (Laura)
- [ ] ~OCTO review (Danielle)~
- [x] Send to partners for approval (Aliyah)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [ ] Content is updated on the live page with info about debt portal

**Comment by RLHecht** [comment]
@aliyahblackmore I updated the info at the top of this ticket with what Danielle said the work is. You'll need to ask her who the SME is you should be working with. Could you also please add an estimate once you have a better handle on the ticket? Thanks!

**Comment by aliyahblackmore** [comment]
Thanks Randi! 

**Just an update here:** 
Danielle is going to connect me via email with the SMEs and I was in touch with Denise about reviewing the user flow for the new debt portal. We'll meeting next Wednesday 2/22.

**Comment by aliyahblackmore** [comment]
**Update here:** Danielle connected me with the SME and I sent a few questions over this afternoon.

**Comment by aliyahblackmore** [comment]
**Update:** Denise proposed a new meeting time (SME will be joining the meeting) for 2/28. 
Will pause on this until after our meeting!

**Comment by aliyahblackmore** [comment]
**Update:** Met with Denise this AM. Will draft suggestions and get these in to Drupal. 
No additional SME feedback needs our attention right now.

**Comment by aliyahblackmore** [comment]
**Update:** I drafted up the bulk of content for this. I have two questions out to Denise re: the requirements for debt forgiveness and the letter (for the by mail or in person option). Waiting for a response from her, will update my content and get it in Drupal.

**Comment by aliyahblackmore** [comment]
Hi @laurwill - this work is ready for you to review when you have a moment. 
Preview link: 

A few notes and questions on this:

1. I moved this content out of the process list component, as we are also including the online option and the same steps aren't needed here.  Danielle mentioned it’s okay to move away from this.
2. This may be slightly outside of the scope for this ask/ticket, but I wondered if the page structure should shift at all. For example, creating another H2s along the lines of "Types of repayment options" and nestling the two options within that or making the repayment options their own H2s? Open to any thoughts on this. 
3. Under the question “What can I do if I can’t afford to pay my current VA copay debt?” I changed the use of “below” to “on this page.” Wanted to get rid of directional language. 
4. Denise confirmed that we can use “Financial Status Report” 
5. You’ll see that there are 2 relief options now. I confirmed with Jill that the tool currently has those two options (debt forgiveness and compromise). For consistency, matching the options on this page.  This is a screen capture of the language. 
![Types of waiver for copay debt](https://user-images.githubusercontent.com/102090263/223236101-c605f09e-c262-4cb8-98fa-5961504f32ca.png)

6. Denise mentioned that writing a letter isn’t required, but it is helpful in requesting debt so that VA has more context for the reason. Someone can also request a hearing to explain why they are requesting  relief. I'm curious about your thoughts here about this information -- would some sort of additional info component be useful here? 
7. I initially tired out placing this info with smaller paragraphs, but the text felt a bit long. I tried out presenting the mail or in person options in a list using numbers, similar to this [VHIE page](https://www.va.gov/resources/the-veterans-health-information-exchange-vhie/). Let me know if the use of numbers works here! 
8. Do we need to adjust language on the form page on VA.gov, so that the language matches re: calling this the Financial Status Report? Something like, you can also use our online Financial Status Report to request help for VA debt related to copay bills. https://www.va.gov/find-forms/about-form-5655/
9. On the [manage your VA debt page](https://www.va.gov/manage-va-debt/), I noticed that we use “Health Resource Center” for the telephone number. Do we need to specify the specific center in the contact info on this page?
10. Should we link to the screen that has the “Is this the form you need” options or should we link directly to the form in the online tool (circled in the screen capture). This info seems to exist on the same URL, but just wanted to clarify which section we should link to. This is a screen capture of the "for you need" options - and I circled the link to go directly to the form.
![Screen Shot 2023-03-06 at 12 14 10 PM](https://user-images.githubusercontent.com/102090263/223239466-f3853c35-6b79-4774-989e-b06994ad5523.png)

**Comment by laurwill** [comment]
@aliyahblackmore as we chatted, next step is to confirm with SMEs:
- How do Veterans request a hearing (both in the online form and PDF option)? And is the hearing recommended as strongly as the letter, or is this more optional?
- Is it still true that there's no way to request a payment plan online for copay debts?

And when you next update the Drupal page, could you remove the subway map styling for options 1 and 3? 

I'll plan to review an updated draft when I'm back. Thank you!

**Comment by aliyahblackmore** [comment]
Thank @laurwill - I passed questions to SMEs earlier today! 

Will make updates once I hear back from them.

**Comment by aliyahblackmore** [comment]
Updates from this week: 

- Jill, Denise, Danielle, and I met this week and intended to chat through the two remaining questions, but the majority of convo was about a few other logistics that span various pages.
- I went ahead and reached out to Denise and Jill to set up another time to chat about our questions.
- After we get answers to the questions, we'll integrate that info, get approval on content from Jill, and move forward with getting the debt portal link up on the financial hardship page (in the page vs. at the top using an info alert).
-After we publish the page with the link, we'll start on an audit of info on the auth and unauth pages,  note any differences between the two, and compile a list of questions. After the audit, we'll do another sweep of content to be sure everything is aligned with the portal content (as that should be most up to date).
- In the future, we can make any updates to this page as needed.

**Comment by aliyahblackmore** [comment]
**Just an additional update here**: 

- We needed to update a link on another section of this page (IT ticket). I went in and reverted to the last published version (October 2022 - by Danielle) and added in the link. This was published by Megan and then reverted back to the most recent draft version. I'll just need to check that the new link is updated.\ 
- Laura and I reviewed the last 3 questions with Jill and Denise this afternoon.

**Next steps for me:** 

- I'll move forward with making changes to the language about "hearings."
- We'll wait for confirmation about "hearings" and "write-offs." Jill and Denise are sending an email about this.

**Comment by aliyahblackmore** [comment]
**Update here on completed next step @laurwill:** 

- I went ahead and made changes to the language about hearings to reflect the instruction we chatted about - mention of folks saying this in their letter. Denise and Jill mentioned that they were confirming this with SMEs. I'll follow up with them about whether they got an answer about this and about "write-offs."

- Let me know your thoughts here. I'm wondering we want to move "We'll send you a notice with a date, time, and place" after the sentence that starts with "Submit your completed form.." 

- Also, curious about your thoughts on using "take these steps?" 
Thinking that this could be changed to something like this: "You can also follow these steps to explain..."

**Comment by aliyahblackmore** [comment]
**Update here:** 
Reached out to Jill and Denise on Slack thread re: two open questions they are getting more info about.

**Comment by DanielleThierryUSDSVA** [comment]
@aliyahblackmore @laurwill Hi! I had a conversation with Jill and Denise about needing to change the order of the options on this page (debt relief first, then repayment). I made the changes and some tweaks to language while in there that you'll see in the file. I know there's a desire to launch these updates soon, but it sounds like we have just a couple of open questions still. Let me know if the updates look good to you and then we can ask for confirmation on the last open questions. Thanks!

**Comment by aliyahblackmore** [comment]
**Just tracking an update here:** 

I'll send off the email to Jill and Denise tomorrow morning. I sent one last question to Danielle re: the use of "copay debt" vs. "copay bills"

**Comment by aliyahblackmore** [comment]
I sent our changes to Jill for her approval. 

**These were the page adjustments:** 

- We removed the Financial Status Report (FSR) tool link and the alert from the top of the page

- We moved debt relief up to be option 1 and added the FSR tool link here

- We adjusted the relief options to align with the what’s in the FSR tool and made a few other adjustments to terms to align with VA style guide standards (changed "copay debt" to "copay bills")

- Danielle also made the changes she discussed with Jill. 

- I adjusted the spacing in the page intro and changed "copay debt" to "copay bills"

**Comment by RLHecht** [comment]
@aliyahblackmore checking on this one. Is this still with Jill?

**Comment by aliyahblackmore** [comment]
Hi @RLHecht - yes this is still with Jill. I sent her a follow up email yesterday and then pinged her on our thread on Slack.

**Comment by aliyahblackmore** [comment]
Hi @megzehn - this is ready for you! 

We got approval from Jill on the changes on the Request for financial hardship assistance page

**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=706

**Changes:** 

- We removed the Financial Status Report (FSR) tool link and the alert from the top of the page

- We moved debt relief up to be option 1 and added the FSR tool link here

- We adjusted the relief options to align with the what’s in the FSR tool and made a few other adjustments to terms to align with VA style guide standards (changed "copay debt" to "copay bills")

- Danielle also made the changes she discussed with Jill.

- I adjusted the spacing in the page intro and changed "copay debt" to "copay bills"

**Comment by aliyahblackmore** [comment]
Thanks @megzehn! I emailed Jill and Denise with the link to the live changes. 

This is ready to close @coforma-terry!
