### ISSUE TITLE
Request `vets-api` Admin Add GH Secret

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#52854]
# Description
In order to follow the pattern in use with `vets-api`, we need to add a GitHub secret `PE_ECR_REPOSITORY` to `vets-api` which will be the path to the backend ECR repository we will be using for preview environments.

# Tasks
- [x] Discover who has admin access to `vets-api`
- [x] Request that the secret `PE_ECR_REPOSITORY` be added
- [x] Verify that the value stored in `PE_ECR_REPOSITORY` is correct

# Acceptance Criteria
- [x] `PE_ECR_REPOSITORY` is available for use with GHA in `vets-api`

**Comment by powellkerry** [comment]
@pjhill had admin access to add the secret. It was added with the value of `dsva/preview-environment/vets-api`

We were unable to verify the value of `ECR_REPOSITORY` so it is unclear whether this is the right value.

**Comment by pjhill** [comment]
The call was coming from inside the house!  Thanks for getting this done speedily.
