### ISSUE TITLE
[BE] Hand-off Pre-check-in to Day-of Check-in Design Document

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#52867]
## User Story
As a veteran, I should be able to check in on the day of the appointment using a pre-check-in link

## Tasks
- [ ] [BE] Create a design document with all possible options
- [ ] [BE] Sequence diagram for all the proposed design options

## Acceptance Criteria
- [ ] Review with the engineering team

**Comment by kanchanasuriya** [comment]
Consolidated all the investigations & design options considered in [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/pre-check-in_hand-off/README.md)
