### ISSUE TITLE
Add signature date to FSR PDF

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#52864]
## Issue Description
Provide date of FSR submission to signature date box on FSR PDF. 

---
## Tasks
- [x] Add mapping of data point to necessary PDF box in filler logic

## Acceptance Criteria
- [x] Date signature has been added to FSR date
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Moving to blocked due to lack of access to PDF editor

**Comment by HeatherRienks** [comment]
@ScottyRJames - LMK if you need help with getting a PDF editor. 

cc: @denisecoveyduc

**Comment by HeatherRienks** [comment]
@josephrlee -thanks for offering to help on this one, if needed. :)

**Comment by HeatherRienks** [comment]
@ScottyRJames - any updates from Jeff Chant on this? Would love to get this one closed out by end of Sprint 94. Thanks!

cc: @denisecoveyduc

**Comment by HeatherRienks** [comment]
@ScottyRJames - any updates on this one? Thx!

**Comment by ScottyRJames** [comment]
@HeatherRienks Jill mentioned there shouldn't be any issues with sharing the template. Reached out to Jeff to see if they're willing to share.

**Comment by denisecoveyduc** [comment]
Adjusting the sizing to this one now that we understand the scope a bit better

**Comment by HeatherRienks** [comment]
Update - communication over email with Jeff Chant/Joey.

**Comment by HeatherRienks** [comment]
Pinged Joey/Jeff again for an update

**Comment by ScottyRJames** [comment]
PDF with signature fields has been obtained from DMC, unblocking this.

**Comment by HeatherRienks** [comment]
@ScottyRJames - anything we need on this now that we are unblocked?

**Comment by ScottyRJames** [comment]
@HeatherRienks Nothing needed presently! Hoping to get knocked out soon

**Comment by ScottyRJames** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-api/pull/12382) opened!

May roll over if no review before 4/12
