### ISSUE TITLE
(Samara) Assist Tech Team 2 w/new Datadog documentation

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#52866]
### Info

- Jesse House (Platform Tech Team 2 Product Manager) came to our office hours on January 31

- His team is drafting new content to publish on the Platform website. The topic is related to Datadog.

- He will need our help to review their new documentation to make sure it gets deployed successfully and it follows all style guidelines.

- Information Architecture placement: He believes it might make sense to live under Developer Docs > Monitoring performance.

- Cross-linking opportunities: From "Request Access to Tools"

- Related GitHub ticket from Tech Team, just as an FYI for us: https://app.zenhub.com/workspaces/platform-tech-team-2-633efe4ca5a428e5294d7ade/issues/gh/department-of-veterans-affairs/va.gov-team/50774

- Estimated timeline: Jesse mentioned dropping new content in the Drafts section of Confluence starting Monday, February 6, but probably all of it by February 14.

- Goal is to have this live/published on the website by February 20-21

### Tasks

- [x] Review 4 new pages provided by Tech Team 2. Found here: https://vfs.atlassian.net/wiki/spaces/PWD/pages/2529591297/Monitor+Applications+and+Infrastructure+with+Datadog
- [x] Identify any styling launch-blocking issues and other recommendations
- [x] Clarify any questions with Jesse House as needed on this Slack thread: https://dsva.slack.com/archives/CL181NRJQ/p1676304349700119
- [x] Edit documentation as needed
- [x] When ready, place in the IA section of the Platform website recommended by Jesse. See Slack thread.
- [x] Prepare new pages to be deployed on Monday, February 20

**Comment by vbellissimo** [comment]
This task will have to be re-prioritized for next sprint. We're dependent on Tech Team 2 delivering the new documentation in need of editorial review.
