### ISSUE TITLE
Link research documentation on Getting Started

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#52862]
## User Story
As a new VFS team member, I be able to access and learn about research on VA.gov, so that I do not have to wait until a research orientation session to begin doing research.

Assignee: @allison0034 
Peer Reviewer: @CherylEvans 

## Description
During Platform Orientation research (#29671) we discovered that we should separate design and research orientation into 2 sessions as well as create an async option for sessions. Since separating design and research is not a quick fix and would require more intense planning and potentially several sprints of implementation work, we would like to introduce a simple solution until async is ready to be worked on. One thought is to link new team members from [Getting Started](https://depo-platform-documentation.scrollhelp.site/getting-started/welcome) to [Research and design](https://depo-platform-documentation.scrollhelp.site/research-design/).

## Impacted Artifacts
[Getting Started/Welcome](https://depo-platform-documentation.scrollhelp.site/getting-started/welcome) 
[GitHub template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/orientation-epic.md)

## Tasks
- [x] Add a research paragraph to the [Getting Started](https://depo-platform-documentation.scrollhelp.site/getting-started/welcome) and point them to [Research and design](https://depo-platform-documentation.scrollhelp.site/research-design/)
- [x] Review the [Platform Orientation Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team%2C+analytics-insights%2C+analytics-request&template=orientation-epic.md&title=Platform+Orientation+Template+%5BYour+name+here%5D) to see if anything needs to be added there. (potentially in the Design & Research section?)
- [x] Change GitHub template Designers & Researchers check list to
  - Review the Research and Design Guide on Platform Website
  - Learn how we do research at VA
  - Get oriented to the Design System
  - Get oriented to the Collaboration cycle
  - Attend Design and Research orientation session (schedule via Calendly)
  - Attend Accessibility orientation session (schedule via Calendly)

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] New VFS team researchers are introduced to Platform research guidance in the Platform Orientation process

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
@CherylEvans @naomimarcussen please review

**Comment by naomimarcussen** [comment]
This looks good! Here are a few thoughts:
- I suggest moving the **Research** paragraph above **Design**. 

- For the content, we'll want to update the second bullet since the Platform isn't doing research reviews anymore.

> You'll need reviews from the Platform team to help you make sure you're on track! [Here's what to expect, and how to request a midpoint review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)

You could say something like:
> You'll need to have your research plan reviewed before you recruit participants. [Here's how to request a research review.](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist#ResearchChecklist-2.Researchreview)

**Comment by naomimarcussen** [comment]
Here are a few notes on the [Platform Orientation Template:](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team%2C+analytics-insights%2C+analytics-request&template=orientation-epic.md&title=Platform+Orientation+Template+%5BYour+name+here%5D)

Review [Design & Research Onboarding Documentation](https://design.va.gov/about/designers)

- Since this section only talks about the Design System and not research, maybe change the text to this: 
Review [Design Onboarding Documentation](https://design.va.gov/about/designers)

Review the [Research and Design Guide](https://depo-platform-documentation.scrollhelp.site/research-design/index.html) on Platform Website

- Does it make sense to have this be first in the list?
- I updated [this page](https://vfs.atlassian.net/wiki/spaces/RD/overview) to highlight where to start (should be published at 3:00 on 2/8)

Attend Design orientation session ([schedule via Calendly](https://calendly.com/collaboration-cycle/design-orientation-for-va-gov-platform))

- Are we ready to drop the Research orientation? Do we want to call this the Design and Research Orientation?

--------------
My thoughts are to update from this:
- [ ] Review [Design & Research Onboarding Documentation](https://design.va.gov/about/designers)
- [ ] Review the [VA.gov Design System](https://design.va.gov/)
- [ ] Review the [Research and Design Guide](https://depo-platform-documentation.scrollhelp.site/research-design/index.html) on Platform Website
- [ ] Attend Design orientation session ([schedule via Calendly](https://calendly.com/collaboration-cycle/design-orientation-for-va-gov-platform))
- [ ] Attend Accessibility orientation session ([schedule via Calendly](https://calendly.com/collaboration-cycle/accessibility-orientation-for-va-gov-platform))

To possibly this:

- [ ] Review the [Research and Design Guide](https://depo-platform-documentation.scrollhelp.site/research-design/index.html) on Platform Website
- [ ] Learn how we do [research at VA](https://depo-platform-documentation.scrollhelp.site/research-design/research-at-va)
- [ ] Get [oriented to the Design System](https://design.va.gov/about/designers)
- [ ] Get [oriented to the Collaboration cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/)
- [ ] Attend Design and Research orientation session ([schedule via Calendly](https://calendly.com/collaboration-cycle/design-orientation-for-va-gov-platform))
- [ ] Attend Accessibility orientation session ([schedule via Calendly](https://calendly.com/collaboration-cycle/accessibility-orientation-for-va-gov-platform))

**Comment by CherylEvans** [comment]
@allison0034 Thanks, sounds good!

**Comment by allison0034** [comment]
@CherylEvans this is now ready for your review. Artifacts are linked.

**Comment by CherylEvans** [comment]
@allison0034 I think they restored the version before you made your changes.

**Comment by CherylEvans** [comment]
@allison0034 Cleared my cache and everything looks great.  Review is complete. :-)
