### ISSUE TITLE
Create DS demonstration application for USWDS v3-based Design System

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/va.gov-team#52870]
## Description
We need to create a set of demonstration pages for the following scenarios. These should be built in vets-website, though not deployed to production, in order to reproduce what VFS teams will need to do in order to configure their applications to use the new Design System. We should also document for VFS teams how they can achieve these build configurations in their own applications.

### A. MVP - Phase 1: Formation-sans Forms plus v3-based forms components

In this scenario the application is using form components that are USWDS v3-based, but otherwise uses our current web-components and a Formation build that removes form elements. This scenario represents the first step that a VFS team can take to adopt the USWDS v3-based Design System.

This **must** demonstrate:
* Form components that are based on USWDS v3. This may require additional styling that negates or overrides portions of Formation in order for v3-based form components to appear correctly.
* Base typographical elements (headers, paragraphs, lists, etc.) that use Formation.
* Color scheme coming from v3 but configured to match Formation for the form elements.

Form components (10) include the following:
* text-input
* radio-button
* select
* memorable-date
* checkbox
* textarea
* file input
* progress bar - segmented
* button
* button-pair

It **may** demonstrate:
* CSS-library - based on v3, namespaced to vads.

We should make the CSS-library determination as a team as it may allow VFS Teams to get a head start on phase 2, but is not a requirement to use the MVP. It's also my understanding that this is pretty much already done given that we're just namespacing the USWDS CSS library (though I haven't seen it in action).

### B. Phase 2: USWDS v3-based base design system + USWDS v3-based Form components & 5 most used web-components  + Minimal Formation

In this scenario the application looks like a USWDS v3-based application but may still be using some of our un-converted current web-components based on USWDS v1. However, at this phase the typography (headers, paragraphs, lists, etc.), colors, grid, etc. of the base v3-based design system have been adopted.

This **must** demonstrate:
* Form components (10) that are based on USWDS v3
* Top 5 most used web-components converted to v3 (alert, telephone, loading indicator, additional-info, accordion)
* Base typographical elements (headers, paragraphs, lists, etc.) from our base USWDS v3-based package
* Color scheme coming from v3
* CSS-library - based on v3, namespaced to vads
* Any bits of Formation that teams still need, or a way to get to them, that are not included above.

### C. End goal: USWDS v3-based base design system + USWDS v3-based components built to-date

In this scenario the application is free of Formation and only loads the latest and greatest design system based on USWDS v3. This is our eventual end-goal. 

This **must** demonstrate:
* Base typographical elements (headers, paragraphs, lists, etc.) from our base USWDS v3-based package
* Color scheme coming from v3
* CSS-library - based on v3, namespaced to vads
* All v3-based components that we've built to-date (and keep that updated)

## Acceptance Criteria
- [ ] The Design System Team has the ability to demonstrate a page or pages that show the scenarios listed above with the MUST requirements met.
- [ ] The Design System Team can see the current state of their work on enabling VFS Teams to adopt a USWDS v3-based Design System across the 3 scenarios.
- [ ] VFS Teams can read documentation on how to migrate their application to at least the MVP - Phase 1.

**Comment by caw310** [comment]
Closing epic as we have moved onto phase 2.
