### ISSUE TITLE
Add unique label to Platform Orientation template(s)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#52884]
## User Story
As a Platform team member supporting Platform Orientation, I want the Platform Orientation template and New VFS team template to have unique labels so that they are easy to find, sort, filter and ultimately make it easier to take action.

Assignee: @sterkenburgsara 
Peer Reviewer: @it-harrison 

## Description
In the Platform Orientation discovery research (#29671), one of the findings was that it would be beneficial and valuable for Platform if the Platform Orientation template and New VFS team template had unique labels so that they are easy to locate and allow for Platform to take action. The purpose of this ticket is to add a unique label to those templates.

## Impacted Artifacts
[Platform Orientation template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=analytics-insights%2C+analytics-request%2C+governance-team&template=orientation-epic.md&title=Platform+Orientation+Template+%5BYour+name+here%5D)
[New VFS team template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=analytics-insights%2C+governance-team&template=new-vfs-team.md&title=New+VFS+Team+%5BInsert+team+name+here%5D)
Links on [Guidance for new teams and team members](https://depo-platform-documentation.scrollhelp.site/getting-started/guidance-for-new-teams-and-team-members) PW page

## Tasks
- [x] Create the new label `Platform-Orientation`
- [x] Add the new label to the Platform Orientation template
- [x] Add the new label to the New VFS Team template
- [x] Update both links on the PW page so that the new label is populated when the template opens

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The Platform Orientation templates completed by VFS teams contain a unique label

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by sterkenburgsara** [comment]
@shiragoodman I can't find the master template for orientation to edit. Can you help?

**Comment by shiragoodman** [comment]
@sterkenburgsara yup![ This is where](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/.github/ISSUE_TEMPLATE) all issue templates for the va.gov-team repo are stored. The Platform Orientation template (for individuals) is called orientation epic, and the New VFS Team template (for teams) is called new-vfs-team . Let me know if you still have trouble locating.

**Comment by shiragoodman** [comment]
@it-harrison should be able to help too, since he's your peer reviewer :)

**Comment by sterkenburgsara** [comment]
@shiragoodman Aha - I didn't know the filenames were different. Thanks for the help!

**Comment by sterkenburgsara** [comment]
@it-harrison do you know how to add labels here? the templates are .md files, not issue tickets. I am confused.

**Comment by it-harrison** [comment]
@sterkenburgsara I think the idea is to create a [new label](https://github.com/department-of-veterans-affairs/va.gov-team/issues/labels) and then add it to the respective template manually:
<img width="1321" alt="Screenshot 2023-02-21 at 12 54 02 PM" src="https://user-images.githubusercontent.com/8867779/220434080-636f409f-a194-456b-9f63-bf3d45051758.png">

**Comment by sterkenburgsara** [comment]
@it-harrison oh wow, not what I thought when I read through this. @shiragoodman - Is what Ian said above the expectation? Do you want me to go back to all past templates and add this label? Thanks all!

**Comment by it-harrison** [comment]
@sterkenburgsara you don't have to update all the old tickets (it's not in the tasks) just the templates so shouldn't be too bad

**Comment by shiragoodman** [comment]
we want the template to auto populate when the VFS team member opens a new ticket. so yes, manually add it but you have to add it to the .md file

**Comment by sterkenburgsara** [comment]
@it-harrison I see where to add the labels, but my commits are not merging and I'm not sure why. Can we sync on this tomorrow? I'll set up a time. // cc @shiragoodman

**Comment by sterkenburgsara** [comment]
@it-harrison links have updated to Platform Website and should now be correct. Can you peer review and let me know if you find any errors? Thanks!

**Comment by it-harrison** [comment]
@sterkenburgsara looks good!
