### ISSUE TITLE
Update Welcome Kit page with new PDFs

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#52889]
## Issue Description

Justin Hoffman asked us to update the [Welcome Kit](https://www.va.gov/welcome-kit/) page with new PDFs that he's uploaded into Drupal. 

There are 19 PDFs. 18 of them will replace PDFs that are already on the page and 1 will require a new link. The new one is the Pension Benefits PDF. 

## Tasks
- [x] Update PDFs on page (Randi)
- [x] Add new PDF link (Randi)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Welcome Kit has newest PDFs live on the site

**Comment by RLHecht** [comment]
I uploaded all of these new PDFs and added in the new pension quick start guide. I put it under disability in the list since we often say "disability compensation, pension, education..." @megzehn This is ready for you to copyedit.

**Comment by megzehn** [comment]
That placement looks good to me. I reviewed the links and published this page. Thank you so much, @RLHecht!!

**Comment by RLHecht** [comment]
Changes are live. Closing ticket!

**Comment by coforma-terry** [comment]
Test comment
