### ISSUE TITLE
[FE] Run Test Cases for Functional Testing

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#52907]
## Description
As a team, we need to perform functional testing so that we can ensure our feature is ready for release. 

## Tasks
- [ ] Run these test cases
    - [ ] [Pre-Check-in](https://dsvavsp.testrail.io/index.php?/runs/view/4462)
    - [ ] [Check-in](https://dsvavsp.testrail.io/index.php?/runs/view/4463)

**Comment by brianseek** [comment]
We ran test rail in a sync and added one comment but otherwise passed

**Comment by loripusey** [comment]
are there any tickets that need to be created @brianseek ?
