### ISSUE TITLE
[PRODUCT] Run Test Cases for Functional Testing

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#52905]
## Description
As a team, we need to perform functional testing so that we can ensure our feature is ready for release. 

## Tasks
- [x] Run these test cases
    - [x] [Pre-Check-in](https://dsvavsp.testrail.io/index.php?/runs/view/4449)
    - [x] [Check-in](https://dsvavsp.testrail.io/index.php?/runs/view/4450)

**Comment by loripusey** [comment]
Done and all TestRail test cases passed
