### ISSUE TITLE
Run Test Cases for Functional Testing

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#52906]
## Description
As a team, we need to perform functional testing so that we can ensure our feature is ready for release. 

## Tasks
- [x] Run these test cases
    - [x] [Pre-Check-in](https://dsvavsp.testrail.io/index.php?/runs/view/4460)
    - [x] [Check-in](https://dsvavsp.testrail.io/index.php?/runs/view/4461)

**Comment by kellysmith1008** [comment]
Blocked waiting for feature flag to be flipped in staging. Will pick up another ticket in the meantime and put this back in our queue

**Comment by kellysmith1008** [comment]
[Content/UX] Pre-check-in test failed. Mostly updating text and icons to resolve. Pictures included in test rail comments.

**Comment by loripusey** [comment]
@kellysmith1008 can you create bug tickets and attach to this Epic for the issues you found? Also, please review the bugs that @benbrasso-agile6 already logged so that we don't duplicate. Thanks.

**Comment by kellysmith1008** [comment]
Check-in failed with similar issues. Putting in validate for @loripusey to take a look

**Comment by kellysmith1008** [comment]
@loripusey Whoops - I just saw your response above. Yes ma'am, I'll review Ben's tickets and create any new ones as needed.

**Comment by kellysmith1008** [comment]
- [Add time zone](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/53971)
- [Back to appointments](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/53973)
- [Update Need help section](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/53979)
- [Flipped phone icon](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/53981)

**Comment by loripusey** [comment]
Changed 1, 2, and 4 to design debt ticket and pulled all into sprint goals for planning consideration
closing
