### ISSUE TITLE
[FE] Perform Accessibility Testing and Create Artifact

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#52908]
## Description
As a team, we need to perform accessibility testing so that we can ensure our feature is ready for release. 

## Tasks
- [ ] Create an accessibility ticket/artifact using this [template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D)
- [ ] Add the HCE-Checkin label to the accessibility ticket
- [ ] Associate the accessibility ticket with the appropriate feature Epic
- [ ] Attach the accessibility ticket to the collab cycle ticket for the feature Epic
- [ ] Complete & check-off each test in the ticket

**Comment by loripusey** [comment]
@loripusey add link to John's example ticket

**Comment by wullaski** [comment]
@loripusey Here's the completed artifact https://github.com/department-of-veterans-affairs/va.gov-team/issues/53857

**Comment by benbrasso-agile6** [comment]
thanks
