### ISSUE TITLE
Create list of upstream endpoints to test for each service

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#52921]
## Issue Description
In order to create Synthetic Tests for the upstream services vets-api consumes, we need a list of endpoints that vets-api hits.

---
## Tasks
- [ ] Create list of upstream external endpoints to test for each service 

## Acceptance Criteria
- [ ] The list of upstream external endpoints to test for each service is complete
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by holdenhinkle** [comment]
Google spreadsheet - https://docs.google.com/spreadsheets/d/1T0pVr4urfR-e4NHh2x_UWcPu53-0gm4fxehMDvX0Jig/edit#gid=1759090874

Included notes what [external services map to that master services list](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1889599494/External+Service+Integrations) and whether or not endpoint information exists for those services.

**Comment by npeterson54** [comment]
Not moving to the next sprint due to some changes in priority

**Comment by npeterson54** [comment]
Removing tech team 3 label from story as we will not be working on this

**Comment by rjain21** [comment]
Adding to Watchtower SRE Program board

**Comment by rjain21** [comment]
Old Issue. Not relevant anymore
