### ISSUE TITLE
MDT- Reivew Page- Review order page - default, v1

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5292]
## User Story:
As a veteran, I need to be able to confirm my order before I submit the order so that I have peace of mind.

## Tasks
- Create high fidelity mockups for editing selected products from the review order page
- Upload to Invision with a comment to highlight initial focus state

## Acceptance Criteria:
- [ ] Mockup aligns with VA.gov’s design system
- [ ] Include a way for Veterans to change their selected product(s) 
- [ ] Initial focus point documented in Invision
- [ ] Sketch artboards are uploaded to Invision and linked in this ticket as a comment

**Comment by rebeccawalsh** [comment]
**Invision Prototype:** Default [(Desktop)](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/407932002_C3-_Review) 


Github documentation: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-review.md#use-case---review-default
