### ISSUE TITLE
Create synthetic tests in DataDag for the upstream services that vets-api consumes

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#52922]
## Issue Description
In order to monitor the health of the external services vets-api consumes, we need to create synthetic tests in DataDog for each endpoint vets-api hits.

---
## Tasks
- [ ] Create synthetic tests for each external service endpoint that vets-api hits

## Acceptance Criteria
- [ ] Synthetic tests for each external service endpoint have been created and are up and running
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by holdenhinkle** [comment]
Link to doc with list of links to docs about external service endpoints - https://app.zenhub.com/workspaces/platform-tech-team-3-6335ab9b1901b99243ce7601/issues/gh/department-of-veterans-affairs/va.gov-team/52921

**Comment by npeterson54** [comment]
Not moving to the next sprint due to some changes in priority

**Comment by npeterson54** [comment]
Not moving to the next sprint due to some changes in priority

**Comment by npeterson54** [comment]
Removing tech team 3 label from story as we will not be working on this
