### ISSUE TITLE
Planning: Create and ADR to update Common::Client::Base to use the HTTP gem (AKA http.rb) and the Faraday HTTP adapter

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#52930]
## Issue Description
In order to successfully update `Common::Client::Base` to use the HTTP gem, it's wise to create an ADR to do so and have Backend CoP members review it.

---
## Tasks
- [ ] Research what changes will need to be made to vets-api
- [ ] Create ADR
- [ ] Get feedback from BE CoP members
- [ ] Finalize ADR 

## Acceptance Criteria
- [ ] ADR has been created, reviewed and finalized
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by npeterson54** [comment]
Removing tech team 3 label from story as we will not be working on this
