### ISSUE TITLE
Verify debts controller endpoints in EKS

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#52938]
## Issue Description
As part of our migration to EKS we need to [validate ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52261)that the endpoints owned by our team work as intended with the new infrastructure. Some instructions can be found [here](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2485518367/EKS+Endpoint+Testing).

---
## Tasks
- [x] Create endpoint collection
- [x] Add requests to collection
- [x] Use variables for secretes
- [x] Run tests

## Acceptance Criteria
- [x] We've validated the tests against our endpoints in EKS
- [ ] Communicate results with platform devops team - associated ticket [#52710](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52710) Please communicate updates to Lainey. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
Feb 7 - This has been pushed back due to the priority of #53262.
