### ISSUE TITLE
BE | Profile | Feature Flag Removal Issue

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#52944]
## Background

The following flags have been removed from features.yml (along with any code references)...
- [x] profile_show_receive_text_notifications
- [x] profile_notification_settings
- [x] profile_show_bad_address_indicator
- [x] profile_force_bad_address_indicator

These flags (listed at https://api.va.gov/flipper/features/ ) don't show up in staging, but still show up in production with an empty description. 

A Platform support ticket has been opened: https://dsva.slack.com/archives/CBU0KDSB1/p1674143804622079

Context from the support ticket:
Ray Messina "I looked into this issue, and found that the flags are automatically removed if ALL  the code  referencing them has been removed,  but that it can take a couple of day for this process to show up in the dash. As it has been a day  since  this issue was posted, if the  flags still remain in the dash, i would recommend a repo wide text search for the remaining flags to see if something may have been overlooked."

## Tasks
- [ ] search the repo to see if we can locate any flags are still lingering out there somewhere 
- [ ] Conduct Unit tests 
- [ ] Run E2E tests covering current code and regression
- [ ] Notify PM if this needs to be deployed to Staging behind feature flag
  

## Acceptance Criteria
- [x] Flags are removed (don't show up in production env)
