### ISSUE TITLE
MDT- Review order page - edit selected products, v1

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5294]
As a veteran, I need be able to change my selected items if I have made an ordering error so that I can make corrections before submitting my order 

## Tasks
- Create high fidelity mockups for editing selected products from the review order page
- Upload to Invision with a comment to highlight initial focus state

## Acceptance Criteria:
- [ ] Mockup aligns with VA.gov’s design system
- [ ] Include a way for Veterans to change their selected product(s) 
- [ ] Initial focus point documented in Invision
- [ ] Sketch artboards are uploaded to Invision and linked in this ticket as a comment

## Dep/Blockers

**Comment by rebeccawalsh** [comment]
**Invision Prototype:** Edit product selections [(Desktop)](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/407932001_C3-_Review_-_Edit)

Github documentation: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-review.md#use-case---review-edit-product-selections
