### ISSUE TITLE
Create master list of all services used on platform and transfer ownership to new accounts email if possible.

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#52956]
## Issue Description
Create master list of all services used on platform and transfer ownership to new accounts email if possible.

---
## Tasks
- [x] List all services on platform
- [x] Find out who created the account and list their name and contact info
- [ ] Create a general 'accounts' email that is owned by the VA or Oddball
- [ ] If possible, transfer all services to the new account
- [ ] Setup automatic email forwarding to admins
- [ ] Optional: Create a Slack notification that's fired each time a new email hits the account

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by rjohnson2011** [comment]
Currently researching and consolidating a list of services on the platform. Following that will begin discovery into the best point of contact for each service.

**Comment by laineymajor** [comment]
@rjohnson2011 I think I can find a list with some (likely) contacts...I'll send to you and you can link if appropriate

**Comment by rjohnson2011** [comment]
Spoke with @pjhill about incorporating services into the existing [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory). Peter confirmed the Product Directory is still active and being maintained and welcomes the addition of services, keeping the Product Directory as a single source of truth as much as possible.

Will plan on using [the following link ](https://github.com/department-of-veterans-affairs/product-directory/issues/new?assignees=cbonade&labels=form-submitted-update&template=update-product-request.yml&title=Product+Directory+Change+Request+for+%5BProduct+Name%5D)to update the Product Directory with services.

**Comment by rjohnson2011** [comment]
Looking through the `vets-api` repo for services then cross-checking with those that are not currently reflected on Product Directory. Currently compiling a list that will be posted.

**Comment by rjohnson2011** [comment]
Created the following compilation list of services used with the `vets-api` Github repository: https://vfs.atlassian.net/wiki/spaces/~527721881/pages/2605482200/VA+Services+Compilation

Currently searching for further references to services not located within the `vets-api` repo through various support documentation and prior Slack threads. After this, locating point of contact information for each indicated service.

**Comment by laineymajor** [comment]
Thanks Ryan!

**Comment by rjohnson2011** [comment]
Located these resources regarding external / upstream services:

https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885601877/Partner+Services+Upstream+Services
https://vfs.atlassian.net/wiki/spaces/pilot/pages/640909834/External+Integrations
https://vfs.atlassian.net/wiki/spaces/pilot/pages/1889599494/External+Service+Integrations

Currently going through these to add to the master service list.

**Comment by rjohnson2011** [comment]
Here is a master list of all services at VA. Spoke with @holdenhinkle this morning regarding the difficulty in transferring ownership of services from a variety of companies (Oddball, Adhoc, Coforma, Agile6, VA, BAH, etc) under one unified account. The intention of the ticket in response to a service malfunctioning and not being able to locate the correct contact info, so this resolves that pain point.
https://docs.google.com/spreadsheets/d/1mfh4BWAnpdMnIqMWigugzBFfKQurGwOXGzZplIQ2VUU/edit#gid=0
