### ISSUE TITLE
Login.gov adoption team: Sprint 13 (2/2 - 2/15)

### ISSUE THREAD

**Issue by elizabethkochBT** [department-of-veterans-affairs/va.gov-team#52958]
## PTO

- Elizabeth OOO: 2/14
- Tyler OOO: February 13-15th
- Carolyn OOO 2/9–2/13

## Sprint 13 Priorities

Legacy Credential Migration:
- Migration dashboard
- Plan organic Login.gov adoption experiment
- Create a working prototype of grandfathering user flow in Sketch including content
- Key collaboration cycle touch points
 
## Retro Board

[Sprint 12 Retro](https://easyretro.io/publicboard/NLK9KWMAtKc2MQwDfo9HXLZGTww1/b3565655-6ea8-42ba-ac0d-5104bc4d1ef5)

### Discussion Topics/Retro Action Items
 - [x] Put stuff in the right place, Anthony, COME ON MAN
 - [x] Add a calendar reminder to update tickets before sprint planning.
 - [x] Everyone update your tickets regularly throughout the sprint please!
 - [x] Tyler reach out to Surge and Core teams to set up an intro with their researchers.
 - [x] Ask for agendas for upcoming stakeholder meetings.
 - [x] In standup, we'll check who needs to be at which meetings and rely on representatives.
 - [x] Steve to set up pair development for engineering tasks. Let's drive this! (And keep Trevor in the loop).
 - [x] Discuss dashboard in sprint planning.

### Legacy credential migrations & Login.gov proactive adoption
 - [x] Mapping of MHV premium and DS Logon to NIST 800-63 #52970
 - [x] Front end development of grandfather flows #52984
 - [x] Create research plan and conversation guide for 1st round of testing the grandfathering flow #52747
 - [x] Create tactical plan to test organic Login.gov account creation with a limited number of users #52638
 - [x] Draft grandfathering user flow in Sketch #52734
 - [x] Reviewing back end api #52987
 - [x] Make Design Intent request for grandfathering user flow #52737

## Collab Cycle Tasks 
- [x] [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent)
- [x] [Sitewide content and IA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-Content-and-IA-intake-request.2124906551.html)
