### ISSUE TITLE
MDT- Order confirmation - default state, v1

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5295]
## User Story:
As a veteran, I need to be able to see the next steps and print off a receipt so that I can have some documentation of the order if needed.

## Tasks
- Create a high fidelity mockup of the order confirmation page
- Upload to Invision with a comment to highlight initial focus state

## Acceptance Criteria:
- [x] Mockup aligns with VA.gov’s design system
- [x] Includes information on what the Veteran can expect next
- [x] Includes information on what the Veteran can do in the meantime
- [x] Initial focus point documented in Invision
- [x] Sketch artboards are uploaded to Invision and linked in this ticket as a comment

## Next Steps
- design review

**Comment by rileyorr** [comment]
[Desktop](https://vsateams.invisionapp.com/share/MYVTQ79UGNP) | [Mobile](https://vsateams.invisionapp.com/share/NCVTQ81RDH7)

**Comment by rileyorr** [comment]
@mojaray2k Here is the _Order confirmation_ screen mockup. Let me know if you have any questions!
