### ISSUE TITLE
[FE] 10-10EZ - Household optimization: Update Household pages with new content and design changes

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#52960]
# Background
As a result of our [December 2022 Research sessions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2022-10-Household%20Information%20Section/Research%20Findings.md#recommendations) and Design office hours feedback, we have made the decision to move forward with updating the Household section of the 10-10EZ.

Designers: Nick Osmanski & Jessica Stump

### Resources
- [Sketch File](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/208CCE1E-DC03-457F-B2FA-1232663983CF/canvas)
- [Updated household wireflow](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/nR0pl7W)
- [Research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2022-10-Household%20Information%20Section/Research%20Findings.md#recommendations)
- [Initiative Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Household%20section%20redesign/ReadMe.md)

# Outline of changes to be made:

*Note for the following updates: content changes presented here represent the design team's updates, with only some Content team review. There will likely be more complete Content team reviews in the near future, but the general structure, order, and components on the following pages should remain (mostly) the same.*

(*The gray/orange dots in screenshots are just comment icons from the Sketch for teams site*)

### Marital status expandable info

[Marital status, open info](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/zxdZeEe)

- Small update to the marital status info: removing *"We'll ask about your income"*, and making content one paragraph.
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/81988788/217847887-88ab0497-1200-442a-a9c9-1998691f5083.png">

### Household section onboarding

[Financial onboarding page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/ygvYdEq)

- The household section onboarding page has updated content. The alert, yes/no question, and bulleted list have been moved to another page.

**Content**

- [Body] Next we’ll ask about your household finances. We’ll ask about income and expenses for you, your spouse (if you’re married), and any dependents you may have.
- [H3] How we use your financial information
- [Body] When you provide your financial information from the most recent tax year, we will verify this information with the IRS. We use this information to determine these factors:
     - If you’re eligible for VA health care based on your income
     - If you’re eligible for travel pay reimbursement
     - If you’ll need to pay a copay for care or prescription medicines
 - [H3] The financial information you will need
 - [Body] You will need the following information to fill out this part of the application:
      - **Last year’s gross and net household income for you, your spouse, and your dependents.** This includes income from a job and any other sources. Gross income is your income before taxes and any other deductions. Net income is your income after taxes and deductions.
      - **Your deductible expenses for last year.** These include certain health care and education costs. These expenses will lower the amount of money we count as your income.

<img width="977" alt="image" src="https://user-images.githubusercontent.com/81988788/217644223-9e6b4c0d-cc78-41ff-a31e-846054c66077.png">

### Annual Income

[Veteran annual income page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/L0yqdk5)

- The annual income page is now only for the Veteran (separate pages for spouse and dependent income are outlined in "pages/questions splitting up" section.)
- Bold financial definitions are now included as sub-labels associated with each field

**Content - Veteran annual income page**

- [H3] Your annual income
- [Label 1] Gross annual income from employment
- [Gross income sub-label] Gross income is your income before any taxes, and other deductions are subtracted. This includes any employment wages, bonuses, severance pay, and tips. Include your dependent’s income if it could have been used to pay household expenses. 
- [Label 2] Net annual income from your farm, property, or business
- [Net income sub-label] Net income is your income after any taxes and other deductions are subtracted.
- [Label 3] Other income
- [Other income sub-label] This includes any income from Social Security, unemployment, retirement and pension, compensation benefits such as VA disability, and any interest or dividends including, tax-exempt earnings from Individual Retirement Accounts (IRAs) or annuities. 

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/81988788/218217517-687043bd-9248-4fc7-9605-a3e7d3d989e8.png">

### Deductible expenses education field

[Deductible expenses page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/zWZ5Z4/a/8yKwlVO)

- Removed "Do not list..." sentence from education field label. Added new sub-label.

**Content**

- [Sub-label] This includes tuition, books, fees, and course materials.

<img width="847" alt="image" src="https://user-images.githubusercontent.com/81988788/218485964-87d5fd88-28c4-446b-b850-ab19cbc4ca67.png">

### Financial Disclosure - onboarding

[Financial yes/no page - closed](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/paPybK0)
[Financial yes/no page - open](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/lYO5MO/a/Omgq0Kq)

- The alert and yes/no question are now together on a separate page. The bulleted list of qualifying eligibility factors are now included in a new expandable info component within the alert (see components section).
- Small content update in alert: replaced "--" with ",".
<img width="516" alt="image" src="https://user-images.githubusercontent.com/81988788/218201664-cc2c0a4e-03fa-44e1-94a5-46a6b690ba57.png">

### Spouse yes/no questions on separate pages

[Page 1 - spouse live with you / address page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/lYO5MO/a/9Pzj9AP)
[Page 2 - spouse support yes/no page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/lYO5MO/a/AxmGM4m)

- The yes/no radio button questions are now on their own separate pages.

**Content - page 1**
- [H3] Spouse’s additional information
- [Body] Fill this out to the best of your knowledge. The more accurate your responses, the faster we can process your application.

**Content - page 2**
- [H3] Spouse’s financial support

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/81988788/217934006-eac879ef-73ea-498b-abfc-0065e7b13c89.png">

### Spouse address/phone number

[Spouse address/phone page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/lYO5MO/a/g0eDkkx)

- Spouse address/phone number info now appears on a separate page. It appears conditionally with the "no" response to "Do you have the same address as your spouse?" question.
<img width="799" alt="image" src="https://user-images.githubusercontent.com/81988788/217931022-e6459e89-8e29-4921-bac8-3cb7fe087fc4.png">

### Dependent info

[Dependent information fields - page 1](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/qW07Md/a/1Kd3avO)
[Dependent yes/no questions and education expenses field - page 2](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/qW07Md/a/jgwqgl7)
[Dependent support question - page 3](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/qW07Md/a/DPgxQm2)

- After answering "yes" to dependent question, dependent information fields and yes/no questions are now on separate pages. Subsequent dependents use the same pattern of multiple pages.
- "Add another dependent" button is removed.
- Dependent support question appears conditionally with a "no" response to "Did your dependent live with you last year?"
- New cancel button & cancel modal (see new components section).

**Content - dependent's information page**
- [H3] Dependent's information

**Content - dependent's additional information page**
- [H3] [Dependent's name]'s additional information

**Content - dependent's support page**
- [H3] [Dependent's name]'s support
- [Label] If your dependent didn’t live with you last year, did you provide support?
- [Sub-label] Please count all support contributions even if they weren’t paid in regular and set amounts. Support can include tuition or medical bill payments.

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/81988788/218191940-e1ff62ab-d47a-4dfc-a2ac-12163edfe43f.png">

### Annual Income

[Veteran income page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/lYO5MO/a/L0yqdk5)
[Spouse income page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/lYO5MO/a/ygRLq0E)
[Dependent income page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/lYO5MO/a/DP7M5Rn)

- Veteran annual income, spouse annual income, and dependent(s) annual income are now listed on separate pages. 
- Each dependent has it's own sequential income page (Dependent 1 annual income, Dependent 2 annual income, etc.)

**Content - spouse annual income page**

- [H3] Spouse’s annual income
- [Label 1] Spouse’s gross annual income from employment
- [Gross income sub-label] Gross income is income before any taxes, and other deductions are subtracted. This includes any employment wages, bonuses, and tips.
- [Label 2] Spouse’s net annual income from a farm, property, or business
- [Net income sub-label] Net income is income after any taxes and other deductions are subtracted.
- [Label 3] Spouse's other income
- [Other income sub-label] This includes any income from Social Security, unemployment, retirement and pension, compensation benefits such as VA disability, and any interest or dividends including, tax-exempt earnings from Individual Retirement Accounts (IRAs) or annuities. 

**Content - dependent annual income page(s)**

- [H3] [Dependent's name]'s annual income
- [Label 1] Dependent’s gross annual income from employment
- [Gross income sub-label] Gross income is income before any taxes, and other deductions are subtracted. This includes any employment wages, bonuses, and tips.
- [Label 2] Dependent’s net annual income from a farm, property, or business
- [Net income sub-label] Net income is income after any taxes and other deductions are subtracted.
- [Label 3] Dependent's other income
- [Other income sub-label] This includes any income from Social Security, unemployment, retirement and pension, compensation benefits such as VA disability, and any interest or dividends including, tax-exempt earnings from Individual Retirement Accounts (IRAs) or annuities.

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/81988788/217935761-84233e89-a5cd-407f-86d3-5c81f7bc0c19.png">

### Financial disclosure alert expandable info

[Financial yes/no page - open](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/lYO5MO/a/Omgq0Kq)

- The new expandable info component in the alert contains the bulleted list of qualifying eligibility factors.

<img width="619" alt="image" src="https://user-images.githubusercontent.com/81988788/218186084-7df85372-d2f7-4739-a0f5-bd9e3b431063.png">

### Eligibility alert

[Eligibility alert visible](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/n9w5rl/a/8y8PDoq)

- Answering "no" to the financial disclosure yes/no question now displays a background color only alert with an icon. 

**Content**

- [Body] If you don’t provide your financial information and you don’t have another qualifying eligibility factor, VA can’t enroll you.

<img width="942" alt="image" src="https://user-images.githubusercontent.com/81988788/217849367-5c0c11ba-17d1-4187-b9e3-4bf03699c508.png">

### Dependents expandable info component

[Dependent expandable info - open](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/kaJ9m2R)

- The dependent question has a new expandable info component with information on who VA considers a dependent

**Content**
- [Body] **A dependent is:**
     - A spouse (we recognize same-sex and common law marriages)
     - A parent, if you’re directly caring for them and their income and net worth are below a certain amount
     - An unmarried child (including an adopted child or stepchild) who meets one of the 	eligibility requirements listed below
 - [Body] **To be considered a dependent, one of these must be true of an unmarried child:**
     - They're under 18 years old, **or**
     - They're between the ages of 18 and 23 years old and enrolled in school full time, **or**
     - They became permanently disabled before they turned 18

<img width="849" alt="image" src="https://user-images.githubusercontent.com/81988788/218188455-adc7b8b6-5f15-4b22-b754-5c4a723ead60.png">

### Dependent cancel button & confirmation modal

[Dependent information fields - page 1](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/qW07Md/a/1Kd3avO)
[Dependent yes/no questions and education expenses field - page 2](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/qW07Md/a/jgwqgl7)
[Dependent support question - page 3](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/qW07Md/a/DPgxQm2)
[Cancel modal](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/09wJL2j)

- Dependent information fields and yes/no question pages each have a new cancel button, and each cancel button triggers the cancel confirmation modal.

**Content - cancel button**

- [Secondary button] Cancel editing this dependent

**Content - cancel modal**

- [H3] Are you sure you want to cancel editing this dependent?
     - [Body] This will stop editing the dependent. You will return to a list of any previously added dependents and your edits will not be applied.
     - [Primary button] Yes, cancel editing this dependent
     - [Secondary button] No, continue
     - Close button now includes "CLOSE" text

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/81988788/219137697-7e5580e9-9d43-4aeb-a7b7-7f456f14bfbe.png">

### List and Loop dependent card

[Dependent list and loop card list](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/4a1LYqx)
[Button interaction style](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/8yLW1m3)

- Adding a dependent creates a new list and loop card component; additional dependents adds more cards to the list.
- Each card has the first/last name of the dependent.
- The "edit" link takes users back through the dependent information flow.
- The "remove" button triggers the remove dependent confirmation modal.
- "Delete" button interaction (hover, focus, etc.) uses "default" styling (see [button interaction style](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/8yLW1m3) Sketch link)

<img width="587" alt="image" src="https://user-images.githubusercontent.com/81988788/219135898-35862d07-7aed-4be3-a867-27ee3cdcdbcf.png">

### "Remove dependent" confirmation modal

[Remove dependent modal](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/m145KEg)

- Clicking "remove" button triggers the remove confirmation modal.

**Content - "remove" modal**

- [H3] Are you sure you want to remove this dependent?
- [Body] This will remove **[First Last]** and all their information from your list of dependents.
- [Primary button] Yes, remove this dependent
- [Secondary button] No, cancel
- Close button now includes "CLOSE" text

<img width="506" alt="image" src="https://user-images.githubusercontent.com/81988788/219139597-ae8a1e46-6965-40d7-9de9-89ef861c61b6.png">

### Deductible alert

[Deductible expenses page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/8yKwlVO)

- Removed "Tell us a bit..." sentence.
- The deductible expenses page now uses an alert instead of an expandable info component.

**Content - deductible alert**

- [Body] **Note:** We understand in some cases your expenses might be higher than your income. If your expenses exceed your income, we’ll adjust them to be equal to your income. This won’t affect your application or benefits.

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/81988788/217653206-f6ce463d-bca0-41d3-a763-2ade40c69603.png">

## Tasks
- [ ] Update the pages within the Household section as indicated in the outline above
     - Work with Nick & Jessica on questions and decisions
- [ ] Ensure all changes align with accessibility guidelines
- [ ] Create feature flag

## Acceptance Criteria
- The Household section of the 10-10EZ will be updated as per design, and ready for testing

**Comment by nicko-amida** [comment]
@longmd Slight update to page headings: now using H3 not H5 (updated above)!

**Comment by nicko-amida** [comment]
@longmd The new component for the list and loop dependent card has been updated according to yesterday's [convo with the design team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52965#issuecomment-1430405486). Card style and button interaction style are linked above!

**Comment by longmd** [comment]
@jessicastump , one piece that has become unclear for me here is related to dependents income. I see we have the line item for expenses on the dependents add/edit page, but then we have the dependent's income page after spousal income. 

Is that dependents income page supposed to be gross for all dependents (i.e. if I have 3 dependents, am I supposed to add up all 3 and put them on that page?) 

OR 

Do we need to move that dependent income page into the add/edit bit for dependents?

**Comment by jessicastump** [comment]
The [current wireflow](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/nR0pl7W) was for the spouse and dependent income pages to show up after the Veteran's income page, conditionally for if any were added during those earlier spouse/dependent question flows.

**Comment by longmd** [comment]
@jessicastump , as we discussed on the call ... talked about asking a question in the dependent declaration of if they have any income to declare, if no, we send zeros (0s) for all the fields, otherwise they can get an additional page that allows them to declare that income. Spousal income will stay where it is at in the current flow.

**Comment by jessicastump** [comment]
@longmd - working through these changes, here is an [updated wireflow](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/xrqWbp0) for the dependents section with the additional conditionals around age and income. 
@hdjustice - do you know if reporting educational expenses is only needed if a dependent falls into the 18-23 age range or could educational expenses apply to younger dependents, spouses or dependent parents as well?

**Comment by jessicastump** [comment]
For the remove buttons on the dependent cards - [this is what was provided](https://www.sketch.com/s/be292806-8dbf-4201-bfa7-0edbba103347) from the Platform/design system for guidance and includes all the button states needed.

**Comment by hdjustice** [comment]
> do you know if reporting educational expenses is only needed if a dependent falls into the 18-23 age range or could educational expenses apply to younger dependents, spouses or dependent parents as well?

Good question, I will confirm with HEC

**Comment by hdjustice** [comment]
@jessicastump You may have seen the response from the business, but I will also include here:

> Unreimbursed educational expenses are allowable only for Veterans, surviving spouses and their dependent children (max age 23) seeking (post high school) educational degrees or training certification.

<details>
<summary>Full response with references</summary>
<html>
<body>
<p class="m_1169092326150772281xmsonormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><b><span style="font-size: 16pt;">Response<span style="color: rgb(0, 32, 96);">:</span></span></b><span style="font-size: 16pt; color: rgb(0, 32, 96);">  Unreimbursed educational expenses are allowable only for Veterans, surviving spouses and their dependent children (max age 23) seeking (post high school) educational degrees or training certification.</span><span style="font-size: 16pt;"><u></u><u></u></span></p><p class="m_1169092326150772281xmsonormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size: 20pt;">M21-1, Part IX, Subpart i, Chapter 3, Section D – Reduction of Income Due to Unreimbursed Expenses</span><span style="font-size: 16pt;"><u></u><u></u></span></p><p class="m_1169092326150772281xmsonormal" style="margin: 0in 0in 7.5pt; font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><b><span style="font-size: 14pt; font-family: Arial, sans-serif;">IX.i.3.D.4.c<span style="color: blue;">.</span>  Applicability of the Educational Expense Deduction to Children</span></b><span style="font-size: 16pt;"><u></u><u></u></span></p><p class="m_1169092326150772281xmsonormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size: 14pt; font-family: Arial, sans-serif;">The educational expense deduction for children applies <i>only</i> in current-law pension cases. </span><span style="font-size: 16pt;"><u></u><u></u></span></p><p class="m_1169092326150772281xmsonormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size: 14pt; font-family: Arial, sans-serif;">Per <a href="https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.ecfr.gov%2Fcgi-bin%2Ftext-idx%3FSID%3D6793f96c80fd87106ce29a1ee7d6c97a%26node%3Dse38.1.3_1272%26rgn%3Ddiv8&amp;data=05%7C01%7C%7C463cca1656e648b8f98208db1b3d8616%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638133723276843317%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=bie43HNnZ5bauH4QPfnB33c%2BBpYO7cZWw9%2BLyZDtOCw%3D&amp;reserved=0" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://gcc02.safelinks.protection.outlook.com/?url%3Dhttp%253A%252F%252Fwww.ecfr.gov%252Fcgi-bin%252Ftext-idx%253FSID%253D6793f96c80fd87106ce29a1ee7d6c97a%2526node%253Dse38.1.3_1272%2526rgn%253Ddiv8%26data%3D05%257C01%257C%257C463cca1656e648b8f98208db1b3d8616%257Ce95f1b23abaf45ee821db7ab251ab3bf%257C0%257C0%257C638133723276843317%257CUnknown%257CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%253D%257C3000%257C%257C%257C%26sdata%3Dbie43HNnZ5bauH4QPfnB33c%252BBpYO7cZWw9%252BLyZDtOCw%253D%26reserved%3D0&amp;source=gmail&amp;ust=1677873163494000&amp;usg=AOvVaw186BzT8zgFSwgoKbTg2Pya" style="color: rgb(17, 85, 204);"><b><span style="color: blue;">38 CFR 3.272(j)(2)</span></b></a>, the educational expense deduction applies</span><span style="font-size: 16pt;"><u></u><u></u></span></p><ul type="disc" style="margin-bottom: 0in; color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin-top: 0in;"><li class="m_1169092326150772281xmsonormal" style="margin: 0in 12pt 0in 0in; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14pt; font-family: Arial, sans-serif;">to cases in which the child is</span><span style="font-size: 16pt;"><u></u><u></u></span></li><ul type="disc" style="margin-bottom: 0in; margin-top: 0in;"><li class="m_1169092326150772281xmsonormal" style="margin: 0in 24pt 0in 0in; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14pt; font-family: Arial, sans-serif;">the payee, and</span><span style="font-size: 16pt;"><u></u><u></u></span></li><li class="m_1169092326150772281xmsonormal" style="margin: 0in 24pt 0in 0in; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="font-size: 14pt; font-family: Arial, sans-serif;">a dependent on a Veteran’s or surviving spouse’s claim</span><span style="font-size: 16pt;"><u></u><u></u></span></li></ul><li class="m_1169092326150772281xmsonormal" style="margin: 0in 12pt 0in 0in; font-size: 11pt; font-family: Calibri, sans-serif;"><i><span style="font-size: 14pt; font-family: Arial, sans-serif;">only</span></i><span style="font-size: 14pt; font-family: Arial, sans-serif;"> to reduce the child’s earned income and does <i>not</i> apply if the child has only unearned income, and</span><span style="font-size: 16pt;"><u></u><u></u></span></li><li class="m_1169092326150772281xmsonormal" style="margin: 0in 12pt 0in 0in; font-size: 11pt; font-family: Calibri, sans-serif;"><i><span style="font-size: 14pt; font-family: Arial, sans-serif; color: black; background: yellow;">only</span></i><span style="font-size: 14pt; font-family: Arial, sans-serif; color: black; background: yellow;"> if the child is pursuing a course of post-secondary (after high school) education or training.</span><span style="font-size: 16pt;"><u></u><u></u></span></li></ul><p class="m_1169092326150772281xmsonormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><b><i><span style="font-size: 14pt; font-family: Arial, sans-serif;">Note</span></i></b><span style="font-size: 14pt; font-family: Arial, sans-serif;">:  Deductible expenses include amounts paid for tuition, fees, books, and materials.</span><span style="font-size: 16pt;"><u></u><u></u></span></p><p class="m_1169092326150772281xmsonormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size: 16pt;"> <u></u><u></u></span></p>
Change Date |   | March 31, 2021
-- | -- | --





**IX.i.3.D.4.a.  Applicability of the Educational Expense Deduction to a Veteran or Surviving Spouse Payee**

The educational expense deduction applies only in current-law pension cases.

Per [38 CFR 3.272(i)](https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.ecfr.gov%2Fcgi-bin%2Ftext-idx%3FSID%3D6793f96c80fd87106ce29a1ee7d6c97a%26node%3Dse38.1.3_1272%26rgn%3Ddiv8&data=05%7C01%7C%7C463cca1656e648b8f98208db1b3d8616%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638133723276843317%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bie43HNnZ5bauH4QPfnB33c%2BBpYO7cZWw9%2BLyZDtOCw%3D&reserved=0), **a Veteran’s or surviving spouse’s income for VA purposes may be reduced by amounts paid for tuition, fees, books, and necessary materials.**

If the Veteran or surviving spouse is found to be in need of regular A&A, an additional deduction is allowed for transportation expenses which

are related to school attendance, and exceed the reasonable amounts that would have been incurred by a nondisabled person.

**Comment by jessicastump** [comment]
An update on the content review and changes can be found in the [content ticket here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52920#issuecomment-1474364408). There are both content and flow changes. 

For the flow there is page 1 onboarding, page 2 question with yes/no radio buttons, page 3 is conditional based on the choice (no goes to confirmation screen and yes goes to docs needed screen). 

@longmd and @hdjustice   Would you like me to add details of this to the ticket here as a comment or open a new ticket?

**Comment by jessicastump** [comment]
@hdjustice Checked with content, the enhanced eligibility term came from the [eligibility for VA health care](https://www.va.gov/health-care/eligibility/) page.

**Comment by jessicastump** [comment]
An update on the content review/final Sketch file for reference:  
The [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56616) for this work and the [Sketch file ](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/12B7255E-72F6-4C6A-83C3-81BF9A1CEBDE/canvas) have been updated for all sections except the income and deductibles, awaiting content's final review on these pages and hope to have an update after this Friday's bi-weekly meeting.

**Comment by longmd** [comment]
@jessicastump, are there new changes to this or just reposting here for reference. If there are new things from the last update, can there be a separate posting or something with those updates. It's going to get really hard to keep track of ever-changing content if it's all in the same file.

**Comment by jessicastump** [comment]
@longmd That goal of [this Sketch QA page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/12B7255E-72F6-4C6A-83C3-81BF9A1CEBDE/canvas) is to not have the content evolving but a place for the decided final... but some content has changed since this ticket was created and the screen captures Nick provided. I would be happy to flag the changes made by posting more comments here or creating a new ticket.

**Comment by longmd** [comment]
@jessicastump, if it all matches the last update from when we split the onboarding, confirmation checkbox screen and then the info screen, then I'm good with that. Just wasn't sure if there was anything more that changed after that update. If not, I'm good with where we are at. I'm just about ready to turn over the RI to the team for review and to @davidakennedy for accessibility checks, so if anything else had changed, I would put it in before turning everyone loose.

**Comment by jessicastump** [comment]
No other major flow changes since then and it does match the last update with the onboarding split but there have been some other minor content edits - consistency in language with modals, add info labels are statements now not questions, are a couple of examples. I will flag all of those items here.

**Comment by jessicastump** [comment]
Content change to flag: Financial disclosure

**Comment by jessicastump** [comment]
_Content change to flag _ 
**Marital status question**

Content change summary:
Label change from statement to question: What is your marital status?
Slight change to additional info content: 
> We want to make sure we understand your household’s financial information to better determine what health care benefits you can get. If you’re married, we also need to understand your spouse’s financial information.

[Sketch link](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/dglOLM3)

**Comment by jessicastump** [comment]
_Content change to flag_
**Spouse's additional information page**

Content changes:
1. New additional information component added
2. Label for live with question changed

**New additional information component added**
Add info label: Why we ask for this information
Add info content: This information helps us determine if your spouse was your dependent in 2022.

**Label for live with question changed**
New content: Did you live with your spouse for all or part of 2022? 

[Sketch link](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/Eeeqyyd)

**Comment by jessicastump** [comment]
_Content change to flag_
**Spouse's financial support page**

Content changes of referencing year directly made throughout the form.
New label content: Did you provide financial support to your spouse in 2022 even though you didn't live together?

[Sketch link](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/ZVVJGwZ)

**Comment by jessicastump** [comment]
_Content change to flag_
**Add dependent page**

Updated add info component content:
[label] Who we consider a dependent
[open content]
**Here’s who we consider to be a dependent:**
- A spouse (we recognize same-sex and common law marriages) 
- An unmarried child (including adopted children or stepchildren)

**If your dependent is an unmarried child, one of these descriptions must be true:**
- They’re under 18 years old, **or**
- They’re between the ages of 18 and 23 years old and were attending high school, college, or vocational school full-time or part-time enrolled as a full time student in 2022, **or**
- They're living with a permanent disability that happened before they turned 18

[Sketch link](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/AZxwR8r)

**Comment by jessicastump** [comment]
_Content change_
**Review / add additional dependents**

Content change to h3 on page
Before: Your dependents
Updated: Review your dependents

[Sketch link](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/x00eLJ8)

**Comment by jessicastump** [comment]
Content update after bi-weekly meeting 4/28

- No update on income/deductible content review; Aliyah needs to meet with Danielle next week to go over this before passing back to our team.

_**Content update to flag**_
- One content change came up this week: on the cancel adding modal "you will" should be "you'll"
- [Sketch link](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/bLLq59z)
