### ISSUE TITLE
Define requirements with VBS for new copay notification 

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#52962]
## Issue Description
Connect with VBS to discuss requirements and next steps for the new medical copay notification 

---
## Tasks
- [ ] Create some rough draft definitions for the data file that will be transferred for notifications

## Acceptance Criteria
- [ ] Present and discuss with VBS data requirements
---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
Feb 2 - I just set up reoccurring meeting with VBS team to move this work forward and provide a weekly touchpoint. @ScottyRJames if you have any information that you can send over to them ahead of our first meeting (Feb 10th) Logan said the team is able to start that work now.  Which would be incredible. 
cc: @HeatherRienks

**Comment by ScottyRJames** [comment]
Met with VBS and defined requirements of needing Veteran identifiers and type of identifier as part of the payload

Future work:
- [Generate swagger doc](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/53517)
- [Connect with identity regarding DFN and EDIPI](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/53519)
