### ISSUE TITLE
[FE] [STAGING TOOL] Surface initiate (pre-)checkin errors to end user in the Staging Tool

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#52973]
## Background

Since the switch to use VEText data for initiate checkin, errors such as `Pre-checkin attempted in unsupported location(s)` are not surfaced to the end user. Instead we just see `Failed to fetch`. We should re-surface these errors to make debugging easier and help users with errors they can correct themselves.

## Tasks
- [ ] [FE] Surface initiate (pre-)checkin errors to end user
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
co-worked and validated together with @acrollet
