### ISSUE TITLE
[Ongoing Service] New Platform Website Documentation: FY2023 Q2

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#52979]
### Problem
In the current process, there is no way for the Platform Content team to know which content in the deployment process is simply edited vs brand new.

When there is brand new content, we would like to elevate the importance of this to VFS team members.

We would also like to make sure we understand where it best fits in the Information Architecture (IA) of the website.

### How might we?

- How might we differentiate minor content updates from "more important" or new content added to the Platform websites for VFS teams to know about?
- How might we guide other Platform teams to let us know when new documentation needs to be created?
- How might we collaborate on where in the IA new documentation needs to live?
- How might we align our editing support to other Platform teams based on their release timelines?

### User Stories
As a VFS team member,
I want to know what content is new on the Platform website,
So that I stay in the know about a new technical release or general information I need to know about.

As a Platform team member,
I want to know what the process is to release new documentation on the Platform website related to a technical release,
So that I can communicate to VFS teams how and when to find it on the Platform website.

As a Platform content team member,
I want to start tracking when another Platform team has a new release that needs new documentation on the Platform website,
So that we know where in the IA of the Platform website it will live,
So that we can provide extra support to the other Platform team with style guidance,
So that we can elevate the importance of this new documentation to VFS teams.

## Current content support outlets:

Initial content support requests from other Platform teams may come through any of these outlets:

1. Slack:

- #platform-content

2. Office Hours:

- Office hours, every Tuesday at 2:30pm EST

## Definition of done

- [x] Platform Content team is aware of what content is brand new on the Platform website.

- [x] Platform Content team is able to identify new content on the Platform website for VFS teams.

- [x] Platform Content team provided extra editing support to Platform teams who released new documentation on the website in FY2023 Q2

**Comment by jknipes** [comment]
no issues were added to this Epic, but we can verify definition of done using the Last Updated app in Confluencer
