### ISSUE TITLE
Mapping of MHV premium and DS Logon to NIST 800-63

### ISSUE THREAD

**Issue by porta-antiporta** [department-of-veterans-affairs/va.gov-team#52970]
## Issue Description
As a Login.gov stakeholder, I want to understand how MHV Premium and DS Logon accounts map to 800-63 so I can make a risk based decision to accept the credential or not

---
## Tasks
- [x] Get location of MHV policies, credential data from previous sprint
- [x] Investigate what documents already exist mapping to 800-63
- [ ] Enumerate MHV premium credentialing paths
- [ ] Enumerate DS-Logon CAC credentialing paths
- [ ] Create 800-63 mapping matrix (get from Kantara or Login.gov)
- [ ] Map each path to 1 matrix (ex. 1 per tab)
- [x] Assess compensating controls for any gaps (ex. Fraud detection, usage)

## Acceptance Criteria
- [x] Highlight any risks to inheritance (due to gaps in mapping) to John during midsprint review
- [x] Share draft with John by end of sprint
- [x] Share draft with Login.gov
- [x] Schedule time with Login.gov to review after sharing
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [X] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by tygindraux** [comment]
Not sure if there's anything helpful [in here](https://docs.google.com/presentation/d/1T6LnoYdnfiTxTwwljn_2jPT-2z63VcbL/edit#slide=id.p70), it'll be pretty rudimentary though.

**Comment by porta-antiporta** [comment]
As I've been writing the rIsks [document](https://docs.google.com/document/d/1TWCSslF8_96Xzqw-F282C4RHShDF_YF8Zh1ag3I937o/edit#), I have concerns that Login.gov may not accept MHV premium credentials (even with the work they are conducting on address confirmation). 

Also, the [mapping](https://docs.google.com/spreadsheets/d/1zEsPw0U_oEyEdO3YntL-nGL7sDLPqiL6/edit?usp=share_link&ouid=114019674656609869359&rtpof=true&sd=true) that had been created by the discovery team is fairly close, enough for Login.gov to start reviewing. Flipping it into the SAC format that Login.gov is used to would be some effort, but not terrible.

But given the risks may preclude inheritance, recommend focusing on confirming / working through those with Login.gov over the mapping for the remainder of the sprint.

**Comment by porta-antiporta** [comment]
Had slack discussions with Identity Core team re: AAL2 gaps, which were confirmed in [slack](https://dsva.slack.com/archives/C04LFGY2SJK/p1675956580792459). Updated the risk document to reflect latest findings and potential paths forward. 

Confirmed in demo that we will pause mapping and continue gaps discussion with Login.gov around not just inherited proofing, but other upcoming initiatives. Propose closing this issue
