### ISSUE TITLE
Invite additional groups to #vfs-change-announcements channel

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#52983]
## Purpose
Given the changing team compositions and analysis of 4th Qtr use of the channel, let's attempt to increase the membership of the channel

## Tasks
- [x] Invite vfs-backend
- [x] Invite vfs-frontend
- [x] Invite design

## Acceptance Criteria
- [x] Invitations sent to all of the above groups
