### ISSUE TITLE
FSR Facility Discrepancy

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#52999]
## Issue Description
DMC has reported conflicting information for a Veteran who was serviced by both Orlando and Houston.  It is believed that when the Veteran tried to submit a waiver for the Orlando debt it came up with the Houston facility.  The Veteran added a note on the waiver but it was routed to Houston where the Veteran currently does not have any debts. 

The last statement from Houston was in 2019. 
The last statement from Orlando was November and December 2022

Facilities: Orlando (675) and Houston (580)

---
## Tasks
- [x] Scott plans to validate the information on the VODA end and reach out to VBS if needed

## Acceptance Criteria
- [x] Determine cause of issue or route issue to VBS for continued investigation. 
    - [ ] If routed to VBS, communicate back to DMC with update for awareness.  
---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Looked into submission on SharePoint and all facility and statement info points to Orlando VAMC, `vets-json-schema` station id 580 is also correlated with Orlando, and the data we received from VBS also states Orlando as the med center. No references in our data to old Houston station found in this FSR submission. Would need more information from the affected Veteran.
