### ISSUE TITLE
[Design] My VA Audit Improvements: Use Case Documentation

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#53000]
## Background
We need to craft our use case documentation for My VA now that the audit improvement work is moving toward launch. Until the audit improvements are launched to all users, we'll want to keep this documentation out of Github to avoid any confusion. When we're ready, we'll move it over into[ this space.](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/use-cases#my-va-use-cases)

## Tasks
- [x] Craft use cases for Claims and Appeals section
- [x] Craft use cases for Health Care section
- [x] Craft use cases for Education and Training section
- [x] Craft use cases for Benefit Application Drafts section
- [ ] PM/PO review

## Acceptance Criteria
- [ ] Use cases documented and reviewed by PM/PO

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ NA
- _How can this work be validated?_ NA

**Comment by aagosto90** [comment]
FYI @Samara-Strauss @ajakabcin Here's a link to the [Google doc](https://docs.google.com/document/d/1JG8AJs-b8ceD_YCNBEX6Ie3-ZOX_JytEM963_vuZ39A/edit#) where I'll be drafting these use cases until we are live with the updates and I can publish it all in GH.

**Comment by BerniXiongA6** [comment]
Hi @aagosto90  -- will any of this work carry over and if so do you have an estimate of how many points are left?

**Comment by aagosto90** [comment]
Hi @BerniXiongA6 - The only reason this is still open is for @ajakabcin and @Samara-Strauss to review the draft doc but it's just kind of been sitting here because there's no rush on that as of now and it's going to be time-consuming for them to review. So probably no more points for me, but possibly a couple for @ajakabcin .

**Comment by BerniXiongA6** [comment]
Perfect thanks @aagosto90 -- if your points are completed, then that will get updated on my sprint calculator. Great job!

**Comment by Samara-Strauss** [comment]
I didn't realize this needed my review! I'm sorry. When would like this work reviewed?

**Comment by Samara-Strauss** [comment]
Just had a chance to review -- this is awesome! I made a couple comments/suggestions, but that's it. The most impactful one is around potentially restructuring how the health docs are organized, so that would take some editing, but hopefully make things simpler all around. Excellent work, @aagosto90! Can't wait to get these into Github when the new updates launch.

**Comment by aagosto90** [comment]
@Samara-Strauss [I've completed the updates!](https://docs.google.com/document/d/1JG8AJs-b8ceD_YCNBEX6Ie3-ZOX_JytEM963_vuZ39A/edit#) This definitely did help to simplify the crazy health care section. Let me know if the changes are good with you and I'll close this ticket.

**Comment by Samara-Strauss** [comment]
Just gave a quick glance to the health care sections, and this looks good to me! It's good to go for when the audit updates go out :D
