### ISSUE TITLE
Repopulate user data from MPI in FSR submission jobs

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#53021]
## Issue Description
User objects in redis are not guaranteed to be populated when a sidekiq job is ran so we should use the use `user_account_id` to repopulate any needed data from MPI. This has caused a couple errors within the jobs for lack of email or ssn.

---
## Tasks
- [ ] Pass `user_account_id` to job as parameter
- [ ] Repopulate redis user object with MPI data

## Acceptance Criteria
- [ ] Jobs don't rely on redis user object existence 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kjsuarez** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/12858
