### ISSUE TITLE
[CONTENT] Translate and create NEW content for "Lebanon-health-care" Home Page in CMS [CONTENT]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#5302]
## User Story or Problem Statement
As a Veteran Web user, I need a plain language and descriptive HOME/SPLASH page, so that it will help direct me to the quickest path on my web journey. 

## Goal
_Efficient and clear content describing local Jobs and Careers Page?_

## Objectives or Key Results this is meant to further
- _Reduced word count and improved plain language._

## Resources - Tools - Documentation
[Home/Splash Page](https://www.lebanon.va.gov/)
[AtoZ Health Services](https://www.lebanon.va.gov/services/index.asp)
[Leadership page](https://www.lebanon.va.gov/about/leadership.asp)
[Pittsburgh new HOME Page](https://va.gov/pittsburgh-health-care/)
[Required VAMC WebPage Listing and Drupal Example](https://drive.google.com/drive/folders/1f_PRAt67ccYNm5DkJiAKwINsSX_S5_4o)

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [x] Completed Content is written in Word Document format (Template provided above) and is saved 
referencing Medical Facility Name, Page name, and writer's initials (i.e. Lebanon-HomePage-lw) 
- [x] Page must be saved in Content folder on Google Drive,

-Includes the following sections in the content
- [x] Site intro
- [x] Locations introduction
- [x] Health Services Introduction
- [ ] Leadership Introduction
- [x] Review and List any "Spotlight items at Facility of System"

## Acceptance Criteria
* Completed Content is written in Word Document format and is saved referencing Facility Name, Page Name, and writer's initials.
* Page must be saved in Content folder on Google Drive under Page reference name
