### ISSUE TITLE
Remove react widget from Supplemental Claims page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#53039]
## Issue Description

Once the Supplemental Claims online form is launched to 100% of users, we can remove the react widget and put content back in the Drupal page. 

## Tasks
- [x] Remove react widget (Katherine)
- [x] Add content back into Drupal (Katherine)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Content is in Drupal on live page

**Comment by RLHecht** [comment]
I removed the widget and added content back into Drupal. Will hold to send to Megan until we know the tool is ready to launch.

**Comment by megzehn** [comment]
Thanks, @RLHecht. Confirming I reviewed the changes and published this page.

**Comment by RLHecht** [comment]
These changes are live. Closing!
