### ISSUE TITLE
Document the steps to decommission an application

### ISSUE THREAD

**Issue by considerable** [department-of-veterans-affairs/va.gov-team#53044]
## Issue Description
Routine steps to decommission an application need to be well documented

---
## Tasks
- [x] Create a step-by-step document
- [x] Link it to the index page [How do I...](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593968/How+do+I...)

---
## Acceptance Criteria
- [ ] Another engineer must be able to decommission an application following the document

**Comment by laineymajor** [comment]
@considerable can you please assign an estimate to this work?
1 - XS (1 day)
2 - S (1-3 days)
3 - M (3-5 day, max 1 week)
5 - L (5-10 days - max, full sprint)
8 - XL - (more than a sprint, break apart)
13 - XXL (multiple sprints, break apart)

**Comment by considerable** [comment]
- How do I...: [Deprecate and remove old application from EKS](https://vfs.atlassian.net/wiki/spaces/OT/pages/2521399636/Deprecate+and+remove+old+application+from+EKS)

![app-deprecation.png](https://images.zenhubusercontent.com/616758e4c5e87dce2146cdcf/4ce15724-c96b-4921-867a-23f8ca3174f1)

**Comment by laineymajor** [comment]
@rmtolmach to test instructions... will close upon completion
- Rebecca: deprecate PgHero helm 102
- Igor: helm 101 (the zombie)

**Comment by laineymajor** [comment]
Anticipate completing by end of sprint 20

**Comment by laineymajor** [comment]
Added to current sprint.. item was identified as needed _after_ sprint planning, and I neglected to add it to the sprint.

**Comment by laineymajor** [comment]
Ready to close per @considerable
