### ISSUE TITLE
[FE] - Refactor appointmentActionVaos component

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#53050]
## Description
Look at moving the check-in click call to a util and pass the onClick handler in an effort to remove need for the appointmentActionVaos component all together.
 
## Tasks
- [ ] Avoid passing router down into component tree by creating a hook or util to handle appointment Check In button click and pass that to the CheckInButton component on the list and details views
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
@brianseek I'm assuming this is a completely behind-the-scenes thing and won't affect what the Veteran sees? just want to make sure if we start testing that nothing will change from a Veterans point of view when this refactor is complete
@kellysmith1008 @benbrasso-agile6

**Comment by brianseek** [comment]
@loripusey yep, that is correct. But we should wait for this to be in before we start testing.

**Comment by brianseek** [comment]
Moving this to closed since it is merged and will be tested with the rest of the epic
