### ISSUE TITLE
[FE] Integrate mock authentication between FE + BE

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#53054]
## Description
This button will call Sign in Service with `client_id=vamock`, and will initiate the process to mock authentication (if everything works fine maybe `vets-website` won't need any other changes?)

Ensure this button does not, cannot show up on staging or production stacks

## Tasks
- [x] Create new Unified Sign in Page configuration for `vamock` on `dev.config.js` and `staging.config.js`
  - [x] Ensure redirect to `<environment>/sign_in/authorize?client_id=vamock`
- [x] Create mock authentication button for USiP 
  - [x] Ensure it will not display for production (localhost & dev only)
  - [x] Clicking the ubtton takes you to the above URL
  - [x] Ensure button background color is different than any other CSP color
- [x] Write unit tests to ensure functionality
- [x] Add Select bar and options for each CSP that alters `type=<csp>` when button redirects

**Comment by asg5704** [comment]
Ensure both Ian M. & Afia C.'s work is incorporated into a single body of work.  The goal should be able to authenticate front to back.
