### ISSUE TITLE
[UX] [Research] Create optimal workshop study

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#53056]
## Description 

How might we better understand text messaging preferences of Veterans to inform when to send them text messages when it's time to check in for their appointments? How might those preferences differ for different cohorts? For example, gender, age, cognitive disabilities, blind Veterans, care givers, etc. 

[Refer to Check In's recent optimal workshop study, if needed](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/43576). 

## Tasks 

- [ ] Create draft study in optimal workshop
- [ ] Approved by VA stakeholders and POs
- [ ] Approved by Shane

## AC

- [ ] Created draft study in optimal workshop
- [ ] Approved by VA stakeholders and POs
- [ ] Approved by Shane
