### ISSUE TITLE
Certificate of Eligibility | Adding LOA3 and EDIPI verification

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#53062]
## Issue Description

After launching COE to 25% of vets, we discovered that the COE form and COE status page don't validate whether a user is LOA3 or has an EDIPI -- both of which are necessary to submit a COE form.

---
## Tasks
- [x] Display alert if vet is missing these requirements.

## Acceptance Criteria
- [x] Vet sees alerts, and can't proceed with form until they meet requirements.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by data-doge** [comment]
@saderagsdale Works on production. Tested with Rocio (who saw the COE form) and myself (who saw the EDIPI alert, since as a non-vet, I do not have an EDIPI). Closing.
