### ISSUE TITLE
[UX] Initial prototype tasks for testing with Veterans

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#53067]
## Tasks

- [x] Setup new CodePen account for team use (currently free)
- [x] Determine how to get appt list code (e.g., should we grab from VAOS) 
- [x] Determine how to move FE templates to new CodePen account
- [x] Confirm which components can be brought in from the design system vs. hard coded - and where FE help is needed
- [ ] Build prototype (to the degree possible, without engineer support) 
  - [x] Confirm all needed components are included in templates - check with FE if stuck
  - [x] Confirm templates match Sketch designs
  - [x] Fork (copy) templates for all needed pages (happy path + unhappy paths) - and rename each page
  - [x] Make changes to forked templates as needed
  - [x] Link templates and confirm full flow
- [x] Knowledge share with UX team 
- [ ] Have engineers do an accessibility audit

## AC

- [ ] Prototype is complete
- [ ] Pages are linked to represent user flows
- [ ] Prototype matches Sketch designs (any discrepancies have been updated or documented)
- [ ] UX knowledge share complete
- [ ] Accessibility audit is done

**Comment by cgednalske** [comment]
Hey @benbrasso-agile6 -- added in more tasks/sub-tasks and some AC. Anything I'm missing or including too early?

**Comment by benbrasso-agile6** [comment]
Looks great

**Comment by loripusey** [comment]
UX pointed 5, need engineering to point @loripusey

**Comment by loripusey** [comment]
2 points engineering time

**Comment by cgednalske** [comment]
@benbrasso-agile6 @zach-park @kellysmith1008 @ytsaoca here is the CodePen info we'll all need to get started. We'll go over all this in our walk-through today.

**CodePen Access:** 
https://codepen.io/your-work/ (message Christina for credentials)

**Storybook:** 
https://design.va.gov/storybook/?path=/docs/components-va-alert--default
- This is where you can grab the code for design system components. 
- Talk with Brian or John if something you need is not included in the design system and also isn't already in one of our templates. 
- Use FE channel for code questions for them in case a few of us have similar questions.

**CodePen page categories**
Collections are set up for each of us to work on these areas.
- [Demographics](https://codepen.io/collection/QWzywW) (Kelly)
- [Travel reimbursement](https://codepen.io/collection/dbrYGZ) (Ya-ching)
- [Appointment details pages](https://codepen.io/collection/jbxZPO) (Zach)
- Confirmation pages (+PCI intro page) (Christina)
- Appointment list (Christina)
- (Ben will float around)

**For easy reference:**
[Templates Collection](https://codepen.io/collection/gYMYbb)

**Comment by zach-park** [comment]
Hi @cgednalske, the appointment details pages are ready for review: https://codepen.io/collection/jbxZPO

**Comment by kellysmith1008** [comment]
Hi @cgednalske the demographics pages are ready for review

**Comment by zach-park** [comment]
Hi @cgednalske , contents for the appointment detail pages are finished.

**Comment by cgednalske** [comment]
@kellysmith1008 they look great! Will just need the back to last screen once we have that code. Nice work 🎉

**Comment by loripusey** [comment]
@benbrasso-agile6 If there are tasks left from this ticket by tomorrow, can we split just those tasks out into separate tickets and close this one?

**Comment by benbrasso-agile6** [comment]
This will be the new one, Lori - https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/56144

**Comment by cgednalske** [comment]
Quick update that the prototype was handed off to Brian and John earlier this afternoon. Looks like they have implemented the tool they'll use for the accessibility scan 👍

**Comment by loripusey** [comment]
@brianseek can you please close this ticket when you have completed the A11y scan? thanks.
