### ISSUE TITLE
Collaboration Cycle - Implement Staging Review requirements

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#53070]
## Problem Statement 
Governance team has experienced challenges with VFS teams not having their products completely ready for a Staging Review. This impacts Governance because there is an expectation that we'll be able to fully test the product/feature to ensure it meets design, IA, accessibility, QA and content standards. Since we try to be accommodating and not delay the VFS team by pushing out the Staging Review, we will typically work with the VFS team to resolve access issues, address missing artifacts, or resolve whatever the specific challenge is that we're facing. Unfortunately, this approach requires a significant time commitment from Governance team, and asks us to take on additional work simply because the VFS team did not come to the Staging Review prepared. In addition, the stress levels of the Governance team have increased and team morale has decreased. We can no longer allow VFS teams to move forward with a Staging Review if Governance team is not able to fully test the product/feature. 

HMW ensure VFS teams are better prepared for a Collaboration Cycle Staging Review?
HMW introduce processes that allow Governance team to postpone the Staging Review if the product is not testable?
HMW clearly communicate our Staging Review expectations to the VFS team? 
HMW collaborate with other teams involved in the Collaboration Cycle to not introduce churn and or challenges with their existing processes?

## Hypothesis or Bet
If we implement Staging Review requirements, then we will encounter less blockers at VFS team Staging Reviews.
If we implement Staging Review requirements, then we will not spend more time than average completing our Staging Review testing.

## We will know we're done when... ("Definition of Done")
- [x] Governance team is able to postpone a Staging Review if requirements are not met without consulting with OCTO first
- [x] Platform Website/Collaboration Cycle pages communicate the requirements for a Staging Review.
- [x] VFS teams have been informed of the new Staging Review requirements following guidelines in the Platform Communication Playbook
- [x] We have agreed upon a solution that does not impact or creates minimal impact to the existing processes of Sitewide Content, IA, and Accessibility team

## Solution
**Phase 1:** 
Communicate to VFS teams the following Staging Review criteria:

> The following requirements must be met for a Staging Review to continue as scheduled:

> 1. All test scenarios must be able to be completed by the Governance team.
> 2. All possible user paths must be included for testing.
> 3. Any test users identified for the product must be available, valid and/or functioning as specified. We will make no exceptions for third-party dependencies.
> 4. All known bugs that could cause false errors have been addressed.

**Phase 2:**
(Phase 2 may be broken out of this initiative and implemented as it's own initiative at a later date due to dependencies on Sitewide CAIA)
Improve VFS team engagement with Sitewide CAIA with introduction of the following solutions:

1. Update the SWC and IA Intake request page to include that this touchpoint is required if a) the entry point for the tool is on a static page, b) etc. (Sitewide CAIA to help define this). Similar proposal in place for other Collaboration Cycle touchpoint pages per ticket #53084
2. Link Sitewide Content and IA intake touchpoint page on Platform Website in the Collaboration Cycle Request ticket

Once solutions 1 and 2 are implemented above, then we will add the following to the Staging Review criteria from Phase 1:

>- If applicable, the static landing page, which serves as the entry point of the product, must be complete. The static page and the product must go through Staging Review together or the static page must complete the Staging Review first. 

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed*

## Projected Launch Date
March 14, 2023

### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my Platform initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given Platform initiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1912569976/Platform+Product+terminology?atlOrigin=eyJpIjoiM2VmNzY2MTZkZWE4NGY2NmJmNjk2YWIwMmJhMGZiZmYiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ) for details._

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [Platform Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Configure your communication to teams about your work using the [Change Communication Guide](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2317647873/Change+Communication+Guide)
- [ ] Conduct a [go/no-go](https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic
- [ ] Add this initiative to the [Digital Experience Product Board](https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform) using [these instructions](https://vfs.atlassian.net/wiki/spaces/AP/pages/2120974387/Platform+Initiative+Guidelines+for+Digital+Experience+Product+Board)

**Comment by shiragoodman** [comment]
@raywangoctova FYI Phase 2, detailed above under Solution, may have to be broken out and implemented at a later date due to dependencies on the Sitewide CAIA team. We should be ready to launch the other 4 requirements by next week.

**Comment by shiragoodman** [comment]
The first 4 Staging Review requirements have been released and announced to VFS teams. Phase 2, which includes contingencies with the Sitewide CAIA team, will be implemented in initiative [Collaboration Cycle - Improve collaboration points with Sitewide CAIA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55118).
