### ISSUE TITLE
Evaluate options for improving communication on touchpoints being recommended vs. required

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#53084]
## User Story
_"As a (persona), I (want to), (so that)."_

Assignee:
Peer Reviewer:

## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

## Tasks
- [ ] _Placeholder task_

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] _Placeholder AC_

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
## User Story
_"As a (persona), I (want to), (so that)."_

Assignee:
Peer Reviewer:

## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

## Impacted Artifacts


## Tasks
- [ ] _Placeholder task_

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] _Placeholder AC_

## How to prepare this issue
### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Removed this ticket from initiative #53070. This ticket is not critical for roll out of the Staging Review requirements, and instead can be addressed as tech-debt or part of a larger initiative if/when the 5th requirement (re: static pages being complete) is ready to be implemented.

**Comment by shiragoodman** [comment]
we no longer say "recommended Collaboration Cycle touchpoints" in the CC Request ticket. we communicate on each PW touchpoint page if the touchpoint is required or not.
