### ISSUE TITLE
Discuss options for redefining static page support expectations for VFS teams

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#53112]
## User Story
As a Sitewide Content, IA and Accessibility team member, I want VFS teams needing static page support to engage with my team early on so that we are able to plan and provide support appropriately and aren't guilted, bullied and or pressured to meet their stakeholder deadlines.

As a Governance team member, I want to make sure VFS teams needing static page support are engaging with Sitewide Content, IA and Accessibility early on in their build process so that they receive support in a timely manner and we are able to view the full product flow at the VFS teams Staging Review.

As a VFS team member, I want to make sure I am reaching out in a timely manner for receiving static page support so that I am able to go to Staging Review without delaying stakeholder deadlines.

Assignee:
Peer Reviewer:

## Description
Governance team wants to enforce that all VFS teams in need of a new static page or modifications to existing static page  have that work completed by Sitewide Content, IA and Accessibility prior to engaging in a Collaboration Cycle Staging Review so that the VFS product and the entry static page can be upheld together to the same Platform standards. 

However, the challenges we face are that sometimes VFS teams don't reach out to the Sitewide Content, IA and Accessibility team for that support until later in their build cycle. If Governance team were to require that the static page be completed and ready by the time of the VFS product Staging Review, this could put pressure on the Sitewide Content, IA and Accessibility team to rush to complete the static page changes.

We want to make sure the Sitewide Content, IA and Accessibility team has sufficient time to make modifications to the static page or create a new static page. We want to encourage the VFS team to reach out to the Sitewide Content, IA and Accessibility team (via the Sitewide Content and IA Intake request) early in their build cycle for support.

How might we encourage the VFS team to engage with the Sitewide Content, IA and Accessibility team early on in their build cycle?
How might we deter VFS teams from late engagement with the Sitewide Content, IA and Accessibility team?
How might we communicate that VFS teams are required to receive support from Sitewide Content, IA and Accessibility for any static page changes?
How might we make Collaboration Cycle expectations more transparent for VFS teams?

## Tasks
- [x] Hold meeting with Governance team and Sitewide Content, IA and Accessibility team to discuss current challenges and proposed solutions
   - Meeting scheduled for 2/6 at 2:00pm ET
   - Terry, Randi, Martha and Shira were in attendance. Ideas (in no particular order) are detailed below
- [x] Ideas/solutions proposed:

1.   Update the SWC and IA Intake request page to include that this touchpoint is required if a) the entry point for the tool is on a static page, b) etc. (Sitewide CAIA to help define this). Similar proposal in place for other Collaboration Cycle touchpoint pages per ticket #53084
2.   Create checklist for Staging Review page. Staging Review cannot be scheduled until all items are met.
3.   Modify Kickoff questions to ask more about content and IA needs
4.   Link Sitewide Content and IA intake touchpoint page on Platform Website in the Collaboration Cycle Request ticket (this should happen regardless)
5.   Use Design Intent meeting to determine content and IA needs (this doesn't help solve our problem for teams who decide to skip Design Intent) 

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Governance team and Sitewide Content have agreed on a solution for redefining static page support expectations for VFS teams

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by DanielleThierryUSDSVA** [comment]
Hi @shiragoodman. I think you've captured the user stories well here, thank you! One thing I want to just be sure that we're doing throughout all documentation is referring to the team as Sitewide content, IA, and accessibility. We're working to strengthen the connection and workflows between the 3 disciplines in our combined team and I just want to make sure we're all (both within our team and across OCTO/VA) always thinking of all 3 in everything we discuss and plan.

Bringing @RLHecht and @coforma-terry into this ticket as well. I won't be able to be at the Monday meeting because I'll be flying to D.C. but I totally trust you all to come up with ideas for this and am happy to talk more about potential approaches. And Beth is going to attend to share her content perspective based on the recent challenge. Thanks!

**Comment by shiragoodman** [comment]
thanks @DanielleThierryUSDSVA ! I will make the updates to reflect your proper team name (it already is at the initiative level in #53070) and looking forward to discussing further today!

**Comment by shiragoodman** [comment]
@RLHecht @coforma-terry @artsymartha68 I added ideas/solutions proposed to the Tasks section above. 

My 2 cents is we gotta try something. W/e we try doesn't have to be our forever solution. We also don't even need to pick 1... we can choose to implement many. But we're not going to see a change until we do something. I personally feel like solution # 1, 2 and 4 are what we should move forward with, however I'm still open to new ideas and additional discussion.

**Comment by RLHecht** [comment]
Thanks so much for putting all this together @shiragoodman. I agree that we need to try something and think having a checklist that must be complete before a staging review can be scheduled will really help. I also agree with you that we should implement # 1 and # 4 too. The more times we can stress that support from our team is critical, the better. For teams doing design intents, there shouldn't be too many issues anymore because we are now making sure someone from our team is always at one—we'll know if we don't get an intake request afterward. And for the teams that skip the first two touch points the required checklist will help.

**Comment by artsymartha68** [comment]
Linking #53288 where @briandeconinck has a nice template started.

**Comment by shiragoodman** [comment]
hey @RLHecht . We have decided as a team to move forward with rolling out the 4 other agreed upon requirements (see Solution/Phase 1 in the [initiative ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53070)). Phase 2 of the Solution will involve adding the static page requirements, but we think it would be best to give your team some time to define under what circumstances would it be _required_ for a VFS team to engage with Sitewide CAIA and submit an intake request. We know "if they need a static page" but what else? 

Let me know if you'd like to get together to discuss further. For now, I will be closing out this ticket and we can come back to this when Phase 1 is complete. ty!
