### ISSUE TITLE
Amazon Linux 1 AMI POA&M Update

### ISSUE THREAD

**Issue by gary-fallon** [department-of-veterans-affairs/va.gov-team#53151]
## Description
RE: POA&M 1018541285936

Per Doug Wheeler from OIT, the current POA&M needs to be revised and should include an updated vulnerability description and milestone(s). In addition, it was recommended that a BIA also be included for the severity of "very high."

## Related
https://github.com/department-of-veterans-affairs/platform-security/issues/187

## Tasks
The following tasks must be reviewed and completed as necessary.
- [ ] Review our dynamic inventory of AL1 instances within the system boundary and compare it to the most recent report from Doug Wheeler.
- [ ] Ensure the AL1 instances in question are actually within our boundary because VA.gov is only in control of certain subnets that fall within the 10.247.0.0/16 CIDR range. Doug Wheeler had taken this as an action item during our discussion.
- [ ] Review the Known Exploited Vulnerabilities (KEV) in our AL1 image and determine if any can be mitigated or remediated through removal from the base image.
- [ ] Update POA&M to include possible milestones:
  - [ ] Remove or update known vulnerabilities from the AL1 image, including the estimated date of completion.
  - [ ] Update vets-api AL1 instances, including the estimated date of completion and estimated number of instances affected.
  - [ ] Update of remaining AL1 instances, including the estimated date of completion.

## Acceptance
The following tasks must be completed before this issue can be considered done.
- [ ] The POA&M is reviewed by @little-oddball, @fowusu2, and @gary-fallon.
- [ ] The POA&M is submitted to the VA portal for review and feedback (optional).

**Comment by fowusu2** [comment]
Doug Wheeler sent me a teams message on 03/24/2023 requesting for a status update of AMI linux servers  upgrade because there was a 1000 instances of AMI linux servers that showed up on his reports. Asked him to send me a copy of the reports. Will attach the results when received
