### ISSUE TITLE
Update production EOAS fwdproxy entry to use new endpoint

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#53165]
## Background
EOAS has been migrating their services to AWS and in order to support their efforts, we will need to update our production fwdproxy config settings to use their new service.

## Considerations
| Environment | SSO URL | Non-SSO URL |
| ------------  | --- | ---- |
| Dev | https://ssodev.cem.vaec.va.gov | https://dev.cem.vaec.va.gov |
| Staging | https://ssobeta.cem.vaec.va.gov | https://beta.cem.vaec.va.gov |
| Prod | https://ssoboss.cem.vaec.va.gov | https://vaww.boss.cem.vaec.va.gov |

We need to update the production URL to the **non-sso** version

## Tasks
- [x] Update prod EOAS fwdproxy config entry to use **non-sso** URL

## Acceptance Criteria
- [x] Prod EOAS fwdproxy config entry is using new **non-sso** URL
- [x] PR has been approved / merged
