### ISSUE TITLE
Content updates to COVID-19 vaccine and booster pages 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#53162]
## Issue Description

We recently got new and updated information from the SMEs we work with for our COVID-19 content. We need to incorporate these changes into our pages and make sure we adhere to VA.gov plain language and style standards. 

We can make copyedits to this content as long as we adhere to the accuracy.

[COVID-19 booster shots](https://www.va.gov/health-care/covid-19-vaccine/booster-shots-and-additional-doses/) page:

![Screen Shot 2023-02-06 at 10.36.38 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/6c5b436d-5ba0-45c7-8df3-2ca17c1dae89)

[About COVID-19 vaccines](https://www.va.gov/health-care/covid-19-vaccine/about-covid-19-vaccine/) page:

![Screen Shot 2023-02-06 at 10.41.08 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/19121a99-e19d-4ee1-834c-371bcc905eac)

![Screen Shot 2023-02-06 at 10.42.16 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/bac2eb89-6559-47cf-9c72-45c9a4069066)

![Screen Shot 2023-02-06 at 10.41.38 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/116138db-736a-465b-9972-2c53f4ce52a5)

![Screen Shot 2023-02-06 at 10.43.02 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/16417150-d973-4588-9ff0-d28a1d938fb8)

![Screen Shot 2023-02-06 at 10.43.27 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/b3047571-f832-4b66-9663-cc40905155fb)

![Screen Shot 2023-02-06 at 10.43.49 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/e79cb98b-62b8-4adf-ad66-e2d3f5197484)

![Screen Shot 2023-02-06 at 10.44.12 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/434aa9fe-8715-4fa3-8ca8-050fc1871f38)

![Screen Shot 2023-02-06 at 10.45.34 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/c4b9c682-cd2e-40bd-a206-f1fed6ccc771)

[Coronavirus FAQs](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/#covid-19-vaccines) page:

![Screen Shot 2023-02-06 at 10.46.33 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/7c79e2a1-382e-4ad9-b69c-28d0a0115997)

## Tasks
- [x] Make edits to Drupal pages (Aliyah)
- [x] Copyedit (Megan)
- [x] Publish (Megan)
- [x] Create word doc to send to translation team (Randi/Ana)
- [x] Notify stakeholders that changes are live (Randi)
## Acceptance Criteria
- [x] New content is live on 3 pages

**Comment by aliyahblackmore** [comment]
Hi @megzehn the updates on the booster shots and about COVID-19 pages are ready for you. Going to just confirm with Randi tomorrow which draft version of the FAQs page I should make changes to, as I noticed that Danielle started to make a few updates to this page. 
____________

[**COVID booster shots page**](https://www.va.gov/health-care/covid-19-vaccine/booster-shots-and-additional-doses/)
**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=34054
**Notes:** I removed the third sentence in the featured content box.

[**About COVID-19 vaccines**](https://www.va.gov/health-care/covid-19-vaccine/about-covid-19-vaccine/) page:
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=34627

**Notes:** 

1. In section “Why to get a COVID-19 vaccine” I removed the bullet point that starts with “When you get a COVID-19 vaccine, you help protect your family, friends, and community”
2. I tried moving the note content before the bulleted list, as SMEs recommended, but it didn’t seem to work the bulleted list. I did add in “Here are some reasons to get a COVID-19 vaccine”  ahead of the list – it seems like there needed to be an intro after the H2. I left the “Note” as is for the time being, and sent a Slack message to Danielle for a quick gut check on this. More on this soon!
3. For their adjustment to the “When you’re up to date” bullet point, I think that we’d want to state what someone can do vs. “not.” I addressed this by adjusting this language to say “or going to different activities.” Open to thoughts here.
4. In this same bullet point, I noticed that the bolded text doesn’t say “COVID-19 vaccines” but other bullet points are using it on a first mention. Wondering if we’d want to include that here and if it would be okay to remove “COVID-19” on the second mention? I went ahead and made this change in Drupal.
5. Wondering if hospitalization should be switched to “severe illness” here or if that would change the meaning? I noticed that we are using "severe illness" on this page. I left this as is for the time being and I changed “dying from” to “death from” to be more closely aligned with content on this page.
6. I adjusted “vaccine” to “vaccines”
7. In the “Vaccine effectiveness” section, confirmed with Randi that we should leave the two links at the end in. The screen capture in the ticket and from the SME email have them excluded. 
8. In the “Vaccine safety” section I added in their suggestion for Hundred of millions. 
9. In this same section I also added in the suggested new link on vaccine safety, adjusted placement, and added “on the CDC website” since we are linking out to an external page/non VA page.
10. In the “COVID-19 vaccine safety during pregnancy and breastfeeding section” I made an adjustment to the links in their new bullet points to be sentence case and to more closely match the header on the CDC page that we link. Both links lead to the same page. Alternatively,  if we can jump link to specific parts of the page (i.e. the section on pregnancy or breastfeeding), I would suggest adjusting the links to specify pregnancy or breastfeeding for the appropriate bullet point. I also added “on the CDC website” since we are linking to an external site and made the link in the bullet point about breast feeding sentence case.
11. For their new bullet point on breastfeeding, I’m wondering if we need to start the second sentence with “Recent reports suggest…” as that is mentioned on the linked CDC page? I'm flagging this because other sections of this page seem to reference “data” when stating facts about how the vaccine may impact the person getting a vaccine.  I left this as is for the time being.  I also adjusted “which could help” to “may." Also, and if possible, would we consider adding "protect their babies against COVID-19" to specify what babies are potentially protected from? 

Also, an additional note that I noticed while on this page. In the bullet point “Experts believe that COVID-19 vaccines are safe for people who are pregnant…” People who are pregnant is used and the second second goes on to use “pregnant women.” Wondering if this needs to be changed to match the use of “pregnant people” on this page?

I'll update when I've made changes to the Coronavirus FAQs page!

**Comment by aliyahblackmore** [comment]
Hi @megzehn ! 

The Coronavirus FAQS page is ready for you! 

I confirmed with Randi that I needed to revert to the version right before the last published (11/29/22 - 4:38pm) and make these new updates. After you publish, Danielle will make her additional edits.

**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=3014

**A few notes:** 

- They used "shot" in the text right before the bulleted list. I changed this to "vaccine."

-I tried adjusting their bullet point to "You didn't get an updated...," but changed this to "You didn't already get an updated..." because I wasn't sure if I was changing the meaning at all by leaving out "already." Open to thoughts here! I'm leaning more towards "You didn't get an updated..."

- I also noticed that the link text in this section had no edits from SMEs, but following the other changes it seems like we'd need to change "booster shot" to "updated vaccine?" I left this as is considering the H1 on that [linked page](https://www.va.gov/health-care/covid-19-vaccine/booster-shots-and-additional-doses/) still uses "booster shots," but wanted to flag this!

**Comment by megzehn** [comment]
Thank you, @aliyahblackmore! I published your changes. Good question about changing the link text. I think it makes sense to have it match the header for now -- like you said --  but we could bring that up with Danielle next time we publish changes on this page.

**Comment by megzehn** [comment]
Thank you, @aliyahblackmore. Great call-outs and suggestions. I changed "hospitalization" to "severe illness" and "pregnant women" to "pregnant people" as you suggested for consistency with our page. 

I also moved up the note about "It's always your choice..." as we discussed. 

And finally, I changed these 2 broken links:

[Learn more about COVID-19 vaccine effectiveness on the CDC website] https://www.cdc.gov/coronavirus/2019-ncov/vaccines/effectiveness.html
[Learn more about the Janssen vaccine on the CDC website] https://www.cdc.gov/coronavirus/2019-ncov/vaccines/safety/JJUpdate.html#symptoms-list-question
Node: 34627

to these:

[Learn more about COVID-19 vaccine effectiveness on the CDC website] https://www.cdc.gov/coronavirus/2019-ncov/vaccines/effectiveness/index.html
[Learn more about the Janssen vaccine on the CDC website] [https://www.cdc.gov/coronavirus/2019-ncov/vaccines/safety/JJUpdate.html#symptoms-list-question
Node: 34627](https://www.cdc.gov/vaccines/covid-19/info-by-product/janssen/index.html)

@RLHecht, all 3 of these pages are now published with the updated changes. Thank you!

**Comment by RLHecht** [comment]
Closing this ticket. I created a new one to send the translations out.
