### ISSUE TITLE
[BE] Report 404 to front end when refresh-precheckin returns 404

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#53166]
## User Story
As a Veteran, I wish to see relevant error messaging when I try to load an expired pre-checkin link, so that I can know I don't have any other tasks to complete.

## Tasks
- [ ] [BE] Report 404 to front end when refresh-precheckin returns 404

## Acceptance Criteria
- [ ] vets-api returns 404 for GET session when calling with a missing UUID
- [ ] Deployed to staging
- [ ] Tested on staging
