### ISSUE TITLE
MDT- Order confirmation page- Code

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5317]
## User Story:
As a developer, I need to code the Order Confirmation page so that I can complete the MDT ordering process.

## Tasks
- [ ] code the Order Confirmation page
- [ ] confirm design from the Design team. 
- [ ] code page elements. 
 
## Acceptance Criteria:
Order Confirmation page's content is displayed: 
UI is approved by the design team
UI matches the UI elements in the Design library system. 
Get url of components??
UI is approved by the DLC team

## Next Steps
- 2 PR
- FE review
