### ISSUE TITLE
Support: Mon-Thur Deploy (S21)

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#53179]
### User stories
As a Platform team member who just contributed to the Platform website,
I need my content published,
so that I can share my content updates with the intended audience.

As a content team,
we need to review any new content changes made on the platform,
so that we can deploy every Tuesday and Thursday of the week.

### Tasks
Someone from our team will use Scroll Viewport to publish changes to the website after 3pm EST on:

- [x] Wednesday (2/15) - Samara
- [x] Thursday (2/16) - Jill
- [x] Monday (2/20) - Lauren
- [x] Tuesday (2/21) - Brian
- [x] Wednesday (2/22) - Jill (swap for Samara)
- [x] Thursday (2/23) - Samara (swap day)
- [x] Monday (2/27) - Jill (swap for Lauren)
- [x] Tuesday (2/28) - Brian

### Other Info
Rotating schedule:
https://vfs.atlassian.net/wiki/spaces/CIT/pages/2405171201/Deployment+rotation+schedule

Data tracking info:
https://vfs.atlassian.net/wiki/spaces/CIT/pages/2282979860/KPIs+-+Content+Support
