### ISSUE TITLE
Update language for Edith Nourse STEM Scholarship on program page and other education pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#53196]
## Issue Description

Tammy Hurley asked us to make a change to the intro of our [Edith Nourse Rogers STEM Scholarship](https://www.va.gov/education/other-va-education-benefits/stem-scholarship/) page. 

We should change the sentence to the following (bolding to point out change):

The Edith Nourse Rogers Science Technology Engineering Math (STEM) Scholarship allows eligible Veterans **using the Post-9/11 GI Bill or dependents using the Fry Scholarship to get added benefits**. 

We also need to update this anywhere else we have this content. It also appears on [Other VA education benefits](https://www.va.gov/education/other-va-education-benefits/) page and [About GI Bill benefits](https://www.va.gov/education/about-gi-bill-benefits/). 

We should use the CMS audit tool to check if there are any other pages.

## Tasks
- [x] Update content on Drupal pages (Katherine)
- [x] Search in Drupal for other pages that has this content (Katherine)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Updated content is live on the site

**Comment by katherine-fung** [comment]
STEM Scholarship page: 
http://preview-prod.vfs.va.gov/preview?nodeId=6860 

Other VA education benefits page: 
http://preview-prod.vfs.va.gov/preview?nodeId=945

**Comment by megzehn** [comment]
Thanks, @katherine-fung! I'll check these off as I review and publish them. 

- [ ] STEM Scholarship page (change in the page intro):
http://preview-prod.vfs.va.gov/preview?nodeId=6860

- [ ] Other VA education benefits page:
http://preview-prod.vfs.va.gov/preview?nodeId=945

- [ ] Getting a GI Bill extension
http://preview-prod.vfs.va.gov/preview?nodeId=41926

- [ ] Post-9/11 GI Bill (change in the link summary at the bottom of the page)
http://preview-prod.vfs.va.gov/preview?nodeId=935

- [ ] Fry Scholarship (change in the link summary at the bottom of the page)
http://preview-prod.vfs.va.gov/preview?nodeId=951

- [ ] About GI Bill (change in the link summary at the bottom of the page)
http://preview-prod.vfs.va.gov/preview?nodeId=915

**Comment by megzehn** [comment]
@RLHecht, these changes have been published! Thanks!

**Comment by RLHecht** [comment]
These pages are live. Closing ticket!
