### ISSUE TITLE
[Design] Review profile documentation for mentions of users 36 and 11

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#53206]
### Background

After we launched the fiduciary/is deceased flag updates that hide the profile for anyone with the fiduciary/incompetent/deceased flags, we realized that users 36 and 11 are returning these indicators from EVSS. This means that they can no longer see the profile based on the new logic.

Since we used to rely on these users prior to the logic change, we need to review all of our use case documentation for mentions of these users, and replace them where necessary.

### Tasks

- [x] Review all profile use case documentation for mentions of user 36 and user 11
- [x] Where found, replace with other staging users 
- [x] Add users 11, 36, and 233 to the documentation we have on users with the fiduciary/incompetent/deceased flags

### Acceptance criteria

- [x] Documentation has been updated as needed

**Comment by andaleliz** [comment]
I'm starting to work on this since I had to document these for the account security updates I'm working on in #52502. We have a lot of instances where "Any LOA3 user" is available to test a certain use case. Is the expectation that it should now read "Any LOA3 user except 11, 36, and 233"? I'm wondering if a more long-term solution is to  find specific users for those use cases, because the exception list will be difficult to maintain over time.

**Comment by Samara-Strauss** [comment]
As we talked about in standup, Idk if there is a perfect solution to this. Another idea we didn't talk about was listing a small number (3?) of specific users, and making a note that most users should see that functionality unless their profile is otherwise blocked.

**Comment by andaleliz** [comment]
The docs are all updated.  In places where it made sense (which turned out to be most), I linked to the relevant section in our test case documentation.  Elsewhere, I specified the exclusion of users 11, 36, and 233
