### ISSUE TITLE
Research Veteran Verification against MPI

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#5321]
## User Story:
As the Caregiver team, we need to research how we could go about verifying veteran identity prior to form submission so that the program team can confirm that all online form are submitted by identified Veterans. 

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [x] Research MPI
- [ ] Design approach for Veteran verifcation
- [ ] Approach is documented in Github
- [ ] Approach is approved by stakeholders
- [ ] Tickets are documented in Zenhub

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
* Plan is in place to verify veteran identity prior to form submission
* Tickets are created

## Configuration
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinmirc** [comment]
**Summary**:
We can use the veteran’s information, on the 10-10CG form submission, to search MPI for their profile. Their profile should be there even if they have not registered an account on VA.gov.

We’d use the ICN to search eMIS for veteran status and other service information. We can then either (1) use business logic to filter out the application or (2) attach the additional veteran context to the information that is submitted to CARMA.

**Other Findings**:
- MPI is not just populated by website registrations. The DoD also seeds MPI with profiles; meaning veterans can be MPI even if they have not registered an account on VA.gov.
- MPI can be searched with the veteran's PII provided on the form submission (given_names, family_name, birth_date, ssn, and gender).
- Finding an identity in MPI does not verify that the veteran is a veteran. We must use the MPI profile identifier (ICN) to then search eMIS to get the military and service information of the veteran.
- eMIS can tell us all sorts of information on the veteran, their status, their service history, which eras they served and more. * We need to identify what's needed for application processing.

**Suggested Workflow**:
Since there are cases of legitimate applications where the veteran is not our systems, **and** the veteran verification isn't a procedural process that can be programmed (for the purpose of 10-10CG), I don't believe an application for the veterans in our systems, should be handled differently from the ones _not_ in our system.

I suggest that **all** application be submitted CARMA digitally, but we add an intermediate step for data enrichment. Before sending the submission to CARMA, we attach veteran's service information, when possible. If the veteran cannot be found in our systems, we add a flag to the submission indicating which systems do not have the provided veteran.

The flag will serve as an indicator to CARMA that this application may not be legitimate.

**Alternative Workflows**:
If the Caregiver Program office insists on receiving the applications where the veteran can’t be found, by mail, we have these alternative options:

Once the form's data is valid (**Successful Flow**):
- We fetch the veteran's profile in MPI using the veterans PII provided on the form.
- Using the MPI profile's ICN, we search eMIS to get the military service information and attach any data that is required for the back office to process the application and verify the veteran's status.
- We then submit to CARMA the form's data **with** the additional veteran's military service context.

If a profile cannot be found in MPI (**Error Handled Flow**): 
- We can return a 400 (client) error notifying the end-user that the veteran cannot be found in the VA's systems. The end-user should be prompted to double-check that the information on the form was entered correctly and is accurate.

  The user can then either:
    - (1) Be instructed to fill out the paper form and mail it to the VA (please don't make me build this).
    - (2) Be prompted to generate a PDF with a button click (Using the data in the digital form, we can fill out the PDF version of the 10-10CG programmatically. Then return the document to the end-user to download and mail in - Additional security measures need to be considered).
    - (3) Accept the application. Instead of sending it to CARMA digitally, we fill out the paper form in the background and then send it to the VA's Central Mail programmatically (*this is the optimal workflow if the Caregiver Program requires these types of applications to be submitted by mail).
