### ISSUE TITLE
PE-MVP Usability Test: Create Draft Conversation Guide

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#53218]
# Description
In order to conduct usability test sessions effectively, the moderator should be properly prepared for conversations about topics/areas that they may not be directly familiar with. A conversation guide will help the moderator be more informed and prepared to manage responses effectively in these sessions. This ticket will focus on creating a draft document for later refinement as the MVP is more solidified and a schedule is known.

# Tasks
- [ ] Create a page to host the research plan in Confluence, based on the Conversation Guide template [here](https://vfs.atlassian.net/wiki/spaces/DCP/pages/1474494518/TEMPLATE+Platform+Conversation+Guide)
- [ ] Populate and refine this page until it's complete and ready for review
- [ ] Review w/ PM & TL

# Acceptance Criteria
- [ ] A complete draft conversation guide has been documented and is ready for refinement as MVP details are more solidified

**Comment by LillyBoot** [comment]
Started laying out my ideal testing flow

**Comment by LillyBoot** [comment]
Link to conversation guide draft: https://vfs.atlassian.net/wiki/spaces/~63d7ed0df1475ad42c577ae0/pages/edit-v2/2538831873?draftShareId=3fc1f50c-943b-4e58-b8f0-f3bd91e3ee8c

**Comment by JoeTice** [comment]
Draft is reviewed/approved 2/28/23 - further refinement will be done next sprint
