### ISSUE TITLE
Review of live Spanish-translated COVID pages 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#53211]
## Issue Description

Now that our Spanish-version COVID-19 pages have been live for a long time without having our volunteer translation team reviewing content, we need to do our own review to make sure content is consistent and error-free. Some examples include where we're using sentence casing vs. initial caps, using the same term for things like "Note," and punctuation.

Pages to review:

- [Coronavirus FAQs](https://www.va.gov/coronavirus-veteran-frequently-asked-questions-esp/)
- [COVID-19 vaccines at VA](https://www.va.gov/health-care/covid-19-vaccine-esp/)
- [About COVID vaccines](https://www.va.gov/health-care/covid-19-vaccine-esp/about-covid-19-vaccine-esp/)
- [COVID booster shots](https://www.va.gov/health-care/covid-19-vaccine-esp/booster-shots-and-additional-doses-esp/)
- [How to get your COVID vaccine records online](https://www.va.gov/health-care/covid-19-vaccine-esp/vaccine-record-esp/)

We need to document any changes that need to be made and we can then create a new ticket to implement these changes.

## Tasks
- [x] Review content (Ana)
- [x] Write up changes that need to be made (Ana)
- [x] Create ticket to implement changes (Randi)

## Acceptance Criteria
- [x] All Spanish COVID content has been reviewed

**Comment by ABeltran77** [comment]
Test

**Comment by ABeltran77** [comment]
https://docs.google.com/document/d/1Qi64PKHw4jh3jJXzYgj8JXK95pC-lYcU7ZqPmRph2Dc/edit?usp=sharing

**Comment by RLHecht** [comment]
@ABeltran77 It looks like the Word doc you linked might not be complete. I only see a few items from the FAQs page. Are there changes to more than that?

**Comment by ABeltran77** [comment]
Yes, there are...Let me see what I did wrong with the doc.

**Comment by RLHecht** [comment]
@ABeltran77 can you move your edits to a Word doc and post them here? i'm going to set up a separate ticket for making the changes in Drupal but I want to make sure Danielle is able to access these (VA can't work in Google docs). Thank you!

**Comment by ABeltran77** [comment]
Yes

**Comment by ABeltran77** [comment]
[https://app.zenhub.com/files/133843125/9c6c9fa4-39d5-422c-a520-18fc005ad007/download](https://app.zenhub.com/files/133843125/9c6c9fa4-39d5-422c-a520-18fc005ad007/download)

[https://app.zenhub.com/files/133843125/1334a49c-2909-4af2-bf21-708340a47cfc/download](https://app.zenhub.com/files/133843125/1334a49c-2909-4af2-bf21-708340a47cfc/download)

[https://app.zenhub.com/files/133843125/2337857e-bda9-4764-95e8-07de2a0d5bd5/download](https://app.zenhub.com/files/133843125/2337857e-bda9-4764-95e8-07de2a0d5bd5/download)

[https://app.zenhub.com/files/133843125/3bc60d3f-4515-4e89-a912-5c0cfd0bf2ac/download](https://app.zenhub.com/files/133843125/3bc60d3f-4515-4e89-a912-5c0cfd0bf2ac/download)

**Comment by RLHecht** [comment]
Closing this ticket as I've set up a new ticket to implement these changes.
