### ISSUE TITLE
PE-MVP Usability Test: Conduct Pilot Session

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#53221]
# Description
Before releasing to a wider audience, we'll conduct a single pilot session with the Preview Environment MVP.

# Tasks
- [ ] Recruit participant
- [ ] Conduct usability test session
- [ ] Review findings and notes to determine if any additional changes are needed prior to scheduling remaining sessions

# Acceptance Criteria
- [ ] Pilot session has been conducted
- [ ] Results have been reviewed and a determination made

**Comment by JoeTice** [comment]
This MVP didn't end up having usability testing - these tickets are no longer viable
