### ISSUE TITLE
[Research] Profile | My VA | UX Improvements: Heuristic Review and Analysis of Profile and My VA

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-team#53227]
## Problem Statement
As the Authenticated Experience team, I'd like to understand the gaps in the existing design of the My VA and Profile sections relative to UX best practices so that I can understand opportunities for improvement, and how those opportunities might be prioritized.

## Background
This heuristic review and analysis is in support of the Authenticated Experience team objective of "Maintenance & UX Improvements" and the OCTO objective of "Enhance veterans' personalized online experience" ([link to 2023 goals & roadmap](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/roadmap/2023-goals-roadmap.md))

[Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1679590080949/193acbf93132f4f1719dbcbc5b11b25af682c2c8?sender=ua13e567cb5c4221acaa14949)

## Tasks

- [x] Meet with Liz and Angela
- [x] Conduct the review
- [x] Create write-up
  
## Acceptance Criteria
- [x] Easily consumable visual that highlights the opportunity for improvement relative to UX best practice
- [x] Each opportunity mapped to at least one usability heuristic from a credible source

## Validation
_Who can validate this ticket? (FE, BE, Design, PM)? N/A_
_How can this work be validated? N/A_
_What updates need to be made (e.g. product outline, use cases, contact center guide)? N/A_

**Comment by Samara-Strauss** [comment]
A good first step for this would be to talk to Angela and Liz, since they have background on both the My VA product and profile section and how/why things are designed the way they are. That doesn't mean there aren't areas for improvement! But context is always important, so I think a conversation with them would help to give necessary context.

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 and @fmccaf1 to schedule chats with @aagosto90 and @andaleliz to learn more about My VA product and profile section and how/why things are designed the way they are.

**Comment by BerniXiongA6** [comment]
Hi @fmccaf1  will any of this work carry over and if so do you have an estimate of how many points are left?

**Comment by fmccaf1** [comment]
If possible, I'd love to meet with @Samara-Strauss and discuss this work and potential next steps.

**Comment by Samara-Strauss** [comment]
Responded in Slack! Let's set up a time before I'm out.

**Comment by fmccaf1** [comment]
### Summary of findings
@Samara-Strauss @BerniXiongA6 @andaleliz @aagosto90 

1. Prioritize the most important: What is most important for Veterans to see on each screen of Profile and My VA? What if anything, can be removed from Profile and My VA to elevate the truly most important information? Part of this is also having a clear reason (and offering a clear understanding to users) for why each thing is on the page. 
2. Revisit CTA placement and text: What CTAs make sense within AE products, given what people are thinking and doing on these pages of the site? Also, where should CTAs live and how can they be better integrated to the products to seem less randomly placed?
3. Improve UX visual patterns: How might we improve consistency and make affordances clearer by improving some visual patterns? For example, we're lacking some distinction between fields that can and cannot be edited and in some cases we use text descriptions to tell users how to use the interface, which shouldn't be necessary for the simplistic level of interaction needed on these screens.
4. Revisit use of term "gender identity": The phrase "gender identity" could be an unnecessary source of complicated / uncomfortable emotions for users. We could avoid that and do everything needed here by simply calling this section "Gender."
5. AE products = the personalized VA experience: It is confusing that personalized information is the focus of Profile and My VA, but personalized information can also live anywhere on the VA.gov site. We have the power to greatly improve the logged in experience by surfacing all personalized information in one place (and this would also follow commonly used standardized usability practices). In addition, instead of sending users around VA.gov to find their personalized info, could we surface more of that right within the AE products?
6. (Related to point 5) Consider combining Profile and My VA: Why keep My VA and Profile separate? How does the separation of these products support users' mental model or help users complete tasks?

**Comment by Samara-Strauss** [comment]
Thank you for this, @fmccaf1! I wanted to include some notes around how I am processing your summary, in hopes that it will help us guide next steps.

### Product/Strategy questions

> Why keep My VA and Profile separate? How does the separation of these products support users' mental model or help users complete tasks?

### IA questions

> What is most important for Veterans to see on each screen of Profile and My VA? What if anything, can be removed from Profile and My VA to elevate the truly most important information?

> the personalized VA experience: It is confusing that personalized information is the focus of Profile and My VA, but personalized information can also live anywhere on the VA.gov site. We have the power to greatly improve the logged in experience by surfacing all personalized information in one place

### Interaction design questions

> What CTAs make sense within AE products, given what people are thinking and doing on these pages of the site? Also, where should CTAs live and how can they be better integrated to the products to seem less randomly placed?

> How might we improve consistency and make affordances clearer by improving some visual patterns? For example, we're lacking some distinction between fields that can and cannot be edited and in some cases we use text descriptions to tell users how to use the interface, which shouldn't be necessary for the simplistic level of interaction needed on these screens.

> The phrase "gender identity" could be an unnecessary source of complicated / uncomfortable emotions for users. We could avoid that and do everything needed here by simply calling this section "Gender."

### Next steps

- **Explore some of this in the ongoing notifications work and IA/nav research and work**
  - We already know from previous research that action items and relevant updates are the most important things veterans want to see upon logging in. Our continued work around notifications can help us figure out how we can do this in a way that iteratively grows our products -- and VA.gov as a whole.
  - We also have had open questions for a while on the relationship between My VA and the Profile (their purposes are clear; site organization and separation are different questions) and what's included in the profile vs. what is found throughout the rest of the website. Overall organization is something we will hopefully explore and improve through the logged-in IA/nav research.
- **Explore some of this in future research to validate what actually is or is not a problem**: There are some points brought up in the analysis that we should further explore to understand how much of a problem they are (or not). Example: we haven't heard issues or confusion around CTAs, and the term "gender identity" didn't cause issues in our research before launching this field (we did not specifically ask about this, and it's possible that people would prefer "gender"). It's not that these aren't valid points to bring up -- they are! -- but let's validate our assumptions before moving forward.
- **Get updates into the backlog that we feel confident enough about that don't need additional research - Is there anything that's pretty clearly something we can just go ahead and implement? For example, I remember we talked about why these FAQs aren't paired with the fields they are talking about. We should just make an update like this, and if there are similar improvements that are pretty clearly the right move, let's get them into the backlog: 
![image](https://user-images.githubusercontent.com/34068740/229184995-2b89edc4-9802-4d0e-a1db-5c3ca91c087c.png)

### Other thoughts

> some cases we use text descriptions to tell users how to use the interface, which shouldn't be necessary for the simplistic level of interaction needed on these screens.

It probably depends on the example, but I think some of this has to do with accessibility, and others may have to do with recommendations from content or feedback we received in user research. We might want to review this on a case-by-case basis and see if we can recall why something was designed the way it was. And even if there was a good rationale at the time, that doesn't mean there isn't room for change. I just want us to be sure that it's OK that we change/update something before we do (ie. it's not going to go against accessibility best practices or cause user confusion).

**Comment by Samara-Strauss** [comment]
Thank you for listing out each insight in your original post! Here are my thoughts on how to address each:

## Things to explore through onsite notifications work

> Serve up whatever is new or needing attention as the first thing(s) users see in My VA, regardless of categories
> Use name tag space to highlight something that has changed or is likely to cause issues when incorrect

## Things to explore through IA/navigation work

> Consider re-ordering info in profile based on what is most error-prone / most likely to cause problems if it's incorrect or not filled in
> Think about the fields that are helpful to users and drop everything else, i.e. are legal name and date of birth helpful in profile? What do users need them for?
> We could do a better job of figuring out and integrating which tasks can be grouped into a personalized experience, this should include:
> - Include dd214 and other documents / letters here
> - Surfacing information directly in profile or My VA instead of sending users elsewhere
> - I believe this doesn't need research to know that this would bring about an improved user experience. We have lots and lots of examples from the real world where this approach is used (think: websites for banks, schools, etc) and no examples (that I can think of) where the current VA.gov approach is a standard

## Things that we might want to explore further to determine if they are/are not problems 

> Increase visual distinction between fields that can be edited by the user in the UI and fields that cannot (and possibly include explanations for why they cannot be edited)
> We could make this much less polarizing immediately and have the exact same meaning just by calling this "gender"

## Things we should just go ahead and implement/get into the backlog

> Link to profile (from My VA) may be getting overlooked according to research sessions

## Answers to your questions

> Curious about the use case for dividing profile direct deposit section up based on benefit. Why is this helpful for users?

Unfortunately, VA made a decision well before our time to have one backend support direct deposit for disability compensation & pension benefits and a completely separate backend for direct deposit for education. This, as you might have guessed, had to do with existing organization silos, where each "business line" doesn't really talk to each other. So, we have to account for this on the frontend. In an ideal world, there would be one system supporting direct deposit, but reconciling this is out of the purview of our team.

> Also curious about why the VA needs addresses in addition to mailing address (same for phone numbers). And, is it really helpful to show all addresses we have on a user from the user's pov?

Home and mailing address are relevant because of use cases like (1) PO Boxes and (2) People who live in different places at different times of year. Besides that VA sends a lot of mail, this is especially relevant to people who receive prescriptions by mail from VA (which is the primary way people receive prescriptions through VA).

As for phone numbers, I don't have evidence either way that we need to show all the phone number options, but I would advocate us being more upfront and showing what we have.

> Why keep My VA and Profile separate? How does the separation of these products support users' mental model or help users complete tasks?

As I mentioned on our call earlier, the goal for My VA is for it to become the true logged-in homepage. If this happens, I think that lessens the association between My VA and the profile quite a bit. However, the broader point that we need to do a better job elevating personalized tasks and tools is understood, and hopefully what we'll be addressing and improving as a follow-up to Liz's research.

## Questions I have

> I think we could better integrate CTAs into the profile by placing them closer to the fields they are specific to or just think about placement / wording to make them seem less random

What are specific examples of this? I'm unsure how to address this because I'm not quite sure what this is in reference to.

> Confusing to have "you have no claims to show" followed by cta: "manage all claims and appeals"

So people may not have claims in flight currently, but have had claims previously that are now closed. That's why we keep the "manage all" link there. Do you have ideas on how we could make this better given that context?

>Curious about the different CTAs and how the team decided to include them. For example, do users go to My VA to apply for healthcare?

I wouldn't say that users go to My VA specifically to apply for health care, but this is supposed to be a landing/launch pad for their site experience, so we want to get them to primary tasks associated with the most popular benefits.

> Two-step editing process started by clicking a button seems unnecessarily complex for such a simple interaction

What is this in reference to? It sounds like something we should address, but I'm not sure what field this is in reference to.

> Need for text to explain how to edit fields also seems unnecessary, or else is a good clue that this interaction is overly complicated

What is this in reference to?

**Comment by fmccaf1** [comment]
Thanks @Samara-Strauss for going back and forth here. Sorry I was still unclear on my second try. Trying again for (hopefully) the last time: 

> I think we could better integrate CTAs into the profile by placing them closer to the fields they are specific to or just think about placement / wording to make them seem less random

> What are specific examples of this? I'm unsure how to address this because I'm not quite sure what this is in reference to.

See screenshot from [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1679590080949/193acbf93132f4f1719dbcbc5b11b25af682c2c8?sender=ua13e567cb5c4221acaa14949):
![image](https://user-images.githubusercontent.com/106624475/230465043-b757f5a5-c00d-4e2b-aa3f-fab10f527946.png)


> Confusing to have "you have no claims to show" followed by cta: "manage all claims and appeals"

> So people may not have claims in flight currently, but have had claims previously that are now closed. That's why we keep the "manage all" link there. Do you have ideas on how we could make this better given that context?

I do have ideas! One is to instead use text: "You have no claims currently in process." And a CTA with text: "Manage all past claims and appeals."

That being said, I think design work is much more interesting when we let the ticket state the problem and the designer that picks it up can address it as they see fit. At least for me, that makes it feel like I'm using my brain much more in my day-to-day work as opposed to picking up a ticket that says "do x exactly in this way." But, I understand that's not generally how our team runs work.

> Two-step editing process started by clicking a button seems unnecessarily complex for such a simple interaction

> What is this in reference to? It sounds like something we should address, but I'm not sure what field this is in reference to.

>Need for text to explain how to edit fields also seems unnecessary, or else is a good clue that this interaction is overly complicated

>What is this in reference to?

See screenshot from [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1679590080949/193acbf93132f4f1719dbcbc5b11b25af682c2c8?sender=ua13e567cb5c4221acaa14949):
![image](https://user-images.githubusercontent.com/106624475/230464723-6df6e2df-f939-49f8-a938-75dbf064d953.png)

**Comment by Samara-Strauss** [comment]
Thank you for this!

1. For the update to move "How to update your legal name" and "How to fix an error with your name or date of birth", let's get a ticket into the backlog to move those into the boxes for their respective fields.
2. Re: the "You have no claims to show" problem -- I think this is work bringing up to Angela/the team to discuss if others feel this is confusing and/or how we can finesse the copy in just the right way to make sure there is definitely no confusion.
3. For "Choose to edit a preferred name/gender identity", I forget if this copy is there for accessibility reasons, OR if this copy allows us to communicate a blank state without having to change buttons from "Add" to "Edit". Can you check with Liz about this? She was not the designer on the project, but she can probably answer questions around accessibility and blank states.
