### ISSUE TITLE
Update General Support Responsibilities to include information about what Slack channels to continuously monitor

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#53235]
## Issue Description
As a member on the Support Team, I need a list of the DS@VA and Oddball Slack channels that I should monitor throughout the day, with information about how to Star a channel and get all notifications.

Related Slack link - https://oddball.slack.com/archives/C0459AQ5GBT/p1675781176119069

---
## Tasks
- [x] Update the [Responsibilities](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2502426757/Responsibilities) Confluence doc to include a list of Slack channels to monitor throughout the day
- [x] Include information on how to Star a channel and get all notifications from a channel

## Acceptance Criteria
- [x] Slack channel list is complete
- [x] Included information on how to Star a channel and get all notifications from a channel
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by holdenhinkle** [comment]
Estimate should be a 1, but 1 is not available from the dropdown.

**Comment by holdenhinkle** [comment]
[Done](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2502426757/Responsibilities#Slack-Channels-to-Star-and-Monitor-Throughout-the-Day).

![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/e0ec8a1f-c173-460d-8b47-f403311a008b)
