### ISSUE TITLE
508 Findings for Pre-Launch 508 review for address validation

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5323]
## Background

The authenticated experience team has added a feature to the VA.gov profile mailing address field that will run a check on all addresses that are submitted to determine how likely it is that the US postal service will be able to deliver mail to them. If the address validation functionality determines this address is likely real/deliverable, we'll save the form just as we do now. However, if the address validation functionality determines that an address may be problematic/not deliverable, we let the user know and show suggested addresses if we have them.

## Resources

- You can view this by logging into staging, going to the VA.gov profile, and editing the mailing address field. https://staging.va.gov/profile/
- You can use any staging user since they all are LOA3 and have access to the profile.
- If it's helpful, this is the [link to Tze's QA test plan](https://dsvavsp.testrail.io/index.php?/plans/view/28). He can give you the login credentials if you need them.Please note this data is all made up and does *not* include PII.

## Tasks

- [x] Complete pre-launch 508 review for the address validation feature.
- [x] Create bug/update tickets as needed, and assign to Samara for triage.

## Acceptance criteria

- [x] 508 review is complete and all bug/update tickets have been created.

**Comment by Samara-Strauss** [comment]
@1Copenut let me know what your bandwidth looks like for this over the next couple of weeks. I know you have a lot of work to do so we can accommodate whatever timeline works for you.

**Comment by jenstrickland** [comment]
@Samara-Strauss — I'm the person who will handle VSA reviews.

**Comment by Samara-Strauss** [comment]
@jenstrickland noted! @1Copenut was preassigned to the ticket when I [clicked the link from here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/vsa-accessibility-review-process.md#development-reviews) (the *request a 508 Pre-launch Review* link under **2. 508 Pre-launch Review Checkpoint** , so sorry and noted for the future. I'll assign you.

**Comment by jenstrickland** [comment]
We both get automatically assigned, but I'm here especially for VSA people.
Trevor and I are doing a lot of work in tandem, because we each bring
compatible skills. Trevor is very familiar with the dev environment, so
he'll have recommendations for different components and such. I'm still
awaiting the opportunity to get in there. I bring a lot of design,
research, product, and front-end expertise. Aiming for zero errors in
Pre-Launch 508 Reviews for all VSA teams.💪 😁

**Comment by Samara-Strauss** [comment]
Sounds good. Thanks!

**Comment by jenstrickland** [comment]
@Samara-Strauss - I wanted to give you an update on this review progress. I encountered a number of issues, but am evaluating which to include here and which belong to other teams. Apologies for the delay! It's a complicated audit, since the majority of your team's effort is in the modal, which is not evaluated in any of the e2e or automated testing. I hope to wrap this audit up in the next two days.

**Comment by Samara-Strauss** [comment]
Great, thank you for the update @jenstrickland!

**Comment by Samara-Strauss** [comment]
Hey @jenstrickland — checking in for a status updates. Are there additional tickets our team should expect?

**Comment by jenstrickland** [comment]
@Samara-Strauss there will be a couple. Earlier today with Trevor I reviewed half the list of items I found, as I believe the majority of them are for the design/forms systems teams. I expect to write up the issue tickets on Thursday morning. Sorry for the delay! The modal nature of this proved to be a particularly different item to audit.

**Comment by Samara-Strauss** [comment]
Thank you @jenstrickland! No need to apologize. Thank you for following up. I'll look for those additional tickets tomorrow.

**Comment by jenstrickland** [comment]
Created ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/5871 and sent to the sitewide / triage team regarding content order in the modal component.

**Comment by jenstrickland** [comment]
Created ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/5875 and assigned sitewide / triage team regarding error message reading upon entry of each character in Zip Code input.

**Comment by jenstrickland** [comment]
The accessibility audit is complete. cc @Samara-Strauss @mshea0606  Please let me know if there are any questions.

**Comment by Samara-Strauss** [comment]
Thanks @jenstrickland! These are the tickets that came out of this for our team:

- #5846 (Handling this now even though it's not address validation specific)
- #5861 (Put in backlog because it's not address validation specific)
- #5865 
- #5866 

For #5871 and #5875 — are there people to take on this work, or should we add those tickets to our backlog as well? Let me know. Once we square that away, I'll close this out!

**Comment by Samara-Strauss** [comment]
Actually, just gonna close this. @jenstrickland let me know if you need my team to handle #5871 and #5875. Otherwise, thank you for all your help! We appreciate it!

**Comment by Samara-Strauss** [comment]
@jenstrickland why did you reopen this?

**Comment by jenstrickland** [comment]
@Samara-Strauss In order to open the ticket about focus returning to the Edit button that launched the modals and assign it to the 508 Findings for Pre-Launch 508 review, I needed to reopen, as the epic was not available to attach the issue to.

**Comment by Samara-Strauss** [comment]
> I needed to reopen, as the epic was not available to attach the issue to.

The additional work in #6156 is not related strictly to address validation and is a general ticket for the profile, so this is the wrong place/epic to attach it to. I'm closing this ticket. If you need another epic for the #6156, you can attach it to the Profile 2.0 work. Epic is #2086.
