### ISSUE TITLE
Create a basic and updated user flow 

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#53259]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
 
We currently have a user flow diagram on Mural specifically representing the [List Loop Redesign Flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/vsa8243/1651159117540/2a19b7d20abbc52f219a14e52d786eb22af0457b?sender=ue0461b50c52704882a301396). 

- **We are creating a more comprehensive user flow from Veteran's point of entry to FSR all the way to completion of FSR form. This new and updated user flow will give us a more comprehensive bird's eye view of the entire process. This user flow will serve as a visual to help facilitate conversation during the heuristic evaluation workshop. It is a necessary step for workshop planning. Team members will be able to refer to the user flow now and in the future. ** 

---
## Tasks
- [x] _What work is necessary for this story to be completed?_
- Create the user flow in Sketch App and share with core team. 

## Acceptance Criteria
- [x] _What will be created or happen as a result of this story?_
- A user flow diagram. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mgleo** [comment]
@HeatherRienks @denisecoveyduc This is an unplanned ticket added to Sprint 92 that will assist with Research Planning and Heuristic Workshop.

**Comment by mgleo** [comment]
[**DRAFT** Debt Portal to FSR User Journey - Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1675866231768/ae9ff969ee9b909eb69aa657e747f3478a712692?sender=ua78f969c4cddcbfe56b27885)
[**DRAFT** FSR User Journey - Sketch](https://www.sketch.com/s/6418142a-1baa-4e1e-ae53-4af7f675427c)

We will pause on this for now. In the future we need to 
- Define goals for user journey artifacts
- Create user journey maps in Mural based on goals

**Comment by HeatherRienks** [comment]
@denisecoveyduc - I am going to move this to closed so it accurately reflects that we completed this in Sprint 93, before it rolls over into the new sprint in a few hours. :)

**Comment by denisecoveyduc** [comment]
@HeatherRienks Thank you Thank you!!
