### ISSUE TITLE
Find cause of not found Veteran identifiers in IAM

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#53262]
## Issue Description
There were 600 user CSPIDs that were not found by the IAM team when pulling the records for the VBMS audit. We need to find the provider these CSPIDs were pulled from and determine a reason why they were not found or if they are still valid.

---
## Tasks
- [x] Create script to find user account and identity provider
- [x] Connect with identity team to discuss theories

## Acceptance Criteria
- [ ] We are able to report the results to IAM 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Delivered list of ICNs of not found users to IAM team. Awaiting confirmation they found MPI records using them.

**Comment by HeatherRienks** [comment]
@ScottyRJames - do you have any updates on this? 

cc: @denisecoveyduc

**Comment by ScottyRJames** [comment]
@HeatherRienks Have not heard anything from IAM. I believe Jill was going to followup with Danny soon.

**Comment by HeatherRienks** [comment]
@ScottyRJames - ok, I will ping Jill in Slack to see if she has updates for us. Thanks!

**Comment by denisecoveyduc** [comment]
Here is the slack thread where we asked Jill. https://dsva.slack.com/archives/CPE4AJ6Q0/p1677610399794719

**Comment by HeatherRienks** [comment]
Per Jill on 3/2/23: "Yes, we got the file and the team will be reviewing it."
