### ISSUE TITLE
Update Wireframes to remove reason for visit fields

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#53269]
## User Story
Update Wireframes to remove reason for visit fields (for both PCI and CI)

## Tasks
- [x] Create final mockups with callouts 
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [x] UI review meeting with product/UX team for feature capabilities
- [x] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.

## Wireframes

PCI collection (**Link updated**): 
https://share.goabstract.com/0388e7ee-0857-468f-8117-bdf38226e991?collectionLayerId&mode

CI collection (**Link updated**): 
https://share.goabstract.com/5fe16b1d-dd4d-4acd-8cb0-064736be0bec?collectionLayerId&mode

**Comment by benbrasso-agile6** [comment]
It looks great. 

Can we meet to talk a bit about check in? I think a couple of Ya-ching's wireframes are located somewhere else and we need to get them included here.

**Comment by benbrasso-agile6** [comment]
Looks good now, after bringing those two wireframes in from Ya-ching's work

**Comment by zach-park** [comment]
Here is the [collection](https://share.goabstract.com/09599f96-94b9-43b8-bc3a-14aa0e2a737c?collectionLayerId&mode) that Ya-ching's wireframes that she created: https://share.goabstract.com/09599f96-94b9-43b8-bc3a-14aa0e2a737c?collectionLayerId&mode

**Comment by zach-park** [comment]
@benbrasso-agile6 ,@ytsaoca 's wireframes (CI confirmations and appnt. detail) are included in the master branch now.

**Comment by sarahknoppA6** [comment]
this is currently behind a feature flag, so the feature is not "live" yet.

**Comment by benbrasso-agile6** [comment]
pre check in looks good
the check in doesn't look completed quite yet

**Comment by zach-park** [comment]
An incorrect check-in wireframe link was attached in the AC. Collection links were added with the correct wireframes.

**Comment by benbrasso-agile6** [comment]
lgtm, good to merge it with the main VAOS branches

**Comment by zach-park** [comment]
Merged to the VAOS branch and ticket is closed now.
