### ISSUE TITLE
Review disclaimer content for medical records domains

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#53268]
## Issue Description
MHV has a list of disclaimers that display on pages in Blue Button reports. We need to review the disclaimer content and work with the design team to determine how to display this in the new MR tool.

Then we'll need to edit this content for site style and plain language.

[Slack thread for context](https://dsva.slack.com/archives/C03Q2UQL1AS/p1675794835670059)

Current disclaimers: [https://app.zenhub.com/files/133843125/b3bfdbf2-d52d-49d1-83cb-f233e4904954/download](https://app.zenhub.com/files/133843125/b3bfdbf2-d52d-49d1-83cb-f233e4904954/download)

---
## Tasks
- [ ] Review existing disclaimer content
- [ ] Discuss options for how to display in new tool with design team
- [ ] Edit content

## Acceptance Criteria
- [ ] Disclaimer content is edited and incorporated in tool designs

**Comment by laurwill** [comment]
Update here: We discussed this with Coulton and Lichelle on a design collab session. We agreed that the current disclaimers contain several different types of information that serve different purposes. 

So instead of treating these as single chunks of content, we'll review the disclaimer text for each domain on a case by case basis. Then we'll update as needed to fit the new tool and suggest how to incorporate this info into the domain pages.

**Comment by laurwill** [comment]
@RLHecht , I think we can close this — we'll plan to address the disclaimers for each domain as part of the overall content review.
