### ISSUE TITLE
Build CARMA Service Authentication

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#5326]
## User Story:
As an application trying to connect to the CARMA/Salesforce backend
We need to build an authentication service
So that we can transmit data to CARMA securely.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] 

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
* 

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinmirc** [comment]
There is an existing Salesforce::Service module that we can use in order to handle authentication for the CARMA salesforce module. Waiting for the CARMA team to confirm that our interface will be a Apex REST service, allowing us to use the existing Salesforce::Service module for our auth workflow.
