### ISSUE TITLE
CoE | Update developer documentation

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#53278]
## Value Statement
**_As a_** dev
**_I want to_** update dev documentation
**_So that_** future teams understand how the code works.

---
## Background Context
- After the readiness review, we made a few changes that warrant updates to our docs.

## Acceptance Criteria
- [ ] Swagger docs updated
- [ ] Sequence diagrams updated

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by data-doge** [comment]
@saderagsdale Swagger docs are updated in production. I'll close this issue now.
