### ISSUE TITLE
Create content for app with appointments list 

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#53270]
## Description 

How might we...

1. Make pre-check-in and check-in look like one app?
2. While still focusing on highlighting any primary actions that Veterans need to be complete
3. And, allow Veterans to view all of their appointments (like VAOS does with their appointments list), including future and past

[Userflow options](https://app.mural.co/t/vfscie8528/m/vfscie8528/1674839426683/003e6f3c9bd04bab8a3c63f9e6111c61e4060a5e?sender=u83bc52d7fa73658f84f27755)

## Tasks

- [x] Write new or edit content 
- [ ] Review with UX team
- [ ] Review with CIE team 

## AC 

- [ ] Content was written 
- [ ] Reviewed with UX team
- [ ] Reviewed with CIE team

**Comment by kellysmith1008** [comment]
Duplicated [the workflow mural](https://app.mural.co/t/vfscie8528/m/vfscie8528/1676382110267) so I can edit the text freely. Will start work on this today and present to team when the first draft is done

**Comment by kellysmith1008** [comment]
I've completed the first draft of the content and will share with the UX team tomorrow during our sync. I'll make any updates needed after - this ticket should be closed by Friday.

**Comment by kellysmith1008** [comment]
Ran the draft of content past the UX team today in our sync and made changes/updates as needed from sync and design intent. This ticket is done
