### ISSUE TITLE
526ez | Send historical claim data

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#53273]
## Value Statement
**_As a_** developer
**_I want to_** securely send claim data to Veteran's e-folders
**_So that_** claims can be processed by the VBA. 

---
## Background Context
We've agreed on file formatting, method, and location. Next we need to coordinate steps to complete the transmission. 

## Tasks
- [x] Notify Steve Albers about the plan to transmit data, ask him to vouch for our approach
- [x] Get finalized de-dupped claim id list from VA/David Reis
- [x] Add code to make sure that failed historical pulls do not trip the EVSS circuit breakers
- [x] Test staging to make sure it works as expected
- [x] Test setting up a bulk/batch pull via sidekiq in staging
- [ ] Once confident it wont break prod, will attempt in prod in a small batch
- [ ] Will then attempt in prod with all claims needed

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Plan approved by VA (Steve Albers or otherwise)
- [ ] Plan approved by other parties involved in transmission
- [ ] Circuit breaker cut off (optional)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Transmission sample completed
- [ ] Transmission completed

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
@kylesoskin add link to platform support ticket.

**Comment by saderagsdale** [comment]
Sade talking to Steve Albers about plan.

**Comment by saderagsdale** [comment]
Noticing data validation errors in sample data pulls. Action items:

- Need to get those over to the 526 team (or do them ourselves). Sade will bring it up with Matt.

**Comment by saderagsdale** [comment]
Historical 

- Need payload for about 40K, only got them for about 20k
- VA trying to determine how to process them

Batch 1 (20K items that we could generate payload for)
Action item: Kyle pulling together the files and two lists of data to help VA determine how to generate claims in VBMS

Batch 2 (other validation-related issues that causes claims we could NOT generate payload for)
Action item: Kyle sharing validation errors with new 526 team

**Comment by saderagsdale** [comment]
- VBA is figuring out how to process the first batch that was sent to them
- EVSS is lifting a validation requirement to support another batch 
- Kyle is waiting to send the next batch over to VBA (there will be one or two more total, more complex batches)

**Comment by saderagsdale** [comment]
@kylesoskin Can we close this one now that there is a more detailed ticket open?
