### ISSUE TITLE
526ez | Post-release tasks for backup submissions

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#53276]
## Value Statement
**_As a_** developer
**_I want to_** monitor submissions that are re-routed to Centralized Mail and iterate as needed
**_So that_** I know the code is working as desired. 

---
## Background Context
We deployed code on Feb 03, 9pm EST. Next up: fixes and monitoring. 

## Tasks
- [x] Fix bug causing failed evidence uploads also trigger a backup submission (rollout with 2/7 prod release at 3pm)
- [ ] Track complete list of backup submissions every day this week in a shared spreadsheet with Tim Wagner from the VA, and Jay Ruggerio from GovCIO to validate and ensure packets are received and complete
- [ ] Confirm if we can block non-conforming uploads on the frontend

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Plan approved by VA (Talk to Matt Self)
- [ ] Plan approved by other parties involved in transmission
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Transmission sample completed
- [ ] Transmission completed

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
Sending example of failed evidence w/ packet to Matt so he can resolve upstream issue.
