### ISSUE TITLE
Coe | Fix hard coded parts of the form

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#53281]
## Value Statement
**_As a_** dev
**_I want to_** remove hardcoded content
**_So that_** the code is easier to maintain. 

---
## Background Context
- Add here

## Acceptance Criteria
- [ ] _AC_
- [ ] _AC_
- [ ] _AC_

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by saderagsdale** [comment]
@data-doge jot in task details

**Comment by steele-lm** [comment]
@fred-khoury-oddball It looks like this ticket was drafted but never refined. Have you uncovered anything that should be called out?
