### ISSUE TITLE
Add task to New VFS Team template for accessibility people/resources

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#53288]
## User Story
_"As a PM for a new VFS team, I want to share what kind of accessibility support my team already has, so that we can get the help we need and/or our accessibility specialist(s) can connect with the broader a11y practice."_

_"As the PM for the CAIA team, I want to know when a new VFS team is onboarding and what kind of accessibility support they have, so that I can plan our schedule."_

_"As the Governance team accessibility specialist, I want to know when a VFS team has their own accessibility specialist, so that I can engage with them as needed around Collab Cycle touchpoints."_

Assignee:
Peer Reviewer:

## Description
This came up in the 2/7/2023 accessibility specialist sync meeting, as the CAIA team onboards and determines what their processes are. @artsymartha68 indicated that it would be helpful if we had a consistent way for new teams to introduce themselves to CAIA and indicate whether they had their own accessibility support or they would be relying on CAIA's assistance. Additional benefits:
- When a team joins with their own accessibility support, the a11y practice can reach out to them and welcome them into our ongoing conversations.
- Around Collab Cycle touchpoints, if a team has their own accessibility support it would be helpful to know ahead of time if we need to engage with them around feedback.

Some potential scenarios:
- A new team that has no accessibility support and will rely on CAIA
- A new team joins via a contract that already has an existing accessibility specialist who will also support them in addition to their existing workload (eg. new team on the contract that Josh is on, Josh will support them too)
- A new team has someone in a non-accessibility specialist role who has deep knowledge or experience with accessibility and will be their point person for accessibility conformance and testing
- A new team has a team member with an accessibility specialist role

## Impacted Artifacts
- [New VFS Team template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=analytics-insights%2C+governance-team&template=new-vfs-team.md&title=New+VFS+Team+%5BInsert+team+name+here%5D)
- Potentially [Guidance for new teams and team members](https://depo-platform-documentation.scrollhelp.site/getting-started/guidance-for-new-teams-and-team-members)

## Tasks
- [ ] Work with CAIA team and Martha Wilkes to determine the best way to notify them when a new team onboards
   - [ ] (Secondary) Determine a process by which the Governance team accessibility specialist sees this too
- [ ] Add task(s)/question(s) to the New VFS Team template to determine the level of accessibility experience/other resources they have and communicate it to CAIA

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] _Placeholder AC_

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Per refinement on 12/16, the new accessibility team will be handling onboarding recommendations for new VFS teams re: accessibility. This ticket can be closed.
