### ISSUE TITLE
ISCP Review of Roles and Responsibilities

### ISSUE THREAD

**Issue by gary-fallon** [department-of-veterans-affairs/va.gov-team#53293]
## Description
The Roles and Responsibilities in Section 2.2 need to be reviewed and updated.

The ISCP Contact List assigns multiple roles to Clint Little and only an e-mail address is provided. This is unorthodox and generally not a recommended practice. PSEC recommends assigning additional personnel who are trained per Section 2.3.1.

The question you must answer is, could one person effectively perform the responsibilities of three people?

## Tasks
The following tasks must be reviewed and completed as necessary.
- [ ] Roles assigned to @little-oddball are missing a phone number.
- [ ] @little-oddball is identified as the ISCP Coordinator, Platform Support Team Lead, and Recovery & Reconstitution Team Lead. Do you understand and accept your roles and the assigned responsibilities?
  - [ ] Have you gone through any ISCP-specific training for these roles per Section 2.3.1?
- [ ] Andrea Hewitt is identified as the ISCP Coordinator - Alternate.  Do you understand and accept your roles and the assigned responsibilities?
  - [ ] Have you gone through any ISCP-specific training for this role per Section 2.3.1?

## Acceptance
The following tasks must be completed before this issue can be considered done.
- [x] Review for accuracy and completeness.

**Comment by alyssagallion** [comment]
Looping in @andreahewitt-odd and @little-oddball as they will be owning this task.

**Comment by gary-fallon** [comment]
I will be drafting the BIA and ISCP based on a new definition of the FISMA authorization boundary that includes all VFS applications.

**Comment by alyssagallion** [comment]
During our Gap Analysis, we realized that the System Security Plan (SSP) was incorrect. We have since updated it, presented it to the ISSO and Ray Wang is now reviewing the associated tickets he needs to approve. Once those are reviewed and approved, @ScottCutlip will continue the work on SSP. 

SSP is blocking BIA work and BIA work must be completed prior to ISCP work being done. Blocked.

**Comment by jhouse-solvd** [comment]
Please [see the parent epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53216#issuecomment-1589597039) for a recent update. 

Moving to review.

**Comment by jhouse-solvd** [comment]
The ISCP has been updated w/ the most recent info. 

Please see the parent epic (#53216) for future updates and follow-up issues. 

Closing.
