### ISSUE TITLE
ISCP Review of Assumptions

### ISSUE THREAD

**Issue by gary-fallon** [department-of-veterans-affairs/va.gov-team#53291]
## Description
The ISCP assumes specific tasks have been completed prior to document submission.

> This Information System Contingency Plan (ISCP) contains potentially sensitive operational and personnel information; its distribution should be marked accordingly and controlled. The ISCP should be protected from unauthorized disclosure and modification. Copies of the plan will be provided to the recovery team for storage. A copy should also be stored at the alternate site and with the backup media. This is to ensure its availability and good condition in the event the local plan copies cannot be accessed.

> The ISCP Coordinator will maintain a record of copies of the plan and a list of key personnel to whom they were distributed. The ISCP Coordinator is responsible for notifying and updating the identified personnel with the latest version of this ISCP.

## Tasks
The following tasks must be reviewed and completed as necessary.

- [x] The VFSP-Va.gov has been established as a Moderate Impact system, in accordance with FIPS 199.
- [x] Key system personnel have been identified and trained in their emergency response and recovery roles. They are available to activate the VFSP-Va.gov ISCP.
- [x] Backups are processed, maintained, and stored according to VA policy.
- [x] Exercises are conducted on regular basis and the ISCP is updated based on the After-Action Reports from those exercises as well as real-world events.
- [x] Business Impact Analysis results developed for this plan have been incorporated in the development strategy of other organizational plans including, but not limited to, COOP, BCPs and DRP.
- [x] IS Service component restoration priorities have been established

## Acceptance
The following tasks must be completed before this issue can be considered done.
- [x] Review for accuracy and completeness.

**Comment by gary-fallon** [comment]
This item might require additional user stories once the tasks have been reviewed.

**Comment by gary-fallon** [comment]
I will be drafting the BIA and ISCP based on a new definition of the FISMA authorization boundary that includes all VFS applications.

**Comment by jhouse-solvd** [comment]
Please [see the parent epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53216#issuecomment-1589597039) for a recent update. 

Moving to review.

**Comment by jhouse-solvd** [comment]
The ISCP has been updated w/ the most recent info. 

Please see the parent epic (#53216) for future updates and follow-up issues. 

Closing.
