### ISSUE TITLE
ISCP Review of Training, Testing, Exercises, and Evaluation

### ISSUE THREAD

**Issue by gary-fallon** [department-of-veterans-affairs/va.gov-team#53295]
## Description
The Training, Testing, Exercises, and Evaluation in Section 2.3 need to be reviewed and updated.

- Ensure that VFSP-Va.gov’s personnel are familiar with the ISCP and its associated activation, recovery, and reconstitution procedures.
- Validate ISCP policies and procedures;
- Exercise procedures using tabletop and functional exercises, as appropriate; and 
- Ensure that hardware, software, backup data, and records required to support recovery are available. 

Based on the readout from the Tabletop exercise dated January 27, 2023, the ISCP was not discussed nor were any policies or procedures validated. However, the report has already been submitted to eMASS. 

> ISOs are responsible for ensuring the development of a training program for all personnel with assigned ISCP responsibilities so that they will be properly trained to respond to a contingency event affecting the VFSP-Va.gov efficiently and correctly. This training will assist personnel in identifying and learning their respective roles and responsibilities. The training will be provided to personnel within 30 business days of being assigned to the information system, with refresher training conducted at least annually thereafter.

PSEC is not aware of any team-specific or individual training that has been conducted, nor of an assigned TMS module for IS members.

> For Moderate Impact systems, a functional exercise must be conducted at least once every three years. A tabletop exercise is acceptable in other years.

> Functional exercises are more extensive than tabletops, requiring an event to be replicated. 

PSEC is not aware of any functional exercise having ever been conducted on the information system. If one is not completed by September 1st, 2023, a POA&M will need to be created.

## Tasks
The following tasks must be reviewed and completed as necessary.
- [ ] Determine if a POA&M is needed to address this oversight.
- [ ] Ensure that training for the ISCP is being provided to identified personnel within 30 business days of being assigned to the information system with annual refreshers.
  - [ ] Is this being provided via TMS? What is the module name?
- [ ] Ensure that team-specific process training has been created and is available for review.
- [ ] Ensure that individual responsibility training has been created and is available for review.

## Acceptance
The following tasks must be completed before this issue can be considered done.
- [x] Review for accuracy and completeness.

**Comment by gary-fallon** [comment]
This item might require additional user stories once the tasks have been reviewed.

**Comment by gary-fallon** [comment]
I will be drafting the BIA and ISCP based on a new definition of the FISMA authorization boundary that includes all VFS applications.

**Comment by alyssagallion** [comment]
During our Gap Analysis, we realized that the System Security Plan (SSP) was incorrect. We have since updated it, presented it to the ISSO and Ray Wang is now reviewing the associated tickets he needs to approve. Once those are reviewed and approved, @ScottCutlip will continue the work on SSP. 

SSP is blocking BIA work and BIA work must be completed prior to ISCP work being done. Blocked.

**Comment by jhouse-solvd** [comment]
The ISCP has been updated w/ the most recent info. 

Please see the parent epic (#53216) for future updates and follow-up issues. 

Closing.
