### ISSUE TITLE
EKS Migration

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#53307]
## Issue Description
Platform Tech Team 1 is preparing to migrate vets-api to EKS.
This epic captures work related to this initiative. 

---
## Information
- Debt Resolution: Testing Vets-API Server from BRD to EKS (dev) #52261

## Acceptance Criteria
- [ ] All requirements are complete for the migration to EKS
---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
