### ISSUE TITLE
Discuss w/Governance team how to share orientation video

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#53326]
## Issue Description
We now have a video on the Platform's YouTube channel that introduces the Platform website to VFS team members. It lives here: https://www.youtube.com/watch?v=yzl6nyLmqkA

---

## User Stories
As a Platform Content team member,
I need to align with the Governance team on how the video will be delivered to VFS team members,
so that it fits into the bigger structure of the Platform Orientation hosted by them.

As a Governance team member,
I need to know what the Platform Content team created as an orientation for VFS team members,
so I can weigh in on how to best present it to VFS teams.

## Tasks

- [x] Schedule meeting with Governance team's product manager, Shira
- [x] Share the orientation video plans with her, as well as the topics covered in the video
- [x] Align on a plan for how to best share this video with VFS team members (example: where will the video live? play during their orientation? provide a URL for attendees? etc.)
- [x] Document any meeting takeaway tasks in Zen Hub

## Meeting on 3/7 Takeaways
**Add link to video to the following orientation artifacts:**
* General checklist in GitHub orientation template to watch a 1-minute video (Shira)
* Add to the Getting Started, under Platform Orientation general section of website (Content team)
* Add to the Platform Orientation slide (Shira)

**To do:**
* Shira will create a ticket with action items above and Platform content team will peer review
* We will create a Slack post about it
* Vicky will share at Team of Teams

How do we create a process to make edits to a video?
How often will they happen?
How important is the edit?
