### ISSUE TITLE
[FE] (DS Logon Credential Migration) - Update default configurations for USiP

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#53342]
## Description
Update the default configurations for the Unified Sign in Page and Modal so that the DS Logon credential no longer is an option to authenticate with.  

## Tasks
- [ ] Update all environment configs for USiP
- [ ] Verify DS Logon button is not available for any USiP applications
- [ ] Ensure feature is put behind a feature toggle (or DO NOT MERGE in until backend folks are ready)
