### ISSUE TITLE
[FE] (DS Logon Credential Migration) - Verify Burn Pit Registry requirements

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#53349]
## Description
The Burn Pit Registry via the OCC Mobile app currently only allows DS Logon for authentication.  Work with the OCC Mobile team and the Burn Pit Registry teams to allow Login.gov and ID.me accounts to authenticate.

## Tasks
- [ ] Setup a meeting with the OCC Mobile + Burn Pit Registry teams
- [ ] Gather requirements to allow more than just DS Logon for authentication
- [ ] Create ticket for the implementation details of the Burn Pit Registry app
