### ISSUE TITLE
Establish SRE team initiative

### ISSUE THREAD

**Issue by BillChapmanUSDS** [department-of-veterans-affairs/va.gov-team#53354]
## Problem Statement 

* Site Reliability is an ongoing concern across VA.gov properties. To bring platform in inline with the wider SRE intitiatives happening at VA, we need to build  a Site Reliability team that serves to maintain best practices for SRE across Vets-API projects. 

* Beginning with a 6 - 8 month discovery sprint this will be the foundational period for the SRE Community of Practice.  We need 2 SRE  who focus on SRE topics, to help us build out Vets API specific SRE initiatives and culture. Each of these 2 SRE will also be able to step in to the SRE (CoP) lead role that is being filled by OCTO  in the event of their absence or unavailability.

* Each of the four primary project teams will also have an SRE lead hat, this person would attend the weekly SRE standups, bring the issues their team is facing to SRE awareness, help build out SRE related projects on the team when prioritized. 

A Note on SRE: 
A function created at Google, SRE is about driving shifts in how teams operate across a company. SRE teams are responsible for building automated solutions for operational aspects, such as incident response, on-call duties and performance monitoring.  This does not mean that SRE teams are the front line response. SRE exists so that front line incident response is less common. 

## User Impact
Reliability issues effect every veteran using VA.gov services. 

## What do we not know about the problem space?
* The backlog and priority of projects that are supported by the SRE CoP is to be sourced via the initial discover sprint. These projects will be suggested, refined, and curated by the SRE team.  

## What (if any) research or discovery has been done?
[Building SRE Teams](https://cloud.google.com/blog/products/devops-sre/how-sre-teams-are-organized-and-how-to-get-started)
[Adopting SLOs](https://cloud.google.com/architecture/adopting-slos)
[SRE Priorities and Initiatives](https://vfs.atlassian.net/wiki/spaces/~63618f93fc0cc7a600b041f2/pages/edit-v2/2424799858)

## What is the acceptance criteria?
* Team members will be named and added to the SRE effort 
* Workloads are adjusted for SRE team members to account for this effort 
* Discovery period begins and meeting cadence is established. 

## How should we measure success?
* A long term strategy for SRE on platform teams exists and is being implemented. 
* A discovery period of no less than 6 months has concluded 
* A backlog of prioritized and in progress projects exists. 

## TODOs
- [x] Identify SRE team candidates 
- [x] Have kick off meeting establishing team norms
- [x] Establish cadence of  meetings and initial goals
- [x] identify SME's in group

**Comment by jwoodman5** [comment]
@BillChapmanUSDS I believe this is in-progress, but did not want to move it without chatting with you. Can you please move it unless you disagree? Thanks.

**Comment by little-oddball** [comment]
I believe this ticket might also need some tweaking based on conversations we have had on approach just to be more aligned.

**Comment by BillChapmanUSDS** [comment]
Current Status:   SRE Advsory Group:  Kyle, Lyndsay,  Eiric.   
Eric will be serving as SRE CoP lead. 

Kickoff meeting to happen week of 4/ 16

**Comment by BillChapmanUSDS** [comment]
The SRE kickoff meeting happens tomorrow.

**Comment by BillChapmanUSDS** [comment]
KIck off meeting has been completed. Currently working on Cademce of the next few touchpoints.
