### ISSUE TITLE
[FE] (Mock Authentication) - Add mock authentication button

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#53351]
## Description
Create a mock authentication button that can be enabled on the Unified Sign in Page as well as on the Sign in Modal (in dev & below environments).

## Tasks
- [x] Create mock authentication button that generates the proper URL for Sign in Service
- [ ] ~~Ensure button does not display for Production (only staging & below environments)~~
- [x] Button should display on /sign-in/mocked-auth 
- [x] Clicking the button takes you to the `<api-env>/v0/sign_in/authorize?client_id=vamock` API URL
- [x] Ensure the button color is different than any other CSP

**Comment by asg5704** [comment]
@ianmagenta can we get the design to look like this please?
![mocked-auth.png](https://images.zenhubusercontent.com/5f3be621ca5d1e85751d760d/ae10f7f2-c34a-493f-b6b4-3097f65dfdcc).

The content could possibly change so just be aware of that.

**Comment by asg5704** [comment]
Also @ianmagenta this should be for dev & localhost only not staging. That's my fault.

**Comment by ianmagenta** [comment]
@asg5704 - No worries, I'll make the necessary adjustments before pushing up later today. 
Below is the design as I currently have it. Would that be acceptable?
 
![image](https://user-images.githubusercontent.com/59981318/222802738-c2c2a0dc-06d0-49b9-b006-108d3f7a491a.png)
