### ISSUE TITLE
[FE] (Mock Authentication) - Add vamock to USiP configurations

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#53350]
## Description
Update the Unified Sign in Page configuration files to include a new application `vamock` to mock authentication from a CSP standpoint.  

## Tasks
- [x] Create new Unified Sign in Page configuration for `vamock` in staging & below configuration files
  - [x] Ensure URL renders as `<environment>/v0/sign_in/authorize?client_id=vamock`
- [x] Create unit tests so that a mock auth button renders as appropriate when the `vamock` application is loaded

**Comment by mjconw3** [comment]
Hey @acaruso-oddball l...Mike and I have reviewed this ticket, added the appropriate label and sprint and have closed. Moving forward we will be making sure acceptance criteria/tasks are checked as completed on all tickets to make review easier (not a problem for now while you all were managing your own tickets). Since this is already merged we closed it.
