### ISSUE TITLE
[FE] (Tech Debt) - Remove MHV Accounts (CTA) from vets-website

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#53362]
## Description
The MHV Accounts creation/deletion/updates should be removed from vets-website. [Slack thread](https://dsva.slack.com/archives/C019S3NSSAD/p1671574583761209)

## Tasks
- [x] Remove MHV Accounts from vets-website applications
- [x] Inform vfs-frontend and vfs-all-teams that MHV Accounts application will be removed (it's already removed in vets-api according to Trevor)
- [x] Ensure unit tests are removed & all instances where there are callouts (aka Call to Action) for MHV Accounts creation/updates are removed
