### ISSUE TITLE
[FE] (Tech Debt) - Remove Terms & Conditions from vets-website

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#53360]
## Description
Remove the old Terms & Conditions functionality from vets-website and ensure any code redirect to that page is also removed.

## Tasks
- [x] Remove the `terms and conditions` application from vets-website
- [x] Notify in vfs-frontend & vfs-all-teams that Terms & Conditions application will be removed
- [x] Ensure `cta-widget` that handles some MHV stuff does not redirect to terms & conditions

**Comment by asg5704** [comment]
We're going to close this pending new info from Tom Black and the Terms of Use.
