### ISSUE TITLE
Collaboration Cycle for CTO Health Team, MHV on VA.gov Portal, Authenticated Landing Page

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#53374]
### VFS team name

CTO Health Team

### Product name

MHV on VA.gov Portal

### Feature name

Authenticated Landing Page

### GitHub label for product

my-health-INTEGRATION

## Kickoff questions

<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

2023-01-30

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Tools, applications and dynamic pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

No

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline

TBD

### Notify the Collaboration Cycle team of this ticket in the vfs-platform-support Slack channel.
</details>

- [X] I acknowledge that I must notify \#vfs-platform-support after submitting this issue.
### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- Navigate to reference link: [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent)
- [x] Schedule your Design Intent when ready:
   - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders 
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [x] Link all artifacts **ONLY** in the Design Intent artifacts section below at least two days before the scheduled Design Intent.  **Do NOT add artifacts to Comments section**
  
**Design Intent artifacts**

- [ ] Whiteboard sketch or other lo-fi prototypes or wireframes
- [x] User flow
  - [x] VA.gov --> sign on --> My Health in main nav --> **Landing page** --> Deep link to MHV legacy tool / content (excluding appointment related things)
  - [x] VA.gov --> sign on --> My Health in main nav --> **Landing page** --> VA Online Scheduling
- [x] Research plan
  - [x] We aren't planning on doing research before it goes live (since it is so close to what we have today), but the plan is for our team to complete some related usability research on the landing page and its evolution shortly thereafter.
- [x] Any other artifacts you have so far
  - [x] [Proposed design](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49026#issuecomment-1423090950)
 - [x] See [Slack conversation](https://dsva.slack.com/archives/CBU0KDSB1/p1676038299909839) for additional info
  
##### Platform actions
- [x] Follow Moderator Responsibilities guidance for Design Intent
- [x] Meeting date/time: 2/14/2023 11.00 AM
  
##### Platform actions

- [ ] If you have feedback, create feedback tickets and link to this epic. Once you have completed you review, check the box next to your practice area
  - [x] Accessibility has completed the review
  - [x] Design has completed the review
  - [x] IA has completed the review
- [x] Update this ticket with the Zoom recording
  - Recording URL: [Zoom recording](https://oddball-io.zoom.us/rec/share/YwbQI6GSa_BoHtFaQk0dk9HI8AMtRxCnl2WZ9tUfBIjJUj_hu9akehkqeeJV5CHs.FCHJx6amUTJu45D8)
  - Password: u!4WQG?4
  
##### VFS actions

- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Sitewide Content and IA Intake Request
<details>
  <summary>Toggle Sitewide Content and IA Intake Request</summary>

##### VFS actions
- [x] Complete the [sitewide content and IA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-Content-and-IA-intake-request.2124906551.html)
- [ ] Link to the Sitewide Content and IA Intake Request ticket below
https://github.com/department-of-veterans-affairs/va.gov-team/issues/53568

</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [ ] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [ ] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

Provide links or documents for the following:

- [ ] Finalized design prototype or mockup
- [ ] Specify which pages are included in the review 
- [ ] Research plan
- [ ] Conversation guide
 
**Content artifacts**
  
- [ ] Your product’s content source of truth 
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)

**IA artifacts**

- [X] [Sitewide Content & IA](https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/53568) feedback you received, including an IA review document or intake form.

https://github.com/department-of-veterans-affairs/va.gov-team/issues/54087
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/49253
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/49016
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/49022
https://github.com/department-of-veterans-affairs/va.gov-team/issues/49246
https://github.com/department-of-veterans-affairs/va.gov-team/issues/52117
https://github.com/department-of-veterans-affairs/va.gov-team/issues/49017

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
**Please note that we do not currently have TestRail plans written due to challenges with replicating the user experience in Staging and getting authority to the project in order to create tests.**

- [ ] [Regression test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-regression-test-planRegressionTestPlan)
- [ ] [Test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-test-planTestPlan)
- [ ] [Coverage for References](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [ ] [Summary(Defects) reports](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [X] [E2E tests](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/mhv/landing-page/tests)
- [X] [Code coverage](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/mhv/landing-page/tests)
  
##### Platform actions
- [ ] Follow Moderator Responsibilities guidance for Midpoint Review
- [ ] Meeting date/time:

##### Platform actions

- [ ] If you have midpoint review feedback, create feedback ticket and link to this epic. Once you have completed your review, check the box next to your practice area
  - [ ] Design has completed the review
  - [ ] Accessibility has completed the review
  - [ ] IA has completed the review
  - [ ] Content has completed the review
  - [ ] QA has completed the review
- [ ] Update this ticket with the Zoom recording
  - Recording URL: 
  - Password:
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [ ] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [ ] Link to the Analytics Implementation and QA Request ticket below

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [x] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [x] Link to the Contact Center review request ticket below

https://app.zenhub.com/workspaces/mhv-on-vagov-top-level-view-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/54901
</details>

### Staging Review
<details open>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [X] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [X] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [X] I confirm the environment is available and test users have been provided.
- [X] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
 
**Staging Review artifacts**
  
  Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts)
  
**Product artifacts** 
- [X] Staging URL https://staging.va.gov/my-health/
- [X] Specify which pages are included in the review       
   - After logging into VA.gov on Staging using the below-referenced credentials, click on the "My Health" link in the main nav to access the landing page.  This is the only page in scope for the staging review.
- [X] Staging test user information  - test user information can be obtained through the [Test User Dashboard](https://tud.vfs.va.gov/) and selecting a user that has an MHV account.

**Content artifacts**
- [X] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
  
**IA artifacts**
- [X] Sitewide Content & IA feedback you received, including an IA review document or intake form.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/53568
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/54087
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/49253
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/49016
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/49022
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/49246
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/52117
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/49017

**QA artifacts**

*Please note that we do not currently have TestRail plans written for this page due to challenges with replicating the user experience in Staging and getting authority to the project in order to create tests.*

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [ ] [Regression test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-regression-test-planRegressionTestPlan)
- [ ] [Test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-test-planTestPlan)
- [ ] [Coverage for References](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [ ] [Summary(Defects) reports](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [X] [E2E tests](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/mhv/landing-page/tests)
- [X] [Code coverage](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/mhv/landing-page/tests)
  Per the [Frontend Support Dashboard](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report/):

| Application |	Lines |	Functions |	Statements | Branches |
| mhv/landing-page | 100.00%	| 100.00%	| 100.00%	| 84.62% |
  
**Accessibility artifacts**
  
- [x] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D). For details, see [Prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/54863
  
##### Platform actions
- [x] Follow Moderator Responsibilities guidance for Staging Review
- [x] Meeting date/time:  **Thursday, March 16, 2023 at 1:30PM Eastern**

##### Platform actions

- [x] Update this ticket with the Zoom recording
  - Recording URL:  https://oddball-io.zoom.us/rec/share/Xkh2TWJbJ1WZRKTbHoBcmVMdVMw2V1XyhvHiWHWgDSgBN81zp5GmGf2QLBgX65ma.UgP4rqQWZeVOfTtE
  - Password: ah9%M2Yy
  
##### VFS actions
  
- [x] Review feedback tickets and comment on the ticket if there are any questions or concerns
- [x] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [x] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [X] Share ServiceNow ticket number here: REQ9071572
- [X] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [x] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [x] Link to the Readiness Review ticket below
https://github.com/department-of-veterans-affairs/va.gov-team/issues/54944#### Platform actions

- [x] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by CherylEvans** [comment]
@bethpottsVADEPO Good morning Beth.  I was reviewing this ticket yesterday and noticed that the acronym COE is spelled out below the H1 for obvious spatial limitations reasons ([guidance from design.va.gov](https://design.va.gov/content-style-guide/page-titles-and-section-titles#page-titles)).  Do we have more detailed guidance regarding punctuation use in titles and headings?  I would love to hear your thoughts and advice on this matter.

**Comment by bethpottsVADEPO** [comment]
@CherylEvans What kind of punctuation guidance are you looking for related to this work?

**Comment by MarciMcGuire** [comment]
@batemapf any objection to me getting this CTO Health Team added to the VFS team roster?

**Comment by batemapf** [comment]
none!

**Comment by batemapf** [comment]
👋 now that we're done with staging review and ready to release to our first small increment of production traffic, is this OK to close?

**Comment by MarciMcGuire** [comment]
I believe so.  I'll make a new ticket to write the tests.
