### ISSUE TITLE
Conduct research sessions to test grandfathering journey(s) with Veterans

### ISSUE THREAD

**Issue by tygindraux** [department-of-veterans-affairs/va.gov-team#53386]
### Problem statement
Veterans need to make migrate their DS Logon accounts to Login.gov through grandfathering, which allows them to defer identity proofing.

### Initiative
We have been approved to run research March 27 - April 6. We're following the [VA Platform Research Checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist#ResearchChecklist-2.Researchreview) throughout [this study](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/login.gov-adoption/research/2023-02-Grandfathering-Migration-Round-1-Usability).

### Timeline
March 8 - Submit prototype for Midpoint Review
March 8 - Submit artifacts for Research Review
March 9 - Ready documentation is ready (feedback incorporated)
March 17 - Prototypes are ready (feedback incorporated)
March 20 - Pilot session at 12:00pm EST
March 27 to April 6 - Research sessions
April 10 to 12 - Analysis
April 13 to 19 - Share findings

### Acceptance criteria
- [x] Interviews have been conducted with Veterans

### Tasks
- [x] @tygindraux schedule a couple debriefs with team
- [x] @tygindraux @MOStudioCarolyn follow [moderator guidelines](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/research/Guidelines/Guide%20to%20moderating.md) when moderating sessions
- [x] @tygindraux download recordings (do not re-upload to the cloud)

### Materials for research sessions
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/research/2023-02-Grandfathering-Migration-Round-1-Usability/research%20plan.md)
- [Conversation guide #1 Modal after sign in](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/research/2023-02-Grandfathering-Migration-Round-1-Usability/conversation%20guide%20%231.md)
- [Conversation guide #2 Email ask to sign in](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/research/2023-02-Grandfathering-Migration-Round-1-Usability/conversation%20guide%20%232.md)
- [Prototype #1 Modal after sign in](https://www.figma.com/proto/8vobVoSl1UqLnXsni3rcvO/Login.gov-Migration%3A-Grandfathering-IAL1-Flow?node-id=41%3A1311&scaling=contain&page-id=0%3A1&starting-point-node-id=41%3A1311)
- [Prototype #2 Email ask to sign in](https://www.figma.com/proto/8vobVoSl1UqLnXsni3rcvO/Login.gov-Migration%3A-Grandfathering-IAL1-Flow?node-id=402%3A2918&scaling=min-zoom&page-id=241%3A1368&starting-point-node-id=402%3A2918)
---
- [Tech set up checklist](https://depo-platform-documentation.scrollhelp.site/research-design/tech-set-up-checklist)
- [Troubleshooting research sessions](https://depo-platform-documentation.scrollhelp.site/research-design/troubleshooting-for-va-gov-research-sessions-in-pr)
- [Tips on moderating](https://depo-platform-documentation.scrollhelp.site/research-design/Conducting-Research-Sessions.1958773061.html#ConductingResearchSessions-Moderatingtips)
- [Responding to emergencies](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Safety-and-Emergency-Exit-Strategies.2143649793.html)
