### ISSUE TITLE
Submit prototype(s) for Midpoint Review

### ISSUE THREAD

**Issue by tygindraux** [department-of-veterans-affairs/va.gov-team#53383]
### Problem statement
Veterans need to make migrate their DS Logon accounts to Login.gov through grandfathering, which allows them to defer identity proofing.

### Initiative
We are aiming to submit the prototype(s) for Midpoint Review by the Platform team on March 1st.

#### Collaboration Cycle touchpoint
[Midpoint review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review): Request this touchpoint when you’ve finalized your design and have a prototype or mockup ready to put in front of users. Midpoint Reviews require a 2 day lead time.

The Collaboration Cycle should conduct a Midpoint Review a week (minimum) before you start your research. They ensure it meets VA.gov quality standards before putting it in front of Veterans.

You may schedule a Midpoint Review in either of these formats:
- Synchronous: Live, 30-minute Zoom meeting with Governance team
- Asynchronous: No meeting is scheduled. Governance team members review your research and design artifacts on their own, and append their feedback to your request ticket

We recommend a synchronous meeting if this is the first time you’re introducing Platform to your product and/or iteration.

To confirm your prototype or mockup aligns with existing VA.gov patterns and standards and to ensure your product is ready for successful research activities. This may include usability testing, Veteran interviews, or anything else specified in your research plan.

VFS Product Manager (@elizabethkochBT) completes the Before Meeting/VFS Actions in the Midpoint Review section of their [Collaboration Cycle Request ticket](https://app.zenhub.com/workspaces/logingov-adoption-team-632280b31e745000136a61fc/issues/gh/department-of-veterans-affairs/va.gov-team/50773)

Provide links or documents for the following:
- Product outline
- Finalized design prototype or mockup
- Research plan
- Conversation guide

### Acceptance criteria
- [x] [Midpoint review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review) has been attended and MUST feedback has been incorporated

### Tasks
- [x] @elizabethkochBT make [Midpoint review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review) request in our [Collaboration Cycle Request ticket](https://app.zenhub.com/workspaces/logingov-adoption-team-632280b31e745000136a61fc/issues/gh/department-of-veterans-affairs/va.gov-team/50773)
- [x] @tygindraux update ticket with links to prototypes and research plans
- [x] @all attend meeting with Platform team on Monday, March 13th

### Materials for midpoint review
- [Prototype #1 Modal after sign in](https://www.figma.com/proto/8vobVoSl1UqLnXsni3rcvO/Login.gov-Migration%3A-Grandfathering-IAL1-Flow?node-id=41%3A1311&scaling=contain&page-id=0%3A1&starting-point-node-id=41%3A1311)
- [Prototype #2 Email ask to sign in](https://www.figma.com/proto/8vobVoSl1UqLnXsni3rcvO/Login.gov-Migration%3A-Grandfathering-IAL1-Flow?node-id=402%3A2918&scaling=min-zoom&page-id=241%3A1368&starting-point-node-id=402%3A2918)

---

- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/research/2023-02-Grandfathering-Migration-Round-1-Usability/research%20plan.md)
- [Conversation guide #1 Modal after sign in](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/research/2023-02-Grandfathering-Migration-Round-1-Usability/conversation%20guide%20%231.md)
- [Conversation guide #2 Email ask to sign in](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/research/2023-02-Grandfathering-Migration-Round-1-Usability/conversation%20guide%20%232.md)
