### ISSUE TITLE
Submit artifacts for Research Review

### ISSUE THREAD

**Issue by tygindraux** [department-of-veterans-affairs/va.gov-team#53384]
### Problem statement
Veterans need to make migrate their DS Logon accounts to Login.gov through grandfathering, which allows them to defer identity proofing.

### Initiative
We need to submit our plan for how we test the end-to-end grandfathering flow with Veterans so it can be reviewed by the Platform team. We are aiming to submit artifacts for the Research Review on March 1st.

#### Collaboration Cycle touchpoint
[Research review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/research-review): Request this touchpoint 1 - 2 weeks before you plan to conduct user research. Asynchronous review of research plan and conversation guide.

Follow the [Research Checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist#ResearchChecklist-2.Researchreview) for this.

### Acceptance criteria
- [x] Study is added to the repo board
- [x] Pilot session has been scheduled with pilot participant
- [x] Research documentation has been updated based on Platform feedback

### Tasks
- [x] @tygindraux add the study to the repo board
- [x] @tygindraux submit the research for async review by the Platform team 
- [x] @tygindraux find pilot participant
- [x] @tygindraux schedule pilot session
- [x] @tygindraux make updates based on Platform team's feedback

**Comment by tygindraux** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/team-veterans.md

**Comment by tygindraux** [comment]
I'm hesitant to make this request too early; before we have an expected date for the Midpoint Review. On Tuesday, March 7 (after the call with Login.gov on Monday) I'm going to check in with Carl/Carolyn to see expected deadline for completing design work/submitting for Midpoint.
