### ISSUE TITLE
GA4: Testing & Validation - Web/Form Events

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#53394]
## Issue Description

Upon completion of form components FE code deploy test and validate event tracking again UA360.

---
## Tasks
- [ ] Test each web component on staging.va.gov to ensure tracking is reflected on adwerve console
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzZ1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--64d51811011eb2c7a3d1ee624514471ad39c61b7/image.png)

- [ ] Compare UA report metrics to GA4 report metrics for each web component and validate working as expected
- [ ] Update/change/correct any web components who are not tracking as expected per console and report metrics
- [ ] Iterate testing until sign off on all web components

## Acceptance Criteria
- [ ] All web components have been test and validated
---

**Comment by johnny-jesensky-adhoc** [comment]
Closing this ticket out, as was creating factoring an older GA4 transition workflow. Will be tracking this work through other tickets.

FYI @jestutt
