### ISSUE TITLE
GA4:  VFS Custom Events - Testing & Validation

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#53399]
## Issue Description

Upon completion of VFS custom event code deploy test and validate event tracking again UA360.

---
## Tasks
- [ ] Test each custom event on staging.va.gov to ensure tracking is reflected on adwerve console
- [ ] Compare UA report metrics to GA4 report metrics for each custom event and validate working as expected
- [ ] Update/change/correct any custom event that are not tracking as expected per console and report metrics
- [ ] Iterate testing until sign off on all custom events

## Acceptance Criteria
- [ ] All custom events have been test and validated

**Comment by johnny-jesensky-adhoc** [comment]
Closing this ticket out, as was creating factoring an older GA4 transition workflow. Will be tracking this work through other tickets.

FYI @jestutt
