### ISSUE TITLE
GA4:  Web components - GTM configuration and documentation for handoff to FE

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#53390]
## Issue Description
We will begin implementation and testing of web components in Sprint 22. In preparation for that we need to ensure the data layer code is complete and clear for the Design System team to implement. 

---
## Tasks
- [x] Review each web component config in GTM
- [x] Update web component data layer documentation
- [ ] Develop instruction doc for FEs

## Acceptance Criteria
- [x]  A document will be completed for handoff to FE to support their implementation efforts.
