### ISSUE TITLE
[Discovery] 10-10CG - Improvements: Explore possible updates from business feedback

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#53405]
## Background
In November 2022, our team asked questions of the Caregiver operations management to get a sense of what kind of issues they are seeing when processing applications.  One of the main topics was incorrect or conflicting data on the application.
We need to explore some of these issues, and consider what kinds of improvements we might be able to implement.

Notes from [1/13/2023 bi-weekly meeting](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/Meeting%20Notes/01-13-2023%20CG%20Stakeholder%20Touchbase.md)
>- They [applicants] don't know stuff, causing delays
>     - They don't know to use primary physical residence vs mailing/PO box
>     - DOB functionality is not being used right
>          - year or day will flip one over (one number off) [issue with dropdown)
>     - Signature fields
>          - wrong person name entered (secondary enters in primary field) [PAPER ONLY, NOT POSSIBLE ONLINE]
>     - First & Last name
>          - listing Jon instead of Jonathan, Cat or Cathy instead of Catherine
>     - Non-required fields that are useful
>          - Such as Middle name, useful in ensuring Bank info matches so payments can be processed

## Tasks
- [x] Explore each problem area, collaborate with CG operations team on additional questions
- [x] Work with the team to propose solutions, if any are applicable
- [x] Determine next steps, if any (design, development, testing)

## Acceptance Criteria
- Each problem area will be explored and possible solutions determined and shared with Caregiver team

**Comment by hdjustice** [comment]
@katelyncai - Are we done with this one?  I created the design ticket #60228, will be scheduled for next sprint (will bring up in planning today)

**Comment by katelyncai** [comment]
Did discovery, drafted some proposed designs, and discussed with content. Will take their recommendations forward with work on the design ticket.
