### ISSUE TITLE
[Design] Review and update links in our documentation as necessary re: TTY and button pairs updates

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#53408]
## Background

Sketch files reviewed in #52637

Now that Sketch files have been reviewed/updated to reflect the updates for how we are showing TTY numbers and the change from Update/Cancel --> Save/Cancel button pairs, our documentation needs to be reviewed to see if any links need to be updated for anything that links to Sketch.

[Here is the primary list of our profile documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/use-cases#readme). You only need to review the following:

- Personal information (for TTY and button pairs)
- Contact information (for TTY and button pairs)
- Military information (TTY only -- there are not editable fields in this section)
- Direct deposit (for TTY and button pairs)
- Notification preferences (TTY only -- this section uses auto-save instead of an edit --> save model)

Account security and Connected apps do not mention TDY or have editable states.

Each link will take you to an overview of use cases for that section. I'd go through the use cases, check the links to the sketch files, and update links as needed.

## Tasks

- [x] Review documentation for where we link to instances that show the TTY number use case, and where we show Save/Cancel button pairs (basically any edit state). 
- [x] Update links to Sketch files as needed

## Acceptance criteria

- [x] All Sketch file links have been updated accordingly

**Comment by andaleliz** [comment]
@Samara-Strauss and @fmccaf1 as an FYI the user flow charts shouldn't have to be updated for these two changes changes, since the purpose of those isn't about content. 

When we created those, it was under the guise of "let's make sure these don't need to get updated unless we have a new step in the flow we need to capture".  If we want to change our approach to that, then they probably all need to be updated in some way.

**Comment by Samara-Strauss** [comment]
Fine by me! Thank you for letting me know. Then we can ignore the flow charts. I'll update the requirements.

**Comment by fmccaf1** [comment]
## Here are some changes I made as part of this ticket:
- Realized by looking through links that we still had some update/cancel button pairs as well as reference to "update" in the content on a few screens (all within contact info: bad address indicator), so I edited those screens
- Changed links and some text for [bad address flag use case](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/use-cases/address-marked-as-bad.md)
- Deleted mid-fi mock-ups for bad address use case
- Changed some links and added some for [notification settings: user has no contact info on file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/use-cases/user-missing-contact-info.md)

## Some other important info:
There are currently some missing pieces for the notification settings links that I'm attributing to the fact that @andaleliz is working right now to expand notification setting affordances and so this documentation will need to change to reflect that there are now more options. 
- User wants to update notification settings: saving and editing. We don't yet have a "update saved" design for desktop or mobile (that I could find) so I just wrote "mockups needed" instead of providing links.
- User has partial or missing contact information: User has partial contact info (email OR phone number). This one is in the works (no page linked yet) and I'm assuming @andaleliz will update as part of her ongoing work around notification settings.
- User has partial or missing contact information: User doesn't have contact info on file. There is a mix of available mockups for this page. I was able to find a desktop mockup with correct warning alert component, but for mobile, [there is only a mockup for missing mobile number](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/v8ejpvM) so I removed the link and added "mobile mock-up needed."
- User has partial or missing contact information: User doesn't have contact info on file. I felt there was a step skipped in documentation where user accesses field(s) to add contact info, so I added that in, but I couldn't find any mock-ups [(only mock-ups I could find gave user option to add mobile number)](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/v8ej4q3). I noted in the text that mock-ups are needed.
- User has partial or missing contact information: User doesn't have contact info on file. For the final 2 links on this page, I found mock-ups where success message is shown, but message is specific to phone number getting added.

**Comment by fmccaf1** [comment]
All TTY/button pair instances have been addressed!

**Comment by fmccaf1** [comment]
Thanks @andaleliz!

You raise a good point about clarity of the document! When I first read it, I was expecting that the contact field(s) that the user was missing would be attracting the user's attention in a different way, but it sounds like the experience is the same as if a user got to their contact info section on their own. Maybe just a temporary me problem!
