### ISSUE TITLE
[FSR] Contact Information Bug

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#53409]
## Issue Description
Investigate an issue on staging where users with no address have the form crashing looking for `livesOutsideUS`. Could also be related to the getting singed out issue with [this sentry error](http://sentry.vfs.va.gov/organizations/vsp/issues/183827/?environment=production&project=4&query=is%3Aunresolved+location%3A%2Fgenerated%2Frequest-debt-help-form-5655.entry.js&statsPeriod=14d)

---
## Tasks
- [x] Identify root cause of issue
- [ ] Add localhost mockdata for local testing purposes
- [x] resolve issue with form crash

## Acceptance Criteria
- [ ] all staging users are able to access 5655 with enhanced flag on/off
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
PR reverting changes that are causing these errors:
https://github.com/department-of-veterans-affairs/vets-website/pull/23350

**Comment by HeatherRienks** [comment]
@Dr-Pongo @OptionSelect - Is this ready to be closed?

**Comment by Dr-Pongo** [comment]
Yes! The errors cleaned up after its removal
