### ISSUE TITLE
GA4:  Documentation, Training, & Communications

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#53417]
## Problem Statement 
GA4 event tracking and reporting is different than UA360.  We will need to update all our supporting documentation and conduct training sessions for teams in order to to complete the migration and sunset the 360 property.

### Hypothesis or Bet
If we provide the documentation and training resources for GA4 we will complete the migration with less disruption.

---
## We will know we're done when... ("Definition of Done")
- [x] Confluence documentation updated
- [x] Platform website updated
- [x] Training materials are updated
- [x] Training session and/or recording are completed
- [x] Updates have been announced
- [ ] 

### Known Blockers/Dependencies 
GA4 testing & validation complete.

### Documentation
* **`PRODUCT_NAME`**: [GA4 Discovery - WIP](https://vfs.atlassian.net/wiki/spaces/AT/pages/1928495134/WIP+-+GA4+discovery)
* **Product Outline**: [GTM Product Outline](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1905066142/Google+Tag+Manager+product+outline)  _- Needs to be updated based on this work_
* **User Guide**: [GA and GTM User Guide](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-and-Google-Tag-Manager.1857978529.html#GoogleAnalyticsandGoogleTagManager-GoogleTagManager) _- Needs to be updated based on this work_

**Comment by raywangoctova** [comment]
@johnny-jesensky-adhoc Can we discuss the DoD of this epic card? How can the completion of more focused buckets of products, features, or services be reflected in our incremental deliveries?

**Comment by johnny-jesensky-adhoc** [comment]
@raywangoctova  -- Yes, I'll add this to the agenda of our next PO sync. For the record, this is an epic that I inherited when I took over the team, and haven't made too many edits on it since then. We've only just begun some of our work on this now that we're past the sunset of Universal Analytics (UA), so we can discuss how to incorporate some solid DoD criteria going forward.

**Comment by johnny-jesensky-adhoc** [comment]
As discussed in PO sync on September 26th, the initial work on documentation, training, and communications meets the definition of done here. We will continue as part of our ongoing services to VFS Teams -- marking this as _Done_ for now.
