### ISSUE TITLE
Draft alternative grandfathering user flow for testing incl. conversation guide

### ISSUE THREAD

**Issue by tygindraux** [department-of-veterans-affairs/va.gov-team#53410]
### Problem statement
Veterans need to make migrate their DS Logon accounts to Login.gov through grandfathering, which allows them to defer identity proofing.

### Initiative
We have drafted an initial flow which is trigged by a Veteran signing in to VA.gov and seeing a modal pop-up asking them to migrate.

We want to explore alternative flows or ways that this flow is triggered. We'll create 1 additional flow for round 1 of testing.

This might be through:
- Additional or other entry points (eg. an email or starting on eBen)
- Additional or other components are used (eg. not a modal)
- Exploring what happens if a Veterans clicks away (eg. how do they return?)

### Acceptance criteria
- [x] User flow including content is created in Figma
- [x] Conversation guide has been created in Github

### Tasks
- [x] @MOStudioCarolyn draft user flow in Figma
- [x] @tygindraux copy discovery email screen to file
- [x] @tygindraux create 2nd conversation guide for testing this flow
- [x] @tygindraux share guide with the team for feedback
- [x] @CarlDickerson draft content for email and re-direct page
- [x] @MOStudioCarolyn update success and error screens (in both flows) to end up on MyVA (and post sign-in pages)
- [x] @MOStudioCarolyn @CarlDickerson share prototype at demo
