### ISSUE TITLE
Tech discovery - are REACT based radio buttons being used by 526ez forms

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#53413]
## Issue Description
The Design System Team has been deprecating older React-based versions of our components in favor of web-components (which have React bindings). 

The scope of this ticket is limited to planned deprecation of the use of React-based radio buttons by end of Feb'2023

---
## Tasks
- [x] _Technical research to see if REACT based radio buttons are being used in 506 forms

---
## Need To Know
- [ ] _Here is a page specifically for developers with relevant information https://design.va.gov/about/developers#using-web-components
 - [ ] Components that have been deprecated in Storybook - https://design.va.gov/storybook/?path=/story/about-introduction--page
 - [ ] Slack thread - https://dsva.slack.com/archives/C0NGDDXME/p1675952902462759

## Acceptance Criteria
- [x] _Discover if 526ez forms use REACT based radio buttons
- [x] _Open a ticket to update the forms to replace REACT based radio buttons with web-components
- [x] _The new ticket has a list of all occurrences of REACT based radio buttons in the application

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ahay-agile6** [comment]
The `VaRadio` React RadioButton Component is being used in the 526EZ form:

1. "Are you on active duty right now?"  
**/disability/file-disability-claim-form-21-526ez/start**: 
`src/applications/disability-benefits/wizard/pages/start.jsx:28`
```
<VaRadio
      class="vads-u-margin-y--2"
      label={label}
      onVaValueChange={onValueChange}
    >
      {options.map(option => (
        <va-radio-option
          key={option.value}
          name="active-duty"
          label={option.label}
          value={option.value}
          checked={state.selected === option.value}
          aria-describedby={
            state.selected === option.value ? option.value : null
          }
        />
      ))}
    </VaRadio>
```
![image.png](https://images.zenhubusercontent.com/5c1047425e37320ceee743c3/80e6e738-fa77-44d1-b541-549fe7d80513)

2. Separation Pay
**disability/file-disability-claim-form-21-526ez/separation-pay**
This one does _**not**_ seem to be using the React component, but rather the form component. Need to check if the form component is using React components
`src/applications/disability-benefits/all-claims/pages/separationPay.js:17`
```
hasSeparationPay: {
    'ui:title': hasSeparationPayTitle,
    'ui:widget': 'yesNo',
  },
```
![image.png](https://images.zenhubusercontent.com/5c1047425e37320ceee743c3/91c58e95-c015-473d-97e4-56507e661b18)

3. Retirement Pay
**/disability/file-disability-claim-form-21-526ez/retirement-pay**
This one looks to be the same pattern as above. Need to check forms component.
`src/applications/disability-benefits/all-claims/pages/retirementPay.js:11`
```
'view:hasMilitaryRetiredPay': {
    'ui:title': 'Have you ever received military retirement pay?',
    'ui:widget': 'yesNo',
    'ui:options': {},
  },
```
![image.png](https://images.zenhubusercontent.com/5c1047425e37320ceee743c3/395369f0-26d8-4748-b5b9-7bdb604e2534)

4. Training Pay
**disability/file-disability-claim-form-21-526ez/training-pay**
Same for this one as Separation and Retirement Pay
![image.png](https://images.zenhubusercontent.com/5c1047425e37320ceee743c3/be61a1dd-4eca-45af-aa36-687b9b85eeae)

5. New Disability Follow up
**disability/file-disability-claim-form-21-526ez/new-disabilities/follow-up/0**
When choosing a new disability, this form pops up.
This seems to be using the forms component.
`src/applications/disability-benefits/all-claims/pages/newDisabilityFollowUp.js:69`
```
cause: {
        'ui:title': 'What caused this service-connected disability?',
        'ui:widget': 'radio',
        'ui:options': {
          labels: {
            NEW:
              'My disability was caused by an injury or exposure during my military service.',
            SECONDARY:
              'My disability was caused by another service-connected disability I already have. (For example, I have a limp that caused lower-back problems.)',
            WORSENED:
              'My disability or condition existed before I served in the military, but it got worse because of my military service.',
            VA:
              'My disability was caused by an injury or event that happened when I was receiving VA care.',
          },
          updateSchema: (formData, causeSchema, causeUISchema, index) => ({
            enum: getDisabilitiesList(formData, index).length
              ? allCauses
              : causesWithoutSecondary,
          }),
        },
      },
```
![image.png](https://images.zenhubusercontent.com/5c1047425e37320ceee743c3/ee7ffd9c-e79c-47c0-af76-7ee0e9747088)

6. POW
`src/applications/disability-benefits/all-claims/pages/prisonerOfWar.js:21`
```
'view:powStatus': {
    'ui:title': 'Have you ever been a POW?',
    'ui:widget': 'yesNo',
  },
```
![image.png](https://images.zenhubusercontent.com/5c1047425e37320ceee743c3/bb9b97c3-bce3-4f14-87ae-71d445b3c6c8)

7. Would you like to learn more about additional benefits?
**disability/file-disability-claim-form-21-526ez/additional-disability-benefits**
Form component
`src/applications/disability-benefits/all-claims/config/form.js:535`
```
'view:ancillaryFormsWizard': {
              'ui:title':
                'Would you like to learn more about additional benefits?',
              'ui:widget': 'yesNo',
            },
```
![image.png](https://images.zenhubusercontent.com/5c1047425e37320ceee743c3/9368dca0-d8ca-4005-a215-05ca777d5b60)

**Comment by ahay-agile6** [comment]
8. Do you need help buying or modifying your home?
src/applications/disability-benefits/all-claims/pages/adaptiveBenefits.js:10
```
'view:modifyingHome': {
    'ui:title': 'Do you need help buying or modifying your home?',
    'ui:widget': 'yesNo',
  },
```

9. Do you need help buying or modifying your car?
src/applications/disability-benefits/all-claims/pages/adaptiveBenefits.js:14
```
'view:modifyingCar': {
    'ui:title': 'Do you need help buying or modifying your car?',
    'ui:widget': 'yesNo',
  },
```

10. Have you ever been granted an automobile allowance?
src/applications/disability-benefits/all-claims/pages/adaptiveBenefits.js:22
```
'view:alreadyClaimedVehicleAllowance': {
      'ui:title': 'Have you ever been granted an automobile allowance?',
      'ui:widget': 'yesNo',
    },
```

For #8, #9, and #10
![image.png](https://images.zenhubusercontent.com/5c1047425e37320ceee743c3/3c72d177-1f98-4c2d-b668-ce492e584c59)

11. Are you confined to your home or need help with everyday activities?
src/applications/disability-benefits/all-claims/pages/aidAndAttendance.js:5
```
'view:aidAndAttendance': {
    'ui:title':
      'Are you confined to your home or need help with everyday activities?',
    'ui:widget': 'yesNo',
  },
```
![image.png](https://images.zenhubusercontent.com/5c1047425e37320ceee743c3/2fa19945-e208-4cdc-ad44-4ea9f925535a)

12. Does your disability prevent you from holding down a job that you could otherwise do? (This doesn’t include being retired.)
src/applications/disability-benefits/all-claims/pages/individualUnemployability.js:5
```
'view:unemployable': {
    'ui:title':
      'Does your disability prevent you from holding down a job that you could otherwise do? (This doesn’t include being retired.)',
    'ui:widget': 'yesNo',
  },
```
![image.png](https://images.zenhubusercontent.com/5c1047425e37320ceee743c3/da87f2d4-932e-4b7a-bf94-594184846d78)

13. Please tell us what you would like to do.
```
'view:unemployabilityUploadChoice': {
    'ui:title': 'Please tell us what you would like to do.',
    'ui:widget': 'radio',
    'ui:options': {
      labels: {
        answerQuestions:
          'I want to continue online and answer questions about my unemployability.',
        upload:
          'I already filled out VA Form 21-8940 in paper form and want to upload it.',
      },
    },
  },
```
![image.png](https://images.zenhubusercontent.com/5c1047425e37320ceee743c3/d6521110-161f-45ac-9f7f-4b3ef24d3599)

14. Did you spend time in a hospital or under a doctor's care for your service-connected disabilities in the past 12 months?
src/applications/disability-benefits/all-claims/pages/medicalCare.jsx:17
```
unemployability: {
    'view:medicalCare': {
      'ui:title': ' ',
      'ui:widget': 'yesNo',
    },
```

15. Are you employed now?
src/applications/disability-benefits/all-claims/pages/recentEarnedIncome.js:32
```
'view:isEmployed': {
      'ui:title': 'Are you employed now?',
      'ui:widget': 'yesNo',
    },
```

16. Did you leave your job or have you stopped working because of your disability?
src/applications/disability-benefits/all-claims/pages/recentEarnedIncome.js:43
```
leftLastJobDueToDisability: {
      'ui:title':
        'Did you leave your job or have you stopped working because of your disability?',
      'ui:widget': 'yesNo',
      'ui:options': {
        expandUnder: 'view:isEmployed',
        expandUnderCondition: false,
      },
    },
```
![image.png](https://images.zenhubusercontent.com/5c1047425e37320ceee743c3/92ac9ed4-d68b-48be-a7ff-b82d60afd854)

17. If you’re currently serving in the Reserve or the National Guard, does your service-connected disability prevent you from performing your military duties?
src/applications/disability-benefits/all-claims/pages/militaryDutyImpact.js:10
```
disabilityPreventMilitaryDuties: {
      'ui:title':
        'If you’re currently serving in the Reserve or the National Guard, does your service-connected disability prevent you from performing your military duties?',
      'ui:widget': 'radio',
      'ui:options': {
        labels: {
          yes: 'Yes',
          no: 'No',
          reservesNo: 'I’m not serving in the Reserve or the National Guard.',
        },
      },
      'ui:errorMessages': {
        required: 'Please select one of the three options provided',
      },
    },
```
![image.png](https://images.zenhubusercontent.com/5c1047425e37320ceee743c3/d9790c4b-8a9b-4b86-8ab5-a214cb3c934b)

18. Have you tried to find a steady job (substantially gainful employment) since you became too disabled to work?
src/applications/disability-benefits/all-claims/pages/recentJobApplications.js:25
```
attemptedToObtainEmploymentSinceUnemployability: {
      'ui:title': recentJobApplicationsDescription(),
      'ui:widget': 'yesNo',
    },
```
![image.png](https://images.zenhubusercontent.com/5c1047425e37320ceee743c3/51f4b301-e15d-4753-a82f-a49e6691b2de)

19. Did you have any other education or training before you became too disabled to work?
src/applications/disability-benefits/all-claims/pages/pastEducationTraining.js:30
```
receivedOtherEducationTrainingPreUnemployability: {
      'ui:title':
        'Did you have any other education or training before you became too disabled to work?',
      'ui:widget': 'yesNo',
    },
```

20. In the time since you became too disabled to work, have you had any education or training?

```
receivedOtherEducationTrainingPostUnemployability: {
      'ui:title': RecentEducationTrainingTitle,
      'ui:widget': 'yesNo',
    },
```
![image.png](https://images.zenhubusercontent.com/5c1047425e37320ceee743c3/4e88cb44-4b34-429d-a6fb-1f22cc39b6d9)

21. Do you have supporting documents you’d like to upload?
src/applications/disability-benefits/all-claims/pages/uploadUnemployabilitySupportingDocumentsChoice.js:7
```
'view:uploadUnemployabilitySupportingDocumentsChoice': {
    'ui:title': ' ',
    'ui:widget': 'yesNo',
  },
```

22. Is there any evidence you’d like us to review as part of your claim?
src/applications/disability-benefits/all-claims/pages/evidenceTypes.js:8
```
'view:hasEvidence': {
    'ui:title':
      'Is there any evidence you’d like us to review as part of your claim?',
    'ui:widget': 'yesNo',
  },
```
![image.png](https://images.zenhubusercontent.com/5c1047425e37320ceee743c3/8e547a17-9fc0-4311-bd0b-b5afcea44c61)

23. Do you want to upload your private medical records?
src/applications/disability-benefits/all-claims/pages/privateMedicalRecords.js:18
![image.png](https://images.zenhubusercontent.com/5c1047425e37320ceee743c3/10126749-cf1d-4f82-b192-094301ee42ea)

24.
src/applications/disability-benefits/all-claims/pages/homelessOrAtRisk.js:27
```
homelessOrAtRisk: {
    'ui:title': 'Are you homeless or at risk of becoming homeless?',
    'ui:widget': 'radio',
    'ui:options': {
      labels: {
        no: 'No',
        homeless: homelessLabel,
        atRisk: atRiskLabel,
      },
    },
  },
```

25. Please describe your current living situation.
src/applications/disability-benefits/all-claims/pages/homelessOrAtRisk:43
```
homelessHousingSituation: {
      'ui:title': 'Please describe your current living situation.',
      'ui:required': formData =>
        _.get('homelessOrAtRisk', formData, '') === HOMELESSNESS_TYPES.homeless,
      'ui:widget': 'radio',
      'ui:options': {
        labels: {
          shelter: 'I’m living in a homeless shelter.',
          notShelter:
            'I’m living somewhere other than a shelter. (For example, I’m living in a car or a tent.)',
          anotherPerson: 'I’m living with another person.',
          other: 'Other',
        },
      },
    },
```

26. Do you need to quickly leave your current living situation?

```
needToLeaveHousing: {
      'ui:title': 'Do you need to quickly leave your current living situation?',
      'ui:required': formData =>
        _.get('homelessOrAtRisk', formData, '') === HOMELESSNESS_TYPES.homeless,
      'ui:widget': 'yesNo',
    },
```


![image.png](https://images.zenhubusercontent.com/5c1047425e37320ceee743c3/e4728367-6913-482c-aa03-301540567611)

**Comment by ahay-agile6** [comment]
27. Are you terminally ill?
src/applications/disability-benefits/all-claims/pages/terminallyIll.js:17
```
isTerminallyIll: {
    'ui:title': 'Are you terminally ill?',
    'ui:widget': 'yesNo',
  },
```

28.Are you currently a VA employee?
src/applications/disability-benefits/all-claims/pages/vaEmployee.js:5
```
isVaEmployee: {
    'ui:title': 'Are you currently a VA employee?',
    'ui:widget': 'yesNo',
  },
```

29. What type of pay you would like to receive?
src/applications/disability-benefits/all-claims/pages/retirementPayWaiver.js:11
```
waiveRetirementPay: {
    'ui:title': 'What type of pay you would like to receive?',
    'ui:widget': 'yesNo',
    'ui:options': {
      labels: {
        Y: 'I want to receive VA compensation pay.',
        N: 'I don’t want to receive tax-free VA compensation pay.',
      },
    },
  },
```

29. You can’t get VA compensation for the same days you get training pay. If you want to keep your training pay, you’ll need to waive (or tell us you don’t want to get) VA compensation pay for the days you receive training pay. In general, training pay is going to be more than your compensation pay for any given day.
src/applications/disability-benefits/all-claims/pages/trainingPayWaiver.js:20
```
waiveTrainingPay: {
    'ui:title': ' ',
    'ui:description': waiveTrainingPayDescription,
    'ui:widget': 'yesNo',
    'ui:options': {
      yesNoReverse: true,
      labels: {
        Y:
          'I don’t want to get VA compensation pay for the days I receive training pay.',
        N: 'I want to get VA compensation pay instead of training pay.',
      },
    },
  },
```

30. Do you want to apply using the Fully Developed Claim program?
src/applications/disability-benefits/all-claims/pages/fullyDevelopedClaim.js:13
```
standardClaim: {
    'ui:title': 'Do you want to apply using the Fully Developed Claim program?',
    'ui:widget': 'yesNo',
    'ui:options': {
      yesNoReverse: true,
      labels: {
        Y: 'Yes, I have uploaded all my supporting documents.',
        N: 'No, I have some extra information that I’ll submit to VA later.',
      },
    },
  },
```

**Comment by ahay-agile6** [comment]
# Conclusion

We have found only 1 place where the `VaRadio` React Component is being used, right at the beginning of the 21-526EZ.

Remediation is hypothesized to be minimal.

1. "Are you on active duty right now?"  
**/disability/file-disability-claim-form-21-526ez/start**: 
`src/applications/disability-benefits/wizard/pages/start.jsx:28`
```
<VaRadio
      class="vads-u-margin-y--2"
      label={label}
      onVaValueChange={onValueChange}
    >
      {options.map(option => (
        <va-radio-option
          key={option.value}
          name="active-duty"
          label={option.label}
          value={option.value}
          checked={state.selected === option.value}
          aria-describedby={
            state.selected === option.value ? option.value : null
          }
        />
      ))}
    </VaRadio>
```
![image.png](https://images.zenhubusercontent.com/5c1047425e37320ceee743c3/80e6e738-fa77-44d1-b541-549fe7d80513)
