### ISSUE TITLE
Vets API: Timeout external requests

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#53418]
## Problem Statement

Vets API can experience global downtime or significant slowness when a single upstream provider has issues.

Vets API makes many requests to external (or upstream) services. When the upstream provider is having issues with their infrastructure, their response times to us suffer (response times >5 seconds). Vets API response times reflect this slowness and cause cascading issues to unrelated endpoints.

If this remains unaddressed, further global downtime events for Vets API can occur and we may be exacerbating upstream issues by tying up their connections with long running requests.

## What is the acceptance criteria?

- Vets API HTTP requests timeout when running for longer than appropriate (wall-clock timeout).
- Documentation is established for appropriate baseline timeouts to upstream services and how to use them.
- VFS Teams notified of documentation/timeout usage.
- Platform Support is familiar with these requirements for the code review process.

## How should we measure success?

Measurements for success:
- Timeout errors (e.g. Faraday) to upstream services should be reduced
- Timeout errors (i.e. Rack::Timeout) for client requests should be reduced
- Saturation and capacity metrics (e.g. Puma pool capacity, Puma backlog) should be reduced
- Latency and number of downtime events should be reduced

## TODOs

- [ ] Automate collection of in-use upstream service
- [ ] Evaluate appropriate timeouts to upstream services 
- [ ] Determine method to implement a global (wall clock) timeout in Rails
- [ ] Implement global timeout to all external requests
