### ISSUE TITLE
Google Analytics 4 (GA4) Migration

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#53426]
## Problem Statement 
Google will be sunsetting Universal/360 Analytics in July 2024 and will discontinue any tracking and historical data management at that time.  Their new tool Google Analytics 4 (GA4) will replace their current product and will change how events and parameters work on Google Analytics.  **This super epic contains the overall project epics to support this migration initiative.**

## We will know we're done when... ("Definition of Done")
- When all the supporting epics have been completed.
- New GA4 Properties will be created, and accessible to VFS Teams
    - [x] [[GA4] VA.gov - Production](https://analytics.google.com/analytics/web/#/p419143770/reports/intelligenthome)
    - [x] [[GA4] VA.gov - Non-Production](https://analytics.google.com/analytics/web/#/p418218150/reports/intelligenthome)
    - [x] [[GA4] VSP Platform Documentation Sites](https://analytics.google.com/analytics/web/#/p448451986/reports/intelligenthome)

## Known Blockers/Dependencies 
- VFS and Design System team dependencies.
- Staffing dependencies

## Projected Launch Date
April 2024

### Complete
- [x] [**Discovery & Planning**](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/13704)
     - [x] Audit current tracking set up
     - [x] Identify events needed to be migrated to support KPIs
     - [x] [Document findings](https://vfs.atlassian.net/wiki/spaces/AT/pages/1928495134/GA4+discovery)
     - [x] Create GA4 Properties (Prod & Non-Prod)
- [x] [**Implementation & Testing - Web Components & Form Events**](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/51114)
     - [x] Configure events (web components)
     - [x] [Map events](https://docs.google.com/spreadsheets/d/1R0I5_dglyXEXYl0uESUTsSfsyIcBAk2lr7DVrRsx3qY/edit?pli=1#gid=1768618567) and Gtags 
     - [x] Provide data layer code to FE 
     - [x] Test & Validate
- [x] [**Implementation & Testing - VFS Custom Events**](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/47604)
     - [x] [Review custom events](https://docs.google.com/spreadsheets/d/1R0I5_dglyXEXYl0uESUTsSfsyIcBAk2lr7DVrRsx3qY/edit?pli=1#gid=343262001) with VFS team - align on what will/will not migrate
     - [x] Configure events (custom)
     - [x] Map events and Gtags
     - [x] Provide data layer code to FE
     - [x] Test & Validate
- [x] [**Data Integration**](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/47698)
    - [x]  Connect to GA4 to BQ
    - [x]  Map/Translate/Merge GA4 & UA data to common dataset/model in BQ to support Domo dashboards
    - [x]  Test & Validate Domo datasets

---

### Remaining GA4 Tasks (as of July 29, 2024)
- [x] **1 - Data Analysis & Reporting** -- _We are in the final stages of this epic. We are performing some QCs of our reports this week, as GA4 data is flowing in most of our reports as of July 29, 2024. Similar to our GA4 Properties, we will be doing ongoing monitoring to look out for potential data anomalies, or glitches associated with appending GA4 data on top of the original datasets. Our data QC process can be found documented [here](https://vfs.atlassian.net/wiki/spaces/AT/pages/3192389670/GA4+Migration+-+Domo+Data+Mapping+QC+Workstream), along with our working document for which datasets have been updated [here](https://docs.google.com/spreadsheets/d/1mIsJEM5sQFVi8lWIMI6eRiOUQUwO9wdVjjsBis0QqXY/edit?gid=884424480#gid=884424480). We are anticipating being finished as the end of this sprint, Wed, July 31, 2024. The Epic end date has been updated accordingly._
    - [x] Configure new GA4 reports and dashboards
    - [x] Redirect cards on Domo dashboards to new GA4/UA dataset
    - [x] Continuously monitor Domo reports for glitches, data anomalies, or other issues.
    - [x] Finalize GA4 appends, backfills, and open QA-items.

- [x] **2 - Training & Documentation** -- _Updated Epic end date to late August/September 2024_
    - [x] Internal/Confluence GTM/GA documentation is updated
    - [x] Platform Website GTM/GA documentation is updated -- _We've updated some, but not all of our Google Analytics documentation. We performed an [audit](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79980) of which of our pages will need a refresh, and plan to work through this iteratively._
    - [x] Conduct training sessions (publish recording). -- _GA4 training will likely be ongoing through at least the rest of the summer. We have led and recorded three training sessions so far, and our documenting our topics and progress [here](https://vfs.atlassian.net/wiki/spaces/AT/pages/3290660872/GA4+Trainings+How-To+Resources). We may move to team-specific training over the coming months, once we cover the basics in our open trainings. Need to confirm with PO (Ray), what _Done_ looks like from a training perspective._

- [ ] **3 - Miscellaneous Clean-Up Tasks** -- _No direct Epic associated with these tasks, though we are trying to prioritize anything that we might find that to further refine our GA4 Properties._
    - [x] Continuously monitor feedback from teams on tracking in GA4 -- to see if anything is not being tracked as expected.
    - [ ] Wrap up lingering, findings from events, mostly set-up directly in GTM
         - [ ] [Implement Findings from Spike on Legacy Sites Tracking in GA4 #88128](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88128)
         - [ ] [Transition GTM Triggered Events to GA4 -- Continued Work #89345](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89345)

**Comment by michelle-dooley** [comment]
![image](https://user-images.githubusercontent.com/93597659/219437220-b1c388df-f3a2-4116-856c-4302e409a7c0.png)

**Comment by annekerr49** [comment]
no roadmap-DMC label

**Comment by michelle-dooley** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/93597659/7dc55e51-3bd0-4008-a9d1-ec6b915c7ace)

**Comment by michelle-dooley** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmRMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--572732fbc021c14ec95047093c6d13901caae8fe/image.png)

**Comment by EWashb** [comment]
Can we confirm/update the target delivery date @michelle-dooley ?

**Comment by EWashb** [comment]
Shift in delivery date to be completed April 2024 to allow for proper documentation and team support. 

The timeline shift occurred due to lack of proper GA specialist and dependencies on cross team collaboration.

**Comment by michelle-dooley** [comment]
And the updated ToTs slide for reference...
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdm1kIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9d6012ddf251829f7ef9d73749fdf83e12844f3d/image.png)

**Comment by EWashb** [comment]
On track to migrate to GA4 by April 2024, well before Universal's deprecation.

**Comment by humancompanion-usds** [comment]
@raywangoctova and @johnny-jesensky-adhoc - Can you update this issue with what is remaining to be done? The target date is past due and I know we made the transition but that there are some clean-up tasks. Just trying to get a sense of when you all get to slide this over to the "Done" column and celebrate! 🍾

**Comment by johnny-jesensky-adhoc** [comment]
@humancompanion-usds -- Yes, I'll go ahead and update this one with the latest updates, and what documentation and QA tasks we're in the process of finalizing. Will flag once updated.

FYI @raywangoctova

**Comment by johnny-jesensky-adhoc** [comment]
Made a few updates to the body of this GA4 epic today (7/29). See section --> _Remaining GA4 Tasks (as of July 29, 2024)_. 

There will likely be some continual tasks such as updated documentation and GA4 support and training that will be on-going in order to best serve VFS Teams. I'll plan to connect with Ray around the best threshold for meeting _Done_ for those sub-epics. 

I should have more insight into our Data and Reporting QC after this sprint, so will plan to provide another update/refresh on that piece.

**Comment by johnny-jesensky-adhoc** [comment]
Hi @raywangoctova -- I just reviewed this super epic. As of today (9/24), just about all of the migration work is completed, including:

- Successfully migrated over to two new GA4 Properties ([[GA4] VA.gov Production](https://analytics.google.com/analytics/web/#/p419143770/reports/intelligenthome) & [[GA4] VA.gov Non-Production](https://analytics.google.com/analytics/web/#/p418218150/reports/intelligenthome))
- Fully updated and QA'd our downstream reporting in Domo to utilize GA4 data.
- Led a 7-part GA4 Training series that is recorded and available to VFS Teams.
- Published some updates to docs on our Platform Website, including How-To resources.

Any remaining work we have is mostly around additional updates to our documentation and training, and optimization around some of the tracking that was implemented for efficiencies, redundancies of duplicate firings, etc. -- which will likely always be an ongoing effort to a certain extent. 

Some of that work is mostly covered as part of this second epic -- _**GA4: Documentation, Training, & Communications**_ https://github.com/department-of-veterans-affairs/va.gov-team/issues/53417, and the optimization work will likely be a small number of stories.

**My proposal** -- I would recommend we move _this_ super epic to _Done_, as most of the original criteria is completed, and closed:

- [x] [Discovery & Planning](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/13704)

 - [x] [Implementation & Testing - Web Components & Form Events](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/51114)
 - [x] [Implementation & Testing - VFS Custom Events](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/47604)
 - [x] [Data Integration](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/47698)
 
 and keep the epic on documentation and training open (https://github.com/department-of-veterans-affairs/va.gov-team/issues/53417), while fleshing out a more concrete definition of done around what constitutes a _complete_ set of training resources for Platform on GA4.

We can plan to discuss in our sync this upcoming Thursday (9/26).

**Comment by johnny-jesensky-adhoc** [comment]
@raywangoctova -- as discussed in our PO sync today, moving this super epic to _Done_.
