### ISSUE TITLE
[SLO] Break down puma notifications on a per service basis

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#53425]
## Description

As we are gathering new metrics, the data is heavily skewed due to it have 1 centralized location. We should be reporting on a per service basis to gather appropriate metrics and be able to create action items accordingly

For now, let's break this into the 2 bulkheads that we have, then after EKS is live, break this out further with other stories.

## Tasks
- [x] Break down puma notifications per bulkhead
- [x] Spin up tickets for EKS

## Acceptance Criteria
- [x] puma notifications are broken out per bulkhead

## How to configure this issue
- [ ] _Attach a Milestone_
- [ ] _Story points_
- [ ] _Sprint assigned if pulling into sprint_
- [ ] _Epic assigned_
- [ ] _Team label assigned_

**Comment by oseasmoran73** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/50419

**Comment by oseasmoran73** [comment]
@npeterson54 Given that we are now breaking them into per bulkhead/service, To what extent do we want to add to Vets API Dashboard? Thoughts? 

I feel it can go both ways. It may be helpful for specific service, but also can be congested / create a lot of "noise"

**Comment by npeterson54** [comment]
I would err on the side of adding to much rather than too little.  We can always trim the fat.

**Comment by oseasmoran73** [comment]
@npeterson54 Moved to the review column

**Comment by npeterson54** [comment]
Looks good to me, closing out
