### ISSUE TITLE
Migrate call to /getPDF endpoint from eVSS to Lighthouse - 526ez

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#53437]
## Issue Description
Form 526 currently calls eVSS endpoint /getPDF for getting documents. This call needs to be  migrated to Benefits Document Service API in Lighthouse as part of overall eVSS migration to Lighthouse.

## Need To Know
- [ ] Lighthouse team Firefly is working on this and expects to have it ready for integration test by March 2023
- [ ] Team firefly contacts - https://app.mural.co/t/agilesixapplications0942/m/agilesixapplications0942/1674666875176/5bffb27d080685913fc74b5e4e2179511e4c2089?sender=ub46ab2ca03c3ddd9a8ac0157

---
## Tasks
- [ ] All getPDF method to claims service
- [ ] Make provider? - figure out part of Backup submission discovery ticket
- [ ] unit test

## Acceptance Criteria
- [ ] The call to endpoint /getPDF is migrated to the Lighthouse API
- [ ] /getPDF functionality does not change (need to understand what part of the submission uses this API and how it functions today)
- [ ] Tested against LH sandbox

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by navaeddie** [comment]
The current implementation of the [getPDF endpoint](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/evss/disability_compensation_form/service.rb#L76) which relies on eVSS is used  in two methods, both written within the Sidekiq::Form526BackupSubmissionProcess::Processor:
1. [line 329](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/sidekiq/form526_backup_submission_process/processor.rb#L329), within #get_form526_pdf
2. [line 405](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/sidekiq/form526_backup_submission_process/processor.rb#L406), within (a subclass) NonBreakeredProcessor#get_form526_pdf

**Comment by navaeddie** [comment]
Just saving some screenshots that capture SimpleCov's current test coverage around a few methods that rely on eVSS's getPDF api.

![first.png](https://images.zenhubusercontent.com/63dd30048b2159302590655a/1d8515ee-00f7-4498-9fb5-b98de069f0e9)

![second.png](https://images.zenhubusercontent.com/63dd30048b2159302590655a/7070b557-9a98-44bf-b746-e3661e1e39db)

![third.png](https://images.zenhubusercontent.com/63dd30048b2159302590655a/9d0660e3-ee03-4fcc-858b-2742b819321b)

**Comment by alatempa24** [comment]
Duplicated by team Carbs issue #82245
