### ISSUE TITLE
[SLI][DD][Conf] Documentation on Vets API Dashboard

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#53432]
## Description

With the latest vets api dashboard created, we want to have documentation around it for our team, platform, and IC in their playbook for reference

## Tasks
- [x] Create documentation regarding dashboard 
- [x] Fill in with appropriate details

## Acceptance Criteria
- [x] Documentation exists, reviewed, and approved by appropriate parties

**Comment by oseasmoran73** [comment]
[Confluence](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2537488689/Vets+API+Dashboard) created for it. Can we get the team to review @npeterson54 and get feedback on it?

**Comment by npeterson54** [comment]
I think this looks good, would like others on the team to review.

**Comment by oseasmoran73** [comment]
CC @harshil1793 @holdenhinkle When y'all get a chance, can you review the document?

**Comment by oseasmoran73** [comment]
Got some great feedback from Holden! Re-pinged @harshil1793 to review it

**Comment by harshil1793** [comment]
Just reviewed it. LGTM :)

**Comment by oseasmoran73** [comment]
@npeterson54 Got review from TT3. I think this is ready to be closed out and shared with others if needed

**Comment by oseasmoran73** [comment]
@npeterson54 Closing. Feel free to reopen if you dont think the AC has been met
