### ISSUE TITLE
Create web components that remove dependency on Formation

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#53436]
## Description
As part of the VA Design System to USWDS v3, the DST needs to remove the dependency on Formation. The team has already built web components to replace the React components but there are still a few remaining React components that need to be replaced with a web component version. Also, we will update the Forms library with web components to replace React components that are in use in Forms. 

As part of this epic, we will need to deprecate the remaining  React components. This means VFS team will need to update any applications using a React component to the web component version.

## Details
There are the areas of work that are to be done as part of this epic: 
- Build web components for: maintenance banner, header, footer and icons
- Deprecate React component library [Plan for deprecation](https://vfs.atlassian.net/l/cp/86bgiY8p)
- Update Forms library with web-components [See discovery ticket for details](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1375)  

**Q2 2024**
Remaining work for this epic includes: 
- Full header and footer as web-components
- Expanding Group component design and replacement of current instances so we can finally, fully deprecate the React library

## Tasks
- [x] Build web component for maintenance banner
- [x] Build web component for  icons
- [x] Deprecate React component library 
- [x] Update Forms library with web components 
- [x] Replace expanding group 

## Acceptance Criteria
- [x] Web components built for maintenance banner,  and icons
- [x] React components have been replaced with web component versions 
- [x] Replace expanding group
- [x] Forms library is using web components

**Comment by annekerr49** [comment]
Carol this item is in draft form on ZenHub, but in progress in DEproducts Board. Should we move this ticket to in progress on the ZenHub Planning Board?

**Comment by caw310** [comment]
@annekerr49 On the Design System Team Zenhub board this has been a current initiative that is in progress. I'm not sure which Zenhub board you are referring to.

**Comment by humancompanion-usds** [comment]
This initiative is long and tough road to hoe. We have made some progress:

* Minimal variations of the header and footer have been built as web-components.
* React component library is just about gone. There is one component that needs a design in order to be replaced.
* The Veteran-facing Forms team has added web-components to the Forms Library.
* Aside from the full version of header and footer, all web-components have been created.

Remaining work:
* Full, federal CIO versions of header and footer as web-components
* Expanding Group component design and replacement of current instances so we can finally, fully deprecate the React library

**Comment by humancompanion-usds** [comment]
@caw310 - We need to update this epic to better reflect a true start and end date that matches our roadmap. Thanks.

**Comment by humancompanion-usds** [comment]
We're holding on this for the moment as we focus on other things. We'll pick up the design again next sprint.

**Comment by caw310** [comment]
Closing this initiative as the work outlined has been done. The three remaining web components will be separated out into three epics: 
- Create header web-component
- Create footer web-component
- Create sidenav web-component
Any work for those web components will be associated with those epics.
