### ISSUE TITLE
VAOS - Update VistA testing environment in staging 124/125

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#53439]
This is an internal epic for the VAOS FE team to do research and provide recommendations on how to support updating the VAOS VistA testing environment from 983 and 984 (which is the current) to 124 and 125. 

### Product Checklist 
<details>
  <summary>Toggle Product Checklist</summary>

## Product
- [X] Set up an internal call to map out the user flow in VAOS 2/14
- [ ] Create a copy of the user flow and attach link to Mural 
- [ ] 
</details>

### Engineering Checklist 
<details>
  <summary>Toggle Engineering Checklist</summary>

### Engineering 
- [ ] Project Description.
- [ ] Are UI designs/ specs available/ready? If yes, attach specs. (We are assuming the design specs have been approved by the accessibility team if they're ready)
- [ ] Are there any deadlines that need to be met?
- [ ] What is the roll out plan? (Do we need a feature toggle? is this going to be available to every user immediately or do we want to roll out to a few users first)
- [ ] Does this project require api integration? if yes, what api endpoint are we integrating with and what is the expected response body?
- [ ]  Do we want to capture analytics for this projects (i.e. update GA, add logs to grafana/datadog etc)?If yes, what metrics would we like to capture?

</details>

**Comment by ldelacosta** [comment]
No need to keep this epic. Our team did not handle this work. Closing it out. cc: @JRRoof
