### ISSUE TITLE
Research the use of Persistent Volumes with EKS for Drupal Cache

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#53452]
# Description
Given the fact that the `content-build` Drupal cache takes a very long time to resolve and requires an internal connection to VA resources, we should research the use of persistent volumes in EKS to store the Drupal cache for use by multiple preview environments. Using a persistent volume to store the Drupal cache is more efficient since the volume could be mounted by multiple PEs instead of retrieved individually for each PE.

# Tasks
- [ ] Determine what technology could be used for the persistent volumes in EKS
- [ ] Could a single persistent volume be used by multiple preview environments?

# Acceptance Criteria
- [ ] An assessment of how Drupal cache might be retrieved to a persistent volume and mounted in EKS is available in Confluence or in this ticket

**Comment by powellkerry** [comment]
Began researching how drupal cache works and how we might store it in persistent volumes. No direction found yet.

**Comment by powellkerry** [comment]
Solutions and ideas:
- Pull S3 tgz file for drupal cache, unzip it and use it in the content-build directory. (This does not save any processing time or improve memory and storage on the image)
- Unzip tgz file for drupal cache in S3 and configure content build to use it without copying it to the image. The unzip and build could be done as a scheduled task in GHA or could be triggered when changes are made to content-build. (There is a lot of unknowns and logic hunting involved in this option, but it would speed up the build)
- Use persistent volumes like EBS. (I have not found any documentation or tutorials on how to do this with drupal)

**Comment by JoeTice** [comment]
Sprint 21 Update: This does not currently seem like a viable path for MVP, we will create a ticket to re-evaluate this approach Post-MVP
