### ISSUE TITLE
Implement Persistent Volumes in EKS for Drupal Cache

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#53455]
# Description
Implement the plan for a persistent volume that contains the Drupal cache and refreshes it periodically defined in [this ticket](https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/53453).

# Tasks
- [ ] Implement the plan
- [ ] Test the solution
- [ ] Record what is out of scope for this implementation and create a ticket for a post-MVP version of it
   - Ability to refresh the Drupal cache for a given PE
   - Ability to retrieve the latest version of the Drupal cache instead of using the persistent volume
   - Ability to load a specific version of the Drupal cache into a persistent volume

# Acceptance Criteria
- [ ] The PE's frontend uses a persistent volume to load the Drupal content instead of retrieving a copy during the building of the frontend

**Comment by JoeTice** [comment]
Sprint 21 Update - This task is OBE, it was dependent on a viable option from [53452](https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/53452)

However, that ticket has not revealed any viable options currently. We will re-evaluate the approach post-MVP, and create new tasks for this work if viable.
