### ISSUE TITLE
[Design] Update wireframes to prioritize info messages (for answering "no" to travel question.)

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#53461]
## Description 

It was determined that equal priority shouldn't be given to the travel information when a Veteran is NOT eligible for travel (i.e., never presented with travel questions) and successfully checks in for their appointment. 

This likely also applies to the scenario when a Veteran says "no" to travel. 

Therefore, how might we update the wireframes for those two scenarios? 

[Currently, both scenarios use the following wireframe.](https://share.goabstract.com/6b69924f-904b-4d78-b5a1-4c40ed65e4d2?collectionLayerId=fda84b41-9434-41b6-a2c4-7b6007737eb3&mode=design&sha=latest)

## Tasks

- [x] Create branch
- [ ] Update wireframe(s) with content
- [ ] Get feedback from team
- [ ] Get feedback from engineers, in case, for example, it's updating a component that's being used for appts that impact other pages, which might need to be avoided 

## AC

- [x] Branch created
- [ ] Wireframe(s) created
- [ ] Feedback received from team 
- [ ] Alert product and engineers of finished work

**Comment by zach-park** [comment]
@benbrasso-agile6 , does this also apply to other scenarios that show two equal priority messages like when an API error happens or a travel claim already exists? I've attached the screenshot below.

[Screenshot 2023-03-02 at 8.19.58 AM.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/61b9ee63-d752-4e30-8a8d-514b759f7a38)?

**Comment by benbrasso-agile6** [comment]
@zach-park I actually think that [this wireframe](https://app.abstract.com/projects/ab30c34e-e2f9-4d3e-bb96-3b683b006c24/branches/3c784fa2-f86a-42b7-b1e4-f0fd5f3c1aa3/commits/6005ff435b0cdf911ee6e2ba4e041760afd61482/files/585436fe-2120-45f4-b4f7-fbae01d258d9/layers/5619FA67-59FE-4D71-9670-2D8A842A5AA4?collectionId=3e7034be-0a0a-4895-8cf2-246a3d3ecb52&collectionLayerId=fda84b41-9434-41b6-a2c4-7b6007737eb3&mode=design&sha=latest) is okay to use for this scenario. I don't think there's any work needed on this ticket any longer. 

We could update those other wireframes that you provided a screenshot for. But, those have already tested well with Veterans. So, changing them now seems unnecessary.

**Comment by zach-park** [comment]
That sounds great. Thank you!

**Comment by benbrasso-agile6** [comment]
Closing, no longer needed
