### ISSUE TITLE
External Connections - Required Field and Control Review

### ISSUE THREAD

**Issue by gary-fallon** [department-of-veterans-affairs/va.gov-team#53464]
## Description
ACTION REQUIRED: Completion of new required field in eMASS and review of External Connections controls.

![image.png](https://images.zenhubusercontent.com/6123becac1cf6c603d1eeecd/7a100f4b-f6cc-477f-aa43-6ba8eb7d373e)https://dsva.slack.com/files/UMSRG1881/F04PAFXHEQZ/image.png

![image.png](https://images.zenhubusercontent.com/6123becac1cf6c603d1eeecd/f610c787-bb54-4e28-b519-8b97a86c747b)

![image.png](https://images.zenhubusercontent.com/6123becac1cf6c603d1eeecd/4b82a7e6-957a-458c-922c-805945fba9b9)

![image.png](https://images.zenhubusercontent.com/6123becac1cf6c603d1eeecd/a867621c-8772-4e44-9650-cd01f604c50d)

## Tasks
The following tasks must be reviewed and completed as necessary.
- [ ] Ensure that all connections to the Internet are routed through a Trusted Internet Connection (TIC) gateway.
- [ ] Initiate the field completion by no later than 2/24/2023.
- [ ] Populate the required filed by no later than 2/24/2023.
- [ ] Review the "External Connections" controls listing and resolve outstanding POA&Ms by no later than 3/10/2023.
- [ ] Review entered data (ISSO/ISO) by no later than 3/31/2023.

## Acceptance
The following tasks must be completed before this issue can be considered done.
- [ ] Review for accuracy and completeness.
