### ISSUE TITLE
Remove DS Logon from sign-in options on VA pages

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#53466]
## Issue Description
DS Logon will phase out starting in May 2023 and finishing in September 2023. We'll be removing content about DS Logon in several tickets and phases. This ticket is for removing DS Logon from lists of sign-in options in Drupal page content and from the react widget sign-in blocks.

We'll coordinate the timing for this with Carl on the identity team.

---
## Tasks
- [ ] Audit Drupal pages and identify content to update
- [ ] Suggest revisions to Drupal content and react content in sign-in blocks
- [ ] Make Drupal changes
- [ ] Coordinate updates to sign in react widgets with PW

## Acceptance Criteria
- [ ] DS Logon no longer appears as a sign in option on VA.gov

**Comment by mistymg** [comment]
Ticket was moved to Closed column but not actually closed.
