### ISSUE TITLE
[Design] HLR: Introduction Page Improvements

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#5347]
## User Story:
As a veteran, I need a submit requests for higher level review in an easy to navigate and understand fashion so that I can successfully get my benefits.

After the usability testing research, we found some opportunities to enhance the user experience on the Introduction Page to the HLR form. Some of these improvements include:

- Consider adding an info box about the Opt out process, or adding a F.A.Q. section (why should I do this, what are the benefits, what are the implications, what the difference between new and old appeals process? etc.)
- Increase visibility by moving info about New Evidence up to the first paragraph (with the link “Learn more about review options”
- Consider if more info about this rule is needed on this page

## Tasks
- [x] Revise intro page mockup to incorporate recommended design changes
- [x] Communicate with Christian to ensure conceptual symmetry

## Acceptance Criteria:
- [x] Updated intro page mockup has been delivered
- [x] Design reviewed and accepted by design team

## Configuration
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
Ticket is complete and new design can be found here: https://vsateams.invisionapp.com/share/W5U21BDFTQK#/404076957_Signed_In_-_File_An_HLR

Note: We found that the 'what are the benefits of opting in?' dropdown only contained two known benefits, and we'd like to speak with AMO to know if we could add more. Nice to have, but not a 'must have'.
