### ISSUE TITLE
[Process] Create a rough-draft monitoring roadmap

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#53470]
Currently certain monitoring channels are not as real-time as we need them to be in order to stay ahead of any incidents that occur.

In order to proactively respond to incidents, we need to set up more robust monitoring.

We should create a rough-draft plan for how we can ruggedize our monitoring, especially in the short term. This outline should be formatted as a "good-better-best", "now-later-someday", etc doc. It should be detailed and actionable, especially in the short term, but with strategies for improvement as time goes on.

This is NOT a manifesto. This is a reference.

AC:
- [x] Document created: [Monitoring Roadmap](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/engineering/MonitoringRoadmap.md)
- [x] Document reviewed by all team members
- [ ] Tickets created for short term plan

**Comment by kjduensing** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/engineering/MonitoringRoadmap.md
