### ISSUE TITLE
Update styling of content (Hours of Operation, Account Number, Apostrophes and Quotation Marks)

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#53489]
## Issue Description
As part of the staging review for Medical Copays there as a styling update that was not addressed back in 2021. This issue is to pull that work forward. 

Original Ticket =[ [Content styleguide] Content doesn't align with style guidance in VA.gov content style guide (05.08.1) #33947](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/33947)

---
## Tasks
- [ ] The way the hours of operation are written doesn't match our style.
- [ ] Account number is not sentence cased.
- [ ] Curly apostrophes and quotation marks aren't used throughout.

## Acceptance Criteria
- [ ] Update the content to align with style guide
---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
