### ISSUE TITLE
[FE] [BUG] Start pre-check-in link is not correctly styled

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#53497]
## User Story

Start link is missing action link styling:

![Screenshot 2023-02-10 at 09.59.36.png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/3245f118-cea1-4284-a0ac-f3bebcca9963)

## Tasks
- [x] [FE] fix styling
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by acrollet** [comment]
Fixed & validated on staging: https://dsva.slack.com/archives/C02G6AB3ZRS/p1676057757830259?thread_ts=1676052217.461759&cid=C02G6AB3ZRS
