### ISSUE TITLE
Move marital status and dependent children questions

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#53495]
## Issue Description
During the design intent for adding copays to the FSR it was brought up that certain questions should be moved in the order of the FSR form. This is something that we will revisit as we dig into the streamlined waiver work. I am creating this ticket as a reminder to address this as we embark on the streamlined waiver work. 

Original Ticket - [#42558](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/42558)

---
## Tasks
- [x] Consider order of FSR Form questions in design  - move marital status and dependent children questions to the first step in the FSR (1 of 7 veteran information) 

## Acceptance Criteria
- [x] Questions have been ordered appropriately to optimize user clarity across the experience. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mgleo** [comment]
SW Waiver Desktop prototype for reference on order: https://preview.uxpin.com/6940f648e5994b8fad9550934a5530b4cd73cacb#/pages/163500315/simulate/sitemap?mode=cvhid

**Comment by Dr-Pongo** [comment]
Created frontend ticket to address changes: **[FSR] SW - Move marital status and dependents pages [#61862](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/61862)**
