### ISSUE TITLE
Update number of days to complete disability-related claims in February 2023

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#53493]
## Issue Description
We need to update the number of days it takes to complete disability related claims. Sitewide content needs to email Tanekwa Bournes on the first of the month to get the number from the previous month and input into Drupal.

This needs to be done on the following pages:
https://www.va.gov/disability/after-you-file-claim/
https://www.va.gov/disability/how-to-file-claim/

## Tasks
- [x] Email Tanekwa for most recent number (Randi)
- [x] Input number and new month into both Drupal pages (Aliyah)
- [x] Review and publish (Megan)

## Acceptance Criteria
- [x] Most current number of days is on live site.

**Comment by RLHecht** [comment]
@aliyah February's number is 102.2. Thanks!

**Comment by aliyahblackmore** [comment]
Thanks Randi! 

Hi @megzehn this is ready for you! 

The VA claim process after you file your claim
**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=870

How to file a VA disability claim 
**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=905

**Comment by RLHecht** [comment]
thanks all! I published these.

**Comment by RLHecht** [comment]
These pages are live. Closing!
