### ISSUE TITLE
Production Certs and Buckets

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#53500]
**Problem Statement**
To go into **production** migration with additional confidence, Tech Team 1 needs to complete a double/triple check of certs and buckets (outlined in tickets nested in this epic).

**Issue Description**
This will confirm all certs in production are present and all buckets are present in S3
_Additional documentation and/or slack threads linked here_

---
**Tasks**
- [x] Verify srv/vets-api/secret/production certs (ticket below)
- [x] Verify Production S3 buckets (ticket below)
- [x] Confirm certificates in /srv/vets-api/secret directory (ticket below)
- [x] Confirm /srv/vets-api/src/config/ file paths have been updated to /app/config (ticket below)

**Acceptance Criteria**
- [x] Verification tickets associated with this epic are complete

**Comment by RachalCassity** [comment]
[PR ](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1463)

**Comment by laineymajor** [comment]
@RachalCassity before you sign off today, please make sure this epic and subsequent tickets are updated. Thanks!!

**Comment by laineymajor** [comment]
Closing as all tickets under this epic are now complete. @RachalCassity for visibility.
