### ISSUE TITLE
[FE] [PRE-CHECK-IN] Fix canceled appointment behavior & messaging when canceled appointment is in same clinic

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#53508]
## Background

This is a follow-on from #51862 - when there is a canceled appointment and a valid appointment in the same clinic at the same time, we [show the canceled appointment messaging](https://dsva.slack.com/archives/C02UP02HHGX/p1676050707601009?thread_ts=1673458292.082829&cid=C02UP02HHGX). We should instead show the generic error page with the `possible-canceled-appointment` error code.

## How to reproduce

- Create an appointment for a given clinic at a given time
- Cancel that appointment
- Create a new appointment for the same clinic at the same time
- Generate a pre-check-in link by calling initiate-precheckin directly with both appointment IENs

Example response that produces the error:
```
[
  {
        "clinicName": "STG/ECHO/3",
        "appointmentIen": 36866,
        "stationNo": "530",
        "clinicIen": 464,
        "checkedInTime": "",
        "kind": "clinic",
        "eligibility": "INELIGIBLE_BAD_STATUS",
        "clinicPhoneNumber": "555-555-5555",
        "clinicLocation": "SECOND FLOOR ROOM 2",
        "clinicStopCodeName": "CARDIOLOGY",
        "doctorName": "",
        "checkInSteps": [
            {
                "status": "PRE-CHECK-IN STARTED",
                "dateTime": "2023-02-10T14:47:21",
                "ien": 1
            }
        ],
        "clinicFriendlyName": "ECHO CLINIC 3",
        "startTime": "2023-02-14T08:00:00",
        "clinicCreditStopCodeName": "",
        "facility": "VISTA-API STAGING",
        "checkInWindowEnd": "2023-02-14T08:15:00.000-05:00",
        "checkInWindowStart": "2023-02-14T07:15:00.000-05:00",
        "status": "FUTURE"
    },
    {
        "clinicName": "STG/CARDIO/3",
        "appointmentIen": 36865,
        "stationNo": "530",
        "clinicIen": 463,
        "checkedInTime": "",
        "kind": "clinic",
        "eligibility": "INELIGIBLE_BAD_STATUS",
        "clinicPhoneNumber": "555-555-5555",
        "clinicLocation": "SECOND FLOOR ROOM 2",
        "clinicStopCodeName": "CARDIOLOGY",
        "doctorName": "",
        "checkInSteps": [],
        "clinicFriendlyName": "HEART CLINIC 3",
        "startTime": "2023-02-14T08:00:00",
        "clinicCreditStopCodeName": "",
        "facility": "VISTA-API STAGING",
        "checkInWindowEnd": "2023-02-14T08:15:00.000-05:00",
        "checkInWindowStart": "2023-02-14T07:15:00.000-05:00",
        "status": "CANCELLED BY CLINIC"
    }
]
```

## Tasks
- [ ] [FE] show the generic error page with the `possible-canceled-appointment` error code in this situation
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by wullaski** [comment]
@acrollet closing this as it couldn't be reproduced locally.
