### ISSUE TITLE
[FE] Profile 2.0: Build the profile header

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5350]
## User story

As a user, I need to easily be able to see my name and other personal information information in my profile so I know I'm in the right place.

## Additional background

Epic #5346

## Design & Specs

- [InVision prototype](https://vsateams.invisionapp.com/share/FJW9OGY2B9A)
- ["Profile Header" build specs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Design/design-specs/profile-header.md)

![header](https://user-images.githubusercontent.com/60523453/75922849-db11b280-5e31-11ea-8cab-864ff5b78018.png)

<img width="642" alt="profile-header specs" src="https://user-images.githubusercontent.com/58752772/78279404-eead4900-74c3-11ea-95ea-6df2b147613c.png">

## Tasks

- [ ] Build the new profile header.
- [ ] Implement correct copy.
- [ ] Get Tressa to test out the new header and make sure it looks OK.

## Acceptance criteria

- [ ] New header has been built and reviewed by Tressa.
