### ISSUE TITLE
Review two ID types (EDIPI and DFN) with Platform Identity team

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#53519]
## Issue Description
Discuss with platform identity team the current existence of fetching an MPI profile from the two user identifiers we will work with MCP notifications (EDIPI and DFN). 

---
## Tasks
- [x] Connect with Platform ID Team
- [x] Research existing or editable areas for getting profile from identifier
- [x] Determine next steps for allowing profile to be fetched if needed

## Acceptance Criteria
- [ ] Understanding if both ID types will work for purposes of identifying Veterans for new MCP notification. 
---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Rolling over to S95 with UAT taking place with DMC last week [#55137](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/55137)
