### ISSUE TITLE
[Design] Higher Level Review - Opt Out Page Improvements

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#5351]
## User Story:
As a veteran, I need a submit requests for higher level review in an easy to navigate and understand fashion so that I can successfully get my benefits.

After the usability testing research, we found some opportunities to enhance the user experience on the Opt Out Page to the HLR form. Some of these improvements include:

- (idea and design by Riley Orr). Move the Opt Out page to the Contested Issue page to make it contextual. Allow user to know what claim/issue specifically this opt out action is for.
- Consider reworking copy to make language less “scary” and “intimidating” (phrases used by users)

## Tasks
- [x] Revise opt out page mockup to incorporate recommended design changes
- [x] Communicate with Christian to ensure conceptual symmetry

## Acceptance Criteria:
- [x] Updated opt out page mockup has been delivered
- [x] Design reviewed and accepted by design team

## Configuration
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
The acceptance criteria for this ticket has been met and the design can be viewed here:

https://vsateams.invisionapp.com/share/W5U21BDFTQK#/404526248_HLR-Contested-Issues-Default

Note: Let's see if we can communicate with AMO to make this language less intimidating. New ticket will be necessary to review language with AMO and content team.
