### ISSUE TITLE
[eFSR] Add interactions to FSR prototype for user research

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#53518]
## Issue Description
A shortened prototype is needed for user research in March. Because of timing and limitation in access to prototyping software, this prototype will only be available as a Desktop prototype and will not include every section of the FSR form

---
## Tasks
- [x] _Discuss what to include on this simplified prototype_
- [x] _Make any necessary input field updates to prototype _
- [x] _Add interactions to prototype _
- [x] _Test prototype _

## Acceptance Criteria
- [x] _Interactions have been added on specific pages_
