### ISSUE TITLE
Establish Swagger Doc for VBS -MCP New Statement Notification 

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#53517]
## Issue Description
During weekly touchpoint with VBS to progress '_MCP notification for new statement'_ work forward we identified the need to establish a swagger doc. This doc should contain info about the endpoint such as (endpoint name, headers, body, body attributes).

---
## Tasks
- [x] Build a swagger doc and share with VBS 
    - [x] Name endpoint
    - [x] Determine needed data for endpoint
    - [x] Document data
    - [x] Specify JSON fields within body file

## Acceptance Criteria
- [x] Swagger has been established and shared with VBS Team
---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
