### ISSUE TITLE
[EOAS] Switch to SSO prod URLs in staging

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#53521]
## Background
EOAS reached out this morning (02/10/2023) to let us know that the SSO version of their production URLs are ready to test with in staging. We have been asked to use `vaww.ssoboss.cem.vaec.va.gov` as the new host. This switch should be made in staging first so that we can verify that submissions work correctly before moving this over to production.

## Context
* We switched over to the non-SSO version off this host on 02/06/2023
* Existing host: `ssobeta.cem.vaec.va.gov`
* New host:  `vaww.ssoboss.cem.vaec.va.gov`
* Relevant file: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/fwdproxy-vagov-staging.yml#L142-L149
* Preneeds form url: https://staging.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/introduction

## Next steps
If this is successful, then we should revert the host for staging back to `ssobeta.cem.vaec.va.gov` and update the production host to `ssoboss.cem.vaec.va.gov`

## Tasks
- [x] Confirm that submissions work in staging before making any changes
- [ ] Switch URL in staging fwdproxy config to requested one
- [ ] Test to make sure that submissions still work in staging

## Acceptance Criteria
- [x] Submissions have been verified to succeed before any changes have been made
- [ ] Staging fwdproxy URL has been updated
- [ ] Preneeds submissions continue to work as expected
