### ISSUE TITLE
Design | Profile |  Notification settings | Update Sketch files

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#53529]
## Background

We need to update all the notification settings screens to reflect the following changes:
- removing the "don't notify me" option
- changing radio inputs to checkboxes
- (maybe - see how it looks) add a horizontal rule between each notification, and a bolder border between each section, like the [prototype](https://codepen.io/surfbird/pen/gOjmPyj)

## Tasks
- [x] Update Sketch files
- [ ] Have another team member validate

## Acceptance Criteria
- [ ] All desktop and mobile screens are updated
- [ ] Team member has reviewed
-
## Validation
- Any team member can validate by reviewing the Sketch [desktop](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c) and [mobile](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/p/B5792AF8-87F2-496D-AE7A-DAD1448A6018/canvas) screens

**Comment by BerniXiongA6** [comment]
@andaleliz and I met to write and pre-refine this ticket, and added it to Sprint 4 epic. cc: @Samara-Strauss

**Comment by andaleliz** [comment]
Requested validation in [Slack](https://dsva.slack.com/archives/C909ZG2BB/p1677188493724699).

**Comment by BerniXiongA6** [comment]
@andaleliz my feedback is saved in [Slack](https://dsva.slack.com/archives/C909ZG2BB/p1677188493724699).
