### ISSUE TITLE
[FE] Profile 2.0: Build the Contact information section

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5353]
## User story

As a veteran, I need to be able to easily find and update my contact information so the VA can reach me at the right places.

## Additional background

Epic #5346

## Design & Copy

WIP

## Tasks

- [ ] Build the Contact information section.
- [ ] Implement correct copy.
- [ ] Get Tressa to test out the new header and make sure it looks OK.

## Acceptance criteria

- [ ] New header has been built and reviewed by Tressa.

**Comment by tressaellen** [comment]
Here is the updated email address section for personal and contact information. 

Text:

**Change the email address you use to sign into VA.gov**

The email address listed above is for the VA to contact you.
To update the email address you use to log in, go to the account where you manage your settings and identity information. Any email updates you make there will automatically update on VA.gov.

Link - [Update email address on ID.me]

![pc-text new email](https://user-images.githubusercontent.com/58752772/82250427-e8e6b800-98f7-11ea-8594-48d1589e3361.png)

**Comment by Samara-Strauss** [comment]
> Link - [Update email address on ID.me]

What about the links to MHV and DS Logon?

**Comment by erikphansen** [comment]
I think the idea is to only show the link that corresponds to how the user is signed in. But are the three possible links documented?

**Comment by tressaellen** [comment]
It's in the original specs - but I can post it here too. 

  - **Link text**: Update email address on ID.me
  - **Link**: https://api.id.me/en/session/new

  - **Link text**: Update email address on MyHealtheVet
  - **Link**: https://mhvidp-prod.myhealth.va.gov/mhv-portal-web/web/guest/home?p_p_state=maximized&p_p_mode=view&saveLastPath=false&_58_struts_action=%2Flogin%2Flogin&p_p_id=58&p_p_lifecycle=0&_58_redirect=%2Fmhv-portal-web%2Fc%2Fportal%2Fsaml%2Fsso

  - **Link text**: Update email address on DS Logon
  - **Link**: https://myaccess.dmdc.osd.mil/identitymanagement/authenticate.do?execution=e1s1

**Comment by tressaellen** [comment]
I'll work on that and get the links to you @erikphansen

**Comment by tressaellen** [comment]
I dropped the links currently used in the original comment with the rest of the copy as well as the specs. To be honest, the only one that took me to somewhere useful was the DS logon link.  The ID.me just takes the user to the sign-in page, and the MHV link just takes the user to the MHV homepage - and both of these they'd have to re-sign in. Is that anything that we can change and possibly make it a bit more user friendly? @Samara-Strauss

**Comment by Samara-Strauss** [comment]
> I think the idea is to only show the link that corresponds to how the user is signed in. But are the three possible links documented?

Oh cool! Yeah, that makes sense if we can detect that!

> To be honest, the only one that took me somewhere useful was the DS logon link. The ID.me just takes the user to the sign-in page, and the MHV link just takes the user to the MHV homepage - and both of these they'd have to re-sign in. Is that anything that we can change and possibly make it a bit more user friendly?

OK, so a couple things:

- Single sign on doesn't work in staging, but it does work in prod. So, someone would not (or should not) have to sign in again to MHV at least (idk about ID.me).
- For ID.me, the URL is https://wallet.id.me/settings. You can check this by right clicking the URL on the Account page and pasting it in the URL bar without pressing enter, which will result in all the redirect business. It looks like the URL redirects to the sign in page, but my guess is that once you are signed in, you are redirected back to your settings. So that should be OK.
- For MHV, the URL appears to be https://www.myhealth.va.gov/, and I am not sure why we don't send people to a more helpful page. You'll have to do some research to see if you can find what the URL is for settings in MHV. I recommend:
  - [Sign into MHV's lower environment with the URL on this page](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Identity/Login/reference_documents/MHV/mhv-lower-env-test-accounts.md)
  - Since MHV now allows you to sign in with ID.me, you can use the regular ID.me credentials you'd use to sign in to our staging environment. You can use user 226 since they have health care data.
  - Poke around MHV to find the right place to send people. We'll have to make sure the URL for the lower environment is the same place we'd send people in prod.

**Comment by tressaellen** [comment]
@Samara-Strauss I'm trying to poke around MHV a bit, but the link for the lower environment doesn't work (it says the IP address cannot be found), any ideas on how I can get into it?

**Comment by Samara-Strauss** [comment]
So as we discussed on Slack, it looks like the link for the lower environment only works on the VA network :-/

The easiest way around this was for me to create an account on prod, so I did. The link to change a password n MHV is https://www.myhealth.va.gov/mhv-portal-web/change-password

**Comment by tressaellen** [comment]
Thank you!!

**Comment by erikphansen** [comment]
@tressaellen can you check out the Profile on staging with user 36 and see how things look? And then we can decide if any changes or adjustments should be their own tickets are be handled before we call this ticket done.

**Comment by tressaellen** [comment]
Sure - I'll take a look

**Comment by tressaellen** [comment]
First of all this is seriously looking so good - really great job. Some of what I am including is larger than just personal and contact information - but I am just going to drop everything that I've noticed here and we can talk about if they need separate tickets or not. Sorry to leave such a long block to work through - I'm happy to chat about any of this tomorrow!

-  Breadcrumbs should be 'Your profile' 

- Breadcrumbs/nav/badge alignment vs the header alignment is just slightly off - again might be a site wide thing
- Nav - should be 'Your profile', not 'Your Profile'
-  Personal and contact information in navigation has a capital 'I' - should be lowercase
<img width="409" alt="Screen Shot 2020-06-02 at 2 49 36 PM" src="https://user-images.githubusercontent.com/58752772/83577307-53931880-a4e0-11ea-92bc-834fd5ce756a.png">

- Box headers (i.g. Phone numbers, Addresses etc.) seem like they're black? Or grey? They should be Blue (#112E51)
- Spacing of the mobile text message checkbox messaging shouldn't overlap the 'edit area'. In general the content of each section (Home > + 1 (510) 799-1234 > edit) seems like it's spaced out really far. Maybe if there was more padding in general around the edges.
- The alignment between the headers of the 'box' and content of the box should either be left aligned with each other - or we could bump the content and have it be indented. What do you think?
- Small typo in "Which of my benefits will use this contact information?". In 'If you're enrolled in VA healthcare, we'll send your prescriptions..." the 'W' in 'We'll' is capitalized - should be lowercased.

<img width="855" alt="Screen Shot 2020-06-02 at 2 55 16 PM" src="https://user-images.githubusercontent.com/58752772/83577916-f13b1780-a4e1-11ea-9d00-613ca85bd21b.png">

- Is it possible to bump the messaging up to be inline with 'Home'?
<img width="794" alt="Screen Shot 2020-06-02 at 3 03 52 PM" src="https://user-images.githubusercontent.com/58752772/83578089-5db61680-a4e2-11ea-910d-bfd1fc20c05a.png">

-Are these the standard input field sizes? They seem really big - especially with the 35 character limit.
<img width="504" alt="Screen Shot 2020-06-02 at 3 04 59 PM" src="https://user-images.githubusercontent.com/58752772/83578152-8807d400-a4e2-11ea-8870-94ab2198683e.png">

-'Delete' should line up with the outside right edge of the field.
<img width="477" alt="Screen Shot 2020-06-02 at 3 06 01 PM" src="https://user-images.githubusercontent.com/58752772/83578218-aa99ed00-a4e2-11ea-9d14-5880dba62acf.png">

-When trying to edit different fields the focus is confusing - I have a video of the screen but it's not letting me paste it in the comment. I'll drop it in slack. 

- Delete messaging is not aligned with the icon
<img width="493" alt="Screen Shot 2020-06-02 at 3 13 47 PM" src="https://user-images.githubusercontent.com/58752772/83578630-b9cd6a80-a4e3-11ea-9d6e-fbfd9a210d21.png">

- In the mobile numbers box, in edit mode - there is two messages about receiving a text message from the VA. 
<img width="528" alt="Screen Shot 2020-06-02 at 3 15 34 PM" src="https://user-images.githubusercontent.com/58752772/83578788-17fa4d80-a4e4-11ea-995c-1b5a23fd0299.png">

-A few times when I tried to delete a number it gave me the old message 'We're trying to delete your number....', and then the rest of the time it didn't give me that message

**Comment by mshea0606** [comment]
@erikphansen Great job on this!
