### ISSUE TITLE
[eFSR] Submit Research Plan and Conversation Guide to Perigean

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#53535]
## Issue Description
Submit completed Research Plan and Conversation Guide to Perigean. Documents must be submitted 1 week before research takes place.

---
## Tasks
- [x] _Submit completed Research Plan and Conversation Guide to Perigean_
- [x] _Create participant criteria outline for Perigean_
- [x] _Meet with Perigean_
- [x] _Ensure note taking docs line up with conversation guide_

## Acceptance Criteria
- [x] _Criteria outline created for Perigean_
- [x] _Met with Perigean on 4/10_
- [x] _Research Plan and Conversation Guide submitted to Perigean_

**Comment by HeatherRienks** [comment]
Plan to submit to Perigean in Sprint 97 (4/12-4/25/23)
