### ISSUE TITLE
[FE] Profile 2.0: Build the military information section

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5354]
## User story

As a veteran, I need to be able to easily see my military information to make sure it's accurate.

## Additional background

Epic #5346

## Design & Copy

- [InVision prototype](https://vsateams.invisionapp.com/share/FJW9OGY2B9A#/screens/407039340)
- ["Military information" build specs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Design/design-specs/military-information.md)

## Tasks

- [ ] Build the military information section.
- [ ] Implement correct copy.
- [ ] Get Tressa to test out this section and make sure it looks OK.

## Acceptance criteria

- [ ] This section has been built and reviewed by Tressa.

**Comment by tressaellen** [comment]
It's looking so good! There's just a few spacing issues outlined in the image below.  Also, for the FAQ dropdown - was that pulled from a previous component? Or was that custom built?

![Military info changes.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/b34fd4b9-af03-4cca-a621-fe4018406d7e)

**Comment by erikphansen** [comment]
@tressaellen Most of these are easy adjustments.

- yes let's not worry about the alignment of the title to the side nav until the side nav is closer to done
- yes the caret in the FAQ dropdown is just the standard `AdditionalInfo` React component that we use throughout the site. does the color differ from other instances of a similar-looking widget in other parts of the site?
- where does the max width of 647px come from? is that used elsewhere on the site? just seems a little weird since we tend to work in multiples of 8px.

**Comment by tressaellen** [comment]
@erikphansen 

- For the caret - if that's what the component is then that will work.  I think there's just a difference between what's on the style guide and what's on the site - I'll just ask platform about this.
- The width for that element came from the grid - 648 px would make more sense, I probably just mistyped it.

**Comment by tressaellen** [comment]
Military Information is looking great on desktop and mobile! The only thing I noticed is updating the months to be non-abbreviated (as you pointed out). 

Also - I can drop this in the side nav ticket as well - but in all of the pages it looks like the page title is aligned with the word 'profile' in the side nav. They should be aligned with the top line above the word 'profile'.

**Comment by mshea0606** [comment]
Hey @erikphansen , it looks like the months have been updated. Can you please update the side-nav alignment when you get a chance? Then we can close this out. Thanks!

**Comment by erikphansen** [comment]
@mshea0606 are you talking about aligning the top of the section headline to the top of the side nav? That is done about as well as it can be; aligning the tops of text elements is a little tricky and imprecise by nature since the visual top of the text is different from the top of the box that contains the text (and you're really just controlling the placement of the box).

**Comment by mshea0606** [comment]
@erikphansen Ok. Sounds good. Closing this out.
