### ISSUE TITLE
Update "Manage Your VA Debt" button to link

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#53540]
## Issue Description
As a result of #28343 we need to update button to a link

---
## Tasks
- [ ] Update button to action link

## Acceptance Criteria
- [ ] Action Link is live in production. 
---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
@mgleo This is one we discussed earlier today with @Dr-Pongo.  Could you provide the necessary design details needed for the FE team to implement this change.

**Comment by mgleo** [comment]
Ticket has been updated. The button will need to be updated as a [**primary** action link](https://design.va.gov/components/link/action).
