### ISSUE TITLE
FSR total monthly expenses not being calculated correctly

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#53550]
## Issue Description
When a Veteran is filling out the expenses portion of the FSR form the summation of these expenses for field 23 is not being calculated correctly. It appears that the value is only considering utilities and other living expenses and not taking into account rent or food.

---
## Tasks
- [ ] Identify reason for miscalculation
- [ ] Include all expenses for total expense column

## Acceptance Criteria
- [ ] A fix has been added to correctly calculate the monthly expenses
- [ ] Communicate with stakeholder teams
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
For tracking purposes this fix for the total expenses field calculation to include the missing values was merged into production on February 14, 2023
