### ISSUE TITLE
[FE] Profile 2.0: Build the direct deposit section

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5355]
## User story

As a veteran, I need to be able to easily find and update my direct deposit information so I can receive my disability and pension payments.

## Additional background

Epic #5346

## Design & Specs

- [InVision prototype](https://vsateams.invisionapp.com/share/FJW9OGY2B9A#/screens/407039340)
- ["Direct deposit" build specs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Design/design-specs/direct-deposit.md)

## Tasks

- [x] Build the direct deposit section.
- [ ] Implement correct copy.
- [ ] Get Tressa to test out this section and make sure it looks OK.

## Acceptance criteria

- [ ] This section has been built and reviewed by Tressa.

**Comment by erikphansen** [comment]
Currently blocked by https://github.com/department-of-veterans-affairs/va.gov-team/issues/7554.

**Comment by mshea0606** [comment]
@tressaellen can you please validate this ticket?

**Comment by tressaellen** [comment]
@mshea0606 I think we are still waiting on #8757 (my bad).  

@erikphansen one thing - is it possible to add more space between the lines in the title? Is that just the component line spacing? It seems pretty tight. Also, staging user +32 doesn't show anything for profile. Like literally nothing.  Any ideas why?
<img width="1013" alt="Screen Shot 2020-05-15 at 10 25 13 AM" src="https://user-images.githubusercontent.com/58752772/82083777-bc803100-9696-11ea-8036-1ad5c589246b.png">

<img width="1267" alt="Screen Shot 2020-05-15 at 10 31 35 AM" src="https://user-images.githubusercontent.com/58752772/82084341-a32bb480-9697-11ea-8df4-163a9a26f72b.png">

**Comment by erikphansen** [comment]
That's just the styling but I can adjust it

also looking into user 32. will be a good test user to make sure it handles things properly. right now it totally busts DD

**Comment by erikphansen** [comment]
@tressaellen I adjusted the headline's leading in this PR https://github.com/department-of-veterans-affairs/vets-website/issues/12700
