### ISSUE TITLE
[Letters] Add mock data for download

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#53553]
## Background
There are 3 endpoints for the EVSS letters service. All 3 have entries in the betamocks config file, but only 2 of them have data in the mockdata repo. We need to add mock data for the PDF download endpoint so that we can test all functionality of the letter generator app locally without having to connect to EVSS directly

## Context
* [Betamocks config (vets-api)](https://github.com/department-of-veterans-affairs/vets-api/blob/3db57d1/config/betamocks/services_config.yml#L313-L328)
* [Mock files (vets-api-mockdata)](https://github.com/department-of-veterans-affairs/vets-api-mockdata/tree/8e5bf1c/evss/letters)
* The Betamocks config expects that the PDF will be found at `evss/letters/download` in the `vets-api-mockdata` repo
* `Settings.evss.mock_letters` should be set to true for this to work locally

## Tasks
- [x] Add download subdirectory to `evss/letters` in `vets-api-mockdata`
- [x] Add basic set of PDFs to `download_pdf` directory
- [x] Test that this works locally

## Acceptance Criteria
- [x] `download` subdirectory has been created under `evss/letters`
- [x] PDFs have been added to `download_pdf` directory
- [x] Letter generator downloads work when `Settings.evss.mock_letters` is set to `true`
