### ISSUE TITLE
Update "On this Page" Component 

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#53552]
## Issue Description
Update "On this page" component styling and add as a landmark for screen readers. 

**This is an example from the design system what the component should look like - link is below**. 
![Screenshot 2023-02-13 at 10.47.02 AM.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/bfb0f7ac-4c91-4ff1-9a9d-fd7477e54591)
**[On this page jump links component](https://design.va.gov/components/on-this-page) - VA Design System**

During A11y review it was identified that the "on the page" component is not emerging as a landmark and therefore confusing for screenreader users.  ([see ticket #28349 ](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/28349)for more details)

As we reviewed we realized that there are some styling updates that also need to take place. 

---
## Tasks
- [x] Add "On this page" as a landmark
- [x] Update [styling](https://design.va.gov/components/on-this-page)

## Acceptance Criteria
- [x] "On this page" [component styling](https://design.va.gov/components/on-this-page) has been updated
- [x] "On this page" component has been added as a landmark 
- [x] Add a comment on #28349 and tag Terry Nichols to forward to the shared support team to validate and close out. 

---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
@mgleo Could you please add the stying details to this ticket for implementation?

**Comment by mgleo** [comment]
[On this page jump links component](https://design.va.gov/components/on-this-page) - VA Design System

**Comment by HeatherRienks** [comment]
@OptionSelect - will confirm that this has been completed.

**Comment by josephrlee** [comment]
Hi, I accidentally completed this issue without knowing when I took care of the [debt portal cleanup ticket last month](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74826). 

cc: @HeatherRienks @denisecoveyduc @mgleo
