### ISSUE TITLE
[UX] Create Content for 45-Minute Check-in Reminder Text

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#53569]
## User Story
As a Veteran, I would like to receive a text message when it is time for me to check-in for my health appointment, so that I don't have to initiate a text myself and I will know that I can now use eCheck-in to check in.

## Tasks
- [x] Review updated content in [unified check in experience wireframes](https://sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec) based on CAIA feedback
- [x] Create the content for this scenario
- [x] Get any feedback from CIE team 
- [x] Add into unified check in experience Sketch file 
- [x] Create [CAIA ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=RLHecht%2C+coforma-terry&labels=sitewide+CAIA%2C+sitewide+content-product+support%2C+Sitewide+IA%2C+sitewide+content&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E) 

## Considerations for later when we talk about implementation with VeText 

const ERROR_INSURANCE_VALIDATION = 'We're sorry. We can't check you in online. We need to review your health insurance information with you. Ask a staff member for help.';
const CHECK_IN_ERROR = 'We're sorry. We can't check you in online. Ask a staff member for help.';

And, here are some other messages that might be helpful for reference or consideration. One other thing we'll want to discuss is whether or not we're still going to support texting CHECK IN to 53079. Because, if we are, are we going to keep all the existing text messages AND add new ones for the new workflow? Or, are we getting rid of the poster, plus getting rid some of these other text message responses when a Veteran initiates eCheck-in. 

const CHECK_IN_EARLY = (MINUTES_BEFORE) => 'Our records show that you have an appointment today. You can check in up to ${MINUTES_BEFORE} minutes before your appointment. Try again later.';
const CHECK_IN_LATE = 'We're sorry. Online check-in is no longer available for your appointment time. Ask a staff member for help.';
const CHECK_IN_SUCCESS = (SHORT_URL) => 'Check in for your VA appointment at ${SHORT_URL}';

[CHIP responses documentation in Git](https://github.com/department-of-veterans-affairs/chip/blob/master/src/initiateCheckin/messages.js)

## Acceptance Criteria
- [x] Text message content has been created
- [x] Feedback incorporated from CIE team 
- [x] Created CAIA ticket

**Comment by acrollet** [comment]
@benbrasso-agile6 @kellysmith1008 @loripusey are veterans with shared phone numbers being taken into account for this work? It looks like this happens [more frequently ](https://tevi.ddog-gov.com/logs?query=%22for%20multiple%20patients%22%20&agg_q=%40lambda.request_id&cols=host%2Cservice&index=%2A&messageDisplay=inline&sort_m=&sort_t=&stream_sort=desc&top_n=10&top_o=top&viz=pattern&x_missing=true&from_ts=1682270627567&to_ts=1683566627567&live=true) than at least I realized, about 550 instances over the past two weeks. Just thinking it could be confusing if someone gets a check-in link for someone else's appointment.

**Comment by acrollet** [comment]
sort of 🙂 - what happens today is that if VEText receives a check-in request from a number that is associated with multiple patients, they get this message back:

> We're sorry. There was a problem looking up your patient record. Ask a staff member for help.

If we're sending texts out beforehand, I think we have to decide what to do in this situation. (Considering also that if someone's number has changed we could end up sending information to entirely the wrong person, or someone who isn't even a VA patient)

**Comment by benbrasso-agile6** [comment]
So, assuming we still support the Veteran initiated "check in" to 53079... then, that error would still occur, right? 

This probably deserves a quick chat. Maybe Kelly and I can catch you later today or tomorrow.

**Comment by benbrasso-agile6** [comment]
... it also seems like this is a potential area for the VEText team to tackle. I know, for now, we were focused just on writing this text message. (Unless you were inferring that the text message would benefit from including a Veteran's name.) But, I think there's a lot more for VEText to be thinking about to adjust for this new change to the workflow. E.g., health insurance, updating appt confirmation status if Veteran completes pre-check-in for a different appt in check in, etc.

**Comment by benbrasso-agile6** [comment]
@loripusey @kellysmith1008 depending on how this privacy officer review goes with the travel text messages, we may need them to review this ticket's text message too. Don't need to act now, but just writing it down now.

**Comment by kellysmith1008** [comment]
CAIA intake ticket created and Randi tagged in slack. Closing this ticket as all AC has been met
