### ISSUE TITLE
[FE] Profile 2.0: Build the account security section

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5356]
## User story

As a veteran, I need to be able to easily verify my identity, add 2FA, or find and update my login information with the VA to keep my account information updated, safe, and secure.

## Additional background

Epic #5346

## Design & Copy

- ["Account Security" build specs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Design/design-specs/account-security.md)

https://vsateams.invisionapp.com/share/FJW9OGY2B9A#/screens/407039340

click the bottom right icon to view all screens then select "Account" screens

## Tasks

- [ ] Build the account security section.
- [ ] Implement correct copy.
- [ ] Get Tressa to test out this section and make sure it looks OK.

## Acceptance criteria

- [ ] This section has been built and reviewed by Tressa.

**Comment by erikphansen** [comment]
@tressaellen feel free to review this on staging at `profile-2/`. Not sure if we have test users to use to show all the different potential states, though.

**Comment by Samara-Strauss** [comment]
- Any of the staging users who are LOA3 will show the state where identity is already proofed and 2FA is set up.
- An LOA1 user will show the prompt to verify your identity. This could be that one staging user we have who is LOA1 or any user you create.
- User 226 will show the terms and conditions already accepted
- Not sure which user might show the terms and conditions not already accepted

**Comment by erikphansen** [comment]
User 350 is LOA1

**Comment by tressaellen** [comment]
It's looking great! Only one thing - I can't find any other users that don't have terms and conditions not already accepted.  I would *assume* 350 doesn't have it accepted and that section just isn't showing on that profile, I'll keep looking at some other users to see if that's a common thread or just on this one. 

<img width="825" alt="Screen Shot 2020-04-23 at 10 21 02 AM" src="https://user-images.githubusercontent.com/58752772/80136075-af679a80-854d-11ea-82a2-11b87b35dfe5.png">

**Comment by Samara-Strauss** [comment]
> I can't find any other users that don't have terms and conditions not already accepted.

You might want to ask about this in Slack because I'm not 100% sure how this works. There *might* not be a way for them to accept the terms and conditions from account settings. That might be something they do separately, and then we show that they've accepted on that page. But I'm honestly not 100% sure so it would be worth trying to track someone down who is more familiar with this process.

**Comment by erikphansen** [comment]
350 might not be have medical benefits set up at all so they don't see that section.

**Comment by tressaellen** [comment]
Oh that would make sense... I'm still trying to track down some answers for this - so I'll keep you posted.

**Comment by mshea0606** [comment]
hey @tressaellen, do you have any update on this?

**Comment by mshea0606** [comment]
@tressaellen it looks like we can test that scenario locally vs having a staging user specifically for that use case.
