### ISSUE TITLE
[Design] Update wireframes to prioritize info messages (for check-in with no travel questions)

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#53566]
## Description 

How might we prioritize check-in information over travel information after check-in when the Veteran was not presented with travel questions.

Specifically, we need to [update this wireframe and content](https://app.abstract.com/projects/ab30c34e-e2f9-4d3e-bb96-3b683b006c24/branches/3c784fa2-f86a-42b7-b1e4-f0fd5f3c1aa3/commits/513b981720d0d848d283f4b4884a1e6a9a6565f9/files/585436fe-2120-45f4-b4f7-fbae01d258d9/layers/5619FA67-59FE-4D71-9670-2D8A842A5AA4?collectionId=3e7034be-0a0a-4895-8cf2-246a3d3ecb52&collectionLayerId=fda84b41-9434-41b6-a2c4-7b6007737eb3&mode=design&sha=latest). 

[Review related ticket](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/53253). Chat with Christina and Kelly. 

[Demonstrated in user flows for option 1](https://app.mural.co/t/vfscie8528/m/vfscie8528/1675890779520/0f6c8b1eeda87ab857e48b54bef7f15045c258ce?sender=u83bc52d7fa73658f84f27755). 

## Tasks

- [x] Update wireframe 
- [x] Share with CIE team for feedback
- [x] Get feedback from engineers, in case, for example, it's updating a component that's being used for appts that impact other pages, which might need to be avoided

## AC

- [x] Wireframe updated
- [x] Branch created in Abstract
- [ ] Reviewed and validated by CIE team 

## Deliverable
- [x] Abstract collection: 
https://share.goabstract.com/e29e0ead-47e8-4be0-9346-afe7d7383721?collectionLayerId=8d512b1d-2c82-4aed-b364-299716c2dca2&mode=design

**Comment by zach-park** [comment]
@cgednalske , @kellysmith1008 , and I met to discuss this task, and we'd like to conduct a mini-internal study to explore the solution instead of coming to a UX solution. The end delivery will be an agreed UX decision and approach.

**Comment by zach-park** [comment]
@loripusey @benbrasso-agile6 @kellysmith1008 @cgednalske @acrollet, the [wireframe](https://share.goabstract.com/e29e0ead-47e8-4be0-9346-afe7d7383721?collectionLayerId=8d512b1d-2c82-4aed-b364-299716c2dca2&mode=design) is ready for review:
https://share.goabstract.com/e29e0ead-47e8-4be0-9346-afe7d7383721?collectionLayerId=8d512b1d-2c82-4aed-b364-299716c2dca2&mode=design

**Comment by benbrasso-agile6** [comment]
Great prioritization. And, great mini-test. 

Have you thought about having "File a travel reimbursement claim." be presented as a question to Veterans instead of a statement? I wonder if, as a statement, it could be taken as something they have to do next. 

Or, if not, have you considered using a colon to be consistent with the "Your appointment:" larger body text?

**Comment by zach-park** [comment]
Great point, @benbrasso-agile6 . What do you think, @kellysmith1008 ?

**Comment by kellysmith1008** [comment]
@zach-park @benbrasso-agile6 I'm not sure a question makes sense there unless it's phrased as a question: "Would you like to file a travel reimbursement claim?" which we don't have room for as an H2 heading, I don't imagine. If we just slap a question mark on it, I feel like it looks like we're uncertain :) But I agree it could be snazzier. Maybe make it the same font/text as the "For questions about your appointment..." under the **Need help** section?

**Comment by zach-park** [comment]
@kellysmith1008 and @benbrasso-agile6, making the "**File a travel reimbursement claim**." the same font/text as the "**For questions about your appointment**..." under the Need Help section is possible since they are both body styles (e.g., body lead vs. body bold). Ideally, I'd like to recommend having the same style as the "**Your appointment:**" for visual consistency issues though.

**Comment by zach-park** [comment]
@kellysmith1008 @benbrasso-agile6 , needs content decision

**Comment by kellysmith1008** [comment]
@zach-park I think this was answered in our chat last week but I forgot to post it here. We agreed with your suggestion to keep the similar font for "File a claim" but without the question mark at the end. And now I finally remembered to put it in the ticket!

**Comment by benbrasso-agile6** [comment]
LGTM. Great work. 

That wireframe will replace [this wireframe](https://share.goabstract.com/6b69924f-904b-4d78-b5a1-4c40ed65e4d2?collectionLayerId=fda84b41-9434-41b6-a2c4-7b6007737eb3&mode=design&sha=latest). I would say, go ahead and merge that now. Not sure if there's an advantage to wait. 

We will need to have @loripusey or someone else create a ticket for FE to do this work now.

**Comment by kellysmith1008** [comment]
LGTM
