### ISSUE TITLE
[TEXT SOLUTION] [Content] Write two text messages for claim status 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#53567]
## Description 

How might we communicate to Veterans the status of their travel reimbursement claim via text? 

Specifically, we need to create two new text messages. There is one existing text message for the happy path: 

> We received your travel reimbursement claim for your VA appointment on MM/DD/YYYY. Your claim number is TC202207000011666.
> 
> You can check the status of your travel reimbursement claim online 24/7 on the Beneficiary Travel Self Service System (BTSSS) through the AccessVA travel claim portal: http://va.gov/accessva-travel-claim
> 

The other two text messages should be built around the following wireframe content (which will no longer be wireframes): 

1. [You've created a travel reimbursement claim already](https://share.goabstract.com/6b69924f-904b-4d78-b5a1-4c40ed65e4d2?collectionLayerId=9e990c2f-01db-4987-89a1-e84866da37fb&mode=design&sha=2318f16143e2c530c702b030cdd0dfd5e71155ad). 

2. [We're sorry. Something went wrong on our end](https://share.goabstract.com/6b69924f-904b-4d78-b5a1-4c40ed65e4d2?collectionLayerId=304edb10-56f6-4e9d-80d9-ba2cd88b9528&mode=design&sha=991446e80197aad415dc1c1e288f5709afaa3bef). 

[Demonstrated in user flows for option 1](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677531401756/f2ecd191cf691044fb11f57fe3398b91ad4dbc82?sender=u37bb983bd3fc3cc00c7d32865). 

## Tasks

- [x] New content for two text messages are written
- [x] Review new content with Danielle from sitewide content and IA 
- [x] Review with CIE team 
- [ ] Work with Lori to assign to PCI API or VEText team when validated 

## AC

- [x] New content for two text messages are written
- [x] Reviewed with Danielle from sitewide content and IA
- [x] Reviewed with CIE team 
- [ ] Passed off to PCI API or VEText team for implementation

**Comment by kellysmith1008** [comment]
[Created a mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1678110008784/6242cbd8d7127a71ac927a9a6f873f13f9eaaf0f?sender=u5d970cc175b184392a004997) for housing the text. Sharing with Danielle and UX team now.

**Comment by benbrasso-agile6** [comment]
Looks nice :) No comments on the content. Just left a few comments about the scenarios.

**Comment by kellysmith1008** [comment]
I've sent the mural to Danielle and she will review. @loripusey I'm putting this in validate for you. Is there someone on the API team I should reach out to after you validate or is that something you do?

**Comment by loripusey** [comment]
Questions for @acrollet 
1. In what layer(s) will we be making these calls to the VEText API? 
2. Which team do you anticipate doing this work?  If PCI/API, have we talked to them about this yet?

**Comment by loripusey** [comment]
@kellysmith1008 The text looks good to me

**Comment by acrollet** [comment]
@loripusey 

1. we're anticipating implementing this in vets-api, likely using sidekiq to queue the job to call the API and send the message
2. backend team, cc @randomsync & @kanchanasuriya to expand on my limited understanding 🙂

**Comment by loripusey** [comment]
Thanks! So, @kellysmith1008 we only have to worry about handing off to ourselves.

**Comment by kellysmith1008** [comment]
Great, @loripusey!  How would you like me to proceed? Should I close this ticket and create a backend ticket? Or remove the UX and content tags and add the backend? Something else?

**Comment by loripusey** [comment]
I would close this ticket. There is already a placeholder ticket for the engineering work. It will probably get broken down once we understand how it will all work.
