### ISSUE TITLE
FE | Profile | Account Security | Implement account security design and content updates

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-team#53574]
## Background

There are Account Security content updates (both for mobile and desktop screens) that need to be implemented on the front end using the validated design mock-ups.

Here are the Sketch files:
[Mobile](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/p/E79E0419-8D9A-4CF2-A052-EEBA8274E418/canvas)
[Desktop](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc)

#### In verify identity modal:
- **Header:** Change "view" to "access"

- **1st sentence:** Change the hyphens to em dashes and close up the spaces around them so it reads: you—and not someone pretending to be you—before

- **We can make the last sentences 2 shorter ones:** 

> This helps us keep your information safe. It helps us prevent fraud and identity theft.

#### In sign in information section:
- **Header:** Add hyphen in Sign-in

- **1st sentence:** Add hyphen in Sign-in

- **1st sentence:** Change "view" to "access"

#### Account setup section:

- **Step 1:** Change "view" to "access"

- **Step 2:** Change to:

> **Add multifactor authentication**
> Add an extra layer of protection called multifactor authentication (or 2-factor authentication). This helps to make sure only you can access your account—even if someone gets your password.

## Associated Tickets
- #50801 

## Tasks
(Ticket needs grooming)

- [ ]  
  

## Acceptance Criteria
- [x] Complete all unit testing
- [x] End-to-end tests showing 0 violations
- [x] All axe checks pass
- [x] Notify Product Manager that the change is ready to be validated on Staging
- [x] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [x] Confirm PM has opened a new ticket to deploy changes to Production using feature flag, if needed

## Validation
- Who can validate this ticket? 
- How can this work be validated?
- What updates need to be made (e.g. product outline, use cases, contact center guide)?

**Comment by adamwhitlock1** [comment]
These changes have been made and can be validated in staging now.

**Comment by mtcA6** [comment]
Looks good, checked a MHV account user w/the extra alert from 73357 and that is working as expected. 

<details><summary>screen grabs confirming the updates</summary>

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/74b33a76-20b4-44d3-8ee3-c28de2bf096c)

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/62028cf1-944c-4435-92e2-b26a3db3febf)


</details> 

With the USWDS component updates, were those supposed to reduce the padding between the left nav and the main content on the page? It feels just a smidge slimmer than the Figma files. 

@andaleliz @pamela-drouin question for you all, should the "learn how to verify your identity on VA.gov" be left adjusted like that? something about it feels weird that all of the other text is indented and that isn't? I guess the more I look at it the more the indentation is all over the place between components. 

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/f4d0b506-0239-4e1d-9064-448c1b106fd1)

Going to close this ticket w/this comment since the work is completed but feel free to respond to my questions and if we need a new ticket I can spin one up from the comments.
