### ISSUE TITLE
[FE] Profile 2.0: Build connected apps section

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5357]
## User story

As a veteran, I need to be able to manage the apps I've let access my VA.gov information.

## Additional background

Epic #5346

## Design & Copy

- [InVision prototype](https://vsateams.invisionapp.com/share/FJW9OGY2B9A#/screens/407039340)
- ["Connected Apps" build specs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Design/design-specs/connected-apps.md)

<img width="540" alt="Connected-apps-specs" src="https://user-images.githubusercontent.com/58752772/78726360-3f66dc80-78de-11ea-9ea4-16a5c10d2ab4.png">
![connected-apps-modal](https://user-images.githubusercontent.com/58752772/78726363-4261cd00-78de-11ea-9e93-d6cd33588669.jpg)
![Processing update button](https://user-images.githubusercontent.com/58752772/78726371-44c42700-78de-11ea-9eaa-732903fc3964.jpg)

## Tasks

- [ ] Build the connected accounts section.
- [ ] Implement correct copy.
- [ ] Get Tressa to test out this section and make sure it looks OK.

## Acceptance criteria

- [ ] This section has been built and reviewed by Tressa.

**Comment by Samara-Strauss** [comment]
Since this is in the Validate column, is it ready for @tressaellen or @mshea0606 to look at?

**Comment by mshea0606** [comment]
@Samara-Strauss Yes, i tried to validate it earlier this morning but it was not in staging yet. It has now been moved to staging but @sanlouise is making a few changes and will let me know when she's done and I can validate it.

**Comment by Samara-Strauss** [comment]
Got it!! Thanks for letting me know :)

**Comment by sanlouise** [comment]
For transparency - 

Te platform team made a change to the security protocol and is no longer allowing us to fetch the app logos the way we did previously. The logos are also broken in Profile 1 under accounts (which was not caused by my PR but happened because of the security update). I am currently in talks with them about how to resolve the issue.

**Comment by Samara-Strauss** [comment]
@sanlouise thank you for this.

If we need design updates, please pull @tressaellen and @careyotto into those conversations.

**Comment by careyotto** [comment]
Regarding app logo issue, cc'ing @beaugrantham-va who is our OAuth lead and might be able to share ideas for how to work around this.

Beau, the logos referred to are the app logos displayed when a user has a connected app on their VA.gov profile.

**Comment by mshea0606** [comment]
This looks great @sanlouise !

**Comment by Samara-Strauss** [comment]
Ditto! Looks great!
