### ISSUE TITLE
[FE] Test apps with new apiRequest function

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#53581]
## Background

Changes are being made to the `apiRequest` [(slack thread)](https://dsva.slack.com/archives/C03R5SBELQM/p1676062071057549) function that we use to call vets-api. We need to test our day-of and pre-check-in workflows on a review instance with the changes in place to confirm that there are no regressions.
 
## Tasks
- [ ] [FE] confirm that apps function correctly
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by acrollet** [comment]
Completed testing and notified requesting team here: https://github.com/department-of-veterans-affairs/vets-website/pull/23263#pullrequestreview-1296269920
