### ISSUE TITLE
[Design] Create wireframes for can't check you in scenarios

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#53582]
## Description 

How might we communicate the following scenarios to Veterans: 

1. Couldn't check you in. See staff. Can't file for this TYPE of travel reimbursement claim. (Meaning, they selected "No" to one of the travel eligibility questions.) "We're sorry. We can't file this type of travel reimbursement claim for you now. But you can still file within 30 days of the appointment. Find out how to file for travel reimbursement" 
2. Couldn't check you in. See staff. We're sorry, we can't file claim right now. Here's how to file manually later. (Meaning, because we were not able to set the VistaA appt status to CHECKED IN, then we shouldn't submit a travel claim for them.) "We're sorry, something went wrong on our end. We can't file a travel reimbursement claim for you now. But you can still file within 30 days of the appointment. Find out how to file for travel reimbursement" 
3. Couldn't check you in. See staff. "VA travel pay reimbursement pays eligible Veterans and caregivers back for mileage and other travel expenses to and from approved health care appointments. Find out if you're eligible and how to file for travel reimbursement" 

[Travel user flow (Mural)](https://app.mural.co/t/vfscie8528/m/vfscie8528/1667222840454/ada0c417b71c922895f1750cd32d869f6213e129?sender=u83bc52d7fa73658f84f27755)

## Tasks

- [x] Make sure you have the most up to date error message from engineers (for example, when CHIP fails during check in or the Veteran is past the check in window)
- [ ] Create wireframes with content 
- [ ] Review with CIE team 

## AC

- [ ] Wireframes are created
- [ ] Reviewed with CIE team 
- [ ] Ensure work tickets get created

**Comment by ytsaoca** [comment]
Currently the error message is the same for every senario on day-of check-in We're sorry. Something went wrong on our end. Check in with a staff member.

**Comment by ytsaoca** [comment]
@brianseek: Maybe just to let people know that their travel claim also didn’t submit if they were trying to do that. I think it could be the same message for the first two the third probably doesn’t need anything special since they couldn’t even try to check-in

**Comment by benbrasso-agile6** [comment]
I can help with these next week. We can meet to go over what’s needed here.

**Comment by benbrasso-agile6** [comment]
I have matched each wireframe that's needed in the [user flow](https://app.mural.co/t/vfscie8528/m/vfscie8528/1667222840454/ada0c417b71c922895f1750cd32d869f6213e129?sender=u83bc52d7fa73658f84f27755). For example, 53582-1 corresponds to scenario 1 in this ticket.

**Comment by benbrasso-agile6** [comment]
This is the [wireframe](https://share.goabstract.com/42ad6c8a-1e51-458c-a098-61838b01602b?collectionLayerId=068b5f51-db74-44a4-abb6-b3edfb1ab9d5&mode=design&sha=latest) that we should be building off of. This is what Veterans see when there's an issue when attempting to check a Veteran in. 

And, we just need to create 3 new versions to account for the 3 travel scenarios listed above.

**Comment by ytsaoca** [comment]
Mockups for review: https://share.goabstract.com/8cc043c4-8ca8-4f44-a979-626f261703cf

**Comment by ytsaoca** [comment]
Mockups for review: https://share.goabstract.com/8cc043c4-8ca8-4f44-a979-626f261703cf

**Comment by benbrasso-agile6** [comment]
Validated. Nice work. 

@loripusey FYI, I updated the [user flow mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677531124203/5edcfd3ea4b1eaf1ef082d56782a8b3291ef3932?sender=u37bb983bd3fc3cc00c7d3286) with these new wireframe links.
