### ISSUE TITLE
Spanish translation: Updated booster content on main vaccines page and coronavirus FAQs

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#53587]
## Issue Description

We made changes to our English COVID pages with updates from SMEs. We need to translate this new content into Spanish and update those pages.

## Tasks
- [ ] Send content to translators (Randi/Ana)
- [ ] Update vaccines Drupal page (Ana)
- [ ] Update FAQs Drupal page (Ana)
- [ ] Review vaccines page (Megan)
- [ ] Review FAQs page (Megan)
- [ ] Publish vaccines page (Megan)
- [ ] Publish FAQs page (Megan)

## Acceptance Criteria
- [ ] Vaccine and FAQs pages have most updated content in Spanish

**Comment by RLHecht** [comment]
@aliyahblackmore @ABeltran77 Here is the content back from the translators: [https://app.zenhub.com/files/133843125/264e82d7-c2ab-410c-971f-08f3aea3d6c6/download](https://app.zenhub.com/files/133843125/264e82d7-c2ab-410c-971f-08f3aea3d6c6/download)

Since Ana isn't in Drupal yet, Aliyah will need to update the pages this time around.

**Comment by RLHecht** [comment]
@megzehn This one is ready for you too!

**Comment by RLHecht** [comment]
Also noting that I changed mascaras and mascarillos to cubrebocas throughout per Ana's guidance. The translators had changed a new section to cubrebocas but it was inconsistent with the rest of the page. We updated all instances.

**Comment by megzehn** [comment]
Thanks, @RLHecht! These are all published and ready for you to validate:

FAQs:
http://preview-prod.vfs.va.gov/preview?nodeId=14580

About vaccines:
http://preview-prod.vfs.va.gov/preview?nodeId=36461

Booster shots: 
http://preview-prod.vfs.va.gov/preview?nodeId=34408

**Comment by RLHecht** [comment]
These pages are all live with changes. Closing ticket.
