### ISSUE TITLE
Tagalog translation: Updated booster content on main vaccines page and coronavirus FAQs

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#53589]
## Issue Description

We made changes to our English COVID pages with updates from SMEs. We need to translate this new content into Tagalog and update those pages.

## Tasks
- [ ] Send content to translators (Randi/Ana)
- [ ] Update vaccines Drupal page (Ana)
- [ ] Update FAQs Drupal page (Ana)
- [ ] Review vaccines page (Megan)
- [ ] Review FAQs page (Megan)
- [ ] Publish vaccines page (Megan)
- [ ] Publish FAQs page (Megan)

## Acceptance Criteria
- [ ] Vaccine and FAQs pages have most updated content in Tagalog

**Comment by RLHecht** [comment]
@aliyahblackmore @ABeltran77 Here is the Tagalog copy back from the translators:

[https://app.zenhub.com/files/133843125/a8fe924f-8efb-4a8b-94ee-8311772c108d/download](https://app.zenhub.com/files/133843125/a8fe924f-8efb-4a8b-94ee-8311772c108d/download)

**Comment by RLHecht** [comment]
@megzehn These pages are now all ready for you. Also noting that I removed content from the COVID boosters page (there wasn't any content to send to the translators, so it's not reflected on that doc).

**Comment by megzehn** [comment]
Thanks, @RLHecht! I reviewed and published these.
