### ISSUE TITLE
Remove the term "feedback" from Staging Review

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#53595]
## User Story
As a VFS team member, I want to have a clear understanding on how to interpret all communication from Governance team wrt Staging Review so that I can take the appropriate action. 

As a Governance team member, I want to remove all instances of the term "feedback" from the Staging Review process so that VFS teams understand that "feedback" is applicable to DI and MPR, but all communication at Staging Review is related to "issues" where the VFS product does not meet VA.gov Standards.

Assignee: @CherylEvans 
Peer Reviewer: @sterkenburgsara 

## Description
While documenting the language changes for ticket #53079, Governance team PM Shira Goodman noticed that our language/content choices for Staging Review mirror the language/content choices we have in place for Design Intent and Midpoint Review. At DI and MPR, we document "feedback" tickets that are practice area specific and align with the [Must, Should, and Consider Framework for _Feedback_](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). This is an intentional choice as the VFS team has not yet pushed their product to prod/live to VA.gov. The response from Governance team is rightly labeled "feedback" as the VFS product is still being built and it is not yet clear whether their final product will align with the VA.gov standards.

However, at Staging Review, the product is now ready to go to prod. We already communicate at SR that our tickets will be aligned with the VA.gov Experience Standards, yet we use the same language/term for those tickets - feedback tickets. This is very evident on the Staging Review touchpoint page where we encourage the VFS team to "implement feedback" and tell them the Objective is to "get feedback."

This is not ideal as it implies that the response from Governance at SR can be interpreted and/or addressed the same way as the response from Governance team at DI or MPR. Instead of using the word "feedback" at Staging Review, Governance team should be using "document issues" or "issue tickets" or addressing "issues" where their product doesn't meet the VA.gov Standards.... whichever makes the most sense contextually. 

The purpose of this ticket is to address all instances of the word "feedback" in Staging Review operational guidance and in the Staging Review code block for the Collaboration Cycle request. All changes to the Staging Review touchpoint page will be completed in ticket #53079. It is critical that the assignees and Peer Reviewer for this ticket work with and collaborate with the assignee and peer reviewer for ticket #53079.

## Impacted Artifacts
Every artifact in the [Staging Review Confluence folder](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1978859531/Staging+Review)
Staging Review Code block in the [Collab Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)

## Tasks
- [x] Identify every instance of the term "feedback" in all impacted artifacts
- [x] If/when "feedback" is found, replace with "findings" or "Staging review issue tickets" or addressing "issues" where their product doesn't meet the VA.gov Standards.... whichever makes the most sense contextually. 
- [ ] Coordinate with the assignee and peer review of ticket #53079 re: the Staging Review script
- [x] Update SR code block of open Collab Cycle Request tickets

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team members understand that the term "feedback" should not be referenced within the context of a Staging Review
- [x] VFS team members do not see the term "feedback" within the context of Staging Review in their Collaboration Cycle Request ticket. 

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Question for team - should we update the Staging Review section of open Collaboration Cycle Request tickets to align with our SR code block changes?

**Comment by shiragoodman** [comment]
thank you @CherylEvans . Personally, I like "documented issue" but I'm not too fond of "non-compliance" (for accessibility reasons - ask @briandeconinck if you're curious why compliance is not a great choice). I also don't think "issue" is too strong. No need for "concern."

Do you think "documented issue" is sufficient on it's own? to be fair, before we were calling them "feedback" tickets which isn't much more descriptive.

**Comment by CherylEvans** [comment]
@shiragoodman @sterkenburgsara Thank you for your input! I completely understand why we shouldn't use "compliance." I don't think "documented issue" is enough on its own. "Documented issue" states what we found, and "non-conformance" denotes "why" it is an issue. Does that make sense? I personally like "Documented issue of non-conformance" as it leaves no doubt or room for interpretation.

**Comment by shiragoodman** [comment]
in the past we've also said "standards issue"

My only concern re:  "Documented issue of non-conformance" is that it's a mouthful.

**Comment by CherylEvans** [comment]
@shiragoodman "non-conformance standards issue"...I think I like it!

**Comment by CherylEvans** [comment]
@shiragoodman I could learn to like "standards issue" as well... :-)

**Comment by sterkenburgsara** [comment]
@CherylEvans @shiragoodman I agree it is a mouthful. Do we need non-conformance?

**Comment by CherylEvans** [comment]
@shiragoodman @sterkenburgsara I am trying to get a point across w/o sounding like an order.  I think "standards issue" would be fine.  Language is tricky...

**Comment by shiragoodman** [comment]
@sterkenburgsara yes, that'll take place in https://github.com/department-of-veterans-affairs/va.gov-team/issues/53079

**Comment by CherylEvans** [comment]
@shiragoodman Can I add the changing the Staging review template to Impacted Artifacts and Tasks?  We are going to need to change the template to reflect the replacement of the "Individual Feedback" tab with "Individual Standards Issues" or simply "Standards Issues".

**Comment by CherylEvans** [comment]
@shiragoodman @sterkenburgsara After much thought and consultation with various guides, I have concluded that "standards-issue" won't work.  It won't work because it doesn't imply a resultant "action."
I am considering this: "standards-issue directive" instead. What are your thoughts?  "Directive" is the most gentle way to say that our guidance is not a suggestion but a requirement.

**Comment by shiragoodman** [comment]
@CherylEvans let me think about this. I'm not really a fan of that wording. It's also starting to feel like we're overcomplicating this. Currently in the [Anatomy of a Staging Review issue ticket ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket)guidance, we call them Staging Review issues or Staging Review issue tickets. 

Keep in mind that currently, we're calling everything "feedback." I'm not sure feedback implies a resultant action either. And if that's true, feedback won't work at DI or MPR. 

I've put this on the agenda for standup on Monday. We can discuss then!

**Comment by shiragoodman** [comment]
"findings" or "findings" 
"Staging Review issue ticket"

**Comment by shiragoodman** [comment]
FYI @CherylEvans Ticket #54424 was just assigned for this sprint. Please note that there may be some overlap in impacted documents. @sterkenburgsara is involved in both tickets so please connect with her to ensure no duplicate work and/or gaps occur. Thank you!

**Comment by CherylEvans** [comment]
@sterkenburgsara I have done a preliminary editing of these doc drafts.  It's time for another set of eyes to go over the changes. :-)
I know it's a lot to review! 
My Drafts:
[Staging Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2546925569/53595+-+Copy+of+Staging+Review+-+Moderator+Responsibilities) 
[How to document feedback for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2546958337/53595+-+Copy+of+How+to+document+feedback+for+Staging+Review)
[Design System Staging Review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2546958360/53595+-+Copy+of+Design+System+Staging+Review)
[Staging Environment Guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2546925610/53595+-+Copy+of+Staging+Environment+Guidance)
[How to Add Images to the Staging Review Drafting Template](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2546958387/53595+-+Copy+of+How+to+Add+Images+to+the+Staging+Review+DraftingTemplate)
[How to reassign, move backlog, or close invalid or duplicate Staging review tickets](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2546958387/53595+-+Copy+of+How+to+Add+Images+to+the+Staging+Review+DraftingTemplate)
[Anatomy of a Staging Review Issue ticket](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2546925621/53595+-+Copy+of+Anatomy+of+a+Staging+Review+Issue+ticket)
https://vfs.atlassian.net/wiki/spaces/PPST/pages/2546958405/53595+-+Copy+of+DraftingTemplate+Outline
Staging Review finding - Issue Template (Shira added this 30 minutes ago and it already contains the appropriate verbiage.)
[Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2548170753/53595+-+Copy+of+Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)

**Comment by sterkenburgsara** [comment]
@CherylEvans I provided comments directly on confluence pages, but only found a few things. I can't even tell what you changed about the [Staging Environment Guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2546925610/53595+-+Copy+of+Staging+Environment+Guidance) and [How to Add Images...](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2546958387/53595+-+Copy+of+How+to+Add+Images+to+the+Staging+Review+DraftingTemplate) pages 🤣  this is very thorough!

**Comment by CherylEvans** [comment]
@sterkenburgsara Great!!  Thank you for reviewing!  I will resolve your comments and go from there.  :-)

**Comment by sterkenburgsara** [comment]
@CherylEvans I think the only outstanding thing is the `collab-cycle-feedback` label, and whether we want to update language to say `collab-cycle-finding`. I would vote for yes, as it seems very much in the spirit of this entire effort. Thoughts? // cc @shiragoodman

**Comment by sterkenburgsara** [comment]
@shiragoodman @it-harrison would this affect our Domo dashboards in any way? (Do we have existing queries that reference "collab-cycle-feedback"? // cc @CherylEvans

**Comment by shiragoodman** [comment]
@sterkenburgsara I've had some time to think about this and my vote right now is to leave the label `collab-cycle-feedback` as-is and do not change it. This label is applied to all tickets generated by our team at Design Intent, Midpoint Review and Staging Review. I understand we want to remove the word feedback from Staging, but changing the label could introduce more problems. I'd rather leave as-is and we can investigate and discuss later on.

**Comment by CherylEvans** [comment]
@shiragoodman @sterkenburgsara Sounds good!

**Comment by sterkenburgsara** [comment]
@CherylEvans @shiragoodman okay, sounds good. I'll leave it as-is in artifacts related to my other ticket as well. I think this one can be closed out, Cheryl. Good work editing a gazillion documents!

**Comment by CherylEvans** [comment]
@sterkenburgsara Thank you, Sara!  And thank you for your thorough review. :-)

**Comment by CherylEvans** [comment]
@sterkenburgsara Hi Sara.  I have incorporated your recommendations and am ready for you to review. :-)

**Comment by sterkenburgsara** [comment]
@CherylEvans looks great - no further edits. I think we're just waiting for Friday's workshop now.

**Comment by CherylEvans** [comment]
Published all drafts!
