### ISSUE TITLE
Profile: Sprint 5 (3.1.23 - 3.14.23)

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-team#53602]
## Sprint 4 Retro
Thank you for another awesome sprint, overall the team completed the capacity of work as planned! We can chat about that at planning.
[EasyRetro board](https://easyretro.io/board/f4051524-d7be-43a4-8c50-f43d887f3a7f/66c8fea6-a7a1-4ef8-ab9e-2e9cc755cb88)

## Sprint 5 Notes
Sprint 5 epic was populated using this [project outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/sprint-objectives/profile/sprints-1-10-Jan23-May23.md#sprint-5-31---314) -- this epic is not yet final, we'll discuss at Sprint 5 Planning -- thanks team!

## Priorities for Authenticated Experience
- High: Migrating MyHealtheVet into VA.gov; expanding notification functionality (both onsite and preferences); improving the logged-in nav/IA/experience overall; urgent/required maintenance for a feature; unplanned work that aligns with OCTO high-priority objectives
- Low: improvements team wants to make but might fall outside of OCTO objectives
- To complete: some initiatives that we should finish but don't fall under OCTO high-priority objectives

More details found at [Q1 Roadmap](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/roadmap/2023-goals-roadmap.md#100-foot-view-q1-cy2023-january---march-authenticated-experience-roadmap)

## PTO
- No scheduled OOO for Profile team at this time; Samara may be out for part or most of Sprint 5 (TBA)

## Sprint Goals
- Military info research (carried over from Sprint 4)
- Direct deposit migration
- Notification preferences
- Logged-in IA/nav research
- Accessibility updates
- Other: UX improvements review and analysis, Address validation issue, Datadog setup

## Military info research
(From the roadmap: With passage of the PACT Act, there is renewed internal interest internally to surface more about veterans' miltary histories on VA.gov. In order to determine if and how we might expand the military information section on VA.gov, we need to conduct discovery to figure out what would be helpful to veterans.)
Design - Flo
- [x] #51889 (carry over from Sprint 4 - about 5 points left to do)

## Direct deposit migration
(From the roadmpap: Direct deposit for comp & pen information on VA.gov is currently supported by EVSS. However, EVSS is going away in 2023 and EVSS integrations are in the process of moving over to the Lighthouse platform... once we can start moving over our integration from EVSS to Lighthouse, we'll work closely with Lighthouse to get this functionality updated, tested, and launched.)
BE - Tom
- [x] #54051
- [ ] #54054

## Notification preferences
(From the roadmap: For the profile, the notification preferences section is currently our biggest focus. We've got a lot of work coming down the pipeline, including incorporating preferences from MHV and eBenefits, as well as working with VANotify and VA Profile to add new preferences as other notifications are added. By year's end, I could see us adding 5 new preferences, if partners continue adding new notifications at the pace they did in 2022.)
FE - Adam
- [ ] #53616
- [ ] #53545  - ~Should this be broken into smaller tickets? Or pushed entirely back a sprint or two?~

## Logged-in IA/nav research
(From the roadmap: We're aware of some high-level problems people have navigating the logged in experience on VA.gov -- eg. if a link isn't on the homepage or My VA, people tend to have trouble finding what they need. However, we've never conducted more holistic research that evaluates navigating the logged in experience. This research effort aims to dive deeper into users' problems with and expectations around navigating VA.gov once they're signed in. We'll be partnering with Mikki to conduct a research review, analytics review, and user research that will be used to inform work throughout this calendar year.)
Design - Liz 
- [x] #53626
- [x] #52796 (pulled in early and started in Sprint 4)
- [x] #54094 (pulled in early and started in Sprint 4 - currently blocked)
- [ ] #54092

## Accessibility updates
(From the roadmap: There are quite a few design updates that are complete and need to be implemented. We should wrap up frontend implementation on these tickets ahead of moving on to other work.)
FE - Adam
- [ ] #53631

## General (other)
UX improvements review and analysis, Address validation issue, Datadog setup
Design - Florence
- [ ] #53227

BE - Tom
- [x] #52786
- [x] #54053
