### ISSUE TITLE
Remove React-based radio buttons being used by 526EZ form

### ISSUE THREAD

**Issue by ahay-agile6** [department-of-veterans-affairs/va.gov-team#53605]
## Issue Description
The Design System Team has been deprecating older React-based versions of our components in favor of web-components (which have React bindings).

The scope of this ticket is limited to planned deprecation of the use of React-based radio buttons by end of Feb'2023.

### Notes
We have found only 1 place where the VaRadio React Component is being used, right at the beginning of the 21-526EZ.

Remediation is hypothesized to be minimal.

"Are you on active duty right now?"
/disability/file-disability-claim-form-21-526ez/start:
src/applications/disability-benefits/wizard/pages/start.jsx:28
```
<VaRadio
      class="vads-u-margin-y--2"
      label={label}
      onVaValueChange={onValueChange}
    >
      {options.map(option => (
        <va-radio-option
          key={option.value}
          name="active-duty"
          label={option.label}
          value={option.value}
          checked={state.selected === option.value}
          aria-describedby={
            state.selected === option.value ? option.value : null
          }
        />
      ))}
    </VaRadio>
```

How to convert to web component: https://design.va.gov/about/developers#using-web-components

---
## Tasks
- [ ] Convert `VaRadio` React component to web component

## Acceptance Criteria
- [ ] There are no more React-based radio buttons being used by the 526EZ form
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ahay-agile6** [comment]
According to the VA Design System team, this chunk of code is the correct way to do the `va-radio` button component with React applications.

Closing this as there is nothing to do! :D

- Slack thread: https://dsva.slack.com/archives/C01DBGX4P45/p1676397421496949
- VA Design System documenation explaining web components with React bindings: https://design.va.gov/about/developers#react-applications
