### ISSUE TITLE
[Design] Logged-in generative IA/nav research: Add recent mobile app IA findings to our research review

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#53626]
## Background

The mobile app team recently complete some IA/navigation research for the mobile app that has the potential to influence the VA.gov logged-in IA/nav.

[Here is the mobile app's research summary deck](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/ux-design/information-architecture-navigation/2023%20VA%20Mobile%20App%20-%20IA%20%26%20Navigation%20Project%20Summary.pdf)

We should add any relevant findings to the [logged-in generative IA/nav research review you already completed](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ia-and-navigation/2023-generative-logged-in-research/research-review-findings.md), and make sure this deck is linked from there.

## Tasks

- [ ] Review mobile app deck
- [ ] Add findings to the logged-in generative IA research review as necessary
- [ ] Link to the mobile app's deck from the research review

**Comment by Samara-Strauss** [comment]
@andaleliz -- can you also make sure [this finding from Florence's military research report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/military-information/discovery-and-research/2023-military-info-discovery/topline-summary.md) makes it into the research review along with the new mobile work? Thank you!!

> When asked to show me where they'd expect to find their military info on VA.gov (starting from the My VA screen), participants always (check number) went to the search bar as their first step.
> 
> Once I directed participants to the profile link at the top of the screen, they were able to find "military info" in the side nav of the profile. At this point, it can't be said for certain why participants didn't click on the profile link. For example, is the link not clearly visible? Is the link text not accurately describing what info could be found within profile? Or, are participants trained by previous usage of the site to always use the search bar? (Or some other reason I'm not thinking of now?)

**Comment by andaleliz** [comment]
Yes @Samara-Strauss, will do! While this work is in progress, I'll be sure to start paying closer attention to other research read outs as well, in case there are new findings that will be helpful.

**Comment by andaleliz** [comment]
@Samara-Strauss I was able to find a few points from the new mobile research and add this study as another piece of supporting evidence, but there wasn't anything majorly different from the other mobile studies we had previously reviewed.  Was there anything new in particular that you wanted me to add to it?

Florence's research as been added too.

**Comment by Samara-Strauss** [comment]
Re: the mobile research -- given that they tested an IA/nav structure that worked well, I think we should call that out specifically. I don't think that really falls under an existing question we posed for the research review, but it's important to capture IMO.

**Comment by andaleliz** [comment]
Ok, we're on the same page then.  That is specifically called out under [What are other known insights around navigating the site overall?](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ia-and-navigation/2023-generative-logged-in-research/research-review-findings.md#what-are-other-known-insights-around-navigating-the-site-overall), in number 7.  I'll close this out. Thanks!

**Comment by Samara-Strauss** [comment]
Ah, ok, I'm sorry I missed that. We are good to go!
