### ISSUE TITLE
GA4:  Web & Form - prepare data layer code for hand off

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#53635]
## Issue Description
We will begin implementation and testing of web components in Sprint 22.  I preparation for that we need to ensure the data layer code is complete and clear for the Design System team to implement.  We will then ensure the form components are configured in GTM and create the data layer code for that hand off in future sprint.

---
## Tasks
- [ ] Review each web component config in GTM
- [ ] Update web component data layer documentation
- [ ] Review/update each Form component in GTM
- [ ] Create form components data layer documentation
- [ ] Develop instruction doc for FEs

## Acceptance Criteria
- [ ] A document will be completed for handoff to FE to support their implementation efforts.
---
