### ISSUE TITLE
Part 1: Heuristic evaluation workshop

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#53645]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
The heuristic evaluation workshop is an opportunity for the Debt Resolution team to: 
* Collaborate creatively as a team
* Learn about or refresh knowledge of usability heuristics and practice design thinking
* Become familiar with the FSR form and/or enhance present understanding
* Think about possible usability improvements within current constraints 

---
## Tasks
- [x] _Planning for part 1 presentation_
- [x] _Part 1 takes place_

## Acceptance Criteria
- [x] _Part 1 of the the Heuristic evaluation workshop has taken place_

**Comment by mgleo** [comment]
Part 1 took place today 2/28/23. Great job Charlotte!

**Comment by HeatherRienks** [comment]
@denisecoveyduc - I am going to move this to closed so it accurately reflects that we completed this in Sprint 93, before it rolls over into the new sprint in a few hours. :)
