### ISSUE TITLE
GA4:  Test & Validate - Auto Tracked Events

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#53642]
## Issue Description
GA4 auto tracks some standard events such as page views, api calls, etc.  We need to review each auto tracked event to ensure it is working and providing the level of detail we need to support current VFS team needs.

---
## Tasks
- [x] Review each auto tracked event
- [x] Test each auto tracked event
- [ ] Sign-off on or more to custom if needed.

## Acceptance Criteria
- [ ] We have completed the auto tracked events configuration and testing requirements.
---

**Comment by michelle-dooley** [comment]
final sign off will be completed as part of #53393
