### ISSUE TITLE
Content changes to note on Veterans burial allowance page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#53653]
## Issue Description
VA partner Angie Smith asked us to make content updates on the [How to apply for a Veterans burial allowance](https://www.va.gov/burials-memorials/veterans-burial-allowance/) page. 

She wants us to remove the note under the H2 "What kind of burial benefits can I get?"

## Tasks
- [ ] Assess request (Laura)
- [ ] Update page in Drupal
- [ ] Copyedit (Megan)
- [ ] Publish (Megan)

## Acceptance Criteria
- [ ] Content updates are live on the site

**Comment by RLHecht** [comment]
Closing this ticket and adding combining this work in another ticket that also touches on the same page.
