### ISSUE TITLE
Discovery: Capture Ruby 3.0 Test Failures

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#53657]
Errors in Ruby 3.0 will need to be resolved. Running the test suite and capturing its output will help us find and resolve these errors.

## Tasks

- [x] Run Vets API's test suite using latest Ruby 3.0.x
- [x] Categorize issues captured in results
- [x] Create issues for each category of failure found

## AC

- [x] Categorical issues are created for 3.0 test failures 

## Blocked by

Issue #53655 and related discovered issues will need to be resolved as unresolved language deprecations will cause test failures.
