### ISSUE TITLE
Determine if latest version of Bundler poses any issue

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#53658]
Previously when updating to Ruby 3.0, I remember having an issue with using Bundler 2.2 over 2.1. It was back in 2021 so I don't recall the exact issue but I remember having to specify 2.1 for some reason. Let's investigate this further to make sure everything works as expected with the latest.

## Tasks
- [x] Review current version
- [x] Upgrade documentation and criteria's
- [x] Upgrade version without any breaking changes

## Acceptance Criteria
- [x] Bundler is the latest

**Comment by oseasmoran73** [comment]
Upgraded bundler to the latest version. Attempted to rebuild the image, but it looks like there seems to be a cache that is being pulled from somewhere. Investigating!!

**Comment by oseasmoran73** [comment]
When I updated the Gemlock with the updated version and manually called the install in the Dockerfile. It seems to work. Seems to be a ruby issue that if there is a difference within the cache that it requires another install

**Comment by oseasmoran73** [comment]
PR has been created. Pending approval. Based on testing done, if we move forward in 2.7, it won't have any impact and should be a smooth transition onto 3.0

**Comment by oseasmoran73** [comment]
There was issue with the upgrade. Gemfile was not properly committed (thought we needed those, turned out we dont). Fix found [here](https://github.com/department-of-veterans-affairs/vets-api/pull/12115). Thanks Eric!

**Comment by npeterson54** [comment]
Didn't quite finish in sprint, moving into next sprint.

**Comment by oseasmoran73** [comment]
v2.4.8 is deployed and in prod, as well as lower environment

@npeterson54 @ericboehs Closing ticket. If AC have not ben met, feel free to reopen and pull me back in

**Comment by oseasmoran73** [comment]
Looks like it got reverted in lower environments. Its correct version in prod. Reopening until they are fixed in lower environments

**Comment by oseasmoran73** [comment]
Officially verified that it is now working in lower environments. Closing ticket
