### ISSUE TITLE
Discovery: Capture Ruby 2.7 Warnings

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#53655]
Ruby 2.7 has deprecated language features which will no longer be available in Ruby 3.0.

These warnings need to be documented and fixed in another ticket.

## Tasks

- [x] Run test suite with warnings enabled
- [x] Capture these warnings into issues

## AC

- [x] Issues are created for each warning category found

**Comment by holdenhinkle** [comment]
I'm using the following command to log all warnings to `warnings.txt`:

`rspec --warnings --format documentation |& grep warning > warnings.txt `

**Comment by holdenhinkle** [comment]
I've attached the [warnings.txt file](https://app.zenhub.com/files/133843125/6656d803-7111-406f-ae15-56e7f1eea3bf/download)

**Comment by holdenhinkle** [comment]
[Deprecation warnings](https://app.zenhub.com/files/133843125/f127955e-0c9f-4520-99e1-4faa32741c60/download) zip file

**Comment by holdenhinkle** [comment]
Each warning, with the number of instances of the warning:

```
grep -r -h -A 1 "DEPRECATION WARNING" ./**/*.y* | grep -o 'warning: .*' | sed 's/^[^w]*//' | awk -F: '{print $2}' | sort | uniq -c

   1  Passing the keyword argument as the last hash parameter is deprecated
   1  The called method `combine_name_addr' is defined here
   1  The called method `delete' is defined here
   1  The called method `get' is defined here
  51  The called method `initialize' is defined here
   1  The called method `measure' is defined here
   1  The called method `patch' is defined here
   1  The called method `post' is defined here
   1  The called method `put' is defined here
   1  The called method `record_submission_failure_client_data' is defined here
   2  The called method `validate_string' is defined here
   3  The called method is defined here
   2  Using the last argument as keyword parameters is deprecated
  63  Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
   4  already initialized constant OPTIONS_STRUCT
   4  already initialized constant ROW
   1  already initialized constant Testing
   1  previous definition of EVENTS was here
   4  previous definition of OPTIONS_STRUCT was here
   4  previous definition of ROW was here
   1  redefining constant Struct
```

**Comment by holdenhinkle** [comment]
### vets-api Rspec Warnings (only 3 deprecations)

grep command:
```
grep -h "^/Users/holdenhinkle/Documents/Oddball/va_website/vets-api" /Users/holdenhinkle/Downloads/warnings.txt | awk -F'warning: ' '{print $2}' | sort | uniq -c | sort -nr
```

Number of occurrences for each warning:
```
2486 instance variable @access_token not initialized
1910 instance variable @current_user not initialized
 617 instance variable @session_object not initialized
 125 instance variable @veteran_status not initialized
 113 instance variable @mvi_ids not initialized
  94 Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
  68 instance variable @vet360_contact_info not initialized
  64 The called method `initialize' is defined here
  45 instance variable @vet360_contact_info_retrieved not initialized
  44 instance variable @reply not initialized
  27 instance variable @military_information not initialized
  20 instance variable @id not initialized
  10 instance variable @okta_profile not initialized
   7 instance variable @token_uri not initialized
   7 instance variable @okta_grants not initialized
   5 previous definition of basic_class was here
   5 method redefined; discarding old basic_class
   4 previous definition of warden was here
   4 previous definition of github_team_authenticate! was here
   4 previous definition of github_organization_authenticate! was here
   4 method redefined; discarding old warden
   4 method redefined; discarding old open
   4 method redefined; discarding old github_team_authenticate!
   4 method redefined; discarding old github_organization_authenticate!
   4 instance variable @uuid not initialized
   4 instance variable @office_location not initialized
   4 The called method `record' is defined here
   4 The called method `paginate' is defined here
   3 previous definition of open was here
   3 instance variable @sanitized_req_body not initialized
   3 The called method is defined here
   3 The called method `record_submission_failure_client_data' is defined here
   3 The called method `perform_get' is defined here
   2 instance variable @unchanged_schemas not initialized
   2 `frozen_string_literal' is ignored after any tokens
   2 Using the last argument as keyword parameters is deprecated
   2 The called method `validate_string' is defined here
   2 The called method `record_submission_success' is defined here
   2 The called method `record_submission_failure_client_qualification' is defined here
   2 The called method `record_notifications' is defined here
   1 redefining constant Struct::Surprise
   1 previous definition of un_camel_va_keys! was here
   1 previous definition of to_olivebranch_case was here
   1 previous definition of simplify_string was here
   1 previous definition of silently was here
   1 previous definition of service_history_object was here
   1 previous definition of perform was here
   1 previous definition of home_phone was here
   1 previous definition of get_education_form_fixture was here
   1 previous definition of get_disability_array was here
   1 previous definition of get_dis_translation_hash was here
   1 previous definition of gender was here
   1 previous definition of fix_treatment_facilities_disability_name was here
   1 previous definition of fix_pow_disabilities was here
   1 previous definition of EVENTS was here
   1 method redefined; discarding old un_camel_va_keys!
   1 method redefined; discarding old to_olivebranch_case
   1 method redefined; discarding old status
   1 method redefined; discarding old simplify_string
   1 method redefined; discarding old silently
   1 method redefined; discarding old service_history_object
   1 method redefined; discarding old perform
   1 method redefined; discarding old on
   1 method redefined; discarding old jobs
   1 method redefined; discarding old initialize
   1 method redefined; discarding old home_phone
   1 method redefined; discarding old get_education_form_fixture
   1 method redefined; discarding old get_disability_array
   1 method redefined; discarding old get_dis_translation_hash
   1 method redefined; discarding old gender
   1 method redefined; discarding old ga_collection_uri
   1 method redefined; discarding old fix_treatment_facilities_disability_name
   1 method redefined; discarding old fix_pow_disabilities
   1 method redefined; discarding old description=
   1 method redefined; discarding old description
   1 method redefined; discarding old bid
   1 instance variable @user not initialized
   1 instance variable @status_job_title not initialized
   1 instance variable @sftp not initialized
   1 instance variable @root not initialized
   1 instance variable @event_to_api_name not initialized
   1 instance variable @cookie_id not initialized
   1 character class has duplicated range: /\W+status\W+([^"|^,|^\\]*)/
   1 assigned but unused variable - environment
   1 already initialized constant Testing::EVENTS
   1 The called method `record_attachments_delivered' is defined here
   1 The called method `make_request' is defined here
   1 The called method `log_mpi_search_result' is defined here
   1 The called method `combine_name_addr' is defined here
   1 The called method `__perform_get_without_any_instance__' is defined here
   1 Passing the keyword argument as the last hash parameter is deprecated
```

**Comment by holdenhinkle** [comment]
### vets-api gems Rspec Warnings (only 2 deprecations)

grep command: 
```grep -v "/Users/holdenhinkle/Documents/Oddball/va_website/vets-api" /Users/holdenhinkle/Downloads/warnings.txt | grep -o "warning: .*" | sort | uniq -c | sort -nr
```

Number of occurrences for each warning:
```
4982 warning: instance variable @lockbox_attributes not initialized
4340 warning: instance variable @kms_keys not initialized
4014 warning: instance variable @idp_sso_service_url not initialized
2473 warning: instance variable @kms_key not initialized
1800 warning: previous definition of sent was here
1800 warning: previous definition of recipients was here
1800 warning: previous definition of opened was here
1800 warning: previous definition of failed was here
1800 warning: previous definition of clicked was here
1800 warning: method redefined; discarding old sent
1800 warning: method redefined; discarding old recipients
1800 warning: method redefined; discarding old opened
1800 warning: method redefined; discarding old failed
1800 warning: method redefined; discarding old clicked
1452 warning: instance variable @idp_sso_service_binding not initialized
 664 warning: instance variable @wsu_timestamp not initialized
 664 warning: instance variable @signature not initialized
 664 warning: instance variable @namespace_identifier not initialized
 664 warning: character class has duplicated range: /[^a-zA-Z0-9\-\.\_\~\!\$\&\'\(\)\*\+\,\;\=\:\@\[\:\]]/
 606 warning: instance variable @nori not initialized
 452 warning: instance variable @includes not initialized
 210 warning: instance variable @requirement not initialized
 112 warning: instance variable @idp_slo_service_url not initialized
  66 warning: previous definition of webhooks was here
  66 warning: previous definition of sms_templates was here
  66 warning: previous definition of sms_messages was here
  66 warning: previous definition of session_info was here
  66 warning: previous definition of reports_messages_sms_statistics was here
  66 warning: previous definition of reports_messages_email_statistics was here
  66 warning: previous definition of message_types was here
  66 warning: previous definition of keywords was here
  66 warning: previous definition of inbound_sms_messages was here
  66 warning: previous definition of from_addresses was here
  66 warning: previous definition of email_templates was here
  66 warning: previous definition of email_messages was here
  66 warning: previous definition of command_types was here
  66 warning: method redefined; discarding old webhooks
  66 warning: method redefined; discarding old sms_templates
  66 warning: method redefined; discarding old sms_messages
  66 warning: method redefined; discarding old session_info
  66 warning: method redefined; discarding old reports_messages_sms_statistics
  66 warning: method redefined; discarding old reports_messages_email_statistics
  66 warning: method redefined; discarding old message_types
  66 warning: method redefined; discarding old keywords
  66 warning: method redefined; discarding old inbound_sms_messages
  66 warning: method redefined; discarding old from_addresses
  66 warning: method redefined; discarding old email_templates
  66 warning: method redefined; discarding old email_messages
  66 warning: method redefined; discarding old command_types
  56 warning: instance variable @io not initialized
  54 warning: instance variable @bottom_margin not initialized
  41 warning: instance variable @sort_order not initialized
  41 warning: instance variable @field_name not initialized
  39 warning: instance variable @outage_response not initialized
  36 warning: URI.regexp is obsolete
  34 warning: instance variable @file_attacher not initialized
  32 warning: instance variable @idp_slo_service_binding not initialized
  18 warning: instance variable @meta not initialized
  18 warning: instance variable @links not initialized
  18 warning: instance variable @is_collection not initialized
  17 warning: net/http: nil HTTP header: apikey
  13 warning: instance variable @deferred_eager_loading_data not initialized
  11 warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
  10 warning: instance variable @header_row not initialized
   7 warning: parentheses after method name is interpreted as an argument list, not a decomposed argument
   7 warning: instance variable @discard_past not initialized
   6 warning: global variable `$TESTING' not initialized
   5 warning: instance variable @pid not initialized
   3 warning: previous definition of next was here
   3 warning: previous definition of last was here
   3 warning: method redefined; discarding old next
   3 warning: method redefined; discarding old last
   3 warning: method redefined; discarding old created_at
   3 warning: instance variable @previous_time not initialized
   3 warning: assigned but unused variable - url
   3 warning: assigned but unused variable - e
   3 warning: `*' interpreted as argument prefix
   2 warning: statement not reached
   2 warning: previous definition of initialize was here
   2 warning: previous definition of aws_signer was here
   2 warning: previous definition of aws_acl= was here
   2 warning: method redefined; discarding old tag
   2 warning: method redefined; discarding old resources
   2 warning: method redefined; discarding old parameters
   2 warning: method redefined; discarding old iv
   2 warning: method redefined; discarding old initialize
   2 warning: method redefined; discarding old host
   2 warning: method redefined; discarding old cek
   2 warning: method redefined; discarding old aws_signer
   2 warning: method redefined; discarding old aws_acl=
   2 warning: method redefined; discarding old api_methods
   2 warning: instance variable @logger not initialized
   2 warning: instance variable @id_attr not initialized
   2 warning: instance variable @attribute_definitions not initialized
   2 warning: The called method `initialize' is defined here
   1 warning: previous definition of yellow was here
   1 warning: previous definition of white was here
   1 warning: previous definition of validate_schema was here
   1 warning: previous definition of uuid= was here
   1 warning: previous definition of uuid was here
   1 warning: previous definition of type= was here
   1 warning: previous definition of type was here
   1 warning: previous definition of to_gapi was here
   1 warning: previous definition of tag_logger was here
   1 warning: previous definition of status was here
   1 warning: previous definition of serialize was here
   1 warning: previous definition of red was here
   1 warning: previous definition of qualifier= was here
   1 warning: previous definition of qualifier was here
   1 warning: previous definition of open was here
   1 warning: previous definition of on_send was here
   1 warning: previous definition of on_class was here
   1 warning: previous definition of on was here
   1 warning: previous definition of mailer was here
   1 warning: previous definition of latest= was here
   1 warning: previous definition of latest was here
   1 warning: previous definition of jobs was here
   1 warning: previous definition of included was here
   1 warning: previous definition of green was here
   1 warning: previous definition of ga_collection_uri was here
   1 warning: previous definition of frozen_check! was here
   1 warning: previous definition of from_gapi was here
   1 warning: previous definition of field_name= was here
   1 warning: previous definition of field_name was here
   1 warning: previous definition of encoding= was here
   1 warning: previous definition of encoding was here
   1 warning: previous definition of encode64 was here
   1 warning: previous definition of cyan was here
   1 warning: previous definition of canonicalized_signed_info was here
   1 warning: previous definition of blue was here
   1 warning: previous definition of aws_signer= was here
   1 warning: previous definition of asset_host_public was here
   1 warning: previous definition of __synchronized_sidekiq_retry_in_block was here
   1 warning: previous definition of __synchronized_sidekiq_retries_exhausted_block was here
   1 warning: previous definition of __synchronized_sidekiq_options_hash was here
   1 warning: mismatched indentations at 'rescue' with 'def' at 31
   1 warning: mismatched indentations at 'else' with 'if' at 20
   1 warning: method redefined; discarding old yellow
   1 warning: method redefined; discarding old white
   1 warning: method redefined; discarding old version
   1 warning: method redefined; discarding old validate_schema
   1 warning: method redefined; discarding old uuid=
   1 warning: method redefined; discarding old uuid
   1 warning: method redefined; discarding old username
   1 warning: method redefined; discarding old use_cache
   1 warning: method redefined; discarding old updated_at
   1 warning: method redefined; discarding old type=
   1 warning: method redefined; discarding old type
   1 warning: method redefined; discarding old to_gapi
   1 warning: method redefined; discarding old title_level=
   1 warning: method redefined; discarding old title_level
   1 warning: method redefined; discarding old tag_logger
   1 warning: method redefined; discarding old supported_request_sources
   1 warning: method redefined; discarding old status
   1 warning: method redefined; discarding old ssl
   1 warning: method redefined; discarding old serialize
   1 warning: method redefined; discarding old sent_at
   1 warning: method redefined; discarding old security_token
   1 warning: method redefined; discarding old scopes
   1 warning: method redefined; discarding old scm
   1 warning: method redefined; discarding old schemas
   1 warning: method redefined; discarding old red
   1 warning: method redefined; discarding old recording=
   1 warning: method redefined; discarding old qualifier=
   1 warning: method redefined; discarding old qualifier
   1 warning: method redefined; discarding old proxy_uri
   1 warning: method redefined; discarding old properties
   1 warning: method redefined; discarding old password
   1 warning: method redefined; discarding old on_send
   1 warning: method redefined; discarding old on_class
   1 warning: method redefined; discarding old name
   1 warning: method redefined; discarding old mailer
   1 warning: method redefined; discarding old logger
   1 warning: method redefined; discarding old log_level
   1 warning: method redefined; discarding old latest=
   1 warning: method redefined; discarding old latest
   1 warning: method redefined; discarding old json=
   1 warning: method redefined; discarding old json
   1 warning: method redefined; discarding old inspect
   1 warning: method redefined; discarding old indentation_level=
   1 warning: method redefined; discarding old included
   1 warning: method redefined; discarding old ignored_violations
   1 warning: method redefined; discarding old id
   1 warning: method redefined; discarding old green
   1 warning: method redefined; discarding old gcommit
   1 warning: method redefined; discarding old frozen_check!
   1 warning: method redefined; discarding old from_gapi
   1 warning: method redefined; discarding old field_name=
   1 warning: method redefined; discarding old field_name
   1 warning: method redefined; discarding old encoding=
   1 warning: method redefined; discarding old encoding
   1 warning: method redefined; discarding old encode64
   1 warning: method redefined; discarding old enabled=
   1 warning: method redefined; discarding old cyan
   1 warning: method redefined; discarding old config=
   1 warning: method redefined; discarding old config
   1 warning: method redefined; discarding old completed_at
   1 warning: method redefined; discarding old client_secret
   1 warning: method redefined; discarding old client_id
   1 warning: method redefined; discarding old client
   1 warning: method redefined; discarding old canonicalized_signed_info
   1 warning: method redefined; discarding old body
   1 warning: method redefined; discarding old blue
   1 warning: method redefined; discarding old base_path
   1 warning: method redefined; discarding old banner_class=
   1 warning: method redefined; discarding old aws_signer=
   1 warning: method redefined; discarding old authentication_retries
   1 warning: method redefined; discarding old asset_host_public
   1 warning: method redefined; discarding old api_version
   1 warning: method redefined; discarding old add_path
   1 warning: method redefined; discarding old add_file
   1 warning: method redefined; discarding old add_cert
   1 warning: method redefined; discarding old adapter
   1 warning: method redefined; discarding old absolute_path?
   1 warning: method redefined; discarding old __synchronized_sidekiq_retry_in_block
   1 warning: method redefined; discarding old __synchronized_sidekiq_retries_exhausted_block
   1 warning: method redefined; discarding old __synchronized_sidekiq_options_hash
   1 warning: instance variable @with not initialized
   1 warning: instance variable @times not initialized
   1 warning: instance variable @suffix not initialized
   1 warning: instance variable @schema not initialized
   1 warning: instance variable @middle not initialized
   1 warning: instance variable @form_address not initialized
   1 warning: instance variable @filter_methods not initialized
   1 warning: instance variable @at_most not initialized
   1 warning: instance variable @_ran_once not initialized
   1 warning: character class has duplicated range: /(?<=scheme)(\s*)=(\s*)([\".:_\-\/\w]+)/
   1 warning: character class has duplicated range: /(?<=label)(\s*)=(\s*)([\".:_\-\/\w\s]+)/
   1 warning: assigned but unused variable - y2
   1 warning: assigned but unused variable - y1
   1 warning: assigned but unused variable - testEof
   1 warning: assigned but unused variable - secondary_status
   1 warning: assigned but unused variable - rest
   1 warning: assigned but unused variable - response
   1 warning: assigned but unused variable - pathlen
   1 warning: assigned but unused variable - non_danger_threads
   1 warning: assigned but unused variable - matcher_url
   1 warning: assigned but unused variable - i
   1 warning: assigned but unused variable - gate_name
   1 warning: assigned but unused variable - filename
   1 warning: assigned but unused variable - content
   1 warning: assigned but unused variable - comment_result
   1 warning: assigned but unused variable - check
   1 warning: ambiguous first argument; put parentheses or a space even after `/' operator
   1 warning: The called method is defined here
   1 warning: The called method `t' is defined here
   1 warning: The called method `put' is defined here
   1 warning: The called method `post' is defined here
   1 warning: The called method `patch' is defined here
   1 warning: The called method `measure' is defined here
   1 warning: The called method `get' is defined here
   1 warning: The called method `find_benefit_claim_type_increment' is defined here
   1 warning: The called method `delete' is defined here
   1 warning: The called method `add' is defined here
   1 warning: Dir.exists? is a deprecated name, use Dir.exist? instead
   1 warning: /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/tracing/writer.rb:3: warning: loading in progress, circular require considered harmful - /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/core.rb
   1 warning: /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/tracing/workers.rb:3: warning: loading in progress, circular require considered harmful - /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/core.rb
   1 warning: /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/tracing/tracer.rb:3: warning: loading in progress, circular require considered harmful - /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/core.rb
   1 warning: /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/tracing/trace_operation.rb:3: warning: loading in progress, circular require considered harmful - /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/core.rb
   1 warning: /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/tracing/sync_writer.rb:3: warning: loading in progress, circular require considered harmful - /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/core.rb
   1 warning: /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/tracing/span_operation.rb:5: warning: loading in progress, circular require considered harmful - /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/core.rb
   1 warning: /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/tracing/sampling/rule_sampler.rb:3: warning: loading in progress, circular require considered harmful - /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/core.rb
   1 warning: /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/tracing/sampling/rule.rb:3: warning: loading in progress, circular require considered harmful - /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/core.rb
   1 warning: /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/tracing/sampling/rate_sampler.rb:3: warning: loading in progress, circular require considered harmful - /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/core.rb
   1 warning: /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/tracing/sampling/rate_by_service_sampler.rb:3: warning: loading in progress, circular require considered harmful - /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/core.rb
   1 warning: /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/tracing/runtime/metrics.rb:3: warning: loading in progress, circular require considered harmful - /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/core.rb
   1 warning: /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/tracing/pipeline.rb:3: warning: loading in progress, circular require considered harmful - /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/core.rb
   1 warning: /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/tracing/event.rb:3: warning: loading in progress, circular require considered harmful - /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/core.rb
   1 warning: /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/tracing/correlation.rb:3: warning: loading in progress, circular require considered harmful - /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/core.rb
   1 warning: /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/tracing/buffer.rb:3: warning: loading in progress, circular require considered harmful - /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/ddtrace-1.8.0/lib/datadog/core.rb
   1 warning: /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32: warning: loading in progress, circular require considered harmful - /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/typhoeus-1.4.0/lib/typhoeus/adapters/faraday.rb
   1 warning: /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32: warning: loading in progress, circular require considered harmful - /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/savon-2.12.0/lib/savon.rb
   1 warning: /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32: warning: loading in progress, circular require considered harmful - /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/guard-rspec-4.7.3/lib/guard/rspec.rb
   1 warning: /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32: warning: loading in progress, circular require considered harmful - /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/danger-8.6.1/lib/danger/request_sources/github/github_review.rb
   1 warning: /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32: warning: loading in progress, circular require considered harmful - /Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/claide-plugins-0.9.2/lib/claide/command/gem_helper.rb
```

**Comment by npeterson54** [comment]
Looks good to me, closing out
