### ISSUE TITLE
Update Governance Team operational processes to reflect static pages exemption from QA standards

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#53673]
## User Story
As a Governance team member, I want to make sure our processes and guidance for supporting QA at the Staging Review include specific guidance around static pages so that VFS teams aren't asked to be help to non-applicable standards.

Assignee: @it-harrison 
Peer Reviewer: @CherylEvans 

## Description
OCTO [recently approved](https://dsva.slack.com/archives/GNF5GSD9N/p1675719361752149?thread_ts=1675716849.902929&cid=GNF5GSD9N) exempting static pages from QA. We need to update the documentation on Governance Team processes to make this clear 

## Tasks
- [x] update the [Staging Review script](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review+-+Moderator+Responsibilities#Step-4.3) to omit reference of QA if Review is for a static page
- [x] update the [How to complete a QA review for Staging review touchpoint](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2428010558/How+to+complete+a+QA+review+for+Staging+review+touchpoint) page to explain static page exemption

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Governance team's process for providing QA feedback at Staging Review includes exemptions for statis pages

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
@CherylEvans I have two drafts for your consideration:
* [How to Complete a Staging Review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2538012724/Copy+of+How+to+complete+a+QA+review+for+Staging+review+touchpoint)
* [Staging Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2537979905/Copy+of+Staging+Review+-+Moderator+Responsibilities+-+static+page+QA+exemption)

**Comment by CherylEvans** [comment]
@it-harrison Hi Ian.  I made a few minor changes such as capitalization and grammar; other than that it looks great to publish.  :-)
