### ISSUE TITLE
Determine next steps for Platform Security Engineers at Design Intent

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#53688]
## User Story
As a governance team member, I want to connect with the platform security engineers and understand if they are getting the information they need from design intent meetings, so that we can ensure we are supporting Privacy, Security, and Infrastructure Readiness Reviews (PSIRRs).

Assignee: @briandeconinck 
Peer Reviewer: @sterkenburgsara 

## Description
The Platform Security Engineers (@gary-fallon @joeniquette ) have had the opportunity to attend 3 different Design Intents over the last sprint. The purpose of this ticket is to figure out next steps for helping them improve the PSIRR process.

* Did they get what they needed out of the Design Intent?
    * If not, what was missing?
* Do they want an opportunity to follow up with the VFS team post-Design Intent?
* Would they like an opportunity to ask questions in the meeting? (this may be challenging to implement)
* What do they think the appropriate next steps are?
* Would they like to permanently attend Design Intent's moving forward?
* What are the implications, concerns and/or risks of Platform Security Engineers being involved in the Design Intent permanently?

The purpose of this ticket is to "pick the brains" of the Platform Security Engineers to help determine what solutions should be put forth, if any.

## Tasks
- [x] Connect with @gary-fallon @joeniquette and ask questions regarding their experience attending design-intent touchpoints and whether those are meeting their needs for PSIRRs currently
- [ ] Determine next steps for platform security engineers at Design Intent (do they need to ask questions or have time at those meetings?)
- [ ] Determine impact to the Design Intent touchpoint if Platform Security Engineers having a more permanent role

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have determined next steps for Platform Security Engineer's role at the Design Intent
- [ ] We have determined impacts to the Design Intent touchpoint with Platform Security Engineers having a more permanent role

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@briandeconinck @sterkenburgsara please be sure to complete the ticket details above. ty!

**Comment by briandeconinck** [comment]
Status update: Connected with Gary and Joe. Joe expressed an interest in being able to ask questions at Design Intent to help determine whether additional meetings might be needed with the VFS team, and will be following up with a draft of some of the questions they might want to ask.

**Comment by shiragoodman** [comment]
Connected with Gary on 2/27. The list of questions is not yet complete so this work will carry into the next sprint.

**Comment by shiragoodman** [comment]
Gary shared this doc on 3/8: https://vfs.atlassian.net/wiki/spaces/PSEC/pages/2541715457/Design+Intent

**Comment by shiragoodman** [comment]
Ticket #54910 opened to document proposed solution PSIRR and present to Platform Security for their approval.
