### ISSUE TITLE
Operational and VFS-facing updates re: PSIRR not needed for static pages

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#53686]
## User Story
As a Governance team member, I want to make sure products that are strictly static pages are not recommended a PSIRR at CC Kickoff so that I'm not asking teams to take unnecessary steps. 

As a VFS team member, I want to know what type of products require a PSIRR so that I know what is required for my team.

Assignee: @sterkenburgsara 
Peer Reviewer: @briandeconinck 

## Description
Currently, VFS-facing guidance does not indicate to teams that static pages (or iterations/updates to those pages) are not required to undergo Privacy, Security, Infrastructure, and Readiness Review (PSIRR). We need to update guidance to provide clarity around PSIRR reviews, so that only the necessary touchpoints are recommended.

## Impacted Artifacts
- [Custom Tracks Flow](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1872822276/Custom+Tracks+Flow)
- [PSIRR page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/privacy-security-infrastructure-readiness-review) on Platform Website

## Tasks
- [x] Redesign custom tracks flow using [Mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1676486000565/b37faafd60422b6ac153d7e160e979ed09fbde0c?sender=u792eff8ef82f499a192a4934) (deprecate Lucid Chart version since most team members cannot access or edit using that tool)
- [x] Edit the custom tracks flow diagram for static pages to eliminate the recommendation for PSIRR reviews
- [x] Update PSIRR review page on platform website under "Timing" section to indicate that this touchpoint is not applicable for static pages (or iterations on static pages)

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS teams know and understand that PSIRR is not required for static pages
- [x] Governance team processes are updated to ensure that static page products are not recommended the PSIRR

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@briandeconinck @sterkenburgsara please be sure to update the user story, tasks, description and AC. Ty!

**Comment by sterkenburgsara** [comment]
@shiragoodman updated this ticket to reflect a new task for moving Custom Flow Track diagram to Mural. Mural version [here](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1676486000565/b37faafd60422b6ac153d7e160e979ed09fbde0c?sender=u792eff8ef82f499a192a4934). // cc @briandeconinck

**Comment by sterkenburgsara** [comment]
@briandeconinck this ticket is ready for review.

**Comment by sterkenburgsara** [comment]
@briandeconinck can you peek at this when time allows?

**Comment by briandeconinck** [comment]
@sterkenburgsara Sorry for the delay on this review! And thank you to @shiragoodman for the nudge. This all looks great and can be closed!
