### ISSUE TITLE
Create new card for practice area

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#53690]
## User Story
As a Platform OCTO lead, I want to see how Staging Review issues disperse across the varying practice areas so that I understand what practice areas need the most support.

Assignee: @it-harrison 
Peer Reviewer: @sterkenburgsara 

## Description
Governance team is looking to expand the Collaboration Cycle Dashboard using the data set already available within Domo and associated with the dashboard. The purpose of this ticket is to create a new card showing how the Staging Review issue tickets vary across the 4 practice areas - design, accessibility, content and IA.

## Impacted Artifacts
[Collaboration Cycle Dashboard ](https://va-gov.domo.com/page/1340527018?userId=1646566899)

## Tasks
- [x] Using the existing data set of Staging Review issue tickets (currently being utilized in the existing Collab Cycle dashboard cards), create a new card showing distribution of all issue tickets by practice area.
   - A bar chart may make the most sense, however feel free to experiment. Note that 1 issue could have multiple practice areas impacted, so a pie chart or donut chart is not ideal.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The Collaboration Cycle Dashboard shows how all Staging Review issue tickets are dispersed by practice area

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
@sterkenburgsara I created [two views](https://va-gov.domo.com/page/1340527018) for this data, one showing simple counts for each practice area and another showing hits to specific combinations of practice areas.

**Comment by it-harrison** [comment]
@sterkenburgsara I created the pie chart just as an experiment because it doesn't double count anything whereas the pie chart does; if somebody didn't realize that a ticket could belong to more than one practice area the bar chart might be a little misleading...but apart from the pie chart (which takes time to digest) I wasn't sure how else to convey the information. We might just go with the bar chart and add a reminder that tickets can have multiple practice areas?

**Comment by sterkenburgsara** [comment]
@it-harrison ah, makes sense. I do agree it takes a long time to digest. I think I lean toward just using the bar chart? @shiragoodman can you weigh in?

**Comment by sterkenburgsara** [comment]
Update: @it-harrison and @shiragoodman realized that our dataset is challenging to manipulate in its current format - it is double-counting tickets where more than one practice-area applies. To handle that, we introduced [this ticket](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/gh/department-of-veterans-affairs/va.gov-team/55104), which will result in us requesting an update to our BigQuery data export from Github. We'll attend analytics office hours on 3/14/23 to make our request & will update this ticket with our resolution after that.
