### ISSUE TITLE
Create new card for issue number

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#53691]
## User Story
As a Platform OCTO lead, I want to see how Staging Review issues disperse across the varying issue numbers so that I understand where VFS teams are having trouble adhering to standards.

Assignee: @it-harrison 
Peer Reviewer: @sterkenburgsara 

## Description
Governance team is looking to expand the Collaboration Cycle Dashboard using the data set already available within Domo and associated with the dashboard. The purpose of this ticket is to create a new card showing how the Staging Review issue tickets vary across VA.gov Experience Standard issue numbers.

## Impacted Artifacts
[Collaboration Cycle Dashboard ](https://va-gov.domo.com/page/1340527018?userId=1646566899)

## Tasks
- [ ] Using the existing data set of Staging Review issue tickets (currently being utilized in the existing Collab Cycle dashboard cards), create a new card showing distribution of all issue ticket by VA.gov Experience Standard issue number
   - A pie chart may make the most sense as it shows the percentage of the whole, however feel free to experiment and try different things.
 -  [ ] Share chart with Shira and Ray via #platform-governance-team channel for review and feedback (no need to share with Shira first before Ray)

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] The Collaboration Cycle Dashboard shows how all Staging Review issue tickets are dispersed by VA.gov Exp Std issue number

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@it-harrison @sterkenburgsara this ticket is ready to be worked on!

estimating this ticket at a 3, not a 5 like the[ category ticket,](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/gh/department-of-veterans-affairs/va.gov-team/33099) since it seems like it wasn't as much effort as initially assumed.

**Comment by it-harrison** [comment]
@sterkenburgsara the card is finished and [on the dashboard](https://va-gov.domo.com/page/1340527018) but it is in the "appendix" section; I have tried to drag and drop it onto the main section of the page but cannot do so for some reason...can you try?

**Comment by shiragoodman** [comment]
@it-harrison @sterkenburgsara if you can't figure it out, I encourage you to join Analytics Office hours today at 3:30pm ET. Here is the Zoom link: https://oddball-io.zoom.us/j/86920766098

**Comment by it-harrison** [comment]
@sterkenburgsara I fixed the issue after going to office hours (basically you have to select "Edit Dashboard" from the wrench in the top right of the Dashboard page)

**Comment by sterkenburgsara** [comment]
@it-harrison Awesome! I'll look at it and aim to close today.

**Comment by sterkenburgsara** [comment]
@shiragoodman to clarify from today's planning meeting, did you want us to play around with the type of visual for this card before closing (instead of pie chart), or is that something we're saving for the review at a later date? // cc @it-harrison

**Comment by shiragoodman** [comment]
@sterkenburgsara save for a later date. I will create a follow up ticket.
