### ISSUE TITLE
Re-enable RSA key GitHub Action

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#53700]
## Summary
Revisit the [alert-aws-rsa-format](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/.github/workflows/alert-aws-rsa-format.yaml) GitHub Action that comments when line breaks are found in an AWS key parameter. There are keys stored in AWS that have line breaks (and not `\n`) _and_ a new line at the end of the param store entry  (see screenshot) 
![image (11)](https://user-images.githubusercontent.com/10993987/218831458-4ef75dc7-cfab-4ded-a611-65af80392ca8.png)
I think what’s important here is having the new line at the end. The PR that calls that key was merged last week (https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1424) and we haven’t had any problems with it. This is the parameter: [/dsva-vagov/vets-api/staging/vbms_key](https://console.amazonaws-us-gov.com/systems-manager/parameters/dsva-vagov/vets-api/staging/vbms_key/description?region=us-gov-west-1&tab=Table#list_parameter_filters=Name:Contains:%2Fdsva-vagov%2Fvets-api%2Fstaging%2Fvbms_key). The certs included in that PR also have line breaks and that hasn't been a problem. 

The workflow has been disabled (via the UI) so as not to warn people unnecessarily and create a "boy who cried wolf" scenario. 

**Example comment**: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1424#issuecomment-1419765377:
![image](https://user-images.githubusercontent.com/10993987/218830286-313a212e-cc91-4327-8f7b-23ba57ffab73.png)

This issue could be related to 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/52585
## Tasks
- [ ] Determine what will type of formatting will cause EKS to break.
- [ ] Modify GitHub Action to check for the incorrect formatting.
- [ ] Re-enable workflow here: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/actions/workflows/alert-aws-rsa-format.yaml

**Comment by LindseySaari** [comment]
May need to circle back on this.. I know we are going to focus on Automating this in the next project. cc @laineymajor

**Comment by laineymajor** [comment]
Should be taken care of by the auto deploy

**Comment by laineymajor** [comment]
this is accounted for in another ticket that's part of the toil reduction work
