### ISSUE TITLE
[TEXT SOLUTION] [Design] Create Content and Final Wireframes for Text Message Solution

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#53704]
## Scenario
Veteran is checked-in AND we submitted a travel claim for them. We need to tell them that we are going to send them a text message with the submission status of their travel claim (i.e. we don't want them to think that when the claim is approved we are sending them anything). 

## Tasks
- [x] Create content for message
- [x] Create final mockups with callouts 
- [x] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [x] UI review meeting with product/UX team for feature capabilities
- [x] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Wireframe available on Sketch Cloud
- [x] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.

**Comment by kellysmith1008** [comment]
Looking into [this pattern](https://design.va.gov/patterns/help-users-to/keep-a-record-of-submitted-information) (and other types) before scheduling a meeting with FE

**Comment by kellysmith1008** [comment]
Created [some mockups](https://www.sketch.com/s/f18f3642-ef85-474e-ae69-a2f09504e34d) in sketch. Have shared with Ben and we're coworking via the sketch file. Planning on sharing with the full UX team tomorrow

**Comment by loripusey** [comment]
Question: regarding the 1-2-3 control. Does the control imply that all steps must be completed? Do you think Veterans will understand that they can do any of the steps?

**Comment by kellysmith1008** [comment]
Yeah, the 1-2-3 control is something I want to discuss with the UX team. It's part of the design pattern, so I'm not sure if we can go without the numbers in it - still trying to determine that. But I agree, it may add confusion for Veterans and lead them to think they have to do all 3 steps vs any one of them. I'll keep you posted on what I find about having the number labels there!

**Comment by kellysmith1008** [comment]
@ytsaoca The mockups in the included sketch file have been shared with the team and agreed upon version is titled "Updates after Ben's comments V2" - the third frame in the group. Can you put this formally into sketch cloud and close this ticket?

**Comment by ytsaoca** [comment]
Discussion about the UI elements: https://dsva.slack.com/archives/C04J6H2LYUU/p1678134468872719

**Comment by ytsaoca** [comment]
Discussion about the UI elements: https://dsva.slack.com/archives/C04J6H2LYUU/p1678134468872719

**Comment by ytsaoca** [comment]
Final wireframe: https://share.goabstract.com/d4065aa6-8234-497c-9b46-b73b9afdd659
Reviewed with the design team.

**Comment by ytsaoca** [comment]
Final wireframe: https://share.goabstract.com/d4065aa6-8234-497c-9b46-b73b9afdd659
Reviewed with the design team.
