### ISSUE TITLE
[Design, FE] My VA audit improvements: a11y prep for staging review

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#53706]
## Background
In preparation for staging review we need to perform accessibility tests on all the audit improvement work to My VA. This will be a joint effort from Design and FE to perform these tests, and Product to ensure everything is documented to submit the request. 

[A11y staging review preparation](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review) documentation for reference. 

Additional reference: examples of same tests/process done for staging reviews of 
- [Onsite notifications](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/launch-materials/onsite-notifications-mvp-a11y-staging-review-prep.md)
- [payment info v2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/launch-materials/payment-info-v2-a11y-staging-review-prep.md)

## Tasks
- [x] Design and FE to perform the accessibility tests as documented [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/launch-materials/my-va-audit-improvements-a11y-staging-review-prep.md)
- [x] PM to assist as needed and track progress in staging review artifact documentation

## Acceptance Criteria
- [x] Accessibility tests are ready for Staging Review

**Comment by ajakabcin** [comment]
Complete - thank you!
