### ISSUE TITLE
BE | Profile | Direct Deposit | Migrate POST Direct Deposit Info

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#53714]
## Background
Add functionality to add/update direct deposit information from the Lighthouse API. This includes configuration, specs, attribute mapping, error handling, and logging.

## Tasks
- [x] Update Service to include POST function
- [x] Update request/response mapping
- [x] Add error handling and validation
- [x] Create Service Specs

## Acceptance Criteria
- [x] Service specs passing.
- [ ] PR reviewed and approved.

**Comment by tpharrison** [comment]
Discovered that the sandbox environment is using mocked data, so updating records won't work in this environment.  

Tried using staging, but get the following error...
`Backend Connection Error - Failed to retrieve data from MPI`

Reached out to David Lennon and waiting to hear back.

**Comment by tpharrison** [comment]
@Samara-Strauss @BerniXiongA6 

Ran into an issue with Lighthouse DD API updates. 

The sandbox it is only connected to mock data sources that do not actually make the updates so the data remains static.  Because of this, I connected to the staging environment.  Making update requests in staging returns the following error:
```
502: Backend Connection Error - Failed to retrieve data from MPI
```

Reached out to David Lennon and he has confirmed that the error is related to a certificate issue within the Lighthouse API and he is working to get it resolved.

Trying to work around this, but it may hold me up a bit.  I'll keep you posted.

**Comment by Samara-Strauss** [comment]
> Trying to work around this, but it may hold me up a bit. I'll keep you posted.

Totally understand. Just keep us posted, and feel free to adjust sprint expectations as needed.
