### ISSUE TITLE
[EOAS][Preneeds] Failed form submissions are not automatically retried

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#53710]
## Background
Many of our form applications have the ability to retry sending submissions if the initial submission fails. In some cases we also have mechanisms in place that allow us to manually retry submissions. The pre-needs application doesn't have either of these mechanisms in place, so there is no good way to resubmit failed submissions currently.

## Context
There was an outage recently that led to ~160 failed submissions. When we looked more deeply at the backend code, we realized that the submissions are not part of Sidekiq jobs, and failed submissions would have to be resubmitted manually. We looked into that as well and found that there would need to be more work done in order to create a script / set of scripts to resubmit manually.

## Tasks
- [ ] Convert the submission functions to use Sidekiq jobs
- [ ] Determine if there is a way to manually resubmit if the Sidekiq jobs fail

## Acceptance Criteria
- [ ] Preneeds submission functions are using Sidekiq

**Comment by MichelleDieudonne** [comment]
@jerekshoe We have some questions around this item.  We are working towards the EOAS system no longer being part of this form and we will be integrating our form with a different system, but that is about a year out.  We have reviewed this item and to take this on now would be a larger lift, and would also be a duplicate effort on our end since we are already working to have this issue resolved with our form integration mentioned above.  Does this item need to be completed now, or are you good with us holding this item to be worked on/fixed with our integration efforts?  cc @ksantiagoBAH @CatherineHughes202 @carly-yamrus

**Comment by jerekshoe** [comment]
@MichelleDieudonne I think it's fine to leave it until later, though I would make sure that you integrate this functionality into whatever solution you use in the future as this is fairly standard across most of the forms. Downstream systems are never guaranteed to have 100% uptime so it's good to have something in place so you don't have to resubmit the failed submissions manually

**Comment by MichelleDieudonne** [comment]
@jerekshoe Thank you.
