### ISSUE TITLE
[BE] Remove enable/disable flags for check-in and pre-checkin

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#53712]
## Background

We have `check_in_experience_enabled` and `check_in_experience_pre_check_in_enabled` feature flags that disable the apps when turned off. We [recently discovered](https://dsva.slack.com/archives/C02G6AB3ZRS/p1676400275729829) that feature toggles should not be relied upon to stay enabled long-term. We should remove this feature toggles, since we have maintenance mode available if we need to prevent either app being used.
  
## Tasks
- [ ] [FE] remove feature toggles and dependent code
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] `check_in_experience_enabled` and check-in is functional
- [ ] `check_in_experience_pre_check_in_enabled` and pre-check-in is functional
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
too old, closing
