### ISSUE TITLE
Update Governance team operational processes to reflect QA's removal from Midpoint Review

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#53725]
## User Story
As a Governance team member, I want to make sure our operational processes are up to date so that I am able to follow correct guidance for Midpoint Review.

Assignee:
Peer Reviewer:

## Description
Assuming OCTO approves the [removal of QA from the Midpoint review](#52783) we will need to update operational guidance on confluence.

## Impacted Artifacts
[Midpoint Review - Moderator Responsibilities page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Moderator+Responsibilities) 
 [How to document feedback for a Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1945239838/How+to+document+feedback+for+a+Midpoint+Review) 

## Tasks
- [x] update the [Midpoint Review - Moderator Responsibilities page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Moderator+Responsibilities) to remove mention of QA
- [x] update the [How to document feedback for a Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1945239838/How+to+document+feedback+for+a+Midpoint+Review) to remove mention of QA

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team processes no longer reflect QA at Midpoint Review

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
This ticket and #53726 should be worked on in parallel.

**Comment by it-harrison** [comment]
@briandeconinck I updated the pages (the changes were small so I didn't make a copy - just removing mention of QA)

**Comment by briandeconinck** [comment]
@it-harrison This all looks good! I think you can close this ticket.
