### ISSUE TITLE
Update VFS-facing documentation to reflect QA's removal from Midpoint Review

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#53726]
## User Story
As a VFS team member, I want to know what artifacts to provide and who to expect to heard feedback from at the Midpoint Review re: QA so that I can prepare appropriately. 

Assignee: @it-harrison 
Peer Reviewer: @briandeconinck 

## Description
Assuming OCTO approves the [removal of QA from the Midpoint review](#52783) we will need to update VFS-facing documentation.

## Impacted Artifacts
[Midpoint Review touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review) - QA artifacts section

## Tasks
- [x] update the [Midpoint Review page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review) to remove mention of QA and QA artifacts
- [x] Create draft of change history page announcing that VFS teams will no longer be asked to provide QA artifacts, and Governance QA will no longer provide feedback.
- [ ] Follow Platform Communication Playbook for sharing with VFS teams

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] VFS teams are aware that their products will not be reviewed for QA at Midpoint Review
- [ ] VFS teams are aware that they will not receive feedback for QA at Midpoint Review
- [ ] VFS teams will no longer be asked to submit QA artifacts at Midpoint Review
- [ ] VFS teams have been informed of the changes for QA at Midpoint Review.

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@it-harrison @briandeconinck although this doesn't have the `needs-refinement` label, we are waiting for Ray to give his full approval for QA being removed from Midpoint. He did say "approved" in [this slack message](https://dsva.slack.com/archives/GNF5GSD9N/p1676414713552249) but asked for some additional detail. I'd prefer to wait until we get additional feedback from Ray before making this change. Ty!

**Comment by shiragoodman** [comment]
This ticket and #53725 should be worked on in parallel.

**Comment by it-harrison** [comment]
@briandeconinck:
* I updated the [Midpoint Review page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)
* I have a [draft of a change announcement](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2539225089/Copy+of+Change+history+-+remove+QA+from+Midpoint) ready to to post 
* below is a draft of a change announcement to post on slack:

> :mega: **QA removed from Midpoint Review**
> 
> Attention:  **VFS teams**
> 
> On **02/21/23**, the Governance Team removed QA from Midpoint Review
> 
> **Impact**: QA will no longer participate in the Midpoint Review. VFS teams will not be asked to provide QA artifacts at Midpoint Review.
> 
> **Documentation**: see the [guide to the Midpoint Review for VFS teams](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review).
> 
> **Support**: Reach out to Governance team by filing a support request on #vfs-platform-support
>

**Comment by briandeconinck** [comment]
@it-harrison Sorry for the slow review here. All of this looks perfect, I think you're good to post the announcement.

**Comment by it-harrison** [comment]
@shiragoodman it is waiting to be published later today

**Comment by shiragoodman** [comment]
Ok, thank you. In the future, please wait to post the Slack change announcements post until the change history page is updated. You can close this ticket once that takes place.

**Comment by shiragoodman** [comment]
@it-harrison thanks for making the change. Please publish and close out this ticket when the updated CH page is live. TY!
