### ISSUE TITLE
Update VFS-facing documentation to reflect static pages exemption from QA standards

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#53722]
## User Story
As a VFS team member, I want to know that statis pages are exempt from QA Standards at Staging Review so that I can prepare appropriately. 

Assignee: @CherylEvans 
Peer Reviewer: @it-harrison 

## Description
OCTO [recently approved](https://dsva.slack.com/archives/GNF5GSD9N/p1675719361752149?thread_ts=1675716849.902929&cid=GNF5GSD9N) exempting static pages from QA. We need to update VFS-facing documentation to make this clear.

## Impacted Artifacts
[Staging Review touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review) - QA Artifacts section
[QA Standards page](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards) 

## Tasks
- [x] update the [Staging Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review) clarify static page exemption
- [x] update the [QA Standards page](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards) to clarify the static page exemption

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] VFS teams know that static pages are exempt from upholding the QA Standards

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
@it-harrison Hi Ian.  I have the drafts ready for you to take a look at.  Please feel free to make any recommendations with regard to verbiage or placement.  Once you give the thumbs up, I will publish. :-) [Copy of Staging Review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2536865793/Ticket+53722+Copy+of+Staging+review+2) and [Copy of QA Standards](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2536898561/Ticket+53722+-+Copy+of+QA+standards).
I changed the verbiage on both to: VFS teams will not be held accountable for upholding QA Standards with regard to static pages. This is counter-productive as their products do not have dynamic content that requires extensive testing.
I took this verbiage from the [Proposal to exempt static pages from QA Standards document](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2515992950/Proposal+to+exempt+static+pages+from+QA+Standards).

**Comment by it-harrison** [comment]
@CherylEvans looks good! thank you!

**Comment by CherylEvans** [comment]
@it-harrison I changed it slightly as I wasn't quite satisfied with my previous edits: A VFS team that launches a static page through the Collaboration Cycle will not be held responsible for upholding the QA Standards. Static pages do not have dynamic content that requires extensive testing.
Sorry about the last minute change of heart.  :-)

**Comment by it-harrison** [comment]
@CherylEvans looks even better!

**Comment by CherylEvans** [comment]
Changes have been published.

**Comment by shiragoodman** [comment]
@it-harrison @CherylEvans FYI I'm going to announce this change to Sitewide CAIA via the collab cycle channel. Since the audience for this is small (they're the only team that directly supports static pages) I do not think we need to make a VFS-wide announcement.

**Comment by CherylEvans** [comment]
@shiragoodman Thank you, Shira!!
