### ISSUE TITLE
Design Schedule Graphic for ToT Slide

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#53732]
# Description
Leadership has requested that our team adopt a similar schedule graphic as other technical teams have done, we would like to make something that is more well designed and laid out visually. This would be preferably done in PowerPoint, but the design could be mocked up and fine tuned elsewhere and recreated in PowerPoint

# Tasks
- [x] Get reference for Technical Teams slide graphics (ping @JoeTice )
- [x] Draft design(s) for an alternate approach and review
- [x] Review w/ PM & TL
- [x] Finalize graphic and provide to be incorporated into slide

# Acceptance Criteria
- [x] Graphic is available for slide

**Comment by LillyBoot** [comment]
Unable to access the Digital Services @VA slack channel. Not sure if I have to wait till my eQuip goes through

**Comment by JoeTice** [comment]
Design has been handed off and incorporated into slide - more iteration may come on this in the future
