### ISSUE TITLE
Create content for new BTSSS widget on travel reimbursement page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#53735]
## Issue Description

Public Websites opened an intake request for content support on the [VA travel pay reimbursement](https://www.va.gov/health-care/get-reimbursed-for-travel-pay/) page. They will be updating the Veteran experience to deep-link authenticated users directly to BTSSS. They are going to create a widget similar to the Cerner widgets we have on other health care pages (medical records, prescriptions, secure messaging, etc.) where there is separate content for both authenticated an unauthenticated users.

We need to provide content for them to build the widget with. 

See intake request #53402 for more info and screenshots of suggested copy.

## Tasks
- [x] Create content 
- [x] Review (Laura)
- [x] Copyedit (Megan)
- [x] Provide PW with content in original intake ticket #53402 (Megan)
- [x] Create new ticket for reworking drupal page and adding react widget when ready to launch (Randi)

## Acceptance Criteria
- [ ] Public Websites has final content for widget

**Comment by aliyahblackmore** [comment]
Hi @laurwill this content is ready for you to review.
[BTSSS react widget content_AB_3.7.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10914399/BTSSS.react.widget.content_AB_3.7.docx)

**General notes/questions:**

1. On the static page, the widget will replace the AccessVA action link, [outlined in the epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9157).

2. On the unauth and auth versions, PW would need to remove this sentence - “You’ll access this system through the AccessVA travel claim portal.”

3. For the authenticated experience (when someone is signed in), if this sentence remains above the widget, “You can file a claim online through the Beneficiary Travel Self Service System (BTSSS),” does the widget content need to also mention BTSSS?  Or can we pull that content in to the widget? Based on the mockup from PW, there is mention of BTSSS, but I don't think this is needed if it is used in sentence before the widget content. I included two options in the word document. 

4. On the [Health benefit hub](https://www.va.gov/health-care/) page, I think we’d want to shift the language to “how to file a claim” to match the [linked page](https://www.va.gov/health-care/get-reimbursed-for-travel-pay/).

5. Question for PW team – will this page account for the DS Logon transition?

6. This isn't in the scope of the work and we should focus on the widget content, but calling out that we'd want to remove the question "Filing a travel pay claim for the first time?" and shift language to be along the lines of "If you're filing a travel claim for the first time..." We could consider doing this work in the future.

**Comment by laurwill** [comment]
Thanks @aliyahblackmore !

Here's the Word doc back with some edits and comments — I want to run a couple things by Danielle in today's team sync before we pass this to Megan for copyedit.
[BTSSS.react.widget.content_LW_3.8.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10921491/BTSSS.react.widget.content_LW_3.8.docx)

And good callout about the language on the hub page. I also found some broken links on related pages we need to fix. Here's a list of related changes to include as part of this work:
- Change teaser for travel pay on [hub page](https://www.va.gov/health-care/) from "how to apply for" to "how to file a claim for"
- Fix broken link to BTSSS on Access VA on 2 R&S pages: [How to file a travel reimbursement claim](https://www.va.gov/resources/how-to-file-a-va-travel-reimbursement-claim-online/) and [How to set up direct deposit for travel pay](https://www.va.gov/resources/how-to-set-up-direct-deposit-for-va-travel-pay-reimbursement/)
- Fix link on [pdf form page](https://www.va.gov/find-forms/about-form-10-3542/) to point to BTSSS on Access VA, rather than Access VA homepage

And collecting questions here for @DanielleThierryUSDSVA : 
- Keep mention of BTSSS tool name in unauth static page?
- Does new deep link affect how we link to the tool from R&S pages or the pdf form page?
- Can we shorten headers to use either "travel pay claim" or "claim for travel reimbursement" (assuming we want to continue to alternate for search reasons)?
- The first section on this page has info about what travel pay covers before the link into the tool. Would we want to move this into a "What travel pay covers" H2 below the widget to follow health care tool pattern more closely, or leave as is?
- We don't mention checking status of a travel pay claim on this page, but the [2020 press release](https://www.visn4.va.gov/VISN4/features/beneficiary-travel-reimbursement.asp) says BTSSS has this feature. Would we want to add a sentence noting that here?

**Comment by DanielleThierryUSDSVA** [comment]
@laurwill These Qs aren't as easy to answer as I think we thought. I'll get back to you on them tomorrow.

**Comment by DanielleThierryUSDSVA** [comment]
> Keep mention of BTSSS tool name in unauth static page?
- I saw your comment in the Word doc about us mentioning this tool in an R&S page and being consistent here. I think that makes sense.

> Does new deep link affect how we link to the tool from R&S pages or the pdf form page? I know we've done a react widget in an action link in at least one instance, but wasn't sure if we'd do that here.
- Let's put a ticket on this question in the backlog so we can keep this request scoped. I think the answer is that we change those links to drive folks here to this landing page so they can sign in and access the tool. But that's not critical to this request.

> Can we shorten headers to use either "travel pay claim" or "claim for travel reimbursement" rather than "general health care travel pay reimbursement"? SEO seems to point to those 2 options.

Please leave these as is for now. There are 2 different types of travel reimbursement claims (general and special mode). So these sections are specific to the general type. There's a question that speaks to special mode in the accordions. SMEs reviewed this page relatively recently for accuracy. We can certainly go back to them at some point with questions like this, but that's out of scope for this request and we need to stay focused on our priorities.

> The first section on this page has info about what travel pay covers before the link into the tool. Would we want to move this into a "What travel pay covers" H2 below the widget to follow health care tool pattern more closely, or leave as is?

- This is this way to distinguish what general travel reimbursement specifically covers. But I think we can move it down as long as we keep the "general" in the H2 about what it covers.

> We don't mention checking status of a travel pay claim on this page, but the 2020 press release says BTSSS has this feature. Would we want to add a sentence noting that here?
- Let's put this in the backlog to keep this request scoped. This is a good question, but something we can address in another ticket.

Thanks!

**Comment by wesrowe** [comment]
Hi all – just checking in to see how close you are to finalizing content for this widget. We would build the widget this sprint if content is available. I see there's active discussion going on, do you have an ETA?

**Comment by wesrowe** [comment]
@laurwill, I'll make a note in our ticket that we need to be in touch with you all about when the widget is ready to go live. [Ticket for reference](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12591).

**Comment by RLHecht** [comment]
Closing this ticket. I created #55342 for us to add the widget to our page once it's ready.

**Comment by aliyahblackmore** [comment]
Hi @laurwill - tracking the changes to the travel pay claim page, R&S pages, and form page here. 

**### Travel pay claim page:** 

- Reverted to the last draft version before publish (10/07/2022) to address the linkies issue.
- I removed the sentence about AccessVA.
- From Danielle’s reply, we’re holding off on adding in your sentence about checking the status of a travel claim page.
- I edited the sentence with the question “If,” as I mentioned earlier via Slack.

**### On the How to file a VA travel pay claim  R&S:**

- I adjusted the page intro text and removed the mention of AccessVA. I added "Then file a claim online through the BTSSS.
- I changed the CTA link text to “File a travel pay claim online” and as we chatted linked to the travel entry portal, since the other CTA goes to the travel pay claim page and we'd want to avoid two CTA links that go to the same page.
- In the step by step process list, as we chatted, I removed the second step and adjusted the new second step to say “Sign in and go to…” 
- I removed the periods from the steps
- Not within the scope of the ticket but on the last step, should we adjust the question to "If you need time to gather receipts or other information..."? 

**### On the How to set up direct deposit R&S:**

- @laurwill I initially adjusted the CTA to go to the travel pay claim page with a jump link to the first H2, **but** because this page is about setting up direct deposit I think that we’d want this CTA to be “Sign in to the travel claim entry portal.” I made this adjustment to reflect this pages content vs. aligning with language on the “how to file" page. Happy to change this - let me know your thoughts!
- In the new step 3, I edited the link for "Find out how to file a claim for VA travel pay" and changed it to a jump link the new H2, as we chatted.
-**Potential backlog change:** I think that we may want to revisit the steps after someone submits (by  fax or mail) their direct deposit form. I think we may want to consider adding information about when someone would check their profile to see if their direct deposit info is correct? Is that immediately or after a few days? That step seems unclear and curious about whether there can be any later updates there!

**### On the form page:**
As we chatted, I linked directly to the travel claim entry portal page (instead of the BTSSS home page).

**Comment by megzehn** [comment]
**Update:** Re-opening this ticket since there's some work that still needs to be tracked.

After talking with @laurwill, I reverted these 2 pages to the version currently published and fixed just the broken links.

- [How to file a VA travel pay claim R&S](http://preview-prod.vfs.va.gov/preview?nodeId=19367)
- [How to set up direct deposit R&S](http://preview-prod.vfs.va.gov/preview?nodeId=16665)

**Older broken link:** https://eauth.va.gov/accessva/?cspSelectFor=bts
**New link:** https://eauth.va.gov/accessva/?cspSelectFor=oauth.BTSSS&targetPath508=cspSelectFor%3Dhttps%253A%252F%252Ffed.eauth.va.gov%252Fisam%252Fsaml20SPFed%252Fsaml20&foiaUrl=https%3A%2F%2Fwww.va.gov%2Ffoia%2F&nonce=W3pEOdg6kIndmX8ZvUEzWZk2fzHayNxP

I then reverted back to the latest version with @aliyahblackmore's edits. We'll still need to review these and pick these back up when @laurwill gets back. 

Thanks!

**Comment by mistymg** [comment]
Spoke with Randi. OK to close this ticket as it's irrelevant now with more changes to travel pay pages.
