### ISSUE TITLE
UX Research on the Platform Website

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#53739]
## Research Plan
Link to [Platform Website Research Plan](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2588278812/Platform+Website+User+Experience+Research+v.2) and other artifacts

## Problem Statement
The Platform website has been launched for approximately two years. The purpose for it is to be a one-stop-shop for documentation to build in VA.gov for VFS team members. The content of the Platform website is owned maintained by all Platform teams. However, the Platform Content team ultimately maintains product updates, content changes, style guidelines and support processes associated with content maintenance for the Platform website.

Since the Platform website was first launched, a lot has changed in the program. For example, how the Platform offers support to VFS teams, support staff rotations, technical teams' priorities and general team member changes across the program. Ultimately, the Platform Content team does not know how this has impacted the quality of the content on the Platform website (or if it has been impacted at all).

The Platform Content team would like to perform UX research to find out how VFS teams perceive the Platform website at this point in time. By seeking feedback from the end users (VFS teams), we can get a pulse on the health of the content of the Platform website, identify pain points, make recommendations to Platform leadership on how to improve the website and prioritize recommendations for the roadmap.

**Research ideas -** 

Qualitative:
- How helpful or unhelpful is the documentation on the Platform website in helping you build VA.gov?
- How easy or difficult is it to find documentation on the Platform website with the current information architecture (IA)?
- How up-to-date do you perceive the documentation on the Platform website?

- How often do you reference documentation on the Platform website before seeking help from the Slack support channel?
- How easy or difficult are the support instructions and outlets to understand on the Platform website? Ex. Website footer, Support pages, etc.

- Last comments about the Platform website

Quantitative:
- How often do you use the Platform website to do your job?
- What is your role?
- How long have you been in a VFS (Veteran Facing Services) team?
- Are you willing to be interviewed by the Platform Content team about your answers?

## Hypothesis
**If** _the Platform Content team seeks feedback from VFS team members about the usefulness of the Platform website_ 
**then** _we will gain better insights that will help us make improvements to the website from a user-centered perspective._.

**If** _the Platform Content team leverages user-centered feedback to iterate on the Platform website_ 
**then** _the Platform website will be more useful to VFS teams who rely on it more._

**If** _the Platform website is more user-friendly for VFS teams who rely on it to build on VA.gov._ 
**then** _they will look for information on it as their primary source of truth._

**If** _VFS team members rely on the Platform website as their primary source of truth._ 
**then** _they will rely less on the Platform Slack support channel._

## High Level User Story/ies
As a Platform Content team member,
I need to understand how satisfied or dissatisfied VFS team members are with the Platform website in helping them find documentation they need,
so that we can determine where the pain points are with an open-ended follow up question.

As a Platform Content team member,
I need to understand if VFS team members find the IA of the Platform website helpful,
so that we can assess whether we need to reorganize it or not.

As a Platform Content team member,
I need to understand if VFS team members find the content of the Platform website up-to-date,
so that we can gain insights to help us create technical documentation lifecycle guidelines.

As a Platform Content team member,
I need to know if VFS team members find the "support" offerings on the website easy to understand,
so that we can gain insights on how to better position/offer our services (report issues with the website, suggest content, request general help from the Platform, etc.)

### What must be true in order for you to consider this epic complete? 

- [x] We have a list of VFS pain points associated with their experience in using the Platform website.
- [x] We understand how those pain points currently impact the rest of the Platform teams.
- [x] We are able to prioritize recommendations to improve the Platform website.

**Comment by vbellissimo** [comment]
@raywangoctova Documenting a new epic on our board to do UX research on the Platform website soon.

**Comment by raywangoctova** [comment]
Please take a look at the recent platform surveys to insight as well.
