### ISSUE TITLE
[FE] My VA audit improvements: Investigate & fix GA tagging on "Claims and Appeals" section

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#53744]
## Background
Per guidance from the Analytics team, we actually do have almost all GA tracking covered for the audit updates to My VA. The one outliers are the links in the Claims and Appeals section: "Learn how to file a claim" and "Manage all claims and appeals."

![image](https://user-images.githubusercontent.com/45603961/219092495-a51a434a-4270-49ae-a1c3-837708e674c0.png)
(logged into staging with test user cecil.morgan@id.me)
 
According to the audit that our previous APM performed, she was seeing GA events in staging for those two links labeled as follows:
* `profile - navigation - view link - view learn how to file a claim` 
* `profile - navigation - view link - view manage claims and appeals`

Ordinarily these events should follow naming convention as follows (like :
* `navigation- link list - Claims and appeals - view learn how to file a claim` 
* `navigation - link list - Claims and appeals - view manage claims and appeals` 

We need to determine why these event tags are formatted this way (did we use the wrong elements from the component library?), and - more importantly - determine what we need to do to get them formatted correctly, and execute that work.

## Tasks
- [x] Download Adswerve chrome extension (if you don't have it already for help investigating the issue)
- [x] Investigate the code/links outlined above to determine why the GA event tags are formatted as profile tags and not navigation link list tags (for example, were the wrong elements used from the component library because this sort of tagging should come with the component "for free")
- [x] Determine what needs to be done to correct the tagging
- [x] Execute the fix to correct the tagging

## Acceptance Criteria
- [ ] We understand what happened with the tagging on these two links (note in the comments of this ticket is sufficient)
- [ ] We have a path for a fix 
- [ ] Ultimately, the event tagging is corrected 

## Resources
- [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/claims-and-appeals-FE-documentation.md)
- [My VA GA event tag audit](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/Product/audit-analytics-request.md)
- [Notes from Analytics team (Michelle Dooley) in response to our audit document](https://docs.google.com/document/d/1G6OjL1tnJ-goCiu-z3hsAq8KGRldcHCYuI1f0l5tx3s/edit)

**Comment by allisonlu** [comment]
The incorrect GA event name is being recorded here:

https://github.com/department-of-veterans-affairs/vets-website/blob/e801bb13171f46cf50b298e57d54f0610461dbd4/src/applications/personalization/dashboard/components/claims-and-appeals-v2/ClaimsAndAppealsV2.jsx#L61-L87

This should be a straight-forward fix. I would just need to change the following:

| current | new |
|--|--|
| `profile-navigation` | `nav-linkslist` |
|`profile-action` | `links-list-header` | 
| `profile-section` | `links-list-section-header` |

**Comment by allisonlu** [comment]
The updated event names are appearing on staging for me! 

![Screenshot 2023-02-23 at 2 06 50 PM](https://user-images.githubusercontent.com/8542413/221006009-a8666e53-fa72-4e88-868d-f02c5b38a360.png)
