### ISSUE TITLE
INTL - Sitewide Homepage Dashboard - Data Model Updates

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#53748]
## Issue Description
This is an internal ticket for the [sitewide homepage dashboard updates](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49618)  

The request is to - COMPLETE
- Add `va.gov/new-home-page` URL to scope of data pulled in and add field to capture which homepage version was visited so dashboard can be filtered for each.
- Add **User Satisfaction** section to dashboard with new Medallia data coming in.

The new data has been added now we need to QA.

Resources:
[Homepage dashboard](https://va-gov.domo.com/page/80919003) page_version filter at top to filter to new homepage specific metrics 

![image](https://user-images.githubusercontent.com/93597659/225979123-2ca3ad96-5e5d-467b-8e1d-d6452757571c.png)

[New Homepage Update Request ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49618)

[Standardized Search Dashboard](https://va-gov.domo.com/page/1964748112) another resource for QA as this data model was built off it but specific to homepage

[QA Processes - How to's](https://vfs.atlassian.net/wiki/spaces/AT/pages/2216001587/QA+Processes)

[Chloe's summary doc](https://vfs.atlassian.net/wiki/spaces/AT/pages/2428338517/Chloe+Project+Background+Notes) (we are not doing first interaction portion at this time.

see [slack threads](https://dsva.slack.com/archives/C01S78V4AUA/p1674057955607299) in platform-analytics-private channel for latest notes.

---
## Tasks

QA data:
- [ ] Create GA reports matching each card specs to ensure matching within an acceptable margin of error) (similar to what we did for Profile dashboard 
![image](https://user-images.githubusercontent.com/93597659/225978883-2901719e-df74-41f5-a82f-5dd9be58b130.png)
[GA report list for Profile](https://analytics.google.com/analytics/web/#/savedreport-overview/savedreport-overview/a50123418w177519031p184624291/) 
- [ ] If report does not match trouble shoot what may be going on.  Is it not picking up a url, is the filter not working, are you looking at correct metrics (pages, events, etc)
- [ ] Create [tracking doc](https://docs.google.com/spreadsheets/d/1H-rD3y9OKcwmWhztNyUCqpWws8oIV1xRq43gLzWPz9s/edit#gid=0) for each card denoting status (Pass or Fail, if fail provide findings)

## Acceptance Criteria
- [ ] QA has been completed and approved.
---

**Comment by michelle-dooley** [comment]
Closing this ticket.  We need to regroup on Domo clean up process and time to complete tables.
