### ISSUE TITLE
Tech Discovery - endpoint /rateddisabilities

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#53755]
## Issue Description
Form 526 currently calls EVSS.submit_all_claim endpoint for submitting claims via vets-api. This call needs to be migrated to Lighthouse as part of overall eVSS migration to Lighthouse.

endpoint /rateddisabilities is not being migrated to Lighthouse as LH already has an endpoint that provides related information. This issue is to discover 
- what data field(s) are being sent and received from the eVSS endpoint by the 526 form?
- what is the endpoint in existence in LH that replaces this service?
- what data field(s) are being sent and received from the new LH endpoint?
- can form 526 switch to this LH endpoint without changes for this service?

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] what data field(s) are being sent and received from the eVSS endpoint by the 526 form?
- [ ] what is the endpoint in existence in LH that replaces this service?
- [ ] what data field(s) are being sent and received from the new LD endpoint?
- [ ] can form 526 switch to this LH endpoint without changes for this service?
- [ ] a ticket created on 526 board to switch this end point to LH endpoint, with dependencies documented, if any

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
cc @ahay-agile6 @colevoss @navaeddie - this ticket is for the 4th eVSS endpoint that is not being migrated to Lighthouse. This is slightly different from the other endpoint migration tickets.

**Comment by navaeddie** [comment]
Swagger docs for endpoint?
https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/form_526/getRatedDisabilities

**Comment by navaeddie** [comment]
>  what data field(s) are being sent and received from the eVSS endpoint by the 526 form?
No information is being _sent_ to eVSS other than the vet's personal information in the auth headers (see class `DisabilityCompensationAuthHeaders`).
It's receiving a veteran's disability rating and related information.
> what is the endpoint in existence in LH that replaces this service?
Veteran Verification API's DisabilityRatingAttributes
> what data field(s) are being sent and received from the new LH endpoint?
LH endpoint requires Authorization Code Flow authorization (because that's the form identified with this API in the sandbox registration form).

The documentation for `DisabilityRatingAttributes` suggests the response includes each of the fields that the DisabilityRatingSerializer currently handles:
https://developer.va.gov/explore/verification/docs/veteran_verification?version=current
https://api.va.gov/internal/docs/veteran-verification/v1/openapi.json

**Comment by RakshindaAslam** [comment]
The work has been pulled into [SPIKE] Design Common Api Interface #54076
