### ISSUE TITLE
Platform synthetic tests for staging

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#53750]
**PROBLEM STATEMENT**
Datadog synthetic tests that verify the appropriate response from the endpoints that we are testing for the vets-api server migration to EKS in Staging. This will be a combination of HTTP tests, stored in Terraform that don't require authentication. Anything that requires authentication will need to be stored as a browser based test in Datadog to utilize the login flow and cookies that are needed to make authenticated API requests after login.

**TASKS/questions**
- [ ] VFS aka "Inside" testing 
- [ ] revproxy aka "Outside" testing 
- [ ] Validation and Apply Terraform

**Comment by LindseySaari** [comment]
[PR for staging synthetic tests via Terraform](https://github.com/department-of-veterans-affairs/devops/pull/12568). Rebecca is planning to apply the Terraform and merge the PR. The remaining (authenticated) routes will be created as browser based tests for the staging env.

**Comment by LindseySaari** [comment]
[Staging synthetic browser tests ](https://vagov.ddog-gov.com/monitors/manage?q=creator%3A%22Lindsey%20Hattamer%22)are all green ✅

**Comment by LindseySaari** [comment]
Still need someone to [apply the terraform from this PR](https://github.com/department-of-veterans-affairs/devops/pull/12568) and then this can be closed.

**Comment by rmtolmach** [comment]
Done. PR https://github.com/department-of-veterans-affairs/devops/pull/12568 merged and terraform applied ✅
