### ISSUE TITLE
Non-combined VHA submissions not being submitted

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#53757]
## Issue Description
While tracking submission numbers it looks like the only time we are receiving VHA submissions are when they are bundled with VBA debts. This may have been related to another FE bug that has been fixed but will continue to be tracked and worked to replicate locally. 

---
## Tasks
- [x] Replicate bug locally with only VHA debts
- [x] Identify cause
- [ ] Create any tickets that may need to be worked

## Acceptance Criteria
- [x] We can progress forward with VHA only submissions 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
