### ISSUE TITLE
Investigate discrepancy between VHA submissions and emails sent

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#53756]
## Issue Description
Jill has brought up that the number of emails going out for FSR confirmation is more than the total submissions being delivered

![image.png](https://images.zenhubusercontent.com/614a1fef81dbf0d12d8dd5ac/7dee2cf3-9427-470a-aeb4-b9f7367319e9)

---
## Tasks
- [ ] Investigate potential causes for these different numbers

## Acceptance Criteria
- [ ] We know a potential cause
- [ ] Generated future work to align the numbers
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Based on submission numbers within VHA SharePoint the emails sent closely align with the amount of PDF uploads. Grafana logs may have been missing API requests that prevented an accurate measurement. Also confirmed that there are multiple requests sending for each facility request. Opened new [ticket ](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/55554) to accommodate
