### ISSUE TITLE
Promote Vets-API Server with EKS to PROD: Release Plan

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#53760]
### Description
This captures the release plan for migrating Vets-API with EKS to PRODUCTION.

### Goal
The goal is to create a process for the promotion of Vets-API with EKS to PRODUCTION, with minimal interruption to veterans, VFS teams, and Platform teams.

### Overview
The completion of this initiative removes the current need to straddle the BRD and EKS line and move towards a more scalable and manageable approach to supporting the platform. Additionally, EKS provides the platform opportunities to innovate away from the monolithic approach currently in place and open doors to other architectures and technology stacks. This move also paves the way to address an improved maintenance model and CI/CD pipeline.

### Acceptance Criteria
- [x] Discovery for ['everything' remaining on BRD](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2403532805/Discovery+Vets-API+from+BRD+to+EKS+47627)
- [x] `Vets-API` is running EKS on dev and handling dev traffic
- [x] `Vets-API` is running EKS on staging and handling staging traffic
- [x] `Vets-API` is running EKS on sandbox and handling sandbox traffic
- [x] `Vets-API` is running EKS on production and handling production traffic
- [x] A VFS team is able to deploy their own containerized workloads all the way through into EKS production, if they so choose, with their production traffic being handled by that deployment
- [x] All documentation referencing BRD has been updated to reflect EKS infrastructure
*VFS-facing [documentation updates](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/54571)
*Platform team documentation updates
- [x] List of tests that can be automated post-release (This list has been started and is being tracked in the post-production rollout [epic](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/53387))
- [x] The `Vets-API` specific portion of the BRD, including Jenkins, has been deprecated and replaced with GitHub Actions that tie into the delivery model for `Vets-API` on EKS
* [Dev](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/52427)
* [Staging](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/53607)
* [Sandbox](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/54615)
* [Post Prod rollout](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/53387)

---
### Launch Checklist

...tested? YES - SEE TESTING DETAILS BELOW
- [x] Usability test (TODO: link) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it. _VFS teams tested to ensure endpoints are behaving as expected. Confirmed YES._
- [x] ... and issues discovered in usability testing have been addressed.
_All known issues have been addressed. Outlined below._
- [x] End-to-end manual QA or UAT is complete, to validate there are no high-severity issues before launching
_The appropriate VFS teams completed UAT (ex: VAOS) within staging after staging was at 100% EKS traffic._
- [ ] (if applicable) New functionality has thorough, automated tests running in CI/CD

... documented? IN PROGRESS ([epic](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/54571))
- [x] New documentation is written pursuant to our documentation style guide
_All platform website documentation will be updated March 20-22 in collaboration with the content management team._
- [x] Product is included in the List of VSP Products
_In progress. Will be complete prior to final go/no-go._
- [x] List the existing product that this initiative fits within, or add a new product to this list.
_Vets-API (no current product outline)_
- [x] Internal-facing: there's a Product Outline
_In progress. Will be complete prior to final go/no-go._
- [x] External-facing: a User Guide on Platform Website exists for this product/feature tool
_All platform website documentation will be updated March 20-22 in collaboration with the content management team._
- [ ] (if applicable) Post to #vsp-service-design for external communication about this change (e.g. customer-facing meetings) 
_NA_

... measurable YES - SEE DETAILS BELOW
- [x] (if applicable) This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
- [x] This change has an accompanying Platform Release Plan.
_See below_

When you're ready to launch... IN PROGRESS
- [x] Configure your communication to teams about your work using the Change Communication Guide
_This can be found in the route-based rollout plan for production._
- [ ] Conduct a go/no-go when you're almost ready to launch.

---
### Planning:

- Desired date range or test duration: January - March 2023
- Desired number of users: [VFS teams](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/52684) teams that own/maintain APIs
- The group(s) from which you'll recruit test users: [VFS teams](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/52684) that own/maintain APIs
- How you'll recruit test users: Slack channel #eks-migration-support, #vfs-all-teams, ZenHub [[tickets](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/52684)](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/52684), and Team of Teams meetings
- How you'll give test users access to the product: Testing commenced for each environment once said environment was running at 100% EKS.
- What "Success" criteria will you look at before launch? 100% of issues reported have been resolved and recorded in preparation for production rollout.
- How you'll measure your "Success" criteria? All major issues and their respective solutions have been recorded in our pre-production rollout [check](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/53356).

## Phase I: Testing
Endpoint testing is completed by endpoint-owning VFS teams to ensure their endpoints are behaving as expected in an environment that has been migrated to EKS.

1. Dev Environment: January 2023
2. Staging Environment: February 2023
*[Major issues + lessons learned](https://miro.com/app/board/uXjVPpBYbtM=/?share_link_id=601339122391)
3. Sandbox Environment [only applicable for lighthouse]: March 2-14
4. Load testing to be completed on March 20. Tech Team 1 will test for platform, while working with the check-in team and a team from Lighthouse to simulate the peak load.
5. Sidekiq HPA load test [complete](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/54026) on March 13.

### Results:

- Number of users: All endpoint-owning VFS teams + Platform (platform testing done by TT1) 	

- Results per your "Success" criteria:
All major issues reported by VFS testing teams have been [resolved and recorded](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/53356) for the prod migration.

- Number of major issues identified / fixed: 7/7
These included:
1. CORs for Traefik
2. ClamAV
3. Missing certs & secrets
4. Incorrect settings.yml
5. Test app race conditions (service account + sidekiq running)
6. Missing S3 buckets
7. General AWS work with the DevOps CoP required

- Any UX changes necessary based on the logs, user feedback, or VA challenges? NO

### Planning:

- Desired launch date: April 4, 2023 (1st route = Search)
Route-based prod rollout plan [linked here](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/54557).
- Post-launch KPI 1: 100% of major incidents resolved.
- Post-launch KPI 2: 80% of reported issues resolved. 
_Upon completion of KPI 1&2, move to the next route (outlined in the route-based prod rollout plan)._

### 1-week results:

**From DataDog Metrics for Search**
- Number of unique users: 
- Post-launch KPI 1 actual: 
- Post-launch KPI 2 actual: 
- Post-launch KPI 3 actual:
- Any issues with Platform handling/processing?: yes/no
  - If yes, what:
- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes/no
  - If yes, what: 

### 1-month results:

**From DataDog metrics for additional routes**
- Number of unique users: 
- Post-launch KPI 1 actual: 
- Post-launch KPI 2 actual: 
- Post-launch KPI 3 actual: 
- Any issues with Platform handling/processing?: yes/no
  - If yes, what:
- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes/no
  - If yes, what: 

## Post-launch Questions

*To be completed once you have gathered your initial set of data, as outlined above.*

1. How do the KPIs you gathered compare to your pre-launch definition(s) of "success"?
2. What qualitative feedback have you gathered from users or other stakeholders, if any?
3. Which of the assumptions you listed in your product outline were/were not validated?
4. How might your product evolve now or in the future based on these results?

**Comment by laineymajor** [comment]
https://vfs.atlassian.net/wiki/spaces/AP/pages/2037448871/Go+No+Go

**Comment by laineymajor** [comment]
- revproxy concerns: ex when we change revproxy for the search rollout, will that be cleanly changed? can we isolate the changes to a single config file?
*LH: we should be able to isolate and use conditionals; need to be very cautious when editing anything with revproxy

- can we test the route-based approach in staging? 
*would need to roll back to test brd to test this
*potentially use 2nd asg for this

- do we want to move the old configs to 'sites available' or something like that? how do we stage/deploy engine x configs
*make note of the last good config for the rollback (paste the rollback commit in the ticket)

- how do we decide which routes we rollout to first
*start with least impact to veteran
*2nd asg already has these routes
*modules
*REVIEW TRAFFIC OF THE ROUTES BEING ROLLED OUT
*REVIEW CURRENT ORDER OF THE ROLLOUT

- Check with the support team on which channels they are monitoring. How can these be accounted for in the support plan?

**Comment by laineymajor** [comment]
@laineymajor send link of product teams/apps to Ray

How are we measuring performance of the API?
- average latency times, max latency times, etc
- utilizing APM boards and vets-api specific board
- @laineymajor to clearly define the above in the release plan

**Comment by laineymajor** [comment]
there is a security related epic for this effort. add this security epic to the post prod epic (maybe even a project??)
how does this work ^ tie into the post-prod work already listed in the post prod epic

**Comment by laineymajor** [comment]
- [ ] create ticket for a monitoring/measuring plan... tag you and Oseas

**Comment by laineymajor** [comment]
ITEMS TO REVIEW DURING MARCH 28 GO/NO-GO [follow-up items from previous go/no-go]
- [ ] Product outline 
- [ ] Include product in product list
- [ ] Add notes about revproxy concerns to rollout plan
- [ ] Test route-based approach in staging [will be complete on 3.30; results will be posted to #eks-migration-support]
- [ ] Review of route order. Final decision. New candidate for second route.
- [ ] Monitoring mechanisms added to the support plan
