### ISSUE TITLE
Login.gov adoption team: Sprint 14 (2/16 - 3/1)

### ISSUE THREAD

**Issue by elizabethkochBT** [department-of-veterans-affairs/va.gov-team#53766]
## PTO

- Elizabeth OOO: 2/20-2/24
- John Offsite 2/21 - 2/24
- Jay Tanner OoO 2/20 
- Tyler: 2/16 - 2/17
- Carolyn: 2/24 & 2/28
- Federal holiday: President's Day 2/20
## Sprint 14 Priorities

Legacy Credential Migration:
- Design baseline migration data dashboards
- Continued discussion with Login.gov on MHV premium gaps
- Build organic adoption experiment content and assets
- Present grandfathering workflow to identity working group and comms meeting
- Create working prototype of grandfathering user flow in Sketch including content
- Partner with sitewide content team on plan to prevent DS Logon account creation from VA.gov
- Key collaboration cycle touchpoints
  - Research Review
  - Midpoint Review

 
## Retro Board

[Sprint 13 Retro](https://www.reetro.app/board/63e5271aabe3b3a8ca8cda88/63e5280cabe3b3a8ca8cdd83)

### Discussion Topics/Retro Action Items
 - [x] Sprint planning meeting async
 - [x] Review ceremonies to accommodate PST team members
 - [x] Creating dashboards - placeholder data is fine

### Legacy credential migrations & Login.gov proactive adoption
 - [x] Update grandfathering flow content based on sitewide content's feedback #53490
 - [x] Continued discussion with Login.gov around proofing and compensating controls #53783
 - [x] Update research plan and conversation guide based on John's feedback #53486
 - [x] Draft alternative grandfathering user flow(s) for testing #53410
 - [x] Design baseline migration data dashboards #51023
 - [x] Create research plan and conversation guide for 1st round of testing the grandfathering flow #52747
 - [x] Modal & logic to identify eligible users #53785 
 - [ ] Are you sure? Modal  #53787
 - [ ] Analytics tagging for organic adoption experiment  #53788
 - [x] Feature toggle for organic adoption experiment  #53789 
 - [ ] Reporting for organic adoption experiment #53790

## Collab Cycle Tasks 
 - [ ] Design Intent - IA Feedback - Login.gov adoption team, DS Logon Grandfathering / Inherited Proofing #53254
 - [ ] Design Intent - Accessibility Feedback - Login.gov adoption team, DS Logon Grandfathering & Inherited Proofing #53333
 - [ ] Submit artifacts for Research Review #53384
 - [ ] Submit prototype(s) for Midpoint Review #53383
