### ISSUE TITLE
[FE] My VA audit improvements: Investigate GA event tag on "learn about verification" link

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#53765]
## Background
Per guidance from the Analytics team, we actually do have almost all GA tracking covered for the audit updates to My VA. The one other outlier is on a link that appears for LOA1 users (unverified accounts) on the My VA page: "Learn how to verify your identity on Va.gov"
 
![image](https://user-images.githubusercontent.com/45603961/219141482-69019677-7485-4dcc-9c18-63f1083ee417.png)

We need to investigate whether there is tracking in place and if not, add tracking to that link. _To investigate the code/link, you'll need to sign into staging with an LOA1 (unverified) account - you can create an LOA1 test user account with any email address via ID.me, just stop short of the verification steps (which would make the account LOA3)._

## Tasks
- [x] Determine if there is GA event tracking in place on that link
- [x] If tracking does not exist, consult with the Analytics team (slack: `#vfs-analytics`) on appropriate tagging
- [ ] Implement tag
- [ ] Request review/validation on tag implementation from Analytics team

## Acceptance Criteria
- [ ] We have GA event tracking on the "Learn how to verify your identity on Va.gov" link

## Resources
- [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/LOA1-state-FE-documentation.md)
- [My VA GA event tag audit](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/Product/audit-analytics-request.md)
- [Notes from Analytics team (Michelle Dooley) in response to our audit document](https://docs.google.com/document/d/1G6OjL1tnJ-goCiu-z3hsAq8KGRldcHCYuI1f0l5tx3s/edit)

**Comment by allisonlu** [comment]
Per [Michelle Dooley on Slack](https://dsva.slack.com/archives/C1Q4294JJ/p1677162361932999?thread_ts=1677080235.872189&cid=C1Q4294JJ):

> I confirmed it is not tracking.  Are you using a web component for that link?  Seems like the va-link web component with event: nav-link-click would make sense here.

I'm going to go ahead today and see if implementing a web component for this will affect any other part of AE (I know Profile also uses the component that contains this link)

**Comment by allisonlu** [comment]
This is going to require a small refactor of the [`IdentityNotVerified` component](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/components/IdentityNotVerified.jsx). This will affect the [AccountSecurityContent component](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/profile/components/account-security/AccountSecurityContent.jsx) on Profile, and the main [Dashboard component](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/Dashboard.jsx) on the MyVA side. 

Shouldn't take more than this sprint, but wanted to note that.

**Comment by allisonlu** [comment]
Change is on staging! Ready for validation.

![Screenshot 2023-02-28 at 12 21 36 PM](https://user-images.githubusercontent.com/8542413/221929393-25a68b99-fedb-42b8-ab05-e5acd38c20b3.png)
