### ISSUE TITLE
[FE] Fix appointment details unit tests

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#53769]
## Background

Slack thread: https://dsva.slack.com/archives/C02G6AB3ZRS/p1676494166980289

The appointment details unit tests are sometimes failing, perhaps due to issues with the mock router. We need to reproduce, diagnose and fix the issue and re-enable the tests. It might make sense to split the test file out into check-in and pre-check-in files as part of this work.

## Tasks
- [ ] [FE] Diagnose cause and socialize with front end team
- [ ] [FE] Fix and re-enable tests 
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Appointment details tests are enabled and pass consistently
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
@loripusey this is one of the tests that I refactored and merged in earlier today. We can keep this ticket open here to monitor it for a bit. But could close it in a couple days if nothing crops up.

**Comment by brianseek** [comment]
I'm going to close this up since its been a week and new issues

**Comment by brianseek** [comment]
@acrollet had an issue with this test in the pipeline today. Re-opening for testing.

I can re-produce and error with his CHOMA-SEED. Not the same one exactly but still an error in the file.

**Comment by brianseek** [comment]
@loripusey a fix for this is now in place, maybe leave this in validate for a bit just to make sure again.

**Comment by brianseek** [comment]
I'm going to go ahead and close this one. Lets see if that triggers a flaky test :/
