### ISSUE TITLE
Review Spanish language assistance page 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#53777]
## Issue Description

In the VA.gov footer we have links to language assistance pages in Spanish and Tagalog. Now that we have a Spanish copy editor on the team, we should review the Spanish page to make sure there are no inconsistencies and it meets VA.gov's plain language and style guide standards. 

Page to review: https://www.va.gov/asistencia-y-recursos-en-espanol/

## Tasks
- [x] Copy edit page (Ana)
- [x] Confirm all links are working on Spanish page (Ana)
- [x] Confirm all links are working on Tagalog page (Ana)
- [x] Create doc with changes that need to be made (Ana)
- [x] Add list of links in doc of any new newer translated pages not already on page (Ana)
- [x] Open new ticket for Drupal work (Randi)

## Acceptance Criteria
- [x] Spanish language assistance page is reviewed

**Comment by RLHecht** [comment]
@ABeltran77 I wanted to add a few more items here that Danielle flagged as needing to look at on this page (as well as the Tagalog). I'll add them to the tasks list above too but wanted to point it out here.

We haven't checked the links on these pages in a long time, so we want to make sure they are all accurate, we don't have any broken links and we're not pointing to any broken PDFs. This is true for both the Spanish and Tagalog pages.

We also should be linking to any translated page that's currently on the site so we may need to add more links on this page. Not sure if PACT Act is currently on here.

**Comment by ABeltran77** [comment]
Completed edits for language assistance pages in Spanish and reviewed Spanish and Tagalog links.
[https://app.zenhub.com/files/133843125/48d23c39-69cf-48fd-b5bc-1d5b73e6cb31/download](https://app.zenhub.com/files/133843125/48d23c39-69cf-48fd-b5bc-1d5b73e6cb31/download)

**Comment by RLHecht** [comment]
Going to close this ticket. I created #55707 for Ana to do the drupal work in.
