### ISSUE TITLE
Modal GA tagging for organic adoption experiment

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#53788]
## Issue Description
_As part of the organic adoption experiment, we want to tag these features in order to track user behavior._

*Important to get this part right!
We plan to de-risk this by doing some up-front research and/or get consultation from Analytics team.

---
## Tasks
- [x] Set up tag
- [x] Apply tag
- [ ] Test tag

## Acceptance Criteria
- [ ] Able to track user behavior with respect to organic adoption experiment
- [ ] CTA clicks
- [ ] X clicks
- [ ] Learn more clicks

---

**Comment by sdickson-gt** [comment]
blocked needing integration with feature flipper so doesn't become active if promoted.  Can't test until in staging - GA is integrated in staging.  Is GA linked to our Dev env?
