### ISSUE TITLE
Continued discussion with Login.gov around proofing and compensating controls

### ISSUE THREAD

**Issue by elizabethkochBT** [department-of-veterans-affairs/va.gov-team#53783]
## Issue Description
As two government agencies sharing responsibilities on providing a streamlined process to enable a Veteran to assert their identity and unlock access to government services, we we want to align on a framework on assessments and approvals to succeed in launching this process to production.

---
## Tasks
- [x] Discuss gaps on MHV premium inheritance
- [ ] Align on corrective measures to close out MHV premium inheritance
- [x] Leverage discussion to initiate a reusable framework/pattern going forward

## Acceptance Criteria
- [x] Meeting with Login.gov on 2/17
- [x] Update risk document on path forward
- [x] Discussions on rev 4
- [x] Process overview of Login.gov assessments

**Comment by porta-antiporta** [comment]
Had a discussion with Login.gov where we discussed the gaps identified in the last sprint.
Coming out of meeting, we are looking on creating a document (as a canary into a repeatable framework) where we discuss 1 gap and point out potential compensating controls, paths forward.

In process of drafting that for the AAL2 gap.

**Comment by porta-antiporta** [comment]
Note, in discussion with @elizabethkochBT, IPP (in person proofing) is also in the mix for a control for credential migration. Putting together a product brief on IPP.

**Comment by porta-antiporta** [comment]
Have not yet heard back from Login.gov. Am aware they have a few internal high priority initiatives that may be cause for some of the delay.

**Comment by porta-antiporta** [comment]
Other updates:
* The IPP product brief has been updated to reflect MVP scope.
* Prelim rev 4 comments have been submitted. NIST has extended deadline to 4/14 so there's time to submit additional.
