### ISSUE TITLE
Are you sure? modal

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#53787]
## Issue Description
_As part of the organic adoption experiment, the system will need to show users who close the first modal an "Are you sure?" modal to retarget them._

---
## Tasks
- [ ] _Build modal per designs from @carolynwill & @CarlDickerson _

## Acceptance Criteria
- [ ] Are you sure? modal is activated when user clicks X to close initial modal
- [ ] Users can click through to start the process or learn more
- [ ] Modal can be dismissed by standard methods (X, clicking outside)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sdickson-gt** [comment]
dependent on finalization of design

**Comment by elizabethkochBT** [comment]
canceled
