### ISSUE TITLE
Modal & logic to identify eligible users

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#53785]
## Issue Description
_As part of the organic adoption experiment, the system will need to identify eligible users and show them a modal to get them to begin the organic account adoption process._

---
## Tasks
- [ ] Decide on detection vs. self-select (as proposed by @kscoulter )
- [ ] If detection: decide on detection method (Use GCID? To look for correlated Login.gov/ID.me. Has authoritative source)
- [ ] Build detection logic
- [ ] Build modal per designs from @carolynwill & @CarlDickerson 

## Acceptance Criteria
- [ ] Users with DSL account & no ID.me/Login.gov account can see the modal
- [ ] Users can click through to start the process or learn more
- [ ] Modal can be dismissed by standard methods (X, clicking outside)
- [ ] After dismissing: modal doesn’t pop up again that same day

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kscoulter** [comment]
@MOStudioCarolyn, @alevindecanini, @CarlDickerson Please add the links to the buttons so I can complete this ticket

**Comment by MOStudioCarolyn** [comment]
@kscoulter The primary button will take you to Login.gov. The secondary button will take you [here](https://www.va.gov/resources/signing-in-to-vagov/#should-i-create-a-logingov-or-)

**Comment by holytoastr** [comment]
Logic for detecting the correct users is still in progress. Taking a little bit of time to familiarize myself with some of the quirks of the backend
