### ISSUE TITLE
Feature toggle for organic adoption experiment

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#53789]
## Issue Description
As part of the organic adoption experiment, we need to add a feature toggle in order to be able to 1) show the features to a limited set (10%) of users, and 2) turn the features on and off (or roll back, if needed) according to the experiment plan.

[Flipper gem details](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles)

---
## Tasks
- [x] Research Flipper gem
- [x] Build toggle
- [x] Deploy in staging & prod to our team only (list of emails) for testing purposes

## Acceptance Criteria
- [x] All experiment components can be toggled as a set
- [x] Toggling is done manually
- [x] 10% of users are targeted
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by holytoastr** [comment]
Added me, Ksenia, and Anthony as initial users with access to toggle control ui. Can add more if given list of who should be included.
