### ISSUE TITLE
Reporting for organic adoption experiment

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#53790]
## Issue Description
_In order to report on the organic adoption experiment, we need to be able to view data about it in a dashboard format._

---
## Tasks
- [ ] _TBD_

## Acceptance Criteria
- [ ] _TBD_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alevindecanini** [comment]
this is redundant with: 
https://app.zenhub.com/workspaces/logingov-adoption-team-632280b31e745000136a61fc/issues/gh/department-of-veterans-affairs/va.gov-team/53788
and
https://app.zenhub.com/workspaces/logingov-adoption-team-632280b31e745000136a61fc/issues/gh/department-of-veterans-affairs/va.gov-team/55329
