### ISSUE TITLE
Documentation site - consolidate GitHub repositories

### ISSUE THREAD

**Issue by minafarzad** [department-of-veterans-affairs/va.gov-team#538]
## User Story

As a team member building or supporting products on VA.gov, I need to be able to access and navigate documentation so that I can find what I need on my own quickly and easily. 

## VSP Objective (Q1 & Q2 2020)

O1: Any volume of simultaneous customers have a delightful, self-service, end-to-end experience using the Platform to build on VA.gov.

## Measuring Success (KRs/KPIs)

- [VSP KR] Increase in customer NPS
- [VSP KR] Reduction in volume of “non-human-needed” support requests month over month
- Number of documentation support requests per week

## Details and Notes

This super epic encompasses the migration of crucial documentation content from legacy `vets.gov-team` and `va.gov-vfs-teams` GitHub repos into `va.gov-team` and `va.gov-team-sensitive` and the deprecation ("shut down") of the primary legacy repo, `vets.gov-team`. 

Note that in some cases, a link within `va.gov-team` to crucial documentation that "lives" elsewhere is sufficient. 

- Example of time when a link is sufficient: engineering documentation that needs to "live" within the repo where the code itself actually "lives" is linked from the appropriate README.md in `va.gov-team`
- Example of a time when a link is not sufficient: a platform customer has been using an external, non public documentation site and does not want to/see the value in/have the time to transfer their crucial documentation to `va.gov-team`.

### Goal

Crucial, non-sensitive documentation created by and for platform customers and platform teams is consolidated in `va.gov-team` and `va.gov-team-sensitive`.

### Assumptions and Hypotheses

**If** we make our documentation comprehensive and easy to navigate **then** people working with or on VSP will be able to independently find the information they need to build successful tools.

## Areas for Discovery
- ~What repositories _other than_ `vets.gov-team` and `va.gov-vfs-teams` (if any) should we be consolidating documentation from? (Capture that info here or in another super epic.)~ <- this was determined to be out of scope. Future migration efforts will be tracked as separate initiatives.

## Definition of Done

- [X] Repos for core documentation are identified (`va.gov-team` and `va.gov-team-sensitive`)
- [X] User-centered IA is defined and structure is implemented within the appropriate repos
- [X] Content in legacy repos (primarily `vets.gov-team` and `va.gov-vfs-teams`) has been audited with content owners to identify crucial documentation that needs to be migrated/copied
- [x] Crucial non-sensitive documentation from legacy repos, as audited, is copied to `va.gov-team` GitHub repository.
- [x] Crucial sensitive documentation from legacy repos, as audited, is copied to `va.gov-team-sensitive`
- [x] Content in legacy repos that has been copied is marked at deprecated in the legacy repo, with historical content left in place.
- [x] All links to legacy repos that exist within `va.gov-team` and `va.gov-team-sensitive` repos are updated with either: a link to the appropriate content in the `va.gov-team` repo, or a note that the content referenced does not exist in the `va.gov-team` repo.
- [X] "Shut down" plan for legacy repos — primarily `vets.gov-team` — is defined
- [x] "Shut down" plan for legacy repos is executed

**Comment by meganhkelley** [comment]
Converting this to a super epic.

**Comment by meganhkelley** [comment]
`vets.gov-team` and `va.gov-vfs-teams` have not been archived, but write access has been removed. We will separately track shutting down and archiving `vets.gov-team` and `va.gov-vfs-teams` as needed as part of this item in our backlog: #3379
