### ISSUE TITLE
[Design] Wireframe when veteran answers "no" to demo question

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#53829]
## Description 

How might we include information about travel (as a second priority) when a Veteran answers "no" to a demo question? 

[Travel user flow](https://app.mural.co/t/vfscie8528/m/vfscie8528/1667222840454/ada0c417b71c922895f1750cd32d869f6213e129?sender=u83bc52d7fa73658f84f27755)

Current branch has the following ux (which includes a link about travel that goes to VA.gov resources page): 

![Screen Shot 2023-02-21 at 10.35.28 AM.png](https://images.zenhubusercontent.com/62264cddfdd7546d65710eff/3a808944-a626-4c1b-9fcf-6d3257869030)

## Tasks

- [ ] Create wireframe
- [ ] Review with team 
- [ ] Review with sitewide content and IA, if needed

## AC

- [ ] Wireframe completed
- [ ] Team has reviewed and validated
- [ ] Ensure ticket is created for next step
