### ISSUE TITLE
Support: Mon-Thur Deploy (S22)

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#53823]
## User Stories
As a Platform team member who just contributed to the Platform website,
I need my content published,
so that I can share my content updates with the intended audience.

As a content team,
we need to review any new content changes made on the platform,
so that we can deploy every Tuesday and Thursday of the week.

## Tasks
Someone from our team will use Scroll Viewport to publish changes to the website after 3pm EST on:

- [x] Wednesday (3/1) - Samara
- [x] Thursday (3/2) - Lauren (swap with Jill from last sprint)
- [x] Monday (3/6) - Lauren
- [x] Tuesday (3/7) - Brian
- [x] Wednesday (3/8) - Samara
- [x] Thursday (3/9) - Jill
- [x] Monday (3/13) - Lauren
- [x] Tuesday (3/14) - Brian

## Acceptance Criteria

- [x] The Platform website will be deployed Monday-Thursday between 3:30 and 5pm for this sprint.
- [x] Any edits with launch-blocking issues will be announced to their content editors via #platform-content

## Other Info
Rotating schedule:
https://vfs.atlassian.net/wiki/spaces/CIT/pages/2405171201/Deployment+rotation+schedule

Data tracking info:
https://vfs.atlassian.net/wiki/spaces/CIT/pages/2282979860/KPIs+-+Content+Support
