### ISSUE TITLE
Content Tip for Sprint 22

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#53826]
## Purpose
The Content team provides a new "content tip" every sprint with the #platform-content channel's audience. The purpose of this is to provide continuous style guidance and re-enforce content best practices for contributors of the Platform website.

## Tasks

- [x] Pick a content tip idea from the style guide

- [x] Draft a content tip Slack post, similar to the first one posted on Thurs, Jan 5: https://dsva.slack.com/archives/CL181NRJQ/p1672938003050849

- [x] If needed, get feedback from rest of Content team

- [x] Copy and paste the team-approved announcement of our Tip of the Sprint in to the platform-content slack channel.

- [x] Schedule for first Monday of the sprint at 1pm ET

## Acceptance Criteria

- [x] A new content tip will be posted on #platform-content for this sprint.

## Other Info

Reminder: Add a line to engage with the post if they find the tip helpful.

**Comment by vbellissimo** [comment]
**Ideas for this sprint:**
- How to reference acronyms
- Re-surface the Word List from our style guide
