### ISSUE TITLE
Next steps to update website footer form

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#53831]
## Issue Description
Jill has found a way to update the website's footer form template in Github: https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=vbellissimo%2C+ssimmorins%2C+amygoldman&labels=documentation-support%2C+pw-footer-feedback&template=platform-website-footer-feedback.md&title=

We need to add a question that asks the customer if they are a VFS or Platform team member.

The value of adding this additional question to the form is for Platform Content team members to more easily identify the customer type. If they are part of Leadership or a VFS team, we need to know so we can reach out to a Platform SME to align with any changes made to the content of the website.

**Proposed question:**
Which type of team are you in? (Platform team, VFS team or Leadership)

## Tasks

- [x] Add a new "heading" to the form to provide new question.

- [x] Submit a test entry from any of the website footer from any of the pages' footer such as: https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/getting-started-with-platform-analytics-insights
1. If successful, let the team know.
2. If not successful, revert the form back to it's original state.

## Acceptance Criteria

- [x] The intake form will have a new question that will allow the Platform Content team easily determine whether the request is from a VFS team, Platform team or Leadership.

**Comment by taylojill** [comment]
3/8/2023 - Added new heading for question: Which type of team are you on? (Platform team, VFS team, or Leadership)
