### ISSUE TITLE
Update content in R&S and education hub to support launch of online enrollment verification tool

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#53848]
## Issue Description

With the launch of the new enrollment verification tool, we need to update content on our pages about enrollment verification for Post-9/11 GI Bill recipients. 

One page we know needs changing is the [GI Bill WAVE FAQs](https://www.va.gov/resources/gi-bill-wave-faqs/) in R&S.

We also need to audit the rest of R&S education articles and the education hub for any other pages that need updating.

## Tasks
- [x] Update WAVE R&S article (Katherine)
- [x] Audit for other pages to correct (Katherine)
- [x] Update other pages (Katherine)
- [x] OCTO review (Beth)
- [ ] Send to stakeholders for approval (Katherine)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Live pages are updated with info about new tool

**Comment by RLHecht** [comment]
@katherine-fung Since we want to publish this page (and others with that we find) when we launch the tool, we'll want to bring this ticket into this sprint. Could you please add an estimate to it (2, 4, or 8, etc.) before you start working on it? Thanks!

**Comment by katherine-fung** [comment]
Sure, I put a 4 on it @RLHecht

**Comment by katherine-fung** [comment]
Quick update: 

I'd like to check with Mikki about what we're doing with the GI Bill WAVE page. 

I audited the Resources and Support pages and found 1 more page to update so far: 

https://www.va.gov/resources/what-if-my-school-closes-temporarily-because-of-a-natural-disaster/

**Comment by katherine-fung** [comment]
I've updated this page: 

https://www.va.gov/resources/what-if-my-school-closes-temporarily-because-of-a-natural-disaster/

**Comment by bethpottsVADEPO** [comment]
@katherine-fung Wanted to comment on this first one now so you can reach out to SMEs. I'm considering the other pages, but just didn't want to hold you up!
**What if my school closes temporarily because of a natural disaster?**
http://preview-prod.vfs.va.gov/preview?nodeId=14968
Based on ongoing feedback we've gotten from SMEs, they want to deemphasize the phone number, right? So I think for the Montgomery GI Bill bullet, you'll want to point the user to WAVE first, using our purpose and target accessibility standard for the text link. And this raises the question of whether the SMEs even want to provide the option of calling to verify. If they do, we should add that to the new enrollment verification page that's about to launch. If they don't, then remove that as an option for MGIB from this natural disaster R&S page. Would you check with the SME on this point?

**Comment by bethpottsVADEPO** [comment]
@katherine-fung As you suggested in slack, let's remove the second chunk of bullets for the info about "continue to verify your enrollment each month" and just crosslink over to our new static tool page for enrollment verification:

- Change the colon to a period for this line: "To keep getting payments while your school is closed..."
- Add this link text: Verify school enrollment for GI Bill benefits

Once we have the separate R&S article published for DEA enrollment verification, please add that link here too. For now, let's leave off the "Note" but add it back in when you add the DEA link.

**Comment by bethpottsVADEPO** [comment]
@katherine-fung I edited the single Q&A and the WAVE FAQ. You can check out what I did. 

The text and link on the Post-9/11 GI Bill page look great. Would you make that a jump link so we can send users right to the "For Post-9/11 GI Bill benefits" H2 on the Verify school enrollment for GI Bill benefits page? Thanks!

**Comment by katherine-fung** [comment]
Thank you @bethpottsVADEPO! 

The single and multiple FAQ look great. 

I updated the natural disaster R&S page. Since we're taking out that chunk of information, we're also removing the phone number for verifying MGIB, so there's no need to re-arrange that information. 

I updated the link on the Post-9/11 GI Bill page. Since the verification requirement hasn't changed since Sept 2021, I removed the alert. The information about who has to verify is now in the new note. 

@megzehn - 

these pages are ready for copy edit: 

What if my school closes temporarily because of a natural disaster?
http://preview-prod.vfs.va.gov/preview?nodeId=14968
2a. single FAQ - How do I verify my enrollment?
http://preview-prod.vfs.va.gov/preview?nodeId=16481

2b. multiple FAQ - GI Bill WAVE FAQs
http://preview-prod.vfs.va.gov/preview?nodeId=16484
(The changes in the multiple FAQ aren't showing in preview, but they show up in edit mode)

3. Post-9/11 GI Bill page:
http://preview-prod.vfs.va.gov/preview?nodeId=935

**Comment by katherine-fung** [comment]
I'm working on 1 more page to update: http://preview-prod.vfs.va.gov/preview?nodeId=937 

I just sent the changes to Tammy to sign off on, and will update the ticket when I hear back.

**Comment by katherine-fung** [comment]
Hi @megzehn - 

There's 1 more page to copy edit. Tammy, the stakeholder, signed off on the changes.  

After you apply for education benefits 
http://preview-prod.vfs.va.gov/preview?nodeId=937

Thank you!

**Comment by katherine-fung** [comment]
Hi @megzehn, I'm sorry - I updated 2 more pages that are ready for copy edit. I added links to the download letter tool to both of these. I also changed the language to say "education decision letter" or "decision letter" instead of "Certificate of Eligibility" or "COE," which education stakeholders confirmed we should do. 

"Can I get a copy of my education decision letter?"
http://preview-prod.vfs.va.gov/preview?nodeId=14971 

"Post-9/11 GI Bill Statement of Benefits"
http://preview-prod.vfs.va.gov/preview?nodeId=3007

**Comment by megzehn** [comment]
Thanks, @katherine-fung! I'm going to check off this list as I go: 

COPY EDITED

- [ ] What if my school closes temporarily because of a natural disaster?
http://preview-prod.vfs.va.gov/preview?nodeId=14968

- [ ] How do I verify my enrollment?
http://preview-prod.vfs.va.gov/preview?nodeId=16481

- [ ] multiple FAQ - GI Bill WAVE FAQs
http://preview-prod.vfs.va.gov/preview?nodeId=16484

- [ ] Post-9/11 GI Bill page:
http://preview-prod.vfs.va.gov/preview?nodeId=935

- [ ] After you apply for education benefits
http://preview-prod.vfs.va.gov/preview?nodeId=937

- [ ] Can I get a copy of my education decision letter? -
http://preview-prod.vfs.va.gov/preview?nodeId=14971

- [ ] Post-9/11 GI Bill Statement of Benefits
http://preview-prod.vfs.va.gov/preview?nodeId=3007


PUBLISHED (for when tool is fixed)

- [ ] What if my school closes temporarily because of a natural disaster?
http://preview-prod.vfs.va.gov/preview?nodeId=14968

- [ ] How do I verify my enrollment?
http://preview-prod.vfs.va.gov/preview?nodeId=16481

- [ ] multiple FAQ - GI Bill WAVE FAQs
http://preview-prod.vfs.va.gov/preview?nodeId=16484

- [ ] Post-9/11 GI Bill page:
http://preview-prod.vfs.va.gov/preview?nodeId=935

- [ ] After you apply for education benefits
http://preview-prod.vfs.va.gov/preview?nodeId=937

- [ ] Can I get a copy of my education decision letter? -
http://preview-prod.vfs.va.gov/preview?nodeId=14971

- [ ] Post-9/11 GI Bill Statement of Benefits
http://preview-prod.vfs.va.gov/preview?nodeId=3007

**Comment by megzehn** [comment]
@RLHecht these are all published and ready for you to validate! ^

Thanks so much @katherine-fung for getting them ready!

**Comment by RLHecht** [comment]
Changes are live. Closing ticket!
