### ISSUE TITLE
Create lighthouse Pundit policy

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#53840]
## Background
We need to create a new Pundit policy for Lighthouse claims. We use Pundit to determine who should be able to access resources in vets-api. In order to access Lighthouse Benefits Claims the current user needs to have both an ICN and a Participant ID.

## Context
We can use Pundit for both vets-api and vets-website. In vets-api we can restrict access to certain controllers / services based by specifying policies. On the frontend, we retrieve the list of backend services that a user has access to when they login, so we can also restrict access in that way

## Tasks
- [x] Create lighthouse Pundit policy (BE)
- [x] Update Backend services (BE/FE)
- [x] Update rails specs to reflect changes made (BE)

## Acceptance Criteria
- [x] Lighthouse policy has been created
- [x] The call to backend_services includes the `LIGHTHOUSE_CLAIMS` service when appropriate
- [x] vets-website is able to restrict calls based on the new policy
