### ISSUE TITLE
[FE] Extend short URL expiration dates to one week after day of appointment 

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#53845]
## Background

As discussed in ToT Feb 16, we want to extend the short URL expiration date to improve the Veteran experience when clicking on links that are a few days old.

## Tasks
- [x] Submit PR for VEText for pre-check-in
- [x] Submit PR for CHIP for check-in
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] All short URLs are valid for one week after the appointment date
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by acrollet** [comment]
VEText PR: https://github.com/department-of-veterans-affairs/vetext/pull/413

**Comment by acrollet** [comment]
CHIP PR: https://github.com/department-of-veterans-affairs/chip/pull/1633

**Comment by acrollet** [comment]
The VEText update was deployed last night: https://dsva.slack.com/archives/C03E5FEBTLH/p1677155439716459?thread_ts=1677113079.716759&cid=C03E5FEBTLH

**Comment by acrollet** [comment]
The PCI API team has [completed staging QA](https://app.zenhub.com/workspaces/pci-api-6149f6401b0b3c001219802f/issues/gh/department-of-veterans-affairs/chip/1631) and this should go out with the next CHIP release.

**Comment by acrollet** [comment]
CHIP release is [planned for this afternoon](https://dsva.slack.com/archives/C03E5FEBTLH/p1677609111504439)

**Comment by acrollet** [comment]
### day-of expiration validation

- searched CHIP logs for a check-in and found [this log](https://tevi.ddog-gov.com/logs?query=service%3Achip%20functionname%3Aproject-chipapi-shortenurl-prod%20%20%40lambda.request_id%3Af0e3e735-64f3-4644-8063-725de5eee83c&cols=host%2Cservice%2C%40lorotaUuid&event=AQAAAYajRptl0VTlQwAAAABBWWFqUnF1VEFBQ1lsYkhMZjJhTmpnQVk&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1677764085701&to_ts=1677778485701&live=true) with short url https://www.va.gov/c/ij8knUt
- looked up the associated UUID and found that the appointment was for the morning of 03/02 (central time)
- looked up the associated short url record and found that its expiration date is `1678427999`, which corresponds to `Thu Mar 09 2023 23:59:59 GMT-0700 (Central Standard Time)`

The expiration is at midnight a week after the appointment, so this passes.

**Comment by acrollet** [comment]
closing as complete.
