### ISSUE TITLE
Research device types and capabilities of Va.gov users

### ISSUE THREAD

**Issue by APorter-Clarity** [department-of-veterans-affairs/va.gov-team#53876]
- What are the majority of device types and capabilities that Veterans are using to access va.gov

- This required datadog or google analytics. 

- Peer with Joe for DD and peer with Alex for GA

**Artifacts**
- [Analytics.us.gov's public analytics dashboard for VA](https://analytics.usa.gov/veterans-affairs/)
- [VA's public analytics dashboard](https://digital.va.gov/va-website-analytics/)
- [Spreed sheet: Users by LOA and Mobile Device | GA](https://docs.google.com/spreadsheets/d/1a2Mof8xBM3G12DO1fRzfn8-uYfslRxXqhl_WBS3Pbd0/edit?usp=sharing)
- [Spreed sheet: DataDog Verified User Flow - Device Analytics](https://docs.google.com/spreadsheets/d/1NsuhYhLJBdf9LnaJe2fEWzz1hxzsRbSRBoAy0XSkA7I/edit?usp=sharing)
- [Findings from VA mobile device login analytics](https://docs.google.com/document/d/1TgPrAQH_q1C7CM_74v0N_Qb9ieOHB_igPh_Qkocfk0o/edit?usp=sharing)

**Tasks**
- [x] decide what data is needed
   - Device type
   - Browser
   - OS
   - screen size/browser size
   - Do users with certain browsers fail more often at successfully verifying their account?
      - browser type + verification success metrics
   - Do users with certain devices fail more often at successfully verifying their account?
      - device type + verification success metrics
   - Do unverified users tend to have a specific device or browser
      - LOA1 vs LOA3 and x device
- [x] connect with Joe to get understanding of and help with DD
- [x] connect with Alex to get GA analytics data and Sentry data
- [x] add camera data to LOA3 vs 1 device data
   - [x] analyze for any significant findings
   - [x] Specific Q: are there a significant number of users on devices with less than 8 MP camera sensor ([min required by LI.G](https://www.login.gov/help/verify-your-identity/how-to-add-images-of-your-state-issued-id/#:~:text=8%20megapixel%20or%20higher)
- [x] decide which analytics source makes the most sense for the data needed
- [x] if needed, get proper access to, DD, GA, Sentry
- [x] if needed, set up dashboard(s)
- [x] draft findings document
- [x] peer review
- [x] make updates based on feedback, and copy to GH
- [ ] send out to team

**Comment by claytonzook** [comment]
@APorter-Clarity Ready for review on the [findings doc](https://docs.google.com/document/d/1TgPrAQH_q1C7CM_74v0N_Qb9ieOHB_igPh_Qkocfk0o/edit?usp=sharing) for this. Once good, I'll transfer this over to GH for ease of linking/sharing

**Comment by claytonzook** [comment]
Making updates and revisions based on review discussions from March 8
