### ISSUE TITLE
External Connections - Review Controls and Resolve Outstanding POA&Ms

### ISSUE THREAD

**Issue by gary-fallon** [department-of-veterans-affairs/va.gov-team#53885]
## Description
ACTION REQUIRED: Completion of new required field in eMASS and review of External Connections controls.

![image.png](https://images.zenhubusercontent.com/6123becac1cf6c603d1eeecd/7a100f4b-f6cc-477f-aa43-6ba8eb7d373e)

![image.png](https://images.zenhubusercontent.com/6123becac1cf6c603d1eeecd/f610c787-bb54-4e28-b519-8b97a86c747b)

![image.png](https://images.zenhubusercontent.com/6123becac1cf6c603d1eeecd/1f92bc58-1eaf-4dec-8c53-11edb4d2c16f)

![image.png](https://images.zenhubusercontent.com/6123becac1cf6c603d1eeecd/a867621c-8772-4e44-9650-cd01f604c50d)

![image.png](https://images.zenhubusercontent.com/6123becac1cf6c603d1eeecd/4b82a7e6-957a-458c-922c-805945fba9b9)

## Documentation
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/artifacts/ATO/2023/artifacts

## Tasks
The following tasks must be reviewed and completed as necessary.
- [x] Create POA&M for non-compliant external connections.
- [ ] Review the external connections controls listing (below) and resolve outstanding POA&Ms.

## Controls (CCIs)
The following controls must be implemented for each external connection. If any controls cannot be implemented, a POA&M must be opened.

- [ ] **AC-4.2**: The information system enforces approved authorizations for controlling the flow of information between interconnected systems based on organization-defined information flow control policies.
- [ ] **AC-20(1).1**: The organization permits authorized individuals to use an external information system to access the information system only when the organization verifies the implementation of required security controls on the external system as specified in the organization's information security policy and security plan.
- [ ] **AU-2.1**: The organization determines the information system must be capable of auditing an organization-defined list of auditable events.
- [ ] **AU-2.3**: The organization coordinates the security audit function with other organizational entities requiring audit-related information to enhance mutual support and to help guide the selection of auditable events.
- [ ] **AU-3.1**: The information system generates audit records containing information that establishes what type of event occurred.
- [ ] **AU-3.2**: The information system generates audit records containing information that establishes when an event occurred.
- [ ] **AU-3.3**: The information system generates audit records containing information that establishes where the event occurred.
- [ ] **AU-3.4**: The information system generates audit records containing information that establishes the source of the event.
- [ ] **CA-3.3**: The organization documents, for each interconnection, the security requirements.
- [ ] **CA-3.4**: The organization documents, for each interconnection, the nature of the information communicated.
- [ ] **CA-3.5**: The organization reviews and updates Interconnection Security Agreements on an organization-defined frequency.
- [ ] **CM-6.2**: The organization establishes configuration settings for information technology products employed within the information system using organization-defined security configuration checklists.
- [ ] **CM-7(1).1**: The organization reviews the information system per organization defined frequency to identify unnecessary and nonsecure functions, ports, protocols, and services.
- [ ] **CM-7(1).3**: The organization defines the functions, ports, protocols and services within the information system that are to be disabled when deemed unnecessary and/or nonsecure.
- [ ] **CM-7(1).4**: The organization disables organization-defined functions, ports, protocols, and services within the information system deemed to be unnecessary and/or nonsecure.
- [ ] **RA-5.1**: The organization scans for vulnerabilities in the information system and hosted applications on an organization-defined frequency.

## Acceptance
The following tasks must be completed by the System Steward (@fowusu2)  no later than 3/10/2023 before this issue can be considered done.
- [ ] If your system has any of the CCIs marked as non-Compliant and has a Plan of Action & Milestone (POA&M) current in place ensure that the control is implemented and that the POA&M is closed by no later than 3/31/2023.

**Comment by gary-fallon** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Security-615c86f78b52bf0014e79606/issues/department-of-veterans-affairs/va.gov-team/53885?planning-poker) with Zenhub @little-oddball

**Comment by fowusu2** [comment]
@gary-fallon There are no external connection lists or MOU/ISAs in emass. The answer to whether va.gov has an external connection with any third-party outside va  has been left BLANK in emass over the years until now that is has become a mandatory field to complete for all systems.

**Comment by alyssagallion** [comment]
@jhouse-solvd Over to you!

**Comment by alyssagallion** [comment]
@jhouse-solvd I know. you are working on this already but could you provide any updates on this issue directly? That'll help me prioritize which things need following up on!

**Comment by fowusu2** [comment]
I will be discussing with Gary to create a POAM for the controls above  since the external connection task is not completed yet

**Comment by jhouse-solvd** [comment]
@alyssagallion - _Sorry for not commenting sooner_ 

I'm working on updating the external connections diagram today. Joe and Gary have been helpful in [verifying and clarifying info for the diagram](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53111#issuecomment-1460708860). I'll have an updated version of it to share by EOD. 

Gary is putting together an inventory of external connections, related administrative info, and the adherence of those connections w/ various controls. Gary and I discussed the documentation needed for each external connection to ensure compliance with ATO requirements. 

Although many details regarding external connections are readily available, additional time is needed to verify info and update documentation and supporting diagrams with anything that needs clarification. Per Faith's comment above, she is working with Gary to put together a plan of action, as we will only have some of the documentation together in time for the 3/10 deadline. 

I still need clarification on how the POAM submission influences the ETA for this specific issue. I'm hoping Gary and Faith can provide some clarity there. Also, it might be helpful to break this issue into sub-tasks based on the different pieces needed. 

Please feel free to let me know if you need any other information at this time. I'm happy to help!

**Comment by gary-fallon** [comment]
@jhouse-solvd thank you. The POA&M does not change the need for this effort to be completed by 3/10. Yours is only part of a larger initiative that is blocked, but the diagram will be invaluable and help inform future decisions.

**Comment by jhouse-solvd** [comment]
Please see [my comments on #53111](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53111#issuecomment-1462971369) for the most recent updates to the external connections diagram. 

I've requested Gary's feedback so that we can refine the information presented :)

**Comment by jhouse-solvd** [comment]
Update 3/13: 

I'm meeting w/ @gary-fallon later today to review the most recent version of the external connections diagram. And I've scheduled time for tomorrow morning to review the diagram w/ Lindsey Hattamer, a maintainer of Vets-API familiar with external integrations. 

I plan to have additional information to share after meeting w/ Gary and Lindsey.

**Comment by gary-fallon** [comment]
X-Post

@jhouse-solvd can you please share whatever diagrams you are currently working on?

I will be drafting the BIA and ISCP based on a new definition of the FISMA authorization boundary that includes all VFS applications.

I'll unassign this issue for now and follow up if I have questions. Thank you!

**Comment by jhouse-solvd** [comment]
[X-Post for awareness](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53111#issuecomment-1478519677) _- this comment contains a link to a conversation in Slack with updated diagrams._

**Comment by gary-fallon** [comment]
I started comparing external connections in Grafana to External Connections spreadsheet.

https://grafana.vfs.va.gov/d/pEgVdRlZk/external-service-performance-indicators?orgId=1

**Comment by gary-fallon** [comment]
I am working on getting these connections updated, but the progress is slow because there are several data sources to consider.

**Comment by gary-fallon** [comment]
I am still researching connections, but this is blocked until we receive a leadership decision on minor applications.

**Comment by alyssagallion** [comment]
Ray Wang is reviewing the Minor Applications document here: https://vfs.atlassian.net/wiki/spaces/PSEC/pages/2578153732/2023-03-27+-+VFSP-Va.gov+Minor+Applications

We have reiterated that this is in his court both on our PO sync and via Slack as a follow up. @jwoodman5 will also remind Ray on his 1:1 with him on Friday, April 14, 2023.

**Comment by jwoodman5** [comment]
@alyssagallion Did you get the feedback needed here?

**Comment by gary-fallon** [comment]
@jhouse-solvd 

We have a list of external connections that were added to the SSP in February. Additionally, all of the aforementioned CCIs will need to be updated this month regardless, and the required POA&M closure date has passed.

Is there an open POA&M for this issue? I don't see one linked anywhere, but I may have missed it.

If there isn't an open POA&M, can this issue be closed?
