### ISSUE TITLE
[Content] Audit and update Need Help content

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#53883]
## Description 

How might we need to update the Need Help content across all wireframes to align with the unified experience? For example: 

No more use of "pre-check-in" 
Shifting to "confirm your appointment" (e.g., being consistent with content that we choose for headings, body, etc.) 

## Tasks

- [x] Create final Need Help content for each wireframe (or scenario). For example, some will need to change, while other content will not. 
- [x] Ensure designers have new content

## AC

- [x] Need Help content is documented for each wireframe (or scenario) 
- [x] Designers have access to new content

**Comment by kellysmith1008** [comment]
[Started the audit of existing help content](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677508200929/3b34ae8fe52c1618e8a60a30f2a1923db589d3bf?sender=u5d970cc175b184392a004997). Will affinitize and create new mockups from scenarios types to share among team

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 I took a stab at a rough draft suggestion for the text and order. Could you let me know what you think?

**Comment by benbrasso-agile6** [comment]
Sure thing. Will take a look tomorrow.

**Comment by kellysmith1008** [comment]
[Created a sketch mockup](https://www.sketch.com/s/c641634f-c318-4d4d-ae7c-2b353fc1a5e6) of my preferred one -will add others if updates are needed. Will share sketch file with designers to bring into abstract when done.

**Comment by benbrasso-agile6** [comment]
Looks great. Yep, go ahead and add it directly in the sketch file that we're working on.

**Comment by kellysmith1008** [comment]
Added it to [the sketch file](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec#About) and tagged Christina in the file for awareness
