### ISSUE TITLE
Add MVI/MPI outage errors to AuthApp

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#53888]
## Description
There is an error message that is recorded in Sentry stating that there is an MPI/MVI outage as described in this [Slack thread](https://dsva.slack.com/archives/C04LW2P19M0/p1676580859689359).  We want the ability to tell users if there is an outage in MPI/MVI with an error message rather than the generic `007`

## Tasks
- [ ] Add an error code (TBD by BE) to the AuthApp page
  - [ ] Use the MVI/MPI outage messaging in the the DowntimeBanner component to display in the `authentication/errors.js` page
  - [ ] Update associated unit tests to ensure the MPI/MVI outage error screen displays as appropriate

**Comment by aparsley** [comment]
@bramleyjl can you speak on this?

**Comment by asg5704** [comment]
@aparsley This is a two-pronged process, the BE needs to create the code + logic and the FE needs to add the code + logic to render the error.
