### ISSUE TITLE
Assess and update nav instances of "check your claim or appeal status" to include decision reviews

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#53907]
## Issue Description

Although we've changed using "appeals" to using "decision reviews," this isn't reflected in the [Check your VA claim or appeal status](https://www.va.gov/claim-or-appeal-status/) H1 and we don't use "decision reviews" in the links in the top and left navs for that page. 

We need to look at each of the hubs and decide what the left nav and top nav labels should be and if we should look into changing the H1 of the page. If we change the labels to add "decision reviews" is it a confusing user experience to not have "decision reviews" mentioned on the page itself?

## Tasks
- [x] Assess 
- [x] Update left nav instances
- [x] Update top nav instances

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

**Comment by bethpottsVADEPO** [comment]
@mnorthuis Since we're turning to this work now, I wanted to get your input on mega menu and left nav labels.

**Comment by mnorthuis** [comment]
An IA can pick this up when they are available.  Initial work will be to review all placements/references within the top and left nav so we can determine what makes sense to update.

**Comment by kristinoletmuskat** [comment]
FYI I've started documenting existing instances of Appeals in Navs here: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683319832444/c0c8b36f9ab0004fa156ac36e54295918124c85c?sender=ua641db233dc545173f8d9816

**Comment by kristinoletmuskat** [comment]
Hi @bethpottsVADEPO, I've documented all of the link label discrepancies in navigation across the site in this spreadsheet: https://docs.google.com/spreadsheets/d/15I1-UFygQ44EAypHrq68k27Fo2Jhb0hFTMnSLpRPThk/edit#gid=0

Let me know if you have trouble accessing, or any questions.

**Comment by bethpottsVADEPO** [comment]
Thanks @kristinoletmuskat! You can work with @katherine-fung if you need content input as you implement.

**Comment by kristinoletmuskat** [comment]
Update: we synced with @katherine-fung today and she's going to check with content about our recommendation for the left nav.

**Comment by jennymayoco** [comment]
Following up here that we've connected with Content about our recommendation for the left nav and have decided to move forward with using

>  Check claim, decision review, or appeal status

 to avoid splitting 'decision review'. Here's a screengrab of how it looks with "your" and without that Megan shared with us.

![image](https://images.zenhubusercontent.com/63c83028c6610cceebc89916/fedd3f9a-5cbe-4fdf-8d63-7440e9f6f1eb)

Megan also gave Kristin and I a walkthrough on how to make edits in Drupal. @katherine-fung @bethpottsVADEPO are we okay to move forward with updating the nav items?

**Comment by bethpottsVADEPO** [comment]
@jennymayoco Yes! Please move forward with those nav changes. Many thanks.

**Comment by jennymayoco** [comment]
Quick update on this - I have updated the link label text in the benefit hub pages to "Check your claim, decision review, or appeal status" and shared with @megzehn as drafts for for review. The hub pages I made changes to are:

- Health
- Disability
- Education
- Careers and employment
- Pension
- Housing
- Life insurance

**Comment by jennymayoco** [comment]
Updating to in progress because we have access to edit menus now

**Comment by kristinoletmuskat** [comment]
Confirmed with @katherine-fung that the changes are pretty standard, nothing surprising for stakeholders, so we don't need to run this by them. @bethpotts FYI! I might get to this next week or the week after.

**Comment by jennymayoco** [comment]
Made the following changes to the megamenu:

- **Disability**: updated link label from `Check your claim or appeal status` to `Check your claim, decision review, or appeal status`
- **Pension**: updated link label from `Check your claim or appeal status` to `Check your claim, decision review, or appeal status`
- **Housing**: updated link label from `Check your SAH claim status` to `Check your claim, decision review, or appeal status`
- **Life Insurance**: updated link label from `Check your appeal status` to `Check your claim, decision review, or appeal status`

**Comment by jennymayoco** [comment]
#### Made the following changes to the left nav:
- Healthcare
    - Updated link label from `Check appeal status` to `Check your claim, decision review, or appeal status`
    - Updated link label from `Request a decision review or appeal` to `Request a decision review`
- Disability
    - Updated link label from `Check claim or appeal status` to `Check your claim, decision review, or appeal status`
    - Updated link label from `Request a decision review or appeal` to `Request a decision review` 
- Education
    - Updated link label from `Check VA appeal status` to `Check your claim, decision review, or appeal status`
    - Updated link label from `Request a decision review or appeal` to `Request a decision review` 
- Careers and Employment
    - Updated link label from `Check your VA claim status` to `Check your claim, decision review, or appeal status`
    - Updated link label from `Request a decision review or appeal` to `Request a decision review`
    - Changed order so link to `check decision review` is above `request`
- Pension
    - Updated link label from `Check claim or appeal status` to `Check your claim, decision review, or appeal status`
    - Updated link label from `Request a decision review or appeal` to `Request a decision review`
- Housing
    - Updated link label from `Check appeal status` to `Check your claim, decision review, or appeal status` under both sections "VA-backed home loans" and "Housing grants"
    - Updated link label from `Request a decision review or appeal` to `Request a decision review`
- Life Insurance
    - Updated link label from `Check appeal status` to `Check your claim, decision review, or appeal status`
    - Updated link label from `Request a decision review or appeal` to `Request a decision review`

#### Notes
- @megzehn noting that there were a couple of pages where the link node was `base:claim-or-appeal-status`. The two times I came across it were when I updated the Healthcare left nav - `Check your claim, decision review, or appeal status` and Pension left nav - `Check your claim, decision review, or appeal status`
- I also removed the second link under "Manage your pension benefits" in the Pension hub page and submitted as a draft for your review @megzehn
<img width="400" alt="image1" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/122128479/46162e70-7190-4cd3-9c88-3175579c1c2a">

**Comment by jennymayoco** [comment]
[Slack convo](https://dsva.slack.com/archives/C52CL1PKQ/p1697741089411279) with PW team to see how we can proceed to updating the homepage link label for the decision reviews page

**Comment by jennymayoco** [comment]
Homepage link label is now live! I updated final statuses in the [doc we we were using to track changes](https://docs.google.com/spreadsheets/d/15I1-UFygQ44EAypHrq68k27Fo2Jhb0hFTMnSLpRPThk/edit#gid=1716330285). Moving this ticket to validate

<image width="800" alt="Image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/122128479/76a3b3e2-42b4-4906-bc83-d09ab06ca485">

**Comment by megzehn** [comment]
Thanks so much, @jennymayoco!!

Confirming that I reviewed the hub landing page changes and published them for consistency with the left nav. 

@jennymayoco thank you also for catching and flagging the double link on the pension hub page!

**Comment by RLHecht** [comment]
Hi all! I just noticed a link we need to update on our [COVID FAQs page](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/) (in the "Helpful online tools" section). Did this audit include all instances or were we only looking at the hub landing pages? If it was only for the hub landing pages, should we set up a new ticket to make sure we capture all links?

**Comment by jennymayoco** [comment]
Hi @RLHecht, thanks for catching this and flagging. This work was focused on nav items and hub landing pages, but I think it's worth capturing all instances! Happy to set up a ticket for this

cc @kristinoletmuskat

**Comment by kristinoletmuskat** [comment]
Hey @jennymayoco @RLHecht, that's a great flag that we should also be updating links across the site. I think IA owns left navs, mega menu, and hub page changes, and content still owns all of the page-level changes. So I think we would need to create a backlog ticket for that @l-sinreich -- I can add this to hive mind today to discuss.

**Comment by l-sinreich** [comment]
@kristinoletmuskat let me know if there's a follow up for this with the Decision Reviews team and I can point you to the appropriate person.

**Comment by kristinoletmuskat** [comment]
Whoops @l-sinreich I tagged the wrong person! Meant to tag @strelichl !
