### ISSUE TITLE
[BE] Call refresh_precheckin after auth in precheckin scenarios

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#53903]
During precheckin, vets-api calls refresh_precheckin in SessionsController#get, which means if someone puts any 
valid but random UUID in this URL: https://staging.va.gov/health-care/appointment-pre-check-in/?id=61bd5edc-64b1-4cc6-9a19-762f195e2abc, it will call refresh_precheckin CHIP endpoints unnecessarily. 

We should remediate this to call refresh_precheckin only after auth

## Tasks
- [ ] [BE] Call refresh_precheckin after auth
- [ ] [BE] Update sequence diagrams

## Acceptance Criteria
- [ ] Deployed to prod

**Comment by loripusey** [comment]
too old, closing
