### ISSUE TITLE
Create react widget content for Specially Adapted Housing (Form 26-4555)

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#53915]
## Issue Description

When the Specially Adapted Housing digital form launches, the product team will first do it incrementally so only 25% of users see a link to it. Because of this, we'll need to create a react widget on the page with two different types of text:
1. What 75% of users will see (no link to the online form)
2. What 25% of users will see (a link to the online form)

We need to give the product team the content for them to build the react widget. We'll then add the widget to the page in a new ticket. 

## Tasks
- [ ] Create content for widget 
- [ ] Copyedit (Megan)
- [ ] Provide content to product team in intake request #53077

## Acceptance Criteria
- [ ] Product team has final content for react widget

**Comment by RLHecht** [comment]
@laurwill Here's draft content of the react widget for the SAH form. Can you review?

[https://app.zenhub.com/files/133843125/079e2106-8496-4e2b-be13-5472e3e398fe/download](https://app.zenhub.com/files/133843125/079e2106-8496-4e2b-be13-5472e3e398fe/download)

**Comment by megzehn** [comment]
Thanks for making that change, @laurwill! 

Attached is the copy edited version. I updated the action link URL after IA team confirmed we need "form" in it.  [As reflected in the updated IA specs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/housing-grants-application.md), the CTA URL should be:    /housing-assistance/disability-housing-grants/apply-for-grant-form-26-4555

[copy edited version of react widget copy for housing grant](https://app.zenhub.com/files/133843125/1bf5d11f-31f8-47de-a7f5-1beb17717c04/download)

**Comment by RLHecht** [comment]
Thanks! Closing this. Actual: 2.
