### ISSUE TITLE
Remove content about creating DS Logon accounts

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#53924]
## Issue Description
VA.gov is retiring DS Logon access. The identity team wants us to remove Drupal content that encourages Veterans to create new DS Logon accounts, since they will stop working on VA.gov soon.

Communication about DS Logon phase out will start in May. DS Logon will stop working on VA.gov in September.

| Page | Suggested changes | Suggested timing |
|:----------|:-----------|:----------|
|[How to get a Premium DS Logon account online](https://www.va.gov/resources/how-to-get-a-premium-ds-logon-account-online/) | Redirect to [DS Logon FAQs](https://www.va.gov/resources/ds-logon-faqs/) | Done as of 3/22/23 |
|[DS Logon FAQs](https://www.va.gov/resources/ds-logon-faqs/) | Phase 1. Update to reframe DS Logon as an option for DoD websites that you can still currently use on VA.gov. <br><br> Phase 2. Add info alert about VA.gov sunsetting DS Logon & update page to say DS Logon is only for DoD sites | Phase 1: May <br><br> Phase 2: TBD |
|[Creating an account for VA.gov](https://www.va.gov/resources/creating-an-account-for-vagov/)| Phase 1. Update Q&A about DS Logon and MHV and remove link to create DS Logon <br> <br>Phase 2. Add info alert about VA.gov sunsetting DS Logon & remove DS Logon from list of account options | Phase 1. May <br><br> Phase 2. TBD |
|[Signing in to VA.gov](https://www.va.gov/resources/signing-in-to-vagov/)| Phase 1. Update Q&A about Login.gov and ID.me to match content on Creating an account page <br><br> Phase 2.  Add info alert about VA.gov sunsetting DS Logon& remove DS Logon from list of account options | Phase 1. May <br><br> Phase 2. TBD |
|[Verifying your identity on VA.gov](https://www.va.gov/resources/verifying-your-identity-on-vagov/)| Phase 1. Update page to remove 2 Q&As specific to DS Logon <br><br> Phase 2. Add info alert about VA.gov sunsetting DS Logon & remove DS Logon from list of account options| Phase 1. May <br><br> Phase 2. TBD |

---
## Tasks
- [x] Suggest remove/update steps and confirm with identity team
- [x] Coordinate redirects & user flow changes with Kristin
- [x] Suggest Phase 1 revisions to pages (Aliyah)
- [x] Review Phase 1 revisions (Laura)
- [x] Share Phase 1 revisions with Carl and identity team (Aliyah)
- [ ] Copyedit & publish updated pages (Megan)
- [ ] Open a new ticket for Phase 2 work (Laura)

## Acceptance Criteria
- [ ] No VA.gov pages encourage Veterans to create new DS Logon accounts

**Comment by laurwill** [comment]
Hi @CarlDickerson ,
As we chatted last week, we set up this ticket to assess updates to content about creating DS Logon accounts. We have a few questions before we proceed here—I'll post in the channel for visibility, but please let me know if there's someone else we should address these questions to!

**Pages to retire**
There are 2 pages specific to DS Logon that it looks like we'll probably need to retire. 

We had talked about potentially leaving the FAQ page up longer, but the primary purpose seems to be helping people create or verify DS Logon accounts rather than more general questions.

**Question here:**
- DS Logon will still be used to access TRICARE and milConnect, which we link to from several VA pages (see list in this [related audit ticket](https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/53412)). These sites also accept CAC cards, but they don't currently accept Login.gov or ID.me. So before we pull these pages down, we'd like to confirm with your team whether there's any ongoing need for content about DS Logon on VA.gov. 

**Pages to update**
- The [Creating an account page](https://www.va.gov/resources/creating-an-account-for-vagov/#can-i-still-use-a-ds-logon-or-) says "At this time, you can use your DS Logon or My HealtheVet account to sign in to VA.gov." 
- The [Verifying page](https://www.va.gov/resources/verifying-your-identity-on-vagov/) mentions DS Logon and MHV accounts several times as ways to sign in without re-verifying your identity. It also promotes DS Logon as the only way to identity proof by phone.

**Questions here:**
- Do we want to remove all references to DS Logon as a way to sign in, or only content that helps people create DS Logon accounts?
- Do we want to adjust any messaging about MHV at the same time?
- Are there any concerns about removing the only "by phone" option for identity proofing?

**Comment by kristinoletmuskat** [comment]
Hello! And Laura proposed these redirects as well which I think make sense:

Old Page
Redirect




| Old Page     | Redirect |
| ----------- | ----------- |
| https://www.va.gov/resources/how-to-get-a-premium-ds-logon-account-online/      | https://www.va.gov/resources/creating-an-account-for-vagov/       |
| https://www.va.gov/resources/ds-logon-faqs/      | https://www.va.gov/resources/creating-an-account-for-vagov/        |

**Comment by kristinoletmuskat** [comment]
Also pending the answer to Laura's Q about all references to DS Logon, we might also want to adjust content on the [Signing In](https://www.va.gov/resources/signing-in-to-vagov/) page (linked to from the SSO Sign in Modal)
![Screenshot 2023-02-21 at 4.07.45 PM.png](https://images.zenhubusercontent.com/63c829f1a7fcfd33a1b47c17/da28822e-d49b-4683-bb32-f9dfd1b4d387)

**Comment by laurwill** [comment]
Thanks @kristinoletmuskat ! 
I'll add that one to my list above — I'm not sure if we'll remove it from the list of ways you can sign in yet, but we'll want to remove the related link to creating a DS Logon account from the bottom of that page.

**Comment by laurwill** [comment]
Hi @CarlDickerson , 
Because DS Logon will still be needed for DoD sites, we're recommending that we keep the DS Logon FAQs page but update it to frame DS Logon as an account for DoD sites only. We can also add a temporary info alert or page content to explain the transition from DS Logon to Login.gov. We want to make sure that Veterans who come to VA.gov and search for DS Logon can find content explaining what happened to this account option, rather than finding no helpful results.

See new table at top of this ticket with suggested next steps and timing for this work. Before we draft suggested updates to the pages, we want to confirm the next steps and the timing for each step with your team. 

And documenting answers to the previous round of questions here from Slack:
- We're not removing DS Logon from lists of sign in options until it phases out completely in September. For now, we're only removing content that encourages Veterans to create new DS Logon accounts or upgrade to Premium.
- DS Logon will still be needed for DoD sites like TRICARE and milConnect, which we link to from VA.gov pages.
- We're not removing or adjusting content about MHV accounts at this time — that will be separate future work.

**Comment by laurwill** [comment]
Just an update here: The Creating an account page already says "Soon all VA websites will follow a new sign-in process through VA.gov with Login.gov as the recommended account." So we're already publicly talking about this transition on our pages. Could we start updating the DS Logon FAQs and the other sign-in related pages at top of this ticket to reflect that messaging?

**Comment by CarlDickerson** [comment]
> Just an update here: The Creating an account page already says "Soon all VA websites will follow a new sign-in process through VA.gov with Login.gov as the recommended account." So we're already publicly talking about this transition on our pages. Could we start updating the DS Logon FAQs and the other sign-in related pages at top of this ticket to reflect that messaging?

@laurwill I discussed with the team and if we're already showing this language on the Creating and account page, then it makes sense to proceed with updating the DS Logon FAQ with this as well.

**Comment by aliyahblackmore** [comment]
**Update here:** Passed word doc to Laura with the DS Logon FAQs changes. Tracking work on that page in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55491).

**Comment by laurwill** [comment]
Hi @CarlDickerson , confirming that the How to get a Premium DS Logon page is now redirecting to DS Logon FAQs.

We'll have a draft of the updated DS Logon FAQs page ready for you and your team to review later today. But as we're making updates to other related pages, want to confirm how to handle content like this Q&A on the Creating an account page: 
<img width="694" alt="image" src="https://user-images.githubusercontent.com/104158104/226927194-37581539-5ab6-4362-9dd4-64a05ff79227.png">

Questions:
- Should we continue to encourage people to upgrade their MHV accounts to Premium?
- Or should we replace the links to both MHV and DS Logon upgrade resources with something like, "You'll need a Premium MHV or DS Logon account to sign in to VA.gov. If you don't have a Premium account, you can make a Login.gov account now. Login.gov will work for all VA websites and digital tools."
- If we continue telling people to upgrade MHV but not DS Logon, the messaging here will be a bit lopsided. Like "you need a premium account. You can upgrade your MHV. If you have only basic DS Logon, make a Login.gov account."

**Comment by laurwill** [comment]
Hi @aliyahblackmore and @CarlDickerson , 
Just noting that I updated the table at the top of this page to show 2 phases of page updates — initial changes we can make now to align with the "Soon VA will recommend Login.gov language" on the Creating page, and then a second round of changes when we're ready to officially announce that we're sunsetting DS Logon. 

Aliyah will share suggested page revisions with Carl while I'm out of office — just noting we'll hold on copyedit for these until identity team has reviewed and approved the approach.

**Comment by aliyahblackmore** [comment]
Updates here: 

Carl requested I pass a Google document with Phase 1 changes to their team via Slack. 
Tagged Joe, Elizabeth, and Amber on the chat. 

Carl will review with John on their Wednesday demo call.

**Notes on the document** 

- The document contains suggested updates to pages that encourage Veterans to create DS Logon accounts or upgrade DS Logon accounts to Premium.
- This work will still need to go through a copy edit with our team, but we wanted to pass this along for your teams approval and review. 
- In the document, as I mentioned to Joe, there is an open question regarding features Premium MHV and DS Logon users can't use (like modifying direct deposit info). Joe and I will plan to review that question for accuracy next Tuesday and we'll update content accordingly.
- Carl - as you mentioned, you'll review this with John in your Wednesday demo.

**Comment by aliyahblackmore** [comment]
**Updates here:** 
- Carl is OOO on Thursday. I pulled down the weekly meeting. 
- We'll review the feedback from Joe, integrate feedback, and adjust content to meet VA style standards. 
- We'll need to meet with John to align on a few pieces of information. We'll aim to get something on the calendar for next week.

**Comment by RLHecht** [comment]
This work is complete for now. Closing ticket.
