### ISSUE TITLE
Adjust language surrounding "What to Communicate" in CC Playbook

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#53935]
## Purpose
Governance (Shira) had questions about whether a recent change they'd made needed to be communicated in the VFS Change Comm. channel.  We discussed their specific case and she had a suggestion for the playbook to address this specific scenario regarding "what to communicate".

Discussion:  _Maybe it would be helpful to add to the change playbook a checklist or something that helps Platform teams identify if the change they're making should follow these guidelines... Reading the "What types of changes to communicate" doesn't really specify the number of impacted teams, just if the change is perceivable._

## Tasks
- [x] Explore language to make clear that some changes may not need to be announced in the channel.
- [x] Fine tune the language and include in the playbook

## Acceptance Criteria
- [x] Language updated in [playbook](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2317647873/Change+Communication+Guide)
