### ISSUE TITLE
Investigate bounce/exit rates when users interact with language toggle

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#53932]
## Tasks

- [ ] Investigate why the bounce/exit rates might be higher when users interact with the language toggle ([GA Dashboard to view bounce/exit rates](https://analytics.google.com/analytics/web/#/dashboard/jdNx2VfCSDO6xD6_XLtUdA/a50123418w177519031p176188361/_u.dateOption=last7days/)) 
- [ ] Document hypothesis (for example, is it an issue?) 
- [ ] Determine next step (e.g., design, content, bug ticket, etc.) 

## AC

- [ ] Investigated potential issue with language toggle bounce rates
- [ ] Determined next step
