### ISSUE TITLE
[BE] CHIP/service object changes for initiate-check-in endpoint

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#53958]
## Description
Add initiate-check-in endpoint in CHIP/Service object to facility pre-check-in hand off

## Tasks
- [ ] [BE] **Add initiate-check-in endpoint in CHIP/Service object**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
