### ISSUE TITLE
[BE] Create hand-off pre-check-in feature flag

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#53955]
## User Story
As an engineer, I want to create pre-check-in handoff feature flag so that I can implement new changes for pre-check-in handoff behing feature flag

## Tasks
- [ ] [BE] **Create pre-check-in hand-off feature flag**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
