### ISSUE TITLE
[BE] vets-api-mockdata changes for initiate-check-in endpoint

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#53957]
## Description
Modify vets-api-mockdata to add initiate-check-in endpoint mocked response

## Tasks
- [ ] [BE] **Add initiate-check-in endpoint successful response**
- [ ] [BE] **Add initiate-check-in endpoint failure response**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
