### ISSUE TITLE
[FSR] Expanding Group Deprecation 

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#53953]
### Deadline: On Friday, March 31st
Remove soon-to-be deprecated Expanding Group React component from debt applications. 

FSR ExpandingGroup Locations:
`src/applications/financial-status-report/components/ResolutionDebtCards.jsx`
`src/applications/financial-status-report/components/ResolutionOptions.jsx`

#### Helpful links:
[DSVA Announcement](https://dsva.slack.com/archives/C03R5SBELQM/p1676910531869329)
[Deprecated component documentation](https://design.va.gov/storybook/?path=/docs/components-expandinggroup--closed)
[New Design Solution](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54354)

---
## Tasks
- [x] Replace `ExpandingGroup` in FSR components

## Acceptance Criteria
- [x] Expanding Group react component no longer included in debt related apps
- [x] Tests still passing as expected 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
@denisecoveyduc - what epic should we put this ticket in?

**Comment by denisecoveyduc** [comment]
@HeatherRienks adding to our ongoing maintenances since this is a follow on piece to a previous release.

**Comment by HeatherRienks** [comment]
@Dr-Pongo - are we blocked on this ticket and if so, by what?

cc: @denisecoveyduc

**Comment by Dr-Pongo** [comment]
Hey @HeatherRienks ! We will need design input so we can appropriately replace the existing waiver resolution option

**Comment by HeatherRienks** [comment]
Ok, got it!  
Design Team - @mgleo @josephrlee and @charlottecesana - let me know what the best way is to share this feedback. Happy to set up some time for us to discuss if needed.

**Comment by mgleo** [comment]
Hey all, I just created this ticket #54354 with a possible design solution.

**Comment by denisecoveyduc** [comment]
@Dr-Pongo does the design work Megan provided in #54354 unblock this ticket then?

**Comment by Dr-Pongo** [comment]
@denisecoveyduc Yup! Thank you @mgleo !

**Comment by mgleo** [comment]
@amponce I'm meeting with the design & accessibility team on March 7 about the design. To prevent additional work, I'll move both design and dev tickets into blocked for until I receive confirmation that we can move forward. cc @denisecoveyduc @HeatherRienks

**Comment by mgleo** [comment]
@amponce Based on Platform review, updated designs are up on ticket #54354.

**Comment by HeatherRienks** [comment]
@amponce to work on this - needs to be tested.

**Comment by amponce** [comment]
Review Screen:
![Screenshot 2023-03-31 at 2 49 36 PM](https://user-images.githubusercontent.com/3916436/229605784-0dd9a9d0-151d-402b-9e2b-326b743efd06.png)
![Screenshot 2023-03-31 at 2 46 49 PM](https://user-images.githubusercontent.com/3916436/229605791-df2ca6b7-8988-42f8-b37e-a9b5f8097624.png)

![Screenshot 2023-03-30 at 9 28 12 AM](https://user-images.githubusercontent.com/3916436/229605915-a5c590d4-2458-44c0-a340-8779ce8de223.png)
![Screenshot 2023-03-30 at 9 28 28 AM](https://user-images.githubusercontent.com/3916436/229605920-b05ac774-94b0-481e-9776-d47dded4cc95.png)
![Screenshot 2023-03-30 at 9 28 40 AM](https://user-images.githubusercontent.com/3916436/229605924-c94d2ae4-f365-4e3f-a639-889ca8a93b1a.png)
![Screenshot 2023-03-30 at 9 28 51 AM](https://user-images.githubusercontent.com/3916436/229605928-cb3b6e42-cff4-4556-beae-c7c61734d86e.png)

**Comment by amponce** [comment]
Dev is complete, Ready to merge
