### ISSUE TITLE
[BE] CHIP/client object changes for initiate-check-in endpoint

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#53956]
## Description
Add initiate-check-in endpoint call to CHIP/client object to hand off pre-check-in to day-of check-in

## Tasks
- [ ] [BE] **Implement new initiate-check-in method in CHIP/client object**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
