### ISSUE TITLE
[UX] [Research] Create Conversation Guide

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#53964]
## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- Platform [research process](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html) and [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)

## Description
- Create the conversation guide for testing with users

## Tasks
- [x] Create new folder for this specific test in this [overall research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research).
- [x] Create conversation guide (template in research checklist above)

## Acceptance Criteria
- [x] Review conversation guide with team (particularly product, Kristen, and Patrick)
- [x] Post finalized conversation guide to GitHub folder

**Comment by benbrasso-agile6** [comment]
@loripusey we will likely have a point or two leftover for next sprint. I'm finishing up the bulk of the conversation guide and will likely post for feedback tomorrow. Here's the remaining steps: 

* Incorporate Stephen and Lori feedback
* Waiting for Stephen feedback on the poster. E.g., whether or not I need to include something about the poster in the research study or not. 
* Incorporate sitewide content and accessibility feedback (still waiting to receive) 
* Version out a variation for AT users
* Confirm accessibility team availability for research sessions
* Add availability for research sesssions to research plan 
* Submit to Shane Strassberg

Can probably use this same ticket and re-point it during refinement. Your call.

**Comment by benbrasso-agile6** [comment]
Moved to validate. Need to circle back to this after we implement the CAIA feedback into the wireframes and CodePen.

**Comment by benbrasso-agile6** [comment]
Will post in slack shortly
