### ISSUE TITLE
Prep and send 10-10CG form landing page for Spanish translation

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#53967]
## Issue Description

As part of the work to translate the 10-10CG form into Spanish, we also need to translate the static landing page [The Program of Comprehensive Assistance for Family Caregivers](https://www.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers/).

We need to prep the page using our [content readiness checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/editorial-resources/preparing-content-for-translation-checklist.md) before sending it to the State Department.

## Tasks
- [x] Prep document (Randi)
- [x] Review (Ana) 
- [x] Send to translators (Ana)
- [x] Create ticket for building Spanish page (Randi)

## Acceptance Criteria
- [x] Document is with translators

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA I've prepped the document: [https://app.zenhub.com/files/133843125/b9d55459-0bd9-4ef5-810a-c0f84941fdaf/download](https://app.zenhub.com/files/133843125/b9d55459-0bd9-4ef5-810a-c0f84941fdaf/download)

Let me know once you review and I can send it to the State Department.

**Comment by ABeltran77** [comment]
I made some edit suggestions that will allow for a more efficient Spanish translation.

[https-::www.va.gov:family-member-benefits:comprehensive-assistance-for-family-caregivers:.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11204303/https-.www.va.gov.family-member-benefits.comprehensive-assistance-for-family-caregivers.docx)

**Comment by ABeltran77** [comment]
Here is the updated work, had to make some procedural corrections :)
[https://app.zenhub.com/files/133843125/c314e31c-32bb-4bd4-859e-ae3207b6b248/download](https://app.zenhub.com/files/133843125/c314e31c-32bb-4bd4-859e-ae3207b6b248/download)

**Comment by RLHecht** [comment]
This is now with the translators. Closing ticket.
