### ISSUE TITLE
Recheck GA Events due to text solution change

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#53966]
## Tasks

- [x] Check to make sure no new GA events need to get created
- [x] Create new GA events, if needed
- [x] Create FE ticket if GA events need to be updated or added
- [x] Adjust GA widget, if needed
- [x] Add these to the GA dashboard
     - How many users (%) were eligible to file a claim (i.e. viewed the "Want to file?" page)
     - How many users (%) submitted a travel claim (i.e. the BTSSS API was called) ? 

## AC

- [x] Check to make sure no new GA events need to get created
- [x] Created new GA events, if needed
- [x] Created FE ticket if GA events need to be updated or added
- [x] Adjusted GA widget, if needed

**Comment by benbrasso-agile6** [comment]
Created separate GA dashboard - https://analytics.google.com/analytics/web/#/dashboard/-LnfQTl3ShO8HbLIPQ7ZEQ/a50123418w177519031p176188361/_u.dateOption=last7days/

Updated widgets in eCheck-in dashboard: https://analytics.google.com/analytics/web/#/dashboard/1iHzB1FJTq6wHfngzN0LQg/a50123418w177519031p176188361/

**Comment by loripusey** [comment]
closing
