### ISSUE TITLE
Fix Ruby 2.7 Warning - Passing the keyword argument as the last hash parameter is deprecated

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#53972]
## Issue Description
The following Ruby deprecation warning need to be addressed so we can update Ruby to v3.0.0.

Warning - `Passing the keyword argument as the last hash parameter is deprecated`

See discovery ticket for more detailed information - https://github.com/department-of-veterans-affairs/va.gov-team/issues/53655

---
## Tasks
- [ ] All code that triggers this deprecation warning has been updated

## Acceptance Criteria
- [ ] This warning is no longer raised when running Rspec tests with Deprecation Toolkit
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
