### ISSUE TITLE
Fix Ruby 2.7 Warning - Using the last argument as keyword parameters is deprecated

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#53974]
## Issue Description
The following Ruby deprecation warning need to be addressed so we can update Ruby to v3.0.0.

Warning - `Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call`

See discovery ticket for more detailed information - https://github.com/department-of-veterans-affairs/va.gov-team/issues/53655

---
## Tasks
- [ ] All code that triggers this deprecation warning has been updated

## Acceptance Criteria
- [ ] This warning is no longer raised when running Rspec tests with Deprecation Toolkit
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by holdenhinkle** [comment]
Gems to update:
```
/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/bundler/gems/bgs-ext-b173cfba5de3/lib/bgs/services.rb:91::
/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/bundler/gems/bgs-ext-b173cfba5de3/lib/bgs/services.rb:91: 
warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call:
/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/bundler/gems/bgs-ext-b173cfba5de3/lib/bgs/base.rb:28: warning: The called method `initialize' is defined here

/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/actionpack-6.1.7.2/lib/action_dispatch/testing/integration.rb:372::
/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/actionpack-6.1.7.2/lib/action_dispatch/testing/integration.rb:372: 
warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call:  
/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/actionpack-6.1.7.2/lib/action_dispatch/testing/integration.rb:15: warning: The called method `get' is defined here
/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/actionpack-6.1.7.2/lib/action_dispatch/testing/integration.rb:21: warning: The called method `post' is defined here
/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/actionpack-6.1.7.2/lib/action_dispatch/testing/integration.rb:27: warning: The called method `patch' is defined here
/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/actionpack-6.1.7.2/lib/action_dispatch/testing/integration.rb:33: warning: The called method `put' is defined here
/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/actionpack-6.1.7.2/lib/action_dispatch/testing/integration.rb:39: warning: The called method `delete' is defined here

/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/rspec-mocks-3.11.1/lib/rspec/mocks/message_expectation.rb:188::
/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/rspec-mocks-3.11.1/lib/rspec/mocks/message_expectation.rb:188:
warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call:
/Users/holdenhinkle/Documents/Oddball/va_website/vets-api/app/services/sign_in/errors.rb:8: warning: The called method `initialize' is defined here

/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/super_diff-0.9.0/lib/super_diff/object_inspection/inspection_tree_builders/default_object.rb:46::
/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/super_diff-0.9.0/lib/super_diff/object_inspection/inspection_tree_builders/default_object.rb:46:
warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call:
/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/super_diff-0.9.0/lib/super_diff/object_inspection/inspection_tree.rb:16: warning: The called method is defined here

/Users/holdenhinkle/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/forwardable.rb:235::
/Users/holdenhinkle/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/forwardable.rb:235:
warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call:
/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/statsd-instrument-3.5.3/lib/statsd/instrument/client.rb:214: warning: The called method `measure' is defined here
```

**Comment by holdenhinkle** [comment]
All tests are passing now. Closing this...
