### ISSUE TITLE
[BE] Modify lorota/service object check_in_data for hand-off

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#53984]
## Description
Behind pre-check-in handoff feature flag, modify ``lorota/service`` object ``check_in_data`` method to support pre-check-in hand-off

## Tasks
- [ ] [BE] Cache appointment_identifiers for all requests irrespective of check_in type
- [ ] [BE] Implement business logic to call refresh_appointments for day-of check-in multiple appointments
- [ ] [BE] Implement business logic to call refresh_appointments for pre-check-in hand-off to day-of check-in 
- [ ] [BE] Implement business logic to avoid calling refresh_appointments for pre-check-in GET
- [ ] [BE] Implement business logic to avoid calling refresh_appointments for day-of check-in GET first time call
- [ ] [BE] Call initiate_check_in endpoint for pre-check-in hand-off to day-of check-in

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
