### ISSUE TITLE
[BE] Modify PatientCheckIns Controller GET for optional query parameter

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#53997]
## Description
Modify PatientCheckIns Controller GET for optional query parameter

## Tasks
- [ ] [BE] **Modify PatientCheckIns controller GET to accept optional query parameter**
- [ ] [BE] **Add rspecs for newly added query parameter**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by loripusey** [comment]
putting back in the backlog as we are not working on this in the current sprint
