### ISSUE TITLE
[BE] Store hand-off query parameter in model

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#53996]
## Description
Identify the relevant model to store the hand-off query parameter received in PatientCheckInsController GET endpoint

## Tasks
- [ ] [BE] **Identify model to store hand-off query parameter**
- [ ] [BE] **Store hand-off query parameter**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by loripusey** [comment]
@randomsync @kanchanasuriya is this ticket complete or do we need to put it back in the backlog?

**Comment by loripusey** [comment]
putting this back in the backlog as we are not working on this in the current sprint

**Comment by randomsync** [comment]
just waiting on platform approval to merge
