### ISSUE TITLE
[BE] CHIP/refresh-appointments Error Handling 

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#53994]
## Description
Implement refresh-appointments error scenarios to send appropriate error message to vets-website

## Tasks
- [ ] [BE] **Identify possible set of refresh-appointments error scenarios**
- [ ] [BE] **Implement appropriate error messages to send vets-website**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
