### ISSUE TITLE
[BE] Adding request spec for hand-off scenarios

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#53998]
## Description
Add PatientCheckInsController GET request specs for all pre-check-in hand-off scenarios

## Tasks
- [ ] [BE] **Identify all success scenarios & add request specs**
- [ ] [BE] **Identify all failure scenarios & add request specs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
