### ISSUE TITLE
[eFSR] Credit Card Bills Enhancements

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#54003]
## Issue Description
Create new Credit Card bill pages that match [the new design](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1671734127581/dc254b12e788570c946af60bc55338b0045aea03?invited=true&sender=u81a40ee8bf3d2a1110c10911): 

Yes/No
![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/c874b79e-bd65-4199-ae26-3135b5d6dafc)

Input Page:
![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/e12779d1-02a1-4b18-90cd-c3b74f7ffd47)

Mini Summary:
![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/1a54a016-ff4d-4771-873d-17c32630ccf7)

---
## Tasks
- [x] Create Necessary Pages:
  - [ ] Yes/No
  - [ ] Input
  - [ ] Mini Summary
- [ ] Update tests
  - [ ] Unit
  - [ ] e2e
- [ ] Update maximals/minimals as necessary

## Acceptance Criteria
- [ ] New pages added and match design
- [ ] All tests passing

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
