### ISSUE TITLE
[eFSR] Updating alert cards 

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#54005]
## Issue Description
Remove Combined FSR feature flag and old experience from FSR. Now that the FSR has been live with the combined flag active we can remove the feature flag that is currently hiding the previous experience.

#### Note: 
**Do not** remove the combined feature flag enhancments flag as that is being used to hid the currrent enhancement work. 

---
## Tasks
- [x] Remove pages hidden by combined 
 **Note:** This may not be a comprehensive list
  - [x] `availableDebts` Page
  - [x] `recreationalVehicleRecords` Page
  - [x] `resolutionOptions` Page
- [ ] Update / Remove data mocks that no longer apply
- [ ] Update / Remove tests that no longer apply for previous structure  
- [ ] Test test test test test test

## Acceptance Criteria
- [ ] Combined FSR feature flag references have been removed leaving only the new experience pages
- [ ] All tests (unit / e2e) are running and passing. 
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
@denisecoveyduc - are you ok with pulling this one into this Sprint (93)? This is what Andrew mentioned yesterday as being important to get done.

cc: @Dr-Pongo

**Comment by Dr-Pongo** [comment]
Moving to blocked until we can finalize error/alert notification flow/design to avoid additional test updates

**Comment by HeatherRienks** [comment]
@Dr-Pongo - anything else you need on this one?

cc: @mgleo

**Comment by Dr-Pongo** [comment]
Ticket is still WIP! Wrapping up e2e tests, and deprecating some older ones. Once expanding group deprecation is in place I should be able to address the last of the testing errors and get this merged in!

**Comment by HeatherRienks** [comment]
Per Andrew's SU update, holding off until employment history &other living expenses work is completed.

**Comment by Dr-Pongo** [comment]
Now that major flow changes have been implemented, I'm segmenting the work on this ticket in two parts:
- Updating debt fetching to selection page and including new alerts for failures/empty states
  - [PR here](https://github.com/department-of-veterans-affairs/vets-website/pull/24151)
- Removing combined feature flag and updating tests/data structures

**Comment by HeatherRienks** [comment]
@Dr-Pongo - do you anticipate that this one will be wrapped up by end of S98? (EOD tmrw?)

**Comment by Dr-Pongo** [comment]
Updated title to reflect work for just alert cards! 
Main reason this kept getting delayed is cypress tests timing out likely due to using outdated versions of Cypress. [Support thread here identifying issue](https://dsva.slack.com/archives/CBU0KDSB1/p1684773428364509)

Skipping tests until Cypress has been updated, closing out ticket after final checks pass with updated error handling.
