### ISSUE TITLE
[eFSR] Installment Contract Enhancements 

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#54004]
## Issue Description
Create new Installment Contract pages that match [the new design](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1671734127581/dc254b12e788570c946af60bc55338b0045aea03?invited=true&sender=u81a40ee8bf3d2a1110c10911): 

Yes/No
![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/b1d30e3a-6f01-4e44-b0eb-4c766e17c40e)

Input Page:
![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/76afa7e9-4eed-4f7a-acb1-d0837cac8e63)

Mini Summary:
![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/69560eac-e7be-42f5-89b0-ec13389f6a27)

---
## Tasks
- [ ] Create Necessary Pages:
  - [ ] Yes/No
  - [ ] Input
  - [ ] Mini Summary
- [ ] Update tests
  - [ ] Unit
  - [ ] e2e
- [ ] Update maximals/minimals as necessary

## Acceptance Criteria
- [ ] New pages added and match design
- [ ] All tests passing

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by OptionSelect** [comment]
This is going to roll to the next sprint based on how long the other ticket took me to do!

**Comment by HeatherRienks** [comment]
Blocked by GIT CI pipeline - will merge ASAP once resolved (DevOps issue).
