### ISSUE TITLE
[Design] [Bug] Update Wireframes to remove timezone

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#54002]
## Background
See [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53971#issuecomment-1439202797)
## Tasks
- [ ] Update Wireframes to remove timezones from appointment information. Do NOT need to remove timezones from times that are in Need Help or Accordions. 
- [ ] Update all files: production sketch pages, check in sketch file but just main design pages, pre check in sketch file but just main design pages. Unified check in sketch file does NOT have timezones already. 
- [ ] Publish wireframes to VA Sketch cloud

**Comment by benbrasso-agile6** [comment]
Knowing that we may be adding the timezone at some point, do we need to remove it from our design files now?

**Comment by loripusey** [comment]
these are pushed out to VA Sketch cloud, so anyone looking at them (and not our product) will think we have time zone but we do know and have no idea if/when it will happen; probably safer to take it out (is there a hide?)

**Comment by benbrasso-agile6** [comment]
Sure, no worries.

**Comment by zach-park** [comment]
@benbrasso-agile6 @loripusey , They are completed and ready for validation. Thank you.

**Comment by benbrasso-agile6** [comment]
Validated. @zach-park it looks like the typography is still in bold in the check in file
