### ISSUE TITLE
Supplemental Claims | Update start page content

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#54006]
## Value Statement

**_As a_** Screen reader user
**_I want to_** be aware of all content on the page
**_So that_** I don't miss important details

## Background Context

The Supplemental Claim start page (subtask) currently includes content below the "Continue" button which a screen reader user may not be aware of. A redesign of the start page moves this content above.

[DESIGN](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/v/zW0OmM/p/0454C07B-0B34-46F7-9287-200FD43F78D5/canvas#Version)

## Tasks
- [ ] Update the content on the start page
- [ ] Update and check tests as needed

## Definition of done
- [ ] All tasks complete
- [ ] All tests passing

**Comment by Mottie** [comment]
Changed merged in, may be [available in staging](https://staging.va.gov/decision-reviews/supplemental-claim/file-supplemental-claim-form-20-0995/start) soon

**Comment by saderagsdale** [comment]
@eileen-coforma the content appears to be above the Continue button in staging. Any concerns with closing this one?
