### ISSUE TITLE
Support Sitewide IA to map user flows for DSL migration

### ISSUE THREAD

**Issue by tygindraux** [department-of-veterans-affairs/va.gov-team#54013]
## Problem statement
Veterans need to make migrate their DS Logon accounts to Login.gov through grandfathering, which allows them to defer identity proofing to a later date.

## Initiative
Kristin Ouellette Muskat, Information Architect on Sitewide Content/Accessibility/IA (sitewide CAIA) first reached out: 

> "I really appreciate all the documentation ya’ll have on your product page and esp. the mural of the user flow you’ve put together! I think the big thing we’ll be supporting with is with beefing up the [user flow](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1671554156732/bb8f2948581f649bf8fd8ad9816224d93818992d?invited=true&sender=ua67f17f1c416a96ea04d2476) so that we don’t miss any important use cases in the initial rollout. I’ve started to put together some questions and ideas about the [user flows in mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1676397151510/f4cf4f4187a3d0fd5f2d6d56c9bd2ba3a4376e7a?sender=ua67f17f1c416a96ea04d2476) (unfortunately this doc is untitled at the moment and I can’t change it because of permissions). @tygindraux does it make the most sense to chat with you about this? Or who should I connect with?"

We met with sitewide CAIA on March 3 and March 9 to answer questions and scope work. This ticket has been updated with tasks from our last meeting on March 9th. This work is still ongoing and acceptance criteria is not well defined yet.

This work likely with require advice from Steve.

## Acceptance criteria
- [ ] Sitemap(s) have been created to accurately reflect the DSL migration to Login.gov

## Tasks
- [x] @tygindraux - ask core team if we can send the user directly to the DSL sign-in page
- [ ] @kristinoletmuskat - define what happens if the user is logged out of VA.gov while they are still on Login.gov
- [ ] @MOStudioCarolyn and Sofia - define how we can get a user back to the task they were originally trying to do before they were interrupted, if they decide to stop Login.gov account creation before the flow finishes (eg. does the login.gov flow open in a new tab, do we redirect them back to their original task in another way, or something else)

## Notes from chat with Carolyn/Sofia on March 14th
How might a user get back to the task they were originally trying to do on VA.gov?
- Think through reasons for or against a second tab opening
- Think through alternative options to second tab, eg. 'take me back' button (and how might this work since it's on Login.gov's page?)

Outcome
- Add stickies to Sitewide IA Mural board

**Comment by tygindraux** [comment]
Note to myself: I need to update this ticket to better reflect this IA work.

**Comment by laurwill** [comment]
Hi @tygindraux and @kristinoletmuskat @MOStudioCarolyn , 
Just chiming in with 2 user flow questions here:
- In the binding flow that starts from an email, will users see the same modal after signing in with DS Logon that they would see in the interrupted flow? Or can we serve them different content at that step? The email content is almost identical to the modal in the interrupted flow, so I'm concerned about confusion if they see the same content again.
- Documenting Q from slack thread: What happens if a user needs to accept the new Terms of use (aka unified T&C) at the same time that we're showing them this binding flow content? These are both task-interrupting flows that appear just after signing in to VA.gov.

**Comment by tygindraux** [comment]
@laurwill Part of the reason we're testing these two different flows to understand whether one is more or less motivating for Veterans. Here's the [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/research/2023-02-Grandfathering-Migration-Round-1-Usability/research%20plan.md) for additional context. We'll use this research to make decisions about whether we continue with a modal flow, an email flow, or (if for some reason this was an outcome of the research) how we would design both these flows so they could interact without confusion (for example, in the way that Carl's posted above).

I think we need to wait until we've done at least some research before we start making decisions about whether to use a modal or not. And the TCs work is something we're tracking in weekly identity working group meetings, so this is on our radar and will influence our decision. Hope that helps.

**Comment by laurwill** [comment]
Aha! Thank you both for these answers. That all makes sense!

**Comment by tygindraux** [comment]
No worries! Thanks for continuing to flag questions!

**Comment by tygindraux** [comment]
Note: I've asked whether we would be able to send a Veteran directly to the DSL sign in page (rather than SSO page) and was advised to ask John Rahaghi. I'd suggest we wait to ask about this/pursue this option until after Round 1 of testing. If we see there's a potential issue with sending people to VA.gov's SSO page (which is now our hypothesis) than we can raise the issue with John and address whether we test this alternate flow instead.

**Comment by tygindraux** [comment]
Note from Sofia: I added blue stickies to the IA sitewide site map mural board and considered some pros and cons of having one vs two tabs for the interruption. At this point, I would lean towards having two tabs but it is probably worth reviewing this with some other product team members (specifically Steve and our devs) to get thoughts since this topic has come up before.

In addition to having multiple tabs, I considered ways to get users back to the task they were trying to accomplish. A lot of the ideas have to do with timing out the Login.gov page or adding a button that permits users a quick exit/‘return to start’ which may not be feasible given that Login would need to make this addition.

A question that came up for me at this time  was how long might it take for users to complete the binding, and this is something we can learn from our first round of research. By having this information, we can send a warning to users about navigating to Login.gov and tell them how long it may take to bind their accounts. We can also be sure about whether we will run into timeout issues with DSL.

A final consideration is what happens to the Login.gov tab if it times out after DSL times out (say if the user left it open after deciding not to complete binding at the time). After researching some other examples, some common patterns seem to be the following:

1. Allowing the page to refresh and letting it say “session timed out”
2. Having a warning pop up come up about the timed out session before sending the users back to another page (usually a homepage but in our case it could be different)
3. Having a warning pop up about the timed out session before the tab closes completely.

I’m more in favor of the first option just because it seems the most clear and familiar to users and the least complicated given that we’re dealing with multiple sites at once.
