### ISSUE TITLE
[Product] Submit Translations to the State Department

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#54029]
## Tasks
- [x] Create JSON file with new content to be translated (one for each language)
  - See instructions [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/translations/json-compare/README.md)
- [ ] Create English screen shots for context
  - See examples of screenshots [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/translations/spanish-round-3)
- [ ] Submit JSON file and English screen shots to Randi Hecht for forwarding to the State Department

## Acceptance Criteria
- [ ] JSON file and English screen shots have been submitted to Randi Hecht

**Comment by loripusey** [comment]
UX pointed 5

**Comment by loripusey** [comment]
Let's work towards not needing to involve engineers in this process

**Comment by kellysmith1008** [comment]
Emailed Randi today with the files, copied Lori, Ben, Sarah, and Brian on the email.
[Tagalog mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1680116198387/674c5ec10e2c4837478021dcac3c1c99cb4bb053?sender=u5d970cc175b184392a004997)
[Spanish mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1680011920646/4d6b4ff89bb7803610c1fb50f3034b057568ba4f?sender=u5d970cc175b184392a004997)
Will post the information in git and then close this ticket
