### ISSUE TITLE
Find and replace instances of "on file"

### ISSUE THREAD

**Issue by megzehn** [department-of-veterans-affairs/va.gov-team#54035]
## Issue Description
We need to look for instances of "on file" within VA.gov and replace with a plain language version that isn't an idiom. 

---
## Tasks
- [ ] Conduct an audit to find instances of "on file" 
- [ ] Replace those versions
- [ ] Copy edit
- [ ] Publish 

## Acceptance Criteria
- [ ] All instances of "on file" are replaced with a PL alternative 
---
