### ISSUE TITLE
Design | Profile | Logged-in IA/Nav | Notification settings | surface relevant links

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#54047]
## Background

We know that claim status is incredibly important to Veterans who have a claim or appeal in progress. How might we give them easier access to that information from profile?

As we expand the prescription shipping notification options, we should also explore if there’s a way we can make it easier for people to check whether or not the notification is relevant to them based on their pharmacy.

([From add email channel research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/discovery-and-research/usability-study-add-email-jan-2023/findings-summary.md#explore-how-we-might-surface-meaningful-and-relevant-links-to-people-in-the-notification-settings-section))

## Tasks
- [x] Identify opportunities to surface relevant information for Veterans
- [x] Create mock-ups (lo-fi, sketch, anything works) representing alternatives to what we're doing today
- [ ] Review concepts w/ fellow designers, including a11y specialists
- [ ] Once a way forward is determined, review w/ content 
- [ ] Review with PO

## Acceptance Criteria
- [ ]  A new approach is agreed upon by the team and we can move forward w/ hi-fi mock-ups and updating all Sketch files

## Validation
- Any member of the team can validate

**Comment by BerniXiongA6** [comment]
@mtcA6 -- in stand up, @andaleliz said this ticket can go to the Ready pipeline so she can take it on next in Sprint 11. So I've moved the ticket over from Sprint 10 to 11 ahead of sprint planning. This is an FYI for us.

**Comment by andaleliz** [comment]
@mtcA6 FYI I need to bump this into the next sprint; won't get it finished tomorrow

**Comment by andaleliz** [comment]
Thoughts so far:
- I looked at [GA searches that took place on profile pages from Jan-Jun 2023](https://analytics.google.com/analytics/web/#/report/content-site-search-pages/a50123418w177519031p184624291/_u.date00=20230101&_u.date01=20230611&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=250&explorer-table.filter=~2Fprofile&explorer-table.secSegmentId=analytics.searchKeyword&explorer-table.advFilter=%5B%5B0,%22analytics.searchStartPage%22,%22RE%22,%22~2Fprofile%22,0%5D%5D/), and visits to profile pages during the same time.   If I'm doing the math correctly, it looks like ~1% of visitors to profile use search. Not a huge amount.
  - The terms they're searching for from profile are largely related to dependents and records, which we are already addressing through #59199 and #59202
  - There are a small amount of searches for things related to claims ([report](https://analytics.google.com/analytics/web/#/report/content-site-search-pages/a50123418w177519031p184624291/_u.date00=20230101&_u.date01=20230611&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=250&explorer-table.secSegmentId=analytics.searchKeyword&explorer-table.advFilter=%5B%5B0,%22analytics.searchStartPage%22,%22RE%22,%22~2Fprofile%22,0%5D,%5B0,%22analytics.searchKeyword%22,%22PT%22,%22claim%22,0%5D%5D/))
- I also looked at navigation summaries for each page in profile to see if there are any trends around next pages people are going that might suggest they're going somewhere we're not already sending them. They aren't - all the next pages are either another place in profile, a link we're surfacing (disability rating and payment history are the most common non-profile pages), or My VA.
- Looking at other notification settings sections of similar site profiles (banking, insurance, USAA, etc), I don't see a pattern of cross-linking to other parts of the website, other than to things like terms and conditions.  That tells me there isn't some kind of best practice private sector standard we're missing.

Given that we know claim status is highly important to people, I still think it's worth exploring better surfacing that to people in the profile, especially if we know that they have a claim in progress. I'm going to start further digging into a couple of other ideas:
1. If someone doesn’t yet have a rating, and they have a claim in progress, that tells us they are probably waiting for a rating. What would it look like to surface a link to their claim status in the nametag when that’s the case?  How could that work if they have a rating AND a claim in progress?
2. Should we add a link to the CST in the disability rating section of `/personal-information` when we know someone has a claim in progress? What about in the Payment History section of direct deposit?

**Comment by mtcA6** [comment]
do you want to sync up about the additional questions/ideas this has generated? or not yet?

**Comment by andaleliz** [comment]
@mtcA6 thanks for checking in! I mostly have technical questions at this point:

@tpharrison and @adamwhitlock1 I'm interested to get your thoughts on conditionally showing things in the profile or name tag based on if someone has a claim in progress.  I know that part of My VA always takes a long time to load, and I'm curious how it would impact the performance if we were to conditionally display a link to the claim status tool based on whether or not someone has a claim in progress.  I think to start we would show this if they don't have a rating yet. Something like:

![image.png](https://images.zenhubusercontent.com/5d9def68b6de6d00018d50f2/97b27e2e-139b-4968-9616-94a21f0a0eb9)

 I'm not sure if status of a claim in progress or disability rating would be more important to Veterans who have both, so I think we'd stick w/ just showing the disability rating if they have both. 

And then in the disability rating section of the Personal Info page, we could swap out the rating content for claim status content, when applicable:
![image.png](https://images.zenhubusercontent.com/5d9def68b6de6d00018d50f2/b733c591-2594-4a59-b88d-4ebbfeb06da6)

**Comment by adamwhitlock1** [comment]
Claims and Appeals is definitely one of the things that slows down the loading of the My VA dashboard.

As far as the Claims endpoint `/evss_claims_async`:

I don't know a ton about the flow of the api requests on My VA, but I do know that the claims endpoint is 'async' which means that 2 actual requests need to be done to get the data.

- first request is basically asking for the claims service to _start the work_ to get the data
- second request after the first is done, is the follow-up to actually retrieve the data
- it wasn't terribly slow when I looked at staging, but the second call was delayed significantly mainly due to other data loading at the same time.

There is another endpoint just for `/appeals`, and I'm not sure if that would also need to be called for use by the nametag, but it usually resolves (at least in staging) at around 1 second. Not great, so hopefully that one wouldn't be needed.

**Comment by tpharrison** [comment]
I think its a great idea, but because of the reasons that Adam stated, I think Derrick and I should take a look at the performance.  We might be able to make some improvements.  I'll open a ticket for us to investigate.

**Comment by andaleliz** [comment]
Thanks @tpharrison! Can you send me that ticket when you have a moment? I'll add it as a dependency for this one, and move this out of in progress while I wait to hear back from you.  I don't think we need any more mock-ups at this point, beyond what I posted in the comment above.

**Comment by adamwhitlock1** [comment]
> @adamwhitlock1 thanks for your feedback too! One thing I thought about is that if we went this route, would we move the claim API call from My VA, to the name tag, since we'd be leveraging it across both products? I don't know how that works exactly.

That is a good point, and one that would definitely have to be considered as far as LOE. It would require the api request logic to be moved out of the My VA code and into a common area like the nametag, or some sort of 'data provider' abstraction. If the data was held in our state store (or React context), then any component _could_ use it, so that might be a viable way to explore.

Also handling the loading of the claims api request failing will be something to design around maybe?

**Comment by andaleliz** [comment]
> It would require the api request logic to be moved out of the My VA code and into a common area like the nametag, or some sort of 'data provider' abstraction.

This sounds like a not small amount of work, and probably something we would want to have a clear estimate on before we go too far down the road. I think this would be valuable to Veterans but depending on the LOE, maybe not worth it? Or worth only doing when we have downtime and not a high priority thing.  Is it something a sync between My VA devs and Profile devs would help?  I'm not sure what the best approach would be

> Also handling the loading of the claims api request failing will be something to design around maybe?

Ah, that's a good call out @adamwhitlock1! I can work on that (and any other edge cases I think of) while we figure out more about technical feasibility.

**Comment by andaleliz** [comment]
I've mocked up 2 scenarios to surface the claim status tool:
- [Personal information, disability rating section](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/p/92C0BD0E-4B51-4C50-A349-AF2A685F72FB/canvas)
- [In the name tag](https://www.sketch.com/s/113f0ee6-e77d-4b1b-bf02-af27580931fe/p/372FECD7-7064-4B5F-857F-687F0B8B0A58/canvas) (for some reason the Sketch symbols are rendering weird in the browser, but it's fine in the Sketch app)


Since we still need to do some discovery around technical feasibility, I'm going to remove the content review from the AC on this ticket. No point in leaving this open until next Thursday's office hours if we don't know whether or not we want to do it.

@tpharrison did you get a chance to make that ticket? If so, I'll follow along and then work on the next steps once we know whether or not we want to proceed.

**Comment by tpharrison** [comment]
@andaleliz Yep - https://github.com/department-of-veterans-affairs/va.gov-team/issues/60248.
