### ISSUE TITLE
Design | Profile | Notification settings | Improve accessibility of input message pattern

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#54046]
## Background

The input message pattern design caused some problems people using magnification in a [recent research study](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/discovery-and-research/usability-study-add-email-jan-2023/findings-summary.md). 

We should look into how we might improve the pattern to reduce that friction and make the design more accessible for all. 

Two ideas are to remove the checkmark icon, and reduce the width of the green background.

## Tasks

- [x] Create mock-ups (lo-fi, sketch, anything works) representing alternatives to what we're doing today
- [x] Review concepts w/ fellow designers, including a11y specialists
- [x] Review with PO
- [ ] Possibly review w/ design council, if it's a major change.
- [ ] Submit update to [design system documentation](https://design.va.gov/components/form/input-message) for this component

  

## Acceptance Criteria
- [ ]  A new approach is agreed upon by the team and we can move forward w/ hi-fi mock-ups and updating all Sketch files, including component specs

## Validation
- Any member of the team can validate this

**Comment by andaleliz** [comment]
I talked about this with the other practitioners who reviewed the work, because I was thinking the same thing.  We came to the consensus that it would be worth doing the work despite it being only 1 person's feedback because:
- We've seen other horizontal scrolling issues happen with people using magnification in research that suggest we need to be intentional about the cues we do or don't give users about what is on the right side of the page. Cindy observed the opposite problem where people missed things on the right side of the page because there were no cues to suggest they should look there.
- The stacking checkbox thing is a really good point. It does look weird and it's kind of confusing. Swapping the icon to be the inverse of what is in the checked checkbox is an easy win.

**Comment by Samara-Strauss** [comment]
Thanks for this, @andaleliz. I still have a couple more questions:

1. Does this affect anywhere else in the profile?
2. Are you going to go through the design system council to update the styling of this element in general?

**Comment by andaleliz** [comment]
1. No it doesn't, we only use it in notification preferences
2. Yes, I would. That's the last task needed to close this ticket.

**Comment by Samara-Strauss** [comment]
Great! Thank you for this. Then I am OK with us moving forward, and my preference would be for the first design. 

Also, if the check icon in the circle caused confusion, I do have concerns that the checkbox not in the circle could still be confusing. Do you have any concerns around this or no?

**Comment by andaleliz** [comment]
Yeah, I'm not totally convinced it'll eliminate confusion, but I do think it lessens it. With the new padding and margin, it's further away from the other checkboxes, and it's not contained in a similar way that the actual inputs are.  The main thing is that I don't think it'll make things any worse than they are now.

**Comment by Samara-Strauss** [comment]
Great! That works for me. Let's move forward with design 1.
