### ISSUE TITLE
Branch maintenance for VAOS pre check in 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#54044]
## Task

- [x] [This commit](https://share.goabstract.com/49e5e0ca-feac-4ccb-9a03-0e05eeb05d75?collectionLayerId=cb455f27-7b9d-4dac-82f5-ac339c563b3b&mode=design&sha=31966a97d7ce87bb6c64c6778a801a609ceb5850) needs to be  replace [this wireframe in this branch](https://share.goabstract.com/04c09d9c-4153-4a14-b034-2e1ca094ebb0?collectionLayerId=d0a08063-59d6-426e-a5b4-1cb7d733e8bb&mode=design&sha=latest). (@zach-park )

- [ ] Once that is moved, there is no longer a need for this [sub branch](https://share.goabstract.com/49e5e0ca-feac-4ccb-9a03-0e05eeb05d75). It can be deleted. (@ytsaoca )

Do not merge with master. 

## Deliverable
- [x] [Wireframe link](https://share.goabstract.com/04c09d9c-4153-4a14-b034-2e1ca094ebb0?collectionLayerId=d0a08063-59d6-426e-a5b4-1cb7d733e8bb&mode=design)

**Comment by zach-park** [comment]
@ytsaoca , can you please archive this [branch](https://share.goabstract.com/95aa61ec-125e-4756-a1a2-20b39a9a0ab9)?

**Comment by zach-park** [comment]
[The wireframe](https://share.goabstract.com/c3988503-4634-4f1c-b38d-6b990cc764e6?collectionLayerId=1692e806-88ea-4a48-9ea3-f6196c8689f4&mode=design) is updated and ready to be merged to the parent branch: (https://share.goabstract.com/c3988503-4634-4f1c-b38d-6b990cc764e6?collectionLayerId=1692e806-88ea-4a48-9ea3-f6196c8689f4&mode=design)

**Comment by benbrasso-agile6** [comment]
@zach-park [this wireframe ](https://share.goabstract.com/c3988503-4634-4f1c-b38d-6b990cc764e6) should replace [this wireframe](https://share.goabstract.com/04c09d9c-4153-4a14-b034-2e1ca094ebb0?collectionLayerId=d0a08063-59d6-426e-a5b4-1cb7d733e8bb&mode=design&sha=latest). 

Can we do that now and get rid of the two sub branches?

**Comment by benbrasso-agile6** [comment]
Perfect. All set
