### ISSUE TITLE
Design | Profile | Notification Preferences | Reconsider "add contact info" call to action

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#54045]
## Background

We have an opportunity to reduce clutter in the UI and set clearer expectations about the 2 step process of adding missing contact information. Let's explore how we might present this important call to action in a clearer way. ([from add email channel research study](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/discovery-and-research/usability-study-add-email-jan-2023/findings-summary.md#reconsider-how-we-are-encouraging-people-to-add-their-email-address-to-their-profile))

## Tasks
- [x] Create mock-ups (lo-fi, sketch, anything works) representing alternatives to what we're doing today
- [x] Review concepts w/ fellow designers, including a11y specialists
- [x] Once you land on a way forward, bring to content office hours 
- [x] Review with PO

  

## Acceptance Criteria
- [x] A new approach is agreed upon by the team and we can move forward w/ hi-fi mock-ups and updating all Sketch files

## Validation
- Any member of the team can validate

**Comment by adamwhitlock1** [comment]
We can totally do this. I think this is a pretty cool approach as it helps bring clarity to what notifications are tied to what channels (email or text)

It will be a bit of a challenge I'm sure with the dynamic nature of the api data and how we render it, but I say lets give it a shot.

**Comment by adamwhitlock1** [comment]
As to the second item. I think we can flesh that idea out and see how that conditional logic could work. I will need to look into that further, and see how things work. One part of this equation is all the feature toggles tied to 'not production ready' notification and their groups/channel based hide and show logic. It's a bit dicey right now, but this type of feature may help up nail down that code and modularize the display logic better.

**Comment by andaleliz** [comment]
@mtcA6 @BerniXiongA6 and @mtcA6 I'm wondering if we should try to include this into the default send collab cycle work. This is "default send adjacent" work, since we're updating the way we handle when user has contact info for one channel, but not both (e.g. has email address on file but not mobile number).

This is ready for a design intent review, so we might be able to get it reviewed Thursday and not have to do collab cycle just for this feature; we'd likely launch all the changes at the same time.  The only thing is that this specific update has NOT been tested with users. I would hope we can evaluate it as part of UAT (I have included 1-2 usability questions in UAT studies without issue before).

**Comment by mtcA6** [comment]
Let’s try, sounds like a good plan to me @andaleliz

**Comment by mtcA6** [comment]
@andaleliz thanks for all the added details, I like 2 and 3 (I feel the language in option 2 is clearer but prefer the color in option 3) but both feel like they'll get the job done.

**Comment by andaleliz** [comment]
I reviewed this in content office hours today and updated the mocks (and mural board) with the approved language. Onto design intent :) 

Here's the [closed view](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/x0gvqD0), and the [expanded view](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/EeqpOwq)

**Comment by mtcA6** [comment]
@andaleliz since this was well received at the design intent, do we move onto the next step and have adam build this out? How do you convert this design into tickets/issues for adam to work on? ie. what's the process?

**Comment by andaleliz** [comment]
And, @mtcA6, actually the PO step would usually take place _before_ design intent. Chante was in that meeting, so I'm not sure we need anything else from her. You might want to double check with her to make sure she's good with these changes, but I'll leave it to you.

**Comment by mtcA6** [comment]
@andaleliz chatted w/her today and she was onboard w/ the next steps. I'll create a ticket and slate it against the next sprint and tag you when its ready

**Comment by andaleliz** [comment]
Sounds good! Closing this out then, all AC has been satisfied

**Comment by mtcA6** [comment]
@andaleliz this has been implemented, but should the bullets be dots instead of squares? 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/15d244d4-2252-4306-ad07-0fce4ff274cc)

**Comment by andaleliz** [comment]
There's a disconnect between bullets in Sketch and bullets in code - however they render in the code is fine. Thanks for catching that though! I think @pamela-drouin and I talked about opening a ticket for that once upon a time but not sure if she has had a chance to do that.

**Comment by pamela-drouin** [comment]
@andaleliz @mtcA6 That fell off my radar!

**Comment by andaleliz** [comment]
@pamela-drouin no problem! I'll fill one out.

**Comment by andaleliz** [comment]
FYI [here's the ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1964)
