### ISSUE TITLE
FE COP: Review and Update E2E allow list documentation

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#54055]
## Issue Description
The E2E allow list documentation was hastily thrown together as the team restructure was happening. As such, it may be missing information and should be reviewed for comprehensiveness. Additionally, some changes have been made to how the allow list notifies teams and that should be added to the documentation as well. Lastly, we should make sure this documentation link is contained in the published page that is referenced to teams and possibly, in the Slack notification.

---
## Tasks
- [x] Review allow list documentation for comprehensiveness
- [x] Add updated information regarding the notification procedures
- [x] Make sure documentation is linked accordingly to be easily accessible.

## Acceptance Criteria
- [x] Documentation is all up to date and easily accessible.
---

**Comment by CBonade** [comment]
https://vfs.atlassian.net/wiki/spaces/pilot/pages/2379120641/E2E+Stress+Test+and+Allow+List Documentation page has been updated

**Comment by pjhill** [comment]
We can close this ticket once we confirm that the page is successfully published to the Platform Website around 5pm today.

**Comment by pjhill** [comment]
It's published! And, Curt resolved a defect -- hooray!
