### ISSUE TITLE
BE | Profile | Direct Deposit | Configure and Test Staging access

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#54054]
## Background
Configure staging access for the vets-api.

## Tasks
- [x] Obtain staging authentication keys.
- [x] Add staging key to AWS parameter store.
- [x] Update configuration files.
- [x] Test in staging with feature flag on.
  

## Acceptance Criteria
- [x] Staging tests run successfully

**Comment by tpharrison** [comment]
@Samara-Strauss Based on a conversation with another developer that is working through a similar ticket, configuring staging (the work for this ticket) may take a bit more time (~ 1 more day) than I originally anticipated due to the recent EKS migration.

I haven't started the work yet so I'm just anticipating at this point, but I figured I'd let you know.  I'll keep you updated.

cc/ @BerniXiongA6

**Comment by Samara-Strauss** [comment]
Totally fine! Thank you for letting us know. If those goes into next sprint, we'll adjust timelines accordingly. Thanks, Tom!

**Comment by BerniXiongA6** [comment]
Hi @tpharrison will any of this work carry over and if so do you have an estimate of how many points are left?

**Comment by tpharrison** [comment]
Hi @BerniXiongA6 I am planning on completing this by the end of the day.  Ok if I give you an update later today?

**Comment by BerniXiongA6** [comment]
That's update is already awesome thanks @tpharrison !

**Comment by tpharrison** [comment]
@Samara-Strauss @BerniXiongA6 I'm submitting PRs for this ticket today, so it will be moved to validation status by the end of the day and remain there until the PRs are reviewed and accepted (probably 24-48 hrs).
