### ISSUE TITLE
Preview Env: Write Developer Docs - Cleanup Job

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#54050]
## Issue Description
While we wait for numerous aspects of the PE initiative to move forward, it would be nice to start the documentation so we have a good bit in place when we're ready to launch. The first piece that seems set in place and unlikely to change are the cleanup jobs. Lets document both of the cleanup jobs with some of what they will be involving.

---
## Tasks
- [x] Create PE Documentation section in TT4 Confluence Space
- [x] Add page for cleanup jobs that details both the scheduled cleanup job and the delete-triggered cleanup job
- [x] Review w/ PM & TL, refine as needed

## Acceptance Criteria
- [x] Documentation has been reviewed and approved

**Comment by CBonade** [comment]
Parent page to house all PE documentation:
https://vfs.atlassian.net/wiki/spaces/TT4/pages/2542370882/Preview+Environments+Documentation

Cleanup Jobs documentation: 
https://vfs.atlassian.net/wiki/spaces/TT4/pages/2541650303/Cleanup+Jobs

This can be all moved to developer docs once we're ready to launch the product, along with whtaever other pages need to be added.

**Comment by pjhill** [comment]
Thanks for knocking out some documentation
