### ISSUE TITLE
BE | Profile | Direct Deposit | Create Comp & Pen Controller

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#54051]
## Background
Create a new controller/endpoint to replace the existing PPIU controller.

## Tasks
- [x] Create new Controller
- [x] Update routes
- [x] Create specs
- [x] Add error handling
- [x] Add feature flag
  

## Acceptance Criteria
- [x] PR accepted
- [x] All specs passing
