### ISSUE TITLE
SPRINT GOALS:  2/22/2023 - 3/7/2023

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#54064]
#### SPRINT GOALS
- **GOAL: Test Vets-API Server to EKS in Staging**
- **GOAL: Standardize how Veterans see their appointment information across all Veteran-facing applications**
- **GOAL: Make submission of a travel reimbursement claim easier**
- **GOAL: Increase usage of Pre-Check-in & Check-in**
- **GOAL: Address tech debt**

#### Planned Releases 
- [New Message for Expired Link: Pre-Check-in and Day of Check-in](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52392)
   - Release when complete

#### SPRINT TICKETS
- **GOAL: Test Vets-API Server to EKS in Staging**
   - [ ] [[FE][BE] Check-In Experience: Testing in Staging Vets-API Server to EKS](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52715)
- **GOAL: Standardize how Veterans see their appointment information across all Veteran-facing applications**
   - **Sub Goal: [Make Appointment Info & Visual Design Consistent with VAOS](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45315)**
      - Fix bugs
         - [x] [[FE] Add appt instructions into appt list on pre check in confirmation page](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/53855)
         - [ ] [[FE] Clicked on details link after 15 mins past appt time](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/53862)  
      - Prepare for release
         - [x] [[Research] Implement & Track Metrics](https://github.com/department-of-veterans-affairs/va.gov-team/issues/51109)
         - [x] Hold Staging Review    
- **GOAL: Make submission of a travel reimbursement claim easier**
   - **Sub Goal: [Submit Mileage-Only Claim during Check-in](https://github.com/department-of-veterans-affairs/va.gov-team/issues/40265)**
      - Update our tranlations
         - [ ] [[Product] Submit Translations to the State Department](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54029)
      - Address un-handled scenarios
         - [x] [[Design] Create wireframes for can't check you in scenarios](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53582)
         - [x] [[Design] Update wireframes to prioritize info messages (for answering "no" to travel question.)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53461)
         - [x] [[Design] Update wireframes to prioritize info messages (for check-in with no travel questions)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53566)
      - Implement text solution for BTSSS latency    
         - [ ] [[TEXT SOLUTION] [Design] Create Content and Final Wireframes for Text Message Solution](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53704)
         - [ ] [[TEXT SOLUTION] [Content] Write two text messages for claim status](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53567)               
      - Configure metrics
         - [ ] [[Research] Recheck GA Events due to text solution change](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/53966)
- **GOAL: Increase usage of Pre-Check-in & Check-in**
   - **Sub Goal: [Send to Check-in when Pre-Check-in link is accessed inside check-in window](https://app.zenhub.com/workspaces/pci-api-6149f6401b0b3c001219802f/issues/gh/department-of-veterans-affairs/chip/1330)**
      - [ ] [[BE] Modify lorota/service object check_in_data for hand-off](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53984)
      - [ ] [[BE] CHIP/refresh-appointments Error Handling](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53994)
  - **Sub Goal: [Show Clear Message when using an expired link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52392)**
      - [ ] [[FE] New Message for Expired Link for Pre-Check-in](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52492)
      - [ ] [[FE] New Message for Expired Link on Day-of Check-in](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52393)
      - [ ] [[Design] Update Design Artifacts for Release](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52395)
      - [ ] [Release to Production](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52396)
  - **Sub Goal: [Move Action Link on Pre-Check-in Intro Page to increase clicks](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52054)**
      - Solve the issue of "Answer questions" when there are no questions to answer
         - [ ] [[Design] Update text of pre check in action link on introduction page](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/53793)
         - [ ] [Release to Production](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52057)
   - **Sub Goal: [Send Check-in Text 45 Minutes Before Appointment to encourage use](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53560)**
      - Nothing this sprint
   - **Sub Goal: [Unify the Pre-Check-in & Check-in experiences to decrease confusion](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49924)**
      - [ ] [[Design]Create wireframes for app with appointments list](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52486)
      - [x] [[Content] Audit and update Need Help content](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53883)
      - [x] [[Design] [SPIKE] Research CodePen to Determine if we Want to Use it for Prototyping](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53959)
      - [ ] Fill out sitewide IA request
   - **Sub Goal: Analyze current metrics to see what they tell us**
      - [ ] [Research] Analyze GA Metrics
      - [x] [[Research] Analyze VSignals Data](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53651) - rolled over one
      - [x] [[Research] Analyze VSignals Data](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53963) - new one
- **GOAL: Address tech debt**
   - [ ] [[FE] Update "Need help" section in pre-check-in and check-in](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54002)
   - [x] [[FE] Breadcrumb angle bracket is read aloud by Voice Over](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53066)   
   - [x] [[FE] Loading component is read aloud twice by Voice Over](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52509)   
   - [ ] [[FE] [STAGING TOOL] Surface initiate (pre-)checkin errors to end user in the Staging Tool](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52973)
   - [ ] [[FE] [STAGING TOOL] Book appointments directly with VistA instead of via VEText](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53416)
   - **_Optional Tech Debt (these items are not in the current sprint but can be pulled in)_**
      - [ ] [Have an Initial Discussion to Identify Risks & Problems w/ Current Architecture](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54034)
      - [ ] [[FE] Create Proposal for an MVP for a Cross-Product Path Analysis](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54021)
      - [ ] [[FE] [BE] Review Applications & Identify Areas for Improvement](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53713)
