### ISSUE TITLE
Assess VALife FAQs for migration

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#54062]
## Issue Description
The life insurance office created a new legacy page with FAQs about applying for VALife. We need to assess this content and decide how to migrate it to VA.gov.

---
## Tasks
- [ ] Assess content (Laura)
- [ ] Draft new content (Aliyah or Katherine)
- [ ] Review (Laura)
- [ ] Send to SMEs (Laura)
- [ ] Copyedit & publish (Megan)
- [ ] Request redirects (Laura)

## Acceptance Criteria
- [ ] Content is migrated and page is redirected

**Comment by laurwill** [comment]
Update: As a first step here, we adjusted the headers on the VALife page to get the "Apply now" link closer to the top.

**Comment by mistymg** [comment]
Moved to closed but not actually showing up as closed on board.
