### ISSUE TITLE
Audit instances of "senior reviewer" and change to "higher-level reviewer"

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#54063]
## Issue Description
OAR SMEs requested that we change "senior reviewer" to "higher-level reviewer" everywhere across the site. We'll need to do an audit of static pages and coordinate with the team that owns the higher-level reviews online request form. 

We'll want to make these changes everywhere at once, if possible.

---
## Tasks
- [ ] Use audit tool to find static pages
- [ ] Replace term in Drupal
- [ ] Coordinate with product team on form changes
- [ ] Copyedit publish Drupal pages to coincide with tool changes

## Acceptance Criteria
- [ ] Term is replaced across site

**Comment by laurwill** [comment]
Audit found 9 pages where we'll need to change this term:
-[ Decision reviews FAQs](https://www.va.gov/decision-reviews/faq/)
- [Fiduciary claims](https://www.va.gov/decision-reviews/fiduciary-claims/)
- [Insurance claims](https://www.va.gov/decision-reviews/insurance-claims/)
- [What your decision review or appeal status means](https://www.va.gov/resources/what-your-decision-review-or-appeal-status-means/)
- [After you apply for an eligibility determination](https://www.va.gov/burials-memorials/pre-need-eligibility/after-you-apply/)
- [Choosing a decision review option](https://www.va.gov/resources/choosing-a-decision-review-option/)
- [About VA Form 20-0996](https://www.va.gov/find-forms/about-form-20-0996/)
- [Higher-Level Reviews](https://www.va.gov/decision-reviews/higher-level-review/)
- [Decision reviews hub page](https://www.va.gov/decision-reviews/)

**Comment by laurwill** [comment]
Updates:
- Sade from benefits decision reviews team is updating this term in HLR online form
- Misty is updating this term in mobile app

**Comment by katherine-fung** [comment]
I'll check these off as I go: 

- [ ] Decision reviews FAQs
- [x ] Fiduciary claims
- [x ] Insurance claims
- [ ] What your decision review or appeal status means
- [ ] After you apply for an eligibility determination
- [ ] Choosing a decision review option
- [ ] About VA Form 20-0996
- [ ] Higher-Level Reviews
- [ ] Decision reviews hub page

**Comment by katherine-fung** [comment]
Just noting here that I've updated the pages above to replace the phrase "senior reviewer." 

@megzehn - these pages will be ready for copy edit once stakeholders get back to us about larger edits in ticket #44011. 

Decision reviews FAQs
http://preview-prod.vfs.va.gov/preview?nodeId=50010

Fiduciary claims
http://preview-prod.vfs.va.gov/preview?nodeId=3016 

Insurance claims
http://preview-prod.vfs.va.gov/preview?nodeId=3025 

What your decision review or appeal status means
http://preview-prod.vfs.va.gov/preview?nodeId=9626

After you apply for an eligibility determination
http://preview-prod.vfs.va.gov/preview?nodeId=863 

Choosing a decision review option
http://preview-prod.vfs.va.gov/preview?nodeId=23290 

About VA Form 20-0996
http://preview-prod.vfs.va.gov/preview?nodeId=5790 

Higher-Level Reviews
http://preview-prod.vfs.va.gov/preview?nodeId=3003

Decision reviews hub page
http://preview-prod.vfs.va.gov/preview?nodeId=3071

**Comment by megzehn** [comment]
Thanks, @katherine-fung! I reviewed all of these. I'll check them off here as I publish the changes.

- [ ] Decision reviews FAQs
http://preview-prod.vfs.va.gov/preview?nodeId=50010

- [ ] Fiduciary claims
http://preview-prod.vfs.va.gov/preview?nodeId=3016

- [ ] Insurance claims
http://preview-prod.vfs.va.gov/preview?nodeId=3025

- [ ] What your decision review or appeal status means
http://preview-prod.vfs.va.gov/preview?nodeId=9626

- [ ] After you apply for an eligibility determination
http://preview-prod.vfs.va.gov/preview?nodeId=863

- [ ] Choosing a decision review option
http://preview-prod.vfs.va.gov/preview?nodeId=23290

- [ ] About VA Form 20-0996
http://preview-prod.vfs.va.gov/preview?nodeId=5790

- [ ] Higher-Level Reviews
http://preview-prod.vfs.va.gov/preview?nodeId=3003

- [ ] Decision reviews hub page
http://preview-prod.vfs.va.gov/preview?nodeId=3071

**Comment by megzehn** [comment]
@RLHecht these are all published now!

**Comment by RLHecht** [comment]
Thanks! These are all validated as live. Closing!
