### ISSUE TITLE
[CAIA Content Support] Content Style Guide: Add entry about how to use aria labels with extensions in phone number entry

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#54073]
## Issue Description

Laura Flannery opened an intake request for us to add guidance in the content style guide for how to use aria labels with a phone number that has an extension. While the telephone component does this correctly, if an editor needs to manually add and style a phone number in Drupal, there's no currently information in the style guide for including an extension.

The correct aria labeling and background info in the original intake ticket: #54033

## Tasks
- [ ] Update style guide entry (Megan)
- [ ] Review (Beth/Danielle)

## Acceptance Criteria
- [ ] Extensions info is added to style guide
