### ISSUE TITLE
Use GitHub Cloud Runners for Vets API

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#54072]
Our self-hosted runners are painful to maintain with frequent errors (e.g. no space left on device). This prevents development work from continuing and code from deploying.

Vets API does not require VA network access to run its test suite. Previously, Vets API implemented the use of self-hosted runners as they were faster than GitHub's dual-core cloud runners. GitHub now allows us to use 8-core Cloud Runners which are similar in speed to our self-hosted runners.

## Tasks

- [ ] Use GitHub's Cloud Runners
- [ ] Port changes to k8s branch

## AC

- [ ] Vets API's CI (GitHub Actions) is using GitHub's 8-core cloud runners for BRD and EKS CI runs.

**Comment by ericboehs** [comment]
I've got some work done on this [here](https://github.com/department-of-veterans-affairs/vets-api/pull/11872). Bundler isn't being cached but it seems it runs just as fast as standard master builds so caching of bundler can be handled separately.

**Comment by npeterson54** [comment]
Added to sprint to help progress other stories in the sprint

**Comment by ericboehs** [comment]
This is done!
