### ISSUE TITLE
[SPIKE] Design Common Api Interface 

### ISSUE THREAD

**Issue by ahay-agile6** [department-of-veterans-affairs/va.gov-team#54076]
## Issue Description
Right now, there is no easy way to connect to another 3rd-party or in-house Api Provider - i.e. the EVSS API calls are embedded in models.
So, what we want to do is abstract out what services or providers the (for now) Form526 uses.

Notes/Exploration:
- If the model doesn't need to know what "EVSS" is, what does the model need to know about functionality?
- Create a Factory or a way to create different factories to generate which implementation at any time?
- 

---
## Tasks
- [x] Identify a path/endpoint/route as a good candidate to go end-to-end for for rated disabilities endpoint
- [x] Feature toggle/Flipper for the provider?
- [x] Create new unit tests for the abstracted interface
- [ ] Unit test: can we provide an api to the Form526Submission? 
- [x] Any existing unit tests break?

- [x] Seth/Aurora - start transform layer: data structure, see if we can use a generic data structure to return the same eVSS response
- [ ] Cole - start looking into another endpoint that needs migration, BRD is a good candidate. Answer the question (or at least get a good idea): Does this framework work?

## Acceptance Criteria
- [ ] Abstracted out interface between model Form526Submission and api calls for rated disabilities
- [ ] No breaking unit tests (goes without saying, but we need to make sure), i.e. the code is "mergeable" in the vets-api repo? Part of CI
- [ ] Code is merged with main

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
