### ISSUE TITLE
FE COP: Split allow list workflow to separate job schedules

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#54071]
## Issue Description
When the allow list notification was moved to the vfs-all-teams channel and the frequency was reduced, it also reduced the frequency of the publishing of the allow list to confluence. We don't want the publishing frequency reduced as it should be as up-to-date as possible at all times.

---
## Tasks
- [x] Split the publish job from the notification job so they can each have their own schedule for when they run.

## Acceptance Criteria
- [x] Two workflows exist for the allow list
- [x] The publish runs daily M-F
- [x] The notification only runs Monday weekly.
---

**Comment by pjhill** [comment]
@CBonade -- would you please add an estimate and a link to the PR? I believe you stated that the PR is already merged, but just for future reference.

**Comment by pjhill** [comment]
Huzzah!
