### ISSUE TITLE
[FE] 10-10EZ - American Indian question: Disable and remove the American Indian question from all environments

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#54080]
## Background
During a [Bi-weekly Stakeholder meeting in December 2022](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/product/Bi-weekly%20Stakeholder%20Mtg%20notes/12-21-2022%20HEC%20Bi-weekly%20Health%20Care%20app%20update.md), it was mentioned that there was going to be approval to remove the American Indian/Indian Health question from the form (which has been released in November 2022).  

On February 23, 2022, we were notified by Jessica Soza that the HEC team has published an updated 10-10EZ paper form with the American Indian/Indian Health question removed.
>The updated [10-10 EZ](https://www.va.gov/vaforms/medical/pdf/VA_Form_10-10EZ.pdf) and [10-10 EZR](https://www.va.gov/vaforms/medical/pdf/VA%20Form%2010-10EZR.pdf) paper forms have been published.

Confirmed with PO - Patrick Bateman - that the question can now be removed from the Online 10-10EZ form.

## Tasks
- [ ] Disable American Indian/Indian Health question from all environments
- [ ] Confirm successful end-to-end test with ES with question disabled
- [ ] Remove code and content from all environments

## Acceptance Criteria
- American Indian/Indian Health question will be removed from the Online 10-10EZ form

**Comment by longmd** [comment]
@hdjustice , am I good to do this today, or do you want to wait?

**Comment by hdjustice** [comment]
@longmd - Let's wait so we can test it downstream to be sure we don't cause failures.  I am pinging Joshua this afternoon

**Comment by hdjustice** [comment]
Tested end2end with Joshua Faulkner confirming successful receipt
We tested:
- Question disabled and submit
- Question enabled, saved in-progress, returned and submit

Submissions were successful on VA.gov, and received in Enrollment System with no issues. 

We are clear to disable in Production, and work to remove the code from all environments

**Comment by hdjustice** [comment]
Confirmed AIQ has been disabled.  Created ticket #54775 to remove the code from the various repos/locations

**Comment by jessicastump** [comment]
During Figma design file migration this design page was listed as not needing to migrate. Posting an image of what was in the design file for reference here:
<img width="477" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL29TQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--587a15cd94708549f5bb6cd4f5be3fa21301e832/american-indian%7D-REMOVED-022223.jpg" alt="american-indian}-REMOVED-022223.jpg" />
