### ISSUE TITLE
BE | Profile | Contact Info | Remove Email change toggle

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#54082]
## Background
Remove the feature toggle `profile_email_specify_change` from vets-api.

## Tasks
- [x] Remove all references
- [x] Remove feature flag from features.yml

## Acceptance Criteria
- [x] Verify email change sends email

**Comment by tpharrison** [comment]
@BerniXiongA6 @mtcA6 

When a user changes their phone # or address in the profile, an email is sent to the user to notify them that their phone # or address was changed.  The email didn't specify whether the phone # changed was home or mobile or whether the address changed was residential or correspondence.

Last year, we added a feature to include the type of phone # or address that was changed in the email.  [See this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/37483).  The `profile_email_specify` feature flag was created for this feature.  
> When enabled, if a user changes a phone number, the notification email will specify whether the home or mobile phone was changed. For an address change, the notification email will specify whether the residential or correspondence address was changed. 

In Feb, @adamwhitlock1 asked if this feature toggle was still needed.  I didn't think it was needed, so created this ticket to remove it.

I was in the process of removing it when I noticed that the feature flag is not "on" in production.  It is only enabled for myself and the previous PM.  Based on our comments in the ticket, we were ready to turn it on, but never did.

Before I remove this feature flag, I'd like to test this a bit further in production.  Can we coordinate some testing for this before I remove this feature flag?

**Comment by tpharrison** [comment]
@mtcA6 Did we want to have the team test this further in production?

**Comment by mtcA6** [comment]
@tpharrison yea i think we do, sent this in the slack channel for the team.

**Comment by BerniXiongA6** [comment]
Hey @tpharrison I tested this in Production using my A6 email with ID.me login, here's the behavior I received:

- When I updated my mobile phone number, I received an email confirming that a "Phone Number" was updated.
- When I updated my home phone number, I received an email confirming that a "Phone Number" was updated.
- When I updated my mailing address, I received an email confirming that an "Address" was updated.
- When I updated my home address, I received an email confirming that an "Address" was updated.

Not sure whether the confirmation email should be even more explicit saying "home address" as opposed to just "address" or "mobile phone number" vs. "phone number" or whether the above behavior is what we wanted. Hope this feedback helps!

cc: @mtcA6

**Comment by mtcA6** [comment]
@tpharrison given the positive test results from Adam I would say we're good to remove this feature toggle in production

**Comment by tpharrison** [comment]
@mtcA6 Feature toggle is removed in staging.  Verified email notification works.  Will move to production this afternoon.

**Comment by tpharrison** [comment]
Feature toggle removed in production.
