### ISSUE TITLE
Communicate changes made to Survey

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#54081]
## Purpose
This is to create content for and how to share out change communications regarding the change of format for the [quarterly Platform Satisfaction survey](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2194964673/Platform+Satisfaction+Survey). It will include how the experience will differ from the previous quarterly survey, for both VFS users and Platform team members. 

[Change Communication components](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2564587521/Change+Communications+for+Survey+Changes)

## Tasks
- [x] Where to share out (include following channels)
**Slack channels for change announcement to Platform teams**
 -  #platform-service-design
 -  #platform-team
**Slack channels for change announcement to VFS teams**
 -  #vfs-change-announcements

## Acceptance Criteria
- [x] Drafted and reviewed content for sharing
  - [x] Confluence page
  - [x] Condense for Slack
  - [x] Bullet points for slides
- [x] Change communication plan drafted that addresses each item above.
- [x] Coordinate with [Ticket #51989
](https://app.zenhub.com/workspaces/platform-service-design-61bcbaf174a70100154e22e7/issues/gh/department-of-veterans-affairs/va.gov-team/51989)
- [x] changes communicated via Slack

**Comment by steel36** [comment]
Rolling over to next sprint to allow for additional team review, and for changes to be communicated in determined channels.
