### ISSUE TITLE
Update Ruby Gems that have deprecation_toolkit warnings

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#54095]
## Issue Description
A list of Ruby Gems used in vets-api have been identified that have deprecation warnings. Update them.

---
## Tasks
- [ ] Identified Gems have been either updated or forked and updated and no longer have any deprecation warnings

## Acceptance Criteria
- [ ] There are 0 depreciation warnings for Ruby Gems used in vets-api
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by holdenhinkle** [comment]
Gems that need to be updated:
```
/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/bundler/gems/bgs-ext-b173cfba5de3/lib/bgs/services.rb:91::
/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/bundler/gems/bgs-ext-b173cfba5de3/lib/bgs/services.rb:91: 
warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call:
/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/bundler/gems/bgs-ext-b173cfba5de3/lib/bgs/base.rb:28: warning: The called method `initialize' is defined here

/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/actionpack-6.1.7.2/lib/action_dispatch/testing/integration.rb:372::
/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/actionpack-6.1.7.2/lib/action_dispatch/testing/integration.rb:372: 
warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call:  
/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/actionpack-6.1.7.2/lib/action_dispatch/testing/integration.rb:15: warning: The called method `get' is defined here
/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/actionpack-6.1.7.2/lib/action_dispatch/testing/integration.rb:21: warning: The called method `post' is defined here
/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/actionpack-6.1.7.2/lib/action_dispatch/testing/integration.rb:27: warning: The called method `patch' is defined here
/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/actionpack-6.1.7.2/lib/action_dispatch/testing/integration.rb:33: warning: The called method `put' is defined here
/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/actionpack-6.1.7.2/lib/action_dispatch/testing/integration.rb:39: warning: The called method `delete' is defined here

/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/rspec-mocks-3.11.1/lib/rspec/mocks/message_expectation.rb:188::
/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/rspec-mocks-3.11.1/lib/rspec/mocks/message_expectation.rb:188:
warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call:
/Users/holdenhinkle/Documents/Oddball/va_website/vets-api/app/services/sign_in/errors.rb:8: warning: The called method `initialize' is defined here

/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/super_diff-0.9.0/lib/super_diff/object_inspection/inspection_tree_builders/default_object.rb:46::
/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/super_diff-0.9.0/lib/super_diff/object_inspection/inspection_tree_builders/default_object.rb:46:
warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call:
/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/super_diff-0.9.0/lib/super_diff/object_inspection/inspection_tree.rb:16: warning: The called method is defined here

/Users/holdenhinkle/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/forwardable.rb:235::
/Users/holdenhinkle/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/forwardable.rb:235:
warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call:
/Users/holdenhinkle/.rvm/gems/ruby-2.7.6/gems/statsd-instrument-3.5.3/lib/statsd/instrument/client.rb:214: warning: The called method `measure' is defined here
```

**Comment by holdenhinkle** [comment]
`bgs_ext` is updated. PR:

- https://github.com/department-of-veterans-affairs/bgs-ext/pull/80
- https://github.com/department-of-veterans-affairs/bgs-ext/pull/81
- https://github.com/department-of-veterans-affairs/vets-api/pull/11886

**Comment by holdenhinkle** [comment]
Rails PR closed:
> Rails 6.1.Z only supports security issues that is explained in the Maintenance Policy for Ruby on Rails
>
> Let me close this pull request because addressing warnings are not security issues.
FYI Starting from Rails 7.0.0 the line modified in this pull request 594c924 has been removed via f9cc3c8

**Comment by holdenhinkle** [comment]
`rspec-mocks-3.11.1`
The keyword argument deprecation has fixed in [3.11.2 / 2022-10-25](https://github.com/rspec/rspec-mocks/blob/v3.12.3/Changelog.md#3112--2022-10-25)

**Comment by holdenhinkle** [comment]
## Notes

`deprecations/jobs/evss/disability_compensation_form/submit_form8940.yml`

```yaml
---
test_evss/disability_compensation_form/submit_form8940.perform_async_with_a_successful_submission_job_submits_successfully:
- 'DEPRECATION WARNING: VCR: got `Encoding::UndefinedConversionError: "\xE2" from
  ASCII-8BIT to UTF-8` while trying to encode the ASCII-8BIT request body to the original
  body encoding (UTF-8). Consider using the `:preserve_exact_body_bytes` option to
  work around this.

  '
- 'DEPRECATION WARNING: VCR: got `Encoding::UndefinedConversionError: "\xE2" from
  ASCII-8BIT to UTF-8` while trying to encode the ASCII-8BIT request body to the original
  body encoding (UTF-8). Consider using the `:preserve_exact_body_bytes` option to
  work around this.

  '
```

In `spec/jobs/evss/disability_compensation_form/submit_form8940_spec.rb`, l:48

Looks like we'll have to rerecord the cassette? Just guessing...

![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/fddbb092-01aa-4902-ad5b-dac84deb03ae)

**Comment by holdenhinkle** [comment]
PR wip - [fix keyword arg / param deprecations & update rspec and rspec-mocks](https://github.com/department-of-veterans-affairs/vets-api/pull/11905)

Yes, it(^) started out as one thing and ended up being something else. I'll clean it up.

Fixing lots of keyword arg / param deprecations.

I misunderstood the original list I created. There's a lot more work to do than I thought.

**Comment by holdenhinkle** [comment]
Just a quick note. As we've been updating deprecations in vets-api, we've stopped getting warning for some of the Gems, like the warning above for `rspec-mocks`.

I think we should continue handling the deprecations in vets-api then rerun deprecation_toolkit to see if there are any more Gem warnings...
