### ISSUE TITLE
Design | Profile | Logged-in IA research | Review data from call centers and Medallia

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#54094]
## Background

Conduct a review of [call center and Medallia data](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/contact-center/medallia-audits/IA-navigaion.md) as outlined in the [research brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ia-and-navigation/2023-generative-logged-in-research/medallia-call-center-review.md).

To request this data:

- [Request ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=ianMcCullough-ob%2C+ATMiddleton&labels=VSP-contact-center%2Ccc-data-request&template=qualitative-data-request.yml&title=Qualitative+Data+Request)
- (From Josh Kim) As for getting qual data, I recommend reaching out to VEO folk. I know Marlee on VEO trains call center agents. I have her email if you’d like it!

## Tasks
- [x] Request Medallia data ([#54120](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54120))
- [x] Request call center data ([#54121](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54121))
- [x] Review medallia data
- [x] Review call center data
- [x] Draft report
- [x] Have report peer reviewed
- [ ] PO review
- [ ] Add any outstanding questions to user research plan/convo guide
  

## Acceptance Criteria
- [ ] Report complete and questions in the research brief are answered

## Validation
PO review will serve as validation

**Comment by andaleliz** [comment]
@Samara-Strauss I met with Ian today; he reached out after I submitted my request for data.  He said he had been working on a report for Chante and you, but hadn't had a chance to sync with either of you yet on what he pulled.

[Here are his audit results from Medallia](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/contact-center/medallia-audits/IA-navigaion.md), and a [DOMO dashboard for the call center data](https://va-gov.domo.com/page/1363709429).

After reviewing these with him, I think I can answer the [two research questions in the brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ia-and-navigation/2023-generative-logged-in-research/medallia-call-center-review.md#questions-to-answer):

1. The audit data, combined with the Mural board linked in his doc, can give us insights into what people have a hard time finding. I think the sample comments in the Mural board will be especially helpful there.
2. The call center data and the audit data combined, can give us an idea of where people are on the site when they start to have trouble.

I can also do a little more digging into something that's not in either link he shared yet. He ran another report based on people using the Feedback button on URLs having the `?postLogin=true` parameter (which is present immediately after signing in). He filtered that report with the keyword "navigation", and there are 1800 responses to look through. I'm thinking that could be a good route to get insights into where people are struggling immediately after signing in.

I realize that I created this ticket before talking with you, and maybe I was never supposed to make these requests at all! But now that I've connected the dots from Ian, and have this much to go on - is this what you wanted me to do for this research activity? 

Please let me know how this all sounds, and how you'd like to proceed. I've asked Ian to hold off on further work for the two requests I submitted until he hears back from me.

CC @BerniXiongA6 for awareness.

**Comment by Samara-Strauss** [comment]
> I realize that I created this ticket before talking with you, and maybe I was never supposed to make these requests at all! But now that I've connected the dots from Ian, and have this much to go on - is this what you wanted me to do for this research activity?

Thanks for so thoroughly reviewing this data, Liz! I think I'm unsure on what you see as next steps here. Besides reviewing the data, was there something else you planned on doing?

**Comment by andaleliz** [comment]
@Samara-Strauss nope, that was my next step, as long as there aren't any other data points I need Ian to pull for me. I just didn't realize he had already been working on the request, and so wasn't sure whether or not there was more to do or if his work was setting me up for mine :) 

As long as it's the latter, I'm ready to rock and move forward with the data I have from him.

**Comment by Samara-Strauss** [comment]
Great! Yeah, I would say nothing else for you to do re: call center or Medallia besides being familiar with Ian's findings. Thank you!!

**Comment by andaleliz** [comment]
Hi @Samara-Strauss! Here's [my report for the qualitative data analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ia-and-navigation/2023-generative-logged-in-research/qualitative-data-findings.md).  I look forward to your feedback - I'm open to any updates or areas you want me to dig further.

**Comment by andaleliz** [comment]
@mnorthuis and @clantosswett tagging you in for awareness, meant to do that earlier.

**Comment by Samara-Strauss** [comment]
@andaleliz this is my extrapolation from the research:

- We saw the most comments around issues with finding health care and claims information. This is likely because of two things: (1) These are the most popular tasks, so they'll yield the most comments, and (2) eBenefits and MHV are  still not fully integrated into VA.gov.
- Additionally, while not totally the focus of this work, we can't ignore what a big issue login causes with navigation.

Is that accurate? Even though these are known issues, I think this is still good that we documented this, and supports that we need to do some user research to get insights into more specific flows, since the survey feedback naturally leaves out some details.

**Comment by andaleliz** [comment]
@Samara-Strauss yes, those are both accurate, and I agree with you that it's good to document it. It's nice to not have any unexpected, unpleasant surprises coming out of the qualitative research.

**Comment by Samara-Strauss** [comment]
I think we are good to close this out! Great work, Liz.

**Comment by andaleliz** [comment]
Excellent, I'll close it now. Thank you Samara!
