### ISSUE TITLE
Design | Profile | Logged-in IA Research| Create research plan

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#54092]
## Background

As part of our larger [logged-in IA research initiative](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/ia-and-navigation/2023-generative-logged-in-research#readme), we need to user research to answer questions we haven't answered in other parts of our research, and to gain additional insight into problems and expectations people have with navigating VA.gov while logged in.

This ticket covers the creation of a research plan for this work.

## Tasks
- [x] Create research plan
- [x] Have plan peer reviewed
- [x] PO review
  

## Acceptance Criteria
- [x] Research plan is complete and we can start on conversation guide

## Validation
- PO review will serve as validation

**Comment by Samara-Strauss** [comment]
@andaleliz [here are my preliminary notes on things to consider for the research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ia-and-navigation/2023-generative-logged-in-research/user-research-guidance.md). I've asked a few other OCTO folks to look at it, too. I am hoping to be released from the hospital today, so if I'm home tomorrow (Thursday), let's find a time to chat.

**Comment by Samara-Strauss** [comment]
@mnorthuis @clantosswett tagging you on this ticket so you're aware that this where Liz will be working on the user research plan.

**Comment by andaleliz** [comment]
@Samara-Strauss just FYI I moved the preliminary notes doc into a directory so all the user research docs can be together. It lives here now https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ia-and-navigation/2023-generative-logged-in-research/2023-logged-in-user-interviews/user-research-guidance.md

**Comment by andaleliz** [comment]
@Samara-Strauss, I'll be including Chante and Mikki as observers in this research. I'm thinking I should include Dave, Lauren, and Danielle. Anyone else?

I think we may need to have sign-up slots given the number of stakeholders + our regular team members, who I'm sure will be interested to attend.

**Comment by Samara-Strauss** [comment]
I don't think you need to include Dave, Lauren, and Danielle, as they are swamped on other things and probably don't have bandwidth. But maybe Robyn and Cindy as optional and as representatives from those teams?

**Comment by Samara-Strauss** [comment]
@andaleliz one thing I was just thinking about -- for one of the tasks/research objectives, I'm curious if people know where they should go if they need help with something. Since we don't really have a "help center" or a cohesive place to get help, my hypothesis is people won't know how to get help if they need it.

**Comment by andaleliz** [comment]
@Samara-Strauss that's a good call out. We do have the Resources and Support section, but it's not intuitive IMO. I added that as a research question and hypothesis. [The research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ia-and-navigation/2023-generative-logged-in-research/2023-logged-in-user-interviews/research-plan.md) is now ready for your review. I've got a couple TBDs in there for a11y specialists.

**Comment by Samara-Strauss** [comment]
This looks great to me. I have the smallest of notes:

> If they can’t find what they need, where do they go for help?

I think we're interested in two separate things:

- If people can't find what they need, what do they do?
- If people are having trouble with the website/information is inaccurate/they need help with something or have questions in general, what do they do?

When you're ready, we can ask for feedback from various OCTO stakeholders to see if they would like to review and if they have any feedback.

**Comment by andaleliz** [comment]
Hi @clantosswett, @coultonbunney-usds, @mnorthuis, @lalexanderson-dsva, [the research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ia-and-navigation/2023-generative-logged-in-research/2023-logged-in-user-interviews/research-plan.md) for the logged-in IA and nav user interviews is complete, and it'd be great to get your thoughts on it if you have bandwidth to review.

Is it do-able to provide feedback by Wednesday?  You can provide comments in this GitHub ticket.

I'll work on the conversation guide in the meantime, and I hope to submit to Shane to kick off the recruiting process by Friday this week. Thanks!

**Comment by Samara-Strauss** [comment]
@andaleliz I also gave this a bump in one of our OCTO-only channels. If we don't hear back from anyone by EOD tomorrow, I think we are good to move forward and close this out.

**Comment by coultonbunney-usds** [comment]
@andaleliz thanks! I think this looks great. Just took a look and have a few questions/comments. 

1. What do you mean by, "How do they do this if they can’t use the homepage/My VA links?"
2. I am curious to better understand the expectations and mental model of logged in users. Do you think your current research questions account for the following? 
   1. Once a user logs in, do they expect to still find information that is not personalized to them, or do they expect to be navigated to a separate portal experience?  E.g. the information hubs
   1. Does a user differentiate "logged in / authenticated" parts of the website, and "unauthenticated" parts of the website? What is the difference to them, if any? Does the current experience cause confusion?
   1. When a user wants to review information personalized to them, do they use the mega menu to find that information? Or do they go directly to the MyVA page? 

I'm thinking of this mainly from a _should we more clearly separate the logged in experience from the rest of the VA.gov content_ perspective. You get at this with your hypothesis, "People’s expectations of a logged-in navigation will not be much different than what we have today." 

Thank you for letting me provide a few thoughts.

**Comment by andaleliz** [comment]
@coultonbunney-usds these are excellent questions! 

>What do you mean by, "How do they do this if they can’t use the homepage/My VA links?"

We're interested in learning how people navigate to tasks if they're not linked from the homepage or My VA. The top tasks have links there, but not all tasks do. I updated my question to "How do they navigate without relying on homepage/My VA links?" which I hope is more clear. Please let me know if not.

>I am curious to better understand the expectations and mental model of logged in users. Do you think your current research questions account for the following?...

I'm curious to better understand this too. I think the plan _starts_ to get at those questions but I think it would be better to be more explicit about it. I'll revise it later this afternoon.  Thanks so much for the feedback!

**Comment by andaleliz** [comment]
@coultonbunney-usds I've updated the research plan, and I'll be sure the conversation guide includes the points you raised too.

Would you like me to add you to the list of observers for the research study?

**Comment by andaleliz** [comment]
No further feedback received; closing out.
