### ISSUE TITLE
[FSR] Update OMB information

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#54096]
## Issue Description
OMB information for FSR needs to be updated with correct code and expiration date
Date: `2023-10-31`
OMB: `2900-0165`
https://omb.report/omb/2900-0165 

---
## Tasks
- [ ] Update OMB information for FSR

## Acceptance Criteria
- [ ] OMB info has been updated
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
