### ISSUE TITLE
Request current version of product at Kickoff

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#54091]
## User Story
As a Governance team member, I want to see what the current state of the product looks like throughout the products journey through the Collaboration Cycle so that I can compare changes and provide appropriate feedback. 

Assignee: @it-harrison 
Peer Reviewer:  @CherylEvans 

## Description
One of the findings of the Midpoint Review research was that we often have to ask VFS teams to share the current version of their product before they begin making their changes. Instead of asking for a current version at Midpoint Review, Governance team members agreed that it would be helpful to have this throughout the products journey in the Collab Cycle and it should be available to us at the Kickoff.

The purpose of this ticket is to modify our Collaboration Cycle Request yaml template to request links, designs, and/or screenshots of the current, change-free version of the product.

## Impacted Artifacts
[Collaboration Cycle Request yaml template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-review%2Ccollaboration-cycle%2CCC-Request&template=collaboration-cycle-request.yml&title=Collaboration+Cycle+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D)
Collaboration Cycle Kickoff - Moderator Responsibilities

## Tasks
- [x] In the Artifacts section of the yaml template, add a new checkbox for requesting links, screenshots, images, designs, etc. of the as-is version of the product
   - wordsmith here. Maybe work with Cheryl on this as I'm not sure exactly what we want to call this.
   - does not need to be a required questions for the VFS team to answer (at least for now)
- [x] Once the change is implemented, review the Moderator Responsibilities doc and make necessary for Step 4, if needed

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] The as-is version of the VFS product is shared early on in the Collaboration Cycle journey

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
@shiragoodman I will have this finished by EOD (3/14)

**Comment by it-harrison** [comment]
Hi @CherylEvans you can review the [updated template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/collaboration-cycle-request.yml). I didn't make changes to the Moderator Responsibilities document because the checkbox is for VFS teams, not us.

**Comment by CherylEvans** [comment]
@it-harrison I recommend these changes to the Artifacts checkbox: "I have provided all relevant and up-to-date links, screenshots, images, designs, etc., of the as-is version of the product."
I added the needed punctuation and additional verbiage to satisfy the User Story. :-)
@shiragoodman @it-harrison Can either of you clarify the second task regarding Step 4?  I'm unsure what this means and how it relates to the checkbox.  I understand that the checkbox is for the VFS team, but want to make sure I'm not missing something that needs attention.  Thank you!

**Comment by CherylEvans** [comment]
@it-harrison I recommend these changes to the Artifacts checkbox: "I have provided all relevant and up-to-date links, screenshots, images, designs, etc., of the as-is version of the product."
I added the needed punctuation and additional verbiage to satisfy the User Story. :-)
@shiragoodman @it-harrison Can either of you clarify the second task regarding Step 4?  I'm unsure what this means and how it relates to the checkbox.  I understand that the checkbox is for the VFS team, but want to make sure I'm not missing something that needs attention.  Thank you!
