### ISSUE TITLE
Gather past Midpoint Review artifact types

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#54090]
## User Story
As a Governance team member, I want to show VFS teams examples of different types of artifacts shared previously at Midpoint Review so that VFS teams scheduling Midpoint Reviews can share appropriate artifacts.

Assignee:
Peer Reviewer:

## Description
In the Midpoint Review touchpoint page and within the Collab Cycle Request ticket, Governance team currently requests the following artifacts:

- Product outline
- Finalized design prototype or mockup
- Research plan
- Conversation guide
- Content artifacts: GitHub ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
- IA artifacts: Please include a link to any Sitewide Content & IA feedback you received, including an IA review document or intake form.

VFS teams interpret this as an inclusive list, and don't share with us other artifacts that would be helpful for Governance team to see.

The purpose of this ticket is to review previously completed Midpoint Reviews to see what other artifacts have been shared and have been helpful for Governance team. The purpose of this ticket is to compile a list (with or without examples) of other artifacts that we may also want to look at.

In a later ticket, Governance team will potentially update the VFS-Facing guidance to share this list.

## Impacted Artifacts
N/A

## Tasks
- [ ] Review previously completed Midpoint Reviews (maybe Design Intents too) and capture the artifacts shared that were helpful for Governance team.
 - Organize the list based on artifact type (prototypes, mobile, flows, code, etc)

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have compiled a list of artifacts that Governance team has used to evaluate VFS teams at the Midpoint Review

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
question for team - do we want _actual examples_ of artifacts or will titles suffice?

**Comment by sterkenburgsara** [comment]
@shiragoodman still working on this one & it will move into the next sprint. Regarding your question above in an earlier comment, I think titles should suffice? But I can poll the team before this ticket gets closed to get a better pulse on what everyone thinks about that.

**Comment by sterkenburgsara** [comment]
Updated list with team feedback incorporated: 
* Finalized design prototype (desktop and mobile, with accessibility annotations)
* Wireframes (with all possible user paths and error states)
* Research plan
* Conversation guide
* Content artifacts: link to any Sitewide CAIA feedback you received, including updates to static page entry points to your product (if applicable) or plain language modifications
* IA artifacts: link to any Sitewide CAIA feedback you received, including an IA review document or intake form

Ready for your review/feedback on this list @briandeconinck :-)

**Comment by sterkenburgsara** [comment]
@briandeconinck poking you for review again so I can get this blocker out of the way for some other tickets. Ty!

**Comment by briandeconinck** [comment]
@sterkenburgsara Sorry! This list looks great, and is ready to go.

**Comment by sterkenburgsara** [comment]
@briandeconinck no worries. Thank you!
