### ISSUE TITLE
Flipper admin user management

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#54110]
### Summary
We need a process for managing the flipper admin users in [config/settings.yml](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/settings.yml#L834).

user management ideas:
One idea is to add a task to the [offboarding document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/offboarding-request.md) + instructions in the [Confluence doc](https://vfs.atlassian.net/wiki/spaces/OT/pages/2097545323/Offboard+Team+Member). This seems like a tedious, ongoing task. A github action could be written to make this as automated as possible. Alternatively, could we use github teams to manage this access. And then when they leave the org, their access to flipper is automatically revoked. 

>  Alternatively, could we use github teams to manage this access. 
This seems like the direction platform is going in. Let's go with this approach.

### Tasks
- [ ] ~~Audit the users in [config/settings.yml](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/settings.yml#L834) for accuracy. If people have left the org, remove them from the list. (One way of checking is to search for the user's email in [the offboarding issues](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+label%3AOffboarding).) (Trevor thinks everyone from `gcio` is gone.)~~
- [x] Come up with a way to revoke access when someone leaves the org. 
  * NOTE: Happens automatically - user gets removed from GH Teams when they're removed from the org

**Comment by holdenhinkle** [comment]
@LindseySaari just implemented this for Sidekiq recently. Feel free to check in with her about how she did it.

**Comment by holdenhinkle** [comment]
@LindseySaari just implemented this for Sidekiq recently. Feel free to check in with her about how she did it.

**Comment by ryan-mcneil** [comment]
Adding a few things for reference:

Lindsey's [recent PR](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53420)

Rebecca's notes (from Lindsey convo) on github team ID:
```
Retrieve the ID of a github team
Use the GH API to make a call to retrieve the team_id 
curl -H "Authorization: token pat_goes_here" https://api.github.com/orgs/department-of-veterans-affairs/teams/team_name_here
```

**Comment by ryan-mcneil** [comment]
@rmtolmach @holdenhinkle or anyone that has input

Looking at what's currently in place, there seems to be 3 different levels based on the spec, though the tests aren't very explicit about the differences between an unauthenticated (or unauthorized) user and an L0A1 user. The specs validate:

`unauthenticated` - Can access (GET) `/flipper/features`, but cannot toggle (send POST to `/flipper/features/test_feature/boolean`)
`authenticated admin with LOA1 access` - cannot toggle (send POST to `/flipper/features/test_feature/boolean` ) 
`authenticated admin with LOA3 access` - can access and toggle.

So it seems like there's really only 2 layers, which we can use a single [set] of github teams to manage, as being on a team gives GET and POST privileges, while not being a member removes the ability to POST/toggle. Does this seem reasonable?

**Comment by ericboehs** [comment]
> being on a team gives GET and POST privileges, while not being a member removes the ability to POST/toggle. Does this seem reasonable?

@ryan-mcneil Yes. That seems reasonable.

**Comment by ryan-mcneil** [comment]
Update:

WIP PR's up for [vets-api](https://github.com/department-of-veterans-affairs/vets-api/pull/12643), and for manifest values in [dev](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1907) and [staging](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1910)

TODO (after I get this handshake working properly
- [ ] Create GIthub Oauth app to retrieve team info
  - [ ] Add secrets to Parameter Store
- [ ] Create Github Teams for each Env
  - [ ] Update Manifest PRs with Team ID
- [ ] Create PRs for Sandbox and Prod (Manifest)
- [ ] Update secrets/values in `devops` repo (is this still needed?)

**Comment by ryan-mcneil** [comment]
I got back to this and made some good progress. I'm successfully retrieving the github user for us to use in confirmation of GH team membership. My focus had been on this piece, but now that I peeled back another layer, I have more questions. They are mostly regarding how many layers of authorization we want/need. We currently require both ID.me validation and being on the hardcoded list of admins. While the hardcoded list was the initial target of this ticket, I'm wondering if we need the other ID.me check? If GH team membership is good enough for granting access to Prod terminals/data, I feel like it should be good enough for giving devs the ability to enable feature flags.

So, I have two proposed ways forward

1. A less invasive approach would be keeping the ID.me stuff in tact, and just replacing the admin list check with a session check, which would spin off the GH integration if the session was missing/invalid/expired.
The UX would change slightly:
* User would first need to sign in, as usual
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/41602677/32af72f9-818e-4861-982a-456c81922cbd)
* Upon reaching this page, I would have already updated the session with GH user info, so I would then check to see if they had GH team membership (and probably assign to a view variable).
* I'd add an error/info message that would appear in the case that they weren't authorized that would direct them to where they needed to go.

2. OR we can tear all this ID.me stuff out, and simplify it. It would take a little more work, but in the end be much cleaner and easier to understand
A few things to note:
* We currently dig through a JWT in the request to get the current user, and their email, that we then use for logging purposes. If we go through GH, we'll only have their GH user, not the one associated with their platform user. Is that ok? (I'm not 100% convinced this logging works anyway... I'll investigate this more)
* I think the main reason we were querying for the current user was to check their `loa3`, but according to a few comments above, we don't need to consider that anymore with the GH team method.

Thoughts? Is there anything I'm not considering?

**Comment by ryan-mcneil** [comment]
Merged PRs adding new params to PS/Manifests:
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1907
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1910
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2101
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2105

**Comment by ryan-mcneil** [comment]
[Final PR](https://github.com/department-of-veterans-affairs/vets-api/pull/13563) after requiring revert. Links to PR with more details
