### ISSUE TITLE
[EOAS] Preneeds submissions fail when user is not logged in

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#54132]
## Background
When submitting a filled out Prneeds form as a unauthenticated user, the submission fails with an error. Entering the same information as a logged in user results in a successful submission.

## Discussion
* The error details in Sentry seem to indicate that this might be an error coming back from EOAS, as opposed to an error happening in vets-api
* We get the same error when submitting with or without attachments
    * There have been issues in the past with submissions erroring when submitted with attachments, but submitting successfully when submitted without any attachments 

## Context
[Sentry Issue](http://sentry.vfs.va.gov/organizations/vsp/issues/185501/?environment=staging&project=3&query=is%3Aunresolved)

Error from Sentry link above
```
Unmapped VA900 (Backend Response: { status: 500, message: <?xml version="1.0" encoding="UTF-8"?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns0:Fault xmlns:ns0="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://www.w3.org/2003/05/soap-envelope"><faultcode>ns0:Server</faultcode><faultstring>Error committing transaction:</faultstring></ns0:Fault></S:Body></S:Envelope>) }
```

## Screenshots
<img width="640" alt="Screenshot 2023-02-24 at 10 19 24 AM" src="https://user-images.githubusercontent.com/13838621/221230999-2e897d27-674a-458c-83d7-610718fb0dd6.png">

## Tasks
- [ ] Test that this is happening in staging
- [ ] Put together a payload to send to EOAS that reproduces this error

## Acceptance Criteria
- [ ] Error has been reproduced in staging
- [ ] Submission XML has been sent to the EOAS team

**Comment by jacobworrell** [comment]
We could not reproduce the error, but we did meet with EOAS to bring this issue to resolution. Closing ticket.
