### ISSUE TITLE
Clean up: Remove unused BigQuery settings from AWS Parameter Store

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#54135]
## Issue Description
A feature in vets-api that hit BigQuery's api was recently removed from vets-api (the feature wasTUD-related).

Remove unused BigQuery settings from the AWS Parameter Store as part of clean up.

---
## Tasks
- [x] Make list of BigQuery settings that are safe to remove from AWS

## Acceptance Criteria
- [x] Remove the settings
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by holdenhinkle** [comment]
Spreadsheet listing settings, date create, who created them, repos they're used in, whether or not they can be deleted - https://docs.google.com/spreadsheets/d/1Nt_FOQxIeCDE_b9RI-INeiBQIoUp09Cr5QIChz7UBM4/edit?usp=sharing

The following settings are safe to delete:

- `/dsva-vagov/testing-team/bigquery_service_private_key`
- `/dsva-vagov/testing-team/bigquery_service_client_id`
- `/dsva-vagov/testing-team/bigquery_service_client_email`
- `/dsva-vagov/testing-team/bigquery_service_private_key_id`

**Comment by holdenhinkle** [comment]
The settings listed above have been deleted.
