### ISSUE TITLE
[A11y Design Review]: MHV Lab and Test Results

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#54131]
### Auditor(s)

sara-amanda

### Automated

- [ ] Run axe checks on every page or unique state (required)
- [ ] Run WAVE on every page if time allows. WAVE is more visual than axe or axe-coconut, but offers some excellent ways to identify nested headings and HTML5 landmark tags.

### Manual

- [ ] Color contrast checks (recommend using whocanuse.com for beyond compliance reports)
- [ ] Color blindness checks
- [ ] Zoom layouts to 400% and inspect them for readability. If layouts break at 400%, I will start reducing them until they become stable, and log the zoom ratio when things started breaking.
- [ ] Keyboard navigation

### Screen Reader

- [ ] Firefox and NVDA
- [ ] Edge and JAWS
- [ ] iOS Safari and VoiceOver (Mobile)
- [ ] Safari and Voiceover (Desktop)
- [ ] Chrome and Talkback

### Staging or Production Link

None

### Prototype Link

[Link to MHV prototype](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/p/0326DA17-53AD-4366-86B4-EC15B66FC582/canvas#Version)

### Test Users

```bash
--
```

**Comment by sara-amanda** [comment]
## CAIA New Related Ticket

### Related Ticket/Epic
[MHV Accessibility Patterns Consolidation for Midpoint #56578](https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/56578)

**Comment by SarahKay8** [comment]
HI @coultonbunney-usds! May I have an updated url to the MHV Lab and Test Results prototype. Getting an error on canvas

**Comment by coforma-terry** [comment]
Hey @alexiawunder - just following up - dis there an updated link for SK for the Lab Test Results prototype?
Thanks!

**Comment by alexiawunder** [comment]
Hi @SarahKay8 and @coforma-terry ! Thank you for your patience. I updated the links in the ticket. These are the updated prototypes: [mobile](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/prototype/a/A4F3BED9-A319-442F-9A8C-7105FB7E01AB) | [desktop](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/prototype/a/E9F3F0B1-5C09-4E1D-8659-4822D08164CE)

**Comment by SarahKay8** [comment]
Hey @alexiawunder I have no feedback to add on this landing page but I thought it might be useful to specify the tool in the H2. "What can you do in our MyHealthevet Medical Records tool" However, this is more of a content discussion. Please close out once reviewed.

**Comment by RLHecht** [comment]
Closing this ticket. Please reopen if there are any questions. We can open a new ticket for accessibility work for staging.
