### ISSUE TITLE
[DD][EKS] Add OOM & CPU Throttle for vets-api dashboard

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#54142]
## Description

Recommendation given. I think that is great information to have

## Tasks
- [x] Add CPU Throttle information 
- [x] Add OOM information
- [x] Part of IaC

## Acceptance Criteria
- [x] Dashboard reflects accordingly

**Comment by npeterson54** [comment]
Adding into sprint

**Comment by oseasmoran73** [comment]
@npeterson54 IaC has been merged and dashboard reflects accordingly. Closing this ticket out as it is completed and doesnt need extensive review (it is under `EKS` group if you wish to verify)

Closing ticket. Please feel free to reopen as needed
