### ISSUE TITLE
Update Deployment Status When a Preview Environment Expires

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#54159]
## Issue Description

When a preview environment expires, we need to update the deployment status endpoint to a `closed` status.

## Tasks
- [ ] Determine an event that can trigger this automation
- [ ] Describe a method by which we can use the event to update the deployment status of a preview environment is removed
- [ ] Implement the method by which we can update the deployment status

## Acceptance Criteria
- [ ] When a preview environment reaches the end of its life for any reason, the deployment status for that preview environment updates to closed in relevant PRs
