### ISSUE TITLE
Support ESECC Approval Process (Sprint 21)

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#54150]
## Issue Description
In order to be approved to get access to use preview.va.gov for preview environments, we have submitted a request and are working through the ESECC approval process - as of Sprint 21, we have received 2 levels of approvals and believe there are two more remaining.

These tasks are updated as new information surfaces since we do not have a clear understanding of the process and subsequent steps in advance, but only as additional info is requested.

---
## Tasks
- [ ] Continue to check/review the submitted request to determine if additional action is needed (should be checked daily)
- [ ] NEW 2/16 - Information was requested from ESECC team:
-- [ ] Site needs to be indicated
-- [ ] www URL registered must be https
-- [ ] WASA finding risk must have an AO-approved POAM, PTA required

## Acceptance Criteria
- [ ] We have followed up with the request and have logged any requested items
- [ ] Any requested items have been delivered... OR
-- [ ] Have been carried over to a ticket for the following sprint
