### ISSUE TITLE
BRD Deprecation: Alerts! Prometheus, Pagerduty, Datadog

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#54162]
Any Prometheus, Pagerduty, Datadog alerts for BRD server and worker

Note: Some of these alerts are standard and one specific app can’t be removed

Tasks

- [x] discovery to understand what all the alerts are in dev? have any alerts already been migrated?
- [x]  make note of important things for higher environments
**pending discovery, might need to break up the ticket (could be one ticket per alert that needs to be migrated)
- [x] migrate current alerts to datadog (if they are applicable)

POST Tasks
- [ ] Ensure all alerts are working properly
- [x] Ensure all alerts have the correct calculations and filters

**Comment by laineymajor** [comment]
@rmtolmach @considerable to meet today to split up tickets for this sprint.

**Comment by rmtolmach** [comment]
Issues nested in this Epic have been divided between Igor and me.

**Comment by rmtolmach** [comment]
Datadog things from Tech Team 2:
- Kubernetes Cluster Overview Dashboard](https://vagov.ddog-gov.com/dash/integration/349/kubernetes-cluster-overview-dashboard?from_ts=1678731029759&to_ts=1678817429759&live=true)
- [Platform monitors and alerts](https://vagov.ddog-gov.com/dashboard/9dk-y7n-6vf/platform-monitors-alerts?from_ts=1678802960132&to_ts=1678817360132&live=false&tile_focus=8958145257280952)

**Comment by LindseySaari** [comment]
Should we make an alert for when the sidekiq queue is too high (I mean the HPA should take care of this.. but incase it fails) just a thought.

**Comment by rmtolmach** [comment]
@LindseySaari I think that will be handled in #54209.

End of sprint update:
None of these tickets were started this sprint. Priority was support (certs!), #54219 and #52433.

**Comment by laineymajor** [comment]
Is there any overlap here with Kyle's team? Any new tickets we need to add?
We will circle back to this!

**Comment by LindseySaari** [comment]
Alerts work has not been started as of yet

**Comment by laineymajor** [comment]
@rmtolmach any progress on this to note? Please update

**Comment by rmtolmach** [comment]
No work has been done on these. Priority has load testing and doc updates
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/54571
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/54225

**Comment by laineymajor** [comment]
Moving to next sprint as other migration work took priority.

**Comment by rmtolmach** [comment]
We have EKS alerts for:
- pods down
- db migrate failing
- a container running out of memory
- pod restarting
- pod CPU throttling
- external secrets failing to sync

we're concerned about startup and are looking for an alert to cover that scenario (#54254)

**Comment by laineymajor** [comment]
Near complete.
This ticket will be reprioritized around the time TT1 reaches 100% migration.

**Comment by laineymajor** [comment]
Updated the sprint assignment as we cannot complete the final ticket for this epic until the migration is more stable.

**Comment by RachalCassity** [comment]
Added POST Tasks (4/26)

**Comment by RachalCassity** [comment]
Updated alerts in PR

**Comment by RachalCassity** [comment]
PR in review

**Comment by laineymajor** [comment]
@RachalCassity what team are we waiting on for this review?

**Comment by laineymajor** [comment]
Closing this epic as we are only awaiting one review and it's accounted for in #54252
