### ISSUE TITLE
TEMPLATE

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#54164]
**Problem Statement**
_WHO_
_WHAT_
_WHAT FOR_
_WHERE_

**Issue Description**
_What details are necessary for understanding the specific work or request tracked by this issue?_
_Additional documentation and/or slack threads linked here_

---
**Tasks**
- [ ] _What work is necessary for this story to be completed?_

**Acceptance Criteria**
- [ ] _What will be created or happen as a result of this story?_

**What needs to be validated?**
- [ ] The ticket is complete
- [ ] Things are working as expected (reviewed in env where it's intended to be used)
