### ISSUE TITLE
Migrate eVSS calls to rated disabilities functionality (vets-api /rated_disabilities) 

### ISSUE THREAD

**Issue by ahay-agile6** [department-of-veterans-affairs/va.gov-team#54161]
## Issue Description
The eVSS is being deprecated and the vets-api utilizes these services to retrieve and post data.
One of these services is the Disability Rating service that retrieves the rating per contention.
This eVSS rated disabilities endpoint is being sunsetted with the eVSS in October.

Sooooo we need to migrate any calls to the eVSS rated disabilities endpoint to the Lighthouse version.

---
## Tasks
- [ ] Identify Lighthouse migration endpoint - what is the endpoint in existence in LH that replaces this service?
- [ ] Audit all calls to eVSS services within the functionality
- [ ] create (a) provider(s) - evss and Lighthouse
- [ ] create (a) service(s) - evss and Lighthouse
- [ ] Authentication?
- [ ] Create Response object - what data field(s) are being sent and received from the eVSS endpoint by the 526 form?
- [ ] Find where functionality is being utilized in vets-website and use that place to test new api provider - can form 526 switch to this LH endpoint without changes for this service? what data field(s) are being sent and received from the new LD endpoint?

## Acceptance Criteria
- [ ] Form 526: no changes to the list of rated disabilities on the frontend 
- [ ] Maintain test coverage?
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
