### ISSUE TITLE
MHV on VA.gov: Landing Page MVP: Usability testing conversation guide, dev & pilot

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#54178]
## Issue Description
**What needs to be done?**
We will need to design a data collection instrument. Best guess at this point is a conversation guide but TBD based on research questions and approach. 

**Why does this need to be done?**
To guide collection of data to answer the research questions. 

---
## Tasks
- [x] Create data collection instrument
- [x] Receive feedback on instrument and refine
- [x] Test data collection instrument in pilot; refine instrument as necessary

## Acceptance Criteria
- [x] A final data collection instrument that has incorporate feedback from key stakeholders and been tested with a proxy participant for the intended audience
- [x] Instrument has been submitted to research repo with the research plan; does not need to have been tested prior to submission

**Comment by rbsingleton** [comment]
[Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/research/2023-03-Landing-Page-User-Research/2023-03-conversation-guide.md)

**Comment by rbsingleton** [comment]
Pilot session scheduled with Angela Fowler for 3/20.

**Comment by rbsingleton** [comment]
Pilot session completed.
