### ISSUE TITLE
MHV on VA.gov: Landing Page MVP: Usability research plan

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#54179]
## Issue Description
**What needs to be done?**
We need to create a plan that explains what we want to learn (research questions) and how we plan to learn it (research approach and data collection instruments). 

**Why does it need to be done?**
To reflect upon and align our team around the best methods to answer our research questions. 

---
## Tasks
- [x] Write a research plan using research template
- [x] Submit plan to research repo

## Acceptance Criteria
- [x] Final research plan
- [x] Ticket in research repo

**Comment by rbsingleton** [comment]
[Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/research/2023-03-Landing-Page-User-Research/2023-03-research-plan.md)

[Ticket for research plan](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/243) - approved 3/13
