### ISSUE TITLE
MHV on VA.gov: Landing Page MVP: Partner with Perigean to recruit usability testing participants

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#54180]
## Issue Description
**What needs to be done?**
We need to provide the information Perigean needs to recruit participants with relevant characteristics for our study. 

**Why does this need to be done?**
Perigean is responsible for all recruitment but needs to know exactly what we're looking for in order to find us participants that will provide us with the best information. 

---
## Tasks
- [x] Identify the most important characteristics for our sample - document in research plan
- [x] Complete a recruitment ticket
- [x] If necessary, complete a kickoff meeting with Perigean to minimize confusion or errors

## Acceptance Criteria
- [ ] When a sample has been recruited and sufficient data has been collection

**Comment by rbsingleton** [comment]
Had to schedule non-MHV users for last couple days of data collection as they were overlooked in original sample.
