### ISSUE TITLE
Show team how to deprecate GitHub files

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#54201]
## Issue Description
Specific Platform support pages still exist on GitHub, specifically working-with-vsp, as well as many others. These pages don't have a deprecation notice and it's very likely that many are out of date and no longer relevant. However, they are still being found by VFS team members and it's possible they could be interpreted as valid guidance. We need to ensure all pages that should be deprecated should have a message that points them to the Platform website, as their source of truth.

---
## Tasks
- [x] Schedule team meeting / **Monday, June 5 @ 10:30am**
- [x] Share the spreadsheet with team
- [x] Share the message we will add to GitHub files
- [x] Show them step-by-step how to add a message to a GitHub file.

## Acceptance Criteria
- [x] Team members will know how to add a deprecation message to GitHub files

- [x] Each person will know which URLs they are responsible for deprecating

**Comment by vbellissimo** [comment]
This is going to have to be pushed back to the backlog to better align to when the work is starting. 2 team members will be out for a week next sprint.
