### ISSUE TITLE
Migrate BRD Sidekiq alerts to EKS

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#54209]
### Summary
[sidekiq.yaml](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/datadog/catalog/sidekiq.yaml) contains two alerts:
* "[Prod] [Sidekiq] There are no sidekiq processes running"
* "[Prod] [Sidekiq] Retry queue size is high"

Both of them use metrics from BRD. The queries need to be updated and tested. 

The [Sidekiq dashboard](https://vagov.ddog-gov.com/dashboard/csk-gk9-u9v/vets-api-sidekiq-dashboard?from_ts=1677778605549&to_ts=1677782205549&live=true) in Datadog might be helpful to use for the transition. 

### Tasks
~~[ ] Update queries. The [Datadog metrics explorer](https://vagov.ddog-gov.com/metric/explorer?start=1677510872338&end=1677514472338&paused=false) can be used to tinker around and find the right metrics. Also see Sidekiq dashboard linked above~~
- [x] Update query for processes running
- [x] Update query for retries queue
- [x] Test for accuracy
- [x] alert based on puma backlog of c. 200
~~[remove old alert](https://vagov.ddog-gov.com/monitors/104982) (no IaC)~~ #56224

**Comment by rmtolmach** [comment]
Note: This alert is also being modified as part of:
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/52558

**Comment by laineymajor** [comment]
@considerable to complete after dev deprecation work

**Comment by laineymajor** [comment]
@considerable what's going on here? Please update ASAP

**Comment by oseasmoran73** [comment]
There is a discrepancy on processes being reported in Sidekiq UI and Datadog. I am unable to verify via sandbox Sidekiq, which will make alert inaccurate

[Slack](https://adhoc.slack.com/archives/C045LCF8WU8/p1680123540238699)

**Comment by rmtolmach** [comment]
In https://github.com/department-of-veterans-affairs/va.gov-team/issues/54255, I added a monitor that includes alerting if `vets-api-sidekiq` _pods_ go down. This won't overlap with the work done in this ticket, but just posting here to keep track of sidekiq alerts 😎

**Comment by oseasmoran73** [comment]
Some nits have been addressed thanks to @rmtolmach catching them!

**Comment by oseasmoran73** [comment]
All set for tomorrow!

**Comment by oseasmoran73** [comment]
@laineymajor @LindseySaari Closing ticket. Feel free to reopen as needed
