### ISSUE TITLE
Revise eligibility section on burial allowance page

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#54203]
## Issue Description
We recently made some accessibility updates to the https://www.va.gov/burials-memorials/veterans-burial-allowance/page. The eligibility section on that page has some unusual bullet patterns and seems to repeat some info, so we should suggest updates and get SME approval before we publish.

Laura already suggested revisions in this Drupal version: prod.cms.va.gov/node/864/revisions/749869/view

---
## Tasks
- [ ] Revise blue box content for ease of reading (Laura)
- [ ] Copyedit (Megan)
- [ ] Send to Angie and other pension SMEs for accuracy review (Laura)
- [ ] Prepub and publish (Megan)

## Acceptance Criteria
- [ ] Blue box is updated
