### ISSUE TITLE
Add VFS video to Platform YouTube channel

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#54200]
## Issue Description
We now have a video on the Platform's YouTube channel that introduces the Platform website to VFS team members. It lives here: https://www.youtube.com/watch?v=yzl6nyLmqkA

---
## Tasks

- [x] Reach out to Naomi to ask how to add the video to the Platform's YouTube channel

- [x] Add the video to the Platform's YouTube channel

- [x] Decide as a team how you want the description to look

- [x] Talk to Naomi about descriptions and links and verifications

## Acceptance Criteria
- [x]  The Platform website orientation video created for VFS teams will be added to the Platform's YouTube channel.
- Location: https://www.youtube.com/watch?v=yzl6nyLmqkA
