### ISSUE TITLE
[Secrets.yml cleanup] Discovery and documentation of adding secrets

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#54219]
_note: this issue was originally the Epic, so there are some comments below that aren't exactly related to the discovery and documentation of adding secrets. The Epic is now #55718_

**PROBLEM STATEMENT**
The current lack of process in adding secrets.yml to the manifest repo is creating inconsistencies process and therefore causing breaking changes to be deployed (TLDR server problems).

_Originally, we had thought a GitHub Action would be the way to streamline this process, but we worried there would be no one to maintain the action, so decided to tackle this via comprehensive documentation. There are comments below about this thought process_

**ACTION STEPS**
- [x] Quick discovery to determine param store permissions related to VFS teams and which paths and environments are available to them
- [x] Discovery to determine desired process for adding secrets
- [x] Documentation to formalize process around adding secrets to vets-api
    - [x] Adding certs
    - [x] Adding normal non-cert secrets

**DEFINITION OF DONE**
- [x] Discovery complete (see comments below)
- [x] Documentation created and reviewed

**Comment by rmtolmach** [comment]
**Discovery**
Many VFS developers have this permission: [dsva-vfs-developers](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf#L1959) 
```tf
    "dsva-vfs-developers" = {
      path = "/"
      policy_attachments = [
        "arn:aws-us-gov:iam::aws:policy/CloudWatchReadOnlyAccess",
        "arn:aws-us-gov:iam::aws:policy/CloudWatchSyntheticsFullAccess",
        aws_iam_policy.CredstashReadAccess.arn,
        aws_iam_policy.VagovSSMLowerEnvironmentAccess.arn,
        "arn:aws-us-gov:iam::008577686731:policy/cloudwatchlogs-allow-filterevents",
        aws_iam_policy.vsp-vetsapi.arn,
        aws_iam_policy.ssm_parameter_store_vets-website.arn
      ]
    }
```
`ssm_parameter_store_vets-website` and `vsp-vetsapi` give access to `"dsva-vagov/vets-website/*"` and `"dsva-vagov/vets-api/*"` (in [iam_policies](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_policies.tf#L2254-L2270)) and allows that user to do all actions (delete, etc.) but only for resources under the `dsva-vagov/vets-website` or `dsva-vagov/vets-api` path.

**Comment by laineymajor** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Tech-Team-1-633af4074573d06c3cda142a/issues/department-of-veterans-affairs/va.gov-team/54219?planning-poker) with Zenhub @LindseySaari @rmtolmach

**Comment by laineymajor** [comment]
@rmtolmach I tagged you in this ticket as I see you started some of the discovery. When you feel that work is complete, please check the box for that DoD item :)

**Comment by laineymajor** [comment]
@rmtolmach check in with the DevOps CoP about:
The policy with the biggest impact is dsva-vfs-developers. Do we want to modify that? There are policies left over from Spike last year that could probably be cleaned up. Not sure if that needs to be part of this work.

Potentially need a higher level of authority for decision making (Clint)...

**Comment by rmtolmach** [comment]
Working on this ticket today.

**Comment by rmtolmach** [comment]
3/13 update:
- [ ] Add documentation to section about deleting parameters to this page: https://depo-platform-documentation.scrollhelp.site/developer-docs/store-a-secret-in-parameter-store

Rachal ran a test (see PR linked to this issue ☝️). She created an ssm parameter, the SSM parameter was added to the dev local secrets, SSM was deleted from AWS Parameter store, a sync was ran, and **the sync failed**. So this is still an issue ("this" being the potential that someone can delete something from param store and it mess up vets-api.) However, the _deployment_ didn't go through, so that was good. 

From Kyle:
> this is a process/discipline issue, largely. "don't delete anything that is still in use, _including_ the current deployment"

**Comment by rmtolmach** [comment]
3/14 🥧 update:
I'm still in talks with Kyle on what the best way forward is for the parameter deletion process. (Conversation is happening in the same thread I linked two comments up.)

**Comment by laineymajor** [comment]
Working with Kyle on how to address this.

**Comment by rmtolmach** [comment]
3/15 update:
I am editing the [Platform Website docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/store-a-secret-in-parameter-store#StoreasecretinParameterStore-Deletingasecret). It's currently [in draft](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2567766074/COPY+OF+Store+a+secret+in+Parameter+Store#Deleting-a-secret), so more edits can be made, but I added this ⚠️ section:
![image](https://user-images.githubusercontent.com/10993987/225443309-a2e92cbb-d905-4deb-a198-39718526c4f3.png)

No word yet on the details of a solution from Kyle, but his general idea is:
> have a process to clear the param in ps, and mark it for deletion. This way we can be sure nothing is going to break (by clearing the value), and after a given period of time we run a cleanup job.

My thoughts:
* does this mean we would take away the ability to delete parameters and instruct devs to only delete the value of the parameter?
* This addresses the parameter deletion part of this ticket, but not the problem that we've had with people incorrectly adding their secrets to the manifest repo. That will require more discovery (maybe a brainstorm session with Lindsey and Rachal?) 
    * I'm thinking I should just write up two separate tickets for these things to put in this epic.

**Comment by rmtolmach** [comment]
3/16 update:
Still haven't heard from Kyle about his proposed approach to Parameter Store values, so I started to tackle the other part of this ticket: managing secrets and values in vets-api.

I talked with Lindsey and we were talking about the pros and cons of having people add their secrets and environment variables directly into the manifest repository vs. creating some automated way for them to be added (like via a form and GitHub action). A form + GHA would give us more control, _but_ when the form or GHA needs to change, who is going to do that without a dedicated team? Once we finish this project, no one would own the form or action, so we worry that it might need updates and there would be no one to work on it. 

The problem with people adding to the secrets.yml and values.yml files without any guardrails is that it's error-prone. The files are both pretty long and we have seen people put their secrets in the wrong sections. And it's hard to catch during code review if a section is a few hundred lines long. How can we prevent this without adding more github actions to maintain? One idea we talked about was adding comprehensive documentation to the Platform Website. There could then be a simple GHA that comments with a link to the docs if someone modifies secrets.yml. 

I have started a document in my personal space in Confluence with the intention of it eventually ending up on the platform website (once complete and reviewed). WIP doc: https://vfs.atlassian.net/wiki/spaces/~121859534/pages/2568945819/How+to+modify+secrets+and+values+in+vets-api

**Comment by rmtolmach** [comment]
3/17 ☘️ update:
I worked on the Confluence doc (linked in previous comment ☝️). The doc I'm writing will likely fit into this existing page (or be nested in the same location of the platform website): https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-SecretValues

**Comment by LindseySaari** [comment]
Rebecca is working on this from a documentation update angle.

**Comment by LindseySaari** [comment]
@rmtolmach is starting to work on this today

**Comment by rmtolmach** [comment]
Update:
✅ I added the ⚠️ section to the platform website (mentioned in https://github.com/department-of-veterans-affairs/va.gov-team/issues/54219#issuecomment-1470861650)
✅ I worked with Lindsey on updating the [Secret Values](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-SecretValues) section of the Platform website. The steps are clear (_I_ think 😃) and include links, examples, and screenshots (_with_ captions!) 
🏗️ Work is still in progress on a document that outlines adding a non `settings-local-secret` secret

**Comment by rmtolmach** [comment]
in-progress doc is reviewed and complete!
It lives here: https://vfs.atlassian.net/wiki/spaces/pilot/pages/2568945819/Add+certs+as+secrets+to+vets-api

And I've added a link to it at https://vfs.atlassian.net/wiki/spaces/pilot/pages/2452193284/Vets+API+on+EKS#Adding-a-cert

Both of these pages should get published to the platform website on Monday.

**Comment by rmtolmach** [comment]
Done with this ticket. I've created #55720 to cover the issue of people deleting parameters in Parameter Store. I added it to the secrets.yml Epic.
