### ISSUE TITLE
Make "containers out of memory" alert actionable

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#54214]
"[EKS] Containers out of memory (by pod)" in [eks.yaml](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/datadog/catalog/eks.yaml) needs to have an action item in the message so a dev responding to the alert knows what to do. What needs to be done to resolve or investigate? If the "what to do" message is long, add a section to [alerts.md](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/OnCall/alerts.md) and link to it in the alert message in eks.yaml.

### Tasks
- [x] Figure out what the action items should be.
- [x] Determine whether they belong in eks.yaml or in alerts.md
- [x] Add action items, make PR, get approval, get DevOps to run Terraform, merge.

**Comment by rmtolmach** [comment]
Done in https://github.com/department-of-veterans-affairs/devops/pull/12823. But I'll wait to close tomorrow b/c today is the in-between sprint day!
