### ISSUE TITLE
BE | Profile | Testing | Local | Discovery: Improve Mock Testing

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#54238]
## Background
Betamocks is used to mock data in the lower-level environments (local, sandbox, and dev).

The purpose of this ticket is to investigate and document how to setup and leverage beta-mocks so that engineers can more easily test VA.gov FE-BE integration and automate future test scenarios that can be run before feature releases.

We know that these endpoints are failing (all 500 status code)...
- `v0/profile/personal_information`
- `v0/profile/service_history`
- `v0/profile/ch33_bank_account`

## Tasks
- [x] Investigate and document how to configure and use current betamocks solution.
- [x] Open tickets for implementing new scenarios, or alternate solutions.

## Acceptance Criteria
- [x] Review findings with PM.

## Resources
https://github.com/department-of-veterans-affairs/betamocks
https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/setup/betamocks.md
https://github.com/department-of-veterans-affairs/vets-api-mockdata#create-mock-data-for-a-brand-new-service

**Comment by ajakabcin** [comment]
@dellerbie  @tpharrison and @BerniXiongA6 I'm going to slot this as something for @dellerbie to work in sprint 9 if it's not done before then, just fyi!

**Comment by mtcA6** [comment]
@ajakabcin @dellerbie @tpharrison is there an, and I use this lightly, mvp test case we'd like to setup? Do we need to brainstorm all the possible test scenarios we're hoping to contemplate and pick the one that will get us the most value add?

**Comment by tpharrison** [comment]
I have things running locally and the reason the above endpoints are returning 500 errors is because mocked responses have not been configured for this user (or other users).

I need to work with the mock repository a bit more to understand how everything is wired up and will work that unders ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/54238.
