### ISSUE TITLE
Add entry points to online HLR form on several pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#54233]
## Issue Description

The benefits decision reviews team opened an intake request after they noticed that several decision reviews pages don't have the link to the [online HLR form](https://www.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996). 

Initial intake request: #54124

Pages asking to add entry point on:

[https://www.va.gov/decision-reviews/fiduciary-claims/](https://www.va.gov/decision-reviews/fiduciary-claims/)
[https://www.va.gov/decision-reviews/insurance-claims/](https://www.va.gov/decision-reviews/insurance-claims/)

We need to confirm with IA that the entry points make sense and then add content and action links to each page if needed.

## Tasks
- [x] Confirm entry points (Jenny)
- [x] Create content with links (Katherine)
- [x] Review (Laura)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Entry points are on live pages

**Comment by jennymayoco** [comment]
Hi @katherine-fung - The two entry points make sense from an IA perspective. Let me know if there's anything else I can support with!

**Comment by katherine-fung** [comment]
Thanks @jennymayoco! 

@RLHecht @laurwill - these 2 pages are ready for copyedit. 

Fiduciary claims
http://preview-prod.vfs.va.gov/preview?nodeId=3016 

Insurance claims 
http://preview-prod.vfs.va.gov/preview?nodeId=3025

Note: On both of these pages, I added an entry point for HLR and replaced "senior reviewer" with the phrase "higher-level reviewer."

**Comment by megzehn** [comment]
These changes look good. Confirming I reviewed and published. Thanks everyone! This is ready for you to validate and close @RLHecht.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket!
