### ISSUE TITLE
Rework "pod restarting" alert

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#54232]
### Summary
"[EKS] Pod restarting", in [eks.yaml](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/datadog/catalog/eks.yaml), needs some attention. this one is very noisy, so the metric needs adjusted to only alert when necessary (notes: sometimes it takes a little bit for a pod to restart). The alert is being sent to #platform-datadog-alerts-test. Once the metric is adjusted, it should be directed at #devops-alerts. 

Add action items to the message. What needs to be done to resolve or investigate? If the "what to do" message is long, add a section to [alerts.md](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/OnCall/alerts.md) and link to it in the alert message.

### Tasks
- [x] Adjust alert so it's not spammy
- [x] Redirect to #devops-alerts
- [x] Include action items in the alert message
- [x] After PR approval, get DevOps to run terraform and merge PR

**Comment by oseasmoran73** [comment]
@rmtolmach I presume this is specific for vets-api, correct? Is there a specific threshold that the team had in mind?

I would probably say for lower environments to go to #devops-alerts and sandbox/prod go to #oncall.

When I initially created that yaml, it was for the entire platform. Not app specific. I would recommend we create a new yaml with alert specific for vets-api. Thoughts?

> What needs to be done to resolve or investigate?

Given tier 1 would be first on the scene, we can probably reference the playbook

**Comment by rmtolmach** [comment]
> I presume this is specific for vets-api, correct? 

Yes! 

> Is there a specific threshold that the team had in mind?

No, I don't think so. 

> I would recommend we create a new yaml with alert specific for vets-api. Thoughts?

idk. I think we could change the alert  to notify certain channels depending on certain variables. Similar to [external-secrets.yaml](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/datadog/catalog/external-secrets.yaml):
```
{{#is_exact_match "kube_cluster_name.name" "dsva-vagov-prod-cluster" "dsva-vagov-utility-cluster" "dsva-vagov-sandbox-cluster" }}
```
I _think_ this is what Kyle was talking about yesterday–that we should reuse alerts so we didn't have to duplicate alerts.

> Given tier 1 would be first on the scene, we can probably reference the playbook

Let's try to be as precise as possible

**Comment by oseasmoran73** [comment]
> idk. I think we could change the alert to notify certain channels depending on certain variables. Similar to [external-secrets.yaml](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/datadog/catalog/external-secrets.yaml):

I am fine changing it more for vets-api, but initially when I created it, was more for platform as a whole. Which is why I was leaning more towards creating vets-api yaml specifically

If Kyle has one they are using or for their purpose, then we can def reuse

**Comment by LindseySaari** [comment]
It may be best to rework this for vets-api specifically to make the alerts more actionable. This may be another great item for AFTER EKS prod rollout. Let's discuss if a new ticket is needed.

**Comment by rmtolmach** [comment]
I've partly adjusted this in https://github.com/department-of-veterans-affairs/devops/pull/12756.

Like Oseas mentioned, this alert covers _all_ apps, not just vets-api. Alerts could be routed to different places based on namespace. I am guessing the many apps will probably be split up into devops and backend alerts. Currently, the alert is being routed to `@pagerduty-EKS_Cluster_-_Prod` which falls under devops. Figure out if this is desired or not. You might need to edit the pager duty integration in Datadog to include the right pd service. [These docs](https://vfs.atlassian.net/wiki/spaces/OT/pages/2346844179/Migrate+Alerts+from+Prometheus+to+Datadog) show screenshots of the integration.

**Comment by oseasmoran73** [comment]
With RT PR and comment above, I think the acceptance criteria has been met. Moving to review state

**Comment by rmtolmach** [comment]
I've reviewed this ticket in reference to vets-api. The one thing I think we're missing is that alerts for the dev and staging environments for vets-api go to the datadog-alerts-test channel (along with all the other apps). To make this more visible, I'm moving those to #devops-alerts
![Screenshot 2023-04-11 at 1 04 41 PM](https://user-images.githubusercontent.com/10993987/231237305-f172dd78-a476-486d-8db3-6eb15305352c.png)

I will make a PR for these changes or include them in another PR for another alert!

**Comment by rmtolmach** [comment]
I applied the changes mentioned in my comment from earlier today in https://github.com/department-of-veterans-affairs/devops/pull/12819. This is now done! ✅
