### ISSUE TITLE
Audit & organize GitHub file URLs into spreadsheet

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#54239]
## Issue Description
Specific Platform support pages still exist on GitHub, specifically working-with-vsp, as well as many others. These pages don't have a deprecation notice and it's very likely that many are out of date and no longer relevant. However, they are still being found by VFS team members and it's possible they could be interpreted as valid guidance. We need to ensure all pages that should be deprecated should have a message that points them to the Platform website, as their source of truth.

Spreadsheet audit: https://docs.google.com/spreadsheets/d/1pTzNDqb8jg9_zEYOsTsgsEIbcKUEo8UbIiPHXSwkAz8/edit#gid=0

---
## Tasks
- [x] Organize all Git Hub URLs shared by Andrea and Shira into a spreadsheet

- [x] Prepare spreadsheet to divide URLs for each team member to audit and add deprecation message

## Acceptance Criteria
- [x] PM will know how to divide work across the team
