### ISSUE TITLE
Migrate `DeploymentHostCountCritical`

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#54246]
### Summary
The alert [DeploymentHostCountCritical](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/prometheus/rules/cluster.rules) (and its messaging in [alerts.md](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/OnCall/alerts.md#deploymenthostcountcritical)) needs to be changed from a Prometheus alert to a Datadog alert. AND it needs to change based on our changing infrastructure from BRD to EKS. 

*[Confluence documentation on migrating an alert from Prometheus to Datadog](https://vfs.atlassian.net/wiki/spaces/OT/pages/2346844179/Migrate+Alerts+from+Prometheus+to+Datadog)
*[High-level Datadog Confluence documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/2236612646/Monitor+Applications+and+Infrastructure+with+Datadog)

### Tasks
- [ ] Determine what the equivalent alert would be for EKS
- [ ] Create alert in Datadog (using Terraform)
- [ ] Update alerts.md and add link in alert messaging. 
- [ ] ~Delete `cluster.rules` because `DeploymentHostCountCritical` is now migrated and `DeploymentInstanceCyclingWarning` is being done in #54232~
- [ ] After the PR has been approved, get a DevOps eng to run the terraform and merge the PR.

**Comment by rmtolmach** [comment]
I will come back to this once higher priority items are complete

**Comment by laineymajor** [comment]
@rmtolmach is this currently on hold?

**Comment by laineymajor** [comment]
Will start soon after other item is complete

**Comment by rmtolmach** [comment]
Turns out `DeploymentHostCountCritical` is for more than just vets-api things 💡 Screenshot shows some metrics for the past few weeks: 
![image](https://user-images.githubusercontent.com/10993987/228970770-5015a977-85e6-43c6-a93b-43d871c94b25.png)
[Prometheus link](http://prometheus-sandbox.vfs.va.gov:9090/prometheus/graph?g0.range_input=2w&g0.expr=sum(up%7Bdeployment_name!~%22(%7Cpkg-cache%7Cscratch.*%7C.%2B-test%7Ccms)%22%7D)%20BY%20(deployment_name)&g0.tab=0)
So we definitely don't want to delete this since the revproxy and fwdproxy are still in EC2. And we don't need to filter out the vets-api server and worker deployments from this metric because once they're out of EC2, the metric just won't pick them up, which is what we want. 

In terms of creating an alert in Datadog that would be the equivalent for EKS, I _think_ that is covered in https://github.com/department-of-veterans-affairs/va.gov-team/issues/54255. That metric alerts if pods are down in `vets-api-web`, `vets-api-sidekiq`, `address`, or `vets-api-web-bgs-evss`. @LindseySaari, can you check me on that?

**Comment by rmtolmach** [comment]
I brought this up during a meeting, and yeah, the host count will be covered by checking the `replicas_available` in the [`no_pods_running`](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/datadog/catalog/vets-api.yaml#L46) alert.
