### ISSUE TITLE
(Lauren) Reviewing of Migration to EKS docs

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#54240]
## Issue Description

- With the EKS migration wrapping up soon, Tech Team 1 is preparing to make a lot of content updates to the following pages on the Platform website: https://docs.google.com/spreadsheets/d/1rTacvOYTXh3jMehzlfd0gGMlhiQOqu_Re-kKrGUVY80/edit#gid=0
- They will be going to Leadership **office hours on March 14** about this.
- They are planning to make a lot of the **content updates during Sprint 23 (week of March 20-23)**.
- The Platform Content team will likely need to review a lot more documents to deploy on this week than usual and we will need to prepare the right amount of coverage for this.
- Product Manager from Tech Team 1, Lainey Trahan, will provide more information on what kind of content updates to expect on each of the pages listed on the Google document above.
- Tech Team 1's epic in Zen Hub: https://github.com/department-of-veterans-affairs/va.gov-team/issues/54571

**More information on the project:**

- Lainey's team will try to make the content updates on **Monday and Tuesday (March 20-23)**
- There are 30 documents total
- 15 documents on Monday
- 15 documents on Tuesday
- Depending on her team members' time zones, some documents may be updated on Wednesday ET (our time)
- Here's the spreadsheet with the pages: https://docs.google.com/spreadsheets/d/1rTacvOYTXh3jMehzlfd0gGMlhiQOqu_Re-kKrGUVY80/edit#gid=0

## Our plan of action

Our team will:
- meet on Monday to review what has been submitted on the first day
- identify what is part of Lainey's documentation vs other regular deployment entries
- decide how to divide the pages to review
- coordinate amongst ourselves on what the content update was and communicate with each other on whether we're reviewing for the same content update on each of our pages.
- coordinate amongst ourselves how we will alert Tech Team 1 of anything they need to correct or we decide is a launch blocking issue for this specific deploy

---
## Tasks
- [x] Review assigned pages in the deploy; shared review and deploy work for Mon-Thurs

- [x] If there are any launch blocking issues, send back to content editors

- [x] Team will deploy all content updates made related to Tech Team 1's migration to EKS

## Acceptance Criteria
- [x] Tech Team 1's documentation updates related to the migration to EKS will be reflected live on the Platform website.

**Comment by vbellissimo** [comment]
Comments from team:

- Team prefers to be more involved
- Offer to help load the templated messages to most of the pages. This would allow us to better know how many pages will be updated on each day from March 20-23. Which in turn, allows us to be better prepared to distribute the content review amongst our team.
- We can help fine-tune the message
- We can also help with the formatting/styling (call out box, etc.)
