### ISSUE TITLE
New alert: Container failing to start

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#54253]
### Summary
If a vets-api EKS container fails to start we need to be alerted about it. The messaging in the alert needs to be actionable. What needs to be done to resolve this alert or what needs to be investigated? If the action items are verbose, add a section to [alerts.md](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/OnCall/alerts.md) and link to it in the alert's message.

Route the alerts by environment (we don't need to wake anyone up in the middle of the night for a non-prod environment) to #oncall, #devops-alerts, pagerduty, or wherever is appropriate. 

* [Confluence documentation on migrating an alert from Prometheus to Datadog](https://vfs.atlassian.net/wiki/spaces/OT/pages/2346844179/Migrate+Alerts+from+Prometheus+to+Datadog)
* [High-level Datadog Confluence documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/2236612646/Monitor+Applications+and+Infrastructure+with+Datadog)
* [Datadog metrics explorer](https://vagov.ddog-gov.com/metric/explorer)
* Examples: https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/datadog/catalog/eks.yaml

### Tasks
- [ ] Create alert in Datadog (using Terraform)
- [ ] Update alerts.md and add link in alert messaging (if applicable). 
- [ ] After the PR has been approved, get a DevOps eng to run the terraform and merge the PR.

**Comment by laineymajor** [comment]
@considerable to complete after dev deprecation work

**Comment by laineymajor** [comment]
@considerable what's going on here? Please update ASAP

**Comment by rmtolmach** [comment]
3/31 update:
Docs: https://docs.datadoghq.com/integrations/kubernetes_state_core/?tab=helm
Metrics explorer: https://vagov.ddog-gov.com/metric/explorer

Looking at some metrics (summed by `kube_cluster_name` i.e. environment)
* `kubernetes.containers.running` or `kubernetes_state.container.running` - gives the number of containers running
    ![image](https://user-images.githubusercontent.com/10993987/229233085-4fdfd771-4ad9-4355-93f9-27eaf51f291a.png)

* `kubernetes_state.container.restarts` - gives the number of restarts. Could be valuable. I know in BRD sometimes a vets-api container would be restarting over and over and this would indicate that something was wrong. We could alert if it restarts a certain number of times. 
    ![image](https://user-images.githubusercontent.com/10993987/229231462-435f13eb-4f3d-4a1c-aeb5-0f24b28cb41c.png)

* `kubernetes_state.container.ready` - "Describes whether the containers readiness check succeeded." 😕 this one doesn't make sens to me because the graph's `y` axis is numbers. What number is "ready"? Or am I Datadogging all wrong? 😂 
    ![image](https://user-images.githubusercontent.com/10993987/229233992-f975657f-bd4b-4335-9a9a-179cd631ec63.png)

**Comment by rmtolmach** [comment]
This PR enables alerting on retries: https://github.com/department-of-veterans-affairs/devops/pull/12756

I will merge and apply the terraform tomorrow morning and then close this ticket.

**Comment by rmtolmach** [comment]
terraform applied. I will monitor #oncall for instances of this alert.
