### ISSUE TITLE
Migrate devops entropy alerts

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#54252]
### Summary
There are two entropy alerts in [node.rules](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/prometheus/rules/node.rules) that need to be migrated from Prometheus to Datadog AND changed from using BRD (EC2 instances) metrics to EKS metrics. 

Background: Entropy is related to randomness. Low entropy can lead to a possible security vulnerability. From what I've been able to tell, “low” is below the 100-200 average. I think entropy is measured in bits per second.

*[Confluence documentation on migrating an alert from Prometheus to Datadog](https://vfs.atlassian.net/wiki/spaces/OT/pages/2346844179/Migrate+Alerts+from+Prometheus+to+Datadog)
*[High-level Datadog Confluence documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/2236612646/Monitor+Applications+and+Infrastructure+with+Datadog)

### Tasks
- [x] Determine what the equivalent alert would be for EKS
- [ ] Create alert in Datadog (using Terraform)
- [x] Update alerts.md and add link in alert messaging. 
- [x] Delete `node.rules`
- [x] After the PR has been approved, get a DevOps eng to run the terraform and merge the PR.

**Comment by oseasmoran73** [comment]
@rmtolmach Is this specifically for EKS migration? I would imagine that this handled by TT2 & the sunset of Prometheus. See [#437](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/437) for additional details

**Comment by rmtolmach** [comment]
I think I flagged this alert for migrating during EKS because it can alert on vets-api, so we'd want a similar one keeping an eye on our EKS clusters. Example: https://dsva.slack.com/archives/C24RH0W11/p1657644628008419

**Comment by rmtolmach** [comment]
@oseasmoran73 what do you mean by "platform monitors"?

I found this documentation that looks relevant: https://docs.datadoghq.com/integrations/linux_proc_extras/
I don't think we get `entropy` by default. It would be under `system.entropy` which isn't populating in datadog when I try.

**Comment by laineymajor** [comment]
@rjohnson2011 Please take a look at this ticket. We would love if you could pick this up for THIS sprint. That being said, prioritize this ticket plus (only) one of the CoP tickets that you currently have. Thank you!

**Comment by rjohnson2011** [comment]
Entropy monitoring uses a [built in method from Prometheus](https://docs.cloudera.com/management-console/1.5.0/monitoring-metrics/topics/cdppvc_ds_node_entropy_available_bits_orter.html). 

There does not appear to be an entropy method for EKS. 

Looking at Prometheus, the chart is static for entire timeline at 256 bits. Looking into finding a similar monitor using EKS such as node_memory_utilization as a % of memory used by nodes and node_network_total_bytes as the total number of bytes transmitted over the network, are available
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-metrics-EKS.html
![image.png](https://images.zenhubusercontent.com/5fb40598d06a06671e842a63/c462cb02-e976-4df0-a907-6b867e3fa426)

**Comment by laineymajor** [comment]
Looking for an equivalent to the entropy metrics. Found something suitable (kubernetes state node memory allocatable).... will be moving forward with this.

**Comment by rjohnson2011** [comment]
Currently working with DevOps support to run the necessary terraform commands to close out this ticket - https://dsva.slack.com/archives/C04CYC4LMU6/p1683305768726459

**Comment by laineymajor** [comment]
Waiting for devops to run terraform command, then this can be closed. Sounds like there are currently issues in his environment...

**Comment by laineymajor** [comment]
@laineymajor this is a use case for why someone on our team needs devops creds/perms. We keep getting stuck, but we have a LOT of devops experience.

**Comment by laineymajor** [comment]
Ryan and Rachal to meet and review together.

**Comment by LindseySaari** [comment]
Ryan reached out to Clint in the CoP channel and will sync with Rachal this afternoon

**Comment by rjohnson2011** [comment]
I'm able to access the [DataDog agent](https://vagov.ddog-gov.com/account/settings#agent/kubernetes) page now. Installed helm but could use guidance how to manipulate this with our helm charts (https://github.com/department-of-veterans-affairs/vsp-infra-k8s-datadog-agent and https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/datadog-agent) to close out this ticket. Happy to pair on this when I get back.

**Comment by laineymajor** [comment]
This needs to be complete Monday morning @rjohnson2011

**Comment by rjohnson2011** [comment]
[Current put in a request to DevOps support to deploy this to dev and staging for testing](https://oddball.slack.com/archives/C045LCF8WU8/p1684782288698799?thread_ts=1684770714.690979&cid=C045LCF8WU8) -> https://dsva.slack.com/archives/C04CYC4LMU6/p1684782364744489

**Comment by laineymajor** [comment]
@RachalCassity will step in and help @rjohnson2011 ... DevOps CoP not sure how to deploy this at the moment. PR is ready.

**Comment by rjohnson2011** [comment]
Paired with @RachalCassity to merge in PRs for system entropy check. The entropy metric is [now available on DataDog.](https://vagov.ddog-gov.com/metric/explorer?start=1685720244797&end=1685720544797&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYZAYgUJ4YThr42gDGSsgg6gi6mZaBZnHKGniqyBpYGghwqgB0cCIFOPJYjRgAbhgQmABGaHDAAFQ8AAQDWBPALd08IDwAulSu7niYoeHrqpsYMaXxS6sgdVjDMiDyGMMI9cpQODBOmVsaEJmJaKJwTnKKco4H5Qb6-Jz0JjKERuDxoJb8CD2TBYf4KHIgH4iJQrHh8M7yH4IADCUmEMBQIk2aB4QA)

Created a PR for a terraform file of this query, the final step to completion. Placing this into review until Lindsey & Rachal can look over on Monday. https://github.com/department-of-veterans-affairs/devops/pull/13092

**Comment by rjohnson2011** [comment]
Here is the revised terraform alert PR based on the discussion & feedback from this morning's standup: https://github.com/department-of-veterans-affairs/devops/pull/13103

**Comment by laineymajor** [comment]
@rjohnson2011 can you leave a note here with what's been done on 6.6, and what's remaining? I want to ensure that is recorded as this will be carried over to our next sprint.

**Comment by laineymajor** [comment]
@rjohnson2011 what's remaining here?

**Comment by rjohnson2011** [comment]
@laineymajor Just coordinated with @rmtolmach to resolve a failing CI check. Everything is passing now and @rmtolmach will apply the terraform and merge tomorrow.

**Comment by rjohnson2011** [comment]
@rmtolmach informed me this is now deployed via Terraform.
