### ISSUE TITLE
Collaboration Cycle for Digitize Forms - Form 21-4142(a)

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#54257]
### VFS team name

Digitize Forms

### Product name

Form 21-4142(a)

### Feature name

Form 21-4142(a)

### GitHub label for product

21-4142

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>
### When did/will you start working on this product/feature?

2/20/2023

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

No

### Will your work involve changes to...

Tools, applications and dynamic pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline

https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-4142(a)/Product%20Outline.md

### Notify the Collaboration Cycle team of this ticket in the vfs-platform-support Slack channel.

- [X] I acknowledge that I must notify \#vfs-platform-support after submitting this issue.
</details>

### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- [ ] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [ ] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [ ] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.

**Design Intent artifacts**

- [x] [Sketches and User Flow](https://www.sketch.com/s/c8c31a8a-19ae-4cbc-81ef-40eb8f4f8c52)
- [x] [Source of Truth](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-4142(a)/sourceoftruth.md)
  
##### Platform actions
- [x] Follow Moderator Responsibilities guidance for Design Intent
- [x] Meeting date/time: **Monday, March 6 3:30PM ET**
  
##### Platform actions

- [x] If you have feedback, create feedback tickets and link to this epic. Once you have completed you review, check the box next to your practice area
  - [x] Accessibility has completed the review
  - [x] Design has completed the review
  - [x] IA has completed the review
- [x] Update this ticket with the Zoom recording
  - Recording URL: https://oddball-io.zoom.us/rec/share/lwOqmI_GI_5hQ3cY-aKEOKORhHII8swDoK5wzHS-FrT3IjY_UJ_mEcBO_7aHgQOs.IXtRP6d8LBo3RH1U
  - Password: mCHE3O2#
  
##### VFS actions

- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Sitewide Content and IA Intake Request
<details>
  <summary>Toggle Sitewide Content and IA Intake Request</summary>

##### VFS actions
- [ ] Complete the [sitewide content and IA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-Content-and-IA-intake-request.2124906551.html)
- [ ] Link to the Sitewide Content and IA Intake Request ticket below -  epic #55195

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [ ] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

Provide links or documents for the following:

- [x] [Finalized design prototype or mockup](https://www.sketch.com/s/c8c31a8a-19ae-4cbc-81ef-40eb8f4f8c52)
- [ ] Specify which pages are included in the review 
- [ ] Research plan
- [ ] Conversation guide
 
**Content artifacts**
  
- [x] [Source of Truth](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-4142(a)/sourceoftruth.md)
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)

**IA artifacts**

- [x] Please include a link to any [Sitewide Content & IA](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/54641) feedback you received, including an IA review document or intake form.

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [ ] [Regression test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-regression-test-planRegressionTestPlan)
- [ ] [Test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-test-planTestPlan)
- [ ] [Coverage for References](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [ ] [Summary(Defects) reports](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [ ] [E2E tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-e2e-test-participationE2ETestParticipation) (provide a link to the product’s code)
- [ ] [Code coverage](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-unit-test-coverageUnitTestCoverage) (provide a link to the product’s code)
  
##### Platform actions
- [ ] Follow Moderator Responsibilities guidance for Midpoint Review
- [ ] Meeting date/time: **Thursday, April 6 at 1:30 pm EST**
- [ ] [Slack request](https://dsva.slack.com/archives/CBU0KDSB1/p1680292454549319)

##### Platform actions

- [ ] If you have midpoint review feedback, create feedback ticket and link to this epic. Once you have completed your review, check the box next to your practice area
  - [x] Design has completed the review
  - [ ] Accessibility has completed the review
  - [ ] IA has completed the review
  - [ ] Content has completed the review
- [x] Update this ticket with the Zoom recording
  - Recording URL: [Zoom link](https://oddball-io.zoom.us/rec/share/Tja_BY3UNiFM9EldTJ5PnLybklQLlY4GgcaY50STcsXMUW1ufJNI2UCXXeBPX50V.UjelLNogLhWnAMyo)
  - Password: $Z%sXk0%
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [ ] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [ ] Link to the Analytics Implementation and QA Request ticket below

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [x] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [x] [Link to the Contact Center review request ticket below
](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57404)
</details>

### Staging Review
<details open>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [ ] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [ ] I confirm the environment is available and test users have been provided.
- [ ] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).

**Staging Review artifacts**
  
  Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts)
  
**Product artifacts** 
**[PLEASE SEE GITHUB PAGE FOR ALL SUPPORTING ARTIFACT LISTED BELOW](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-4142(a)/Supporting%20Artifacts.md)**

- [ ] Staging URL
- [ ] All Pages, new Form
- [ ] Staging test user information         
  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
  
**IA artifacts**
- [x] Please include a link to any [Sitewide Content & IA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54641) feedback you received, including an IA review document or intake form.

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [x] [Regression test plan](https://dsvavsp.testrail.io/index.php?/plans/view/4622)
- [x] [Test Plan Link to Test Rails](https://dsvavsp.testrail.io/index.php?/milestones/view/1156)
- [x] Coverage for References [Coverage Link](https://github.com/department-of-veterans-affairs/vets-api/tree/master/modules/forms_api/spec)
- [ ] [Summary(Defects) reports](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [x] E2E tests[provide a link to the product’s code](https://github.com/department-of-veterans-affairs/vets-website/pull/24060)
- [ ] [Code coverage](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-unit-test-coverageUnitTestCoverage) (provide a link to the product’s code)  
  
**Accessibility artifacts**
  
- [x] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57671). For details, see [Prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).
  
##### Platform actions
- [x] Follow Moderator Responsibilities guidance for Staging Review
- [x] Meeting date/time: **Thursday, June 15, 2023 at 2:00PM Eastern**
- [x] Slack thread with the VFS team: [#vfs-platform-support Slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1686079340637949) 

##### Platform actions

- [x] Update this ticket with the Zoom recording
  - Recording URL: [Link](https://oddball-io.zoom.us/rec/share/nFQ891KKqDtnU63VYpoFqFhZSdz2OyLXcl3niv1nJminIpemMM2fiDEP8l4CAoM3.qLTQ_QMMODsfFmmU)
  - Password: crn2CyU=
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual feedback tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [ ] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [x] Link to the Readiness Review [ticket](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1006) below

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by tbaker1026** [comment]
Form went live - 08/03/2023
