### ISSUE TITLE
New alert: No web or sidekiq pods running

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#54255]
### Summary
If there are no `web` pods or `sidekiq` pods running on a vets-api cluster, we need to be alerted about it. Make sure the alert isn't spammy. The messaging in the alert needs to be actionable. What needs to be done to resolve this alert or what needs to be investigated? If the action items are verbose, add a section to [alerts.md](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/OnCall/alerts.md) and link to it in the alert's message.

Route the alerts by environment (we don't need to wake anyone up in the middle of the night for a non-prod environment) to #oncall, #devops-alerts, pagerduty, or wherever is appropriate. 

*[Confluence documentation on migrating an alert from Prometheus to Datadog](https://vfs.atlassian.net/wiki/spaces/OT/pages/2346844179/Migrate+Alerts+from+Prometheus+to+Datadog)
*[High-level Datadog Confluence documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/2236612646/Monitor+Applications+and+Infrastructure+with+Datadog)

### Tasks
- [ ] Create alert in Datadog (using Terraform)
- [ ] Update alerts.md and add link in alert messaging (if applicable). 
- [ ] After the PR has been approved, get a DevOps eng to run the terraform and merge the PR.

**Comment by RachalCassity** [comment]
@rmtolmach I have web workers alert setup in datadog already if you want see the metrics that were used.

https://vagov.ddog-gov.com/monitors/104669

**Comment by rmtolmach** [comment]
Awesome! 

I will come back to this once higher priority items are complete

**Comment by laineymajor** [comment]
@rmtolmach is this on hold?

**Comment by rmtolmach** [comment]
Finishing up https://github.com/department-of-veterans-affairs/va.gov-team/issues/54219 before moving on to alerts.

**Comment by rmtolmach** [comment]
Starting on this today 👀

**Comment by rmtolmach** [comment]
Looking into Rachal's monitor linked in her comment above. "EKS vets-api-web No Replicas Available" is a monitor for the following query:
```
avg(last_5m):sum:kubernetes_state.deployment.replicas_available{
kube_deployment:vets-api-web,
kube_cluster_name:dsva-vagov-dev-cluster,
kube_namespace:vets-api
} < 0.5
```
`kubernetes_state.deployment.replicas_available` Datadog docs [here](https://docs.datadoghq.com/integrations/kubernetes_state_core/?tab=helm).

We use `minReplicas` and `maxReplicas` to specify the number of pods, so getting the count of available replicas per deployment makes sense. Here is a screenshot of the metric over the last two days for `vets-api-dev`:
![image](https://user-images.githubusercontent.com/10993987/228569138-b36f0bec-09e2-40fe-88bd-bc2e6006c049.png)
The `minReplicas` is set to 4, so this graph looks accurate. There are frequent moments of "No Data" (the gray sections on the graph) which causes an error:
![image](https://user-images.githubusercontent.com/10993987/228570980-e9d176f0-7062-4923-9928-3f8c357fc5d2.png)
I'm looking in ArgoCD and I do see `vets-api-web` pods up, so I think we'll want to do something about instances where the metric can't get any data.

**Comment by rmtolmach** [comment]
* PR is in review: https://github.com/department-of-veterans-affairs/devops/pull/12744

**Comment by rmtolmach** [comment]
PR is merged and I have set up my slack notifications so I will be alerted when one of these alerts comes in.

**Comment by rmtolmach** [comment]
I'm going to close this. There have been no alerts in the last 24 hours. It might need to get fine-tuned at some point.
