### ISSUE TITLE
[FE] Update action link for pre-check-in A/B test top location

### ISSUE THREAD

**Issue by kellysmith1008** [department-of-veterans-affairs/va.gov-team#54250]
## Description

How might we increase the click rate of the action link in pre-check-in, located at the top in its new location, so it sees the same success rate as the existing location link?
How might we ensure that the action link test is relevant to Veterans? How might we increase click-through rate for Veterans?

[Wireframe](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677163894954/45915e9eafcbdb8cb203a8f32eb5608cd73bbf1a?sender=u5d970cc175b184392a004997)

**NOTE: we are only changing the text of the top link**

![image.png](https://images.zenhubusercontent.com/63346ebd45ab78d62eea3201/a5c8b9b2-31c4-4645-8a8c-64b6f35dcc48)

## Tasks
- [ ] Update the top action link only from "Answer questions" to "Complete pre-check-in" 
- [ ] Turn on FF w/ stepped increase in %

## AC
- [ ] Text has been updated to Complete pre-check-in
- [ ] Feature is in production on a stepped increase schedule

**Comment by benbrasso-agile6** [comment]
@loripusey I added a widget into the pre-check-in GA dashboard. https://analytics.google.com/analytics/web/#/dashboard/DgeEvA4JTruKLAW444xXOg/a50123418w177519031p176188361/_u.dateOption=last7days/

@wullaski @brianseek is there a "top-position" variation for each of these GA events? 

nav-check-in-pre-check-in-viewed-introduction-VAOS-design	
nav-check-in-pre-check-in-started-in-person-VAOS-design	
nav-check-in-pre-check-in-started-phone-VAOS-design
