### ISSUE TITLE
New alert: Startup probe failures

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#54254]
### Summary
If a startup probe fails, we need to be alerted about it. But make sure it's not spammy. The messaging in the alert needs to be actionable. What needs to be done to resolve this alert or what needs to be investigated? If the action items are verbose, add a section to [alerts.md](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/OnCall/alerts.md) and link to it in the alert's message.

Route the alerts by environment (we don't need to wake anyone up in the middle of the night for a non-prod environment) to #oncall, #devops-alerts, pagerduty, or wherever is appropriate. 

* [Confluence documentation on migrating an alert from Prometheus to Datadog](https://vfs.atlassian.net/wiki/spaces/OT/pages/2346844179/Migrate+Alerts+from+Prometheus+to+Datadog)
* [High-level Datadog Confluence documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/2236612646/Monitor+Applications+and+Infrastructure+with+Datadog)
* [Datadog metrics explorer](https://vagov.ddog-gov.com/metric/explorer)
* Examples: https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/datadog/catalog

### Tasks
- [x] Create alert in Datadog (using Terraform)
- [x] ~Update alerts.md and add link in alert messaging (if applicable).~ 
- [ ] After the PR has been approved, get a DevOps eng to run the terraform and merge the PR.

**Comment by laineymajor** [comment]
@RachalCassity to provide update on potential solution

**Comment by laineymajor** [comment]
@considerable to complete after dev deprecation work

**Comment by laineymajor** [comment]
@considerable what's going on here? Please update ASAP

**Comment by considerable** [comment]
@LindseySaari - my random searching around concluded that LivenessProbe logs are "swallowed" by the `kubelet` unless there is a failure. Longer answer of the same nature can be found in the [official k8s docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/), which in our case would ask for something like this:
```
kubectl get pods -n vets-api
kubectl describe pod vets-api-web-7898789d48-zcm6s -n vets-api
```
LivenesProbe is called often. If dead, a pod is killed and redeployed quickly, and overall it does not sound like a very good idea to log the churning LivenesProbe activities or alert on the pod being killed and redeployed.

On the other hand, ReadinessProbe is called not so often and can be programmed to output somet text to stdout with `echo` command for which we can monitor and alert.

This [readiness.sh](https://github.com/department-of-veterans-affairs/vsp-infra-clamav/blob/main/readyness.sh) example might log the text for alerting if we chose to deploy it.

**Comment by LindseySaari** [comment]
> @LindseySaari - my random searching around concluded that LivenessProbe and ReadinessProbe logs are "swallowed" by the `kubelet` unless there is a failure. A longer answer of the same nature can be found in the [official k8s docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/), which in our case would ask for something like this:
> 
> ```
> kubectl get pods -n vets-api
> kubectl describe pod vets-api-web-7898789d48-zcm6s -n vets-api
> ```
> 
> LivenessProbe is called often. If dead, a pod is killed and redeployed quickly, and overall it does not sound like a very good idea to log the churning LivenessProbe activities or alert on the pod being killed and redeployed.
> 
> On the other hand, ReadinessProbe is called not so often and can be programmed to output some text to stdout with `echo` command for which we can monitor and alert.
> 
> This [readiness.sh](https://github.com/department-of-veterans-affairs/vsp-infra-clamav/blob/main/readyness.sh) example might log the text for alerting if we chose to deploy it.

Maybe we can do some alerting around the startup probes instead. The readiness probe currently is used to test if a pod is saturated or not. If so, it takes the pod out of rotation (not killing it), checks again, and if healthy, allows the pod to receive traffic again. I would shift this ticket to create some alerting around startup probe failures

**Comment by considerable** [comment]
### 1. Background
Ruby Rails common practice is to use [health_check gem](https://www.rubydoc.info/gems/health_check/1.5.0) for K8s startupProbe.
Vets-API uses it for a number of endpoints that we captured in DD synthetic tests:
```
grep 'url:' devops/terraform/environments/datadog/catalog/synthetics/vets-api.yaml | sort
```
While in the monolith, I picked /v0/backend_statuses that reports 19 active statuses in dev:
```
curl -s https://dev-api.va.gov/v0/backend_statuses | grep -o active | wc -l
```
and 27 active statuses in prod: 
```
curl -s https://api.va.gov/v0/backend_statuses | grep -o active | wc -l
```
### 2. Solution
I could program a startupProbe.sh like
```
#!/bin/sh
if (( 27 == $(curl -s http://127.0.0.1:3000/v0/backend_statuses | grep -o active | wc -l) )); then
  echo "startupProbe Ok"
  exit 0
else
  echo "startupProbe Failed"
  exit 1
fi
```
_Note_: `27 == $(curl...` for prod but `19 == $(curl...` for dev.
### 3. Condition
The IP 127.0.0.1 must be whitelisted in Vets-API for this to work.
Otherwise, connection is rejected:
```
nonroot@vets-api-web-568fc5c896-q8dq2:~$ curl -s http://127.0.0.1:3000/v0/backend_statuses
```
> {"errors":[{"title":"Bad Request","detail":"\"127.0.0.1\" is not a safe host","code":"110","status":"400"}]}

@LindseySaari - may I whitelist 127.0.0.1 ?

**Comment by considerable** [comment]
# Plan B
@LindseySaari 

We leave the startupProbe as is and find the metric that indicates a problem if any.

I mocked a pod that has such a prob and ran it in vets-api dev:
```
# If a container fails its startup probe, it follows the restartPolicy.
# kubectl apply -f startup-probe-demo.yml -n vets-api
# kubectl describe pod startup-probe-demo -n vets-api
# kubectl delete pod startup-probe-demo -n vets-api
---
apiVersion: v1
kind: Pod
metadata:
  name: startup-probe-demo
spec:
  restartPolicy: Always
  containers:
    - name: startup-probe-demo
      image: 008577686731.dkr.ecr.us-gov-west-1.amazonaws.com/dsva/go-httpbin:go-httpbin-v2.3.0
      startupProbe:
        httpGet:
          path: /stats
          port: 9293
          httpHeaders:
            - name: Host
              value: localhost
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 1
        failureThreshold: 3
```
The metric catching the failing probe is `kubernetes_state.container.restarts` :   ![kubernetes_state.container.restarts.png](https://images.zenhubusercontent.com/616758e4c5e87dce2146cdcf/d21d43d2-1189-4a2e-b70b-26b8a799e105)

**Comment by considerable** [comment]
I also found that 
1. such an alert already exists in terraform - [pod_number_of_restarts](https://github.com/department-of-veterans-affairs/devops/blob/77dbc76133d8875e79c92aa6c969e2931db08ec1/terraform/environments/datadog/catalog/eks.yaml#L32-L61)
2. and this DD Monitor did catch my today's activities: [[EKS] Pod restarting](https://vagov.ddog-gov.com/monitors/88843)

The next step, we need to do, is to tune the [values.yaml](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/18ccabf1ff4cb784308d342cbfdca9afd7b66fb9/apps/vets-api/dev/values.yaml#L41-L53) for use in [server-deployment.yaml](https://github.com/department-of-veterans-affairs/vets-api/blob/aeab2bc14c3ee030c8f927fa7a6908cbb30293df/chart/templates/server-deployment.yaml#L64-L72) paying attention for these to stay in the line:
- restartPolicy
- initialDelaySeconds
- periodSeconds
- timeoutSeconds
- failureThreshold

Then test and see the alert/no-alert in slack #platform-datadog-alerts-test 
where the **[EKS] Pod restarting** is currently reported.

**Comment by rmtolmach** [comment]
> If a container fails its startup probe, it follows the `restartPolicy`.

`restartPolicy` is not defined in vets-api app 👀 but [the docs](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy) say the default value is `Always`.

PR:
- https://github.com/department-of-veterans-affairs/devops/pull/12756

**Comment by rmtolmach** [comment]
terraform applied. I will monitor #oncall for instances of this alert.
