### ISSUE TITLE
[FE] SPIKE - How might we setup the VA design system in codepen

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#54264]
## User Story
As a designer or developer, I want to create prototypes using the va design system in codepen so that I can more rapidly test accessibility and design with real users.

## Description
For this spike, determine if we can load the design system web-components and css dynamically. 

Sync with Adam Whitlock on profile team who is doing similar work

## Tasks
- [x] [FE] look into loading the VA webcomponents in code pen
- [x] [FE] Create a new ticket for setting up the library with examples in codepen
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Was able to successfully import va web-components into code pen using a workaround of standing up a GH page that serves the compiled files. Repo here: https://github.com/department-of-veterans-affairs/web-component-wrapper

Will do a bit more work testing things and documenting for the next ticket.

**Comment by brianseek** [comment]
new ticket here: https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/54556

**Comment by brianseek** [comment]
Had sync up with Christina on findings, moving this spike to closed.
