### ISSUE TITLE
Add presumptive conditions info to evidence needed for disability claim page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#54273]
## Issue Description

We had a request from a stakeholder to add presumptive conditions information to our [Evidence needed for your disability claim](https://www.va.gov/disability/how-to-file-claim/evidence-needed/) page.

The information to add is from the presumptive service connection section of this page: https://www.vba.va.gov/pubs/forms/VBA-21-526EZ-ARE.pdf

We'll need to review the page and add a new accordion with this information. 

## Tasks
- [x] Update Drupal page with new info 
- [x] Review (Laura)
- [x] OCTO review (Danielle)
- [x] Send to stakeholders 
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Page is live with presumptive conditions info

**Comment by katherine-fung** [comment]
Hi @laurwill, 

I added information about evidence needed for presumptive conditions to this page: 

http://preview-prod.vfs.va.gov/preview?nodeId=907 

- I added the language to the "Type of claim you're filing" -- "Supplemental Claim" accordion, and a modified version of the same information under "Issue or benefit you're filing a claim for" -- "Presumptive condition" accordion 
- I added the "Type of claim you're filing" and "Issue or benefit you're filing a claim for" H3s. "Issue" is what we currently use on the page 
- There are 9 accordions under the "Issue or benefit you're filing a claim for." Is this too many? Should we break the list up into "Issue you're filing a claim for" and "Benefit your filing a claim for"? 
3 of the accordions (Aid and Attendance benefits and Housebound allowance, Specially Adapted Housing or Special Home Adaptation, Automobile allowance and adaptive equipment) are benefits, rather than issues or conditions (like PTSD, presumptive condition)

**Comment by katherine-fung** [comment]
Hi @laurwill, 

I added information about evidence needed for presumptive conditions to this page: 

http://preview-prod.vfs.va.gov/preview?nodeId=907 

- I added the language to the "Type of claim you're filing" -- "Supplemental Claim" accordion, and a modified version of the same information under "Issue or benefit you're filing a claim for" -- "Presumptive condition" accordion 
- I added the "Type of claim you're filing" and "Issue or benefit you're filing a claim for" H3s. "Issue" is what we currently use on the page 
- There are 9 accordions under the "Issue or benefit you're filing a claim for." Is this too many? Should we break the list up into "Issue you're filing a claim for" and "Benefit your filing a claim for"? 
3 of the accordions (Aid and Attendance benefits and Housebound allowance, Specially Adapted Housing or Special Home Adaptation, Automobile allowance and adaptive equipment) are benefits, rather than issues or conditions (like PTSD, presumptive condition)

**Comment by laurwill** [comment]
Thanks @katherine-fung !
I like your idea to break up that long accordion group — I tried it out with "Additional evidence for certain issues" and "Additional evidence for certain benefits." See what you think. 

@DanielleThierryUSDSVA I started reviewing but I know you've been working on the Supplemental Claims/presumptive conditions work — do you want to review this before it goes to SMEs? So I can pass this off to you or do a full review myself, whichever you prefer.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @katherine-fung @laurwill The way you've broken up the accordions is great!

I made some edits to match the "new and relevant" language on the latest supplemental claims page preview more closely and to make a more clear distinction within the supplemental claims accordion between new and relevant evidence and presumptive claims. Let me know what you think and we can get this to SMEs for review.

-

**Comment by DanielleThierryUSDSVA** [comment]
Hi @katherine-fung @laurwill The way you've broken up the accordions is great!

I made some edits to match the "new and relevant" language on the latest supplemental claims page preview more closely and to make a more clear distinction within the supplemental claims accordion between new and relevant evidence and presumptive claims. Let me know what you think and we can get this to SMEs for review.

-

**Comment by katherine-fung** [comment]
Hi @DanielleThierryUSDSVA, thanks so much for these changes. They look great. I really like how you split the information under the "Supplemental Claims" accordion to address both types of claims.

**Comment by RLHecht** [comment]
Update: We sent this to stakeholders 3/22 for an accuracy review.

**Comment by katherine-fung** [comment]
Hi @DanielleThierryUSDSVA @RLHecht, 

I added links on this page to our pages about different presumptive conditions: 

http://preview-prod.vfs.va.gov/preview?nodeId=907 

(Danielle, in addition to what we discussed on Slack, I added links for asbestos exposure and Projects 112/SHAD.) 

Let me know if I should respond to Melissa's email about the page, in the thread that Randi started. Thanks!

**Comment by katherine-fung** [comment]
Quick update to note that I just emailed Melissa/stakeholders to check about adding links for exposures beyond what's listed in the evidence table of Form 21-526EZ.

**Comment by katherine-fung** [comment]
I've updated the links to not include exposure to asbestos and Projects 112/SHAD testing. I sent the preview link to Melissa and stakeholders on 3/31 to show them where we landed.

**Comment by katherine-fung** [comment]
@megzehn - This page is ready for copy editing: 

http://preview-prod.vfs.va.gov/preview?nodeId=907

Feel free to let me know if you have any questions about it!

**Comment by megzehn** [comment]
Thanks, @katherine-fung! I copy edited this page. 

There's some language in there that I wanted to rework (specifically under "Evidence needed for your disability claim" and some lead-in bullet list language) but I'm going to check with Danielle first, just to make sure I stay within scope.

**Comment by megzehn** [comment]
@katherine-fung, are the changes you made ready to go live? 

Also dropping in some notes for when this page comes up for a PL audit.

________________
Suggestions to consider in the future:

- Rework bullet list intro language "you'll need to submit evidence of:" if we can. 
- Verify if we need to keep the last 2 paragraphs under, "What should the evidence show to support my disability claim?" Or make PL edits.

**Comment by katherine-fung** [comment]
Hi @megzehn - yes, the changes are ready to go live. The stakeholders have seen them. Thanks!

**Comment by RLHecht** [comment]
Changes are live. Closing ticket!
