### ISSUE TITLE
[FE] Update UI to Prioritize Info Messages

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#54279]
## User Story
As a Veteran, I would like to see the most important information highlighted so that I don't get confused by other information on the page.
 
## Wireframes
See [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53566) and [this ticket.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53461)

## Tasks
- [ ] [FE] Update UI to Prioritize Info Messages
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Update from meeting with Ben, this needs to be behind the travel flag. Also Ben to sync with the rest of UX on if all complete pages should move this message out of the info-box.

**Comment by brianseek** [comment]
After talking with Ben we are not doing this for now.
