### ISSUE TITLE
[FE] Remove BTSSS call and the Error Handling from day-of check-in

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#54281]
## Tasks
- [x] [FE] update the useSendTravelPayClaim hook and usage
- [x] [FE] Remove the Error Handling from BTSSS (e.g. duplicate...)
- [x] Create or update unit tests
- [x] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Spoke with Gaurav and got a better understanding of new BTSSS flow. Abandoning first PR in favor of a new one. Work about 80% complete

**Comment by loripusey** [comment]
We will have testing tickets later to validate, closing.
