### ISSUE TITLE
GA4:  Test & Validate - Auto Track Events - Wrap Up

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#54284]
## Issue Description
GA4 auto tracks some standard events such as page views, api calls, etc.  We need to review each auto tracked event to ensure it is working and providing the level of detail we need to support current VFS team needs.

This work began in sprint 21, this is just final check and wrap up before closing.

---
## Tasks
- [ ] Review each auto tracked event
- [ ] Test each auto tracked event
- [ ] Sign-off on or more to custom if needed.

## Acceptance Criteria
- [ ] We have completed the auto tracked events configuration and testing requirements.
---
