### ISSUE TITLE
Update values files generation and workflows

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#54288]
## Issue Description
Some updates are being requested to alter the values files and workflows that generate them as we move through our initiative.
---
## Tasks
- [x] The auto generated values file should reside inside the folder apps/preview-environment/dev/pe-envs folder
- [x] The unique name of each preview environment should be entered in the apps/preview-environment/dev/argocd-apps/values.yaml file
- [x] The values file name should follow a specific format <unique-name-for-each-preview-environment>-values.yaml (This unique name should be present in the above mentioned values file as a list content
- [x] The values.yaml file which is getting auto generated is not up to the mark and doesn't contains all the required values. UID needs to be unique.

## Acceptance Criteria
- [x] Values files are pushed to the correct directory and contain the correct required values.
---

**Comment by CBonade** [comment]
This is done pending testing when the new template file is available to be copied from

**Comment by CBonade** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/12613 this was tested and merged.

**Comment by pjhill** [comment]
In one-off testing this process generates corresponding deployments in ArgoCD -- hooray!
