### ISSUE TITLE
[FE] Update. UI for the "can't check you in scenarios"

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#54280]
Wireframes
See [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53582)

## Tasks
- [ ] Updated UI for the "can't check you in scenarios"
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
@wullaski can you add some screenshots from Cypress? Not sure how we can validate this in staging
cc: @benbrasso-agile6

**Comment by wullaski** [comment]
@loripusey okay to drop them here in this thread? 

### No Travel
![Day-of-check-in--travel-pay--check-in-error--no-travel](https://user-images.githubusercontent.com/2982977/223171335-b312381b-ce55-4cb9-abf5-2b95e88c1d1c.png)
### No to vehicle, Address, or mileage
![Day-of-check-in--travel-pay--check-in-error--no-vehicle](https://user-images.githubusercontent.com/2982977/223171377-f919c3ed-53a3-4516-b3f7-62702b6f0a06.png)
### Yes to all
![Day-of-check-in--travel-pay--check-in-error](https://user-images.githubusercontent.com/2982977/223183512-513d6ad9-700f-4a75-935a-3cb21249c503.png)

**Comment by loripusey** [comment]
These look correct to me. @benbrasso-agile6 @ytsaoca can you validate as well? Thanks.

**Comment by benbrasso-agile6** [comment]
These look correct to me. 

Add a period at the end of all the h1's. 

> We couldn't check you in. 

I believe there's a separate ticket to get the "Need help?" content updated on these pages.

**Comment by wullaski** [comment]
I added a new issue for the missing period.
