### ISSUE TITLE
BE discovery work to change template names in DMC Notifications

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#54314]
## Issue Description
In order to change the template names we need to meet and discuss next steps with the VA Notify team. 

---
## Tasks
- [x] Reach out via VA notify channel and ask about how to change templates 

## Acceptance Criteria
- [x] We can progress forward with updated template names 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Template name functionality has been added to VA Notify portal
