### ISSUE TITLE
Review Lighthouse Sizing of effort and next steps

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#54319]
## Issue Description
As a follow up after #43791 we want to monitor the progress of the lighthouse team sizing work. This issue is to remind our team to check in on the status and once we have sizing and details from them our team (debt team) will need to determine next steps to move forward. 

---
## Tasks
- [ ] Once Adam Foster has sent lighthouse sizing details and timeline we need to review and determine next steps. 

## Acceptance Criteria
- [x] Next steps have been identified and captured in our backlog
- [x] Create the ticket to implement in Epic #72735
- [x] Add in documentation from Lighthouse team to ticket
- [x] Access sandbox 
---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
Let's reach out to Adam Foster to see where the Lighthouse team is at - @ScottyRJames to send email and cc team
Goals are to:
1- Copay balances (in real time) in Corp Data Warehouse
2-  Getting payment data in real time for Veterans

**Comment by HeatherRienks** [comment]
@ScottyRJames - any additional updates on this one that you are aware of? If not, we can intro Kevin and see where Adam and team are at..

Thanks!

Email response from Adam Foster to Scott on August 15, 2023:

Hi Scott-

The good news is that I have found a person who is both a VistA and an Accounts Receivable expert.  I believe that he will be able to work with us to figure out the various VistA routines that are creating the statements that your team uses. 

Our theory right now is that if we can understand those routines, we can re-engineer them on CDW data to get the same results.  There is a member on our team who knows both VistA and CDW.  The plan is to have him work with the Accounts Receivable expert to document the calculations.

Right now the blocker is that our resource is tied up with our server migration.  We expect this to be completed by the end of September.  Once that happens, we’ll get these two geniuses together and start moving things along.

I hope this helps.

Adam

cc: @Tom-Davis @denisecoveyduc

**Comment by asmithgovcio** [comment]
I've done research on how the lighthouse api's are setup however I don't fully understand the purpose of this ticket or what we're really trying to accomplish with this. If the goal is to integrate some of their endpoints into our vets-api codebase then we need those api's to be available to size the effort required.

**Comment by HeatherRienks** [comment]
Got it -thanks for the update. Let's plan to discuss this one in our BE Sync on Monday (2/5/24) and @denisecoveyduc can provide more context around the intent of this ticket.

**Comment by denisecoveyduc** [comment]
Hey all BE sync happened during my afternoon filled with migraine symptoms. Do you need anything right now or should we just add to agenda for an upcoming sync?
@asmithgovcio @HeatherRienks

**Comment by HeatherRienks** [comment]
@denisecoveyduc - let's add to Monday's BE Sync on 2/12

**Comment by HeatherRienks** [comment]
Per Austin, he cannot access sandbox. He will reach out to Jessica Sexton via Slack for next steps.

**Comment by HeatherRienks** [comment]
Per @denisecoveyduc - goal is to confirm that we can access the API endpoint.

**Comment by HeatherRienks** [comment]
@asmithgovcio - do you have any updates on this issue? If you're blocked, please move to "blocked" and let me know if I can help.

**Comment by asmithgovcio** [comment]
@HeatherRienks @denisecoveyduc I think we're really early on this ticket, I spoke with Jessica Sexton who took over for Adam Foster on this work, Adam left that team in September, 2023. Here is what she had to say about sizing of lighthouse efforts. 

<img width="1706" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenBuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd94075b2fe6ec42604102466d7afad99c9c0ff9/Screenshot%202024-02-16%20at%2010.17.03%E2%80%AFAM.png" alt="Screenshot 2024-02-16 at 10.17.03 AM.png" />

**Comment by asmithgovcio** [comment]
Created next steps backlog ticket https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/zh/240

**Comment by asmithgovcio** [comment]
I've created a github repo that contains a script for generating the JWT needed for gaining sandbox access, it can be found at [https://github.com/asmithgovcio/generate-jwt/](https://github.com/asmithgovcio/generate-jwt/) it works great too once you understand how it works.
