### ISSUE TITLE
Gather list of potential empty submission Veterans that have resubmitted FSRs

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#54316]
## Issue Description
Jill would like to know what Veterans may have resubmitted FSRs who previously submitted one that contained an empty submission that did not route anywhere.

---
## Tasks
- [x] Develop script to determine if the user resubmitted
- [x] Provide script to platform team with production access
- [x] Filter out successful resubmitted users

## Acceptance Criteria
- [x] We can provide list of affected Veterans to DMC that have not resubmitted
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Discovered 43 Veterans that were able to resubmit and filtered their ids out of original lost submission CSV
