### ISSUE TITLE
[BE] Text Veteran when Travel Claim Submitted to BTSSS API

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#54348]
## NOTES
We will most likely need to break this ticket down into smaller parts.

## Content
See this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53567) for content of text messages

## Tasks
- [ ] [BE] Text Veteran when Travel Claim Submitted to BTSSS API

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
