### ISSUE TITLE
SB Phase 1: Intake (Part B)

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#54340]
## Purpose
Pick, and start...

Essentially,[ Phase 1](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2436169768/Phase+1+Intake) from the Guide.

## Tasks
Team members will take a pass at validating/updating existing scoring in the  [worksheet](https://docs.google.com/spreadsheets/d/11FIihW9Vn-QJbhwryG9dZ_YQxzI030nAWSwpfX6e-1Y/edit#gid=0) or adding their own (Dan is out this week)
- [x] Taylor
- [x] Bryan
- [x] Nicole

- [x] Prioritize [log](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2445312001/Service+Mapping+artifacts+and+Status+Log) together 
- [x] Select next high priority Scenario to Blueprint

## Acceptance Criteria
- [x] Log prioritized
- [x] Next SB scenario is identified
