### ISSUE TITLE
Research Request - Tech Team 2 - Findings/Presentation

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#54341]
## Issue Description
A Research [Request ](https://dsva.slack.com/archives/CPCGRR7F1/p1666381261475809)was made and our team met w/ TT2 to hear out their thinking.

_From Jesse:  We’d like to gather info from VFS teams regarding their needs for platform monitoring tools. We hope the understand the use cases and how VFS teams might use Datadog for monitoring.
I’d be happy to collab with your team on technical surveys/interviews/etc to collect the info we’re interested in._ 

## Tasks
- [x] Collaborate with TT2 on Recommendations
- [x] Share research findings in OCTO Office Hours (3/7/23)
- [x] Process any applicable feedback from OCTO/Platform Leadership

## Acceptance Criteria
- [x] Research findings are shared with leadership and OCTO-DE
