### ISSUE TITLE
Deprecate GitHub files assigned

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#54347]
## Issue Description
Specific Platform support pages still exist on GitHub. These pages don't have a deprecation notice and it's very likely that many are out of date and no longer relevant. However, they are still being found by VFS team members and it's possible they could be interpreted as valid guidance. We need to ensure all pages that should be deprecated should have a message that points them to the Platform website, as their source of truth.

---
## Tasks
- [x] Review all URLs assigned: https://docs.google.com/spreadsheets/d/1pTzNDqb8jg9_zEYOsTsgsEIbcKUEo8UbIiPHXSwkAz8/edit#gid=0

- [x] If GitHub file does not have a deprecation message, add it to page.

## Acceptance Criteria
- [x] All assigned GitHub files will be deprecated with a message pointing to the Platform website.

_- Lauren taking over Samara's github chunk_

**Comment by vbellissimo** [comment]
This task is pending Samara's PIV re-instatement and re-associating the VA's GitHub to Samara's GitHub account.
