### ISSUE TITLE
Evaluate use of persistent volumes in EKS for FE image

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#54355]
A previous attempt was made at exploring this option - it did not bear fruit initially, but we'd like to re-evaluate it...  This language was from the initial task:

# Description
Given the fact that the `content-build` Drupal cache takes a very long time to resolve and requires an internal connection to VA resources, we should research the use of persistent volumes in EKS to store the Drupal cache for use by multiple preview environments. Using a persistent volume to store the Drupal cache is more efficient since the volume could be mounted by multiple PEs instead of retrieved individually for each PE.

Additional brainstormed attributes for the proposed solution are --
1. Use AWS' EFS to provision a persistent volume
2. Use GHA to sync new builds to the persistent volume when a new version of the Drupal content gets deployed OR use GHA to sync new builds to the persistent volume on a fixed schedule like every hour

# Tasks
- [ ] Determine what technology could be used for the persistent volumes in EKS
- [ ] Could a single persistent volume be used by multiple preview environments?

# Acceptance Criteria
- [x] An assessment of how Drupal cache might be retrieved to a persistent volume and mounted in EKS is available in Confluence or in this ticket

**Comment by JoeTice** [comment]
Refer to any info included in [53452](https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/53452)

**Comment by JoeTice** [comment]
These tasks were dependent on viable options from the original, and may need to be recreated...
[53453](https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/53453)

[53455](https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/53455)

**Comment by pjhill** [comment]
Our high level evaluation is here -- https://vfs.atlassian.net/wiki/spaces/TT4/pages/2564030583/Configure+Preview+Environments+to+use+a+persistent+volume+for+static+content
