### ISSUE TITLE
Product Template Library

### ISSUE THREAD

**Issue by lkoenigsberg** [department-of-veterans-affairs/va.gov-team#54350]
## What are building
Building out a library of templates that product managers can use

## Why are we pursuing this opportunity/problem
The library will allow product managers to spend more time managing and less time creating artifacts that are mostly repeatable.  Also allows us to have a bit more guidance on what things we've seen work - how we work. 

---
## Tasks
- [ ] Lorem

---
## Definition of Done
- [ ] identify existing versions of each item within the various components of OCTO (ask everyone in product ops to weigh in and then put out a question with list we have in the #product channel.
- [ ] use CoP meetings to review status and get feedback or competing version from product people
- [ ] identify the processes and docs in place that use existing versions
- [ ] identify any work currently underway to update related docs or processes
- [ ] coordinate with the product ops team to create a single, OCTO version of each item
- [ ] update doc links, archive old docs, and update processes to direct users to the new version
- [ ] ensure the new version is listed in onboarding docs and processes

---
## How to configure this issue
- [ ] **Review issue** with the Product Ops team
- [ ] **Prioritize**  
  - label accordingly: 
    - Low Priority - 🟢
    - Medium Priority - 🟠
    - High Priority - 🔴
- [ ] **Add Assignees** (who will do this work?)

**Comment by lkoenigsberg** [comment]
Pulled from the roles & responsibilities research feedback:

- Could help to have a template of monthly report of qual/quant data about project?
- Is there a good example of how to write a KPI anywhere that we recommend OCTO folks follow?
- It would be really helpful we have performance setting and tracking examples that we all can follow and reuse.
- Multiple people requested "links" to vision, goals, strategy, okr, etc  (i.e., guidance, templates)
