### ISSUE TITLE
Supplemental Claims | Small content updates

### ISSUE THREAD

**Issue by rocio-desantiago** [department-of-veterans-affairs/va.gov-team#54368]
## Value Statement
- Consider breaking apart big paragraph in opt-in page to three smaller paragraphs for easier reading
  > - ![screenshot_2023-02-24_at_1 41 49_pm_480](https://user-images.githubusercontent.com/37054305/222051582-d839d0ed-8efc-40ee-8952-e85c3e07ce87.png)

- Replace `Change` with `Edit`
  > ![screenshot_2023-02-27_at_5 21 49_pm_720](https://user-images.githubusercontent.com/37054305/222051793-f8eecb24-3548-4cbd-98af-78ebff5a772f.png)

---
## Acceptance Criteria

- [ ] Sentences into separate paragraphs 
- [ ] Word changed

- [ ] User receives a notice for unsuccessful submissions
- [ ] Unit tests complete (90% coverage)
- [ ] E2E tests complete
- [ ] Accessibility testing complete
- [ ] Reviewed and approved by product and/or design

## Designs and Build Notes
- [DESIGN](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/p/665AA990-66CC-4CD9-9B1D-62D737DA2223/canvas)
- [CONTENT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/sourceofcontenttruth.md)
- [Prototype](https://www.figma.com/proto/JveclTFbNNSmx4eiYwbZdZ/Supplemental-Claims?node-id=70%3A5676&scaling=scale-down&page-id=10%3A1697&starting-point-node-id=70%3A5676)

## Tasks
- [x] _Design_
- [x] _Content_

## Definition of Ready
- [ ] _Clear value description_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [ ] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by rocio-desantiago** [comment]
@joshkimux ready for validation

**Comment by joshkimux** [comment]
Will check this tomorrow when it (hopefully) makes it to staging!

**Comment by joshkimux** [comment]
<img width="586" alt="Screenshot 2023-03-02 at 4 56 38 PM" src="https://user-images.githubusercontent.com/14154792/222567670-d17ee6eb-27f8-490b-9582-c2eb48212dda.png">
<img width="582" alt="Screenshot 2023-03-02 at 4 56 14 PM" src="https://user-images.githubusercontent.com/14154792/222567694-7eaa64a2-48cc-438c-a445-037b5c2a3409.png">

Confirming both are fixed! Awesome work as always @rocio-desantiago 🥳
