### ISSUE TITLE
Move deploy job back to it's own GHA

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#54369]
## Description

The `workflow_run: on: complete` only works in default branches (eg. vets-api master). We were seeing an issue in EKS where the image tag for vets-api was getting updated **before** to image was pushed to ECR, causing a crashloopbackoff on the pod until the image existed. 

I [pushed this change](https://github.com/department-of-veterans-affairs/vets-api/commit/e6993f36fab93e153956b9fa294e89f213615f83) to add the ECR push and manifest update to the same job. This allows us to run the ECR job **before** updating the manifest image tag. Again, you can't do the on: workflow complete on a non-master branch, so **this is a bandaid until we can make k8s the master branch**. 

I [left a comment here](https://github.com/department-of-veterans-affairs/vets-api/commit/e6993f36fab93e153956b9fa294e89f213615f83#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R50) for what we need to do once k8s=master

I've temp removed the [commented out workflows in this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/13696). We will want to put this back upon k8s merge to master

## Tasks
- [ ] Break apart deploy job to its own GHA
- [ ] Update GHA to the latest version.
- [ ] Test in all applicable environments
- [ ] Document the process that was undertaken to break the deploy job out
 
## Success Metrics
- [ ] Deploy job gets its own GHA, which lowers the code complexity by isolating it to its own workflow. 
 
## Acceptability Criteria
- [ ] Deploy job has its own GHA 
- [ ] Deploy job functions as expected.

**Comment by RachalCassity** [comment]
This might be blocked by the preview-environments. A team is currently developing them and using the master branch.

**Comment by jennb33** [comment]
10/7/2024 update: this ticket can be closed because we don't use K8s any longer. Closing this ticket.
