### ISSUE TITLE
[FE] My VA Audit improvements: [QA finding] Copy in Claims and appeals error message is incorrect

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#54379]
## Background
Per [QA findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/README.md#findings) (test case 10), the copy in the Claims and appeals error message is incorrect. The title needs to be updated to match documentation and sketch files.

On staging, the error message title reads: "We can't access any claims or appeals information right now."

In our [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/claims-and-appeals-FE-documentation.md#error-states), the title reads: "We can't access your claims or appeals information"

## Screenshots
| Staging | Sketch |
|--|--|
| <img width="462" alt="qa-test-9-macos-safari-01" src="https://user-images.githubusercontent.com/8542413/222261216-01965303-7c0b-4793-943b-c5eedaefd7a5.png"> | ![Screenshot 2023-03-01 at 3 48 06 PM](https://user-images.githubusercontent.com/8542413/222261506-960ebdd5-d81b-44d4-bb38-2adf3e0a3875.png) |

## Tasks
- [x] Update copy in error message 
- [x] Re-test 
- [x] PM to mark resolved in QA findings doc

## Acceptance Criteria
- [x] Claims and appeals error message title reads "We can't access your claims or appeals information"

**Comment by allisonlu** [comment]
Currently writing a unit test for the `ClaimsAndAppealsV2` component, which I adopted from the unit test for the old ClaimsAndAppeals. I have some questions for @aagosto90:

- I know [this FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/claims-and-appeals-FE-documentation.md) is the most updated, but there are some discrepancies between the [list of test cases](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva.md#test-cases-for-apply-for-benefits) and the [Claims and appeals specs document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/claims-and-appeals-status.md).
- Should the header **Claims and appeals** be visible when the section is loading data (i.e. user seeing the loading spinner, should they also see the h2?)
- If user has no recent activity in the last 30 days, should they see this text: "**You have no claims or appeals updates in the last 30 days**"?
- If user has lacks both claims and appeals services, should the header **Claims and appeals** be visible?
- When user has no open claims or appeals, but does have an appeal that closed within the past thirty days, should the CTA link **Check your claim or appeal status** be visible?

**Comment by aagosto90** [comment]
Hey @allisonlu , sorry for the confusion with the old documentation. That's correct that this [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/claims-and-appeals-FE-documentation.md) is the most updated.

- Yes, the header should be visible with the loading indicator while the section is loading.
- Follow guidance in the FE documentation above: A user should see a card for the latest status update as long as they have or claim or appeal open or one that has been closed in the last 60 days.
- Yes, follow guidance in the FE documentation above: This section will now be visible to all LOA3 users.
- Follow guidance in the FE documentation above: When a user has a claim or appeal closed within the last 60 days, show a card for the recently closed claim or appeal as well as the "Manage all claims and appeals" link.

Let me know if any of this is confusing r if you have any other questions :)

**Comment by allisonlu** [comment]
Confirmed copy is updated on staging with test user 10!

**Comment by ajakabcin** [comment]
Thanks @allisonlu closing
