### ISSUE TITLE
[FE] My VA audit improvements: [QA finding] "Learn about VA debt" link needs to be right-aligned on desktop

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#54387]
## Background
Per [QA findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/README.md#findings) (test case 18), when a user has no debts but has copays in the Outstanding Debts section on My VA, the "Learn about VA debt" secondary link should be right aligned on desktop. On staging the link appears left-aligned immediately below the copy card.

Incorrect on staging: 
![Screenshot 2023-02-23 at 3 35 14 PM](https://user-images.githubusercontent.com/45603961/222209026-27624c43-279f-4d27-9d05-e3a2eeedf98c.png)

Per [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/outstanding-debts-FE-documentation.md#learn-about-va-debt-link) it should be right-aligned when the user has a copay or an outstanding debt.

## Tasks
- [ ] Implement fix so that "Learn about VA debt" link appear right-aligned on desktop
- [ ] Re-test 
- [ ] PM to mark resolved in QA findings doc

## Acceptance Criteria
- [ ] The Learn about VA debt link appears right-aligned on desktop

**Comment by BerniXiongA6** [comment]
When @allisonlu gets back, let's find out how many points are left on this.

**Comment by allisonlu** [comment]
Most changes have been made, just need to check (and/or update) some e2e tests

**Comment by BerniXiongA6** [comment]
Hi @allisonlu as Sprint 6 is coming to a close tomorrow, is there any concern about getting this ticket completed by then? Curious to see how many points are left and if you need any help -- thank you! cc: @ajakabcin

**Comment by allisonlu** [comment]
hoping to wrap this up and open a PR by eod today! so hopefully get it merged by tomorrow and validated by Wednesday

**Comment by BerniXiongA6** [comment]
thank you @allisonlu !!

**Comment by allisonlu** [comment]
PR is approved and merged! I think it _just_ missed the daily deploy unfortunately. I'll let you know when it's up on staging for validation (might be tomorrow after or during planning)

**Comment by allisonlu** [comment]
Ready for validation on staging! Log on as test user 36

**Comment by BerniXiongA6** [comment]
Thanks @allisonlu -- logged in as user 36 and it looks great! But we can wait for @ajakabcin to Validate before closing the ticket.

**Comment by ajakabcin** [comment]
Confirmed as well! thank you!
