### ISSUE TITLE
[FE] My VA Audit improvements: [QA finding] Health care error copy is incorrect, secondary links display (desktop & mobile)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#54384]
## Background
Per [QA findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/README.md#findings) (test case 15), there are two main issues with the health care error state when the health care API call fails.

1. The  copy in the Health care error message is incorrect. 

- On staging, the error message title reads: "We can’t access your appointment information"
- The error message should read as documented [here](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/1Kq3lea) and [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/health-care-FE-documentation.md#error-state-1-the-health-care-api-call-fails-cant-tell-if-user-has-va-health-care-or-not)

2. Additionally, the health care secondary links all appear below the error message on staging. They should not appear at all when the health care API fails. The user should only see the error message, per [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/health-care-FE-documentation.md#error-state-1-the-health-care-api-call-fails-cant-tell-if-user-has-va-health-care-or-not).

### Screenshots 
| Staging | Sketch |
|--|--|
| <img width="460" alt="qa-test-15-macos-chrome-01" src="https://user-images.githubusercontent.com/8542413/222262863-1f7cbadb-5718-4af2-9e11-f7bd289fcfe4.png"> | ![Screenshot 2023-03-01 at 3 54 18 PM](https://user-images.githubusercontent.com/8542413/222262812-9d5171d9-6497-49ca-8e71-80ac106d0dd6.png) |

## Tasks
- [ ] Update copy in error message 
- [ ] Implement fix so that health care secondary links do not display when this error is triggered
- [ ] Re-test 
- [ ] PM to mark resolved in QA findings doc

## Acceptance Criteria
- [ ] Health care error message title reads "**We can't access any health care information right now** We're sorry. Something went wrong on our end. If you get health care through VA, you can go to My HealtheVet to access your health care information. [Visit My HealtheVet](https://www.myhealth.va.gov/mhv-portal-web/home)
- [ ] No health care secondary links display when this error is triggered

**Comment by ajakabcin** [comment]
Closing this ticket - nothing to address here. When we were testing the error states the appointments error (seen above in the staging screenshot) was triggered when we manually blocked the appointments endpoint, therefore this is working correctly/as intended.
