### ISSUE TITLE
[FE] My VA audit improvements: [QA finding] Health care section seems to disappear entirely on Safari (desktop)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#54386]
## Background
Per [QA findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/README.md#findings) (test case 15), the health care section seems to disappear entirely on Safari desktop. Please investigate and determine route cause and resolution.

## Tasks
- [ ] Investigate issue (time box yourself to 30-45mins)
- [ ] Implement fix so that health care section does not disappear
- [ ] Re-test 
- [ ] PM to mark resolved in QA findings doc

## Acceptance Criteria
- [ ] Health care section appears appropriately on Safari desktop

**Comment by allisonlu** [comment]
Retested on 3/1, around 4:30p ET and Health care section is appearing as intended. QA findings include copy not matching the Sketch file and secondary links are appearing below the alert. 

<img width="531" alt="qa-test-15-macos-safari-01" src="https://user-images.githubusercontent.com/8542413/222268948-dd327a67-e714-4728-aa5d-dd817ac0b1fd.png">

I'm going to update the cell in the spreadsheet and close this ticket, since this will be addressed in #54384.
