### ISSUE TITLE
Clean up test application teams in GitHub

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#54388]
**Problem Statement**
At one point, we had helm test apps to test in sandbox. These are no longer needed, so the apps **are** deleted. There are GH teams attached to these apps, and potentially some additional config. GH teams and (potential) additional config needs to be cleaned up. Without doing this now, it would become tech debt.

**Issue Description**
_What details are necessary for understanding the specific work or request tracked by this issue?_
[_Additional documentation and/or slack threads linked here_
](https://adhoc.slack.com/archives/C045LCF8WU8/p1677688780556159)

---
**Tasks**
- [ ] gather all the test app GH teams
- [ ] ensure ryan is added as an admin so he can work on this as needed
- [ ] review manifests in app of apps repo
- [ ] delete the ^ teams
- [ ] delete config not needed
- [ ] test to ensure there are no sync issues

**Acceptance Criteria**
- [ ] GH teams that are attached to the helm test apps (that have been deleted) are removed
- [ ] Any misc config is deleted
- [ ] testing passes = no sync issues

**Comment by laineymajor** [comment]
Would like @rjohnson2011 to do this

**Comment by RachalCassity** [comment]
GH Action clean up, I will take this on.

**Comment by LindseySaari** [comment]
Hoping to extend our access for another three months on this. Thread here as [our three months is up](https://dsva.slack.com/archives/C04CYC4LMU6/p1683121982155209?thread_ts=1682946024.814299&cid=C04CYC4LMU6) as of two days ago

**Comment by laineymajor** [comment]
Could be linked to the 500s errors
