### ISSUE TITLE
Add mock MVI responses for debt users

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#54396]
## Issue Description
Mockdata identity changes were not updated for all users, to allow for successful sign in and LOA we need to add the mvi profile mock responses for our team's users and any data needed for them. 

---
## Tasks
- [ ] Add mock response for user 80
- [ ] Add mock response for user 81
- [ ] Add EDIPI identifier to responses

## Acceptance Criteria
- [ ] We have a way to successfully login with our users locally
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/264) is open but awaiting review and merge

**Comment by HeatherRienks** [comment]
@ScottyRJames - just checking in to see if you have any updates on this.

**Comment by ScottyRJames** [comment]
@HeatherRienks This has been merged
