### ISSUE TITLE
[FE] My VA audit improvements: [QA finding] "Continue your application" link should be active link style

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#54394]
## Background
Per [QA findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/README.md#findings) (test case 33), when the user has Applications in progress they see the draft application card.  The link to "continue your application" should be the active link style, per designs. On staging, the styling is currently incorrect.

Steps to reproduce:
1. Navigate to staging.va.gov
2. Log in with user 220
3. Scroll to Benefit Application Drafts section
4. See draft cards
5. See link for "continue your application"
6. Compare styling to same link in [sketch file](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/oYlrJn2) and in [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/applications-FE-documentation.md#benefit-application-draft-card) (see "Visual specs" under Benefit application draft card section) ❌ 

## Tasks
- [x] Change "continue your application" link to active link styling
- [x] Retest
- [ ] PM to update QA findings documentation

## Acceptance Criteria
- [ ] "Continue your application" link should be active link style

## Resources
Incorrect on staging for user 220:
![Screenshot 2023-03-01 at 1 03 10 PM](https://user-images.githubusercontent.com/45603961/222224250-a7be903a-7d49-47c0-86b1-8cc67d618798.png)

Correct styling from sketch:
![Screenshot 2023-03-01 at 1 05 23 PM](https://user-images.githubusercontent.com/45603961/222224737-08ea95d8-cd2a-4240-8415-293d6657c5f2.png)

**Comment by allisonlu** [comment]
Note to dev:

The current link styling is coming from a [homegrown `CTALink` component](https://github.com/department-of-veterans-affairs/vets-website/blob/639b5213acea962c93a59875460408f748b24217/src/applications/personalization/dashboard/components/CTALink.jsx#L1), but we want to migrate this to the [VA design system Link web component](https://github.com/department-of-veterans-affairs/vets-website/blob/68b8eb0396f7cc6c2736986fb0ce81e452011c62/src/applications/personalization/dashboard/components/apply-for-benefits/ApplicationInProgress.jsx#L62-L68), which will include all styles and GA tracking. We'll have to update corresponding unit and e2e tests as well.

See [ApplicationInProgress component](https://github.com/department-of-veterans-affairs/vets-website/blob/68b8eb0396f7cc6c2736986fb0ce81e452011c62/src/applications/personalization/dashboard/components/apply-for-benefits/ApplicationInProgress.jsx#L62-L68): 
```
          <CTALink
            ariaLabel={`Continue your ${formTitle}`}
            text="Continue your application"
            href={continueUrl}
            onClick={recordDashboardClick(formId, 'continue-button')}
            showArrow
          />
```

**Comment by BerniXiongA6** [comment]
Hi @dellerbie -- will any of this work carry over and if so do you have an estimate of how many points are left?

**Comment by dellerbie** [comment]
@BerniXiongA6 No, should not carry over. Will merge later today.

**Comment by ajakabcin** [comment]
Confirmed on staging with user 220
![Screenshot 2023-03-15 at 3 46 39 PM](https://user-images.githubusercontent.com/45603961/225425760-d16469f5-a310-4cff-a4a7-2f8ad6126d9c.png)


Closing - thank you!
