### ISSUE TITLE
[FE] My VA audit improvements: [QA finding] Incorrect "view your payment history" link when no recent payments & on payment error

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#54391]
## Background
Per [QA findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/README.md#findings) (test case 26), when the user does not have recent payments, but has received payments in the past, the user sees text "You don't have any recent payments to show" and they also see links to "Manage your direct deposit information" and a link to "Review your payment history."

Additionally, in test case 30, when the payment API call fails, the same link is also incorrect. Shows as "View your payment history" instead of "Review your payment history" (screenshot below)
 
On staging the "Review your payment history" link is incorrect - it is appearing as "_View_ your payment history" instead of _Review_

## Steps to reproduce
1. Navigate to staging.va.gov
2. Log in with user 0 (has no recent payments)
3. Scroll to Benefit Payments section
4. See "You have no recent payments to show"
5. See "Manage your direct deposit information"
6. See "_View_ your payment history" ❌ 

### Screenshots 
**Test case 16 - user has no recent payments** 
|  **Staging** ❌ | **Sketch** ✅ |
|--|--|
| ![Screenshot 2023-03-07 at 12 00 32 PM](https://user-images.githubusercontent.com/45603961/223494753-b8da6e46-18f1-4aeb-b4d6-6cc5aea21405.png) | ![Screenshot 2023-03-07 at 12 00 47 PM](https://user-images.githubusercontent.com/45603961/223495046-74b1ac65-0337-43cb-a845-4d2d947c2b8e.png) |

 **Test case 30 - payments API call error** 
|  **Staging** ❌ | **Sketch** ✅ |
|--|--|
|![Screenshot 2023-03-07 at 2 52 12 PM](https://user-images.githubusercontent.com/45603961/223537509-9deacd40-7e05-4188-b576-edc69b580630.png)| ![Screenshot 2023-03-07 at 2 52 16 PM](https://user-images.githubusercontent.com/45603961/223537634-0c906a78-09f7-4f04-8e60-8fe17a0c88d8.png) |

## Tasks
- [ ] Change text of link to read "Review your payment history"
- [ ] Retest
- [ ] PM to update QA findings documentation

## Acceptance Criteria
- [ ] When a user does not have recent payments, but has received payments in the past, they see a link to "_Review_ your payment history."

**Comment by ajakabcin** [comment]
@dellerbie I just came across the incorrect "view your payment history" link (instead of _review_) in the payments API error state as well. I added screenshots for both. Not sure if this requires a separate fix than in the original scenario outlined (when the user has no recent payments) but I wanted to flag just in case! Let me know if you have any questions!

cc @allisonlu @aagosto90

**Comment by BerniXiongA6** [comment]
Hi @dellerbie -- will any of this work carry over and if so do you have an estimate of how many points are left?

**Comment by dellerbie** [comment]
> Hi @dellerbie -- will any of this work carry over and if so do you have an estimate of how many points are left?

No, will not carry over. I will merge today

**Comment by ajakabcin** [comment]
Looks good on staging for test case 16:
![Screenshot 2023-03-15 at 3 44 17 PM](https://user-images.githubusercontent.com/45603961/225425317-ec3e3651-724f-43ef-87f1-4b819d7d3a74.png)

@dellerbie could you share a screenshot of the error state with the link corrected? I wasn't sure how to manually trigger that.

**Comment by ajakabcin** [comment]
Confirmed error state as well (test case 30)

<img width="491" alt="image (2)" src="https://user-images.githubusercontent.com/45603961/225654576-fa37c5ba-45db-457b-b80d-610183bbadcd.png">
