### ISSUE TITLE
Remove combined FSR references in BE

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#54397]
## Issue Description
The combined FSR has been launched since 9/2022 and references to the BE forking logic can be removed. We will want to keep the feature flag in place since FE still has uses for it

*Not urgent to complete*

---
## Tasks
- [ ] Remove references to check if flipper enabled for `combined_financial_status_report`
- [ ] Update logic to assume flipper is enabled 

## Acceptance Criteria
- [ ] The BE assumes that cFSR is turned on
- [ ] The flipper still exists for FE usage
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
@ScottyRJames - in prep for tmrw's planning session, just curious if this is a ticket that has any dependencies on FE work, or if we should consider adding this into Sprint 97?

**Comment by HeatherRienks** [comment]
Kevin to merge!
