### ISSUE TITLE
[FE] My VA Claim Status EVSS > Lighthouse: Technical discovery

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#54406]
## Background
We need to do some technical discovery around what needs to be done to update the My VA claim status integration to connect to Lighthouse (instead of EVSS, current integration). We'll need to identify what frontend updates need to be made, and to confirm backend needs, if any.

**Critical**: our team _should_ only have to make frontend updates as we believe the claim status team (`#benefits-claim-appeal-status` on slack) has completed the migration of the claim status tool from EVSS > Lighthouse. We need to double check with them to confirm this. _The claim status team is responsible for the backend_.  
 
## Tasks
- [ ] Review current implementation documentation of claim status and EVSS 
- [ ] Meet with Tom  and Jerek Shoemaker to familiarize yourself with EVSS vs Lighthouse
- [ ] Confirm with claim status team (PM is Jacob Worrell) that they have completed their side of the claim status tool migration (EVSS > Lighthouse)
- [ ] Identify what needs to be done on our side from frontend perspective to update the claims widget to Lighthouse
- [ ] Identify what needs to be done on our side from backend perspective to update the claims widget to Lighthouse
- [ ] Document a recommendation for how we will test this (code, but also QA, UAT?)

## Acceptance Criteria
- [ ] We have a write up in GH outlining what we needs to be done/gives us an understanding of how to migrate the claims widget on My VA from EVSS to Lighthouse

## Resources
- Slack thread [here](https://dsva.slack.com/archives/C04KHCT3ZMY/p1678121172227809)

**Comment by ajakabcin** [comment]
@dellerbie given that the claims team hasn't completed their part of this migration I'm going to put a hold on this ticket for a sprint or two. We have plenty to keep us/you busy for at least the next sprint. Thanks! 

cc @BerniXiongA6

**Comment by ajakabcin** [comment]
@dellerbie here's the [shell](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/claim-status-lighthouse-migration/technical-discovery.md) for your technical discovery - I included some placeholder sections but feel free to revise as you see fit! And [here's another technical discovery doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/frontend/adding-new-onsite-notification.md) that @allisonlu put together for onsite notifications - again just an example :)
