### ISSUE TITLE
[PM] My VA Claim Status EVSS > Lighthouse: Submit collab cycle ticket

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#54404]
## Background
We need to submit the collab cycle ticket to complete the claim status integration from EVSS to Lighthouse on My VA. 

This includes creating a draft project outline.

## Tasks
- [x] Create draft project outline (link project epic in outline)
- [x] Submit collab cycle ticket (link collab cycle epic in outline)
- [x] Link collab cycle epic to project epic

## Acceptance Criteria
- [x] Draft outline exists
- [x] Collab cycle epic exists
