### ISSUE TITLE
[FE] My VA: Review disabled E2E tests for flakiness

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#54402]
## Background
Per slack thread, there are 43 E2E tests in `vets-website` that are disabled due to flakiness. The full list is available [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/currently-disallowed-cypress-test-specs-on-va-gov). We need to review them for anything from My VA and fix them.

## Tasks
- [ ] Review the list of disabled e2e tests
- [ ] Fix any pertaining to My VA

## Acceptance Criteria
- [ ] all My VA e2e tests currently disabled due to flakiness are fixed

## Validation
- _Who can validate this ticket?_  any dev
- _How can this work be validated?_ check tests and ensure they are properly reenabled 

## Resources
- [Slack thread](https://dsva.slack.com/archives/CE4304QPK/p1677517472776789)

**Comment by BerniXiongA6** [comment]
Hi @dellerbie -- will any of this work carry over and if so do you have an estimate of how many points are left?

**Comment by adamwhitlock1** [comment]
Validated that the e2e test has been put back into rotation, and if it gets added back to the disabled list, then will revisit the test and evaluate a rewrite of it.
