### ISSUE TITLE
Update grandfathering content based on Login.gov feedback

### ISSUE THREAD

**Issue by tygindraux** [department-of-veterans-affairs/va.gov-team#54416]
## Problem statement
Veterans need to make migrate their DS Logon accounts to Login.gov through grandfathering, which allows them to defer identity proofing.

## Initiative
We have designed 2 grandfathering user flows for the first round of testing with Veterans. We've asked Login.gov's Auth team and Identity Verification team if they have time to review our initial design work sync or async. 

We're meeting on Monday, March 6 at 2:30pm EST.

## Acceptance Criteria
- [x] Updates have been made to content based on Login.gov's recommendations

## Tasks
- [x] attend meeting with Login.gov on Monday, March 6 at 2:30pm EST.
- [x] @CarlDickerson update content in modal based on feedback from Login.gov
- [x] @CarlDickerson update content in email based on modal
