### ISSUE TITLE
[EOAS] Update fwdproxy configurations

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#54411]
## Background
Currently the staging fwdproxy is pointing to the SSO version of EOAS's production URL. We have confidence that submissions to the new URL works and are ready to promote the URL to the production fwdproxy. We should use `vaww.ssoboss.cem.vaec.va.gov` as the new host.

### Staging fwproxy
* Existing host: `vaww.ssoboss.cem.vaec.va.gov`
* New host: `ssobeta.cem.vaec.va.gov`
* Relevant file: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/fwdproxy-vagov-staging.yml#L142-L149

### Production fwdproxy
* Existing host: `vaww.boss.cem.vaec.va.gov`
* New host: `vaww.ssoboss.cem.vaec.va.gov`
* Relevant file: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/fwdproxy-vagov-prod.yml#L147-L154

* Preneeds form url: https://staging.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/introduction

## Next steps
This should be the last of the changes needed to the fwdproxy config for EOAS

## Tasks
- [ ] Switch URL in prod fwdproxy config to requested one
- [ ] Switch URL in staging fwdproxy config back to the staging one

## Acceptance Criteria
- [ ] Prod fwdproxy URL has been updated
- [ ] Staging fwdproxy URL has been updated
