### ISSUE TITLE
IA of VA.gov — IA Redesign for Online Tools

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#5441]
## Summary
- **The inability to scale digital tools on VA.gov while maintaining findability in the current IA** is a pain point for **VFS teams and Veterans.**
- We believe **decoupling tools from benefit hubs and otherwise reorganizing the information architecture of VA.gov** will help solve it by **providing a clear, scalable solution for digital tools that VFS teams can adhere to.**
- We’ll know we’re right if **the IA health (including findability) of digital tools on VA.gov stays steady or improves as the website expands.**

### User Story

As a Veteran or other VA.gov users, I need to be able to find tools that help me complete key tasks on VA.gov, so that I can apply for/manage/track my benefits etc.

### Problem Statement

How might we reorganize key products and tools within the VA.gov information architecture to decouple them from the benefit hubs? 

## VSP Objective (Q1 & Q2 2020)

- O2: Customers use qualitative and quantitative user data to build and iterate on VFSs.

## Measuring Success (KRs/KPIs)

VSP KR: Increase in VA.gov user satisfaction
IA health of VA.gov as measured in #3676

## Details and Notes

Currently, the information architecture of VA.gov has authenticated and unauthenticated tools scattered across multiple benefit hubs. This causes a variety of problems that all negatively impact the findability of key tasks on VA.gov. As the tools become more broad and apply to multiple benefit hubs, it becomes harder to find them buried in a single benefit hub (ex. If a disability claims tool became a benefits claims tool, expecting users to find it through the disability hub is no longer feasible). 

Some specific problems: 
- We need to better surface tools to users in the unauthenticated experience. 
- We don’t have a single home for profile-related tools. 
- Tools are scattered across multiple benefit hubs. 
- We have a general need to flatten the information architecture in order to improve findability and navigational tools.

### Links

- [List of current and planned VA.gov digital products](https://docs.google.com/spreadsheets/d/1ZxWZzZmoI5tIUKl4UdxLIz6exAu0eQVdbb5_-KRIIqQ/edit?usp=sharing)

### Goal(s)

- Veterans can find what they need on VA.gov
- VFS teams understand the VA.gov ecosystem into which their products fit
- The IA of VA.gov can scale to support an increasing number of products
- The IA of VA.gov is better able to support an authenticated homepage

## Definition of Done

- [x] Compile list of existing and planned digital tools on VA.gov
- [x] Draft reorganized IA that decouples tools from benefit hubs
- [ ] Complete user testing 
- [ ] Finalize reorganized IA for VA.gov

## We'll know we're done when
- DEPO has accepted recommendation, work has been handed to teams, and we have baseline metrics in place for IA quality on VA.gov

**Comment by mnorthuis** [comment]
Prior to research getting started, we need to communicate out proposed approach for testing, gather info on impacts to teams, and break down an implementation plan.

**Comment by mnorthuis** [comment]
Older issue.  This work is being broken up and will tracked as we get to it.  Closing.
