### ISSUE TITLE
Retire 'Collab Cycle Feedback for Staging' gh issue template

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#54424]
## User Story
As an OCTO lead, I want to remove some of the unused gh issue templates in the VA.gov team repo so that VFS and Platform teams are not overwhelmed with niche, outdated and unnecessary templates.

Assignee: @sterkenburgsara 
Peer Reviewer: @briandeconinck 

## Description
Dan Kosko of the OCTO Product team reached out to see if any of the templates that Governance team uses or has used can be retired. After reviewing the templates, Governance team PM decided that the "Collab Cycle Feedback for Staging" gh issue template can likely be retired. This template is only used 1) if a Gov team member misses the DraftingTemplate deadline for Staging Review or 2)if additional findings for the product/feature are found post-Staging Review. 

The purpose of this ticket is to retired the 'Collab Cycle Feedback for Staging' gh issue template, however still save the markdown text within the template as a code block on Confluence. This way, if Governance team members need to create a new Staging Review findings ticket, they can copy/paste the markdown into a blank issue template. 

## Impacted Artifacts
[Collabo Cycle Feedback for Staging](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-feedback%2C+Staging&template=collab-cycle-feedback-staging.md&title=VA.gov+category+issue+-+VA.gov+Issue+Description+%28Category+Number.Issue+Number%29) gh issue template
[collab-cycle-feedback-staging.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/collab-cycle-feedback-staging.md)
[How to document feedback for Staging Review - Things to keep in mind as a reviewer](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+feedback+for+Staging+Review#Things-to-keep-in-mind-as-a-reviewer)
New artifact - [Staging Review findings - issue template](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2548957608/Staging+Review+findings+-+issue+template)

## Tasks
- [x] Copy the markdown from the 'Collab Cycle Feedback for Staging' gh issue template to the code block of the new Staging Review findings - issue template 
- [x] The instructions in the 'Collab Cycle Feedback for Staging' gh issue template should not remain in the code block as it is no longer necessary. Ensure they are added as instructions within the 'Staging Review findings - issue template ' Confluence page
- [x] In the 'How to document feedback for Staging Review' Confluence doc, the section, 'Things to keep in mind as a reviewer' should be modified to reference the new 'Staging Review findings - issue template ' Confluence page
- [x] Review Confluence pages under Staging Review to ensure there are no other references to the 'Collab Cycle Feedback for Staging' gh issue template. If so, document in this ticket and consult with Peer Reviewer and/or PM on what action to take.
- [x] When all changes to Confluence are complete, delete the collab-cycle-feedback-staging.md file

**Note**: This ticket may interfere with ticket #53595 since changes will be made to all operational docs for Staging re: use of the word, "feedback." Please consult with Assignee for #53595 to ensure no duplicate work and/or gaps occur (**Follow-up on note:** it was determined that the template name and usage of the label 'collab-cycle-feedback' both use the name feedback. The name of this template can be changed, but team will be retaining historical label for tracking purposes).

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The 'Collab Cycle Feedback for Staging' template is no longer an issue template in the va.gov-team repo
- [x] Governance team is still able to create a Staging Review findings issue ticket outside of the DraftingTemplate and/or post-Staging Review that follows the framework of the 'Collab Cycle feedback for Staging' gh issue template 

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@sterkenburgsara @briandeconinck just assigned today. Please review the ticket and let me know if you have any concerns.

**Comment by sterkenburgsara** [comment]
@shiragoodman Re: the second task (removing the instructions from the code block, and instead adding them to the Confluence page) - I'm not sure that is better - I'm worried that many of us will come here to copy/paste the .md code and may miss those instructions if they're not in the code block. Thoughts?

**Comment by shiragoodman** [comment]
Whatever works for the team is fine with me. My thoughts were that the VFS team doesn't need to see the instructions that we follow for populating the ticket, so why add to the ticket if we can avoid it? but if you think it'll be better for Gov team, then go for it. It's not going to make it challenging and/or more difficult for VFS teams to interpret our findings.

**Comment by sterkenburgsara** [comment]
@shiragoodman hmm, that is true. I'll play around with it. Thanks!

**Comment by shiragoodman** [comment]
also, it may be worth noting that when we generate issue tickets via the DraftingTemplate, the instructions are not included.

**Comment by sterkenburgsara** [comment]
@shiragoodman these directions need some finesse anyway, so moving out of template and fleshing them out. [This template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/collab-cycle-feedback-staging.md) is referred to as "Collab Cycle Feedback for Staging" and pre-populates the label `collab-cycle-feedback` which likely needs to be updated, so I will sync with @CherylEvans to ensure that a clean swap of "feedback" with "finding" is appropriate here. // cc @briandeconinck

**Comment by shiragoodman** [comment]
@sterkenburgsara see my comment here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/53595#issuecomment-1454145959

**Comment by sterkenburgsara** [comment]
In [this ticket regarding the removal of "feedback" at staging review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53595) it was decided to retain the label 'collab-cycle-feedback' on github issue tickets. Just FYI that in light of that decision, you will see that label on the artifacts impacted by this ticket as well. cc @briandeconinck

**Comment by sterkenburgsara** [comment]
@shiragoodman noticing that this template we're deprecating never pre-populated with `CC-Dashboard` label. It isn't in the code block. Do we need to do an audit to capture any tickets that were posted after staging reviews retrospectively since they aren't being reflected in Domo? Let me know if I should add a backlog ticket for that. // cc @briandeconinck

**Comment by sterkenburgsara** [comment]
@briandeconinck ready for your review. I haven't deleted the template on GH yet, I want to get your approval on the confluence documents before I take that last step. Thanks!

**Comment by shiragoodman** [comment]
@sterkenburgsara good catch. We began logging staging review findings that are issue-focused/linked to the VA.gov Exp Stds in August 2021. We have used the Collab Cycle Feedback for Staging template probably only a handlful of times, so it is possible that they may have some missed labels. I'm not opposed to an audit, but it may be more time consuming than it's really worth. Please go ahead and make the ticket and we can pick up as tech-debt at some point.

**Comment by sterkenburgsara** [comment]
@shiragoodman will do.

**Comment by briandeconinck** [comment]
@sterkenburgsara I left one comment on the new [Staging Review findings - issue template](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2548957608/Staging+Review+findings+-+issue+template) page in Confluence. I think we can remove the top section of the code block, since that's coming from the issue template in GH and won't make sense to copy/paste into a blank issue.

Otherwise this all looks good and I think you can delete the GH template when ready!

**Comment by sterkenburgsara** [comment]
@briandeconinck got it - I see the comment and it is a great point! I just made those changes on Confluence and will go ahead and remove the GH template.
