### ISSUE TITLE
Supplemental Claims | Add OAR content changes

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#54439]
## Background Context
THE VBA (OAR department) requested some content changes due to a regulation amendment and associated policy and manual changes.

[Link to documented changes](https://docs.google.com/document/d/1wdIAYNRfMatFZq1oXU4JqW5DCXwaB3zYV-kUi-3OoTg/edit)

## Acceptance Criteria
- [ ] Form shows a plain language version of this: _"The instructions on VA Form 20-0995 (page 1) includes the statement, “You are entitled to a hearing at any time in the claims process. If you wish to have a hearing, you can contact us online through Ask VA: https://ask.va.gov/ or call us toll-free at 1-800-827-1000 (TTY:711).” This language was added at the recommendation of OGC who identified that VA did not advise within the form that a hearing is available, and therefore, is an error in VA’s duty to assist, causing an increase in settlements. Therefore, OAR recommends this language be added to the instructions within the API at a location deemed appropriate by the ABD/VA.govteam."_
"
- [ ] Form shows a plain language version of this (framed as a recommendation): _"The instructions on VA Form 20-0995 (page 1) includes the statement, “If you are filing a Supplemental Claim within one-year of a decision from the United States Court of Appeals for Veterans Claims, United States Court of Appeals for the Federal Circuit, or Supreme Court of the United States, identify the date of the court decision in item 13B and attach a copy of the decision within this form.” This verbiage was requested by Compensation Service, and was required as part of a legal issue due to a regulation amendment and associated policy and manual changes. Therefore, OAR recommends this language be added to the instructions within the API at a location deemed appropriate by the ABD/VA.gov team."_
- [ ] _AC_

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
Do we need to include thie one?
_"Statement: By filing a Supplemental Claim online you are opting into the new decision review process. The decision to opt-in must be done within 60 days from the date you received your Statement of the Case or Supplemental Statement of the Case. When you do this, we'll move your issues from the old appeals process to the new decision review process. Once you opt-in, you cannot return to the legacy system for the issues you have selected. Once you are in the modernized system, you may change your review option in accordance with the applicable procedures before we render the supplemental claim decision on your selected issues. If you wish to continue your appeal in the old process, please refer to your decision letter for further details."_

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by eileen-coforma** [comment]
@saderagsdale @Mottie Screens attached in design notes. Let me know if you have any questions.

**Comment by saderagsdale** [comment]
Sade and Eileen to update AC @eileen-coforma @saderagsdale

**Comment by eileen-coforma** [comment]
@Mottie @saderagsdale Updated the Design and Build notes with the content source of truth direct links for content.

**Comment by eileen-coforma** [comment]
@Mottie @saderagsdale Added the copy updates to Notice of Evidence Needed. That was also a new OAR requirement, and not reflected on staging.

**Comment by saderagsdale** [comment]
@eileen-coforma @Mottie for the second AC we prob don't need to use the phrase "item 13B" since that's only for the paper form.
