### ISSUE TITLE
[FE] My VA Audit improvements: Investigate strange behavior with appointments API error 

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#54438]
## Background
Per [QA findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/README.md#findings) (test case 16), when the appointments API errors out, we're seeing some strange behavior with the error message in the health care section.

We need to investigate the code further to determine if this is a real issue or a product of staging and trying to manually create an API error. 

## Tasks
- [ ] Investigate behavior
- [ ] Determine if a fix is needed
- [ ] Implement, if needed
- [ ] Retest
- [ ] PM to update QA findings documentation

## Acceptance Criteria
- [ ] TBD

**Comment by ajakabcin** [comment]
no longer seeing this issue closing, will reopen if we encounter further issues with error messages
