### ISSUE TITLE
[FE] My VA Audit improvements: [QA finding] Health care - Incorrect behavior on appointments API error when user has unread messages

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#54437]
## Background
When the appointments API errors out, the user should see an error message and four left-aligned links (immediately below the error message):
![Screenshot 2023-03-06 at 3 55 17 PM](https://user-images.githubusercontent.com/45603961/223228665-4b82b5f6-8ebd-4a32-89f2-02625bbfb37d.png)

We missed an edge case scenario where a user could have unread messages as well. In that scenario, where the user has unread messages, _and_ the appointments API errors out, the user should see

1. the unread messages alert
2. the appointments API error message
3. three left aligned secondary links immediately below the error message for: 1) Refill and track your prescriptions, 2) Request travel reimbursement, and 3) Get your VA medical records and lab and test results (note that they would not see the link for Send a secure message because they have unread messages).
 
Per [QA findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/README.md#findings) (test case 16), currently on staging, in the scenario described above, the user with unread messages is seeing the unread messages alert, the appointments error _and none of the secondary links._ We need to fix that.

## Tasks
- [x] Correct the logic so that when a user has unread messages and the appointments API fails, the user sees the unread messages alert, error message on appointments, and the 3 secondary links  for 1) Refill and track your prescriptions, 2) Request travel reimbursement, and 3) Get your VA medical records and lab and test results
- [x] Retest
- [ ] PM to update QA findings documentation

## Acceptance Criteria
- [ ] When the user has unread messages and the appointments API fails the user sees the unread messages alert, the appointments API error message and the 3 secondary links for 1) Refill and track your prescriptions, 2) Request travel reimbursement, and 3) Get your VA medical records and lab and test results

**Comment by BerniXiongA6** [comment]
When @allisonlu gets back, let's find out how many points are left on this.

**Comment by allisonlu** [comment]
@ajakabcin Ready for validation!

Steps to test:
1. Log into staging as cecil.morgan@id.me
2. Open dev tools on your browser. If you're using Chrome, press **F12** or **Cmd+Option+I** (that's a capital i) and Navigate to the **Network** tab
4. Refresh, find or filter to an `appointments?` row under **Name** panel
5. Right click, click **Block request URL**. Another panel should pop up at the bottom of your dev tools
6. `staging-api.va.gov/vaos/v2/appointments?...` should show up with a checkmark next to it
7. Hover and click the pen icon to edit, and delete everything after the ? and replace it with an asterick so it becomes `staging-api.va.gov/vaos/v2/appointments?*`
8. Refresh and confirm that you see the unread messages warning, appointments API error, and three secondary links (left-aligned) 

I recorded a screen share in case my instructions are confusing:
https://www.loom.com/share/049af5f470f849f3a11d1e6b964af4ba

**Comment by ajakabcin** [comment]
Amazing! Thanks again for the thorough instructions - confirmed on staging:

![Screenshot 2023-03-24 at 3.06.15 PM.png](https://images.zenhubusercontent.com/60465863a45e7b63743045b3/dc204972-f782-4190-be8f-ad10aaafab76)
