### ISSUE TITLE
Login.gov adoption team: Sprint 15 (3/2 - 3/15)

### ISSUE THREAD

**Issue by elizabethkochBT** [department-of-veterans-affairs/va.gov-team#54458]
## PTO

- Carolyn: 3/10, 3/13

## Sprint 15 Priorities

Organic adoption:
 - Collaboration Cycle kickoff
 - Design Intent
 - Sitewide Content & IA Intake Request

Grandfathering migration:
 - Submit prototypes for Midpoint Review
 - Submit documents for Research Review (includes kicking off recruitment with Perigean)
 - Supporting Sitewide Content/IA/Accessibility to create a sitemap and build out user flows

Dashboard: 
 - Iterate on dashboard & start automating ETL
 - Agree on consolidated list of KPIs and begin mapping them to the dashboard crawl/walk/run plan
 
Address review feedback on:
 -  MHV inheritance alternate controls document (and share with Login.gov)
 - In-person proofing product brief

 
## Retro Board

[Sprint 14 Retro](https://www.reetro.app/board/63e5271aabe3b3a8ca8cda88/63ffa0f4bba9aef9664d9ca7)

### Discussion Topics/Retro Action Items
 - [x] Mural Retro
 - [x] Async standup on Fridays
 - [x] New meeting cadence invites
 - [x] Move random 4th to chat during standup
 - [x] More strategic synchronous sprint planning

### Legacy credential migrations & Login.gov proactive adoption

 - [x] Collaboration Cycle for [Login.gov adoption team, Organic Adoption] #54326
 - [ ] Organic Adoption - Modal Display Logic (Front End) #54478
 - [ ] Organic Adoption - Modal Display Logic (Back End) #54479
 - [ ] Analytics tagging for organic adoption experiment #53788
 - [x] Update grandfathering content based on Login.gov feedback #54416
 - [ ] Support Sitewide IA to map user flows and sitemap for DSL migration #54013
 - [x] Baseline data analysis next steps #52976
 - [x] Update grandfathering content based on sitewide content's feedback #53490

## Collab Cycle Tasks 
 - [x] Design Intent - IA Feedback - Login.gov adoption team, DS Logon Grandfathering / Inherited Proofing #53254
 - [x] Design Intent - Accessibility Feedback - Login.gov adoption team, DS Logon Grandfathering & Inherited Proofing #53333
 - [x] Submit artifacts for Research Review #53384
 - [x] Submit prototype(s) for Midpoint Review #53383
