### ISSUE TITLE
Organic Adoption - Modal Display Logic (Front End)

### ISSUE THREAD

**Issue by holytoastr** [department-of-veterans-affairs/va.gov-team#54478]
## Issue Description
Organic adoption experiment will be limited to users who have logged in with dsl and do not have a login.gov account. The experiment will run only when the flag is enabled. The user will only see the modal once per day.

---
## Tasks
- [x] Establish connection between backend service and front end
- [x] Dismissal logic for 24 hours no matter which button clicked

## Acceptance Criteria
- [x] Only displays modal if user logs in with dsl
- [x] Does not show if user has an alternative login.gov or idme account
- [x] Only displays model if user is part of the experiment
- [x] Once the modal is dismissed, does not show the modal again for 24 hours
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
