### ISSUE TITLE
Add VA Github Organization to Platform Orientation template

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#54471]
## User Story
As a VFS team member, I want to be informed that I must be added to the VA Github Organization by my own teams leadership so that I am not blocked at getting GH/ZH access by Platform.

As a Governance team PM, I want VFS team members to know that they must be added to the VA Github Organization so that I no longer have to point them to the guidance on Platform Website, causing delays in getting them access to the vets.gov-write gh team.

Assignee: @briandeconinck 
Peer Reviewer: @it-harrison 

## Description
Too many VFS team members don't realize that they must be added to the VA Github Organization by someone from their team (preferably leadership) prior to Platform adding them as a team member to the vets.gov-write gh team - a team that grants access to commonly used repos.

## Impacted Artifacts
[Platform orientation template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=analytics-insights%2C+analytics-request%2C+governance-team%2C+platform-orientation&template=orientation-epic.md&title=Platform+Orientation+Template+%5BYour+name+here%5D)

## Tasks
- [x] Under General, create a new checkbox item: "Confirm that you have access to the VA GitHub Organization"
   - should link out to guidance on Platform Website re: [VA Github Org](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-GettingaccesstotheVAGitHuborganization)
- [x] Add note below checkbox stating that being a member of the VA Github Organization is a prerequisite for getting access to vets.gov-write. Platform will not be able to complete this task if you are not a member of the VA GitHub Organization.
- [x] Create pull request for review

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] New VFS team members are notified through Platform Orientation that they must be a member of the VA Github Organization 

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
@it-harrison See PR #56155, ready for review.. Let me know if the way I've worded things makes sense and if the placement in the task order makes sense.

**Comment by it-harrison** [comment]
@briandeconinck looks good!
