### ISSUE TITLE
[BE] Execute loadtest script using Docker CLI command

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#54488]
## User Story
As a platform engineer, I want to execute the load test script from the docker container to run all the module load tests simultaneously.

## Timeline
Platform team planning to complete load test between **March 16 - March 28**

## Description
Platform team wanted to run vets-api check-in loadtest script in [K6](https://github.com/department-of-veterans-affairs/devops/blob/40651_check-in_load_test_scripts/loadtest/check_in/k6/script.js) or [Locust](https://github.com/department-of-veterans-affairs/devops/blob/40651_check-in_load_test_scripts/loadtest/check_in/check-in/locustfile.py) using Docker CLI (Reference [Slack Thread](https://dsva.slack.com/archives/C04M7T1CZAS/p1677707089742809?thread_ts=1677177578.577589&cid=C04M7T1CZAS))

**Sample Command:**
```
docker run --rm -v `pwd`/loadtest:/loadtest -i locustio/locust:2.14.2 \
  -u 5 -r 5 -t 60s --headless --only-summary -H https://dev-api.va.gov \
  -f /loadtest/search/search_locust.py 
```

## Tasks
- [ ] [BE] **Choose between K6 vs Locust**
- [ ] [BE] **Remove hardcoded load config (if K6)**
- [ ] [BE] **Modify script to accept load from command line**
- [ ] [BE] **Investigate docker command to execute load test script**

## Acceptance Criteria
- [ ] Run load test using docker command against staging with a small load
- [ ] Unblock platform team with docker command to execute the load test script
