### ISSUE TITLE
:orange_circle: Upload Product Documentation and Templates to OCTOPUS

### ISSUE THREAD

**Issue by dmkosko** [department-of-veterans-affairs/va.gov-team#54504]
## What are building
We are building out a Product CoP page on OCTOPUS which will house all product-related documentation, templates, and other beneficial information.  

## Why are we pursuing this opportunity/problem
One of our goals is to provide a single source of truth for all existing product people here at OCTO and new hires that come aboard. We feel giving everyone a single location that will house this information will help to decrease the amount of time it takes to onboard and understand the environment. Also, we hope to cut down on any "recreating the wheel" of designing PowerPoint decks, reports, and other templates which will give teams a spot to look for anything they may need from a product perspective.     

---
## Tasks
- [x] Meet with Michelle to understand the process of uploading content to OCTOPUS
- [x] Confirm who will be doing the work (her or myself based on their process)
- [x] Demo for Lisa before saying we're "done" 

---
## Definition of Done
- [x] identify existing versions of each item within the various components of OCTO (ask everyone in product ops to weigh in and then put out a question with list we have in the #product channel.
- [x] use CoP meetings to review status and get feedback or competing version from product people
- [x] identify the processes and docs in place that use existing versions
- [x] identify any work currently underway to update related docs or processes
- [x] coordinate with the product ops team to create a single, OCTO version of each item
- [x] update doc links, archive old docs, and update processes to direct users to the new version
- [x] ensure the new version is listed in onboarding docs and processes

---
## How to configure this issue
- [x] **Review issue** with the Product Ops team
- [x] **Prioritize**  
  - label accordingly: 
    - Low Priority - 🟢
    - Medium Priority - 🟠
    - High Priority - 🔴
- [ ] **Add Assignees** (who will do this work?)

**Comment by dmkosko** [comment]
- [ ] Dan to ensure Lisa and I have edit access to OCTOPUS by 3/10

**Comment by dmkosko** [comment]
Michelle Correll will enter in our updates and will let me know when the page's contents are ready to be reviewed.

**Comment by dmkosko** [comment]
Lisa has editing access, Michelle to work on getting Dan those same permissions

**Comment by dmkosko** [comment]
Michelle and Kasey working on uploading content this week, will share page with Lisa once updates are final

**Comment by dmkosko** [comment]
The Product CoP page has been updated and a link to the site has been sent to the Prod Ops team. Link is below.  

[Product CoP](https://dvagov.sharepoint.com/sites/oitocto1/SitePages/Product-CoP.aspx?csf=1&web=1&e=j1AmHz)

**Comment by dmkosko** [comment]
Comm going out on 3/27 out to the following channels:
[#vfs-all-teams](https://dsva.slack.com/archives/CE4304QPK) 
[#general](https://dsva.slack.com/archives/C03FECE9K)
va-cto-product
va-cto-portfolios
#platform-team (private Platform channel)

Comm being sent is:

The Product Operations group now has an OCTOPUS site dedicated to the CoP and it is available [here](https://dvagov.sharepoint.com/sites/oitocto1/SitePages/Product-CoP.aspx?csf=1&web=1&e=j1AmHz). Our goal is to provide a place for product information to be available for new
hires and existing employees. This is V0 and, like many things we do, we'll iterate on it as we learn and grow. We always appreciate feedback and if you’d like to provide any on this initiative or future ones, please visit us at the [#product-operations](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdsva.slack.com%2Farchives%2FC03H546LHDY&data=05%7C01%7C%7Cda2ce13a2cca4c9e629408db2701e300%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638146661276670685%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=uuZluu74Z9sUzrlCBhF0MigPXMAR1Q9cBMAhYSn3gb4%3D&reserved=0).
