### ISSUE TITLE
Intent To File(ITF) - GET - Abstract provider call

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#54508]
## Issue Description
The eVSS is being deprecated and the vets-api utilizes these services to retrieve and post data.
One of these services is the Intent To File service that indicates user's intention to file a claim for benefits and is filed when a user starts a new claim.
This eVSS endpoint is being sunsetted with the eVSS in Aug.

We need to migrate any calls to the eVSS intent to file endpoint to the Lighthouse version.

---
## Tasks
- [ ] Audit all calls to eVSS services within the functionality
- [ ] create (a) provider(s) - evss 
- [ ] Create Response object - what data field(s) are being sent and received from the eVSS endpoint by the 526 form?
- [ ] Create a unit test for the provider

## Acceptance Criteria
- [x] Form 526: no changes to intent to file functionality
- [x] Maintain test coverage?
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
cc @colevoss @navaeddie @ahay-agile6 @sethdarragile6
