### ISSUE TITLE
Find Forms Audit Presentation

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/va.gov-team#54548]
## Issue Description
With the completion of the [find forms audit](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/contact-center/medallia-audits/find-forms.md), a presentation needs to be built and delivered.

---
## Tasks
- [x] Build a slide deck for the audit
- [x] Identify 3 key areas to draw attention to

## Acceptance Criteria
- [x] Slide deck has been built
- [x] Recommendations / screenshots have been added

**Comment by ianMcCullough-ob** [comment]
[SlideDeck for presentation](https://docs.google.com/presentation/d/1FMiSGx-kpOnJqt5FYimHiXzHNtujoFgc1YSdcHRWthU/edit#slide=id.g1a8ba499737_0_94)

**Comment by ianMcCullough-ob** [comment]
The slide deck as been completed, @Solarith added screenshots and summary statements of 3 key problem areas identified through the research.
