### ISSUE TITLE
Emergency Care searches

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#5455]
**PLACEHOLDER**
This work will be dependent on PPMS data structure

## User Story:
As a Veteran, I need to know the differences in my options for emergency care so that I can choose the best place to seek care. 

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] First thing we need to do - x hour(s) - Owner
- [ ] Second thing we need to do - y hour(s) - Owner
- [ ] Third thing we need to do - z hour(s) - Owner
- [ ] etc

## Acceptance Criteria:
[ ]  Veterans understand why 'in network' is important

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
closing as a duplicate
