### ISSUE TITLE
Update COVID faqs page with new mask guidance

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#54551]
## Issue Description

VHA has released new mask guidance at VA facilities. We need to update our [Coronavirus FAQs](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/) page with this new information.

## Tasks
- [x] Update page in Drupal
- [x] Copyedit (Megan)
- [x] Publish (Megan)
- [x] Open translation ticket (Randi)

## Acceptance Criteria
- [x] Changes are live on the site

**Comment by RLHecht** [comment]
This is published. Will open translation ticket and will close once validated.

**Comment by RLHecht** [comment]
This is live. Closing ticket.
