### ISSUE TITLE
Profile: Sprint 6 (3.15.23 - 3.28.23)

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-team#54553]
## Sprint 5 Retro
[Link to EasyRetro board](https://easyretro.io/board/f4051524-d7be-43a4-8c50-f43d887f3a7f/582750af-29a5-4718-b452-627d865a648e)

## Sprint 6 Notes
Sprint 6 epic was created from [this project outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/sprint-objectives/profile/sprints-1-10-Jan23-May23.md#sprint-6-315---328) 

## PTO
- Samara OOO 3/15
- Liz mostly out on 3/27
- Flo OOO 3/27

## Sprint Goals
- Direct deposit migration EVSS > Lighthouse
- Logged-in IA/nav research
- Accessibility updates
- Other / general

##  Direct deposit migration EVSS > Lighthouse
(From the roadmap: Direct deposit for comp & pen information on VA.gov is currently supported by EVSS. However, EVSS is going away in 2023 and EVSS integrations are in the process of moving over to the Lighthouse platform... once we can start moving over our integration from EVSS to Lighthouse, we'll work closely with Lighthouse to get this functionality updated, tested, and launched.) Project outline [at this link](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit/evss-lighthouse-migration#readme).

(From Samara notes: Needs to be thoroughly tested before a monitored, phased launch. For CY Q2, conduct QA, go through pre-launch activities, and launch the updated integration.)

PM - Berni
- [ ] #54870

Design - Florence
- [x] User acceptance testing (UAT) planning #54999 
- [x] Conversation guide #55000 

FE - Adam 
- [ ] #54879

BE - Tom

Note: We had to add some tickets that were not originally planned, so this will likely push backend build into April.

- [x] #54883 (3 pts)
- [ ] #54887 (3 pts)
- [ ] #54879 (3 pts)
- [x] #54763 (2 pts)

## Logged-in IA/nav research
(From the roadmap: We're aware of some high-level problems people have navigating the logged in experience on VA.gov -- eg. if a link isn't on the homepage or My VA, people tend to have trouble finding what they need. However, we've never conducted more holistic research that evaluates navigating the logged in experience. This research effort aims to dive deeper into users' problems with and expectations around navigating VA.gov once they're signed in. We'll be partnering with Mikki to conduct a research review, analytics review, and user research that will be used to inform work throughout this calendar year.) Research outline [at this link](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/ia-and-navigation/2023-generative-logged-in-research#readme).

Design - Liz
- [x] User research conversation guide #54776 (Already pulled in during Sprint 5)
- [x] Recruiting #54777

## Accessibility
(From the roadmap: There are quite a few design updates that are complete and need to be implemented. We should wrap up frontend implementation on these tickets ahead of moving on to other work.)

FE - Adam
- [x] Update All Profile pages to new info card component #53632 (AW broke down ticket to 3 pts)
- [x] #53631 (carry over 1 point, work is mostly done)

## General
Design - Florence
- [x] #53227 (carry over 3 pts) -- this can get pushed out to Sprint 7, if needed

Design - Liz
- [x] #54938
- [x] #54046 (pulled in and started at mid-point Sprint 6, can carry over to Sprint 7 if needed)

## Notification Settings (carry over only)
FE - Adam
- [x] #53545 (only 1 pt left, carried over from Sprint 5 -- needs PR review)

## Unplanned
 FE - Adam 
- [x] #55590 (2 pts)

**Comment by Samara-Strauss** [comment]
I removed #54973 from this epic, as we no longer need to do that work.

**Comment by BerniXiongA6** [comment]
Thanks @Samara-Strauss for the update!

**Comment by Samara-Strauss** [comment]
Great job on completing sprint goals, Team!
