### ISSUE TITLE
[FE] Setup codepen templates

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#54556]
## Description
Set up codepen templates for the UX team to use to create prototypes. See details from spike: https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/54264

Set up web-components using GH page: https://github.com/department-of-veterans-affairs/web-component-wrapper

Note: This may need to get setup in a free account for now until we figure out which codepen (paid) account to use. 

## Tasks
- [x] [FE] Create minimal header pen
- [x] [FE] Create minimal footer pen
- [x] [FE] Create validate page example
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
here are a few pens:
design system import: https://codepen.io/brian-seek/pen/dyqWbVB
minimal header: https://codepen.io/brian-seek/pen/mdGxPPE
page wrapper sample: https://codepen.io/brian-seek/pen/vYzmNjZ

**Comment by wullaski** [comment]
Footer: https://codepen.io/wullaski/pen/abaYzRR

**Comment by loripusey** [comment]
@brianseek @wullaski did we finish this work or does it need to rollover?

@sarahknoppA6

**Comment by brianseek** [comment]
This can get closed.
