### ISSUE TITLE
Design & Research Share Presentation Build

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/va.gov-team#54550]
## Issue Description
A slide deck needs to be built for the Design & Research share on March 20th. This will review the Medallia data retrieval process as well as the analysis process.

---
## Tasks
- [x] Write an outline of the slide deck
- [x] Review outline with Naomi
- [x] Create slide deck
- [x] Practice run slide deck to determine presentation duration

## Acceptance Criteria
- [x] Slide deck has been created and tested

**Comment by ianMcCullough-ob** [comment]
[WIP Outline doc](https://docs.google.com/document/d/1eZJH48uSMV0ZLLbJYxRKmRO2LTCajMRSFMXX3vOwpK8/edit)

I'm working through an outline to send to Naomi prior to building the whole slide deck.

**Comment by ianMcCullough-ob** [comment]
[WIP Slide deck](https://docs.google.com/presentation/d/18NDyplNurmbUDCrGboYvigoV1gkeLKdzk4d-02aSSHM/edit#slide=id.g21b99f20ef7_0_18)

**Comment by ianMcCullough-ob** [comment]
The presentation has been discussed with Naomi, will be delivering it on 3/20 to the design and research share.
