### ISSUE TITLE
Tagalog translation: Update mask guidance on COVID FAQs page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#54569]
## Issue Description

We made changes to the mask guidance for both low and medium risk levels on our [COVID FAQs](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/) page. We need to send this content to translators and update the Tagalog Drupal page.

Word doc sent to translators: [https://app.zenhub.com/files/133843125/8ea4a56a-6ace-4772-bca8-9852d2a84bfa/download](https://app.zenhub.com/files/133843125/8ea4a56a-6ace-4772-bca8-9852d2a84bfa/download)

Note that I only highlighted the changed content in the low risk bullets but this also needs to be updated in the medium risk section too.

## Tasks
- [x] Send text to translators (Randi)
- [x] Update Drupal (Ana/Aliyah)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Tagalog page is live with changes

**Comment by RLHecht** [comment]
Content back from translators: [https://app.zenhub.com/files/133843125/15312b3e-6986-4a3b-9e37-bfd71062d14f/download](https://app.zenhub.com/files/133843125/15312b3e-6986-4a3b-9e37-bfd71062d14f/download)

**Comment by RLHecht** [comment]
Hi @ABeltran77 can you compare what's in the bullets for masking below against the PDF that the translators sent back and let me know if everything looks ok? I copy and pasted so it should be fine but we always want a second set of eyes on everything. Thanks! 

![Screen Shot 2023-03-10 at 1.47.50 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/96b8bdf7-68c6-413d-857f-7e8089b8e0cf)

**Comment by ABeltran77** [comment]
It looks fine.

**Comment by RLHecht** [comment]
Just published. Moving to validate.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
