### ISSUE TITLE
Spanish translation: Update mask guidance on COVID FAQs page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#54568]
## Issue Description

We made changes to the mask guidance for both low and medium risk levels on our [COVID FAQs](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/) page. We need to send this content to translators and update the Spanish Drupal page.

Word doc sent to translators: [https://app.zenhub.com/files/133843125/8ea4a56a-6ace-4772-bca8-9852d2a84bfa/download](https://app.zenhub.com/files/133843125/8ea4a56a-6ace-4772-bca8-9852d2a84bfa/download)

Note that I only highlighted the changed content in the low risk bullets but this also needs to be updated in the medium risk section too.

## Tasks
- [x] Send text to translators (Randi)
- [x] Update Drupal (Ana/Aliyah)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Spanish page is live with changes

**Comment by RLHecht** [comment]
Word doc back from translators: [https://app.zenhub.com/files/133843125/907ed026-30f7-4086-80d4-e39aaf7ffdfd/download](https://app.zenhub.com/files/133843125/907ed026-30f7-4086-80d4-e39aaf7ffdfd/download)

**Comment by RLHecht** [comment]
@ABeltran77 Can you review the screenshot of the changes I made? You only need to look at the "Cubrebocas" bullet in both the low and medium risk section.

![Screen Shot 2023-03-10 at 1.32.46 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/a09668aa-f8f3-43a8-a4ff-400a697d165d)

**Comment by ABeltran77** [comment]
In the "Cubrebocas" bullets for both low and medium levels the word
mascarillas, which appears a total of three times, needs to be replaced
with "cubrebocas".

**Comment by RLHecht** [comment]
Thanks. I made those changes and published. Moving to validate.
