### ISSUE TITLE
Connection Config for BQ data import/export

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#54562]
Based on learnings from Search Discovery  that BQ is not pulling the data in, it is being pushed in by external services which is why we cannot find the details in BQ.  If we start using the Data Transfer Service then we would have more insight into data types. flows and costs.  

As such we need to explore how we should manage data imports to BQ and define a process that will provide detail needed for this ticket and support this [cost management]( https://github.com/department-of-veterans-affairs/va.gov-team/issues/49506) initiative.

[response email from search discovery](https://mail.google.com/mail/u/0/popout?ver=1f2xj95nh2wat&search=inbox&th=%23thread-a%3Ar-4196055941975857562&cvid=3) for reference.

## Issue Description
Ray has asked that we provide a list of all connection config for data import and export to and from BQ that we are using or used in the past 12 months.  This is needed because they want to include BQ in our ATO.

---
## Tasks
- [x] Go into BQ
- [x] do inventory of the data connection configuration set up
- [ ] reach out to data owners as needed to get import details

## Acceptance Criteria
- [ ] documented process.
---

**Comment by dorseypa1** [comment]
Okay, I'll see what I can pull together

**Comment by michelle-dooley** [comment]
This work is continuing into next sprint as we could not find/access data needed.  There is a request with Search Discovery (GA) product support to assist.

**Comment by michelle-dooley** [comment]
@dorseypa1 - Ray just provided this as an example of what he is trying to get at.  Don't need to be quite to this level visually but gives you an idea...

[image](https://files.slack.com/files-pri/T03FECE8V-F04UBK1P35L/1678774886502.gif)

![image](https://user-images.githubusercontent.com/93597659/225980279-604ad15a-8ea5-4b8d-bc89-f6a6854d8040.png)

**Comment by dorseypa1** [comment]
Okay, I think we have a lot of this info.   The Data Loaders is a bit obscure as we've seen since it seems like we can't get details when the data is pushed from external sources but if we reach out to the owners we should be able to fill in the gaps
