### ISSUE TITLE
Add in travel reimbursement into check in wireframes

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#54572]
## Description 

Now that we have a core set up wireframes for the unified experience AND wireframes are close to completion for the text solution adjustments for travel reimbursement, how might we integrate travel reimbursement into the unified experience wireframes? 

## Tasks

- [ ] Check to see if travel questions wireframes need to be adjusted in any way. And, if so, update those wireframes. 
- [ ] Update check in confirmation page to include travel information. 

## AC

- [ ] Unified experience wireframes have been updated to include travel questions and travel information on the check in confirmation pages.
