### ISSUE TITLE
VFS Docs: Infrastructure

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#54579]
**Problem Statement**
VFS facing documentation will be out-of-date once the vets-api migration to EKS is complete. Tech Team 1 will update all relevant VFS facing documentation to reflect EKS infrastructure.

**Issue Description**
The team has completed a documentation audit of VFS facing documents. [Attached](https://docs.google.com/spreadsheets/d/1rTacvOYTXh3jMehzlfd0gGMlhiQOqu_Re-kKrGUVY80/edit#gid=0) is an overall list of documents that require an update due to the EKS migration. These updates will be summarized in tickets, and attached to this epic.

---
**Tasks**
- [x] Update GH repos page in the infra section https://depo-platform-documentation.scrollhelp.site/developer-docs/infrastructure
- [x] Update Environments page in the infra section https://depo-platform-documentation.scrollhelp.site/developer-docs/infrastructure
- [x] Update the review instances page in the infra section https://depo-platform-documentation.scrollhelp.site/developer-docs/infrastructure
- [x] Update the deployment process page in the infra section https://depo-platform-documentation.scrollhelp.site/developer-docs/infrastructure 

**Acceptance Criteria**
- [x] Documentation for this section is deployed to platform website.

**Comment by rmtolmach** [comment]
Mostly done! Addressing launch-blocking issues.

**Comment by rmtolmach** [comment]
They're all deployed!
