### ISSUE TITLE
VFS Facing Documentation Updates

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#54571]
**Problem Statement**
VFS facing documentation will be out-of-date once the vets-api migration to EKS is complete. Tech Team 1 will update all relevant VFS facing documentation to reflect EKS infrastructure.

**Issue Description**
The team has completed a documentation audit of VFS facing documents. [Attached](https://docs.google.com/spreadsheets/d/1rTacvOYTXh3jMehzlfd0gGMlhiQOqu_Re-kKrGUVY80/edit#gid=0) is an overall list of documents that require an update due to the EKS migration. These updates will be summarized in tickets, and attached to this epic.

---
**Tasks**
- [x] Divide tickets out among team members
- [x] Coordinate with the Content team so they are prepared to work with us on changes
- [x] Schedule time to make changes
- [ ] Complete tickets attached to this epic (updates)

MONDAY:
- Lindsey: VFS Docs: EKS Summary
- Rebecca: VFS Docs: Infrastructure
- Rachal: VFS Docs: Deployments
- Lindsey: VFS Docs: Running vets-api locally
- Igor: VFS Docs: External Integrations

TUESDAY:
- Lindsey: VFS Docs: EKS
- Igor: VFS Docs: Platform Dashboards
- Rachal: VFS Docs: Tools and Debugging
- Rebecca: the extra links included on the 2nd tab of the google sheet

WEDNESDAY:
- Work with content team (Vicky is on this invite) to resolve launch-blocking issues

**Acceptance Criteria**
- [ ] All updates associated with this epic are complete
- [ ] All updates are published to https://depo-platform-documentation.scrollhelp.site/developer-docs/va-gov-continuous-integration-process

**Comment by vbellissimo** [comment]
Thanks, @laineymajor !

I briefed my team on this upcoming work and I wanted to share some comments:
Comments from team discussed on 2/27/23:

- Content team prefers to be more hands-on, if able to.
- We can offer to help load the templated messages to most of the pages. This would allow us to better know how many pages will be updated on each day from March 20-23. Which in turn, allows us to be better prepared to distribute the content review work amongst our team.
- We can also help fine-tune the message, if needed.
- We can help with the formatting/styling (call out box, etc.) decisions based on the content of where/how the message is being places on each of the pages.

**Comment by laineymajor** [comment]
@vbellissimo in total, we should be updating about 30 pages; adding 1 new page.

**Comment by LindseySaari** [comment]
Monday:
- Lindsey: Started on EKS summary
- Rebecca: Infra docs - asking for reviews
- Rachal - Deployments - updating docs for EKS related info
- Lindsey - Running vets-api locally (we have the vsp-infra repo but may want to go with docker-compose for now)
- Igor - EKS integrations - priority after load testing

**Comment by laineymajor** [comment]
Thanks for the update!
