### ISSUE TITLE
Collaboration Cycle for [Authenticated Experience - My VA, My VA - Update Claim Status Integration EVSS > Lighthouse]

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#54584]
### VFS team name

Authenticated Experience My VA

### Product name

My VA

### Feature name

Update claim status widget EVSS > Lighthouse

### GitHub label for product

my-va-dashboard

### GitHub label for feature

my-va-claims-EVSS-to-Lighthouse

## Kickoff question
<details><summary>Toggle kickoff questions</summary

### When did/will you start working on this product/feature?

March 2023

### Will your work result in visible changes to the user experience?

No

### Are you doing research with VA.gov users?

No

### Will your work involve changes to...

Tools, applications and dynamic pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

No

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/claim-status-lighthouse-migration/README.md#project-outline-my-va-claim-status-evss--lighthouse-migration

### Notify the Collaboration Cycle team of this ticket in the vfs-platform-support Slack channel.

- [X] I acknowledge that I must notify \#vfs-platform-support after submitting this issue.
</details>

### Privacy, Security, Infrastructure Readiness Review
<details open>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [ ] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [ ] Link to the Readiness Review ticket below

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>
