### ISSUE TITLE
[Development] Remove "Call Us" Bullet from VA Claim Exam Page

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#5459]
## User Story:
As a veteran, I need to get a copy of my claim so that I can have it for my records or as evidence.

During some discussions with Paul Shute we realized that the "call us" option is no longer a real option and should be removed from the page.  See the attached screen shot for where on [this ](https://www.va.gov/disability/va-claim-exam/) page it should be removed.

![image.png](https://images.zenhubusercontent.com/5d54025346ffca000148e7f7/2be26929-86c0-4e99-b506-dc33693711cc)

## Tasks
- [ ] Remove bullet from front-end code.

## Acceptance Criteria:
* New page no longer has the bullet for "call us"

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@luke-gcio Confirming that the number needs to be removed from all instances on the page. It's also listed here: 
<img width="949" alt="Screen Shot 2020-02-04 at 1 26 59 PM" src="https://user-images.githubusercontent.com/48728214/73774518-1e550480-4752-11ea-8046-3532e2964217.png">

**Comment by MickinSahni** [comment]
We're going to take a look at this in grooming to ensure it can be picked up mid-sprint or if it needs to be pushed to our next

**Comment by luke-gcio** [comment]
I would not worry about mid-sprint unless you end up with room.

> @luke-gcio Confirming that the number needs to be removed from all instances on the page. It's also listed here:

Checking on the removal of the number, but pretty sure it is specific to "getting a copy of your report" and not regarding scheduling.  @AZSchneider can you confirm?

**Comment by AZSchneider** [comment]
Seeing as how the instructions about your exam appointment say "Call the number provided right away to confirm the time and location of your exam. It’s important not to miss your scheduled exam, so you’ll want to double check that you have the right place and time." ...I'm thinking that the National Call Center might not be the best place to call if you can't make your appointment. You probably want to call the number provided in your letter or the number of the local doctor's office that reached out. I need to confirm though.

**Comment by MickinSahni** [comment]
Thanks, @AZSchneider. We'll wait for that confirmation, but if no changes are necessary we'll go ahead with publishing.

**Comment by AZSchneider** [comment]
@luke-gcio will be getting confirmation on Friday and will let you know if anything needs to change.

**Comment by MickinSahni** [comment]
2020-02-06 PW Standup
- Awaiting feedback. Should be a straightforward change once we get that go-ahead

**Comment by kelsonic** [comment]
Hey @AnneHurley, saw that you assigned me to this but after reading the ticket + comments I'm not sure what action items I should commit to... Do you need help from me for this ticket? 🙂

**Comment by MickinSahni** [comment]
2020-02-07 PW Standup
- 👋 @AZSchneider - do we have confirmation on whether this change is needed?
   -  specifically around whether we need to remove phone number from both locations

**Comment by luke-gcio** [comment]
I'm talking to Paul Shute today hold your :horse: :horse_racing: :racehorse:

**Comment by luke-gcio** [comment]
Looks like we will keep the number there for now (in the second case of changing the appointment).  I talked to Paul and he explained to me that although it is not ideal and they are working to correct it, right now using the main call center does somewhat work to make the appointment change.  We will revisit at some point but the direction for now was to keep it there.

**Comment by RLHecht** [comment]
Thanks, @luke-gcio . This page was just published with only that one instance of the phone number removed (under the "Can I get a copy of the report?") accordion. Should be live on the site Monday afternoon. Moving this to validate @MickinSahni

**Comment by MickinSahni** [comment]
Sweet. Seems like the next step is for @luke-gcio to validate Monday so we can close this out. Thanks, team.

**Comment by MickinSahni** [comment]
2020-02-10 PW Standup
- Waiting for deploy this afternoon and expected to close before tomorrow

**Comment by RLHecht** [comment]
This has been validated on the live site. Closing ticket.
