### ISSUE TITLE
Tier 2 Support + On Call

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#54599]
**Problem Statement**
Support is struggling to keep up with the current workload. How might we track issues that our team is assisting with, bringing blockers to team standups, to aid in closing tickets in an more efficient manner?

**Issue Description**
- [ZH support board](https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/board)
- #vfs-platform-support

---
**Tasks**
- [ ] Tag platform-tech-team-1 in any tickets being worked by TT1 members
- [ ] Quick summary of progress for current ticket(s)
- [ ] Quick summary of blockers
- [ ] Question: Is there any crossover with current CoP tickets?
- [ ] Question: Are there multiple tickets with the same/similar support issue that need to visited for automation/QI?

**Acceptance Criteria**
- [ ] Ticket is closed upon completion
- [ ] Reporting person/team is notified

**Comment by LindseySaari** [comment]
Igor wrapped up certs. Cyril is taking this to the finish line on Tier 2 (maybe very small support from Igor)

**Comment by LindseySaari** [comment]
Lindsey oncall - 3/22- 3/29
Rebecca - 3/30 & 3/31

**Comment by LindseySaari** [comment]
Lindsey oncall - 3/22- 3/29
Rebecca - 3/30 & 3/31

**Comment by considerable** [comment]
Igor oncall - 3/25- 4/08
