### ISSUE TITLE
[EVSS to Lighthouse] Backend additions

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#54616]
## Background
There are a few things that need to be added to the backend code that were missed on the initial pass
* Use Lighthouse Pundit Policy to gate access to the controller
* Filter out claims with status `CANCELED`, `ERRORED`, and `PENDING`
* Add specs for the service to test the claim status filtering

## Tasks
- [ ] Use Lighthouse Pundit Policy in controller
- [ ] Filter out claims with unwanted statuses
- [ ] Add specs to verify that claims are being filtered out properly

## Acceptance Criteria
- [ ] Users that aren't authorized to hit the Benefits Claims endpoints are unable to
- [ ] Claims that have unwanted statuses are filtered out before they are returned from the service
- [ ] Specs are in place to ensure that this is happening as expected
