### ISSUE TITLE
[BE] Execute CIE Load Test Script

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#54619]
## Description
Execute check-in experience load test script between March 16 - 28 and report to the platform team on the validation results.

## Tasks
- [ ] [BE] **Run CIE load test script**
- [ ] [BE] **Monitor [dashboard](https://vagov.ddog-gov.com/dashboard/bu2-7t9-cja?tpl_var_env%5B0%5D=eks-dev&tpl_var_kube_cluster_name%5B0%5D=dsva-vagov-dev-cluster&tpl_var_kube_deployment%5B0%5D=vets-api-web&tpl_var_kube_namespace%5B0%5D=vets-api&live=true)**
- [ ] [BE] **Report to platform team in eks-migration-support channel**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by kanchanasuriya** [comment]
Consolidated all the details for CIE load test execution in [doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/performance-testing/results/eks-migration/cie-endpoint-load-testing.md)
