### ISSUE TITLE
Supplemental Claims | Intent to File should be on it's own page

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#54628]
## Value Statement
**_As a_** Veteran that is filing a supplemental claim
**_I want to_** see an exclusive url for the Intent to File (ITF)
**_So that_** I won't be confused by the Step and url not matching what's on the page. 

---
## Background Context
After working with the ITF code implementation from 526, it was noted that the ITF alert shown after the Veteran continues their application is on the page that matches the last edited/saved page within their form. So the step X of 4 may not be step 1, and the URL doesn't match the ITF content. What's happening behind the scenes is that the ITF alert overrides the page content about to be rendered &ndash; like a full screen modal &ndash; then allows the original page content to render once the "continue" button is clicked.

<details><summary>ITF error message shown on step 3 of 4</summary>

![Intent to file error - we're sorry. something went wrong on our end - shown on step 3 of 4: new and relevant evident page](https://user-images.githubusercontent.com/136959/223205860-51042ea6-ce24-4bf8-b9b3-99db267b2631.png)</details>

What we think needs to be done is to move the ITF on to it's own page, then the continue button will redirect the Veteran to the last edited/saved page. This may not be as simple as it sounds since we're dealing with the form system.

Alternatively, we could make the ITF message show within a modal overlaying the current page content. This may not be ideal because if the ITF retrieval or submission caused an error, an ITF may not have been checked or submitted, and we're allowing the Veteran to continue.

## Acceptance Criteria
- [ ] Move the ITF content on to it's own page 
- [ ] Determine what happens if there is an error &ndash; retry or return to intro page?
- [ ] 

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
@Mottie is this still relevant?

**Comment by Mottie** [comment]
@eileen-coforma and I were discussing this as something to work on after release. We thought it might be confusing to the Veteran to see the URL not change after they used the continue button
