### ISSUE TITLE
PREP VETS-API FOR MAINTENANCE PHASE

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#54633]
## LOE
Medium

## Problem Statement
Tech Team 1 is wrapping up the migration of vets-api from BRD to EKS; focusing on reaching stability of vets-api in EKS. To complete the migration in a timely fashion, TT1 moved certain items to a separate project (this one). Most of the items _not_ included in the MVP for production migration, include items that require some additional process cleanup and **automation**, ultimately reducing toil, and **making vets-api more easily maintainable** for the support team and CoPs.

**How might we improve vets-api in a way that reduces toil and eases maintenance?**

## User Impact
Platform and VFS teams will be impacted. 
- Automation within vets-api will reduce unnecessary support and maintenance tasks for the support team and CoPs
- Improve experience for VFS teams

**Reducing toil will hopefully reduce the vets-api maintenance load, reducing work for platform support and CoPs**
Toil is the kind of work tied to running a production service that tends to be manual, repetitive, automatable, tactical, devoid of enduring value, and that scales linearly as a service grows. Not every task deemed toil has all these attributes, but the more closely work matches one or more of the following descriptions, the more likely it is to be toil:
- Different categories of toil, found [here](https://sre.google/sre-book/eliminating-toil/)
**Increasing automation of vets-api = a more maintainable vets-api.**
Beneficial for both platform and VFS teams!

**TOIL REDUCTION + INCREASED AUTOMATION = MORE SUSTAINABLE VETS-API AND LESS FOR SUPPORT AND CoPs TO MAINTAIN.**

## Where was this problem reported?
- Redundant support tickets 
- OCTODE (Bill Chapman, specifically toil reduction)

## What do we not know about the problem space?
- Tech Team 1 has an epic with a number of items that need to be completed as part of vets-api maintenance prep 
_Important to note that there is one ticket in the epic that overlaps with TT2's EKS related project. Zero dependency, but creating a local cluster would overlap with our solution of deploying ephemeral clusters and allowing users direct access_
- Will their be any negative impact of toil-reduction on the other teams' current work?
   *once K8 is in master, current review instances will stop working
   *we have a meeting set up with the review instances team to mitigate
- See additional information in discovery outlined below

## What (if any) research or discovery has been done?
- Tech Team 1 has an epic with a number of items that need to be completed post EKS MVP prod rollout
- [Crosswalk](https://docs.google.com/spreadsheets/d/1Cur5O1LUnfWJdaSEf3fk4bVR9HTkQvhKxjv6lRC4e1A/edit?usp=sharing) with TT2's EKS-related project 
- IN PROGRESS [DISCOVERY](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/57993)]: Prep vets-api for maintenance mode
- IN PROGRESS [DISCOVERY](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/58061): Where can we add automation w vets-api?
- What we currently DO know per previous work and discovery has been included in a [roadmap](https://miro.com/app/live-embed/uXjVMOBqbxs=/?moveToViewport=-467,-1067,2844,1587&embedId=735493338951)

## What is the acceptance criteria?
- [x]  Identify 3 instances of toil and define. 
1. Alerts are at the correct threshold and actionable
2. Deployment process (reduction in questions asked about what is deployed and when)
3. Reduce/stop resource tweaking
- [x]  Relevant (3) improvements have been tested
- [x]  Relevant (3) improvements are deployed to production
- [x]  EKS documentation on platform website has been discussed with OCTO and Tech Team 1 present, and acceptance is acknowledged by OCTO (Bill and/or Mike) 
*ArgoCD and EKS training for vets-api
- [x] Assessment of what's missing to resolve logs being forwarded to DD (not necessarily create a solution, and resolve). Collab with TT2. (This is accounted for in a separate project now)

## How should we measure success?
- Reduced # of support tickets related to vets-api (specific to the 3 areas of toil reduction)
- Reduced # of maintenance tasks for vets-api (specific to the 3 areas of toil reduction)

## TODOs
- [ ] Convert this issue to an epic

**Comment by BillChapmanUSDS** [comment]
Acceptance criteria is murky since there is another EPIC that lists a bunch of post prod rollout tasks.  So I'd say let's make sure that Epic is linked here.

**Comment by rjohnson2011** [comment]
As a first step, locating which tickets in the CoP BE backlog are related to EKS rollout. Out of the 26 BE backlog tickets, none are directly related to EKS rollout. However, one ticket is [related to Jenkins](https://app.zenhub.com/workspaces/platform-cop-backlog-6359535e384ff5a473132130/issues/gh/department-of-veterans-affairs/va.gov-team/40523), which we likely want to completely deprecate in time. However, this ticket is part of a larger ticket involving load testing and generating authenticated session keys and requires additional discovery.

**Comment by laineymajor** [comment]
I've linked the work we've designated as 'post-prod' to this project, but it needs a lot of refinement..

**Comment by LindseySaari** [comment]
Automation: Is there any room for automation when it comes to Sidekiq and ArgoCD Terminal requests?

**Comment by laineymajor** [comment]
Question: 
RE Toil Assessment is complete and comprehensive list linked here (Identify platform process and components that currently create toil and ensure issues are created to improve)
- How are we assessing toil
1. tracking auth into prod and staging systems
2. reliability survey (don't really want to do this)
3. looking at GH issues and tracking them for toil (ex: these xx number of issues are all related and duplicate)

Identify x number of toil instances that can improved in this process.

**Comment by annekerr49** [comment]
Bill could you  please add this ticket to the DE Products - In progress column https://github.com/orgs/department-of-veterans-affairs/projects/940/views/2
