### ISSUE TITLE
Modify Midpoint Review meeting agenda

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#54635]
## User Story
As a Governance team member, I want to make sure I level set expectations at the beginning of the Midpoint Review so that VFS teams understand the purpose of the MPR meeting and understand how the meeting is structured.

As a VFS team member, I want to know what the agenda, cadence, and expectations are for the MPR so that my team is prepared and ready to answer questions.

Assignee: @CherylEvans 
Peer Reviewer: @briandeconinck 

## Description
In the[ Midpoint Review Mural workshop](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1673977851275/ed5f4d14afab24df552905158b06374adead0cc3?sender=u0574179b1d97118ccc0e3591) Governance team members shared that sometimes its difficult for us to understand what changes had been made to the product since the last time we saw it. A proposed solution involved  getting an update from the VFS team at the beginning of the MPR so they can share what changes have been made to the product since the Design Intent. In addition, OCTO Design Lead Matt Dingee had thought that asking the VFS team what they would like to receive feedback on, or asking them what areas they'd like us to focus on, would also be of value.

The purpose of this ticket is to change the cadence of the meeting to include the following 2 changes:
1) ask the VFS team to communicate what has changed since the Design Intent, 2) ask the VFS team is there's any areas of their product where they'd specifically like Governance team feedback. This will involve changes to the script as well since the script sets the tone and defines the agenda for the meeting. We will evaluate the current script, define the requirements of the new script, and write a new script. We should aim to remove the "fluff" and redundancies that exist in the current script.

Current script:
> Welcome to the Midpoint Review for _______ team for ______ initiative.
> 
> The purpose of the Midpoint Review is for the Platform Collaboration Cycle team to review your product to ensure it meets design, IA, content, and accessibility VA.gov platform standards. If you are preparing for usability testing or research with Veterans or VA.gov users, the Midpoint Review feedback will inform you if there are any glaring standards issues that could negatively impact the results of your usability testing or user research. These are things we’ll suggest you fix before beginning your research with Veterans. The Midpoint Review feedback is intended to guide VFS teams toward building accessible, compliant, and consistent products for VA.gov. We highly recommend that you address Midpoint Review feedback before the Collaboration Cycle Staging Review. Lastly, please note that "must" feedback, if not addressed, could result in launch-blocking issues at Staging Review. By not addressing the "must" feedback, your team accepts the risk of being blocked from launch to the VA.gov platform. Please handle accordingly.

## Impacted Artifacts
[Midpoint Review - Moderator Responsibilities / During Synchronous Meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Moderator+Responsibilities#During-Synchronous-Meeting)
[Midpoint Review touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review) on Platform Website - specifically the Moderator Script. Potentially the Objective and Outcome.

## Tasks
- [x] Determine how the MPR should look and feel
   - Comment: It is possible for teams to skip DI and go straight to MPR. Our proposed agenda should be cognizant of this. Ideally we want an update on their product whether this is the first time we're seeing this (so teams that skipped DI) or the 2nd time and they've made updates since we've seen it (teams that didn't skip DI). 
- [x] Document a proposed agenda via the During Synchronous Meeting operational process
- [x] Share with Governance team for review and feedback
- [x] Once agenda is agreed upon, rewrite the script to support agenda changes
- [x] Identify if the Objective and/or Outcome on the touchpoint page is impacted by the new agenda. If so, make draft changes.
- [x] Submit for Peer review 
- [x] Follow Platform Communication Playbook for publishing and sharing with VFS teams, including:
   -  [x] Slack announcement via #vfs-change-announcements channel
   - [x] ToT announcement (connect with Shira)
   - [x] Change history post

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have defined a new agenda for the Midpoint Review meeting
- [x] We will get an update from the VFS team on the current state of their product at Midpoint Review
- [x] We have catered the MPR to allow the VFS team to ask for specific feedback on specific features of their product.

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
@briandeconinck Created a [working draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2567766017/54635+-+Copy+of+Midpoint+Review+-+Moderator+Responsibilities) for the Proposed Agenda for Midpoint Review Synchronous Meeting.
I will tag you when I move further along in the process. :-)

**Comment by briandeconinck** [comment]
I spotted one issue in the script, commented on it on both the Platform website page and the moderator responsibilities page. Otherwise this all looks great to me!

**Comment by CherylEvans** [comment]
@shiragoodman @briandeconinck Here is my [draft for the Change history page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2579005476/54635+-+Copy+of+Change+history).  Once approved, I will make the announcement (based on my change history post) and work with Shira on the ToTs announcement.

**Comment by shiragoodman** [comment]
@CherylEvans I made some comments. Take a look at lmk if you have any other questions.

**Comment by briandeconinck** [comment]
@CherylEvans I like the change history post. Straightforward and clear.

**Comment by CherylEvans** [comment]
@shiragoodman @briandeconinck I implemented your additional recommendations, Shira.  Everything should be good to publish.  What do I need to do for the ToT task?

**Comment by CherylEvans** [comment]
@shiragoodman @briandeconinck Here is my proposed Slack message:

:change-announcement: **Changes have been introduced to the Midpoint Review synchronous meeting.**
**Attention:** VFS teams
On 03/28/23, the Governance team added changes to the Midpoint Review Meeting
**Impact:** The Governance team will now ask VFS teams to share what changes they have made to their product since Design Intent. In addition, the Governance team will ask VFS teams if there are specific areas of their product where they have questions or would like clear guidance.
**Documentation:** see the [Midpoint Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)
**Support:** Reach out to the Governance team by filing a support request on #vfs-platform-support

**Comment by shiragoodman** [comment]
I have ToT covered for today. Slack message looks good. This is a minor change, so you only need to share on the #vfs-change-announcements channel. Thanks @CherylEvans !

**Comment by CherylEvans** [comment]
@briandeconinck Everything should be published by EOD today.  Once it is, I will close the ticket! Thank you!!

**Comment by CherylEvans** [comment]
@briandeconinck Everything is published and announcements made.  Closing ticket if you have no objections.
