### ISSUE TITLE
[Design] My VA audit improvements: [QA finding] Update documentation to include error scenario when messaging API errors out

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#54643]
## Background
Through QA, we determined our documentation is missing notes on the scenario when the messaging API fails. We need to update our documentation to include this behavior when the messaging API fails:

1. **If the user has unread messages and the messaging API fails,** the user does not see an error message. Instead they see the "Send a secure message" secondary link (when they ordinarily wouldn't because they would be seeing the "unread messages alert") in addition to the other secondary links that already display ( 1) Refill and track your prescriptions, 2) Request travel reimbursement, and 3) Get your VA medical records and lab and test results)
2. **If the user does not have unread messages and the messaging API fails**, there is no visible difference to the user. They still see the "Send a secure message" secondary link as usual with the other three secondary links ( 1) Refill and track your prescriptions, 2) Request travel reimbursement, and 3) Get your VA medical records and lab and test results)

## Tasks
- [x] Update the Error States section of the Health Care [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/health-care-FE-documentation.md#error-states) to account for this error scenario
- [x] Update the Health Care Use Case documentation to account for this scenario

## Acceptance Criteria
- [x] Our documentation is updated to include the scenario when the messaging API errors out

## Resources
Linking some old resources here from My VA 2.0 discussing logic behind the error state for `/messages`
- [Old documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/health-care-section.md#messages) 
- [Old slack](https://dsva.slack.com/archives/C909ZG2BB/p1615910469010600?thread_ts=1615909362.009500&cid=C909ZG2BB) within a helpful thread 
- Corresponding [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21375#issuecomment-800393008), summarizing decision and logic

**Comment by aagosto90** [comment]
Updated [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/health-care-FE-documentation.md) and [use case documentation draft](https://docs.google.com/document/d/1JG8AJs-b8ceD_YCNBEX6Ie3-ZOX_JytEM963_vuZ39A/edit#)
