### ISSUE TITLE
Discovery - Whether EVSS is used in  DisabilityCompensationFormsController (BRD)

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#54646]
## Issue Description
The eVSS is being deprecated and the vets-api utilizes these services to retrieve and post data.
One of these services is the BRD service that indicates gets Benefits Reference Data.
This eVSS endpoint is being sunsetted with the eVSS in August.

We need to migrate any calls to the eVSS BRD endpoint to the Lighthouse version.
The scope of this ticket to abstract these calls where applicable:
- DisabilityCompensationFormsController#separation_locations
- Is separation_locations being used by 526?
- Note this method leveraged Redis (in EVSS::ReferenceData::ResponseStrategy). Do we need to rebuild that? Even if Lighthouse can plug right into existing Redis functionality, the current implementation references Redis in the module/class names which is confusing - so we might want to at least rebuild duplicate classes to avoid a misnomer there.

Important: code exists in vets-api and vets-website to hit EVSS from here:
- vets-api's [routes file](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/routes.rb#L73) exposes this method to the world.
- vets-website's 526EZ implementation includes [code](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/disability-benefits/all-claims/utils/index.jsx#L251) that aims at that route.

---
## Steps
Confirm separation_locations method is still being used by 526 and needs to be migrated
If answer to 1 is yes, create a "Create Abstraction" ticket
If answer to 1 is "no", raising the question with other teams, if others are relying on this. And do they need us to migrate it.

---
## Tasks
- [ ] confirm separation_locations method is still being used by 526 and needs to be migrated

## Acceptance Criteria
- [ ] We know whether 526 Relies on it
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
Closing this issue as all required eVSS endpoint calls ( service-branches endpoint has already been migrated). More details in [slack thread](https://dsva.slack.com/archives/C04KW0B46N5/p1678393440485009) here.

**Comment by colevoss** [comment]
Locations EVSS Reference Data is being used:

* [Addresses Controller](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/addresses_controller.rb#L52)
* [Disability Comp Controller](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/disability_compensation_forms_controller.rb#L22)
* Disability Comp Validation
  * [L62](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/claims_api/app/controllers/concerns/claims_api/disability_compensation_validations.rb#L62)
* [L162](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/claims_api/app/controllers/concerns/claims_api/disability_compensation_validations.rb#L162)

**Comment by colevoss** [comment]
* [Existing Lighthouse BRD Service](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/lighthouse/benefits_reference_data/service.rb)
* [Benefits Reference Controller](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/benefits_reference_data_controller.rb)

**Comment by RakshindaAslam** [comment]
The scope of this ticket to abstract these calls where applicable:
- Addresses Controller
- Disability Comp Controller
- Disability Comp Validation
   - L62
   - L162

Out of scope:
- service-branches endpoint and 526ez call has been migrated from eVSS to Lighthouse

**Comment by colevoss** [comment]
## Discovery:

After some discovery, the `spearation_locations` API endpoint caches the EVSS Reference data using the [EVSS::ReferenceData::ResponseStrategy](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/evss/reference_data/response_strategy.rb) class which inherits from `Common::RedisStore`. 

We should figure out if we also need to build a similar caching layer for lighthouse as well. And if we do, can we use it for all BRD calls to lighthouse or do we need one for each type of call. I think we can just build one caching response layer for LH BRD calls. 

## Plan:

My plan is to build a similar interface that will abstract the EVSS Calls and caching and call that provider from the controller. That will be the extend of this ticket.

After that, we can implement the same provider interface for lighthouse. I suppose we could wait to build the cache, _but we might want to ask some questions about the implications of not caching the results. Is it for performance/speed, or is it to reduce the load on EVSS/LH._

**Comment by colevoss** [comment]
## Questions for LH:

### Source of Truth
Is the source of the intake site (and other BRD endpoint data) different from that of EVSS? For example, is the `id` of the intake sites response a different id than the `code` property of the EVSS intake site response (different values, and/or different types of data)?

### Usage of BRD/Intake Site Data

Do we know where the BRD data is being used? If the `id` properties aren't the same as the `code` properties from EVSS will the places that the data is being used be affected by that? Is that also using EVSS and need to be migrated to Lighthouse?

### Caching

Currently, we are caching the requests for intake site data in vets-api. Do we need to be doing that for Lighthouse Intake site data as well?

**Comment by colevoss** [comment]
Unfortunately this ticket will have to be carried over into the next sprint. My time away for the rest of the week (3/29-4/3) will hinder my ability to finish it up early in the sprint, but i will attempt to clean up this ticket when I return.

**Comment by colevoss** [comment]
According to the LH BRD Team Intake sites data is coming from BGS (Benefits Gateway Services). 

They mentioned that all of their data is coming from there.

**Comment by navaeddie** [comment]
The next step in this work is now handled by https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/60247
