### ISSUE TITLE
Accessibility Testing for [Auth Experience My VA - My VA Audit UX Improvements]

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#54648]
### Product information

- [X] Team name, product name, and feature name have been added to the title of this issue.
- [X] Team label, product label and feature label (if applicable) have been added to this issue.

### Who completed the use of color and color contrast test?

aagosto90

### Use of color and color contrast checks

- [X] All text of 20px or smaller has a 4.5:1 contrast ratio to its background (or better)
- [X] All text of 20px or larger has a 3:1 contrast ratio to its background (or better)
- [X] Non-text elements have a 3:1  contrast ratio to their background and to neighboring elements (or better)
- [X] Color is not the only way to distinguish links from other text (eg. links are underlined)
- [X] Any charts, maps, infographics, and tables convey all information without only relying on color
- [X] Content does not refer to color, especially when providing user instructions (eg. "Click the blue button")

### How did color testing go?

Pass - audit updates do not present any new components and existing components do not introduce any colorblindness issues

### Who completed the axe scans?

allisonlu

### axe checks

- [X] Each page has been scanned using axe (results shared below)
- [X] axe is integrated into your end-to-end testing

### axe DevTools scan results

Pass - no issues present after running axe test in browser devtools

### How did axe testing go?

There are axe scans already in place. However, we should probably make a ticket to edit [the last test scenario in this file](https://github.com/department-of-veterans-affairs/vets-website/blob/dff03a62f38dab2c526153cef545fa8f4681d76b/src/applications/personalization/dashboard/tests/e2e/loa1.cypress.spec.js#L113) – I don't believe headings are required to receive focus, but we should confirm with an a11y specialist

### Who completed the content zoom and reflow test?

aagosto90

### Content zoom and reflow checks

- [X] All page elements are readable and usable at 200% zoom
- [X] All page elements are readable and usable at 300% zoom
- [X] All page elements are readable and usable at 400% zoom

### How did content zoom and reflow testing go?

Pass - Zooming in to 250+% on my monitor causes the page to rearrange responsively so nothing on the rightside of the screen is missed

### Who completed the keyboard navigation test?

aagosto90

### Keyboard navigation checks

- [X] Each link, button, form input, checkbox, radio button, select menu, and custom element can receive keyboard focus
- [X] Each link, button, form input, checkbox, radio button, select menu, and custom element responds to expected keys
- [X] All elements under focus have a visible focus indicator
- [X] The order of [Tab] stops made sense and was appropriate for completing tasks

### How did keyboard testing go?

Pass - all links are accessible by keyboard and go in the desired order

**Comment by ajakabcin** [comment]
hey @briandeconinck am I able to close this? This was part of a staging review from several months ago
