### ISSUE TITLE
[Design] My VA audit Improvements: [QA finding] Update documentation/designs to account for appointments error + unread messages

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#54642]
## Background
Through QA, we determined that we missed an edge case scenario on errors in the Health Care section. When a user has unread messages, _and_ the appointments API errors out, the user sees three main elements in the Health Care section:

1. the unread messages alert
2. the error message on the appointments API 
3. three right-aligned secondary links immediately below the error message for: 1) Refill and track your prescriptions, 2) Request travel reimbursement, and 3) Get your VA medical records and lab and test results (note that they would not see the link for Send a secure message because they have unread messages).
 
We're making sure the code is functioning this way in #54437 but we need to update our documentation to account for this scenario.

## Tasks
- [x] Update the Error States section of the Health Care [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/health-care-FE-documentation.md#error-states) to account for this error scenario
- [x] Update the Health Care Use Case documentation to account for this scenario
- [x] Update designs/sketch files and post the new designs in this ticket

## Acceptance Criteria
- [x] Our documentation is updated to reflect the error scenario when a user has unread messages and the appointments API errors out

**Comment by aagosto90** [comment]
[Updated error state in FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/health-care-FE-documentation.md#error-state-2-the-health-care-appointments-api-call-fails-cant-tell-if-user-has-appointments-scheduled-but-can-tell-they-have-va-health-care)
[Updated use case documentation draft](https://docs.google.com/document/d/1JG8AJs-b8ceD_YCNBEX6Ie3-ZOX_JytEM963_vuZ39A/edit#)
Added [desktop](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/C19F6AA0-62CE-4F92-89BD-65680DE67F60) and [mobile](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/0C2845E1-A9E9-412C-B653-11B292A822A0) Sketch mockups

**Comment by ajakabcin** [comment]
perfection - thanks @aagosto90
