### ISSUE TITLE
ca-trust cert verification & updates

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#54655]
## Description

While doing a cert investigation, I compared staging certs in `EKS` to `BRD`. There are a few certs that exist in BRD that don't in EKS

[EKS certs](https://github.com/department-of-veterans-affairs/vets-api/blob/k8s/Dockerfile#L29) are mounted at /`usr/local/share/ca-certificates/`
[BRD certs](https://github.com/department-of-veterans-affairs/devops/pull/6152/files#diff-bda8488948e1b45848d100c5c302f1ea3c6ebecd26e57fb5dccc168ecddb52bdR157) are mounted at `/etc/pki/ca-trust/source/anchors/`. The remained of the VA certs are pulled in from http://aia.pki.va.gov/PKI/AIA/VA/ via the [cert installation script](https://github.com/department-of-veterans-affairs/vets-api/blob/k8s/import-va-certs.sh#L14).

In the `/usr/local/share/ca-certificates/` directory, EKS is missing `DigiCertGlobalCAG2.crt.pem`, `DigiCertTLSRSASHA2562020CA1.crt.pem`, `va.pem` and `vba-forms-intermediary.crt`

Cert files in the devops repo can be found here:
1. [DigiCertGlobalCAG2.crt.pem](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/roles/trusted-certs/files/DigiCertGlobalCAG2.crt.pem)
2. [DigiCertTLSRSASHA2562020CA1.crt.pem](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/roles/trusted-certs/files/DigiCertTLSRSASHA2562020CA1.crt.pem)
3. [va.pem](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/roles/trusted-certs/files/va.pem)
4. [vba-forms-intermediary.crt](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/vba-forms-intermediary.crt)

We should be sure that ALL EKS envs have these certs. Most of the EKS certs are mounted/baked into the vets-api image, but we should check the ansible code for additional certs that are mounted via the BRD process. 

It appears that the missing certs exist in ALL environments in BRD.

Charley Strahn is checking with the Forms API team. [See thread for latest updates](https://dsva.slack.com/archives/C04CYC4LMU6/p1678197973103389?thread_ts=1678143633.862439&cid=C04CYC4LMU6)

### Tasks
- [x] Add certs to param store OR add to manifest files if too large 
- [x] Add certs to secrets.yml template and mount via vets-api manifest
- [x] Deploy & verify certs exist and are correctly mounted
- [x] Scan ansible code to make sure we aren't missing other certs

**Comment by LindseySaari** [comment]
[Uploading... Screenshot 2023-03-07 at 8.43.03 AM] - Current BRD Certs

**Comment by laineymajor** [comment]
@considerable to add all cert files while adding the one from the cert renewal yesterday. TOP PRIORITY TODAY @considerable

**Comment by laineymajor** [comment]
@considerable did you do this when updating the recent cert? provide update asap. Thanks!

**Comment by LindseySaari** [comment]
Had to revert these changes yesterday as 1 or 2 of the certs borked Id.me login after cert rotation

**Comment by LindseySaari** [comment]
We have redeployed these certs and @RachalCassity and myself have confirmed that login is still functioning 🚀
