### ISSUE TITLE
Adjust Domo/BigQuery data set to include CMS repo

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#54671]
## User Story
As a Governance team member, I want to update the query that pulls data from Github into Domo to include the CMS repo so that all issues logged at Staging Review are included in the Collaboration Cycle Dashboard. 

Assignee: @it-harrison 
Peer Reviewer: @briandeconinck 

## Description
In the [Lovell VAMC Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52672), @briandeconinck identified several accessibility issues that had already been identified by the Sitewide Accessibility lead. Rather than duplicate issues, Brian instead applied the `CCIssue` labels to the already logged tickets, and then linked them as child tickets to the Collab Cycle Request ticket.

Since these tickets exist in the va.gov-cms repo, they're not currently being pulled into the Collaboration Cycle Dashboard data set. The purpose of this ticket is to 1) ensure that the issue tickets from Lovell have all of the correct gh labels (currently they only have the `CCIssue` label) and 2) update the query to ensure that the data set in Domo includes the tickets in the va.gov-cms repo (or create a 2nd data set that is pulled into the CC Dashboard the same way the current data set it - whatever solution is best per Analytics & Insights team).

Note: this ticket will NOT include updating any cards within the Collaboration Cycle dashboard. That will come later on via another ticket.

## Tasks
- [x] Verify all of the accessibility tickets opened during the Lovell Staging Review have the correct labels per the Anatomy of a Staging Review Issue ticket guidance.
   - If not, add the necessary labels.
- [x] Work with A&I team to pull in new data set. Discuss whether it makes sense to merge with existing data set, pull in as new data set and merge in Big Query etc. Bottom line: this data will need to be displayed alongside the existing Collaboration Cycle data set as if it is all from the same source. How best can we do that?
- [ ] Document action took from discussions with A&I. If new data set, be sure to link name of data set below.
- [ ] Open a new ticket, linking to this one, for updating the CC Dashboard cards to include the cms data.
 
## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] The Collaboration Cycle Staging Review issue tickets opened in the va.gov-cms repo are available as a data set within Domo
- [ ] The Collaboration Cycle Dashboard cards include the CMS repo issue tickets

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@it-harrison this has moved into the next sprint. Can you please comment on the current status of the ticket submitted to Analytics?

**Comment by it-harrison** [comment]
Analytics is evaluating for inclusion in the upcoming sprint.

**Comment by it-harrison** [comment]
Analytics has not yet completed its work that is blocking this ticket so it will roll into the next sprint.

**Comment by it-harrison** [comment]
from Michelle Dooley:

> this is going to require updates to the GH source code that I do not own or manage. I am working on another request that also requires updates to this code. Unfortunately there is no longer a "real" owner of this data but I was able to find out that Ryan on Tech Team 1 is familiar with and can make updates to the code but it requires a ticket be submitted and prioritized by that team first in order for us to be able to access that data. Can you please submit this data request ticket to that team to kick this off.

In the process of submitting ticket to Tech Team 1.

**Comment by it-harrison** [comment]
I have [submitted a ticket](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/59994) to Tech Team 1 to implement these changes. I do not know when it will be picked up for work.

**Comment by shiragoodman** [comment]
escalated this issue to Tech Team 1 at the Platform Huddle meeting on 6/20

**Comment by shiragoodman** [comment]
Putting this on-hold as work is dependent on Backend CoP/Tech Team 1 support.

**Comment by laineymajor** [comment]
@rjohnson2011 please provide update on progress made yesterday and today. Trying to gauge if this will be complete by end of the sprint. Thanks!

**Comment by rjohnson2011** [comment]
Merged a PR to add `vets-cms` repo data into BigQuery, using the same labels/parameters as those in the `vets-api` repo. https://github.com/department-of-veterans-affairs/qa-standards-dashboard-data/pull/209

Also created a new table in BigQuery `github_issues_cms` to store the data relating to the issues in this repo. 

Currently reviewing information to see that it's working correctly. Once daily (at midnight) the table should populate as part of a Github Action workflow.

**Comment by laineymajor** [comment]
Table was populated with the data from the CMS repo! 
- verifying the info and that it's updating at the end of each day
- if things stay on track and look good, will close out

**Comment by rjohnson2011** [comment]
The `github_issues_cms` BigQuery table has been created and populated with all the same labels from the `github_issues` table, with the cms rather than api repo.

![image.png](https://images.zenhubusercontent.com/5fb40598d06a06671e842a63/bff61f0c-1553-4c3e-84cc-272e76c2ec32)

This is now able to be imported into Domo via a Domo BigQuery connector.

**Comment by rjohnson2011** [comment]
@it-harrison @briandeconinck Are you able to pull in this information into Domo? I'm under the impression the blocker on your part was my needing to populate a BigQuery table with relevant Github issue data.

**Comment by it-harrison** [comment]
@rjohnson2011 thanks much for your work on this, yes, our blocker was populating the Biq Query table. I'm going to talk to Analytics about importing it.

**Comment by it-harrison** [comment]
Talked to Michelle today. Analytics is going to work on merging the Big Query Dataset Ryan created into the existing Big Query data set that is pulled into Domo.

**Comment by briandeconinck** [comment]
@shiragoodman @it-harrison Quick follow-up from today's stand-up. Asked Laura, she confirmed that everything from the Lovell epic that's open in GitHub is still open

**Comment by shiragoodman** [comment]
Thanks @briandeconinck. I will put this on my agenda to discuss with Matt tomorrow. We can make a decision whether to continue with updating our query to include the CMS repo or replicate the issues in the va.gov-team repo. I'll let you know what we decide!

**Comment by shiragoodman** [comment]
@it-harrison @briandeconinck we will be closing this ticket out and instead, replicating all of the CMS tickets in our va.gov-team repo. I will create a ticket for tech debt.

@rjohnson2011 we no longer need BE support for this issue.

**Comment by shiragoodman** [comment]
@michelle-dooley see comment above. We no longer need Analytics support for this ticket.
