### ISSUE TITLE
[Bug] File Type and File Contents Mismatch for 526

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#5467]
## User Story:
As a veteran, I need to be able submit medical documentation as part of my claim so that I can get the VA claims assistants the information they need for my claim.

There have been a significant number of errors around the file extension not matching the file type.  There may have been some changes on the VBMS side that did not get incorporated into our process.

This thread has good info: https://dsva.slack.com/archives/C5AGLBNRK/p1580743622110400

## Tasks
- [ ] Obtain updated list from EVSS for the acceptable file types
- [ ] Make sure FE design/implementation supports the correct permutations of file types

## Acceptance Criteria:
* No more file type/extension errors

## Configuration
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ndsprinkle** [comment]
In the 526 form's Supporting Evidence section, the user is instructed to upload only PDFs, JPEGs, or PNGs of file size less than or equal to 25MB. While the file size limit seems to be enforced through my testing, the file extension restriction is not completely enforced. Behind the scenes, the front end actually allows the user to upload JPGs, GIFs, BMPs, and TXTs in addition to the already mentioned extensions. I believe [this](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/all-claims/utils.jsx#L632) is what allows those file types to be uploaded. Simply modifying that array would properly restrict the file extensions, however I'll need to see what other locations will be affected by changing it.

This does not necessarily pinpoint the issue and I'll need to look into the specific error messages more to try to properly recreate the scenarios, but this is definitely a point of inconsistency. @SMLuthi  how do I go about obtaining the list of supported file extensions from EVSS?

**Comment by ndsprinkle** [comment]
Example error from the Slack conversation:

![image](https://user-images.githubusercontent.com/53942725/74187028-c159c280-4c19-11ea-9178-2323685f150e.png)

**Comment by ndsprinkle** [comment]
The wording of the error is interesting because it's almost as if it is implying that the file extension is fine but there is something wrong with the actual content of the file. A way to replicate this would be to take some unsupported file like a DOC and change the file extension to something supported like PNG. I'm not 100% sure if that's what the error means, but I will test this scenario.

**Comment by ndsprinkle** [comment]
@SMLuthi I just noticed you said in Slack that you already reached out to EVSS about this. Did the list get sent your way yet?

**Comment by luke-gcio** [comment]
Email sent to you @ndsprinkle

**Comment by luke-gcio** [comment]
> @SMLuthi I just noticed you said in Slack that you already reached out to EVSS about this. Did the list get sent your way yet?

Did that help @ndsprinkle?

**Comment by ndsprinkle** [comment]
@luke-gcio Not too much. Unless I'm overlooking something in the email, there's nothing regarding the specific file extensions accepted, which is what I think the core issue is related to.

**Comment by luke-gcio** [comment]
Can you reach out to Michael Walker and get more info?

**Comment by SMLuthi** [comment]
Michael has been provided a set of edipis for which he can scour his logs with. He has looked into file validation on their side and there is, according to him, an issue with what is happening when they compare MIME types via file contents. He has requested, if its possible, to send him some of these failing files so he can test them directly.

**Comment by luke-gcio** [comment]
Our end was completed.
