### ISSUE TITLE
Refine Staging Review process for Design System Team

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#54675]
## User Story
As a Governance team member, I want to ensure that the Staging Review process for the Design System team is clearly documented so that the process is understood by all.

Assignee: @allison0034 
Peer Reviewer: @sterkenburgsara 

## Description
Governance team has completed Staging Review's for the Design System Team (DST) and any changes they make to web components for the VA Design System. The Staging Review process for DST does not and should not follow the same process that VFS teams follow. The purpose of this ticket is to improve the guidance Governance team has for DST Staging Reviews, and also to include a reference for DST so they know how we'd like them to schedule and what artifacts we'd like them to share.

Note: Since DST is a Platform team, all guidance for them can be included within Confluence. They do not need to have a custom issue template in VA.gov-team repo. The goal should be to keep this as informal and casual as possible, while still ensuring Governance team has guidance to complete the review and DST has guidance to schedule and provide artifacts for the review.

## Impacted Artifacts
**Final documentation:**
[Design System Staging Reviews](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572025931/Design+System+Staging+Reviews) (this folder contains the 3 proposed documents)

**Proposed documentation:** (will replace the current documentation)
[How to request a design system staging review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572124196/How+to+Request+a+Design+System+Staging+Review)
[Staging Review - Design System - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572124161/Staging+Review+-+Design+System+-+Moderator+Responsibilities)
[How to document findings for a design system staging review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572189697/How+to+Document+Findings+for+a+Design+System+Staging+Review)

**Current documentation:**
[Design System Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1936490517/Design+System+Staging+Review)

## Tasks
- [x] Document proposed process for DST to follow when requesting a Staging Review
- [x] Confirm with Governance team practice areas what artifacts they require for a DS staging review (see [Slack thread](https://dsva.slack.com/archives/GNF5GSD9N/p1678990880543939))
- [x] Confirm with Governance team practice areas other practice area specific content is correct in the documents
- [x] Document process for Governance team to follow for our operational process, including:
   - scheduling the SR with DST
   - testing the DST component and documenting our findings
   - hosting the SR meeting with DST

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] DST knows how to request a Staging Review with Governance team and how to complete scheduling
- [x] Governance team knows the operational process for completing a Staging Review for a design system web component

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
@sterkenburgsara  I have created 3 draft artifacts which I rec replace the 1 current artifact. I tried to align it with our [current documentation](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1978859531/Staging+Review) as well as the [Platform website touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review). Perfect that you as an IA expert are my reviewer! 

- When the design system team decides they are ready for a staging review they will follow the [How to request a design system staging review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2568847409/How+to+request+a+design+system+staging+review)
- After they tag us on Slack (as VFS teams do), the Governance support team member will follow the [Staging Review - Design System - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2569142273/54675+-+Allison+-+Staging+Review+-+Design+System+-+Moderator+Responsibilities)
-  Finally, when the reviewers will follow the [How to document findings for a design system staging review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2568389062/How+to+document+findings+for+a+design+system+staging+review)

@shiragoodman I would love to get your feedback on this. Specifically around the instructions (are all the things applicable to ds staging review)? Also, I am thinking a GH template might actually be beneficial. Here are some placeholders it would contain:

- Scheduling directions
- Artifacts section
- Meeting date and time
- Slack thread request
- Zoom link and passcode

What are your thoughts on a template?

**Comment by shiragoodman** [comment]
FYSA @allison0034 and I chatted at 1:15 ET on 3/17. We agreed to remove some detail from the [How to request a design system staging review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2568847409/How+to+request+a+design+system+staging+review) guidance to make it more specific for DST (and less formal) and made some script modifications.

Re: labels on feedback/findings tickets, Carol asked that we have practice area labels. So for the Design feedback ticket, we should add the `design` label, for accessibility we add the `508/Accessibility` label, etc. I also think we need to create a `DS-Staging` label to add to these tickets so it's easy for us to filter out feedback aimed at Design System vs. VFS teams.

Let me know if you have any questions!

**Comment by allison0034** [comment]
@shiragoodman got it! Can you create the label DS-Staging-Review (that will be consistent with Staging-Review)

**Comment by shiragoodman** [comment]
New label created. I added to this ticket. @allison0034 can we also make sure we (or Carol, whoever) adds this label to the Staging Review request ticket?

**Comment by sterkenburgsara** [comment]
@shiragoodman what about also adding cc-dashboard label?

**Comment by shiragoodman** [comment]
yes, definitely. We want to add it to the request ticket, not our findings tickets. Whereas the DS-Staging-Review label should be added to both.

**Comment by sterkenburgsara** [comment]
@shiragoodman wait, it's the opposite of that, right? We do want the `cc-dashboard` label on findings tickets (not on cc-request ticket).

**Comment by allison0034** [comment]
@sterkenburgsara see if this helps:
 - DS-Staging-Review and cc-dashboard on the ds staging review request ticket
 - DS-Staging-Review on the practice area findings ticket

**Comment by shiragoodman** [comment]
@sterkenburgsara doh! yes, you're right. `CC-Dashboard` goes on the findings tickets - but it's not necessary for DST findings. Since they don't follow the VA.gov Exp Stds, there's no need to track them. That's why we're putting the `DS-Staging-Review` label on them so if we do ever decide to track, we'll be able to easily locate and update if needed.

What I was getting confused with is that we do want to add the `CC-Request` label to the request ticket from DST. This is so it shows up on our Collab Cycle Reviews Dashboard. We'll also want to make sure there's guidance to add these tickets directly to the Staging Review Scheduled pipeline. 

@allison0034 let me know if this is not clear.

**Comment by shiragoodman** [comment]
yes, BUT

Practice area findings ticket should also have the applicable practice area. So `design`, `content`, `ia`, and `508/Accessibility`.

**Comment by shiragoodman** [comment]
and also the `collab-cycle-feedback `label

**Comment by allison0034** [comment]
@sterkenburgsara would you mind giving this one last look? I put everything in a folder, the UX in me is cringing every time I try to navigate the Staging Review structure, the IA of our site needs a good overhaul.
[Design System Staging Reviews](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572025931/Design+System+Staging+Reviews)

**Comment by sterkenburgsara** [comment]
@allison0034 I agree with the way you structured this, and think it's the best until we can give that whole staging reviews folder a thorough review. Everything looks clear and completed to me - I did leave a few comments on the Confluence pages themselves if you can peek at those and respond. Once we resolve those, this is ready to close!

**Comment by shiragoodman** [comment]
@allison0034 checking in. Are we good to close this? Did my comment above get implemented?

**Comment by allison0034** [comment]
@shiragoodman yes! I will close
