### ISSUE TITLE
Share Collab Cycle Dashboard with OCTO for review and feedback

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#54676]
## User Story
As a Governance team member, I want to share the current state of the Collaboration Cycle Dashboard with OCTO-DE so that I can get their comments and feedback to make improvements that suit their needs.

Assignee: @sterkenburgsara 
Peer Reviewer: @it-harrison 

## Description
In tickets #33099, #53691, and #53690, Governance team added 3 new basic cards to the Collaboration Cycle Dashboard. Before future iterations are made to the dashboard, Governance team would like to get feedback, comments and opinions from our OCTO-DE client to help determine what information/data/knowledge would be valuable for them to see, and to help us determine which changes should be made.

In this ticket, Governance team will create a survey for OCTO-DE to complete after reviewing the Collaboration Cycle Dashboard. The survey should inquire about their thoughts/opinions on the as-is dashboard, what's working well, what's not working well, recommendations, etc. The objective should be to gather enough information for Governance team to determine how the dashboard should be modified to suit OCTO's needs (synthesis of findings will take place in ticket #54679)

## Ideas/General thoughts
Maybe we should organize the survey into 5 specific sections - 1 for each of the 3 new cards (per the tickets referenced above), 1 for the existing section of the CC dashboard (days to close tickets) and then 1 section for general thoughts/opinions on the CC dashboard slash the direction OCTO wants the dashboard to take.

I think we should also be straight with OCTO about the current data set and what fields are included in it so they understand the constraints we're currently working with. This could be included in the intro to the survey.

## Impacted Artifacts
N/A

## Tasks
- [x] Sync with @naomimarcussen to get access to Optimal Workshop (for survey setup) and to discuss survey design
- [x] Identify survey questions and overall survey design
- [x] Run survey pilot and incorporate any feedback (share with PO's Ray Wang and Matt Dingee at this time)
- [x] Share with OCTO-DE via #platform-collaboration-cycle Slack channel. Tag the following OCTO-DE leads:
   - Mike Chelen
   - Ray Wang
   - Matt Dingee
   - Mikki Northuis
   - Beth Potts
   - Danielle Thierry
   - Martha Wilkes
   - Shane Strassberg
   - Kevin Hoffman
   - Bill Chapman (will need to be added to channel)
   - Andrea Hewitt
- [x] ask them to share feedback by certain date/time. Given them at least 5 days.

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have given OCTO-DE the opportunity to share their thoughts, questions, concerns and overall feedback about the current Collaboration Cycle dashboard.

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
taken care of!

**Comment by sterkenburgsara** [comment]
@it-harrison I prefer the green for the side-by-side comparison and scannability. Can we sort the bars in some sensible way? either from most to least issues (left to right) or in alphabetical order?

**Comment by sterkenburgsara** [comment]
@it-harrison is it possible to bucket the results in bar-chart with experience standard issue violations by their higher-level category (e.g. all bars that start with 01.XX, 02.XX, 03.XX, 04.XX...etc. get clustered together? Instead of distributed by total count (highest-lowest)? // cc @shiragoodman 

![Screenshot 2023-03-28 at 1.32.31 PM.png](https://images.zenhubusercontent.com/6346cd7ec508fe43b65ae3db/02e3f530-7969-477f-80ea-bfa2691ab3e6)

**Comment by shiragoodman** [comment]
I love this idea, however that might be pretty complicated. @it-harrison what do you think? Do you think you can make this happen?

**Comment by sterkenburgsara** [comment]
Update: synced with @naomimarcussen on Monday, March 27 to get access to Optimal Workshop (for setting up the survey) and to discuss survey design ideas.

**Comment by it-harrison** [comment]
@sterkenburgsara @shiragoodman yes, I'm sure I can do that - will be a nice improvement!

**Comment by shiragoodman** [comment]
Due to dependencies on ticket #55104, this ticket has not been able to move forward and will continue into the next sprint.

**Comment by sterkenburgsara** [comment]
@shiragoodman I have not written out all the questions due to dependencies on #55104, but here is a draft of survey intro (including constraints) if you have any feedback on it:

* Governance team has created an MVP Domo dashboard for the collaboration cycle. Before making additional improvements, we would like to use this survey to gather feedback, comments, and opinions from our OCTO-DE client to help determine what would be valuable to see on the dashboard to better evaluate the experience health of VA.gov. We are looking for clear an actionable feedback to help us implement suggestions, including: specific desired changes to any existing cards or suggestions for entirely new cards. From there, we will iterate on and expand this dashboard to more clearly reflect OCTO-DE priorities. Please keep in mind our current dataset constraints, which are detailed below.

* Constraints: Currently, we are working with an exported dataset from GitHub, which allows us to utilize data from issue-tickets that are generated at staging review for VFS teams. Usable datapoints: **open and close dates** on issue tickets and various **labels**. Here is a list of labels we have to work with: 
   *  508-defect level
   *  Experience standard violations
   * VFS team name and product (currently, usage of this label is inconsistent and would be unreliable unless cleaned up over time)
   *  Practice-area(s) affected by issue

**Comment by it-harrison** [comment]
> @it-harrison is it possible to bucket the results in bar-chart with experience standard issue violations by their higher-level category (e.g. all bars that start with 01.XX, 02.XX, 03.XX, 04.XX...etc. get clustered together? Instead of distributed by total count (highest-lowest)? // cc @shiragoodman
> 
> ![Screenshot 2023-03-28 at 1.32.31 PM.png](https://camo.githubusercontent.com/e2ca481689bfbb83f2af8a14d6e344efd8ab8efe25f044e8c4699422edec7e2d/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3633343663643765633530386665343362363561653364622f30326533663533302d373936392d343737662d383065612d626661323639316162336536)

@sterkenburgsara @shiragoodman I have implemented this

**Comment by shiragoodman** [comment]
@it-harrison the change looks good. However it looks like it's still using the old data set that will soon be archived. [Per this post, ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55104#issuecomment-1490330766 )we need to update all cards in our dashboard to use the new data set that Analytics and Insights created. 

Let me know if this isn't clear or if you have questions.

**Comment by it-harrison** [comment]
> @it-harrison the change looks good. However it looks like it's still using the old data set that will soon be archived. [Per this post, ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55104#issuecomment-1490330766)we need to update all cards in our dashboard to use the new data set that Analytics and Insights created.
> 
> Let me know if this isn't clear or if you have questions.

@shiragoodman you're right - I am going to update the dataset next.

**Comment by shiragoodman** [comment]
@sterkenburgsara I did a quick review and so far, everything looks great. Here are some comments:

- The first page is very brief. Did you plan to add the info you drafted above in [this comment?](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54676#issuecomment-1488981397)
- The images were pretty small. I'm assuming this is why you added the link to the Domo dashboard. I think this is a good alternative, but we'll need to make sure all folks we send this survey to have been given access to view the dashboard as it's not public.

I'll review again tomorrow in more detail. thanks!

**Comment by it-harrison** [comment]
@sterkenburgsara I love this method of getting feedback. It's very easy to use and allows us to get a lot of good feedback. My only suggestion is to include the Domo link on all pages where the images are displayed because, as Shira pointed out, they are a little small.

**Comment by sterkenburgsara** [comment]
@shiragoodman @it-harrison looking at your feedback and tweaking this today. Thank you!

**Comment by it-harrison** [comment]
@sterkenburgsara @shiragoodman I have added a new card that combines the tickets by category with tickets by issue via drilling down. It is at the bottom of [our dashboard](https://va-gov.domo.com/page/1340527018). For now I have left the dedicated tickets by category / tickets by issue cards for comparison.

**Comment by it-harrison** [comment]
@sterkenburgsara a small point: 
If we want the category number ("1" below) to be included in the the category text ("2" below) for clarity then the tooltip displayed on hovering over a category ("3" below) is a little confusing.
![Screenshot 2023-04-06 at 11.40.41 AM.png](https://images.zenhubusercontent.com/61d9eb4308ca5570b5eec560/c32f5586-a9c3-4857-9831-9f0628f8e31c)

**Comment by shiragoodman** [comment]
@it-harrison LOVE THIS!!!! This is fantastic. Thank you so much for putting in the effort.

**Comment by shiragoodman** [comment]
Let's share this with @andreahewitt-odd for her feedback.

**Comment by sterkenburgsara** [comment]
@shiragoodman sounds good. I made updates to [the survey](https://dj540s05.optimalworkshop.com/questions/006g33qm), and it is ready for another pass with your editing eyes. Can you and @it-harrison send any feedback by EOD tomorrow and I'll implement changes / share with @raywangoctova & @andreahewitt-odd at that point?

**Comment by it-harrison** [comment]
@sterkenburgsara the survey looks very good.  Here are a few things you might consider tweaking:
* capitalize "collaboration cycle"
* don't list our data constraints but instead specify that limitations exist; on the one hand it's probably difficult to read the constraints and understand them and on the other it might limit OCTO's thinking...we want to know what they want and if necessary we might be able to get more data from other datasets
* there are some leading questions when asking for feedback on a specific card, e.g. "how helpful do you find this metric about the time it takes teams to close issues identified during staging reviews?
" but this text explains the card and the card should speak for itself (it does have a title that explains it)
* on question 1 you show a graph and a table (two cards) but the question is targeting the graph...so tweak the question or remove the table
* question 7 asks "what other visuals" but maybe we should ask "what other metrics" or something along those lines
* the text responses on 7/8 shouldn't be required
* for question 11: I'm a little confused. This implies the dashboard has problems but we haven't gotten feedback yet. Maybe change to something like: "What decisions would you like a dashboard help you make?"
* for question 12: I would change to "What information needs do you have for this dashboard based on your practice-area or specialty? How can we address those needs better?" just to make the question a little simpler.

**Comment by it-harrison** [comment]
@sterkenburgsara also, I tweaked the tooltip.

**Comment by sterkenburgsara** [comment]
Update: finalized draft of survey and sent to @andreahewitt-odd on Wednesday, April 12. She had no suggested changes, so we have sent onward to @humancompanion-usds and @raywangoctova for additional feedback and approval. Goal is to ship this out to OCTO-DE leadership for feedback on Monday 4/17/23. // cc @it-harrison

**Comment by sterkenburgsara** [comment]
This ticket is partially complete, but has remaining tasks. It will move into the next sprint.

**Comment by sterkenburgsara** [comment]
Update: sent out reminder via Slack on 4/19/2023, requesting all survey responses are submitted by EOD Friday 4/21/2023. So far, 6 participants have taken the survey.

**Comment by sterkenburgsara** [comment]
Closed survey on Friday, and will synthesize results in next ticket.
