### ISSUE TITLE
Update Spanish COVID pages with copyedits

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#54682]
## Issue Description

Ana did a copyedit of all of our live COVID-19 Spanish pages and found several inconsistencies and other edits we need to make in Drupal. 

## Tasks
- [x] Update COVID FAQs (Ana)
- [x] Update main vaccine page (Ana)
- [x] Update About vaccines page (Ana)
- [x] Update boosters page (Ana)
- [ ] Review COVID FAQs (Megan)
- [ ] Review main vaccine page (Megan)
- [ ] Review About vaccines page (Megan)
- [ ] Review boosters page (Megan)
- [ ] Publish COVID FAQs (Megan)
- [ ] Publish main vaccine page (Megan)
- [ ] Publish About vaccines page (Megan)
- [ ] Publish boosters page (Megan)

## Acceptance Criteria
- [ ] Live COVID pages are all up to date

**Comment by ABeltran77** [comment]
Got it, thanks!

**Comment by ABeltran77** [comment]
Updated main vaccine page

**Comment by RLHecht** [comment]
These have all been updated when we made changes in other tickets with the end of the public health emergency. Closing ticket.
