### ISSUE TITLE
526 Testing for EKS migration effort

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#54687]
## Issue Description
vets-api service is migrating to EKS (Amazon's K8 service) from BRD. This ticket covers the testing effort for all vets-api endpoints being called by 526ez. 

Relevant Dates:
As of Feb 28, 2023 - migration has been fully completed in dev and staging environments March 16th - March 28th - Available in production for testing
March 28th - Switch to EKS

---
## Tasks
- [ ] Test happy path for all vet-api endpoints being used by 526

## Need to Know
- [Collection of tickets related to EKS migration](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+is%3Aopen+%22%5BEKS+Testing%5D+%5BDEV%5D%22+in%3Atitle+label%3Asquad-1%2Cbenefits-team-1+label%3Asquad-2%2Cbenefits-team-1)
- [Postman/Insomnia collection & auth instructions](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/teams/vsa/teams/benefits-memorials/endpoints)
- [Testing schedule and end date](https://dsva.slack.com/archives/C04M7T1CZAS/p1676395628265819)
- [Endpoint ownership doc](https://docs.google.com/spreadsheets/d/1pj8D4cXtHta8VsO53Q3AUKBHwbjRmo3v0BJHUFuU-c0/edit#gid=623772164)
- [The Test User Dashboard (TUD)](http://tud.vfs.va.gov/) - we have luck with users 228, 64, and sometimes 0

- Test users are not configured the same for all environments - recommendation to test in staging

## Acceptance Criteria
- [ ] All endpoints work as expected and/or return 200 ok
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
cc @navaeddie @colevoss @ahay-agile6 @sethdarragile6

**Comment by navaeddie** [comment]
A few notes from meeting with Kevin Duensing.

- All endpoints should return 200 ok. If anything seems weird, report it. (Note, some endpoints maybe will include a redirect or the mock data might be unrealistic, but report anything that seems wrong)
- Test users are kinda messy. Some work partially, or in some environments but not in others.
- Testing staging is most important. If it works in staging but not dev, that's probably ok. If it works in dev but not staging, we have a problem.
- Follow up with Kevin with questions. He's available to pair.
- Note authentication is hacky. See documents provided below for instructions.

Resources
Endpoint Ownership Document: https://docs.google.com/spreadsheets/d/1pj8D4cXtHta8VsO53Q3AUKBHwbjRmo3v0BJHUFuU-c0/edit#gid=623772164
Note, tab for status on testing: https://docs.google.com/spreadsheets/d/1pj8D4cXtHta8VsO53Q3AUKBHwbjRmo3v0BJHUFuU-c0/edit#gid=0

Other resources: https://dsva.slack.com/archives/C04M7T1CZAS/p1678202477166569

**Comment by colevoss** [comment]
# Auth Notes

- If using [id.me](http://id.me/), change `csp` to [id.me](http://id.me/) and `acr` to `loa3`
- If using a user from [https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv#L226](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv#L226), the 2fa code can be gotten from
- GET `/v0/disability_compensation_form/submission_status/*` means GET `/v0/disability_compensation_form/submission_status/[:param]` (job_id for this example)
- Ensure that ingress and egress are working properly.
- For non-get requests, might be easiest to just go through the UI in vets-website (<env>.gov)

## Links

- [https://idp.int.identitysandbox.gov/account](https://idp.int.identitysandbox.gov/account)
    - used for checking if user is logged in and logging out.
- [https://github.com/department-of-veterans-affairs/va.gov-team/issues/52605](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52605)
    - ticket made for previous 526 teams
- [http://tud.vfs.va.gov/](http://tud.vfs.va.gov/)
    - For [id.me](http://id.me/) 2fa codes (needs socks)
- [https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Sign-In Service](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Sign-In%20Service)
    - Sign in service docs
