### ISSUE TITLE
Discovery for BGS Integration

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#5471]
As a developer I want any relevant or existing documentation about BGS so that I can use it going forward

### **Tasks**

- [x] Identify contact person for BGS
- [x] Identify relevant BGS documentation 
- [x] Identify any existing 

### Acceptance Criteria

- [x] Documentation saved in Github
- [x] Code saved or link accessible in Github
