### ISSUE TITLE
[PM, FE] My VA Claim Status EVSS > Lighthouse: Prep for/complete PSIR Review

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#54714]
## Background
We need to prep for, submit/complete our Privacy, Security, Infrastructure Readiness (PSIR) Review for the updates we're making to My VA's claim status widget, migrating from EVSS > Lighthouse.

## Tasks
- [x] Compile documentation outlined [here](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/privacy-security-infrastructure-readiness-review)
- [x] Submit [ticket](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/new?assignees=td-usds%2C+troymosher&labels=security-review&template=privacy-and-security-review.md&title=Readiness+Review+%5BTeam-Name%2C+Feature-Name%5D)
- [x] Complete any follow up tasks

## Acceptance Criteria
- [x] Documentation prepped, ticket submitted

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)_ NA
- _How can this work be validated?_ NA

**Comment by ajakabcin** [comment]
Submitted [1061](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1061) last Friday, waiting for review/approval.
