### ISSUE TITLE
TSGLI changes for April 14

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#54712]
## Issue Description
TSGLI regulations are changing. We may need to put up an alert before April 14, and then adjust the alert on April 14.

---
## Tasks
- [x] Draft alert and send to Steve (Laura)
- [x] Publish alert on March 15 (Randi)
- [x] Draft new alert for April 14
- [x] Copyedit (Megan)
- [x] Send to Steve for review (Laura)
- [x] Prepub and publish **alert** on April 14 (Megan)
- [x] Prepub and publish **page with alert** on April 14 (Megan)

## Acceptance Criteria
- [x] TSGLI page is updated to reflect changes

**Comment by laurwill** [comment]
@RLHecht , Steve approved the temporary info alert for the TSGLI page. Since Megan is OOO, could you plan to copyedit and publish node 768 on Wednesday March 15?

Once Steve sends the full text of the changes and the updated resources, we can draft evergreen updates to the TSGLI page to publish on April 14.

Thank you!

**Comment by RLHecht** [comment]
The alert is now published. Moving this ticket into the sprint toward the end of the month so we can draft the new content for April.

**Comment by megzehn** [comment]
Thanks, @laurwill. I copy edited this alert: https://prod.cms.va.gov/block/232?destination=/admin/content/alerts

**Comment by laurwill** [comment]
Thanks @megzehn ! I sent this to Steve for approval. We'll wait to publish until he confirms all the updates are live on the linked benefits.va.gov page. 

Also noting per our new process for alerts that I've added a separate publishing step for the alert to the top of this ticket.

**Comment by megzehn** [comment]
Thank you, @laurwill! Confirming that I published the alert and node 768 with the alert.

**Comment by laurwill** [comment]
Validated! @RLHecht we can close this.

**Comment by RLHecht** [comment]
Thanks! Closing.
