### ISSUE TITLE
Access for BGS Integration

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#5472]
### User Story
As a developer I want access to BGS so that I can integrate it with the other services

### Tasks
- [ ] Identify BGS access owner
- [ ] Determine BGS access process + share with relevant team members 
- [ ] Request access for team

### Acceptance Criteria

- [x] Ticket for access has been submitted

**Comment by bshyong** [comment]
Service requests for use within VA.gov has been filed
 SR-002854 and SR-002855.

BGS tracking numbers are SR 1198911 and SR 1198910
