### ISSUE TITLE
[FE] Add events for phone number on details pages and update event for details page link click

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#54720]
## Tasks

- [ ] For the GA events for clicking on the details page link, update those values to include "check-in" and "pre-check-in" respectively. Currently, they only have the nav-check-in prefix. 
- [ ] Can we create an event to track the phone number clicks on the detail pages for both pre check in and check in? Again, would be good to include "check-in" and "pre-check-in" in the values. 

## AC

- [ ] GA events have been added and validated

**Comment by benbrasso-agile6** [comment]
@wullaski You have time to tackle this one?

**Comment by sarahknoppA6** [comment]
@benbrasso-agile6 to validate

**Comment by benbrasso-agile6** [comment]
Validate on stage

**Comment by benbrasso-agile6** [comment]
nav-check-in-details-link-clicked

nav-check-in-details-phone-link-clicked
