### ISSUE TITLE
[BRD] Upgrade bundler version to latest in BRD image

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#54723]
## Description

With Ruby upgrade occurring, bundler will most likely need to be updated in BRD

## Tasks
- [ ] Review current version
- [ ] Upgrade documentation and criteria's
- [ ] Upgrade version without any breaking changes

## Acceptance Criteria
- [ ] Bundler is the latest (2.4.7 as of 3/7/2023)

**Comment by npeterson54** [comment]
adding to sprint

**Comment by oseasmoran73** [comment]
Moved tasks over to #53658 . Closing ticket as its now a dup
