### ISSUE TITLE
Profile: Sprint 7 (3.29.23 - 4.11.23)

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-team#54733]
## Sprint 6 Retro
[EasyRetro board link](https://easyretro.io/board/f4051524-d7be-43a4-8c50-f43d887f3a7f/d2159f31-477d-4e8e-90cc-7dd1a3715572)

## Sprint 7 Notes
Sprint 7 epic was created using [this outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/sprint-objectives/profile/sprints-1-10-Jan23-May23.md#sprint-7-329---411) 

## PTO
None scheduled at this time.

## Sprint Goals
- Accessibility updates
- Direct deposit migration EVSS > Lighthouse
- Notification preferences
- Logged-in IA/nav research
- Onboarding

## Carrying Over
FE/BE
- [ ] #54879 (1pt left)

BE
- [x] #54887 (1pt left)

## Accessibility
FE - Adam
- [x] #55296 (5 pts)

##  Direct deposit migration EVSS > Lighthouse
FE - Adam
- [x] #54769 (2 pts) - shared w/ BE
- [ ] #54771 (4 pts) - shared w/ BE

BE - Tom
- [x] #54769 (2 pts) - shared w/ FE
- [ ] #54771 (4 pts) - shared w/ FE
- [x] #54762 (3 pts)
**Is backend/frontend work done at this point? If so, we are ready to move on to QA tasks next sprint**

## Notification preferences
FE - Adam
- [ ] #55657 (3 pts)
- [ ] #55658 (2 pts)

Design
- [ ] #55895 (3 pts)

## Logged-in IA/nav research
Design - Liz
- [x] Run research (8 pts) - #55595 
- [x] Topline summary (3 pts) - #56303
- [ ] Start synthesis (8 pts) - #56304

## Other
Design/Rsch - Flo
- [x] Prep for sharing Military Info research findings at VFS Design Sync #55641 (5 pts)

FE - Adam
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/56003

## Onboarding
_New PM starts on April 3rd. Some of these tickets might continue to Sprint 8 if unable to complete in this sprint._ 

PM - Travis
- [ ] Travis Onboarding #50955

Profile Team
- [ ] Personal info demo #55475 (2 pts)
- [x] Contact info demo #55476 (2 pts)
- [ ] Military info demo #55477 (2 pts)
- [ ] Direct deposit demo #55478 (2 pts)
- [ ] Notification settings demo #55479 (2 pts)
- [ ] Account security demo #55480 (2 pts)
- [ ] Connected apps demo #55482 (2 pts)

## Unplanned Work
BE - Tom
- [x] #56223 (1 pt)

**Comment by BerniXiongA6** [comment]
@adamwhitlock1 will create a new FE ticket for MHV changes that affected Account Security -- critical to get this fixed asap
