### ISSUE TITLE
Add new web components and patterns for common form fields

### ISSUE THREAD

**Issue by PSIEBENLIST** [department-of-veterans-affairs/va.gov-team#54747]
**Problem Statement**
Smooth and standardized form digitization isn’t being achieved today because of a complex, inflexible, and poorly documented forms system for front end engineers and designers. The forms library is supposed to be good at building simple forms quickly. However, based on our experience building simple forms, we know this is not the case. Our designs and engineers have encountered challenges developing the most standard form elements due to misalignment of patterns and components in the forms library and design system. These common form elements comprise nearly [half of the fields](https://vfs.atlassian.net/wiki/spaces/VFT/pages/2591522817/Simple+Form+Fields+Audit) in the simple forms we are targeting for digitization. This misalignment creates complexity and workarounds in the form development process and provides an inconsistent UX for both forms library and end users. Additionally, the existing patterns in the forms library use react components or widgets (e.g. checkbox, text input), whereas the design system is undergoing an effort to update react components to use web-components.  

**How might we**
How might we make it easier for forms library users to efficiently develop standardized form elements that are consistent across form applications and easily maintained? 

**Hypothesis** 
- By updating patterns in the forms library to align to existing design system patterns, we can reduce the time spent tweaking or customizing forms library components for both the VA forms team and future VFS teams
- By updating patterns in the forms library to align to existing design system patterns, we can improve confidence and reduce iteration through the collaboration cycle
- By creating and passing in new widgets to patterns in the forms library, we will create patterns that can automatically receive updates when components in the design system are changed and thus not add to the number of variations in the forms library that are out of sync with design system components

Web Components:
- [x] Prototype one existing widget to include a web-component and determine level of effort needed to update the full suite of widgets the VA forms team use in common patterns [(Ticket #137)](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/137)
- [x] Implement new text input web component [Ticket #179](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/179)
- [x] Implement new checkbox web component [Ticket #205](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/206)
- [x] Implement new select web component 
- [x] Implement new memorable date web component 
- [x] Implement radio web component
- [x] Implement text area web component

Patterns:
- [x] Implement new SSN pattern [Ticket #202](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/202)
- [x] Implement new full name pattern 
- [x] Implement new DOB pattern 
- [x] Implement new address pattern 
- [x] Implement new phone number pattern 
- [x] Implement new email pattern
- [x] Implement relationship to veteran
- [x] Implement radio pattern
- [x] Implement yes / no pattern
- [ ] Implement address pattern for arrays
- [ ] checkbox group

Mock form: https://staging.va.gov/mock-simple-forms-patterns/introduction
Mural board with Work / Bugs / Issues: https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1686754885931/38695c51204f165100df60b07ae2b03cc992686a?sender=bdba8d0a-4b18-42ce-b8ef-777c7753e1ee
