### ISSUE TITLE
Certificate of Eligibility | 400 and 404 errors from LGY

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#54751]
## Issue Description

LGY is still returning 400 and 404s on the GET /determination endpoint and PUT /application endpoint. There aren't a lot of these but we do get them every day. This is almost certainly an issue on LGY's end and LGY is working on it. LGY occasionally reaches out for information on the issue. This ticket represents that communication work.

---
## Tasks
- [ ] Help LGY fix the issue.

## Acceptance Criteria
- [ ] No more errors in Sentry.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
@data-doge moving this to the product backlog since it's still in discovery and needs refinement. When you get back, we can talk about what the acceptance criteria/solution should be.

**Comment by sortizsh** [comment]
Fred will look into this

**Comment by steele-lm** [comment]
@tblackwe Can we close this ticket?
