### ISSUE TITLE
Alert users when VAOS can't display some appointments

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#54753]
## Task Description

- Sometimes backend services can't display types of appointments. Users need to be notified when VAOS can't display some appointments
- We don't know if the user has appointments of the type we can't display. So some users will be notified, even though the issue doesn't affect them.
- Given that, the notification should be less disruptive than a standard alert, but still provide information when needed
- The situations in which appointments can't be displayed are:
    - HSRM doesn't return CC appointments
    - HSRM doesn't return CC requests
    - VVS doesn't return Telehealth appointments

## References
- #53370 - Alert when HSRM is unavailable
- #53372 - Alert when VVS is unavailable

## Acceptance Criteria
- [ ]

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by outerpress** [comment]
- @Cieramaddox to work with @ldelacosta on getting content review started

**Comment by outerpress** [comment]
@ldelacosta adding this to the small improvements Epic - this clarifies in the alert that we can't show community care or VVC appointments. Was there a technical barrier to this one?

**Comment by outerpress** [comment]
Marcy found an issue with this messaging conflicting today. I'd add fixing this issue to the work. [Slack thread](https://dsva.slack.com/archives/CMNQT72LX/p1711377034865339)

<img width="608" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDhJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--009ebbb35b1f7f9176f5a8fc71f0579e6ede411b/image.png" alt="image.png" />
