### ISSUE TITLE
Pull in additional screens that need to be updated

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#54750]
## Tasks

- [x] Pull in all other pages into the Additional Screens page in the [unified experience sketch file](https://sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec). For example, ID verification, check in with a staff member pages, general error page, etc. (Don't include travel reimbursement pages for this ticket.) 
- [x] Determine which of those pages need to be updated based on the unified experience direction. For example, need help will need to get updated on all of those wireframes. (That might be the only change.) 
- [x] Create ticket that outlines the design changes that need to be made. 

## AC

- [x] Pull in all other pages into the Additional Screens page in the [unified experience sketch file](https://sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec). For example, ID verification, check in with a staff member pages, general error page, etc. (Don't include travel reimbursement pages for this ticket.) 
- [x] Determine which of those pages need to be updated based on the unified experience direction. For example, need help will need to get updated on all of those wireframes. (That might be the only change.) 
- [x] Ticket created for next steps for design

**Comment by benbrasso-agile6** [comment]
We did some work on this this sprint. After chatting more, we are going to roll this over into next sprint. I'm going to help identify the pages, and then Ya-ching is going to help to bring them in on [this ticket ](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/54810). 

Keep 54750 at a 3 pt.

**Comment by kellysmith1008** [comment]
After meeting with the team today, there are a few more frames in here we want to explore more in detail. Opening this ticket back up, but estimate the points remaining to be 2 or less

**Comment by kellysmith1008** [comment]
Rest of the work has been identified. Closing the ticket
