### ISSUE TITLE
BE | Profile | Direct Deposit | Update BE Documentation

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#54762]
## Background
Add backend documentation for new C&P direct deposit API.

## Tasks
Provide documentation for:
- [ ] Vets-API
  - [ ] Endpoints
  - [ ] Vets-API code base
  - [ ] CCG Configuration
  - [ ] Important behaviors (email notifications, control information rules)
  - [ ] Swagger Docs
- [ ] Lighthouse DD API
  - [ ] Provides documentation references
  - [ ] Point of contacts
  

## Acceptance Criteria
- [ ] Documentation added to sensitive repo
- [ ] Review documentation with FE developers
