### ISSUE TITLE
Team QA | Profile | EVSS>LH | Direct Deposit C&P | QA Testing

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#54771]
## Background
Test with staging users ; this does not include UAT.

- [Thread asking platform support the browsers we need to test with](https://dsva.slack.com/archives/CBU0KDSB1/p1688586976772009)
- [browser support policy ](https://depo-platform-documentation.scrollhelp.site/developer-docs/browser-support-policy)

## Tasks

Use [testing spreadsheet ](https://docs.google.com/spreadsheets/d/1xflLNJhUSVslzLbVQtMkYkzsBGAhIccnmYW0GL_Ihd0/edit#gid=0) from #54870 to test users
- [x] test staging users with C&P Direct Deposit accounts
- [x] test local users (eg. the mocked fraud data) 
- [x] populate spreadsheet 
- [x] add any [adverse findings to the QA test document 
](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/evss-lighthouse-migration/QA/README.md#adverse-findings-summary)

## Acceptance Criteria
- [x] All tested scenarios completed 
- [x] All corrective tickets have been created: see #60945

**Comment by BerniXiongA6** [comment]
Per @adamwhitlock1 -- let's keep this ticket in Ready until FE integration work and initial testing with it is done. Bring into Sprint 8 IF ready, or push out to Sprint 9 if not ready. cc: @mtca6

**Comment by tpharrison** [comment]
@adamwhitlock1 I share a spreadsheet with you that compares test results between EVSS and Lighthouse.  We can review when you get back.

**Comment by tpharrison** [comment]
@adamwhitlock1 - The last PR was deployed yesterday and I ran through some tests.  I'll continue testing things over the next few days in staging, but I should be ready for you to start integrating with FE.

Let me know when you're free to meet and I'll walk you through a few scenarios.  

cc/ @mtcA6
