### ISSUE TITLE
Discovery for eFolder Integration

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#5477]
### User Story
As a developer I want any relevant or existing documentation about VBMS eFolder API so that I can use it going forward.

### Tasks
- [x] Identify contact person for eFolder
- [x] Identify relevant eFolder documentation 
- [x] Identify any existing code 

### Acceptance Criteria
- [x] Code saved or link accessible in Github

**Comment by keithdadkins** [comment]
Blocked until we get access and receive docs from vbms/efolder team
