### ISSUE TITLE
[FE] My VA Audit improvements: Account for error state when messaging endpoint fails

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#54778]
## Background
If we can't connect to `/messaging`, the user should see the "Send a secure message" secondary link. 

Currently, when that endpoint fails we are not seeing the link as we should:

**Incorrect as seen on Staging (with test user Cecil Morgan)**:
![test-case-04-cecil-msg-fail](https://user-images.githubusercontent.com/45603961/223773509-565e3489-b6e6-49d3-ad94-d5e950cbc0fd.png)

## Tasks
- [x] Correct the logic so that when the messaging endpoint fails, users with health care see the "send a secure message" secondary link 
- [x] Make sure GA event tag is present after implementation
- [x] Retest
- [ ] PM to update QA findings documentation

## Acceptance Criteria
- [ ] When the user has unread messages and the appointments API fails the user sees the unread messages alert, the appointments API error message and the 3 secondary links (and no unread messages alert)

**Comment by ajakabcin** [comment]
hey @allisonlu is this ready for validation? I see the PR is merged

**Comment by allisonlu** [comment]
@ajakabcin Ready for validation!

Steps to test:
1. Log into staging as cecil.morgan@id.me
2. Open dev tools on your browser. If you're using Chrome, press **F12** or **Cmd+Option+I** (that's a capital i) and Navigate to the **Network** tab
4. Refresh, find **0** row under **Name** panel or filter with the **messaging** keyword
5. Right click, click **Block request URL**. Another panel should pop up at the bottom of your dev tools
6. `staging-api.va.gov/v0/messaging/health/folders/0` should show up with a checkmark next to it
8. Refresh and confirm that you **DO NOT** see the unread messages warning, a Next appointments card, and **four** secondary links (and the "Send secure message" link is displaying)

**Comment by ajakabcin** [comment]
Confirmed! Thank you for the step by step on how to validate this @allisonlu - so helpful!

![Screenshot 2023-03-24 at 3.01.42 PM.png](https://images.zenhubusercontent.com/60465863a45e7b63743045b3/c0019193-ac52-4a27-ab00-38dd75e8c2ca)
