### ISSUE TITLE
Design | Profile | Logged-in IA research | Recruiting and study prep

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#54777]
## Background

We need to kick off the recruiting process for  the user research for the logged in IA and nav ([research brief](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/ia-and-navigation/2023-generative-logged-in-research#readme))

## Tasks
- [x] Submit research materials to OCTO / Perigean
- [x] Have kick-off meeting with Perigean
- [x] Create Mural board
- [x] Coordinate observers, if needed
- [x] Coordinate feature flag usage - who will do this?
  

## Acceptance Criteria
- [ ] Ready to start research

**Comment by Samara-Strauss** [comment]
@andaleliz can we close this, or is there still work to be done?

**Comment by andaleliz** [comment]
Oh, I totally missed this when closing things out yesterday- def ready to close.
