### ISSUE TITLE
Design | Profile | Logged-in IA research | Create conversation guide

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#54776]
## Background
We need to create a convo guide to support the user research for the logged in IA and nav ([research brief](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/ia-and-navigation/2023-generative-logged-in-research#readme))

## Tasks
- [ ] Draft conversation guide
- [ ] Review with PO
- [ ] Incorporate edits
  

## Acceptance Criteria
- [ ] Guide complete and ready for submission

**Comment by andaleliz** [comment]
Hi @coultonbunney-usds! I have a follow up question to [the comment that you left on the research plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54092#issuecomment-1468177691).

>Does a user differentiate "logged in / authenticated" parts of the website, and "unauthenticated" parts of the website?

I want to clarify the parts of the website you're thinking of.  "logged in / authenticated" makes me think of My VA, and any tool where you can see something about yourself - e.g. the claim status tool, payment history, or upcoming appointments. "unauthenticated" parts of the website to me are essentially all the benefit hub content, and facility locator...search,  I suppose.  Does that align with how you're thinking of it too?

>When a user wants to review information personalized to them, do they use the mega menu to find that information?

For this question, does profile information fit under that umbrella, or are you more thinking of things in the tools I referenced above? 

One of the 3 tasks asks the participant to show me how they would update their address; the other two tasks ask the participant to navigate to something related to a benefit or service they receive. I think between these 3 tasks we'll get to the answer of your question, but wanted to double check in case I need to have something else in my pocket. 

Thanks!

**Comment by coultonbunney-usds** [comment]
@andaleliz 

> Does that align with how you're thinking of it too?

Yes, exactly how I'm thinking about it.

> For this question, does profile information fit under that umbrella, or are you more thinking of things in the tools I referenced above?

I think profile definitely fits in this category, and I think is a nice contrast to the other two tasks you mention. It is a bit higher in the hierarchy, and does not blend in as much with other content on the website (for example, reviewing a previously submitted disability claim is very tied to the disability hub).

**Comment by andaleliz** [comment]
@Samara-Strauss, [the conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ia-and-navigation/2023-generative-logged-in-research/2023-logged-in-user-interviews/conversation-guide.md) is ready for your review.  

I'd like to go ahead and submit the plan for recruiting by EOD Friday, in particular to allow for time to schedule the kick-off meeting with Perigean. If they need a full week to recruit, we'll need to have that meeting in the first part of next week.

The conversation guide might change a bit between submission to Shane, and the start of the study, and I think that's OK.  The tasks are loose and will really heavily rely on my instincts and information the participant shares about their experience.  I'm planning on going through this with a peer, prior to the pilot, to see where I can smooth things out, and iron out any transitions from the new homepage/health landing pages as people move through the site.

I look forward to your feedback!

**Comment by Samara-Strauss** [comment]
One final thing -- let's make sure other OCTO folks have time to give feedback (again, if they choose) to this convo guide. I'd like to give people 2 days for feedback in case they are swamped, so that might mean pushing recruitment to start next Monday or Tuesday instead of EOD tomorrow.

**Comment by andaleliz** [comment]
Thanks for the feedback!

>Re: using the new homepage -- since this is a different URL and does not redirect to My VA after login (which it will once it's transitioned fully to the homepage and uses VA.gov as its URL), I'm questioning whether we should bother with the new homepage. On one hand, it feels silly to test with the current homepage if it's going away. On another, if people login from the homepage and are not redirected to My VA, that's not representative of current functionality. Do you have an opinion on this either way?

I have a slight preference toward testing with the current functionality, to reduce complexities and things I'll need to manage as a facilitator. There are already a lot of things to stay on top of.

>To me, this question is less about overall thoughts on the website and more about specifically what their expectations are around finding information.

Ah, ok. I'm trying to get at what they expect from the site now that they're logged in, vs when they were logged out. I was considering removing that altogether, given the questions in the post-task interview that more directly seeks to understand their expectations around a logged-in experience. (Those were something I added late last night)

>I'd allot more time and questions to that conversation to make sure we have a crystal clear understanding of how we could improve the navigation if the homepage and My VA links aren't an option. I could easily see people saying "oh, it's fine" if they were able to find a link on My VA or the homepage, even after we've asked them to navigate to the task without those pages.

I see your point here, and it's something I feel a little stuck about. This is one reason I want to do a dry run pre-pilot with someone, to figure out how to best navigate that. My expectation is that even if they say "oh it's fine" by going through it we can observe that it isn't if they get stuck or have to go through multiple hub pages to find what they're talking about. If you have any more thoughts about what else I could try, I'd love to hear them!

> This is totally dependent on which version of the homepage we use, let's pick a high-priority task that's not on the homepage or My VA for this last task.

Great call out.  I picked this task because I wanted to choose something that would likely apply to anyone, regardless of their benefits, and requires them to be logged in.  I feel so much more confident in data when we don't have to ask people to imagine a situation applies to them.  Do you think it's OK to keep them in profile, even if it's not a high priority task? We could ask them to:
- change a phone number
- add direct deposit info
- make sure VA has their correct DOB on file

> You might get at this with current questions, but I am curious how they'd compare another site they log into with what VA.gov was like when they logged in. Is it a better/worse/neutral comparison?

I'll add this to the post-task interview, just to be sure it's not missed.

> One final thing -- let's make sure other OCTO folks have time to give feedback (again, if they choose) to this convo guide. I'd like to give people 2 days for feedback in case they are swamped or out tomorrow (some people work compressed schedules and are out every other Friday), so that might mean pushing recruitment to start next Monday or Tuesday instead of EOD tomorrow.

I don't expect they're going to have feedback that drastically changes anything that impacts recruiting, so we can still submit for kick-off, and make changes to the guide while recruiting is happening. As long as nothing major changes with the research plan (particularly recruitment and timing), Shane and Perigean are not impacted by updates to the guide.

**Comment by Samara-Strauss** [comment]
> I have a slight preference toward testing with the current functionality, to reduce complexities and things I'll need to manage as a facilitator. There are already a lot of things to stay on top of.

Agreed. Let's move forward with this approach.

> I see your point here, and it's something I feel a little stuck about. This is one reason I want to do a dry run pre-pilot with someone, to figure out how to best navigate that. 

This sounds good to me. You're a strong enough researcher that I know you won't just let someone get by with "oh, it's fine" when they clearly had trouble with something, or if you know we're not quite getting at the information we need. Hopefully the pre-pilot and pilot sessions will help clarify how or if you want to tweak this.

> Great call out. I picked this task because I wanted to choose something that would likely apply to anyone, regardless of their benefits, and requires them to be logged in. I feel so much more confident in data when we don't have to ask people to imagine a situation applies to them. Do you think it's OK to keep them in profile, even if it's not a high priority task? We could ask them to:

Agreed that whatever the third task is should be a high priority task, but I also think it should be something that doesn't have a path from the homepage or My VA so we can see what people do when they only have the navigation to rely on (even though we're sort of also doing that with the first two questions, but given that people will have already likely found their destination, it's not totally the same).

When you say "do you think it's OK to keep them in the profile", what do you mean? Do you mean to do a task in addition to changing their address? If so, I don't think that's necessary. I'm only curious as to whether people can find tasks across the site, not stuff within a section or page they are already on.

**Comment by andaleliz** [comment]
>When you say "do you think it's OK to keep them in the profile", what do you mean? 

@Samara-Strauss, I meant is it OK to choose a profile-related task, over a high priority task like downloading benefit letters? I don't think any of those other profile tasks I suggested as high-priority as that, and I don't want to use changing an address since that's linked on the current homepage.

**Comment by Samara-Strauss** [comment]
With so many top tasks on the current homepage and My VA, this is tricky! One option for a high-priority task not on the current homepage or My VA is updating dependent information. If we feel that's not appropriate for some reason (though this could be anyone, and does not need to be a child or spouse if those don't apply), then I think it's OK to choose a profile task that's not as high priority, but also not something that's so obscure that they won't care. Updating a phone number is a good idea, or validating that the VA has the correct date of birth or military information on file for someone.

**Comment by andaleliz** [comment]
@Samara-Strauss That sounds good, I'll go with the update dependent information use case.  For my own knowledge, are we ultimately hoping people land on the [View/Change dependents page](https://www.va.gov/view-change-dependents)?  I'm thinking I'll phrase it as "Show me how you'd double check any dependents you have on file with VA", which is more aligned with Coulton's question:

>When a user wants to review information personalized to them, do they use the mega menu to find that information?

Unless we want to get them to the form where they add/change dependents.

**Comment by Samara-Strauss** [comment]
> I'm thinking I'll phrase it as "Show me how you'd double check any dependents you have on file with VA", which is more aligned with Coulton's question:

This sounds good to me.

As for URL, let's try to get them to the actual "view" page, which is at https://www.va.gov/view-change-dependents/view (https://staging.va.gov/view-change-dependents/view for staging if you want to login and see it).

**Comment by andaleliz** [comment]
Hi @clantosswett, @coultonbunney-usds, @mnorthuis, @lalexanderson-dsva, [the conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ia-and-navigation/2023-generative-logged-in-research/2023-logged-in-user-interviews/conversation-guide.md) for the logged-in IA and nav user interviews is complete, and it'd be great to get your thoughts on it if you have bandwidth to review.

I've submitted this to kick-off the work with Perigean, but we have time to fine tune this. If you can provide any feedback you have by Thursday next week (3/22) I'd greatly appreciate it. Thanks!

**Comment by coultonbunney-usds** [comment]
Thanks @andaleliz! This looks really great.

A few questions.

**Task 1: Review medical history**
It seems the task should ultimately result in them getting to va.gov/my-health. If they aren't opted into the new landing page, clicking the My HealtheVet tab in the top right will always direct them to MHV. So there may be a bit of redirection to them successfully completing this task. Would you consider them just clicking on that tab successful? 

**Task 2: Disability rating**
What do you consider successful here? I realize we are more interested in their journey rather than destination, but still, would like to know what the discrete task goal is.

**Other**
I'm not sure how to frame this, but I'm curious to really hone in on the _focus_ of the website. The big difference between VA.gov and other sites is that there is not a dedicated logged in experience - it is presented alongside logged out information - and there is one mega IA/nav across both. Currently this conversation guide focuses on just finding logged in content. I am worried that participants may not be primed to think about all this content sitting next to each and how that might be confusing. Maybe we could throw in a fourth task to find logged out information, and then that could expand how some folks answer the post-interview questions?  

Just a thought. Happy to talk through this more, if what I wrote above doesn't make sense.

**Comment by andaleliz** [comment]
Thanks for the feedback @coultonbunney-usds! I'm glad we can collaborate on this, and grateful for the extra set of eyes.

>If they aren't opted into the new landing page, clicking the My HealtheVet tab in the top right will always auto-redirect them to MHV, which may cause some swirl in the interview.

We're going to whitelist their email address so they will be opted into the new landing page, though I don't think that will do a whole lot for people who aren't enrolled in health care. Thinking more about this generally makes me want to choose a back-up task that doesn't have a one-click option from the navigation (I'll primarily try to create a task from the experience participants share with me).  What do you think about switching to a disability related task, like checking the status of a claim?  Another option could be something education related.

>What do you consider successful here? I realize we are more interested in their journey rather than destination, but still, would like to know what the discrete task goal is.

Success for this task (again, a back up if we don't have anything else to go on) would be landing on the [File for a Disability Increase form ](https://www.va.gov/disability/file-disability-claim-form-21-526ez/)

>Maybe we could throw in a fourth task to find logged out information, and then that could expand how some folks answer the post-interview questions?

This is a really good point. The only concern I have is adding more time to the session and participants getting fatigued, especially screen reader users since those sessions can take much more time.  My current time estimates are conservative, accounting for technical issues and verbose participants, so it may actually be a lot shorter. But for now we're at 42 minutes for non-screenreaders, and over an hour for AT.

What if we add a 4th task to review logged out information, but move it to task 2 or 3, so it's more of a priority.  Then, if people are up for it, I can have them do the additional task to get "bonus" information about logged in content.  It could be something like:

Task 1: Benefit/service related task
Task 2: Review personal information task (review dependents)
Task 3: Logged out content
Task 4: another benefit related task

Thoughts?

**Comment by Samara-Strauss** [comment]
> What if we add a 4th task to review logged out information, but move it to task 2 or 3, so it's more of a priority. Then, if people are up for it, I can have them do the additional task to get "bonus" information about logged in content. It could be something like:

I'm ok with adding one logged-out task so we can add some post-interview questions to evaluate how confusing (or not) it is that logged-out content and  logged-in tools live side by side. However, my personal vote would be to put the logged-out task last since the focus of this work is primarily figuring out what problems exist with navigating the logged-in experience. I'd like us to be able to observe them navigating to at least 3 logged-in tasks so we can feel more confident in our research results than if we looked only at 2 logged-in tasks.

**Comment by coultonbunney-usds** [comment]
I like the idea of keeping a health task included, if possible, but I'm also biased. Whatever you decide is good by me. 

I'm also fine with Samara's suggestion to keep the logged out task fourth, as long as we get to that task at least a few times over the course of the sessions. 

Thanks for allowing me to contribute here. Very excited to see the outcome of this work.

**Comment by Samara-Strauss** [comment]
> I like the idea of keeping a health task included, if possible, but I'm also biased. Whatever you decide is good by me.

I think the plan is to include one should it apply to the veteran. Is that right, @andaleliz? Or are we varying the first two tasks each session depending on how the veteran responds to questions about their existing benefits?

**Comment by andaleliz** [comment]
>I like the idea of keeping a health task included, if possible, but I'm also biased. Whatever you decide is good by me.

Ok; I'll keep it as-is for now and see how it feels during the couple of run-throughs I'll do before the study starts.

> I'm also fine with Samara's suggestion to keep the logged out task fourth, as long as we get to that task at least a few times over the course of the sessions.

That sounds good to me too.  Do either of you have any ideas for a logged-out task? Reviewing disability compensation rates or something around edu benefits both come to mind for me.  The PACT act page is a top page for logged-out users too, according to analytics.

>I think the plan is to include one should it apply to the veteran. Is that right, @andaleliz? Or are we varying the first two tasks each session depending on how the veteran responds to questions about their existing benefits?

The latter. Ideally, the tasks will be having the Veteran show us how they do something related to their own benefits, which we'll learn about in the warm-up. If they don't give me much to go on, then I have "find medical records" and "file for a disability increase" as back-ups to use instead.

**Comment by Samara-Strauss** [comment]
> The latter. Ideally, the tasks will be having the Veteran show us how they do something related to their own benefits, which we'll learn about in the warm-up. If they don't give me much to go on, then I have "find medical records" and "file for a disability increase" as back-ups to use instead.

Thank you for clarifying. This plan sounds good to me.

**Comment by andaleliz** [comment]
After the dry run yesterday, I've landed on this for the logged-out task:

> imagine you wanted to learn about any options offered by VA to pay for school, either for yourself or your dependent. How would you do that?

I haven't received any other feedback so I'll close this out for now. Definitely still _open_ to feedback if any one wants to share comments via Slack or another way :)
