### ISSUE TITLE
Submit test-user updates to TUD

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#54782]
## User Story
As a governance team member, I want to provide QA with updated test users to add to the Test User Dashboard (TUD), so that I can rely on an accurate variety of test users at all login/credential levels for my staging reviews.

Assignee:
Peer Reviewer:

## Description
Currently the TUD has 39 test users, which seem to pull from this document. Some are outdated/incorrect and do not successfully login. This other document, which the MyVA team provided us for their most recent staging review on 3/9/23, seems much more thorough and accurate, but is missing the information about which login level (e.g. LOA1 vs. LOA3) the test user is. 

We need to provide additional test user information to QA (@holden-hinkle) and they will create a ticket to add those users to TUD on our behalf. We should also update them on which users are no longer functioning as expected.

## Impacted Artifacts
* [Test User Dashboard](https://tud.vfs.va.gov/)
* [GH Test Users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/test_users.csv) - what I believe TUD is pulling from?
* [GH MVI Staging users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv) - appears more accurate/updated

## Tasks
- Identify working test users that can be added to TUD (across all login levels)
   - Unauthenticated
   - LOA1 
   - LOA3
  - Other?
- Identify any existing test users in TUD that are not functioning as expected
- Compile data and submit to QA (@holden-hinkle). They will create a ticket to add updates into TUD.

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] _Placeholder AC_

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by jdatoddball** [comment]
@sterkenburgsara 

Sara,

Thank you for creating this thoughtful ticket. I am a member of the DevEx team and we are currently working on a prototype that is similar to TUD but will offer many more features and unique logic to ultimately benefit a larger audience regardless of identity/signin. While we will not be updating TUD, your desire to rely on an accurate variety of test users at all login/credential levels for your staging reviews will be fulfilled using the Test User Portal in the near future. The goal is to give VA Developers and Product Owners the ability to confidently test their products prior to releasing to production. It's worth noting our product is a VA wide solution, not just a VA.GOV solution. Please stay tuned as we hope to deploy very soon. You are welcome to follow our progress and contact us on the VA OCTO Slack in the #ves-developer-experience-team channel.

Best,

Jamie
Product / Delivery Manager
DevEx

**Comment by shiragoodman** [comment]
thank you so much, @jdatoddball . We look forward to seeing the demo! I will coordinate scheduling that with you via Slack.
