### ISSUE TITLE
Access for eFolder Integration

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#5478]
### User Story
As a developer I want access to eFolder so that I can integrate it with the other services

### Tasks
- [x] Identify eFolder access owner
- [x] Request access
- [x] Get onboarding info and docs.
- [ ] Test connecting to lower environments using the connect_vbms gem.

### Acceptance Criteria
- [x] Ticket for access has been submitted
- [x] Documentation saved in Github
- [ ] Verify we can connect to lower environments

**Comment by keithdadkins** [comment]
Blocked until we hear back from vbms/efolder team.

**Comment by jjulian** [comment]
* vets-api already has eFolder integration (!)
* got the client package via email
