### ISSUE TITLE
[FE] My VA audit improvements: Update GA tag on "Review your messages" link

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#54792]
## Background
In staging, the GA event tag on the "Review your messages" link in the unread messages alert within the Health Care section of My VA is `Navigation - Link List - Health care - Review your messages`. However it needs to be the same as the GA event tag on the "Send a secure message to your health care team" secondary link that appears in the Health Care section when the user has no unread messages. 

These two links go to the same destination and should be tracked with the same event tag.

|Link on My VA | Link destination | Current GA event tag on staging | 
|--|--|--|
|Send a secure message to your health care team (appears as secondary link when user has no unread messages or messaging error occurs) | `https://mhv-syst.myhealth.va.gov/mhv-portal-web/secure-messaging`| Navigation - Link List - Health care - View your messages |
| Review your messages (appears in alert when user has unread messages) | `https://mhv-syst.myhealth.va.gov/mhv-portal-web/secure-messaging` | Navigation - Link List - Health care - Review your messages|

## Tasks
- [ ] Update GA event tag on "Review your messages" link to be the same tag as on the "Send a secure message to your health care team" (i.e. it should be Navigation - Link List - Health care - View your messages)
- [ ] Test
- [ ] Coordinate with PM to get assistance from Analytics team to review this change as needed
- [ ] Move to validate

## Acceptance Criteria
- [ ] The "Send a secure message to your health care team" and "Review your messages" links are tracked the same way in Google analytics and Domo 

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ Log into staging with Cecil Morgan, verify GA event tag on "review your messages" link

## Resources
Screenshots of tag implementation on Staging (before)
**1.  Send a secure message**
![Health care  Send secure message link list](https://user-images.githubusercontent.com/45603961/223801235-cd2269bf-0694-41ef-ac35-1c593378111c.png)

**2. Review your messages** 
![Health care  Review your messages ](https://user-images.githubusercontent.com/45603961/223802779-a5f16c70-fd7d-46ba-a1bf-38e8b50eb9e0.png)
