### ISSUE TITLE
Update Spanish disability pages with QA changes from translators

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#54793]
## Issue Description

We sent the State Department translation team live links of the 3 Spanish disability pages for QA. When they send us back corrections, we need to update in Drupal and republish the pages.

QA back from translation team: [https://app.zenhub.com/files/133843125/7fca144f-48b4-4601-a182-b9fe92653f4b/download](https://app.zenhub.com/files/133843125/7fca144f-48b4-4601-a182-b9fe92653f4b/download)

## Tasks
- [x] Update disability eligibility page
- [x] Update how to apply page
- [x] Update after you apply page
- [x] Review eligibility page (Ana)
- [x] Review how to apply page (Ana)
- [x] Review after you apply page (Ana)
- [x] Publish eligibility page (Megan)
- [x] Publish how to apply page (Megan)
- [x] Publish after you apply page (Megan)

## Acceptance Criteria
- [x] Pages are live with corrections

**Comment by ABeltran77** [comment]
- TTY (por sus siglas en inglés) 

- del 2023

**Comment by RLHecht** [comment]
These are published. Moving to validate.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
