### ISSUE TITLE
Update Spanish health pages with QA changes from translators

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#54794]
## Issue Description

We sent the State Department translation team live links of the 3 Spanish health pages for QA. When they send us back corrections, we need to update in Drupal and republish the pages.

QA doc from translators: [https://app.zenhub.com/files/133843125/504b81fd-67b9-41cc-9dc0-7e75461e739b/download](https://app.zenhub.com/files/133843125/504b81fd-67b9-41cc-9dc0-7e75461e739b/download)

## Tasks
- [x] Update eligibility page
- [ ] ~Update how to apply page~
- [ ] ~Update after you apply page~
- [ ] Review eligibility page (Ana)
- [ ] ~Review how to apply page (Ana)~
- [ ] ~Review after you apply page (Ana)~
- [ ] Publish eligibility page (Megan)
- [ ] ~Publish how to apply page (Megan)~
- [ ] ~Publish after you apply page (Megan)~

## Acceptance Criteria
- [x] Pages are live with corrections

**Comment by RLHecht** [comment]
@ABeltran77 Can you compare the spreadsheet the translation team provided to the screen shot here and let me know if the changes look OK and if any changes are missing? Thanks!

![Screen Shot 2023-03-13 at 2.12.06 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/5cdfe8dd-2b43-4a76-a173-1f5947855f41)

**Comment by ABeltran77** [comment]
Looks good, just in  last two bulletes the sentences should read “del VA”.

**Comment by RLHecht** [comment]
Per slack convo we're going to leave "del" out since we don't use "the VA" and the rest of the page has it without. Publishing!

**Comment by RLHecht** [comment]
These changes are live. Closing ticket.
