### ISSUE TITLE
[Tech Debt] Finish deprecating necessary Git Hub support files

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#54806]
## User Stories
As a VFS team member,
I need to know when a GitHub markdown file is no longer relevant and is out of date,
so that I am not relying on outdated information,
so that I know where to go for the source of truth.

As a Platform Content team,
I need to know what GitHub markdown files are no longer relevant, are maintained, and were migrated to the Platform website,
so that we can add a deprecation message on them,
so that we can point to the Platform website as the source of truth.

## Definition of Done

- [x] Remaining documents/files within GitHub that were transitioned to the Platform website will be identified

[See Vicky's notes related to this project](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2582609941/FY23+Q3+Finish+deprecating+necessary+GitHub+files)

- [x] Identified GitHub files that need to be retired will be prioritized

**GitHub folders we can prioritize for archiving/deprecating:**

- [“Platform” folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform)
- [“Working with VSP” sub-folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/working-with-vsp)
- Additional URLs Andrea provided below

- [x] GitHub files prioritized to be retired will have a deprecation message on them that points them to the Platform website

## General Info

- Review working-with-vsp folder in Git Hub (need more info on this) for documents that need to be audited and deprecated due to migration of information to the Platform website
- Identify who might best be able to answer questions that don't have a clear owner?
- **Note:** Be careful with links to GitHub URLs that go to files owned by OCTO-DE (vs Platform specific)
- What and where are the files need to be audited?
- Which files need to be deprecated?
- What message(s) will we use to add to the Git Hub files?
- How is the message added within GitHub? Step-by-step to demonstrate to team
- Does anyone need to approve our GitHub file edit for the change to reflect?

## Other info/artifacts

Content team's spreadsheet: https://docs.google.com/spreadsheets/d/1pTzNDqb8jg9_zEYOsTsgsEIbcKUEo8UbIiPHXSwkAz8/edit#gid=0

Andrea's identified URLs that need to retired / Github folders/pages (all of this needs to be moved to confluence or platform website):

- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams 
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/about-vsp
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/accessibility/guidance
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/accessibility/research
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/accessibility/meeting-notes
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/accessibility/wcag21
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/accessibility/resources
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-accessibility-best-practices.md
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-checklist.md
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-product-review-list.csv
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-product-review-list.md
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-request-prelaunch-review.md
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/README.md
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/content
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/design
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/engineering
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/logging
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/platform-newsletter
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/platform-support
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/product-management <- not sure what to do with this one -- Check in with Shira about it
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/quality-assurance
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/security
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/service-design
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/testing
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/triage
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/user-acceptance-testing
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/vsp-offboarding
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/working-with-vsp

**Comment by andreahewitt-odd** [comment]
Governance's last content audit: https://docs.google.com/spreadsheets/d/1DHeJ6N7Z2DfwBY6uk1urnKOr_sLBe7RTl5oIN1-yRQU/edit#gid=619400864

**Comment by EWashb** [comment]
@vbellissimo is there anything you need from me on this one?

**Comment by vbellissimo** [comment]
@EWashb I think we have enough information to get started on retiring the /platform repo. We will be having a team kickoff meeting on Monday to get started on implementing the message on files.

I think the only piece right now that we're not completely sure what to do about is the [/platform/content sub section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/content/README.md) because it looks to overlap with the VA.gov content teams' guidance.

**Comment by EWashb** [comment]
Thank you very much! I will bring the content subsection as an action item to follow up on and I'll keep you posted.

**Comment by EWashb** [comment]
This is ok to close @vbellissimo . I know that the CMS and Content sections are still in GH, but I will take those as action items for myself to coordinate with those teams on determining where their documentations should live.
