### ISSUE TITLE
New Data Analyst Onboarding 

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#54809]
## Issue Description
This ticket is for the work/time for Michelle to provide onboarding/training direction to the new data analyst Christine Young.

Artifacts
Analyst Projects: https://vfs.atlassian.net/wiki/spaces/AT/pages/2428338517/Chloe+Project+Background+Notes
Domo and GA training https://drive.google.com/drive/folders/1Y31thIC-1X2tHCUnwOAiyshrONcZd5Jq

---
## Tasks
- [x] Confluence
- [x] Platform website
- [x] Slack access
- [x] review access, on/offboarding requests for take over 
- [x] ZH set up
- [ ] monthly reports (socks access)
- [x] team shared drive https://drive.google.com/drive/folders/1PCFIkdvz6ptFENxrcw59x23OQ1VdWEH_

## Acceptance Criteria
- [ ] All items have been provided and reviewed.
---
