### ISSUE TITLE
Updates to fields of values files

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#54804]
## Issue Description
As we work through ArgoCD implementations of Preview Environments, some additional alterations are needed to the generated values file for Preview Environments.

---
## Tasks
- [x] Adjust the fullnameOverride field to a unique value (can be the same as UID).
- [x] Adjust the image tag to the correct image tag value, based on what was pushed to ECR.

## Acceptance Criteria
- [x] Values files will contain the correct values
---

**Comment by CBonade** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/12667 in for PR review here

**Comment by CBonade** [comment]
Merged and done.

**Comment by pjhill** [comment]
Thanks for keeping these in values in sync with our ongoing ArgoCD configuration efforts!
