### ISSUE TITLE
[FE] Notification Component: Replace onsite notification with new design system component

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#54812]
## Background
Once the new notification component is complete and added to the design system, we'll need to update the onsite notification on My VA with the new component. Build of component was done in [48726](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48726)

_Requires vets-website release_

## Tasks
- [x] Update code to use the new notification component (instead of the "warning alert component") for onsite notifications, _but behind a feature flag_
- [x] Update tests
- [x] Move to validate and inform PMs and designer that it's ready for validation

## Acceptance Criteria
- [x] New notification component is used instead of warning alert component
- [x] New component is implemented correctly (per design system specs and recommendations)

## Validation
- **_Who can validate this ticket? (FE, BE, Design, PM)?_** any team member
- **_How can this work be validated?_** log into staging with users 11, 81, or 36 to validate use of new component

**Comment by allisonlu** [comment]
PR merged! Should be up on staging this afternon!

**Comment by ajakabcin** [comment]
Confirmed - I'm seeing the component on staging!
