### ISSUE TITLE
[Design] My VA: Revisit design of unread messages alert

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#54813]
## Background
Through our work developing the design system component for onsite notifications ([1181](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1181), [48726](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48726)), we determined that we only want to use that component for onsite notifications. We need to revisit the design of the "unread messages" alert in the Health Care section of My VA

## Tasks
- [x] Review unread messages alert
- [x] Create options for handling the scenario when a user has unread messages 
- [x] Review with team
- [x] Attend collab cycle office hours and document feedback about what they would suggest if we wanted to change the current warning alert style to a card

## Acceptance Criteria
- [x] We have options to consider for how to unread messages in the Health Care section
- [x] We have an idea from Platform what the collab cycle would look like for this update
- [x] We have documented everything for Samara to review when she returns from maternity leave

**Comment by aagosto90** [comment]
The team attended collab cycle office hours on 5/24/23 and were told we will need to submit a collab cycle kickoff ticket for this work and it will recommend all touchpoints including design intent and midpoint review, but those two are not required for this small of a change and we can go straight to staging review if we feel that's all that's necessary. They also said it's perfectly fine not to conduct research for this update.
CC @ajakabcin

**Comment by ajakabcin** [comment]
Thanks @aagosto90 we can close now!
