### ISSUE TITLE
Adjust PE Cleanup jobs

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#54825]
## Issue Description
The cleanup jobs need to be adjusted due to restructuring of the file structure in the infra manifests repository. Some other small tweaks and bug adjustments may need to be made. This will need to be duplicated for the delete jobs in contnet-build and vets-api.

---
## Tasks
- [x] Adjust directory targets for all existing cleanup procedures.
- [x] Add duplicate protection for environment list.
- [x] Propogate these changes to all relevant repositories (vets-website, content-build, vets-api)

## Acceptance Criteria
- [x] Values files and the environment list are cleaned up appropriately.
- [x] All relevant repositories have had their scripts and workflows updated to reflect these changes.
---

**Comment by CBonade** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/23509 vets-website PR
https://github.com/department-of-veterans-affairs/content-build/pull/1506 content-build PR
https://github.com/department-of-veterans-affairs/vets-api/pull/12042 vets-api PR

All awaiting approvals and this will be complete.

**Comment by pjhill** [comment]
Hooray for housekeeping!
