### ISSUE TITLE
Add "VFS Orientation to Platform Website" video to Platform Orientation

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#54824]
## User Story
As a VFS team member, I want to know what Platform Website is and how to use it so that I can utilize it when needing help with VA.gov Platform.

Assignee: @CherylEvans 
Peer Reviewer: @briandeconinck 

## Description
Platform Content team has created a short 1 minute video on the Platform Website and it is specifically aimed at VFS teams. This video would be valuable for new VFS team members and can be introduced to them via the Platform Orientation process, specifically within the Platform Orientation template.

The purpose of this ticket is to add the video as a checklist item to the Platform Orientation template. 

## Impacted Artifacts

- [VFS Orientation for Platform Website](https://www.youtube.com/watch?v=yzl6nyLmqkA&ab_channel=PlatformCrew) youtube video
- [orientation-epic.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/orientation-epic.md)
- [Platform Orientation Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=analytics-insights%2C+analytics-request%2C+governance-team%2C+platform-orientation&template=orientation-epic.md&title=Platform+Orientation+Template+%5BYour+name+here%5D)
- [General Orientation slide deck](https://docs.google.com/presentation/d/1xZMmHtsa65fJ1nMMfFC2PWFBDhBmBWmx1EqQQlPdsVc/edit#slide=id.gf08689d579_0_58) - slide 22

## Tasks
- [x] Edit orientation-epic.md to add a new checklist item to the 'General' section of the template for watching the "VFS Orientation for Platform Website" video on youtube
   - do not add to bottom of list. instead add as 3rd item, after "Watch VA.gov overview video"
   - include link to youtube video within text
- [x] Submit pull request and assign @vbellissimo and @laucon as reviewers (Platform Content team)
- [x] Modify Slide 22 of the General Orientation slide deck
   - we no longer need to share what Platform Website is or the details of what it includes.
   - this slide should now just reference the orientation youtube video and include a link to the video

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] New VFS team members watch the VFS Orientation to Platform Website video when completing the Platform Orientation process

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
@briandeconinck I have completed the tasks above.  I created PR 55392 for you to review, as well as the Vicki and Lauren.  
I edited the [General Orientation Slide Deck](https://docs.google.com/presentation/d/1xZMmHtsa65fJ1nMMfFC2PWFBDhBmBWmx1EqQQlPdsVc/edit#slide=id.gf08689d579_0_58) (Slide 22) as well.  Please let me know if you have any questions or concerns.

**Comment by shiragoodman** [comment]
@CherylEvans i made 1 change to the slide deck to remove the "Caveat" as I don't think we need to mention that anymore (it's been in the deck now for over 2 years). Otherwise it looks good.

**Comment by CherylEvans** [comment]
@shiragoodman Thank you, Shira!  Once Brian gives the thumbs up, I will commit the PR changes and close.

**Comment by briandeconinck** [comment]
@CherylEvans This all looks good!

**Comment by CherylEvans** [comment]
@briandeconinck Thank you, Brian!  I will commit the changes! :-)

**Comment by briandeconinck** [comment]
@CherylEvans Just did a quick commit to fix it. Minor typo in the Markdown formatting, I missed it in my review too.

**Comment by CherylEvans** [comment]
@briandeconinck I certainly appreciate your assistance with this!! :-)
