### ISSUE TITLE
[Spike] Research the difference between test users for the VSP error in staging 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#54821]
## Background
The VAOS FE implemented a change in [#50362](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/50362) to capture a message in the app if VSP system is down. 

The backend service is returning an error in the response body (sample below): 
```
"system": "VSP",
"status": "500",
"code": 10000,
"message": "Could not fetch appointments from Vista Scheduling Provider",
"detail": "icn=1013120820V528557, startDate=2023-01-08T00:00Z, endDate=2024-03-08T00:00Z"

```

**The logic (currently):** 
When FE is fetching the appointments and the response body matches` "system": "VSP,"  "status": "500" and "message": "Could not fetch appointments from Vista Scheduling Provider"`, then the FE will display a message `We cannot display in-person VA appointments` 

### Goal
To understand the behavior that is handled differently between the test users in staging with the same VSP error. 

### Requirements to Consider
- [ ] Review the code implemented in  [#50362](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/50362)

---

## Tasks
- Answer the following questions:
  - [ ] Review test user john.morrison@id.me in staging. When fetching pending appointments, the alert message is displayed. We expected the alert message because we have the response body indicating the VSP error. The user does not have any pending requests. 
<img width="684" alt="Screenshot 2023-03-08 at 4 33 54 PM" src="https://user-images.githubusercontent.com/90797205/223856234-a38d66f9-218f-4b7f-a3cc-66c09a7ee4f2.png">

  - [ ] Review test user cecil.morgan@id.me in staging. When fetching pending appointments, the alert message does not display. Our assumption is that this test user would behave the same way as john.morrison@id.me. The user does not have any pending requests. 
![image](https://user-images.githubusercontent.com/90797205/223852826-1ba4988e-895e-432f-873f-afcb50919bf3.png)

  - [ ] Review test user claudia.c.lapomarda@id.me in staging (who is Community Care eligible). When fetching pending appointments, the alert message does not display. Our assumption is that this test user would behave the same way as john.morrison@id.me since the response body is stating VSP is down. The user does not have any pending requests. 
![image (1)](https://user-images.githubusercontent.com/90797205/223855985-763f7114-1a42-4f65-943e-abe7b89861e4.png)

    - Q1: Provide the analysis why the code is behaving differently for each user with the same VSP error

## Time Box
_ hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---

**Comment by marcynadeau** [comment]
TESTING NOTE:  Unless we mess up staging and disable RPC broker there will be no way for SQA to test this.  Discussed on SoS 3/9/2023:  With the testing that we can do because our, you know, Simi and team can test it locally, will validate that we're getting the right messages that you know when we see these codes come through, it's just the simulation of the code coming through that is difficult to produce.

**Comment by marcynadeau** [comment]
Thomas Joyner on 14/Mar/23 5:05 PM 
 
	Marcy Nadeau There are now 3 separate codes that we can get from VSP failures. An example response with a failure to fetch booked appointments and a failure for fetching requests (as can seen below). I also added a generic VSP failure that is a fallback in case we get in to a scenario where the failure wasn't due to a fetching of requests or booked appointments. 
New codes:
10000 - Failure to fetch from VSP (Generic Error)
10005 - Failure to fetch Booked Appointments
10006 - Failure to fetch Requests

 "failures": [
            {
                "system": "VSP",
                "status": "500",
                "code": 10000,
                "message": "Could not fetch appointments from Vista Scheduling Provider",
                "detail": "icn=500104V500104 startDate=2016-01-25T00:00Z endDate=2025-12-26T00:00Z"
            },
            {
                "system": "VSP",
                "status": "500",
                "code": 10005,
                "message": "Could not fetch booked appointments from Vista Scheduling Provider",
                "detail": "icn=500104V500104 startDate=2016-01-25T00:00Z endDate=2025-12-26T00:00Z"
            },
            {
                "system": "VSP",
                "status": "500",
                "code": 10006,
                "message": "Could not fetch appointment requests from Vista Scheduling Provider",
                "detail": "icn=500104V500104 startDate=2016-01-25T00:00Z endDate=2025-12-26T00:00Z"
            }
        ]

**Comment by ldelacosta** [comment]
We will close out this spike. @JRRoof @simiadebowale
