### ISSUE TITLE
Run pilot session for round 1 of testing grandfathering journey(s) and make any updates afterwards

### ISSUE THREAD

**Issue by tygindraux** [department-of-veterans-affairs/va.gov-team#54820]
### Problem statement
Veterans need to make migrate their DS Logon accounts to Login.gov through grandfathering, which allows them to defer identity proofing.

### Initiative
As part of our preparation for doing research with Veterans, we need to run a pilot session. Jesse has agreed to be our pilot participant for this session. 

We'll follow [this pilot guidance](https://depo-platform-documentation.scrollhelp.site/research-design/research-pilot-participant-guidelines). As well as reviewing the [VA Platform Research Checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist#ResearchChecklist-2.Researchreview).

### Timeline
March 8 - Submit prototype for Midpoint Review
March 8 - Submit artifacts for Research Review
March 9 - Ready documentation is ready (feedback incorporated)
March 17 - Prototypes are ready (feedback incorporated)
March 20 - Pilot session at 12:00pm EST
March 27 to April 6 - Research sessions
April 10 to 12 - Analysis
April 13 to 19 - Share findings

### Acceptance criteria
- [x] Pilot session has been completed
- [x] Research documentation has been updated based on pilot feedback
- [x] Prototype has been updated based on pilot feedback

### Tasks
- [x] @tygindraux prepare for pilot session
- [x] @tygindraux run pilot session
- [x] @CarlDickerson update "VA Digital tools" language and share with Sitewide for review 
- [x] @CarlDickerson update "USAJobs" to use a different example (ask @porta-antiporta or @holytoastr for help on this)
- [x] @MOStudioCarolyn fix MFA clicks in prototypes
- [x] @MOStudioCarolyn add sign in to Login.gov screens towards end of prototype (before upgrade modal)
- [x] @tygindraux update conversation guides to reflect changes to MFA/end of prototype
- [x] @tygindraux update notetaker Mural based on feedback

### Notes
- We discussed potentially adding a 'warning' at the start of account setup that tells Veterans to stay on one device and warns them that if their session is interrupted, or takes over X minutes, it won't work. We agreed to leave this out of immediate updates and to come back to it after round 1 of testing if we see it's going to be a problem. 

### Materials for research sessions
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/research/2023-02-Grandfathering-Migration-Round-1-Usability/research%20plan.md)
- [Conversation guide #1 Modal after sign in](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/research/2023-02-Grandfathering-Migration-Round-1-Usability/conversation%20guide%20%231.md)
- [Conversation guide #2 Email ask to sign in](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/research/2023-02-Grandfathering-Migration-Round-1-Usability/conversation%20guide%20%232.md)
- [Prototype #1 Modal after sign in](https://www.figma.com/proto/8vobVoSl1UqLnXsni3rcvO/Login.gov-Migration%3A-Grandfathering-IAL1-Flow?node-id=41%3A1311&scaling=contain&page-id=0%3A1&starting-point-node-id=41%3A1311)
- [Prototype #2 Email ask to sign in](https://www.figma.com/proto/8vobVoSl1UqLnXsni3rcvO/Login.gov-Migration%3A-Grandfathering-IAL1-Flow?node-id=402%3A2918&scaling=min-zoom&page-id=241%3A1368&starting-point-node-id=402%3A2918)
