### ISSUE TITLE
[DevOps] Remove CircleCI Configuration Files

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#54837]
- Remove CircleCI configuration directory `.circleci/`
- The VA is not renewing CircleCI licenses
- This work needs to be completed by March 15, 2023

## Tasks
- [x] https://github.com/department-of-veterans-affairs/vsp-infra-aws-load-balancer-controller
- [x] https://github.com/department-of-veterans-affairs/vsp-infra-deployer
- [x] https://github.com/department-of-veterans-affairs/vsp-infra-fluentd
- [x] https://github.com/department-of-veterans-affairs/terraform-aws-vsp-synthetic-canary
- [x] https://github.com/department-of-veterans-affairs/terraform-aws-vsp-eks-asg
- [x] https://github.com/department-of-veterans-affairs/terraform-aws-vsp-cms-test

**Comment by little-oddball** [comment]
thank you!
