### ISSUE TITLE
Test eFolder Integration

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#5483]
### User Story
When a user uploads documents to VA.gov then they are uploaded to the eFolder

### Tasks
- [ ] [ ] Test eFolder in lower environments
- [ ] [ ] Test eFolder in production

### Acceptance Criteria
- [ ] Documents properly sent to eFolder
