### ISSUE TITLE
Supplemental Claims | Update design + content documentation

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#54836]
## Value Statement
**_As a_** designer
**_I want to_** ensure documentation is up to date
**_So that_** developers have a clear reference when they're working on tickets.

---
## Background Context
- Revisions have been made to the Supplemental Claims flow since the second usability test, and the documentation has not been keeping up.

## Acceptance Criteria
- [x] Ensure Supp Claim Sketch files are up-to-date
- [ ] Ensure Content Source of Truth is up-to-date

## Designs and Build Notes
- Add here

## Out of scope
- New design requests

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
