### ISSUE TITLE
Create Team of Teams info page for Platform Website

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#54845]
## User Story
As a Platform team member, I want to make sure all VFS teams are aware of the weekly Team of Teams meeting so that we have full participation from all VFS teams and can monitor what's being built for VA.gov.

As a VFS team member, I want to be aware of weekly Team of Teams meeting so that I can be updated on announcements from Platform and have general awareness across all VA.gov teams needed to support each other, collaborate or draw learnings to apply to my own work. 

Assignee: @CherylEvans 
Peer Reviewer: @allison0034 

## Description
The weekly Team of Teams (ToT) meeting occurs every Tuesday at 12:00pm ET for 50 minutes. To this point, VFS and Platform teams have been made aware of the meeting through several different paths:

1. Word of mouth
2. Posts in the #vfs-all-teams Slack channel
3. ([As of 2/7/2023](https://github.com/department-of-veterans-affairs/va.gov-team/issues/51556)) the New VFS Team template

Ideally, we'd like all VFS and Platform teams to participate and attend ToT however the current options for becoming aware of ToT are not reliable. The first purpose of this ticket is to publish Team of Teams information to Platform Website/Getting Started so that it can be visible to a larger audience.

In addition, when new teams/team members do become aware of ToT, they instinctively ask for an invite to the meeting. Due to the quantity of attendees and the ever changing participants, the OCTO PMO (who helps manage the meeting and assemble the slide deck) no longer tracks 1 central meeting invite and instead ask team members to create their own event on their own calendar. The Zoom information is shared on #vfs-all-teams 5 minutes before the meeting start time each week. The second purpose of this ticket is to include information on Platform Website how new team members can sign up/attend ToT via Zoom.

Note: Because Platform Website is a public site, it is extremely important that we do NOT publish Zoom links to it as it could be a security concern. By directing folks to the #vfs-all-teams channel in DSVA Slack (a private Slack instance), we will not be putting ourselves at risk.

## Tasks
- [x] Create draft page for Team of Teams (ToT) under the Getting Started section of Platform Website
- [x] Include the following information on the page:
   - What is ToT
   - When is ToT
   - Who attends ToT
   - Expectations for attendees/presenters
   - How to attend
- [x] Note: much of the above information can be found in the [ToT slide deck.](https://dsva.slack.com/archives/CE4304QPK/p1680022037360499) See intro slide and appendix slides.
- [x] Share with @jwoodman5 for review and approval
- [x] Once published, share with Erica Robbins and Julia Badillo for their review/approval (they do not have Confluence, so unfortunately we'll have to publish first before they can review). 
- [x] Make changes if necessary
- [x] Announce to VFS and Platform teams following the Platform Communication Playbook

Note: We should probably sync with Platform Content since this involves the creation of a new high level page under Getting Started. cc @vbellissimo 

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS team members are able to learn of Teams of Teams via the Platform Website
- [x] VFS team members are able to sign up/attend Team of Teams on their own without any dependencies from Platform and/or the OCTO PMO

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
@vbellissimo Good morning, Vicky.  I am adding a Team of Teams information page to the PW.  The details are outlined in this ticket.  I want your thoughts and insights on the best way forward regarding the preferred location destination for our new page under Getting Started; please advise.  Thank you, Vicky!

**Comment by CherylEvans** [comment]
[Draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2581430288/54854+-+Draft+Team+of+Teams) Team of Team (ToT) page created.

**Comment by vbellissimo** [comment]
@CherylEvans

IA Placement:
From an IA standpoint, I think it makes the most sense to tuck it under "Platform Orientation", especially if you mention it during orientation. I am not sure if you do or not. What do you think?

Content draft:
From an editorial standpoint, you may or may not know this already but here is the [list of launch-blocking issues](https://vfs.atlassian.net/wiki/spaces/AP/pages/1474461889/Create+a+new+Platform+website+documentation+page#Launch-blocking-issues.1). Figured I would share it so you can review it before you put it in the queue to be deployed. 

Thanks!

**Comment by CherylEvans** [comment]
@vbellissimo Good morning, Vicky!  Thank you for your comments and guidance.  I appreciate your including the list of LB issues for reference.  I appreciate your offer for peer review.  Currently, we have four people designated as peer reviewers, including Erica Robbins and Julia Badillo, who are the PMO and Executive Administrator, respectively.  I will make sure that all content meets your team's style guidelines.  Should we run into any issues or need assistance from your team, I will let you know.  Thanks again, Vicky! :-)

**Comment by CherylEvans** [comment]
@vbellissimo ![Screen Shot 2023-03-31 at 8.29.29 AM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/b16ea83c-9e57-4935-813f-0bd7026b084c)It occurred to me that I never answered your question, "From an IA standpoint, I think it makes the most sense to tuck it under "Platform Orientation," especially if you mention it during orientation. I am not sure if you do or not. What do you think?" Team of Teams seems separate from "Orientation" but related, as it's now part of the New VFS team template. It would fit nicely as a third bullet after Orientation Sessions or nested under Guidance for new team and team members.

**Comment by vbellissimo** [comment]
@CherylEvans I think as the third bullet on there, after "orientation sessions".

**Comment by CherylEvans** [comment]
@vbellissimo Perfect!!  Thank you so much for your continued support!! :-)

**Comment by shiragoodman** [comment]
@vbellissimo @CherylEvans I am not sure I agree with it being nested under Platform Orientation since Team of Teams is not owned by Platform. Yes, we introduce it as part of Platform Orientation, but (just like Github and Slack) we don't want to give VFS teams the impression that WE own it and it's our meeting bc it's not. We're publishing to Platform Website bc we get asked constantly about ToT and since PW is easy to access, navigate and use, it just made sense to publish the info there.

**Comment by CherylEvans** [comment]
@shiragoodman @vbellissimo I will defer to both of you.

**Comment by CherylEvans** [comment]
@jwoodman5 @allison0034 @vbellissimo @shiragoodman My initial [draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2581430288/54854+-+Draft+Team+of+Teams) is complete. Please let me know your thoughts, and I will make the changes. Vicky and Shira, do you have any further thoughts on where this page should reside? Thanks again!

**Comment by vbellissimo** [comment]
I was thinking under Platform Orientation because from the readers' standpoint, I figured we'd want to introduce this information to them during their orientation phase. If you think it's going to cause content ownership confusion, then it can be its own page right under Getting Started, probably between the Platform Orientation and accessibility spaces.

**Comment by allison0034** [comment]
@CherylEvans I think the page looks great, it had an extra space under each heading which I deleted.

As far as "where" it belongs, I think Getting Started is the best option for now, but I think the IA of the site needs to be reworked in the future.

**Comment by CherylEvans** [comment]
@allison0034 Hi Allison. I incorporated @shiragoodman comments and would appreciate it if you took a 2nd look at the [draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2581430288/54845+-+Draft+Team+of+Teams+ToT). Thanks, Allison! :-) I'm waiting for Shira to get back to me about the meeting time, but once she does, I will make the change if necessary.

**Comment by CherylEvans** [comment]
@allison0034 I am ready for your review of the latest and greatest [draft of the ToT page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2581430288/54845+-+Draft+Team+of+Teams+ToT). :-)

**Comment by shiragoodman** [comment]
@CherylEvans i added 2 more comments

**Comment by CherylEvans** [comment]
@allison0034 @shiragoodman I made the final edits for your recommendations to my [draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2581430288/54845+-+Draft+Team+of+Teams+ToT). Hopefully we can get this wrapped up/published today.  Once it is published, I will invite Julia and Erica to take a look and make their recommendations.

**Comment by shiragoodman** [comment]
thanks @CherylEvans . I'll take a look soon.

FYSA Chris Johnston took a look at the draft page and expressed concern about folks having to make their own calendar event. He is concerned "that without the invite on people's calendar, they will forget / start to ignore / generally miss the session. This is especially possible as people rotate through and new folks might not grok the importance." He suggested that we look into creating a VA distribution list. If that's something Erica and Julia want to do, great, but that's outside the scope for Governance and we will not be involved 

In the interim, he asked that we publish the page without the "How to attend" section. I pivoted and asked that we include Erica and Julia for their thoughts and opinions. I reached out to them on Thursday 4/6 and asked them to help convince Chris that the current process is a good idea. At least let's try this out for a bit to see if it works, before looking into alternative options. I think Chris' concerns is legitimate, but publishing a page WITHOUT the how to attend info would defeat the entire purpose of doing this.

If you have any questions, let me know. I wanted to loop you in first in case Erica or Julia bring it up while I'm away.

**Comment by allison0034** [comment]
@CherylEvans I am the peer reviewer so I don't think you need to have me review until it is completely done : )

**Comment by CherylEvans** [comment]
@allison0034 Cool!  Once I have Erica and Julia give the thumbs up, I will tag you! :-)

**Comment by shiragoodman** [comment]
@CherylEvans I saw the live page, and pinged Julia and Erica again for their input.

I do have a couple comments about the current page. I took a screenshot for easy reference:
![image.png](https://images.zenhubusercontent.com/5f62315e822e9b2aa88b1f1c/0a0bbdf1-45c9-43ae-9955-e3e169cb5603)
The text I highlighted in yellow is almost verbatim to the script stated by the host (me or Jason) at the very beginning of the ToT meeting. It feels a bit odd to see the exact same language in a place I wouldn't expect it. Can we modify this so it says something like, "Teams partaking in Team of Teams are responsible for creating and sharing their slide and presenting in the meeting." or something similar. I also want to move away from "if you're the representative" bc it's possible and likely that the person who created the slide may not be the same person who is presenting the slide. 

Secondly, the sentence I circiled in red. All is fine there, however please include that Julia and Erica should be contacted via the #team-of-teams-slide-collection channel. We don't want folks DM'ing them.

LMK if you have any questions! Everything is looking great!

**Comment by CherylEvans** [comment]
@shiragoodman Done! Great suggestions! :-)

**Comment by CherylEvans** [comment]
@allison0034 Ready for your review.  

- [New ToT page](https://depo-platform-documentation.scrollhelp.site/getting-started/team-of-teams) on PW

- [Change Announcement](https://dsva.slack.com/archives/C03R5SBELQM/p1681245050587249) made in Slack

- [Input from Julia and Erica](https://dsva.slack.com/archives/C031S5G29LP/p1681158630822979) (If they request additional changes, those will be made as needed.)

- Shared with @jwoodman5 for input and approval, but I haven't heard back yet.  Once he provides input (if any), I will make the appropriate changes.

**Comment by shiragoodman** [comment]
@CherylEvans I pinged Erica again in the thread. Please wait until we here from her before pushing the change announcement.

We may also want to announce this change in ToT but I don't think it belongs on the Governance team slide. @jwoodman5 what do you think? Could this be an announcement made at the beginning or end of the meeting? I don't think Governance should be the messenger here.

**Comment by CherylEvans** [comment]
@shiragoodman @jwoodman5 We await input from Julia and Erica to announce this change and close the ticket. Therefore, this effort will move into the next sprint.

**Comment by allison0034** [comment]
@CherylEvans this looks goo to me, can you delete the extra space above each heading?

**Comment by jwoodman5** [comment]
@CherylEvans Sorry for the delay here. All looks good to me. I did reach out to Chris Johnston to make sure we are in alignment for announcing this on Tuesday (4/18).

**Comment by CherylEvans** [comment]
@allison0034 Thank you, and yes! :-) @jwoodman5 Thank you, Jason!  Please let me know if anything changes.

**Comment by shiragoodman** [comment]
hey @jwoodman5 and @CherylEvans . I saw some discussion via Slack, but not 100% sure where we landed regarding the new ToT page on Platform Website. could you please update me? Thanks!

**Comment by CherylEvans** [comment]
@shiragoodman @jwoodman5 As far as I'm aware, nothing has changed since I published the [page](https://depo-platform-documentation.scrollhelp.site/getting-started/team-of-teams) and [announced the change](https://dsva.slack.com/archives/C03R5SBELQM/p1681821975349429).  My comments and concerns were memorialized in the comment thread of this ticket.  Before publishing the page, I received no additional comments regarding Chris Johnson's concerns.
