### ISSUE TITLE
Complete audit of past staging review tickets to capture any missing the CC-Dashboard label

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#54842]
## User Story
As a governance team member, I want to ensure that all staging review issues have the label CC-Dashboard so that we know they're being surfaced in any Domo queries or dashboards.

Assignee: @sterkenburgsara 
Peer Reviewer: @CherylEvans 

## Description
During the process of deprecating the ["Collab Cycle Feedback ticket for Staging" template on GH](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54424), it was noticed that the code block is missing the `CC-Dashboard` label. This means that any historical usage of that template (used to add a staging review issue outside of the Drafting Template) would be missing the label that feeds our analytics dataset in Domo. 

We want to do an audit to catch tickets that fell through the cracks by identifying tickets with the `CCIssue*` label but that are missing the `CC-Dashboard` label. 

## Impacted Artifacts
* Domo dashboard
* Past GH tickets with `staging` label

## Tasks
- [x] Query Github to identify any `CCIssue*` tickets from May 2021 and later
- [x] Confirm that all tickets have the `CC-Dashboard` label and are assigned to either a Staging Review ticket and/or a Collaboration Cycle Request ticket.
 - If any tickets are identified with missing labels, link them here first before adding the `CC-Dashboard` label. In the early days of this process, we accidentally created many duplicate tickets for BAH. I believed we removed the CCIssue labels but I'd like to make sure first.
 - [x] Shira will review list of tickets without `CC-Dashboard` and give approval
- [x] Add `CC-Dashboard` where applicable
- [x] Do the reverse as well. Query Github to identify any issues tickets with `CC-Dashboard` to identify if any are missing the `CCIssue*` lables

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] All Staging Review issue tickets have the `CC-Dashboard` label 

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by sterkenburgsara** [comment]
@shiragoodman going through this and finding some that I am not completely certain are collab cycle issue tickets (?) but do meet the criteria above ([example here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36359)) - does this one just predate our current template?

**Comment by shiragoodman** [comment]
WOW. I haven't opened a single one yet, but based on the ticket numbers, I am assuming these were the BAH ones we created by accident. I will take a look today and get back to you ASAP.

**Comment by shiragoodman** [comment]
@sterkenburgsara I have reviewed all of these tickets and determined that NONE of them are valid Staging Review issues tickets and in need of the CC-Dashboard label. We're good!

BTW were there any tickets with the CC-Dashboard label that were missing a CCIssue label?

**Comment by sterkenburgsara** [comment]
@shiragoodman sounds good. No, there were no tickets with the CC-Dashboard label that were missing a CCIssue* label. I will go ahead and close.
