### ISSUE TITLE
Discovery for Claims Integration

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#5484]
### User Story
As a developer I want any relevant or existing documentation about Claims so that I can use it going forward

### Tasks
- [x] Identify contact person for Claims
- [x] Identify relevant Claims documentation 
- [x] Identify any existing code 

### Acceptance Criteria
- [x] Documentation saved in Github
- [x] Code saved or link accessible in Github

**Comment by bshyong** [comment]
Contact is Tim Carrico for Claims API
