### ISSUE TITLE
Test Claims Integration

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#5485]
### User Story
When a 530 claim is submitted on VA.gov then a claim is created using BIP Claims API

### Tasks
- [ ] Test Claims API in lower environments
- [ ] Test Claims API in production

### Acceptance Criteria
- [ ] Claim is established
