### ISSUE TITLE
Discovery for BPD Integration

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#5486]
### User Story
As a developer I want any relevant or existing documentation about BPD so that I can use it going forward

### Tasks
- [x] Identify contact person for BPD
- [x] Identify relevant BPD documentation 
- [ ] Identify any existing code that we can leverage
- [x] List attributes needed to send
- [ ] Document code design
- [ ] Estimate coding

### Acceptance Criteria
- [ ] Documentation saved in Github
- [ ] Code saved or link accessible in Github

**Comment by srmyers17** [comment]
From Kennedy: Matt Price is the tech lead, Allison Doster is the analyst, Phylesha Bullard is the scrum master
