### ISSUE TITLE
[FE/BE] Direct deposit EVSS > Lighthouse migration: QA -- figure out how to locally test outlier use cases (fraud related)

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#54879]
## Background 

Related to #54870

There are three outlier use cases for direct deposit QA that can only be tested locally, if at all. They are:

1. LOA3 User: User's account has been flagged for fraud. User tries to update their comp & pen information, but gets an error that they can not save because their account has been flagged for fraud.
2. LOA3 User: User tries to update their compensation and pension direct deposit information, but they don't have a valid home phone, work phone, and mailing address in profile. The user should get an error when trying to update their information.
3. LOA3 User: The backend is down, and we were not able to retrieve the user's direct deposit for comp & pen data.

I am trying to determine if we can test these locally, and, if so, how to direct the team on how to do this.

## Tasks

- [x] Determine if these use cases can be tested locally
- [ ] If so, outline steps for how people can do that so we can add it to the [QA spreadsheet](https://docs.google.com/spreadsheets/d/12gvlkGnwt206BBYY89gDIYG1AtD6j9uCYMr5x99Nzns/edit#gid=0)

## Acceptance criteria

- [ ] We've determined which tasks we can/can not test locally, and outlined steps for how to do so

**Comment by Samara-Strauss** [comment]
> Once the new endpoint is ready to integrate within staging, then I think we can expand on these mock data files and provide a more concrete procedure on testing between the two integrations.

Thank you! If I am not here by the time this is ready, can you please [populate this information into the QA spreadsheet](https://docs.google.com/spreadsheets/d/12gvlkGnwt206BBYY89gDIYG1AtD6j9uCYMr5x99Nzns/edit#gid=0)?

**Comment by adamwhitlock1** [comment]
I think this ticket might be best moved back into the ready column and worked on once the FE ticket for creating the necessary 'compatibility layer' is done.

Ticket for reference:

**Comment by BerniXiongA6** [comment]
Hey @adamwhitlock1 -- though the ticket itself is not blocked, I did add a dependency on this ticket so that we knew it would need to wait for #56569 before starting this work. Thanks for the heads up! cc: @mtcA6

**Comment by adamwhitlock1** [comment]
Now that we have the complete list of error codes I have started a branch to add these codes for the ones checked within our UI, but will probably need to continue this ticket into next sprint for a day or two to get it all documented.

I have some additional error codes that we don't track on the current 'legacy' ppiu api endpoint that I'm not exactly sure how we should handle, or if we should even handle them at all depending. The new error codes are:

- cnp.payment.api.rate.limit.exceeded
- cnp.payment.account.number.invalid
- cnp.payment.account.type.invalid
- cnp.payment.invalid.authentication.creds
- cnp.payment.invalid.token
- cnp.payment.invalid.scopes
- cnp.payment.icn.not.found
- cnp.payment.icn.invalid

Some of these seem more internal in nature, and they could be reported to sentry, but probably wouldn't result in a different error message other than the generic message _if_ they ever actually happened.

Regardless we should probably go through them and decide if any of these warrant any different user facing error messages.

**Comment by tpharrison** [comment]
@adamwhitlock1 Let me know when you want to review the error codes.

**Comment by mtcA6** [comment]
smush this work into #54896
