### ISSUE TITLE
PM | Direct deposit EVSS > Lighthouse migration: QA prep & planning

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#54870]
## Background

For the direct deposit for compensation & pension EVSS > Lighthouse migration, the team needs to run a thorough QA in staging to make sure that the build is working as expected.

## Tasks

- [x] ~~[Outline test cases, staging users, steps to reproduce in QA spreadsheet](https://docs.google.com/spreadsheets/d/12gvlkGnwt206BBYY89gDIYG1AtD6j9uCYMr5x99Nzns/edit#gid=0)~~
     - [x] [revised spreadsheet ](https://docs.google.com/spreadsheets/d/1xflLNJhUSVslzLbVQtMkYkzsBGAhIccnmYW0GL_Ihd0/edit#gid=0) (used [this spreadsheet ](https://docs.google.com/spreadsheets/d/1XwksfemOePs2KY2RbbbzIzbCeAxxhzXssOzWJ8KHdWo/edit#gid=0)as an example check in here to see how the MyVA team has run the QA process)
- [x] Share the spreadsheet with the team
- [x] Get team to review list of use cases and confirm nothing is missing
- [x] #54879
- [x] #54896
- [x] Assign team members to each use case for testing

## Acceptance criteria

- [x] The QA spreadsheet is fully ready for QA -- all test cases, users, and steps to reproduce are defined, and each OS/device/browser is assigned to a team member.

**Comment by Samara-Strauss** [comment]
@BerniXiongA6 @andaleliz @fmccaf1 @adamwhitlock1 @tpharrison 

When you all have a moment (can be next sprint), can you please [review the test cases in the direct deposit for comp & pen spreadsheet](https://docs.google.com/spreadsheets/d/12gvlkGnwt206BBYY89gDIYG1AtD6j9uCYMr5x99Nzns/edit#gid=0) and let me know if anything sticks out as missing? Once the test cases look like they are in good shape, I'll create tabs for OS/browsers/devices we'll be testing.

**Comment by andaleliz** [comment]
@Samara-Strauss I have reviewed the test cases, and assuming this should not impact edu DD in any way -  nothing sticks out to me as missing.

**Comment by Samara-Strauss** [comment]
Thank you! And you are correct -- the EVSS > Lighthouse migration is for comp & pen only. Edu was not touched at all as part of this.

**Comment by BerniXiongA6** [comment]
Sorry I forgot to comment here last week @Samara-Strauss -- I also reviewed the spreadsheet and all test cases looked good to me too. As we hear back from everyone else on their feedback, let me know if I can help you in any way as we need to populate more tabs for the systems/browsers/devices we'll be testing -- happy to assist!

**Comment by Samara-Strauss** [comment]
Great, thank you!

**Comment by Samara-Strauss** [comment]
Thanks for checking in, @BerniXiongA6! Tom and Adam need to complete #54879, and then I can copy/paste the test cases into individual tabs based on device/browser. We'll be ready to close out after that.

**Comment by BerniXiongA6** [comment]
FYI I'm only assigning @tpharrison and @adamwhitlock1 so that it's easier to locate the QA spreadsheet that Samara had put together before she went on leave. Travis and I will own this ticket, but Tom and Adam feel free to update the spreadsheet once you feel pretty good about the test use-cases. We can plan to run QA in Sprint 10 or beyond once FE/BE feels ready for the whole team. Thanks! P.S. will carry this over to Spring 9.

**Comment by mtcA6** [comment]
@ajakabcin leaning on you for some guidance/insight, Samara said "Once the test cases look like they are in good shape, I'll create tabs for OS/browsers/devices we'll be testing." Do you have an example ticket you can recommend I look at for prior testing that's been done? curious to know which browsers/devices/OS we have to account for here.

**Comment by ajakabcin** [comment]
hey @mtcA6 I'll share the doc we used most recently! Also, I'm going to link you to some resources on the platform site re QA standards: [browser support](https://depo-platform-documentation.scrollhelp.site/developer-docs/browser-support-policy), [tools and resources for QA testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/tools-and-resources-for-qa-testing). These talk a fair amount about using Testrail (though not required) - if you're familiar with that tool I'd say give it a whirl, if not, no biggie either. I'm not/was not at all, so we just did it manually in a spreadsheet 🙃.

**Comment by ajakabcin** [comment]
@mtcA6 some more QA things for you:

- [My VA audit ux improvements: QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/2022-audit/QA)
- [My VA audit ux improvements: test cases](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myvaaudit.md)
- [My VA audit ux improvements (a11y version)](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myvaaudit-a11y.md)
- Collaboration cycle ticket (a lot of the QA artifacts linked above and results from QA are needed for Staging review - you can see them linked in the Staging Review toggle section)

**Comment by mtcA6** [comment]
@ajakabcin thanks!!! I have the VA's QA training scheduled for next month but I think it will be too late in the month.

**Comment by ajakabcin** [comment]
@mtcA6 Happy to help bridge the gap in whatever you need!
