### ISSUE TITLE
Access for BPD Integration

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#5487]
### User Story
As a developer I want access to BPD so that I can integrate it with the other services

### Tasks
- [x] Identify BPD access owner
- [x] Determine BPD access process + share with relevant team members 
- [ ] Request access for team

### Acceptance Criteria
- [ ] Ticket for access has been submitted

**Comment by srmyers17** [comment]
Access could be from Karl, Kennedy, Clayton or Tim Carrico

**Comment by srmyers17** [comment]
The VFS Burial Benefits Structured Data team is developing a way to create structured data from 530 forms that are submitted on VA.gov. In order to store the claims data, we need access to the BDP API. We will also be sending a claim ID and associated eFolder reference to the BDP API. This will allow other services, such as the ones being developed by the pension automation team, to use the data to determine eligibility for benefits.

**Comment by srmyers17** [comment]
lower envt owner is Matt Price

**Comment by jjulian** [comment]
Access will be granted by a simple request to them on slack, we will request when we are ready.
