### ISSUE TITLE
[BE] Direct deposit EVSS > Lighthouse migration: Look into/account for fraud use case

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#54887]
## Background

In the rare event that someone's direct deposit information appears to be compromised, the Salt Lake City fraud team flags their information, which prevents updates to their direct deposit information until the flag is lifted. We need to account for this in our migration from EVSS > Lighthouse.

[More on this use case in our documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/use-cases/flag-fraud.md)

## Tasks

- [ ]  Familiarize yourself with the use case
- [ ] Investigate how we are currently handling this in our code
- [ ] Talk to Lighthouse about accounting for it in the code -- are they handling this? 
- [ ] If needed, reach out to the SLC fraud team with questions
- [ ] Make whatever updates to our BE build that are needed to account for this issue

Acceptance
- [ ] This use case is accounted for in our code and is ready to be QA'd by our team
