### ISSUE TITLE
[BE] Direct deposit EVSS > Lighthouse migration: Look into/account for outlier contact information/direct deposit dependency

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#54883]
## Background

Because of how direct deposit was set up in eBenefits, there is a weird dependency for updating direct deposit that requires people have updated their contact information. We've talked to Lighthouse about removing this dependency, but I believe the most downstream backend system (FAS, I think) has this dependency, meaning Lighthouse can not remove it easily, and we need to account for it.

[More on this use case in our documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/use-cases/validation-address-phone.md)

## Tasks

- [x] Familiarize yourself with the use case
- [x] Investigate how we are currently handling this in our code
- [x] Talk to Lighthouse about accounting for it in the code -- are they handling this? 
- [x] Make whatever updates to our BE build that are needed to account for this issue

## Acceptance

- [ ] This use case is accounted for in our code and is ready to be QA'd by our team
