### ISSUE TITLE
Access for BPD Integration

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#5488]
### User Story
As a developer I want access to BPD so that I can integrate it with the other services

### Tasks
- [ ] Identify BPD access owner
- [ ] Determine BPD access process + share with relevant team members 
- [ ] Request access for team

### Acceptance Criteria
- [ ] Ticket for access has been submitted

**Comment by jjulian** [comment]
Obviated by #5976
