### ISSUE TITLE
Test BPD Integration

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#5489]
### User Story
When a 530 claim is submitted on VA.gov then the structured data is sent to BPD

### Tasks
- [ ] Test BPD in lower environments
- [ ] Test BPD in production

### Acceptance Criteria
- [ ] Structured data properly uploaded to BPD
