### ISSUE TITLE
Travel Complete Page Updates

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#54909]
## Tasks

Note: Each completion page variation in the [user flow (mural)](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677531124203/5edcfd3ea4b1eaf1ef082d56782a8b3291ef3932?sender=u37bb983bd3fc3cc00c7d3286) has the correct corresponding wireframe. 

- [ ] All variations of the /complete page should have different content in the Need Help section. [Here is an example of that content](https://share.goabstract.com/6b69924f-904b-4d78-b5a1-4c40ed65e4d2?collectionLayerId=fda84b41-9434-41b6-a2c4-7b6007737eb3&mode=design&sha=e9082325a21d0a7bc8a2415a58586715bd396381). Keep this behind the travel feature flag.

https://www.va.gov/HEALTHBENEFITS/vtp/beneficiary_travel_pocs.asp is the link for "Find the travel contact for your facility"

- [ ] The "We'll come get you from the waiting room..." content should be presented in the information alert, below the appointment information. [Here is that wireframe](https://share.goabstract.com/5cdc7c4a-53ea-4456-b4bc-1029fa03b055?collectionLayerId=1c303a2f-23f3-4efd-bf66-3b21245e5a5c&mode=design&sha=latest). 

- [ ] The new happy path wireframe with the texting solution (checked in successfully + they answered "Yes" to all travel reimbursement questions") is located [here](https://share.goabstract.com/d4065aa6-8234-497c-9b46-b73b9afdd659?collectionLayerId=04958c75-5ff6-4768-8019-73d33d27f2c7&mode=design&sha=latest).

**Comment by brianseek** [comment]
blocking this until we have a chance to talk about all the asks here.

**Comment by brianseek** [comment]
@benbrasso-agile6 this is ready to validate on stage. The footer (need help) work was already in place but had been broke by the active appointment in the URL stuff. I made a fix for it and added an additional e2e test for that. This will show back up for patients since the original work was not behind the travel feature.
