### ISSUE TITLE
Close research study in VA research repo

### ISSUE THREAD

**Issue by tygindraux** [department-of-veterans-affairs/va.gov-team#54927]
### Problem statement
Veterans need to make migrate their DS Logon accounts to Login.gov through grandfathering, which allows them to defer identity proofing.

### Initiative
After we share out the research we need to close the study by following the [VA Platform Research Checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist#ResearchChecklist-2.Researchreview).

### Timeline
March 8 - Submit prototype for Midpoint Review
March 8 - Submit artifacts for Research Review
March 9 - Ready documentation is ready (feedback incorporated)
March 17 - Prototypes are ready (feedback incorporated)
March 20 - Pilot session at 12:00pm EST
March 27 to April 6 - Research sessions
April 10 to 12 - Analysis
April 13 to 19 - Share findings

### Acceptance criteria
- [x] Research study is closed

### Tasks
- [x] @tygindraux review [guidelines for what to do when research is complete](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/70)
- [ ] if applicable, review [how to contribute to the design system](https://design.va.gov/about/contributing-to-the-design-system/)
