### ISSUE TITLE
Prepare team for research sessions

### ISSUE THREAD

**Issue by tygindraux** [department-of-veterans-affairs/va.gov-team#54926]
### Problem statement
Veterans need to make migrate their DS Logon accounts to Login.gov through grandfathering, which allows them to defer identity proofing.

### Initiative
While Perigean starts scheduling sessions, we need to prepare for conducting research. This involves supporting Perigean, assigning notetakers and observers, preparing guidance for notetakers and observers, preparing for documentation (where we store notes, transcripts, etc.) and preparing to moderate.

We'll following the [VA Platform Research Checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist#ResearchChecklist-2.Researchreview).

### Timeline
March 8 - Submit prototype for Midpoint Review
March 8 - Submit artifacts for Research Review
March 9 - Ready documentation is ready (feedback incorporated)
March 17 - Prototypes are ready (feedback incorporated)
March 20 - Pilot session at 12:00pm EST
March 27 to April 6 - Research sessions
April 10 to 12 - Analysis
April 13 to 19 - Share findings

### Acceptance criteria
- [x] Team is prepared to do research, including moderator(s), notetakers and observers

### Tasks
- [x] @tygindraux create schedule and confirm with team
- [x] @tygindraux invite notetakers/moderators to their assigned sessions in the cal
- [x] @tygindraux create a “session-notes” folder within research study in Github
- [x] @tygindraux schedule practice session for @MOStudioCarolyn
- [x] @tygindraux review prototype links and confirm they work correctly
- [x] @tygindraux create [guidance for moderators](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/research/Guidelines/Guide%20to%20moderating.md)
- [x] @tygindraux create [guidance for notetakers](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/research/Guidelines/Guide%20to%20notetaking.md)
- [x] @tygindraux create [guidance for observers](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/research/Guidelines/Guide%20for%20observing.md)
- [x] @tygindraux share guidance with everyone
- [x] @tygindraux invite observers to their assigned sessions in the cal

### Materials for research sessions
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/research/2023-02-Grandfathering-Migration-Round-1-Usability/research%20plan.md)
- [Conversation guide #1 Modal after sign in](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/research/2023-02-Grandfathering-Migration-Round-1-Usability/conversation%20guide%20%231.md)
- [Conversation guide #2 Email ask to sign in](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/research/2023-02-Grandfathering-Migration-Round-1-Usability/conversation%20guide%20%232.md)
- [Prototype #1 Modal after sign in](https://www.figma.com/proto/8vobVoSl1UqLnXsni3rcvO/Login.gov-Adoption%3A-Design-Flows?node-id=41-1311&scaling=contain&page-id=0%3A1&starting-point-node-id=41%3A1311)
- [Prototype #2 Email ask to sign in](https://www.figma.com/proto/8vobVoSl1UqLnXsni3rcvO/Login.gov-Migration%3A-Grandfathering-IAL1-Flow?node-id=402%3A2918&scaling=min-zoom&page-id=241%3A1368&starting-point-node-id=402%3A2918)
---
- [Tech set up checklist](https://depo-platform-documentation.scrollhelp.site/research-design/tech-set-up-checklist)
- [Troubleshooting research sessions](https://depo-platform-documentation.scrollhelp.site/research-design/troubleshooting-for-va-gov-research-sessions-in-pr)
- [Tips on moderating](https://depo-platform-documentation.scrollhelp.site/research-design/Conducting-Research-Sessions.1958773061.html#ConductingResearchSessions-Moderatingtips)
- [Responding to emergencies](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Safety-and-Emergency-Exit-Strategies.2143649793.html)
