### ISSUE TITLE
Validation Issue - Pull a report of 526 error types and # of errors in the last 6 months

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#54950]
## Issue Description
Some applications for benefit claims submitted via form 526ez error out due to various issues: The application has had some defects fixed in the past so the full report of 5 plus years does not give the most accurate picture of issues impacting the claim submissions currently.

This ticket is to get a refresh of the report of all errors by type in the last 6 months.

The purpose of this report is to understand what errors have the highest and current occurence and therefore, should be prioritized for remediation.

---
## Need to Know
- Initial discovery ticket[ #54286](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/54286)
---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ]A report listing error types and how many errors have occurred for each type in the last 6 months
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
cc @colevoss @navaeddie @ahay-agile6 @sethdarragile6

**Comment by navaeddie** [comment]
**In the past 6 months there were 565 Failed 526 Submissions**
Of those failed submissions, there were 1282 errors and warnings (More than one error/warning was attached to each submission). They consisted of 853 Errors and 422 Warnings. Errors cause the submission to fail - warnings do not.

The most common errors, by order of occurrence are:
1. "form526.disabilities[].ratedDisability.isInvalid"
    - amount: 751
    - text: "The rated disability being claimed for increase was not found for Disability"
1. "form526.serviceInformation.separationLocationCode.isInvalidValue"
    - amount: 30
    - text: "The separation location code for the claimant is not a valid value"
1. "form526.serviceInformation.reservesNationalGuardService.title10Activation.anticipatedSeparationDate.Future"
    - amount: 28
    - text: "title10Activation.anticipatedSeparationDate.Future"
1. "form526.disabilities.Size"
    - amount: 14
    - text: "size must be between 1 and 150"
1. "form526.veteran.homelessness.currentlyHomeless.otherLivingSituation.Size"
    - amount: 11
    - text: "size must be between 1 and 500"
1. "form526.serviceInformation.reservesNationalGuardService.title10Activation.anticipatedSeparationDate.IsNotValid"
    - amount: 7
    - text, a few examples: "Invalid value: 2023-02-29", "Invalid value: 2013-06-31", "Invalid value: 2005-02-29"
1. "form526.directDeposit.accountNumber.Size"
    - amount: 6
    - text: "size must be between 4 and 17"
1. "form526.disabilities[].serviceRelevance.Size"
    - amount: 2
    - text: "size must be between 1 and 500"
1. "form526.serviceInformation.ActiveDutyEndDateMoreThan180Days"
    - amount: 1
    - text: "Service members cannot submit a claim until they are within 180 days of their separation date"
1. "form526.serviceInformation.servicePeriods[].activeDutyBeginDate"
    - amount: 1
    - text: "The active duty start date cannot be prior to the claimants 13th birthday"
1. "form526.serviceInformation.Title10PastActiveDutyDate"
    - amount: 1
    - text: "The Title 10 Activation Date for a claimant currently activated in the Reserves or National Guard is a future date"
1. "form526.disabilities.classificationCode.refdataservice.errorResponse"
    - amount: 1
    - text: "The Reference Data Service was unable to verify the classification code for the disability returned an error response"


_Warnings are not causing claims to fail, but perhaps still reveal insights on friction that users are facing in the form so I pulled data on "Warn" messages as well:_
1. "form526.treatments[0].endDateIsNull"
    - amount: 255
    - text: "Treatment end date is null"
1. "form526.directDeposit.isNull"
    - amount: 146
    - text: "Direct deposit information was not provided"
1. "form526.treatments[0].startDateIsNull"
    - amount: 14
    - text: "Treatment start date is null"
1. "form526.disabilities[7].isDuplicate"
    - amount: 7
    - text: "Claimant has added a duplicate disability"

**Comment by navaeddie** [comment]
Note Kyle Sosskin provided further context on one such error in a Slack thread:
https://dsva.slack.com/archives/C04KW0B46N5/p1680098885816749

> The one that looks like it occurs most frequently
> "form526.disabilities[].ratedDisability.isInvalid"
> amount: 751
> text: "The rated disability being claimed for increase was not found for Disability"
> Deals with cases where the veteran starts a claim for increase (or a claim that includes a claim for increase).
> This issue happens because we query and store the result, of the veterans rated disabilities, and then never re-check or requery that before submitting, This CURRENTLY causes an error in auto-establishment submission AND the backup paper submission. HOWEVER soon (in a few sprints) this will not cause an error in the backup paper submission path.
> Example situation that causes this error:
> 01/20/2023 - Vet starts filing 526 claims
> 01/20/2023 - During that filling out of the form, we query for rated disabilities for them to select, they select "Leg Pain"
> 01/20/2023 - We save the in-progress form for the vet so they can come back later to fill it out if they dont go the whole way to submission in this session, including the rated disability, "Leg Pain"
> 01/20/2023 - Vet abandons form half way
> 06/01/2023 - Vet comes back to complete the form, previously saved in-progress values populate so they can pickup where they left-off
> 06/01/2023 - Vet completes form and presses "Submit", the value for the rated disabilty string is "Leg Pain", however, in the time from when they started (01/20/2023), to now (06/01/2023), their rated disability was changed from "Leg Pain" to "Lower Leg Pain",  IN THE VA's system, so it gives that error (edited) 
>

**Comment by navaeddie** [comment]
Documenting this research in Github: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/black_hole_form_validation_research.md
