### ISSUE TITLE
[Design] Notification preferences: Work with content to come up with group and item names for the new "QuickSubmit" claims letter preference

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#54973]
## Background

We have a new notification preference that will be sent to VA.gov via VA Profile. We need content/IA to help us figure out the following:

- The item name for this preference (ie. What should the preference be called)?
- What group (ie. category) should the preference go in?

### Item name

**Note: Samara has some outstanding questions about this notification that are awaiting stakeholder response**

This is a notification that lets people know there is a new claim letter available for them to view in a tool called "QuickSubmit", which, I believe, allows veterans to upload information to their claim after submitting the initial application. I don't think the tool itself is important, but worth noting this is different than the claim status tool on VA.gov.

### Group name

Previously, we'd had a group called "Applications, claims, decision reviews, and appeals", but we changed that because there were only appeals notifications that we supported at the time (that group is now "Board of Veteran's Appeals").

Our current groups:

- Your health care
- Board of Veteran's Appeals
- Payments

I think it's safe to assume that we need a new group. Should it be called "Claims?" Something else?

## Tasks

- [ ] Go to content office hours, and work with Danielle or other content folks to determine item name for this notification preference
- [ ] Go to content office hours, and work with Danielle or other content folks to determine group name for this notification preference
- [ ] Share back to Samara, so I can get this to VA Profile ASAP (note: if Samara is out, email this info to Michael.Richard2@va.gov)

**Comment by Samara-Strauss** [comment]
Actually closing this ticket. In a meeting just now with VA Profile, VANotify, and QuickSubmit, we will not be adding any QuickSubmit preferences to VA.gov. Those preferences will be surfaced only in the QuickSubmit application.
