### ISSUE TITLE
Research how to send correct deployment ID to ArgoCD

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#54978]
# Description
We need to understand which deployment object we should be attaching the status of a preview environment to.

# Tasks
- [x] Figure out why so many deployments are created for feature branches
- [x] Figure out how we can determine which deployment ID we should forward through the workflows to ArgoCD
- [x] Figure out how to pass the deployment ID through the GHA workflows into the `values` file for a given preview environment

# Acceptance Criteria
- [x] We understand how to determine the deployment ID to submit to the `values` file that defines a preview environment
- [x] We know how to use that deployment ID to update the deployment status for a PR with a URL to the instance

**Comment by pjhill** [comment]
Thanks for extending this document and developing our understanding of how to use deployments in GH.
