### ISSUE TITLE
UAT Research Plan for Direct Deposit EVSS > Lighthouse migration

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#54999]
## Background
As part of the Direct Deposit EVSS > Lighthouse migration, we need to prepare for User Acceptance Testing (UAT).

[Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/evss-lighthouse-migration/UAT/research-plan.md)

## Tasks
- [x] Find/create appropriate folder in github: va.gov-team/products/identity-personalization/profile/evss-migration/?
- [x] Review test cases and let Samara know if anything sticks out as missing
- [x] Create UAT research plan

## Validation
- [x] Send links to team to let them review asynchronously
- [x] Have another designer review research plan

**Comment by fmccaf1** [comment]
Thanks @andaleliz. I just updated the research plan with 2 screener questions, one for level of verification, and the other for login method used, so the plan is ready for your review whenever (plenty of time to review this, by end of day Friday would be great). TY!

**Comment by andaleliz** [comment]
Hey @fmccaf1, thanks for asking for my input. Below are my thoughts - lmk if you want to talk through anything

- Typically for UAT we do 5-6 total sessions. I know we've got a variety of use cases to account for here, but not sure we need to do 5 for each of the 3 bullets in your doc. If you feel strongly about that, go for it, but I think we'd be OK if we can confirm with 3 people each
- I like what you're doing with the User A, B, C approach. You might want to consider putting that at the beginning of your bulleted list where you first introduce the concept, so it's super clear vs nested in a parentheses. 
- In the "Eligibility for direct deposit screener question", if a person checks the first 2 boxes, what user type does that qualify them as?

>If participant answers only DS Logon or MyHealtheVet, they are disqualified.

What if they answer "none of the above"?

Lastly, I'm not sure if you'll be using a feature toggle to test this with people, but if so, you'll need to make sure Perigean gives you their email address so they can be whitelisted for the feature.

**Comment by Samara-Strauss** [comment]
I would say that the only thing we can reliably recruit for is people who receive payments from VA. This is because Perigean is only going to be able to reliably recruit people who fall into the much broader category of having a disability rating (meaning that person receives some type of payment from VA as a result). They won't be able to differentiate between people who have set up electronic payments or not, but since most people have set up direct deposit, that's the use case we are likely to see.

As for people who are not eligible for direct deposit, our team can validate that state in our own production accounts.

**Comment by fmccaf1** [comment]
Thanks @Samara-Strauss, I did write a screener question to ask potential participants if they receive benefit funds as a check in the mail or as a direct deposit into their bank account. So, we _could_ try to recruit participant who are eligible but have not yet set up the Direct Deposit section of Profile. For now, I'll plan to remove that question and look to _only_ recruit participants that have direct deposit currently set up, so we'll be planning to validate only [rows 9-14 of the test cases spreadsheet.](https://docs.google.com/spreadsheets/d/12gvlkGnwt206BBYY89gDIYG1AtD6j9uCYMr5x99Nzns/edit#gid=0) If I should change course on that just let me know.

**Comment by Samara-Strauss** [comment]
That sounds great, @fmccaf1! And we can validate cases in rows 3, 4, and 7 with our own production accounts. We can also see if a veteran on the team has an MHV or DS Logon credential and could check that the gate is working for us to validate row 6 (no need to schedule a call -- they can just let us know what they do or do not see).

**Comment by fmccaf1** [comment]
Great, thanks for all your help @Samara-Strauss. I removed any screening questions about how participants receive funds from the VA, and I'll move this ticket back over to Validate for your review whenever you have time.

**Comment by fmccaf1** [comment]
I actually meant to change that to 30 mins, so thanks for point that out. I'll go in and change that now. Thanks @Samara-Strauss
