### ISSUE TITLE
UAT Conversation Guide for Direct Deposit EVSS > Lighthouse migration 

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#55000]
## Background
As part of the Direct Deposit EVSS > Lighthouse migration, we need to prepare for User Acceptance Testing (UAT).

[Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/evss-lighthouse-migration/UAT/conversation-guide.md)

## Tasks
- [x] Write UAT conversation guide

## Validation
- [x] Send links to team to let them review asynchronously
- [x] Have another designer review research plan

**Comment by fmccaf1** [comment]
@andaleliz this conversation guide is ready for your review whenever you get a chance. By end of day Friday would be lovely!

**Comment by andaleliz** [comment]
Hi @fmccaf1 thanks for asking for my input! I think this looks solid, just a few notes that are mostly from the perspective of "If Florence won the lottery and wasn't able to run a session and I had to step in...":

In the [screen question](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/evss-lighthouse-migration/UAT/conversation-guide.md#screen-questions---3-minutes) section:
- will you end the session if it turns out they don't have ID.me or login.gov for their account? If so you might want to add a note for that on the off chance your back-up needs to facilitate a session.
- for the imaginary back-up person, it might be helpful to list the users from A-C instead of the way you have it now just so it follows how you've laid it out in other areas of the doc

[Task 6,](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/evss-lighthouse-migration/UAT/conversation-guide.md#uat-task-6-switch-to-logingov-or-idme---10-minutes) seems to assume participants will have both and be able to switch, but I don't think that's a requirement for your research plan.  Is this an optional task?
- there are a couple of prompts that say "move to task #" but don't have a number
- the other prompt says "move to task 2 directly below" but it's actually above in this case

For task 7, same comment about having multiple types of logins. I would just make it clear in the guide if it's optional or what to do if otherwise.

**Comment by fmccaf1** [comment]
Thanks so much for this feedback @andaleliz. Can you say more about this quote below? Do you mean to add a note in the screen questions section that just lists out what user A is, what user B is...?

> for the imaginary back-up person, it might be helpful to list the users from A-C instead of the way you have it now just so it follows how you've laid it out in other areas of the doc

**Comment by andaleliz** [comment]
You're welcome! Yes, I was just thinking something like this might be easier to mentally process during a session:

> Okay and then, it looks like you reported that: 
> - **user a:** _thing to say_
> - **user b:** _thing to say_
> - **user c:** _thing to say_

**Comment by Samara-Strauss** [comment]
> I was actually planning to not record these calls at all. I will still give them the option to stop screen-sharing though just to help them be as comfortable as possible. If you think this poses any potential issues, let me know!

Sounds good to me! You're right that we don't need to record them in the first place.

> To answer your final question about UAT task 6: This is actually asking them to switch from login.gov to id.me, or vise versa.

Got it! Thank you for clarifying.

I think this is all great and good to go 😃
