### ISSUE TITLE
EPIC | BE | Auth Experience | Telemetry & Monitoring | Datadog

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#55009]
## Background
The Authenticated Experience team would like to use Datadog to monitor issues and setup alerts for high-severity errors and latency issues, so that we can resolve them more quickly.

The team was granted read-only access.  Datadog currently has pre-configured dashboards and health and performance metrics available, but most of these are at the infrastructure-level and not specific to Profile or My VA endpoints.

| Ticket                           | Description                                                                                                                                              | Points |
| -------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------- | ------ |
| ~Request write access to Datadog~  | ~Write access to Datadog is needed In order to create monitors and alerts that are specific to the endpoints that will support the Auth Experience pages.~ | ~2~      |
| Discovery Auth Experience Dashboard    | Do we have a combined one, do we have 3 dashboards, or two My VA and Profile.                                                        | 5      |
| Build Auth Experience Dashboard(s)    | A centralized dashboard to consolidate health and performance metrics related to Auth Experience.                                                        | 5      |
| Add Profile Latency Alerts       | Move any existing latency alerts for Profile from Grafana to Datadog; create any new alerts where neccessary.                                            | 5      |
| Add My VA Latency Alerts         | Move any existing latency alerts for My VA from Grafana to Datadog; create any new alerts where neccessary.                                              | 3      |
| Add Profile Error Rate Alerts    | Add monitors/alerts for when error rates suddenly increase for Profile endpoints.                                                                        | 5      |
| Add My VA Error Rate Alerts      | Add monitors/alerts for when error rates suddenly increase for My VA endpoints.                                                                          | 3      |
| Add Profile High-Severity Alerts | Add monitors/alerts for high-severity errors related to Profile                                                                                          | 5      |
| Add My VA High-Severity Alerts   | Add monitors/alerts for high-severity errors related to My VA                                                                                            | 3      |

```[tasklist]
### Discovery
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/63642
```

```[tasklist]
### Profile
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/64317
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/64382
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/64385
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/64400
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/64401
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/71338
```

```[tasklist]
### MyVA
- [ ] tbd
```
