### ISSUE TITLE
[FE][TECH DEBT] - Refactor our api initializers and mock data creation for e2e

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#55004]
## Description
Our api initializers and mock data generators have a lot of duplicated code and is overly complex. This ticket is to simplify and refactor those areas of our e2e tests.

## Tasks
- [ ] [FE] re-work initializers
- [ ] [FE] re-work data creation to be simpler and more universal
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] All tests still continue to work as they did before
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
