### ISSUE TITLE
[FSR] Empty and endpoint failure designs

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#55028]
## Issue Description
List of Alert messages we'll need:

- No debt or copay balances
- Debt and copay endpoints fail
- copay endpoint fails
- debt endpoint fails

---
## Tasks
- [ ] _Create one empty alert mockup_
- [ ] _Create three endpoint failure mockups_
- [ ] _Confirm copy and contact information is correct_

## Acceptance Criteria
- [ ] _One empty alert and three endpoint failure mockups are created and attached to this ticket_

**Comment by mgleo** [comment]
Mockups created. Sent to Jill to confirm copy on 03/24/2023.

![Empty State - No Overpayments or Copays.jpg](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/cfc2b02b-0862-455f-837c-490bff237e2b)
![Error State - Overpayments and Copays.jpg](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/be2ae6e3-7b08-4062-8e46-439afcad8d0d)
![Error State - Overpayments.jpg](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/5ae57558-2618-4f8f-8533-fb68af991a0d)
![Error State - Copay.jpg](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/c4508058-4bb2-4436-a8d3-75940939bb2f)

**Comment by denisecoveyduc** [comment]
@mgleo  These look great! I am validating with Jill and will let you know if there are any adjustments needed but I don't see any. 🚀
