### ISSUE TITLE
Add Unit Tests and e2e Tests for "View Dependents"

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#5502]
## Goal
Now that we have the "View Dependents" front end pulling data from the back end, through mock data, we need to add e2e tests for the data coming from the back end as well as unit tests for the logic that acts on the data inside the "View Dependents" components.

## Tasks
- [ ] ensure 80% unit test coverage is achieved for all "View Dependents" components
- [ ] create e2e tests to test API calls

## Acceptance Criteria
- [ ] All necessary e2e tests have been created and have at least 80% coverage.
