### ISSUE TITLE
Third-party `set-output` usage

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#55037]
# Acceptance Criteria
- [x] All actions that can be updated have been updated to avoid use of `set-out`
- [x] Create a new ticket with a list of GitHub Actions that have been abandoned or are no longer maintained that need to be maintained internally or discontinue use

### Summary
`set-output` will be deprecated May 31, 2023: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ 

In https://github.com/department-of-veterans-affairs/va.gov-team/issues/49475, the DevOps CoP removed all instances of `set-output` from devops-related repos within the `department-of-veterans-affairs` org. We still see some errors when we run github actions because of some third-party actions we are using. 

Tim Cosgrove documented these findings:
1. [`aws-actions/configure-aws-credentials@v1`](https://github.com/aws-actions/configure-aws-credentials) - Can be replaced with `@v2`; see https://github.com/aws-actions/configure-aws-credentials/issues/489
2. [`marvinpinto/action-inject-ssm-secrets`](https://github.com/marvinpinto/action-inject-ssm-secrets) - [No apparent updates forthcoming](https://github.com/marvinpinto/actions/issues/543); the maintainer appears to be absent. This is **widely** used: https://github.com/search?q=org%3Adepartment-of-veterans-affairs+action-inject-ssm-secrets&type=code
3. [`slackapi/slack-github-action`](https://github.com/slackapi/slack-github-action) - Fixable by moving to version 1.23.0
4. [`EndBug/add-and-commit`](https://github.com/EndBug/add-and-commit/issues/448#issuecomment-1297742564) - Fixable by moving to `v9`

⚠️ ⚠️ marvinpinto/action-inject-ssm-secrets is the most concerning because of its wide use and apparent lack of update. 

### Tasks
- [ ] Update our versions where we can (1, 3 and 4 above). 
  - [ ] `aws-actions/configure-aws-credentials`
     - [ ] [devops](https://github.com/department-of-veterans-affairs/devops)
- [ ] Figure out what to do about 2!

### Repos

1. <https://github.com/department-of-veterans-affairs/devops>
    -   [X] [PR up](https://github.com/department-of-veterans-affairs/devops/pull/13005)
    -   [x] PR merged
1. <https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests>
    -   [X] [PR up](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1909)
    -   [x] PR merged
1. <https://github.com/department-of-veterans-affairs/vsp-infra-argocd>
    -   [X] [PR up](https://github.com/department-of-veterans-affairs/vsp-infra-argocd/pull/203)
    -   [x] PR merged
1. <https://github.com/department-of-veterans-affairs/va.gov-team-sensitive>
    -   NA
1. <https://github.com/department-of-veterans-affairs/vsp-infra-clamav>
    -   [X] [PR up](https://github.com/department-of-veterans-affairs/vsp-infra-clamav/pull/59)
    -   [x] PR merged
1. <https://github.com/department-of-veterans-affairs/vsp-infra-clamav-mirror>
    -   NA
1. <https://github.com/department-of-veterans-affairs/vsp-infra-deployer>
    -   NA
1. <https://github.com/department-of-veterans-affairs/vsp-infra-aws-load-balancer-controller>
    -   NA
1. <https://github.com/department-of-veterans-affairs/vsp-infra-fluentd>
    -   NA
1. <https://github.com/department-of-veterans-affairs/vsp-infra-kubernetes-metrics-server>
    -   [X] [PR up](https://github.com/department-of-veterans-affairs/vsp-infra-kubernetes-metrics-server/pull/7)
    -   [x] PR merged
1. <https://github.com/department-of-veterans-affairs/vsp-infra-argo-workflows-server>
    -   [X] [PR up](https://github.com/department-of-veterans-affairs/vsp-infra-argo-workflows-server/pull/4)
    -   [x] PR merged
1. <https://github.com/department-of-veterans-affairs/vsp-infra-argo-rollouts>
    -   [X] [PR up](https://github.com/department-of-veterans-affairs/vsp-infra-argo-rollouts/pull/4)
    -   [x] PR merged
1. <https://github.com/department-of-veterans-affairs/vsp-infra-eks-efs-csi>
    -   [X] [PR up](https://github.com/department-of-veterans-affairs/vsp-infra-eks-efs-csi/pull/2)
    -   [x] PR merged
1. <https://github.com/department-of-veterans-affairs/vsp-infra-loki-canary>
    -   [X] [PR up](https://github.com/department-of-veterans-affairs/vsp-infra-loki-canary/pull/7)
    -   [x] PR merged
1. <https://github.com/department-of-veterans-affairs/vsp-github-actions>
    -   [X] [PR up](https://github.com/department-of-veterans-affairs/vsp-github-actions/pull/22)
    -   [x] PR merged
1. <https://github.com/department-of-veterans-affairs/vsp-infra-k8s-datadog-agent>
    -   [X] [PR up](https://github.com/department-of-veterans-affairs/vsp-infra-k8s-datadog-agent/pull/11)
    -   [x] PR merged
1. <https://github.com/department-of-veterans-affairs/vsp-infra-aws-node-termination-handler>
    -   [X] [PR up](https://github.com/department-of-veterans-affairs/vsp-infra-aws-node-termination-handler/pull/7)
    -   [x] PR merged
1. <https://github.com/department-of-veterans-affairs/vsp-infra-sentry>
    -   [X] [PR up](https://github.com/department-of-veterans-affairs/vsp-infra-sentry/pull/1)
    -   [x] PR merged
1. <https://github.com/department-of-veterans-affairs/vsp-infra-k8s-sorry-cypress>
    -   [x] PR up
        -   [x] missing write access
    -   [x] PR merged
1. <https://github.com/department-of-veterans-affairs/vsp-infra-k8s-datadog-private-location>
    -   [X] [PR up](https://github.com/department-of-veterans-affairs/vsp-infra-k8s-datadog-private-location/pull/12)
    -   [x] PR merged
1. <https://github.com/department-of-veterans-affairs/vsp-infra-k8s-cert-manager>
    -   [X] [PR up](https://github.com/department-of-veterans-affairs/vsp-infra-k8s-cert-manager/pull/3)
    -   [x] PR merged
1. <https://github.com/department-of-veterans-affairs/vsp-infra-kubernetes-autoscaler>
    -   [X] [PR up](https://github.com/department-of-veterans-affairs/vsp-infra-kubernetes-autoscaler/pull/6)
    -   [x] PR merged
1. <https://github.com/department-of-veterans-affairs/vsp-infra-calico>
    -   [X] [PR up](https://github.com/department-of-veterans-affairs/vsp-infra-calico/pull/7)
      -   [x] changes requested: https://github.com/department-of-veterans-affairs/vsp-infra-calico/pull/7#issuecomment-1555013278 
    -   [x] PR merged
1. <https://github.com/department-of-veterans-affairs/content-build/>
    -   [X] [MR up](https://github.com/department-of-veterans-affairs/content-build/pull/1563) **approved**
    -   [x] MR merged
1. <https://github.com/department-of-veterans-affairs/va.gov-team/>
    -   [X] [MR up](https://github.com/department-of-veterans-affairs/va.gov-team/pull/58494) **approved**
    -   [x] MR merged

-   [ ] <https://github.com/department-of-veterans-affairs/terraform-dd-eks-module>
-   [ ] <https://github.com/department-of-veterans-affairs/vanotify-team>
-   [ ] <https://github.com/department-of-veterans-affairs/ec2-github-runner>
-   [ ] <https://github.com/department-of-veterans-affairs/vets-website>
-   [ ] <https://github.com/department-of-veterans-affairs/notification-api>
-   [ ] <https://github.com/department-of-veterans-affairs/smart-on-fhir-infra>
-   [ ] <https://github.com/department-of-veterans-affairs/chip>
-   [ ] <https://github.com/department-of-veterans-affairs/lighthouse-di-secrets-manager>
-   [ ] <https://github.com/department-of-veterans-affairs/example-smart-on-fhir-application>
-   [ ] <https://github.com/department-of-veterans-affairs/cds-hooks-client-api>
-   [ ] <https://github.com/department-of-veterans-affairs/whole-health-api>
-   [ ] <https://github.com/department-of-veterans-affairs/va-virtual-agent>
-   [ ] <https://github.com/department-of-veterans-affairs/pst-amt-keycloak>
-   [ ] <https://github.com/department-of-veterans-affairs/platform-support-slackbot>
-   [ ] <https://github.com/department-of-veterans-affairs/lighthouse-di-service-kiali>
-   [ ] <https://github.com/department-of-veterans-affairs/component-library>
-   [ ] <https://github.com/department-of-veterans-affairs/lighthouse-api-gateway>
-   [ ] <https://github.com/department-of-veterans-affairs/mlds-platform>
-   [ ] <https://github.com/department-of-veterans-affairs/vets-api-mockdata>
-   [ ] <https://github.com/department-of-veterans-affairs/performance-dashboard>
-   [ ] <https://github.com/department-of-veterans-affairs/medication-visualizer>
-   [ ] <https://github.com/department-of-veterans-affairs/MLDS>
-   [ ] <https://github.com/department-of-veterans-affairs/pst-amt-keycloak-react-test-app>
-   [ ] <https://github.com/department-of-veterans-affairs/mlds-base-infra>
-   [ ] <https://github.com/department-of-veterans-affairs/qa-standards-dashboard-data>
-   [ ] <https://github.com/department-of-veterans-affairs/bia-bgs-infrastructure>
-   [ ] <https://github.com/department-of-veterans-affairs/lighthouse-di-service-jaeger>
-   [ ] <https://github.com/department-of-veterans-affairs/smart-on-fhir-container>
-   [ ] <https://github.com/department-of-veterans-affairs/developer-portal>
-   [ ] <https://github.com/department-of-veterans-affairs/octo-vista-api>
-   [ ] <https://github.com/department-of-veterans-affairs/sign-in-service>
-   [ ] <https://github.com/department-of-veterans-affairs/bip-images>
-   [ ] <https://github.com/department-of-veterans-affairs/lighthouse-di-api-teams>
-   [ ] <https://github.com/department-of-veterans-affairs/notification-ui>
-   [ ] <https://github.com/department-of-veterans-affairs/smart-on-fhir-report-wrapper>
-   [ ] <https://github.com/department-of-veterans-affairs/platform-console-ui>
-   [ ] <https://github.com/department-of-veterans-affairs/cdsp-shared-decision-making>
-   [ ] <https://github.com/department-of-veterans-affairs/clinician_workflow>
-   [ ] <https://github.com/department-of-veterans-affairs/vets-api-sidekiq-ui>
-   [ ] <https://github.com/department-of-veterans-affairs/checkin-devops>
-   [ ] <https://github.com/department-of-veterans-affairs/platform-console-api>
-   [ ] <https://github.com/department-of-veterans-affairs/cdsp-my-work-week>
-   [ ] <https://github.com/department-of-veterans-affairs/lorota>
-   [ ] <https://github.com/department-of-veterans-affairs/bip-tenant-intake>
-   [ ] <https://github.com/department-of-veterans-affairs/vets-design-system-documentation>

**Comment by rmtolmach** [comment]
From @timcosgrove in https://dsva.slack.com/archives/C04CYC4LMU6/p1680565555351849?thread_ts=1678195554.705199&cid=C04CYC4LMU6
> So, I wanted to bring up the issue again with marvinpinto/action-inject-ssm-secrets action, which we use extensively: https://github.com/search?q=org%3Adepartment-of-veterans-affairs+action-inject-ssm-secrets&type=code
The issue being, the action uses some syntax and packages that have been deprecated by Github and are set to start failing in May this year; and, the developer is not responding to issues asking after the update.
I went ahead and forked the source repo, updated, and built a release. It seems to be working.
Fork: https://github.com/timcosgrove/aws-secrets-actions
Workflow using the forked action: https://github.com/department-of-veterans-affairs/content-build/actions/runs/4602334205/jobs/8131173408#step:5:1
> So, a thought: what if we forked marvinpinto/action-inject-ssm-secrets to the department-of-veteran-affairs org, and maintained it that way? The original developer is not responding, so I don't think this action is going to be updated at its source.
> I'd be happy to lead that if the CoP decides it's the best course of action for replacing the current action. I went through the steps to do it for my own fork. It's slightly more than trivial but not much

**Comment by pjhill** [comment]
We need to identify which repositories this COP is truly responsible for -- there may be some repositories that FE or BE COPs might be a better fit to own the change.

**Comment by pjhill** [comment]
Should we volunteer / facilitate a discussion about the deprecation and the potential effect to GHA outside of the platform?

**Comment by pjhill** [comment]
Node16 issue described by GitHub here: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by pjhill** [comment]
Tim Cosgrove has forked the repo into DSVA org. Initial draft version of the action repo is available currently. Should be ready to go by next week some time.

**Comment by pjhill** [comment]
Answer the question, do we want to be the maintainers of the forked action going forward? Should we update the community for the original action with the fact that we are going to maintain it going forward within our org?

**Comment by rmtolmach** [comment]
See update in internal docs: https://vfs.atlassian.net/wiki/spaces/DO/pages/2600993119/April+14
But basically, we're waiting for Tim's forked repo to go public and then we can start.

**Comment by timcosgrove** [comment]
Action is available: `department-of-veterans-affairs/action-inject-ssm-secrets@latest`

This is a drop-in substitution for `marvinpinto/action-inject-ssm-secrets`.

**Comment by pjhill** [comment]
Links provided by Tim Cosgrove during discussion:
* https://github.com/department-of-veterans-affairs/va.gov-cms/pull/13669
* https://github.com/department-of-veterans-affairs/content-build/pull/1554

**Comment by pjhill** [comment]
We are targeting Monday 5/22/23 for a merge of the `devops` PR. We will quickly fire off a revert PR just in case we need to back the change out in a timely manner.

**Comment by timcosgrove** [comment]
Just noting here that the ticket as-written seems to indicate there are only 4 actions that need to be checked. This is not the case.

**Every** third-party action is suspect and should be looked at for update. You can scan any and all workflow yaml files in a given repo for this text: `uses:`. This will find you any 'external' actions that need to be examined. 

Note that the majority of these are remote, of the form `aws-actions/configure-aws-credentials@v1`, but some may be actions local to the repo. These 'local' actions also should be checked for any dependent actions that need updating. 

If you look at the current state of content-build's actions, you can find a wide variety of commonly-used actions that have been updated. This might be a good starting point for figuring out what actions need updating. https://github.com/department-of-veterans-affairs/content-build/tree/main/.github/workflows

**Comment by timcosgrove** [comment]
I will need to be granted membership to the vsp-operations team in order to work on most of these, but I am willing to help out if I am granted access.

**Comment by pjhill** [comment]
@Kshitiz-devops --
- [ ] Work with @flooose to compare the output of the script to what we have manually created

**Comment by pjhill** [comment]
@flooose -- Get with Kshistiz and come up with a plan to merge the PRs

**Comment by pjhill** [comment]
* Still working on getting PRs approved
* Some actions contain deprecated usage still
* Let's post a few at a time into the Devops COP slack channel -- https://dsva.slack.com/archives/C04CYC4LMU6

**Comment by pjhill** [comment]
Link to Google sheet with actions that are an issue and which repository is using those actions --
https://docs.google.com/spreadsheets/d/1pWvtREV3Uvf3Q7FJhdymG31u_bo8-C3Gfm2sW5m7dK8/edit?pli=1#gid=0

**Comment by pjhill** [comment]
There's an issue with how secrets are being handled as a part of this effort.  It may be prudent to de-prioritize this effort until a new method for managing secrets from GHA is available for the platform.

**Comment by flooose** [comment]
Issue for abandoned gh-actions is [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62147)
