### ISSUE TITLE
Demo:  Communicate changes made to Survey

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#55032]
## Purpose
The Survey was altered to gather more detailed feedback about various areas of concern around the Platform.  Communicate changes made to Survey.

## Tasks
- [x] draft [deck](https://docs.google.com/presentation/d/18Zeav-CS-oAuVb8TBTwvPA9u00sVb7qcM12Rujpsrk8/edit#slide=id.g148c63603f3_0_1199)
- [x] get feedback and revise
- [x] Communicate changes made to Survey at End of Sprint Demo

## Acceptance Criteria
- [x] Changes demoed
