### ISSUE TITLE
Add workflow for reporting a divorce to new 686 form

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#5504]
## Story
As a Veteran using the 686 in VA.gov, I want to be able to adjust my claim to account for divorce so that I can maintain an accurate representation of my status with the VA.

## Goal
Include the necessary schema workflows and submit PRs for them to be incorporated.  This will fully flesh out the rest of the workflows to coincide with what has already been put out.

## Considerations
- When these are done as multiples, there are merge conflicts that will need to be carefully addressed.
 - [Mockup](https://xd.adobe.com/view/ffffe536-2ba5-47c6-4c4b-ac1679179973-89ce/screen/cf1d4c72-97a0-45af-b9b4-2cfdcc2e7288/Apply-Dependents-Report-Divorce-1A
)
 
## Tasks
- [ ] Add and/or remove the necessary schema at the workflow level and ensure there are no validation errors.

## Acceptance Criteria
- [ ] A PR has been requested and completed for `vets-json`
- [ ] A PR has been requested and completed for `vets-website`
