### ISSUE TITLE
Add links to new VA tool pages on the Download VA letters page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#55062]
## Issue Description

Now that we've launched the [Download your VA education letter](https://www.va.gov/education/download-letters/) tool and the [online housing COE tool](https://www.va.gov/housing-assistance/home-loans/how-to-request-coe/), we need to add links to these on the [Download VA letters](https://www.va.gov/records/download-va-letters/) page in the section with the H2 "What if I want to download a letter or document that isn’t available from this tool?" 

## Tasks
- [ ] Add link to education letters page (Katherine)
- [ ] Add link to online COE tool (Katherine)
- [ ] Review (Laura)
- [ ] Copyedit (Megan)
- [ ] Publish (Megan)

## Acceptance Criteria
- [ ] Changes are live on the site

**Comment by katherine-fung** [comment]
Hi @laurwill, 

This page is ready for your review: 
http://preview-prod.vfs.va.gov/preview?nodeId=471 

I added the links. I also tweaked the sentence leading into the links to say: 

"If you’re eligible for other letters or documents listed here, you can use these links to access them on VA.gov:"

**Comment by laurwill** [comment]
Thanks @katherine-fung !
As I was reviewing this, I remembered that we had planned work to add an entry point to the recently launched decision letter download feature in the claim status tool ([see old ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45908)). Let's pause this until we confirm if that work is moving forward, so we can make all updates at once.

**Comment by laurwill** [comment]
Hi again @katherine-fung ! 
Per chat in grooming today, we'll fix these links before we address the work in that old ticket. 
I made some tweaks to direct all the links to our static pages, rather than a mix of static pages and form intro pages. 
I also fixed a header issue at the top of this page — this will change again when we address the old work, but I think good to fix for now.
Want to take a look and see if you have questions? Then you can pass to Megan. Thank you!

**Comment by laurwill** [comment]
New update! Mikki clarified the future changes that are needed to this page in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45908). So I reverted this page and changed only the links for now, to replace the outdated eBenefits links and add the education letters.

@RLHecht can you confirm that what I did aligns with what we discussed with Beth? Then Megan can copyedit and publish. And then you could open a new ticket to make the changes Mikki suggested. Thank you!

**Comment by megzehn** [comment]
Thanks, @RLHecht! Confirming I reviewed and published these changes.

**Comment by RLHecht** [comment]
These changes are live. Closing ticket.
