### ISSUE TITLE
Update Front End repo cron jobs start times 

### ISSUE THREAD

**Issue by rmessina1010** [department-of-veterans-affairs/va.gov-team#55076]
Update Front End repo cron jobs start times for daylight savings time.

### Task
**Update the following files:**
[vets-website](https://github.com/department-of-veterans-affairs/vets-website/blob/main/.github/workflows/daily-deploy-production.yml#L14)
[content-build  ](https://github.com/department-of-veterans-affairs/content-build/blob/main/.github/workflows/daily-production-release.yml#L6)

From
```
  schedule:
    - cron: 0 20 * * 1-5
```

To
```
  schedule:
    - cron: 0 19 * * 1-5
```

### Definition of Done:

- [x]  Update cron job start time  for vets-website
- [x]  Update cron job start time  for content-build
- [x]  Confirm jobs run at 2pm ET- 
- [x]  Set reminders, with links , for  Fri, Nov 3, 2023 and  Fri, Mar 8, 2024

**Comment by rmessina1010** [comment]
Completed. Closing.
