### ISSUE TITLE
Rework DD214 process on Request military records page 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#55088]
## Issue Description

We need to make changes to the process list and other content on our [Request your military service records (including DD214)](https://www.va.gov/records/get-military-service-records/) so that it's clearer how a Veteran can get their DD214.

We learned that depending on when the Veteran was discharged, their DD214 may not be available in DPRIS. Instead they may need to request their DD214 through the National Personnel Records Center (NPRC)--which they need to access through milConnect. 

**Veterans who were discharged after these dates** can get their records through DPRIS (milConnect):
- Air Force: 10/1/2004
- Army: 10/1/2002
- Marines: 1/1/1999
- Navy: 1/1/1995

**Veterans who were discharged before these dates** must get their records through the NPRC (National Archives).

NPRC = National Personnel Records Center
DPRIS = Defense Personnel Records Information Retrieval System

A Platform member who is also a Veteran and took screenshots of the process for signing in to milConnect and going through the steps to request the form through Defense Personnel Records Information (DPRIS). It's several more steps than what we currently have on our subway map. 

We need to look at the page overall as well as the screenshots provided to determine how best to rework the page to make it clearer for Veterans.

Screenshots for milconnect process:

![milConnect step 1.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/c9d2a0e0-51a9-4fe6-89f0-a4424be7a8a0)

![milConnect step 2.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/4e507683-055d-4449-83da-7cd9725922ab)!

[milConnect step 3.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/cd8576f4-214b-4538-a1a9-2c80e2d74cc3)

![milConnect step 4.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/179248fc-26de-4b4d-8713-03258b768c73)

![milConnect step 5.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/54067129-fbf0-441d-a85c-a4aab32e2b54)

![milConnect step 6.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/f00e0a53-b4dc-4c1b-b38e-bf66be0d8306)

![milConnect step 7.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/573d919c-000e-4647-8021-47b12dcc5f51)

![milConnect step 8.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/1ba6b04b-7365-42fa-9298-1b3e58209ac9)

![milConnect step 9.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/eb4140d5-3f51-48ce-9d1a-0b44bf3b7092)

This is the confirmation page for after you request through milConnect:

![IMG_6891.jpg](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/dfebddb3-e058-491e-821d-dac371bbcf7e)

Screenshots for NARA request for records:

![Nara Step 1.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/c8615c1a-54fb-4fbd-a2ad-fbb8731c41b0)

![Nara Step 2.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/ace31b16-e27b-4e78-a1cb-9b06d56da552)

![Nara Step 3.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/ade6b874-5289-41dc-b7d9-fd91fd606ac0)

![Nara Step 4.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/1dccf0d8-fd65-4798-a921-9d390fed4e7e)

![Nara Step 5.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/e7b28c28-4dcc-49ce-9772-ac60172765e6)

![Nara Step 6.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/ca29eb68-3cad-4b8e-b2dc-2c14ac3c0195)

![Nara Step 7.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/08c298dd-1b6f-4356-8da6-0adb1ad258ec)

![Nara Step 8.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/c353d060-d516-48eb-a5eb-15cf4e28d4e4)

![Nara Step 9.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/f4ad608b-9e1b-4487-be90-eb893dbe94ad)

![Nara Step 10.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/37a5878d-516e-4aca-ada5-e8c35bba7eeb)

![Vetrecs-Notification-Email.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/b81f5f77-36a2-40db-bbf3-55e01d219cf6)

## Tasks
- [x] Assess work (Aliyah)
- [x] Rework content (Aliyah) 
- [x] Email National Archives and milConnect SMEs
- [x] Review (Laura)
- [x] OCTO review (Beth)
- [x] Send to stakeholders
- [x] Copyedit (Megan)
- [x] Publish (Megan)

<details>
<summary>Prepublishing checklist</summary>

### Before you begin
- [ ] Confirm that there are no updates in draft by other content authors that aren't ready to be published. Check the revision log and then confirm with the content author who made the previous edits that the page is ready to publish.

### Accessibility standards

- [ ] If your link or button will take the user off VA.gov, confirm that the text for the link or button contains a purpose and a target. The user should be able to tell from the link or button text what the call to action is (the purpose) and where they will end up if they click on the link (the target). The following link is an example of this: <br>[Read more about making links accessible on AccessibilityOz](https://www.accessibilityoz.com/2014/02/links-and-accessibility/)</br> 
**Note:** When you direct the user to another VA.gov page, the link only needs to contain text indicating purpose (the call to action).
- [ ] Confirm all phone numbers are in aria labels. [Learn how to code numbers with aria labels](https://design.va.gov/content-style-guide/dates-and-numbers#phone-numbers)
- [ ] Confirm that the hierarchy of section and subsection titles is correct (H1 to H2 to H3—levels shouldn't be skipped). [Learn more about section titles](https://design.va.gov/content-style-guide/page-titles-and-section-titles)
- [ ] Replace any sighted language ("view," "see," "look") with a word that's inclusive of our screen reader users ("check," "go to," "review").
- [ ] Avoid using other ability-focused language. ("hear back from")

### Link standards

- [ ] Confirm that links work (aren't broken—no error message) and point to the intended page (you pasted in the correct URL or chose the correct node ID).
- [ ] Confirm all link text is 100 characters or less.
- [ ] Check that you've selected a node ID for all links pointing to VA.gov (internal) pages. Only paste in a URL if the page you're linking to doesn't live in our CMS (isn't one of our modernized pages). [Learn how to add node IDs in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/linking-with-node-ids.md) 
- [ ] Check that all anchor/jump links are pointing to a node followed by # and the header identifier (Example: /node/47278/#information-for-survivors). Double check all anchor/jump links post-publish. 

### CMS standards

- [ ] Make sure all apostrophes and quotation marks are curly not straight. (Once this is automatic in Drupal, we can remove this item.)
- [ ] If there are alerts at the top of the Drupal Edit node for broken links, redirected links, or links to unpublished pages, correct the issues. If there's an alert for a broken link but the link is actually working, report the issue to the CMS help desk. [Read more about link alerts in the CMS knowledge base](https://prod.cms.va.gov/help/cms-basics/how-to-fix-broken-links-and-redirects)
- [ ] If publishing a brand-new page, confirm the left nav and url are set up correclty. (If the page is a child page, the section needs to be the same as the parent page in order for the left nav to show.) [Learn how to set up a url and left nav in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/adding-left-nav-and-url.md)
- [ ] Check if the page has a new or updated alert. If so, publish the alert separately. 

### Additional checks for translated articles
- [ ] If we don't have updated translated versions, add the alert that links to the corresponding English page and lets users know that the translated pages aren't up to date. 

</details>

## Acceptance Criteria
- [ ] Page is live with changes

**Comment by aliyahblackmore** [comment]
**Update here:** Beth and I chatted yesterday (3/24) and I'll continue to draft content for this and will get changes in Drupal.

**Comment by aliyahblackmore** [comment]
**Update here:** I picked this work back up yesterday (4/6) and today. I'll have a full draft to Beth on Monday and I'll get changes in to Drupal, just to have an idea of the page flow. 

So far I have a few additional questions for National Archives and milConnect/DPRIS SMEs. I have those compiled in my word doc. I'll circle back to Beth on Monday for the notes she has from National Archives call.

**Comment by aliyahblackmore** [comment]
Hi @bethpottsVADEPO this is a draft word doc with changes for the Request military records page. I'll set up on meeting for Thursday to chat through this and pull out any additional questions for milConnect and National Archives SMEs. 
[Changes to request military service records_AB_3.21.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11194347/Changes.to.request.military.service.records_AB_3.21.docx)

These are a few of the more general notes/questions.

**Global questions/notes on page:**

1. Note – the [DPRIS milConnect FAQs](https://milconnect.dmdc.osd.mil/milconnect/public/faq/Documentation-DPRIS) has the same cut off dates as this ticket. This is in question “Are my documents available via DPRIS?”
2. Note - this page previously used a subway map/process list for the milConnect request steps. We chatted a bit about potentially removing this all together and I think that we actually should. Based on the [style guide](https://www.va.gov/claim-or-appeal-status/), instructions that don’t require any additional description shouldn’t use a process list. It seems like the instructions for milConnect and the National Archives don’t require any additional steps. Open to thoughts here. I tried out numbers in a list for both sections. [This](https://www.va.gov/claim-or-appeal-status/) is an example of how the process list component could be used – it doesn’t seem like the instructions here fit.
3. Question – for milConnect, does this page need to account for record request online as well as via mail, in person, or fax? Those are options for the National Archives, so just want to confirm. If so, can SMEs confirm if they can or want to receive requests in other ways?
4. Question - We need to confirm with your colleague or SMEs what the page is before someone is in DPRIS. As I call out on the doc, according to [this Iowa national guard website](https://www.iowanationalguard.com/wp-content/uploads/2022/01/How-to-retrieve-documents-from-DPRI.pdf), the user needs to select DPRIS from a drop down on their home page. In the screen captures that we have, it seems like there is a missing step between sign in and getting in to DPRIS. The current step to get to DPRIS on our live page matches info on the Iowa site.
5. The screenshots here include info about multi factor authentication. Is this a step that someone would get each time they sign in or is this only if they need to update this info? I’m not sure that that is a step in the sign in process – I think that for this work, we may want to provide instructions after the user is signed in/on their homepage.
6. Question – For requesting from National Archives - is there an in-person option to request and is there a preference of requesting online over mail or fax?
7. Question – on our current live page we have in person, through local Veterans agency, and through an independent researcher listed as request options. Can we confirm whether this is still a preferred way/way to get records?
8. Question: Is there a preferred entry point to make the request or should someone select the option that be describes what they’re looking for and go through the request that way? I went to the National Archives site and there are actually a few different entry points from this block to start a request. For example, someone can select DD 214/Separation Documents, and they would land on the same eVetsRecs records request screen. 
9. Question: In the service and request details section, the user would need to select a category that best described why they are requesting they records. There is then an info alert type pop up that states the record that the National Archives would provide them with. Should out instructions account for this? It seems like someone can still move forward and section the record type they want (if it’s not the one selected for them), but I’m wondering if we need to frame our content differently if National Archives determined which records they would need.
10. Question – Is there a confirmation button on link that someone needs to select to submit their request? From the screen captures we have, the screens jump from the review and submit screen to confirmation, but we don’t see a submit button anywhere?
11. Note - I'll need to make updates to the section on requesting someone else's records. I have a few questions called out in the document.

**Comment by bethpottsVADEPO** [comment]
Pasting here Danielle's notes from her convo with the National Archives director:

- While it's true that there are dividing dates between whether the National Archives has a Veteran's DD214 on file or not, a Veteran could still request their DD214 through the National Archives after those dates and the Archives staff will get it for them. The Archives hold paper records from earlier eras, but their technicians still have access to the electronic systems for later records. So we don't need to worry about trying to communicate the date cut off.

- Veterans may actually be better served in many cases by having VA get their DD214 for them after they apply for benefits because National Archives works directly with VA to meet requests quickly. So we can provide the path to the [self-service option](https://www.archives.gov/veterans/military-service-records) first, but also add a note about having VA get their records as part of the application process.
- We should encourage Veterans who are applying for benefits to be sure to do 2 things when requesting their records from the National Archives: 1) Select the right reason for why they're requesting their records and 2) Only request their DD214. This will help speed up the process of getting their records. It usually takes about 3 days to get just a DD214 for a benefit application.
- The director is happy to be a SME and review the content for us when ready. So just let me know when it's ready and I can facilitate that.
- Caveat to the first point in previous slack: As I was exploring the self-service option after my call, I got this message when I chose "current service member."

![image](https://user-images.githubusercontent.com/66026798/231225451-1be27771-90fe-45af-aa1c-00c6ab246d5f.png)

- This matches the date for the dividing line for Marines of 1/1/1999 and introduces the Coast Guard (which I don't believe was on our original list of dividing dates), but it doesn't reference dividing dates for Air Force, Army, or Navy (though contact info for those branches is included after the "Get addresses" link).
- I'm going to send the director a follow-up question about this and will send info when I have it.

**Comment by aliyahblackmore** [comment]
**Update here:**

Waiting to get a few questions answered from National Archives. For now, we're pausing on this work.

**Comment by RLHecht** [comment]
Moving to blocked until we hear back from National Archives.

**Comment by aliyahblackmore** [comment]
Just circling back here following yesterday's backlog meeting and after looking at other content items on my list.

There are a few other priorities that I have on my list for next week. I'm going to move this out to the next sprint and will come back to this if I have time before I'm OOO (July 27 - Aug 9). 

cc: @coforma-terry and @bethpottsVADEPO 

Danielle provided updated notes on 6/23 - I'll refer to those when I am working on this.

**Comment by aliyahblackmore** [comment]
**Update here:** 

As I mentioned in our weekly content sync with Beth (7/20), I'm prioritizing some other form and identity work before OOO time (7/27 to 8/9). I checked in during this meeting just to update my notes on direction based on the notes that Danielle shared from the National Archives. 

- We agreed that we'll continue to move page content in the direction of folks submitting their request for records through National Archives first and, depending on discharge date, through milConnect.

- Also noting that we'll want to find a way to say that if National Archives doesn't have your record they'll help you get them/the Veteran should contact their personnel command.

**Comment by aliyahblackmore** [comment]
Ahead of our sync tomorrow, this is a word document with updates to the Request for military record page based on additional feedback from National Archives SMEs (via Danielle).

[Changes to request military service records_AB_8.21.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12415503/Changes.to.request.military.service.records_AB_8.21.docx)

### Additional notes on page updates: 

- There are a few additional SME questions included in the document 
- As we’ve discussed and following feedback from National Archives we’ll lead with sending Veterans and service members to the National Archives to get their records, but also say that if the discharge date is “after” a certain date the request can be made through milConnect. 
- I used statement headers (aside from the accordion section) to better align with more current VA style standards.
- As mentioned via Slack, the [National Archives records request page](https://www.archives.gov/veterans/military-service-records/notice-backlog-response-times-nprc) currently has an alert about DD214 requests taking about 10 days, but other document requests taking months. I’ve included adjustments to text on the page to note the time for requests for the DD214 through National Archives and that, as we chatted before, we suggest requesting through the National Archives. 
- I’ve also included content addressing folks submitting a request for their benefits application. Based on Danielle's suggestion, they also just submit their benefits application and VA will request their records for them. In future work, I’d also suggest that we note this across benefits pages on any step that refers to entering military records. I'd still like some clarity on how this happens - can we confirm with business lines whether VA automatically does this when they receive a benefits application or if someone needs to request that VA gets their records. Does this delay their application review in any way? 
- Is it most common to refer to the National Archives as the National Personnel Records Center (NPRC) or National Archives (which is at the footer of the eVetsRec tool). I think that we should consistently use "National Archives through the eVetsRec tool" since National Archives is used on the tool screens. For requests submitted in any other way or when referencing the 1973 fire, use NPRC (this seems to be how NPRC is used on our current page). Additionally from my understanding of Semrush results, "National Archives" and "National Archives military records request" have a much larger search volume than "NPRC" or "NPRC military records request."

____

**These are Danielle's notes from June 23:** 

> **Should we direct Veterans and service members who served in the Marines from 1998 to the present or the Coast Guard from 2008 to the present to contact their current unit of assignment or service department instead of directing them to the National Archives site?**
> Answer: They should contact their Personnel Command. If they submit a request to NPRC instead, we will normally refer it to their Personnel Command.

> **Should we direct all other Veterans and service members to the National Archives site?**
> Answer: Yes. 

> **As we’re reworking our information to make the National Archives site more prominent, do you have any concerns about the potential increase in the volume of records requests?**
> Answer: We have a large backlog and are not trying to drum up additional business, but it is important to get accurate information out there and for anyone in need of records, we certainly want to help them, so please make any adjustments to your web pages that you think will help.

>There were a few other questions that I looked into more myself and here are my recommendations for those:

>**In the service and request details section, the user would need to select a category that best describes why they're requesting their records. Based on your comment, Danielle, it seems like in order to get a DD 214 for benefits, they'd need to select "Benefits."** I tried this out and I was matched with a Report of Separation. But if someone needs a DD 214 for employment or another category, will they also be matched with a DD 214? 

>**Is there a way that the user should get the system to match them with a DD 214? What is that option?**
This direction was based on processing speed for benefit applications. So we could say something like, “If you need your DD214 to apply for VA benefits, select Benefits…” 

>**Is there a confirmation button or link that someone needs to select to submit their request? From the screen captures we have, the screens jump from the review and submit screen to confirmation, but we don’t see a submit button anywhere.**
I went through the request process and saw the submit button. I just went to check it out again and it seems like the whole form is down. We can double check again this week and reach out as needed. 

>**Does the Veteran’s next of kin need an authorization to request the Veterans’ records?**
Veterans and next of kin of deceased veterans have the same access rights to the record. Next of kin need to provide proof of the Veteran’s death such as a copy of death certificate, letter from funeral home, or published obituary.

**Comment by aliyahblackmore** [comment]
@bethpottsVADEPO as we discussed in our sync today, this is an updated document **without** instructions on how to request records from milConnect on the page. 

I've included the accordion with question "Can I request my records from the DOD?" and a brief answer about requesting through milConnect, as we chatted. 

[Changes to request military records page_without milConnect sections_8.23.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12423357/Changes.to.request.military.records.page_without.milConnect.sections_8.23.docx)


**As next steps:** 

- I'll update the content in Drupal tomorrow

- I'll compile questions for National Archives SMEs, draft an email summarizing the page changes, and pass the page content and email to Danielle.

**Comment by aliyahblackmore** [comment]
Hi @bethpottsVADEPO - the updates to the **[Request your military records page](https://www.va.gov/records/get-military-service-records/)** are now in Drupal and ready for your review. 

**Preview link:** 
http://preview-prod.vfs.va.gov/preview?nodeId=472

This is an updated word document of the page:
[FINAL_Changes.to.request.military.records.page_without.milConnect.sections_8.23.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12433098/FINAL_Changes.to.request.military.records.page_without.milConnect.sections_8.23.docx)

**A few notes on the page:** 
- I made a few additional adjustments to the content once I got it in Drupal - those are also reflected in this word document version of the page. 
- There are a few questions in the document for the National Archives SME - I'll adjust content accordingly once we get answers from them. 
- There are a few comments, highlighted in green, for you. If needed, I'll adjust any content accordingly based on your answers. 
- Calling out a specific comment:  I'm wondering your thoughts on including the step by step instruction on requesting records from the National Archives vs. just linking to their eVetRecs tool.  After looking at the steps and page in Drupal, they aren't very extensive and since the steps could change on the National Archives side in the future, I think that it may be better to link out to their site. One of my questions for the National Archive SME is about whether they are aware of any users having specific issues with completing the form. If they do share specific insights, then I'd suggest that we leave in the instructions.
- Last, while looking at the page in Drupal the placement of the "Reconstruct your records" link didn't feel right and aligned with more current VA page style. I moved that link to the "Other records information" link section - let me know if you have any concerns about moving that link or if there was a specific reason why it was placed there when the page was originally built.

_______

### Next steps:

After you've reviewed, as a next step I'll send a draft email over to Danielle to share with the National Archives SME. The email will include a few remaining questions (highlighted in yellow in the word document version of the page) and I'll outline these points for them: 

 - We've made updates to our VA.gov page "Request your military service records" and are now directing users to request their records from the National Archives 
 - As you all noted in your responses to Danielle, we've included details about how to request records and the selections someone should make in their request form is only for a DD214.
 
I'll check in with Danielle about the best way to send over the page - either a preview link or a word document. 

And as we discussed in our sync yesterday, I'll wait for any feedback from the National Archive SMEs and then I'll adjust content accordingly. You'll determine any other folks that may need to review this content ahead of us doing a copyedit and publishing.

**Comment by bethpottsVADEPO** [comment]
@aliyahblackmore this is ready for copyediting if you could initiate that part of the process by requesting a copyedit ticket get created. 

Couple responses here on Qs you had in the Word doc:
- I removed the step by step. I don't think it's needed because the process isn't that complicated. And we risk outdated content on our site should these steps change in the future on the NARA website.
- There's nothing the Veteran needs to do to initiate VA's gathering of the DD214 for them. VA automatically does it.
- I added an action link under "Online" and will verify that this is the right design system element here.
- I deleted the info in the accordion about "Are there other ways" because those seem to be edge cases. We'll see if the National Archives SME raises this omission.

@DanielleThierryUSDSVA Capturing a couple questions here for your contact at NARA (but first we need Megan to copyedit this):
- Do they want fax to be an option or is this now pretty outdated/hardly used?
- What other types of records are commonly requested by Veterans other than what we have listed under "Types of records"? Is there a potential third list (maybe a catch-all that covers a few others) that would make sense to add in here along with "Documents related to your discharge" and "Documents with information about your service"?

**Comment by aliyahblackmore** [comment]
@bethpottsVADEPO tracking some updates here following our conversation today:

- Adjust the list about types of documents to be this: 

**You can request documents related to your service and discharge, like these:**
•	Separation or discharge documents (including your DD 214) 
•	Awards, medals, and other decorations
•	Duty stations and assignments
•	Performance reports

- Beth to adjust above ticket comment to include question to SME about whether this list is accurate/makes sense. Is there anything else that needs to be here instead of or in addition to what we have?

**Comment by bethpottsVADEPO** [comment]
@aliyahblackmore Thanks again for the conversation about this today. I returned to look at what we discussed and realized what was not sitting right with me: we were conflating documents (DD214) and the type of information in those documents (the medals you received). So I took another shot at that section in the Drupal file. Let me know if you agree with this direction when you have a chance to take a look.

**Comment by bethpottsVADEPO** [comment]
@megzehn Just wanted to make sure you knew that this isn't ready for publishing yet, but it _is_ ready for copy editing. Thanks!

**Comment by aliyahblackmore** [comment]
Hi @bethpottsVADEPO - I took another look at the page.

Thanks for more context on the bullet list adjustments to resolve how we were conflating the documents and type of information in those documents. This list makes sense and I agree with the changes.

**Comment by megzehn** [comment]
Thanks, @aliyahblackmore and @bethpotts! Confirming that I copy edited this page. 

Note that I updated the meta description, since we shifted the language. I changed it to match the intro, but if we want to tweak it any more, let me know. 

**New meta:** 
"You can request a copy of your DD214 and other military service records from the National Archives. Learn more about how to make a request."

**Older meta:**
"Submit a military records request for documents like your DD214, awards, decorations, performance reports, orders, qualifications, and security clearance. Learn about the ways to get your own military service records or request someone else’s."

**Comment by bethpottsVADEPO** [comment]
@megzehn @aliyahblackmore thanks so much for your time and careful work on this page. Time for a SME review!

@DanielleThierryUSDSVA You can go ahead and send this to the national archives. Once you hear back and we make any needed adjustments/edits, we'll get it over to NCA to review just the one accordion that has info specific to that business line. Thanks!

**Comment by bethpottsVADEPO** [comment]
@DanielleThierryUSDSVA I don't expect you to be scanning back through this long ticket, so just repeating these couple of questions here that we'd like you to ask the NARA SME:

- Do they want fax to be an option or is this now pretty outdated/hardly used?
- Is what we have listed under "Types of information you can get" a reasonable list? What are the most important items to list there--and would you recommend removing or adding anything?

**Comment by DanielleThierryUSDSVA** [comment]
@bethpottsVADEPO @aliyahblackmore @strelichl Just sent another email to NARA director and got final feedback:

- Remove option 3. They do accept handwritten letters, but they don't encourage it because the letters often are missing info.
- In "After you request your records" section, make it clear that you only get the email if you submit a request online.

**Comment by aliyahblackmore** [comment]
**Updates here:** 

- Beth and I met (1/23) and I made updates to the page based on NARA feedback. I removed "option 3" and moved the "you'll get an email" info under the "Online" section as a note.
- I'll send an email to confirm the NCA contact info.
- After, we can have Megan do another review and then publish.

**Comment by aliyahblackmore** [comment]
Update here: 

- NCSO confirmed hours and phone number are accurate. 
- We recieved feedback on the sentence "We can help get the Veteran's DD214 or other discharge documents you may need." We'll need to make adjustments and then share them for approval.

**Comment by aliyahblackmore** [comment]
**Updates here:**

- NCSO confirmed content and I made the update in Drupal. 
- We're ready to copy edit and publish 
- After we publish, we'll share the live link with NCSO.

@megzehn this page is ready for you to review and publish!

**cc** @bethpottsVADEPO FYSA

**Comment by megzehn** [comment]
Noting here that Beth asked me to hold this in drafts for now, but that it's ready for copy editing.

**Comment by megzehn** [comment]
Hi all, confirming that I published this page. Thank you for all the updates and SME coordination! I'll move this to validate.

**Comment by aliyahblackmore** [comment]
**Update here:** 

I shared a link to the live page with NSCO SME.

**Comment by megzehn** [comment]
Thank you, Aliyah! Moving this to validate.

**Comment by megzehn** [comment]
@aliyahblackmore I went ahead and marked this as an 8 for you in the capacity tracker and a 2 for me. If that's off, feel free to adjust!
