### ISSUE TITLE
BGS debts

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#55081]
### PROD 
April 5, 2023
10AM ET

### ROUTE
/debts
/debt_letters

### PREP FOR ROLLOUT
- [x] As it's in it's own container, scale up replicas, adjust config (RC & LH)
- [x] Hit BGS from fwd proxy (RT & OM)
- [x] Review sentry for errors
- [x] Replicate for BGS https://vagov.ddog-gov.com/synthetics/details/ywf-tw7-tzx?from_ts=1680550487375&to_ts=1680636887375&live=true

### CHECKS AFTER ROLLOUT
- [ ] Test bulkhead deployment
- [ ] Test scaling

### MONITORING MECHANISMS

- /debts [datadog monitoring](https://vagov.ddog-gov.com/apm/services/vets-api/operations/rack.request/resources?env=production&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap99%29%2CtopN%3A%215%2Csearch%3Adebt%29%2Cversion%3A%210%29&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A75%29%2Cdistribution%3A%28isLogScale%3A%21f%29%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%29%2Cversion%3A%211%29&topGraphs=latency%3Alatency%2CbreakdownAs%3Apercentage%2Cerrors%3Acount%2Chits%3Acount&start=1680028596631&end=1680633396631&paused=false)

**Comment by laineymajor** [comment]
https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/53808

**Comment by oseasmoran73** [comment]
Me and @rmtolmach tested against fwdproxy.  Got a `200 OK`

**Comment by rmtolmach** [comment]
summary:

We started by modifying the revproxy to send two routes to eks. [Link to PR](https://github.com/department-of-veterans-affairs/devops/pull/12777).
```
    location ~ ^/(v0|v1)(/debts|/debt_letters) {
      proxy_pass http://{{ nginx_config_eks_api_url }}$request_uri;
```
That started working–we were able to see traffic move from BRD to EKS 🎉 

But then we realized that traffic wasn’t going to the `vets-api-web-bgs-evss` pods, it was going to the plain `vets-api-web` pods.
How did we realize that?
From [datadog](https://vagov.ddog-gov.com/logs?query=%40named_tags.dd.env%3Aeks-prod&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1680609960502&to_ts=1680610860502&live=true):
<img width="352" alt="image" src="https://user-images.githubusercontent.com/10993987/230211741-4ec284c8-bed3-4d7f-bb08-dae10a8a3e54.png">


We tell it to go to those pods in values.yaml:
```yaml
      vets-api-web-bgs-evss:
        healthCheck:
          host: ''
        autoscaling:
          enabled: true
          minReplicas: 10
          maxReplicas: 32
        routes:
          - path: PathPrefix(`/mobile/(v0|v1)(/user|/disability-rating|/payment-history)`)
            priority: 40
          - path: PathPrefix(`/(v0|v1)(/debts|/debt_letters|/profile/ch33_bank_accounts|/profile/payment_history)`)
            priority: 40
```
BUT, something’s not working b/c it’s not working! (traffic is not being routed to the right pods)
We tried:
* tweaking the priority (higher numbers and lower numbers)
* changing path vs pathPrefix
* added another route in staging to test
* tried || in the ingress route path
* changed container name to service name in parent helm chart.

The resolution was to add an extra `/` to routes.path (👏 @ericboehs). We tried it in staging with: 
```
- path: PathPrefix(`//v0/status`)`
```
And then when we realized that worked, we added it to prod for the paths we were migrating today.
PR with resolution: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1721/files 

yay, it’s working:
<img width="406" alt="image" src="https://user-images.githubusercontent.com/10993987/230211123-5ce19349-ad57-4b9c-8146-32cbaee8433d.png">
`/v0/debts` is going to `vets-api-web-bgs-evss` 🎉

**Comment by RachalCassity** [comment]
The` \\` is only in staging. Production only has a single `\`

**Comment by RachalCassity** [comment]
Incorrect format (Currently using):
`Path(`/(v0|v1)(/debts|/debt_letters|))``

Correct format:
PathPrefix(`//{path:(v0|v1)/(debts|debt_letters)}`)

**Comment by laineymajor** [comment]
ADDED TO THIS SPRINT AS PART OF THE EKS MIGRATION.
