### ISSUE TITLE
[VFS Monitoring/Alerting]: Enable Slack Integration for Sentry Alerts

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#55091]
### Describe the problem

Monitoring and alerting are a central component of a mature product team. Though it's no fault of Platform teams, we have been significantly impacted by a lack of autonomy and unwieldy nature of the only available alerting process in Sentry.

Alerting on VFS teams is currently limited in the following ways:

1. We don't have the autonomy to set up alerts in the only alerting mechanism (issue ownership) currently working in Sentry; we must rely on platform support. While platform teams are excellent, relying on y'all to approve simple configuration requests like this places unnecessary burden on platform teams and reduces the autonomy with which VFS teams operate. Both of these drawbacks decrease the velocity of product and platform teams.
2. The only currently working alerting mechanism in Sentry (issue ownership config) is prolific in the alerts it sends, making it hard to pinpoint issues. It also solely relies on email as its alerting system, which is prone to filters, spam blockers, and accidentally getting buried.

### Who will benefit

It's clear that all VFS teams will benefit by having control over their alerting system. However, Platform teams will also see a decrease in requests to configure alerts for VFS teams, reducing the burden on platform support.

### Describe your idea

The simplest idea we have is to enable Slack integration in the current `http://sentry.vfs.va.gov/` Sentry instance (`VSP` organization). There may be technical or procedural issues with this approach, however, enabling Slack integration will allow VFS teams to configure their own slack integrations with dedicated channels to proactively handle any incidents that occur.

If Slack integration is unfeasible due to level of effort or a technical/procedural blocker, it looks like there may be [some history of using webhooks to sent errors to DataDog and then having DataDog take care of the alerting](https://dsva.slack.com/archives/CBU0KDSB1/p1642535108486300?thread_ts=1642187323.408700&cid=CBU0KDSB1). However, VFS teams do not have write access to DD, so this would require platform support as well.

Finally, email is an acceptable alerting mechanism, but there are drawbacks vs Slack. If we could figure out how to re-enable sending alerts via email from Sentry, this would be a step in the right direction.

### Provide evidence

https://dsva.slack.com/archives/CBU0KDSB1/p1676059425011579

https://dsva.slack.com/archives/CBU0KDSB1/p1678122264462019

https://dsva.slack.com/archives/CBU0KDSB1/p1678721148949179

https://dsva.slack.com/archives/CBU0KDSB1/p1668707111130899

https://dsva.slack.com/archives/CBU0KDSB1/p1659448501942089

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4696

https://dsva.slack.com/archives/CBU0KDSB1/p1642535108486300?thread_ts=1642187323.408700&cid=CBU0KDSB1

### Platform Mission

- [X] Keeps these products and services available, stable, and secure.
- [X] Ensures they are consistent and meet high standards of quality in Veteran-centered user experience and technical approach.
- [X] Provides shared tools, software, support, and technical infrastructure to accelerate their development.
- [ ] Other

**Comment by va-albers** [comment]
Including @mchelen-gov for prioritization help

**Comment by jilladams** [comment]
+1 for this feature request. 

For Public Websites, we use Sentry for error monitoring for the Forms product which relies on vets-api: [Find a Form error report](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?id=19&project=4&statsPeriod=7d). We have also configured Alerts: [Forms errors warning / critical notifications](http://sentry.vfs.va.gov/organizations/vsp/alerts/metric-rules/platform-web/7/), but they don't do anything. We don't receive a notification or email. Would be great if we could.  (cc @wesrowe )

**Comment by va-albers** [comment]
Hi @little-oddball & team - how can I check the status on this item?  Also who do I need to work with to prioritize this?  🙇

**Comment by va-albers** [comment]
Hi @little-oddball and team - I'm checking in on the status for this item.  We have production issues and we are trying to address (in part) by configuring Sentry/Slack integration - what can we do to prioritize (or get a status update) on this work?  I'm hoping this is as simple as someone pressing the big "Enable Sentry integration" button, but please let me know if there is more work involved that we can assist with.

**Comment by kjduensing** [comment]
From my perspective, Sentry holds an important place in debugging, error tracing, and alerting. I see Sentry and Datadog performing 2 different functions. 

Functionality aside, in addition to invalidating our tooling, processes, and documentation, the Sentry -> Datadog migration might represent actual code changes on our side, which slows down delivery of features.

Also, the Platform's customers are a little bit "migration weary" right now. There are several non-optional migrations (EKS & EVSS sunsetting) many VFS teams are having to implement. 

Obviously, I prefer getting Sentry/Slack integration working :). But these are just my thoughts, more user research is needed by the Platform to see if the themes above resonate throughout VFS teams.

**Comment by jilladams** [comment]
@gia-lexa any updates here? We have active incidents every now and then ([example](https://dsva.slack.com/archives/CBU0KDSB1/p1691430186980299)) where this push from Sentry would be really really helpful.

**Comment by gopixelsgo** [comment]
Hi @gia-lexa thanks for the detailed status from a while back! Is it safe to say this ticket can be closed? Doing a bit of cleanup and closing some loops. Thanks!

**Comment by gopixelsgo** [comment]
Hi @gia-lexa and @little-oddball - just following up on my previous comment. Is it safe to close this ticket? Thanks!

**Comment by gopixelsgo** [comment]
Thank you @gia-lexa! That does help!

**Comment by gopixelsgo** [comment]
Hi @little-oddball - would you mind closing this ticket if the request is considered complete? Thanks!

**Comment by gopixelsgo** [comment]
Hi @little-oddball - any update on this item?

**Comment by little-oddball** [comment]
> Hi @little-oddball - any update on this item?

I wasn't assigned to the issue so haven't been tracking it at all.

**Comment by little-oddball** [comment]
Sentry is an item Platform is working to deprecate so that aspect of this ticket doesn't make sense to invest in moving forward. As far as DD, it should already be working w/ Slack Integration.

I would suggest closing this ticket.
