### ISSUE TITLE
GA4:  Testing & Validation - Web Components

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#55100]
## Issue Description

This ticket is for the testing and validation of web components event tracking as the Design System team implements the provided data layer code.  

The design system team will be implementing in phases and we will be testing in phases as they release them. (Get links to their tickets)

## Tasks
- [x] Review each implemented web component
- [x] Test each web components
- [x] Sign-off on or more to custom if needed.

## Acceptance Criteria
- [x] We have completed the web component events configuration and testing requirements.

**Comment by michelle-dooley** [comment]
web components tested as part of this ticket... https://docs.google.com/spreadsheets/d/1c3Fd0f6rA0yRBeYuZEZzxzeLvJJclFUB5lX8hYPn7SY/edit#gid=2089299676
alert
alert expandable
breadcrumbs
button pair
banner
