### ISSUE TITLE
Research Spike: Encourage users to create idme or login.gov accounts

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#55127]
With the sunsetting of DSLogon, users will need to be informed of the next steps needed in order to create idme or login.gov accounts. We need to research how to format and present this information

## Tasks
- [x] Draft a [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/90f06685432228b839fec6fa0b7b740e09d02b5d/products/identity/Research/2023-04%20Proactive%20LIG%20Migration/2023-04%20Proactive%20LIG%20Migration%20research%20plan.md) that considers how to encourage veterans to create idme or login.gov account
- [x] Draft a [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/90f06685432228b839fec6fa0b7b740e09d02b5d/products/identity/Research/2023-04%20Proactive%20LIG%20Migration/2023-04%20Proactive%20LIG%20Migration%20conversation%20guide.md) for research considering Proactive Migration
- [x] work with LGA team to understand the prototype they designed that's related to this work
   - [x] add prototype to this research as makes sense
- [x] meet with LGA to understand their recent research findings related to terms or phrases that might help guide this research
- [x] Complete the [Midpoint Review](https://app.zenhub.com/workspaces/collaboration-cycle-reviews-61d89e9e5f4c120011a0ad37/issues/gh/department-of-veterans-affairs/va.gov-team/54326) touchpoint
- [x] UX team research document review
- [x] PO research document review
- [x] Complete [Research Review](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/280) touch point
- [x] practice conversation guide
- [x] pilot session
   - [x] set up pilot session
   - [x]  run pilot session
   - [x]  debrief pilot session
- [x]  [organize moderators, note takers and observers for each session](https://docs.google.com/spreadsheets/d/1y6D2_ItNX9Tch5-nlOFw4Te1ycQMxTqCh09-w-iluWQ/edit#gid=0)
- [x]  conduct all research sessions (15 scheduled, 14 complete)
   - [x] post-session debriefs
- [x]  [analyze notes](https://app.mural.co/t/oddballinternal7486/m/oddballinternal7486/1681396854554/ff9d23f8eef22907cccb8d45cf46f81f5686684d?wid=0-1682693897900)
- [x]  synthesize findings 
- [x]  draft [findings report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Research/2023-04%20Proactive%20CSP%20Migration/2023-04%20Proactive%20CSP%20Migration%20research%20findings.md)
- [x]  draft findings presentation deck
- [x]  communicate and socialize findings ([slide deck](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Research/2023-04%20Proactive%20CSP%20Migration/Proactive%20Migration%20Research%20Readout.pdf))
   - [x]  Demo - Wed 24May
   - [x]  Identity working group (Thurs 25May)
   - [x]  Sitewide Content team
   - [x]  Schedule to present for Monday VA UX meeting (June 12th)

## Acceptance Criteria

- [x] define language for alerting and informing users 
- [x] Research and decisions are documented and shared with appropriate team members
- [x] Path forward for tasking for alerting/informing defined (collab cycle, etc)
- [x] Follow on ticket for front end implementation and other communication methods is created/updated

**Comment by claytonzook** [comment]
Today we completed conducting the last sessions for this research

**Comment by aparsley** [comment]
Taking these findings and using them for Infographic as well as Login.gov Verification Account Guide
