### ISSUE TITLE
Get Ruby 3.0 running on k8s branch

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#55126]
## Issue Description
Now that vets-api has been updated from Ruby 2.7 to Ruby 3, it's time to get it running on the k8s branch. Let's do that.

---
## Tasks
- [x] Get vets-api running Ruby 3 on the k8s branch

## Acceptance Criteria
- [x] vets-api is running Ruby 3 runs on the k8s branch
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-api/pull/12121

6 Failures in run - https://github.com/department-of-veterans-affairs/vets-api/actions/runs/4428456808/jobs/7767564039:
```
2023-03-15T16:23:50.3187120Z [31mrspec './modules/appeals_api/spec/services/appeals_api/pdf_construction/generator_spec.rb[1:1:3:2:1]'[0m [36m# AppealsApi::PdfConstruction::Generator#generate Higher Level Review v3 generates the expected pdf[0m
2023-03-15T16:23:50.3188078Z [31mrspec './modules/appeals_api/spec/services/appeals_api/pdf_construction/generator_spec.rb[1:1:3:2:4:1]'[0m [36m# AppealsApi::PdfConstruction::Generator#generate Higher Level Review v3 with max length generates the expected pdf[0m
2023-03-15T16:23:50.3189232Z [31mrspec './modules/appeals_api/spec/services/appeals_api/pdf_construction/generator_spec.rb[1:1:3:2:3:1]'[0m [36m# AppealsApi::PdfConstruction::Generator#generate Higher Level Review v3 with minimum content generates the expected pdf[0m
2023-03-15T16:23:50.3190276Z [31mrspec './modules/appeals_api/spec/services/appeals_api/pdf_construction/generator_spec.rb[1:1:3:2:5:1:1]'[0m [36m# AppealsApi::PdfConstruction::Generator#generate Higher Level Review v3 with special characters when compatible with Windows-1252 does not remove the characters[0m
2023-03-15T16:23:50.3191394Z [31mrspec './modules/appeals_api/spec/services/appeals_api/pdf_construction/generator_spec.rb[1:1:3:2:5:2:1]'[0m [36m# AppealsApi::PdfConstruction::Generator#generate Higher Level Review v3 with special characters when incompatible with Windows-1252 and unable to downgrade removes the characters[0m
2023-03-15T16:23:50.3192608Z [31mrspec './modules/appeals_api/spec/services/appeals_api/pdf_construction/generator_spec.rb[1:1:3:2:2:1]'[0m [36m# AppealsApi::PdfConstruction::Generator#generate Higher Level Review v3 with extra content generates the expected pdf[0m
```
