### ISSUE TITLE
Identify crew for all VFS Products in Directory

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#55134]
# Description
Work is being done to identify key points of contact for all products that are listed on the VFS Product Directory. Some preliminary tickets have been done at this point. Next we would like to compile a list of any products that have not been assigned to a crew, and identify which crew they belong to.

# Tasks
- [ ] Create a list of all products that do not have a Crew identified
- [ ] Review for any easily answered items - and complete them
- [ ] Determine who should be involved in determining what crew unassigned products should belong to
- [ ] Review the list with those stakeholders, make the changes as appropriate
- [ ] Inform new associations to ensure they are aware of the change

# Acceptance Criteria
- [ ] A list of decision makers is identified for who should assign products to a crew
- [ ] All products have a defined crew

**Comment by CBonade** [comment]
Reliability no longer owns the product. Not planning to complete this.
