### ISSUE TITLE
Modify text of VFS Product Directory page

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#55135]
# Description
The Product Operations group requested some updates to the VFS Product Directory page opening on Platform Website, due to some confusion about what VFS stands for, as well as making it clear what the focus of the page is. Based on discussions around the details of this, we anticipate that the text below would be sufficient.

**SAMPLE TEXT**
Veteran Facing Service (or VFS) teams create what we refer to as VFS Products, these are products that veterans, their family members and care providers have direct interaction with. This product directory provides a list of all VFS products currently in use on va.gov, as well as key information about them. It provides a way for VFS Team Members and OCTO Stakeholders to view the data currently associated with VFS products and serves as a reference for identifying what data needs to be updated. If you see any errors that need to be fixed, changes to these fields can be made by following the steps outlined here

To learn about what information is listed in each column, see this page.

# Tasks
- [ ] Reconfirm text version w/ Dan and product operations group
- [ ] Make the change to the Confluence page
- [ ] Verify that the page output properly to Platform Website

# Acceptance Criteria
- [ ] Update has been verified on platform website

**Comment by JoeTice** [comment]
Products for Potential Removal:

- Product Name
- 22-0994 Education Benefits Form
- 22-1990e TOE Form Benefits
- About VA Disability Ratings 
- Authentication and Authorization 
- Campaign Landing Page
- Coronavirus Chatbot
- Education Benefits App under FRY or DEA 22-5490 (Under My Education Benefits) 
- Education Benefits for National Call to Service App (22-1990N) (Under My Education Benefits) 
- Education Benefits Transfer App (22-1990E) (Under My Education Benefits) 
- Education Change of Program or Training App 22-1995 (Under My Education Benefits) 
- Education Change of Program or Training App under FRY or DEA 22-5495 (Under My Education Benefits) 
- COVID-19 screener
- Education Benefits Applications
- Enrollment Verification (Under My Education Benefits in GH) 
- FRY/DEA – VA Education Benefits for Survivors and Dependents
- Mock Form
- Notice of Disagreement
- Opt Out of Sharing VA Education Benefits Information
- Original Claims
- PCPG CH36
- 1010EZ Health Care Application 
- Questionnaire List
- LGY: COE
- Request a Supplemental Claim
- Secure Inbox for Education Benefits
- Site Navigation
- Stakeholder Enterprise Portal
- Terms and Conditions
- STEM Scholarship
- My Education Benefits
- Notifications Preferences
- Verify Identity
- View your Representative
- View, search, and update you representative
- VR&E CH 31
- Post-9/11 GI Bill Benefit Information
- Rated Disabilities
- Search Representative
- Translated Pages
- Veteran Rapid Retraining Assistance Program (VRRAP) 
- View and Update Dependents
Do research on how to handle products that could be removed.


•	VA Education Letters
