### ISSUE TITLE
UAT Testing with DMC API change

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#55137]
## Issue Description
DMC is adding an API change for handling file not found responses and requires us to use a couple file number examples to test found letters, no letters, and no file number. 

---
## Tasks
- [ ] Sync with DMC engineering team to test via curl API requests
- [ ] Take responses from API tests and test data against the portal

## Acceptance Criteria
- [ ] DMC can move forward with releasing their API change
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
