### ISSUE TITLE
Review Product Directory in comparison with products for potential removal

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#55132]
# Description
The product operations group has created a list of products that exist on the VFS Product Directory that they believe should be removed. While that is possible to do, removing products from the VFS Product Directory has some potentially wider reaching impacts, so it's important to understand why each item is being removed, so that those products are handled appropriately. Some examples:

- Is the product being removed because it is no longer present on va.gov?
- Is the product being removed because it is not a standalone product, but in fact is a part/component of a larger product?
- Is the product being removed because it is not actually a VFS product, but belongs to a platform group?
- Other reasons - to be identified

# Tasks
- [ ] Review the list of products to be removed and identify the reason why
- [ ] Discuss the list w/ Dan Kosko, Peter, and other relevant team members
- [ ] Identify how each product should be handled
   - [ ] If necessary, schedule meetings as necessary to ensure alignment on any products with unclear status
- [ ] Make the changes as agreed
   - [ ] Make any subsequent tickets for any issues that are more involved

# Acceptance Criteria
- [ ] Get an agreed plan for how each product should be handled
- [ ] Make changes to any items

**Comment by JoeTice** [comment]
Products for Potential Removal:

- Product Name
- 22-0994 Education Benefits Form
- 22-1990e TOE Form Benefits
- About VA Disability Ratings 
- Authentication and Authorization 
- Campaign Landing Page
- Coronavirus Chatbot
- Education Benefits App under FRY or DEA 22-5490 (Under My Education Benefits) 
- Education Benefits for National Call to Service App (22-1990N) (Under My Education Benefits) 
- Education Benefits Transfer App (22-1990E) (Under My Education Benefits) 
- Education Change of Program or Training App 22-1995 (Under My Education Benefits) 
- Education Change of Program or Training App under FRY or DEA 22-5495 (Under My Education Benefits) 
- COVID-19 screener
- Education Benefits Applications
- Enrollment Verification (Under My Education Benefits in GH) 
- FRY/DEA – VA Education Benefits for Survivors and Dependents
- Mock Form
- Notice of Disagreement
- Opt Out of Sharing VA Education Benefits Information
- Original Claims
- PCPG CH36
- 1010EZ Health Care Application 
- Questionnaire List
- LGY: COE
- Request a Supplemental Claim
- Secure Inbox for Education Benefits
- Site Navigation
- Stakeholder Enterprise Portal
- Terms and Conditions
- STEM Scholarship
- My Education Benefits
- Notifications Preferences
- Verify Identity
- View your Representative
- View, search, and update you representative
- VR&E CH 31
- Post-9/11 GI Bill Benefit Information
- Rated Disabilities
- Search Representative
- Translated Pages
- Veteran Rapid Retraining Assistance Program (VRRAP) 
- View and Update Dependents
- VA Education Letters

**Comment by CBonade** [comment]
This work was completed.
