### ISSUE TITLE
Research Medallia Written Response Survey Data - Get Data

### ISSUE THREAD

**Issue by Nyanteea** [department-of-veterans-affairs/va.gov-team#55143]
## Issue Description
   As Product, I would like to see the written survey feedback from veterans about their experience with 526ez form to understand their pain points and understand where to focus our efforts for improvement. 

Scope of this ticket is to get this information from the source.

Nyantee - There is a feedback button on each page of the 526 form; feedback from the form is pulled in to DOMO through Medallia however there is no access to the written response portion of the survey due to PII security concerns. I want to try and gain access to that data from the Contact Center team to gain insight into veterans' pinpoints at specific points in the form. 

## Dependencies
- [x]  [Create ticket for contact center insights request ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=ianMcCullough-ob%2C+ATMiddleton&labels=VSP-contact-center%2Ccc-data-request&template=qualitative-data-request.yml&title=Qualitative+Data+Request)

---
## Tasks
- [x]  [Create ticket for contact center insights request ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=ianMcCullough-ob%2C+ATMiddleton&labels=VSP-contact-center%2Ccc-data-request&template=qualitative-data-request.yml&title=Qualitative+Data+Request)
- [x] Approval and review from Ian McCullough

## Acceptance Criteria
- [ ]  Receive batch of survey insights from contact center that is good enough to begin analysis 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Nyanteea** [comment]
![Screenshot 2023-03-14 at 5.03.24 PM.png](https://images.zenhubusercontent.com/63e51eafcf2f21b449885353/03906840-e2f7-4ce0-8d47-858da26afef7)
