### ISSUE TITLE
Support ESECC Approval Process (Sprint 23)

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#55148]
## Issue Description
In order to be approved to get access to use preview.va.gov for preview environments, we have submitted a request and are working through the ESECC approval process.

**Current State:**
As of Sprint 21, we have received 2 levels of approvals and believe there are two more remaining.

**Latest Action:**
In late Feb, there was a request for additional information:
- Site needs to be indicated
- www URL registered must be https
- WASA finding risk must have an AO-approved POAM, PTA required
- Resubmit once addressed
This info and these items were resubmitted on 3/10 and we are waiting for a response.

---
## Tasks
- [ ] Continue to check/review the submitted request to determine if additional action is needed (should be checked daily)
- [ ] TBD

## Acceptance Criteria
- [x] We have followed up with the request and have logged any requested items
- [ ] Any requested items have been delivered... OR
- [x] Have been carried over to a ticket for the following sprint

**Comment by pjhill** [comment]
- [ ] Complete the BPE tab
- [ ] Provide adequate WASA report
- [ ] Describe preview environment activity more completely in resubmission
- [ ] Indicate Cloud region

**Comment by pjhill** [comment]
BPE is described as --

>Business Partner Extranet (BPE) is an encrypted connection between a remote party (Business Partner, Vendors, affiliate university, etc.) and the VA TIC Gateways. BPE uses a leased circuit that directly connects the VA resource(s) to a partner(s) and capable of supporting higher bandwidth requirements. The BPE comes at a cost when it resides on the VA domain and must be acquired by the cost center through the VIPR process and completing a WAN Capacity evaluation.

>BPE connections to the cloud must go through the VIPR, VAEC, and WAN Capacity evaluation and could be an iBPE (Internet) or eBPE. All prerequisites are done prior to ESECC submission.

>Ø    Change types that fall under BPE:
>·   New BPE Sub-Connection - Submit when no connection exists for the requirement
>·   Cloud Service Provider BPE - Submit when a connection to/from/within the cloud is required
>·   BPE & Firewall Connection - Submit when modification to a BPE requires firewall changes
>·   BPE & Internet Connection - Submit when a web service or application must be added to a BPE or modified

**Comment by JoeTice** [comment]
Based on discussions from this effort since feedback was provided:
- [ ] Complete the BPE tab
  - [ ] Fill out the BPE worksheet
- [ ] Submit request for a WASA scan (will wait till we feel more confident on having internal preview environments working within SOCKS) (NOTE - We believe WASA scans have a 30 day wait)
- [ ] Describe preview environments more completely in resubmission, without using terms that might raise concern
- [ ] Indicate cloud region
- [ ] Submit updated answers

**Comment by pjhill** [comment]
The process of resolving this ESECC request will continue to next sprint.
