### ISSUE TITLE
Research how revproxy is used in RIs, dev and staging

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#55164]
# Description
As we prepare to use revproxy in support of preview environments, there are a number of questions that need to be answered in order to ensure we approach the solution in the best way...

Kerry previously experimented with a Docker image of an nginx revproxy [here](https://vfs.atlassian.net/wiki/spaces/TT4/pages/2563407880/Revproxy+in+EKS).

# Tasks
- [ ] Answer the following research questions:
   - [ ] Is it possible to operate a single revproxy in support of preview environments?
   - [ ] Can we use one image and configure it in the container after setup?
   - [ ] If we need to create a custom revpoxy container for each preview environment - how should we do that?
   - [ ] Can we borrow from the existing revproxy templates in devops?
- [ ] Document your findings in Confluence

# Acceptance Criteria
- [ ] Questions have been answered to a level that allows us to have a clear path forward
- [ ] Documentation is complete that articulates what we learned and why we chose the approach that we did

**Comment by pjhill** [comment]
Prior work with revproxy from Kerry is here -- https://vfs.atlassian.net/wiki/spaces/TT4/pages/2563407880/Revproxy+in+EKS

**Comment by JoeTice** [comment]
Sprint 23 Update - Task was started this sprint but was too long to complete this sprint, will be completed in Sprint 24

**Comment by JoeTice** [comment]
Adding @gia-lexa @holdenhinkle to this task

**Comment by holdenhinkle** [comment]
Does this Ningx server exist yet? If so, where is it?

Will all requests coming to this server be specifically for preview instances? Will requests ever come in that are not for review instances?

***

My mental model for how this works:
A new version of vets-website (based on branch and last commit) is built and deployed
=> The preview instance or PI going forward

A URL is created for this PI.

What is the anatomy of this URL? Can we get an example of it one?

The user is directed to the URL.

A request is made to the PI.

The RevProxy, RP going forward, intercepts the request, and routes it to the correct PI.

How does the RP know about newly created PIs? How is it updated?

***

From the little previous experience I had with RPs, Nginx can't discover new containers to route traffic to on its own. The service would have to be stopped, the new containers port/ip address/whatever would have to be added to the configuration, and then the service would have to be restarted.

We used [Traefik](https://github.com/traefik/traefik-library-image), an RP for Docker that can be dynamically updated in real time and doesn't need to be stopped/started when new containers are spun up that it needs to route request to.

I asked ChatGPT about this:


Holden:
> When running containers or pods in Docker or Kubernetes, is this the following statement true regarding Nginx as a rev proxy?

_"From the little previous experience I had with RPs, Nginx can't discover new containers to route traffic to on its own. The service would have to be stopped, the new containers port/ip address/whatever would have to be added to the configuration, and then the service would have to be restarted."
The statement you provided is partially true but does not consider the capabilities of Nginx when used with Docker or Kubernetes. In a typical setup, Nginx alone cannot automatically discover new containers or pods to route traffic to. However, when used in conjunction with Docker or Kubernetes, there are mechanisms that allow for dynamic configuration and automatic discovery."_

GPT:
> In a Docker environment, you can use tools like Docker Compose or Docker Swarm. Docker Swarm, for example, provides service discovery and load balancing features, which allow Nginx to route traffic to different containers without having to manually update the configuration.
> 
> In a Kubernetes environment, Nginx can be deployed as an Ingress controller, which is a more native solution for managing external access to services running in a Kubernetes cluster. The Ingress controller automatically discovers new services and pods based on Ingress resources and configures Nginx to route traffic to them. This eliminates the need to manually update the Nginx configuration for each new service or pod.
> 
> In both cases, you can achieve dynamic configuration and service discovery without having to stop the service, manually update the configuration, and restart the service.

Holden
>Is a rev proxy like Traefik better for routing traffic to dynamically created pods or containers that have dynamically created URLs? Or can Nginx handle this use-case now?

GPT:
> Traefik is often considered better suited for routing traffic to dynamically created containers or pods with dynamically created URLs, as it has been designed specifically for this purpose. It comes with built-in service discovery and can dynamically update its configuration without requiring a restart.
> 
> That being said, Nginx can also handle this use-case, especially when used in conjunction with other tools or platforms.
> 
> In a Docker environment, you can use Nginx with Docker Swarm or third-party tools like Consul Template to enable dynamic configuration updates based on container creation and termination events.
> 
> In a Kubernetes environment, as mentioned earlier, you can deploy Nginx as an Ingress controller. The Ingress controller will automatically discover new services and pods based on Ingress resources and update the Nginx configuration accordingly.
> 
> While both Traefik and Nginx can handle dynamic routing, Traefik is generally considered more user-friendly and better suited for dynamic environments out-of-the-box. However, Nginx is more mature and battle-tested, and it can be configured to handle dynamic routing when integrated with other tools or platforms. The choice between the two often comes down to personal preference, specific use-cases, and familiarity with either tool.


***

How did this work with review instances?

What are the differences between review instances and preview instances?

Can the RP config for review instances be repurposed?
https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/templates/review_instance_nginx_revproxy.conf.j2

**Comment by JoeTice** [comment]
The team encountered challenges in completing this task, we feel it would be more helpful to start with an initial task to look at Review Instance's use and setup of revproxy to help point us in the right direction
