### ISSUE TITLE
Prepare Presentation of Feedback data

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#55175]
## Purpose
Prepare artifacts associated with the synthesis of the survey.  Our goal w/ this updated Survey is to be able to track changes qtr-over-qtr, and make these results easily accessed and absorbed by Leadership and Platform teams.

Communicating these on Demo Day and a SDT Confluence space will help:
1) Communicate data to Leadership & Platform teams
2) Tell the story over time of progress or not

## Notes
- Important to relay info in a way that Leadership understands its significance, and hopefully is actionable for them as well when it comes to prioritization.

## Tasks
- [x] Evaluate how best to present the data in an interesting and quarter-over-quarter way
- [x] Prepare slide deck to present at Demo Day
- [x] Prepare format to be shared on SDT's Confluence space (or preferred spot)

## Acceptance Criteria
- [x] [Deck](https://docs.google.com/presentation/d/1YyoJbzBTk9BDoIqI682vW5bSy7xfr9tCyu6uwuaKzpo/edit#slide=id.p1) for Demo is ready
- [x] [Site](https://vfs.atlassian.net/wiki/spaces/AP/pages/2629173255/new+Customer+Satisfaction+Survey+2023+and+beyond) is ready

**Comment by steel36** [comment]
Will rollover to next sprint - unexpected OoO

**Comment by steel36** [comment]
Will rollover to next sprint - (due to team resource change)

**Comment by tayism** [comment]
This ticket should have been closed yesterday, on the last day of the sprint. That was my error.

**Comment by steel36** [comment]
Ticket is complete; will close tomorrow due to Zenhub policy.
