### ISSUE TITLE
Close Survey and Synthesize results

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#55174]
## Purpose
_What details are necessary for understanding the specific work or request tracked by this issue?_

## Tasks
- [ ] Close Survey
- [ ] Synthesize Results
- [ ] Prepare Presentation
- [ ] Prepare Feedback themes mural
- [ ] Present Presentation at Demo day

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

**Comment by steel36** [comment]
Will rollover to next sprint - unexpected OoO

**Comment by twoangstroms** [comment]
@steel36 Thanks for catching that! I did not see that that text was a link.

**Comment by steel36** [comment]
I updated the Confluence page to reflect the closed status.

**Comment by twoangstroms** [comment]
@tayism Looks like a slip of the paste in the ticket description: the "Synthesize" link goes to Google Calendar.

**Comment by tayism** [comment]
This will roll over as we're working through synthesis with the new format survey, and had some considerations to work though regarding how we'd slice the data. Feedback has been collected from the team and design lead, and this will be complete this sprint.
