### ISSUE TITLE
Publicize Survey

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#55173]
## Purpose
Step through the tasks to prep, launch, run, and synthesize the quarterly survey

## Tasks
- [ ] Publicize Survey (Slack)
-draft messaging
-execute messaging
- [ ] Publicize Survey (ToT)

- [ ] Close Survey
- [ ] Synthesize Results
- [ ] Prepare Presentation
- [ ] Prepare Feedback themes mural
- [ ] Present Presentation at Demo day

## Acceptance Criteria
- [ ] Survey is socialized in ToT
- [ ] Survey is socialized in Slack
