### ISSUE TITLE
[PM] Notification design system component: Submit collab cycle request

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#55186]
## Background
To begin development of the notification design system component we'll need to submit the collaboration cycle request. Information about the collaboration cycle and kick-off process can be found [here](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/collaboration-cycle-kickoff).

## Tasks
- [x] Gather materials for kick-off - write project outline
- [x] Submit [kick-off ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-review%2Ccollaboration-cycle%2CCC-Request&template=collaboration-cycle-request.yml&title=Collaboration+Cycle+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D)
- [x] Perform any follow-up items from kick-off

## Acceptance Criteria
- Kick-off is submitted and completed

## Resources
- [Onsite notifications FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/mvp/frontend-documentation/notifications-frontend-documentation.md)
- [Design system submission - #1181](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1181)
- [Sketch design file](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/BE3AD487-CCBD-4DAB-96F2-18A5F90D063F)

**Comment by ajakabcin** [comment]
Submitted #55405
