### ISSUE TITLE
[Epic] Profile 2.0: Review content pages/My VA dashboard for any needed updates

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5518]
## User story

As a person trying to access my VA.gov profile/settings, I may be accessing my profile from another part of VA.gov and need links to the profile/settings to work correctly and content to be accurate so I don't get lost. 

## Tasks

- [x] Review My VA for any links/content that need to be updated #5522
- [x] Review Change your address content page for any links/content that need to be updated #5524
- [x] Review Direct deposit content page for any links/content that need to be updated #5525
- [x] Review Sign in FAQ for any links/content that need to be updated #5527
- [x] Determine if there's any other pages we might have missed in this list above #5528

## Acceptance criteria

- [x] All the above tasks are complete

**Comment by tressaellen** [comment]
List of updates are stored in #8395
