### ISSUE TITLE
Update past and current Post-9/11 GI Bill rates pages to match changes made to future rates page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#55188]
## Issue Description

We recently published the [Future rates for Post-9/11 GI Bill](https://www.va.gov/education/benefit-rates/post-9-11-gi-bill-rates/future-rates/). We need to update our current and past rates pages to match some of the changes we made after working with stakeholders.

## Tasks
- [ ] Update current rates page (Katherine)
- [ ] Update past rates page (Katherine)
- [ ] Copyedit current rates page (Megan)
- [ ] Copyedit past rates page (Megan)
- [ ] Publish current rates page (Megan)
- [ ] Publish past rates page (Megan)

## Acceptance Criteria
- [ ] Changes on both pages are live on the site

**Comment by megzehn** [comment]
These have been reviewed and published. Thanks for making all these changes, @katherine-fung!

**Comment by RLHecht** [comment]
These changes are live. Closing.
