### ISSUE TITLE
Tech Discovery - endpoint /intenttofile

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#55190]
## Issue Description
Form 526 currently calls EVSS /intenttofile endpoint for submitting claims via vets-api. This call needs to be migrated to Lighthouse as part of overall eVSS migration to Lighthouse.

endpoint /intenttofile is available in Lighthouse in production. This issue is to discover 
- what data field(s) are being sent and received from the eVSS endpoint by the 526 form?
- what is the endpoint in existence in LH that replaces this service?
- what data field(s) are being sent and received from the new LH endpoint?
- can form 526 switch to this LH endpoint without changes for this service?

Scope - Potentially 3 endpoints to migrate.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [x] what data field(s) are being sent and received from the eVSS endpoint by the 526 form?
- [x] what is the endpoint in existence in LH that replaces this service?
- [x] what data field(s) are being sent and received from the new LD endpoint?
- [x] can form 526 switch to this LH endpoint without changes for this service?
- [x] a ticket created on 526 board to switch this end point to LH endpoint, with dependencies documented, if any

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by colevoss** [comment]
[Lighthouse API Docs](https://developer.va.gov/explore/benefits/docs/claims?version=current)

**Comment by navaeddie** [comment]
**General Structure of these EVSS services that's followed here**
- Configuration file: lib/evss/:service_name/configuration.rb
	- A partially hardcoded string for the destination
- Service definition: lib/evss/:service_name/service.rb
	- operative methods are defined
- [Service Name] Controller
        - uses a standard Rails controller, calls on the service's methods

**Old Intent to File implementation**
- `EVSS::IntentToFile` 
- "/wss-intenttofile-services-web/rest/intenttofile/v1"
- IntentToFileController has index, active, submit.
	- index: return an intent to file
		- Is it scoped to a user? Where?
	- active:
		- uses seperate service for Redis?
			- Sends current_user uuid.
	- submit:
		- What is sent? How is it scoped to a user?
	- Creating a new Intent to File via the browser, after clicking Start Disability Compensation link on a 526 introductory page
		- V0::IntentToFilesController#index actions (app/controllers/v0/intent_to_files_controller.rb) is triggered
		- If it doesn't find one, it redirects to V0::IntentToFilesController#submit
- Other relevant files
	- intent_to_file/service
	- intent_to_file/response_strategy
		- Seems like services with "response strategy" (in addition to the standard Response class applied to other EVSS services) to handle Redis
	- intent_to_file/intent_to_files_response
		- recieves an array of "intent to files" from EVSS
			- Haven't yet found where/how the code deciphers which of the files is applicable to the current user. And how it decides if none of them match and it needs to send a submit request
