### ISSUE TITLE
[eFSR] Employment History summary card update

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#55196]
## Issue Description
Update employment history cards to match [new design](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1671734127581/dc254b12e788570c946af60bc55338b0045aea03?invited=true&sender=u7f58f2afe2ea053d4dea4234)

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/ed70dbc5-9c35-4e18-ad49-aa5f961d66b3)

---
## Tasks
- [ ] Update veteran employment history summary page to match new design
- [ ] Update spouse employment history summary page to match new design
- [ ] Confirm flow and other employment related pages match new design as well
- [ ] Update e2e tests as necessary
- [ ] Update unit tests as necessary

## Acceptance Criteria
- [ ] Veteran employment history matches new design
- [ ] Spouse employment history matches new design
- [ ] Unit and e2e test are updated and passing

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by amponce** [comment]
Current progress. I was able to get the cards in place and populate the contents with data. I need to confirm with design that the above screenshot is still current and then I'll address styling. 

**Todo:**

- [ ] Fix index when user clicks edit
- [ ] Add delete functionality
- [ ] Meet with Andrew and Brandyn to get a better understanding of the spouse employment section and if this file can be shared between the two.

![Screenshot 2023-04-11 at 12 29 26 PM](https://user-images.githubusercontent.com/3916436/231519793-2cd6651a-53ae-439a-be90-9c2670d5ede0.png)

**Comment by amponce** [comment]
Possible option to make employment history summary a shared file between spouse and veteran

https://gist.github.com/amponce/5b3fb1580067779e4771c383fab01a7e

**Changes are based on this data:**

```
"employmentHistory": {
      "spouse": {
        "employmentRecords": [
          {
            "type": "Full time",
            "from": "2018-6-XX",
            "to": "",
            "isCurrent": true,
            "employerName": "Spouse Current"
          },
          {
            "type": "Full time",
            "from": "2015-3-XX",
            "to": "2018-6-XX",
            "employerName": "Spouse Previous",
            "isCurrent": false
          }
        ]
      },
      "veteran": {
      "employmentRecords": [
        {
          "type": "Full time",
          "from": "2021-01-XX",
          "to": "",
          "isCurrent": true,
          "employerName": "Test",
          "grossMonthlyIncome": "123",
          "deductions": [
            {
              "name": "State tax",
              "amount": "1"
            }
          ]
        },
        {
          "type": "Full time",
          "from": "2021-01-XX",
          "to": "2021-12-XX",
          "isCurrent": false,
          "employerName": "I quit"
        }
      ]}
    },
    ```

**Comment by mgleo** [comment]
@amponce Here is the design with the information from the card in your comment: 
![Screenshot 2023-04-12 at 2.00.06 PM.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/9bce2448-7e78-43ec-9277-3a07b7d6ad35)

Link to Mural: https://preview.uxpin.com/f43733391f52c409c4d3152e9a4b101a392e29df#/pages/161664325/simulate/sitemap
Link to Sketch:
https://www.sketch.com/s/79aa4a84-fef1-4c06-9495-e0431a6390bd

Small detail: The delete button width can be shrunk down as it is currently too far from the right border
![Screenshot 2023-04-12 at 1.58.44 PM.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/68e062a7-c958-451e-87f6-eda8759e2e6a)

**Comment by mgleo** [comment]
Hi @amponce, 
Just wanted to note, this may be addressed on another ticket but the radio buttons below the summary cards on Employment History also need to be changed into an action link.
![Screenshot 2023-04-18 at 10.00.32 AM.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/8c2e9297-248e-4537-af69-643c46e88122)

cc @Dr-Pongo @HeatherRienks

**Comment by HeatherRienks** [comment]
Per our team's FSR conversation on 4/18 - will not need additional ticket!

**Comment by amponce** [comment]
updated screens




### Before

<table>
  <tr>
    <th>Original</th>
  </tr>
  <tr>
    <td>
      <img src="https://user-images.githubusercontent.com/3916436/231890971-4daeb605-294f-4d17-aa55-8e5d98dfba3b.png" alt="Original" width="300" />
    </td>

  </tr>
</table>


### After - Employment history (Veteran)

<table>
  <tr>
    <th>Veteran Screenshot 1</th>
    <th>Veteran Screenshot 2</th>
  </tr>
  <tr>
    <td>
      <img src="https://user-images.githubusercontent.com/3916436/232908878-b93ac2cb-8c92-4ec9-8035-2fe6b051f6d0.png" alt="Screenshot 1" width="300" />
    </td>
    <td>
      <img src="https://user-images.githubusercontent.com/3916436/232908944-1e0aa187-1a4b-41d9-b515-68f49ec2e84d.png" alt="Screenshot 2" width="300" />
    </td>
  </tr>
</table>


### After - Employment history (Spouse)

<table>
  <tr>
    <th>Spouse Screenshot 1</th>
    <th>Spouse Screenshot 2</th>
  </tr>
  <tr>
    <td>
      <img src="https://user-images.githubusercontent.com/3916436/232909245-7b6334ac-4714-4b57-a23d-9c82a9d18e26.png" alt="Screenshot 1" width="300" />
    </td>
    <td>
      <img src="https://user-images.githubusercontent.com/3916436/232909289-0f7faa33-faf7-435e-abc2-eee4bea2ece5.png" alt="Screenshot 2" width="300" />
    </td>
  </tr>
</table>
