### ISSUE TITLE
Translation: Content changes to disability eligibility page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#55192]
## Issue Description

As part of the disability audit work, we made changes to the [Eligibility for VA disability benefits page](https://www.va.gov/disability/eligibility/). Now that this page is also in Spanish, we need to have these changes translated and update the Spanish version of the page.

## Tasks
- [ ] Send content changes to translators (Ana)
- [ ] Input translated changes in Drupal (Ana)
- [ ] Review (Megan)
- [ ] Publish (Megan)

## Acceptance Criteria
- [ ] Spanish content is updated to match English page

**Comment by coforma-terry** [comment]
@ABeltran77 - check in with Megan on this one :)

**Comment by ABeltran77** [comment]
@coforma-terry Will do :)

**Comment by ABeltran77** [comment]
@RLHecht Here is the Word doc with the Content changes to disability eligibility page for the translators.

[Eligibility for VA disability benefits page_SP edits.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12322586/Eligibility.for.VA.disability.benefits.page_SP.edits.docx)

**Comment by RLHecht** [comment]
Thanks @ABeltran77 I sent this to the translators. Will update the tracker

**Comment by ABeltran77** [comment]
@RLHecht Thank you!

**Comment by RLHecht** [comment]
@ABeltran77 Here is the content back from the translation team. [LS-2022-0118394-D-SPA-FINAL_New Eligibility for VA disability benefits content for Spanish translation.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBamhaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--09ee8d3bea83cb2a841cb13353e4cda4980886ef/LS-2022-0118394-D-SPA-FINAL_New%20Eligibility%20for%20VA%20disability%20benefits%20content%20for%20Spanish%20translation.docx)

**Comment by ABeltran77** [comment]
@RLHecht @megzehn Translated changes in have been input in Drupal

**Comment by megzehn** [comment]
Thanks, @ABeltran77! Confirming I published the changes that were in there.

Could you confirm if this sentence was translated or not? I didn't see a corresponding sentence. 

> For some conditions, we automatically assume (or “presume”) that your service caused your condition. We call these presumptive conditions.

Also, I think we still need to translate this additional bullet:

> Mental or physical health conditions related to military sexual trauma (MST)
[Learn about MST and disability compensation](http://preview-prod.vfs.va.gov/resources/military-sexual-trauma-and-disability-compensation)

**Comment by megzehn** [comment]
^ CC @RLHecht for awareness!

**Comment by ABeltran77** [comment]
@megzehn @RLHecht are these sentences and bullet on the Eligibility for VA disability benefits page (https://www.va.gov/disability/eligibility/)? I'm not seeing them ???

**Comment by ABeltran77** [comment]
Ahhh, sorry, I've been looking at so many pages I skipped that one...here you go:

- For some conditions, we automatically assume (or “presume”) that your service caused your condition. We call these presumptive conditions.

Para algunas condiciones, automáticamente asumimos (o “presuponemos”) que su servicio causó su condición. A estas las llamamos condiciones presuntivas.

- Mental or physical health conditions related to military sexual trauma (MST)
   Learn about MST and disability compensation

Condiciones de salud física o mental relacionadas con el trauma sexual militar (MST, por sus siglas en inglés)
Obtenga más información sobre MST y la compensación por discapacidad

**Comment by RLHecht** [comment]
Thanks @ABeltran77 Can you add these changes into the Drupal page and then Megan can review and publish?

**Comment by ABeltran77** [comment]
@RLHecht @strelichl These changes have been made into the Drupal page. @megzehn they're ready for review and publishing. Thank you!

**Comment by megzehn** [comment]
Thanks, @ABeltran77! Confirming this is live now. 

Here's the Drupal link for reference: http://preview-prod.vfs.va.gov/preview?nodeId=50389

@strelichl we can close this one out!
