### ISSUE TITLE
[FE] My VA Healthcare: Update Schedule and manage appointments icon

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#55199]
## Background
As described in [53241](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53241), we need to update the icon for "Schedule and manage your appointments" within the Health care section on My VA from the current fa-calendar-check icon to the fa-calendar icon. This will align us with what's being used in the appointments tool and what will be used in a new MHV landing page design.

## Tasks
- [ ] Update the icon associated with the "Schedule and manage appointments" secondary link in the health care section of My VA to use the `fa-calendar` icon (instead of the `fa-calendar-check` icon) ([documentation here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/health-care-FE-documentation.md#schedule-and-manage-your-appointments-link))
- [ ] Test
- [ ] Move to validate

## Acceptance Criteria
- [ ] Schedule and manage appointments icon matches styling in [sketch file](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/8AB87684-AE2C-42F4-BC9D-60E4B26AE1BB)

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ See that icon on staging matches designs (test with user 262)

## Resources
- [Slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1675786396553929)
- [GH comment thread](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1493#issuecomment-1420904698)

**Comment by allisonlu** [comment]
is this a duplicate of #53242?

**Comment by ajakabcin** [comment]
@allisonlu whoops! sure is 🙃 I'll close this one - thanks for catching!
