### ISSUE TITLE
[eFSR] Other asset user flow update

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#55202]
## Issue Description
Update other asset checklist - input list - summary page flows so an empty checklist will result in the user being directed to the next section rather than an empty summary page. 

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/393a478b-bc64-4315-9ca6-8c3ecbcc07e9)

---
## Tasks
- [ ] Update other asset page flow to match new design
- [ ] Identify & update any other similar flow to match new design
- [ ] Update e2e tests to match new flow
- [ ] Update unit tests to match new flow

## Acceptance Criteria
- [ ] (checklist - input list - summary) flows match new design (skipping empty mini summary)
- [ ] User and e2e tests are updated and passing as necessary

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
