### ISSUE TITLE
[eFSR][bug] Employment history navigation fixes

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#55200]
## Issue Description
Back navigation in the midst of updating employment history has some unexpected results like kicking the user back to the summary page with an incomplete record and adding an additional blank record. Another note is the payroll deductions checkbox to input box selection pages, if no checkbox is selected, the input list page is empty and it should be skipped. 

Steps to recreate issue:
- Answer yes to"have you had a job in the last 2 years", click continue. 
- Enter employer information, click continue.
- Select back on gross monthly income page.
- This returns user to summary page with incomplete data.

---
## Tasks
- [ ] Identify & fix navigational issues
- [ ] Identify & fix checklist/input list navigation issue
- [ ] Update e2e and unit tests as necessary. 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
Deprecation and a few other issues caused this to get pushed back. Will roll to sprint 97, but it'll be top of the list!

**Comment by amponce** [comment]
I'll take a crack at this ticket since we already got a good start on it with the summary card updates
