### ISSUE TITLE
[FE] Add period on h1 for error pages

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#55214]
## User Story
Add a period after "We couldn't check you in"

https://github.com/department-of-veterans-affairs/va.gov-team/issues/54280

## Tasks
- [ ] Add period
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by wullaski** [comment]
@loripusey I have a PR for [this issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54475) which will close this out.
