### ISSUE TITLE
[FE] Modify the PreCheckInAccordionBlock to not open accordion items when there is an error

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#55219]
## User Story
Ben to evaluate if a change is needed.

[slack thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1678887494781529)

When the veteran gets an error on an expired pre check in link the accordion assumes that the answers to the demographics questions were all 'no'. This results in the accordion opening certain drawers that might not make sense. 

<img width="994" alt="screen_shot_2023-03-15_at_9 35 53_am" src="https://user-images.githubusercontent.com/2982977/225369710-3111f305-bc2b-4100-97d2-94f2dc7a0278.png">

For these scenarios we don't have answers to the questions but we show the accordion.
- appointment-canceled
- pre-check-in-past-appointment
- pre-check-in-expired

We could change the default to null and don't open any drawers on the accordion unless answers to demographicsUpToDate, emergencyContactUpToDate, or nextOfKinUpToDate are passed in.

  
## Tasks
- [ ] Change the argument default to null
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
Too old, closing
