### ISSUE TITLE
[eFSR] Currency input box design 

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#55213]
## Issue Description
`va-number-input` doesn't currently support including a $ to represent currency input, so we will need a temporary styling update to apply until it has been added. There is currently a `currency-input` class defined in the FSR that can probably be modified to target the shadow root input component of the `va-number-input`. 

[Platform design issue](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1280)

---
## Tasks
- [ ] Implement a style update that targets `va-number-input` so a $ is visible and the input boxes match designs

## Acceptance Criteria
- [ ] Currency inputs on the FSR that use `va-number-input` show a $

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by amponce** [comment]
Looks like this issue is currently slated to be resolved this sprint. https://github.com/department-of-veterans-affairs/component-library/pull/651

**Comment by amponce** [comment]
Closing issue and my corresponding PR with the temporary fix
