### ISSUE TITLE
Profile Dashboard - Design & Data QA - Internal

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#55215]
## What this form is for
As we roll out the Profile edge case dashboard, we need to do a final QA of the data and the design.    

---
## Resources
- [How to design QA Domo dashboards]( https://vfs.atlassian.net/wiki/spaces/AT/pages/2216002036/How+to+Design+QA+a+Domo+dashboard)
- [How to data QA Domo dashboards](https://vfs.atlassian.net/wiki/spaces/AT/pages/1821900905/How+to+Data+QA+Domo+dashboards)
- [Profile Tracking sheet](https://docs.google.com/spreadsheets/d/15NKyGxXm9d43iGUoWMxKmo0NZv4gW3dX1sFIeVhGt_I/edit#gid=2091635579)
- [Profile dashboard](https://va-gov.domo.com/page/1834995012)
- [Profile mock up](https://docs.google.com/presentation/d/1zzFSi5ZfIDqy5buQZX1NwRjvCA-dwPTDYOaSidCwZlw/edit#slide=id.g17e6772cc4c_0_31)

---
## Tasks
- [x] Complete steps as outlined in [How to design QA Domo dashboards]( https://vfs.atlassian.net/wiki/spaces/AT/pages/2216002036/How+to+Design+QA+a+Domo+dashboard) using this [template](https://docs.google.com/spreadsheets/d/1m-P4eLEzD59X_yMvbh5AtdMN4gSHLW7yAvjCdR42KU4/edit#gid=0)
- [x] Complete steps as outlined in [How to data QA Domo dashboards](https://vfs.atlassian.net/wiki/spaces/AT/pages/1821900905/How+to+Data+QA+Domo+dashboards)

---
## Acceptance Criteria
- [x] The design and data on the new dashboard, card, or for a new product in Domo has accurate and trustworthy. The dashboard is ready to be shared with stakeholders.
