### ISSUE TITLE
[Design] Profile 2.0: Review My VA for any links/content that need to be updated

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5522]
## User story

As a person trying to access my VA.gov profile/settings, I may be accessing my profile from another part of VA.gov and need links to the profile/settings to work correctly and content to be accurate so I don't get lost. 

## Additional background

Epic #5518

## Tasks 

- [x] Review My VA to see if any of the content needs to be updated (eg. does it mention account?)
- [x] Review My VA to see if any links need to be updated (eg. do we link to account?)
- [x] Determine any tickets that need to come out of this work and work with Matt/Samara to get those tickets created

## Acceptance criteria

- [x] My VA has been reviewed and next steps have been determined

**Comment by Samara-Strauss** [comment]
Is there anything that needs to be updated coming out of this? Even if not, it would be helpful to have a status update in the comments so we can easily look back and see what the resolution was.

**Comment by tressaellen** [comment]
Currently there are links to account and profile from my VA.gov, these need to be combined into a single link to profile - this is tracked in #8400 

Part of epic #8395
