### ISSUE TITLE
[Analytics] Create filters in GA for unique page urls

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#55223]
## Description 

To create a more apples to apples comparison in Google Analytics, for example, bounce rates from /intro page vs. /complete page, create filters in GA to combine unique urls into one. 

Pages that are effected are, /complete and /appointment-details in check in and /appointment-details in pre check in. 

## Tasks

- [x] Confirm pages that are effected are correct
- [x] Write regex statement for those to be used in GA (it should be a total of 3 filters)
- [x] Work with Michelle to add those filters into the GA staging site
- [x] Check if it worked in GA staging
- [x] Add to GA production 
- [x] Verify it worked in GA production

**Comment by loripusey** [comment]
[Filters in Staging](https://analytics.google.com/analytics/web/#/a50123418w178298118p245756216/admin/view/filters/)

**Comment by benbrasso-agile6** [comment]
The filters look good to me. I'd like to wait for a bit more traffic to show up in staging to confirm it's working.

**Comment by loripusey** [comment]
@benbrasso-agile6 I am adding a 4th filter for pre-check-in details because it exists
![image](https://user-images.githubusercontent.com/86678742/227218216-d6037153-beb2-463a-99d2-ddb82d7a489a.png)

**Comment by benbrasso-agile6** [comment]
If the url has the UUID in it, sounds good.

**Comment by loripusey** [comment]
It does: https://staging.va.gov/health-care/appointment-pre-check-in/appointment-details/38044-530

**Comment by benbrasso-agile6** [comment]
I think this is working as intended. Nice work. Ok to close. 

https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20230328&_u.date01=20230328&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22RE%22,%22appointment-check-in~2Fappointment-details%22,0%5D%5D&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=100/

https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20230328&_u.date01=20230328&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22RE%22,%22appointment-check-in~2Fcomplete%22,0%5D%5D&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=100/

https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20230328&_u.date01=20230328&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22RE%22,%22appointment-pre-check-in~2Fappointment-details%22,0%5D%5D&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=100/

https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20230328&_u.date01=20230328&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22RE%22,%22appointment-pre-check-in~2Fcomplete%22,0%5D%5D&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=100/

**Comment by loripusey** [comment]
closing

**Comment by benbrasso-agile6** [comment]
I believe these are working in production. Looked at the data from yesterday.
