### ISSUE TITLE
Benefits Reference Data(BRD) functionality - Abstract calls for - Address Controller

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#55235]
## Issue Description
The eVSS is being deprecated and the vets-api utilizes these services to retrieve and post data.
One of these services is the BRD service that indicates gets Benefits Reference Data.
This eVSS endpoint is being sunsetted with the eVSS in August.

We need to migrate any calls to the eVSS BRD endpoint to the Lighthouse version.
The scope of this ticket to abstract these calls where applicable:
-  Address Controller

---
## Tasks
- [ ] Identify Lighthouse migration endpoint - what is the endpoint in existence in LH that replaces this service?
- [ ] Audit all calls to eVSS services within the functionality
- [ ] create (a) provider(s) - evss and Lighthouse
- [ ] Authentication?
- [ ] Create Response object - what data field(s) are being sent and received from the eVSS endpoint by the 526 form?
- [ ] Find how endpoint can be tested. Where does this information get stored when a user works on a claim. Where functionality is being utilized and use that place to test new api provider - can form 526 switch to this LH endpoint without changes for this service? what data field(s) are being sent and received from the new LH endpoint?

## Acceptance Criteria
- [ ] Form 526: no changes to BRD functionality
- [ ] Maintain test coverage?
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
