### ISSUE TITLE
Heuristic evaluation synthesis and report

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#55231]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

A review and synthesis of the team's completed individual heuristic evaluations will be done. A concise report will be created for the team, compiling everyone's individual evaluation feedback. In Heuristic Eval Workshop Part 2, the team will have a chance to review the issues that were noted, and decide what to change. 

Report/deck [https://docs.google.com/presentation/d/1CWREIS5t-8wPJaHIpQCKJNYn9jluuslE/edit?usp=sharing&ouid=105840574529848970044&rtpof=true&sd=true] 

Heuristic evaluation compilation spreadsheet [https://docs.google.com/spreadsheets/d/1BonkkC9j4xVrwDjmX_rEeNIjfnU_WTYEjQoVVRz6Ihc/edit#gid=439561159]

## Tasks
-  _What work is necessary for this story to be completed?_
- [x] _The review and synthesis process_
- [x] _Creation of a report as a document or a deck_

## Acceptance Criteria
- _What will be created or happen as a result of this story?_
- [x] _The review and synthesis process_
- [x] _Creation of a report as a document or a deck_

**Comment by HeatherRienks** [comment]
I think we are done with this work! :) If so, it can be moved to "Validate."

**Comment by charlottecesana** [comment]
Report/deck [https://docs.google.com/presentation/d/1CWREIS5t-8wPJaHIpQCKJNYn9jluuslE/edit?usp=sharing&ouid=105840574529848970044&rtpof=true&sd=true] (url)

Heuristic evaluation compilation spreadsheet [https://docs.google.com/spreadsheets/d/1BonkkC9j4xVrwDjmX_rEeNIjfnU_WTYEjQoVVRz6Ihc/edit#gid=439561159](url)

**Comment by HeatherRienks** [comment]
Thank you @charlottecesana  for adding the links in! So helpful!

**Comment by denisecoveyduc** [comment]
@charlottecesana One last time I will reiterate our thanks for leading the team through this material!  The output is incredible and I know we will leverage these principles going forward to enhance our products even more!
