### ISSUE TITLE
Develop Relationship with Login.gov

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#55237]
## Issue Description
_The call center team receives cases from AVA and the VEO call center regarding users being unable to log into their VA.gov account.  In many instances, the issue may lie with the CSP or credentialing service provider.  In order to provide the best service to VA.gov users, a relationship must be established with CSPs._

_Login.gov is a provider that allows or prohibits individuals into their VA.gov accounts.  Building a bridge to work in partnership to offer faster service for login issues is vital._

---
## Tasks
- [ ] _Create a process for getting callers to Login.gov for better/faster results._
- [ ] _Obtain details on how to determine Login.gov issues._
- [ ] _Gather details to modify/create new templates regarding Login.gov_
- [ ] _Establish meeting cadence for knowledge sharing._
- [ ] _Share any relevant information with VEO tier 1 agents._

## Acceptance Criteria
- [ ] _A decrease in cases concerning Login.gov sign in issues_
- [ ] _An opportunity to use this experience as a blueprint to begin establishing intentional relationships with other CSPs and call centers_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
[https://app.zenhub.com/files/133843125/36d97110-dec0-43cc-ba26-6393c1d8d805/download](https://app.zenhub.com/files/133843125/36d97110-dec0-43cc-ba26-6393c1d8d805/download)
