### ISSUE TITLE
Discovery - Sync 526ez form with the current paper form

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#55243]
## Issue Description
VBA needs to have the 526ez form on va.gov to be in sync with the latest version of the paper form. The scope of this ticket is to identify all locations on the digital form that need to be updated as part of this work.

Scope also includes ancillary forms. Check which of the following are on the 526ez form and/or need to be:
Form 21-4142, Authorization to Disclose Information to the Department of Veterans Affairs (VA)
Form 21-4142a, General Release for Medical Provider Information to the Department of Veterans Affairs (VA)
Form 21-686c, Application Request to Add and/or Remove Dependents
Form 21-674, Request for Approval of School Attendance
Form 21-8940, Veteran's Application for Increased Compensation Based on Unemployability
Form 21-0781, Statement in Support of Claim for Service Connection for Post-Traumatic Stress Disorder
Form 21-0781a, Statement in Support of Claim for Service Connection for Post-Traumatic Stress Disorder Secondary to Personal Assault
Form 26-4555, Application in Acquiring Specially Adapted Housing or Special Home Adaptation Grant
Form 21-4502, Application for Automobile or Other Conveyance and Adaptive Equipment
Form 21-2680, Examination for Housebound Status or Permanent Need for Regular Aid and Attendance
Form 21-0779, Request for Nursing Home Information in Connection with Claim for Aid and Attendance

Out of scope:
- Design/content changes for the update
- Implementation of the design/content changes

---
## Tasks
- [x] Compare the paper and digital versions of 526 form 
- [x] Discuss ancillary forms with stakeholders to determine which to include in 526 digital experience

## Acceptance Criteria
- [x] List of all locations on the 526 digital form that require a change, including locations of applicable ancillary forms
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
@lydiahooper @Nyanteea

**Comment by lydiahooper** [comment]
The digital 526 currently includes: 
**Form 21-0781** (Claim for Service Connection for Post-Traumatic Stress Disorder), only if user specifies PTSD as a new condition
**Form 21-8940** (Veteran’s Application for Increased Compensation Based on Unemployability) in a screen flow with **Form 21-4192** (Request for Employment Information) 

Additionally, users can download (to submit outside of digital 526):
Form 26-4555 (Application in Acquiring Specially Adapted Housing or Special Home Adaptation Grant)
Form 21-4502 (Application for Automobile or Other Conveyance and Adaptive Equipment)
Form 10-1394 (Application for Adaptive Equipment—Motor Vehicle), and/or 
Form 21-2680 (Examination for Housebound Status or Permanent Need for Regular Aid and Attendance).

**Comment by lydiahooper** [comment]
The digital 526 currently also includes **Form 21-4142**, Authorization to Disclose Information to the Department of Veterans Affairs (VA) is embedded but displays only if user selects "Please get my records from my doctor." If user indicates that they want to upload their private medical records, they are given the option to upload a completed **Form 21-4142** but are not directed to where they can download a blank version.

**Comment by lydiahooper** [comment]
Purple stickies on this board indicate locations for changes within digital 526, based on paper version: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1676487520026/4af83a6b8196cf61ff93abc7cf17b8260fa80240?sender=u2905941a69b3083a009c9997

**Comment by lydiahooper** [comment]
I would propose this chunking of work for making 526 updates based on paper form:

1. Update explanatory language (especially on landing/initial pages; this language is the first half of the 15-page paper form) -- Content/language changes only, probably will need research/validation
2. Build new screens (for toxic exposure questions and service pay questions if needed) -- These are entirely new and therefore will need research/testing and design/prototyping
3. Update questions (minimal addition, removal, or reordering, for example insert checkboxes where needed) -- Will require design but probably not research
4. Basic functional changes (for example, change required questions to optional) -- Mostly engineering

Another way to do it would be to chunk by sections of form:
1. Initial info about form
2. Veteran info including address/homeless info
3. Service and exposure info
4. Disabilities info
5. Service pay, direct deposit info, and certification

**Comment by lydiahooper** [comment]
Discussion with forms digitization team on Mar 27 resulted in these decisions/recommendations:

1. Keep Form 21-0781 PTSD in 526 flow (the only place it's needed in digital form) to improve efficiency
2. Keep Form 21-4142 Authorization to Disclose in 526 flow to improve efficiency, but eventually replace with design/code being created for standalone digital version
3. Keep Form 21-8940 Unemployability in 526 flow (and probably Form 21-4192?) until standalone digital version is available, then...
4. Move (from step 2) or add links to all other forms to post-submission page
