### ISSUE TITLE
[Design] Profile 2.0: Review Change your address content page for any links/content that need to be updated

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5524]
## User story

As a person trying to access my VA.gov profile/settings, I may be accessing my profile from another part of VA.gov and need links to the profile/settings to work correctly and content to be accurate so I don't get lost. 

## Additional background

Epic #5518

## Tasks 

[Change your address content page](https://www.staging.va.gov/change-address/)

- [x] Review Change your address content to see if anything needs to be updated
- [x] Review Change your address to see if any links need to be updated (eg. do we link to account?)
- [x] Determine any tickets that need to come out of this work and work with Matt/Samara to get those tickets created

## Acceptance criteria

- [x] Change your address has been reviewed and next steps have been determined

**Comment by Samara-Strauss** [comment]
Is there anything that needs to be updated coming out of this? Even if not, it would be helpful to have a status update in the comments so we can easily look back and see what the resolution was.

**Comment by tressaellen** [comment]
This page is using a subway map and needs to be updated to use a dynamic modal with updated links. Tracked in #8420
