### ISSUE TITLE
Login.gov adoption team: Sprint 16 (3/16 - 3/29)

### ISSUE THREAD

**Issue by elizabethkochBT** [department-of-veterans-affairs/va.gov-team#55252]
## PTO

- Ksenia 3/16
- Sofia 3/16
- Elizabeth 3/17
- Tom 3/20 - 4/3
- John 3/23 - 4/6
- Tyler 3/23-3/24
- Carl 3/29

## Sprint 16 Priorities

 - Test grandfathering journeys with Veterans
 - Update comms strategy, and develop content for email outreach to users with ID.me/Login.gov
 - Continue to iterate dashboard
 - Prep for organic adoption research
 - Plan in-person proofing kickoff
 - Review feedback form Login.gov on compensating for lack of AAL2

 
## Retro Board

[Sprint 15 Retro](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1677768711421/aad15b9308afe560c52a1beddefe388840ae239d?wid=0-1678115373703)

### Discussion Topics/Retro Action Items
 - [x] share summary sprint ticket with core team so they know/can look at what we're working on
 - [x] Tight Agenda 
 - [x] create tickets based on sprint planning discussion
 - [x] Jay, Anthony, & Porta to discuss collaboration strategy. 
 - [x] Review the Shared Tasking with the Core Team (DS Logon Migration)
 - [x] tag other teams' tickets with login.gov-adoption
 - [x] create a separate ticket for tasks we're doing related to other teams' (big) tickets

### Legacy credential migrations & Login.gov proactive adoption
 - [ ] Modal GA tagging for organic adoption experiment #53788
 - [x] Continued discussion with Login.gov around proofing and compensating controls #53783
 - [x] Run pilot session for round 1 of testing grandfathering journey(s) #54820
 - [x] Prepare team for research sessions #54926
 - [x] Conduct research sessions to test grandfathering journey(s) with Veterans #53386
 - [x] Back end modal logic for identifying MHV binding #55315
 - [x] Create Data Dictionary and Data Lineage documents for the data supporting the Login.gov Adoption Dashboard #55323
 - [x] Build charts which visualize KPIs for Login.gov Adoption #55325
 - [x] Establish MHV grandfathering feature flag #55314
 - [x] Update comms strategy #55372
 - [x] Develop content for email outreach to users that already have ID.me/Login.gov #55362
 - [x] Define how we get a user back to their original task before they were interrupted #55332
- [x] Refine pathways & releases strategy doc #55473
- [x] Plan kickoff with Core team(w/o 4/3) #55466
- [x] Prepare to partner with core team on organic adoption messaging usability study #55185
- [x] Organic Adoption - Modal Display Logic (Front End) #54478
- [ ] Prep for help center interviews #55474
- [ ] Reporting for organic adoption experiment #53790

## Collab Cycle Tasks 
 - [x] Design Intent for organic adoption  
 - [x] Design Intent - IA Feedback - Login.gov adoption team, Organic Adoption #55393
 - [x] Midpoint Review - Accessibility Feedback - Login.gov adoption team, DS Logon Grandfathering / Inherited Proofing #55066
 - [x] Plan for research, analytics, and midpoint reviews for organic adoption
 - [x] Research for grandfathering (binding) #53386
