### ISSUE TITLE
[Design] Profile 2.0: Review Direct deposit content page for any links/content that need to be updated

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5525]
## User story

As a person trying to access my VA.gov profile/settings, I may be accessing my profile from another part of VA.gov and need links to the profile/settings to work correctly and content to be accurate so I don't get lost. 

## Additional background

Epic #5518

## Tasks 

[Change direct deposit content page](https://www.staging.va.gov/change-direct-deposit/)

**For this page, you will need to review the dynamic widgets as well, so you'll need to sign in to test different states. Talk to Samara about how to do this.**

- [x] Review Change direct deposit content to see if anything needs to be updated
- [x] Review Change direct deposit to see if any links need to be updated 
- [x] Determine any tickets that need to come out of this work and work with Matt/Samara to get those tickets created

## Acceptance criteria

- [x] Change direct deposit has been reviewed and next steps have been determined

**Comment by tressaellen** [comment]
Moving from slack for visibility:

There are four states for the first dynamic widget:
Signed out 
Signed is as LOA1 (user hasn't verified their identity) (+350)
Signed in as LOA3 without 2FA set up
Signed in as LOA with 2FA set up 
The copy for each widget shouldn't need to change. They all link to the profile. So, the update here may just be the link to the profile itself.
As for seeing each widget, I'll leave it up to you and Matt to figure out how to see each of those states, though I will tell you we have one user for the 2FA state and those credentials are all messed up and Idk that we can view that state right now. But you should be able to view states 1, 2, and 4

**Comment by tressaellen** [comment]
Signed out 
<img width="858" alt="Screen Shot 2020-04-24 at 10 27 45 AM" src="https://user-images.githubusercontent.com/58752772/80253965-c1693c00-8626-11ea-9971-cd82c19f556d.png">


Signed in as LOA with 2FA set up
<img width="858" alt="Screen Shot 2020-04-24 at 10 27 45 AM" src="https://user-images.githubusercontent.com/58752772/80253901-9f6fb980-8626-11ea-8ef3-11b43931fd65.png">

Signed in as LOA1
<img width="836" alt="Screen Shot 2020-04-24 at 12 26 42 PM" src="https://user-images.githubusercontent.com/58752772/80254087-fe353300-8626-11ea-87fc-c54e5cfd2afa.png">

**Comment by Samara-Strauss** [comment]
Is there anything that needs to be updated coming out of this? Even if not, it would be helpful to have a status update in the comments so we can easily look back and see what the resolution was.

**Comment by tressaellen** [comment]
If the user is signed in as LOA with 2FA set up the  'Go to your profile link' needs to be updated. This is outlined in ticket #8419 (Part of epic #8395 )
