### ISSUE TITLE
[Design] Profile 2.0: Review Sign in FAQ for any links/content that need to be updated

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5527]
## User story

As a person trying to access my VA.gov profile/settings, I may be accessing my profile from another part of VA.gov and need links to the profile/settings to work correctly and content to be accurate so I don't get lost. 

## Additional background

Epic #5518

## Tasks 

[Sign in FAQ page](https://www.staging.va.gov/sign-in-faq/)

- [x] Review Sign in FAQ to see if anything needs to be updated
- [x] Review Sign in FAQ to see if any links need to be updated (eg. do we link to account?)
- [x] Determine any tickets that need to come out of this work and work with Matt/Samara to get those tickets created

## Acceptance criteria

- [x] Sign in FAQ has been reviewed and next steps have been determined

**Comment by tressaellen** [comment]
No updates needed for the FAQ page.
