### ISSUE TITLE
[Design] Profile 2.0: Determine if there is any other content/links that needs to be updated as part of Profile 2.0

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5528]
## User story

As a person trying to access my VA.gov profile/settings, I may be accessing my profile from another part of VA.gov and need links to the profile/settings to work correctly and content to be accurate so I don't get lost. 

## Additional background

Epic #5518

## Tasks

- [x] Determine if there are any other pages than the ones listed in #5518 that need to be updated
- [x] Determine if any additional tickets need to be created and work with Matt/Samara to get those tickets created

## Acceptance criteria

- [x] VA.gov has been reviewed and next steps have been determined

**Comment by tressaellen** [comment]
I couldn't find any other pages with links to the profile in va.gov.
