### ISSUE TITLE
[DD][EKS] Db-migrate monitor and alert

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#55297]
## Description

There have been a few instances where vets-api fails to sync in kubernetes due to `db-migrate` failing or getting stuck. We should add some monitor and alerts to notify for environments

## Tasks

- [x] Create monitor and alert
- [x] Environments sending to correct channels

## Acceptance Criteria

- [x] db-migrate alerts are going to slack in correct channels
~~[ ] Prod integrated with PD~~

**Comment by oseasmoran73** [comment]
Figured out monitor. Need to create and send alerts to appropriate channel. Not sure what that will be

**Comment by oseasmoran73** [comment]
@laineymajor @LindseySaari Should `sandbox` be alerted for PD? Or just #oncall channel?

**Comment by LindseySaari** [comment]
> @laineymajor @LindseySaari Should `sandbox` be alerted for PD? Or just #oncall channel?

Great question, I would check with Lighthouse. Sandbox has an SLA or 99% uptime. Although, on the weekend, I wouldn't see this being super critical, because new pods wouldn't roll out/break anything if because they'd be stopped from rolling out. I think oncall may suffice.

**Comment by oseasmoran73** [comment]
@LindseySaari Im sure i know the answer, but when the daily deploy (in BRD) goes out, that is the only time `sandbox` gets updated, correct? It does not get updated on a push basis like how dev + staging are, correct?

**Comment by LindseySaari** [comment]
Merged this morning + tf applied.

**Comment by LindseySaari** [comment]
Pd not integrated for prod as of yet. Let's revisit this before the prod rollout, but we can create the oncall alert for the after prod rollout.

**Comment by laineymajor** [comment]
Adding to the pre-prod epic!

**Comment by oseasmoran73** [comment]
#56034 created. Closing this out
