### ISSUE TITLE
MHV on VA.gov: Landing Page: Wayfinding research

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#55305]
## Issue Description
Robyn Singleton is leading a study on wayfinding study to understand how different groups of users understand and navigate the different portions of the future state of VA.gov (health hub, My VA, MHV on VA.gov) to accomplish common health-related tasks.

This ticket tracks some of the work and tasks Cara Frissell is doing to support this study.

---
## Tasks
- [x]  Cara sync with Robyn re: wayfinding study needs
- [x]  Desktop research
- [x]  Review/feedback on research plan
- [x]  Ideate analysis frameworks

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
