### ISSUE TITLE
Back end modal logic for identifying MHV binding

### ISSUE THREAD

**Issue by holytoastr** [department-of-veterans-affairs/va.gov-team#55315]
## Issue Description
We need to be able to identify which users log in with MHV for both the organic and grandfathering features. Given the adoption service endpoint is hit on the front end, when the front end receives a response, then it should be able to tell if the logged in user is using dsl or mhv, and doesn't have id.me or login.gov CSP.

---
## Tasks
- [x] Identify users who sign in with MHV
- [x] Include MHV users in organic experiment
- [x] show the CSP type so the frontend can decide to show the modal

## Acceptance Criteria
- [x] As an authenticated MHV or DSL user, the API will return the CSP the user logged in with.
---
