### ISSUE TITLE
Establish MHV grandfathering feature flag

### ISSUE THREAD

**Issue by holytoastr** [department-of-veterans-affairs/va.gov-team#55314]
## Issue Description
In order to test and track user groups more precisely for the grandfathering feature, we need a flag to target only users who sign in with MHV

---
## Tasks
- [x] Add `grandfathering_mhv` flag

## Acceptance Criteria
- [x] A `grandfathering_mhv` exists in Flipper
- [x] The flag can be toggled on and off
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
