### ISSUE TITLE
Configure CodeQL for vets-api

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#55317]
## Issue Description
CodeQL is setup in vets-api but it might not be configured and it is currently non-blocking.

Let's make sure it's configured and test it out.

Once we're sure it's working as expected, we'll make it blocking (in another ticket).

---
## Tasks
- [x] Configure CodeQL

## Acceptance Criteria
- [x] CodeQL is configured
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by laineymajor** [comment]
TT1 under the impressions this is already configured as part of pilot. Not certain what team specifically...

**Comment by laineymajor** [comment]
This will be started after the completion of the other 2 tickets Ryan is working

**Comment by laineymajor** [comment]
bringing this back to the top of his list... been on the backburner while other things were being completed.

Ryan doing an hour (tops) of discovery to determine options - will bring to TT1

**Comment by laineymajor** [comment]
Ryan to look into the codeql logs... Rachal seeing an error

**Comment by rjohnson2011** [comment]
CodeQL is erroring on a file that no longer exists. Setting up CodeQL to run on PRs for `master` branch again.

Screenshot of error:
![image.png](https://images.zenhubusercontent.com/5fb40598d06a06671e842a63/6ad3cdc8-4e92-47de-b093-30c5b675dd7a)

**Comment by rjohnson2011** [comment]
CodeQL is running on master branch with default settings and passing. Please reopen this ticket if additional configuration is needed.
