### ISSUE TITLE
Make CodeQL in vets-api blocking

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#55318]
## Issue Description
Once CodeQL is configured and is operating as expected, making it blocking.

---
## Tasks
- [ ] Make CodeQL blocking

## Acceptance Criteria
- [ ] CodeQL is blocking
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by laineymajor** [comment]
@holdenhinkle can you explain more what is meant by 'make it blocking'?? We want to make sure we're on the same page. Thanks!

**Comment by rmtolmach** [comment]
@laineymajor I updated the description to provide more info! :)
