### ISSUE TITLE
[CAIA intake] 10-10CG Facility page

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#55327]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [x] Making revisions to one or more existing VA.gov pages
- [ ] Something else 
 
 *Give a brief description of what your team needs support with.*
- On the 10-10CG Caregiver application, we are revising the Veteran's preferred facility selection page 
     - rewording the question, providing context on why we are asking for the information
     - introducing a free-text search functionality
     - providing a 'confirmation' page showing the facility selection and associated parent facility with Caregiver support (this can be the same facility)

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [x] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
- We are looking to launch some time in June-July
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: [10-10CG Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/10-10CG%20Caregiver%20application%20product-outline.md)
- Link to initiative brief: [Improve Facility Selection Initiative Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/Improve%20Facility%20Selection/Improve%20Facility%20Selection%20-%20Initiative%20Brief.md)
- Link to or attach user flows:  [Wireflows of proposed flow](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/dlyed5l)
- Link to prototype or mockups: 
     - Desktop
          - search input desktop - [https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/jgnAQyo](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/url)
          - search results desktop - [https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/zx9e3Yb](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/url)
          - select desktop - [https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/Jn1QKqr](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/url)
          - confirmation desktop - [https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/4aRZWrd](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/url)
     - Mobile
          - search input mobile - [https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/dlyemEb](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/url)
          - search results mobile - [https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/ZOGQjqp](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/url)
          - select mobile - [https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/v8VZMbM](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/url)
          - confirmation mobile - [https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/eKPGDyq](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/url)
- Link to any epics/issues that may be helpful: 
     - [Artboard with Content brainstorming](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/ZO137w3) - working with Danielle

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: Late June
- Estimated staging review date: Early June
- Content and IA work needed by:  Early-mid April

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Patrick Bateman
-	Product manager: Heather Justice
-	Designer: Jessica Stump
-	FE engineer: Matt Long
-	Product/team Slack channel: #1010-health-apps

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

```[tasklist]
### Content tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/55614
```

**Comment by kristinoletmuskat** [comment]
Confirmed that we don't need a separate IA ticket for this. The only thing that stuck out to me might be out of scope: The stepper shows that we're on step 1 of the process, but there are several sub-steps within step 1 (veteran name, then location, then this facilities selector). As someone walking through the flow for the first time, I was confused and thought maybe the stepper wasn't working, and then once I saw each step had several pages, I wasn't sure how many steps the 5 step process really was!

And one other thought: I think the confirmation screens are really helpful. But I'm unsure what the impact will be on the user if the facility with the caregiver support coordinator is diff from the one my Veteran usually goes to. Will I have to drive there? Or is that just where the coordinator works? Will I have to change my Veteran's facility to be this other one?

**Comment by hdjustice** [comment]
Thank you for this feedback!  We are reviewing and making updates on the Design Intent feedback, so we will put this in there as well.  The stepper has always been an issue for us (we feel the same!), and we have that on our list to address as a whole, which may impact our other application (10-10EZ) and potentially other forms online.
cc @jessicastump @davidakennedy

**Comment by jessicastump** [comment]
Design intent feedback has been incorporated into the following Sketch links:
**Confirmation screen updates:** removed alert, changed link styling for finding a new facility and worked with content on updates
- [Mobile confirmation screen Sketch link](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/GoOPMGE)
- [Desktop confirmation screen Sketch link](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/y98PyLK)

**Accessibility feedback:** Removed pagination and added link to follow Navigate a long list pattern, team decided to not show closed facilities so a disabled radio tile state is not needed, added annotations for focus order
- [Desktop search results Sketch link](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/AZxJmLz)

**Content feedback:** Updates to confirmation screen language above

**Comment by RLHecht** [comment]
@jessicastump We still have a ticket open for our team to give content support. Just confirming that we should still be working on this. Should I reopen this ticket? FYSA @aliyahblackmore

**Comment by jessicastump** [comment]
@RLHecht - As part of the Design Intent phase, we incorporated content feedback received by going to office hours and workshopping only the confirmation page with @DanielleThierryUSDSVA. 
This will still need content support to get through midpoint/staging phases on time, correct @hdjustice? Or would a final content review now be appropriate?

**Comment by hdjustice** [comment]
We opened this ticket as part of the Collab cycle process.  Perhaps I may have been confused by the comment above from @kristinoletmuskat 

> Confirmed that we don't need a separate IA ticket for this. 

Whichever way is best to track this work is fine, I just didn't want an open ticket that wasn't needed.

**Comment by RLHecht** [comment]
Hi @hdjustice I'll reopen this ticket since @aliyahblackmore will post final content and any questions for your team in here.

**Comment by hdjustice** [comment]
Sounds great to me, thank you @RLHecht and @aliyahblackmore!

**Comment by aliyahblackmore** [comment]
Hi @jessicastump - I'd like to move to this work now that the we've wrapped up most of the 1010EZ household work. 

I know that we'd chatted about prioritizing the other field label ask from Katelyn (feedback provided on June 29) and then moving to this.

I'll be able to turn to this when I'm back in office, in early August.

**Comment by aliyahblackmore** [comment]
Hi @jessicastump - I've taken a look at the screens linked above and the initiative brief and have two questions: 

1. Can you confirm what screen comes before the facility selection screens?
2. Will the search for facilities input include the type-ahead function? [Link to this component in the design system ](https://design.va.gov/components/search-input#with-type-ahead)

Thanks so much!

**Comment by jessicastump** [comment]
Hi @aliyahblackmore 
1. Here is a link to the [Mural user flow doc](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687288632872/0728ba8a597b439671741c573fbba777ad0dac16?sender=uadf1ed7fe7c76f0914967329) - before the facility selection screens are the two pages around Veteran information. The facility page is the last page in this section before moving on to the primary caregiver section
2. I think it would but I would need to check with engineering first - I will circle back on this one early next week.

**Comment by aliyahblackmore** [comment]
Thanks @jessicastump !

A few additional questions: 

- When someone searches for a facility, will the page reload at all or will the search options just populate once someone selects the "Search" button? 

- On [this screen](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/zx9e3Yb) with the facilities results, I see that there's a link to find facilities with the VA facility locator if someone can't find their facility in the search. Why wouldn't all facilities show in the search? Will this be a link to an external page? And if so, how would the user making a selection from that external page connect back to the application?

**Comment by jessicastump** [comment]
- Once a search is started / selects button then the locations will populate. This won't preload as far as I know...
- For the second item, there are still some unknowns around the API as far as facilities showing in the search, our hope is to pull in all and map to caregiver facilities. This link to the locator would be to be more to allow for a visual map search, it would open in a new tab just like it does on the EZ side today with the form remaining open (the facilities question is currently the last question of the insurance step on the EZ).

**Comment by aliyahblackmore** [comment]
Thanks @jessicastump !

I'm back with a follow up question about how the facilities will show in the search (considering the fact that there are still some unknowns around the API!):

1. As you mentioned, I took a look at the insurance section in the 1010 EZ and it seems like there's a slightly different use case there - someone can either use the drop down **or** they can use the facility locator link. And it seems like if they use the facility locator link, they'd need to come back to the form and then find the selection based on what showed on the facility locator. So they'd select the state and facility name from the drop down, based on what showed on the facility locator. Is that thinking right?
2. **If the facility search shows all locations**, it sounds like you all want the facility locator link be another way that someone can search and then select in the application screen based on what showed in the facility locator? If so, I'd suggest showing the facility link before the results.  I can provide content suggestions for this. 
- **If the facility search won't show all locations at this time** and the facility locator link is there for someone to search for additional options ("Don't see your facility listed in search?"), how does that map back to the application? From my understanding of the flow, I have a concern about the user experience in this instance since the results for the facility locator (name of facility, state, zip code, etc.) aren't a direct or exact map to the field input options on CG search (city, state, or postal code). Are you all expecting that the user would go through the searches that populated already and match the information to what showed in the facility search (I.e. looking for a name or searching for a name, zip code, etc.) or search again and only enter the state, zip, code or city information that showed in the facility locator search?

Because there are still some unknowns about the API, after getting some more clarity about the above, I'd likely suggest content for two different use cases/scenarios and we can plan to chat more in our meeting on Friday about the flow if someone isn't finding their facility in the application and goes out to the external link!

**Comment by jessicastump** [comment]
Let's talk through this on Friday or happy to meet before too! And maybe this will help.
1. The EZ facility search page is odd and is intended to be updated next and the use cases between the forms are very different. 
2. The goal is to have a zip/city/state input search for locations and not really have to rely on the map at all.  With this discussion, I am wondering if the link should remain on there at all.
3. The hope here is the new api has all locations and has them mapped in a way that works for the Caregiver program. There are basically caregiver point facilities that some smaller facilities map up to, "parent" facilities. There are two different flows, only difference is the confirm facility page for those smaller "child" locations and that is just to provide awareness of the caregiver coordinator location.

**Comment by aliyahblackmore** [comment]
Thanks for providing this info @jessicastump - chatting further tomorrow would be great to confirm I'm aligned with content needs given the API conversation.

- It sounds like I can make content adjustments based on the assumption that there will be a future adjustment to the API to include all locations. And that the adjustment will happen ahead of this page going live. 

- There may be a need for another set of content in the event that not all of the locations populate with the new API (as I know that the API conversation is still ongoing). 

I will plan to walk through some preliminary suggestions tomorrow and looking forward to continued conversation!

**Comment by aliyahblackmore** [comment]
As the Jessica, DK, and Hieu mentioned last week, just tracking here that this work is on pause as we pivot to and prioritize the 1010EZR work!

**Comment by jessicastump** [comment]
Hello - 

An update on the content needs around the CG facilities updates.

Since the initial content request/implementation of this ticket, we have tested this update with caregivers and Veterans and have some updates we would like to make before or right after staging review involving content.

References:
- [Mural for research synthesis, themes and recommendations](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1726173728303/0cf8beb343b2e2ed0a84d4afc9732e3bf40d3ad0)
- [Research findings presentation deck](https://docs.google.com/presentation/d/1fTJCUoxGOa7o3UaOfDEiXxKN2XG4wecwfzbZb3UeL28/edit#slide=id.g892adcb623_0_141)
- [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1731950503702/187f8510c3ff36b6a5f92a5442b77fbc976a93cc) for facilities prioritization
- [Figma page with post-research explorations](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=3575-13565&node-type=canvas&t=umF8sgDK8Yj0LNvB-0)


**The content changes we would like to review are:**
1. Error messages specific to the search input field 
2. Additional content with instructions to search then select a facility
3. Changes to content and order on facility confirmation page

@aliyahblackmore  - I know it is vacation and packed calendar time and we don’t have the usually weekly content sync up for the next couple of weeks — maybe we can chat about this async or find a short half hour next week? :)

**Comment by jessicastump** [comment]
Adding a note per Aliyah's request - the staging review for this work is currently scheduled for 12/12/24.

**Comment by aliyahblackmore** [comment]
Hi @jessicastump 

Thanks so much for sharing the teams redesigns of the facilities screen!

I'll send you a message to find a short time for us to go over the designs. I just want to clarify the specific sections I'll need to update ( I see that there's a "NOW" vs "LATER" section).

**Comment by aliyahblackmore** [comment]
**Update here:** 

Jessica confirmed that I can make content adjustments in[ this section of Figma](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=3592-11039&t=gVmEDvO8Axg8oCTi-4). 

The team will move forward with content adjustments to the redesigns as they are. I'm making content adjustments on those screens and will do one last review tomorrow morning.

I also mocked up an Option 2 with content recommendations for the search screen - that mock up that uses two headers and pulls up the "Note" content about how they'll use the Veteran's facility. These adjustments likely aren't in scope for this V1, but the designers/team may consider those adjustments for a V2/future iteration. I labeled that section accordingly.

**Comment by aliyahblackmore** [comment]
**Update here:** 

- The content recommendations are in the Figma designs. I tracked notes about the content adjustments.
- I noted a few consistency things across the screens  ([using "coordinator" vs. "Caregiver Support Team/Program Team](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK?node-id=3737-11431#1048653656), [add "or clinic" to the form intro page](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK?node-id=3737-11431#1046437730), and [a question](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK?node-id=3737-11431#1048426964) about whether a header above the search selection is in scope for the product team)
- The "Content draft" section has the Option 2 content for the search screens. Those adjustments likely aren't in scope for V1, but they're there for the future.

**Comment by aliyahblackmore** [comment]
**Closing the loop on the question re: the header above the search results** ([cross posting from Figma](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK?node-id=3792-32442#1048426964)):

I chatted about the header with an accessibility specialist on the CAIA team.

- Because it seems like you all are using radio buttons here in this facilities list, she shared that the group of radio buttons needs to be in a fieldset with a legend. This is a screen capture of the code she shared. And this is a [link](https://design.va.gov/components/form/radio-button#label-header) to the VADS guidance.

- So this means that there needs to be a header after the "Showing 1-5" text. I added the header above the search results in the designs. I believe that this is a H3, but can you all confirm this in your design QA.

**Comment by hdjustice** [comment]
This work launched to 100% as of 2/14/2025
