### ISSUE TITLE
Build charts which visualize KPIs for Login.gov Adoption

### ISSUE THREAD

**Issue by sdickson-gt** [department-of-veterans-affairs/va.gov-team#55325]
## Issue Description
Evolve the Login.gov Adoption Dashboard to enhance reporting on the following KPIs
- Number of existing accounts by credential
- Migration segments
- Number of new accounts being created for all creds
- Number of sign ins by week and month (Using VA.gov dataset)

---
## Tasks
**Number of existing accounts by credential**
- [x] Replace and consolidate static numbers with visualizations

**Migration segments**
- [x] Replace and consolidate static numbers with visualizations

**Number of new accounts being created for all creds**
- [x] Revise current visualizations to support additional creds and filters

**Number of sign ins by week and month (Using VA.gov dataset)**
- [x] Analyze sign-in data from VA.gov dataset
- [x] Design solution to retrieve and potentially append data from DataDog and transform as needed to support visualizations
- [x] Create data dictionary
- [x] Create data lineage
- [x] Create visualizations for weekly and monthly data

## Acceptance Criteria
- [x] Updated dashboards

**Comment by sdickson-gt** [comment]
Updated the dashboard with metrics for CSP usage.  TBD if the metrics are currently available to show the authentication events in conjunction with overlap of credentials.
