### ISSUE TITLE
Create Data Dictionary and Data Lineage documents for the data supporting the Login.gov Adoption Dashboard

### ISSUE THREAD

**Issue by sdickson-gt** [department-of-veterans-affairs/va.gov-team#55323]
## Issue Description
As a VA stakeholder for the adoption of Login.gov and abandonment of legacy CSPs, i.e. DS Logon and MHV's CSP, I want visibility and transparency into the data that is driving the Login.gov Adoption Dashboard so that I can have confidence in decisions.

---
## Tasks
- [x] Create and publish a data dictionary document
- [x] Create and publish a data and data model lineage document

## Acceptance Criteria
- [x] documents are published and available for stakeholders
- [x] data dictionary provided context about dataset in Domo and detailed information about fields and information about known quality issues
- [x] data lineage document provides information about the source data and ETL processes used to prepare the dataset for use within Domo
