### ISSUE TITLE
Pull Organic experiment events from GA into DOMO - GA Dev env

### ISSUE THREAD

**Issue by sdickson-gt** [department-of-veterans-affairs/va.gov-team#55329]
## Issue Description
We want to be able to track metrics related to the organic experiment on the Login.gov Adoption dashboard in Domo.  

---
## Tasks
- [ ] Once metrics have been sent to GA, starting with GA Dev env, configure Domo to retrieve the metrics
- [ ] Create a card in Domo to report on metrics

## Acceptance Criteria
- [ ] Card in Domo LGA Dashboard for GA

**Comment by sdickson-gt** [comment]
able to pull data from Google Analytics.  Dependent on resolution of getting events into GA.

**Comment by sdickson-gt** [comment]
@elizabethkochBT GA can map metrics to a campaign used to acquire users. If we want to use this, we need a story to do a proof of concept in advance of an actual campaign.
