### ISSUE TITLE
Define how we get a user back to their original task before they were interrupted

### ISSUE THREAD

**Issue by MOStudioCarolyn** [department-of-veterans-affairs/va.gov-team#55332]
## Tasks
- [x] Discuss pros and cons of new tab opening with accessibility expert Martha Wilkes or Brian DeConinck
- [x] Discuss interruption scenarios with engineers
- [x] @carl check on recurring meeting with Sitewide IA (if we don't have one, should we schedule one?)

## Acceptance Criteria
- [x] Document recommendations in shared [Login.gov transition Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1676397151510/f4cf4f4187a3d0fd5f2d6d56c9bd2ba3a4376e7a?sender=u1e2c263656ad89ecadb41603)

**Comment by tygindraux** [comment]
Suggest chatting to Brian DeConinck (Platform Accessibility) about this.

**Comment by MOStudioCarolyn** [comment]
Biweekly meeting with Sitewide IA has been scheduled, after meeting March 23, we were left with some technical questions around new tabs. Met with engineering team March 28 to determine pros/cons, and determined not to use a new tab. This has been documented in the Login.gov Transition Mural

**Comment by skirkman16** [comment]
Spoke with our developers and determined that one tab will be used when users create a Login.gov account. This is to prevent the potential of data loss and to make the mobile experience more accessible and user friendly. The devs also explained that when users create a Login.gov account, their DSL session is terminated so the users will not be timed out of their account creation. If the users exit the account creation flow or complete it, they will be navigated back to VA.gov so that they may complete their original task
