### ISSUE TITLE
Start preparing for deferred identity proofing accessibility testing

### ISSUE THREAD

**Issue by MOStudioCarolyn** [department-of-veterans-affairs/va.gov-team#55336]
## Tasks 
- [ ] Discuss with Steve Dickson/Ksenia what needs to be prepared for working prototypes to be created for accessibility testing
- [x] Reach out to Martha Wilkes or other Sitewide accessibility expert to determine best VA practices for conducting accessibility research

## Acceptance Criteria
- [ ] Document results from conversations

**Comment by MOStudioCarolyn** [comment]
Reached out to Martha Wilkes 4/12. Waiting to hear back.

**Comment by MOStudioCarolyn** [comment]
Martha sent over pages of documentation on the VA Platform site. 
[Conducting research with assistive technology users](https://depo-platform-documentation.scrollhelp.site/research-design/research-with-assistive-technology-users)
[Accessible prototyping with CodePen](https://depo-platform-documentation.scrollhelp.site/research-design/accessible-prototyping-with-codepen)

**Comment by tygindraux** [comment]
Let's discuss whether this is blocked/moved to the backlog given new priorities. (Adding this here as a reminder to myself and others).

**Comment by tygindraux** [comment]
We've created a new ticket about accessibility testing modal components, which covers this ticket. I'm going to close this ticket and link it to the new/more complete ticket.
