### ISSUE TITLE
10-10 Health Apps team onboarding - Alex Seelig

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#55347]
## Background
As a new team member joining the 10-10 Health Apps team, I need to become familiar with the 10-10 products, current designs, workflows, and research.

### Resources
- [Team Charter](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/caregiver/team-charter.md)
- [10-10 Team ZenHub board](https://app.zenhub.com/workspaces/vsa---10-10-team-5fff0cfd1462b6000e320fc7/board)
- [10-10 Team Sprint Planning document](https://docs.google.com/presentation/d/1ASalrxCcn-SXoNzz7ueIYQws97O6ROkXZznVch1mF-c/edit)

**Our Products**
- 10-10CG - Caregiver support program application
     - [10-10cg Transition Hub folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/caregivers/Transition%20hub)
     - [10-10cg Product Folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/caregivers)
     - [Staging Env - CG Form on VA.gov](https://staging.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction)
- 10-10EZ - Veteran health care application
     - [10-10ez Transition Hub Folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/Transition%20hub)
     - [10-10ez Product Folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application)
     - [Staging Env - EZ Form on VA.gov](https://staging.va.gov/health-care/apply/application/introduction)

### Testing details
- [Test User credentials document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)

### Tools
<details>
<summary>Onboarding tools checklist</summary>

# Team Onboarding Checklist

Reference the [VA Platform Tools site](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-tools) for detailed information and more links for gaining access

- [x] VA.gov Email set up
     - Completed by COR
- [x] GitHub account, associated to VA.gov email address
- [x] Add to VA Org - [Request Ticket](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=&labels=add-user-to-org%2Cnew-user%2Cuser-created&template=add-user.yml&title=Add+User+to+Org%3A+%5Busername%5D)
- [ ] Add to VA.gov-team Repo - [Request ticket](https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html#Requestaccesstotools-GitHub)
- [x] Add to [ZenHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/zenhub.md) (if applicable)
     - Add to workspace
     - Ensure connected with GH account
     - Chrome extension (if desired/needed)
- [x] Add to DSVA Slack instance - [request ticket](https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html#Requestaccesstotools-Slack)
     - [x] 1010-health-apps
     - [x] health-tools-1010-apm
     - [x] vecms-carma_vadotgov_development_external
     - [x] vfs-change-announcements
     - [x] vfs-platform-support
     - [x] vfs-all-teams
     - [ ] feedback-backchannel
     - [x] (PMs) team-of-teams-slide-collection
     - [ ] (Design.research) design

- [ ] Design/Research
     - [ ] Add to Mural - OCTO PO to submit [DOTS request](https://login.max.gov/cas/login?service=https%3A%2F%2Fvajira.max.gov%2Fservicedesk%2Fcustomer%2Fportal%2F1%2Fcreate%2F18)
     - [ ] Add to Sketch
          - To access Sketch for Teams, contact Kevin Hoffman in the #design Slack channel. 
     - Add to 

- [ ] Analytics
     - [ ] Google Analytics/Domo ([same request ticket for both](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo))
     - [ ] Datadog - [directions for access](https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog)

- [ ] Development
     - [ ] [SOCKS](https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy) (confirm with DM/PM on pre-reqs before requesting, must have e-QIP transmittal date)
     - [ ] [Jenkins](http://jenkins.vfs.va.gov/) (used with SOCKS proxy running)
     - [ ] [Sentry](http://sentry.vfs.va.gov/) (used with SOCKS proxy running)
     - [ ] [Grafana](http://grafana.vfs.va.gov/login) (used with SOCKS proxy running)
     - [ ] AWS Console - [Request Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose)
          - If you aren't sure you need AWS Access, don't request it until you determine that you do need it.

- [ ] Testing
     - [ ] [TestRail](https://dsvavsp.testrail.io/index.php?/auth/login/)
          - Team has a shared account, check with PM
          - [User Guide](https://www.gurock.com/testrail/docs/user-guide/getting-started/)

</details>

### Tasks
- [ ] Meet the team
  - Heather Justice (PM)
  - Matt Long (FE)
  - Lihan Li (BE)
  - Jessica Stump (UX Design/Research)
  - David "DK" Kennedy (UX Design/Research, A11y focus)
  - Erin Flaherty (QA Engineer)
- [ ] Review the Product Folders
     - Research documents are the best source to see what feedback we got from veterans and caregivers on the application forms
- [ ] Click through each of the forms in the Staging Environment, to become familiar with the layout, content/verbiage, and think of how a veteran or caregiver might experience filling out the form.
- [ ] Reach out to any teammates with questions, if applicable

## Expected Result
- I will have a base knowledge of the products that the team is responsible for and can start to move forward on the work in progress and up next.
