### ISSUE TITLE
[Epic] Profile 2.0: IA plan and review

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5534]
## User story

As a person looking for my VA.gov profile, the wayfinding to/in the profile needs to make sense so I don't get lost.

## Additional background

We need to make sure we have a plan for the URLs leading to/in the profile and any redirects that need to happen, and we need to make sure the URL suggestions we have match our current URL structure requirements.

## Tasks

- [x] Consolidate any redirects/link updates that need to happen from #5518 into one list. #5536
- [x] Propose IA/URL plan for the profile itself #5538
- [x] Review all of the above with Mikki (ticket to be created later)

## Acceptance criteria

- [x] We have a plan for URLs and redirects that has been approved by Mikki and can be passed off to FE.

**Comment by Samara-Strauss** [comment]
Looks like all the tickets got close but not the epic. Closing!
