### ISSUE TITLE
Fix the parsing of the vagov_info_token cookie

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#55344]
## Description
Currently on VA.gov when the Sign in Service is used to authenticate the `vagov_info_token` cookie is created as a consumable cookie for the Frontend to get the session expiration.  In this [Slack thread](https://dsva.slack.com/archives/C04LW2P19M0/p1679071286746689) we want to change this so we can more easily extend our services to others.

**Note, this effort needs to be coordinated launching with vets-api so reach out to a backend engineer before merging in a Pull Request into vets-website

## Tasks
- [x] Modify the `formatInfoCookie` function to parse the string as JSON instead of the custom parsing
- [x] Update unit tests as necessary
- [x] Work with BE team to ensure the PR + their PR is deployed around the same time

**Comment by rileyanderson** [comment]
New token value example:
```json
{
  "access_token_expiration": "2023-03-17T19:17:31.089Z", 
  "refresh_token_expiration": "2023-03-17T19:29:11.093Z"
}
```
