### ISSUE TITLE
Get designs ready for midpoint review (organic adoption)

### ISSUE THREAD

**Issue by tygindraux** [department-of-veterans-affairs/va.gov-team#55358]
## Issue Description
Get designs ready for midpoint review (organic adoption)
---

## Tasks
- [ ] update prototype to mobile interface
- [x] update content based on sitewide feedback

## Acceptance Criteria
- [ ] Attach artifacts to the midpoint review ticket (Collaboration Cycle for Login.gov adoption team, Organic Adoption #54326)

**Comment by tygindraux** [comment]
@elizabethkochBT suggest closing this since there's another ticket for mockup in mobile (also the midpoint review will be on the core team now...)
