### ISSUE TITLE
Initial Documentation for "View and Update My Representative"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#5535]
## Goal
As they relate to existing application features, we want to capture as much information about the known metrics and stakeholders and document them.

## Tasks
- [x] Schedule and conduct a walk-through of the feature and paper form by Steve
- [x] Understand the functions and how they map to the user stories and experience seen in the Epic
- [ ] Document in GH as an .MD file these findings for future reference

## Acceptance Criteria
- [ ] An .MD file has been created in the feature repo root and includes the items above

**Comment by wygonikGCIO** [comment]
Link to GH document 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-POA/research-design/Mapping-POA-features-and-functions-to-user-stories-and-experience.md
