### ISSUE TITLE
Revise standard descriptions for VAMC Drupal taxons

### ISSUE THREAD

**Issue by megzehn** [department-of-veterans-affairs/va.gov-team#55364]
## Issue description

Revise standard VAMC descriptions based on what we used [for Lovell in this ticket](https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/53043).

## Tasks
- [x] Copyedit and review for plain language (Megan)
- [x] Send to Steve (Megan)

## Acceptance Criteria
- [x] Descriptions are written in plain language and meet VA.gov style standards

**Comment by megzehn** [comment]
Confirming that I copy edited the list from Lovell and sent it over to Steve. 

I also checked the reading levels of the descriptions before and after the edits, and they went from grade 13 to grade 10. 

I don't think this was a complete list of descriptions, since this was just the list from Lovell. We may want to open a backlog ticket to review the rest of the descriptions.

**Comment by megzehn** [comment]
@RLHecht I think we can close this one out. You can keep this one at a 2.

**Comment by RLHecht** [comment]
Thanks, Megan. Closing!
