### ISSUE TITLE
Develop content for email outreach to users that already have ID.me/Login.gov

### ISSUE THREAD

**Issue by CarlDickerson** [department-of-veterans-affairs/va.gov-team#55362]
### Description
In support of the plan to remove DS Logon as an option for signing in, awareness content needs to be developed to communicate this change to various user groups. This particular work will focus on Users who may have DS Logon, but in addition already have an ID.me or Login.gov account that works with VA (we know because they have used it to sign in previously at some point). They will not need to be migrated, but will need to understand that DS Logon will no longer be an option for logging into VA digital tools and that moving forward they should use their ID.me or Login.gov credentials.

### Acceptance criteria
- [x] Content is drafted in Figma
- [x] Content has been shared with team

### Tasks
- [x] @CarlDickerson draft first pass of email outreach content
- [x] @CarlDickerson socialize with LGA team
- [x] @CarlDickerson socialize with Sitewide Content Team

**Comment by CarlDickerson** [comment]
Attaching link to do design files here: https://www.figma.com/file/8vobVoSl1UqLnXsni3rcvO/Login.gov-Adoption%3A-Design-Flows?node-id=1187%3A4055&t=NXvkVQndN5CJggjv-1
