### ISSUE TITLE
Create Workflow Diagram of Existing Application ("View and Update My Representative")

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#5537]
## Goal
Create a high level view of the workflow a Veteran might take to view and update their representative.

## Considerations
- Note any functions that are outside of the regular path as well as any potential improvements we might make.

## Tasks
- [x] Create a thumbnail view of the workflow with notes on alternate paths mapping the known intended functionality.
- [x] Share with IA for url/page placement, as needed or at kickoff

## Acceptance Criteria
- [x] A high level workflow has been created
- [x] Share with IA (Mikki) for confirmation, as needed or at kickoff

**Comment by wygonikGCIO** [comment]
Workflow diagram 
![eBenefits current workflow@2x (1).png](https://images.zenhubusercontent.com/5d9cd59bb6de6d00018d4a32/2bb9ce7b-af56-459d-9e1e-e93137c2f076)
