### ISSUE TITLE
Copyedit content-standards changes for "Mustard gas or lewisite exposure" for annual audit

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#55378]
## Issue Description
For the annual audit of all the pages in the disability hub, OCTO content leads assessed these 7 content issues on the [Mustard gas or lewisite exposure](https://www.va.gov/disability/eligibility/hazardous-materials-exposure/mustard-gas-lewisite/) page and made changes that need copyediting before we republish the page:

- The intro paragraph has no more than 2 to 4 sentences and is within 200 to 400 characters with spaces
- Header levels are hierarchical
- The page has no broken links
- Link text has a purpose and target
- The content is free of ability-focused language (view, walk, see, hear)
- Relevant terms from page are in content brief and any relevant backlog work is noted
- Remove "Who's covered?" section (if needed)
- Remove "What kind of disability benefits can I get?" section (if needed)

---
## Tasks
- [x] Copyedit the changes made (review revisions only, not the full page) to https://www.va.gov/disability/eligibility/hazardous-materials-exposure/mustard-gas-lewisite/
- [x] Publish page.

## Acceptance Criteria
- [x] Updates are live on the site.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by megzehn** [comment]
Confirming I reviewed these changes. Thank you @bethpottsVADEPO and @DanielleThierryUSDSVA for setting this up and making the edits!

**Comment by megzehn** [comment]
Reopening this ticket, because we made a few other changes to the featured content to be more consistent with other pages (shortened it). The SME signed off on those changes, so we are OK to publish them.

But... I realized as I was about to publish that there is a broken link: 

[Visit the U.S. Army website for more information](https://armymedicine.health.mil/CBTP)

@bethpottsVADEPO should we check with Matt to see if there's a better link for us to use? I'm not sure how to find the best replacement.

**Comment by megzehn** [comment]
Update: We removed the broken link, so this issue is resolved. Closing!
