### ISSUE TITLE
Profile 2.0: Propose IA/URL plan for the profile itself

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5538]
## User story

As a person looking for my VA.gov profile, the wayfinding to/in the profile needs to make sense so I don't get lost.

## Additional background

Epic #5534

For tracking purposes - here is the [slack conversation](https://dsva.slack.com/archives/C909ZG2BB/p1588356623483500) we had around breadcrumbs.

## Tasks

- [x] Create plan for the main URL in the profile (is it /profile? does /profile redirect to /profile/contact-information?)
- [x] Create a proposal for the URLs for each section of the profile
- [x] Review initial proposal with Samara

## Acceptance criteria

- [ ] Proposal is complete and ready for review with Mikki

**Comment by tressaellen** [comment]
Hi @Samara-Strauss, I'd love to get your thoughts on this URL plan whenever you have a minute. ![Screen Shot 2020-05-27 at 10.58.58 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/27cebff7-8129-4a9b-9f42-d77d494e1e52)

**Comment by Samara-Strauss** [comment]
That looks great to me. Idk if this is already in your notes, but /profile should automatically redirect to /profile/personal-and-contact-information.

**Comment by tressaellen** [comment]
I just added a line at the top for clarification. Thanks!

<img width="574" alt="Screen Shot 2020-05-28 at 10 38 41 AM" src="https://user-images.githubusercontent.com/58752772/83180140-70d67a00-a0cf-11ea-90c0-8e3c09c0bc2e.png">
