### ISSUE TITLE
Connect with Jesse House on deprecating GitHub files

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#55389]
## Issue Description
Governance has brought to our attention a couple of times when a Github page was missing a deprecation message. All of our team members are new, therefore, we have no historical knowledge of how this was done.

It has been shared that Jesse House, PM for Tech Team 2, may have more historical knowledge on:
- The Platform website migration
- Files we could prioritize
- How to mass move files within GitHub
- How to add the messages to files correctly, including how to commit directly to the main branch or other workflows

---
## Tasks
- [x] Schedule 30 minute meeting with Jesse House to gather more information based on the notes above; **Scheduled for Monday, April 17.**

## Acceptance Criteria

- [x] PM will understand how to add a deprecation message onto a GitHub file

- [x] PM will have a general understanding of which files in GitHub need to be retired
