### ISSUE TITLE
Copyedit taxonomy of toxic exposures for VHA digital media team

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#55388]
## Issue Description

VHA digital media opened an intake request for us to do a content review of the toxic exposures taxonomy to add as a health service to VAMCs. 

Our team should do a copyedit similar to the taxonomy review we did for Lovell. 

Word doc provided: [https://app.zenhub.com/files/133843125/bda06c30-1311-4a46-8aa7-d46fb7d9a5ed/download](https://app.zenhub.com/files/133843125/bda06c30-1311-4a46-8aa7-d46fb7d9a5ed/download)

Original intake ticket for background: #55187

## Tasks
- [x] Copyedit taxonomy (Megan)
- [x] Provide final content in original intake ticket (Megan)

## Acceptance Criteria
- [x] VHA digital media has final content

**Comment by megzehn** [comment]
Thanks, @RLHecht. I've copy edited the text [in this sharepoint doc.](https://dvagov-my.sharepoint.com/:w:/g/personal/megan_zehnder_va_gov/Ef_MrQ5fbvxKn3qrfFYUFIYBemLGZEPiyOLvoRZOT9XPjg?e=4VNYLn)

I'll share the link and the final text on the intake ticket.

**Comment by RLHecht** [comment]
Closing this out. Putting 2 as the actual for work time as well.
