### ISSUE TITLE
Improve clarity re: 2 or 4 day window for Collab Cycle touchpoints in Calendly

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#55391]
## User Story
As a Governance team member, I want to make sure that VFS teams are scheduling Staging Review with the sufficient 4 day window so that I only infrequently have to interfere and ask them to reschedule.

 As a VFS team member, I want to make sure I am scheduling my Staging Review with at least 4 days notice for the Governance team so that I am not asked to reschedule. 

Assignee: @allison0034 
Peer Reviewer: @shiragoodman 

## Description
Over the last month, we have had to contact VFS teams post-scheduling of their Staging Review to ask them to choose a different date/time as their original date did not give Governance team at minimum 4 days notice. The reason this is happening is because Calendly, the tool used for scheduling all Governance team Collaboration Cycle meetings, does not use a business day calendar. The settings in Calendly are set to only allow VFS teams to schedule an event when it is at minimum 4 days from the current date/time. However, when VFS teams visit the Calendly site on a Friday, the Tuesday and Thursday time slots on the following week are options because Calendly counts both Saturday and Sunday as calendar days. Shira has previously contacted Calendly to ask them to implement a business day calendar, however it has not occurred yet.

In addition, the Design Intent/ Midpoint Review Calendly event asks for 2 full days notice. Although it hasn't occurred often, it is possible that a VFS team may try to schedule the Monday or Tuesday time slots on a Thursday or Friday, again not giving the Governance team a proper 2 full days notice. 

The purpose of this ticket is to introduce manual checks within our operational process so that Governance team members know when and how to notify VFS teams that their review will need to be rescheduled due to lack of 2 and 4 day minimum notice. This ticket will also add language to Calendly so that VFS teams are more visibly aware of the 2 and 4 day minimum notice, so that they schedule touchpoints within the 2 or 4 day window less frequently.

In addition, we will combine the pre-scheduling and Scheduling steps for DI, MPR and SR as it is not clear when the pre-scheduling steps should be followed. All steps needs to occur at once.

## Impacted Artifacts
[Staging Review - VFS - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review+-+VFS+-+Moderator+Responsibilities)
[Midpoint Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Moderator+Responsibilities)
[Design Intent - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Moderator+Responsibilities)
[Calendly event for DI and MPR](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review?month=2023-04&date=2023-04-10)
[Calendly event for SR](https://calendly.com/collaboration-cycle/staging-review?month=2023-04)

## Tasks
- [x] Create draft pages for all Moderator responsibility docs
- [x] Merge pre-scheduling and scheduling. Remove any unnecessary steps 
- [x] Add step for checking to see that VFS Calendly event is outside of 2 day window for DI and MPR and 4 day window for SR
 - Note: as stated in description, it's likely that VFS teams will schedule inside the window if they schedule on a Thursday afternoon, Friday or anytime over the weekend. Not sure if we wnt to add that note, but FYSA.
- [x] Connect with Shira for adding a note to Calendly for both the DI/MPR event and SR event.
- [x] Change Calendly link checkbox: I understand that I must notify the Platform Governance team via the #vfs-platform-support Slack channel at least 2 business days in advance that I have scheduled this event, per the guidance in the Collaboration Cycle Request ticket.
 

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] VFS teams are notified that they may be asked to reschedule their touchpoint if scheduled within the 2 or 4 day window
- [ ] Governance team has a process in place to check to see if events are scheduled within the 2 or 4 day window

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
I have draft pages made in [this folder](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2584772611/55391+-+Allison+-+Calendly+window).

**Comment by shiragoodman** [comment]
@allison0034 this looks good to me. The only thing we may want to add is stating that Calendly doesn't recognize business calendar days. If you want to add it, great. but honestly, I don't think it's 100% necessary.

You can publish this.

**Comment by allison0034** [comment]
@shiragoodman everything is publish, give one final review and then I can close.

**Comment by shiragoodman** [comment]
@allison0034 looks good!
