### ISSUE TITLE
Competitive Analysis of "View and Update My Representative"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#5539]
## Goal
We want to get initial impressions, design hypothesis and simple field research/competitive analysis in place to move the feature forward in serving the Veterans needs.

## Tasks
-  [x] Document in GH any initial impressions on the existing features and paper form and what might change as the feature is transformed in to VA.gov.
- [x] Document in GH our design hypothesis that shows how we might be able to implement the feature using existing design patterns and practices.
  - For example, perhaps View and Update are on the same page?
- [x] Document in GH existing field research, if any.  Include findings from discovery sessions

## Acceptance Criteria
- [x] An .MD file has been created in GH in the feature research repo.

**Comment by sporeboy** [comment]
Made changes to formatting:
- "Intro" section at top
- Headings
- Some verb tense
- punctuation/capitalization
- Moved stories to end of sections

**Comment by sporeboy** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-POA/research-design/Mapping-POA-features-and-functions-to-user-stories-and-experience.md

**Comment by wygonikGCIO** [comment]
Link: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-POA/research-design/POA-competitive-analysis.md
