### ISSUE TITLE
Collaboration Cycle for Authenticated Experience My VA, My VA: Notification design system component

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#55405]
### VFS team name

Authenticated Experience My VA

### Product name

My VA

### Feature name

Notification design system component

### GitHub label for product

my-va-dashboard

### GitHub label for feature

onsite-notifications

## Kickoff questions

<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

Design and acceptance to design system library - Q3 2022, Development on component to begin March 2023

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

No

### Will your work involve changes to...

Other

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications#product-outline-on-site-notifications-ie-personalized-notifications-that-show-on-vagov

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Notify the Collaboration Cycle team of this ticket in the vfs-platform-support Slack channel.

- [X] I acknowledge that I must notify \#vfs-platform-support after submitting this issue.

[Kickoff Slack thread request](https://dsva.slack.com/archives/CBU0KDSB1/p1679325221280049)

</details>

### Design Intent

<details>
  <summary>Toggle Design Intent instructions</summary>

##### VFS team actions
- [ ] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [ ] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [ ] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.
  
**Design Intent artifacts for review**

[See guidance on Design Intent artifacts.](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts) Governance Team feedback is based on the artifacts provided here as well as information provided during the meeting. Please provide links to artifacts **at least two business days** before the scheduled meeting.

Required:
- [ ] User flow

Not required, but nice to have:
- [ ] Wireframes (if provided, must include mobile wireframes)

Optional:
- [ ] Research plan
- [ ] Any other artifacts you have so far
  
##### Governance Team actions
- [ ] Design Intent Slack thread with VFS team
- [ ] Meeting date/time:
  
##### Governance Team actions

- [ ] Update this ticket with the Zoom recording
  - Recording link
  - Passcode:
- Accessibility
  - [ ] Feedback ticket attached
  - [ ] No feedback
- Design
  - [ ] Feedback ticket attached
  - [ ] No feedback
- IA
  - [ ] Feedback ticket attached
  - [ ] No feedback
  
##### VFS team actions

- [ ] Review feedback tickets. Comment on the ticket if there are any questions or concerns.
  

</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [x] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [x] Link to the Readiness Review [ticket (#1000)](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1000) 

#### Platform actions
- [x] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by ajakabcin** [comment]
Hi @allison0034 - [per guidance from Matt Dingee](https://dsva.slack.com/archives/C909ZG2BB/p1666821374143059?thread_ts=1666811158.866349&cid=C909ZG2BB) we're actually going to skip Design Intent for this feature since we've pretty much already done that exercise with DSC. However, I did link the relevant artifacts in the section. Thanks!

cc @shiragoodman @BerniXiongA6 @Samara-Strauss @aagosto90

**Comment by humancompanion-usds** [comment]
Guidance and Sketch assets are now available: https://design.va.gov/components/notification

**Comment by ajakabcin** [comment]
Closing this out - this feature was removed from production and deprecated from the design system
