### ISSUE TITLE
Conduct Discovery Research Session for "View and update my representative/ View payments"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#5540]
## Goal
We want to conduct some discovery sessions with users to gain insight as to features currently in use and any pain points.

## Considerations
- We will need a research plan and conversation guide with Lauren Alexanderson's approval, abiding by the [latest design process]( https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/vsa-research-process.md) guidance.
- Schedule with Perigean and obtain some users to chat with.
- Conduct sessions
- This may include a few questions regarding "View my payment history"
- There will be a practice session before a pilot session

## Tasks
- Include a pilot session before live sessions

## Acceptance Criteria
- [x] Perigean has been contacted after this smaller, initial user discovery research plan has been approved.
- [ ] Conduct sessions with feedback from Shawna and Lauren Alexanderson
- [ ] Summary docs at conclusion using Mural
