### ISSUE TITLE
Analytics - Identify flow points of low ratings

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#55409]
## Issue Description
   As Product team, I would like to understand what points of benefits claims workflow causes the users to give it 1 or 2 star rating so that we can focus improvement ideas towards mitigating those pain points.
     
Nyantee - The analytics team was able to show me how to dissect some of the data in the DOMO dashboard to understand where users were most likely to click the feedback button which could add some granularity to understanding where pain points are occurring

## Dependencies
- [ ] Ability to access URLs listed in DOMO and link them to actual 526 screens for analysis 

---
## Tasks
- [ ]  Document URLs for 526 screens that have received 1 or 2 star rating. Analyze for pain points. 

## Acceptance Criteria
Analysis report 
- [ ]  Identifying points/pages on the 526ez form flow where users have given 1 or 2 * ratings 
- [ ] Analysis of all ratings for these pages

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Nyanteea** [comment]
As intercept survey are launched to users after they have been on the from 20 seconds, any ratings collected only reflect user experience of the first few pages of the form -- mainly introduction and start pages. Excel sheet of the data is linked below.

**Comment by Nyanteea** [comment]
[https://app.zenhub.com/files/133843125/99a6d9fb-24f6-43d9-969b-147324554c40/download](https://app.zenhub.com/files/133843125/99a6d9fb-24f6-43d9-969b-147324554c40/download)

**Comment by Nyanteea** [comment]
[https://app.zenhub.com/files/133843125/06e53a95-5e4e-495d-84da-ecd6948e7265/download](https://app.zenhub.com/files/133843125/06e53a95-5e4e-495d-84da-ecd6948e7265/download)
