### ISSUE TITLE
Audit Staging Review issue tickets with "Other" category

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#55401]
## User Story
As a VFS team member, I want to know the complete list of VA.gov Experience Standards that I must adhere to so that I can ensure that my product is ready for Staging Review.

As a Governance team member, I want to make sure the VA.gov Experience Standards list is as accurate as possible so that when I find an issue during a Staging Review, I know what VA.gov Experience Standard it is in violation of and no longer have to use the "Other" category.

Assignee: 
Peer Reviewer: 

## Description
As of 6/28/2022, the Governance team has flagged [26 issues ](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aopen+is%3Aissue+label%3ACC-Dashboard+label%3ACCIssue00.00) with the Category of "Other" stating the issue, "No VA.gov Experience Standard for the issue found." This category/issue is used as a catch-all so that Governance team members can still flag their concerns at a Staging Review, even if there isn't a VA.gov Experience Standard that fits the issue found perfectly.

However, since 26 issues have accumulated, it would make sense that we now audit those issues to see if:

1. They could've been mapped to a more appropriate, already documented VA.gov Experience Standard, OR
2. There is a gap in the VA.gov Experience Standards that must be addressed (AKA create a new standard)

## Impacted Artifacts
[Platform Website: VA.gov Experience Standard](https://vfs.atlassian.net/wiki/spaces/CC/pages/1683980311/VA.gov+experience+standards)
[Drafting Template Source](https://docs.google.com/spreadsheets/d/1IkIX7CgbFneFvlia1r9mYD8QU7uML5HWILkM7qsxizs/edit#gid=333168944)

## Tasks
- [ ] Create a [working document](https://docs.google.com/spreadsheets/d/1A9pw-k4AKErWQhFJjBDmKgCfH80lrFvHLyQpnE1ByO0/edit#gid=0) to review the "Other" issues. Capture the following:
   - GitHub issue #
   - Date of ticket
   - Governance team reviewer
   - Governance team reviewer practice area
   - 1 sentence summary of issue found
   - Possible VA.gov Experience Standard (if applicable)
- [ ] Share on #platform-governance-team Slack channel and ask for team review. If your practice area opened the "Other" issue, confirm the following:
   - 1 sentence summary is accurate
   - If there is a Possible VA.gov Experience Standard, confirm that the summary and Possible VA.gov Experience align. If not, comment on the ticket with your thoughts/opinion
   - If there is NOT a Possible VA.gov Experience Standard, review the VA.gov Experience Standards list and validate that there is not a Va.gov Experience Standard that aligns with the summary. If there is a VA.gov Experience Standard that aligns, comment on the ticket with your thoughts/opinion
- [ ] If any "Other" issues _almost_ align to the existing VA.gov Experience Standard, comment in the working document. It may be best to modify the existing VA.gov Experience Standard.
- [ ] If anything needs OCTO escalation, share on #platform-collaboration-cycle Slack channel
- [ ] Once team is in agreement for the issues with aligned Possible VA.gov Experience Standards, update the labels on the ticket:
   - remove label `CCIssue00.00`
   - add the appropriate new label `CCIssue.XX.YY`per [VA.gov Experience Standards labels guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket#AnatomyofaStagingReviewIssueticket-VA.govExperienceStandardslabels)
   - Update the Platform Issue section in the ticket with the appropriate new name per [Platform Issue guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket#AnatomyofaStagingReviewIssueticket-PlatformIssue)
   - Comment on the ticket:

> This ticket has been reassigned from CCIssue00.00 "No VA.gov Experience Standard for the issue found" to CCIssueXX.YY "Name of issue". No VFS action is needed.
- [ ] If there is no Possible VA.gov Experience Standard listed for the issue, then it is likely than a new VA.gov Experience Standard will be created. No action is needed on the Github ticket. Create individual issue tickets (for Governance team to address) for each new VA.gov Experience Standard and link them all below: 
 - 
Note: it is possible that there may not need to be 1 new standard for each issue that doesn't currently have a VA.gov Experience Standard to map back to. 2 "Other" issues may have the same summary which would mean only 1 new issue ticket is needed for Governance team.

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have reviewed all "Other" tickets and either reassigned them to an appropriate VA.gov Experience Standard or created a ticket in our backlog for the creation or update of a new VA.gov Experience Standard.
- [ ] VFS teams are notified if/when their existing issue tickets have been reassigned  a new VA.gov Experience Standard

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by sterkenburgsara** [comment]
@shiragoodman Fwiw I did a quick, high-level audit of the tickets with label 00.00 in developing the affinity map for Experience Standards. [Cards in orange on the Mural ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687405248108/d062ed36c1e5191571492e64cfe61ac87c02c9fc?sender=uf94a77a19aaf687331c09367)represent the ticket title (or description when ticket title was not unique) of the "Other" use cases. The following issues were repeated 2+ times: 

* Content or page behaviors not being announced by screen readers - **5 times**
* Issues with keyboard focus management - **5 times**
* Unnecessary screenreader text and/or aria elements (overly verbose / not efficient) - **4 times**
* Bugs with the product - **4 times**
* Single-click destructive action without confirmation step - **3 times**
* No warning given for opening link in new tab (Has also been recorded several times as: 4.07 components pattern standards (issue with following URL guidance for external links)) - **3 times**
* Data tables missing caption elements - **2 times**

Other uses for 00.00 include these isolated findings: 
![Screenshot 2023-07-05 at 12.26.03 PM.png](https://images.zenhubusercontent.com/6346cd7ec508fe43b65ae3db/b70572b3-df45-491c-84f4-73cff7378c5f)

**Comment by shiragoodman** [comment]
thanks @sterkenburgsara . Sorry, somehow I am just seeing your comment above. I think we made the right call sorting them into our new categories.

**Comment by shiragoodman** [comment]
closing this ticket as the 00 issues were recategorized in our workshop.
