### ISSUE TITLE
Mocked authentication FE Docs

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#55415]
## Description
Create documentation for the mocked authentication workflow on dev.va.gov

## Tasks
- [x] Create documentation on
  - [x] Routing (which routes)
  - [x] User flow (full flow from FE to BE)
  - [x] Modifying user via Rails FE

**Comment by mjconw3** [comment]
Looks good @asg5704 gonna close this out
