### ISSUE TITLE
[Research] Prepare Research plan for HLR Desk research

### ISSUE THREAD

**Issue by uxgary** [department-of-veterans-affairs/va.gov-team#55446]
## Description
Create a research plan to focus our research efforts around aligned objectives and goals. At the end of this ticket, our team will be prepared to conduct research.

## Definition of done
The plan should include objectives, goals, outcomes and research questions.

## Tasks
- [x] Define if this plan is for desk research or user interviews
- [ ] Compose research questions based on research method
- [ ] Draft research plan
