### ISSUE TITLE
Set up Annotations/Design Specs Page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#55458]
## Description 
Document design, functional or other specifications on specific symbols and page components to engineers, designers, product owners and other stakeholders.

For example:
* Heading classes to be used. E.g., when the markup needs to be a different heading than the actual heading design.
* Use of mobile headings vs. desktop headings.
* Notifications do not stack. But, on page refresh, check to see if there's an appointment in the check in window.

## Tasks
- [x] Set up an annotations/design specs page
- [x] Consolidate notes/decisions on this page
- [x] Have a co-working session with the engineers to fill in the gaps of missing aria labels
- [x] Create f/u ticket(s)

**Comment by zach-park** [comment]
@Ya-ching and I met and the [Annotations/Design specs](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/3E175577-7AE3-4FDF-A037-7265F09C1775/canvas#Version) are ready for co-work/share with engineering. @ytsaoca @benbrasso-agile6 @cgednalske @kellysmith1008

**Comment by benbrasso-agile6** [comment]
Cool. Going to tag @cgednalske to validate too!

**Comment by benbrasso-agile6** [comment]
We have structure. Nice work
