### ISSUE TITLE
[Design] Remove dupes and organize symbols in unified experience sketch file 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#55456]
## Description 

Remove dupes and organize symbols in sketch file in order to be able to document design, functional 

_[optional] Other specifications on specific symbols to engineers, designers, product owners and other stakeholders.[/optional]_ 

## Tasks

- [x] Meet with Christina and Ben to knowledge share about this conversation
- [x] Discuss how to manage this task while sitewide content is reviewing the sketch file. For example, should we create another page? 
- [x] Remove dupes and organize symbols

## AC

- [x] Work is validated. E.g., dupes are removed and symbols are organized.

**Comment by benbrasso-agile6** [comment]
Looks great. I left 1 or 2 very small comments. @cgednalske should take a look as well.

**Comment by cgednalske** [comment]
Looks good to me! Just two quick questions:

- Do we need all the different dividers? (If yes, totally good with that and you can ignore this question 😄 )
- Would adding headings above the sections of components be helpful for quickly scanning to look for something? Or if not now, later on? (If no, then feel free to ignore this question as well 🙂 )

**Comment by zach-park** [comment]
@cgednalske , I updated the symbols page to reflect your comments.  Thank you!
