### ISSUE TITLE
[SPIKE] [Design] Best method to document specifications to engineers

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#55457]
## Time Boxed
1 1/2 hours

## Description 

Determine the best method to document design, functional or other specifications on specific symbols and page components to engineers, designers, product owners and other stakeholders. 

For example: 

* Heading classes to be used. E.g., when the markup needs to be a different heading than the actual heading design. 
* Use of mobile headings vs. desktop headings. 
* Notifications do not stack. But, on page refresh, check to see if there's an appointment in the check in window. 

## Tasks

- [x] Meet with Christina and Ben to knowledge share about this conversation
- [x] [Review annotations library from DST](https://dsva.slack.com/archives/C04J6H2LYUU/p1680207421757729)
- [x] Ask how engineers use and/or might use sketch or abstract to inspect components
- [x] Determine solution 
- [x] Get approval or feedback from engineers 

## AC

- [ ] Solution determined

**Comment by benbrasso-agile6** [comment]
1) Don't need to include "mobile" in the "H2 mobile" name because they can inspect the heading and see that it's mobile. 
2) Don't need the 2nd label, e.g., "H3 styling" because they can inspect the heading and see what heading it is. 
3) Where a component does have a related artboard, use an annotation as a reminder to engineers, designers, product owner, etc.
