### ISSUE TITLE
Remove lymphatic cancers from Spanish and Tagalog PACT Act pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#55455]
## Issue Description

We removed the term "lymphatic cancers" from the English PACT Act page because of changes in the law. We need to remove this on the Spanish and Tagalog pages as well.

## Tasks
- [x] Remove from Spanish page (Randi)
- [x] Remove from Tagalog page (Randi)
- [x] Review and publish (Megan)
- [x] Review and publish (Megan)

## Acceptance Criteria
- [x] Pages are live with term removed

**Comment by RLHecht** [comment]
@megzehn I just removed these from the translated PACT Act pages as well. Can you review and publish? Thanks!

**Comment by megzehn** [comment]
Thanks, @RLHecht! I reviewed and published these pages.
