### ISSUE TITLE
Add in user flow components for the alternative path wireframes in unified experience 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#55460]
## Description 

The expectation is to not complete the entire PCI user flow. However, it is a building block to documenting the entire PCI user flow.

The expectation is to add in user flow components for the alternative path wireframes that are in the sketch file. For example, arrange and add in arrows to the alternative path wireframes. 

## Tasks 

- [x] Meet with Christina and Ben to knowledge share about this conversation
- [ ] Discuss how to manage this task while sitewide content is reviewing the sketch file. For example, should we create another page?
- [ ] Add in user flow components for the alternative path wireframes that are in the sketch file
- [ ] Update artboard headings, as needed, to create consistent structure for the user flow 

Note: An engineering walk-through is probably not needed because engineering work will not happen for some time.

## AC

- [ ] Added in user flow components for the alternative path wireframes that are in the sketch file

**Comment by benbrasso-agile6** [comment]
I'm going to start this task and look to set up a cowork with everyone

**Comment by benbrasso-agile6** [comment]
Will share progress on Monday UX sync - https://sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec

**Comment by benbrasso-agile6** [comment]
No. Working to finish it up today.

**Comment by benbrasso-agile6** [comment]
Finisihed this work, tossing it in vlaidate for now - https://sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec
