### ISSUE TITLE
Profile | Onboarding | Product Demo: Notification Settings in the VA.gov profile

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-team#55479]
## Background
As we're onboarding our new product manager to the Profile team, we want to provide a demo of the Notification Settings in the VA.gov profile so that he can get acclimated to the product.

## What you need to know
- Any team member who is comfortable providing a demo on the Notification Settings can take this ticket 
- Refer to the [Notification Settings](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/notification-preferences#readme) product outline for topics to cover in the demo

## Tasks
For assigned team member:
- [ ] Schedule a 30-minute demo with new product manager
- [ ] Conduct a 30-minute demo with new product manager
- [ ] No validation needed, team member can close this ticket when demo is completed

## Topics
The demo should be interactive, allowing for the new product manager to ask questions throughout. Here are some topics that can be addressed in the demo:
- [ ] What is this feature?
- [ ] Who uses it?
- [ ] Why is it used?
- [ ] How does it affect the user?
- [ ] Where does the user interact with it?
- [ ] As the Profile team, what is our responsibility for this feature?
