### ISSUE TITLE
[PM] 10-10EZ - Household section optimization: Update Contact Center guide

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#55470]
## Background
The Household section of the 10-10EZ form is being reorganized and updated.  We need to update the Contact Center guide with these changes.
**Note** We will need to also submit the change that includes the Medicare Claim number field (was not previously submitted).

## Tasks

- [x] Update all Household section pages with the new screenshots and details on completion
- [x] Include Medicare Claim number field update
- [x] Submit request ticket for Contact Center Guide review

## Acceptance Criteria
- Contact Center guide draft will be updated and submitted for review

**Comment by hdjustice** [comment]
Updated Contact Center guide submitted for review - #62679
