### ISSUE TITLE
Include welcome slide for DI introducing Gov team and others

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#55489]
## User Story
As a VFS team member, I want to know who is going to be on the call for a Design Intent and get introduced to the folks involved so that I feel comfortable and welcomed in the Collaboration Cycle.

As a Governance team member, I want VFS teams to feel comfortable at the DI so that they are not intimidated by our process and we're able to build relationships and trust with the VFS team.

Assignee: @CherylEvans 
Peer Reviewer: @sterkenburgsara 

## Description
The Design Intent is the first touchpoint in the Collaboration Cycle where VFS teams meet with Governance face-to-face. When it's a new team, this is likely the first time they're meeting us at all. To make VFS teams feel more comfortable and to make the process less intimidating, we have decided to introduce a welcome slide that will be shared at the beginning of the Design Intent meeting. The welcome slide will include names and pictures of Governance team members, as well as other folks that may be on the call, including Platform Security, Sitewide CAIA, and OCTO practice area leads.

## Impacted Artifacts
[Design Intent - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Moderator+Responsibilities)

## Tasks
- [x] Create an image (or slide) that includes the following:
   - Introduces Governance team members (team plus Ray and Matt) and their title. Photos should be included for Governance team members. See General Orientation slide deck.
   - Introduces other supporting teams by group (no need to mention their names). This should include Platform Security, Sitewide CAIA and OCTO Practice Area leads.
   - Slide/image should say at the top, "Welcome to the Design Intent" and also "Teams that support the Design Intent meeting:" or something like that
- [x] Modify DI Moderator Responsibilities - During Meeting section to include step for sharing slide. Slide should also be saved within the DI Moderator Responsibilities (or child page) for each reference.
   - Slide should only be shared as folks are joining the call. 
   - It is the hosts responsibility to share their screen and display the slide.
- [x] Modify DI Moderator Responsibilities - During Meeting section to include step for stopping sharing the slide.
- [x] Determine how the slide and the script will work together or not.
   - For example, do we want to modify the script to include the slide? Do we want to just share the slide and keep the script separately? Do we want to ensure the slide is being shared for at least part of the recording? I personally don't have an opinion and I like the option that means less changes to our process.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS teams are introduced to Governance team members and other teams supporting Collaboration Cycle at the beginning of the Design Intent.

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
Created [Draft](https://docs.google.com/presentation/d/1c1U0FMX1Efbr7Rs2RfikLKdbTVWEH4n28aGZoVas4jE/edit#slide=id.g23abdf76bc1_0_0) slide.

**Comment by CherylEvans** [comment]
@sterkenburgsara Hi Sara.  [Here](https://docs.google.com/presentation/d/1c1U0FMX1Efbr7Rs2RfikLKdbTVWEH4n28aGZoVas4jE/edit#slide=id.g23abdf76bc1_0_0) is my draft slide.  It's imperfect, so please let me know how I can improve.  Thank you!!

**Comment by CherylEvans** [comment]
Created a [draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2618490881/55489+-+Copy+of+Design+Intent+-+Moderator+Responsibilities) for Design Intent Moderator Responsibilities.

**Comment by sterkenburgsara** [comment]
@CherylEvans I added a comment on the slide, thanks for doing this! For the draft of DI moderator responsibilities - for some reason I can't tell where the edits are, can you point me to the section you updated?

**Comment by CherylEvans** [comment]
@sterkenburgsara Sara, the draft doc is not ready for peer review.  That was a SA update to let others know the status of the work for this effort.  We can only finalize something once the slide is finalized.  I replied to your comments on the slide.  I also copied a slide from PO and sent you a link.  That one might work better.  I need assistance with it, as I am unfamiliar with creating Google slides.  Once the slide is finalized and I have finished updating the draft doc, I will tag you for peer review. :-)

**Comment by CherylEvans** [comment]
Regarding the last task: "Determine how the slide and the script will work together or not.
For example, do we want to modify the script to include the slide? Do we want to just share the slide and keep the script separately? Do we want to ensure the slide is being shared for at least part of the recording? I personally don't have an opinion and I like the option that means less changes to our process."
I opt not to add verbiage to the script explaining the introduction slide.  The host should set up screen sharing of the slide 5 minutes before the start of the meeting.  This gives attendees who show up early a chance to read it and put names with faces, hopefully during the meeting.  I wrote the verbiage to reflect this and directed the host to speak only when they stopped sharing the slide.

**Comment by CherylEvans** [comment]
@sterkenburgsara Hi Sara.  I am ready for your peer review.
[Draft Welcome to Design Intent slide](https://docs.google.com/presentation/d/1c1U0FMX1Efbr7Rs2RfikLKdbTVWEH4n28aGZoVas4jE/edit#slide=id.g23db8d1d252_0_248) 
[Draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2618490881/55489+-+Copy+of+Design+Intent+-+Moderator+Responsibilities#During-Meeting) for Design Intent Moderator Responsibilities.

**Comment by sterkenburgsara** [comment]
@CherylEvans I love what you have and agree with your preferences above! I added a comment on the confluence doc, but I don't have strong opinions about the step we stop sharing at.

**Comment by sterkenburgsara** [comment]
@CherylEvans @allison0034 ooh Allison the slide looks nice! ship it! :-)

**Comment by CherylEvans** [comment]
@sterkenburgsara Hi Sara.  I just responded to your comments.  Let's try it out this way and change it if necessary.  I will add the step to allow the VFS team to walk through their design.  I always forget this step!!
I agree, Allison rocks!

**Comment by sterkenburgsara** [comment]
@CherylEvans perfect!

**Comment by CherylEvans** [comment]
@sterkenburgsara I've made the changes, and if you're good with it, I will publish it.

**Comment by sterkenburgsara** [comment]
@CherylEvans yes, looks good. Go for it!

**Comment by CherylEvans** [comment]
The Governance team was notified of the slight change to the Design Intent Moderator Responsibilities guidance.
