### ISSUE TITLE
Redirect Request: Legacy VA form landing pages (1:1 and Bulk)

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#5549]
### Tasks
- [ ] coordinate with mikki during redirects
- [ ] implement 1:1 redirects
- [ ] implement bulk redirects

### AC
- All legacy form urls are redirected to the new va.gov find va forms search or detail page experiences

---

### Instructions
- Requests for redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
*This is a detailed description of the request. It should include background information and reason for the request.*

### Requestor Info
*Indicate what team and who the primary contact on that team is*

### Implementation Date
Date new URL(s) will be live: *enter date new pages/URLs will be live*

Please indicate when the redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [x] Other - Please indicate timing : After basic auth gate is removed

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects Needed - See source spreadsheet: 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/redirects/form-detail-landing-pages-cutoff-for-redirects-091820.xlsx  (Reviewed 9/18 with Jen and Mikki)

Current URL  |  Redirect Destination (new URL)
---  |  ---
www.va.gov/vaforms/form_detail.asp?formno=21-4138 | /find-forms/about-form-21-4138
www.va.gov/vaforms/form_detail.asp?formno=21-526ez | /find-forms/about-form-21-526ez
www.va.gov/vaforms/form_detail.asp?formno=180 | https://www.va.gov/records/get-military-service-records/
www.va.gov/vaforms/form_detail.asp?formno=21-2680 | /find-forms/about-form-21-2680
www.va.gov/vaforms/form_detail.asp?formno=22-1995 | /find-forms/about-form-22-1995
www.va.gov/vaforms/form_detail.asp?formno=21-22 | /find-forms/about-form-21-22
www.va.gov/vaforms/form_detail.asp?formno=7959c | /find-forms/about-form-10-7959c
www.va.gov/vaforms/form_detail.asp?formno=10d | /find-forms/about-form-10-10d
www.va.gov/vaforms/form_detail.asp?formno=5345 | /find-forms/about-form-10-5345
www.va.gov/vaforms/form_detail.asp?formno=21-686c | /find-forms/about-form-21-686c
www.va.gov/vaforms/form_detail.asp?formno=20-0995 | /find-forms/about-form-20-0995
www.va.gov/vaforms/form_detail.asp?formno=0137 | /find-forms/about-form-10-0137
www.va.gov/vaforms/form_detail.asp?formno=21-0966 | /find-forms/about-form-21-0966
www.va.gov/vaforms/form_detail.asp?formno=21-0781 | /find-forms/about-form-21-0781
www.va.gov/vaforms/form_detail.asp?formno=21-0845 | /find-forms/about-form-21-0845
www.va.gov/vaforms/form_detail.asp?formno=22-5490 | /find-forms/about-form-22-5490
www.va.gov/vaforms/form_detail.asp?formno=21p-534ez | /find-forms/about-form-21p-534ez
www.va.gov/vaforms/form_detail.asp?formno=21-4142 | /find-forms/about-form-21-4142
www.va.gov/vaforms/form_detail.asp?formno=26-1880 | /find-forms/about-form-26-1880
www.va.gov/vaforms/form_detail.asp?formno=2850c | /find-forms/about-form-10-2850c
www.va.gov/vaforms/form_detail.asp?formno=306 | https://www.opm.gov/forms
www.va.gov/vaforms/form_detail.asp?formno=10ez | /find-forms/about-form-10-10ez
www.va.gov/vaforms/form_detail.asp?formno=21p-0969 | /find-forms/about-form-21p-0969
www.va.gov/vaforms/form_detail.asp?formno=21-674 | /find-forms/about-form-21-674
www.va.gov/vaforms/form_detail.asp?formno=21-8940 | /find-forms/about-form-21-8940
www.va.gov/vaforms/form_detail.asp?formno=3542 | /find-forms/about-form-10-3542
www.va.gov/vaforms/form_detail.asp?formno=20-572 | /find-forms/about-form-20-572
www.va.gov/vaforms/form_detail.asp?formno=7959a | /find-forms/about-form-10-7959a
www.va.gov/vaforms/form_detail.asp?formno=22-1990 | /find-forms/about-form-22-1990
www.va.gov/vaforms/form_detail.asp?formno=10cg | /find-forms/about-form-10-10cg
www.va.gov/vaforms/form_detail.asp?formno=21p-527ez | /find-forms/about-form-21p-527ez
www.va.gov/vaforms/form_detail.asp?formno=5655 | /find-forms/about-form-5655
www.va.gov/vaforms/form_detail.asp?formno=8678 | /find-forms/about-form-10-8678
www.va.gov/vaforms/form_detail.asp?formno=21-4192 | /find-forms/about-form-21-4192
www.va.gov/vaforms/form_detail.asp?formno=20-0996 | /find-forms/about-form-20-0996
www.va.gov/vaforms/form_detail.asp?formno=21-0788 | /find-forms/about-form-21-0788
www.va.gov/vaforms/form_detail.asp?formno=21p-530 | /find-forms/about-form-21p-530
www.va.gov/vaforms/form_detail.asp?formno=21p-8146 | /find-forms/about-form-21p-8146
www.va.gov/vaforms/form_detail.asp?formno=26-8923 | /find-forms/about-form-26-8923
www.va.gov/vaforms/form_detail.asp?formno=22-5495 | /find-forms/about-form-22-5495
www.va.gov/vaforms/form_detail.asp?formno=26-8937 | /find-forms/about-form-26-8937
www.va.gov/vaforms/form_detail.asp?formno=22-1990e | /find-forms/about-form-22-1990e
www.va.gov/vaforms/form_detail.asp?formno=21-4142a | /find-forms/about-form-21-4142a
www.va.gov/vaforms/form_detail.asp?formno=24-0296 | /find-forms/about-form-24-0296
www.va.gov/vaforms/form_detail.asp?formno=21-22a | /find-forms/about-form-21-22a
www.va.gov/vaforms/form_detail.asp?formno=21-8951-2 | /find-forms/about-form-21-8951-2
www.va.gov/vaforms/form_detail.asp?formno=28-1900 | /find-forms/about-form-28-1900
www.va.gov/vaforms/form_detail.asp?formno=21p-4706b | /find-forms/about-form-21p-4706b
www.va.gov/vaforms/form_detail.asp?formno=26-1820 | /find-forms/about-form-26-1820
www.va.gov/vaforms/form_detail.asp?formno=21-0779 | /find-forms/about-form-21-0779
www.va.gov/vaforms/form_detail.asp?formno=26-1859 | /find-forms/about-form-26-1859
www.va.gov/vaforms/form_detail.asp?formno=27-2008 | /find-forms/about-form-27-2008
www.va.gov/vaforms/form_detail.asp?formno=21-0781a | /find-forms/about-form-21-0781a
www.va.gov/vaforms/form_detail.asp?formno=10091 | /find-forms/about-form-10091
www.va.gov/vaforms/form_detail.asp?formno=10182 | /find-forms/about-form-10182
www.va.gov/vaforms/form_detail.asp?formno=21-0538 | /find-forms/about-form-21-0538
www.va.gov/vaforms/form_detail.asp?formno=7959f-1 | /find-forms/about-form-10-7959f-1
www.va.gov/vaforms/form_detail.asp?formno=3288 | /find-forms/about-form-3288
www.va.gov/vaforms/form_detail.asp?formno=26-6381 | /find-forms/about-form-26-6381
www.va.gov/vaforms/form_detail.asp?formno=26-1802a | /find-forms/about-form-26-1802a
www.va.gov/vaforms/form_detail.asp?formno=22-6553d-1 | /find-forms/about-form-22-6553d-1
www.va.gov/vaforms/form_detail.asp?formno=2850a | /find-forms/about-form-10-2850a
www.va.gov/vaforms/form_detail.asp?formno=0426 | /find-forms/about-form-10-0426
www.va.gov/vaforms/form_detail.asp?formno=10ec | /find-forms/about-form-10-10ec
www.va.gov/vaforms/form_detail.asp?formno=29-4125 | /find-forms/about-form-29-4125
~www.va.gov/vaforms/form_detail.asp~ | ~www.va.gov/find-forms/~
www.va.gov/vaforms/form_detail.asp?formno=10ezr | /find-forms/about-form-10-10ezr
www.va.gov/vaforms/form_detail.asp?formno=20-0998 | /find-forms/about-form-20-0998
www.va.gov/vaforms/form_detail.asp?formno=2850 | /find-forms/about-form-10-2850
www.va.gov/vaforms/form_detail.asp?formno=9 | /find-forms/about-form-9
www.va.gov/vaforms/form_detail.asp?formno=40-1330 | /find-forms/about-form-40-1330
www.va.gov/vaforms/form_detail.asp?formno=583 | /find-forms/about-form-10-583
www.va.gov/vaforms/form_detail.asp?formno=21-4502 | /find-forms/about-form-21-4502
www.va.gov/vaforms/form_detail.asp?formno=21-526 | /find-forms/about-form-21-526ez
www.va.gov/vaforms/form_detail.asp?formno=21-526b | /find-forms/about-form-21-526ez
https://www.va.gov/vaforms/form_detail.asp?formno=10ez%20(pdf) | /find-forms/about-form-10-10ez
www.va.gov/vaforms/form_detail.asp?formno=22-1990n | /find-forms/about-form-22-1990n
https://www.va.gov/vaforms/form_detail.asp?formno=40-10007 | /find-forms/about-form-40-10007

- [ ] **Once all the above 1:1 redirects are complete, a redirect should be put in place that captures all remaining legacy forms (i.e. www.va.gov/vaforms/form_detail.asp***) and redirects them to `www.va.gov/find-forms/`**

### Steps to complete
- [ ] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [ ] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Redirect request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by mnorthuis** [comment]
Review spreadsheet of form detail landing pages and identify redirect mapping for each line.  


[Original spreadsheet of 1800 lines](https://app.zenhub.com/files/133843125/3774c81f-f4cc-43e0-b2c5-79e132fe24a0/download)

[Revised focused spreadsheet to be mapped](https://github.com/department-of-veterans-affairs/va.gov-team/files/4167890/form-detail-landing-pages-analytics-YTD-sept2019.xlsx)

**Comment by MickinSahni** [comment]
Grooming:
- @jenniferlee-dsva to fill out redirect table and this'll be implemented when we're ready to launch the form detail pages
Note: not dependent on launch of Find VA Forms Search MVP

**Comment by jenniferlee-dsva** [comment]
@mnorthuis  - I updated the forms product decisions with our conversation about those OPM/GSA forms. 

Here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/README.md#03112020

Couple Qs and additional updates: 
1/ Can I provide the URLs in the form of a spreadsheet - the one we used to identify our 'cutoff' point?  
2/ Also do we need to one-by-one note the new /about-form-[number] URL for each redirect, or is this something we can do programmatically - via scripting maybe? 
3/ During SME validation of VBA forms, one form (Notice of Disagreement) is now deprecated  due to the AMA switch - it's actually one of the high traffic forms. Instead of just eliminating the legacy page, what do you think about redirecting this 1:1 to the `Decision Reviews hub `page or maybe better to the `Manage a legacy appeal `page?

**Comment by mnorthuis** [comment]
@jenniferlee-dsva @stephorkandatx  
To do the mapping for the redircts, we will need to know the exact URL of the new form detail pages.  Once that is determined - or we have the exact data that will be used to generate the URL - then we can map each legacy page to redirect.

**Comment by jenniferlee-dsva** [comment]
@mnorthuis - The url mapping is complete and can be found in the 8/5 Excel spreadsheet in this form detail product repo: 
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign/form-detail-landing-pages/redirects

**There are 2 sheets in the spreadsheet.** 
1/ Sheet 1 includes the 1:1 redirects of high value form pages - there are about 70. 
2/ Sheet 2 includes the rest, bulk redirects to the modernized forms search page. 

We will need to coordinate on timing because we need to publish the modern form detail pages in batches as part of our phased release. We can implement redirects similarly in batches OR all together at the very end when all modern form detail pages have been published - depending on your recommendation on how you would like to implement these. 

FYSA @MickinSahni @ncksllvn @kelsonic

**Comment by lunascoop** [comment]
@mnorthuis I added the URLs to the redirect table in your initial comment. Here's the Google version: https://drive.google.com/file/d/1hIVyafXDMQGJZZWQliQ0yQdboP7Uu7Mz/view?usp=sharing

**Comment by jenniferlee-dsva** [comment]
@mnorthuis - Added a link to the original request description and crossed out that invalid 10ez (pdf) URL. 

Here for easy access: 

**See source spreadsheet:**
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/redirects/form-detail-landing-pages-cutoff-for-redirects-091820.xlsx 
(Reviewed 9/18 with Jen and Mikki)

**Comment by mnorthuis** [comment]
Made updates to a couple of the URLs in the issue description to reflect conversations from the batch 1 release:

- `/find-forms/about-form-va40-10007` was updated to `/find-forms/about-form-40-10007` to remove the extra "va"
- `https://www.va.gov/vaforms/form_detail.asp?formno=10ez (pdf)` was updated to `https://www.va.gov/vaforms/form_detail.asp?formno=10ez%20(pdf)` to encode the space in the url
- I moved the final `https://www.va.gov/vaforms/form_detail.asp` redirect that is meant to capture all remaining legacy form urls out of the main list.  That redirect will need to be handled very carefully to ensure it doesn't override any of the 1:1 redirects. 

I will review this list again once the batch 2 pages are live and prior to this being implemented.

**Comment by MickinSahni** [comment]
Pulling into VSA Sprint 31 and awaiting lifting of basic auth/noindex and @mnorthuis's before we can start.

**Comment by lunascoop** [comment]
Posting comment from #13964 here:

I have validated that these URL changes are published.

@jenniferlee-dsva @mnorthuis While none of the form changes above are not on the 1:1 redirect list, I have updated the URL listed for VA form 40-10007 to remove "VA" per UAT change ticket #13751. With the change to VA form 40-10007 in mind, shouldn't the URLs for these other forms on the 1:1 redirect list be changed (listed below)? In looking at the PDF versions of the forms, they technically do not include a "VA" before the form name and follow the same schema as the other form names listed.

- VA Form VA-5655
- VA Form VA-10091
- VA Form VA-10182
- VA Form VA-3288
- VA Form VA-9
- VA Form VA-40-1330

Here's the updated spreadsheet w/ the forms listed above highlighted. 
[form-detail-landing-pages-cutoff-for-redirects-092520.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5283521/form-detail-landing-pages-cutoff-for-redirects-092520.xlsx)

**Comment by MickinSahni** [comment]
> Pulling into VSA Sprint 31 and awaiting lifting of basic auth/noindex and @mnorthuis's before we can start.
> 
> Approach: can roll out in redirect batches e.g. starting with 1:1s or bulk depending on risk.

Dev approach: start to crate PRs and push to lower envs given risk and testing need. But, will not push until 
- UAT complete
- basic auth and no index are removed 
- get thumbs up on roll-out plan (e.g. error rates)

**Comment by lunascoop** [comment]
In preparation for this redirect, I want to confirm that this requires stakeholder notification. I'm asking so that I can get the list of the appropriate stakeholders if needed, and possibly pull out this sprint due to the seven business-day notification requirement (cc: @bethpotts, @MickinSahni). I imagine that these redirects would involve stakeholders across multiple benefit hubs.

**Comment by MickinSahni** [comment]
Good call, Selina. Thoughts, @jenniferlee-dsva?

**Comment by jenniferlee-dsva** [comment]
Thank you for checking @lunascoop 

> In preparation for this redirect, I want to confirm that this requires stakeholder notification. 

I will send out a final redirect heads up/reminder to the VA forms managers and to Kevin Reid who manages the VA forms database. Please let me know a day or two in advance of the 1:1 and bulk redirects are about to happen and I will communicate.

**Comment by jenniferlee-dsva** [comment]
I will take a look at your other comment @lunascoop : https://github.com/department-of-veterans-affairs/va.gov-team/issues/5549#issuecomment-698981476

**Comment by jenniferlee-dsva** [comment]
Replying to: https://github.com/department-of-veterans-affairs/va.gov-team/issues/5549#issuecomment-698981476) 

RE updating the URLs to omit the VA prefix on the form number: Yes, that follows Mikki's patterns, so I'm okay doing this.  

To be clear, it would be changing `/about-form-va5655/` to `/about-form-5655/`  as an example. (Just note - this will not affect the H1s at all.) 

These are the H1s:
```
VA Form VA-5655
VA Form VA-10091
VA Form VA-10182
VA Form VA-3288
VA Form VA-9
VA Form VA-40-1330
```

RE the above list of H1s: W have no control over how the forms re named. If the form manager names their form in such a way that the display name is "VA-5665" or "5665blank," unfortunately, that is what will appear in the H1 of these form pages. 

Getting form managers to fix or standardize their form naming schema is a little bit of a losing battle, so I'd rather we let these H1s alone on forms that are low trafficked or does not have a digital tool. The future real solution would be to migrate forms inside the CMS, so we can rigidify the form naming and file naming schema.

**Comment by lunascoop** [comment]
@jenniferlee-dsva yes, I was talking about changing the urls and not the H1s. It's sort of like the "pdf" and "Spanish" forms where we changed the URLs but couldn't change the form titles.

**Comment by jenniferlee-dsva** [comment]
My bad - I looked up the forms on your list @lunascoop . and they actually are on our high trafficked list of forms/form pages. I've gone ahead and asked the form manager to update the form display name field in the db - this shouldn't affect your updating the URL, which we should still do. Thank you. Sorry for not 'getting' it quickly.

**Comment by jenniferlee-dsva** [comment]
I let Mikki [know here](https://dsva.slack.com/archives/CUB5X5MGF/p1601305900010700) and uploaded updated [spreadsheet **(9/28)** to product repo.](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign/form-detail-landing-pages/redirects)

**Comment by kelsonic** [comment]
Did we mean to close this ticket? 🙂 The redirects have not been implemented as of yet

**Comment by MickinSahni** [comment]
Yeah that was my same thought. This captures our work on the redirects

**Comment by mnorthuis** [comment]
@MickinSahni @lunascoop @jenniferlee-dsva  Let's use the steps to complete in the original description.  

Once you have the original list in the ticket updated, please assign back to me to be vetted and documented.

**Comment by lunascoop** [comment]
@mnorthuis I have updated the URLs in the original list.

**Comment by lunascoop** [comment]
URL updates for the six forms mentioned [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5549#issuecomment-699041678) have been published. The "va" before the form number has been removed.

**Comment by mnorthuis** [comment]
URLs above that are in batch 2 have been reviewed.  I made one change to the new page for form `/find-forms/about-form-21p-8416`, the form number was transposed in the above chart.  

As I mentioned previously, I crossed out the redirect for `www.va.gov/vaforms/form_detail.asp` from this list so that the 1:1 redirects can be put in place, and then all others can be done after that.    If you want to add it back in to do all at once, I will leave that up to you, just want to make sure that one is handled delicately. :-)     

These redirects are ready for implementation once your team is ready.

**Comment by kelsonic** [comment]
Implementation is currently blocked until:

1. Fix UAT bugs
2. Remove basic auth + noindex

**Comment by ncksllvn** [comment]
On pause - [Pr is open](https://github.com/department-of-veterans-affairs/devops/pull/7710) but holding off til Tuesday, Oct 13th,  to launch to prod because of holiday weekend.

**Comment by MickinSahni** [comment]
> plan on launching redirects tmw [wednesday] as part of the scheduled devops deployment

test urls:
https://dev.va.gov/vaforms/form_detail.asp?FormNo=21-526ez
https://dev.va.gov/vaforms/form_detail.asp?FormNo=21-526EZ
https://dev.va.gov/vaforms/form_detail.asp?formno=21-526ez
https://dev.va.gov/vaforms/form_detail.asp?formno=21-526EZ
