### ISSUE TITLE
[PM/DM] Review list of PO/PM/DM responsibilities and update as necessary

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#55499]
## Background

I created [a list of PO/PM/DM responsibilities](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/team/po-pm-dm-responsibilities.md) to help clarify each role on the team. I would love it if you could review this list @ajakabcin @BerniXiongA6 and update accordingly. 

I'm putting this in sprint 7, but feel free to prioritize and deprioritize as you see fit. Team/project work is more important.

## Tasks

- [ ] Review list of responsibilities
- [ ] Update accordingly
- [ ] Post in this ticket when you've completed your review/updates
- [ ] **If Samara is here**: I'll review updates, then close the ticket
- [ ] **If Samara is already on leave**: Feel free to close the ticket when you've both had a chance to review

**Comment by BerniXiongA6** [comment]
Thanks for putting this list together @Samara-Strauss -- I realize I shared a one-pager doc (of what I do as a Delivery Manager / Scrum Master) with you when I first started but I might not have shared the doc with @ajakabcin yet so this is good that you created this resource for us. I copied over my DM responsibilities from that one-pager onto your list here and made some updates. Please review the updates, and lmk if either of you have questions.

**Comment by Samara-Strauss** [comment]
Thank you, @BerniXiongA6!!

**Comment by mtcA6** [comment]
@ajakabcin @Samara-Strauss @ACParker89 should we dust this off? or can we close this out and spin up a new one?

**Comment by Samara-Strauss** [comment]
I think we can dust this off. I would need to read through and update the PO section. Everyone should feel free to do the same with their own respective sections, though no rush.
