### ISSUE TITLE
[Analytics Request] OPIA/VHA Email Campaign GA Tracking

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#555]
## User Story
As a va.gov platform user, I need to know how the OPIA/VHA email campaign is affecting website traffic so I can understand any website anomalies..

## Goal
Annotate GA to track email campaign.

## Screenshots/Resources
![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/a9c26248-14cf-4f36-aeff-fd86bd4671e9)

![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/86c5a9fe-8ffd-49ff-8ee0-0cd8711ebeeb)

First email tracking code.

https://links.govdelivery.com/track?type=click&enid=ZWFzPTEmbXNpZD0mYXVpZD0mbWFpbGluZ2lkPTIwMTkwNzA5Ljc4NDMzODEmbWVzc2FnZWlkPU1EQi1QUkQtQlVMLTIwMTkwNzA5Ljc4NDMzODEmZGF0YWJhc2VpZD0xMDAxJnNlcmlhbD0xNjc4ODQ1NCZlbWFpbGlkPWFuZHJldy5sZXdhbmRvd3NraTJAdmEuZ292JnVzZXJpZD1hbmRyZXcubGV3YW5kb3dza2kyQHZhLmdvdiZ0YXJnZXRpZD0mZmw9Jm12aWQ9JmV4dHJhPSYmJg==&&&104&&&https://www.va.gov/health-care/

## Acceptance Criteria
- [x] Track email campaign
- [ ] Share tracking efforts with stakeholders

## Definition of Done
- [ ] **Attached to a Milestone** 
- [ ] **Attached to an Epic**
- [ ] **Labeled with Team** 
- [ ] **Labeled with Practice Area** 
- [ ] **Labeled with Type**

**Comment by nedierecel** [comment]
@joanneesteban FYI - I can take this request.

**Comment by nedierecel** [comment]
@joanneesteban Annotations were made for 7/2 and 7/9 to track emails 1 and 2 of the OPIA/VHA emails sent via GovDelivery. 

These annotations are visible in the *All - Production*, *WBC*, and *Health Care - Modernized* Views.

The *Health Care - Modernized* view shows a spike on 7/9 when email 2 was sent. This report filters on the */health-care* hub page, which served as the landing page. 

[View the GA report here](https://analytics.google.com/analytics/web/?authuser=0#/report/content-pages/a50123418w177519031p184318975/_u.dateOption=last30days&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.sourceMedium&_r.drilldown=analytics.pagePath:~2Fhealth-care~2Findex.html/)

Future roadmap: this campaign is recorded as *links.govdelivery.com / referral*, but we could potentially work with email team to append tracking parameters that would organize these interactions into the *email* medium within Google Analytics.
