### ISSUE TITLE
Swap out videos in COVID CLP-HOLD TO PUBLISH UNTIL WEEK OF 4/3

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#55505]
## User story
We need to swap out the videos in the stories section of the CLP to these 2 Veterans:

Patricia Victor: https://www.youtube.com/watch?v=Dcnx5fOY268
John McAllister: https://www.youtube.com/watch?v=X2c7NMAWgHM

Drupal Page: Have questions before you get your COVID-19 vaccine? http://preview-prod.vfs.va.gov/preview?nodeId=19578

Documentation for how to swap videos: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/covid-19-biweekly-video-swap-process.md

## Tasks
- [ ] Replace text and videos (Aliyah)
- [ ] Review and publish (Randi)
- [ ] Create new ticket for next update (Randi)

## Acceptance Criteria
- [ ] New videos and text are live on the page

**Comment by RLHecht** [comment]
Closing this. We are redirecting this page so this work is no longer needed.
