### ISSUE TITLE
Update Midpoint Review artifact list

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#55517]
## User Story
As a VFS team member, I want to know what artifacts would be valuable for Governance team to see and review at Midpoint Review so that I can provide them to the team.

Assignee: @briandeconinck 
Peer Reviewer: @CherylEvans 

## Description
An updated artifacts list was created in ticket #54090. The purpose of this ticket will include updating the list of artifacts in both the Collab Cycle Request template (aka the cc kickoff - Midpoint Review code block) and the Midpoint Review touchpoint page.

## Impacted Artifacts
[Midpoint Review code block](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities#Midpoint-Review-code-block)
[Midpoint Review touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)

## Tasks
- [x] Update the artifact section of both documents to reflect the current list of requested artifacts

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS teams are asked to provide the current list of artifacts at Midpoint Review

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Note: this ticket and ticket #50725 should be worked on in parallel.

**Comment by briandeconinck** [comment]
Draft updated artifacts:
- [Midpoint review, artifacts section](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2579005463/55517+-+Midpoint+review#Artifacts)
- [Kickoff moderator responsibilities, midpoint review code block](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2579005497/55517+-+Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities#Midpoint-Review-code-block)

**Comment by briandeconinck** [comment]
@CherylEvans This and #50725 are ready for review!

**Comment by CherylEvans** [comment]
@briandeconinck For the Midpoint review, artifacts section, I recommend the Note section verbiage be changed to: 
"Note: VFS teams must provide all artifacts at least 2 days before the scheduled meeting/review. Please also ensure Collaboration Cycle reviewers have appropriate access to secured applications." This recommendation reflects an "active voice" and is less wordy.  :-)
The rest of the Artifacts section looks great!
For Kickoff moderator responsibilities, midpoint review code block, everything looks good.

**Comment by briandeconinck** [comment]
@CherylEvans Made that change!

**Comment by CherylEvans** [comment]
@briandeconinck Good to go! :-)
