### ISSUE TITLE
[Research] 10-10EZ - Improvements: Discovery on User Experience with the form title as H1

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#55518]
## Background
During some screenreader user testing for the 10-10EZ form, it was brought up that on some of the Yes/No questions, we start the page with a semi-unrelated paragraph that caused confusion about where you are in the form. The suggestion was to either have the question, then the explaining paragraph (in an additional info component), then the choices OR start the page with a title that gives context to the explanation content.

During discovery, it was found that this is a known design system-wide issue and is being researched and tested with other teams (tickets below).  We are monitoring the activity and will review the results, with an anticipated change to the overall design system for headers.  This will address the larger root cause for our application.

>#45483 @jessicastump and I chatted about this and we came to this recommendation:
>
>Leave this as is for now. It's a known issue that the form title as a h1 on every page causes accessibility issues for screen reader users. I believe that's the main issue here, and would be improved if the h1 and page title were the same as the question being asked. See #36116 for this coming up in an accessibility audit. Also, the new Forms team is planning on doing usability testing a changed header for forms. See #55121. The new header would be something like this page.
>
>Moving the additional info components and/or changing the color of the text doesn't address the root problem. So if we wait here for an improved solution upstream in the design system, it might be a better outcome.

## Scope
- Determine if this is still a valid concern
- Determine if there may be a similar concern, just with a different part of the form
- Determine what we might do, if anything, to improve this experience
- Timebox to one sprint's worth of effort.

## Tasks

- [x] Look into the tickets linked above
- [x] Determine if the solutions resolved the over-arching issue
- [x] Determine if we need to make any changes to align with the solutions, if applicable
- [x] Determine if we should address the issue differently, potentially revising our original findings

## Acceptance Criteria
- The team will know what next steps are needed to address this issue, if needed
- The team will know if there is something else (related but different) we should address, if needed.

**Comment by jessicastump** [comment]
Since this ticket and initial discovery there have been a couple of design system template updates that could be more impactful here: 

### Templates - Form step (last updated May 1, 2025)
There is additional guidance on step headers and page titles.
https://design.va.gov/templates/forms/form-step


### Templates - Form step minimal (last updated April 10, 2025)
https://design.va.gov/templates/forms/form-step-minimal


### Audit of current state

<details>
<summary>Pages missing text and/or visible headers</summary>

These are the pages that don’t currently have a visible heading within the page content section.

Audit of current pages without a text or field legend visual header: 

### Veteran information: 
1. Mother’s Maiden Name
2. Birth Sex
3. Demographics
4. Contact information

### VA Benefits: 
- h3 are the same content for both pages (disability rating and pension) 
“Current compensation from VA”

### Military Service: 
1. Last branch of service
- DS headline is “Service periods” but also setup for multiple responses in DS docs

- Toxic exposure header smaller font size styling


### Household Financial
1. Disclosure: yes/no
2. Spouse information - Potential Pattern Update https://design.va.gov/patterns/ask-users-for/marital-information
3. Dependents to report (1st question)


### Insurance Section
1. Medicare 
2. Medicaid


** Note:** Some headline’s / field legends using different font sizes (Spouse’s additional information + Toxic exposure intro page)

</details>


### Possible Options

<details>
<summary>Summary of updated discovery</summary>


**Directions for team to discuss after initial updated discovery :)** 

- Ensure all headers / field legends are using consistent stying/sizing


#### OPT 1 
- The pages listed above would be minimal content edits to add simple headers. Such as “Your marital status” 


#### OPT 2
- Make the field label legend the same size as the headers instead of the current default - make all pages consistent visually. 

- Field label text (also called legend)
https://design.va.gov/templates/forms/form-step#field-label-text-also-called-legend


#### OPT 3 - Bigger lift option: 
- Minimal header - overall form template/pattern
- And consistent h1 headers
- https://design.va.gov/templates/forms/form-step-minimal#page-headers

</details>

**Comment by jessicastump** [comment]
Recommendation - the VADS templates for the Form Step (or Form Step - Minimal) both would require some prep work to these few outlier pages listed in this ticket. A small lift could be to choose a direction- header or fieldset legend - example in image below and work on update page one at a time.

<img width="763" alt="Image" src="https://github.com/user-attachments/assets/99cfb407-7009-426a-a90a-633cdeb80198" />

**Comment by jessicastump** [comment]
Hi @hdjustice - I picked up this ticket while waiting for the research study to wrap up :) 
I added some notes to the ticket on the latest-and-greatest guidance in the design system around the **_Form step template_** options. Also started a [Figma page here](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ-Working-File?node-id=9862-21601&t=D4JnivH6STgKITFi-0) to visualize change options

**Comment by hdjustice** [comment]
Thanks @jessicastump !  Let's talk about this & make a decision in refinement next Wednesday, after all the holiday catch up.

**Comment by hdjustice** [comment]
Discussed during refinement, team agreement to move forward with option one

<img width="594" height="701" alt="Image" src="https://github.com/user-attachments/assets/825ab062-996e-4586-992f-bb37e3cbe148" />

**Comment by jessicastump** [comment]
Thanks! I will get the Figma page cleaned up so it is clear the exploration vs decided direction and will tag/close this ticket here when done.

**Comment by jessicastump** [comment]
@hdjustice  Updated [area on the Figma page created here](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ-Working-File?node-id=9909-13257&t=A3wOucYqTKtDVyKz-4) with decided direction mocks...

There are a couple of pages that are bugging me however. The added header feels more forced in a couple of scenarios - these pages are the household financial disclosure, demographics, birth sex and Medicaid (the eligibility wording in the question adds a layer here). For these few pages, I mocked up both ways and maybe we can circle back next week?

Also, noted on the Figma page there are a couple of patterns to keep watch out for in the future: the marital status and the demographics. Marital status has a new pattern that was just recently added to VADS and  demographics has a warning alert on it saying it will be deprecated soon.

**Comment by jessicastump** [comment]
@hdjustice - Figma page cleaned up in [this section here](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ-Working-File?node-id=9909-13257&t=cY39v0AeO2Ain3ht-4), with the changes chatted about in planning. The only page/question to hold off on at this time is the household financial information question. Added a comment in Figma that page title addition feels redundant and to hold on updating this round. Added notes to where additional information components can be moved.
