### ISSUE TITLE
Update Deployment process

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#55540]
### Summary
A couple areas need updating after EKS is rolled out to prod. Here is one spot, for example:
![image](https://user-images.githubusercontent.com/10993987/226743512-6b6ebbc2-517e-4e92-8cb7-15290a59564b.png)

I have made comments on the Confluence page to indicate where changes are needed. 

### Links
Confluence page: https://vfs.atlassian.net/wiki/spaces/pilot/pages/590970953/Deployment+process
Platform website page: https://depo-platform-documentation.scrollhelp.site/developer-docs/deployment-process

## Tasks
- [x] update https://vfs.atlassian.net/wiki/spaces/pilot/pages/590970953/Deployment+process+to+production
 
## Success Metrics
- [ ] ADD SUCCESS METRICS HERE
 
## Acceptance Criteria
- [ ] https://depo-platform-documentation.scrollhelp.site/developer-docs/deployment-process is deployed with the updates.

**Comment by jennb33** [comment]
Asked @rmtolmach to review this ticket and note any other factors that may be blocking it, aside from EKS being in PROD. Also requested update as to if it's still a relevant ticket.

**Comment by rmtolmach** [comment]
I updated the page. It was an older page. While not fully outdated, some info on the page didn't make sense, so I deleted a couple paragraphs. See changes here: https://vfs.atlassian.net/wiki/pages/diffpagesbyversion.action?pageId=590970953&selectedPageVersions=17&selectedPageVersions=18

**Comment by jennb33** [comment]
7/10 - @rjohnson2011 will review this change

**Comment by rjohnson2011** [comment]
Changes look great! Thanks for updating the deployment schedule times.
