### ISSUE TITLE
Confirm VBS ability to connect with MCP notifications endpoint

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#55555]
## Issue Description
VBS would like to connect with the MCP notifications endpoint soon to begin testing. We need to validate we have the security and authentication in place. 

---
## Tasks
- [x] Validate API key was sent and configured
    - [x] If not, generate new key and add configuration
- [ ] Test the endpoint can be called from within VA network

## Acceptance Criteria
- [ ] We know VBS can connect to our endpoint
- [x] We generated work to allow VBS to connect 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
As of 4/21/23 -VBS is currently testing. Scott assisting.
