### ISSUE TITLE
Send one FSR submission email per unique request

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#55554]
## Issue Description
VHA submissions have been generating more than one successful email if the request involved multiple facilities (because these are broken up into individual requests). We need to put the email submission logic in a way to track all of these requests being successful. 

Question: How do we want to handle a submission for one facility being sent successfully but one fails? 

---
## Tasks
- [x] Bundle individual requests into single parent request
- [x] Check if all requests are successful
    - [x] Send email success

## Acceptance Criteria
- [x] Successful FSR emails more accurately represent a Veteran request
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
May roll over if not reviewed before 4/12

[PR](https://github.com/department-of-veterans-affairs/vets-api/pull/12376) open
