### ISSUE TITLE
Analytics discovery for FSR Experience (Post Launch)

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#55568]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

The Debt Resolution UX team is exploring the analytics of the current live debt resolution and FSR experience. This will allow the team to take a targeted and evidence based approach to the upcoming enhanced FSR usability study, and to set meaningful KPIs. 

---
## Tasks
What work is necessary for this story to be completed?
- [ ] _UX team reviews analytics in Domo dashboard and Google Analytics_
- [ ] _UX team discusses what they find_
- [ ] _UX team documents current analytics and sets KPI goals once enhanced FSR is implemented_

## Acceptance Criteria
What will be created or happen as a result of this story?
- [ ] _Documentation of analytics before the enhanced FSR changes go live_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
Per Design team, let's look at this in S103, post-FSR launch.

**Comment by HeatherRienks** [comment]
Per SP, will carryover into S110.

**Comment by mgleo** [comment]
[Analytics Brainstorming Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695323152200/f17a8dce024cd79e8049135c708783b45da61f0c?sender=ua78f969c4cddcbfe56b27885)

**Comment by mgleo** [comment]
Ticket for analytics team has been created: [https://github.com/department-of-veterans-affairs/va.gov-team/issues/68094](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68094)

Once implemented by the analytics team, the funnel on our DOMO page should be accurate.
