### ISSUE TITLE
[Design]10-10CG - Primary/Secondary Caregiver clarification: Explore one page content

### ISSUE THREAD

**Issue by davidakennedy** [department-of-veterans-affairs/va.gov-team#55564]
## Background

Over the last 2 years, there has been sporadic feedback reflecting confusion on how to complete the 10-10CG, specifically around the differences between the Primary and Secondary caregiver roles, responsibilities and benefits.
Currently, the form only lists who would be eligible to be a caregiver, but does not provide much guidance on anything else.

The team decided to explore [creating a full page of content around this in the form](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/Primary%20vs%20Secondary%20Clarification/Discovery_Research/Primary/primary-secondary-caregiver-clarification-opporunities.md#idea-full-page-of-info-with-question-on-next-page). This ticket will be for creating those designs and content.

**Reference**

- See #38119 for past work on this.
- [Product Review Deck](https://docs.google.com/presentation/d/1BFVxhVI2gQIJx9xvCAKZi1LbzfDDifC6VcaN13iGOac/edit#slide=id.g33cc3b02a5_0_49)
- [Initiative Brief](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/caregivers/Primary%20vs%20Secondary%20Clarification)
- #35838 - Discovery
- #22372 - Initial designs (pre-design intent) Note: A few different designs ([Sketch link](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/v/15WML8/p/79BDE8AC-21C9-4FEF-B0FB-DA6E0C3990DD)) have been prepared with the intention to be shown at design intent.
- [Discovery work](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/Primary%20vs%20Secondary%20Clarification/Discovery_Research/Primary/primary-secondary-caregiver-clarification-opporunities.md)

## Tasks

- [x] Review reference resources, especially past design iterations.
- [ ] Design at least two versions of the one page content recommendation.
- [ ] Review with the team and content team.

## Acceptance criteria

Design options will be created, and reviewed by the team.

**Comment by davidakennedy** [comment]
Dropping a comment in here to update this ticket some:

1. This is on hold since I'm waiting for access to Sketch, as my onboarding is in a bit of limbo at the moment.
2. I did draft up some possible content to use for the designs, so have that ready when needed.

**Comment by hdjustice** [comment]
Adding Katelyn here to acclimate to some of the design work already in progress

**Comment by hdjustice** [comment]
Discussion with @katelyncai and @davidakennedy:
- It may be better to refer to a static information page rather than trying to outline eligibility requirements and responsibilities on our Intro pages
- Considering an authenticated experience, which may also inform a different flow, as well as the Intro page

Closing this ticket with the current exploration designs and working through the other explorations for flow and authenticated experience.
