### ISSUE TITLE
Supplemental Claims | Make it easier to edit and add more evidence from summary

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#55560]
## Value Statement
**_As a_** Veteran
**_I want to_** be able to easily review, edit, and add new evidence to my claim
**_So that_** I can supply the best evidence to support my claim

---
## Background Context
Expanded implementation of [Experimental Pattern: List & Loop](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1187)

Usability tests showed that there was friction from users who were navigating from the evidence summary page to add more evidence. Users did not expect to step through multiple screens to reach their target evidence type. 

Similarly, there is a usability concern that the user has to step through the entire evidence flow after adding editing or adding new evidence, requiring extra steps to return to where they started from.

## Acceptance Criteria
- [ ] Veterans have a way to return back to the evidence summary page easily after editing evidence.
- [ ] Veterans have a way to return back to the evidence summary page easily after adding new evidence.

## Out of scope
- Not part of MVP

## Tasks

- [ ] Identify if it's an issue post-launch.
- [ ] Draft design.

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
@eileen-coforma is this still relevant or can we close it?

**Comment by eileen-coforma** [comment]
@saderagsdale Still relevant. This could be part of the v2 work for Supplemental Claims. It's based off findings that surfaced during user research that we weren't able to solve for MVP release.
