### ISSUE TITLE
[PM] My VA Audit Improvements: Review/update product outline

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#55577]
## Background
Following the launch of My VA audit UX improvements, we need to review and update the product and project outline.

## Tasks
- [x] Review and update the [project outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/2022-audit#project-outline-my-va-audit-updates-and-documentation) 
- [x] Review and update the [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/README.md#product-outline-my-va)
- [x] Review and update [My VA roadmap](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/roadmap/my-va-roadmap.md)

## Acceptance Criteria
- Project outline is updated
- Product outline is updated
- Roadmap is updated
