### ISSUE TITLE
[eFSR] Housing Expenses Enhancement

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#55570]
## Issue Description
Update Montly housing expenses to match [new design flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1671734127581/dc254b12e788570c946af60bc55338b0045aea03?invited=true&sender=u7f58f2afe2ea053d4dea4234). 

|Checklist|Input List|Mini summary|
|--|--|--|
| ![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/16a598aa-141e-4472-b041-bd5d6ad4d79a) | ![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/9ecb8f8f-d1f6-4178-9a46-4878d3584f53) | ![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/eee1ebd2-8959-4a65-9ec0-fda086e4ebee) |

---
## Tasks
- [ ] Update Checklist
- [ ] Update Input list
- [ ] Add Mini Summary
- [ ] Update tests
  - [ ] Cypress
  - [ ] Unit

## Acceptance Criteria
- [ ] Workflow matches new design
- [ ] All relevant tests have been updated and are passing
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
Sliding to the blocked column until we receive further guidance on [expense calculation and organization](https://dsva.slack.com/archives/CPE4AJ6Q0/p1680100304721589) 

Also tagging [related expense ticket ](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/48510)

**Comment by Dr-Pongo** [comment]
Sliding back to ready now that we have clarification!

**Comment by HeatherRienks** [comment]
Waiting on clarification from Jill Anderson on next steps

**Comment by OptionSelect** [comment]
Giving to Andrew per convo. Branch efsr/55570/housing-expenses has been pushed up for him to have a starting point.

**Comment by Dr-Pongo** [comment]
Closing out for now since current functionality seems to be sufficient 
[Discussion with Jill](https://dsva.slack.com/archives/CPE4AJ6Q0/p1680100304721589)
