### ISSUE TITLE
[discovery] Decision Reviews | Refine success metrics and priorities

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#55587]
## Value Statement
**_As a_** team
**_We want to_** refine post-launch metrics for the Decision Review pathways
**_So that_** we can prioritize opportunities for each form. 

---
## Tasks
- [x] Sade - Draft success metrics
- [x] Sade - Schedule time with Matt for decision review info (HLR and NOD)
- [x] Sade/Eva - Create shared MURAL board for decision reviews
- [x] Gary/Eileen/Eva - Asynchronously add content to the board
- [x] Sarah - schedule working session with Gary, Eva, Eileen, Robin

## Acceptance Criteria

- [x] _We've informed our success metrics and priorities with data (interviews, DOMO, GA)_
- [x] _We have a working draft in MURAL that we can use to engage VA, VBA, and BVA stakeholders_
- [x] _We have inputs needed to define our next research plan_

**Comment by Evafloyd** [comment]
In addition to adding existing content to the mural board, Gary, Eileen and I have started journey mapping the 3 pathways which may grow into a separate ticket. TBD.

**Comment by saderagsdale** [comment]
Meeting with Matt Self this Friday to review action items for metrics.

**Comment by kylesoskin** [comment]
@saderagsdale can you link the draft you mention into this ticket (or send via slack)

**Comment by kylesoskin** [comment]
## Work in-progress

# Current baselines (Last 30 days)

# NOD Stats

- get_contestable_issues
  - Failures: 2
  - Success: 1530
  - Success rate: 99.87%
- evidence
  - Failures: 
  - Success:
  - Success rate: 
- create
  - Failures: 2
  - Success: 618
  - Success rate: 99.68%

# HLR Stats

- get_contestable_issues
  - Failures: 2
  - Success: 1530
  - Success rate: 99.87%
- create
  - Failures: 2
  - Success: 618
  - Success rate: 99.68%

# Supplemental Claims (Targets)
- get_contestable_issues
  - Success rate: 99.87%
- evidence
  - Success rate: 
- create
  - Success rate: 99.68%

**Comment by kylesoskin** [comment]
@saderagsdale this is still a work in progress. 
The numbers above need some more refinement and investigation.... but they are close to what we should expect for SC. 
>= 99.5% is probably a "safe" target

**Comment by eileen-coforma** [comment]
Can close after kick-off call with stakeholders next Tuesday (5/2)
