### ISSUE TITLE
[Design] My VA: Review heading hierarchy/styling

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#55585]
## Background
Per feedback in design intent, midpoint review and staging review, we need to review heading hierarchy and styling to make sure we're in alignment with the style and a11y guidance. (See relevant tickets linked below in Resource section)

## Tasks
- [x] Review tickets and feedback
- [x] Work with PM to determine where we need to make adjustments
- [x] Designer to make necessary updates to designs and FE documentation
- [x] PM to create tickets for FE updates

## Acceptance Criteria
- We have identified where our headings need to be adjusted to be in alignment with style and a11y guides
- We have FE ticket(s) created to execute necessary changes

## Resources
Design Intent
- #47549

Midpoint Review
- #48676 (second point re screenreader and H2/H3)

Staging Review
- #54878
- #54880

**Comment by fmccaf1** [comment]
### Changes requested in linked documents:

- Change to benefit payment cards: change h4 that follows h3 to a p with styling to make it look like a heading and use aria-describedby to associate it with the h3:

<div ...>
   <h3 class="vads-u-margin-top--0" data-testid="deposit-header-v2" **aria-describedby="some-unique-id"**>
      +$3,057.13
   </h3>
   **<p class="..." id="some-unique-id">**
      Compensation &amp; Pension - Recurring
   </p>
   <p ...>
      Check mailed on November 1, 2022
   </p>
   <a ...>
      View your payment history<i ...></i>
   </a>
</div>

- Change to benefits application in progress: Currently heading level for application in progress card is an h4, which is skipping a heading level. It should be an h3.
- Conduct testing on Education and training section: Double-check in Angela Fowler's office hours or with other screenreader user to ensure that there's no need for a hidden h3 for the secondary links in the Education and training section
- Conduct testing on "You have no [...] to show" message that appears under section headings to ensure that screen-reader-only H3s are not causing confusion or repetition for screen-reader users

**Comment by ajakabcin** [comment]
@fmccaf1 and @aagosto90 I created these three tickets based on Florence's review:

- #57393
- #57394 
- #57395

**Comment by ajakabcin** [comment]
Thanks for your work here @fmccaf1 I'm going to close this out : )

**Comment by fmccaf1** [comment]
Oh no @ajakabcin I also just finished these tickets!

- [57388](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57388)
- [57396](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57396)
- [57398] (https://github.com/department-of-veterans-affairs/va.gov-team/issues/57398)

**Comment by fmccaf1** [comment]
We must've been working at the exact same moment

**Comment by ajakabcin** [comment]
I'll take a look - so sorry for the double work @fmccaf1!
