### ISSUE TITLE
[FE] My VA: All dashboard links should open in the same tab

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#55580]
## Background
[Per feedback from staging review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54875), all links on My VA dashboard should open in the same tab.

## Tasks
- [ ] Review links on My VA to identify which ones open in a new tab
- [ ] Change behavior so that all links on My VA open in the same tab
- [ ] Test
- [ ] Move to validate

## Acceptance Criteria
All links on My VA open in the same tab

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ Log into staging and confirm all links on My VA open in the same tab

**Comment by ajakabcin** [comment]
sorry for the slow response on this but looks great - thank you!
