### ISSUE TITLE
[Design] My VA: Explore Cerner alert design

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#55582]
## Background
[Per feedback from staging review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54876), we should consider alternative design options for the message users see when they receive care at a Cerner facility.

## Tasks
- [x] Review feedback
- [x] Touch base with other teams who use the Cerner alert to be on the same page
- [x] Discuss with DSC (slack is fine) to determine what would be more appropriate
- [x] Explore alternative designs
- [x] Share with the team

## Acceptance Criteria
We have considered/explored alternative designs for the Cerner message

**Comment by fmccaf1** [comment]
Some screenshots of the current cerner experience: 

![Screen Shot 2023-04-17 at 4 05 04 PM](https://user-images.githubusercontent.com/106624475/232855464-ab251cde-411c-4568-8ff1-6b8c8bebaac2.png)

![Screen Shot 2023-04-17 at 4 03 41 PM](https://user-images.githubusercontent.com/106624475/232855480-17c9e2da-2d9e-4651-bbfa-326f67afcb37.png)

**Comment by fmccaf1** [comment]
[Link to slack message](https://dsva.slack.com/archives/CE4304QPK/p1681839358623199) to VFS-all-teams seeking other teams that have products with the Cerner alert
