### ISSUE TITLE
Discovery - Whether PCIU Address service used by Form 526EZ (BRD)

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#55594]
## Issue Description

Discovery work needs to be done to know:
1. If [EVSS Reference Data Address](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/addresses_controller.rb#L52) is being used
2. Are we responsible for migrating that to Lighthouse.
2a. Addresses isn't being used in the [DisabilityCompensationFormController](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/disability_compensation_forms_controller.rb)
2b. What LH endpoint do we migrate this too. 
3. What is the relationship of `EVSS::ReferenceData` and `EVSS::PCIUAddress` and what is the "Setting" in the linked file above.

_note:_ Given [reference_data_service](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/settings.yml#L400) is disabled, I don't think we are even using [EVSS::ReferenceData] address, or that it even exists. ([Used here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/addresses_controller.rb#L51))

## Resources:
* [PCIU Address Info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/evss-integration/pciu-address-specs.md)
---
## Tasks
- [ ] Research [PCIU Address Information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/evss-integration/pciu-address-specs.md) (what is it?)
- [ ] Why was `EVSS::ReferenceData` being used in the addresses controller? It doesn't seem to have a `get_address` method on it.
- [ ] Reach out to LH and EVSS to understand what the equivalent LH API is to EVSS ReferenceData (or EVSS PCIUAddress).
- [ ] Meeting with Axolotl team(LH BRD team)

## Acceptance Criteria
- [ ] Identify the work that needs to be done as an outcome of this ticket.
- [ ] A ticket created on our Zenhub board, if this is BDE work.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by colevoss** [comment]
Does this have anything to do with Address???
[Lighthouse Veteran Verification -> Address](https://developer.va.gov/explore/verification/docs/address_validation?version=current)

**Comment by navaeddie** [comment]
A different team is handling this migration.
See [Slack thread](https://dsva.slack.com/archives/C04KW0B46N5/p1682623991892389).
Point of contact: Kevin Duensing
