### ISSUE TITLE
[Research] BDD: Initial Usability Testing/Discovery with Mocked Up BDD Based on Original Claims

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#5559]
## User Story or Problem Statement
As a UX designer, I need to test the Benefits Delivery at Discharge digital form mockup so I can receive feedback on the initial design and improve it.

This will not be a "true" usability study with a built out front-end, we will collect feedback on the BDD digital form mockup.

## Tasks
- [x] Conduct interviews and collect notes
- [x] Create readout and schedule readout review meeting
- [x] Share with design team/lead
- [x] Upload to GitHub and update [this ](https://docs.google.com/spreadsheets/d/191FcWP_pqq2jnPnEJ1OXjLvaflYszt5VKuSw8NMe3FY)document

## Acceptance Criteria
- [x] Test the mockup with 8-10 users 
- [x] Create notes and drop scrubbed data into GH
- [x] Share notes with team
- [x] Conduct first readout of research findings

**Comment by chrvalla** [comment]
The BDD prototype has been tested with 10 users.  
 Notes are uploaded to GH
Topline Summary and Notes has been shared with team. 
Topline Summary uploaded to GH. 
Research Finding report written. Will be uploaded to GH 3/27/2020
See all documents here:
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/disability-compensation-claim/bdd/BDD%20Research/Initial-usability-March2020
