### ISSUE TITLE
Design | Profile | Logged-in IA and Nav | Topline Summary

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#55596]
## Background

Now that the logged-in IA research is complete, we need to put together a topline summary to share w/ the team before full synthesis starts.

## Tasks
- [ ] Publish topline summary
- [ ] Solicit feedback from observers
  

## Acceptance Criteria
- [ ] Observers have provided feedback

**Comment by andaleliz** [comment]
closing as duplicate
