### ISSUE TITLE
[FE, BE] My VA: Audit unit test coverage on My VA

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#55593]
## Background
In preparing for staging review of the My VA audit work we learned that our code coverage could be improved. We need to review our existing unit tests and document what needs improvement in order to meet (and preferably exceed) the [QA standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards) for staging review. 

**Our current level of unit test coverage is ~50%, the QA standard is 75% or higher (as of March 2023)**

## Tasks
- [x] Review existing unit tests
- [x] Document findings/where we need to make improvements
- [x] Work with PM to create tickets for making unit test improvements

## Acceptance Criteria
- We have completed an audit of our existing unit tests and identified where we need improvements
- We have a plan for implementing areas of improvement

**Comment by allisonlu** [comment]
I created a markdown file for documenting updates that we should make (this is very much so a WIP):

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/test-audit.md

**Comment by ajakabcin** [comment]
Thanks for doing this very thorough audit @dellerbie! Am I understanding correctly that all the ❌ 's implies a test does not exist but is needed? In that case looks like we have our work cut out for us in terms of writing them!

**Comment by ajakabcin** [comment]
BE unit test tickets created:
- #57459
- #57458
- #57457
- #57456
- #57455
- #57454
