### ISSUE TITLE
[Research] BDD: Usability Testing of Full BDD Prototype

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#5560]
## User Story or Problem Statement
As a UX designer, I need to test the Benefits Delivery at Discharge digital form (in password protected production) with real users so I can receive feedback on the design and improve it.

This is the full usability study after we have a real FE build out ready for testing.

## Tasks
- [ ] Conduct interviews and collect notes
- [ ] Create readout and schedule readout review meeting
- [ ] Share with design team/lead
- [ ] Upload to GitHub and update [this ](https://docs.google.com/spreadsheets/d/191FcWP_pqq2jnPnEJ1OXjLvaflYszt5VKuSw8NMe3FY)document

## Acceptance Criteria
- [ ] Test the prototype with 8-10 users 
- [ ] Create notes and drop scrubbed data into GH
- [ ] Share notes with team
- [ ] Conduct readout of research findings

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
