### ISSUE TITLE
[FE, BE] My VA: Audit E2E test coverage on My VA

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#55602]
## Background
In preparing for staging review of the My VA audit work we learned that our E2E test coverage could be improved. We need to review our existing E2E tests and document what needs improvement in order to exceed the [QA standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards) for staging review. 

**the QA standard is to have one or more E2E tests. [My VA has 20+](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/personalization/dashboard/tests/e2e), though many are very outdated.**

## Tasks
- [x] Review existing E2E tests
- [x] Document findings/where we need to make improvements
- [x] Work with PM to create tickets for making E2E test improvements

## Acceptance Criteria
- We have completed an audit of our existing E2E tests and identified where we need improvements
- We have a plan for implementing the improvements identified in the audit

**Comment by allisonlu** [comment]
Still a WIP, here's what I have so far: 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/fe-e2e-test-audit.md

**Comment by allisonlu** [comment]
ready for validation!

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/fe-e2e-test-audit.md

q's for @ajakabcin:
- do we have access to TestRail? some of these tests were written by Tze and seems like they were exported from TestRail
- how often do we consider / add new test cases?

q's for @aagosto90 (and/or @ajakabcin):

**Nametag**
- there is a discrepancy for [error state of Disability rating](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/nametag.md#disability-rating) in FE docs (link is **View disability rating**) and the [Sketch file](https://www.sketch.com/s/bca53b50-8797-44fa-8c37-2b13c24c626c) (link is **Your disability rating**). Which one is the most up-to-date?
- does user having disability rating info imply user also has a military info? i.e. if user has disability rating, but does not have military info, what do we show in Nametag? (confirming if State 2 of [Military information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/nametag.md#military-information) also applies for DOES NOT have branch of service, but HAS disability rating)

**Health care**
- from my understanding, if the main `GET/user` API call fails, then we get a full page error. Is [error state 1 in Health care](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/health-care-FE-documentation.md#error-state-1-the-getuser-user-call-fails-cant-tell-if-user-has-va-health-care-or-not) different from the [My VA full page error](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/full-page-error-FE-documentation.md)?

**Comment by ajakabcin** [comment]
Allison, Angela and I huddled on these questions, just closing the loop for record keeping

RE test rail
- we're not really using TestRail going forward (for the foreseeable future)
- I'll get in touch with out former QA support team member and see what if any archived tests he has access to

**Name tag**
- Angela is updating the sketch file to match what's on staging and prod, just a text discrepancy
- It should, and we think there might be an issue with military info because it's not showing for some reason on staging right now for users that it should

**Health care**
- we should consider these error states separate because we're not entirely certain that the page _couldn't_ load and render the health care error

**Comment by ajakabcin** [comment]
Closing this - I'll create tickets for the tests Allison identified to be groomed and planned for future sprints.
