### ISSUE TITLE
Add content about flags to burial flags page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#55613]
## Issue Description

NCA reached out and asked us to add content to our [Burial flags](https://www.va.gov/burials-memorials/memorial-items/burial-flags/) page about giving a flag to a VSO. 

This work was done in emails with stakeholders but creating ticket for tracking purposes. 

## Tasks
- [x] Rework content (Beth)
- [x] Update in Drupal (Randi)
- [x] Share with stakeholders (Randi)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Page is live with changes
