### ISSUE TITLE
Content support for 10-10CG facility page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#55614]
## Issue Description

The Health Apps team opened an intake request for content help on the 10-10CG's Veteran's preferred facility page.

Intake ticket with more background #55327

Artifacts provided by product team:

- Link to product outline: 10-10CG Product Outline
- Link to initiative brief: Improve Facility Selection Initiative Brief
- Link to or attach user flows: Wireflows of proposed flow

- Link to prototype or mockups:

[Figma designs from Jessica](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=3592-11039&t=FQTBTgA3gMu0h2CF-4)

**Archive**

**Desktop**
search input desktop - https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/jgnAQyo
search results desktop - https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/zx9e3Yb
select desktop - https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/Jn1QKqr
confirmation desktop - https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/4aRZWrd

**Mobile**
search input mobile - https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/dlyemEb
search results mobile - https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/ZOGQjqp
select mobile - https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/v8VZMbM
confirmation mobile - https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/eKPGDyq

- Link to any epics/issues that may be helpful:

[Artboard with Content brainstorming](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/ZO137w3) - working with Danielle

## Tasks
- [x] Review and edit screens (Aliyah)
- [x] Provide team with final content (Aliyah)

## Acceptance Criteria
- [x] Product team has final content

**Comment by aliyahblackmore** [comment]
**Update here:** 

I'll begin work on this with the 1010 team over the next sprints.

There's a technical aspect that their team is still waiting on, but we can begin content in the mean time.

**Comment by coforma-terry** [comment]
Moving to backlog @Alicklog @aliyahblackmore for now

**Comment by aliyahblackmore** [comment]
I have two questions out to their team in the intake request: 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/55327#issuecomment-1693904974

**Comment by aliyahblackmore** [comment]
Moved to backlog for now. This is on pause while we're working on the 1010EZR.

**Comment by aliyahblackmore** [comment]
**Cross posting from the intake request to close the loop here:** 

- The content recommendations are in the [Figma designs](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=3592-11039&t=FQTBTgA3gMu0h2CF-4). I tracked notes about the content adjustments in that section.
   - [edit 12/4] After chatting with Jessica about the error messages, we clarified that there are 2 different errors on the search screen depending on the action ([link to screen](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK?node-id=3792-32442#1051872812)). Action A - If they enter a city/state/postal code in the input and select "continue", error tells them to select the "Search" button // Action B - if they don't enter a a city/state/postal code in the input, 1 error tells them to enter a city/state/postal code
- I noted a few consistency things across the screens ([using "coordinator" vs. "Caregiver Support Team/Program Team](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK?node-id=3737-11431#1048653656), [add "or clinic" to the form intro page](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK?node-id=3737-11431#1046437730), and [a question](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK?node-id=3737-11431#1048426964) about whether a header above the search selection is in scope for the product team)
 - The "Content draft" section has the Option 2 content for the search screens. Those adjustments likely aren't in scope for V1, but they're there for the future.

**Comment by aliyahblackmore** [comment]
**Update here:** 

- Form updates launch TBD. 
- The team already has the content updates/recommendations. And there aren't any static page updates for this iteration.

**Comment by aliyahblackmore** [comment]
**Update here** 

Moving this to "Blocked" for now. Per Heather, the team is planning to launch in January (maybe mid-January).

**Comment by hdjustice** [comment]
This feature has been launched to 100% as of 2/14/2025
