### ISSUE TITLE
[eFSR] Functionality updates for FSR

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#55628]
## Issue Description
This Work in Progress ticket is a placeholder and will contain a list of functionality updates that need to be made on VA.gov by Front End team. @Dr-Pongo  will create individual additional Front End tickets.

---
## Tasks
- [x] Remove _other_ checkbox option from [Veteran other income](https://preview.uxpin.com/f43733391f52c409c4d3152e9a4b101a392e29df#/pages/161460730) and Spouse's other income and add additional [update/add pages](https://www.sketch.com/s/79aa4a84-fef1-4c06-9495-e0431a6390bd/p/E92105DB-956A-4122-B542-423F36F85041/canvas#Version) to this list loop to mimic [Other Assets](https://preview.uxpin.com/f43733391f52c409c4d3152e9a4b101a392e29df#/pages/161460775) functionality. 
Ticket: #56738
- [x] Change _back/continue_ buttons to _cancel_ or _add/update_  when adding or editing items from a mini summary card list. When adding item directly in the flow of the form (example: [first vehicle]
(https://preview.uxpin.com/f43733391f52c409c4d3152e9a4b101a392e29df#/pages/161460760/simulate/sitemap)), keep _back/continue_ buttons.
Ticket: #56739
- [x] [Vehicle input](https://preview.uxpin.com/f43733391f52c409c4d3152e9a4b101a392e29df#/pages/161460760/simulate/sitemap?mode=i): Errors aren't shown when user doesn't fill out required field.  Ticket: #56741

- [x] Add correct [conditional `disabled` functionality](https://preview.uxpin.com/f43733391f52c409c4d3152e9a4b101a392e29df#/pages/161460736) to _Current Year and Month_ fields for the [employment history](https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-spouse-employment-records) pages for spouse and the veteran when _I currenlty work here_ `checkbox` is selected. Here's the [slack thread](https://dsva.slack.com/archives/CPE4AJ6Q0/p1681414185203349) for more context.  Ticket [#57342](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/57342)

<img width="547" alt="Screenshot 2023-04-13 at 1 00 18 PM" src="https://user-images.githubusercontent.com/1631062/231869956-6cfc8aa0-7b6b-4b17-b3fb-1b242bd4330e.png">

- [x] **[Installment contracts and other debt > summary card](https://preview.uxpin.com/f43733391f52c409c4d3152e9a4b101a392e29df#/pages/161460818/simulate/sitemap)**  Only show fields that the user has filled out on summary cards - Ticket [#57343](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/57343)
- [x] All input fields - Update length of input fields to match designs. [See discussion on Slack.](https://dsva.slack.com/archives/C01DBGX4P45/p1681943660853739) Ticket [#57345](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/57345)

**Design/Content needed:** (Can be added after Sprint 98- not launch blocking)

- [x] **[Veteran Employment History > Current job income](https://preview.uxpin.com/f43733391f52c409c4d3152e9a4b101a392e29df#/pages/161460718/simulate/sitemap)** Add an [Additional Info component](https://design.va.gov/components/additional-info#examples) that explains how to calculate monthly income
- [x] **[Veteran employment history > payroll deductions](https://preview.uxpin.com/f43733391f52c409c4d3152e9a4b101a392e29df#/pages/161460720/simulate/sitemap)**  Add an [Additional Info component](https://design.va.gov/components/additional-info#examples) that explains how to check for payroll deductions and calculate them from paystub
- [x] **[Veteran employment history > payroll deduction amounts](https://preview.uxpin.com/f43733391f52c409c4d3152e9a4b101a392e29df#/pages/161460722/simulate/sitemap)**  Add an [Additional Info component](https://design.va.gov/components/additional-info#examples) that explains how to check for payroll deductions and calculate them from paystub
- [x] **[Household expenses > summary](https://preview.uxpin.com/f43733391f52c409c4d3152e9a4b101a392e29df#/pages/161665014)** Page is missing, needs to be added.
- [x] **[Household expenses > installment contracts/credit card bills](https://preview.uxpin.com/f43733391f52c409c4d3152e9a4b101a392e29df#/pages/161460809)** Change order of installments and credit card bills steps so that **credit card bills comes first** and **installment contracts comes next**.
- [x] **Vehicle Summary Page** Remove index number from `aria-label` for vehicle mini-summary page edit/delete buttons; it's confusing from a screen reader standpoint to read *Edit 1989 BMW 325ix **0*** or *Edit 2004 Honda Accord **1*** [Saw that the index](https://github.com/department-of-veterans-affairs/vets-website/pull/23986) was added to prevent confusion if there were dupes, but it reads strangely to have a number, is there something else we can do? [#58973](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/58973)
- [x] **[Add Employment Record](https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-employment-records)** Required label on **Employer Name** doesn't trigger error when you click the **Add Employment Record button**, can skip it even though it's a required field. [#58974](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/58974)
- [x] Back and continue buttons aren't showing anymore when you add an initial employment history or vehicle. Seems like this is happening on all the pages. Not sure if the functionality changed or not. (buttons exist, just not labeled correctly) [#58975](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/58975)
- [x] H3 styled as h4 update #58959
- [x] **Add a credit card bill** Tried to add credit card bill (clicked cancel like it wasn't going to be added; and went to a blank screen). [#58977](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/58977)
- [x] Exploration: NaN is appearing on mobile (Example: Veteran Benefits Summary page).  [#58978](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/58978)
- [x] Exploration: Two mobile users were unable to submit form using eFSR. [#58979](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/58979)
- [x] **Contact info > Edit phone number**  Remove extension field [#58980](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/58980)
- [x] **[Spouse employment > Monthly income question](https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-gross-monthly-income)**  Required field doesn't work, can press continue without filling out the field.  [#58981](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/58981)
- [x] [Recreational vehicles review page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57600#issuecomment-1564993520) is missing update button. 
- [x] [Review page spouse benefits and recreational vehicles](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57600#issuecomment-1564990536) are missing $ symbol in review mode.
- [x] **Contact info** Typo on Contact Info page, says "Supplemental Claim"

## Acceptance Criteria
- [x] _Frontend team will create tickets based on these updates_

**Comment by HeatherRienks** [comment]
@Dr-Pongo - these tickets are ready to be created! :)

**Comment by HeatherRienks** [comment]
@Dr-Pongo - of all 3 tasks listed above, please prioritize creating a ticket for Task 1 listed above:
"Remove other checkbox option from Veteran other income and Spouse's other income and add additional update/add pages to this list loop to mimic Other Assets functionality." 

Thanks!

**Comment by Dr-Pongo** [comment]
Task 1 ticket:
Other income summary page addition (Veteran & Spouse) [#56738](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/56738)

**Comment by Dr-Pongo** [comment]
Remaining tickets for tasks

Mini summary update page content [#56739](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/56739)
Vehicle input error messages [#56741](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/56741)

**Comment by josephrlee** [comment]
@Dr-Pongo, I just added a new functionality task for y'all based on [the convo in Slack](https://dsva.slack.com/archives/CPE4AJ6Q0/p1681414185203349).

**Comment by Dr-Pongo** [comment]
Added installment contract summary card update FE Ticket [#57343](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/57343)

**Comment by Dr-Pongo** [comment]
Added input field width FE Ticket [#57345](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/57345)

**Comment by josephrlee** [comment]
@Dr-Pongo, just added a new task to this ticket regarding adding the mini-summary page for **Household Expenses**!

**Comment by HeatherRienks** [comment]
FYI- per 5/8/23 convo, we do NOT need Household Expenses task.

**Comment by josephrlee** [comment]
@Dr-Pongo, just added the new task to update the order of contract installments/credit card bills so that **credit card bills** comes before **installment contracts**.

**Comment by Dr-Pongo** [comment]
[#58160](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/58160) Ticket created for installment contract / credit card bill ordering

**Comment by josephrlee** [comment]
@Dr-Pongo, added a few more tasks that came out of our [assistive tech pilot session](https://github.com/department-of-veterans-affairs/va.gov-team/issues/58211#issuecomment-1555190617) we had. I can handle the `h4` to `h3` issue for the Mini Summary Cards, but for the rest, y'all will have to take on. Also, happy to chat through it more with you as well!

**Comment by Dr-Pongo** [comment]
New Tickets Created:



- [eFSR] aria labeling mini summary cards [#58973](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/58973)
- [eFSR] Bug -Employment History required not triggering error [#58974](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/58974)
- [eFSR] Navigation content update [#58975](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/58975)
- [eFSR] Bug -Add Credit Card Bill cancel button [#58977](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/58977)
- [eFSR] Bug -Veteran Benefits Summary page NaN [#58978](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/58978)
- [eFSR] Bug -Investigate submission issues during testing [#58979](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/58979)
- [eFSR] Contact information mobile number extension [#58980](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/58980)
- [eFSR] Bug - Required Field Spouse Employment history monthly income [#58981](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/58981)

**Comment by josephrlee** [comment]
@Dr-Pongo Created a couple more tasks after doing the accessibility testing that are not accessibility-related but are minor bugs nonetheless.

**Comment by HeatherRienks** [comment]
@Dr-Pongo- would you be able to add these tickets in (so we can possibly add them to our new Sprint tomorrow? :) Thanks!

cc: @josephrlee

**Comment by Dr-Pongo** [comment]
@HeatherRienks I'll add them first thing tomorrow!

**Comment by HeatherRienks** [comment]
Thank you @Dr-Pongo!

**Comment by Dr-Pongo** [comment]
Created:

- [eFSR] Update recreational vehicle on review page [#59851](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/59851)
- [eFSR] Add dollar sign to spouse benefits on review page [#59852](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/59852)
- Contact Info typo fixed in [#24435](https://github.com/department-of-veterans-affairs/vets-website/pull/24435)

**Comment by mgleo** [comment]
@HeatherRienks @Tom-Davis closing this ticket
