### ISSUE TITLE
[Design] BDD: Design MVP Based on Research Findings from Initial Usability Study

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#5562]
## User Story:
As a veteran, I need a submit a BDD claim so I can get my benefit soon after my separation.

After the first major round of usability testing (#5559) is conducted, we will have a better idea of what the design of the BDD process should look like.  This ticket is a placeholder for that work.  We believe some of the major areas of design will be around the gating and information about what qualifies or does not qualify for a BDD claim. 

## Tasks
- [x] Mockups updated in InVision with findings from first round usability studies
- [x] Split off stories for different design changes (possibly) from research findings

## Acceptance Criteria:
- [x] Delivered updated wireframes
- [x] Design reviewed and accepted

## Configuration
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by luke-gcio** [comment]
https://vsateams.invisionapp.com/share/BUWOTNKFPK7#/screens
