### ISSUE TITLE
[DD][EKS] Crashback loops alerts

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#55637]
## Description

While sometimes restarts are necessary, when crashloops continues for a long time, it may indicate pods are having issues or the image committed is not valid. It would be good to have an alert to indicate if pods are looping at a high rate

## Tasks

- [x] Create crashloop backoff alert in Datadog
- [x] Send alert to slack or PD 

## Acceptance Criteria

- [ ] Alert exists in Datadog
- [ ] It posts to the correct channels and pager duty

**Comment by LindseySaari** [comment]
I started on this ticket and [created the alert here](https://vagov.ddog-gov.com/monitors/122290). I would like for this to eventually alert the oncall and devops-alerts, but will have it post to the test channel to work out any kinks

**Comment by LindseySaari** [comment]
[I've updated the alert ](https://vagov.ddog-gov.com/monitors/122290)with the appropriate groups for alerting.
