### ISSUE TITLE
Login.gov adoption team: Sprint 17 (3/30 - 4/12)

### ISSUE THREAD

**Issue by elizabethkochBT** [department-of-veterans-affairs/va.gov-team#55634]
## PTO

- Carl 3/30 - 4/4
- Steve 3/30 - 3/31, 4/5 - 4/7
- Carolyn 3/31 - 4/4
- Ksenia 3/31
- Tom 3/20 - 4/3
- John 3/23 - 4/6

## Sprint 17 Priorities

 - Organic adoption: Incorporate feedback to get ready for midpoint review
 - Dashboard: Finish automating ETL
 - Grandfathering: Finish usability testing and define insights
 - Grandfathering: Finalize technical approach & document business rules (ie Eligibility, etc) + any open questions
 - Iterate on comms strategy &amp; specific DSL content based on feedback, share with stakeholders?
 - In-Person Proofing: Kickoff & create initial backlog

 
## Retro Board

[Sprint 16 Retro](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1677768711421/aad15b9308afe560c52a1beddefe388840ae239d?wid=0-1678115385246)

### Discussion Topics/Retro Action Items
 - [ ] elizabeth and anthony will get clarity around collab cycle (organic adoption) with core
 - [ ] come up with a way to schedule regular notetakers for the identity working group 
 - [x] anthony will take notes at one of the next identity working group session
 - [x] ask for clarification in standup if you're not sure whether you need to attend a meeting or not
 - [x] over share in #vagov-identity or #identity-research so we're working in the open
 - [x] demo prep optional for people who aren't presenting
 - [x] start slack thread on mondays to start demo prep async

### Legacy credential migrations & Login.gov proactive adoption
 - [ ] Login.gov proactive adoption Roadmap #51104
 - [ ] Start preparing for grandfathering accessibility testing #55336
 - [ ] Pull Organic experiment events from GA into DOMO - GA Dev env #55329
 - [ ] Automate process to easily ingest IAM MPI data and report on CSP counts #51861
 - [x] Mock up organic adoption flow in mobile #55503
 - [ ] Automate process to easily ingest IAM SSOe data and report on CSP counts #55960
 - [ ] Analyze and synthesize research from round 1 of testing grandfathering journey(s) #54924
 - [ ] Make a plan for sending out and updating the comms migration board #56049
 - [ ] Research: Backend logging #56089
 - [ ] Conduct research sessions to test grandfathering journey(s) with Veterans #53386
 - [ ] Prep for help center discussions #55474
 - [ ] Reporting for organic adoption experiment #53790
 - [ ] Modal GA tagging for organic adoption experiment #53788

## Collab Cycle Tasks 
 - [ ] tbd
