### ISSUE TITLE
[QA] 10-10EZ: AIQ - review/update test cases

### ISSUE THREAD

**Issue by eflaherty** [department-of-veterans-affairs/va.gov-team#55642]
## Background

AIQ was removed in 2/2023 and the related test cases in TestRail will be reviewed and updated appropriately.

## Tasks
- [ ] Review and update manual test case
- [ ] Review and update automated test cases
- [ ] Review and update regression test cases

## Acceptance Criteria
The test cases are updated accordingly and match current functionality.

**Comment by eflaherty** [comment]
Manual test:
1. https://dsvavsp.testrail.io/index.php?/cases/view/12796

Automated tests:
1. https://dsvavsp.testrail.io/index.php?/cases/view/12901
2. https://dsvavsp.testrail.io/index.php?/cases/view/13159
3. https://dsvavsp.testrail.io/index.php?/cases/view/13160
4. https://dsvavsp.testrail.io/index.php?/cases/view/13161

Regression tests:
1. https://dsvavsp.testrail.io/index.php?/cases/view/31603
2. https://dsvavsp.testrail.io/index.php?/cases/view/31604
3. https://dsvavsp.testrail.io/index.php?/cases/view/31605
4. https://dsvavsp.testrail.io/index.php?/cases/view/31606
5. https://dsvavsp.testrail.io/index.php?/cases/view/31607
6. https://dsvavsp.testrail.io/index.php?/cases/view/31608

**Comment by eflaherty** [comment]
**Cypress Tests:` vets-website/src/applications/hca/tests/e2e/hca-aiq.cypress.spec.js`**
Ran the automated tests locally and they're failing as expected on the call to `advanceToAiqPage`

**Obsolete mocks:**
```
vets-website/src/applications/hca/tests/e2e/fixtures/mocks/feature-toggles-aiq.json
vets-website/src/applications/hca/tests/e2e/fixtures/mocks/mockPrefillAiq.json
vets-website/src/applications/hca/tests/e2e/fixtures/mocks/mockUserAiq.js
```

**Tests that import obsolete mocks (from above):**
```
./hca-service-info.cypress.spec.js (import featureToggles from './fixtures/mocks/feature-toggles-aiq.json';)
./hca-dob.cypress.spec.js (import featureToggles from './fixtures/mocks/feature-toggles-aiq.json';)
```

**Comment by eflaherty** [comment]
just a side note on other hca cypress tests - hca-service-info.cypress.spec.js is failing.

**Error**
  1) HCA-Service-Info
       displays error message on service start date, with age less than 15 years old :
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `#1-continueButton`, but never found it.
      at advanceToServiceInfoPage (http://localhost:3001/__cypress/tests?p=src/applications/hca/tests/e2e/hca-service-info.cypress.spec.js:4189:6)
      at Context.eval (http://localhost:3001/__cypress/tests?p=src/applications/hca/tests/e2e/hca-service-info.cypress.spec.js:4245:5)

All other tests are passing, here's the summary:
<img width="817" alt="image" src="https://user-images.githubusercontent.com/20667501/231895866-fe7d2135-f611-4a00-bea9-21b35cb3e790.png">
