### ISSUE TITLE
[FE] Profile: Update notification preferences so that the feature flag can filter by channel (email/text)

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#55657]
## Background

Discussed in 3.23.23 meeting with VA Profile and VANotify.

**Ideally, this is completed in Sprint 7 so that VA Profile can meet a 4/18 deadline. If this gets moved back in planning, please let VA Profile know so they can adjust accordingly.**

We already have notification preferences live for Rx refill and prescription shipments for text, and we need to eventually add email as a channel, but not yet. However, VA Profile is currently ready to support both in their backend, so we need to adjust our feature flag so it allows us to turn the "text" preference on while keeping the "email" preference off until we are ready.

## Tasks

- [x] Update feature flag so we can turn notification preferences on and off by channel for individual items
- [x] Let VA Profile know when this is ready to test. **Samara may not be here, so Adam or Berni or anyone should get in touch with Mike Richard to confirm the update.**
- [x] Test that the flag works
- [x] Turn flag on once testing is complete

## Acceptance criteria

- [ ] Feature flag works for Rx refill and Prescription shipments so that the existing "text" preference is still live in prod, and the pending "email" preference is still behind a feature flag and does not show in prod.

**Comment by adamwhitlock1** [comment]
I've completed the work to filter out email channel from notifications. I have posted in the Va Profile slack channel to get some notifications updated to include the email channel in the lower environment and will follow up to test once they are coming back from the endpoints.

**Comment by adamwhitlock1** [comment]
Mike responded in the VA Profile slack channel that he will turn on some email channel items in the lower environments so that we can test this work in staging.

https://dsva.slack.com/archives/C7TE0PFTL/p1681233856744039

I'm going to bump this down to a 1 point ticket as I would imagine this will carry into the next sprint for mostly validation or any fixes that arrise.

**Comment by BerniXiongA6** [comment]
Thanks @adamwhitlock1

**Comment by mtcA6** [comment]
@adamwhitlock1 uh oh I should have made a note as to why we're blocked here but I didn't. Are we still waiting on VA Profile folks to make something available for testing?

**Comment by adamwhitlock1** [comment]
This work is done and in place on the site. Closing
