### ISSUE TITLE
[FE] Profile: Update notification preferences so that it filters out the new QuickSubmit group

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#55658]
## Background

Discussed in 3.23.23 meeting with VA Profile and VANotify.

**Ideally, this is completed in Sprint 7 so that VA Profile can meet a 4/19 deadline. If this gets moved back in planning, please let VA Profile know so they can adjust accordingly.**

VA Profile is adding a new notification preference group that we **do not** need to show in the VA.gov interface. This group is called "QuickSubmit", and we need to add a filter so it doesn't show in the profile.

## Tasks

- [ ] Add filter to hide the new QuickSubmit group
- [ ] Let VA Profile know when this is ready to test. **Samara may not be here, so Adam or Berni or anyone should get in touch with Mike Richard to confirm the update.**
- [ ] Test that the filter works
- [ ] Turn flag on once testing is complete

## Acceptance criteria

- [ ] Filter works to hide the QuickSubmit group from VA.gov.

**Comment by adamwhitlock1** [comment]
Started a branch for this. The group based blocking is done by ID, and there isn't one yet for quick submit, so this will be blocked until VA Profile sets it up and gives us that information.

**Comment by mtcA6** [comment]
@adamwhitlock1 VA Profile provided us with the ID. Group = 5, Item = 12
![image](https://user-images.githubusercontent.com/129431463/236479676-2c8f8725-d75d-4ce1-abec-1b8f88e12880.png)

**Comment by adamwhitlock1** [comment]
This toggle has been deployed and I have validated it. @mtcA6 if you would like to validate it, the feature toggle name is: `profile_show_quick_submit_notification_setting` and can be turned on freely within staging to test the show/hide.

![Screenshot 2023-05-11 at 12.55.38 PM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/88aec6dc-4c36-4d7a-9197-41a06c41d4ad)

**Comment by mtcA6** [comment]
This worked as expected closing it out! Tested on the phone w Adam.

**Comment by adamwhitlock1** [comment]
I did let them know, and they were testing it in staging with their partners. VA Profile should follow up with us when they are ready for use to release this to production.
