### ISSUE TITLE
[EKS] Deployment Dashboard

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#55653]
## Problem Statement

Currently in order to figure out what commit is being used in Argo for vets-api, you have to do the following [steps](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2452193284/Vets+API+on+EKS#Deploy-Process-Details). That is a bit of effort involved. 

It would be nice to have something similar to how [FE Dashboard](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/) has for VFS members

How might we make it easier for engineers to see PRs and commits being released to vets-api via EKS?

## Tasks

- [ ] Discovery: Is this something that can be done in Argo? Are there other options so we don't have to completely recreate a wheel for this dashboard?
- [ ] Jenkins provides this - review current state in Jenkins
- [ ] Talk with Eric about option of adding to a dashboard he is building.

## Acceptance Criteria

- [x] Visual for PRs and commits being released
- [x] MVP dashboard
- [x] add analytics trackers on the dashboard
- [x] create a collab ticket for FE and BE CoP post-mvp work
- [ ] deployed to fly.io  (does it need to be behind socks? no... info all from public api)

**Comment by laineymajor** [comment]
Not the highest priority, but will likely move up in prio + be easier was CD is enabled.

**Comment by rjohnson2011** [comment]
Currently researching how to best accomplish this goal. ArgoCD has [tracking and deployment strategies](https://argo-cd.readthedocs.io/en/stable/user-guide/tracking_strategies/) but this seems to differ from the goal of a single source of truth deployment dashboard. 

Cloned the `veteran-facing-services-tools` repo and currently investigating how the [frontend support dashboard](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/) was built.

**Comment by LindseySaari** [comment]
@rjohnson2011 I was talking with Eric, and he's working on a somewhat similar feature to display outdated gems. I would sync with Eric to see if there is better place to deploy this. I don't think that the deployment dashboard necessarily has to live in the veteran-facing-service-tools.

**Comment by rjohnson2011** [comment]
@LindseySaari Thanks, I've been working the past few days on running the veteran-facing-service-tools repo and have been running into numerous errors to get this running locally. I am definitely open to creating something greenfield / in collaboration with Eric - though the tradeoff for that might be that we can't reuse components already created for the frontend dashboard. I'll touch base with Eric about the objectives and how to best accomplish this.

**Comment by laineymajor** [comment]
@rjohnson2011 
- Is discovery complete?
- Eric is ready to work with you. Please connect with him first thing when you are complete with the internal work.

**Comment by laineymajor** [comment]
Actions from meeting with Eric:
https://api.va.gov/v0/status
https://dev-api.va.gov/v0/status
https://staging-api.va.gov/v0/status

1. get repo cloned locally
2. start integrating the octo kit api -> make calls to see what PRs are merged to master
3. create cross checks to the above links for the envs
4. cross-check logic to what's in GH vs va.gov statuses
5. build visualization for the above data

**Comment by laineymajor** [comment]
Please use these va.gov a11y friendly colors :)
https://design.va.gov/foundation/color-palette

**Comment by laineymajor** [comment]
Eric and Ryan to simplify color scheme

**Comment by laineymajor** [comment]
@rjohnson2011 can you update the color scheme per our convo earlier in the comments:

Please use these va.gov a11y friendly colors :)
https://design.va.gov/foundation/color-palette

DEPLOYED (GREENS: LIGHTEST TO TRUE GREEN)
dev - #e7f4e4
staging - #94bfa2
sandbox - #4aa564
prod - #2e8540

USE YELLOWS FOR WAITING FOR DEPLOY
