### ISSUE TITLE
[IaC][EKS][BRD] Remove ASG policies from Sandbox

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#55654]
## Description

There was an issue that recently occurred due to some resources still existing in BRD. They have been manually been brought down and issue been resolved. We need to double check that IaC has been brought down for all lower environments

## Task

- [x] Remove IaC in sandbox for vets-api
- [x] Double check lower environments IaC have been removed for vets-api

## Acceptance Criteria
- [x] IaC has been removed for lower environments
