### ISSUE TITLE
[Development] BDD: Benefits Delivery at Discharge

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#5568]
## Product Outline
[TBD](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level Epic
As a veteran, I need to be able to apply for my VA benefits before I separate from the DoD so I can get my benefits in a timely manner.

As a developer, I need to be able to code this up!  This Epic is rolled up into #1834 and all of the launch checklist etc is captured there.

## Tasks
- [ ] Complete FE build out
- [ ] Complete BE build out
- [ ] Test all the things

**Comment by luke-gcio** [comment]
Made as an issue and not an Epic.  Closing out.
