### ISSUE TITLE
[Design] Create wireframe for complete page variation for when vets api fails to talk to BTSSS API 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#55692]
### Description 

How might we communicate to Veterans that something went wrong on our end when vets api fails when attempting to submit the travel reimbursement claim request? 

Added a [new path in the user flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677531124203/5edcfd3ea4b1eaf1ef082d56782a8b3291ef3932?sender=u37bb983bd3fc3cc00c7d3286
) for this scenario. I.e., check in was successful, but call to vets-api failed. 

### Tasks

- [ ] Create new wireframe for this new complete page variation. The content to use for the h1 and travel warning alert are [shown here in the unified experience](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/bLgZZaV). Need to use this content and add it into the travel branch in Abstract.   
- [ ] Add it to the [travel pay collection in Abstract](https://share.goabstract.com/6b69924f-904b-4d78-b5a1-4c40ed65e4d2?collectionLayerId&mode
).  

Front-end is aware of this change. 

### AC

- [ ] Wireframe created in sketch. 
- [ ] Wireframe added into [travel branch in abstract](https://share.goabstract.com/6b69924f-904b-4d78-b5a1-4c40ed65e4d2).

**Comment by loripusey** [comment]
Note that the engineering work for this has already been completed, we only need to update the Sketch files as part of our design artifacts.

**Comment by ytsaoca** [comment]
Hi @benbrasso-agile6 ,

I found that we already had [this wireframe](https://share.goabstract.com/f5eae64b-62b1-4c5b-bd23-16b0f2eeca6e?mode=design&sha=317ae8670525a263859b6e2e970f600e2ccd8fe3) but you mentioned that we were no longer need it. Do we just add it back?

**Comment by benbrasso-agile6** [comment]
Great. Yes, let's add it back. And, we'll want to add that extra sentence in the second alert to explain to Veterans why we can't process their claim. The content for the second alert should be: 

> We're sorry, something went wrong on our end. We can't file a travel reimbursement claim for you now. But you can still file within **30 days** of the appointment. 

> [Find out how to file for travel reimbursement](https://www.va.gov/resources/how-to-file-a-va-travel-reimbursement-claim-online/)

**Comment by benbrasso-agile6** [comment]
Looks perfect to me! I think we can go ahead and merge it up into this branch: https://share.goabstract.com/6b69924f-904b-4d78-b5a1-4c40ed65e4d2

**Comment by benbrasso-agile6** [comment]
@zach-park can you merge this up into the travel pay branch?

**Comment by loripusey** [comment]
@zach-park has this been merged?

**Comment by benbrasso-agile6** [comment]
Thx
