### ISSUE TITLE
Enrollment verification work: Create FAQs and determine where to place content from legacy page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#55719]
## Issue Description

Now that the enrollment verification tool is live, we have follow-up work to do to migrate legacy content. The 2 legacy pages we're pulling content from are:

- benefits.va.gov/gibill/isaksonroe/verification_of_enrollment.asp
- https://benefits.va.gov/gibill/isaksonRoe/EV_FAQs.asp

We will need to
1. Create an FAQs page in R&S
2. Review the main legacy page and figure out if the content that isn't accounted for yet on our tool landing page should be added to our modern page or to the new FAQ or a separate R&S page

Word doc that Katherine started with info: [https://app.zenhub.com/files/133843125/dad8664a-0a31-4974-9bb3-c97e4eee6b33/download](https://app.zenhub.com/files/133843125/dad8664a-0a31-4974-9bb3-c97e4eee6b33/download) 

Once this content is accounted for we need to set up redirect tickets.

## Tasks
- [x] Create FAQs page (Katherine)
- [x] Revise modernized page if needed (Katherine)
- [x] Create new page if needed (Katherine)
- [ ] Review (Beth)
- [ ] Send to stakeholders (Katherine)
- [ ] Copyedit (Megan)
- [ ] Publish (Megan)
- [ ] Set up redirect tickets (Randi)

## Acceptance Criteria
- [ ] Content from legacy pages are live on our site

**Comment by katherine-fung** [comment]
Hi @bethpottsVADEPO, 

After reviewing the Teamsite enrollment verification and FAQ pages, I've created a draft for enrollment verification FAQs. 

[https://app.zenhub.com/files/133843125/afa60444-c266-4bbe-b389-4c62646216aa/download](https://app.zenhub.com/files/133843125/afa60444-c266-4bbe-b389-4c62646216aa/download)

There's also 1 detail we should consider putting on the existing modernized enrollment verification page:  

- The legacy page says students with international phone numbers can't verify their enrollment by text. We should consider adding a note about this to the modernized static page for enrollment verification. 

suggested: "**Note:** You must have a cell phone number with a U.S.-based phone carrier to verify your enrollment by text. If you have an international phone number, you'll need to verify your enrollment another way."

I've emailed education SMEs with some initial questions about enrollment verifiation. I also have additional questions I'm noting here. 

1. The legacy page says you don’t need to verify enrollment if you’re enrolled less than half time. Is it possible to be enrolled less than half time and get kicker payments? If so, do those students need to verify their enrollment? 

2. We say that if someone doesn't opt in to verifying by text, we'll default to having them verify by email. If they choose to verify online, is there a way they can opt out of verification emails? 

3. Can we say anything more about what happens when your enrollment changes? How can someone start verifying their new enrollment details and resume payments again? 

Here's what the legacy page currently says: "If you provide a 'No' response, VA will review your enrollment status and follow up with you and your School Certifying Official (SCO) if necessary. VA will adjust benefits when appropriate and notify you if changes are processed. We also recommend following up with your SCO to ensure your enrollment record with VA has been adjusted."

4. We have a question "How can I check my enrollment information before I verify?" We tell people to contact their school certifying official, or check their award letter. If someone is verifying online, does the tool also show them their enrollment information? 

5. Can someone help us understand this information on the legacy page? 

“For example, if you started classes on February 21 but didn’t receive an opt-in text until March 2, your February and March enrollment will automatically be verified. Note: In this scenario, you wouldn’t receive an enrollment verification text at the end of February or March.” 

Why would someone not have to verify at the end of March if they got the opt-in text at the start of March? 

6. There are a few other QA I didn't fully understand, so I've left them out of the draft for now: 

- "My school submitted my enrollment information after I had already started the term.
You are still required to verify enrollment unless your term has already ended." 

- "Does anything change about how my school will certify my enrollment?

Yes. Your school is now required to certify your enrollment again after the drop-add period has closed to ensure VA has the most accurate enrollment information and help eliminate overpayments."

7. I left this question off the page, because it seemed more about payments than about enrollment verification itself: 

"I verified my enrollment, but I didn’t receive my payment.
You can contact the Education Call Center at 1-888-GIBILL-1 (1-888-442-4551) domestically or 001-918-781-5678 internationally to request a status update for your payment."

**Comment by bethpottsVADEPO** [comment]
> * The legacy page says students with international phone numbers can't verify their enrollment by text. We should consider adding a note about this to the modernized static page for enrollment verification.

I agree, @katherine-fung, thanks for identifying this. You can add this to the list of things to flag for stakeholders and get their thumbs up on! I have a small edit to the "Note" text you wrote up:

**Note:** You must have a U.S. cell phone number to verify your enrollment by text. If you have an international phone number, you'll need to verify your enrollment another way.

Did you hear back from SMEs about the above questions?

**Comment by katherine-fung** [comment]
Beth and I met this week to discuss the EV FAQ draft. We've: 
- created a new ticket #57073 as part of the work to migrate enrollment FAQ content from the legacy site.
- sent the stakeholders a list of questions about the content 

I've created this draft in Drupal for now: 
http://preview-prod.vfs.va.gov/preview?nodeId=55607 

And I'll set up a meeting next week for us to research the SEO around enrollment verification for the H1.

**Comment by coforma-terry** [comment]
Needs follow up.

**Comment by katherine-fung** [comment]
We can close this ticket. The enrollment verification FAQs page is done @coforma-terry @strelichl 

cc @bethpottsVADEPO

**Comment by katherine-fung** [comment]
My mistake @strelichl. I confused this with a different page. This work is still open. I've sent a follow-up email to the education team. I'll re-open the ticket.

**Comment by katherine-fung** [comment]
I haven't returned to this work.

**Comment by katherine-fung** [comment]
Update: @aprocik1 and @d-beyer are taking on this work as part of education migration.
