### ISSUE TITLE
Restructure Practice Area Operational Guidance

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#55710]
## User Story
As a Governance team member, I want to ensure that all of our practice area operational guidance for Design Intent has a consistent flow, tone and voice so that Governance team products uphold our expectations of VFS teams.

Assignee: @CherylEvans 
 

## Description
Governance team members have peer reviewed the practice area Design Intent operational guidance for design, IA and accessibility to ensure there were no gaps, overlaps and/or inconsistencies across practice areas when it comes to how we approach and complete a Collaboration Cycle Design Intent. Now that we are confident that the content in the 3 guidance docs is complete, we want to make sure that each guidance doc flows similarly, and meets our content standards for tone, voice and grammar/formatting.

## Impacted Artifacts
[How to document feedback for a Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1934426130/How+to+document+feedback+for+a+Design+Intent)

## Tasks
- [x] Review feedback from ticket #55709 and follow up with team members for clarification if needed
- [x] Ensure all guidance docs are written in a consistent voice, tone, use plain language and use consistent language
- [x] Reorganize headings/sections so all docs have the same flow
- [x] Incorporate [How to document feedback for a Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1934426130/How+to+document+feedback+for+a+Design+Intent) into all 3 practice area docs.
   - Note: Governance team members should utilize both their practice-area specific guidance and the How to document feedback for a Design Intent guidance. It is important that the document feedback guidance and practice area guidance flow and read as 1 piece of guidance. This means, that anything in the document feedback guidance does not need to be in the practice area guidance. Anything that is applicable across the board, regardless of practice area, should be in the document feedback guidance.
   - If changes need to be made to the document feedback guidance, then capture them here and a new ticket will be created for implementation of those changes.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] All practice area specific guidance for Design Intent has consistent content and flow.
- [x] Governance team members are able to refer to their specific practice area guidance for DI for completing a DI

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
Reviewing feedback from ticket [55709](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55709)

**Comment by CherylEvans** [comment]
@shiragoodman [How to document feedback for a Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1934426130/How+to+document+feedback+for+a+Design+Intent) is incorporated into the following practice area specific documents:

- [How to complete an Accessibility review for Design Intent](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2611511338/55648+-+How+to+complete+an+Accessibility+review+for+Design+Intent)
- [How to complete a Design review for Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2605056001/How+to+complete+a+Design+review+for+Design+Intent)
- [How to complete an Information Architecture (IA) review for Design Intent](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2601025548/55649+-+Sara+-+How+to+complete+an+Information+Architecture+IA+review+for+Design+Intent)
- [How to complete a Content review for Design Intent](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2598371379/56777+-+How+to+complete+a+Content+review+for+Design+Intent)

Please let me know if you're good with these, and I will move them over to PP&S to their appropriate locations.

**Comment by shiragoodman** [comment]
these look good to me - thanks @CherylEvans !

**Comment by CherylEvans** [comment]
All docs now live in this space: [Link](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1934426130/How+to+document+feedback+for+a+Design+Intent)
