### ISSUE TITLE
[Development] BDD: Benefits Delivery at Discharge

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#5571]
## Epic Description
As a veteran, I need to be able to apply for my VA benefits before I separate from the DoD so I can get my benefits in a timely manner.

As a developer, I need to be able to code this up!  This Epic is rolled up into #1834 and all of the launch checklist etc is captured there.

## Tasks
- [x] Complete FE build out
- [x] Complete BE build out
- [x] Test all the things

**Comment by vhenry07** [comment]
BDD rolled out at 100%.
