### ISSUE TITLE
Updates to download benefits letters 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#55711]
## Issue Description

We recently updated some links on our [Download VA benefit letters](https://www.va.gov/records/download-va-letters/) page in ticket #55062 but after conversations with Mikki and Beth and work done by the benefits 1 team, we need to make some other bigger changes to the page.

Mikki's guidance:

- We should add information to the "Which types of letters can I get" section to be more clear on what is available. A list can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/c3d525f9b0b2c73c54211cc63777b023046163b4/products/benefit-letters
- The home loans COE is a benefit letter, so this should be referenced on the page in the main content. I could see this being placed under the "Which types of letters can I get" heading, indicating that the COE is available separately.
- The claim status and education letters could be added to the "More information" box at the bottom

Laura also made other edits to the page in a previous version in Drupal so we can review the revision history when working on other changes.

## Tasks
- [x] Update page in Drupal (Katherine)
- [x] Review (Laura)
_stopped here during contract gap_
- [X] Send to stakeholders (Amy Lai sent to Andrew Gray)
- [ ] Copyedit (Lauren V.)
- [ ] Publish (Lauren V.)

## Acceptance Criteria
- [ ] Page is updated on live site

**Comment by katherine-fung** [comment]
Hi @laurwill, I started making these changes per Mikki's guidance (and added back an H2 and another change that you made in a previous revision). 

I have a question about this part of the guidance though: 

> "The home loans COE is a benefit letter, so this should be referenced on the page in the main content. I could see this being placed under the "Which types of letters can I get" heading, indicating that the COE is available separately.
> The claim status and education letters could be added to the "More information" box at the bottom"

We currently have the questions "What types of VA letters can I download using this tool?" and "How can I download a letter or document that isn’t available from this tool?" 

I think the guidance suggests we move the housing COE under the "What types of VA letters can I download using this tool?" which might be confusing to people. 

Do you think we can ask Mikki about keeping the "How do I download a letter or document that isn’t available from this tool?" question? Or do you think we should approach this a different way?

**Comment by katherine-fung** [comment]
Hi @laurwill, 

Thanks for chatting about this ticket today. 

Here's the draft for review: 
http://preview-prod.vfs.va.gov/preview?nodeId=471 

- I checked with Matt Self about the benefit letters. It seems those letters only describe disability benefits, so I've updated the letter type headers accordingly. ([link to our Slack with examples of letters](https://app.slack.com/client/T03FECE8V/C04KHCT3ZMY))

- I've also added a link to the CST in the "More information" section, per Mikki in ticket #45908.  
(She wrote: "So here's what I believe we need to do on the existing download letters page

We should add information to the "Which types of letters can I get" section to be more clear on what is available. A list can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/c3d525f9b0b2c73c54211cc63777b023046163b4/products/benefit-letters
The home loans COE is a benefit letter, so this should be referenced on the page in the main content. I could see this being placed under the "Which types of letters can I get" heading, indicating that the COE is available separately.
The claim status and education letters could be added to the "More information" box at the bottom")


- Here's a [link ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/c3d525f9b0b2c73c54211cc63777b023046163b4/products/benefit-letters)to the types of letters available in the VA benefit letters tool.

**Comment by aprocik1** [comment]
@laurwill, I found my way to this ticket through some work I'm doing with an education product team. Based on the revisions log in Drupal, I think all the edits captured in this ticket have been incorporated. Have you reviewed this page? Do you know if SMEs have reviewed this page? 

I need to make a small update to a crosslink label and URL on this page. It'd be great if we could publish Katherine's changes at the same time.

**Comment by aprocik1** [comment]
Current status: Katherine's draft edits in Drupal haven't been published. We published small changes to this page in December 2024, and then reverted it back to the previous version with those draft edits included. This page needs to be reviewed and approved by SMEs.

**Comment by mnorthuis** [comment]
Consider this draft work with the current letters work epic #99477

**Comment by mistymg** [comment]
I'm taking this task out of it's current parent ticket to handle as a one-off need. I reached out to Amy Lai [in Slack](https://dsva.slack.com/archives/C04KHCT3ZMY/p1761150802530559?thread_ts=1761142649.092319&cid=C04KHCT3ZMY) to see who the SME is. Moving to blocked given we need the green light to publish and the govt shutdown is affecting that.

**Comment by mistymg** [comment]
Amy Lai confirmed [in Slack](https://dsva.slack.com/archives/C04KHCT3ZMY/p1764720061320359?thread_ts=1761142649.092319&cid=C04KHCT3ZMY) that VBA SME (Andrew Gray) approved publishing these changes to this page. I made a slight tweak to remove mentions of "tool" in the Q&A.

@laurenvocke-va This [page](http://preview-prod.vfs.va.gov/preview?nodeId=471) is ready for your review and can be published whenever. Once live, we can close out this ticket. Thanks!

**Comment by laurenvocke-va** [comment]
Reviewed and published. I'll confirm when it's live!

**Comment by laurenvocke-va** [comment]
Confirmed live! Closing this ticket
