### ISSUE TITLE
Feedback from Product Lead and Manager Expectations

### ISSUE THREAD

**Issue by dmkosko** [department-of-veterans-affairs/va.gov-team#55721]
## What are building
Compiling feedback from this closed issue ticket #46192

## Why are we pursuing this opportunity/problem
As we're constantly iterating, it also provides the opportunity for feedback from individuals in this space. 

---
## Tasks
- [ ] Lorem

---
## Definition of Done
- [ ] identify existing versions of each item within the various components of OCTO (ask everyone in product ops to weigh in and then put out a question with list we have in the #product channel.
- [ ] use CoP meetings to review status and get feedback or competing version from product people
- [ ] identify the processes and docs in place that use existing versions
- [ ] identify any work currently underway to update related docs or processes
- [ ] coordinate with the product ops team to create a single, OCTO version of each item
- [ ] update doc links, archive old docs, and update processes to direct users to the new version
- [ ] ensure the new version is listed in onboarding docs and processes

---
## How to configure this issue
- [ ] **Review issue** with the Product Ops team
- [ ] **Prioritize**  
  - label accordingly: 
    - Low Priority - 🟢
    - Medium Priority - 🟠
    - High Priority - 🔴
- [ ] **Add Assignees** (who will do this work?)

**Comment by dmkosko** [comment]
- “Is it expected that all teams will always have a PO?”
  - This was an interesting observation from a team that no longer exists.
  - It was a “non-traditional” team that provided a service to other teams (QA, 508 guidance)
- ‘What do we do when there’s gaps [in meeting expectations]?’
  - We assume that open communications would help resolve situations like this
  - But it raises an interesting question nonetheless about how we help teams maintain a certain standard
- ’For some, there’s a ‘here if you need us’ feeling when it comes to some expectations of gov folks
  - This isn’t inherently a negative thing; it points to trust between gov folks and product team
  - It does naturally follow-on from the previous two observations and assumptions of open communication
- Folks remarked on the tension between a) wanting more specificity (e.g. for communications of direction between teams) and b) letting teams be themselves.
- They ultimately suggested framing this doc as a “baseline” might allow teams to build on top of these expectations.
- Some people mentioned a lack of awareness of the expectations themselves
- People were unsure what to do if there’s disagreement between PO and team or within a team

**Comment by lkoenigsberg** [comment]
@dmkosko , I've yellow highlighted the section of content to add to Product Expectations in the original document linked above.   Please let me know when that's complete.

**Comment by dmkosko** [comment]
@lkoenigsberg, all set. That section was added to the "Overview" of Product Expectations
