### ISSUE TITLE
Setting up platform-support as a feedback funnel

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#55729]
## Purpose
We have determined that the #vfs-platform-support channel is a solid mechanism to support feedback that funnels into the continuous feedback Portal, which may be a web page with a form input. [How do we set this up?](https://vfs.atlassian.net/wiki/spaces/~318780155/pages/2577170507/Using+vfs-platform-support+as+a+feedback+funnel)

[Flow chart of channel](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1679607880960/dcb763f273a49ef82a47a45b6e83cfd3fd935065?sender=u9ea6bd3ca12795949b606150)

## Tasks
- [x] Determine and map what the technical options are for funneling feedback
- [x] Select the funneling options that make sense
- [x] Test internally if the funnel is working
- [x] Determine where public documentation for this should live

## Acceptance Criteria
- [x] Prototype shows that feedback can funnel from vfs-platform-support to a website link (change made so this ticket isn't blocked by Portal's existence/launch)
