### ISSUE TITLE
[Development] BDD: Back-End Initial MVP API Discovery and Design

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#5575]
## User Story:
As a veteran, I need to be able to apply for my VA benefits before I separate from the DoD so I can get my benefits in a timely manner.

This story is to sort out which APIs we will be integrating with to support in the initial MVP design.  Any artifacts that generally get created to document this step should be created here.

## Tasks
- [ ] Document which APIs we are using and which methods/etc
- [ ] @SMLuthi  I need some help here since I am not yet familiar with all of the tasks involved in a typical API discovery/design phase

## Acceptance Criteria:
- [ ] PR held
- [ ] Tests passing

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by SarahJaine** [comment]
## Notes on Document "STR 2.1 Integration Architecture SHA Addendum"
[STR 2.1 Integration Architecture SHA Addendum.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4476115/STR.2.1.Integration.Architecture.SHA.Addendum.pdf)

- Goal: reduce incidence of duplicate exams

- View from 50k feet:
	- VA tells DoD a claim was filed and submits Notification of Interest (NOI) to request pre-discharge service treatment records (STRs)
	- DOD gives pre-discharge service treatment records (STRs) to the VA
	- Exam Vendor performs Separation Health Assessment (SHA) exams and gives those exam results to VA, VA passes results to the DoD

- Agency and system level interaction:
	- Service member 1. updates Release from Active Duty (RAD) date, and 2. files a BDD claim or intent-to-file 180-90 days prior to RAD date
		=> Claim created by user in VA's VBMS Claim Services or VBMS UI
		=> pre-discharge claims are enumerated in the form "BSD255 - Request STRs for Pre-Discharge Claims Supporting Attributes List (SAL)", list EP and claim label
	- Exam Vendor performs SHA exam and returns results to VA
		=> Exam vendor submits results to VA's Data Access Service (DAS)
	- Claim is passed around within VA
		=> VBMS sends NOI with Pre-Discharge Claim Information Type to DAS.
		=> If RAD is updated in VBMS, new NOI is submitted with new date. (Can be mult NOIs for single claim.)
	- VA sends request to DoD for pre-separation Service Treatment Records
		=> VA Data Access Service (DAS) sends NOI to DoD's Health Artifact and Image Management Solution (HAIMS) system
		=> DAS will store the most recent/final NOI Submission Status message (indicates if NOI succeeded/failed to relay to HAIMS)
	- DoD sends VA pre-separation Service Treatment Records if the RAD date listed on the NOI has not passed
		=> After all 5 required STR documents are present, DoD's HAIMS transfers pre-separation Service Treatment Records to VA's DAS
	- VA sends Disability Benefits Questionnaires (DBQ- exam completed with private doctor for disability claims process) to DoD
		=> If DAS receives DBQ results before the RAD date, it sends results to HAIMS. Otherwise, it doesn't share.
	- After veteran separates, DoD sends final Post discharge records
		=> HAIMS will only send Post discharge STR manifest once all results are available and there is a certification memo.

**Comment by SarahJaine** [comment]
Same integrations needed as form 526 (disability comp).  Service Treatment Records (STR) attachment is handled by downstream process.
