### ISSUE TITLE
[Development] BDD: Back-End API Testing and Integration for Initial MVP

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#5576]
## User Story:
As a veteran, I need to be able to apply for my VA benefits before I separate from the DoD so I can get my benefits in a timely manner.

This story is to start doing some initial integration and testing with the APIs we will need for BDD.  Any artifacts that generally get created to document this step should be created here.

## Tasks
- [ ] Code up integration test on dev/staging with the API end-points
- [ ] @SMLuthi  I need some help here since I am not yet familiar with all of the tasks involved in this testing and integration phase (may just be thumbs up it works, I'm good with that)
- [ ] Possibly split this story out into dev/staging/prod how the MVI tickets were split off

## Acceptance Criteria:
- [ ] We know what our end-point is going to be doing and we are ready to officially code it up.

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
