### ISSUE TITLE
Content for users with existing Login.gov/ID.me accounts

### ISSUE THREAD

**Issue by CarlDickerson** [department-of-veterans-affairs/va.gov-team#55762]
### Description
In support of the plan to remove DS Logon as an option for signing in, awareness content needs to be developed to communicate this change to various user groups. This particular work will focus on Users who may have DS Logon, but in addition already have an ID.me or Login.gov account that works with VA (we know because they have used it to sign in previously at some point). They will not need to be migrated, but will need to understand that DS Logon will no longer be an option for logging into VA digital tools and that moving forward they should use their ID.me or Login.gov credentials.

Attached is a word document with options for proposed content-- 2 versions of an email and a post-sign in modal that would appear when a user who already has Login.gov or ID.me signs in with DS Logon account.[https://app.zenhub.com/files/133843125/595925cc-e5e9-4d3f-841a-324793c36375/download](https://app.zenhub.com/files/133843125/595925cc-e5e9-4d3f-841a-324793c36375/download)

### Tasks
- [x] Review document and provide content feedback (Aliyah and Laura)
- [x] Provide feedback to Carl
- [x] Update content based on research recommendations

**Comment by laurwill** [comment]
Hi @CarlDickerson ! 
As we discussed in our recent syncs, Aliyah found some draft content work on email and modal content from the [2022 MHV transition project](https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EXlaeiACcsxKhyw2DFZLMqsBitZUTPFpcP50EZTn_Bkaug?e=fb2NS1). We can borrow any relevant messaging from that work, since this is so similar.

We reviewed this DS Logon email and modal content and I added some comments to a [Sharepoint version here](https://dvagov-my.sharepoint.com/:w:/g/personal/laura_willwerth_va_gov/ESRyyRhYhYdAv-5LK4kDNW8BRkUL8G9dceqR1VvBfjH_qw?e=Vvv1b8). Want to take a look at the comments and take a pass at incorporating some of the messaging from the 2022 MHV work? Then we can chat in our next sync. Let us know if you have questions or want to chat before then. Thank you!
