### ISSUE TITLE
Centralize Logging: Get all logs into Datadog and deprecate Loki

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#55774]
## Problem Statement 
Currently:
- Logs are spread across multiple systems (Loki and Datadog), making them difficult to correlate by Platform and VFS teams
- Multiple systems have to be maintained by Platform creating maintenance overhead 

How might we consolidate logging as much as possible to allow ease of traceability?
How might we reduce the number and variety of systems that must be maintained?

## User Impact
- Platform and VFS engineers are blocked from accurately understanding and debugging applications
- Platform and VFS engineers are blocked from developing and enhancing monitors and alerts

## Where was this problem reported?
Reported frequently in Postmortems and support issues from both Platform and VFS teams

## How well do we understand the problem?
We have a good understanding of the technical problem space and have identified potential solutions.
Areas that need further investigation:
- What are our log retention requirements, how do these affect migration, deprecation or sunset?
- What roles and permissions are needed by VFS teams to effectively leverage logging system?

## What is the acceptance criteria?
- [ ] A single centralized system provides:
  - [ ] Logging
- [ ] System is accessible to Platform and VFS users
- [ ] Users have sufficient permissions to effectively use tools without risk of causing a negative impact on other users
- [ ] Legacy logging system is deprecated (ie Loki)
  - [ ] Access by VFS and Platform teams is disabled
  - [ ] Loki Documentation is removed
  - [ ] Timeline for the sunset of Loki is created
  - [ ] Work item for the sunset of Loki is created
- [ ] Documentation exists for usage by Platform and VFS teams
- [ ] Onboarding and offboarding processes exist and are documented

## How should we measure success?
- How many incoming alerts can be resolved using the system
- How many VFS support requests can be resolved using the system 
- How many legacy systems are deprecated

## TODOs
- [x] Convert this issue to an epic
- [] Assign project team name
- [ ] Identify this project's OCTO and Vendor key POCs
- [ ] Identify specific VFS teams to be part of this project's acceptance
- [ ] Identify project target end date
- [x] Conduct project kickoff meeting
- [ ] Develop and implement a project communication plan
