### ISSUE TITLE
Centralize Monitoring: Provide write access for VFS and deprecate Grafana

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#55777]
## Problem Statement 
Currently:
- Metrics are spread across multiple systems (Grafana and Datadog), making them difficult to correlate by Platform and VFS teams
- Multiple systems have to be maintained by Platform creating maintenance overhead 

How might we consolidate monitoring as much as possible to allow ease of traceability?
How might we reduce the number and variety of systems that must be maintained?

## User Impact
- VFS engineers are blocked from accurately understanding and debugging applications
- VFS engineers are blocked from developing and enhancing monitors and alerts

## Where was this problem reported?
Reported frequently in Postmortems and support issues from both Platform and VFS teams

## How well do we understand the problem?
We have a good understanding of the technical problem space and have identified potential solutions.
Areas that need further investigation:
- What roles and permissions are needed by VFS teams to leverage the monitoring system effectively?

## What is the acceptance criteria?
- [ ] A single centralized system provides:
  - [ ] Monitoring
- [ ] System is accessible to Platform and VFS users
- [ ] Users have sufficient permissions to effectively use tools without the risk of causing a negative impact on other users
- [ ] Legacy logging system is deprecated (i.e., Grafana)
  - [ ] Access by VFS and Platform teams is disabled
  - [ ] Grafana Documentation is removed
  - [ ] Timeline for the sunset of Loki is created
  - [ ] Work item for the sunset of Loki is created
- [ ] Documentation exists for usage by VFS teams
- [ ] Onboarding and offboarding processes exist and are documented

## How should we measure success?
- How many incoming alerts can be resolved using the system
- How many VFS support requests can be resolved using the system 
- How many legacy systems are deprecated

## TODOs
- [x] Convert this issue to an epic
- [] Assign project team name
- [ ] Identify this project's OCTO and Vendor key POCs
- [ ] Identify specific VFS teams to be part of this project's acceptance
- [ ] Identify project target end date
- [x] Conduct project kickoff meeting
- [ ] Develop and implement a project communication plan

**Comment by batemapf** [comment]
re:

> The Platform has chosen Datadog as the 'single-pane-of-glass' monitoring tool but has not yet granted write permissions to VFS teams
Without properly scoped permissions, VFS teams could inadvertently re-configure others' dashboards and monitors, including those needed by Platform teams for ongoing observability and monitoring
Datadog lacks built-in features that allow the Platform to scope permissions (ie write access) to app- or team-specific resources, which means a solution is needed to enforce Datadog configuration standards and avoid disruption to resources in Datadog (i.e., dashboards, monitors, alerts) that the Platform depends on for day-to-day operations

it looks like you can restrict editing of monitors to specific roles (though i assume those roles are defined by the DOTS team, so maybe not practical). alternatively / additionally, alerts can be configured to trigger when a monitor is edited. might not be a perfect solution:

![image.png](https://images.zenhubusercontent.com/57d19681e40e5714b16e8696/e1b336b5-5612-43b5-8505-6384df21f213)

**Comment by mchelen-gov** [comment]
> re:
> 
> > The Platform has chosen Datadog as the 'single-pane-of-glass' monitoring tool but has not yet granted write permissions to VFS teams
> > Without properly scoped permissions, VFS teams could inadvertently re-configure others' dashboards and monitors, including those needed by Platform teams for ongoing observability and monitoring
> > Datadog lacks built-in features that allow the Platform to scope permissions (ie write access) to app- or team-specific resources, which means a solution is needed to enforce Datadog configuration standards and avoid disruption to resources in Datadog (i.e., dashboards, monitors, alerts) that the Platform depends on for day-to-day operations
> 
> it looks like you can restrict editing of monitors to specific roles (though i assume those roles are defined by the DOTS team, so maybe not practical). alternatively / additionally, alerts can be configured to trigger when a monitor is edited. might not be a perfect solution:
> 
> ![image.png](https://camo.githubusercontent.com/4dd5e257ab9b6c5e24aba3d33fabe2b650de12dbbcd382149f662c6308eab89c/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3537643139363831653430653537313462313665383639362f65316233333662352d353631322d343362352d383530352d363338346466323166323133)

Yup, we're trying to figure out how to get these roles configured and if they can be mapped from AD or other SSO.

**Comment by little-oddball** [comment]
Would encourage the addition of at least 1 spike related to role decomposition and experimentation.
