### ISSUE TITLE
Fix Ruby 3 Deprecation Warnings

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#55779]
## Issue Description
The Ruby 3 branch has some deprecation warnings. Let's fix them.

---
## Tasks
- [x] Fix the depreciation warnings

## Acceptance Criteria
- [x] The deprecation warnings that can be fix are fixed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by holdenhinkle** [comment]
Warnings:

```
---
  test_evss/disability_compensation_form/submit_form8940.perform_async_with_a_successful_submission_job_submits_successfully:
  - 'DEPRECATION WARNING: VCR: got `Encoding::UndefinedConversionError: "\xE2" from
    ASCII-8BIT to UTF-8` while trying to encode the ASCII-8BIT request body to the original
    body encoding (UTF-8). Consider using the `:preserve_exact_body_bytes` option to
    work around this.
  
    '
  - 'DEPRECATION WARNING: VCR: got `Encoding::UndefinedConversionError: "\xE2" from
    ASCII-8BIT to UTF-8` while trying to encode the ASCII-8BIT request body to the original
    body encoding (UTF-8). Consider using the `:preserve_exact_body_bytes` option to
    work around this.
  
    '


---
test_token_validation_indicates_token_is_invalid:
- 'DEPRECATION WARNING: Breakers is not implemented for service: TokenValidation

  '
test_token_validation_indicates_token_is_valid:
- 'DEPRECATION WARNING: Breakers is not implemented for service: TokenValidation

  '
test_token_validation_when_token_is_valid,_but_is_not_granted_access_for_the_requested_scope_indicates_token_is_invalid:
- 'DEPRECATION WARNING: Breakers is not implemented for service: TokenValidation

  '


---
test_webhooks/utilities_registers_events_and_blocks:
- 'DEPRECATION WARNING: /Users/holdenhinkle/Documents/Oddball/va_website/vets-api/spec/lib/webhooks/utilities_spec.rb:35:
  warning: already initialized constant Testing::EVENTS

  '
- 'DEPRECATION WARNING: /Users/holdenhinkle/Documents/Oddball/va_website/vets-api/spec/models/webhooks/utilities_spec.rb:38:
  warning: previous definition of EVENTS was here

  '

---
test_form526_rake_tasks_rake_form526:submissions_runs_without_errors_bdd_stats_mode:
- 'DEPRECATION WARNING: /Users/holdenhinkle/Documents/Oddball/va_website/vets-api/rakelib/form526.rake:42:
  warning: already initialized constant ROW

  '
- 'DEPRECATION WARNING: /Users/holdenhinkle/Documents/Oddball/va_website/vets-api/rakelib/form526.rake:42:
  warning: previous definition of ROW was here

  '
- 'DEPRECATION WARNING: /Users/holdenhinkle/Documents/Oddball/va_website/vets-api/rakelib/form526.rake:63:
  warning: already initialized constant OPTIONS_STRUCT

  '
- 'DEPRECATION WARNING: /Users/holdenhinkle/Documents/Oddball/va_website/vets-api/rakelib/form526.rake:63:
  warning: previous definition of OPTIONS_STRUCT was here

  '
test_form526_rake_tasks_rake_form526:submissions_runs_without_errors_two_dates:
- 'DEPRECATION WARNING: /Users/holdenhinkle/Documents/Oddball/va_website/vets-api/rakelib/form526.rake:42:
  warning: already initialized constant ROW

  '
- 'DEPRECATION WARNING: /Users/holdenhinkle/Documents/Oddball/va_website/vets-api/rakelib/form526.rake:42:
  warning: previous definition of ROW was here

  '
- 'DEPRECATION WARNING: /Users/holdenhinkle/Documents/Oddball/va_website/vets-api/rakelib/form526.rake:63:
  warning: already initialized constant OPTIONS_STRUCT

  '
- 'DEPRECATION WARNING: /Users/holdenhinkle/Documents/Oddball/va_website/vets-api/rakelib/form526.rake:63:
  warning: previous definition of OPTIONS_STRUCT was here

  '
test_form526_rake_tasks_rake_form526:submissions_runs_without_errors_just_a_start_date:
- 'DEPRECATION WARNING: /Users/holdenhinkle/Documents/Oddball/va_website/vets-api/rakelib/form526.rake:42:
  warning: already initialized constant ROW

  '
- 'DEPRECATION WARNING: /Users/holdenhinkle/Documents/Oddball/va_website/vets-api/rakelib/form526.rake:42:
  warning: previous definition of ROW was here

  '
- 'DEPRECATION WARNING: /Users/holdenhinkle/Documents/Oddball/va_website/vets-api/rakelib/form526.rake:63:
  warning: already initialized constant OPTIONS_STRUCT

  '
- 'DEPRECATION WARNING: /Users/holdenhinkle/Documents/Oddball/va_website/vets-api/rakelib/form526.rake:63:
  warning: previous definition of OPTIONS_STRUCT was here

  '
test_form526_rake_tasks_rake_form526:submissions_runs_without_errors_just_an_end_date:
- 'DEPRECATION WARNING: /Users/holdenhinkle/Documents/Oddball/va_website/vets-api/rakelib/form526.rake:42:
  warning: already initialized constant ROW

  '
- 'DEPRECATION WARNING: /Users/holdenhinkle/Documents/Oddball/va_website/vets-api/rakelib/form526.rake:42:
  warning: previous definition of ROW was here

  '
- 'DEPRECATION WARNING: /Users/holdenhinkle/Documents/Oddball/va_website/vets-api/rakelib/form526.rake:63:
  warning: already initialized constant OPTIONS_STRUCT

  '
- 'DEPRECATION WARNING: /Users/holdenhinkle/Documents/Oddball/va_website/vets-api/rakelib/form526.rake:63:
  warning: previous definition of OPTIONS_STRUCT was here

  '
```
