### ISSUE TITLE
My HealtheVet on VA.gov: Landing Page: Create QA tests in TestRail

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#55785]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
We were previously unable to write tests in TestRail due to authority issues.   Now that they have been resolved, we need to have tests so they can be run when updates are made.
---
## Tasks
**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
**Please note that we do not currently have TestRail plans written due to challenges with replicating the user experience in Staging and getting authority to the project in order to create tests.**
- [ ] [Regression test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-regression-test-planRegressionTestPlan)
- [ ] [Test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-test-planTestPlan)
- [ ] [Coverage for References](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [ ] [Summary(Defects) reports](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)

## Acceptance Criteria
- [ ] All four tests lists above have been created in TestRail and run
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by batemapf** [comment]
moving to `Blocked` b/c of `challenges with replicating the user experience in Staging and getting authority to the project in order to create tests.`
