### ISSUE TITLE
Supplemental Claims | Validate if AMA needs to be revisited post-launch

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#55781]
## Value Statement
**_As a_**  designer
**_I want to_** review post-launch data determine the percentage of users that actually see the AMA
**_So that_** we can validate and focus our efforts on features that make the most impact

---

## Background
Opt-in was removed as a part of the requirement for the new decision review page. By starting a Supplemental Claim, the Veteran will automatically opt-in to the new decisions review. The screen currently exists for information purposes only.

If we want to follow how the form is exactly set up, then it would exist in the introduction of the form since it does not require Veteran action or acknowledgement.

---

## Tasks
- [x] Determine the percentage of people who see this page
- [x] Determine the percentage of people who experience friction with this page
- [x] Decide if there's a better location for this page
