### ISSUE TITLE
Draft an internal document for other Platform teams on "how to work with us"

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#55795]
## Issue Description
With a recent team retrospective discussion, we would like to create some guidelines for other Platform teams on "how to work with us (Platform Content team).

## User Story
As a Platform Content team,
I want to be able to set clear exceptions for other Platform team members on how to work with us for larger projects,
So that we are able to mitigate as much ambiguity in the process,
So that we are able to better prepare for the reviewing and deployment load for 1 single day,
So that we are able to better prepare for reviewing and deployment duties across team members,
So that the other Platform team understands the launch-blocking issues.

This process can be two-fold:
1. Create initial to draft to review as a team
2. Polish the document to be "external" facing to other Platform teams

## Other ideas:
- Setting a maximum number of pages to be reviewed for deployment per day.
- See retro board for other ideas we had!
[Sprint 23 retrospective.png](https://images.zenhubusercontent.com/62aa32e3df1aa14040474a33/27761780-425c-48c5-a346-2172fea626f5).
- Append the new step-by-step instructions for moving Confluence pages from Drafts to the IA

---
## Tasks
- [x] Review the retro board feedback

- [x] Create an initial draft of document

## Acceptance Criteria
- [x] A draft of the document will exist with bullet points of ideas we documented during our team's retro.

## Acceptance Criteria

- Have a kickoff meeting between 2 teams (share style guide, launch-blocking issues, scroll viewport, etc.)
- Assign a team point of contact we work with
- Set a limit of # of pages we review in 1 day
- Only communicate via thread we start in #platform-content

## Artifact
Link to document: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2613772343/Working+with+Platform+Content+team+on+bigger+projects
