### ISSUE TITLE
Implement Deployment ID creation and write ID to values files

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#55802]
## Issue Description
Based on the findings in https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/54978 we need to implement our decided-upon strategy for creating deployments and passing the ID to ArgoCD for use in updating the status after a Preview Environment is launched.

---
## Tasks
- [ ] Create a new deployment in GitHub actions whenever a preview environment is launched. This will need to be included in vets-website, content-build, and vets-api.
- [ ] Pass the ID of the new deployment to the devops main workflow that creates the values file for the Preview environment
- [ ] Write the Deployment ID to the values file
- [ ] Ensure the vets-website workflow sends the correct deployment ID dependent on whether the Preview Environment was launched from content-build or vets-website

## Acceptance Criteria
- [ ] Every values file generated for preview environments contains a deployment ID that can be used to update the deployment status after the preview environment is launched.
---
