### ISSUE TITLE
Onboarding - G. Antoniades

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#55827]
## Issue Description
Gia Antoniades (BE Engineer) has joined the team and will need to onboard to the platform and project.

---
## Tasks
- [ ] Complete corporate onboarding tasks
- [ ] Complete VA Platform onboarding tasks
- [ ] Complete Preview Environment Project onboarding tasks

## Acceptance Criteria
- [ ] Onboarding tasks have been completed

**Comment by pjhill** [comment]
Welcome to the team!
