### ISSUE TITLE
Content support for unified check-in work

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#55836]
## Issue Description

The modernized check-in experience team opened an intake request ticket for content support as they are trying to create a single, consistent check in app experience, instead of two applications, that supports, and highlights, medical appointment tasks that need to be completed (no matter which text message link is used to navigate to the check in application) and provides a larger view of all upcoming and past appointments (similar to the appointments tool in VAOS).

For the content team:

- Review content that has changed in our [draft wireframes (Sketch)](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec) and provide feedback. Content that needs review is identified with a comment on an artboard that begins with, "For Sitewide content review." Viewing comments works best using the Sketch web app. If you need to zoom into an individual wireframe/artboard, you can double click the artboard name that will direct you to that individual wireframe/artboard. For example, https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/bgwvQKZ. Please leave a reply to the comments. Or, you can add a new comment on an artboard and tag Ben Brasso. 

More background and artifacts in ticket #55686

Note that the team is using VAOS content that has already been worked on with Danielle so this doesn't need to be reviewed. The content we're reviewing should only be new. We should confirm with the team that is what's being called out in the artboard mentioned above.

## Tasks
- [ ] Edit content (Aliyah)
- [ ] Review (Laura)
- [ ] Copyedit (Megan)
- [ ] Provide final content to product team in intake request (Aliyah/Megan)

## Acceptance Criteria
- [ ] Product team has final content

**Comment by aliyahblackmore** [comment]
**Update here:** 

As mentioned above, I just pinged Ben in the intake request to confirm that the content marked for us to review is only new content.

**Comment by aliyahblackmore** [comment]
**Update here:**

Chatted with Danielle about a few of our questions and the "verify" screen. 
Will continue this tomorrow!

**Comment by aliyahblackmore** [comment]
**Update here:** 

Suggestions are in the sketch screens. Laura is going to pass our higher level comments to their team by today.

**Comment by laurwill** [comment]
@RLHecht Noting we've passed them all our content suggestions in the intake ticket. But we'll likely work on a few more screens after Ben and team review our suggestions. Should we close this initial content ticket and continue our conversation with them in the intake?

**Comment by RLHecht** [comment]
Thanks, Laura. Yeah, let's do that so we can close this one.
