### ISSUE TITLE
[Design] Create New Design that Excludes the QR Code Instructions 

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#55833]
## User Story
As the VA, we have decided to remove the QR code instructions from the Patient Check-in posters so that Veterans do not become confused or risk being asked for their credit card information.

## Tasks
- [ ] Create new design for the poster that excludes the QR code instructions
- [ ] Review new design with content team

## AC
- [ ] A new poster design that excludes the QR code instructions has been approved by UX & the content team representatives

**Comment by loripusey** [comment]
@benbrasso-agile6 let's show our new design to Stephen after it's complete and find out if it's ok to wait until the research study asks Veterans or does he want this to go out ASAP
