### ISSUE TITLE
[FE] My VA: Review & fix disabled E2E tests

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#55868]
## Background
Periodically we need to review E2E tests in `vets-website` that are disabled due to flakiness. The current list of disabled tests can be found here [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/currently-disallowed-cypress-test-specs-on-va-gov). We need to review them for anything from My VA and fix them.

_This is a recurring task that should be completed roughly once a month._

## Tasks
- [ ] Review the list of disabled e2e tests
- [ ] Fix any pertaining to My VA

## Acceptance Criteria
- [ ] all My VA e2e tests currently disabled due to flakiness are fixed

## Validation
- _Who can validate this ticket?_  any dev
- _How can this work be validated?_ check tests and ensure they are properly reenabled

**Comment by allisonlu** [comment]
No My VA tests are currently in the list! (as of 5/10/23)
