### ISSUE TITLE
[eFSR] Updates to resolution options to repeat amount of debt

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#55877]
## Issue Description
Update text and design to repeat the amount of debt for the [payment plan and compromise offers.](https://preview.uxpin.com/f43733391f52c409c4d3152e9a4b101a392e29df#/pages/161460843) Here are the before and after, with the after being the proposed solution.

| | Resolution Options | Waiver | Monthly Payments | Compromise |
|--------|--------|--------|--------|--------|
| Beneifit Before | ![C5P1: benefit debt resolution options](https://user-images.githubusercontent.com/1631062/229943292-ef02a825-309f-4a7a-b5c4-9d6052b7aeb2.png) | ![C5P1: benefit debt - forgiveness](https://user-images.githubusercontent.com/1631062/229943294-17f6655b-4ccc-4c41-8fd1-10a0a2730333.png) | ![C5P1: benefit debt - extended monthly payments](https://user-images.githubusercontent.com/1631062/229943297-5140b5f7-4bc3-4df2-9964-a5ae7c2da3e1.png) | ![C5P1: benefit debt - compromise](https://user-images.githubusercontent.com/1631062/229943299-896d2396-7e22-4a9c-8524-ba7711e2f544.png) | 
| Benefit After | ![C5P1: benefit debt - resolution options](https://user-images.githubusercontent.com/1631062/230681649-8d1c1f01-0752-4a8e-a9da-95f54bbaba01.png) | ![C5P1: benefit debt - forgiveness](https://user-images.githubusercontent.com/1631062/230681647-10057139-0508-4574-bdf7-e715c8a6f95a.png) | ![C5P1: benefit debt - extended monthly payments](https://user-images.githubusercontent.com/1631062/230681644-922e2b89-b031-4ccb-a4e3-8496b5e5db58.png) | ![C5P1: benefit debt - compromise](https://user-images.githubusercontent.com/1631062/230681642-ca1afe3f-0295-4459-8080-90b8eaf3345b.png) |

| | Resolution Options | Waiver | Compromise |
|--------|--------|--------|--------|
| Copay Before | ![C5P1: copay debt - resolution options](https://user-images.githubusercontent.com/1631062/230682171-53a7d7e1-9e54-4087-ba02-22282ae9a6a1.png) | ![C5P1: copay debt - waiver](https://user-images.githubusercontent.com/1631062/230682170-e879f409-977d-4a82-8420-b0e8e86a9062.png) | ![C5P1: copay debt - compromise](https://user-images.githubusercontent.com/1631062/230682167-1c46a0d2-6ac0-4340-9931-2dad9efc2797.png) | 
| Copay After | ![C5P1: copay debt - resolution options](https://user-images.githubusercontent.com/1631062/230681879-4ef90619-cb6c-4f2f-8c28-73bd276c3fb3.png) | ![C5P1: copay debt - waiver](https://user-images.githubusercontent.com/1631062/230681880-355caceb-5c9a-4f0a-b910-7094845d91b8.png) | ![C5P1: copay debt - compromise](https://user-images.githubusercontent.com/1631062/230681872-28ee444b-fa4c-4133-a668-d5425e60d4cc.png) |
---

## Tasks
- [x] _Update designs in Sketch for each resolution option_
- [x] _Archive old designs in Sketch for each resolution option_
- [x] _Update UXPin prototype for each resolution option_

## Acceptance Criteria
- [x] _Attach updated designs for each resolution option_
- [x] _Attach links to updated designs in UXPin_

**Comment by HeatherRienks** [comment]
@mgleo to discuss with Content Team during office hours.

**Comment by josephrlee** [comment]
@Dr-Pongo, this is ready to be worked on now pending Jill's [comments on this slack thread](https://dsva.slack.com/archives/CPE4AJ6Q0/p1680888363740659) for the Copay Waiver Option.

**Comment by HeatherRienks** [comment]
@Dr-Pongo - can you please create a FE ticket and add the link in this ticket?  Once you do that, I will close this ticket. Thank you!

cc: @josephrlee 

A

**Comment by Dr-Pongo** [comment]
FE Ticket has been created! [#56540](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/56540) Leaving this in the backlog and it's probably going to take a lower priority compared to other functionality changes we need to address prior to launch

**Comment by HeatherRienks** [comment]
Great, @Dr-Pongo - thank you! Closing this ticket!
