### ISSUE TITLE
[BE] vets-api: Update configs to store template info

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#55879]
## User Story
As a Veteran, I want to receive a text message with status when I file a travel claim during online check-in

## Tasks
- [ ] [BE] Update configs to store the template uuids from VANotify 

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
