### ISSUE TITLE
[BE] Update Travel Claims Controller to call background worker to submit claims

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#55882]
## User Story
As a Veteran, I want to receive a text message with status when I file a travel claim during online check-in

## Tasks
- [ ] [BE] Update travel claims to call the background worker to submit claim and notify user
- [ ] [BE] Return 202 Accepted
- [ ] Update rspecs

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by loripusey** [comment]
@randomsync who needs to validate this?

**Comment by randomsync** [comment]
I was keeping it in 'validate' column to make sure we don't see any impact in production. Done and closing it.
