### ISSUE TITLE
Tech Discovery - React component deprecation

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#55889]
## Issue Description
The Design System Team has been deprecating older React-based versions of our components in favor of web-components (which have React bindings).

Slack thread - https://dsva.slack.com/archives/C04KW0B46N5/p1680097266303619

In scope for this ticket:
Here is the list of fully deprecated components:
- Accept Terms
- Banner
- Collapsible panel
- Date
- Help Menu
- IconHelp
- Month Year
- Number input
- Privacy agreement
- Process list
- Promo banner
- Radio button
- Search menu
- Text area

List of components being deprecated week of April 3rd

- System down view
- Text input
- Alert Box
- Checkbox group
- Expanding group
- Additional Info
- Breadcrumbs
- Dropdown panel
- Loading indicator
- Modal
- OMB Info
- Pagination
- Progress button
- ProgressButton / button pair React component
- Table
- Telephone
- Select
- Fileinput

---
## Tasks
- [ ] Scan the vets-website repo for our usage of these components
- [ ] Learn about how the VA uses web components, and about web components in general

## Acceptance Criteria
- [ ] List of react components in scope that are being used in 526ez
- [ ] Tickets created for next steps

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
Replaced this with an epic

**Comment by christinec-fftc** [comment]
[Discovery notes](https://docs.google.com/document/d/1fZZck_xxrqep4FJ1mZaOOlhWOzNKo-Ni6XGYD3fbMEo/edit?usp=sharing)

**Comment by christinec-fftc** [comment]
**Summary of findings**

1. Confirmed that from the phase 1 list of already deprecated react components, our pages were only using the radio buttons component and that was covered by these tickets
[Tech discovery - are REACT based radio buttons being used by 526ez forms #53413](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/53413)
[Move to deprecation phase 3 - RadioButtons React component #1310](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1310)

2. From phase 2 list, there is one relevant component in use by 526. Created this story
[Migrate OMBInfo component on 526 Introduction Page](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/56297)

3. Also checked use of [ui:widgets](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-using-form-widgets-and-fields) which are form widgets utilizing RJSF (React JSON Schema Form) which in turn could potentially use deprecated react components. Did not find any deprecated components there.

**Comment by christinec-fftc** [comment]
Created 2 more issues for the 686 work
[Migrate OMBInfo component on 686 Introduction Page #56629](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/56629)
[Migrate Telephone component for 686 #56630](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/56630)
