### ISSUE TITLE
[BE] Add configs with api keys for VANotify for staging/prod vets-api environments

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#55880]
## User Story
As a Veteran, I want to receive a text message with status when I file a travel claim during online check-in

## Tasks
- [ ] [BE] Add configs in vets-api
- [ ] [BE] Add configs in AWS store and devops repo

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
