### ISSUE TITLE
[BE] Create sidekiq worker to call BTSSS in the background

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#55883]
## User Story
As a Veteran, I want to receive a text message with status when I file a travel claim during online check-in

## Tasks
- [x] [BE] Create a sidekiq worker to call VEIS and BTSSS apis to submit the travel claim
- [x] Create rspec

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
