### ISSUE TITLE
[Launch] Find VA Forms Search

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#5589]
## Background
Determine and complete activities necessary to launch Find VA Forms - Search
## Tasks
- [x] publish the Drupal page to /find-forms without redirects
- [x] add a record into our robots.txt to prevent search crawlers from indexing the page
- [x] Best Bets/Recommendations are updated - #7695
- [x] Update footer link
- [x] Implement redirect from /vaforms to /find-forms - [List of forms search URLs that need redirecting: ticket 5163 ]( https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/5163)
- [ ] Confirm analytics continue to flow after launch activities

## Acceptance Criteria
- Appropriate checklists are completed 
- Launch receives any necessary approvals
- Find VA Forms - Search is launched

**Comment by MickinSahni** [comment]
Next steps: 
* Create tickets in order to launch this search

**Comment by MickinSahni** [comment]
Convert this to an issue within #1632 - @MickinSahni

**Comment by MickinSahni** [comment]
- [ ] [Accessibility / 508 review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-request-prelaunch-review.md)
- [ ] [ATO review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/security/security-review-process.md)
- [ ] [Content review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/content/content-review-process.md#how-to-request-content-review)
- [ ] [Design QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/design/working-with-platform-design-team.md) / review(?)
- [ ] Analytics / Product Health Report review
*   Reviewing analytics that will be used to just the product health / success, and making recommendations as appropriate.
- [ ] Release plan review
*   Review release phases and criteria for moving between them. This should include rollout schedule, success/rollback criteria, any pre- and post-launch user testing and monitoring, external documentation and comms.
- [ ] [IA review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/working-with-ia.md)
*   Should include review of URLs, navigation hierarchy, crosslinks/redirects, SEO
- [ ] [Security review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/security/security-review-process.md)
*   Review looking for potential technical security issues / vulnerabilities, focusing particularly on frontend-backend interactions, anything involving certificates or cookies, and any new interactions with dependent backends.
- [ ] Privacy review
*   Review looking for potential user data issues, including affirming best practices around handling PII.
- [ ] Production readiness / infrastructure review
*   Review of technical architecture, looking for potential scaling concerns, dependency analysis, SLO assessment
- [ ] Documentation for quickly addressing when things go wrong
- [ ]   Contacts for oncall support: who do we contact if the application is failing? What kinds of failure modes are likely?
    - [ ]   Documentation and points of contact for any new backend dependencies
    - [ ]   Links to important dashboards for investigating relevant issues
- [ ] [Quality Assurance](../../quality-assurance/README.md)
    - [ ]   [Test plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/testrail/README.md)
    - [ ]   [E2E tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/e2e-testing/README.md), running in CI/CD, passing on all browsers
    - [ ]   [Load testing](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/quality-assurance/load-testing/README.md)
    - [ ]   Manual test cases created where necessary
    - [ ]   Code coverage requirements
    - [ ]   No high-severity bugs present
- [ ] Monitoring requirements
    - [ ]   Contact (mailing list? Slack channel?) for errors to be reported to
    - [ ]   Errors getting sent directly to team
- [ ] Contact center(s) are prepared for this launch, with updated scripts/documentation as needed
- [ ] VA web comms team is aware of this launch and has accurate messaging
- [ ] Product Outline w/critical criteria up-to-date
- [ ] Tested in prod with VA back-of-house people and systems
- [ ] Entrance pages (i.e. supporting static content) in place
- [ ] Downtime UX and error messaging documentation complete
- [ ] "Learn and Improve" plan written: KPI measurements, analytics reporting, next phase of features to build

**Comment by ncksllvn** [comment]
Since the redirects that are required for Find Forms are complicated by the web-scraping situation, I think we should consider a soft launch. That is, publish the Drupal page to `/find-forms` without redirects. Then, we can add a record into our `robots.txt` to prevent search crawlers from indexing the page. That way, we can confirm functionality on the new page, while focusing on the redirect implementation.

**Comment by ncksllvn** [comment]
Next steps - Now that we're treating queries as a space-separated list of terms, I think we're good to begin auditing the quality of search results of the [modernized search](http://preview-prod.vfs.va.gov/preview?nodeId=2352) (staging version [here](https://staging.va.gov/find-va-forms-beta/)) against the [legacy search](https://www.va.gov/vaforms/). 

This will decide whether we're blocked on launching - if the legacy search is still considered better, than we're blocked until the Lighthouse API has official access to the VA Forms DB, in order to access the `keywords` table.

**Comment by AkucherGCIO** [comment]
@ncksllvn - I will set up some time for us to discuss what is needed for this to soft launch.

**Comment by ncksllvn** [comment]
Soft launch ticket, https://github.com/department-of-veterans-affairs/va.gov-team/issues/6317

**Comment by jenniferlee-dsva** [comment]
Added link to full list of forms search URLs that need redirecting - https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/5163

**Comment by stephorkandatx** [comment]
@ncksllvn I'm pulling this into the current sprint. We plan to do the redirects this Thursday

**Comment by ncksllvn** [comment]
PR to launch redirects - https://github.com/department-of-veterans-affairs/devops/pull/6819
PR to update footer - https://github.com/department-of-veterans-affairs/vets-website/pull/13250

**Comment by jenniferlee-dsva** [comment]
@ncksllvn - could you confirm that the robots.txt is removed? 

I'll check analytics flow later this week to validate that checkbox item.

**Comment by MickinSahni** [comment]
No longer blocked (@MickinSahni to figure out how to remove the ZH blocker).

Confirmed removal of (/vaforms) from robots.txt
