### ISSUE TITLE
[FE] [TECH Debt] - Create unit test coverage report

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#55898]
## Description
We have < 75% coverage of unit tests reported. See this ticket: https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/54475

### Before
/check-in/day-of
![coverage--day-of](https://user-images.githubusercontent.com/2982977/231509360-5ca81c94-0b95-4817-83a3-e25a768e8325.png)

/check-in/pre-check-in
![coverage--pre-check-in](https://user-images.githubusercontent.com/2982977/231509489-6be8c738-1abe-48b3-bdd9-437966347516.png)

/check-in
![coverage--entire-app](https://user-images.githubusercontent.com/2982977/231509530-bcc4804b-1e40-4e66-8cb1-47d0f2492b8b.png)

## Tasks
[ ] - Run a report on our unit test coverage
[ ] - Analyze report and make plan to increase coverage

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by wullaski** [comment]
Here are the coverage reports as static HTML. Generated using: 

`yarn test:unit --app-folder check-in --coverage --coverage-html`
`yarn test:unit --app-folder check-in/pre-check-in --coverage --coverage-html`
`yarn test:unit --app-folder check-in/day-of --coverage --coverage-html`

[coverage-entire-app.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/11213188/coverage-entire-app.zip)
[coverage-pre-check-in.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/11213189/coverage-pre-check-in.zip)
[coverage-day-of.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/11213190/coverage-day-of.zip)

**Comment by wullaski** [comment]
@loripusey I've identified a couple of areas in the code that are problematic from a unit test coverage standpoint but I don't know if it would be worth the time and effort to refactor just to satisfy the scan. While the code is not covered by a unit test the results of the code are covered by other unit tests and e2e testing.
