### ISSUE TITLE
Remove React-based components being used by 526EZ form

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#55896]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/README.md)

## High Level User Story/ies
The Design System Team has been deprecating older React-based versions of our components in favor of web-components (which have React bindings).
This epic covers the the search and replace of following components.

1. Text-input
2. Textarea
3. Radio button
4. Checkbox
5. Select
6. Memorable date
7. Button

Out of scope:
8. Button pair
9. Modal
10. Number input
11. Additional info
12. Progress bar - Segmented
13. File input
14. Privacy agreement
15. Alert
---

## Need to know
- The current MVP plan is for full migration of these components by May 27' 2023
- Slack thread with more details - https://dsva.slack.com/archives/C0NGDDXME/p1679938793334079?thread_ts=1679922006.245719&cid=C0NGDDXME

## Hypothesis or Bet
**If** _we make this change_ **then** _we expect this to happen_.

## OKR
_Which Objective / Key Result does this epic push forward?_

## Definition of done
- [ ] Search for the in-scope react based components
- [ ] Replace with web based version of the component based on design team's recommendations
 

## Acceptance Criteria
- [ ] In scope react based components are no longer being used by all forms that part of 526ez submission
- [ ] Existing functionality does not change

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by RakshindaAslam** [comment]
cc @christinec-fftc @navaeddie @ahay-agile6

**Comment by navaeddie** [comment]
Couple of helpful links:
[How to Migrate documentation](https://design.va.gov/about/developers/using-web-components#how-to-migrate-to-web-components)
[Storybook](https://design.va.gov/storybook/?path=/story/about-introduction--page)

**Comment by pacerwow** [comment]
Can this be closed? @aurora-a-k-a-lightning @christinec-fftc

**Comment by christinec-fftc** [comment]
Yes, I think so
