### ISSUE TITLE
[BE] Call VANotify in the background with the worker

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#55908]
## User Story
As a Veteran, I want to receive a text message with status when I file a travel claim during online check-in

## Tasks
- [ ] [BE] The worker calls VANotify to send a text message to the veteran with status

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
