### ISSUE TITLE
Wireframe User Flows for Streamlined Waiver

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#55905]
## Issue Description
Build out user flows with wireframes based on [Streamlined Waiver Flow Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1678973946956/6f3bb65fe1ccc2b9d3bc38cd24cd09e74d18d778?sender=ua78f969c4cddcbfe56b27885).

---
## Tasks
- [x] _Meeting on Wed March 29th and April 5th_
- [x] _Create user flow documents with various scenarios_

UX Research (learning and understanding phase)
- [ ] _Explore and document future research opportunities_
- [ ] _Define said research opportunities_
- [ ] _Define what we want to learn, and what we already know_

## Acceptance Criteria
- [x] _Weekly meetings occur_
- [x] _User flow with wireframes created_

UX Research (learning and understanding phase)
- [x] _Create a visual for UX research cycles for Streamlined Waiver initiative with a timeline_
- [ ] _Define said research opportunities_

**Comment by charlottecesana** [comment]
I added the UX Research tasks for this initiative.

**Comment by mgleo** [comment]
@HeatherRienks Moved to Validate

**Comment by HeatherRienks** [comment]
Thank you so much @mgleo for adding these tickets in! :)
