### ISSUE TITLE
[BE] Migrate Check-in DataDog Dashboard to monitor EKS vets-api in Staging/Prod

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#55916]
## Description
Platform team starting to rollout vets-api EKS migration to production starting **April 4th** in phases.  Currently, CIE team uses [dashboard](https://vagov.ddog-gov.com/dashboard/zps-5fk-azw/check-in-vets-api?from_ts=1679943437297&to_ts=1680029837297&live=true) to monitor CIE performance in production.  Environment config changes in datadog when vets-api EKS migration completes. CIE team will be blocked on viewing/receiving end of day summary in Production channel when the EKS migration completes. 

## Tasks
- [ ] [BE] **Update CIE Dashboard for vets-api in EKS**
- [ ] [BE] **Update End of Summary Script to use vets-api in EKS**

## Acceptance Criteria
- [ ] Tested on staging

**Comment by kanchanasuriya** [comment]
Created [dashboard](https://vagov.ddog-gov.com/dashboard/x8y-zjx-tyt/check-in-eks-vets-api?tpl_var_environment%5B0%5D=eks-staging&from_ts=1680821513138&to_ts=1680907913138&live=true) for vets-api in EKS environment and verified in `eks-staging`.  Currently, dashboard shows data only for `eks-staging` as `vets-api/check-in` endpoints in prod yet to be rolled out for EKS

**Comment by kanchanasuriya** [comment]
Below are the changes for end of day summary script.

Modify metric & environment tag in,

- [Line-37](https://github.com/department-of-veterans-affairs/checkin-devops/blob/master/scripts/summary.py#L37) as `sum:vets_api.statsd.api.check_in.v2.sessions.show.count.success{env:eks-staging}.as_count()`
-  [Line-39](https://github.com/department-of-veterans-affairs/checkin-devops/blob/master/scripts/summary.py#L39) as `sum:vets_api.statsd.api.check_in.v2.checkins.create.count.success{env:eks-staging}.as_count()`
- [Line-42](https://github.com/department-of-veterans-affairs/checkin-devops/blob/master/scripts/summary.py#L42) as `sum:vets_api.statsd.api.pre_check_in.v2.sessions.show.count.success{env:eks-staging}.as_count()`
- [Line-44](https://github.com/department-of-veterans-affairs/checkin-devops/blob/master/scripts/summary.py#L44) as `sum:vets_api.statsd.api.check_in.v2.pre_checkins.create.count.success{env:eks-staging}.as_count()`

**Comment by kanchanasuriya** [comment]
Created a [ticket](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/56659) to update the script when vets-api EKS roll out completes in production
