### ISSUE TITLE
[View Payments] For 508 defect, tables are verbose and semantically mismatched on mobile, determine if this issue is local or tied to the design system

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#55927]
## Value Statement
**_As a_**
**_I want to_**
**_So that_** 

---
## Background Context
This relates to a level 2 accessibility defect. We want to check out whether the semantics of the design systems table is causing the issue. If it is, we can consider using a different web component or consider more creative solutions. 

## Acceptance Criteria
- [ ] Verify to what extent this is a design system issue
- [ ] Make recommendation for how to proceed in fixing original defect

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jaredcunha** [comment]
The more I think about this, the more it seems the issue with Apple.
Semi-related: https://bugs.webkit.org/show_bug.cgi?id=257458

Also this ticket:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/58146

I think this ticket is out of hands @jacobworrell
