### ISSUE TITLE
Accessibility Orientation - April 2023

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#55936]
## Issue Description
Hosted the Accessibility Orientation Session for VA.gov Platform on 4/14/2023

---
## Tasks
- [x] Host the session and answer any questions that come up.

## Acceptance Criteria
- [x] We have provided an Accessibility Orientation session for VA.gov Platform for April 2023.

---
### How to format this ticket

- [x] Add estimate of 1
- [x] Add assignee
- [x] Add sprint
- [x] Ensure ticket is assigned to quarterly Platform Orientation epic
