### ISSUE TITLE
[Design] 10-10CG Facilities Design Intent Feedback Changes

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#55942]
## Issue Description
Update Sketch file to reflect team decisions of how to incorporate Design Intent feedback received. 
Tickets #55490, #55545 and #55327

---
## Tasks
- [x] Make updates to confirmation screen(s)/flow
- [x] Updates to remove pagination  
- [x] Complete annotations needed
- [x] Review with content during health office hours on Thursdays at 11aET/8aPT
- [x] Review with 1010 team

## Acceptance Criteria
- [x] Design files updated to reflect feedback and direction for Midpoint Review/Staging
---

**Comment by jessicastump** [comment]
Revised search results page (removed pagination)

- [Mobile](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/L40r8GW)
- [Desktop](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/AZxJmLz)

Revised confirmation page - different locations

- [Mobile](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/GoOPMGE)
- [Desktop](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/y98PyLK)

If facility chosen has caregiver support staff located there possible option below or is a confirmation screen needed if they are the same?

- [Mobile](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/K0vrOZe)
- [Desktop](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/mP1qqEP)

**Comment by jessicastump** [comment]
Content updates for confirmation screen after content health office hours:
- [Mobile Sketch](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/GoOPMGE)
- [Desktop Sketch](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/y98PyLK)

--

Veteran's facility has/is coordinator facility option
- [Mobile](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/K0vrOZe)

Circling back on idea to have different confirmation screens if the Veteran/caregiver selects a facility where there is already a coordinator located... is this needed? Or should this extra step be skipped (confirmation screen) if a coordinator facility is selected as the Veteran's facility?

**Comment by hdjustice** [comment]
During a Slack discussion regarding the need for a confirmation page if the Selected Facility and associated Caregiver Facility are the same, it was mentioned that the confirmation page would not be useful if it lists one facility only to say 'this is where we will send the application for processing' since the whole reason for the confirmation page is to inform applicants of the associated facility.  
We will not show the Confirmation page when the facilities (selected and Caregiver) are the same, and consider adding a research prompt to ask about expected behavior once the selection is made.

**Comment by jessicastump** [comment]
Will add this note to the 3 collab cycle feedback tickets (Tickets #55490, #55545 and #55327)

Design intent feedback has been incorporated into the following Sketch links:
**Confirmation screen updates:** removed alert, changed link styling for finding a new facility and worked with content on updates
- [Mobile confirmation screen Sketch link](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/GoOPMGE)
- [Desktop confirmation screen Sketch link](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/y98PyLK)

**Accessibility feedback:** Removed pagination and added link to follow Navigate a long list pattern, team decided to not show closed facilities so a disabled radio tile state is not needed, added annotations for focus order
- [Desktop search results Sketch link](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/AZxJmLz)

**Content feedback:** Updates to confirmation screen language above
