### ISSUE TITLE
QA Orientation - May 2023

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#55940]
## Issue Description
Hosted the QA Orientation Session for VA.gov Platform on 5/18/2023

---
## Tasks
- [ ] Host the session and answer any questions that come up.

## Acceptance Criteria
- [ ] We have provided a QA Orientation session for VA.gov Platform for May 2023.

---
### How to format this ticket

- [x] Add estimate of 1
- [x] Add assignee
- [x] Add sprint
- [x] Ensure ticket is assigned to quarterly Platform Orientation epic
