### ISSUE TITLE
Tech Discovery - endpoint /getpdf

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#55955]
## Issue Description
Form 526 currently calls EVSS /getpdf endpoint. This call needs to be migrated to Lighthouse as part of overall eVSS migration to Lighthouse.

endpoint /getpdf is planned to be available in Lighthouse in production in May 2023. This issue is to discover 
- what data field(s) are being sent and received from the eVSS endpoint by the 526 form?
- what is the endpoint in existence in LH that replaces this service?
- what data field(s) are being sent and received from the new LH endpoint?
- can form 526 switch to this LH endpoint without changes for this service?

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] what data field(s) are being sent and received from the eVSS endpoint by the 526 form?
- [ ] what is the endpoint in existence in LH that replaces this service?
- [ ] what data field(s) are being sent and received from the new LD endpoint?
- [ ] can form 526 switch to this LH endpoint without changes for this service?
- [ ] a ticket created on 526 board to switch this end point to LH endpoint, with dependencies documented, if any

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
cc @navaeddie @colevoss @ahay-agile6 @sethdarragile6

**Comment by sethdarragile6** [comment]
One consumer of this is the [Form526BackupSubmissionProcess](https://github.com/department-of-veterans-affairs/vets-api/blob/c213d2ed6e0184fd6ac1d0732492a66555c5e98d/lib/sidekiq/form526_backup_submission_process/processor.rb#L329). It will likely need to be "switched on" along with a call out to new translation service so that the Lighthouse-formatted JSON is sent to it. That is assuming that the LH /getPdf endpoint will also be accepting the full JSON as a parameter (as the EVSS version seems to).
