### ISSUE TITLE
<Epic> CAIA Accessibility Documentation Epic

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#55956]
## Description

Currently, shared support accessibility documentation is scattered across multiple github folders including:
- [Previous a11y team’s shared support folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/shared-support/accessibility)
- [Previous vsa a11y folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/accessibility)
- [Sitewide content folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/sitewide-content)

Having a single repository or place to store our documentation will:
- reduce maintenance issues
- provide a single place for a11y resources and content for onboarding practitioners and a11y specialists

### Now
- [ ] @DanielleThierryUSDSVA to ask content/IA/accessibility OCTO leads group to ensure a documentation approach is consistent across the 3 disciplines on the shared team. 
- [x] [Create a list of all VA.gov accessibility resources #56000](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56000) This is the spreadsheet list of all a11y resources and locations on GitHub created by @sara-amanda 
  - [ ] Confirm if resources are up to date or out of date **(Currently In Progress)**
  - [ ] Archive or update outdated documentation

### Next
This depends on what Danielle learns through the content/IA/accessibility OCTO leads group.

## Success criteria
- [ ] An up to date repository of shared support accessibility documentation exists
- [ ] All outdated accessibility documentation is archived

## Related Tickets
#56000 
#57208 
```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/56000
```

**Comment by sara-amanda** [comment]
@artsymartha68 Following up from the VA A11y Sync Meeting 5/11/2023: 
**Here is the Epic that contains the tickets for:** 
- [Create a list of all VA.gov accessibility resources #56000](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56000)
- [a11y Onboarding Documentation #57208](https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/57208)

☑️ @joshkimux This ticket has been updated to reflect the work done so far in the ticket body "tasks" section, above.
