### ISSUE TITLE
EVSS Migration - Abstract eVSS submit endpoint

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#55953]
## Issue Description
Form 526 currently calls EVSS /submit endpoint for submitting claims via vets-api. This call needs to be migrated to Lighthouse as part of overall eVSS migration to Lighthouse. **This work is split across multiple tickets.**

### This ticket
Insert feature flag in couple of places to support EVSS to LH migration.

1. in app/models/saved_claim/disability_compensation.rb#to_submission_data after line 24
2. in app/workers/evss/disability_compensation_form/submit_form526.rb#perform after line 62

-----

Ticket #2 - are there any other eVSS services being consumed within 526 flow.
      What evss service calls from ancillary jobs when the 526 form is submitted need to be extracted? 
     Does the framework sufficient for this?

## Need to know
The schema is available

## Notes

---

## Tasks
- [ ] create the submit service provider to be created by the factory - evss
- [ ] Authentication 
- [ ] use eVSS provider in the form 526 submit workflow(path in notes in the description)
- [ ] create flipper feature toggle to switch from evss to LH
- [ ] fix failing unit tests by switching the feature toggle off

## Acceptance Criteria
- [ ] Abstract references to the submit endpoint calls to evss
- [ ] Maintain test coverage

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
cc @navaeddie @colevoss @ahay-agile6 @sethdarragile6

**Comment by navaeddie** [comment]
The method that fires at the submit endpoint: [EVSS::DisabilityCompensationForm::Service#submit_form526](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/evss/disability_compensation_form/service.rb#L57)

```
def submit_form526(form_content)
	with_monitoring_and_error_handling do
	  headers = { 'Content-Type' => 'application/json' }
	  options = { timeout: Settings.evss.disability_compensation_form.submit_timeout || 355 }
	  raw_response = perform(:post, 'submit', form_content, headers, options)
	  FormSubmitResponse.new(raw_response.status, raw_response)
	end
  end
```

To see what's sent via that method, see comment accompanying the `submit_form526` method,
`form_content [JSON] JSON serialized version of a {Form526Submission}`
See that [table in database](https://github.com/department-of-veterans-affairs/vets-api/blob/master/db/schema.rb#L567) to know what metadata included there,

Hints on what vets-api receives from EVSS:
EVSS::DisabilityCompensationForm::FormSubmitResponse, a few relevant attributes are identified as:
```
attribute :claim_id, Integer
attribute :inflight_document_id, Integer
attribute :end_product_claim_code, String
attribute :end_product_claim_name, String
```
