### ISSUE TITLE
Automate process to easily ingest MHV data and report on CSP counts (part 1)

### ISSUE THREAD

**Issue by elizabethmkoch** [department-of-veterans-affairs/va.gov-team#55961]
## Issue Description
The login.gov adoption team, stakeholders, and VA leadership need to review data and analyze CSP counts and CSP method changes to track login.gov adoption.

## User Story
As a Product Owner
I want to know the total user counts by CSP accessing the va.gov ecosystem as we progress through the migration
So that we can track adoption.

---
## Tasks
Pre-process script automation
- [ ] clean up (or re-write) script to pre-process MHV data exports
- [ ] ensure script has access to network drive: \\vacohsm01.dva.va.gov\VACO_Workgroups\Information & Technology\OCTO Digital Experience\ETL
- [ ] detect MHV exports and implement a hand-off to Domo Workbench workflow
- [ ] enable auto-detection of IAM data exports to initiate pre-process and load into Domo

## Acceptance Criteria
- [ ] Process automated on regular weekly cadence

**Comment by holytoastr** [comment]
Where specifically does the data come from and where does it need to go?

**Comment by lmorris3** [comment]
@sdickson-gt is this still relevant or is the work being handled through other tickets on the board?
