### ISSUE TITLE
[BE] Fix hca submission error

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#5596]
## Background

There is a bug in sentry with the file size being too big.

http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/67136/?query=is%3Aunresolved%20level%3Aerror
seems to be caused by attachments that are too large

## Tasks

- [ ] Investigate issue
- [ ] Determine next steps
- [ ] Fix issue, or create additional tickets if needed

## Acceptance criteria

- [ ] Issue is fixed OR additional next steps have been determined

**Comment by lihanli** [comment]
@bradl3yC @erikphansen 
### HCA submission endpoint behavior once my pr is merged

previous parameter `async_compatible` will be ignored
if an application has an email set it will be sent asynchronously with retries
if an application has no email set it will be sent synchronously
if an application has no email set and the `async_all` parameter is passed in with a truthy value then it will be sent asynchronously with no retries

### New endpoint
GET /v0/health_care_applications/:id

response:
```javascript
{
  "data": {
    "id": "68",
    "type": "health_care_applications",
    "attributes": {
      "state": "pending", // possible values: success, pending, failed
      "form_submission_id": null,
      "timestamp": null
    }
  }
}

```

**Comment by erikphansen** [comment]
@lihanli will the `:id` be the `data.id` or `data.attributes.forSubmissionId` that we get back from the call to `POST v0/health_care_applications`?

**Comment by erikphansen** [comment]
I created https://github.com/department-of-veterans-affairs/va.gov-team/issues/6466 for the front end work.

**Comment by lihanli** [comment]
@erikphansen `data.id`
