### ISSUE TITLE
Automate process to easily ingest IAM SSOe data and report on CSP counts

### ISSUE THREAD

**Issue by elizabethkochBT** [department-of-veterans-affairs/va.gov-team#55960]
## Issue Description
The login.gov adoption team, stakeholders, and VA leadership need to review data and analyze CSP counts and CSP method changes to track login.gov adoption.

## User Story
As a Product Owner
I want to know the total user counts by CSP accessing the va.gov ecosystem as we progress through the migration
So that we can track adoption.

---
## Tasks
- [x] Load in data from IAM SSOe
- [ ] Make a repeatable process for scheduled updates on the load above

1. create pre-process script (details in design doc https://docs.google.com/document/d/12zh0ck5eoxmF7aREdfqTJtYQQfwP53mP/edit)
- [x] call the SSOe endpoint to get the access events
- [ ] use map file to replace PII with synthetic IDs
- [ ] don't create any files containing PII

## Acceptance Criteria
- [ ] Process automated on regular weekly cadence

**Comment by jrjamespdx** [comment]
Due to being pulled away from this ticket many times, Steve and I agreed that the best path forward would be to do the following:

1.  Jesse will update the ticket and provide information on the work that has been done so far.
2.  Jesse will create a new ticket to outline a path forward and to handle the remaining work in the next sprint for an engineer to pick up.  (I'll work/pair with the engineer who takes the ticket if there are any questions)
3.  Jesse will close this ticket.

**Comment by jrjamespdx** [comment]
Pre-closing update:

Per my discussion with Steve, this issue will be updated and closed while all remaining work to be done will be placed into a new issue for Ksenia to work on.

Completed Items:
- Initial call to retrieve the saved searches history
- Parsing of XML response from saved search call for URL
- Using parsed URL to in the call to the saved search results
- Saved search results retrieved in CSV/JSON format

Remaining work:
- Replace any PII in the saved search result response with synthetic IDs
- Add any required tests to ensure compliance with relevant standards
- With Steve's guidance, identify and document how this script will be run automatically once finished.
