### ISSUE TITLE
[Data] 10-10CG - Facility page: Discovery on Lighthouse V1 API parent/child relationship

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#55977]
## Background
Once 10-10 CG applications are submitted, they are processed at a facility with Caregiver support, as opposed to a centralized support center.  The facility that provides Caregiver support and processes the applications may not be the same as the facility where the Veteran receives care, however it is associated within the same "Health System".  
A Health System is a network of VA facilities and clinics, with a main parent facility, usually a VA hospital/medical center (VAMC).

The Facility selection page in the application currently asks for the facility where the Veteran plans to receive or does receive care.  The page includes a dropdown to select a State, which then filters the next dropdown to show a list of facilities.  The list of facilities only includes those with Caregiver support.  This means that if the Veteran receives care from a facility that does not have Caregiver support, they will not see it in the list.  This causes confusion and frustration for the applicant.

In an effort to improve the Facility selection page on the 10-10CG, we will be moving from a [static JSON file](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/8cdc5f35ad743af51170adad84b92a8b49504bdf/dist/caregiverProgramFacilities.json) (listing only facilities with Caregiver support) to using the Lighthouse V1 API (not yet in production), so that we can pull a more complete, dynamic list of facilities based on the search criteria provided by the applicant (City, State, Zip).  This will allow us to list VA clinics and other facilities that may not have Caregiver support, so that the applicant can select their preferred facility with more confidence.

**What we need to do**:
- We need to analyze the facilities data in Lighthouse V1 API to view the non-caregiver facilities, the parent relationship (what does that look like?) and see how it might compare to our JSON static list, as well as determining how we might use the relationship to filter the list for Caregiver support facilities, and display that in our form after the applicant makes their selection.

### Resources
- [Lighthouse Facilities API details page](https://developer.va.gov/explore/facilities/docs/facilities?version=current)
- [Implementation of Lighthouse Facilities API in Staging](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/46243) - DONE
- [Initiative Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/Improve%20Facility%20Selection/Improve%20Facility%20Selection%20-%20Initiative%20Brief.md)
- [Improve Facility Selection folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/caregivers/Improve%20Facility%20Selection) - with meeting notes, initial designs and test cases

## Tasks

- [ ] Analyze the Lighthouse V1 API for facilities data (sandbox)
- [ ] Discover how the parent/child relationship between facilities looks like (does it show the Caregiver attribute?)
- [ ] Determine how we can use the data to filter for Caregiver support facilities
- [ ] Compare to the JSON static list of facilities we use today (any missing from either list?)
- [ ] Share findings with the team to determine next steps

## Acceptance Criteria
- Lighthouse V1 API data is analyzed for Caregiver facilities, parent/child relationship, and how we might use the data for the Facilities selection page

**Comment by hdjustice** [comment]
Per Joshua Jennings in the #cms-lighthouse slack channel, the V1 of the API will be available in early May (hopefully!).  It will be deployed to all environments at the same time.  This work will need to be back-logged until we can access V1.
Also - Branden Winn will be PM for the API going forward

**Comment by hdjustice** [comment]
Ticket no longer needed
