### ISSUE TITLE
Supplemental Claims | Match H1 to breadcrumb

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#55982]
### Background 
For this page: https://staging.va.gov/decision-reviews/supplemental-claim/file-supplemental-claim-form-20-0995/start

### Acceptance Criteria
- [ ] The page reads with the following header structure: 
H1 File a Supplemental Claim
H2 Is this the form I need?
H2 What type of claim are you filing a Supplemental Claim for?

### Tasks
- [ ] Add H1 that says 'File a Supplemental Claim' to match breadcrumb.
- [ ] Change 'Is this the form I need?' to an H2

### Design & Build Notes
[DESIGN](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/a/ZOGd21Z#Version)
[COPY](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/sourceofcontenttruth.md#file-a-supplemental-claim)

**Comment by saderagsdale** [comment]
Looks good to me. @eileen-coforma?

**Comment by eileen-coforma** [comment]
Yup, looks good now :D
