### ISSUE TITLE
[eFSR] VA Number input currency update

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#55995]
## Issue Description
`va-number-input` has been updated with a `currency` property and we need to enable that flag throughout the form. 

- [PR where update has been completed](https://github.com/department-of-veterans-affairs/component-library/pull/651)
- [Updated documentation with currency property](https://design.va.gov/components/form/number-input#code-usage)

---
## Tasks
- [x] Update `va-number-input` with currency flag where it's applicable. 
- [x] Confirm functionality stays the same 

## Acceptance Criteria
- [x] `va-number-input`s in FSR have been updated accordingly. 
- [x] All e2e and unit tests are passing 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
