### ISSUE TITLE
[Research] BDD: User Interview Conversation Guide for Initial MVP

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#5601]
## User Story:
As a UX designer, I need to create a user testing conversation guide so I can ensure that all necessary questions are documented in one place and can be referenced during user interviews.

This furthers the discovery effort to understand more about the product being built and identify needs and pain points.  Since this is not a "green field" effort, we will be including the mockups based off of the existing 

## Tasks
- [x] Create conversation guide (according to template if provided)
- [x] Review conversation guide with design team & PM
- [x] (Optional) Review conversation guide with content team, IA team for additional questions that could be beneficial
- [x] Make edits to conversation guide if necessary

## Acceptance Criteria:
- [x] Conversation guide has been completed

## Next Steps
- [x] Send conversation guide to Lauren Alexanderson for approval and scheduling with Perigean.

## Configuration
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chrvalla** [comment]
The research is completed. 

Research plan, Conversation guide, and Research findings can be found here:

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/disability-compensation-claim/bdd/BDD%20Research/Initial-usability-March2020
