### ISSUE TITLE
[Accessibility]: 1010EZ - Accessibility audit: 1010EZ Household Section

### ISSUE THREAD

**Issue by davidakennedy** [department-of-veterans-affairs/va.gov-team#56028]
## Auditor(s)

David Kennedy

**Note: This only includes the new household section, not the entire form.** The rest of the form is tested in #56025.

## Automated

- [ ] Run axe checks on every page or unique state (required)
- [ ] Run WAVE on every page if time allows. WAVE is more visual than axe or axe-coconut, but offers some excellent ways to identify nested headings and HTML5 landmark tags.

## Manual

- [ ] Color contrast checks (recommend using whocanuse.com for beyond compliance reports)
- [ ] Color blindness checks
- [ ] Zoom layouts to 400% and inspect them for readability. If layouts break at 400%, I will start reducing them until they become stable, and log the zoom ratio when things started breaking.
- [ ] Keyboard navigation

## Screen Reader

- [ ] Firefox and NVDA
- [ ] Edge and JAWS
- [ ] iOS Safari and VoiceOver (Mobile)
- [ ] Safari and Voiceover (Desktop)

## Staging or Production Link

https://staging.va.gov/health-care/apply/application/introduction

## Prototype Link

[Mural link with screenshots](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1632923531828/474bfdde942c22a0df26ad416a0b23e36b834d4a?sender=u971851d0c9fe71c880557116)

## Test Users
- vets.gov.user+36@gmail.com
- vets.gov.user+228@gmail.com
- [Find password](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)

**Comment by davidakennedy** [comment]
Closing this ticket out in favor of this duplicate, which covers the Household section accessibility QA work: #51644
