### ISSUE TITLE
[Accessibility]: 1010EZ - Accessibility audit: 1010EZ

### ISSUE THREAD

**Issue by davidakennedy** [department-of-veterans-affairs/va.gov-team#56025]
## Auditor(s)

David Kennedy

**Note: This won't include the new household section. That will be tested via a separate ticket once the new functionality is in a place to be tested.** For Household section, see #56028.

## Automated

- [x] Run axe checks on every page or unique state (required)
- [x] Run WAVE or ARC on every page if time allows. WAVE is more visual than axe or axe-coconut, but offers some excellent ways to identify nested headings and HTML5 landmark tags.

## Manual

- [x] Color contrast checks (recommend using whocanuse.com for beyond compliance reports)
- [x] Color blindness checks
- [x] Zoom layouts to 400% and inspect them for readability. If layouts break at 400%, I will start reducing them until they become stable, and log the zoom ratio when things started breaking.
- [x] Keyboard navigation

## Screen Reader

- [x] Firefox and NVDA
- [x] Edge and JAWS
- [ ] iOS Safari and VoiceOver (Mobile) Time permitting.
- [x] Safari and Voiceover (Desktop)

## Staging or Production Link

https://staging.va.gov/health-care/apply/application/introduction

## Prototype Link

[Mural link with screenshots](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1632923531828/474bfdde942c22a0df26ad416a0b23e36b834d4a?sender=u971851d0c9fe71c880557116)

## Test Users
- vets.gov.user+36@gmail.com
- vets.gov.user+228@gmail.com
- [Find password](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)

**Comment by davidakennedy** [comment]
I kicked this work off today, March 30, 2023. I'm going to update this comment as I go so it captures my progress and my notes.

---

## Axe + Arc Toolkit

- [x] Apply for VA health care (https://staging.va.gov/health-care/apply/application/introduction): No errors from Axe or Arc Toolkit.
- [x] We need some information before you can start your application (https://staging.va.gov/health-care/apply/application/id-form): No errors from Axe or Arc Toolkit.
- [x] Veteran information (https://staging.va.gov/health-care/apply/application/veteran-information/profile-information): No errors from Axe or Arc Toolkit.
- [x] Veteran information: SSN (https://staging.va.gov/health-care/apply/application/veteran-information/profile-information-ssn): No errors from Axe or Arc Toolkit.
- [x] Veteran information: DOB (https://staging.va.gov/health-care/apply/application/veteran-information/profile-information-dob): No errors from Axe or Arc Toolkit.
- [x] Veteran information: Birth Information (https://staging.va.gov/health-care/apply/application/veteran-information/birth-information): No errors from Axe or Arc Toolkit.
- [x] Veteran information: Maiden name (https://staging.va.gov/health-care/apply/application/veteran-information/maiden-name-information): No errors from Axe or Arc Toolkit.
- [x] Veteran information: Birth sex (https://staging.va.gov/health-care/apply/application/veteran-information/birth-sex): No errors from Axe or Arc Toolkit.
- [x] Veteran information: Demographic information (https://staging.va.gov/health-care/apply/application/veteran-information/demographic-information): No errors from Axe or Arc Toolkit.

## Color + Color Blindness

- [ ] Page name (URL):

## Content + Headings

- [ ] Page name (URL):

## Keyboard Navigation

- [ ] Page name (URL):

## Desktop: Safari/VoiceOver

- [ ] Page name (URL):

## Desktop: Edge/JAWS

- [ ] Page name (URL):

## Desktop: Firefox/NVDA

- [ ] Page name (URL):

## Mobile: iOS/VoiceOver

- [ ] Page name (URL):

**Comment by davidakennedy** [comment]
A few notes on this audit:

- Eight total issues found related to accessibility.
- Two issues found that were not related to accessibility, but potential bugs.
- Four of the eight accessibility issues relate to the design system and/or forms library.
- Mostly defect 1s and 2s, some related to the design system.
