### ISSUE TITLE
Research options for DraftingTemplate replacement

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#56027]
## User Story
As a Governance team member, I want to look into finding an alternate option for the DraftingTemplate as the template is fragile and easily corrupted, so that my team can easily generate Staging Review issue tickets. 

Assignee: @it-harrison 
Peer Reviewer: @shiragoodman 

## Description
Governance team created the DraftingTemplate (a Google sheets workbook) in summer of 2021 as a solution to several problems we were facing with the Collaboration Cycle Staging Review. The DraftingTemplate currently provides the following benefits:

- It allows Governance team members to document their findings in a shared space, closed off to VFS teams.
- It allows Governance team members to see what other team members have documented.
- It allows like findings to be merged so the resulting Staging review issue ticket has input from all applicable team members.
- It transforms the findings from Google Sheets to a CSV in gh markdown format, allowing for easy upload/generation of the Staging review issue tickets.

Unfortunately, the DraftingTemplate also has it's share of problems. The problems include:

- It is fragile. Accidentally overwriting a cell or altering a formula could cause problems.
- It requires Governance team to create a new copy for each Staging Review. Permissions must be shared with Shira by the creator so fixes can be made, if needed.
- Once the new copy is made, there is still additional set up tasks that must be completed so that the VA.gov Experience Standards data set and the Collaboration Cycle Point Tracker data set are able to used/referenced within the DraftingTemplate.
- The layout makes it challenging for Governance team members to read and/or document their findings.
- It requires Governance team members to document their findings using Github markdown syntax.
   - Team members will draft their findings in Notepad and copy/paste into the DraftingTemplate to ensure proper formatting.
- The CSV file, which is the output of the DraftingTemplate, needs to be submitted through a node.js script in order to be published as new issue tickets in Github. Team members (outside of Shira) have had issues running the script correctly.

The purpose of this ticket is to identify other options for creating Staging Review issue tickets that still meet the Governance team benefits outlined above. 

## Impacted Artifacts
[Potential solutions for replacing the DraftingTemplate](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2580775269/Potential+solutions+for+replacing+the+DraftingTemplate
)

## Tasks
- [ ] TBD
- [x] Document options in [Potential solutions for replacing the DraftingTemplate](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2580775269/Potential+solutions+for+replacing+the+DraftingTemplate
)
- [ ] Share with Governance team members for their review and input

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have identified options for replacing the DraftingTemplate in the Collab Cycle Staging Review

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
I have researched technical issues related to this issues and will be adding them along with questions/issues for Governance team members to continue going forward into the next sprint.

**Comment by it-harrison** [comment]
@sterkenburgsara @allison0034 @CherylEvans @briandeconinck I have completed a [draft of my thoughts](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2580775269/Potential+solution+for+replacing+the+DraftingTemplate) regarding replacing the DraftingTemplate. When you have a chance, please take a look and tell me what you think.

**Comment by allison0034** [comment]
@it-harrison I do not know what a web app is... is there any place you can link to to show us exactly what it is? Otherwise... love it! I have wanted a different solution since day 1!

**Comment by briandeconinck** [comment]
Thank you @allison0034 for commenting, because it reminded me to look at this too! 😄 

@it-harrison Definitely agree that EKS is the place for this if Platform Console is orphaned. 

I'm not sure if you've thought about authentication and user management and it's probably way too early, but I'll bring it up now anyway. There are a handful of non-Governance people who will probably need the ability to submit findings via the app (eg. people filling in as backups when we're out of office), and I could imagine some people wanting read-only or even comment access too (OCTO people, Platform leadership).

**Comment by it-harrison** [comment]
> @it-harrison I do not know what a web app is... is there any place you can link to to show us exactly what it is? Otherwise... love it! I have wanted a different solution since day 1!

thanks for the callout @allison0034 I have updated the document but basically by web app I mean a website that performs functions like the products in the product directory.

**Comment by allison0034** [comment]
This looks good to me!

**Comment by shiragoodman** [comment]
thank you so much, @it-harrison ! This looks fantastic, and hopefully will be a good solution for us. One thing I'd still like to see is a feasibility estimate. If we were to move forward with the EKS solution, could you provide a rough estimate of hours it would take to complete? Are there any potential risks and/or issues we could encounter during implementation? Are there technical complexities that would require support from other Platform teams?

**Comment by shiragoodman** [comment]
thank you @it-harrison !

@humancompanion-usds I'd like to discuss this with you at our next 1:1. If you're able to, please review Ian's draft document above. Thanks!

**Comment by shiragoodman** [comment]
@it-harrison if you could also please add a section for ongoing maintenance. I want to make sure that if/when the proposed tool needs to be modified, how can we get support if you are not available? Can we cross train other FE folks via the COP? Please let me know fi you have any questions.

**Comment by shiragoodman** [comment]
Per comment above, this work will move into the next sprint. Once maintenance has been added to the proposal, the ticket will be closed and discussed with PO.

**Comment by shiragoodman** [comment]
thank you @it-harrison ! closing this out. Will discuss with @humancompanion-usds at our next 1:1 sync on 5/12

**Comment by it-harrison** [comment]
@shiragoodman the [discovery do](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2580775269/Potential+solution+for+replacing+the+DraftingTemplate?focusedCommentId=2631762872)c has been updated to take into account Chelen's comment.
