### ISSUE TITLE
Design system component deprecation 

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-team#56037]
## Issue Summary
Phase 2 of the component design system deprecation is already starting and next week commits using these components will not pass our GitHub linting rules

## Task

Replace the following deprecated components with updated design system va components

**Telephone:** 

```
/src/applications/financial-status-report/components/AvailableDebts.jsx
/src/applications/financial-status-report/components/AvailableDebtsAndCopays.jsx
/src/applications/financial-status-report/components/Benefits.jsx
/src/applications/financial-status-report/components/EnhancedBenefits.jsx
/src/applications/financial-status-report/components/GetFormHelp.jsx
/src/applications/financial-status-report/components/ResolutionDebtCards.jsx
/src/applications/financial-status-report/components/VeteranInfoBox.jsx
/src/applications/financial-status-report/constants/deduction-codes/index.js
/src/applications/financial-status-report/constants/diary-codes/index.js
/src/applications/financial-status-report/wizard/components/Contacts.jsx
/src/applications/financial-status-report/wizard/pages/Benefits.jsx
/src/applications/financial-status-report/wizard/pages/Dependents.jsx
/src/applications/financial-status-report/wizard/pages/VetTec.jsx
```

**TextInput**
```
/src/applications/financial-status-report/components/EmploymentRecord.jsx
/src/applications/financial-status-report/components/EnhancedEmploymentRecord.jsx
/src/applications/financial-status-report/components/EnhancedSpouseEmploymentRecord.jsx
/src/applications/financial-status-report/components/EnhancedVehicleRecord.jsx
/src/applications/financial-status-report/components/ResolutionDebtCards.jsx
/src/applications/financial-status-report/components/otherAssets/AddAsset.jsx
/src/applications/financial-status-report/components/utilityBills/AddUtilityBill.jsx
```
**Additional Info**
```
/src/applications/financial-status-report/components/DebtCard.jsx
/src/applications/financial-status-report/constants/deduction-codes/index.js
/src/applications/financial-status-report/constants/diary-codes/index.js
/src/applications/financial-status-report/containers/IntroductionPage.jsx
/src/applications/financial-status-report/pages/assets/other/records.js
/src/applications/financial-status-report/pages/assets/realEstate/enhancedIndex.js
/src/applications/financial-status-report/pages/assets/vehicles/records.js
/src/applications/financial-status-report/pages/expenses/other/records.js
/src/applications/financial-status-report/pages/income/spouse/spouseInfo.js
/src/applications/financial-status-report/pages/veteran/contact.js
```

**Select**

```
/src/applications/financial-status-report/components/EmploymentRecord.jsx
/src/applications/financial-status-report/components/EnhancedEmploymentRecord.jsx
/src/applications/financial-status-report/components/EnhancedSpouseEmploymentRecord.jsx
```

**FileInput**
```
/src/applications/financial-status-report/components/FileUploader.jsx
```

## Acceptance Criteria
- [ ] Old components are replaced by va- design system components
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] All axe checks pass

---

**Comment by Dr-Pongo** [comment]
Updated with combined debt portal, debt letters, and medical copay locations! (Luckily it was only Telephone!)

**Comment by OptionSelect** [comment]
Instructions for how to migrate each component found here. 
https://design.va.gov/about/developers/using-web-components#how-to-migrate-to-web-components

**Comment by josephrlee** [comment]
Hey team, I saw some more [depcrated class in the wizard](https://github.com/department-of-veterans-affairs/vets-website/blob/96128fdb5d4136f8ae2e3fb34007d54e2a7bcc03/src/applications/financial-status-report/wizard/components/StartFormButton.jsx#L17). The Start your request now button is using an old green background color that's no longer in use. Here's a [slack thread on the topic too](https://dsva.slack.com/archives/C0NGDDXME/p1655496948976409?thread_ts=1655474477.229769&cid=C0NGDDXME).

**Comment by josephrlee** [comment]
Hey team, I saw a [depcrated class in the wizard](https://github.com/department-of-veterans-affairs/vets-website/blob/96128fdb5d4136f8ae2e3fb34007d54e2a7bcc03/src/applications/financial-status-report/wizard/components/StartFormButton.jsx#L17). The Start your request now button is using an old green background color that's no longer in use. Here's a [slack thread on the topic too](https://dsva.slack.com/archives/C0NGDDXME/p1655496948976409?thread_ts=1655474477.229769&cid=C0NGDDXME).

Is this something that needs to be fixed too? 

Here's a screenshot of the notice:
![Screenshot 2023-03-30 at 3.03.22 PM.png](https://images.zenhubusercontent.com/63ea96045c6deec1c9a25425/418e6cb5-3180-46cd-8d44-be32856265cf)

**Comment by HeatherRienks** [comment]
@Dr-Pongo - to create PR and finish up today

**Comment by Dr-Pongo** [comment]
Closing out since FileInput was the last one and it's now merged! 
CC @HeatherRienks

**Comment by HeatherRienks** [comment]
YAHOO!!! Thanks FE Team!
