### ISSUE TITLE
LIGHTHOUSE

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#56045]
### LIGHTHOUSE ROUTES TO BE MIGRATED TO EKS
/services/apps/v0
/services/veteran/v0
/services/appeals/v1/decision_reviews
/services/appeals/v2/decision_reviews
/services/vba_documents/v1
/services/va_forms/v0
/services/vba_documents/internal/v0
/services/veteran_confirmation/v0
/services/claims/v1
/services/claims/v2/
/services/appeals/v0
/services/appeals/docs
/internal/auth/v2
/services/meta/v0/version
/services/meta/v0/ping"
/services/veteran_verification/v0
/services/veteran_verification/v1

### NOTES FROM MEETING
https://docs.google.com/spreadsheets/d/1lDH9Ywwup1JpoBjjFOo6kTyMZ7HhfE5DRA_bQXlsEPU/edit#gid=0

### ACTION ITEMS IN PREP FOR APRIL 10 OR 11 MIGRATION TO EKS
- [ ] Config change will need to happen by lighthouse (similar to what was done with lower envs)
- [ ] Prep revert PR (just incase we need it...)
- [ ] TT1 to create graphs in datadog
- [ ] TT1 and LH to monitor migration activity + communication about issues

[Revproxy config](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/templates/nginx_api_server.conf.j2#L233-L266) that points lighthouse routes to Kong

**Comment by laineymajor** [comment]
ADDED TO THIS SPRINT AS PART OF THE EKS MIGRATION.

**Comment by laineymajor** [comment]
Reopening epic and adding it to new sprint. We are having new issues come up with the Lighthouse endpoints migration that need to be addressed. Those issues are being tracked within this epic.

**Comment by laineymajor** [comment]
While the 502s have significantly decreased, this will be left open for monitoring purposes.

**Comment by laineymajor** [comment]
closing and moving to monitoring epic
