### ISSUE TITLE
[Research] BDD: Initial MVP Research Synthesis

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#5605]
## User Story or Problem Statement
As a UX Designer, I need to synthesize gathered data from user testing sessions so I can identify successes, gaps, pain points, and improvements to the BDD design.

This is for the initial round of research which includes some overall BDD discovery as well as a walk through and research with the modified original claims process.

## Goal
A document containing data from user testing sessions that has been organized into common themes and recommendations. 

## Objectives or Key Results this is meant to further
- Finding pain points in the design
- Discovering improvements to the design

## Tasks
- [x] Synthesis document (readout) has been created
- [x] Organize data from the interview sessions into themes
- [x] Create recommendations based on key themes determined from the usability research

## Acceptance Criteria
- [x] Key Themes are identified
- [x] Recommendations are created
- [x] Readout is generated
- [x] Meeting held with Andrea and decisions are made on scope and implementation/design expectations

**Comment by chrvalla** [comment]
The research has been conducted and all research documents can be found here: 

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/disability-compensation-claim/bdd/BDD%20Research/Initial-usability-March2020
