### ISSUE TITLE
[UX] AVS MVP: Research Plan

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#56053]
# Description
How might we understand if the AVS MVP meets veteran expectations

# Tasks
- [x] Create [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/avs/research/2023-04-MVP-Usability/research-plan.md) and [folder in git](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/avs/research/2023-04-MVP-Usability)
- [x] Review with health apps team
- [x] Submit to research repo for Shane review
- [x] Complete kickoff with Perigean, if needed

# AC
- [x] Research plan created
- [x] Consensus reached with health apps
- [x] Submitted to Shane
- [x] Kickoff completed with Perigean, if needed

**Comment by kristenmcconnell** [comment]
Moving back to backlog until technical discovery progresses a little further.

**Comment by kristenmcconnell** [comment]
@ninaranusavice Async send availability for research sessions for June 1 - 9.

**Comment by kristenmcconnell** [comment]
cc @ninaranusavice, since you are finalizing the research plan today.
