### ISSUE TITLE
Decision Reviews | Replace deprecated components

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#56058]
## Issue Description

The Design System Team is currently [deprecating React components](https://vfs.atlassian.net/wiki/spaces/DST/pages/2243854357/Plan+-+Deprecation+plan+for+React+components) (mostly [`ProgressButton`](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1356) in our case).

Our team needs to find and replace deprecated/planned deprecated React components. 

## Tasks
- [ ] Find and replace listed React components with recommended web component
- [ ] Update unit tests
- [ ] Update e2e tests

## Acceptance Criteria
- [ ] All tasks complete
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression

**Comment by Mottie** [comment]
Done in https://github.com/department-of-veterans-affairs/vets-website/pull/23863
