### ISSUE TITLE
Add Yarn Workspace to VSF vaos

### ISSUE THREAD

**Issue by rmessina1010** [department-of-veterans-affairs/va.gov-team#56050]
## Description
Adds Yarn Workspaces  to vaos app in vets website

path:

## Original issue(s)
---

## Testing done
- [x]  Confirm workspace path: `src/applications/vaos` !
- [x] Confirm demo scripts run
- [x] Confirm sym link in root  `node_modules` folder is present after  yarn install
- [x] Unit/e2e
- [x] Visual Web Test:  link  pending 

## Tasks For vaos team to do
- [x]  Check dependencies/devDependecies / peerDependencies are correct for your app
- [x]  If required, add` nohoist`  dependencies to root `package.json`
- [x]  If required , add scripts
- [x]   Visual Test  link pending
- [x]  Approve PR

Docs:
https://depo-platform-documentation.scrollhelp.site/developer-docs/guide-for-maintainers-overview
(Please note that as a VSF app, you don't have any exports (or need an exportsFile.js)

## Acceptance criteria
- [x] Testing done completed
- [x]  Tasks For check-in team to do

**Comment by rmessina1010** [comment]
Visual tests: https://docs.google.com/spreadsheets/d/1d6V7wmKNQlWxVxYzQIH7NpIEYY3h6GQfhlM8Mkrw_1c/edit#gid=0

**Comment by rmessina1010** [comment]
Yarn work spaces PR successfully merges, tested and deploy. After 1 day,  Simi  Adebowale has confirm that previous functionality has not been adversely affected.  Closing ticket.
