### ISSUE TITLE
[UX] AVS MVP: Create conversation guide

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#56056]
## Related Documentation
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/digital-health-modernization/mhv-to-va.gov/avs)
- Platform [research process](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html) and [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)
- [Conversation Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/avs/research/2023-04-MVP-Usability/conversation%20guide.md)

## Description
- Create the conversation guide for testing with users

## Tasks
- [x] Create new folder for this specific test in this [overall research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/digital-health-modernization/mhv-to-va.gov/avs/research).
- [x] Create conversation guide (template in research checklist above)
- [x] Create the notes folder for Perigean (follow guidelines above)
- [x] Identify pilot participant and date

## Acceptance Criteria
- [x] Review conversation guide with health apps team
- [x] Post finalized conversation guide to GitHub folder

**Comment by kristenmcconnell** [comment]
@ninaranusavice Can you link the conversation guide here and pilot participant info, then close this story.
