### ISSUE TITLE
[Research] BDD: Final MVP Research Synthesis

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#5606]
## User Story or Problem Statement
As a UX Designer, I need to synthesize gathered data from user testing sessions so I can identify successes, gaps, pain points, and improvements to the BDD design.

This is for the final round of research with the built out MVP.

## Goal
A document containing data from user testing sessions that has been organized into common themes and recommendations. 

## Objectives or Key Results this is meant to further
- Finding pain points in the design
- Discovering improvements to the design

## Tasks
- [ ] Synthesis document (readout) has been created
- [ ] Organize data from the interview sessions into themes
- [ ] Create recommendations based on key themes determined from the usability research

## Acceptance Criteria
- [ ] Key Themes are identified
- [ ] Recommendations are created
- [ ] Readout is generated
- [ ] Meeting held with Andrea and decisions are made on scope and implementation/design expectations

**Comment by luke-gcio** [comment]
Completed, work found in GitHub.
