### ISSUE TITLE
[PRODUCT] Update and document tasks required within the VAMC-Upgrade "RUN BOOK" detailing tasks and ownership [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#5607]
## User Story or Problem Statement
As a Stakeholder, I need to be able to estimate tasks and track expectations for the product using a Run Book, so that team members and stakeholders can better estimate work to be complete and the timeline to complete those tasks. 

## Goal
_Consolidate task and work estimates in one runbook_

## Objectives or Key Results this is meant to further
* Transparency to team and stakeholders

## Resources - Tools - Documentation
_There are no existing run books that will help the content and expectations of VAMC-Upgrade
_New Runbook will be created to track tasks and expectations

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] Document all know tasks and timelines for those tasks in deployment of VAMC_System_Upgrades_
- [ ] Creation of RUN BOOK with deployment tasks, timeline estimates, owners, notes, a Communication Plan, and Roll Back plan_
- [ ] Runbook is dated and loaded to GitHub REPO_

## Acceptance Criteria
* Run Book is complete with known tasks and estimates
* Dated runbook (Latest copy) is uploaded to GitHub REPO
* Links to Run Book are shared with Stakeholders for review and discussion
* Run Book is a living document and will change through product process and execution.
