### ISSUE TITLE
Research: Backend logging

### ISSUE THREAD

**Issue by holytoastr** [department-of-veterans-affairs/va.gov-team#56089]
## Issue Description
It will be necessary to track and log users on the back end as we implement the grandfathering flow

---
## Tasks
- [x] Research options for logging and tracking on the backend
- [x] Learn how to implement logging/tracking options
- [x] Learn how to test logging/tracking options (automated testing)
- [x] Learn how to retrieve logging/tracking data

## Acceptance Criteria
- [x] Developer has an understanding of how to implement back end logging/tracking and can apply research to future tickets
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by elizabethkochBT** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Logingov-adoption-Team-632280b31e745000136a61fc/issues/department-of-veterans-affairs/va.gov-team/56089?planning-poker) with Zenhub @holytoastr

**Comment by holytoastr** [comment]
@elizabethkochBT  It's a research task, so I gave it a 5 to be safe and allow myself the time to dig in. If I finish it sooner, that's a bonus.
