### ISSUE TITLE
[BE] Add a method to send text message to VANotify library in vets-api

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#56098]
## User Story
As a Veteran, I want to receive a text message with status when I file a travel claim during online check-in

## Tasks
- [ ] [BE] Add a method in VANotify module in vets-api to use the /text endpoint in notifications-api to send a text message

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
