### ISSUE TITLE
Sign-in Service App - GHA - Build and push docker image ECR

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/va.gov-team#56104]
## Summary
Create a GitHub action in the `sign-in-service` repo that builds and pushes a docker image to ECR.

## Tasks
- [x] Add AWS credentials to repo action secrets
#### Github Action
- [x] Configure AWS credentials 
- [x] Login to ECR
- [x] use `docker/build-push-action` to build and push image
- [x] tag image with git ref

## Acceptance Criteria
- [x] Image builds and pushes to ECR
- [x] Image tagged correctly
