### ISSUE TITLE
Sign-in Service App - Create Dockerfile 

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/va.gov-team#56102]
## Issue Description
Create Dockerfile for [Sign-in Service app](https://github.com/department-of-veterans-affairs/sign-in-service).

## Tasks
- [x] Dockerfile is in SiS app repo
- [x] Latest Ruby version (3.2.2 as of writing)
- [x] Latest bundler version (2.4.10)
- [x] Install dependencies (`build-essential`, `libpq-dev` for now)
- [x] Install VA certs
- [x] Use builder pattern
- [x] Ensure gems are cached properly

## Acceptance critera
- [x] Image builds successfully
- [x] Layers are cached properly
