### ISSUE TITLE
[UX] Low-fidelity AVS MVP Wireframes

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#56113]
# Description

# Tasks
- [X] Initial wireframe set in [Sketch](https://www.sketch.com/s/05d5a740-4fc7-4380-8d83-e7acfbab201b).
- [x] Update wireframes through the discovery phase.
- [x] Review with health app team and Lauren
- [x] Review with stakeholders

# Acceptance criteria
- [x] Feedback from stakeholders is incorporated into the wireframes
