### ISSUE TITLE
[User experience issue] A user can see a message that they have a decision letter ready, but can't access the letter on VA.gov

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#56112]
## Value Statement
**_As a_** Veteran
**_I want to_** see my decision letter when a portion (but not all) of my issues in a claim have been decided
**_So that_** I can access my decision letter more easily via VA.gov

---
## Background Context
- Currently, a Veteran can be in a state where they see a message in CST saying "You have a decision letter ready" and they get a physical decision letter, but there is no way for them to access the decision letter in CST. 
- Currently, we get a value for when the decision letter is available sent back to us. We've created a UI state to deal with this response when a claim is closed. We haven't yet created designs for the cases in which a claim is OPEN, but we still get that value returned saying the decision letter is available. 

## Acceptance Criteria
- [ ] _Design for this scenario_
- [ ] _Ability for Veteran to get to Claim Letters page from the claim detail view_
- [ ] _The appropriate letters are available and accessible from the Claim Letters page_

## Open questions
- How is the claim status UI impacted by this? Does it need to be adjusted in some way to make this scenario clearer?
- How should issues be displayed and what information/status about them should we provide?

## Tasks
- [ ] _Create a mock for this design_
- [ ] _Task_
- [ ] _Task_

**Comment by HeatherWidmont** [comment]
We don't have a design for this yet, so @uxgary will pick up this ticket. Will try to do it this sprint

**Comment by skylerschain** [comment]
I'm gonna pick this up

**Comment by skylerschain** [comment]
Mocks for this are ready:
https://www.sketch.com/s/4806c02e-9cde-47ff-9326-f3a4acc53373/p/7874DF27-BF38-4D70-8AB6-E5BEFDCA3A21/canvas

**Comment by HeatherWidmont** [comment]
@samcoforma will take a look at this tomorrow

**Comment by jacobworrell** [comment]
this ticket is duplicative, closing it
