### ISSUE TITLE
[Design] HLR: Remove Additional Notes Page

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#5611]
## User Story:
As a veteran, I need a submit requests for higher level review in an easy to navigate and understand fashion so that I can successfully get my benefits.

After the usability testing research, we found that we do not want to have the Notes page due to legal issues.  Essentially, anything written in that form will end up being considered new evidence and therefore create a supplemental claim and kick them out of HLR process.

## Tasks
- [x] Kill the page

## Acceptance Criteria:
- [x] Page is killed

## Configuration
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
All associated designs for the additional notes page have been archived in our official HLR design invision project.
