### ISSUE TITLE
[Design] BDD: Initial BDD Design Mockups Before Usability Studies

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#5615]
## User Story:
As a veteran, I need a submit a BDD claim so I can get my benefit soon after my separation.

This is in preparation for the usability study.  Since we do not have a baseline design for Original Claims (Christian spent some time looking) we will have to start from scratch.  Given that, this story is being pulled out as a separate effort from the #5556 story.

## Tasks
- [x] Mockups created in Sketch of expected BDD flow (based on Original Claims)

## Acceptance Criteria:
- [x] Delivered new Sketch design (all branches)
- [x] Design reviewed and accepted

## Configuration
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chrvalla** [comment]
BDD Sketch files are done. Invision prototype is done. 
Prototype has been reviewed by VSP design collaboration team. 
Link to prototype:
https://vsateams.invisionapp.com/share/Z8W8ACWN3UG
