### ISSUE TITLE
Explore what preview environment metrics should be tracked for MVP

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#56162]
## Issue Description
With a working Preview Environment, it will be helpful to begin to consider what metrics should be tracked to ensure they are reliable, usable, performing properly, etc.

---
## Tasks
- [x] Review initially defined success metrics
- [x] Brainstorm potential success metrics

## Acceptance Criteria
- [ ] Compile a list metrics to track for the preview environment MVP
- [ ] Create tickets to track those metrics

**Comment by JoeTice** [comment]
Initially Defined Success Metrics
- Fewer instances of Platform's testing ecosystem as a negative theme on customer satisfaction survey
- Decline in support requests around review instances
- Increase in usage of preview environments
- Error rate and reliability of preview environments
- Take the pieces of the QA health survey that are relevant to review instances and compare to the recently completed survey

**Comment by JoeTice** [comment]
Potential Additional Metrics
- Adoption rate, % of development teams within the org that are using Preview Environments
- Number of times accessed
- Number of users accessing PEs
- Number of PRs/day
- Time to review/close PRs
- Resource utilization
- Spin up time
- User satisfaction - is there any way to build this into Preview Environments?
