### ISSUE TITLE
[UX] [SPIKE] Determine how artboards should be named in sketch

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#56179]
## Timeboxed
1 hour (1 meeting)

## Description 
How might we update artboards in sketch to, 1) have a consistent naming convention, 2) describe the wireframe for team members and stakeholders to better understand the context. 

## Tasks
- [x] Determine artboard naming convention 
- [x] Create any f/u ticket(s)

## AC
- [x] Artboard naming convention determined 
- [x] f/u ticket(s) created

**Comment by loripusey** [comment]
@benbrasso-agile6 @ytsaoca did this meeting happen? can we close this ticket?

**Comment by ytsaoca** [comment]
The meeting is on Apr 26.

Mural for brainstorming https://app.mural.co/t/vfscie8528/m/vfscie8528/1681854535164/cb0d05833cda5a8406ca974557008c9f9c7c90a5?sender=u70b8b2930b03d3ef317d2520

**Comment by ytsaoca** [comment]
@benbrasso-agile6  Will create a ticket for next steps: create some names of artboard and then share with the UX team.

**Comment by ytsaoca** [comment]
@benbrasso-agile6  Will create a ticket for next steps: create some names of artboard and then share with the UX team.

**Comment by benbrasso-agile6** [comment]
f/u ticket created and assigned to @kellysmith1008 https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/57557
