### ISSUE TITLE
Login: Investigate MHV/ID.me vulnerability

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5618]
## Background

We got the following email and we need someone to look into it to confirm these issues and help us determine next steps moving forward:

Message from Veteran:
Is there a way to get this information out? How hackers get into your VA account and can change your direct deposit info to steal your disability deposit. My account was hacked and I figured out how they did it.
VA.gov has three sign-in settings. They are DS Logon, MyHealtheVet and ID.me. MyHealtheVet does not have the layers of security that ID.me and ebenefits have. Because of this, and the circular way the websites grant access to each other, once a hacker can get into your MyHealtheVet account, they can use this “sharing” to change info in VA.gov.
Since direct deposit is now in VA.gov, it makes it that much easier, since va.gov is easier to hack into than ebenefits.
WHAT TO DO RIGHT NOW:
Make sure
1) You have 2-factor sign-in method set up on id.me AND
2) You have your DS logon and My HealtheVet log-ins linked to your ID.me account inside ID.me.
If your My HealtheVet account is not linked in your ID.me account, whether or not you have 2-factor sign in enabled, your VA.gov account is vulnerable to being hacked.
 
HOW THE HACKER BREAKS IN:
ID.me Vulnerability:
There have been several data breeches in the past couple of years, most significant was the 2017 Equifax breech which exposed the personal information on 147 million people.
ID.me has several ways to verify the identity of the person, but the vulnerability lies with verifying information from your credit consumer profile which is no longer a secure method because of the recent data breeches. A hacker only needs your SS#, DOB and current mailing address to verify your identity on ID.me.
The hacker creates a new ID.me account with their email and telephone number, but with your name and then verifies the new account through information contained in your credit profile (rather than using your passport, drivers license etc).
 
My HealtheVet Vulnerability:
VA.gov does not require that the DS Logon and MyHealtheVet account all be linked in ID.me, so if you created your accounts separately, you may not have ever linked them all in ID.me to begin with.
If you don’t have MyHealtheVet already linked to the logins to your ID.me account, a hacker can access your MyHealtheVet account by logging in using the forged ID.me account, verifying your info, then doing a password reset and using their new forged id.me account to access and control your account.
Once they have updated the login and password info on MyHealtheVet, they can log in and change your email and other personal information including the challenge questions. Also, they will see the answers to your existing challenge questions and every bit of other personal information you have there. They will also likely download all your information kept on My HealtheVet.
Once they have changed the log-in information on My HealtheVet to their phone and email, they can use your hijacked My HealtheVet login to log into your va.gov account – including with 2-factor authentication with their own number in the forged ID.me account. Once in your VA.gov account, they can change the contact info to avoid notices to you, then change the routing and checking account for your direct deposit and steal your disability payment.
 
HOW THIS HACK CAN BE FOILED
Secure your ID.me account with 2-factor sign in AND
Link BOTH your DS Login and My HealtheVet to your ID.me account (in the logins section).
The main thing is having your My HealtheVet account (and DS logon) linked with 2-factor sign in inside your ID.me account – this will cause a look-up error in va.gov even if there is a forged ID.me account.
I have tried to warn ID.me, the VA and MyHealtheVet about the vulnerability, but no response. Hackers can find targets by joining veterans disability facebook groups, find info on subject on the dark web, then work on hacking in on the account that are vulnerable.
I don't know how to make the VA pay attention to this, so I hope you can pass the warning on to members so they secure accounts as best as they can before they become victims of these hackers.
 
## Tasks

- [ ] Read through email
- [ ] Try to duplicate steps the email outlines that allow hackers to get into people's accounts
- [ ] Determine if there's a security concern
- [ ] Based on investigation, determine potential solutions

## Acceptance Criteria

- [ ] Either determine there isn't a security concern, OR if there is a concern, determine next steps to mitigate the problem

**Comment by chrisj-usds** [comment]
From @patrickvinograd 

Some of this tracks, some of it is confusing:

* Yes it's a known thing that knowledge-based verification is problematic post-Equifax breach. If a malicious actor can establish a LOA3 credential (where they control the username/password and second factor) with somebody else's PII traits then they can do a great deal of bad stuff.

* But, once they've created that LOA3 account on ID.me, they could just sign in to VA.gov and change direct deposit info and contact information, I'm not sure why the additional steps involving MHV are mentioned, other than I guess locking the legitimate user out of all their accounts.

* I'm not 100% clear on the step about using the forged ID.me account to log in to MHV and "verifying your info, then doing a password reset", etc. Does signing in to MHV through ID.me enable changes to the person's MHV credential info (password reset, challenge questions, etc)? If so then that linkage/cross-talk may be something worth investigating/limiting. 

* I'm also want to validate "The main thing is having your My HealtheVet account (and DS logon) linked with 2-factor sign in inside your ID.me account – this will cause a look-up error in va.gov even if there is a forged ID.me account." because I'm not aware of what this lookup error is or how it's tied to 2-factor and if it incidentally providing some security we don't want to inadvertently remove it.

**Comment by chrisj-usds** [comment]
@Samara-Strauss 
Patrick pointed out that security issues shouldn't be in public channels. Can you move this to: 

va.gov-team-sensitive
