### ISSUE TITLE
Add additional screens into unified check-in experience sketch page with user flows 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#56181]
## Description 

How might we move the additional screens wireframes into the unified check-in experience sketch page with user flows? 

## Tasks

- [x] Add the additional screens wireframes into the unified check-in experience sketch page with user flows 
- [x] Confirm with engineers, e.g., error pages, etc. 

AC

- [x] Additional screens wireframes were added into unified check-in experience sketch page with user flows 
- [x] Confirmed with engineers, e.g., error pages, etc.

**Comment by kellysmith1008** [comment]
Ya-ching, Ben, and I met yesterday to divvy up the work for additional screens - work has started on this ticket

**Comment by kellysmith1008** [comment]
I've added my screens to the workflow and the accordions for updating information
