### ISSUE TITLE
[FE] Display Clinic Phone Number or Facility Phone Number if Clinic Phone is Not Available

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#56186]
## User Story
As a Veteran, I want access to the clinic phone number associated with my appointment so that I can call them if I have questions or problems with my appointment.

## Tasks
- [ ] [FE] When we display the phone number associated with an appointment, we should always display the clinic phone number. In the event there is no clinic phone number available, we should display the facility phone number. If we don't have any phone number to display then we don't display the labels/text.
    - NOTE: we don't know if we have access to the facility phone number, when we find out let's discuss 
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
@benbrasso-agile6 run this by Stephen to verify

**Comment by brianseek** [comment]
@benbrasso-agile6 & @loripusey This is merged and ready to validate.

Hard to validate on stage, so here are some screen shots:
With number:![localhost_3001_health-care_appointment-pre-check-in_complete_lang=en (1).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/b78eada5-60a8-434b-99de-1cb0bb27f695)

Without number:
![localhost_3001_health-care_appointment-pre-check-in_complete_lang=en.png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/efd18d7e-a8a4-403d-9469-042ee73be74d)

**Comment by loripusey** [comment]
LGTM!

**Comment by benbrasso-agile6** [comment]
LG
