### ISSUE TITLE
Assess request to add COVID note to VA DIC page

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#56217]
## Issue Description
Angie asked us to add the following note to the [About VA DIC page](https://www.va.gov/disability/dependency-indemnity-compensation/) in the "How do I apply for compensation?" section:

**Note:** Our understanding of COVID-19 and the impact that underlying conditions have on individuals with this disease is ever-evolving. If your loved one passed away due to COVID-19 and a service-related condition worsened the illness, you may qualify for Dependency and Indemnity Compensation (DIC). Information on DIC and how to file a claim can be found here. If a claim for DIC is filed and COVID-19 is listed as a cause of death, VA will take into consideration the contributory effects of any service-related conditions.

---
## Tasks
- [x] Assess request and suggest PL wording
- [x] Send to Angie for approval
- [x] Copyedit and publish

## Acceptance Criteria
- [x] New note is live on page

**Comment by laurwill** [comment]
Hi @DanielleThierryUSDSVA ,
We got a request to add a note about service-related conditions contributing to COVID deaths to the VA DIC page.

We have 2 options:
1. Add a short note like this in the eligibility section:
**Note:** If you're the survivor of a Veteran who died from COVID-19 and a service-related condition made their illness worse, you may be eligible for VA DIC. 
2. Add a Q&A to the COVID FAQs page about DIC claims for COVID deaths, and link to it from this VA DIC page.

Also want to ask if this content needs any further review from the joint task force or other SMEs. We can check in about this on today's sync!

**Comment by laurwill** [comment]
Update: Danielle confirmed that it's best to add this type of COVID content to the related page, rather than the COVID FAQs. We don't need additional review for this type of note.

@megzehn , could you copyedit the note I added to the eligibility section before I send to Angie? It's node 855. Thank you!

**Comment by megzehn** [comment]
Thanks @laurwill! I copy edited the note you added, and it looks good.

**Comment by laurwill** [comment]
@megzehn , we got approval for this note. Could you publish today or tomorrow? Thanks!

**Comment by laurwill** [comment]
Update: Since Megan's out and already copyedited, I published the page with the new note. @RLHecht I'm moving to validate, and then you can close!

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
