### ISSUE TITLE
[DD][BRD][EKS] Sidekiq alerts cleanup post Production

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#56224]
## Description

Now that sidekiq has been migrated over to EKS, we need to clean up lingering alerts and notifications that came from BRD

## Tasks

- [x] Remove all todos in [sidekiq.yaml](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/datadog/catalog/sidekiq.yaml#L1) pertaining to BRD
- [x] [remove old alert](https://vagov.ddog-gov.com/monitors/104982) (no IaC)

## Acceptance Criteria

- [x] Tasks above has been cleaned up (ensure EKS alerts are clean)
- [x] Monitor and alerts from BRD are deprecated (anything BRD related is in prometheus) 
- [x] Deprecated monitors no longer available via DD

**Comment by laineymajor** [comment]
Clean up some of the load alerts. Keep alerts actionable.

**Comment by laineymajor** [comment]
@rjohnson2011 please review info and let us know if you have any questions

**Comment by rjohnson2011** [comment]
All BRD related todos in `sidekiq.yaml` have been removed. Only jobs relating to EKS are remaining.

The deprecated IAC alert in DataDog has been removed.
