### ISSUE TITLE
Determine timeline and goals for CMS Team transition from Sitewide to Platform

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-team#56226]
## Description

The CMS Team will need to transition from a Sitewide team to a Platform team. Previously, the DevOps side of this team lived in Platform Crew, and the remainder of the CMS Team (UX, Drupal Devs, etc.) went into the Sitewide Crew. As of January 2023, the teams were combined due to contract limits and reassigned to Sitewide. Since the Drupal CMS is a platform to build the unauthenticated VA.gov experience, adding the CMS team to this portfolio will allow other teams across the VA to build within this CMS structure.

## Northstar/Mission Statement

Drupal provides a platform that increases VA's ability to deliver consistent, accessible, quality information to Veterans and their dependents across the digital ecosystem.

## Assumptions

By moving the CMS out of the Sitewide Crew and into the Platform Crew, we will be able to:

- Enhance the accessibility, stability, reliability, resiliency, and security of Drupal so that Veterans and their families are more likely to locate a single, credible source of truth across VA.gov

## Considerations

In order to make the transition to Platform some things we must do:

- Evaluate the current state of Drupal and the CMS Team processes/procedures/documentation/and the way they work 
- Deep dive into the different disciplines represented on the CMS team to determine if they can be integrated into the larger CoPs (for collaborative purposes and a sense of mission-driven belonging)
- Determine how technical, UX, and other discipline practices differ from Platform and what the scope of the CMS Team, aka what will they keep different and what will we integrate?
- Think through access and subscriptions to different tools (which contract pays for what?)
- Determine what to do with Github and the various labels, repos, boards
- Combine onboarding and collaboration cycle efforts

## Acceptance Criteria

- [x] Determine a timeline for the team transition 
- [x] Define what it means to "platformize" the CMS team from each discipline perspective in a V.1 document (Product, Design, Research, Engineering)
- [x] Create a goal post or definition of done for this initial phase of transition
- [x] Coordinate with Sitewide stakeholders on the plan

**Comment by EWashb** [comment]
Also, what exactly does transition mean for us? Will CMS still be tied to Sitewide in any way? We should think through the Platform ATO as well.

**Comment by EWashb** [comment]
[WIP Strategy Doc](https://dvagov-my.sharepoint.com/:w:/r/personal/erika_washburn_va_gov/_layouts/15/doc2.aspx?sourcedoc=%7B2B608D85-1CED-4136-A5BA-E69036BD059A%7D&file=CMS%20Team%20to%20Platform%20Crew%20Strategy.docx&action=default&mobileredirect=true&DefaultItemOpen=1&ct=1683645069076&wdOrigin=OFFICECOM-WEB.MAIN.EDGEWORTH&cid=a7bdc80b-8371-4c99-a400-565c65f56989&wdPreviousSessionSrc=HarmonyWeb&wdPreviousSession=eafa8e64-c427-4176-9bc8-681fb29c3352)

**Comment by EWashb** [comment]
I need to confirm with Sitewide Crew Chief on direction of this initiative.

**Comment by EWashb** [comment]
I've spoken with both Crews and have found no issues with my ideas.

**Comment by EWashb** [comment]
@productmike 

An addition here that I failed to mention before is a sure-up of our intake processes and guidance for how teams can work with our team. The reason for CMS to solidify itself as a Platform is so that Drupal can be scaled. If we are a Platform as a Service...what does that mean? Do we have everything we need in place for additional teams to know HOW to work in Drupal. Right now, no. But what might those teams need to do that? Starting all the way with something as simple as access, all the way through to Collab Cycle and beyond. We can do some blue sky thinking..

**Comment by productmike** [comment]
This is perfect additional guidance @EWashb, thank you
