### ISSUE TITLE
BE | Authentication Experience | Monitor EKS production rollout

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#56223]
## Background
Tech Team 1 will complete a route-based rollout for EKS to production on April 4TH @ 9AM ET.

Monitor the following endpoints that use BGS:
- /profile/ch33_bank_accounts
- /profile/payment_history

Slack thread: https://dsva.slack.com/archives/C04M7T1CZAS/p1680544264182229

## Tasks
- [ ] Monitor endpoints
- [ ] Report issues to #eks-migration-support
- [ ] Attend zoom room if/when concerns arise
- [ ] Be available to answer questions we might have about your app and/or your reported issues(s)
- [ ] Be available to help us recreate an issue if needed, and test the resolution

**Comment by ajakabcin** [comment]
hey @BerniXiongA6 and Travis I think this is for Profile? Adding the label and sprint epic for you :)

**Comment by tpharrison** [comment]
The endpoints are used by both Profile and MyVA.  The endpoints were migrated to the EKS environment earlier today.  I've been monitoring and everything looks.  I will close this out later today.
