### ISSUE TITLE
Design Debt

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#56238]
## Issue Description
Capturing future design iterations or ideas that will be progressed and prioritized as time allows. 

---
## Tasks
- [ ] Design team to capture information on required enhancements or changes that need designated design time to implement. 
- [x] Clean up header and footer symbols on eFSR Sketch file.
- [ ] Update fields to use symbols from DS on eFSR Sketch file.

## Acceptance Criteria
- [ ] Issue is a collection of ideas and can remain as long as it is helpful for the team. 
- [ ] All symbols are from the DS on eFSR Sketch file.
---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by josephrlee** [comment]
@HeatherRienks, I ended up working on this today and yesterday for a bit, but I'm not quite sure how to document it. Maybe we can chat briefly on Monday?

**Comment by HeatherRienks** [comment]
@josephrlee - yes, let's chat!
