### ISSUE TITLE
Update VA-backed home loan funding fees for April 7

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#56232]
## Issue Description
Raleigh asked us to change the VA home loan funding fees, effective April 7. 

[https://app.zenhub.com/files/133843125/3e194e09-826e-4d45-b49d-4aef8aa496fa/download](https://app.zenhub.com/files/133843125/3e194e09-826e-4d45-b49d-4aef8aa496fa/download)

---
## Tasks
- [x] Update rates in Drupal (Laura)
- [x] Copyedit and prepub (Megan)
- [x] Publish on Friday morning (Laura)

## Acceptance Criteria
- [x] Rates are updated on page

**Comment by laurwill** [comment]
Hi @megzehn , 
I just updated some rates per Raleigh's request. Could you copyedit and prepub the VA home loan funding fee page? We'll hold to publish until Friday morning (I can do that since you'll be out). Thank you!

http://preview-prod.vfs.va.gov/preview?nodeId=748

**Comment by megzehn** [comment]
Thanks, @laurwill!

I copy edited this page and went through the prepub list, so it's ready to go on Friday. Thank you for publishing it!

Side note: I noticed the tables weren't captioned. I couldn't figure out a clean and easy way to add them, so I went ahead and opened a ticket for us to tackle that separately. It may take some reordering and rewriting.

**Comment by laurwill** [comment]
Thanks @megzehn! I published this. Moving to validate.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
