### ISSUE TITLE
[a11y Process Work] Create an a11y maturity model for teams

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#56240]
> [!IMPORTANT]
> `GITHUB PROJECT LOCATION` Per @eli-oat [on 11/15/2023:](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56240#issuecomment-1812999597) Notes for this work will be [recorded on GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/Deliverables/CAIA/maturity-modeling.md).

<hr>

## Issue Description
@artsymartha68 had the idea of creating an a11y maturity model for teams to identify:
- which teams are more or less in need of accessibility support
- what _kind_ of support teams may need
- who is currently supporting teams (e.g. specialists/champions)
- what pain points and strengths emerge as patterns for us to take strategic action on
- who to celebrate for their a11y success

A prototype of this by @coforma-terry and @joshkimux [exists in the a11y dashboard](https://docs.google.com/spreadsheets/d/1lgzMiZZ-0rBPDuB2gRupBAjsyF0WTe005VvEHYrMxww/edit?usp=sharing)

---
## Tasks
- [ ] Co-determine criteria to assess team a11y maturity
  - [ ] Ensure criteria considers team resources and staffing
  - [ ] Co-design criteria with a sample of product owners, product managers, a11y specialists, designers, and (if possible) disabled Veterans and the Section 508 office
    - [ ] If co-design is not possible, document it as a risk and future opportunity/need
- [ ] Operationalize criteria onto the a11y dashboard (or public equivalent)
  - [ ] Create and publish a plan on how to maintain the dashboard
  - [ ] Determine hours needed to operate and a responsible owner(s)
- [ ] Create a strategy to regularly publish/share team a11y maturity across VA.gov

## Acceptance Criteria
- [ ] Measurable, non-vanity metrics exist to assess team a11y maturity
  - [ ] Metrics are reviewed by specialists, product owners, and any other relevant stakeholders
- [ ] Team a11y maturity is easily visible in a public location (e.g. the a11y dashboard, platform website, etc)
- [ ] A maintenance plan exists and is feasible based on the resources available
- [ ] An explicit owner(s) exists for the maturity model
- [ ] A strategy to publish and share to teams
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sara-amanda** [comment]
@coforma-terry @eli-oat moving ticket to match pipeline in ZenHub and Projects.

**Comment by eli-oat** [comment]
@joshkimux and @sara-amanda is okay if I start to tackle this one? If ya'll are cozy with it I'm happy to own this.

**Comment by joshkimux** [comment]
@eli-oat WE'VE BEEN WAITING FOR YOU

Yes. Please. And let's chat to get you caught up on the work done so far.

**Comment by eli-oat** [comment]
@artsymartha68 I'm looking to validate a few assumptions, given this: 

> - which teams are more or less in need of accessibility support
> - what kind of support teams may need
> - who is currently supporting teams (e.g. specialists/champions)
> - what pain points and strengths emerge as patterns for us to take strategic action on
> - who to celebrate for their a11y success

is it safe to say that this work aims to produce a tool that helps to...

- prioritize what teams need support at what point in the design and development lifecycle (this could be within, or external from the Collab cycle) 
    - as an added benefit, provide teams with a roadmap on how to "level up" their internal accessibility practice

That 2nd point isn't clearly supported by the previous goals, but I know we've talked about it in the past. I think it can be an outgrowth of meeting the first goal.

**Comment by artsymartha68** [comment]
@eli-oat this looks great. I think that this tool also aims to show where we may need to request additional team members or contracts. Or, dare I say, even help us forecast where we are going to need more! I know we don't always get a heads-up for new projects spinning up, and even if we do, those teams don't always bring a11y specialists with them. Does this make sense?

**Comment by eli-oat** [comment]
Notes for this work are [recorded on GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/Deliverables/CAIA/maturity-modeling.md).

**Comment by sara-amanda** [comment]
## Next Steps
- @artsymartha68 how would you like to proceed with your ticket, based on the work that Eli has completed? 
- Note: We have it documented as an Eli follow-up item in ticket #83204, and it is currently open. 
- Moving to `Blocked` for now. Perhaps we can discuss in our next meeting with @NaomiPMC and team?

**Comment by artsymartha68** [comment]
This certainly feels Icebox-y.

**Comment by sara-amanda** [comment]
## Ticket Status 
🧊 Putting on ice for now, per a11y/OCTO call with @artsymartha68 and comment above. 

> This certainly feels Icebox-y.

cc: @NaomiPMC
