### ISSUE TITLE
Landing Page -  Prep for design intent

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#56269]
## Issue Description
The 526ez and ancillary paper forms get updated when necessary. This ticket is part of work required to get the digital 526ez form on va.gov sync with the paper version. The scope of this work is to prepare for design intent based on what we plan to research with veterans, including changes to make to /start wizard i.e. "Is this the form I need" https://www.va.gov/disability/file-disability-claim-form-21-526ez/start

---
## Tasks
- [x] Connect with other team/stakeholders about changes being made to wizard
- [x] Review research as it becomes available ([see ticket](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/56350))
- [x] Create design artifacts that outline proposed changes/what we hope to do research on (lo-fi mockups and/or user flow)
- [x] Initiate design intent with collab cycle

## Acceptance Criteria
- [x] Created design artifacts
- [x] Created design intent ticket

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
cc @lydiahooper @Nyanteea

**Comment by lydiahooper** [comment]
Sketch file with user flows and low-fi mockups: https://sketch.com/s/0fa92d93-0841-4c62-8112-c9c528204092
