### ISSUE TITLE
Intro pages - New design

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#56271]
## Issue Description
The 526ez and ancillary paper forms get updated when necessary. This ticket is part of work required to get the digital 526ez form on va.gov sync with the paper version. The scope of this work is to prepare for research with veterans. In scope are introduction, active duty and expected end date pages.

Sketch file with prototypes: https://sketch.com/s/0fa92d93-0841-4c62-8112-c9c528204092

---
## Tasks
- [x] Get feedback from design intent meeting
- [x] Create initial prototypes for three pages (desktop and mobile, so 6 screens) with revised content, using design system guidance and content (revised content based on content review, if possible) 

## Acceptance Criteria
- [x] Prototypes for three pages (desktop and mobile)
- [x] Create ticket for midpoint in collab cycle

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
Break this into design and content tickets

**Comment by lydiahooper** [comment]
Related content ticket: https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/57643
