### ISSUE TITLE
686c | Redesign SubmitForm686cJob and SubmitForm674Job so they can be run any time after being enqueued

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#56289]
## Value Statement
**_As a_** software developer
**_I want to_** re-design the SubmitForm686cJob and SubmitForm674Job so they can be run any time after being enqueued
**_So that_** they don't cause claims to fail.

---
## Background Context
These jobs (and others across VA.gov) are enqueued with a `user_uuid`. When the job finally runs, it attempts to fetch a `User` record with this `user_uuid`. The `User` record is a transient record that is destroyed from Redis when the veteran's session expires. As a result, one of these submission jobs will fail simply because a veteran logged out, or was logged out, before it had the opportunity to run. This happens all throughout the day, and there will be an increased risk of this happening once we set up retries. 

---
## Acceptance Criteria
- [ ] Automated tests still pass after re-design.
- [ ] No new errors thrown in prod after re-design.
 
## Tasks
- [ ] Review and update https://github.com/department-of-veterans-affairs/vets-api/pull/12460, _very carefully_
- [ ] Coordinate with platform team so that we can roll back changes if anything goes wrong
- [ ] Monitor Sentry closely on day of deploy

## Definition of Ready 
- [x] Implementation plan is approved by BGS and VBA (Trevor from Identity Team proposed implementation plan; Don't need BGS approval on this matter because these specific changes don't affect them).
- [x] Dependencies assumption and blockers are listed (There are none)
- [x] If code work is added to this ticket it is written into AC

## Definition of Done
- [x] VBA and BGS give sign-off on implementation success (Trevor from Identity Team proposed implementation plan; Don't need BGS approval on this matter because these specific changes don't affect them)
- [ ] Reviewed and approved by product
