### ISSUE TITLE
686c | Make SubmitForm686cJob and SubmitForm674Job retryable.

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#56290]
## Issue Description

Once https://github.com/department-of-veterans-affairs/va.gov-team/issues/56285 and https://github.com/department-of-veterans-affairs/va.gov-team/issues/56289 are complete, we will be able to retry these two jobs without worry. 

A max-retry count of 14 would wait for a total of just over 24 hours. See https://github.com/sidekiq/sidekiq/wiki/Error-Handling#automatic-job-retry. The longest period of downtime in the past 90 days was about 7 hours, so 24 hours should be more than sufficient.

Related (old) issue: #30784

---
## Tasks
- [ ] Decide on a max retries count.
- [ ] Set up an exponential backoff (Pretty sure Sidekiq does this out of the box).
- [ ] Decide what kind of failures warrant a retry and what kinds don't.
- [ ] Decide what should happen when a job fails for good.
- [ ] Set up appropriate logging and monitoring.

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
