### ISSUE TITLE
Design | 686 | Action Needed Email

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#56291]
## Issue Description
_When a VA.gov claim fails to submit, VA.gov needs to email the Veteran letting them know they need to take additional action._

- Design guidance [here](https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status).
- [More info](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Design/patterns/Application%20status/readme.md)

---
## Tasks
- [ ] Customize failure email text with form details
- [ ] Create failure email template in VA Notify

## Acceptance Criteria
- [ ] Failure email has been created in VA Notify
---

**Comment by tblackwe** [comment]
@steele-lm @zack this is the User Experience ticket I mentioned on our calls today

**Comment by tblackwe** [comment]
@data-doge could you speak more to why we might want to change this behavior?

**Comment by steele-lm** [comment]
@tblackwe @ajialeilani @juliepedtke I repurposed this ticket from Eugene into a design ticket, so we can confirm the email language. I'll create two additional tickets: 1 to update the logic now to prevent false failure notifications and a second to update the email text.

**Comment by steele-lm** [comment]
OCTO is currently working on a failure email template that all benefit forms will leverage.

**Comment by steele-lm** [comment]
See proposed copy [here](https://docs.google.com/spreadsheets/d/14yQM0ABbrF9LK_7yIzhThK1eiS9MFe946aZxMWH3ezU/edit?usp=sharing).

**Comment by ajialeilani** [comment]
@steele-lm the link sends me to our sprint goal progress tracker. Is that intended?

**Comment by steele-lm** [comment]
@ajialeilani Gah! No! I updated the comment with the correct copy link and some documentation about the notification emails as a whole.
