### ISSUE TITLE
[Engineering]10-10EZ - Unit tests: Determine opportunities for additional unit tests

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#56293]
## Background
We need to review our code in Vets-website repo to increase our Unit Tests to meet/exceed the 75% coverage guidance (currently at 68-70%).  We need to find out where we are short/missing unit tests

- [Vets-website](https://github.com/department-of-veterans-affairs/vets-website)

## Tasks
- [x] Familiarize with current unit tests in the repo
- [x] Review code for additional tests that could be implemented
- [x] Implement and run the new tests (if any) to analyze results for accuracy

## Acceptance Criteria
- Review is complete on determining opportunities for additional unit tests and, if any are found, the tests have been implemented and run with accurate and expedited results

**Comment by hdjustice** [comment]
moving to Icebox, return to this another time

**Comment by longmd** [comment]
Closing as implementation is being handled with #60897.
