### ISSUE TITLE
[CONTENT] Update content of "ALTOONA, PA" History page with local system/facility information and link to va.gov/history/ [CONTENT]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#5629]
## User Story or Problem Statement
As a Veteran Web user, I need a plain language and descriptive HISTORY page, so that I better understand the history of my local Medical Center.

## Goal
_Efficient and clear content describing local Jobs and Careers Page?_

## Objectives or Key Results this is meant to further
- _Reduced word count and improved plain language._

## Resources - Tools - Documentation
[Home/Splash Page](https://www.altoona.va.gov/)
[Pittsburgh new HOME Page](https://va.gov/pittsburgh-health-care/)
[Pittsburgh new HISTORY page](https://www.va.gov/pittsburgh-health-care/history/)

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [x] Completed Content is written in Word Document format (Template provided above) and is saved 
referencing Medical Facility Name, Page name, and writer's initials (i.e. "System"-History-lw) 
- [x] Page must be saved in Content folder on Google Drive.
_Content can be derived from legacy web pages, Stories, or google historical information.

-Includes the following sections in the content
- [x] Local Historical information and theme
- [x] Link to va.gov/history page for global history of VA

## Acceptance Criteria
* Completed Content is written in Word Document format and is saved referencing Facility Name, Page Name, and writer's initials.
* Page must be saved in Content folder on Google Drive under Page reference name
