### ISSUE TITLE
UX | Profile | Logged-in IA and Nav research | Start research synthesis

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#56304]
## Background

Now that research is complete, let's synthesize data!

## Tasks
- [x] Transcribe recordings and drop notes in research folder
- [x] Mural board affinity mapping
- [x] Draft findings report

## Acceptance Criteria
- [x] Initial draft is ready for peer review
