### ISSUE TITLE
UX | Profile | Logged-in IA and Nav Research | Topline summary

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#56303]
## Background

Create a topline summary immediately following research sessions and get input from observers.

## Tasks
- [x] Complete topline summary
- [x] Gather feedback from observers
  

## Acceptance Criteria
- [x] Feedback received on topline summary, and synthesis can begin

**Comment by andaleliz** [comment]
[Solicited feedback from team in Slack](https://dsva.slack.com/archives/C909ZG2BB/p1680656281173099?thread_ts=1679415217.390619&cid=C909ZG2BB); aiming to close this out by Thursday.

**Comment by allisonlu** [comment]
no comments! it was great sitting in on these, thank you

**Comment by Samara-Strauss** [comment]
Just noting that we talked about this in our weekly check-in today. Great job and great notes. This research was so helpful.

One thing I didn't get to mention in our discussion:

> No one expressed frustration or confusion by encountering content that wasn’t personalized to them, though some did get frustrated when they didn’t find personalized content where they expected it. They commented that it would be nice to have a link to personalized content, or that the link “should” be there.

I'm interested in this particular piece of things, as I think there could be potential paths forward in terms of improvement. Any notes we can capture on what people expect to be more personalized or comments around this could be helpful, especially if we ever wanted to collaborate with the sitewide team on improvements to content in a logged-in state.

Otherwise, I think you captured all of our feedback during our call. I know I won't be here in an official capacity when the research synthesis comes out, but I might sneak online to read it anyway :) Great work all around!

**Comment by cindymerrill** [comment]
I know this is only a topline summary and not the final report, but I read it carefully and have some detailed feedback for you below...

Re "When asked to find content without using links on the homepage or My VA, about half of the participants used the mega menu, and the other half used search", I was bothered by how you posed the question during the session (too late, I know). After someone finds a direct link, it seems strange to ask them what they'd do if that link weren't there because you're giving them an unrealistic scenario. They already found the link, so why ask them to look for it another way? I'd instead observe to see what they do when they actually CAN'T find something you've asked them to do, such as dependent information. I'm concerned that what you observed after giving that prompt may not be their actual searching/browsing behavior. Also, I believe you used the word "search" in your prompt, which could have biased the participants toward looking for somewhere for the word "search" on the page. 

Re "Participants struggled to find dependent information, which wasn’t linked from the homepage, My VA, or the mega menu links", this is an ongoing problem in my studies. I'd like to summarize your findings on this and add them to [this insight in the Research Repo](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/198). I saw P9 go to the _Service member benefits hub_ and then to the _Family member benefits hub._ It might be helpful to detail in your research report all the different places where participants looked. Data like this could help demonstrate to the Content & IA team that there's an issue.

Was it the same participant who assumed that the word "your" indicated personalization in both of these points? If so, you should say that explicitly.
- **One participant** stated they the menus were personalized because they used the word “your” in the links.
- Most did not differentiate or comment on the homepage content being personalized or not. **One participant** referred to the homepage as a “dashboard” and felt it was personalized because it used the word “your”.

I also noticed a couple typos: 

1. Delete "a" in "Participants understood that content available via the navigation menus was for all Veterans or potential VA beneficiaries. Most felt it was appropriate to have that content, and that it should be **a** accessible even though they were logged in."
2. Missing verb in the sentence "One participant stated **they the** menus were personalized because they used the word “your” in the links."

I hope that all of this feedback is helpful, though it's probably more than you were looking for.

**Comment by andaleliz** [comment]
Hi @cindymerrill, this is very helpful! Thank you for taking the time to review and share these thoughts. 

For the first item, you're right in that it is too late. I appreciate the feedback anyway! My thoughts on how to address this are:
- Pay attention to differences in wayfinding behavior for tasks when I asked them to imagine it wasn't there, vs when it _actually_ wasn't there
- call out in the report that for some participants the word "search" was used in the prompt (I can revisit to confirm the exact number) so they may have been biased.
- consider this feedback for future prompts 

Do you have any other suggestions about how to address this as I synthesize and write the research report?

Items 2-5 are clear to me as far as a way forward. Thanks again!

**Comment by Samara-Strauss** [comment]
> After someone finds a direct link, it seems strange to ask them what they'd do if that link weren't there because you're giving them an unrealistic scenario. They already found the link, so why ask them to look for it another way? I'd instead observe to see what they do when they actually CAN'T find something you've asked them to do, such as dependent information. I'm concerned that what you observed after giving that prompt may not be their actual searching/browsing behavior. 

To clarify, Liz asked the question this way because I asked her to. We already know how reliant people are on the homepage and My VA links to find tools, and that's not all bad. If someone finds something easily, great! That's the goal. But we also had open questions about whether people can find information without those two pages, and it turns out people actually found things quite easily in the navigation! I'm really glad we have this insight, even if the research scenario wasn't entirely organic. This insight is super important in guiding us in what *not* to do as we go forward.

**Comment by cindymerrill** [comment]
@andaleliz I'd be explicit in the research report about what you asked participants to do including the wording you used (including "search"), and that you were asking people to try looking for a second way to find the desired information (and maybe also why you did this, per Samara's comment). I would acknowledge that this wasn't a natural task for participants (find a second way to do this task after you've already found one way), and also that the wording of the prompt wasn't ideal because it may have biased the participants toward looking for a Search tool.

You could certainly "Pay attention to differences in wayfinding behavior for tasks when I asked them to imagine it wasn't there, vs when it actually wasn't there", but once you've used the prompt to "search" once, that may still be in participants' minds during subsequent tasks. So I might be skeptical about any conclusions you might draw from this.
