### ISSUE TITLE
Decision Reviews | Performance analytics

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#56311]
## Value Statement
**_As a_** product team
**_I want to_** refine our performance metrics and establish analytics for decision reviews 
**_So that_** we can measure the impact of our work,

---
## Background Context
This is a tracking ticket for various tasks to establish analytics for decision reviews.

## Acceptance Criteria
- [ ] We have access to quant and qual data that helps us establish baseline key performance indicators
- [ ] We have dashboard for all decision reviews

## Tasks
- [x] Contact Center Request https://github.com/department-of-veterans-affairs/va.gov-team/issues/57228
- [x] DOMO Request https://github.com/department-of-veterans-affairs/va.gov-team/issues/55818
- [x] DOMO Request https://github.com/department-of-veterans-affairs/va.gov-team/issues/55417
- [x] Medallia Request https://github.com/department-of-veterans-affairs/va.gov-team/issues/56154
- [x] Medallia Request https://github.com/department-of-veterans-affairs/va.gov-team/issues/56435
- [x] Investigate making a GA dashboard for decision reviews
- [x] checking with Alejandro on BVA dashboard

**Comment by saderagsdale** [comment]
Requested an ETA from Michelle Dooley

**Comment by saderagsdale** [comment]
Alejandro noted that the BVA dashboard is delayed until mid-June

**Comment by saderagsdale** [comment]
Kimberley Daniels can provide info on Contact Center data @eileen-coforma

**Comment by eileen-coforma** [comment]
Got data from Ian from Contact Center. Waiting on Michelle to fix one last section of the NoD dashboard to close the DOMO ticket.
