### ISSUE TITLE
Supplemental Claim | Release communications

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#56312]
## Background Context
The VA has services available to socialize the release, internally and externally. 

## Acceptance Criteria
- [ ] VA has info they need to tell a story about the product to internal and Veteran audiences
- [ ] We have communications scheduled internally
- [ ] We have communications scheduled externally

## Tasks
- [ ] Check with Matt on internal communication tasks
- [ ] Send Michelle documentation for supp claims
- [ ] _Add tasks here as needed_

**Comment by saderagsdale** [comment]
Alejandro is waiting for approval send the info to the comms team.
