### ISSUE TITLE
[Research] 10-10EZ - Progression Stepper improvement

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#56319]
## Background
The progression stepper within the application has been reported as misleading, confusing, and not very useful in showing where the Veteran is in the application.  We have also received feedback from IA regarding this in ticket #55327.

We need to do some discovery on the best way to use the progression stepper, potentially add a sub-stepper (as mentioned in this [discovery work](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/Household%20info%20design%20discovery.pdf)) or discover another alternative in letting Veterans know where they are in the application and how much more they have to go.

### Resources

[Some interesting options from USWDS](https://designsystem.digital.gov/components/step-indicator/
) (Per Katelyn: I like how they call out the different steps by name and emphasize which you’re on)

[Related Accessibility Bug](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1538)

[Related Progress Bar Design](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1333)

[Experimental Design: Simple Form Header](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1326)

[Experimental Design Simplified VA Header and Footer](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1339)

[New Forms library](https://github.com/department-of-veterans-affairs/va-forms-system-core)

Veterans Facing Forms team: Simplified Form Header
[Research](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/research/2023-03-formheader/research-plan.md) 
[Designs/ Wireframes](https://www.sketch.com/s/9f215f8f-ba86-4b99-813f-d0ca3c03ca18) 

## Tasks
- [x] Review other related tickets to observe design explorations
- [x] Consider other possible alternatives that may not have been explored
- [x] Share with the team

## Acceptance Criteria
- Gather alternative opportunities that may be used for both 10-10 forms and possibly as a new Design Component, and share with the team

**Comment by jessicastump** [comment]
Flagging the [USWDS progress stepper](https://designsystem.digital.gov/components/step-indicator/) here for reference.

**Comment by jessicastump** [comment]
@IMHieuVo and @hdjustice - the ticket I was remembering/mentioned in DSU :) Not sure if we need to add the needs-grooming tag to it and chat at next meeting?

**Comment by IMHieuVo** [comment]
I've created a [mural](https://app.mural.co/invitation/mural/departmentofveteransaffairs9999/1686606287030?sender=ubf5503bf47b6eb1e92730053&key=ffcefb0f-8601-429c-a0b7-a8a0043998be) for this information.

**Comment by hdjustice** [comment]
This story can be closed - #60545 created for next steps
