### ISSUE TITLE
IA & Content from Veteran Facing Forms Digitize -21-0966

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#56313]
## What does your team need support for? Check all that apply.
- [x] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [ ] Making revisions to one or more existing VA.gov pages
- [ ] Something else 
 
 *Give a brief description of what your team needs support with.*

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [x] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: [Product Outline](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-0966/Product%20Outline.md), [Source of Truth](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-0966/sourceoftruth.md)
- Link to or attach user flows: [Mural User flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1689261093555/6c03d0c5d9d3f5ee875295e6ee444c3420f9ad3b?sender=ud94436ff2bf5d5ce166a5253)   
- Link to prototype or mockups: [Sketch files](https://sketch.com/s/54db90a2-2431-433c-9806-831efe54087f)
- Link to any epics/issues that may be helpful: 
  - [21-0966 Epic](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/172)
  - [IA Question/Answers](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-0966/ia-sitewide.md)

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date:
- Estimated staging review date:
- Content, Accessibility, and IA work needed by: 

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [x] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Veteran Facing Forms
-	OCTO-DE product owner: @humancompanion-usds 
-	Product manager: @tbaker1026 
-	Designer:  @jeana-adhoc 
-	FE engineer: 
-	Product/team Slack channel: #veteran-facing-forms

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/58265
```

**Comment by jeana-adhoc** [comment]
I've added our [IA question/answers](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-0966/ia-sitewide.md) to the description above

**Comment by tbaker1026** [comment]
@RLHecht any updates on content on introduction and confirmation pages?

**Comment by RLHecht** [comment]
@tbaker1026 I thought we were waiting on IA to determine what to do about a landing page for whether that content was going to go there or in the form itself. I can check on this again.

**Comment by tbaker1026** [comment]
[@jennymayoco](https://github.com/jennymayoco) since we have the supplemental page get out can you provide the URL and breadcrumbs?  [https://www.va.gov/supporting-forms-for-claims/](https://www.va.gov/supporting-forms-for-claims/)

**Comment by jennymayoco** [comment]
Hi @tbaker1026! Here is the [finalized IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/form-digitization-21-0966.md) - let me know if you have any questions.

**Comment by jennymayoco** [comment]
Hi @tbaker1026 @jeana-adhoc @megzehn, I had posted this update in the wrong intake ticket 😅 sorry for any confusion! As I mentioned during content hours earlier, I've updated the [IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/form-digitization-21-0966.md) with a couple of new entry points, the [R&S Intent to File page ](https://www.va.gov/resources/your-intent-to-file-a-va-claim/)and the [Pension form how to apply page](https://www.va.gov/pension/how-to-apply/). The Pension form is currently down and so the placement of 21-0966 might change once 21P-527EZ is relaunched. We recommend working with Katherine Fung at CAIA to coordinate placement.

**Comment by jennymayoco** [comment]
Hi @strelichl! IA work is done for this form. I think what's next is adding the two additional entry points shared above cc @megzehn for visibility

**Comment by AdamOye** [comment]
@AdamOye to follow up with Jenny on closing ticket.

**Comment by AdamOye** [comment]
@jennymayoco Hey Jenny can this ticket be closed now that 0966 is in prod. ?

**Comment by jennymayoco** [comment]
hi @AdamOye ! The IA work is done for this but I think there might still be content work for the last entry point so looping in @megzehn for any updates on this or other content work

**Comment by megzehn** [comment]
Hi! We implemented the 2 entry points, so we can officially close this! Yay!

**Comment by megzehn** [comment]
@AdamOye I'll let you close it in case you have your own tracking system!

**Comment by AdamOye** [comment]
Sounds like a plan. Closed.
