### ISSUE TITLE
[FE] My VA audit: Update url for "Check your Post-9/11 GI Bill benefits"

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#56336]
## Background
In UAT we found that the "Check your Post-9/11 GI Bill benefits" links to the content page for Post-9/11 GI bill benefits and we need it to deep link directly into the tool. We need to update the url on that link in the Education and Training section.

## Tasks
- [ ] Update the URL on the "Check your Post-9/11 GI Bill benefits" to link to `https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit/status` (instead of `https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit/`)
- [ ] Confirm GA tracking is still in place and functioning properly
- [ ] Test
- [ ] Move to validate

## Acceptance Criteria
- [ ] "Check your Post-9/11 GI Bill benefits" links to `https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit/status`

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ Log in with any LOA3 staging user, confirm "Check your Post-9/11 GI Bill benefits" links to `https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit/status` (note that staging users will not have access to this page and will likely see a system error message, but in production Veterans will be able to see it)

**Comment by allisonlu** [comment]
This link also appears in the main mega-menu – are we responsible for this update?

![Screenshot 2023-04-07 at 4 12 55 PM](https://user-images.githubusercontent.com/8542413/230672886-7aed0a7d-ed31-410e-be32-5741ec1352c3.png)

**Comment by ajakabcin** [comment]
@allisonlu  sorry I didn't catch this - no we're not responsible for that!

**Comment by allisonlu** [comment]
lookin good on Cecil's account!

![Screenshot 2023-04-10 at 3 05 13 PM](https://user-images.githubusercontent.com/8542413/230975459-fcbfc702-af16-4dc1-a389-8c5a2ad3d952.png)

**Comment by ajakabcin** [comment]
Confirmed on Judy's as well! and still seeing the GA tag - thanks @allisonlu !
