### ISSUE TITLE
[technical discovery] 686c | Resolve SubmitForm686cJob and SubmitForm674Job BGS rollback errors

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#56333]
## Issue Description

Looking back at the past 90 days it looks like we've always gotten these errors. Interestingly, there are peaks of these errors on January 13, February 26, and March 26. Additionally, after March 22nd (which was the date of the 686c/674 race condition bugfix https://github.com/department-of-veterans-affairs/vets-api/pull/12186), the number of SubmitForm674Job errors have increased significantly.

![image](https://user-images.githubusercontent.com/7520103/230486690-f5a6caab-1384-4b48-919b-c96b2d392413.png)

Since March 22nd (and not counting the peak on March 26), we have been getting about 97 of these errors per day (677 / week; 3,000 / month). It seems like around 80% of these are SubmitForm674Job errors. It is likely that many of the errors in the above screenshot are duplicates of another. My instinct is that the `raise_backend_exception` errors represent the true number of failed claims. I have yet to validate that instinct though.

Interestingly these jobs are failing when a request to a "create_person" BGS endpoint fails with a "The transaction has been rolled back" error. 

The goal of this ticket is to investigate the cause of this error and resolve it. I cannot place an estimate on this ticket until I've determined the cause.

---
## Tasks
- [ ] Investigate bug and resolve it.

## Acceptance Criteria
- [ ] No more of these errors in Sentry.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
Will write a separate ticket for code work.

**Comment by data-doge** [comment]
Update: it looks like this error occurs when the file number and ssn we send to BGS's create_person endpoint are different. 

![image](https://user-images.githubusercontent.com/7520103/230666027-5077c256-270f-4aad-b74c-f355d7fd8942.png)

**Comment by data-doge** [comment]
After setting up logging in https://github.com/department-of-veterans-affairs/vets-api/pull/12379, I have seen [one case](http://sentry.vfs.va.gov/organizations/vsp/discover/platform-api:71787efe86624af68f1ec43869eb99f1/?end=2023-04-11T18%3A50%3A00.000&field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&query=job%3ABGS%3A%3ASubmitForm674Job+level%3Aerror+%21message%3A%22%2ATMS%2A%22+%21message%3A%22%2ASavon%2A%22&sort=-timestamp&start=2023-04-11T16%3A58%3A02.000&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1) so far where we've sent an invalid SSN (eight instead of nine digits) to BGS. But there are still many instances where the SSN is neither invalid nor nil.

**Comment by data-doge** [comment]
Since deploying the logging mentioned above, we've observed 37 instances where the SSN has been eight instead of nine digits.

**Comment by data-doge** [comment]
Some information on File #s and SSNs: https://design.va.gov/patterns/ask-users-for/social-security-number

**Comment by data-doge** [comment]
The eight-digit SSNs we're sending to BGS are actually a string of eight asterisks (i.e. "********"). I learned this by looking at a 686c (and not a 674) rollback error and seeing that the file number and ssn (and not just the file number) were _both_ unredacted in the error message. [[Link](https://vagov.ddog-gov.com/logs?query=%40named_tags.jid%3A6af70b8d021d92c513906cd9&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1680292974815&to_ts=1680897774815&live=true)]. Another interesting finding: we are only sending asterisks to BGS in the `SubmitForm674Job` (and not the `SubmitForm686cJob` that runs prior). Two issues here:
- Why do we send a valid ssn in the 686c job, but send asterisks in the 674 job?
- Neither the SSN or file number should be returned in BGS's error response body / we shouldn't be logging it.

**Comment by saderagsdale** [comment]
@data-doge should we ask Corey and Linda about this in the teams chat?

**Comment by data-doge** [comment]
@saderagsdale I can reach out to Linda about the PII concern, today.  Matt B. is looking into the redacted SSN issue. 

Also, pasting update I made to VA folks here:

> Hey all, I've got an update!

> Over the past week, I've been looking into the next biggest source of null claims. I'm calling this bug the "ssn / file number mismatch bug."  There are actually two variants of this bug. The first, I'll call the "redacted ssn variant."  The second, I'll call the "true mismatch variant."  The "redacted ssn variant" accounts for most of these null claims -- roughly 45 per day.  The "true mismatch variant" accounts for roughly 12 null claims per day. These null claims are null Form 674 claims.

Today, I deployed a short-term fix for the "redacted ssn variant," and I am monitoring to see whether it's working as intended.  So far, it appears to be working.

> The "redacted ssn variant" is another interesting bug. I'll provide more detail on it, in case you're interested. When we enqueue the 686 Submit Job, we pass it several arguments, including the User's ssn. The 686 Submit Job sends this ssn along with certain requests to BGS, without issue. Before the 686 Submit Job completes, it may enqueue a 674 Submit Job, and when it does so, the 686 Submit Job passes along the same SSN that it received when it was enqueued. This is where things get interesting. By the time the 674 Submit Job first attempts to send this ssn to BGS, the ssn has been transformed from a nine-digit number, to the following string: ********. Literally, ********. It's unclear where this transformation occurs. As expected, BGS returns an error stating that this ssn doesn't match the veteran's file number, and we are unable to submit Form 674 to BGS. Put another way, we end up with a null Form 674 claim.

> My short-term fix simply "refreshes" the User's ssn before we send it to BGS. Again, so far, it appears to be working. I am currently looking into a long-term fix that addresses the fact that these ssns, for no apparent reason, transform into a series of asterisks. It's a bad code smell that raises the specter of a broader issue.

> I am also looking into the "true mismatch variant." For context, these are cases where we send a 9-digit ssn to BGS that does not match the veteran's file number. BGS requires the two to match. I took a quick look at one of these instances, and saw that the ssn and file number differed by only one digit, suggesting an input error. I'll continue looking into this, and will provide an update when I have one.

---

> The redacted ssn bug is indeed squashed. Note the reduction in errors past April 15. 

![image](https://user-images.githubusercontent.com/7520103/232545782-84badac5-4a2c-43f2-93b2-ce1a836e49c8.png)

And here's that short term fix: https://github.com/department-of-veterans-affairs/vets-api/pull/12410

**Comment by data-doge** [comment]
@saderagsdale I'm closing this ticket in favor of #56993 (important work, but not highest priority; can probably be done after retroactive remediation) and #56995 (the next biggest source of null claims; I'm going to start this now).
