### ISSUE TITLE
Migrate call to Common API services from eVSS to lighthouse -526ez

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#56342]
## Issue Description
Form 526 currently calls Common API on eVSS. This call needs to be migrated to Lighthouse as part of overall eVSS migration to Lighthouse.

## Need To Know

---
## Tasks
- [ ] Technical discovery to understand where the change needs to be made and how it will be tested
- [ ] Update call to LH endpoint
- [ ] Create QA test plan
- [ ] Integrate Testrail if not already integrated?
- [ ] Send executed test scripts to the QA team

## Acceptance Criteria
- [ ] The call to endpoint is migrated to the Lighthouse API
- [ ] functionality does not change (need to understand what part of the submission uses this API and how it functions today)
- [ ] QA completed successfully and artifacts submitted to the QA team (Do we need to integrate with Testrail first?)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
The findings from the discovery ticket [Tech Discovery - Common API Migration#12052](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/vets-api/12052) showed that no migration work is required for 526ez flow for common services API.
