### ISSUE TITLE
Design changes for making 526 current for existing sections

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#56348]
## Issue Description
The 526ez and ancillary paper forms get updated when necessary. This ticket is part of work required to get the digital 526ez form on va.gov in sync with the paper version.

This ticket includes content and design work needed for engineering to make changes that do not require user research first:
1. Make phone number field on contact information optional
2. Change user flow: 
- Move homeless and terminal illness to vet details chapter
- Remove additional benefits flow/screens from disabilities chapter, except for Individual Employability screens which needs to move to additional info section
- Remove FDC program screen from evidence chapter
- Remove bank account info screens from additional chapter

---
## Tasks
- [x] Create annotated screenshots for revised contact information page 
- [x] Create userflows showing where pages need to be moved from and to 
- [x] Initiate design intent meeting with VA Platform

## Acceptance Criteria
- [x] Annotated screenshots for contact information 
- [x] Userflows showing changes 
- [x] Create tickets for implementation, including for collab cycle

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lydiahooper** [comment]
Sketch file for user flow: https://sketch.com/s/c3ee9ba8-f268-46dc-a870-194e99bed37e

Screenshot: ![Annotated contact info page.png](https://images.zenhubusercontent.com/63dd30c43859c04de31f7608/76d3eed6-bc1b-4ed8-a713-6b6a5d330f7a)

**Comment by christinec-fftc** [comment]
Created #56920 to implement these changes. We won't need to make any back end or API changes for this. Also, seems like many of these will be config changes for RJSF and then updating unit or e2e tests, so seems ok to bundle into one ticket.

**Comment by lydiahooper** [comment]
Annotated screenshot for c![Screen Shot 2023-04-18 at 12.00.59 PM.png](https://images.zenhubusercontent.com/63dd30c43859c04de31f7608/791c1b4d-28ca-46c4-9ac9-1e757ff6e1d6)hanges for https://www.va.gov/disability/file-disability-claim-form-21-526ez/how-claim-exams-work

**Comment by lydiahooper** [comment]
@christinec-fftc this spreadsheet has the URLs, let me know if you need further help with this
https://docs.google.com/spreadsheets/d/14g3VW9uvMwrn88uk_PfApmgsvugXu6AyHR5N9Y0EYY0/edit#gid=0
