### ISSUE TITLE
Review of existing content research

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#56350]
## Issue Description
We need to understand what guidelines and practices have been put in place when it comes to creating and structuring content especially for dense forms like the 526. This will provide guidance as we approach the new form pages and the landing page redesign. We will speak to Randi Hecht - content lead about previous research she's conducted or collected and review Slack/Research Github Repository for content related insights. 

---
## Tasks
- [ ] Find existing content research in Git Repository 
- [ ] Talk to Randi  
- [ ] Find existing content research in Slack (sitewide-content-ia channel)

## Acceptance Criteria
- [ ] List of links to reports in github
- [ ] White paper 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lydiahooper** [comment]
@Nyanteea For example research on content related to PACT Act/toxic exposure, service connection, evidence, disability vs. condition, intent to file, and hidden text (known as Additional Information in VA design system)

**Comment by Nyanteea** [comment]
Running list of research reports with content insights:

1.  [Supplemental Claims Form Research ](https://dsva.slack.com/archives/C0NGDDXME/p1680543412371049?thread_ts=1680526803.975979&cid=C0NGDDXME)
2. [PACT act discovery research ](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/136)

**Comment by Nyanteea** [comment]
[Complete list of all research repository labels for sorting](https://github.com/department-of-veterans-affairs/va.gov-research-repository/labels?page=1&sort=name-asc)

**Comment by Nyanteea** [comment]
Relevant Content Request Tickets:

1. [Compose and build landing page - for 10950B form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/38448)

**Comment by lydiahooper** [comment]
Linking survey research here too: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/SurveyFeedback_Intro.md
