### ISSUE TITLE
Tech Discovery - 526 submit workflow 

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#56361]
## Issue Description
Form 526 currently calls EVSS /submit endpoint for submitting claims via vets-api. This call needs to be migrated to Lighthouse as part of overall eVSS migration to Lighthouse.
endpoint /submit is currently being developed. This issue is to discover 
 - are there any other eVSS services being consumed within 526 flow.
      What evss service calls from ancillary jobs when the 526 form is submitted need to be extracted? 
     Is the framework sufficient for this?

## Need to know
The endpoint is in progress and the schema will be available mid-April.

## Links

[overview](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/evss-to-lighthouse-migration/overview.md)

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [x] Identify all remaining eVSS service calls, other than those identified
- [x] If found, create tickets for discovery/migration

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

## Notes from Discovery
![Discovery Notes.png](https://images.zenhubusercontent.com/642494d169d76bbcaeb6679d/3154bfa0-baef-47be-a094-37e85c4c977a)

## Outcomes
- [x] Ticket for Rated Disabilities #57215
- [x] Ticket for migrating EVSS Document Service #57231
- [x] Ticket for migrating EVSS Benefits Claims Service #57265

**Comment by sethdarragile6** [comment]
[Submit endpoint discovery mobbing notes](https://dsva.slack.com/archives/C04U3EDUR3M/p1682015476845939) from Mark
