### ISSUE TITLE
Updates to the My HealtheVet premium account page to reflect they're paperless

### ISSUE THREAD

**Issue by aliyahblackmore** [department-of-veterans-affairs/va.gov-team#56369]
## Issue Description
We need to make updates to the [Get a Premium My HealtheVet account page](https://www.va.gov/resources/get-a-premium-my-healthevet-account/) to reflect that My HealtheVet has gone paperless.

Currently, this page still has information about submitting (paper) Form 10-5345a in person - this needs to be removed and replaced with new content available on this page about how to get a premium account in person:

https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/upgrading-your-my-healthevet-account-through-in-person-or-online-authentication

---
## Tasks
- [x] Assess "Get Premium My HealtheVet" page and remove mention of bringing Form 10-5345a in person (Aliyah)
- [x] Edit content (Laura)
- [x] Review content (Laura)
- [x] Copy edit (Megan)
- [x] Publish (Megan)
- [x] Share with partner for awareness (Danielle)

## Acceptance Criteria
- [x] Changes shared with partner for awareness

**Comment by aliyahblackmore** [comment]
Hi Laura - draft of this content is ready for you in this word doc. As mentioned, there aer


**These are a few global notes/questions:**

1. Do we want to make any other adjustments on this page? Page intro uses “Read below” and I think we’d want to remove “easy to use.” And the online section uses “above,” “click,” and “sign up.”  I would suggest we adjust mentions of "sign up" to "get" throughout the page, if possible. 
2. The page intro mentions that this page is about upgrading to a Premium MHV account – the first question in the first H1 includes info about signing up for an account on MHV, but do we need to direct people to create a “basic” MHV account and then upgrade or should we only include the step to upgrade – so making the first step “Sign in…” and the second step “Upgrade…” I think we’d want the instruction to be more aligned with the current page intro.
3. Initially considered nestling the Online and In person options (as H3s) under a new H2, but we’d want to have at least two questions on this Q&A, yes?
4. Is a VHIC considered a government-issued photo ID?
5. Tried out two options here – one is the with a list and the other takes the instructions out of the list. 
6. There are questions called out regarding the requirements to go in person (enrollment in VA health care vs. getting care at a VA health facility), the types of ID, any steps before going in person, and what happens once eligibility is determined.  **Laura** – I called these out in comments and if there are any other questions you have, we can bring them to Danielle/SMEs!

**Comment by laurwill** [comment]
Thanks so much @aliyahblackmore !
Before we make any more updates here, let's confirm with Ngozi (or others if needed) these items:
- For the online option, are steps 1 and 2 a sequential process? It says if you have ID.me or DS Logon you can skip to Step 2. But Step 2 assumes you do have one of those account types. So we need to confirm if there's a way to get a Premium MHV account online **without** another type of verified account.
- Do we need to add Login.gov here? Page doesn't currently mention it.
- Are VHICs and licenses the only types of ID you can use?
- Do we need to specify other steps to take before arriving in person, or where they need to go at their facility? 

Since we have a sync with Ngozi tomorrow, I can ask these questions (I think you'll be OOO). Then we'll see if we have enough info to update the page. Thank you!

**Comment by laurwill** [comment]
Update: Ngozi let us know that the live page provided as the source at top of this ticket is not the most recent version — she will send updated materials for us to work from.

She also confirmed that the online option is outdated, in addition to the outdated form info in the in-person option. So we'll update both sections as part of this work.

**Comment by laurwill** [comment]
Another update! VA partner asked if we could remove the paper form info right away as it's causing confusion. 

I went ahead and updated the Drupal node to remove the form and add a note about secondary ID from the source they provided. 

@megzehn this is ready for copyedit of just the updates and publishing — we'll be making more changes soon. It's node 8507. Thank you!

**Comment by megzehn** [comment]
Thanks @laurwill! Confirming I reviewed and published those initial changes.

**Comment by laurwill** [comment]
@RLHecht , this initial change is live — we can close this and I'll open a new ticket for additional changes.

**Comment by RLHecht** [comment]
Thanks, Laura. Closing this!
