### ISSUE TITLE
[PM] Profile | Notification Preferences | Updates to default send functionality: Submit collab cycle request

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-team#56397]
## Background
To begin development of the updates to notification preferences to add email as a channel (default send functionality and design updates), we'll need to submit the collaboration cycle request. Information about the collaboration cycle and kick-off process can be found at [VA Platform: Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/collaboration-cycle-kickoff).

## Tasks
- [x] Gather materials for kick-off - write [project outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/default-send/README.md)
- [x] Submit [kick-off ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-review%2Ccollaboration-cycle%2CCC-Request&template=collaboration-cycle-request.yml&title=Collaboration+Cycle+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D)
- [ ] Perform any follow-up items from kick-off

## Acceptance Criteria
- Kick-off is submitted and completed #57409 

## Resources
- Notification preferences [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/notification-preferences)
- Design files [desktop](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c), [mobile](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/p/B5792AF8-87F2-496D-AE7A-DAD1448A6018/canvas)
- Note: Liz has already conducted usability testing on the designs ([findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/discovery-and-research/usability-study-add-email-jan-2023/findings-summary.md)) and should not have to conduct user research again. Will only need to go through a design intent review with Platform.
- We discussed how our design changes could support VA Notify's requirements for capturing optins and optouts now that we have default send available in July 2022 ([meeting notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/discovery-and-research/default-send/july-2022-notes.md))

**Comment by BerniXiongA6** [comment]
FYI I'm working on finishing this ticket and should have it done before EOB day today. WIll share and go over it with you @mtcA6 for the next time when we have a similar project like this. Thanks!

**Comment by BerniXiongA6** [comment]
Collab Cycle Request KO ticket has been created at #57409.

**Comment by BerniXiongA6** [comment]
Submitted a Slack thread along with a link to the Collab Cycle KO Request ticket at https://dsva.slack.com/archives/CBU0KDSB1/p1682467300381819.

**Comment by mtcA6** [comment]
@BerniXiongA6 in this collab cycle, are we including the work that Liz completed to leverage the[ experimental design](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1646) for actually selecting email as a notification channel.

**Comment by BerniXiongA6** [comment]
Thanks @andaleliz -- for this Collab Cycle request, I'm only referring to the "Default Send Functionality" future FE work and your previous design/research work that's already completed. Hope that clarifies things. cc: @mtcA6

**Comment by andaleliz** [comment]
It does @BerniXiongA6! We should leave the editing pattern out of it then (but not be surprised if it comes up in the review ;)

**Comment by mtcA6** [comment]
If it does come up then we can reference the Collab ticket I'm pulling together that specifically focuses on that updated flow.
