### ISSUE TITLE
Update Board of Veterans' Appeals entry in VA stylebook

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#5640]
## User Story:
As a member of the content team, I need to know the correct terminology for offices and programs within the VA so that I can ensure consistency on VA.gov.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [x] Update entry for Board of Veterans Appeals in VA.gov style guide to add apostrophe to "Veterans'" (put after s)- 1 hour(s) - @RLHecht 
- [x] Create PR for approval - 1 hour(s) - @RLHecht 
- [x] Approve and merge PR - 1 hour(s) - @jenniferlee-dsva 

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
* Term is showing correctly on VA.gov style guide as Board of Veterans' Appeals

## Configuration
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@jenniferlee-dsva I made this change to the style guide and created a PR for you to review: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/170

**Comment by MickinSahni** [comment]
2020-02-12 PW Planning
- Just needs a review on the PR

**Comment by MickinSahni** [comment]
2020-02-13 PW Standup
- waiting for PR review and will check-in to see if it's been ✅

**Comment by RLHecht** [comment]
This has been validated in the live style guide. Closing ticket. fyi @MickinSahni
