### ISSUE TITLE
Remove reference to VBMS Letters

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#56425]
## Issue Description
As a result of privacy incident our stakeholders have decided to no longer use VBMS Letters going forward. 
Although a more detailed update is planned in the future we would like to remove all download letter references for benefit overpayment letters from VBMS.  For follow up questions reach out to Jill Anderson.

![image.png](https://images.zenhubusercontent.com/5f7f60ca14e26c658f77b9f5/d2127a67-ee97-47d7-8a0f-98ef35796176)

---
## Tasks
- [ ] Remove all links to go to the letters.
- [ ] Remove the top sentence below
- [ ] Remove Note (see screenshot) 
- [ ] Add in:
> If you have questions about your debt letter history, or would like a copy of your letters please contact the Debt Management Center at 800-827-0648 or via Ask VA (put in the link)

## Acceptance Criteria
- [ ] All references to download letters from VBMS have been removed from the portal 
---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Tom-Davis** [comment]
This was already completed.
