### ISSUE TITLE
[SW] Product Outline for Streamlined Waiver

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#56432]
## Issue Description
Review and make any necessary updates to [Product Outline: Streamlined Waiver Process
](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/streamlined_waiver/product_outline.md)

---
## Tasks
- [ ]  _Discuss updates with team_
- [x]  _Make any necessary updates_

## Acceptance Criteria
- [ ] _Product outline updated and reviewed by team_

**Comment by HeatherRienks** [comment]
Let's plan to discuss this in an upcoming SW meeting to determine how we will tackle this.

**Comment by HeatherRienks** [comment]
Testing; did this message go through, @denisecoveyduc ? :)

**Comment by denisecoveyduc** [comment]
Thanks @HeatherRienks - found the issue..  good to go now!

**Comment by HeatherRienks** [comment]
This ticket will rollover; focus has been on FSR launch.

**Comment by denisecoveyduc** [comment]
@HeatherRienks  @Tom-Davis  I have updated the product outline for the Streamlined Waiver work. There may be a few slight adjustments here and there but for now the document is ready to go. Let me know if you have any questions or need any further details or  insights etc. 
Link to  - **[Streamlined Waiver Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/streamlined_waiver/product_outline.md)**

**Comment by HeatherRienks** [comment]
Thank you @denisecoveyduc!
