### ISSUE TITLE
Competitive Analysis of "My Payment History"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#5644]
## Goal
We want to get initial impressions, design hypothesis and simple field research/competitive analysis in place to move the feature forward in serving the Veterans needs.

## Considerations
Time box this to 1 hour.

## Tasks
-  [ ] Document in GH any initial impressions on the existing features and paper form and what might change as the feature is transformed in to VA.gov.
- [ ] Document in GH our design hypothesis that shows how we might be able to implement the feature using existing design patterns and practices.
  - For example, perhaps some components are on the same page?
- [ ] Document in GH existing field research, if any.  Include findings from discovery sessions

## Acceptance Criteria
- [ ] An .MD file has been created in GH in the feature research repo.

**Comment by sporeboy** [comment]
Draft of analysis here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-payment-history/research-design/payment-history-comp-analysis.md

Due to time constraints, there are no screen caps.
