### ISSUE TITLE
Create Workflow Diagram of Existing Application ("My Payment History")

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#5645]
## Goal
Create a high level view of the workflow a Veteran might take to view and update their representative.

## Considerations
- Note any functions that are outside of the regular path as well as any potential improvements we might make.
- Note any limitations or caps on what and how data is returned

## Tasks
- [x] Create a thumbnail view of the workflow with notes on alternate paths mapping the known intended functionality.
- [x] Share with IA for url/page placement

## Acceptance Criteria
- [x] A high level workflow has been created with notes for future research plan
- [x] Share with IA (Mikki) for confirmation

**Comment by sporeboy** [comment]
Thubnail diagrams created for both existing and proposed user flows.

XD link available here: https://xd.adobe.com/view/44399930-6143-4192-6e80-99a0566c4092-3208/

**Comment by sporeboy** [comment]
@mnorthuis We have initial ideas for the next eBenefits feature we're migrating: Payment History. In the abstract, it's a lot like Rated Disabilities or View Dependents--that is, it's a static view of what VA has on record. Our initial thought the page would live right off the root, and it would have a static landing page to gate users. I'm not sure where it would generally belong: Disabilities, Pensions, or ???

Here is the diagram we're using to start the conversation.

![View_Payments_User_Paths_1.png](https://images.zenhubusercontent.com/5d6ec7967521390001c3e794/88ea6b54-e51b-4938-b72f-29c7ef6d5aa5)
