### ISSUE TITLE
Medallia satisfaction survey data review

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#56464]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

We seek to establish a baseline of satisfaction of the FSR form by assessing previous satisfaction data, before the launch of upcoming eFSR. 

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_
- [x] _Submit a ticket for data request_
- [x] _Receive data reports_
- [ ] _ Review data reports_
- [ ] _ Extract meaningful data to include in a report_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

- [x] _Submit a ticket for data request_
- [x] _Receive data reports_
- [ ] _ Review data reports_
- [ ] _ Extract meaningful data to include in a report_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
Per 6/6 Design meeting, moving this to Ready for now, as our top priorities are currently FSR and SW work.

**Comment by HeatherRienks** [comment]
Moving this ticket to the "ready" column, as there are more pressing priorities. We will tackle this is an upcoming sprint.

**Comment by HeatherRienks** [comment]
We need to prioritize our SW efforts and we have decided to close this ticket. We will create a follow up ticket (to remain in the Backlog) until we are able to revisit.

cc: @Tom-Davis

**Comment by charlottecesana** [comment]
Data has been requested, received, and transferred to Mural for analysis. The analysis is in progress, pending completion when we are able to revisit.

**Comment by HeatherRienks** [comment]
New ticket with remaining work is #61351. Closing this ticket.
