### ISSUE TITLE
Create automatic reminders for Monthly VFS Backend and Frontend Orientations

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#56460]
## Issue Description
Automatic reminders for Monthly backend and frontend CoP Orientations need to be created so they're not accidentally missed.

The reminders can be sent to the Internal Tech Support Team channel and the COP channels.

---
## Tasks
- [x] Create reminders

## Acceptance Criteria
- [x] Reminders have been tested and operate as expected
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by holdenhinkle** [comment]
I added the FE and BE orientations to the Platform calendar and added the folks who are currently presenting the orientations.

@rjohnson2011 will be rolling off support (which includes presenting the BE orientation) and @rmtolmach , @ryan-mcneil and @jeremy6d will be rolling onto support. I'll get with Rebecca, Ryan and Jeremey to discuss who would like to present and who might like to be the designated backup.

**Comment by holdenhinkle** [comment]
I added several Slack notifications:

The FE and BE Slack channels will be notified on...

The 1st of every month:![monthly reminders - 1st of the month.jpg](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/685901b0-796b-440f-b90f-28a790c90dc7)

And at 9am the day of:![day-of-reminder-example.jpg](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/ce2ffb49-af30-43e0-a58a-6920aa9c6251)

**Comment by holdenhinkle** [comment]
For Q2:

Frontend:

- @CBonade is primary
- @rmessina1010 is backup

Backend:

- A meeting has been scheduled for next week to designate a primary and a backup
