### ISSUE TITLE
Support: Mon-Thur Deploy (S25)

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#56487]
## User Stories
As a Platform team member who just contributed to the Platform website,
I need my content published,
so that I can share my content updates with the intended audience.

As a content team,
we need to review any new content changes made on the platform,
so that we can deploy every Tuesday and Thursday of the week.

## Tasks
Someone from our team will use Scroll Viewport to publish changes to the website after 3pm EST on:

- [x] Wednesday (4/12) - Brian filling in for Samara
- [x] Thursday (4/13) - Jill
- [x] Monday (4/17) - Lauren
- [x] Tuesday (4/18) - Brian
- [x] Wednesday (4/19) - Samara
- [x] Thursday (4/20) - Jill
- [x] Monday (4/24) - Lauren
- [x] Tuesday (4/25) - Brian

## Acceptance Criteria

- [x] The Platform website will be deployed Monday-Thursday between 3:30 and 5pm for this sprint.
- [x] Any edits with launch-blocking issues will be announced to their content editors via #platform-content

## Other Info
Rotating schedule:
https://vfs.atlassian.net/wiki/spaces/CIT/pages/2405171201/Deployment+rotation+schedule

Data tracking info:
https://vfs.atlassian.net/wiki/spaces/CIT/pages/2282979860/KPIs+-+Content+Support
