### ISSUE TITLE
Make claim status tool CTAs consistent across benefit pages

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#5648]
## Make claim status tool CTAs consistent across benefit pages
Change the various CTA button labels to be consistent: "Check your claim ~~or appeal~~ status"
(Update 5/20/2020: we are removing the 'or appeal' part of the label listed above, we think the updated language will be applicable to all scenarios)
 
__On these pages - note: there may be others; please do a search where others may appear:__

- [x] https://www.va.gov/decision-reviews/
- [x] https://www.va.gov/decision-reviews/supplemental-claim/
- [?] https://www.va.gov/decision-reviews/higher-level-review/ Did not find mention of tool on this page. 
- [x] https://www.va.gov/decision-reviews/after-you-request-review/
- [x] https://www.va.gov/disability/file-an-appeal/
- [x] https://www.va.gov/disability/how-to-file-claim/
- [x] ![image](https://user-images.githubusercontent.com/53535663/82483351-41f44e80-9aa6-11ea-9e3d-57f1bbffae0a.png)
- [x] ![image](https://user-images.githubusercontent.com/53535663/82483372-4d477a00-9aa6-11ea-9dbc-29c225fa45d7.png)
- [x] ![image](https://user-images.githubusercontent.com/53535663/82483393-559fb500-9aa6-11ea-9289-153d4b61c058.png)
- [x] ![image](https://user-images.githubusercontent.com/53535663/82483445-67815800-9aa6-11ea-8907-a1fdedf7d32b.png)

This is related to (but not dependent on) the larger AMA updates that @lwalsh617 is working on. She can provide background. 
@MickinSahni These are all in Drupal so Randi should be able to do these; but a few of these may appear inside REACT widgets, so we may need FE to update those. 

## Tasks / Pre-requisites
- [x] Get CTA language approved/consistent across benefit pages - @lwalsh617 
- [x] Circle up with Mikki for her guidance - @lwalsh617 
- [ ] Search for any other pages where these may appear - @ncksllvn @kelsonic 

## Acceptance Criteria
- [ ] Make the requisite changes to make changes to the associated React widgets

**Comment by MickinSahni** [comment]
Thanks, @jenniferlee-dsva. Couple questions:
- What epic/initiative should this be a part of?
- We start Sprint 15 next. How important is it to include this in that sprint vs a later one?

**Comment by jenniferlee-dsva** [comment]
I think site maintenance. It's not urgent, though it is related to Laura's larger AMA content updates. It can happen with or after those.

**Comment by MickinSahni** [comment]
2020-03-18 Grooming
* Doing prep work before assigning to a sprint

**Comment by MickinSahni** [comment]
2020-03-18 PW Grooming
* Still requires dev grooming. Tagged Nick above

**Comment by lwalsh617** [comment]
@mnorthuis  -- Jen had requested that I touch base with you on this. We want to make the button language for the status tool consistent across the site. The language Jen proposed is:
"**Check your claim or appeal status**"
Do you have any input, or can we go ahead and make this change?

**Comment by mnorthuis** [comment]
@lwalsh617 I would like to see this be consistent as well, but I'd like to review all the places where we have the button to make sure.  I believe there may be some placements where we don't include language around "appeals" because its not applicable to the placement (and visa-versa).   Do we have a full list of pages where this button currently lives?

**Comment by ncksllvn** [comment]
I started looking into which pages use CTA widgets, specifically those for Claims. The only page that uses the React-based CTA widget is `/claim-or-appeal-status`. The rest of these pages use other elements - sometimes a just a link (that looks like a button) and other times a wizard, which is similar but contains steps to help guide the user before actually starting the form. Because of these different formats, it's difficult for me to do a search.

| Page | Element type |
| --- | --- |
| https://www.va.gov/decision-reviews/  | Plain link |
| https://www.va.gov/decision-reviews/supplemental-claim/ | Plain link |
| https://www.va.gov/decision-reviews/higher-level-review/ | Plain link |
| https://www.va.gov/decision-reviews/after-you-request-review/ | Plain link |
| https://www.va.gov/disability/file-an-appeal/ | Plain link (inside an alert box) |
| https://www.va.gov/disability/how-to-file-claim/ | Wizard (FE code) |

I can really easily search for certain text or links though if there's a particular text snippet you'd like to search for.

**Comment by MickinSahni** [comment]
Thanks, Mikki. 
@lwalsh617 @ncksllvn  — how do you feel about where we are with this inventory and whether we're able to begin making these CTAs consistent? Granted we prob didn't find them all.

**Comment by ncksllvn** [comment]
I think almost all of them are editable from Drupal, except for the wizard at /disability/how-to-file-claim/

**Comment by ncksllvn** [comment]
Scratch that, https://www.va.gov/disability/how-to-file-claim/ -

![image](https://user-images.githubusercontent.com/1915775/77677108-a0e58d80-6f65-11ea-97e6-737a31a99265.png)

This is also a plain link. I was looking at the wrong page component.

**Comment by lwalsh617** [comment]
I've been keeping a list of pages where I've spotted the tool.  Would feel better if we could do an exhaustive search. The tricky part is that the language changes. Is there a way to search for the tool itself rather than button copy?

**Comment by lwalsh617** [comment]
@mnorthuis FYI, we discussed this on sprint planning with Jen. We want to change the CTA to "**Check your VA claim status**" everywhere, because:
- Users don't think of an "appeal" as separate from a claim, as an appeal is part of the larger claim process, so we're okay with having a "Check your VA claim status" on a decision-review page
- We avoid the word "appeal" which has become an SME hot button
- We don't need to worry about appeal vs. claim for CTA and can be consistent across the site
- It's tied to the tool name, which starts "Check your VA claim..."

Let me know if you have any questions. I'll start changing it in Drupal. 
FYSA:  @stephorkandatx @jenniferlee-dsva

**Comment by stephorkandatx** [comment]
@lwalsh617 i updated the CTA language in light of the discussion re: "appeal" that you covered in your comment. Ready for the sprint!

**Comment by lwalsh617** [comment]
@RLHecht @mnorthuis -- 
I checked all pages on this ticket and made revisions where needed. Did not find the tool on other pages listed:
Supplemental claims:  preview-prod.vfs.va.gov/preview?nodeId=3011
Higher-Level Reviews: tool not found
After you request review: preview-prod.vfs.va.gov/preview?nodeId=3008
Disability/File an appeal: preview-prod.vfs.va.gov/preview?nodeId=3102

**Comment by lwalsh617** [comment]
@mnorthuis -- Randi is ready to publish these pages, but wanted to get the go-ahead from you first. Thanks!
