### ISSUE TITLE
[526 - Historical Claims] Batch #3

### ISSUE THREAD

**Issue by kylesoskin** [department-of-veterans-affairs/va.gov-team#56494]
## Value Statement
**_As a_** VBA stakeholder
**_I want to_** have a set of payloads that represent historically failed 526 submissions
**_So that_** I can have my people reprocess them into new 526 claims in bulk.

## Background Context

This is the third batch of payloads attempted to be pulled from the original list of ~40k submissions. 

This batch is attempting to pull around ~7500 remaining submissions that have not already been delivered in the first 2 batches. 

## Out of scope

- Any additional batches
- Any work to reduce or slim down this batch
- Generation of any lists or additional info the VBA needs to process batch 3, this is just for generating and getting the payloads to them 
- Fixing of any of the ~7500 that fail to generate payloads (there will be many that will not be able to yet without further investigation and bug reduction, that is not part of this ticket)

## Tasks
- [x] Get list of remaining IDs (not in batch 1 or 2)
- [x] Get script in place to pull payloads
- [x] Coordinate time to pull files with EVSS (Aug 23, 2023 10pm EST, or Aug 24, 2023 5pm EST)
- [x] Generate payloads into s3
- [ ] Generate pull-down links for VBA people to pull files to their system from s3
- [ ] Send list to VBA

## Acceptance Criteria
- [ ] Confirm receipt of files

## Definition of Done
- [ ] AC and related tasks complete
- [ ] Processed with approval from VBA (David Reis)
- [ ] Documented for KT handoff to 526 team

* Note, working with @SamStuckey to knowledge transfer this.

**Comment by saderagsdale** [comment]
@kylesoskin can you fill this in with details before refinement?

**Comment by HeatherWidmont** [comment]
Will pull tonight at 5pm 😄

**Comment by saderagsdale** [comment]
Need to confirm with David Reis that they can pull down file that Kyle shared. Kyle will check today @kylesoskin
