### ISSUE TITLE
[526 - Historical Claims] Batch #2

### ISSUE THREAD

**Issue by kylesoskin** [department-of-veterans-affairs/va.gov-team#56493]
## Value Statement
**_As a_** software developer
**_I want to_** transfer the second batch of failed 526ez claims
**_So that_** they can be processed by the VBA.

---
## Background Context
15,000 claims fail for the same reason as the backup submission failures, validation errors from EVSS getPDF endpoint. Awaiting relaxing of validation on that endpoint to gather these

## Tasks
- [x] Await release of EVSS validation lifting
- [x] Test Validation has been lifted
- [x] Run Sidekiq queued jobs to pull remain issues that were resolvable by this fix
- [x] Pull down and deliver Files to VA
- [x] Delete/Clear out/Move files to prepare for next pulls
- [ ] Generate Address and Pcpt_id mapping list for VA

## Assumptions, Dependencies, and Blockers
- EVSS fix goes out on time and works as expected

## Definition of Ready 
- [x] Script(s) used to transfer these claims are approved with EVSS and VBA
- [x] VBA gives approval before initiating the transfer
- [x] Dependencies assumption and blockers are listed

## Definition of Done
- [x] VBA and EVSS give sign off on the success of the transfer
- [x] Reviewed and approved by product

**Comment by saderagsdale** [comment]
David R confirmed that we're good to send batch 2. Will send over after 4pm ET today.

**Comment by saderagsdale** [comment]
Needs to find the format for the last file and send it to VBA.

**Comment by saderagsdale** [comment]
@kylesoskin is this still in progress?
