### ISSUE TITLE
Conduct UAT for "View my payment history"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#5651]
## Story
As a designer/researcher for the eBenefits Team, I want to be able to understand how the Veteran is currently interacting with this feature holistically so that I can create a more accurate description of what needs to be developed.

## Goals
- Use a conversation guide (include as delivery)
- Use research plan (include as delivery)
- Conduct a usability session that answers pain point questions and informs the team what the best thing to build might be
- [Previous Research Plans used](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/disabilities-dependents-usability-1119/disabilities-dependents-usability-research-plan.md)
- [General VSA eBenefits Research Process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/vsa-research-process.md)

## Tasks
- [x] Using the [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-POA/research-design/poa-payment-history-research-plan.md), and included [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-POA/research-design/21-22-interview-conversation-guide.md)
- [x] Coordinate sessions with user research partner (Perigean), asking them to take notes 

## Acceptance Criteria
- [x] UAT has been conducted 
`(Initial synthesis due 7 days from last session)`

**Comment by jason-gcio** [comment]
Moving this to next sprint

**Comment by jason-gcio** [comment]
6 sessions scheduled

**Comment by sporeboy** [comment]
New state created in mockups to show LOA1 access to VPH feature.

**Comment by sporeboy** [comment]
UAT sessions conducted; study closed 1/8.
