### ISSUE TITLE
Design identity communications model/roadmap

### ISSUE THREAD

**Issue by elizabethkochBT** [department-of-veterans-affairs/va.gov-team#56513]
Design identity communications model for tracking all team's identity comms efforts and overlap.

Build out a visual diagram of the process and what comms pieces are coming from who. We're several months in and it's still a little confusing all of the offices and who owns and sends what. I was thinking of something almost like a journey map or service blueprint that connects dots on process and plan. Something visually showing flow, ownership and process might be helpful. 

## User Story 
As an identity stakeholder, I need clarity around all the communications going out to Veterans so we are aware of overlap and potential conflicts. 

## Tasks 
- [X]  Design [mural](https://app.mural.co/invitation/mural/innovationboards1199/1680884313222?sender=u99cd1ac4f5c240d8dffd4204&key=ee41c499-56e0-4b9f-9247-3d3849c9ae35)

- [X]  Once identity [contacts list](https://docs.google.com/spreadsheets/d/18LUvaTxHe__Ae54O3yUHFwhEpQZrqf-f-312drKsOwc/edit#gid=1513246744) finalized, share and partner with stakeholders

## Acceptance Criteria
- [ ]  Present to the working group meeting

**Comment by skirkman16** [comment]
will present at the working group meeting on 4/27. Sent out a link to Michelle so that she can share in OCTOPUS
