### ISSUE TITLE
Establish GA Events for "View Dependents"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#5652]
## Goal
Fire appropriate GA events on this feature so we gain insight into how often it's accessed and how it is being used.

## Considerations
- Complete unit test first
- @nedierecel & @jonwehausen will be looking for these things:
  - For Event Tracking: Other than obvious links on the page, are there any other user interactions that are expected to take place that might not be visible?  
  - We can measure successful and failed loads of pages. Are you currently seeing any of these events pushed into the dataLayer?  
  - For Pageview Tracking: Does this page render a unique URL? Are there any other historyChanges that take place as the screen loads? I ask as it impacts how we measure pageviews.  
- In case it helps, here is a link to [a similar past ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/2072) and a ticket for [implementation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/2859), also see comments below.
- [Link to Insights request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6830)

## Tasks
- [x] Engage with GA/Insight Team to understand:
  - [x] We need event names supplied to us from the GA / Insight team similar to how other events are fired in other applications. i.e. `recordEvent({ event: 'profile-get-direct-deposit-failure' });`
  - [x] Gain any feedback from the GA/Insight Team that might help for other event names

## Acceptance Criteria
After staging:
- [x] Request event names from GA / Insight team that we can use on View (and Submit 686 as applicable)

**Next Steps**
- Implement the event names per the format of Insights
- Events are successfully fired and recorded in GA.
- Establish baseline metrics

**Comment by micahchiang** [comment]
Here's the GA ticket from Rated Disabilities, in case anyone is interested in using it as a reference - https://github.com/department-of-veterans-affairs/va.gov-team/issues/2072

**Comment by jason-gcio** [comment]
@micahchiang - Nice find.  I added some notes to this ticket description and included a link to another ticket for actual implementation.  I think you mentioned something in planning about these being separate.  I envy your memory.

**Comment by micahchiang** [comment]
Taking some queues from https://github.com/department-of-veterans-affairs/va.gov-team/issues/2072, I think we want to determine what aspects of the view dependents page users an interact with. Additionally, we'll want events that capture successful page loads as well as error states. 

I _think_ we might also need to fill out this request template as well - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/analytics-communication-guide.md.

Here are some rough ideas for potential events after a cursory glance at View Dependents and a look at what we did for Rated Disabilities:

#### API request events:
`window.dataLayer.push({'event': 'view-dependents-load-success'})`
`window.dataLayer.push({'event': 'view-dependents-load-failed', 'error-key': '500 internal error'})`
`window.dataLayer.push({'event': 'view-dependents-load-failed', 'error-key': '4xx no dependents found'})`

#### Navigation events:
`window.dataLayer.push({'event': 'dependents-navigation', 'nav-action': 'add-remove-dependents-information' });`
`window.dataLayer.push({'event': 'dependents-navigation', 'nav-action': 'get-help-filing-claim' });`

#### Assistance(?) events:
`window.dataLayer.push({'event': 'dependents-assistance', 'assistance-action': 'call-va-helpdesk' });`

**Comment by cohnjesse** [comment]
@nedierecel @jonwehausen  As we move towards deploying rated disabilities to staging, I wanted to kick off a conversation about what sort of events this page should fire. I've attached a screenshot of the page to this comment. Would it be possible, just by looking at it, for you to give us an idea of:

- How many events would need to be implemented.
- The names of the events.

I have seen some events being pushed by the dataLayer. Would this need to be done here? Basically I am wondering, since our eBenefits team is all fairly new, what sort of configuration we need to do on our end to register rated disabilities with GA.

Here are some rough ideas for potential events after a cursory glance at View Dependents and a look at what we did for Rated Disabilities:

API request events:
window.dataLayer.push({'event': 'view-dependents-load-success'})
window.dataLayer.push({'event': 'view-dependents-load-failed', 'error-key': '500 internal error'})
window.dataLayer.push({'event': 'view-dependents-load-failed', 'error-key': '4xx no dependents found'})

Navigation events:
window.dataLayer.push({'event': 'dependents-navigation', 'nav-action': 'add-remove-dependents-information' });
window.dataLayer.push({'event': 'dependents-navigation', 'nav-action': 'get-help-filing-claim' });

Assistance(?) events:
window.dataLayer.push({'event': 'dependents-assistance', 'assistance-action': 'call-va-helpdesk' });

![screencapture-xd-adobe-view-8cdfe895-c907-4662-7234-305056778b2a-faee-screen-61211510-a9de-477c-950c-ae7fe5d2ce65-View-Dependents-2-2020-03-11-12_06_42](https://user-images.githubusercontent.com/1899695/76453863-dcdaf900-6390-11ea-9c03-890fbab1c495.png)
