### ISSUE TITLE
Build the Drupal template AX for the forms detail landing page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#5653]
## Acceptance criteria
- [x] Edit screen AX approved
- [x] Plan for edit screen hep text in place
- [ ] Forms listing page AX approved
- [ ] AX validated with Jen in Drupal  <-- added 6/18 Jen

## Tasks
 - [x] Create AX mockup or prototype
- Get sign-off on AX
  -  [x] from websites team
  -  [x] from cms team
- [x] Consult with cms team regarding help text

## Build the Drupal template AX for the forms detail landing page

User story:
As a veteran who does a Google or other organic search for form X, I want to be able to find the form and also know if there's an online alternative that's easier than filling out and mailing a paper form.

As a content person, I need to be able to enter certain custom SEO optimized text to the basic form detail landing page template. 

__Product Outline__
[Redesign the Find a VA Form page](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign#product-outline-redesign-the-find-a-va-form-page-httpswwwvagovvaforms)

### Doc showing mockups of design is uploaded here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/VA-form-master-detail-LP-patterns-mockups-v7.pdf

__Background:__
We have 2 kinds of 'master detail' form landing pages - custom and 'template.' We are creating custom landing pages for our top forms that map to our online tools. The custom pages share many of the same content fields as the basic template version but with a few that are unique and customizable.

__Task:__
Build the Drupal template AX 
- it will include template data fields that pull info from the forms database (currently via Lighthouse API)
-it will also include a few other data fields that enable authors to enter custom text (Ex: When to use this form; Related forms and instructions; Helpful links related to <VA FORM #>)

This task does not cover backend implementation with the API and with the forms database, which is separately being discussed with @ncksllvn @JeffBarnesUSDS @kevwalsh @jefflbrauer and the Lighthouse API team. 

__Template fields:__
The content fields in a template landing page – if it has everything filled out in the db schema – will be:
a. Form number H1 [rigid; dynamically pulled from forms db]
b. Form name H2 [rigid; dynamically pulled from forms db]
c. Related to: [category, category… one or multi-select][rigid; dynamically pulled from forms db]
d. Form download link [rigid; dynamically pulled from forms db]
e. Button CTA to online exp – omit in FE if N/A [dynamically pulled from forms db, but only if form has an online tool]
f. Standard helpful links [rigid; static content] 

The CUSTOM (customizable) landing page will include the above, plus:
- When to use this form [rigid label; customizable blurb text] <--this content entry field needs to accommodate wysiwig/rich text formatting. Edited JLee 6/3]
- Related forms and instructions [rigid label; customizable text links]
- Custom helpful links (instead of the standard links - but same component style)

**Comment by jenniferlee-dsva** [comment]
@davidconlon Per convo last week with @JeffBarnesUSDS  @KevinMHoffmanUSDS and @chrisj-usds, the public website team is  requesting Drupal engineering resource from your VAMC team to build this template AX in Drupal. I wasn't sure which team label to use (frontend VAMC or VAMC upgrade?), so will leave that for you and/or Stan to figure out how you want to manage. 

We don't currently have a specific ETA for this. We have a few dependencies with the API and forms database, so it is not urgent/imminent, but we would like to get it in your queue for Sundhar early, as I know his availability may change later. 

@MickinSahni and @ncksllvn ^ FYSA.

**Comment by AkucherGCIO** [comment]
03/11/20 Sprint 17 Planning
Blocked until the VA Forms database access comes through.

**Comment by beeyayjay** [comment]
AX has been reviewed and implemented in content model prototype (https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1774)

**Comment by jenniferlee-dsva** [comment]
I clarified one of the AC's ^ per prior convos w/Beth: The 'when to use this form' content filed needs to be enable rich text formatting (bold, para breaks, bullets, so on) wisywig. 
@swirtSJW  @stephorkandatx

**Comment by swirtSJW** [comment]
I confirmed that field is already a WYSWIG field.

**Comment by jenniferlee-dsva** [comment]
Hi @swirtSJW - Looks like there's already a ticket for the AX. I just added a validation step as an AC, so whenever you are ready, let's do a synchronous walk through/validation. 
FYSA @stephorkandatx

**Comment by jenniferlee-dsva** [comment]
@swirtSJW - Thank you for the walk through and AX validation. Once the items we noted during the walk through have been updated, we can mark this as done. The items are: 

1/ Form administration dropdown choices: Add "Veterans Affairs"; remove "DEPO"

2/ Add ability to add an in-body alert component (unique or reusable). This component should be allowed above the `When to use this` form custom field and PDF link. 

3/ Meta title tag logic: "Va" should be "VA"

4/ Meta description field logic: Point to pull from the When to use this form field, when available. If none, should show empty. Is also over ridable with manual entry.

**Comment by swirtSJW** [comment]
Created ticket for 1, 3, and 4 here 
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2108

2 is already tracking here https://github.com/department-of-veterans-affairs/va.gov-team/issues/9189

**Comment by jenniferlee-dsva** [comment]
Referencing one more item here for visibility - a new ticket - on CMS board for Steve: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2119

**Comment by swirtSJW** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2108 has been merged in.
it resolves 1,3 and 4 as well as the breacrumb and title change to add "About "

1/ Form administration dropdown choices: Add "Veterans Affairs"; remove "DEPO"  This request could only be partially acted upon because this is just surfacing the top levels of the "Sections" taxonomy in the CMS
1. Veterans Affairs
2. National Cemetery Administration
3. Veterans Benefits Administration
4. Veterans Health Administration
5. DEPO

I can spend time intentionally removing "DEPO" but that creates a bit of technical debt as a one-off case of altering the top level sections, so I would prefer not to build that technical debt.

**Comment by swirtSJW** [comment]
This has been merged and will go out to production on Mon 6/28 https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2123   

This resolves 

> 2/ Add ability to add an in-body alert component (unique or reusable). This component should be allowed above the When to use this form custom field and PDF link.
