### ISSUE TITLE
[UX] Create Content for Next-Step Instructions for a Video Appointment

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#56551]
## User Story
As a Veteran, when I complete Pre-Check-in for a video appointment, I want to see next-step instructions that are applicable to my video appointment so that I will know what to do next.

## Userflow
- Given I
     - Received a pre-check-in link for a VVT appointment
- When I
    - Open the link
    - Complete any contact verification questions
    - See the pre-check-in completion page
- Then I
    - See instructions that tell me what to do next for my video appointment

## Tasks
- [ ] Create the content 
- [ ] Run content by Sitewide Content team

## Acceptance Criteria
- [ ] Content has been created & reviewed
