### ISSUE TITLE
[UX] Create Final Wireframes for Next-Step Instructions for a Video Appointment

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#56552]
## User Story
As a Veteran, when I complete Pre-Check-in for a video appointment, I want to see next-step instructions that are applicable to my video appointment so that I will know what to do next.

## Userflow
- Given I
     - Received a pre-check-in link for a VVT appointment
- When I
    - Open the link
    - Complete any contact verification questions
    - See the pre-check-in completion page
- Then I
    - See instructions that tell me what to do next for my video appointment

## Tasks
- [ ] Create final mockups with callouts 

## Acceptance Criteria
- [ ] UI review meeting with product/UX team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.
