### ISSUE TITLE
[FE] Change Next-Step Instructions for VVT/Video Appointment upon Pre-Check-in Completion

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#56554]
## User Story
As a Veteran, when I complete Pre-Check-in for a video appointment, I want to see next-step instructions that are applicable to my video appointment so that I will know what to do next.

## User Flow
- Given I
     - Received a pre-check-in link for a VVT appointment
- When I
    - Open the link
    - Complete any contact verification questions
    - See the pre-check-in completion page
- Then I
    - See instructions that tell me what to do next for my video appointment
  
## Wireframes
See [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56552)

## Tasks
- [ ] [FE] Update messaging if appointment is a VVT/video appointment
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
