### ISSUE TITLE
Sign-in Service App - Onboard app to EKS

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/va.gov-team#56574]
## Summary
Onboard app to EKS/Argo; create app in [vsp-infra-application-manifests](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests)

## Tasks
- [x] Create [Application Onboarding ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=va-vsp-bot&labels=application-onboarding%2Coperations&template=application-onboarding.yml&title=Application+to+Onboard%3A+%5Bapplication-name%5D)
- [x] Maintainers - @rileyanderson, @bosawt, @joeniquette
- [x] Application name - `sign-in-service`

## Acceptance Criteria
- [x] Application successfully added to [vsp-infra-application-manifests](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests)

## Related Issues/PRs
- department-of-veterans-affairs/va.gov-team#58627
- department-of-veterans-affairs/vsp-infra-argocd#204

**Comment by aparsley** [comment]
Why is this blocked? Please put a comment.
