### ISSUE TITLE
Content changes for BDD - SHA Part 1

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#56570]
## Issue Description
Users who are active service members submitting a 526 under the BDD (Benefits Delivery at Discharge) Program will need to also submit a Part A Self-Assessment form as of April 1 in order to get an exam before discharge from service.

This ticket is to implement content changes on the following pages of the form to inform/direct the veteran of the requirement to complete and upload the Part A Self-Assessment form along with the claim to not hold-up further processing:
- Content changes to BDD intro page
- Content changes to separation page in Original Claim (OC) flow
- Content changes to BDD supporting evidence page (two states, one for yes, one for no)
- Content changes to BDD evidence upload page
- Content changes to BDD and OC post-submission page

---
## Tasks
- [ ] TBD

## Acceptance Criteria
- [ ] Content changes completed as specified in the following sketch file for the following pages:
- Content changes to BDD intro page
- Content changes to separation page in Original Claim (OC) flow
- Content changes to BDD supporting evidence page (two states, one for yes, one for no)
- Content changes to BDD evidence upload page
- Content changes to BDD and OC post-submission page
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
cc @lydiahooper @christinec-fftc 
Needs link to the content changes

**Comment by christinec-fftc** [comment]
This ticket has been reworked (see [this comment](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/56573#issuecomment-1511807935)) and needs repointing

**Comment by christinec-fftc** [comment]
This ticket has been reworked (see [this comment](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/56573#issuecomment-1511807935)) and needs repointing
