### ISSUE TITLE
[bug] Missing in-line errors for Review and Submit validation

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#56608]
## Value Statement
**_As a_** veteran
**_I want to_** know exactly what is causing an error in my submission
**_So that_** I can fix the errors and submit my form

---
## Background Context
- In the past 7 days, there have been 2 FE validation issues (from Apr 6, 2023). The validation errors that came up are '[You must enter a treatment date](http://sentry.vfs.va.gov/organizations/vsp/discover/platform-web:00caeedad8674afeabe284dee33b42de/?field=message&name=Supplemental+Claims&project=4&query=url%3Ahttps%3A%2F%2Fwww.va.gov%2Fdecision-reviews%2Fsupplemental-claim%2Ffile-supplemental-claim-form-20-0995%2F%2A+level%3Aerror+message%3A%22Validation+issue+not+displayed+https%3A%2F%2Fwww.va.gov%2Fdecision-reviews%2Fsupplemental-claim%2Ffile-supplemental-claim-form-20-0995%2Freview-and-submit%22&sort=-message&statsPeriod=7d&widths=-1)' and '[You must enter a treatment date #2](http://sentry.vfs.va.gov/organizations/vsp/discover/platform-web:ae9456ed5d1f447f81a24a960bc930e4/?field=message&name=Supplemental+Claims&project=4&query=url%3Ahttps%3A%2F%2Fwww.va.gov%2Fdecision-reviews%2Fsupplemental-claim%2Ffile-supplemental-claim-form-20-0995%2F%2A+level%3Aerror+message%3A%22Validation+issue+not+displayed+https%3A%2F%2Fwww.va.gov%2Fdecision-reviews%2Fsupplemental-claim%2Ffile-supplemental-claim-form-20-0995%2Freview-and-submit%22&sort=-message&statsPeriod=7d&widths=-1)'. 

As it's unclear how the applicant is able to reach the Review and Submit page with errors pending, we are adding validation on the Review and Submit page and notifying veterans if there is an error within the evidence they need to fix.

<details><summary>Currently on staging</summary>

![image.png](https://images.zenhubusercontent.com/630d073e647e629355675b4b/01b474de-eddc-449b-984c-056329b5ec23)
</details>

## Acceptance Criteria
- [ ] Validation is in place for Review and Submit page to check for errors.
- [ ] In-line errors will show where applicable

## Designs and Build Notes
- [SKETCH](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/a/MmyE0Kz)

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by eileen-coforma** [comment]
Looks good

**Comment by Mottie** [comment]
@saderagsdale I think we can close this ticket
