### ISSUE TITLE
Add the form Wizard and Report a death of a dependent workflows for the new form 686

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#5661]
## User Story
As a veteran, I want to use the 686c to pick the form workflow I want to complete as well as to report the death of a dependent, so my disability benefits information is reported accurately. 

## Considerations
- [Mockup for workflow](https://xd.adobe.com/view/0f7759a1-b990-4d71-50c9-138d9e593fd0-7946/screen/dba0e2aa-ee9f-42ec-9414-806c58b1695b/Apply-Dependents-Report-Child-Marriage-1B)
- [Corresponding paper form section](https://www.vba.va.gov/pubs/forms/VBA-21-686c-ARE.pdf)

## Tasks
- [ ] Add the workflow for the death of a dependent to the new 686c form
- [ ] Add the wizard at the beginning of the new 686c form

## Definition of done
- [ ] The section has been added and maps correctly to the paper form.

**Comment by micahchiang** [comment]
PR merged - https://github.com/department-of-veterans-affairs/vets-website/pull/11624
