### ISSUE TITLE
Design/Content - Validation for Future Service Exit Date

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#56631]
## Issue Description
526ez allows both veterans and active service members to file claim for benefits on va.gov. The 526ez flow requires active service members to select BDD to file for pre-discharge benefit claim. Currently, there is no validation in place to stop users from entering a future service exit data if they have not selected BDD. This is causing a downstream problem where a claim is getting established for a veteran with future service exit date.

The scope of this ticket is to prevent a veteran from entering a future service exit date. 

Veterans who are no longer in service
- must enter a past date as their service exit date
- when entering a future or null service exit date, this ticket will define what error message is displayed to the user.

An active service member must  
- choose BDD for pre-discharge benefit claim
- when choosing BDD, they are allowed to put a future date for their exit date. They can also leave it as blank
- when entering a past service exit date, this ticket will define what error message is displayed to the user.(Required only if there is no validation in place today)

---
## Tasks
- [ ] TBD

## Acceptance Criteria
- [ ] Define design/content to display for active service member when entering past service exit date
- [ ] Define design/content to display for a veteran when entering null or future service exit date

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
@lydiahooper @christinec-fftc @navaeddie

**Comment by RakshindaAslam** [comment]
Included in #58814
