### ISSUE TITLE
Discovery - Understand calculations behind metrics in DOMO

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#56644]
## Issue Description
In order to establish baselines and measure performance against our product goals, we need to understand how the current metrics are being calculated on DOMO dashboard.

The scope of this ticket is to understand the calculations behind the following metrics:
- number of sessions to complete the form
- satisfaction score
- Review the existing list for other metrics that need this discovery

---
## Tasks
- [ ] Go to analytic office hours
- [ ] TBD

## Acceptance Criteria
- [ ] What is the data set for these metrics? What is being excluded, included
- [ ] Calculation for the metric
- [ ] What related data points might be available for metrics
- [ ] Other insights
- [ ] Recommendations on improving what is being measured

 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
cc @Nyanteea @navaeddie

**Comment by Nyanteea** [comment]
@navaeddie @lydiahooper

**Comment by Nyanteea** [comment]
![Screenshot 2023-04-17 at 1.54.32 PM.png](https://images.zenhubusercontent.com/63e51eafcf2f21b449885353/8dda115b-291c-4348-a274-943a006b7afd)

**Comment by Nyanteea** [comment]
Update: Learnings from Analytics OH

1. Sessions is defined by Platform [here ](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/metrics-and-dimensions) as :
"Total number of visits. Sessions records each time someone has started/ended a visit to the site. 30 minutes of inactivity will also cause a session to record.

- Example: A veteran visits the site, looks at a few pages, closes the site. The veteran takes a lunch break and returns to the site again after their lunch break. Sessions = 2

- Example: A veteran visits the site, has been inactive for 30 minutes while keeping the site open, comes back at minute. Sessions = 2

2.

**Comment by Nyanteea** [comment]
This ticket was left open as several questions remained unanswered  and it is unclear whether new tickets are needed:
1) What is the data set for these metrics? What is being excluded, included -- we learned some of how these metrics are being tracked however triggers are embedded in the front end and within components. Depending on the level of understanding we need, we would have to use front end resources to better understand tracking

2) We did not learn why exit rates only include "required pages" and which pages are classified as "required"

**Comment by RakshindaAslam** [comment]
Create a new ticket for outstanding questions

**Comment by Nyanteea** [comment]
CREATE ANALYTICS TICKET REQUESTING ALL STEPS
