### ISSUE TITLE
Present findings to OCTO at Platform Office Hours

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#56641]
## User Story
As a Governance team member, I want to present my research findings to OCTO so that OCTO can help guide Governance towards building value into the Collaboration Cycle. 

Assignee: @sterkenburgsara 
Peer Reviewer: @shiragoodman 

## Description
In ticket #54679 we synthesized and analyzed the findings from our Collaboration Cycle dashboard research study. We now must present our findings to OCTO. We are hopeful that our research findings will help guide future iterations of either the Collaboration Cycle or the Collaboration Cycle dashboard so that we may continue to provide value to OCTO-DE.

## Impacted Artifacts
* [Domo collab cycle dashboard](https://va-gov.domo.com/page/1340527018)
* Team survey synthesis [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1682433356327/f5d87406f5d940b0384c29a9e5cc6a4424d31214?sender=uf94a77a19aaf687331c09367)

## Tasks
- [x] Schedule presentation following the [Platform Crew Office Hours](https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours) guidance for **May 16th Platform Office Hours meeting**
- [x] Put together slide presentation following the [Discovery Research Readout](https://vfs.atlassian.net/wiki/spaces/AP/pages/2037448917/Discovery+Research+Readout) guidance: [slide deck here](https://docs.google.com/presentation/d/16w58NffkHQ4vcSW7rwHcwGsGXGbpVL9OtLA82WMSTNM/edit?usp=sharing)
- [x] Sync with peer-reviewer on presentation before Platform Office Hours take place (**scheduled for 5/15**)

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have presented our research findings to OCTO at Platform Office Hours
- [x] We have received guidance and/or direction from OCTO on their Collaboration Cycle and/or Collaboration Cycle dashboard priorities

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by sterkenburgsara** [comment]
Per updates from @jwoodman5 in today's standup, office hours on May 2nd are being repurposed for a celebration of EKS migration. We will bump out our planned presentation to the following week (May 9th).

**Comment by sterkenburgsara** [comment]
update: EKS migration celebration has been bumped to May 9th, which pushes us back to May 16th on this.

**Comment by shiragoodman** [comment]
thanks for following up on this @sterkenburgsara ! Bummer our findings won't be shared for another 2 weeks, but I am glad I get to be involved. I still haven't reviewed the responses or your synthesized findings, but I'm looking forward to it! Please let me know if there's anything concerning you want to discuss prior to sharing with OCTO.

also please update the tasks above to reflect the new date. thank you!

**Comment by sterkenburgsara** [comment]
Update: moving into the next sprint to present at platform office hours next Tuesday, May 16.

**Comment by sterkenburgsara** [comment]
Per sprint planning meeting, will sync with Shira on Monday 5/15 on Domo dashboard presentation for OCTO office hours before presenting on Tuesday.

**Comment by sterkenburgsara** [comment]
Update: presented research readout on 5/16 during platform office hours and got approval to move forward with implementing priority recommendations (pending PO approval). Will move "not currently actionable" findings to backlog for further solutioning. // cc @shiragoodman
