### ISSUE TITLE
Translate core pension "get benefit" content into Spanish

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#56657]
## Story

As a Veteran with limited English proficiency, I need the core benefit information for VA pension in my primary language.

We are starting with 2 pension pages for Spanish translation:

- [Eligibility for Veterans Pension](https://www.va.gov/pension/eligibility/)
- [How to apply for a VA pension as a Veteran](https://www.va.gov/pension/how-to-apply/)
- [VA Survivors Pension](https://www.va.gov/pension/survivors-pension/)

## Tasks

- [x] Send a word count and links to pages to State Department for estimate (Ana)
- [x] Prep content for translation (Ana)
- [x] Send content to translators (Ana)

## Acceptance criteria

- [x] Pension content sent to State Department

**Comment by RLHecht** [comment]
@ABeltran77 For some reason this isn't showing up under tickets you're assigned to on my board so I'm tagging you here as well so you'll see it. I'm going to post the meta descriptions for you from the Drupal pages so you'll have for each page.

**Comment by ABeltran77** [comment]
Ok!

**Comment by ABeltran77** [comment]
Here are the following pages:

- Eligibility for Veterans Pension
- How to apply for a VA pension as a Veteran
- VA Survivors Pension


[Eligibility page_pension_SP.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11319390/Eligibility.page_pension_SP.docx)

[How to apply for a VA pension as a Veteran_SP.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11319393/How.to.apply.for.a.VA.pension.as.a.Veteran_SP.docx)

[VA Survivors Pension_SP.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11319396/VA.Survivors.Pension_SP.docx)

**Comment by ABeltran77** [comment]
Updated:

[Eligibility page_pension_SP.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11325155/Eligibility.page_pension_SP.docx)

[How to apply for a VA pension as a Veteran_SP.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11325145/How.to.apply.for.a.VA.pension.as.a.Veteran_SP.docx)
ge_pension_SP.docx)

[VA Survivors Pension_SP.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11325152/VA.Survivors.Pension_SP.docx)

**Comment by RLHecht** [comment]
Thanks @ABeltran77 I made a few comments to each of these but they look good! Can you please accept all changes and send an email to the State Department through your VA email? You can give her the word counts for each of these pages and let her know that these are the first 3 pages of core content we are translating from the Pension benefit hub. Thank you!
[https://app.zenhub.com/files/133843125/c7cf8642-70e2-49fc-9235-3b86216c841b/download](https://app.zenhub.com/files/133843125/c7cf8642-70e2-49fc-9235-3b86216c841b/download)

[https://app.zenhub.com/files/133843125/aa443da8-790a-483e-a91a-719cc79c4f5c/download](https://app.zenhub.com/files/133843125/aa443da8-790a-483e-a91a-719cc79c4f5c/download)

[https://app.zenhub.com/files/133843125/26413a49-dcf2-4b36-bdd4-3a2aaefe44b3/download](https://app.zenhub.com/files/133843125/26413a49-dcf2-4b36-bdd4-3a2aaefe44b3/download)

**Comment by RLHecht** [comment]
This content is with the state department. Will open a new ticket when we get content back.
