### ISSUE TITLE
[BE] Update End of Day Summary Reporting Script

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#56659]
## Description
Once vets-api in production rolled out to EKS, update the [script](https://github.com/department-of-veterans-affairs/checkin-devops/blob/master/scripts/summary.py)  with metrics & env tag as per the [ticket](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/55916)
 
## Tasks
- [ ] [BE] **Update the script**
- [ ] [BE] **Confirm changes deployed**
- [ ] [BE] **Prod support channel notified with updates from vets-api EKS environment**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
