### ISSUE TITLE
Conduct mini-session to discuss learnings from Research Initiative

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#56665]
## Purpose
Follow-up to this ticket: https://app.zenhub.com/workspaces/platform-service-design-61bcbaf174a70100154e22e7/issues/gh/department-of-veterans-affairs/va.gov-team/54492

Ideas collected in [Thinkpiece](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2486140984/Thinkpiece+How+to+collaborate+on+research+effectively+with+other+Platform+teams).

## Tasks
- [x] Schedule workshop
- [x] Prep board with new feedback / considerations
- [x] Conduct session to review mural and discuss thinkpiece

## Acceptance Criteria
- [x] Mini workshop w/ mural is complete and next steps are in order
