### ISSUE TITLE
Bug Fix - Future Date of Claim(DOC) being established for Reservists and National Guards

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#56674]
## Issue Description
Some claims are being populated with a future Date of Claim(DOC) when the user is entering their Contract End Date instead of active Service Exit Date

How to replicate: 
1. Enter Service Type as Reservist or National Guards and enter future Service Exit Date > 180 days
2. Submit the claim with other fields populated
3. The claim gets established with this future Service Exit Date as Date of Claim.

The discovery has identified that the reservists and national guards are able to submit claims with > 180 days exit date. The scope of this ticket is to:
1 . Provide clarity that the value expected here is Active Service exit date and not the Contract End Date
2. Put in validation so that the user is not able to move forward with a date > 180 days

The validation exemption can be found on line 448 in `src/applications/disability-benefits/all-claims/validations.js`, `vets-website` repo
```
  } else if (
    +isBDD &&
    !isReserves &&
    moment(dateString).isAfter(moment().add(180, 'days'))
  ) {
...
```

--
## Need to know
 -- [Slack thread](https://dsva.slack.com/archives/C8R3JS8BU/p1683646680437329?thread_ts=1683565044.419109&cid=C8R3JS8BU)
From: Cooper, Barrett E., VBAVACO
Sent: Wednesday, February 3, 2021 9:16 AM
Subject: Date of Contention
Is it possible to make the date of contention for BDD and BDD-Excluded claims submitted on VA.gov as the date of claim which is the day after discharge? The field is reporting VA.gov is entering the date the claim was submitted. We are required to enter the contention with the date of the day after discharge.

-- Notes from discussion with VBA stakeholders(Alejandro) on[ May 18th](https://docs.google.com/document/d/1H9xgYJ-oAj3AWKtnzZxOI3xv_ayQKju03rkc36Emax8/edit#)
- Prevent reservists and national guards from entering a date > 180 days
---
## Tasks
- [ ] 

## Acceptance Criteria
- [ ] Form does not accept > 180 days as service exit date for reservists and national guards
- [ ] Updated content clearly explains what is expected in this field.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
@lydiahooper - do we need a separate content ticket for this?

**Comment by lydiahooper** [comment]
@RakshindaAslam I don't think so, but we can create a design ticket for mocking up UI change for this page.

**Comment by tblackwe** [comment]
Assessment work already completed, progressing ticket

**Comment by alatempa24** [comment]
Fix to this bug : https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/60313

**Comment by RakshindaAslam** [comment]
Being addressed in #60313

**Comment by RakshindaAslam** [comment]
Closed with  #60313
