### ISSUE TITLE
Create visual workflow for how Portal is intended to work

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#56687]
## Purpose
Create visual map in Mural of how we think this process can/should work

Ticket work and deliverables [here](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2605547641/Input+paths+onramps+for+Portal)

## Tasks
- [x] What are the main paths for input into Portal?
- [x] Where are these paths ideally located (engaged with)?
- [x] Draft flow for someone submitting through the Platform Doc site
- [x] Draft flow for someone submitting through the Slack Support workflow

## Acceptance Criteria
- [x] A visual flow represents how a user travels from ideation, to the main engagement points, through the feedback portal, to confirmation of submission.

**Comment by steel36** [comment]
Reviewed and commented.
