### ISSUE TITLE
Update eligibility info on Veterans asbestos exposure page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#56688]
## Issue Description

As part of the annual disability audit work, we need to make changes to the [Veterans asbestos exposure](https://www.va.gov/disability/eligibility/hazardous-materials-exposure/asbestos/) based on SME feedback.

The content to change is the bullets in the blue eligibility box.

![Screen Shot 2023-04-11 at 1.26.00 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/d406d361-b14c-4b16-ab55-6aeca0d4a024)

From Paul Shute: 
Because a dishonorable discharge impacts all types of compensation claims, this doesn't need to be part of this specific eligibility criteria. Additionally, the criteria that needs to be met in addition to being exposed to asbestos during military service is that the Veteran now has a disability related to asbestos exposure. 

I recommend structuring it like the Agent Orange page: 
**Both of these must be true:** 
- You have a health condition that’s caused by exposure to Agent Orange, **and** 
- You served in a location that exposed you to Agent Orange 

I think it might make more sense to include the character of discharge information on the basic eligibility page or elsewhere and leave the exposure specific pages to focus on the criteria specific to those type of claims. 

## Tasks
- [x] Update bullets in eligibility box
- [x] Review (Laura)
- [x] Copyedit (Megan)
- [x] Send preview to stakeholder (Megan)
- [x] Publish (Megan)
- [x] Notify stakeholder that changes are live (Megan)

## Acceptance Criteria
- [x] Changes are live on the page

**Comment by katherine-fung** [comment]
Hi @laurwill, I updated the bullet points here. 

This page is ready for review:  

http://preview-prod.vfs.va.gov/preview?nodeId=882

**Comment by laurwill** [comment]
Looks good @katherine-fung ! 

@megzehn , this one is ready for copyedit.

**Comment by RLHecht** [comment]
These changes are live. Closing ticket!
