### ISSUE TITLE
BE | Profile | Direct Deposit | Configure and Test Metrics and Error Logging

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#56706]
## Background
Direct deposit information is now connected to Lighthouse in the staging environment.  Add error handling and logging hooks to direct deposit service layer.

## Tasks
- [x] Add hooks for error logging.
- [x] Add hooks for metric logging.
  
## Acceptance Criteria
- [x] Verify metrics are in Datadog
- [x] Verify errors are logged to Sentry
