### ISSUE TITLE
Discovery: Explore approaches to create a Parameterized Workflow for Preview Environments

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#56718]
# Description
The objective of this discovery phase is to research and analyze the requirements and technical aspects needed to create a parameterized workflow for preview environment creation. This will involve identifying the changes required in the existing GitHub Action (GHA) workflows, understanding how to accept user inputs and provide default values, and evaluating the updates needed in subsequent workflows for using environment variables instead of hardcoded values.

# Tasks
- [x] Investigate the current GHA workflows to understand their structure and dependencies.
- [x] Research best practices for accepting user inputs and providing default values in GHA workflows.
- [x] Identify the specific configuration parameters that need to be customizable, and define their default values.
- [x] Evaluate the changes needed in the starting workflow to pass values along through GitHub as environment variables.
- [x] Assess the required updates in the subsequent workflows to replace hardcoded values with environment variables.
- [x] Explore potential challenges and limitations associated with implementing parameterized workflows.
- [x] Are there other methods for this that should be explored?
- [x] Is this list still the complete list of customizations that we intend to support?
     * Specify Hosting Environment
     * Specify Repository Settings
     * Specify Test Data
     * Duration Settings (Not needed right now)
     * Authorization Settings (Not needed right now)

# Acceptance Criteria
- [x] A comprehensive understanding of the existing GHA workflows and their dependencies has been established.
- [x] The specific configuration parameters and their default values that need to be customizable have been identified.
- [x] Best practices for accepting user inputs and providing default values in GHA workflows have been researched.
- [x] The changes needed in the starting workflow and subsequent workflows for using environment variables have been evaluated.
- [x] Potential challenges and limitations associated with implementing parameterized workflows have been identified.
- [x] A documented summary of the research findings is provided, which will serve as a basis for the implementation phase of the epic.
- [x] A review of the customizations to be supported has been conducted to confirm the completeness of the list.
- [x] A documented summary of the research findings is provided, which will serve as a basis for the implementation phase of the epic.

**Comment by CBonade** [comment]
I made a test workflow to test out this concept. The long and short of it is, we can define parameters and set a workflow trigger that will allow the workflow to be manually run whenever the user wants. Whatever parameters we want to have set will be able to be defined in the box pictured here ![image.png](https://images.zenhubusercontent.com/60aa993146d844d86f494162/8455480b-dff8-4f79-9599-bae5f74eeb84). This can be integrated into our existing preview environment workflow and the value that is used can be decided upon based on which method the workflow was triggered by.

Decisions to be made: 
1) Do we want to allow these custom workflows to be triggered from all repositories or singular source.
2) As these would be triggered from an external source and not attached to a PR, we need to decide where the user would get their link to the PE from.

Things that will need to be done to make this work:
1) `workflow_dispatch` trigger and inputs/default values will need to be added to our existing PE workflow(s).
2) The logic set in place that decides what variables get set for the PE will need additional conditional cases to cover a manually triggered workflow.

This really is a low-lift for us, with the only potential complication being finding a home for the PE to live for the user to be able to click on. There is a master list of deployments for the repository, so this would probably suffice for that purpose, we'd just have to clearly document it.

**Comment by CBonade** [comment]
After a chat with Joe, good starter fields that are easy to implement will be:

vets-website branch
vets-api branch
content-build branch
expiration time

Ones we'll need to do some further discovery on:

Drupal cache version: the initial way we were going to approach this was to set it during the building of content build - which we are no longer doing. This may not be possible with the method we are currently using.

Specify test data: Where does this data get inserted? vets-api? other source? This may require a simultaneous build/rebuild of vets-api's image but i need some more details to fully understand what we're doing here.

Specify user and services on/off - I don't know enough about these to offer up how we'd handle them. Need to discuss this one a well.

**Comment by CBonade** [comment]
Documenting this syntax for making these options drop down compatible:
```choice:
        type: choice
        description: Make a choice
        options:
        - foo
        - bar
        - baz```

We won't be able to dynamically populate these (well, we could kinda simulate it like we did with the product directory yaml), but the other options such as data source can be stuck in a dropdown menu.

**Comment by CBonade** [comment]
Per discussions the last couple days, here's our current list of params we want to go with for the mvp:

vets-website branch
vets-api branch
expiration time

Future additions post-MVP:
content-build branch (requires a rework of how we are building the front-end image)
Data source  (MVP will only support mockdata)
Authorization settings (whole other can of worms we haven't even started exploring how we can handle).

Features we don't think are relevant:
Hosting environment (this doesn't seem to apply to spinning up PEs at all)

**Comment by pjhill** [comment]
@CBonade -- That list looks good. Thanks for attaching the reasoning to each.

**Comment by CBonade** [comment]
https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/57047 New ticket to implement everything we've discussed. This one's ready to close.

**Comment by pjhill** [comment]
Thanks for finishing out the discovery with an implementation ticket!
