### ISSUE TITLE
Feature: Create a Parameterized Workflow for Preview Environment Creation

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#56715]
# Description
As the MVP reaches completion, the next step is to enhance the preview environment creation process by introducing configurable parameters. This will enable users to create preview environments with varying configurations, such as different versions of content-build and vets-website builds, authentication pointing at the staging lower, and using alternate branches for supplemental repositories. By providing default values and supporting user inputs for these parameters, we will make the process more flexible, accommodating various team requirements and improving the overall user experience.

# User Story
"As a user, I want to create a preview environment with custom configurations so that I can test and validate various scenarios with greater flexibility and control."

# Acceptance Criteria
- [ ] Convert the existing GHA workflows to accept user inputs via parameters while providing default values.
- [ ] Update the starting workflow to pass values along through GitHub as environment variables.
- [ ] Adapt the subsequent workflows in the process to use environment variables instead of hardcoded values.
- [ ] Ensure that when users don't specify a value for a given parameter, the existing defaults from the MVP are used.
- [ ] Verify the successful creation of preview environments with custom configurations, as specified by the user inputs.

**Comment by JoeTice** [comment]
These tickets are OBE as our approach is shifting, closing these tickets to reflect that.
