### ISSUE TITLE
Updates to Get a Premium MHV account page

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#56724]
## Issue Description
Ngozi sent us updated info for the Get a Premium MHV page. We recently removed an outdated paper form from this page, but the online option needs updates as well. This will also include adding Login.gov as a sign-in option, so placing this in the Login.gov epic.

Materials from Ngozi:
[Most recent version of MHV page](https://app.zenhub.com/files/133843125/49ac3b19-f275-42a4-95d2-1facc7e25fd9/download)
[Suggested changes to VA.gov page](https://app.zenhub.com/files/133843125/b2c8ef2d-e4b9-4f93-b035-a173b47d6c08/download)

---
## Tasks
- [ ] Update Ngozi's version for VA.gov style (Aliyah)
- [ ] Review (Laura)
- [ ] Share with Ngozi and Carnetta 
- [ ] Copyedit and publish (Megan)

## Acceptance Criteria
- [ ] Page is updated with current info

**Comment by aliyahblackmore** [comment]
Passed a word document with my review to Laura - via Slack.

**Comment by aliyahblackmore** [comment]
Laura chatted with Carnetta re: this last week and will have her review some preliminary changes to this page.

**Comment by aliyahblackmore** [comment]
@laurwill as we chatted, thanks for reviewing and adding in the video visit option. I did another review of this page just to confirm that all of Ngozi's updates are included. 

I made one adjustment to the page intro to reflect that the secure video visit option.

This is ready for Ngozi to review. Let me know if you'd like to review again, if not I'll send over the email to Ngozi.

**Comment by aliyahblackmore** [comment]
@laurwill As we confirmed, I just sent over the email to Ngozi with the preview link of the Get a Premium MHV account page. 

Also noting a small adjustment that I made to the page intro: I changed the page intro to match the change from "video visit" to "video call" later on the page.

**Comment by aliyahblackmore** [comment]
**Update here:** 

**8/29** - Ngozi shared her feedback on the page changes in this word document 
[Get a Premium My HealtheVet account - NA(1).docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12490108/Get.a.Premium.My.HealtheVet.account.-.NA.1.docx)

I'll plan to review those changes next week.

**Comment by aliyahblackmore** [comment]
Hi @laurwill - I made some additional adjustments to the Get a Premium MHV account page content based on Ngozi’s feedback in her word document. Any comments that need your attention are in green. 

This is ready for you to review.
[Get a Premium My HealtheVet account - NA_AB 8.31.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12501442/Get.a.Premium.My.HealtheVet.account.-.NA_AB.8.31.docx)

- I have one clarifying question about Premium accounts for Ngozi re: if someone doesn’t have a “basic” MHV account. 

- When we send this back to her, we can also ask the question that you flagged about whether, at this time, it would be best to link to the Get a Premium MHV account page from the [Verifying page](https://www.va.gov/resources/verifying-your-identity-on-vagov/) in the question " from the question “Can I verifying my identity in person?"

**Comment by laurwill** [comment]
Update here: Carnetta suggested additional updates to this page, Danielle and I iterated on it, and the most recent version is now in the Drupal node. We'll wait for Danielle to confirm that we can publish this.

**Comment by megzehn** [comment]
Thanks @laurwill! Confirming I reviewed and published the page!

**Comment by laurwill** [comment]
Thanks so much @megzehn ! 
@strelichl tracking next steps before we can close this ticket:
- [ ] Request redirect — [PW ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73550)
- [ ] Audit site for links to old page and replace with new page URL — **can you do this step?** 
- [ ] Once redirect is live, archive old page

**Comment by laurwill** [comment]
Update: We updated this page and changed the H1 yet again!

@megzehn could you copyedit the new version in the new node: http://preview-prod.vfs.va.gov/preview?nodeId=69150

Here's the new redirect request with PW: https://github.com/department-of-veterans-affairs/va.gov-team/issues/83809

**Comment by megzehn** [comment]
Hi @laurwill, 

I reviewed this page, and it looks good to go. 

One thing: Could you confirm that the CTA link we want in Step 2, **Sign in to VA.gov**,  is https://www.va.gov/my-health ? I think that seems right for this page, but just wanted to confirm since it's the same link we have for [Go to My HealtheVet on VA.gov](https://www.va.gov/my-health). Thanks!

**Comment by laurwill** [comment]
Thanks so much @megzehn ! And yes, confirming that we're using the My Health landing page link in the "sign in" step because we want the person to land on that page after signing in.

**Comment by laurwill** [comment]
@megzehn Danielle confirmed we can publish this page on Tuesday, and I notified Carnetta of this plan. After you confirm the page is live, could you post in the [redirect ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83809) for Kristin and Fran to go ahead with the redirect? Thank you!

cc @DanielleThierryUSDSVA

**Comment by laurwill** [comment]
Also @megzehn noting I made a couple tweaks after you copyedited, so might want to do a quick compare revisions.

**Comment by laurwill** [comment]
Updates: Megan published this page and PW implemented the redirect. 

But per a [Slack conversation on Thursday](https://dsva.slack.com/archives/C0581MN69TJ/p1717112821124529?thread_ts=1717087798.375779&cid=C0581MN69TJ), one of the underlying assumptions of this page (that Veterans must follow all of these steps to access any part of MHV on VA.gov) is incorrect. We'll need to update the page again. Leaving this ticket open to track.
