### ISSUE TITLE
Feature: Create Test Harness for Preview Environments

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#56727]
# Description
The objective of this epic is to improve the testing paradigm in preview environments by creating test harnesses that integrate fake external services backed by user-controlled datasets. This will empower users to create custom data for fake external services, enabling them to demo or test new business scenarios without relying on external service lower environments. The test harnesses will be initiated by selecting one or two high-value external services, creating a mock service that adheres to the production service schema, setting up an RDBMS to provide data, and implementing a way for users to CREATE, READ, UPDATE, and DELETE data in the backend.

# User Story
"As a user, I want to utilize test harnesses in preview environments so that I can have better control over the data used in fake external services and test new business scenarios more effectively."

# Acceptance Criteria
- [ ] Identify one or two high-value external services to begin creating test harnesses.
- [ ] Develop a mock service that responds using the same schema as the selected production services.
- [ ] Implement an RDBMS to provide data for the fake external services.
- [ ] Provide a way for users to CREATE, READ, UPDATE, and DELETE data in the backend.
- [ ] Determine whether a new test harness needs to be spun up for each team or user.
- [ ] Integrate the test harnesses into the preview environments, ensuring seamless functionality.
- [ ] Verify that users can successfully demo or test new business scenarios using the test harnesses and user-controlled datasets.

**Comment by JoeTice** [comment]
This feature has been deprioritized from Post-MVP improvements that we were trying to get included in MVP

**Comment by JoeTice** [comment]
These tickets are OBE as our approach is shifting, closing these tickets to reflect that.
