### ISSUE TITLE
Review MST fact sheet to determine missing info on VA.gov

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#56721]
## Issue Description

The MST Path Forward work group sent us a fact sheet and asked us to add any missing information to VA.gov. We should compare the sheet to our [Military sexual trauma](https://www.va.gov/health-care/health-needs-conditions/military-sexual-trauma/) page as well as our [VA claim exam](https://www.va.gov/disability/va-claim-exam/) page. 

Fact sheet to review: [https://app.zenhub.com/files/133843125/05f2990f-dc69-4766-831c-b692b0409d4f/download](https://app.zenhub.com/files/133843125/05f2990f-dc69-4766-831c-b692b0409d4f/download)

## Tasks
- [x] Assess fact sheet (Katherine)
- [x] Update drupal pages (Katherine)
- [x] Review (Laura)
- [x] Copyedit (Megan)
- [x] Send to stakeholders for review (Katherine)
- [x] Publish (Megan)

## Acceptance Criteria
- [ ] Site is updated with info from fact sheet

**Comment by katherine-fung** [comment]
Hi @DanielleThierryUSDSVA, 

I've assessed the fact sheet. I believe that we need to add information to va.gov about filing a disability claim for a condition related to MST. 

1. The PDF includes information about types of compensation that we may want to add to VA.gov. There's also information about claim exams and support that's available during the claims process. 

For now, I've added this information to the existing section on the current page "Can I get disability compensation (monthly payments) or other benefits from VA?"

Do you think this section should be its own separate page? I think under the criteria for placing content, this should be an R&S page. But I want to check with you/see if there's a reason we should keep it together on the current page.  

Inline revisions to current page: https://prod.cms.va.gov/node/24/revisions/view/718846/763610/visual_inline 

2. The PDF also includes information about evidence needed for your claim. I believe this should go in a new accordion on the "evidence needed" page. I created the accordion. The information we have about filing a claim for a condition related to MST will link to the evidence needed page. 

Preview of evidence needed page: 
https://prod.cms.va.gov/node/907/revisions/763269/view

**Comment by katherine-fung** [comment]
I should also point out that the PDF offers a definition of MST with examples. This felt important to migrate, but I don't think the current placement of the examples (after the blue box) on the draft works. Laura pointed out that having the definition may be more important for the disability claim process, than on a page about treatment options (there are no eligibility requirements to get treatment).

**Comment by katherine-fung** [comment]
Hi @DanielleThierryUSDSVA, 

I created the MST page and I wanted to show it to you before diving into changes on the 3 other pages. 

MST and disability compensation draft: 
http://preview-prod.vfs.va.gov/preview?nodeId=55676

I have a few questions and notes here: 

1/ For the "About MST and when to file" section, I tried breaking this up into an informational alert directed at people who may have filed before August 2018, and a separate H2 "About MST." Do you think this works, or does the information work better as 1 section? 

2/ In the section "How to file a disability compensation claim," I used the H3 "If this is the first time you're filing your claim." I was looking for the right language to indicate first time filing a claim for the issue they're claiming, and landed on this after debating "... filing a claim" and "...filing a claim for this issue."  

3/ I have the sections "Getting support during the claims process" and "Getting support and care for MST." 

The section "Getting support during the claims process" explains what a claim exam is, and that a Veteran can choose an provider of a specific gender. I wanted to have this section address claim exams, and broader support during the claims process (aka the support and treatment options) but the latter sounds repetitive given the next section "Getting support and care for MST." 

I've left just the claim exam info in the section about the claims process, and put information about treatment and support in "Getting support and care for MST." Do you think this works, or should we combine the 2 sections?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @katherine-fung. Thanks for putting this page together! I made a few edits as you continue working on this.

- We know that people often skip alerts if we use them too frequently. This isn't a time-sensitive issue where they need to file a claim by a certain time, so I would put the info in the how to file section + a mention in the when to file section.
- We want to stay specific to claims rather than having a general "About MST" section, so I've adjusted that H2 and added info about when to file in that section. 
- I was playing around with removing the examples of MST in that top section because that's not the focus of the page and they add more need to scroll. We also know from conversations with social workers about harassment that sometimes specific examples can be traumatizing. I wonder if we might add an accordion with "Review examples of MST" or something here? Give it some thought and let me know what you think.
- I think "If this is the first time you're filing a claim for this issue" works well. "If you haven't filed a claim for this issue before" might also work, though I like the positive framing of "first time."
- We need to break up the content in the evidence section a bit more. And we need to break up the lists so no list is more than 7 bullets. You'll see that I started doing that.
- I like combining the support section. Let me know what you think of how I've started to do that!

**Comment by katherine-fung** [comment]
@DanielleThierryUSDSVA, thanks for this helpful feedback! I've updated the page and will pass it, along with the other pages we're updating, to Laura for review. I just wanted to respond to the feedback in this ticket: 

1/ Noted about alerts. 
2/ Thanks for adjusting the first H2 and the content within it. 
3/ Thank you for pointing that out about the examples of MST. I agree - it feels jarring and traumatizing to read specific examples. An accordion listing the examples could work, especially if for some reason, the SMEs require us to list the examples. If we don't have to use the examples, I wonder we can use some alternative, less explicit language. I've suggested this in the preview (I'll ask Laura to review):

> "There are many different types of MST. These experiences can be physical or non-physical. They can include behavior that occurred without your consent. They can also include behavior that you found threatening, or made you uncomfortable."

4/5/6 - Thank you for this! I've added information about MST coordinators to the support section. I also added in that you may be able to get care for MST even if you're not eligible for other VA services (this is from the MST health page).

**Comment by katherine-fung** [comment]
@laurwill - 

These pages are ready for review: 

Military sexual trauma and disability compensation
http://preview-prod.vfs.va.gov/preview?nodeId=55676

Evidence needed for your disability claim
http://preview-prod.vfs.va.gov/preview?nodeId=907

- I added a link to the section "Additional evidence for certain issues," above the accordions. 

Eligibility for VA disability benefits
http://preview-prod.vfs.va.gov/preview?nodeId=871

- I added a bullet about health conditions related to MST.

Military sexual trauma (MST) 
http://preview-prod.vfs.va.gov/preview?nodeId=24

- I made minor tweaks to this existing page for style.

**Comment by katherine-fung** [comment]
I sent these pages to the SME for review.

**Comment by katherine-fung** [comment]
The team sent us feedback on our draft. 

I’ve incorporated their feedback on these sections: 
•	“Evidence we’ll need for your claim” 
•	“How to get support” 

I’m going to email them to discuss these pieces of feedback with them some more:

1.	Page introduction and "When to file a disability claim related to MST" section – Their team wants to reverse the order of the content in these two sections at the top of the page. The feedback bumps up the more detailed information defining MST and letting people they can request a decision review. 

We know that people often skip the introduction text on pages, and go straight to the first section (in this case, that’s “When to file a claim for a condition related to MST”). I'm going to let them know that we usually keep the introduction text brief and go into further details below it. On this page, we don’t want people to skip this important information about when they can file, or how to get a review of their previous claim, so we’d like to keep the introduction and “When to file a claim for a condition related to MST” sections as they are. 

2.	The feedback from the team adds “VBA” to the phrase “MST coordinator.” I'd like to ask if there's a reason we need to specify to Veterans that MST coordinators are part of VBA. We usually try to avoid acronyms unless we absolutely need them (it can be confusing for Veterans to see a string of letters – VBA MST - and think about what they mean). Does the MST coordinator’s agency matter from a Veteran’s perspective?

(Also, the very last sentence of draft doc says VHA instead of VBA - “Every VA facility has a Veterans Health Administration (VHA) MST Coordinator who can help you access care.” Noting here that we don’t specify VBA or VHA MST coordinator on the live “Military sexual trauma” page on va.gov.)

**Comment by DanielleThierryUSDSVA** [comment]
@katherine-fung Please just let them know that we do not include VBA or VHA, rather than asking that one as a question. We take a one-VA approach. Veterans don't need to understand how VA is organized. Thanks!

**Comment by katherine-fung** [comment]
Thank you @DanielleThierryUSDSVA! I'll include that in my email to them. 

Also noting one other change: 

They're requesting that we say, "You can submit evidence that shows symptoms of a mental health disorder like:" (bulleted list that follows includes: anxiety, feeling depressed, feeling disconnected from others, panic attacks, suicidal thoughts, uncontrollable worries) 

I discussed the word "disorders" with @megzehn. I'm going to respond that we'll say, "You can submit evidence that shows symptoms of a mental health condition..." instead. This change aligns with how we talk about mental health elsewhere on va.gov.

**Comment by katherine-fung** [comment]
Hi @megzehn, 

This page is ready for a final copy edit: 

Military sexual trauma and disability compensation
http://preview-prod.vfs.va.gov/preview?nodeId=55676 

Once it's ready, you can publish. 

The changes on these pages are also ready to publish. You copy edited these in May: 

Evidence needed for your disability claim
http://preview-prod.vfs.va.gov/preview?nodeId=907

Eligibility for VA disability benefits
http://preview-prod.vfs.va.gov/preview?nodeId=871

Military sexual trauma (MST)
http://preview-prod.vfs.va.gov/preview?nodeId=24

Thank you!!

**Comment by katherine-fung** [comment]
I'm meeting with the stakeholders tomorrow, 7/19, to discuss this ticket.

**Comment by katherine-fung** [comment]
Hi @DanielleThierryUSDSVA. I met with stakeholders to discuss the workgroup's feedback on the changes we proposed. They came back with this feedback: 

1. The group insists we say VBA/VHA (or Veterans Benefits Administration/Veterans Health Administration), before "MST coordinator." They don't want us to say "MST coordinator for benefits" or "MST coordinator for healthcare." They only want us to use the agency name. This is out of concern that a Veteran will ask for a certain type of MST coordinator, and whoever they're speaking to might get confused and think there's a different type of MST coordinator they need to find. 
 
In the draft, I updated instances of "MST coordinator" to say "Veterans Benefits Administration MST coordinator" or  "Veterans Health Administration MST coordinator." i.e. 
![Screenshot (222).png](https://images.zenhubusercontent.com/627bd98be9182e080ddd515b/07604c25-a3b1-4aa9-a7d3-93bb574c5e21)


2.   The workgroup rejected "mental health conditions," and says we must say "mental health disorders." The stakeholders and I discussed the possibility of getting rid of the phrase altogether, and simply saying: 

> You can submit evidence that shows symptoms like these:   

The stakeholders will bring this to the workgroup and get back to us.

**Comment by katherine-fung** [comment]
Hi @megzehn, 

These 4 pages are finally ready for copy edit and publishing. 

A few things to note on the MST and disability compensation page (1st link): 

- We spelled out the agency names of VBA and VHA on this page. 
- We removed mentions of an August 2018 date (you should request a decision review if you filed a claim before August 2018 and VA denied it) because the stakeholders said it wasn't accurate. 

Here are the 4 pages. You copy edited the last 3 pages in May, and I haven't made changes since then: 

Military sexual trauma and disability compensation
http://preview-prod.vfs.va.gov/preview?nodeId=55676


Evidence needed for your disability claim (I added MST info under "Additional evidence for certain issues")
http://preview-prod.vfs.va.gov/preview?nodeId=907

Eligibility for VA disability benefits (I added bullet point about MST)
http://preview-prod.vfs.va.gov/preview?nodeId=871

Military sexual trauma (MST) (I updated the disability comp section)
http://preview-prod.vfs.va.gov/preview?nodeId=24

**Comment by katherine-fung** [comment]
We're waiting for stakeholders to approve the "Veterans Benefits Administration MST coordinator" and "Veterans Health Administration MST coordinator."

**Comment by megzehn** [comment]
Confirming these are all published! Thank you, @katherine-fung! 

I will move this to validate and close out once I finish the post-publish steps for the R&S page.

**Comment by laurwill** [comment]
Thanks @megzehn and @katherine-fung ! I notified Ciena that these are live — Megan you can close once you do post-pub steps.

**Comment by megzehn** [comment]
Thanks, @katherine-fung!
