### ISSUE TITLE
Discovery: Explore how to create an EFS Hosted Persistent Volume for Preview Environments

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#56720]
# Description
The objective of this discovery phase is to research and analyze the requirements and technical aspects needed to create an EFS hosted persistent volume for preview environments. This will involve understanding the process of implementing an EFS volume in EKS, identifying the changes required in the Docker image and vets-website configuration, and evaluating the benefits of utilizing a persistent volume, such as reduced startup time and supporting tailored static content in preview environments.

# Tasks
- [x] Investigate the process of creating and implementing an EFS hosted persistent volume in EKS in the `vagov-staging` VPC where preview environments live.
- [x] Research best practices for configuring the Docker image to mount the EFS volume and setting up vets-website to use the mounted volume.
- [x] Identify the necessary steps to synchronize the static content build external to the preview environment creation process.
- [x] Explore the requirements and potential methods for implementing a startup script to mount a specific subdirectory containing the desired version of the content build.
- [x] Explore the requirements and potential methods for removing older versions of `content-build` when they become too stale

# Acceptance Criteria
- [x] A comprehensive understanding of the process of creating and implementing an EFS hosted persistent volume in EKS has been established.
- [x] Best practices for configuring the Docker image and vets-website to use the EFS volume have been researched.
- [x] The necessary steps to synchronize the static content build external to the preview environment creation process have been identified.
- [x] Potential methods for implementing a startup script to mount a specific subdirectory have been explored.
- [x] Potential methods for removing older versions of `content-build` when they are too stale has been explored and documented.
- [x] A documented summary of the research findings is provided, which will serve as a basis for the implementation phase of the epic.

**Comment by holdenhinkle** [comment]
An EFS (Elastic File System) Hosted Persistent Volume refers to a network-attached storage (NAS) solution provided by Amazon Web Services (AWS) for use with containerized workloads running on their Kubernetes-based platform, Amazon Elastic Kubernetes Service (EKS). A persistent volume is a storage resource that can outlive the life of a container or pod, providing a way to retain and share data between different containers, even if they are running on separate instances.

EFS is a managed file storage service that can automatically scale up and down according to the needs of the applications using it, providing high performance and durability. In the context of Kubernetes, an EFS Hosted Persistent Volume can be utilized as a backing store for Kubernetes Persistent Volumes (PV) and Persistent Volume Claims (PVC), enabling the sharing of data between multiple pods or containers across different nodes in a Kubernetes cluster.

To set up an EFS Hosted Persistent Volume, you would typically follow these steps:

Create an Amazon EFS file system in your AWS account.
Configure the necessary IAM roles and security groups to allow the EKS worker nodes to access the EFS file system.
Create a Kubernetes StorageClass that uses the EFS CSI (Container Storage Interface) driver, which enables EFS integration with Kubernetes.
Create a Kubernetes Persistent Volume (PV) that references the EFS file system and the StorageClass you created in step 3.
Create a Kubernetes Persistent Volume Claim (PVC) that binds to the Persistent Volume created in step 4.
Finally, deploy your application with a pod specification that includes the PVC as a mounted volume.
EFS Hosted Persistent Volumes provide a flexible and scalable storage solution for containerized workloads on AWS, making it an attractive choice for various use cases, such as content management systems, data analytics, and machine learning applications.

https://console.amazonaws-us-gov.com/efs/home?region=us-gov-west-1#/get-started

**Comment by holdenhinkle** [comment]
Task:
 # Investigate the process of creating and implementing an EFS hosted persistent volume in EKS in the vagov-staging VPC where preview environments live.

**Comment by holdenhinkle** [comment]
Task:
 # Research best practices for configuring the Docker image to mount the EFS volume and setting up vets-website to use the mounted volume.

**Comment by holdenhinkle** [comment]
Task:
 # Identify the necessary steps to synchronize the static content build external to the preview environment creation process.

**Comment by holdenhinkle** [comment]
Task:
 # Explore the requirements and potential methods for implementing a startup script to mount a specific subdirectory containing the desired version of the content build.

**Comment by holdenhinkle** [comment]
Task:
 # Explore the requirements and potential methods for removing older versions of content-build when they become too stale

**Comment by holdenhinkle** [comment]
You can create your own directories and store JSON blobs or other files within those directories when using Amazon EFS. EFS behaves like a network file system (NFS) that can be mounted to multiple instances or containers simultaneously, allowing you to read and write files as you would on any other file system.

To create directories and store JSON blobs in each directory, follow these steps:

1. Mount the EFS volume to your instance or container, as described in the previous answers.
2. Once the EFS volume is mounted, you can use standard file system commands and programming libraries to create directories, read, write, and delete files. For example, if you mounted the EFS volume at `/efs`, you could create a directory called `my_directory` and store a `JSON` blob as follows:
```bash
mkdir /efs/my_directory
echo '{ "key": "value" }' > /efs/my_directory/my_blob.json
```

3. You can also interact with the EFS volume programmatically using your preferred programming language's file I/O libraries, such as Node.js's `fs` module.

The EFS volume is shared across all instances or containers that have it mounted, so changes made to the files and directories will be visible to all of them. This can be beneficial for sharing configurations or data across your application, but you should also be aware of potential concurrency issues when multiple processes are accessing and modifying the same files simultaneously.

**Comment by pjhill** [comment]
Thanks for looking into all these aspects. I haven't digested all the analysis yet, but I think this goes a long way to helping us understand the capabilities/limitations and in being able to describe the implementation details for each aspect of what we need. Thanks!
