### ISSUE TITLE
Streamlined Waiver User Flow Planning & Design Ideation

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#56737]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [x] Meeting with SMEs on 4/17
- [x] Meeting with Platform Design team on 4/18
- [x] Based on convo with Platform: Continue Progress bar & conversational design work

## Acceptance Criteria
- [x] Make updates based on conversations with SMEs (no updates needed)
- [x] Make updates based on conversations with Design Platform (no updates needed)
- [x] Design ideation for Progress bar

**Comment by mgleo** [comment]
@HeatherRienks Ticket is now in Validate and new ticket is [#57386](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/57386)
