### ISSUE TITLE
[eFSR] Veteran Contact Information

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#56734]
## Issue Description
Update contaft information page so it takes user to new page for editing and back again when completed.
[UXPin mock](https://preview.uxpin.com/f43733391f52c409c4d3152e9a4b101a392e29df#/pages/161460699/simulate/sitemap)

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/32b986b6-ba57-4712-8d73-c916e30db38e)

---
## Tasks
- [ ] Add overview page
- [ ] Add phone number page
- [ ] Add email address page
- [ ] Add mailing address page

## Acceptance Criteria
- [ ] All user tests are passing
- [ ] Contact information is updating accordingly 
- [ ] All pages match design
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
Rolling into 98! Ran into some blockers for other tickets, but this is still in progress!
