### ISSUE TITLE
[eFSR] Mini summary update page content

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#56739]
## Issue Description
Change back/continue buttons to cancel or add/update when adding or editing items from a mini summary card list. When adding item directly in the flow of the form (example: [first vehicle](https://preview.uxpin.com/f43733391f52c409c4d3152e9a4b101a392e29df#/pages/161460760/simulate/sitemap)), keep back/continue buttons.

*Please note this is one of the tasks that was noted from the functionality updates ticket #55628 and is not considered a high priority (as of 4/12/23).

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/d560d3b4-dd02-43f5-868f-a9811faf685c)

---
## Tasks
- [ ] Identify instances of update pages that use continue/back text
- [ ] Update button text accordingly

## Acceptance Criteria
- [ ] Buttons match new design
- [ ] All tests pass

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by OptionSelect** [comment]
Identified areas: Employment History, Spouse Employment History, Vehicles. Will begin work to convert.
