### ISSUE TITLE
[eFSR] Other income summary page addition (Veteran & Spouse)

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#56738]
## Issue Description
*Please note this is one of the tasks that was noted from the functionality updates ticket #55628.

Update Veteran and spouse other income pages to include mini summary. 
Checkbox to input box functionality is in place so we just need to add the summary page and the update page for individuals that mimics what Other Assets has. 

Confirm checklist options (remove `Other`)

[UXPin for other income pages](https://preview.uxpin.com/f43733391f52c409c4d3152e9a4b101a392e29df#/pages/161460730/simulate/sitemap)

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/fca5ca66-04ad-4986-bdc4-b5c834a0ddc7)

---
## Tasks
- [x] Add veteran other income summary page
- [x] Add veteran other income update page
- [x] Add spouse other income summary page
- [x] Add spouse other income update page
- [x] Update e2e tests as necessary

## Acceptance Criteria
- [x] Pages match new design/flow
- [x] All tests are passing

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by OptionSelect** [comment]
Work is complete, awaiting break testing by rest of FE team and approval for merge.
