### ISSUE TITLE
Individual compromise amounts not populating

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#56748]
## Issue Description
Jill has reached out that the individual compromise amounts we're adding to the additional comments section of the FSR is neither showing the compromise amount nor the selected debt name. 

---
## Tasks
- [x] Replicate issue locally
- [ ] Identify reason behind missing values
- [ ] Create fix to populate the values

## Acceptance Criteria
- [ ] Individual compromise amounts are populating again
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Parameters were not being passed to controller and available in the service accurately. Updated to adjust and ran tests in staging with the desired results.
