### ISSUE TITLE
Add "decision reviews" to claim status tool landing page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#56747]
## Issue Description

Now that the product team has started using the term "decision reviews" in the claim status tool, we need to add it to the [Check your VA claim status or appeal](https://www.va.gov/claim-or-appeal-status/) landing page as well. 

We need to update the H1 to "Check your VA claim, appeal, or decision review status" as well as the intro paragraph and meta description and any other places needed.

## Tasks
- [x] Add "decision review" to page (Katherine)
- [x] Review (Laura)
- [x] Copyedit (Megan)
- [x] Publish (Laura)
- [ ] Notify stakeholders of changes (Laura/Katherine)

## Acceptance Criteria
- [x] Changes are live on the site

**Comment by katherine-fung** [comment]
Hi @laurwill and @RLHecht, 

I added "decision reviews" to this page. We'll also need to add it to the widget header. Who should I reach out to about that? 

Otherwise, this page is ready for review: 

http://preview-prod.vfs.va.gov/preview?nodeId=711

**Comment by laurwill** [comment]
Looks good @katherine-fung ! When you post updated sign-in widget header for the product team, let's change that "see" to "check" as well. 

@megzehn , ready for you.

**Comment by katherine-fung** [comment]
Thanks @laurwill. Noting here that I requested the widget change in a Slack to Jacob Worrell (https://app.slack.com/client/T03FECE8V/C04KHCT3ZMY)  

He said: "I've added the appropriate labels to get the ticket into our backlog. We'll put it through our refinement process and prioritize it in a future sprint."

**Comment by bethpottsVADEPO** [comment]
@katherine-fung Want to have him hold off on this until we decide the placement of "decision review"?

**Comment by katherine-fung** [comment]
@bethpottsVADEPO - yes! I'll let him know.

**Comment by katherine-fung** [comment]
Update: Laura found an old email where stakeholders asked us to use "claim, decision review, or appeal" in that order. 

I've updated the language on the page, and asked Jacob Worrell to update the widget header. 

I'm waiting for his team to provide some information on this content and whether we need to add "Supplemental Claim" to mentions of filing online: 

"You can also view these details:

Any evidence you’ve filed online to support your initial claim
Any additional evidence we’ve requested from you
Your claim type
What you’ve claimed
Your representative for VA claims
Note: You can only upload documents online to support your initial claim. You can’t upload documents online to support an appeal."

**Comment by katherine-fung** [comment]
After walking through the tool in staging, I propose we add the language in bold: 

"You can also view these details:
...
Your claim**, decision review, or appeal** type"

**You can use this tool to upload evidence for an initial claim. But you can’t use this tool to upload evidence for a decision review or an appeal.**

**Comment by bethpottsVADEPO** [comment]
@laurwill You can drive this forward without my input/review. Ping me if you want an opinion, but don't wait for me! You'll need to have stakeholders review this new content. You can ask the PM who that would be and ask them to set up a meeting so you can show the edits. We'll need to make sure any changes are accurate. Thanks!

**Comment by katherine-fung** [comment]
@laurwill - I checked with the product team and they said the tool does show decision reviews for all the types of compensation and benefits currently listed.

**Comment by katherine-fung** [comment]
@jacobworrell - Your team can go ahead with updating the header for the sign-in widget on this page. The header text should be an H2 that says: 

Sign in to check your claim, decision review, or appeal status

**Comment by katherine-fung** [comment]
Hi @laurwill, I added information about decision letters to this page. Can you take a look? Thanks! 

http://preview-prod.vfs.va.gov/preview?nodeId=711

**Comment by jacobworrell** [comment]
@katherine-fung looking at this again, it seems like this content is actually managed in Drupal. The codebase we manage is for the application that loads on these pages, but we don't have access to the code for things like headers, side rails, and other pieces of the UI in many cases. Sorry this nuance was lost in the initial pass.

**Comment by katherine-fung** [comment]
Noting here that Jacob and I discussed this over Slack, and he's going to see if his engineers can change the widget header.

**Comment by jacobworrell** [comment]
@katherine-fung I know this is frustrating as this, in theory, should be a relatively simple change, but @jerekshoe has been hunting for where the code for this widget actually lives and we just can't find it. It's not part of the codebase we work with regularly. Maybe we're just looking in the wrong places, but so far we haven't been able to deduce where the code lives.

**Comment by laurwill** [comment]
Noting here that I emailed Alejandro (partner in disability comp) to review several updates to the tool landing page and FAQs. I'll update here when he responds.

**Comment by katherine-fung** [comment]
I'm having a conversation with the product team about adjusting the widget header in ticket #58433

**Comment by laurwill** [comment]
Hi @megzehn , 
Alejandro approved the changes to our 2 static pages — these are ready for you to copyedit and publish.
- Tool landing page: http://preview-prod.vfs.va.gov/preview?nodeId=711
- FAQ page: http://preview-prod.vfs.va.gov/preview?nodeId=9275 (includes changes in single Q&A nodes)

Notes on next steps:
- We realized the CST landing page should also get an update to follow our [new tool landing page pattern](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/content-patterns-and-standards/tool-landing-pages.md) — we'll make those changes in a follow-on ticket.
- I sent an email to Jane and Lauren in OAR to confirm a question about some content inside the tool — once they confirm, I'll pass suggested changes for the tool content to Jacob and team.

**Comment by megzehn** [comment]
Thanks, @laurwill! Confirming I published these Q&As and landing page.

**Comment by megzehn** [comment]
@RLHecht this is ready for validation!

**Comment by RLHecht** [comment]
These changes are all live. closing ticket. @katherine-fung or @laurwill do you want to notify stakeholders?
