### ISSUE TITLE
[eFSR] Vehicle input error messages

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#56741]
## Issue Description
*Please note this is one of the tasks that was noted from the functionality updates ticket #55628 and is not considered a high priority (as of 4/12/23).

Errors aren't shown when user doesn't fill out required field. [UXPin for vehicle page](https://preview.uxpin.com/f43733391f52c409c4d3152e9a4b101a392e29df#/pages/161460760/simulate/sitemap?mode=i)

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/2f256167-8cb7-4f2a-a1bf-33bd9c324b0e)

---
## Tasks
- [ ] Update error messages to show appropriately 

## Acceptance Criteria
- [ ] Error messages are now functional for required field(s)
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
FE to confirm
