### ISSUE TITLE
Combine FSR reasons for user generated PDF

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#56749]
## Issue Description
Box #3 for FSR reason could be applied to multiple debts and isn't showing all for the PDF returned to the UI. These are being correctly mapped for VBA and VHA requests but not for the portal downloadable one.

---
## Tasks
- [x] Aggregate FSR reasons for all selected debts
- [x] Add aggregated reasons to box 3 (FSR reason field)

## Acceptance Criteria
- [ ] FSR reasons are shown for all debts for the downloadable PDF
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
@kjsuarez & @ScottyRJames - this might be a good ticket for Kevin?

**Comment by ScottyRJames** [comment]
Code is written but slow to validate with local submission issues

**Comment by HeatherRienks** [comment]
@ScottyRJames to ping Platform for an update.
