### ISSUE TITLE
Draft survey questions

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#56753]
## Issue Description

- [The research plan](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2588278812/Platform+Website+User+Experience+Research+v.2) has been scoped down with fewer objectives

- The initial method to gather feedback about the Platform website is through the use of an online survey that will be shared with VFS team members. It is time to rough draft this survey using the refined research objectives document and a selected survey tool.

---
## Tasks
- [x] Using Airtable, create a rough draft of the survey

- [x] Share survey with the rest of the team for feedback

- [x] Edit survey questions based on team feedback

## Acceptance Criteria
- [x] A survey will be drafted based on research objectives and team feedback

## Artifacts
- [Research plan v2](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2588278812/Platform+Website+User+Experience+Research+v.2)
- [Research action plan](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2598338590/Platform+Website+UX+Research+Action+Items)
- [Link to survey](https://airtable.com/shrT0FFoghjzQI3MR)
