### ISSUE TITLE
Create instructions for moving Confluence pages with launch-blocking issues

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#56756]
## Issue Description
The Platform Content has identified a need to create instructions for moving Confluence pages from the Drafts space back to a place in the website's IA.

1. Having step-by-step instructions for this would be helpful for other Platforms when working with us when:
a) they have launch-blocking issues in their documentation that is preventing their content from being deployed by our team; and

2. When our team collaborates with another Platform team during a bigger project.

---
## Tasks
- [x] Create step-by-step instructions on how to move a page in Confluence from the Drafts space back to a place in the Platform website's information architecture (IA)

- [x] Share instructions for any feedback from our team

- [x] Work on info panel problem

- [x] Record video of instructions

- [x] Record a troubleshooting video

- [x] Write in a troubleshooting section

- [x] Select a place for the instructions to live within the rest of the Platform website guidance: https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines

- [x] Edit the launch-blocking deployment message with a link to this page. (Brian doing this part)

## Acceptance Criteria
- [x] Platform teams will be able to reference step-by-step instructions available to them that explain how to move documents within Confluence from the Drafts space back to a place in the Platform website's IA
