### ISSUE TITLE
[FE] Notification design system comp.: finish setting up logic and relevant tests

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-team#56767]
## Background
Per feedback from [My VA audit UX improvement Midpoint review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42601), we learned we can use the notification component that Angela designed and submitted to the design system.

Allison has completed the [build and styling of the Notification component (#48726)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48726), but still needs to update "mid-stack" logic and e2e/unit tests.

---
## Tasks
- [x] create mock data for `/v0/onsite_notifications` endpoint and `/v0/onsite_notifications/{id}`
- [x] make sure Redux actions and reducers are updating global state locally 
- [ ] make current Notifications and DebtNotification components more abstract and scalable
- [x] remove entire Notifications section from My VA when last notification is dismissed
- [ ] ask VA Notify team:
  - [ ] if `template_id`s for each template remain **constant**
  - [ ] confirm template_id for debt notifications is still `f9947b27-df3b-4b09-875c-7f76594d766d`
 - [ ] ask @tpharrison where the [`id` property for a notification](https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/my_va/listOnsiteNotification) comes from 
 - [x] update e2e and unit tests accordingly
 - [x] put behind a Toggler component
   - [x] open PR to [add a new feature toggle](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles#Featuretoggles-Addinganewfeaturetoggle(frontend)) on `vets-api`

## Acceptance Criteria
- [ ] able to encounter no errors while [navigating the user flow](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications/use-cases)

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_  log into staging with users 11 or 220 to validate use of new component

## Resources

**Documentation references:**
- [Onsite notifications FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/mvp/frontend-documentation/notifications-frontend-documentation.md)
- [Design system submission - #1181](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1181)
- [Sketch design file](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/BE3AD487-CCBD-4DAB-96F2-18A5F90D063F)

**Screenshots**
- build from #48726 
![Screenshot 2023-04-07 at 5 14 04 PM](https://user-images.githubusercontent.com/8542413/231522842-5d1e9f88-ef69-4c86-99eb-1f307ff88283.png)

**Comment by ajakabcin** [comment]
confirmed on staging with user 36
![Screenshot 2023-05-10 at 11 39 11 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/a003c98a-f70f-4bb7-ba32-60a2344c4978)
