### ISSUE TITLE
Add Research hub/guidance specific to Platform teams

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#56784]
## Purpose
This is an idea we have suggested at times, and one that a previous version of the team [considered](https://vfs.atlassian.net/wiki/spaces/SDT/pages/637632667/Service+Design+Team+Mission+Workshop+-+Nov+2021) just before we joined.

## Tasks
- [x] [Discuss](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1681401093002/b419040d7d2b81ca55fc0e511789095783f5e003?sender=u9ea6bd3ca12795949b606150) whether we should pursue a resource like this.  (Would it be useful?  Would it be used?)
- [ ] Try creating a resource page that includes "how to's" and tips with links (our own and/or from Research Hub)

## Acceptance Criteria
- [x] Decision on whether to pursue this idea
- [ ] If pursued, a collection of ideas on what it might include

**Comment by tayism** [comment]
The newer format of the current team no longer accounts for this type of workflow (ex: platform teams using service design on their own; self-service).
