### ISSUE TITLE
[Design] 10-10EZ: Audit of headings and radio buttons

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#56801]
## Background

During a Content review of the Household section optimization work, it was recommended that we adjust the Marital Status and Financial Disclosure pages as follows:
- Add H3 stating the question
     - Ex: What is your marital status?
     - Ex: Do you want to disclose your household financial information?
- Include a label instructing the applicant what to do and re-states the question
     - Ex: Select your marital status
     - Ex: Select whether you want to provide your household financial information
- On the Financial Info page, update the Yes/No radio buttons to re-state the question with the answer
     - Ex: Yes, I want to provide my household financial information
     - Ex: No, I do not want to provide my household financial information

While we agree that having an H3 would be beneficial, especially for those using screenreaders or other AT, we do not agree that we should include the label that re-states the question.  We also need to consider that Labels are filtered down to the Review page, so the H3 would also need to be the Label to display correctly.

We want to audit the 10-10EZ form as a whole to review all pages individually and determine whether the page could benefit from having an H3 question, ensure all questions and choice-answers are displayed consistently, and ensure the Review page is not negatively impacted by these changes

### Resources

<details>
<summary>Marital Status page - CURRENT</summary>

![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/bca98a6a-f022-4ca7-ab0a-850217d6b862)

</details>

<details>
<summary>Marital Status page - SUGGESTED by Content Team</summary>

![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/e5043ff7-880e-4356-8bb7-cf1956ff13e6)

</details>

<details>
<summary>Financial Disclosure page - CURRENT</summary>

![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/1716cc48-224b-45e8-b6d7-02432ea79b39)

</details>

<details>
<summary>Financial Disclosure page - SUGGESTED by Content Team</summary>

![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/0b574630-a6a0-4706-9db3-d84d6a0c387e)

</details>

## Tasks 
- [x] Perform audit of 10-10EZ pages, questions, headings, answer formats
- [x] Update [content source of truth doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZ%20Form/10-10EZ-application-copy.md)

Following tasks moved to [[Design] 10-10EZ - Improvements: Exploration of designs using existing or experimental components/patterns #57794)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57794)
- [ ] Determine if any pages can benefit from adding an H3
- [ ] Determine if any pages should have choice-answers re-worded (Yes/No, Drop down, Multiple choice)
- [ ] Determine how the Review page would be impacted by any recommended changes
- [ ] Explore any design directions using existing or experimental components/patterns 
- [ ] Share findings with the team to determine next steps/tickets

## Acceptance Criteria
- An audit will be completed of the 10-10EZ form to determine if any changes are needed, and the findings are shared with the team. 
- Design explorations created of possible directions to share and discuss with the team

**Comment by jessicastump** [comment]
[Link to working doc](https://docs.google.com/document/d/1Ws69w3Yh-rCr8VU8AW9uVtTHeAVB_N0xMsU94nDtKHc/edit?usp=sharing) for audit placeholder. This will be moved to a github md file once completed. 

Should [this still be the content source of truth doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZ%20Form/10-10EZ-application-copy.md)? If so, can we add a task to this ticket to update with heading and other needed html tags.

**Comment by jessicastump** [comment]
### Audit of Radios with Yes/No answers

#### Section 1 Veteran Information:
Mailing address page: 
Is your home address the same as your mailing address? 

#### Section 2: VA Benefits
Pension page question: 
Do you receive a Veterans pension from the VA?

#### Section 3: Military Service
No yes/no radio questions

#### Section 4: Household financial information
Financial disclosure page: 
Do you want to share your household financial information?  
Spouse’s additional information page:
Did you live with your spouse for all or part of 2022?
Do you have the same address as your spouse?
Spouse’s financial support page:
Did you provide financial support to your spouse in 2022 even though you didn't live together?
Dependents page:
Do you have any dependents to report?
Dependent’s additional information page:
Was your dependent permanently and totally disabled before the age of 18?
If your dependent is between 18 and 23 years of age, did they attend school during the last calendar year?
Did your dependent live with you last year?
Did your dependent earn income last year?
Dependent support page:
If your dependent didn’t live with you last year, did you provide support?
Review/add additional dependents page:
Do you have another dependent to report?

#### Section 5: Insurance Information
Medicaid page:
Are you eligible for Medicaid?
Medicare page:
Are you enrolled in Medicare Part A (hospital insurance)?
Health insurance page page:
Do you have health insurance coverage?
VA Facility page:
Do you want VA to contact you to schedule your first appointment?

**Comment by jessicastump** [comment]
## Audit of H3’s

### Section 1 Veteran Information:
 
(3 pages/questions with no h3/title)
Page: Place of Birth = Fieldset legend title = Your place of birth
(3 pages/questions with no h3/title)
Page: Mailing address  = Fieldset legend title =  Mailing address
Conditional Page: Home address  = Fieldset legend title =  Home address
(1 page/question with no h3/title)

### Section 2: VA Benefits
H3 = Fieldset legend title  = Current compensation from VA
H3 = Fieldset legend title = Current compensation from VA
(same on two pages)
H3 = Confirm that you receive service-connected pay for a 50% or higher disability rating.

### Section 3: Military Service
(1 page with no h3)
h3=Fieldset legend title =  Service history
H3=Fieldset legend title =  Upload your discharge papers

### Section 4: Household financial information
NEW CONTENT IN EPIC #41403

Onboarding page, after intro paragraph
H3 = How we use your household financial information 
h3= Financial information you’ll need
H3 = Confirm that you don't want to provide your household financial information

(1 page no h3, marital status page)
H3 = Spouse’s information
H3 = Spouse’s additional information
H3 = Spouse’s financial support
H3 = Spouse’s address and phone number

(1 page no h3, dependent to report?) 
h3= Dependent’s information
H3 = [First Last]’s additional information
H3 = [First Last]’s support
H3 = [First Last]’s income
H3 = Review your dependents

H3 = TBD Your annual income
H3 = TBD Spouse’s annual income

H3 = TBD Last year's deductible expenses

### Section 5: Insurance Information
(4 pages no h3, 1 conditional, 1 includes old list loop pattern on insurance)
[both on same page]
H3=Fieldset legend title =   VA facility
H3=Fieldset legend title =   Select your preferred VA medical facility

### Section 6: Review
H3 = Agreement

**Comment by jessicastump** [comment]
Discovery during the audit to note: what resembles an h3 and what is used in the design system sketch file is actually a `fieldset legend title` not a heading `h3`.

**Comment by jessicastump** [comment]
The [source of truth doc on github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZ%20Form/10-10EZ-application-copy.md#content-source-of-truth) is updated with current content - household information section was left as is.

The [working google doc](https://docs.google.com/document/d/1Ws69w3Yh-rCr8VU8AW9uVtTHeAVB_N0xMsU94nDtKHc/edit?usp=sharing) has the new household section content and will move over to the github file once staging review/QA is complete.
