### ISSUE TITLE
[eFSR] Text/copy updates for FSR

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#56802]
## Issue Description

This ticket has been created as a result of QA work that was done by the Debt Resolution Design & Research team. The changes relate to text/copy to enhance clarity and specificity on the FSR form so that the Veteran enters the correct information, making the form clear, and easy to fill out. We also recommend additions of help sections or sub-text for accessibility. 

---
## Tasks
- [x] [Household income > Payroll deduction](https://preview.uxpin.com/f43733391f52c409c4d3152e9a4b101a392e29df#/pages/161460722/simulate/sitemap) Add the word **monthly** to [Payroll deduction](https://preview.uxpin.com/f43733391f52c409c4d3152e9a4b101a392e29df#/pages/161460722/simulate/sitemap) question ([also for spouse](https://preview.uxpin.com/f43733391f52c409c4d3152e9a4b101a392e29df#/pages/161460739/simulate/sitemap)): How much do you pay **monthly** on each of your payroll deductions? 
- [x] [Spouse information > add a job](https://preview.uxpin.com/f43733391f52c409c4d3152e9a4b101a392e29df#/pages/161460735/simulate/sitemap) Change **a** to **any** and **job** to **jobs**
- [x] [Confirmation page > We received your request alert](https://preview.uxpin.com/f43733391f52c409c4d3152e9a4b101a392e29df#/pages/161460902/simulate/sitemap) Highlight **If you experience changes that may affect our decision (like a job loss or a new job), you’ll need to submit a new request.** better somehow.
- [x] "Waiver" and "Debt forgiveness" are used interchangeably throughout the FSR, and this might not be intuitive to everyone. Should always say "Waiver/debt forgiveness".

## Acceptance Criteria
- [ ] _Frontend team will create tickets based on these updates and will link the newly created ticket numbers in the comments_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by josephrlee** [comment]
Moved to backlog for now. 

cc: @HeatherRienks

**Comment by josephrlee** [comment]
The Spouse Information task is being handled in @amponce [Employment History](https://github.com/department-of-veterans-affairs/vets-website/pull/23937) PR.

**Comment by HeatherRienks** [comment]
@josephrlee - thank you for all of your help!

**Comment by HeatherRienks** [comment]
@josephrlee -moving to closed, as the PR noted above has been approved and merged!

**Comment by josephrlee** [comment]
Just noting that this ticket is officially closed as the PR had some fixes that needed to be merged.
