### ISSUE TITLE
Engineering spike to de-risk: MPI & Sign-in Service

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#56816]
## Issue Description
_From IPP Kick-off:
**Risk: Database access**
Concerns:
- Challenges around creating new, seemingly redundant databases - compliance, security, and privacy issues.
- Will we be able to successfully (and quickly) make schema changes to existing databases (Master Person Index aka MPI) to enable IPP solutions? (Requires IAM involvement currently)
Mitigation strategy:
- Reference MPI instead of creating new database(s)
- If we encounter challenges with MPI integration, raise potential blockers ASAP
- Explore Sign-In Service (SIS) with Core team

---
## Tasks
- [ ] Check with IAM team to determine if we can propose/add columns to the schema for the Master Person Index (MPI), document findings in this issue.
- [ ] If IAM will not allow us to make changes ourselves, discover and document in this issue the process that we would need to follow to request changes to be made.
- [ ] Check with Core Team about the process required to request/make changes to their database schema as it relates to VA user (non-patient) database table(s), document those findings in this issue.

## Acceptance Criteria
- [ ] We understand whether we can make changes to the MPI schema or if we have to rely on IAM to do so.
- [ ] How do we make, propose, or submit requests for changes for the MPI schema to IAM?
- [ ] We understand the process to make/request changes to the Core Team's Sign-in Service.
---

**Comment by elizabethkochBT** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Logingov-adoption-Team-632280b31e745000136a61fc/issues/department-of-veterans-affairs/va.gov-team/56816?planning-poker) with Zenhub @jrjamespdx

**Comment by elizabethkochBT** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Logingov-adoption-Team-632280b31e745000136a61fc/issues/department-of-veterans-affairs/va.gov-team/56816?planning-poker) with Zenhub @alevindecanini

**Comment by jrjamespdx** [comment]
**Final Disposition:**

MPI:  
While I'm awaiting response from IAM on the ability to add Trusted Referee information to MPI, the reliance on other teams to make changes that are not a large priority on their side is troublesome.  If we get word from IAM that they are able to handle our requests for changes or allow us to make the changes, then I can update our system design plans to make use of MPI.

Sign-In Service:
Core Team brought up the possibility of us being able to put Trusted Referee data into their Sign-in Service.  Unfortunately this also carries the same risk as MPI via IAM:  we'd be dependent on the Core Team to make changes or allow us to make changes.  Additionally, we'd be mixing concerns by adding data to the user models for Sign-in Service that doesn't really belong there logically for both business rule and dependency reasons.

Suggested Alternative:
We maintain our own database which maintains the Trusted Referee administration information. 
 Additionally, we can utilize the UUID for users from MPI to tie our records back to their's without actually maintaining any PII in our database.  This gives us more freedom to iterate on all three major components  user administration, training, and workflow) without being hindered by extra dependencies.
