### ISSUE TITLE
Conduct research to de-risk: Identity Management Toolkit

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#56814]
## Issue Description
_Investigate: Can/should MHV Coordinators use the [Identity Management Toolkit](https://mvitkssoi-prod.aac.va.gov/imdquiWeb/login.do) instead of, or alongside, a new IPP solution?
Identity Management Toolkit is mentioned in [VHIC User guide](https://www.va.gov/vdl/documents/Financial_Admin/Veteran_ID_Card/vhic_4_22_um_v1.pdf) 

Per Tyler & Elizabeth: This isn't pertinent to MHV Coordinators, although some of them have this responsibility too. A lot of people that do VHIC are eligibility and enrollment people.
_

---
## Tasks
- [x] _Review VHIC user guide_
- [x] _Write follow-up questions_
- [x] _Identify who the SME is (MHV Coordinators?)_
- [x] _Interview SME(s)_
- [x] _Report findings_

## Acceptance Criteria
- [x] _We understand how the Toolkit is being used today and whether it could be used for In-person proofing_
---

**Comment by alevindecanini** [comment]
Reached out to Danny Reed 4/20/23, have not heard back yet.
Reached out to Damien DeAntonio to follow up, he is going to ask for details during his call with the internal architecture team today.

**Comment by alevindecanini** [comment]
[Notes from my call with Alicia Ray 5/2/23](https://docs.google.com/document/d/1jMrHUuKPvIAPKttQURSISBYjBSmSUIUraeIs9ssBCn0/edit?usp=sharing)
