### ISSUE TITLE
Execute Communication Plan for new Feedback portal

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#56813]
## Purpose
Step through the communications outline in the plan

## Tasks
- [x] Communicate via Slack (Taylor)
- [x] Communicate via Demo day (Dan)
- [x] Communicate via ToT (Bryan)

## Acceptance Criteria
- [x] Communicated via Slack (Taylor
- [x] Communicated via Demo day (Dan)
- [x] Communicated via ToT (Bryan)

**Comment by steel36** [comment]
Will rollover to next sprint;  result of additional options being explored
