### ISSUE TITLE
Conduct research to de-risk: MHV Coordinators

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#56815]
## Issue Description
_From IPP kick-off:_
**Risk: Getting buy-in from MHV Coordinators**
Concerns:
- Some MHV Coordinators work remotely today and may not be able to provide in-person services
- Union requires 60 days of lead time in order to train MHV Coordinators on new processes & tools

Mitigation strategy:
- Revisit PWS language that mentions MHV coordinators
- Conduct research to better understand policies & practices around MHV Coordinators working remotely

---
## Tasks
- [x] _Revisit PWS language_
- [x] _Write an interview guide_
- [x] _Schedule interviews with MHV staff_
- [x] _Conduct interviews_
- [x] _Report findings_

## Acceptance Criteria
- [x] _We understand whether it will be possible to overcome concerns about MHV coordinator buy-in, remote work, and union contract considerations_
---

**Comment by alevindecanini** [comment]
https://dsva.slack.com/archives/C04LFGY2SJK/p1679930836609499

**Comment by elizabethkochBT** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Logingov-adoption-Team-632280b31e745000136a61fc/issues/department-of-veterans-affairs/va.gov-team/56815?planning-poker) with Zenhub @alevindecanini

**Comment by alevindecanini** [comment]
Need to schedule sessions with MHV Coordinators, working with Susan to set that up
