### ISSUE TITLE
Draft IPP product outline based on product brief

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#56822]
[Product outlines](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/login.gov-adoption/products)

## Issue Description
_Per the Platform, every product needs to have a Product Outline. Based on the [brief that Porta wrote](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/products/in-person%20support/product-brief.md), we will create a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/login.gov-adoption/products)._

---
## Tasks
- [x] _Write Overview section_
- [ ] _Write Priorities section_
- [ ] _Write Initiatives section, with Vision, Desired user outcomes, and User problem statements for each Initiative_
- [ ] _Write Requirements & Constraints section_
- [ ] _Write Value Propositions section_
- [x] _Write KPIs section_
- [ ] _Socialize Product Outline_
- [ ] _Iterate based on feedback_
- [ ] _Publish on Github_

## Acceptance Criteria
- [ ] _Team and PO agree that the Product Outline is appropriate and accurate_

**Comment by elizabethkochBT** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Logingov-adoption-Team-632280b31e745000136a61fc/issues/department-of-veterans-affairs/va.gov-team/56822?planning-poker) with Zenhub @alevindecanini

**Comment by alevindecanini** [comment]
Draft: https://docs.google.com/document/d/1t0wgERgqTRvyxx7kPSNAKWQ0a4G5DpjXaYcqYBVGHu0/edit#
