### ISSUE TITLE
Determine IPP service design process

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#56825]
## Issue Description
_In order to begin developing the different components of an in-person proofing solution, we first want to consider how the service will be delivered to Veterans. The first step is to plan out the service design process._

---
## Tasks
- [x] _Meet to discuss the process_
- [x] _Draft an initial design process plan_
- [x] _Iterate_
- [x] _Finalize the service design plan_

## Acceptance Criteria
- [x] _Design and Product teams agree that the planned design process is appropriate to address project goals_

**Comment by elizabethkochBT** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Logingov-adoption-Team-632280b31e745000136a61fc/issues/department-of-veterans-affairs/va.gov-team/56825?planning-poker) with Zenhub @alevindecanini

**Comment by alevindecanini** [comment]
![Screen Shot 2023-04-24 at 10.41.01 PM.png](https://images.zenhubusercontent.com/63a49829a7612e8c437e2033/c3975278-48e6-4d37-9f26-ae67c32d6e83)

**Comment by tygindraux** [comment]
I created and shared [this document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/products/in-person%20support/design%20approach.md) with @alevindecanini to better describe our design approach in this phase. While Anthony reviews this, I'm going to move this ticket to review.
