### ISSUE TITLE
Login.gov adoption team: Sprint 18 (4/13 - 4/26)

### ISSUE THREAD

**Issue by elizabethkochBT** [department-of-veterans-affairs/va.gov-team#56841]
## PTO

- Elizabeth 4/17-4/21
- Carolyn 4/21–4/26
- Sofia 4/20-4/21
- Steve 4/26-4/28

## Sprint 18 Priorities

Legacy credential migration
 - Based on research findings come up with recommendations as a team
 - Share research findings and recommendations
 - Address IAM concerns around binding app

Dashboards
 - Dashboard automation and access reports

Organic adoption
 - Collaboration cycle midpoint review 4/14
 - Partnering with core team for first organic adoption research study
 - Make TAP recommendations based on observations from current review and discovery work

In-person proofing
 - Conduct research & Engineering spikes to de-risk: MPI, SSI, Identity Management Toolkit, MHV Coordinators
 - Revisit service design considerations & define design process going forward 

 
## Retro Board

[Sprint 17 Retro](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1677768711421/aad15b9308afe560c52a1beddefe388840ae239d?wid=0-1678115798175)

### Discussion Topics/Retro Action Items
 - [ ] Best way forward with Zenhub and backlog grooming
 - [ ] IPP - Swat at fog and clarify questions
 - [ ] Backup Plan for Binding. Strategerize the situation

## Collab Cycle Tasks 
 - [x] Midpoint review 4/14
