### ISSUE TITLE
[Design, FE] 10-10EZ - Critical: Update Review page with Copay, Communication and Assignment of Benefits disclosure

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#56847]
## Background

During a discussion with the HEC/EZ Stakeholders on 4/12/23, it was requested that the disclosure regarding Copays, Communications and Assignment of Benefits be added to the online 10-10EZ form.  (see [Meeting Notes](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/products/health-care/application/va-application/product/Bi-weekly%20Stakeholder%20Mtg%20notes/4-12-2023%20HEC%20Bi-weekly%20Health%20Care%20app%20update.md) for more information)
As this is a high priority for the business, and contains important legal information for the Veteran applicants, we need to add the disclosure information quickly.

### Resources
- Screenshot of disclosure content from Stakeholders
![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/db554843-9091-45e9-8b63-939479f87c81)

- [Sketch file with content review suggestions](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/9llVd3P)

## Tasks

- [ ] Review disclosure verbiage from stakeholder
- [ ] Update design with language, including content review suggestions
- [ ] Implement changes on Review page in Staging
- [ ] Complete QA testing to confirm content and links functionality
- [ ] Confirm Launch approval with team/PO/Stakeholders
- [ ] Launch changes in production

## Acceptance Criteria
- Disclosure information will be added to the 10-10EZ form Review page

**Comment by jessicastump** [comment]
Answer to above blocker: 
For this initial launch we need to have the exact word-for-word disclosure one click away. 

Sketch design links below using the additional information component route.
[Review page - add info closed
](url)Review page - add info open

**Comment by jessicastump** [comment]
@longmd Would you like me to add the content here via a comment so it is easier to copy, or can you pull from the Sketch file?

**Comment by longmd** [comment]
@jessicastump , I can pull from the sketch file. No need to do double copy/paste.

**Comment by longmd** [comment]
This is ready for full validation and sign off to go to prod with today's daily. 🚀

**Comment by hdjustice** [comment]
Validated in staging on both desktop (Chrome) and mobile (Android).  Also tested with NVDA on Chrome.  Found no issues

- Desktop:
![image](https://user-images.githubusercontent.com/92328831/234303861-b446c7eb-2124-4149-a90f-84dad9b4303f.png)

- Mobile:
![Screenshot_20230425_100921_Samsung Internet](https://user-images.githubusercontent.com/92328831/234304170-d0fa5e80-4994-4f3d-b7da-2a9e4c18c232.jpg)

**Comment by hdjustice** [comment]
Full screenshot
![image](https://user-images.githubusercontent.com/92328831/234307010-2c057ee1-21b7-4190-a6ec-8983a6c4586a.png)

**Comment by jessicastump** [comment]
Updated [Sketch page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/5A0793CD-192B-4BB9-8752-E2AF5BA24A45/canvas) for design file source of truth
