### ISSUE TITLE
Create eFolder API module with basic upload functionality

### ISSUE THREAD

**Issue by keithdadkins** [department-of-veterans-affairs/va.gov-team#5685]
## User Story:
When a user uploads a document to the `/services/efolder/v0/documents` endpoint via a `POST` method, then the document is uploaded and queued for processing.

## Tasks
- [x] create a new eFolder API Rails::Engine module for handling file uploads
- [x] generate an appropriate 'document' resource/model
- [x] setup module to use rspec
- [ ] generate a carrierwave uploader and associate it with the document model
- [ ] upload a document

## Acceptance Criteria:
* efolder_api engine exists and is mounted inside the vets-api
* efolder_api migrations are run inside vets-api
* `rake routes` includes efolder_api routes
* `rspec modules/efodler_api/spec` successfully runs at least one test
* `services/efolder/v0/documents` RESTful routes exists
* able to upload documents
