### ISSUE TITLE
Collect R/VSR data 

### ISSUE THREAD

**Issue by Nyanteea** [department-of-veterans-affairs/va.gov-team#56866]
## Issue Description

Product needs to create a metric baseline that must encompass user-generated metrics but also RVSR metrics currently tracked by VSOs. 

**Proposed R/VSR metrics to request:**
- R/VSR baseline data - (digital vs paper)
- VSR - form processing time/ development time
- number of forms sent back for development a second time by RSVR
- number of forms expired after ITF
- number of ancillary forms submitted
- 

---
## Tasks
- [x] Determine R/VSR metrics to track 
- [x] Ask Matt to obtain  R/VSR data
- [x] Ask Shannon if she has access to R/VSR data
- [ ] NEW: CREATE LIST OF METRICS FOR REVIEW AT NEXT VBA SYNC 
- [ ] Submit list to Alejandro 

## Acceptance Criteria
- [ ] Send the request for datasets 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Nyanteea** [comment]
@lydiahooper @RakshindaAslam

**Comment by Nyanteea** [comment]
Shannon says : "Let me see what I can find out about the data - I know that the HTN team is actively trying to get some RVSR stats as well."

**Comment by Nyanteea** [comment]
After a discussion with Shannon on 4/2 -- Shannon to come up with a list of R/VSR data to be collected to inform baseline/success metrics.

**Comment by Nyanteea** [comment]
Shannon to sync with Matt and Alejandro to discuss other appropriate RVSR measurements

**Comment by Nyanteea** [comment]
[VBA Check-in Notes and conversation about data ](https://docs.google.com/document/d/1H9xgYJ-oAj3AWKtnzZxOI3xv_ayQKju03rkc36Emax8/edit#)

**Comment by shannonkford** [comment]
@Nyanteea / @RakshindaAslam 

It would be helpful to clarify this request: "number of forms sent back for development a second time by RSVR" - data team will know this as a deferral, but it is unclear if you are asking for # of deferrals or # of 2nd deferrals.

Also it seems like we lost the request for #s of development letters sent to Veterans by type

**Comment by lydiahooper** [comment]
List was compiled in VBA meeting on 08/08/2023. Emily Theis is going to walk PMs through a set of data she has in Tableau, hopefully what we want will be in there.
