### ISSUE TITLE
Automated deploys with prod

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#56871]
https://dsva.slack.com/archives/C04M7T1CZAS/p1681418048307999?thread_ts=1680792328.300899&cid=C04M7T1CZAS

## Objective
- **Increase Automation**: Transition from manual to automated deployments for Vets API in ArgoCD in sandbox and prod.
- **Collaborative Design**: Involve the team in creating a design document to brainstorm, discuss, and decide on the best automation approach.

## Tasks
- [x] Schedule a brainstorming session with the team to discuss automation ideas.
- [x] Assign a lead to draft the initial version of the design document.
- [x] Review current deployment process to identify manual steps and challenges.
- [x] Research potential automation tools and methods suitable for our workflow.
- [x] Compile team inputs and ideas into the design document.
- [ ] Review and finalize the design document with the team.
- [ ] Create a follow-up ticket for the implementation of the agreed-upon automation strategy.

## Acceptance Criteria
- A comprehensive design document is created, detailing the proposed automated deployment process for Vets API.
- The document includes inputs and consensus from the team members.
- A clear plan of action for implementation is outlined in the document.

## Notes
- Consider the existing infrastructure and compatibility with ArgoCD.
- Ensure that any proposed automation maintains our standards for security and reliability.
- Document potential risks and mitigation strategies associated with automation.

**Comment by laineymajor** [comment]
Will require a LOT of communication with VFS teams

**Comment by laineymajor** [comment]
On hold until code freeze is over. All other work for this ticket is currently complete.

**Comment by LindseySaari** [comment]
Continuous Deployment directly to production can be risky for several reasons. While it automates the release of new changes, making the deployment process efficient and streamlined, it also comes with challenges and risks, particularly for environments where stability and reliability are critical. 

* **Introduction of Bugs Risk:** Continuous Deployment increases the risk of deploying code that hasn't been thoroughly tested, directly into the production environment. With CD, code bypasses testing in lower environments. Our current practice schedules deployments for 3 PM ET on business days, allowing sufficient time to test in these lower, live environments before release. We would need to derive a plan to re-evaluate and explore various aspects of our testing strategy, such as preview environments, review instances, and feature toggles. Implementing CD will represent a significant shift in development  and testing practices for our team members and customers on the Platform.
* **Complicated Rollbacks:** In a Continuous Deployment setup, addressing issues caused by a deployment can be more challenging. This complexity increases if there have been several deployments since the last manual review, complicating the process of rolling back changes and figuring out where a breaking change was introduced.
* **Resource Intensive Deployments:** Our method of bulkheading and managing pod surges means continuous deployments could significantly strain resources. If deployments are ongoing and frequent, this could lead to continuous and substantial resource consumption.
* **User Perception and Adaptation Challenges:** Continually rolling out updates, particularly major ones, may be perceived as a lack of stability by our Veterans (end users). This is especially relevant for updates that necessitate significant user retraining or adaptation, as it might affect user confidence in the product.

**Comment by laineymajor** [comment]
Work will continue on this during our part 2 of the double sprint. We were on hold with this due to code freeze.

**Comment by laineymajor** [comment]
We need to define automated deploys as 'not having human intervention of clicking the deploy button' for now. We are not ready for multiple prod deploys (CD)

**Comment by RachalCassity** [comment]
ArgoCD does not support daily deployments. To allow auto-deployments for vets-api, aka not manual syncing, prod and sandbox need to have autodeploy enabled but the two branches need to be deployed from a controlled branch that is only pushed once a day. 

Instead of having sandbox and prod deploy from the manifest's main branch, prod and sandbox will be auto-deployed from the auto-deploy-vets-api-prod branch.

**Comment by RachalCassity** [comment]
Asked the devops cop for thoughts in this slack thread, https://dsva.slack.com/archives/C04CYC4LMU6/p1704323252079629

**Comment by RachalCassity** [comment]
We can also implement automatic code freeze dates with github actions:

Freeze Dates 
Code freeze dates

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/deployment-policy.md#holiday-release-freeze-schedule
Github action example:
```
on:
  schedule:
    - cron: '1 * 24 DEC *'
    - cron: '1 * 11 NOV *'
```

**Comment by RachalCassity** [comment]
Confluence doc: https://vfs.atlassian.net/wiki/spaces/PPT/pages/2893676597/Automatically+Syncing+Vets-api+Daily+Deploys

**Comment by RachalCassity** [comment]
Confluence doc: https://vfs.atlassian.net/wiki/spaces/PPT/pages/2893676597/Automatically+Syncing+Vets-api+Daily+Deploys

**Comment by jennb33** [comment]
@little-oddball approved this on 1/17/2024 so we can proceed with the work.

**Comment by jennb33** [comment]
Per @RachalCassity this was deployed to the Sandbox successfully on Friday 1/19, we are letting this ride through Wednesday then, provided there are no incidents, this ticket can close.

**Comment by jennb33** [comment]
We need to fix the automatic 5 retries, will be syching with Infra to solve. CoP meeting is 1/25 to level-set on next steps. @RachalCassity

**Comment by jennb33** [comment]
After CoP meeting, @RachalCassity will be able to progress to Prod

**Comment by RachalCassity** [comment]
This will be held off until support dies down.

**Comment by RachalCassity** [comment]
Sandbox PRs waiting in review: https://oddball.slack.com/archives/C045LCF8WU8/p1706631497955649

**Comment by jennb33** [comment]
@RachalCassity to review on 2/1

**Comment by RachalCassity** [comment]
This has been completed, closing after standup.
