### ISSUE TITLE
Update content on digital notifications terms and conditions page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#56890]
## Issue Description

The VA Notify team opened an intake request for our team to make a few minor content changes to the [Digital notifications terms and conditions](https://www.va.gov/privacy-policy/digital-notifications-terms-and-conditions/) page.

Changes requested: 
1. Section header "Delivery and messaging rates" must be changed verbatim to "Message and data rates may apply". This is a carrier requirement for SMS notifications on the terms and conditions page.
2. We are required to provide at least one method of help/contact on the page. After talking to our SMS provider, they told us it would be ok to link to our current contact us page somewhere within terms and conditions. https://www.va.gov/contact-us/

Intake request for more background: #56877

## Tasks
- [x] Update page in Drupal
- [x] Review (Laura)
- [x] Copyedit (Megan)
- [x] Publish (Megan)
- [x] Alert product team in intake request that changes have been made (Megan)

## Acceptance Criteria
- [x] Changes are live on the site

**Comment by laurwill** [comment]
Thanks Katherine! Your change makes sense. I see other updates we could make to this page, but we may be editing this again soon to align with unified T&C work, so let's just do this specific ask for now.

@megzehn , ready for you.

**Comment by megzehn** [comment]
Thanks, @laurwill and @katherine-fung. I copy edited the changes. Let me know when we're good to publish!

**Comment by katherine-fung** [comment]
Noting that Amazon asked the product team to make one more change to this page. The product team is clarifying the change, and will let us know what the request is.

**Comment by katherine-fung** [comment]
Hi @megzehn - I've added "T-Mobile" to the list of mobile phone providers on the page, per the product team. Here's the inline comparison of the change: https://prod.cms.va.gov/node/34307/revisions/view/766548/770593/visual_inline 

If that change is fine, this page is ready to publish. Thank you!!

**Comment by megzehn** [comment]
Thanks, @katherine-fung. I published the changes.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
