### ISSUE TITLE
Datadog metric issues (Identity)

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#56891]
**Problem Statement**
Identity team is being paged because the stats are calculating as counts instead of rates. This is making the number drop below their acceptable threshold -> getting paged.
*No known impact directly to veterans.

**Issue Description**
Link to [slack thread](https://dsva.slack.com/archives/C04M7T1CZAS/p1681482867339969)

- started around 1600ET 4.13.23 
*THis was around the time Trevor and Riley's changes were deployed

- mobile stats

- stats randomly flipping from rate to count (below are the stats the identity team uses to monitor prod, and are being switched from rate to count by themselves):
`vets_api.statsd.api_sis_auth_failure`
`vets_api.statsd.api_sis_token_failure`
`vets_api.statsd.api_sis_revoke_failure`
`vets_api.statsd.api_sis_refresh_failure`
`vets_api.statsd.api_sis_callback_failure`
`vets_api.statsd.api_sis_callback_success`
`vets_api.statsd.api_auth_saml_request`
`vets_api.statsd.api_auth_login_failure`
`vets_api.statsd.api_auth_login_success`
`vets_api.statsd.api_auth_saml_response`
`vets_api.statsd.iam_ssoe_oauth_session`
`vets_api.statsd.iam_ssoe_oauth_auth_total`

---
**Tasks**
- [ ] Investigating: a job thats running that is switching rate to count (and all of our metrics should always be rate)
- [ ] Investigating: deploy for DD agent is causing the type to flip
- [ ] Investigating: bug in Trevors monkeypatch
- [ ] Investigating: openmetrics only in Dev? Is this impacting stats in other envinronments
- [ ] Investigating: 1600 ET 14APR is when this issue started

Resolution:
The metrics broke because we removed them from the mobile components file in nginx. We only removed it from there so we could point mobile traffic to EKS but not /appointments.
- Theory: the metrics were getting lumped regardless of env
- Undid openmetrics change
- Continue monitoring with Identity team

**Comment by laineymajor** [comment]
closing but in open monitoring epic
