### ISSUE TITLE
[Discovery] Understand how Veterans schedule VA appointments online [example epic for UX onboarding]

### ISSUE THREAD

**Issue by smoonpeyes** [department-of-veterans-affairs/va.gov-team#569]
*This is an example epic for UX onboarding.*

## High-Level User Story
As the x product team, we need to understand how Veterans schedule VA appointments online so we can improve the process.

## Goals
* Identify pain points in the current online scheduling process
* Identify what's working well
* Identify opportunities to improve Veterans' experiences with online scheduling

## Definition of done
- [ ] Research plan created
- [ ] Participants recruited
- [ ] Sessions scheduled
- [ ] Discovery Conversation Guide created
- [ ] Research sessions conducted
- [ ] Discovery Synthesis completed
- [ ] Discovery Research Readout shared and socialized
- [ ] Link to Research Summary added to Research History doc
