### ISSUE TITLE
Update documentation to remind VFS teams about previously recorded touchpoints

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#56907]
## User Story
As a new VFS Team member, I want to discover (or be reminded) that I can watch recordings of previous touchpoints, so that I can feel up to date and prepared for feedback I might receive at the team's next touchpoint in the collaboration cycle. 

Assignee: @sterkenburgsara 
Peer Reviewer: @allison0034 

## Description
Add documentation to collaboration cycle moderator responsibilities at Midpoint and Staging review to suggest to VFS teams that they can rewatch previous touchpoints anytime by clicking the link to the recording in their collab cycle epic ticket. 

Proposed solution: add reminder in the Slack message letting the team know previous touchpoint recordings are available.

## Impacted Artifacts
* Midpoint documentation / moderator responsibilities
* Staging review documentation / moderator responsibilities
* ~~Consider whether we possibly want to add a change to codeblocks (Kickoff responsibilities) in the collab cycle ticket to include that in the directions for VFS teams at midpoint and staging.~~ 

## Tasks
- [x] Add reminder in the Slack message confirming the touchpoint was scheduled successfully letting the team know previous touchpoint recordings are available
   - [x] Midpoint Review ([moderator responsibilities page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Moderator+Responsibilities))
   - [x] Staging Review ([moderator responsibilities page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review+-+VFS+-+Moderator+Responsibilities))

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS teams are reminded of previous touchpoint recordings when they schedule Midpoint Review and Staging Review

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by sterkenburgsara** [comment]
@allison0034 Ready for your review - I added a sentence about the Zoom recordings to the moderator responsibilities pages for midpoint & staging review. I think it adds a lot of bulk to the already lengthy Slack message, so I'm curious what you think.

**Comment by allison0034** [comment]
I agree @sterkenburgsara this seems lengthy and we have only heard once about VFS not knowing about a recording. Perhaps it is something we can just mention at the end of the meeting? Something like...

Just a reminder, our feedback will be attached to the epic by EOD and the Zoom recording from this meeting will be linked in the design intent section.

**Comment by allison0034** [comment]
I feel like that canned response we put in writing should be for really important things only. This does not seem that important.

**Comment by sterkenburgsara** [comment]
@allison0034 I agree! I can edit that sentence back out. Before I do that, @shiragoodman can you weigh in?

**Comment by shiragoodman** [comment]
So are you proposing instead that we should remind folks the meeting is recorded at the end of the meeting? Opposed to reminding them of previous recordings when they schedule a MPR or SR?

**Comment by allison0034** [comment]
Yes, the reason is we only hear 1 person say they "forgot" we posted the recordings and I think that canned response should be for really important things.

**Comment by shiragoodman** [comment]
i agree. Let's pivot towards that. Also, it might be a good idea to format the outgoing message of MPR and SR (and DI too)  in the moderator responsibility docs to look like the script (formatted as code). it would be more visible that way and less likely to be forgotten by the host. Thoughts?

**Comment by sterkenburgsara** [comment]
@shiragoodman sounds great to me - I'll make these changes this morning.

**Comment by sterkenburgsara** [comment]
@allison0034 @shiragoodman I think the moderator scripts are so long already, it was my preference to add this into the last step during each "during the meeting" section (DI, MPR, SR).  It's possible it get missed since it isn't called out in the script, but I don't think we can afford to add more heft there. Thoughts? Does that sound okay?

**Comment by shiragoodman** [comment]
hi @sterkenburgsara . I think my comment may have been misunderstood. I am not suggesting we add this to the moderator script. I was suggesting we add this to the close out guidance... so when we end the meeting. We currently state that feedback will be available by EOD (for MPR), etc. I was thinking that formalizing our closeout guidance would be valuable... and I suggested that we could _format it_ in the Moderator Responsibility doc so it looks and feels similar to the script. 

Does that make sense? Let me know. Once you confirm, I think it might be best to close this ticket and create a new one for the work since a lot is changing.

**Comment by sterkenburgsara** [comment]
@shiragoodman yes, got it and agree - I think we are saying the same thing. Closing this one and creating new ticket.
