### ISSUE TITLE
Draft blog and social media about why security is an evolving priority

### ISSUE THREAD

**Issue by elizabethkochBT** [department-of-veterans-affairs/va.gov-team#56912]
## Summary 
The VA should utilize traditional and non-traditional methods of education/awareness to help users understand the future of security, and why security standards are evolving and should be a priority. It's more than just preventing someone from stealing your identity. Education methods can include informal moments like Facebook reels or social media that feel relatable.

As a Veteran, I need to be aware of changing security landscapes and my role so I can make informed decisions

**VA VetResources Guest Post Blog Guidelines**
We would ask that your blog piece answer these four main questions:

 - What is the resource?
 - Who is eligible?
 - How to apply?
 - What to expect after applying?
 
Additional requirements/recommendations:

- Target 500 or so words, 300 word minimum
- Veteran is always capitalized
- Minimum of one quality 1200 x 628 pixel horizontal photo jpg or png file, two is better (We can embed video if you have one.)
- Written in active voice, avoid passive
- Sentences no longer than 20 words
- Ease in reading, no corporate buzzwords, avoid acronyms, no overly fluffy wording
- Simple, straightforward storytelling—VETERAN CENTERED
- Who is the author and their title (byline)
- Direct URL to sign up for the resource
- Social media handles for your organization (so we can tag you in posts to promote)

Here are links to recent VetResources blogs that have posted at blogs.va.gov:
https://www.blogs.va.gov/VAntage/76292/free-training-veterans-spouses-npower/
https://www.blogs.va.gov/VAntage/76115/military-child-education-coalition-free-resources-veteran-families/
https://www.blogs.va.gov/VAntage/75991/team-rubicon-delivering-food-risk-americans-front-doors/

### Tasks
- [x]  Reach out to VEO to understand process of publishing post, sending in newsletter, and social media.
- [x]  @CarlDickerson Draft new blog post
- [x]  @MOStudioCarolyn source images for blog post

### Acceptance Criteria
 - [x] Socialize blog and received feedback
