### ISSUE TITLE
HLR | Refactor code with VA components

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#56927]
## Value Statement
**_As a_** Veteran with accessibility needs that is filing a higher-level review
**_I want to_** file using the latest enhancements to the frontend experience
**_So that_** I can benefit from accessibility and other design updates. 

---
## Background Context
This form uses outdated components. The VA design system has updated components that we can use for the form. 

## Acceptance Criteria
- [x] All tasks complete
- [x] All tests passing
- [x] User can submit a Higher-Level review with no errors related to component use

## Designs and Build Notes
- ~Replace wizard with subtask~ move task to #57821
- `va-date` to `va-memorable-date` (accept 1 or 2 digit month & day numbers)
- Download link to `va-link`
- OMBInfo to `va-omb-info` & check privacy policy content
- Replace `button` (not a React component) with `va-button`
- Possibly more

## Out of scope
- Add here

## Open questions
- Any change to OMB privacy policy text?
- Remove AMA opt-in checkbox?

## Tasks
- [ ] ~Subtask replaces wizard and shows one question per page~
- [x] `va-memorable-date` replaces `va-date` & update validations
- [x] Replace `DownloadLink` with `va-link`
- [x] Replace `OMBInfo` with `va-omb-info`
- [x] Update OMB privacy policy content as needed
- [x] Replace plain `<button>` with `<va-button>` as needed
- [x] Unit tests updated
- [ ] ~e2e tests updated~

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by saderagsdale** [comment]
Need help adding AC for testing this @Mottie

**Comment by Mottie** [comment]
Move subtask work to a new ticket since it needs design changes

**Comment by saderagsdale** [comment]
@rocio-desantiago will check E2E tests and confirm if this can be closed.

**Comment by rocio-desantiago** [comment]
@saderagsdale confirmed e2e tests are passing. Updated components did not affect them. Closing.
