### ISSUE TITLE
HLR | Confirm destructive actions

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#56929]
## Value Statement
**_As a_** Veteran editing data I've entered into the form
**_I want to_** receive a confirmation before completing destructive actions
**_So that_** I don't accidentally delete info from the form. 

---
## Background Context

While building the Supplemental Claim form, the collaboration cycle required that all destructive actions be confirmed by the user. For HLR, this will be needed on the contestable issues page for added issues.

## Acceptance Criteria
- [ ] User is asked to confirm their change before removing contestable issues from the form

## Designs and Build Notes
- See [design and a11y notes for Supplemental Claims](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56082) 
- [Link to designs](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/p/C22CAF85-3AE8-4837-9C8F-0C7145740CC1/canvas)

## Out of scope
- Uploads are a platform change.

## Open questions
- Add here

## Tasks
- [x] Create design for modals
- [ ] Add remove confirmation to contestable issues page
- [ ] Add unit & e2e tests

## Definition of Ready 

- [ ] Content in place
- [ ] Code reviewed prior to starting

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by uxgary** [comment]
The design has been updated in the [sketch file](https://www.sketch.com/s/96420652-15b7-45bb-80c5-5454dcd4b3c6/p/B37669FF-D5F8-4A6C-AB28-60F4DF570C9E/canvas). 

Review the layer: Contestable issues.

**Comment by Mottie** [comment]
Work completed, please test these focus management scenarios:

| Start action | Then | Focus result |
|---|---|---|
| Add new issue | Cancel | Add new issue |
| Add new issue | Fill out and Add | New issue checkbox |
| Edit issue | Cancel | Return to same edit link |
| Edit issue | Update | Return to same issue checkbox |
| Remove issue | In modal, use close or press escape | last issue remove button |
| Remove issue | In modal, use "No, keep" | Last issue remove button |
| Remove issue | In modal, use "Yes, remove" | Add new issue link |

**Comment by saderagsdale** [comment]
Worked for me using Cara in staging.
