### ISSUE TITLE
Decision Reviews | Technical Spike

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#56931]
## Value Statement
**_As a_** Veteran filing a decision review
**_I want to_** submit forms with validated data and no errors that will impact my submission
**_So that_** I can be confident that the forms and evidence I submit are received and processed

---
## Background Context
This is a timeboxed investigation into the decision review code. As part of our effort to assess the health of decision reviews that have already launched, we want to look at errors that occur through Century and the quality of validation logic on the front end. The goal of this technical discovery is to identify areas for improvement and enhanced logging and monitoring.

## Acceptance Criteria
- [ ] We have identified what errors occur and made tickets for them
- [ ] We have setup logs to help us trace the cause of failures
- [ ] We have a way to get notified about issues that occur with the forms
- [ ] We have a cadence for checking and reporting
- [ ] If there are other enhancing changes we could implement, they are noted here for team discussion

## Tasks
- [ ] Conduct in-depth code inspection
- [ ] Conduct error investigation using Sentry and Grafana logs
- [ ] Learn about how Data Dog handles error states
- [ ] Test drive the [Logging and Monitoring Framework](https://docs.google.com/document/d/1TqBQmbYGF7Xvjzs_2q83qDuoKd9022n153wVl8V4MmI/edit#heading=h.wb43vjfgcjqq), and report back to Jared/Kevin

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by saderagsdale** [comment]
Phases:

Assessment
- Filter queries to reduce noise + identify big issues
- Review existing logging and monitoring to check for things that were once important
- Review the form to understand what actions the form can take (list them out)
- Identify gaps in tracing issues (example: jobs missing from query, downtime from upstream services, add body of errors from upstream services)
- Flag error messages that aren't actionable (backend or frontend)
- If possible, recommend fixes for frontend errors to improve user experience

KPIs
- Craft KPIs for how you measure success for those things

Implementation
- Determine what you want to see in a dashboard (visuals, alerts, grouping/ungrouping)
- Add logging points
- Review with eng (squad 2)

Bugs
- Prioritization and fixes for anything you've identified

**Comment by saderagsdale** [comment]
Ticket #1: Identify KPIs for all five of these forms ("assessment")
Ticket #2: Set up monitoring and logging for these KPIs if not already set up ("implementation")
Ticket #3: Refine sentry error monitoring dashboards for all five forms ("assessment" and "implementation", simultaneously)

Ticket #1 and Ticket #2 must be done in series, and will ultimately result in a series of DataDog dashboards
Ticket #3 will ultimately result in a series of Sentry dashboards (the same ones you already saw, just refined)
Ticket #3 and Tickets #1-#2 can be done in parallel
