### ISSUE TITLE
NOD | Confirm destructive actions

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#56930]
## Value Statement
**_As a_** Veteran editing data I've entered into the form
**_I want to_** receive a confirmation before completing destructive actions
**_So that_** I don't accidentally delete info from the form. 

---
## Background Context

While building the Supplemental Claim form, the collaboration cycle required that all destructive actions be confirmed by the user. For NOD, this will be needed on the contestable issues page for added issues.

## Acceptance Criteria
- [ ] User is asked to confirm their change before removing contestable issues from the form

## Designs and Build Notes
- See [design and a11y notes for Supplemental Claims](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56082) 
- [Link to designs](https://www.sketch.com/s/0424c51d-7818-43ea-8821-6de91eb7ab27/p/B37669FF-D5F8-4A6C-AB28-60F4DF570C9E/canvas)

## Out of scope
- Upload section is a platform change

## Open questions
- Add here

## Tasks
- [ ] Create design for modals
- [ ] Add remove confirmation to contestable issues page
- [ ] Add unit & e2e tests

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by Evafloyd** [comment]
Backlog refinement: Robin: Anytime you remove something from your data, you want to have a modal pop-up. Same as supp claims. It will be needed for issues, same as HLR. For both NOD and HLR you can add issues, so that means, if you remove it, its destructive. You have to add one on staging first, before being able to remove. Can probably just copy the design from Sup claims. 

Gary: remembers seeing edit but not remove.

**Comment by uxgary** [comment]
The design has been updated in the [sketch file](https://www.sketch.com/s/0424c51d-7818-43ea-8821-6de91eb7ab27/p/B37669FF-D5F8-4A6C-AB28-60F4DF570C9E/canvas). 

Review the layers: Contestable issues and Submit additional Evidence.

**Comment by Mottie** [comment]
Work completed, please test these focus management scenarios:

| Start action | Then | Focus result |
|---|---|---|
| Add new issue | Cancel | Add new issue |
| Add new issue | Fill out and Add | New issue checkbox |
| Edit issue | Cancel | Return to same edit link |
| Edit issue | Update | Return to same issue checkbox |
| Remove issue | In modal, use close or press escape | last issue remove button |
| Remove issue | In modal, use "No, keep" | Last issue remove button |
| Remove issue | In modal, use "Yes, remove" | Add new issue link |

**Comment by eileen-coforma** [comment]
This works on staging, and the focus management works.
