### ISSUE TITLE
NOD | Include review error links within the error modal

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#56934]
## Value Statement
**_As a_** Veteran in the process of editing the Review and Submit page of a Request for Board Appeal (NOD) form
**_I want to_** be able to click on a link to the error I need to correct
**_So that_** I can complete and submit the form more efficiently.

---
## Background Context
When form validation shows a generic error, it is not very helpful to the Veteran in narrowing down the source of the error. If we include [review error](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/docs/reviewErrors.md) links within the error modal, this will display a link to each error that once activated, will open the accordion (chapter) and specific page. The page will be placed into edit mode allowing the Veteran to fix the problem and continue with submission.

## Acceptance Criteria
- [ ] User can click a link to open an accordion to edit the error they need to fix
- [ ] User can save in-line edits 

## Designs and Build Notes
- [review error docs](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/docs/reviewErrors.md); we will need content to review each error message

## Out of scope
- Add here

## Open questions
- What are _all_ possible errors that will occur within the form?

## Tasks
- [ ] Determine all possible form errors
- [ ] Content reviews & makes suggestions for error links
- [ ] Add review error links
- [ ] Add tests

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
This would be considered blocked, because there's a larger [review page wicked a11y issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61549), and possible new summary page that would make this not necessary.
