### ISSUE TITLE
HLR | Improve page confirmations and focus management

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#56932]
## Value Statement
**_As a_** Veteran in the process of completing a higher-level review form
**_I want to_** receive confirmations when I make changes and help navigating the form
**_So that_** I know when I've completed an action and I know where I'm at in the form flow.

---
## Background Context
- Add here

## Acceptance Criteria
- [ ] User sees confirmation when making updates to the info they provide
- [ ] Focus guides the user to the area where their attention is required without missing key information

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by saderagsdale** [comment]
@saderagsdale @eileen-coforma Look at the review and submit behavior for DR forms to determine if this may be beneficial.

**Comment by eileen-coforma** [comment]
I was checking how many submission error alerts happen on review and submit because of incomplete data, but I don't see it within our [error alert events](https://analytics.google.com/analytics/web/#/report/content-event-pages/a50123418w177519031p176188361/explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.eventAction&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22RE%22,%22www.va.gov~2Fdecision-reviews~2Fhigher-level-review~2Frequest-higher-level-review-form-20-0996%22,0%5D,%5B0,%22analytics.eventAction%22,%22PT%22,%22error%22,0%5D%5D/). 

I was able to check the [interactions](https://analytics.google.com/analytics/web/#/report/content-event-pages/a50123418w177519031p176188361/explorer-table.plotKeys=%5B%5D&explorer-table.rowStart=0&explorer-table.rowCount=10&_r.drilldown=analytics.pagePath:www.va.gov~2Fdecision-reviews~2Fhigher-level-review~2Frequest-higher-level-review-form-20-0996~2Freview-and-submit~2F,analytics.eventCategory:Interactions/) for the R&S page, and edit actions is the 5th highest event (after expanding accordions). It makes up about 8% of total interaction events.

Stats for 7 days (1,532 submissions in this time period)
<img width="1441" alt="Screenshot 2024-05-20 at 1 17 00 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/111457818/c5f5cc87-4a85-48f8-a584-c30a29b05dd7">

Stats for 1 month (6,186 submissions in this time period)
<img width="1439" alt="Screenshot 2024-05-20 at 1 16 09 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/111457818/2f46569f-fa2e-4457-be02-1be473ee6563">

Given these statistics, @saderagsdale what are your thoughts on the possible impact for this work?

**Comment by saderagsdale** [comment]
Hit pause on this until other work runs out.
