### ISSUE TITLE
Board Appeals Interviews | Conduct Sessions

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#56942]
## Value Statement
**_As a_** UX researcher on the Benefits team
**_I want to_** conduct sessions with Veterans
**_So that_** the team can have a fundamental understanding around user needs.

---
## Background Context
The Request for Board Appeal form was released in April 2022 and is overdue for a post-launch review of the feature. The scope of this evaluative discovery includes reviewing qualitative and quantitative data, redefining product outcomes, and identifying opportunities for improvement and ways to measure the impact of our work on the form.

## Acceptance Criteria
- [x] Capture research findings from interviews

## Out of scope
- Synthesis

## Open questions
- What approach to testing are we going forward with?

## Tasks
- [x] Schedule pilot
- [x] Setup note-taking board
- [x] Send observer schedule

## Definition of Ready
- [x] Recruitment kickoff
- [x] Pilot test
- [x] Note-taking board
- [x] Sign-up schedule
- [x] Observer kickoff

## Definition of Done
- [x] All sessions completed
- [x] Notes on the board

**Comment by eileen-coforma** [comment]
Added some details to this

**Comment by eileen-coforma** [comment]
Moved to blocked until recruitment is done and studies can start.
