### ISSUE TITLE
[Bug] Veteran Cannot Upload Large Numbers of Claims Evidence

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#5694]
## User Story:
As a veteran, I need to be able to submit large numbers of and sizes of claims evidence so that I can get a proper review of my claim.

**Summary:** A Veteran has been trying to upload 500+ pages of documents as part of his disability claim and erroring out. They have been able to get these details from the Veteran:

1. It was 15-20 files, each ranging between 1 and 5 MB. He said it will allow him to attach the files but then the error occurs upon submitting.
2. VA Form 21-526EZ: https://www.va.gov/disability/file-disability-claim-form-21-526ez/introduction
3. He has tried both Google Chrome and Microsoft Edge.

We need to explore whether this is a bug on the VSA-side or downstream from us.  Could be part of the file extension issue.  Or could be a size limit, submission limit.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] Setup time with Veteran
- [ ] Explore file extension angle (#5467)

## Acceptance Criteria:
* The veteran is able to submit all of their files.

## Configuration
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ndsprinkle** [comment]
This is an interesting bug, it definitely could be related to how many the user is trying to upload simultaneously, because I have one user that I've uploaded hundreds of files to, but they were all one at a time.

**Comment by Andrea** [comment]
Please use correct GitHub handle

**Comment by luke-gcio** [comment]
Copy/paste had Andrea's Slack handle and it pulled in another Andrea :)

**Comment by luke-gcio** [comment]
Andrea sent a note to the veteran, waiting to hear back.

**Comment by luke-gcio** [comment]
Looks like the veteran was able to split the submission into two claims and it worked.  Icebox for now.

**Comment by Andrea** [comment]
Please stop using my handle

Andrea

**Comment by luke-gcio** [comment]
Your handle is not being used above you may have to manually unsubscribe at this point since you commented on the GitHub issue.

**Comment by luke-gcio** [comment]
Has not come up again, closing.
