### ISSUE TITLE
Board Appeal Interviews | Research Plan

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#56941]
## Value Statement
**_As a_** UX researcher and designer on the Benefits Decision Review team
**_I want to_** create a document detailing research goals, objectives, and research methods
**_So that_** the team can be aligned on the research scope

---
## Background Context
The Request for Board Appeal form was released in April 2022 and is overdue for a post-launch review of the feature. The scope of this evaluative discovery includes reviewing qualitative and quantitative data, redefining product outcomes, and identifying opportunities for improvement and ways to measure the impact of our work on the form.

## Acceptance Criteria
- [x] Have clear goals and objectives
- [x] Has a hypothesis about how we help Veterans by improving the NoD experience
- [x] Serves to guide research efforts in a way that the outcomes identify actionable areas of improvement for our product
- [x] Has a clear timeframe and milestones
- [x] Has conversation guide
- [x] Approved by collab cycle
- [x] Recruitment kicked off

## Designs and Build Notes
- [Research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/decision-reviews/Notice-of-Disagreement/Research/042023%20NoD%20Evaluative%20Research)
- [Research plan](https://docs.google.com/document/d/11CuZRCXug64T29uZ1i4ldn-r96D5e9UQqn9OSPzoX00/edit)
- [Recruitment ticket (and screener)](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/318)
- [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/Research/042023%20NoD%20Evaluative%20Research/conversation-guide.md)
- [Research ticket](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/319)

## Out of scope
- Add here

## Open questions
- What areas of the board of appeal form can we improve and have timely data that we can use to track the impact of our work?

General questions that could apply to any decision review pathway
- Is it clear to Veterans that Board Appeal is the right pathway for them? 
- Are the Veterans using the anticipated wait length to influence decision pathway choice?
- What's the use of informal conference, and how is it carried out through decision reviews?
- Can vets using assistive technology navigate and make edits on this page efficiently?
- Where is the veteran experiencing the most friction when filing Board Appeal?
- Are notifications received useful? Do they receive an email when submitting?
- is there a scenario where vets submit again because it doesn't show in CST?
- how long does it take for status to appear in CST?
- how long does it take before folx hear back about their next steps 

Board Appeal Specific Questions
How confident do veterans feel when they start Board Appeal?
- What do Veterans call NOD?
- Does the VSO submit through a separate system? assuming yes
- When does a veteran decide to file an NoD? (longest process with backlog)
- Is the deadline screen conditional to the account? Why is it shown here?
- Do contested claims show up the same way as normal claims?
- Why do veterans choose specific hearing type

## Tasks
- [x] Review findings from discovery efforts
- [x] Conduct learning goals session with the broader team
- [x] Refine research questions
- [x] Identify research method
- [x] Refine recruitment criteria for research study
- [x] Create draft for research plan
- [x] Refine plan with Matt Self and team
- [x] Kick-off research with research collab cycle team

**Comment by uxgary** [comment]
@eileen-coforma and @Evafloyd I've added some info to this ticket. Fee free to make any updates.

**Comment by eileen-coforma** [comment]
Added a few things to the design build notes. We can aggregate the links when we get to this ticket.

**Comment by eileen-coforma** [comment]
Research review ticket requested: https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/319
