### ISSUE TITLE
Board Appeal Discovery | Review existing data

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#56940]
## Value Statement
**_As a_** team
**_We want to_** review past research and existing analytics and talk to SMEs
**_So that_** we can align on background, goals, and next steps for the Board Appeals form.

---
## Background Context
The Request for Board Appeal form was released in April 2022 and is overdue for a post-launch review of the feature. The scope of this evaluative discovery includes reviewing qualitative and quantitative data, redefining product outcomes, and identifying opportunities for improvement and ways to measure the impact of our work on the form.

## Acceptance Criteria
- [x] Have an understanding of the current state of the digital board appeals form
- [x] Have research strategy that addresses some of the qualitative discoveries
- [ ] Have an outline of discoveries made during review

## Designs and Build Notes
- [Research strategy](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/Research/042423%20Research%20Strategy.md)
- [Decision reviews knowledge base (WIP)](https://app.mural.co/t/coforma8350/m/coforma8350/1679600983883/c565af371b4772fe601b1ab9df7a4a8212b7f7e9)
- [NoD knowledge base / screen flow](https://app.mural.co/t/coforma8350/m/coforma8350/1669650678748/65486e34976eacb8fb1d97ed0abc9877b37caff2?sender=udbf574074425980f04c55360)
- [NoD Desk Research](https://docs.google.com/document/d/1cWaD7OW_gWLYrc7iw_YZ_YFVaAp12llWZVTSsBD13js/edit?usp=sharing)

## Out of scope
- Add here

## Open questions
Quant Data Q's
- What points along the Board Appeal journey currently have the highest dropoff rate?
- What opportunities have been captured in the Medallia survey? 
- What is the baseline satisfaction rating for Board Appeal?
- Does the digital form improve user satisfaction?
- Can we find out if there are instances where veterans are trying to use the 'application ID' for reference after submission?

## Tasks
- [x] Review Google Analytics, DOMO data (Gary)
- [x] Place dropoff rates on journey map (Gary)
- [x] Synthesize Medallia data provided (Eileen)
- [x] Review VA411 (contact center) data provided (Eileen)
- [x] Gather questions about board appeal process to ask SME
- [x] Create discovery brief in Github

**Comment by eileen-coforma** [comment]
@Evafloyd @uxgary Filled out some preliminary information for the ticket. Please add/edit with anymore relevant information.

**Comment by Evafloyd** [comment]
I added a few questions to this ticket to help focus the discovery, and modified the title so its clear this is Board Appeal

**Comment by saderagsdale** [comment]
Added three more SME questions

**Comment by eileen-coforma** [comment]
Separated out the SME discussions to another ticket for next sprint: https://github.com/department-of-veterans-affairs/va.gov-team/issues/57522

**Comment by eileen-coforma** [comment]
Reopened this to add a tangible deliverable for this work (apart from the Mural board)

**Comment by eileen-coforma** [comment]
Completed and shared [Board AppealsData Discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/Research/042023%20NoD%20Evaluative%20Research/Board%20Appeal%20Existing%20Data%20Discovery.md) in Github.
