### ISSUE TITLE
Remove Sign-in service metrics from initializer

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/va.gov-team#56949]
## Summary

Metrics initialized to 0 are causing issues with the new EKS implementation. The default type for metrics in datadog is `rate` (which EKS sends)  but `BRD` is sets type to `count`. Metrics are still being initialized in BRD which is clashing with metrics being created in EKS causing frequent flipping between `count` and `rate`. Remove sign-in service metrics from initializer as a test and then remove the initializer if it's not necessary anymore.
https://vagov.ddog-gov.com/dashboard/fdk-gs9-nb5/sign-in-service-brd-metrics?from_ts=1681655986345&to_ts=1681742386345&live=true

## Tasks

- [x] Remove sign-in service metrics from initializer

## AC
- [x] Metrics are not flipping
- [x] Metrics are being collected
