### ISSUE TITLE
[BE] Implement phone_number method in TravelClaim/RedisClient

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#56976]
## Description
In order to address the concern of notifying travel claims to a different phone number (Ref [VANotify intake ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55526)), vets-api should cache the patient phone number and retrieve from Redis to call VANotify API.

Modify `travel_claim/service` interface `redis_client` to read patient `mobilePhone` from Redis to use in VANotify API call.

## Tasks
- [ ] [BE] **Implement phone_number method to retrieve phone number from Redis**
- [ ] [BE] **Add rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
