### ISSUE TITLE
[BE] Modify Appointment Data Serializer to Cache Phone number

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#56975]
## Description
To avoid the mismatch of the phone number used for check-in and travel claims notifications, vets-api needs to cache the phone number that veterans used to send check in text for day-of check-in. [Reference: [VANotify Intake Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55526)]

## Tasks
- [ ] [BE] **Modify Appointment Data Serializer to cache phone number**
- [ ] [BE] **Add rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
