### ISSUE TITLE
ITF expiration error discovery

### ISSUE THREAD

**Issue by Nyanteea** [department-of-veterans-affairs/va.gov-team#56987]
## Issue Description

Survey feedback from several users suggests that there may be an issue when veterans try to complete their form too close to the end of their ITF. Some responses suggest that ITF time is reset or erased prior to the actual expiration date. 

There maybe different wordings for these messages. Can we get some of those responses?

---
## Tasks
- [x] Development/UX discovery around the issue and its source 

## Acceptance Criteria
- [x] Summary of problem discovery in this ticket 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Nyanteea** [comment]
helpful context: 

quote from survey:
" I logged in repeatedly and selected 'Continue Application....' then I repeatedly got an error message saying "Oops, Something went wrong on our end. Today was the deadline to file before my Intent to File Expired. I tried two different devices and two browsers."

**Comment by tblackwe** [comment]
@micahaspyr the two things I think we should check on this:

- Is ITF date being treated as exclusive not inclusive by the system
- What timezone is ITF date being calculated in ?

**Comment by micahaspyr** [comment]
Looks like there is some strange caching going on here that should expire a day before the ITF expires.  Not totally understanding why this is needing to be cached.  Looks to have been written five years ago, so I'll look to track the author down but I'm not seeing that they still work on this

**Comment by micahaspyr** [comment]
### Intent To File Expiration (ITF) Issue

Some users are stating that they are unable to process their 526 form when it is close to the ITF expiration. A generic “Oops, Something went wrong on our end” message is then shown when they try and continue their 526 form input.


**Likely Causes(s)**

Expiration date isn’t taking other time zones into account

**Source of data**

A check is done whenever a user tries to start or continue their 526 claim.  The data is pulled from an EVSS/LH api endpoint that returns active ITF.  If the expiration date has been surpassed, an error is thrown (The “Oops, Something is wrong on our end”)

**Issue(s)**

- A user can not file their claim

- Generic error message gives no clarity into what the actual problem is

**Possible Fix(es)**

- Add a buffer to the expiration date to account for all US time zones (Hawaii being the furthest behind?). This could be done on the EVSS/LH side but would require a request for change

- Instead of asking EVSS/LH to change the way ITFs are created, we can pull down the user’s entire ITF list and check if expired ITF’s expiration date is within a certain buffered range or scope the expiration date to their time zone 

- Do a combination of the two choices above.  Put in the temporary fix while the API devs consider making the change on their side


Reach out to EVSS team in charge of creating the intents to file, then go from there as it’s not an error seen everywhere.

**Comment by austinjprice** [comment]
@nnicholas7 can we add this error message to the Form Validation Tracker for improved messaging. This will be in addition to asking LH to increase the buffer because as of right now, the end date is EXACTLY one year, e.g. if user begins at Jan 1 at 2 pm central it will end one year from Jan 1 at 2 pm central. 

Thoughts to consider:
1. Time zones (most lenient?)
2. Leap year?
3. In general we want to make sure the 1 year distinction given to the user allows them to submit at any time on the day of expiration and any error message due to expiration is clearly stated.
