### ISSUE TITLE
[technical discovery] 686c | Figure out why SSNs become redacted when passed across functions

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#56993]
## Issue Description

While working on https://github.com/department-of-veterans-affairs/va.gov-team/issues/56333, I discovered that we were sending redacted SSNs to BGS.  See https://github.com/department-of-veterans-affairs/vets-api/pull/12410 for detail.  In that PR, I drafted a short-term fix to "refresh" a User's ssn before sending it to BGS. That short-term fix worked. See https://github.com/department-of-veterans-affairs/va.gov-team/issues/56333#issuecomment-1511680163.  

Now, I'd like to understand how the user's ssn transformed into a redacted string in the first place. It's a bad code smell that raises the specter of a broader issue.

---
## Tasks
- [ ] Figure out why it's happening
- [ ] Determine whether worth changing this behavior
- [ ] If worth changing, briefly assess wider impact across VA

## Acceptance Criteria
- [ ] Tasks above complete. 

---

**Comment by sortizsh** [comment]
wait until after we push our encrypted data to see if we still see this issue happening

**Comment by tblackwe** [comment]
resolved by encrypted data. 
https://vagov.ddog-gov.com/logs?query=%40message_content%3A%22Malformed%20SSN%21%20Reassigning%20to%20User%23ssn.%22%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=paused&storage=online_archives&stream_sort=desc&viz=stream&from_ts=1698120000000&to_ts=1699156740000&live=false

closing ticket.
