### ISSUE TITLE
AVS Create Product Outline

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#56990]
#Description
Create a product outline to explain the AVS product.

# Tasks
- [X] Copy this [template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)
- [X] [Create document on GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/avs/README.md)
- [X] Write outline

# Acceptance Criteria
- [X] Post[ outline for review by team on Slack](https://dsva.slack.com/archives/C04UBETRY8N/p1681761872886469)
