### ISSUE TITLE
Send survey draft to SD team for review

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#57023]
## Issue Description

- [The research plan](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2588278812/Platform+Website+User+Experience+Research+v.2) has been scoped down with fewer objectives

- The initial method to gather feedback about the Platform website is through the use of an online survey that will be shared with VFS team members.

- It is time to share the survey draft with the Service Design team so they can review it and provide any necessary feedback.

---
## Tasks

- [x] Send revised research plan and survey draft to Service Design: https://dsva.slack.com/archives/CPCGRR7F1/p1681828730254759?thread_ts=1679501102.512609&cid=CPCGRR7F1

- [x] Make any necessary edits to the research plan or survey based on Service Design team's feedback

## Acceptance Criteria
- [x] The Service Design team will have reviewed the survey draft and provided to us any necessary feedback

## Artifacts
- [Research plan v2](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2588278812/Platform+Website+User+Experience+Research+v.2)
- [Research action plan](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2598338590/Platform+Website+UX+Research+Action+Items)
- [Link to survey](https://airtable.com/shrT0FFoghjzQI3MR)
