### ISSUE TITLE
Communicate the newly streamlined UXR collab process

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#57029]
## Purpose
Now that the "How to work with SDT" landing page and relevant guiding documentation are updated, it's time to market this updated offering to Platform Teams.

## Tasks
- [ ] Create a communication plan that lets Platform Teams know how to collaborate on UXR with SDT
- [ ] Announce in Slack, and update any channel descriptions
- [ ] Announce and showcase at Demo Day

## Acceptance Criteria
- [ ] Communication plan is created
- [ ] Updated process is communicated via appropriate methods
