### ISSUE TITLE
Content changes to COVID pages around monovalent vaccines

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#57032]
## Issue Description

The FDA is no longer authorizing monovalent vaccines and boosters. We'll need to make changes to our COVID-19 pages to reflect this. These pages may include:

- [COVID-19 vaccines at VA](https://www.va.gov/health-care/covid-19-vaccine/)
- [COVID-19 booster shots](https://www.va.gov/health-care/covid-19-vaccine/booster-shots-and-additional-doses/)
- [About COVID-10 vaccines](https://www.va.gov/health-care/covid-19-vaccine/about-covid-19-vaccine/)

## Tasks
- [x] Update pages in Drupal 
- [x] Send for SME approval (Danielle)
- [x] Copyedit (Megan)
- [x] Publish (Megan)
- [x] Set up translation ticket (Randi)

## Acceptance Criteria
- [x] Changes are live on the site

**Comment by RLHecht** [comment]
Update: We made some tweaks to these pages and published on 4/21. We're still waiting on CDC final recommendations before making the rest of the changes to these pages.

**Comment by RLHecht** [comment]
@megzehn the main vaccines page is now ready for you to copyedit and publish. Laura and I worked on the text in the blue box and got it OK'ed by our SME. There will be more changes at a later date once CDC issues further guidance on immune compromised individuals.

**Comment by RLHecht** [comment]
@megzehn this page is ready for you again. CDC made their official recommendations for immuno compromised so we updated the language in the blue box again. Can you copyedit and publish? Thank you!

**Comment by megzehn** [comment]
Thanks, @RLHecht! This is published.

**Comment by RLHecht** [comment]
Thanks all! I sent the new changes to the translation team. This is ready to close.
