### ISSUE TITLE
Design improvements to Cerner handoff

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#57036]
## Task Description
This work:
- Review and recommend design improvements to the Cerner widget on the static landing page
- Add a handoff to Cerner from the Appointments landing page

## References
- MHV on VA.gov phase 1 workflow. Note: design here is not set in stone.
    - [Static landing page](https://www.figma.com/file/0wG5mpi760FGvVh89phapu/User-flow-for-MHV-Portal-to-Appointments?node-id=540-1952&t=hdOrQMKAxxkSuxe8-4)
    - [Cerner widget on home page
](https://www.figma.com/file/0wG5mpi760FGvVh89phapu/User-flow-for-MHV-Portal-to-Appointments?node-id=708-2712&t=hdOrQMKAxxkSuxe8-4)
    - [Slack thread](https://dsva.slack.com/archives/CE4304QPK/p1681839358623199) re: MyVA proposed changes to static landing page Cerner portal.
## Acceptance Criteria
- [x] Workflow spec (if changes)
- [x] Design spec for new Cerner handoff on Appointments landing page:
    - [x] Includes scenario: VistA + Cerner user
    - [x] Includes scenario: VistA + Cerner user AND VistA is only displaying some appointments
- [x] Requirements/recommended changes for the MHV LIFERAY appointments landing page
- [x] Requirements/recommended changes for the appointments static landing page

## Design Links

- [Appointments list page](https://www.figma.com/file/iqjkZx2EbrZu6leL6YfN45/Cerner-Handoff?type=design&node-id=1222%3A26182&mode=design&t=q1PVhmDd2VI4Yt8M-1) 
- [Design recommendations for the landing page](https://www.figma.com/file/iqjkZx2EbrZu6leL6YfN45/Cerner-Handoff?type=design&node-id=1222%3A30393&mode=design&t=q1PVhmDd2VI4Yt8M-1)

## Landing Page recommendations
- Consider reducing text length on alert header to minimize clutter [See here](https://www.figma.com/file/iqjkZx2EbrZu6leL6YfN45/Cerner-Handoff?type=design&node-id=1151%3A15782&t=fihgBUGa3I3sC15o-1)
- Consider listing the facilities for the corresponding portal with only one link to the portal as opposed to one for each facility to simplify and reduce noise. [See here](https://www.figma.com/file/iqjkZx2EbrZu6leL6YfN45/Cerner-Handoff?type=design&node-id=1151%3A15774&t=fihgBUGa3I3sC15o-1)
- Consider changing content to simplify alert. [See here](https://www.figma.com/file/iqjkZx2EbrZu6leL6YfN45/Cerner-Handoff?type=design&node-id=1151%3A15760&t=fihgBUGa3I3sC15o-1)
- Consider changing buttons to [active links](https://www.figma.com/file/iqjkZx2EbrZu6leL6YfN45/Cerner-Handoff?type=design&node-id=1151%3A15778&t=fihgBUGa3I3sC15o-1) or [standard text links](https://www.figma.com/file/iqjkZx2EbrZu6leL6YfN45/Cerner-Handoff?type=design&node-id=1151%3A15786&t=fihgBUGa3I3sC15o-1)

**Comment by outerpress** [comment]
@Cieramaddox I added a couple of scenarios under the AC's, let me know if you have questions.

**Comment by Cieramaddox** [comment]
@outerpress I think these cover them. Ready for review.

**Comment by outerpress** [comment]
This is in review by the CAIA team. [Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59293)

**Comment by Cieramaddox** [comment]
@ldelacosta Design specs have been updated

**Comment by outerpress** [comment]
Dev work is done, closing. Will reopen follow-up ticket if other changes are needed
