### ISSUE TITLE
Tier 3 Issue Escalation Processes

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#57048]
## Issue Description
The Contact Center Support team does not have official documentation for handling Tier 3 issues that have a specific process that doesn't involve investigation by a VFS team (i.e. filing a github issue for incorrect content, what is routed to EVSS, etc.). 

As a user handling and resolving Tier 3 issues, I want to know how to escalate all Tier 3 issues correctly and follow the identified processes. 

---
## Tasks
- [x] Identify all Tier 3 processes that are outside the scope of a VFS product team.
- [x] Document the identified issues and the escalation/resolution process
- [x] Have document reviewed by EVSS lead (Jeremy Haas) for feedback
- [ ] Have reviewed documentation uploaded to the correct location for ongoing use and maintenance

## Acceptance Criteria
- [ ] A finalized document that is stored in the correct location
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
Reviewed the document with Jeremy and got the approval. Will upload to teams and github or confluence.

**Comment by ATMiddleton** [comment]
Document will be uploaded in Teams on the VA side and confluence.
