### ISSUE TITLE
Create Parameterized Workflow for Custom Preview Environment

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#57047]
## Issue Description
We need to give users the ability to create a custom workflow that will meet their use case for a Preview environment. This workflow should be able to be triggered from one place and contain customizations that help the user tailor the PE to their needs.

---
## Tasks
- [ ] Build a centralized workflow in the devops repo that contains customizations for vets-website, vets-api, expiration time, and the source repository
- [ ] Rework any logic as necessary to allow these values to take priority when used.

## Acceptance Criteria
- [ ] Custom PEs can be generated with custom branches of both vets-api and vets-website.

**Comment by CBonade** [comment]
Current status:

I have a working workflow here: https://github.com/department-of-veterans-affairs/devops/actions/workflows/preview-environment-custom.yml

This can be launched by pushing the "Run Workflow" button and filling in the parameters. This successfully passes these parameters to the other preview environment workflow and kicks off the process as usual. However:

The other workflows that are part of the PE process will need modifications to complete the implementation of this functionality. Vets-website and vets-api both have open pull requests to add this functionality, however, only vets-website has been tested and confirmed working at this point as I have not yet merged the vets-api one.

The last step, is the primary devops workflow that writes the values file will need to be updated to work with the new conditions that custom variables present.

That said, I do believe the current progress of this ticket satisfies the requirement of a parameterized workflow that launches our preview environment deployment process. Further tickets would be:

- Test vets-api and vets-website workflows for how they respond to custom PEs being launched and adjust anything that does not work correctly.
- Update devops workflow to receive the new values and alter the values file in accordance with expectations.

**Comment by pjhill** [comment]
Something is a bit off here --
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/f91c4ad6-da78-4b9a-be46-cb248c6692d2)
