### ISSUE TITLE
HLR | Update focus from breadcrumbs to unique H3 headers

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#57045]
## Value Statement
**_As a_** Veteran using a screenreader to navigate through the form
**_I want to_** know what page I'm on in the form
**_So that_** I know where I'm at in the form flow and I understand when the page has changed. 

---
## Background Context
This is an improvement in accessibility. 

## Acceptance Criteria
- [ ] Focus is removed from breadcrumbs and instead placed on unique H3 headers
- [ ] A screenreader can pick up the H3 and read it to the user

## Designs and Build Notes
- [Content Source of Truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/higher-level-review/design/content-source-of-truth.md)

## Tasks
- [ ] Add H3s to the form where needed
- [ ] Update focus

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by saderagsdale** [comment]
Gary to circle back after talking through content with Beth today at 3ET.

**Comment by jaredcunha** [comment]
Scoping out extra functionality:
- Headings are not interactive, so `tabindex="-1"` must be applied to the heading before sending `focus()`
- Requires a `blur()` event listener to remove the `tabindex` attribute after a blur event to prevent users from being able to click on the heading and setting focus after it's no longer necessary.

**Comment by Mottie** [comment]
Hey @jaredcunha!

We're using the platform `focusElement` function which has been updated to add the `-1` tabindex and automatically remove it on blur ([link to code](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/utilities/ui/focus.js#L25-L36)).

**Comment by saderagsdale** [comment]
@eileen-coforma will confirm if this is ready for pickup.

**Comment by saderagsdale** [comment]
@eileen-coforma can you shoot Katherine a note and see if they have any more feedback?

**Comment by eileen-coforma** [comment]
@saderagsdale Katherine is done with the edits, but they need Beth's approval before giving it to our team, which she requested last week. I sent a message to Randi on our ticket to see if we need to wait for Beth or if we can have someone else approve.

**Comment by eileen-coforma** [comment]
Beth gave an update that they will be done with it in the sprint.

**Comment by eileen-coforma** [comment]
@saderagsdale @Mottie 
Content came back with updates. I've updated the CSoT to reflect the edits.

A few things they came back with that may not be within the scope of H3s, but are beneficial content updates include:
1. We're recommending changes to 1 H3 about the reason you disagree with your claim decision, 1 H3 about requesting an informal conference, and 1 H3 about your scheduling availability. There are 5 other places in the form (non-headers) we should update to match the new language. The changes are pretty straightforward.
2. On the [intro page of the form in staging](https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/introduction), we should consider getting rid of steps 3 and 4 "VA review" and "Decision." The Veteran doesn’t have to complete these steps, so they don’t need to be listed as steps.
3. On the [intro page of the form in staging](https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/introduction), we noticed that the H2s had H2 tags with H3 font size. And the H3s had H3 tags with H4 font size. Is that intentional?

1. Is directly related to the headers and will be affected by the language change we're doing on headers. I think it can be included within this ticket. Do we want a separate ticket for 2 and 3?

**Comment by saderagsdale** [comment]
@eileen-coforma Let's move everything that's not related to the original scope of this ticket to a separate ticket.  Then we can refine that work separately.

**Comment by saderagsdale** [comment]
@joshkimux can you take a look this one, too?

**Comment by joshkimux** [comment]
Sure can do!

**Comment by saderagsdale** [comment]
Investigating unrelated unit tests that are failing. Will post in platform support or re-run flaky tests if needed.

**Comment by rocio-desantiago** [comment]
@joshkimux PR just merged. I imagine it may be ready in staging by tomorrow.
I removed the redundant decision date as discussed with you and Eileen.

<img width="592" alt="decision-date-dupe-removed" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/37054305/04776651-e339-447d-baea-5ec56095ef78">

**Comment by rocio-desantiago** [comment]
@joshkimux woohoot it made it to [prod](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/) today.

**Comment by saderagsdale** [comment]
@joshkimux Mind validating this one when you have a moment?

**Comment by saderagsdale** [comment]
@Mottie will check on this issue @joshkimux

**Comment by Mottie** [comment]
It looks like we've got a backend (bad gateway) server error happening - @kylesoskin is investigating

**Comment by kylesoskin** [comment]
@Mottie @joshkimux  this works locally :( , so I think this is an issue with the staging user's data? or with a setting set in staging? I am not sure yet... but it will take some more investigating, which I am doing.

**Comment by Mottie** [comment]
@joshkimux You should be able to test this now!

**Comment by joshkimux** [comment]
This is working like a dream! Awesome work y'all 💙 
Just some notes for history purposes:
- Focus management does not work well on the review answers page due to larger issues out of our immediate control (fingers crossed this page gets worked on by the DST at some point soon)
- This remains to be our best next step until we can fully transition to a simple form header ✨ 

Thanks to everyone for working on this, I think we're ready to close this 😄
