### ISSUE TITLE
NOD | Update focus from breadcrumbs to unique H3 headers #57045

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#57046]
## Value Statement
**_As a_** Veteran using a screenreader to navigate through the form
**_I want to_** know what page I'm on in the form
**_So that_** I know where I'm at in the form flow and I understand when the page has changed. 

---
## Background Context
This is an improvement in accessibility. 

## Acceptance Criteria
- [ ] Focus is removed from breadcrumbs and instead placed on unique H3 headers
- [ ] A screenreader can pick up the H3 and read it to the user

## Designs and Build Notes
- Need content for this.

## Tasks
- [ ] Add H3s to the form where needed
- [ ] Update focus

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by saderagsdale** [comment]
Gary to circle back after talking through content with Beth today at 3ET.

**Comment by jaredcunha** [comment]
Scoping out extra functionality:
- Headings are not interactive, so `tabindex="-1"` must be applied to the heading before sending `focus()`
- Requires a `blur()` event listener to remove the `tabindex` attribute after a blur event to prevent users from being able to click on the heading and setting focus after it's no longer necessary.

**Comment by Mottie** [comment]
Hey @jaredcunha!

We're using the platform `focusElement` function which has been updated to add the `-1` tabindex and automatically remove it on blur ([link to code](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/utilities/ui/focus.js#L25-L36)).

**Comment by saderagsdale** [comment]
@eileen-coforma will confirm if this is ready for pickup.

**Comment by eileen-coforma** [comment]
@Mottie @saderagsdale This is good to go. Source of Truth is updated with the edits that Content had.

**Comment by saderagsdale** [comment]
@joshkimux Howdy - does this one look good to close?

**Comment by joshkimux** [comment]
@saderagsdale great question! It depends. I need to comb this through with a fine comb this week in my audit to make sure it's still working in all navigational instances. Will have an update for you before EoD Friday!

**Comment by saderagsdale** [comment]
@joshkimux thank youuuuu

**Comment by joshkimux** [comment]
I've tested this through, and for the most part it's working great! There are some unique bugs though that intersect with the profile team's work.

@saderagsdale what do you think about closing this out? I can open up unique tickets to cover the odd cases.

**Comment by saderagsdale** [comment]
@joshkimux sounds good! Thank you Josh!
