### ISSUE TITLE
Engineering/Architecture Spike to determine best path for Trusted Referee user data to be stored/accessed

### ISSUE THREAD

**Issue by jrjamespdx** [department-of-veterans-affairs/va.gov-team#57049]
### Issue Description
_From IPP Kick-off:
Given the information documented in issue [56818](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56816), determine the best path forward for storing and retrieving necessary user information for managing Trusted Referees in our proposed IPP Trusted Referee Management system.

### Tasks
- [x] Using the information documented in [56816 ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56816)and proposed architectural ideas for IPP Trusted Referee Management, outline the different possible approaches and the pros/cons of each.
- [ ] Discuss different approaches with Anthony/Porta and engineering team.
- [x] Based on the discussions from the previous task, select a path forward and document that path in this issue.

### Acceptance Criteria
- Paths that are not available to use (MPI, Sign-In Service, etc) are clearly documented as such in this issue.
- Potential paths forward are documented in this issue for use in architecture/systems design tasks.
- If other information is needed to start architecture/systems design, new spike tickets are created and assigned to reflect the necessary investigations.

**Comment by jrjamespdx** [comment]
Path forward:

This service will utilize its own database to store the information necessary to establish authorized user access to the service as well as to store information regarding the users themselves.  This will allow us to change/modify/iterate on our data model while avoiding additional dependency on other systems/teams such as IAM.  A work in progress data model will be created as further details emerge throughout the Product-Engineering collaboration cycle.
