### ISSUE TITLE
[BE] Update TravelClaim Response to include 'code' in response body when status is 200

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#57042]
## Description
Currently the body doesn't include a code when the response is 200, but it does when the response is an error. Including a 'code' for all responses will help make it easier to decide which template to use when sending notifications.

## Tasks
- [x] [BE] **Update Response to include code in the body when 200 response is received from BTSSS**
- [x] [BE] **Update/Add rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
