### ISSUE TITLE
[PM] Address validation: Determine what analytics we need for this feature

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5705]
## Background

Part of the pre-launch checklist.

Also, Erik has started the conversation about analytics here #4597. Need to figure out if we need anything else than what he has already suggested.

## Tasks

- [x] Determine what analytics we need
- [ ] Review with team
- [ ] Create analytics implementation ticket

## Acceptance criteria

- [ ] Analytics implementation ticket is created

**Comment by Samara-Strauss** [comment]
Pretty sure this is what we need:

1. Track how often the address validation screen is triggered
2. Track the different alert types:
 - Override w/ suggestions
 - Override w/ no suggestions
 - Add unit number
 - Edit unit number
3. How many people edit their address from the address validation form
4. How many people select a suggested address
5. How many people choose to override and use the address they originally entered

**Comment by Samara-Strauss** [comment]
Based on the team discussion, we probably don't really need to know how often people edit.

**Comment by Samara-Strauss** [comment]
Changed my mind and added "edit" back in. It might be helpful to know if people select that at all to understand if address validation is triggered because of typos or other reason. If no one is choosing it, people probably feel that what they entered was correct or that a suggested response will do.

Implementation request in #5895. Closing.
