### ISSUE TITLE
[FE] - Unified app feature based routing

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#57069]
## Description

setup feature for unified experience and create switch board for routing.

Details are still TBD

Somewhat related slack convo: https://dsva.slack.com/archives/C04GDQSHD1R/p1680713730288409
## Tasks
- [ ] [FE] Create route to new application & new FF
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Here is a POC for when we pick this work backup:

- vets-website: https://github.com/department-of-veterans-affairs/vets-website/pull/24038
Adds a small react app that routes based on feature toggle and url param. Also adds a minimal template that excludes wrappers based on lay defined in content-build

- content-build: https://github.com/department-of-veterans-affairs/content-build/pull/1536
Adds the app in registry along with a template that only imports the header and react-loader. A value of `"noHeader": true` is added  to the registry to prevent the header from fully rendering.

- Other considerations needed for this to work would be a change the the URL shortener to build short URLs that go to the router with an app param rather than routing to the apps themselves.

**Comment by loripusey** [comment]
closing for now
