### ISSUE TITLE
Medallia Dashboard Creation Process 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#57061]
## Product Outline
[Medallia Dashboard Creation Process ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a Medallia User, I need to access Custom surveys so I can have specific data relative to direct survey questions. 

## Hypothesis or Bet
**If we have custom surveys, internal groups can request specific data and access dashboards with targeted data. 

## OKR
Medallia Dashboard Creation Process - - custom surveys – determine how internal groups request custom surveys – and how they access the data – future management of the process – determine how to work with teams who requests custom surveys and how Sarkis would manage creating dashboards. 

### What must be true in order for you to consider this epic complete?

- [ ] Established template (OOTB) dashboard that can be initially setup with Medallia team
- [ ] Created streamlined process for requesting access to custom Medallia dashboard and how to request any updates to that dashboard.
- [ ] Fully documented process for easy reference by Contact Center Support Team and all other VFS team.  

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by ATMiddleton** [comment]
Dashboard created and functional https://va-gov.domo.com/page/825663825
