### ISSUE TITLE
Migrate POST call to /intenttofile from eVSS to Lighthouse

### ISSUE THREAD

**Issue by mchae-nava** [department-of-veterans-affairs/va.gov-team#57064]
## Issue Description
The eVSS is being deprecated and the vets-api utilizes these services to retrieve and post data.
One of these services is the Intent To File service that indicates user's intention to file a claim for benefits and is filed when a user starts a new claim.
This eVSS endpoint is being sunsetted with the eVSS in Aug.

We need to migrate any calls to the eVSS intent to file endpoint to the Lighthouse version.

## Need To Know
- [ ] Lighthouse team Dash worked on this endpoint
- [ ] Team Dash contacts - https://app.mural.co/t/agilesixapplications0942/m/agilesixapplications0942/1674666875176/5bffb27d080685913fc74b5e4e2179511e4c2089?sender=ub46ab2ca03c3ddd9a8ac0157

---
## Notes
- Permission on resources to allow creation in a remote DB
- Test CRUD operations in higher environments

---
## Tasks
- [ ] Identify Lighthouse migration endpoint - what is the endpoint in existence in LH that replaces this service?
- [ ] Audit all calls to eVSS services within the functionality
- [ ] create (a) provider(s) -  Lighthouse
- [ ] create (a) service(s) - Lighthouse
- [ ] Authentication (document all steps taken to get credentials and test them)
- [ ] Create Response object - what data field(s) are being sent and received from the eVSS endpoint by the 526 form?
- [ ] Find where functionality is being utilized in vets-website and use that place to test new api provider - can form 526 switch to this LH endpoint without changes for this service? what data field(s) are being sent and received from the new LD endpoint?

## Acceptance Criteria
- [ ] Form 526: no changes to the endpoint functionality
- [ ] Maintain test coverage
- [ ] Documentation of specific steps taken for code complete
- [ ] Code is merged but not necessarily tested in higher environment

----------
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
