### ISSUE TITLE
Create Montgomery GI Bill Selected Reserve past rates page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#57077]
## Issue Description

We need to create and publish a past rates page for the Montgomery GI Bill Selected Reserve past rates for October 1, 2020, to September 30, 2021. To do this, we'll clone [the past rates page](https://www.va.gov/education/benefit-rates/montgomery-selected-reserve-rates/past-rates/) that already exists and input the correct numbers and dates. 

Rates to input: https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch1606/Ch1606rates100120.asp

Proposed H1: Past rates: 2021-22 MGIB-SR
Note that we'll also need to change the H1 of the 2021-22 rates that are already on the site. 

We'll need to add a link to the new past rates page on the current rates page.

We will publish the page in a separate ticket once we've determined the IA. 

## Tasks
- [x] Clone Drupal page (Katherine)
- [x] Input correct rates info and update years (Katherine)
- [x] Update H1 of already live past rates page (Katherine)
- [x] Add link on current rates page (Katherine)
- [x] Copyedit new page (Megan)
- [x] Copyedit H1 of existing past rates page (Megan)
- [x] Copyedit link on current rates page (Megan)

## Acceptance Criteria
- [x] Page is ready to publish

**Comment by RLHecht** [comment]
@megzehn These pages are ready for you!

**Comment by megzehn** [comment]
Confirming that these have been published!

**Comment by RLHecht** [comment]
Thanks! Closing!
