### ISSUE TITLE
Create Montgomery GI Bill Active Duty past rates page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#57076]
## Issue Description

We need to create and publish a past rates page for the Montgomery GI Bill Active Duty rates for October 1, 2020, to September 30, 2021.. To do this, we'll clone [the past rates page](https://www.va.gov/education/benefit-rates/montgomery-active-duty-rates/past-rates/) that already exists and input the correct numbers and dates. 

Rates to input: https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch30/ch30rates100120.asp

Proposed H1: Past rates: 2021-22 MGIB-AD
Note that we'll also need to change the H1 of the 2021-22 rates that are already on the site. 

We'll need to add a link to the new past rates page on the current rates page.

We will publish the page in a separate ticket once we've determined the IA. 

## Tasks
- [x] Clone Drupal page (Katherine)
- [x] Input correct rates info and update years (Katherine)
- [x] Update H1 of already live past rates page (Katherine)
- [x] Add link on current rates page (Katherine)
- [x] Copyedit new page (Megan)
- [x] Copyedit H1 of existing past rates page (Megan)
- [x] Copyedit link on current rates page (Megan)

## Acceptance Criteria
- [x] Page is ready to publish

**Comment by RLHecht** [comment]
@megzehn these are all ready for you. Katherine and I noticed an error in 2 examples on the original past rates page so I also made those changes on that page. We'll hold to publish in a separate ticket.

**Comment by RLHecht** [comment]
Thanks! Closing this one out.
