### ISSUE TITLE
Create Post-9/11 GI Bill past rates page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#57075]
## Issue Description

We need to create and publish a past rates page for the Post-9/11 GI Bill rates for August 1, 2020, to July 31, 2021. To do this, we'll clone [the past rates page](https://www.va.gov/education/benefit-rates/post-9-11-gi-bill-rates/past-rates/) that already exists and input the correct numbers and dates. 

Rates to input: https://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch33/ch33rates080120.asp

Proposed H1: Past rates: 2020-21 Post-9/11 GI Bill
Note that we'll also need to change the H1 of the 2021-22 rates that are already on the site. 

We'll need to add a link to the new past rates page on the current rates page.

We will publish the page in a separate ticket once we've determined the IA. 

## Tasks
- [ ] Clone Drupal page (Katherine)
- [ ] Input correct rates info and update years (Katherine)
- [ ] Update H1 of already live past rates page (Katherine)
- [ ] Add link on current rates page (Katherine)
- [ ] Copyedit new page (Megan)
- [ ] Copyedit H1 of existing past rates page (Megan)
- [ ] Copyedit link on current rates page (Megan)

## Acceptance Criteria
- [ ] Page is ready to publish

**Comment by RLHecht** [comment]
@megzehn this is ready for you to copyedit. We'll do the publishing in a separate ticket. Thanks!

**Comment by megzehn** [comment]
Confirming I reviewed and published these pages. Thanks!
