### ISSUE TITLE
[Design] Personal Info: Move stray dropdown questions to their appropriate boxes

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#57098]
### Background

Discovered and approved for re-design as part of issue 53227. The two dropdown items, "How to update your legal name" and "How to fix an error in your name or date of birth," are floating above personal info boxes and need to be moved to their appropriate places near "Legal name" and "Date of birth."

![image.png](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/135b26be-6fb3-460a-a41b-57eeea9ef0e4)!

### Tasks

- [ ] Mock up sketch designs with dropdown items moved to appropriate positions on the page
- [ ] Share designs / get approved 
- [ ] Ask dev to create ticket to implement changes
- [ ] Any documentation updates as needed

**Comment by mtcA6** [comment]
duplicate of #57097
