### ISSUE TITLE
Secure messaging errors and alerts

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#57101]
## Issue Description
Secure messaging tool in staging includes errors and alerts that didn't go through content review, and a couple of additional error/alert needs have emerged since we completed phase 0 content. 

Joel provided a spreadsheet of existing errors & alerts in staging. We need to provide suggested updates to this content. We're planning an error message content mini-sprint for May, so we'll want to track what we suggest here and understand guidance may change. We'll work with Misty on this, so we align with mobile app.

---
## Tasks
- [x] Edit existing alerts in spreadsheet (Laura, Aliyah, Misty)
- [ ] Review (Danielle)
- [ ] Provide suggested updates to Joel (Laura)

## Acceptance Criteria
- [ ] Error and alert updates provided to SM design team

**Comment by laurwill** [comment]
This is a duplicate ticket to 57102. Closing.
