### ISSUE TITLE
Secure messaging errors and alerts

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#57102]
## Issue Description
Secure messaging tool in staging includes errors and alerts that didn't go through content review, and a couple of additional error/alert needs have emerged since we completed phase 0 content. 

Joel provided a spreadsheet of existing errors & alerts in staging. We need to provide suggested updates to this content. We're planning an error message content mini-sprint for May, so we'll want to track what we suggest here and understand guidance may change. We'll work with Misty on this, so we align with mobile app.

---
## Tasks
- [x] Edit existing alerts in spreadsheet (Laura, Aliyah, Misty)
- [x] Review Cerner message (Danielle)
- [x] Provide suggested updates to Joel (Laura)

## Acceptance Criteria
- [x] Error and alert updates provided to SM design team

**Comment by laurwill** [comment]
Hi @DanielleThierryUSDSVA ,
Misty, Aliyah, and I suggested updates to the errors and alerts currently in staging for SM. Passing these along for your review before we pass back to the product team. Let me know if you’d like to chat about anything!

[SM Phase 0 errors and alerts_4.19.23.xlsx](https://dvagov-my.sharepoint.com/:x:/g/personal/laura_willwerth_va_gov/ERsEacbGPFFEg90TcHT2_h8B2xo2zxGcxP6gGtWCAFm3JQ?e=QOsRGk)

And noting that the Cerner message is in the final tab of the spreadsheet — I copied over the existing message from our static SM page, removed “new" per slack direction from Lauren, and changed the MHV links to “Continue to My HealtheVet on VA.gov” since users will have just signed in to try out the phase 0 tool. But this version is different from the one in the mobile app: 
![image.png](https://images.zenhubusercontent.com/626705c08314b7e2fecdf2eb/f0e37e7b-6b93-4618-a6b4-1072b387ea69)

**Comment by laurwill** [comment]
Updates here: I talked with Danielle about specific questions we had here, like the Cerner message and the variation around "we couldn't delete" vs "not deleted". She's not doing a full review at this time.

 @underpaid1ntern ,
Our suggested updates to the errors and alerts are ready for you in this Sharepoint file [SM Phase 0 errors and alerts_4.25.23.xlsx](https://dvagov-my.sharepoint.com/:x:/g/personal/laura_willwerth_va_gov/ERsEacbGPFFEg90TcHT2_h8B2xo2zxGcxP6gGtWCAFm3JQ?e=QOsRGk) . Let me know if you have trouble accessing.

We've called out a few notes and questions in the file. And here are 2 overall notes:
- Our content community of practice will be holding an error message retreat in mid-May to review and update our sitewide approach to error messaging. So some of the suggestions we made here may change after that meeting, but we've made the most up-to-date suggestions possible for now.
- We noticed you split the tabs into "Error messages" "Alerts" and "Prompts". But similar content appears in errors and alerts tabs. We left them as is but wanted to confirm: Does the organization in these tabs have any relation to how these pieces of content appear in the tool?

Let us know if you have questions or want to chat about anything! And thanks again for putting this spreadsheet together — it was so helpful to see these all in one place.

**Comment by laurwill** [comment]
@RLHecht we can close this in this sprint, I think.

**Comment by RLHecht** [comment]
Thanks, closing!

**Comment by underpaid1ntern** [comment]
> Updates here: I talked with Danielle about specific questions we had here, like the Cerner message and the variation around "we couldn't delete" vs "not deleted". She's not doing a full review at this time.
> 
> @underpaid1ntern , Our suggested updates to the errors and alerts are ready for you in this Sharepoint file [SM Phase 0 errors and alerts_4.25.23.xlsx](https://dvagov-my.sharepoint.com/:x:/g/personal/laura_willwerth_va_gov/ERsEacbGPFFEg90TcHT2_h8B2xo2zxGcxP6gGtWCAFm3JQ?e=QOsRGk) . Let me know if you have trouble accessing.
> 
> We've called out a few notes and questions in the file. And here are 2 overall notes:
> 
> * Our content community of practice will be holding an error message retreat in mid-May to review and update our sitewide approach to error messaging. So some of the suggestions we made here may change after that meeting, but we've made the most up-to-date suggestions possible for now.
> * We noticed you split the tabs into "Error messages" "Alerts" and "Prompts". But similar content appears in errors and alerts tabs. We left them as is but wanted to confirm: Does the organization in these tabs have any relation to how these pieces of content appear in the tool?
> 
> Let us know if you have questions or want to chat about anything! And thanks again for putting this spreadsheet together — it was so helpful to see these all in one place.

Hi @laurwill thanks so much for this work. To answer your question about the xl tabs: That organization is based off of how the developers organized their data structure for holding these. I tried to keep the labels/matching the same as possible to help ensure that the edits make it to the right place.

As for some of the questions you had in the xl doc:
<img width="843" alt="image" src="https://user-images.githubusercontent.com/126206606/234940594-792ecac4-8892-4d30-90b2-42f4094b3f2d.png">
We may move this to a 1-click function that displays a success banner with the caveat of messages are never fully deleted; however, I don't see that happening until later.

<img width="525" alt="image" src="https://user-images.githubusercontent.com/126206606/234940980-3d86dc93-1009-4ebd-9406-061d305fbc31.png">
This will just be a top banner

<img width="589" alt="image" src="https://user-images.githubusercontent.com/126206606/234941255-3e77ed15-9da8-4b38-a868-d2bc4f143119.png">
This should be the only thing that displays except for constant elements like the "Start a new message" action link. Here's an example of how it might look (not finalized)
<img width="532" alt="image" src="https://user-images.githubusercontent.com/126206606/234941499-312ca092-33ba-4510-a4e7-6f9fb2648f65.png">

<img width="667" alt="image" src="https://user-images.githubusercontent.com/126206606/234941675-93fd712a-090a-465d-ae2e-bf2debf6ccdd.png">
You're right, this does not need to be a modal and we can change the pattern going fwd. Thank you!

<img width="868" alt="image" src="https://user-images.githubusercontent.com/126206606/234942026-f53fc0c4-ad98-488a-bbcb-03145dc66650.png">
These two are similar so addressing them at the same time - yes, it should either be a message or a conversation, not both at the same time. In this case, moving/trashing is a conversation action so going fwd, it'll just say conversation, not message.

Thanks for all your help! LMK if you have further questions.

**Comment by mistymg** [comment]
@underpaid1ntern, thanks for all that! I have a clarifying question on the conversation/message moving thing. Can a user trash a single message or do they have to trash a whole conversation? Similarly, can a user move a single message or do they have to move a whole conversation when moving something to a different folder?

**Comment by underpaid1ntern** [comment]
Hi @mistymg , moving/trashing actions happen at the conversation level, even if there's only one message. Users can only reply to the latest message in a conversation.
<img width="403" alt="image" src="https://user-images.githubusercontent.com/126206606/235234959-ae3c0bdc-5206-40a6-adf8-e1f47d93a937.png">
The previous designers hoped to reflect this in the UI so the print/trash buttons are at the top of the whole details view.

**Comment by mistymg** [comment]
Interesting! Thanks for that info, @underpaid1ntern!
