### ISSUE TITLE
Draft wording for Slack paths for Portal (Workflow, etc.)

### ISSUE THREAD

**Issue by twoangstroms** [department-of-veterans-affairs/va.gov-team#57113]
## Purpose
As per Ticket #[56687](https://app.zenhub.com/workspaces/platform-service-design-61bcbaf174a70100154e22e7/issues/gh/department-of-veterans-affairs/va.gov-team/56687), links from Slack to the feedback Portal could be strong affordances for users. Given the character limits available, we'll need to draft the content and triggers for a Workflow

[Mural w/ notes ](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1683740184684/22ca7ea6f8f6fc10bf47f22e11817fc19de82513?sender=u4397b715dc3690a417b71483)on workflow

## Tasks
- [x] Draft content
  - [x] How to use Workflows
  - [x] Workflow construction recommendations
- [x] Determine triggers for Workflow
- [x] Draft Workflow name (24 character limit)
- [x] Team Review

## Acceptance Criteria
- [ ] Workflow is ready to launch

**Comment by steel36** [comment]
Review complete.

**Comment by tayism** [comment]
Review complete!

**Comment by twoangstroms** [comment]
Updated [content proposals](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2617933876/Workflow+Bookmark+wordings+and+construction+for+Portal) to include bookmark

**Comment by twoangstroms** [comment]
Updated to reflect move to bookmark rather than Workflow
