### ISSUE TITLE
Update phone number on 526-EZ alert #49356

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#57110]
On hold - pending discussion on slack thread about the support hours around eVSS Helpdesk.
https://dsva.slack.com/archives/CNCEXNXK4/p1684342364382719

## Issue Description
As a Veteran I want to make sure that if there is some information that I need to get to the VA regarding my disability claim submission that I can get that information to the correct person.

# Background
On the 526-EZ form we make a check before the Veteran begins the form to make sure we can set up an EDIPI or a BIRLS ID for the Veteran because without one of these they cannot submit a claim. If we are unable to establish one of these we show the Veteran a message that we need more information shown here -

![image (1).png](https://images.zenhubusercontent.com/5d643dbea77bcf04870bc424/878dd8ff-6afc-4a48-b531-7ca93ce2cede)

The correct phone number we need on this error message is 800-698-2411, that is the number for the Tier 1 Contact Center which can route issues like this to the EVSS help desk. They are available 24 hours a day, 7 days a week.

## Tasks
- [x] Update the phone number on the alert
- [ ] Notify Tier 1 Group of the change with added training
- [ ] Submit a PR for review and merge

## Acceptance criteria
- [x] The correct phone number now shows on the alert message referenced above
- [ ] Designer comments on this issue to approve page styling 
- [x] Unit tests pass
- [x] E2E tests cover current code and regression
- [x] End-to-end tests show 0 violations.
- [x] All axe checks pass
- [x] All screenreader checks pass

**Comment by RakshindaAslam** [comment]
@Nyanteea @christinec-fftc

**Comment by christinec-fftc** [comment]
My notes from our chat this afternoon.

Visually the changes are good, but we want to double check that we have the right phone number. We may also want to tweak the content a little. Holding off on merging the changes until this is resolved.

**Comment by lydiahooper** [comment]
Here is final content:

To update your account, please call the MyVA411 main information line at 800-698-2411 (TTY: 711) and select 0. We're here 24 hours a day, 7 days a week.
