### ISSUE TITLE
Intercept Survey Research

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/va.gov-team#57126]
## Issue Description
Numerous intercept survey responses mention frustration at the speed at which the intercept modal window appears. Research needs to be done to understand industry best practices to compare against our current intercept survey timing. Understanding on the decisions behind the current timing would be beneficial as well.

---
## Tasks
- [ ] Determine how the current modal window timing was decided upon
- [ ] Do analysis on other recommended timing
- [ ] Writing up findings comparing current timing to recommended timing.

## Acceptance Criteria
- [ ] A github doc has been published with the findings
- [ ] Recommendations are included in the document.
