### ISSUE TITLE
Add Supplemental Claims info to alert on intent to file page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#57124]
## Issue Description

When a Veteran starts their online Supplemental Form they automatically submit an intent to file. We need to add this information to the alert on our [Your intent to file a VA claim](https://www.va.gov/resources/your-intent-to-file-a-va-claim) R&S article. Right now it only mentions that this happens when you file a disability claim.  

We should also review the rest of the page to make sure we don't need to add any other information about Supplemental Claims.

Before we publish, we need to send to Paul Shute for approval.

## Tasks
- [x] Update alert to include Supplemental Claims and review rest of page (Katherine)
- [x] OCTO review (Beth)
- [x] Send to stakeholder for approval (Katherine)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [ ] Alert is live with changes

**Comment by katherine-fung** [comment]
note to self: 

https://prod.cms.va.gov/node/20490/edit 

http://preview-prod.vfs.va.gov/preview?nodeId=23233

http://preview-prod.vfs.va.gov/preview?nodeId=20486

**Comment by katherine-fung** [comment]
note to self: 

https://prod.cms.va.gov/node/20490/edit 

http://preview-prod.vfs.va.gov/preview?nodeId=23233

http://preview-prod.vfs.va.gov/preview?nodeId=20486

**Comment by bethpottsVADEPO** [comment]
@katherine-fung Thanks! I put some edits in there. When you send this to Paul for an accuracy check, can you please call out the first Q&A and ask specifically if the way we've worded that is correct? I'm wondering if we need to list more there than the 3 bullets.

**Comment by bethpottsVADEPO** [comment]
@megzehn and @katherine-fung Do you think we should be capping "Intent to File" when the word "form" follows? I think it should be lowercase when we say, "...notify us of your intent to file" because that's not as specific, but I'm waffling on the former.

**Comment by megzehn** [comment]
Good Q, @bethpottsVADEPO. I'm leaning toward keeping it lowercase before form, since it's still a shortened version of the full form name.

We have it lowercase on these pages, too:
- [How to apply for a VA pension](https://www.va.gov/pension/how-to-apply/)
- [How to file a VA disability claim](https://www.va.gov/disability/how-to-file-claim/)

It's a tricky one though. I can make a note to add this to the style guide once we confirm!

**Comment by katherine-fung** [comment]
I sent these changes to the stakeholder for review.

**Comment by katherine-fung** [comment]
I just followed up on my email to Paul.

**Comment by katherine-fung** [comment]
Hi @megzehn, 

This is ready for copy edit. 

Here are the previews of the individual FAQs I changed: 

- Preview for the FAQ "What's intent to file?" 
http://preview-prod.vfs.va.gov/preview?nodeId=23233

- Preview for the FAQ "How do I notify VA of my intent to file?"
- http://preview-prod.vfs.va.gov/preview?nodeId=20486

Here's the preview of the alert copy I changed (on the full FAQ page):
http://preview-prod.vfs.va.gov/preview?nodeId=20490

Thanks!

**Comment by megzehn** [comment]
Thanks, @katherine-fung! Confirming these pages are published.

**Comment by RLHecht** [comment]
These are live. Closing ticket!
