### ISSUE TITLE
Intercept Timing Research

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/va.gov-team#57128]
## Issue Description
Numerous intercept survey responses mention frustration at the speed at which the intercept modal window appears. Research needs to be done to understand industry best practices to compare against our current intercept survey timing. Understanding the decisions behind the current timing would be beneficial as well.

---
## Tasks
- [x] Determine how the current modal window timing was decided upon
- [x] Do analysis on other recommended timing
- [x] Writing up findings comparing current timing to recommended timing.

## Acceptance Criteria
- [x] A github doc has been published with the findings
- [x] Recommendations are included in the document.

**Comment by ianMcCullough-ob** [comment]
I created a google doc with findings [here](https://docs.google.com/document/d/1667UmcucfcOvZMnapc-aT4J8KvKSaZa3OxQChNHFRRI/edit?usp=sharing). This is a trimmed down version.

I will eventually published a more refined GitHub doc after research on the survey questions has been performed as well.
