### ISSUE TITLE
User flow for Toxic Exposure screens

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#57121]
## Issue Description
The 526ez and ancillary paper forms get updated when necessary. This ticket is part of work required to get the digital 526ez form on va.gov sync with the paper version. The scope of this work is to outline new screens for usability testing. These screens will include 12 new fields related to toxic exposure (on page 10 of [paper form](https://www.vba.va.gov/pubs/forms/vba-21-526ez-are.pdf))

This work is to prepare for design intent with collab cycle.

---
## Tasks
- [x] Document user flows that outline proposed changes/what we hope to do research on 
- [x] Create list of questions for VBA, if needed

## Acceptance Criteria
- [x] New user flows including Toxic Exposure screens in the 526ez flow

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lydiahooper** [comment]
Sketch file showing proposed user flow: https://sketch.com/s/c353146f-eceb-4626-9918-7603c693417f
