### ISSUE TITLE
Phase 3: USWDS v3-based base design system + USWDS v3-based components built to-date

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#57123]
We need to create a set of demonstration pages for the following scenarios. These should be built in vets-website, though not deployed to production, in order to reproduce what VFS teams will need to do in order to configure their applications to use the new Design System. We should also document for VFS teams how they can achieve these build configurations in their own applications.

Phase 3:  USWDS v3-based base design system + USWDS v3-based components built to-date
In this scenario the application is free of Formation and only loads the latest and greatest design system based on USWDS v3. This is our eventual end-goal.

This must demonstrate:

Base typographical elements (headers, paragraphs, lists, etc.) from our base USWDS v3-based package
Color scheme coming from v3
CSS-library - based on v3, namespaced to vads
All v3-based components that we've built to-date (and keep that updated)

## Acceptance Criteria
- [ ] The Design System Team has the ability to demonstrate a page or pages that show the scenarios listed above with the MUST requirements met.
- [ ] The Design System Team can see the current state of their work on enabling VFS Teams to adopt a USWDS v3-based Design System across the 3 scenarios.
- [ ] VFS Teams can read documentation on how to migrate their application to the final v3-based Design System.

**Comment by Andrew565** [comment]
Do we want this V3 demo page to be in addition to the V3 playground, or is it enough for this to _be_ what is presented as the V3 playground?

**Comment by humancompanion-usds** [comment]
I'm not sure I follow the question but what I'd like is to keep what we have which is a page to compare v1 to the v3 MVP and then add another page that just shows the full v3 system (components + base build). For now that can be a similar kitchen sink to what we have for the MVP. In future, that might be a full blown proper page or pages that show typical page types on va.gov.

**Comment by caw310** [comment]
Closing this initiative as the remaining work for this will be part of the Formation Deprecation initiative. https://github.com/department-of-veterans-affairs/va.gov-team/issues/66756
