### ISSUE TITLE
[Team Workshop] Prioritization 

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#57142]
## Workshop Goals
- Conduct gap-bet analysis to determine the strongest opportunity to pursue coming out of Ideation workshop

## Participants
- All members of squad 1
- Matt and Julie

## Facilitator 
- Jacob

## Length of workshop
- 1 hour

## Tasks

- [x] Schedule workshop
- [ ] Review pre-workshop materials (to be posted in Slack)
- [ ] Review results of Ideation workshop
- [ ] Conduct workshop
- [ ] Provide workshop summary

**Comment by sortizsh** [comment]
scheduled for May 2
