### ISSUE TITLE
Engineering spike to de-risk: PIV authentication

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#57155]
## Issue Description
Our in-person proofing solution assumes that we can authenticate trusted referees via PIV. In order to test the technical feasibility of this assumption, we want to complete an engineering spike on PIV authentication.

---
## Tasks
- [ ] _Determine which other applications rely on PIV for authentication_
- [ ] _Analyze code and list any questions_
- [ ] _Review any relevant documentation_
- [ ] _Follow up with SMEs who can help answer our questions_
- [ ] _Summarize what we learned, including any dependencies, risks, or blockers involved in using PIV for authentication_

## Acceptance Criteria
- [ ] _Engineering team understands basics of implementing PIV authentication_
- [ ] _Engineering team agrees that PIV authentication is feasible_
- [ ] _Summary presented during sprint demo_

**Comment by alevindecanini** [comment]
@jrjamespdx can you please take a look at this ticket and edit the description/tasks/acceptance criteria as needed

**Comment by jrjamespdx** [comment]
PIV authentication is possible utilizing the already present VA SSOi service.  The Single Sign-On Internal service is one of the main ways that users can authenticate for internal VA application access.  This method allows for PIV to be used, satisfying the needs of this question.
