### ISSUE TITLE
Define KPIs for In-person Proofing

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#57160]
## Issue Description
_In order to begin developing in-person proofing solutions and evaluate their effectiveness, we need to first define how success will be measured._

---
## Tasks
- [x] _Draft IPP KPIs_
- [x] _Socialize IPP KPIs_
- [x] _Revise IPP KPIs per feedback_
- [x] _Present IPP KPIs during sprint demo_
- [x] _Incorporate IPP KPIs in Product Outline_

## Acceptance Criteria
- [x] _PO and team agree on appropriate KPIs for IPP_

**Comment by alevindecanini** [comment]
Draft: https://docs.google.com/document/d/1s02E_2aEFiMD6--iCLx6uDtzS6zDKMnnfQkc4FAHsw0/edit#
