### ISSUE TITLE
Lighthouse Tracked Items collaboration

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#57186]
## Background
There have been issues with getting the responses for tracked items from Lighthouse to match up with what we currently receive from EVSS. This has resulted in a lot of back and forth between us and Lighthouse as we go through the development cycle with them.

## Tasks
- [ ] Review changes made to the Lighthouse Benefits Claims API and report any issues back to Lighthouse
- [ ] Be ready to deal with any follow up questions Lighthouse has and attend any discussions that are scheduled
- [ ] Prepare test scenarios as needed via VBMS

## Acceptance Criteria
- [ ] We have done everything in our power to enable Lighthouse to finalize work on their API
