### ISSUE TITLE
Data no longer going to grafana

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#57183]
### PROBLEM STATEMENT
2 teams (benefits and vaos) have reported that they are unable to view their charts in grafana after their endpoints were migrated to EKS. Teams are also unable to receive alerts.
Grafana is not receiving data.

### ADDITIONAL INFORMATION
Slack threads
https://dsva.slack.com/archives/C04M7T1CZAS/p1681923209806389
https://dsva.slack.com/archives/CBU0KDSB1/p1681844660339409

### ACTION ITEMS
- [ ] option a: work to get data flowing back to grafana (very heavy lift)
- [x] option b: Work with 2 reporting VFS teams to migrate graphs to DD + alerts

_Hi folks! After much discussion among our team, the team working on datadog, and our PO, we have decided on the following for the current metrics issue:_
_- Please nominate up to 2 people from your respective team that will receive temporary write access to datadog. With this, those 2 team members will work with our team to setup the needed dashboards in datadog, along with the alerts._
_- Write access will remain until Monday morning as we want to ensure the nominated team members can adjust alerts (if needed) over the weekend._

### ACCEPTANCE CRITERIA
- [x] the 2 reporting teams have alerts working for their endpoints
*1 team (benefits) said they didn't want to setup alerts

**Comment by laineymajor** [comment]
Closing as the AC are complete (this was more of a bandaid for now). Circling up with @jhouse-solvd so we can chat about how this work relates to the project he drafted.

@jhouse-solvd I started a miro board to begin analyzing the qualitative data from teams (Q: what data from grafana boards overlap between teams?)
