### ISSUE TITLE
Map touchpoint journey for DS Logon users

### ISSUE THREAD

**Issue by tygindraux** [department-of-veterans-affairs/va.gov-team#57202]
## Description
We need to map a journey that shows the different touchpoints a DS Logon user would encounter, to show how we propose:
- layering different unauth and auth channels like email, modals, banners, etc.
- adding more touchpoints in the authenticated experience like VA Profile notifications
- reaching out to Veterans after account creation

## Acceptance criteria
- [x] Touchpoint journey has been mapped

## Tasks
- [x] @elizabethkochBT share spreadsheet
- [x] @MOStudioCarolyn draft journey map that shows various touchpoints that 1 Veteran could encounter, focusing on breadth
- [x] @MOStudioCarolyn share with team for review

**Comment by MOStudioCarolyn** [comment]
Working document here https://app.mural.co/invitation/mural/innovationboards1199/1683207377789?sender=u1e2c263656ad89ecadb41603&key=7590a094-f21c-4b4a-b604-864dcf85b933

**Comment by MOStudioCarolyn** [comment]
After discussing with @tygindraux, this map has shifted to a storyboard.
