### ISSUE TITLE
Create downloadable PDF for Login.gov campaign page

### ISSUE THREAD

**Issue by tygindraux** [department-of-veterans-affairs/va.gov-team#57200]
## Description
We need to create a downloadable PDF that can be linked on the Login.gov campaign landing page we create. It should be 508 compliant.

## Acceptance criteria
- [ ] Downloadable PDF has been created and is ready for upload

## Tasks
- [x] @skirkman16 start draft in Figma
- [x] @skirkman16 reach out to the Accessibility Specialist for 508 compliance

## Moved to next sprint ticket
- [ ] @skirkman16 make document 508 compliant based on advice
- [ ] @skirkman16 get document ready to be uploaded to the landing page
- [ ] @skirkman16 link document to this ticket

**Comment by skirkman16** [comment]
met with platform team on 5/3 and received accessibility feedback. Will reach out to Martha Wilkes by 5/5 for 508 compliance

**Comment by skirkman16** [comment]
Connected with a11y PDF specialist @SarahKay8 to ensure 508 compliance
