### ISSUE TITLE
EVSS Migration: replace EVSS service provider for rated_disabilities in Form526RapidReadyForDecisionConcern#disabilities_not_service_connected?

### ISSUE THREAD

**Issue by ahay-agile6** [department-of-veterans-affairs/va.gov-team#57215]
## Issue Description
In ticket #56361, we discovered we missed a spot in migrating the EVSS provider for rated_disabilities in the submission workflow: `Form526RapidReadyForDecisionConcern#disabilities_not_service_connected?`
We need to replace that service reference with our generic RatedDisabilities API Provider.

Scope - just the code change 

## Notes:

- `SubmitForm526#perform`
 - `Form526RapidReadyForDecisionConcern#prepare_for_evss!` -> `#disabilities_not_service_connected?`
 - `Form526RapidReadyForDecisionConcern#disabilities_not_service_connected?`
  - calls to EVSS rated_disabilities endpoint
   - **ACTION REQUIRED:** we need to switch the service here

---
## Tasks
- [ ] Replace EVSS::Service with our RatedDisabilities Provider in `Form526RapidReadyForDecisionConcern#disabilities_not_service_connected?` method

## Links
- Created from [#56361](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/56361)

## Acceptance Criteria
- [ ] EVSS service not referred to directly in `Form526RapidReadyForDecisionConcern#disabilities_not_service_connected?` 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
cc @RakshindaAslam
