### ISSUE TITLE
[Sign-in Service] - Application onboarding requirements checklist

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/va.gov-team#57226]
## Description of application
Sign-in Service is an open source VA created OAuth solution which provides identity brokering for [Login.gov](http://login.gov/), [ID.me](http://id.me/), DSLogon, and My HealtheVet credentials. 

Sign-in Service currently lives inside `vets-api` and will be migrated out to this new application.

Because this is a migration of a core part of vets-api/va.gov, the plan is to get the infrastructure up for a barebones Rails app and then begin migrating the app over. Technical details and requirements may change as the migration proceeds.

### Basic info:
**Team Name:**   
Identity Surge

**Application Name:**  
Sign-in Service

**Functionality:**  
OAuth sign-in solution for vets-api

**Language/Stack:**  
Ruby on Rails

**Ports/Networking needed:**  
"80, 443" for standard HTTP and HTTPS - TBD

**Other infrastructure needed:**  
RDS-Postgres 15.2, Elasticache- Redis 6.2
- https://github.com/department-of-veterans-affairs/devops/pull/12901

### Background/Context/Resources
Sign-in Service currently lives inside `vets-api` and will be migrated out to this new application
[README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Sign-In%20Service/readme.md) 

### Technical Notes
- communication with vets-api (tbd)

---

## Onboarding checklist 
_*The responsible parties are listed below each item in the checklist_    

### Application repository and container 
- [x] **GitHub repo:** https://github.com/department-of-veterans-affairs/sign-in-service
Note: app should conform to the 12 factor app methodology | [Docs](https://12factor.net/)   
_Requesting team_  

- [x] **Dockerfile:** https://github.com/department-of-veterans-affairs/sign-in-service/blob/master/Dockerfile
_Requesting team_  

### Application delivery pipeline (CI/CD)
- [ ] **AWS service account for GitHub actions**  | [Request here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=operations%2C+devops%2C+needs-grooming&template=ops_issue_template.md&title=)
_Infrastructure Team_ 
   - `svc-gha-identityteam-user` Already exists. Need to add `identity-sign-in-service` ECR resource.
   https://github.com/department-of-veterans-affairs/devops/pull/12895

- [x] **AWS Elastic Container Registry (ECR) repository for the app container:** Submit PR to add your application name to the "all-repos" section of [this page](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/ecr.tf)
_Requesting team_  
	- DONE - `identity-sign-in-service` 
	https://github.com/department-of-veterans-affairs/devops/pull/12805

- [ ] **Add semantic release configuration (a `.releaserc` file) to your repo** | [Example](https://github.com/department-of-veterans-affairs/vsp-infra-calico/blob/main/.releaserc) | [Docs](https://semantic-release.gitbook.io/semantic-release/)    
_Requesting team_  

- [ ] **Automation to push the app's container to ECR with a semantic version number** | [Example](https://github.com/department-of-veterans-affairs/vsp-infra-calico/blob/main/.github/workflows/mirror-images.yaml)    
Note: Use `sha` or semver. Don't use default "latest" tag. The release system uses modified container image tags to synchronize automation.  
_Requesting team_  

### Application secrets and parameters
- [x] **AWS SSM Parameter Store path created for your team or app,** 
_Infrastructure Team_
    - `/dsva-vagov/identity-team` (Already exist)
 
- [ ] **AWS SSM Parameter Store parameters that the app needs to run,** ie `/dsva-vagov/team-name/env/secret-name` | [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/Store-a-secret-in-Parameter-Store.1474595172.html)  
_Requesting team_

---
Once the checklist is complete, you will be ready to onboard your application. Visit [Manage applications in EKS](https://vfs.atlassian.net/wiki/spaces/OT/pages/2348909545/Manage+applications+in+EKS) to get started.

### Notes 
- Please add comments to this issue as checklist items are completed, and...
- Tag the Infrastructure Team's product manager and product owner to help expedite the process

**Comment by kingbmike** [comment]
@rileyanderson Does this ticket/epic still have relevant work we need to complete?
