### ISSUE TITLE
Add self-assessment form information to pre-discharge claim page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#57227]
## Issue Description

The product team working on the 526 form opened an intake request for our team to make changes to the [Pre-discharge claim](https://staging.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/) page. 

As of April 1. 2023, an active service member filing for pre-discharge benefits under the BDD Program needs to submit a completed Self-Assessment form Part A in order to get an exam before discharge from service. Without this form, the claim cannot move forward. 

The team is currently working on making these changes to the 526 form and we need to update the content on the static page. 

Proposed content to add to the blue box "Can I use the BDD program to get my disability compensation sooner?": [https://app.zenhub.com/files/133843125/0f42fe76-ef95-44f4-857f-29f4721d4827/download](https://app.zenhub.com/files/133843125/0f42fe76-ef95-44f4-857f-29f4721d4827/download)

Intake ticket for background: #57187

Before we publish we need to coordinate timing of change with when the form gets corrected.

## Tasks
- [x] Update content on page (Katherine)
- [ ] Review (Beth)
- [x] Copyedit (Megan)
- [x] Publish (Megan)
- [x] Notify product team that changes are live (Randi)

## Acceptance Criteria
- [ ] Changes are live on the site

**Comment by katherine-fung** [comment]
Hi @laurwill (cc @bethpottsVADEPO for awareness),  

I added the self-assessment form link to the page. After discussing with Beth, I've added the link to another page "File a pre-discharge claim while overseas" as well. 

Here are the pages for review: 

**Pre-discharge claim**
http://preview-prod.vfs.va.gov/preview?nodeId=911 

Some notes: 

1. After discussing with Beth, we're not going to change the structure of the blue box/featured content for now. This can happen later, during the broader review of disability compensation pages. 

2. I added the form link to the accordion "If you have 180 to 90 days left on active duty: Apply through the BDD program."

3. There's a PDF that contains guidance/instructions for filling out the form. I included a link to it on the page because I think it could be helpful to people filling out the form. 

4. I added both the form and instructions links to the blue box as well, to highlight that the process has changed. But I'm wondering whether this information belongs in that section, which discusses eligibility. I considered whether this information should be in an informational alert, but we currently have one about the COVID pandemic and I know we're trying to remove those in batches. Do we want to put the form information in an alert, and if so, should we remove the COVID alert? 

5. I updated the links and language in the accordion "If you have less than 90 days left on active duty." 

6. I replaced a broken link for "Learn more about TAP"

**File a pre-discharge claim while overseas**
http://preview-prod.vfs.va.gov/preview?nodeId=912

Some notes: 

1. The information "What you need to know to complete the pre-discharge claim process" was on this page 2x, under each BDD office. Since the information is the same, I've moved this section up to precede information about the BDD offices. 

2. I added the link to the self-assessment form to "What you need to know to complete the pre-discharge claim process." 

3. I re-structured the "What you need to know to complete the pre-discharge claim process" section by: 
- taking the info about time needed to complete the medical exams out of bullets 
- putting the documents you need to submit with the claim into new bullets

**Comment by katherine-fung** [comment]
Hi @laurwill (cc @bethpottsVADEPO for awareness),  

I added the self-assessment form link to the page. After discussing with Beth, I've added the link to another page "File a pre-discharge claim while overseas" as well. 

Here are the pages for review: 

**Pre-discharge claim**
http://preview-prod.vfs.va.gov/preview?nodeId=911 

Some notes: 

1. After discussing with Beth, we're not going to change the structure of the blue box/featured content for now. This can happen later, during the broader review of disability compensation pages. 

2. I added the form link to the accordion "If you have 180 to 90 days left on active duty: Apply through the BDD program."

3. There's a PDF that contains guidance/instructions for filling out the form. I included a link to it on the page because I think it could be helpful to people filling out the form. 

4. I added both the form and instructions links to the blue box as well, to highlight that the process has changed. But I'm wondering whether this information belongs in that section, which discusses eligibility. I considered whether this information should be in an informational alert, but we currently have one about the COVID pandemic and I know we're trying to remove those in batches. Do we want to put the form information in an alert, and if so, should we remove the COVID alert? 

5. I updated the links and language in the accordion "If you have less than 90 days left on active duty." 

6. I replaced a broken link for "Learn more about TAP"

**File a pre-discharge claim while overseas**
http://preview-prod.vfs.va.gov/preview?nodeId=912

Some notes: 

1. The information "What you need to know to complete the pre-discharge claim process" was on this page 2x, under each BDD office. Since the information is the same, I've moved this section up to precede information about the BDD offices. 

2. I added the link to the self-assessment form to "What you need to know to complete the pre-discharge claim process." 

3. I re-structured the "What you need to know to complete the pre-discharge claim process" section by: 
- taking the info about time needed to complete the medical exams out of bullets 
- putting the documents you need to submit with the claim into new bullets

**Comment by bethpottsVADEPO** [comment]
@katherine-fung 
Re: your note No. 4 in Pre-discharge claim
http://preview-prod.vfs.va.gov/preview?nodeId=911
I think you're right that my idea to put the information and link in the blue box doesn't work since that's all eligibility info there. Thanks for trying it out. And let's not do an alert on this page. Alert components should be time-limited and this requirement seems very long term.

I like where you added the bullet and link in the 180-90 day accordion. I think that's sufficient. Thanks!

Re: File a pre-discharge claim while overseas
http://preview-prod.vfs.va.gov/preview?nodeId=912
I like how you reorganized. I want to make sure we're not changing the meaning a bit with this bullet:
- Your service treatment records

The original wording was: "a **copy** of your service treatment records **for your most recent service period**

Would you add those details back in? And since you've reworked this page pretty significantly, we'll need to make SMEs aware and ask them to review the whole page, not just the addition of the link to the health assessment. Shouldn't feel like too big of an ask since the page is so short. Can you work with the PM in that ticket and mention this?

**Comment by katherine-fung** [comment]
Thanks for the feedback @bethpottsVADEPO!! 

I've removed the links from the blue box on the pre-discharge claims page. And added back the details for service records on the overseas page. 

I've tagged the PM in #57187 about connecting with the SMEs.

**Comment by katherine-fung** [comment]
Hi @megzehn, 

These pages are ready for copy edit. Let me know if you have any questions. Thanks! 

Pre-discharge claim
http://preview-prod.vfs.va.gov/preview?nodeId=911

File a pre-discharge claim while overseas
http://preview-prod.vfs.va.gov/preview?nodeId=912

**Comment by katherine-fung** [comment]
Hi @megzehn, I'm out on Wednesday - just noting here that the stakeholders have seen these pages. The changes are ready to publish once the pages are copy edited. Thank you!!!

**Comment by megzehn** [comment]
Thanks, @katherine-fung. I reviewed the changes and published these pages. CC @RLHecht.

**Comment by megzehn** [comment]
I moved this over to validate. I'm thinking the actual is also a 4? But @katherine-fung, since you did the work, you should probably confirm :)

**Comment by RLHecht** [comment]
Thanks all! These pages are live and I let the product team know. Closing!
