### ISSUE TITLE
EVSS Migration - Submit workflow migration: Abstract references to EVSS::DocumentsService

### ISSUE THREAD

**Issue by mchae-nava** [department-of-veterans-affairs/va.gov-team#57231]
## Issue Description
The EVSS::DocumentService service is invoked by multiple async jobs during every Submit.

[Lighthouse Document Service](https://developer.va.gov/explore/api/benefits-documents/docs?version=current)

## Notes
- called in 5 places
  - SubmitForm0781 (part of 526 submit)
  - SubmitForm8940 (part of 526 submit)
  - SubmitUploads (part of 526 submit)
  - UploadBddInstructions (part of 526 submit)
  - EVSS::DocumentUpload (was used by VA Mobile, they will deprecate when ready)
- SubmitUploads, SubmitForm0781, and SubmitForm8940 are all async jobs and each call on EVSS::DocumentService. 
- The DocumentsService calls inside of 526 submit are all invoked in a single [method](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/form526_submission.rb#L297) downstream from `submit_all_claims`.

---
## Tasks
- [ ] create a documents service provider to be created by the factory - evss 
- [ ] use eVSS provider in the form 526 submit workflow(path in notes in the description)
- [ ] create flipper feature toggle to switch from evss to LH
- [ ] fix failing unit tests by switching the feature toggle off

## Acceptance Criteria
- [ ] Abstract references to EVSS::DocumentsService
- [ ] Maintain test coverage

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Links
- Created from [#56361](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/56361)

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
@ahay-agile6 - does this represent more than one ticket of work?

**Comment by navaeddie** [comment]
Note: The reference to EVSS::DocumentsService in EVSS::DocumentUpload was used by mobile and will be deprecated by them once EVSS is shutoff. So we shouldn't touch it.

> Andrew Herzberg
> Hi Eddie, Yes we currently use the EVSS::DocumentUpload  as a way to test if a file has been uploaded in specs but don't use it beyond that. We have already migrated to use Lighthouse claim document endpoints but are keeping around the old EVSS code until EVSS has been officially turned off. We have yet to start using the Lighthouse claims endpoints in production but plan on doing it soon.
