### ISSUE TITLE
Design changes for phone number optional

### ISSUE THREAD

**Issue by lydiahooper** [department-of-veterans-affairs/va.gov-team#57239]
## Issue Description
The 526ez and ancillary paper forms get updated when necessary. This ticket is part of work required to get the digital 526ez form on va.gov in sync with the paper version.

This ticket includes content and design work needed for engineering to make changes that do not require user research first, to make phone number field on contact information optional and add info about where to change phone number on page about exams.

## Tasks
- [x] Create annotated screenshots for revised contact information
- [x] Create mockup for exam page
- [x] Open ticket for content request

## Acceptance Criteria
- [x] Annotated screenshots for contact information and for exam pages
- [x] Create tickets for implementation, including for collab cycle
