### ISSUE TITLE
COVID vaccine updates for Tagalog translation 5/1/23

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#57249]
## Issue Description
We recently made changes to 2 COVID-19 pages and we'll need to send the content to get translated into Tagalog. 

Content sent to translators: [https://app.zenhub.com/files/133843125/44ad44e1-0085-4722-b4c5-082b604d60a4/download](https://app.zenhub.com/files/133843125/44ad44e1-0085-4722-b4c5-082b604d60a4/download)

Second batch sent to translators: [https://app.zenhub.com/files/133843125/535b2299-c14c-4af7-8825-e10c142ec275/download](https://app.zenhub.com/files/133843125/535b2299-c14c-4af7-8825-e10c142ec275/download)

Also note that we removed content on pages, which wouldn't be reflected in the translation doc. 

Pages with updates:
- [COVID-19 vaccines at VA](https://www.va.gov/health-care/covid-19-vaccine/)
- [COVID-19 booster shots](https://www.va.gov/health-care/covid-19-vaccine/booster-shots-and-additional-doses/)

## Tasks
- [x] Send content to translators (Randi/Ana)
- [x] Update vaccines page (Ana)
- [x] Update boosters page (Ana)
- [x] Copyedit vaccines page(Megan)
- [x] Remove translation alert from vaccines page (Megan)
- [ ] Copyedit boosters page (Megan)
- [ ] Remove translation alert from boosters page (Megan)
- [x] Publish vaccines page (Megan)
- [ ] Publish boosters page (Megan)

## Acceptance Criteria
- [ ] Updated content is live on the site

**Comment by RLHecht** [comment]
I sent this to translators today. Will keep in backlog until they send it back.

**Comment by RLHecht** [comment]
Second batch of translations back: [https://app.zenhub.com/files/133843125/c967abe1-f6af-4632-a81e-b6e45943f30e/download](https://app.zenhub.com/files/133843125/c967abe1-f6af-4632-a81e-b6e45943f30e/download)

**Comment by ABeltran77** [comment]
Sent content to translators
 Updated vaccines page 
 Updated boosters page

**Comment by megzehn** [comment]
Hi, I worked with Ana and reviewed all the COVID updates except for the Boosters page (which we're in the process of archiving), and I published the changes. 

CC @coforma-terry and @RLHecht

**Comment by ABeltran77** [comment]
Thank you @megzehn
