### ISSUE TITLE
COVID vaccine updates for Spanish translation 5/1/23

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#57247]
## Issue Description
We recently made changes to 2 COVID-19 pages and we'll need to send the content to get translated into Spanish. 

Content sent to translators: [https://app.zenhub.com/files/133843125/1be5081e-b662-4b4e-a704-0181d475030a/download](https://app.zenhub.com/files/133843125/1be5081e-b662-4b4e-a704-0181d475030a/download)

Second batch sent to translators: [https://app.zenhub.com/files/133843125/535b2299-c14c-4af7-8825-e10c142ec275/download](https://app.zenhub.com/files/133843125/535b2299-c14c-4af7-8825-e10c142ec275/download)

Also note that we removed content on pages, which wouldn't be reflected in the translation doc. 

Pages with updates:
- [COVID-19 vaccines at VA](https://www.va.gov/health-care/covid-19-vaccine/)
- [COVID-19 booster shots](https://www.va.gov/health-care/covid-19-vaccine/booster-shots-and-additional-doses/)

## Tasks
- [x] Send content to translators (Randi/Ana)
- [x] Update vaccines page (Ana)
- [x] Update boosters page (Ana)
- [x] Copyedit vaccines page(Megan)
- [ ] Remove translation alert from vaccines page (Megan)
- [x] Copyedit boosters page (Megan)
- [ ] Remove translation alert from boosters page (Megan)
- [x] Publish vaccines page (Megan)
- [x] Publish boosters page (Megan)

## Acceptance Criteria
- [x] Updated content is live on the site

**Comment by RLHecht** [comment]
I sent this to translators today. Will keep in backlog until we get it back.

**Comment by RLHecht** [comment]
Here's the second translation file back from the translators. @ABeltran77 We can update our page but note that we're still waiting for the first round of translation still as well. 

[https://app.zenhub.com/files/133843125/1daa3535-ee88-4787-a983-76a698e7edf4/download](https://app.zenhub.com/files/133843125/1daa3535-ee88-4787-a983-76a698e7edf4/download)

**Comment by RLHecht** [comment]
@ABeltran77 Here's the first set of translations back as well: [https://app.zenhub.com/files/133843125/227e3954-ad7c-4076-82ed-7a2e447d737b/download](https://app.zenhub.com/files/133843125/227e3954-ad7c-4076-82ed-7a2e447d737b/download)

You can put these revisions as well as the ones in the comment above into the Drupal page.

**Comment by ABeltran77** [comment]
Booster page has been updated and previewed.

**Comment by RLHecht** [comment]
These are both copyedited and published. Moving to validate. I'm holding off on removing translation alerts because we have some more changes coming later this week.

**Comment by ABeltran77** [comment]
ok

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
