### ISSUE TITLE
Update number of days to complete disability-related claims on Spanish pages for March

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#57244]
## Issue Description

We need to change the number of days it takes to complete disability-related claims on the following 2 Spanish pages:

- [Cómo presentar una reclamación de discapacidad de VA](https://www.va.gov/disability/how-to-file-claim-esp/)
- [Proceso de reclamación de VA después de presentar su reclamación](https://www.va.gov/disability/after-you-file-claim-esp/)

The number should match the English page for March: 118.3

## Tasks
- [x] Update how to apply page (Randi)
- [x] Update after you apply page (Randi)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Spanish pages are up to date

**Comment by RLHecht** [comment]
These changes are ready for you, @megzehn

**Comment by megzehn** [comment]
Thanks so much, @RLHecht. Confirming these are published.
