### ISSUE TITLE
[Testing] 526: Determine How Many V1 In Progress Original Claims Remain

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#5725]
## User Story:
As a veteran, I need to be able to save my progress so that I can come back to my claim and complete it.

EVSS is going to be migrating to a new application server and database.  They will be needing support to test their APIs. Since we have no way to test 526 V1 (no front end exists and no way to write a test due to the way staging is setup - if this is not true blame @SMLuthi ).  

In order to determine whether we will invest in testing the V1 API, we need to know how many in-progress claims remain from the V1 526 form.  If it is less than _some number Andrea is ok with_, we will not go through the motion of testing the the old API endpoint.

## Tasks
- [x] Go into whatever analytics we have and determine number of veterans with saved progress.

## Acceptance Criteria:
* The number of veterans is < _some number Andrea is ok with_

## Next Steps
* If there is an unacceptably high number of veterans still in progress, we need to create another story to do some testing.

## Configuration
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by SMLuthi** [comment]
@AZSchneider @luke-gcio 

These are the results from running tests on a prod server box to identify how many v1 forms still exist in our form-in-progress table. Currently there are `2373` forms still in existence. It looks like all but 19 of these forms have a creation date of April 2019 or older. Im not sure *how* these other 19 forms were started... but their creation dates are basically a couple every month after April. Furthermore, `2002` of these forms have not been touched since the end of April 2019 meaning that, if they continue to not be "updated", they will expire by the end of April 2020. This would leave us with about ~371 forms. All but 90 of these would expire by the end of year.
