### ISSUE TITLE
BDD: Create Platform Analytics Ticket to update changes to funnel

### ISSUE THREAD

**Issue by Nyanteea** [department-of-veterans-affairs/va.gov-team#57268]
Pending flow updates

## Issue Description

Platform Analytics requires that teams working on a form submit a ticket when flow changes are made, or unique components are added so that the analytics tracking can be up-to-date.

We want to make sure the current funnel reflects recent 526-page changes so page metrics can be tracked accurately. However, Platform analytics has let us know that changing the funnel can be time-consuming so they would like us to be thoughtful about how often we make change requests. 

For example, some upcoming flow changes that will need to be reflected in the funnel :

1. Flow changes with housing/terminally ill/FDC *already implemented and reflected in analytics funnel change request*
2. Flow changes with intro page work
3. Addition of 4142 pages
4. Addition of toxic exposure screens/URLs
5. Flow changes for ancillary/additional benefits (includes payment info)

---
## Tasks
- [x] Collect URLs currently being collected in DOMO funnel
- [ ] Collect new URLs from updated flow / receive new urls from content/IA team (there were no new urls that came our of BDD work) 
- [ ] Define the new funnel incorporating any changes made to flow
- [ ] submit request to Platform 

## Acceptance Criteria
- [ ] Submit the request to Platform Analytics 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Nyanteea** [comment]
@RakshindaAslam

**Comment by Nyanteea** [comment]
[Current form URLs](https://docs.google.com/spreadsheets/d/1gRmJqZvzRKSgoz8BzAxULRfRHegVrAOV6ciZU3fVWq0/edit#gid=0) (have not yet been checked for accuracy)

**Comment by Nyanteea** [comment]
[Platform analytics request sheet ](https://docs.google.com/spreadsheets/d/1YGtHECWM6x2XsqDgB-wkw3zEjs7iKWZLbUCd32UFPXo/edit#gid=0)

**Comment by RakshindaAslam** [comment]
cc @austinjprice @juliepedtke - the URLs have been updated.

**Comment by lydiahooper** [comment]
@austinjprice do you want to assign this ticket to you or close or something else?

**Comment by austinjprice** [comment]
assigned to me - will set up review with team once we get domo update

**Comment by austinjprice** [comment]
Closed :)
