### ISSUE TITLE
Create Benefits Report in Salesforce

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#57269]
## Issue Description
The OCTO product owner for benefit products on VA.gov is interested in having a report to review incoming Tier 1 and Tier 2 issues to the VEO Contact Center. This report will allow benefit team members to review the number of issues coming in during a given time period, the case type and case category, and the case notes. 

---
## Tasks
- [x] Ask Todd to grant access to Matt Self to Salesforce
- [x] Confirm criteria for the report 
- [x] Create report
- [x] Have report reviewed by Chante
- [x] Share link to the report with Matt Self 

## Acceptance Criteria
- [x] Completed report that is reviewed by Chante
- [x] Shared with Matt Self on the benefits team and any adjustments made based on feedback. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
@edpearson20 here is what I am thinking for the report criteria and report fields to display. 

First, I think we should do two reports:

**Report 1 Criteria**

- All Tier 1 Issues no matter what their status
- Case Type = disability claim application, claim/appeal status, home loan, VA benefit letters
- Date range = Jan 1, 2023 to present

**Report 2 Criteria**

- Tier 2 Issues no matter what their status
- Case Type = disability claim application, claim/appeal status, home loan, VA benefit letters
- Date range = Jan 1, 2023 to present

Each report should display the following fields:

- Date
- Status
- Case Type
- Case Category
- Case Notes

**Comment by ATMiddleton** [comment]
@edpearson20 - report created will coordinate with Chante.

**Comment by edpearson20** [comment]
@clantosswett 

1. I changed the criteria for the second report requested as I noticed that there were EVSS cases that had the case types that you indicated.
2. I added Case Number to both report outlines, so it will be the last column.  Please inform whether or not you would like it removed.

Report 01 (Case Owner - WH VA Hotline Tier 1)

https://va.lightning.force.com/lightning/r/sObject/00O3d000000ZidcEAC/view?queryScope=userFolders

Please review  report filter data as there are no results

Filters...

- Show Me ~ All cases
- Date/Time Opened ~ On or after Jan 1, 2023
- Case Owner ~ contains WH VA Hotline Tier 1
- Case Type ~ equals Claim/Appeal Status, Disability Claim Application, Home Loan, VA Benefit Letters

Report 02 (Case Owner - contains WH VA Hotline)

https://va.lightning.force.com/lightning/r/sObject/00O3d000000ZidhEAC/view?queryScope=userFolders

Filters...

- Show Me ~ All cases
- Date/Time Opened ~ On or after Jan 1, 2023
- Case Owner ~ contains WH VA Hotline
- Case Type ~ equals Claim/Appeal Status, Disability Claim Application, Home Loan, VA Benefit Letters

**Comment by clantosswett** [comment]
Thanks for this @edpearson20. I reviewed and everything looks good so I'm going to share directly with Matt Self and close this ticket.
