### ISSUE TITLE
Collaboration Cycle for Veteran Facing Forms - Product 21-0972 Alternate Signer

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#57266]
### VFS team name

Veteran Facing Forms

### Product name

Form 21-0972 Alternate Signer

### Feature name

Form 21-0972 Alternate Signer

### GitHub label for product

forms-audit-digitize

### GitHub label for feature

21-0972

## Kickoff questions

<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

Started Already

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

No

### Will your work involve changes to...

Tools, applications and dynamic pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline

https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-0972%20Alternate%20Signer/Product%20Outline.md

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Notify the Collaboration Cycle team of this ticket in the vfs-platform-support Slack channel.

- [X] I acknowledge that I must notify \#vfs-platform-support after submitting this issue.

</details>

Kickoff Slack Thread with VFS team: https://dsva.slack.com/archives/CBU0KDSB1/p1682118272000309

### Design Intent

<details>
  <summary>Toggle Design Intent instructions</summary>

##### VFS team actions
- [ ] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [ ] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [ ] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.
  
**Design Intent artifacts for review**

[See guidance on Design Intent artifacts.](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts) Governance Team feedback is based on the artifacts provided here as well as information provided during the meeting. Please provide links to artifacts **at least two business days** before the scheduled meeting.

Required:
- [ ] User flow

Not required, but nice to have:
- [ ] Wireframes (if provided, must include mobile wireframes)

Optional:
- [ ] Research plan
- [ ] Any other artifacts you have so far
  
##### Governance Team actions
- [ ] Design Intent Slack thread with VFS team
- [ ] Meeting date/time:
  
##### Governance Team actions

- [ ] Update this ticket with the Zoom recording
  - Recording link
  - Passcode:
- Accessibility
  - [ ] Feedback ticket attached
  - [ ] No feedback
- Design
  - [ ] Feedback ticket attached
  - [ ] No feedback
- IA
  - [ ] Feedback ticket attached
  - [ ] No feedback
  
##### VFS team actions

- [ ] Review feedback tickets. Comment on the ticket if there are any questions or concerns.
  

</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [ ] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [ ] Link to the Readiness Review ticket below
- [x] https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1235

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by tbaker1026** [comment]
Form went live - 10/10/2023
