### ISSUE TITLE
EVSS Migration - Submit workflow migration: Abstract references to EVSS::ClaimsService

### ISSUE THREAD

**Issue by aurora-a-k-a-lightning** [department-of-veterans-affairs/va.gov-team#57265]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

[Lighthouse Version of this API](https://developer.va.gov/explore/api/benefits-claims/docs?version=current)
example url: `curl -X GET 'https://sandbox-api.va.gov/services/claims/v2/veterans/1012667145V762142/claims/1234`

## Notes
- From Discovery session. Bullets each represent a manual search path to the eVSS call
- `start_evss_submission_job` HAS EVSS CALL!
- `EVSS::DisabilityCompensationForm::SubmitForm526AllClaim` inherits from `SubmitForm526` > `perform` > `submission.prepare_for_evss` > `pending_eps?` > `open_claims.any` > `ClaimsService` > `all_claims` references `evss.url`

---
## Tasks
- [ ] create a claims service provider to be created by the factory - evss 
- [ ] use eVSS provider in the form 526 submit workflow(path in notes in the description)
- [ ] create flipper feature toggle to switch from evss to LH
- [ ] fix failing unit tests by switching the feature toggle off

## Acceptance Criteria
- [ ] Abstract references to EVSS::ClaimsService
- [ ] Maintain test coverage

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by navaeddie** [comment]
There are a couple open questions:
1. When `vets-api` receives claim data from EVSS it comes with an array of `openClaims`, presumably separated from "closed" claims. Lighthouse will not differentiate these so we'll need to filter them within `vets-api`. We raised a question with Lighthouse as to which attribute is the most reliable metadata to make this differentiation.
2. When `vets-api` gets claim data from EVSS it relies on an attribute called `baseEndProductCode`. Lighthouse plans on removing this attribute. We asked them to keep it or identify where else we could make the relevant determination and they are looking into it.

[Slack conversation](https://dsva.slack.com/archives/C02CQP3RFFX/p1691694602623639) on Lighthouse trying to address these questions.

Kayla Watanabe is the best POC on that. Jerek Shoemaker has worked on this API a lot, too, he's provided a lot of helpful information, so we should keep him in the loop.

**Comment by navaeddie** [comment]
My changes have been committed on a branch named 57265/claims-service and pushed to Github.

**Comment by sethdarragile6** [comment]
@RakshindaAslam on the same [slack thread](https://dsva.slack.com/archives/C02CQP3RFFX/p1691694602623639) as above, Kayla mentioned that adding back `baseEndProductCode` should be a small effort, and will look to add that into their next sprint. We also seem to now have a path forward question 1 above. Should we move this back into Next Items until they (probably) add that back? Another option would be to go forward with a possible workaround I described on the thread for `baseEndProductCode` (if it's valid). We can discuss in standup tomorrow.

**Comment by RakshindaAslam** [comment]
@sethdarragile6 - Seems like our options are:
1. Wait for the LH team to add back baseEndProductCode and put our ticket on hold for possibly 4 weeks
2. Go ahead with the work-around and come back later to use the  baseEndProductCode  when it's implemented

If we go with #1, there's a possibility that we deploy submit without backup submission connected to LH. Given that we are not considering data integrity a concern when connected with both EVSS and LH, that may be the option with least amount of throw away work. More in the stand-up.
