### ISSUE TITLE
[Organic Modal] Limit statsd calls to once per session

### ISSUE THREAD

**Issue by holytoastr** [department-of-veterans-affairs/va.gov-team#57286]
## Issue Description
As a developer,
I need organic modal statsd calls to be limited to once/user session,
To add more value to the metrics and prevent us from going over our monitoring limit

---
## Tasks
- [ ] Research `callback` method for SiS as an example of session-limited metrics calls
- [ ] Adjust AcceptableVerifiedCredentialAdoptionService to limit metrics calls to once per session

## Acceptance Criteria
- [ ] Statsd metrics will increment once per session
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by holytoastr** [comment]
This issue is no longer needed because it was specific to the modal. Ok to close?
