### ISSUE TITLE
Off-hour deployment process

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#57283]
### Tasks
- [ ]  Discover how to disabling auto-sync on weekends and holidays
- [ ]  Create a deployment plan
- [ ]  Document process

## Success Metrics
- [ ] ADD SUCCESS METRICS HERE

### ACCEPTANCE CRITERIA
- [ ] deployment process is documented in confluence (for internal teams)

**Comment by laineymajor** [comment]
Note: CD can cause potential memory issues @RachalCassity for additional explanation if needed

**Comment by RachalCassity** [comment]
Updated action items (4/26)

**Comment by LindseySaari** [comment]
Initial thoughts:
1. If we don't fully commit to CD for production, it may be possible to create a CronJob that syncs the app at specific times of the day on business day, skipping holidays and weekends. Pro: Automation Con: This is not full CD
2. Prevent the Vets API GHA's from updating the image tag during off hours (weekends and holidays)

**Comment by LindseySaari** [comment]
After meeting with Bill, CD is something that we eventually want, but need to complete a few steps before getting there.

**Comment by laineymajor** [comment]
Removing from current sprint. After speaking with Bill, this is a ticket that should be included in the 'automating deployment of vets-api' project proposal.

**Comment by jennb33** [comment]
@LindseySaari do we still need this ticket? Can you please advise? TY

**Comment by LindseySaari** [comment]
This ticket has been covered by the [deny window ticket](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73380) for holiday code freezes. We do not sync on weekends, which is covered by the current sync window configuration.
