### ISSUE TITLE
Add clarifying language to Feature Request entry on the Platform Doc site footer

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#57291]
## Purpose
It currently just tells the user to Submit a FR.  What can we add to clarify that option, as well as differentiate it from the other PC footer option?

Also: should we rename the FRP to be more of a verb in line w/ Good Services? i.e. Submit a Suggestion for the Platform / Request a new Feature on the Platform / etc?

![image.png](https://images.zenhubusercontent.com/610037824c513c8eae9f81c8/74a80f4a-d723-4a00-9752-ca760937ce64)

## Tasks
- [x] [Define problem](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2661122054/Platform+Website+Updates); and what we're after
- [x] Draft updated language
- [x] Share desired change w/ Platform Content Team

## Acceptance Criteria
- [x] Language is drafted

**Comment by tayism** [comment]
Rolling over to next sprint; would like to get team's buy-in on some language options.
