### ISSUE TITLE
Global IA placement for hub-agnostic digitized forms

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#57295]
## User Story
As a member of the VFS Forms digitization team, I need to know where hub-agnostic forms we are working on will live so that we can continue through our product lifecycle and assign breadcrumbs and URLs. We also may make different content decisions based on this answer. 

As an IA, I need to know where we are placing hub-agnostic forms so that we can have a strategy to cross-link and handle SEO for those forms on an ongoing basis, handle global IA decisions, and so we can unblock teams who have no clear place to put their forms.

Assignee: @sterkenburgsara 
Reviewer: @mnorthuis 

## Description
In the process of digitizing forms on their docket, the forms digitization team realized that many forms are hub-agnostic, meaning they belong to more than one place and no clear hub is the best location for them. 

Mikki Northuis and Matt Dingee have asked Sara to assist with determining global placement of hub-agnostic / ancillary forms that are part of the forms-digitization team's work. The goal is to write up a report of options, with weighted pros and cons, and to share with @mnorthuis. She'll respond with additional tasks/edits for implementation. Once we agree on a direction and have IA and content needs clearly outlined, @mnorthuis will discuss with @DanielleThierryUSDSVA to work toward approving a solution that unblocks the VFS team. At that point, remaining IA work will be passed to @jennymayoco. 

## Impacted Artifacts
* [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1682611799163/1c8fba5298b81d662077ca8a0a4c499925b350f4?sender=uf94a77a19aaf687331c09367) with detailed solution proposal
* User flow through example hub (disability) - _included in Mural linked above_

## Tasks
- [x] Meet with @mnorthuis to go over project details
- [x] Meet with @jennymayoco to go over disability forms audit
- [x] Meet with @tbaker1026 and @jeana-adhoc to go over more specifics
- [x] Review spreadsheets and documentation around hub-agnostic forms
- [x] Compile report with IA placement options
- [x] Share report with @mnorthuis
- [x] Make edits/changes as discussed
- [ ] Develop clear implementation instructions for SWCAIA to be able to take solution forward

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] A report with actionable possible solutions is presented to @mnorthuis and Sitewide CAIA ([Mural here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1682611799163/1c8fba5298b81d662077ca8a0a4c499925b350f4?sender=uf94a77a19aaf687331c09367))

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by sterkenburgsara** [comment]
cc @jwoodman5 for visibility

**Comment by sterkenburgsara** [comment]
This work is still in progress and will be moving into the next sprint.

**Comment by sterkenburgsara** [comment]
Update: have drafted a potential solution. There are some additional brainstorming & clarifying questions to work out. Mikki at offsite this week, but we will touch base and connect next week.

**Comment by sterkenburgsara** [comment]
FYSA @shiragoodman

**Comment by shiragoodman** [comment]
thanks for keeping me informed, @sterkenburgsara. This is exciting work!

**Comment by mnorthuis** [comment]
Sara's work has been summarized and documented: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/form-digitization-supporting-forms.md

@RLHecht Can you open a corresponding content ticket for the content work needed?   We will need a new supporting content page built - or copied from the existing additional forms page - and some entry point changes.   I will submit a redirect ticket separately later on.
