### ISSUE TITLE
Bug - BDD Claim - asking for separation date in the past - Discovery

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#57294]
## Issue Description
Issue - For an active service member filing for a BDD Claim, they are being asked for a separation date in the past, instead of between 90 to 180 days in the future.

***** From the reporter ********
It is our belief that this is a technical issue with VA.gov, or at least a case of an electronic form not serving the purpose it is intended to. It is not a VSO or regional issue.
Fact #1: A "Benefits Delivery at Discharge" (BDD) claim is a type of claim which MUST be filed between 90-180 days prior to discharge from the Active Duty military. More details may be found here Pre-Discharge Claim | Veterans Affairs (va.gov).
Fact #2: The form used to submit a BDD claim is the "VA Form 21-526EZ".
-The VA.gov website will automatically direct users to the VA Form 21-526EZ if they meet the criteria for a BDD claim (see "Screenshot 1")
-Based on my Separation Date, I meet the criteria for a BDD; thus, the VA.gov website directed me to create a 21-526EZ application (see "Screenshot 2")
-HOWEVER, upon entering my Separation Date, I receive an error message stating that said date "must be in the past" (see "Screenshot 3"). I am unable to proceed further at this point.
Given Facts #1 & 2, it stands to reason that the VA Form 21-526EZ should accept Separation Dates up to 180 days in the future in order to meet BDD filing requirements. My testing indicates this limit is incorrectly set at 90 days from the current date, as evidenced by the fact that the online form will accept a separation date of 11 July 2023 (D+90), but not 12 July 2023 (D+91) (see "Screenshot 4" and "Screenshot 5")
The online VA Form 21-526EZ should either accept Separation Dates up to 180 days from the date the form is accessed, or the VA.gov website should redirect BDD claimants to the correct form. Alternately, this problem may be unique to my account. In whichever case, I request your assistance.

[Slack thread ](https://dsva.slack.com/archives/C04KW0B46N5/p1682355283664809)
---
## Tasks
- [ ] 

## Acceptance Criteria
- [x] Data to understand the severity of this issue
     - How many tickets have been submitted for this issue since it was first reported (we know of 2 since Tuesday)
     - Can we identify the scale of the issue in numbers? Is there a daily average that is going down?
- [x] Identification of the actual issue
- [x] Proposal for fix that so that BDD claim allows the service member to enter a separation date between 90-180 days
- [x] Create ticket for a fix, if needed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
cc @mchae-nava - updated the AC - lets talk more in the planning session today

**Comment by mchae-nava** [comment]
Follow up issue: https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/57946
