### ISSUE TITLE
MONITORING VETS-API IN PROD

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#57315]
As a result of the vets-api migration, we have a number of things our team would like to continue monitoring until deemed _stable_.

**ACCEPTANCE CRITERIA**
The following monitoring can be marked as complete upon stabilization. 
-----
**Stable:**
- [ ] There is not need to adjust the HPAs 
- [ ] There is no need to adjust the CPU
- [ ] There is no need to adjust the memory
- [ ] There is no need to adjust the replicas
- [ ] All major errors are mitigated (502s, 504s, CSRF, could include puma issue/thread count)

----
- [ ] [Vets-API EKS Prod Rollout](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/56653) _general_
- [ ] [Mobile](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/55082) _general_ 
- [ ] [Lighthouse](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/56045) _general_
- [ ] [Increase in 503 errors](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/56689)
- [ ] [Lighthouse increase in 502s](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/56968)
- [ ] Logger issues

**Comment by LindseySaari** [comment]
I'm working through some 504 and 504 errors that we are seeing correlate with scaling up.
[504 error window](https://vagov.ddog-gov.com/logs?query=service%3Atraefik%20env%3Aeks-prod%20%22HTTP%2F1.1%5C%22%20504%22%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&spanID=2782992987462859630&stream_sort=service%2Cdesc&viz=stream&from_ts=1683138370964&to_ts=1683139267800&live=false)

[Scaling up event](https://vagov.ddog-gov.com/dashboard/tpb-22p-tch/vets-api-scaling-and-puma-backlog?fullscreen_end_ts=1683139260000&fullscreen_paused=true&fullscreen_section=overview&fullscreen_start_ts=1683138360000&fullscreen_widget=6460026890889592&tpl_var_kube_deployment%5B0%5D=vets-api-web&from_ts=1683052554433&to_ts=1683138954433&live=true)


[Another event](https://vagov.ddog-gov.com/logs?query=service%3Atraefik%20env%3Aeks-prod%20%22HTTP%2F1.1%5C%22%20504%22%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&spanID=2782992987462859630&stream_sort=service%2Cdesc&viz=stream&from_ts=1683142993112&to_ts=1683143946000&live=false) that seems to [correlate with scale up](https://vagov.ddog-gov.com/dashboard/tpb-22p-tch/vets-api-scaling-and-puma-backlog?fullscreen_end_ts=1683143940000&fullscreen_paused=true&fullscreen_section=overview&fullscreen_start_ts=1683142980000&fullscreen_widget=6460026890889592&tpl_var_kube_deployment%5B0%5D=vets-api-web&from_ts=1683052554433&to_ts=1683138954433&live=true)

**Comment by laineymajor** [comment]
Continuing to monitor overall 500 errors

**Comment by LindseySaari** [comment]
Continuing to monitor 504 errors from Lighthouse, but two other higher priority items have taken priority
