### ISSUE TITLE
[Design] My VA: Health care updates related to MHV/Cerner split

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5733]
## User story

As a person who receives medical care from VA facilities in Spokane, WA, I will need to start going to a different VA system than MHV in (March/April) to message my doctor, refill prescriptions, and schedule appointments. Note that people who receive medial care from the VA facility in Columbus, OH, will also be directed to a different system for scheduling appointments only

## Tasks

- [x] Samara to create mockups (one with 1 message and one with 3 messages) and share with the team.
- [x] @peggygannon to provide copy.

## Acceptance 

- [x] Mockups are complete.

**Comment by bridgethapner** [comment]
Hi there @Samara-Strauss - A couple questions arose for me after this morning's call: 

- Is this page only on staging now / is there a timeline to push to production? 
- Could you upload the wireframe you shared this morning here as a reference for how healthcare information looks here today? 

Thank you in advance!

**Comment by Samara-Strauss** [comment]
@bridgethapner 

> Is this page only on staging now / is there a timeline to push to production?

My VA is currently live in production.

> Could you upload the wireframe you shared this morning here as a reference for how healthcare information looks here today?

Sure! Here you go:

![Dashboard-Updated-All Features](https://user-images.githubusercontent.com/34068740/74341789-5540a100-4d76-11ea-8287-302ee662affa.png)

**Comment by bridgethapner** [comment]
Thank you so much!

**Comment by Samara-Strauss** [comment]
@bridgethapner I am so sorry it took me to so long to get these to you. Below are the two options for the alert placement on My VA. We had talked about seeing the option for one alert above all of the health widgets, and one option with three alerts that are paired with their respective tools. I am looking for feedback on:

- If you have a preference for one design over the other. I think you may want to test both, so if that's the case, let me know that as well.
- If you have any general design feedback.
- If the copy is the general spirit of what needs to be communicated. If it is, I will hand off to Peggy for her to write the actual copy. Just want to make sure there are no details missing so nothing gets missed when I handoff to her.

### One message

![Dashboard-One message](https://user-images.githubusercontent.com/34068740/76557310-b6d95580-6471-11ea-9686-ceda1412372c.png)

### Three messages

![Dashboard-Three messages](https://user-images.githubusercontent.com/34068740/76557317-b93baf80-6471-11ea-8bcb-b23b6ffe5030.png)

**Comment by bridgethapner** [comment]
Hi @Samara-Strauss - Thank you for sharing! 

- The launch date for Cerner at Spokane has pushed back to July 15 as of last week. The launch date for Cerner at Columbus is still mid-April, and only scheduling will be rolled at that time. I think the highest priority now is a version of this page that only changes the "Schedule a VA Appointment" section of the My VA tab to also point to Cerner. 


**Here is my feedback in response to your questions**
- If you have a preference for one design over the other. I think you may want to test both, so if that's the case, let me know that as well.

When we tested alerts, we heard from users that they preferred seeing 1 warning alert box with all relevant information rather than having to scroll and view multiple. Additionally, they preferred that when there are two CTAs, those sit right next to each other at the same UI level so they can quickly make a decision about which one to click.

I think we can extrapolate and apply that insight here, and proceed with the option of 1 alert box at the top of the _Manage your VA health care_ section announcing Cerner. Then, we can duplicate the CTAs that lead to MHV today so, for example, replacing "View all your prescriptions" with "View all Mann-Grandstaff Prescriptions" and "View all prescriptions from other VA Medical Centers" to link to both MHV and Cerner.

- If the copy is the general spirit of what needs to be communicated. If it is, I will hand off to Peggy for her to write the actual copy. Just want to make sure there are no details missing so nothing gets missed when I handoff to her.

Here is the final UX design for the updated Alert boxes for Manage Health Benefit pages - Peggy has not reviewed this copy yet, but I think we'll want to be consistent in how we communicate about Cerner across the board. Can you incorporate the copy "According to our records, you are registered at Mann-Grandstaff VA Medical Center. As of March 28, 2020, VA providers at this facility are using the new My VA Health portal." into your UX for now?

![#5381-#5836-Secure Messaging-slice.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/98dd226b-d758-432b-9256-50f807b06ac8)

**Comment by Samara-Strauss** [comment]
OK, I *think* I finally get what we need. I've mocked up two states below — one is what people who part of the Columbus facility see (assuming we can identify that) and what is what everyone else would see (which is basically what we have now on the site). Let me know if this is what you're thinking and what meets our current needs.

### What Columbus patients would see

![Dashboard-Columbus notification](https://user-images.githubusercontent.com/34068740/76657661-bcee3580-6548-11ea-965c-b2855cabf561.png)

### What everyone else would see (existing state)

![Dashboard-Everyone else](https://user-images.githubusercontent.com/34068740/76657665-bf508f80-6548-11ea-81e0-585281b11a19.png)

**Comment by ambikaroos** [comment]
Per info from @ericbuckley:

When the user is logged into va.gov, from the FE you can make a `GET /v0/user` request to get information about the user.  Under the path `data["attributes"]["va_profile"]["is_cerner_patient"] `there will be a boolean that indicates whether or not they are a cerner patient.

**Comment by bridgethapner** [comment]
@Samara-Strauss I'm so sorry about the tardiness in responding to your post! The email notification of your reply slipped through the cracks for me. I assigned the ticket to me just so I don't miss any questions in the future. 

Some stuff from SSO-Login team work that might be hepful: 

- Peggy reviewed copy for the Scheduling Page Alert ([wireframe here](https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/404881778)) if you want to implement the same here. Here is the text for copy/pasting:

#### Our records show that you’re registered at Chalmers P. Wylie Ambulatory Care Center. Starting April 10, 2020, providers at this center are using My VA Health to manage appointments. 

You may need to sign in again to use VA health appointment tools. If you do, sign in with the same account you used to sign in on VA.gov. You may need to disable your browser’s pop-up block so these tools can open.

**Manage appointments with a Chalmers P. Wylie provider**
Go to My VA Health

**Manage appointments at all other VA medical centers**
Go to VA appointments


- We used a Secondary CTA style for the second CTA to clarify the differences between the buttons if you want to consider that.

**Comment by Samara-Strauss** [comment]
@bridgethapner how does this look? I implemented the copy and changed the second CTA to the secondary style.

Also, with all the COVID stuff going on, is the timeline the same for the Cerner launch? If this needs to be ready by April 10, we'll want to get this built ASAP.

![Dashboard-Columbus notification](https://user-images.githubusercontent.com/34068740/77588392-21ea4980-6ec0-11ea-910a-e8a5c771731c.png)

**Comment by bridgethapner** [comment]
Hi @Samara-Strauss - looks great. 

Yes, the date is still the 10th at this point. We are awaiting word if that's getting pushed amid COVID stuff, but haven't heard yet. If we do, I'll post here. So yes we should move this into development.

**Comment by Samara-Strauss** [comment]
OK, I will get the ticket created for this.

**Comment by Samara-Strauss** [comment]
ALSO — what technical details do my FE devs need to know so they can differentiate the veterans to whom this applies (Chalmers P. Wylie Ambulatory Care Center patients) from veterans who don't?

**Comment by ambikaroos** [comment]
@Samara-Strauss - this should be the info from @ericbuckley included in my comment above. But feel free to have your devs reach out to him directly if they need more details!

**Comment by Samara-Strauss** [comment]
OMG, thank you. I'm sorry. I totally forgot about that @ambikaroos. We should be good!

**Comment by ambikaroos** [comment]
No worries at all @Samara-Strauss ! I know there are a ton of tickets and comments flying around 😅

**Comment by Samara-Strauss** [comment]
Am I correct in remembering that we don't yet have a URL for the "Go to My VA Health" button?

**Comment by ambikaroos** [comment]
@hinzed1127 did we get a URL from Steve for My VA Health? Can't remember where we landed

**Comment by Samara-Strauss** [comment]
Creating an issue for our FE devs — #7286

**Comment by hinzed1127** [comment]
@ambikaroos I believe [this is the accurate info](https://dsva.slack.com/archives/GTUSXTBNE/p1584396531014600)

**Staging URL**: https://ehrm-va-test.patientportal.us.healtheintent.com/
**Production**: https://patientportal.myhealth.va.gov/

**Comment by Samara-Strauss** [comment]
Should have closed this a while ago!
