### ISSUE TITLE
[Initiative] Offboard to Cerner portal

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#5734]
# Stakeholder input
## Who is the target user?
- Veterans who are part of the Cerner/EHR rollout
- VAMC who are transitioning to new Cerner/EHR system

## High Level User Need / Problem / Opportunity
When a Veteran's preferred VA facility transitions to Cerner/EHR system, we want the Veteran's experience between VA.gov scheduling and My VA Health (Cerner portal) to be as seamless as possible. 

## Schedule of rollout: (latest 10/2020) _Subject to change, stay up to date with Lauren A. & #vagov-cerner-lauch-coordination channel_
- [x] 08/23/2020 - CSS/ Columbus
- [x] 10/24/2020 - Spokane
- [ ] Q1 2021 - Spokane again?
- [ ] Q2 2021 - Columbus full
- [ ] Q3 2021 - Walla Walla, White City
- [ ] Q4 2021 - Roseburg, Boise, Alaska

---
## AC for offboarding v1
- [ ] Veterans registered to Cerner site(s) are provided with information about how to schedule online using the My VA Health at the right time in the flow
    - [ ] For both  Full and CSS Cerner sites
- [ ] Veterans who are *only* registered to Cerner site(s) are prevented from using VAOS
- [ ] Veterans who are registered at both a Cerner site _and a non-Cerner site(s) should still be able to cancel or create appointment and/or requests for their _non-cerner_ registered locations, but not for the Cerner registered site
- [ ] Veterans should not be able to see upcoming appointments for Cerner sites
    - [ ] Cannot cancel an appointment
    - [ ] Cannot cancel a video appt
    - [ ] Cannot cancel a CC appt
    - [ ] Cannot schedule or request a VA appt
    - [ ] Veteran logs in at full Cerner site (ie spokane), we should get 200CRNR ID in MVI
- [ ] VAOS should provide alerts in tool during the flowing flow stages:
    - [ ] "VA Appointments" page
    - [ ] "VA Facility" page 
- [ ] Veterans with previously scheduled appointments should see and manage those appointments in the Cerner portal instead of VAOS
 - [ ] **Special case** - Columbus/CSS Site (not full Cerner) -- need to know what data exists in which systems for Columbus Veterans; Columbus uses EPIC tool (not VAOS), understand identifiers
- [ ] **Special case** - Columbus/CSS site - User should not be able to:
    - [ ] Cannot cancel an appointment at a CSS site (may show on 'Appts' page but can't take action, point to Cerner portal)
    - [ ] Cannot cancel a video appt at a CSS site
    - [ ] Cannot cancel a CC appt at a CSS site
    - [ ] Cannot schedule or request a VA appt at a CSS site
    - [ ] Veteran logs in at a CSS site (Columbus) - we will get 200CRNR ID in MVI

## Data discovery documentation -- Cerner
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/engineering/discovery/Cerner_data_discovery.md

## High level Cerner sitemap - VA.gov, MHV, My VA Health (Cerner)
https://adhoc.invisionapp.com/share/VMW6WMI9NDU#/screens/407257731

**Comment by jbalboni** [comment]
- Are non-Columbus Cerner appointments ever written back to VistA?
- Are Columbus Cerner appointments written back to VistA?
- Will we still see upcoming appointments in VistA from Cerner sites that were created before the switch over?
- Will we still be able to get past appointments from the VistA instances of sites switched to Cerner?
- Are there two different identifiers for Columbus Cerner and other Cerner sites? (220CRNR vs 200CRNR?)
- If there are appointments at Cerner sites coming through in the data that we need to hide, it feels more appropriate for that logic to live in the backend. Is that work possible?
- Will all facilities at Cerner sites be disabled for requests and direct scheduling in VATS?
- For Columbus sites, do we have dfn identifiers in MVI for users of that site?

**Comment by lalexanderson-dsva** [comment]
1. Non-columbus Cerner appointments as in Puget Sound, Spokane when they are online? At this time, no. 

2. Yes. Columbus appointments ARE written back to Vista. 

3. Yes, we should see upcoming appointments for Columbus before the switchover. 

4. Yes, we will be able to get past appointments. 

5. From Damien:

>The ID correlated for a patient in Cerner is the EDIPI so for a Cerner patient you would see a Cerner correlation and a DoD correlation both with EDIPI. [EDIPI]^PI^200CRNR^USVHA
[EDIPI]^NI^200DOD^USDOD; If they also happen to be a VA employee with Cerner access (as a user) they will have the below as well: [EDIPI]^PN^200CRNR^USVHA

6. This is a good ? for the BE. 

7. Want to validate with BE team but I think so. 

8. need to validate with BE team. 

9. We can access them via Perigean. 

10. Yes and yes. Will provide separately.

**Comment by lalexanderson-dsva** [comment]
Further clarification from Damien: No, only 200CRNR

**Comment by jbalboni** [comment]
Notes from @marcynadeau:

Updates after Judy and Stephen added feedback:

- Partial: Cerner scheduling tool (CSS aka My VA Health Portal)—i.e. which the veteran (and staff) uses to schedule/request an appointment—that writes to a VistA back-end. No appts will be made in VistA because they will not appear in CSS (data flows one-way) so scheduling will be disabled in VistA.
- Full: Cerner Millennium—i.e. Cerner scheduling that writes to a Cerner EHR back-end
- Even though VATS setting for Columbus are all set to no, vets can still log in and view and cancel appts in VAOS. This presents a problem if the site is on Cerner (in this case CSS, partial installation), there would be no way for VAOS to write to Cerner so it appears in CSS *and* VAOS should no longer write to the VistA back-end for the cancelled appt; any cancellations should be done thru CSS.
- With Cerner, appt will still be written to VistA so that they are available for other downstream VistA modules. VistA just becomes a database for appts. Communication is only one way from Cerner to VistA. 
- Columbus is a CC enabled site. Will need to update Mongo collection to remove Columbus. 
- Columbus site veterans won’t be able to directly schedule or request an appt thru VAOS. But VAOS should display a note to direct them over to the My VA Health Portal (Cerner). 
- So if Columbus is in the veteran’s JWT header then we know to direct to My VA Health Portal (Cerner).
- Per Lynne Case, an ID will be passed indicating if it’s a partial or full Cerner site.
- Display the appt (VA and Video Visit) and if a Cerner site, remove the cancel button and direct to My VA Health Portal (Cerner)
- For testing need a Veteran registered only at Columbus (Cerner site) and a veteran registered with a Columbus (Cerner) site and another VAMC not Columbus. 

The scenario we are looking at for the below is for the interim time period when Columbus/Spokane/Puget Sound are live and EAS is not deployed and connected to Cerner APIs yet. I think the UX work will only need to be done in VAOS-R, but if there is a major delay in VAOSR deployment (and thus var-web decommission) we may need to do some work in var-web. I hope not. 

For the interim scenario outlined below, I see most of the work being done in the UX:

- When VAOSR gets the list of Identifiers from MVI, it can see if any sites associated with the Veteran are Cerner sites. If so, it will need to:
- Hide the cancel button on displayed appointments
- Disable ability to select the Cerner site from the drop down of possible parent sites or allow selection of that site and at that point display info to the Veteran or maybe we just put the info display on the front page? This is something the UX experts will need to determine. 
- If there are identifiers that are NOT Cerner sites, the Veteran can continue to do all the standard stuff with them
- Once EAS is deployed and connected with Cerner APIs, this will become unnecessary and VAOS will have full functionality across VistA and Cerner without the Veteran knowing which system is backing their site.

**Comment by lenaecb** [comment]
@jbalboni @lalexanderson-dsva - based on Jeff's notes above I want to clarify what the following - a Columbus ONLY Veteran will be able to see their appointments but cannot take any action on them such as 'cancel'. AND we're also going to display the following info in a module to a Columbus ONLY Veteran in the VAOS homepage:
_"We need to make sure that the alert on the home page of VAOS specifies that you cannot SCHEDULE, REQUEST, or CANCEL VA, Community Care, or VA Video Connect appointments and provide a link to My VA Health."_

For Veteran who is registered at Columbus and a non-Cerner site they will:

- can only cancel non Columbus/Cerner appointments from VAOS app homepage, but are redirected to My VA Health for their Columbus site
- Still also get above module and message
- Get in-flow message about not booking at Columbus/Cerner site, provide redirect link to My VA Health at that point of flow if need Columbus

This may be redundant but there a multiple comments in other epics/stories so I want to make sure we're all on the same page with what actions we are looking for here so we can get the design and content story readied.

**Comment by ldelacosta** [comment]
No further action is needed at this time. Closing out the epic cc: @JRRoof
