### ISSUE TITLE
[eFSR] Installment contract summary card update

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#57343]
## Issue Description
Update installment contract summary card to only display fields that have valid data (if a non-required field is blank or zero hide its label on the card).

Additional: Confirm which fields in Credit card and Installment contracts are required. i.e. Monthly payment and name of creditor*? 

Design functionality reference ticket [#55628](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/55628)
---
## Tasks
- [ ] Update installment contract summary card to only display completed fields
- [ ] Confirm required fields
- [ ] Include e2e/unit test to check functionality

## Acceptance Criteria
- [ ] Installment contract summary card displays completed fields
- [ ] all e2e and unit tests are passing. 
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
