### ISSUE TITLE
[eFSR] Conditionally disable Month/Year in employment history

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#57342]
## Issue Description
Add correct [conditional `disabled` functionality](https://preview.uxpin.com/f43733391f52c409c4d3152e9a4b101a392e29df#/pages/161460736) to Current Year and Month fields for the [employment history](https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-spouse-employment-records) pages for spouse and the veteran when _I currently work here_ `checkbox` is selected. Here's the [slack thread](https://dsva.slack.com/archives/CPE4AJ6Q0/p1681414185203349) for more context.

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/6dffbd6e-0223-407d-841d-07ca18e83d84)

---
## Tasks
- [ ] Add disable functionality for Employee history job end date
- [ ] Add disable functionality for Spouse Employee history job end date
- [ ] Include e2e test integration to check disable

## Acceptance Criteria
- [ ] Job end date in employment history conditionally disabled if _I currently work here_ is selected
- [ ] All e2e and unit tests are passing
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by OptionSelect** [comment]
VA Date component currently does not have disabled functionality from platform's end.

https://design.va.gov/storybook/?path=/docs/components-va-date--default

Per convo with Andrew, making end date dynamically required based on current job checkbox and moved it over the end date. Will speak with design about implementation and future steps.

**Comment by OptionSelect** [comment]
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1711

Link to experimental design request asking platform to add the functionality.

**Comment by HeatherRienks** [comment]
FYI- Carol Wong from Design Team has created this follow on ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/57845

**Comment by OptionSelect** [comment]
Our stuff seems to need redesign based on feedback here
https://github.com/department-of-veterans-affairs/va.gov-team/issues/57845

**Comment by HeatherRienks** [comment]
@josephrlee @mgleo @OptionSelect - see recent feedback in this ticket: #57845.

Thoughts on next steps?

**Comment by OptionSelect** [comment]
Ticket was created by Joe to rework the content into two pages
https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/58444

**Comment by OptionSelect** [comment]
Changing to 5 because this affects spouse as well.

**Comment by OptionSelect** [comment]
Work is complete. Break testing with Andrew again before merge.

**Comment by OptionSelect** [comment]
Per Andrew review continuing work.
https://github.com/department-of-veterans-affairs/vets-website/pull/24346#issuecomment-1581146036

**Comment by OptionSelect** [comment]
Remaining issues still being worked on in here. Very close overall but this ticket grew beyond its initial scope due to the complexity of how this goes.
Veteran
* Check end date required if not a current job (not preventing continue)

Spouse
* Required not preventing continue on dates (working on veteran)
* Delete doesn’t remove summary card

Both
* Deductions input list required not preventing continue

**Comment by OptionSelect** [comment]
Remaining issues now are just dates preventing moving forward. Very close to completion.

**Comment by OptionSelect** [comment]
Fixed date continues with Andrew today, now just working on tests.

**Comment by OptionSelect** [comment]
Have fixed unit tests, just working on the remaining cypress ones now.
