### ISSUE TITLE
[DDL] Alert: decision letters are unavailable

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#57346]
## Value Statement
**_As a_** veteran accustomed to seeing decision letters in CST
**_I want to_** see some kind of message when the link to DDL is missing
**_So that_** I know DDL is unavailable and I should check back later instead of hunting around for a link that doesn't exist. 

---
## Background Context
Due to business reasons, sometimes we'll have to disable the DDL feature. Currently, when we do that, it just removes the link from the claim detail page and also makes the DDL listing page unavailable. We need some kind of generic message in CST that lets veterans know when DDL is temporarily unavailable.

Possible approaches:

- sitewide "maintenance" blocks
- consult sitewide team 

## Acceptance Criteria
- [ ]  When DDL is not available a message is visible and salient in the UI telling users that DDL is temporarily unavailable.
- [ ]  Message is removed when DDL not longer hidden behind a feature flag

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by uxgary** [comment]
Update mocks are ready in [sketch](https://sketch.com/s/0f11d505-f486-4ebb-9c33-36838cac2742)

**Comment by uxgary** [comment]
edits and accessibility notes from the content team. 

**Decision letters aren't available to download right now**
We're fixing some problems with this tool. Check back later.
If you need information about your decision letters now, call us at 800-827-1000 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.

We'll also need to adjust the content in the blue info alert on the Your compensation claim page. We want to avoid saying "You can download your letter now" if the feature isn't available. We also previously suggested changing "closed" to "decided" in this alert. Here's suggested content for this alert when the feature is down, which would appear above the yellow alert about the feature being down:

**We decided your claim on [date]**
We mailed you a decision letter.

**Additional notes:**

- Phone number and TTY need aria labels for accessibility

For additional context refer to the [content request issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61108)

**Comment by HeatherWidmont** [comment]
@samcoforma hey there! Did you need Gary to do anything else for this ticket, or is it ready for you to pick up when you have capacity?

**Comment by samcoforma** [comment]
@HeatherWidmont I believe this is ready to go for me to pick up. @uxgary There's nothing else needed from your end before I start on this right?

**Comment by HeatherWidmont** [comment]
@samcoforma in standup today he said there wasn't. Thanks for the quick response, Sam! I'll add you to the ticket 😄

**Comment by uxgary** [comment]
@jerekshoe Hey, in the sketch file, only focus on the layer marked "FINAL". I just updated the last desktop art board, _Option 1 - CST - Claim letters_. The final content matches what I posted in this ticket: 

**Decision letters aren't available to download right now**
We're fixing some problems with this tool. Check back later.
If you need information about your decision letters now, call us at 800-827-1000 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.

**We decided your claim on [date]**
We mailed you a decision letter.

**Additional notes:**

- Phone number and TTY need aria labels for accessibility

**Comment by HeatherWidmont** [comment]
@jerekshoe will review
