### ISSUE TITLE
FE | Profile | Design System | React components deprecation

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#57344]
## Issue Description
DST announced ~15 components will enter a new phase of depreciation which will prevent developers from committing code where one of these React components exists. 

We'll need to either convert the component to a full web component or to the 'react-bindings' version of the web component.

See [thread](https://dsva.slack.com/archives/C909ZG2BB/p1682432067560599)

---
## Tasks
- [ ] document which components are impacted and on which pages of the profile 

## Acceptance Criteria
- [ ] End-to-end testing ensuring updated components function as expected 
- [ ] Notify Product Manager that the change is ready to be validated on Staging
---

**Comment by mtcA6** [comment]
@adamwhitlock1 any recommendation how to test this? not sure on which pages we had the alerbox

**Comment by adamwhitlock1** [comment]
I think I can validate this in general. They are mostly triggered from specific errors that aren't easy to make happen in staging.
