### ISSUE TITLE
Request campaign landing page from Public Websites

### ISSUE THREAD

**Issue by tygindraux** [department-of-veterans-affairs/va.gov-team#57352]
## Description
We need to request a campaign landing page to be set up. Dave Conlon is the point of contact for this.

Here's an [example](https://www.va.gov/initiatives/veteran-trust-in-va/) of a campaign landing page. Here is the [campaign landing page governance product guide](https://app.zenhub.com/files/133843125/ff592f47-b48e-4d37-b1c9-91377312532d/download).

Submit requests via the [Public Websites Intake Form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose)

## Acceptance criteria
- [ ] Campaign landing page has been created

## Tasks
- [x] @CarlDickerson reach out to Dave Conlon
- [x] @CarlDickerson submit CLP request in Github
- [x] @CarlDickerson submit Helpdesk ticket
- [x] @CarlDickerson request CMS access

**Comment by elizabethkochBT** [comment]
[https://app.zenhub.com/files/133843125/ff592f47-b48e-4d37-b1c9-91377312532d/download](https://app.zenhub.com/files/133843125/ff592f47-b48e-4d37-b1c9-91377312532d/download)

**Comment by CarlDickerson** [comment]
Request for CLP submitted Github [ticket# 13603](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13603)
