### ISSUE TITLE
Desk research to write FAQs

### ISSUE THREAD

**Issue by tygindraux** [department-of-veterans-affairs/va.gov-team#57356]
## Description
We need to do desk research to help us prepare to write more specific Login.gov FAQs.  This review will include:
- [Login.gov blog comments analysis by Clayton](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Research/2023-02%20Desk%20Research/Findings%20from%20VA%20login%20post%20comment%20analysis.md)
- Help desk resources (We need to gather these)
- Sitewide FAQs ([Signing in](https://www.va.gov/resources/signing-in-to-vagov/)) and ([Creating an account](https://www.va.gov/resources/creating-an-account-for-vagov/))

We have a ticket to follow for writing FAQs.

## Acceptance criteria
- [ ] Desk research has been summarized and can be used to write FAQs

## Tasks
- [x] @MOStudioCarolyn review Login.gov blog comments
- [ ] @elizabethkochBT get resources from help desk that they use to support people with Login.gov (and/or data on questions they're frequently asked)
- [ ] @MOStudioCarolyn review help desk resources
- [x] @MOStudioCarolyn review Sitewide FAQs
- [x] create summary document describing findings
- [x] @skirkman16 will make recommendations
- [x] @skirkman16 share work with Sitewide

**Comment by skirkman16** [comment]
Today, Carolyn shared progress on the FAQ research. Unable to reach Helpdesk so we reviewed existing FAQs on VA.gov and issues from blog comments (Clayton's research). We identified some FAQs that we could make recommendations for before we write new ones that pertain specifically to Login.gov migration. Next step is to write recommendations (in the same doc) and share progress with Sitewide and MHV.
