### ISSUE TITLE
BE | Profile | Direct Deposit | Updates and Refactorings

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#57359]
## Background
There are some small technical improvements/changes to make to the direct deposit components:

## Tasks
- [x] Move key transformations from service to serializer class.
- [x] Add key inflections (camel case to snake case) to middleware.
- [x] Change calls to use base client rather than configuration class.
- [x] Miscellaneous updates.

## Acceptance Criteria
- [x] Review code changes with BE engineers.

**Comment by tpharrison** [comment]
Going to review some things with the mobile team to make sure they have what they need.
