### ISSUE TITLE
Create and publish future rates page for Fry Scholarship

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#57362]
## Issue Description

We need to create a page for future Fry Scholarship rates similarly to what we did for the Post-9/11 GI Bill page. 

To do this, we should clone the [current rates](https://www.va.gov/education/benefit-rates/fry-scholarship-rates/) page and input the same numbers that are on the [Post-9/11 GI Bill future rates](https://www.va.gov/education/benefit-rates/post-9-11-gi-bill-rates/future-rates/) page. We also need to match the intro to what is on the Post-9/11 future rates page. 

## Tasks
- [x] Clone Drupal page (Randi)
- [x] Input numbers (Randi)
- [x] Copyedit (Megan)
- [x] Publish (Megan)
- [x] Add to left nav (Megan)

## Acceptance Criteria
- [x] Future Fry Scholarship rates page is live on the site

**Comment by megzehn** [comment]
Thank you for putting this page together, @RLHecht! It looked good. I published it, and added it to the left nav.

**Comment by RLHecht** [comment]
This page is now live. Thanks for doing this, Megan! Closing!
