### ISSUE TITLE
[BE]  My VA, Direct Deposit: Discovery - Determine Client IDs required for Lighthouse APIs

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#57361]
## Background
For each Lighthouse API, the Lighthouse team requires each VSF team to authenticate using their own credentials (client ID).  Lighthouse credentials cannot be shared across VSF teams.  

## Tasks
Determine is we need to request and configure access for:
- [x] Rating Disabilities (this will cover Profile as well).
- [x] Claims Status  

## Acceptance Criteria
- [ ] If additional credentials are need for _Rating Info_, create tickets for this work.
- [ ] If additional credentials are need for _Claims Status_, create tickets for this work.

**Comment by tpharrison** [comment]
@ajakabcin - Please review...I may have missed some tags and I wasn't sure which epic to link to.  Let me know if you have any questions. Thanks!

**Comment by ajakabcin** [comment]
Thanks @tpharrison - this will go hand-in-hand with @dellerbie's technical discovery ticket (#54406). I have it slotted for sprint 11 as of right now (end of May), hoping we'll be able to work on it sooner but it's pending benefit team's work.

**Comment by tpharrison** [comment]
@mtcA6 @BerniXiongA6 
Attended the Lighthouse/VA.gov touchpoint meeting.  A decision has not been reached, but should be made on Monday, May 15th.

**Comment by tpharrison** [comment]
The Lighthouse team has decided to allow VFS teams to share client IDs, so we will be able to use client IDs that should already be in place (from other teams).
