### ISSUE TITLE
Determine / Document Sentry Ownership

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#57370]
## Issue Description
Determine who owns Sentry (if anyone—according to the epic, this tool may not have an owner anymore.) and document the findings. The owner/admin/subject matter expert (SME) of Sentry needs to be clarified.

---
## Tasks
- [x] Determine if there is a current owner of Sentry
- [x] If there is no owner, determine if there's a process in place for assigning ownership
- [x] Document ownership in an appropriate location

## Acceptance Criteria
- [x] Sentry ownership is identified and documented
