### ISSUE TITLE
Transparency Discovery & Mockups for Streamlined Waiver

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#57386]
## Issue Description
Continue work from [#56737](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/56737)

---
## Tasks
- [x] Add additional concepts to [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1681915967355/24f2b3dd9895a919f7199f5ab654748849ef53d8?sender=ua78f969c4cddcbfe56b27885)
- [x] Attend Thursday office hours with Content Team to get more info - Megan to coordinate
- [x] Draft content for 3 pages [intro, approval notice, confirmation] and share with stake holders and content team
 - [ ] Create new prototype (will create a new ticket for this effort)
## Acceptance Criteria
- [x] Additional concepts added to [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1681915967355/24f2b3dd9895a919f7199f5ab654748849ef53d8?sender=ua78f969c4cddcbfe56b27885)
- [x] Drafts created
- [ ] Several new prototypes have been created (will create a new ticket for this effort)

**Comment by HeatherRienks** [comment]
Progress Bar efforts are under way with another VFS team (Veteran Facing Forms Team).  We will utilize their findings to apply to our work.

**Comment by HeatherRienks** [comment]
Per 6/6 Design Sync, we need input from Content Team before moving forward.
