### ISSUE TITLE
Review older A11y issues with Medallia team

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#57381]
## Issue Description
Multiple A11y issues that were created over the last 2.5 years.  Some are no longer relevant, review all isses and determine validity relative the current state of Medallia._

---
## Tasks
- [x] _Review outstanding issues. 
- [ ] Determine if we have the capability to resolve
- [x] Engage Medallia determine ability to move forward

## Acceptance Criteria
- [ ] If it can be done - we will complete - still undetermined. _
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by manalo-soco** [comment]
via @aubreyarcangel :

The meeting with the Medallia team and VSignals last week highlighted that the blockers we had were blockers because Sarkis said some things couldnt be done, but after meeting with Medallia, we learned that they could.
--  arkis just didn’t know and said no or he genuinely thought it couldn’t be done. 
--  Ultimately, it did open up a line of communication for VA.gov to the Medallia team to continue suggesting our a11y needs to them.

Q @aubreyarcangel Do we have the capability to resolve? Or what else is needed.
