### ISSUE TITLE
ORMDI Medallia survey checkbox elements styling does not match the rest of the survey

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#57384]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
Check box elements do not match - This survey fires on the legacy pages - styling needs to be corrected to reflect the other surveys 
---
## Tasks
- [ Compare styles 
Match font styling of check box elements to mirror the VA.gov design standards. 
] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _Compare and confirm all fonts and styles match 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
@aubreyarcangel - still working with Sarkis on ARIA labels for phone numbers.  continuing research to determine complexity..

**Comment by ATMiddleton** [comment]
Delayed due to current workload.

**Comment by aubreyarcangel** [comment]
find the issue and incorporated into [this ticket](https://app.zenhub.com/workspaces/contact-center-62cdd9546ec1530018209672/issues/gh/department-of-veterans-affairs/va.gov-team/57780)
