### ISSUE TITLE
Make phone number optional

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#57392]
## Issue Description
The 526 paper form does not require the contact phone number to be filled in. This ticket is to make this fields optional on the digital form on va.gov.
1. Make phone number field not required on the contact information page
2. Update the language on the exam information page

Link to the new content - 
https://sketch.com/s/ae7a7a94-9e48-4cbd-bc99-006754ad2ddb

Pending sitewide content ticket #57297 - completed

## Need to know
 - This does not require a toggle deployment - ready to go when the ticket is done
 - There are old PRs that Mark can find

## Tasks
- 3 PRs go at the same time
- FE change, update vets-json-schema, potentially a BE schema

- ## Front end tasks
- Ensure the page is styled according to design spec. 
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests
- Run axe checks using the Chrome or Firefox browser plugin
- Test for color contrast and color blindness issues
- Zoom layouts to 400% at 1280px width
- Test with 1 or 2 screen readers (voiceover)
- Navigate using the keyboard only

## Acceptance Criteria
- [x] Designer comments on this issue to approve page styling - Lydia
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations
- [x] The contact phone number is no longer required to move to the next page
- [x] Check if the phone number is optional for eVSS/LH
- [x] All axe checks pass
- [x] All color contrast checks pass
- [x] All zoom testing passes
- [x] All keyboard checks pass 
- [x] All screenreader checks pass

**Comment by mchae-nava** [comment]
Schema update: https://github.com/department-of-veterans-affairs/vets-json-schema/pull/781
FE update: https://github.com/department-of-veterans-affairs/vets-website/pull/24647/files

This may have to be stalled a bit while EVSS investigates some more downstream implications. Will also require a backlog item on their end to make the field optional for submit

**Comment by mchae-nava** [comment]
EVSS-12467 and EVSS-12468 created to research downstream implications of the schema update and provide feedback

**Comment by RakshindaAslam** [comment]
@mchae-nava - do we have any update on this?

**Comment by mchae-nava** [comment]
@RakshindaAslam EVSS mentioned the change being in PINT (testable) August 03, and will be shipped August 13

**Comment by RakshindaAslam** [comment]
@sethdarragile6 @mchae-nava - can we check if this field is optional in Lighthouse?

**Comment by sethdarragile6** [comment]
> @sethdarragile6 @mchae-nava - can we check if this field is optional in Lighthouse?

According to [this](https://dev-developer.va.gov/explore/api/benefits-claims/docs?version=current), it is optional. It transforms to `veteranNumber.telephone`

**Comment by mchae-nava** [comment]
[Screenshots](https://app.zenhub.com/files/133843125/03a31b4b-838a-4e7c-bef4-256371cf3f48/download) showcasing testing done by EVSS via their /submit endpoint, pre-PINT

Confirmed shipping August 3rd at 9am ET, with some buffer for the changes to deploy

**Comment by RakshindaAslam** [comment]
cc @Kimberley2019

**Comment by mchae-nava** [comment]
@RakshindaAslam Good news and bad news:

The bad: 
We miscommunicated and the wrong field was updated on the EVSS end:
- Our `phoneAndEmail.primaryPhone` maps to their `veteran.dayTimePhone`.
- Our `homelessnessContact.phoneNumber` maps to their `homelessness.pointOfContact.primaryPhone`
Consequently, the latter was updated, when we wanted the former.

For prosperity, mappings can be confirmed via `lib/evss/disability_compensation_form/data_translation_all_claim.rb`

The good:
`veteran.dayTimePhone` is already optional on the EVSS end (our `phoneAndEmail.primaryPhone`), and we can move forward with this

**Comment by nnicholas7** [comment]
Just tagging Mock Up Error Message for improved language here- https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/61915

**Comment by mchae-nava** [comment]
@tommasina-va, I have two PRs linked in a previous comment, one of them has the actual schema change.

The slightly tricky part comes with the package version update, which you can read about [here](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/a567cb832aadbb6489beca1ea0445b8dac4a054b/README.md). Once your `vets-json-schema` update have been approved, you need to update the dependency in both `vets-website` and `vets-api`.

Let me know if you want to pair on this

**Comment by mchae-nava** [comment]
Sketch design is outdated, email should NOT be optional, per https://nava.slack.com/archives/C04MJV66ZPC/p1687284906509569?thread_ts=1687284823.122299&cid=C04MJV66ZPC
