### ISSUE TITLE
Test vets-website and vets-api deployment workflows for compatibility with different custom and default PE scenarios

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#57397]
## Issue Description
With the implementation of the custom workflow in devops, we need to now make sure that the values that get sent off to the vets-website and vets-api workflows make it to where they're supposed to go. We also need to ensure that the default behavior launched by pushing directly to these repositories does not break as a result of our changes for custom implementation.

---
## Tasks
- [x] Update vets-website workflow to be compatible with the new values sent from the custom PE launch workflow.
- [x] Update vets-api workflow to be compatible with the new values sent from the custom PE launch workflow.
- [x] Test vets-website workflow functions correctly with both the custom and default PE behaviors.
- [ ] Test vets-api workflow functions correctly with both the custom and default PE behaviors.

## Acceptance Criteria
- [ ] Custom PEs launched for either vets-website or vets-api make it through their respective repositories and pass these values to the main devops workflow.
- [ ] Default push-based PEs still behave as expected and also pass the correct values to the main devops workflow.

**Comment by CBonade** [comment]
![image.png](https://images.zenhubusercontent.com/60aa993146d844d86f494162/0f3aa603-3c76-4d04-88d9-a6d727d09352)

This is a workflow that was pushed directly from vets-website. The branch output appears correct.

![image.png](https://images.zenhubusercontent.com/60aa993146d844d86f494162/433602fd-bc17-4d71-a9b9-5ee47373a041)
This is a custom dispatched PE from the devops custom workflow. The branch output also appears corerct.

These results are consistent on vets-api with both of the same scenarios. Content-build, as it is not supported for MVP, has been disabled in the interim. It will require some extra tinkering once we are ready to go down that road.

**Comment by pjhill** [comment]
Hooray testing -- I did some minimal poking around as well -- looking good!
