### ISSUE TITLE
[Research] My VA: Conduct testing to ensure that My VA works well for screenreader users

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#57398]
## Issue description

Following session in collab cycle, we received feedback from platform related to accessibility of My VA, specifically the Education and training section. This feedback requests that we validate two design choices with screenreader users:
1. No hidden h3 is needed for secondary links in the Education section (from Platform ticket [48678](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48676)
2. Hidden h3 still existing when a section is in the "You have no [...] to show" state (from Platform ticket [47549](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47549)

[For item number 1, Platform wrote:](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48676)
> On the discussion about placing secondary links in the right-hand column on desktop: I think the benefits of a consistent layout (eg. cognitive load, predictability of interaction) are enough that it makes sense to preserve that layout.
> I think @aagosto90's thoughts on not including a hidden H3 for the secondary links in the Education and training section are correct. Since there's no content under the H2 that wouldn't be under the H3, it feels unnecessary. But I'd recommend stopping by Angela Fowler's office hours some time for verification from a full-time screen reader user.

[For item number 2, Platform wrote:](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47549)
> Currently, My VA has visually-hidden headings to help screen reader users navigate through content. The big thing they do is differentiate the right-column blue links from the notifications and actions in the left-column. Example: Under the Benefit Payments H2 heading, there's a screen-reader-only H3 Popular actions for Benefit Payments. I think you should keep those visually-hidden H3s, since the heading hierarchy provides useful structure.
> However, for the situation where the "You have no [...] to show" message appears it may be worth verifying that everything makes sense together, in case any text needs to be adjusted for clarity or to reduce repetition. Just a quick audit of the text on the page (visible and non-visible) to make sure there's nothing unintentionally confusing for screen reader users.

## Tasks

- [x] Attend a11y office hours (or work with another screenreader user) to ensure that Education section of My VA hidden H3 for secondary links makes sense without any other content in that section
- [x] Attend a11y office hours (or work with another screenreader user) to ensure that there is no strange repetition for screen reader users when a section is in the "You have no [...] to show" state.
- [ ] Work with PM to determine what, if any, FE changes need to be made
- [ ] PM to create FE tickets as needed

**Comment by aagosto90** [comment]
Hey @ajakabcin ! I met with Angela Fowler today and determined that no action is needed for either of these tickets. For the education and training section, it does have a hidden H3 for the links and she said that makes sense within the context of the page because that's how it's handled in other sections, and if we do add dynamic content to that section in the future, we can just slide it right in (which I thought was a good point).

For the empty sections, the screen reader read the empty text directly after the H2 and Angela said it wasn't confusing or repetitive and was helpful to hear. 

Should I comment on the platform tickets and close them?

One thing Angela did find is that the titles in the benefit draft application cards are H4s and they should be H3s. We should check if we have a ticket to handle that and if not, create a FE ticket to update that in the code.

**Comment by ajakabcin** [comment]
No further work needed here - thanks Angela!
