### ISSUE TITLE
Update primary devops PE workflow to support custom PE values being written to values files

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#57399]
## Issue Description
The main devops workflow that controls the values file that gets written for each Preview Environment currently only accounts for default behavior. That workflow will need to be adjusted to account for custom variables coming in and will change the image names and other values accordingly. 

---
## Tasks
- [ ] Adjust logic that writes the values files to account for custom PE values as well as default values
- [ ] Test the full workflow from starting at the custom params workflow, all the way to the end of the main devops workflow, from both vets-website and vets-api. Check the values files generated by both to ensure the values are correct.

## Acceptance Criteria
- [ ] The main devops workflow can write values files for both default and custom PEs.
---

**Comment by CBonade** [comment]
This workflow appears to be working correctly after my changes to the best of my testing ability. I've left some logging in so it will be easier for us to test as more changes come down and more people run workflows.

**Comment by pjhill** [comment]
This is pretty neat! I think users will pretty intuitively get this. I can't wait to get this in front of them -- nice!
