### ISSUE TITLE
FE | Profile | Notifications Settings | Editing as a Sub-Task | Add GA for new edit page API calls, change update link href

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#57408]
## Issue Description
On the profile there is a new page that hosts the mobile editing form as its _own paage_. It is live in staging at the moment and when logged in with staging users can be accessed at [the editing page](https://staging.va.gov/profile/edit?fieldName=mobilePhone&returnPath=%2Fprofile%2Fnotifications)

As a team we need to be able to track the usage of this new feature including api success, failures, and navigation from the links on the Notification Settings pages. [Docs for tracking api requests](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/api-call-events) - we should be able to customize the event to include information that indicates it specifically was called from the new edit page.

We also need to update the link that is present when a user has a phone number to also send to the new page.

<img width="663" alt="Screenshot of update link on notification settings" src="https://user-images.githubusercontent.com/8332986/234431170-45bc2b8f-e69a-4b50-b6d1-43b3482137d4.png">

## Front end tasks
- Add specific GA event for the mobile editing page for this page, so that it can be uniquely tracked.
- Update link on Notification Settings to open up editing page (based on feature toggle)
- Roll out to limited group once analytics are verified.

## Acceptance Criteria
- [ ] Analytics captured in GA on staging first then prod
- [ ] Update link uses new page link
- [ ] All tests pass

**Comment by adamwhitlock1** [comment]
For the GA events. It is entirely possible to use the existing events that are fired by the form to get just events that happen on the edit page, so no new code will be required to get analytics for this new page.

I created a couple Widgets on the Authenticated Experience | Sandbox dashboard to show the form submissions, form failures, and also the errors by their specific error code.

https://analytics.google.com/analytics/web/#/dashboard/DRqBrmiyTD6l8L75rei0fw/a50123418w178298118p176884211/_u.date00=20230507&_u.date01=20230614/

Right now if you view the last month of data there are only a few `Profile - Form Submit - Mobile Phone Number` which are all indicative of form submission success, but I triggered some error today, and so we should see some example failure events come in within the next day or 2.

I will update the edit link though and get a PR for those code changes in shortly.

**Comment by adamwhitlock1** [comment]
The second half of this work (updating the link to dynamically use the edit page based on feature toggle) can now be validated, and issue closed once validated.

To validate you can log in with any staging user (I used 202) and verify that they have a mobile phone number saved, then navigate to the notification settings page to verify that the update link now takes the user to the edit page for the mobile phone number specifically.

Below is a screenshot of the link in staging as it should appear. The old behavior was for the link to point to the `/contact-information` page instead of `/edit`

![Screenshot 2023-06-20 at 8.27.20 AM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/317c0ebd-c1d1-4765-a683-05b3b535f716)

**Comment by mtcA6** [comment]
I'll reopen tomorrow if there's an issue w the GA data.
