### ISSUE TITLE
Collaboration Cycle for AE Profile, Notification Settings - Default Send Functionality | EPIC

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-team#57409]
### VFS team name

Authenticated Experience - Profile

### Product name

Notification Settings

### Feature name

Default send functionality

### GitHub label for product

authenticated-exp; profile

### GitHub label for feature

notification-settings

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

Research/Design: Research discovery, usability sessions, and designs have all already completed - need Design Intent Review. Frontend Development: Intend to start frontend implementation of designs in Q2 (Sprint 9 or 10) which is April/May 2023 timeframe.

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

No

### Will your work involve changes to...

Other

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/default-send/README.md

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Notify the Collaboration Cycle team of this ticket in the vfs-platform-support Slack channel.

- [X] I acknowledge that I must notify \#vfs-platform-support after submitting this issue.
</details>

- Kickoff Slack Thread with VFS Team: [link](https://dsva.slack.com/archives/CBU0KDSB1/p1682467300381819)
### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- Navigate to reference link: [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent)
- [ ] Schedule your Design Intent when ready:
   - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders 
   - Click "Schedule Event"
- [ ] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [ ] Link all artifacts **ONLY** in the Design Intent artifacts section below at least two days before the scheduled Design Intent.  **Do NOT add artifacts to Comments section**
  
**Design Intent artifacts**

See Platform guidance on [Design Intent artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Design Intent meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

- [x] Whiteboard sketch or other lo-fi prototypes or wireframes [desktop](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/uuid/433E9253-D180-4607-8CA7-9F1762FBC768), [mobile](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/uuid/A5BD8D07-7DB9-4C99-A79A-73E5412DADBB)
   - We'd also like our design reviewed for our approach to a use case where a user has partial contact information on file. This is "default send adjacent" work, since we're updating the way we handle when user has contact info for one channel, but not both (e.g. has email address on file but not mobile number). We're using the expandable alert - here it is [closed](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/x0gvqD0), and [open](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/EeqpOwq). Note that this piece has not been researched and has placeholder content.
- [ ] User flow
- [x] Research plan ([findings from usability research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/discovery-and-research/usability-study-add-email-jan-2023/findings-summary.md)) 
- [x] Any other artifacts you have so far >  We discussed how our design changes could support VA Notify's requirements for capturing optins and optouts now that we have default send available in July 2022 ([meeting notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/discovery-and-research/default-send/july-2022-notes.md)) 
[default send project outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/notification-preferences/default-send)
  
##### Platform actions
- [x] [Design Intent Slack thread with VFS team](https://dsva.slack.com/archives/CBU0KDSB1/p1683899082135939)
- [x] Meeting date/time: May 18th at 2pm EST
  
##### Platform actions

- [x] If you have feedback, create feedback tickets and link to this epic. Once you have completed you review, check the box next to your practice area
  - [x] Accessibility has completed the review
  - [x] Design has completed the review
  - [x] IA has completed the review
- [x] Update this ticket with the Zoom recording
  - Recording URL: [Zoom Link](https://oddball-io.zoom.us/rec/share/lBPwCVk223TRu1AvFuxG55j2SVLCN3Ccg3mYin637Vsy274Qd5LE8GQ55WJSfv2N.hd4akkjkJjf9qO5P)
  - Password: 8*DYXg?P
  
##### VFS actions

- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Sitewide Content and IA Intake Request
<details>
  <summary>Toggle Sitewide Content and IA Intake Request</summary>

##### VFS actions
- [ ] Complete the [sitewide content and IA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-Content-and-IA-intake-request.2124906551.html)
- [ ] Link to the Sitewide Content and IA Intake Request ticket below

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [x] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

Provide links or documents for the following:

- [ ] Finalized design prototype or mockup
- [x] [sketch files for the various scenarios](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-notification-preferences.md#draft-test-cases-to-account-for-when-we-add-email-as-a-channel)
- [ ] Specify which pages are included in the review > please review the cases detailed out here: [Draft test cases to account for when we add email as a channel](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-notification-preferences.md#draft-test-cases-to-account-for-when-we-add-email-as-a-channel)

**N/A as we completed research/usability testing before Design Intent** 
- [ ] ~~Research plan~~
- [ ] ~~Conversation guide~~
 
**Content artifacts**
 n/a 
- [x] Your product’s content source of truth (this isn't what we're seeking review on, but the product outline can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/notification-preferences))
- [ ] ~Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)~

**IA artifacts**
n/a
- [ ] ~Please include a link to any [Sitewide Content & IA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including an IA review document or intake form.~

  
##### Platform actions
- [x] Midpoint review Slack thread with VFS team: [Link](https://dsva.slack.com/archives/CBU0KDSB1/p1686936171345279)
- [x] Meeting date/time: **Friday, June 23rd at 2:00pm ET**

##### Platform actions

- [ ] If you have midpoint review feedback, create feedback ticket and link to this epic. Once you have completed your review, check the box next to your practice area
  - [x] Design has completed the review
  - [x] Accessibility has completed the review
  - [x] IA has completed the review
  - [ ] Content has completed the review
- [x] Update this ticket with the Zoom recording
  - Recording URL: [Link](https://oddball-io.zoom.us/rec/share/eLe41c-cjuFdRX005asEmX7N3QMrmDJOY42riaJqb3-qEH1czyTxZDxF9VTu84Z5.9v3fLLW3FYKqP_-_)
  - Password: Vn#Y0Y$q
  
##### VFS actions
  
- [x] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [ ] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [ ] Link to the Analytics Implementation and QA Request ticket below

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [ ] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [ ] Link to the Contact Center review request ticket below

</details>

### Staging Review
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [x] I confirm the environment is available and test users have been provided.
- [x] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
 
**Staging Review artifacts**
  
See Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts). Platform findings are based solely on the staging URL and test users provided, as reviewed during the four days before the Staging Review meeting. Any test cases not covered or any ongoing work taking place during the review period may not be reflected in those findings.  

**Product artifacts** 
- [x] Staging URL
     - [x] https://staging.va.gov/profile/notifications
          - [x] if a mobile phone number isn't in the profile there's a message advising as much, following the alert will enter the edit as a subtask flow
               - [x] https://staging.va.gov/profile/edit?fieldName=mobilePhone&returnPath=%2Fprofile%2Fnotifications 
          - [x] if a mobile phone number is available, users will see an 'update' message
               - [x] https://staging.va.gov/profile/edit?fieldName=mobilePhone&returnPath=%2Fprofile%2Fnotifications
- [x] Specify which pages are included in the review: Notification Settings and the Editing as a Subtask Flow (url's above)       
- [x] Staging test user information:  can use any LOA3 user, I use user202, see QA section for full testing scripts   
  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**

**N/a**
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
  
**IA artifacts**

**n/a**
- [ ] Please include a link to any [Sitewide Content & IA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) of the findings you received, including an IA review document or intake form.

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [x] Regression test plan
     - [x]  [qa testing plan in google sheets](https://docs.google.com/spreadsheets/d/1-oSUr_kFqyptbSI6jRC3O7wqk3TNDOwaWedmO3eh7FA/edit?usp=sharing)
- [x] [Test plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/default-send/QA/qaPlan.md) 
- [ ] [Coverage for References](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [x] [Summary(Defects) reports](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports) < see our Test Plan,[ defects are at the bottom](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/default-send/QA/qaPlan.md)
- [x] [E2E tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-e2e-test-participationE2ETestParticipation) (provide a link to the product’s code) [Edit page E2E tests](https://github.com/department-of-veterans-affairs/vets-website/blob/e7c4365653cf653cbf80db1e49dd2799bd73a0f5/src/applications/personalization/profile/tests/e2e/edit/edit.cypress.spec.js)
- [ ] [Code coverage](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-unit-test-coverageUnitTestCoverage) (provide a link to the product’s code)  
  
**Accessibility artifacts**
  
- [x] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D). For details, see [Prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).
     - [x] [accessibile test plan](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/notification_settings/default-send/qa-default-send.md) 
  
##### Platform actions
- [X] [Staging review Slack thread with VFS team](https://dsva.slack.com/archives/C909ZG2BB/p1695763750060569)
- [X] Meeting date/time: Friday, October 6, 2023, at 2 p.m. Eastern

##### Platform actions

- [ ] Update this ticket with the Zoom recording
  - Recording URL: https://oddball-io.zoom.us/rec/share/WR8x-ZcsPgnPViXeNyaOIxtLN9SkP127FvaAi5DtN1vREoUHQBPJDFPcM3jN8jbh.md9sZwP5otJSUWRM
  - Password: 6R#cLsHs
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [ ] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [ ] Link to the Readiness Review ticket below

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by BerniXiongA6** [comment]
Submitted a Slack thread here: https://dsva.slack.com/archives/CBU0KDSB1/p1682467300381819

**Comment by andaleliz** [comment]
@allison0034 FYI, I updated the description and added this.

> We'd also like our design reviewed for our approach to a use case where a user has partial contact information on file. This is "default send adjacent" work, since we're updating the way we handle when user has contact info for one channel, but not both (e.g. has email address on file but not mobile number). We're using the expandable alert - here it is [closed](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/x0gvqD0), and [open](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/EeqpOwq). Note that this piece has not been researched and has placeholder content.

I wanted to flag it to be sure people have a chance to check it out before Thursday's meeting. Thanks!

cc @mtcA6 for awareness

**Comment by allison0034** [comment]
@andaleliz I see that note under the artifact so we will see it. Thank you!

**Comment by andaleliz** [comment]
Awesome, thank you! I wasn't sure how far in advance of the meeting people actually start the review process.

**Comment by allison0034** [comment]
We typically do not look until at least 48 hours before, with design intents sometime the day before. Staging and Midpoints take a but longer ; )

**Comment by adamwhitlock1** [comment]
@mtcA6 Here are some test coverage numbers:

All of Profile
![Screenshot 2023-10-02 at 3 58 38 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/4e5ee1b9-ce80-4193-883f-49f078f7a1e0)

Edit page components:
![Screenshot 2023-10-02 at 4 04 48 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/064f7ef9-2537-4517-aee3-4d304137a250)
