### ISSUE TITLE
Address bugs with Parameterized Workflow for custom PEs

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#57400]
## Issue Description
The parameterized workflow has two bugs that have become visible:

- it doesn't pass the expiration days to the subsequent repositories
- the parameters that are supposed to be dropdown select boxes, are still requesting free input

These bugs should be squashed before this is launched to any users.

---
## Tasks
- [x] Add expiration days to the repository dispatch action.
- [x] Look into why select boxes are not working as expected, and verify this functionality is possible

## Acceptance Criteria
- [ ] Bugs in the parameterized workflow no longer exist.

**Comment by CBonade** [comment]
This is completed. ![image.png](https://images.zenhubusercontent.com/60aa993146d844d86f494162/270e0956-91e5-4a51-b211-fde43caa3940) The options now have select boxes as dropdowns for the fields we want to restrict and the expiration days are being passed accordingly.

**Comment by pjhill** [comment]
Bugs squashed!
