### ISSUE TITLE
Medallia Intercept Survey Question Review

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#57415]
## Issue Description
As part of the work to audit and update the Veteran Feedback Surveys on VA.gov, a review of the intercept survey questions we ask users is necessary to determine if we are asking questions that help provide meaningful feedback to VA and VFS teams and also make sense to the users answering the questions. 

---
## Tasks
- [x] Review research and industry best practices on feedback/satisfaction questions
- [x] Review research and industry best practices on question responses scales and formats (Likert, open text, etc.).
- [x] Complete write up of findings to be reviewed by team
- [x] Determine next steps for survey enhancements

## Acceptance Criteria
- [x] Write up research is complete and presented to team for review
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
I've document some thoughts, recommendations and discussion points [here](https://docs.google.com/document/d/1667UmcucfcOvZMnapc-aT4J8KvKSaZa3OxQChNHFRRI/edit#).

@ATMiddleton and @clantosswett can we meet sometime next week (or later this week) to start talking about any changes we want to make?

**Comment by ATMiddleton** [comment]
Good morning,

I'm out of the office next week Monday - Thursday.  Perhaps we can find
time on Friday this week...

I'm available after 2pm.  Are you @Ian McCullough
***@***.***> and @***@***.***
***@***.***> available at 2pm?

Regards,

Anita
Product Manager
305-522-2306

**Comment by ianMcCullough-ob** [comment]
@ATMiddleton and @clantosswett I'm free tomorrow (5/12) any time after noon EST.

**Comment by ianMcCullough-ob** [comment]
Chante, Anita and I met and reviewed the [findings document](https://docs.google.com/document/d/1667UmcucfcOvZMnapc-aT4J8KvKSaZa3OxQChNHFRRI/edit#). Further research and questions have been outlined in a new ticket.
