### ISSUE TITLE
GA4:  Configuration, Mapping & Data Layer Code - VFS Custom Events

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#57418]
## Issue Description
As part of the GA4 migration we need to configure custom events needed by VFS team.  

We will likely break this out by VFS teams for tracking
---
## Tasks
- [ ] Define all required events 
- [ ] Complete custom event set up/configuration as required

## Acceptance Criteria
- [ ] Above tasks have been completed and 3-5 VAOS custom events are actively tracking in GA4.

**Comment by michelle-dooley** [comment]
link to the ticket from VAO team https://github.com/department-of-veterans-affairs/va.gov-team/issues/57623

**Comment by michelle-dooley** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-vaos.md

**Comment by michelle-dooley** [comment]
Sprint update:  VAOS dependencies so not completely in our control.  This work will continue into the next sprint.

**Comment by michelle-dooley** [comment]
Sprint update: VAOS dependencies so not completely in our control. This work will continue into the next sprint.

**Comment by johnny-jesensky-adhoc** [comment]
Closing this ticket out, as was creating factoring an older GA4 transition workflow. Will be working to track custom events for VFS Teams, but will be handled using GH templates, in separate tickets.

FYI @jestutt
