### ISSUE TITLE
BE | Profile | Direct Deposit | Document Lighthouse Testing and Issue Identification

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#57419]
## Background
Run through the list of test cases and ensure that the same HTTP status code is being returned from both EVSS and Lighthouse.

Document and create any additional tickets for any issues discovered.

- [QA spreadsheet](https://docs.google.com/spreadsheets/d/12gvlkGnwt206BBYY89gDIYG1AtD6j9uCYMr5x99Nzns/edit#gid=0).

## Tasks
For each test case:
- [x] Run the tests
- [x] If the response is different than expected or different from EVSS, then document the result

## Acceptance Criteria
- [x] Create ticket that contains all issues
- [x] Review each issue with Lighthouse contact (David Lennon) if necessary

**Comment by tpharrison** [comment]
Ran through test cases.  
- All response status codes match between EVSS and LH
- In some cases, even though response status code are equal, the UI behaves differently.  This may be due to error message differences.
- In one case, the bank name is not returned from LH.  I will follow up on this.
