### ISSUE TITLE
Supplemental Claims | Check & fix phone number validations

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#57428]
## Issue Description

Our Supplemental Claim form is at 75%, and we noticed one submitted rejection was due to the phone number not being included. Some how the submission was missing both the primary phone selection and a phone number value. These should have been caught within the form flow and at the review & submit page before submission. Investigate & fix this issue.

## Tasks

- [ ] Investigate validation checks on primary phone selection page
- [ ] investigate validation checks on review & submit page
- [ ] Add missing validation checks
- [ ] Add unit tests
- [ ] Update e2e tests as needed

## Acceptance Criteria
- [ ] All tasks complete
- [ ] All tests passing

**Comment by Mottie** [comment]
@saderagsdale @eileen-coforma Did you want to check this in staging before closing this ticket?
