### ISSUE TITLE
Domo Dataset Clean Up

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#57429]
## Issue Description

Our Domo datasets have grown considerably resulting in increasing costs.  As part of this clean up we will removed 2019 & 2020 data from standardized dashboard datasets.  We also audit all Domo datasets to determine if they are still needed and if they are a duplicate of another view and remove accordingly.

## Tasks
- [x] Complete dataset audit [tracking doc](https://docs.google.com/spreadsheets/d/1y6WRGftpGzzCwrytaFjoxrzZaLBmAqNZ58sXIQMmj68/edit#gid=0)
- [ ] Remove 2019 & 2020 data from datasets as defined in worksheet
- [x] Review [OUTPUT] datasets to determine if needed or if original view can be used for attached cards.
- [x] For datasets identified for removal - document cards and dataflows they may be a part of.  
- [ ] Update tracking doc as datasets are updated/removed

NOTE:  Make sure before we remove any dataset that all cards attached to it are directed to another dataset or are no longer needed.  Also confirm no additional dataflows are dependent upon that table.

## Acceptance Criteria
- [ ] Clean up process as outlined above is completed and our total Domo row counts are < 1M (per current Domo cost structure)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelle-dooley** [comment]
Completed clean up.  Next step is to removed 2019 historical data that will be a different ticket.
