### ISSUE TITLE
KPI Dashboard Eligibility - Table Updates

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#57432]
## Issue Description

Need to update the [KPI dashboard tracker](https://docs.google.com/spreadsheets/d/1JdNPKo9y-4o2c_HaWIne2L6H310fhRn2M51e5NvHdxE/edit?pli=1#gid=1660978947).

## Tasks
- [x] Confirm VFS teams are up to date
- [x] Confirm all VFS products are included
- [x] Update dashboard flag if they have been added
- [x] Make sure [Dashboard eligibility] page is updated and shows all rows

## Acceptance Criteria
- [x] When steps above have been completed and the eligibility dashboard is up to date.
---
