### ISSUE TITLE
Medical Records page - Unauthenticated users main content updates

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#5743]
**User Story**
As a user who is browsing the Medical Records page on VA.gov without authenticating (logging in), I want the content on the page (above and below the alert box) to be neutral between MHV and Cerner so that I am not confused about where my patient portal information is housed.

**Acceptance Criteria**
1. Content on Medical Records page (above and below the alert box) for unauthenticated users does not contain any references to MHV or Cerner

**Tasks**
- [ ] SSO-Login team: First pass at copy changes
- [ ] VSP Content-IA team: Edit and validate
- [ ] SSO-Login team: Ensure frontend implementation

_Alert box content updates are housed in separate tickets_

**Comment by bridgethapner** [comment]
I don't believe any updates are needed to the unauth page. Moving to icebox for now.

**Comment by bridgethapner** [comment]
Hi @peggygannon - Looking at this unauth page (https://www.va.gov/health-care/get-medical-records/) I don't believe any content updates are needed. But I wanted to move into this sprint + ask you to take a look and see if you think the same.

**Comment by FranECross** [comment]
Ticket is old and outdated. Closing.
