### ISSUE TITLE
Update GA Equivalent Worksheet for Domo QA

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#57434]
## Issue Description

Need to complete/update the [Dashboard GA Equivalents](https://vfs.atlassian.net/wiki/spaces/AT/pages/2234286081/Data+QA+-+Standardized+Dashboard+GA+Equivalents) table to be used for Domo cards QA.  

Artifacts:
[Supplemental Claim QA tracker](https://docs.google.com/spreadsheets/d/1QoN1ZLffiNMY7CbTy5SCdjWrpClUz3uIicsNtLRUxmA/edit#gid=0)
[Supplement Claim GA submissions report](https://analytics.google.com/analytics/web/?authuser=0#/savedreport/FutJpPBmRyaGua5dJkUmVw/a50123418w177519031p184624291/_u.date00=20230402&_u.date01=20230408&_r.dsa=1&_.sectionId=&_.useg=userZ1RKgkH7SWmy5bRjiBOmiA,usercv5vQYZpQzWpUs-kKSsXjQ,userUs855vitS3G_NNfLh6mMAg,userqyv8MfOySGqGaePBq9n9uQ&_.advseg=/)
[User counts by page GA report](https://analytics.google.com/analytics/web/?authuser=0#/savedreport/FutJpPBmRyaGua5dJkUmVw/a50123418w177519031p184624291/_u.date00=20230402&_u.date01=20230408&_r.dsa=1&_.sectionId=&_.useg=userZ1RKgkH7SWmy5bRjiBOmiA,usercv5vQYZpQzWpUs-kKSsXjQ,userUs855vitS3G_NNfLh6mMAg,userqyv8MfOySGqGaePBq9n9uQ&_.advseg=/)
[Device Brower Campaign GA reports](https://analytics.google.com/analytics/web/?authuser=0#/savedreport/FutJpPBmRyaGua5dJkUmVw/a50123418w177519031p184624291/_u.date00=20230402&_u.date01=20230408&_r.dsa=1&_.sectionId=&_.useg=userZ1RKgkH7SWmy5bRjiBOmiA,usercv5vQYZpQzWpUs-kKSsXjQ,userUs855vitS3G_NNfLh6mMAg,userqyv8MfOySGqGaePBq9n9uQ&_.advseg=/)

## Tasks
- [ ] Create generic/template version of GA reports 
- [ ] Add links and instructions to table
- [ ] Create new GA reports for those not already defined above or listed in worksheet (confirm worksheet links are correct)

## Acceptance Criteria
- [ ] GA equivalent updates have been completed.

**Comment by michelle-dooley** [comment]
this work will be ongoing.
