### ISSUE TITLE
[AFTER RESEARCH] [UX] Create Wireframe to Address CAIA Heading Feedback for Confirmation Page

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#57444]
## Description
We received feedback from IA/Content/A11y prior to the midpoint review for the Unified Check-in feature; these are items that were not related to that effort but for which we thought we should address

### Convert two cards to h2s on check-in confirmation page

Don't stack alerts; convert to h2 headings. 
[Check-in Sketch comment](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/L40YYnQ?annotation=29bf88bc-5190-4ba4-b06e-5d37be486242&utm_medium=email&_hsmi=210989272&_hsenc=p2ANqtz-8h796b9xy37cK9SnJxWc9Ukg9TGkBKZPfId1eaeFQIJeqSyeCbDdl5YiZJi3oOYdV8DxLPTt4hMUHXq7PgbJGtHn6skQ&utm_source=hs_email#Comment)
[Pre-check-in Sketch comment](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/zx95r4b?annotation=cd106215-841f-49ce-a5d8-28e62530d91a&utm_medium=email&_hsmi=210989272&_hsenc=p2ANqtz-88FTnJen9W8bd_17ZFKRcn1iffYEZ5E66pIUncWLkpGI-AlWH0tsGAJY3xqMmYMIrdTdKYtM48zCozbu2DT_mdQgSkMA&utm_source=hs_email#Comment)

## Tasks
- [ ] Create final mockups with callouts 
- [x] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [ ] UI review meeting with product/UX team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Wireframe available on Sketch Cloud

**Comment by benbrasso-agile6** [comment]
Added @zach-park per [slack convo](https://dsva.slack.com/archives/C04J6H2LYUU/p1684880592147929)

**Comment by benbrasso-agile6** [comment]
@cgednalske how's our progress here? How can I help?

**Comment by benbrasso-agile6** [comment]
After thinking about this more and considering where we are right now, I would recommend focusing this ticket on solving for pre-check-in and check-in confirmation pages in unified check-in. And, not as a blocker to begin the moderated research. So, this should give us time to chat with VA Forms team, Laura, etc. 

Once we complete this ^^ then we can decide what tickets we want or need for our production apps. 

Hopefully this direction narrows the scope. At least, that's my goal here.

**Comment by cgednalske** [comment]
Sounds good @benbrasso-agile6! Here's an update on how this work is coming along for unified experience.

## #1

For #1, UX landed on the following structure in our discovery, with cards replacing the alerts and surfacing Appointment and Travel Claim info. Will take this to platform office hours next week to see if there are any concerns or further changes we should make. We'll also want to run the content by Laura, which can start in slack and turn into a meeting if needed. 

<img width="482" alt="Screenshot 2023-05-25 at 4 30 35 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/79372956/c1ee4f5b-9bb4-4b6a-8357-59f4058be9e3">

## #2

For #2, @kellysmith1008 and I are working through different options for where we can place the information on how to update contact information, but are finding this trickier. We will meet with Laura to talk through the different options of where this information best fits. I believe this part is now lower priority than the cards and heading structure in #1 - which resolves the launch-blocking issue of stacked alerts (for unified check-in).

**Comment by cgednalske** [comment]
For reference: We're exploring and finessing the many use cases for this in our collaboration Sketch page, [a11y changes - confirmation page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/24358612-4675-4BB2-852E-8E7EA58D64B6/canvas).

**Comment by benbrasso-agile6** [comment]
In talking to christina, we will need to create a separate/new ticket for applying this to unified check-in pre-check-in.

**Comment by benbrasso-agile6** [comment]
If Christina and team can speak to Larua about unified check-in travel confirmation pages, then Christina can toss that in CodePen (somewhat) quickly.

**Comment by cgednalske** [comment]
@loripusey @benbrasso-agile6 -- To recap today's review for part #1 of this ticket, [this design](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/1V22dAw) was approved by platform as a solution for the stacked alert issue 🎉  Once Laura (sitewide content) reviews the text, we'll be able to update this throughout unified check-in (check-in) wireframes and CodePen, which won't take long. So this ticket will carry over a bit, but shouldn't be much. 

For the contact information part of this ticket (#2), we have work already done there but will need to collaborate more closely with Laura in the separate ticket Ben mentioned above. Other than that, we shouldn't need any other follow-up tickets. 

I believe that's all I have to relay, but let me know if there is another specific question about this ticket I'm forgetting to answer. 🙂

**Comment by loripusey** [comment]
Thanks @cgednalske , I'll roll it over into the new sprint.

**Comment by benbrasso-agile6** [comment]
Created ux ticket for the pre-check-in/accordion work - https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/59309

**Comment by cgednalske** [comment]
Update on this work: [New confirmation page structure](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/dgw5a2m) as suggested by CAIA and approved by Platform (image below). Warning and success alerts will stay alerts. Info alerts will not.

The only pages that still need attention are the error pages, which have a tricker layout. @ytsaoca is looking into those. 

<img width="223" alt="Screenshot 2023-06-07 at 9 03 39 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/79372956/fb095898-943d-485c-9582-b19f2d166fc4">

**Comment by ytsaoca** [comment]
Completed editing the check-in and pre-check-in confirmation pages.  Will looking into the error pages.

The confirmation page changes:
- Added title "Your appointment" as H2
- Edited the title of "The other steps to manage appointments" symbol from H3 to H2
- Not sure if the spacing rules still apply, but I make the spacing 60 px among each section.

'cc @zach-park @benbrasso-agile6 @cgednalske

**Comment by benbrasso-agile6** [comment]
@cgednalske let's think about other work that Ya-ching can help on

**Comment by cgednalske** [comment]
@ytsaoca nice! Looks good 👍 @benbrasso-agile6 now seems like a good time to finish figuring out the error pages if Ya-ching's up for that. 👀

**Comment by loripusey** [comment]
@cgednalske & @benbrasso-agile6 to validate

**Comment by cgednalske** [comment]
Looks good to me! 

**For reference:** All confirmation pages updated with new heading structure and alerts above - per recommendation of of CAIA and design system folks. **Take other steps to manage appointments** changed to **Manage appointments**. Both of these changes are being tested by Veterans in the unified check-in usability study.
