### ISSUE TITLE
Create initial boilerplate for find MPI profile by Vista

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#57447]
## Issue Description
Create initial classes and methods that will be needed for finding an MPI profile by vista ID

- `MPI::Services.find_profile_by_vista`
- `MPI::Messages::FindProfileByVista`

---
## Tasks
- [x] Create initial methods models
- [ ] Add initial rspec tests to add to

## Acceptance Criteria
- [ ] The project has classes and methods to build onto to get profile by vista
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
