### ISSUE TITLE
Create MPI message for find profile by Vista

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#57449]
## Issue Description
To perform the MPI profile request we will need to generate a MPI message for getting profile by Vista to pass along to the service.

---
## Tasks
- [ ] Create initializer for MPI message
- [ ] Add necessary parameteres
    - [ ] Identifier
    - [ ] Search Type

## Acceptance Criteria
- [ ] We have an MPI message for getting profile by Vista to work with
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
