### ISSUE TITLE
Build request body for MPI find profile by Vista

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#57450]
## Issue Description
The MPI module has some helpers and builders to help build the SOAP request body but we will need to specialize it for the Vista identifier use case.

---
## Tasks
- [x] Determine what request body will look like with Vista
- [x] Use request helpers to build body

## Acceptance Criteria
- [x] We have a request body we can test and send to MPI for Vista
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
