### ISSUE TITLE
Build MPI response from profile fetch with vista

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#57452]
## Issue Description
Once the service method has called the MPI endpoint to get the profile from the Vista ID we can create a response object using `MPI::Services::FindProfileResponseCreator`

---
## Tasks
- [x] Take response from MPI service and build response class

## Acceptance Criteria
- [x] We have a parsed MPI profile from the Vista ID
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
