### ISSUE TITLE
[BE] My VA: Update appeals BE unit test

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#57454]
## Background
Post EVSS > Lighthouse migration, we'll need to review and update BE unit tests pertaining to the claims and appeals section. This ticket is to address the v0/appeals_controller.rb unit test.

## Tasks
- [ ] Write a controller spec for [`v0/appeals_controller.rb`](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/appeals_controller.rb)
- [ ] Write a unit test for [`Caseflow#get_appeals`](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/caseflow/service.rb#L31-L41)
- [ ] Update the [audit doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/be-unit-test-audit.md) to show that this controller now has tests

## Acceptance Criteria
- Test is written, running, and passing

## Resources
- [`v0/appeals_controller.rb`](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/appeals_controller.rb)
- [`Caseflow#get_appeals`](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/caseflow/service.rb#L31-L41)
- [audit doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/be-unit-test-audit.md)

**Comment by ajakabcin** [comment]
@dellerbie we'll need to come back to this after the EVSS migration so I updated this ticket and moved over to that epic.

**Comment by ajakabcin** [comment]
not needed
