### ISSUE TITLE
Scheduling page - Unauthenticated users main content updates

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#5745]
**User Story**
As a user who is browsing the Scheduling page on VA.gov without authenticating (logging in), I want the content on the page (above and below the alert box) to be neutral between MHV and Cerner so that I am not confused about where my patient portal information is housed.

**Acceptance Criteria**
1. Content on Scheduling page (above and below the alert box) for unauthenticated users does not contain any references to MHV or Cerner

**Tasks**
- [x] SSO-Login team: First pass at copy changes
- [ ] VSP Content-IA team: Edit and validate
- [ ] SSO-Login team: Ensure frontend implementation

_Alert box content updates are housed in separate tickets_

**Comment by bridgethapner** [comment]
I don't think any updates will be needed to the unauth state of Scheduling - the page doesn't currently reference MHV explicitly. Moving to icebox.

**Comment by bridgethapner** [comment]
I don't believe changes will be needed here as it stands, but recognize changes to static content will be made by the VAOS team. Have moved ticket to ready because this seems like a useful ticket to link to relevant VAOS tickets on static scheduling page content updats.

**Comment by bridgethapner** [comment]
Moving to blocked because we need clarity on Cerner scheduling functionality to recommend content changes. All areas where clarity is needed are circled in *orange* [here](https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/404881624) and questions are in Invision comments. Summary of questions: 

1. [There are currently 8 features listed under **How can VA appointment tools help me manage my health care?**](https://www.va.gov/health-care/schedule-view-va-appointments/), but looking at Cerner's portal it seems these are not features of Cerner. I have removed the following bullets from this list: 
- Reschedule appointments
- Set up email reminders for upcoming appointments
- Look up past appointments from the last 2 years
- Add non-VA appointments to your health calendar

**I need confirmation: are these features listed above indeed _not_ available in Cerner?** 

2. Under **Can I use this tool to schedule non-VA appointments?** today, the section says "Yes. You can schedule VA and non-VA appointments with this tool." 

**Can users schedule non-VA appointments in Cerner? I can't tell.**

**Comment by bridgethapner** [comment]
## Summary of Content Changes

Content changes are outlined in pink in [the wireframe](https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/404881624). 

#### Content Change 1
**You can use these tools to:**
- Schedule some of your VA medical appointments online
- Cancel appointments made online
- View appointments on your health calendar
- Find the location of the VA facility for your appointments
- Print a list of your future appointments

#### Content Change 2
**Can I use these tools to schedule non-VA appointments?**
It depends on the VA health management portal you are using. Once you’re signed in to the appointments tool, you’ll be able to see what providers you can schedule with online.

#### Content Change 3
**What if I have more questions?**
If you have questions about appointment scheduling on MyHealtheVet, please go to the [VA Appointments FAQs](https://www.myhealth.va.gov/mhv-portal-web/faqs#Appointments) on the My HealtheVet web portal.

Or contact the My HealtheVet help desk at 877-327-0022 (TTY: 800-877-8339). We’re here Monday through Friday, 7:00 a.m. to 7:00 p.m. CT.

You can also [contact us online](https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/contact-mhv).

**Comment by peggygannon** [comment]
@bridgethapner per our 4/2 content sync: 

Here are the updates to the **Unauthenticated** Schedule and View appointments page: 

1. rewrite header and first sentence to:
How can these appointment tools help me manage my health care?
These appointment tools offer a secure, online way......

2. Under "What if I have more questions?
Please update first sentence to unbrand the tool name since we don't know which tool the users needs at this point. 


**If you have questions about scheduling an appointment,** please go to the VA Appointments FAQ.......

**Comment by bridgethapner** [comment]
Thanks, @peggygannon!

@hinzed1127 The final page content is done, [the wireframe is here](https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/404881624_-5745-Scheduling-Unauth). 

# Summary of content changes

## Content change 1
#### How can these appointment tools help me manage my health care?
These appointment tools offer a secure, online way to schedule, view, and organize your VA appointments. The appointments you can schedule online depends on your facility, the type of health service, and other factors.

- Schedule some of your VA medical appointments online
- Cancel appointments made online
- View appointments on your health calendar
- Find the location of the VA facility for your appointments
- Print a list of your future appointments

## Content change 2
#### Can I use these tools to schedule non-VA appointments?
It depends on the VA health management portal you are using. Once you’re signed in to the appointments tool, you’ll be able to see what providers you can schedule with online.

## Content change 3
#### What if I have more questions?
If you have questions about scheduling an appointment, please go to the [VA Appointments FAQs](https://www.myhealth.va.gov/mhv-portal-web/faqs#Appointments) on the My HealtheVet web portal.

Or contact the My HealtheVet help desk at 877-327-0022 (TTY: 800-877-8339). We’re here Monday through Friday, 7:00 a.m. to 7:00 p.m. CT.

You can also [contact us online](https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/contact-mhv).

**Comment by FranECross** [comment]
Ticket is old and outdated. Closing.
