### ISSUE TITLE
 [Sign-in Service Microservice] - Spike: Deployed environments and deployment processes

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/va.gov-team#57464]
### Description of Spike
Which environments do we want to have? How should we utilize envs for QA/testing? What should our deployment process look like?

# TODO
**In order to** GOAL,

**we need to** ACTION,

**so that** VALUE.

#### Acceptance Criteria
- [ ] Documentation has been updated
- [ ] Next steps have been determined and documented
- [ ] AC1
- [ ] AC2

#### MR Approver
- TBD

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
