### ISSUE TITLE
[FE] My VA: Write FE unit tests for personalization/dashboard/actions

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#57462]
## Background
After completing an audit of FE unit tests on My VA, we found several that were missing. This ticket is to address unit tests for `personalization/dashboard/actions`:
- claims.jsx
- debts.js
- messaging.js
- ~notifications.js~
- payments.js

## Tasks
- [x] Write FE unit test for `claims.jsx`
- [x] Write FE unit test for `debts.js`
- [x] Write FE unit test for `messaging.js`
- [ ] ~Write FE unit test for `notifications.js`~
- [x] Write FE unit test for `payments.js`
- update [audit table](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/fe-unit-test-audit.md#personalizationdashboardactions) after validation

## Acceptance Criteria
- Unit tests are written and running 
- `/actions/` has >80% coverage

## Resources
See files linked in `personalization/dashboard/actions' [table](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/fe-unit-test-audit.md#personalizationdashboardactions)

**Comment by ajakabcin** [comment]
@dellerbie  and @allisonlu - I'm pulling this out of the sprint for now, but if either of you end up with bandwidth feel free to pull back in, just let me know - thanks!

**Comment by ajakabcin** [comment]
Not started in sprint 21, moving back to ready to be picked up at a later time

**Comment by allisonlu** [comment]
i made tiny progress with this, but i will keep this as 4 points for sprint 31

**Comment by allisonlu** [comment]
@ajakabcin 

updating to 0 points for sprint 32! just need validation, and there aren't any visible changes to the UI.

@adamwhitlock1 @DanielMiller-agile6 

can you help check that my commit is indeed on staging? 

https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/

**Comment by adamwhitlock1** [comment]
I think I can provide 'validation'. The changes have been merged into main for a few days now. All tests are consistently passing and there is showing an increase in test coverage at the [platform unit test coverage dashboard.](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report)

![Screenshot 2024-03-14 at 12 06 36 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/e27fc7ca-d3fa-40a4-87f4-6e63f8514309)

I'd say close it out!
