### ISSUE TITLE
[FE] My VA: Write FE unit test for RenderWidgetDowntimeNotification component

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#57472]
## Background
After completing an audit of FE unit tests on My VA, we found several that were missing. This ticket is to address the unit test for the `RenderWidgetDowntimeNotification` component.

## Tasks
- [x] Confirm whether the components is being used on My VA and note that in the audit list 

_If not in use on My VA_
- [ ] Log as not in use on the audit table
- [ ] Put the ticket back into backlog
- [ ] Let PM know by comment on this ticket (tag them)

_If they are in use on My VA_
- [x] Write/update FE unit test(s) for the `RenderWidgetDowntimeNotification` component
- [x] Test
- [x] Move to validate and tag another developer for validation
- [ ] Update audit list once complete
- [ ] Close the ticket

## Acceptance Criteria
- Unit test(s) updated/written and running _OR_
- Ticket is moved to backlog

## Resources
- Full audit [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/fe-unit-test-audit.md#personalizationdashboardcomponents)
- [RenderWidgetDowntimeNotification.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/RenderWidgetDowntimeNotification.jsx)

**Comment by adamwhitlock1** [comment]
The tests for this component have been merged into main and the file `helpers.jsx` is where this function is called and test coverage for that file is now at or above 80% for all sections:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWFFQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--93f09470b14571c8fe73fe32f7ad19b007c949ec/Screenshot%202023-10-30%20at%2011.58.21%E2%80%AFAM.png)

**Comment by allisonlu** [comment]
can confirm that i also see the same coverage! thanks @adamwhitlock1 !!
