### ISSUE TITLE
[FE] My VA: Write FE unit tests for all Claims and Appeals components

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#57477]
## Background
After completing an audit of FE unit tests on My VA, we found several that were missing. This ticket is to address unit tests for Claims & Appeals components:
- `claims-and-appeals/Appeal.jsx`
- `claims-and-appeals/Claim.jsx`
- `claims-and-appeals/Decision.jsx`

## Tasks
- [ ] Confirm whether these components are being used on My VA and note that in the audit list 
- [ ] If they are not being used log them as not in use, put the ticket back into backlog, and let PM know via comment on this ticket

If they are being used on My VA: 
- [ ] Write FE unit test for `claims-and-appeals/Appeal.jsx` component
- [ ] Write FE unit test for `claims-and-appeals/Claim.jsx` component
- [ ] Write FE unit test for `claims-and-appeals/Decision.jsx` component
- [ ] Test
- [ ] Move to validate
- [ ] Update audit list

## Acceptance Criteria
- Unit test(s) is written and running _OR_
- Ticket is moved to backlog

## Resources
- [claims-and-appeals/Appeal.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/claims-and-appeals/Appeal.jsx)	
- [claims-and-appeals/Claim.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/claims-and-appeals/Claim.jsx)
- [claims-and-appeals/Decision.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/claims-and-appeals/Decision.jsx)
- Full audit [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/fe-unit-test-audit.md#personalizationdashboardcomponents)

**Comment by adamwhitlock1** [comment]
Yep, validated tests running and passing. You can close this out now.

**Comment by ajakabcin** [comment]
Closing per Adam's comment
