### ISSUE TITLE
[FE] My VA: Write FE unit tests for all Benefit Payments components

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#57476]
## Background
After completing an audit of FE unit tests on My VA, we found several that were missing. This ticket is to address unit tests for Benefit payments components:
- `benefit-payments/BenefitPayments.jsx` 
- `benefit-payments/PaymentsCard.jsx`

## Tasks
- [x] Confirm whether these components are being used on My VA and note that in the audit list 
- [x] If they are not being used log them as not in use, put the ticket back into backlog, and let PM via comment on this ticket

If they are being used on My VA: 
- [x] Write FE unit test for `benefit-payments/BenefitPayments.jsx`  component
- [x] Write FE unit test for `benefit-payments/PaymentsCard.jsx` component
- [x] Test
- [x] Move to validate
- [x] Update audit list

## Acceptance Criteria
- Unit test(s) is written and running _OR_
- Ticket is moved to backlog

## Resources
- [benefit-payments/BenefitPayments.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/benefit-payments/BenefitPayments.jsx)
- [benefit-payments/PaymentsCard.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/benefit-payments/PaymentsCard.jsx)
- Full audit [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/fe-unit-test-audit.md#personalizationdashboardcomponents)

**Comment by adamwhitlock1** [comment]
Yep, close it out 🎉
