### ISSUE TITLE
[FE] My VA: Write FE unit test for Apply for Benefits components

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#57474]
## Background
After completing an audit of FE unit tests on My VA, we found several that were missing. This ticket is to address unit tests for  Apply for Benefits components:

- `apply-for-benefits/ApplicationsInProgress.js`
- `apply-for-benefits/BenefitOfInterest.jsx`
- `apply-for-benefits/SavedApplications.jsx`

## Tasks
- [ ] Confirm whether these components are being used on My VA and note that in the audit list 
- [ ] If they are not being used log them as not in use, put the ticket back into backlog, and let PM via comment on this ticket

If they are being used on My VA: 
- [ ] Write FE unit test(s) for `apply-for-benefits/ApplicationsInProgress.js` component
- [ ] Write FE unit test for `apply-for-benefits/BenefitOfInterest.jsx` component
- [ ] Write FE unit test for `apply-for-benefits/SavedApplications.jsx` component
- [ ] Test
- [ ] Move to validate
- [ ] Update audit list

## Acceptance Criteria
- Unit test(s) is written and running _OR_
- Ticket is moved to backlog

## Resources
- `[apply-for-benefits/ApplicationsInProgress.js](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/apply-for-benefits/ApplicationsInProgress.jsx)
- [apply-for-benefits/BenefitOfInterest.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/apply-for-benefits/BenefitOfInterest.jsx)
- [apply-for-benefits/SavedApplications.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/apply-for-benefits/SavedApplications.jsx)
- Full audit [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/fe-unit-test-audit.md#personalizationdashboardcomponents)

**Comment by adamwhitlock1** [comment]
Yep, can confirm tests are written, passing, and merged to main. Good to close this one out!
