### ISSUE TITLE
[FE] My VA: Write FE unit tests for all Debts components

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#57478]
## Background
After completing an audit of FE unit tests on My VA, we found several that were missing. This ticket is to address unit tests for Debts components:
- `debts/CopaysCard.jsx`
- `debts/DebtsCard.jsx`
- `debts/Debts.jsx`

## Tasks
- [x] Confirm whether these components are being used on My VA and note that in the audit list 
- [x] If they are not being used log them as not in use, put the ticket back into backlog, and let PM via comment on this ticket

If they are being used on My VA: 
- [x] Write FE unit test for `debts/CopaysCard.jsx` component
- [x] Write FE unit test for `debts/DebtsCard.jsx` component
- [x] Write FE unit test for `debts/Debts.jsx` component
- [x] Test
- [x] Move to validate
- [x] Update audit list

## Acceptance Criteria
- Unit test(s) is written and running _OR_
- Ticket is moved to backlog

## Resources
- [debts/CopaysCardjsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/debts/CopaysCard.jsx)
- [debts/DebtsCard.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/debts/DebtsCard.jsx)
- [debts/Debts.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/debts/Debts.jsx)
- Full audit [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/fe-unit-test-audit.md#personalizationdashboardcomponents)

**Comment by allisonlu** [comment]
updating the issue description a bit, since @dellerbie [cleaned up v1/v2 components last week](https://github.com/department-of-veterans-affairs/vets-website/pull/25418). woo!

**Comment by allisonlu** [comment]
[Audit list](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/fe-unit-test-audit.md#personalizationdashboardcomponents) has also been updated
