### ISSUE TITLE
[FE] My VA: Write FE unit test for Dashboard components

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#57470]
## Background
After completing an audit of FE unit tests on My VA, we found several that were missing. This ticket is to address unit tests for `Dashboard.jsx` and `DashboardWidgetWrapper.jsx` components.

## Tasks
- [x] Confirm whether these components are being used on My VA and note that in the audit list 
- [x] If they are not being used log them as not in use, put the ticket back into backlog, and let PM via comment on this ticket
- [x] If they are being used on My VA, write FE unit test(s) for `Dashboard.jsx` component and `DashboardWidgetWrapper.jsx` component
- [x] Test
- [ ] Move to validate
- [ ] Update audit list

## Acceptance Criteria
- Unit test(s) is written and running _OR_
- Ticket is moved to backlog

## Resources
- [Dashboard.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/Dashboard.jsx)
- [DashboardWidgetWrapper.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/DashboardWidgetWrapper.jsx)
- Full audit [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/fe-unit-test-audit.md#personalizationdashboardcomponents)

**Comment by adamwhitlock1** [comment]
Yep, looks good! Go ahead and close this out.
