### ISSUE TITLE
[FE] My VA: Write FE unit test for IconCTALink component

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#57471]
## Background
After completing an audit of FE unit tests on My VA, we found several that were missing. This ticket is to address the unit test for the `IconCTALink` component.

## Tasks
- [x] Confirm whether the component is being used on My VA and note that in the audit list 

_If not in use on My VA_
- [ ] Log as not in use on the audit table
- [ ] Put the ticket back into backlog
- [ ] Let PM know by comment on this ticket (tag them)

_If they are in use on My VA_
- [x] Write/update FE unit test(s) for the `IconCTALink` component
- [x] Test
- [x] Move to validate and tag another developer for validation
- [ ] Update audit list once complete
- [ ] Close the ticket

## Acceptance Criteria
- Unit test(s) updated/written and running _OR_
- Ticket is moved to backlog

## Resources
- Full audit [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/fe-unit-test-audit.md#personalizationdashboardcomponents)
- [IconCTALink.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/IconCTALink.jsx)

**Comment by adamwhitlock1** [comment]
Tests for this component have been merged to main and test coverage is acceptable now:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelNFQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--734917ecd7e47ad01b5ec49ee73ba4c886ffdb88/Screenshot%202023-10-30%20at%2012.02.48%E2%80%AFPM.png)

@allisonlu can youu confirm that this is good to close please?

**Comment by allisonlu** [comment]
looks good 💯 thanks @adamwhitlock1 !
