### ISSUE TITLE
526ez | Assess code and identify KPIs

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#57489]
## Value Statement
**_As a_** software developer
**_I want to_** assess the health of the software code for the 526ez service
**_So that_** I can identify areas for improvement and track progress over time.

---
## Background Context
The details for this work are captured in [this epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57473). 

## Acceptance Criteria
- [x] Code analysis has been run against the codebase to identify what actions are supposed to be occurring and various states/paths of execution
- [x] All identified actions have been documented
- [x] Key Performance Indicators (KPIs) have been identified and documented

## Out of scope
Moderate/major bug fixes should be ticketed separately.

## Tasks

- [x] Review the form to understand what actions the form can take (list them out/document)
- [x] Craft KPIs for how you measure success for those things

## Definition of Done

- [x] We've identified the specific objectives and goals for assessing the health of the form
- [x] We've documented the specific actions of the form and how they translate into KPIs
- [x] The KPIs have been identified and agreed upon by all relevant stakeholders.
- [ ] (as needed) Reports summarizing progress and highlighting areas for improvement or concern have been generated and shared with the relevant stakeholders.
- [ ] Make revisions to the [Logging and Monitoring Framework](https://docs.google.com/document/d/1TqBQmbYGF7Xvjzs_2q83qDuoKd9022n153wVl8V4MmI/edit#heading=h.wb43vjfgcjqq) as needed and report back to Jared/Kevin.
- [ ] The user story has been reviewed and approved by all relevant stakeholders, including product and development.

**Comment by kylesoskin** [comment]
# VA.gov 526ez KPIs


### Objective 

Identify all backend actions and items a 526ez submission on va.gov can trigger. From that determine all metrics around those that need to be captured, monitored, logged, and alerted on. 


### List of possible Discrete Submission Actions - Auto Establishment Path

|                           |                                                                                                                            |                                   |                                  |                                                   |
| ------------------------- | -------------------------------------------------------------------------------------------------------------------------- | --------------------------------- | -------------------------------- | ------------------------------------------------- |
| **Action**                | **Description**                                                                                                            | **\[Up/Down]stream System**       | **Transfer Description**         | **Frequency**                                     |
| Overall 526 Submission    | The overall submission that establishes the claim                                                                          | EVSS (Lighthouse after migration) | An http call to external service | Always 1 per submission                           |
| Evidence Upload Retrieval | Pulling down the evidence files to submit                                                                                  | AWS S3                            | An http call to external service | Any number per submission, including 0 (optional) |
| Evidence Uploads          | Files provided by the user to support their claim                                                                          | EVSS (Lighthouse after migration) | An http call to external service | Any number per submission, including 0 (optional) |
| Form 4142(a)              | Authorization to Disclose Information to the Department of Veterans Affairs, usually medical records from private sources. | Central Mail                      | An http call to external service | Optional based on provided info                   |
| Form 21-0781(a)           | Statement in Support of Claim for Service Connection for PTSD                                                              | EVSS (Lighthouse after migration) | An http call to external service | Optional based on provided info                   |
| Form 21-8940              | Veteran's Application for Increased Compensation Based on Unemployability                                                  | EVSS (Lighthouse after migration) | An http call to external service | Optional based on provided info                   |
| BDD Instructions          | Pre-discharge claim instructions for claim processor to use for the claim                                                  | EVSS (Lighthouse after migration) | An http call to external service | Optional based on provided info  STATIC document  |
| Flashes                   | Flags or Flashes to set for a veteran on their external VA BGS account                                                     | BGS                               | An http call to external service | Optional based on provided info                   |




### List of possible Discrete Submission Actions - Backup Path

  


|                                       |                                                                                                                                                                                                                                                                   |                                       |                                  |                                                   |
| ------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------- | -------------------------------- | ------------------------------------------------- |
| **Action**                            | **Description**                                                                                                                                                                                                                                                   | **\[Up/Down]stream System**           | **Transfer Description**         | **Frequency**                                     |
| Backup Submission                     | Submission of a single backup payload that is a combination of all of the documents that would have been submitted if the overall submission had been established successfully. Only triggered when the overall submission in the auto-establishment path fails.  | Lighthouse Benefits Claims Intake API | An http call to external service | 1 per submission failure                          |
| Evidence Upload Retrieval             | Pulling down the evidence files to submit                                                                                                                                                                                                                         | AWS S3                                | An http call to external service | Any number per submission, including 0 (optional) |
| Overall 526 Submission PDF Generation | Request for filled out 526 PDF form from veterans information                                                                                                                                                                                                     | EVSS (Lighthouse after migration)     | An http call to external service | 1 per submission failure                          |




### List of Metrics/Data for each action


#### Logged data

- User_uuid

- Action being performed (Form ID or action description)

- Up or Downstream system involved

- If a retriable action

  - Attempt counter
  - If will be retried or if it is the final attempt

- Success or failure status

- Http status from up/downstream service

- Http response body if not a 200 (successful) response 


#### Metrics


##### Incremental

- Success
- Failure
- Total 
- (Or any 2 of the 3 that allow you to arrive at the 3rd)


##### Measures

- duration

**Comment by saderagsdale** [comment]
@kylesoskin why is this blocked?

**Comment by saderagsdale** [comment]
@jaredcunha Take a look at the info above to draw connections to the L&M framework.

**Comment by jaredcunha** [comment]
Adding note for myself. Need to see if this influences what is in the original L&M framework or vice versa

**Comment by kylesoskin** [comment]
Had meeting with Jared and Sade. Awaiting meeting with Steve Albers.

**Comment by saderagsdale** [comment]
Meeting with Steve is complete. This will be transferred to the new team.

**Comment by kylesoskin** [comment]
@saderagsdale I am closing this. It is mostly done, and remaining work is being transisioned to new 526 team and can be represented in new ticket(s) if need be.

**Comment by SamStuckey** [comment]
a few additional notes from kyle about other possible target areas, dumping a link here for posterity
https://dsva.slack.com/archives/C053U7BUT27/p1686836358577259
