### ISSUE TITLE
Collaboration Cycle for [govcio-vfep, GI Bill Comparison Tool, Specialized Mission Filter]

### ISSUE THREAD

**Issue by arianaadili** [department-of-veterans-affairs/va.gov-team#57486]
### VFS team name

govcio-vfep

### Product name

GI Bill Comparison Tool

### Feature name

Specialized Mission Filter

### GitHub label for product

GI Bill Comparison Tool

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

March, 2023

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Tools, applications and dynamic pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Comparison%20Tool%20Enhancements/GI%20Bill%20Comparison%20Tool_Specialized%20Mission%20Filter%20Product%20Product%20Outline_v2.docx

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Notify the Collaboration Cycle team of this ticket in the vfs-platform-support Slack channel.

- [X] I acknowledge that I must notify \#vfs-platform-support after submitting this issue.

Kickoff Slack Thread with VFS team: [Link](https://dsva.slack.com/archives/CBU0KDSB1/p1682530125452249)
</details> 

### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- Navigate to reference link: [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent)
- [x] Schedule your Design Intent when ready:
   - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders 
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [x] Link all artifacts **ONLY** in the Design Intent artifacts section below at least two days before the scheduled Design Intent.  **Do NOT add artifacts to Comments section**
  
**Design Intent artifacts**

See Platform guidance on [Design Intent artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Design Intent meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

- [x] Whiteboard sketch or other lo-fi prototypes or [wireframes](https://sketch.com/s/0b3a5923-3bd3-44e4-9b24-e74428163cae)
- [ ] User flow
- [x] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Comparison%20Tool%20Enhancements/Research_Plan_CT_SMF.md)
- [x] Any other artifacts you have so far
[Design Intent PowerPoint presentation]([va.gov-team/GovCIO-Design Intent_GIBCT-SMF.pptx at master · department-of-veterans-affairs/va.gov-team · GitHub](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepartment-of-veterans-affairs%2Fva.gov-team%2Fblob%2Fmaster%2Fproducts%2FComparison%2520Tool%2520Enhancements%2FGovCIO-Design%2520Intent_GIBCT-SMF.pptx&data=05%7C01%7CAriana.Adili%40govcio.com%7C641799010ad34b0fa67208db531e8df0%7C6499e3f51d3e4f099ad352b9e2f67fb8%7C1%7C0%7C638195162942731984%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=C64%2FwPKKeHUJ929dMBXdxvcl%2BVhj%2FljBjQTOk%2Bqm72E%3D&reserved=0))
  
##### Platform actions
- [x] Design Intent Slack thread with VFS team: [Link](https://dsva.slack.com/archives/CBU0KDSB1/p1682532760497989)
- [x] Meeting date/time: **Friday, May 12 at 11:30am ET**
  
##### Platform actions

- [x] If you have feedback, create feedback tickets and link to this epic. Once you have completed you review, check the box next to your practice area
  - [x] Accessibility has completed the review
  - [x] Design has completed the review
  - [x] IA has completed the review
- [x] Update this ticket with the Zoom recording
  - [Recording URL](https://oddball-io.zoom.us/rec/share/LoOi6bqrUcJgTTiCXVbzVYWrL8J6M9y_Ui9VoT-5fdR5rLr5au7PYXUlW6P7jZ7O.MKXUoq39IGmgudF0 ) 
  - Password: 7v&Ntbs4
  
##### VFS actions

- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Sitewide Content and IA Intake Request
<details>
  <summary>Toggle Sitewide Content and IA Intake Request</summary>

##### VFS actions
- [ ] Complete the [sitewide content and IA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-Content-and-IA-intake-request.2124906551.html)
- [x] Link to the Sitewide Content and IA Intake Request ticket below: https://github.com/department-of-veterans-affairs/va.gov-team/issues/64172 

</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [ ] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [x] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [x] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

Provide links or documents for the following:

- [x] [Finalized design prototype or mockup](https://sketch.com/s/3edef2a8-47eb-456d-bfec-60da90ae51a1) - Sketch page titled: "GIBCT_SMF_'Search by name' tab"
- [x] Specify which pages are included in the review: We only intend to review the following: Comparison Tool homepage > 'Search by name' tab > Institution results page
- [x] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Comparison%20Tool%20Enhancements/research/Research_Plan_CT_SMF.md)
- [x] [Conversation guide
](https://github.com/department-of-veterans-affairs/va.gov-team/blob/99e88d0fdb18a17b8254a585ef2b617071760435/products/Comparison%20Tool%20Enhancements/Conversation_Guide_CT_SMF.md) 

**Content artifacts**
  
- [ ] Your product’s content source of truth 
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)

**IA artifacts**

- [x] Please include a link to any [Sitewide Content & IA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including an IA review document or intake form.
- [Link to IA intake form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64172)
  
##### Platform actions
- [x] Midpoint review Slack thread with VFS team: [Link](https://dsva.slack.com/archives/C04D5FS91BK/p1692821427284109)
- [x] Meeting date/time: 09/01/23 at 11:30 AM ET

##### Platform actions

- [ ] If you have midpoint review feedback, create feedback ticket and link to this epic. Once you have completed your review, check the box next to your practice area
  - [ ] Design has completed the review
  - [x] Accessibility has completed the review
  - [x] IA has completed the review
  - [ ] Content has completed the review
- [X] Update this ticket with the Zoom recording
  - [Midpoint review recording](https://oddball-io.zoom.us/rec/share/M-15GBp924YtVcxzRYkUUvaxWrov3TM1V8-x4xmCby0-jN743FR-xIIOKZExnhnH.8bUN7TDXy5qg63Pw)
  - Passcode: dUu&J2a%
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [ ] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [ ] Link to the Analytics Implementation and QA Request ticket below

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [ ] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [ ] Link to the Contact Center review request ticket below

</details>

### Staging Review
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [x] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [x] I confirm the environment is available <s>and test users have been provided.</s>
- [x] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
 
**Staging Review artifacts**
  
See Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts). Platform findings are based solely on the staging URL and test users provided, as reviewed during the four days before the Staging Review meeting. Any test cases not covered or any ongoing work taking place during the review period may not be reflected in those findings.  

**Product artifacts** 
- [x] [Staging URL](https://staging.va.gov/education/gi-bill-comparison-tool)
- [x] Specify which pages are included in the review: GIBCT homepage, 'search by name' and 'search by location' tabs, institution search results (cards)
- [N/A] Staging test user information         
  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**
- [x] [Github ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65094) for any relevant static content page and entry point updates for tool or feature (if applicable)
  
**IA artifacts**
- [x] [Sitewide Content & IA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64172) 

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [ ] [Regression test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-regression-test-planRegressionTestPlan)
- [x] [Test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-test-planTestPlan)
- [x] [Coverage for References](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [x] [Summary(Defects) reports](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [x] [E2E tests] [Unit Test Coverage Report](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report/)
- [x] [Code coverage] [Unit Test Coverage Report](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report/)
*Displaying the current percentages of code coverage as of 2/5/2024:*<img width="883" alt="Screenshot 2024-02-05 at 1 58 58 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/119622092/7fd804a9-c34f-4187-ac6e-58ea0452136b">

*Our test engineer has documented the following tests in a single [Word document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Comparison%20Tool%20Enhancements/VFEP%20SMF%20UAT%20Feb5.docx) (download raw file):*
- Test plan
- Coverage for references
- Summary (defects) reports

**Accessibility artifacts**
  
- [x] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75292)
  
##### Platform actions
- [x] Staging review Slack thread with VFS team: [Slack thread](https://dsva.slack.com/archives/C04D5FS91BK/p1706298536255659)
- [x] Meeting date/time: **Tuesday, February 13, 2024 at 11:30AM ET**

##### Platform actions

- [x] Update this ticket with the Zoom recording
  - [Staging review meeting recording](https://oddball-io.zoom.us/rec/share/fDkU3someEJB5nRo7heB5wq-dsZNCRa9s_05jE__iBbP3deVw47X9lq0CAEkYMcR.ALA9eEY_ovMsYHrM)
  - Password: `A?tL57vt`
  
##### VFS actions
  
- [x] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [x] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [x] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [x] Share ServiceNow ticket number here: REQ24038615
- [x] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [ ] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [ ] Link to the Readiness Review ticket below

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by sara-amanda** [comment]
Added link to CAIA ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/64172

**Comment by arianaadili** [comment]
Hello, I edited this ticket under the midpoint review toggle in order to correct the link to our research plan as we made a small update to it. I'm not sure if it was necessary for me to make this update but wanted to provide an explanation here just in case.

**Comment by arianaadili** [comment]
A PSIR review isn't necessary for this product as it's merely an update to a static page. All other tasks, including the submission of a 508 audit request, have been addressed.
