### ISSUE TITLE
Profile: Sprint 10 (5.10.23 - 5.23.23) Epic

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#57497]
## Sprint 9 Retro
EasyRetro Board ([link](https://easyretro.io/board/f4051524-d7be-43a4-8c50-f43d887f3a7f/ee28bd88-bc5e-449e-bfa2-c434a31e5693))

## Sprint 10 Notes
Sprint 10 epic will be finalized at Sprint Planning -- [see project outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/sprint-objectives/profile/sprints-1-10-Jan23-May23.md#sprint-10-510---523) for more info

## 2023 Priorities for Authenticated Experience
<details> 
<summary>2023 Priorities Breakdown</summary>

**High**: 
Migrating MyHealtheVet into VA.gov; 
expanding notification functionality (both onsite and preferences); 
improving the logged-in nav/IA/experience overall; urgent/required maintenance for a feature; unplanned work that aligns with OCTO high-priority objectives

**Low**: 
improvements team wants to make but might fall outside of OCTO objectives
To complete: some initiatives that we should finish but don't fall under OCTO high-priority objectives
</details>

## Q2 CY2023 (Apr-Jun) Product Goals
More details found at [Q2 CY2023 Product Roadmap](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/roadmap/2023-goals-roadmap.md#q2-cy2023-april---june)

## PTO
- None scheduled

## Sprint 10 Goals
_At the end of this sprint, what do we want to have accomplished/delivered?_

**Direct deposit migration EVSS > Lighthouse:**
Prepare for QA/ integration testing in Staging 
 

**Notification preferences:** 
- Assuming technical discovery happened last sprint, PM to scope out work for both default send indicator and adding email as a channel. Please account for required collab cycle milestones.
- FE/BE work dependent on technical discovery for both default send indicator and adding email as a channel.
Design: When new mobile phone number flow is launched in production, update documentation (ticket already exists).

**Logged-in IA/nav research:** 
- Begin exploration outlined in #58463

## Carry over (modify points in Sprint Planning)
- [ ] Remove Email change toggle #54082 (2 pts)  ~~< currently blocked, may be able to clear this after some testing on 5/11/2023 w Tom and Travis~~  <this is ready to go to prod
- [x] #55658 this is now unblocked < travis and adam to test 5/23
- [ ] #54870 < blocked 5/17/2023
- [x] #57359 very small rollover - ~3-4 to roll over
- [x] #57407 1ish point left < travis and adam testing 5/23/2023

##  Direct deposit migration EVSS > Lighthouse (Epic #51900)
- [ ] Integration testing #54771  <continuing in sprint 11
- [ ] [FE] Complete Analytics work #54893 <continuing in sprint 11
- [x] [BE Carry Over?] #57357

## Notification preferences
- [x] #57820 < design intent scheduled 5/25
- [x] #56397  < design intent completed 5/18
- [ ] ~~#57408 (3pts)~~ this was moved back to the backlog 
- [x] #53547 < in validate 5/18

## Logged-in IA/nav research (Epic #51519)
- [x] #58463

## General / Other

- [ ] ~~#48566 for our new joiner~~ move out to sprint 12
- [x] #54045  < this was well received at the design intent review, i think next steps are to create more tickets for adam to build out on the FE 
- [x] #58108
- [x] #58111
- [ ] #47666 < in progress
- [ ] #55398  ~~<quick fix to clean up our GA data~~  < moving to sprint 11

---
I feel like the things sandwiched here should potentially push to the next sprint but I'm not confident on this 
---
- [ ] ~~API Improvements (Epic #54241) - Depending on time ( #54238 <sprint11  #54237 <sprint10? #52628 <sprint10?)~~ <for these Tom is going to pick them up in sprint 11 or 12. 
- [ ] ~~Telemetry & monitoring (Epic #55009) - Need tickets~~
---

## Unplanned Work
- For this sprint -- allot 2-3 points for unplanned work 
- [x] #58286 
- [x] #58205

**Comment by BerniXiongA6** [comment]
@andaleliz will take this on in Sprint 11 @mtcA6

**Comment by mtcA6** [comment]
@BerniXiongA6 what is this in this context?

**Comment by BerniXiongA6** [comment]
My bad @mtcA6 I had two screens open and wrote the comment in the wrong issue. Disregard. I'll write the comment in the correct ticket that @andaleliz brought up in Stand Up today. Thanks for following up!
