### ISSUE TITLE
Bug - Discovery - Form 21-0781a Issue on event desc field length

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#57510]
## Issue Description
We were notified of an issue from field users with VA.gov generated 21-0781a forms, which appear to be cutting off entries in the 8E box (description of the event).  It looks like the online form allows claimants to enter in text in this section without limiting characters, however – when the form is completed, it flattens out and any text beyond the character limit is cut off.  Military Sexual Trauma coordinators are having a hard time with this as it is a sensitive subject and requires them contacting the Veteran to determine what part of the experience has been left off the online form.

They provided the following claim IDs as examples.

Claim IDs: 94172674, 93731295

Reporter -  Alejandro Mendiolaflores
---
## Tasks
- [x] Identify the form field for 8E - check with Lydia - 
- [x] Identify contacts for pdf generation team
- [x] Look at the form field for limit on the field
- [x] Validation or sanitation done on the input
- [x] Is the pdf creation trimming the text

## Acceptance Criteria
- [x] What is the current limit on the text field in 526
- [x] What is being sent to the downstream application for pdf generation
- [ ] Discussion with stakeholders on what is the desired outcome
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lydiahooper** [comment]
![Screen Shot 2023-02-14 at 11.08.37 AM.png](https://images.zenhubusercontent.com/63dd30c43859c04de31f7608/317dd26d-8b61-4015-8454-b6c9bde27fa7)

**Comment by micahaspyr** [comment]
- Backend: Does not limit the number of characters for the form field itself
   - No validation of input
- Frontend: No max character length is enforced or exists
   - None seen BUT this need more discovery to double check 

Preliminarily this looks to be pointing to the PDF generation step through the sidekiq background job.  Next will speak with someone familiar with the PDF generation job

**Comment by micahaspyr** [comment]
After talking with Kyle Soskin it looks like the PDF generation doesn't erroneously cut off any characters, even with 10,000 characters.   The claims trauma description references provided are less than 10,000 characters.  Still tracking this one down....

**Comment by micahaspyr** [comment]
- There is no current limit on the text area field 
- It does not appear that anything unusual is happening as what is seen in the DB is what is being sent to the pdf creation job via the "form_data" attribute

**Comment by austinjprice** [comment]
Need to review how downstream (VBMS) system handles this data downstream - contact Alejandro SME to determine if there is a restriction there.

**Comment by micahaspyr** [comment]
@austinjprice @tblackwe I emailed Alejandro concerning this bug asking for some more info.  I think we need to set up a meeting with Alejandro to further discuss this problem.

**Comment by RakshindaAslam** [comment]
@austinjprice @micahaspyr @tblackwe - this would be a good candidate for the biweekly VBA stakeholder meeting with Alejandro.

**Comment by micahaspyr** [comment]
@tblackwe, @austinjprice, and myself met with Alejandro today.   He shared the bad PDF with us which shed more of a light on where to look. This issue looks to be on the PDF generation side of the submission that cuts off text in the form input that is on the actual PDF, which has nothing to do with the text saved via the 526 form. Running through the code and testing again

**Comment by RakshindaAslam** [comment]
@micahaspyr @tblackwe - Can we reach out to the pdf generation team in evss/LH to make sure they put the fix on their backlog?

**Comment by micahaspyr** [comment]
@RakshindaAslam that was not really a fix and doesn't have any impact on the bug.  Alejandro mentioned the number characters in the "Event Description" field was around 5,000 and the pdf showed a portion of that.  Alejandro said that items that are too big for fields when transferred to the PDF form should move into the "additional info pages".  After testing pdf generation multiple times, it looks like the issue may have been fixed/corrected.  Providing my latest example.  You can see the "Description of Event" (which I highlighted yellow) on page 4 was added because the text overflowed the 8E field. [https://app.zenhub.com/files/133843125/b15e5f4d-c9a0-4da7-a680-eedc07a0f532/download](https://app.zenhub.com/files/133843125/b15e5f4d-c9a0-4da7-a680-eedc07a0f532/download)

But to answer part of your question, I think it would be best to talk a bit with the PDF generation team.  I've talked to Kyle since he wrote some of the code.  I do think we should now talk to EVSS to see if this was something they have already addressed.  

Does anyone know who we should talk to?

**Comment by austinjprice** [comment]
thanks @micahaspyr - I do wonder if there is a way to identify inProgress forms that have this field filled out, are over a certain length and didnt flow over to the 8E field and then reprocess?
