### ISSUE TITLE
Board Appeal Discovery | talk to SMEs, brief the team

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#57522]
## Value Statement
**_As a_** team
**_We want to_** talk to SMEs
**_So that_** we can align on background, goals, and next steps for the Board Appeals form.

---
## Background Context
The Request for Board Appeal form was released in April 2022 and is overdue for a post-launch review of the feature. The scope of this evaluative discovery includes reviewing qualitative and quantitative data, redefining product outcomes, and identifying opportunities for improvement and ways to measure the impact of our work on the form.

## Acceptance Criteria
- [x] Have a clear and shareable understanding of the current state of the digital board appeals form
- [x] Have business input on problem areas throughout the NoD service
- [x] Have VFS team input on existing or ongoing research, known limitations of NoD service
- [x] Have a shareable service blueprint that captures points of friction/opportunity
- [x] Have team alignment on goals, gaps, and next steps for the digital board appeals form.

## Designs and Build Notes
- [Research strategy + Open questions](https://docs.google.com/document/d/1vHDnIHV2LTgjMRpYWYpXYjG0J9NkXuEacYVlqZjKJtU/edit#)

## Out of scope
- Add here

## Open questions
SME Q's
- What are the most common issues you see with this type of decision review that cause the backlog to build?
- Does the type of hearing selected have a significant impact on the outcome of the decision? 
- Are there use cases when it is better or worse to choose a certain hearing type?
- Do SME's such as Quality Control have documented points of friction?
- What is the notify team providing along the journey/doing for incomplete forms?
- Are there other SME's we should hear from prior to the Veteran facing evaluation?
- Does the VSO submit through a separate system? assuming yes. (Ask Kyle if there is a marker for VSO submissions?)
- How many Veterans choose to manually send evidence than uploading immediately?
- How many Veterans still choose to select hearing type with 10,000 people
- How many use informal conference?
- What use cases outside of disability compensation is NoD being used for?

## Tasks
- [x] Kick of research with stakeholders and ID SMEs
- [x] Chat with Board Appeal SMEs
- [x] Interview intake team
- [x] Chat with the VANotify team
- [x] Chat with the content team
- [x] Chat with Lighthouse researcher (Melinda Cuerda)
- [x] Compile information in the Decision Review knowledge base
- [x] Create service blueprint, mapping out findings
- [x] Draft baseline success metrics for the form
- [x] Share with team

**Comment by saderagsdale** [comment]
Reached out to John Gosnell again and asked Matt to nudge him.

**Comment by HeatherWidmont** [comment]
Eileen & Sade have a meeting set up next Wednesday to talk about a different strategy with SME discussions to be more impactful

**Comment by HeatherWidmont** [comment]
Sade to talk to Matt Self about how much Octo & Board of Appeals are aligned. She will discuss this & how we work with the Content team with Matt in today's Product Sync.

**Comment by saderagsdale** [comment]
Moving to the sprint backlog since our sprint focus is Veteran Interviews. If this is part of the sprint goal we can move it back in.
