### ISSUE TITLE
Request Analytics review and setup for new landing pages 

### ISSUE THREAD

**Issue by Nyanteea** [department-of-veterans-affairs/va.gov-team#57526]
Blocked by IA team giving us the new URLs - pending the new URLs in production

## Issue Description

As a part of the platform cycle, they may recommend[ setting up special analytics tracking](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/analytics-request) for changes to the product through platform analytics by creating a ticket. Or you could do so voluntarily. 

Landing page developments (start, introduction, etc.) may require new tags in addition to the funnel change requests. Platform analytics will let us know what to track and whether that will allow us to measure OKRs. 

Blocked by a ticket to the IA team
---
## Tasks
- [ ] Discuss and establish OKRs specific to this work 
- [ ] [Submit ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review%2C+gtm&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D)

## Acceptance Criteria
- [ ]  Request submitted to Platform Analytics 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Nyanteea** [comment]
@RakshindaAslam

**Comment by Nyanteea** [comment]
[List of current form URLs](https://docs.google.com/spreadsheets/d/1gRmJqZvzRKSgoz8BzAxULRfRHegVrAOV6ciZU3fVWq0/edit#gid=0) (have not yet been checked for accuracy)

**Comment by lydiahooper** [comment]
@RakshindaAslam can you take this on once we're ready for this?

**Comment by RakshindaAslam** [comment]
I am not quite sure what needs to be done on this. @christinec-fftc - do you know anything about this ticket?

**Comment by lydiahooper** [comment]
This is a ticket for when we get to staging review for revised intro pages, to make sure we notify analytics about URL changes
