### ISSUE TITLE
Flaky e2e test - long-ptsd.cypress.spec.js

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#57528]
This test is showing up on the flaky tests report and has been auto disabled. Investigate root cause and put in a fix to make this test reliable.

![image.png](https://images.zenhubusercontent.com/641341411444ec27c3eb60a4/ea54dd21-0a69-4497-80ad-92408e59463e)

[report](https://depo-platform-documentation.scrollhelp.site/developer-docs/currently-disallowed-cypress-test-specs-on-va-gov)

[documentation](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/57527#:~:text=report-,documentation,-Dependencies)

Risk of not doing this investigation is that we won't know if there is a defect in the application.

## Task
- [x] Understand what is being tested
- [x] Manually test
- [ ] Determine if the test is useful or should be removed
- [ ] Provide fix (application / test)

## Acceptance Criteria
- [ ] Fix committed for the bug
- [ ] Test is re-enabled and reliably passes (i.e. no longer on the flaky report)

**Comment by SamStuckey** [comment]
Not much here so far, but I've started this doc attempting to identify patterns in CI that I can use as research threads.  https://docs.google.com/document/d/1ktVaYWUxAZsG_8VbEtIcabXU_Qek0k3qKh2hu_63GV8/edit#heading=h.n1myaasjjc15
