### ISSUE TITLE
Flaky e2e test - all-claims-keyboard-only.cypress.spec.js

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#57527]
This keyboard test is showing up on the flaky tests report and has been auto disabled. Investigate root cause and put in a fix to make this test reliable.
![image.png](https://images.zenhubusercontent.com/641341411444ec27c3eb60a4/36bb0375-4949-422c-a8c3-a29a16edab81)

[report](https://depo-platform-documentation.scrollhelp.site/developer-docs/currently-disallowed-cypress-test-specs-on-va-gov)

[documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/flaky-test-management-in-cypress)

## Task
- [x] Understand what is being tested
- [x] Manually test
- [x] Determine if the test is useful or should be removed
- [ ] Provide fix (application / test)

## Acceptance Criteria
- [ ] Fix committed for the bug
- [ ] Test is re-enabled and reliably passes (i.e. no longer on the flaky report)

**Comment by tblackwe** [comment]
Test is to fully fill out 526EZ form using only keyboard navigation

Helper Library [cypress-real-events](https://github.com/dmtrKovalenko/cypress-real-events) used to aid with creating tests. 

The command `cy.realPress('Enter');` works for some buttons, but not all. researching to determine what can be done to resolve issue.
Passes by replacing `realPress` with `.type('Cypress.io{enter}')` but that doesnt explain why it stopped working.

**Comment by tblackwe** [comment]
something is causing the first realPress to be ignored. Can proceed with the test by repeating the input. 

`cy.tabToElement('#2-continueButton');
cy.realPress('Enter');
cy.tabToElement('#2-continueButton');
cy.realPress('Enter');`

**Comment by tblackwe** [comment]
Manual test passes in staging and local development 
Manual test fails when in the cypress managed chrome instance, also fails to click the button

This makes me think there is an issue with the way the test data is arranged, but I'm not seeing the issue yet.

**Comment by tblackwe** [comment]
Working with Robin Garrison, the issue has been found in RoutedSavableApp


![continue-button.gif](https://images.zenhubusercontent.com/64593ab7d485a96347136073/72755349-5e84-4a9f-8f79-059c4c491a7d)
> when the veteran info page appears, the loadedStatus is set to success and when that happens this code makes the router replace the URL with the save-in-progress returnUrl which happens to be the /veteran-information path

 `    } else if (status === LOAD_STATUSES.success) {
      if (newProps.formConfig.onFormLoaded) {
        // The onFormLoaded callback should handle navigating to the start of the form
        newProps.formConfig.onFormLoaded(newProps);
      } else {
        newProps.router.push(newProps.returnUrl);
      }`

This is an issue in the platform code and isn't owned by our team.
