### ISSUE TITLE
Update content on TOE static page and in tool to clarify whose login to use

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#57537]
## Issue Description

Tammy let us know that there's been some confusion with the TOE online form and which login to use. The login should be the person who is getting the transferred benefits. If the person doing the transferring uses their own login, the form will pull their SSN instead of the person getting the benefits. 

We need to add content on the [static page](https://www.va.gov/education/survivor-dependent-benefits/transferred-benefits/) to make this clear as well as work with Tammy to provide plain language content for her team to add to the form. 

## Tasks
- [x] Update content on static page (Katherine)
- [x] Provide content to Tammy (Katherine)
- [x] Review (Beth)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Static page is live with changes
- [ ] Product team has final content for tool update

**Comment by katherine-fung** [comment]
Hi @bethpottsVADEPO, 

I've updated the static page and the about form page. I've also included suggested copy for the form intro page, and the tool itself. 

**1. Static page:** 
http://preview-prod.vfs.va.gov/preview?nodeId=44698 

**2. About form page:** 
http://preview-prod.vfs.va.gov/preview?nodeId=5863 

**3. For the form intro page, I suggest this copy to replace the note that's currently at the top of the page:** 

https://www.va.gov/education/survivor-dependent-benefits/apply-for-transferred-benefits-form-22-1990e/introduction

**Note:** You can only sign in and complete the application if you're the dependent of a Veteran or service member who transferred Post-9/11 GI Bill benefits to you. We can't process the application if the Veteran or service member signs in and completes the application for you. 
![Screenshot (138).png](https://images.zenhubusercontent.com/627bd98be9182e080ddd515b/377d4cfc-882d-4cad-bdc6-05a51732f77b)

**4. In the form itself, I suggest adding this copy to the screen showing the first step:** 

You must be signed in to your own Login.gov or ID.me account to complete this application. We can't process the application if the Veteran or service member is signed in. 

![Screenshot (139).png](https://images.zenhubusercontent.com/627bd98be9182e080ddd515b/072293ea-1d53-4e00-aab8-bde5af6616c6)

**Comment by bethpottsVADEPO** [comment]
@katherine-fung  Thanks for your work on this! Here are my thoughts:

1. Static page (note that for the second sentence, I bolded my edits just to show you where I edited--don't use bolding for the final text):
Be sure you're signed in as a family member to your own Login.gov or ID.me account to complete this application. We can't process **your** application if the Veteran or service member signs in **to their account** and **submits** the application for you. 

2. About form page:
**Note:** If you choose to use our online tool to apply, be sure you're signed in as a family member to your own Login.gov or ID.me account to complete this application. We can't process **your** application if the Veteran or service member signs in **to their account** and **submits** the application for you. 

3. For the form intro page (thank you for recognizing that this note needed some rephrasing):
**Note:** Use this application if you're the dependent of a Veteran or service member who transferred Post-9/11 GI Bill benefits to you. Be sure you're signed in as a family member to your own Login.gov or ID.me account to complete this application. We can't process your application if the Veteran or service member signs in to their account and submits the application for you. 

4. In the form itself--can you show me the context here on a quick call? We may want to leave that existing note there...

**Comment by katherine-fung** [comment]
Hi @megzehn, 

We made changes to 2 pages for this ticket. They're ready for copy edit. 

I'm linking to the inline revisions in case it's easier to review the changes that way: 

**Transferred education benefits for family members**
https://prod.cms.va.gov/node/44698/revisions/view/752449/771832/visual_inline

**About VA Form 22-1990e**
https://prod.cms.va.gov/node/5863/revisions/view/758946/771833/visual_inline

Let me know if you have any questions. Thank you!!

**Comment by megzehn** [comment]
Confirming I copy edited and published these pages. Thanks, @katherine-fung!

**Comment by RLHecht** [comment]
These changes are live. Closing ticket.
