### ISSUE TITLE
Draft artboards names using new structure

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#57557]
## Description 

Artboard naming strucuture idenitifed in the mural in this ticket - https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/56179

Now, need to apply the structure. 

## Tasks

- [ ] Write names for 12-15 artboards using new structure
- [ ] Share and get feedback from UX team 

## AC

- [ ] UX team agrees with the 12-15 artboard names

**Comment by loripusey** [comment]
@benbrasso-agile6 is this ticket done? ready to close?

**Comment by benbrasso-agile6** [comment]
We pulled this in during the sprint. Need to carryover.

**Comment by kellysmith1008** [comment]
@ytsaoca  I went in and updated quite a few of the pre visit artboards - I'm not able to view the mural anymore (same as you from last Friday) so I used what I vaguely remembered to be true as the naming convention: Visit type (pre visit or echeck in) > Primary action > Sub action > Extra information. So for example, the login screen I labeled: Pre visit > Log in. For demographics, I used: Pre visit > Review demographics > contact information verification. Please let me know if this isn't what you envisioned and I can change them :)

**Comment by ytsaoca** [comment]
@kellysmith1008  Did you directly change the naming on Sketch? If yes, which page did you work on?
Also, if you've decided the Primary actions and Sub actions, could you list them down so that I can have a better understanding of your structure? Thanks

**Comment by ytsaoca** [comment]
@kellysmith1008  Did you directly change the naming on Sketch? If yes, which page did you work on?
Also, if you've decided the Primary actions and Sub actions, could you list them down so that I can have a better understanding of your structure? Thanks

**Comment by kellysmith1008** [comment]
@ytsaoca and I met today to agree on naming conventions. We have a plan moving forward and will share the naming of the new artboards at our UX sync on Tuesday, and then we can stub out a ticket in an upcoming sprint to rename the rest of them.
