### ISSUE TITLE
Edit text messages based on VA Notify feedback

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#57562]
## Description 

Received feedback from VA Notify team on our text messages - https://github.com/department-of-veterans-affairs/va.gov-team/issues/55526#issuecomment-1525802043

## Tasks

- [ ] Draft edits based on feedback 
- [ ] Create [intake ticket for CAIA review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=RLHecht%2C+coforma-terry&labels=sitewide+CAIA%2C+sitewide+content-product+support%2C+Sitewide+IA%2C+sitewide+content&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E) 
- [ ] Review with privacy officer (per feedback) (although, not clear who to go to) 
- [ ] Update [mural work flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677531124203/5edcfd3ea4b1eaf1ef082d56782a8b3291ef3932?sender=u37bb983bd3fc3cc00c7d3286) with text messages
- [ ] Resubmit to [VA Notify team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55526#issuecomment-1525802043) 

## AC

- [ ] CAIA provided feedback
- [ ] Privacy officer approval
- [ ] Updated in [mural work flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677531124203/5edcfd3ea4b1eaf1ef082d56782a8b3291ef3932?sender=u37bb983bd3fc3cc00c7d3286)
- [ ] Resubmitted to [VA Notify team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55526#issuecomment-1525802043)

**Comment by loripusey** [comment]
I added this to our current sprint goals.

**Comment by kellysmith1008** [comment]
Seems git created multiple versions of this ticket - we're going to close the duplicates and keep everything in [57560](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57560)
