### ISSUE TITLE
Edit error text messages based on VA Notify feedback

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#57561]
## Description 

Received feedback from VA Notify team on our text messages - https://github.com/department-of-veterans-affairs/va.gov-team/issues/55526#issuecomment-1525802043

## Tasks

- [ ] Draft edits based on feedback 
- [ ] Create [intake ticket for CAIA review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=RLHecht%2C+coforma-terry&labels=sitewide+CAIA%2C+sitewide+content-product+support%2C+Sitewide+IA%2C+sitewide+content&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E) 
- [ ] Review with privacy officer (per feedback) (although, not clear who to go to) 
- [ ] Update [mural work flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677531124203/5edcfd3ea4b1eaf1ef082d56782a8b3291ef3932?sender=u37bb983bd3fc3cc00c7d3286) with text messages
- [ ] Resubmit to [VA Notify team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55526#issuecomment-1525802043) 

## AC

- [ ] CAIA provided feedback
- [ ] Privacy officer approval
- [ ] Updated in [mural work flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677531124203/5edcfd3ea4b1eaf1ef082d56782a8b3291ef3932?sender=u37bb983bd3fc3cc00c7d3286)
- [ ] Resubmitted to [VA Notify team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55526#issuecomment-1525802043)

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 @loripusey 
Here's the proposed text from 55526: Error (may change depending on the answer to my question about manual review):
We're sorry, something went wrong with your travel reimbursement claim. Please try again within 30 days of your appointment, https://www.va.gov/resources/how-to-file-a-va-travel-reimbursement-claim-online/
This is 205 characters.

Given the 160 character limit, I propose:
"We’re sorry, we can’t file your claim now. File your claim within 30 days at https://www.va.gov/resources/how-to-file-a-va-travel-reimbursement-claim-online."
That is 157 characters. The problem with that is there's no way we could include the date and fall within the 160 character limit, unless we could shorten that url, which is responsible for 80 characters.

**Comment by kellysmith1008** [comment]
Seems git created multiple versions of this ticket - we're going to close the duplicates and keep everything in [57560](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57560)
