### ISSUE TITLE
Analyze analogous services like Real ID

### ISSUE THREAD

**Issue by tygindraux** [department-of-veterans-affairs/va.gov-team#57578]
## Description
We want to do comparative analysis of similar services like Real ID, USPS Pilot and TSA identity proofing in order to:
- understand how others solve this problem
- understand how we might solve this problem and narrow our focus

## Acceptance criteria
- [ ] Journey map created for 1-2 services

## Tasks
- [x] @skirkman16 map USPS process (and questions)
- [x] @skirkman16 map Real ID process (and questions)

**Comment by tygindraux** [comment]
Anthony and I were on a call today with Carrie from Login.gov/IPP. Here are my [meeting notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/products/in-person%20support/meeting%20notes/05-02-2023.md) if they're useful to review as you work through the review of analogous services @skirkman16.
