### ISSUE TITLE
Publishing new past education rates pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#57582]
## Issue Description

Once the new past education rates for 2020-21 are copyedited and approved for publishing, we need to set up the menu items and adjust the urls of the 2021-22 past rates pages. 

URLS for new past rates pages:
/education/benefit-rates/post-9-11-gi-bill-rates/past-rates-2020-2021/
/education/benefit-rates/montgomery-active-duty-rates/past-rates-2020-2021/
/education/benefit-rates/montgomery-selected-reserve-rates/past-rates-2020-2021/
/education/benefit-rates/fry-scholarship/past-rates-2020-2021/
/education/benefit-rates/chapter-35-rates/past-rates-2020-2021/

URLS for already live past rates pages:
/education/benefit-rates/post-9-11-gi-bill-rates/past-rates-2021-2022/
/education/benefit-rates/montgomery-active-duty-rates/past-rates-2021-2022/
/education/benefit-rates/montgomery-selected-reserve-rates/past-rates-2021-2022/
/education/benefit-rates/fry-scholarship/past-rates-2021-2022/
/education/benefit-rates/chapter-35-rates/past-rates-2021-2022/

Left nav:
Display each past rates section as
Past rates: 2021-2022
Past rates: 2020-2021

## Tasks

**Post-9/11 GI Bill page**
- [x] Publish 2020-21 past rates page
- [x] Set up left nav 
- [x] Publish current rates page
- [x] Change url of more recent past rates page and publish

**Montgomery Active Duty page**
- [x] Publish 2020-21 past rates page
- [x] Set up left nav 
- [x] Publish current rates page
- [x] Change url of more recent past rates page and publish

**Montgomery Selected Reserve page**
- [x] Publish 2020-21 past rates page
- [x] Set up left nav 
- [x] Publish current rates page
- [x] Change url of more recent past rates page and publish

**Fry Scholarship page**
- [x] Publish 2020-21 past rates page
- [x] Set up left nav 
- [x] Publish current rates page
- [x] Change url of more recent past rates page and publish

**Chapter 35 page**
- [x] Publish 2020-21 past rates page
- [x] Set up left nav 
- [x] Publish current rates page
- [x] Change url of more recent past rates page and publish

## Acceptance Criteria
- [x] Past rates are live and showing in the left nav

**Comment by megzehn** [comment]
Hi @RLHecht! I finished reviewing and publishing these pages, so they're ready for you again. Thank you for setting them up!

**Comment by RLHecht** [comment]
I validated that these are all live. Closing!
