### ISSUE TITLE
[eFSR] Accessibility Testing - Color and color contrast

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#57589]
## Issue Description
From [Issue: Accessibility Testing
](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D)

Color must not be the only way information is communicated, and all elements must have sufficient contrast against the page background and neighboring elements. Multiple tools exist for testing use of color and color contrast, but we recommend checking color pairings with [WhoCanUse](https://www.whocanuse.com/) and reviewing your product with the [Colorblindly extension for Google Chrome](https://chrome.google.com/webstore/detail/colorblindly/floniaahmccleoclneebhhmnjgdfijgg).

We recommend that designers make accessible color choices before any code is written, and then double-check colors prior to staging review.

[Learn more about testing for color and color contrast](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review#Prepareforanaccessibilitystagingreview-Useofcolorandcolorcontrastuse-of-color) or [watch a color and color contrast testing demo](https://www.youtube.com/watch?v=ReLtfiZlSCo).

---
## Tasks
**Use of color and color contrast checks**
- [x] All text of 20px or smaller has a 4.5:1 contrast ratio to its background (or better)
- [x] All text of 20px or larger has a 3:1 contrast ratio to its background (or better)
- [x] Non-text elements have a 3:1 contrast ratio to their background and to neighboring elements (or better)
- [x] Color is not the only way to distinguish links from other text (eg. links are underlined)
- [x] Any charts, maps, infographics, and tables convey all information without only relying on color
- [x] Content does not refer to color, especially when providing user instructions (eg. "Click the blue button")

## Acceptance Criteria
- [x] Ensure the FSR passes the following tests
- [x] Document any issues and create tickets to fix any problems

**Comment by josephrlee** [comment]
The new Delete button fails the [contrast ratio on hover](https://www.whocanuse.com/?bg=f9dede&fg=cd2026&fs=16&fw=).

![Screenshot 2023-05-26 at 3.26.10 PM.png](https://images.zenhubusercontent.com/63ea96045c6deec1c9a25425/263691e1-c1c1-4f54-ab2c-a7a7bf4ad65f)

![Screenshot 2023-05-26 at 3.26.47 PM.png](https://images.zenhubusercontent.com/63ea96045c6deec1c9a25425/cd20fe9d-4e14-4b9f-992b-3c72ede02b28)

**Comment by josephrlee** [comment]
This is all done, just created an [issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59517) and [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/24409) to fix it!
