### ISSUE TITLE
[ANALYTICS] Research and determine COATESVILLE, PA - Caregiver information for all Health Service Programs [ANALYTICS]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#5758]
## User Story or Problem Statement
As a Veteran web user, I need to know the Care Giver contact information and specific details, so I can quickly reach my health service goals and programs requested. 

## Goal
_Compile all the Contact Data and related Health Service data required to build a clear Health Service Program page for each of the below programs at a Medical System Level._

## Objectives or Key Results this is meant to further
- _Reduce click through count_
- _Document pages that can be created in a scalable manner_

## Resources - Tools - Documentation
[Caregiver_Info_SpreadSheet](https://drive.google.com/drive/folders/1_rMzWOrogXW4g0YazOB1e2U8FuZIAvLY)
[Coatesville Legacy Web Page](www.coatesville.va.gov)
[National Caregiver Listing](https://www.caregiver.va.gov/support/New_CSC_Page.asp)

## Tasks
_Compile Care Giver information and Service provided (Bullet points) for all of the following:_
_Health Service Programs:_
- [ ] Caregiver Support
- [ ] Homeless-Veteran-Care
- [ ] LGBT-Veteran-Care
- [ ] Mental-Health-Care
- [ ] Minority-Veteran-Care
- [ ] Patient-Advocates
- [ ] Returning-Service-Member-care
- [ ] Suicide-Prevention
- [ ] Women-Veteran-Care

## Acceptance Criteria
_Confirm all have been reviewed and updated in the Caregiver Information spreadsheet "See Resources Above"_
* Caregiver Support
* Homeless-Veteran-Care
* LGBT-Veteran-Care
* Mental-Health-Care
* Minority-Veteran-Care
* Patient-Advocates
* Returning-Service-Member-care
* Suicide-Prevention
* Women-Veteran-Care
