### ISSUE TITLE
[eFSR] Accessibility Testing - Content zoom and reflow

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#57600]
## Issue Description
From [Issue: Accessibility Testing
](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D)

All page elements must be readable and usable at 200%, 300%, and 400% zoom. That means:

No functionality has been hidden or removed from the page. (Example: a button that is visible on desktop but hidden on a mobile device will likely be hidden at high zoom.)
Nothing overlaps. (Example: text getting covered up by other elements.)
No horizontal scrolling. (Exceptions: data tables, charts, and images.)
To test content zoom and resizing, set your browser width to 1280 pixels and use Ctrl + or Cmd + to zoom in to 200%, 300%, and 400%.

We recommend that designers think about how content will resize and reflow in high-zoom situations prior to handing off to engineers. High-fidelity prototypes at high zoom aren't required, but designers may want to create low-fi wireframes for complex page layouts. Once coded, content zoom and reflow should be tested prior to staging review.

[Learn more about testing content zoom and reflow](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review#Prepareforanaccessibilitystagingreview-Contentzoomandreflowcontent-zoom) or [watch a content zoom and resizing demo](https://www.youtube.com/watch?v=cO6wJK2Mp5U).

---
## Tasks
**Content zoom and reflow checks**
- [x]  All page elements are readable and usable at 200% zoom
- [x]   All page elements are readable and usable at 300% zoom
- [x]   All page elements are readable and usable at 400% zoom

## Acceptance Criteria
- [x] Ensure the FSR passes the following tests
- [x] Document any issues and create tickets to fix any problems

**Comment by josephrlee** [comment]
At 400% zoom, the radio button options are unreadable because there's a hard 320px width applied to the component. ![Screenshot 2023-05-26 at 2.13.09 PM.png](https://images.zenhubusercontent.com/63ea96045c6deec1c9a25425/a3541442-c910-4897-a7fe-5a2c008c35e9)

**Comment by josephrlee** [comment]
On the **dependents question** the input is too wide from 300% on up.  
`.dependent-count label, .dependent-count .usa-input-error-message {
    width: 32em;
}`

`_b-variables.scss` seems to be the issue since `width` is being applied as a fixed value from the variable. 

![Screenshot 2023-05-26 at 2.28.48 PM.png](https://images.zenhubusercontent.com/63ea96045c6deec1c9a25425/26e16ffd-5bac-4fc6-bc31-4475f066e79a)

**Comment by josephrlee** [comment]
The currency label isn't showing on **Extended Monthly Payments** resolution option. ![Screenshot 2023-05-26 at 2.38.02 PM.png](https://images.zenhubusercontent.com/63ea96045c6deec1c9a25425/ec3aa1bf-8332-452a-a419-7dddfcb845ef)

**Comment by josephrlee** [comment]
The review page is missing $ next to the amount.
![Screenshot 2023-05-26 at 2.40.57 PM.png](https://images.zenhubusercontent.com/63ea96045c6deec1c9a25425/b4b3fb60-6e46-4070-b3e7-579dd6c68e21)

**Comment by josephrlee** [comment]
The dependents amount field is also broken on the **review page** because of the same width issue, which makes sense since it pulls from the same component view. Fixing the component will fix the issue in both places.
![Screenshot 2023-05-26 at 2.42.53 PM.png](https://images.zenhubusercontent.com/63ea96045c6deec1c9a25425/635637cb-d847-40b4-b8ca-362e2b098912)

**Comment by josephrlee** [comment]
The boats/trailers question is missing the update button on the amount field:

![Screenshot 2023-05-26 at 2.45.47 PM.png](https://images.zenhubusercontent.com/63ea96045c6deec1c9a25425/2e1f5a4c-d200-4556-bb5d-d96bd6bbe84d)

**Comment by josephrlee** [comment]
Testing is finished! Just need to create an issue ticket for the fixes!

**Comment by josephrlee** [comment]
Created a [DST issue](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1797) for the radio button label being cut off.
