### ISSUE TITLE
[Engineering]10-10CG - Unit tests: Determine opportunities for additional unit tests

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#57619]
## Background
We need to review our code in Vets-website repo to increase our Unit Tests to meet/exceed the 75% coverage guidance (currently at 68-70%).  We need to find out where we are short/missing unit tests

- [Vets-website](https://github.com/department-of-veterans-affairs/vets-website)

## Tasks
- [ ] Familiarize with current unit tests in the repo
- [ ] Review code for additional tests that could be implemented
- [ ] Implement and run the new tests (if any) to analyze results for accuracy

## Acceptance Criteria
- Review is complete on determining opportunities for additional unit tests and, if any are found, the tests have been implemented and run with accurate and expedited results
