### ISSUE TITLE
Create prototype for MHV on VA.gov Phase 2 usability test

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#57625]
## Task Description
Create a mobile prototype that includes changes planned for MHV on VA.gov Phase 2:
- After-visit summary

## References
- Ticket #57041: proposal for new appointments list navigation under MHV on VA.gov 
   - Note, this needs CAIA review before it's final.
   - Consider including #50272  Replace breadcrumb with "back" link on appointments list
   - CAIA's WIP recommendations are here - #57669 
- [AVS research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/avs/research/2022-04-MVP-Usability/research-plan.md)

## Acceptance Criteria
- [x] [Mobile prototype in Figma](https://www.figma.com/proto/VHHxvo1QA1ndWc0TBhfkNq/Add-After-Visit-Summary?page-id=2%3A3&type=design&node-id=1233-16119&viewport=-892%2C210%2C0.4&scaling=scale-down&starting-point-node-id=1233%3A16119)
- [x] [AVS research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/avs/research/2022-04-MVP-Usability/research-plan.md) includes all tasks to be tested
- [x] Must include
    - After-visit summary 
<br>
- [x] May include navigation changes: appointment list breadcrumb changes (TBD - needs CAIA review)

**Comment by Cieramaddox** [comment]
@kristenmcconnell [Here](https://www.figma.com/proto/VHHxvo1QA1ndWc0TBhfkNq/Add-After-Visit-Summary?page-id=2%3A3&node-id=1135-10620&viewport=-1777%2C1587%2C0.45&scaling=min-zoom&starting-point-node-id=1135%3A10686) is the prototype set up and ready for the after visit summary to be added. Let me know when you have it ready for me to build out in Figma.

**Comment by kristenmcconnell** [comment]
@Cieramaddox Great. I am reviewing the wireframes with a few people this week. Check out this [Sketch](https://www.sketch.com/s/05d5a740-4fc7-4380-8d83-e7acfbab201b) (High-fi MVP page, then the versions with the accordions). Let me know if you have any feedback.

**Comment by Cieramaddox** [comment]
@kristenmcconnell Loving the accordions. Thank you for sharing. I just made one comment on the Sketch file.

**Comment by outerpress** [comment]
@Cieramaddox could you add the following to the prototype?
- Start from the new VA.gov home page
- Include one page in the login flow. Not the whole thing, just enough to indicate that login has happened.

TBD but we may include a path to medical records via the MHV on VA.gov landing page. We'll discuss more next week.

**Comment by kristenmcconnell** [comment]
@coultonbunney-usds Can you share the latest medical record wireframes (all necessary pages in the workflow to reach AVS, including the care and summaries page), so we can look into adding that workflow to our AVS test?

**Comment by Cieramaddox** [comment]
Awaiting feedback regarding naviagtion

**Comment by outerpress** [comment]
Waiting for Pilot test, changes may come from that.

**Comment by outerpress** [comment]
@Cieramaddox test is in progress so closing this one, feel free to reopen if needed.
