### ISSUE TITLE
MHV to VA.gov: Medical Records Usability testing

### ISSUE THREAD

**Issue by rbsingleton** [department-of-veterans-affairs/va.gov-team#57629]
To be done: 

- [x] Create research plan and conversation guide
- [x] Submit research plan and conversation guide to research repo
- [x] Partner with Perigean for recruitment
- [ ] Collect data
- [ ] Analyze data
- [ ] Socializing findings and make recommendations

**Comment by rbsingleton** [comment]
[Research plan and conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records/research/2023-04-usability-testing-round-1)

[Ticket submitted to research repo](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records/research/2023-04-usability-testing-round-1)

**Comment by bryan-riley-va** [comment]
Completed in Mid 2024
