### ISSUE TITLE
Edits to Need Help

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#57636]
## Tasks

For the unified check in experience: 

- [ ] Address comments in the need help symbols
- [ ] Add need help w/ travel pay symbol to all of the confirmation pages in check in 

## AC

- [ ] Need help symbols include the correct link styling and spacing 
- [ ] Need help w/ travel pay is applied to confirmation pages in check in

**Comment by zach-park** [comment]
@benbrasso-agile6 , the Need help symbols are ready for review now.
