### ISSUE TITLE
MHV to VA.gov: Secure Messaging - Triage Group Research

### ISSUE THREAD

**Issue by rbsingleton** [department-of-veterans-affairs/va.gov-team#57632]
- [ ] Confirm approach documented in Short/long term solution document (attached)
- [ ] Usability testing prep
- [ ] Usability testing of short term solution prototype
- [ ] Evaluation of strategies/ feasibility of long-term solution

[https://app.zenhub.com/files/133843125/1dd1beeb-df1c-4311-a835-79ec778b8652/download](https://app.zenhub.com/files/133843125/1dd1beeb-df1c-4311-a835-79ec778b8652/download)
[https://app.zenhub.com/files/133843125/db44302d-f431-4983-af50-5411100c0e13/download](https://app.zenhub.com/files/133843125/db44302d-f431-4983-af50-5411100c0e13/download)
