### ISSUE TITLE
Intro pages - Content

### ISSUE THREAD

**Issue by lydiahooper** [department-of-veterans-affairs/va.gov-team#57643]
## Issue Description
The 526ez and ancillary paper forms get updated when necessary. This ticket is part of work required to get the digital 526ez form on va.gov sync with the paper version. The scope of this work is to prepare for content review and subsequent research with veterans. In scope are introduction, active duty and expected end date pages. 

Sketch file with mockups: https://sketch.com/s/0fa92d93-0841-4c62-8112-c9c528204092

---
## Tasks
- [x] Create content for three pages, based on language on paper form and research already available
- [x] Meet with VBA about policy questions, to prep for content review

## Acceptance Criteria
- [x] Create ticket for content review

**Comment by lydiahooper** [comment]
Created ticket for content review: https://github.com/department-of-veterans-affairs/va.gov-team/issues/57843

Link to content in Google doc: https://docs.google.com/document/d/1FeN68e-udsPEd_bTUmMSUiiB5UpJ34tFoXiZ657jvdY/edit?usp=sharing

Link to content copied to Github (for SOT): https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/design/introduction%20page%20content.md
