### ISSUE TITLE
Add translated Tagalog alert to 2 COVID pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#57651]
## Issue Description

We need to add an alert to COVID pages in Tagalog when we're awaiting translation. We need to send the content to the translation team and then place the alerts on the main vaccines and boosters pages.

## Tasks
- [x] Send text to translators (Randi)
- [x] Create alert for main vaccines page (Randi)
- [x] Create alert for boosters page (Randi)
- [x] Copyedit main vaccines page and alert (Megan)
- [x] Copyedit boosters page and alert (Megan)
- [x] Publish main vaccines page and alert (Megan)
- [x] Publish boosters page and alert (Megan)

## Acceptance Criteria
- [x] Tagalog alerts are live on the pages

**Comment by megzehn** [comment]
Thank you, @RLHecht!! I reviewed these, published the alerts, and then published the pages.
