### ISSUE TITLE
[Epic] IA - 'Apply' CTA Audit

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#57663]
We have a number of different labels currently in place for online applications in our primary navigation (top nav) and secondary navigation (side nav) - apply now, apply online, etc.   We need audit labels in use, evaluate if there is a preferred  label, and update as appropriate.  We do need to consider different forms may have different use cases that may require them to utilize different labeling (i.e. we use "file claim" in disability), and those situations should be called out.

- [ ] audit current labeling for applications within primary and secondary nav, home page, and hub pages 
- [ ] determine standard for label
- [ ] update labels across site

**Comment by kristinoletmuskat** [comment]
moving this into closed because this is a duplicate ticket
