### ISSUE TITLE
[Epic] Appointments List Navigation

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#57669]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [X] Making revisions to one or more existing VA.gov pages
- [ ] Something else 
 
Our team is requesting feedback from the CAIA team for our initiative adding the navigation for the appointment list in MHV on VA.gov 

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [X] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
August 2023 
 
*Please provide an estimated date so our team can create other relevant tickets.*
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- [Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/initiatives/navigation-link/add-navigation-links-mhv.md)
- [Current links/breadcrumbs/headings](https://dvagov.sharepoint.com/:x:/r/sites/HealthApartment/Shared%20Documents/General/Appointments/Projects/2023%20Appointments%20move%20to%20MHV%20on%20VA.gov/Appointments-FE%20IA%20update.xlsx?d=w68c09cd80f12465daaf847060d02c4cc&csf=1&web=1&e=27eaFn)(VA network)
- [Link to or attach user flows](https://www.figma.com/file/0wG5mpi760FGvVh89phapu/User-flow-for-MHV-Portal-to-Appointments?node-id=0-1&t=9OPd7c3fZcY4KD5x-0)
- Link to prototype or mockups: N/A 
- [Link to any epics/issues that may be helpful](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57667)

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [X] No

## When does this work need to be done?
- Estimated launch date: August 2023
- Estimated staging review date: July 2023
- Content, Accessibility, and IA work needed by: June 2023

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [X] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Appointments Team (formerly known as VAOS) 
- OCTO-DE product owner: [Kay Lawyer](https://dsva.slack.com/archives/U7T6EKTK9) 
- Product manager:  [Jeff Roof](https://dsva.slack.com/archives/D02UD9VS3JP) and [Leah De La Costa](https://dsva.slack.com/team/U02F00JPL79)
- Designer:  [Peter Russo](https://dsva.slack.com/team/U01C2UUHXH9) and [Ciera Maddox](https://dsva.slack.com/team/U02JWT564E9)
- FE engineer: [Simi Adebowale](https://dsva.slack.com/archives/D037VNB23T2)
- Product/team Slack channel: #appointments-team 

- Product Management:

- Design & Research:

- Engineering:

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by kristinoletmuskat** [comment]
The IA is being tracked here: https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/57788

We've started documenting our recs in the IA spec doc, but I need to make some edits to it FYI! But feedback/questions welcome.

**Comment by outerpress** [comment]
@kristinoletmuskat thanks! I'll drop questions here as they pop up.

We do want to revisit cancelation at some point in the future but don't have any plans to change it at the moment, and I believe it would be out of scope for the move under MHV on VA.gov.

(@JRRoof @ldelacosta correct me if I'm wrong here)

**Comment by outerpress** [comment]
FYI @Cieramaddox

**Comment by outerpress** [comment]
@kristinoletmuskat @mnorthuis I updated our [key decisions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/initiatives/navigation-link/add-navigation-links-mhv.md#key-decisions) based on the meeting today. 

Still to do:
- Mock up confirmation/details pages to see if descriptive back link causes any issues
- Finalize MVP for your review
- Document param-based URLs for future work when we revisit requests

I'll update this ticket once I finish those things. Thanks!

**Comment by outerpress** [comment]
@kristinoletmuskat @mnorthuis [Appointments IA changes MVP](https://dvagov.sharepoint.com/:x:/s/HealthApartment/EY-ingYBqb1Amg28qF-MnPEBtNI6EXKAH2aJARGgvgzpeA) is ready for your review. 

I added it to Teams, so Kristin I'll need your VA.gov email - or please let me know if there's an easier way to share.

FYI @JRRoof @simiadebowale @kristenmcconnell @klawyer

**Comment by outerpress** [comment]
We've completed the work of defining the new URLs, Breadcrumbs, and title tags. IA and VAOS has documented this in two spots:
- [VAOS content docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/README.md)
- [IA Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/health-appointments.md)

So I think y'all can close this one out. Thanks for the help!

@RLHecht @kristinoletmuskat @ldelacosta @JRRoof

**Comment by ldelacosta** [comment]
No additional work is needed. Closing out the ticket.
