### ISSUE TITLE
Sprint 15 objectives (2/12 - 2/25)

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5767]
### Long term planning

- Tressa out: Feb 12 – 19

### Order of priorities

1. Bug fixes/508 for address validation
2. Launch checklist for address validation (including E2E testing, documentation)
3. Profile 2.0 work
4. Monitoring, maintenance, bug fixes, hardening, 508, etc.

And we also have Matt onboarding!!

### Address validation

**PM** 

- [x] Determine what analytics we need for this feature #5705
- [x] Create call center guide #5084
- [x] Create a release plan #5085
  
**Dev**

- [x] Profile - Address Validation - Alert-messages copy incorrect #5466
- [x] Profile - Address Validation - Entered address selection IE11 quirk #5505
- [x] Profile - Address Validation - Firefox - Alert-message icon not aligned & spaced correctly #5553
- [ ] [SCREENREADER, FOCUS MANAGEMENT] While on "Please confirm your address" screen, the content from "Edit mailing address" is read by screen reader #5865
- [ ] [SCREENREADER, KEYBOARD]: Edit address link will not receive keyboard focus #5866
- [ ] E2E tests, running in CI/CD, passing on all browsers #5005
- [x] Stop using country name for va profile contact information endpoint #5591
- [x] Security review/Privacy review/ Production readiness review [41](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/41)
- [x] Address validation: Review product outline and update if needed #5256
- [x] Address validation flow to save / validate #5191
- [x] Conditional rendering of the address validation form is somewhat cumbersome #5193

### Profile 2.0

**Design**

Tressa out most of the sprint. For when she is back:

- [x] Military information #5265
- [x] Direct deposit #5266
- [x] Account security #5268
- [x] Connected accounts #5269

**Dev**

- [x] Convert profile phone number form to use SchemaForm #5118
- [x] Refactor direct deposit form #5816
- [x] Profile page scrolls when trying to submit invalid profile data #5458
- [x] Profile edit email modal validations on staging do not match production #5704
- [ ] Release new profile forms to production and remove old legacy code #5817
- [ ] Profile 2.0: Investigate saving contact information #5815
- [x] Profile page scrolls when trying to submit invalid profile data #5458

### Monitoring, maintenance, bug fixes, hardening, 508, etc.

- [x] [COGNITION]: Bug There is a character bug in country select data option ‘Reunion’ where it is ‘R�union’. #5846
- [x] [BE] Stop using country name for va profile contact information endpoint #5591
- [x] filter vet360 address fields in PII sanitizer #5736

### Direct deposit issues

- [x] FE - Hide Direct Deposit section if indicated user is incompetent or has a fiduciary #6088
- [x] BE -Updates to API security for Direct Deposit #6093
