### ISSUE TITLE
[FE][TECH DEBT] - Simplify appointment creation in initializers for e2e tests

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#57670]
## Description
There are several places where we define appointments. The goal of this ticket is to unify those to one mock appointment creation utility.

## Tasks
- [ ] [FE] Create appointment creation utility
- [ ] [FE] update existing tests to use utility
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
@brianseek is this one ready to close? If not, can we put it back in the backlog?

**Comment by brianseek** [comment]
I'll wrap it up today with notes and move it back to backlog

**Comment by brianseek** [comment]
This PR is merged and deployed, moving to closed since there is no further validation
