### ISSUE TITLE
Add text messages to sketch and abstract

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#57688]
## Description

As part of [57560](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/57560), text messages were edited to meet VA Notify criteria. 

Those text messages are in the [user flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677531124203/5edcfd3ea4b1eaf1ef082d56782a8b3291ef3932?sender=u37bb983bd3fc3cc00c7d3286). 

Now, we need to add them into sketch and abstract. 

## Tasks

- [ ] Add three text messages into check in sketch file
- [ ] Merge into the travel Abstract branch
- [ ] Update sketch travel prototype with text message ([sketch page](https://www.sketch.com/s/c3e590f9-898d-4771-a3d4-9464ece91582) and [prototype](https://www.sketch.com/s/c3e590f9-898d-4771-a3d4-9464ece91582/prototype/a/9B61B462-73BA-45CF-ABA4-215FD07B6D5A))
- [ ] Update text messages in unified check in experience sketch file to 375 px width

## AC

- [ ] Text messages are in abstract
- [ ] Sketch prototype has been updated
- [ ] Text messages in unified check in experience sketch file are 375 px width

**Comment by kellysmith1008** [comment]
@ytsaoca Here's the[ link to the intake ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57626)we talked about this morning. 
And here's the [link to the mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677531124203/5edcfd3ea4b1eaf1ef082d56782a8b3291ef3932?sender=u5d970cc175b184392a004997).
And screenshots of the messages as they are in the mural right now:
![image.png](https://images.zenhubusercontent.com/63346ebd45ab78d62eea3201/00635373-95dd-499f-8db4-d832aa988ae0)
![image.png](https://images.zenhubusercontent.com/63346ebd45ab78d62eea3201/d6896d53-9ca7-4e36-8498-73c2e85d3288)
![image.png](https://images.zenhubusercontent.com/63346ebd45ab78d62eea3201/e6ac62bf-e78b-4b09-a7b7-8fb41420c815)

**Comment by ytsaoca** [comment]
Wireframes for review: https://share.goabstract.com/1577994b-d4f5-4a4c-a094-b31d57afc8f9

'cc @zach-park @kellysmith1008 @benbrasso-agile6

**Comment by benbrasso-agile6** [comment]
Text messages look great. Can we merge it up into the parent travel pay branch in Abstract? @zach-park And, can we save down to sketch cloud and update the prototype? I'd like to be able to include the sketch cloud link and prototype for staging review.

**Comment by zach-park** [comment]
@benbrasso-agile6 , the sub-branch is merged to the travel pay branch. And the SMS/1,2,3 wireframes are added to its collection. I have some questions re: the sketchcloud upload. I'll follow up via slack. Thank you.

**Comment by benbrasso-agile6** [comment]
Zach updated the prototype. Gave 1 or 2 quick comments. But, looks good.

**Comment by zach-park** [comment]
[Travel Pay prototype page](https://www.sketch.com/s/38819fc4-18ef-4958-a330-a699785301d6#Version) on sketch cloud: 
https://www.sketch.com/s/38819fc4-18ef-4958-a330-a699785301d6#Version (edited) 

[Happy path prototype](https://www.sketch.com/s/38819fc4-18ef-4958-a330-a699785301d6/prototype/a/0042DC07-D314-45AF-946F-884DCBBE43C0): 
https://www.sketch.com/s/38819fc4-18ef-4958-a330-a699785301d6/prototype/a/0042DC07-D314-45AF-946F-884DCBBE43C0

**Comment by benbrasso-agile6** [comment]
LGTM
