### ISSUE TITLE
Remove Conditional Rendering of Header in User Nav Component

### ISSUE THREAD

**Issue by acaruso-oddball** [department-of-veterans-affairs/va.gov-team#57697]
## Issue Description
Conditional rendering of the Header component has caused a bug in which AutoSSO does not properly work. Initially this rendering was necessary, as it ensured that the sign-in button did not render twice on the Unified Sign In Page. However, to get AutoSSO to work, the header renders regardless. To do so, we will need change what’s rendering conditionally. In this issue, we will remove code around conditional rendering of the Header component. 

## Tasks
- [x] Remove lines 258 - 263 on the site-wide/user-nav/containers/Main.jsx
- [x] Update tests to accommodate such change.

## Acceptance Criteria
- [x] Header component no longer conditionally renders.  
- [x] All tests pass appropriately.
