### ISSUE TITLE
Update Design Artifacts for Release

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#57707]
## Description
Update sketch wireframes so that they match what we are releasing and prepare them for merging to Abstract main and VA Sketch Cloud.

## Tasks
- [x] Validate that final sketches (and/or poster) match what we are pushing to production. For example, a wireframe or content may have gotten out of date. 
     - [x] If sketch files aren't up to date and what engineering is pushing to production is correct, update sketch files to match what we're going to release to production with
     - [ ] Notify FE if they missed something in that's in sketch that's supposed to be in production. Create a ticket and post it in Slack to notify them. 
- [x] Prepare SketchCloudwireframe (and/or poster) collection so that it can be merged when we go to production
- [x] Prepare [production prototype links](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/product#production-wireframes-in-va-sketch-cloud)

**Comment by zach-park** [comment]
@benbrasso-agile6, ready to be validated. 

Updates are:

PCI In-person & Phone (and corresponding pages in the production sketch file): 
- Action links on the Intro pages 
- https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/a/uuid/3AA6CBDB-6B1D-459B-9D7D-E9B85EB64E5E
- https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/a/uuid/91DDF09A-6229-4463-A291-EB455FD8E694
- https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/a/uuid/519EDF29-3F80-40BC-B2CC-DEA2BCD7DD58
- https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/a/uuid/C45F8029-C8D6-4A91-BABF-7DF9AF52FB75
- https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/a/uuid/128910BC-B398-4F46-B745-7D72E4698BE1
- https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/a/uuid/7AFAAAD4-2E2E-435D-9164-071EE9E6D631

CI  (and corresponding pages in the production sketch file): 
- Eyebrow 
- https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/uuid/F2F43173-8B35-4C8E-9B15-73D52A3F7A3D
- https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/uuid/B6810409-F08B-4D99-B0B4-8901C1587331
- https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/uuid/B7DCB10D-923D-45F1-8DF0-8FAD31A105CE
- https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/uuid/3105EBC1-585B-49B0-B85D-CE91F0A90104
- https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/uuid/240EBCC2-AD7B-447B-A3CC-5FDFDA8D2E23

**Comment by benbrasso-agile6** [comment]
LGTM
