### ISSUE TITLE
Update CSS around conditional rendering of the Header component. 

### ISSUE THREAD

**Issue by acaruso-oddball** [department-of-veterans-affairs/va.gov-team#57701]
## Issue Description
Conditional rendering of the Header component has caused a bug in which AutoSSO does not properly work. Initially this rendering was necessary, as it ensured that the sign-in button did not render twice on the Unified Sign In Page. However, to get AutoSSO to work, the header needs to render regardless. To do so, we will need change what’s rendering conditionally. In this issue, we will update the CSS around . 

## Tasks
- [x] Update Header component to conditionally hide the container that contains the Sign In Modal using CSS, when user navigates to the Unified Sign-In Page. 
- [x] Clean up neighboring styling to accommodate such changes. 
- [x] Update tests to accommodate such change.

## Acceptance Criteria
- [x] Header component's visibility is conditional using CSS.  
- [x] All tests pass appropriately.

**Comment by aparsley** [comment]
Looks great, thank you for attaching 56514 with screen shots for comparison.
