### ISSUE TITLE
Refactor unit test due to the removal of getConfirmedAppointments function

### ISSUE THREAD

**Issue by vbahinwillit** [department-of-veterans-affairs/va.gov-team#57700]
This PR refactors all unit test affected by the removal of the getConfirmedAppointments function.

**NOTE** This PR is a dependency of #53080 and must be merged into #53080 before creating PR for #53080.

```[tasklist]
### Tasks
- [ ] Fix PastAppointmentsListV2 unit test
- [ ] Fix UpcomingAppointmentsList unit test
- [ ] Fix AppointmentListV2 unit test
- [ ] Remove appointment v0/v2 comparison tests
- [ ] Fix BackendAppointmentServiceAlert unit test
```
