### ISSUE TITLE
Content support for After Visit Summary 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#57711]
## Issue Description

The after visit and appointments team opened an intake request for CAIA support for the new After Visit Summary online experience. 

Intake request for background: #57259

For MVP, the content needs to stay consistent with what's on the PDF form that the Veterans are used to getting. We should be tracking content that needs to change to align with the work we're doing in My HealtheVet on VA, but we can't make those changes now. 

Link to [prototype or mockups](https://www.sketch.com/s/05d5a740-4fc7-4380-8d83-e7acfbab201b) - Look at "Low-fi MVP" page

## Tasks
- [x] Edit content (Aliyah)
- [ ] Review (Laura)
- [ ] Give product team final content in intake request

## Acceptance Criteria
- [ ] Product team has final content

**Comment by aliyahblackmore** [comment]
I started on an edit of this work and passed what I have so far to Laura - via Slack.

**Comment by aliyahblackmore** [comment]
**Updates:** 

- Laura caught me up on Tuesday with notes from her meeting with the AVS team last week 
- We discussed compiling 4 to 5 questions we'd like to get answered in testing - based on the newly added high-fi designs in sketch. 
- I passed my 4 to 5 questions to Laura via slack today, 5/17

**Comment by aliyahblackmore** [comment]
**Updates:** 

- Laura and I synced on my 4 to 5 testing suggestions yesterday 
- We aligned on prioritizing testing some content around medications and the glossary.
- Adjustment made to those pieces of content we're suggesting get tested.
- Content is in a SharePoint document

**Comment by RLHecht** [comment]
Product team has final content. We can track any follow-up work in the intake ticket or open a new content only tickets. Closing.
