### ISSUE TITLE
Add specs in unified check in annotations page in sketch

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#57727]
## Tasks

- [x] Document headings (e.g., h1 + h3 styling) AND spacing for each design template. For example, [design template with the "What to do next" heading](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/bgwvQKZ) (this one is complete) vs. [design template with h1 + body text](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/zx95r4b). 
- [x] Pick 3 components and create an artboard with the spacing specs

## AC

- [x] Annotations and Designs Specs shared with UX team
- [x] Annotations and Design Specs updated

**Comment by benbrasso-agile6** [comment]
@zach-park I added some "design templates" next to this [annoations artboard](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/oMMjpEL), where we might want to add the spacing specs to these, like you did to that first example

**Comment by zach-park** [comment]
@benbrasso-agile6 , the spacing artboard is ready for review. 
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/oMMjpEL

**Comment by cgednalske** [comment]
Looks great @zach-park! This is/will be extremely helpful. Might be small tweaks to make as we learn more about the Design System defaults, but you've made it super easy for us to document all that as we move forward 🎉 🎉
