### ISSUE TITLE
Rework and publish compare education benefits for family members page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#57744]
## Issue Description

We have a draft version of an R&S article for comparing education benefits for family members that was started a while ago with a previous content team. We need to rework this page to make sure it meets our plain language and current style standards. We also need to determine if we should add other benefits to the page (VR&E, Chapter 36). 

Once we revise the page we should send to stakeholders along with the draft article for comparing education benefits for Veterans. These pages can both be published at the same time.

Drupal page: http://preview-prod.vfs.va.gov/preview?nodeId=44718

## Tasks
- [ ] Rework page (Katherine)
- [ ] OCTO review (Beth)
- [ ] Send to stakeholders (Katherine)
- [ ] Copyedit (Megan)
- [ ] Publish (Megan)

## Acceptance Criteria
- [ ] New article is live on the site

**Comment by katherine-fung** [comment]
I've determined that there are no other benefits that need to go on this page. I'm moving forward with re-working it.

**Comment by katherine-fung** [comment]
I've started working on this page. 

Draft in progress: http://preview-prod.vfs.va.gov/preview?nodeId=44718 

I have a few notes and questions about it @bethpottsVADEPO.  

1. I've tweaked the style of the headers to match the "Compare VA education benefits" page. Since the latter included eligibility information, I've created a new section "Eligibility requirements" for DEA and the Fry Scholarship. 
2. I based the language of the eligibility requirements on the legislation in the federal register (https://www.ecfr.gov/current/title-38/chapter-I/part-21/subpart-C), but there are slight variations between the legislation I read (not sure if there have been updates to it that I'm not aware of) and the program pages on VA.gov. We'll need SMEs to confirm. 
3.   There was a note on the program pages about a situation in which you can use both DEA and the Fry Scholarship. I created the section "What to know if you qualify for both DEA and the Fry Scholarship" to 
4.   this information. 
4.   I tried to make sense of the "How much time you have to use benefits" section, but I had a hard time. For example, both the DEA program page and the Compare draft say if you're a child, you can use DEA benefits between the ages of 18 and 26. However, my reading of the legislation suggests that you can't start using benefits after age 26. But if you're already using DEA benefits, you can use them until age 31. Can we have stakeholders confirm the time limit to use benefits, and when you can/can't get DIC benefits? 
("Age limitation for commencement.  No person is eligible for educational assistance who reached his or her 26th birthday on or before the effective date of a finding of permanent total service-connected disability, or on or before the date the veteran's death occurred, or on or before the 91st day of listing by the Secretary concerned of the member of the Armed Forces on whose service eligibility is claimed as being in one of the missing status categories of § 21.3021 (a)(1)(iv) and (3)(ii). 

(d) Termination of eligibility.  No person is eligible for educational assistance beyond his or her 31st birthday, except as provided under § 21.3041(g)(2). In no event may educational assistance be provided after the period of entitlement has been exhausted. In an exceptional case special restorative training may be provided in excess of 45 months. See § 21.3300.")

**Comment by bethpottsVADEPO** [comment]
@katherine-fung One more thing! For the CTAs at the top of the page, we should remove "more" from those labels. I also think we'll need to change that last sentence in the intro to: Keep reading on this page to compare these 2 programs and decide which is right for you.

**Comment by katherine-fung** [comment]
Thanks for the feedback @bethpottsVADEPO! 

I made the edits to the intro, main CTAs, "What to know" and "Eligibility" sections. 

re: the use of the word "surviving" for "child or spouse" in the "Eligibility" section - 
- For DEA, the child or spouse may be eligible in situations where the service member or Veteran is still alive. So it makes more sense here to say "child or spouse" without the word "surviving.
- For Fry, the child or spouse is eligible only in situations where the service member or Veteran has died. Here, it probably makes sense to say "surviving child or spouse." [though the program page for Fry says "child or surviving spouse"]. We could also say "child or spouse" without the word "surviving."
- If we want to use the same phrase when talking about both DEA and Fry, we could say "child or spouse."

For the "Programs you can use these benefits for" section, you can use both DEA and Fry for most of the programs. But there is 1 difference - you can use Fry, not DEA, for flight training. 

We could shorten this section by saying: 

> You can use DEA or Fry Scholarship benefits to pay for these types of programs:
> - Higher education 
> - Training for a specific career, trade, or industry
> - Classes from home 
> - Work study 

>**Note:** Only the Fry Scholarship covers vocational flight training.

> You can also use DEA or Fry Scholarship benefits to pay for these costs: 
> - Tutorial assistance
> - Fees for standardized testing, and tests for licenses and certifications

**Comment by katherine-fung** [comment]
[saving my questions for SMEs here: 

I'm working on the page "Compare DEA and Fry Scholarship benefits for family members." I have a few questions.

1. We currently say that if you're the child of a service member or Veteran, you can only use DEA benefits between the ages of 18 and 26. [My reading of the legislation](https://www.ecfr.gov/current/title-38/chapter-I/part-21/subpart-C) says you can start using DEA benefits between the ages of 18 and 26. Is it accurate to say the following? "If you’re a child, you can start using this benefit between ages 18 and 26."

2. My understanding is that someone can get 45 months of DEA benefits. According to my reading of the [legislation](https://www.ecfr.gov/current/title-38/chapter-I/part-21/subpart-C), you can't use DEA benefits once you turn 31. Is it possible for someone who starts their DEA benefits between the ages of 18 and 26 to pause using their benefits, and then continue using them again (for example, at age 29)? Or would someone have to use their DEA benefits continuously?

3. I reviewed the legislation outlining eligibility for DEA under [Title 38, Chapter 35 of US Code](https://www.ecfr.gov/current/title-38/chapter-I/part-21/subpart-C) and [Public Law 109-461](https://www.govinfo.gov/content/pkg/PLAW-109publ461/html/PLAW-109publ461.htm). I see that Chapter 35 says a child or spouse is eligible if A. the service member or Veteran "has a total disability permanent in nature resulting from a service-connected disability." Our existing va.gov page about DEA adds that a child or spouse is eligible if B. the Veteran or service member "is in the hospital or getting outpatient treatment for a service-connected permanent and total disability and is likely to be discharged for that disability." Does group A include those in group B?

4. On the current va.gov page about DEA, we say that a child or spouse is eligible for DEA if "the Veteran or service member died while on active duty or as a result of a service-connected disability..." Is the part in bold true? I didn't see this in the legislation, so I want to confirm.]

**Comment by katherine-fung** [comment]
I sent a list of questions to stakeholders on 6/7/23. 

Separately, Tammy asked other EDU stakeholders on 6/22/23 if the page should also compare TOE benefits. 

Waiting for stakeholders' responses to both messages.

**Comment by bethpottsVADEPO** [comment]
@katherine-fung You could do an assessment about whether it makes sense to incorporate TOE onto this page in some way. It might not be an exact apples to apples comparison that's needed between the 3 options here, but more of a comparison of Fry and DEA with a TOE "presence" as well. Let's chat about it!

**Comment by katherine-fung** [comment]
Hi @laurwill, 

We got feedback from stakeholders about our proposed DEA updates. I emailed them a few questions about this feedback. 

I also want to get your thoughts on copy for the sections "If you became eligible on or after August 1, 2023" and "If you became eligible before August 1, 2023." 

**Under "If you became eligible on or after August 1, 2023"**

I tweaked the list of bullet points to define who became eligible on or after August 1, 2023.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEJjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ecd8c587b069f766d5284975c30c85c8259488d7/Screenshot%20%28244%29.png)

**Under "If you became eligible before August 1, 2023"**

- I edited the first section of the copy about who has time limits to apply to both children and spouses (originally, this copy specified children). The stakeholders' edits specify that "a spouse who became eligible or who turned 18 and completed high school on or after August 1, 2023, has no time limit to use these benefits." I assume that means anyone (not just children) who turned 18 or completed high school before August 1, 2023 does have time limits to use benefits. I can confirm this with stakeholders. 

- I'll ask stakeholders if this note applies to spouses (we currently say this for children of Veterans and service members): 
"Note: If you join the military, you can’t use this benefit while on active duty. And if you want to use this benefit after you leave the service, you can’t have a dishonorable discharge. Military service can extend your eligibility, but this extension usually ends when you turn 31 years old."

- I'll ask stakeholders if this note about spouses is necessary: "Note: This policy began on October 10, 2008. We won’t pay benefits for training you started before this date."

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVJjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b22f673e3bddb868f0c252331478b10d9efa101b/Screenshot%20%28245%29.png)

**Comment by katherine-fung** [comment]
I followed up with the edu team to request an accuracy review of the compare page today.

**Comment by katherine-fung** [comment]
I've sent the edu team an invite for 2/7 to provide feedback on this draft.

**Comment by katherine-fung** [comment]
I haven't been able to return to this work since 2/7.

**Comment by katherine-fung** [comment]
Update on this: Jodie and Cinda gave us some feedback that some content may have to change to reflect guidance for family members that have DEA entitlement from multiple Veterans. 

SME Jerome G. responded on Feb 16 (pasting his response below). I've followed up via Outlook now to try to understand how this information affects the copy we drafted.  cc @aprocik1 @bethpottsVADEPO @d-beyer 

Jerome's response: 

> •	How many months of benefits can the eligible person receive? 
> o	An individual (spouse or child) may receive a maximum of 45 or 36 months of entitlement, regardless if they receive entitlement from multiple sources, depending upon when they first used chapter 35 benefits.
> 	45 months of entitlement if first used before August 1, 2018.
> 	36 months of entitlement if first used on or after August 1, 2018.
> 
> •	Does the eligible person have to use the benefits in a certain order? Do they have to use benefits from both Veterans or service members in a row?  
> o	No. Benefits can be used individually at the student’s direction (i.e. each period of enrollment the student can identify which entitlement source they wish to use).
> o	If the student receives entitlement from multiple sources, the multiple entitlement sources can be used concurrently, though twice the entitlement will be charges for terms when this is done.
> 	Example: A beneficiary with two sources of entitlement has 36 months of original entitlement. If they elect concurrent payments; an enrollment for 4 months of fulltime training paid will be paid at twice the fulltime rate. This beneficiary will have 28 months of chapter 35 remaining after this certification is processed).
> 
> Please Note: For Survivors’ and Dependents’ Educational Assistance (Chapter 35) there is a statutory limit that a claimant can only use a max of 81 months of benefits if the individual uses more than one education benefit. 
>

**Comment by aprocik1** [comment]
Update: I followed up with Cinda, Jerome, Jodie, and Terry about this page via email. I asked them for a final accuracy review of the sections we updated based on Jerome's latest feedback. We hope to publish this page by the end of the year.

**Comment by aprocik1** [comment]
Update: I just sent this email to cinda.quattrini@va.gov, jerome.golombek@va.gov, jodie.balder@va.gov, and terry.warren@va.gov:

> The information on this page was originally part of a broader legacy page comparing all the education benefits that we migrated to [VA.gov](http://va.gov/). The purpose of this page was to separate out the information for our non-Veteran audience. It's meant to be the family member version of this page: [Compare VA education benefits](https://www.va.gov/resources/compare-va-education-benefits/)
> 
> Beth and Cinda talked briefly about it yesterday and decided that it can wait since it's a busy time with Rudisill changes. We're happy to pick it back up when there's a little more bandwidth for your review.
> 
> We'll plan to check back in beginning of next calendar year. And of course, let us know if you do want to proceed with a review before the holidays. Either works for us!

I put a reminder on my calendar to return to this in January 2025. For now, I'm placing this ticket in backlog.

**Comment by aprocik1** [comment]
Current status: This page needs to be reviewed by SMEs. I discussed this with Beth on January 14. She's prioritizing other work with the education service stakeholders right now. Our last communication with them about this page is in my previous comment.

[Compare DEA and Fry Scholarship benefits for family members](https://preview-prod.vfs.va.gov/preview?nodeId=44718) (Drupal)
