### ISSUE TITLE
[UX] Finalize CodePen Prototype

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#57751]
## Tasks

- [x] Finish edits in CodePen based on changes in Sketch from CAIA feedback
- [x] Change links to debug mode
- [x] Make sure accessibility feedback from CAIA feedback is included 
- [x] Address all remaining feedback about conversation guide from [Slack thread](https://dsva.slack.com/archives/C02GXKL8WM6/p1681218994743479)
- [ ] Double check spacing aligns with Sketch designs and spacing guidelines

## AC

- [x] Pens are linked and prototype can be viewed in debug mode
- [ ] Code and accessibility reviewed by FE

**Comment by benbrasso-agile6** [comment]
I'm going to do a review. Assuming these links are correct? 

https://codepen.io/team/va-cie/full/NWORQEe
https://codepen.io/team/va-cie/full/qBJqWaV

**Comment by cgednalske** [comment]
New links for the final live mode (no CodePen iFrame):

Pre-check-in start - https://codepen.io/team/va-cie/live/NWORQEe
Check-in start - https://codepen.io/team/va-cie/live/qBJqWaV

**Comment by benbrasso-agile6** [comment]
- When I hit the "jump to e checkin," then authenticate, I think the appt list page is incorrect. I would have expected a check in now card.

**Comment by benbrasso-agile6** [comment]
Let me know when that's resolved and I can proceed looking at check in.

**Comment by cgednalske** [comment]
@benbrasso-agile6 resolved! 👍

**Comment by benbrasso-agile6** [comment]
Gave more feedback via phone call. E.g., add "it's almost time to check in" card after returning to appt list for check in.

**Comment by cgednalske** [comment]
The following main updates were completed after Ben's review. Closing this out - spacing will be addressed in the #57728 spacing ticket.

- Eyebrow added to review your information flow
- Card added for “you can check in soon” on top of the second check in appointment list
- New confirm page at the end of check in flow
- New appointment list page for the new end of check-in
- Time zone removed from appointment list times

**Comment by benbrasso-agile6** [comment]
This is validated
