### ISSUE TITLE
Update number of days to complete disability related claims for April 2023 (in English and Spanish)

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#57753]
## Issue Description
We need to update the number of days it takes to complete disability related claims. Sitewide content needs to email Tanekwa Bournes on the first of the month to get the number from the previous month and input into Drupal.

This needs to be done on the following pages:
https://www.va.gov/disability/after-you-file-claim/
https://www.va.gov/disability/how-to-file-claim/
https://www.va.gov/disability/eligibility-esp/
https://www.va.gov/disability/after-you-file-claim-esp/

## Tasks
- [x] Email Tanekwa for most recent number (Randi)
- [x] Input number and new month into both Drupal pages (Randi)
- [x] Review Spanish pages (Ana)
- [x] Review English pages (Megan)
- [x] Publish all 4 pages (Megan)

## Acceptance Criteria
- [x] Most current number of days is on live site

**Comment by RLHecht** [comment]
Tanekwa wrote back and this month's number is 102.2.

**Comment by RLHecht** [comment]
@ABeltran77 the 2 Spanish pages are ready for you to review. You only need to look at the box with the number of disability-related claims to make sure there are no errors. Posting the drupal pages here. You need to be in Citrix to view these:

http://preview-prod.vfs.va.gov/preview?nodeId=50453
http://preview-prod.vfs.va.gov/preview?nodeId=50435

You can comment back here if they look good to go and then @megzehn can publish.

and @megzehn the 2 English pages are ready for you to review and publish!

**Comment by megzehn** [comment]
Thanks, @RLHecht! I reviewed and published the English pages!

**Comment by ABeltran77** [comment]
I reviewed the pages and they look good.

**Comment by megzehn** [comment]
Thanks, @ABeltran77! Confirming these 4 pages are now published. Ready to validate @RLHecht.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
