### ISSUE TITLE
Profile: Sprint 11 (5.24.23 - 6.6.23) Epic

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#57752]
## Sprint 10 Retro
EasyRetro Board ([link](https://easyretro.io/board/f4051524-d7be-43a4-8c50-f43d887f3a7f/9071d4c2-39da-41bc-a67e-aea76e4628dd))

## Sprint 11 Notes
Sprint 11 epic will be finalized at Sprint Planning -- [see project outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/sprint-objectives/profile/sprints-1-10-Jan23-May23.md#sprint-11) for more info

## 2023 Priorities for Authenticated Experience
<details> 
<summary>2023 Priorities Breakdown</summary>

**High**: 
Migrating MyHealtheVet into VA.gov; 
expanding notification functionality (both onsite and preferences); 
improving the logged-in nav/IA/experience overall; urgent/required maintenance for a feature; unplanned work that aligns with OCTO high-priority objectives

**Low**: 
improvements team wants to make but might fall outside of OCTO objectives
To complete: some initiatives that we should finish but don't fall under OCTO high-priority objectives
</details>

## Q2 CY2023 (Apr-Jun) Product Goals
More details found at [Q2 CY2023 Product Roadmap](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/roadmap/2023-goals-roadmap.md#q2-cy2023-april---june)

## Carry over (modify points in Sprint Planning)
**In progress**
- ~~#54771~~ moved to sprint 13
- #54893 

**In validate**
- #54082 
- #47666
- #58520

##  Direct deposit migration EVSS > Lighthouse (Epic #51900)
**Question for planning:** Are we ready for QA testing? 
Goal: Finalize QA/ integration testing in Staging and get GA items ready

- [x] #54893
- [x] #54879 
- [ ] ~~#54896~~ < move to sprint 12
- [x] LH conversation about sharing Client ID's concerns around best practices 

If we get far enough w/testing PM to take these steps:
- Fill out [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md) and add it to [project folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit/evss-lighthouse-migration)
- Submit ticket for privacy and security review

## Notification preferences ( #49319 & #51113 )

**Email as a channel** 
Incorporate DI feedback #58790 , to finalize default send work/add email as a channel
- Collab Cycle PM Ticket #56397
- Design Intent #58231
- [x] Design - Sketch Files Update #58890

**Updated Mobile Flow**
- Collab Cycle PM Ticket  #57820
- Design Intent #58231

**Surface Relevant Links**
- [ ] ~~#54047~~ moving to sprint 12

## Logged-in IA/nav research (Epic #51519)
Discovery: where we can surface personalized content
- [x] #58875
- [x] #59022 (3pts) completed in this sprint

## Technical Debt - API Improvements (#54241)
Working on improving our mock testing data 
- [x] #54237
- [ ] ~~#54238~~ < this moves to next sprint 
- [x] #52628

## General / Other
- [x] #55398
- [ ] #58388 
- [x] #47070 (in validate) 
- [x] #52944

## Unplanned Work
- For this sprint -- allot 2-3 points for unplanned work 
- [ ] #59301 < we added this work at the behest of mobile and then quickly reversed course. Tom is going to add a story to next sprint to update our documentation to clarify how demographics sections work 
- [x] #59140
- [x] #59409
- [x] #59446
