### ISSUE TITLE
[BE] 10-10EZ - Bug: Update SOAP response for Race/Ethnicity/Origin question

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#57769]
## Background
We received an email from the VES team reporting an issue found during testing in SQA (our Staging env):
>During testing of Demographics in SQA environment, VES team encountered unexpected results when user selects “Prefer Not to Answer” for Race & Ethnicity in online application. VES is expecting to receive “Declined to Answer” for both Race and Ethnicity; instead, we are getting “Not Hispanic or Latino” (2186-5) for Ethnicity and nothing for Race. The SOAP message is provided in the attachment.
>
>![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/a97f3716-9c6b-4807-92a2-d472576325bf)

We engaged the team and determined that the SOAP message should refer to the "Prefer not to answer" selection:
>I believe the message should be like this when VOA user selects “Prefer Not to Answer” for Race & Ethnicity.
>![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/dda4f308-4fce-4202-86a4-6dcb2d4b32a2)

We need to update the SOAP message to correspond to the selection made by the Veteran within the application.

## Tasks
- [ ] Update SOAP message to include the correct code for Ethnicity and Race when "Prefer not to answer" is selected
- [ ] Confirm with VES that they have tested this change successfully
- [ ] Release to Production

## Acceptance Criteria
- The correct codes that correspond to the Race/Ethnicity/Origin selections are sent to Enrollment system
