### ISSUE TITLE
Sidekiq access updates

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#57760]
### Background
During the 4/18/23 Backend CoP meeting ([meeting notes](https://vfs.atlassian.net/wiki/spaces/BCP/pages/2604204250/4+18+23+BE+CoP+Meeting+Minutes)), we talked about Sidekiq UI access. Bill Chapman and Clint agree that Bill does not need to be involved with the Sidekiq Admin UI Access Requests, so the Backed CoP need to have a process for support to follow to grant access to the different sidekiq envs.

### Tasks
See meeting notes (linked above ☝️) to complete these tasks

- [ ] Update the [Sidekiq Admin UI Access Request link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=sidekiq-access-request%2Coperations%2Cops-access-request&template=sidekiq-admin-ui-access-request.md&title=Sidekiq+Admin+UI+Access+Request) to better fit our needs.
- [ ]  Update the [internal documentation](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Sidekiq-UI-Access) for the Platform Support team to follow.
- [ ] Update [external documentation](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2555183177/Sidekiq+UI+Access) (if necessary) that is published to the Platform website for VFS teams. 

### Acceptance criteria
- [ ] Updated GitHub template for access is reviewed and merged
- [ ] Documentation is reviewed

**Comment by ryan-mcneil** [comment]
New Sidekiq Admin UI Request form [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Cplatform-tech-team-support%2Cops-access-request%2Csidekiq-access-request&projects=&template=vetsapi-sidekiq-ui-access.yaml&title=Sidekiq+Admin+UI+access+for+%5Bindividual%5D)

Will mark the old one obsolete soon.

**Comment by ryan-mcneil** [comment]
Internal and External docs updated, pending review ✅
