### ISSUE TITLE
Understand # of sessions to complete metric discrepancy 

### ISSUE THREAD

**Issue by Nyanteea** [department-of-veterans-affairs/va.gov-team#57789]
## Issue Description

The number of sessions to complete the benefits disability (from 526ez) claims jumped drastically in April 2023. Has something changed about how this is being calculated? 
 
1.87	19 Mar 2023
1.82	26 Mar 2023
1.70	2 Apr 2023
4.15	9 Apr 2023
4.73	16 Apr 2023

[Link to thread on Slack](https://dsva.slack.com/archives/C1Q4294JJ/p1682704549071669)

---
## Tasks
- [ ] Circle up with Michelle Dooley of updates to the issue 

## Acceptance Criteria
- [ ] # of sessions to completion will be established/confirmed as a success metric
- [ ] Understand why the metric jumped in April 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Nyanteea** [comment]
@RakshindaAslam, I'm adding new tickets for outstanding metric questions. Let me know if it's better to combine a few into one.

**Comment by Nyanteea** [comment]
Resolution: The data table loaded more than once during those two weeks during other system updates causing the inflated numbers. The Analytics team removed the duplicates to reflect the actual number of sessions.
