### ISSUE TITLE
Medallia - adjust header styling to match VA design standards

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#57780]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [ Styling] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _Review and create specific ARIA label work 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by aubreyarcangel** [comment]
about 95% done. Met with Sarkis today to discuss solutions for adding `aria-labels` to the phone numbers. Currently researching the best way to do that.

**Comment by aubreyarcangel** [comment]
Had a blocker earlier where the mock survey went blank and was unable to test. I reached out to Sarkis and it is back up now.

Continuing working on the solution which requires writing a script that appends the labels and hyperlinks to the header

**Comment by aubreyarcangel** [comment]
Blocked by unable to deploy review instance to test solution. Opened a ticket with VFS platform support and DevOps is still investigating. It was a wider issue that has impacted other PR review instances https://dsva.slack.com/archives/CBU0KDSB1/p1684767619143429

A [PR](https://github.com/department-of-veterans-affairs/devops/pull/13069) was recently merged in the devops repo to fix the issue, but the problem still persists. Still
