### ISSUE TITLE
EVSS Migration: Form 21-526EZ Submit Workflow: retrieve ICN for rated disabilities call in Form526RapidReadyForDecisionConcern#disabilities_not_service_connected?

### ISSUE THREAD

**Issue by ahay-agile6** [department-of-veterans-affairs/va.gov-team#57791]
# Problem
Within the context of the background job that submits the completed Form526 on behalf of the veteran, there is a call to retrieve Rated Disabilities from a different source.
Currently, that source is EVSS.
However, we need to migrate from EVSS to another service provider called Lighthouse.

EVSS requires certain authentication headers to be used when making a service call. These headers are saved into the database and retrieved when the submission happens in the job.

Lighthouse requires certain authentication context to identify the Veteran that needs the data. This authentication context is called the `launch` context. Within the `launch` context, there is an attribute called `patient`. 
The value that Lighthouse is expecting for `patient` to uniquely identify a Veteran is the Veteran's ICN.

The main way `vets-api` has access to a Veteran's ICN is through the `@current_user` context, which is available with a logged in user making requests to `vets-api`. We were using this `@current_user` to send the Veteran's ICN to Lighthouse to get their Rated Disability data.

However, in the context of a background job, there is no `@current_user`, as there is no user logged in.
Instead, the `Form526Submission` data object saved off what is called "`auth_headers`" - an encrypted field in the database, and retrieved it during the submission job, and sent those headers to the EVSS endpoint.

We believe that `auth_headers` does not have the Veteran's ICN to pull from to satisfy the Lighthouse requirement to get the Veteran's Rated Disabilities.

So, we need to retrieve the Veteran's ICN... somehow, and pass it into our service provider creation so that when we migrate to use solely the Lighthouse Data Provider, the Veteran can submit their form properly.

## Tasks:
- [ ] make sure `Form526Submission#auth_headers` does not have ICN. If it does, great! we can use that in `Form526RapidReadyForDecisionConcern#disabilities_not_service_connected?`. But our initial findings (albiet they were very quick and dirty) did not lead to this conclusion. Double check!
- [ ] If the first task is absolutely "no", we need to figure out how to get the Veteran's ICN within the context of the background job

## Acceptance Criteria
- [ ] ICN is retrieved and passed in to `ApiProviderFactory` that creates the rated disabilities service in `Form526RapidReadyForDecisionConcern#disabilities_not_service_connected?`
