### ISSUE TITLE
Update Design Artifacts for Release

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#57810]
## Background
Base on [this minor change][[FE] Change alert content shown when Veteran is too early to check in within check in app](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/54511) to content, we need to update the appropriate design artifacts. This is already in production.

## Description
Update sketch wireframes so that they match what we are releasing and prepare them for merging to Abstract main and VA Sketch Cloud.

## Tasks
- [x] Validate that final sketches (and/or poster) match what we are pushing to production. For example, a wireframe or content may have gotten out of date. 
     - [x] If sketch files aren't up to date and what engineering is pushing to production is correct, update sketch files to match what we're going to release to production with
     - [ ] Notify FE if they missed something in that's in sketch that's supposed to be in production. Create a ticket and post it in Slack to notify them. 
- [ ] Prepare Abstract wireframe (and/or poster) collection so that it can be merged when we go to production
- [ ] Prepare [production prototype links](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/product#production-wireframes-in-va-sketch-cloud)

**Comment by zach-park** [comment]
In reference: 

![localhost_3001_health-care_appointment-check-in_loading-appointments.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/c95fce0b-e38f-474c-860d-b976f57ee6a3)

**Comment by zach-park** [comment]
@benbrasso-agile6 , the wireframe is added for this use case. And it is ready for review.
https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/a/JAPpqDz

NOTE: The wireframe is also added to the [design sketch file](https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/Wdopq32) also for reference.

**Comment by benbrasso-agile6** [comment]
LGTM
