### ISSUE TITLE
HLR | Update contact info page

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#57815]
## Value Statement
**_As a_** Veteran with accessibility needs that is filing a higher-level review
**_I want to_** file using the latest enhancements to the frontend experience
**_So that_** I can benefit from accessibility and other design updates. 

---
## Background Context

Higher-Level Review contact info page does not display any message that an entry has been updated. This includes focusing on the updated alert after returning to the main contact info page. Additionally, the contact info page needs to be made editable from the review & submit page - it would show the edit contact info page and return to the review & submit page.

These enhancements are implemented in our Supplemental Claims form, so we should copy these enhancements from there.

## Acceptance Criteria
- [x] When a user makes changes to their contact info, they see a successful update alert
- [x] Focus management includes focusing on the update alert when a change is made, and focus on the edit link when the edit is canceled
- [x] User can edit contact info from the review & submit page - go to edit page & return to review & submit page
- [ ] Add analytics events for update & cancel clicks

## Designs and Build Notes
- [Supplemental Claim contact info DESIGN](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/p/14726A84-8E51-4285-B64D-2100694C5CB3/canvas)

## Out of scope
- Add here

## Open questions
- Will these updates require any content or design changes?

## Tasks
- [ ] Add successful update alert
- [ ] Add focus management
- [ ] Implement editing from review & submit page
- [ ] Add analytics
- [ ] Unit tests updated
- [ ] e2e tests updated

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by saderagsdale** [comment]
@Mottie add screenshot or link to design

**Comment by saderagsdale** [comment]
@Mottie shouldn't this be in progress?

**Comment by Mottie** [comment]
Yes, thanks!

**Comment by Mottie** [comment]
Please test these changes in staging.

**Comment by saderagsdale** [comment]
@eileen-coforma I checked the other AC. Do we need to put in an analytics ticket for the last one or is that a note for @Mottie to put it in the code?

**Comment by Mottie** [comment]
It's built-into the profile components...
<img width="272" alt="GA data layer event profile-navigation, profile-action is cancel-button and profile-section is home-telephone" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/56cafe94-cb91-48f6-87f1-6f5d6edf228a">

<img width="289" alt="GA data layer event profile-navigation, profile-action is update-button and profile-section is mobile-telephone" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/902e8688-5814-4401-bd01-280e070b9983">
