### ISSUE TITLE
[PM] Profile | Notification Settings | Updates to edit mobile phone number flow: Submit collab cycle request #

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#57820]
## Tasks
- [ ] Gather materials for kick-off - write project outline
- [ ] Submit kick-off ticket
- [ ] Perform any follow-up items from kick-off

## Acceptance Criteria
- Kick-off is submitted and completed

**Comment by andaleliz** [comment]
Hi Travis! [Here's the user flow for editing profile information as a sub-task](https://www.sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d/p/293F15EA-9CCC-466C-A3B7-3E54E3111676/canvas). This feature can work with any piece of profile information, and mobile number is the first use case we have for it.
