### ISSUE TITLE
HLR | Replace wizard with subtask

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#57821]
## Value Statement
**_As a_** Veteran with accessibility needs that is filing a higher-level review
**_I want to_** file using the latest enhancements to the frontend experience
**_So that_** I can benefit from accessibility and other design updates. 

---
## Background Context

The wizard (on the `/start` page) is a deprecated pattern. We need to update it to the subtask pattern that shows one question per page. In order to do this, we need to update our design & content to 

## Acceptance Criteria
- [x] All tasks complete
- [x] All tests passing
- [x] User can toggle additional information component to answer 'What are other decision review options?' Content matching design.
- [x] User can select Disability compensation claim or A claim other than disability claim
- [x] If user selects Disability compensation claim and hits continue, they are directed to the introduction of the HLR form.
- [x] If the user selects A claim other than disability claim and hits continue, they are directed to non-disability content where they can navigate to find an address for mailing their form, and download a PDF of the form.

## Designs and Build Notes
- [FIGMA](https://www.figma.com/file/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?type=design&node-id=0-43&mode=design&t=ilOaZNuLOnAOWBcC-0) Labeled with Proposed and Error on that page
- [CSoT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/higher-level-review/design/content-source-of-truth.md)
- The subtask maintains the same `H1` as the form
- Unique `H2` that includes the main question for that subtask page
- Match subtask content to the subtask page

## Out of scope
- Add here

## Open questions
- Any change to OMB privacy policy text?
- Remove AMA opt-in checkbox?

## Tasks
- [x] Update design & content for subtask
- [x] Subtask replaces wizard to show one question per page
- [x] Replace plain `<button>` with `<va-button>` as needed
- [x] Unit tests updated
- [x] e2e tests updated

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
![Screenshot 2024-04-12 at 10 43 51 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/111457818/2f31e344-f61a-496f-b235-e3691f29122a)

@Mottie The back button is too close to the inline link.

Is the Need Help? missing because of #77946

**Comment by Mottie** [comment]
Hmmm, those are problems. I'll get it fixed ASAP!

**Comment by Mottie** [comment]
This can be rechecked in staging

**Comment by eileen-coforma** [comment]
The Need Help is back 👍 

The back button is still missing a top margin.

**Comment by Mottie** [comment]
Ugh, I just noticed that... it looks fine locally...

**Comment by eileen-coforma** [comment]
![Screenshot 2024-04-16 at 3 03 45 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/111457818/0dd20a64-01c2-43d5-b279-9b317a61f22c)

@Mottie Minor thing I didn't catch earlier. It should say 'What type of claim are you requesting a Higher-Level Review for?' It's missing the for.

**Comment by Mottie** [comment]
I've merged in that start page title fix, it won't be available in staging right away.

**Comment by eileen-coforma** [comment]
@jstrothman this is the deprecated wizard replacement work I mentioned before. It has the same content as the wizard, just separated into two subtask pages (following the pattern we use for Supplemental Claims).

**Comment by eileen-coforma** [comment]
Validated.
