### ISSUE TITLE
[eFSR] Add item / summary page navigation bug

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#57846]
## Issue Description
Found bug with mini summary page adding additional items after list has been emptied. 
Potential affected pages (may not be comprehensive list): 
- Utilities
- Assets
- Additional income
- Expenses

### Steps to reproduce:
1. Checklist page - Use checklist to add items, click continue
2. Input list page - Use input list to include values, click continue
3. Summary page - Use delete functionality to remove all items in list, click add new <item>
4. Add <item> page - use form nav buttons to cancel or continue 
   - Note: should kick to form start from trying to access hidden page.

This is likely caused by the `depends` on the summary page checking the length of the <item> array and trying to navigate back to it once it's empty. 

---
## Tasks
- [ ] Identify root cause of issue
- [ ] Update add <item> navigation and maybe `depends` on summary page to resolve issue

## Acceptance Criteria
- [ ] Form no longer break when navigating away from add <item> page when list is empty. 

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
Found issue with page not updating correctly after chatting with Rob it looks like a forms system issue. He mentioned making a change to how `setFormData` works that could help! 
[Link to convo](https://dsva.slack.com/archives/C5HP4GN3F/p1684870222202999)

**Comment by Dr-Pongo** [comment]
Including new `returnUrl` functionality [provided by Rob](https://github.com/department-of-veterans-affairs/vets-website/pull/24343) to help with save in progress nav when returning to the form. Also fixed some other similar nav issues that popped up
