### ISSUE TITLE
Discovery - EVSS to Lighthouse Migration - submit endpoint

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#57859]
## Issue Description
What would it take to migrate this endpoint?
-- what data field(s) are being sent and received from the eVSS endpoint by the 526 form?
-- what is the endpoint in existence in LH that replaces this service?
-- what data field(s) are being sent and received from the new LH endpoint?
-- can form 526 switch to this LH endpoint without changes for this service?
-- what is the data structure vets-api is expecting from eVSS?
--- does data structure LH has in their documentation adhere to that contract?
In vets-api, is this service being used?
What is the workflow from form 526?
-- If there is more than one endpoint being utilized, do we need separate tickets to capture that work? How complex is it?
Can our new framework handle the migration?
-- Can we abstract out eVSS calls?
-- Can the responses from both eVSS and LH be genericized?
At the conclusion of this discovery, information should be shared out to engineering team
-- We should be able to answer the question: Are we confident in taking on the implementation of the migration?

---
## Tasks
- [ ] review submit form526 lighthouse schema https://dev-developer.va.gov/explore/benefits/docs/claims?version=current
- [ ] review vets-api form526 submit schema
- [ ] question: can an "optional" attribute _**not**_ be sent?
- [ ] question: if an optional attribute is on the `formData` sent to lighthouse, can it be `null`?
- [ ] question: should we just not send the "optional" attribute at all if there is no form data

## Acceptance Criteria
- [ ] Answer to the questions in the description
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sethdarragile6** [comment]
Little progress check-in. I've been creating [this diagram](https://lucid.app/lucidchart/b93a0b4d-c62b-49b0-8efc-c7e9e4a05d1c/edit?viewport_loc=1258%2C2345%2C2466%2C1172%2C0_0&invitationId=inv_a7c98577-e6f5-4ec2-897b-3b0f6212b08d) as I'm going through the existing 526 submission workflow. It's not complete, and in the interests of time I may stop before I _fully_ flesh things out in the detail I've gone into so far. There is an explosion of translation calls right as you reach the end of the call chain, and most of them are simply running business logic on the JSON of the input form to build the _output_ JSON that will be submitted. Lots of great info in there that will be key in understanding exactly what we're now submitting (and will be passing on to Lighthouse. 

But one of the main points of this exercise (besides just getting an understanding) is to see what other API calls might need to be migrated along the way. The "good" news is that there seems to be only [one](https://github.com/department-of-veterans-affairs/vets-api/blob/d30b00ad5be37d43edb2720442e3cb1aff1228aa/lib/evss/disability_compensation_form/data_translation_all_claim.rb#L119): to the **PPIU service**, which stands for "Personal Payment Information (Update)" (thanks, wtf-bot). We call out to its `/paymentInformation` endpoint to grab the user's bank account information if it hasn't already been included- which is [entirely based](https://github.com/department-of-veterans-affairs/vets-api/blob/d30b00ad5be37d43edb2720442e3cb1aff1228aa/lib/evss/disability_compensation_form/data_translation_all_claim.rb#L101) on the presence (or lack thereof) of banking information submitted from the form.

If there's not an existing/related ticket for this particular service migration, I'll create one- depending on whether or not it ends up making more sense to migrate it during the course of the actual submit endpoint.

FYI CC: @RakshindaAslam @ahay-agile6

**Comment by sethdarragile6** [comment]
Created these 3 tickets for PPIU migration:

- [#59695](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/59695) EVSS Migration - PPIU migration: Abstract references to EVSS::PPIU::Service
- [#59698](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/59698) Migrate GET call to /paymentInformation to Lighthouse
- [#59702](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/59702) Migrate POST call to /paymentInformation to Lighthouse

**Comment by sethdarragile6** [comment]
Created this [526 Submit Endpoint Discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/evss-to-lighthouse-migration/526-submit-discovery.md) doc, moved to Review. Other new docs it references:
- [526 Submit Questions for EVSS/LH](https://docs.google.com/document/d/1Z6Cw6MU5fgsjeJ9vuqrk-4xMEkq3LpQ7NbKUq0KNAyk/edit?usp=sharing)
- [EVSS/LH Mapping worksheet](https://docs.google.com/spreadsheets/d/1e_UoLN31Uzr9_aG4ByCcuQm3kIq844cg_l0IBJYnfLE/edit?usp=sharing)

**Comment by sethdarragile6** [comment]
- Created all the basic stories, filled them out with docs/examples and open questions that relate to each one
- Outlined them in a [Development Plan](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/57859) section of the wiki page
- Moved the remaining questions from the OG question doc to a question doc for [EVSS ](https://docs.google.com/document/d/1a8rvnlzUfEkE5j_DwTvNK-Q78N3FQcnXxPsVs7QimJk/edit?usp=sharing)and one for [LH engineering](https://docs.google.com/document/d/1KEMStn7GDZc4Qs1xHHODMrd8il5TeaYjPYNDWxVm4zA/edit?usp=sharing)
- Posted those over [here](https://dsva.slack.com/archives/C02CQP3RFFX/p1689033999469669?thread_ts=1688410338.910259&cid=C02CQP3RFFX)
