### ISSUE TITLE
[FE] 10-10CG - Facility page: Create connection from search input to MapBox API Client

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#57860]
## Background
**Must complete this ticket prior to working on #61786**
To improve the Facility Selection experience, we are implementing new functionality to allow users to input their city, state or postal code and get a list of results from which they can choose. In order to successfully query the Lighthouse API using the provided data from the search input (city, state and/or postal code) we need to connect to the MapBox API client. The result from that MapBox API request will be a set of boundary coordinates that we will then use in the API request to Lighthouse.

**NOTE:** Consult the `facility-locator` app  in `vets-website` for their implementation of the MapBox client. You may also seek any help or references from the Facilities team in their DSVA slack channel (`#sitewide-facilities`).

**NOTE:** Consult "API Keys" section of the README.md file in `vets-website` for instructions on obtaining access tokens and setting up local environment variables for testing.

### Resources
- [Initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/Improve%20Facility%20Selection/Improve%20Facility%20Selection%20-%20Initiative%20Brief.md)
- [MapBox API docs](https://docs.mapbox.com/)

## Tasks
- [x] Work with PM to obtain access token for MapBox connection
- [x] Create MapBox client and set up all necessary actions
- [x] Test connection to ensure proper coordinates are being returned
- [x] Ensure all work is implemented behind feature flag and not being ran in production

## Acceptance Criteria
- Connection is successfully established to MapBox client and bounding coordinates are returned.
