### ISSUE TITLE
Build Out and Refine Mockups/Prototypes for 686 Usability Pilot

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#5786]
## Goal
To facilitate the 686 usability-testing sessions, we want to create form workflows that approximate an authentic VA.gov user experience. This will assist the team in making informed decisions on how how to proceed with development, and  how to improve the application for Veterans.

## Tasks
- [x] Create functional prototype simulating the "add-spouse/add-child" workflow
- [x] Create functional prototype simulating the "remove stepchild" workflow
- [x] Create functional prototype simulating the "add-student" workflow
- [x] Create functional prototype simulating the "remove-student" workflow

## Acceptance Criteria
- [x] Mockups and prototypes are prepared ahead of usability session
- [x] Schedule meeting with session facilitator to walk-through prototypes
- [x] Incorporate any changes/feedback into prototypes

**Comment by sporeboy** [comment]
Prototype is functional and ready to present to participant of usability study. Incremental functionality added as study progresses. Some clarification in text ongoing. XD doc here:  https://xd.adobe.com/view/fef8a415-74b4-45a9-6b5f-da956acd75d9-88c9/?fullscreen

Prototype has the latest , most up-to-date revisions.
