### ISSUE TITLE
Add step indicator to DS Playground

### ISSUE THREAD

**Issue by powellkerry** [department-of-veterans-affairs/va.gov-team#57875]
## Description
In order to demonstrate compatibility between v1 and v3 components when loaded on the same page, the step indicator component (va-segmented-progress-bar) should be added to the DS Playground's "V1 and V3 Side-by-Side Demo" page.

V3 Variations to show:
- No labels (default)
- Left aligned labels (supply value for labels prop)
- Center aligned labels (supply value for labels prop and centeredLabels: true)
- Counters, labels aligned left (supply value for labels prop, counters: "default")
- Counters, labels center aligned (supply value for labels prop, centeredLabels: true, counters: "default")
- Small counters, labels aligned left (supply value for labels prop, counters: "small")
- Small counters, labels center aligned (supply value for labels prop, centeredLabels: true, counters: "small")

## Tasks
- [ ] Add the va-segmented-progress-bar to the V1 and V3 sides of the demo page (vets-website repo)
- [ ] Add 'current' and 'total' props, and modifiers to demonstrate variations of V3 component
- [ ] Add/modify appropriate formation overrides within the component-library repo (if needed)
- [ ] Verify that all styles render correctly

## Acceptance Criteria
- [ ] The V1-compatible and V3-compatible versions of this component render correctly and function correctly when loaded simultaneously within the DS Playground app.

**Comment by caw310** [comment]
This will carry over into sprint 28 as review is not yet done.
