### ISSUE TITLE
Crosslinking recommendations for EDU benefits comparison page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#57870]
## Issue Description

We need to recommend crosslinking opportunities within the Careers hub to the new R&S [Compare VA education benefits](http://preview-prod.vfs.va.gov/preview?nodeId=5575) page that we are migrating. VA stakeholders would like to raise visibility of this page. 

Currently, we link to the legacy page on the [Eligibility for Veteran Readiness and Employment](https://www.va.gov/careers-employment/vocational-rehabilitation/eligibility/) page.

Other suggestions:
In the left nav in the Careers hub, under More resources
On the hub landing page under More helpful resources

## Tasks
- [x] Determine crosslinking opportunities (Jenny)
- [x] Set up ticket to add crosslinks once page is live (Randi)

## Acceptance Criteria
- [x] We've determined where to crosslink and set up a ticket for implementation

**Comment by jennymayoco** [comment]
Hi @RLHecht! Here are the crosslinking recommendations for the new modernized EDU benefits page. Happy to chat if you have any questions.

### 1. [Careers and employment hub page](https://www.va.gov/careers-employment/)
<img width="400" alt="Screenshot 2023-06-02 at 2 02 38 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/122128479/7a9322bb-8c1e-40f8-8d9b-9e13ab1fb726">


#### Notes
We are suggesting adding this to the top of the "More information and resources" list for highest visibility.

----
### 2. Careers and employment left nav
<img width="400" alt="Screenshot 2023-06-02 at 2 15 19 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/122128479/b0da0ecf-10f4-401a-9a39-be701f4c5c13">

#### Notes
Same as above -- add to the top of "More resources" list in the left nav.

----
### 3. [Veteran Readiness and Employment (Chapter 31) page](https://www.va.gov/careers-employment/vocational-rehabilitation/)
<img width="400" alt="Screenshot 2023-06-02 at 2 24 27 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/122128479/198d1a2f-f5a3-408e-b8bb-5f6475f385e8">

#### Notes
Since Veterans can only apply to one program at a time, we believe it's important that the EDU benefits comparison page is towards the top so Veterans are able to make a decision that best fits them prior to applying. We realize that VR&E and eligibility may take precedence, so recommend as the third option.

----
### 4. [Eligibility for Veteran Readiness and Employment page](https://www.va.gov/careers-employment/vocational-rehabilitation/eligibility/)
<img width="400" alt="Screenshot 2023-06-02 at 2 20 53 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/122128479/515ef7cd-7c72-4bfa-a850-8ce1126c8b26">

#### Notes
Update "Compare VA education benefits" link to redirect to new modernized page.

----
### 5. [About GI Bill Benefits page](https://www.va.gov/education/about-gi-bill-benefits/)
<img width="500" alt="Screenshot 2023-06-02 at 2 30 59 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/122128479/2feef316-75ba-4099-b6be-55727ca01c42">

#### Notes
We recommend adding a link to the EDU benefits comparison page under the section "Benefit rates and ways you can use your benefits" and below the "Rates" link that way Veterans see this right below Post 9/11 benefits section if they don't continue to scroll down the page. Happy to follow the Content team's lead on this one though!

----
### 6. [Post-9/11 GI Bill (Chapter 33) page](https://www.va.gov/education/about-gi-bill-benefits/post-9-11/)
<img width="400" alt="Screenshot 2023-06-02 at 2 42 27 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/122128479/5e62bcfe-6196-4925-969a-35e8f57eb724">

#### Notes
Add link in section "What if I qualify for other VA education benefits too?"

----
### 7. [Montgomery GI Bill Active Duty (MGIB-AD) page](https://www.va.gov/education/about-gi-bill-benefits/montgomery-active-duty/)
<img width="400" alt="Screenshot 2023-06-02 at 2 43 19 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/122128479/de2a2a8e-cab8-433b-92f0-146b7476ea1c">

#### Notes
Add link in section "What if I qualify for other VA education benefits too?"

----
### 8. [Montgomery GI Bill Selected Reserve (MGIB-SR) page](https://www.va.gov/education/about-gi-bill-benefits/montgomery-selected-reserve/)
<img width="400" alt="Screenshot 2023-06-02 at 2 44 39 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/122128479/ab3b845f-5dbb-47b8-a7fb-b59a7785fccf">

#### Notes
Add link in section "Can I qualify for more than one VA education benefit?" The title for this one follows a bit of a different pattern than the two above, would it make sense to update so it's a cohesive experience between all three?

**Comment by RLHecht** [comment]
Thanks so much @jennymayoco Going to close this out and set up a new ticket for implementation.

**Comment by jennymayoco** [comment]
Hi @RLHecht! I made some edits to the original comment with updates

- Careers hub page and left nav: moved the entry point as the second option below rates
- Added entry points in the education hub page and left nav. I also noted that the order in the hub page differs a bit from  the left nav
- Updated VR&E page with a recommendation to add a link in the "more helpful resources" section
- Updated GI Bill benefits page with a recommendation to add a link in the section "More GI Bill benefits and information"

Let me know if you have any questions!

**Comment by mnorthuis** [comment]
Hi, just 2 minor tweaks:
3) Education hub page - Place it below the "Find a Yellow Ribbon School" option.  For whatever reason this order is different than the left nav, but the 2 school/benefit tools and the rates should be first in the list, and this 4th. We will correct the overall order when we get to this hub in our audits.
7) About GI Bill benefits page - move it one more down, below Tutorial assistance.  That leaves all of the ways you can utilize your education benefits at the top of the list, then this resource for selecting a benefit, then the 2 other tools at the bottom. 

Thank you!
