### ISSUE TITLE
Resolve plugin-traefik-real-ip issues.

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#57872]
The current Traefik version, used in vets-api, depends on the plugin [traefik-real-ip](github.com/soulbalz/traefik-real-ip/) to resolve IP issues. From the plugin readme, `This plugin solves this issue by overwriting the X-Real-Ip with an IP from the X-Forwarded-For or Cf-Connecting-Ip (if from Cloudflare) header. The real IP will be the first one that is not included in any of the CIDRs passed as the ExcludedNets parameter. The evaluation of the X-Forwarded-For or Cf-Connecting-Ip (if from Cloudflare) IPs will go from the last to the first one.`

This plugin has been throwing this error `plugins-local/src/github.com/soulbalz/traefik-real-ip/real_ip.go:55:18: panic`. The plugin repo was archived in Dec 2022. 

Updating Traefik might resolve this issue. 

## Tasks
- [ ] Research the panic issue, found in these [Datadog Logs](https://vagov.ddog-gov.com/logs?query=service%3Atraefik%20%22plugins-local%2Fsrc%2Fgithub.com%2Fsoulbalz%2Ftraefik-real-ip%2Freal_ip.go%22%20env%3Aeks-prod%20&cols=host%2Cservice&event=AgAAAYdY2dpEE05RAQAAAAAAAAAYAAAAAEFZZFkyZXlRQUFCRG9JSTJMX0FSS0FBRQAAACQAAAAAMDE4NzU4ZTEtYTE5Yi00OTZiLTg2YWItMjQzY2M0MjlhOGVj&index=%2A&messageDisplay=inline&stream_sort=time%2Casc&viz=stream&from_ts=1680783496012&to_ts=1680896508194&live=false)
- [ ] Research the real IP issue to see when Traefik was able to provide Real IP forwarding without a plugin
- [ ] Research any modifications needs when upgrading (if Traefik needs to be updated)

**Comment by laineymajor** [comment]
Find a new middleware tool that we can adopt

**Comment by RachalCassity** [comment]
Research this plugin: https://github.com/Paxxs/traefik-get-real-ip

**Comment by RachalCassity** [comment]
Researched traefik-get-real-ip and there is quite some modifications to make. During high traffic, the traefik-real-ip sends a panic signal. This ticket is being passed to the devops cop.

**Comment by LindseySaari** [comment]
@ph-One Could you take a look at this as you make adjustments to the scaling buffer please?
