### ISSUE TITLE
Add Rated Disabilities to the Mega-Menu on VA.gov

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#5787]
## Story
As a Veteran, I want relevant pages displayed closer to the top of my navigation experience so I can more easily get to features that are meaningful to my browsing session.

## Goal
Document and define how features are added and displayed in the mega-menu on VA.gov

## Tasks
- [x] Schedule a meeting with IA to ask:
  - How are features added to the mega-menu, if not automatically added from interior hub specific menus
  - Determine if a mockup needs to be created
- [ ] ~Implement the recommended procedures per Mikki~
  - This is not automated but hand selected and only the top 5 tasks are shown.
- [x] Document in our launch checklist as a step to address before launch

## Acceptance Criteria
❌ The Rated Disabilities link has been added to the mega-menu
- [x] Procedures are captured here in the [launch checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/launch-playbook/checklist.md)
