### ISSUE TITLE
Complete 526 sitemap

### ISSUE THREAD

**Issue by lydiahooper** [department-of-veterans-affairs/va.gov-team#57880]
##Issue Description
Site map needs to be completed (missing some Original Claim pieces, National-Guard specific info, and the PTSD flow) and updated with the flow changes in process. May also consider adding color coding or symbols to clearly indicate different flows. Once we have this updated, it can be used to request that analytics team update/add flows in Domo dashboard (for Original Claim and BDD, at minimum).

## Need to know
Flow documented in MURAL: 
Original: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1680211466282/0b44cead253b62f1fde2dbed4a83a1345764b56d?wid=8-1682631266214

Active Flow (VA Mural): https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686768383603/3f4415dd2ddb71bbd104ebefd92a2c7b553ad792?invited=true&sender=u813bb40bd648bc2b58599242

There are 2 flows in MURAL — a detailed flow with screenshots, and a summary flow. On big yellow sticky notes are marked where we are missing some parts of the flow (some Original Claim pieces, National-Guard specific info, and the PTSD flow). Black stickies note where changes are expected to be made to the flow.

Note: there are some screenshots in this Sketch folder: https://www.sketch.com/s/6eb1ff1a-38a5-4e15-9ff8-5ba91c800839

Sketch file showing flow changes: https://sketch.com/s/c3ee9ba8-f268-46dc-a870-194e99bed37e

Slack thread with numbered order of coming changes: https://dsva.slack.com/archives/C053UDWMH7U/p1685478887446579

Google sheet with current URLs (gaps are noted in sheet): https://docs.google.com/spreadsheets/d/1Bi65N54v2yKCFFR42aStk3SGHBXlHDOCNbchKHb8ddg/edit?usp=sharing

## Tasks
- [ ] 

## Acceptance Criteria
- [x] Updated with missing flows 
- [x] Updated based on flow changes being made 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nnicholas7** [comment]
- Updated the flow with PTSD and Reserve SubFlows and validated the entire flow
- Next steps (6/15/23): Chat with Team 2 to validate and add any additional pieces
- Needs some design help (formatting)

**Comment by austinjprice** [comment]
@juliepedtke @nnicholas7 @RakshindaAslam @lydiahooper we created a separate ticket to continue this work, but lets discuss to before closing or we should merge back as one ticket. New ticket:

https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/60716
