### ISSUE TITLE
Identity Dashboard FE - Create Getting Started page

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#57886]
## Description
Using the Design assets (Figma) link below, create the Getting Started page (authenticated)

## Design Review
https://www.figma.com/file/NgTUQowdoP3TsasZTHiwpu/Identity-Dashboard-(views)?node-id=0%3A1&t=I9pcazLJSWhj2rCA-1

## Tasks
- [x] Using Next.js create a page for the Getting Started page (authenticated)
  - [x] Invite team Action link (goes to Teams page)
  - [x] "Adding team members" and "identity documention" and "Learn more" will navigate to external documentation site (empty href)
  - [x] Create application button should Navigate to Application page
  - [x] Sign out link should do nothing (yet)
- [x] Create the sidebar
  - [x] Add internal links/pages for Getting Started, Applications, Teams, and Monitoring
  - [x] Links to (external) documentation can have empty hrefs
- [x] Render the Getting Started page using conditional routing
  - [x] Reorganize the landing page under this new layout
- [x] Write tests for the above

**Comment by aparsley** [comment]
Looks great, thank you for attaching the Getting Started Figma Page.
