### ISSUE TITLE
Identity Dashboard FE - Create landing page

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#57885]
## Description
Using the Design assets (Figma) link below, create the Landing page for the Identity dashboard

## Design Review
https://www.figma.com/file/NgTUQowdoP3TsasZTHiwpu/Identity-Dashboard-(views)?node-id=0%3A1&t=I9pcazLJSWhj2rCA-1

## Tasks
- [x] Using Next.js create a page for the Landing page (unauthenticated)
  - [x] Any links referencing documentation can have an empty href
  - [x] Sign in button does not need to be functional, use Login.gov logo similar to Sign in Modal on vets-website
  - [x] Add "US government site header" (reference developer.va.gov or design.va.gov)
  - [x] Add "Veteran crisis line" (reference developer.va.gov or design.va.gov)
- [x] Create footer (reference developer.va.gov)
  - [x] Add VA image crest
  - [x] Add links (same links, again reference developer.va.gov)
  - [x] Add link to documentation + Github repo link
