### ISSUE TITLE
Identity dashboard FE - Setup testing strategy

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#57892]
## Description
Set up a modern test runner to run unit tests (Vitest or Jest)

## Tasks
- [x] Set up a test runner (either Vitest or Jest) for Identity dashboard
- [x] Create `scripts` in the `package.json` to run all tests
- [x] Update README.me
 - [x] Create testing section + usage on how to run tests
