### ISSUE TITLE
Develop a Qualtrics survey for the campaign page

### ISSUE THREAD

**Issue by tygindraux** [department-of-veterans-affairs/va.gov-team#57890]
## Description
Now that our campaign landing page is live we should create a Qualtrics survey to capture baseline data

## Acceptance criteria
- [ ] Qualtrics survey is ready to capture data

## Tasks
- [ ] find out if there are limitations using Qualtrics with Drupal
- [ ] come up with questions for the survey
- [ ] develop a strategy for how often users will receive the survey and through what means (feedback button, embedded feedback, ...)

## Related Tasks
how are comments (on blogs, for example) responded to
there might be time window for when you can reply to

tie to other tickets too
