### ISSUE TITLE
[Pattern] Help users to stay informed of their application status

### ISSUE THREAD

**Issue by taylojill** [department-of-veterans-affairs/va.gov-team#57899]

**Comment by taylojill** [comment]
## Description
This work comes from issue #1594 and follows the audit completed in #1128. Mural audit is [here](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1661355714382/20b034bd9720885de162064c435f5a86f4222449?sender=u5eae0d4aded4157ec73a9247).

The audit uncovered several ways that Veterans/caregivers are informed of an application status update:
1. Status update on the intro page of the form they completed (Healthcare 10-10EZ).
2. Update in the Claims Status Tool (CST).
3. Certificate of Eligibility (letters).

There is no one size fits all solution, but we can help teams get on the same page by sharing what is out there today and detailing what the limitations are. This has been done with the Ask users for multiple responses pattern (list and loop), and that has resulted in greater clarity. 

## Tasks
- [ ] Capture screenshot examples.
- [ ] Write documentation for design.va.gov
- [ ] Request documentation draft review.
- [ ] Once documentation is approved, publish to design.va.gov

## Acceptance Criteria
- [ ] Pattern documentation is updated on design.va.gov

**Comment by caw310** [comment]
Will be two sprints work

**Comment by taylojill** [comment]
Added step to document process for writing patterns.

**Comment by humancompanion-usds** [comment]
I've updated and released the pattern. I messaged @allison0034 and @taylojill on Slack to work together to capture a claim status in MyVA.
