### ISSUE TITLE
[Design] MDT- Veteran contact details - v2

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5789]
## User story:  
As a veteran, I need to be able to see that my personal information as the first step so that I can confirm my information is correct.

## Tasks:
- Incorporate the following feedback from VSP into the contact details screens:
   - Stack the address form fields
   - Lengthen the State dropdown component and indicate that full state names will be displayed 
   - Label all required fields 
   - Add helper text for Address line 2  

## Acceptance criteria:
- [x] Mockup aligns with VA.gov’s design system
- [x] The screen’s initial focus is incorporated
- [x] Sketch artboards are uploaded to Invision and linked in this ticket as a comment

**Comment by rileyorr** [comment]
The following screens have been updated in the Invision prototype: 
[Contact info - Prefilled](https://vsateams.invisionapp.com/share/Q7VVWGZUG4N) | [Contact info - manually entered](https://vsateams.invisionapp.com/share/RJVXC02MS3W) | [Contact info - Email manually entered](https://vsateams.invisionapp.com/share/JVVXCA1W3GA)

@mojaray2k & @mr0sari0 The following changes have been made:
- Address form fields are now stacked
- The _State_ dropdown has been lengthened so the full state name can be displayed; the previous design accounted for state abbreviations to be displayed but Trevor indicated that full state names would be more advantageous for accessibility 
- All required fields are labeled while all optional fields are not; this may automatically be implemented in the coded components 
- Address field labels have been updated to _Street address line 1_ and _Street address line 2_
- _Street address line 2_ has supporting content _(Apartment, building, suite, etc.)_

I can definitely meet to walk through these updates if you'd like! :)

**Comment by mojaray2k** [comment]
@rileyorr I just want to know. I see 3 address screens. But really there is just one correct?

**Comment by rileyorr** [comment]
@mojaray2k Correct! The three address screens linked are just various possible states of that one address screen. 
The tickets for those screens are:
- #5165 
- #5168 
- #5166 
- #5162 
- #5167
