### ISSUE TITLE
Identity dashboard FE - Setup roles and authorization

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#57895]
## Description
Set up roles and authorization for the Identity dashboard

## Tasks
- [ ] Work with BE (Trevor, John, or Riley) to implement authorization to the Identity dashboard
- [ ] Set up team-based authorization
  - [ ] A user cannot (CRUD) any applications or teams that they do not belong to
  - [ ] A user should see a 401 Unauthorized page if they try to access another team
  - [ ] A user should see a 401 Unauthorized page if they try to access another application
  - [ ] A user should see a 401 Unauthorized page if they try to access any resource not belonging to their team

**Comment by ianmagenta** [comment]
Closing this because the IDD is no longer being worked on.
