### ISSUE TITLE
Identity dashboard FE - Set up authentication

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#57891]
## Description
Conduct Authentication Research/Proof of Concept for NextAuth to see if it will work for us

## Tasks
- [ ] Research authentication to our Sign in Service
  - [ ] Possibly use NextAuth.js :shrug: 
  - [ ] Create a Proof of Concept (time limit of 1 week)
     - [ ] If we can't get it working, we will get Identity SDK up and running

**Comment by acald-creator** [comment]
Researching NextAuth.js

Will work on creating some mocked authentication from the current Figma diagram for now. Will change as goes by.

**Comment by acald-creator** [comment]
Created branch to work on this https://github.com/department-of-veterans-affairs/identity-dashboard-fe/tree/feat/nextauth

**Comment by acald-creator** [comment]
unassigned, @asg5704 is working issue #59142, which sets up authentication to utilize sign in service
