### ISSUE TITLE
[AFTER RESEARCH] [SPIKE] Do we use dismissible alerts or not? 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#57894]
## Tasks

- [x] How does the dismissible alert work? Does it have to explicitly get dismissed even after a session? 
- [x] If it's not a dismissible alerts, when do we want the alert to go away? (Note: this impacts the decision on whether alerts should include the appointment date & time vs. saying "for this appointment." 
- [ ] Run answers by FE
- [x] Create f/u ticket to update alerts and/or annotations in sketch 

## AC

- [x] Decision is known 
- [x] F/u tickets created

**Comment by cgednalske** [comment]
@benbrasso-agile6 Whenever someone works on this, here's the initial discovery and recommendations I mentioned that I started back when we had this ticket in a sprint for a bit but then removed it. Because things have changed a bit, it might not be accounting for everything we know now about the unified setup. 

### Initial Recommendation: 
Leave as dismissible. Add in the date to the information to clarify context. 

### DS Guidance:

- Dismissible if we want the Veteran to dismiss it
- Not dismissible if we want to decide when it disappears

Following our current content, the alert should not be dismissible. However, we can decide to have it either way. The main concern is likely that the content included should, regardless, be tailored to clarify the appointment the alert is referring to.

Also looked at MyVA's research for their notifications/alerts - they ended up with dismissible notifications. And the info included in theirs is very important.

### Discovery questions:
**Where is the alert there?**
The Veteran needs to know the result of that action. Ex: link is expired for that appointment.

**How long do they need to see this?** 
Until they understand the result of that action, following actions will take priority. After which they would move on to something else.

**How do we know when they've moved on to something else?**
When they go to a different page or refresh or when they dismiss the alert (would signify they - in theory - have read it)

**Is there any research showing Veterans have trouble with dismissible alerts?**
Not that I know of, but we know there is alert fatigue. Dismissible alert could help with that by allowing them to have an extra alert go away on their own terms.

Alerts takes up lots of space on mobile. If not dismissible, the Veteran would be seeing this on their whole screen possibly longer than needed.

**Does having the alert linger provide added benefit?**

- Not if the Veteran has moved on to something else.
- Yes if the Veteran is still wondering about that appointment.
- Dismissible allows for both of these.

(The information is only important as long as they need to see it. It is difficult for us to know when they no longer need that information.)

**If the Veteran opens the same link again, would the alert appear again?**
Unsure - something to discuss with engineering

**Is there anything the Veteran needs to do that the alert tells them about?**
No, no direct actions to take for any of these default alerts. Any important info is in the list or details page.

**Are we interested in tailoring the content to each appointment?** 
This is more work for UX, content, and FE, but may be necessary regardless, as having the appointment info would help Veterans remember what appointment they came there looking for - which is not provided anywhere on the page. So this probably needs to change regardless. 

If we do not end up tailoring the appointment info in the alert, the alert should not be dismissible, and we should have it disappear on refresh or after navigating somewhere else. 

If we need it to be dismissible, then it must be tailored to the specific link.

**Comment by cgednalske** [comment]
@ben @zach and I met to discuss this and landed on keep this as a dismissible alert. 

**Decision details:**
- Leave the dismissible alert there until the Veteran has closed it or their session has ended 
- Add in appointment details to provide more context
- We don't "carry over" dismissible alerts from other appointments because each alert is specific to the text message and UUID

**Action items:** 

- @zach-park is going to make some quick updates to the content: "The link you visited for your appointment on [Monday, February 2, 8:00 a.m.] has expired. When it's time…."
- @benbrasso-agile6 will add annotation for the logic listed above

**Comment by benbrasso-agile6** [comment]
Zach's work is validated

**Comment by benbrasso-agile6** [comment]
Added to Design page in unified file

1) Dismissible warning alert components can be dimissed. Veterans can nagivate to other pages within pre-check-in or check-in before dismissing the alert. If/when returning back to the appointment list page, the dismissible warning alert should still appear until dismissed. 
2) If a Veteran dismisses the warning alert, ends their session, then selects the same UUID link on a different date, then the dismissible warning alert should appear (to give the user some feedback). 3) Because they are associated with a specific UUID, a warning alert, if not dismissed during a session, should not appear for a different UUID session. 

https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/0EC89917-F949-4461-A7B3-32A5201FD2A2/canvas

^ Review then close this ticket out @cgednalske

**Comment by cgednalske** [comment]
@benbrasso-agile6 Looks good! 👍 Closing this out.
