### ISSUE TITLE
[Design] MDT- Veteran contact details - error handling, v1

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5791]
## Tasks:
- Document error message content for possible error states 
- Create a high fidelity mockup to depict how an error state on the contact information page should be stylized
- Upload export to Invision and indicate initial focus point as a comment

## Acceptance criteria:
- [x] Error state messages are documented and attached to this ticket
- [x] Mockup aligns with VA.gov’s design system
- [x] The screen’s initial focus is incorporated
- [x] Sketch artboards are uploaded to Invision and linked in this ticket as a comment

**Comment by rileyorr** [comment]
Prototype: [Desktop](https://vsateams.invisionapp.com/share/CMW1O5S9ZQN)

Possible error messages: 
**Country**
* _There shouldn’t need to be an error message because they will automatically have United States selected - referencing 10-10CG_
**Street address line 1**
* Please enter a street address (User presses Continue button without entering an address)
* Please enter a street address (User selects and deselects text input box with no input value)
**City**
* Please enter a city (User presses Continue button without entering a city)
* Please enter a city (User selects and deselects text input box with no input value)
**State**
* Please select a state (User presses Continue button without selecting a state)
* Please select a state (User selects and deselects dropdown with no state selected)
**Postal code**
* Please enter a zip code (User presses Continue button without entering an address)
* Please enter a zip code (User selects and deselects text input box with no input value)
* Please enter a valid zip code (User types less than 5 digit postal code or more than 5 digit postal code with United States selected for country) 

I added a comment with the initial focus point, but I'll post it here as well:
Initial focus point depends on the action the user is taking. For example, if a user selects & deselects “Street address line 1”, then the focus would be on “Street address line 2”. We need to double-check with the Accessibility team to determine where the focus point would be if a user attempted to proceed to the next screen without completing all required fields. 

@mojaray2k & @mr0sari0 let me know if you'd like to sync to discuss or reach out to me if you have any questions! :)
