### ISSUE TITLE
[Congressional] V10134537 Due 6/5/2023

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#57928]
## Issue Description
Veteran is having log in issues with VA.gov. Technical support was unable to resolve the constituent's issue, and asking what's the next step to helping resolve this issue.

Due Date: June 5, 2023

https://dvagov.sharepoint.com/:f:/s/DigitalExperiencePMOInternalFTC-PrivateOCTO-DEActions/EuNRrlIqJ4JNj3RlwOz2qSoBHHRqqe65l_tWtkNzkzihDA?e=eYSxZk

---
## Tasks
- [x] [Review congressional correspondence](https://dvagov.sharepoint.com/:f:/s/DigitalExperiencePMOInternalFTC-PrivateOCTO-DEActions/EuNRrlIqJ4JNj3RlwOz2qSoBHHRqqe65l_tWtkNzkzihDA?e=eYSxZk)
- [x] Resolve issue
- [x] Notify Veteran and Congressional Correspondence channel of resolution. 

## Acceptance Criteria
- [ ] Veteran issue will be resolved or responded to with final answer to issue.
- [ ] Congressional Correspondence will receive details of the resolution.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
Still have not heard from the Veteran. I sent a follow up email today asking if they still need assistance.

**Comment by clantosswett** [comment]
From the EVSS helpdesk: "I just wanted to provide another update on this case.  We have verified with MPI that the PCE flag has successfully been removed.   We have just verified that DA has resolved the 2 CORP/2 BRLS duplicate record on the veteran’s accounts as well.  We believe all of the veteran’s issues to now be resolved, but will be sending a follow-up communication to confirm that with the veteran. I will reply back to this email thread once we have gotten that confirmation."
