### ISSUE TITLE
Update links to redirected decision reviews FAQ

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#57920]
## Issue Description
We recently published a new decision reviews FAQ page in the R&S section and redirected the old FAQ that was in the benefit hub. Now that the redirect is live, we need to change all existing links to point to the new page.

---
## Tasks
- [ ] Find links that point to the old decision reviews page and update them to point to the new page
- [ ] Copyedit and publish the updated pages

## Acceptance Criteria
- [ ] No pages link to the old URL

**Comment by bethpottsVADEPO** [comment]
@jsuarezzabala Someone on our unauth team could pick this one up when they have time.

**Comment by RLHecht** [comment]
@jonesb-va here is the new list. ignore the one from the previous comment:

<img width="1021" height="591" alt="Image" src="https://github.com/user-attachments/assets/2131acff-9510-40a6-b671-6e0c8f5b67cd" />

<img width="991" height="463" alt="Image" src="https://github.com/user-attachments/assets/7412cfde-6794-46d2-a929-efbe3f434d63" />

**Comment by jonesb-va** [comment]
LIST IN PROGRESS

Pages with updated crosslinks that need to be published:

Higher-Level Reviews *this page should stay in draft until it is ready for the other draft updates to be published
- https://prod.cms.va.gov/node/3003/latest
- http://preview-prod.vfs.va.gov/preview?nodeId=3003

Board Appeals
- https://prod.cms.va.gov/node/3029/latest
- http://preview-prod.vfs.va.gov/preview?nodeId=3029

VA’s duty to assist
- https://prod.cms.va.gov/node/49994/latest
- http://preview-prod.vfs.va.gov/preview?nodeId=49994

Supplemental Claims
- https://prod.cms.va.gov/node/3011/latest
- http://preview-prod.vfs.va.gov/preview?nodeId=3011

VA decision reviews and appeals *this page has a notice that the Health benefits node is unpublished, I need to ask bc I am not sure what we need to do for that
*this page should stay in draft until the other draft updates are ready to be published
- https://prod.cms.va.gov/node/3071/latest
- http://preview-prod.vfs.va.gov/preview?nodeId=3071

Insurance claims
- https://prod.cms.va.gov/node/3025/latest
- http://preview-prod.vfs.va.gov/preview?nodeId=3025

**Comment by jsuarezzabala** [comment]
I double-checked the links on all pages and everything looks good. Thanks, @jonesb-va!

@laurenvocke-va, this is ready for your review. Thanks!

**Comment by laurenvocke-va** [comment]
Reviewed all and published all except Higher-Level Reviews and VA decision reviews and appeals. I'll confirm when everything's live

**Comment by laurenvocke-va** [comment]
All published pages are live! I'll keep this open since we have 2 pages that are still in draft until the other edits are approved
