### ISSUE TITLE
Implement Accessibility Feedback for "Rated Disabilities" (Service Connected Sorting)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#5792]
## Goal 
For "Rated Disabilities" on staging, consider some accessibility improvements so the application has more clarity for those with accessibility needs.

## Considerations
- [Link to XD mockup](https://xd.adobe.com/view/8cdfe895-c907-4662-7234-305056778b2a-faee/)
- [Detailed notes on feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4664)
## Tasks
- [x] Collaborate with Jennifer Strickland on accessibility improvements
- [ ]  Incorporate feedback into staging

## Acceptance Criteria
- [ ] Jennifer Strickland has been notified of changes noted below

**Comment by joshkimux** [comment]
Closing this out, we'll want to conduct a maintenance audit to make sure changes have been published to prod
