### ISSUE TITLE
Create IA ticket to receive updated URLs for new landing/intro pages 

### ISSUE THREAD

**Issue by Nyanteea** [department-of-veterans-affairs/va.gov-team#57923]
## Issue Description

The information architecture team has requested we submit a ticket at design intent detailing flow changes. The current design work on landing/introduction pages includes the removal of the pre-authentication start page and the addition of two pages to replace it/the wizard it contains.  One ticket may be sufficient for all flow changes OR two may be needed for this work and the later funnel changes. 

---
## Tasks
- [ ] [Create one or two IA ticket requests ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request)

## Acceptance Criteria
- [ ] Updated URLs are received from IA team and can be submitted to the Analytics team 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Nyanteea** [comment]
@RakshindaAslam

**Comment by lydiahooper** [comment]
This was included in this content request ticket: https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/57843
