### ISSUE TITLE
Supplemental Claims | Normalize entry prior to uniqueness check

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#57927]
## Value Statement
**_As a_** Veteran filing a Supplemental Claim form
**_I want to_** make sure my submission isn't rejected because I ended duplicate entries
**_So that_** I can submit the form on the first try

---
## Background Context

A recent submission showed that a Veteran was attempting to submit a duplicate VA location entry. They tried 7 times before discovering and removing the duplicate, then made a successful submission. We don't retain the data, so this is a best guess that they may have entered a duplicate treatment date because the front end does allow entering single digit month and days. A duplication may have occurred when one entry included a single digit format and the other included leading zeros, e.g. `1-1-2023` and `01-01-2023`.

We will update the validation check for uniqueness to prevent this issue in the future.

## Acceptance Criteria
- [ ] All tasks complete
- [ ] All tests passing
- [ ] Veteran can submit a Supplemental Claim without duplicates

## Designs and Build Notes
- Update both VA and Private evidence validation checks
- A combined string comparison of all field is done, so normalize the date format before comparison

## Out of scope
- Add here

## Tasks
- [ ] Update VA evidence uniqueness validation check
- [ ] Update Private evidence uniqueness validation check
- [ ] Unit tests updated
- [ ] e2e tests updated

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design
