### ISSUE TITLE
Import latest MHV Premium Credentials export into Domo

### ISSUE THREAD

**Issue by sdickson-gt** [department-of-veterans-affairs/va.gov-team#57926]
## Issue Description
_MHV has provided another export of total credentials. This needs to be loaded into Domo_

---
## Tasks
- [x] Preprocess the MHV data export to remove ICN PII and replace with synthetic ID from the map file.
- [x] Load the data into Domo and update the dashboard to use just the MHV dataset to define total MHV credentials.
- [x] Update the data dictionary and lineage documentation.

## Acceptance Criteria
- [x] _Dashboards show total MHV credentials which align with the total credentials in the MHV dataset 3,462,134_
- [x] _The data dictionary and lineage documentation are updated._
