### ISSUE TITLE
[Design] MDT- Select supplies, batteries - default state, v1

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5793]
## Tasks:
- Create a high fidelity mockup of the battery supply selection page
- Upload to Invision with a comment to highlight initial focus state

## Acceptance criteria:
- [x] Mockup aligns with VA.gov’s design system
- [x] Include the gating question, with and without progressive disclosure expanded
- [x] Include in the selectable cards: HA model, prescribed date, and associated battery details (model, quantity, last order date)
- [x] Initial focus point documented in Invision
- [x] Sketch artboards are uploaded to Invision and linked in this ticket as a comment

**Comment by rebeccawalsh** [comment]
Screens have been uploaded to invision, including:
1. [Default page, unselected](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/405269595_C2_P2-_Select_Supplies_-_Batteries_-_Default)
2. [Default page, 'no' selected](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/405269596_C2_P2-_Select_Supplies_-_Batteries_-_No)
3. [Default page, 'yes' selected, all devices are binaural (a set for both ears)](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/405269597_C2_P2-_Select_Supplies_-_Batteries_-_Yes_-_No_Categories)
4. [Default page, 'yes' selected, mixture of binaural and monaural hearing aids (mix of pairs and single aids)](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/405269598_C2_P2-_Select_Supplies_-_Batteries_-_Yes_-_With_Categories)
5. [Page 4, but in mobile form!](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/405289953_C2_P2-_Select_Supplies_-_Batteries_-_Yes_-_With_Categories_Mobile)

Page 4 shows selected and open states for content seen on page 3 as well.

@mr0sari0 & @mojaray2k let me know if you have any questions about these pages!
