### ISSUE TITLE
Supplemental Claims | Investigate how to show errors for non-unique entries

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#57936]
## Value Statement
**_As a_** Veteran filing a Supplemental Claim form
**_I want to_** ensure that all of the evidence I am submitting is unique
**_So that_** I can submit the form on the first try

---
## Background Context

A recent submission showed that a Veteran was attempting to submit a duplicate VA location entry. This may have been to several reasons: Adding a single digit month or day in the treatment date entry, or checking the conditions associated with a location in a different order. This problem has been fixed in #57927.

Now we're presented with an issue of _where and when to show the duplicate error message_. An exact duplicate entry currently shows the error message within the location/facility name input, but this may not be the ultimate reason of the duplication. The text of the error was updated to reflect that the error may not be in the location name.

<img width="555" alt="non-unique VA location showing an error message of You must enter a location, condition and dates you haven't already entered" src="https://user-images.githubusercontent.com/136959/236485815-bea0cfea-923d-4ac1-9308-a37f02f43577.png">

<img width="552" alt="non-unique private facility showing an error message of You must enter a provider, address, condition and dates you haven't already entered" src="https://user-images.githubusercontent.com/136959/236485813-786873e7-f6b3-43d1-9ae5-8a317c4f2be3.png">

The error message on the name input may confuse the Veteran (research is needed), as to which field needs to be change, or if the duplicate entry needs to be removed. @eileen-coforma and I discussed this and she thought adding an alert to the page, or maybe only notifying the Veteran of the problem on the summary page would be a better solution.

Note that if the summary page is used to show the non-unique error message, the Veteran may have to navigate back through all the VA evidence, private evidence and uploaded evidence pages, if they decide to edit the issue, to return to the summary page.

## Acceptance Criteria
- [ ] Veteran is aware of any duplicate entries
- [ ] Veteran can check where the duplication is happening
- [ ] Veteran is able to fix the issues by making changes to or removing duplicate entry
- [ ] All tasks complete
- [ ] All tests passing

## Designs and Build Notes

- [Current design](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/p/274ABD98-987B-4C4D-BB93-8FCE3DD6C3DE/canvas)

## Out of scope
- Add here

## Tasks
- [ ] Discuss & determine the best method to notify the Veteran of duplicate entries
- [ ] Review content
- [ ] Update design

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design
