### ISSUE TITLE
Generate and issue API key to VBS

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#57937]
## Issue Description
VBS needs an API key to validate their service with our API. We can generate a random alphanumeric code and send over encrypted VA email and add to AWS parameter store

---
## Tasks
- [x] Generate API key
- [x] Send to VBS over VA encrypted email
- [x] Add to AWS parameter store

## Acceptance Criteria
- [x] We have shared and stored an API key for VBS auth
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
