### ISSUE TITLE
[Design] MDT- Select supplies, batteries - ineligible state, v1

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5794]
## Tasks:
- Create a high fidelity mockup of the battery supply selection page when a user is ineligible to order batteries for any device(s)
- Upload to Invision with a comment to highlight initial focus state

## Acceptance criteria:
- [x] Mockup aligns with VA.gov’s design system
- [x] Include information box with explanation of eligibility issue and next step
- [x] Include text in each device’s card about their last order date and next eligibility date
- [x] Initial focus point documented in Invision
- [x] Sketch artboards are uploaded to Invision and linked in this ticket as a comment

**Comment by rebeccawalsh** [comment]
Mockups can be found here:
[All devices are ineligible, default](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/406260564_C2_P2-_Select_Supplies_-_All_Devices_Ineligible_-closed-)
[All devices are ineligible, open 'additional information' components](https://vsateams.invisionapp.com/d/main?origin=v7#/console/19309480/406260563/preview?scrollOffset=0)
