### ISSUE TITLE
[Design] Create Mural user flow source of truth in VA Mural workspace

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#57951]
## Issue Description
Currently the reference [EZ site user flow in Mural](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1632923531828/474bfdde942c22a0df26ad416a0b23e36b834d4a?sender=uadf1ed7fe7c76f0914967329) and [CG site user flow in Mural](url) is in the Ad Hoc workspace and designers don't have the ability to edit. 

Create a Mural in the VA workspace 1010 room so it is available for future access/edits needed. 

---
## Tasks
- [x] Create a [Mural artboard for EZ](https://app.mural.co/invitation/mural/departmentofveteransaffairs9999/1682696116933?sender=uadf1ed7fe7c76f0914967329&key=e183a517-fda3-411e-a7c5-12c5e0854df3)
- [x] Create a Mural artboard for CG
- [x] Move over wireflow and screen captures and/or Sketch artboard exports into Mural
- [x] Add any tags/notes needs
- [x] Review/share with team

## Acceptance Criteria
- [x] User flow is available for team access for future editing needs
---

**Comment by davidakennedy** [comment]
Links for new boards:

- [1010EZ user flow](https://app.mural.co/invitation/mural/departmentofveteransaffairs9999/1687376928311?sender=u773b824999f25f58b8e77486&key=e0227975-98c5-48ea-8add-a7e7234ebadf)
- [1010 CG user flow](https://app.mural.co/invitation/mural/departmentofveteransaffairs9999/1687288632872?sender=u773b824999f25f58b8e77486&key=13b985b2-3c02-45b1-a8fe-aae0ec9ba7a7)

**Comment by davidakennedy** [comment]
Commenting here to add a few notes for the team and for future tickets, which I'll make tomorrow:

- Both flows exist now in there most basic forms. We should try to add more notes and details in Mural as we work on projects.
- The CG needs Sketch files for the confirmation page. That needs to be copied from the Sketch page: Submission confirmation - 42322. Also, it needs a mobile version.
- The authenticated flow in the EZ in Sketch is very minimal and would be good to update in the future.
