### ISSUE TITLE
Add MHA effective date information to education pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#57953]
## Issue Description

Our education stakeholders let us know that we currently don't explain on our education pages that the effective date for MHA is August 1 while the BAH rate effective date is January 1.

Here's an example: The MHA someone receives for April 2023 will be based on the January 1, 2022 BAH rates, NOT January 1, 2023. Then, on August 1, 2023, the MHA will change to the January 1, 2023 rates.

We need to explain this on our [Post-9/11 GI Bill](https://www.va.gov/education/about-gi-bill-benefits/post-9-11/) page and consider other pages that also may need this info.

## Tasks
- [x] Update pages in Drupal (Katherine)
- [x] Review (Beth)
- [x] Send to stakeholders for review (Katherine)
- [x] Copyedit (Megan)
- [x] Publish

## Acceptance Criteria
- [ ] Page is live with changes

**Comment by katherine-fung** [comment]
Hi @bethpottsVADEPO. 

I updated the MHA information is just 1 section of the Post-9/11 GI Bill rates page. I want to get your thoughts on the approach first. 

1. I added this line: "We use the 2022 rates to calculate the MHA you get between August 1, 2022 and July 31, 2023."

2. Jodie also asked us to explain that if you're enrolled at a foreign school, you get the national average for MHA. And to include the actual number. For this, I tried 2 approaches. 

In screenshot/approach #1, I added 2 H3s to the MHA section under "Full rates for schools and training programs." Under one H3, I explained that we base MHA on the national average rate if you're at a foreign school or in online only classes. The other H3 includes the existing MHA info, which says we use BAH for E5 with dependents for your zip code to calculate MHA if you're in other types of programs. 

I think I prefer this approach because the breakdown is more clear. The H3s are a bit long though.
![screenshot 1.png](https://images.zenhubusercontent.com/627bd98be9182e080ddd515b/8e93b6b9-f7aa-4d18-96c1-f518d81e5f12)


Screenshot/approach #2 is more similar to the live page. I added the foreign school info and grouped it together with info about distance learning and flight/correspondence training. 

![screenshot 2.png](https://images.zenhubusercontent.com/627bd98be9182e080ddd515b/6dcfeba1-e1b4-4335-beec-c1e88948b3a5)

**Comment by bethpottsVADEPO** [comment]
@katherine-fung I like your first approach too! Could you try breaking online only and foreign into 2 separate sections? So the headers would be: "For online-only classes" and "For foreign institutions of higher learning." Both sections would start with "We base your monthly housing allowance on the national average." And both will end with the same sentence about the maximum amount: "This is the maximum amount we'll pay you each month."

I also made a couple tweaks in the drupal file. You can go ahead and show this to SMEs and tell them we can get it live this week if these updates look good. 

One question I have for you is this: Do we need to say "online only"? If we do, we should hyphenate it before "classes."

**Comment by katherine-fung** [comment]
Thanks @bethpottsVADEPO! I brought the question about the header to the team, and we landed on: 
"For online-only classes, or distance learning" 

I've emailed the stakeholders with screenshots, and asked for their feedback. 

For reference, here's a list of pages we'll need to update: 

- current PGIB rates 
http://preview-prod.vfs.va.gov/preview?nodeId=1009

- future PGIB rates 
http://preview-prod.vfs.va.gov/preview?nodeId=52939

- 2021-2022 PGIB rates 
http://preview-prod.vfs.va.gov/preview?nodeId=49728 

- 2020-2021 PGIB rates 
http://preview-prod.vfs.va.gov/preview?nodeId=55782

- current Fry rates 
http://preview-prod.vfs.va.gov/preview?nodeId=49549

- 2021-2022 Fry rates 
http://preview-prod.vfs.va.gov/preview?nodeId=55782

- 2020-2021 Fry rates
http://preview-prod.vfs.va.gov/preview?nodeId=55778

- current transferred rates 
http://preview-prod.vfs.va.gov/preview?nodeId=51816 

- current VET TEC rates  
http://preview-prod.vfs.va.gov/preview?nodeId=52956

**Comment by katherine-fung** [comment]
Hi @bethpottsVADEPO, 

I'm incorporating Cinda and Jodie's feedback. I want to run the H3 "For schools based in the U.S. and non-college degree programs" by you. Do you think this works? 

![MHA.png](https://images.zenhubusercontent.com/627bd98be9182e080ddd515b/82f36cb2-6715-4422-9761-b2032887f280)

Previously, this said "For other institutions of higher learning," but I've changed it for accuracy, and to account for moving this section up. I replaced "institutions of higher learning" with "schools," though, to keep the H3 shorter. 

Here's a link for the preview: http://preview-prod.vfs.va.gov/preview?nodeId=1009

**Comment by katherine-fung** [comment]
Hi @RLHecht @laurwill, 

I've updated all of the pages in the checklist above, and stakeholders have signed off. They're ready to publish once copy edited.

A few things to note: 

- Cinda and Jodie informed me that we now refer to "distance learning" as "online learning."
- Outside of the scope of the initial intake request, Cinda and Jodie asked that we also add the specific MHA rates for online learning and foreign schools. The numbers are in an email I got from edu service, I'll forward those to you.  
- Beth and I decided to re-formatt this page while we were making these other changes. In the "school and training programs" section, I took the information that was in accordions, out of accordions. 
- If we need to prioritize which pages to copy edit, the current and future PGIB and Fry rates pages are most important. The rest (past rates) can wait until next week. 
- We shouldn't publish VET TEC and transferred rates pages yet.

**Comment by RLHecht** [comment]
I copyedited and published the current and future rates pages for Post-9/11 and Fry and emailed the stakeholders to let them know. All the past rates still need to be get published.

**Comment by RLHecht** [comment]
@megzehn I made the rest of the tweaks to the 2 past rates pages for PGIB and Fry (Katherine listed the links above). Those four pages are ready for you to publish.

**Comment by megzehn** [comment]
Thanks @katherine-fung and Randi! Confirming I copy edited and published the rates pages. And I copy edited the transferred benefits and VET TEC pages but let them in drafts.

**Comment by katherine-fung** [comment]
Thanks so much @megzehn. I'm following up with Jodie and Cinda this week to check where the transferred benefits and VET TEC rates pages stand.

**Comment by katherine-fung** [comment]
closing this ticket - we'll continue other work in tickets #50456 and #50455.
