### ISSUE TITLE
686c | Metrics for successful and failed submissions

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#57955]
## Issue Description

A re-processing effort depends on  knowing all null claims that have been generated.  Matt B. put together SQL aimed at generating reports of all null claims in a given time period.  We would like to verify the accuracy of these reports.  One way to do that is to log all failed submissions on our end, and then compare our counts within some time period to the counts generated by Matt B.'s reports. If the two are sufficiently similar, then we can reasonably rely on Matt B.'s report of null claims for our re-processing efforts.

This should be as simple as logging failures in our existing rescue block, and then building a datadog dashboard to search for and count those queries.

While we're at it, we may as well log successful submissions too.

---
## Tasks
- [x] Add logs for successful and failed submissions
- [x] Build datadog dashboard to track both

## Acceptance Criteria
- [x] Datadog dashboard shows number of successful and failed submissions
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by data-doge** [comment]
Works as intended. We don't have DataDog write access, so we can't create fancy looking dashboards. Kyle has been asking for DD write access for a long time. In the meantime, these queries should suffice:
- [Failures](https://vagov.ddog-gov.com/logs?query=%40message_content%3A%22BGS%3A%3ADependentService%20failed%21%22%20OR%20%40message_content%3A%22BGS%3A%3ASubmitForm686cJob%20failed%21%22%20OR%20%40message_content%3A%22BGS%3A%3ASubmitForm674Job%20failed%21%22%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=desc&viz=stream&from_ts=1683225144271&to_ts=1683829944271&live=true)
- [Successes](https://vagov.ddog-gov.com/logs?query=%40message_content%3A%22BGS%3A%3ASubmitForm686cJob%20succeeded%21%22%20OR%20%40message_content%3A%22BGS%3A%3ASubmitForm674Job%20succeeded%21%22%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=desc&viz=stream&from_ts=1683225144271&to_ts=1683829944271&live=true)

Closing this ticket
