### ISSUE TITLE
Change product directory from manifest-driven to a singular source of truth

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#57958]
## Issue Description
Currently the product directory requires a manifest to exist for a product to be listed on the directory. Additionally, there's no way with our current system for a directory in vets-website to have a manifest and not be listed on the product directory. The product directory needs to be switched to source off a singular source of truth that can handle adding, removing, de-listing, and all other future configuration concerns for the product directory.

---
## Tasks
- [ ] Develop a singular source of truth for the product-directory.
- [ ] Convert all automated processes around the product directory that currently source off manifests to source off this new source of truth.

## Acceptance Criteria
- [ ] The product directory is disconnected from manifests with no loss in functionality.
- [ ] The product directory has flexibility to be configured however is necessary moving forward.
