### ISSUE TITLE
Change product directory from manifest-driven to a singular source of truth

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#57957]
## Issue Description
Currently the product directory requires a manifest to exist for a product to be listed on the directory. Additionally, there's no way with our current system for a directory in vets-website to have a manifest and not be listed on the product directory. The product directory needs to be switched to source off a singular source of truth that can handle adding, removing, de-listing, and all other future configuration concerns for the product directory.

---
## Tasks
- [x] Develop a singular source of truth for the product-directory.
- [x] Convert all automated processes around the product directory that currently source off manifests to source off this new source of truth.

## Acceptance Criteria
- [ ] The product directory is disconnected from manifests with no loss in functionality.
- [ ] The product directory has flexibility to be configured however is necessary moving forward.

**Comment by CBonade** [comment]
Zenhub duplicated issue. Closing

**Comment by JoeTice** [comment]
Task is in progress, work was started on it this sprint, but remains open due to technical troubleshooting on Preview Environments that took priority. Work will be completed in Sprint 29

**Comment by CBonade** [comment]
Work commenced on this today. The entirety of the daily automated script to check the manifest and update according to the true/false flags has been complete, along with archiving entries that have been removed. The next step will be using this list as the source of truth for the daily product scan in vets-website, which should hopefully be completed tomorrow and this will be ready to go to production.

**Comment by JoeTice** [comment]
Sprint 29 Update - IN PROGRESS - Progress was made on this ticket this sprint, Expect this task to be completed in Sprint 30

**Comment by CBonade** [comment]
This code has been merged. The manifest located in the product-directory repository is the new source of truth for the product directory, while the daily update scan sources off the directory itself instead of manifests.
