### ISSUE TITLE
[designer] MDT- Select supplies, batteries - rechargeable only, v1

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5796]
## Tasks:
- Create a high fidelity mockup of the battery supply selection page when a user has only rechargeable hearing aids eligible for resupply
- Upload to Invision with a comment to highlight initial focus state

## Acceptance criteria:
- [x] Mockup aligns with VA.gov’s design system
- [x] Include information box with explanation of eligibility issue and next step
- [x] Initial focus point documented in Invision
- [x] Sketch artboards are uploaded to Invision and linked in this ticket as a comment

**Comment by rileyorr** [comment]
**Prototype:** [Desktop](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/406054376_C2_P2-_Select_Supplies_-_Rechargeable_Only)
A couple notes to consider:
1. The initial focus point should be the h1: Order hearing aid batteries and accessories (marked on the prototype as comment 1)
2. The other battery ordering screens contain a gating question asking the veteran whether or not they want to place an order for batteries; we do not need to prompt the question for this instance. I chose to design without the gating question because it's not good user experience to ask the user if they want to order batteries only to tell them that they never had the option to. 

@mojaray2k & @mr0sari0 as always, please let me know if you have any questions and/or if you'd like to meet to review this design! :)
