### ISSUE TITLE
Identity Docs site - Setup site hosting

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#57978]
## Description
Set up Next.js website for identity documentation (public facing) with landing page

## Tasks
- [ ] Requires integration with VA Design System
  - [ ] Requires US Government site header
  - [ ] Requires Veterans Crisis Line header
- [ ] Create landing page
