### ISSUE TITLE
[Design] MDT- Select supplies, accessories - default state, v1

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5797]
## Tasks:
- Create a high fidelity mockup of the accessory supplies selection page
- Upload to Invision with a comment to highlight initial focus state

## Acceptance criteria:
- [x] Mockup aligns with VA.gov’s design system
- [x] Include domes, wax guards, and additional supplies, with corresponding products
- [x] For each product, include (at minimum) item model, quantity, and date last ordered
- [x] Initial focus point documented in Invision
- [ ]Sketch artboards are uploaded to Invision and linked in this ticket as a comment

## Dependencies:
DLC providing guidance on accessories other than wax guards and domes

**Comment by rileyorr** [comment]
@mr0sari0 & @mojaray2k I've created a [GH markdown file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-accessory-selection.md) containing links to the prototypes, content in code blocks (including component names & utility classes), a description of the use case, and the initial focus points for each screen (also displayed on the screens as either a comment or using the focus point component from VA's design system). Please let me know if you have any questions or would like a walkthrough of the screens! 
@leahkeeler I am moving this ticket to validate~
