### ISSUE TITLE
Changes to COVID pages for end of public health emergency-HOLD TO PUBLISH ON MAY 12

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#57989]
## Issue Description

The COVID-19 public health emergency is ending on May 11. This also means the VA's save lives act allowing more than just Veterans to receive vaccines through VA is also ending. We need to add info explaining this change on our [main vaccines page](https://www.va.gov/health-care/covid-19-vaccine/) as well as remove some content on our COVID pages to reflect this. These changes should be published on May 11, 2023. 

## Tasks
- [x] Add info to main vaccines page (Randi)
- [x] Remove content in drupal (Randi)
- [x] Review new content (Danielle/Laura)
- [x] Send to Missy for approval (Randi)
- [x] Copyedit (Megan)
- [x] Publish (Megan)
- [x] Create translation ticket (Randi)

## Acceptance Criteria
- [ ] Changes are live on the site

**Comment by RLHecht** [comment]
@megzehn these pages are now ready for you to copyedit and publish. Thanks

**Comment by megzehn** [comment]
Thanks, @RLHecht!! I reviewed these and published.

**Comment by RLHecht** [comment]
These pages are live. Closing ticket!
