### ISSUE TITLE
Identity docs site - Build quick start integration page

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#57984]
## Description
Create an "integration breakdown" step-by-step instructions

## Tasks
- [ ] Add quick start integration page using (reference https://auth0.com/docs/quickstart/webapp/nextjs/interactive)
  - [ ] Left-side provies step-by-step instructions
  - [ ] Right-side provides code that coincides with the left-hand step (reference Notion)
