### ISSUE TITLE
[Design] Mdt- Select supplies, accessories - ineligible state, v1

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5798]
## Tasks:
- Create a high fidelity mockup of the accessory supplies selection page when users are ineligible for all accessories
- Upload to Invision with a comment to highlight initial focus state

## Acceptance criteria:
- [x] Mockup aligns with VA.gov’s design system
- [x] Include information box with explanation of eligibility issue and next step
- [x] Include text for each product about their last order date and next eligibility date
- [x] Initial focus point documented in Invision
- [x] Sketch artboards are uploaded to Invision and linked in this ticket as a comment

**Comment by rileyorr** [comment]
@mr0sari0 & @mojaray2k I've updated the _Add Additional Accessories_ [GH markdown file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-accessory-selection.md#use-case---all-accessories-are-ineligible) containing links to the prototypes, content in code blocks (including component names & utility classes), a description of the use case, and the initial focus points for each screen (also displayed on the screens as either a comment or using the focus point component from VA's design system). Please let me know if you have any questions or would like a walkthrough of the screens!
@leahkeeler I am moving this ticket to validate~
