### ISSUE TITLE
Identity Docs site - Research & integrate a CMS

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#57982]
## Description
Research and integrate a CMS (Content Management System) with the Next.js site

## Tasks
- [ ] Research and choose an appropriate CMS based on the requirements
  - [ ] Tech writers can modify content with a WYSIWYG editor
  - [ ] Git-based CMS (no API required)
- [ ] Integrate the CMS with Next.js
