### ISSUE TITLE
[PM, FE] My VA audit ux: Investigate "payment history" event action tags

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#57991]
## Background
While monitoring analytics post-launch, I noticed that there were multiple event action tags associated with (I believe) the "review your payment history" link in the Benefit payment section on My VA (both links go to the same destination and therefore should be/are tracked with the same event tag):
 
![Screenshot 2023-05-08 at 12 35 44 PM](https://user-images.githubusercontent.com/45603961/236880035-429bb0a2-469d-4bf0-a555-893fbb1f82fc.png)

![Screenshot 2023-05-08 at 12 35 33 PM](https://user-images.githubusercontent.com/45603961/236880129-0f3de596-6e7e-4c36-846e-44ac98e9200e.png)

I did some digging on my own and created a timeline with changes I know we made in comparison to what I've been able to see in Domo:

### Nov 14, 2022
New event tag appears in addition to the existing tag, which coincides with changing sighted words (view --> review):
| Tag | Existing or New | Time Frame |Total Events from Domo|
|--|--|--|--|
|`Navigation - Link List - Benefit payments and debts - View your payment history`| Existing/Original | Nov 1 - Nov 14 | 69,163|  
|`Navigation - Link List - Benefit payments - Review your payment history`| New | Nov 1 - Nov 14 | 1|

### Nov 29, 2022
A _third_ tag appears, joining the existing two, which coincides with the start of payment info v2 phased launch
| Tag | Existing or New | Time Frame |Total Events from Domo|
|--|--|--|--|
|`Navigation - Link List - Benefit payments and debts - View your payment history`| Existing/Original | Nov 1 - Nov 29 | 161,698| 
|`Navigation - Link List - Benefit payments - Review your payment history`| Existing (as of Nov 14) | Nov 1 - Nov 29 | 2,118|
|`Navigation - Link List - Benefit payments - View your payment history` | New |  Nov 1 - Nov 29 | 111 |

### Nov 29, 2022 - March 15, 2023
All three tags appear gather clicks/metrics. Notice that at some point in this time frame, the tag added on 11/14 (review) overtakes the original event tag in clicks
| Tag | Existing or New | Time Frame |Total Events from Domo|
|--|--|--|--|
|`Navigation - Link List - Benefit payments - Review your payment history`| Existing (as of Nov 14 2022) | Nov 29 2022 - March 15 2023 | 798,942|
|`Navigation - Link List - Benefit payments and debts - View your payment history`| Existing/Original | Nov 29 2022 - March 15 2023 | 63,370| 
| `Navigation - Link List - Benefit payments - View your payment history` | Existing (as of Nov 29 2022) |  Nov 29 2022 - March 15 2023 | 38,463 |

### March 16, 2023
Tag that appeared on 11/29/22 disappears
| Tag | Existing or New | Time Frame |Total Events from Domo|
|--|--|--|--|
|`Navigation - Link List - Benefit payments - Review your payment history`| Existing (as of Nov 14 2022) | March 16 - May 7 2023 | 385,022|
|`Navigation - Link List - Benefit payments and debts - View your payment history`| Existing/Original | March 16 - May 7 2023 | 500 | 

### Staging
I've tested on staging with users 36, 14 and 15 - the event tag that shows in the console when clicking "Review your payment history" link is `Navigation - Link List - Benefit payments - Review your payment history`

## Tasks
- [x] Go to analytics office hours to show them what we've found (PM)
- [x] Investigate what's happening here (FE): locate `Navigation - Link List - Benefit payments and debts - View your payment history` in the code 
- [ ] Implement solution: correct the tag to be `Navigation - Link List - Benefit payments - Review your payment history` (i.e. to match the other existing tag)
- [ ] Have Analytics team test/check for us
- [ ] Document explanation in GH (PM)

## Acceptance Criteria
- The event tag `Navigation - Link List - Benefit payments and debts - View your payment history` is corrected in the code to match `Navigation - Link List - Benefit payments - Review your payment history` so that going forward in Domo there is only one event tag associated with the link "Review your payment history"

## Resources
Info from analytics team about data layers and event tag names:
![image (3)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/5d888eff-ce8e-49a1-a565-8c504d8783bd)

![image (4)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/0883ae8e-4324-4252-b067-d48ba7ccb892)

**Comment by ajakabcin** [comment]
@allisonlu and I attended analytics office hours today for some guidance on this - we determined we need to find where in the code this old event tag is and change it to match the correct one. I've updated the tasks to reflect next steps.

**Comment by ajakabcin** [comment]
Moving to blocked while we investigate why users are still seeing the old version of payment info (investigating in #58543 )

**Comment by ajakabcin** [comment]
We believe this should be resolved by solution outlined [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/58543#issuecomment-1555232177), to be implemented in #47243. Will leave this open to review once solution is implemented and we can confirm in Domo how things are looking.

**Comment by ajakabcin** [comment]
Confirmed that the only event tag for the payments section is the `Navigation - Link List - Benefit payments - Review your payment history` 🎉 - great job @allisonlu!!

Filtering by date, it looks like [Allison's fix](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47243#issuecomment-1579397233) to remove the feature flag from the code did the trick! Just fyi for reference on the same issue we're seeing with the claims and appeals section tags (#59400)
