### ISSUE TITLE
[Design] MDT- Review order - default state, v1

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5800]
## Tasks:
- Create a high fidelity mockup of the review order page
- Upload to Invision with a comment to highlight initial focus state

## Acceptance criteria:
- [ ] Mockup aligns with VA.gov’s design system
- [ ] Include the Veteran’s personal details, with details on how to fix incorrect info
- [ ] Include contact information (mailing and email addresses), with a way to edit it
- [ ] Include details about selected product(s), with a way to change them
- [ ] Initial focus point documented in Invision
- [ ] Sketch artboards are uploaded to Invision and linked in this ticket as a comment
