### ISSUE TITLE
[BE] Update how we handle the success response from BTSSS API

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#58015]
## User Story
As a Veteran, I want to see the text message with the correct travel claim number when I file the travel claim as a part of check-in process.

## Tasks
- [x] [BE] Update the code for handling success response from BTSSS API
- [x] [BE] update vcr cassettes and betamock responses

## Acceptance Criteria
- [x] Deployed to staging
- [x] Tested on staging
