### ISSUE TITLE
[Design] HLR: Update Higher Level Review Design Artifacts Based on AMO Comments

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#5801]
## User Story or Problem Statement
As a veteran, I need a submit requests for higher level review in an easy to navigate and understand fashion so that I can successfully get my benefits.

We've done the redesign at this point but we will likely have some more comments flowing in from AMO.  This is the follow-up ticket to #5259.

## Goal
Final design blessed by AMO.

## Tasks
- [ ] Meet with AMO and get feedback into the design

## Acceptance Criteria
- [ ] InVision design is done and blessed by AMO.

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by luke-gcio** [comment]
Moving into Sprint 16 turns out we have one more round with AMO on the wording on the Opt-Out language.

**Comment by luke-gcio** [comment]
Closing and will make another story for the Sprint 16 round.
