### ISSUE TITLE
Review appointments UX

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#58027]
## Task Description
Review all existing VAOS user flows on staging and write notes on how they could be improved. Review with Appointments UX Lead. Consider A11y, Navigation, Functionality, Usability heuristics etc. 

## References
- 

## Acceptance Criteria
- [x] Create a spreadsheet to gather notes
- [x] Collect notes on experience improvements 
- [x] Open questions on the experience
- [x] Schedule a meeting with Ciera and Peter to talk through notes/ questions
- [x] Share with UX Lead
_________________ 
- [x] Review Peter's comments in the spreadsheet
- [x] Create tickets for the idea board

**Comment by outerpress** [comment]
@melissa-lefevre I reviewed the doc and added my comments. Nice work! Assigning back to you, we'll discuss next steps during project planning.

**Comment by melissa-lefevre** [comment]
I made tickets out of all the issues I found.
