### ISSUE TITLE
[Design] MDT- Review order page - edit contact details, v1

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5802]
## Tasks:
- Create high fidelity mockup(s) showing how a Veteran might update their  address and contact details
- Upload to Invision with a comment to highlight initial focus state

## Acceptance criteria:
- [x] Mockup aligns with VA.gov’s design system
- [x] Include a way for Veterans to edit their mailing and email addresses
- [x] Include a way for Veterans to save or cancel their edits
- [x] Initial focus point documented in Invision
- [x] Sketch artboards are uploaded to Invision and linked in this ticket as a comment

**Comment by rebeccawalsh** [comment]
**Invision Prototype:** Edit contact information [(Desktop)](https://vsateams.invisionapp.com/d/main?origin=v7#/console/19309480/408056197/preview?scrollOffset=2695)

Github documentation: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-review.md#use-case---review-edit-contact-information
