### ISSUE TITLE
[Design] 10-10EZ Update household section source of truth docs

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#58021]
## Issue Description
Update the source of truth files once the household information optimization work is ready/in first production release (5%?) 

---
## Tasks
- [x] Update the [github content source of truth doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZ%20Form/10-10EZ-application-copy.md)
- [x] Update any [Mural files reference user flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687376928311/303a0fbb8ffe1353eedf695ac86a6e069cd2003f?sender=uadf1ed7fe7c76f0914967329)
- [x] Update the general [wireflows Sketch page source of truth](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6) 
- [x]  Update the page in [Sketch file 4. Household information](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/9472FAA6-0024-4DCF-BDFA-FF1FCA2C82EF/canvas) source of truth
- [x]  Add new errors to the [Error Matrix](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZ%20Form/Error%20Matrix.md) on github and [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683651181051/e0f47b9aaefbf78a3942df3028525cdc4336caff?sender=uadf1ed7fe7c76f0914967329) for error audit

## Acceptance Criteria
- [x] All source of truth files are updated reference the new release of the household information section
---

**Comment by hdjustice** [comment]
Revisit when Household section work is in production

**Comment by jessicastump** [comment]
All source of truth docs have been updated and this ticket can be closed. 

tagging ux peeps just for reference so you all have access to the source of truth links listed above in tasks :)
cc @davidakennedy @IMHieuVo @katelyncai

**Comment by hdjustice** [comment]
Closing!  Thanks Jessica!
