### ISSUE TITLE
Implementation: Create an EFS

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#58031]
Research can be found here - https://vfs.atlassian.net/wiki/spaces/TT4/pages/2626420737/Discovery+Explore+how+to+create+an+EFS+Hosted+Persistent+Volume+for+Preview+Environments+56720

Terraform + EFS link - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_file_system

---
## Tasks
- [x] Create an EFS file system in the AWS Management Console or via [Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_file_system)
- [x] Install the EFS CSI driver in your EKS cluster
- [x] Create a Kubernetes StorageClass for EFS
- [x] Create a PersistentVolumeClaim (PVC) for your application

## Acceptance Criteria
- [x] The EFS file system is created in the "vagov-staging" VPC
- [x] The EFS CSI driver is installed in the EKS cluster
- [x] The Kubernetes StorageClass for EFS is created and applied successfully
- [x] The PersistentVolumeClaim for the application is created and applied successfully
- [x] The EFS volume can be mounted by the application running in the EKS cluster
- [x] ~The application running in the EKS cluster can read data from the EFS volume~ (broken out into its own [ticket](https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/60064))
- [x] ~Multiple instances of the application can access the EFS volume simultaneously, allowing for a shared storage solution~ (broken out into its own [ticket](https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/60065))

**Comment by holdenhinkle** [comment]
Draft PR - https://github.com/department-of-veterans-affairs/devops/pull/13006

**Comment by holdenhinkle** [comment]
Here's a description of what's happening in each file:

### `terraform/environments/dsva-vagov-staging/efs.tf`
This file contains the Terraform resources to create the EFS file system and its mount targets.

- `aws_security_group` resource creates a security group that allows ingress access on port 2049 (NFS protocol) for the specified CIDR blocks.
- `aws_efs_file_system` resource creates the EFS file system.
- `aws_efs_mount_target` resource creates EFS mount targets in each specified subnet. This makes the EFS file system accessible within your VPC.

### `terraform/environments/dsva-vagov-staging/eks.tf`
This file contains the Terraform resources to configure the EKS cluster, deploy the AWS EFS CSI driver, and create a storage class and persistent volume claim.

- The `helm` provider is configured to interact with the EKS cluster using the specified kubeconfig file.
- `helm_release` resource deploys the AWS EFS CSI driver to the EKS cluster using the Helm chart from the official repository.
- The `kubernetes` provider is configured to interact with the EKS cluster using the specified kubeconfig file.
- `kubernetes_storage_class` resource creates a storage class that uses the EFS CSI driver as its provisioner.
- `kubernetes_persistent_volume_claim` resource creates a persistent volume claim that requests storage from the previously created storage class.

### `terraform/environments/dsva-vagov-staging/main.tf`
This file is the main entry point for your Terraform configuration. It includes the EFS and EKS resources by referencing the efs.tf and eks.tf files.

- The `module` block imports and runs the EFS and EKS resources defined in the `efs_eks` directory.
- The `output` block exposes the EFS file system ID as an output of the Terraform configuration.

### `terraform/environments/dsva-vagov-staging/variables.tf`
This file defines the input variables required for the Terraform configuration.

- `vpc_id`: The VPC ID where the EFS file system and EKS cluster will be created.
- `subnet_ids`: A list of subnet IDs where the EFS mount targets and EKS worker nodes will be created.
- `allowed_cidr_blocks`: A list of allowed CIDR blocks to access the EFS file system.
- `kubernetes_config_path`: The path to the Kubernetes configuration file.

These variables are not assigned default values in the `variables.tf` file. You'll need to provide values for these variables when running `terraform apply` or set them in a `terraform.tfvars` file in the same directory.

**Comment by cyriltech** [comment]
Made some changes from @holdenhinkle draft pr and created some new terraform resources. Terraform code to create EFS is ready and awaiting review and approval from Devops. Slack [thread](https://dsva.slack.com/archives/C04CYC4LMU6/p1684252981158689)

**Comment by cyriltech** [comment]
Per the [conversation](https://dsva.slack.com/archives/C04CYC4LMU6/p1684252981158689) with Kyle the platform standard is to create efs-csi-driver within the infra manifest repo. I made some changes to the terraform [PR](https://github.com/department-of-veterans-affairs/devops/pull/13023) to create EFS with terraform and efs-csi-driver with helm in the infra manifest repo. Currently, I have the terraform code PR ready. Waiting for an output of the EFS ID and role from a terraform apply to insert within the efs-csi-driver code within the infra manifest repo.

**Comment by pjhill** [comment]
Awesome, thanks for continuing to push on this!

**Comment by cyriltech** [comment]
Kyle reviewed PR and requested some changes. Code is updated and PR approved by Hector, however merge is blocked since Kyle needs to approve PR as well because he requested changes. The blocker now is that Kyle is on vacation.

**Comment by JoeTice** [comment]
Issue is in progress, taking longer than expected as we learn what's involved, work will continue in Sprint 28

**Comment by cyriltech** [comment]
A new [PR](https://github.com/department-of-veterans-affairs/devops/pull/13060) was created and merge. Terraform apply was ran and EFS storage was created for preview-environment with role and permissions. Next step is to use the EFS id and role Id within the efs-csi-driver code.

**Comment by JoeTice** [comment]
Sprint 28 Update - DEPRIORITIZED - Due to Holden being out on vacation, and Cyril being focused on helping us resolve a technical blocker, we deprioritized this task for this sprint. Work will resume in Sprint 29

**Comment by cyriltech** [comment]
Efs-csi-driver successfully onboarded as an application within preview-environment![image.png](https://images.zenhubusercontent.com/6385292bddbc0cbb14b84a51/2074fff8-aeac-4697-9b1b-67ab211ba0eb).  Updated [PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1996) to add a storage class and pvc. Next step is to test Volume mount on test app.

**Comment by holdenhinkle** [comment]
Create sub-tickets for the following:

- The application running in the EKS cluster can read data from the EFS volume
- Multiple instances of the application can access the EFS volume simultaneously, allowing for a shared storage solution

**Comment by holdenhinkle** [comment]
Tickets have been created.

Closing this.
