### ISSUE TITLE
[BE] Modify test.yml with explicit fake ID 

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#58037]
## Description
Modify [test.yml](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/settings/test.yml#L224) with explicit fake ID to avoid triggering security review

## Tasks
- [ ] [BE] **Modify test.yml**
- [ ] [BE] **Update rspec (if required)**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
