### ISSUE TITLE
visuals of MHV/DSL users with either login.gov/id.me that are using legacy credentials

### ISSUE THREAD

**Issue by sdickson-gt** [department-of-veterans-affairs/va.gov-team#58042]
## Issue Description
Provide dashboard visuals for tracking effectiveness of targeting the reactivation segment, where the reactivation segment are users with either MHV or DS Logon credentials and either Login.gov or ID.me credentials.  

---
## Tasks
- [ ] Update dashboard to: Provide total users. And then a way to track over time the decrease in using legacy creds…Or over time only using modern creds
- [ ] Update dashboard with new view: modern credentials added overlap with legacy
- [ ] Update dashboard with: visual of MHV/DSL users with either login.gov/id.me that are using legacy credentials

## Acceptance Criteria
- [ ] _???_
