### ISSUE TITLE
Implementation: Update the Dockerfile to mount the EFS volume so vets-website can use the mounted volume

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#58046]
See https://vfs.atlassian.net/wiki/spaces/TT4/pages/2626420737/Discovery+Explore+how+to+create+an+EFS+Hosted+Persistent+Volume+for+Preview+Environments+56720#Research-best-practices-for-configuring-the-Docker-image-to-mount-the-EFS-volume-and-setting-up-vets-website-to-use-the-mounted-volume.

---
## Tasks
- [x] Update the `Dockerfile` for vets-website
  - [x] Install NFS utilities for mounting EFS volumes
  - [x] Create a directory for EFS volume mount
- [x] Modify the Kubernetes deployment YAML file for your application
  - [x] Add a volume entry in the `spec.template.spec.volumes` section, referencing the previously created PVC
  - [x] Mount the volume to your application container by adding a volumeMounts entry in the spec.template.spec.containers section
- [x] Update the vets-website configuration to use the mounted EFS volume
  - [x] Modify the configuration files or environment variables in your application to reference the `/efs` directory as the desired location for file storage

## Acceptance Criteria
- [x] The `Dockerfile` is updated to include NFS utilities and creates the `/efs` directory for EFS volume mount
- [x] The Kubernetes deployment YAML file is modified to include a volume entry referencing the PVC and mounts the volume to the application container
- [x] The vets-website configuration is updated to use the mounted EFS volume
- [x] The application running in the EKS cluster can successfully access the EFS volume mounted at `/efs`
- [x] The application can read and write data to the EFS volume, allowing for a shared storage solution
- [x] The updated Docker image, when deployed to the Kubernetes cluster, works correctly with the mounted EFS volume

**Comment by JoeTice** [comment]
Sprint 29 Update - IN PROGRESS - Progress was made on this ticket this sprint, this issue was lower priority than some technical blockers we're encountering, work will continue in Sprint 30
