### ISSUE TITLE
Re-activation eligible user list

### ISSUE THREAD

**Issue by sdickson-gt** [department-of-veterans-affairs/va.gov-team#58044]
## Issue Description
Need a list of emails for the re-activation segment.

---
## Tasks
- [x] create script to generate CSV list of emails of the reactivation segment in format: secid, email, MHVlastUsedDate, DSLlastUsedDate, IDMlastUsedDate, LGNlastUsedDate
- [x] create script to add/merge with email list from VA.gov 
- [ ] TBD: Filter by credential(s) lastUsed date
- [ ] Split CSVs into files with less that 1M rows 

## Acceptance Criteria
- [ ] _CSV with primary and secondary emails for the re-activation segment_

**Comment by sdickson-gt** [comment]
Secid won't be available in the dataset provided by Joe.  Will need to revise the scripts based on what ID(s) are provided.

**Comment by sdickson-gt** [comment]
This is OBE with the pivot to VA Notify.
