### ISSUE TITLE
[PM][Design] 10-10 Forms: Error state audit

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#58056]
## Issue Description
As a 1010 team member, I want a robust and clear error message library that I can feel confident is accurate to the latest version in staging. 

As a designer, I want the content and design source of truth to be robust and correct. The Sketch file contains all states per field and possible alerts and error message a Veteran could potentially see.

---
## Tasks
- [x] Audit what is in the native design file/Sketch
- [x] Audit what exists on github for documentation of error states (CG Matrix and EZ Matrix)(Content source of truth EZ)(Content source of truth CG)
- [x] Note what is missing and needs to be collected
- [x] Review staging both authenticated and unauth paths to gather additional error content 
- [x] Review with team for any missing states/iterations needed

## Acceptance Criteria
- [ ] The 1010 team knows where to go for referencing any error states or messages a user could potentially come across
---

## Additional tasks added post-estimate
- [x] Update github files (Error Matrix) as a full set of errors source of truth in addition to Mural board created

**Comment by jessicastump** [comment]
I setup working audit spaces in Mural for both the [EZ](https://app.mural.co/invitation/mural/departmentofveteransaffairs9999/1683651181051?sender=uadf1ed7fe7c76f0914967329&key=eb1b6796-2eb1-4233-9b21-b42cbb2a1e2b) and the [CG](https://app.mural.co/invitation/mural/departmentofveteransaffairs9999/1683656893560?sender=uadf1ed7fe7c76f0914967329&key=17c753fa-7e1a-4198-ae51-0b558ac429c7). There is a brainstorming area for links from github or sketch that is found. Discovery/confirmation needed of what is in production and what is missing.

**Comment by hdjustice** [comment]
As much as I hate duplication, I think we should have GH updated, and I like your idea of the link to Mural.

**Comment by jessicastump** [comment]
Updated the tables on the Error Matrix GH pages

**Comment by jessicastump** [comment]
@hdjustice The full text and table sections of the Error Matrix GH files are updated to align with the full audit in Mural. I think at this time, we can close this ticket and these become living documents to update anytime there are changes to the error messages used.

**Comment by hdjustice** [comment]
Sounds great, thank you @jessicastump !!  I know it was tedious, but I am so glad to have it done.
