### ISSUE TITLE
Implementation: Write script to remove stale content-build images from EFS

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#58062]
Research for this ticket - https://vfs.atlassian.net/wiki/spaces/TT4/pages/2626420737/Discovery+Explore+how+to+create+an+EFS+Hosted+Persistent+Volume+for+Preview+Environments+56720#Identify-the-necessary-steps-to-synchronize-the-static-content-build-external-to-the-preview-environment-creation-process.

---
## Tasks
- [ ] Choose one of the following methods:
  - [ ] Create a GitHub Actions that would would run once a day and delete directories/files that are older than, say, 30 days (my preference because we've been using GHA for jobs like this)
  - [ ] Use a cron job on an EC2 instance
  - [ ] Use a scheduled AWS Lambda function

## Acceptance Criteria
- [ ] The chosen method for cleaning up old files and directories is implemented and operational
- [ ] The cleanup process successfully identifies files and directories older than 30 days in the EFS file system
- [ ] The cleanup process deletes the identified files and directories
- [ ] The cleanup process runs periodically (e.g., daily) as scheduled
- [ ] The EFS file system is maintained with only relevant content-build versions, removing stale versions automatically

**Comment by JoeTice** [comment]
These tickets are OBE as our approach is shifting, closing these tickets to reflect that.
