### ISSUE TITLE
Supplemental Claims | Add missing email error message on review & submit

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#58096]
## Value Statement
**_As a_** Veteran with filing a Supplemental Claim
**_I want to_** be notified that I'm missing my email address 
**_So that_** I can fix it and submit my claim 

---
## Background Context

While monitoring Supplemental Claim submissions, we noted one rejected submission with a missing email (empty string) address. This _should_ have been caught prior to form submission. We need to make changes to show a specific error message informing the Veteran that the email is missing, and ensure submission is blocked until it is rectified.

## Acceptance Criteria
- [ ] All tasks complete
- [ ] All tests passing
- [ ] User can submit a Supplemental Claims without missing crucial information and having it get rejected

## Designs and Build Notes
- After discussing this with Eileen, we're adding a "Missing email address" message on the review & submit page

## Out of scope
- Add here

## Tasks
- [ ] Add missing email error message
- [ ] Add required field schema for email
- [ ] Add analytics
- [ ] Unit tests updated
- [ ] e2e tests updated

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design
