### ISSUE TITLE
Build required content for Campaign Landing Page

### ISSUE THREAD

**Issue by CarlDickerson** [department-of-veterans-affairs/va.gov-team#58091]
The four required segments that you’ll use to build out your campaign landing page:

**Hero**: The Hero banner panel attracts attention, announces the campaign’s main message and adds visual interest. The hero panel includes a required CTA, and an option to add a large full-width image.

**Why this matters**: The Why this matters to you panel calls out the most impactful information about your campaign and the intended audience, e.g. If people read nothing else on the page, what should they know?

**What you can do**: The What you can do panel focuses on actions or steps that the CLP target audience can or should take. The panel includes up to three “promos” – content formatted as text and image teasers that engage attention and inspire further action.

**VA benefits**: Select and use at least one and up to two benefit blocks to give readers another way to link to important benefits information. Some things to remember:
This segment will always appear last, below any optional segments that may be used, and just above the footer.
The title text and blurbs are templated and not editable. 

## Acceptance criteria
- [x] Content has been added to the CLP

## Tasks
- [x] @skirkman draft content for why this matters and what you can do
- [x] @skirkman16 source hero image for CLP
- [x] Socialize content for review and approval
- [x] Update content based on feedback

**Comment by skirkman16** [comment]
Campaign landing page required elements have been drafted [here](https://docs.google.com/document/d/1NOWJlCCkYCatITpyS73-KgyLIZMzoWoxtW__6ClaHbo/edit?usp=sharing). Work has been shared with John in midsprint demo and team. Content will be shared with Sitewide on 5/18 in content sync or async. Lost access to edit Drupal on 5/16 and access still has not been restored. Once access has been regranted, updates will be implemented there.

**Comment by alevindecanini** [comment]
Per sprint demo on 5/25:

>Progress
Required elements have been reviewed by team and Sitewide and are now  live–hero banner, Why this matters section, and What you can do section
Progress can be followed at http://preview-prod.vfs.va.gov/preview?nodeID=56090

>Next steps
 Team will continue to  build out content on page 
Links to updated FAQs
Links to blog posts
Landing page will live at https://www.va.gov/initiatives/secure-sign-in/
