### ISSUE TITLE
UX Review: Identity Dashboard

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#58105]
### Description
As a developer looking to integrate with the Identity Team's SiS, I need to be able to navigate the developer pages so I can complete self-service tasks.  

### Tasks
- [x] review copy & flow (comments to be added in [Figma](https://www.figma.com/file/NgTUQowdoP3TsasZTHiwpu/Identity-Dashboard-(views)?type=design&node-id=0-1&t=eKioKYKZ6X1vW6ya-0))
- [x] comparison with login.gov and auth0 documentation pages
- [x] run through prototype with 1 back-end dev ([Identity Dashboard Walk Through Guide](https://docs.google.com/document/d/1l513nyKGusvQ-9mtEEVLdq5A8t9zWO-s7Nbdot-89IQ/edit?usp=sharing))

### Open questions:
- [ ] Any requirements for footer?

#### Acceptance Criteria
- [x] Reviewed by UX Team
- [x] Reviewed by PMs
- [ ] Documentation has been updated as needed
- [ ] Put published research in drive

### How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by charlye-bluetiger** [comment]
relevant links:

Login.gov
- Partner Dashboard
- Partner Documentation

VA.gov

- [Figma prototype](https://www.figma.com/file/NgTUQowdoP3TsasZTHiwpu/Identity-Dashboard-(views)?type=design&node-id=0-1&t=eKioKYKZ6X1vW6ya-0)
- [My Notion for Identity Dashboard](https://www.notion.so/Identity-Dashboard-df88e37083e44253980fb23970c74e90)
- Lighthouse Documentation site (footer info, not owned by our team & not auth-related)


Auth0
Identity Platform (I invited you as an Admin)
Identity Documentation

**Comment by charlye-bluetiger** [comment]
Added comments in the Figma for ease of updating/editing in real time.  @asg5704 do you need additional context?

**Comment by aparsley** [comment]
Looks good, thank you.
