### ISSUE TITLE
Discovery for making VAMC location field optional

### ISSUE THREAD

**Issue by lydiahooper** [department-of-veterans-affairs/va.gov-team#58102]
VAMC location field is causing errors that are preventing users from submitting 526 (see attached screenshots including of page before). Slack thread: https://dsva.slack.com/archives/C04KW0B46N5/p1683556195129599

Since operational policy is that VSRs/RVSRs are required to check all VAMCs for records, and since Veterans find it anxiety-provoking, we should consider removing this field or making this field optional. 
Slack thread: https://dsva.slack.com/archives/C053UDWMH7U/p1683564176716349

### Tasks
- [x] Discussions with stakeholders and Matt about this decision
- [x] If we decide to make this change, create annotated screenshot for pass-off to FE engineering

### Acceptance Criteria
- [x] Plan for improving this experience in 526
- [x] If we decide to make this change, create annotated screenshot for pass-off to FE

**Comment by lydiahooper** [comment]
![Screen Shot 2023-05-08 at 9.21.59 AM.png](https://images.zenhubusercontent.com/63dd30c43859c04de31f7608/4523a956-edea-43f3-8b6c-617e9f51c5af)

![Screen Shot 2023-05-08 at 9.21.48 AM.png](https://images.zenhubusercontent.com/63dd30c43859c04de31f7608/d28f5f53-c015-4e81-8182-9095ea942173)

**Comment by lydiahooper** [comment]
At meeting on 5/18/23, Alejandro confirmed that we can make the VA facility field optional, and he suggested we add language to clarify expectations for the user. He said there is no need to validate what they enter. 

Sketch file with annotated screenshot showing changes to make: https://sketch.com/s/5e464026-9acb-4f80-a4f9-634c7e972d19
