### ISSUE TITLE
Update Backend Orientation slide deck with current EKS setup

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#58100]
## Issue Description
As a VFS team member, I need the vets-api deployment/CD/EKS part of the Backend Orientation Slide Desk to be up to date so I can easily understand vets-api deployment/CD.

---
## Tasks
- [x] Update/replace old deployment/k8s/EKS slides with the current EKS scheme
- [x] Create a quick ArgoCD _tour_
- [ ] Lainey to complete review of feedback and link here if information is relevant for BE orientation

## Acceptance Criteria
- [x] The [slide deck](https://docs.google.com/presentation/d/1_ui4c8ucMMZhoQGCdX6Q6dPAa_gkSfwtswJMjrcbIdI/edit) is up to date with current deployment scheme
- [x] Argo CD information added to BE orientation

**Comment by rmtolmach** [comment]
Slide 8 shows a high-level overview of the process: https://docs.google.com/presentation/d/1_ui4c8ucMMZhoQGCdX6Q6dPAa_gkSfwtswJMjrcbIdI/edit#slide=id.g130c5b8cb4e_0_0

@LindseySaari, is this good enough or do we need something more?

**Comment by laineymajor** [comment]
https://vfs.atlassian.net/wiki/spaces/TT1/pages/2638250053/DISCOVERY+PREP+FOR+VETS-API+MAINTENANCE

**Comment by laineymajor** [comment]
Moving this to our next sprint as we deemed the timing more appropriate.

**Comment by LindseySaari** [comment]
Slide deck is updated with images and speaker notes!
