### ISSUE TITLE
Design an interaction for printing appointment lists

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#58115]
## Task Description
Design an interaction for printing a list of appointments.

## References
- [TBD - Product initiative doc]()
- [MHV print feature (Sketch file)](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/prototype/a/5CBE8AA6-D039-4084-88F8-88B99539B5EE)
- Dev ticket - #59730

## Acceptance Criteria
- [x] The print feature is associated with all lists.
- [x] The print feature triggers the browser's default print behavior
- [x] Checked in platform-design-system for existing print/toolbar patterns
- [x] Design spec complete for Small/Medium/Large screens
- [ ] Design specs include semantic annotations

## Design Spec
[Figma Link](https://www.figma.com/file/qm63ZVrjq6eohFpWnVqj7F/Add-Print-Button-to-Appt-List?type=design&node-id=1292%3A27826&mode=design&t=FZ8dSdC7vQGt1zpr-1)

**Comment by outerpress** [comment]
FYI @Cieramaddox I added the MHV print sketch file to the references

**Comment by outerpress** [comment]
This is in Collab Cycle. We are approved to do staging review only:
- [Collab cycle ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59429)

**Comment by outerpress** [comment]
@Cieramaddox could you ping [this ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1559) just so Matt is aware of our progress on this feature?
