### ISSUE TITLE
Create GitHub Issue form to request a product addition to the product directory

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#58112]
## Issue Description
Right now all products that are to be added to the product directory must either be manually added, or must have a manifest file that gets picked up in part of our automated scan. There may be products that have different code structure that we still want on the list, and the manual side of the process should be in the form of an approval, as opposed to explicitly adding it to the directory.

---
## Tasks
- [ ] Create Github issue form that submits a PR to add a product  to the product directory.
- [ ] Update product directory user guide with instructions on how to add a product to the directory.

## Acceptance Criteria
- [ ] A method exists for users to request an addition to the product directory and this method is documented.
- [ ] This method is based on our revamped decoupled-from-manifests approach
---
