### ISSUE TITLE
Add crosslinks on Pension pages to How to report a death of a Veteran R&S page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#58116]
## Issue Description

A VA Pension partner asked us to make the information that's now in our [How to report the death of a Veteran to VA](https://www.va.gov/resources/how-to-report-the-death-of-a-veteran-to-va/) R&S page more accessible on Pension pages. 

We need to review our pension pages and find places where we can add crosslinks. 

## Tasks
- [x] Assess pages to add crosslinks to
- [x] Add crosslinks in Drupal
- [x] Review (Laura)
- [x] Send to stakeholders
- [x] Copyedit (Megan)
- [x] Publish (Megan)
- [x] Notify stakeholders that changes are live

## Acceptance Criteria
- [x] Crosslinks have been added to live pension pages

**Comment by aliyahblackmore** [comment]
Hey @laurwill - before I go ahead and get these crosslink suggestions in Drupal, I'm sharing my assessment here and a few notes.

### **General notes:**


- The goal of the How to report a death to the VA page is to help surviving family members avoid overpayment debt. While this is the focus of this page, this page could also be a pathway for survivors to consider what benefits they’d be eligible for after the death of a Veteran. 

- As we chatted with Randi earlier in the week, you all mentioned that there wasn’t a requirement from partners that crosslinks be included on the body of pages. 

- Given the focus of the How to report page and the partners request, in my review of pension pages, I didn’t find instances of this link being related to content on pages or needing to be nestled in on the body of pages. I think we can make use of the More information sections or Related information sections to pull in this R&S page that’s relevant, but not necessarily the main focus on these pension pages.

If we’re pulling the How to report page into any More information sections, we’d need a sentence about the page that would exist after the link. 

**Suggested content:**

[Report the death of a Veteran to VA](https://www.va.gov/resources/how-to-report-the-death-of-a-veteran-to-va/)
Learn more about how to report the death of a Veteran to VA and make sure their survivors avoid debt from benefit overpayments.  

____ 

I did a review of pension pages from the [VA pension benefits hub](https://www.va.gov/pension/) and R&S and identified these potential pages. 

### **Pages**

https://www.va.gov/pension/survivors-pension/
**Notes**: Link in the More information section

https://www.va.gov/pension/pension-management-centers/
**Notes:** I think we’d want to consider pulling in a Related information section on this page and include the link to the Reporting a death page here. The majority of this page isn’t related to survivors, but the info under **Philadelphia VA Pension Management Center** mentions burial benefits and VA DIC. Having the Reporting a death page as a related info link could be an additional source that folks navigate to while on this page.

https://www.va.gov/claim-or-appeal-status/
**Notes:** Link in More information section, before the “Manage your VA debt” link. I think we'd want this before manage your debt because the hope with the Reporting a death page is that folks are taking a first step to avoid debt from overpayments.

https://www.va.gov/decision-reviews/
**Notes:** More information and resources section – I think we may also want to consider a change in order for the links - the appeals modernization act link, reporting the death of a veteran link, manage your VA debt link. I'm suggesting this change because the appeals link seems more related to the decision review/claims process.

https://www.va.gov/va-payment-history/
**Notes:** Survivors would be using this page to review past payments, so that means they’re already receiving benefits and perhaps have already reported the death. I don’t think we’d need this link on the body of the page, but we could pull it into the More information section before the Manage your VA debt link.

https://www.va.gov/change-direct-deposit/
**Notes:** Link in the More information section after Manage your VA debt link

https://www.va.gov/resources/how-are-pension-benefits-and-disability-compensation-different/
**Notes:** We can consider adding this as a Related information link

https://www.va.gov/resources/evidence-to-support-va-pension-dic-or-accrued-benefits-claims/
**Note:** We can consider adding this as a related information link, but we'd need to remove one of the current links (up to 5). I also considered including this as a note in the “Survivors pension evidence needed” or “Documents you’ll need to support your claim sections, but reporting the death of a Veteran, from my understanding, isn’t related to the evidence that’s needed for claims.

**Comment by aliyahblackmore** [comment]
Thanks Laura! 

**About VA DIC** 
http://preview-prod.vfs.va.gov/preview?nodeId=855
I added the link after the rates link in the more information section 


**VA Survivors Pension** 
http://preview-prod.vfs.va.gov/preview?nodeId=590
I reverted to the last published version (Megan 06/29/22 -2:40pm) to address the "linkies." Link is after the DIC benefits for surviving parents link.

**Comment by laurwill** [comment]
Sent suggestions to Angie via email.

**Comment by RLHecht** [comment]
Moving to blocked until we hear back from stakeholders.

**Comment by laurwill** [comment]
@megzehn the new More info links and teasers on these 2 pages are ready to copyedit and publish:
http://preview-prod.vfs.va.gov/preview?nodeId=855
http://preview-prod.vfs.va.gov/preview?nodeId=590

And @aliyahblackmore just noting a tweak I made — Beth flagged that these need to address the survivor audience directly, so changed "survivors" to "you" in both. We'll keep this in mind for future!

**Comment by megzehn** [comment]
Thank you, @laurwill and @aliyahblackmore! Confirming I reviewed these links and published them.

**Comment by laurwill** [comment]
I validated and notified Angie that these are live. Closing this out.
