### ISSUE TITLE
UX | Profile | Alert audit | Share messages with content team

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#58111]
## Background

The content community of practice is going to be holding an "error message retreat" later this month to update and refine our [error messages dictionary](https://design.va.gov/content-style-guide/error-messages/).  We'll spend a day writing, editing, and reviewing [VA.gov](http://va.gov/) error messages to make sure they meet our style and plain language standards. We'll then revise the style guide so that all teams have a single source of truth when using error messages for their products and tools.
I'm reaching out to product teams to ask for help with 3 things:
- Sharing any recent research your team may have done around error messages
- Sharing any error messages the Sitewide Content team may not have seen before or aren't currently in the error message dictionary
- Sharing feedback about what would be helpful to have in an error message dictionary

## Tasks
- [x] Identify any error messages that aren't currently in the error message dictionary
- [x] Share with @RLHecht via Slack
  

## Acceptance Criteria
- [x] Messages sent to Randi
