### ISSUE TITLE
Full Accessibility & 508 Office Audit [Appointments (VAOS)]

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#5812]
## Steps to complete the Full Accessibility & 508 Audit: 
- [ ] Using this template, create issue and fill in feature name in the title and other bolded information appropriately
- [ ] Make sure the issue is assigned to yourself, @1Copenut and @jenstrickland
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)

## Artifacts - _please provide the following artifacts when you request a full review_
- Link to where the feature lives on staging and link to any user testing credentials in https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/platform/accessibility
Testing link - https://staging.va.gov/health-care/schedule-view-va-appointments/appointments

- Link to test cases/test plan in TestRail and test execution logs in https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/platform/accessibility
https://github.com/department-of-veterans-affairs/va.gov-team/tree/f4f42f071e47712cc4e4af5db0b93a97ee3548c7/products/health-care/appointments/research

Testrail - https://dsvavsp.testrail.io/index.php?/auth/login/L3N1aXRlcy92aWV3LzIxJmdyb3VwX2J5PWNhc2VzOnNlY3Rpb25faWQmZ3JvdXBfb3JkZXI9YXNjLTYwZWY4NmFiZGM5MzRiZDJmMGViZTlkODI5ODA5YWZlOGQ1NGUwYWI1OTk1ZjE2MTY3MWM4ODdkYTVlOTVjN2E:

**Comment by 1Copenut** [comment]
Thank you @lenaecb . I'll keep you posted as the audit starts and progresses.

**Comment by lenaecb** [comment]
@1Copenut - In looking at our backlog it seems we've got a lot of audit tickets going on? Should I tag you in those and see what needs to move to this ticket vs. closed?

**Comment by 1Copenut** [comment]
Yes please, tag me in them, and for any that are accessibility related, I'll add them to an epic I'll create for the audit.

I like to keep the actual audit ticket separate from the "ask" to conduct it. It does create an additional item to keep track of, but the separation of concerns has worked well in the past.

**Comment by 1Copenut** [comment]
VA 508 office has been requested to review the new application in staging, Trevor will keep track of that progress and update the VAOS team of any changes.

**Comment by lenaecb** [comment]
@1Copenut - any update from the VA 508 office about the review? 

Thanks!

**Comment by 1Copenut** [comment]
@lenaecb Yes, I got feedback late Thursday PM. There's one issue I need to look into, and one that I sent back with a follow up question. Hoping that one gets waived. There might be one ticket come out of the full audit, but we look to be in good shape otherwise.

**Comment by lenaecb** [comment]
Great, thanks @1Copenut !
