### ISSUE TITLE
Create GitHub Issue form to request a product deletion from the product directory

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#58131]
## Issue Description
Right now all products that are to be deleted from the product directory must be manually deleted. Even if deleted, if they have a manifest file that gets picked up in part of our automated scan, it will be automatically readded. Teams want the ability to remove a product whether it's because they don't consider it a product, or for any other reason.
---

## Tasks
- [ ] Create Github issue form that submits a PR to delete a product from the product directory.
- [ ] Update product directory user guide with instructions on how to remove a product from the directory.

## Acceptance Criteria
- [ ] A method exists for users to request an removal from the product directory and this method is documented.
- [ ] This method is based on our revamped decoupled-from-manifests approach
---
