### ISSUE TITLE
Review and resolve [25-42+ Daily] of incoming issues (T2)

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#58155]
## Issue Description
_Define the number of issues to review and/or resolve weekly (per sprint) 

---
## Tasks
- [x] _Define which team members will participate
- [x] Determine approximate number of incoming issues to address daily
- [x] Update ticket with # of Issues closed/modified per sprint

## Acceptance Criteria
- [x] _confirmation of number of issues reviewed and resolved per sprint
- [x] Record in confluence when complete
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by edpearson20** [comment]
@manalo-soco Yes, this would/should be 25-42+ total daily for the team.  Of course, more case closures will cut into the backlog.

**Comment by manalo-soco** [comment]
Refer to [this ticket](https://app.zenhub.com/workspaces/contact-center-62cdd9546ec1530018209672/issues/gh/department-of-veterans-affairs/va.gov-team/59758)

**Comment by Kimberley2019** [comment]
The breakdown of average case totals are below:

- Daily total: 65
- T2 - 35
- T3 EVSS - 30
- T3 - 10
