### ISSUE TITLE
Tier 2 Process Definitions 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#58152]
## Issue Description

The reviewing and handling of Tier 2 cases is an ongoing process managed by the contact center support team. In partnership with the [new daily case review process and the ongoing development of the tier 3 process](https://dvagov.sharepoint.com/:w:/r/sites/Tier2779/Shared%20Documents/General/Defining%20Tier%203.docx?d=wc9ac757d04354130a5b0650a3bb5d71f&csf=1&web=1&e=zvlcIs), the tier 2 process needs to be documented to account for how tier 2 cases will be reviewed, resolved, or escalated to the appropriate channels.

---
## Tasks
- [x] Define the process for reviewing all incoming Tier 2 cases from incoming to resolution.
- [x] Address Tier 2 cases ONLY 
- [x] Define the cadence for addressing cases by incoming date.
- [x] Define how to manage Veteran follow--up
- [x] Define the requirements for closing/concluding a case or issue.
- [x] Define routing procedures for incoming cases
- [x] Define the process of closing cases
- [x] Define criteria for including detailed notes in Salesforce - including any attachments 
- [x] Define process for capturing all Veteran responses in salesforce to create and maintain entire case history

## Acceptance Criteria
- [x] _Publish a complete Tier 2 procedure document in Confluence.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by edpearson20** [comment]
Defining Tier 3 Document...
https://dvagov.sharepoint.com/:w:/r/sites/Tier2779/_layouts/15/Doc.aspx?sourcedoc=%7BC9AC757D-0435-4130-A5B0-650A3BB5D71F%7D&file=Defining%20Tier%203.docx&action=default&mobileredirect=true

**Comment by ATMiddleton** [comment]
@edpearson20 , @Solarith and @manalo-soco will meet next week to discuss tasks and next steps.

**Comment by edpearson20** [comment]
Scheduled to meet with Michael and Young, moving meeting to future date.  I will be championing the document and sharing for feedback.  Document will be completed within the by 6/8.

**Comment by edpearson20** [comment]
A draft document is currently prepared.  This document will incorporate an interim strategy, whereby we are closing cases in mass prior to the Salesforce Implementation, and Email Builder as a method of communicating with the Veteran.

https://vfs.atlassian.net/wiki/spaces/~428096154/pages/2668036113/VA.Gov+Tier+II+Technical+Support+Process

**Comment by edpearson20** [comment]
Document published

**Comment by edpearson20** [comment]
Tier 2 Process updated on June 27th.  Currently working on email handling outline.

**Comment by edpearson20** [comment]
Updated Tier 2 Process document with...
- Comment replies
- Outlook Email Inbox Handling https://vfs.atlassian.net/wiki/spaces/~428096154/pages/2668036113/VA.Gov+Contact+Center+Tier+2+Technical+Support+Framework#:~:text=Outlook%20Email%20Inbox%20Handling
- Action Items https://vfs.atlassian.net/wiki/spaces/~428096154/pages/2668036113/VA.Gov+Contact+Center+Tier+2+Technical+Support+Framework#%E2%9C%85-Action-Items

**Comment by manalo-soco** [comment]
Confluence updated:https://vfs.atlassian.net/wiki/spaces/~428096154/pages/2668036113/VA.Gov+Tier+II+Technical+Support+Process
