### ISSUE TITLE
Tier 3 Processes and Procedures

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#58153]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [x]  Define process to review incoming issues from VEO
- [x]  Define the requirements for closing/concluding a case or issue.
- [x]  Define routing procedures for incoming cases
- [x]  Define criteria for including detailed notes in Salesforce - including any attachments
- [x]  Define process for capturing all Veteran responses in salesforce to create and maintain entire case history

## Acceptance Criteria
- [ ] _Published documentation of entire Tier 3 process_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
Documents complete:

- [https://app.zenhub.com/files/133843125/8733c5ce-096a-45e0-89a8-8985fedb96be/download](https://app.zenhub.com/files/133843125/8733c5ce-096a-45e0-89a8-8985fedb96be/downlo[https://app.zenhub.com/files/133843125/073bfb9a-10c4-492b-8834-57e310b95a5a/download](https://app.zenhub.com/files/133843125/073bfb9a-10c4-492b-8834-57e310b95a5a/download)ad)
