### ISSUE TITLE
[FE] Profile 2.0: Investigate saving contact information

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5815]
## Background

In the profile right now, we save information asynchronously and close the contact information modal before information successfully saves. We want to investigate whether we need to do that for profile 2.0.

## Tasks

- [ ] Investigate whether we can keep the modal open to see if save is successful before closing.
- [ ] Determine how we should move forward.

## Acceptance criteria

- [ ] Investigation is complete and next steps have been determined

**Comment by erikphansen** [comment]
I'm going to close this ticket since it was really a research spike to determine how feasible it would be to have a nicer save experience for Profile 2.0. The conclusion is that it's totally feasible.

Later today I'm going to demo an updated version of saving on the current profile. We can decide if we'd like to turn my work into a real PR and roll it out to production after the demo.
