### ISSUE TITLE
[eFSR] Testing - WAVE spot checks & Code quality review

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#58163]
## Issue Description
Prepare for accessibility staging review time!
[Documentation WAVE](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review#Prepareforanaccessibilitystagingreview-WAVEspotcheckswave)
[Documentation Code quality](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review#Prepareforanaccessibilitystagingreview-Codequalityreviewcode-quality)

Complete testing and note any issues to be addressed prior to staging review. 

---
## Tasks
- [x] Complete testing as detailed in documentation
- [x] Write up any issues in this ticket that need addressing
- [x] Categorize any issues that need to be completed prior to staging review

## Acceptance Criteria
- [x] Testing completed 
- [x] Any issues discovered are documented
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by OptionSelect** [comment]
![Screenshot 2023-05-22 at 9.14.51 AM.png](https://images.zenhubusercontent.com/61fc34bdeb6088eace717afe/3f2d4b2c-a239-4a6b-b025-a10fa60b25a5)

![Screenshot 2023-05-22 at 9.16.18 AM.png](https://images.zenhubusercontent.com/61fc34bdeb6088eace717afe/63397d3a-4ea6-402c-86bc-4af46c29ad50)

![Screenshot 2023-05-22 at 9.18.12 AM.png](https://images.zenhubusercontent.com/61fc34bdeb6088eace717afe/0d6e46be-fab6-4842-b3bf-e492b92c5a4f)
