### ISSUE TITLE
[eFSR] Testing - Automated testing with axe by Deque

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#58161]
## Issue Description
Prepare for accessibility staging review time! 
[Documentation source](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review#Prepareforanaccessibilitystagingreview-AutomatedtestingwithaxebyDequeaxe)

Complete testing and note any issues to be addressed prior to staging review.

---
## Tasks
- [ ] Complete testing as detailed in documentation
- [ ] Write up any issues in this ticket that need addressing
- [ ] Categorize any issues that need to be completed prior to staging review

## Acceptance Criteria
- [ ] Testing completed 
- [ ] Any issues discovered are documented
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by OptionSelect** [comment]
Went through the entire form. We have 0 axe Deque violations it seems! Screenshotted various screens as I went through it.

![Screenshot 2023-05-25 at 9.20.51 AM.png](https://images.zenhubusercontent.com/61fc34bdeb6088eace717afe/5e150e1c-7b74-41e4-9514-33b0195c051b)
