### ISSUE TITLE
[FE] Profile: Refactor direct deposit form

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5816]
## Background

Epic #4068

## Tasks
- [x] Make a new version of the direct deposit component that wraps a `SchemaForm` component and does not use any `Errorable` form components

## Acceptance Criteria:
- [ ] Should function the same as the existing direct deposit component.
- [ ] Needs to be able to live alongside the existing direct deposit form (ie, behind a feature flag or some other method so the form can be put on staging but not prod)

**Comment by erikphansen** [comment]
@Samara-Strauss or @mshea0606 this can be validated on staging now. Basically we just want to make sure it still works: you can update DD info if you enter valid bank info but if you enter bad or missing info you can't update the DD info. Info on accessing the feature is here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit#how-to-access-and-test

**Comment by Samara-Strauss** [comment]
I was able to save/update my info.

I did notice this bug

1. With user 226, I edited my bank info.
2. I entered 325070760 for the routing number and 123456789 for the account number.
3. I clicked save. When I reopened the form after saving my new information, all the fields were filled in. **Desired behavior**: Those fields should always be blank in the form when the form opens. However, this did fix itself when I refreshed the page and opened the form — it was blank again just like it should be.

Let me know if you have any questions.

**Comment by erikphansen** [comment]
Thank you Samara! Another great catch. Will fix.

**Comment by Samara-Strauss** [comment]
>  Another great catch. Will fix.

I have a weird gift for finding bugs. You're welcome 😂 And, of course, thanks for taking care of this!

**Comment by erikphansen** [comment]
@Samara-Strauss sorry I should have let you know days ago that the bug you found has been addressed and can be validated on staging.

**Comment by Samara-Strauss** [comment]
Fixed! Closing.
