### ISSUE TITLE
[eFSR] Update installment contract page order

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#58160]
## Issue Description
Change order of installments and credit card bills steps so that credit card bills comes first and installment contracts comes next.

[Design reference ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/55628)

---
## Tasks
- [ ] Move Credit Card Bills page(s) before Installment Contracts
- [ ] Update e2e tests so order is reflected

## Acceptance Criteria
- [ ] Credit card pages come before installment contracts
- [ ] All tests passing
  - [ ] e2e
  - [ ] unit
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
