### ISSUE TITLE
Parse new statement file to get email addresses for existing Veteran profiles

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#58164]
## Issue Description
The format of our medical copay notifications endpoint is that VBS will send an ASCII encoded file that contains all the information needed to get a Veteran's email address and send them an email via VA Notify.

The format of the file is as follows (sample data):

```
[
  {
    "veteranIdentifier": "1005534532",
    "identifierType": <edipi/dfn>
    "facilityNum": "585HB"
    "facilityName": "Sault Saint Marie VA Clinic",
    "statementDate": "04/14/2023"
  },
]
```

This code will be initially executed within `MedicalCopays::VBS::Service#send_statement_notifications(statement_json)` called from the medical copays controller.

The bulk of this execution should be behind a background job due to the possible size of the file to be parsed and the API calls that will happen to prevent timeout from VBS client.

---
## Tasks
- [x] Decode file from request body
- [x] Parse JSON from file in `MedicalCopays::VBS::Service#send_statement_notifications(statement_json)`
- [x] Generate background jobs for each row to potentially send VA Notify email request

## Acceptance Criteria
- [x] Parsing logic for new statement file is completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Code is completed but blocked until this PR is merged

https://github.com/department-of-veterans-affairs/vets-api/pull/12622

**Comment by HeatherRienks** [comment]
@ScottyRJames -any update on this PR?

cc: @Tom-Davis

**Comment by ScottyRJames** [comment]
@HeatherRienks Remains blocked by the PR below. Reached out to Trevor and he said he will review today (5/22)

https://github.com/department-of-veterans-affairs/vets-api/pull/12622

**Comment by HeatherRienks** [comment]
@ScottyRJames - Just checking to see if this is ok to be marked as "closed" now (I am pretty sure it has been merged, so I am closing since it's the end of the sprint, but if I am wrong, please let me know!) Thanks!

cc: @Tom-Davis
