### ISSUE TITLE
Reconfigure `vets-website` to use EKS service name for `vets-api`

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#58174]
# Description
Currently, in our Preview Environments, the Frontend (FE) and Backend (BE) are hosted in separate pods. Due to the fact that localhost networking is not functional in our testing, we need to configure the FE to make requests to the BE using the service name -- http://vets-api-web:3004.

This setup mirrors a local deployment to sidestep the need for a revproxy resource configured for each PE and theoretically simplify Docker image setup. In a local environment, the web server users interact with is served up from content-build, and vets-website resources are served by the content-build web server using a symlink to the vets-website resources.

We are currently bypassing the fetching of the Drupal cache in our content-build due to the process being long and unpredictable. Instead, we're utilizing a content-build cache archive retrieved from an S3 bucket and extracted into our PE's content-build folder.

For testing, a locally generated image has been used, but we need to avoid that in future as some environment variables assigned in the GHA workflow are now used in the startup script for the FE container.

## Context
* PEs are setup like a local deployment in order to --
   * avoid the need for a `revproxy` resource configured for each PE
   * simplify the Docker image setup (in theory)
* In a local environment setup, the web server that users hit is served up from `content-build`
* `vets-website` resources are served up by the `content-build` web server using a symlink to the vw resources
* We are avoiding the fetching of the Drupal cache in our `content-build` because the process is long and unpredictable
* We are using a content-build cache archive retrieved from an S3 bucket and extracted into our PE's content-build folder
* I have been using a locally generated image for testing, but we should avoid that in future because some environment variables assigned in the GHA workflow are used in the startup script for the FE container now

# Tasks:
- [x] Develop a method to configure the FE to make requests to the BE using the service name
- [x] Test the configured setup to ensure requests are being properly directed
- [x] Implement the new setup into the existing system, replacing the localhost networking setup
- [x] Test the system thoroughly to ensure all components are functioning as expected
- [ ] Document changes made to the system setup for future reference

# Acceptance Criteria
- [ ] vets-website is able to successfully make requests to the API over http://vets-api-web:3004
- [ ] The system is stable, and no critical issues or regressions are introduced by these changes
- [ ] The new setup for FE to make requests to the BE using the service name is well-documented
- [ ] Tests confirm that the FE-BE communication is functioning as expected across different scenarios

**Comment by pjhill** [comment]
Experimental data point --
Perusing the code that previous engineers have used to spin up Codespaces and Review Instances, it looks like in order to set a custom API endpoint with `content-build` you need to set it at build time and not while serving the content. Unfortunately, the build step takes a very long time.  We will need to --
1. Stage the cache locally before running build so that it doesn't try to retrieve it over the slow network connection (~45 mins)
2. Remove the cache retrieval from the build script by creating a customized preview environment build script for `content-build`

**Comment by CBonade** [comment]
So, this has been in the works for the past week or so and we've learned a lot.

- vets-website has support already implemented for passing a custom API route using the `--api` argument structure.
- passing this to vets-website alone was not enough to get this to change in the final, served version of va.gov local.
- content-build needs the route passed to it as well, which also supports an `--api` environment variable.
- content-build not being built at runtime, via us fetching a prebuilt version, does not permit this to be set on build.
- the decision was made that we need to build content-build at runtime, but we will fetch an archived drupal cache instead, to save on the overall time to not have to fetch it directly from drupal.
