### ISSUE TITLE
[FE] Profile: Release new profile forms to production and remove old legacy code

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5817]
## Background

See epic - (Refactor Vet360 Profile form components to use SchemaForm #4068)

## Tasks

- [x] Release new profile forms to prod
- [x] Remove legacy code

## Acceptance criteria

- [x] Items listed above are complete

**Comment by erikphansen** [comment]
Merged!! I will monitor analytics again to make sure the PR to remove the feature flag and blow away the old forms entirely didn't somehow break things and then close this out tomorrow
