### ISSUE TITLE
IAM automation script

### ISSUE THREAD

**Issue by holytoastr** [department-of-veterans-affairs/va.gov-team#58184]
## Issue Description
The login.gov adoption team, stakeholders, and VA leadership need to review data and analyze CSP counts and CSP method changes to track login.gov adoption.

## User Story
As a Product Owner
I want to know the total user counts by CSP accessing the va.gov ecosystem as we progress through the migration
So that we can track adoption.

---
## Tasks
pre-process script automation
- [ ] clean up (or re-write) script to pre-process IAM data exports
  - [x] Ingests CSV files
  - [x] Outputs CSV files
  - [x] Updates map file
  - [ ] Generates file tracking login methods 
- [ ] ensure script has access to network drive: \\vacohsm01.dva.va.gov\VACO_Workgroups\Information & Technology\OCTO Digital Experience\ETL
- [ ] enable auto-detection of IAM data exports to initiate pre-process and load into Domo
- [ ] implement a hand-off to Domo Workbench workflow

## Acceptance Criteria
- [ ] Process automated on regular weekly cadence

**Comment by alevindecanini** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Logingov-adoption-Team-632280b31e745000136a61fc/issues/department-of-veterans-affairs/va.gov-team/58184?planning-poker) with Zenhub @holytoastr @sdickson-gt
