### ISSUE TITLE
[Design] MDT- C2 P2 Select supplies, accessories - Additional research

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5818]
## Task
- Meet with DLC
- Confirm accessories
- Ask what categories would they like to display on the new tool 

## AC
- [ ] Define accessories that will be included in the MVP 
- [ ] Define accessories that will be included in the Long term vision
- [ ] Both will be documented into GH

**Comment by rebeccawalsh** [comment]
Additional research came in the form of a meeting with the DLC, notes can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/meetings/20200220-DALC-stakeholder-meeting.md

MVP: Decoupled accessories (domes, wax guards, dessicant, cleaners) without categories from the past 2 years

We will move forward with this information on the accessories page for next sprint.
