### ISSUE TITLE
Add new statement notification template to VA Notify

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#58189]
## Issue Description
Once we have updated the verbiage of the new statement email for the medical copays tool we will need to add this to the existing VA Notify templates under the DMC service and add the template to our devops config.

---
## Tasks
- [x] Obtain final copy of new copay copy
- [x] On VA Network login to VA Notify and create template in staging and prod
- [x] Copy template IDs
- [x] Add template ID to staging and prod devops settings

## Acceptance Criteria
- [x] There exists a usable new copay email template to be referenced in API code
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
