### ISSUE TITLE
Drafting Platform website incident order of operations

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#58190]
## Issue Description
During the last team retro, we discussed some learned lessons from our experience with a recent incident with the Platform website's deployment tools.

Some ideas we discussed during team retro:

- Create an incident management order of tasks if the Platform website and/or scroll viewport go down again.
- Carefully document which Slack channels to post on, leadership (Oddball leaders, Erika/PO
- how we kept reviewing new documents even though we couldn't deploy, etc.)
- what time is a "cut off" to send the message to Platform teams about deploy not working
- For example, send the communication by 5pm ET. 

Link to Zen Hub task from 5/8/23 incident: https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/58071

## User Story

As a platform content team member,
I want to know what steps to take if the website goes down again,
So that I can take the appropriate steps to handle an ongoing incident, communicate to the appropriate people in a timely manner when it happens again.

---
## Tasks
- [x] On a team document in Confluence, document the steps we would take whenever we are unable to deploy changes to the the Platform website due to a technical incident. See ideas we wrote down above on this card and [this Zen Hub card](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/58071)
- [x] Incorporate any ideas that may be important for our team to do in this situation
- [x] Share the document with rest of team via Slack to incorporate Confluence comments

## Acceptance Criteria
- [x] Each person on our team would be able to follow the instructions of this document on their own, if needed.
- [x] Link to document: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2677407817/Platform+Website+Incident+Order+of+Operations
