### ISSUE TITLE
Share TAP Recommendations

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#58193]
[TAP Recommendations](https://app.zenhub.com/files/133843125/e68a2ebf-038c-41b3-81b1-c63a2e0bd8ac/download) were presented in Demo on 5/10 and shared with John.
TAP Curriculum needs to be sent to MHV to confirm recommendations and make other content updates as they see fit. After MHV has reviewed, TAP can be sent to John for a final look over and then to Melissa Rebstock, Laurie Baker and Dr. Hill.

## Acceptance Criteria
- [ ] final updates sent

## Tasks
- [x] meet w/ Ngozi and send her the TAP Curriculum to review and make recommendations
- [ ] send PDF to John
- [ ] send final draft of recommendations to Melissa, Laurie and Dr. Hill

**Comment by skirkman16** [comment]
Met w/ Ngozi on 5/15 and discussed MHV pages that need to be updated. Ngozi will discuss these changes with Carnetta and send the doc back to us with her recommendations.

**Comment by skirkman16** [comment]
Ngozi is hoping to meet with Carnetta today to discuss changes

**Comment by alevindecanini** [comment]
Sofia will check on urgency/timeline requirements
