### ISSUE TITLE
[Development] 526: Final Fixes to Claims Status Based on EVSS Status Type Feedback

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#5819]
## User Story or Problem Statement
As a veteran, I need be able to see the status of my claims without errors/default status being shown so I can actually know the true status of my claim.

This is a follow-up to #5123 where we submitted a PR related to status type.  However, there may be some more work to clean this up based on what EVSS has to say.  

`wss-claims-services-web-3.6/rest/vbaClaimStatusService/getClaims`

Slack convo was started here:

https://dsva.slack.com/archives/C8R3JS8BU/p1581524670102800 (not a thread but it should get us close enough to the convo to follow along)

## Tasks
- [ ] Review `wss-claims-services-web-3.6/rest/vbaClaimStatusService/getClaims` endpoint claims status
- [ ] Code up a more robust claims status conditional to make sure we don't go to the default status.

## Acceptance Criteria
- [ ] Updated code deployed with updated claims status checks

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by vhenry07** [comment]
Closing as worked tracked in another ticket.
