### ISSUE TITLE
My VA: Sprint 16 (8/2/23 - 8/15/23)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#58198]
## Priorities
_At the end of this sprint, what do we want to have accomplished/delivered?_
1. Release notification component on My VA
2. Begin phased launch of CST migration
3. Begin code clean up on My VA

# **Onsite Notifications**

## Notification Component (#59398)
_Note: We cannot proceed with release activities until GA issues are sorted out_
**PM**
- [ ] #60871 (_from previous sprint_)

**FE**
- [ ] #60845 (_tbd - may require additional GA work on our side, pending analytics meeting next week_)
- [x] #58222 (_from previous sprint_)
- [ ] #62132 (_from previous sprint_)

## Onsite Notifications v2 (#50758)
**Research & Design**
- [ ] #62744 
- [x] #62995 

# **My VA**

## Claim Status EVSS > Lighthouse (#54403)
**PM**
- [x] #61316
- [x] #61318
- [x] #61319

**FE**
- [x] #61318
- [x] #61319

## My VA Audit UX Improvements (#41934)
**FE**
- [x] #60637 (_from sprint 14 - validation only_)
- [ ] #60329 (_from previous sprint_)
- [ ] #60360
- [x] #62994

## MHV Migration Support (#62258)
**BE**
- [x] #58647

## Benefit Application Drafts Enhancements (#60509)
**FE**
- [ ] ~#62874~

**BE**
- [ ] #62897 

## General (#31611)
**Research & Design**
- [ ] #49605
- [ ] #49509
