### ISSUE TITLE
My VA: Sprint 15 (7/19/23 - 8/1/23)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#58195]
## Priorities
_At the end of this sprint, what do we want to have accomplished/delivered?_
1. Release component
2. Begin phased launch of CST to lighthouse
3. Discovery on benefit application drafts

PTO
- AJ 7/24 -7/28
- Samara 7/31

# Onsite Notifications

## Notification Component (#59398)
**PM**
- [ ] #60871
- [ ] #62132

**FE**
- [ ] #60845 (_from previous sprint - validation only once DST completes their work_)
- [x] #61399 (_from previous sprint - validation only, waiting for DST deployment_)
- [ ] #62132
- [ ] #58222 

## Notification Center (#58425)
**FE**
- [ ] #60400 (_from previous sprint_)

**BE**
- [ ] #60639 (_from previous sprint_)

# My VA

## Claim Status EVSS > Lighthouse (#54403)
**PM**
- [x] #61313
- [ ] #61316
- [ ] #61318

**FE**
- [ ] #62397 
- [ ] #61318 

**BE**
- [x] #62025  

## My VA Audit UX Improvements (#41934)
**Design**
- [ ] #62519 

**FE**
- [x] #60886 
- [ ] #60329 
- [x] #62492

## MHV Migration Support (#62258)
**Design & Research**
- [ ] #62255

**FE**
- [ ] #60327

## Benefit Application Drafts Enhancements (#60509)
**Design & Research**
- [x] #60510
- [x] #57185
- [x] #57184

**Comment by ajakabcin** [comment]
Order of operations 😎 

**Design & Research**
1. Unread messages design work #62255 
2. Benefit application drafts documentation work #60510 
3. Benefit application drafts discovery work: #57185 and #57184

**Devs**
@dellerbie 
1. Finish up #60639 
4. CST to migration EVSS > Lighthouse documentation #62025 
5. Audit code or My VA code cleanup # 60886
6. Impact of MHV migration on My VA code discovery  (FE) #60327 

@allisonlu 
1. Finish up NC mock data ticket #60400 
2. Component build/release process documentation #58222 
3. Update My VA alerts and warnings (once component is released) #60329
