### ISSUE TITLE
My VA: Sprint 17 (8/16/23 - 8/29/23)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#58199]
## Priorities
_At the end of this sprint, what do we want to have accomplished/delivered?_
1. Prep for notification indicator experiment
2. CST EVSS > LH: Continue phased launch of CST migration
3. Launch component
4. Support MHV migration: Update appointments links + Cerner message
5. Bene application drafts updates

PTO
- Samara 8/18

# Onsite Notifications

## Unread Messages Dot Indicator (#63788)
**Design & Research**
- [x] #63751
- [x] #63752

**FE**
- [x] #63753
- [ ] #63775 

## Notification Component (#59398)
**PM**
- [ ] #60871 (_from previous sprint_)

**FE**
- [ ] #60845 (_from previous sprint_)
- [ ] #62132 (_from previous sprint_)

# My VA

## Claim Status EVSS > Lighthouse (#54403)
**PM**
- [x] #61320
- [x] #61322

**FE**
- [x] #61320
- [x] #61322

## MHV Migration Support (#62258)
**Design & Research**
- [x] #63399

**FE**
- [x] #63401
- [ ] #63400

## My VA Audit UX Improvements (#41934)
**FE**
- [ ] #60329 (_from previous sprint - release/remove component only_)
- [x] #60360 (_from previous sprint_)
- [ ] #62899

## Benefit Application Drafts Enhancements (#60509)
**PM**
- [x] #63381

**FE**
- [x] #63379

**BE**
- [x] #62897 (_from previous sprint_)

## My VA LOA1 Updates (#63424)
**Research & Design**
- [ ] #63420

## General (#31611)
**Research & Design**
- [ ] #49509

**Comment by ajakabcin** [comment]
Order of operations for the sprint 😎 

@aagosto90 
1. Finalize design details for dot indicator experiment (#63751)
2. Documentation updates for health care section: dot indicator experiment (#63752) and MHV phase 1b support (#63399)
3. LOA1 design updates (#63420)
4. Explore designs for multiple claims (#49509)

@dellerbie 
1. Continue Save in Progress research (#62897)
2. Implement feature flag to hide the "what benefits does VA offer" section (and hide it for all users)  (#63379)
3. Update health appointment links (#63401)
4. Resume code cleanup of My VA (#62899)
5. _(Ongoing) Assist in phased launch of CST lighthouse migration: #61320 and #61322_ 

@allisonlu 
1. Prep for dot experiment: #63753 and #63775 
2. Cerner alert update #63400 
3. If bandwidth allows, pull in #62294
