### ISSUE TITLE
Certificate Support: Add documents in the how-to for certificates expiration tracking for all environments.

### ISSUE THREAD

**Issue by tuongngova** [department-of-veterans-affairs/va.gov-team#58208]
## Certificate Support: Add documents in the how-to for certificates expiration tracking for all environments.

As a DevOps engineer, I need to be able to track the certificates expiration so the certificate updates can be well prepared ahead of time. This is critical for DevOps to be able to prioritize because certificate is needed to keep communication with partners active.

## Devops tasks
- [ ] Develops table for certificates expiration for all environments  
- [ ] Indicate the active certificates that the team support for each environment.
- [ ] Indicate the exact location of each certificate, whether in Parameter Store or github repo
- [ ] Indicate whether the certificate is representing ourselves or it's the partner's certificates
- [ ] Indicate the CN of the certificate
- [ ] Indicate the expiration date of the certificate

## Acceptance Criteria
- [ ] Develops table for certificates expiration for all environments  
- [ ] Indicate the active certificates that the team support for each environment.
- [ ] Indicate the exact location of each certificate, whether in Parameter Store or github repo
- [ ] Indicate whether the certificate is representing ourselves or it's the partner's certificates
- [ ] Indicate the CN of the certificate
- [ ] Indicate the expiration date of the certificate
- [ ] Documentation has been updated
- [ ] Next steps have been determined and documented
- [ ] AC1
- [ ] AC2

#### Tech notes

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
