### ISSUE TITLE
My VA: Sprint 19 (9/13/23 - 9/26/23)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#58201]
## Priorities
_At the end of this sprint, what do we want to have accomplished/delivered?_
1. Remove notifications section on My VA
2. QA LOA1 updates + PSIRR
3. Tech debt

# Onsite Notifications

## Unread Messages Dot Indicator (#63788)
**PM**
- [x] #65515

## On-site Notifications v2 (#50758)
**Design/Research**
- [x] #65514

## Notification Component (#59398)
**PM**
- [ ] #65504

**Research & Design**
- [x] #64559

**FE**
- [x] #65503 
- [x] #60845 (_from previous sprint - blocked_)

# My VA

## MHV Migration Support (#62258)
**FE**
- [x] #65508

## My VA LOA1 Updates (#63424)
**PM**
- [x] #63428 (_from previous sprint_)
- [x] #63429
- [x] #66180 

**FE**
- [x] #63422 (_from previous sprint - validation only_)

## Unit & E2E Test Improvements (#61602)
**FE**
- [x] #57478
- [x] #57468
- [x] #57476
- [x] #57474 
- [ ] #57470 
- [ ] #57462 

## My VA Audit UX Improvements (#41934)
**FE**
- [x] #60329 (_from previous sprint - release/remove flag only_)

## General (#31611)
**FE**
- [ ] #62294 

**BE**
- [ ] #64468
