### ISSUE TITLE
Look into interference with dev.va.gov

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#58209]
# Description
We have been experiencing some issues causing interference on dev.va.gov. This investigation aims to identify the root cause of these problems and implement a resolution to restore the smooth operation of the platform.

Perhaps some aspect is cross-wired.

Ticket with error messages:
https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/58113

# Tasks
-  Identify the symptoms and the potential areas affected by the interference
-  Analyze logs, error reports, or any other available data to gather clues about the source of the issue
-  Replicate the interference in a controlled environment if possible to understand the problem better
-  Identify the root cause of the interference
-  Resolve the identified issue
-  Conduct extensive testing to ensure the issue is fully resolved and no new issues are introduced
-  Document the problem, its root cause, and the implemented solution
-  Close the [bug ticket](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/58113) associated with this issue

# Acceptance Criteria
-  [ ] The root cause of the interference on dev.va.gov has been correctly identified
-  [ ] A resolution plan has been developed and successfully implemented
-  [ ] The implemented solution has been tested and verified, ensuring the interference issue is fully resolved and no new issues have been introduced
-  [ ] Documentation exists detailing the problem, its root cause, and the implemented solution
-  [ ] The bug ticket associated with this issue has been closed
-  [ ] No further reports of the same interference are received after the resolution

**Comment by pjhill** [comment]
PR to turn off one instance of PE that we were using for testing while we troubleshoot the issue -- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1926

**Comment by cyriltech** [comment]
Attempt to login to Datadog was not successful. The plan is to login and test to;
1.  see the trend of error in last 15 days
2.    Check if error goes down since we uninstalled the app from PE few hours back
then Check if reported users are still facing the error and how do i replicate.

**Comment by cyriltech** [comment]
Thanks to Lindsey for providing some clue on what could be causing the interference. [Thread](https://dsva.slack.com/archives/C04CYC4LMU6/p1684785138029189). [Role](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/applications/platform-eks-clusters/iam.tf#L208-L217) needs to be modified to grant preview-environment namespace permissions to use vets-api service account

**Comment by JoeTice** [comment]
Completion of this ticket is blocked in Sprint 27 waiting for Datadog access

**Comment by cyriltech** [comment]
Access to Datadog granted. After checking Datadog logs and other things , I identified that request was landing to the vets-api in PE which doesn't have any permission granted to perform any action on AWS and hence resulting to the error of 403 unable to assume the sts role.  I've created the [PR](https://github.com/department-of-veterans-affairs/devops/pull/13068) in Devops repo for applying the policy.  I'm figuring out how can i run the terraform plan for that path.

as a next stepI'll be granting the application access and deploying it again to the preview env and deleting the ingressroute for pe to check if it still gets the conflict and if yes then debug the potential root cause.

**Comment by cyriltech** [comment]
Quick update on this, I have re added vets-api chart, values and secret. [PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1959). Not sure how to do terraform init within the terraform/applications/eks-clusters path to add permission for preview-environment since it requires a value.

**Comment by cyriltech** [comment]
Vets-api for preview environment has been up and running since Friday June 2. No user have complain about login issues yet. I changed the ingress route hostname to exclude traffic coming into vets-api preview-environment. Will confirm with users today before marking this issue as resolve.

**Comment by pjhill** [comment]
No reports of interference for several business days now -- closing as resolved!
