### ISSUE TITLE
BE | Profile | MHV Integration | Determine validation rules for contact info

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#58204]
## Background
As per Carnetta Scruggs...

Going forward, MHV emails need to be merged into VA.gov.  We need to make sure that the validation rules are documented and in sync.

## Tasks
Document validation rules for the following:
- [ ] Email address
- [ ] Phone numbers (home, work, and mobile)
- [ ] Addresses (residential, correspondence)
  

## Acceptance Criteria
- [ ] Send validation rules Jason Boire
- [ ] Review with PM

**Comment by mtcA6** [comment]
[Duplicates](https://github.com/department-of-veterans-affairs/va.gov-team/issues/58205) closing this one out
