### ISSUE TITLE
My VA: Sprint 18 (8/30/23 - 9/12/23)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#58200]
## Priorities
_At the end of this sprint, what do we want to have accomplished/delivered?_
1. Execute notification indicator experiment (health unread messages)
2. Exploration of personalization elevation
3. My VA LOA1 enhancements
4. Launch notification component (pending GA issues)

PTO
- Labor Day 9/4
- AJ 9/8
- Angela 9/8
- Derrick 9/6 - 9/8
- Tom 9/1

# Onsite Notifications

## Unread Messages Dot Indicator (#63788)
**FE**
- [x] #63775 (_from previous sprint_)

## Onsite Notifications v2 (scaling) (#50758)
**Research & Design**
- [x] #64569 

## Notification Component (#59398)
**PM**
- [ ] #60871 (_from previous sprint - blocked_)

**Research & Design**
- [ ] #64559

**FE**
- [ ] #60845 (_from previous sprint - blocked_)
- [ ] #62132 (_from previous sprint - blocked_)

# My VA

## My VA LOA1 Updates (#63424)
**PM**
- [x] #64499
- [ ] #63428 

**FE**
- [ ] #63422 

## Claim Status EVSS > Lighthouse (#54403)
**PM**
- [x] #63290

## MHV Migration Support (#62258)
**FE**
- [x] #63400 (_from previous sprint_)

## My VA Audit UX Improvements (#41934)
**FE**
- [ ] #60329 (_from previous sprint - release/remove component only_)
- [x] #62899

## Unit & E2E Test Improvements (#61602)
**FE**
- [x] #57477
- [x] #57479 
- [ ] #57478

## General (#31611)
**Research & Design**
- [x] #63785
- [x] #64557 

**FE**
- [ ] #62294

**BE**
- [ ] #64468

**Comment by ajakabcin** [comment]
Order of operations for sprint 18 🥳 

@aagosto90 - I don't think there's any reason (urgency wise) to pick your work up in a particular order. Perhaps coordinate with Liz and Pam on [64569](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64569) to see what works best schedule wise, otherwise proceed as you wish! :) 

@allisonlu 
1. LOA1 updates #63422 
2. moment.js library update #62294
3. FE unit tests on the debts components #57478 

@dellerbie 
1. Wrap up the cerner alert update (63400) and the audit ux clean up part 2 (62899)
2. BE code ownership verification #64468 
3. FE unit tests on claims and appeals components #57477 
4. FE unit tests on the education and training components #57479
