### ISSUE TITLE
Design System Staging Review for converted components Radio button, Checkbox and Checkbox group

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#58203]
## Design System Staging Review
The DST has been working on converting USWDS v3 components. This staging review request is for 3 of those components: 

- Radio button
- Checkbox 
- Checkbox group

**Here are links to Storybook and Sketch for each of the components.** 
Radio button
Storybook - https://design.va.gov/storybook/?path=/docs/uswds-va-radio--default 
Sketch - https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/QbgQ5l8

Checkbox 
Storybook - https://design.va.gov/storybook/?path=/docs/uswds-va-checkbox--default 
Sketch - https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/KvVOjxr 

Checkbox group 
Storybook - https://design.va.gov/storybook/?path=/docs/uswds-va-checkbox-group--default
Sketch - https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/KvVOjxr 

  
#### Design System actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [ ] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the Design System meeting attendees email addresses
      - Invite all relevant Design System team members
   - Click "Schedule Event"
- [ ] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
 
##### Staging Review artifacts

- [ ] All URLs (design system and storybook)
- [ ] Here are links to Storybook and Sketch for each of the components.** 
Radio button
Storybook - https://design.va.gov/storybook/?path=/docs/uswds-va-radio--default 
Sketch - https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/QbgQ5l8

Checkbox 
Storybook - https://design.va.gov/storybook/?path=/docs/uswds-va-checkbox--default 
Sketch - https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/KvVOjxr 

Checkbox group 
Storybook - https://design.va.gov/storybook/?path=/docs/uswds-va-checkbox-group--default
Sketch - https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/KvVOjxr 
- [ ] [QA E2E tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-e2e-test-participationE2ETestParticipation) (provide a link to the product’s code)
- [ ] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D). For details, see [Prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).
  
#### Platform actions
- [x] [Slack request](https://dsva.slack.com/archives/CBU0KDSB1/p1683736615021549)
- [x] Meeting date/time: Tuesday, May 23 at 11:30AM ET

#### Platform actions

- [x] Update this ticket with the Zoom recording
  - Recording URL: 
  - Password: https://drive.google.com/file/d/1AV26SCx7fOIkV_sd1Ii3C7RBVpzbflnf/view?usp=share_link
  
#### Design System actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] Close ticket

**Comment by CherylEvans** [comment]
No Content findings for this effort. Thank you!

**Comment by sterkenburgsara** [comment]
No IA feedback.

**Comment by allison0034** [comment]
Yay for more components! If possible try to align the design system and storybook. Eg. checkbox vs checkbox group.

**Comment by caw310** [comment]
Closing
