### ISSUE TITLE
Add note about loans to VALIfe page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#58215]
## Issue Description

Steve Fital asked that we add a note to our [VALIfe](https://www.va.gov/life-insurance/options-eligibility/valife/) explaining that VALife doesn't offer loans. The suggested placement was under the H2 Benefits you can get with VALife after the second bullet.

## Tasks
- [ ] Add note to Drupal page
- [ ] Send to stakeholder for approval
- [ ] Copyedit (Megan)
- [ ] Publish (Megan)
- [ ] Notify stakeholder that changes are live

## Acceptance Criteria
- [ ] Changes are live on the site

**Comment by RLHecht** [comment]
We added this note and published. Moving to validate.

**Comment by RLHecht** [comment]
Change is live. Closing ticket.
