### ISSUE TITLE
[FSR] Streamlined Waiver Functionality Discovery

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#58212]
## Issue Description
Investigate Streamlined waiver FE functionality. Things to test and familiarize with 

- FE Sync to look over flow again
- Test and get a better understanding for using `depends` on whole chapters. 
  - Use form data to set depends and jump to review page. 
- Confirm review page is happy with limited chapters / skipped pages. Will we need to to update `confirmation` and `preSubmitInfo` in form.js for this?
- Can we hijack and use different routing (or another method) to swap between multiple `formConfig`s depending on feature flags? 

---
## Tasks
- [x] Review flow
- [x] Testing depends 
- [x] Testing early escape & review page ramifications 

## Acceptance Criteria
- [x] FE has a roadmap forward for streamlined waiver implementation
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
Bumping up to 3pts as of 5/22/23.

**Comment by amponce** [comment]
Draft PR with from config refactor and cleanup

https://github.com/department-of-veterans-affairs/va.gov-team/issues/58212

**Comment by amponce** [comment]
---
# FSR Streamlined Waiver Functionality Discovery Findings

## 1. Using depends on whole chapters

Upon testing, we found that by adding a `depends: () => false` function at the chapter level of resolution options, we are able to effectively hide the chapter from the form flow and the results page. This indicates that it is feasible to use `formData` to pass conditions at a chapter level to either load or bypass the chapter, depending on predetermined conditions for form loading.

## 2. Setting depends and jumping to the review page using form data

Given that this was a discovery ticket, time constraints prevented testing of using form data to set `depends` and jump to the review page. However, based on our discovery, we'll create a follow-up ticket to further explore form navigation and transitioning between the review and form page.

## 3. Review page's response to limited chapters/skipped pages

We've confirmed that the review page can handle limited chapters and skipped pages. However, testing this thoroughly would involve coordination with our Backend team to ensure the server can handle form data submitted by users without triggering 500 errors due to missing required data. Next step, it's recommended to create a dedicated follow-up ticket for collaboration with Scott and Kevin.

## 4. Routing manipulation based on feature flags

We have successfully tested routing options and found a way to use feature flags with a build form config function. This allows loading of chapters in varying orders based on the flag status. This development process will make maintenance easier and allow for clean-up of unused pages post-EFSR launch.

Here is the Pull Request for the routing experiment: [#24302](https://github.com/department-of-veterans-affairs/vets-website/pull/24302)

We are still in the process of testing more routing options, similar to what we're using in the combined debt portal: [Combined Debt Portal](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/combined-debt-portal/combined/routes.jsx)

Additionally, we need to investigate why `formConfig` is loaded in both `app.jsx` and `routes.jsx`.
