### ISSUE TITLE
EVSS Migration - rated disabilities - ensure `rated_disability_id` is not needed in any workflow

### ISSUE THREAD

**Issue by ahay-agile6** [department-of-veterans-affairs/va.gov-team#58214]
## Issue Description
We need to ensure `rated_disability_id` is not used _**anywhere**_ in the application.

Lighthouse does not send it back, yet we see references to it in places like the submit workflow for Form526

## Notes

app/models/concerns/form526_rapid_ready_for_decision_concern.rb:94
```
# return whether all disabilities on this form are rated as not service-connected
  def disabilities_not_service_connected?
    disabilities.pluck('ratedDisabilityId').all? do |rated_id|
      rated_id.present? && (all_rated_disabilities
                              .find { |rated| rated_id == rated.rated_disability_id }
                              &.decision_code == 'NOTSVCCON')
    end
  end
```

---
## Tasks
- [ ] Refactor `disabilities_not_service_connected?` to not use `rated_disability_id`
- [ ] Check vets-website and make absolutely sure `rated_disability_id` or `ratedDisabilityId` or any other flavor of it is not being used anywhere, ever
- [ ] Check vets-api make sure absolutely sure `rated_disability_id` is not being used (i.e. submit workflow, sending to another api, etc.)

## Acceptance Criteria
- [ ] The team is absolutely sure  `rated_disability_id` is not needed in the application
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mchae-nava** [comment]
LH rated_disability_id meeting
- Met with Lorri Glover, David Lennon
- Does not have knowledge on diagnostic_code

- Lorri: Give us short-term time to figure out the ramifications, level of effort
-- Best case, fast tracked into a sprint, mid-June
-- David could potentially let us know the shape of this before it is ready
- Lorri: Could we have something sometime this week?
-- David: probably, but we will talk to Janet and make sure

Resolution: They'll implement the ids, capacity allowing! Will try to update us on the shape of the change, and tentative mid-June timeline sometime this week

Our next steps will be syncing with David once they've done their investigation, and then implementing a solution to match theirs
