### ISSUE TITLE
Prep communication and/or artifact for Governance to include w/ G.O.

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#58223]
## Purpose
Governance is interested in including information about the new portal in General orientation.  Let's get a sense of how they'd like that presented, then we can decide what is needed from the team

## Tasks
- [x] Take a look at GT's existing slide (general orientation)
- [x] Quick audit of all orientation decks for mentions of the survey
- [x] GT shared the [video](https://oddball-io.zoom.us/rec/share/jiicZ9akOQG4MBr-zJfElZnudewRHRgUyDArNEjA9EXBKFH1JkuCn60uQk5d_bzW.fymbqGQiSWivBaBP) w/ us.  View it and see how the slide is used. Passcode:  er4*icF7
- [x] Update with new Survey info and Feedback portal info
- [x] SDT review of [new slide](https://docs.google.com/presentation/d/1ZbBZKEtMOpxDZ5N-67idWl7yhY3p3EeMcYCIXV0qnAE/edit?usp=sharing)

## Acceptance Criteria
- [x] Slide/information is shared w/ GT
- [x] Slide/information is absorbed into General Orientation
