### ISSUE TITLE
Board Appeal | Setup environment for user research

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#58229]
## Value Statement
**_As a_** researcher
**_I want to_** safely test the Board Appeal form in a realistic environment
**_So that_** I can get accurate feedback without risking a Veteran's appeal status

---
## Background Context

Board Appeal form is already existing in Production, and we want to observe how Veterans interact with the form within the VA.gov environment. 

Ideal testing scenario:
- Participants are able to log in and share their experience on their actual account, so we can see how real claims/issues are showing up within the form.
- Participants are not able to submit the form (to prevent duplication or errored submissions)
- Save data for session will be cleared after research

## Acceptance Criteria
- [x] Code a temporary [feature toggle](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles) that disables the Submit button from functioning on Board Appeal forms for specific users.
- [ ] Remove feature toggle and clear data when research is complete.

## Designs and Build Notes
[feature toggle documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles)

## Out of scope
- Add here

## Open questions
- 

## Tasks
- [x] Add feature flag to disable submit button
- [x] Test in staging 
- [ ] Enable feature flag for specific users (for research)
- [ ] Remove feature flag after study is complete

## Definition of Ready 

- [ ] Tested in staging
- [ ] Tested in production

## Definition of Done

- [ ] Toggled for research studies
- [ ] Code removed after research
- [ ] Closed after research

**Comment by saderagsdale** [comment]
Robin is waiting to hear back from the platform team. Eva is waiting to hear back from Shane. We may have to use staging if working in prod is too risky. Other options:

- Use zoom feature to give remote access to staging.

**Comment by eileen-coforma** [comment]
@saderagsdale asked Matt for approval to move forward with this

**Comment by michelpmcdonald** [comment]
Just an Update, working with Kyle and Robin on this.

**Comment by eileen-coforma** [comment]
@Mottie @michelpmcdonald @saderagsdale Moving the conversation for updating mock data in staging to this ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/58833

**Comment by HeatherWidmont** [comment]
Heather to set up a meeting tomorrow with devs, Eileen, & Sade to see it in action before we close out this ticket

**Comment by Mottie** [comment]
Verified working (disabled submit) in staging for user [vetsgov+test234@id.me](mailto:vetsgov+test234@id.me)

**Comment by eileen-coforma** [comment]
Also verified in staging. We can verify it tomorrow in PROD

**Comment by Mottie** [comment]
Starting work to remove this feature flag

**Comment by rocio-desantiago** [comment]
@eileen-coforma @saderagsdale changes have been merged. Ready to be closed upon validation.

**Comment by eileen-coforma** [comment]
@Mottie can you validate? It's not something Sade or I can see from our ends.

**Comment by rocio-desantiago** [comment]
@Mottie would we have to wait til it hits production today?

**Comment by Mottie** [comment]
Yeah, all the code has been removed. No need to wait until production deploy.
