### ISSUE TITLE
Create new Supporting Forms landing page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#58230]
## Issue Description

We need to create a new page on VA.gov to serve as a landing page for additional forms that aren't specific to one benefit area, including the new digitized ones we are working on. This page will take the place of the current [File additional forms for your disability claim](https://www.va.gov/disability/how-to-file-claim/additional-forms/) page. It will include links to the PDF and the new online form. A redirect will be put in place once the page is live and we'll set up an entry point ticket before publishing.

IA doc with more info: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/form-digitization-supporting-forms.md

## Tasks
- [x] Create new landing page in Drupal incorporating content from original additional forms page
- [x] Review
- [x] Copyedit
- [x] Create publishing and entry point tickets

## Acceptance Criteria
- [x] New supporting forms landing page is created

**Comment by tbaker1026** [comment]
@megzehn Here is a list of all the forms - note these will not all be launching at the same time - I have included the Intake tickets for reference to supporting documents (Note there might be more but these are the active ones we are working on)

21-4142 - Release medical records to VA 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/54641

21-10210 - Lay/Witness Statement 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/55817

21-0845 - Authorization to Disclose Personal Information to Third Party
https://github.com/department-of-veterans-affairs/va.gov-team/issues/58356

21-0972 - Alternate signer
https://github.com/department-of-veterans-affairs/va.gov-team/issues/57319

21-0966 - Intent to File
https://github.com/department-of-veterans-affairs/va.gov-team/issues/56313

21P-0847 - Request to be substitute claimant
https://github.com/department-of-veterans-affairs/va.gov-team/issues/58950

**Comment by megzehn** [comment]
Confirming that I copy edited the [landing page.](http://preview-prod.vfs.va.gov/preview?nodeId=56902)

Note: Danielle and I discussed including mailing addresses under the **How to submit** heading. This will take a little more coordination, so we're planning it in a future iteration!

CC @RLHecht

**Comment by RLHecht** [comment]
This work is complete. Closing!
