### ISSUE TITLE
Medications Preferences - Research field storage

### ISSUE THREAD

**Issue by LynneJohnson224** [department-of-veterans-affairs/va.gov-team#58261]
**Tasks:**

- [ ] For the fields that will be moving to va.gov (identified in [58256](https://app.zenhub.com/workspaces/mhv-on-vagov-top-level-view-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/58256))), research how the field's data is stored in current MHV

- [ ] For the fields that will be moving to va.gov, research how the field's data will be stored on va.gov.

- [ ] Research if there are any synchronization issues between current MHV and VA.gov 

**Deliverable:**

- [ ] Documentation on where/how the data is stored in current MHV
- [ ] Documentation on where/how the data will be stored on va.gov
- [ ] Documentation on if sync issues exist between current MHV and VA.gov
