### ISSUE TITLE
Login.gov adoption team: Sprint 20 (5/11 - 5/24)

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#58274]
## PTO
- Carl May 10-18
- Tyler May 15-29

## Sprint 20 Goals

- Dashboard: Create strategy for addressing Reactivation data visualizations
- Dashboard: Automate ingestion of identity feed from MPI
- Submit Campaign Landing Page for approvals
- Finalize strategies for organic adoption (including retargeting emails) & reactivation campaign
- IPP: Define options for potential target user groups

## Future Sprint Goals
- Dashboard: Automating access feed from SSOe

## Sprint 20 Tasks

**Proactive adoption**
 - [x] Get Drupal access #57889
 - [x] Build required content for Campaign Landing Page #58091
 - [x] Make account creation doc accessible #58192
 - [ ] Publish blog about why security is an evolving priority #50333
 - [x] Finalize plan for retargeting users who dismiss/ignore the modal #58276

**Dashboard**

 - [ ] IAM automation script #58184
 - [ ] Create strategy for addressing Reactivation data visualizations
 - [x] Build a Proof of Concept using VA Notify/GA/Domo #58442
 - [ ] Enhance MPI Credentials dataset to support trends #58440
 - [x] [bug][organic modal] IDME 2FA causes organic modal to return false #58401

**In-person proofing**
 - [ ] Conduct additional research to de-risk: MHV Coordinators / other target users #58269

**Deferred proofing**
 - [x] Define possible technical mitigations for the binding app #57180
 - [ ] Finalize high-level strategy in light of blocked pathways #58268

**Legacy credential migration**
 - [ ] Reactivation: Finalize plans for reactivating dormant users #58295
 - [x] Re-activation eligible user list #58044
 - [ ] Collaborate with Contact Center to draft support plan #58296
 - [ ] Desk research to write FAQs #57356

**Deferring!**
 - [ ] Automate process to easily ingest MHV data and report on CSP counts (part 1) #55961
 - [ ] [Organic Modal] Limit statsd calls to once per session #57286
 - [ ] Complete 55960 Automation Script Work #58300
 
## Retro Board

[Sprint 19 Retro](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1677768711421/aad15b9308afe560c52a1beddefe388840ae239d?wid=0-1682539365898&sender=uaaa67493ae613f0003928743)

### Discussion Topics/Retro Action Items
 - [ ] work on Deliberate actions 
 - [ ] Prioritize and Focus, with the Why!
 - [ ] Release stuff
 - [ ] Discuss capacity during sprint planning

## Collab Cycle Tasks 
 - [ ] TBD

(Some follow-up on VA Notify?)

**Comment by sdickson-gt** [comment]
@alevindecanini How do you want to tackle this one under dashboards: "Create strategy for addressing Reactivation data visualizations"?  Are you driving it?  Anything engineering can do in the interim while fleshing out strategy and KPIs?  We do have a ticket to do discovery for how to pull in GA campaign info from email and landing pages.

**Comment by sdickson-gt** [comment]
@alevindecanini I thought you had said we will defer the work to report on application access via SSOe, based on the size/complexity and because it doesn't support visualizations for Re-activations. I see that "Complete 55960 Automation Script Work #58300" it is in scope under Dashboards.
