### ISSUE TITLE
[a11y design review]: MHV Medications

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#58272]
## Auditor(s)
(SK) Sarah Koomson
## Design Review
Based on the development of the prototype, some of the following may or may not be applicable. 
- [ ] [Color and contrast checks](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review#use-of-color) (Non applicable - Low Fidelity)
  - [ ] WCAG 2.1 AA
  - [ ] WCAG 2.1 AAA
  - [ ] [Who Can Use](https://www.whocanuse.com/?b=ecece5&c=000000&f=20&s=)
  - [ ] High Contrast Mode
- [x] [Keyboard navigation](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review#keyboard-nav)
  - [x] Annotations for Tab order, reflow and reading order (if needed)
- [x] Accessible Name Annotations
  - [x] [Alt attributes for images](https://webaim.org/techniques/alttext/)
  - [x] Text alternative for complex images such as charts graphs maps etc.
- [x] Language (ease of reading)
- [x] HTML Tags
  - [x] [Page Title](https://accessibility.18f.gov/page-titles/)
  - [x] [Heading order](https://accessibility.18f.gov/headings/)
   - [x] Annotations (if needed)
  - [x] Semantic Consideration for paragraphs ordered lists numbering
  - [x] [Tables (heading rows)](https://design.va.gov/components/table)
- [x] Size of clickable areas

### As Time Allows
- [ ] [Components](https://design.va.gov/components/) follow VA design system guidance.
- [ ] [Patterns](https://design.va.gov/patterns/) follow VA design system guidance.

## Team artificats

- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medications)
- [User flows](https://www.sketch.com/s/c117249d-4845-4740-a3e2-78ebde262de3/v/38Y4Qa/p/3B5DC627-0552-423B-9D05-1796643D4605/canvas?posX=-678.118645854775&posY=-685.7033198873772&zoom=0.3199818730354309)
- [Low Fidelity Sketch designs (all pages)](https://www.sketch.com/s/c117249d-4845-4740-a3e2-78ebde262de3/v/38Y4Qa/p/C5D940B0-048F-42DB-BBE7-A2D0F96C8FD5/canvas?posX=-10068.66851338589&posY=-664.0641904524819&zoom=0.05561014264822006)
- Link to any epics/issues that may be helpful:
  - [Prescription status definitions ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medications/research/Discovery/prescription%20%26%20refill%20statuses.md)
  - [MVP Requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medications/requirements/requirements.md)
  - [Pharmacy pages error messages
](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medications/research/Discovery/Pharmacy_Pages_Error_Message_Analysis.xlsx)
  - [Mural Board for initial content mapping](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1681935491539/3add3a248ca8210f6cfd22f8a82f8c5579d8ee63?sender=u3196b80393a36f1ccebf7408)
### Concise issue description

![D13ECC41-1D84-4D56-AD5F-8256A799FCFB_4_5005_c.jpeg](https://images.zenhubusercontent.com/623cd4d6774110eeb19922cb/efd03917-b8df-4cf9-b8b8-d98d42dae739)

#### Bandaid solution
- Similar "Refill medications" buttons on page 

#### Recommended solution
In order to distinguish "refill medications" buttons from others, consider making these buttons unique by possibly adding name of prescription or prescription number in the label text

**Comment by SarahKay8** [comment]
Hi @alexiawunder! Brian mentioned providing unique labels to the "refill medications" buttons which is what we currently have listed here on our review.  Closing this out as I have no further feedback to add.
