### ISSUE TITLE
Finalize re-targeting strategy

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#58276]
## Description
Based on research indicating that many users are likely to close the organic adoption modal, we want to devise methods to re-target those users with messages about creating a Login.gov account. Previously, we had discussions documented in [this Mural](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1683647958507/c5f96dd311c276618b5a0b9fccc6874229177352?sender=uaaa67493ae613f0003928743), but we did not make final decisions about how we would re-target users

## Tasks

- [x] Conduct follow-up meeting
- [x] Document decisions

## Acceptance Criteria

- [x] Team can refer back to the document
- [x] Team understands the strategy
- [x] Team can implement the approach to re-targeting
- [x] Next steps are documented

**Comment by alevindecanini** [comment]
Described our approach in the Sprint 20 demo deck:

> In order to gather reliable data sooner about conversion rates and downstream effects (ie contact center), we recommend shifting from a modal/intercept to triggered email campaigns.
Research indicates that a modal is likely to have very low interaction rates and extremely low conversion.
Modal likely to hit snags as it moves through collab cycle
Other relevant recent info:
VA Notify API would give us ownership of email campaigns, so we could potentially trigger them based on user actions instead of sending in bulk.
Reactivation and organic adoption are very similar: assess eligibility, target with relevant message, push through conversion funnel.

Strategy recommendations:
Treat both organic adoption and reactivation as email campaigns triggered whenever user logs in with a legacy credential.
Gives additional confidence that the user is active
Use VA Notify API to gain the benefit of a check against (most recent) VA Profile data 
Reactivation should be released first – eligibility is straightforward, conversion is likely to be higher
Organic adoption should be released after we’re confident that a majority of reactivation-eligible users have seen those emails
Consider A/B testing messaging:  “this fall” vs. specific date
Consider reintroducing modal & banner as we approach the deadline
Discussing with VA Notify team: drip campaign vs. single email
