### ISSUE TITLE
[BE] Notification Center: Technical discovery on Notification Center mvp

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#58316]
## Background
Based on designs shared in grooming on 5/17 we need to conduct some technical research/discovery into the development of the MVP. Similar to what was done in #51447 we need to put together some findings around developing an MVP notification center. Part of this ticket will be determining what work is needed from FE and BE perspective, as well as any potential support needed from VA Notify.

### Considerations
**FE**
- Use of component card (use border or not?)
- New application therefore a new folder because it doesn't live within the My VA folder
- Breadcrumbs
- Error handling

**BE**
- Pagination (consider how many to show per page)
- Show dismissed notifications (dismissed flag in db)
- Does NC (eventually) show notifications from all channels? (email, text, onsite)
- Error handling

## Tasks
- [x] Determine technical needs for building MVP notification center
- [x] Collaborate with FE dev to create one technical artifact doc (similar to [this one](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/frontend/adding-new-onsite-notification.md) for onsite notifications)
- [x] Discuss with partners on VA Notify to make sure we're not missing anything from their side
- [x] Work with PM to create dev tickets for implementation

## Acceptance Criteria
A write-up of technical questions/findings exists in GH and initial tickets for FE and BE dev work are created.

**Comment by ajakabcin** [comment]
@dellerbie and @allisonlu I realized I didn't create a place for documentation to go - I made a single doc for FE and BE discovery, but let me know if you'd like to separate things out: [tech discovery doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/notification-center-mvp/technical-discovery.md)

**Comment by ajakabcin** [comment]
Complete - BE ticket created and noted in [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/notification-center-mvp/technical-discovery.md#backend-be)
