### ISSUE TITLE
Compare Classic MHV message API to Cerner message API

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#58328]
## Issue Description
We must be able to determine if Cerner's message API will provide the same functionality as the "classic" secure messaging API used by My HealtheVet.

---
## Tasks
- [x] Compare API documentation
- [x] Compare request and response

## Acceptance Criteria
- [x] We will document how the two APIs are similar and any differences we find
- [ ] We will relay any potential show-stopper issues to the team and stakeholders
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
