### ISSUE TITLE
Compare VA.gov Secure Messaging API to Cerner API

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#58329]
## Issue Description
We must be able to determine if Cerner's message API will provide the same functionality as the updated secure messaging API used by Secure Messaging on VA.gov.  
---
## Tasks
- [x] Compare API documentation
- [x] Compare request and response

## Acceptance Criteria
- [x] We will document how the two APIs are similar and any differences we find
- [ ] We will relay any potential show-stopper issues to the team and stakeholders
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by carlosfelix2** [comment]
Link to temporary documentation. This will be moved to SharePoint.
https://docs.google.com/spreadsheets/d/13U_H8BLUYuk53WdSWPKJcFwSVPNap2S0JsaQFZxYBEE/edit?usp=sharing
