### ISSUE TITLE
[EPIC] Determine if Cerner supports the ability to block users from sending messages

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#58332]
## Product Outline
*ADD LINK* [Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## Background ## 
The "classic" My HealtheVet secure messaging tool includes a check for a flag that determines if users have been blocked from sending messages for disruptive behavior (ex - cc'ing excessive numbers of people, abusive language, threats).   The SME on the MyHealtheVet "classic" side is Bhanu Goparaju.

In a meeting held on 5/11/2023, the consensus was that it is not necessary to exactly replicate the way the current system functions if we are able to find ways to improve this feature within technical, legal, business, policy constraints.

## High Level User Story/ies
As a clinician or MHV coordinator, I need the ability to block problematic users from sending messages so that they are no longer able to send abusive or disruptive messages to medical staff.

## 

### What must be true in order for you to consider this epic complete? 
- [ ] We understand how the current flag is set, read, and cleared
- [ ] We understand what options (if any) Cerner's APIs offer that can fulfill this requirement

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
