### ISSUE TITLE
Compare Cerner messaging API to secure messaging API being used by VA Mobile

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#58330]
## Issue Description
We must be able to determine if Cerner's message API will provide the same functionality as the secure messaging API used by the VA Mobile team.
---
## Tasks
- [ ] Compare API documentation
- [ ] Compare request and response

## Acceptance Criteria
- [ ] We will document how the two APIs are similar and any differences we find
- [ ] We will relay any potential show-stopper issues to the team and stakeholders
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by carlosfelix2** [comment]
The VA Mobile app uses the vets-api (VA.gov) for the data. There are a few app specific endpoints, but they are to provide the data to the mobile app in a certain format/dataset. The vets-api is already documented per #58329
