### ISSUE TITLE
Update content on Housing assistance hub landing page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#58351]
## Issue Description

Housing stakeholders asked us to make a content change to the [housing assistance hub landing page](https://www.va.gov/housing-assistance/).

Under the H2 "Get VA home loan benefits" we need to change the following:

~Find a VA regional loan center~Regional loan center contact information
Look up contact information for ~your nearest regional loan center~a VA Home Loan Representative.

We may need to tweak the content to make sure it meets our plain language and style standards.

## Tasks
- [ ] Update content
- [ ] Review (Laura)
- [ ] Send to stakeholders for approval
- [ ] Copyedit (Megan)
- [ ] Publish (Megan)
- [ ] Let stakeholders know changes are live

## Acceptance Criteria
- [ ] Changes are live on the site

**Comment by coforma-terry** [comment]
Need to confirm if there is a new POC for this

**Comment by RLHecht** [comment]
Closing this ticket. We were asked to remove this link because it was going to an outdated page with no information.
