### ISSUE TITLE
Prescription page - Authenticated users main content updates

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#5835]
**User Story**
As a user who is a patient at a Cerner facility and who is browsing the Prescription page on VA.gov after authenticating (logging in), I want the content on the page (above ad below the alert box) to give me the correct information about Cerner and/or MHV so that I am not confused about where my patient portal information is housed.

Note that authenticated users who are not patients at Cerner facilities should see the same content/UX as unauthenticated users (see #5741)

**Acceptance Criteria**
1. Content on Prescriptions page (above and below alert box) for authenticated Cerner patients displays the necessary Cerner-specific information
2. Content on Prescriptions page (above and below the alert box) for authenticated users who are not Cerner patients is the same as for unauthenticated users

**Tasks**
- [ ] SSO-Login team: First pass at copy changes
- [ ] VSP Content-IA team: Edit and validate
- [ ] SSO-Login team: Ensure frontend implementation

**Comment by bridgethapner** [comment]
Have a solid draft of this, but won't pass on to content until we clarify if we are linking to My VA Health for launch or if we're only linking to the refill/tracking phone number. Question is out to Lauren via Slack.

**Comment by bridgethapner** [comment]
Unblocked per 3/3 conversation - at launch, we'll link only to Audiocare phone #, not Cerner. 

@peggygannon We can chat through more today in our touchbase! 

**Wireframe is here:** https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/404897044

### Summary of content changes

- Added a section underneath the alert box "Why can’t I use this tool to refill and track prescriptions at Mann-Grandstaff VA Medical Center?"
- Added the tool name into "The Prescription Refill and Tracking tool on My HealtheVet, sometimes called “Rx Refill” or “Rx Tracker,” is a web-based service that helps you manage your VA prescriptions online." 
- Added tool name to header "Once I’m signed in to My HealtheVet, how do I get started?"
- Added an alert underneath "Can I use this tool to refill and track all my VA prescriptions?" clarifying that Mann-Grandstaff prescriptions won't be seen in MHV. 
- I took a first pass at the "What if I have more questions?" section based off your revised copy for this section on other pages.

**Comment by bridgethapner** [comment]
Things are changing every day and I apologize for any confusion around this page. With the launch date push back, we _will_ be directing users to My VA Health at launch, and they _will_ be able to manage their prescriptions there. [I have updated the UX of this page and my first pass of content edits to reflect this](https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/404897044_-5741_AUTH_Prescription_Page_Content_Updates_-non-Alert_Box-).

I have some questions I am capturing here for near future discussion with Lauren: 
- Will functionality in MHV and My VA Health be the same? (e.g. does "How can the VA Prescription Refill and Tracking tools help me manage my health care?" section need to be split in 2 for different feature lists for each tool?) 
- The page today says "If you change your address within My HealtheVet, it does not change your address for prescription shipments." Is the same thing true for My VA Health? 

Flag: 
- I have written draft content for the My VA Health sub-section of "Once I’m signed in, how do I get started?" section, but as My VA Health builds this part of their tool this copy will need to change.

**Comment by FranECross** [comment]
Ticket is old and outdated. Closing.
