### ISSUE TITLE
[Congressional] V10193913 Due 6/9/2023

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#58359]
## Issue Description
_Veteran is having issues with accessing VA websites due to confusion with son's information _

---
## Tasks
- [ ] Review congressional correspondence 
- [ ] Resolve issue
- [ ] Notify Veteran and Congressional Correspondence channel of resolution 

## Acceptance Criteria
- [ ] _Veteran issue will be resolved or responded to with final answer to issue
- [ ] Congressional Correspondence will receive details of the resolution 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
