### ISSUE TITLE
Content updates to VA help to avoid foreclosure page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#58353]
## Issue Description

Housing assistance stakeholders asked us to make several changes to our [VA help to avoid foreclosure](https://www.va.gov/housing-assistance/home-loans/trouble-making-payments/) page.

1. Under the H2 "If I can’t avoid foreclosure, will I have to pay back my loan?": For both loans closed on or after January 1, 1990, we should change the wording from “your loan” to “the loss incurred by the government on your behalf only” 

For background: VA doesn’t pursue collection unless there is fraud/etc. hence the distinction.

2. We need to add the following to the end of this same section: If you had a prior VA home loan that terminated through foreclosure or a foreclosure avoidance alternative, you will need to repay the loss for full VA home loan entitlement to be restored.  You can request the amount to restore your entitlement by emailing LGYLANATIONAL.VBACO@va.gov. Please include the property address for the VA home loan that was terminated, your name and phone number. Restoration amounts can't be given until 13 months after loan termination as mortgage servicers have one year from the date of termination to file a claim against your guaranty amount.

For background: This way it’s clear Veterans have a way to find out what they owe for their foreclosure. (In some cases, a property sells and government actually recoups part or all of guaranty payment and legal fees, so Veterans might not owe VA as much as they think. But in any case, at least they know where to request this info and perhaps get a VA home loan in the future.

We need to edit this content for plain language and to make sure it meets our style standards.

## Tasks
- [ ] Revise page with new content
- [ ] Review (Laura)
- [ ] Send to stakeholders for feedback
- [ ] Copyedit (Megan)
- [ ] Publish (Megan)

## Acceptance Criteria
- [ ] Revised content is live on the site
