### ISSUE TITLE
[Congressional] V10193913 Due 6/10/2023

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#58361]
## Issue Description
_Veteran is having issues accessing VA websites due to confusion with son's information.
https://dvagov.sharepoint.com/:f:/s/DigitalExperiencePMOInternalFTC-PrivateOCTO-DEActions/Eswkw-xodPpHu8HgMLg0BNsBeaCB2BKP0umUhnEHhj99Ww?e=7m1el3 
---
## Tasks
- [ ] Review congressional correspondence 
- [ ] Resolve issue 
- [ ] Notify Veteran and Congressional Correspondence channel of resolution 

## Acceptance Criteria
- [ ] Veteran issue will be resolved or responded to with final answer to issue
- [ ] Congressional Correspondence will receive details of the resolution. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
