### ISSUE TITLE
Messaging page - Authenticated users main content updates

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#5836]
**User Story**
As a user who is a patient at a Cerner facility and who is browsing the Messaging page on VA.gov after authenticating (logging in), I want the content on the page (above ad below the alert box) to give me the correct information about Cerner and/or MHV so that I am not confused about where my patient portal information is housed.

Note that authenticated users who are not patients at Cerner facilities should see the same content/UX as unauthenticated users (see #5742)

**Acceptance Criteria**
1. Content on Messaging page (above and below alert box) for authenticated Cerner patients displays the necessary Cerner-specific information
2. Content on Messaging page (above and below the alert box) for authenticated users who are not Cerner patients is the same as for unauthenticated users

**Tasks**
- [ ] SSO-Login team: First pass at copy changes
- [x] VSP Content-IA team: Edit and validate
- [ ] SSO-Login team: Ensure frontend implementation

**Comment by bridgethapner** [comment]
@peggygannon Wireframe is here: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/404880626. 

- Everything I've changed from the unauthenticated page (#5472) is outlined with a pink box. The only update here is to the help section. (Note: we're still awaiting My VA Health Help Desk information) 
- All the updates made to the unauthenticated page should also be shown here. I've outlined those with a blue box to help clarify that. 

Please let me know if you have any questions.

**Comment by peggygannon** [comment]
@bridgethapner Please see below for content recommendation for the authenticated page. 
also I wanted to confirm, per the note in the wireframe, that you don't need an alert for those users who can use the My VA Health tool for this page at this time? 

**What if I have more questions?** 

**If you have questions about Secure Messaging on MyHealtheVet**, please read the [Secure Messaging FAQs]( https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/faqs#smGeneralFAQ) on the My HealtheVet web portal. 
Or contact the My HealtheVet help desk at 877-327-0022 (TTY: 800-877-8339). We’re here Monday through Friday, 7:00 a.m. to 7:00 p.m. CT.  
You can also [contact us online](https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/contact-mhv

**If you have questions about Secure Messaging on My VA Health**, you can call the My VA Health help desk at xxx-xxx-xxxx (TTY: xxx-xxx-xxxx). We’re here Monday through Friday, 7:00 a.m. to 7:00 p.m. CT. 
You can also [contact us online](link TK?).

**Comment by bridgethapner** [comment]
Hi @peggygannon - Thank you for the content! I have updated the Help Section with your copy. 

To answer your question - yes, I'm still working on the final alerts direction for all the authenticated pages.

**Comment by FranECross** [comment]
Ticket is old and outdated. Closing.

**Comment by FranECross** [comment]
Ticket is old and outdated. Closing.
