### ISSUE TITLE
Medical Records page - Authenticated users main content updates

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#5837]
**User Story**
As a user who is a patient at a Cerner facility and who is browsing the Medical Records page on VA.gov after authenticating (logging in), I want the content on the page (above ad below the alert box) to give me the correct information about Cerner and/or MHV so that I am not confused about where my patient portal information is housed.

Note that authenticated users who are not patients at Cerner facilities should see the same content/UX as unauthenticated users (see #5743)

**Acceptance Criteria**
1. Content on Medical Records page (above and below alert box) for authenticated Cerner patients displays the necessary Cerner-specific information
2. Content on Medical Records page (above and below the alert box) for authenticated users who are not Cerner patients is the same as for unauthenticated users

**Tasks**
- [ ] SSO-Login team: First pass at copy changes
- [ ] VSP Content-IA team: Edit and validate
- [ ] SSO-Login team: Ensure frontend implementation

**Comment by bridgethapner** [comment]
Have a draft version of this page, and the following open questions out to Lauren: 
- I wrote up a new section on the features of the Health Record on My VA Health - is there anyone at Cerner that needs to approve how we talk about Cerner on VA.gov?
- Will information from Cerner go to the Veterans Health Information Exchange if Veterans have already opted in to that? Or will they need to opt in again?

Waiting on answers to these before involving content.

**Comment by bridgethapner** [comment]
Draft of AUTH Medical Records page attached. Questions are: 

- I wrote up a new section on the features of the Health Record on My VA Health - is there anyone at Cerner that needs to approve how we talk about Cerner on VA.gov?
- Will information from Cerner go to the Veterans Health Information Exchange if Veterans have already opted in to that? Or will they need to opt in again?

https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/405228559

**Comment by FranECross** [comment]
Ticket is old and outdated. Closing.
