### ISSUE TITLE
[FE discovery] 10-10EZ - Bug: Discovery on CSRF Token failures on File Uploads

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#58390]
## Background
Reference ticket #58058

A VFS team reported CSRF token failures errors for file uploads. We identified the issue to be related to how the frontend polls Vets API endpoints along with having multiple browser tabs open. Essentially, if a user starts with one browser tab, leaves it idle for > 30 min (the session timeout) and then authenticates in another browser tab, the first browser tab (for some endpoints/forms) will continue to poll the API. Since the second browser tab has reset the session, browser 1 is unauthorized and the CSRF token has also changed. Browser one no longer has a valid session, but continues to poll.

Solution: The frontend needs to identify when a session is gone (when they are getting 401 or 403 http responses) and they need to adjust the current behavior to log out a user instead of continuing to hit the endpoint (since the browser tab is holding onto a csrf token from an old session). The CSRF issue has been going on for quite some time. 

Debugging
The issue was passed to the backend team to debug the errors, as Vets API implements CSRF protection. On each request, Vets API essentially stores a CSRF token on the session (redis) AND returns the same (masked) token via a response header. The frontend then stores the token in localStorage and passes the token back to the API in subsequent requests via a request header X-CSRF-Token.

Theory of what is happening:

Browser 1 has in progress form open, been idle for >30 min
Browser 2 logs in and resets the session
Browser 1 continues to make requests but now they are unauthorized (and CSRF hits first, so we get the CSRF error)
In this example, you can see where the CSRF token fails over and over again in a loop. The "looping" boils down to the polling behavior.

Platform was were able to identify the multiple browser tab theory in a lower environment.

<details>

<Summary>Expand for a long thread for additional details</Summary>

From Curt Bonade:
> Hey there, VFS teams! An issue was surfaced through support regarding CSRF token failures for file uploads. The TLDR on the issue, is that it’s related to sessions cancelling each other out when the browser has multiple tabs open with the application in them. Each subsequent tab invalidates the session of the tab before it, causing the prior tabs to experience failed authentication. This issue with session handling is not unique to one application, and should be reviewed by all teams to see if any application code needs to be updated to account for this. There’s a lot more details in the ticket linked below including all context and conversation logs that took place around this issue.
https://app.zenhub.com/workspaces/platform-cop-backlog-6359535e384ff5a473132130/issues/gh/department-of-veterans-affairs/va.gov-team/58058

> believe it stands for Cross-Site Request Forgery . CSRF is an attack where a hacker would force a user to make a request that was not initiated by them. The CSRF Token is a unique value that’s required when making a request, that prevents this type of outside interference, as the request will be denied if it’s not the correct value

>From the combination of our component team and back end team’s evaluations, the conclusion was made that this would be on each team’s side to ensure their app was working properly

</details>

- [Original Ticket from Platform Support](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/57338)
- [Another way to view the CSRF](https://vagov.ddog-gov.com/logs?query=service%3Avets-api%20env%3Aeks-prod%20%40client_[…]g=true&from_ts=1683298204872&to_ts=1683299154988&live=false)

## Tasks
- [ ] Check our application behavior for the existence of this issue
     - [ ] Determine whether the issue exists
     - [ ] If it exists, determine solution (reference Background above)
- [ ] Share discovery results with the team and recommend next steps (if any)

## Acceptance Criteria
- Discovery will be done to determine whether this issue exists for our application, and if so, how we will resolve it.

**Comment by JoshingYou1** [comment]
I was not able to reproduce this issue. After logging in as an authenticated user in a separate tab after 30+ minutes, I was still able to submit the form on the unauthenticated tab, and did not see a CSRF token error.

To clarify, what do we mean by file uploads? The uploading of files, for example the military documents portion of the 1010EZ, are done on the frontend only (as far as I know), so I'm not sure where the API polling is taking place.

**Comment by JoshingYou1** [comment]
Closing this out due to the inability to reproduce the underlying issue. If a reliable repro loop is discovered, we can revisit this issue.
