### ISSUE TITLE
Discovery for Error handling for bad CSRF tokens

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#58396]
## Background
Reference ticket #58058

A VFS team reported CSRF token failures errors for file uploads. We identified the issue to be related to how the frontend polls Vets API endpoints along with having multiple browser tabs open. Essentially, if a user starts with one browser tab, leaves it idle for > 30 min (the session timeout) and then authenticates in another browser tab, the first browser tab (for some endpoints/forms) will continue to poll the API. Since the second browser tab has reset the session, browser 1 is unauthorized and the CSRF token has also changed. Browser one no longer has a valid session, but continues to poll.

Solution: The frontend needs to identify when a session is gone (when they are getting 401 or 403 http responses) and they need to adjust the current behavior to log out a user instead of continuing to hit the endpoint (since the browser tab is holding onto a csrf token from an old session). The CSRF issue has been going on for quite some time. 

- [See this long thread for additional details](https://dsva.slack.com/archives/C0460N83Y9G/p1683580901604409?thread_ts=1683221935.528819&cid=C0460N83Y9G)
- [Original Ticket from Platform Support](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/57338)
- [Another way to view the CSRF](https://vagov.ddog-gov.com/logs?query=service%3Avets-api%20env%3Aeks-prod%20%40client_[…]g=true&from_ts=1683298204872&to_ts=1683299154988&live=false)

## Tasks
- [ ] Check our application behavior for the existence of this issue
- [ ] Update application behavior to log out a user when getting a 401 or 403 http response on an old session
- [ ] Test the scenario to confirm the CSRF token is not being used by the old session
     -  Theory of what is happening:
          - Browser 1 has in progress form open, been idle for >30 min
          - Browser 2 logs in and resets the session
          - Browser 1 continues to make requests but now they are unauthorized (and CSRF hits first, so we get the CSRF error)

## Acceptance Criteria for discovery
- Try to reproduce to prove or disprove the above theory (is it two tabs or two windows?)
- Get some stats on how often this error is happening and when it last happened
- Reach out to appropriate platform team for guidance
- See if we can answer some of the questions [here](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/58396#issuecomment-1629205885)

[Related slack thread](https://dsva.slack.com/archives/C04KW0B46N5/p1683921720793839)

Copied from similar issue [#58390](https://app.zenhub.com/workspaces/platform-cop-backlog-6359535e384ff5a473132130/issues/gh/department-of-veterans-affairs/va.gov-team/58390), since all app teams need to handle this error

**Comment by mchae-nava** [comment]
Has the potential to affect any user, repro case is not entirely uncommon. We have a clear repro, and the solution will be frontend-focused, and can end up pretty involved depending on how many places will need to implement "retry" logic

**Comment by RakshindaAslam** [comment]
@mchae-nava - What is the impact to the user? Are they able to submit the claim? What is the cost of not fixing this?

**Comment by mchae-nava** [comment]
@RakshindaAslam I could have been more clear, my bad!

> Non-blocking, closer to tech debt

means that the user can still submit, however there is likely to be a performance hit when the issue is reproduced. I mentioned tech debt, because while the cost to the user is low, it has potentially worsening implications for the applications the longer it's left alone

**Comment by christinec-fftc** [comment]
@RakshindaAslam I mocked this up on staging and this is the behavior I'm seeing. The save in progress api returns 403, but the 526 app allows the user to continue filling out the form. The recommendation described above is to log out the user when the CSRF token becomes invalid since re-authenticating will give the user a fresh, valid token. User won't be able to submit their claim until they have a valid CSRF token and any data the user fills out in this state will not be saved.
![image.png](https://images.zenhubusercontent.com/641341411444ec27c3eb60a4/db58c2b6-c0ea-4679-9ae0-607fa01cf401)

**Comment by RakshindaAslam** [comment]
- Can happen to anyone who is inactive for > 30 min. 
- Needs discovery for more info
- Potential security issue

**Comment by RakshindaAslam** [comment]
Check with Kevin Dunsing and Sade on some work is already happening on this.

**Comment by RakshindaAslam** [comment]
@christinec-fftc to reach out for more info before refinement.

**Comment by christinec-fftc** [comment]
@RakshindaAslam I reached out to Kevin today. It turns out the issue their team had was unrelated to CSRF token. Seems like the best past forward is to do some discovery work to make sure our team fully understands the issue and then come up with a plan to fix.

**Comment by christinec-fftc** [comment]
Some questions we may want to look into

how often does this happen?
is the error only happening on the upload page or are there other pages?
what is unique to the upload page that could be causing this?
why is user not getting logged out? (look into auto logout, session handling logic)
what is the impact to other applications if we modify the platform code to logout?

**Comment by christinec-fftc** [comment]
Discussed with the team at 16th min today. We decided to convert this to a discovery ticket and do some investigation.

**Comment by christinec-fftc** [comment]
Thanks for asking @va-albers. From what i understand so far, this issue is happening for at least 3 different forms/apps (526,  1010, 995) and during the save in progress logic, some of which can be found [here](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms/save-in-progress/SaveStatus.jsx#L76) in the platform dir (not specific to an app). We're still investigating to better understand the issue, but it's not clear as of yet how we would modify the 526 form to handle logout as advised.

**Comment by christinec-fftc** [comment]
### Discovery notes summary
We tried reproducing this many times on the staging environment, but were not successful. There was a theory (see description) that this issue happens when leaving the browser idle, using multiple tabs. However, we were not able to reproduce and in all cases user was automatically logged out. We even tried with leaving the file dialog open.

### Questions Answered
Here are some questions and things we were able to look into for this discovery ticket

**1. How often is the error happening?**
In the past 90 days (this is the farthest back I can seem to go in Sentry), the ‘Invalid Authenticity Token’ error is happening on most days, anywhere from 1 - 27 times
![image.png](https://images.zenhubusercontent.com/641341411444ec27c3eb60a4/b30aa199-02dc-41b3-9f38-32c6f63c3092)

**2. Is the error only happening on the upload page or are there other pages?**
The 'Invalid Authenticity Error' error seems to all be for `vets_upload_error` implying that a user was in some type of file upload workflow. It is also happening for several different apps and pages including 21-526ez, supplemental-claim, burials-and-memorials, home-loan
![image.png](https://images.zenhubusercontent.com/641341411444ec27c3eb60a4/110110c6-1d1e-464e-b1bc-fcd1ea95cde1)

**3. Are the errors specific to any device or browser?**
No. Here is a sampling of different combinations
Chrome 114.0.0, Windows 10
Chrome Mobile 114.0.0, Android 10
Edge 114.0.08123, Windows 10
Safari 13.1.1, Mac OS X 10.15.5
Mobile Safari 16.1, iOS 16.1.2
Chrome 114.0.0, Mac OS X 10.15.7

**4. Why is user not getting logged out before the error happens? (look into auto logout, session handling logic)**
Based on sentry breadcrumbs ([example](http://sentry.vfs.va.gov/organizations/vsp/discover/platform-web:f1fc729d48204382b1f408b1fcbecbaa/?display=daily&environment=production&field=title&field=timestamp&field=http.url&name=All+Events&project=4&query=%22Invalid+Authenticity+Token%22&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1)) it doesn’t appear the user is idle and timing out. There is pretty consistent user activity when the error occurs. Also, since we were unable to reproduce with idleness, did not look further into this flow.

**5. What is the user experience when this issue occurs?**
We were unable to organically reproduce the issue, but there is [error handling logic ](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms/save-in-progress/SaveStatus.jsx#L76)to show the error message in the [mocked error above](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/58396#issuecomment-1611723355) "We’re sorry, but we’re having some issues and are working to fix them. You can continue filling out the ${appType}, but it will not be automatically saved as you fill it out."

This seems concerning that we would tell the user to continue filling out the form, but the data may not be saved. This logic lives in the platform dir, so we were hesitant to touch it since we don't have a broad enough view or experience to know how this change may impact other apps.

For the error example in question 4, we also tried to check if the user was able to continue filling out 526 form and submit. According to [datadog](https://vagov.ddog-gov.com/logs?query=service%3Avets-api%20env%3Aeks-prod%20%40client_ip%3A75.72.168.15%20&cols=host%2Cservice&event=AgAAAYlSvVpLuG7aVQAAAAAAAAAYAAAAAEFZbFN2VjIzQUFEX0RNcC0xMzZJb0FCeAAAACQAAAAAMDE4OTUyZjEtMzkyOC00MjUwLThjODItMzZkMzRlY2NmNTJh&index=%2A&messageDisplay=inline&stream_sort=desc&viz=stream&from_ts=1687127356907&to_ts=1689719356907&live=true), they had a CSRF token failure at Jul 13 21:51:28.459, and they then had a successful 526 submission at Jul 13 21:52:45.358. This had us wondering whether automatically logging out the user is the right approach. Would this cause data loss? Further investigation likely needed.

**6. How does the CSRF token logic work on the FE?**
There is logic in a [platform util function](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/utilities/api/index.js#L91) to make api requests that does the following
- get csrf token from local storage
- pass this token as an `X-CSRF-Token` header along with the request
- in the api response, get the response header `X-CSRF-Token`
- if the value doesn't match what's currently in local storage, update it

### Open/New Questions
All these questions led to more questions. Here are open questions that could be further investigated
1. What is unique to the upload pages that could be causing this?
2. How long do CSRF tokens last? What is the expiry time?
3. What is the history around our CSRF implementation? What are the origins of needing this on the api layer?
4. What is the CORS policy?
5. Did the issue start happening more after we switched to Kubernetes?
6. Do we rotate our secret base key? If so, when?

### Conclusion
We were able to clarify a bunch of things, but ultimately the CSRF token and upload logic feels way outside the scope of just disability benefits. While the feature teams were tasked with logging out the user when these failures occur, the errors are happening during the save in progress flow and that logic lives within platform and would be better handled there for several reasons.

Closing out this ticket since we've used all the points allotted for this discovery ticket. Will reach out to the platform team for further help.

**Comment by christinec-fftc** [comment]
### Discovery notes summary
We tried reproducing this many times on the staging environment, but were not successful. There was a theory (see description) that this issue happens when leaving the browser idle, using multiple tabs. However, we were not able to reproduce and in all cases user was automatically logged out. We even tried with leaving the file dialog open.

### Questions Answered
Here are some questions and things we were able to look into for this discovery ticket

**1. How often is the error happening?**
In the past 90 days (this is the farthest back I can seem to go in Sentry), the ‘Invalid Authenticity Token’ error is happening on most days, anywhere from 1 - 27 times
![image.png](https://images.zenhubusercontent.com/641341411444ec27c3eb60a4/b30aa199-02dc-41b3-9f38-32c6f63c3092)

**2. Is the error only happening on the upload page or are there other pages?**
The 'Invalid Authenticity Error' error seems to all be for `vets_upload_error` implying that a user was in some type of file upload workflow. It is also happening for several different apps and pages including 21-526ez, supplemental-claim, burials-and-memorials, home-loan
![image.png](https://images.zenhubusercontent.com/641341411444ec27c3eb60a4/110110c6-1d1e-464e-b1bc-fcd1ea95cde1)

**3. Are the errors specific to any device or browser?**
No. Here is a sampling of different combinations
Chrome 114.0.0, Windows 10
Chrome Mobile 114.0.0, Android 10
Edge 114.0.08123, Windows 10
Safari 13.1.1, Mac OS X 10.15.5
Mobile Safari 16.1, iOS 16.1.2
Chrome 114.0.0, Mac OS X 10.15.7

**4. Why is user not getting logged out before the error happens? (look into auto logout, session handling logic)**
Based on sentry breadcrumbs ([example](http://sentry.vfs.va.gov/organizations/vsp/discover/platform-web:f1fc729d48204382b1f408b1fcbecbaa/?display=daily&environment=production&field=title&field=timestamp&field=http.url&name=All+Events&project=4&query=%22Invalid+Authenticity+Token%22&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1)) it doesn’t appear the user is idle and timing out. There is pretty consistent user activity when the error occurs. Also, since we were unable to reproduce with idleness, did not look further into this flow.

**5. What is the user experience when this issue occurs?**
We were unable to organically reproduce the issue, but there is [error handling logic ](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms/save-in-progress/SaveStatus.jsx#L76)to show the error message in the [mocked error above](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/58396#issuecomment-1611723355) "We’re sorry, but we’re having some issues and are working to fix them. You can continue filling out the ${appType}, but it will not be automatically saved as you fill it out."

This seems concerning that we would tell the user to continue filling out the form, but the data may not be saved. This logic lives in the platform dir, so we were hesitant to touch it since we don't have a broad enough view or experience to know how this change may impact other apps.

For the error example in question 4, we also tried to check if the user was able to continue filling out 526 form and submit. According to [datadog](https://vagov.ddog-gov.com/logs?query=service%3Avets-api%20env%3Aeks-prod%20%40client_ip%3A75.72.168.15%20&cols=host%2Cservice&event=AgAAAYlSvVpLuG7aVQAAAAAAAAAYAAAAAEFZbFN2VjIzQUFEX0RNcC0xMzZJb0FCeAAAACQAAAAAMDE4OTUyZjEtMzkyOC00MjUwLThjODItMzZkMzRlY2NmNTJh&index=%2A&messageDisplay=inline&stream_sort=desc&viz=stream&from_ts=1687127356907&to_ts=1689719356907&live=true), they had a CSRF token failure at Jul 13 21:51:28.459, and they then had a successful 526 submission at Jul 13 21:52:45.358. This had us wondering whether automatically logging out the user is the right approach. Would this cause data loss? Further investigation likely needed.

**6. How does the CSRF token logic work on the FE?**
There is logic in a [platform util function](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/utilities/api/index.js#L91) to make api requests that does the following
- get csrf token from local storage
- pass this token as an `X-CSRF-Token` header along with the request
- in the api response, get the response header `X-CSRF-Token`
- if the value doesn't match what's currently in local storage, update it

### Open/New Questions
All these questions led to more questions. Here are open questions that could be further investigated
1. What is unique to the upload pages that could be causing this?
2. How long do CSRF tokens last? What is the expiry time?
3. What is the history around our CSRF implementation? What are the origins of needing this on the api layer?
4. What is the CORS policy?
5. Did the issue start happening more after we switched to Kubernetes?
6. Do we rotate our secret base key? If so, when?

### Conclusion
We were able to clarify a bunch of things, but ultimately the CSRF token and upload logic feels way outside the scope of just disability benefits. While the feature teams were tasked with logging out the user when these failures occur, the errors are happening during the save in progress flow and that logic lives within platform and would be better handled there for several reasons.

Closing out this ticket since we've used all the points allotted for this discovery ticket. Will reach out to the platform team for further help.

**Comment by christinec-fftc** [comment]
Created a Platform Support Request ([slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1689721450533939))
