### ISSUE TITLE
[bug][organic modal] IDME 2FA causes organic modal to return false

### ISSUE THREAD

**Issue by holytoastr** [department-of-veterans-affairs/va.gov-team#58401]
## Issue Description
A DSLogon user with IDME 2FA should see the organic modal but the existence of the `idme_verified_credential_at` created by 2FA causes the API to return false. We need to check for a full IDME account instead.

---
## Tasks
- [x] Update specs to catch 2FA edge case
- [x] Change check on `idme_verified_credential_at` to check for full IDME account instead

## Acceptance Criteria
- [x] The API will return `organic_modal: true` when a user logs in with DSLogon and 2FA 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
