### ISSUE TITLE
Research Bottom of Page Feedback Mechanisms

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/va.gov-team#58403]
## Issue Description
To aid in the capturing of relevant user feedback for VFS teams on their pages, a bottom-of-page feedback element needs to be created. Research on potential solutions needs to be performed.

---
## Tasks
- [x] Finding existing examples of bottom-of-page feedback mechanisms
- [x] Find articles of existing research on the topic that provide recommendations
- [x] Write up a document capturing the above findings

## Acceptance Criteria
- [x] A document has been created and shared with Anita and Chante

**Comment by ianMcCullough-ob** [comment]
[Mural capturing existing mechanisms](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1684953231937/3efed6c1f125009d264e57e61019c07a0df71d47?sender=u683996861c7842a72dea8966)

**Comment by ianMcCullough-ob** [comment]
[The document](https://docs.google.com/document/d/1667UmcucfcOvZMnapc-aT4J8KvKSaZa3OxQChNHFRRI/edit) was created and next steps have been scheduled.
