### ISSUE TITLE
VA Feedback & A11 Research Follow Up

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/va.gov-team#58402]
## Issue Description
Based on past research and internal conversations, follow-up research needs to be performed in order to make decisions on potential survey enhancements. The final items that need to be addressed are:
- What is the average number of pageviews per session on VA.gov
- What is the average session duration on VA.gov?
- What is the rejection percent on the A11 survey?
- Is A/B testing possible within Medallia?
- Is there an order recommendation for positive to negative answers on survey answers?

---
## Tasks
- [x] Find data on the above points
- [x] Reach out to Medallia partners where necessary (A/B Testing)
- [x] Write up a document outlining the new findings
- [x] Share the document with Chante and Anita

## Acceptance Criteria
- [x] Has a document with all the relevant findings been created and shared?

**Comment by ianMcCullough-ob** [comment]
Updated research has been added to the previous doc: https://docs.google.com/document/d/1667UmcucfcOvZMnapc-aT4J8KvKSaZa3OxQChNHFRRI/edit#
