### ISSUE TITLE
[Design] Notification Center: FE documentation on Notification Center MVP

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#58419]
## Background
Following design intent on Notification Center mvp we need to create the FE documentation that will help guide the build on va.gov.

## Tasks
- [x] Create FE documentation in GH
- [x] Review with PMs and devs

## Acceptance Criteria
- [x] FE documentation is in GH and has been reviewed with team

**Comment by aagosto90** [comment]
[Link to FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/2023-scaling-onsite-notifications/notification-center-mvp/documentation/notification-center-mvp-FE-documentation.md)
Shared with team 6/22/23
