### ISSUE TITLE
[FE] Remove second line of text from echeck in when answering "No" to current contact demographic information

### ISSUE THREAD

**Issue by kellysmith1008** [department-of-veterans-affairs/va.gov-team#58428]
## User Story
As a Veteran, I don't need to see information on what to do if I don't live at a fixed address when answering "no" to current contact information so that I can see only the relevant information on what to do if my current information is incorrect.

## User Workflow
- Given I
    - **attempt to check in for an appointment for today within the 45 minute window and need to review my demographics**
- When I
    - **answer "No" to my current contact information being correct**
- Then I
    - **see only the text: "Our staff can help you update your contact information."**
  
## Wireframes
- [Abstract](https://share.goabstract.com/42ad6c8a-1e51-458c-a098-61838b01602b?collectionLayerId=aa5169a2-643c-43a6-9d5b-34a911db1afd&mode=design) 
- NOTE: The following is a screenshot of the Abstract file at the time this ticket was created, if the screenshot differs from the Abstract file when this ticket is worked, please raise the issue with the team during stand up

  - **Incorrect text in staging ![image.png](https://images.zenhubusercontent.com/63346ebd45ab78d62eea3201/deb0faa4-f6b7-4108-9efd-37ddf4b293b0)_**

## Tasks
- [ ] [FE] Remove the second line of text
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by wullaski** [comment]
@kellysmith1008 this is ready to be validated on staging

**Comment by kellysmith1008** [comment]
Thanks @wullaski ! I'll try and get to validating this today, but if not today I'll prioritize it for first thing tomorrow

**Comment by kellysmith1008** [comment]
@wullaski This looks good to me. @benbrasso-agile6 just tagging you in case you wanna have a quick glance as well.

**Comment by benbrasso-agile6** [comment]
Sounds good to me
