### ISSUE TITLE
[PM, Design] Notification Center: Prep for & complete design intent

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#58427]
## Background
We need to prepare for the Design Intent as part of the collaboration cycle for the build of the notification center mvp. Design Intent guidance is available [here](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent).

## Tasks
- [x] PM will schedule Design Intent
- [x] Designer prep artifacts for Design Intent (guidance linked above) with assistance from PM (will need to create a high-level user flow and mobile mockup)
- [x] Perform follow-up actions as needed

**Comment by ajakabcin** [comment]
Complete - two items to respond to that we'll address next sprint
