### ISSUE TITLE
[PM] Notification Center: Submit collab cycle request

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#58426]
## Background
To begin development of the notification center mvp we'll need to submit the collaboration cycle request. Information about the collaboration cycle and kick-off process can be found [here](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/collaboration-cycle-kickoff).

## Tasks
- [x] Gather materials for kick-off - write project outline and link in GH (project epic and Onsite Notification product outline)
- [x] Submit [kick-off ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-review%2Ccollaboration-cycle%2CCC-Request&template=collaboration-cycle-request.yml&title=Collaboration+Cycle+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D)
- [x] Perform any follow-up items from kick-off

## Acceptance Criteria
- Kick-off is submitted and completed

**Comment by ajakabcin** [comment]
Complete - more details will be added to the outline over time but draft is published and collab cycle request is submitted (#59826)
