### ISSUE TITLE
Build a Proof of Concept using VA Notify/GA/Domo

### ISSUE THREAD

**Issue by sdickson-gt** [department-of-veterans-affairs/va.gov-team#58442]
## User story
As an LGA team member, I want to build a proof of concept of the reactivation campaign in order to: 
- learn more about how VA Notify works
- de-risk the upcoming release of the reactivation campaign, and 
- ensure that we're able to visualize data about this campaign in our dashboard. 

## Description
In order to prep for the reactivation campaign release, we will build a proof of concept. The main features of this proof of concept are:
- It's triggered by an event: a user logging into VA.gov with a legacy credential
- It determines the user's eligibility for the reactivation campaign, based on whether or not they have a modern credential
- It uses the VA Notify API to send an email to the user
- We're able to ingest relevant data about the email campaign into Domo

More details are captured in [this Mural](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1684329312312/df1c36fc281d2e288446e9feb0603321e115525d?sender=uaaa67493ae613f0003928743)

## Tasks
- [x] VA Notify [Business Intake Form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/58503)
- [ ] Read VA Notify documentation
- [x] @alevindecanini Write acceptance criteria & user stories to describe the test in greater detail
- [x] @alevindecanini Write business rules for eligibility
- [x] @alevindecanini Document campaign triggers & timing
- [x] Determine strategy: how to track which users have already received these emails & prevent them from receiving it again immediately
- [ ] @kscoulter Investigate available campaign management tools used by VA - ask VA Notify
- [ ] @alevindecanini Investigate available campaign management tools used by VA - ask Comms working group 
- [ ] @holytoastr Create technical sequence diagram that addresses integration points
- [ ] Architecture/design options: how to track which users have already received these emails & prevent them from receiving it again immediately
- [ ] @kscoulter Check if there's a catcher and where it goes 

##Tracking:
- [ ] @sdickson-gt @kscoulter Investigate: Event tracking when users kickoff account creation, complete account creation, and when they return to VA.gov. Use custom or non-custom events?
- [x] Determine: is the GA connector issue that was preventing us from ingesting GA data in Domo now fixed?
- [x] Request API key for access to portal
- [ ] Pull GA events into Domo based on email campaign.  (Behavior and Acquisition)
- [ ] Develop visualization of KPIs

##Delivery:
- [x] @elizabethkochBT Request custom reply-to email (can take up to 3 weeks) 
- [ ] Set up templates in VA Notify portal
- [ ] Work with VA Notify team to send test emails integrated with lower env GA
- [ ] @alevindecanini Determine phased rollout plan

## Acceptance Criteria
 - [ ] Able to be triggered by logging in with a legacy account
 - [ ] Correctly assesses user's eligibility for reactivation campaign
 - [ ] Sends an email to a test user using VA Notify
 - [ ] Data from GA events (ie % of users who clicked the CTA in the email) is visualized in Domo

**Comment by sdickson-gt** [comment]
1. Submit the intake form *
2. Kick-off with VA Notify **
3. Have your technical team review the VA Notify API docs *
4. Get access to the Self Service Portal **
5. Create your notification content (Privacy Officer review required)
6. VA Notify submits a communication preference intake for your team (if applicable)
7. Please note, if you have a new communication preference your team will need to determine a plan to communicate this to veterans so they know a new notification is available to opt into.
8. Build your notification code to call the VA Notify API *
9. Test your notification
10. Launch your notification
11. Evaluate business outcomes and make revisions as needed

**Comment by sdickson-gt** [comment]
Related links:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=bevnobev%2C+mjones-oddball&labels=vanotify-intake&template=VANotify-Business-Intake.md&title=Business+intake+form+for+%5BBusiness+or+team%5D
https://drive.google.com/file/d/101GGNCVS3Yj5Oxr18J9iunqZQ26d_MEI/view
https://staging.notifications.va.gov/developer/api_docs

**Comment by alevindecanini** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Logingov-adoption-Team-632280b31e745000136a61fc/issues/department-of-veterans-affairs/va.gov-team/58442?planning-poker) with Zenhub @sdickson-gt @kscoulter

**Comment by kscoulter** [comment]
For reference, VA notify playbook https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/VA%20Notify%20Playbook.pdf

**Comment by alevindecanini** [comment]
[Diagram here](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1684329312312/df1c36fc281d2e288446e9feb0603321e115525d?sender=uaaa67493ae613f0003928743)

**Comment by alevindecanini** [comment]
Closing this, follow-on tasks moved to their own epic
