### ISSUE TITLE
Enhance MPI Credentials dataset to support trends

### ISSUE THREAD

**Issue by sdickson-gt** [department-of-veterans-affairs/va.gov-team#58440]
## Description
- Want to be able to see trends of metrics over time to visualize the impact of campaigns and changes.

## Tasks
 - [x] Discovery into how Domo and Domo Workbench can support snapshots
 - [x] Implement snapshots
 - [x] Update total credentials by CSP segment visuals to show trend

## Acceptance Criteria
 - [x] Dashboard total credentials by CSP segment visuals to show trend
