### ISSUE TITLE
[FSR] Employment Date Component 

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#58444]
## Issue Description
Employment Date Component needs to be updated so that it is not utilizing the greyed out date field.

- CAIA ticket #57845
- Front end ticket #57342

### CAIA Recommendation

An option here is to follow the standard of grouping with one set of questions per page. This keeps it simple with one "item" per page. So, something you could try here is [breaking apart this page into two different steps - detailed below.](https://preview.uxpin.com/f43733391f52c409c4d3152e9a4b101a392e29df#/pages/161460736/simulate/no-panels).

### Step 2
   - Type of work (dropdown) 
   - Employer name (text field)
   - Do they currently work here?  (checkbox)
### Step 3
- Date Input(s)
   - **If they check the box in step 2**, that greyed out option does not need to show at all. 
   - **If they _do not_ check the box in step 2**, then that field will be available for input. 
### Resource Links
For more information on one thing per page, these are excellent resources to check out: 
- [Original smashing article](https://www.smashingmagazine.com/2017/05/better-form-design-one-thing-per-page/)
- [gov uk](https://www.gov.uk/service-manual/design/form-structure)
- [va design principle](https://design.va.gov/patterns/help-users-to/complete-a-sub-task#design-principles)

---
## Tasks
- [x] _Discuss and create mockups_

## Acceptance Criteria
- [x] _Mockups created_
- [x] _Share with CAIA #57845_
- [x] _Share with with front end team #57342_

**Comment by josephrlee** [comment]
@mgleo, I ended up working on this a little more! I cleaned it up a bit and shared it with the CAIA as well!

**Comment by josephrlee** [comment]
Closing this out after handing it off to @OptionSelect!

**Comment by mgleo** [comment]
Thanks @josephrlee!
