### ISSUE TITLE
[DESIGN] Revisit eyebrow design

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#58453]
We have a short-term solution in place for the eyebrow on our [travel reimbursement](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/oMYJKQ2#Inspect) and [demographics](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/0A9WbMV) pages that has been ok'd by Matt Dingee on the design system team ([feedback thread](https://dsva.slack.com/archives/C01DBGX4P45/p1683759265902469)), but we'd would like to explore this design more and confirm the long-term solution.

Also note this will be used for "Review your information" and "Confirm your appointment." 

Examples of different versions located in the Sketch [Discovery page under the blue line](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/6116A56D-9F46-40FA-B8A7-0955308F9AE2/canvas). 

## Tasks

- [ ] Revisit and decided on font style, size, spacing, and all caps vs. lowercase -- different explorations located in [Discovery page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/6116A56D-9F46-40FA-B8A7-0955308F9AE2/canvas) in Sketch
- [ ] Sync with UX to discuss top options
- [ ] Confirm with FE that the solution will work within the H1 in the code
- [ ] If using the a11y fix for how all caps is read out to screen readers, make sure [this CSS](https://dsva.slack.com/archives/C04J6H2LYUU/p1684175118278309?thread_ts=1684168789.987349&cid=C04J6H2LYUU) is included in the annotations page

## Acceptance Criteria
- [ ] UX is decided on a longterm eyebrow solution
- [ ] FE has confirmed eyebrow will work in code 
- [ ] Eyebrow is ok with platform design and accessibility

**Comment by zach-park** [comment]
From Kelly: Here’s the CSS code for easy reference:
<h1><span class=“eyebrow”>Check-In</span>
Did you travel in your own vehicle?</h1>
.eyebrow {text-transform: uppercase;}

**Comment by ytsaoca** [comment]
I synced with @cgednalske  yesterday. I evaluated how the different eyebrow designs based on whether they are easy to read (color and weight) and how they differentiate the eyebrow content with H1 (font and tag design). Christina and I agree that Source Sans Pro with Regular Weight and Dark Gray (#323A45) color works better for both eyebrow wordings (Review your information, Confirm your appointment, or Check-in). I’m happy to go into those more if needed.

Wireframes:
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/Eeq1nlo
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/3oKRJ3j

Next steps: 
(Please correct me if I’m wrong.) According to Christina, because we are going to the same direction with what we decided last sprint, we don’t need to sync with FE or Accessibility team because they’ve approve that this design is practical.

**Comment by ytsaoca** [comment]
I synced with @cgednalske  yesterday. I evaluated how the different eyebrow designs based on whether they are easy to read (color and weight) and how they differentiate the eyebrow content with H1 (font and tag design). Christina and I agree that Source Sans Pro with Regular Weight and Dark Gray (#323A45) color works better for both eyebrow wordings (Review your information, Confirm your appointment, or Check-in). I’m happy to go into those more if needed.

Wireframes:
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/Eeq1nlo
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/3oKRJ3j

Next steps: 
(Please correct me if I’m wrong.) According to Christina, because we are going to the same direction with what we decided last sprint, we don’t need to sync with FE or Accessibility team because they’ve approve that this design is practical.

**Comment by benbrasso-agile6** [comment]
This is perfect. 

1. Do you want to go ahead and update all artboards in unified check-in? 
2. Christina, is CodePen all set or is that something that still needs to happen before research? 
3. Ya-ching, do you want to move now to focus on making this update in our check-in sketch file?

**Comment by cgednalske** [comment]
@benbrasso-agile6 CodePen just needs the font changed on those pages. Just tried it out on [this page](https://codepen.io/team/va-cie/pen/RweobKY?editors=1100) and it was pretty quick. I can go ahead and update the rest of them.

**Comment by cgednalske** [comment]
@benbrasso-agile6 @ytsaoca CodePen is updated 👍

**Comment by benbrasso-agile6** [comment]
This looks like we need to carryover to complete this item: 

> Do you want to go ahead and update all artboards in unified check-in?

**Comment by ytsaoca** [comment]
Updated the style needs and made a symbol for eyebrow
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/pYavwnZ

**Comment by benbrasso-agile6** [comment]
LGTM @ytsaoca 

@cgednalske can you validate too

**Comment by cgednalske** [comment]
@ytsaoca @benbrasso-agile6 Looks good to me as well 👍
