### ISSUE TITLE
UX | Auth Exp | Logged-in IA and Nav | Exploration

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#58463]
## Background

If we replace the logged-in homepage with my VA, we take away access to the logged-in homepage. Let's explore some ideas around:
- Instead of taking away the logged-in homepage, how can we better surface My VA when people are logged in? Re-think how we give people access to it.
- If we do take away access to the logged-in homepage, how could people access the parts of it that aren't on My VA?

Additionally, we should think about immediate changes we might be able to make to improve the logged-in UX ("low hanging fruit"?) 
- What has been discussed so far about adding records to My VA?
- Do records belong in My VA or Profile?
- What else can we do?

## Tasks
- [x] Create rough designs/list of possibilities to answer the questions above
- [x] Share w/ team in Monday sync
  

## Acceptance Criteria
- [x] Shared w/ team in Monday sync and received feedback

**Comment by andaleliz** [comment]
Status update:
- met with My VA team to learn about any historical decisions/conversations around adding records to My VA, making My VA the logged-in homepage, and surfacing non-task content on My VA in preparation for replacing the homepage
- talked w/ sitewide team members to learn about plans for the auth version of the new homepage (none), and to learn about decisions leading to the current design choices to prioritize search, deprioritize task links, and change the order of benefits in the "Explore..." section
-  [started a Mural board ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684266228888/70e80eb031b0215679917698dc3abfcd74c76e03?sender=ub868d471cfdb1c56cc0b4512)to capture thoughts; will continue to elaborate and add sketches

**Comment by andaleliz** [comment]
Shared the Mural board in today's sync and received the following feedback:
- any header/nav changes should be shelved since VA.gov has been selected to be the test site for the new federal government header, that OPM wants consistently used across all government sites. Mikki has some more info she'll share with me
- The most viable and interesting options to the group are to pursue ideas in the "[in other parts of the site](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684266228888/70e80eb031b0215679917698dc3abfcd74c76e03?wid=0-1684366379577)" section of the Mural board. I've created #58875 to start tracking that work
- The homepage ideas are worth sharing with Dave Conlon and his team, though they ultimately have ownership of the auth homepage at this time. We can advocate for having more say/involvement in that work
