### ISSUE TITLE
Design Intent Info session at Veteran Digital User Experience Weekly Design Sync

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#58464]
## User Story
As a designer, I know what types of artifacts I need to create for a Design intent, so that I inform the Governance team about my product correctly.

As a Governance team member, I want to make sure Designers understand the purpose of a Design Intent so they can create the correct artifacts.

Assignee:
Peer Reviewer: 

## Description
While working on Solutioning for high-priority Design Intent challenges#[56730](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/gh/department-of-veterans-affairs/va.gov-team/56730), we decided it would be helpful to present something in the Monday Veteran Digital User Experience Weekly Design Sync as an MVP. We want to explain to designers what types of artifacts are needed and why. This is also related to #[55646](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55646).

## Tasks
- [ ]  Sync with Matt Dingee about his vision for this

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] _Placeholder AC_

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
I have started to get ideas around what needs to be said and reached out to Matt to confirm.

- What is the purpose of a design intent
- When should I schedule
- What artifacts should I bring
- User flows are going to be required moving forward
- What are the next steps after a DI

**Comment by humancompanion-usds** [comment]
The key point I want to get across to them is that it's a collaborative discussion.

**Comment by allison0034** [comment]
This will be carrying over to the next sprint bc of a heavy review week.

**Comment by allison0034** [comment]
[Presentation draft](https://docs.google.com/presentation/d/1FgwSbjdngGcXgwNgDethHX_Tjr4QMjI9Tr7ZpO-Ncj8/edit#slide=id.gbf0559dc8d_0_15)

**Comment by allison0034** [comment]
Asking for team feedback via this [Slack thread](https://dsva.slack.com/archives/GNF5GSD9N/p1686318684099679)

**Comment by allison0034** [comment]
@briandeconinck ready for your review! [Presentation](https://docs.google.com/presentation/d/1FgwSbjdngGcXgwNgDethHX_Tjr4QMjI9Tr7ZpO-Ncj8/edit#slide=id.gbf0559dc8d_0_15)

**Comment by allison0034** [comment]
@humancompanion-usds I will not be presenting until July, do you have any final thoughts on the [Presentation](https://docs.google.com/presentation/d/1FgwSbjdngGcXgwNgDethHX_Tjr4QMjI9Tr7ZpO-Ncj8/edit#slide=id.gbf0559dc8d_0_15)?

**Comment by briandeconinck** [comment]
@allison0034 I think this all looks good. Clear, concise, all makes sense. But I'm happy to review again if Matt asks for any additional changes! 😄
