### ISSUE TITLE
Content support and guidance for MHV appointment reminder email

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#58475]
## Issue Description
The MHV on VA.gov team opened an intake request asking for a content review of their appointment reminder email. 

Email to review: [https://app.zenhub.com/files/133843125/cc13cc88-ca48-48eb-9a66-b6d615853d76/download](https://app.zenhub.com/files/133843125/cc13cc88-ca48-48eb-9a66-b6d615853d76/download)

Intake request for background: #58378

## Tasks
- [ ] Content review of email (Aliyah)
- [ ] Review (Laura)
- [ ] Post final content for product team in intake request (Aliyah)

## Acceptance Criteria
- [ ] Product team has final content

**Comment by aliyahblackmore** [comment]
GitHub link with email notification template: 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/README.md#email-frame-and-template

When I move to this work, I'll take a look at this and can be back in communication with the VA notify team if there is more info that we need re: templates/guidance for email notifications

**Comment by RLHecht** [comment]
Note: They added a second version of the email in the intake request.

**Comment by aliyahblackmore** [comment]
**Update:** I followed up with their re: answers to a few questions we asked previously and I added an additional question in the intake request.

**Comment by aliyahblackmore** [comment]
Laura continued this work as part of the larger MHV work. I'm unassigning myself for now.

**Comment by laurwill** [comment]
Blocked waiting for privacy office review

**Comment by laurwill** [comment]
Updates:
- Met with privacy office in fall 2024. Kristen McConnell, Kay, and Bresha were on the call. Privacy office had concerns about PII, even in the "non-PII" versions. 
- Privacy office explained that we can't include details like location, date, time of appointment unless we encrypt the email. 
- Next steps were for Bresha and Kristen to learn more about encryption options and to confirm how MHV classic is currently handling the privacy issues
- As of January 2025, Laura was still waiting for MHV tool teams to confirm with the privacy office exactly what info we could use in the emails

**Comment by mistymg** [comment]
Updates: 
Assigning myself to this ticket as I've taken over with the new content team. Content source of trust is in [the Figma file](https://www.figma.com/design/CuF6OZVJ6r7dEMpp2jLMAh/MHV-Appointment-Email-Reminders-%7C-Appointments-FE?node-id=3510-29675&p=f&t=9UAzuf7SvDSpNogN-0). I've reviewed with the team and made some suggestion. Once all issues are resolved, we can close out this ticket.

**Comment by mistymg** [comment]
All open questions in [Figma file](https://www.figma.com/design/CuF6OZVJ6r7dEMpp2jLMAh/MHV-Appointment-Email-Reminders-%7C-Appointments-FE?node-id=3510-29675&p=f&t=JZUcIKfH454BhcwK-0), which is source of truth now for content. Closing ticket as done.
