### ISSUE TITLE
[FE] Address IA on check-in confirmation page Feedback

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#58479]
## Description
Address IA on check-in confirmation page Feedback.

## Wireframes
[See wireframe ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57444)

## Tasks
- [ ] [FE] Make changes per the new wireframes
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
closing as the wireframes are for the unified experience
