### ISSUE TITLE
Update 2 R&S pages about statuses in CST 

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#58473]
## Issue Description
We noticed that at least one status in the CST doesn't match what's on our R&S page about claim statuses. We need to confirm the correct statuses with the product team and update our pages to match.

---
## Tasks
- [ ] Get list of current statuses from product team (Laura)
- [ ] Update pages as needed (Katherine)
- [ ] Review (Laura)
- [ ] Share with partners (Laura)
- [ ] Copyedit (Megan)
- [ ] Publish (Megan)

## Acceptance Criteria
- [ ] Statuses on our pages match statuses in the live tool

**Comment by RLHecht** [comment]
This work isn't needed. Closing ticket.
