### ISSUE TITLE
Tagalog translation: Update COVID pages with end of public health emergency changes

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#58483]
## Issue Description

We made changes to 3 of our COVID pages to reflect changes with the end of the public health emergency. We need to get this content translated and then update the Tagalog pages.

Pages to revise:
- [COVID-19 vaccines at VA](https://www.va.gov/health-care/covid-19-vaccine/)
- [COVID-19 booster shots](https://www.va.gov/health-care/covid-19-vaccine/booster-shots-and-additional-doses/)
- [Coronavirus FAQs](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/)

## Tasks
- [x] Create word doc to send to translation team (Ana)
- [x] Update main vaccines page (Ana)
- [x] Update booster page (Ana)
- [x] Update FAQs page (Ana)
- [x] Copyedit main vaccines page (Megan)
- [ ] Copyedit booster page (Megan)
- [x] Copyedit FAQs page (Megan)
- [x] Publish main vaccines page (Megan)
- [ ] Publish booster page (Megan)
- [x] Publish FAQs page (Megan)

## Acceptance Criteria
- [ ] Tagalog COVID pages are live with most recent info

**Comment by RLHecht** [comment]
Here's the document I sent to translators on 5/23: [https://app.zenhub.com/files/133843125/e1c1ec04-c696-4bb9-8fbd-573df1a75f36/download](https://app.zenhub.com/files/133843125/e1c1ec04-c696-4bb9-8fbd-573df1a75f36/download)

**Comment by RLHecht** [comment]
Word doc back from translators: [https://app.zenhub.com/files/133843125/0e0b957b-bbca-42c4-a184-790c09e79f8d/download](https://app.zenhub.com/files/133843125/0e0b957b-bbca-42c4-a184-790c09e79f8d/download)

**Comment by coforma-terry** [comment]
@Hey @ABeltran77 - let me know if we have an update on this :) TY

**Comment by ABeltran77** [comment]
@coforma-terry I'm not able to edit with the translated format. Should I reach out to the translators?

**Comment by ABeltran77** [comment]
@coforma-terry I'm not able to edit from the translated pages, do I reach out to the translators?

**Comment by coforma-terry** [comment]
Hey @ABeltran77  - yes please :)

**Comment by ABeltran77** [comment]
@RLHecht @coforma-terry Sent email.

**Comment by ABeltran77** [comment]
@megzehn Ready for you to review. I did notice that some of the booster info is no longer on the live English pages. Let me know if you need anything else from me.

**Comment by megzehn** [comment]
Confirming that I reviewed these changes (except for the Booster page, which we're archiving) and published.

**Comment by ABeltran77** [comment]
Thanks! @megzehn
