### ISSUE TITLE
Demo: Platform website survey findings

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#58489]
## Tasks
- [x] Create PPT to introduce demo. [Use this template](https://docs.google.com/presentation/d/1SUQp7RPCz8-hZx5jj3sW0ZeLx2x6MWVFhADbhZdONnA/edit?usp=sharing).

**Demo topic:** 

- [x] Demo Platform website research insights: https://docs.google.com/presentation/d/16UomRBxSyfqASYvRVMxPPI_CV6ui8WFqpYbiYMCz7KE/edit?usp=sharing

## Acceptance Criteria

- [x] Demo at the next scheduled demo
