### ISSUE TITLE
Spanish translation: Update COVID pages with end of public health emergency changes

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#58482]
## Issue Description

We made changes to 3 of our COVID pages to reflect changes with the end of the public health emergency. We need to get this content translated and then update the Spanish pages.

Pages to revise:
- [COVID-19 vaccines at VA](https://www.va.gov/health-care/covid-19-vaccine/)
- [COVID-19 booster shots](https://www.va.gov/health-care/covid-19-vaccine/booster-shots-and-additional-doses/)
- [Coronavirus FAQs](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/)

## Tasks
- [x] Create word doc to send to translation team (Ana)
- [x] Update main vaccines page (Ana)
- [x] Update booster page (Ana)
- [x] Update FAQs page (Ana)
- [x] Copyedit main vaccines page (Megan)
- [x] Copyedit booster page (Megan)
- [x] Copyedit FAQs page (Megan)
- [x] Publish main vaccines page (Megan)
- [x] Publish booster page (Megan)
- [x] Publish FAQs page (Megan)

## Acceptance Criteria
- [x] Spanish COVID pages are live with most recent info

**Comment by RLHecht** [comment]
Here's the word doc I sent to translators on 5/23: [https://app.zenhub.com/files/133843125/f5c9992b-eda2-46c8-8d6f-d4cd7c7ed971/download](https://app.zenhub.com/files/133843125/f5c9992b-eda2-46c8-8d6f-d4cd7c7ed971/download)

**Comment by RLHecht** [comment]
@ABeltran77 Here's the doc back from the translators. These updates can be incorporated with updates you're working on in the other ticket so we can get these all published together. Thanks!

[https://app.zenhub.com/files/133843125/1d931cdc-7934-4bbb-ad26-32aa89d6d1e6/download](https://app.zenhub.com/files/133843125/1d931cdc-7934-4bbb-ad26-32aa89d6d1e6/download)

**Comment by ABeltran77** [comment]
Update FAQs pages completed.

**Comment by RLHecht** [comment]
I published the FAQs page. moving to validate and will close once changes are live.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
