### ISSUE TITLE
526ez | Prep work for triggering email notifications

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#58492]
## Value Statement
**_As a_** Veteran that submitted a claim that failed to establish
**_I want to_** know what happened and how it's being handled
**_So that_** I can take appropriate action on my claim. 

---
## Background Context
VBA is sending email notifications to Veterans as the last step in completing the transfer of each batch. David Reis and VA Notify are coordinating with us. 

## Acceptance Criteria
- [x] Given a list of submission IDs, the trigger pulls emails and sends them
- [x] Email trigger errors are logged
- [ ] Passes load and concurrency testing (not doing, just going to do 1 at a time in a loop, it should be fine)

## Out of scope
- Sending emails in production

## Tasks
- [x] VA Notify - Give VA.gov an example of calling the VA Notify API, call it in lower environments
- [x] VA Notify, VBA - Get email content in place
- [x] VA.gov - Make code for a list of 526 submissions, gathering the emails, and calling the VA Notify API
- [x] VA.gov, VA Notify - Test email load and concurrency
- [x] VA.gov, VA Notify - Test code in lower environments
- [x] Send sample to David 
---
## Definition of Ready 
- [x] VA Notify sent documentation for engaging their endpoints

## Definition of Done
- [x] Code works in lower environments
- [x] Approved by VBA and product manager

**Comment by saderagsdale** [comment]
@kylesoskin Anything more we need to do before confirming with David when it's time to send the emails?

**Comment by kylesoskin** [comment]
@saderagsdale nothing else left for us to do but wait for the "all clear" to send from David. (we also need a list of submissions to send for from him, or ones to exclude, if ALL of the ones I sent him did not work on their end for any reason)

**Comment by kylesoskin** [comment]
Think we are good to close this. Prep work that can be done is done.
