### ISSUE TITLE
526ez | Send email notifications to Veterans

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#58495]
## Value Statement
**_As a_** Veteran that submitted a claim that failed to establish
**_I want to_** know what happened and how it's being handled
**_So that_** I can take appropriate action on my claim. 

---
## Background Context
VBA is sending email notifications to Veterans as the last step in completing the transfer of each batch. David Reis and VA Notify are coordinating with us. 

## Acceptance Criteria
- [x] Given a list of submission IDs, the trigger pulls emails and sends them
- [x] Email trigger errors are logged

## Out of scope
- Add here

## Tasks
- [ ] VA.gov - Find out if VA Notify returns bounce back emails
- [ ] VBA - Confirm when claims are established on the VA side
- [ ] VBA - Provide approved content
- [ ] VBA - Provide submission ids that correspond with the established claims
- [ ] VA.gov - Use that list to send the emails

---
## Definition of Ready 
- [ ] Content is approved and ready
- [ ] We have a validated list of submission IDs
- [ ] Logging and monitoring is in place before sending emails

## Definition of Done
- [ ] Code works in lower environments
- [ ] Approved by VBA and product manager

**Comment by saderagsdale** [comment]
@kylesoskin Can you estimate this?

**Comment by saderagsdale** [comment]
@kylesoskin this is supposed to happen in July right, like next sprint?

**Comment by saderagsdale** [comment]
Will take place after first two batches are established (targeting July 5th).
