### ISSUE TITLE
[Research] 10-10EZ - Short Form: Deep dive into the research and designs

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#58499]
## Background
To gain a good understanding on one of the most impactful changes made to the 10-10EZ form, a deep review of the Short Form design and extensive research is recommended.
The research will give good insights into how the Veteran experience remained center to all the decisions made, and the impact it had.

### Resources
- [GH 10-10EZ folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application)
- [Short Form folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/Short%20Form)
- [Research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/research)

## Tasks
- [x] Review all Short Form designs, research and related documentation in GH
- [x] Document any questions, thoughts and suggestions you may have, even if it challenges a decision made
- [ ] Review with the team/during design sync to share any findings (optional task)

## Acceptance Criteria
- A clear understanding of the Short Form flow designs, and functionality will be gained, and you will have a precedented body of work to lean on in future initiatives.

**Comment by jessicastump** [comment]
@IMHieuVo Completed by a designer before I joined the team; but these are the Sketch pages with this work
- [Designs](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/4EEB69A5-43C1-45B3-B5B6-58D7DA435BD1/canvas)
- [Flow](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/A71F1C96-FF98-42A2-9ADD-6D4B7A1DDB20/canvas)
- [Staging/prod VA Benefits section](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/5EAC690B-520D-493C-AD17-81535870F536/canvas)

**Comment by jessicastump** [comment]
@IMHieuVo I just saw this note when I received the closed notification email :) A couple of replies to your comments above.

1. Toggle feature is more of a FE thing; when big updates or features are developed they are behind a toggle. Also has something to do with staging/prod being in sync but Matt could explain it better.
2. The latest I know of is April of 2023 - [link here](https://www.va.gov/vaforms/medical/pdf/va_form_10-10ez.pdf)
3. @hdjustice can confirm, not sure.
4. Facility has not launched for the EZ, on the roadmap for Q3 2023. On the CG side, is in development phase - Collab cycle has been initiated and designs when through Design Intent. 
5. Yep, just initial thoughts, not even planning.
6. A disability rating is given to Veterans to rate the severity of their disability they received during active duty. I think they go through the C&P exam process for that. 

Another note, SIGI did not launch in December 2022. Was scheduled to, but was blocked.

**Comment by hdjustice** [comment]
Hello!  
for #3, you are right, VAN - VA Notify.  This is the target state platform for notifications going to Veterans (email and text).
