### ISSUE TITLE
Remove COVID-19 boosters page and migrant needed content to main vaccines page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#58493]
## Issue Description

Now that CDC guidance is moving away from people getting boosters and instead being up-to-date with a bivalent COVID-19 vaccine, we no longer need a separate [boosters page](https://www.va.gov/health-care/covid-19-vaccine/booster-shots-and-additional-doses/). We can archive the page and set up a redirect to point to the [main vaccines page](https://www.va.gov/health-care/covid-19-vaccine/). We also want to review the content on the boosters page to see if any info should be brought over.

## Tasks
- [ ] Audit boosters page for content that should move to main vaccines page (Randi)
- [ ] Update main vaccines page with needed info (Randi)
- [ ] Find and remove crosslinks to boosters page (Randi)
- [ ] Send to SMEs for accuracy review
- [ ] Copyedit all pages with changes (Megan)
- [ ] Publish (Megan)
- [ ] Archive boosters page (Megan)
- [ ] Remove boosters page from left nav)
- [ ] Set up redirect ticket (Randi)
- [ ] Set up translation tickets (Randi)

## Acceptance Criteria
- [ ] Boosters page is archived

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA I reviewed our boosters page to determine if there's any content that's not currently on our other vaccines page before we archive the page. The only thing I noticed is this Novavax note: 

**Note:** In limited cases, people can get an original (monovalent) Novavax booster if they can’t or won’t get the updated COVID-19 vaccine. Novavax is not updated to protect against the Omicron variant.

Suggestion: We can add this in the accordion "Currently available COVID-19 vaccines" under the bulleted list and before the Janssen info.

Let me know what you think.

**Comment by RLHecht** [comment]
I also removed mentions of boosters and any crosslinks to the boosters page(and changed some to our main vaccines page on the following pages:
- COVID FAQs
- COVID-19 vaccines at VA
- About COVID-19 vaccines

**Comment by RLHecht** [comment]
Moving to blocked until the redirect is in place.

**Comment by RLHecht** [comment]
This redirect is now in place. @megzehn you should be able to archive this now and remove from the left nav. Moving out of blocked. FYSA @coforma-terry

**Comment by megzehn** [comment]
Thanks, @RLHecht! Confirming I removed the booster page from the left nav and archived it in Drupal. 

Moving to validate.

**Comment by megzehn** [comment]
@RLHecht before I close this, is there anything I need to do here on the Spanish and Tagalog pages? Or is that captured in another ticket?

**Comment by RLHecht** [comment]
@megzehn it looks like the Spanish and Tagalog booster pages are redirecting but they're still published and showing in the left nav. I think we'll need to archive them but I didn't create a separate ticket for that. Could we do that work in here? Thank you!

**Comment by megzehn** [comment]
Yes! Confirming that the Tagalog and Spanish pages have been archived and removed from the left nav. Thanks, Randi!
