### ISSUE TITLE
Launch PW survey on Mon, May 22

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#58509]
## Issue Description
The Platform website survey has now been edited and finalized, based on user tester feedback and it is ready to be launched.

The plan will be to have it opened for approximately one Sprint, starting Monday, May 22, 2023 and into the end of Sprint 28.

Link to survey within Optimal Workshop login: https://app.optimalworkshop.com/a/dj540s05/questions/surveys/5c67a6b4-5395-47b7-b70e-23677b3747df/edit#/t/setup/questionnaire

---
## Tasks
- [x] Prepare an announcement checklist. [Link to plan](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2588278812/Platform+Website+User+Experience+Research+v.2#Survey-launch-%26-announcement-timelines).
- [x] Prepare a Slack announcement verbiage. [Link to verbiage](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2588278812/Platform+Website+User+Experience+Research+v.2#Slack-Announcement).
- [x] Launch the survey in Optimal Workshop on Monday, May 22, 2023
- [x] Share with Erika
- [x] Share on Team of Teams
- [x] Share on Slack channels

## Acceptance Criteria
- [x] The survey will be officially open for feedback in Optimal Workshop and will be announced through the various mediums listed above.
