### ISSUE TITLE
[Discovery] 10-10EZ - Reg Only: Research Registration Only processes

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#58506]
## Background
The HEC and VEO stakeholders have requested to start on implementing a "Registration Only" path within the 10-10EZ application, as the Paper form allows today (checkbox Registration or Enroll).
This initiative is being driven by regulation that requires this path be available to Service Members and Veterans who do not wish to or are ineligible to enroll in VA health care.

We need to research the form, the scenarios that would require a "Registration Only" path, the staff-facing process, and the Service Member/Veteran experience.  

### Resources
- [Epic - Registration Path #43221](https://github.com/department-of-veterans-affairs/va.gov-team/issues/43221)
- [Paper form 10-10EZ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZ%20Form/VA_Form_10-10EZ%20(Paper%20form%202-23-2023).pdf)
- [Registration folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/Registration)
- [Meeting Notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Registration/Meeting%20Notes)
     - Including [10/11 meeting](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Registration/Meeting%20Notes/10-11-2023%20Kickoff%20Mtg%20with%20VES%20Technical%20team.md) with VES Tech team
- [VHA Directive (amended January 10, 2023)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Registration/Registration%20and%20Enrollment%20directive%20-%201601A_01(1)_D_2020-07-07.pdf)
     - Definitions:
          - **Registration**: Adding a Veteran or Patient into ES or the VA's electronic health record for the purpose of receiving services at a VA medical facility.  Registration in ES must be completed prior to enrollment.
          - **Veteran**: A person who Served in the active military, naval, or air service and was discharged or released from service under conditions other than dishonorable.

### Registration Use Cases
These are the following confirmed use cases for registration over enrollment. 

- Veteran who is already enrolled/registered in one facility and wants/needs to change facilities.
- Active duty service member with TRICARE.
- Active duty service member getting a Comp & Pen Exam.
- Active duty service member getting care where there is a sharing agreement in place between the DoD and VA.
- Active duty service member getting VA care within a "Military Treatment Facility."
- Registration of collaterals (family members, ex: SAVE Lives Act).
- Active duty transitioning out with a future discharge date (up to 365 days).
- Veterans requesting an eligibility assessment
- Veterans requesting an clinical evaluation PP (Presumptive Psychosis) and/or MST (Military Sexual Trauma)
- Veterans requesting an care or treatment pursuant to a special treatment authority
- Veteran that only wants to be seen for service-connected condition and doesn't want to enroll in VA healthcare.
- HUD-VASH, some Veterans who might not be eligible because of character of discharge, but can be seen.
- Mental health evaluation/services within a year of separation (OTH MENTAL HEALTH).
- Employees (Veterans and non-Veterans)
- Humanitarian cases

### Outstanding questions
- What benefit does "registering" provide?
     - What do you get with Registration vs Enrollment?
- Confirm - this is for both Active Duty Service Members **and** Veterans?
- Is this the first and only time the Veteran will see these terms used?  
     - If so, do they even need to know about these terms at all?
- How do Service Members/Veterans know if they need to complete the 10-10EZ for "Registration Only"?
     - Do they understand why/what scenario they are in that calls for the Reg Only pathway, especially as opposed to enrollment? 
- What are the current volumes of monthly registration vs enrollment applications?
     - What are the volumes of registration approvals, follow-ups (if any) and denials?
     - What are the top 3-5 scenarios/use cases with the most registration-only applications?
- Can a Veteran in good health with no service-connected disabilties or injuries be eligible for VA Health Care or at least obtain care at a VA medical facility?
     - Does their discharge character impact whether they can receive this care?

### Stakeholder request:
>**Desired Functionality:** The online form will be a short form to collect the Veterans information Name, SSN, DOB, Address, Phone Number, Military Service Dates and Reason for Registration Only. This information will feed into VES and place the Veteran in a Registration 
>Only status if they do not wish to enroll. If the Veteran is already known to the system we will capture and update existing information if it is different.
>
>Capture and retain a 1010EZ Registration application when received online.
>
>Create service to receive online form data from VA.gov for Veterans who do not wish to enroll and provide that data to VistA/Millennium. In alignment with PACT Act, COMPACT, SERVICE Act and 38 CFR 17.37 this enables Veterans to request an appointment and register for those not wishing to enroll.

## Tasks
- [x] Review the form instructions for Registration Only
- [ ] Research the scenarios for clear understanding on each one
- [ ] Research the problem being solved by having a "Registration Only" path
- [ ] Consider what Service Members/Veterans know or don't know about Registration vs Enrollment (HEC/VEO feedback to start)
- [ ] Review with Stakeholders on any questions or clarifications needed
- [ ] Collaborate with working sessions to brainstorm on the problem and possible solutions

## Acceptance Criteria
- Have a clear understanding of the need for the Registration Only path and consider how to gain insight on the Service Member/Veteran experience using the Paper form for registration.

**Comment by jessicastump** [comment]
A starting point to gather what we know, our assumptions and any existing data/research we can find around this experience (Veterans and processing systems/people) -  [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684348883203/49fc4ff1bf31f3cabe200663708c1002645b447f?wid=0-1684349447667&outline=open)

**Comment by hdjustice** [comment]
During today's meeting, we discussed the possibility of refactoring the current EZ flow to complete "Registration" fields first, and prompting for enrollment eligibility based on various criteria.  
We have a standing bi-weekly mtg with the VES modernization team who is also working on decoupling "Registration Only" from enrollment on the Enrollment system side.  We will be collaborating with this team to align on outcomes and solutions.
I have reached out to the VA product managers inquiring if anyone has access to volumes of Veteran disability ratings to get a sense of the landscape there, helping to narrow our audiences.  Pending response.
Jessica will work a bit more on research questions, collaborate with Kristen M. and Shane on possible research audiences for Veterans who visit VAMCs (or other facilities) but are not enrolled in VA Health care.
Our next meeting, we will share what we have learned and create a rough outline of how we would present our experimental flow to research participants.

**Comment by jessicastump** [comment]
[Adding a link to the funnels](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684348883203/49fc4ff1bf31f3cabe200663708c1002645b447f?wid=0-1688665713769&outline=open) for the possible MVP use cases.

**Comment by hdjustice** [comment]
@jessicastump - I think we could close this ticket. Do you feel there is anything else outstanding here?

**Comment by jessicastump** [comment]
I agree we can close this initial discovery work ticket, there is alot in the Mural board and notes. 
The only possible item to maybe add would be the notes from the initial/kickoff meeting with VES team on Wednesday 10/11/23.

**Comment by hdjustice** [comment]
Added link to 10/11 meeting notes in the description of this ticket. Closing!
