### ISSUE TITLE
EVSS Migration: Form 21-526EZ Submit Workflow: Add error handling to all_rated_disabilities method

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#58513]
# Problem

A [change](https://github.com/department-of-veterans-affairs/vets-api/pull/12647) to the `all_rated_disabilities` method (in form526_rapid_ready_for_decisioni_concern.rb) was made to retrieve the ICN from the user's account before passing it on to call Lighthouse:

```
icn = UserAccount.where(id: user_account_id).first&.icn
service = ApiProviderFactory.rated_disabilities_service_provider(
  { auth_headers:, icn: }
)
```

Though unlikely, it would be nice to more safely handle the scenario of a failed database lookup against the UserAccount table. Since this code runs within the context of a job (and with little to no existing error-handling), some discovery and design is needed to determine the best way to handle errors _in general_ (not just for this case)

## Tasks:
- [ ] Determine best way to handle errors within a job (sidekiq) context.
- [ ] begin/rescue?
- [ ] error logging?

## Acceptance Criteria
- [ ] Add error handling for a potential failed database lookup for ICN
- [ ] Unit tests to support, if needed
