### ISSUE TITLE
Bug in automation behind the GitHub SOCKS access request

### ISSUE THREAD

**Issue by considerable** [department-of-veterans-affairs/va.gov-team#58519]
## Summary
_Describe what went wrong_

- The automation behind the GitHub SOCKS access issue is adding a new user to the wrong place in config file.

## Steps to Reproduce

1. Use the template [SOCKS Access request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Coperations%2Cops-access-request&projects=&template=socks-access-request.yml&title=SOCKS+access+for+%5Bindividual%5D)
2. Inspect auto-generated PR for correctness

### Actual Result
_Describe what happened that was unexpected or undesired; including screenshots is encouraged_

- https://github.com/department-of-veterans-affairs/devops/pull/13027/files

### Desired Result
_Describe what was supposed to happen; reference existing Github issue that contains a solution if possible_

- The new user must be added to the list of developers sorted alphabetically.

---
## Tasks
 _What work is necessary for this story to be completed?_
- [ ] Recreate the issue for a mocked user account
- [ ] Fix the automation code
- [ ] Test the new code on a mocked user account

## Acceptance Criteria
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kshitiz-devops** [comment]
This was caused by user while creating the issue. While creating the issue the value for **Access Type Requesting** have default value as automation, due to which requestor doesn't change it's value and move ahead with the submission which will add the user to automation group.

To fix this issue an empty option can be at the top of option so that user will select the right option.

**Comment by Kshitiz-devops** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/pull/58607
