### ISSUE TITLE
[BE] Add travel_claims Endpoint in Swagger

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#58514]
## Description
Add ``travel_claims`` endpoint in [swagger](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/check_in/app/docs/check_in/v2/check_in.yaml) document.

## Tasks
- [ ] [BE] **Update check_in.yaml with travel_claims endpoint**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
