### ISSUE TITLE
Tier 2 Process Documentation

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#58512]
## Issue Description

The reviewing and handling of Tier 2 cases is an ongoing process managed by the contact center support team. In partnership with the new daily case review process and the ongoing development of the tier 3 process, the tier 2 process needs to be documented to account for how tier 2 cases will be reviewed, resolved, or escalated to the appropriate channels.

Below is a list of areas that should be covered in the Tier 2 process documentation:

- Explanation for how cases are reviewed by members of the tier 2 team for prompt response and resolution
- Plan for how responses to tier 2 outreach will be handled. This includes a process for monitoring the inbox when salesforce email functionality is not available and will be updated dependent on any technical changes.
- Steps for how to handle escalating cases to Tier 3 for EVSS or VFS Tier 3. This will need to follow any steps already identified by the Tier 3 process but also include criteria for when things will be escalated and what information needs to be included so that the next group is able to easily pick up the case and not redo the work of information gathering. 
- Define any case related fields that might be used (i.e. case status definitions)

---
## Tasks
- [ ] Outline and define Tier 2 Process
- [ ] Document Tier 2 Process
- [ ] Have reviewed by necessary team members
- [ ] Upload to teams and confluence

## Acceptance Criteria
- [ ] Tier 2 process document is created that has been reviewed and approved by team
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
