### ISSUE TITLE
BE | Profile | Direct Deposit | Update Error Mapping and Handling

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#58520]
## Background
Davide Lennon [posted these EVSS error mappings](https://dsva.slack.com/archives/C03P6C3FYMR/p1683918340822839?thread_ts=1683916196.283799&cid=C03P6C3FYMR) that are no longer handled by Lighthouse:
- `cnp.payment.routing.number.fraud.message`  = that message contained "Routing number related to potential fraud"
- `cnp.payment.flashes.on.record.message` = that message contained "Flashes on record"
- `cnp.payment.unspecified.error.message` = that message contained "GUIE50022"
- `cnp.payment.generic.error.message` = any other permutation of that message

A Lighthouse [ServiceException class was added](https://dsva.slack.com/archives/C02CQP3RFFX/p1683916581367179) to vets-api.  For consistency across services, It makes sense to use this for direct deposit calls.

## Tasks
- [x] Add the listed mappings to vets-api so the FE gets the correct error codes.
- [ ] ~Update error handling to use new `ServiceException` class.~
  

## Acceptance Criteria
- [ ] Code reviewed by VFS engineer.
- [ ] Code reviewed by Platform engineer.
- [ ] document the complete list of items (travis to create follow on FE ticket based on the comprehensive list of messages)_

**Comment by tpharrison** [comment]
@Tonksthebear This is the ticket I'm working on for Direct Deposit changes.

**Comment by Tonksthebear** [comment]
Thanks for the link!

**Comment by tpharrison** [comment]
The related PR large (~1100 lines), so I spoke with the platform team and I'm going to need to break it up into at least 2 separate PRs.  They are reviewing another very large PR that is closely related (also Lighthouse migration code) and they want to make sure that this is squared away before reviewing my PR.  I'm going to try and get this broken up and reviewed by EOD tomorrow, but if I can't, it'll need to wait until next week since the platform is on a skeleton crew this Friday.

**Comment by mtcA6** [comment]
@tpharrison cool! so that means @adamwhitlock1 can pick up [FE | Profile | Direct Deposit - FE End to End Integration Work#54896](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54896)

once that's done, then we move onto [BE | Profile | Direct Deposit | Integration Testing between FE and BE (Staging)#54771](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54771)

Is that right?

**Comment by tpharrison** [comment]
Yep!
