### ISSUE TITLE
🔴 Intake and Prioritization processes on the DE Product Board

### ISSUE THREAD

**Issue by dmkosko** [department-of-veterans-affairs/va.gov-team#58523]
## We are looking to understand if these processes are still valid and how the work is started, tracked, and prioritized. This is important because there's a feeling that cards do not follow a process and sometimes items are moved to the front of the line without proper vetting/discussion of the impact. These discussions could help with identifying work in progress limits and ensuring the most beneficial work is prioritized correctly.  

---
## Tasks
- [x] Kickoff meeting held
- [ ] All 1:1 interviews scheduled with Alpa and Dan
- [ ] Responses cataloged in a rainbow-style spreadsheet
- [ ] Schedule the retrospective with the discovery team

---
## Definition of Done
- [ ] identify existing versions of each item within the various components of OCTO
- [ ] identify the processes and docs in place that use existing versions
- [ ] identify any work currently underway to update related docs or processes
- [ ] coordinate with the product ops team to create a single, OCTO version of each item
- [ ] update doc links, archive old docs, and update processes to direct users to the new version
- [ ] ensure the new version is listed in onboarding docs and processes

---
## How to configure this issue
- [ ] **Review issue** with the Product Ops team
- [ ] **Prioritize**  
  - label accordingly: 
    - Low Priority - 🟢
    - Medium Priority - 🟠
    - High Priority - 🔴
- [ ] **Add Assignees** (who will do this work?)

**Comment by dmkosko** [comment]
Kickoff session one recording [here](https://dvagov-my.sharepoint.com/personal/lisa_koenigsberg_va_gov/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Flisa%5Fkoenigsberg%5Fva%5Fgov%2FDocuments%2FProductOperations%2FDE%20Product%20Board%20Process%20Initiative%20%2D%202023&view=0) and meeting minutes posted to channel. Starting to set up interviews with the five individuals we targeted from the Product Board.

**Comment by dmkosko** [comment]
Met with the group today to develop and discuss the potential interview questions. We will be conducting pilot interviews which will allow us to get feedback on the questions and tweak them, as needed. Robyn will be assisting in putting the questions in an interview guide which will also have an area for notes and comments.

**Comment by dmkosko** [comment]
All pilot interviews completed. Follow-up meeting scheduled with the sprint group to discuss key takeaways and next steps. After that call the expectation is for interviews to be set up with our participants.

**Comment by dmkosko** [comment]
Follow-up call moved to 7/17

GitHub site in process of being created [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/octo/product/Intake%20&%20Prioritization%20Sprint%20Discovery.md) which will store documents and provide context about our mission.

**Comment by dmkosko** [comment]
Follow-up call meeting minutes are [here](https://dvagov-my.sharepoint.com/personal/lisa_koenigsberg_va_gov/_layouts/15/doc.aspx?sourcedoc={362ff50e-2efa-48c6-8edf-c2d0eb272aa0}&action=edit)

ACTION: Erica and Julia to finish up their pilot interviews and send to Alpa/our channel by July 21st  
ACTION: Alpa to attach Erica and Julia’s portions into the consolidated document by July 28th  
ACTION: Alpa to determine next steps and where to take the project next after talking with Lisa, timeframe TBD

**Comment by dmkosko** [comment]
Alpa created and then sent out a 'consolidated takeaways' document from our pilot interviews which can be viewed [here](https://dvagov-my.sharepoint.com/:w:/r/personal/lisa_koenigsberg_va_gov/Documents/ProductOperations/Intake%20and%20Prioritization%20Initiative%20-%202023/Consolidated%20Takeaways.docx?d=wfc49f5fb530e4df293b1599c415fa55c&csf=1&web=1&e=vWDF61).

**Comment by dmkosko** [comment]
Final interview participants assigned, but still need someone for Julia to interview (currently looking into). Documents will be uploaded [here](https://dvagov-my.sharepoint.com/personal/lisa_koenigsberg_va_gov/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Flisa%5Fkoenigsberg%5Fva%5Fgov%2FDocuments%2FProductOperations%2FIntake%20and%20Prioritization%20Initiative%20%2D%202023&view=0).

**Comment by dmkosko** [comment]
Discovery sprint has wrapped up. See below regarding the message sent from Alpa to the team. Any documentation is linked [here](https://dvagov-my.sharepoint.com/personal/lisa_koenigsberg_va_gov/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Flisa%5Fkoenigsberg%5Fva%5Fgov%2FDocuments%2FProductOperations%2FIntake%20and%20Prioritization%20Initiative%20%2D%202023). 

Hello Team,
First, thank you once again for participating on the Intake & Prioritization Discovery project!

All of you scrubbed in to create an interview guide, to interview each other and other OCTO staff, and to document your findings – to determine how intake and prioritization are done in OCTO, and opportunities for improvement.

Dan and I discussed the research findings with our new Product COP director, Matt Self. He honed in on the need for better coordination among teams and the opportunity to define intake and prioritization under the lens of product strategy.

Dan and I will be meeting with Matt again – to help define next steps and take our work to the next step. Stay tuned.

**Comment by dmkosko** [comment]
Final interview notes are linked [here](https://dvagov-my.sharepoint.com/:w:/r/personal/lisa_koenigsberg_va_gov/_layouts/15/Doc.aspx?sourcedoc=%7B89AC28BE-4F80-4CD2-97B9-0F9A6DB4BD73%7D&file=FINAL_Consolidated%20Intake%20and%20Prioritization%20Notes%20from%20final%20interviews%202023.docx&action=default&mobileredirect=true). Additional notes are provided in the bottom of the doc.
