### ISSUE TITLE
Survey results analysis

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#58524]
## Issue Description

The Platform website experience survey has now been closed at this point and it is time to go through all the survey entries, organize and analyze the feedback and document any insights.

---
## Tasks
- [x] Review all survey entries
- [x] Organize feedback in spreadsheet
- [x] Create PPT to share with team: https://docs.google.com/presentation/d/16UomRBxSyfqASYvRVMxPPI_CV6ui8WFqpYbiYMCz7KE/edit?usp=sharing

## Acceptance Criteria
- [x] An artifact of slides or other document will be created to share survey insights
