### ISSUE TITLE
Onboard design team 2

### ISSUE THREAD

**Issue by lydiahooper** [department-of-veterans-affairs/va.gov-team#58540]
## Issue Description
With 526 team 2 joining us, we can revisit/add to documentation on Github and get design folks up to speed.

---
## Tasks
- [x] Meet with design folks to discuss design debt backlog (error messages, sitemap) and relevant research reports
- [x] Create Github folder that includes list of links to previous research and research summary PDF
- [x] Document key info such as list of contacts, workflow for design changes, when to work with collab cycle, etc.
- [x] Update personas page on Github 

## Acceptance Criteria
- [x] New and updated Github folders/pages
