### ISSUE TITLE
Pull in progress FSR forms count for April and May

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#58559]
## Issue Description
Stakeholders are concerned with the lower amount of FSRs that are being submitted in recent months and are curious if Veterans may be leaving forms incomplete or pausing them. We need to pull the numbers for in progress 5655 forms that began in the months of April and May but were not submitted.

---
## Tasks
- [ ] Generate script to find in progress forms that weren't submitted
- [ ] Hand script off to platform to run in production

## Acceptance Criteria
- [ ] We know of the amount of incomplete forms for these months
- [ ] Make a rake task.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kjsuarez** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/12832
