### ISSUE TITLE
Set Up BigQuery

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#5855]
## Product Outline
Product Success Tool Product Outline [Link](https://docs.google.com/document/d/1GuuhRXT8-NjEHdFHysNg1VA1o89Qr0_Mkrg46Q8kBeI/edit#heading=h.ev8ozaubejnk)

Warehousing [Recommendation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/research/product-success-data-warehouse-bi-recommendation.md)

Schema [Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/research/product-health-prototype/bigquery-schema-proof-of-concept.md)

## High Level User Story/ies
How might we set up a data warehouse so that we can provide VFS teams with more relevant and more accurate data to make product decisions?

## Hypothesis or Bet
**If** _we set up BigQuery_ **then** _we expect to have more and better access to data sources, including, but not limited to Call Center flat files, Prometheus data, and funneling and timing data from Google Analytics_.

## OKR
O2: Customers use qualitative and quantitative user data to build and iterate on VFSs.				

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

- [ ] VSP has bought and has licensing to BigQuery
- [ ] VSP has "stood up" BigQuery with relevant user access
- [ ] VSP has connected BigQuery to the following data sources:
    - [ ] Google Analytics
    - [ ] Call Center files (flat CSV)
    - [ ] Prometheus
    - [ ] ForeSee (direct or historical CSVs)
    - [ ] Medallia (timeline TBD)

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
