### ISSUE TITLE
Propose a revamp to Platform Docs main page; adding 7th button: "Feedback"

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#58561]
## Purpose
With the increased number of feedback mechanisms (our two-mechanism approach with the satisfaction survey, FRP, Content Team's page feedback, etc etc) the Support page is becoming tangled with several different feedback efforts that could cause confusion and frustration with the VFS customer.

[Research plan](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2671640623/Research+Plan+for+Revamp+to+Support+Overview+Page)

![Screenshot 2023-06-15 at 10.10.45 AM.png](https://images.zenhubusercontent.com/622ba3fd325cb66ad49f3f28/9258a5f8-34e0-4f25-bc99-9bf487b26abc)
Additionally: it would be helpful to have descriptions or more descriptive titles/language tied to each of the items on the page.

### Pivot:
Platform Content is currently engaged in research on the IA of the Platform Docs site, so we're asking about the best time to consider adding a 7th "button", Feedback, to the main site.

This item may need to wait until their research is completed.

## Tasks
- [x] Reach out to Platform Content team with idea about adding 7th button (Bryan)
- [x] Learn where they are and what timing looks like for discussing this change

## Acceptance Criteria
- [x] Get feedback from PCT

## Next Steps:
PCT is meeting w/ PO in next sprint to brainstorm solutions.  I'll create a follow-up ticket for after that.

**Comment by steel36** [comment]
Pivot on timing of this ticket due to similar research by PCT; will rollover
