### ISSUE TITLE
Pilot Transition Back to Sketch

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#58563]
In [#57125](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57125), we arrived at a plan for working solely within Sketch without Abstract. Before applying this to all designs, we need to try out this method in a pilot phase, starting with the existing application wireframes for Check-in (including travel reimbursement).

[Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677519559665/ef1c00d871a0766261940d6fce80faed94059c05?sender=ua2ec2e34eb6128f3375e0207) with new Sketch setup

## Tasks
- [ ] Set up two new Sketch files: 1 regular file for Check-in (+ travel reimbursement) and 1 production file (this will also be used for production versions of Pre-check-in and Unified Check-in)
- [ ] Create the page setup shown in the Mural board for each file
- [ ] Copy the existing application Check-in wireframes to their correct pages within the new setup
- [ ] Work through any questions or concerns that come up - bring to UX sync if needed
- [ ] Document any important instructions for UX and FE 
- [ ] Share with UX and FE
- [ ] Create f/u tickets for next step

## Acceptance Criteria
- [ ] Check-in (with travel) wireframes have been copied into the two new files
- [ ] This process has been fully ironed out
- [ ] Important instructions are documented
- [ ] Results shared with UX and FE
