### ISSUE TITLE
[SPIKE] [UX] Pilot transition back to Sketch

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#58564]
In [#57125](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57125), we arrived at a plan to move designs to Sketch only (no Abstract). Before applying this change to all designs, we need to try out this method in a pilot phase, starting with the existing application wireframes for Check-in (including travel reimbursement).

[Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677519559665/ef1c00d871a0766261940d6fce80faed94059c05?sender=ua2ec2e34eb6128f3375e0207) with new Sketch setup

## Tasks
- [x] Set up two new Sketch files: 1 regular file for Check-in (+ travel reimbursement) and 1 production file (this will also be used for production versions of Pre-check-in and Unified Check-in)
- [x] Create the page setup shown in the Mural board for each file
- [x] Copy the existing application Check-in wireframes to their correct pages within the new setup
- [x] Work through any questions or concerns that come up - bring to UX sync if needed
- [x] Document any important instructions for UX and FE 
- [ ] Share with UX and FE
- [ ] Create f/u tickets for next step

## Acceptance Criteria
- [x] Check-in (with travel) wireframes have been copied into the two new files
- [x] This process has been fully ironed out
- [x] Important instructions are documented
- [ ] Results shared with UX and FE

**Comment by loripusey** [comment]
@cgednalske can you guys point this before planning today?

**Comment by zach-park** [comment]
Initial documents:

(Pilot) Check-in - UXUI
https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f

(Pilot) Production
https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744

**Comment by loripusey** [comment]
Meeting on 6/5 to validate with UX
