### ISSUE TITLE
Require user flows at Design Intent

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#58579]
## User Story
As a Governance team member, I want VFS teams to provide a user flow diagram at the Design Intent so that I can understand what path the Veteran will follow in order to complete their intended task.

Assignee: @sterkenburgsara 
Peer Reviewer: @CherylEvans 

## Description
Governance PO @humancompanion-usds has requested that we make the user flow a required artifact for VFS teams to provide for the Design Intent. When the VFS team does not provide a user flow, it makes it very challenging for Governance team to understand the intended path the Veteran will take. This can impact the feedback provided by design, IA and accessibility practice areas.

Discussion with team at refinement:

- Quality and style of user flows will vary. Are they just showing us happy path? 
- Create a template teams could use.
- Helpful to have VFS teams use the same symbols. Template could use standardized key.
- DST sketch library has an annotations collection (not on design.va.gov)
- Link to teams/products with user flows that we like.
- Talk to Naomi about swim lanes (re her work with Jim?)

**Note 5/24:** The above options all require additional research and/or effort to implement. In order to make user flows mandatory at Design Intent as soon as possible, the MVP for requiring user flows will be simple and will not include a template for teams, examples of other user flows, guidance on quality and/or standardized annotations. While this ticket is being worked on, we're simultaneously completing https://github.com/department-of-veterans-affairs/va.gov-team/issues/59001 to better understand how quality of user flow diagram completed by VFS teams. Based on the outcomes of that research, we'll determine if additional user flow diagram guidance is needed.

## Impacted Artifacts
[Design Intent touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent)
[Design Intent code block ](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities#Design-Intent-code-block)on Collab Cycle Kickoff Moderator Responsibilities 

## Tasks
- [x] Modify the code block and touchpoint page to communicate that the user flow diagram is a required artifact
   - should we go back and modify the CC Request tickets for teams who have submitted kickoff but not yet schedule DI? We could get earlier fb for the research study. 
- [x] Coordinate with assignee from #59001 to ensure user flow diagram requirement is launched alongside the research study
- [x] Announce changes to VFS teams following the Platform Communication Playbook
- [x] Let Shira know so she can share in ToT

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS teams know that they are required to provide a user flow diagram to Governance at the Design Intent touchpoint

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by sterkenburgsara** [comment]
@CherylEvans how do you feel about this update? ![Screenshot 2023-06-01 at 9.50.34 AM.png](https://images.zenhubusercontent.com/6346cd7ec508fe43b65ae3db/9dff69c5-55bf-4d5e-a7e9-a9b72aa83329)
![Screenshot 2023-06-01 at 9.50.47 AM.png](https://images.zenhubusercontent.com/6346cd7ec508fe43b65ae3db/42a6cfb1-8311-42c6-8917-5db31df40e95)

**Comment by CherylEvans** [comment]
@sterkenburgsara Looks great. You don't need to capitalize (T)eams. :-)

**Comment by sterkenburgsara** [comment]
Update: changes have been published (updates to Platform Website should take place this afternoon). I will update previously opened collab cycle tickets to reflect the requirement of user flows today.

**Comment by sterkenburgsara** [comment]
@shiragoodman this one will be ready to close out this sprint, but will be slightly out of sync with the companion ticket #59001 since I haven't begun that one yet. I don't think it will have an impact, since only 2 current tickets are awaiting Design Intent & they have been sitting in that column for many moons. Hopefully we can make progress on / launch that other ticket before new Design Intents get scheduled. Thoughts?

**Comment by shiragoodman** [comment]
Thanks for filling me in @sterkenburgsara ! I'm fine with this going live while we finalize the other ticket.
