### ISSUE TITLE
[UX] AVS MVP: High-fidelity Wireframes

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#58573]
# Description
Create a high-fidelity wireframe set for AVS, so we are ready for user research.

# Tasks
- [x] Wireframe set in [Sketch](https://www.sketch.com/s/05d5a740-4fc7-4380-8d83-e7acfbab201b).
- [x] Update wireframes until ready.
- [x] Review with CAIA, health app team

# Acceptance criteria
- [x] When the wireframes are sent off to the appointments team to be incorporated in the prototype
