### ISSUE TITLE
Sidekiq Restarts

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#58570]
## Description

We are noticing in the logs that [Sidekiq pods are restarting.](https://vagov.ddog-gov.com/logs?query=env%3Aeks-prod%20host%3Avets-api-sidekiq-79c55c9[…]=stream&from_ts=1684349985000&to_ts=1684350585000&live=true) This means that they are somehow failing the liveness probe. We have a liveness probe that pings 7433... which checks for a successful job completion (through sidekiq alive)

Here's how Sidekiq alive works

```
The Sidekiq-Alive gem sets up a special queue in Sidekiq and periodically enqueues a job to that queue. The purpose of the job is to touch a key in Redis as a "heartbeat" to signal that Sidekiq is still alive and working properly. If the key isn't updated within a certain time frame, Sidekiq-Alive assumes that Sidekiq is dead or unhealthy, and triggers a failure of the liveness probe.
```

Before moving to EKS, there used to be a sidekiq alive queue for each worker process but now there is just one named sidekiq-alive-api.va.gov for all worker processes.

## Tasks
- [x] Remove Sidekiq Alive Cleanup
- [x] Sync and Deploy
- [x] Monitor Logs

## AC
- [x] Sidekiq pods are no longer restarting

**Comment by LindseySaari** [comment]
PR Here

**Comment by LindseySaari** [comment]
Continuing to monitor and will close this in the morning after checking logs first thing

**Comment by LindseySaari** [comment]
Had to rename the Sidekiq Alive Queues and we just verified that the queue naming scheme and queue removal process is functioning properly in lower envs. [PR for prod here](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1929) and will sync at 3pm

**Comment by LindseySaari** [comment]
This is complete. Queues are functioning properly and cleaning up

**Comment by LindseySaari** [comment]
Reopening this... queues are not being deleted properly

**Comment by LindseySaari** [comment]
PR opened here to cleanup orphaned queues. Queues deletion for the most part is working through the shutdown_callback, but on the occasion that there are jobs that run longer than the terminationGracePeriodSeconds OR long running jobs, the shutdown_callback isn't run properly, therefore leaving orphaned Sidekiq Alive queues hanging around. This job will take care of those orphaned queues
