### ISSUE TITLE
Medallia -  Focus order and reading order for screen readers

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#58574]
## Issue Description
Reading order - after reading the last survey question/radio button group, the CLOSE button is read aloud, followed by the SUBMIT FEEDBACK button, even though the SUBMIT FEEDBACK button appears first
---
## Tasks
- [ ] Fix tab order to make Submit Feedback button come before close

## Acceptance Criteria
- [ ] Screen reader reads SUBMIT FEEDBACK button before CLOSE button
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
[@Aubrey Arcangel](https://dsva.slack.com/team/U9C0RHFHA) has updated the button aesthetics (not the tab order) and will tag the accessibility strategist when he submits the PR—targeting Friday, 8/8/25.
The proposed repositioning of the submit and close buttons on the intercept modal change requires an override to the current accessibility standards, it will need to be reviewed and approved by the accessibility strategist on the OCTO team at VA — Martha Wilkes. Once the PR is submitted, @aubrey will tag Martha to review and provide authorization.

**Comment by aubreyarcangel** [comment]
We previously swapped the “Close” and “Submit” buttons using the CSS order property so that the primary button (Submit) appeared on the left, matching the VA Design System visual pattern. However, this approach caused a mismatch between the visual order and the DOM/tab order, which does not meet accessibility standards (keyboard and screen reader users would encounter “Close” first).

Because Medallia is a COTS (commercial off-the-shelf) platform, the VSignals team is limited to the capabilities of its WYSIWYG-type UI editor and cannot directly modify the underlying HTML or DOM order for these buttons. Per guidance from VSignals/Medallia Engineering, there is currently no standard way to change the button order in the DOM.

**To maintain accessibility compliance, we are reverting to the default layout with the primary button (Submit) on the right for now.** A feature request has been submitted to Medallia Engineering to support this change in a future release.

**Comment by artsymartha68** [comment]
Our accessibility experts had more to say about how the code is currently structured to make it even better:
 

1. We assume that for styling reasons, they’re hiding actual `<labels>` and `using aria-label` for screen readers. Like `<input aria-label="My label"><label aria-hidden="true">My label</label>`. it works, but if someone’s using Google translate or another translation software, the English will be what’s read aloud.
2. They use `role="text"` all over the place, like `<p role="text">My question</p>`. `role=text` is really unneeded here, and is an issue if there’s any children with roles - those roles will be overwritten (`<p role="text"><a href="#">My link</a></p>` — the link will lose its “link” role)
3. They way the code uses fieldset/legend works but could be improved.
