### ISSUE TITLE
[526 - Historical Claims] Address Payload(s)

### ISSUE THREAD

**Issue by kylesoskin** [department-of-veterans-affairs/va.gov-team#58571]
## Value Statement
**_As a_** person at the VA processing historical 526 claims
**_I want to_** be able to cross-reference my records with va.gov records from submissions
**_So that_** I can still perform actions on the claims if I (person at VA) do not have an address on file

---
## Background Context
 Previously we (va.gov) provided the VA a list of participant IDs and corresponding address from va.gov submissions, that corresponded to a batch of failures. Instead, it is easier and cleaner, for us to just provide 1 big list for all the failed claims in the initial 40k, instead of for each individual chunk/batch. This also ensures that all batches have the "most recent" address. 

## Acceptance Criteria
- [x] A mapping of participant IDs to address is generated for all ~40k of the submissions flagged by the VA
- [x] The mapping file is delivered via secure email to the VA (David Reis) 

## Out of scope
- submissions outside of the initial ~40k identified by the VA. There will be a need to generate another list for failures outside of that locked-in bunch. 

## Tasks
- [x] Rediscover required format desired
- [x] Ensure existing script matches format desired
- [x] Run script, generate file, upload to S3
- [x] Pull down in RDP and email securely 

---
## Definition of Ready 
- [x] ~40k IDs identified
- [x] Script found and double checked
- [x] Format verified

## Definition of Done
- [ ] Approved by VBA and product manager
- [x] The mapping file is delivered via secure email to the VA (David Reis)

**Comment by kylesoskin** [comment]
David from VBA reported that it is fine to be 1 single address payload in the IPT channel. We can now refine further @saderagsdale

**Comment by kylesoskin** [comment]
This should be done today.

**Comment by kylesoskin** [comment]
Need to rejigger with cross-ref participant/dup-C list

**Comment by kylesoskin** [comment]
Resent, awaiting final approval
