### ISSUE TITLE
FE Implementation of New Claim Card

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#58589]
## Value Statement
**_As a_** veteran checking the status of their disability claim
**_I want to_** be able to distinguish my claims from one another
**_So that_**  I can reference it if I need to contact the call center or provide that info to my representative.

---
## Background Context
- Initial decision research shows that veterans would like this feature. 

## Design Concept
 
![Group 20](https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/5291ffe0-263a-4d6b-bd7e-f01a94898a8b)

## Acceptance Criteria
- [x] Implementation is complete for all claim & decision review cards

## Designs and Build Notes
- [x] Implementation should match the [Sketch](https://www.sketch.com/s/98e35645-34eb-40cf-80c1-6c4952943584/p/B9C46ABC-36AD-4CA8-9896-55762FC6912E/canvas) design

## Out of scope
- Claim details page

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherWidmont** [comment]
We've updated the title to reflect that fact that this is a holistic implementation of the card design which includes distinguishing between claims in addition to other things

**Comment by HeatherWidmont** [comment]
https://www.sketch.com/s/98e35645-34eb-40cf-80c1-6c4952943584/p/B9C46ABC-36AD-4CA8-9896-55762FC6912E/canvas
