### ISSUE TITLE
[UX] AVS MVP: Research Sessions

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#58580]
# Description
Running interview sessions with Veterans

# Tasks
- [x] Download the participant tracker from Perigean
- [x] Make sure we have meeting invites with a Zoom
- [x] Send any necessary messages to Perigean via Slack
- [x] Attend sessions
- [x] Make sure observer and notetakers are organized
- [x] Gather notes after each session
- [x] Download videos from each session

# Acceptance Criteria
- [x] Post deidentified notes to GitHub
