### ISSUE TITLE
Make the Collaboration Cycle timeslots more consistent throughout the week

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#58582]
## User Story
As a Governance team member, I want to change the timeslot availability for Collab Cycle so I no longer have back to back meetings and so our PO is able to attend.

Assignee: @it-harrison 
Peer Reviewer: @CherylEvans 

## Description
At the 5/12 1:1 between @shiragoodman and @humancompanion-usds, it was suggested that the Collaboration Cycle timeslots for scheduling a Design Intent, Midpoint Review and Staging Review be more consistent throughout the week. 

Matt shared that there are certain days/times where he has prior commitments and can't make the current CC timeslots work. See his comment on this ticket. 

This ticket will also focus on moving the timeslots so that there are no longer back to back Collab Cycle touchpoints. 

@allison0034 started a[ Slack thread](https://dsva.slack.com/archives/GNF5GSD9N/p1684877526799579) on the #platform-governance-team channel to share previous commitments Governance team has on Tuesday/Thursday in order to find a new timeslot that works for everyone. 

## Impacted Artifacts
Calendly
[Calendly guide](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2017034292/Collaboration+Cycle+Calendly+guide)
Onboarding doc for Governance (?)
Collaboration Cycle Calendar in Google (?)

## Tasks
- [x] Determine alternate time slots for Tuesday and Thursday (see Allison's Slack thread above)
   - existing timeslots 11am ET Tuesday and 2pm ET Thursday will be cancelled
- [x] Share with Governance team and Matt Dingee. Ensure everyone approves of the new slots.
- [x] Determine which date the new schedule will begin to take effect
- [x] Once approved by team, work with Shira or Allison to update availability in Calendly
- [x] Update [Calendly guide](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2017034292/Collaboration+Cycle+Calendly+guide)
- [x] Update Onboarding doc, if applicable
- [x] Update Google calendar, if applicable
- [x] Follow Platform Communication Playbook for communicating change to VFS teams

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Collaboration Cycle timeslots are no longer back to back
- [x] Collaboration Cycle timeslots are not conflicts for anyone on Governance, including PO

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@humancompanion-usds  Could you please let us know which [Collab Cycle timeslots](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2017034292/Collaboration+Cycle+Calendly+guide) you currently have on ongoing conflict with?

**Comment by humancompanion-usds** [comment]
* Monday 3:30pm - 4:00pm ET - I have a calendar hold for this one and generally can make it.
* Tuesday 11:00am - 12:00pm ET - I don't have a hold and this conflicts with Chelen's stand-up for platform-crew at 11am. I can skip stand-up as needed (and my time is already held by that invite). I'll block off the 2nd 30 minutes.
* Thursday 1:30pm - 2:30pm ET - This one overlaps with Kevin's 2pm OCTO Design CoP Monthly meeting every 2nd Thursday of the month. Thus every month I miss this one if it's at 2pm. All OCTO designers are required for this meeting so when it conflicts I skip CollabCycle (which I'd rather not have to do). So this is the problematic time slot for me.
* Friday 11:30am - 12:00pm ET - This is fine. I'll create a hold for this.
* Friday 2:00pm - 2:30pm ET - I have a hold for this one and generally can make it (though it's right after Design System Council and thus I would prefer to be writing up next steps coming out of that meeting. But that's my problem.)

**Comment by it-harrison** [comment]
@shiragoodman @allison0034 @sterkenburgsara @CherylEvans @briandeconinck @humancompanion-usds 
After comparing schedules there are very few options for moving collab cycle hours on Tuesday / Thursday. The open windows are:

**Tuesday**:
* 10.30 - 11.00 ET
* 11.30 - 12.00 ET (this interval is within the current Design / Midpoint Tuesday window)
* 4.30 - 5.00 ET

**Thursday**
* 1.30 -2.00 ET (this interval is within the current Thursday window for Staging Review)

Note: I didn't include any slots before 10.30 in consideration of West Coast teams.

**Comment by shiragoodman** [comment]
@it-harrison what about Tuesday at 3:30pm ET? I think that might work..

Thursday might be a bit trickier.

**Comment by it-harrison** [comment]
@shiragoodman Tuesday at 3.30 could work except for your Platform Huddle.

**Comment by shiragoodman** [comment]
I can still attend the first part of the huddle. It usually wraps within 30 minutes.

**Comment by it-harrison** [comment]
@humancompanion-usds it looks like the best/only options to move the times are:
* **Tuesday at 3.30 ET.**
* **Thursday at 3.30 ET**
_(We will cancel the existing 11am ET Tuesday and 2pm ET Thursday slots)_
But we want to make sure you can make these times before making any switch.

**Comment by humancompanion-usds** [comment]
Yes! I can make that work. Let's do it!

**Comment by shiragoodman** [comment]
@briandeconinck @allison0034 @sterkenburgsara @CherylEvans Does this work for everyone?

**Comment by allison0034** [comment]
I will have to drop by 3:50 on Tuesdays during the school year and once a month I have the Platform UX meeting on Thursdays : /

**Comment by shiragoodman** [comment]
@it-harrison once we hear from everyone, please continue with the tasks in the ticket. It's likely this will move into the next sprint.

**Comment by sterkenburgsara** [comment]
This should work for me. Thanks!

**Comment by shiragoodman** [comment]
We are proposing cancelling the Tuesday 11am ET slot and replacing with Tuesday 3:30pm ET, as well as cancelling the Thursday 2:00pm ET slot and replacing with Thursday 3:30pm ET.

**Comment by briandeconinck** [comment]
These work for me!

**Comment by CherylEvans** [comment]
Those times work for me as well. :-)

**Comment by it-harrison** [comment]
Now that the team has weighed in and we have settled on a new schedule this ticket can proceed into the next sprint.

**Comment by shiragoodman** [comment]
@it-harrison we discussed in Planning - goal is to have this work completed by End of Sprint, with the new schedule beginning Thurs June 22

**Comment by it-harrison** [comment]
@shiragoodman looking at the Collab Cycle calendar there are no scheduled touchpoints in the Tues 11 - 11.30 ET or Thurs 1.00 - 1.30 ET beyond June 15. So these changes could take effect June 20th (the 19th is a holiday).

**Comment by allison0034** [comment]
@it-harrison @shiragoodman  I updated Calendly. [Staging review calendar](https://calendly.com/collaboration-cycle/staging-review?month=2023-06&date=2023-06-29) and [design intent/midpoint calendar.](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review?month=2023-06&date=2023-06-29)

Just to confirm this is the new availability for design intents/midpoints
- ![Screen Shot 2023-06-13 at 10.20.41 AM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/7253f956-016a-4d08-ad40-1d21a5054892)
- 

And this is the new availability for staging
- ![Screen Shot 2023-06-13 at 10.21.42 AM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/fc3a9813-78d3-447e-b81c-0102b7928ad5)

**Comment by it-harrison** [comment]
@allison0034 looks perfect, thank you!

**Comment by it-harrison** [comment]
@CherylEvans can you take a look at the updated [Calendly guide](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2669608961/Copy+of+Collaboration+Cycle+Calendly+guide+-+58582)?

**Comment by CherylEvans** [comment]
@it-harrison, I am looking at it now.  :-)

**Comment by CherylEvans** [comment]
@it-harrison, I made a few edits for grammar and punctuation. I also changed 2 headings for proper nesting. What do you think?

**Comment by it-harrison** [comment]
@shiragoodman I have drafts of a change announcement and a change history post for this ticket:

:mega:  Attention: VFS teams

Tuesday, Thursday Collaboration Cycle Time Slots Changing

On 06/22/23, the Collaboration Cycle Time Slots on Tuesday and Thursday will change:
* the 11.00 AM ET Tuesday is moving to 3.30 PM ET Tuesday
* the 2.00 PM ET Thursday is moving to 3.30 PM ET Thursday

Impact:  Any VFS team looking to schedule Design, Midpoint, or Staging reviews on Tuesdays or Thursdays

Questions:  Please post any questions in thread or reach out to #vfs-platform-support


--------------

June 22, 2023
Tuesday and Thursday Collaboration Cycle Time Slots have changed. 
* The Tuesday 11.00 AM Design Intent / Midpoint Review time slot has moved to 3.30 PM ET. 
* The Thursday 2.00 PM ET Staging Review time slot has moved to 3.30 PM ET.

**Comment by shiragoodman** [comment]
this looks perfect Ian. Thank you. I'll add to ToT on Tuesday. Can you push the changes today?

**Comment by it-harrison** [comment]
@CherylEvans this is ready for review:
* see Allison's screenshots above for new time slots
* [calendly guide](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2017034292/Collaboration+Cycle+Calendly+guide)
* [change announcement](https://vfs.atlassian.net/wiki/spaces/CC/pages/1846870032/Change+history)
* [slack announcement](https://dsva.slack.com/archives/C03R5SBELQM/p1686947467793709)

**Comment by CherylEvans** [comment]
@it-harrison, Everything looks great, Ian.  It is good to close. :-) 
I checked off the remaining boxes above for you. :-)
