### ISSUE TITLE
Guide users to stronger evidence submissions

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#58591]
## Value Statement
**_As a_** veteran with a pending disability claim who has received an evidence request
**_I want to_** know exactly what a strong and poor submission might look like
**_So that_** I can provide the former and avoid the latter.

---
## Background Context
Many different kinds of evidence are provided in CST, but often it's unclear what a strong submission for that request might look like. It's important we provide as much context as possible to help veterans understand what to submit, why it's being requested, and for what specific contention. 

## Acceptance Criteria
- [ ] _AC_
- [ ] _AC_
- [ ] _AC_

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
