### ISSUE TITLE
Help veterans understand background processes

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#58590]
## Value Statement
**_As a_** veteran with a pending disability claim
**_I want to_** understand what's happening behind the scenes with my claim, what processes and policies are being followed when things like evidence requests are being made and reviewed
**_So that_** I can provide evidence that meets requests in such a way I am positioned to get the best outcome possible.

---
## Background Context
- Add here

### These are early concepts and not final designs

![Process1](https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/4bda90ac-4ec1-41fb-acf6-eb3feaa9ebb6)

## Acceptance Criteria
- [ ] Each step in the claims process provides a rough overview of what's happening behind the scenes
- [ ] Evidence request phase talks about the VA's duty to assist and what that means
- [ ] Veterans can see what happens before and after evidence requests so they can anticipate how submissions play into the process

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
