### ISSUE TITLE
Make Collaboration Cycle Office hours schedule-only

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#58599]
## User Story
As a Governance team member, I want to pivot from open hours to schedule only for the Collaboration Cycle office hours so that I can use my time wisely and better prepare for topics from VFS teams.

Assignee: @allison0034 
Peer Reviewer: @it-harrison 

## Description
The Design office hours, which are every Tuesday afternoon, recently pivoted to schedule only, meaning folks interested in attending need to sign-up for office hours at least 30 minutes before the office hours. They have also introduced a 2 person limit (or 2 topic limit). Governance team is considering making the same change for Collaboration Cycle office hours as they are infrequently attended and can be time consuming for Governance team members. 

**Other suggestions from the team:**

- Make a required field for topic - give us an idea of what you want to talk about.
- Auto forwarding of Calendly notifications to Governance team (via Calendly?)
- Remove Slack notification on #vfs-platform-support
- Remove CC OH from Collab Cycle Calendar (or at least remove Zoom info)
- Update Platform Website:
   - Resources
   - FAQ
   - Contact Us
- Custom questions re: practice area included in Calendly sign up

## Impacted Artifacts
Calendly Collab Cycle Office Hours event
Platform Website:
   - [Resources](https://vfs.atlassian.net/wiki/spaces/CC/pages/1764491265/Resources)
   - [FAQ](https://vfs.atlassian.net/wiki/spaces/CC/pages/1864073263/Collaboration+Cycle+FAQ)
   - [Contact Us](https://vfs.atlassian.net/wiki/spaces/CC/pages/1764524036/Contact+us)
   - [Calendly link](https://calendly.com/platform-office-hours/collaboration-cycle?back=1&month=2023-06&date=2023-06-07) (change join to sign up)

## Tasks
- [ ] Delete Slack reminder on #vfs-platform-support channel
   - Shira may have to help with this since she set it up
- [x] Delete Collaboration Cycle office hours from the Collaboration Cycle Calendar
- [x] Reach out to Governance team to determine what should be included in the Calendly sign up
   - Topic and Impacted practice area were previously discussed
- [x] once confirmed, connect with Shira and/or Allison to make the modifications to Calendly
- [x] Update Platform Website:
   - Resources
   - FAQ
   - Contact Us
   - [Calendly link](https://calendly.com/platform-office-hours/collaboration-cycle?back=1&month=2023-06&date=2023-06-07) (change join to sign up)

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] VFS team members sign up for Collaboration Cycle office hours when interested in attending
- [ ] Governance team members are notified of VFS team member attendance at Office hours at least 30 minutes prior to the office hours event. 

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
[Link to Slack thread](https://dsva.slack.com/archives/GNF5GSD9N/p1685453448974169) asking the team about which practice area attendees want to talk to.

**Comment by shiragoodman** [comment]
> @shiragoodman for the first task...
> 
> * Delete Slack reminder on #vfs-platform-support channel
> * Shira may have to help with this since she set it up
> 
> I do not think we want to delete it. We still want to make it easy for people to attend. For design, I post it on Tuesday at 11am EST and office hours are at 3:00pm EST. This give people time to sign up that day if they want. We cut to the sign ups off at 2:30pm EST.
> 
> What do you think about changing this reminder to post at 10:00am EST and then cutting it off at 11:am EST? I know that is early for Pacific time but it will be there when they log on so they can sign up if they want.

We can change it, however my reason for deleting it is because it has a direct Zoom link. So we'll want to remove that and potentially change when it's pushed.

**Comment by allison0034** [comment]
Per this [slack discussion](https://dsva.slack.com/archives/GNF5GSD9N/p1685453448974169), we will gather practice area info when people sign up for office hours, however I think we need to check the data after each meeting to confirm the attendees selected the right practice areas.

**Comment by shiragoodman** [comment]
Changes made to the #vfs-platform-support reminder can be tracked via [this Slack post ](https://dsva.slack.com/archives/GNF5GSD9N/p1685988764217399)

**Comment by allison0034** [comment]
Verified the changes went in the recent content update.
