### ISSUE TITLE
File upload | Add confirmation modal when removing files

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#58596]
## Value Statement
**_As a_** Veteran that has uploaded files into a form
**_I want to_** see a confirmation to remove a file
**_So that_** I don't accidentally remove an upload

---
## Background Context

Prior to release of our team's Supplemental Claims form, the collaboration cycle mentioned that this [confirmation of a destructive action](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56082) was missing in several pages of our form. One of which was the removing of uploaded files.

## Acceptance Criteria
- [ ] All tasks complete
- [ ] All tests passing
- [ ] User will see a confirmation prior to removing an already uploaded file

## Designs and Build Notes
- [Design System ticket #1770](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1770)
- [SKETCH Screen](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/a/ZVOkEAv)

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] Include an approved design
- [ ] Add confirmation action prior to removing an already uploaded file
- [ ] Unit tests updated
- [ ] e2e tests updated

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
@Mottie @saderagsdale Design was already created when we did it for Supplemental Claims. I added it into the Design & Build notes. It should carry over for upload file removals.

**Comment by saderagsdale** [comment]
@Mottie Was this done already? in the individual tickets you and rocio completed?

**Comment by Mottie** [comment]
This has not yet been done. This work would change platform code.

**Comment by Mottie** [comment]
Changes merged in. These changes will work for both Supplemental Claims & Notice of Disagreement.

**Comment by eileen-coforma** [comment]
@Mottie I found a bug for Supplemental Claims. Not sure if it's linked to this update. If it isn't, I can open a new ticket for it.

In SC, when you hit edit in the issue summary page, the focus now jumps to 'upload another file' instead of the dropdown for the document type.

**Comment by saderagsdale** [comment]
@eileen-coforma If the scope of this ticket works as expected we can close it and make a separate bug ticket.

**Comment by eileen-coforma** [comment]
Then we can close this. I'll make a separate bug ticket.

**Comment by Mottie** [comment]
Focus bug has been implemented. Please test in staging at your convenience
