### ISSUE TITLE
Make clearer when an evidence request is for the veteran.

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#58594]
## Value Statement
**_As a_** veteran with a disability claim
**_I want to_** to be able to clearly identify the tasks that are for me to do pertaining to evidence requests
**_So that_** I make sure I action on those requests.

---
## Background Context
- Add here

## Design concept

[Sketch file](https://www.sketch.com/s/98e35645-34eb-40cf-80c1-6c4952943584/p/B9C46ABC-36AD-4CA8-9896-55762FC6912E/canvas)

This work relates to the "What you need to do" section of the Status tab. 

<img width="475" alt="Screenshot 2023-11-01 at 5 06 31 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/823666e5-bd5f-42d9-9b51-cd2ad4a9ee7f">

## Acceptance Criteria
- [ ] There is a clear indicator when an open request is for the veteran
- [ ] Open requests for the veteran are made the most salient requests
- [ ] Requests are are sorted so that priority goes to open requests; secondary priority is to sort by reverse chronological order

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jerekshoe** [comment]
@jacobworrell can you put a sketch link in the description of this ticket?
