### ISSUE TITLE
Evidence requests are easier to find

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#58603]
## Value Statement
**_As a_** veteran with an open disability claim
**_I want to_** be able to easily notice open evidence requests in the claims list view
**_So that_**  I can take action on them

---
## Background Context
- Add here

## Acceptance Criteria
- [ ] Open evidence requests are easy to find in list view
- [ ] The link between evidence request and the claim it's for is obvious
- [ ] Evidence requests provide an on ramp to action on those requests
- [ ] Claims are sorted so that the claim with the most recent request rises to the top

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kjduensing** [comment]
Algorithm is to:
1. Sort the entire list by lastUpdated
2. Find all the claims with open requests, preserving sorted order
3. Concatenate the rest of the list (claims w/o open requests, appeals) to the open request group
4. Result will be: all claims with open requests will be sorted and grouped at the top, followed by claims without open requests and appeals and stem claims below.

Gotchas:
- Claims without `documentsNeeded` will always appear lower in the list than claims with `documentsNeeded`, even if the claim without `documentsNeeded` was updated more recently.
