### ISSUE TITLE
Update Offboarding doc to include Test Rail check

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#58611]
### Summary
Test Rail is a tool we, on the Platform, add members to, but we never remove them! The [offboarding document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/offboarding-request.md) needs to be modified to include a checkbox to check TestRail and link to documentation that explains how to remove a user. We also need to go back and remove users that have left but we're never offboarded from TestRail.

### Tasks
- [x] Update [offboarding document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/offboarding-request.md) (below Sentry, above Google Analytics)
- [x] Add steps to [the Confluence documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/2097545323/Offboard+Team+Member).
- [x] go through current test rail users, and remove anyone no longer in the org (you can check if they've been deactivated from Slack)

### Acceptance criteria
- [x] changes to offboarding template are merged.
- [x] steps have been added to confluence documentation
- [x] users no longer in the org have been removed from TestRail

**Comment by bdech** [comment]
Created PR request to update offboarding template to include TestRail

https://github.com/department-of-veterans-affairs/va.gov-team/pull/63558

**Comment by bdech** [comment]
Offboarding Confluence doc has been updated with steps to remove users from TestRail access
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcllGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--74f38f0375a51ab8920b42acc41ff7a113b8f531/image.png)

**Comment by bdech** [comment]
Instead of completely removing inactive users, we will be removing the check 'This user is active'. This way it will free up the license but also keep any historical data intact.
