### ISSUE TITLE
CANCELED**ICN lookup route

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#58612]
## Issue Description
For ease of use an ICN lookup route that only requires a user's ICN and the query start/end dates should be created

---
## Tasks
- [ ] create frontend ICN lookup form
- [ ] create backend ICN lookup route
- [ ] connect lookup form to route
