### ISSUE TITLE
Platform | Add centralized inline contact info page for forms

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#58638]
## Value Statement
**_As a_** developer
**_I want to_** a simple, centralized method connected to profile data to include in forms
**_So that_** adding and updating contact info pages linked to profile is quick and easy to do

---
## Background Context

Similar code is being used for profile-connected contact info pages in 5 apps outside of the profile app (10182, 995, 996, FSR & Letters). In order to centralize and simplify adding profile-connected contact info pages, the code will be modified and moved into the form system. Documentation will also be updated.

## Acceptance Criteria
- [ ] All tasks complete
- [ ] All tests passing
- [ ] User will get a similar experience when being asked for their contact info 

## Designs and Build Notes
- [Supplemental Claim contact info DESIGN](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/p/14726A84-8E51-4285-B64D-2100694C5CB3/canvas)
- Differences from previous implementations:
  - Add successful update alert
  - Focus management includes focusing on the update alert when a change is made, and focus on the edit link when the edit is canceled
  - Implement editing contact info from the review & submit page - go to edit page & return to review & submit page
- Add analytics events for update & cancel clicks

## Tasks
- [ ] Add profile-connected contact info pages code to form system
- [ ] Check success update alert & focus management
- [ ] Implement editing from review & submit page
- [ ] Add analytics
- [ ] Unit tests updated
- [ ] e2e tests updated

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
Work implemented and testable on [staging.va.gov/mock-form](https://staging.va.gov/mock-form/).
