### ISSUE TITLE
Establish the design intent of IPP

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#58658]
After reviewing the progress on our service blueprint and analogous research, we discovered that we need to perform desk research to inform the design intent. We will do desk research to answer the following questions:

- what kinds of populations will this service be for? (veterans and identity verifiers)
- what are some analogous projects that have had success with implementing in person processes? what can be learned from them?
- What do we need to prioritize in our pilot and how can we scale this over time?
- how can we better understand the patient experience at the VAMC?
- what are some technical considerations we need to be aware of? (i.e. who has the authority to mandate IPP training and how is this done)

Once the design intent has been established, we can finalize our product outline and further develop our service blueprint

## Acceptance Criteria
- [ ] Design intent has been established

## Tasks
- [ ] @skirkman16 Perform desk research through the [repository ](https://github.com/orgs/department-of-veterans-affairs/projects/880/views/1?layout=board)and summarize the findings in the [service design Mural](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1682452070019/4a1256564f6f5ca86610f17b325c4134fc654b3c?sender=u99cd1ac4f5c240d8dffd4204)
- [ ] @skirkman16 synthesize findings, discover patterns and prioritize patterns
- [ ] @MOStudioCarolyn investigate veteran experience flows from [Patient Experience Journey Map](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/design/va-product-journey-maps/Patient%20Experience%20Journey%20Map.pdf) and [kickoff Mural](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1679677574832/5b4e2a904a2e79ffeb177855af818085fc270d17?sender=u99cd1ac4f5c240d8dffd4204)
- [ ] @MOStudioCarolyn investigate tech fluency issues and share findings
- [ ] @alevindecanini Gather more information on Identity Verifiers and Toolkit through John and MHV
- [ ]  @alevindecanini Set up a meeting to finalize the design intent
