### ISSUE TITLE
Competitive analysis on how other orgs have approached form digitization

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#58674]
## Purpose
Ours is not the first large organization to try to move from paper-based forms to digital ones.  What has been learned, and what can we adopt?

[Main text](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2639036425/Form+digitization+competitive+analysis+link+capture)

## Tasks
- [x] Research and review similar scenarios
- [x] What were things to be incorporated?  what worked well?
- [x] What were things to be avoided?

## Acceptance Criteria
- [x] Idea board broken into sections mentioned above

**Comment by twoangstroms** [comment]
This will carry over to next sprint as a continuous research document

**Comment by twoangstroms** [comment]
Added [child page for no-code and code form builders](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2662170793/No-code+and+code+form+builders)

**Comment by twoangstroms** [comment]
[Confluence page](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2639036425/Form+digitization+competitive+analysis+link+capture) is ready for review
