### ISSUE TITLE
Login.gov adoption team: Sprint 21 (5/24 - 6/7)

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#58677]
## PTO
- Memorial Day 5/29
- Tyler 5/25-26

## Sprint 21 Goals
**Building comms infrastructure:**
- Dashboard: Automating feed from SSOe
- Dashboard: Design for v2.0 that better addresses KPIs & comms
- Reactivation: Build proof of concept
- Collaboration cycle touchpoints for Organic Adoption & Reactivation
- Release campaign landing page containing messaging that aligns with Sitewide & MHV requirements.

## Sprint 21 Tasks

**Dashboard**
 - [x] Complete 55960 SSOe Access Log Automation Script Work #58300
 - [ ] Design for v2.0 that better addresses KPIs & comms #59101

**Reactivation proof of concept**
 - [x] Research campaign platforms #59070
 - [x] Technical design/architecture of proof of concept #59071
 - [x] Assess the test user's eligibility #59074
 - [ ] Send the appropriate email to the test user based on their eligibility #59073
 - [ ] ~~Visualize data about the campaign in Domo #59072~~ (Decided not to use Domo)
 
**Comms strategy**
 - [x] Let collaboration cycle know about our shift from a modal to email #59100

 - [x] Publish campaign Landing Page #59114
 
## Retro Board

[Sprint 20 Retro] (#)

## Discussion Topics/Retro Action Items
 - [ ] TBD

## Collab Cycle Tasks 
 - [ ] TBD

-----

## Future Sprint Goals (deferring for now)
- Reactivation: Test in staging
- Reactivation & Organic Adoption: Get PO & privacy officer approvals for email campaign content & design
- Dashboard: Set up infrastructure to fully automate feeds from MPI & SSOe (Dependency on SNO ticket)
- IPP: Kick off collab cycle with design intent meeting
- Creating Product Guides per Support plan & [templates](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md)

**Tasks we're deferring for now**
 - [ ] Creating Product Guides per Support plan & templates #59102
