### ISSUE TITLE
[FSR] Form restart flag bug

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#58681]
## Issue Description
Noticed `isStartingOver` was never getting reset to false if restart was triggered multiple times in the same session. Found `startingOver` flag being set in the `SET_SAVE_FORM_STATUS` reducer that isn't referenced anywhere else except a test. Thinking this is just a minor naming bug. 

This variable being reset should fix edge cases of veterans ending up in the 'old experience'!

---
## Tasks
- [x] Update platform component to reset isStartingOver variable appropriately 
- [x] Update FSR App to account for the change!

## Acceptance Criteria
- [x] No matter how many times the form is restarted the feature flags are properly fetched. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
[PR didn't link correctly, but here's the fix](https://github.com/department-of-veterans-affairs/vets-website/pull/24271)
