### ISSUE TITLE
Add note to VHIC page to avoid duplicate requests

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#58698]
## Issue Description
Keith and Kim from VHIC asked us to add a note on the VHIC page to tell Veterans not to request cards online and in person—this causes delays and confusion in the issuing process.

---
## Tasks
- [ ] Add note {Laura)
- [ ] Send to partners (Laura)
- [ ] Copyedit & publish (Megan)

## Acceptance Criteria
- [ ] Note is live on page

**Comment by laurwill** [comment]
I added a note to the "how to" section and sent it to partners to approve

**Comment by RLHecht** [comment]
Moving to blocked while waiting on stakeholders

**Comment by laurwill** [comment]
Yes, I'll follow up via email now.

**Comment by coforma-terry** [comment]
Will re ping

**Comment by laurwill** [comment]
Pinged! Partners responded that they're reviewing and will get back to us.

**Comment by laurwill** [comment]
Partners approved — I went ahead and published this because it was very small and I had someone check before I sent the original (either Randi or Megan). @strelichl we can close out!
