### ISSUE TITLE
Board Appeal | Setup radio button tracking

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#58705]
## Value Statement
**_As a_** researcher
**_I want to_** track the radio buttons on the Board Appeal digital form
**_So that_** the team can have a clearer picture of what decisions Veterans are making on the form

---
## Background Context

I made a request earlier to Analytics to see if radio buttons are automatically tracked for our forms since it's a design component, and Michelle mentioned that they were not, and that we need an extra layer of code to track them.
Original ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/57206

## Acceptance Criteria
- [ ] Analytics can see the tracking code from the pages listed
- [ ] Tracking appears in GA

## Designs and Build Notes
Here is the data layer code to use:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/93597659/63508e18-a4e1-4904-b4fe-7c932b181ed3)

## Tasks
- [x] Add data layer code to: https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/board-review-option
- [x] Add data layer code to: https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/evidence-submission
- [x] Add data layer code to: https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/hearing-type
- [ ] Comment Michelle Dooley in attached dependency ticket to confirm when our work is done

---
## Definition of Ready 
- [ ] We know which are web components vs. React components
- [ ] Properties added to each web component to enable it are identified

## Definition of Done
- [ ] Properties added to each web component to enable it
- [ ] Confirmed done by Michelle Dooley

**Comment by saderagsdale** [comment]
@eileen-coforma I think you need to use [this](https://github.com/department-of-veterans-affairs/va.gov-team/issues/58800) template for the GA change you want to request. Can you add the details there and ping me when it's done?

**Comment by eileen-coforma** [comment]
@saderagsdale I already added the analytics ticket, as linked in the body: https://github.com/department-of-veterans-affairs/va.gov-team/issues/57206

Michelle came back to us and said our front end needs to add the layer of code, before she can check for it in GA.

**Comment by saderagsdale** [comment]
@eileen-coforma Thanks. In the future, you can link #57206 as a dependency so others in the backlog can spot it easily. I did it for you this time.

**Comment by Mottie** [comment]
This work is done and ready for testing in staging

**Comment by eileen-coforma** [comment]
I pinged Michelle about it. Just need confirmation from her.

**Comment by eileen-coforma** [comment]
I see it in GA already, we can close this.
