### ISSUE TITLE
STEM: Request accessibility/508 review

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#5870]
## Team Name
BAH

## Product Description
The Education Benefit Wizard and 22-1995 form have been updated to better reflect the eligibility requirements for the Edith Rogers STEM Scholarship so that fewer ineligible Veterans spend time apply for the program. The goal of this effort is to reduce the large number of rejections that are processed on an ongoing basis. 

## Staging URL and Credentials

https://www.va.gov/education/how-to-apply/
https://www.va.gov/education/apply-for-education-benefits/application/1995

## Test Plan

Wizard Test Plan: 
[STEM Wizard Accessibility Test - TestRail.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4262401/STEM.Wizard.Accessibility.Test.-.TestRail.pdf)
[https://app.zenhub.com/files/133843125/280c49ca-f219-453f-a4e4-4ebec2b10195/download](https://app.zenhub.com/files/133843125/280c49ca-f219-453f-a4e4-4ebec2b10195/download)

## Known Issues
https://github.com/department-of-veterans-affairs/va.gov-team/issues/6290
https://github.com/department-of-veterans-affairs/va.gov-team/issues/6280
https://github.com/department-of-veterans-affairs/va.gov-team/issues/6285

**Comment by desireeturner** [comment]
@1Copenut We are ready for the Accesibility Review of the functionality described above. Please let myself or @WillMcCormack know if you have any questions. Note that I will be out on Tuesady and Wednesday, so @WillMcCormack will be able to get you a faster response those days.

**Comment by 1Copenut** [comment]
@desireeturner Thank you for the heads up. I'll get this on the docket for this week.

**Comment by 1Copenut** [comment]
@WillMcCormack && @desireeturner I'm going to make this issue an epic so we can house any accessibility findings inside it. Won't change anything, but makes it able to collect issues in Zenhub.

**Comment by 1Copenut** [comment]
@WillMcCormack && @desireeturner Making this an epic to capture any accessibility findings (including those by your QA team) for easy visibility.

**Comment by 1Copenut** [comment]
## VSP Staging Review Happy Path Testing:
* [ ] axe checks
* [ ] keyboard navigation
* [ ] zoom to 400%
* [ ] VoiceOver + Safari (MacOS)
* [ ] NVDA + Firefox/Chrome (Win10)
* [ ] JAWS + IE11/Chrome (Win10)

**Comment by 1Copenut** [comment]
@WillMcCormack && @desireeturner I've completed the Staging review happy path accessibility review. Let me know when this is in production and I'll run a deep dive audit and let the VA 508 office know it's ready for their review as well. Thank you for sending the Test Rail cases and your QA accessibility testing. They made the review go smoothly.

**Comment by WillMcCormack** [comment]
@1Copenut thank you for the quick turn around on your review! We will work with the customer to prioritize #6545 post-launch.

**Comment by WillMcCormack** [comment]
@1Copenut can we close this issue out and open another once everything is in production? Or would you prefer to track everything on this ticket?

**Comment by WillMcCormack** [comment]
@1Copenut can we move forward with closing this issue?

**Comment by 1Copenut** [comment]
@WillMcCormack Yes, we can close this one and let's open a new one for the post-launch full audit.
