### ISSUE TITLE
[CST] Migrate AddFilesForm to web components

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#58713]
## Background
The design team is deprecating the react components in favor of their web component counterparts and have added eslint errors for a few of the ones used in the AddFilesForm component, specifically:
* `FileInput`
* `Select`
These need to be migrated before we can make any more changes to the `AddFilesForm` component

## Considerations
Since both of these components have event handlers, we will need to use the `react-bindings` variant of the web-components i.e. `VaSelect` and `VaFileInput`

## Tasks
- [ ] Update the `AddFilesForm` component to use the `va-select` component
- [ ] Update the `AddFilesForm` component to use the `va-file-input` component

## Acceptance Criteria
- [ ] React component in the `AddFilesForm` component are migrated to web-components
- [ ] We no longer get linting errors when updating the `AddFilesForm.jsx` file
