### ISSUE TITLE
Monitor survey entries

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#58733]
## Issue Description
The survey is live and will be open to feedback. We need to know if people are filling it out.

Login URL: https://app.optimalworkshop.com/login

---
## Tasks
- [x] Log into Optimal Workshop to review any new survey entries
- [x] Update the team on # of survey entries every other day
- [x] If needed, share with team anything that stands out from the survey entries

## Acceptance Criteria
- [x] We have an understanding of the # of surveys being completed on an ongoing basis
