### ISSUE TITLE
Kickoff meeting w/ PO for Forms Digitization research

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#58741]
## Purpose
Let's meet w/ Matt to get a solid sense of what the scope of this endeavor can and should be.

Notes:  https://vfs.atlassian.net/wiki/spaces/SDT/pages/2606563408/VFS+Form+Digitization+Effort+-+discussion+notes

## Tasks
- [x] Schedule Meeting (5/31/23 @ 2pm ET)
- [x] Meet to [discuss](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2649325585/Meet+w+Matt+to+learn+space+asks+for+Research) research initiative

## Acceptance Criteria
- [x] Initial discussion conducted, establishing initial sense of scope and direction
