### ISSUE TITLE
Design for return URL with the new 526 flow

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#58744]
## Issue Description
For the first pass of 526 online form with the latest paper form, we are moving and removing pages (see #56920, #56348). With the save in progress flow, we need to decide where the user should return to when a page has moved to a different chapter or has been removed.

##Need to know
Sketch file with flow changes: https://sketch.com/s/c3ee9ba8-f268-46dc-a870-194e99bed37e

## Tasks
- [x] Create concept(s) for user returns, based on where the user exited the form

## Acceptance Criteria
- [x] Proposal for where the user should be brought back to in the returning session after the flow has changed as part of 526 sync with paper version.
- [ ] A ticket is created for the IA team for review 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
cc @lydiahooper @christinec-fftc

**Comment by lydiahooper** [comment]
Initial concept is:
- For those users who have not proceeded past contact info pages in chapter 1, return as normal 
- For those users who have proceeded all the way to "Are you a VA employee" in chapter 4, return as normal
- For all other users, return to relocated housing situation page in chapter 1

I plan to share this with Shannon Ford on Tues May 30.

**Comment by christinec-fftc** [comment]
@lydiahooper @RakshindaAslam One other question I had was for the pages we are removing - namely adaptive-benefits, aid-and-attendance, fully-developed-claim, additional-disability-benefits - do we want to take any action if a user has this data saved with their in progress form? e.g. Should we still include that data when they submit or remove it?

**Comment by lydiahooper** [comment]
Spoke with Matt Self and Shannon Ford on May 30 and we made these decisions:
- Place returning users in flow as I proposed in previous comment
- Hold off on moving the additional benefits screens until we are ready to implement the new submission experience as well (like we decided for bank account pages)
