### ISSUE TITLE
Tech Discovery - Fix 4142 embedded in 526 flow

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#58753]
## Issue Description
When a user selects that they want VA to review private medical evidence on this page, they need to sign digital version of Form 4142/4142a to authorize release of this information. Currently, they bypass signing this if they say they want to upload records themselves. We need to design a better experience to make sure the veteran isn't waiting for VA to send and receive this form to them to have their claim processed.

The form has been digitized (in QA, and waiting IA as of May 8, 2023), so we can design how to embed in 526. Note, no research was done for this, so we might want to consider that.
Link to in staging: https://staging.va.gov/health-care/medical-release-form
MURAL board with user flows: https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1679331618997/29ef67d11247a32cdc7a12a7c48c5b07941820c0?sender=u2905941a69b3083a009c9997

[Slack thread ](https://dsva.slack.com/archives/C044AGZFG2W/p1683575311400649)

Sketch file showing proposed changes: https://sketch.com/s/6ee257e1-d7b5-4879-9110-d083b0383d20

The scope of this ticket is to understand:
- Does the current 526 create a 4142 pdf in the efolder (there are two ways to do this, one is through user entering data in 526, another is to upload 4142 on a different screen)
- For the changes being recommended in the flow, what kind of eng changes would be required to ensure that the pdf is generated correctly and placed in the efolder

---
## Tasks
- [ ] 

## Acceptance Criteria
- [x] We believe the current 526 creates a 4142 pdf in the efolder when the user enters something in the form (not through a file upload)- Matt and Shannon said yes. Can any of this be reused for the new flow? _**Confirmed. Yes, 526 goes through a whole process of generating a 4142 PDF on behalf of the Veteran and sends it to the e-folder. More information in the "Discovery Details" section below.**_
- [x] Do we need any external support to implement these changes? (post submission) _**Maybe. We need to make changes to the vets-json-schema repository to allow for new fields in the 526 schema: https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/dist/21-526EZ-ALLCLAIMS-schema.json#L1315. More information in the "Discovery Details" section below.**_
- [x] Can we use the digitized 4142 form for this work?  (stand-alone implementation) _**Short answer: Kind of. We think there may be opportunity for creating reusable components, sharing with the standalone 4142, but we need to take the time to figure out how this will work or if it is feasible. This discovery we moved to another ticket #60878.**_
- [x] For the changes being recommended in the flow, what kind of eng changes would be required to ensure that the pdf is generated correctly and placed in the efolder _**From the back-end's perspective, the only added thing here is in the Provider Information section where it asks "Conditions you are being treated for". We would need to modify the validation json schema (mentioned above) to 1. add conditionsTreated to providerFacility block and 2. add conditionsTreated to required fields.**_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
- [ ] 

---
## Discovery details
1. TL;DR:  526 creates a 4142 PDF and sends it to the efolder as a part of the submission job workflow.
Generating a 4142 PDF is based off of the template in the form. There are some processors that get the data ready to be converted into PDF format.
The 526 form already handles the processing and generating of the PDF from the form information provided. Through investigation, it is apparent that we do not need to do anything else to this process to get it working for form 526 as it already is working!

This diagram illustrates two known ways form 4142 gets generated in vets-api. The green paths in this diagram are the 526 submission workflow.
![BDex Diagrams - #58753 - form 4142 discovery.jpeg](https://images.zenhubusercontent.com/5c1047425e37320ceee743c3/60ca6c70-7a34-483e-843d-3d3f7ca74a30)

There is some overlap between a couple of "Processors" that are specific to 4142 that may do the same thing, but this is not crucial to consolidate as a part of this work, though it would be nice to consolidate some confusion!

2. We need to add some additional information to the json schema validation library to support a new-to-form-526-version-of-4142-field: "Conditions you are being treated for". 
-- 1. We need to add `conditionsTreated` to the `form4142` `providerFacility` block in the json schema
-- 2. We need to add the `conditionsTreated` to the `form4142` `providerFacility` `required` block.
This work would be done in this repository: https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/dist/21-526EZ-ALLCLAIMS-schema.json#L1315.
This looks relatively simple, but we have not done this before. 

![BDex Diagrams - #58753 - form 4142 discovery (1).jpeg](https://images.zenhubusercontent.com/5c1047425e37320ceee743c3/ac4fb6bc-dcfb-4c7e-92e3-cb108ad10049)

**Comment by RakshindaAslam** [comment]
@RakshindaAslam - create an epic for 4142 changes
