### ISSUE TITLE
[PM] Onsite Notifications v2: Product guide updates + call center submission

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#58774]
## Background
We need to update the product guide with information about new onsite notification(s) that users may see on My VA.

## Tasks
- [ ] Update call center guide with details of new notification(s) (content and screenshots)
- [ ] Submit to [call center ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jwoodman5%2C+kimberley2019&labels=contact+center%2C+collaboration+cycle%2C+collab-cycle-review&template=request-contact-center-review-template.md&title=Contact+Center+Review+for+%5BTeam+Name+-+Feature+Name%5D) with product guide
- [ ] Once approved update the product guides versioning documentation found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/product/product-guides.md).

## Acceptance Criteria
- [ ] Call center guide is updated with notification(s) info and final version is stored in our team documentation

**Comment by ajakabcin** [comment]
Closing out - this work was paused indefinitely
