### ISSUE TITLE
[PM] Notification Component: Prep for and submit PSIR Review

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#58779]
## Background
We need to prep for and submit our privacy and security review for the new notification component.

## Tasks
- [x] Compile documentation outlined [here](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/privacy-security-infrastructure-readiness-review)
- [x] Submit [ticket](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/new?assignees=td-usds%2C+troymosher&labels=security-review&template=privacy-and-security-review.md&title=Readiness+Review+%5BTeam-Name%2C+Feature-Name%5D)
- [ ] Complete any follow up tasks

## Acceptance Criteria
- [x] Documentation prepped, ticket submitted

**Comment by ajakabcin** [comment]
Ticket submitted - [1000](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1000)

**Comment by ajakabcin** [comment]
[approved](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1000)
