### ISSUE TITLE
Add launch-blocking filter to relevant dashboard graphs

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#58781]
## User Story
As an OCTO-DE leader, I want to better understand what portion of all staging-review issues are considered launch-blocking, so that I can better understand the overall severity and distribution of issue tickets.

Assignee:
Peer Reviewer:

## Description
In ticket #56641 we presented a set proposed improvements to the current Collaboration Cycle Domo dashboard based on OCTO-DE feedback via survey. This ticket addresses OCTO feedback regarding a request to be able to filter between regular issue tickets and launch-blocking issues. It is worth considering whether or not the ability to identify launch-blocking issues would also be beneficial on other existing graphs on the dashboard. 

### Analysis from research readout
* **Anticipated Level of Effort (LoE):** low
* **New graph needed?** No, edits to existing graph

## Impacted Artifacts
* [Collab cycle Domo dashboard](https://va-gov.domo.com/page/1340527018)

## Tasks
- [ ] Ensure that the launch-blocking label is coming through in BigQuery dataset (if not, connect with the Analytics team during their office hours)
- [ ] Build out a filter-feature for _Graph 1: How long does it take to resolve staging review issue tickets?_ to be able to filter on the `launch-blocking `label
- [ ] Evaluate whether the ability to filter on the launch-blocking label would be valuable for other existing graphs. If there is consensus around this, then 
- [ ] Add the filter to other relevant graphs (if applicable)

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Dashboard users can filter issue-tickets by the` launch-blocking ` label

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer
