### ISSUE TITLE
Update dashboard to reflect how data is trending over time

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#58787]
## User Story
As an OCTO-DE leader, I want to be able to see a line graph that combines issue-based data with date-based data so that I can start to understand how things are trending over time.

Assignee:
Peer Reviewer:

## Description
In ticket #56641 we presented a set proposed improvements to the current Collaboration Cycle Domo dashboard based on OCTO-DE feedback via survey. This ticket addresses OCTO feedback requests to better understand how data is trending (in a positive or negative direction) and changing over time. The idea for this ticket is to create a new line graph that combines data from the current graph 1 (time it takes to close issues) and graph 2 (frequency of experience standard violations). That line graph would chart out moment-in-time data so that we can see spikes in issue frequency. This would allow leadership to see identify recent problems and improve documentation/guidance around those specific issues. We could then track whether the documentation leads to a decrease in the frequency of those issues.

Our tickets only have dates for when they were open and closed, but we should be able to display the count of how many experience standard violations were open at any given day/week/month. This ticket will require some exploration and a new graph will take some iteration/edits since it represents a lot of data. 

This work is related to ticket #58784 (also in this initiative) which adds drop-down filter functionality by date. While that work adds a date-range as a filter for users who select it, it doesn't necessarily display trends over time (not all Domo cards are configured as line graphs that would get at this). This ticket will introduce a new line graph that displays those trends upfront.

### Analysis from research readout
* **Anticipated level of effort (LoE):** high
* **New graph needed?** Yes

## Impacted Artifacts
* [Collab cycle Domo dashboard](https://va-gov.domo.com/page/1340527018)

## Tasks
- [ ] Build out a new Domo card that combines metrics for graphs 1 & 2 (experience standards according to time they take to close)
- [ ] Tweak this card and solution over the display
- [ ] Check with OCTO-DE practice-area leads to see if this new graph better accomplishes the need to see trends over time

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Dashboard users have the ability to see trends over time in the violation of experience standards and identify which issues are the biggest hurdles for teams

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer
