### ISSUE TITLE
Add date-range filter to all existing dashboard graphs

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#58784]
## User Story
As an OCTO-DE leader, I want to be able to filter graphs by date-range so that I can understand the significance of issues (and issue categories) based on a narrower window than "all time." 

Assignee:
Peer Reviewer:

## Description
In ticket #56641 we presented a set proposed improvements to the current Collaboration Cycle Domo dashboard based on OCTO-DE feedback via survey. This ticket addresses OCTO feedback requests to better understand how data is trending (in a positive or negative direction) and changing over time. Our tickets only have dates for open and closed, but we should be able to add a drop-down filter feature to each graph with time-ranges (e.g. last 3 months, 6 months, 12 months, over 12 months). 

### Analysis from research readout
* **Anticipated Level of Effort (LoE):** medium
* **New graph needed?** No, edit existing graphs

## Impacted Artifacts
* [Collab cycle Domo dashboard](https://va-gov.domo.com/page/1340527018)

## Tasks
- [ ] Consider what time frames make the most sense for dividing out data (3, 6, 9, 12 months? something else?) 
- [ ] Add a date-range filter to all graphs

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Dashboard users can filter issue-tickets by date range

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
design determined in ticket #59621. This ticket is no longer necessary.
