### ISSUE TITLE
Design wireframes for revised 4142

### ISSUE THREAD

**Issue by lydiahooper** [department-of-veterans-affairs/va.gov-team#58793]
##Issue Description
When a user selects that they want VA to review private medical evidence, they are forced to select either that they want to upload evidence themselves, or they want VA to get records, but they may want to choose both. Also, for users that choose to upload records themselves, they may be confused by the option to upload a 4142 PDF (which is NOT required for vets that choose to only upload evidence themselves). And there are two relevant pages in 526 currently using the deprecated wizard component, which presents accessibility problems.

Also factor in language that sets expectations for evidence/documents needed (based on intro page research if possible) including for presumptive claims (see notes from discussion with VBA on Apr 4 2023)

This work will NOT be going through collab cycle

## Need to know
Prior ticket: https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/57876
Sketch file showing proposed changes: https://sketch.com/s/6ee257e1-d7b5-4879-9110-d083b0383d20

This work runs alongside tech discovery: https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/58753
New URL for standalone: https://staging.va.gov/supporting-forms-for-claims/release-information-to-va-form-21-4142/introduction

Note this ticket from BDD SHA staging to address issues on these pages: https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/59257

Bug/issue ticket relevant to this redesign: https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/59617

## Tasks
- [x] If needed, ask questions to VBA in order to write content
- [x] Write content for new pages
- [x] Create wireframes or annotated screenshots for 7 screens (including any notes on error states)

## Acceptance Criteria
- [x] Wireframes or annotated screenshots
- [x] Create ticket for content review, if needed

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lydiahooper** [comment]
Google doc where drafting revised content for 4142 pages: https://docs.google.com/document/d/1F-vsSeEqWWlwDidOkcJ3d8_FaOXZgpG163qj1OUTiMU/edit?usp=sharing

**Comment by lydiahooper** [comment]
See user interfaces page on Sketch file for completed wireframe mockups: https://sketch.com/s/6ee257e1-d7b5-4879-9110-d083b0383d20
