### ISSUE TITLE
 AVS MVP Wireframes May, 2023 Usability Test Data Synthesis

### ISSUE THREAD

**Issue by ninaranusavice** [department-of-veterans-affairs/va.gov-team#58806]
# Description
Usability testing with Veterans of AVS MVP Hi-Fi wireframes is set to take place on June 14-21, 2023. After testing is complete, the raw data from the sessions will be synthesized into findings.

# Task
- [x] Download transcript of each session.
- [x] Create [Mural ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687528329546/32dfa4302787c500e34c4ec8927416e6c778d362?sender=u7c471a43344939c759cb1640)for participant quotes and common themes.
- [x] Meet with team to synthesize findings.

# Acceptance Criteria
- [x] Complete synthesis Mural, so you are ready to start the research report.
- [x] Consensus reached on common themes and final findings.
