### ISSUE TITLE
[bug] Supplemental Claims | Combine duplicate VA requests

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#58804]
## Value Statement
**_As a_** Veteran with multiple VA location evidence requests
**_I want to_** be confident that my form is submitted
**_So that_** I don't accidentally delete info from the form. 

---
## Background Context

Our Supplemental Claims form asks the Veteran to include the issue that was treated for each location. If a Veteran adds the same location and same treatment dates for multiple entries, but selects different treated issues, these entries are considered to be unique; but once the form is submitted, the treated issues are not included (they are not on the form, but asked in the online form to keep the UI consistent), and thus the entries may no longer be unique - same location & dates.

To fix this problem, we plan to combine entries with the same location & dates (ignoring treated issues) so that Lighthouse doesn't reject the submission

## Tasks
- [ ] Ensure unique VA locations & dates are submitted
- [ ] Add unit & e2e tests

## Acceptance Criteria
- [ ] Duplicate VA locations & dates are combined prior to submission
- [ ] All tasks complete
- [ ] All tests passing

**Comment by saderagsdale** [comment]
@Mottie @kylesoskin Do we need to confirm with Lighthouse is this is the right solution?

**Comment by kylesoskin** [comment]
We can loop them in for the longer term strategy and goals around treatment centers/treatment dates/treatment conditions, but for now, none of that really is important. There is an issue preventing (2 thus far, potentially more) users from submitting, and to quickly remedy, the easiest thing to do is just combine the ones that are the same.

Combining them does not materially change the submission. 

For example instead of submitting:

```
[
  {
    "type": "retrievalEvidence",
    "attributes": {
      "locationAndName": "VAMC Location",
      "evidenceDates": [
        {
          "startDate": "2001-01-01",
          "endDate": "2011-01-01"
        }
      ]
    }
  },
  {
    "type": "retrievalEvidence",
    "attributes": {
      "locationAndName": "VAMC Location",
      "evidenceDates": [
        {
          "startDate": "2001-01-01",
          "endDate": "2011-01-01"
        }
      ]
    }
  }
]
```

We should instead submit
```
[
  {
    "type": "retrievalEvidence",
    "attributes": {
      "locationAndName": "VAMC Location",
      "evidenceDates": [
        {
          "startDate": "2001-01-01",
          "endDate": "2011-01-01"
        }
      ]
    }
  }
]
```

Since the dates and location are the same. On the frontend the user also entered conditions, but we do not pass them along or do anything with them right now. We can further evaluate THAT, with lighthouse, but I do not think we should block fixing this bug, with that discussion.

**Comment by Mottie** [comment]
Fix has been merged, will evaluate the work in staging; but this fix will likely be published into production today

**Comment by Mottie** [comment]
Found one bug while testing in staging - `2022-01-01` wasn't matching `2022-1-1`. Opening a PR for this fix soon.
