### ISSUE TITLE
Bug Fix - Design - Future Date of Claim(DOC) being established for Reservists and National Guards

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#58814]
## Issue Description
Some claims are being populated with a future Date of Claim(DOC) when the user is entering their Contract End Date instead of active Service Exit Date. The discovery has identified that the reservists and national guards are able to submit claims with > 180 days exit date. Validation will soon prevent reservists and national guards from entering a date > 180 days.

The scope of this ticket is to design UI changes to 
1 . Provide clarity about the value expected here (Active Service exit date, not Contract End Date)
2. Help user recover from error (Veterans must enter a past date as their service exit date, for the most recent active service)

## Need to know

How to replicate: 
1. Enter Service Type as Reservist or National Guards and enter future Service Exit Date > 180 days
2. Submit the claim with other fields populated
3. The claim gets established with this future Service Exit Date as Date of Claim.

#56631 -older ticket with context- https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/56631

-- Notes from discussion with VBA stakeholders(Alejandro) on[ May 18th](https://docs.google.com/document/d/1H9xgYJ-oAj3AWKtnzZxOI3xv_ayQKju03rkc36Emax8/edit#)

---
## Tasks
- [x] Create annotated screenshot/low-fi mockup to show revised UI including revised error message(s)

## Acceptance Criteria
- [x] Sketch file for pass off to FE engineering

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
cc @lydiahooper

**Comment by lydiahooper** [comment]
Content notes:

There are potentially four screens on which users enter data related to service dates, and this is the language used on each that refers to an end date of one kind or another (listed in order of flow in 526):
[Start](https://www.va.gov/disability/file-disability-claim-form-21-526ez/start) -"date or anticipated date of your release from active duty"
[Military service history](https://www.va.gov/disability/file-disability-claim-form-21-526ez/review-veteran-details/military-service-history) - "Service end date"
[Reserve and National Guard Information](https://www.va.gov/disability/file-disability-claim-form-21-526ez/review-veteran-details/military-service-history/reserves-national-guard) - "Obligation end date"
[Federal Orders](https://www.va.gov/disability/file-disability-claim-form-21-526ez/review-veteran-details/military-service-history/federal-orders) - "Expected separation date"

According to meeting with VBA (Alejandro) on May 18, 2023, 
separation date = date active duty ends = release from active duty (RAD)
contract end date = obligation term of service end date 

Use cases described in this MURAL: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683913843847/0345ee4211f208974d546a51fedb71f0deb46724?wid=0-1683923223010&sender=u2905941a69b3083a009c9997

**Comment by lydiahooper** [comment]
Revised content is for this page: https://www.va.gov/disability/file-disability-claim-form-21-526ez/review-veteran-details/military-service-history

Sketch file showing changes: https://sketch.com/s/ff18b4fb-376a-4f9f-b014-e888f69d9957
