### ISSUE TITLE
Update poster for IVC feedback

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#58813]
## Description 

Update poster based on IVC feedback.

[PDF](https://app.zenhub.com/files/133843125/1afbbe18-9c44-499c-a62c-0cb191e77e25/download)

[Slack thread - see comments from Danielle](https://dsva.slack.com/archives/C02GXKL8WM6/p1684766543498899)

## Tasks

- [x] Update all versions of posters
- [x] Work with Danielle and Laura to review feedback
- [ ] Update Git page with new versions

## AC

- [x] All poster versions are updated
- [x] Git page is updated

**Comment by zach-park** [comment]
@kellysmith1008  and I met and here is the updated poster based on the feedback.
https://www.sketch.com/s/9798426e-bba3-46dd-9d87-73d77dcf6599/v/kv2Y9g/a/YZZ39Av

**Comment by kellysmith1008** [comment]
@zach-park and I met today to make a few changes: we added periods in almost all suggested areas. The one place we did not was in Step 1: Text check in to 53079 
The reason behind this is that if a Veteran includes the period in the number when entering it into a phone text "To" field, it cancels the text and doesn't provide good information on why the text was canceled. To avoid any confusion, we'd like to avoid adding a period to the end of this step.
We removed "instead" from the final wording to now read "Need to update your information? Check in with a staff member."
We removed the hyphen from Step 3, changed "Tap" to "Select", and removed "on" to make Step 3 now read: "Select the link to start check in."
We also added a period after "If you wait more than 15 minutes, tell a staff member." though not explicitly part of the received feedback.
Other suggestions we deferred to guidance provided in the slack conversation by Danielle.

**Comment by zach-park** [comment]
[1] “53079.” entered in the latest Android OS (version 13) -->  

![text invalid contact error-1 Screenshot_20230525-123930 copy.jpg](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/2a8329a4-5e8d-4563-80bc-8d9054e3fef0)

[2] Invalid Contact error toast appears in the same screen with the “53079.” is cleared. Canceling out the composing text action.  
![text invalid contact error-2 Screenshot_20230525-123935 copy.jpg](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/ce33ca7f-45cc-419c-bc26-fc74b03aaf93)

**Comment by kellysmith1008** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/93271257/657fb1df-d4f0-4d17-9177-b416b041fb3b)

**Comment by benbrasso-agile6** [comment]
Ah, sounds good. @zach-park want to get it pushed up to our Git page and ping stephen here https://dsva.slack.com/archives/C02GXKL8WM6/p1684766543498899

**Comment by zach-park** [comment]
Hi @benbrasso-agile6 , PDF posters (in all sizes) are uploaded on Git and shared the link to Stephen.

**Comment by benbrasso-agile6** [comment]
lgtm https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/design/visual-collateral
