### ISSUE TITLE
Collaboration Cycle for Benefits Management Tools, Claim Status Tool, Improve Evidence Request/Submission Experience

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#58828]
### VFS team name

Benefit Tools

### Product name

Claim Status Tool

### Feature name

Improved Evidence Request Initiative

### GitHub label for product

claim status tool

### GitHub label for feature

evidence-requests

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

5/1/2023

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Tools, applications and dynamic pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/CST%20Product/Product%20Outline.md

### Initiative Brief

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/CST%20Product/Improved%20Evidence%20Requests%20Initiative.md

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Notify the Collaboration Cycle team of this ticket in the vfs-platform-support Slack channel.

- [X] I acknowledge that I must notify \#vfs-platform-support after submitting this issue.

Kickoff Slack Thread with VFS team: https://dsva.slack.com/archives/CBU0KDSB1/p1687895405129199

</details>

### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- Navigate to reference link: [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent)
- [x] Schedule your Design Intent when ready:
   - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
      - The Governance team is responsible for inviting our team members, including our Product Owner, Product Manager, and practice area specialists. We also notify OCTO-DE practice area leads when we finalize meeting scheduling. 
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [x] Link all artifacts **ONLY** in the Design Intent artifacts section below at least two days before the scheduled Design Intent.  **Do NOT add artifacts to Comments section**
  
**Design Intent artifacts**

See Platform guidance on [Design Intent artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Design Intent meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

- [x] [CST Design Concepts.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/11911047/CST.Design.Concepts.pdf) (Early design explorations)
- [x] [User flow](https://www.sketch.com/s/98e35645-34eb-40cf-80c1-6c4952943584/prototype/a/252DFC7E-C58A-478F-A521-5C082886DA75) (Latest prototype used in testing)
- [x] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/2023-05-Evidence-Submission/research-plan.md)
- [x] [Research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/2023-05-Evidence-Submission/research-findings.md)
- [x] [Evidence Request Initiative Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/CST%20Product/Improved%20Evidence%20Requests%20Initiative.md)
- [x] Any other artifacts you have so far
  
##### Platform actions
- [x] Design Intent Slack thread with VFS team: [Link](https://dsva.slack.com/archives/CBU0KDSB1/p1687895405129199)
- [x] Meeting date/time: **Thursday, July 6th at 3:30pm ET**
  
##### Platform actions

- [x] If you have feedback, create feedback tickets and link to this epic. Once you have completed you review, check the box next to your practice area
  - [x] Accessibility has completed the review
  - [x] Design has completed the review
  - [x] IA has completed the review
- [x] Update this ticket with the Zoom recording
  - [Recording](https://oddball-io.zoom.us/rec/share/7aCcNkAolS42nEcrWOMFtS2-g6KNNCcLlgrLmKARUYo2rLEy-8Jx6bExZLW1h1Df.gOC6owaChg7nGR9q)
  - Password: a**Czo0s
  
##### VFS actions

- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Sitewide CAIA Intake Request
<details>
  <summary>Toggle Sitewide CAIA Intake Request</summary>

##### VFS actions
- [ ] Complete the [sitewide content and IA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-Content-and-IA-intake-request.2124906551.html)
- [ ] Link to the Sitewide Content and IA Intake Request ticket below

</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [ ] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [ ] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

Provide links or documents for the following:

- [x] [Finalized design prototype or mockup](https://www.sketch.com/s/98e35645-34eb-40cf-80c1-6c4952943584/p/B9C46ABC-36AD-4CA8-9896-55762FC6912E/canvas)
- [x] Specify which pages are included in the review: Please review the content in the "Latest" page of the Sketch file. There are mobile and desktop versions, with no major differences between the two other than form factor.
- [x] Research plan: [Research findings from initial usability testing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/2023-05-Evidence-Submission/research-findings.md). Since we started this design process with user research, we are not sure another usability test is necessary. Most of the changes we've made since the initial research are visual design updates based on platform feedback. We'd like to discuss what type of validation makes sense, given the research we've done up until this point.
- [x] Conversation guide: [Conversation guide from initial usability study](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/2023-05-Evidence-Submission/conversation-guide.md)

**Content artifacts**
  
- [x] Your product’s content source of truth: [Design mocks](https://www.sketch.com/s/98e35645-34eb-40cf-80c1-6c4952943584/p/B9C46ABC-36AD-4CA8-9896-55762FC6912E/canvas) serve as our content source of truth.
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)

**IA artifacts**

- [x] [Please include a link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61696) to any Sitewide Content & IA feedback you received, including an IA review document or intake form. 

##### Platform actions
- [X] [Midpoint review Slack thread with VFS team](https://dsva.slack.com/archives/C04KHCT3ZMY/p1693243472118049)
- [X] Meeting date/time: Tuesday, September 5 at 3:30 p.m. Eastern

##### Platform actions

- [ ] If you have midpoint review feedback, create feedback ticket and link to this epic. Once you have completed your review, check the box next to your practice area
  - [x] Design has completed the review
  - [ ] Accessibility has completed the review
  - [x] IA has completed the review
  - [x] Content has completed the review
- [ ] Update this ticket with the Zoom recording
  - Recording URL: https://oddball-io.zoom.us/rec/share/-0RtFzaGFAl0pJsRJ_z-xLiqPH4pNSv9ZCKp4_E5ZftsnIWo2nzlPbNSVPCLRzgT.iBXDpnyJXMnzT4Pa
  - Password: 7Xai2aQ#
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [x] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [x] Link to the Analytics Implementation and QA Request ticket below
https://github.com/department-of-veterans-affairs/va.gov-team/issues/80920

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [x] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [x] [Link to the Contact Center review request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80996) 

</details>

### Staging Review (claim cards)
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [ ] I confirm the environment is available and test users have been provided.
- [ ] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
 
**Staging Review artifacts**
  
See Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts). Platform findings are based solely on the staging URL and test users provided, as reviewed during the four days before the Staging Review meeting. Any test cases not covered or any ongoing work taking place during the review period may not be reflected in those findings.  

**Product artifacts** 
- [ ] Staging URL:  https://staging.va.gov/track-claims/your-claims
- [ ] Specify which pages are included in the review        
- [ ] Staging test user information: Line 25 here: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv        
  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
  
**IA artifacts**
- [ ] Please include a link to any [Sitewide Content & IA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) of the findings you received, including an IA review document or intake form.

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [x] [Regression test and functional QA plan](https://dsvavsp.testrail.io/index.php?/milestones/view/1321)
- [x] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/505)
- [x] [Summary(Defects) reports](https://dsvavsp.testrail.io/index.php?/reports/view/506)
- [x] [E2E tests](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/claims-status/tests/e2e/00.claims-list.cypress.spec.js) 
- [x] Code coverage 

You can view the claim status project code coverage by going to [this link](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report). 

For a more in-depth code coverage report please pull down `vets-website` and run the following command `yarn test:coverage-app claims-status`. This will provide you with a report of code coverage per file. Below is a list of the files that we made changes to.

**claims-status/components**
- ClaimComplete.jsx
- ClaimDetailLayout.jsx
- ClaimOverviewHeader.jsx
- ClaimsDecision.jsx
- ClaimsListItem.jsx
- ClaimStatusHeader.jsx
- ClosedClaimMessage.jsx
- DueDate.jsx
- NeedHelp.jsx
- RequestedFilesInfo.jsx
- TabNav.jsx

**claims-status/components/claim-files-tab**
- AddFilesForm.jsx
- AdditionalEvidencePage.jsx
- ClaimFileHeader.jsx
- DocumentsFiled.jsx
- FilesNeeded.jsx
- FilesOptional.jsx

**claims-status/components/claim-status-tab**
- ClosedClaimAlert.jsx
- NextSteps.jsx
- Payments.jsx
- RecentActivity.jsx
- WhatWeAreDoing.jsx
- WhatYouNeedToDo.jsx

**claims-status/components/ClaimCard**
- ClaimCardLink.jsx

**claims-status/containers**
- AskVAPage.jsx
- ClaimStatusPage.jsx
- DocumentRequestPage.jsx
- FilesPage.jsx
- OverviewPage.jsx
- YourClaimsPageV2.jsx

**claims-status/utils**
- helpers.js
  
**Accessibility artifacts**
  
- [x] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64831). 

For details, see [Prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).
  
##### Platform actions
- [x] [Staging review Slack thread with VFS team](https://dsva.slack.com/archives/C04KHCT3ZMY/p1693243422927899) [Second Slack request](https://dsva.slack.com/archives/C04KHCT3ZMY/p1698686364006089)
- [x] ~~Meeting date/time: Tuesday, September 5, 11:30 a.m. Eastern~~ Rescheduled: November 3 at 2:00pm ET

##### Platform actions

- [x] Update this ticket with the Zoom recording
  - Recording URL: [Zoom recording](https://oddball-io.zoom.us/rec/share/WpP7smYZhlkAEIkJMm0e2OEIOKej9mygqwqf2UyEQwvhg_dGhTQZMcp8O6CayQv0.LLbJSR_4SvveOleY)
  - Password: `7*nN=8bv`
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Staging Review (detail page)
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [x] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [x] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [x] I confirm the environment is available and test users have been provided.
- [x] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
 
**Staging Review artifacts**
  
See Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts). Platform findings are based solely on the staging URL and test users provided, as reviewed during the four days before the Staging Review meeting. Any test cases not covered or any ongoing work taking place during the review period may not be reflected in those findings.  

**Product artifacts** 
- [x] Staging URL: https://staging.va.gov/track-claims/your-claims/600471552/status
- [x] Specify which pages are included in the review: Status tab, files tab, Overview tab, specific evidence request details pages that alerts link to, such as https://staging.va.gov/track-claims/your-claims/600471552/document-request/467558
- [x] Staging test user information: Row 25 (Kyle Cole) and Row 48 (Cody Garza) here: https://staging.va.gov/track-claims/your-claims/600471552/document-request/467558

- "Cody Garza" should be used to see the "Recent Activity" secondary alert in action. 
- "Kyle Cole" is sufficient to view most other use cases
  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**
- [x] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
  
**IA artifacts**
- [x] Please include a link to any [Sitewide Content & IA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61696) of the findings you received, including an IA review document or intake form.

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).

Note that, for the following "test plans", we ran test runs that were not attached to a test plan and there wasn't a way to retroactively attach those runs to a plan (sorry about that). Here are the results of the runs in question, which contains all the information about what use cases were tested: 
- [x] [Regression test plan]: Seen in Claim Details V2 section of this Test Rails page: https://dsvavsp.testrail.io/index.php?/runs/view/5326&group_by=cases:section_id&group_order=asc
- [x] [Test plan] Seen in the Claim Details V2 section of this Test Rails page: https://dsvavsp.testrail.io/index.php?/runs/view/5322&group_by=cases:section_id&group_order=asc

More caveats incoming: We did find some issues in our test runs, but they ended up being issues with the V3 file submission component and the tickets we created for that were Design System tickets in a repo different from the one connected to Test Rails. Adding those reference IDs ended up producing incorrect results in Test Rails. The tickets you'll see in the summary of defect report are not the actual tickets that ended up being created. Here are links to those tickets: 

- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2549
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2511
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1578

- [x] [Coverage for References](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports) https://dsvavsp.testrail.io/index.php?/reports/view/718
- [x] [Summary(Defects) reports](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports): https://dsvavsp.testrail.io/index.php?/reports/view/733
- [x] [E2E tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-e2e-test-participationE2ETestParticipation) (provide a link to the product’s code): Tests can be found [here](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/claims-status/tests/e2e). Specific names of new tests: 

- [01.claim-status.v2.cypress.spec.js](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/claims-status/tests/e2e/01.claim-status.v2.cypress.spec.js)
- [02.claim-files.v2.cypress.spec.js](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/claims-status/tests/e2e/02.claim-files.v2.cypress.spec.js)
- [03.claim-overview.v2.cypress.spec.js](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/claims-status/tests/e2e/03.claim-overview.v2.cypress.spec.js)
- [04.claim-ask-va.v2.cypress.spec.js](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/claims-status/tests/e2e/04.claim-ask-va.v2.cypress.spec.js)

- [x] Code coverage 

You can view the claim status project code coverage by going to [this link](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report). 

For a more in-depth code coverage report please pull down `vets-website` and run the following command `yarn test:coverage-app claims-status`. This will provide you with a report of code coverage per file. Below is a list of the files that we made changes to.

**claims-status/components**
- ClaimComplete.jsx
- ClaimDetailLayout.jsx
- ClaimOverviewHeader.jsx
- ClaimsDecision.jsx
- ClaimsListItem.jsx
- ClaimStatusHeader.jsx
- ClosedClaimMessage.jsx
- DueDate.jsx
- NeedHelp.jsx
- RequestedFilesInfo.jsx
- TabNav.jsx

**claims-status/components/claim-files-tab**
- AddFilesForm.jsx
- AdditionalEvidencePage.jsx
- ClaimFileHeader.jsx
- DocumentsFiled.jsx
- FilesNeeded.jsx
- FilesOptional.jsx

**claims-status/components/claim-status-tab**
- ClosedClaimAlert.jsx
- NextSteps.jsx
- Payments.jsx
- RecentActivity.jsx
- WhatWeAreDoing.jsx
- WhatYouNeedToDo.jsx

**claims-status/components/ClaimCard**
- ClaimCardLink.jsx

**claims-status/containers**
- AskVAPage.jsx
- ClaimStatusPage.jsx
- DocumentRequestPage.jsx
- FilesPage.jsx
- OverviewPage.jsx
- YourClaimsPageV2.jsx

**claims-status/utils**
- helpers.js
  
**Accessibility artifacts**
  
- [x] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78989). We've also attached the specific accessibility defect tickets to this epic for your reference.
  
##### Platform actions
- [x] Staging review [Slack thread with VFS team](https://dsva.slack.com/archives/C04KHCT3ZMY/p1712177848932539)
- [x] Meeting date/time: April 11 at 1:30pm ET

##### Platform actions

- [x] Update this ticket with the Zoom recording
  - Recording URL: [Zoom recording](https://oddball-io.zoom.us/rec/share/nGQeb9LlkhaTTh5QTUYViv3OjY5fpXx5WE805tCqSYFM0-6_ZtmiGDlcNMZuUFxr.HhjZH1kK3iLvvlbx)
  - Password: `1MFfNj=5`
  
##### VFS actions
  
- [x] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [x] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [x] Link to the Readiness Review ticket below
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1616

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by skylerschain** [comment]
Design Intent feedback tickets have been updated and closed out. Thanks all for your contributions!

**Comment by jacobworrell** [comment]
Hi @shiragoodman! Now that we've incorporated Collab Cycle feedback into design revisions, I want to ensure we're taking the appropriate next steps. 

The usual objective for the Midpoint Review is "To confirm your prototype or mockup aligns with existing [VA.gov](http://va.gov/) patterns and standards and to ensure your product is ready for successful research activities. This may include usability testing, Veteran interviews, or anything else specified in your research plan."

After making changes based on Collab Cycle feedback, we don't feel like the designs changed enough to require an additional round of user testing. We feel like the user insights that came from our previous user testing sessions are also baked into our revisions and we'd likely encounter diminishing returns and unnecessary delays by running a second round of testing. 

Given this is where we're at, what do you recommend as a next step here? Our instinct is to transition to delivery-mode but put things behind a feature flag. We'd concurrently go through the Analytics Request process and also work on materials for Contact Center Review. I wonder if the next formal touchpoint with the Collab Cycle should be Staging Review.

**Comment by shiragoodman** [comment]
hey @jacobworrell . Thanks for reaching out. We don't have a preference regarding which path you take... Whatever makes to most sense for your team. However, with that said, here are your options. 

- You can skip Midpoint Review and go straight to Staging Review. Midpoint Review is optional, so no need to partake in it if you don't think it'll be valuable.
- You can still schedule a Midpoint Review (either synch or asynch) as an additional check-in. Teams don't always complete research on the standard timeline, so we offer Midpoint as an option if VFS teams want to get confirmation that the decisions they made post Design Intent are still in alignment with the VA.gov standards.

With regards to your Staging Review... we can accommodate 2 Staging Reviews. We have done that in the past for any product that has a static entry page that was built or updated by CAIA. If that's the path you choose to take, just let me know, and we can get your ticket set up to accommodate 2 staging reviews.

**Comment by pmclaren19** [comment]
For Code Coverage report please pull down vets-website and run the following command `yarn test:coverage-app claims-status`.

**[claims-status/components](https://github.com/department-of-veterans-affairs/va.gov-team/issues/claims-status/components/index.html)**
- ClaimComplete.jsx
- ClaimDetailLayout.jsx
- ClaimOverviewHeader.jsx
- ClaimsDecision.jsx
- ClaimsListItem.jsx
- ClaimStatusHeader.jsx
- ClosedClaimMessage.jsx
- DueDate.jsx
- NeedHelp.jsx
- RequestedFilesInfo.jsx
- TabNav.jsx

**[claims-status/components/claim-files-tab](https://github.com/department-of-veterans-affairs/va.gov-team/issues/claims-status/components/claim-files-tab/index.html)**
- AddFilesForm.jsx
- AdditionalEvidencePage.jsx
- ClaimFileHeader.jsx
- DocumentsFiled.jsx
- FilesNeeded.jsx
- FilesOptional.jsx

**[claims-status/components/claim-status-tab](https://github.com/department-of-veterans-affairs/va.gov-team/issues/claims-status/components/claim-status-tab/index.html)**
- ClosedClaimAlert.jsx
- NextSteps.jsx
- Payments.jsx
- RecentActivity.jsx
- WhatWeAreDoing.jsx
- WhatYouNeedToDo.jsx

**[claims-status/components/ClaimCard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/claims-status/components/ClaimCard/index.html)**
- ClaimCardLink.jsx

**[claims-status/containers](https://github.com/department-of-veterans-affairs/va.gov-team/issues/claims-status/containers/index.html)**
- AskVAPage.jsx
- ClaimEstimationPage.jsx
- ClaimStatusPage.jsx
- DocumentRequestPage.jsx
- FilesPage.jsx
- OverviewPage.jsx
- YourClaimsPageV2.jsx

**[claims-status/utils](https://github.com/department-of-veterans-affairs/va.gov-team/issues/claims-status/utils/index.html)**
- helpers.js

**Comment by shiragoodman** [comment]
Hi @pmclaren19  - thanks for sharing this! In the future, please be sure to include this information within the body of the ticket. My team knows to look for artifacts within the ticket, and we don't always check the comments section of the gh ticket. Thanks for understanding!

**Comment by pmclaren19** [comment]
No problem @shiragoodman ! I was just asked to add a comment with the info, I believe we planned to update the ticket body with this info!

**Comment by skylerschain** [comment]
Hey @shiragoodman I seem to recall from past reviews there being a master ticket for each practice area with all of the issues listed out (Must, Should, Consider). Can you remind me where those live? Thank you!

**Comment by shiragoodman** [comment]
Hey @skylerschain  - good question! The feedback tickets our team provides for Design Intent and Midpoint Review use the[ Must, Should, Consider framework. ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback)You can read more about it on the page I linked. 

For Staging Review, we use a different ticket template. The [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket) guidance would _normally_ help, however, as you can see at the top of each of your Staging Review tickets...
<img width="801" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/71330581/9f69feb5-b889-4591-8e30-d7f64ea3b988">

...we're in the middle of testing/piloting/launching changes to our Staging Review process and the VA.gov Experience Standards that go along with it. The Anatomy guidance I linked won't exactly be a 1:1 match to the tickets we created for you today, but it should help somewhat. We plan to get the updated Anatomy guidance published within the next couple weeks. We apologize for any inconvenience, and thank you for your understanding. 

Lastly, as for where to find all of your tickets, we utilize the Milestone feature in Github. All tickets opened by our team at the Design Intent, Midpoint Review, and/or Staging Review(s) can be found in the [milestone. ](https://github.com/department-of-veterans-affairs/va.gov-team/milestone/1122) You can typically find the milestone linked in the right panel of this ticket, alongside Labels, Assignees, Sprint, etc.

hope this helps!
