### ISSUE TITLE
Updates to COVID FAQS page around new guidance

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#58827]
## Issue Description

We've been asked to make updates to our COVID faqs page around health protection levels, free masks and tests, and mask guidance in VA facilities.

We need to hold on publishing the changes until we get the OK.

Changes are all in this word doc: [https://app.zenhub.com/files/133843125/77ee0a83-d781-41d7-a584-558fce212df3/download](https://app.zenhub.com/files/133843125/77ee0a83-d781-41d7-a584-558fce212df3/download)

## Tasks
- [ ] Update Drupal page with changes
- [ ] OCTO review (Danielle)
- [ ] Send to stakeholders for review (Aliyah/Randi)
- [ ] Copyedit (Megan)
- [ ] Publish (Megan)

## Acceptance Criteria
- [ ] Changes are live on the site

**Comment by aliyahblackmore** [comment]
Hi @DanielleThierryUSDSVA these updates are ready for you to review in Drupal.

**Coronavirus FAQs: What Veterans need to know**
http://preview-prod.vfs.va.gov/preview?nodeId=3014#check-your-va-health-facilitys

I tracked some changes to content in their word document and included some more specific notes/questions on the _"What are VA health facility’s guidelines on masks, visitors, and symptom screening as COVID-19 levels change?"_ accordion.

[COVID-19 FAQs edits around new guidance_AB_5.23.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11548914/COVID-19.FAQs.edits.around.new.guidance_AB_5.23.docx)

**Posting those questions here as well:** 

- Their updated answer to this question only mentions mask guidelines – there’s no mention of guidelines for visitors or symptom screening. I adjusted the accordion question to reflect their suggested update re: masks and removed the mention of “levels” since that was removed from their update. Randi mentioned that when we send content for their review, we can call out that we adjusted the question since they’re now only talking about masks. 

- They included a few examples of high-risk areas – I put those in a bulleted list. Alternatively, if you have a preference to not include specific high-risk areas, the sentence would just be something like this: _All facilities require masks in high-risk areas and for people who are sick with COVID-19 or other viral respiratory illnesses._

- They’ve asked us to link out to this [public health page](http://www.publichealth.va.gov/). I searched on the page and think that the specific link is actually [this COVID-19 page.](https://www.publichealth.va.gov/n-coronavirus/index.asp) We wouldn’t usually link out to a legacy page, but I’m wondering if there’s a need to link to this page here?  I’m also asking this because the content for VA specific COVID-19 information (in the yellow box) links back to this Coronavirus FAQs page. I’d suggest that we include their suggestion to contact their care team (link to send a secure message) and direct folks to contact their VA health facility if they have more questions about mask requirements. I’ve made that adjustment in the content.

- Stakeholders are having us remove the mentions of “levels” in their updated content, but some VA health facilities are still using “COVID-19 levels” on their pages. [This Bronx VA facility still has](https://www.va.gov/bronx-health-care/locations/james-j-peters-department-of-veterans-affairs-medical-center/) “Levels high.” Any need for us to communicate this change to facilities? 

- Wondering if we’d want to include a note here like this:  “Check signs at your facility so you know what’s required.” If so, I’d suggest a slight adjustment here if we're not sure if facility signs are accessible to all folks – could we instead suggest that folks check in with a staff member or their care team **or** would contacting a VA health facility about requirements be enough?  

- On the sentence about practices/requirements by facilities, I added in “mask and safety practices” because their suggested updates are more specific to masks. I also made some smaller adjustments here to better align with VA site style. Also, I wonder if this sentence would work better as a note?

- Stakeholders included a sentence about asking a staff member for a mask. I noticed that they’re having us remove the question on free masks – is it the case that VA facilities will still provide a free mask, at an appointment for example? I adjusted their language and left this in for now.

**Comment by aliyahblackmore** [comment]
**Update:** 

Stakeholders got back to use to clarify re: masks - we're okay to leave in that folks will get a mask if they ask for one. 

This is ready to publish after a copy edit!

**Comment by aliyahblackmore** [comment]
Megan published this and the changes are live!

**Comment by RLHecht** [comment]
Thanks! Closing ticket and will set up a translation ticket.
