### ISSUE TITLE
[bug spike] Supplemental Claims | A file that is too large for downstream service was accepted

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#58837]
## Value Statement

**_As a_** developer
**_I want to_** know the cause of evidence that is too large being allowed to pass through a submission
**_So that_** we can prevent the error from occurring.

---
## Background Context
Time boxed spike (1-2 hours). Look into why the file was accepted. Could be the difference in how bytes are calculated.  

## Tasks
- [x] Review the PDF that was submitted, gather user UUID
- [x] Discuss with LH how they calculate bytes
- [x] LH to possibly talk to upstream services like Domo or Data Dimensions

---
## Definition of Ready 
- [x] We have a sample of the PDF
- [x] User UUID

## Definition of Done
- [x] We know the cause of the error
- [ ] We've defined a solution if needed, and assigned it to the appropriate party
- [ ] We've asked the CC team to reach out and ask the Veteran to resubmit

**Comment by kylesoskin** [comment]
Got some more occurrences of this. Picking up now.

**Comment by kylesoskin** [comment]
@saderagsdale this ticket can be closed. Mystery is solved. Lighthouse has been brought into the fold and is investigating solutions on their end (with our input) and we can all come to a joint solution! 

Lmk if you would like to chat about why this bug was occurring and possible fixes/solutions.

**Comment by kylesoskin** [comment]
https://jira.devops.va.gov/browse/API-27154

We dont have access I dont think, but that is LH ticket tracking this.
