### ISSUE TITLE
HLR | Update mock user data in staging

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#58833]
## Value Statement
**_As a_** researcher
**_I want to_** accurately test the Board Appeal form in a staging environment
**_So that_** I can get accurate feedback using up-to-date data

---
## Background Context

**Needs to be completed for experimental design testing.** Board Appeal form is already existing in PROD, and we want to observe how Veterans interact with the form within the VA.gov environment. As a backup, for Veterans uncomfortable sharing their information in PROD, we want a testable environment in STAGING, where the claims information is up-to-date (within the year)

Ideal testing scenario (user-236):
- Login to staging
- Sees closed disability claim that was updated with a decision date within the year 
- Sees a decision letter for that claim
- Sees claim show up when adding issues in NoD (HLR uses a different endpoint)

## Acceptance Criteria
- [ ] Updated mock data for staging user-236 that has closed disability claims within the year. 

## Out of scope
- PROD changes

## Tasks
- [ ] Find out why the current implementation is failing (wrong data or issues with upstream service)
- [ ] Update mock user data for user-236 to include closed claims/appeals that are within the year.

## Definition of Ready 

- [ ] Aligned on what data needs to appear
- [ ] Use case defined
- [ ] We know who can update the data (Robin looking into this with Michel)

## Definition of Done

- [ ] Mock data added
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
All work had been merged in, but:
- The `vets-api` feature flag (backend) won't get merged in until tomorrow. The api deploy happens at noon daily.
- The front-end work is available in production, but the feature flag is named `hlr_disable_submit`

**Comment by Mottie** [comment]
Verified working (disabled submit) in staging for user vetsgov+test234@id.me

**Comment by eileen-coforma** [comment]
@Mottie I think you meant to update https://github.com/department-of-veterans-affairs/va.gov-team/issues/58229

**Comment by saderagsdale** [comment]
@Mottie @eileen-coforma Is this work completed?

**Comment by Mottie** [comment]
Yes, this work is done; but I just checked the feature flags in staging and it's still showing up there, but when I tried to use it, it failed telling me that the feature flag is gone, but the entry is still showing up due to a bug on the backend. I'll let platform know.

**Comment by eileen-coforma** [comment]
@Mottie Wrong ticket... this is about mock user data

**Comment by eileen-coforma** [comment]
This is the ticket for getting updated mock user data on staging, for at last one of our testing accounts. I believe @michelpmcdonald was looking into this, but haven't gotten an update since. 

We passed the immediate need for it (since it was meant for initial research), but we still need it to test our product in staging when we start doing design updates.

**Comment by saderagsdale** [comment]
We'll do this internally (excluding Michel).

**Comment by saderagsdale** [comment]
Waiting for contacts to reach out to. See [this thread](https://dsva.slack.com/archives/C05HT3MFK0F/p1690378787985179).

**Comment by kylesoskin** [comment]
I am hoping to transition this to a non-engineering task (more of a research/design effort to figure out how to use VBMS to create or edit data to our desired states in an ongoing manner to support testing and research.

**Comment by shaunburdick** [comment]
@skylerschain and @eileen-coforma will sync up to see if they can create a new claim for the users commonly tested with.

**Comment by eileen-coforma** [comment]
Met with Skyler. Skyler will ask Andrew Gray to see if it's something that can be done within VBMS.
From what we can see, VBMS Core does not have the ability to close claims or edit closed claims.

**Comment by eileen-coforma** [comment]
Skyler requested that a claim for staging Claim ID: 600529849
User: vets.gov.user+23@gmail.com to Andrew to close

We'll check if Andrew can close claims, and if it fulfills our testing requirements.

**Comment by skylerschain** [comment]
There's now a claim closed on *Aug 2, 2024* for vets.gov.user+23@gmail.com – we should be able to use that for testing.

**Comment by anniebtran** [comment]
@eileen-coforma to validate or @Mottie ?

**Comment by Mottie** [comment]
Verified that user 23 has:
- 4 contestable issues dated Aug 2, 2024
- 4 contestable issues dated Feb 5, 2024
