### ISSUE TITLE
[bug spike] Supplemental Claims | Internal Server error

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#58839]
## Value Statement

**_As a_** developer
**_I want to_** know the cause of this internal server error
**_So that_** we can prevent the error from occurring.

---
## Background Context
Time boxed spike (1-2 hours).

## Tasks
- [ ] Review Sentry logs for more info
- [ ] See if they can be aligned with and other logs from backend errors

---
## Definition of Ready 
- [ ] Access to logs and error info (FE and BE)

## Definition of Done
- [ ] We know the cause of the error
- [ ] We've defined a solution if needed, and assigned it to the appropriate party
