### ISSUE TITLE
[bug spike] Supplemental Claims | The frontend passed a blank/empty email 

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#58835]
## Value Statement

**_As a_** developer
**_I want to_** know the cause of blank emails passing through a submission
**_So that_** we can prevent the error from occurring.

---
## Background Context
Time boxed spike (1-2 hours)/. Look at the save in progress data to see what the current value is (to confirm that it's actually blank and not another issue stripping the email address). 

## Tasks
- [ ] Review save in progress data
- [ ] If it's blank as expected, ask contact center to reach out to Veteran to ask them to update their email address in profile
- [ ] If something else is stripping out the email address, add tasks below for further investigation

---
## Definition of Ready 
- [ ] SIP data
- [ ] User UUID

## Definition of Done
- [ ] We know the cause of the error
- [ ] We've asked the CC team to reach out to them with instructions for fixing their issue
