### ISSUE TITLE
[CST] Add feature toggle override

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#58843]
## Background
In order to facilitate a staged rollout of the Lighthouse version of the CST, we made separate versions of many of the components where each version is associated with either Lighthouse claims, or EVSS claims. As we are at the staging QA step in the migration (to be followed by a staged rollout in production) it makes sense to compare the same claims with both versions of each component to make sure that everything works the same. To do this requires flipping the feature toggle on and off and logging in and out of the staging users to do so. To make this process easier, it seems to make sense to have a set of manual overrides so that we can select which version of a claim we want to view. I'm going to create a set of controls that allow us to override the value of the feature toggle in lower environments (staging, dev, localhost, etc.)

## Considerations
In order to simplify the architecture, the controls won't force a rerender. For now the user will select which API they want to use, and then refresh the page to see the intended UI.

## Tasks
- [ ] Create controls to override feature toggle value

## Acceptance Criteria
- [ ] The override controls should only be available in lower environments
- [ ] Selecting an override will not automatically update the UI
- [ ] Override controls can be hidden with a keyboard shortcut
