### ISSUE TITLE
Modify BenefitsClaims::Service and its downstream dependencies to assume a single Client ID and RSA Key

### ISSUE THREAD

**Issue by navaeddie** [department-of-veterans-affairs/va.gov-team#58845]
## Issue Description
In the course of migrating [GET Intent to File](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/57063) we learned that Lighthouse requires all products/teams on VA.gov use the same client_id and rsa_key for each Lighthouse API.

The code we first wrote for GET Intent to File assumed multiple client IDs would be used. Some of the changes made for GET Intent to File should be removed.

---
## Tasks
- [ ] Adjust places designed to handle multiple Client IDs to assume just one.

## Acceptance Criteria
- [ ] GET Intent to File still works
- [ ] BenefitsClaim::Service does not accomodate multiple Client Ids
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
No needed. Team decided to use our own LH credentials
