### ISSUE TITLE
Medallia - launch modal with crisis header language and new footer

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#58840]
## Issue Description
- aria label to `988` VCL line number
- hyperlink SMS number `838255`
- aria label to `911`
- remove `target` attribute from VCL hyperlink
- remove 'target` attribute from contact us hyperlink

![Screen Shot 2023-05-22 at 1.40.17 PM.png](https://images.zenhubusercontent.com/5a8c8e864b5806bc2bc7b6c7/98d0dc50-81dc-44d7-a10e-df4351e2dd54)---
## Tasks
- [x] _aria label to `988` VCL line number
- [x] - hyperlink SMS number `838255`
- [x] - aria label to `911`
- [ ] - remove `target` attribute from VCL hyperlink
- [ ] - remove 'target` attribute from contact us hyperlink
- [ ] - What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by aubreyarcangel** [comment]
Blocked by unable to deploy review instance to test solution. Opened a ticket with VFS platform support and DevOps is still investigating. It was a wider issue that has impacted other PR review instances https://dsva.slack.com/archives/CBU0KDSB1/p1684767619143429

A [PR](https://github.com/department-of-veterans-affairs/devops/pull/13069) was recently merged in the devops repo to fix the issue, but the problem still persists.

**Comment by aubreyarcangel** [comment]
The review instance issue above has been resolved. 

We have a new blocker. I've identified that the Cross-Origin Resource Sharing (CORS) policy is currently blocking the implementation of adding aria-labels to the Medallia header. Here's an explanation of why CORS is causing issues and some possible solutions we can explore:

Understanding CORS:
CORS is a security mechanism web browsers implement to restrict cross-origin HTTP requests. It ensures that resources (e.g., scripts, fonts, or APIs) requested from one domain are only accessible to requests originating from the same domain, unless explicitly allowed. This policy prevents potential security vulnerabilities that could arise from unauthorized access to sensitive data. [Here's a. more in-depth documentation on CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

To overcome this CORS-related blocker, I will contact the VSignals team about adding the Medallia server response headers to include the appropriate CORS headers.

**Comment by aubreyarcangel** [comment]
Still blocked. Met with VSignals team June 8th to request adding `access-origin` permissions to the Medallia HTTP headers, but they do not have direct access to the Medallia servers. A request was put in with the Medallia team.

**Comment by ATMiddleton** [comment]
@aubreyarcangel - relocated to backlog until unblocked.

**Comment by aubreyarcangel** [comment]
Updating requirements list here:

- Remove “1” in href=“tel:+1988"
- Remove “target” attribute in 988
- Add aria-label=“9 8 8" to 988
- hyperlink SMS number 838255 (a href=“sms:838255”)
- Add aria-label=“9 1 1" to 911
- Remove “1” in href=“tel:+1911"
- Remove ‘target’ attribute in 911 hyperlink
- Remove ‘target’ attribute from Veteran Crisis line hyperlink
- Remove ’target` attribute from Contact us hyperlink

**Comment by aubreyarcangel** [comment]
Met with Medallia team along with VSignals last week (7/13) and learned some blockers for us. Here are the [meeting notes](https://docs.google.com/document/d/1t6hlqLrLKyLUTrHAzgjPCnNSv32b4C6XgUW8mZBIfw0/edit#heading=h.e2g4m73qkmit)

I'll work with Sarkis to update the staging modal to reflect the action items from that meeting.

**Comment by aubreyarcangel** [comment]
Met with Sarkis to make adjustments to the staging Medallia modal.

**Comment by starlow00** [comment]
No blockers, but waiting on info from Sarkis and Medallia team (dependencies).

**Comment by aubreyarcangel** [comment]
Updates:
- Sarkis could not implement the `hidden` text solution (which CAIA accessibility folks okayed) for accessibility, so he is working with the Medallia engineering team to implement a fix.
- Medallia team has a ticket to add a feature to remove the `target` attribute in hyperlinks. No timeline for that implementation
- Medallia team has a ticket to add a feature to hyperlink SMS numbers, but no timeline for that

Sarkis is expecting an update back regarding the aria-label or hidden text solution, which is our biggest blocker to launching.

**Comment by ATMiddleton** [comment]
Awaiting input from Sarkis - should have update this week.

**Comment by aubreyarcangel** [comment]
From Sarkis regarding aria-labels or `hidden` element implementation: "nope - they are still investigating, however I did escalate this to a manager"

**Comment by ATMiddleton** [comment]
V signals needs to update the current version of Medallia. More information to follow.

**Comment by aubreyarcangel** [comment]
Met with Sarkis yesterday (8/23). His team is still waiting back from the Medallia team on new CSS file for the upgraded a11y-feature-friendly Medallia version. If the new Medallia version isn't ready to launch and issue have been fixed, then we will launch the crisis header language in its current form.

**Comment by ATMiddleton** [comment]
@aubreyarcangel - awaiting approval - should deploy by end of next Sprint.

**Comment by aubreyarcangel** [comment]
The crisis header has been deployed to production and is now live on VA.gov

Next steps:

1. Collaborate with Sarkis and his team to set up the latest version of Medallia in the staging environment. This upgraded version is anticipated to resolve several pending accessibility concerns.
2. After the setup, partner with the VA.gov a11y specialists to perform a thorough accessibility audit of the new Medallia.
3. Work with Sarkis to resolve any problems that come up during the audit.
4. Release the latest version of Medallia.
