### ISSUE TITLE
Demo: GitHub deprecation work

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#58849]
## Tasks
- [x] Create PPT to introduce demo. [Use this template](https://docs.google.com/presentation/d/1SUQp7RPCz8-hZx5jj3sW0ZeLx2x6MWVFhADbhZdONnA/edit?usp=sharing).

**Demo topic:** 

- [x] Demo document of GitHub audit and work done at this point in time

## Acceptance Criteria

- [x] Demo at the next scheduled demo
