### ISSUE TITLE
Demo: Understanding scroll viewport

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#58850]
## Tasks
- [x] Create PPT to introduce demo. [Use this template](https://docs.google.com/presentation/d/1SUQp7RPCz8-hZx5jj3sW0ZeLx2x6MWVFhADbhZdONnA/edit?usp=sharing).

**Demo topic:** 

- [x] Demo new document: [Understanding Scroll Viewport](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2613805085/Understanding+Scroll+Viewport)

## Acceptance Criteria

- [x] Demo at the next scheduled demo
