### ISSUE TITLE
Dynamically assign API endpoint to `content-build`

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#58851]
# Description
Given that Preview Environment frontends need to access API resources at a custom location in a separate pod, we need to configure `content-build` to route traffic to the appropriate API endpoint.

Given that each Preview Environment is creating resources dynamically when the image is created or when the container is started, the service name for the backend pod will be assigned when the individual PE is created. We need to pass the expected service name for the API endpoint into the start script from the GHA workflow that generates the frontend image so it can be used to build `content-build` with an API configuration argument.

# Tasks
- [ ] Determine how to feed a custom API endpoint into `content-build` before building and serving it
- [ ] Determine how to build `content-build` when the container starts consistently with the least amount of time and resources
- [ ] Verify that the methods used to configure the API endpoint in `content-build` produces consistent results

# Acceptance Criteria
- [ ] `content-build` routes traffic for API requests to a custom API endpoint
- [ ] The API endpoint argument is dynamically determined and passed into the preview environment backend from a GHA workflow

**Comment by CBonade** [comment]
Today i made a lot of progress on this and got it to a state where it's a working container. The unfortunate discovery, is that this method is slow (took almost 2 hours to boot up the docker container) so while this may run faster in argoCD, it's not likely to provide enough savings that will make this a viable production-ready solution.

I have one more piece to implement here before we merge this and test it in argoCD, but once that test is confirmed to not be viable, we will likely have to shift to another solution (thinking a singular docker-compose file).

**Comment by CBonade** [comment]
This code is merged and this task is completed.

**Comment by pjhill** [comment]
This is working in testing, nicely done!
