### ISSUE TITLE
After check in, user should not be able to go back to questions

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#58862]
## Description 

As a user, when I answer "Yes" to travel questions and complete check in, I should not be able to navigate back to travel questions and demo questions. I shouldn't be able to navigate to the questions from using "back" in the browser or using "back to last screen" page link. I shouldn't be able to re-visit check in and be shown the questions again. 

[Slack conversation](https://dsva.slack.com/archives/C022AC2STBM/p1684786585549189?thread_ts=1684347737.265739&cid=C022AC2STBM)

Video of desired functionality when travel questions aren't included:  

https://images.zenhubusercontent.com/133843125/3fed31ad-7bda-443d-8672-979cde7bb4ff/screen_recording_2023_05_22_at_4_35_25_pm.mov

## Tasks

- [ ] Update so that users can't navigate back to travel questions after check in 

## AC

- [ ] Users can't go back to travel questions after check in
- [ ] Users can't redo check in (authenticate again) and be able to view the questions again 
- [ ] Users can't go back to demo questions after check in, when travel questions aren't shown

**Comment by wullaski** [comment]
@benbrasso-agile6 what do you think about _removing_ the back button on the appointment list if check-in has been completed?

**Comment by benbrasso-agile6** [comment]
Right, in production, it's probably not there. But, if you have more than one appt, there is a link for "back to appointments." Then, on the appt list, the "back to last screen" appears, which then takes users back to the last screen that they were on, which would be the complete page. So, I think we just need to apply that to the travel workflow. For some reason it's not working like that with the travel questions appearing. 

Does that make sense?

**Comment by wullaski** [comment]
The back button has been removed and if a veteran tries to navigate back to the question pages either by changing the url or using the back button the app will redirect back to the appointment list view. This is ready to be validated @benbrasso-agile6

**Comment by loripusey** [comment]
validated
