### ISSUE TITLE
UX | Auth Exp | Logged-in IA and Nav | Discovery to identify where we can surface personalized information outside of My VA

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#58875]
## Background

As a next step in the logged-in IA and nav work, we're going to look into where it makes sense to surface personalized information outside of My VA, and get a better idea of technical feasibility/constraints we need to think about.

[This is the area of our mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684266228888/70e80eb031b0215679917698dc3abfcd74c76e03?wid=0-1684366379577) where we've started to gather some ideas.

## Tasks
- [x] Identify places on the site where it would make sense to experiment with this. This includes talking with content/IA folks, and looking into analytics for places in the benefit hubs where people are signing in frequently, or visiting while already signed in.
- [x] Learn about any technical considerations or constraints that could shape implementation. How would we implement this on the various pages we've identified?
- [x] Discuss with My VA product team
- [x] Share w/ Chante + Mikki
  

## Acceptance Criteria
- [x] We have identified places on VA.gov to surface personalized information

**Comment by andaleliz** [comment]
@mtcA6 fyi created this for sprint 11

**Comment by andaleliz** [comment]
[Started an outline here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/surfacing-personalized-content/README.md), capturing what I've learned so far about technical implementation

**Comment by andaleliz** [comment]
I've started to capture [some ideas here](https://docs.google.com/spreadsheets/d/1CVhhnWC3bRkHCMTXA8OrpDOwyZL-zRvm4E1sbRKFZDo/edit#gid=488402680), but after speaking with Mikki on Friday, these don't seem like promising leads. The "opportunity" on some of these pages only exists because the sign-in widget doesn't work correctly.

I regrouped with Berni on Friday; will have a discussion with team lead about how to move forward.

**Comment by andaleliz** [comment]
After a lot of back and forth on this, I'm ready to close this out. I've captured all the opportunities we've identified in [this doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/personalization-enhancements/opportunities.md).
