### ISSUE TITLE
Build a Proof of Concept using VA Notify/GA/Domo (part 2)

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#58879]
[Part 1](https://app.zenhub.com/workspaces/logingov-adoption-team-632280b31e745000136a61fc/issues/gh/department-of-veterans-affairs/va.gov-team/58442)

## Description
In the previous sprint, we conducted research and defined the scope of the reactivation proof of concept. 
[Mural here](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1684329312312/df1c36fc281d2e288446e9feb0603321e115525d?sender=uaaa67493ae613f0003928743)
To continue this work, we will build out the proof of concept. 

## Tasks
- [ ] Lorem

## Acceptance Criteria
 - [ ] Able to be triggered by logging in with a legacy account
 - [ ] Correctly assesses user's eligibility for reactivation campaign
 - [ ] Sends an email to a test user using VA Notify
 - [ ] Data from GA events (ie % of users who clicked the CTA in the email) is visualized in Domo
