### ISSUE TITLE
On-page survey for 4142 (post-production)

### ISSUE THREAD

**Issue by Nyanteea** [department-of-veterans-affairs/va.gov-team#58889]
This ticket to be modified for discovery around survey - does not need prototypes
Refinement pending discussions
Estimation pending discussion with contact center
 
## Issue Description
Research planning for creating intercept survey/feedback survey for 4142 pages within 526 and submitting request to contact center
---
## Tasks
- [ ] Draft questions for intercept survey
- [ ] submit the request for survey change to contact center 

## Acceptance Criteria
- [ ] Research plan
- [ ] ticket submitted to contact center
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lydiahooper** [comment]
Closing this ticket per Evelyn and I's discussion with Shannon on 9/22/23--We no longer have any plans for research specific to 4142 redesign
