### ISSUE TITLE
Document closed caption and transcript instructions for Zoom and YouTube

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#58896]
## User Story
As a Platform Orientation host, I want to know what steps to follow to ensure I am recording my orientation session correctly with closed captions and transcript so that VFS team members can view the video with closed captions and/or read through the transcript when taking the Platform orientation sessions. 

Assignee: @briandeconinck 
Peer Reviewer: @allison0034 

## Description
The recordings of the Platform Orientation sessions should be accessible and meet our own standards for publishing video content to the Platform Website/Youtube. This means that the videos should include closed captions, and a transcript of the recording should be available to anyone who requires it. 

In order to do this successfully, we must document the process Platform Orientation hosts must follow in Zoom while recording their orientation session, steps after the session has ended for capturing the transcript, and then the steps that must be followed for ensuring the video with closed captions and the transcript is uploaded to YouTube correctly.

## Impacted Artifacts
New draft document detailing the steps
- Draft [Orientation session captions, transcripts, and video upload](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2647523364/58896+-+Orientation+session+captions+transcripts+and+video+upload)

## Tasks
- [x] Run test Zoom call with captions enabled
- [x] Download test Zoom call files
- [x] Create draft documentation for setting up Zoom call, downloading files, cleaning up transcript, and uploading files
   - Draft [Orientation session captions, transcripts, and video upload](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2647523364/58896+-+Orientation+session+captions+transcripts+and+video+upload)

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have detailed instructions for recording a video with closed captions and transcript enabled
- [ ] We have detailed instructions for capturing the transcript and cc'd recording from Zoom
- [ ] We have detailed instructions for uploading the cc'd recording and transcript to YouTube

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
End of sprint status update: Draft documentation started but still in progress. Need to sync with Allison this week to do a quick test call and generate a sample Zoom transcript file.

**Comment by shiragoodman** [comment]
@briandeconinck please link the draft documentation within this ticket. Thank you!

**Comment by allison0034** [comment]
@briandeconinck this looks good, however I would rec just linking to Youtube's upload directions similar to what Platform website does. I believe it was done on purpose, if the directions change then we need to change our page, but if you only link to Youtube, if they change the directions they will update their page. What are your thoughts?

**Comment by briandeconinck** [comment]
@allison0034 I've removed as much as I feel like I can in favor of YouTube's upload instructions. They really bury the transcript instructions and I feel like most orientation hosts would benefit from the more explicit instructions I give. But I might be overthinking.

(Note that the page now also includes material for #58899.)

**Comment by allison0034** [comment]
@briandeconinck thank you! You can close : )
