### ISSUE TITLE
Design | Profile | Notification Settings | Update Sketch files to account for all use cases to add email as a channel 

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#58890]
## Background
We completed the collaboration cycle and are ready to move toward FE development. The sketch files already reflect the update from a radio button to a checkbox, but we now need to make sure the Sketch files reflect all the use cases for partial contact information.

## Tasks
- [x] Update link copy for updating/adding contact information, per [collab cycle feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/58790)
- [x] Make sure mock ups reflect partial contact information use cases

## Acceptance Criteria
- [x] Ready for FE development

**Comment by andaleliz** [comment]
@mtcA6 Leaving a comment here since I'll be out for the first half of planning. I removed the FE aspects of this ticket to make it just about design, since that's the first step. It's hard to accurately estimate tix if there are multiple practice areas involved.

**Comment by mtcA6** [comment]
> @mtcA6 Leaving a comment here since I'll be out for the first half of planning. I removed the FE aspects of this ticket to make it just about design, since that's the first step, and updated it to reflect all the updates we need to do to get FE done. I think it's best to keep FE and design tickets separate for more accurate estimation.

@andaleliz Gotchya, didn't see this before planning yesterday. In GH/ZH there are only epics and issues. On the call, I wanted to use this ticket as an example of how I'd like to, within the GH framework, operate more like it functions on JIRA. In JIRA, you have EPICS, Stories, and SubTasks. In this case, I wanted to write a story (GH epic) where we created the two SubTasks (GH issues) together. I understand for GH, this then would have functioned as an EPIC inside of an EPIC. I thought it would be a good exercise to gauge how you all felt about that, the ways we could create that linking/context and to see if there were any concerns. This may have already been happening, and in my current state as a novice I've not fully been able to trace the connections. 

In any event, I've created the corresponding FE ticket that goes along w/this one.

**Comment by andaleliz** [comment]
@adamwhitlock1 I'm thinking through a use case and am interested to get your thoughts:

We have launched the MHV notifications, and now have email as a channel. A user does not have health care, and so these new notifications (and email channels) are meaningless. Currently, we would not show the health care section to that person. I'm debating as to whether or not we should show them "**Email address:**  [address] Add to your profile" link at the top w/ their mobile number. 

<img width="220" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/55992116/2f2e6a67-1132-4cf1-ae3b-d58900f0adcd">

It'd be subtle, but I think it's a low key way to encourage them to add one to their profile, for future states when we have more email notifications beyond health care.

From a FE perspective, would it add more complexity to always show that, but NOT always show the "Want to add your email address" expandable alert? Since that expandable alert will contain a list of notifications they _could_ get, that would not make sense for someone without health care. 
<img width="428" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/55992116/d6dcf586-6461-4198-a9a6-3fc081e7a9eb">

**Comment by andaleliz** [comment]
@adamwhitlock1 wait, maybe we already talked about this? In [this draft](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-notification-preferences.md#draft-test-cases-to-account-for-when-we-add-email-as-a-channel) looks like I put that we'd show the `add info` link. Or possibly I just came up with that on my own and didn't share 😇

**Comment by andaleliz** [comment]
Awesome, thanks @adamwhitlock1 I appreciate your input.

**Comment by andaleliz** [comment]
@mtcA6 and @adamwhitlock1 these are all updated! All of them are linked in [this table](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-notification-preferences.md#draft-test-cases-to-account-for-when-we-add-email-as-a-channel).  I got a little cross-eyed adding those links in markdown, so hopefully I didn't miss anything.

There are a couple of outstanding questions, captured in #59721.  Two of them are content related so I don't think will impact FE since we get the notification channel and item names from the VA profile API.  But the outstanding one about Rx shipping emails has the potential for a lot of FE work, depending on the logic we have to account for.
