### ISSUE TITLE
Create operational guidance for orientation hosts

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#58899]
## User Story
As a Platform Orientation host, I want to know what steps I need to follow to ensure I am recording the orientation session correctly so that it can be uploaded to YouTube without any issue.

As a Platform Orientation host, I want to know what steps I need to follow to ensure I am uploading the recording of the orientation session to YouTube correctly so that it can be linked out correctly on Platform Website. 

As a Platform Orientation host, I want to know what steps I need to follow to ensure I am sharing the YouTube link correctly so VFS team members can view the recording as part of their Platform Orientation process.

Assignee: @briandeconinck 
Peer Reviewer: @sterkenburgsara @it-harrison 

## Description
It is the responsibility of Platform Orientation hosts and Zoom hosts to ensure that the Orientation session is recorded correctly, that the recorded meeting is uploaded to YouTube correctly and that the YouTube link is shared on Platform Website correctly. The purpose of this ticket is to document operational guidance for all hosts and Zoom hosts to follow so that we can ensure each orientation session is recorded, uploaded and shared consistently each quarter.

Refer to the existing guidance on [uploading videos. ](https://vfs.atlassian.net/wiki/spaces/AP/pages/1857060875/Embed+images+videos+and+GIFs+in+a+Platform+website+page)

## Impacted Artifacts
[Orientation Sessions](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2062024864/Orientation+Sessions)
[Roles and Responsibilities for Orientation hosts](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2595094717/Roles+and+Responsibilities+for+Orientation+hosts)
New page  - [Orientation Host/Zoom Host Guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2656731745/Orientation+Host+Zoom+Host+Guidance) 

- Directions for hosting and recording a live session (most of this should come directly from ticket #58896)
- Directions for sharing the recorded session on YouTube
- Directions for updating Platform Website/Orientation Sessions page

Draft documentation:
- [Roles and responsibilities for orientation hosts](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2673573899/58899+-+Roles+and+Responsibilities+for+Orientation+hosts)
- [Orientation Sessions (PPS)](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2673115151/58899+-+Orientation+Sessions+PPS)
- [Orientation Sessions (Platform website)](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2673147927/58899+-+Orientation+Sessions+Platform+Website)
- [Orientation Host/Zoom Host Guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2647523364/58896+58899+-+Orientation+Host+Zoom+Host+Guidance)

## Tasks
- [x] Document detailed instructions that the Zoom host and/or Orientation host can follow to complete the following 3 tasks in the new Orientation Host/Zoom Host Guidance page
1. hosting and recording a live session
2. sharing the recorded session on YouTube
3. updating Platform Website/Orientation Sessions page
- [x] instructions should also include preferred timeframe
- [x] Create a draft of the Orientation Sessions page, identify where changes need to be made to be brought up to par with the new guidelines and make the changes.
- [x] Create a draft of the Roles and Responsibilities for Orientation hosts page, identify where changes need to be made to be brought up to par with the new guidelines and make the changes.
   - Note: if you believe any of the 3 above pages could/should be merged, please make the proposed change and share with the peer reviewer for their input/feedback
 - [x] Once all changes are made, test the instructions with Ian Harrison (since he is the QA Orientation host). Ian will identify if there is anything unclear, confusing, duplicate steps and/or gaps.

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Platform Orientation hosts know the steps to follow to ensure the orientation session is recorded correctly.
- [ ] Platform Orientation hosts know the steps to follow to upload the recording of the orientation session to YouTube
- [ ] Platform Orientation hosts know the steps to follow to share haring the YouTube link correctly via Platform Website

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
@sterkenburgsara @it-harrison I think this is ready for review. The ticket suggests some pages could be merged. I haven't done that yet. My thinking is any clear redundancies should reveal themselves as you test.

Let me know if you want to do test-runs synchronously or asynchronously. I'm up for anything!

Draft documentation:
- [Roles and responsibilities for orientation hosts](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2673573899/58899+-+Roles+and+Responsibilities+for+Orientation+hosts)
- [Orientation Sessions (PPS)](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2673115151/58899+-+Orientation+Sessions+PPS)
- [Orientation Sessions (Platform website)](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2673147927/58899+-+Orientation+Sessions+Platform+Website)
- [Orientation Host/Zoom Host Guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2647523364/58896+58899+-+Orientation+Host+Zoom+Host+Guidance)

**Comment by it-harrison** [comment]
@briandeconinck looks great - made a few minor comments!

**Comment by shiragoodman** [comment]
I will set up a Zoom session for @it-harrison to test out the instructions.

**Comment by briandeconinck** [comment]
Question from sprint planning for @shiragoodman and @humancompanion-usds, related to #60597 and the visibility of the recorded orientation sessions.

YouTube has three options for [video privacy](https://support.google.com/youtube/answer/157177?hl=en&co=GENIE.Platform%3DDesktop):
- Public -- appears on the Platform channel, in YouTube search, could theoretically be promoted by the YouTube algorithm
- Unlisted -- anyone can view with a link, doesn't show up on the channel (unless we add them to a channel section manually), doesn't show up in search, algorithm ignores it
- Private -- doesn't appear anywhere, must be logged in and shared with you to view

If the solution for tracking whether people are attending orientation is [number of people attending live session] + [number of YouTube views], then it's possible (but unlikely!) that a public video's view count might get boosted by random people out in the world stumbling onto it. But the downside of making it unlisted would be it not showing up on the channel, and/or giving hosts an extra task to add it to a channel section.

This is almost certainly not going to be a real problem, but just in case it somehow is I'd love a clear ruling on video visibility for the host guidance. Public or Unlisted?

**Comment by humancompanion-usds** [comment]
Let's start off public. If we think the numbers look off or inflated we can move to unlisted.

**Comment by sterkenburgsara** [comment]
Okay, I am going to to stub out spots where instructions are slightly off from what I experienced: 

* Youtube Permissions
   * I think you may also need a step or line of content describing that you need to set up a new YouTube account with your work email address if you do not already have one. This will require responding to a pop-up that says "create channel" under your own name. If you are a new user you will also have to follow steps to be added to the Platform youtube channel, but your directions there were perfect and I was able to request access with and provide leadership with the necessary information (username and level of permissions needed) easily from your documentation. 
  
* Zoom Settings
   * Step 12 - I do not think this step exists - there is no "Save" button in Zoom for me, I believe any modifications auto-save.
   * I did have to restart my Zoom desktop client to have updated changes reflected (new features installed)

* During your orientation session
  * Step 1: Button in Zoom just says "Captions". Once you select that, a new sub-menu appears and you select "show captions" from there and select the appropriate language from a drop-down dialog box. 
  * Step 2-3: There is actually no "Record" option - I see two button options in the bottom toolbar: Record on this Computer or Record to the cloud. Could probably simplify this to one step.
 
* Tips for generating a good transcript
  * Can you move this before the section above? When testing these instructions, I had already hit "record" before I saw the useful tips. I think I'd want to see those tips first in practice when doing this live as an orientation host. 

* Uploading your recording and transcript to YouTube
  * Step 3b. Asks me to include an external link in the description. YouTube flags this for me and says I need to complete a one-time verification process in order to do this (but the Channel owner, not me, must be the one to do it). We may need to check with someone to enable that before external links will display. ![Screenshot 2023-06-23 at 1.47.45 PM.png](https://images.zenhubusercontent.com/6346cd7ec508fe43b65ae3db/1c2268f8-cc50-42e0-a3da-10912c5e5e3f) 
  * 6-7: for me these steps are inverted (After I select "upload file"  _then_ I see the pop-up box about Timing) 
  * 9: After this step, should add in an additional step to click the "Publish" button
 
**Note**: Someone on our team may want to have permissions to delete content if any of us mess up - in doing this as a test user I am unable to delete the dummy data that I just upload to the Platform YouTube channel. For now, I am setting the TEST video to private so at least it cannot be discovered publicly. 

Thanks, @briandeconinck . This was so much work and I figured it out, so bravo!

**Comment by briandeconinck** [comment]
@sterkenburgsara thank you for all of these edits! I've made all of the changes outlined, and changed the external links one to just read `More information about VA.gov Platform orientation is available on the Platform website.` We're not really looking to drive traffic from the videos to Platform website and anyone going through orientation should have gotten here *from* Platform website, so that seems like a fair placeholder description unless/until we decide something else should go there.

**Comment by briandeconinck** [comment]
@sterkenburgsara when you get a chance, could you do a quick review for the other impacted artifacts? If they look good I can go ahead and publish all of these so they're available for #60451

**Comment by sterkenburgsara** [comment]
@briandeconinck can you respond to pending comments on the confluence pages?

**Comment by sterkenburgsara** [comment]
@briandeconinck Orientation Host/Zoom Host Guidance looks great! This all matches my experience. Thanks for the updates.

**Comment by shiragoodman** [comment]
@briandeconinck I reviewed the instructions and everything is clear and easy to follow. Thank you so much for working on this - we are all very thankful for your diligence. 

The only doc that I have concerns about is the Roles & Responsibility doc. If you don't mind, I'd like to make some edits to it - not with the content, but the organization of the content. LMK if you have any concerns.

**Comment by briandeconinck** [comment]
All comments resolved and drafts have been published except for Platform website. Closing!
