### ISSUE TITLE
Copyedit for 2023 audit: Exposure through Project 112 or Project SHAD

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#58906]
## Issue Description
For the annual audit of all the pages in the disability hub, OCTO content lead assessed these 8 content issues on the [Exposure through Project 112 or Project SHAD](https://www.va.gov/disability/eligibility/hazardous-materials-exposure/project-112-shad/) page and made changes that need copyediting before we republish the page:

- The intro paragraph has no more than 2 to 4 sentences and is within 200 to 400 characters with spaces
- Header levels are hierarchical
- The page has no broken links
- Text links have purpose and target
- The content is free of ability-focused language (view, walk, see, hear)
- Relevant terms from page are in content brief and any relevant backlog work is noted
- Remove "Who's covered?" section (if needed)
- Remove "What kind of disability benefits can I get?" section (if needed)
- Revise "How do I get these benefits?" section: Rename to "How do I file a claim for compensation?"
- Change content in the above "How do I file...." section to this:
You can file a claim online now. You can also file by mail, in person, or with the help of a trained professional.
[Action link] File for disability compensation online
[Text link] Learn about other ways to file a disability compensation claim
You can also call the VA Special Issue Hotline at 800-749-8387. We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.
- Create new Q&A for guiding the user in how to get more information:
**How can I learn more about Project 112 or Project SHAD?**
If you were part of Project 112 or Project SHAD from 1962 to 1974 and want to know more about a certain test site, ship, or unit, check the declassified Defense Department fact sheets.
[Text link] Get declassified Defense Department fact sheets from Health.mil
You can also call the Defense Health Agency exposure information hotline at 800-497-6261 for any of these reasons:

- You want to know if you may have been part of the tests
- You have information that can help prove you were part of the tests
- You have other questions about the tests

---
## Tasks
- [ ] Copyedit the changes made (review revisions only, not the full page) to https://www.va.gov/disability/eligibility/hazardous-materials-exposure/project-112-shad/
- [ ] Publish page.

## Acceptance Criteria
- [ ] Updates are live on the site.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by megzehn** [comment]
Confirming I copy edited these changes! After I get through this next batch, I'll send them all over to the stakeholder for review before publishing. 

CC @bethpottsVADEPO

**Comment by megzehn** [comment]
Sent this over to Paul for review!

**Comment by bethpottsVADEPO** [comment]
@megzehn As we discussed recently, I'm going to start adding to the checklist to account for the reworking I'm doing (on every page) to the newly named "How do I file a claim for compensation?" section that has a new H2 label, new running text, an action link, etc. So I added 2 new bullets above in this ticket (sorry it's a little messy as I forget how to do sub-bullet in github to show that the 3 bullets are a part of the updated text on the webpage itself).

**Comment by megzehn** [comment]
Thanks, @bethpottsVADEPO! Confirming these changes have all been implemented on this page, reviewed by the SME, and published. 

I'll move this over to Github when I start working on #62134. Closing for now!
