### ISSUE TITLE
Determine access to veteran's existing clinical relationships via API 

### ISSUE THREAD

**Issue by carlosfelix2** [department-of-veterans-affairs/va.gov-team#58912]
## Issue Description
Explore weather Cerner provides a way for SM to access a list of veteran's clinical relationships.

## Details
Cerner has feature they developed for VA where we can know if a Veteran has an existing clinical relationship with a VA provider. For SM, we Cerner portal shows Veterans EVERY doctor across the DOD and VA systems in the dropdown for messaging. We would want to limit, or at a minimum sort, that list by those with whom Veterans have an existing clinical relationship.

---
## Tasks
- [ ] Determine if there is an existing API we can use to retrieve this list. Take into account the Millennium Messaging Web Services' endpoint to retrieve pools provides this functionality.

## Acceptance Criteria
- [ ] Document the findings on retrieving the relationship list.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by carlosfelix2** [comment]
Angela Chen: 
To Lauren's original question: the table in Millennium that holds clinician-patient relationships is PERSON_PRSNL_RELTN. According to the CDW-Mill Crosswalk, the CDWWork2 table is SVeteranMill.SPersonStaffMemberRelation.
If those are the same relationships that Lauren is referring to, the relationship is assigned each time a user (clinician or other user, e.g. front desk staff, IT staff) enters the patient's chart. Relationships in Cerner can be encounter-specific (common in inpatient setting) or lifetime (PCP, Care Coordinator, etc). If relationships are used for any messaging, one possible place to get it is CDW

**Comment by carlosfelix2** [comment]
We are waiting on information from Cerner. Rick Ross has an action to ask this question.
