### ISSUE TITLE
Display planned Network Maintenance banner msg on Debt Portal 

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#58919]
## Issue Description
We have been advised by Jill Anderson that there will be planned maintenance on the Debt Portal on Saturday, May 27, 2023 from 8am - 4pm CT.  We will need to post a message on the portal to notify Veterans.

---
## Tasks
- [ ] Post the message listed below on the Debt Portal website (https://www.va.gov/manage-va-debt/) anytime on Friday, 5/26/23 and also schedule for removal on Saturday, 5/27/23 at 4pm CT.

**We will be performing a scheduled maintenance on this site from 8:00 a.m. to 4:00 p.m. Central Time on Saturday, May 27, 2023. The website will not be available during this maintenance activity.  We apologize for any inconvenience this may cause.**

## Acceptance Criteria
- [ ] Message has been posted prior to the planned maintenance.
- [ ] Message has been removed post maintenance.
---

**Comment by Dr-Pongo** [comment]
[Coordinating with content to post message](https://dsva.slack.com/archives/C01K37HRUAH/p1685107585237949)

**Comment by Dr-Pongo** [comment]
Alert was posted for the weekend and has now been removed!
