### ISSUE TITLE
[Design] Notification Center: Static/empty state for Notifications on My VA

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#58921]
## Background
While working on designs for notification center MVP Angela raised a great point: while notifications don't live anywhere in the navigation (and possibly once they do), we might want to make the "Notifications" section of My VA static and have a link to all notifications and an empty state. Otherwise a user wouldn't have a way to see all notifications if they had dismissed all onsite notifications from My VA and wherever else they may end up living throughout the site. 

## Tasks
- [x] Work through some design options for a static/empty state for the Notifications section on My VA
- [x] Review with team

## Acceptance Criteria
- [x] We have some design options for an every present notifications section on My VA

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ Designs are available for review in sketch

**Comment by aagosto90** [comment]
[Design for empty state](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/960F9081-F6CB-4DBC-9860-7DA92147A555)
