### ISSUE TITLE
Modifications to Platform Orientation section of Platform Website

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#58924]
## User Story
As a VFS team member, I want to easily locate the recording of the orientation session as well as the sign-up for Calendly so that I can attend the session in person or view the recording on my own time.

Assignee: @CherylEvans 
Peer Reviewer: @sterkenburgsara 

## Description
With the release of the quarterly orientation session recordings, we will need to ensure the Platform Website is updated to reflect the change in process. The purpose of this ticket is to audit the Platform Orientation pages on Platform Website, identify where changes need to occur and create drafts of the modified pages.

**Note**: since the recordings haven't happened yet and we have not gone live with VFS teams, this ticket can be closed when the draft PW are finalized. Do not publish the pages to Platform Website. 

## Impacted Artifacts
- [Platform Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-orientation)
- [Guidance for new teams and team members](https://depo-platform-documentation.scrollhelp.site/getting-started/guidance-for-new-teams-and-team-members)
- [Orientation Sessions](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions)

## Tasks
- [x] Review the Platform Orientation pages on Platform Website and identify anywhere we state "attend" or "sign-up" related to the orientation sessions
- [x] Ensure all impacted pages are captured in the Impacted Artifacts section above
- [x] Create draft pages of all Impacted Artifacts and store in a #58924 folder within Documentation Drafts
- [x] On the Orientation Sessions page, the section for each orientation session should include a new option to view the latest recording via YouTube

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS teams are able to access the new YouTube recordings via the Platform Website/Orientation Sessions page
- [x] Guidance to VFS teams re: the orientation sessions is consistent across all Platform Orientation pages on PW

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
Drafts created in Governance team, documentation drafts, space.
58924 - [Guidance for new teams and team members](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2648866826/58924+Draft+-+Copy+of+Guidance+for+new+teams+and+team+members)
58924 - [Orientation Sessions](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2648866848/58924+Draft+-+Copy+of+Orientation+Sessions)
58924 - [Platform Orientation](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2648965121/58924+Draft+-+Copy+of+Platform+Orientation)

**Comment by CherylEvans** [comment]
@sterkenburgsara Ready for your peer review! :-)

**Comment by sterkenburgsara** [comment]
@CherylEvans @shiragoodman is it correct that we will not be doing synchronous sessions anymore with the availability of async? If so, should we also update language in the user flow graphic where it says to "sign up for platform orientation meetings via Calendly" in any way?

**Comment by sterkenburgsara** [comment]
@CherylEvans I like this a lot! "Check out the latest recorded session via YouTube" is a bit long, but I think it is clear. No edits to any of your language - just waiting for response to question above. Great job!

**Comment by CherylEvans** [comment]
@sterkenburgsara Thank you, Sara! I avoid using "sighted" (look, view, see)  language whenever possible. I also thought "Check Out" sounded kind of intriguing and fun. Thanks again for your thoughtful response! :-)

**Comment by CherylEvans** [comment]
@sterkenburgsara I'm going to go ahead and close this ticket if that's cool with you. :-)

**Comment by shiragoodman** [comment]
@CherylEvans I provided some comments in the drafts. Please review.

**Comment by CherylEvans** [comment]
@shiragoodman, Can you modify the User Flow for Draft Guidance for new teams and team members? That is the only thing I need to close this ticket. Thank you!

**Comment by shiragoodman** [comment]
@CherylEvans modified user flow added to https://vfs.atlassian.net/wiki/spaces/PPST/pages/2648866826/58924+Draft+-+Copy+of+Guidance+for+new+teams+and+team+members
