### ISSUE TITLE
Requests from Other Teams for Data from Contact Center 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#58931]
## Issue Description
Need to create a template for other teams to request data from Contact Center.  

---
## Tasks
- [ ] Design template 
- [ ] Determine what data can be requested 
- [ ] Check with @chante for existing template

## Acceptance Criteria
- [ ] complete process of requesting and delivering information to teams that request information from the Contact Center  
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by starlow00** [comment]
Duplicate, closing
