### ISSUE TITLE
Requests from Other Teams for Data from Contact Center 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#58930]
## Issue Description
Need to create a template for other teams to request data from Contact Center.  

---
## Tasks
- [x] Design template 
- [x] Determine what data can be requested 
- [x] Check with @chante for existing template

## Acceptance Criteria
- [x] complete process of requesting and delivering information to teams that request information from the Contact Center  
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
**Information Type Requested**


**Date Range Start**


**Date Range End**


**Product/Tool Name(s)**

**Request Description**


**Product/Tool term(s)**


**File Delivery Format**


**VA Email Address(es)**


**Add Assignee and Labels**
If not already done so, please ensure @Kimberley2019 is set as the assignee for this issue and "VSP-contact-center" and "cc-RFI-request" are set as labels.
Please leave this field as is when submitting.

**Comment by Kimberley2019** [comment]
I have the fields determined and will gather feedback with @clantosswett during our sync on 6/6/23 to determine if any additional fields should be included. 
Also reached out to Ian for assistance on how to create template for RFI.

This will be complete by EOS.

**Comment by Kimberley2019** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/request-for-information-contact-center

**Comment by ATMiddleton** [comment]
@Kimberley2019 will update the file to reflect a YML file.

**Comment by Kimberley2019** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Kimberley2019%2C+ATMiddleton&labels=VSP-contact-center%2Crequest-for-information-cc&projects=&template=request-for-information-contact-center.yml&title=Request+for+Information+%28RFI%29
