### ISSUE TITLE
[BE] Investigate MHV 400 errors

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#5893]
## Background

according to eric robertson MHV endpoint https://essapi.myhealth.va.gov/mhv-api/patient/v1/session is returning a lot of 400 errors, investigate to see where this endpoint is used and if it's a login or auth exp issue

## Tasks

- [x] Figure out where we're calling this endpoint to see what part of the code is using it
- [x] Determine next steps for fixing the bug, OR pass off to platform team if it's a login issue

## Acceptance criteria

- [x] Next steps have been determined
