### ISSUE TITLE
Copyedit for 2023 audit: VA disability compensation for PTSD

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#58939]
## Issue Description
For the annual audit of all the pages in the disability hub, OCTO content lead assessed these 8 content issues on the [VA disability compensation for PTSD](https://www.va.gov/disability/eligibility/ptsd/) page and made changes that need copyediting before we republish the page:

- The intro paragraph has no more than 2 to 4 sentences and is within 200 to 400 characters with spaces
- Header levels are hierarchical
- The page has no broken links
- Text links have purpose and target
- The content is free of ability-focused language (view, walk, see, hear)
- Relevant terms from page are in content brief and any relevant backlog work is noted
- Remove "Who's covered?" section (if needed)
- Remove "What kind of disability benefits can I get?" section (if needed)

---
## Tasks
- [x] Copyedit the changes made (review revisions only, not the full page) to https://www.va.gov/disability/eligibility/ptsd/
- [ ] Publish page.

## Acceptance Criteria
- [ ] Updates are live on the site.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by megzehn** [comment]
Confirming I copy edited this page against this check list. 

CC @bethpottsVADEPO

**Comment by megzehn** [comment]
Sent this over to Paul for review!

**Comment by megzehn** [comment]
Update: I made the minor change that Paul requested and Beth reviewed. The updated page is published.

**Comment by megzehn** [comment]
Re-opening for a small bit of new work that came up: Copy edit the "How do I file" section

**Comment by megzehn** [comment]
I reviewed the updated work and published the page again. Moving over to validate!
