### ISSUE TITLE
Understanding AuthN/AuthZ use cases

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#58948]
## Description
As part of the epic to implement Authentication & Authorization for Preview Environments, this story ticket focuses on understanding the desired user flows and technical requirements. We need to gather as much information as possible from our user diagram and technical stakeholders to ensure we build an effective Authentication & Authorization system.

---
## Tasks
- [x] Define key roles and permissions for the system.
- [x] Document typical user journeys for each identified role.
- [x] Gather technical requirements from devops-cop.
- [x] Review current Authentication & Authorization practices, if any, and identify areas for improvement.
- [x] Document the gathered information and prepare a report.

## Acceptance Criteria
- [x] Documentation of identified roles and permissions.
- [x] Definition and documentation of user journeys for each role.
- [x] Provide a diagram of current pull request event
- [x] Identify appropriate step in the PR event for raising authentication choice to user
- [x] Documentation of current Authentication & Authorization practices, if any, and identification of areas for improvement.
- [x] A report summarizing all the findings and insights.

**Comment by pjhill** [comment]
@gia-lexa -- It looks like that Miro link is incorrect. Thanks for all these updates! When you get a chance would you update that Miro link, please?
