### ISSUE TITLE
Testing/ Merging to main of Yarn Workspaces for lgy team

### ISSUE THREAD

**Issue by rmessina1010** [department-of-veterans-affairs/va.gov-team#58941]
## Description
This is ticket finishes the installation  of yarn workspaces in lgy, pending the aforementioned team's testing and approval. All other tasks have been completed  and branch has been synched.  As per SOP, this branch must be merged  to main  in 30 days  or it will be considered stale.

Original issue: https://app.zenhub.com/workspaces/frontend-cop-backlog-6452b043f27c8b0011a25236/issues/gh/department-of-veterans-affairs/va.gov-team/47415

## Testing done
- [x] Confirm demo scripts run
- [x] Confirm sym link in root  `node_modules` folder is present after  yarn install
- [x] Unit/e2e
- [x]  resynched  branch with main.
- [ ] Visual Web Test:  link  pending 

## Tasks For lgy team to do
- [ ]  Check dependencies/devDependecies / peerDependencies are correct for your app
- [ ]  If required, add` nohoist`  dependencies to root `package.json`
- [ ]  If required , add scripts
- [ ]   Visual Test  link pending
- [ ]  Approve PR

### TEST PLAN
https://docs.google.com/spreadsheets/d/1un1NG-wrYSPQbHSq6BxEpc3g02IjUQPOZg_3ni5qvdg/edit#gid=0

Docs:
https://depo-platform-documentation.scrollhelp.site/developer-docs/guide-for-maintainers-overview
(Please note that as a VSF app, you don't have any exports (or need an exportsFile.js)

## Acceptance criteria
- [ ] Testing done completed
- [ ]  Tasks For check-in team to do

**Comment by CBonade** [comment]
Awaiting communication from VFS team member to continue. per @rmessina1010

**Comment by rmessina1010** [comment]
lgy,  reviewed work but opted NOT  to have yarn workspaces installed. Closing.
