### ISSUE TITLE
Create Identity Dashboard ClientConfig & ServiceAccountConfig in vets-api development environment

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#58968]
# Description

We need client configurations in the Sign in Service to enable the Identity Dashboard. Configurations should be created for both the end user authentication/PKCE flow (`ClientConfig`) that comes from the Identity Dashboard frontend, as well as for the API-to-API authentication using private JWT from the Identity Dashboard backend (`ServiceAccountConfig`).

# Tasks

## User Authentication / PKCE 

- [x] add user authentication client config to default localhost SiS (`development.rb` file)
- [x] add user authentication client config for development SiS (manual change)

```
{ client_id: "identity_dashboard",
  authentication: "cookie",
  anti_csrf: true,
  redirect_uri: "http://{localhost/dev}/auth/login/callback",
  access_token_duration: 5.minutes,
  access_token_audience: "identity_dashboard",
  refresh_token_duration: 30.minutes,
  logout_redirect_uri: "http://{localhost/dev frontend}",
  pkce: true }
```

## API Authentication / Service Account Config

- [x] add Service Account Config to default localhost SiS (`development.rb` file)
- [x] add Service Account Config for development SiS (manual change)
  - Identity Dashboard public certificate can be found at `'spec/fixtures/sign_in/identity_dashboard_service_account.crt'` in vets-api

```
{ service_account_id: "01b8ebaac5215f84640ade756b645f28",
  description: 'VA Identity Dashboard API',
  anti_csrf: true,
  scopes: ['https://dev-api.va.gov/sign_in/client_configs'],
  access_token_audience: 'http://identity-dashboard-api-dev.vfs.va.gov',
  access_token_duration: 5.minutes,
  certificates: <public certificate>}
```

**Comment by bramleyjl** [comment]
https://dsva.slack.com/archives/C04LW2P19M0/p1686333151192009

**Comment by bramleyjl** [comment]
SiS authentication is functional on https://identity-dashboard-dev.vfs.va.gov/, closing this.
