### ISSUE TITLE
Sign in Service Account/Application `/token` route

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#58964]
# Description
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Sign-In%20Service/Components/Service_Accounts.md

Identity Dashboard backend will need to communicate both to Sign in Service and Vets-Api backends. This will be actions performed on behalf of an authenticated user, but must only be allowed as a direct call from the identity dashboard backend (these actions should not be allowed, even from an authenticated user, to be called directly from a frontend). We need to discover and implement a protocol that will allow for secure connection between the identity dashboard backend and Sign in Service/Vets-api backends. The proposed protocol will likely involve the creation of a private key on the Identity Dashboard backend, which will then be confirmed by the Sign in Service / Vets-api backends before processing these protected routes

## Examples of routes that must be protected in this way:
- Client Config read/edit from Sign in Service
- MPI find by ICN

# Tasks
- [x] create `account_configs` table
- [x] add `SignInService::AccountConfig` model to persist User/Application specific permissions
  - [x] fields:
    - `account_id`
    - `scope`
    - `description`
    - `access_token_audience`
    - `certificates`
- [x] add `/token` handling for a new grant type: `urn:ietf:params:oauth:grant-type:jwt-bearer`
  - [x] assertion is a `private_key_jwt`
    - [x] fields:
      - `iss`
      - `scope`
      - `aud`
      - `exp`
      - `iat`
      - `sub`
      - `account_id`
      - `jti`
    - [x] validations: signed against AccountConfig public cert, not expired, permissions are <= AccountConfig scope
  - [x] return a 5 minute access token, do not create other tokens
    - [x] access token fields
      - `iss`
      - `aud`
      - `jti`
      - `sub`
      - `exp`
      - `iat`
      - `version`
      - `scope`
  - [x] do not create a session

**Comment by bosawt** [comment]
This protocol will leverage the existing Sign in Service private_key_jwt flow to allow applications themselves to integrate with sign in service as a client and a user.  

Once set up, the applications will call Sign in Service with: 
`/token&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer&assertion=<private_key_jwt>`
Sign in Service will then return the request with a proper `access token` (no `refresh token`, and no session will be set up, since the access token alone will represent the 'session' here)

**Comment by bosawt** [comment]
I also wrote this in a message in slack, figured I'd reproduce it here:

So just to put down the decision, communications between identity-dashboard backend and sign in service will be facilitated by a new type of Sign in Service connection that facilitates ‘Service Accounts’ connections. This will leverage a flow in sign in service similar to the private key jwt flow, except the /authorize step is skipped entirely here.
A known backend will call sign in service with:
/token&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer&assertion=<private_key_jwt>
 sign in service will return with an access token with an expiration of 5 minutes
sign in service won’t create a session or return other types of tokens for this type of connection
Each application will determine what applications it accepts with this system to system authentication. To do this, when an application verifies an access token, it will be able to inspect a specific field to see what application the access token is authenticated as
There will not be any scopes initially. This means applications will authenticate for access to all permissions and applications they have access to. If we expand this functionality we can consider the use of scopes

**Comment by bosawt** [comment]
We've documented the ultimate plan for this here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Sign-In%20Service/Components/Service_Accounts.md

**Comment by bramleyjl** [comment]
Service Account Access Token documentation: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsp/teams/Identity/Sign%20In%20Service/Service_Account_Authentication.md

**Comment by aparsley** [comment]
Thank you for attaching artifacts for review.
