### ISSUE TITLE
[eFSR] aria labeling mini summary cards 

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#58973]
## Issue Description

> Vehicle Summary Page Remove index number from aria-label for vehicle mini-summary page edit/delete buttons; it's confusing from a screen reader standpoint to read Edit 1989 BMW 325ix 0 or Edit 2004 Honda Accord 1 Saw that the index was added to prevent confusion if there were dupes, but it reads strangely to have a number.

Let's try having the aria label as `Vehicle <index + 1>, <name of vehicle>`. This will be helpful because it will include a unique index and the name of the vehicle so it's easily identifiable to screen readers. Check and see if we can add this to delete button and maybe the title of the card as well for clarification?

The similar labeling may be applicable to `Employment History` (veteran & spouse), `Credit Cards`, and `Installment Contracts`.

[Parent functionality ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/55628)

---
## Tasks
- [x] Update `aria-label` for Vehicle Summary card components.
- [x] Investigate & include if fix will be applicable to other Summary pages. 

## Acceptance Criteria
- [x] Mini Summary card components have clear aria labeling
- [x] All tests passing.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
