### ISSUE TITLE
[eFSR] Navigation content update

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#58975]
## Issue Description

> Back and continue buttons aren't showing anymore when you add an initial employment history or vehicle. Seems like this is happening on all the pages. Not sure if the functionality changed or not.
[Functionality parent ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/55628)

The first page instance of adding a new `Vehicle`, `Credit Card`, or `Installment Contract` navigation buttons should read `Back` and `Continue`. 

We'll likely need clarification from Design on content for adding employment as it is multiple pages. 

---
## Tasks
- [x] Update conditional button text for the following pages:
  - [x] Vehicle
  - [x] Credit Card
  - [x] Installment Contract

## Acceptance Criteria
- [ ] Page navigation buttons for adding first instance of `Vehicle`, `Credit Card`, or `Installment Contract` use text `Back` and `Continue`
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
Sliding into 102 since other higher priorities came up

**Comment by HeatherRienks** [comment]
This ticket will rollover; focus has been on FSR launch.

**Comment by HeatherRienks** [comment]
Moving back to Ready until SW is completed.
