### ISSUE TITLE
[eFSR] Employment History required not triggering error 

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#58974]
## Issue Description
> Required label on Employer Name doesn't trigger error when you click the Add Employment Record button, can skip it even though it's a required field.

[Parent functionality ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/55628)

---
## Tasks
- [ ] Prevent user from continuing if Employer Name is not filled out
- [ ] Investigate if issues is also on Spouse Employment and fix.

## Acceptance Criteria
- [ ] Not completing required field triggers error and prevents navigation. 
- [ ] All tests passing
  - [ ] e2e
  - [ ] unit
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by josephrlee** [comment]
Additional info for this bug, the required dates don't trigger an error. Attached is a link to a Loom showing the issue better. https://www.loom.com/share/d6a0b164e4974b92963ff3c5ce0f96d3

**Comment by josephrlee** [comment]
Also noticed that if you check payroll deductions, you can still skip filling out the inputs, this is happening for the spouse one as well:![Screenshot 2023-06-05 at 3.23.34 PM.png](https://images.zenhubusercontent.com/63ea96045c6deec1c9a25425/c556441f-893b-46bd-80b9-4a73528a8ad4)

**Comment by OptionSelect** [comment]
Work for this is complete and part of 57342.
