### ISSUE TITLE
[eFSR] Bug - Investigate submission issues during testing 

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#58979]
## Issue Description
> Exploration: Two mobile users were unable to submit form using eFSR.

[Parent Functionality Ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/55628)

I think FE & BE already touched on this a bit, but there seems to be some issues with veterans submitting the form in the new flow on prod (issue doesn't appear to happen on staging?). Contact Information could be root cause (not enough/too many fields on address?).

---
## Tasks
- [x] Investigate user session testing issues. 
- [x] Resolve Issue or create appropriately sized ticket to handle. 

## Acceptance Criteria
- [x] Issue is resolved or ticket is created. 
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by amponce** [comment]
During user testing we had some issues with form submission.

**Sentry**:` http://sentry.vfs.va.gov/organizations/vsp/issues/205378/events/?environment=production&project=3&statsPeriod=14d`

**Error**: `NoMethodError: undefined method `empty?' for nil:NilClass `

**Investigate**: Address field in contact to ensure all of the required submit data is being passed to the server

```
address_fields = %w[
          addresslineOne
          addresslineTwo
          addresslineThree
          city
          stateOrProvince
          zipOrPostalCode
          countryName
]
```

**Comment by amponce** [comment]
Resolved issue by passing addressLineTwo with and empty string in the data transform

`addresslineTwo: enhancedFSRActive ? address.addressLine2 || '' : street2,`
