### ISSUE TITLE
[eFSR] Bug - Add Credit Card Bill cancel button

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#58977]
## Issue Description
> Add a credit card bill Tried to add credit card bill (clicked cancel like it wasn't going to be added; and went to a blank screen).

[Parent Functionality Ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/55628)

Cancel (back) button on adding first Credit Card bill should take the user back to the radio button question, and Mini Summary page should be able to display if length of list is zero (blank screen is page rendering but not map in component). 

Investigate to see if this issues also applies to similar pages (`Vehicle`, `Installment Contracts`)

---
## Tasks
- [x] Update Cancel (back) navigation from first instance of new Credit Card Bill.
- [x] Confirm Credit Card Bill mini summary page can handle empty list. 
- [x] Confirm issue doesn't exist on related pages..

## Acceptance Criteria
- [x] Credit Card page navigation functions as anticipated.
- [x] All tests passing
  - [x] e2e
  - [x] unit
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by amponce** [comment]
@HeatherRienks , this ticket turned out to be more like a 3 pointer:

Along with the cancel button bug, @Dr-Pongo  identified an analytics issue occurring with credit card bills and installment contracts. We then found problems with navigation related to deleting items and attempting to add items back in. I also managed to take care of some cleanup tasks and added PropTypes to resolve ESLint issues. Here is the [finished PR](https://github.com/department-of-veterans-affairs/vets-website/pull/24446). I'll be merging shortly 🚀
