### ISSUE TITLE
[eFSR] Bug - Veteran Benefits Summary page NaN 

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#58978]
## Issue Description
>Exploration: NaN is appearing on mobile (Example: Veteran Benefits Summary page).

[Parent Functionality Ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/55628)

---
## Tasks
- [x] Investigate NaN appearing on Veteran Benefits Summary Page
- [x] Fix issues causing NaN to appear. 
- [x] Investigate if the issue applies to other pages. 

## Acceptance Criteria
- [x] NaN no longer able to appear on Veteran Benefits Summary Page (or elsewhere)
- [x] All tests passing
  - [x] e2e 
  - [x] unit
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
`NaN` was appearing due to `&&` operator conditionally rendering the card and not appearing in the "Amount received last month: " section. 
Including screenshot of NaN that was appearing:
![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/2d054ef8-a6bf-4daa-86c1-39bfc6581b42)
