### ISSUE TITLE
Fix link in DST Staging Review template

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#58983]
## User Story
As a DST team member, I want to follow the correct guidance for scheduling a staging review so that I know I have done it correctly. 

Assignee: @CherylEvans 
Peer Reviewer: @briandeconinck 

## Description
The Staging Review Guidance link in the DST Staging Review template (not an issue template, but a code block in the 
[ How to Request a Design System Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572124196/How+to+Request+a+Design+System+Staging+Review) Confluence page) links out to the Platform Website. This link should either refer back to the Confluence guidance, or be deleted. We should not be directing DST to the SR guidance on PW as it is not applicable for their team.

## Impacted Artifacts
[ How to Request a Design System Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572124196/How+to+Request+a+Design+System+Staging+Review) 

## Tasks
- [x] Remove the Platform Website link and replace with the DST Confluence link

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] DST is directed to the correct Staging Review guidance

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
@CherylEvans This looks good! Thanks for your patience waiting on me!

**Comment by CherylEvans** [comment]
@briandeconinck Thank you so much for your review! :-)
