### ISSUE TITLE
[eFSR] Bug - Required Field Spouse Employment history monthly income 

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#58981]
## Issue Description
>Spouse employment > Monthly income question Required field doesn't work, can press continue without filling out the field.

[Parent Functionality Ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/55628)

Veteran employment history appears to be working, so functionality may need to be lifted.

---
## Tasks
- [ ] Fix Required Field for Spouse gross monthly income. 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by OptionSelect** [comment]
Per Andrew review bumping to 3.
https://github.com/department-of-veterans-affairs/vets-website/pull/24346#issuecomment-1581146036

**Comment by OptionSelect** [comment]
This ticket also encompasses related fixes for required fields from https://github.com/department-of-veterans-affairs/vets-website/pull/24346. The main 3 are the date not preventing moving forward, gmi and deduction list doing the same.

**Comment by josephrlee** [comment]
@OptionSelect, I was able to get the SpouseGrossMonthlyIncome component and the GrossMonthlyIncome component working. I'll need help with the Deduction lists for both Spouse and the Veteran one.
