### ISSUE TITLE
Add eyebrow to check-in question pages

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#58989]
## Description 

Based on (consistent) feedback from platform, most recently during unified check-in midpoint review, we should consider adding the eyebrow to check-in question pages, which includes pre-reg, travel and the appointments list. 

Feedback from IA during unified check-in midpoint review: 

> The travel reimbursement claim questions don't end with a summary review page or a submit button, so it felt unclear to me that this was the end of that form flow when I completed it on staging. Your user research seems to indicate that Veterans did not have any problems, but consider poking at that a bit when you user test the happy path for the full check-in flow.

> Being dropped from the travel questions to the appointments page is jarring. The travel questions never reach a resolution before you shift gears into checking in. Some additional content/messaging on the appointments page could reassure the user that they'll get a status update on their claim after they proceed to check-in. Targeted usability testing around the task separation there (5/5 of us on governance team were confused) could also be beneficial. But again, if research participants are not confused by that, it may not be an issue.

> I love the "eyebrow" addition - a mini-header like that on the relevant sections of the pre check-in & check-in flow could help reduce the user confusion I experienced above & further clarify that the travel questions are part of the check-in flow.

## Tasks

[Abstract branch](https://share.goabstract.com/6b69924f-904b-4d78-b5a1-4c40ed65e4d2) 

- [X] Implement feedback from Matt Dingee - look at serif vs. sans serif and ensure it meets color contrast standards
- [ ] Create final wireframes for question pages - pre-reg, travel and appointments list
- [ ] Add annotation for what markup looks like for supporting screen readers

## AC

- [ ] Final wireframes created
- [ ] Merge up into travel branch in Abstract
- [ ] Create ticket for FE

**Comment by benbrasso-agile6** [comment]
@ytsaoca this should be prioritized this sprint please!

**Comment by ytsaoca** [comment]
Will do. Thank you!

**Comment by benbrasso-agile6** [comment]
LGTM 

Adding @zach-park to merge it up into the travel pay branch

**Comment by zach-park** [comment]
The eyebrow branch is merged into the main. And new wireframes are added to the main collections.

**Comment by benbrasso-agile6** [comment]
Just remembered, we need to give some instructions to FE about the h1 markup. @cgednalske
