### ISSUE TITLE
[eFSR] Contact information mobile number extension 

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#58980]
## Issue Description
> Contact info > Edit phone number Remove extension field

[Parent Functionality Ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/55628)

Edit Mobile phone page is actually handled by `ProfileInformationFieldController`, so we can't update it without diving into profile source, so suggestion from Rob was to use css to hide `extension` field. 

---
## Tasks
- [x] hide `extension` field on edit mobile number page. 

## Acceptance Criteria
- [x] `extension` field no longer visible on edit mobile number page. 
- [x] all tests passing
  - [x] e2e
  - [x] unit
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
