### ISSUE TITLE
Switch to need help component

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#58991]
## Description 

Switch to [need help component](https://design.va.gov/components/form/need-help). 

## Tasks

- [ ] Switch all artboards to use the [need help component](https://design.va.gov/components/form/need-help)
- [ ] Check symbols

## AC

- [ ] Final wireframes created
- [ ] Merge up into travel branch in Abstract

Note: This ticket has a FE ticket already - https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/59166

**Comment by zach-park** [comment]
Hi @benbrasso-agile6 , A quick question about this ticket: Would we need to update the Travel pay main branch and/or all PCI/CI master files? Thank you!

**Comment by benbrasso-agile6** [comment]
I would updated all (travel branch and main branch) of the need help for just check-in (not pre-check-in). We can update pre-check-in later. 

Is that easiest? What do you think?

**Comment by ytsaoca** [comment]
I'll work on the travel branch first.

**Comment by ytsaoca** [comment]
I'll work on the travel branch first.

**Comment by zach-park** [comment]
This ticket is transferred to Ya-ching.

**Comment by loripusey** [comment]
no longer needed, closing
