### ISSUE TITLE
Switch to need help component

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#58993]
## Description 

Switch to [need help component](https://design.va.gov/components/form/need-help). 

## Tasks

- [x] Switch all artboards to use the [need help component](https://design.va.gov/components/form/need-help)
- [x] Check symbols
- [x] Check annotations
- [x] Tag Christina to update in CodePen

## AC

- [x] Final wireframes created
- [ ] Updated in CodePen
- [ ] Create ticket for FE

**Comment by zach-park** [comment]
@benbrasso-agile6 @cgednalske , the ticket is ready for review. For Christina, please note that the spacing between the body text and the VA footer (32px vertical spacing) is updated due to the symbol update.

**Comment by benbrasso-agile6** [comment]
Looks good. I actually don't think we need to update in CodePen.

**Comment by benbrasso-agile6** [comment]
FE https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/59166
