### ISSUE TITLE
Change warning and success alerts to default alert style

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#59007]
## Description 

Use the [default alert style](https://design.va.gov/components/alert#warning-alert) for the warning alerts. Background only alerts are for immediate feedback only.

Change all warning and success alerts to default alert style

DO NOT change the following yet (because we'll tackle them in a different ticket): 

- Informational alerts
- Check-in confirmation pages

## Tasks

- [x] Switch all warning and success alerts to [default alert style](https://design.va.gov/components/alert#warning-alert) (not including check-in confirmation pages)  
- [x] Check and symbols
- [x] Check and update annotations

## AC

- [x] Final wireframes created
- [ ] Create ticket for FE

**Comment by zach-park** [comment]
@benbrasso-agile6 , the ticket is ready for validation. Thank you!

**Comment by benbrasso-agile6** [comment]
Validated

No FE ticket. I'm going to create the needed FE tickets off of different ticket being worked on.
