### ISSUE TITLE
Prod launch of first pass of 526 Paper Sync

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#59003]
## Issue Description
Prep for release of first pass of 526 paper sync into production

## Tasks
- Remove all environment checks that kept the changes confined to non-prod environments
- Delete any components that should be removed and their associated tests

## Acceptance Criteria
- [ ] Environment checks are removed
- [ ] Unit, e2e and manual tests are successful
- [ ] Changes are deployed to prod

**Comment by RakshindaAslam** [comment]
cc @RakshindaAslam - add blocked by the collab cycle staging review
cc @christinec-fftc

**Comment by RakshindaAslam** [comment]
@christinec-fftc - do we have a date for this launch yet?

**Comment by christinec-fftc** [comment]
Changes merged afternoon of 8/8/23. Typically this would have deployed the following day, but due to an un related additional deploy, it went out late evening of 8/8/23
