### ISSUE TITLE
Set up ongoing marketing communications for the Portal

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#59015]
## Purpose
Set up the decided upon modes for marketing the portal in an ongoing way

[Prework
](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2637758599/Ongoing+Marketing+for+the+Portal)

## Tasks
- [x] Test Slackbot /reminder in private channel
- [x] Step though Launch [checklist](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2658074913/Portal+Marketing+Launch+Checklist)
- [x] Confirm ToT slide is updated

## Acceptance Criteria
- [x] Setup of /reminder is complete
- [x] ToT slide is updated

**Comment by tayism** [comment]
Picked this up early. Will roll over to next sprint (where it is originally assigned)
