### ISSUE TITLE
[DISCOVERY] Vet Centers

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#5902]
## High Level User Story
As the Facilities Team, we need to understand the services provided at Vet Centers so we can build pages to display information about them that are meaningful to our users. 

## Goals
- To build a foundation for understanding Vet Centers in preparation for future conversations with SMEs and research sessions with Veterans
- Begin to validate [assumptions](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/vet-centers#assumptions-and-early-discussions) and [Andy's product plan](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/vet-centers#what-we-need-to-do)
   - Consider what we have learned from the VAMCs since Andy's plan was created

## Tasks
- [ ] Review user research done for the Pittsburgh pilot for user feedback which apply to Vet Centers and/or PTSD/SUD
- [ ] Review content available on [Vet Centers](https://www.vetcenter.va.gov/)
- [ ] Review contents of Design and Taxonomy folders in [Vet Centers](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/vet-centers)
- [ ] Work with Vet Center Central Office to validate the existing list of services

## Output
[ ] Begin to document/validate understanding about the services offered at Vet Centers: 

1. What services are offered?
2. Who can receive the services (Veteran? Families of active enlisted?)
3. Why would Veteran/families be looking for the service?
4. Where do the services fit into the journey?

[ ] List of questions (What don't we know?)
[ ] Begin to consider topics for research sessions focused on Vet Center Facility Page content 

Documentation can be housed in this [Discovery folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/vet-centers/discovery)
