### ISSUE TITLE
Remove "prior to May 26, 2022" section from Resources page

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#59024]
## User Story
As a VFS team member, I want to view the Platform Collaboration Point Tracker so that I can track my teams products and/or journeys in the Collaboration Cycle. 

Assignee: @CherylEvans 
Peer Reviewer: @sterkenburgsara 

## Description
The Resources page includes guidance for teams that is no longer applicable. All teams currently engaged in CC began so after May 26, 2022. The guidance on the Resources page for the Platform Collaboration Point Tracker still has "prior to May 26, 2022"  and it should be delete. The heading "after May 26, 2022" should be removed.

## Impacted Artifacts
[Resources](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/resources) Platform Collaboration Point Tracker section

## Tasks
- [x] Delete the ""prior to May 26, 2022" heading and body paragraph for the Platform Collaboration Point Tracker
- [x] Remove the heading (not the body paragraph) "after May 26, 2022" so that the section reads Platform Collaboration Point Tracker with the body paragraph

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS team members have access to accurate information on the Platform Collaboration Point Tracker

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by sterkenburgsara** [comment]
@CherylEvans looks great! Do we need to do anything about the text in the purple background section that refers to that date?

**Comment by CherylEvans** [comment]
@sterkenburgsara There was nothing mentioned in the tasks section, so I left it alone.  Let me tag @shiragoodman to confirm.

**Comment by CherylEvans** [comment]
@sterkenburgsara I removed the reference with the purple background and published the updates on the source page. :-)

**Comment by CherylEvans** [comment]
Updates are published to PW.
