### ISSUE TITLE
Develop a way to send Login.gov veteran info for quicker registration

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#59023]
### Develop a way to send Login.gov veteran info for quicker registration
This work comes out of the [Progressive Migration research](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/55127) which found that veterans expect to not have to reenter information that is already on file.
There was similar work being previously worked on for Inherited Proofing work that was shelved. This seeks to pick that back up but excluding ID proofing and other verification.

### Tasks
- [x] Reach out to LIG to gauge their interest in restarting the work that was shelved
- [ ] Connect with Tom on if VA is able to lend resources - i.e. general council

#### Acceptance Criteria
- [ ] Veterans can choose to have VA send their info to LIG when they are registering for a LIG account
- [ ] Reviewed by PMs
- [ ] Documentation has been updated
- [ ] Put published research in drive

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by claytonzook** [comment]
Email sent to LIG (Sierra) on May 24

**Comment by claytonzook** [comment]
Heard back from LIG - Even though this wouldn't include the identity verification part from the inherited proofing work, since it would still be dealing with PII, they felt it was too much scrutiny to continue forward with at this time.

**Blocked by Login.gov team**

**Comment by claytonzook** [comment]
Some extra context and ideas from chatting with Tom:
- our privacy and info sharing agreement is one-way from LIG to VA
- question - would it make a difference to send LIG encrypted info that they don't store until the Veteran reviews and submits, so data is still technically coming from the user and not VA?
- opportunities 
   - work with LIG to better explain on their pages why they need to input this info
   - better explain this on VA communications

**Comment by aparsley** [comment]
LGA has taken this initiative.
