### ISSUE TITLE
Profile |  MHV Notification Migration | Add Email as a Channel - Update documentation

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#59021]
## Background

Now that our notification settings feature supports multiple channels, we need to update the [use case documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/notification-preferences/use-cases#user-has-partial-or-missing-contact-information) to provide a high level overview of how this works.

## Tasks
- [ ] Update use case documentation linked above
- [ ] Update the [feature toggle list documented here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/frontend/feature-flags.md)
  

## Acceptance Criteria
- [ ] Docs are updated

**Comment by andaleliz** [comment]
@mtcA6 I created this ticket just so we don't forget to do this once FE changes are on prod. This ticket would be blocked by any FE work and could be completed by anyone on the team.

**Comment by mtcA6** [comment]
this has already been completed
