### ISSUE TITLE
UX | Auth Exp | Logged-in IA/Nav | Map the veteran object

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#59022]
## Background

In #58875, we identified places in the site where it makes sense to surface personalized content outside of My VA. Now we have determined the next best step is to map the veteran object to aid in a content/IA audit.

## Tasks
- [x] Create map of veteran object (OOUX methodology likely will help)
- [x] Share with Mikki, Chante, Kristen
  

## Acceptance Criteria
- [x] Columns B-E have been completed in the spreadsheet

**Comment by andaleliz** [comment]
Hi @mtcA6 I updated the Mural link and gave you temp access to the spreadsheet. This is so dumb, but Ad Hoc wants us to lock down Google docs to internal only, so I'm technically not supposed to share with you (this is also why I didn't ping Allison or Derrick for review, even though they have technical knowledge that might be helpful). I had planned on sharing with the larger team once it's in Sharepoint. It's just a pain for everyone to have to get on CAG and generally Sharepoint is clunky so I'm trying to do as many edits as possible in Google Sheets before moving it over.

Happy to go over any questions you have on a call, or screen share and talk through what I'm working on. There won't be any product work for our team that comes out of this (other than getting tech input from devs) until Samara gets back, at least.

**Comment by tpharrison** [comment]
@andaleliz both docs give a great overview.  I don't think anything is missing.  Thanks for sharing!

**Comment by andaleliz** [comment]
**Update**: I've taken this as far as I can until I talk to Mike on Tuesday to learn more about specific values.

**Comment by tpharrison** [comment]
I created [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59916) to add examples values to the spreadsheet.

**Comment by andaleliz** [comment]
We met with Mike Richard and Karl Moll today from the VA Profile team, and got answers to several outstanding questions.   I've completed columns B-E as much as I can at this point, so I'm going to close this out.  

@tpharrison, I highlighted the cells in the "Example values" column that will be most helpful for you to add info to once you get to work on [59916](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59916). I'm following that ticket so I can stay tuned.

FYSA @kristinoletmuskat
