### ISSUE TITLE
[Research] Notification Center: Preliminary research strategy

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#59036]
## Background
We need to determine our strategy for conducting usability testing on our Notification Center MVP. We don't need to have a full research plan written up at this point but we should determine our high level goals and exactly how we'll test (i.e. in code or with a prototype)

## Tasks
- [ ] Craft a draft plan for how we will conduct this round of research 
- [ ] Determine high level goals of this round of research
- [ ] Discuss proposal with team

## Acceptance Criteria
- [ ] (Nice to have) initial draft plan exists in GH (note this does not need to be a formal research plan at this stage, but can be the start of it/an outline)

**Comment by ajakabcin** [comment]
Closing as complete
