### ISSUE TITLE
[Design, FE] Notification Component: A11y prep for staging review

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#59039]
## Background
In preparation for staging review we need to perform accessibility tests on the new notification component. This will be a joint effort from Design and FE to perform these tests, and Product to ensure everything is documented to submit the request. 

[A11y staging review preparation](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review) documentation for reference. Noting for future reference, a11y platform folks have introduced a new format for completing these tests. For staging review, a11y asks that the team submit a11y testing via [this ticket template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D). More documentation [here](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review#Prepareforanaccessibilitystagingreview-Usingtheaccessibilitytestingartifactartifact).

Additional reference: examples of same tests/process done for staging reviews of 
- _[Onsite notifications](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/launch-materials/onsite-notifications-mvp-a11y-staging-review-prep.md) (old format)_
- _[payment info v2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/launch-materials/payment-info-v2-a11y-staging-review-prep.md) (old format)_
- [My VA audit UX improvements](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54648) (new/current format)

## Tasks
- [x] Design and FE to perform the accessibility tests as documented [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/update-design-system-component/launch-materials/notification-design-system-component-a11y-staging-review-prep.md)
- [x] PM to assist as needed and track progress in staging review artifact documentation
- [x] Let PM know when complete so they can fill out [this request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D)

## Acceptance Criteria
- [ ] Accessibility tests are ready for Staging Review

**Comment by allisonlu** [comment]
@ajakabcin 

Angela and I have completed the [a11y staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/update-design-system-component/launch-materials/notification-design-system-component-a11y-staging-review-prep.md). 

All of the foundational tests pass, and I added some notes to the optional advanced tests.

**Comment by ajakabcin** [comment]
thank you both @allisonlu and @aagosto90 ! I've submitted #59505 as part of prep for staging review
