### ISSUE TITLE
Create new Sketch workspaces / libraries to separate examples from the symbols

### ISSUE THREAD

**Issue by babsdenney** [department-of-veterans-affairs/va.gov-team#59048]
## Description
We need to create new Sketch workspaces to separate examples from the symbols in the libraries. 

Continuation of this ticket to create New Sketch workspaces
[Ticket #1723](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/1723
)
## Tasks

- [x] Create an Example library for the[ MVP Foundations & Pattern Library](https://www.sketch.com/s/998b1585-ba60-474f-ba5d-85729b247f3c)
- [x] Create an Example library for [USWDS Component library](https://www.sketch.com/s/2476e4ee-fa82-4a19-bf11-dcb9b790acb7)
- [x] Create an Example library for the [USWDS MVP Component library](https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4)
- [x] Remove examples from USWDS Component library and USWDS MVP Component library
- [x] Move symbols to the corresponding page in each library (MVP Foundations & Pattern Library, USWDS Component library and USWDS MVP Component library). Example: Move v3 Accordion symbol from Symbols page to Accordion page in the USWDS Component Library

## Acceptance Criteria

- [ ] Reviewed by PO

**Comment by LillyBoot** [comment]
4 tickets will be coming out of this ticket:

1. Reorganize the sketch libraries 
2. Link symbols libraries to example libraries 
3. Reorganize colors and link to example libraries 
4. Reorganize Typography/make sizing changes (if needed) and link to example libraries 

@babsdenney @humancompanion-usds are there any other tickets that need to be created?

**Comment by LillyBoot** [comment]
Will create tickets before closing this ticket out

**Comment by babsdenney** [comment]
@LillyBoot this looks good to me. I like the new tickets, that should address the additional work that is needed. Thank you for organizing these libraries, it's a lot of work.
