### ISSUE TITLE
[FE] 10-10EZ - Household: BUG - Error generated within Dependents pages, unable to continue application

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#59041]
## Background
During QA (#51641) of the Household section optimization feature, a bug was found around the Dependents section when editing/cancelling a dependent, and when adding dependent income.

From Matt K:
>After adding Dependents Annual Income information and clicking continue, the form breaks and reveals this error message in the console: instrument.js:109 TypeError: Cannot read properties of undefined (reading 'first')
>(I believe this happened when there were more than one dependent)

From Jessica
>I went through the form a couple of times (most cancelled out in error mentioned below, but was able to submit one app successfully with one dependent) and could not replicate error below on screen but realizing the note said "is in console"...so perhaps it was occurring.
>
>message in the console: instrument.js:109 TypeError: Cannot read properties of undefined (reading 'first')
>
>What I did encounter: when in the modals and canceling adding/editing a dependent, the page would blank out and I would have to start the application over. See screenshot below.
>
>https://user-images.githubusercontent.com/98367393/240015125-b3cce058-fd22-4c2d-98d1-c761dc456020.png

## Tasks
- [ ] Review the error and determine root cause
- [ ] Implement solution and test successfully
- [ ] Inform PMs to review and continue QA on Household section optimization feature

## Acceptance Criteria
- Application can be completed without errors
