### ISSUE TITLE
EPIC | FE | Profile | Notification Settings | Consume Default Send on FE 

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#59043]
## Background

Leverage the output from [Design | Profile | Notification Settings | Update Sketch files to account for all use cases to add email as a channel #58890](https://github.com/department-of-veterans-affairs/va.gov-team/issues/58890) to make the necessary changes. 

This will form the basis for enabling emails as a channel. We're going to update the UI to allow for Checkboxes instead of Radio Buttons for all of our existing notifications. 

## Associated artifacts 
[List of sketch use cases](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-notification-preferences.md#draft-test-cases-to-account-for-when-we-add-email-as-a-channel)

## Tasks

```[tasklist]
### Ticket tracking
- [ ] #59915
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/59940
- [x] 6/23@2PM midpoint review for #57409
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/61013
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62077
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/61112
```

 

## Acceptance Criteria
- [ ] FE work is completed and we're ready for staging review 

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)? Anyone
- How can this work be validated? Compare [staging to sketch files](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-notification-preferences.md#draft-test-cases-to-account-for-when-we-add-email-as-a-channel) to confirm updates have been made 
- What updates need to be made (e.g. product outline, use cases, contact center guide): the UI needs to be updated to match the sketch files per our Design Intent feedback #58790 

## Associated Tickets
- #58890
