### ISSUE TITLE
Remove Spanish instructions for health care form from 2 pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#59046]
## Issue Description
Public Websites let us know there's an accessibility issue with the Spanish language instructions we have on 2 of our health care pages. We can remove these since we now have the full how to apply page translated into Spanish. 

The component is on these 2 pages:
- How to apply for VA health care
- Eligibility for VA health care

## Tasks
- [x] Remove component in Drupal (Randi)
- [x] Review (Megan)
- [x] Publish (Megan)
- [x] Notify PW that components were removed (Randi)

## Acceptance Criteria
- [x] Components no longer on live pages

**Comment by megzehn** [comment]
Thanks so much, @RLHecht! Confirming I published these changes.

**Comment by RLHecht** [comment]
These changes are live and I'll notify PW. Closing
