### ISSUE TITLE
[FE] My VA: Write FE unit tests for Health Care components part 2

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#59054]
## Background
Part 2 of Health Care component unit tests. This ticket is to address unit tests for the Health Care components: 

- `health-care-v2/AppointmentsV2.jsx`
- `health-care-v2/HealthCareV2.jsx`
- `health-care/HealthCareCTA.jsx`
- `health-care/HealthCareContent.jsx`

## Tasks
- [ ] Confirm whether these components are being used on My VA and note that in the audit list 
- [ ] If they are not being used log them as not in use, put the ticket back into backlog, and let PM via comment on this ticket

If they are being used on My VA: 
- [ ] Write FE unit test for `health-care-v2/AppointmentsV2.jsx` component
- [ ] Write FE unit test for `health-care-v2/HealthCareV2.jsx` component
- [ ] Mark as not in use (and for removal) `health-care/HealthCareCTA.jsx` in the audit doc
- [ ] Mark as not in use (and for removal) `health-care/HealthCareContent.jsx` in the audit doc
- [ ] Test
- [ ] Move to validate
- [ ] Update audit list

## Acceptance Criteria
- Unit test(s) is written and running _OR_
- Ticket is moved to backlog

## Resources
- [health-care-v2/AppointmentsV2.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/health-care-v2/AppointmentsV2.jsx)
- [health-care-v2/HealthCareCTAV2.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/health-care-v2/HealthCareCTAV2.jsx)
- [health-care-v2/HealthCareContentV2.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/health-care-v2/HealthCareContentV2.jsx)
- [health-care-v2/HealthCareV2.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/health-care-v2/HealthCareV2.jsx)
- [health-care/HealthCareCTA.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/health-care/HealthCareCTA.jsx)
- [health-care/HealthCareContent.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/health-care/HealthCareContent.jsx)
- Full audit [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/fe-unit-test-audit.md#personalizationdashboardcomponents)

**Comment by adamwhitlock1** [comment]
Tests have been added and unit tests are passing! good to close this issue
