### ISSUE TITLE
Supplemental Claims | Refactor code with va-button

### ISSUE THREAD

**Issue by rocio-desantiago** [department-of-veterans-affairs/va.gov-team#59058]
## Value Statement
**_As a_** Veteran with accessibility needs that is filing a supplemental claim
**_I want to_** file using the latest enhancements to the frontend experience
**_So that_** I can benefit from accessibility and other design updates. 

---
## Background Context
This form uses outdated components. The VA design system has updated components that we can use for the form. 

## Acceptance Criteria
- [ ] All tasks complete
- [ ] All tests passing
- [ ] User can submit a Supplemental Claim with no errors related to component use

## Designs and Build Notes
- Replace `button` (not a React component) with `va-button`

## Out of scope
- Any others components (design system, etc) that use the element

## Tasks
- [ ] Replace plain `<button>` with `<va-button>` as needed
- [ ] Unit tests updated
- [ ] e2e tests updated

## Definition of Ready 

- [ ] We know which elements to update, and which to leave out of scope

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by jaredcunha** [comment]
For sizing:
- 11 instances in 7 files of `<button>` in supplemental claims
- Should removing `DownloadLink` component file in supplemental be considered in scope?
- Out of scope: components using `<button>` that are imported into supplemental claims?

**Comment by saderagsdale** [comment]
@rocio-desantiago break into two tickets

**Comment by Mottie** [comment]
Changes verified
