### ISSUE TITLE
[FSR] Downtime dependency update

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#59051]
## Issue Description
We need to update `DowntimeNotification` `dependencies` to include `vbs` as well as `vba`. 

We have something similar set up [in the CDP app](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/combined-debt-portal/combined/containers/CombinedPortalApp.jsx#L82), so we can probably mirror functionality here. 

Looks like it's used in [the wizard](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/financial-status-report/wizard/WizardContainer.jsx#L26) and on [the confirmation](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/financial-status-report/wizard/pages/Submit.jsx#L45) page for the FSR

---
## Tasks
- [x] Update downtime notification to include all necessary dependencies for FSR
- [x] Confirm CDP also has all necessary dependencies while we're at it!

## Acceptance Criteria
- [x] FSR and CDP include all necessary downtime notification dependencies. 
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
Sliding into 102 since other higher priorities came up. Streamlined prep and proper launch blockers and other feedback from user testing

**Comment by OptionSelect** [comment]
I believe I have the dependencies in place but need to get better info so I can ask questions about what is really necessary based on config that I seem to have found here

https://github.com/department-of-veterans-affairs/devops/blob/a4b5432061ae60a4f77952bbe5f668a1355ee007/ansible/deployment/config/vets-api/prod-settings.local.yml.j2#L232

**Comment by HeatherRienks** [comment]
@Dr-Pongo and @ScottyRJames to coordinate completing this

**Comment by HeatherRienks** [comment]
@OptionSelect - @Dr-Pongo - any updates you can share here for visibility would be awesome! Thanks!

**Comment by OptionSelect** [comment]
Next step is to coordinate with Scott to create a downtime window to test if the notification still works. Will hopefully begin week of 8/7

**Comment by OptionSelect** [comment]
Will begin work again in Sprint 106.

**Comment by HeatherRienks** [comment]
Awaiting PR approval; will roll into S106

**Comment by HeatherRienks** [comment]
Per FE Sync, still awaiting PR merge. Should be done within a few days or so.

**Comment by HeatherRienks** [comment]
@OptionSelect - any updates on this ticket? Thanks!

**Comment by HeatherRienks** [comment]
Per @OptionSelect ,  he and @ScottyRJames need to confirm this works as expected. Will be done in S107.

**Comment by HeatherRienks** [comment]
@OptionSelect @ScottyRJames - any blockers on this one?  Hoping we can wrap up by end of sprint! Thanks!

cc: @Tom-Davis

**Comment by OptionSelect** [comment]
Per convo with Tom in standup (and because I won't get to this today) closing ticket and we will spin up new one pointer for investigating the console issue discovered with the dependencies.
