### ISSUE TITLE
Domo dataset clean up

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#59060]
## Issue Description

Our Domo datasets have grown considerably resulting in increasing costs.  As part of this clean up we will remove 2019 data from standardized dashboard datasets.  We also audit all Domo datasets to determine if they are still needed and if they are a duplicate of another view and remove accordingly.

## Tasks
- [x] Complete dataset audit [tracking doc](https://docs.google.com/spreadsheets/d/1y6WRGftpGzzCwrytaFjoxrzZaLBmAqNZ58sXIQMmj68/edit#gid=0)
- [x] Remove 2019 data from datasets as defined in tracking doc.
- [x] Review [OUTPUT] datasets to determine if needed or if original view can be used for attached cards.
- [x] For datasets identified for removal - document cards and dataflows they may be a part of.  
- [x] Update tracking doc as datasets are updated/removed

NOTE:  Make sure before we remove any dataset that all cards attached to it are directed to another dataset or are no longer needed.  Also confirm no additional dataflows are dependent upon that table.

## Acceptance Criteria
- [ ] Clean up process as outlined above is completed and our total Domo row counts are < 1M (per current Domo cost structure)

**Comment by michelle-dooley** [comment]
removed from all datasets except standard forms engagement which keeps failing due to size.  We will complete that work in the upcoming sprint.
