### ISSUE TITLE
Build a comms proof of concept

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#59069]
## Issue Description
In order to prep for the reactivation & organic adoption campaign releases, we will build a proof of concept. The main features of this proof of concept are:
- It's triggered by an event: a user logging into VA.gov with a legacy credential
- It determines the user's eligibility for the reactivation campaign, based on whether or not they have a modern credential
- It uses the VA Notify API to send an email to the user
- We're able to view relevant data about the email campaign 

[Requirements here](https://docs.google.com/document/d/1SU-BWgiihi_RBQ7tplnkAPlaEulmkL03ypOpWSWIp2o/edit#)
More details are captured in [this Mural](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1684329312312/df1c36fc281d2e288446e9feb0603321e115525d?sender=uaaa67493ae613f0003928743)

## High Level User Story/ies
As an LGA team member, I want to build a proof of concept of the reactivation campaign in order to: 
- learn more about how VA Notify works
- de-risk the upcoming release of the reactivation campaign, and 
- ensure that we're able to visualize data about this campaign in our dashboard. 

## Acceptance Criteria
 - [ ] Able to be triggered by logging in with a legacy account
 - [ ] Correctly assesses user's eligibility for reactivation campaign
 - [ ] Sends an email to a test user using VA Notify
 - [ ] Data from GA events (ie % of users who clicked the CTA in the email) is accessible

## Assumptions
- POC will be content-agnostic, and therefore won't require any reviews, approvals, or collab cycle. 
- POC will be deployed in a staging environment.

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed*
- Full access to VA Notify 
- Need an understanding of how VA Notify & Google Analytics track campaigns
- VA Notify: Custom reply-to inbox request can take up to three weeks

## Target Launch Date
End of Sprint 21

## Risks and Concerns
- Core Team is being extra cautious with code/PR reviews because this will eventually impact veteran users directly.

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

**Comment by lmorris3** [comment]
Closing epic - all stories are complete.
