### ISSUE TITLE
Reiterate on AVS MVP Design based on the Findings from May 2023 AVS MVP User Testing.

### ISSUE THREAD

**Issue by ninaranusavice** [department-of-veterans-affairs/va.gov-team#59066]
# Description
Reiterate on AVS MVP Design before final hand-off to Engineering.

# Tasks
- [x] Remove the "Details" link from the design.
- [x] Make phone numbers look like links within the Sketch wireframes.
- [x] Review any needed annotations for engineering to Sketch wireframes.

# Acceptance Criteria
- [ ] Message engineering when wireframes are complete.

**Comment by kristenmcconnell** [comment]
@acrollet This is the scope of design changes for MVP that came from the usability study. @ninaranusavice is going to be starting this ticket and will message when the wireframes are updated.

**Comment by acrollet** [comment]
@kristenmcconnell thanks, we should maybe have a brief discussion about linking phone numbers. AFAIK they will be embedded in free text and we may not always be able to identify and link them, my guess is that they will not follow a standard format. Is this an MVP requirement?

**Comment by kristenmcconnell** [comment]
Lets definitely talk about this at our next sync on Monday. Is there anything that does come across as an easily identifiable phone number? If so, could we connect those for MVP. We can push the rest from MVP where it is hard to tell.

**Comment by acrollet** [comment]
I just looked and we can at least do the facility phone under VA Medications.
