### ISSUE TITLE
Technical design/architecture of proof of concept

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#59071]
## Tasks
- [x] Break down & discuss: login trigger
- [x] Break down & discuss: eligibility assessment
- [x] Break down & discuss: sending email with VA Notify
- [x] Break down & discuss: UTMs, Google Analytics, & campaign event tracking
- [x] Answer any other questions about requirements or business rules
- [x] Document any questions that need further research
- [x] Suggest ways of streamlining the POC to reduce complexity/level of effort
- [x] Create a diagram that documents the proposed technical design for the proof of concept
- [x] Review with the Engineering team & iterate

## Acceptance Criteria
- [x] Engineering team agrees that the technical design is feasible
- [x] There are no major open questions about how we will build this POC
- [x] We have a plan for how we'll integrate with VA Notify & Google Analytics
