### ISSUE TITLE
Add hypen to in person when precedes a noun

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#59081]
## Description 

In our card components (not in the appt list) and in appt detail pages, hyphenate "in-person" because it precedes a noun.  

## Tasks 

- [x] Update all artboards 
- [x] Check symbols
- [x] Check annotations 
- [x] Tag Christina to updated in CodePen

## AC

- [ ] Final wireframes created
- [ ] Updated in CodePen

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 for awareness

**Comment by cgednalske** [comment]
@benbrasso-agile6 this is just for unified check-in right? I don't believe we have this scenario anywhere else - just in the new cards.

**Comment by benbrasso-agile6** [comment]
Yes, unified check-in. There's a [separate ticket for production app](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/59083).

**Comment by benbrasso-agile6** [comment]
But, this is ONLY for detail pages. NOT the card within the appt list pages.

**Comment by cgednalske** [comment]
@benbrasso-agile6 this is updated on Sketch for unified (cards and appointment detail pages) + in CodePen. Could you validate?
[CodePen link](https://codepen.io/team/va-cie/live/NWORQEe)
