### ISSUE TITLE
Add hypen to "in person" on appt detail page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#59083]
## Description 

In appt detail pages, hyphenate "in-person" because it precedes a noun.  

For pre-check-in and check-in, the heading for in-person appts on the appt detail pages (not the appt list pages) should include a hypen. E.g., "In-person appointment"

## Tasks 

- [ ] Update all artboards 
- [ ] Check symbols

## AC

- [ ] Final wireframes created
- [ ] Merge up into travel branch in abstract

**Comment by benbrasso-agile6** [comment]
@loripusey ticket already assigned to FE https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/59082

**Comment by ytsaoca** [comment]
Wireframes for review:
Check-in
https://share.goabstract.com/3630ccdf-c1fd-4257-ae9f-13d1bded1ff6
Pre-checl-in
https://share.goabstract.com/0576baf8-4d71-47ce-ac89-7f42d52ee289

**Comment by ytsaoca** [comment]
Wireframes for review:
Check-in
https://share.goabstract.com/3630ccdf-c1fd-4257-ae9f-13d1bded1ff6
Pre-checl-in
https://share.goabstract.com/0576baf8-4d71-47ce-ac89-7f42d52ee289

**Comment by benbrasso-agile6** [comment]
On this page, https://share.goabstract.com/3630ccdf-c1fd-4257-ae9f-13d1bded1ff6?collectionLayerId=85fe82b5-66d8-42da-89ff-09cec4dc56ad&mode=design&sha=latest, did you want to add the hypen to the 3 other cards? Looks like you added it to 1 of them.

That's the only feedback. Nice work.

When that's complete, this update is already in production. So, @zach-park, I would recommend merging it up to Master in both check-in and and pre-check-in when Ya-ching is finished.

**Comment by benbrasso-agile6** [comment]
Cool!

**Comment by zach-park** [comment]
Pre-check-in version is merged into the main branch

**Comment by ytsaoca** [comment]
Created a new branch under check-in master, edited it, and merged it into the main branch.
