### ISSUE TITLE
[MCP] Email copy/design enhancements 

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#59097]
## Issue Description
The MCP notification email copy lacks some key information regarding copays. Needs to be edited to have a more clear CTA and be more personal and relevant to a veteran. 

---
## Tasks
- [x] Update copy and subject line to be more personal and actionable.
- [x] Start conversation with stakeholders ([Slack thread is here](https://dsva.slack.com/archives/CPE4AJ6Q0/p1685053653718719))

## Acceptance Criteria
- [x] Draft the proposed updated copy
- [x] Create an implementation ticket outlining the new copy

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by josephrlee** [comment]
Here is the proposed copy:

Current subject line: **Important information from the Veterans Health Administration**
Proposed subject line: **You have new information from the Veterans Health Administration**

Body copy:

> Dear [First Name],
> 
> You have a new medical copay from the Veterans Health Administration. Please sign in to https://va.gov/manage-va-debt to view the details.
> 
> [View your copay details](Big button)
> 
> You will also receive a letter from the VHA with details of this information.
> 
> Thank you,
Veterans Affairs

[Here is the link to the discussion in the Slack thread for more context](https://dsva.slack.com/archives/CPE4AJ6Q0/p1685053653718719).

Jill and Denise will identify the privacy conversations and then revisit the notification copy.

cc: @HeatherRienks

**Comment by josephrlee** [comment]
@HeatherRienks , were we moving this out of this sprint?

**Comment by HeatherRienks** [comment]
@josephrlee - I am inclined to say yes, we should move out since I don't think this is a top priority right now, but let's confirm with @denisecoveyduc

**Comment by denisecoveyduc** [comment]
Hi @josephrlee  & @HeatherRienks  I'd recommend we adjust this ticket to prepare the copy and then put a ticket in the backlog for me to approve and prioritize integration of this copy. While this would be nice to do I think we need to hold off for right now and will prioritize in the future.

**Comment by HeatherRienks** [comment]
New ticket has been created for this effort: #61324 and we will prioritize accordingly.
