### ISSUE TITLE
Board Appeals Interviews | Post Interview Re-group

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#59123]
## Value Statement
**_As a_** team
**_I want to_** debrief on on our first two rounds of SME convos with John, Amy, and Intake + review the documentation they shared
**_So that_** we can plan our next SME conversations and connect any useful info from the documents to our work. 

---
## Background Context
- [Link to documents](https://drive.google.com/drive/folders/1U-vzZvKTghrueZN0AIFPKyyiRwQTjFrK) shared by John + Intake team
- [Link to meeting notes](https://drive.google.com/drive/u/0/folders/1mRgJDn6uMeNbP1-gKO_X5WZoLJUPe3aH) for kick-off call
- [Link to meeting notes](https://drive.google.com/drive/u/0/folders/1k2xzWI6X1-nqADXPW2UG1hg15J9tV9I3) for Intake call
- [Link to Research Strategy](https://docs.google.com/document/d/1vHDnIHV2LTgjMRpYWYpXYjG0J9NkXuEacYVlqZjKJtU/edit#heading=h.lihallwas2ml) w/ SME Notes

## Out of scope
- Add here

## Open questions
- Is there a more recent copy of the OAI Report? This one is from March 2022.
- Are we allowed to request access to the VACOBVA sharepoint? Links shared in OAI report are inaccessible.

## Tasks
- [x] Review the documents
- [x] Surface any assumptions we want to debunk
- [ ] Look at our learning goals and ask ourselves if we think there are any new known unknowns we want to learn about
- [x] Determine which BVA SME convos to have next

## Definition of Ready 

- [x] The docs are accessible
- [x] We have a forum for brainstorming
- [x] We have a [decision log](https://docs.google.com/spreadsheets/d/1emC1gzWnO36iN5rykwajBU2KyVSEy2iAy_g6DcrBouo/edit#gid=609426218)

## Definition of Done

- [ ] We've re-aligned as necessary
- [ ] We've debunked assumptions
- [ ] We've course corrected discovery by lining up our next conversations

**Comment by eileen-coforma** [comment]
Scheduled a meeting with Julie for 6/1 to discuss the level of detail the service blueprint should have to be useful for the VBA.

**Comment by saderagsdale** [comment]
@eileen-coforma @rubensun think we still need to keep this open?

**Comment by saderagsdale** [comment]
@eileen-coforma @rubensun bumping this back up. Think we still need to keep this open?

**Comment by saderagsdale** [comment]
Moving to the product backlog for now.

**Comment by rubensun** [comment]
yep. closing out.
