### ISSUE TITLE
[UX] Update the travel pay confirmation page to avoid using 2 sentences (only 59165 and 59121 gets worked on)

### ISSUE THREAD

**Issue by kellysmith1008** [department-of-veterans-affairs/va.gov-team#59121]
## Issue Description
If I choose to submit a travel pay claim and I am successfully checked in, but something went wrong with sending my claim request, our [header on the confirmation page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/v/gdemVa/a/9lP4eM7/) currently reads: "You're checked in. But we couldn't file your travel claim." After conversations with platform and content, we've agreed to align our designs with the design language system, which involves not using periods in headings. We need to come up with new content to smoosh these two ideas together into one sentence and remove the periods.

---
## Tasks
- [ ] Content needs to be combined into a singular sentence
- [ ] Run new content past Laura W for approval
- [ ] Update in unified check in file

## Acceptance Criteria
- [ ] New content created
- [ ] Content has Laura W's approval
- [ ] Unified check in sketch is updated

**Comment by benbrasso-agile6** [comment]
Removed tasks associated with production apps. Once we have a solution, we can decide if we want to pull into production apps now or not. The reason behind this decision was because this feedback was coming out of unified check-in midpoint review (not travel staging review).

**Comment by kellysmith1008** [comment]
Updated guidance: Use one sentence only in H1s, and a singular idea conveyed in the sentence. So, for example, don't combine a success statement and an error statement, or two successes or two errors. 1 idea per sentence.
[Slack thread](https://dsva.slack.com/archives/C05M369EQSU/p1692136562811459?thread_ts=1692042637.809279&cid=C05M369EQSU)

**Comment by benbrasso-agile6** [comment]
Closing ticket because of resolution in https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/62345

Moving forward with this ticket https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/59165

**Comment by benbrasso-agile6** [comment]
Shoot, I did that backwards

**Comment by benbrasso-agile6** [comment]
This ticket is ready to be worked on and probably starts with @kellysmith1008 and then to @zach-park 

Resolved here https://dsva.slack.com/archives/C05M369EQSU/p1692042637809279

**Comment by benbrasso-agile6** [comment]
That's cool.  And, we're staying within this framework/page IA, right? 

<img width="629" alt="Screenshot 2023-08-16 at 10 39 14 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/101129355/9e01857e-4cf0-4d3d-a75f-624faace3145">

**Comment by kellysmith1008** [comment]
Yes sir - part of why I don't think it'll take that long to for Zach to make professional (almost said "make good" hahaha) once I mock it up and he can see where my head is. I just don't know if I'll get to that mock up tomorrow or if it will be Friday, and I don't want to rush him getting the updates done. But short answer, yes :)

**Comment by cgednalske** [comment]
Yay - go team 🎉 I'm not quite following your explanation yet @kellysmith1008 😄 but am excited to see what you're thinking! @zach-park let me know if you need me to take any of these tasks depending on your annotations work.

**Comment by zach-park** [comment]
@kellysmith1008 , sounds great. Please let me know when ready. @cgednalske , let's co-work together (or take you up on your lead). Thanks so much!

**Comment by cgednalske** [comment]
@zach-park -- with @kellysmith1008 having done the real work already 👏 , this ended up being just two super quick tweaks in our design file. 😄 So I believe it is all complete, but if you all could take a look at the changes and make sure I'm on track or didn't miss anywhere else that needs them, that'd be great. 
cc @benbrasso-agile6

**Comment by kellysmith1008** [comment]
Looks good, @cgednalske! I'm good to close this ticket if Zach and Ben are!

**Comment by zach-park** [comment]
Looks great. Thank you! :)

**Comment by benbrasso-agile6** [comment]
Looks good, but what did we decide with Kelly's comment here? @cgednalske @zach-park 
https://sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/9886B622-31C2-4B58-9C84-DA84423B9A96/canvas?annotation=6ec7dd60-cda7-49a8-aa2b-a1959e9ed05c

**Comment by cgednalske** [comment]
@benbrasso-agile6 a little confused by the comments in Sketch, but yes I believe we addressed all that and applied our decisions to the main design file. 👍 Just made those changes in the feature page as well.
