### ISSUE TITLE
[AFTER RESEARCH] Update alerts in check-in

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#59126]
## Description 

We need to move away from using background [alerts](https://design.va.gov/components/alert) on the travel reimbursement pages. We are not using them correctly. (This is from [feedback we received from platform design](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/58811).) 

## Tasks 

- [ ] Determine what design change we need to make. For example, there's probably a couple options to consider, 1) body text, or 2) [additional info component](https://design.va.gov/components/additional-info)
- [ ] Share design decision with UX team. The scope of this ticket is the 4 travel reimbursement wireframes. 

## AC 

- [ ] Wireframes created to show design change
- [ ] Reviewed by UX team

**Comment by benbrasso-agile6** [comment]
Adding @kellysmith1008 on to help with the question headings

**Comment by ytsaoca** [comment]
Final wireframes:
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/L4nE83Q
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/K0RYg3D
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/w5Q0POD
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/qbVGxZy

@benbrasso-agile6 If I move them to the design page and deleted the old one, we will lose the comments on the old boards. Not sure if you still want to keep them so I haven't done this.

**Comment by benbrasso-agile6** [comment]
Thanks. I’ll look in the morning.

**Comment by benbrasso-agile6** [comment]
updated

https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/ZVKgWP3#Version
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/JAPvz0k#Version
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/vRE1LY4#Version
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/4omEVyD#Version

Annotation for open/close - https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/29AAD49B-F511-46DA-B253-F49FF924D7C5/canvas#Version

**Comment by kellysmith1008** [comment]
@ytsaoca @benbrasso-agile6 I left a comment in the mockups - the vehicle question needs to be reworded to match the "what if" phrasing in the other questions and vehicle is misspelled.

**Comment by benbrasso-agile6** [comment]
Feel free to update. Thanks
