### ISSUE TITLE
Research Docker Compose use for PEs

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#59143]
# Description
In order to be able to use a pre-built `content-build` we will need to resolve the communication issue between the frontend and backend. One possibility is to use docker compose to create all the resources required for a preview environment and simplify the networking -- https://docs.docker.com/compose/networking/

After our brainstorming session on the afternoon of 5/25 -- https://vfs.atlassian.net/wiki/spaces/TT4/pages/2645000797/Brainstorm+Preview+Environments -- let's look into other ways that we might be able to configure `content-build` that are detailed in the brainstorming session notes.

# Tasks
- [ ] Read through Docker Compose setup
- [ ] Determine whether Docker Compose will be able to resolve our issue with getting our frontend talking to our backend in preview environments

# Acceptance Criteria
- [ ] A research document describing whether and how Docker Compose might help us configure our preview environments to have frontend and backend talking

**Comment by CBonade** [comment]
The time dedicated to this today was spent in a brainstorming session where we discussed alternate options. Evaluating the path forward, we've decided that researching into an alternate environment config at the content-build level may produce a better result for us.

**Comment by pjhill** [comment]
After reviewing the documents for docker-compose I'm not entirely convinced that this is a solution to our problem with being able to configure content-build to connect to a custom vets-api URL. Additionally, the brainstorming session that we held after creating this ticket produced several more promising ideas with shorter implementation timelines.

**Comment by pjhill** [comment]
This is not the solution to our problems at the moment. It may be viable in the future.
