### ISSUE TITLE
Identity Dashboard (FE) - Micro-frontend aka Module Federation

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#59147]
## Description
Research and implement Module Federation with Next.js (identity-dashboard-fe) and Vue (fwa-dashboard)

## Tasks
- [x] Research the micro-frontend architecture with Module Federation
  - [x] Time box research/PoC to 1 week
- [ ] Implement Module Federation for Next.js + Vue

**Comment by acald-creator** [comment]
Created separate repo to track different implementations on how to setup module federation with different frameworks: https://github.com/department-of-veterans-affairs/vsp-idp-microfrontend-test

**Comment by acald-creator** [comment]
Implementation Module Federation with Next.js 13 app router and Vue.js 3

Pros:
* allow us to share code between multiple applications with duplications
* enables us to develop micro frontend architecture, where each team can own and deploy their own module
* independent development and deployment among the teams
* version control management, allows managing different versionings and can deploy packages

Cons:
* setting up microfrontend architecture can be complex
* build performance can be slower, and depends on the number of applications are created, build time can slow because there is a process of resolving and bundling dependencies
* compatability - not all frameworks work with Module Federation, refactoring will be needed
* debugging and troubleshooting will be necessary and can be more challenging

Resources:
* https://github.com/module-federation/universe
* https://github.com/module-federation/module-federation-examples
* https://github.com/originjs/vite-plugin-federation

However, pertaining to the current project, implementing Micro-frontend with Vue.js and Next.js will not work as expected.

Next.js 13 currently has an app directory layout which might not have full support with using `@module-federation/nextjs-mf`, and if there is, this implementation is tightly coupled and supported within Next.js apps, not any other apps outside of Next.js.

There is support to use React with Next.js in a module federation format, but extra configuration are needed to make sure that the implementation works properly.

Also, Next.js 13 also supports React Server Components, which means you have to declare which is Client Component and which is Server Components.

Next.js 13 also has a pages directory layout where `@module-federation/nextjs-mf` is working properly, but there are potential issues with importing and displaying the component. There are suggestions to use `async boundary`, which means waiting to check the module is available before loading the module.

In the case of using Next.js 13 with Vue.js, there doesn't seem to be an easier way to implement this. 

Tool that could serve as a wrapper to use React in Vue, and Vue in React
* https://github.com/akxcv/vuera
* https://github.com/nmpribeiro/vuera-ts
* https://github.com/devilwjp/veaury
* Open issue regarding running `vuera` within Next.js - https://github.com/akxcv/vuera/issues/125

Cons for the above is adding overhead and maintaining another package if we were to create our own library.

Potential alternative project layout (future reference)
* https://github.com/vercel/examples/tree/main/solutions/microfrontends
	* This is a monorepo layout that utilize build time, using Turbo, and also creating `apps` and `packages`, and allows local/published imports within the same repo.
* https://github.com/munafio/react-vue-turborepo-starter
	* Turborepo (monorepo) layout with React and Vue.js but also have packages that include a  UI component library for React, and UI component library for Vue.js to use.

**Comment by asg5704** [comment]
Sounds good. Put this ticket in PM review and I'll create a new one for the eventual migration in the backlog.

**Comment by aparsley** [comment]
Looks great, keep up the good work.
