### ISSUE TITLE
Add section on Support Teams to VA.gov Platform General Orientation

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#59153]
**Description:**
The goal of this ticket is to add slides to Orientation video introducing new team members to expectations of support

**Definition of Done** 

- All tasks below are complete

**Tasks**

- [x] Introduction to Support to be added to _VA.gov Platform Orientation_ video (orig. by Shira Goodman)
- [x] Edit suggestions [here](https://docs.google.com/presentation/d/1wtP_QWEZ_5wlC8q0kqnaI_bJhI8HhzHtd4j89yTrF7c/edit#slide=id.p)
- [x] Send for review in #platform-tech-support-team

**Comment by alyssagallion** [comment]
Duplicate. Closing!

Related tickets:

- https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/62403
- https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/60977
