### ISSUE TITLE
[UX] Revisit adding travel confirmation into h1 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#59165]
## Description

Feedback from staging review: https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/59133

This ticket focuses on: 

> If technical constraints require the green confirmation alert to appear only after you've checked into an appointment, consider moving the alert just after the "You're checked in" H1. This ensures that the feedback on both of the actions you've taken (checked in and submitted a travel claim) are the first two items announced for screen reader users ("You're checked in. We're processing your travel claim.").

 I.e., If it's important for screen reader users that both actions are announced, could/should the travel confirmation message be moved back into the h1? 

## Tasks

- [ ] Create wireframe
- [ ] Review with sitewide content 
- [ ] Double check with FE if solution is approved. There's been conversation in the past about managing how many versions of the confirmation pages we have. 
- [ ] Add solution in unified check-in sketch file

## AC

- [ ] Wireframe complete
- [ ] Reviewed with sitewide content
- [ ] Updated in unified check-in sketch file (no need to update in CodePen as of 5/25)
- [ ] Create FE ticket

**Comment by kellysmith1008** [comment]
FYI, I was chatting with Laura Flannery, a CA accessibility engineer on the VA project, about this, asking if we could "code" the travel reimbursement for screenreaders but leave the design how it is for sighted users. This is the recap of that conversation - thought it might be helpful as research as we take a look at options for this ticket:
Kelly: I have a quick question for you - is it possible to use aria labels, CSS, or something else to group information together for a screen reader that isn’t “together” visually on a screen? for instance, the most important part of this screen is that the Veteran is checked in and they should have a seat in the waiting room. BUT, their travel reimbursement claim submission is dependent upon successful check-in completion. We’ve received feedback that we should move the green alert up under the H1 so screenreader users get both sets of info: you’re checked in, have a seat in the waiting room, and we’ve received your travel pay claim. However, that might become quite visually overloaded there. So I was wondering if there was a different way to code it in the backend that might compromise for both?
Laura: Ok, so here's my thought - there definitely could be a possible way to "tie" the travel reimbursement stuff to the H1 check-in stuff.  It might be slightly clunky but definitely do-able. However, my argument for not doing that is - only assistive tech folks would get that benefit. If we think it's important enough for those folks shouldn't we make sure visual folks not using assistive tech notice this too? Meaning we would advocate more for moving it up to the top visually as well?
To me, again not knowing a ton about this flow, I think this does make sense they way you have it - "great I've checked in, here's my appointment info, and then here's the travel stuff"
Short recap: 
- In her opinion, the layout needs to be the same for sighted and non-sighted users, because we may have sighted users who also benefit from using a screenreader, and not visually presenting the content in the same order as a screenreader reads it can be confusing.
- The way we have it laid out now makes sense to her for both sighted and non-sighted users
- Screenreaders can navigate by headings, so they can still find the travel pay information by heading, even if it doesn't come under the H1
- (I'm sure we already know this) but we can keep the design as an alert, but don't code the travel pay information as an alert or else it interrupts the screenreader every time it lands on this page

That's it - just wanted to provide some info I found out while chatting with her.

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 Is this now the 3rd ticket dealing with this heading? It's getting very difficult to keep up with which one we're actually supposed to be working on. Are we no longer supposed to put anything in this [also still open ticket](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/62345) and work in this ticket instead? Is there any way we could, at a minimum, combine any of these tickets so there aren't 3 dealing with the same work? This ticket doesn't seem to have any points associated with it - so if we're choosing this one, we need to point it, and that's going to put some of us way over the 10 point per sprint cap

**Comment by benbrasso-agile6** [comment]
Added response in slack https://dsva.slack.com/archives/C04J6H2LYUU/p1691606268735429

**Comment by benbrasso-agile6** [comment]
Closing ticket because of resolution in https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/62345
