### ISSUE TITLE
[AFTER RESEARCH] Consider location of check-in status

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#59169]
## Description 

Feedback from Brian during midpoint review: 

Consider: For Upcoming Appointments when displaying the check-in status for an appointment, consider whether it makes sense to move the status message up earlier in that list item. For sighted users, the status message is probably fine in its current location.

For screen reader users (and maybe screen magnification users), there might be some benefit for getting the "You checked in at 8:55am"-type messages closer to the appointment name and before the modality/location. I'm just thinking if I'm sitting in the waiting room and sifting through all the appointments I have scheduled for today, it's probably better to hear "Primary care... you checked in at..." and then move on to the next list item rather than listen to the whole "Primary care... In person at... Details for... You checked in at..." before knowing if I can move on to the next one.

It's not a huge amount of extra information you have to listen to so the impact is probably pretty small. But it might make the interaction a bit smoother.

## Tasks

- [x] Explore and make decision 
- [x] Create f/u ticket for the work 

## AC

- [x] Make decision 
- [x] Created f/u ticket for the work

**Comment by benbrasso-agile6** [comment]
No issues during research
