### ISSUE TITLE
IA Design: Digitized Form 21P-0847

### ISSUE THREAD

**Issue by jennymayoco** [department-of-veterans-affairs/va.gov-team#59163]
### Description
The digitized forms team opened an intake request for CAIA support on form 21P-0847. We will need to review and provide any IA feedback.

#### About form
VA Form 21P-0847 is used to allow claimants to request substitution for a claimant, who passed away, prior to VA processing a claim to completion. This is only allowed when a claimant dies while a claim or appeal for any benefit under a law administered by the VA is pending.

### Links

- [Intake Ticket #58950](https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/58950)

### Team

- Team Name: Veteran facing forms
- Designer: Jeana Clark
- Product Manager: Tricia Baker
- Slack (_optional_): veteran-facing-forms

### Timeline
Async Midpoint Review scheduled for Friday June 2nd @ 2pm ET

---

### Work Needed (if applicable)

- IA Spec: **Needed**
- Feedback for product team: **Needed**

### Tasks
Check all that apply.

- [X] Create process ticket draft
- [ ] Watch Design Intent --> no design intent recording
- [X] Determine work needed
- [x] Collaborate with CAIA
- [ ] Ask questions to product team
- [x] Create IA Spec
- [ ] Mikki reviews IA Spec
- [x] Share IA Spec with product team
- [x] Update Site Map and VA.gov Mega IA sheet

## Acceptance Criteria
- [ ] Feedback is shared with product team in Intake Ticket.

**Comment by RLHecht** [comment]
waiting on H1

**Comment by jennymayoco** [comment]
Here is the [IA spec for this form](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/form-digitization-21p-0847.md).

- [x] Has been shared with the forms team
- [ ] Has been shared with Megan

**Comment by jennymayoco** [comment]
Closing ticket as feedback has been shared with team.
