### ISSUE TITLE
Create wireframes for no stacked alerts on check-in confirmation pages

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#59178]
## Description 

We have 7 different confirmation pages for check-in (based on the travel release). Platform has asked us to remove stacked alerts. 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/59133

We need to apply the solution that we worked on for unified check-in and apply it here. https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/57444

Related ticket for the 1 success confirmation page - https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/59165

## Tasks

- [ ] Finalize wireframes
- [ ] Review with sitewide content, if needed

## AC

- [ ] Wireframes complete
- [ ] Create FE ticket
- [ ] Close platform ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/59133

**Comment by loripusey** [comment]
not going to implement this now in production; separate ticket to address this in the Unified Check-in epic
