### ISSUE TITLE
Research and Implement Improved PE Networking Configurations

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#59194]
# Description
## Givens
* content-build takes a very long time to build
* we use a cached pre-built content-build to save time
* in current testing, the pre-built content-build detects that it is running in a localhost configuration and tries to reach vets-api at localhost:3000
* in EKS, vets-api is not reachable at localhost:3000 from the content-build container
* the [brainstorming](https://vfs.atlassian.net/wiki/spaces/TT4/pages/2645000797/Brainstorm+Preview+Environments) in our session from 5/25

Based on these givens, we believe we should research and attempt to implement the following idea from our brainstorming session --
Change the environment config to detect a preview environment specific URL and append `-api` to the end of the URL where the instance attempts to communicate with vets-api

# Tasks
- [x] Research the feasibility of adding logic to the environments configuration for content-build and vets-website to detect a preview environment URL
- [x] Implement the change in `content-build`
- [x] Implement the change in `vets-website`
- [x] Test locally using a service like ngrok to create a custom URL against local environment
- [ ] Test in EKS / ArgoCD

# Acceptance Criteria
- [ ] The preview environment frontend is communicating with the preview environment backend over a dynamically assigned URL

**Comment by CBonade** [comment]
Idea 2 was an almost instant success! I'm fighting CodeQL on ensuring that our code isn't vulnerable to attacks but once that error is solved these PRs will be open for review.

**Comment by CBonade** [comment]
CodeQL issues are resolved and this solution is merged into both vets-website and content-build.

**Comment by pjhill** [comment]
This works in local testing, but is not working EKS via ArgoCD deployment. We need an additional change.

**Comment by JoeTice** [comment]
Sprint 28 Update - IN PROGRESS - We are continuing to work on this task, it is working locally but not in ArgoCD yet. Work will be completed in Sprint 29

**Comment by pjhill** [comment]
Something changed out from under us in EKS while we were implementing this. For some reason, our latest test in EKS is not being detected as a typical localhost environment. The logic for the environment configuration is now following a different path, we will need to make another change in the environment configuration or somewhere else to detect an instance that is running like a localhost environment but using port 80 for hosting.

**Comment by holdenhinkle** [comment]
Curt's PR:
https://github.com/department-of-veterans-affairs/vets-website/pull/24432

***

Tim Cosgrove's ideas from comments from https://dsva.slack.com/archives/C04CYC4LMU6/p1686336776006339?thread_ts=1686336141.840359&cid=C04CYC4LMU6

IDEA 1
> API_URL is set here - https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/constants/environments-configs.js#L48
>
> would it be enough to set the env variable when you call content-build?
> so like,
>
> `API_URL=<my_dynamic_API_url> yarn build`
>
> and then modify the environment "constants" such that they look for an API_URL already being there and use it if it exists

IDEA 2
https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/utilities/preview-environment/start.sh#LL56C18-L56C48
> in the last line, couldn't you just do `API_URL=<your url> yarn serve`?
>
> if vets-website is looking for an env variable API_URL you could just feed it to the process.
> `yarn serve` is just running `http-server`. I would check but I would assume that would be enough to pass an env variable to it.

***

Ideas:
Set `API_URL` env var here - https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/preview-environment/dev/pe-envs/templates/deployment.yaml#L77

***

Side notes:
Why is this still here? https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/preview-environment/dev/argocd-apps/Chart.yaml

Do we need this? https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/[…]pps/preview-environment/dev/pe-envs/charts/vets-api-0.11.46.tgz

SAVING BEFORE MY COMPUTER DIES

**Comment by holdenhinkle** [comment]
Some quick notes:

Regarding the `rework-pe-frontend` branch - https://github.com/department-of-veterans-affairs/vets-website/pull/24432 - I noticed that vets-website is never being served:

```
# Build and watch vets-website
echo "Install, build, and watch vets-website"
cd vets-website
yarn install --production=false
yarn build:webpack:local

wait
cd ..

# Serve the content-build

mkdir -p content-build/.cache/localhost/drupal
echo "untar the build into content-build/.cache/localhost/drupal"
tar -xf ${AWS_FILENAME} -C content-build/.cache/localhost/drupal



echo "Install and serve content-build"
cd content-build
yarn install
yarn build --use-cached-assets
yarn serve
```

The `content-build` is being served but `vets-website` definitely isn't.

I added the following line - `yarn watch --env.buildtype=localhost --env.api="http://vets-api-web:3004" &`
See https://github.com/department-of-veterans-affairs/vets-website/blob/32c3027110571793b9816ac2d66d9c69231f5739/src/platform/utilities/preview-environment/start.sh#L56

** I'm not sure what the value for `env.api` should be.

I spent a fair amount of time trying to figure out why we're using `yarn watch` to serve vets-website. This command serves the app but watches for changes made to it and then rebuilds it accordingly. Why would we want this in production? Why not use `yarn serve`?

Regarding the team's pairing session last Thursday where we weren't see changes made to the image:
If vets-website wasn't being served, then it wouldn't be serving up the changes made to the image. We would be able to see the code, but it wouldn't be running. Actually, I'm not sure why we would have been able to see the app. Were we seeing static pages? content-build was being served.

I'm looking forward to testing this tomorrow morning.

**Comment by holdenhinkle** [comment]
## Changes:
We're running `yarn watch` now:

```
# Install, build and watch vets-website
echo "Install, build, and watch vets-website"
cd vets-website
yarn install --production=false
yarn build:webpack:local
yarn watch --env.buildtype=localhost &
```

We're also retrieving the content-build from s3 instead of using the drupal cache.

## Working:

- The request URL is being set correctly

## Problems:

- All the links are taking us to production 
- Fonts are trying to be retrieved from a prod s3 bucket
- vets-api is not running where request URL is routed (bad gateway)

**Comment by holdenhinkle** [comment]
## Next Steps:

- Get vets-api working
- Fix links that are currently pointing to prod
- Fix font issue

**Comment by holdenhinkle** [comment]
## Get vets-api working

- Move redis and postgres out of vets-website pod into vets-api pod

**Comment by holdenhinkle** [comment]
We have a new problem. It seems that Pods (at least the vets-website Pod) are updated for no reason at all after several hours?? And result in the preview instance return `Bad Gateway`.

**Comment by pjhill** [comment]
The networking scope of this ticket has been resolved. Some issues remain with our container configuration, but those will be worked under different tickets.
