### ISSUE TITLE
Design | Profile | Dependents | Discovery for understanding what adding dependents to AE Profile might look like

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#59199]
## Background
Discovery ticket to begin understanding what dependents might look like within the profile. 

## Tasks
- [x] review of previous research (Pam)
- [x] review search terms, patterns/behaviors (Liz)
- [x] sync w content/IA folks as they may have details that aren't detailed in research (also be prepared to discuss #59202) (Liz & Pam)
     - [x] what is the veteran mental model around dependents   

## Acceptance Criteria  
- [ ] [summary & recommendations doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2023-06-add-dependents-records-discovery/summary.md) 
- [ ] ready for mock ups / design intent ([artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts))

**Comment by andaleliz** [comment]
This analytics report will be helpful for this work - [YTD search terms people use when they're in profile](https://analytics.google.com/analytics/web/#/report/content-site-search-pages/a50123418w177519031p184624291/_u.date00=20230101&_u.date01=20230611&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=250&explorer-table.filter=~2Fprofile&explorer-table.secSegmentId=analytics.searchKeyword&explorer-table.advFilter=%5B%5B0,%22analytics.searchStartPage%22,%22RE%22,%22~2Fprofile%22,0%5D%5D)

**Comment by andaleliz** [comment]
Progress notes:
- I've added the search/content/nav data to [this draft summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2023-06-add-dependents-records-discovery/summary.md)
- Pam is working on the research review and capturing findings in [this spreadsheet](https://docs.google.com/spreadsheets/d/1YYZEYoMoRqp4lIc3u5dn3L5Oaur-S3c043bswkCuhMo/edit#gid=0)
- We're meeting Tuesday to check in on next steps, who is doing what etc.

**Comment by pamela-drouin** [comment]
Progress notes: 

- Liz and I met today to go over secondary research & takeaways. 
- We decided on the next steps of work
- I will be finishing the [summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2023-06-add-dependents-records-discovery/summary.md)

**Comment by andaleliz** [comment]
[Left feedback on the other ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59202#issuecomment-1618560148)

**Comment by mtcA6** [comment]
@andaleliz @pamela-drouin what's the best way to incorporate additional questions? is it okay to add them to the page? 

eg, you all listed this:
> **Open question**
> What would a user would want to do with their ID card online via Profile (apply/renew, download, etc)?

I'd also want to know if users would want to see this in a digital wallet < this may be encompassed by the "etc" but I think it's worth calling it out

**Comment by andaleliz** [comment]
@mtcA6 thanks for checking - please don't update the document, as it serves as a record of the research we did (and your question is separate from that). 

The _best_ place will be when we put together our research plan and questions, because those are things we will answer when we talk to users.  But, that's on us as researchers to gather that feedback from the team. Typically, I'd do a read out, and I think that'd be a good place to capture questions from teammates. 

Since Pam is a seasoned researcher and led this work, so I want to check with her and see how she'd like to capture these kinds of comments from the team. Can you sit tight for a few days until we have a chance to do that?

**Comment by pamela-drouin** [comment]
@mtcA6 @andaleliz I missed this comment! I have since then cleaned up how I see github notifications!

If there are any additional comments or questions, I think I'd want to keep them here in the comments for whenever the work is picked back up again. I would be checking this ticket's comments whenever we get to developing the research plan.
