### ISSUE TITLE
Get access to the Secure Messaging API test endpoint

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#59206]
## Issue Description
The API test endpoint will be needed to validate code written to support integrating Cerner's internal messaging API into MHV on VA.gov secure messaging.
---
## Tasks
- [ ] Request URL for a test secure messaging endpoint for MHV on VA.gov Secure Messaging from the MHV on VA.gov team

## Acceptance Criteria
- [ ] We have the URL for a test secure messaging endpoint for MHV on VA.gov Secure Messaging
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MarciMcGuire** [comment]
@carlosfelix2 tagging you on this issue so you can see updates.  I will email the MHV on VA.gov team to request a test endpoint and cc you
