### ISSUE TITLE
Diagram current secure messaging/message flag process

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#59205]
## Issue Description
The current My HealtheVet (MHV) Secure Messaging (SM) app provides a mechanism for a patient to be flagged for disruptive behavior.  Based on what we know about the new SM application on VA.gov and Cerner's messaging API, we will create a diagram showing a proposed to-be process.
---
## Tasks
- [ ] Diagram proposed to-be MHV SM/message flag process

## Acceptance Criteria
- [ ] We will have a diagram for the proposed to-be MHV on VA.gov SM/message flag process
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by carlosfelix2** [comment]
Bhanu created a diagram for the blocking flag based on current MHV requirements. See files in Teams' OCC-EHRMIO teams channel.
