### ISSUE TITLE
Design | Profile | Records | Discovery for understanding what adding records to AE Profile might look like

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#59202]
## Background

Out of our logged in IA research we've started to formulate some ideas around things that might be helpful to add into the profile. 

One of those things is 'records'. There isn't a records team or a team so we'll need to start to understand what types of records users look for.  This analytics report is a good place to start - [YTD search terms people use when they're in profile](https://analytics.google.com/analytics/web/#/report/content-site-search-pages/a50123418w177519031p184624291/_u.date00=20230101&_u.date01=20230611&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=250&explorer-table.filter=~2Fprofile&explorer-table.secSegmentId=analytics.searchKeyword&explorer-table.advFilter=%5B%5B0,%22analytics.searchStartPage%22,%22RE%22,%22~2Fprofile%22,0%5D%5D)

`/profile/personal-information` ranks as 19 in the top 20 pages people use search from, and many of the terms (pretty much everything that isn't `dependent` in that report) are related to records.

## Records to investigate:
- [Benefit letters](https://www.va.gov/records/download-va-letters/)
- [ ID cards ](https://www.va.gov/records/get-veteran-id-cards/)
- claim letters (/track-claims/your-claim-letters is one of the top pages along the flow to the claim status tool. It would be interesting to learn where those fit into the Veteran mental model along with benefit letters.) 

## Tasks
- [x] review of previous research (Pam)
- [x] review search terms, patterns/behaviors (Liz)
- [x] sync w content/IA folks as they may have details that aren't detailed in research (also be prepared to discuss #59199) (Liz/Pam)
     - [x] what is the veteran mental model around dependents   

## Acceptance Criteria  
- [ ] [summary & recommendations doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2023-06-add-dependents-records-discovery/summary.md) 
- [ ] ready for mock ups / design intent ([artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts))

**Comment by andaleliz** [comment]
Progress notes:
- I've added the search/content/nav data to [this draft summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2023-06-add-dependents-records-discovery/summary.md)
- Pam is working on the research review and capturing findings in [this spreadsheet](https://docs.google.com/spreadsheets/d/1YYZEYoMoRqp4lIc3u5dn3L5Oaur-S3c043bswkCuhMo/edit#gid=0)
- We're meeting Tuesday to check in on next steps, who is doing what etc.

**Comment by pamela-drouin** [comment]
Progress notes: 

- Liz and I met today to go over secondary research & takeaways. 
- We decided on the next steps of work
- I will be finishing the [summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2023-06-add-dependents-records-discovery/summary.md)

**Comment by andaleliz** [comment]
Hi @pamela-drouin, EXCELLENT job on the summary! I made a few changes but overall kept the content the same
- restructured the heading format
- This is probably the biggest one: I removed the "our recommendations" bullet from each study and instead put them under the "Takeaways relevant to profile" section. I did this so we could be consistent with each section, and there weren't really recommendations coming out of search analytics + content in the same way. I had to slightly rephrase some so it made more sense under that heading, but preserved your same ideas.
- fixed a couple of small typos
- added periods to the ends of bullets (some had them, some didn't, wanted to be consisted with how we used them)
- Added "in Profile" to the end of this sentence: `Use what we learn to inform the information architecture of the Letters page in Profile.`

I'm going to close this ticket for this sprint, and share the summary with Chante. If we need to re-work it again, no problem, we can do it in the next sprint. Great work!
