### ISSUE TITLE
Profile: Sprint 13 (6.21.23-7.4.23) Epic

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#59212]
## Sprint 12 Retro
[EasyRetro Board ](https://easyretro.io/board/f4051524-d7be-43a4-8c50-f43d887f3a7f/054e4dbb-915a-49a0-9907-fd41724539d4)

## Sprint 13 Notes
Sprint 13 epic will be finalized at Sprint Planning -- [see project outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/sprint-objectives/profile/sprints-1-10-Jan23-May23.md#sprint-11) for more info

## 2023 Priorities for Authenticated Experience
<details> 
<summary>2023 Priorities Breakdown</summary>

**High**: 
Migrating MyHealtheVet into VA.gov; 
expanding notification functionality (both onsite and preferences); 
improving the logged-in nav/IA/experience overall; urgent/required maintenance for a feature; unplanned work that aligns with OCTO high-priority objectives

**Low**: 
improvements team wants to make but might fall outside of OCTO objectives
To complete: some initiatives that we should finish but don't fall under OCTO high-priority objectives
</details>

## People News
July 4th
Liz Out 6/26-6/30
Tom Out 7/3-7/6
Berni Out 6/20-6/22
Adam 6/26-27
Pam 7/3

## Capacity Planning 
Engineers: Total of 15 pts (8 for Tom, 7 for Adam)
UX: Total of 21 pts (6-7 for Liz, 14 for Pam)

Adam: 7
Pam/Liz: 18
Tom: 8 + 3pt stretch goal 

## Carry over (modify points in Sprint Planning)
- 1pt for #59915

## Direct deposit migration EVSS > Lighthouse:**
**GOAL: Work through additional BE items that have surfaced**
Other teams have started enabling LH endpoints in production. Using their experience and feedback we're going to work on some additional BE tickets to ensure we're prepared for go-live. We wouldn't see these items impact our testing but they would impact users in production/UAT. 
```[tasklist]
### Direct Deposit Migration
- [x] PM QA Ticket #54870
- [ ] #60481
- [ ] #60477
- [ ] #60478
- [ ] #60483
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/60697
```

## Notification preferences:

**GOAL: Use updated Sketch files to continue FE work**

```[tasklist]
### Default Send / Email as a channel
- [x] Midpoint review for #57409 scheduled for 6/23 @ 2pm
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/59915
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/59940
```

```[tasklist]
### Editing as a subtask
- [x] Midpoint review for #58231
```

## Logged-in IA/nav:

```[tasklist]
### This is a stretch goal:
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/59916
```

```[tasklist]
### Enhanced Personalized Experience
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/59438 < we completed the work that we could, the identity team has to pick this up now. leaving the same ticket open just adding the identity team to it,
```

```[tasklist]
### Dependents / Records
- [ ] #59199 
- [ ] #59202 
```

## General/Other

```[tasklist]
### Tasks
- [ ] #57097
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/58388
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/59300
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/60484
```

## Unplanned Work
- For this sprint -- allot 2-3 points for unplanned work
