### ISSUE TITLE
Copyedit for 2023 audit: Disabilities that appear within 1 year after discharge

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#59239]
## Issue Description
For the annual audit of all the pages in the disability hub, OCTO content lead assessed these 10 content issues on the [Disabilities that appear within 1 year after discharge](https://www.va.gov/disability/eligibility/illnesses-within-one-year-of-discharge/) page and made changes that need copyediting before we republish the page:

- The intro paragraph has no more than 2 to 4 sentences and is within 200 to 400 characters with spaces
- Header levels are hierarchical
- The page has no broken links
- Text links have purpose and target
- The content is free of ability-focused language (view, walk, see, hear)
- Remove "Who's covered?" section (if needed)
- Remove "What kind of disability benefits can I get?" section (if needed)
- Add this Note to the end of the blue box: **Note:** If you get a disability rating, you may also be eligible for VA health care and other benefits.
- Change the H2 from "How do I get these benefits" to "How do I file a claim for compensation?" / add an action link for the CTA and use the label "File for disability compensation online" / Use this text for the link under the action link that should point to the [How to file](https://www.va.gov/disability/how-to-file-claim/) page: "Learn about other ways to file a disability compensation claim"

---
## Tasks
- [x] Copyedit the changes made (review revisions only, not the full page) to https://www.va.gov/disability/eligibility/illnesses-within-one-year-of-discharge/
- [x] Check all links.
- [x] Publish page.

## Acceptance Criteria
- [x] Updates are live on the site.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by megzehn** [comment]
Hi @bethpottsVADEPO, I copy edited this page against the list above, and it looks good!

One Q: This may be for the SME, but do we need to add content under "Am I eligible..." and "What evidence do I need to support my claim?" that covers non-presumptive conditions? Like conditions that they need to provide evidence of being service-connected?

Also I know you're already filing a ticket for this, but I'll note here that we want to eventually move the list of presumptive conditions out of the doc and get those in Drupal.

**Comment by megzehn** [comment]
Update: Sent this over to Paul

**Comment by megzehn** [comment]
Update: SME reviewed the changes, and I published. Updates are live on the site, so I'm closing!
