### ISSUE TITLE
Install and test eslint-import-resolver-alias

### ISSUE THREAD

**Issue by rmessina1010** [department-of-veterans-affairs/va.gov-team#59238]
### The Issue
`@department-of-veterans-affairs/platform-<app-name>/alias` produce a false linting error, stating that the module cannot be resolved. 
Related to: https://app.zenhub.com/workspaces/frontend-cop-backlog-6452b043f27c8b0011a25236/issues/gh/department-of-veterans-affairs/va.gov-team/58721

###  Observations:
- This error occurs only in  applications that have yarn workspaces. 
- There seem to be no apparent  cause in the linting code rules, either  local or in veteran-facing-services-tools. 
- The error is a false positive, that  being that code tests  and compiles despite  the misleading  linting message. 
- The error is exclusive to the alias; eg: `@department-of-veterans-affairs/platform-forms/exportsFile` instead of `@department-of-veterans-affairs/platform-forms/exports' does not trigger the error. ( Note this could be used as work around  until the issue is fixed!).

###. Proposed solution 
Install and configure `eslint-import-resolver-alias` as suggested here: https://www.appsloveworld.com/reactjs/100/13/eslint-typescript-path-in-tsconfig-eslint-unable-to-resolve-path-to-module

###  Documentation for dependency
`eslint-import-resolver-alias
`https://yarnpkg.com/package/eslint-import-resolver-alias

###  Tasks
- [x] Test vets-website  (yarn watch, yarn test) as a reference point
- [x]  Determine whether the `eslint-import-resolver-alias` can be installed in `vets-website` (preferable)  or needs  to be installed in  each module
- [x]  Install `eslint-import-resolver-alias` accordingly
- [x]  Repeat  tests in step 1,  if pass  continue
- [x]  Test at least 4 separate imports, if pass, end ( solution found)
- [x]  Configure based on specific alises, and repeat previous test

###  Definition of Done
- [x] Linting error is resolved 
- [ ] OR dependency is proven incompatible with vets-website, 
- [ ] OR dependency does not solve error.

**Comment by rmessina1010** [comment]
Test of vets-website, base successful. 
Installed `eslint-import-resolver-alias`,  at repo level, for  initial testing.

**Comment by rmessina1010** [comment]
Successful  sample imports/compiles for:

- forms
- forms-system
- static-data
-  startup
-  utilities
-  monitoring

Pending:
-  users*
-  utilities*
-  landing-pages*
-  testing*

Unsuccessful for:

- polyfills ( but this makes sense... polyfill doesn't export functions/vars and needs to be addressed individually)

**Comment by rmessina1010** [comment]
Possible blocker : `user`  compilation  error. 
cause    `fetchLatestTerms, acceptTerms` , required in `AcceptTermsPrompt.js `do not exist in '../../profile/actions'; In fact I cannot find either export anywhere on platform

Commented  out import from from './authorization/components/AcceptTermsPrompt';, error still present

**Comment by rmessina1010** [comment]
Possible blocker : testing  (unit test crash... no error message)

**Comment by rmessina1010** [comment]
Note : `site-wide` compilation error.
'fs' file system, encountered earlier,  not related  to dependency instalation.

**Comment by rmessina1010** [comment]
the linting rule file now imports the babel config json file,  extracts for aliases declared in the config, and configures those automatically.  Essentially, if its config.plugin.aliases , it's reflected in eslintrc.settings[import/resolver]. alias.map.

Updated PR:https://github.com/department-of-veterans-affairs/vets-website/pull/24436

**Comment by rmessina1010** [comment]
Corrected a bug  in eslintrc.js;  fixing the  manipulation of the imported  babel config json data and correctly resoling aliases.

**Comment by rmessina1010** [comment]
With regards to _Possible blocker: user compilation error._
I, found that exports in in question in a 5 year old commit, where they were  moved  out of platform  and into specific applications.  However, stray  imports were left behind and  still attempts the import and exports as to redux (which why  I had concern about nixing this).   
Having found the original platform code for `fetchLatestTerms`, `acceptTerms` , I thought I could reinstate that specific  bit of code into to platform, but it needed other variables to be imported (from src/applications). This would essentially introduce a cross-app import and we do not want that.  I imagine that this is the reason the code was extracted, engineer responsible is no longer with us, so I could not get any context to why.

An alternate  possible solution would be comment out any  exports  of `fetchLatestTerms`, `acceptTerms` in platform/user...  this would cause  a lintining warning,  but  specifically for those two imports, but since those are imports that would error out anyway.. maybe that not a bad thing.

**Comment by rmessina1010** [comment]
With regards to site-wide compilation error ( 'fs' module missing):  the failure to compile  seems to have been resolved by adding ` fs: false`,
 to `fallback`  field in the modules export of `webpack.config.js`, as suggested here: [https://stackoverflow.com/questions/71765550/module-not-found-error-cant-resolve-fs-react-js](https://stackoverflow.com/questions/71765550/module-not-found-error-cant-resolve-fs-react-js) Will test further, but so far it's looking good!

**Comment by rmessina1010** [comment]
Also with With regards to site-wide, I combed through import/exports in  exportsFile.js. The method employed was to comment out all imports, an corresponding exports,  then uncommenting out one at a time and running `yarn test:unit` and `yarn watch `,  if the scripts failed then I recommended out the import/export,  and they can be dealt with at a later date.

During this process, I observed  that, specifically,  imports of .scss files and header/footer/mega menus  caused  the test  to completely crash while other types of imports did not.   Am going over  the other. directories  in Platform  to see if  this assumption is consistent. 

However,  once all the troublesome imports have been  identified, we can safely merge this into main, and  address the cause of the issues with  imports  separately and on a case by case basis.

**Comment by rmessina1010** [comment]
Regarding:  user compilation error.
Slightly similar  to  the issues  with site-wide, I commented out the exports for `MHVApp` and `RequiredTermsAcceptanceView` to prevent  compiling fails until  can get context as to why those dependencies  were moved out of Platform entirely/ and a fix is made.

Running a final check, with intent to merge.
