### ISSUE TITLE
[UX] Submit Translations to the State Department

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#59241]
## Description
Per Collab Cycle feedback, the following needs to be translated to Spanish & Tagalog:
![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/41900076-1e92-466c-a09a-4e3f14167528)

## Tasks
- [ ] Create JSON file with new content to be translated (one for each language)
  - See instructions [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/translations/json-compare/README.md)
- [ ] Create English screen shots for context
  - See examples of screenshots [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/translations/spanish-round-3)
- [ ] Submit JSON file and English screen shots to Randi Hecht for forwarding to the State Department

## Acceptance Criteria
- [ ] JSON file and English screen shots have been submitted to Randi Hecht
