### ISSUE TITLE
[UX] [Content] Create Content to update Text Messages to include Information about Checking in with Mobile App

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#59278]
## Scenario
The Mobile App team is not including a push notification as part of the MVP. We have been asked to update these text messages we send Veterans as part of check-in to ensure that they are aware that they can check-in using the Mobile App.
 - Text message we already send them when they text "check in" to 53079 and we send them a check-in link
 - Text message that we plan to push to Veterans as a 45-minute reminder with a check-in link

## Tasks
- [x] Create content for messages in the 2 scenarios above
- [x] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [x] UI review meeting with product/UX team for feature capabilities
- [x] UI review meeting with engineering for layout and callouts (can be the same meeting as above)

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 @zach-park I've mocked up the final two text messages (Veteran-initiated check in and 45-minute check in) [in my sketch file](https://www.sketch.com/s/170bfa07-46af-4d45-9f66-53406dd93aa3/p/B21D3442-1FF0-4ADB-BE38-4CB473139CC8/). I'm going to move this ticket to validate. Once you've approved them, Ben, and they've been added in Check-in sketch file, Zach, I think we can close this ticket.

**Comment by kellysmith1008** [comment]
Laura provided great feedback, including splitting the text into 2 or 3 sentences and swapping "view" for "find" as they're moving away from sighted language in VA content. [I mocked up her suggestions](https://sketch.com/s/170bfa07-46af-4d45-9f66-53406dd93aa3) and will run them past the UX team on Tuesday - we'll get a decision from the UX sync and then can close this ticket.

**Comment by benbrasso-agile6** [comment]
Whenever Zach gets them into sketch, here’s that slack thread I was talking about to post them in: https://dsva.slack.com/archives/C022AC2STBM/p1686080601673549

**Comment by kellysmith1008** [comment]
@zach-park Can you share the sketch link to the text messages in the slack message Ben listed above? We can close this ticket once that's done. Thanks!

**Comment by zach-park** [comment]
@kellysmith1008 , sure, here is the [link](https://www.sketch.com/s/28e5020d-7d1f-461c-a7a0-d31bb57afdaa/p/362B013A-C05E-4040-9AE9-8F0E4BA12632/canvas): https://www.sketch.com/s/28e5020d-7d1f-461c-a7a0-d31bb57afdaa/p/362B013A-C05E-4040-9AE9-8F0E4BA12632/canvas
