### ISSUE TITLE
[UX] [Design] Create Final Wireframes for Adding Mobile App Info to the Pre-Check-in Completion Page

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#59275]
## Scenario
The Mobile App team is not including a push notification as part of the MVP. We have been asked to add information to the Pre-Check-in completion page to let Veteran know that they can check-in using the Mobile App.

## Tasks
- [x] Create final mockups with callouts 
- [x] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [x] UI review meeting with product/UX team for feature capabilities
- [x] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [x] Wireframe available on Sketch Cloud
- [x] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.

**Comment by zach-park** [comment]
Per the UX discussion, it is determined that no CIE UI design work would be necessary. Cc: @benbrasso-agile6 @kellysmith1008

**Comment by benbrasso-agile6** [comment]
We will want to mention this to maybe a smaller group of people in Slack to get their thoughts, e.g., Lori, Stephen, Kristen. And, when ready, submit a ticket to Randi about this work that their team will need to work on. They will likely need some of our help.

**Comment by loripusey** [comment]
We need to start this discussion ASAP. Thanks @zach-park

**Comment by benbrasso-agile6** [comment]
The appointments office hours meeting we will talk about it. Kristen and sitewide content should both be there.

**Comment by benbrasso-agile6** [comment]
Sounded like Kristen was fine with the approach of updating the [how to check in with your smartphone page](https://www.va.gov/resources/how-to-check-in-with-your-smartphone-for-some-va-appointments/) instead of adding more content on the pre-check-in confirmation page. @kellysmith1008 @zach-park would you mind maybe just pinging Stephen about this decision in slack. And, we'll need to start a [sitewide intake ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=RLHecht%2C+coforma-terry&labels=sitewide+CAIA%2C+sitewide+content-product+support%2C+Sitewide+IA%2C+sitewide+content&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E) for this work, which the sitewide team should be writing. We probably want to include Misty, Meko and Kristen on that ticket too because this is sort of a cross-team initiative. The published date would be TBD. We'd probably need more information from OCTO team about the timeline for this page being completed.

**Comment by kellysmith1008** [comment]
@zach-park @benbrasso-agile6 I can create the intake ticket for our request and copy MM&K on the ticket. Can we PL this for standup to show Stephen? Also, Ben, when you say we'd need more information from the OCTO team about the timeline - is that something I need to gather? In other words, does not having this information published block us in any way? Or do you mean I should let someone on the VA mobile team know that the outcome of this ticket and let them monitor the timeline?
