### ISSUE TITLE
[CST] Create endpoint for 5103 submission

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#59279]
## Background
The Lighthouse Benefits Claims API provides us with 3 different endpoints that we are interested in using with the CST: 2 for index/show for claims and 1 for submitting the 5103 Notice. We have implemented the first 2 on the backend, but need to implement the 5103 Notice in vets-api

## Tasks
- [ ] Add route for 5103 endpoint
- [ ] Add method to BenefitsClaimsController for 5103 endpoint
- [ ] Add method to BenefitsClaims::Service as well
- [ ] Update any specs involving the controller or service

## Acceptance Criteria
- [ ] 5103 route is ready for use by the FE
- [ ] Tests are accounted for
