### ISSUE TITLE
[eFSR] Remove nested fieldsets for all pages

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#59289]
## Issue Description
Need to remove nested fieldsets as they are an accessibility issue for screen readers. 

---
## Tasks
- [x] Refactor each page that has nested fieldsets with semantic HTML.

## Acceptance Criteria
- [x] Each page with a nested fieldset will no longer have one and have semantic HTML instead. 
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
@josephrlee - Was this work to satisfy this request: #60040? 

cc: @Tom-Davis

**Comment by josephrlee** [comment]
@HeatherRienks , yup!

**Comment by HeatherRienks** [comment]
Awesome - I will close out that Platform ticket then! TY!
