### ISSUE TITLE
(Research) 10-10EZ - Reg Only: Research Study Planning

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#59288]
## Background
While we still have questions open for the business to clarify, we can start on creating a research plan and conversation guide for Veteran facing research.  

Here is the working [Mural board
](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684348883203/49fc4ff1bf31f3cabe200663708c1002645b447f?sender=u5ad49c107baa41137f271007)

---

**Not for staff facing research:** We should collaborate with the VES Modernization team to gain any potential insights that will work with both efforts. We will also add additional questions to upcoming EZR staff facility meetings/interviews with a goal of better understanding the overall problem space. See ticket [#59891](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59891) for staff facing research. 

---

Being in the generative research phase, we plan to conduced an iterative exploratory interview study that can happen simultaneously as the staff facing and other desk research.

**For Veteran facing research:** We will conduct 2 studies; the first an iterative interview study where we can learn more about the Veteran's mental model of the registration/enrollment process and terminology used as well as get very early feedback on hypothesis "registration only" pathways. The second study will be testing a prototype of the pathway direction(s) and include content feedback. 

- [Research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/research/2023-06-Registration%20flow%20exploration)

- Methodology: Conduct an iterative interview study where we can learn more about the how Veterans look back on their application process including terminology used. We will conduct this in 3 cycles so we can gain a better understanding of the Veteran's perspective while exploring early hypothesis scenarios of "registration pathway" that aligns with the Veteran's mental model and work on building the prototype. 

**Additional research:**
- Desk research includes current page analytics analysis around the research goals and questions outlined in Mural board
- Keyword analysis and review within VSignals
- Medallia feedback around key terms 

----

## Tasks

- [x] Create Mental Model [Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2023-06-Registration%20flow%20exploration/research-plan-mental-model.md)
     - Target audience? Recent Veterans who have registered and/or enrolled in health care recently (see screener questions in plan, two cohorts to target possible registration group)
     - What do we hope to learn/achieve? Understand more about Veteran's mental model around the terminology and process of applying for health care benefits.
     - What assumptions do we have? See Mural board
- [x] Create [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2023-06-Registration%20flow%20exploration/conversation-guide-mental-model.md)
- [x] Review with team for final approvals before submitting to repo 

--- 
MOVE THESE TASKS TO NEW TICKET

- [ ] Create Prototype 
- [ ] Create Hypothesis Flow [Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2023-06-Registration%20flow%20exploration/research-plan-prototype.md)
     - Target audience? 
     - What do we hope to learn/achieve? Check a hypothesis flow for early feedback and get initial content / process feedback.
     - What assumptions do we have? TBD
- [ ] Create [Conversation guide](url)

## Acceptance Criteria
- A research plan and conversation guide are created and ready for review

**Comment by jessicastump** [comment]
- [Research Plan Draft](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2023-06-Registration%20flow%20exploration/research-plan-mental-model.md)
- [Convo Guide Cohort 1](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2023-06-Registration%20flow%20exploration/conversation-guide-mental-model-cohort1.md)
- [Convo Guide Cohort 2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2023-06-Registration%20flow%20exploration/conversation-guide-mental-model-cohort2.md)

**Comment by jessicastump** [comment]
The research plan and convo guides have both been updated since last discussed and added print instructions scenario to convo guides. 
- [Research Plan Draft](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2023-06-Registration%20flow%20exploration/research-plan-mental-model.md)
- [Convo Guide Cohort 1](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2023-06-Registration%20flow%20exploration/conversation-guide-mental-model-cohort1.md)
- [Convo Guide Cohort 2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2023-06-Registration%20flow%20exploration/conversation-guide-mental-model-cohort2.md)

The dates are currently TBD at September 13 - 22 and this is ready for final reviews/approvals pending how next week goes with EZR work. Let's touch base the week of August 21st and see if this is ready to submit to the repo for review and recruitment or if we need to adjust dates again. 
cc @hdjustice @katelyncai @kristenmcconnell

**Comment by jessicastump** [comment]
Link to [research repo ticket](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/371). this has been submitted and review/recruitment has started.
