### ISSUE TITLE
Update BDD Product Documentation to add BDD SHA 

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#59290]
## Tasks ##
- Update BDD product guide found at https://github.com/department-of-veterans-affairs/va.gov-team/blob/e8022d2012f42652dbf2378a30bc92c1fa4864be/products/disability/526ez/archive/product/526%20Benefits%20Delivery%20at%20Discharge%20-%20Product%20Guide.docx
- Add a change log inside the doc, starting with v1.0 to acknowledge the existing content which we don't know the history of. New changes will start with v2.0
- Scope of this ticket is to update the BDD Product guide with changes for BDD SHA Part 1

Note: There may be several changes needed to make the doc current, so that will be addressed in a separate ticket

## Acceptance Criteria ##

- [x] Doc is updated with BDD SHA info and uploaded to new product guide home https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez/product
- [x] Doc is reviewed by Design
- [x] Link to the new doc is updated on the contact center review ticket - [#59016](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/59016)

**Comment by RakshindaAslam** [comment]
@RakshindaAslam - review BDD product guide changes
