### ISSUE TITLE
[FE] 10-10EZ - Household: BUG - Fields showing errors before input

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#59296]
## Background
Per [this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/51641#issuecomment-1564901998) on the QA ticket, the issue found went as follows:

Use Case F:
- I entered the second dependent, on that page i mistyped the birth month and corrected it on the same screen, however the subsequent screens are prompting me with an error on a field I have only just now seen.  **Could this be due to the URL not changing for the dependent info?**

- 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/7a565879-9764-4c1b-ae35-e2c2c64c84a7)

- 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/3abc0bef-1ef7-4216-a29f-d735c9b1f31a)
- 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/fdcd7473-3185-46c3-bab4-ae1b7bd0dbc3)

## Tasks
- [ ] Determine the root cause of the field errors when there has been no attempt at input
- [ ] Determine solution, if any
- [ ] Implement solution
- [ ] Test using scenario above, document successful results (comment on this ticket and @hdjustice)
## Acceptance Criteria
- A solution was determined and implemented, or no resolution can be found.

**Comment by hdjustice** [comment]
Validated that this issue has been resolved.  I no longer see the error messages on subsequent pages when I have not accessed them yet.
