### ISSUE TITLE
Profile | MHV and DS Logon Users | Investigate authorization rules for managing demographic info | EPIC

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#59301]
## Core Issue

If a user logs in with DSLogon or MHV (which is always brokered through ID.me), should they be able to update preferred name and gender identity?

## Background

On May 24th, the mobile team brought up an issue in the #va-profile channel about allowing users that logged in using DSLogon (DSL) or MHV to update their preferred name and gender identity updates.

[See this thread](https://dsva.slack.com/archives/C7TE0PFTL/p1684946206797519) for more details on the conversation.

Our documentation states...

> To access personal information data, a user must authenticate with an identity verified account through either a ID.me or Login.gov (DS Logon and MHV credentials are gated because of security issues).

VA Profile is the backend system that stores demographic data for a user.  The following is from their documentation...

>  _A user must have a `CSP ID` *and an assigning authority of either* `PN^200IDME^USDVA` or `PN^200VLGN^USDVA`. If not, then an access denied error is returned from VA Profile..._
>
> _CUF_ACCESS_DENIED | CORE101 | You do not have access to perform the requested operation. Please correct your request before trying again! If you believe you have received this access denied error incorrect, please contact your system administrator._

At the time the demographic service was built, my assumption was that if a user logged in and had a CSP ID from ID.me or Login.gov, then they must have signed in using ID.me or [Login.gov](http://login.gov/).  However, after further discussion we discovered that any time a user signs in using MHV or DSLogin, the authentication is brokered through ID.me.  Because of this, a CSP ID from ID.me is present on the user session even when a user signs in using MHV and DSLogon.  

Based on this discovery, we believed that the authorization logic I initially implemented was incorrect, which was backed further by Jayson Perkins statement...

> *For what it's worth, every other feature I've seen in vets-api that has similar restrictions checks the actual CSP of login instead of for those UUIDs.*

In other words, the authorization check should not check whether the user has a CSP ID from ID.me or DSLogon, but rather which CSP the user signed in with.  If a user signs in using MHV or DSL, they shouldn't be allowed to manage preferred name or gender identity. If a user signs in using ID.me or [Login.gov](http://login.gov/), they are good to go.

After discussing this situation with the mobile team and va-profile team, we concluded that the authorization logic for the demographic endpoints in vets-api should be updated to reflect the new understanding of the business requirements.  On May 25th, the authorization changes were made through this [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/12813#event-9352704256).  

As a result, the authorization logic for demographic endpoints now checks which CSP the user logged in with (not whether they have a CSP ID from ID.me or Login.gov).  Previously, if a user did not have a CSP ID from ID.me or Login.gov, a `401 Unauthorized` status code was returned.  Now, if a user signs in using DSLogon or MHV, the demographic endpoint will return a `403 Forbidden` status code.

The changes went into production on May 26th and the authorization changes affect the following endpoints:

- `GET https://api.va.gov/v0/profile/personal_information`
- `PUT https://api.va.gov/v0/profile/preferred_names`
- `PUT https://api.va.gov/v0/profile/gender_identities`

Some errors related to these endpoints have been logged to Sentry since May 26th, but the totals are lower than what we usually see and the types of errors are similar to what we usually see as well.  

However, the user experience may be different and the Profile team has some concerns about the change.

## Questions to investigate

1. If a user does have a CSP ID from the correct assigning authority (ID.me or Login.gov), why shouldn't they be able to manage their demographic info? Particularly if ID.me brokers (authenticates) DSL and MHV logins. It could be confusing for a user to be able to manage demographic info if they sign in using IDme or [Login.gov](http://login.gov/), but not if they use DS Logon or MHV.  
[slack thread ](https://dsva.slack.com/archives/CSFV4QTKN/p1684976391578659)
2. If they can't manage their demographic info through DSL or MHV, should they be able to manage any other parts of profile? 
3. What message is currently being displayed to a user if they are unable to manage their demographic information?
**Answer:** Users currently see our [system error behavior.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/use-cases/system-cant-display-personal-info.md)
4. What message should be displayed to a user if they are unable to manage their demographic information?
**Answer:** We should probably do something similar to the [gate we have for direct deposit](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/use-cases/gate-mhv-dslogon.md), although we might not need to gate the whole page.

## Tasks

- [ ] ~~Get answers to above~~ 
- [ ] ~~Determine if we need to update the UX for personal information, or all of profile~~ 
- [ ] ~~If we make any changes, alert the contact center team (next step, in a separate ticket, will be to update the contact center guide)~~

**Comment by andaleliz** [comment]
@tpharrison IMO the ticket is super clear - thank you for putting this together!  Who can definitively answer question 1? I think based on that, our team can determine the answer to the second question.

It occurred to me last night that we _may_ need to alert the contact center about this in case they get calls about people not able to update their personal information, especially since this is the profile landing page. Looking at analytics, it doesn't look like this is impacting much so maybe it's not really a big deal. I don't think there's a way in analytics to tell what credential people are logging in with which makes it hard to know how many people get this error.  @mtcA6 normally this is a product decision, so I think this piece is your call.

**Comment by tpharrison** [comment]
@andaleliz Josh Lindsay from VA Profile recommended that we reach out to Danny Reed at MPI.  I don't think he's on Slack, so I'll reach out to him through email and CC our team.

**Comment by tpharrison** [comment]
Sent an email to Danny Reed (Danny.Reed@va.gov) on May 31st.

**Comment by mtcA6** [comment]
how do we tell if a user has a "wrapped" session?

> **Patrick Vinograd:** What I want to avoid is if there's any chance that we're saying "veteran signed in at some point with ID.me, therefore was identity proofed, therefore this current unwrapped MHV session is secure"  - because it's not, having a separate account says nothing about the security of this current session.
But, a wrapped session using a DSL credential is in fact an ID.me session - they are acting as the identity provider, they are vouching for the identity proofing and MFA happening, it's just a different username/password database.

**Comment by andaleliz** [comment]
@mtcA6 was that from a Slack convo? If so would you mind linking the thread too, just so I can get some more context?

Does that mean that this really should only impact MHV users, and not DSL?

**Comment by tpharrison** [comment]
@andaleliz It's from the thread referenced above.

**Comment by andaleliz** [comment]
Got it, thank you @tpharrison

**Comment by mtcA6** [comment]
The way I'm reading this, 

IF MHV and DS logon use ID.me as a broker for identification 
AND that is a 'wrapped' session 
THEN they should be able to edit the info.

IF MHV and DS logon use ID.me as a broker for identification 
AND it is not a 'wrapped' session 
THEN they shouldn't be able to edit the information 

That's why i asked the question, how can we tell if it's a wrapped or unwrapped session? that would then help us answer question one, i think.

**Comment by tpharrison** [comment]
From team discussion on June 2nd...

We decided on the following next steps:
-  Add a feature toggle (`profile_personal_info_authorization`) that will allow us to toggle between old and new authorization policies.
- Add FE alert to notify users when they are not authorized to make demographic updates.
- Haven't heard back from Danny Reed, so Chante suggested that we reach out to Damien DeAntonio.

**Comment by tpharrison** [comment]
Reached out to Damien DeAntonio is Slack ([see thread](https://dsva.slack.com/archives/CSFV4QTKN/p1685730524373289?thread_ts=1684976391.578659&cid=CSFV4QTKN)).

He asked to be added to the email thread and responded with...
> I don’t see why the MHV or DS Logon users would be treated any differently.

**Comment by tpharrison** [comment]
- [Ticket for feature toggle](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59409).
- [PR for feature toggle](https://github.com/department-of-veterans-affairs/vets-api/pull/12869)

**Comment by tpharrison** [comment]
After further discussion, the Mobile team decided to revert back to the original authorization rules.  See this PR - https://github.com/department-of-veterans-affairs/vets-api/pull/12890.

**Comment by tpharrison** [comment]
Waiting for PR https://github.com/department-of-veterans-affairs/vets-api/pull/12890 to be deployed to staging.

**Comment by tpharrison** [comment]
Followed up with mobile team in [this thread](https://dsva.slack.com/archives/C7TE0PFTL/p1686255500367479?thread_ts=1684946206.797519&cid=C7TE0PFTL).

[This PR](https://github.com/department-of-veterans-affairs/vets-api/pull/12890) will revert back to the original authorization rules.

Will verify in staging/production tomorrow.

**Comment by andaleliz** [comment]
@tpharrison, I tested this with @pamela-drouin and everything looks good for MHV and DSLogon users on staging 🎉
