### ISSUE TITLE
Publicize Survey in Slack

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#59318]
## Purpose
Step through the tasks to prep, launch, run, and synthesize the quarterly survey

## Tasks
- [x] Verify that Platform's [Survey page](https://depo-platform-documentation.scrollhelp.site/support/platform-satisfaction-survey#PlatformSatisfactionSurvey-ThesurveyiscurrentlyclosedRedforthisquarter.) is showing the Survey as OPEN.
- [x] Publicize Survey (Slack)
-draft messaging
-execute messaging
- [x] Schedule reminders in Slack

## Acceptance Criteria
- [x] Survey is socialized in Slack
