### ISSUE TITLE
[FE] Severity 10: Breadcrumb Live Region

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#59315]
## Issue
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/b9124ab4-d407-4a72-9f86-ff30e15ff053)

Original Spreadsheet Source for Issue: [Mobile Audit 05102023 Patient Check-in (eCheck-in  Pre-Check-in) Web.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11614848/Mobile.Audit.05102023.Patient.Check-in.eCheck-in.Pre-Check-in.Web.xlsx)

## Tasks
- [x] [FE] Resolve issue
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [x] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [x] Read ticket details and verify that ACs are met
- [x] Review code in PR
- [x] Run branch locally
- [ ] Check that new and updated translations use new keys
- [x] Check for hardcoded strings
