### ISSUE TITLE
Demo Satisfaction Survey

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#59326]
## Purpose
Present Q3 results at Demo day

## Tasks
- [x] Share with PO for feedback prior to Demo Day
- [x] Present Presentation at Demo day

## Acceptance Criteria
- [x] Presentation is delivered.
