### ISSUE TITLE
Design System Staging Review: Converted Segmented progress bar / Step Indicator to USWDS v3 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#59349]
## Design System Staging Review
Staging review request for Converted Segmented progress bar / Step Indicator to USWDS v3 
  
#### Design System actions
- Navigate to reference link: [Design System Staging Review Guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572025931/Design+System+Staging+Reviews)  
- [ ] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the Design System meeting attendees email addresses
      - Invite all relevant Design System team members
   - Click "Schedule Event"
- [ ] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
 
##### Staging Review artifacts

- [ ] All URLs (design system and storybook)
-  Sketch - https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4/p/2FCC2B76-88D4-477C-AF19-EC1A1A6DA6B7/canvas 
-  Storybook https://design.va.gov/storybook/?path=/docs/uswds-va-segmented-progress-bar--default 
- [ ] [QA E2E tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-e2e-test-participationE2ETestParticipation) (provide a link to the product’s code)
- [ ] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D). For details, see [Prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).
  
#### Platform actions
- [x] [Staging review Slack thread with VFS team](Staging Review - Design System Team)
- [x] Meeting date/time: June 8, 2023 at 1:30pm ET

#### Platform actions

- [x] Update this ticket with the Zoom recording
  - Recording URL: [Zoom recording](https://oddball-io.zoom.us/rec/share/_hJMWuXyBgLy_nd4vWFMmhmXH62rREKBsU-zQvMP1uKL6nojlLACAWqXOr_IHzi7.Xuv6GL5CD98kHcJv)
  - Password: `yb?jlsS4`
  
#### Design System actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] Close ticket

**Comment by CherylEvans** [comment]
No Content FB.

**Comment by sterkenburgsara** [comment]
No IA feedback.
