### ISSUE TITLE
686c | Transition work to new team

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#59354]
## Value Statement

**_As_** the new team responsible for 686c
**_I want to_** have sufficient context on past, present, and planned 686c work
**_So that_** I can pick up where the previous team left off, without anything falling through the cracks.

## Background Context

We are transitioning 686c work to a new team. We would like to start that transition process on June 6, 2023. Please see the following list of tasks for more detail on what is necessary to get the new team up to speed.

## Acceptance Criteria
- [x] New team understands reprocessing work
- [x] New team understands Sidekiq work
- [x] New team can pair with Brandi and Matt B. during IPT meetings

## Tasks
- [x] Add new team to the "Dependency Applications IPT" Teams chat and provide context.
- [x] Include new team on "Dependency Applications IPT" recurring Tuesday meetings and provide context.
- [x] Add new team to the "Reporting File # and SSN issues observed during Form 686c submission" Teams chat and provide with context.
  - See https://github.com/department-of-veterans-affairs/va.gov-team/issues/57798#issuecomment-1622457644 for context.
- [x] Add new team to the "526 Failures 686 Issues Ch. 31 Defects" Slack chat and provide context.
  - Looks like you can't add more than 9 people to a Slack group chat, so I'm unable to add @tblackwe or anyone else to this chat. I think that's okay though. This chat hasn't been active for about a month.
- [x] Give new team a list of contacts who may be helpful during the 686c work.
  - See https://docs.google.com/document/d/1VkTxa4sgE5mhOJmzgSqJX_lDcaXwy0SRZCcia3aCgIU/edit?usp=sharing
- [x] Give new team Datadog and Sentry dashboards related to 686c work and provide context.
  - See https://docs.google.com/document/d/1voc1LaQQhWU3Ur9ULNog0qy4i74MGKyhfCTAcl26K34/edit?usp=sharing
- [x] Update the progress tracking spreadsheet shared with Brandi, share with new team, and provide context.
  - Will talk through this on call.
- [x] Give new team the "RBPS Reprocessing Estimates" document and provide context.
- [x] Update 686c epic, share with new team, and provide context on each ticket therein.
  - Will talk through this on call.  See https://docs.google.com/document/d/1EhaR_HBWaYxB-Mhl0INvLZKrDNyd44veDi_CXtaWKX4/edit. 
- [x] Share 686c logging and monitoring tickets with new team and provide context.
  - Will talk through this on call.  See https://docs.google.com/document/d/1EhaR_HBWaYxB-Mhl0INvLZKrDNyd44veDi_CXtaWKX4/edit. 
- [x] Give new team a tour of relevant 686c code and record a video of this tour for their future reference.
  - Will talk through this on call.
- [x] Give new team context on downtime notifications, maintenance windows, and the #evss-prod Slack channel.
  - Will talk through this on call.  See https://docs.google.com/document/d/1EhaR_HBWaYxB-Mhl0INvLZKrDNyd44veDi_CXtaWKX4/edit.

## Definition of Ready
- [x] Eugene updates progress tracking spreadsheet shared with Brandi.
- [x] Eugene updates 686c epic.
- [x] Eugene and Sade create document summarizing the current state of affairs for 686c work, including bug fixing and null claim reprocessing.
  - See https://docs.google.com/document/d/1EhaR_HBWaYxB-Mhl0INvLZKrDNyd44veDi_CXtaWKX4/edit
- [x] Eugene knows who the new team is and who specifically will be working on 686c.
- [x] The new 686c team has access to VA remote desktop, VA Github, VA Slack, VA Datadog, and VA Sentry. 
  - Thomas has access and can give the rest of his team access when possible.

## Definition of Done
- [x] All documents referenced above have been updated to reflect the current state of 686c work.
- [x] New team added to all channels, meetings, documents, and dashboards referenced above, and is sufficiently familiar therewith.
- [x] Team's engineers are sufficiently familiar with the 686c code.

**Comment by data-doge** [comment]
Hey @saderagsdale, here's a first pass at a transition ticket for the 686c work.

**Comment by saderagsdale** [comment]
Thomas will notify us when developers are ready to begin KT.

**Comment by saderagsdale** [comment]
@data-doge anything else we need to do with this?

**Comment by saderagsdale** [comment]
@data-doge remind me if we need to do anything else with this?

**Comment by data-doge** [comment]
@saderagsdale Once @tblackwe starts presenting in 686c IPT meetings, we can close this ticket. So I believe we'll able to close this ticket on Tuesday (7/25) afternoon!

**Comment by data-doge** [comment]
@tblackwe did an excellent job presenting on behalf of OCTO, in my stead, at today's IPT. Closing this ticket
