### ISSUE TITLE
[FE] My VA Claims section: investigate claims and appeals event tags

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#59400]
## Background
Similar to what we were seeing with the payment info event tags in #57991, there appears to be an issue with previous GA event tags still showing up in GA and domo with event activity even after the newest iteration has launched to 100%

- Prior to release of My VA audit updates, the claims and appeals section had a link to "check your claim or appeal status" with the event tag `Navigation - Link List - Claims and appeals - Check your claim or appeal status`
- With the audit UX updated came a revised link to "Manage all claims and appeals" with the event tag `Navigation - Link List - Claims and appeals - Manage all claims and appeals`
- We started the phased launch of the audit work on 4/11/23, and completed it on 4/25/23, which means from 4/11 through 4/24, we should see clicks on both event tags as the old version and new version were visible at the same time to different segments of users
- We completed the phased launch of the audit updates on 4/25/23, meaning the new version of My VA was available to 100% of users, and as a result no users should be seeing/clicking the "Check your claim or appeal status" link (`Navigation - Link List - Claims and appeals - Check your claim or appeal status`), ONLY the "Manage all claims and appeals" (`Navigation - Link List - Claims and appeals - Manage all claims and appeals`)

## Tasks
- [ ] Investigate what's happening here (FE): locate where in the code we're still showing the user the "check your claim or appeal status link" and corresponding event tag (`Navigation - Link List - Claims and appeals - Check your claim or appeal status`)
- [ ] Identify and implement solution
- [ ] Have Analytics team test/check for us (if necessary)
- [ ] Document explanation in GH (PM)

## Acceptance Criteria
- We no longer see engagement on the old "check your claim or appeal status link" and corresponding event tag (`Navigation - Link List - Claims and appeals - Check your claim or appeal status`)

## Resources
Domo screenshots
**Phased launch period**
![Domo claims and appeals phased launch period](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/e9d163a3-c661-43ac-b138-413a7adc8595)

**Launched to 100% - still seeing engagement on the old "check your claim or appeal status" link**
![Domo full launch to 100p claims and appeals links](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/cec35349-20b5-4e12-9b16-bd9fb33b1155)

**Comment by ajakabcin** [comment]
Just checked Domo this morning and the `Navigation - Link List - Claims and appeals - Check your claim or appeal status` is gone from tracking as of yesterday's metrics. Woo! Thanks @dellerbie !
