### ISSUE TITLE
[FE] "TTY:" part should be inside the link with the 711

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#59401]
## Background
As part of the midpoint review, this issue was uncovered.
- Must: Super small thing: In the Need Help section, any time you have a TTY 711 link the "TTY:" part should be inside the link with the 711. When coding everything the tty attribute on the va-telephone component does all the formatting for you.

[Original ticket](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/58952)

## Tasks
- [ ] [FE] **_insert frontend work_**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [x] Read ticket details and verify that ACs are met
- [x] Review code in PR
- [x] Run branch locally
- [x] Check that new and updated translations use new keys
- [x] Check for hardcoded strings
