### ISSUE TITLE
BE| Profile | DS And MHV Logon Users | Personal Information | Add Feature toggle for authorization

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#59409]
## Background
Authorization rules for personal information were recently changed to check a user's CSP (credential service provider) so that if a user signs in with MHV or DSL, they will not be able to view or update demographic information (preferred name and gender identity).

Add a feature toggle that when turned on will check if a user is LOA3.

## Tasks
Add feature toggle to the following endpoints:
- [ ] GET /v0/profile/personal_information
- [ ] PUT /v0/profile/preferred_names
- [ ] PUT /v0/profile/gender_identities
  
## Acceptance Criteria
Test the following in staging and update ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/59301 with results:
- [ ] MHV user with toggle off
- [ ] MHV user with toggle on

**Comment by tpharrison** [comment]
@adamwhitlock1 @andaleliz @mtcA6 

In order to toggle authorization rules, a change needs to be made the demographics service that is used by the mobile team.  Before making the change, I want to review it with Jason Conigliari from the mobile team.   He's on the west coast, so we probably won't meet until after 12pm ET.

**Comment by tpharrison** [comment]
Opened a draft PR that I'll review with the mobile team tomorrow.

**Comment by tpharrison** [comment]
@mtcA6 @andaleliz @adamwhitlock1 

There are still a few issues remaining with mobile-related specs.  Jason Conigliari is working on making fixes, so the PR won't get into staging until Monday, June 5th.

**Comment by tpharrison** [comment]
After further discussion, the Mobile team decided to revert back to the original authorization rules.  See this PR - https://github.com/department-of-veterans-affairs/vets-api/pull/12890.

Closing this ticket and associated PR.
