### ISSUE TITLE
Design for toxic exposure screens

### ISSUE THREAD

**Issue by lydiahooper** [department-of-veterans-affairs/va.gov-team#59404]
Note prototypes do NOT reflect feedback from CAIA or VBA

###Collab Cycle needed
Yes

###Desc
The 526ez and ancillary paper forms get updated when necessary. This ticket is part of work required to get the digital 526ez form on va.gov sync with the paper version. The scope of this work is to create prototypes for the new screens for usability testing.

Note the implementation of these changes should also include updating existing disabilities and evidence page(s) including to answer Qs about presumptive

Content ticket: https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/60669

### Tasks
- [x] Create draft prototypes using design system guidance
- [x] Meet with Nyantee about research plan

###Need to Know
- [x] Testing on mobile only
- [x] 16 total mobile screens (A test is 5 screens, B test is 2 screens)

###Acceptance Criteria
- [X] Draft prototypes

**Comment by lydiahooper** [comment]
Sketch file: https://sketch.com/s/c353146f-eceb-4626-9918-7603c693417f
See toxic exposure collab cycle epic for additional tickets: https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/60140
