### ISSUE TITLE
[SPIKE] [UX] Which solution will solve the accordion issue? 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#59416]
## Description 

Which design solution will solve the accordion issue getting the "how do update information" out of accordion and on to the page for pre-check-in confirmation page? 

Address the "How to update my information" accordion and IA on pre-check-in confirmation pages

> Placing this inside a Q&A seems to hidden 

Link to comments in sketch: 

https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/zx95r4b?annotation=cd106215-841f-49ce-a5d8-28e62530d91a&utm_medium=email&_hsmi=210989272&_hsenc=p2ANqtz-88FTnJen9W8bd_17ZFKRcn1iffYEZ5E66pIUncWLkpGI-AlWH0tsGAJY3xqMmYMIrdTdKYtM48zCozbu2DT_mdQgSkMA&utm_source=hs_email#Comment

https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/zx95r4b?_hsenc=p2ANqtz-9IHIIoGU0NVMKgjtoDdRRDsCTeYibuvdbVoViM_Gzyqo3FvMIZRado3fT4S1aI3OkXyJuSnJx0FI8CWG1yssDQL1xlAQ&_hsmi=210989272&annotation=673580ac-e110-41d4-b8f6-c10cc42736b0&utm_medium=email&utm_source=hs_email#Comment

[Related ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57444)

## Tasks

- [ ] Review with Laura
- [ ] Review feedback from Laura with UX team 
- [ ] Determine next step

## AC

- [ ] Determine next step

Note: Solution will be applied via this ticket - https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/59309
