### ISSUE TITLE
[FE] My VA Claim Status EVSS > Lighthouse: Update claim status widget on My VA

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#59410]
## Background
Per discovery in #54406 we'll need to update the claim status widget on My VA to point to Lighthouse instead of EVSS.

## Tasks
- [x] Create a feature flag for this work: (`my_va_lighthouse_claims`)
- [x] Create a new action that uses v0/benefits_claims. See: [current action](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/actions/claims.jsx#L147)
- [x] Update the [ClaimsAndAppealsV2.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/claims-and-appeals-v2/ClaimsAndAppealsV2.jsx) component to use the new action
- [x] Update the isClaimsAvailableSelector to include the new the lighthouse service
- [x] Confirm the proper [service name](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/user/profile/constants/backendServices.js#L8-L9) to use
- [x] Update tests

## Acceptance Criteria
- [x] Claims status widget functions properly on My VA after being pointed to the new Lighthouse endpoints

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ A dev for technical validation, any team member for functional on My VA
- _How can this work be validated?_  Confirm BE and FE code points to correct place 

## Resources
- [Derrick's technical discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/claim-status-lighthouse-migration/technical-discovery.md#technical-discovery-evss--lighthouse---updating-the-claim-status-widget-on-my-va)

**Comment by ajakabcin** [comment]
Remaining points 3 (from original 5)

**Comment by ajakabcin** [comment]
Closing - further functional validation will be done via QA
