### ISSUE TITLE
Create UX Research Roadmap

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#59417]
#### Tasks
- [ ] Brainstorm session with UX and PMs
- [ ] Draft priorities
- [ ] Set priorities
- [ ] develop a visual roadmap of UX research priorities

#### Acceptance Criteria
- [ ] Reviewed by UX Team
- [ ] Reviewed by PMs
- [ ] Documentation has been updated
- [ ] Put published research in drive

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by APorter-Clarity** [comment]
[UX Roadmap Brainstorm Mural](https://app.mural.co/t/oddballinternal7486/m/oddballinternal7486/1685625148097/3b4befa71ab283f219be5c07196daaf03d21e69a?sender=u6c46f747a0483ea836054483)
