### ISSUE TITLE
Run a local test with the proof of concept

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#59435]
As a LGA Product Manager, I want to run a test of the proof of concept in order to ensure that it's working properly and detect any issues so that we can resolve them. 

Run this test locally! (Doesn't require merge or flipper)
We'll have a way to catch the emails and avoid sending it to places it should not go (ie out in production).

## Tasks
- [ ] Verify that we can hit VA Notify from local
- [ ] Use test user accounts to log in with legacy credential, thereby triggering the process
- [ ] Ensure that the system sends emails to those test users
- [ ] Access email inboxes of test users
- [ ] Confirm that email is received
- [ ] Click on CTA in the email - go to login page
- [ ] View a report in Google Analytics for this campaign: sent, opens, clickthrough
- [ ] Document any issues or proposed improvements

## Acceptance criteria 
- [ ] Able to see data about test emails
- [ ] Document describing issues & proposed improvements exists

**Comment by holytoastr** [comment]
Tech limitations have been a blocker on this task. I have been unable to figure out a working solution.
