### ISSUE TITLE
QA for Reactivation (lmtd) prod test email 

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#59437]
## Tasks
- [ ] Confirm that template looks right
- [ ] Content is correct
- [ ] Content is formatted properly
- [ ] Email was sent out within 2 hours of user logging in
- [ ] Email is personalized with user's preferred name

**Comment by alevindecanini** [comment]
This is blocked by challenges around testing via local and on staging
We expect to be able to demo on prod at the end of Sprint 24, at which point we should be unblocked on this ticket
