### ISSUE TITLE
Finalize template(s) in VA Notify

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#59434]
In order to use VA Notify, we'll need to set up a template which will define the content of the email that Veterans receive.

## Tasks
- [x] Edit copy from draft to final
- [ ] ~~Add link to CLP~~
- [x] Get approvals
- [ ] Complete privacy officer review
- [x] Share template ID with dev #61383

**Comment by alevindecanini** [comment]
- Used latest content from [Figma](https://www.figma.com/file/8vobVoSl1UqLnXsni3rcvO/Login.gov-Adoption%3A-Design-Flows?type=design&node-id=2450-4103&mode=design&t=qJkBbZl0B1sBSBJw-0)
- Created new template [in prod on VA Notify](https://notifications.va.gov/services/a1765cbb-e281-4454-8792-3ae4ade08491/templates/480270b2-d2c8-4048-91d7-aebc51a2f073?templateSaved=true)
- Template name: Reactivation test B
- Template ID: 480270b2-d2c8-4048-91d7-aebc51a2f073
- Added formatting, personalization. @holytoastr @jrjamespdx please check when you get a chance.
- 2 formatting issues: 1) unable to format the CTA as a button via markdown. Discussed this with @kscoulter but we were unable to determine a solution. Currently it's formatted as an h1. 2) unable to format the content below the CTA according to [the mock-up](https://www.figma.com/file/8vobVoSl1UqLnXsni3rcvO/Login.gov-Adoption%3A-Design-Flows?type=design&node-id=1151-4057&mode=design&t=qJkBbZl0B1sBSBJw-0). Not sure how to proceed here either. 
- Another issue: `Custom reply-to email` field won't accept our email address (secure_sign_on@va.gov), presumably because it contains underscores.

**Comment by alevindecanini** [comment]
![Screen Shot 2023-07-07 at 2.48.26 PM.png](https://images.zenhubusercontent.com/63a49829a7612e8c437e2033/cbe499f2-0b74-45bb-8749-950742389cfe)

**Comment by alevindecanini** [comment]
@mjones-oddball are you able to provide any suggestions for how to handle the formatting & reply-to issues mentioned above?

**Comment by mjones-oddball** [comment]
@alevindecanini can you confirm this is a shared VA mailbox and not a distribution group or something else? We were told by the group that creates those the only supported special characters were dash and period

**Comment by mjones-oddball** [comment]
@alevindecanini Thank you for confirming! Sounds like there's been an update to supported characters. I'll discuss with the team and get back to you on resolution timing for your mailbox.

- I noticed your template is in Production rather than Staging. Is this intentional? Testing typically occurs in the lower environments as Production has access to live data.

- For the CTA, buttons are not supported at this time. Here's the VA supported style guide for links in emails: https://design.va.gov/templates/email#links
    - If you were looking to call extra attention to the link you could utilize a card around the link and bold. (screenshot below)
   
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/99204969/2b06b1f2-8145-4686-b5c1-05832cb27935)

CC @hubgitian @GitSamJennings @bevnobev

**Comment by holytoastr** [comment]
> * I noticed your template is in Production rather than Staging. Is this intentional? Testing typically occurs in the lower environments as Production has access to live data.

@mjones-oddball Do you know how other folks have tested on staging? We've been having a hard time making of use of different environment api calls for vets-api. If you happen to know and can point me to some example code, it would be appreciated! 🙇‍♀️

**Comment by mjones-oddball** [comment]
@nathanbwright Do you have any tips to share?
> @mjones-oddball Do you know how other folks have tested on staging? We've been having a hard time making of use of different environment api calls for vets-api. If you happen to know and can point me to some example code, it would be appreciated! 🙇‍♀️

**Comment by nathanbwright** [comment]
@mjones-oddball - Sure, let me get some examples.

**Comment by nathanbwright** [comment]
@holytoastr 

You'll need a staging API key and need to have it saved correctly in `Settings` (under your own namespace). Using `Settings` allows for each env to store it's own API key and template id.

This example shows how it is used for the `va.gov` service but you can adapt it for your own use case by changing the `Setting` lines.

```ruby
notify_client = VaNotify::Service.new(Settings.vanotify.services.va_gov.api_key)

notify_client.send_email(
  {
    email_address: 'some_email@example.com,
    template_id: Settings.vanotify.services.va_gov.template_id.some_template_name,
    personalisation: {
      'fname': 'first_name'
      'date_submitted': '01/02/2023'
    }
  }
)
```

Note the spelling of `personalisation` (it's something that we plan to update but haven't gotten to it yet...).

Happy to spin up a slack convo if you'd like any more details!

**Comment by mjones-oddball** [comment]
@alevindecanini @djmunoz1 Update on the custom reply-to email address, secure_sign_on@va.gov. We are going to schedule an update to the Self Service Portal to support underscores in this field. In the meantime, I've added it to your templates in Staging and Production behind the scenes. You can continue to edit the email template itself, it just won't allow you to edit the reply-to email address field. If you need a change please reach out!
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/99204969/9c8aa83b-2af0-4cf1-a942-cbb63b38a9ab)
CC @GitSamJennings @bevnobev

**Comment by mjones-oddball** [comment]
@djmunoz1 Just wanted to let you know that underscores are now supported in our Self Service Portal.

> @alevindecanini @djmunoz1 Update on the custom reply-to email address, [secure_sign_on@va.gov](mailto:secure_sign_on@va.gov). We are going to schedule an update to the Self Service Portal to support underscores in this field. In the meantime, I've added it to your templates in Staging and Production behind the scenes. You can continue to edit the email template itself, it just won't allow you to edit the reply-to email address field. If you need a change or add new templates please reach out! ![image](https://user-images.githubusercontent.com/99204969/252785269-9c8aa83b-2af0-4cf1-a942-cbb63b38a9ab.png) CC @GitSamJennings @bevnobev
