### ISSUE TITLE
UX | Profile | MHV / DSL gates | Create alerts

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#59446]
## Background

As we learn more about #59301, we should be prepared if we need to gate personal information or all of profile. 

## Tasks
- [ ] Create alert mock-ups in Sketch
- [ ] Review w/ content team and get approval
  

## Acceptance Criteria
- [ ] Alert mock-ups are ready for FE

## Associated Tickets
- #59301

**Comment by andaleliz** [comment]
@mtcA6 FYI, I'm adding this to the current sprint.  These have all been approved by the content team and are for FE implementation, if we need them.

- If we need to gate all of profile, we can use [this mock-up](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/a/uuid/A8170D36-F051-4999-B2DD-BAF839BA805F)

- If we need to gate all of personal information, we can use [this mock-up](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/DELnY1e)

- If we need to gate **only** the editable fields of personal information, we can use [this mock-up](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/lRkQ8AV)

I haven't created mobile versions yet but I will once we decide on a direction. 

CC @adamwhitlock1 for awareness.

**Comment by mtcA6** [comment]
Thanks for the heads up @andaleliz, you're super quick
