### ISSUE TITLE
[task] Document development pain points

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#59506]
## Issue Description

As discussed in our teams retro, we have encountered multiple issues and blockers that we would like to share with the VA (Steve Albers). Including, but not limited to pain points we've encountered with platform.

## Tasks

- [x] Create a doc with the described pain points ([draft here](https://docs.google.com/document/d/1fxWmt9znoqge669-3MYGlzO7esnmfv0D2Sq2j7f68o4/edit?usp=sharing))
- [x] Collaborate and get feedback from other team members
- [x] Share the doc with the VA

## Definition of done

- [x] Complete all tasks
- [x] Discuss doc with VA

**Comment by saderagsdale** [comment]
We can close this. I shared it with Steve.
