### ISSUE TITLE
[QA bug] Notification Component: "x close" link appears outside of notification box

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#59544]
## Background
While testing the component on Safari I found that the "close" link (and accompanying x icon) appear partially outside of the notification card when the browser is sized at a normal desktop. It goes back inside the notification card when sized down to mobile size. So far I'm only seeing this on Safari. Screenshots in resources section

## Tasks
- [ ] Review issue and identify a fix
- [ ] Implement fix
- [ ] Test
- [ ] Move to validate

## Acceptance Criteria
- [ ] "X close" appears entirely inside the notification card across all browsers and sizes

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ Log into staging with user 11 on Safari and confirm notification component visually matches [sketch files](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/FC0B70C7-FF70-4A54-8247-DC0AD864E5ED).

## Resources

**Desktop size on Safari**
![Screenshot 2023-06-01 at 4 27 30 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/6ee76e10-df67-4e2d-89e1-2eac054855cb)

**Mobile size on Safari**
![Screenshot 2023-06-01 at 4 27 46 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/6ae57841-9a96-4843-b356-fb867119daa7)

**Comment by ajakabcin** [comment]
Commenting here to close the loop from our discussion offline - we'll leave this open until the component is on My VA but we believe this should be resolved then

**Comment by ajakabcin** [comment]
Zeroing this out for an estimate as we believe this will resolve on it's own once the component is live on My VA

**Comment by ajakabcin** [comment]
Closing - once the component was implemented in the code on My VA this issue was resolved.
