### ISSUE TITLE
Add remarried surviving spouse info to burials eligibility page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#59559]
## Issue Description
Our burials and memorials stakeholder asked us to add information about remarried surviving spouses to our [Eligibility for burial in a VA national cemetery](https://www.va.gov/burials-memorials/eligibility/) page. 

These are the 2 options she gave for placement:

1. In the blue eligibility box, change the third bullet to read: The person qualifying for burial benefits is the spouse, surviving spouse (even if remarried), or minor child of a Veteran, even if the Veteran died first, or
2. Under the "Eligibility information for specific groups" H2 add an accordion labeled "Remarried spouses of Veterans" and put the following content in the accordion: A spouse who was married to a Veteran at the time of the Veteran’s death is eligible for interment in a national cemetery, even if they remarry

We'll need to review these options and determine which makes more sense to do, or if there is a different option. We may also need to rewrite the content for plain language and VA.gov style.

## Tasks
- [x] Add new content to Drupal 
- [x] Review (Laura)
- [x] Send to stakeholders for approval
- [x] Copyedit (Megan)
- [x] Publish (Megan)
- [x] Notify stakeholders that changes are live (Randi)

## Acceptance Criteria
- [x] Updated content is live on the page

**Comment by megzehn** [comment]
Thanks, @RLHecht! Confirming I published.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
