### ISSUE TITLE
SOCKS access for Travis Cahill

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#59567]
### Your Name

Travis Cahill

### Your Email

travis.cahill@agile6.com

### Your Role and Team

PM - Authenticated Experience - Profile 

### Product Manager (PM) name and email

Travis Cahill travis.cahill@agile6.com

### Product Owner (PO) name and email

Samara Strauss samara.strauss@va.gov

### Access Type Requesting

viewers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCxYC6U78Zmfbzszq1LsaSH6orEfHhDCJ+O3tmD6R8wgHntdmdKKyniJstnywQsCXglRqXZcfWr859m7QftdDUPoAqzKXMiscnsweIeop/b4jOH1mov6I/aUStjY0+FSOarj1tGBX9wEXU98uTrI1uSHbGXNbTSaCNOd9LyPaR+/tNLs4wSAAIhRAgjcvYfCIu+c+A7xY4rLvsPbtjeAQJP6q0rnCH/V0w7tCkbvGaYCoAWYtmyth2opNlW9/DXvW4IJElxVB7h3o57QNWTTbNtgfwBmRok8kOP5voHmPXKEoa+QJ741RSxGcrtzPi8Y/jXTjIDlAOkAU0UUzgHEYpNBSGcC7NAX5BFeBtTcDGD8yE9jr7u2oTeUcn8bDZr9+StY3FCNKFigrD/LMAg+3Q4g4qYHDCRSCKSTr+pRvBNvvyqS+1Advr5cBEocm9YX1+Wv7jENhKka/yW7BV4zpOyjgJ+D0N/xqu+OrZ54VdJdvrssbwDff96c1nO246+k0s= mcahill@CahillM-A114

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/d72d545c-4848-4cb9-8971-d1a5433f0e75)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by rmtolmach** [comment]
You've been granted access. See documentation for more info: https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy and reach out in #vfs-platform-support if you have any problems!
