### ISSUE TITLE
Documentation: Tier 1 to Tier 2 Escalation Update

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#59572]
**Description:** Create section Support Best Practices documentation to include triaging of new issues by Tier 1 team members Joe Knipes and Brandon Dech

Draft for editing [HERE](https://vfs.atlassian.net/wiki/spaces/~7120206d71ac1d51d9451b8aa7b67d7c4b7101/pages/2645098900/Draft+Tier+1+to+Tier+2+Support+Escalation+-+An+Update+to+Best+Practices+Documentation) 

**Definition of Done:**
Tasks below are complete.

**Tasks**

- [x] Document how issues are triaged

- [x] Document how and when issues are escalated to Tier 2 

- [x] Document process of how and when issues are escalated from Tier 2 to CoP

- [x] Add related articles section and point to them like Support Best Practices and Advanced Support Best Practices (example of page structure: https://vfs.atlassian.net/wiki/spaces/PTST/pages/2630353240/Advanced+Ticket+Support+Best+Practices)

- [x] Add section for Tier 1 Schedule and point here (https://vfs.atlassian.net/wiki/spaces/~63442b7bb380bb46a0906c45/pages/2658893845/Tier+1+Support+Schedule+Platform+Tech+Support+Team)

- [x] Add section for Tier 2 Schedule and point here (https://vfs.atlassian.net/wiki/spaces/~63442b7bb380bb46a0906c45/pages/2658893845/Tier+1+Support+Schedule+Platform+Tech+Support+Team)
