### ISSUE TITLE
[FSR] Sentry error, failed fetch handling 

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#59611]
## Issue Description
Investigate Sentry issue `Error: [object Object]`. Seems like it's caused by how we're handling failed responses error messages for `/debts` and `/medical_copays`. This isn't catastrophically form breaking and likely caused by trying to interpolate an object without stringifying or parsing it in the `.catch` handler in the actions. 

Let's try and coordinate with back end to make sure we handle the failed response object, and properly destructure it to get a meaningful error message. 

http://sentry.vfs.va.gov/organizations/vsp/issues/204290/?query=is%3Aunresolved+location%3A%2Fgenerated%2Frequest-debt-help-form-5655.entry.js

I [snuck in a small fix](https://github.com/department-of-veterans-affairs/vets-website/pull/24151/files#diff-c54aebc8cdd126d0810422c07268aa38544674c4b64706e2cc8e3f2e50054a55R45-R49) to help cut back on the number of errors we receive this way, but there's probably a better way to handle it. 

This ticket was opened after [investigation Sentry issues](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/58187)

---
## Tasks
- [x] Identify root cause of error. 
- [x] Find a better way to handle the error for 
  - [x] `/debts` error response
  - [x] `/medical_copays` error response

## Acceptance Criteria
- [x] best case scenario we won't see these gross `Error: [object Object]` errors, and we'll have something more helpful or clear in the log. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
This ticket will roll into Sprint 137! It was pulled in late, and came at a general awkward time with PTO as well

**Comment by Dr-Pongo** [comment]
These generic errors are now more neatly captured with the messaging change already made recently so they appear under one alert Sentry with the message `medical_copays failed: `. Previously they would just pop with `Error: [object Object]` as a new issue on occasion causing strife and panic, but now it's at least managed.
