### ISSUE TITLE
Draft changes to Collaboration Cycle Dashboard

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#59621]
## User Story
As a Governance Team member, I want to sketch out potential graph solutions for Domo that address the data that was requested by OCTO-DE leadership in the Domo survey, so that I can get alignment on those graphs before building them.

As an OCTO-DE lead, I want to understand what a graph might look like so that I can make suggestions and edits in the design phase, before the governance team has begun building out new Domo cards.

Assignee: @sterkenburgsara 
Peer Reviewer: @it-harrison 

## Description
Following the presentation of OCTO-DE Domo dashboard survey feedback, governance team proposed implementing solutions proposed by OCTO-DE leadership that were both 1.) actionable given our current dataset and 2.) were a low/medium level of effort to build. However, some of those solutions are slightly ambiguous and require some thought to implement. Do they replace or build on current cards? Do they require new cards? What type of graph does that data require? What toggle/drop-down sort functionality can we add without making each card overwhelming? This ticket asks assignees to sketch out potential dashboard graphs that can get at these solutions and work together to ensure that the options would be feasible. The draft of changes for the dashboard should be presented to Shira and Matt Dingee for feedback.

## Impacted Artifacts
* [Collab Cycle Domo dashboard](https://va-gov.domo.com/page/1340527018)
* [Draft of Ideas - Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686764117069/5e30ad39ba0126a133110af9e4d4864246634bf1?sender=uf94a77a19aaf687331c09367)

## Tasks
- [x] Analyze survey feedback and current dashboard, and sketch out some graphs that address the following OCTO-DE needs: 
    * The Collaboration Cycle dashboard includes date-range filters on relevant cards
    * The Collaboration Cycle dashboard includes a launch-blocking filter on relevant cards
    * The Collaboration Cycle dashboard allows OCTO-DE to see how data is trending over time
- [x] Check that the sketched options would be technically feasible
- [x] Present to Shira and Matt Dingee to get feedback
- [x] Iterate on designs as needed

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have identified what changes we would like to make to the Collaboration Cycle dashboard

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by sterkenburgsara** [comment]
Update: @it-harrison and I synced on Wednesday, June 14th to discuss some ideas. We want to propose a few changes that I will summarize in a Mural or a series of screenshot and link here shortly. 

We'd also like to create a new backlog ticket to get the epic # out of GH for issue tickets so that we can roll up issues into clusters together based on specific staging reviews. Then we can pull data averages around reviews (average # of issues/review; average # launch-blocking issues/review) to give directional data about how average teams perform. Having that epic # would also afford us the option to mute any noise coming from fluctuating #'s of staging reviews any particular time-frame; we could instead display data according to last X staging reviews (instead of last X months). 

// cc @shiragoodman @humancompanion-usds

**Comment by sterkenburgsara** [comment]
Draft dashboard: [Mural link](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686764117069/5e30ad39ba0126a133110af9e4d4864246634bf1?sender=uf94a77a19aaf687331c09367)

**Comment by sterkenburgsara** [comment]
@it-harrison per our conversation today, here is a draft of proposed dashboard updates: [Mural link](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686764117069/5e30ad39ba0126a133110af9e4d4864246634bf1?sender=uf94a77a19aaf687331c09367) - can you play around with these concepts to see if any of these are technically feasible and see what you think? I'll schedule a quick sync with @shiragoodman within next few days.

**Comment by sterkenburgsara** [comment]
Update: reviewed draft with @it-harrison and @shiragoodman this morning. Following that meeting, I will annotate the [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686764117069/5e30ad39ba0126a133110af9e4d4864246634bf1?sender=uf94a77a19aaf687331c09367) to indicate changes/updates following that conversation. Once complete, I will paste the Mural link into governance-team Slack channel for additional comments. To allow ample time for feedback, this ticket will move into the next sprint.

**Comment by it-harrison** [comment]
@sterkenburgsara - looks good!
