### ISSUE TITLE
Add eyebrow to pre-check-in production 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#59637]
Follow up from adding the eyebrow into check in - https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/58989

## Tasks

- [ ] Identify what pages need the eyebrow
- [ ] Determine what content will be in the eyebrow. For example, "Pre-check-in"? 
- [ ] Create wireframes
- [ ] Validate with team 

## AC

- [ ] Wireframes are complete
- [ ] Validated with team 
- [ ] Create f/u ticket for FE to start implementation
