### ISSUE TITLE
[Research] My VA Education: Consider expansion to education and training section

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#59636]
## Background
As a result of [My VA audit UX improvements UAT study](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/UAT/findings-summary.md), it was [recommended](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/UAT/findings-summary.md#recommendations) that we consider expanding the education and training section to include education/training benefits that do not fall under the post-9/11 GI bill. We should do some "research/discovery" work on this: talk to other teams who work with education and training data, search slack for old threads and mentions, poke around GH to gather info on other types of education benefits; and see how/if we can incorporate that into My VA education and training section.

## Tasks
- [ ] Review slack and github for mentions/threads around education benefits and trainings
- [ ] Identify teams to reach out to who may have more subject matter expertise on education and training benefits
- [ ] Reach out to those teams for meetings/slack convos to see if they can point us to additional information and share insights
- [ ] Identify scope of education and training benefits as it pertains to My VA - what could we feasibly incorporate into our dashboard?

## Acceptance Criteria
- [ ] Discovery documentation exists in Github
- [ ] We have an understanding of whether this is something we can or should pursue further to incorporate into My VA
