### ISSUE TITLE
Review research, design, and technical architecture for on-screen notifications

### ISSUE THREAD

**Issue by A6-toma** [department-of-veterans-affairs/va.gov-team#59633]
Review existing research, design, and technical architecture for the My VA `onsite_notifications` concept. 

Understand state of design and architecture, plans of the My VA team and Design System team, and any existing constraints / opportunities.

Understand how the different systems involved in the VA notifications ecosystem work together, including but not limited to:
o	VA Notify
o	VEText
o	VA Health and Benefits mobile app
o	VA.gov/vets-api
o	VAOS backend
o	MHV API

**TASKS**

- [ ] UX research review
- [ ] UX design review
- [ ] Technical research review
- [ ] Technical architecture review
