### ISSUE TITLE
Design feature to opt-out from MHV on VA.gov

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#59641]
## Task Description
Add a way for Veterans to temporarily opt out of using Appointments on MHV on VA.gov and return to MHV.gov Liferay.

## Notes and References
- This will show on the appointments landing page
- This will only show for Appointments until we have Cerner data displaying (phase 1b). After that we'd remove it
- [Here's an example](https://dsva.slack.com/archives/C03CGTDLTFF/p1685722771929829?thread_ts=1685119970.558859&cid=C03CGTDLTFF) from Secure Messaging - this would be on their static landing page
- Other teams would be showing it for a longer time as they move over. We'll need to coordinate with Secure Messaging on language and UI
- This will show for all users
- [Current explorations [WIP]](https://www.figma.com/file/mylP38N3rxVWIk707r0ZmN/Feature-to-opt-out-from-MHV-on-VA.gov?type=design&node-id=2-4)

## Acceptance Criteria
- [ ] A user can return to the MHV Liferay appointments list from
    - [ ]  From the Appointments on VA.gov Static Landing Page
    - [ ]  From the Appointments on VA.gov Main landing page
- [ ]  Consider adding an option to leave feedback

## Deliverables
- [Designs](https://www.figma.com/file/mylP38N3rxVWIk707r0ZmN/Feature-to-opt-out-from-MHV-on-VA.gov?type=design&node-id=1242%3A17532&t=woz5Qap7TlO8NJTP-1)

**Comment by Cieramaddox** [comment]
@outerpress [Explorations](https://www.figma.com/file/mylP38N3rxVWIk707r0ZmN/Feature-to-opt-out-from-MHV-on-VA.gov?type=design&node-id=1238%3A14899&t=9IkuAaYmS2noFSby-1) are ready for your review.

**Comment by Cieramaddox** [comment]
We are also exploring what it would look like when both the cerner redirect alert and the feature to Opt Out from MHV on VA.gov appear together [here](https://www.figma.com/file/mylP38N3rxVWIk707r0ZmN/Feature-to-opt-out-from-MHV-on-VA.gov?type=design&node-id=1277%3A30188&t=woz5Qap7TlO8NJTP-1).

**Comment by outerpress** [comment]
At SME sync 6/21 we decided not to add this to VAOS as it might add confusion - MHV is already redirecting to VAOS for some of its functionality which could put users in a loop.
