### ISSUE TITLE
Planning: Forms digitization research

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#59672]
## Purpose
How do we want to go about this research effort?

## Tasks
- [ ] Prep approaches
- [ ] Discuss possible approaches
- [ ] Settle on a direction
- [ ] Share w/ PO for buy-in

## Acceptance Criteria
- [ ] Direction documented
- [ ] PO buy-in affirmed

**Comment by twoangstroms** [comment]
From Naomi: Why do Form Teams go the custom route? What are all the variances?

**Comment by twoangstroms** [comment]
The initial examples of prioritization dovetail with what we've already seen from Forms teams, but interesting process insights into roadmaps [here](https://govos.com/blog/what-is-change-management/)
