### ISSUE TITLE
[FE] Notification Component: Post-launch code cleanup

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#59686]
## Background
Once the notification component is live to all users on My VA we need to do a post-launch clean up to remove the feature flag from the code and update tests.

## Tasks
- [ ] Remove feature flag from FE code 
- [ ] Remove feature flag from API code
- [ ] Update notification component tests

## Acceptance Criteria
- [ ] Notification component feature flipper is removed from FE and API code and tests are updated

## Resources
- Notification component tests [reference](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57482#event-9307365061)
