### ISSUE TITLE
Update number of days to complete disability related claims for May 2023 (in English and Spanish)

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#59687]
## Issue Description
We need to update the number of days it takes to complete disability related claims. Sitewide content needs to email Tanekwa Bournes on the first of the month to get the number from the previous month and input into Drupal.

This needs to be done on the following pages:
https://www.va.gov/disability/after-you-file-claim/
https://www.va.gov/disability/how-to-file-claim/
https://www.va.gov/disability/how-to-file-claim-esp/
https://www.va.gov/disability/after-you-file-claim-esp/

## Tasks
- [x] Email Tanekwa for most recent number (Randi)
- [x] Input number and new month into both Drupal pages (Randi)
- [x] Review Spanish pages (Ana)
- [x] Review English pages (Megan)
- [x] Publish all 4 pages (Megan)

## Acceptance Criteria
- [x] Most current number of days is on live site

**Comment by RLHecht** [comment]
@megzehn and @ABeltran77 these pages are ready for you to both review. Megan, once Ana is done you can publish hers as well. Thanks!

**Comment by megzehn** [comment]
Ana and I copy edited, and I published. This is good to go! Thanks, @RLHecht!!

**Comment by RLHecht** [comment]
These changes are live. Closing ticket.

**Comment by ABeltran77** [comment]
Great!
