### ISSUE TITLE
EVSS Migration - PPIU migration: Abstract references to EVSS::PPIU::Service

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#59695]
## Issue Description
During 526 submit workflow discovery, an [unmigrated callout](https://github.com/department-of-veterans-affairs/vets-api/blob/d30b00ad5be37d43edb2720442e3cb1aff1228aa/lib/evss/disability_compensation_form/data_translation_all_claim.rb#L119) out to the EVSS PPIU Service was discovered. We need to abstract this service out so that we can migrate to the [Lighthouse's Direct Deposit API](https://staging-developer.va.gov/explore/benefits/docs/direct-deposit-management?version=current)

NOTE: We are only using the GET endpoint for PPIU to retrieve direct deposit information before 526 submission- however, the mobile apps are using both [GET](https://github.com/department-of-veterans-affairs/vets-api/blob/8203024d2c3762881dcba4153c2e905e7d476541/modules/mobile/app/services/mobile/v0/payment_information/proxy.rb#L14) and [POST](https://github.com/department-of-veterans-affairs/vets-api/blob/8203024d2c3762881dcba4153c2e905e7d476541/modules/mobile/app/services/mobile/v0/payment_information/proxy.rb#L18)

---
## Tasks
- [x] create a direct deposit provider to be created by the ApiFactory
- [x] create flipper feature toggle to switch from EVSS to LH
- [x] fix failing unit tests by switching the feature toggle on/off

## Acceptance Criteria
- [x] Abstract references to EVSS::PPIU::Service
- [x] Maintain test coverage
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

## Related Issues
- [#57859](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/57859)
