### ISSUE TITLE
686c | Update max length for address fields

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#59697]
## Issue Description

We need to add a max length of 30 characters for `veteran_contact_information.veteran_address.city` on the front end, a max length of 35 characters for `last_term_school_information.address.address_line1`, and a max length of 35 characters for `school_information.address.address_line1`. This should be very simple to achieve using VA's form system.

## Tasks
- [x] Set max length of 30 characters for `veteran_contact_information.veteran_address.city`, and appropriate error messaging.
- [x] Set max length of 35 characters for `last_term_school_information.address.address_line1`, and appropriate error messaging.
- [x] Set max length of 35 characters for `school_information.address.address_line1`, and appropriate error messaging.

## Definition of Ready
- [x] Fields that need validation are known.

## Definition of Done
- [x] Confirmed to work on staging or production.

**Comment by data-doge** [comment]
No errors since deploy. Closing.
