### ISSUE TITLE
526 Submit - Migrate GET call to /paymentInformation to Lighthouse PPIU

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#59698]
## Issue Description
The eVSS is being deprecated and the vets-api utilizes these services to retrieve and post data.
One of these services is the PPIU, or Personal Payment Information/Update service. The GET endpoint is used during the 526 submission workflow to retrieve bank account information for direct deposit. Big need to migrate this to [Lighthouse's Direct Deposit API](https://staging-developer.va.gov/explore/benefits/docs/direct-deposit-management?version=current)

We think this has already been built by another team - Authenticated Experience?

## Related Tickets
- [#59695](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/59695) PPIU abstraction
- [#57895](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/57859) 526 submit discovery

---
## Tasks
- [x] Use abstracted PPIU/DirectDeposit service in va_526ez.rb line 216 for PPIU service
- [x] Create Lighthouse PPIU Provider
- [x] Create or Use Ligthouse DirectDeposit service
- [x] Implement Lighthouse transform method
- [x] Update unit tests for Lighthouse Provider and service

## Acceptance Criteria
- [ ] Migrate [call to `get_payment_info`](https://github.com/department-of-veterans-affairs/vets-api/blob/d30b00ad5be37d43edb2720442e3cb1aff1228aa/lib/evss/disability_compensation_form/data_translation_all_claim.rb#L119) to ApiFactory implementation
- [ ]  Maintain test coverage
- [ ]  Documentation of specific steps taken for code complete
- [ ]  Code is merged but not necessarily tested in higher environment
- [ ]  Backend tested in sandbox

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
