### ISSUE TITLE
www.pittsburgh.va.gov migration to www.va.gov

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#597]
## Intro 
The CMS / website team is re-launching the Pittsburgh location website under www.va.gov as part of continuing the WBC project. Latest projection of timeline right now is October/November. They’re asking that the VSP takes on serving of pittsburgh.va.gov traffic to handle those redirects so they can be managed by Drupal.

Update:
During an internal meeting, the team came up POC and will brief a model for how to handle redirects and taking ownership of domains.

cc: @wyattwalter, @tskinn (feel free to change anything)

## AC

- [x] Initial ESECC paperwork for domain takeover
- [x] Ability to query CMS both directly or through SOCKS (for local testing)
- [x] Ability to query GraphQL endpoint at Drupal for redirects
- [x] Template in nginx config to generate working configuration for server-side redirects
- [x] Decision on model for launching Pittsburgh new site
- [x] Establish redirect mapping (not us, but needs to be done before we can redirect the traffic)
- [x] Obtain SSL certificate
- [x] Take over traffic for www.pittsburgh.va.gov and enable redirects to new location

**Comment by wyattwalter** [comment]
We started this and got the model mostly figured out. Moving this to backlog for now as priorities shifted and redirects on www.va.gov is more pressing.

**Comment by ricetj** [comment]
Looking to have a conversation around this.

**Comment by wyattwalter** [comment]
This site launch is done, our tasks related to it are completed.
