### ISSUE TITLE
686c | Improve BGS validation error logging.

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#59706]
## Issue Description

We should improve our logging around validation errors. Currently, I need to sift through enormous error messages returned by BIS to understand whether an error was a validation error, and if so, what kind of validation error. This makes it more difficult to assess the kinds of errors we are getting, and their relative proportions. The relevant part of BIS's error messages tend to start with a `ORA-*` signature. So, it should be possible to extract the relevant portion of those error messages, and log them alongside the raw error message.

## Tasks
- [x] Determine regex necessary to capture errors with `ORA-*` signatures
- [x] Update logging to log such errors

## Definition of Ready
N/A. Ready to work on now.

## Definition of Done
- [ ] Evident in Datadog and Sentry that logging has been updated.

**Comment by data-doge** [comment]
Work merged. Waiting for deploy to validate.
