### ISSUE TITLE
686c | Fix bugs related to foreign military addresses

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#59705]
## Issue Description

We need to fix some bugs around foreign military addresses. There are instances where a veteran inputs a city of APO, DPO, or FPO (indicating a foreign military address), but is still allowed to indicate a State address, state code, and zip code. BIS rejects this data because it expects a military_postal_code of either AE, AP, or AA for APO, DPO, and FPO addresses. Additionally, when a veteran indicates a foreign military address, our code deletes city from the payload we send to BIS. But BIS throws an error when city is null. We should consult with Linda and Baha to learn what data is expected for military addresses.

## Tasks
- [x] Update front-end to prohibit vets from indicating a State address after choosing to submit a foreign miilitary address.
- [x] Talk to Linda and Baha about what to send for `city`, instead of `null`, for a foreign military address.
- [x] Update what we send for `city` for foreign military addresses.

## Definition of Ready
- [x] Linda and Baha clarify how to avoid a `City is null` error, for foreign military addresses.

## Definition of Done
- [x] Front-end prohibits vets from indicating a State address after choosing to submit a foreign miilitary address.
- [x] We are able to submit foreign military addresses without a `City is null` error.

**Comment by data-doge** [comment]
Note to self:
- It seems like we expect a `state_code` to exist for foreign military addresses
- We seem to store the military state code as `province`, and not `state_code`
- However, we try to set `military_postal_code` to `state_code` (https://github.com/department-of-veterans-affairs/vets-api/blob/c4b1258a690edcea7d1fe8e2a8fcf74a251f86a2/app/models/bgs_dependents/base.rb#L95), even though there is no `state_code`.

**Comment by data-doge** [comment]
Downgrading to 3 points now that I have clarity from Linda

**Comment by data-doge** [comment]
Posed a question to platform support: https://dsva.slack.com/archives/CBU0KDSB1/p1686259249984419.

**Comment by data-doge** [comment]
Platform support believes that all APO/FPO/DPO address must have a state code of AA/AE/AP. Meaning, we may want to make updates to the 686c address form. Specifically, if a veteran doesn't tick the "I live on a military base outside the US" checkbox, but indicates APO/FPO/DPO as the city, I think we'd want to either display an error message to that effect, or automatically tick that checkbox.

**Comment by saderagsdale** [comment]
@data-doge are we on track to close this one or did it get blocked?

**Comment by saderagsdale** [comment]
@data-doge let me know when this is ready to close.

**Comment by data-doge** [comment]
@saderagsdale I just validated that this is working on staging and that we're no longer seeing these kinds of errors on prod. I'll close now.
