### ISSUE TITLE
686c | Handle special characters in names and addresses

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#59703]
## Issue Description

We need to change how we handle names and addresses with special characters (e.g. apostrophes, umlauts). BIS (and perhaps Corp DB) reject them. We could strip them out, replace them with a space, add front end validations preventing veterans from entering them, or advocate for the relevant datastore(s) to accept special characters.

DECISION: Removal/replacement approach.

## Tasks
- [x] Decide how to handle special characters like umlauts and apostrophes (remove/replace)
- [x] Make appropriate updates

## Definition of Ready
- [x] Relevant stakeholders agree on way to handle special characters

## Definition of Done
- [x] Special characters handled in way that doesn't cause errors to be thrown.

**Comment by data-doge** [comment]
Reached out to Cheri Ray for documentation on this.

**Comment by data-doge** [comment]
Work is merged. Just waiting for deployment, so I can validate that fix works in production.

**Comment by saderagsdale** [comment]
Waiting until EOD today to check the logs

**Comment by data-doge** [comment]
Logs look good. Closing.

**Comment by data-doge** [comment]
Fix here: https://github.com/department-of-veterans-affairs/vets-api/pull/13135

**Comment by sortizsh** [comment]
@tfink419 @evansmith can you take a look at this ticket plz

**Comment by data-doge** [comment]
Thanks @sortizsh! @tfink419 @evansmith, you'll just need to validate whether my fix worked or not.

**Comment by evansmith** [comment]
@tblackwe I confirmed in datadog's production logs that the invalid characters error isn't appearing. I think that this one can be closed.

**Comment by tblackwe** [comment]
closed by #13408
