### ISSUE TITLE
Migrate POST call to /paymentInformation to Lighthouse PPIU

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#59702]
## Issue Description
The eVSS is being deprecated and the vets-api utilizes these services to retrieve and post data.
One of these services is the PPIU, or Personal Payment Information/Update service. The POST endpoint is used by the mobile team (as well as the GET), but _not_ during the course of the 526 submission. Big need to migrate this to [Lighthouse's Direct Deposit API](https://staging-developer.va.gov/explore/benefits/docs/direct-deposit-management?version=current)

NOTE: coordinate with mobile team

## Related Tickets
- [#59695](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/59695) PPIU abstraction
- [#57895](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/57859) 526 submit discovery

---
## Tasks
- [ ] 

## Acceptance Criteria
- [ ] Migrate call to `update_payment_info` to ApiFactory implementation
- [ ]  Maintain test coverage
- [ ]  Documentation of specific steps taken for code complete
- [ ]  Code is merged but not necessarily tested in higher environment

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by aurora-a-k-a-lightning** [comment]
@RakshindaAslam @sethdarragile6 
i am proposing we close this ticket.

i feel that if our application does not use these services and endpoint, we shouldn't migrate it as our feature flags pertain to our workflows/features, our testing, and our rollout plans, while other teams consuming it may have different plans and we could really mess things up for them.

in this case, form526 does not use the POST PPIU calls, so i propose we don't migrate it.

**Comment by RakshindaAslam** [comment]
Makes sense to me! @sethdarragile6 @aurora-a-k-a-lightning
