### ISSUE TITLE
Add a new feature toggle for Print List initiative 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#59708]
## Item Description
We will need to create a feature toggle in application for the print list feature. 

---

## Tasks
- Add `va_online_scheduling_print_list` feature toggle

## Acceptance Criteria: 
- [x] The toggle is created for VAOS

## Definition of Done
- [x] All acceptance criteria are met
- [x] [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md) is updated
---

**Comment by simiadebowale** [comment]
@ldelacosta - this is ready for validation

**Comment by ldelacosta** [comment]
Validated the toggle has been added. Closing out the ticket. 
![Screenshot 2023-06-23 at 2.37.07 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/3ce09a9f-53f1-4aea-b027-766e8fa65c69)
