### ISSUE TITLE
686c | Change how we represent UK addresses

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#59701]
## Issue Description

We need to change how we represent UK addresses, specifically. Currently, if the veteran provides an `international_postal_code` (i.e. GBR), we use an `IsoCountryCodes` class to automatically expand that to "United Kingdom of Great Britain and Northern Ireland", which exceeds the 50 character limit for countries by two characters. We should consult with Linda and Baha. Ideally, we could simply truncate the country to 50 chars without creating any negative impact.

## Tasks
- [x] Talk to VA platform to determine whether any negative consequences to truncating country name to "United Kingdom."
- [x] Ask same question to BIS, and get their perspective.
- [x] Consider using BIS web service to get correct country names.
- [x] Update the country name we send to BIS.

## Definition of Ready
- [x] No objections from VA platform support
- [x] No objections from BIS
- [x] We've decided whether to use BIS's web service for country names, or just put it in a quick fix for UK specifically.

## Definition of Done
- [x] No more UK-related errors appear in DataDog

**Comment by data-doge** [comment]
No errors observed since merge. Closing.
