### ISSUE TITLE
Remove "QA" from Midpoint Review codeblock

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#59710]
## User Story
As a VFS team member, I want to know what practice areas to expect feedback from at the Midpoint Review so that I don't need to follow up and waste my time if a checkbox is not checked.

Assignee: @sterkenburgsara 
Peer Reviewer: @CherylEvans 

## Description
QA no longer provides feedback at the Midpoint Review, however the codeblock still has a checkbox for QA to check off. 

## Impacted Artifacts
Collab Cycle Kickoff moderator responsibilities - Midpoint Review codeblock
Open Collab Cycle request tickets

## Tasks
- [x] Remove QA checkbox from the Midpoint Review codeblock
- [x] Remove QA artifacts section from the Midpoint Review codeblock
- [x] Remove the QA checkbox from all open Collab Cycle request tickets where
   - a Midpoint Review is included in the ticket
   - the team has not yet scheduled or requested the Midpoint Review (ie no need to update tickets where the Midpoint Review has already taken place)

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS teams no longer expect QA feedback at the Midpoint Review

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
possibly QA artifact information in the ticket too?

**Comment by shiragoodman** [comment]
confirmed. We need to remove the QA artifacts section from the MPR Review codeblock too

**Comment by shiragoodman** [comment]
@sterkenburgsara can you update this ticket with the work you completed?

**Comment by sterkenburgsara** [comment]
Update: Removed QA checkbox and artifacts section from the midpoint review codeblock.

**Comment by sterkenburgsara** [comment]
@CherylEvans you should no longer see any mention of QA in ticket codeblocks under midpoint section / this is ready for review
