### ISSUE TITLE
Design | Profile | Notification settings | Reconsider "we don't have your contact information" alert content CTA

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#59728]
## Background

If a user is missing both email and mobile phone from their profile, and we have both text and email notifications, we were planning on showing an alert that says "Update your contact information" with a link to the contact information of the VA.gov profile (`/profile/contact-information`) ([mock-up](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/9P49mAx)).

Is that still the right approach, now that we have the "Editing as a sub-task" flow ([sketch file](https://www.sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d) and [design system docs](https://design.va.gov/patterns/help-users-to/complete-a-sub-task))? The current alert content assumes that a person will remember what they're supposed to update once they get to `/profile/contact-information`, and easily be able to find it.

However, we've only considered the "editing as a sub-task" flow when there is **one** piece of contact information to update at a time.  Could/should we show both email and phone number if a person clicks from that link? Is there a better way to do this? 

 If not, how should we revise this to incorporate editing as a sub-task?

## Tasks
- [x] Create mock-ups
- [x] Review w/ team
- [x] Get content approved
- [x] Revise mock-ups as needed
- [x] Let team know ready for FE
  

## Acceptance Criteria
- [x] Ready for FE

**Comment by andaleliz** [comment]
[Here is the info about the problems with the deprecated wizard pattern](https://design.va.gov/patterns/wizards#retrofit-this-pattern)

**Comment by andaleliz** [comment]
Hi @pamela-drouin! Taking your questions from Slack over here:

> I could either:
> - try my best band-aid for the scenario of a user missing both contact info pieces (phone and email), using the editing-as-subtask flow (maybe that's what this ticket wants to be done?) or...
> - really think through what's shown to the user when under which conditions -- but maybe that's overkill and only for my benefit as I'm trying to understand this particular intricacy.

I'm inclined to explore the first option, but I'm curious about the band-aid comment. Is there a bigger problem with that flow that you're seeing, that should make us reconsider the whole thing?  My initial thought was to see if it could work to just show fields for both email + mobile on the sub-task page, with an appropriate h1.  

> - Or is there another approach I can take that'd be most helpful? 

I personally don't know of anything else, but that's why two minds are better than one :) I think using the sub-task flow would be OK but I'm totally biased and as I said above, am now curious if there's something I missed.  Looking forward to hearing your thoughts :)

**Comment by pamela-drouin** [comment]
Liz helped immensely by making a flow chart of screens/conditions on the Mobile page of [this Sketch file](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c).

I probably could have used a better word for band-aid! It felt like one to me because I wasn't fully understanding the larger flow that this scenario exists within. Now that I understand it, doesn't feel like a band-aid at all!

**Comment by pamela-drouin** [comment]
Here are three options I mocked up in my notes app (avoiding the fiddliness of Sketch for the moment). I prefer the 3rd version as I'm intending it to be simpler and easier to understand, but even if I am on the right track, I'd imagine it would need testing.

It's a little abstracted, but there are three options. I've described each at the top, and the below is a text mock-up of each.

<img width="1124" alt="Screenshot 2023-06-13 at 1 40 58 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/5949769/3babab1f-82f7-46c3-8d0f-d2ea4c1bba2b">

Thoughts as to whether I'm on the right track, and if so, which version is most promising to mock-up in Sketch?

**Comment by pamela-drouin** [comment]
@andaleliz updated mobile screen is on the [Exploration - update missing contact info alert text](https://sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c). Please let me know if you have any feedback!

**Comment by andaleliz** [comment]
@pamela-drouin this looks like a great thing to take to content office hours for review, well done! I wouldn't change a thing about it at this point.

**Comment by pamela-drouin** [comment]
@andaleliz Went to content office hours and got great advice from Danielle! She suggested changing the body text:

> **Current**: "To manage your notification settings, first update at least one form of contact information."
>
> **Suggestion**: "To get started managing your notification settings, add an email address or phone number to your profile."

I will go ahead and update the screen!

**Comment by pamela-drouin** [comment]
Screen is updated -- see this mobile mock-up: 

https://sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/p/8F33D983-75FB-4317-9DAF-D8306F3966FB/canvas?annotation=c65ad1c1-750b-41f4-bbd8-cc92c7d0da8e

**Comment by mtcA6** [comment]
@pamela-drouin is there an updated desktop version too?

**Comment by pamela-drouin** [comment]
@mtcA6 sorry I missed this -- there is not an updated desktop version. Mobile will always be the most up-to-date.

**Comment by andaleliz** [comment]
@pamela-drouin I didn't do a good job of explaining this when I walked you through Sketch files as part of onboarding - we do typically create desktop and mobile versions of everything once we've landed on a particular direction.  Sometimes it feels redundant, but it is helpful for folks to be able to see both.

**Comment by pamela-drouin** [comment]
Ah, ok! I must have gotten my wires crossed somewhere. I can go ahead and
fix this.

**Comment by pamela-drouin** [comment]
Closing this -- as it turns out, @andaleliz beat me to it and had already updated the desktop version 😺
