### ISSUE TITLE
[UX][Content] Create FAQ Guide for MSAs

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#59722]
## Description
In preparation for the pilot with Wilkes-Barre, let's create a FAQ Guide that can be provided to MSAs and that contains the following:
- Screenshots of the happy-path workflow for eCheck-in w/ Travel
-  How to record feedback they may get from Veterans
- Answers to what we anticipate will be the frequently-asked questions
    - How do I submit a claim?
    - What type of claim can I submit?
    - What do I do if I did not travel from my home address?
    - What do I do if I did not use my own vehicle?
    - What do I do if I have receipts to submit?
    - How do I know if my claim has been submitted?
    - How can I find out if my claim was approved?
    - When will I get my money?
    - Can I submit a claim without doing eCheck-in?
    - Can I submit a claim later, after my appointment?
    - Who can I contact if I have questions or problems with my claim?

## Tasks
- [x] Create the FAQ Guide
- [x] Record a short (30-45 second) demo
- [x] Run FAQ Guide by UX, Mark & Stephen
- [ ] Upload to SharePoint & make sure is accessible to any VA employee

## Acceptance Criteria
- [x] FAQ Guide has been created & reviewed & uploaded
- [x] Demo has been recorded

**Comment by loripusey** [comment]
@kellysmith1008 assigned this to you; if you can go ahead and take a stab at this; I don't think it needs to be big and fancy
cc: @benbrasso-agile6

**Comment by kellysmith1008** [comment]
We've gotten sign-off from Lori, Ben, and Stephen. Waiting on sign-off from Mark. @benbrasso-agile6 recorded the demo and has uploaded it to sharepoint. I'll attach the FAQ document here after all approvals and Ben will upload to sharepoint with the demo video.

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 I've attached the Word document - I made your changes, we got sign-off from Mark in slack, so we're good to go for you to upload it! Thanks!
[https://app.zenhub.com/files/133843125/e0936c38-abf5-442b-afce-80d110abc7eb/download](https://app.zenhub.com/files/133843125/e0936c38-abf5-442b-afce-80d110abc7eb/download)

**Comment by benbrasso-agile6** [comment]
https://dvagov-my.sharepoint.com/:w:/g/personal/benjamin_brasso_va_gov/EbWC5IPc3UBIk7I9ZjLB53YBaCciLpuoVyYCPhvB5QmoZQ?e=oNpdic
