### ISSUE TITLE
Add language to unauth pages about how to upload Self-Assessment form to BDD 526 claim

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#59723]
## Issue Description
We need to provide Veterans with the information they need to upload a Self-Assessment Part A to their disability compensation claim when they are using the BDD program. 

---

## Supporting artifacts

- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/README.md
- Link to or attach user flows:
- Link to prototype or mockups: Page 1 of [Modifications to VA.gov’s BDD Claim Flow for New SHA Part A.docx](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/collab-cycle/Modifications%20to%20VA.gov%E2%80%99s%20BDD%20Claim%20Flow%20for%20New%20SHA%20Part%20A.docx)
- Link to any epics/issues that may be helpful: [Self Assessment Part A for BDD Flow](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/56579)
[Collaboration Cycle for [Benefits Disability Experience, Disability Comp Application](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/56612)

## Tasks
- [x] Consider R&S main page to communicate how to upload, then crosslink to this from the below pages. Like: "Learn more about the health self-assessment and how to upload this form." Or, do we want to add the upload info in full to each of the below pages. 
- [ ] Add Self-Assessment how-to-upload content to https://www.va.gov/disability/how-to-file-claim/evidence-needed/
- [ ] Add Self-Assessment how-to-upload content to https://www.va.gov/disability/upload-supporting-evidence/
- [ ] Add Self-Assessment how-to-upload content to https://www.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/
- [ ] Add Self-Assessment how-to-upload content to https://www.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/file-while-overseas/

## Acceptance Criteria
- [x] Content is findable that guides service members using the BDD program on how to upload the self-assessment Part A after they've already filed their disability claim.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
These changes are all live. Closing ticket.
