### ISSUE TITLE
Set up new sketch files for use 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#59744]
## Tasks

- [x] Create a production Sketch file (pre-check-in, check-in, and a placeholder for unified experience), set up Sketch page structure, and (re)create prototypes
- [x] Update [Sketch links in GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin#production-wireframes-in-va-sketch-cloud) 
- [x] Create pre-check-in and check-in non-prod Sketch files, set up Sketch page structure, and (re)create prototype for travel pay feature 
- [ ] Update the unified experience sketch file to align the naming and format from the pilot pci/ci sketch files @ytsaoca 
- [x] Utilize the sketchcloud's collections feature on Health Care Applications project space
- [x] Determine if/how we want to use labels (e.g., On Hold, Backlogged, etc.) in the feature page names

## AC

- [x] Production Sketch files are created (pre-check-in and check-in)
- [x] GitHub is updated
- [x] Release the pre-check-in and check-in non-prod Sketch files on sketchcloud
- [x] Pre-check-in and check-in non-prod Sketch files are created 
- [ ] Unified experience sketch file is updated @ytsaoca 
- [ ] Create f/u tickets. E.g., offboard Abstract.

**Comment by zach-park** [comment]
I made a minor update. Otherwise, it looks good!

**Comment by ytsaoca** [comment]
Unified experience sketch file:https://www.sketch.com/s/00bb49e1-42a1-4c5d-99c8-48e5dc502e71

**Comment by zach-park** [comment]
@ytsaoca , I've noticed some pages are unmarked with tag emoji. I was assuming that they needed to be confirmed so I added the "❓" emoji as a temporary tag. Other than that, it looks great. Thank you.

**Comment by zach-park** [comment]
@benbrasso-agile6 @ytsaoca @cgednalske , one more check re: the unified sketch file, do we share out any link from the file? If so, we may need to keep the original sketch file and update it instead...

**Comment by zach-park** [comment]
Transition is complete
- GitHub URLs are updated with the new SketchCloud URLs.
- All sketch files are renamed with final names (i.e., removed the "(Pilot)").
- Legacy sketch files (that were depending on the Abstract) were renamed with the prefix "[ARCHIVED - DO NOT USE]")
@benbrasso-agile6 @ytsaoca @cgednalske @kellysmith1008 Cc: @loripusey

**Comment by zach-park** [comment]
We may need a follow-up ticket to organize or clean up the unused or old sketch files in the [CIE collection](https://www.sketch.com/workspace/c99d3e96-7c23-4210-b173-92a2b73a8788/p/51829d69-2e7c-4aeb-b06f-a399c357bc66/c/a64a0cf7-424e-4695-8a4d-81f2bb3f2a60).
