### ISSUE TITLE
Content support for Pre-need eligibility determination for burial in a VA national cemetery

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#59745]
## Issue Description

The product team working on the modernized pre-need eligibility determination for burial in a VA national cemetery opened an intake request for us to give content support. 

They will be doing usability testing the week of June 6 and will have a revised prototype ready for us the week of June 19. 

We'll need to work on the prototype to make sure it's plain language and adheres to our style guide. We'll also want to look at the intro page to the form and have it align more closely with the new format we've been working on (transfer of entitlement is one example).

Intake request: #58437

Artifacts from product team:

- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/burials-memorials/pre-need/README-2023.md
- Link to or attach user flows: [Pre-Need Pre-Integration Process Flow 051523.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/11481432/Pre-Need.Pre-Integration.Process.Flow.051523.pdf)
[Pre-need Integration Process Flow 051623.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/11488930/Pre-need.Integration.Process.Flow.051623.pdf)
- Link to prototype or mockups: https://vaselfservice.invisionapp.com/console/share/BGYS6FJQ49H **This will be updated after usability testing**

## Tasks
- [ ] Edit prototype (Aliyah)
- [ ] Review (Laura)
- [ ] Post final content for product team in intake request

## Acceptance Criteria
- [ ] Product team has final suggested content

**Comment by aliyahblackmore** [comment]
**Update here:** Meeting with Cindy this afternoon to discuss some challenges with the form labels that they're having.

**Comment by aliyahblackmore** [comment]
Hi @laurwill - this is the word document with my review of the pre-need eligibility application content that their team passed to us in this GitHub file. 

- I exported the content to a Word document on 7/18 and started my review then. 
- As we chatted last week, I did a full review of the content and included questions in the document. The questions are numbered to track the responses from Cindy/SMEs. I'll post the questions in the intake request by tomorrow for Cindy and tag you.
- While I’m OOO, you’ll adjust content as needed based on responses and can pass the document to their team. You can remove any comments/notes that are resolved after your review.

**[Pre-need eligibility review_AB_7.18.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12165694/Pre-need.eligibility.review_AB_7.18.docx)**

**Comment by aliyahblackmore** [comment]
Updates here (while I was OOO): 

- Laura learned from their team on 8/4 that they'll be doing additional testing the week of week of 8/14. 
- She prioritized key labels and pulled a few pieces of content from my content document and shared with them in their sketch files.
- We'll provide remaining/more content guidance after they share their testing findings (8/25).

The suggestions are in [this comment](https://www.sketch.com/s/103478a1-4061-48e4-809d-92f6e32cbfed/a/0AGe44e?annotation=a5a01920-432a-4f5d-80a3-418415e8c730#Comment) in the intake request.

**Comment by aliyahblackmore** [comment]
**Update here:** 

8/29 - Their team posted their[ research readout](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/burials-memorials/pre-need/research/integration-research-aug23/Pre-Need%20Integration%20Study%20Readout%20-%20August%202023.pdf), [suggestions for the static pages](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61517#issuecomment-1698013066), and Cindy is in the process of updating the [content source of truth document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/burials-memorials/pre-need/content/pre-need-integration-content.MD).

We'll wait for their team to confirm when the source of truth document is updated before starting to review this form content again. 

In the mean time, I'll start on updates to the static pages (in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61517))

**Comment by aliyahblackmore** [comment]
We're picking up this work again. We met with their team yesterday and plan to have content feedback to them next week. 

This is the content source of truth document with the adjustments after testing
[Content source of truth document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/burials-memorials/pre-need/content/pre-need-integration-content.MD#va-form-40-10007-apply-for-pre-need-eligibility-determination---integration-content-document)

**Notes from sync with Laura (A and Lily sat in for context) 10/13:** 

- Aliyah to follow up with Cindy to determine if the [alternate signer form](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-0972%20Alternate%20Signer/sourceoftruth.md) is required when someone is filling out the pre-need form on behalf of someone else. If so, we can adjust language to align with the alternate signer form (if we can't use "Your") or we'd use "Your" across the screens. 

- If someone is applying for themself use "you" or "your."  Use "Applicant" if someone is filling out this form for someone else. Laura flagged that there was a previous convo about "Claimant," "Beneficiary" or "Applicant" - she's going to flag this in the channel for Beth. Flagging that the [PDF version of the pre-need form](https://www.va.gov/vaforms/va/pdf/va40-10007.pdf) uses "Claimant"

- "They have a disability that prevents them from making decisions for themselves or providing the information needed to complete forms, or" was the language that Laura chatted more about with Danielle. We're okay to keep this in.

- Use of "Spouse/Child/Parent"  - Laura to start a chat about this and we can continue the conversation in a sync next week.  PDF version of Pre-need form uses "Spouse/Child," but the modern system of pre-need form requires "Husband/Wife/Son/Daughter." 

- Aliyah to work on content feedback and flag the pieces of content that are used across multiple screens (i.e. Identity questions or "Military service question). Review these with Laura on Tuesday so that we apply the same changes across other screens.

**Comment by aliyahblackmore** [comment]
Hi @laurwill - 

This is my feedback on the pre-need eligibility application. As I confirmed with Cindy, I've worked from the [content source of truth documen](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/burials-memorials/pre-need/content/pre-need-integration-content.MD#chapter-title-step-5-of-7-burial-benefits-h2-if-applying-for-self-and-applicant-is-a-non-veteran)t. I'm considering 10/13 the date that I started my review of the post testing material. 

As mentioned via Slack, there are a few last questions that I posted for Cindy in the intake request this morning. Once she replies I'll need to update the content. 

[Post research_pre need eligibility form_AB_10.5.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/13056158/Post.research_pre.need.eligibility.form_AB_10.5.docx)

**Comment by aliyahblackmore** [comment]
Hi @laurwill - this is my feedback in a SharePoint document. 

[SharePoint link to post research pre need eligibility form](
https://dvagov-my.sharepoint.com/:w:/r/personal/aliyah_blackmore_va_gov/Documents/Documents/2023/Post%20research_pre%20need%20eligibility%20form_AB_10.5.docx?d=wb935bacba264475ca16ed4f1d54362bf&csf=1&web=1&e=n3wUbD)

**Comment by aliyahblackmore** [comment]
Capturing some updates following our sync @laurwill 

- You'll flag in comments that they need to confirm whether an affidavit and the forms are needed **OR** if someone can just submit the forms.
- You'll flag a suggestion to include information dynamically re: the documents needed depending on what someone selects (i.e. apply for self or applying for someone else).
- You'll leave the "mail and fax" information on the upload screen with some adjustments. And will suggest similar content for an error message.

You'll pass the SharePoint document to their team.

**Comment by laurwill** [comment]
@aliyahblackmore I think this is an ancient ticket for the work on the actual form — shall we move this to validate?

**Comment by aliyahblackmore** [comment]
@laurwill yes, this is okay to validate! Any follow up convo with that team was happening in their intake request.
