### ISSUE TITLE
Run a staging test with the proof of concept

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#59759]
As a LGA Product Manager, I want to run a test of the proof of concept in order to ensure that it's working properly and detect any issues so that we can resolve them. 

Do this test in staging!
This is the preferred way of testing. We will fall back to the [local test](https://app.zenhub.com/workspaces/logingov-adoption-team-632280b31e745000136a61fc/issues/gh/department-of-veterans-affairs/va.gov-team/59435) if this isn't going to be possible in time for our sprint 22 demo.

We'll have a way to catch the emails and avoid sending it to places it should not go (ie out in production).

## Tasks
- [ ] Use test user accounts to log in with legacy credential, thereby triggering the process
- [ ] Access email inboxes of test users
- [ ] Confirm that email is received
- [ ] Click on CTA in the email - go to login page
- [ ] Verify opens (and sends) in VA Notify-based performance reporting
- [ ] View a report in Google Analytics  clickthrough

## Acceptance criteria 
- [ ] Able to see data about test emails
- [ ] Document describing issues & proposed improvements exists

**Comment by jrjamespdx** [comment]
Closed as we're no longer attempting to test in staging or local.
