### ISSUE TITLE
Weekly Case Open Reporting For Each Sprint

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#59758]
## Issue Description
_Each Sprint this ticket should be created and include reporting for weekly case open report, case closure/modification report and a breakdown report of Tier 2/Tier3/EVSS._

---
## Tasks
- [x] Resolve 25-42 incoming cases daily - capture and attach at the end of each week of the Sprint - a daily cases summary (by week) in the form of a document, comment, screenshot or link with summary of activity for incoming cases - In the form of a comprehensive Dashboard
- [x] Weekly Case open report document 
- [x] Weekly Case closure/modification report document 
- [x] Breakdown report for the following: 
- [x] Tier 2 report - by case type and case category  
- [x] Tier 3 report - by case type and case category  
- [x] Tier 3 EVSS report - by case type and case category  

## Acceptance Criteria
- [ ] Attach Dashboard 
- [x] Each task is complete and requested reports are attached prior to closing
- [x] Confirm resolving 25-42 cases daily
- [ ] Recording blockers or deficiencies_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
@ervin will create a dashboard that includes completion of all the tasks and acceptance criteria above and post a screenshot twice during the Sprint - once for each week.

**Comment by edpearson20** [comment]
In progress, working on the new reporting.

**Comment by Kimberley2019** [comment]
The breakdown of average case totals are below:

Daily total: 65
T2 - 35
T3 EVSS - 30
T3 - 10

**Comment by manalo-soco** [comment]
Ref to[ this ticket ](https://app.zenhub.com/workspaces/contact-center-62cdd9546ec1530018209672/issues/gh/department-of-veterans-affairs/va.gov-team/59924)
