### ISSUE TITLE
[UX] Create New VA Notify Template for Check-in Text Message that includes Information about Checking in with Mobile App

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#59755]
## Scenario
The Mobile App team is not including a push notification as part of the MVP. We have been asked to update these text messages we send Veterans as part of check-in to ensure that they are aware that they can check-in using the Mobile App.
 - Text message we already send them when they text "check in" to 53079 and we send them a check-in link
  
## Content
[https://github.com/department-of-veterans-affairs/va.gov-team/issues/59278](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59278)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/2715cecb-393a-4338-a519-0bcb278f6210)

## Tasks
- [ ] ~Get VA Notify to create a new template for message that is sent when Vet texts "check in"~
- [ ] ~Get the template ID~
- [ ] Let VeText know that they will need to update the existing VA Notify template with the new text message

**Comment by loripusey** [comment]
@loripusey Let VeText know that they have work to do (give them the template ID)

**Comment by loripusey** [comment]
@kellysmith1008 since you have interacted with VA notify before, can you point this one? if you need to discuss let me know.

**Comment by kellysmith1008** [comment]
@loripusey Nice - that sounds good to me!

**Comment by benbrasso-agile6** [comment]
One thing I wanted to mention: there was a mention or two in the recent research study that Veteran's prefer when sentences or topics are separated out in paragraphs for the text messages. Something to consider here.

**Comment by loripusey** [comment]
@kellysmith1008 after our eng sync with the Mobile App team, it seems that there will not be a pilot for this feature; so we really don't need a new VA Notify template but we will just need to request that VeText team updates the existing template with the new content; I will communicate this to Justin in slack and cc you and Kay to let him know that we will need this. It should only take them a few minutes to use the tool to update the template content but it will need to be timed with the release of this feature.
cc: @brianseek @benbrasso-agile6 @anita-halici

**Comment by benbrasso-agile6** [comment]
One thing I spoke to Kristen about this week was, knowing that, should the new text message and poster still be piloted at a specific site. She said she would need to discuss with OCTO. This was a few days ago.

**Comment by kellysmith1008** [comment]
Thanks for the update, @loripusey - let me know if you need me to do anything to help with communication!

**Comment by loripusey** [comment]
In the 6/29 TOT, group decided on a structured roll-out as follows; see [Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1688068421685049?thread_ts=1688068414.878979&cid=C022AC2STBM)
- Roll out the Mobile App feature to everyone
- Conduct a Pilot using the new poster to advertise the feature
- After the pilot, roll out the new text message & front-end communication on the eCheck-in Login page to add more advertisement

On 6/29, I notified Justin on the VeText team that we will need to make a change to a text messge; see [Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1688053669392019)
