### ISSUE TITLE
[FE] Add Mobile App Info to the Pre-Check-in Completion Page

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#59757]
## NOTE
We need to put this behind a feature flag.

## Scenario
The Mobile App team is not including a push notification as part of the MVP. We have been asked to add information to the Pre-Check-in completion page to let Veteran know that they can check-in using the Mobile App.
  
## Wireframes
[https://github.com/department-of-veterans-affairs/va.gov-team/issues/59275](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59275)

## Tasks
- [ ] [FE] Update the message on the Pre-Check-in completion page
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
we do not need this as there will be no changes; changes will be to Danielle's [resource page ](https://www.va.gov/resources/how-to-check-in-with-your-smartphone-for-some-va-appointments/)
