### ISSUE TITLE
[CST] Status Tab, Recent activity (tracked items)

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#59761]
## Value Statement
**_As a_** veteran with a disability claim
**_I want to_** to be able to clearly identify what actions are being taken on my claim by the VA, as well as requests that are for third parties
**_So that_** I'm aware of what's going on with the claim, and I'm what other people are responsible to provide on my behalf and so I can take follow up actions with those third parties if necessary

---
## Background Context

The "Recent Activity" section of the Status tab informs Veterans about actions being taken on the claim by the VA and show a blue alert for any open 3P evidence requests.

## Design

**Figma**

Main spec with Recent Activity logic

- [Recent Activity](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=966-7066&mode=design&t=ZOkXnD61I66AvJCS-0)
- [ListItem component](https://www.figma.com/file/lbRZz68qGRGTdUigcoJq3a/Local-BMT-Components?type=design&node-id=158-126&mode=design&t=TJhso1wQwAtMUSj6-4)

___________________________________________________________

Other specs (for reference)

- [Core screen](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=0-593&mode=design&t=WJW1EPaD4lQk3ooF-4) (Look at "Recent Activity" portion of mock)

<img width="560" alt="Screenshot 2024-02-08 at 1 35 27 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/d51a9cd5-8775-4234-8cdd-01d3c524ab9e">

- [How 3P Evidence Requests show up in Recent Activity](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=630-12980&mode=design&t=WJW1EPaD4lQk3ooF-4)

<img width="513" alt="Screenshot 2024-02-08 at 1 39 55 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/73ad975f-32b6-49f1-9d24-eb325e0c6b7c">

### Date - Status mapping
- NEEDED_FROM_YOU / NEEDED_FROM_OTHERS - requestedDate
- SUBMITTED_AWAITING_REVIEW - Most likely use the oldest recent `uploadDate` from the list of documents
- INITIAL_REVIEW_COMPLETE - receivedDate
- ACCEPTED - receivedDate
- NO_LONGER_REQUIRED - closedDate

## Designs and Build Notes
- List items come from tracked items
- We're showing items that status "needed from others" and "needed from you", "no longer needed"
- We're not showing evidence submissions
- If the status of the tracked item is complete than the date should be the "received" date.

## Engineering Notes
[Eng Implementation Notes](https://docs.google.com/spreadsheets/d/1Z0Z9l_NcP7KDxtshZ6B8uOvSbyC2oHZyMErpxLEaadk/edit?usp=sharing)

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] Design recent activity list item description text for the given request types and add link for that to the ticket
- [ ] Design and Engineer meet to discuss design mocks 
- [ ] Create engineering spec doc

## Acceptance Criteria
- [x] An alert is provided for open requests, needed from others that confirms the user does not have to submit a requested item, but they can if they like. A link is provided to the evidence submission section of CST. 
- [x] There is a header that clearly indicates this section as distinct from other sections.
- [x] Open requests for third parties are salient, but not as salient as requests for the veteran
- [x] Requests are are sorted by reverse chronological order (newest to oldest)
- [x] Should be behind feature flag `cst_use_claim_details_v2`
- [x] Pagination is included and the list should not require excessive scrolling, 10 items max. 
- [x] Pagination is hidden if there's 10 items or less.
- [x] The Pagination design should be visually consistent with other pagination design approaches found elsewhere in CST 

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [x] Design performs design QA and verifies the implementation matches the design spec
- [ ] Product performs functional QA and verifies acceptance criteria was met

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherWidmont** [comment]
To resize this & talk about it as a group

**Comment by jacobworrell** [comment]
vertically slice into two tickets: 1) header + phase, 2) recent activity, which includes alert and pagination states.

**Comment by skylerschain** [comment]
[Added variations of the "Step [x] of 5" card here](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=469-3050&mode=design&t=neSPbjBOLhwJ1xAi-4) with lorem ipsum as initial text until we have the chance to work with content on finalizing that.

**Comment by pmclaren19** [comment]
@skylerschain is there a figma design link for this that you can add?

**Comment by pmclaren19** [comment]
@jacobworrell I thought we were doing these tickets separately and recent activity was going to be its own ticket?

**Comment by pmclaren19** [comment]
I think this ticket is a duplicate and was replaced with https://github.com/department-of-veterans-affairs/va.gov-team/issues/74247 @jacobworrell thoughts?

**Comment by skylerschain** [comment]
@pmclaren19 Updated Design section with Figma links to core screen and step card variations.

**Comment by skylerschain** [comment]
Updated ticket title, Background section, and Design section to clarify that this is about Recent Activity specifically, and provide more detailed screenshots and Figma links. cc: @pmclaren19

**Comment by pmclaren19** [comment]
Spoke to @skylerschain and @jerekshoe yesterday about the design/ eng specs for the tracked items and the different event types. 

After our discussion talked to @skylerschain this morning and there is some design work needed in order to determine what the recent activity list item description is going to be for a given tracked item event type. Updated the tasks on the ticket to reflect this work. He will let us know when this work is done and engineering work can continue!

**Comment by skylerschain** [comment]
Reviewed recent additions to design spec with @pmclaren19 and @jerekshoe. Reassigning back to @pmclaren19 for development.

**Comment by HeatherWidmont** [comment]
@samcoforma to review

**Comment by HeatherWidmont** [comment]
Has been reviewed & merged. @jacobworrell to validate

**Comment by jacobworrell** [comment]
@skylerschain I'm done my QA. Looks good. Feel free to close with comment after you do yours.
