### ISSUE TITLE
Add screenshot to Help users to stay informed of their application status pattern

### ISSUE THREAD

**Issue by taylojill** [department-of-veterans-affairs/va.gov-team#59762]

**Comment by taylojill** [comment]
## Description
Add an additional screenshot to the "Help users to stay informed of their application status" pattern.

## Tasks

- [ ] Identify a user account from staging that shows claim status tool in MyVA.
- [ ] Capture claim status tool screenshot from MyVA.
- [ ] Add screenshot to "Help users to stay informed of their application status" pattern.
- [ ] Request a review of new screenshot.
- [ ] Once the screenshot is approved, update pattern and publish to design.va.gov

**Comment by taylojill** [comment]
Hi @humancompanion-usds. Please review screenshot below from claim status tool in MyVa. Will this work?
![claim-status-in-myva.png](https://images.zenhubusercontent.com/62bf4c7c639e74afe30fad00/ed09d155-0692-46ca-b8b6-28890e555d1a)
