### ISSUE TITLE
Set up Flipper for staging test

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#59765]
[Staging test](https://app.zenhub.com/workspaces/logingov-adoption-team-632280b31e745000136a61fc/issues/gh/department-of-veterans-affairs/va.gov-team/59759)

In order to run the staging test, we want to create a Flipper which will turn on/off the Reactivation campaign. Then we'll turn it on for staging. 

## Tasks
- [x] Add a flag to the config file
- [x] Apply it to the credential service so it knows to be controlled by the flag (and not send emails every time)
- [x] Add Jesse to admin users list

## Acceptance criteria
- [ ] When flag is off, emails don't send
- [ ] When flag is on, emails do send!
