### ISSUE TITLE
Remove Janssen content from COVID pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#59771]
## Issue Description

As of June 1, the FDA has revoked the emergency use authorization of the Janssen vaccine. From the FDA: The last lots of the vaccine purchased by the U.S. Government have expired, there is no demand for new lots of the vaccine in the U.S., and they do not intend to update the strain composition of this vaccine to address emerging variants. 

We should remove mentions of the Janssen vaccine on our pages and consider adding a note with an explanation in case anyone is looking for the vaccine. 

Pages with mentions:

- [COVID-19 vaccines at VA](https://www.va.gov/health-care/covid-19-vaccine/)
- [About COVID-19 vaccines](https://www.va.gov/health-care/covid-19-vaccine/about-covid-19-vaccine/)

## Tasks
- [x] Remove mentions on pages
- [x] Add note
- [x] Review (Laura)
- [x] Send to stakeholder for approval (Randi/Laura)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Live pages have been updated

**Comment by RLHecht** [comment]
I removed the Janssen references on both pages and added a note to the main vaccines page that it's no longer available in the U.S. I also changed the number of authorized vaccines from 4 to 3. @laurwill these are ready for you to review.

**Comment by laurwill** [comment]
Hi @RLHecht , 
These look great. I just made 2 small updates:
- Removed this note under the new Janssen note in the "Currently available vaccines" Q&A: "Note: Not all VA health facilities have all types of vaccines. And facilities may offer different vaccines at different times." This content is covered at the top of the page in the "how to get your vaccine" section, and wanted to avoid stacked notes.
- Removed 1 more reference to Janssen in the "About vaccines" page, from the "Novavax vaccine is the same type..." Q&A

All set for you to send for approval!

**Comment by RLHecht** [comment]
@laurwill I just made the edits that Missy emailed about if you want to take a look. The links she said were broken were all VA pages that don't work in preview so I left those alone.

**Comment by laurwill** [comment]
Thanks Randi! I reviewed and the changes look good.

**Comment by RLHecht** [comment]
Missy approved the last round of changes so I copyedited and published. Moving to validate and will set up a translation ticket.
