### ISSUE TITLE
[bug spike] Contestable Issue failing errors

### ISSUE THREAD

**Issue by kylesoskin** [department-of-veterans-affairs/va.gov-team#59773]
## Value Statement

**_As a_** developer
**_I want to_** know the cause of the contestable issues endpoint failing
**_So that_** we can prevent the error from occurring.

---
## Background Context
Time boxed spike (1-2 hours).

## Tasks
- [ ] Review Sentry and DataDog logs for more info
- [ ] Eliminate known platform failures from the list of findings
- [ ] For other failures, see if we can find the cause 

---
## Definition of Ready 
- [ ] Access to logs and error info (FE and BE)

## Definition of Done
- [ ] We know the cause of the error
- [ ] We've defined a solution if needed, and assigned it to the appropriate party

## Additional Info
![Screenshot 2023-06-05 at 3.20.02 PM.png](https://images.zenhubusercontent.com/62067253500f33af56810776/ca7324a0-f2ef-46ac-a379-4c17ff36db34)## Additional info

@Mottie reporting `http://localhost:3000/v0/notice_of_disagreements/contestable_issues` is returning with an error
