### ISSUE TITLE
Revise Sitewide CAIA touchpoint page on Platform website

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#59775]
## Issue Description

The Platform website has an outdated page explaining what our team's role in collab cycle is. We need to revise the page to incorporate all of CAIA (right now it's just content and IA). This will hopefully also give product teams a better sense of what our team does and how we can support them through the collab cycle.

Platform page to revise: https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request

## Tasks
- [x] Revise Platform page
- [x] Review
- [x] Send to Platform team to update site

## Acceptance Criteria
- [x] Platform team has final revised content
