### ISSUE TITLE
[bug spike] NOD Evidence errors related to zip code

### ISSUE THREAD

**Issue by kylesoskin** [department-of-veterans-affairs/va.gov-team#59772]
## Value Statement

**_As a_** developer
**_I want to_** know the cause of NOD Evidence errors related to zip code
**_So that_** we can prevent the error from occurring.

---
## Background Context
Time boxed spike (1-2 hours).

## Tasks
- [x] Review Sentry and DataDog logs for more info
- [x] Eliminate known platform failures from the list of findings
- [x] For other failures, see if we can find the cause 

---
## Definition of Ready 
- [x] Access to logs and error info (FE and BE)

## Definition of Done
- [x] We know the cause of the error
- [x] We've defined a solution if needed, and assigned it to the appropriate party
- [ ] Ticket(s) for next steps submitted and linked

## More detailed info
```
Faulty NOD Evidence
IDENTIFIERS	CONSUMER	STATUS	CODE	DETAIL	CREATED AT	UPDATED AT
ES GUID	6f9ee4f9-7083-4bac-b07d-85a059345d6e
AP GUID	2833c9ee-c32b-48bb-9cc3-a143b01068c0
US GUID	76e1ec71-dcf0-4f40-9711-71b02370fd6d
VAGOV	error	DOC104	Upstream status: 412 - Invalid ZIP Code. ZIP Code must be 5 digits, or 9 digits in XXXXX-XXXX format. Specify '00000' for non-US addresses.	2023-06-05 07:11:36 UTC	2023-06-05 07:11:36 UTC
ES GUID	c5b6f46f-fa87-4edf-bf0c-e78e5c1f60c8
AP GUID	2833c9ee-c32b-48bb-9cc3-a143b01068c0
US GUID	0fb88d56-6273-4865-97c0-e3cb8f0dfa9d
VAGOV	error	DOC104	Upstream status: 412 - Invalid ZIP Code. ZIP Code must be 5 digits, or 9 digits in XXXXX-XXXX format. Specify '00000' for non-US addresses.	2023-06-05 07:11:36 UTC	2023-06-05 07:11:36 UTC
ES GUID	24557260-fbba-4e76-b995-8005dec5f572
AP GUID	2833c9ee-c32b-48bb-9cc3-a143b01068c0
US GUID	9a4954b7-71ac-4118-8178-07312734af84
VAGOV	error	DOC104	Upstream status: 412 - Invalid ZIP Code. ZIP Code must be 5 digits, or 9 digits in XXXXX-XXXX format. Specify '00000' for non-US addresses.	2023-06-05 07:11:36 UTC	2023-06-05 07:11:36 UTC
ES GUID	3b741864-e84f-4dca-9414-b80cd9534f31
AP GUID	2833c9ee-c32b-48bb-9cc3-a143b01068c0
US GUID	20a6ba1a-e66a-45c1-9514-f47dfb725957
VAGOV	error	DOC104	Upstream status: 412 - Invalid ZIP Code. ZIP Code must be 5 digits, or 9 digits in XXXXX-XXXX format. Specify '00000' for non-US addresses.	2023-06-05 07:11:36 UTC	2023-06-05 07:11:36 UTC
```

**Comment by kylesoskin** [comment]
This is actually what comes back in MPI for the address for the individual from the submission. It is a foreign zip code in Sweden. 

We can have either the frontend check upon submission, or the backend can check if it is valid and replace with '00000' if so (for foreign zip)

**Comment by Mottie** [comment]
Hmmm, was the selected country Sweden? I would think that selecting a different country would make it return an international postal code and not a zip code.

**Comment by kylesoskin** [comment]
@Mottie Yea, the country was Sweden

**Comment by saderagsdale** [comment]
@kylesoskin @Mottie (for tomorrow) do we know enough about the issue to make a user story for it?
