### ISSUE TITLE
Appeals | Add NOD and Supplemental Claims in progress to my-va

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#59792]
## Value Statement

**_As a_** Veteran
**_I want to_** see all my in-progress benefits forms on `/my-va`
**_So that_** I don't have to search for the form to resume.

---
## Background Context

On the `/my-va` page, there is a "Benefits application drafts" section which shows in progress benefits forms. Currently, only our Higher-Level Review form shows up in this section (526EZ is owned by another team).

![Screenshot 2023-06-05 at 2 41 11 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/feb657a3-1528-4400-b67d-bdfb71c9cb7a)

We need to add the Notice of Disagreement and Supplemental Claims forms to the list so that they show up in this section ([docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-set-up-save-in-progress-si#VAFormsLibrary-HowtosetupSaveInProgress(SiP)-UserProfilePage))

## Tasks
- [ ] Add NOD to Benefits application drafts
- [ ] Add Supplemental Claims to Benefits application drafts
- [ ] Add tests as needed

---
## Definition of Ready 
- [ ] Review documentation for adding in progress forms to my-va
- [ ] Addition discussed with auth experience team

## Definition of Done
- [ ] All tasks complete
- [ ] All tests passing
- [ ] Design and/or PM review of result in staging

**Comment by saderagsdale** [comment]
@Mottie what is the estimated complexity for this? Can you find out before tomorrow's refinement?

**Comment by Mottie** [comment]
Updates available in staging

**Comment by eileen-coforma** [comment]
Works in staging! Tested with user 236. If it's as instantaneous in Production as it is in Staging, that'll be amazing 🎉

**Comment by saderagsdale** [comment]
@Mottie can this be closed yet?
