### ISSUE TITLE
BE | Profile | Military Service History | Review and update swagger docs

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#59795]
## Background
Review and update the military service swagger docs for the following endpoints:

| Method | Endpoint                    |
| ------ | --------------------------- |
| GET    | /v0/profile/service_history |

## Tasks
- [ ] Add any useful comments and descriptions.
- [ ] Make sure each endpoint is documented for the following responses:
  - [ ] 200 range
  - [ ] 400 range
  - [ ] 500 range

## Acceptance Criteria
- [ ] Review with FE engineer.
