### ISSUE TITLE
BE | Profile | Contact Info | Review and update swagger docs

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#59794]
## Background
Review and update the personal information swagger docs for the following endpoints:

| Method | Endpoint                       |
| ------ | ------------------------------ |
| GET    | /v0/user                       |
| POST   | /v0/profile/address_validation |
| POST   | /v0/profile/addresses          |
| GET    | /v0/profile/status/:guid       |
| PUT    | /v0/profile/telephones         |
| PUT    | /v0/profile/email_addresses    |

## 

## Tasks
- [ ] Add any useful comments and descriptions.
- [ ] Make sure each endpoint is documented for the following responses:
  - [ ] 200 range
  - [ ] 400 range
  - [ ] 500 range

## Acceptance Criteria
- [ ] Review with FE engineer.
