### ISSUE TITLE
Confirm handshake works vets-api's ITF POST -> Lighthouse -> vets-api -> vets-website

### ISSUE THREAD

**Issue by navaeddie** [department-of-veterans-affairs/va.gov-team#59805]
## Issue Description
Reproduce:
- Find a user with no active ITF
- Login with a User
- Start the file a new claim process for Disability Benefits
- click through the form to create a new Intent to File
note: this occurs on `root_url/disability/file-disability-claim-form-21-526ez/introduction`, when you click "Start the Disability Compensation Application"

---
## Tasks
- Find Test Users that can access Disability Benefits filing form, but do not have an active ITF
- Optional: leverage VBMS UAT to find Users with no active ITF - we might want a bunch of eligible Test Users to triple confirm this is operating correctly [instructions on that](https://nava.slack.com/archives/C04MJV66ZPC/p1686671803441049)

## Acceptance Criteria
- [ ] A User with no Intent to File can start the Disability Benefits filing flow, step through the Intent to File w/o incident
- [ ] Confirm nothing concerning appears in Network tab
- [ ] Confirm an Intent to File with the status of "active" is created for the User
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by navaeddie** [comment]
Maybe a resource for getting data from BGS: https://github.com/department-of-veterans-affairs/bgs-ext

**Comment by RakshindaAslam** [comment]
No longer required as non-prod environment testing was done in Sandbox per Lighthouse contract.
