### ISSUE TITLE
VFF team interview/workshop - Round 1

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#59810]
## Purpose
This team is both digitizing forms and working at some level on a framework to assist other teams in doing so.

## Tasks
- [x] Schedule initial meeting w/ VFF team: Monday, 6/26, @ 12ET @steel36 
- [x] Conduct interview/meeting @tayism 
- [x] Capture notes @twoangstroms & @steel36 

## Acceptance Criteria
- [x] Documented notes
