### ISSUE TITLE
Prep for Debt Resolution team

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#59811]
### Teams to check with:
Debt Resolution team. PM is Heather Reinks [#57105](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57105)

What was their experience?
What worked?
What didn't work well?
What were big pain points

## Tasks
- [x] Reach out to schedule workshop
- [x] Draft [interview guide](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2710077441/4th+Workshop+Debt+Resolution+Team+Conversation+Guide+-+Forms+Digitization+Research)
- [x] Prep [Mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1689787522479/cc4f13720fc43e289f62da452a214b3a7337e04b?sender=u9ea6bd3ca12795949b606150)
- [x] share mural w/ their team

## Acceptance Criteria
- [x] meeting scheduled; Monday 7/24 @ 3pm ET
- [x] guide is ready
- [x] Mural is ready
- [x] mural is shared
