### ISSUE TITLE
[FE] My VA Claim Status EVSS > Lighthouse: Post-launch code cleanup

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#59817]
## Background
Once our update to the claim status widget is complete and we've fully migrated over to the Lighthouse endpoints instead of EVSS, we'll need to do the standard post-launch code cleanup: remove feature flag, update tests, etc.

Discuss with team: it might make sense to hold off on this cleanup until the EVSS service is deprecated in September?

Nov 15 update: [there is an open PR on this](https://github.com/department-of-veterans-affairs/vets-website/pull/25974)

## Tasks
- [x] Remove feature flag from FE code for claim status widget to point to Lighthouse (`my_va_lighthouse_claims`)
- [x] Remove feature flag from API code for claim status widget to point to Lighthouse (`my_va_lighthouse_claims`)
- [x] Update tests as needed (?)

## Acceptance Criteria
- [ ] Claim status widget to point to Lighthouse (`my_va_lighthouse_claims`) feature flipper is removed from FE and API code and not visible on the feature flipper tool

## Validation
- **_Who can validate this ticket? (FE, BE, Design, PM)?_** Dev
- **_How can this work be validated?_** confirm toggle is removed and tests are updated (if needed)

**Comment by ajakabcin** [comment]
Swapping this to the backlog for now in favor of #66660

**Comment by DanielMiller-agile6** [comment]
I updated Derek's PR merged with latest code from main, and resolved a few errors:
https://github.com/department-of-veterans-affairs/vets-website/pull/25974

Also added vets-api PR to remove the feature flag:
https://github.com/department-of-veterans-affairs/vets-api/pull/14849

**Comment by DanielMiller-agile6** [comment]
looks like the FE code has made it to staging. i've verified that calls are still being made to lighthouse and that UX appears to work as expected after removing the feature toggle UI code.  After vets-api PR is merged, the actual toggle will be removed as well, but we'll need to manually remove from the DB as it deploys across environments (see comments in vets-api PR). Until then, the old `my_va_lighthouse_claims` flag shouldn't do anything, since all calls will now be made to lighthouse regardless of toggle state.

<img width="764" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTkxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4424ed6f26d59a0713d5b79e387cc3cc1ad402b1/Screenshot%202023-12-19%20at%202.30.51%E2%80%AFPM.png" alt="Screenshot 2023-12-19 at 2.30.51 PM.png" />

---

@ajakabcin let me know if anything looks "off" in staging :).  I'll update this issue again once vets-api PR is merged and database entries are removed in order to verify removal from the toggler interface as well. I don't have permissions to change toggles on staging, but toggling them there will no longer have any effect.
