### ISSUE TITLE
Remove all Office hours from Collaboration Cycle Calendar

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#59813]
## User Story
As a Governance team member, I want to ensure the Collab Cycle Calendar only has CC and Orientation events so there's no unforeseen conflicts when scheduling meetings.

Assignee: @CherylEvans 
Peer Reviewer: @sterkenburgsara 

## Description
Governance team is moving Collab cycle timeslots on Tuesday and Thursday to be held at 3:30pm ET which currently conflicts with the Analytics Office hours. Since a meeting cannot be booked via Calendly if there's already an event on the calendar, it is important that we remove the Analytics Office Hours from the Collab Cycle Calendar. The analytics office hours already exist on the Platform Office Hours calendar and there is no need for the events to live in both places.

## Impacted Artifacts
Collab Cycle Calendar in google

## Tasks
- [x] Inform @michelle-dooley of the change via the #platform-analytics channel
- [x] Delete all future events of analytics office hours from the calendar
- [x] Confirm that the only events on the Collaboration Cycle calendar are for Governance Collab Cycle touchpoints and Platform orientation sessions

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team has no Collab Cycle touchpoint conflicts due to outside events on the Collab Cycle Calendar

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
@sterkenburgsara Hi Sara. :-) This ticket is ready for your peer review.

**Comment by sterkenburgsara** [comment]
@CherylEvans Looks good! No feedback.
