### ISSUE TITLE
[PM] My VA Claim Status EVSS > Lighthouse: Write release plan & security playbook

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#59820]
## Background
In preparation for PSIR review there are some product-related documents we need to create.

## Tasks
- [x] Write [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/claim-status-lighthouse-migration/launch-materials/claim-status-lighthouse-migration-release-plan.md)
- [x] Write [release readiness checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/claim-status-lighthouse-migration/launch-materials/claim-status-lighthouse-migration-launch-readiness-checklist.md)
- [x] Write "[security playbook](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/claim-status-lighthouse-migration/launch-materials/claim-status-lighthouse-migration-security-playbook.md)" and link to it in the [project outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/claim-status-lighthouse-migration/README.md#security).

## Acceptance Criteria
- [x] Documentation is written in GH

**Comment by ajakabcin** [comment]
Complete - all artifacts are updated and linked
