### ISSUE TITLE
Staging stress tests for copay notifications

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#59822]
## Issue Description
With the load for the amount of statements we need to make sure we are handling the number of workers correctly. Stress testing in staging with various workers and solutions.

---
## Tasks
- [ ] Hit staging with large requests
- [ ] Test multiple solutions

## Acceptance Criteria
- [ ] We don't have to worry about prod performance
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Added mid-sprint in conjunction with copay notification rollout for high request testing. Rolling over as we practice trial and error.
