### ISSUE TITLE
Events tracking for analytics

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#5983]
As a product manager I want to ensure that all the important GA event tracking is implemented so that I can report the success of the VAOS rollout. 

##AC:
- [ ] Consolidated list of events we want to track
- [ ] All events from list are implemented

## Events implementation list
Updated list of events we want to implement:
- [ ] 'schedule appointment' button clicked
    - [ ] On the VAOS homepage
- [ ] 'submit request/appointment' button clicked
    - As additional data, capture type of care and flow (VA Req, CC Req, DS)
- [ ] Form submission succeeded
    - As additional data, capture type of care and flow (VA Req, CC Req, DS)
- [ ] Form submission failed
    - As additional data, capture type of care and flow (VA Req, CC Req, DS)
- [ ] 'return to legacy VAOS' link clicked
- [ ] 'Cancel' link clicked
    - As additional data, capture confirmed vs pending & whether VA or CC
- [ ] 'Cancel' succeeded
    - As additional data, capture confirmed vs pending & whether VA or CC
- [ ] 'Cancel' failed
    - As additional data, capture confirmed vs pending & whether VA or CC
- [ ] 'new appointment' button clicked from the appt confirmation page (if they are scheduling another appointment from the 'Confirmation' page)

## Events tracking implementation for errors
- [ ] Failure - Exceeded outstanding requests limit
     - Errored - Exceeded outstanding requests limit
- [ ] Failure - Doesn't meet requests past visits requirement
     - errored - Doesn't meet requests past visits requirement
- [ ] Failure - Doesn't meet direct schedule past visits requirement
     -  errored - Doesn't meet direct schedule past visits requirement
- [ ] Failure - Doesn't have any available clinics
     - errored - Doesn't have any available clinics
- [ ] Failure - Doesn't have any clinics available that match past clinics
     - errored - Doesn't have any clinics available that match past clinics
- [ ] Failure - Doesn't have active PACT members
     -  errored - Doesn't have active PACT members

Per Jeff: A failure being when the user didn't meet the condition and an error being when we had some issue fetching the info for the check

**Comment by markgreenburg** [comment]
Updated list of events we want to implement:
- [ ] 'schedule appointment' button clicked
- [ ] 'submit request/appointment' button clicked
    - As additional data, capture type of care and flow (VA Req, CC Req, DS)
- [ ] Form submission succeeded
    - As additional data, capture type of care and flow (VA Req, CC Req, DS)
- [ ] Form submission failed
    - As additional data, capture type of care and flow (VA Req, CC Req, DS)
- 'return to legacy VAOS' link clicked

**Comment by lenaecb** [comment]
Updated AC to include the "New Appointment" on confirmation page

**Comment by lenaecb** [comment]
Updated AC to include the "New Appointment" on confirmation page

**Comment by jbalboni** [comment]
Not sure where to note this, but I think we want analytics to track all the different eligibility conditions. I think we want to know the most common reasons why a user can't direct schedule or request an appointment.

**Comment by lenaecb** [comment]
Thanks for catching this @jbalboni. Like we talked about, implementing analytics for the eligibility conditions will also help us understand things like what happens for those with PACT and other potential impacts of the different eligibility checks/rules. 

@narin @jbalboni - can you help me with the AC for all the different eligibility conditions so we can get that added to this ticket? I don't think there is a single source outside of the tool where that info is tracked, but maybe there is?

**Comment by jbalboni** [comment]
Yeah, I don't think think there is. Here are all the conditions. I think we would want to track errors and failures separately. A failure being when the user didn't meet the condition and an error being when we had some issue fetching the info for the check:

- Exceeded outstanding requests limit/errored
- Doesn't meet requests past visits requirement/errored
- Doesn't meet direct schedule past visits requirement/errored
- Doesn't have any available clinics/errored
- Doesn't have any clinics available that match past clinics/errored
- Doesn't have active PACT members/errored

If possible, it might be interesting to be able to look at this for specific types of care, too.

**Comment by nedierecel** [comment]
@lenaecb @narin Clarifying question on the acceptance criteria. Are these two actions (the first and last bullets) the same action?

>'schedule appointment' button clicked
 On the VAOS homepage as well as clicking 'schedule another' button from the confirmation page

AND

>'New Appointment' on confirmation page
Tracking "New Appointments" on Confirmation Page - This button was missing vaos-schedule-new-appointment-started again on this interaction. Within GA, we can add the page dimension to distinguish which pages drove the activity.

@jbalboni - Thanks for also surfacing those errors. If helpful in your naming convention, we have a new global dataLayer variable called `error-key`. For example, if you want to pass in an event to capture the Exceeded Requests failure, you could structure it like `dataLayer.push({ 'event': 'vaos-error', 'error-key': 'exceeded-requests'});`

**Comment by jbalboni** [comment]
@nedierecel That seems useful. Is the error-key meant to be used with multiple different event names? Or is it extra info telling GA that this is an error event?

**Comment by lenaecb** [comment]
Oh lawd, yes, @nedierecel that is redundant. I have updated the AC to correct the redudency.

**Comment by narin** [comment]
@nedierecel @lenaecb I think they should be 2 separate events.  The first one is on the Appointment List 
 page (landing page), and then there is a second schedule button on the confirmation page after a user schedules in case they want to schedule another appointment. I'm assuming we'd want to track these independently?

@jbalboni Thanks for listing the possible error cases.  Will implement them within this same ticket/PR as well.

**Comment by lenaecb** [comment]
@narin - Yes, track them separately. Sorry if the AC is confusing. I can break bullet 1 back out so that there is an event for 'Schedule an appt' from the landing page and then the 2 tracking on the confirmation page for 'New Appointment.'

I also added the errors to the AC for ease of reference.

**Comment by nedierecel** [comment]
@jbalboni For your question below, moreso the latter--it was meant to make the error event more of a generic value with extra information (in case it was too onerous to have different event values for each situation). We can accept either option--we'll need a heads up with whatever option you choose so we can configure within Google Tag Manager.

>That seems useful. Is the error-key meant to be used with multiple different event names? Or is it extra info telling GA that this is an error event?

@narin @lenaecb Thanks for clarifying the bullets. I'll look for those when QAing.

**Comment by narin** [comment]
@nedierecel I have the events in place, just working on passing along the additional data and error codes.  Can you please review the following naming convention when you get a chance?  Thanks so much.

- 'schedule appointment' button clicked on homepage
  - `vaos-schedule-appointment-button-clicked`
- 'New Appointment' on confirmation page
  - `vaos-schedule-another-appointment-button-clicked`
- 'submit request/appointment' button clicked
  - `vaos-community-care-submission-attempted`
  - `vaos-direct-submission-attempted`
  - `vaos-request-submission-attempted`
  - As additional data, capture type of care and flow (VA Req, CC Req, DS)
    - `{ typeOfCare: ‘Primary Care’, flow: ‘direct’}`
- Form submission succeeded
  - `vaos-community-care-submission-succeeded`
  - `vaos-direct-submission-succeeded`
  - `vaos-request-submission-succeeded`
  - As additional data, capture type of care and flow (VA Req, CC Req, DS)
    - `{ typeOfCare: ‘Primary Care’, flow: ‘direct’}`
- Form submission failed
  - `vaos-community-care-submission-failed`
  - `vaos-direct-submission-failed`
  - `vaos-request-submission-failed`
  - As additional data, capture type of care and flow (VA Req, CC Req, DS)
    - `{ typeOfCare: ‘Primary Care’, flow: ‘direct’}`
- 'return to legacy VAOS' link clicked
	- `vaos-return-to-legacy-link-clicked`
	    - `{ typeOfCare: ‘Primary Care’, flow: ‘direct’}`
- 'Cancel' link clicked
  - `vaos-cancel-appointment-attempted`
  - As additional data, capture confirmed vs pending & whether VA or CC
    - `{ appointmentType: ‘pending’, facilityType: ‘va’}`
- 'Cancel' succeeded
  - `vaos-cancel-appointment-succeeded`
  - As additional data, capture confirmed vs pending & whether VA or CC
    - `{ appointmentType: ‘confirmed’, facilityType: ‘va’}`
- 'Cancel' failed
  - `vaos-cancel-appointment-failed`
  - As additional data, capture confirmed vs pending & whether VA or CC
    - `{ appointmentType: ‘pending’, facilityType: ‘va’}`

**Comment by nedierecel** [comment]
@narin Thanks for the chat and for the update here. Please see my bolded feedback below:

- 'schedule appointment' button clicked on homepage - **Approved**
  - `vaos-schedule-appointment-button-clicked`
- 'New Appointment' on confirmation page - **Approved**
  - `vaos-schedule-another-appointment-button-clicked`
- 'submit request/appointment' button clicked - **We typically end the submission attempts with only "submission", so "attempted" can be removed (e.g. `vaos-community-care-submission`)**
  - `vaos-community-care-submission-attempted`
  - `vaos-direct-submission-attempted`
  - `vaos-request-submission-attempted`
  - As additional data, capture type of care and flow (VA Req, CC Req, DS) - **Would we ever expect to see any other values for flow besides `direct`?**
    - `{ typeOfCare: ‘Primary Care’, flow: ‘direct’}`
- Form submission succeeded - **Recommend updating to end in `-successful` to match other success events**
  - `vaos-community-care-submission-succeeded`
  - `vaos-direct-submission-succeeded`
  - `vaos-request-submission-succeeded`
  - As additional data, capture type of care and flow (VA Req, CC Req, DS) - **Approved**
    - `{ typeOfCare: ‘Primary Care’, flow: ‘direct’}`
- Form submission failed - **Approved** 
  - `vaos-community-care-submission-failed`
  - `vaos-direct-submission-failed`
  - `vaos-request-submission-failed`
  - As additional data, capture type of care and flow (VA Req, CC Req, DS) - **Approved**
    - `{ typeOfCare: ‘Primary Care’, flow: ‘direct’}`
- 'return to legacy VAOS' link clicked - **Approved**
	- `vaos-return-to-legacy-link-clicked`
	    - `{ typeOfCare: ‘Primary Care’, flow: ‘direct’}`
- 'Cancel' link clicked - **Update to `vaos-cancel-appointment-submission`**
  - `vaos-cancel-appointment-attempted`
  - As additional data, capture confirmed vs pending & whether VA or CC - **Approved - Please ensure casing for facilityType values stay consistent**
    - `{ appointmentType: ‘pending’, facilityType: ‘va’}`
- 'Cancel' succeeded - **Update to `vaos-cancel-appointment-successful`**
  - `vaos-cancel-appointment-succeeded`
  - As additional data, capture confirmed vs pending & whether VA or CC
    - `{ appointmentType: ‘confirmed’, facilityType: ‘va’}`
- 'Cancel' failed - **Approved**
  - `vaos-cancel-appointment-failed`
  - As additional data, capture confirmed vs pending & whether VA or CC
    - `{ appointmentType: ‘pending’, facilityType: ‘va’}`

In parallel, I will work on updating settings in Google Tag Manager to capture these new events.

**Comment by narin** [comment]
@nedierecel Thanks for the quick turnaround on the review.  Will implement your feedback.

>   * As additional data, capture type of care and flow (VA Req, CC Req, DS) - **Would we ever expect to see any other values for flow besides `direct`?**

Yes, the other possible values would be something along the lines of `va-request` and `cc-request`.

**Comment by nedierecel** [comment]
@narin Looking forward to the implementation. 

I had one follow-up: in reviewing the submission, submission-successful, and failed events for Appointments (not cancellations), we wouldn't know the `appointmentType` until it is submitted, correct? I assumed this is why the value is omitted. I wanted to confirm my assumption. 

Thanks!

**Comment by narin** [comment]
> @narin Looking forward to the implementation.
> 
> I had one follow-up: in reviewing the submission, submission-successful, and failed events for Appointments (not cancellations), we wouldn't know the `appointmentType` until it is submitted, correct? I assumed this is why the value is omitted. I wanted to confirm my assumption.
> 
> Thanks!

@nedierecel For submission, we _could_ assume the future `appointmentType` based on the flow (e.g. direct => `confirmed`, and cc/va-request => `pending`), but I'm not sure it'd make sense to include it.  What do you think?

Also, for the cancel events, should I follow the same pattern as the submission?
```
vaos-cancel-appointment-submission
vaos-cancel-appointment-submission-successful
vaos-cancel-appointment-submission-failed
```

In your comments, you omitted the "submission" from the event for successful and failed.

I have a PR open for the implementation so you should be able to test the events in staging soon.

**Comment by nedierecel** [comment]
@narin For submission, I don't think it would make sense to include if it's not a certainty. 

Re: cancellations, thank you for catching. You're correct that it should follow the format you have indicated. 

Thank you for the notice on staging. I am updating Google Tag Manager to reflect the `appointmentType`, `flow`, and `facilityType`.

**Comment by nedierecel** [comment]
Hi @narin and @lenaecb Is this ready for a new QA round on Staging?

**Comment by jbalboni** [comment]
@nedierecel We're waiting on VSP review, so the changes aren't on staging yet.

**Comment by jbalboni** [comment]
@nedierecel This should be ready in staging now.

**Comment by narin** [comment]
@nedierecel I'm not sure which user you typically use, but I wasn't able to log on with judy.morrison (dslogon) this morning.  Will try again later.

**Comment by jbalboni** [comment]
Id.me is down right now on staging, so will probably have to wait until it's online again.

**Comment by nedierecel** [comment]
Thanks @narin and @jbalboni I'll try again when it's up. Appreciate the updates!

**Comment by nedierecel** [comment]
@jbalboni @narin - I outlined my observations below and noted follow-ups.

#### Form Submissions
1. `vaos-request-submission` and `vaos-request-submission-successful` - PASSED, with small caveat that GA is passing in an unexpected "error-key" value with the submission event. This is visible in the screenshot. 

I did see a `vaos-error` earlier in the process but was not expecting to set the value later at form submission. **ACTION**: Can you review? I will also explore fixes within Google Tag Manager. 

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/a4de7bcc-8e8c-4d20-8fba-f9a7bef5e467)

2. `vaos-direct-submission-successful` - PASSED WITH CAVEAT - Like the `vaos-request-submission-successful`, it is inheriting the `error-type`. 

3. `vaos-community-care-submission` and `vaos-community-care-submission-successful` - PASSED; I did not encounter an error during this submission, so I did not see the `error-type` pass. 

4.  I could not recreate failed submissions at this time.

#### Errors
1. `vaos-error` - NEEDS UPDATE - Expected to see dataLayer event after reaching an error.

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/8c66e380-8008-4d2b-9f36-1dfca5cdc602)

#### Cancellations
1. `vaos-cancel-appointment-submission` and `vaos-cancel-appointment-submission-successful` - PASSED, including `appointmentType` and `facilityType`
2. `vaos-cancel-appointment-submission-failed` - COULD NOT RECREATE 

#### Navigation Elements 
1. New appointment on Confirmation page - PASSED
2. Schedule an Appointment on VAOS landing page - PASSED
3. Return to VAOS - Can you please comment with link? 

#### Post-Launch 
These were not originally in this thread. Please let us know if these items are a priority.
1. "View your appointments" on Confirmation Page
![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/586b580a-3536-4c0f-82ff-ab43c78502d5)

2. Reason for Appointment - This was on an original thread but did not make it to this updated issue. Is this valuable to the product team?

**Comment by narin** [comment]
Thanks for your feedback @nedierecel.  Will look into those unintentional `error-type`s being passed and add reasonForAppointment as additional info for submission events. 

For the "View your appointments", does `vaos-view-appointments-button-clicked` work as an event name?

Will look into the `vaos-error` dataLayers.

**Comment by nedierecel** [comment]
@narin Thanks for the updates on next steps. Yes, the `vaos-view-appointments-button-clicked` event is a solid event name.

@jonwehausen For your visibility, I added new custom dimensions in non-prod and prod for the following:

- Health Care - VAOS Facility Type (CD slot 75)
- Health Care - VAOS Reason for Appointment (CD slot 76)

**Comment by jbalboni** [comment]
@nedierecel @narin Can we break out these events, and not have them under the `vaos-error` key? They're expected events in the app and we want to be able to monitory how often they happen:

```
vaos-request-exceeded-outstanding-requests-failure
vaos-request-past-visits-failure
vaos-direct-check-past-visits-failure
vaos-direct-available-clinics-failure
vaos-direct-pac-team-failure (currently not used, but may be in future)
```

There's an error variant for all those events that I think we should track as errors, but not these ones.

**Comment by nedierecel** [comment]
@narin We can pass these as standalone events, which I can tweak in Google Tag Manager.

@jbalboni When an error occurs for any of these, is the expected order of events (using `vaos-request-exceeded-outstanding-requests-failure` as an example):

1. `vaos-request-exceeded-outstanding-requests-failure` is pushed first
2. `vaos-error` pushed next, with `error-key` of XYZ.

Thanks!

**Comment by jbalboni** [comment]
Ok, but that makes the `vaos-error` event less meaningful, doesn't it? Those `-failure` events aren't something that has gone wrong they're expected to happen regularly. And they would be getting mixed in with actual application errors that indicate something is wrong with the tool.

It's not really clear to me what the value of `vaos-error` is, either, though.

**Comment by nedierecel** [comment]
@jbalboni Noted - the `vaos-error` was intended to aggregate all errors, but I understand your point on making these `-failure` events stand on their own.  

I think it's fine to remove the `vaos-error` altogether if it's not going to add value. Please let me know what direction you go, and we can remove it from Google Tag Manager so that it only accepts the list you stated above. 

We would then expect:
`vaos-request-exceeded-outstanding-requests-failure` with a code attached to `error-key`

**Comment by jbalboni** [comment]
Ok. I'm inclined to leave `vaos-error` for now and see if we find it useful, but just make those `-failure` events stand on their own.

Also, I'd suggest adding one more event, something like `vaos-not-eligible`, that tracks when a user is stopped from continuing on the form due to having too many of those `-failure` checks. I think that would be useful to track because it would show how many people are forced to drop out of the flow on the facility page.

**Comment by narin** [comment]
@jbalboni Will do, in regards to `vaos-not-eligible`.

@nedierecel:

> We would then expect:
> `vaos-request-exceeded-outstanding-requests-failure` with a code attached to `error-key`

Just to clarify, it would look like this?
```
{
  "event": "vaos-request-exceeded-outstanding-requests-failure",
  "error-key": "request-exceeded-outstanding-requests-failure"
}
```

**Comment by nedierecel** [comment]
@jbalboni - can you review my assumptions?

To confirm, would @narin need to send any `error-key` values with these `-failure` events below? After rereading, it sounds like there would be another event that would be sent separately. 

>There's an error variant for all those events that I think we should track as errors, but not these ones.

```vaos-request-exceeded-outstanding-requests-failure
vaos-request-past-visits-failure
vaos-direct-check-past-visits-failure
vaos-direct-available-clinics-failure
vaos-direct-pac-team-failure (currently not used, but may be in future)```

**Comment by jbalboni** [comment]
@nedierecel @narin I still don't feel like I understand what `error-key` does, but those `-failure` events aren't errors, so wouldn't we leave off `error-key` altogether?

**Comment by narin** [comment]
@nedierecel The changes we discussed the other day should now be on staging, in the case you wanted to do any additional testing.  Closing this out.

**Comment by nedierecel** [comment]
Thanks @narin I'll validate and will reopen if I see anything.
