### ISSUE TITLE
Launch asynch Platform Orientation sessions

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#59835]
## User Story
As a Governance team member, I want to launch the new asynch Platform Orientation process so that VFS teams are made aware of the new options for participating in Platform orientation.

Assignee: @CherylEvans 
Peer Reviewer: @briandeconinck 

## Description
Governance team has completed all necessary steps for getting the new asynch Platform orientation process in place. The purpose of this ticket is to go-live with all of the changes ang begin quarterly recording/hosting of the Platform orientation sessions.

## Impacted Artifacts
- Platform Orientation gh template (see Pull request https://github.com/department-of-veterans-affairs/va.gov-team/pull/60041)
- Orientation sessions page on PW (see draft [Orientation Sessions](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2648866848/58924+Draft+-+Copy+of+Orientation+Sessions))
- Platform Orientation page on PW (see draft [Platform Orientation](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2648965121/58924+Draft+-+Copy+of+Platform+Orientation))
- Operational guidance on Confluence (see #58899 for all impacted docs)

## Tasks
- [x] Cancel Calendly events outside of the 1st month of the quarter
- [x] Merge github ticket pull request
- [x] Publish all changes to Platform Website
- [x] Ensure operational guidance is live/available on Confluence for Platform Orientation hosts
   - I think it would be wise to have orientation hosts contact @platform-governance-team-members via the #platform-team Slack channel if any questions or concerns come up prior to them hosting their session. [LINK](https://dsva.slack.com/archives/CJRQ85PQB/p1688157749921449)
- [x] Announce changes to VFS teams following the Platform Communication playbook
   - Slack announcement [LINK](https://dsva.slack.com/archives/C03R5SBELQM/p1688392194655779)
   - ToT announcement

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS teams are made aware of the new process for participating in Platform Orientation
- [x] The new Platform orientation process for asynch sessions is live

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
#60041

**Comment by shiragoodman** [comment]
@allison0034 can you edit your comment above to include a title so it's easy to track? Thanks!

**Comment by shiragoodman** [comment]
@briandeconinck FYI, since Cheryl is working on Monday 7/3, I have made her the assignee and you the peer reviewer so we can get this closed by end of sprint. Please let me know if you have any questions or concerns. CC @CherylEvans

**Comment by CherylEvans** [comment]
@shiragoodman @briandeconinck I have completed all tasks except Canceling Calendly events outside of the 1st month of the quarter and the ToT announcement.

**Comment by CherylEvans** [comment]
@shiragoodman @briandeconinck I have completed all tasks except Canceling Calendly events outside of the 1st month of the quarter and the ToT announcement.

**Comment by shiragoodman** [comment]
Calendly is giving me issues this morning. It won't even load. Allison said she was having the same problem. I will check again later today.

**Comment by shiragoodman** [comment]
All August and September orientation sessions have been cancelled.
