### ISSUE TITLE
[eFSR] Add dollar sign to spouse benefits on review page

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#59852]
## Issue Description
> [Review page spouse benefits ~~and recreational vehicles~~](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57600#issuecomment-1564990536) are missing $ symbol in review mode.

from [parent functionality ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/55628)

~~Removing recreational vehicles from this ticket since it is addressed [in another ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/59851)~~

Add $ sign to Recreational Vehicles and Real Estate as well since they still need it. 

---
## Tasks
- [x] Add dollar sign to spouse benefits review page portion
- [x] Add dollar sign to recreational vehicles review page portion
- [x] Add dollar sign to real estate review page portion

## Acceptance Criteria
- [x] Spouse benefits dollar amount correctly displayed with dollar sign.
- [x] Recreational vehicles dollar amount correctly displayed with dollar sign.
- [x] Real estate dollar amount correctly displayed with dollar sign.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by OptionSelect** [comment]
Work on this was deprioritized due to issues with EFSR launch. Working on it now.

**Comment by OptionSelect** [comment]
Work on this was deprioritized due to issues with EFSR launch. Working on it now.

**Comment by OptionSelect** [comment]
Currently works the same as Recreational vehicles. Per convo with Andrew we are tabling this until making further progress with Aaron's ticket that is similar.

**Comment by HeatherRienks** [comment]
@Tom-Davis - changing label to med-priority per Brandyn's feedback
