### ISSUE TITLE
[eFSR] Analytics - Add efsr feature flag to submission event for tracking

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#59856]
## Issue Description
Update GA tracking props on submission to monitor enhanced FSR submissions similar to [how we track types of submissions here](https://github.com/department-of-veterans-affairs/vets-website/pull/23174)

---
## Tasks
- [x] Add new property to GA event data

## Acceptance Criteria
- [x] We can now track enhanced FSR submissions
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
Going to carry over to 102! Got caught up with some local dev bugs, pr reviewing and prepping for streamlined works

**Comment by Dr-Pongo** [comment]
Included `enhanced-submission` property in GA `fsr-5655--submission-successful` event

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/6017e48b-edad-4d2d-913c-55f76b65a7be)
