### ISSUE TITLE
[eFSR] Update recreational vehicle on review page

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#59851]
## Issue Description
>[Recreational vehicles review page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57600#issuecomment-1564993520) is missing update button.

>[Review page ~~spouse benefits and~~ recreational vehicles](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57600#issuecomment-1564990536) are missing $ symbol in review mode.

from [parent functionality ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/55628)

Let's try this page with `editModeOnReviewPage: false`, and see if we can get the view/edit/update flow instead of having the input box be visible by default. 

---
## Tasks
- [x] Try updating `editModeOnReviewPage` to see if it fixes the issue.
- [x] Confirm dollar sign is appearing when displaying edit and normal view only mode.

## Acceptance Criteria
- [x] Recreational vehicle input box no longer shown by default on review page.  
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by amponce** [comment]
Closing this issue and opening a new one for the dollar sign since it will apply to several other locations and increase the scope of this ticket. 

We'll talk about the best approach tomorrow morning for supporting the $ symbol
