### ISSUE TITLE
EPIC | EVSS to Lighthouse | Disability Rating

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#59866]
# Background 

## [Samara's leave plan ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/sprint-objectives/maternity-leave-plan-2023.md#update-the-disability-rating-section-of-the-nametag-and-vagov-profile)
**Update the disability rating section of the nametag and VA.gov profile**
Status: The backend migration will be done by the [benefits disability experience team](https://dsva.slack.com/channels/benefits-disability-experience). As of March 2023, Matt Self says they are still in discovery, but it's possible they'll begin work while I am on leave. Our team needs to keep up on this work, as we will need to migrate our frontend connections for the nametag and the profile as soon as they are done.
[Long-term planning](https://docs.google.com/spreadsheets/d/1EN2Z0MPLZ-6qAS3S4q6uiwCekSU1daysJkykDs5bPCs/edit#gid=378891642)

# Artifacts 
[Nametag Readme](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/products/identity-personalization/profile/nametag/README.md)
[Initiative Brief](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/nametag/evssMigrationToLH)
[Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/nametag/evssMigrationToLH/releasePlan.md)
[GA Dashboard ](https://analytics.google.com/analytics/web/#/dashboard/DRqBrmiyTD6l8L75rei0fw/a50123418w177519031p176188361/)

## Latest Update 6/7/2023

- The team met w/ the disability experience team on 5/18/2023 to review the changes 
- [Thread 6/6/2023 it appears things are ready to progress forward](https://dsva.slack.com/archives/C02CQP3RFFX/p1685996894993509) 
     - Tom is going to create stories for the work that's needed  

## Tasks
```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/59869
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/60622
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/61912
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/61095
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/63021
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/63199
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/64089
```

```[tasklist]
### Launch
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/63159
```

```[tasklist]
### Bugs/Enhancements
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65019
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65093
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/66899
```

```[tasklist]
### Post Launch
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/64268
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62241
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/69883
```
