### ISSUE TITLE
Create widget content for VA Form 21-10210 Lay/witness and add to new additional forms page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#59879]
## Issue Description

As part of the digitized forms work, we are creating a new additional forms page as the landing page for many of these. Because these forms will be launching incrementally, we need to add them as react widgets to the page so that 100% of users see only the paper form entry point and a subset of users see the digital form entry point. 

We need to provide the product team with the widget content for both use cases for VA Form 21-10210. Once they give us the react app code we can add it to our Drupal page.

## Tasks
- [x] Provide product team with widget content (Megan)
- [x] Add widget to Drupal page (Megan)

## Acceptance Criteria
- [ ] React widget is on additional forms page

**Comment by megzehn** [comment]
Hello! Here's the widget copy for 21-10210. I'll send this to Tricia as well. 

[Widget copy for VA Form 21-10210 Lay/witness](https://app.zenhub.com/files/133843125/6d7d0c42-e2e4-41c9-8d4c-18c37dbbf782/download)

**Comment by RLHecht** [comment]
Widget code to add to drupal page: form2110210

**Comment by RLHecht** [comment]
Not adding to page until form is ready to launch.

**Comment by RLHecht** [comment]
@megzehn can you test this before we are ready to publish?

**Comment by megzehn** [comment]
Update: The online version of form 21-10210 is now open to 25%. I tested the react widget and published the page with it. Note that this page currently has 2 active widgets on it.
