### ISSUE TITLE
Mocked Auth Usability Testing preparations

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#59876]
#### Mocked Auth Usability Testing
Usability test the Mocked Auth product with VFS users to help develop the product backlog.

Mocked auth allows devs to iterate and to work on their code in a more local way without actually having to sign into an authorized account, which can go down or cause issues. This simplifies the development for dev who aren't in the Identity realm, and this allows them to work even without internet connection since there are no "external calls". This also makes it more consistent

#### Tasks
- [x] develop questions
   - what are dev's workflow with this kind of thing?
   - walkthrough/usability q's
- [x] draft [Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Research/2023-06%20Mocked%20Authentication/Mocked%20authentication%20research%20plan.md)
- [x] draft [convo guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Research/2023-06%20Mocked%20Authentication/Mocked%20authentication%20conversation%20guide.md)
- [x] sync with Core team dev about the questions and wordings
- [x] finalize research artifacts

##### Questions/ideas 
- first page
   - make the front page link more prominent (a CTA link)
   - should we clarify any language in the GH documentation
   - will folks even read it?
   - feedback button doesn't work - remove? or who gets that?
- Select profile page 
   - "what is modded auth" link on profile select page needs to be corrected to the documentation
- who else might use this?
   - PO, testers, Collab Cycle, etc could potentially all look over here
   - note: everything happens here is mock, so a form doesn't actually submit out and get a response for example where staging environment does actually reach out.
- known bugs
   - like all accounts, mock accounts need to have the mocked credential and the mocked MPI record. The error message means the MPI record are not found - mocked auth fails in this case.
      - pre-check after selects a profile an warning if MPI data is missing
      - have flag or info when an account isn't working
      - only allow new mock users that work
   - "code in state is not valid" because you need to go back to the start page after a failed attempt like the state above
      - otherwise stuck in a perpetual state

#### Acceptance Criteria
- [x] Documentation has been updated
- [x] Reviewed by UX Team
- [x] Reviewed by PMs

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by claytonzook** [comment]
@kingbmike This ticket is ready for PM review

**Comment by aparsley** [comment]
Looks great, thank you for the hard work!
