### ISSUE TITLE
Consolidate Frontend and Backend Repos

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#59874]
## Description
Move forntend code to va-identity-dashboard repo. Update github actions 

## Tasks
- [ ] move existing/backend code `api` directory & [update github actions `working directory`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrun)
- [ ] Move frontend code to va-identity-dashboard repo, into `ui` directory
- [ ] update frontend github actions to point to its working directory
- [ ] Add conditional CI - run api or ui actions based on changed code
