### ISSUE TITLE
Create widget content for VA Form 21-4142/4142a and add to new additional forms page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#59877]
## Issue Description

As part of the digitized forms work, we are creating a new additional forms page as the landing page for many of these. Because these forms will be launching incrementally, we need to add them as react widgets to the page so that 100% of users see only the paper form entry point and a subset of users see the digital form entry point. 

We need to provide the product team with the widget content for both use cases for VA Form 21-4142/4142a. Once they give us the react app code we can add it to our Drupal page.

## Tasks
- [x] Provide product team with widget content (Megan)
- [x] Add widget to Drupal page (Megan)

## Acceptance Criteria
- [ ] React widget is on additional forms page

**Comment by megzehn** [comment]
Hi @RLHecht, I'm attaching final widget copy for 21-4142. I'll share this with Tricia as well. Thank you!

[Widget content for VA Form 21-4142](https://app.zenhub.com/files/133843125/3c830e7f-b957-4a3d-b80b-506751a422bb/download)

**Comment by RLHecht** [comment]
Widget code to add to drupal page: form214142

**Comment by RLHecht** [comment]
I added the widget to the page but there's an issue with it showing in Drupal preview. The CMS support team is working on it.
