### ISSUE TITLE
Platform Support Dashboard

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#59885]
## Issue Description
We have received several requests from individual Platform teams wanting to create a Domo dashboards for their support/GH requests/tickets.  We currently have one for [Collaboration Cycle](https://va-gov.domo.com/page/1340527018) and [Platform Website](https://va-gov.domo.com/page/189282309).  The BQ dataset 'vsp_testing_tools.github_issues' is the source data for each of these dashboards.  Instead of continuing to build individual dashboards for each team we would like to create one Support Dashboard that can be filtered to specific teams/labels. 

We would like the new dashboard to contain the following metrics:

- [ ] New Tickets/Requests Received
- [ ] Total Open Tickets
- [ ] Requests Completed/Closed
- [ ] Time (days) resolution (open date to close date)
- [ ] Tickets per support person/assignee

Resources:
![image.png](https://images.zenhubusercontent.com/618144c8b17b33313a8c0cbe/17d416c5-9503-4fdd-93ce-9fd2eeae7301)

https://docs.google.com/spreadsheets/d/1HVtCjYCq57yaVu8jdbFYXyg9AHc1XXtyl29d2Vrg6fE/edit#gid=0

## Tasks
- [ ] Review GH issues data, define metrics and what/how to create cards based on data availability
- [ ] Review vw_governance_github_tickets and vw_vsp_content_github view for transformations as needed for new dashboard
- [ ] Review Collab and Platform support dashboards for examples of how cards are currently viewed - determine best way to display in new dashboard with most flexibility
- [ ] Create new dashboard that contains each of the above metrics in cards views similar to other dashboards (and any other meaningful metrics that surface as part of analysis)
- [ ] Create dashboard level filters for label, state, assignee (similar to filters used in Forms KPIs dashboard![image.png](https://images.zenhubusercontent.com/618144c8b17b33313a8c0cbe/aed0018c-83af-4f74-a160-f72d566ac85b) 
- [ ] QA data based on current GH/support dashboards (does the new dashboard metrics align and provide same level of detail)

## Acceptance Criteria
- [ ] New dashboard in production
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelle-dooley** [comment]
@ChristineYoungZA - configure the dashboard with the cards we created.  With sections and cards similar to the  Platform Website dashboard.

Sections:
Summary:  New tickets, Closed tickets, Open tickets - these would just be raw number like used in the value guage cards
Status: Tickets by status by month 
Days to Close: Avg days to close by month - may need to create a new dataset that aggregates the tickets so that you are only counting the days between open and close one time (not for all labels as there are mulitple rows for each ticket in current table)
Teams:  tickets by teams and tickets by assigneess 

Because the current table has multiple rows per ticket need to be careful and ensure we are doing distinct or unique counts so we are not counting same ticket more than once.  Or as stated above create a new aggregated dataset from the current data as needed.

**Comment by alyssagallion** [comment]
@ChristineYoungZA Can we put a pause on this temporarily? We are working out some things on our end with leadership. Thank you for all of your hard work so far!

CC: @jwoodman5

**Comment by ChristineYoungZA** [comment]
Sure @alyssagallion. Please let us know next steps when ready.
