### ISSUE TITLE
[FE] Update eCheck-in Login Page to Include Information about Checking in with Mobile App

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#59897]
## Note
Needs to be behind this feature flag: check-in-mobile-messaging

## Wireframes
See [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59282)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/858a9526-e2c4-4416-a487-63eab49ecee0)

## Links
Here are the URLs for the 2 app stores:
- [Apple](https://apps.apple.com/us/app/va-health-and-benefits/id1559609596)
- [Google](https://play.google.com/store/search?q=va+health+and+benefits+app&c=apps&hl=en_US&gl=US)

## Tasks
- [ ] [FE] Update eCheck-in Login Page to Include Information about Checking in with Mobile App
- [ ] Add custom events that are reported to Google Analytics for each of the App Store clicks
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/59897?planning-poker) with Zenhub @wullaski

**Comment by loripusey** [comment]
@loripusey get links to the app on the 2 app stores and put in this ticket
