### ISSUE TITLE
[discovery] Define copay notification retry logic

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#59898]
## Issue Description
We should have some retry logic in place for copay notifications in the case that an external dependency fails or is unavailable. We should have some well defined restraints of when to trigger a retried job and how to track them.

---
## Tasks
- [ ] Define retry restraints
- [ ] Determine when to retry
- [ ] How to track retried jobs

## Acceptance Criteria
- [ ] Sidekiq worker retry logic is defined
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
