### ISSUE TITLE
[discovery] Investigate how we can use redis to minimize copay notification external service dependency

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#59892]
## Issue Description
Since copay notifications trigger 1000s of requests in a limited amount of time, we should try to minimize any external service load and dependency. We should look into how we can leverage redis or other data stores to maintain data found from the external service for identifiers we receive from VBS to reference in future requests after the initial load.

---
## Tasks
- [ ] Communicate with teams that maintain data we need
- [ ] Mull over options for maintaining and referencing data
- [ ] Create system architecture diagram that encapsulates this new flow

## Acceptance Criteria
- [ ] We know of a design to implement for maintaining data
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kjsuarez** [comment]
The results of this ticket are captured in [60466](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/60466)
