### ISSUE TITLE
[CHIP] Create a CHIP Endpoint for Getting Demographics

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#59895]
## Tasks
- [ ] [CHIP] **Create a CHIP Endpoint for Getting Demographics**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by wullaski** [comment]
I broke this up into 3 other smaller tickets #61194 #61192 #61187
