### ISSUE TITLE
CMS Export Build [v1] — Transition from GraphQL to CMS Export + transformers 

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#5989]
Note that documenting long-term ownership of CMS Export Build is tracked in initiative #16715

## Problem Statement 
The current (GraphQL-based) build process for the VA.gov CMS is not scalable, and it does not meet the requirements set by DEPO & VA content stakeholders. The number of nodes (essentially pages) that can be published via GraphQL has essentially reached its limit, which means that the 15+ new VAMC sites that are ready to be published via the VA.gov CMS are blocked from doing so. Furthermore, content editors expect that content from the VA.gov CMS will publish to VA.gov in a matter of minutes — "instant publishing" — which is not possible or scalable in the current solution. 

In fall of 2019, the CMS SuperTeam was established ([charter](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/cms-metalsmith-build/2019-11-superteam-draft-charter.md)) to address these issues, and chose an approach based on a new type of CMS export. 

How might we enable the VA.gov CMS to scale and decrease publish times to meet the needs of VFS teams and other VA content writers?

### High level goals 
- All transformers are done 
- Build finishes with no errors
- Diff of HTML between graphQL and file export shows correct results
- Build in under 5 minutes
- Rollout plan to transition from graphQL to content build

## Hypothesis or Bet
If we implement the CMS Export (previously referred to as tome sync) approach, then the CMS will be able to scale to meet the needs of content editors. 
If we implement the CMS Export approach, then content will be published in 5 minutes or less, which will improve the workflows and meet the expectations of content editors.

## We will know we're done when... ("Definition of Done")
- Transformers reach parity with GraphQL 
- CMS Export Build is used to publish content from VA.gov CMS
- Content publishes on VA.gov in 5 minutes or less 

## Out of Scope
- Preview server
- Transformer generator and/or auto-generator
- Transition menus and side nav off of GraphQL

## VSP OKRs
O1: Scale the DEPO Platform to comfortably support 50+ simultaneous VFS builds, leveraging more self-service pathways.
This initiative includes some work towards "KR1: By April 2021, we provide fully self-service options for 5 common VFS tasks" however, the primary reason we are doing this work is to allow the VA.gov CMS to scale to support VAMC sites and other new products (which are currently blocked).

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md) checked into [`products/platform/PRODUCT_NAME/`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/)
    * _Note: the Product Directory Name should match 1:1 with the List of VSP Products_
- [ ] External-facing: a [VFS-facing README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md) exists for this product/feature tool
    - [ ] ... and should be located at `platform/PRODUCT_NAME/README.md`
- [ ] External-facing: a [User Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md) exists for this product/feature/tool, and is updated for changes from this initiative
    - [ ] ... and should be linked from the VFS-facing README for your product
    - [ ] ... and should be located within `platform/PRODUCT_NAME/`, unless you already have another location for it
    - [ ] _(if applicable)_... and post to [#vsp-content-ia](https://dsva.slack.com/channels/vsp-content-ia) about whether this should be added to the [Documentation homepage](https://department-of-veterans-affairs.github.io/va.gov-team/)
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. VSP Newsletter, customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### Documentation
* **`PRODUCT_NAME`**: internal docs in [/products/platform/cms-metalsmith-build](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/platform/cms-metalsmith-build)
* **Product Outline**: [product-outline.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/cms-metalsmith-build/product-outline.md)
* **README**: _link to VFS-facing README for your product_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: measuring success in [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/cms-metalsmith-build/product-outline.md#measuring-success)
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [X] Convert this issue to an epic
- [X] Add your team's label to this epic

**Comment by rianfowler** [comment]
### Previous epic descriptions

*[July 2020 MK:]*

The tickets in this epic represent the remaining work needed to complete the Tome sync build, including creating transformers to enable Find VA Forms and 8 VAMC sites to be released. 

- [ ] Fix the existing transformers with validation errors due to drift
- [ ] Create the remaining transformers
- [ ] Verify the result of the CMS export transformer content build matches the result of the GraphQL content build
- [ ] Handle the preview server

*[pre July description:]*

As VSP is rolling off of active development for the tome-sync build process work, we wanted to make sure that organized the final steps involved.  

We added all relevant stories in this epic and then added all of the dependencies as well so that we can get a view of path remaining.  Each ticket should include a set of acceptance criteria as well so that we are aligned on what is needed to clear the dependency.  

Work with linear dependencies:
1. Publish event needs to tar files and content (#2989) - Owner: CMS
2. Make tarball available in production  (#5984) - Owner: CMS
3. Fetch data for content build (#2699) - Owner: VSP
4. Complete remaining transformations that required images (#3308, #3316, #3339) - Owner: VSP
5. Final Validation of tome-sync build vs graphql site build (#5988) - Owner: VSP & CMS


There is additional work that is being worked on that does not have dependencies. These will be worked on by VSP while we wait for steps 1 and 2 to be completed.
- Filter & Transform node-event_listing content (#3338) - Owner: VSP
- Update Transformers to include new data (entity id's, breadcrumbs, etc...) (#5986) - Owner: VSP 

CMS epic used to track:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/948

**Comment by meganhkelley** [comment]
diagrams from superteam (likely out of date now) https://app.lucidchart.com/documents/edit/d413a48c-02ae-483e-8c44-812dedb0de76/0_0?shared=true#?folder_id=home&browser=icon

**Comment by meganhkelley** [comment]
No longer relevant due to pivot away from CMS Export documented here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/20165
