### ISSUE TITLE
BQ - Standard Forms Engagement - 2019 Data Removal 

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#59904]
## Issue Description
We need to re-create the BQ - Standard Forms Engagement removing 2019 and re-running for all other years so the backfill for the most recent 2 dashboards is updated.  Have tried to run several times in Domo and keeps failing due to size.  Need to determine how to make the update/removal to the existing dataset so that it will still auto update each week.

---
## Tasks
- [x] remove 2019 from datasert
- [ ] re-run 2020-2023 so up to date including new dashboards 

## Acceptance Criteria
- [ ] Dataset has been updated and the weekly updates are configured going foward.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelle-dooley** [comment]
Spring update:  Data updates still in process due to size.  This will continue into and be completed as part of next sprint.

**Comment by michelle-dooley** [comment]
@dorseypa1 - remaining steps/updates needed to complete...

- Complete 2021 and as much of 2020 as possible before Sunday (6/25)
- Change Domo query back for weekly update before Sunday (Sunday update, Append new week)
- Fix ETL for update to run [Output] - Standard KPI Forms by Status 
- Fix ETL for update to run [Output] Standardized Forms - Previous Page
- Finish loading any remaining 2020 data after weekly update
- Check dashboard to make sure all dates are updates as expcted.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/93597659/5dc2c103-19ef-4bd8-affa-22b4ef60f97c)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/93597659/d618ac72-b873-4319-b724-a9c5f93afa48)

**Comment by dorseypa1** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/117392065/1b57bfa0-96b5-4140-a3bb-84475441ffec)

**Comment by dorseypa1** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/117392065/22f4afa9-8f5b-4e24-adc2-d13cf124ac78)

**Comment by michelle-dooley** [comment]
2019 has been removed.  Need to do additional QA as the dataset size has doubled from 245M in April to 551M in June after removing 2019.  Original dataset had 20M records from 2020 and now we have 110M.  What changed?  I will create a new ticket for that work.
