### ISSUE TITLE
All VA Dashboard - Add New User Data

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#59911]
## Issue Description
We need to update and/or create a new dataset for the [All VAgov Dashboard](https://va-gov.domo.com/page/1030131175) that contains "New User" data.  As part of the [OCTO updates request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59038) we would like to add a card similar to the one on the Forms dashboard (we cannot use that dataset though bc it only included forms part of Standardized Forms Dashboard, not all forms).  

![image.png](https://images.zenhubusercontent.com/618144c8b17b33313a8c0cbe/53586bc7-df3c-4032-b979-d5e60324277d)

---
## Tasks
- [x] Add newVisits to BQ dataset pull in Domo so we can break out new users from total (logged in) users.
- [x] or create a net new dataset with new vs returning user metrics (if new dataset make sure the new + returning = total logged in from current dataset used in dashboard 1.59M for May
- [x] QA
## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by dorseypa1** [comment]
The new user column has been added into the 'BQ Logged in Compare' Domo dataset
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/117392065/abb315c3-23f8-437e-8fa0-167f597b1beb)

**Comment by dorseypa1** [comment]
Here is an image of the logged_in_new_user column in Domo
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/117392065/6b1d12cd-a712-462b-9579-4f808ed85f42)
