### ISSUE TITLE
Profile | Direct Deposit EVSS to Lighthouse | Create GA dashboard using #54893

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#59910]
## Issue Description
Using the work completed in #54893 we need to create a GA dashboard to check out the new events 

## Tasks 
- [x] travis to setup a call w adam to work on this 

## Acceptance Criteria 
- [x] new dashboard in GA 
     - [x] [staging](https://analytics.google.com/analytics/web/#/dashboard/DRqBrmiyTD6l8L75rei0fw/a50123418w178298118p176884211/)
     - [x] [production](https://analytics.google.com/analytics/web/#/dashboard/DRqBrmiyTD6l8L75rei0fw/a50123418w177519031p176188361/)
