### ISSUE TITLE
FE | Profile | Notification Settings | Consume Default Send | Feature Toggles 

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#59915]
## Background
In order to add email as a channel we have a series of tickets to complete, the first step is having a way to consume the default send data that's in the API and display that on the front end. 

see epic: 
- #59043 

## Tasks
- [x] Feature toggle added
- [x] Create preliminary checkbox UI components for use to consume default send and support email channel.
- [x] Checkboxes are displayed in staging when feature toggle is turned on.
- [x] Verify that radio buttons retain existing functionality with toggle turned off.
- [x] Basic unit / e2e tests added for 
- [x] Notify PM if this needs to be deployed to Staging behind feature flag
  

## Acceptance Criteria
- [x] Toggle present on staging
- [x] Checkboxes appear in staging behind toggle
- [x] Radio buttons retain functionality with toggle turned off
- [x] Confirm PM has opened a new ticket to deploy changes to Production using feature flag, if needed

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)?
- How can this work be validated?
- What updates need to be made (e.g. product outline, use cases, contact center guide)

**Comment by adamwhitlock1** [comment]
@mtcA6 Still working on this and prepping it for PR. Probably will have 1pt of work that rolls into the next sprint, unless I get it reviewed quickly.

**Comment by adamwhitlock1** [comment]
Was able to get this merged an deployed on staging.

@mtcA6 we can validate now on staging. I turned it on for `vets.gov.user+202@gmail.com`, so you should be able to see the checkboxes on that user, and any other user should be able to see and use the old radio buttons as if nothing has changed.

I even wired up the checkboxes to work for text notifications, so for user 202 you can even use them and they _should_ work (even though this wasn't technically part of this task)

**Comment by mtcA6** [comment]
Looks great! Feeling like i should probably comment on #59940 instead of this one, but I'll post it here and we can move it if that makes more sense. 

Noticing some spacing stuff that looks a bit odd.

**Mock:** 

> ![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/d5a8d665-889d-498f-8998-3ef1074bcea0)

**Versus Staging UI (using the user recommended):**

> ![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/dc97e657-23c8-438a-89b9-f1eec7c80e36)


The helper text isn't showing for RX prescriptions. Did we create a regression issue here potentially? 

In this story:
- #60063 

we said that the UI was updated but the mock-up wasn't. But now it looks like the UI is missing the helper text.

**Comment by mtcA6** [comment]
All that said, I feel like the toggle ticket is ready to close and we can continue w/the meat and potatoes ticket :)

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/238b4105-8c2e-46d6-ab8c-46d1f4a9cd5c)

**Comment by adamwhitlock1** [comment]
That helper text is conditional, and is based on what facilities the user has as their 'preferred facilities'. From what I can tell, the conditions aren't met to show that text for user 202, but I will double check some of the other test users and make sure I didn't break anything.

I definitely will go through the spacing in the upcoming tickets and make sure we are matching the sketch files.

**Comment by adamwhitlock1** [comment]
@mtcA6 I added the user `vets.gov.user+41@gmail.com` to the feature toggles for this, and they have the facilities in their user info so that helper text would be shown, so you can check that user out on staging and see that the text is present.

**Comment by adamwhitlock1** [comment]
Going to close this now though.

**Comment by andaleliz** [comment]
Hey @adamwhitlock1 this is great! Woot woot! I saw your comment:

>I definitely will go through the spacing in the upcoming tickets and make sure we are matching the sketch files.

Spacing is always such a hard thing in Sketch, because some of the design system components have built in margin that is supposed to align w/ how the CSS renders online.  I generally try not to design anything that will require any sort of custom CSS or spacing; I actually normally refer to staging and try to make my spacing line up with the margins I see in the CSS.

This particular situation _does_ look like it might need an increase in spacing between the two, only because the input + the link are both tap targets and they're really close together. It's weird that the input doesn't have a nice bottom margin baked in. But typically, know that I'm not trying to be prescriptive with spacing :) 

Maybe we should sync on a better way to make this all line up so it's easy for all of us?

CC @pamela-drouin just fyi

**Comment by andaleliz** [comment]
@adamwhitlock1 actually, I spoke to soon - I noticed we lost the dark green border on the left side when an update is saved, and the update saved banner is persisting, even when another one gets updated (we currently only show one at a time). 

Perhaps that's planned for a separate ticket, but wanted to let you know.

<img width="701" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/55992116/9959aa09-14a8-497e-992a-3164dde91324">

Side note: when MHV launches, we will also have a "notify by email" option for appointment reminders. I don't see that among all the other MHV notifications with `vets.gov.user+41@gmail.com` but I think that's a BE thing vs FE thing.

**Comment by mtcA6** [comment]
@andaleliz moved that comment to: 
- #59940

**Comment by adamwhitlock1** [comment]
@andaleliz great point on the styling of the success messages. I will make sure to address that as I build it out further.

There was a lot of custom styling with the old radio buttons (basically it was all custom), and in fact they didn't even use the design system component for the radio buttons at all! So now we are using the official `va-checkbox` component and will be attempting to remove whatever super custom styling was present with the old solution. 

That being said, I am sure there will be spacing adjustments that need to be made that fall within the styling utilities that we are using everywhere else, so I will be able to tweak lots of things to get this where it needs to be eventually.

As far as the email as a channel goes, that is hidden behind another feature toggle, and spoiler alert, that is already supported in this current work. It is just hidden for now as I tweak the first round of implementation. Stay tuned! 😸

**Comment by mtcA6** [comment]
@adamwhitlock1 for the release plan(s) I need to add in the toggle names, could you confirm what those are? 

I found this one but what's the other one? 

<html>
<body>


Conditional | profile_use_notification_settings_checkboxes | Use checkboxes for Notification Settings in Profile - Default Send and Email Channel | Actors
-- | -- | -- | --


</body>
</html>
