### ISSUE TITLE
Update and Test debts-api module

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#59919]
## Issue Description
_A few sprints ago we duplicated the FSR workflow inside the debts-api module with the intention of migrating all FSR endpoints and functionality over to this module. Since the initial release of the module code, changes have been made to the original code that need to be copied over. Once the module has been brought up to date it should be manually tested from the front end in a staging env._

---
## Tasks
- [ ] _Bring debts-api files up to date with primary app counterparts_
- [ ] _Add a feature flipper to point the front end at either debts-api module routes or regular routes_
- [ ] _test FSR functionality in staging env_
## Acceptance Criteria
- [ ] _The debts-api module is up to date and tested_
---

**Comment by HeatherRienks** [comment]
Let's add to Sprint 103; better to complete sooner rather than later.

**Comment by HeatherRienks** [comment]
@kjsuarez interested in taking this on in S104

cc: @Tom-Davis

**Comment by kjsuarez** [comment]
Branch: 59919-update-debts-api-module
