### ISSUE TITLE
Content support on updates to "happy path" for usability testing

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#59927]
## Issue Description
Christina shared 3 updated confirmation screens in CodePen for the pre-check-in and check-in flows. We're reviewing and providing content feedback ahead of usability testing. At this time, they're only testing the happy path.

Pre-check-in
[Contact info up-to-date](https://codepen.io/team/va-cie/live/poxNzgv)
[Confirmed appointment](https://codepen.io/team/va-cie/live/yLRVBJY)

Check-in
[You're checked in](https://codepen.io/team/va-cie/live/gOBgrGB)

---
## Tasks
- [x] Review 3 screens in CodePen
- [x] Provide suggested updates to checkin team

## Acceptance Criteria
- [x] Feedback provided to checkin team

**Comment by laurwill** [comment]
Hi @cgednalske @benbrasso-agile6 @kellysmith1008 ,
Christina shared the 3 updated confirmation screens, and the updates to the structure look great! Looking forward to see how these test. 

We have some additional suggestions on these 3 screens — I chatted with Christina and she let us know that larger changes are probably not possible now. But we wanted to document these here, and you can see what you're able to implement.

For both pre-check-in screens in the happy path, we suggest removing all 3 accordion Q&As:
- "How can I update my info" isn't needed here, since their info is already up to date in happy path
- "Why do I need to make sure my info is up to date" — they already reviewed their info, and it seems clear enough why a health system would need current info
- "What if I have questions about my appointments" is covered below in the Need help? section, so this is duplicate content

I chatted with Christina about header hierarchy around these accordions — are these nested under the "Take other steps" H2? Suggest making sure these scan correctly for screen readers in CodePen, if this testing will involve assistive tech. cc @sara-amanda 

And here are suggestions for the "Take other steps" section:
- Suggest changing this header to "Manage appointments"
- Suggest taking the "Find out how to check in" link out of this section. We could move it into the intro after "When it's time to check in, we'll send you a text," so it will appear in context. Or we could remove it altogether, since the check-in process should be clear in the UI. 
- We also considered if the "schedule appointments" link might work better in the Upcoming appointments section instead of on this confirmation page. That might be too radical for this round, but wanted to note that here!

Here's what the updated section could look like:
**Manage appointments**
Review all your upcoming appointments. You can also confirm or check in for other appointments if it's time to do so.
Go back to your appointments list [link]

You can schedule a new appointment in the VA appointments tool.
Learn how to schedule appointments [link]

**Comment by cgednalske** [comment]
@laurwill thank you for documenting all of this 🎉  We've changed the "Take other steps manage appointments..." heading to "Manage appointments" and have the other recommended changes on our radar for continued work outside of research. 👍 

I see Sara is out, but I'll go to Angela's internal office hours tomorrow and ask her to check on the possible accordion issue on our prototype.

**Comment by benbrasso-agile6** [comment]
Sorry, I meant to respond earlier. @laurwill thanks for all the great feedback. We'll get things worked in.

**Comment by RLHecht** [comment]
Looks like this work is complete. Going to close but please reopen if you need more from our team.
