### ISSUE TITLE
[Discovery] 10-10EZ - Print/Save: Technical discovery on an accessible way to allow applicants to download/print their application input

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#59947]
## Background
There have been a few studies in the last year where Veterans have mentioned they would like to have a way to print or save their application input after submitting it online.

Current state:
Today, we allow for the print/save option for the Confirmation page only.
The applicant could print the Review Page with all the accordions expanded to show their information, but that could be long and cumbersome.  

Target state:
Allow the applicant to print/save a copy of their application input after submission that is easily readable and accessible for those using assistive technology or have cognitive constraints

## Tasks
- [x] Research potential options for an applicant to print and/or save their application input for later reference
- [x] Consider technical feasibility of the options, including effort and the need for external resources (3rd party applications like Adobe for PDFs)
- [x] Comment in this ticket with any thoughts or questions that can be considered for this enhancement

## Acceptance Criteria
- Ideas with some pros/cons will be shared on potential options to provide applicants a way to print/save their application input after submission

**Comment by jadon1979** [comment]
Library details: https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/platform/pdf#usage
