### ISSUE TITLE
FE | Profile | Notification Settings | Consume Default Send | transfer from radio button to check-box (get the meat and potatoes out there!)

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#59940]
## Background
We've now gone through the Design Intent and want to use the [sketch files created](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-notification-preferences.md#draft-test-cases-to-account-for-when-we-add-email-as-a-channel) to shift from using radio buttons to check boxes. 

**Current radio buttons**
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/dad92e79-4f5e-4b7d-aea2-6ff4d7247106)

**checkboxes** 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/d2c64c8c-d560-4aaf-a1f6-4b6ed706cccb)

We'll put this behind the feature toggle we created in #59915 

## Ojo 👀
Midpoint review feedback could be important to incorporate here. 
[Midpoint Review - Accessibility Feedback - Authenticated Experience, Profile, Notification Settings - Default Send Functionality #60838](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60838)

## Tasks
- [x] Checkboxes present and functioning for api calls
- [x] Success, failure, and saving messages present
- [x] Styling for messages consistent with designs (padding, margins, and left border)
- [x] Styling for Checkbox, Fieldset, and messages all use design system components and/or design system utility classes to achieve styling. Remove all reliance on custom scss classes and variable.
- [x] Any existing message is removed when a checkbox is clicked (previously saved/error messages would stick around before)
- [x] Checkboxes for entire item are disabled while saving is ongoing.
- [x] Conduct Unit tests 
- [x] Run E2E tests covering current code and regression
- [x] Notify PM if this needs to be deployed to Staging behind feature flag
  

## Acceptance Criteria
- [x] Complete all unit testing
- [x] End-to-end tests showing 0 violations
- [x] All axe checks pass
- [x] Notify Product Manager that the change is ready to be validated on Staging
- [ ] ~Incorporate any changes resulting from Staging review & re-test & have re-validated~
- [x] Confirm PM has opened a new ticket to deploy changes to Production using feature flag, if needed (**see** #61013)
- [x] We're able to consume the default send in the UI

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)?
- How can this work be validated?
- What updates need to be made (e.g. product outline, use cases, contact center guide)

## Linked tickets 
[Design | Profile | Notification Settings | Update Sketch files to account for all use cases to add email as a channel #58890](https://github.com/department-of-veterans-affairs/va.gov-team/issues/58890)

**Comment by mtcA6** [comment]
@adamwhitlock1  on our call earlier today, you mentioned needing to create some sort of compatibility layer? Could you elaborate on that a little?

**Comment by mtcA6** [comment]
moving the comment from #59915 so we can capture this here 

> @adamwhitlock1 actually, I spoke to soon - I noticed we lost the dark green border on the left side when an update is saved ([Sketch reference](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/v8VnxJQ)), and the update saved banner is persisting, even when another one gets updated (we currently only show one at a time).
> 
> Perhaps that's planned for a separate ticket, but wanted to let you know.
> 
> <img alt="image" width="701" src="https://user-images.githubusercontent.com/55992116/248054577-9959aa09-14a8-497e-992a-3164dde91324.png">
> Side note: when MHV launches, we will also have a "notify by email" option for appointment reminders. I don't see that among all the other MHV notifications with `vets.gov.user+41@gmail.com` but I think that's a BE thing vs FE thing.

**Comment by mtcA6** [comment]
@adamwhitlock1 i mentioned oyu on the midpoint review ticket, might be overkill so forgive me, but I've updated this ticket w/a new section: 
## Ojo 

I know things were easier to work through than you expected but that feedback made me pause since it sounded not super easy to incorporate.

**Comment by adamwhitlock1** [comment]
The changes around this work have been deployed to staging. @mtcA6 you can validate with the test user 202.

The things to check and validate are:
- [ ] alert for save now has green border
- [ ] only one alert is shown at a time and the prior alert disappears once a new save starts on a checkbox
- [ ] the styling of the alert is updated to use the correct icon, and padding/sizing is adjusted to match the design file

**Comment by adamwhitlock1** [comment]
For the extra items that you added around accessibility from the midpoint review, I would say that would be something to bring into the next tickets around this work, since that was out of scope for this issue specifically, and I couldn't fit it in.

The work that I see needing to be built out next for this feature is:

- Addressing the accessibility midpoint feedback
- Actually consuming the default send indicator now that the checkboxes are wired up correctly
- Working on the addition of email as a channel, and the related UI work that is needed for that
  - Building out the logic around when a mobile, email or both items are missing and displaying the alerts with contextual information around those pieces

**Comment by mtcA6** [comment]
> For the extra items that you added around accessibility from the midpoint review, I would say that would be something to bring into the next tickets around this work, since that was out of scope for this issue specifically, and I couldn't fit it in.


No worries that makes complete sense! I wasn't sure how far along in the process you were so I wanted to highlight it in case you were able to incorporate things!! 

I've incorporate this:
> - Addressing the accessibility midpoint feedback
> - Actually consuming the default send indicator now that the checkboxes are wired up correctly
> - Working on the addition of email as a channel, and the related UI work that is needed for that
>      - Building out the logic around when a mobile, email or both items are missing and displaying the alerts with contextual information around those pieces

Into the next ticket  [FE | Profile | Notification Settings | Default Send | bug fixing 🐜 / secondary implementation fixes / Testing coverage (cleaning and seasoning the meat and potatoes)#61013](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61013)

**Comment by mtcA6** [comment]
@adamwhitlock1 getting there! can you check the margin? padding? 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/ad06f07b-8eda-4f09-95ec-744729d2187b)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/d3aa76fc-ca2b-4856-80f5-e7d4eee53613)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/8390f461-a1b7-4846-8d56-e1915a23d198)


@andaleliz do you mind testing this as well? and checking if I missed anything else?

**Comment by adamwhitlock1** [comment]
@mtcA6 I worked mostly from this specs file here:

https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/p/20C1C6FB-C6A5-4D56-B9DE-1E0552C4FC15/canvas

You are correct about the font, it needs to be bolded in the alerts, and it is not, so I will work on fixing that within the next ticket.
