### ISSUE TITLE
[526 - Historical Claims] Finalize Input files

### ISSUE THREAD

**Issue by kylesoskin** [department-of-veterans-affairs/va.gov-team#59943]
## Value Statement

**_As a_** person working 526 historical claims
**_I want to_** ensure the input files with Veteran info is correct and in the correct format(s)
**_So that_** we can prevents/minimize errors and ensure addresses and claims are accurate as possible with the info we have

---
## Background Context
Time boxed (1-2 hours), request from David

## Out of scope
Additional work that may stem from going over the files. 

## Tasks
- [x] Meet w/ David
- [x] Review all files/payloads
- [x] Make tickets for any changes that need to occur

---
## Definition of Ready 
- [x] Meeting scheduled

## Definition of Done
- [x] Meeting has occurred
- [x] Next steps outlined (or files approved/rubber-stamped if no changes are needed/requested)

**Comment by kylesoskin** [comment]
Work from this meeting in this ticket: 

https://app.zenhub.com/workspaces/benefits-team-1-6138d7b57a2631001a4b7562/issues/gh/department-of-veterans-affairs/vets-website/24685
