### ISSUE TITLE
[BE] Replace Claim Number in Log with Last 4 Digits Only

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#59959]
## User Story
Because the travel claim number is considered PII, we have been asked to replace the claim number in the log with the last 4 digits only.

## Tasks
- [ ] [BE] **Replace Claim Number in Log with Last 4 Digits Only**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by loripusey** [comment]
@randomsync pulled these into the sprint based on their priority; If ticket won't be completed before you leave, please hand off to @brianseek 
cc: @anita-halici @benbrasso-agile6
