### ISSUE TITLE
Set up a Slack slash command for feedback

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#59954]
## Purpose
Continuation of work on: Set up the decided upon modes for marketing the portal in an ongoing way

[Prework
](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2637758599/Ongoing+Marketing+for+the+Portal)

## Tasks
- [x] Learn and [document](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2846786306/Continuous+feedback+portal+How+to+set+up+a+custom+slash+command+workflow+in+Slack) how to implement a Slash Command
- [x] Connect with a DSVA Slack admin to implement Slash Command
- [x] Team review of [documentation](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2846786306/Continuous+feedback+portal+How+to+set+up+a+custom+slash+command+workflow+in+Slack)
- [x] Delete earlier workflow instance in vfs-support channel

## Acceptance Criteria
- [x] Setup of Slash Command (at the capacity the settings allow us as of now) is complete

**Comment by gopixelsgo** [comment]
This ticket will carry over to the next sprint for continued work.

**Comment by gopixelsgo** [comment]
This ticket will roll over to next sprint for continuation of work.
