### ISSUE TITLE
[BE] Replace Claim Number Sent to VA Notify for the SMS Content with Last 4 Digits Only

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#59960]
## User Story
Because the travel claim number is considered PII, we have been asked to replace the claim number in the log with the last 4 digits only.

## Content
[Final content](https://dsva.slack.com/archives/C022AC2STBM/p1686312412625249?thread_ts=1686166186.403529&cid=C022AC2STBM)

This content appears in the [Business Intake Form ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55526#issuecomment-1583384167) to VA Notify

I'm assuming that the only change that is needed is to pass only the last 4 digits of the claim number

## Tasks
- [ ] [BE] **Replace Claim Number Sent to VA Notify for the SMS Content with Last 4 Digits Only**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by loripusey** [comment]
@randomsync  If ticket won't be completed before you leave, please hand off to @brianseek

**Comment by loripusey** [comment]
@lee-delarm6 are you going to be able to get this into production this week?
