### ISSUE TITLE
Medallia QDR Training

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/va.gov-team#59975]
## Issue Description
In order to assist in coverage, backup team members need to be trained on how to pull Medallia data from incoming Qualitative Data Requests.

---
## Tasks
- [x] Determine what team members need training
- [x] Schedule a training meeting
- [x] Write thorough supplemental training documentation
- [x] Administer training

## Acceptance Criteria
- [x] Did the training take place?
- [x] Has the documentation been created & shared?

**Comment by ianMcCullough-ob** [comment]
@ATMiddleton I created a ticket to track Medallia training for this sprint. I know @Kimberley2019 wanted to go through training as well. Is there anyone else who should attend?

**Comment by ATMiddleton** [comment]
Hi Ian,

Thanks!

I think just Kimberley and me for starters works.

Best regards,

Anita
Product Manager
305-522-2306

**Comment by ianMcCullough-ob** [comment]
[Documentation for tomorrow's training](https://vfs.atlassian.net/wiki/spaces/Contact/pages/2662924512/Medallia+-+Qualitative+Data+Request+Process)

**Comment by ianMcCullough-ob** [comment]
Training has taken place and the documentation has been updated to include steps on exporting full notes in SalesForce.
