### ISSUE TITLE
Page Feedback Mechanism Follow Up

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/va.gov-team#59974]
## Issue Description
Based on [ongoing research & discussions](https://docs.google.com/document/d/1667UmcucfcOvZMnapc-aT4J8KvKSaZa3OxQChNHFRRI/edit), further steps need to be taken to advance the creation of a site-wide page-specific feedback mechanism. Conversations with the team that oversees the Resources & Support article need to happen to discern the current operation and usage of their feedback mechanism.

---
## Tasks
- [x] Schedule a meeting with Danielle Thierry, Dave Conlon and appropriate CC Team members (Ian, Aubrey, Chante and Anita
- [x] Prepare an agenda for the above meeting
- [ ] Determine next steps based on the meeting

## Acceptance Criteria
- [x] Has the meeting taken place?
- [ ] Have the next steps been determined?

**Comment by Kimberley2019** [comment]
@aubreyarcangel will follow up.

**Comment by starlow00** [comment]
Still on hold, waiting to meet with Sarkis. Been working with him on the modal. Sending some of Ian's previous research over first... discovery call w/Sarkis re. the tech capabilities

Camille will reach out to Aubrey if there are questions.

**Comment by aubreyarcangel** [comment]
Sent documentation to @UXCamG to review and will be meeting with Sarkis next week to discuss.

**Comment by ATMiddleton** [comment]
@aubreyarcangel , @UXCamG will meet with Sarkis week of 8/2/23

**Comment by UXCamG** [comment]
@ATMiddleton I met with Ian to discuss what was previously researched for feedback mechanisms on VA support pages.  Ian gave insight on design systems, sketch designs that were previously used, and who may be a good resource to assist me with ideating on new design concepts for receiving feedback on VA.gov. My next steps are for @aubreyarcangel  and I to meet with Sarkis regarding Medallia's capabilities for a new design to receive feedback, to meet with Nicole Leonard to discuss her design ideas from previous research she conducted on feedback mechanisms, and to develop a clickable  prototype for user testing.

**Comment by UXCamG** [comment]
Week of 8/14  we followed up with ianMcCullough-ob  and jwoodman5  regarding where we left off in design research and product management for our feedback products.  We discovered we need to learn more about where we are from Chante and Sarkis to begin considering our next steps which is research planning planning for a moderated usability test. 

I created a brainstorm document to assist us during our exploration . 
 [https://jamboard.google.com/d/1dXlRa-x8lCjMzGFwQyNCU83_3UotWQ2HAzPqz_AhZXU/edit?usp=sharing](url)

**Comment by ATMiddleton** [comment]
Meeting scheduled 8/23 - will provide additional information at the conclusion.

**Comment by aubreyarcangel** [comment]
Camille and I met with Sarkis and was presented with two options:

1. Embed survey within VA.gov pages
2. Utilize exist radio buttons (Good/Bad) to trigger a Medallia modal survey

**Comment by ATMiddleton** [comment]
@UXCamG has created mock up for new modal for 2nd version.  Will present to VEO and begin research planning.  @aubreyarcangel will create continuation ticket.
