### ISSUE TITLE
QDR Template Update

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/va.gov-team#59976]
## Issue Description
Now that more users are requesting VA411 issues, clarity around how issues are categorized needs to be provided for the requestor. In addition, an expected date turn around needs to be added to the template so submitters know when to expect their data.

---
## Tasks
- [x] A link to VA411 issue categories and types is added to the template
- [x] An expected turnaround date has been added to the template

## Acceptance Criteria
- [x] Have the above additions been added to the template?
- [x] Has the template been tested?

**Comment by ianMcCullough-ob** [comment]
Updated issue template: https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=ianMcCullough-ob%2C+ATMiddleton&labels=VSP-contact-center%2Ccc-data-request&projects=&template=qualitative-data-request.yml&title=Qualitative+Data+Request

**Comment by ATMiddleton** [comment]
Tested and completed.
