### ISSUE TITLE
Identity Dashboard (FE) - Add Chakra UI to Identity Dashboard

### ISSUE THREAD

**Issue by acaruso-oddball** [department-of-veterans-affairs/va.gov-team#59982]
## Issue Description
Integrate use of Chakra UI into Identity Dashboard. 

## Tasks
- [x] Integrate use of Chakra UI into Identity Dashboard. 
- [x] Update styling to accommodate the change. 
- [x] Update tests to accommodate such change.

## Acceptance Criteria
- [x] Components can be written with use of Chakra UI
