### ISSUE TITLE
FE | Profile | Notification Settings | Editing as a Sub-Task | Implement Midpoint Review Feedback and Updated Alert "we don't have your contact information alert"

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#59987]
## Background 
As we progress through our "editing as a subtask" body of work, we've uncovered an alert that needed to be reworked given the new flow/feature. Using the design work from #59728 completed in sprint12 we need to update the alert.

The [sketch file ](https://sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/p/8F33D983-75FB-4317-9DAF-D8306F3966FB/canvas?annotation=c65ad1c1-750b-41f4-bbd8-cc92c7d0da8e)needed to update the alert. 

We've also received midpoint review feedback that we need to incorporate. 

### Blockers / midpoint review feedback tickets 
- [x] #59728
- [x] #61212 
- [x] #61214

## Documentation 

**59728 mocks** update CTA
[mobile ](https://sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/p/8F33D983-75FB-4317-9DAF-D8306F3966FB/canvas?annotation=c65ad1c1-750b-41f4-bbd8-cc92c7d0da8e) and [desktop](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/9P49mAx)

**61214 mocks** updated breadcrumb for edge case from our static page back to profile 
[Desktop](https://www.sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d/v/0qGRoj/a/ZOzGKLZ) and [mobile](https://www.sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d/a/yg23exo) mockups have been updated

**61212 mocks** updated "cancel" link and "save" button 
Updated [mobile mocks here](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/p/8F33D983-75FB-4317-9DAF-D8306F3966FB/canvas)

## Acceptance Criteria 

```[tasklist]
### AC
- [ ] all of the various feedback points have been updated in staging
- [ ] tests are passing
- [ ] we're ready for staging review
- [ ] modal added to edit flow on cancel
- [ ] breadcrumb added regular view and fallback view
- [ ] 'we don't have your contact info' alert updated
```

**Comment by adamwhitlock1** [comment]
@pamela-drouin and @andaleliz how much of a 'big deal' is having the cancel 'link' appear as a link vs a button. 

We have it as a button in the various profile pages, and because we are using the same shared component for this, the cancel button is kinda stuck as a button instead of a link at this point.

I think I can add some more code to trigger the button to conditionally look like a link (something like `cancelShownAsLink = true`) but semantically that feels a bit dirty, since it is still going to be a <button> element under the hood, and will just be styled like a link instead of a real link. Thoughts?

**Comment by andaleliz** [comment]
@adamwhitlock1 is the cancel "link" actually a `<button>` element that cancels the action _and_ redirects a person back to where they came from? If so, I think having it look like a button is OK, but we _might_ need to go back the more verbose label we had the first round ("cancel and go back to last page" or something like that).  I could check w/ accessibility folks about best practices.

>Unless I am missing it, I don't see anywhere in the design system when/how to choose between the two.
You're not missing it, I don't see it either.  

>when to use a button pair, vs when to use a button + link. 

From an accessibility perspective, anything that is an `<a>` element and takes.a user to a new page should always look like a link.  Buttons and links use different keyboard shortcuts, so it's more intuitive to practice material honesty and have thinks look like the thing they are.   But, this is an interesting scenario where we are (I think) using javascript to do a couple of things at once.

**Comment by andaleliz** [comment]
@adamwhitlock1 is the cancel "link" actually a `<button>` element that cancels the action _and_ redirects a person back to where they came from? If so, I think having it look like a button is OK, but we _might_ need to go back the more verbose label we had the first round ("cancel and go back to last page" or something like that).  I could check w/ accessibility folks about best practices.

@pamela-drouin to answer your questions:

>Unless I am missing it, I don't see anywhere in the design system when/how to choose between the two.

You're not missing it, I don't see it either.  

>when to use a button pair, vs when to use a button + link. 

From an accessibility perspective, anything that is an `<a>` element and takes.a user to a new page should always look like a link.  Buttons and links use different keyboard shortcuts, so it's more intuitive to practice material honesty and have thinks look like the thing they are.   But, this is an interesting scenario where we are (I think) using javascript to do a couple of things at once.

**Comment by adamwhitlock1** [comment]
Since the component itself stems from the original contact page implementation it is a <button> element, and we are hooking up custom logic to it.

> But, this is an interesting scenario where we are (I think) using javascript to do a couple of things at once.

^ This is probably the biggest thing that points me towards using a button and making it look like a button. If you hit cancel and have unsaved changes, you are presented with the 'are you sure you wanna cancel' modal, which you then have to interact with to cancel pending changes or return to the editing flow.

Its tough though because sometimes it acts like a link (if there are no unsaved changes) and sometimes it acts like a button... maybe we should use a _Linutton_ or a _Bunk_ 😉

**Comment by andaleliz** [comment]
I've asked a11y folks to weigh in on this via Slack ([convo here](https://dsva.slack.com/archives/C8E985R32/p1690990864183849))

**Comment by andaleliz** [comment]
@adamwhitlock1 they confirmed it should be a button; mock-ups for the editing as a sub-task flow have been updated [here](https://sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d).   

Note that the mock-ups linked in this ticket point to the notification settings use case example, which isn't the source of truth for that flow and won't be maintained.

**Comment by mtcA6** [comment]
This looks good, we've got a cancel button
