### ISSUE TITLE
Board Appeals | Triage research recordings that show slow loading times

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#59988]
## Value Statement
**_As a_** UX researcher on the Benefits team
**_I want to_** collect video clips of veterans experience of my-va loading
**_So that_** the VA tech lead knows the impact of loading delays on veterans

---
## Background Context
Sade requested to triage research recordings where participants lose confidence due to loading time to share with Steve Albers

Link to thread: https://dsva.slack.com/archives/C5AGLBNRK/p1686151266309319

## Acceptance Criteria
- [ ] Video clips of veterans experience with va.gov loading uploaded to Sharepoint

## Tasks
- [ ] Search and clip research recordings for where Veterans are experience load time difficulties
- [ ] Upload into VA Sharepoint
- [ ] Share with Steve Albers

## Definition of Ready
- [ ] Interviews have concluded
- [ ] Research recordings have been downloaded

## Definition of Done
- [ ] Research clips uploaded to Sharepoint and shared with Steve Albers
