### ISSUE TITLE
[bug spike] Investigate Sentry errors that can be fixed

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#59990]
## Value Statement

**_As a_** developer
**_I want to_** review Sentry errors for our 3 appeals forms (HLR, NOD & SC)
**_So that_** investigate issues that are potentially fixable

---
## Background Context

There are numerous Sentry errors that are tracked but not investigated. Some events appear to be JavaScript errors which could be fixed.

## Out of scope

Actual bug fixing.

## Tasks
- [ ] Compile a list of potentially fixable Sentry issues
- [ ] Investigate and open tickets for these issues
- [ ] Add account UUID and/or SiP ID to Sentry events, as needed
---

## Definition of Ready 
- [ ] Have access to [appeals dashboards in Sentry](http://sentry.vfs.va.gov/organizations/vsp/dashboard/10/)
- [ ] Know to ignore load, fetch, save, connection and network errors

## Definition of Done
- [ ] All tasks complete
- [ ] Tickets created, assigned and estimated

## Additional Info

Findings:

### NOD

- [x] Filter error; `Cannot read properties of undefined (reading 'filter')` & `undefined is not an object (evaluating 'e.contestableIssues.filter') TypeError`
- [x] `undefined is not an object (evaluating 'o.disagreementOptions') TypeError`
- [x] chapterKey: `Cannot read properties of undefined (reading 'chapterKey') TypeError` & `undefined is not an object (evaluating 'g.chapterKey') TypeError`
- [ ] `undefined is not an object (evaluating 'a.isProxied')`
- [x] `e.addError is not a function TypeError (multiple pages)`
- [x] `addError("Please add a phone number to your profile")`
- [ ] `SchemaError: Expected `schema` to be an object or boolean (area of disagreement)`
- [ ] `n.matches is not a function - "/node_modules/react-focus-on/dist/es2015/index.js"`
- [x] ~[Unprocessible error](http://sentry.vfs.va.gov/organizations/vsp/discover/platform-web:e6e54c215201469aadd2bb2058332600/?environment=production&field=message&name=Notice+of+Disagreement&project=4&query=url%3Ahttps%3A%2F%2Fwww.va.gov%2Fdecision-reviews%2Fboard-appeal%2Frequest-board-appeal-form-10182%2F%2A+level%3Aerror+message%3A%22vets_server_error%3A+Unprocessable+Entity+Error+%2Fgenerated%2F10182-board-appeal.entry.js+XMLHttpRequest.%3Canonymous%3E+XMLHttpRequest.%3Canonymous%3E%28generated%2F10182-board-appeal.entry%29%22&sort=-message&statsPeriod=90d&widths=-1) - Shared with Kyle; this appears to be an issue with submitting international addresses - we need to set the `zipCode5` value to `00000` in these cases ([#60008](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60008))~ To fix with backend changes

### HLR

- [ ] `e.setWizardStatus is not a function TypeError`
- [ ] `Expected `schema` to be an object or boolean SchemaError` - related to area of disagreement, no SiP data available
- [x] chapterKey: `Cannot read properties of undefined (reading 'chapterKey') TypeError` & `undefined is not an object (evaluating 'g.chapterKey') TypeError`
- [ ] `undefined is not an object (evaluating 'a.isProxied') TypeError`
- [x] `e.addError is not a function. (In 'e.addError("Please add an email address to your profile")', 'e.addError' is undefined) TypeError`
- [ ] `NotFoundError: Node.removeChild: The node to be removed is not a child of this node` - always happens on HLR start page (deprecated wizard)

### Other

- [ ] `Invalid regular expression: unrecognized character after (? SyntaxError` - possibly only an error in older versions of Safari (v10) - Opened a [Design System ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56607)
- [ ] `ReferenceError: Can't find variable: SymBrowser_ModifyAnchorTagWithTarget` - HLR start page in AppleMail browser?
- [ ] `Cannot read property 'query' of undefined TypeError`
- [ ] `TypeError: Argument 1 ('element') to Window.getComputedStyle must be an instance of Element` - mobile Safari?

**Comment by Mottie** [comment]
## NOD
- [ ] Filter error; `Cannot read properties of undefined (reading 'filter')` & `undefined is not an object (evaluating 'e.contestableIssues.filter') TypeError`
- [ ] `undefined is not an object (evaluating 'o.disagreementOptions') TypeError`
- [ ] chapterKey: `Cannot read properties of undefined (reading 'chapterKey') TypeError` & `undefined is not an object (evaluating 'g.chapterKey') TypeError`
- [ ] `undefined is not an object (evaluating 'a.isProxied')`
- [ ] `e.addError is not a function TypeError (multiple pages)`
- [ ] `addError("Please add a phone number to your profile")`
- [ ] `SchemaError: Expected `schema` to be an object or boolean (area of disagreement)`
- [ ] `n.matches is not a function - "/node_modules/react-focus-on/dist/es2015/index.js"`

## HLR

- [ ] `e.setWizardStatus is not a function TypeError`
- [ ] `Expected `schema` to be an object or boolean SchemaError` - related to area of disagreement, no SiP data available
- [ ] chapterKey: `Cannot read properties of undefined (reading 'chapterKey') TypeError` & `undefined is not an object (evaluating 'g.chapterKey') TypeError`
- [ ] `undefined is not an object (evaluating 'a.isProxied') TypeError`
- [ ] `e.addError is not a function. (In 'e.addError("Please add an email address to your profile")', 'e.addError' is undefined) TypeError`
- [ ] `NotFoundError: Node.removeChild: The node to be removed is not a child of this node` - always happens on HLR start page (deprecated wizard)

## Other

- [ ] `Invalid regular expression: unrecognized character after (? SyntaxError` - possibly only an error in older versions of Safari (v10) - Opened a [Design System ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56607)
- [ ] `ReferenceError: Can't find variable: SymBrowser_ModifyAnchorTagWithTarget` - HLR start page in AppleMail browser?
- [ ] `Cannot read property 'query' of undefined TypeError`
- [ ] `TypeError: Argument 1 ('element') to Window.getComputedStyle must be an instance of Element` - mobile Safari?

**Comment by rocio-desantiago** [comment]
Separated into tickets? Is 3 okay?
[HLR bug fix](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59996)
[NOD bug fix](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59997)
[Decision Reviews Browser bugs](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59998)
