### ISSUE TITLE
Higher Level Review | Bug fix

### ISSUE THREAD

**Issue by rocio-desantiago** [department-of-veterans-affairs/va.gov-team#59996]
## Value Statement

**_As a_** developer
**_I want to_** fix Sentry errors related to the Higher Level Review appeals form
**_So that_** users don't have trouble submitting a Higher Level Review request.

---
## Background Context

** Fixed **
- [x] [97 total, 57 unique/90 days](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?display=top5&field=title&field=count%28%29&field=count_unique%28user%29&field=project&name=Errors+by+Title&query=event.type%3Aerror+setWizardStatus&sort=-count&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1) `e.setWizardStatus is not a function TypeError`
- [x] [256 total, 88 unique/90 days](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?display=top5&field=title&field=count%28%29&field=count_unique%28user%29&field=project&name=Errors+by+Title&query=event.type%3Aerror+chapterKey&sort=-count&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1) chapterKey: `Cannot read properties of undefined (reading 'chapterKey') TypeError` & `undefined is not an object (evaluating 'g.chapterKey') TypeError`
- [x] [20 total, 4 unique/90 days](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?display=top5&field=title&field=count%28%29&field=count_unique%28user%29&field=project&name=Errors+by+Title&query=event.type%3Aerror+addError&sort=-count&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1) `e.addError is not a function. (In 'e.addError("Please add an email address to your profile")', 'e.addError' is undefined) TypeError` (duplicate from NOD ticket)

** Re-assigned to platform **
- [x] ~[15k total, 3.3k unique/90 days](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?display=top5&field=title&field=count%28%29&field=count_unique%28user%29&field=project&name=Errors+by+Title&query=event.type%3Aerror+removeChild&sort=-count&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1) `NotFoundError: Node.removeChild: The node to be removed is not a child of this node` - always happens on HLR start page (deprecated wizard)~ Re-assigned to platform in #60670
- [x] ~[86 total, 31 unique/90 days](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?display=top5&field=title&field=count%28%29&field=count_unique%28user%29&field=project&name=Errors+by+Title&query=event.type%3Aerror+schema+object+or+boolean&sort=-count&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1) `Expected 'schema' to be an object or boolean SchemaError` - related to area of disagreement, no SiP data available (duplicate from NOD ticket)~ Re-assigned to platform in #60475
- [x] ~[228k total, 84.2k unique/90 days](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?display=top5&field=title&field=count%28%29&field=count_unique%28user%29&field=project&name=Errors+by+Title&query=event.type%3Aerror+isProxied&sort=-count&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1) `undefined is not an object (evaluating 'a.isProxied') TypeError` (duplicate from NOD ticket)~ Re-assigned to platform in #60474

## Tasks
- [ ] Define steps to fix bug
---

## Definition of Ready 
- [ ] Monitor [appeals dashboards in Sentry](http://sentry.vfs.va.gov/organizations/vsp/dashboard/10/)

## Definition of Done
- [ ] All tasks complete
