### ISSUE TITLE
Notice of Disagreement | Filter error [Bug fix]

### ISSUE THREAD

**Issue by rocio-desantiago** [department-of-veterans-affairs/va.gov-team#59997]
## Value Statement

**_As a_** developer
**_I want to_** fix the filter error showing on the contestable issues page
**_So that_** users don't get stuck on this part of the application

---
## NOD
- [ ] Filter error; `Cannot read properties of undefined (reading 'filter')` & `undefined is not an object (evaluating 'e.contestableIssues.filter') TypeError`
- [ ] `undefined is not an object (evaluating 'o.disagreementOptions') TypeError`
- [ ] chapterKey: `Cannot read properties of undefined (reading 'chapterKey') TypeError` & `undefined is not an object (evaluating 'g.chapterKey') TypeError`
- [ ] `undefined is not an object (evaluating 'a.isProxied')`
- [ ] `e.addError is not a function TypeError (multiple pages)`
- [ ] `addError("Please add a phone number to your profile")`
- [ ] `SchemaError: Expected `schema` to be an object or boolean (area of disagreement)`
- [ ] `n.matches is not a function - "/node_modules/react-focus-on/dist/es2015/index.js"`

## Tasks
- [ ] TBD
---

## Definition of Ready 
- [ ] Monitor [appeals dashboards in Sentry](http://sentry.vfs.va.gov/organizations/vsp/dashboard/10/)
- [ ] 

## Definition of Done
- [ ] All tasks complete

**Comment by HeatherWidmont** [comment]
@saderagsdale are we good to close this?

**Comment by saderagsdale** [comment]
@Mottie Howdy - if all the errors are fixed or handed to the platform team then I think this is done. Can you post a link to the platform ticket we submitted for these?

**Comment by Mottie** [comment]
- [Platform ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60487)
- [DSVA slack request](https://dsva.slack.com/archives/CBU0KDSB1/p1686946267419029)
