### ISSUE TITLE
[platform] DR | Browser bugs (assigned to Platform)

### ISSUE THREAD

**Issue by rocio-desantiago** [department-of-veterans-affairs/va.gov-team#59998]
## Value Statement

**_As a_** developer
**_I want to_** fix the browser errors
**_So that_** users can fill out the form from their preferred browser

---
## Background Context

- [ ] [7.3k total, 1.3k unique/90 days](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?display=top5&field=title&field=count%28%29&field=count_unique%28user%29&field=project&name=Errors+by+Title&query=event.type%3Aerror+Invalid+regular+expression&sort=-count&statsPeriod=24h&widths=-1&widths=-1&widths=-1&widths=-1) `Invalid regular expression: unrecognized character after (? SyntaxError` - possibly only an error in older versions of Safari (v10) - Opened a [Design System ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1834)
- [ ] [2.9k total, 383 unique/90 days](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?display=top5&field=title&field=count%28%29&field=count_unique%28user%29&field=project&name=Errors+by+Title&query=event.type%3Aerror+SymBrowser_ModifyAnchorTagWithTarget&sort=-count&statsPeriod=24h&widths=-1&widths=-1&widths=-1&widths=-1) `ReferenceError: Can't find variable: SymBrowser_ModifyAnchorTagWithTarget` - HLR start page in AppleMail browser?
- [ ] [676 total, 141 unique/90 days](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?display=top5&field=title&field=count%28%29&field=count_unique%28user%29&field=project&name=Errors+by+Title&query=event.type%3Aerror+%27query%27&sort=-count&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1) `Cannot read property 'query' of undefined TypeError`
- [ ] [1.1k total, 455 unique/90 days](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?display=top5&field=title&field=count%28%29&field=count_unique%28user%29&field=project&name=Errors+by+Title&query=event.type%3Aerror+Window.getComputedStyle&sort=-count&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1) `TypeError: Argument 1 ('element') to Window.getComputedStyle must be an instance of Element` - mobile Safari?

## Tasks
- [ ] TBD
---

## Definition of Ready 
- [ ] Monitor [appeals dashboards in Sentry](http://sentry.vfs.va.gov/organizations/vsp/dashboard/10/)

## Definition of Done
- [ ] All tasks complete

**Comment by saderagsdale** [comment]
@rocio-desantiago add a link to the platform slack handoff thread.

**Comment by saderagsdale** [comment]
Sent the final list to Bill Chapman, Dave Conlon, and Zach G. 

Decisions made:

- Their recommendation was to use the normal platform support channels and tag them. 
- They did not want to alternate the process for providing updates on these bugs. 
- They asked to be added to the platform support ticket.
- I acknowledged that the tam has sent numerous requests for these bugs to be investigated to platform support, and that revisiting support threads async to find updates was not an effective approach based on previous attempts due to team capacity and lack of a scalable process from the platform team.
- [Link](https://dsva.slack.com/archives/CBU0KDSB1/p1700448514126239) to the final platform support thread with documentation we submitted.
