### ISSUE TITLE
[bug spike] NOD Unprocessable Entity Investigation

### ISSUE THREAD

**Issue by kylesoskin** [department-of-veterans-affairs/va.gov-team#60008]
## Value Statement

**_As a_** veteran submitting a NOD
**_I want to_** have the submission go through
**_So that_** it gets to the VA

---
## Background Context
Time boxed spike (1-2 hours). Look into why the submission was rejected. Looks to be a missing address key issue.

## Tasks
- [x] Investigate why the submissions is erroring
- [x] Make tickets to fix it if a large effort (or fix if small effort)

---
## Definition of Ready 
- [x] Gather infomation

## Definition of Done
- [x] We know the cause of the error
- [x] We've defined a solution if needed, and assigned it to the appropriate party
- [ ] We've asked the CC team to reach out and ask the Veteran to resubmit

## Additional info/Context
https://vagov.ddog-gov.com/logs?query=%40remote_ip.geoip.ipAddress%3A94.204.229.196%20&cols=host%2Cservice%2C%40payload.error_message&event=AgAAAYiLjDZ1IlM0RgAAAAAAAAAYAAAAAEFZaUxqRHAxQUFCTjlvSm1TT3FYVUFBMwAAACQAAAAAMDE4ODhjMmEtMTIyMS00MzdlLTk3ZTUtNmQ2NTVmOGRiMTU4&index=&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1685954366160&to_ts=1685981677390&live=false

https://vagov.ddog-gov.com/logs?query=%40remote_ip.geoip.ipAddress%3A94.204.229.196%20&cols=host%2Cservice%2C%40payload.error_message&event=AgAAAYiLjDZ1IlM0RwAAAAAAAAAYAAAAAEFZaUxqRHAxQUFCTjlvSm1TT3FYVUFBNAAAACQAAAAAMDE4ODhjMmEtMTIyMS00MzdlLTk3ZTUtNmQ2NTVmOGRiMTU4&index=&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1685954366160&to_ts=1685981677390&live=false

http://sentry.vfs.va.gov/organizations/vsp/issues/198211/?project=3&query=NoticeOfDisagreementsController&statsPeriod=90d

**Comment by saderagsdale** [comment]
@kylesoskin is the initial time boxed spike completed?

**Comment by kylesoskin** [comment]
This is the one with no zip code provided, and an address from UAE (Dubai). @Mottie added frontend zip validation and error handling that should take care of this and we have not seen it since, so I think this is OK to close. I will find the user in the DB and see if they were able to successfully submit or not yet. If not, I will figure out what our process is to get the users info to the call center to ask to retry.
