### ISSUE TITLE
SC | Refactor code with va-link

### ISSUE THREAD

**Issue by rocio-desantiago** [department-of-veterans-affairs/va.gov-team#60030]
## Value Statement
**_As a_** Veteran with accessibility needs that is filing a supplemental claim
**_I want to_** file using the latest enhancements to the frontend experience
**_So that_** I can benefit from accessibility and other design updates. 

---
## Background Context
This form uses outdated components. The VA design system has updated components that we can use for the form. 

## Acceptance Criteria
- [ ] All tasks complete
- [ ] All tests passing
- [ ] User can submit a Supplemental Claim with no errors related to component use

## Designs and Build Notes
- Download link to `va-link`

## Out of scope
- Any others components (design system, etc) that use the element

## Tasks
- [ ] Replace `DownloadLink` with `va-link`
- [ ] Unit tests updated
- [ ] e2e tests updated

## Definition of Ready 

- [ ] We know which elements to update, and which to leave out of scope

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design
