### ISSUE TITLE
[bug] Supplemental Claims | Fix submission of not matching date format

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#60051]
## Value Statement

**_As a_** developer
**_I want to_** fix not matching date formats submitted to Lighthouse
**_So that_** we can prevent the error from occurring & preventing submission.

---
## Background Context

Found in a [Sentry error](http://sentry.vfs.va.gov/organizations/vsp/issues/198994/?project=3&query=user.id%3A8d58b270efec489f8c7920314bca1ce0&statsPeriod=14d), a non-matching date format is blocking submission of the form - the date does not include leading zeros, e.g. `2023-6-9`

## Acceptance Criteria
- [ ] Date format is YYYY-MM-DD

## Tasks
- [ ] Update submission transformer to ensure that dates always follow the "YYYY-MM-DD" format
- [ ] Add unit tests
- [ ] Check e2e tests

---
## Definition of Ready 
- [ ] Review sentry error
- [ ] We know the cause of the error

## Definition of Done
- [ ] Passed testing
- [ ] Data appears as expected on backend

## More detailed info

```
detail: '2023-01-1 ' did not match the defined format, 
meta: { format: date }, 
source: {
  pointer: /data/attributes/evidenceSubmission/retrieveFrom/0/attributes/evidenceDates/0/startDate
}, 
status: 422, 
title: Invalid format
```
