### ISSUE TITLE
Learn about Tier 3 issues and how they are tracked

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#60058]
# Story
As a member of the Cartography Team, I need to obtain and analyze user feedback, so I can make informed decisions about the direction of the MHV on VA.gov landing page.

# Important information
[Notes from call with Sean Good and others](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/metrics-performance-monitoring/MHV-Helpdesk-data.md)

This work is follow-on from [meeting with Susan Haidary](https://app.zenhub.com/workspaces/mhv-on-vagov-top-level-view-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/59619).

User feedback coming from Veterans themselves or from CBOT coordinators get escalated to Tier 3 if they are determined to be technical in nature. 

Questions: 
- How are Tier 3 issues recorded and tracked?
- Source of Tier 3 issues? Assumption: HRC call center & coordinators (and MHV "contact us" form?)
- Who is fielding Tier 3 issues?
- How is the user notified that the issue has been resolved? 

# Tasks

- [x] Get Sean Good's contact info (from Susan?)
- [x] Reach out to Sean Good to get answers to questions and document the answers
- [x] See if possible to set up intervals of data sharing if Tier 3 issues are recorded and tracked

### Acceptance Criteria
Conversation with Sean Good has happened and results are documented.

**Comment by fmccaf1** [comment]
Scheduled a meeting to meet with Sean Good and two of his colleagues, Melissa Ashton and David Rawlins. Scheduled for Friday 7/28 10:30 am.

**Comment by fmccaf1** [comment]
Had meeting with Sean, Melissa and David today. Melissa creates a weekly report on Mondays to share out types of issues coming through. I asked her to send me Monday's report to see if this could be a good source of info for our team or not.
