### ISSUE TITLE
Identity Dashboard FE - Create Teams page

### ISSUE THREAD

**Issue by ianmagenta** [department-of-veterans-affairs/va.gov-team#60055]
## Description
Using the Design assets (Figma) link below, create the Teams page (authenticated)

## Design Review
https://www.figma.com/file/rw8kJXf4VKliimoMpsEy4Q/Identity-Dashboard-(initial)?type=design&node-id=0-1

## Tasks
- [ ] Using Next.js create a page for the Teams page (authenticated)
  - [ ] The "Create Team" button should take you to the Register New Team page
  - [ ] The "creating a team" link should be an empty href (for now)
- [ ] Write tests for the above
