### ISSUE TITLE
Design | Profile | RX Shipment Notifications

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#60054]
## Background 
We learned in [this Slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1686153690433529) that the text notifications and email notifications follow different logic in terms of which facilities send each type of notifications. 

In this ticket, we need to figure out how we are going to handle this in the notification settings section of profile.

## Considerations
- We know email notifications come from CMOP, and those are available nationwide, at all VAMCs.
- We know text notifications are limited to certain facilities
- We currently only conditionally show the notification group to people who are associated with participating facilities
- Text notifications will eventually be rolled out nationwide, but we don't know when.

## Important artifacts 
- [meeting notes from 9/2023](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/mhv-notification-preferences-migration/meeting-notes/2023-09-14-rx-notification-sync.md)

## Tasks
- [x] Review any available documentation in github 
     - [x]    check in with VA Notify? to get additional information 
- [ ] brainstorm possible solutions 
 
### VA Notify Contacts to discuss status with:
~Beverley Nelson~
Melanie Jones

## Acceptance Criteria
- [ ] TBD

**Comment by mtcA6** [comment]
@andaleliz I see you moved this to the current sprint. Do you feel we have enough to proceed [based on this slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1693921206330489)? You and I initially drafted this ticket but I left it in the backlog looking out to around sprint 22, or later, based on the gut feeling I had from [this thread ](https://dsva.slack.com/archives/C909ZG2BB/p1693509904728069)initiated by Beverly where she surfaced concerns around moving forward. 

This comment in particular makes me think its too soon to pick this up:
>Beverly Nelson
>  [7 days ago](https://dsva.slack.com/archives/C909ZG2BB/p1693511151726859?thread_ts=1693509904.728069&cid=C909ZG2BB)
>Especially for Rx shipping.  The functionality is still up in the air (kinda) and  the dates are not clear

**Comment by andaleliz** [comment]
@mtcA6 I'm ok with moving this back to a different sprint - I moved it before I was assigned to the QA ticket and forgot I had to work on that so I don't think I have bandwidth to finish this in this sprint anyway.

There was a convo [this week that might be helpful](https://dsva.slack.com/archives/C909ZG2BB/p1693921206330489) to you as well.

**Comment by mtcA6** [comment]
@andaleliz when you're done making a GH page with your notes from the call we just had, could you link those here?

**Comment by andaleliz** [comment]
[Notes here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/mhv-notification-preferences-migration/meeting-notes/2023-09-14-rx-notification-sync.md)

**Comment by andaleliz** [comment]
@mtcA6 taking another look at this - I think we can close this out since we decided yesterday that Adam is going to use feature toggles to manage each notification once we hear back from the OCTO folks about how they want to handle this. There aren't any updates to make in Sketch to reflect this. 

Do you think we're good to close it out?

**Comment by mtcA6** [comment]
@andaleliz, my preference, for now, is to leave this in the backlog. I want us to have these next couple of meetings with Carnetta about notification preferences and get closer to that PI13 the MHV folks mentioned before we consider this done and dusted.
