### ISSUE TITLE
Identity Dashboard FE - Create Teams Page

### ISSUE THREAD

**Issue by ianmagenta** [department-of-veterans-affairs/va.gov-team#60057]
## Description
Using the Design assets (Figma) link below, create the Teams page (authenticated)

## Design Review
https://www.figma.com/file/rw8kJXf4VKliimoMpsEy4Q/Identity-Dashboard-(initial)?type=design&node-id=0-1

## Tasks
- [x] Using Next.js create a page for the Teams page (authenticated)
  - [x] The "Create Team" button should take you to the Register New Team page
  - [x] The "creating a team" link should be an empty href (for now)
  - [x] "Learn More" link should be an empty href (for now)
  - [x] Fix the `vads-u-` bug
  - [x] Create a basic landing page for Registering a new team on the teams/register route
- [x] Write tests for the above

**Comment by aparsley** [comment]
Looks great, thank you for linking the Dashboard Figma.
