### ISSUE TITLE
Identity Dashboard (FE) - Create the empty integration Client Config page

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#60066]
## Description
Using the Design assets (Figma) link below, create the Client Configurations page

## Design Review
https://www.figma.com/file/NgTUQowdoP3TsasZTHiwpu/Identity-Dashboard-(views)?node-id=0%3A1&t=I9pcazLJSWhj2rCA-1

## Tasks
- [x] Using Next.js create a page for the Client Configurations page
  - [x] Create the "No Integrations" view
    - [x] The "Create integration" button will just navigate to the "Create new integration page"
- [x] Write tests for the above

**Comment by aparsley** [comment]
Looks great, thank you for linking 60066 and checking tasks completed!
