### ISSUE TITLE
Identity Dashboard (FE) - Create the new integration page

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#60069]
## Description
Using the Design assets (Figma) link below, create the "Create new integration" client config page

## Design Review
https://www.figma.com/file/NgTUQowdoP3TsasZTHiwpu/Identity-Dashboard-(views)?node-id=0%3A1&t=I9pcazLJSWhj2rCA-1

## Tasks
- [x] Using Next.js create a page for the "Create new client config" page
  - [x] Combine the Stepper and the "new Client Integration" into the New Integration page
  - [x] Navigating back and forwards will take me to the next "step" in the process
- [x] Write tests for the above

**Comment by asg5704** [comment]
@acaruso-oddball What's the progress on this?
