### ISSUE TITLE
Identity Dashboard (FE) - Create Stepper component for integration steps

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#60071]
## Description
Using the Design assets (Figma) link below, create the Stepper with the integration steps for the "new integration" page

## Design Review
https://www.figma.com/file/NgTUQowdoP3TsasZTHiwpu/Identity-Dashboard-(views)?node-id=0%3A1&t=I9pcazLJSWhj2rCA-1

## Tasks
- [x] Create the Stepper component (using Chakra UI)
  - [x] Each step forward should save the `clientConfigFormState` in a state object
- [ ] Write tests for the above
