### ISSUE TITLE
[UX] Create a sitewide intake ticket (resource page update) for adding mobile check-in information to resource page and update poster

### ISSUE THREAD

**Issue by kellysmith1008** [department-of-veterans-affairs/va.gov-team#60078]
## User Story
As we get closer to a national release for mobile app check-in capability, we need to fill out a [sitewide intake ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=RLHecht%2C+coforma-terry&labels=sitewide+CAIA%2C+sitewide+content-product+support%2C+Sitewide+IA%2C+sitewide+content&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E) to alert the sitewide team that changes need to be made on the [resource page](https://www.va.gov/resources/how-to-check-in-with-your-smartphone-for-some-va-appointments/).

## Tasks
- [ ] Create a sitewide intake ticket. 
- [ ] Include a link to the poster wireframe.
- [ ] Tag Misty Milliron-Grant, Kristen McConnell and Danielle Thierry on the ticket. 
- [ ] Post the ticket link in the #sitewide-content-ia clack channel, tagging the same people listed above

## Acceptance Criteria
- [ ] Release date for mobile app check-in is noted in the intake ticket
- [ ] Misty, Kristen, and Danielle (or necessary people) are tagged on the ticket
- [ ] Link to ticket is posted in the slack channel
- [ ] Link to the ticket is placed in this ticket
