### ISSUE TITLE
Required Accessibility Update from Staging Review:  Statement of truth text

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#60087]
## Issue Description
In our Staging Review on 6/9/23, this Accessibility feedback was provided as "launch-blocking" for our FSR enhancement work. Ticket: #60036

From Platform Team:
"On Step 7 of 7 when reviewing your information prior to submitting, there's a difficult usability challenge that we identified with some other forms around the Veteran's Statement of Truth.

If you're a screen reader user, by the time you get to this point you've likely gotten into the rhythm of just hitting [tab] over and over again to move between interactive elements in the workflow. For the most part, there's no reason you would ever have your screen reader announce the full text of the page.

But when you reach this review page, there's a [tab] jump from the last accordion straight to the "Veteran's full name" input. If you're tabbing through the page, you'll hear "Veteran's full name" but you won't hear any of the statement of truth text that goes with it. The legal fine print is essentially hidden from screen reader users. It's there and technically accessible, but unlikely to be noticed."

Screen reading Reference ticket #57662
---
## Tasks
- [ ] Platform recommends the following steps to resolve this: 
_"Eventually I'm hoping we can develop a better/more consistent pattern for this. But for now, the approach we've landed on is to associate the statement of truth text with the full name input using aria-describedby. It's a little clunky, but it ensures that screen reader users will hear the legal fine print when they reach that input."_

## Acceptance Criteria
- [ ] A user using a screen reader will be hear the statement of truth text prior to being required to legally sign.
- [ ] Product Owner has validated the update meets standard.

**Comment by amponce** [comment]
Merged and ready for verification on stage

**Comment by amponce** [comment]
On production, ready for product owner review on stage and prod
