### ISSUE TITLE
Update operational processes for Platform Support

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#60107]
## User Story
As a Governance team member, I want to ensure I am closing out the #vfs-platform-support requests correctly so the Platform Support team doesn't have to interfere.

Assignee: @CherylEvans 
Peer Reviewer: @allison0034 

## Description
The Platform Support team has recently begun monitoring all support requests in the #vfs-platform-support channel, no matter what team they're assigned to. They add the :eyes emoji when they see the request, just like Governance team, and then they add the :support-complete emoji when the request is completed. Platform Support will reach out in the thread to confirm with the team assigned that the request has been completed. To make the process simpler/easier for both teams involved, Governance team has agreed to begin adding the :support-complete emoji when we have completed our task. This way, the VFS team sees consistent and aligned support behavior no matter who the request is assigned to, and Platform Support team knows the support request has been completed without having to chime in.

The purpose of this ticket is to update the Governance team operational documentation to include adding the :support-complete emoji to our process.

## Impacted Artifacts
Moderator responsibility docs ([Kickoff](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities), [DI](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Moderator+Responsibilities), [MPR](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Moderator+Responsibilities), and [SR](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review+-+VFS+-+Moderator+Responsibilities))
On-support Guide

## Tasks
- [ ] Add steps to all relevant documentation to add the :support-complete emoji when the support request has been completed

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Governance team members add the :support-complete emoji on all support requests in the #vfs-platform-support channel when the support request has been completed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
@CherylEvans I do not think we need to add this step to the individual moderator pages. We currently do not have the "eye" emoji in those pages. I think we should be consistent and just leave those instructions in the on support doc. What do you think?

**Comment by CherylEvans** [comment]
@allison0034 Most people don't read the on-support doc every time they schedule a meeting. They read the individual moderator pages every time they schedule a touchpoint or a KO because there is ### so much information and many tasks. I sometimes get overwhelmed, especially if I have a lot of other things going on, and I love that there is a "list" of steps to follow. I think it would be helpful to new team members as well if we get any. I think we should leave it in.  :-) 
Just my 2 cents. :-)

**Comment by allison0034** [comment]
@CherylEvans ok what do you think about adding the step with the eye emoji so we stay consistent?

**Comment by CherylEvans** [comment]
@allison0034 The eye emoji is specific to the duties and responsibilities of being On-Support, whereby the support-complete emoji is specific to support requests for CC and other support requests. There is no need for consistency between the Moderator responsibility docs and the On-Support doc, as they are guides for two separate but somewhat related guides.  Does that make sense? Let me know if you have any additional thoughts or concerns or want to discuss further with Shira or the team. :-)

**Comment by allison0034** [comment]
If it makes sense to you then I am fine with it.

**Comment by CherylEvans** [comment]
@shiragoodman Let's chat about this tomorrow.

**Comment by CherylEvans** [comment]
@allison0034 @shiragoodman After much thought, I agree we should follow your initial suggestion above and place the support-complete emoji and instructions in the On-Support guide only. My overriding thought was that we would forget to add the support-complete emoji unless we had a reminder in the scheduling docs...but you're right; we don't need it.  I will return the Moderator responsibility docs (Kickoff, DI, MPR, and SR) to their original state!  I appreciate your feedback, even though it took me a minute to align myself with it. lol. :-)

**Comment by CherylEvans** [comment]
@allison0034 The moderator responsibility docs (Kickoff, DI, MPR, and SR) are back to their original state.  Are we good to close this ticket?

**Comment by allison0034** [comment]
@CherylEvans yes, but if you have a difference of opinion I am fine with it and always open to discussion : )

**Comment by CherylEvans** [comment]
@allison0034 Same here. :-) Thank you!

**Comment by CherylEvans** [comment]
@allison0034 It's gone from MPR MR.  I forgot to publish it!
