### ISSUE TITLE
Identity Dashboard (FE) - Refactor Header component

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#60119]
## Description
Refactor the Header component to conditionally render the Crisis Line & US Govt Site header

## Tasks
- [x] Create a prop to conditionally render the Crisis Line Modal & US Govt Site
- [x] Remove Authenticated Header component
- [x] Write unit tests

**Comment by acald-creator** [comment]
https://github.com/department-of-veterans-affairs/identity-dashboard-fe/pull/19

**Comment by aparsley** [comment]
Looks great, thank you for including the dashboard link.
