### ISSUE TITLE
(Samara) Content edits for #60153

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#60110]
## Issue Description
VA engineer provided new content he is suggesting we add to the Platform website relating to [this support ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60153).

---
## Tasks

- [x] Add new content customer provided as a new section toward the bottom of this page: https://depo-platform-documentation.scrollhelp.site/developer-docs/debugging-unit-tests
- [x] Prepare the page for deployment

## Acceptance Criteria

- [x] New section about "how to debug (and avoid writing) flaky unit testing will be added to the [Debugging unit tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/debugging-unit-tests) page and deployed
