### ISSUE TITLE
Identity Dashboard (FE) - Refactor Sidebar

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#60123]
## Description
Fix the Sidebar component to standardize routes and make responsive

## Tasks
- [x] Create a data file for the sidebar routes
  - [x] Should include a friendly name, route, CSS classes and icon reference
- [x] Loop through the routes with the data file and standardize the links
- [ ] Create a responsive view for the Sidebar (wrap to top with menu icon)
  - [ ] *Note whoever picks this up let me know if you need me to add some design in Figma for this.
- [ ] Create a dropdown for the `Applications` where `Client Config` is the only child route

**Comment by joeniquette** [comment]
working on mobile viewport

**Comment by acald-creator** [comment]
Closing to create new ticket
