### ISSUE TITLE
Collaboration Cycle for Disability Benefits Experience Team 1, 21-526EZ, Toxic Exposure Page

### ISSUE THREAD

**Issue by alatempa24** [department-of-veterans-affairs/va.gov-team#60140]
### VFS team name

Disability Benefits Experience Team 1

### Product name

21-526EZ

### Feature name

Toxic Exposure Page

### GitHub label for product

disability-experience

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

5/24/2023

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Tools, applications and dynamic pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/e8022d2012f42652dbf2378a30bc92c1fa4864be/products/disability/526ez/archive/product/526%20Original%20Claims%20-%20Product%20Guide.docx

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Notify the Collaboration Cycle team of this ticket in the vfs-platform-support Slack channel.

- [X] I acknowledge that I must notify \#vfs-platform-support after submitting this issue.

Kickoff Slack Thread with VFS team: ([Link](https://dsva.slack.com/archives/CBU0KDSB1/p1686587715541349))
</details>

### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- [ ] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [ ] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [ ] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.

**Design Intent artifacts**

See Platform guidance on [Design Intent artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Design Intent meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

_Context and problem definition:
We are working to align the digital form with the paper/PDF version and need to add 8 new questions to the form. Our team's overarching goal is to increase ease of use, and we'd like to use this as an opportunity to do research and hear from veterans how they prefer to experience the lengthy 526 form. We would like to experiment with design system patterns to address the tension between making pages concise ("one thing per page") and making them limited in number. Some context to be aware of:
-Based on the 19 va.gov forms reviewed, most digitized forms average 8-10 pages.
-The 526 digital form contains at minimum 20 pages, and especially because the user flow also includes forms 21-8940, 21-0781, and 21-4142 it can be as much as 90 pages depending on user input.
-When we factor in changes that will need to be made to fully deprecate use of the [wizard pattern](https://design.va.gov/patterns/wizards), we expect at least 10 additional pages could be added.
-Based on our current roadmap, we expect we may add up to 5 pages in the near term (including the ones in this toxic exposure flow)
Note there are some pages in which "one thing" is a set of closely related questions, such as details about private medical records, and in this new case the "one thing" could similarly be toxic exposure details. The 526 is exceptional in a few regards (length, use, and timing in veteran journey) so we think it worthwhile to consider whether we may need to make design decisions that are specific to 526, but we expect if this is the case we'd still need to be judicious about where, when, and how._

- [x] User flow (required): https://sketch.com/s/c353146f-eceb-4626-9918-7603c693417f
- [ ] Whiteboard sketch or other lo-fi prototypes or wireframes
- [x] [Research plan](https://github.com/Nyanteea/va.gov-team/blob/master/products/disability/526ez/Research/2023-07-Toxic-Exposure/research-plan.md) 
- [ ] Any other artifacts you have so far
  
##### Platform actions
- [x] Design Intent Slack thread with VFS team: [Link](https://dsva.slack.com/archives/CBU0KDSB1/p1686587715541349)
- [x] Meeting date/time: **Tuesday, June 20 at 11:30am ET**
  
##### Platform actions

- [ ] If you have feedback, create feedback tickets and link to this epic. Once you have completed you review, check the box next to your practice area
  - [x] Accessibility has completed the review
  - [x] Design has completed the review
  - [x] IA has completed the review
- [x] Update this ticket with the Zoom recording
  - Recording URL: [Link](https://oddball-io.zoom.us/rec/share/wZAASKpQZfXDqISIZHd13Mq0YUGgWxuO2VC23Z7Suxu1bbi1mgxtFDPSRicNWcPA.PzVCwWdinp2PZHGv)
  - Password: r1dj#1jx
  
##### VFS actions

- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Sitewide Content and IA Intake Request
<details>
  <summary>Toggle Sitewide Content and IA Intake Request</summary>

##### VFS actions
- [ ] Complete the [sitewide content and IA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-Content-and-IA-intake-request.2124906551.html)
- [ ] Link to the Sitewide Content and IA Intake Request ticket below - Intake #60669

</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [ ] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review (Fall, 2023)
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [ ] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

Provide links or documents for the following:

- [X] Finalized design prototype or mockup: Note that content review is in progress and designs are expected to be updated by EOD Wednesday 6/28 https://sketch.com/s/c353146f-eceb-4626-9918-7603c693417f
migrated mock to figma: [TE Mocks: midpoint review](https://www.figma.com/file/dBKlB23Hs2oa53euXcXmmK/526-toxic-exposure?type=design&node-id=0-54471&mode=design&t=vxEedevKNqmLpa0n-0)
- [x] Specify which pages are included in the review: Please see "TE prototypes - Test A" page (IGNORE "TE prototypes - Test B")
- [x] [Research plan](https://github.com/Nyanteea/va.gov-team/blob/master/products/disability/526ez/Research/2023-07-Toxic-Exposure/research-plan.md) 
- [ ] Conversation guide
 
**Content artifacts**
  
- [X] Your product’s content source of truth: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/design/toxic%20exposure%20questions%20June%202023.md 
- [X] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable): https://github.com/department-of-veterans-affairs/va.gov-team/issues/60669

**IA artifacts**

- [ ] Please include a link to any [Sitewide Content & IA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including an IA review document or intake form.

##### Platform actions
- [x] Midpoint review Slack thread with VFS team: [Link](https://dsva.slack.com/archives/CBU0KDSB1/p1687791892543779)
- [x] Meeting date/time: **Friday, June 30th at 11:30am ET**

##### Platform actions

- [x] If you have midpoint review feedback, create feedback ticket and link to this epic. Once you have completed your review, check the box next to your practice area
  - [x] Design has completed the review
  - [x] Accessibility has completed the review
  - [x] IA has completed the review
  - [x] Content has completed the review
- [x] Update this ticket with the Zoom recording
  - Recording URL: [Link](https://oddball-io.zoom.us/rec/share/v2eDD2MFbuPFxsxOLADO5bCb93p41bCKS0JBwlPPdek2ZUS1UDTMPXJpOBpkcKwA.hYtQ096nyKLEU3tY)
  - Password: *rQQbK@8
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### 2nd Midpoint Review (Feb, 2024)
<details>
  <summary>Toggle 2nd Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [x] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [x] Notify the Collaboration Cycle team of this event by using the `/Collab Cycle Midpoint Review` "slash-command" in your team channel. Provide information as prompted by the Slack workflow.
- [x] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**2nd Midpoint Review artifacts**

> See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

Our design has changed since our Fall, 2023 midpoint review based on CAIA feedback, usability testing results, requirement changes from VBA, and additional engineering discovery. We wanted to bring these changes back for a second review prior to MVP launch.

###### Key changes

1. We’ve moved where the screens are in the flow
2. We’ve eliminated one locations screen
3. We adopted a list and loop pattern for both locations and individual hazards (originally only applied to individual hazards)
4. We are asking for a single date range per location and/or individual hazard
5. We’ve made some copy changes, including to subheadings
6. We are allowing Veterans to hedge on their answers to allow them to move forward without getting bogged down in the details (by indicating “I’m not sure”, for example)

During technical discovery, we found that the [multiple-page list and loop (a.k.a. "multiple response") pattern](https://design.va.gov/patterns/ask-users-for/multiple-responses#how-to-design-and-build---multi-page) cannot be triggered from checkboxes with our current forms library implementation (more detail on the issue in [this comment on issue 67013](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/67013#issuecomment-1890067324)); so, in particular we would like to get feedback on the design and advice on what our options are for moving forward with it.

We are not planning to do another round of usability testing before launch, due to time constraints and also because the list and loop pattern tested well the first time. Our content changes are addressing other usability feedback. We are planning to monitor site metrics and conduct usability testing post-launch, however.

Provide links or documents for the following:

- [x] Finalized [design prototype](https://www.figma.com/proto/dBKlB23Hs2oa53euXcXmmK/526-toxic-exposure?page-id=0%3A411&type=design&node-id=0-411&viewport=-915%2C-532%2C0.18&t=sKs8lMLfq0PwEfoX-1&scaling=min-zoom&starting-point-node-id=0%3A1296&mode=design) and [screens with accessibility annotations general notes](https://www.figma.com/file/dBKlB23Hs2oa53euXcXmmK/526-toxic-exposure?type=design&node-id=0%3A411&mode=design&t=hh9Q2tDzRaddkxRf-1)
- [x] Specify which pages are included in the review: Figma "page" titled "WIP: TE Mocks -  MVP 01/2024". Include the screens under the headings "WIP Mock Updates 01/2024" and "Error messages". These are also all the screens included in the prototype.
- [x] [Background on design decisions made and alternatives explored](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/toxic-exposure.md) 
- [x] [Prior research findings](https://docs.google.com/presentation/d/1VLqXexB72C_fPjUyw1MwL2Pjznvsg_q_UYbg16xk-iM/edit) and [prior research plan](https://github.com/Nyanteea/va.gov-team/blob/master/products/disability/526ez/Research/2023-07-Toxic-Exposure/research-plan.md)
- [x] [Goals for future (post-launch) research / analytics plan](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/73031) (still in progress)
 
**Content artifacts**
  
- [x] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including a content source of truth, any relevant static content page and entry point updates, and the intake form.: 
    - [x] [CAIA accessibility feedback](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/Deliverables/Benefits%20Disability%20Experience%20526EZ/202312-design-review.md)
    - [x] CAIA content feedback was captured in [Sketch comments](https://sketch.com/s/c353146f-eceb-4626-9918-7603c693417f)
    - [x] Content source of truth is [the Figma screens](https://www.figma.com/file/dBKlB23Hs2oa53euXcXmmK/526-toxic-exposure?type=design&node-id=0%3A411&mode=design&t=hh9Q2tDzRaddkxRf-1)

**IA artifacts**

- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) feedback you received, including an IA review document or intake form.
    - [x] [Midpoint Review - IA Feedback Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61260)
    - [ ] (not sure if there is more to list here)  

##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C04KW0B46N5/p1706286146096449), [Rescheduled touchpoint Slack thread](https://dsva.slack.com/archives/C04KW0B46N5/p1706545750653139)
- [x] Meeting date/time: ~February 1st at 3:30 (Cancelled),~ **Friday, February 2, 2024 at 11:30AM ET**

##### Platform actions

* Accessibility
  * [x] [Feedback ticket attached](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/75429)
  * [ ] No feedback
* Content
  * [x] [Feedback ticket attached](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/75274)
  * [ ] No feedback
* Design
  * [x] [Feedback ticket attached](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/75239)
  * [ ] No feedback
* IA
  * [x] [Feedback ticket attached](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/75362)
  * [ ] No feedback
* [x] Update this ticket with the Zoom recording
  - [Recording link](https://oddball-io.zoom.us/rec/share/gvic1Km7Vi5JaDOsduHCgNInp3Yez9RUVbH885H5GQE3bqTVfWF0b5PWRE44jHdq.4sX6hVjXY3WWxlhs)
  - Passcode: `wGf!.8h!`
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [ ] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [ ] Link to the Analytics Implementation and QA Request ticket below

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [x] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [x] Link to the Contact Center review request ticket [#89438](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89438)

</details>

### Staging Review
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [x] I confirm the environment is available and test users have been provided.
- [ ] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).

**Staging Review artifacts**
  
See Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts). Platform findings are based solely on the staging URL and test users provided, as reviewed during the four days before the Staging Review meeting. Any test cases not covered or any ongoing work taking place during the review period may not be reflected in those findings.  

**Product artifacts** 
- [x] Staging URL
https://www.staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction

- [x] Specify which pages are included in the review
[The pages in this google sheet](https://docs.google.com/spreadsheets/d/1Bi65N54v2yKCFFR42aStk3SGHBXlHDOCNbchKHb8ddg/edit?gid=227003192#gid=227003192) and;

http://www.va.gov/disability/file-disability-claim-form-21-526ez/review-and-submit <-- For this page, you should see the Veteran's conditions linked to Toxic Exposure. For Veteran's with an In Progress Form, there should also be an alert for Veterans with an In Progress Form.

- [x] Staging test user information
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-526-toxic-exposure.md

**Content artifacts**
- [x] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
[Add alert to Review & Submit page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85579)

**IA artifacts**
- [x] Please include a link to any [Sitewide Content & IA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) of the findings you received, including an IA review document or intake form.
[526ez Review Toxic Exposure content](https://github.com/department-of-veterans-affairs/va.gov-team/issues/84033)

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [x] [Regression test plan](https://dsvavsp.testrail.io/index.php?/cases/view/37806)

- [x] [Test plan] [Toxic Exposure Pages Implementation](https://dsvavsp.testrail.io/index.php?/suites/view/2552&group_by=cases:section_id&group_id=9942&group_order=asc&display_deleted_cases=0)

- [x] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/928)
- [x] [Summary for Cases(Defects) reports](https://dsvavsp.testrail.io/index.php?/reports/view/930)
- [x] [Summary for(Defects) reports](https://dsvavsp.testrail.io/index.php?/reports/view/929)
- [x] [E2E tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-e2e-test-participationE2ETestParticipation) (provide a link to the product’s code)
https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/disability-benefits/all-claims/tests
- [x] [Code coverage](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-unit-test-coverageUnitTestCoverage) (provide a link to the product’s code) 
https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/disability-benefits/all-claims
Coverage report 8/19/24
<img width="1030" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelpyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d445ca24369f0c7ed8a9042d991940d743e617b/disability-benefits-unit-test.png" alt="disability-benefits-unit-test.png" />
 
  
**Accessibility artifacts**
  
- [x] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89340).
  
##### Platform actions
- [x] [Staging review Slack thread with VFS team](https://dsva.slack.com/archives/C04KW0B46N5/p1723573030726939)
- [x] Meeting date/time: **Friday, August 23, 2024 at 2:00pm ET**

##### Platform actions

- [x] Update this ticket with the Zoom recording
  - [Staging Review meeting recording](https://oddball-io.zoom.us/rec/share/v0xbG6O4ANUaTjlXMROEbxSGg4rWSumTZbCyNPHRPi-QqHB0oQ1_TrXXERLqHN1X.b0GCHvIf4m_XPbUP)
  - Passcode: `Py!0rKS2` 
 
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [x] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [ ] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [ ] Link to the Readiness Review ticket below

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by Nyanteea** [comment]
@Nyanteea

**Comment by Kate-allbee** [comment]
We've migrated this design file to Figma :
[Figma Link](https://www.figma.com/file/dBKlB23Hs2oa53euXcXmmK/526-toxic-exposure?type=design&t=w5voh6uQ0DfcLgsw-6)
**No longer using sketch file**

**Comment by yurenanava** [comment]
Closed as complete
