### ISSUE TITLE
Create swim lanes for Collaboration Cycle

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#60141]
## User Story
As a VFS team member, I want to understand the flow of the Collaboration Cycle, so that I know how the process works and who is responsible for what parts of the process.

As a Governance team member, I want to have documentation around who is responsible for different touchpoints within the collab cycle, so that I can point VFS teams to the right team.

Assignee:
Peer Reviewer:

## Description
VFS teams tag the Governance team in the VFS support Slack channel on things that are in the collaboration cycle but that we are not responsible for. Additionally, newer VFS PMs sometimes get confused about where to start and when to complete touchpoints within the Collaboration Cycle.

## Tasks
- [ ] Create a user flow using swim lanes
- [ ] Determine if we should replace the image on [this page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/)

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] VFS teams can refer to a swim lanes user flow to see who is responsible for different touchpoints within the collab cycle.
- [ ] VFS teams know when to move to the next collab cycle touchpoint.

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
[Swim lanes draft](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1686676305244/4fb520e97c488d1fd053d93c6497e09ab0880207?sender=u045df875f30f7e9f34339908)

**Comment by allison0034** [comment]
This will carry over to the next sprint as it was just picked up in the last sprint.

**Comment by sterkenburgsara** [comment]
@allison0034 sorry for not getting to this in a timely manner this sprint! I am curious if we could explore a circle diagram since the collab cycle is intended to be cyclical - always encouraging VFS teams to start again & iterate continually on their product. I will brainstorm.

Is this intended only for VFS teams? I wonder if a detailed version would help our team, and a more high-level/succinct version could be VFS-facing?

**Comment by allison0034** [comment]
@sterkenburgsara it isnt ready for review yet anyway... I picked it up as an extra ticket last sprint so no worries! We can explore for sure!

**Comment by allison0034** [comment]
I have scheduled a meeting with Sara to discuss some of her ideas.

**Comment by allison0034** [comment]
I have completed the [in depth user flow](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1686676305244/4fb520e97c488d1fd053d93c6497e09ab0880207?fromVisitorModal=true&sender=u045df875f30f7e9f34339908). I would like to look at this again after PTO. I think a high level user flow can be made from this as well.

**Comment by sterkenburgsara** [comment]
Update: this ticket will move into the next sprint when @allison0034 is back from PTO. We still need to decide if we should create a second higher level / simpler diagram for VFS-facing teams, and keep the more nuanced flow for internal use.

**Comment by allison0034** [comment]
@sterkenburgsara I would love your help with working in the actual review. I am struggling, care to take a stab at it?

**Comment by sterkenburgsara** [comment]
@allison0034 took a stab at including the actual review (I copied your swim lanes and made a second copy beneath yours). There are a few sticky notes in there for your review.

**Comment by allison0034** [comment]
#### @sterkenburgsara I made the changes we talked about, can you take one more peak at the [user flow?](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1686676305244/4fb520e97c488d1fd053d93c6497e09ab0880207?fromVisitorModal=true&sender=e421f99d-9f07-4750-8bf7-29451d38f958)


#### @shiragoodman @sterkenburgsara which option do you prefer:
1. Remove the current image on [this page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/) and add a link to the new user flow
2. Keep the current image but add a link to the new user flow
3. Make no changes to that page


#### In addition to the options above, I would like to add the user flow to [our documentation](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748860945/Collaboration+Cycle). Are you ok with that?

**Comment by shiragoodman** [comment]
I am absolutely on board with adding the user flow to our operational documentation. @allison0034 would you be able to get a ticket started for that work and link it here? 

I do also agree with getting the new flow up on Platform Website so that VFS teams can take it in. Wrt replacing or adding on to the existing flow, maybe we could create a version of the existing flow on PW that uses the same design style as the new one you created? That way there's 2 flows - 1 high level and 1 detailed view.

I have concerns about how a flow that wide will display on the Platform Website. Have you thought about this at all? I'm thinking we should reach out to the Platform Content team for their recommendation.

**Comment by allison0034** [comment]
Updates to documentation will be done in ticket #62149
