### ISSUE TITLE
[eFSR] Bug - Required Field Inputs For Spouse Additional Income and Deductions List for Spouse/Veteran

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#60168]
## Issue Description
Spouse Additional Income > [Input list](https://github.com/department-of-veterans-affairs/vets-website/blob/4398d6ba2643301078c48d41847c9dc158485de1/src/applications/financial-status-report/components/SpouseAdditionalIncomeInputList.jsx) question Required field doesn't work.
Employment History > Paroll Deduction Input List (both [Spouse](https://github.com/department-of-veterans-affairs/vets-website/blob/ba4afd1ab2941fccca9d1c3fdc58457b0b2e5097/src/applications/financial-status-report/components/SpousePayrollDeductionInputList.jsx) and [Veteran](https://github.com/department-of-veterans-affairs/vets-website/blob/ba4afd1ab2941fccca9d1c3fdc58457b0b2e5097/src/applications/financial-status-report/components/PayrollDeductionInputList.jsx)) required fields don't work. Can press continue without filling out the fields.

---
## Tasks
- [x] Fix Required field for Spouse Additional Income Input List
- [x] Fix Required field for Payroll Deduction Input List for both Spouse and Veteran

## Acceptance Criteria
- [x] Incomplete required field throws an error and prevents navigation 
- [x] All tests passing
  - [x] e2e
  - [x] unit
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by OptionSelect** [comment]
The work for this is rolling under 57342 due to scope creep in that ticket.
https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/57342
