### ISSUE TITLE
[FE] - Add Wilkes-barre clinics to allow list.

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#60186]
## Summary

Wilkes-barre wants to test a three specific clinics. ~~We need an additional filter to do this. This will add the sta6n value to the travel allow filter.~~

Updated this ticket after some exploration, we are not currently passing sta6n from vets-api, so to avoid two PRs, this ticket is to add all of the Wilkes-barre clinicIens we need as a list.

## Tasks
- [ ] [FE] - ~~update filter to also use `sta6n`~~
- [x] [FE] - Add Wilkes-barre, Allentown clinics to allow list (693B4)
- [x] [FE] - Add Wilkes-barre Sayre clinics to allow list (693GA)
- [x] [FE] - Add Wilkes-barre Williamsport clinics to allow list (693GB)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met and tasks complete
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
@loripusey this is merged and in prod, I guess we will validate on Monday live
