### ISSUE TITLE
Address duplicate steps in Platform Orientation gh ticket

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#60200]
## User Story
As a VFS team member, I want to complete the Platform Orientation process and not encounter duplicate steps so that I am able to support my VFS team as quickly as possible.

Assignee: @CherylEvans 
Peer Reviewer: @briandeconinck 

## Description

> **General**
>  Watch [VA.gov overview video](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html#PlatformOrientation-Purpose)
> 
> **Norms and standards**
>  Review [Orientation materials](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html) on Platform Website
> 
> are duplicative steps.
> 
> _Originally posted by @ohgreatkate in https://github.com/department-of-veterans-affairs/va.gov-team/issues/59057#issuecomment-1563499776_

Let's remove the step from "Norms and Standards" and modify the language under General.

## Impacted Artifacts
Make updates to the pull request for the Orientation ticket associated with the asynch orientation session changes
Platform Orientation Template

## Tasks
- [x] Modify the ticket to remove duplicate steps.
- [x] Refine the language for General

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS teams are no longer asked to complete duplicate steps in Platform Orientation.

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
@briandeconinck Ready for peer review. :-) 

- Deleted duplicative language under Norms and Standards "Review Orientation materials on Platform Website."

- Modified language under General "Watch VA.gov overview video." to "Watch VA.gov overview video to learn about documentation and guidance on Platform Website."
[Pull Request](https://github.com/department-of-veterans-affairs/va.gov-team/pull/60678)

**Comment by CherylEvans** [comment]
@shiragoodman Gotcha.  I'll work on it.

**Comment by CherylEvans** [comment]
@shiragoodman @briandeconinck I updated the description of the video. Ready for review.

**Comment by CherylEvans** [comment]
@briandeconinck This is ready for your peer review. :-)

**Comment by briandeconinck** [comment]
Thank you for the nudge @CherylEvans! This looks good, feel free to merge the PR and close the ticket whenever you're ready

**Comment by CherylEvans** [comment]
@briandeconinck The update to the PO template is complete.
