### ISSUE TITLE
[UX][Design] SPIKE: Confirm alert use in confirmation error pages

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#60210]
## Background

We have a few questions about the use of alerts within our confirmation error pages for unified check-in. Keeping the heading structure the same (worked on with CAIA and approved at platform office hours), we need to answer the following questions:

- Which design shown below should be used for the unified check-in error pages? (check accessibility considerations)
- We know we cannot stack alerts directly, but is it ok to use two alerts if they are under different headings?
- Are we sure we should be using background alerts? (**Background:** We received guidance from Matt Dingee that the green success alert and the yellow warning alert should be a background only alert in this particular case. We would like to double check on this to confirm that it should not be a default alert in any of these cases.)

![Screenshot 2023-06-06 at 4.20.42 PM.png](https://images.zenhubusercontent.com/61843a671a4b5e02e1517a62/0aea3c7a-b334-4af6-b9d8-a9ac8b246c0f)

## Tasks
- [ ] Decide which alert use to go with (between the designs above)
- [ ] Get feedback from platform office hours, in the platform-design-system channel, or from Matt Dingee directly
- [ ] Check on accessibility considerations for the alert solution
- [ ] Create f/u to update wireframes (if there is a change)

## Acceptance Criteria
- [ ] Design solution has been chosen
- [ ] Design solution has been vetted
- [ ] f/u ticket created (if a change is needed)

**Comment by ytsaoca** [comment]
Attended the office hour with @cgednalske yesterday and they confirmed to use the one with 2 H2. (the third option).
Updated the wireframes and they are ready for review.
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/8Vyv4Zx
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/0A7xJ8A
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/Mmya7wm

@benbrasso-agile6 @cgednalske

**Comment by cgednalske** [comment]
Looks good to me! Nice work (and initial error page callout) @ytsaoca 🎉
