### ISSUE TITLE
[eFSR] Checkbox component needs to be updated to use DS 

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#60215]
## Issue Description
The custom [checklist component](https://github.com/department-of-veterans-affairs/vets-website/blob/eb719978a2c3fd423f16ec29fbb58a660b1226d9/src/applications/financial-status-report/components/shared/CheckList.jsx) needs to be updated so that it uses the [DS Checkbox Group](https://design.va.gov/storybook/?path=/docs/components-va-checkbox-group--default) component instead of the custom HTML it currently uses. 

This is needed to ensure consistency with the DS and also to be able to apply the required field to the whole group instead of an individual checkbox. Then we'll be able to implement the original design correctly. 

```
<div key={option + key} className="checkbox-list-item">
  <input
    type="checkbox"
    id={option + key}
    name={option}
    value={option}
    checked={isBoxChecked(option)}
    onChange={onChange}
  />
  <label className="vads-u-margin-y--2" htmlFor={option + key}>
    {option}
  </label>
</div>
```

---
## Tasks
- [ ] Update component to use checkbox group from the DS
- [ ] Update logic connected to checkbox group to ensure data flows across to related input pages

## Acceptance Criteria
- [ ] The custom `Checklist.jsx` component will use the VA DS Checkbox group
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
