### ISSUE TITLE
Identity Dashboard FE - Create Register a Team Page

### ISSUE THREAD

**Issue by ianmagenta** [department-of-veterans-affairs/va.gov-team#60233]
## Description
Using the Design assets (Figma) link below, create the Register a Team page (authenticated)

## Design Review
https://www.figma.com/file/rw8kJXf4VKliimoMpsEy4Q/Identity-Dashboard-(initial)?type=design&node-id=0-1

## Tasks
- [x] Using Next.js create a page for the Register a Team page (authenticated)
  - [x] Team name, agency, and admin email must be required fields
  - [x] "Register team" button should just submit the form (for now)
  - [x] Team setup FAQ’s should be collapsible
  - [x] Remove extra wrapping around text on teams page
- [x] Write tests for the above
