### ISSUE TITLE
Migrate separation_locations from EVSS to Lighthouse - BRD

### ISSUE THREAD

**Issue by navaeddie** [department-of-veterans-affairs/va.gov-team#60247]
## Issue Description
This is a followup to [54646](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/54646)

[Relevant Lighthouse docs](https://developer.va.gov/explore/benefits/docs/benefits_reference_data?version=current). This api is already in production and ready to rock.

After some discovery and consultation amongst engineers, the engineers came up with an outline of how [separation_locations](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/disability_compensation_forms_controller.rb#L31) will migrate from EVSS to Lighthouse.

For further background, some information gathered during discovery is now saved in [Github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/evss-to-lighthouse-migration/brd-migration.md).

There is a [BRD service](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/lighthouse/benefits_reference_data/service.rb) that we will leverage in this work. So we don't have to build something to consume Lighthouse, but rather transform the raw Lighthouse data that this service provides.

There's also some [Redis](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/evss/reference_data/response_strategy.rb) used here. We should be able to rename the Redis service (to something generic that doesn't refer to "EVSS") and keep using it.

We will resist making changes to vets-website, we wish to maintain the contract that vets-api's separation_locations endpoint currently provides to the internets.

[Lucid Chart](https://lucid.app/lucidchart/645d8a16-22de-4971-9626-198da0483430/edit?invitationId=inv_f335ce12-6583-4396-8892-0c33e67c8b9e&referringApp=slack&page=Jj3698RLtzW2#)

![image.png](https://images.zenhubusercontent.com/63dd30048b2159302590655a/a24ac84b-7801-4742-92bc-3999a13b889b) about this work.

---
## Tasks
- [ ] Look over testing to see if it's adequate to ensure a safe migration
- [ ] Build a transform layer to turns the output of the Lighthouse BRD service into whatever the separation_locations method is expecting
- [ ] Update Redis service with a better name
- [ ] Plug separation_locations into Lighthouse service

## Acceptance Criteria
- [ ] We've migrated all the things identified above and BRD still works
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
