### ISSUE TITLE
[bug spike] 526ez | Duplicate claim sent to CMP through backup method

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#60244]
## Value Statement
**_As a_** Veteran whose claim failed to to auto-establish
**_I want to_** send a single backup submission
**_So that_** my claim can be received and established with no confusion.

---
## Background Context
Add here

## Acceptance Criteria
- [ ] A single claim is submitted through the backup pathway.

## Tasks

- [x] Reach out to Tim Wagner for input

# Definition of Ready
- [x] Issue is confirmed as happening
- [x] Scope/# of occurrences is investigated to help inform priority (will be put in ticket comments when discovered)

# Definition of Done
- [x] EXACTLY 1 submission is logged/sent for each backup submission attempted
- [x] All failed submission, attempt/queue only 1 backup submission attempt
- [ ] Confirmed with monitoring/logging over a few days

**Comment by kylesoskin** [comment]
In the last month there were 741 total backup submissions. 
There are 630 unique submission ids in those
So there were 111 duplicate submissions. So 111 / 630 total submissions had duplicates. 
So ~17% of them are having duplicates sent.

**Comment by saderagsdale** [comment]
-Add test case
-Merge
-Validate by spot checking
