### ISSUE TITLE
[eFSR] Bug - Edit address fields not rendering

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#60249]
## Issue Description
Edit mailing address fields not rendering. Likely due to styling implementation used to hide telephone number extension.

### Screenshot 
![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/cacf867b-41b1-4047-899d-1b1df533a53c)

---
## Tasks
- [x] Update styling to correctly target phone number extension so it doesn't affect other fields. 

## Acceptance Criteria
- [x] Phone number extension is hidden
- [x] Edit address fields are hidden
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
