### ISSUE TITLE
CoE | Transition work to new team

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#60243]
## Value Statement

**_As_** the new team responsible for the Certificate of Eligibility
**_I want to_** have sufficient context on past, present, and planned COE work
**_So that_** I can pick up where the previous team left off, without anything falling through the cracks.

## Background Context

We are transitioning COE work to a new team. Please see the following list of tasks for more detail on what is necessary to get the new team up to speed.

## Tasks
- [ ] Give new team a list of contacts who may be helpful during the COE work.
- [ ] Give new team Sentry dashboards related to COE work and provide context.
- [ ] Give new team a tour of relevant COE code and record a video of this tour for their future reference.

## Definition of Ready
- [ ] Eugene knows who the new team is and who specifically will be working on COE.
- [ ] The new COE team has access to VA remote desktop, VA Github, VA Slack, VA Datadog, and VA Sentry. 

## Definition of Done
- [ ] Relevant documentation has been updated to reflect the current state of COE work.
- [ ] New team added to all channels, meetings, documents, and dashboards referenced above, and is sufficiently familiar therewith.
- [ ] Team's engineers are sufficiently familiar with the COE code.

**Comment by data-doge** [comment]
## List of Contacts:

The following people are responsible for the COE Form, on the LGY side. They will probably be able to answer any questions you have and direct you to others who can help. You should also feel free to reach out to me.

| Name | Email | Role |
|---|---|---|
| Kris Kelleher | Kris.Kelleher@va.gov | Scrum Master |
| Kelli Deinarowicz | Kelli.Deinarowicz@va.gov | Product Manager |

## Sentry Dashboard:

http://sentry.vfs.va.gov/organizations/vsp/dashboard/8/?environment=production&project=3&statsPeriod=7d

## Downtime Notifications

LGY Announcements Page: https://lgy.va.gov/lgyhub/announcements (where some downtime periods are announced). See also `#evss-prod` in Slack.

Pager Duty: https://dsva.pagerduty.com/service-directory/PCT7A0L/activity?welcome=1 (See "Maintenance Windows")

Before setting a maintenance window, ask LGY, in the "VA.GOV-LGY COE Group-Production" Team chat, how long the maintenance window should be.

## App Entry Points

vets-api: https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/coe_controller.rb

vets-website: https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/lgy/coe

## Outstanding Work

Along with the open tickets here: https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/lgy/coe, here is a list of other work that you may consider ticketing and throwing in a backlog.

| Description | Notes |
|---|---|
| Troubleshooting 400 and 404 errors on GET /determination and PUT /application endpoints. | If you have a look at Sentry, you'll see the errors referenced in the description. Some portion of these errors (perhaps most) may be due to a discrepancy between VA.gov's EDIPIs and VADIR's APIs. For VADIR-related inquiries you can try reaching out to Jim.Jones@va.gov (SRA) and Christopher.Garrett@va.gov (VADIR PM). In case you find it helpful, just before I moved off this work in February, I began drafting a PR to improve our COE logging, to help debug these 400 and 404 issues. Feel free to re-open that PR: https://github.com/department-of-veterans-affairs/vets-api/pull/11766. |
| Handling non-US uploads | The COE Form currently does not permit veterans domiciled in a foreign country, but not on a US military base, to apply for a COE. Jyssica, an LGY tester (jyssica.sule@va.gov), believes that such veterans should be allowed to apply for a COE. |
| Fix flaky COE keyboard tests | See https://github.com/department-of-veterans-affairs/va.gov-team/issues/52760 |
| Fix hard-coded parts of the COE form | Tech-debt work. Before I had to move off COE, I was in the middle of transitioning some hard-coded changes we had made to the COE schema on the front end, into our vets-json-schema gem. Here are some breadcrumbs for that work: https://github.com/department-of-veterans-affairs/va.gov-team/issues/53281; https://github.com/department-of-veterans-affairs/vets-website/pull/23372; https://github.com/department-of-veterans-affairs/vets-api/pull/11075; https://github.com/department-of-veterans-affairs/vets-json-schema/pull/748.  |

## Other notes

You may find it useful to read through https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/628. There's plenty of useful context around the COE form in there.

**Comment by steele-lm** [comment]
@saderagsdale I confirmed that there are still open tasks on this ticket that need to be completed before closing.
