### ISSUE TITLE
Is Platform Support routing common problems into product backlogs

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#60251]
## Purpose
To lower the burden on Platform Support, and increase the ease of use for VFS team, common problems should be getting routed into product backlogs so that new features can be released to resolve shared problems.

Is there a mechanism for this?  Is it working well?

## Tasks
- [ ] discuss w/ Platform Support team
- [ ] evaluate effectiveness if possible

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
