### ISSUE TITLE
Implementation of Closed Test in Coordination with DevOps COP

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#60254]
## Description
This ticket involves coordinating with a member of the DevOps COP to set up a closed test of the Slack/Sentry integration according to the previously developed plan.

---
## Tasks
- [x] Submit a ticket to DevOps COP Backlog and ensure that team is aware. 
- [x] Member of DevOps will need to set up the new Slack/Sentry integration in a newly created private DSVA Slack channel.
- [x] During set-up determine if there's a means for ensuring just the title of the error and its Sentry link are displayed in Slack
- [ ] Test the new integration by running it in the private slack room in DSVA for 1 -2 weeks.
- [ ] Monitor the output, provide status updates to devops-cop in weekly meeting.

## Acceptance Criteria
- [ ] Successful test setup of the new Slack/Sentry integration has been completed.
- [ ] The new integration works as expected with no issues during the testing period.

**Comment by laineymajor** [comment]
Gia to review info with devops team :)

**Comment by laineymajor** [comment]
Remains in progress. Gia continuing to work with Hector... next steps defined.

**Comment by laineymajor** [comment]
Implementation still being worked on... he will circle back upon completion.

**Comment by laineymajor** [comment]
This is being picked up by Chris and Kshitiz... meeting with hector for a hand off

**Comment by Kshitiz-devops** [comment]
For Slack Sentry integration I created an internal integration which is integrated with slack webhook url. Created a Slack workflow which have webhook for trigger. The workflow will send the message to the channel where it is added.
In Sentry Created a internal Integration by name platform-slack which will integrate with the webhook created earlier. Once the webhook was created I added action to send message to Slack using platform-slack internal integration for below alerts created in sentry for Platform-api project:
http://sentry.vfs.va.gov/organizations/vsp/alerts/metric-rules/platform-api/20/
http://sentry.vfs.va.gov/organizations/vsp/alerts/metric-rules/platform-api/19/
http://sentry.vfs.va.gov/organizations/vsp/alerts/metric-rules/platform-api/15/
http://sentry.vfs.va.gov/organizations/vsp/alerts/metric-rules/platform-api/14/
http://sentry.vfs.va.gov/organizations/vsp/alerts/metric-rules/platform-api/8/
http://sentry.vfs.va.gov/organizations/vsp/alerts/metric-rules/platform-api/6/
http://sentry.vfs.va.gov/organizations/vsp/alerts/metric-rules/platform-api/5/
http://sentry.vfs.va.gov/organizations/vsp/alerts/metric-rules/platform-api/3/cccccbhidvhcdftebkdddgvknjrjfhciclcbriltlrtj

**Comment by laineymajor** [comment]
@Kshitiz-devops @flooose reach out to @kjduensing for feedback.

**Comment by LindseySaari** [comment]
Taking to Kevin D and getting some feedback

**Comment by laineymajor** [comment]
Can we use the official slack integration rather than a custom integration with a web hook. Potential PII leak with the past integration... need some research.
@flooose @Kshitiz-devops to research

**Comment by Kshitiz-devops** [comment]
We can probably use the slack integration available. We need to first know the reason for it to be removed earlier so we can test against that reason and allow it and do the testing.

**Comment by laineymajor** [comment]
@Kshitiz-devops @flooose can y'all please remind me what we are waiting on here? Thanks!

**Comment by jennb33** [comment]
Closing tickets due to decision to not move forward.
