### ISSUE TITLE
Spike: Sketch out steps to implement Slack/Sentry integration

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#60253]
## Description
This purpose of this ticket is to research and determine the possible implementations that will allow us to safely publish Sentry alerts from sentry.vfs.va.gov to a Slack room.  

---
## Tasks
- [x]  Research and document possible design implementations that allow us to publish Sentry alerts to Slack without publicly exposing our Sentry instance.
- [x] If possible, interview engineers who have participated in this process previously.
- [x] Confirm how others have ensured Sentry logs are effectively scrubbed of PII/PHI and session data.
- [x] Document the integration approach(es) in a proposal to be submitted to devops-cop
- [x] Determine if platform-wide communication is necessary to ensure teams are aware of how notifications will be changing

## Acceptance Criteria

- [x] Confirm how other implementations prevent PII from getting surfaced 
- [x] Comprehensive integration approaches are documented, which clearly outline the possible approaches and which steps are to be executed by which teams.
- [x] Integration approach (or approaches) submitted to devops-cop for feedback/approval
- [x] Confirmation whether further communication is needed
