### ISSUE TITLE
Implement Cert Manager

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#60261]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
- [ ] Install cert manager
- [ ] Get service account with the VA's active directory

## Hypothesis or Bet
We need this so that we can manage our certificates, no workarounds 

We want to explore using cert manager for managing venafi certificates; but we need a service account to keep it from getting disabled if someone leaves the VA

## OKR
_Which Objective / Key Result does this epic push forward?_

## Definition of done
- [ ] We have an account with the VA's active directory 
- [ ] Cert manager is installed and functioning as expected,  

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by npeterson54** [comment]
This is done
