### ISSUE TITLE
Update Zoom information for collab cycle meetings

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#60267]
## User Story
As a governance team member, I want to see updated Zoom information in our team documentation so that I can paste the correct information into touchpoints that are scheduled while I am on-support. 

Assignee:
Peer Reviewer:

## Description
We recently updated scheduled collab cycle timeslots to better accomodate our PO Matt Dingee. Now we need to update the Zoom information in [this documentation](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2454585540/Zoom+information+for+Collab+Cycle+meetings) to match. 

## Impacted Artifacts
* [Zoom information for collab cycle meetings](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2454585540/Zoom+information+for+Collab+Cycle+meetings)

## Tasks
- [ ] Confirm with someone who holds Calendly administrative power (Allison or Shira) that these links are still good if bumped to new timeslot
- [ ] Consult our Google calendar or Calendly and update times listed on the Zoom information page to reflect new collab cycle timeslots.

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] The Zoom documentation reflects updated collab cycle touchpoints time slots

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
closing as no longer needed
