### ISSUE TITLE
R&D on Cilium vs Calico

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#60275]
## Description
Review pros, cons, features of CNI solutions?

## Tasks
- [ ] Lead a discussion about pros and cons of CNI options.
- [ ] Develop an implementation strategy.

## Acceptance Criteria
- [ ] Discussion occured and decision made.

## How to configure this issue
- [ ] _Attach a Milestone_
- [x] _Story points_
- [ ] _Sprint assigned if pulling into sprint_
- [x] _Epic assigned_
- [ ] _Team label assigned_

**Comment by ph-One** [comment]
Our current platform uses Calico, but we do not leverage Calico in any way. Going with Cilium out of comfort and the fact that it is rapidly become the default CNI for many offerings (Azure, GCP, EKS Anywhere, etc.)
