### ISSUE TITLE
Implement copay notification retry logic

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#60274]
## Issue Description
MCP notifications run on a daisy-chain of workers which collect data from external sources and then use that data to email veterans. Currently these workers will not retry if they fail which leaves us vulnerable to temporary outages from our external partners.
This ticket intends to implement retry logic on the relevant workers so that they can retry only on specific errors from external services.

#### **Case specific worker retry logic is demonstrated in [these docs](https://github.com/sidekiq/sidekiq/wiki/Error-Handling#configuration)**

- `McpNotificationEmailJob` relies on a response from `VAProfile::ContactInformation::Service#get_person` which has several possible failure cases (see va_profile/contact_information/service_spec for details)
  - 400: returns `nil` person
  - 404: returns `nil` person
  - 503: returns `Common::Exceptions::BackendServiceException`
- `NewStatementNotificationJob` relies on `MPI::Service#find_profile_by_edipi` and `#find_profile_by_facility` See CONNECTION_ERRORS constant and `mpi/service_spec.rb` for details.
    - Faraday::ConnectionFailed
    - Common::Client::Errors::ClientError
    - Common::Exceptions::GatewayTimeout
    - Breakers::OutageException
---
## Tasks
- [ ] Implement a `sidekiq_retry_in` block for `McpNotificationEmailJob` that only retries on 503s
- [ ] Implement a  `sidekiq_retry_in` block for `NewStatementNotificationJob` that only retries on relevant errors
- [ ] Generate new specs to corroborate this behavior

**Comment by HeatherRienks** [comment]
Per @kjsuarez , new Platform process requires a peer review from a team member before the PR can be reviewed by Platform BE Support. @ScottyRJames - thank you in advance for your help! This ticket will roll over.

cc: @Tom-Davis
