### ISSUE TITLE
4142 post-production intercept survey 

### ISSUE THREAD

**Issue by Nyanteea** [department-of-veterans-affairs/va.gov-team#60312]
## Issue Description

In lieu of a full research study/ usability test, gauge user reactions to 4142 [ no collab cycle] with an intercept survey launched through the Contact Center. 

---
## Tasks
- [ ] Talk with Contact Center about confirm custom intercept survey viability 
- [ ] Design survey 
- [ ] Submit a request for survey to CC

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alatempa24** [comment]
duplicate
