### ISSUE TITLE
[FE] My VA: Update various alerts and errors on My VA for consistency

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#60329]
## Background
In ticket #[36340](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36340), screenshots were gathered of various alerts and errors on My VA and guidance was provided from the platform team on which component should be used across the board. In #39066 Angela outlined which alerts needed updating and made the design and documentation updates. Now we need to make the updates in the code.

Guidance from Natalie Hill:

> I recommend the Warning alert -- either the standard full-width style or the background only style -- for the scenario you are describing. We can also talk about making it dismissible if you'd like that option.

According to this guidance, we would need to update the alerts in the code for the following scenarios:

- Notification dismissal error: Can’t dismiss notification ([use case documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/use-cases/cant-dismiss-notification.md))
- Claims API error: We can’t access your claims or appeals information ([FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/claims-and-appeals-FE-documentation.md))
- Health care appointments API error: We can’t access your appointment information ([FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/health-care-FE-documentation.md))
- Main user call fails but page is able to load (we can't tell if user has VA health care): We can’t access any health care information right now ([FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/health-care-FE-documentation.md))
- Debt or copay API error: We can’t access some of your financial information ([FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/outstanding-debts-FE-documentation.md#error-states))
- Payment history API error: We can’t access your payment history ([FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/benefit-payments-FE-documentation.md#error-states))

_Note: we can only proceed with this once the new notification component is released._

## Tasks
- [x] Update errors with indicated warning component
- [x] Update corresponding unit and e2e tests
- [x] Verify all tests pass
- [x] Move to validate and tag PM for validation in the comments
- [x] Remove feature flag to release once component is released

**Comment by aagosto90** [comment]
@allisonlu I updated the list of alerts in this ticket so it's accurate to what actually needs to be updated. Just wanted to clarify this ticket is just to update the style of the component from error to warning. No content is changing. I've noticed some annoying wonkiness with Sketch, like the spacing looks different in the Sketch links than it does in my Sketch desktop app which seems to just be a bug on their side so please just use the padding that's in the library component and ignore any weird spacing things like this for example. Thank you!
<img width="318" alt="Screenshot 2023-07-17 at 2 37 15 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/97965610/60967e4c-e704-4e29-9e17-8acf92f383d0">

**Comment by allisonlu** [comment]
@ajakabcin ready for validation on staging! Lmk if any of these instructions are unclear. I'm happy to jump on a call and screenshare 

## To validate

To validate these use cases, we want to block API requests for each section and make sure there are no more instances of the [error variation](https://design.va.gov/components/alert#error-alert), and instead we should see the [warning variation](https://design.va.gov/components/alert#warning-alert) of the `va-alert` web component.

For more thorough information on Network blocking, [see Adam's documentation](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/profile_errors.md#inspecting-communication)

1. Cmd + Opt + i to open Network tab in Chrome Devtools
2. Refresh to see all API calls

---

### Notification dismissal

* vets.gov.user+11@gmail.com

1. Right click `onsite_notifications` and click **Block request URL** 
2. Click the pencil icon and edit the URL to `staging-api.va.gov/v0/onsite_notifications/*`
3. Refresh page
4. Dismiss any notification
5. We should see the warning alert with headline "**Can't dismiss notification**"

![error-notification-after](https://github.com/department-of-veterans-affairs/vets-website/assets/8542413/405cbc55-82b6-4ee9-be44-ba9e259ef983) 

---

### Claims API error
* vets.gov.user+81@gmail.com

1. Right click `appeals` and click **Block request URL** 
2. Refresh page
4. We should see the warning alert with headline "**We can't access your claims or appeals information**"

![error-claims-after](https://github.com/department-of-veterans-affairs/vets-website/assets/8542413/c611dd1b-c340-4965-ae55-1826eb65e2e9)

---

### Health care appt API error

User has upcoming appointment and no unread messages:

* cecil.morgan@id.me

1. Right click `appointments?start-2023...` and click **Block request URL** 
2. You will see a long string after appointments:

![Screenshot 2023-08-14 at 1 17 32 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8542413/e1fc382f-c7b0-48e3-94e3-f900af3223c1)

4. Click the pencil icon and edit the URL to `staging-api.va.gov/vaos/v2/appointments*` 
![Screenshot 2023-08-14 at 1 17 52 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8542413/2e2c489a-eaee-4c8a-8fe8-5f612b46cbbb)

6. Refresh page
7. We should see the warning alert with headline "**We can't access your appointments information**"

 ![error-healthcare-no-msg-after](https://github.com/department-of-veterans-affairs/vets-website/assets/8542413/a15d6790-9593-4a47-a140-6ee4b15e7e97) 

---

### Main `/user/` call fails

* any user

1. Right click `user` and click **Block request URL** 
2. Refresh page
5. We should see [a full-page error](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/use-cases/system-cant-connect-to-MPI.md#my-va-use-case-theres-an-error-because-the-system-cant-connect-to-mpi)

---

### Debt/copay API error
* vets.gov.user+81@gmail.com

Debt API error only:
1. Right click `debts` and click **Block request URL** 
2. Refresh page
3. We should see the warning alert with headline "**We can't access some of your financial information.**" and **Learn about VA debt** CTA link (right-aligned)

Copay API error only:
1. Right click `medical_copays` and click **Block request URL** 
2. Refresh page
3. We should see the warning alert with headline "**We can't access some of your financial information.**"

![error-debts-after](https://github.com/department-of-veterans-affairs/vets-website/assets/8542413/4cf2dea0-911b-4403-b85a-a0e108808885) 

Both debts and copays API errors:
1. Right click `debts` and `medical_copays` and click **Block request URL** 
2. Refresh page
3. We should see the warning alert with headline "**We can't access some of your financial information.**" and **Learn about VA debt** CTA link (left-aligned)

---

### Payment history API error
* vets.gov.user+81@gmail.com

1. Right click `payment_history` and click **Block request URL** 
2. Refresh page
3. We should see the warning alert with headline "**We can't access your payment history**"

 ![error-payments-after](https://github.com/department-of-veterans-affairs/vets-website/assets/8542413/11f3632f-24d9-4f17-8c71-fc62a1a0ff73)

**Comment by ajakabcin** [comment]
Marking this is blocked so it's clear we're not waiting on any work from our team on this - we need the component to be released and then we can send theses off.

**Comment by ajakabcin** [comment]
Turned these updates on production for all users today (flag is `my_va_update_errors_warnings`)!
