### ISSUE TITLE
Landing Page/Intro Page Research Deck & Shareout 

### ISSUE THREAD

**Issue by Nyanteea** [department-of-veterans-affairs/va.gov-team#60322]
## Issue Description

Create a research deck and schedule shareout 

---
## Tasks
- [ ]  Create a deck / sheet summarizing research findings for share out

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alatempa24** [comment]
duplicate
