### ISSUE TITLE
VA Identity Dashboard <=> Sign in Service Account `/token` integration

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#60337]
# Description
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Sign-In%20Service/Components/Service_Accounts.md

# Tasks
- [x] set up `private_key_jwt` ServiceAccountConfig with SiS for localhost & development
- [x] create backend `account_access_token` method to call SiS account token route
- [x] store received access token in a 5-minute Redis cache
- [x] add method to allow other VA ID DB methods to obtain & pass the SiS account access token
