### ISSUE TITLE
BE | Profile | Direct Deposit | Error Code Updates

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#60348]
## Background
Updated error parsing logic to handle routing checksum error handling and added the following additional error codes:
- `cnp.payment.day.phone.number.invalid`
- `cnp.payment.day.area.number.invalid`
- `cnp.payment.night.phone.number.invalid`
- `cnp.payment.night.area.number.invalid`
- `cnp.payment.mailing.address.invalid`

## Tasks
- [x] Add error parsing
- [x] Add error code mapping
- [x] Add specs
- [x] Submit PR
  

## Acceptance Criteria
- [x] Verify deployed to staging

**Comment by tpharrison** [comment]
changes are in staging
