### ISSUE TITLE
VA Notify Dashboard - Data Updates

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#60344]
## Issue Description
VA Notify dashboard updates.  

---
## Tasks
- [x] Remove campaign name changes code (use names as they come over)
- [x] Include VANotify and vanotify (all cases) to code

## Acceptance Criteria
- [x] Dashboard updated
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
