### ISSUE TITLE
Remove info about claims extensions from COVID FAQs page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#60357]
## Issue Description
Compensation service alerted us that extensions to file claims due to the pandemic are no longer being given, so we need to remove the information from our [Coronavirus FAQs](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/) page. 

The accordion to remove is: What if I need to turn in or sign paperwork for my claim or appeal?

We're going to remove the entire accordion now so we don't have incorrect info on the site but will follow up if we should keep the info about signing paperwork. 

## Tasks
- [x] Remove accordion on English page
- [x] Remove accordion on Spanish page
- [x] Remove accordion on Tagalog page
- [x] Review and publish English page
- [x] Review and publish Spanish page
- [x] Review and publish Tagalog page

## Acceptance Criteria
- [x] Live FAQs pages no longer have accordion

**Comment by RLHecht** [comment]
@laurwill I just removed this accordion as well as 2 broken education links in the GI Bill accordion. Could you review and publish?

**Comment by laurwill** [comment]
Thanks @RLHecht ! I reviewed and published.

**Comment by RLHecht** [comment]
I removed the Spanish and Tagalog accordions and published. Moving to validate.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
