### ISSUE TITLE
[FE] My VA Audit UX: post-launch code cleanup (part 1)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#60360]
## Background
Following the audit of all My VA code, Derrick identified areas that need to be cleaned up and areas that need to be blown away entirely to prevent issues occurring in the future. 

**We need to update the following files:**
- Mocks
	- mocks/feature-toggles/index.js
	- mocks/server.js
- Components
	- DebtsV2.jsx
	- Dashboard.jsx
- e2e specs: `grep 'myVADashboardV2' src/applications/personalization/dashboard/tests/e2e` 
	- benefit-payments-v2-error-states.cypress.spec.js
	- outstanding-debts-v2.cypress.spec.js
	- claims-and-appeals-v2-lighthouse.cypress.spec.js
	- appointments-v2-rx-messaging.cypress.spec.js
	- in-progress-forms.cypress.spec.js
	- downtime.cypress.spec.js
	- benefit-payments-v2.cypress.spec.js
	- health-care-cerner.cypress.spec.js
	- appointments-v2-errors.cypress.spec.js
	- header-is-still-showing.cypress.spec.js
	- outstanding-debts-v2-error-states.cypress.spec.js
	- appointments-v2.cypress.spec.js
	- claims-and-appeals-v2.cypress.spec.js
	- messaging-error.cypress.spec.js
	- benefits-of-interest.cypress.spec.js
- Remove feature toggle `show_myva_dashboard_2_0` from platform/utilities/feature-toggles

## Tasks
- [ ] Update files outlined above
- [ ] Update tests and confirm passage
- [ ] Request validation from another dev

## Acceptance Criteria
- [ ] Files outlined above are updated 

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)_ FE dev
- _How can this work be validated?_  ...
