### ISSUE TITLE
[CST] Unexpected errors when Lighthouse returns HTML instead of JSON

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#60368]
## Background
When Lighthouse returns a 504 (Gateway timeout) they do so by sending us HTML instead of JSON. Our middleware chain expects that all responses returned will be in JSON format and when it encounters HTML it will throw an error. We need to make sure that receiving HTML instead of JSON is not an issue going forward. We should also make sure there is a spec in place that handles this scenario

## Error
**Disclaimer:** The request details below come from Sandbox, not Production
`#<Faraday::Error::ParsingError wrapped=#<Faraday::Error::ParsingError wrapped=#<JSON::ParserError:"unexpected token at '<html>\n<head><title>504 Gateway Time-out</title></head>\n<body>\n<center><h1>504 Gateway Time-out</h1></center>\n</body>\n</html>\n'">> response=#<Faraday::Response:0x000000011a702cc0 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:get @body="<html>\n<head><title>504 Gateway Time-out</title></head>\n<body>\n<center><h1>504 Gateway Time-out</h1></center>\n</body>\n</html>\n" @url=#<URI::HTTPS https://sandbox-api.va.gov/services/claims/v2/veterans/XXXXXXXXXVXXXXXX/claims> @request=#<Faraday::RequestOptions timeout=20, open_timeout=15> @request_headers={"Accept"=>"application/json", "Content-Type"=>"application/json", "User-Agent"=>"Vets.gov Agent", "Authorization"=>"Bearer fake_access_token"} @ssl=#<Faraday::SSLOptions verify=true> @response=#<Faraday::Response:0x000000011a702cc0 ...> @response_headers={"date"=>"Wed, 14 Jun 2023 20:36:12 GMT", "content-type"=>"text/html; charset=utf-8", "content-length"=>"75", "connection"=>"keep-alive", "x-ratelimit-remaining-minute"=>"59", "x-ratelimit-limit-minute"=>"60", "ratelimit-remaining"=>"59", "ratelimit-limit"=>"60", "ratelimit-reset"=>"50", "referrer-policy"=>"strict-origin-when-cross-origin", "vary"=>"Origin", "x-content-type-options"=>"nosniff", "x-download-options"=>"noopen", "x-frame-options"=>"SAMEORIGIN", "x-git-sha"=>"b20885293917fd081d24899644d2718d2ab4ccf9", "x-github-repository"=>"https://github.com/department-of-veterans-affairs/vets-api", "x-permitted-cross-domain-policies"=>"none", "x-request-id"=>"1d89bb4a-8e45-4101-8304-47c149d59868", "x-runtime"=>"1.297684", "x-xss-protection"=>"1; mode=block", "access-control-allow-origin"=>"*", "x-kong-upstream-latency"=>"1302", "x-kong-proxy-latency"=>"14", "via"=>"kong/3.0.2", "strict-transport-security"=>"max-age=31536000; includeSubDomains; preload"} @status=504>>>`

## Context
The best way to deal with this is by restricting the json request middleware to only be applied when the content-type is json

## Tasks
- [ ] Write new specs to make sure this case is covered by tests
- [ ] Update `ServiceException` class to handle 500 level errors

## Acceptance Criteria
- [ ] Specs are in place that cover 504 errors from Lighthouse
- [ ] `ServiceException` class can handle 500 level errors
