### ISSUE TITLE
Demo website footer changes

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#60379]
## Tasks
- [x] Create PPT to introduce demo. [Use this template](https://docs.google.com/presentation/d/1SUQp7RPCz8-hZx5jj3sW0ZeLx2x6MWVFhADbhZdONnA/edit?usp=sharing).

**Demo topic:** 

- [x] Demo the new Platform website "Help and Feedback" footer changes.

## Acceptance Criteria

- [x] Demo at the next scheduled demo
