### ISSUE TITLE
[FE] Notification Center: Create mock server for new app (scaffolding)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#60399]
## Background
To begin development of the notification center MVP we need to set up the scaffolding. After the application is set up in #60398, we'll need to create mock server for the new app.

## Tasks
- [x] create `/mocks/server.js` with [common API requests and responses](https://github.com/department-of-veterans-affairs/vets-website#running-a-mock-api-for-local-development)
- [x] model example data
  ```
   data: [
    {
      id: 'f9947b27-df3b-4b09-875c-7f76594d766d',
      type: 'onsite_notifications',
      attributes: {
        templateId,
        vaProfileId: '1273780',
        dismissed: false,
        createdAt: new Date(2023, 2, 28),
        updatedAt: new Date(2023, 3, 1),
      },
    },
  ],
  ```

## Acceptance Criteria
- [ ] mock server at `src/applications/personalization/notification-center/mocks/server.js` exists

(there won't be any data until https://github.com/department-of-veterans-affairs/va.gov-team/issues/60400 is merged)

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_  @dellerbie or @adamwhitlock1 
- _How can this work be validated?_ check that `src/applications/personalization/notification-center/mocks/server.js` exists

## Resources
- [Technical discovery: Notification Center MVP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/notification-center-mvp/engineering/technical-discovery.md#scaffolding)

**Comment by allisonlu** [comment]
Currently a WIP locally. This is blocked by https://github.com/department-of-veterans-affairs/va.gov-team/issues/60398 (on `vets-website`)

**Comment by allisonlu** [comment]
@dellerbie @adamwhitlock1 can you verify that you're able to spin up the mock server for notification-center?

1. check out [My-VA/allison/60399/nc-mvp/mock-server](https://github.com/department-of-veterans-affairs/vets-website/tree/My-VA/allison/60399/nc-mvp/mock-server)
2. confirm that `src/applications/personalization/notification-center/mocks/server.js` exists
3. (optional) run `yarn watch --env entry=notification-center` and `yarn mock-api --responses src/applications/personalization/notification-center/mocks/server.js`
