### ISSUE TITLE
Prep for mtg w/ Design Systems team

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#60394]
## Purpose
What is their role w.r.t. the Forms Library?

Use VFF mural and guide, amending for DST interview.

## Context
Current relationship of the Design Systems team and the Forms Library:
  -current team member (Harshil) really fixed a lot of accessibility bugs when he was on the Forms Spike Team.  now on DST.
  -Forms Library is currently supported by VFF team.
  -DST manages adding of new components to FL.  (need to understand this better)

-Matt thinks maybe there should be 2 libraries eventually.  
    -They could share components, but one be for teams that need more structure, and the other for more flexibility.
    -He says they’re getting close to being able to release the patterns for broad use, and point to FL components.

-Haven’t really explored best practices for patterns (maybe DST could do some research here), things like where a zip code should go.

## Tasks
- [x] Setup initial meeting
- [x] Draft interview guide
- [x] Setup [Mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1689040340318/d5d8400b3e473ce86c275f2e51be9e49e916cc07?sender=u4f7db1750f2355f805e60296)

## Acceptance Criteria
- [x] Meeting is scheduled  (Wednesday, 7/12 @ 12:30ET)
- [x] Guide is ready
- [x] Mural is ready
