### ISSUE TITLE
Present research findings at Office Hours 6/27

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#60406]
## Issue Description
The Platform website experience survey has now closed and the feedback has mostly been synthesized.

As a group, we have also come up with recommendations and incorporate them into our findings.

It is time to discuss the findings as a group and document any solutions, recommendations, create an affinity map and prioritize them.

This will help us incorporate this information for leadership.
---
## Tasks
- [x] Present research findings and recommendations at Office Hours on 6/27/23
- [x] Document any questions, comments or feedback from leadership

## Acceptance Criteria
- [x] Leadership will have the opportunity to listen to the Platform website survey findings
- [x] We will have documented questions, comments or feedback from leadership and create anything necessary as ZenHub tasks
