### ISSUE TITLE
[FE] Notification Center: Create mock data for new app (scaffolding)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#60400]
## Background
To begin development of the notification center MVP we need to set up the scaffolding. After the application is set up in #60398, and server is created in #60399 we'll need to create data for the new app.

## Tasks
- [x] consolidate `/v0/onsite_notifications` responses (from `/dashboard/` app) to reduce code redundancy
- [ ] tag @dellerbie or @adamwhitlock1 to validate when PR is merged 

## Acceptance Criteria
- [ ] on `main` branch, verify your local environment (http://localhost:3001/notification-center/) consumes data successfully after running `yarn watch --env entry=notificatoin-center` and `yarn mock-api --responses src/applications/personalization/notification-center/mocks/server.js`
- [ ] confirm that [PR is pushed to staging](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/)

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_  @dellerbie or @adamwhitlock1 
- _How can this work be validated?_ run command `yarn mock-api --responses src/applications/personalization/notification-center/mocks/server.js`

## Resources
- [Technical discovery: Notification Center MVP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/notification-center-mvp/engineering/technical-discovery.md#scaffolding)

**Comment by allisonlu** [comment]
I opened a couple cans of worms last week while working on this, but got those ironed out. So this is [currently in draft PR](https://github.com/department-of-veterans-affairs/vets-website/pull/24735), will mark ready for review when all the tests pass!

**Comment by allisonlu** [comment]
@dellerbie and @adamwhitlock1, can you help validate the AC above?

**Comment by adamwhitlock1** [comment]
So overall I can validate that the notification app is up in staging and that it hits the onsite_notifications endpoint. Also the mock server works as expected locally.

**Comment by adamwhitlock1** [comment]
@ajakabcin I saw that there are tickets for handling errors, and also to connect to the Redux state store for any applicable state that needs to be brought into this app. Has the work been scoped out yet for making this a 'authenticated only' app where it auto-redirects to the login if someone accesses the URL directly while not logged in?

**Comment by ajakabcin** [comment]
@adamwhitlock1 that's a great question, @allisonlu and @dellerbie would be better to answer though! Here's the [technical discovery doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/notification-center-mvp/engineering/technical-discovery.md) that outlines the work. 

Also, just so you know we're pausing on this work after this ticket for a bit.
