### ISSUE TITLE
HLR & Supplemental Claim | Setup radio button tracking

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#60431]
## Value Statement
**_As a_** researcher
**_I want to_** track the radio buttons on the Board Appeal digital form
**_So that_** the team can have a clearer picture of what decisions Veterans are making on the form

---
## Background Context

While working on https://github.com/department-of-veterans-affairs/va.gov-team/issues/58705 Robin also mentioned that none of the radios in the other two Decision Review forms are being tracked in GA. I believe there is an opportunity within this gap to get front-end data on Veterans decision we can further use to improve our forms.

## Acceptance Criteria
- [ ] Analytics can see the tracking code from the pages listed
- [ ] Tracking appears in GA

## Designs and Build Notes
Here is the data layer code to use:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/93597659/63508e18-a4e1-4904-b4fe-7c932b181ed3)

## Tasks
- [ ] Add button tracking code to HLR radios: benefit type (wizard), homeless, informal conference & informal conference times
- [ ] Add button tracking code to SC radios: benefit type (subtask), primary phone, include private evidence, include VA evidence & will upload evidence
- [ ] Setup new Analytics ticket to ensure the radio buttons are tracked

---
## Definition of Ready 
- [ ] We know which are web components vs. React components
- [ ] Properties added to each web component to enable it are identified

## Definition of Done
- [ ] Properties added to each web component to enable it
- [ ] Confirmed done by Michelle Dooley

**Comment by Mottie** [comment]
HLR wizard already had GA. When "Disability compensation claim" radio choice is made, this event fires:

```json
{
  "event": "howToWizard-formChange",
  "form-field-type": "form-radio-buttons",
  "form-field-label": "For what type of claim are you requesting a Higher-Level Review?",
  "form-field-value": "compensation"
}
```

And Supplemental Claim subtask fires this GA event:

```json
{
  "event": "howToWizard-formChange",
  "form-field-type": "form-radio-buttons",
  "form-field-label": "For what benefit type are you requesting a Supplemental Claim?",
  "form-field-value": "compensation"
}
```

**Comment by Mottie** [comment]
This work has been merged in, it should be available for testing in staging soon.

**Comment by saderagsdale** [comment]
@eileen-coforma let me know if this appears in GA as you want it to.

**Comment by eileen-coforma** [comment]
It's showing up in GA 👍
