### ISSUE TITLE
Create feature documentation

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#60437]
## Task Description
Create feature documentation from templates. This is a first pass that will only include:
- Overview
- User stories
- Requirements

Other sections will be filled out in separate tickets

## Notes and references
- [Business rules](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/engineering/vaos_business_rules.md)

## Working docs
- [Appointments feature reference](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/feature-reference)

## Acceptance Criteria
All feature reference docs have:
- [x] Been created from the [template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/feature-reference/template-new-vaos-feature.md)
- [x] Been linked from the main reference page
- [x] Includes updated sections
     - [x] Overview 
     - [x] User stories
     - [x] Requirements (copied from Business rules)
   
Pages to create:
- [x] All flows	Choose a type of care
- [x] All flows	Choose a type of sleep care
- [x] All flows	Choose a type of eye care
- [x] All flows	Choose VA or CC facility
- [x] All flows	Choose a type of audiology care
- [x] VA direct-schedule	Choose a location
- [x] VA direct-schedule	Cerner location redirect
- [x] VA direct-schedule	Choose a clinic
- [x] VA direct-schedule	Choose a preferred date
- [x] VA direct-schedule	Reason for appointment
- [x] VA direct-schedule	Confirm contact information
- [x] VA direct-schedule	Review and submit
- [x] VA request	Choose a day and time
- [x] VA request	Reason for appointment
- [x] VA request	Method of attendance
- [x] VA request	Confirm contact information
- [x] VA request	Review and submit
- [x] CC request	Choose a day and time
- [x] CC request	Closest city
- [x] CC request	Choose a provider
- [x] CC request	Choose a preferred language
- [x] CC request	Reason for appointment
- [x] CC request	Confirm contact information
- [x] CC request	Review and submit

**Comment by melissa-lefevre** [comment]
Finished this work. Closing out the ticket.
