### ISSUE TITLE
[FE] Notification Center: Error handling (midstack)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#60439]
## Background
Once the application for the notification center is established and we have mock data and servers established we need to make sure actions handle errors properly. 

## Tasks
- [ ] Make sure actions handle 4xx and 5xx errors
- [ ] Render errors on FE (see design in resources section)
- [ ] Unit tests for errors

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ 
- _How can this work be validated?_

## Resources
- [Technical discovery: Notification Center MVP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/notification-center-mvp/engineering/technical-discovery.md#mid-stack)
- [Error handling design ](https://www.sketch.com/s/1cc4cb25-7de4-492c-bb91-edef871b2a89/a/9l5vKrx)

**Comment by ajakabcin** [comment]
Closing out - team ultimately decided not to pursue this work
