### ISSUE TITLE
[FE] Notification Center: Component validation (midstack)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#60438]
## Background
Once the application for the notification center is established and we have mock data and servers established we need to make sure the notification component is pulling in the correct data from the API call. 

## Tasks
- [ ] Coordinate with Derrick on execution plan
- [ ] Make sure Notification component is pulling in correct data from API call

## Acceptance Criteria
- [ ] API call is functioning properly and pulling in test data (not rendering yet)

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ @allisonlu 
- _How can this work be validated?_ ...

## Resources
- [Technical discovery: Notification Center MVP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/notification-center-mvp/engineering/technical-discovery.md#mid-stack)

**Comment by ajakabcin** [comment]
Closing out - team ultimately decided not to pursue this work
