### ISSUE TITLE
Transport Schemas to Central `vets-json-schema` Repo

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#6043]
## Goal
Once schemas are complete in the `vets-website` file(s), they need to be moved into the `vets-json-schema` repo.  This was done originally to expedite development but they need to live in their eventual home.

## Considerations
- Once transport has been completed and the schema is built into `dist`, and pull request into `vets-website` will need to be made that updates the commit hash for `vets-json-schema` referenced in `vets-website/package.json`. This same pull request will also need to update the import for the form itself in `config/form.js`. The pull request for `vets-website` should have its own ticket.
- Might be best to see that FE and submission state is hunky dory before having to open this again
- Move this to before e2e test and ensure there has been a conversation between FE and BE

## Tasks
- [ ] Move schemas from `vets-website` to `vets-json-schema`
- [ ] Implement updates as needed
- [ ] run `yarn build` to build the schema and add it to the `dist/` directory.

## Acceptance Criteria
- [ ] Schemas have been moved and function as expected.
