### ISSUE TITLE
[FE] Notification Center: Incorporate component on NC page (build)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#60440]
## Background
Once foundation of notification center is stood up we need to bring in the notification component and make any necessary style tweaks to work with the page. We'll use the new notification component our team built in May/June 2023.

## Tasks
- [ ] Populate with notification component (no pagination)
- [ ] Make any style tweaks

## Acceptance Criteria
- [ ] NC mvp is visible on staging (without pagination functionality) with test notifications populated using the component

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ @aagosto90 
- _How can this work be validated?_ compare to design specs

## Resources
- [Technical discovery: Notification Center MVP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/notification-center-mvp/engineering/technical-discovery.md#build)

**Comment by ajakabcin** [comment]
Closing out - team ultimately decided not to pursue this work
