### ISSUE TITLE
[FE] Notification Center: Implement/Confirm GA event tags (build)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#60447]
## Background
As part of build/implementation we need to incorporate GA event tags. We'll be using a lot of components so there shouldn't be a lot of new tags to be added but we'll need to confirm. 

Prerequisite: PM to submit Analytics request

## Tasks
- [ ] Consult with Analytics team to see if there are any tags not already included via components that we need
- [ ] Implement additional tags per recommendation from Analytics team
- [ ] Send to Analytics team for QA

## Acceptance Criteria
- [ ] Event tags are implemented and tracking 

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Analytics team member
- _How can this work be validated?_

## Resources
- [Technical discovery: Notification Center MVP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/notification-center-mvp/engineering/technical-discovery.md#build)

**Comment by ajakabcin** [comment]
Closing out - team ultimately decided not to pursue this work
