### ISSUE TITLE
[Design] Notification Center: Use case documentation

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#60448]
## Background
Once notification center mvp is launched we'll need to update our use case documentation for the Notifications section on My VA and create use case documentation for the notification center. 

Open question: Should there be a new folder for "Notification Center Use Cases" in GH or if they should be part of the existing "Onsite Notifications Use Cases" [folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications/use-cases).

## Tasks
- [ ] Update [use case documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications/use-cases) and user flows for Notifications section on My VA to reflect changes we made to conditional state (addition of ever-present empty state for LOA3 users)
- [ ] Create use case documentation and link user flows for notification center 

## Acceptance Criteria
- [ ] Use case documentation/flows is updated for Notifications to reflect changes to conditional state
- [ ] Use case documentation exists for notification center

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_ Any team member
- _How can this work be validated?_ Confirm documentation is updated/exists per AC outlined above.

**Comment by ajakabcin** [comment]
Closing out - team ultimately decided not to pursue this work
