### ISSUE TITLE
[FE] Notification Center: Pagination (build)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#60442]
## Background
Once foundation of notification center is established the page will need to be handle a large volume of notifications via pagination. We'll use the [pagination](https://design.va.gov/components/pagination) component from the design system library.

## Tasks
- [ ] Discuss with Angela what the limit of notifications per page should be
- [ ] Set up pagination using component.

## Acceptance Criteria
- [ ] Pagination implemented on staging using component with 10 notification limit per page (confirm with Angela)

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ @aagosto90 and @dellerbie 
- _How can this work be validated?_

## Resources
- [Technical discovery: Notification Center MVP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/notification-center-mvp/engineering/technical-discovery.md#build)
- [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/notification-center-mvp/FE-documentation/notification-center-mvp-FE-documentation.md)

**Comment by ajakabcin** [comment]
Closing out - team ultimately decided not to pursue this work
