### ISSUE TITLE
Share new process with Platform Orientation hosts

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#60451]
## User Story
As a Governance team member, I want to share the new operational process with the orientation hosts so they are have the opportunity to ask questions and share concerns prior to launch.

Assignee: @CherylEvans 
Peer Reviewer: @briandeconinck 

## Description
We have defined a new operational process for hosting and recording orientation sessions. We must share it with the other Platform orientation hosts so they are knowledgeable of the new process, but also so they have the opportunity to ask questions and share concerns, if any.

## Tasks
- [x] Schedule sync for all orientation hosts and Zoom hosts
- [x] Present to them the guidance and the new process
   - maybe a demo? 
- [x] Give Platform orientation hosts ~2 days to review new materials and share concerns
- [x] Share links with orientation hosts so they know where to find this guidance in the future
- [x] Inform hosts that we will kickoff this new process on July 5 with the back-end orientation session

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Platform orientation hosts are prepared and ready for recording orientation sessions

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
@shiragoodman @briandeconinck Brian and I are syncing tomorrow to discuss.  Once we do, I will send the invitation to the PO hosts. I will send the invite before the end of the day tomorrow.  I wanted to schedule the meeting/demo when I had answers to the questions needed to complete the tasks.

**Comment by CherylEvans** [comment]
@shiragoodman @briandeconinck I will send the invitation today.  There is no reason to wait.

**Comment by CherylEvans** [comment]
@shiragoodman @briandeconinck I would like to send links to the new documentation in the email invitation so hosts can have some time to review our processes before the Demo.  Thoughts?

**Comment by shiragoodman** [comment]
Thank you for scheduling. We can include links to the documentation them once it's ready. 

also, Curt Bonade let me know he can't make it on Friday. He asked that we record, and I think that's a good idea.

**Comment by CherylEvans** [comment]
@shiragoodman @briandeconinck 

- Sync for all orientation hosts and Zoom hosts scheduled Friday, June 30, from 3:00 PM to 3:30 PM ET.
- Brian will host the meeting.
- The meeting is 30 minutes long.
- Brian and Cheryl's sync is scheduled for Wednesday, June 28, from 3:00 PM to 3:30 PM ET. We will discuss the strategy for Friday's meeting.

**Comment by shiragoodman** [comment]
FYI - since we had lower turnout than expected, I posted a[ message to Slack ](https://dsva.slack.com/archives/CJRQ85PQB/p1688157749921449)communicating the new process to Orientation hosts. 

@CherylEvans this ticket can be closed.
