### ISSUE TITLE
Prepare Forms Research Interview Mural board

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#60463]
## Purpose
Prep [Mural board](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1687284845068/6b1ef33b996321d598c00e5ac8f879cb5973d3cf?sender=u9ea6bd3ca12795949b606150) for Interview workshop(s).  We want to capture responses to questions and then be able to shape these into a perceived process w/i the same board if possible.

## Tasks
- [x] Create sections for questions and responses/notes
- [x] Create space for translating notes to phases / process determination
- [x] Pilot test (scheduled with Dana on 6/23)
- [x] Make edits based on pilot test (Dan)

## Acceptance Criteria
- [x] Mural is ready for research to begin
