### ISSUE TITLE
Request new Domo datapoint for Epic #

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#60469]
## User Story
As a governance team member, I want to be able to access the Epic # for staging review tickets, so that I can understand which issue tickets roll up together into a single review instance. This will allow me to analyze data about staging reviews (not just individual tickets). 

Assignee: @it-harrison 
Peer Reviewer: @allison0034 

## Description
In ticket #59621 we realized that building out our Domo dashboard to accommodate trends (showing data over time) would be more meaningful if we reported not just on common violations of individual tickets, but overall staging reviews themselves (what is the average # of issues at a staging review? what about launch-blocking issues? is this trending up or down?). We also realized that time-based graphs are potentially problematic because the # of staging reviews in a given period of time can fluctuate, so there may be spikes/noise in the data that doesn't reflect anything in particular, just the higher or lower frequency of staging reviews across that time frame. Being able to display data across a count of reviews (e.g. average # of issues over the last 15 staging reviews) could eliminate distracting spikes. 

We would like to create a new ticket with the Analytics & Insights team to see if we can pull the Epic # from individual staging review tickets to be able to use this data. If that is not possible, the assignee will need to work with that team to figure out another way we can get at this data. Do we add a label with the collab cycle ticket #? Something else?

## Impacted Artifacts
* Domo BigQuery dataset

## Tasks
- [ ] Create ticket for Analytics & Insights team
- [ ] Meet with them if necessary to explain what we are looking for / if Epic # cannot be pulled out of data, what other solutions could accomplish this ask?
   - Note: if there is no other solution for Epic # (that doesn't involve us creating a unique label for each SR), then we will put this on pause and return to at a later date.
- [ ] Analytics & Insights has a plan and timeline for providing this data to governance team

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Governance team has articulated a plan with Analytics & Insights and has a timeline for receiving this data

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
[Analytics ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60528) created to address this issue.

**Comment by it-harrison** [comment]
[Analytics internal ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60605) has been created

**Comment by shiragoodman** [comment]
@sterkenburgsara @it-harrison I checked in with Michelle from A&I yesterday and she shared that YES this request is feasible, but similar to the CMS repo request, A&I is dependent on help from the backend CoP. This may take a while.

**Comment by rjohnson2011** [comment]
@sterkenburgsara Can you provide an example of a ticket where the Epic # is stored please?

**Comment by sterkenburgsara** [comment]
@rjohnson2011 yes, sorry! The epics are _linked_ to each ticket. [Here is an example ticket](https://app.zenhub.com/workspaces/collaboration-cycle-reviews-61d89e9e5f4c120011a0ad37/issues/gh/department-of-veterans-affairs/va.gov-team/60736) from our team and a screenshot to display how/where these are linked: 

<img width="1181" alt="Screenshot 2023-07-06 at 10 52 12 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/115033532/ff25c97c-a226-4dd1-a26f-25145c425857">

**Comment by it-harrison** [comment]
Talked to Michelle today. Analytics is going to work on merging the Big Query Dataset Ryan created into the existing Big Query data set that is pulled into Domo.

**Comment by shiragoodman** [comment]
@rjohnson2011 do you have everything you need for this?

**Comment by rjohnson2011** [comment]
Yes! I will look into the feasibility of this when I have additional bandwidth.

**Comment by sterkenburgsara** [comment]
@rjohnson2011 Just so this is noted somewhere, it is possible that our tickets could have multiple attached/linked epics. We only need the epic ID # for the one that begins with "Collaboration Cycle...."

**Comment by laineymajor** [comment]
Ryan to sync with Shira about options re data.

**Comment by shiragoodman** [comment]
@laineymajor @rjohnson2011 please connect with @it-harrison if you have questions about what changes we need made to our query. This ticket takes priority over #54671

**Comment by rjohnson2011** [comment]
@shiragoodman @it-harrison The "Epic" name is not able to be pulled since it's only on Zenhub and not part of Github's API (which is what we're using to pull issue data and populate the table from). 
The epic data is[ available here on the Zenhub ticket](https://app.zenhub.com/workspaces/collaboration-cycle-reviews-61d89e9e5f4c120011a0ad37/issues/gh/department-of-veterans-affairs/va.gov-team/60736). Yet [on the corresponding Github ticket, it is not available](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60736).

Is it possible to add to the "Labels" section in Github any information that would be corresponding to an Epic? From there, information can be sorted and parsed.

**Comment by rjohnson2011** [comment]
I understand the difficulty it would be to maintain using labels and am looking into other available options. Making calls to Zenhub would probably be best to avoid - for one there are 14k issues that are pulled to populate the BigQuery table. They're pulled in batches of 100 using Github API yet Zenhub API would require an individual request for each. Also, there might need to be 2 requests for each issue, since one would need to determine the appropriate Zenhub issue number for a Github issue, then another call to determine the Epic number for that Zenhub issue. That would be almost 30k calls which are limited to 100 requests per minute on Zenhub's API - in short it would take a minimum of 5 hours to complete. Also, it would require a whole new Zenhub ingestion mechanism, which hasn't been built out yet.

Pivoting to Github projects would keep this in the Github API ecosystem! Even better, is it possible to use "Milestone"? I see Milestone on the API query we're using. That would be the most turnkey solution.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/72466113/d557dd07-90cd-4971-9c4c-28f1010b14b9)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/72466113/92eb414e-0596-4de3-910c-e2faf9823336)

**Comment by shiragoodman** [comment]
ok quick question @rjohnson2011 

Here is a [GH Projects board ](https://github.com/orgs/department-of-veterans-affairs/projects/998/views/1)I've been messing with. This is NOT the same data set that we're currently asking you to pull in, however, if we did transition to Gh Projects, would we be able to pull the custom fields? For example, "Kickoff" is a custom field I made up.. If I wanted that data pulled into Domo, could it be done?

**Comment by rjohnson2011** [comment]
If the "Milestone" indicator is at all possible that would the most preferable solution. The way the existing infrastructure works, and the BigQuery table is being populated is by listing all "Issues" in a particular Github repo. This request pulls in 100x issues at a time, which is necessary because there's 14k issues. Within the response data of each of these issues is information like the title of the ticket, assignee, etc. Associated project data is not there, but Milestone data is (here's an overview from the [API showing Milestones in the Issues sub-bullet point](https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28))
<img width="338" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72466113/85f82e52-1139-48a2-ab7b-f2473d7e0bab">

The project route would require a separate request to a Projects endpoint and would involve a total rewrite of logic to cross reference and parse data from that project based on the Github issue number. It would require populating the table using Issues then looping over all 14k issues and checking if they're associated in a project (or something similar). It would take a great deal of effort to get this functional. I think it is possible to pull a custom Project field but it would require a square one rewrite of the ingestion code for the reasons above, basically all rows would have to be looped over to check for an associated project. Domo has a Github connector, although I am not sure if that pulls in Projects information, I did a bit of Google searching but it was not clear. 

"Milestones" or "Labels" can straightforwardly be pulled in and parsed with our existing infrastructure. I would recommend one of these approaches if at all possible.

**Comment by it-harrison** [comment]
@shiragoodman @rjohnson2011 I can look into writing a script to add epic number as milestone to old issues

**Comment by shiragoodman** [comment]
Thanks @rjohnson2011. I think we will want to research our options before making a decision.

@it-harrison let's chat at our Weekly Initiative meeting today

**Comment by shiragoodman** [comment]
Hey @rjohnson2011 . We chatted just now and I _think_ we could make milestones work.. however we will have to do some work on our end to get all of the tickets in need of a milestone assigned a milestone. As well as create all those milestones.

We will close this ticket out for now and will created another ticket for the BE COP when we're ready to move forward. Thank you! This has been super helpful.

**Comment by rjohnson2011** [comment]
@shiragoodman I'm glad this was helpful! Please let me know if I can assist in any other way.

**Comment by laineymajor** [comment]
Thanks for jumping on this ticket Ryan!
