### ISSUE TITLE
Implement minimization of copay notification external service dependencies

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#60466]
## Issue Description
_This ticket is the result of investigation performed in #59892_
#### Current functionality
 Currently the MCP notification workflow (`NewStatementNotificationJob` and `McpNotificationEmailJob`) works like this:
```
Copay statement => (EDIPI or facility/Vista ID) => MPI API call => [vet360 id, ICN] => VAProfile API call => email address
```
When processing thousands of statements, making no less than 2 API calls per statement can impact performance. Whats more, an email address for the veteran in question is already stored locally in vets-api if they've ever logged into VA.gov.

Changes are to be made to `NewStatementNotificationJob` and `McpNotificationEmailJob` so that they only make requests to external APIs when necessary.

#### Insights
vets-api permanently stores the related email address of a veteran when they login to the system. 
Below are examples of sourcing a usable email address from EDIPI and ICN
```
# find email from ICN
UserAccount.find_by(icn: "some icn").user_verifications.map{|ver| ver.user_credential_email.credential_email}

# find email via EDIPI
UserVerification.find_by(dslogon_uuid: "some edipi").user_credential_email.credential_email
```
---
## Tasks
- [ ] Create a long lived Redis model that stores values for icn, edipi, vet360, facility_number and vista_id _(maybe call it IdentifierIndex)_
- [ ] Edit `NewStatementNotificationJob` so that- 
  - [ ] if edipi provided, check for an edipi related UserVerification before hitting MPI, use this address if found
  - [ ] if facility/vista are provided, check for an existing IdentifierIndex
    - [ ] if found try to source email from related ICN/EDIPI, use if found, forgoing the MPI call
  - [ ] In the event that MPI must be called, upsert the identifiers we now possess into an IdentifierIndex
- [ ] Edit `McpNotificationEmailJob` to forgo hitting VAProfile API if an email is provided

## Acceptance Criteria
- [ ] Existing specs green
- [ ] New specs demonstrating the effected workers use of UserVerification and IdentifierIndex models
---
#### Unknowns
Are there users that have UserVerifications that don't rely on edipi or icn? Is there a complete list of VA identifiers? Does the MPI profile contain other identifiers that hook into UserVerifications which we can store in our new IdentifierIndex model?
