### ISSUE TITLE
[FE][TECH DEBT] - fix eslint disabled on platform imports

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#60472]
## Summary
We are using `eslint-disable-next-line import/no-unresolved` on a lot of imports in the check-in applications where we don't need to. See this thread for how to clean them up: https://dsva.slack.com/archives/C02G6AB3ZRS/p1686926459397059

## Tasks
- [ ] [FE] Clean up eslint disabling of import/no-unresolved

## Acceptance Criteria
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Prod validation:
  - [x] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
