### ISSUE TITLE
BE | Profile | Direct Deposit | Handle 504 HTML Responses

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#60477]
## Background
It was brought to my attention by another team that Lighthouse returns HTML, not JSON for `504` errors.

The benefits claims team has made a fix that we can use for direct deposit.  See [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/13020/files#diff-835f2d5f0fe91fd9d5b8ec545423b47d145bc4b1f51204a454868066ca187024) for details.

## Tasks
- [x] Add code to handle 504 responses correctly.
- [ ] Add specs to test 504 responses.

## Acceptance Criteria
- [ ] Code Review completed
