### ISSUE TITLE
Document Data Procedures

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/va.gov-team#60473]
## Issue Description
To position ourselves for the new contract, data procedures need to be documented in Confluence.

---
## Tasks
Document the following
- [x] Python GFE setup
- [x] Weekly Medallia DOMO update
- [x] Monthly Medallia DOMO update
- [x] Performance Dashboard DOMO update
- [x] VA411 SalesForce Report
- [x] VA411 SalesForce DOMO update

## Acceptance Criteria
- [x] Has all the above reporting updates been documented?
- [x] Has the document been shared?
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
@ATMiddleton here's that ticket we were discussing the other day.

**Comment by ianMcCullough-ob** [comment]
[Links for all the resources](https://vfs.atlassian.net/wiki/spaces/Contact/pages/2688483415/CC+Data+Resources)
