### ISSUE TITLE
[SW] Create mobile-friendly eFSR mockups to test in Streamlined Waiver Transparency Study

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#60485]
## Issue Description

We're working through the streamlined waiver draft copy, and updated review page designs, and we will be needing mobile-friendly mockups of at minimum 2 user flows ( 1) automatic waiver decision and 2) manual FSR ). 

 The pages we will need are:
- Updated intro page [evaluate new SW content]
- First sections all will see (work history, income, assets)
- Additional sections 
- Updated review page [evaluate new review page]
- Updated review page editing capability [evaluate editing capability]
- Confirmation page [evaluate new SW content]

---
## Tasks
- [x] Updated intro page [evaluate new SW content]
- [x] First sections all will see (work history, income, assets)
- [x] Additional sections
- [x] Updated review page [evaluate new review page]
- [x] Updated review page editing capability [evaluate editing capability]
- [x] Confirmation page [evaluate new SW content]

## Acceptance Criteria
- [x] Mockups have been created
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mgleo** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VSA---Debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/60485?planning-poker) with Zenhub @josephrlee

**Comment by HeatherRienks** [comment]
Rolling over into S103; needs additional work.

**Comment by HeatherRienks** [comment]
Ticket #61254 created as a follow up ticket

**Comment by josephrlee** [comment]
This is nearly done, I just need to create an updated review page showing some of the editing states.

**Comment by HeatherRienks** [comment]
Work is done!
