### ISSUE TITLE
BE | Profile | Direct Deposit | Test Lighthouse production key

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#60483]
## Background
The benefits claims team (Jerek Shoemaker) has already configured a direct deposit key pair for Lighthouse's production environment.  The key needs to tested to ensure its workin propertly.

## Tasks
- [x] Create cURL command to test Production
- [x] Test with Jerek Shoemaker

## Acceptance Criteria
- [x] Able to use keys to connect against production env.

**Comment by tpharrison** [comment]
Waiting on Lighthouse approval of production keys.
