### ISSUE TITLE
BE | Profile | Direct Deposit | Determine Direct Deposit Traffic per minute

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#60481]
## Background
It was determined that multiple teams will be sharing the same token and client id for making request to the LH direct deposit API.  Currently, there is a rate limit of 60 requests per minute.

Determine direct deposit traffic usage for EVSS direct deposit endpoints. 

## Tasks
- [ ] Analyze Datadog stats to determine highest traffic peaks per minute.
- [ ] Make request to Lighthouse to increase rate limit to accommodate anticipated traffic peaks.

## Acceptance Criteria
- [ ] Lighthouse raises rate limit to requested threshold.

**Comment by mtcA6** [comment]
Is there enough traffic running through the new endpoint to be able to accurately tell what the volume will be?

I thought we and answered the volume question w/ [BE | Profile | Direct Deposit | Increase Rate Limit #55294](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55294) (side note from this ticket, what's the PPIU endpoint? is that the old enpoint?) 

Can we pre-emptively request an increase to the rate limit without showing the volumes since it seems like there are a number of variables in flux?

**Comment by tpharrison** [comment]
Yes - when I last checked, I was only looking at Profile traffic.  Because of recent changes, I now need to look at total traffic (not just from Profile, but from other areas of the application, and VA mobile), so the traffic is going to be higher and we'll most likely need an increase to the rate limit.

**Comment by mtcA6** [comment]
@tpharrison
So according to Jerek, the rate limit is per consumer (client ID) is 12,000 and not 60
