### ISSUE TITLE
Mocked Auth Usability Testing

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#60480]
#### Mocked Auth Usability Testing
Usability test the Mocked Auth product with VFS users to help develop the product backlog.

Mocked auth allows devs to iterate and to work on their code in a more local way without actually having to sign into an authorized account, which can go down or cause issues. This simplifies the development for dev who aren't in the Identity realm, and this allows them to work even without internet connection since there are no "external calls". This also makes it more consistent

#### Tasks
- [x] pilot/study walk through
   - [x] schedule pilot with Core Team engineer
   - [x] conduct pilot
- [x] recruit 3-4 developers
- [x] conduct sessions ([session notes in Mural](https://app.mural.co/t/oddballinternal7486/m/oddballinternal7486/1687797193913/7b196a224beebe023ddd7c71fa303cd335a571e4?sender=u6c46f747a0483ea836054483))
- [x] analyze results
- [x] draft findings report
- [x] present findings
- [x] add tickets to backlog if needed

##### Questions/ideas 
- first page
   - make the front page link more prominent (a CTA link)
   - should we clarify any language in the GH documentation
   - will folks even read it?
   - feedback button doesn't work - remove? or who gets that?
- Select profile page 
   - "what is modded auth" link on profile select page needs to be corrected to the documentation
- who else might use this?
   - PO, testers, Collab Cycle, etc could potentially all look over here
   - note: everything happens here is mock, so a form doesn't actually submit out and get a response for example where staging environment does actually reach out.
- known bugs
   - like all accounts, mock accounts need to have the mocked credential and the mocked MPI record. The error message means the MPI record are not found - mocked auth fails in this case.
      - pre-check after selects a profile an warning if MPI data is missing
      - have flag or info when an account isn't working
      - only allow new mock users that work
   - "code in state is not valid" because you need to go back to the start page after a failed attempt like the state above
      - otherwise stuck in a perpetual state

#### Acceptance Criteria
- [ ] Reviewed by UX Team
- [ ] Reviewed by PMs
- [ ] Findings have been shared and items added to backlog
- [ ] Put published research in GH

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by charlye-bluetiger** [comment]
2 of 3 sessions conducted.  3rd session to be rescheduled prior to starting on synthesis.  A journey map could be an artifact created to build a shared understanding of mocked authentication.

**Comment by joeniquette** [comment]
planning to wrap up this week

**Comment by APorter-Clarity** [comment]
Take a look at the product brief (dig a little deeper on creating user)
Work with Trevor and Joe (input on next steps)

**Comment by APorter-Clarity** [comment]
https://docs.google.com/document/d/1784ZG2Zii9C3S86k5Ep-qRpb8caaMpe9f6n8JUx1JQ4/edit

**Comment by APorter-Clarity** [comment]
Please see final findings report 

[Findings Report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Research/2023-06%20Mocked%20Authentication/Mocked%20Authentication%20research%20findings.md)
