### ISSUE TITLE
Finalize conversation guide for VFF team research

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#60499]
## Purpose
Prep Mural board for Interview workshop(s)

## Tasks
- [ ] Create space for questions and notes
- [ ] Create space for phases and process determination

## Acceptance Criteria
- [ ] Guide is ready for research to begin
