### ISSUE TITLE
End-to-End Tests for "Submit 686" (Part 1)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#6049]
## Goal
Once the 686 application is code complete, e2e tests need to be added to ensure the form behaves as expected. This means writing e2e tests for each distinct workflow, and any combinations of workflows. Combinations don't have to be exhaustive, but should be diverse enough to cover as many realistic scenarios as pragmatically possible. 

## Considerations
- This issue may be a big ticket item that has a lot involved. More to come.
- 8 distinct **combinations** of workflows this will be a time intensive monster.
  - **Part 1:** spouse, child
  - **Part 2:** child, report a divorce
  - **Part 3:** spouse, report a divorce
  - **Part 4:** spouse, child, report a divorce
  - **Part 5:** add child, add school
  - **Part 6:** full form 
 - Check in with Nick Sullivan on how coverage could play out

## Tasks
- [x] create e2e tests that simulate each workflow a user may wish to complete.
- [x] create e2e tests that simulate a combination of workflows a user may wish to complete with the same form.

## Acceptance Criteria
- [ ] All necessary e2e tests have been created and pass correctly.

**Comment by micahchiang** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-website/pull/12225
