### ISSUE TITLE
Clean up unused resources in PE

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#60504]
# Description

In the course of troubleshooting, and quickly porting code from other projects for re-use, we accumulated some tech debt with regards to allocating resources in the PE that we would not really be using. We need to remove our use of these resources in PEs.

# Tasks
- [x] Reduce the number of replicas per preview environment to 1 for all resources
- [x] Remove extraneous containers from the front-end pod

# Acceptance Criteria
- [ ] Each preview environment has a single replica for each resource it uses
- [ ] The extra containers previously present in front-end pods have been removed

**Comment by pjhill** [comment]
PR here -- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2016
