### ISSUE TITLE
[Research] My VA Bene app drafts: Documentation audit/updates

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#60510]
## Background
Some recent inquiries ([inquiry 1](https://dsva.slack.com/archives/C909ZG2BB/p1686065298385539), [inquiry 2](https://dsva.slack.com/archives/C909ZG2BB/p1686599083929699)) from other teams regarding the Benefit application drafts section on My VA has raised some questions on the team as to when, why and how different forms should appear there. At the most basic level, any form that is started and saved on VA.gov should appear there, however it's clear that is not technically the case, as [these](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/helpers.jsx#L123-L147) are the only forms that appear in that section. 

We need to review our documentation and update it so that we have an accurate source of truth for which forms appear there and how. For example, I believe it requires the form to have SiP (Save in Progress) enabled, and we should state that in our docs if we don't already. (Documentation on that process [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-set-up-save-in-progress-si)).  We don't need to update any old documentation, but we should add to our most recent FE documentation to clearly state when and how forms appear in this section.

**Open question:** should documentation like this live in a place where it can be referenced more easily and be considered "evergreen". For example, with the [use cases](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/use-cases/benefit-application-drafts-use-cases.md) for that section, as that information is relevant to the feature in perpetuity and not _just_ for that iteration.

## Tasks
- [x] Consult with developer (Adam, but bring Allison too) to point you in the right direction, validate findings and review summary of how this logic works 
- [x] Review documentation for technical rules regarding when and how forms appear on My VA in the Benefit application drafts section (docs linked in Resources section)
- [x] Update [most recent FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/applications-FE-documentation.md) to state when and how forms appear in that section

## Acceptance Criteria
- [x] Most recent FE documentation is updated with explanation
- [x] (Possibly) Use cases are updated to include this information

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ PM
- _How can this work be validated?_ review updated documentation in github

## Resources
- [Backend doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/my-va/saved_applications/backend_documentation.md) - it looks like we only pull in health apps? Confirm with Derrick if this is correct
- [Old FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/apply-for-benefits.md) from 2.0 redesign - is there anything here that explains the rules for docs appearing in this section?
- [Find a form](https://www.va.gov/find-forms/)

**Comment by aagosto90** [comment]
[FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/applications-FE-documentation.md#how-does-an-application-in-progress-end-up-showing-in-a-card-on-my-va) and [use case documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/use-cases/benefit-application-drafts-use-cases.md) for benefit application drafts has been updated to link to Platform documentation about the requirements for a card to appear on My VA.

@ajakabcin In meeting with Adam on 7/31 to validate this documentation, he said there might be a way to streamline this further by leveraging an API so that forms that are saved in progress can automatically be shown on My VA instead of requiring extra work for other teams' developers. He thinks it's worth creating a discovery ticket for Derrick and Tom to investigate whether this is possible. They can ask Adam and/or Allison for more context on that if needed.
