### ISSUE TITLE
BE | Profile | Military Service History | Add mock responses

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#60531]
## Background
Responses from `/v0/profile/service_history` are still configured to eMIS mocks, which is causing errors.  Add/Update mock responses for this endpoint to use `VAProfile::MilitaryPersonnel::Service` for user `vets.gov.user+228@gmail.com`.

## Tasks
- [x] Update `services_config.yml` configuration.
- [x] Update `settings.yml` config values for `va_profile` (or `vet360`).
- [x] Configure faraday middleware.
- [x] Add mock response (.yml file).
- [x] Document process for adding/updating mock data for endpoints.

## Acceptance Criteria
- [x] Verify that `/v0/profile/service_history` endpoint returns data in local environment.
- [x] Verify that `/v0/profile/service_history` endpoint returns data in development environment.

**Comment by tpharrison** [comment]
[Documentation is here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/developer/mock_data.md).
