### ISSUE TITLE
[Design] 10-10EZ - Progress bar stepper: Mock-ups

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#60545]
## Background
As an applicant completing the 10-10EZ form online, I want a progress stepper to indicate exactly where I am/what page I am on within the form in relation to the beginning and end, so that I will know how much progress I have made and how much longer I have left to complete before submission.

After reviewing past research completed by several teams, including the 10-10 team (2022), and some USWDS design components, there are quite a few potential opportunities to address the current progress bar stepper and its confusion among applicants.
There are a couple teams conducting research on improvements for the stepper, including the Forms team.  We will sync with this team on their progress and the feedback they have obtained to help inform our direction.
We can then design a few best options that will fit the needs of our application, as well as help to clarify where the applicant is within the online form.

#### Resources
- Research ticket - #56319 
- [Mural board](https://app.mural.co/invitation/mural/departmentofveteransaffairs9999/1686606287030?sender=ubf5503bf47b6eb1e92730053&key=ffcefb0f-8601-429c-a0b7-a8a0043998be)

## Tasks
- [ ] Sync with the Forms team (Jeanna Clark) on their stepper research
- [ ] Determine the best options for our form (including accessibility and conditional question functionality)
- [ ] Create mock-ups of potential stepper options
- [ ] Present to team/PMs with recommendations and decision (if possible)
     - Also considering whether the stepper can be used for the 10-10CG
- [ ] Team/PMs to present to PO

## Acceptance Criteria
- The team will have determined whether a better progress stepper exists and if so, will recommend implementation.
