### ISSUE TITLE
Follow-up on idea of Feedback button on Platform Docs site

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#60558]
## Purpose
With the increased number of feedback mechanisms (our two-mechanism approach with the satisfaction survey, FRP, Content Team's page feedback, etc etc) the Support page is becoming tangled with several different feedback efforts that could cause confusion and frustration with the VFS customer.

This item has been waiting until Platform Content finished their IA research

## Tasks
- [x] Has PCT finished their IA research? Yes.
- [x] Set up Mural for PCT meeting with screenshots of existing mechanisms, links to research and existing recs, user stories, and areas for organizing taxonomy of recommendation needs 
- [x] Reach out to Platform Content team to follow-up on idea about adding 7th "Feedback" category or a newly titled "Support and Feedback" button with separate categories on the linked landing.
Not pursuing this portion.  Will include any ask in related ticket _- [ ] Determine what mechanisms would be included in this classification_

## Acceptance Criteria
Closing out as-is - _[ ] Next steps provided from PCT_

**Comment by twoangstroms** [comment]
Held two meeting with Johnny – waiting on him and PCT deciding on their next steps.

**Comment by twoangstroms** [comment]
Will carry over to next sprint because Blocked: PCT has other priorities at the moment
