### ISSUE TITLE
Identity Dashboard FE - Create Edit Team Page

### ISSUE THREAD

**Issue by ianmagenta** [department-of-veterans-affairs/va.gov-team#60564]
## Description
Using the Design assets (Figma) link below, create the Edit Team page (authenticated)

## Design Review
https://www.figma.com/file/rw8kJXf4VKliimoMpsEy4Q/Identity-Dashboard-(initial)?type=design&node-id=0-1

## Tasks
- [ ] Using Next.js create a page for the Edit Team page (authenticated)
  - [ ] Team name, agency, and admin email must be required fields
  - [ ] "Update" button should just submit the form (for now)
  - [ ] "Cancel" should take you back to /teams page
  - [ ] Add button and delete action should do nothing (for now)
  - [ ] Manage Team Members should be collapsible
- [ ] Write tests for the above

**Comment by aparsley** [comment]
Looks great, thank you for adding the Edits.
