### ISSUE TITLE
[SW] Update Review page design based on FE Discovery

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#60560]
## Issue Description
Continuation of #49159

- **On Review page:** Add Edit buttons for each section
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdThTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8cb1352afaf8ed6401c87171b2f961693a899916/Screenshot%202023-08-17%20at%209.37.59%20AM.png)

- Can this be persistent for editing per section? 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdHRNIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b4bccdc71ba4bb8177c8729b4eb5a3ea895036a0/first%20-page-review.png)

- **On Review page:** After user has finished editing section, the user will be sent back to the Review page and a [green status message](https://design.va.gov/components/alert#examples---slim-alert) will appear towards the top of the Review page. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaHdUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8f7f8d91e4c4b92f81a98f131b893f594121d71a/Screenshot%202023-08-17%20at%209.55.48%20AM.png)

---
## Tasks
- [x] _Review page updated made based on discovery by FE team_
- [x] Add yes/no questions to Review page
- [x] Update UI on pages when editing

## Acceptance Criteria
- [x] _Updates made to Sketch_

**Comment by HeatherRienks** [comment]
wait for FE work to be completed before starting (add tix)

**Comment by HeatherRienks** [comment]
@josephrlee & @mgleo - good news, I think we might be able to pull this in soon- let's ask @Dr-Pongo or we can discuss in our SW meeting on 7/26!
cc: @Tom-Davis

**Comment by HeatherRienks** [comment]
Per @Dr-Pongo - discovery work is complete and no design updates are needed. Headers inside accordions don't need to be updated by Design.
Design needs to talk to Experimental Design about action link v button and alert box on editing page location.

**Comment by HeatherRienks** [comment]
@josephrlee and @mgleo - any updates on this one? Thanks!

cc: @Tom-Davis

**Comment by HeatherRienks** [comment]
Per @josephrlee - we can wait until post-launch for this work. We have all needed content in a read-only version. Work is not critical for MVP launch.

cc: @Tom-Davis

**Comment by HeatherRienks** [comment]
Needs further discussion, per Planning meeting on 8/15.

**Comment by mgleo** [comment]
Ticket has been updated with more direction and screenshots. 
Questions for FE:
- Can the green status alert letting users know the form has been saved be removed when users are editing sections?
- How persistent is the dismissible alert? Per section?
- Can the Finish this Request later and Back to Review page links work when a user is editing a section? Or do they need to complete the entire section?
@OptionSelect @amponce @Dr-Pongo 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcU1VIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2552e4c6f7ecd64da54d497f3bfd5f7d507f1932/Screenshot%202023-08-17%20at%2011.43.39%20AM.png)

**Comment by Dr-Pongo** [comment]
Talked with @josephrlee about implementation on this one. It will be easier to implement the alert and back to review link on the first page of the chapter that is navigated to, rather than every single page. I think we just need clarification on that alert maybe being at the top with the link inside of it, and what the end of chapter buttons labels should be

**Comment by josephrlee** [comment]
@Dr-Pongo Here is the updated styling for the review page alert that would be present on the first page of every section: [Alert component styling on section edit for review page flow](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEU0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--178da47eaa135a7b2a40b96a08783160633b8747/Screenshot%202023-08-24%20at%202.34.17%20PM.png)

**Comment by HeatherRienks** [comment]
Megan & Joe meeting with Platform today to discuss this ticket.

**Comment by josephrlee** [comment]
We've got the green light to proceed with our proposed designs and flow. Here's the [Slack thread for more context](https://dsva.slack.com/archives/C01DBGX4P45/p1693336972998609).

Here's a [link to the experimental design request as well](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2040). 

cc: @Tom-Davis @HeatherRienks

**Comment by HeatherRienks** [comment]
Andrew met with Megan & Joe on 9/8/23 to discuss "Continue back to review" button - when/where should it show up? They decided that on pages that might not be the Final page, use "Continue" button for now, but need to discuss further.

**Comment by HeatherRienks** [comment]
Per @josephrlee, this work has been completed! Closing!
