### ISSUE TITLE
BE | Profile | Payment Information | Add mock responses

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#60574]
## Background
Responses from the following endpoints are not working.  

- `GET`  `/v0/ppiu/payment_information`
- `PUT`  `/v0/ppiu/payment_information`

Add/Update mock responses for this endpoint to use for user `vets.gov.user+228@gmail.com`.

## Tasks
- [ ] Update `services_config.yml` configuration.
- [ ] Update `settings.yml` config values for `va_profile` (or `vet360`).
- [ ] Configure faraday middleware.
- [ ] Add mock response (.yml file).
- [ ] Document process for adding/updating mock data for endpoints.

## Acceptance Criteria
- [ ] Verify that all endpoints returns data in local environment.
- [ ] Verify that all endpoints returns data in development environment.
- [ ] Review with FE engineer.

**Comment by mtcA6** [comment]
since we're building a new mock repository (#82753), closing this ticket
