### ISSUE TITLE
Intake - Form 40-0247 - Presidential Memorial Certificate

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#60579]
## About your team

- Team name: 
-	OCTO-DE product owner: Matthew Dingee
-	Product manager: Pat Siebenlist
-	Designer: Andrew Bergeron
-	FE engineer: Tze Lei
- Accessibility specialist: Jeana Clark
- Content writer: 
-	Product/team Slack channel:
 ## Description:
A Presidential Memorial Certificate (PMC) is a gold-embossed paper certificate bearing the official signature of the President of the United States. It honors the memory of a deceased Veteran and expresses the country's grateful recognition of his or her service in the Armed Forces.
The Presidential Memorial Certificate request form allows eligible recipients (next of kin, other relatives or friends) to request PMC.
Appears to be available to be submitted/uploaded online via QuickSubmit https://www.cem.va.gov/facts/Presidential_Memorial_Certificates.asp
https://www.va.gov/burials-memorials/memorial-items/presidential-memorial-certificates/

### What does your team need support for? Check all that apply.
- [x] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [ ] Making revisions to one or more existing VA.gov pages
- [ ] Accessibility review of wireframes and/or prototypes
- [ ] Accessibility issue (general request)
- [ ] Accessibility PDF review request
- [ ] Accessibility user research support ([submit a separate, additional request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name))
- [ ] Something else 
 
### Give a brief description of what your team needs support with:

My team needs support with ...
 Landing Page, Content Updates within the form
 
### Will this new product be released incrementally (for instance 25% of users initially)? 
  - [x] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
### When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
- 
 
### Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No
 
#### If yes, please check all of the phases in the Collaboration Cycle you have completed: 
- [ ] Design Intent
- [ ] Midpoint Review
- [ ] Staging
 
### When does this work need to be completed?
- Estimated launch date: August
- Estimated staging review date:
- Content, Accessibility, and IA work needed by: 
  
## Supporting artifacts
*Please provide supporting artifacts as available.*
- Link to product outline: https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/40-0247/Product%20Outline.md 
- Link to or attach user flows:
  - [Mural user flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1689262768121/889649b79a8c16be86c3e65790d393b9f4af3e36?sender=ud94436ff2bf5d5ce166a5253)     
- Link to prototype or mockups:
- Link to your research plan: 
- Link to any epics/issues that may be helpful:

#### Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

 **Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.
 
### Accessibility Help in Slack
The [#accessibility-help channel](https://dsva.slack.com/archives/C8E985R32) in the DSVA Slack, is also available to you as a resource. Everyone is welcome to ask questions or get help from our a11y (accessibility) specialists. Tag `@Terry Nichols` to get a11y help asap.

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

- If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
- If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)
 
 - If you are creating an [experimental design,](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) please [also contact the DST. ](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- If you are requesting [a11y support for user research,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name) please complete this form, next.

```[tasklist]
### Linked Tickets
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/60607
```

**Comment by RLHecht** [comment]
@tbaker1026 The link to the product outline isn't working. Can you repost?

**Comment by RLHecht** [comment]
Actually never mind, I fixed it!

**Comment by sara-amanda** [comment]
## CAIA a11y Notes 

### Reference Item: Midpoint Review - Accessibility Feedback
**July 6, 2023:** Veteran Facing Forms, 40-0247: Presidential Memorial Certificate Form #61533

> - **Should**: For the supporting discharge documents, I think the content here is right on the edge of needing some additional heading structure. It's probably not necessary, but I'd suggest trying headings for the enlisted service members and enlisted officers sections.
> - **Should**: In the Future v2 version when providing multiple addresses, I think there's a potential cognitive load challenge from separating the requestor's address and the addresses submitted in the list and loop. If I'm requesting a certificate for myself (requestor address), my brother (additional address) and the Veteran's best friend (additional address), I will only see two addresses (brother and friend) listed on that page. Users may have trouble remembering that their address was provided separately, or may be confused about whether they need to enter it more than once. Three possible solutions (no strong preference from me!):
>     - Static text on the multiple addresses page making clear that the requestor's address is already accounted for.
>     - Dynamic card listing the requestor in addition to whatever cards get added through the list and loop.
>     - Reorder the user flow so that the requestor provides their address as a part of this list and loop, so all the addresses happen at the same time.
> - **Consider**: Echoing Allison in #61530, for the multiple addresses consider a multi-page multiple responses pattern if possible.

cc: @ohgreatkate @coforma-terry

**Comment by sara-amanda** [comment]
@coforma-terry moving in Projects to match ZenHub "New Issues."  Adding @ohgreatkate to this ticket.

**Comment by jennymayoco** [comment]
Hi everyone, just an FYI that I will be OOO 8/30-9/5 in case of any IA q's, cc'ing @kristinoletmuskat. I will be back 9/6. Thanks!

**Comment by jennymayoco** [comment]
Hi everyone! Here is the [IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/form-digitization-40-0247.md) for this form. I will be OOO 9/27-10/8 and looping in @kristinoletmuskat in case of any IA questions.
