### ISSUE TITLE
BE | Profile | EDU Direct Deposit | Add mock responses

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#60571]
## Background
Responses from the following endpoints are not working.  

- `GET`  `/v0/profile/ch33_bank_accounts`

Add/Update mock responses for this endpoint to use for user `vets.gov.user+228@gmail.com`.

## Tasks
- [ ] Update `services_config.yml` configuration.
- [ ] Update `settings.yml` config values for `va_profile` (or `vet360`).
- [ ] Configure faraday middleware.
- [ ] Add mock response (.yml file).
- [ ] Document process for adding/updating mock data for endpoints.

## Acceptance Criteria
- [ ] Verify that all endpoints returns data in local environment.
- [ ] Verify that all endpoints returns data in development environment.
- [ ] Review with FE engineer.

**Comment by mtcA6** [comment]
@tpharrison do we need to consider adding mock testing data for our CH33 work? We haven't discussed the need for E2E testing w/LH in the recent calls but that was a major concern you raised for ensuring things are functioning properly. 

@Samara-Strauss I know we're still in the thick of figuring out what is even possible between BGS and LH but would be good to plant the seed sooner rather than later that we're going to need something more than mock testing data to ensure this is fully functional

**Comment by tpharrison** [comment]
@mtcA6 Mock data won't add much value for our DD migration work.  Yesterday, I added "Test scenarios in staging: C&P, EDU, Both" to the acceptance criteria for ticket #76716.

**Comment by mtcA6** [comment]
Yea i agree it wouldn't add a ton of value, worried it may be the only thing we'll have. I've added it into the Ch33 epic so we can keep an eye on things

**Comment by tpharrison** [comment]
Staging data is essential so we can test each of the 4 scenarios.  We should communicate this to LH and BIS as soon as possible.  The sooner we've identified the staging users that cover these scenarios, the better.

**Comment by Samara-Strauss** [comment]
@tpharrison we still have access to staging for C&P, right? I think Travis is thinking about the convo around staging vs. mock data landed last year, but you won that battle for us 🎉 

Re: actual staging users -- Currently the only user (378) I know about that has both C&P and edu benefits also has the fiduciary (or deceased) flag and we can no longer see direct deposit for them. So we'll have to see if we can track down where this flag is and get it removed. Otherwise, we have test users with comp & pen data only and edu data only.

**Comment by tpharrison** [comment]
@Samara-Strauss Yep - we still have access to staging for C&P.  I will reach out to the VES team and ask if they can remove the fiduciary flag on user 378.

**Comment by mtcA6** [comment]
Closing this out as the endpoint referenced in this story is for the legacy ch33 endpoint not the new work we're progressing through now. This will be obsolete in the span of a couple of weeks
