### ISSUE TITLE
Tagalog translation: COVID changes about Janssen vaccine

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#60577]
## Issue Description

We made changes to our COVID-19 pages about the Janssen vaccine no longer being approved. We need to make the same changes to our Tagalog pages.

Word doc sent to translators: [https://app.zenhub.com/files/133843125/9c5edea3-86b0-4d97-b4d7-5060e0612b14/download](https://app.zenhub.com/files/133843125/9c5edea3-86b0-4d97-b4d7-5060e0612b14/download)

Also note that we removed some content that isn't represented in the file sent to translators. We need to make sure we compare the live English page to the Tagalog page.

## Tasks
- [x] Update COVID-19 vaccines at VA page (Ana)
- [x] Update About COVID-19 vaccines page (Ana)
- [x] Copyedit both pages (Megan)
- [x] Remove alert that translated page is not up-to-date (Megan)
- [x] Publish both pages (Megan)

## Acceptance Criteria
- [ ] Changes are live on the site

**Comment by ABeltran77** [comment]
Word doc has not been received back from translators, an email was sent to them with a request for a status update.

**Comment by RLHecht** [comment]
@ABeltran77 here is the doc back from the translators. 

[https://app.zenhub.com/files/133843125/e590162f-ec1b-4517-bcb8-50ef1ba7875c/download](https://app.zenhub.com/files/133843125/e590162f-ec1b-4517-bcb8-50ef1ba7875c/download)

**Comment by megzehn** [comment]
Heads up that I went ahead and added these updates, since I was already in the pages for the last round of edits.

**Comment by megzehn** [comment]
I believe we're still missing Tagalog translations for these 2 notes in the [COVID-19 vaccines at VA](https://www.va.gov/health-care/covid-19-vaccine/) page:

---------------------

Note: The Janssen (Johnson & Johnson) vaccine is no longer available in the U.S. 

Note: Only Veterans who are enrolled in VA health care can get flu shots at VA health facilities. Call before you come in to make sure the facility has both vaccines.

**Comment by RLHecht** [comment]
@ABeltran77 Here are those missing two sentences back from the translators:
[https://app.zenhub.com/files/133843125/7537e629-e37f-43bb-b7be-7542719f798f/download](https://app.zenhub.com/files/133843125/7537e629-e37f-43bb-b7be-7542719f798f/download)

**Comment by ABeltran77** [comment]
@RLHecht @megzehn The two Tagalog sentences have been added.

**Comment by megzehn** [comment]
Thanks, @ABeltran77! Confirming I reviewed and published these pages. Closing this ticket.

**Comment by ABeltran77** [comment]
Thanks @megzehn!
