### ISSUE TITLE
Spanish translation: COVID changes about Janssen vaccine

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#60576]
## Issue Description

We made changes to our COVID-19 pages about the Janssen vaccine no longer being approved. We need to make the same changes to our Spanish pages.

Word doc sent to translators: [https://app.zenhub.com/files/133843125/9c5edea3-86b0-4d97-b4d7-5060e0612b14/download](https://app.zenhub.com/files/133843125/9c5edea3-86b0-4d97-b4d7-5060e0612b14/download)

Also note that we removed some content that isn't represented in the file sent to translators. We need to make sure we compare the live English page to the Spanish page.

## Tasks
- [x] Update COVID-19 vaccines at VA page (Ana)
- [x] Update About COVID-19 vaccines page (Ana)
- [x] Copyedit both pages (Megan)
- [x] Remove alert that translated page is not up-to-date (Megan)
- [x] Publish both pages (Megan)

## Acceptance Criteria
- [ ] Changes are live on the site

**Comment by ABeltran77** [comment]
Word doc has not been received back from translators, an email was sent to them with a request for a status update.

**Comment by ABeltran77** [comment]
State translators replied this morning that the request was resubmitted.

**Comment by RLHecht** [comment]
@ABeltran77 here is the word doc back from the translators. [https://app.zenhub.com/files/133843125/41b7c83e-c0dd-40c7-87a7-dc429e38a7ab/download](https://app.zenhub.com/files/133843125/41b7c83e-c0dd-40c7-87a7-dc429e38a7ab/download)

**Comment by megzehn** [comment]
Thank you, @RLHecht! Confirming that I reviewed these changes against the translation docs that were returned, as well as the updated English page. 

Moving to validate.

**Comment by RLHecht** [comment]
@ABeltran77 here are the missing two sentences back from the translators. 
[https://app.zenhub.com/files/133843125/5efa94a0-9ba2-45c8-8bdd-74c782ba42eb/download](https://app.zenhub.com/files/133843125/5efa94a0-9ba2-45c8-8bdd-74c782ba42eb/download)

**Comment by ABeltran77** [comment]
@RLHecht @megzehn The two Spanish sentences have been added.
