### ISSUE TITLE
BE | Profile | Personal Information | Add mock responses

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#60570]
## Background
Responses from the following endpoints are not working.  

- `GET`  `/v0/profile/personal_information`
- `PUT` `/v0/profile/preferred_names`
- `PUT` `/v0/profile/gender_identities`

Add/Update mock responses for this endpoint to use for user `vets.gov.user+228@gmail.com`.

## Tasks
- [ ] Update `services_config.yml` configuration.
- [ ] Update `settings.yml` config values for `va_profile` (or `vet360`).
- [ ] Configure faraday middleware.
- [ ] Add mock response (.yml file).
- [ ] Document process for adding/updating mock data for endpoints.

## Acceptance Criteria
- [ ] Verify that all endpoints returns data in local environment.
- [ ] Verify that all endpoints returns data in development environment.
- [ ] Review with FE engineer.

**Comment by mtcA6** [comment]
#82753 < building a new mock repository so closing this out
