### ISSUE TITLE
[BLOCKED] Collaboration Cycle for Public Websites: PACT Act Wizard

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#60582]
### VFS team name

Public Websites

### Product name

PACT Act Wizard

### Feature name

n/a

### GitHub label for product

PACT Act Wizard

## Kickoff questions

<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

Sitewide Content (CAIA) started in mid-late 2022

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Tool

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

No

### Do you need to capture any additional analytics or metrics?

Unsure

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/pact-act-wizard

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Notify the Collaboration Cycle team of this ticket in the vfs-platform-support Slack channel.

- [X] I acknowledge that I must notify \#vfs-platform-support after submitting this issue.

Kickoff Slack Thread with VFS team: (https://dsva.slack.com/archives/CBU0KDSB1/p1687303171840029)

</details>

 ## Recommended Collaboration Cycle touchpoints

### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- [ ] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [ ] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [ ] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.

**Design Intent artifacts**

See Platform guidance on [Design Intent artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Design Intent meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

- [x] User flow (required) – There are two user flow diagrams relevant to this product
  - Content and branching diagram, version v.0 (rapidly evolving) - [MURAL](https://app.mural.co/invitation/mural/departmentofveteransaffairs9999/1686687282873?sender=uf8ddb00f0c9a241ee4573555&key=51afbaca-4131-4828-a3c3-eced5a256061) – Danielle Thierry owns
    - We plan on using the Subtask pattern, one question per screen, so the design is completely driven by the content
  - Flows in/out: How the PACT Act wizard fits amongst PACT-related content - [MURAL](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1664903854802/3876e4204edea5dc0e9b52fbca47e9162f752dad)
- [ ] Whiteboard sketch or other lo-fi prototypes or wireframes
- [ ] Research plan
- [ ] Any other artifacts you have so far
  
##### Platform actions
- [x] Design Intent [Slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1687365905671929) with VFS team: 
- [x] Meeting date/time: Tuesday, 6/27/23 at 3:30 PM ET.
  
##### Platform actions

- [x] If you have feedback, create feedback tickets and link to this epic. Once you have completed you review, check the box next to your practice area
  - [x] Accessibility has completed the review
  - [x] Design has completed the review
  - [x] IA has completed the review
- [x] Update this ticket with the Zoom recording
  - Recording URL: [Zoom Link](https://oddball-io.zoom.us/rec/share/AYbJM-TZ_pTDFRmW7IJXGj0gntvkrG13TjnQlifP04LbVccxhkPcdHNem1R3Hem_.shMzPpKQUAcd-RMZ)
  - Password: @j5i!5kn
  
##### VFS actions

- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Sitewide Content and IA Intake Request
<details>
  <summary>Toggle Sitewide Content and IA Intake Request</summary>

##### VFS actions
- [x] Complete the [sitewide content and IA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-Content-and-IA-intake-request.2124906551.html)
- [x] Link to the Sitewide Content and IA Intake Request ticket below

</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [x] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [x] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

Provide links or documents for the following:

- [x] Finalized design prototype or mockup - **Prototype: https://www.surveymonkey.com/r/KKVHSFV**
- [x] Specify which pages are included in the review - Prototype in full.
- [x] Research plan - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pact-act-wizard/research/research-plan.md
- [x] Conversation guide - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pact-act-wizard/research/conversation-guide.md
 
**Content artifacts**
  
- [x] Your product’s content source of truth
  -  Jordan's [interaction flow diagrams that show the logic visually--completely up-to-date](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1692989444688/0044b9825c82d8d23920601f68c41a61d047d681?sender=uff8fa85716c1796ccf022668)
  - [Danielle's questions and description of logic--slightly outdated because missing 3 followup questions](https://dvagov-my.sharepoint.com/:w:/r/personal/danielle_thierry_va_gov/Documents/PACT%20Act%20wizard%20content%20for%20usability%20testing.docx?d=wfee483299a674f38ac4ec198c9cca463&csf=1&web=1&e=xPJwF9) 
  - [Danielle's original wizard flow--slightly outdated because missing 3 followup questions](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686687282873/beba3bd2c148677a82aa5b5c59a4f550e82d98e1?sender=uff8fa85716c1796ccf022668)
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable) NONE

**IA artifacts**

- [x] Please include a link to any [Sitewide Content & IA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including an IA review document or intake form. [Staging URL request from Public Websites, for PACT Act Wizard research #63472](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63472)

  
##### Platform actions
- [x] [Slack request](https://dsva.slack.com/archives/C52CL1PKQ/p1694708141846359)
- [x] Meeting date/time: 9/19/23 at 3:30pm ET

##### Platform actions

- [ ] If you have midpoint review feedback, create feedback ticket and link to this epic. Once you have completed your review, check the box next to your practice area
  - [x] Design has completed the review
  - [x] Accessibility has completed the review
  - [x] IA has completed the review
  - [x] Content has completed the review
- [ ] Update this ticket with the Zoom recording
  - Recording URL: [Zoom recording](https://oddball-io.zoom.us/rec/share/OrW6-tqrLtr7bE_0lk4nkbPU5mFKWNTcSvLXyZEIzPwYA8QRdUfAlV3mkL9VgdzR.AvEr27aiKWSwmLS6)
  - Password: `u^R8zh6M`
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [ ] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [ ] Link to the Analytics Implementation and QA Request ticket below

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [ ] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [ ] Link to the Contact Center review request ticket below

</details>

### Staging Review
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [ ] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [ ] I confirm the environment is available and test users have been provided.
- [ ] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).

**Staging Review artifacts**
  
See Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts). Platform findings are based solely on the staging URL and test users provided, as reviewed during the four days before the Staging Review meeting. Any test cases not covered or any ongoing work taking place during the review period may not be reflected in those findings.  

**Product artifacts** 
- [X] Staging URL: https://staging.va.gov/pact-act-eligibility
- [X] Specify which pages are included in the review: All pages in the PACT Act Wizard. Please note that answers to questions may take you to different pages.
- [X] Staging test user information: There are no credentials needed; this is an unauthenticated experience, and you just need access to va.gov on the staging environment.

**Content artifacts**
- [N/A] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
   * Content source of truth: https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EfA0bDrSS99DqfgUbnlb4LEBBeQDKRLLOTsitH5u4mqSIw?e=7mrjwa
   * https://github.com/department-of-veterans-affairs/va.gov-team/issues/69514
     
**IA artifacts**
- [ ] Please include a link to any [Sitewide Content & IA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) of the findings you received, including an IA review document or intake form.

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [X] [Regression test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-regression-test-planRegressionTestPlan)
  - [X] Regression tests are included in the Test Plan noted below
- [X] [Test plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pact-act-wizard/initiatives/2023-2024-launch/testing-qa.md) – includes test coverage statistics
- [ ] [Coverage for References](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [ ] [Summary(Defects) reports](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [X] [E2E tests](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/pact-act/tests/cypress)
- [X] [Code coverage](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/pact-act/tests/utilities)  
  
**Accessibility artifacts**
  
- [X] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D). For details, see [Prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).

[Completed QA Accessibility Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72031)
  
##### Platform actions
- [x] Staging review Slack thread with VFS team: [Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1704316849649889)
- [ ] Meeting date/time: Friday, January 12, 2024 at 2:00 p.m. ET

##### Platform actions

- [x] Update this ticket with the Zoom recording
  - [Staging review recording](https://oddball-io.zoom.us/rec/share/GOqKISieRUzBn3iDG3XfmaUwXdFPvzON5V7SwzIlnZZCBP600XNGiOP_DaH_5PZm.aCQx4MjV5xJuKf4G)
  - Passcode: `p3FTXA=0`
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [x] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [x] Link to the Readiness Review ticket below
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1831
#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by jilladams** [comment]
**Re: The Content team intake section:** 

In this case, the Content team (@DanielleThierryUSDSVA ) led this project with content. I don't know of a specific ticket that was used for the content development project, but Danielle may be able to point us to that, for reference. 

We've also worked with CAIA on IA for Staging the prototype: https://github.com/department-of-veterans-affairs/va.gov-team/issues/63472

**Comment by DanielleThierryUSDSVA** [comment]
Hi there! Here's the [content source of truth file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pact-act-wizard/design/content-source-of-truth.md). As noted in the file, there's a link to a Word doc (accessible to anyone on the VA network) that SMEs reviewed...that content will come over to the Github file directly soon.

**Comment by shiragoodman** [comment]
Thanks @DanielleThierryUSDSVA !

@wesrowe what is the status of this work?

**Comment by CherylEvans** [comment]
No feedback from Content. Thank you!

**Comment by jilladams** [comment]
Uneventful mid-point review, we are approved to move ahead to Perigean recruiting as no feedback / change requests are expected from the incoming tickets. Thanks all!

**Comment by jilladams** [comment]
Because Zenhub is likely going away, Sitewide may hit our Github Projects issue cap (1200), and may not be able to port all our issues in right away, logging which issues in this ZH epic are still open, so we can later build parent/child relationships in GHP as needed: 

* #73575
* #65776
