### ISSUE TITLE
[FSR] Front End Discovery - Form navigation back to review page

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#60586]
## Issue Description
Discovery ticket to investigate LoE for navigation from in form edits to review page. 

[Design Files: see Review request (C7)](https://www.sketch.com/s/79aa4a84-fef1-4c06-9495-e0431a6390bd/p/45CA0C9E-05B4-4670-BFC7-1DA64DCF2409/canvas)

---
## Tasks
- [x] Determine LoE for the following:
  - [x] Adding navigation to return to review page at the end of each chapter leveraging session storage value. 
- [ ] Create necessary ticket(s) for adding review page navigation from end of each chapter

## Acceptance Criteria
- [ ] LoE and tickets created for tasks listed above.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
List of final page(s) in chapters that would need return to summary:

* **veteranInformationChapter**:
    * `currentContactInformation`
* **householdIncomeChapter**
    * `dependentRecords` / `dependentAges`
* **householdAssetsChapter**
    * `otherAssetsChecklist` / `otherAssetsSummary`
* **householdExpensesChapter**
    * `otherExpensesChecklist` / `otherExpensesSummary`
* **resolutionOptionsChapter**
    * `resolutionComment` / `resolutionWaiverCheck`
* **bankruptcyAttestationChapter**
    * `bankruptcyHistory` / `enhancedBankruptcyHistoryRecords`

**Comment by HeatherRienks** [comment]
@Dr-Pongo - to create tickets and then will close this out.

**Comment by HeatherRienks** [comment]
We will plan for this to rollover to S104.

**Comment by HeatherRienks** [comment]
@HeatherRienks  *Reminder to work with Andrew to add links to this ticket for future reference.
