### ISSUE TITLE
Identify unused feature flags for debt team

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#60599]
## Issue Description
Over time as features and projects are developed we've added feature flags to begin work or launch a new item. We should pinpoint which of these are still needed or have become stale or mature due to launch time.

---
## Tasks
- [ ] Collect feature flags that belong to our team
- [ ] Identify if flag still has active purpose
- [ ] Add documentation for our team's flags

## Acceptance Criteria
- [ ] We have accessibility to active or unneeded feature flags
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kjsuarez** [comment]
[This documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/owned-feature-flags.md) is the fruit of this ticket.
