### ISSUE TITLE
Taxonomy for VA.gov Exp Standards

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#60595]
## User Story
As a Governance team member, I want to define an appropriate taxonomy model to the VA.gov Experience Standards so that I can easily apply the VA.gov Experience Standards at the Collab Cycle Staging Review. 

Assignee: @shiragoodman @sterkenburgsara 

## Description
At the Va.gov Experience Standard workshop for #59547, Governance team determined that the highest priority item and the focus on the initiative should be on improving the overall information architecture of the VA.gov Experience Standards. The first step to doing this is to define a taxonomy model that will allow Governance team members to easily locate the standard they are searching for when an issue is identified in a VFS Staging Review. 

Our planned approach is to take on a group affinity mapping session to re-cluster all of the experience standard problem statements according to the _user experience_, which we hypothesize will reveal standards that are too narrow or broad, that need to be retired/archived, or that need some re-writing. This will break us out of the current structure which is very practice-area driven and refocus the experience standards to be what they should be: standards that reflect the user's experience. 

We imagine we will need 2-3 group syncs to cluster findings. Then we will come up with cluster category names, writing descriptions for those.

Technical debt will result from this initiative (mapping standards to their new categories, rolling several too narrow categories into one larger category and mapping that, re-writing confusing standards, etc.). Technical debt will take place in another ticket. 

## Impacted Artifacts
 - [Experience Standards Affinity Map](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687405248108/d062ed36c1e5191571492e64cfe61ac87c02c9fc)
 
## Tasks
- [x] Shira/Sara 1:1
- [x] Affinity map workshop to re-cluster existing experience standards into new categories based on the user experience
    - [x] Workshop 1 - 6/23
    - [x] Workshop 2 - 6/29
    - [x] Workshop 3 - 6/30
- [x] Review decisions and flag experience standards that need work with a yellow-sticky note.
- [x] Review "00.00 - No experience standard found" stickies from high-level audit & cluster those
- [x] Develop names for final categories (we will write descriptions for categories and rewrite experience standards in next ticket)

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have determined how to apply a functional and appropriate taxonomy to the VA.gov Experience standards
 
### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by sterkenburgsara** [comment]
Update: Affinity mapping workshops took place on 6/23 (session 1) and 6/29 (session 2). We will need one more group sync to complete our first pass at experience standard re-groupings.

**Comment by sterkenburgsara** [comment]
@shiragoodman should this be sized more like an 8 since the scope of the ticket has changed?

**Comment by shiragoodman** [comment]
yea, I'm okay with that. I'll change the story points

**Comment by sterkenburgsara** [comment]
Update: Team completed our first pass of reorganizing the experience standards in the third workshop session today 6/30. Next week we will convene on Friday, July 7th to review and develop final categories with descriptions as next steps. We will also need to define next steps beyond that. This ticket will move into the next sprint.

**Comment by sterkenburgsara** [comment]
Update: had another team sync this week and are much closer to our final categories! Will sync with @shiragoodman early next week to determine next steps.

**Comment by sterkenburgsara** [comment]
@shiragoodman we have completed tasks in this ticket. Am I good to close? I will draft the next ticket & send to you for feedback by tomorrow AM so we can discuss during sprint planning.

**Comment by shiragoodman** [comment]
yes, you are good to close. Thanks @sterkenburgsara !
