### ISSUE TITLE
Add link to home loan support portal on foreclosure page

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#60608]
## Issue Description
David asked us to change the LGY email address contact option to their new Loan Guaranty Support portal. 

---
## Tasks
- [x] Add link (Laura)
- [x] Send to David to approve (Laura)
- [x] Copyedit and publish (Megan)

## Acceptance Criteria
- [ ] Link is live on page

**Comment by megzehn** [comment]
Thanks, @laurwill! Confirming I reviewed and published the changes.
