### ISSUE TITLE
Add realistic VBS copay statement mock data

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#60601]
## Issue Description
The payload we have mocked in the mockdata repo for VBS copay statement data is minimalistic and causes issues in certain use cases in local development, specifically those that validate the statement date expecting a valid date format. This should be updated to represent what a real payload might look like from VBS.

Now
```
---
:body:
  - id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
    pS_SEQ_NUM: 0
    pS_TOT_SEQ_NUM: 0
    pS_FACILITY_NUM: string
    pS_FAC_PHONE_NUM: string
    pS_TOT_STATEMENT: 0
    pS_STATEMENT_VAL: string
    pS_STATEMENT_DATE: string
    pS_STATEMENT_DATE_Output: string
```

What we should look to achieve
```
:body:
  - id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
    pS_SEQ_NUM: 506
    pS_TOT_SEQ_NUM: 588
    pS_FACILITY_NUM: "534"
    pS_FAC_PHONE_NUM: null
    pS_TOT_STATEMENT: 27
    pS_STATEMENT_VAL: 0000018255H
    pS_STATEMENT_DATE: "06012023"
    pS_STATEMENT_DATE_Output: "06/01/2023"
```

---
## Tasks
- [ ] Use existing or create new realistic payload
- [ ] Replace both user specific and default responses in mockdata repo

## Acceptance Criteria
- [ ] Local development has access to realistic VBS copay statement data
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
