### ISSUE TITLE
Add new feature flag for Schedulable parameter

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#60614]
## Description
A feature flag is needed to test the new Schedulable parameter in SQA staging before it is turned on in production.  This will also assist with deployment timing as changes in the backend need to be in production prior to the front end using this new parameter.

Once the feature flag is in place, @cferris32 can put the vets-api change that includes the Schedulable parameter behind the feature flag.

## Tasks
Add `va_online_scheduling_required_schedulable_param` feature toggle

---

## Acceptance Criteria
- [ ] The toggle is created for VAOS

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---)

**Comment by ldelacosta** [comment]
The feature toggle has been added. Closing out the ticket. 

![Screenshot 2023-06-26 at 10.36.50 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/982e9006-c7d7-4ea5-ad16-7c5d99c73005)
