### ISSUE TITLE
Update VHIE static page to match tool content

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#60618]
## Issue Description
Our VHIE R&S page currently says you can submit a form online through MHV to opt out/opt in to sharing records through VHIE. But we confirmed in staging that you can opt in/opt out using a button interaction — you don't need to use a form. We'll need to update our page to reflect this.

Node: http://preview-prod.vfs.va.gov/preview?nodeId=47014

---
## Tasks
- [x] Update page in Drupal (Laura)
- [x] Get SME review & approval from VHIE office and privacy office (Laura)
- [x] Move content into new R&S node to avoid broken link on old node (Laura)
- [x] Check for links to old node on our pages (Laura)
- [x] Copyedit (Megan)
- [x] Prepub and publish in new node (Megan)
- [x] Request redirect for H1 change (Laura)

## Acceptance Criteria
- [ ] New page is live and old page is redirected

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76968
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76977
```

**Comment by RLHecht** [comment]
Waiting to update page until after meeting

**Comment by laurwill** [comment]
Update: This work got rolled in to the interactive tool content for medical records settings. We'll get SME approval as part of that work in [this ticket](https://github.com/orgs/department-of-veterans-affairs/projects/929/views/1?filterQuery=vhie&pane=issue&itemId=38758520), then come back here to get a copyedit and publish the updates.

**Comment by laurwill** [comment]
@megzehn could you copyedit and prepub this node as soon as you have time? http://preview-prod.vfs.va.gov/preview?nodeId=47014 

I'm going to send to one last stakeholder as an FYI before we publish, but aiming for early next week.

@strelichl could you confirm the process we should use for an R&S page that has an H1 change? I know we need to request a redirect, but can't remember if that needs to happen before we pub.

**Comment by megzehn** [comment]
Hi @laurwill, confirming that I copy edited this page and went through the pre-pub list, and left it in drafts. 

I made one sentence-level change. Would you mind reviewing and making sure there aren't any issues with that? [Here's the link with my changes.](https://prod.cms.va.gov/node/47014/revisions/view/821583/844130/visual_inline)

Thanks!

**Comment by laurwill** [comment]
Hi @megzehn , 

I moved the updated content into a new node to follow our new process for R&S updates with H1 URL changes.

Here's the new node, ready to prepub and publish: http://preview-prod.vfs.va.gov/preview?nodeId=65950

@strelichl I added a couple child tickets for related page updates as fast follows to this ticket.

**Comment by megzehn** [comment]
Thank you for doing that, @laurwill!

Confirming I reviewed the new node and published. It should be ready for the redirect part. 

https://www.va.gov/resources/about-electronic-health-information-sharing-at-va

**Comment by laurwill** [comment]
Hi @megzehn , here's the R&S page with new content and old H1: http://preview-prod.vfs.va.gov/preview?nodeId=47014

Ready for you to publish!

**Comment by megzehn** [comment]
Thanks for updating this page, @laurwill! I confirmed that the content is identical and went ahead and published!

**Comment by laurwill** [comment]
@saratorres2 , I made more updates to this R&S page based on SME feedback. Could you copyedit the changes since Megan last published? We agreed with SMEs to call the office referenced in this page a "medical records Release of Information office."

This is ready to publish whenever you get to it! No firm deadline here. 

http://preview-prod.vfs.va.gov/preview?nodeId=47014

**Comment by laurwill** [comment]
Whoops wrong node, @saratorres2 it's this node: http://preview-prod.vfs.va.gov/preview?nodeId=65950
