### ISSUE TITLE
"Try me" content for phase 1 of all remaining health tools on VA.gov

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#60619]
## Issue Description
We recently drafted "try me" content to point people from MHV "View appointments" page to the new appointments on VA.gov. We'll need similar content for each health tool as it enters phase 1. Appointments didn't say the tool was moving, because that tool was already on VA.gov. The remaining tools (secure messaging, medical records, medications) will use messages about "moving" since the existing functionality is moving from MHV to MHV on VA.gov. 

---
## Tasks
- [ ] Draft content (Laura and Aliyah)
- [ ] Review (Danielle)
- [ ] Share with Ngozi and MHV partners (Laura and Aliyah)

## Acceptance Criteria
- [ ] MHV partners have phase 1 "try me" content ready to implement for all remaining health tools

**Comment by laurwill** [comment]
I'll talk with Danielle about process for these going forward — I'll update this ticket once we know if this work will stay with our team.
