### ISSUE TITLE
[FSR] Streamlined organization 

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#60628]
## Issue Description
`components` folder structure could use some organization as we move into streamlined waiver so we can identify areas that need to be cleaned up, or overlapping functionality. 

---
## Tasks
- [ ] Update FSR components folder for a more organized structure
- [ ] Identify any overlapping functionality we can combine
  - [ ] Create any tickets for future cleanup we can include

## Acceptance Criteria
- [ ] Folder structure is more manageable
- [ ] Any necessary tickets created 
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
