### ISSUE TITLE
[FE] My VA Audit UX: Update headings in Benefit application in progress

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#60625]
## Background
Per feedback from audit ux staging review, we need to correct the headings in the benefit application in progress card: When a user has a benefits application in progress (test user 220), the heading level for the application-in-progress card is an H4. The heading before that is an H2 so it skips a heading level, which can be disorienting for screen reader users. (see [54880](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54880) for full details). Angela updated the FE documentation in [57394](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57394), this ticket is to make the change in the code.

## Tasks
- [x] Change the heading level for application in progress card which is currently a h4, to h3 (it's skipping a heading level)
- [x] Tag @aagosto90 when complete for validation
- [x] PM to comment and close corresponding platform tickets when complete: [54880](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54880)

## Acceptance Criteria
- Heading level is changed to H3

**Comment by aagosto90** [comment]
Validated on staging! @dellerbie 

@ajakabcin Leaving the ticket open in case you want to address the Platform ticket before we close it.
