### ISSUE TITLE
[FSR] Streamlined Waiver prep - FE cleanup

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#60623]
## Issue Description
Identify and remove unused files in FSR. This is directed towards some `pages` files that are no longer used because we moved to using `CustomPage` components. We can probably also create and leverage a shared 'empty' schema component for those `CustomPages` where we are handling the validations manually.

This ticket is a good starter to also identify files that are no longer being used since the combined FSR (`combined_financial_status_report`) went live, so let's tack on identifying those deprecated legacy components, and create a separate ticket to remove those so we can remove the combined feature flag, and that can be our new baseline. 

---
## Tasks
- [ ] Identify and remove unused files in FSR. (primarily focusing on those deprecated `pages` files)
- [ ] Identify which files have been deprecated by combined feature flag being true
  - [ ] Determine LoE for removing these legacy files
  - [ ] Create ticket for removing legacy FSR files

## Acceptance Criteria
- [ ] Currently unused files removed from FSR
- [ ] Deprecated legacy files identified
- [ ] Ticket created to remove deprecated legacy files
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
@Tom-Davis - flagging this one; should we carry over to S112 or move to Backlog?

**Comment by Dr-Pongo** [comment]
@Tom-Davis @HeatherRienks I think this can get moved to backlog for the time being. It will come in handy once we [clean up the feature flag status stuffs](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/69313)

**Comment by denisecoveyduc** [comment]
@Dr-Pongo  I have a feeling this ticket is out of date a "prep" ticket doesn't seem accurate since both CDP and SW are live in production.  Could you clarify if there is still a need here?

**Comment by HeatherRienks** [comment]
Per @Dr-Pongo - he will review this next week in further detail and report back.

**Comment by Dr-Pongo** [comment]
Going to close this ticket out as it's no longer relevant! We're addressing the old feature flags and legacy functionality in a separate effort
