### ISSUE TITLE
[FE] My VA audit ux: Update headings in Benefit Payments card

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#60637]
## Background
Per feedback from staging review and design intent, we need to correct the headings in the benefit payments card: Benefit payment cards have an H3 heading followed immediately by an H4 heading, which doesn't really reflect the structure of the content and can be disorienting or misleading to screen reader users navigating the content by heading. (see [54878](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54878) and [47549](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47549)). 

#### This ticket is to update the code, designs and documentation were updated in #57393

>Using test user 80, you get this benefit payment card:

```
<div ...>
   <h3 class="vads-u-margin-top--0" data-testid="deposit-header-v2">
      +$3,057.13
   </h3>
   <h4 class="vads-u-margin-top--0">
      Compensation &amp; Pension - Recurring
   </h4>
   <p ...>
      Check mailed on November 1, 2022
   </p>
   <a ...>
      View your payment history<i ...></i>
   </a>
</div>
```

### Platform Recommendation
>My best suggestion would be to make the `h4` a `p` paragraph with styling to make it look like a heading, and then using `aria-describedby` to associate it with the `h3`. That would look something like this:

```
<div ...>
   <h3 class="vads-u-margin-top--0" data-testid="deposit-header-v2" aria-describedby="some-unique-id">
      +$3,057.13
   </h3>
   <p class="..." id="some-unique-id">
      Compensation &amp; Pension - Recurring
   </p>
   <p ...>
      Check mailed on November 1, 2022
   </p>
   <a ...>
      View your payment history<i ...></i>
   </a>
</div>
```

>Screen readers will announce the `h3` and the line beneath it together, providing full context while still having a heading structure that models the content.

## Tasks
- [ ] Change h4 that follows h3 to a p with styling to make it look like a heading and use aria-describedby to associate it with the h3
- [ ] Tag Angela to assist with validation 
- [ ] Tag PM when complete - PM to comment and close corresponding platform tickets: #54878, and #49264, then ultimately staging review ticket #48603

## Acceptance Criteria
- Heading level is is corrected as outlined above
- documentation is updated to reflect headings

## Resources
- [annotations doc for this in Sketch](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/OeRqarG)
- accessibility specs in the [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/benefit-payments-FE-documentation.md#accessibility-specs) which has that Sketch link as well.

**Comment by ajakabcin** [comment]
Moving to sprint 16 - in order to validate we need to wait for the next batch of "monthly payments" to go out on staging. So we'll test this on 8/2.

**Comment by aagosto90** [comment]
@ajakabcin @dellerbie @allisonlu 
A couple of issues with this that could be caused by something else - I have no idea but I'll point them out:

- I don't see an aria label associated with the title of the card as outlined in this ticket
<img width="657" alt="Screenshot 2023-08-02 at 11 37 13 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/97965610/3605485a-8f84-4956-98ed-13ef42100000">

- The second line of the card (type of payment) doesn't seem to be styled as an H4 or coded as a paragraph. It's styled and coded as an H3 when I inspect it.
<img width="657" alt="Screenshot 2023-08-02 at 11 37 46 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/97965610/3ba8ba0b-1201-436b-a2f7-955d31263317">

I could tell just by looking at it that it doesn't match the designs - here's a screenshot from staging:
<img width="980" alt="Screenshot 2023-08-02 at 11 49 35 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/97965610/878ae131-8016-4701-9c66-297f84c4c1bc">

And the Sketch design (second line of the card should appear a little smaller than the first line if it's using H4 styling):
<img width="991" alt="Screenshot 2023-08-02 at 11 25 44 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/97965610/5ce8801d-6a65-47e4-8ccc-befc6c7884d9">

**Comment by aagosto90** [comment]
Looks good! Thanks so much @dellerbie !
