### ISSUE TITLE
Login.gov adoption team: Sprint 23 (6/22-7/5)

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#60648]
## PTO
- Melissa 7/3
- Steve 7/3
- Dawn 7/3
- Svenja 7/3
- Independence Day 7/4

## Sprint 23 Goals
Preparing to release initial test comms:
- Iterating on our engineering approach: rate limiting, GA research & implementation, GovDelivery discovery, dynamic content
- Moving forward through collab cycle
- Refine roadmap with milestones, risks (incl. mitigation strategies), and research approach

## What we want to demo at the end of the sprint
- Local or staging demo of Reactivation Proof of Concept
- Updated roadmap

## Sprint 23 Tasks
**Iterate on engineering approach:**
- [ ] Reactivation PoC Email Rate Limiting #60789
- [ ] Setup Reactivation PoC Anti-Spam Controls #60787
- [x] create question doc for Granicus on GovDelivery API #60393
- [x] Define Scope for GovDelivery with Granicus #60392
- [x] discover adding GA tag to email #60414
- [ ] add GA tag to staging email CTA #60386
- [x] Investigate dynamic content in emails #60610

**Move forward through collab cycle:**
- [x] Create new Midpoint Review ticket for Organic Adoption and Retargeting #59214

**Refine roadmap:**
- [x] Update our roadmap based on workshop outputs #60712

**Rolled over from last sprint:**
- [ ] Design for Dashboard v2.0 that better addresses KPIs & comms #59101
- [x] Transform research insights into user needs #60208
- [x] Iterate on content for Reactivation email A/B test #59937
- [x] create script for automating SSOe data #60384
- [ ] ~~Run a local test with the proof of concept #59435~~

**Other:**
- [ ] Platform Orientation Template [Anu Das] #60744
- [x] Submit blog post about LGA support #60708
- [x] Prep for IPP workshop #60729
- [x] Pull a list of Veterans #60906
- [x] finalize reactivation email content #60864
- [x] Coordinate with VEO #60905

**From [Retro](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1677768711421/aad15b9308afe560c52a1beddefe388840ae239d?wid=0-1682539365898&sender=uaaa67493ae613f0003928743):**
- [ ] None

-----

## Future Sprint Goals (deferring for now)
- [ ] (Deferred goals go here)

**Tasks we're deferring for now**
- [ ] (Deferred tickets go here)
