### ISSUE TITLE
[FE, BE, PM] My VA Claim Status EVSS > Lighthouse: Coordinate testing strategy

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#60642]
## Background
Once the work is complete to update the claims status widget on My VA to point to Lighthouse instead of EVSS, we need to figure out next steps for testing. PM and BE to discuss process and needs, i.e. do we need to coordinate with Lighthouse at all?

## Tasks
- [x] PM and BE meet to discuss testing needs
- [x] Document a process
- [x] Create additional tickets as needed

## Acceptance Criteria
- [ ] we have a plan for testing

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_  Any team member
- _How can this work be validated?_ Testing plan exists

**Comment by ajakabcin** [comment]
Per our discussion on 6/22:
- we're going to run through test cases to ensure everything is functioning properly on the frontend (it should as nothing from a UX perspective has changed, but we want to be sure)
- @tpharrison and @dellerbie to determine what other additional system tests we should perform
