### ISSUE TITLE
Add crosslinks to new R&S compare education benefits page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#60646]
## Issue Description
Now that we've published our new R&S article about [comparing education benefits](https://www.va.gov/resources/compare-va-education-benefits/), we need to add crosslinks with teaser text from other VA pages for visibility.

IA work for this was done in ticket #57870.

Crosslinks to add:
- [x] [Education hub landing page](https://www.va.gov/education/) Place below "Find a Yellow Ribbon school"
- [x] [Careers and employment hub landing page](https://www.va.gov/careers-employment/) Place below "Subsistence allowance rates"
- [x] [Veteran Readiness and Employment page](https://www.va.gov/careers-employment/vocational-rehabilitation/): Place as first entry in "More helpful resources section"
- [x] [About GI Bill benefits page:](https://www.va.gov/education/about-gi-bill-benefits/) Place below "Tutorial assistance"
- [x] In Careers and employment left nav under "Subsistence allowance rates"
- [x] In Education benefits left nav under "Education benefit rates". Note that we need to remove the link to the legacy page lower down in the left nav.
- [x] [Post-9/11 GI Bill page](https://www.va.gov/education/about-gi-bill-benefits/post-9-11/): Add text link in the section with the H2 "What if I qualify for other VA education benefits too?"
- [x] [Montgomery GI Bill Active Duty page](https://www.va.gov/education/about-gi-bill-benefits/montgomery-active-duty/): Add text link in the section with the H2 "What if I qualify for other VA education benefits too?"
- [x] [Montgomery GI Bill Selected Reserve page](https://www.va.gov/education/about-gi-bill-benefits/montgomery-selected-reserve/): Add text link in section with the H2 "Can I qualify for more than one VA education benefit?"

We also need to update the link from the legacy page to our modernized page this page:
- [x] [Eligibility for Veteran Readiness and Employment](https://www.va.gov/careers-employment/vocational-rehabilitation/eligibility/)

## Tasks
- [x] Add links and teaser text to all pages listed above (Katherine)
- [x] Add to Resources and Support landing page (Megan)
- [x] Copyedit (Megan)
- [x] Publish (Megan)
- [x] Update left navs (Megan)

## Acceptance Criteria
- [ ] Crosslinks are all live

**Comment by katherine-fung** [comment]
Education hub landing page - Place below "Find a Yellow Ribbon school"
 Careers and employment hub landing page Place below "Subsistence allowance rates"
 Veteran Readiness and Employment page: Place as first entry in "More helpful resources section"
 About GI Bill benefits page: Place below "Tutorial assistance"
 In Careers and employment left nav under "Subsistence allowance rates"
 In Education benefits left nav under "Education benefit rates". Note that we need to remove the link to the legacy page lower down in the left nav.
 Post-9/11 GI Bill page: Add text link in the section with the H2 "What if I qualify for other VA education benefits too?"
 Montgomery GI Bill Active Duty page: Add text link in the section with the H2 "What if I qualify for other VA education benefits too?"
 Montgomery GI Bill Selected Reserve page: Add text link in section with the H2 "Can I qualify for more than one VA education benefit?"
We also need to update the link from the legacy page to our modernized page this page:

 Eligibility for Veteran Readiness and Employment
Tasks

**Comment by katherine-fung** [comment]
Education hub landing page - Place below "Find a Yellow Ribbon school"
 Careers and employment hub landing page Place below "Subsistence allowance rates"
 Veteran Readiness and Employment page: Place as first entry in "More helpful resources section"
 About GI Bill benefits page: Place below "Tutorial assistance"
 In Careers and employment left nav under "Subsistence allowance rates"
 In Education benefits left nav under "Education benefit rates". Note that we need to remove the link to the legacy page lower down in the left nav.
 Post-9/11 GI Bill page: Add text link in the section with the H2 "What if I qualify for other VA education benefits too?"
 Montgomery GI Bill Active Duty page: Add text link in the section with the H2 "What if I qualify for other VA education benefits too?"
 Montgomery GI Bill Selected Reserve page: Add text link in section with the H2 "Can I qualify for more than one VA education benefit?"
We also need to update the link from the legacy page to our modernized page this page:

 Eligibility for Veteran Readiness and Employment
Tasks

**Comment by katherine-fung** [comment]
Hi @megzehn! I found the page view #s in Google Analytics. Over the past year: 

How VA education benefit payments affect your taxes (42,016)
How do I get college credits for my military service? (50,642)
Can I get a replacement GI Bill benefit Certificate of Eligibility? (154,645)
What if my school closes temporarily because of a natural disaster? (842)
GI Bill and other VA education benefit payments FAQs (163,966)

I'll replace "What if my school closes temporarily because of a natural disaster?" with the Compare benefits link.

**Comment by megzehn** [comment]
Thank you, @katherine-fung!! I reviewed and published this update.

**Comment by katherine-fung** [comment]
The last update is live. I'm closing this ticket.
