### ISSUE TITLE
Content support and guidance for the Streamlined Waiver in the FSR

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#60656]
## Issue Description

The debt resolution team opened an intake request asking for content support for the new streamlined waiver in the FSR. We need to review the content they've provided and provide content support and guidance to make sure the content meets plain language standards and adheres to our style guide. 

Intake ticket for background: #59918.

Google doc with new content: https://docs.google.com/document/d/1gJJQoVH_iFE_81X2B7SV8_X3H5V64DITBRS_WQWsbUo/edit

Other helpful artifacts:

- UXPin prototype for Full FSR: https://preview.uxpin.com/f43733391f52c409c4d3152e9a4b101a392e29df#/pages//simulate/sitemap?mode=i
- UXPin prototype for FSR with streamlined waiver (Megan shared on 7/11): https://preview.uxpin.com/6940f648e5994b8fad9550934a5530b4cd73cacb#/pages/163500349/simulate/sitemap?mode=cvhid
- Link to or attach user flows: [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1678973946956/6f3bb65fe1ccc2b9d3bc38cd24cd09e74d18d778?sender=ua78f969c4cddcbfe56b27885)
- Link to prototype or mockups: Staging link to FSR (user 228) [https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/introduction](https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/introduction)

## Tasks
- [x] Edit content (Laura)
- [x] Post final content for product team in intake request (Laura)

## Acceptance Criteria
- [ ] Product team has final content

**Comment by aliyahblackmore** [comment]
Hi @laurwill this is a draft of content for you! 
[SW Content Transparency_AB_6.27.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11898564/SW.Content.Transparency_AB_6.27.docx)

- As mentioned, there are a few questions that I got answered via Slack and I'll be joining their weekly meeting with Jill and Denise for the first few minutes this afternoon. 
- I tracked a few notes in the beginning of the document. There are some questions in their for Jill/Denise that I'll ask. 
- I pinged Danielle about standardization of form intro pages. She's going to get back to me about this - I'll flag this in our meeting later on. 
- The word document is exported from their google document. I did notice that after the start of my review that a few pieces of content were changing in the google document - I tracked the recent changes from today in the word document and just noted the start date of my review (6/27) at the top of the document.

**Comment by aliyahblackmore** [comment]
**Update here:** 

- I made some other adjustments to the word document based on some of the responses from Jill/Denise and Danielle. I have one other question out to Jill and Danielle.
- Once they reply, I'll make additional adjustments to the document and share it with you again.

**Comment by aliyahblackmore** [comment]
Hi @laurwill - this streamlined waiver content is ready for you to review.

- Noting that their team passed over a Google doc (above) and I confirmed with their team that 6/28 was when there weren't any remaining changes to be made. I exported the document on 6/27 and began my review then.

- Earlier today, I noticed some more recent changes in their document (as of 6/30) - I noted those using comment in the word document. 
- Their content and notes, along with my suggested changes and comments made the document a bit crowded. When we pass them our suggestion, I'll pull out the sections we reviewed.
- As mentioned, Jill answered a few question regarding the flow and letter. I made adjustments to content today based on her responses. 
[SW Content Transparency_AB_6.27.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11941038/SW.Content.Transparency_AB_6.27.docx)

**Comment by aliyahblackmore** [comment]
Update here: 

Laura is going to pass a version with updates to collections language. 
Next week I'll flag the two remaining questions for their team, make adjustments, and pass them word document with content.

**Comment by aliyahblackmore** [comment]
Hi @laurwill - as we chatted, I'm posting the content feedback for their team in their intake request. I got answers on your last questions and adjusted/did a review this morning with Danielle.

### Notes: 

1. As we chatted, I did a review of the content in blue. There are a few areas where I noted other content changes to better align with site style.

2. Danielle is going to follow up re: intro page standardization and any plans to align with [the Education Benefits form intro page](https://www.va.gov/education/apply-for-benefits-form-22-1990/introduction). For now, I’ve left their process list headers, and in the document I passed to their team removed those comments with adjustments to more closely align with the education benefits intro page style. From my understanding, there is no eligibility step here, so if we’re moving towards aligning with pattern on education page, we can adjust this process list slightly. I also let their team know that once the pattern is confirmed, we can circle back about future updates.

3. Megan and team confirmed that the streamlined waiver is only for copay debt, so the page intro should be a bit more general since it's a page for the full FSR. Additionally, I left in the suggestions for content that should be entered dynamically depending on what someone requests (i.e. they’d need to list Debt Management Center and VHA/Health Resource Center, either, or both). This is relevant in the confirmation screen for non-streamlined waiver requests.

4. Though Megan confirmed that content was set as of 6/27, I did notice adjustment to the statement before the second bulleted list under “Prepare” – I noted the adjustment in comments in the document. 

5. Jill confirmed and clarified that the amount that is forgiven will be confirmed after their request is reviewed and will be included in the letter that is sent. As you confirmed in your comment, I left in the content for Option 2 which says what’ll be in the letter re: the amount.

6. I did clarify with their team that depending on someone’s GMT they may either get one of the asset questions (JUST cash on hand), all the asset questions (including cash on hand) or some of the asset questions (not including the cash check box if they already checked that). The commonality is that all users would get the cash on hand question at some point. Also, because they’re form screen uses “other assets,” I changed the bullet point back to “Additional assets” so that there isn’t confusion here. 

7. On the intro page, on the income bullet point, I adjusted language to remove “you” because the income questions are for the spouse (if they’re married) **and** Veteran. I also removed the sentence about info on a paystub because some of the other income types wouldn’t be on a paystub. I suggested that they add “or statement” here, because benefits payments may show on a statement. I noted that they’ll need to confirm with this with SMEs.

**Comment by aliyahblackmore** [comment]
@coforma-terry I passed final content to their teak in the intake request. I think we're okay to close this ticket out.
