### ISSUE TITLE
Remove **feature flag code** for facilityLocatorShowCommunityCares

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#6065]
## Problem Statement
How might we clean up unnecessary feature flags?
If the need to toggle a feature is no longer needed, then the code for the flag is also no longer needed and can be removed. 

## Goal
Remove unnecessary code from the master
---
## Tasks

- [ ] Remove **feature flag code** for facilityLocatorShowCommunityCares in staging
- [ ] Remove **feature flag code** for facilityLocatorShowCommunityCares in prod
- [ ] Remove **feature flag code** for facility_locator_show_community_cares in staging
- [ ] Remove **feature flag code** for facility_locator_show_community_cares in prod

## Acceptance Criteria

- [ ] facilityLocatorShowCommunityCares is no longer available for toggling in https://api.va.gov/flipper/features
- [ ] facilityLocatorShowCommunityCares is no longer available for toggling in https://staging-api.va.gov/flipper/features
- [ ] facility_locator_show_community_cares is no longer available for toggling in https://api.va.gov/flipper/features
- [ ] facility_locator_show_community_cares is no longer available for toggling in https://staging-api.va.gov/flipper/features
- [ ] All other functionality is maintained. 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
