### ISSUE TITLE
[FSR] Updated Text/Number components to use new width props

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#60653]
## Issue Description
Clean up existing components to use new [width props](https://design.va.gov/storybook/?path=/docs/components-va-text-input--default#widths) and remove unnecessary custom CSS classes. 

---
## Tasks
- [x] Update existing text and number components with new `width` prop
- [x] Remove extra custom CSS attached to existing components. 

## Acceptance Criteria
- [x] All text and number input components have a `width` prop attached to them 
- [x] All text and number input components have cleaned up classes
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
Whoever takes this ticket on, talk to @josephrlee - he has already completed a lot of work!!!!!
