### ISSUE TITLE
[FE] Notification Component: Fix padding and CLOSE text/"x" alignment

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#60661]
## Background
While QA'ing the component on My VA I noticed the "x" and "close" text were not aligned properly. We need to fix that alignment and ensure padding matches all the way around.

Test user 11 on staging
![Screenshot 2023-06-21 at 3 33 56 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/16ce7f97-625e-4d9d-92f1-1fb46971e1d4)

## Tasks
- [x] Horizontally align the "x" and the "CLOSE"
- [x] Adjust padding so that the padding on the right of the "CLOSE" text matches the padding on the left side of the exclamation icon
- [x] Tag @aagosto90 for validation

## Acceptance Criteria
- [x] Close and x icon are aligned properly
- [x] Padding matches all the way around

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_ @aagosto90 
- _How can this work be validated?_ review alignment and inspect padding on staging

**Comment by ajakabcin** [comment]
I'm going to keep this open until the design system release, zeroing it out as no additional work should be needed from us, just confirming once it's deployed.

**Comment by ajakabcin** [comment]
DST release scheduled for today July 5 - will check this again this afternoon for validation

**Comment by ajakabcin** [comment]
Confirmed with user 226 on staging - once component library was updated/released and then another vets website release
![Screenshot 2023-07-10 at 10 04 17 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/0ac4089e-0940-498b-bf74-16cc8cb34431)
