### ISSUE TITLE
Remove **feature flag code** for facility_locator_dedup_community_care_services

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#6067]
## Problem Statement
How might we clean up unnecessary feature flags?
If the need to toggle a feature is no longer needed, then the code for the flag is also no longer needed and can be removed. 

## Goal
Remove unnecessary code from the master

---
## Tasks

- [ ] Remove **feature flag code** for facility_locator_dedup_community_care_services in staging
- [ ] Remove **feature flag code** for facility_locator_dedup_community_care_services in prod

## Acceptance Criteria

- [ ] facility_locator_dedup_community_care_services is no longer available for toggling in https://api.va.gov/flipper/features
- [ ] facility_locator_dedup_community_care_services is no longer available for toggling in https://staging-api.va.gov/flipper/features
- [ ] All other functionality is maintained.

**Comment by mmiddaugh** [comment]
@darkbushido, can this one be closed?

**Comment by mmiddaugh** [comment]
Back end code has been removed. Need to remove from UI. 
@darkbushido
