### ISSUE TITLE
Design | CH 36 PCPG Form Discovery 

### ISSUE THREAD

**Issue by HeatherWidmont** [department-of-veterans-affairs/va.gov-team#60675]
## Issue Description
Time box 8 hours for PCPG (Personalized Career Planning & Guidance) form discovery. 

---
## Tasks
- [x] Screenshot page by page of site and form flows 
- [x] Import UX Pin or Sketch screens if available
- [x] Add call outs and start identifying user flows
- [x] Align the format/legend with the [[526 Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686768383603/3f4415dd2ddb71bbd104ebefd92a2c7b553ad792?sender=udbd39c1bbebb4ec4d7d08829)]

## Acceptance Criteria
  - [x] All screens before and after log in are captured
  - [x] Error states captured if able to validate
  - [x] Quick wins identified
  - [x] Known pain points acknowledged
  - [ ] a11y issues flagged
  - [ ] Areas we want to learn or investigate further highlighted

## Documentation
[Mural link](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1691434304975/3f0c405c820c184d21393b3bbd76324a5ee7c677?sender=u4e1fb0748c58370c03f33409)

**Comment by fiorella-io** [comment]
Finished creating the flow and added the mural link to this ticket
