### ISSUE TITLE
LGY Discovery 

### ISSUE THREAD

**Issue by HeatherWidmont** [department-of-veterans-affairs/va.gov-team#60676]
## Issue Description
Time box 8 hours for LGY (Loan Guarantee) form discovery. 

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] Screenshot page by page of site and form flows 
  - [ ] All screens before and after log in 
  - [ ] Error states if able to validate
- [ ] UX Pin or Sketch files if available
- [ ] Add call outs for 
  - [ ] Quick wins
  - [ ] Known pain points
  - [ ] a11y issues
  - [ ] Areas we want to learn or investigate further
- [ ] Align the format/legend with the [[526 Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686768383603/3f4415dd2ddb71bbd104ebefd92a2c7b553ad792?sender=udbd39c1bbebb4ec4d7d08829)]

**Comment by steele-lm** [comment]
@fiorella-io Is the [COE form discovery and mapping](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686849077019/c8b61e3a0f4bdda0d5bd06f7cfbf3afc77615d89?sender=u0e8ac1d6d7681bb7e1b80558) already done? Can we close this ticket or does additional discovery need to be done?

**Comment by steele-lm** [comment]
Possible option for next sprint. I think we also need to confirm if this work has already been completed ([LGY scratchpad](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686849077019/c8b61e3a0f4bdda0d5bd06f7cfbf3afc77615d89?sender=u0e8ac1d6d7681bb7e1b80558))

**Comment by fiorella-io** [comment]
Based on my conversation with Kate:
- Kate captured the entry points to the form. These entry points are complex and have their own flow that they recorded.
- [ ] We need to create a flow of the actual LGY form (Kate had started it) and do all the asks in this ticket
cc/ @steele-lm

**Comment by fiorella-io** [comment]
I'd like our team to investigate:
Why are some users automatically given a COE request without having to complete the form? What information do we have from them to do this? If they are items that our claimants can update, like on their profile, we should guide them so they don't have to fill out the form. [Link to Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1710194001946/6515464c5bd118903f111a4ec876c8d5ee8766a6?wid=0-1710352109091)

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/91498500/1ed4b31a-9913-4cd2-9c5d-059403aafb47)

**Comment by steele-lm** [comment]
@fiorella-io There is some [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/apply-for-home-loan-COE/Low%20Level%20COE%20Determination%20Flow.png) in the product repo from the last product team that might contain some info.

**Comment by fiorella-io** [comment]
I need access to these screens [specified here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/apply-for-home-loan-COE/engineering/README.MD#background):
1. If the Veteran is not eligible for an automatically approved COE AND they already applied for a COE using the form we provide we then need to let them know some status details of the application as well as provide them with all of the documents that have corresponded between the Veteran and the VA.
2. If the Veteran was denied for a COE we need to provide them with some information about how to appeal this decision.

All the staging user's I've tried with give me an automatic COE or need to manually apply for COE

**Comment by fiorella-io** [comment]
I tried the [users listed on the product page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/apply-for-home-loan-COE/Test%20and%20Launch/CoE%20Staging%20Test%20User%20Information.md). None of them fall under the categories previously listed. I updated that page by adding a notes column and a new staging user that results in an automatic COE

**Comment by fiorella-io** [comment]
@steele-lm Should this be closed or moved to the new team?
