### ISSUE TITLE
Global | Investigate bug related to NotFoundError: Node.removeChild

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#60670]
## Value Statement

**_As a_** developer
**_I want to_** research possible reasons for why this error in sentry exists
**_So that_** the error doesn't continue to affect several projects across the VA

---
## Background Context

Decision Reviews team investigated several sentry errors in this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59996) and this one seems to be out of scope.

These errors started increasing around May 15, 2023.

<img width="827" alt="Screenshot 2023-06-21 at 4 12 44 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/65c0f760-7371-44da-8a48-e65d8c30b8d5">

**Bug details from sentry:**

[15k total, 3.3k unique/90 days](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?display=top5&field=title&field=count%28%29&field=count_unique%28user%29&field=project&name=Errors+by+Title&query=event.type%3Aerror+removeChild&sort=-count&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1) `NotFoundError: Node.removeChild: The node to be removed is not a child of this node`

## Assessment Steps
- Review error in sentry
- Determine situation that replicates this error - since it's not app-specific, it may involve one of the common platform components, or web components (e.g. `va-loading-indicator`) 
- Attempt to replicate: 1-2 hr timebox

## Tasks
- [ ] Research how to duplicate this error
- [ ] Determine if the node has already been removed, or detached from the DOM, and is causing this error

---

## Definition of Ready 
- [ ] Monitor [Sentry remove child error](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?display=top5&field=title&field=count%28%29&field=count_unique%28user%29&field=project&name=Errors+by+Title&query=event.type%3Aerror+removeChild&sort=-count&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1)

## Definition of Done
- [ ] All tasks complete
- [ ] New Issue created upon resolution of spike

## Question/s

1. Can this bug be reproduced based on screenshots?

**Comment by Mottie** [comment]
Closing as we're no longer using Sentry
