### ISSUE TITLE
Pension Form Discovery

### ISSUE THREAD

**Issue by HeatherWidmont** [department-of-veterans-affairs/va.gov-team#60677]
## Issue Description
Time box 8 hours for Pension form discovery. 

---
## Tasks
- [x] Screenshot page by page of site and form flows 
- [x] Import UX Pin or Sketch screens if available
- [x] Add callouts and start identifying user flows
- [x] Align the format/legend with the [[526 Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686768383603/3f4415dd2ddb71bbd104ebefd92a2c7b553ad792?sender=udbd39c1bbebb4ec4d7d08829)]

## Acceptance Criteria
  - [x] All screens before and after login are captured
  - [x] Error states captured if able to validate
  - [x] Quick wins identified
  - [x] Known pain points acknowledged
  - [x] a11y issues flagged
  - [x] Areas we want to learn or investigate further highlighted
  - [x] Identify missing fields in the digital form
  - [x] Identify missing content in the digital form
 
## Mural
- Simplified current flow: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?wid=0-1692377011261
- Screenshot flow: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?wid=0-1683831459269

**Comment by fiorella-io** [comment]
We just finished capturing the items in paper form that are not in the digital form 🎉

**Comment by fiorella-io** [comment]
Updates: Created the simplified current flow of the form
