### ISSUE TITLE
Revise Sitewide CAIA intake request

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#60683]
## Issue Description

Our team is currently reworking our Sitewide CAIA intake request. We've discussed needing more information from product teams to better understand the support we will be giving. We met as a group to workshop ideas and started a Google doc to refine the request. 

Working doc: https://docs.google.com/document/d/1jNmI9j0vmUu3d47yxTeNR1eBWKnrf3rm5s6GDVOMyqE/edit

Once we have a final draft, we need to revise the template in GH here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/sitewide-content-intake-form.md

## Tasks
- [ ] Revise intake request
- [ ] Share with OCTO
- [ ] Update intake request template in Github
- [ ] Alert Platform team to update intake request on Platform website
- [ ] Alert teams of new intake request in ToT and slack channels

## Acceptance Criteria
- [ ] New intake request is in Github and available to product teams

**Comment by sara-amanda** [comment]
## CAIA Update
Updating the tasks in original ticket with links and checkmarks.
## Tasks
- [x] Revise intake request [template](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/.github/ISSUE_TEMPLATE/sitewide-content-intake-form.md)
- [x] Share with OCTO [(thread in Slack with Danielle)](https://dsva.slack.com/archives/C05GG0RPAN5/p1688994000772139)
- [x] Update intake request [template](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/.github/ISSUE_TEMPLATE/sitewide-content-intake-form.md) in Github
- [x] Alert Platform team to update intake request on Platform website (validated 8/2/2023)
- [ ] Alert teams of new intake request in ToT and slack channels

## Acceptance Criteria
- [x] New intake request is in Github and available to product teams
- [x] Update in sitewide-content-accessibility-ia DSVA Channel pinned links (ss 8/2/2023 - updated link to correct version for automating tags)

## Confirmation Request
### Tasks
@coforma-terry - I didn't want to check this off, without checking with you first. Can you verify these are completed above in the original ticket? 
- [ ] Alert teams of new intake request in ToT and slack channels
