### ISSUE TITLE
[Epic] Ask VA

### ISSUE THREAD

**Issue by artsymartha68** [department-of-veterans-affairs/va.gov-team#60696]
I'm opening this request on behalf of the Ask VA (aka AVA) team. The Ask VA team is a new team who will be redesigning the https://ask.va.gov/ tool from scratch. It would be great to assign a CAIA a11y specialist now, in the early stages, so a11y can be considered as early as possible. 

## About your team

- Team name: 
-	OCTO-DE product owner:  @beckyphung 
-	Product manager: @arielma-tw
-	Designer: @t-michaud @tygindraux 
-	FE engineer: 
- Accessibility specialist: 
- Content writer: 
-	Product/team Slack channel: #ask-va-public
 
### Describe what you need in a few sentences:

An existing product right now that basically serves as a support channel for Veterans to submit a web form, with a question, regarding documents, routed to support groups who receive these inquiries. They are able to respond through Secure Message, in the current portal, with mail an option as well. Inbox and messaging component available. 

AVA on the modernized VA.gov platform will be a digital support channel that works with other tools and features on VA.gov and VA ecosystems to quickly and accurately answer submitters' questions. Submitters should feel it is easy and intuitive to submit their issues and receive adequate updates and information that results in a final resolution. Ultimately, we want AVA to feel part of a cohesive and submitter-centered approach to support. 

Our Phase 1 will have brought the current Ask VA up to VA.gov design and accessibility standards, updated the content to make it more intuitive for our submitters, and sunset the existing front-end portal of AVA.

**You can see it in the current dynamics portal here** - https://ask.va.gov/ 

**Routing determined by:** 
- Category selection
    - There are about 18 categories (think of it as all the business lines of the VA) and then there are sub topics, and data that we collect along with the question to figure out how to get the question answered.
- Topic selection 
- Submission: 
    - The form can be submitted signed in or not signed in.

 
### Which are you doing?
- [x] **Launching a new page**, tool, form, or app
- [x] **Making changes** to an existing page, tool, form, or app

### Types of Support
What areas does your team need support in? Check all that apply.
#### Content
- [ ] Collaboration on content written by your team’s dedicated content writer 
- [x] Collaboration on content if your team does not have a dedicated content writer
#### Accessibility
- [x] Accessibility review of wireframes and/or prototypes
- [ ] Accessibility issue (general request)
- [ ] Accessibility PDF review request
- [x] Accessibility user research support ([submit a separate, additional request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name))
- [ ] DST component or pattern 
- [ ] Something else 
#### IA
- [x] User Flows
- [ ] Page placement
- [ ] Object-Oriented UX (OOUX) support
- [ ] URLs
- [ ] Breadcrumbs and Left Nav placement
- [ ] Redirects

#### Multilingual content
- [ ] Translating content

## Timeframe
_We guide and work alongside teams across nearly every OCTO digital product. We also work with partners across VA to lead content migration and manage all unauthenticated content on VA.gov. And we're always working to expand the VA.gov content style guide and our IA and accessibility documentation. We need to prioritize all intake requests based on our overall workload and VA and OCTO priorities._

_Tell us about your product's timeline. And we'll work with you to meet timeline needs as best we can._

### Have you worked with CAIA before? 
  - [ ] Yes
  - [x] No

### What is your team’s next step and its timing?

- **Our next step is** Design Intent 
- **Provide date if available**: 7/28/2023

#### Timing for your next step: 
  - [x] Next week
  - [ ] This month
  - [ ] Next month
  - [ ] This quarter
  - [ ] Next quarter
  - [ ] 6 months
  - [ ] 1 year

### Is this timing related to a specific event or Congressionally mandated deadline?
  - [ ] Yes
  - [ ] No

### If you are conducting research, when is that starting? 
**Provide date if available:** xx/xx/xxxx
  - [ ] Next week
  - [ ] This month
  - [x] Next month
  - [ ] This quarter
  - [ ] Next quarter
  - [ ] 6 months
  - [ ] 1 year

### Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [ ] No
 
**Note**: _If you checked yes, we’ll reach out to discuss details about the content in the react widget (we use these widgets to display entry points for new products to a certain percentage of users who visit our static pages)._

  
### When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
- **We expect to launch our product to 100% of users on:** xx/xx/xxxx
  
### Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

### If no ...
- Skip to the _supporting artifacts_ section, below.
 
#### Please provide the link to your Collaboration Cycle ticket: 
- **Ticket (number)**: #62304 
- **Collab. Cycle Ticket Opened (date)**: 7/20/2023
 
#### Please check all of the phases in the Collaboration Cycle you have completed: 
- [x] Design Intent - scheduled for 7/28/2023
- [ ] Midpoint Review
- [ ] Staging
 
##### Design Intent
- [x] Accessibility
- [x] Content
- [x] IA
- [ ] Translation
- [ ] Already completed, no assistance needed.
- [ ] Unknown at this time.
##### Midpoint
- [x] Accessibility
- [x] Content
- [x] IA
- [ ] Translation
- [ ] Already completed, no assistance needed.
- [ ] Unknown at this time.
##### Staging
- [x] Accessibility
- [x] Content
- [x] IA
- [ ] Translation
- [ ] Already completed, no assistance needed.
- [ ] Unknown at this time.
  
## Supporting artifacts
- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ask-va/products/Ask-VA-MVP-1-Product-Outline.md)
- User flows: [Health Category User Flow](https://www.sketch.com/s/6a75d0a2-e484-4f1e-8675-ad5747a1a871)
- [IA Spec Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/AskVA-MVP.md) c/o Kristin on 8/8/2023.
- Prototype or mockups: [Sketch link as of 10/15/2023](https://www.sketch.com/s/6a75d0a2-e484-4f1e-8675-ad5747a1a871)
    - If this is in Sketch, which version or specific page should we focus on?
- Content source of truth: [Content Flow Spreadsheet](https://docs.google.com/spreadsheets/d/1B8aGHO07RFTxi9QkCktjHWwV_COPIg1BJDBf7S80QX8/edit#gid=0) and [proposed content categories, topics and sub-categories](https://docs.google.com/spreadsheets/d/1aCei8pmLBBkWPeDye4YSmUqRkD0yCfTeLEqwdL-329M/edit#gid=0)
- [**Content Label Spreadsheet**](https://docs.google.com/spreadsheets/d/1aCei8pmLBBkWPeDye4YSmUqRkD0yCfTeLEqwdL-329M/edit?usp=sharing) to document the current names and proposed revisions 
    - **Blocker**: Per Tyler 9/8/2023: Still limited right now in our MVP (Phase 1) stage, where we're not able to merge, add or remove categories, topics or subtopics.
    - #67626
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ask-va/research/Submit%20an%20inquiry/Research%20plan.md)
- Research Ticket:  #66774
- **Any epics/issues that may be helpful**: [#62304](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62304)
- **Link to testing accounts** (please do not paste them in this ticket): 

### Have you already worked with someone from OCTO leadership?
- [ ] Danielle
- [ ] Beth
- [ ] Mikki
- [ ] Martha

### How do you plan to work with us on this request?
- [ ] I’ll take this to Beth or Danielle’s office hours.
- [x] I’d like to schedule time to talk about this.
- [x] Let’s work async and meet as needed.

 
### Accessibility Help in Slack
The [#accessibility-help channel](https://dsva.slack.com/archives/C8E985R32) in the DSVA Slack, is also available to you as a resource. Everyone is welcome to ask questions or get help from our a11y (accessibility) specialists. Tag `@Terry Nichols` to get a11y help asap.

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag `@Terry Nichols`.**

- If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
- If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)
 
 - If you are creating an [experimental design,](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) please [also contact the DST. ](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- If you are requesting [a11y support for user research,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name) please complete this form, next. 

### Content Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/67541
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/63280
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/67626
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/71486
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/78906
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/100265

### A11y Tasks
- [x] Review Intake Ticket for a11y needs
- [x] Plan ahead for requested 2024 research support for Ask VA Team

### CAIA Tasks (General)
- [x] Kickoff Meeting with Ask VA Team and CAIA to Sync on Project
- [x] Kickoff Meeting Held: July 20, 2023 [meeting notes shared](https://docs.google.com/document/d/1lnzlbtI7dUa1jkadKks5NyNeHhw62hNqn0dkvShGPHs/edit)
- [x] Supporting Artifacts Updated 10/27/2023 (SS)
- [ ] **REMINDER** Midpoint Review for (AVA) **11/14/2023** at 11:30 a.m. Eastern via [Zoom](https://oddball-io.zoom.us/j/81600041855?pwd=ejZrVW9jNXp4Qmx4Mzc0VjNCVHREZz09)

**Comment by sara-amanda** [comment]
## CAIA Update
_We will be sending a kickoff meeting invite for next week, so that the Ask VA Team and CAIA Team can connect and sync on the project ahead._ 

cc: @clantosswett @ruchishah29 @t-michaud @beckyphung @tygindraux @artsymartha68  @coforma-terry

**Comment by sara-amanda** [comment]
## CAIA Kickoff
It was great to meet everyone on the call today! 
- Please find our initial [CAIA Kickoff meeting notes in Google Docs here](https://docs.google.com/document/d/1lnzlbtI7dUa1jkadKks5NyNeHhw62hNqn0dkvShGPHs/edit). 
- There is also a [Microsoft Word .docx file](https://app.zenhub.com/files/133843125/e204557b-d403-45fe-8d4e-037ed8e307c9/download) attached, for those who cannot access the Google Doc. Should you need another format, please let us know. Happy to help!
- This ticket will act as the EPIC for the CAIA team on this project. 
    - All related tickets such as: accessibility, content and IA would live within this EPIC, as @coforma-terry mentioned on the call today. 

**_We look forward to supporting your team on this project!_**

**Comment by sara-amanda** [comment]
@coforma-terry - In addition to making this original ticket the new EPIC, I went ahead and updated this ticket to include the new intake ticket fields. I also brought over the link to the collaboration cycle ticket.

**Comment by kristinoletmuskat** [comment]
Hello! Reaching out about the IA. I think from an IA perspective at this stage it would be helpful to create a user flow that shows entry/exit points and conditional logic. IE, how users are going to find this tool, and how they’re going to continue the conversation about their question once they’ve submitted. Here’s an example [user flow mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1676397151510/f4cf4f4187a3d0fd5f2d6d56c9bd2ba3a4376e7a?wid=36-1677711033213) that we used in the past for the Login.gov initiative that Tyler was part of. Basically the goal is to zoom out and try to get a sense of the overall workflow for the user at the same time as we work on the ‘form’ itself.

Do ya’ll have an idea about where on the site you want ask VA to live? Here’s a link to our [sitemaps](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1672351995789/71a5b7ba07995735d458df39e07a696f48a9be48?sender=ua67f17f1c416a96ea04d2476) if that’s helpful in figuring it out.

**Comment by tygindraux** [comment]
@laurwill, hello! Reaching out to see if we can meet to review the first chunk of content we're looking for feedback on. (I'll add details/links below.) Is there a good day for you to meet next week? (I'll reach out on Slack, too.)

More about the work:
- We mentioned at the kickoff that Ask VA currently is structured by category, topic and sub-topic. Users choose a category and topic (and sometimes a sub-topic) and that's how their inquiry is routed to the right agents on the backend. In our MVP phase, we're not messing with the current routing logic, which means we can't remove, merge or add (etc.) categories, topics or sub-topics.
- We're still hoping to make some plain language updates to the current names of categories, topics and sub-topics so they're (1) easier to understand and (2) consistent with other VA.gov content.
- We've created a [spreadsheet](https://docs.google.com/spreadsheets/d/1aCei8pmLBBkWPeDye4YSmUqRkD0yCfTeLEqwdL-329M/edit?usp=sharing) to document the current names and our proposed revisions.
- We're in the (long, ongoing) process of reviewing these with each business line who is responsible for answering that category and/or topics inquiries, because they're currently the "owners" of the names.
- We'd like to meet with you and/or someone from Sitewide Content to give you a brief overview of what's in the spreadsheet, and then maybe you'll be able to review this more closely async.

**Comment by kristinoletmuskat** [comment]
Hello! I wanted to pop in here with the [IA spec doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/AskVA-MVP.md) -- so many thank yous to this team for the awesome work they did thinking through the before and after experience of the form!

**Comment by beckyphung** [comment]
@kristinoletmuskat Thank you for your helpful comments and the IA spec doc! An action item from me will be to note any VA.gov pages that don't currently link to Ask VA that will link to Ask VA in the future.

**Comment by laurwill** [comment]
Hi @tygindraux , just confirming here that we finished our first pass through the [label spreadsheet](https://docs.google.com/spreadsheets/d/1aCei8pmLBBkWPeDye4YSmUqRkD0yCfTeLEqwdL-329M/edit#gid=649654905), left some suggested label updates and questions for the business lines, and looking forward to chatting next Tuesday about next steps!

Here's a couple high-level suggestions that apply across categories:
- Avoid mixing labels for "questions about" and "questions for/from" — this mostly applies to the school certifying officials topics. If these "who has the question" labels are mixed in with the topics, you could get questions like "what does an SCO do" when really that label is trying to capture "I'm an SCO and I have a question." The best solution might be to route SCOs and other groups of people to their own set of topics by first asking who has the question (with options for Veterans, SCOs, etc). If that's not possible, we can suggest a way to relabel these "who" topics.
- It seems that there are 2 types of topics: "questions about" topics and "take an action through Ask VA" topics. For example, "upload documents" in the education category. Is this correct, and do you have a list of all the topics that are primarily "action" topics? We could make a rule to label these more clearly to set them about from "questions about" topics, but it wasn't completely clear from the spreadsheet which ones were actions.

**Comment by tygindraux** [comment]
Thank you so much for your work on this Laura and team! Your high-level comments make sense.

I think we'll be able to talk through both of your high-level suggestions in more depth on Tuesday, but before then I'll just offer some general context that helps explain where we're currently at with the categories, topics and subtopics. In the past (and technically, currently) these were owned by each individual business line.

For example, I answer education related inquiries, I realize that SCOs need a way of sending me documents, so I ask to create an upload documents category.

This explains some of the variation we're seeing across categories, which you're helping us work through.

But we're still limited right now in our MVP (Phase 1) stage, where we're not able to merge, add or remove categories, topics or subtopics.

Anyways, I hope that context is helpful at least to set the stage for our limitations right now. We're totally with you on seeing some of those outliers.

I'll try and identify the topics that are more "action topics" before our meeting on Tuesday.

**Comment by sara-amanda** [comment]
## CAIA Research Support

Good Morning, @tygindraux! 

Reaching out to plan ahead. It appears your original intake ticket indicated research support. 

- [x] Accessibility user research support ([submit a separate, additional request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name))

### AVA GitHub Research Folder

- I took a look at your research folder in GitHub, and it appears that research will be taking place in January 2024. 
- It appears you will be testing with `users of assistive technology` at that time, based on the GH notes: 
    > We will recruit Veterans and dependents through Perigean, including low vision or blind participants who use screen readers. We will also recruit 2 School Certifying Officials and 1 Work Study Supervisor independently.

- I went ahead and opened the ticket for us now, in order to plan for January.
   - [CAIA A11y Research]: Ask VA Tool (January 2024) #66774 
   - Feel free to add info to this as it becomes available. 
- Do you happen to know the time of month (early, middle or late Jan), this is so I can note it on our capacity calendar with a "hold."

<!DOCTYPE html><h4 tabindex="-1" id="user-content-ask-va-research-overview" dir="auto" style="box-sizing: border-box; font-size: 2em; margin-top: 0px !important; margin-right: 0px; margin-bottom: 16px; margin-left: 0px; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; padding-bottom: 0.3em; border-bottom: 1px solid var(--borderColor-muted, var(--color-border-muted)); caret-color: rgb(14, 17, 22); color: rgb(14, 17, 22); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><a class="heading-link" href="#ask-va-research-overview" style="box-sizing: border-box; background-color: transparent; color: unset; text-decoration: none;">Ask VA: Research overview<svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path d="m7.775 3.275 1.25-1.25a3.5 3.5 0 1 1 4.95 4.95l-2.5 2.5a3.5 3.5 0 0 1-4.95 0 .751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018 1.998 1.998 0 0 0 2.83 0l2.5-2.5a2.002 2.002 0 0 0-2.83-2.83l-1.25 1.25a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042Zm-4.69 9.64a1.998 1.998 0 0 0 2.83 0l1.25-1.25a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042l-1.25 1.25a3.5 3.5 0 1 1-4.95-4.95l2.5-2.5a3.5 3.5 0 0 1 4.95 0 .751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018 1.998 1.998 0 0 0-2.83 0l-2.5 2.5a1.998 1.998 0 0 0 0 2.83Z"></path></svg></a></h1><br style="box-sizing: border-box; caret-color: rgb(14, 17, 22); color: rgb(14, 17, 22); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">
`Copied from GitHub, as of 10/3/2023.`
Study | Type of Research | Date | Issue
-- | -- | -- | --
Initial desk research | Desk research | June 2023 |  
Business line engagement | Focus groups | June 2023-Ongoing |  
SCO dashboard workshop | Focus group | September 2023 |  
Submit and review an inquiry | Usability testing | January 2024 |  

<br style="box-sizing: border-box; caret-color: rgb(14, 17, 22); color: rgb(14, 17, 22); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px !important; caret-color: rgb(14, 17, 22); color: rgb(14, 17, 22); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">Reach out on DSVA Slack<span class="Apple-converted-space"> </span><code style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; padding: 0.2em 0.4em; margin: 0px; white-space: break-spaces; background-color: var(--bgColor-neutral-muted, var(--color-neutral-muted)); border-radius: 6px;">#ask-va-public</code><span class="Apple-converted-space"> </span>or contact Tyler Gindraux (<a href="mailto:tyler@bluetiger.digital" style="box-sizing: border-box; background-color: transparent; color: var(--fgColor-accent, var(--color-accent-fg)); text-decoration: none;">tyler@bluetiger.digital</a>) about this research.</p>

cc: @coforma-terry

**Comment by laurwill** [comment]
Hi @tygindraux @ruchishah29 , 
Similar to Sara's post above, now that we're nearly done with content work on the category labels for the MVP launch, I wanted to check about timing for content support on the rest of the tool designs. (I happened to look at [one screen](https://www.sketch.com/s/6a75d0a2-e484-4f1e-8675-ad5747a1a871/a/DEn9gna#Comment) and left a couple comments, but then realized I was getting ahead of myself :) 

We can get a content ticket open for that work, and let's chat next week about timelines for getting any content changes into designs and staging. 

cc @strelichl

**Comment by tygindraux** [comment]
Hi @laurwill! Thanks for your message as well.

That sounds great. We have a few flows in Sketch that are ready for your review, so I'd love to chat about timing whenever you're available. I'll jump over to the next ticket you created and have a look/start a conversation there. Thanks!

**Comment by laurwill** [comment]
Hi @tygindraux ! I'm mostly OOO this week, but @d-beyer and @aprocik1 have been taking a look at the tool screens and have a few initial questions. Would you have time for a quick chat with them this week? We want to make sure we're not making content suggestions that go beyond the scope of phase 1. 

Also noting that since the tool flow has quite a large number of screens, we likely won't provide detailed content feedback on every single one. We can focus our suggestions on priority content issues we find in our review. 

Thanks, and I'll catch up on this conversation on Monday!

**Comment by aprocik1** [comment]
Hey @tygindraux! I'm following up on Laura's comment above. After reviewing the prototype, we've got some questions about content and flow. I know we're aiming to provide recommendations by EOD 11/6, so I left our content questions as comments throughout your screens. The answers to those questions will help us finalize our content recommendations. Our questions about flow may be out of scope for your work right now, but I'm happy to meet this week if you'd like to discuss them. Thanks for your insight!

**Comment by eli-oat** [comment]
[Notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/Deliverables/Ask%20VA/2023-11-02-Ask-VA-design-review-notes.md) for the CAIA accessibility review of provided sketch files.

**Comment by coforma-jamie** [comment]
> [!NOTE]
> ## Accessibility Digital Experience (DE) Ticket Status Update
> Accessibility DE is OCTO’s new accessibility team. We’re working on a new intake process. In the meanwhile:
> - This ticket has been moved to validate and will be closed on the Accessibility DE pipeline (only).
> - This ticket will remain “open” until the work from content and IA is completed.
> 
> If you need additional accessibility support, contact the Accessibility DE team on [#accessibility-help](https://dsva.slack.com/archives/C8E985R32).
> **Thank you for working with the accessibility team!**
