### ISSUE TITLE
VAOS Staging Accessibility Review

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#6069]
## Summary
This is the epic to capture and categorize accessibility issues found during the audit conducted by VSP accessibility specialist in February 2020.

## Definition of done
* [ ] Severity 1 issues are taken care of before launch
* [ ] Severity 2 issues are triaged for fixes soon after launch
* [ ] Calendar widget is working as well as can be expected for launch, with any improvements scheduled for sprints directly after

**Comment by lenaecb** [comment]
Also closing this Epic since all issues have been completed/closed at this point.
