### ISSUE TITLE
BE | Profile | Direct Deposit | Capitalize Account Types

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#60697]
## Background
For Direct Deposit CnP, Lighthouse returns the `account_type` in uppercase ("_CHECKING_" or "_SAVINGS_").

The mobile team asked if the `account_type` fields can be capitalized instead of uppercase.

## Tasks
- [ ] Update `account_type` fields to be capitalized

## Acceptance Criteria
- [ ] Ensure all specs are passing
- [ ] Test in staging
