### ISSUE TITLE
[CDP] Copay statement copy change

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#60702]
## Issue Description
Need to update the copy on `manage-va-debt/summary/copay-balances`

Change "What you owe to your facility" to instead state " Your most recent statement balances for the last six months"

>Sounds like as a result of the new MCP Notifications that have gone out VHA is seeing an influx in calls from Veterans as they are confused by the page which states this is what they owe. We all know this was what they owed on the last statement but may not be reflective of what they currently owe. Hoping a copy change may make that clear and complement the disclaimer we have under each copay.

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/972fae1e-b3c9-4f0e-8453-de975a7676b7)

---
## Tasks
- [ ] Update copy for header on page from "What you owe to your facility" to " Your most recent statement balances for the last six months"
- [ ] Update any related tests this could affect

## Acceptance Criteria
- [ ] Copy changes have been made
- [ ] All tests passing
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
