### ISSUE TITLE
Implement list creation/slack notification of unit tests that incorrectly make network calls

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#60721]
## Description
Context: 

related thread: https://dsva.slack.com/archives/CBU0KDSB1/p1687449237731449

pre-work PR POC: department-of-veterans-affairs/vets-website#24631

We need to expand the allow list to include unit tests that get quarantined under two separate conditions:

- Unit tests are flaky
- Unit tests do not use mock api responses instead of real api calls

Additionally, we want a weekly blast to go out to the vfs-all-teams channel in the same format as the E2E test list informing teams of the tests that are quarantined and how long they've been quarantined for. This information should be published to a platform website page.

## Tasks

- [ ] Create allow list for unit tests in BigQuery
- [ ] Add unit tests stress test GHA workflow to quarantine flaky unit tests as well as tests that do not make mock api calls. Follow the same format as the existing E2E test process.
- [ ] Set up job to publish the list of quarantined unit tests to a platform website page
- [ ] Set up automated slack notification once a week alongside the existing E2E test one, following the same format

**Comment by CBonade** [comment]
Strategy per research ticket:

Unit test results are already collected and stored in BigQuery as a feature of Mochawesome report generation. This data is collected every time unit tests are run and contains all information about failures and the message that accompanied the failure. We can repurpose many of the functions that collect this data and tie them to a daily scan of unit tests, that runs 20x similar to how E2E tests run, and collect up all failures and improper network calls to throw them on an allow list.

For the initial step, we want to just implement the barrier that stops unit tests that are making improper network calls. We do not yet need to quarantine the tests, but need to collect the test data and publish it accordingly to start notifying teams of the improper practices:

1) Set up daily stress test to run unit tests 20x. Should mimic the E2E stress test we have in place.
2) Catch the data from this scan in the qa-standards-dashboard-data repository and leverage existing functions from E2E to send the offending tests to a BigQuery list, being sure to check for duplicates and only add each test once.
3) Fields in the BigQuery list should include `spec path`, `test name`, `failure message`, `date added` at a minimum. This might need to be expanded when implementing as concerns come up
4) Create script to publish this to a confluence page. Start it in a non-platform-website space with the intention to move it alongside the E2E disallowed tests list later after reviews by OCTO/platform leadership.
5) Draft a slack notification to push out weekly informing teams of the disallowed specs. This can likely be done in the same manner that the E2E one currently exists, possibly sharing a workflow just as a separate step or job

**Comment by acrollet** [comment]
@CBonade just checking if this was closed out intentionally? This issue has come up again. thanks!
