### ISSUE TITLE
[DISCOVERY] Explore options of Hardening VAMC "DAV-VAN" detail page in CMS 

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#6072]
## User Story or Problem Statement
As a web developer, the standardized content in the DAV-VAN transportation for veterans page needs to be standardized, so content can be easily copied, updated, and understood in plain language. 

## Goals
- Efficient and clear content describing local policies provided_
- Efficient plain language for veteran web users_
- Optimization of wording for search engines to pick up/point to local sites_

## Objectives or Key Results this is meant to further
- Reduced word count and improved plain language

## Resources - Tools - Documentation
[Pittsburgh DAV-VAN Page](https://www.va.gov/pittsburgh-health-care/dav-vans-transportation-for-veterans/)

## Tasks
_Tasks that must be complete in exploring options of hardening VAMC "DAV-VAN transportation for Veterans" detail page:
- [ ] Identify standardized content in the page  (That can be hardened)
- [ ] Regional standards that can be encapsulated (That can be hardened)
- [ ] Localized content that can be used to optimize search engines
- [ ] Inject facility content to optimize search engines				
- [ ] Determine if there is a single source of truth for this content?

## Acceptance Criteria
_Items that must that must be fully considered iin exploring options of hardening VAMC "Policies" detail page: 
* Identify standardized content (That can be hardened)
* Regional standards that can be encapsulated (That can be hardened)
* Localized content that can be used to optimize search engines
* Inject facility content to optimize search engines				
* Determine if there is a single source of truth for this content?
