### ISSUE TITLE
implement merge-blocking check for E2E allow list after a certain number of days have passed

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#60724]
## Description

As the allow list has accumulated tests that are quarantined, we've had varying levels of participation in correcting these flaky tests. Some are fixed quickly while others have persisted for extended periods of time. These tests need to be fixed in order to ensure the stability of va.gov, so we will be implementing a process to give a warning after 45 days of a test being disabled, followed by a merge-blocking GitHub actions check if the test is not fixed within 30 days of the warning.

## Tasks

- [x] Create a new list in BigQuery for specs that have received a warning, with a date/time they were added to the warning list.
- [x] Write a daily scan to add any test spec that has been quarantined for at least 45 days to the warning list.
- [x] Create a GHA check that will fail and be merge blocking if files in that directory are in the commits that are being merged, if a test in that same directory is on the warning list for more than 45 days.
- [ ] Add a display feature in the published allow list to note which specs are on the warning list
- [x] Coordinate announcing this change in the change-announcements channel

**Comment by CBonade** [comment]
The code for this is completed and working as intended. It hasn't been able to be merged due to failing status checks. Will continue into next week trying to get it to qualify for merge.

**Comment by CBonade** [comment]
This check has been implemented and merged. For the time being, all warnings are being refreshed daily to avoid any checks being failed until we're ready to launch.

Communications about this are being handled in a separate task: https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/63040
