### ISSUE TITLE
ATLAS: What code does platform own? SCOPED TO VETS-API

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#60728]
## LOE
Medium

## Problem Statement 

Currently, we're working in a monolith with a bit of a spaghetti mess of code where product and ownership boundaries are unclear. Not having these clear boundaries provides a handful of challenges from a development and support perspective. In both cases it can tangle the review process, add layers of complexity and dependency as well as cause a management and maintenance nightmare. These negatively impact the effort and efficiency of the Platform support and development teams as well as any other teams that engage with the codebase. This ends up turning them into detectives and having to engage in areas and ask questions that could otherwise be avoided or be more specifically tuned. A very specific use case would be the Platform support team attempting to work through support requests that aren't owned by Platform so they have no real ownership to appropriately address the root of the problem(s).

Determining code ownership is a step towards enabling additional autonomy for VFS teams.

**How might we develop a process to identify what code is owned by platform (scoped to vets-api code), and provide centralized documentation?** 

## User Impact
*Platform Support Team & Platform Teams
Unknown code ownership can cause increased effort and lost time in addressing non platform questions and wasted cycles for unneeded or edge case PR approvals.
*Impacts scalability of what platform is able/not able to do.

*VFS teams
VFS teams depending on platform for issues they come across even though the root cause of the problem is not platform code related. _How VFS teams leverage code in the repos._

^Addressing code ownership should lower the inefficiencies and tighten the feedback loop around issues by being able to more clearly target and communicate with the appropriate team(s). 

## Where was this problem reported?
* This has been known internally within the Platform team for quite a while (months) and has primarily just been something tolerated. However, with the Platform team size being much smaller and a major focus being on stability and resiliency, this is seen as a potential major improvement area.

## What do we know about the problem space?
* The ownership of code in many of the repos has room to be improved and more clearly defined.
* Having clear definition will streamline PRs and shorten support feedback loops
* This would be the core initial step in fully separating code based on "area" and owner (service centric)

## What (if any) research or discovery has been done?
* There hasn't been research done per say but an item that Platform has lived with and discussed numerous times
* During testing for the vets-api EKS migration, Tech Team 1 did some initial work to determine ownership of vets-api code. Some of this information is likely already out of date. 

## What is the acceptance criteria?
- [x] Each piece of code in vets-api that platform owns is identified
- [x] Code that isn't platform owned and doesn't have a clear owner has been identified (no additional research past crew)
- [x] If there is code currently owned by platform that TT1 thinks should be owned by someone else, this should be identified
- [x] Code ownership is documented in a centralized location
- [x] We have communicated to VFS teams how they can know whether code is ours and to only ask platform support about features/products in our code
- [ ] Need way of tracking if support issues are related to code owned by platform (to help with the success measurement below)
- [ ] [Atlas App](https://dev.va.gov/atlas) is deployed and documented in [product outline](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2760671235/Product+Outline+Atlas+WIP)

## How should we measure success?
- Reduction in number of support issues about code we don't own over time
- (0 to 1) We have clear documentation of code in vets-api: code owned by platform, VFS teams, unknown, orphaned

## TODOs
- [ ] Convert this issue to an epic

**Comment by laineymajor** [comment]
To what extent does codeowners represent what is needed by this project? What is the gap?
- visibility beyond the config file
- documentation: is it possible to leverage an existing machine readable format? codeowners, backstage, product directory

How we measure success:
- how much of vets-api currently had a codeowner associated 

How could this information be included in the culture of platform planning, maintenance, support, etc

**Comment by laineymajor** [comment]
TT1 ideas:
- How do we make this NOT go stale
- we need to include governance to keep this maintainable (as part of the AC)

To make more valuable
- figure out how to modularize the code (should we be moving to modules? is that more value add?)
- need to know the team associated to the module to eventually give them additional autonomy

**Comment by laineymajor** [comment]
TT1 ideas:
- How do we make this NOT go stale
- we need to include governance to keep this maintainable (as part of the AC)

To make more valuable
- figure out how to modularize the code (should we be moving to modules? is that more value add?)
- need to know the team associated to the module to eventually give them additional autonomy

**Comment by laineymajor** [comment]
All information from this project is now living in the [ATLAS APP](http://platform-codeowners.vfs.va.gov/) *requires socks
