### ISSUE TITLE
Conceptualize reference handbook for front end support

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#60730]
## Description

As we move to having dedicated Tier 1 support staff and move engineers off of support, in order for the process to go smoothly these newer staff will need reference material. There's many support requests that come up, that engineers that have worked support for a while know the automatic answers to. The new Tier 1 Support Staff will not have those answers at-the-ready and will either spend a good deal of time searching for the answer or end up escalating issues to Tier 2 regularly. It is to our benefit to cobble together a support handbook with commonly repeated support requests and their known solutions. 

The initial way I envision this document has a parent page with a table of contents, that links to child pages (one child page per topic). This would make it easily usable and quick to find the solution that's being looked for. We can add to this document over time, and gradually, the Tier 1s can contribute to it as well.

## Tasks

- [ ] Create confluence support table of contents page that automatically adds child pages (if you need an example of how to do this, check out the front end COP meeting notes page here: https://vfs.atlassian.net/wiki/spaces/FEC/pages/2583724044/Meeting+Notes
- [ ] Create child pages to start as a base to be contributed to over time with common support issues. This ticket: https://app.zenhub.com/workspaces/frontend-cop-backlog-6452b043f27c8b0011a25236/issues/gh/department-of-veterans-affairs/va.gov-team/60816 can be a good starting point.
- [x] This should also include this task: https://app.zenhub.com/workspaces/frontend-cop-backlog-6452b043f27c8b0011a25236/issues/gh/department-of-veterans-affairs/va.gov-team/58394 (which can be closed after documenting those solutions here).

**Comment by CBonade** [comment]
https://app.zenhub.com/workspaces/frontend-cop-backlog-6452b043f27c8b0011a25236/issues/gh/department-of-veterans-affairs/va.gov-team/58058
