### ISSUE TITLE
Add proper routing for authenticated/unauthenticated states instead of 404-ing

### ISSUE THREAD

**Issue by ianmagenta** [department-of-veterans-affairs/va.gov-team#60742]
## Description
Right now, when an unauthenticated user tries to access authenticated pages, they are sent to a 404 page. Similarly, when an authenticated user tries to access the unauthenticated homepage they are also 404-ed. We want to change this so that...

## Tasks
- [x] Instead of a 404/400 for authenticated pages, an unauthenticated user should be re-routed to the homepage.
- [x] Instead of a 404/400 for the unauthenticated homepage, an authenticated user should be kept on their current page.
- [x] We can use default.js files instead of a middleware.js (unless their behavior is undesired).
