### ISSUE TITLE
[eFSR] Remove last nested fieldset on Spouse Benefits and add h3 to legend for remaining pages

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#60758]
## Issue Description
Get rid of last nested legend fieldset and add h3 to legends on Spouse Benefits pages

---
## Tasks
- [x] Change `ui:title` and show the label on the object 

## Acceptance Criteria
- [x] Page has no more nested `fieldset` and `legend` has an `h3` inside of it. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
