### ISSUE TITLE
Create and publish future rates page for Chapter 35 rates for survivors and dependents

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#60779]
## Issue Description

The education business line publishes Chapter 35 rates (that go into effect in October) in July so that students can have the information ahead of time. 

Now that we have the education rates on our modernized pages, we need to create a separate rates page with this information explaining that these are for the future year. 

Future rates url: https://www.va.gov/education/benefit-rates/chapter-35-rates/future-rates/
This should be placed in the left nav in the same position we have the other future rates pages.

Eventually we'll move these rates to our current rates page and change the information on the future rates page to tell users to check back to this page soon for upcoming rates.

## Tasks
- [x] Get future rates from EDU stakeholders
- [x] Create Drupal page and input rates
- [x] Review rates
- [x] Copyedit and publish

## Acceptance Criteria
- [ ] New future rates page is live

**Comment by RLHecht** [comment]
I emailed JJ 6/23 to see if rates were available yet.

**Comment by RLHecht** [comment]
Update: JJ said that these rates won't get to us until after 7/21. She'll email when they're ready.

**Comment by laurwill** [comment]
Hi @katherine-fung , I cloned this page and input the rates — can you check the numbers? 

http://preview-prod.vfs.va.gov/preview?nodeId=59355

Can you also confirm if we left off farm coop rates on purpose? They're not on the live page.

If this looks good, you can pass to Megan to do final prepub and publish — aiming to publish on Monday.

**Comment by katherine-fung** [comment]
Hi @laurwill @megzehn, 

I reviewed the rates and they look good. The page is ready for a final prepub and publish. 

We left off the farm coop rates because Cinda/Jodie told us that no one uses the benefit in this way. I believe we left that off the rates pages for all the programs.
