### ISSUE TITLE
Create and publish future rates page for MGIB-SR

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#60773]
## Issue Description

The education business line publishes Montgomery GI Bill Selected Reserve rates (that go into effect in October) in July so that students can have the information ahead of time. 

Now that we have the education rates on our modernized pages, we need to create a separate rates page with this information explaining that these are for the future year. 

Future rates url: https://www.va.gov/education/benefit-rates/montgomery-selected-reserve-rates/future-rates/
This should be placed in the left nav in the same position we have the other future rates pages.

Eventually we'll move these rates to our current rates page and change the information on the future rates page to tell users to check back to this page soon for upcoming rates.

## Tasks
- [x] Get future rates from EDU stakeholders
- [x] Create Drupal page and input rates
- [x] Review rates
- [x] Copyedit and publish

## Acceptance Criteria
- [x] New future rates page is live

**Comment by RLHecht** [comment]
Education stakeholders had told us they usually publish MGIB-SR future rates around July 21. I sent an email to JJ to ask if the new rates are available yet.

**Comment by RLHecht** [comment]
Update: JJ said these rates won't be ready until after 7/21 and she'll email us when they're available.

**Comment by laurwill** [comment]
Hi @katherine-fung , could you also check this cloned page with the new rates? If it looks good you can pass to Megan to publish, also aiming for Monday. Thank you!

http://preview-prod.vfs.va.gov/preview?nodeId=59358

[https://app.zenhub.com/files/133843125/7bec4d0e-ea68-4cb7-a60f-63a175ce2711/download](https://app.zenhub.com/files/133843125/7bec4d0e-ea68-4cb7-a60f-63a175ce2711/download)

**Comment by katherine-fung** [comment]
Hi @laurwill @megzehn,

I reviewed the rates and they look good. The page is ready for a final prepub and publish.

Thanks so much!!

**Comment by laurwill** [comment]
This is live — closing out.
