### ISSUE TITLE
[bug] Validation for issue requirement for Board Appeal

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#60775]
## Current behavior
On staging, the Board Appeal form is not validating for the issue requirement. If a user does not have eligible issues, they are able to get through the form without any errors.

On production, the issue validation is working, but the focus does not stay on the error message.

## Expected behavior
If a user does not have eligible issues, or has not selected an issue. They are not allowed to move forward, and the focus will be on the error message.

## Background context
Found this when testing the Request a Board Appeal form on staging.

## Acceptance Criteria
- [ ] User is not allowed to move forward unless they have an issue selected
- [ ] The focus stays on the error message if the user tries to move forward.

## Tasks
- [ ] Fix validation on staging
- [ ] Fix focus management for error message

## Definition of done
- [ ] All tasks complete

**Comment by Mottie** [comment]
I'll need to double check, but this _might_ have been [fixed by the work in this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/24675)

**Comment by Mottie** [comment]
This was not previously fixed. PR has been opened.

**Comment by Mottie** [comment]
Ready for testing in staging

**Comment by eileen-coforma** [comment]
This looks fixed in staging. Can't check in production.

**Comment by Mottie** [comment]
@saderagsdale we can close this ticket
