### ISSUE TITLE
[bug] Board Appeal issue validation not working on Staging

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#60776]
## Current behavior
User can move through the Board Appeal form without adding an issue on staging. Validation isn't working on the following pages:
- https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/contestable-issues
- https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/issue-summary
- https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/review-and-submit

User isn't allowed to submit the form, and a generic error message pops up, but it's not highlighting the area that needs to be fixed.

## Expected behavior
User should not be able to move forward without selecting an issue, and an error should pop up, with the focus staying on the error if the user tries to continue.

## Background context
Found this when testing the Request a Board Appeal form on staging with user-236. Robin was able to replicate. Does not happen in production.

## Acceptance Criteria
- [ ] User cannot continue without selecting an issue
- [ ] Focus will go to error message if user tries to continue without selecting an issue

## Tasks
- [ ] Fix validation in staging

## Definition of done
- [ ] All tasks complete

**Comment by eileen-coforma** [comment]
This is a duplicate of 60775
