### ISSUE TITLE
PM | Profile | Direct Deposit EVSS>LH | Phased Release (  5% ,10%, 25% , 🚨50% 🚨,100%)

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#60782]
## Background 
This ticket is for our phased rollout for the Direct Deposit EVSS to LH migration 

## Testing Artifacts
[Test Cases Spreadsheet](https://docs.google.com/spreadsheets/d/1xflLNJhUSVslzLbVQtMkYkzsBGAhIccnmYW0GL_Ihd0/edit#gid=0)
[Team QA ticket #54771](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54771)

## Monitoring
[Direct Deposit for C&P Dashboard](https://analytics.google.com/analytics/web/#/dashboard/naG_-UneTxy50WvvIH0GGQ/a50123418w177519031p176188361/_u.date00=20230601&_u.date01=20230628/)

- [AE Sandbox Dashboard](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/DRqBrmiyTD6l8L75rei0fw/a50123418w177519031p176188361/_u.date00=20230709&_u.date01=20230802/)
- [GA Dashboard](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/naG_-UneTxy50WvvIH0GGQ/a50123418w177519031p176188361/)
     - [Sentry](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?display=daily&environment=production&field=url&field=error.value&field=timestamp&name=Errors+by+URL&query=event.type%3Aerror+url%3Ahttps%3A%2F%2Fapi.va.gov%2Fv0%2Fprofile%2Fdirect_deposits%2Fdisability_compensations&sort=-url&statsPeriod=14d&widths=-1&widths=-1&widths=-1)
     - Data Dog
          - [Viewing LH Direct Deposit](https://vagov.ddog-gov.com/apm/resource/vets-api/rack.request/e504ea6e07d6848b?query=%40_top_level%3A1%20env%3Aeks-prod%20service%3Avets-api%20operation_name%3Arack.request%20resource_name%3A%22V0%3A%3AProfile%3A%3ADirectDeposits%3A%3ADisabilityCompensationsController%23show%22&env=eks-prod&spanType=service-entry&topGraphs=latency%3Alatency%2Chits%3Acount%2Cerrors%3Acount%2CbreakdownAs%3Apercentage&traces=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&start=1690315410527&end=1690920210527&paused=true)
          - [Updating LH Direct Deposit](https://vagov.ddog-gov.com/apm/resource/vets-api/rack.request/bc1e3cb125eb0125?query=%40_top_level%3A1%20env%3Aeks-prod%20service%3Avets-api%20operation_name%3Arack.request%20resource_name%3A%22V0%3A%3AProfile%3A%3ADirectDeposits%3A%3ADisabilityCompensationsController%23update%22&env=eks-prod&spanType=service-entry&topGraphs=latency%3Alatency%2Chits%3Acount%2Cerrors%3Acount%2CbreakdownAs%3Apercentage&traces=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&start=1690315475062&end=1690920275062&paused=true)

## Release Plan

[Release Plan - Direct Deposit Migration from EVSS to Lighthouse](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/evss-lighthouse-migration/direct-deposit-release-plan.md#release-plan---direct-deposit-migration-from-evss-to-lighthouse)
[Prod go/no-go ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63029)
 

## Tasks

<details><summary>Completed Phases </summary>
<p>

```[tasklist]
### 5% rollout 8/7
- [x] Update feature flags to make the feature visible in Production for 5% of users
- [x] Track/monitor analytics
- [x] Validate on Prod with PM and PO
- [x] make decision about next step - yes ramp to 10% - 8/14/2023 - Samara, Tom, Travis, Adam
```

```[tasklist]
### 10% rollout 8/15, Re-Launch 9/12/2023
- [x] Update feature flags to make the feature visible in Production for 10% of users
- [x] Track/monitor analytics
- [x] Validate on Prod with PM and PO
- [x] [Thread](https://dsva.slack.com/archives/C909ZG2BB/p1695735134592459) deciding to launch to 25%
```

```[tasklist]
### 25% rollout 9/26
- [x] Update feature flags to make the feature visible in Production for 25% of users
- [x] Track/monitor analytics
- [x] Validate on Prod with PM and PO
```

</p>
</details> 

```[tasklist]
### 50% rollout 10/3
- [ x] Update feature flags to make the feature visible in Production for 50% of users
- [x ] Track/monitor analytics
- [x ] Validate on Prod with PM and PO
```
<details>
<summary>Future Phases</summary>

### 100% rollout
- [ x] Update feature flags to make the feature visible in Production for 100% of users
- [x ] Track/monitor analytics
- [x ] Validate on Prod with PM and PO

</details>

## Acceptance Criteria
- [ x] feature is fully deployed in production
