### ISSUE TITLE
Appeals | Fix focus on contestable issue page alert

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#60784]
## Value Statement

**_As a_** screen reader user
**_I want to_** focus to be on any alert after trying to continue on a form page
**_So that_** I know what error exists and how to fix it

---
## Background Context

In all three of our appeals forms, move focus to the alert at the top of the page _after_ the user attempts to "Continue" on to the next page. It appears that the focus happens initially, but focus remains on the "Continue" button on subsequent attempts to use the button. This happens in both the HLR and Supplemental Claims forms. For NOD, the user is inadvertently allowed to continue past the contestable issues page without selecting or adding any issues - this needs to be fixed prior to fixing the focus management.

Also, focus must be on the header _inside_ the alert instead on on the entire alert box.

## Out of scope

- Fixing NOD continuation with no selected issues (will be fixed in a separate ticket)

## Acceptance Criteria

- [x] Focus is moved to the alert header for any error state
- [x] A screenreader announces the alert header to the user

## Tasks

- [ ] In any error state, focus must _always_ be moved to the alert header (not the alert)
- [ ] Add unit tests

---

## Definition of Ready
 
- [ ] A11y expert confirmation of focus behavior
- [ ] NOD fix for no selection is in place

## Definition of Done

- [ ] All tasks complete
- [ ] All tests passing
- [ ] A11y expert review of changes

**Comment by eileen-coforma** [comment]
Hey @davidakennedy can you validate this with a screenreader?

**Comment by davidakennedy** [comment]
Works as expected, and moves focus to heading in the alert.

Video of SC form:

https://github.com/user-attachments/assets/d64afdc2-b061-441d-a5f4-1ac230923388

Video of HLR form:

https://github.com/user-attachments/assets/94d62a87-9ed4-4c60-a9c0-06b62d50b8ef

**Comment by Mottie** [comment]
Thanks DK!
