### ISSUE TITLE
Discovery: Terms of Use (TOU) Usability research - planning

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#60793]
#### Terms of Use (TOU) Usability research - planning

Usability test the TOU update with veterans to ensure it's usability and figure out some nuances on the page, like best option for button labels

See docs from [private slack convo](https://dsva.slack.com/archives/C04NYGX8TA8/p1689260485712569?thread_ts=1689260140.630419&cid=C04NYGX8TA8)

#### Tasks
- [x] Collab cycle [kickoff](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/collaboration-cycle-kickoff)
- [x] Collab cycle [design intent](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60961)
- [x] [a11y research ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62359)
   - [x] open ticket
   - [x] discuss setting up research for screen reader
   - [x] make any adjustments needed to prototype
- [x] draft [Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/5247b7834ebca291e07b7716deed4833facecae0/products/identity/Research/2023-07%20Terms%20of%20Use/2023-08%20Terms%20of%20Use%20research%20plan.md)
- [x] draft [convo guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/dd7d219aa70f3c9f322793b5452e04e9e2431e3a/products/identity/Research/2023-07%20Terms%20of%20Use/2023-07%20Terms%20of%20Use%20conversation%20guide.md)
- [x] draft [convo guide for screen reader sessions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/0d0df783a80ee0cf54fb21564e32e3c0e1900284/products/identity/Research/2023-07%20Terms%20of%20Use/2023-08%20Terms%20of%20Use%20convo%20guide%20-%20screen%20reader.md)
- [x] sync with Tom for PO sign off
- [x] finalize research artifacts
- [x] Collab Cycle [midpoint review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)
   - [x] before research address [content feedback](https://app.zenhub.com/workspaces/collaboration-cycle-reviews-61d89e9e5f4c120011a0ad37/issues/gh/department-of-veterans-affairs/va.gov-team/63153)

##### Questions/ideas/setup

* A user must take action to "Accept" or "Decline"
   * The user flow IS interrupted after signing in (they redirect to this page)
   * If a user "Declines" they are automatically logged out
* button language Decline vs. Cancel
* Flow for updated terms
   * May need a slightly different user flow for when the user accepted previous terms but we have new ones to show.
   * In that case, if they hit Decline (or Cancel) we might want to show a confirmation assert that says something like, "If you don't agree to the new TOU you will no longer have access to VA online services"
* Content should explicitly state that a user will be logged out if they decline to accept the terms
   * Additional content is provided stating they still can get access to care over the phone or in person if they don't accept the ToU
* The Terms of Use is in a fixed size scroll
   * No recommendations have been given on whether or not the ToU text needs to be fully scrolled to the bottom before an Agree or Cancel buttons are enabled

- Goals
   * We want users to Accept the Terms of Use
      * So that when bad actors/hackers/fraudsters misuse VA's online services we can prosecute them
      * So we can set rules on how users are able to interact with VA online services (to comply with federal and state laws concerning PII & PHI)
 
* Possibilities for UX research
      * Language of the buttons, Agree vs Accept, Decline vs Cancel
         * What language makes the most sense to user when taking an action
      * Should a user be forced to scroll to the bottom of the fixed height ToU?
         * This is a pattern with most Terms of Use policies, not sure if it should be applied to VA
         * How does this affect limited sight users and other users with disabilities

- Current status
   * We (the Identity team) are currently waiting for the official language to come through after review from the Office of General Counsel (basically the VA lawyers) about what the Terms of Use content should be
   * We met with the Sign up Service team as they have already built a "terms of use policy" on the technical side and our team might** integrate with it, tbd

#### Acceptance Criteria
- [ ] Reviewed by UX Team
- [ ] Reviewed by PMs
- [ ] Documentation has been updated
- [ ] Put published research in drive

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by aparsley** [comment]
Keep up the good work!
