### ISSUE TITLE
Identity Dashboard (FE) - Create a11y test suite

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#60797]
## Description
Create an accessibility test suite that runs against all components OR pages - aka Homepage, Client Config, Teams pages

## Tasks
- [x] Create an a11y test suite
- [x] Ensure running the suite is added to the `scripts` in `package.json`
- [x] Update the README.md to add the command that runs the a11y suite
