### ISSUE TITLE
DR | Clean up review & submit issues page

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#60802]
## Value Statement

**_As a_** screen reader user
**_I want to_** only see my issues on the review & submit page (in review mode)
**_So that_** I don't have to hear the `legend` content in both the review & edit modes

---
## Background Context

The list of issues is normally wrapped within a `fieldset`, which requires a `legend` because of the checkboxes included that allow the Veteran to select API-loaded issues for submission; but on the review & submit page, the list of issues in "review mode" view is only showing the selected issues and not the checkboxes. In this view, we can remove the `fieldset` wrapper and associated `legend` to provide a cleaner page for review.

This change would need to be applied to all of our review forms: HLR, NOD & Supplemental Claims.

Note that in "edit mode" the legend would contain an `H4`, but in "review mode" the legend text is wrapped in a `div`.

<img width="1219" alt="Screenshot 2023-06-23 at 9 52 54 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/5db86cb1-f4a0-40f1-85a0-3c3518d6db27">

## Acceptance Criteria

- [ ] The `fieldset` and `legend` _are not_ included in "review mode"
- [ ] The `fieldset` and `legend` _are_ included in "edit mode", and on the main form page
- [ ] The issues page list is read out as expected by a screen reader
- [ ] All tests are passing

## Tasks

- [ ] Remove `fieldset` & `legend` wrapper in "review mode" in HLR
- [ ] Remove `fieldset` & `legend` wrapper in "review mode" in NOD
- [ ] Remove `fieldset` & `legend` wrapper in "review mode" in Supplemental Claims
- [ ] Evaluate if creating a common folder for this repeated code
- [ ] Add unit tests
- [ ] Verify e2e tests passing

---

## Definition of Ready
 
- [ ] A11y confirmation on removal of wrapper 
- [ ] Discuss with design - this change would make it match the design

## Definition of Done

- [ ] All tasks complete
- [ ] All tests passing
- [ ] A11y expert review of changes

**Comment by saderagsdale** [comment]
Break into smaller tickets. @saderagsdale

**Comment by saderagsdale** [comment]
Tasks:

- Hide div and paragraph below it
- Copy/paste code across decision reviews

**Comment by Mottie** [comment]
Work has been merged for all three decision reviews. Please review when you have time.

<img width="667" alt="sc-after" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/5416f131-7a45-4348-8a93-08f0217b69d2">

**Comment by eileen-coforma** [comment]
Tested it for all three Decision Reviews. Looks good.
