### ISSUE TITLE
Midpoint Review - Content Feedback - Authenticated Experience, Profile, Notification Settings - Default Send Functionality | EPIC

### ISSUE THREAD

**Issue by CherylEvans** [department-of-veterans-affairs/va.gov-team#60818]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [x] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [x] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Great job so far.  I only found 2 minor issues that I listed in the **Must** category.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### **Must**
- No contact information, warning alerts for Desktop/Mobile - Inconsistent language: Please ensure the language is consistent before the Staging Review.
![57409_Desktop_Inconsistent Verbiage_Screen Shot 2023-06-23 at 10.13.35 AM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/f48ed3c1-6869-4179-89b8-347be92e8ced)![57409_Mobile_Inconsistent Verbiage_Screen Shot 2023-06-23 at 10.11.52 AM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/b32cc1b2-fe6c-41ed-b5cb-cda1c51605a5)

- Desktop and Mobile -> partial info, missing mobile, alert expanded > Inconsistent language. Please ensure the language is consistent before the Staging Review.
![54709_Cheryl_1_Mobile Phone verbiage inconsistent_Screen Shot 2023-06-23 at 9.05.21 AM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/a9153f23-d1a6-47da-a263-d07de510eadb)
![57409_Cheryl_1_An vs. Your_Mobile_Screen Shot 2023-06-23 at 8.58.46 AM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/a453799d-860d-44b5-82ff-314b87f9ac1f)

## Duplicate ticket 
- #60817

**Comment by andaleliz** [comment]
- "We don't have your contact information" alerts have been updated for [mobile](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/r9rvgAa) and [desktop](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/9P49mAx) to reflect consistent language, and the latest design

- We've cleaned up the "a" vs "your" language:
<img width="986" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/55992116/99d8a07c-1144-4e40-af78-5b39e74987f3">
<img width="1019" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/55992116/e8970ca2-f331-439d-88a1-202f405f1864">
