### ISSUE TITLE
Design | Enhanced Personalized Experience | Profile "Hub" Research

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#60822]
## Background 
The current structure of the profile lands users into the "Personal Information" section of the profile. This is particularly confusing for screen reader users. See [FE | Profile | Screenreader Accessibility Issue | Sections of Profile are above the H1 #40593](https://github.com/department-of-veterans-affairs/va.gov-team/issues/40593) for specifics on the original problem. 

CAIA helped the team regroup and explore various alternatives. We discussed solutions or 'hacks' to solve the issue of sections of the profile living above the H1. The conclusion we arrived at was to create a "profile page". 

In this ticket we should explore ways of adding a 'hub' or landing page within the profile as a solution to what has been a very intractable problem. 

```[tasklist]
### Tasks
- [ ] Review solutions that exist on other part of the VA website (if any)
- [ ] determine if we need to perform research 
- [ ] leverage internal and external examples to brainstorm potential solutions 
- [ ] do we have the right components in the design system  
- [ ] create mock-up(s)
```

**Comment by andaleliz** [comment]
@mtcA6 this looks good and makes sense!  Thanks for writing this up.

I tweaked the tasks a bit by removing the items related to determining what kind of research we need to do, and if we have the right design system components. I think we can address those items w/ the platform team during design intent. 

Added an estimate so we can have this ready for sprint planning.

**Comment by adamwhitlock1** [comment]
MS account summary / landing page thingy

![ms-account](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/8d9e6eec-203e-42b7-b363-6a242ceb7c84)

**Comment by andaleliz** [comment]
Status update:
- I've gathered screenshots from a variety of sources and placed them in [this Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1690215208596/85132c5e4a025524f742559c6ff773e7f19c4a87?sender=ub868d471cfdb1c56cc0b4512), as well has added to our [GH directory](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/images/screenshots).
- Interestingly, fewer sites had a true profile hub page than I expected.  Many (estimate 60%) have a similar thing to what we do where a person is started in a specific part of the profile. It'll be interesting to learn how Veterans react to our hub when we test it.
- I looked into the collab cycle feedback for the MHV on VA.gov landing page, to see if a11y considerations or other things came up around the 2 column layout they use.  There were no concerns, which is a promising sign that we won't have to be restricted to a single column list.

**Comment by andaleliz** [comment]
@Samara-Strauss out of curiosity, do you have any background info on the decision not to create a hub page for `va.gov/profile` when this version of profile was launched? 

I looked through the [Combine Profile and Account docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account) but couldn't find anything.

**Comment by andaleliz** [comment]
Met with the CAIA folks today and got enough input to explore some concepts! 

Pam and I talked through these points with CAIA:
1. Since we're not yet sure how dependents and NOK will fit into the profile, is it better to focus only on what we know for sure will be there?  
**We decided to focus on the 7 items we know for now, and even in the future we could add these new things (Next of Kin, Dependents, etc) straight into the list, either categorized or not depending on what we decide about categories below**
2. Discussed pros and cons of categorization chunks vs just a straight list. There are various approaches to this out in the wild. 
**We don't think we need categories for the 7 main profile items, so can move forward with an MVP that has no categories. But we could explore the categorization in a user test on a future iteration of this list if we see in analytics or user feedback that ppl are struggling to find things**

3. Another idea we discussed is to have a "quick links" section where we link to specific top profile tasks, like updating mailing address (we could leverage the sub-task flow). If we did that, a link to the dependents and letters tool could make sense.  
**We think this is a great idea to explore in the future, or with user testing, but decided we don't need to do this for MVP.**

4. We discussed whether or not the profile hub page would need the profile menu.
**We determined it doesn't, because the page should designed in a way that that people can find what the need. It's also an accessibility no-no to have duplicate links on a page, and it adds complexity to mitigate that and have the nav**

In the concepts, I reviewed the existing hub patterns on VA.gov and landed on using a card variation to be consistent with what is done elsewhere.  The current guidance favors the white background, black border version of the card; I explored both.  I also tried variations with and without the heading as a link.

All can be seen in [this Sketch file](https://www.sketch.com/s/113f0ee6-e77d-4b1b-bf02-af27580931fe/p/07E02D01-E54B-4ECE-9B5A-838FF0A10CA2/canvas), and I will review with the team tomorrow.

**Comment by andaleliz** [comment]
Feedback from @mtcA6 via Slack:
> - for the quick links on mobile, if we do go that route i feel that should be collapsed to start. <agree also not needed for an MVP it would be something we could explore later
> - Interestingly, I think I like the cards more for mobile, and feel like it's not as needed on the desktop version (does this make me crazy). ie desktop version 2 not super fancy but looks really functional 
> - as for the cards specifically:
>   - version 5 i like that the cards don't read like an alert,
>   - in version 4 it feels really close to our CTA's

**Comment by andaleliz** [comment]
@mtcA6 what are you thinking of when you refer to "our CTAs"? I don't know of profile specific CTAs so I'm wondering if you're thinking of the alert component, or an action link, or something else.

**Comment by mtcA6** [comment]
The alert not the CTA @andaleliz ill see if I can find an example in the am.

**Comment by mtcA6** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/5f5f60b4-b953-443c-a1ff-38c85aebe127)

@andaleliz Reminded me of this.

**Comment by andaleliz** [comment]
Completed review this morning and the team determined that, we want to move forward with this work! 

We'll focus on option 4 in design intent because:
  - It leverages existing design system and content patterns, and already built web components
  - it helps to more closely align the site with the mobile app UX
  - gray cards serve a different purpose on My VA so this helps to differentiate the hub
  
We need to get feedback on during design intent on these questions for sure:
  - do we need the menu on mobile?
  - do detail pages still have the menu?

Next steps
- check out analytics for the mobile menu to get a sense of how people are using it now and inform our think about whether or not we need it on the mobile hub page
- make user flow for design intent

**Comment by adamwhitlock1** [comment]
Apologies for missing the meeting to review this. Great work on the designs @andaleliz

My first gut reaction is the designs with the cards in either gray or white seem the cleanest, and I think personally I prefer the ones with the links at the bottom instead of headings as links. 

I also like the gray colored cards a bit more as it separates them from the background, but understand that those are used for different purposes on My VA so white might be a better choice. 

Option 4 sounds like a great place to start with design intent!

**Comment by andaleliz** [comment]
@adamwhitlock no worries, I'm glad you took some time to rest this morning. You know I would've tracked you down for feedback another way ;) Thanks for coming back to this.

From what I can tell, there aren't any hidden FE complexities about what I'm proposing since its made up of cards and links. I feel like you would've already said something if you spotted something I missed, but if anything does occur to you, please let me know.

**Comment by andaleliz** [comment]
@mtcA6 I've created the flow, and I believe these are the links you'll need to submit the request to schedule design intent. Once you do that, I'll add some more background info to the ticket so they know what we explored and have already discussed:

- User flow is available on the left side of [this page](https://www.sketch.com/s/113f0ee6-e77d-4b1b-bf02-af27580931fe/p/07E02D01-E54B-4ECE-9B5A-838FF0A10CA2/canvas) in Sketch
- [Mobile](https://www.sketch.com/s/113f0ee6-e77d-4b1b-bf02-af27580931fe/a/ZVvVnp3)
- [Desktop](https://www.sketch.com/s/113f0ee6-e77d-4b1b-bf02-af27580931fe/a/JAaAJyk)
- For the purposes of our conversation/comparision, I created versions with the profile menu too. We'd love input on whether or not the reviewers think the menu should be there: [mobile with menu](https://www.sketch.com/s/113f0ee6-e77d-4b1b-bf02-af27580931fe/a/MmxkOqw), [desktop with menu](https://www.sketch.com/s/113f0ee6-e77d-4b1b-bf02-af27580931fe/a/5nPbEpw)

Do you think you look into the analytics mentioned in the first bullet in my last comment?

**Comment by mtcA6** [comment]
@andaleliz thanks for updating the [Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62839) ticket! Excited for the call on Thursday, thanks for the awesome work on this

**Comment by mtcA6** [comment]
> - check out analytics for the mobile menu to get a sense of how people are using it now and inform our think about whether or not we need it on the mobile hub page

@andaleliz [confirmed here](https://dsva.slack.com/archives/C1Q4294JJ/p1691525591192939) that we're not tracking the menu clicks

**Comment by mtcA6** [comment]
@andaleliz Already submitted a ticket for the [same](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63551)
