### ISSUE TITLE
Profile Dashboard - Update

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#60820]
## Issue Description

The Profile team has requested an [update](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60786) to their [Profile edge case dashboard](
https://va-gov.domo.com/page/1834995012)

Their current dashboard is focused mainly on event counts, they need to add some user count metrics.

- number of users who viewed profile page (va.gov/profile) https://staging.va.gov/profile/personal-information

- number of users who searched from profile page (and subpages - as defined in current profile dashboard datasets)
 
- % of profile page users who searched (# who searched/total who viewed)

![image.png](https://images.zenhubusercontent.com/618144c8b17b33313a8c0cbe/8ea6652e-70f2-4db2-8d05-9228a256b952)

## Tasks
- [ ] Review datasets currently used for Profile dashboard to determine if they have the user data needed.
- [ ] if yes build new card(s) as described
- [ ] if no work with @dorseypa1 to update current or create new dataset that will contain the user data needed - then build cards
- [ ] QA against GA user reports filtered to profile page

## Acceptance Criteria
- [ ] Cards created and QA'd
---

**Comment by michelle-dooley** [comment]
Sprint update:  QA work will continue into next sprint.

**Comment by michelle-dooley** [comment]
@ChristineYoungZA - The profile search user count card is correct.  But the total profile user count (those who searched and those who did not) is not correct.  The dataset (BQ - Profile API Requests) you are using is event based and the card is counting events not users, I removed the card from the appendix to avoid confusion.  Looks like we are going to need @dorseypa1 to add 'user' to the 'BQ - Profile API Requests' dataset (or create a new dataset if that messes up current one?!?) in order to get that count.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/93597659/3d024db3-fcb7-424a-94d3-cba04da65aac)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/93597659/4fa22ff8-1539-4eeb-a025-8c1a3aa9497e)

**Comment by michelle-dooley** [comment]
@ChristineYoungZA - per last weeks [slack from phil](https://dsva.slack.com/archives/C01S78V4AUA/p1689274270447219) the dataset was updated with 'user' field so you should be able to complete this.

**Comment by michelle-dooley** [comment]
Closing this ticket.  Will create a new one if needed for the data merge work Phil is working on.
