### ISSUE TITLE
Collaboration Cycle for Public Websites, Benefit Hubs, Mobile App Promotion Banner

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#60829]
### VFS team name

Public Websites

### Product name

Benfit Hubs

### Feature name

Mobile App Promotion Banner

### GitHub label for product

Benfit hubs

## Kickoff questions

<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

July 5, 2023

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

No

### Will your work involve changes to...

Static pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Unsure

### Do you need to capture any additional analytics or metrics?

No

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/Benefit%20Hub/mobile-promotion/README.md

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Notify the Collaboration Cycle team of this ticket in the vfs-platform-support Slack channel.

- [X] I acknowledge that I must notify \#vfs-platform-support after submitting this issue.

Kickoff Slack Thread with VFS team: [Link](https://dsva.slack.com/archives/CBU0KDSB1/p1687545467235939)

</details>

 ## Recommended Collaboration Cycle touchpoints

### Sitewide Content and IA Intake Request 
_note: SW Content reviewed and indicated in comments below that they don't need an intake ticket_
<details>
  <summary>Toggle Sitewide Content and IA Intake Request</summary>

##### VFS actions
- [ ] Complete the [sitewide content and IA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-Content-and-IA-intake-request.2124906551.html)
- [ ] Link to the Sitewide Content and IA Intake Request ticket below

</details>

### Staging Review
<details open>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [ ] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Notify the Collaboration Cycle team of this event with scheduled date/time in team channel
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [ ] I confirm the environment is available and test users have been provided.
- [ ] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
 
**Staging Review artifacts**
  
See Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts). Platform findings are based solely on the staging URL and test users provided, as reviewed during the four days before the Staging Review meeting. Any test cases not covered or any ongoing work taking place during the review period may not be reflected in those findings.  

**Product artifacts** 
- [x] Staging URL
The following links should show an iOS App Store banner when viewed using Safari on and iOS device. **NOTE: Don't dismiss the banner – dismissing it for one page prevents it from appearing for any other page** :

| Category | App Function | VA.gov URL | 
| ------ | ------ | ----- |
|Health care tools | Refill and track your VA prescriptions | https://staging.va.gov/health-care/refill-track-prescriptions/ | 
|Health care tools | Send and receive secure messages from your VA health care team | https://staging.va.gov/health-care/secure-messaging/ 
|Health care tools | Get your records for VA vaccines, such as COVID-19 | https://staging.va.gov/health-care/get-medical-records/ | 
|Benefits tools | Check your disability rating | https://staging.va.gov/disability/view-disability-rating/ | 
|Benefits tools | Review your claim or appeal status | https://staging.va.gov/claim-or-appeal-status/ | 
|Benefits tools | Submit evidence for your claim or appeal | https://staging.va.gov/disability/upload-supporting-evidence/ |
|Benefits tools | Download common VA letters | https://staging.va.gov/records/download-va-letters/ | 
|Payment tools | Review payments we’ve sent you | https://staging.va.gov/va-payment-history/ |
|Payment tools | Update your direct deposit information | https://staging.va.gov/change-direct-deposit/ | 

- [x] Specify which pages are included in the review
  - URLs above only
- [ ] Staging test user information 
  - N/A - Unauthenticated feature
  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
  - N/A
  
**IA artifacts**
- [ ] Please include a link to any [Sitewide Content & IA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) of the findings you received, including an IA review document or intake form.
  - N/A – noted above that CAIA determined no intake ticket was needed 

**QA artifacts**

**NOTE for this section:** The nature of this implementation is that there is no QA possible. Either the banner appears or it doesn't. Banners for all URLs were implemented in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13481) by Public Websites. Functionality was verified at that time in Staging.

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [ ] [Regression test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-regression-test-planRegressionTestPlan)
- [ ] [Test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-test-planTestPlan)
- [ ] [Coverage for References](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [ ] [Summary(Defects) reports](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [ ] [E2E tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-e2e-test-participationE2ETestParticipation) (provide a link to the product’s code)
- [ ] [Code coverage](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-unit-test-coverageUnitTestCoverage) (provide a link to the product’s code)  
  
**Accessibility artifacts**
  
- [ ] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D). For details, see [Prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).
  - **N/A** - As this is out of the box functionality in iOS Safari, which we can not influence, @laflannery reviewed and determined that accessibility was adequate.
  
##### Platform actions
- [x] [Staging review Slack thread with VFS team](https://dsva.slack.com/archives/C52CL1PKQ/p1692732068539919)
- [x] Meeting date/time: August 31, 2023 at 1:30 p.m. ET

##### Platform actions

- [ ] Update this ticket with the Zoom recording
  - Recording URL: 
  - Password:
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

**Comment by wesrowe** [comment]
This feature is a little hard to describe so I thought I'd add help here. [This ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13481) has a screenshot of an example of the iOS Safari Smart Banner. Our MVP/proof-of-concept is to use this out-of-the-box functionality from Apple on a handful of pages; they would look like the screenshot linked above, but obviously promoting the VA mobile app.

**Comment by RLHecht** [comment]
If there's no content that is able to be changed in this, there's no need to open a ticket with Sitewide CAIA.

**Comment by jilladams** [comment]
Next step: Staging Review.

**Comment by allison0034** [comment]
@wesrowe @jilladams no design findings. My only comment is when I view this on my iPhone it blends in a lot with the dark gray background. 

![app](https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/97f7be93-6310-4b65-a86e-7449c9411920)

**Comment by wesrowe** [comment]
Thanks @allison0034. Closing since this is out of our control.

**Comment by wesrowe** [comment]
Just kidding, can't close a comment.

**Comment by briandeconinck** [comment]
No accessibility findings. Chatted briefly with @laflannery, we both agree that in a perfect world there are some minor improvements that could be made, but since it's 100% out of the box and doesn't introduce any barriers to the page content I'm not too concerned.

**Comment by CherylEvans** [comment]
No Content findings.

**Comment by shiragoodman** [comment]
@wesrowe Governance team completed their Staging Review. No findings documented. Please let me know if you have any questions or concerns. Thanks!
