### ISSUE TITLE
Add entry points for Supporting forms landing page

### ISSUE THREAD

**Issue by megzehn** [department-of-veterans-affairs/va.gov-team#60836]
Add links to the [Supporting forms](https://prod.cms.va.gov/supporting-forms-for-va-claims) per the[ IA specs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/form-digitization-supporting-forms.md). 

Add the link to these 2 pages within the disability hub: 

- [How to file page](https://www.va.gov/disability/how-to-file-claim/) - add link to the "More information about filing disability claims" section at the bottom of the page
- [Additional forms page](http://preview-prod.vfs.va.gov/preview?nodeId=906) - add link to the supporting form landing page in a new section for related links at the bottom of the page

## Tasks
- [x] Add entry points (Megan)
- [x] Review (Laura/Randi)
- [x] Publish (Laura/Randi/Megan

## Acceptance criteria
- [x] Entry points are live on the site

**Comment by megzehn** [comment]
Danielle reviewed these entry links and I published!

CC @RLHecht

**Comment by megzehn** [comment]
I'll close this and add it to the Google doc tracker when I'm on my other computer!

**Comment by RLHecht** [comment]
These changes are live. Closing ticket!
