### ISSUE TITLE
Use EFS Volume for frontend build process

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#60835]
# Description
Use an EFS volume to build and store content-build and vets-website.

Rough outline of a plan here --
For the moment since we don't actually want to persist anything, in theory it's as simple as --

* Configure the volume to mount to some path like -- /app/website/slow
* In `start.sh`, we -
   * navigate to that folder and wipe everything out
   * proceed as normal with the init

# Tasks
- [x] Configure the volume to mount to some path like -- /app/website/slow
- [x] Create steps in the start script to navigate to the mount point and wipe out previous contents
- [x] Double check that the script can proceed through the remaining steps without issue

# Acceptance Criteria
- [ ] FE containers build vets-website and content-build in an EFS volume instead of in local container storage
