### ISSUE TITLE
[CHIP] - reduce lorota fields during initiatePreCheckIn

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#60840]
## Description
Reduce the amount of information stored in lorota on initiatePreCheckIn down to:
 - last name
 - DOB
 - appoinmtentIen
 - stationNo
 - patientDFN

This reduction should allow refreshPreCheckIn to continue to work properly and update lorota when called.

## Tasks
- [ ] [CHIP] reduce fields saved in lorota on initiatePreCheckIn
- [ ] [CHIP] Update tests for initiatePreCheckIn
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
@brianseek do we still need this ticket?

**Comment by brianseek** [comment]
I will defer to @stephenBarrs, we did a spike way back when to see if this was possible and it was, but the actual work was never prioritized. Is this still something we want to do?

**Comment by loripusey** [comment]
Is this still the reason we were going to do this?

> This reduction should allow refreshPreCheckIn to continue to work properly and update lorota when called.

**Comment by brianseek** [comment]
That wasn't the reason but the thing that enabled us to do it. The reason was so that we would be storing less PII/user data in LoROTA over the 7+ days that we do for pre-check-in. We would only pull in the needed PII on refresh when the patient was actually doing pre-check-in, then it would get deleted from LoROTA after completion.

**Comment by loripusey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/60840?planning-poker) with Zenhub @brianseek @wullaski
