### ISSUE TITLE
Map upstream data for "choose a location" page

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#60854]
## Task Description
Map the upstream data sources, including people, APIs, and systems, for the choose a location page in the VA direct-schedule flow.

As part of this task:
- [ ] Propose a [collaboration process](https://www.figma.com/file/4OsaXgivaLX1qTxQQf3BDX/Appointments-Data-Mapping-Discovery?type=whiteboard&node-id=209-1581&t=5HT5psdNllMokMkC-4) for doing this initiative and staying aligned with all of the moving pieces. 
- [x] Sync with teams/ individuals who have done similar efforts in the past for a knowledge share. Individuals to sync with:
-Questions to ask: What was the problem the team was trying to solve? What was their solution? What are the pros and cons about their solution? Lessons learned in creating this?
- [x] Kay Lawyer in regard to MHV's Medication team [data tracing xcel spreadsheet](https://app.zenhub.com/files/133843125/e759b169-9393-4d08-b24f-972c2207922e/download)
- [x] Liz Lantz in regard to the [Veteran personal attributes](https://docs.google.com/spreadsheets/d/1BTIlmYyiCInqOiYjIMPCCR2dDf5nmSNLEOmWFMcmXuQ/edit#gid=0) and the [trello board](https://trello.com/b/fk5IBVEe/appointments-object-map)
- [x] Ryan Thurwell in regard to mapping data in general
- [x] Reach out to BE/ dev to ask for help tracing data. 
     - [Response from Marcy ](https://dsva.slack.com/archives/CMNQT72LX/p1689032618173159)
- [ ] [Reflect on the process](https://www.figma.com/file/4OsaXgivaLX1qTxQQf3BDX/Appointments-Data-Mapping-Discovery?type=whiteboard&node-id=225-1244&t=5HT5psdNllMokMkC-4) in order to iterate and scale to other pages
- [ ] Write recommendations and post to GH

## Notes and References
-

## Acceptance Criteria
- [x] Affinity diagram the interview notes from syncing with other teams on their data mapping.
- [x] Comparative analysis of other teams' method of delivering a data map.
- [x] Create a data tracing spreadsheet 
- [ ] Mural with data mapped is complete.

## Deliverables
Link deliverables here

**Comment by outerpress** [comment]
We're pivoting on this one because we don't have enough access to upstream data to provide a detailed map. We're adjusting this to create a high level map and update existing resources.
