### ISSUE TITLE
Update supporting content for "review other upcoming appts" component

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#60857]
## Descriptions 

Veterans had no issues finding out how to review their other upcoming appts from the confirmation pages, e.g., [pre-check-in confirmation page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/zx95r4b), however, the supporting content wasn't as clear to Veterans. For example, it wasn't always accurate to say, "... confirm or check in..." when there was no other appointment to check in to. 

How might we make it more clear to Veterans that there are other actions to take and have it be accurate to the scenario? For example, we wouldn't want to say, "it's time to check in," if there are no appts to check in to. Or, how might we make this content more ambiguous to ensure it encompasses any scenario? 

Note: It's likely we don't need to call too much attention to this area of the page because it's not a required action for Veterans. It could be more useful on the day of an appointment when Veterans have more appts to review later in the day. 

Here's some quotes from Veterans: 

> "I don't see anything that requires me to do anything or anything like that." P 03

> "I'm not sure what I'm supposed to do on this page. It wasn't clear that I had something to do. I just came to see my other upcoming appointments. There shouldn't be anything here to do. It didn't say I had anything to do." P 02

> "I might go back to review upcoming appointments, but it doesn't really seem like it requires me to do anything. The message under review upcoming appointments doesn't seem like I have to do it. It just seems like I either can or can't." P 03

> "If there's absolutely something for me to do, then I would use that arrow button again. To me it looks like it's not a requirement." P 07 [Check in]

> "Yeah, that's a bit confusing. It reads as if I need to check in for other future appointments. It's a little confusing. Why would they want me to check in to another appointment when I'm right here?" P 05 [Pre check in]

## Tasks

- [x] Draft new content 
- [x] Review with any stakeholders, e.g., UX team, Laura, DS team, etc.
- [ ] Update wireframes, symbols, annotations, etc. 

## AC

- [x] Content drafted
- [x] Reviewed by any stakeholders, e.g., UX team, Laura, DS team, etc.
- [ ] Wireframe updated

**Comment by kellysmith1008** [comment]
After some input from Ben (pasted below) we made some changes to the content and @zach-park is updating the spacing and artboards now. Waiting on review by Laura, but as I'm out Monday and Tuesday, Zach knows what to do and we're good with any updates Laura might suggest. Mockups are found in the "Updating supporting content for upcoming appointments" feature in the unified check in sketch file.

Couple things I noticed from the research: 

1) Some Veterans like staying focused on one task, and therefore might not go back to the appointment list, 
2) Using notifications above the appt list after the main task is complete is confusing to most Veterans, and therefore, 
3) Veterans like seeing their upcoming appointments in a chronological list, and if they decide to act on something in the list, then they will, which means to me that we don't really need supporting text underneath "Review upcoming appointments." Sure, there might be more tasks for them to complete, but they know how to find them. I'm not sure we need another reminder for them in this particular scenario. 
Also, we might think about changing "Review upcoming appointments" to "Review" or "View appointments" in case we add past appointments.

**Comment by zach-park** [comment]
@kellysmith1008 , @benbrasso-agile6 , here is the link to the sketch artboard that is ready for review: 
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/zyKMqkb

**Comment by benbrasso-agile6** [comment]
@zach-park comment here for you https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/3CC1B492-4C42-49DC-8236-79253786DC6E/canvas?annotation=d7f362ca-87d6-4942-9b35-27e5180b121d

**Comment by zach-park** [comment]
@benbrasso-agile6 , updates were made to symbols and refined the art boards accordingly. And they are complete now.

**Comment by zach-park** [comment]
Moved to ticket to validate column.

**Comment by benbrasso-agile6** [comment]
validated
