### ISSUE TITLE
Update the "what to do next" notification card pattern above the appt list to reduce confusion 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#60859]
## Description

Some Veterans were confused that the content in the "what to do next" notification card pattern above the appt list was the same information that's listed in the appt list. 

How can we update the notification card pattern to reduce that confusion? 

For example: 

- Shorten amount of information in the pattern. E.g., focus on something like, "Review your contact information and confirm your appointment on February 2 at 8:00." Plus, there might be scenarios where a Veteran only has 1 upcoming appointment. In that scenario, there would be 1 notification card followed by the appt in the appt list. 

## Tasks

- [x] Review how [My VA team is handling information in their notifications](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/p/426AF99C-8159-4972-8BC3-FD5CF5770F3D/canvas)
- [x] Draft new pattern for notification card 
- [x] Note: There are multiple variations for the pattern. For example, review your information now, confirm your appointment, it's time to check in for your appointment, it's almost time to check in for your appointment. 
- [x] Review with  any stakeholders, e.g., UX team, Laura, DS team, etc.
- [x] Update wireframes, symbols, annotations, etc.
 
## AC 

- [x] Pattern drafted with variations 
- [x] Reviewed by any stakeholders, e.g., UX team, Laura, DS team, etc.
- [x] Wireframes updated

**Comment by benbrasso-agile6** [comment]
Started some work https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/6459E0F8-20C9-42F0-A75C-BD4C3497F628/canvas#About

**Comment by benbrasso-agile6** [comment]
I just need to make one small change next week about adding the too early artboard for check in

**Comment by benbrasso-agile6** [comment]
Added https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/dgja1db#Version

**Comment by zach-park** [comment]
Updated the symbol and artboards in the sketch to align the date/time format for the task card (review information).

Artboards:
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/bgwvQKZ#Version
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/mP19p3w#Version

Symbols:
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/4ooyK3z#Version
