### ISSUE TITLE
Transfer CC notification requests to occur on VFS team channel, not #vfs-platform-support

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#60853]
## User Story
As a Governance team member, I want VFS teams to notify Governance of new scheduled CC touchpoints on their own teams Slack channel so that we can reduce clutter and noise on the #vfs-platform-support channel.

Assignee: @briandeconinck 
Peer Reviewer: @it-harrison 

## Description
The Platform Support team has recently adopted some new policies on the #vfs-platform-support channel so no support requests are forgotten and/or unaddressed. This has interfered with the process taken by Governance team when VFS teams contact us to inform us of a kickoff, Design Intent, Midpoint Review and/or Staging Review. Since the Collab Cycle requests from VFS teams on the #vfs-platform support channel are not actually support requests, but more notifications that an event has been scheduled or a kickoff completed, it makes sense that these notifications be moved OFF of the #vfs-platform-support channel and instead occur on the VFS teams public Slack channel.

In order to complete this change, we will need to know the public Slack channel of the VFS team. While this information is available in the VFS Team Roster/Teams tab, it is not reliable. To ensure we have the right channel, we should ask the VFS team to provide their Slack channel in the Collab Cycle Request yaml template.

## Impacted Artifacts
- Moderator Responsibilities for Kickoff
   - operational guidance for Governance team to follow
   - Design Intent, Midpoint Review and Staging Review code blocks
- Moderator Responsibilities for Design Intent 
- Moderator Responsibilities for Midpoint Review
- Moderator Responsibilities for Staging Review
- Collaboration Cycle Request yaml template
- On Support Guidance

## Tasks
- [x] determine how we will update existing CC Request tickets. How will we obtain the correct Slack channel?
   - [Spreadsheet of active CC tickets](https://docs.google.com/spreadsheets/d/11jg14S-BP8uhqp0_jIHZw_kFrKmtpjPyYHIZFS6530M/edit#gid=0), with best-guess public Slack channel
   - Plan to update existing tickets:
      - New ticket for next sprint to go through each ticket to update guidance and include the Slack channel we expect
      - Notify all impacted PMs to ask them to verify or add their public channel
      - Continue to update tickets with correct channels as teams schedule touchpoints (should be temporarily added to moderator docs)
  
### Slackbot auto-responders
- [x] Create Slackbot custom responses for keywords to schedule touchpoints
   - [Confluence page containing response text](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2714271747/60853+-+Slackbot+auto-responses) for...
      - `collab-cycle-kickoff`
      - `collab-cycle-design-intent`
      - `collab-cycle-midpoint-review`
      - `collab-cycle-staging-review`

### Yaml Template
- [x] Create pull request of yaml template 
   - #62566, approved by @it-harrison 
- [x] add a new field for 'Public DSVA Slack channel for VFS team', after GitHub fields, before start date (see image below)
![image.png](https://images.zenhubusercontent.com/5f62315e822e9b2aa88b1f1c/f6acb792-5795-4e09-ad92-9ca47dae1053)
  - Once this change is made and peer reviewed, it can be published right away. No need to wait for operational guidance changes to be made. 
### Operational guidance
- [x] Create draft copies of all 4 moderator responsibilities docs 
- [x] Make changes to the code blocks first, since this is the action the VFS team will take. 
- [x] Identify all occurrences where #vfs-platform-support channel is mentioned and replace with VFS team channel or "your team channel" - wordsmith

### On Support Guidance
- [x] Review the guide and make changes where the #vfs-platform-support channel is mentioned

- [x] Change history post and change announcement via Platform Communication Playbook
   

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS teams inform Governance team of their Collaboration Cycle touchpoints via their own teams Slack channel

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Question - how do we want to handle tickets that are in progress? Do we want to update every DI, MPR and SR section for every open ticket? How would we know the correct Slack channel for the team?

**Comment by shiragoodman** [comment]
@briandeconinck can you please provide a status update? I am assuming this work will continue into the next sprint.

**Comment by briandeconinck** [comment]
Status: Documentation updates in progress, continuing into the next sprint.

**Comment by briandeconinck** [comment]
Question for @it-harrison and @shiragoodman: 

When VFS teams post in their own channels to notify us of Collab Cycle kickoffs/touchpoint requests, which would be better? (Exact wording of each option still TBD.)

**Option A:** In the code blocks for each touchpoint, just tell them something like `Notify the Collaboration Cycle team of this event in your team channel (as listed in the VFS product information section above). Be sure to include the date, time, that you're requesting a Design Intent, and a link to this GitHub ticket. Tag @platform-governance-team-members, or tag @shiragoodman if you're unable to tag the team.`. It's a little wordy but PMs should be able to follow those instructions, and if they don't we'll nudge them to give us whatever is missing in that Slack thread. 

**Option B:** In the code blocks for each touchpoint, tell them something like `Notify the Collaboration Cycle team of this event in your team channel (as listed in the VFS product information section above). See [a template post for scheduling a Design Intent](#)` with a link to a new page on Platform website. The link jumps straight to a sample Slack post for the relevant touchpoint, they just have to change the text to match their request. Additional instructions on that page for if tagging @platform-governance-team-members doesn't work for them and they should tag Shira as a backup.

**Option C:** In the code blocks for each touchpoint, tell them something like `Notify the Collaboration Cycle team of this event in your team channel (as listed in the VFS product information section above) by typing **collab-cycle-design-intent** and follow Slackbot's instructions.` Then we have a Slack custom response that says something like:

```
Thank you for scheduling your Design Intent! Please reply to this post with:
1. The date and time you chose in Calendly.
2. A link to your Collab Cycle request template.
cc @platform-governance-team-members 
```

My preference would be to go with Option C. It's asking teams to remember the least while prompting them in Slack for what we need, and lets Slackbot tag our team (sidestepping the "can't tag a group" issue). Easy to create custom Slackbot responses for kickoff plus three touchpoints, and we probably won't need to do much to maintain them. And if we make the custom response trigger specific enough (eg. collab-cycle-design-intent) it's unlikely to be used accidentally by teams not scheduling touchpoints.

But I want to run that by both of you before I move forward with it, in case you see any issues with that plan.

**Comment by shiragoodman** [comment]
Ooooh I like Option C too. Are we able to set up a reminder that works on all public channels?

**Comment by briandeconinck** [comment]
Yep! Slackbot listens to all channels, public and private. I just added `collab-cycle-design-intent` and tested it in a private DM, should work for you if you want to test it somewhere.

[slackbot-demo.png](https://images.zenhubusercontent.com/61a66f92c1713a0111e338b8/8360d88b-e7a3-48a2-a597-bbc3cd6fa977)

**Comment by briandeconinck** [comment]
Per the discussion at today's stand-up, everyone seems enthusiastic with Option C. @it-harrison and @shiragoodman here's a [first draft for the Slackbot auto-responses](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2714271747/60853+-+Slackbot+auto-responses) at four touchpoints.

My gut feeling right now is it's better to keep these responses short and focused so VFS PMs follow through on the steps we give them, rather than overloading them with reminders about artifacts. But I did add in Platform website links for a little extra exposure. Happy to edit and adjust however each of you sees fit.

**Comment by shiragoodman** [comment]
@briandeconinck I provided some feedback on a few docs. It doesn't look like there were any changes to the moderator responsibility docs for DI, MPR and SR. I don't think we had ever mentioned in those docs that _this is how_ we are notified that an event needs scheduling. Could you add that? Maybe just a "When to use this guidance" heading at the top, prior to the TOC, that explains when this guidance should be followed and how we're notified. What do you think?

**Comment by it-harrison** [comment]
@briandeconinck looks great!

**Comment by shiragoodman** [comment]
@briandeconinck the only thing that I noticed is missing is the Calendly changes. See the[ 2 comments on this draft page. ](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2714271747/60853+-+Slackbot+auto-responses) 

I see you closed this out (likely to meet the sprint end date) however are you still planning on publishing/announcing changes today? Please let me know. I can make the changes to Calendly.

**Comment by briandeconinck** [comment]
@shiragoodman [Draft text for Calendly](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2724201344/60853+-+Calendly+update), more or less consistent with the similar checkbox in the yaml template for kickoff.

**Comment by shiragoodman** [comment]
thanks @briandeconinck . We have a bit of a problem. Design Intent and Midpoint use the same Calendly event, so we can't have 2 different acknowledge statements. Should we just combine them into this?

> I acknowledge that I must notify the Platform Governance team that I have scheduled the event by posting "collab-cycle-design-intent" or "collab-cycle-midpoint-review" in my team's Slack channel at least 2 business days in advance, per the guidance in the Collaboration Cycle Request ticket.

Do you think we need to specify which is which or should we give people the benefit of the doubt?

**Comment by briandeconinck** [comment]
@shiragoodman Ah, of course! I wasn't thinking about that. I think combining them like that makes sense. If they really do start to get mixed up maybe we can revisit but I'd like to think it's straightforward enough that they can keep things straight.

**Comment by shiragoodman** [comment]
@CherylEvans can you help please? Check out the last 4 comments in this ticket.

**Comment by CherylEvans** [comment]
@shiragoodman @briandeconinck Looking at it now.

**Comment by CherylEvans** [comment]
@briandeconinck @shiragoodman This is as short as I could get it and still retain content standards. 

"I acknowledge I must notify the Platform Governance team I have scheduled the event by posting "collab-cycle-design-intent" or "collab-cycle-midpoint-review" in my team's Slack channel at least 2 business days in advance, per the guidance in the Collaboration Cycle Request ticket."

I suggest abrieviating Collaboration Cycle Request ticket to Collab Cycle Request ticket, or CC Request ticket.
You could also take out the word "Platform."  
How about this:
"I acknowledge I must notify the Platform Governance team that I've scheduled the event by posting "collab-cycle-design-intent" or "collab-cycle-midpoint-review" in my team's Slack channel at least 2 business days in advance, per the guidance in the Collaboration Cycle Request ticket."

**Comment by shiragoodman** [comment]
thanks @CherylEvans ! I'll see what fits. However we still need to troubleshoot the problems with the trigger words and Custom responses.
