### ISSUE TITLE
Update supporting content for "review other upcoming appts" component

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#60856]
## Descriptions 

Veterans had no issues finding out how to review their other upcoming appts from the confirmation pages, e.g., [pre-check-in confirmation page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/zx95r4b), however, the supporting content wasn't as clear to Veterans. For example, it wasn't always accurate to say, "... confirm or check in..." when there was no other appointment to check in to. 

How might we make it more clear to Veterans that there are other actions to take and have it be accurate to the scenario? For example, we wouldn't want to say, "it's time to check in," if there are no appts to check in to. Or, how might we make this content more ambiguous to ensure it encompasses any scenario? 

Note: It's likely we don't need to call too much attention to this area of the page because it's not a required action for Veterans. It could be more useful on the day of an appointment when Veterans have more appts to review later in the day. 

## Tasks

- [ ] Draft new content 
- [ ] Review with any stakeholders, e.g., UX team, Laura, DS team, etc.
- [ ] Update wireframes, symbols, annotations, etc. 

## AC

- [ ] Content drafted
- [ ] Reviewed by any stakeholders, e.g., UX team, Laura, DS team, etc.
- [ ] Wireframe updated

**Comment by benbrasso-agile6** [comment]
dupe, closing
