### ISSUE TITLE
Change pre-check-in text message to better influence action 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#60852]
## Description 

Some Veterans didn't feel that the [pre-check-in text message](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/DEPQpLj) required action. For example, Veterans might not feel a sense of urgency to check if their information is up to date. They either know it's up to date, hasn't changed or they may know that MSAs will ask to verify it once they arrive for their appointment.  

How might we edit the message to create a better sense of action and urgency to start the pre-check-in process? 

## Tasks

- [x] Draft new content for the pre-check-in text message
- [x] Review with any stakeholders, e.g., UX team, Laura, etc. 
- [x] Update wireframe
- [x] Note: Does the new content impact content in other wireframes? If so, document those scenarios. 

## AC

- [x] Content drafted 
- [x] Reviewed by any stakeholders, e.g., UX team, Laura, etc. 
- [x] Wireframe updated
- [x] Note: Does the new content impact content in other wireframes? If so, document those scenarios.

**Comment by kellysmith1008** [comment]
[I've drafted some options](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/A28BC241-B36B-47C8-A9BB-C72D8ECB9481/canvas) that include just different spacing, updating the text, and using logic in responses and have shared with the UX team for feedback

**Comment by benbrasso-agile6** [comment]
Updated https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/A28BC241-B36B-47C8-A9BB-C72D8ECB9481/canvas

**Comment by benbrasso-agile6** [comment]
@cgednalske can you do validation on this please?

**Comment by cgednalske** [comment]
@kellysmith1008 @benbrasso-agile6 I apologize for throwing this question out now - just getting up to speed on this - but is there a way we can add to the "save time" part to further safeguard against the "well, my info is already correct" sentiment we heard in research? Maybe to specifically state that they WILL be asked to review at their appointment / their info does need review (even though it might be correct)? Or has this already been explored?

_You'll need to review your contact information when you check in. Save time before…
Your contact information needs to be reviewed. Save time before…
We'll ask you to review your contact info when you check_ in…

**Comment by benbrasso-agile6** [comment]
Updated https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/A28BC241-B36B-47C8-A9BB-C72D8ECB9481/canvas#Version

**Comment by kellysmith1008** [comment]
@cgednalske @benbrasso-agile6 I left a comment in the text message proposal. I'm not sure it fully makes sense - I either need to review my contact information or I need to check to see if it's up to date. But telling me to do both isn't necessary. Can we lean more towards Laura's suggestion (tagged in the comment)?

**Comment by benbrasso-agile6** [comment]
Your call. Tried to account for everyone’s feedback.
