### ISSUE TITLE
[SPIKE] Determine if notification card can be read out as more important for AT users

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#60865]
## Description 

To better draw attention to the notification card above the appt list, e.g., [review your contact information card in pre-check-in](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/bgwvQKZ), for screen reader users, is there something we can do to have this information read out as a distinct group of important information in order to separate it from the appt list lower on the page? 

## Tasks

- [ ] Ask in one of the a11y help channels in slack if there's a way to accomplish this for our scenario. 
- [ ] Document findings in this ticket
- [ ] Create f/u ticket with implementation and next step

## AC 

- [ ] Document findings in this ticket
- [ ] Create f/u ticket with implementation and next step

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 I have a feeling Christina may be better suited to help with this ticket as she's done a lot of work with Ya-ching and the a11y team already. Certainly happy to help out, but not sure I'm the best support for Ya-ching :)

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 Christina is out for the next 2 weeks :)

**Comment by benbrasso-agile6** [comment]
Feel like this was solved already
