### ISSUE TITLE
[SPIKE] Determine if notification card can be read out as more important for AT users

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#60867]
## Description 

To better draw attention to the notification card above the appt list, e.g., [review your contact information card in pre-check-in](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/bgwvQKZ), for screen reader users, is there something we can do to have this information read out as a distinct group of important information in order to separate it from the appt list lower on the page? 

> "Okay, so, it's okay if it wants me to check if my information is correct, but it should just take me to where my information is. Taking me to a page looking at all my appointments, it doesn't make sense to me. I would expect it to take me to a place to review my information. All this other stuff, especially with a screen reader, you're forcing me to read through all this information, which I probably wouldn't do because of time, you know. This is like a calendar of all my appointments, but that's not really what the link said I was going to do. This is kind of annoying. If there was a place to review my other appointments link when I got done with all that, then it shouldn't have been on that first place to begin with. That text should have sent me to that appointment and that's the only thing that should have been on that page. That's not what the text was about."

> "I'm not sure what I'm supposed to do on this page. It wasn't clear that I had something to do. I just came to see my other upcoming appointments. There shouldn't be anything here to do. It didn't say I had anything to do." 

> "What to do next isn't super clear. I don't think it's too much information, but maybe just a wording issue. But, with screen readers, sometimes the headings are repetitive and I'm getting repetitive information on the next page."

## Tasks

- [ ] Ask in one of the a11y help channels in slack if there's a way to accomplish this for our scenario. 
- [ ] Document findings in this ticket
- [ ] Create f/u ticket with implementation and next step (e.g., do we need to add an annotation for markup that's needed)

## AC 

- [ ] Document findings in this ticket
- [ ] Create f/u ticket with implementation and next step (e.g., do we need to add an annotation for markup that's needed)

**Comment by loripusey** [comment]
@cgednalske right down the resolution as brought up by Brian

**Comment by cgednalske** [comment]
Brian confirmed that what we have works fine for accessibility and would be the expected behavior. If we ever want the cards to read out as more urgent we'll need to use something with alerts, but as is he did not think it was necessary to do so and an alert approach would require changing our designs.
