### ISSUE TITLE
Tech Discovery - Fix 4142 embedded in 526 flow - Frontend

### ISSUE THREAD

**Issue by aurora-a-k-a-lightning** [department-of-veterans-affairs/va.gov-team#60878]
## Issue Description

Follow up for task #58753 to discover what would need to be done to implement the embedding of the changes to the 21-4142 form into the 21-526EZ form. 
---
## Tasks
How would we...
- [ ] Approach "page migration"?
- [ ] Make reusable "Do you want to limit the information we can request?" question to the current 526 implementation?
- [ ] Make reusable components for items such as the "Authorization" question and text?
- [ ] Append/amend "Conditions you are being treated for field in provider information"?
- [ ] How do the two workflows look together? What does the branching look like if we allow the users to do both workflows (upload _**and**_ fill out a form)?
- [ ] Anything else discovered?
- [ ] Look into using a checkbox list of disabilities rather than a freeform text field, making sure to use the same ordering as other existing lists
- [ ] Look into returning a string for disabilities list (turn the list of checkboxes into a string). 

## Acceptance Criteria
- [ ] Document/diagram/make cave wall paintings of answers to discovery questions
- [ ] Update [placeholder ticket ](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/59392) with AC, etc
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by christinec-fftc** [comment]
### Summary of Discovery findings
------------------------------------

### Page Migration
For each of the new or modified pages, I mapped out some notes about relevant form fields for each. There are 6 pages with modifications and 2 new pages. Walked through each of these with Lydia and discussed the need for any page migration handling. In general, we are not adding any new, required fields, so there is no need to redirect the user to fill out any new form fields. It looks like the only page migration work will be for the private-medical-records page where we are changing from a yes/no question to checkboxes.

**Modified page: evidence-types**
new boolean field for 'Nothing you provide, only VA records we can find'

**Modified page: evidence-types-bdd**
new boolean field for 'Nothing you provide, only VA records we can find'

**Modified page: private-medical-records**
we are changing from radio buttons to two checkboxes, so we will need to add new fields and migrate the existing value appropriately

**Modified page: private-medical-records-release -> other-medical-records-provider**
new field for list of conditions, array of strings
note: changing path could be challenging for analytics and implementation. from skimming the repo, not seeing any examples of conditional path names. design says if this is a heavy lift, we can keep the existing url.

**New page: other-medical-records-limit**
reuse existing field for limitedConsent. consider adding a max length

**New page: other-medical-records-authorize**
this is a new page, but there is already an existing field for acknowledgment

**Modified page: private-medical-records-upload -> other-medical-records-upload**
similar note about heavy lifts when changing url's
changing document type requires vets-json-schema change. this could be tricky while we're in pre-deploy phase. will have to try out using updateSchema to modify the available doc types or duplicate the schema temporarily

**Modified page: summary**
no form changes, just markup

### Reusability
Initially considered working with the team that built the standalone 4142 form to refactor markup into the platform dir for reuse. However, since learned that there is a third version of 4142 for supplemental claims and that each react application is intentionally isolated. Also learned that the existing 4142 ancillary form in 526, already has most of the content in the mocks so we would just reuse that

### Disability List vs Freeform string
The VA Medical Records page is one of the existing pages that has a list of disabilities. There are a couple of other pages (e.g. Summary of Disabilities and Rated Disabilities) with lists, however, the VA Medical Records page is the most similar to how the 4142 form would look and behave.

Note that there is no consistency in how the list of disabilities is displayed. The summary page lists rated disabilities and then new, while the VA Medical Records page lists new and then rated. Perhaps this is something we may want to do research on to explore all three options (the third being to alphabetize them all together). From talking to Robin, this was not intentional and likely an oversight. Question for our team, do we want to go back and make all of these lists consistent?
![image.png](https://images.zenhubusercontent.com/641341411444ec27c3eb60a4/56548fc2-82f8-4663-9403-1688b1fda6e4)

Implementation-wise, it seems pretty straightforward to build the list and display. However, storing, submitting, retreiving, displaying the data could be challenging. There is a submit transformer (src/applications/disability-benefits/all-claims/submit-transformer.js) where we can massage the data as needed to transform it from an array into a delimited string. Similarly, we’ll need to transform in the pre-fill transformer as well. When going back and forth, we’ll need to make sure we handle any special characters appropriately (for example, we wouldn’t want to use a comma as a delimiter, since the conditions themselves may contain commas)

### Other findings
We already knew about the existing 4142 form in 526 and the standalone 4142. It turns out the team working on supplemental claims also has a version of 4142. Have we met with their designer yet about this?  Couple things to note 1) SC design has more of a 1 question per page flow for evidence types whereas the DBEx version has 4 checkboxes with some validation logic that the 4th checkbox must be solo 2) SC design has some added alerts for when a user tries to Remove (delete) a facility (latest guidance is to have a confirmation for any destructive actions)

### Resources
[Standalone 4142](https://staging.va.gov/supporting-forms-for-claims/release-information-to-va-form-21-4142/)

[VA Forms Library - How to use updateSchema and replaceSchema](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-use-updateschema-and-repla)

[Supplemental claims 4142 mocks](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/p/274ABD98-987B-4C4D-BB93-8FCE3DD6C3DE/canvas)

**Comment by christinec-fftc** [comment]
Went over the findings with the team during 16th min today. We are ok to close this ticket with the findings we have. Given that we need to revisit design, we're not ready to update the placeholder ticket yet.
