### ISSUE TITLE
[SPIKE] Determine implementation needed for adding confirmation status to appt list

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#60877]
## Description 

Veterans thought it would be helpful to have an appt confirmation status within each appt summary card in the appt list. 

Therefore, how might we incorporate a confirmation status? 

Things to think through: 

- Shouldn't use same patterns and icons as check in status
- Can we use one status that encompasses the two scenarios: appt has been confirmed or contact information is up to date
- Would confirmation status ever be presented alongside check in status? E.g., what if a Veteran wants to confirm an appt on the day of another appt? 
- How to indicate when the confirmation window begins? E.g., "Confirming your appointment is not available yet."

## Tasks

- [x] Create low-fi wireframe to communicate, 1) when confirmation statuses appear, 2) how to resolve the two pre-check-in variations, and 3) how might they co-exist with check in statuses 
- [x] Create f/u ticket for wireframe implementation 
 
## AC

- [x] Low-fi wireframe created to communicate potential solution 
- [x] F/u ticket created for wireframe implementation

**Comment by benbrasso-agile6** [comment]
Started some thoughts https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/48EFB134-0DED-4A6F-A482-E7500A68C459/canvas#Version

**Comment by benbrasso-agile6** [comment]
@loripusey we're going to close this ticket based on feedback we got at design system meeting. we need to try a different idea. the ticket for that idea is here https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/61802

Can we pull this into next sprint?
