### ISSUE TITLE
Create styleguide for comms

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#60880]
## Tasks

- [x] Create outline of comms style guide 
- [x] Identify items to leverage from VA, random message guidance, and define outstanding components with design team
- [x] Socialize with Anthony and design team for feedback
- [x] Draft style guide 

## Acceptance Criteria

- [ ] Draft style guide has been circulated with Sitewide and partners for feedback

**Comment by MOStudioCarolyn** [comment]
Style guide is being drafted here https://docs.google.com/presentation/d/1kaTivPzALGZ-RGPN6TVtvEaXwRiD6-M3/edit#slide=id.g19506a99550_0_7

**Comment by MOStudioCarolyn** [comment]
Updated style guide will be shared at Design Crit Mon 8/14
