### ISSUE TITLE
[FE] My VA: Audit code for cleanup

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#60886]
## Background
Before we can proceed with the standard post launch code cleanup for the audit ux improvements we need to conduct an audit of the code to identify everywhere that needs to be cleaned since we've run into issues recently where old code/conditions were causing problems resulting in different versions of My VA being accessible to users. We caught this in the analytics where were seeing activity on event tags associated with links that users should not have been able to see/engage with. See tickets below for reference on those issues:

- #57991
- #47243
- #59400 

## Tasks
- [ ] Review code and identify everywhere that needs to be cleaned up
- [ ] Document where cleanup needs to happen in the comment section of this ticket
- [ ] Confirm with other devs (consult platform documentation if needed?) on appropriate/best practices way to "get rid of old code" (we want to make sure we're not breaking any platform or VA rules)
- [ ] Review with another dev for feedback
- [ ] Let PM know when complete so she can update #60360 

## Acceptance Criteria
- [ ] Areas for code cleanup are identified

**Comment by ajakabcin** [comment]
Thanks @dellerbie this is so thorough and extremely helpful! I've updated our existing post-launch code cleanup for the 5pt ticket you identified above and created a new one for the second part. Part 1 slotted for next sprint, and part 2 for sprint after that but we can discuss more on Wednesday too!

* part 1 #60360 
* part 2 #62899
