### ISSUE TITLE
Coordinate with VEO

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#60905]
In order to send out our Reactivation test email - Version A, we will need coordinate with VEO on the details for sending. They will send the email out using the GovDelivery platform, using content & data provided by us.

## Tasks
- [x] Discuss handoff process with VEO
- [x] Determine approvals process
- [x] Compile list
- [x] Compile content
- [x] Provide mock-up
- [x] cc stakeholders when sharing content
- [x] Review draft email

**Comment by alevindecanini** [comment]
Test email: https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1688151732708/d4b459844030f35aaca089c114003db6bb0c82f1?sender=uaaa67493ae613f0003928743

**Comment by alevindecanini** [comment]
Final comments incorporated, scheduled to go out tomorrow 7/6
