### ISSUE TITLE
Create and add PACT Act banner alert in Spanish

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#60901]
## Issue Description

We added a banner alert to the top of our [PACT Act](https://www.va.gov/resources/the-pact-act-and-your-va-benefits/) page about filing a claim by August 9 to be eligible for backdated benefits. We need to get this translated into Spanish and add to the top of the Spanish page.

When we create the banner alert in Drupal, open the English version to replicate what pages the alert will show on (be sure to select the Spanish version of the page).

Word doc sent to translators: [https://app.zenhub.com/files/133843125/39eb2ec0-2c86-4b84-90c3-911303b64cfc/download](https://app.zenhub.com/files/133843125/39eb2ec0-2c86-4b84-90c3-911303b64cfc/download)

## Tasks
- [x] Send text to translators (Randi)
- [x] Create banner alert in Drupal (Ana)
- [x] Review and publish (Megan)

## Acceptance Criteria
- [ ] Spanish banner alert is live on the page

**Comment by RLHecht** [comment]
Here's where in Drupal you create a banner alert: https://prod.cms.va.gov/node/add/banner

**Comment by aliyahblackmore** [comment]
**Update here:** 

- Translation will be back to us by 7/6. 
- In the meantime, we'll add a note on the page saying that the page is awaiting translation.
 This is the alert we used on the [Spanish COVID page](https://prod.cms.va.gov/block/233?destination=/admin/content/alerts).

**Comment by aliyahblackmore** [comment]
Hi @ABeltran77 - this is the document back from the translators. This is ready for you to add to Drupal.

[LS-2023-0120945-SPA-FINAL_Pact Act banner alert for translation 6_26_23.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12005032/LS-2023-0120945-SPA-FINAL_Pact.Act.banner.alert.for.translation.6_26_23.docx)

**Comment by aliyahblackmore** [comment]
Noting here that @ABeltran77  doesn't have the right permissions to add banners in Drupal. She's in the process of getting this and is in convo with CMS support.

Because the deadline is August 9th and this is already up on the English page, I've added in the banner content. 

@megzehn this is ready for you to review and publish! 

**This is the revisions preview link:** 
https://prod.cms.va.gov/node/58406/revisions

- I chatted with Ana about removing the period from the header - she's okay with that.
- I left in the exclamation points on the last sentence - Ana said that's okay as it's highlighting emphasis.
- I added "(en ingles)" to the end of the links since we're leading to English pages. I pinged Ana to confirm this. If needed, can you remove if Ana says otherwise?
