### ISSUE TITLE
Create and add PACT Act banner alert in Tagalog

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#60902]
## Issue Description

We added a banner alert to the top of our [PACT Act](https://www.va.gov/resources/the-pact-act-and-your-va-benefits/) page about filing a claim by August 9 to be eligible for backdated benefits. We need to get this translated into Tagalog and add to the top of the Tagalog page.

When we create the banner alert in Drupal, open the English version to replicate what pages the alert will show on (be sure to select the Tagalog version of the page).

Word doc sent to translators: [https://app.zenhub.com/files/133843125/39eb2ec0-2c86-4b84-90c3-911303b64cfc/download](https://app.zenhub.com/files/133843125/39eb2ec0-2c86-4b84-90c3-911303b64cfc/download)

## Tasks
- [x] Send text to translators (Randi)
- [x] Create banner alert in Drupal (Ana)
- [x] Review and publish (Megan)

## Acceptance Criteria
- [ ] Tagalog banner alert is live on the page

**Comment by RLHecht** [comment]
Here's where in Drupal you create a banner alert: https://prod.cms.va.gov/node/add/banner

**Comment by aliyahblackmore** [comment]
Update here:

- Translation will be back to us by 7/6.
- In the meantime, we'll add a note on the page saying that the page is awaiting translation.
    This is the alert we used on the [Tagalog COVID page](https://prod.cms.va.gov/block/236?destination=/admin/content/alerts).

**Comment by aliyahblackmore** [comment]
Hi @megzehn this is also ready for you! 

**Preview link to banner:** 
https://prod.cms.va.gov/banner/mag-file-ng-inyong-claim-sa-ilalim-ng-pact-act-hanggang-agosto-9-upang-maging-eligible-sa-mga-retroaktibong-benepisyo

- I added "(sa English)" to the end of the links, since they're going out to English pages. We've used that on COVID pages (like this [vaccines ](https://www.va.gov/health-care/covid-19-vaccine-tag/)page)

**Comment by megzehn** [comment]
Thanks so much, @aliyahblackmore! This one is published, as you already know :)
