### ISSUE TITLE
Update vets-api Manifests to use unique names

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#60924]
# Description
Given that we want to operate multiple preview environments at the same time in order to experiment with resolutions to the issues we are encountering with the FE pod, we need to use unique names for the resources created in the backend pod.  At the moment, if we stood up multiple PE instances, there would be resource collisions due to overlapping names.

# Tasks
- [x] Determine which resources are using static names in the backend pod
- [x] Alter the manifests to use dynamic names based on the PE characteristics like source ref
- [x] Test the dynamically determined names for regressions in functionality
- [x] Verify that more than one PE instance can exist without collisions

# Acceptance Criteria
- [x] We are able to operate more than one PE instance without resource name collissions

**Comment by cyriltech** [comment]
After going through the 2000 line values file and secret for vets-api and identifying some of the resources that needs to be unique across multiple preview-environment, I decided to spin up another preview-environment app.The goal is to have Argocd identify all the resources that are conflicting and list them out.
![image.png](https://images.zenhubusercontent.com/6385292bddbc0cbb14b84a51/b2a6c897-9d52-440c-9665-caa319881b1f)
![image.png](https://images.zenhubusercontent.com/6385292bddbc0cbb14b84a51/cf91bcfa-77df-4d40-b35b-0a28aa6b99cb)

Next step is to come up with a solution; one of which I am thinking is to use GHA to pass a UID from each branch and append it to each vets-api resources.

**Comment by cyriltech** [comment]
Putting down a list of values that needs to be unique.
I started looking into a possible GHA workflow to append unique values per vets-api-pe instance.
name: Templating values file and Deploying

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV

      - name: Template values file
        run: |
          sed -i 's/__UNIQUE_SERVICE_NAME__/vets-api-${{ env.BRANCH_NAME }}/g' values.yaml
          sed -i 's/__UNIQUE_APP_SELECTOR__/vets-app-${{ env.BRANCH_NAME }}/g' values.yaml

      - name: Deploy
        run: |
          #  deployment script 

Something like this, Will reach out to Curt when the complete template values are identified.

**Comment by pjhill** [comment]
Hey @cyriltech -- I take from this code block that the two main things we need to accommodate would be service names and app selectors. I'm bad at `sed`, but it looks like this code is rewriting the values used in a given values file to an env variable's value.  Is this workflow rewriting the values in the file after it's created? Would it be better to create the values file in GHA based on the event that causes the Preview Environment to spin up?

**Comment by JoeTice** [comment]
**Sprint 30 Update** - IN PROGRESS. Progress was made on this task, but this was deprioritized in favor of focusing on the yarn install issue that is currently blocking us from requesting the WASA scan.

**Comment by cyriltech** [comment]
@pjhill After a thorough look at the values file and also thinking best options with best design, I will go with the existing GHA workflow that Curt is using for the template values file for vets-website.

**Comment by cyriltech** [comment]
Update -- Within a test namespace I have deployed two copy of vets-api pe  by making some of the values unique. So far not all the resources are deployed. The process of deployment involves identifying a resource that needs to be unique, make it a unique variable then deploy with helm. After all resources are successfully deploy I intent to push my changes and deploy with Argo cd then share the template values with Curt.
![image.png](https://images.zenhubusercontent.com/6385292bddbc0cbb14b84a51/a686ba76-079c-42eb-919c-ea4bc87c5796)
![image.png](https://images.zenhubusercontent.com/6385292bddbc0cbb14b84a51/7f4beee8-924c-498e-9c42-aaa2013bda73)
![image.png](https://images.zenhubusercontent.com/6385292bddbc0cbb14b84a51/5bf5e468-75ed-40a6-a468-7e2907cae204)

**Comment by cyriltech** [comment]
Another instance of preview-environment is launched. I have identified and made some resouces unique. Still getting some warnings from Argocd console which I am using one by one to change in the values and secret files for vets-api. I had a conversation with Curt about the changes I am making and how GHA will substitute static values and make them dynamic.
Next steps involve completely clear all the warnings then pass a list to Curt.
![image.png](https://images.zenhubusercontent.com/6385292bddbc0cbb14b84a51/a2f34485-9111-40b1-a50c-43a0837e418b)

**Comment by cyriltech** [comment]
Update --since we are importing helm deployment from the Eks migration team work, there are some hardcoded values that I can not change from the values file
1)KIND
DatadogMetric
NAME
sidekiq-enqueued-job
2)Kind 
Middleware
traefik-real-ip
3) Kind: Middleware
traefik-real-ip-header

**Comment by cyriltech** [comment]
Warnings have been fixed except for Traefik-real-ip and traefik-real-ip-headers. ![image.png](https://images.zenhubusercontent.com/6385292bddbc0cbb14b84a51/10914438-1df9-43ef-848a-70f914d38796)
![image.png](https://images.zenhubusercontent.com/6385292bddbc0cbb14b84a51/fae102ff-9ec1-4575-8b01-039cfdc88ff7)
I have a meeting setup with tech team 1 to discuss a possible solution.

**Comment by cyriltech** [comment]
Update --We discussed the conflicting resource name with tech team 1 and also agreed to change the static names of trarfik-real-ip to something dynamic. The changes have been implemented which include releasing a new helm version, updating preview-environment helm chart to point to the new version 0.12.07. 
After deployment argocd displayed a new error, to fix it I had to upgrade to updated values file for new helm release. 
Few changes to implement and ticket expected to be close by the end of this sprint

**Comment by pjhill** [comment]
We can currently manually create as many uniquely resource PEs as we want. Once this [PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2099) is merged then we will be able to allow the creation of each automatically generated Preview Environment with uniquely resourced `vets-api` components.
