### ISSUE TITLE
Review the "forms process" template and incorporate

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#60927]
## Purpose
Tricia shared a [form process](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Product/form_process.md) template she'd created to keep the process order clear

Notes in the SDT Confluence space [here](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2685108229/VFF+Team+Forms+Process+Notes)

Converted to Confluence page [here
](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2686255107/VFF+Team+s+Forms+Process+template)
(a bit easier to question/comment in)
## Tasks
- [x] Review document
    - [x] @tayism 
    - [x] @twoangstroms 
    - [x] @steel36 
- [x] Translate forms process into stickies and a 2nd parallel framework
- [x] Insert these items into the [Timeline Mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1687545549079/60ee3cafbdfe7050f114ea209098641e0ccbad01?sender=u4397b715dc3690a417b71483)
- [x] Create a 3rd Timeline framework to capture both types
- [x] share Timeline w/ VFF team; ask for further details where needed

## Acceptance Criteria
- [x] Timeline represents current understanding

**Comment by steel36** [comment]
Will rollover to next sprint; continued buildout
