### ISSUE TITLE
PM/BE | Profile | EVSS>LH | Direct Deposit C&P | Privacy and security review

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#60939]
Submit a ticket for privacy and security review. 

Questions requiring answers in secure repo. 

```[tasklist]
### Tasks
- [x] review and finalize release plan w/Samara
- [x] Check w/tom to make sure things are ready to go
- [x] locate the privacy and security ticket queue [(probably in platform docs)](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/privacy-security-infrastructure-readiness-review)
- [x] [submit a ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/privacy-security-infrastructure-readiness-review#Privacy,security,infrastructurereadinessreview-Request) - ticket submitted [#1059](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1059)
- [x] pull together any other documentation needed [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/95947f796f73c3fc008549338e7adc510495c938/products/identity-personalization/profile/direct_deposit/lighthouse/psir_prep.md)
```
