### ISSUE TITLE
HLR | Intro Page Updates

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#60947]
## Value Statement
**_As a_** Veteran navigating through the form
**_I want to_** have a consistent VA.gov experience
**_So that_** I can have a seamless experience.

---
## Background Context
The following two issues were found by the content team during H3 review.

On the intro page of the form in staging, we should consider getting rid of steps 3 and 4 "VA review" and "Decision." The Veteran doesn’t have to complete these steps, so they don’t need to be listed as steps.

On the intro page of the form in staging, we noticed that the H2s had H2 tags with H3 font size. And the H3s had H3 tags with H4 font size. Is that intentional?

## Acceptance Criteria
- [x] Process subway only shows steps relevant to the veteran
- [x] Style of the introduction page is consistent with other decision review forms

## Designs and Build Notes
- [Content Source of Truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/higher-level-review/design/content-source-of-truth.md)

## Tasks
- [ ] Remove steps 3 and 4 in the process subway
- [ ] Remove CSS styles from headers, so it matches Supp Claims

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by saderagsdale** [comment]
@rocio-desantiago will check SC code and add an estimate

**Comment by rocio-desantiago** [comment]
@eileen-coforma this one's ready for validation, and also wanted to note a couple of rabbit holes I went down from checking if HLR Intro Page was consistent in Design with the other forms:

| Question | Example |
| ------- | ------ | 
| Should HLR have this `va-additional-info` for "What happens after I apply?" | <img width="3000" alt="SC-additional-info" src="https://images.zenhubusercontent.com/61a57416e6469e7067eb4a98/4d0b9797-dbd6-47a1-b64e-16955d79a1a3"> | 
| NOD has something similar for what to expect after steps completed | <img width="3000" alt="NOD-additional-info" src="https://images.zenhubusercontent.com/61a57416e6469e7067eb4a98/6333165d-7f66-402d-8fc9-96604d915d07"> | 
| Should Supplemental Claims have a save In progress alert (`sip-alert`)? | <img width="3000" alt="should-SC-have-sip-alert" src="https://images.zenhubusercontent.com/61a57416e6469e7067eb4a98/4a82f9c5-ebc8-4d08-885e-f1ca51ae2d20"> | 
| Should Supplemental Claims have the sign in to start your request action link and the paragraph that says "What if I need help filling out my application?" | <img width="3000" alt="SC_Sign-in-button-and-help-filling-out-blurb-missing" src="https://images.zenhubusercontent.com/61a57416e6469e7067eb4a98/4cb21f5e-ff1b-411f-9775-e4be4c730604"> |

**Comment by saderagsdale** [comment]
@rocio-desantiago @eileen-coforma what are the next steps to close this?

**Comment by rocio-desantiago** [comment]
@saderagsdale @eileen-coforma validate in staging.

**Comment by eileen-coforma** [comment]
Looks good. Meets the acceptance criteria. Any more work would extend beyond scope, and require actual content review.
