### ISSUE TITLE
Design - Hide Direct Deposit information if the user is incompetent or has a fiduciary

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#6094]
# Background
We are making security updates to the Direct Deposit screen and would like to prevent showing Direct Deposit Data if it could have a negative impact on the user

# Tasks
- [x] Update Direct Deposit Screen  design to reflect improved security changes
- [ ] Work with content team to approve revised copy

# Acceptance Criteria
- [ ] Direct Deposit information is no longer visible if the user is incompetent or has a fiduciary

**Comment by tressaellen** [comment]
Related to #6090

**Comment by tressaellen** [comment]
![Direct Deposit Fiduciary](https://user-images.githubusercontent.com/58752772/75073430-a1968a00-54b6-11ea-92d2-0c580a1293ea.jpg)

**Comment by Samara-Strauss** [comment]
@tressaellen this needs to show at the top of the profile. We won't be showing the direct deposit section at all — even the heading.

Messaging should be something like "We can't let you update your information" and then explain that this is because our records show they have a fiduciary or are marked as deceased. If this is an error, call the helpline.

**Comment by tressaellen** [comment]
![Direct Deposit Fiduciary](https://user-images.githubusercontent.com/58752772/75074116-38b01180-54b8-11ea-866c-46c27529ca62.jpg)

**Comment by Samara-Strauss** [comment]
OK, we'll work with copy when the time comes.

**Comment by tressaellen** [comment]
We decided to move towards a more generic message as there are 8 different use cases for DD to be blocked. @peggygannon could you take a look at the content for this error message and give us any feedback?

<img width="590" alt="Screen Shot 2020-02-24 at 1 22 19 PM" src="https://user-images.githubusercontent.com/58752772/75188445-617b1580-5709-11ea-8ef2-73ae04a770fc.png">

**Comment by Samara-Strauss** [comment]
@tressaellen did you talk to Erik about how to handle this error in the new profile? If you did and we'll show it there, then no changes needed. If not, you might want to show this error in the context of the current profile.

**Comment by tressaellen** [comment]
@Samara-Strauss I did talk to Erik - he says we probably should revisit where it lives for profile 2.0, so I'll update this screenshot right now. Thanks for catching that!

**Comment by tressaellen** [comment]
![Direct Deposit](https://user-images.githubusercontent.com/58752772/75585113-98fe0080-5a2e-11ea-85bf-96072ca898c9.jpg)

**Comment by Samara-Strauss** [comment]
@tressaellen this will actually show at the top of the profile, as we don't show any of the direct deposit section — even the heading — when we don't load the section.

**Comment by tressaellen** [comment]
Oh yes, sorry - I totally spaced that. Here's the updated image.

![Direct Deposit](https://user-images.githubusercontent.com/58752772/75688070-0b075d00-5c5c-11ea-9ca2-bf9a6afd16ce.jpg)

**Comment by peggygannon** [comment]
@tressaellen here's my recommendation for the error alert. Please let me know if you have any questions. 


**You can’t update your financial information at this time**
We’re sorry. There seems to be an issue with your account that prevents you from updating your financial information. 
If you think this is an error, you can call the VA.gov help desk at 855-574-7286 (TTY: 711). We’re here Monday–Friday, 8:00 a.m.–8:00 p.m. ET.

**Comment by Samara-Strauss** [comment]
My thoughts:

1. "At this time" sounds like there may be a time when they *can* update their information, and in the case of people who have a fiduciary/have been deemed incompetent/are shown as deceased, they'll never be able to update this information. So, I might take those words out, or say something like "You can't update your financial information from VA.gov"
2. "There seems to be an issue with your account" — again, this sounds like this could be temporary (like the issue could be resolved), or that they did something wrong. I think it would be more accurate to say something like "We're sorry. Our records show you are unable to view and update your financial information from the VA.gov profile. If you think this is an error..."

**Comment by peggygannon** [comment]
Ok, @Samara-Strauss thank you for that clarification. 

@tressaellen I've updated the the message based on this info: 

**You can’t update your financial information** 
We’re sorry. Our records show that you're unable to view and update your financial information from your VA.gov profile.
If you think this is an error, you can call the VA.gov help desk at 855-574-7286 (TTY: 711). We’re here Monday–Friday, 8:00 a.m.–8:00 p.m. ET.

**Comment by Samara-Strauss** [comment]
Looks good to me!

**Comment by tressaellen** [comment]
@peggygannon thank you!

**Comment by erikphansen** [comment]
Just a reminder that the final design/copy decisions that came out of this ticket should have been moved to the top of the FE implementation ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/6090.

**Comment by Samara-Strauss** [comment]
@tressaellen @mshea0606 please get #6090 groomed properly for @erikphansen. Thank you!

**Comment by erikphansen** [comment]
I think we're fine with things now. I dug through this ticket and made sense of it :) but in the future the FE eng tickets should be pretty clear about what actually needs to be done.
