### ISSUE TITLE
Profile | EVSS>LH Direct Deposit | UAT testing - refine research plan and conversation guide

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#60942]
## Background 
We completed the research plan (#54999) and conversation guide (#55000) back in March. Now that we're closer to running UAT, we need to review them and make sure we're ready to go.

## Tasks 
- [x] update recruitment criteria to add a screener question that alerts participants that they'll need to input banking information which will be visible to the moderator, and that confirms they're OK with that
- [ ] review both documents to ensure they align with what we want to do
- [ ] submit research to repo for kick-off ([instructions here](https://github.com/department-of-veterans-affairs/va.gov-research-repository/wiki/Adding-research-the-board#how-to-add-new-research-for-approval-from-the-repo-board-old))

## Acceptance Criteria 
- [ ] we've started recruitment

**Comment by mtcA6** [comment]
I think we actually completed this already in March. This should be a relatively light ticket where we review what Florence worked on and then beginning the engagement process. 

[UAT Folder ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit/evss-lighthouse-migration/UAT)

     [Conversation Guide ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/evss-lighthouse-migration/UAT/conversation-guide.md)
     [Research Plan ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/evss-lighthouse-migration/UAT/research-plan.md)

**Comment by andaleliz** [comment]
Oh good catch @mtcA6 I forgot that she worked on this.  We do need to modify the recruitment screeners questions to ensure we let people know up front their bank information will be shared with the moderator, and that they're OK with that before the session starts.  

I'll update the ticket description so that is clear.

**Comment by andaleliz** [comment]
@pamela-drouin [here’s an example of a UAT study](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/uat/mvp/notification-preferences-uat-convo-guide.md) I did that had some “usability notes” we watched out for as we conducted UAT.

Also, I know I spoke up and pointed this as a 1 in refinement - please adjust accordingly considering what we talked about in our sync if that doesn't feel right to you.

**Comment by pamela-drouin** [comment]
@andaleliz & @mtcA6 -- I've reviewed the research plan and research guide. I do want to make some small revisions, so I changed the estimation from 1 to 2. I will also update the screener! I'll be sure to update each relevant ticket besides this one.

**Comment by pamela-drouin** [comment]
@Samara-Strauss & @mtcA6 -- a few quick questions about the research plan linked above:

- It isn't specified whether we would like a mix of devices (desktop/mobile/etc.). How helpful would it be at this stage to have a mix? Or is continuing with whatever participants have sufficient?
- More importantly, it also isn't specified whether we would prefer to recruit people with existing direct deposit set up. I'm assuming we would only want to recruit people who already use direct deposit and have banking info already in the system. Is my assumption correct?

**Comment by mtcA6** [comment]
I think in terms of mixed use of devices since it's just an API change it won't matter a ton. I think we can let the user decide but I'm curious what Samara and Liz recommend. It's my first UAT adventure w/ the VA 

Also it might be good to test w/ a user who doesn't have direct deposit but is eligible to make sure the other states display, but again I'm also curious what Liz and Samara think.

**Comment by Samara-Strauss** [comment]
- We don't need to recruit for a mix of devices. People can use whatever they prefer.
- Recruit for people who receive comp & pen payments. They will most likely already have direct deposit set up, as this is the main way people receive payments. It would be almost impossible to recruit people who receive payments for comp & pen but don't have direct deposit set up. They certainly exist, but Perigean would not be able to determine this with the data they have on research participants, and I think this is too confusing to ask people to self-report.

**Comment by pamela-drouin** [comment]
Thanks, @mtcA6 and @Samara-Strauss! Samara, you said exactly what I was hoping/assuming. I will move forward with a few revisions that make both these points more clearly.

Thanks again!

**Comment by pamela-drouin** [comment]
@andaleliz I have a few additional questions as I wrap up revisions:

- How is "ending the session" handled? Will the participant still be compensated if we end the session early based on our pre-defined criteria?

Tasks 6 and 7 feel wonky to me...
- Under which conditions would we ask a participant to do Task 6? Only if they have more than one login? Say, both LOGIN.gov and ID.me?
- What is the goal for task 7? If a participant has more than one way to log in, and they happen to try MyHealtheVet or DS Login, we would want to confirm that there is a prompt to log in using ID.me or Login.gov? This isn't explicitly stated as a research question in the plan.

**Comment by andaleliz** [comment]
@pamela-drouin great questions!

>How is "ending the session" handled? 

If the participant doesn't meet the criteria and you need to end the session early once you learn that, it's fine to say "for today's session, we need participants with XYZ, so we can go ahead and end the session now." I 

If you're talking about just ending the session in general: I typically have a slightly longer way of saying goodbye and ending the session than what is written in this guide. The author of this convo guide has a different style than me though. You could update the closing to anything you're comfortable with. The [platform conversation guide template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md#thank-you-and-closing---x-minutes) has a suggestion, which is closer to what I normally do.  There's also emergency exit guidance in that template, which I have thankfully never needed.

>Will the participant still be compensated if we end the session early based on our pre-defined criteria?
I believe so, but scheduled a message for tomorrow AM in #research-ops to confirm.  (btw, next time we sync, let's talk about compensation and I can share what I know about that 😄 )

>Under which conditions would we ask a participant to do Task 6? Only if they have more than one login? Say, both LOGIN.gov and ID.me?

Yes, and that will be indicated on the roster we receive from Perigean, so we'll know ahead of time. 

>What is the goal for task 7? If a participant has more than one way to log in, and they happen to try MyHealtheVet or DS Login, we would want to confirm that there is a prompt to log in using ID.me or Login.gov? This isn't explicitly stated as a research question in the plan.

Yes, the task is trying to confirm that the behavior for people with MHV and DSLogon is still the same. But, that's a good point that it's not in the research plan.

IMO, it is critical for us to validate that MHV and DSLogon behavior hasn't changed, and that everything works for ID.me **and** login.gov. If that is correct, we need to update the recruitment criteria to reflect that we need a sampling of people that covers all of these credentials (and update the research goals). 

The way the criteria is currently written, we could end up with 7 participants who have ID.me and no other credential.  @Samara-Strauss what are your thoughts? Maybe it's OK as-is for some reason I'm not thinking of.

**Comment by Samara-Strauss** [comment]
Reiterating what we spoke about earlier today -- I think it's OK to ask for a variety of login types via any open-ended questions we send over to Perigean. I would just be prepared that people's self-reported data isn't always accurate because they aren't always clear on what we're asking. So I would say just have a plan B if you don't get all the credential type.

**Comment by mtcA6** [comment]
same question here @pamela-drouin how many points did you complete, how many are carrying over or need to be added?

**Comment by pamela-drouin** [comment]
@mtcA6 hey Travis -- I hope to complete this today after meeting with Liz, but it will also be carrying over.

**Comment by pamela-drouin** [comment]
@mtcA6 1 point left to complete

**Comment by Samara-Strauss** [comment]
These look great! Thanks, @pamela-drouin!

One thing I didn't see in the conversation guide (sorry if I missed it) -- there should be a task at the beginning to confirm that the direct deposit information someone sees when they open their profile is correct. I see there is a task to confirm the information is there, but we should explicitly ask them if the information looks right.

**Comment by pamela-drouin** [comment]
Fantastic, thanks for pointing that out! Definitely makes sense to make the
confirmation more explicit. I will update!

*Pam Drouin*
*Sr. UX Researcher/Designer*

**Comment by pamela-drouin** [comment]
Updated this with an explicit task to confirm the direct deposit information is correct.
