### ISSUE TITLE
[526 - Historical Claims] Generate Batch 2 (only) Contention List

### ISSUE THREAD

**Issue by kylesoskin** [department-of-veterans-affairs/va.gov-team#60956]
## Issue Description
When the VBA is ready to import batch 2 of claims, they will need a list of dates, participant IDs and contentions, of the subset of submissions in that batch. 

## Tasks
- [x] Take list of IDs from David or VBA person
- [ ] Gather data

## Definition of Ready
- [ ] Relevant stakeholders provide subset of lists they need the info for

## Definition of Done
- [ ] List is generated and delivered

## Additional info

Here is the script I use to pull this data, I had started making it into a rake task in [this branch](https://github.com/department-of-veterans-affairs/vets-api/compare/ksoskin/526_rake_tasks?expand=1#diff-2e525569574ff7c95319b62a4f534284eef767e5c774071c5358449b1879b9abR3) but did not get far before abandoning it to do other stuff. 

The jist of it is something like 

```ruby
    subs = File.read('/tmp/ids.txt').lines.map(&:chomp)
    z=0
    data = []
    Form526Submission.where(id: ids).find_in_batches(batch_size: batch_size) do |group|
      z+=1
      puts "#{Time.now} - Batch #{z}"
      group.each do |sub|
        form = sub.form['form526']['form526']
        auth = sub.auth_headers
        pid = auth['va_eauth_pid']
        form['disabilities'].each do |d|
          x = [pid, sub.created_at, d['name']].to_csv
          data << x 
          print "."
        end        
      end
    end
    filename = '/tmp/disability_data.csv'
    File.write(filename, data.join)
    puts Reports::Uploader.get_s3_link(filename)
```
