### ISSUE TITLE
Profile: Sprint 15 (7.19.23-8.2.23) Epic

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#60959]
## Sprint 14 Retro
EasyRetro Board 

## 2023 Priorities for Authenticated Experience
<details> 
<summary>2023 Priorities Breakdown</summary>

**High**: 
Migrating MyHealtheVet into VA.gov; 
expanding notification functionality (both onsite and preferences); 
improving the logged-in nav/IA/experience overall; urgent/required maintenance for a feature; unplanned work that aligns with OCTO high-priority objectives

**Low**: 
improvements team wants to make but might fall outside of OCTO objectives
To complete: some initiatives that we should finish but don't fall under OCTO high-priority objectives
</details>

## People News
Samara OOO 7/31

## Sprint 15 Goals
_At the end of this sprint, what do we want to have accomplished/delivered?_
Fully finished QA for Direct Deposit Migration, and either be ready to Start UAT or have already started. 

## Carry over (modify points in Sprint Planning)

- 13pts total before accounting for the last item in the list
- guestimate in terms of the QA testing need to check in 
- need to confirm points are accurate 

<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

ID | Story Title | Points Completed Last Sprint | Points Carried Over | Total Points
-- | -- | -- | -- | --
#61013 | FE \| Profile \| Notification Settings \| Default Send \| bug fixing 🐜 / secondary implementation fixes / Testing coverage (cleaning and seasoning the meat and potatoes) | 4 | 1 | 5
#61356 | Design \| Profile \| Update user flows \| Refine user flow for notification settings | 3 | 2 | 5
#54771 | Team QA \| Profile \| EVSS>LH \| Direct Deposit C&P \| QA Testing | 12 | 8 | 20
#61199 | BE \| Profile \| Direct deposit \| Add Production AWS Params | 2 | 0 | 2
#60942 | Profile \| EVSS>LH Direct Deposit \| UAT testing - refine research plan and conversation guide | 1 | 1 | 2
#61212 | Midpoint Review - IA Feedback - Authenticated Experience, Profile, Notification Settings, Updates to Edit Flow | 2 | 1 | 3

</body>
</html>

##  Direct deposit migration EVSS > Lighthouse (Epic #51900)

```[tasklist]
### Direct Deposit Migration
- [ ] #54771
- [ ] #60945
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/60942
- [ ] #61177
- [ ] #61199
- [ ] #61170
- [ ] #61165
```

## Disabilities Rating 

```[tasklist]
### Disabilities Rating Work
- [ ] #62223
- [ ] Depending on ^^ #62223 we may not need #61912:
- [ ] #61912
```

## Notification preferences

```[tasklist]
### Default Send / Email as a channel
- [ ] #61013
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62077
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62091
- [ ] PM | Staging review if we progress far enough
```

```[tasklist]
### Editing as a Sub-Task
- [ ] #61212
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/59987
- [ ] Release Plan and Staging review depending on how far we get
```

## Enhanced Personalized Experience 

```[tasklist]
### TBD Dependents/Letters? / Hub? /
- [ ] #60822
- [ ] #62198
```

## General / Other

```[tasklist]
### General
- [ ] #61243
- [ ] #61356
- [ ] #62240
- [ ] #51842
- [ ] #61997
```

## Unplanned Work
- For this sprint -- allot 2-3 points for unplanned work ID	
```[tasklist]
### unplanned
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62368
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62512
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/61362
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/61360
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/61361
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/61359
```

[Next Sprint 16](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60962)
