### ISSUE TITLE
Vets-API: Noise in RSpec Output (Deprecations, Warnings, puts/print Statements)

### ISSUE THREAD

**Issue by radavis** [department-of-veterans-affairs/va.gov-team#60965]
## Issue Description

As a Vets-API Developer<br />
I would like to see fewer deprecations, warnings, and puts/print statements in the console when running the Vets-API test suite<br />
So that I can easily read the results of individual tests and have greater confidence in our shared suite of automated tests.

---
## Tasks
- [ ] Find the source of individual deprecations, warnings, and puts/print statements, and make the necessary corrections.

## Acceptance Criteria
- [ ] `bundle exec rspec spec/ modules/` outputs no deprecations, warnings, or puts/print statements.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
