### ISSUE TITLE
CH 31 | 28-1900 Data Output

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#60963]
VA integration team working to replace current CWINRS case management system with a new Readiness and Employment System (RES) seeks to understand how and what data is passed from va.gov Chapter 31 (VRE) form 28-1900 to current CWINRS system. 

**In order to** understand how and what data is passed from va.gov form 28-1900,

**we need to**
- [ ] Determine the current process for getting data from va.gov form 28-1900 into CWINRS system.
- [ ] Determine if any output files are current generated for consumption by a downstream system.
- [ ] Stretch goal: Contemplate if and how we should/could assist in ingesting va.org 28-1900 form data into RES (e.g., API).

**so that** the VA integration team can proceed with integrating the VRE program into RES.

#### Acceptance Criteria
- [ ] Document data transfer process between va.gov 28-1900 to CWINRS and/or other downstream systems.
- [ ] Identify any output files generated for downstream consumption.
- [ ] Next steps have been determined and documented

#### Product notes
- [Recording of conversation with VA integration/RES team](https://drive.google.com/drive/folders/1lzwim1E_WJ9N5DG_yQR9mgb5Zsqtql3y)

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DLarson-Oddball** [comment]
In regards to the request for payload information sent to Central Mail. I wasn’t able to capture a request in flight, or find a definitive definition for the payload. I was however, able to piece together a payload that it uploaded to VBMS. From what I have gathered, I believe CWINRS information is input from VBMS, so this may still be actionable information.

As best I can tell, the payload is uploaded by [this api call](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/saved_claim/veteran_readiness_employment_claim.rb#L149).

Note the field `VAFileNumber` is likely a “primary key” of sorts. I believe it is a string.
Payload:
```
{
  {
    "useEva": true,
    "useTelecounseling": true,
    "appointmentTimePreferences": {
      "morning": true,
      "midDay": true,
      "afternoon": false
    },
    "yearsOfEducation": "17",
    "isMoving": true,
    "newAddress": {
      "country": "USA",
      "street": “123 Test St”,
      "city": "Arroyo Grande",
      "state": "CA",
      "postalCode": "93420"
    },
    "veteranAddress": {
      "country": "USA",
      "street": "9417 Princess Palm",
      "city": "Tampa",
      "state": "FL",
      "postalCode": "33928"
    },
    "mainPhone": "5555555555",
    "email": "test@gmail.xom",
    "veteranInformation": {
      "fullName": {
        "first": "Homer",
        "middle": "John",
        "last": "Simpson"
      },
      "dob": "1998-01-02",
      "pid": "600036503",
      "edipi": "1005354478",
      "vet360ID": null,
      "regionalOffice": "317 - St. Petersburg",
      "VAFileNumber": "likely a string; potential format: 123-45-6789"
    }
  }
}
```

**Comment by steele-lm** [comment]
@DLarson-Oddball Question from the RES Team: Do you know how is this information retrievable from the VBMS system?
