### ISSUE TITLE
Add a new feature toggle for the descriptive back link work

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#60964]
## Item Description
We will need to create a feature toggle to update the breadcrumbs in the appointments application. 

---

## Tasks
- Add `va_online_scheduling_descriptive_back_link` feature toggle

## Acceptance Criteria: 
- [x] The toggle is created for VAOS

## Definition of Done
- [x] All acceptance criteria are met
- [ ] [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md) is updated
---

**Comment by ldelacosta** [comment]
The feature toggle has been added. Closing out the ticket. 
![Screenshot 2023-07-05 at 7.30.46 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/fa38d04b-3818-4aef-8d0a-cc4f15c698f0)
