### ISSUE TITLE
Profile: Sprint 16 (8.2.23 - 8.15.23) Epic

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#60962]
## Sprint 15 Retro
[Previous Sprint ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60959)
[EasyRetro Board ](https://easyretro.io/board/f4051524-d7be-43a4-8c50-f43d887f3a7f/2641908b-8c8a-45ae-86e9-9fb8cae25cb1)
[Next Sprint](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61840)

## 2023 Priorities for Authenticated Experience
<details> 
<summary>2023 Priorities Breakdown</summary>

**High**: 
Migrating MyHealtheVet into VA.gov; 
expanding notification functionality (both onsite and preferences); 
improving the logged-in nav/IA/experience overall; urgent/required maintenance for a feature; unplanned work that aligns with OCTO high-priority objectives

**Low**: 
improvements team wants to make but might fall outside of OCTO objectives
To complete: some initiatives that we should finish but don't fall under OCTO high-priority objectives
</details>

## Q2 CY2023 (Apr-Jun) Product Goals
More details found at [Q2 CY2023 Product Roadmap](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/roadmap/2023-goals-roadmap.md#q2-cy2023-april---june)

## People News
Liz OOO 8/7-11
Samara OOO 8/18

## Capacity Planning 
<details><summary>Details</summary>
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/73ce8ba1-5964-4a70-840d-c44c2773bdd1)
</details> 

## Sprint 16 Goals
_At the end of this sprint, what do we want to have accomplished/delivered?_

- By end of sprint we should be deploying LH DD to production 
- Be ready for QA for Default Send / Editing as a Subtask work in the next sprint

## Carry over (modify points in Sprint Planning)

2pts
- #61671 
1pt
- #62077
1pt
- #59987

Blocked should maybe revise the original points down 
- #61912

<details><summary> </summary>
<p>

```[tasklist]
### Tasks
- [ ] #61671 
- [ ] #62077 
- [ ] #59987 
- [ ] #61912
``` 

</p>
</details> 

##  Direct deposit migration EVSS > Lighthouse (Epic #51900)

```[tasklist]
### Direct Deposit Migration
- [ ] #61170
- [ ] #62626
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/63029
- [ ] #60782
```

##  Disabilities Rating

```[tasklist]
### Disabilities Rating
- [ ] #63021
```

## MHV to VA.gov 
```[tasklist]
### MHV Notification Questions
- [ ] #59721
```

## Authenticated Menu
```[tasklist]
### Authenticated Menu
- [ ] #62944
```

## Notification preferences
```[tasklist]
### Default Send / Email as a channel / Editing as a Sub-Task
- [ ] #61112
- [ ] #62606
- [ ] #62610
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62091
```

## API Improvements - Mock Data
```[tasklist]
### Mock Data
- [ ] #60531
- [ ] #60571
- [ ] #60572
```

## General / Other
```[tasklist]
### General
- [ ] #48566 - cary over 2pts to next sprint
- [ ] #52130
- [ ] #61671
- [ ] #62363
```

## Telephone Validation
```[tasklist]
### Telephone Validation
- [ ] #62146
```

## Unplanned Work
- For this sprint -- allot 2-3 points for unplanned work 

```[tasklist]
### unplanned
- [ ] #63323
```
