### ISSUE TITLE
[FE][TECH DEBT] - Disallowed Cypress Test Specs

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#60976]
## Summary
Our applications have a lot of tests in this list. We should evaluate and follow the [steps to remediate](https://depo-platform-documentation.scrollhelp.site/developer-docs/e2e-stress-test-and-allow-list) if we think they are in a good place: https://depo-platform-documentation.scrollhelp.site/developer-docs/currently-disallowed-cypress-test-specs-on-va-gov

## Tasks
- [ ] [FE] Evaluate disallowed tests
- [ ] [FE] Fix tests if needed
- [ ] [FE] reinstate tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by anita-halici** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/60976?planning-poker) with Zenhub @anita-halici

**Comment by brianseek** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/60976?planning-poker) with Zenhub @lee-delarm6 @wullaski

**Comment by wullaski** [comment]
Here's the list of the currently disallowed tests that are stored in a BigQuery table called [vets_website_e2e_allow_list](https://console.cloud.google.com/bigquery?authuser=1&project=vsp-analytics-and-insights&ws=!1m5!1m4!4m3!1svsp-analytics-and-insights!2svsp_testing_tools!3svets_website_e2e_allow_list)

- src/applications/check-in/pre-check-in/tests/e2e/happy-path/happy-path.already.completed.cypress.spec.js
- src/applications/check-in/pre-check-in/tests/e2e/session/session.reloads.on.refresh.cypress.spec.js
- src/applications/check-in/pre-check-in/tests/e2e/intro-display/accordion.toggle.cypress.spec.js
- src/applications/check-in/day-of/tests/e2e/appointment-details-display/appointment-details.complete.cypress.spec.js
- src/applications/check-in/day-of/tests/e2e/appointments-display/veterans.may.refresh.their.appointments.cypress.spec.js
- src/applications/check-in/pre-check-in/tests/e2e/loading-session/returning.session.cypress.spec.js
- src/applications/check-in/pre-check-in/tests/e2e/app-reload/reload.page.error.cypress.spec.js
- src/applications/check-in/pre-check-in/tests/e2e/demographics-display/information.display.cypress.spec.js
- src/applications/check-in/pre-check-in/tests/e2e/extra-validation/fields.are.required.cypress.spec.js
- src/applications/check-in/pre-check-in/tests/e2e/extra-validation/validation.failed.cypress.spec.js
- src/applications/check-in/pre-check-in/tests/e2e/extra-validation/validation.failed.dob.cypress.spec.js

**Comment by wullaski** [comment]
Test isolation is a new feature and could solve a lot of our problems with flakiness. https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Test-Isolation

**Comment by wullaski** [comment]
@loripusey FYI, I couldn't find a definitive cause for why these tests were failing. I added comments to the tests so they would run in the pipeline. We can remove those comments when the tests pass and are removed. Some of them are already removed from the disallowed list. I'll keep an eye on the list over the next week or so to see if more get removed or added and try to track down the exact errors for those that flake out. It's a bit of a moving target for various reasons. More info in this thread https://dsva.slack.com/archives/CBU0KDSB1/p1693495953451689
