### ISSUE TITLE
[CHIP] Create a CHIP Endpoint for Patching Demographics

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#60985]
## Tasks
- [ ] [CHIP] **Create a CHIP Endpoint for Patching Demographics**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by lee-delarm6** [comment]
Finished, but on hold due to library failure with github actions / AWS library change
