### ISSUE TITLE
Update number of days to complete disability related claims for June 2023 (in English and Spanish)

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#60996]
## Issue Description
We need to update the number of days it takes to complete disability related claims. Sitewide content needs to email Tanekwa Bournes on the first of the month to get the number from the previous month and input into Drupal.

This needs to be done on the following pages:
https://www.va.gov/disability/after-you-file-claim/
https://www.va.gov/disability/how-to-file-claim/
https://www.va.gov/disability/how-to-file-claim-esp/
https://www.va.gov/disability/after-you-file-claim-esp/

## Tasks
- [x] Email Tanekwa for most recent number (Aliyah)
- [x] Input number and new month into both Drupal pages (Aliyah)
- [x] Review Spanish pages (Ana)
- [x] Review English pages (Megan)
- [x] Publish all 4 pages (Megan)

## Acceptance Criteria
- [ ] Most current number of days is on live site

**Comment by RLHecht** [comment]
@aliyahblackmore If Tanekwa doesn't email you by July 3, could you reach out to her to get the latest number? The number you'll use is from the Average Days Pending box in the top right corner of the snapshot she sends. Thank you!

**Comment by aliyahblackmore** [comment]
**Update here:** 

Emailed Tanekwa today, 7/3, for the latest number.

**Comment by aliyahblackmore** [comment]
Tanekwa replied. 

Average number of days: 105.9

**Comment by aliyahblackmore** [comment]
Hi @megzehn and @ABeltran77 these pages are ready for you all to review and publish!

**English page for Megan:** 
[How to file](http://preview-prod.vfs.va.gov/preview?nodeId=905)
[After you file ](http://preview-prod.vfs.va.gov/preview?nodeId=870)

**Spanish pages for Ana:**
[How to file](http://preview-prod.vfs.va.gov/preview?nodeId=50435)
[After you file](http://preview-prod.vfs.va.gov/preview?nodeId=50453)

**Comment by aliyahblackmore** [comment]
@coforma-terry - we can close this ticket!

cc @megzehn
