### ISSUE TITLE
[CHIP] Add & Deploy Check-in Endpoint on AWS

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#60993]
## Tasks
- [ ] [CHIP] **Add & Deploy Check-in Endpoint on AWS**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
