### ISSUE TITLE
Create Teams View Prototype

### ISSUE THREAD

**Issue by ianmagenta** [department-of-veterans-affairs/va.gov-team#61006]
## Description
Using the Design assets (Figma) link below, create the Teams View page (authenticated)

## Design Review
https://www.figma.com/file/rw8kJXf4VKliimoMpsEy4Q/Identity-Dashboard-(initial)?type=design&node-id=0-1

## Tasks
- [x] Using Next.js create a page for the Teams View page (authenticated)
  - [x] Create a table for teams to be listed in
  - [x] "Modify" button should take you to the /teams/edit page (for now)
  - [x] The "Learn More" link should be an empty href (for now)
- [x] Write tests for the above

**Comment by aparsley** [comment]
Looks good, thank you.
