### ISSUE TITLE
[spike] CH 31 | 28-1900 Data Output

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#61019]
###Description of Spike

**In order to** :
VA integration team working to replace current CWINRS case management system with a new Readiness and Employment System (RES) seeks to understand how and what data is passed from va.gov Chapter 31 (VRE) form 28-1900 to current CWINRS system.

In order to understand how and what data is passed from va.gov form 28-1900,

**we need to** :
 Determine the current process for getting data from va.gov form 28-1900 into CWINRS system.
 Determine if any output files are current generated for consumption by a downstream system.

**so that**:
the integration team can make progress on the 17 other integrations that are dependent on this information so that VR&E can improve case management.

#### Acceptance Criteria
- [ ] to fulfill the AC in this ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/60963 

#### Timebox
12 hrs 

#### MR Approver
- TBD

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by steele-lm** [comment]
General note: VA RES Team would like confirmation of 1900 form data by their next prioritization session, which is the week of July 10.

**Comment by jstrothman** [comment]
@steele-lm @sortizsh I believe the prioritization referred to was ours--the Claimant Experience non-disability benefits prioritization with Matt upon his return. I'd love to reach out to the folks we met with to provide an update if we have one.

**Comment by steele-lm** [comment]
@DLarson-Oddball The RES team suggested Daniel  [daniel.doong@va.gov](mailto:daniel.doong@va.gov) on the CWNIRS team as a contact.

**Comment by steele-lm** [comment]
@DLarson-Oddball One more, the SME for VRE suggested Ekaterina Shick. Her email is: [EKATERINA.SHICK@va.gov](mailto:EKATERINA.SHICK@va.gov)

**Comment by DLarson-Oddball** [comment]
Response from Daniel Doong: There is no automated way to transmit data on 28-1900 to CWINRS.  CWINRS users need to manually enter veteran file #, stub name, claim received date, IRND.  CWINRS will then retrieve other data such as veteran name, DOB, gender, service from BIRLS/Share and Corporate Database and start the eligibility determination process.

**Comment by steele-lm** [comment]
Next steps: Research how 28-1900 gets into BIRLS/Share and Corporate Database. There might be a spool file passed that we can grab.

**Comment by DLarson-Oddball** [comment]
Here is what we know so far. Please note all of this information is second-hand.

  Based on [this PR](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12090), when form 28-1900 is submitted to va.gov, the form data is sent to central mail. There is a process after the form is submitted to central mail that results in a case being manually created in CWINRS. 

Screenshot of CWINRS interface (Input field data is not real):  
![Add GED Record](https://github.com/department-of-veterans-affairs/va.gov-team/assets/133443504/beaacb9d-e290-4bb2-a1ec-e06e9b3d6526)


The following fields are entered manually entered during case creation:
veteran file #, stub name, claim received date, IRND

Case data is stored in ”Corporate Database”, (which is the database for CWINRS)

After the case is created CWINRS pulls the fields listed below from BIRLS via a Tuxedo service: 

Notes:  We don’t have clarity on BRILS, a “Tuxedo Service”
We determined a “Spool file” is not related to this process and no method to import sets of data was available. 

BRILS Field Set

- File Number(9)
- SSN(9)
- Last Name(20)
- First Name(20)
- Middle Name(20)
- Suffix Name(3)
- Date of Birth(8)
- Date of Death(8)
- Branch of Service1(4)
- EOD Date1(8)
- RAD Date1(8)
- Separation Reason1(3)
- Character of Service Code1(3)
- Branch of Service2(4)
- EOD Date2(8)
- RAD Date2(8)
- Separation Reason2(3)
- Character of Service Code2(3)
- Branch of Service3(4)
- EOD Date3(8)
- RAD Date3(8)
- Separation Reason3(3)
- Character of Service Code3(3)
- Folder Type1(5)
- Folder Location1(3)
- Folder Type2(5)
- Folder Location2(3)
- Folder Type3(5)
- Folder Location3(3)
- Folder Type4(5)
- Folder Location4(3)
- Folder Type5(5)
- Folder Location5(3)
- Folder Type6(5)
- Folder Location6(3)
- Folder Type7(5)
- Folder Location7(3)
- Folder Type8(5)_
- Folder Location8(3)
- Folder Type9(5)
- Folder Location9(3)
- Folder Type10(5)
- Folder Location10(3)
- Gender Code(1)
- VADS Indicator1(1)
- Service Verified Indicator1(1)
- POA Code(3)
- Current Retirement Pay Amount(4)
- Prior Retirement Pay Amount(4)
- VADS Indicator2(1)
- Service Verified Indicator2(1)
- VADS Indicator3(1)
- Service Verified Indicator3(1)

**Comment by steele-lm** [comment]
@mattpointzxer0 @jstrothman The comments above provides a summary of findings related to how and what data CH31 sets to central mail and what is queried by CWINRS. I tried to tag Aude Togbenon and Elizabeth Solley on this ticket, but I'm unable to.
