### ISSUE TITLE
Submit ticket for Privacy/Security Readiness Review

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#61010]
# Description
Our Product Owner would like us to submit a request to have a Privacy, Security and Infrastructure review. This ticket references the form located here: .[Privacy, Security, & Infrastructure Readiness Review](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/new?assignees=gary-fallon&labels=security-review%2Cplatform-security%2Cplatform-security-review&projects=&template=privacy-and-security-review.md&title=Readiness+Review+%5BTeam-Name%2C+Feature-Name%5D)

# Tasks
- [x] Review the template and collect information for the request
- [x] Submit the request

# Acceptance Criteria
- [x] We have submitted the review request

**Comment by pjhill** [comment]
Created a draft ticket. We are missing the following items --
* Architecture diagram (in the form they want)
* Incident Response Plan
* Sequence Diagram
* Data Flow Diagram
* Product Playbook
