### ISSUE TITLE
Add QuickSubmit link and information to education pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#61021]
## Issue Description

EDU stakeholders reached out asking us to add information about Veterans using QuickSubmit to upload education documentation and evidence. Ask VA is still the preferred method for Veterans to ask questions but if they upload documents through Ask VA it needs to then get routed to the right place. QuickSubmit is the more direct way to do this.

Here's the language EDU has provided on how to use QuickSubmit:

If you are only submitting documents for VA Education claims, you should submit directly to Centralized Mail Portal via QuickSubmit for better customer service. It’s quick, easy, and ensures the documents get into file quickly. To log in to QuickSubmit, a VA PIV Card or an ID.me account is required. Access QuickSubmit via AccessVA at https://eauth.va.gov/accessva/?cspSelectFor=quicksubmit
• Users must complete First Name, Last Name, File Number/SSN and Zip Code
• Select Education for both “Organization” and “Benefit Claim Type”
• “Emergent Indicator” must be left blank
Once the fields are completed, you may select the PDF file to attach, or drag and drop the file into the appropriate area. After documents are attached, select Submit.

QuickSubmit link to use: https://eauth.va.gov/accessva/?cspSelectFor=quicksubmit

## Tasks
- [ ] Assess what pages QuickSubmit link should go on
- [ ] Add QuickSubmit link and any content to pages
- [ ] Send to stakeholders for review
- [ ] Copyedit (Megan)
- [ ] Publish (Megan)

## Acceptance Criteria
- [ ] QuickSubmit links are live on the site

**Comment by coforma-terry** [comment]
@laurwill  Is this related to #61267

**Comment by laurwill** [comment]
Closing this — it's a dupe of 61627, we'll continue this work there.
