### ISSUE TITLE
Design ideation for acknowledgement of homelessness in eFSR/Streamlined Waiver form

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#61027]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

In the eFSR Usability Study from 5/2023, one of our most significant findings was related to a lack of acknowledgment of homelessness stirring intense feelings from Veterans experiencing homelessness. 

As a follow-through from this study, we are doing light secondary research and design ideation to determine where it would be clear and sensible to include this acknowledgment in the eFSR/Streamlined Waiver. 

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_
- [ ] Light secondary research of other Forms teams' solutions to address homelessness in forms
- [ ] Light secondary research to understand best practices for asking about homelessness in forms
- [ ] Design ideation to see the different paths that are possible
- [ ] Choosing a solid direction for the best way to ask and acknowledge homelessness in the form

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
- [ ] Final user flow or mockup of design solution for homelessness acknowledgment in the form
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
Per 6/28/23 mtg, Denise has advised that we tackle this post MVP

**Comment by HeatherRienks** [comment]
Per SP on 8/15- this is a lower priority- due to SW, many quesitons will be bypassed

**Comment by HeatherRienks** [comment]
Moving to backlog due to shift in priorities. Needs to be refined before we move back to "ready"

**Comment by HeatherRienks** [comment]
@charlottecesana @josephrlee suggest we postpone work on this effort for now

**Comment by HeatherRienks** [comment]
@charlotte- I am removing this ticket from Sprint 114 and you can add S114 to the new ticket you create.
