### ISSUE TITLE
COE | First steps for 400 remediation 

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#61020]
## Issue Description
Identify next steps for COE:
- [ ] merge Eugene's tests 
- [ ] Set up data dog 
- [ ] Reproduce bug 
- [ ] Trace logs
- [ ] Compare 2 systems 
- [ ] Talk to stakeholders

## Acceptance Criteria
- [ ] remediation plan for the 400 errors 

## Appendix
- Split from https://github.com/department-of-veterans-affairs/va.gov-team/issues/60243#issuecomment-1591471399

**Comment by sanjabaj2** [comment]
@steele-lm What is the outcome of this ticket?

**Comment by steele-lm** [comment]
@sanjabaj2 This ticket was closed bc it was an old exploration ticket that was created when we took over COE from another team. Since then, we've been working off of more specific tickets #54751 and #90389

**Comment by sanjabaj2** [comment]
Thank you. In general, it would be helpful to add a note/comment when ticket is closed for any reason.
