### ISSUE TITLE
[CHIP] - setup authenticated check-in endpoint

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#61029]
## Description
Create a a wrapper that receives the payload (appointmentIen, stationNo, and patientDFN) and outputs a generic success response and error response.

## Tasks
- [x] [CHIP] - Create lambda endpoint as outlined
- [x] [CHIP] - add body validator
- [x] [CHIP] - Write initial tests

## Acceptance Criteria
- [x] Deployed to dev
- [x] Tested on dev

**Comment by brianseek** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/61029?planning-poker) with Zenhub @wullaski

**Comment by brianseek** [comment]
Leaving this here for a beat to discuss in scrum, but this is merged and tested on dev by me with Lee co-working. I don't think the other engineers have the ability to test this at the moment though. Lee needing access and John having issues
