### ISSUE TITLE
[CHIP] - authenticated check-in - fetch appointment

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#61032]
## Summary
Fetch the appointment using the payload from the request. Use the existing `functionalVistaService` to fetch the appointment. Parse the appointment to insure it is a check-in-able appointment. Add to errors if check-in criteria not met. 

Appointment criteria:
 - eCheckinEnabled
 - status (NO ACTION TAKEN/TODAY, INPATIENT/NO ACT TAKN, NON-COUNT) or empty
 - in-person appointment (clinic)
 - within the 45 minutes before 15 minutes after start time window

## Tasks
- [x] [CHIP] fetch appointment
- [x] [CHIP] add check-in criteria check
- [x] [CHIP] add tests

## Acceptance Criteria
- [x] Deployed to dev
- [ ] Tested on dev

**Comment by brianseek** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/61032?planning-poker) with Zenhub @wullaski

**Comment by brianseek** [comment]
moving to closed since merged
