### ISSUE TITLE
[CHIP] - authenticated check-in endpoint - add status changes

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#61030]
## Description
Add functionality to stubbed out endpoint that sets setEcheckinStarted, setCheckin(on success), and setEcheckinComplete(on success)

## Tasks
- [x] [CHIP] use the functionalVistaService to set statuses
- [x] [CHIP] add tests

## Acceptance Criteria
- [x] Deployed to dev
- [x] Tested on dev

**Comment by brianseek** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/61030?planning-poker) with Zenhub @wullaski

**Comment by brianseek** [comment]
Work still in progress, need to work out details with logs in the dev enviroment.

**Comment by brianseek** [comment]
test and working on DEV
