### ISSUE TITLE
[CHIP] - authenticated check-in - fetch demographics statuses 

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#61031]
## Summary
Fetch the demographics for a given patient using the payload from the request. Use the existing `clinicianWorkflowService` to fetch the demographic statuses. Parse the insurance and demographics statuses. Add to errors if statuses are incorrect. Then allow to continue.

If statuses are good continue processing.

## Tasks
- [x] [CHIP] fetch demo statues
- [x] [CHIP] add status check logic
- [x] [CHIP] add tests

## Acceptance Criteria
- [ ] Deployed to dev
- [ ] Tested on dev

**Comment by brianseek** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/61031?planning-poker) with Zenhub @wullaski
