### ISSUE TITLE
[CHIP] - authenticated check-in - reporting

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#61034]
## Summary
Add reporting to all areas of function. See existing initiateCheckIn and checkIn endpoints to see what and when to log using the existing `LoggerService` and `MetricsService`

## Tasks
- [ ] [CHIP] add logging

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by brianseek** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/61034?planning-poker) with Zenhub @wullaski

**Comment by brianseek** [comment]
moving to closed since work is completed and merged
