### ISSUE TITLE
[CHIP] - authenticated check-in - error response/failed validation

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#61033]
## Summary
Return the errors found with proper error codes and string

## Tasks
- [ ] [CHIP] - handle errors in error responce
- [ ] [CHIP] - add tests

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by brianseek** [comment]
moving this to closed since released
