### ISSUE TITLE
Update Sitewide CAIA touchpoint name across Platform Website and Confluence

### ISSUE THREAD

**Issue by CherylEvans** [department-of-veterans-affairs/va.gov-team#61035]
## User Story
As a Governance team member, I want the Sitewide CAIA intake request to appear consistently across all Platform-facing and VFS-facing guidance so that both Platform and VFS teams have a consistent experience. 

Assignee: @CherylEvans 
Peer Reviewer: @allison0034 

## Description
The [Sitewide Content and IA intake request page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) has been updated to reflect the current process supported by Sitewide CAIA. This means that the name of the touchpoint has changed to Sitewide CAIA Intake request (or long name - Sitewide content, accessibility, and information architecture intake request) and the new name (preferably the short version) needs to be updated across all Platform Website and Confluence guidance.

## Impacted Artifacts

**Platform Website**
[Change History Page](https://vfs.atlassian.net/wiki/spaces/CC/pages/1846870032/Change+history) March 16, 2022 change post
[Touchpoints](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/touchpoints) 
[Staging Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review) 
[Contact Us](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/contact-us)
**Internal Documentation**
[CC Product Outline](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748926486/Collaboration+Cycle+Product+Outline)
[CC Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)
[Custom Tracks Flow](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1872822276/Custom+Tracks+Flow)
[How to complete an IA review for Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2601025548/How+to+complete+an+Information+Architecture+IA+review+for+Design+Intent)
[How to complete a Content review for Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2598371379/How+to+complete+a+Content+review+for+Design+Intent)
[How to complete an Accessibility review for Midpoint review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2492727318/How+to+complete+an+Accessibility+Midpoint+Review)
[How to complete a Content Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2491613360/How+to+complete+a+Content+Midpoint+Review)
[How to complete an Information Architecture Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2492727325/How+to+complete+an+Information+Architecture+Midpoint+Review)
[Staging Environment Guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2377875498/Staging+Environment+Guidance)
[Sitewide Content, Accessibility and IA (CAIA)](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2542338142/Sitewide+Content+Accessibility+and+IA+CAIA)
[Content Relationship](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2542469236/Content+Relationship)
[Information Architecture (IA) Relationship](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2541584823/Information+Architecture+IA+Relationship)

## Tasks
 - [x] Once we receive feedback, determine if the name of the touchpoint has changed. If so, identify and link under Impacted Artifacts all other impacted Platform Website changes
 - [x] Make updates to all Impacted Artifacts and publish

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The Sitewide CAIA intake request is consistently referred to across Platform Website and Confluence. 

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
All links are located in the Impacted Artifacts section. They are small changes, so I am changing the source pages directly.

**Comment by CherylEvans** [comment]
@allison0034 Regarding the Custom Tracks Flow changes, I made changes to the [CTF Mural Board link](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1676486000565/b37faafd60422b6ac153d7e160e979ed09fbde0c?sender=739a5b0b-0032-4f0d-aaf6-fa99e7434af8) but don't know how to insert them into the [CTF Confluence page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1872822276/Custom+Tracks+Flow). Do I need to delete the image first?  The last time I updated the CTF, it was in LucidChart, and I took a screenshot and added it to the Confluence page.  [How to embed images into a Confluence page guidance](https://vfs.atlassian.net/wiki/spaces/AP/pages/1857060875/Embed+images+videos+and+GIFs+in+a+Platform+website+page) isn't particularly helpful.
Would you be able to help me with this?  :-)
Otherwise, this is ready for peer review.

**Comment by allison0034** [comment]
@CherylEvans I will start the peer review. 

I assume you would delete the current image and then use the add image icon at the top of the page and insert the new one.

**Comment by CherylEvans** [comment]
@allison0034 Ha ha, yep, that's all it was! :-)

**Comment by allison0034** [comment]
@CherylEvans I wanted to give you something to consider. For How to complete an [IA review for Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2601025548/How+to+complete+an+Information+Architecture+IA+review+for+Design+Intent) you have added...

> In your written feedback, instruct teams to fill out an intake ticket to work with CAIA.

I would push back on this for a couple of reason.

1. If we have the touchpoint added to their epic as something that needs to be completed, then why do we have to tell them to complete that touchpoint? We do not do that for any other touchpoints.
2. You will be filling out a feedback ticket and attaching it to every single Design Intent and it may only have that content in it.

What are your thoughts on removing that and having the team be responsible for completing that touchpoint without us documenting it in feedback?

**Comment by CherylEvans** [comment]
@allison0034 I didn't add this.  I only corrected the new name for Sitewide CAIA.  But to your point, I would take this out because teams know they must work with CAIA as it's part of the CC. I would be happy to take it out though. :-)

**Comment by allison0034** [comment]
@CherylEvans this looks good to me and yes I would remove that if you agree.

**Comment by CherylEvans** [comment]
@allison0034 I remove the sentence, and it flows much better.  Thank you for your review and thoughtful comments; closing! :-)

**Comment by CherylEvans** [comment]
User Story and Acceptance criteria were met, and all tasks were completed.
