### ISSUE TITLE
[BE] Send Appointment Time to BTSSS API

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#61043]
CURRENTLY BLOCKED BY THE BTSSS API WORK

## Background
The BTSSS API method currently only accepts an appointment date, however, to process the claim, BTSSS also needs the appointment time. The BTSSS team will be updating the API to include the time. When that happens, we will need to send the time as well.

![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/9475800c-4e37-4ac1-8c24-318153cc1e40)

## Tasks
- [ ] [BE] **Send Appointment Time to BTSSS API**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by loripusey** [comment]
I think this has already been done
