### ISSUE TITLE
Upgrade Debian to Bookworm

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#61041]
## Problem Statement

In June, Debian "Bookworm" was released. We're currently using Debian "Bullseye" for the container image of Vets API. There are a few reasons we should update now:

- The current version of OpenSSL we're using (1.1.1) in Bullseye is EOL'd and needs to be replaced.
- We're already pulling packages from Bookworm which adds complexity to our Dockerfile.

## Acceptance Criteria 

- [x] Vets API is updated to work with the packages in Debian Bookworm
- [x] Testing has been performed in non-production environments
- [x] An upgrade date is decided and announced in our announcement channel
- [x] Preparations are made to quickly rollback if any issues are encountered
- [x] The Bookworm update is released to production
- [x] Error tooling and communication channels are monitored for trouble

```[tasklist]
## Tasks
- [ ] Update Platform docs to recommend installing pdftk-java
```

**Comment by JoeTice** [comment]
Moving this to backlog since Eric will be on support next sprint

**Comment by ericboehs** [comment]
We attempted to upgrade to Debian Bookworm in production but ran into some errors. [Jerek reported](https://dsva.slack.com/archives/C03R5SBELQM/p1704746423222599) they were seeing errors show up after we deployed this change on Jan 8th. We reverted and now are looking to reproduce the problem in staging.

Jerek suggested calling the [claims endpoint](https://staging-api.va.gov/v0/claim_letters) directly using vets.gov.user+12@gmail.com from our [staging users list](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv#L14).

He also suggested it may be related to the `connect_vbms` gem and I agreed based on [this trace](https://vagov.ddog-gov.com/apm/traces?query=%40_top_level%3A1%20env%3A%22eks-prod%22%20service%3A%22claim-status%22%20resource_name%3A%22V0%3A%3AClaimLettersController%23show%22%20host%3A%22i-0ed70b78bcf23aa64%22&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&env=eks-prod&graphType=flamegraph&historicalData=true&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=time&spanID=1516785844344646739&spanType=service-entry&spanViewType=errors&trace=420e3e32519e500f&traceID=3663991702621174030&traceQuery=&view=spans&start=1704831762942&end=1704831822942&paused=true).

**Comment by stevenjcumming** [comment]
To reproduce this error locally in tests (with `FakeVBMS`):

- Local machine must be running OpenSSL 3+
`ruby -r openssl -e 'puts OpenSSL::OPENSSL_VERSION'`
- Test certificates must be made for OpenSSL 1.1
location: `modules/claims_api/spec/fixtures`

<img width="1016" alt="Screenshot 2024-03-14 at 11 46 02 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/134282106/b1b3c7e0-be41-427a-86bb-4b6202f2f09d">

**Comment by stevenjcumming** [comment]
This issue is caused by a .p12 certificate (values in Param Store) used by connect_vmbs. The cert uses an encryption algo that isn't compatible with OpenSSL 3 (which is used by Bookworm). This will likely be resolved by updating the cert (which requires a password) to a newer algo and updating the values in the Param Store.

**Comment by stevenjcumming** [comment]
k8s branch has Debian upgraded. master branch needs to be upgraded before this ticket can be closed.
