### ISSUE TITLE
DR | Establish a starting point with prior research

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#61052]
## Value Statement
**_As a_** researcher who is interested in establishing a theory about the social process surrounding Decision Reviews
**_I want to_** assess previous research, including synthesis and findings
**_So that_** I can use any existing knowledge about internal and external variables that are part of the mental model of Decision Reviews.

---
## Background Context
- Research is going to start looking at the broader context of Decision Reviews so we can separate insight gathering and experimentation. To do that, a likely starting point is building a mental model of how users think of Decision Reviews, so we can form testable hypotheses about user behavior based on it. 

## Out of scope
- New research efforts

## Open questions
- Add here

## Tasks
- [ ] Check out documentation from squad 1 DR research
- [ ] Check out documentation from squad 2 DR research
- [ ] Check out documentation from Heather Roy's DR research, linked [here](https://coforma.slack.com/archives/C04M9CFPJP7/p1687813523383379) (she is available in DSVA Slack for questions and scheduling

## Definition of Ready 

- [ ] Access to all relevant documentation
- [ ] Team alignment on what we're curious about

## Definition of Done

- [ ] Research has reviewed information from the three most recent studies
- [ ] We have a shared space to consolidate things (like a Mural board perhaps)
- [ ] We have a sense of what's missing or where to start digging in
- [ ] We are aligned on where to point research next

**Comment by saderagsdale** [comment]
@eileen-coforma @rubensun made a ticket

**Comment by saderagsdale** [comment]
@rubensun add link to epic

**Comment by rubensun** [comment]
Attached to this epic: [Decision Review Experience Mapping](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61078)
