### ISSUE TITLE
Write a plan for the experiment

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#61055]
In order to get alignment on the strategy and tactics of the experiment, we will write a plan and socialize it among our team and with key stakeholders. 

## Tasks
- [ ] Draft a plan
- [ ] Share with team leads & iterate
- [ ] Share with LGA team & iterate
- [ ] Share with PO & key stakeholders
- [ ] Draft/refine tickets for next steps

## Acceptance criteria
- [ ] LGA team understands the plan, agrees that it is feasible
- [ ] Risks & dependencies are identified
- [ ] PO & key stakeholders understand the plan, agree that it is feasible

**Comment by djmunoz1** [comment]
list of tests https://docs.google.com/spreadsheets/d/1Q2W_2PKVwCKaMNEG-RsThlb7nUErJ18rIXg1Mr1W0ZU/edit#gid=218391671
