### ISSUE TITLE
Merge VA's CodeQL PR

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#61065]
## Issue Description
Description from the VA PR:
**Action Required**!

Automated source code scanning for potential security issues using CodeQL, Dependabot, and Secret Scanning is required for all repositories in the VA GitHub Enterprise Cloud.

There are steps that you will need to take to configure your repository to enable CodeQL code scanning. Dependabot and Secret Scanning will be automatically configured.

Our automation has analyzed your repository and identified the following [supported CodeQL languages](https://codeql.github.com/docs/codeql-overview/supported-languages-and-frameworks/#languages-and-compilers).
- `python`
- `javascript`
- `ruby`

The steps that you will need to take to configure your repository to enable CodeQL code scanning will be different depending on whether you are using GitHub CI tools or the external Jenkins CI tool:
- [Start here if you're using GitHub CI](https://department-of-veterans-affairs.github.io/ois-swa-wiki/docs/ghas/codeql-usage/how-to-enable-codeql-github-ci/)
- [Start here if you're using Jenkins CI](https://department-of-veterans-affairs.github.io/ois-swa-wiki/docs/ghas/codeql-usage/how-to-enable-codeql-jenkins-ci/)

Additional resources that you will need when you are configuring your repository to enable CodeQL using the guidance provided in the above-linked technical notes include the following:
- [Software Assurance System ID Catalog](https://github.com/department-of-veterans-affairs/.github-internal/blob/main/swa/emass.xls)
- [Edit CodeQL Analysis Workflow](https://github.com/department-of-veterans-affairs/performance-dashboard/blob/ghas-enforcement-codeql/.github/workflows/codeql-analysis.yml)
- [Add Excluded Languages List](https://github.com/department-of-veterans-affairs/performance-dashboard/tree/ghas-enforcement-codeql/.github)
- [Update Production Branch](https://github.com/department-of-veterans-affairs/performance-dashboard/blob/ghas-enforcement-codeql/.github/workflows/codeql-analysis.yml)
- [Remove Pull Request Trigger](https://github.com/department-of-veterans-affairs/performance-dashboard/blob/ghas-enforcement-codeql/.github/workflows/codeql-analysis.yml)
- [Create Custom Build Script](https://github.com/department-of-veterans-affairs/performance-dashboard/tree/ghas-enforcement-codeql/.github)

To request technical support:
- [Please book a meeting with OIS ISO SAVD Software Assurance](https://outlook.office365.com/owa/calendar/OISSoftwareAssurance@DVAGOV.onmicrosoft.com/bookings/)

https://github.com/department-of-veterans-affairs/performance-dashboard/pull/4099

---
## Tasks
- [ ] _Review PR_
- [ ] Meet with VA OIT OIS ISO SAVD Software Assurance to obtain emass ID

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
