### ISSUE TITLE
[spike] Decision Reviews | Real user monitoring

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#61066]
## Value Statement

**_As a_** developer 
**_I want to_** have greater ability to investigate and resolve errors efficiently
**_So that_** We can reduce time spent resolving errors that delay appeals.

---
## Background Context
Time boxed spike (2-3 hours). Talk to Steve and 1010EZ analytics person about using DataDog to setup a RUM view.

## Out of scope
Implementation or deep code assessment.

## Tasks
- [x] Talk to Steve
- [x] Talk to 1010EZ's analytics person about RUM set-up (Not necessary)
- [x] Figure out whether we can include user UUIDs with user sessions (Not necessary, because RUM would automatically pair errors with session replays).
- [x] Outline next steps for addressing FE errors
- [x] Make tickets

---
## Definition of Ready 
- [x] We're aligned on the scope of the spike

## Definition of Done
- [x] We know if we can use DataDog to create a RUM view or use other features for error remediation
- [x] We have a sense of next steps defined in tix

**Comment by saderagsdale** [comment]
Will have time this afternoon to close out.

**Comment by data-doge** [comment]
Spike complete. DD RUM looks good, and should be fairly easy to set up. VA.gov is open to a pilot. Follow up ticket here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/61817
