### ISSUE TITLE
[spike] Decision Reviews | Filter noise out of Sentry

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#61071]
## Value Statement

**_As a_** developer 
**_I want to_** filter out errors that make using Sentry for debugging more difficult 
**_So that_** We can reduce time spent resolving errors that delay appeals.

---
## Background Context
Time boxed spike (3-4 hours). Determine if errors can easily be filtered. If so, align on which ones should be removed. If not, pivot. 

## Out of scope
Add here

## Tasks
- [ ] Review errors in Sentry
- [ ] Determine criteria for which errors stay, and which ones go
- [ ] Determine if errors can easily be filtered
- [ ] If so, align on which ones should be removed

---
## Definition of Ready 
- [ ] We're aligned on the scope of the spike

## Definition of Done
- [ ] We know if we can easily filter Sentry errors
- [ ] We know what stays and what goes
- [ ] We know what the end state of Sentry for FE errors could look like
