### ISSUE TITLE
Clean Up Routing

### ISSUE THREAD

**Issue by ianmagenta** [department-of-veterans-affairs/va.gov-team#61082]
## Description
Right now the changes to default.js files and the root layout need a little more re-configuring.

## Tasks
- [ ] Turn `src/app/@unauthenticated/default.js` into `src/app/default.js`
- [ ] Turn `src/app/@uauthenticated/page.js` into `src/app/page.js`
- [ ] Modify `src/app/@authenticated/default.js` to redirect to `/getting-started`
- [ ] Modify `src/app/layout.js`
  - [ ] Remove `unauthenticated` prop (only `children` and `authenticated` props remain)
  - [ ] Pass `children` to the `unauthLayout` variable
  - [ ] Remove `{children}` above the conditional auth/unauthed rendering
