### ISSUE TITLE
Verification Support Strategy Video Editing

### ISSUE THREAD

**Issue by aparsley** [department-of-veterans-affairs/va.gov-team#61087]
[tasklist]
### Tasks
- [x] Edit and Compile draft videos
   - [x] mobile verification flow
   - [x] desktop verification flow
   - [x] errors encountered

**Comment by aparsley** [comment]
Good job, thank you.
