### ISSUE TITLE
Toxic exposure research sessions 

### ISSUE THREAD

**Issue by Nyanteea** [department-of-veterans-affairs/va.gov-team#61090]
Work on this ticket will begin after research plan and discussion guides are completed. 
Will be picked up when Lydia is back from vacation.

## Issue Description

Usability testing for new toxic exposure screens. We are hoping to recruit 12 participants for 8-10 completed sessions (1.25 hours each, maximum of 3 per day) from Aug 22- 28.

Conversation guide: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/research/2023-07-Toxic-Exposure/conversation-guide.md

Sketch prototype: https://sketch.com/s/c353146f-eceb-4626-9918-7603c693417f/a/71bq0jw/play

Sheet for observer sign up: https://docs.google.com/spreadsheets/d/1kRnURtzLtWLo38XpKfP-rsY_36sgkPHERpZXlz5Q_F4/edit#gid=0

Notes will be taken on Google Docs or Sharepoint, then compiled on Sharepoint after all sessions are completed.

---
## Tasks
- [x] Do run through with guide and prototypes
- [x] Run pilot session on Aug 21 and update guide or prototypes if needed
- [x] Complete moderation of all sessions
- [x] Add compiled notes and recordings to Sharepoint

## Acceptance criteria
- [x] Completed sessions
- [x] Notes and recordings added to Sharepoint

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
Notes taken by @RakshindaAslam - https://docs.google.com/document/d/1HDdPvHQ2CvI9XVYg918WlINvu7Ws3-NRgWAH3tBMVEc/edit?usp=sharing
