### ISSUE TITLE
EPIC | Notification Preferences | Email as a Channel / Default Send /  Checkboxes

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#61101]
## Background

[See here for the background/discovery work](https://github.com/department-of-veterans-affairs/va.gov-team/issues/51113)

## Important Documents 
- [Project Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/notification-preferences/default-send)
- [GH Directory ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/notification-preferences/default-send)
- [Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/default-send/releasePlan/defaultSendReleasePlan.md)
- [QA ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/notification-preferences/default-send/QA)
- [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/Research/2023-10-UAT-edit-as-subtask-default-send-checkbox-ui)

## Tasks

<details><summary>Completed Phases</summary>

```[tasklist]
### Consume Default Send on FE core work
- [ ] #56397
- [ ] #58790
- [x] #58890
- [x] midpoint review
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/60838
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/60818
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/60766
- [ ] #59043
```

```[tasklist]
### staging review prep (default send/checkboxes)
- [ ] #62091
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/61112
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/63278
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/63198
```

```[tasklist]
### QA
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62606
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62629
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65511
```

```[tasklist]
### Staging Review
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/63903
- [ ] #57409
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/67046
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/67073
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/67072
```

```[tasklist]
### UAT
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62610
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/64343
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62915
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/63880
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/63881
```

</details> 

```[tasklist]
### Launch
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62928
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62921
```

```[tasklist]
### Post Launch
- [ ] #68878
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62604
```

Any remaining email as a channel work has been moved to:
- #61102

## Acceptance Criteria
- [x] the work has been deployed to production 
- [x] we've removed toggles and cleaned up the code 
- [x] documentation has been updated (team documentation AND call center items)
