### ISSUE TITLE
[BE] Create CHIP folder structure under /lib in vets-api

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#61118]
## User Story
As a veteran-facing app, I want to be able to call CHIP endpoints through a client so that I can allow Veterans to check in to their appointments.

## Tasks
- [ ] [BE] Review platform docs on using shared components to create modules/libs
- [ ] [BE] Add to github codeowners file the owners
- [ ] [BE] Create a folder under /lib for `chip` with base folder structure (base classes)

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by randomsync** [comment]
platform doc: https://depo-platform-documentation.scrollhelp.site/developer-docs/service-objects
