### ISSUE TITLE
FE | Profile | Notification Settings | Email as Channel & Editing as a Subtask  | GA - map the new features to the current events

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#61112]
## Background 
Now that we've built out the bulk of the default send functionality, we need to ensure our GA tracking is updated

We should ensure we have GA ready to go for both Default Send work AND our Editing as a Subtask work 

## What we need to clarify: 
**for editing as a subtask,** 
are we good on the analytics side of things?
we wanna know who's using the new workflow vs the old workflow
and then we want to know if this leads to more complete user profile data overall (this likely isn't a GA item, [question out there for VA Profile](https://dsva.slack.com/archives/C7TE0PFTL/p1691506222804579))

**for the checkboxes**, were using the old GA tags/events and mapping those

**email as a channel:** don't think we need anything yet on these, but I think we'd want GA tracking on those once we confirm the naming and where/which things are going to display

## Tasks 
- [x] map new functionality to the existing GA events 
- [ ] update the release [plan here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/default-send/releasePlan/defaultSendReleasePlan.md#important-artifacts) linking to the appropriate Analytics dashboard we'll use for go-live 
- [ ] submit any [collab cycle analytics specific tickets ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review%2C+gtm&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D)needed

## Acceptance criteria 
- [x] all events are mapped 
- [ ] we have a dashboard ready for staging review/go live 
- [ ] analytics team has signed off on this from a collab cycle side of things

**Comment by adamwhitlock1** [comment]
I have merged work to trigger GA events for checkbox clicks on the Notification Settings page. Here is what the event looks like in staging at this time for when someone clicks the checkbox.

![Screenshot 2023-08-15 at 5.25.37 PM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/b8464c70-c662-475c-b62d-52bdd024eb81)

The only problem with this, is that the analytics on this event dont really indicate what the notification is that is toggled on or off, but just show the text... so thats not great.

I guess we should leave this open and maybe look at creating a custom event, or figure out how to pass more information to the built in checkbox component to allow better tracking.

**Comment by adamwhitlock1** [comment]
Some additional thoughts.

We aren't using the checkbox 'group' component and instead created out own wrapper for each group of checkboxes. This was due to some custom needs for styling and displaying success/failure alerts after each checkbox had been interacted with. I may be able to revisit this and get the checkbox group to work, and if that is the case, then it appears as though we could get the group name populated into GA events automatically.

If using the checkbox group component still isn't a viable option, then I could code in the analytics event call directly in our implementation using a checkbox change listener to snag the checkbox value. This would require the components 'built-in' analytics not to be used, and would be a bit more hacky, but this is actually how the old radio button events were wired up.

I'd like to try and use the built-in analytics if possible, as that is the recommended way.

**Comment by mtcA6** [comment]
@adamwhitlock1 im pro-built-in vs hackey. Would you mind creating a new ticket for next sprint and we can do the work there since I feel like we accomplished what we wanted here.

**Comment by adamwhitlock1** [comment]
Sure thing! I'll copy over most of this and add in the next steps / acceptance criteria.

**Comment by adamwhitlock1** [comment]
@mtcA6 Here is the new ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/63727

I think I got tags added and such, but double check for me when you get a moment.
