### ISSUE TITLE
[BE] Create `Configuration` class following platform standards

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#61119]
## User Story
As a veteran-facing app, I want to be able to call CHIP endpoints through a client so that I can allow Veterans to check in to their appointments.

## Tasks
- [ ] [BE] Create `Configuration` class under chip lib. This should include the common and necessary settings needed to configure CHIP client.

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
