### ISSUE TITLE
[BE] Add method to get `demographic-confirmations` to the Service class

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#61122]
## User Story
As a veteran-facing app, I want to be able to call CHIP endpoints through a client so that I can allow Veterans to check in to their appointments.

## Tasks
- [ ] [BE] Add method to call GET /demographics-confirmations endpoint

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
