### ISSUE TITLE
[BE] Add method to patch `demographic-confirmations`

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#61123]
## User Story
As a veteran-facing app, I want to be able to call CHIP endpoints through a client so that I can allow Veterans to check in to their appointments.

## Tasks
- [ ] [BE] Add method to call PATCH /demographics-confirmations endpoint

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
