### ISSUE TITLE
[BE] Add token method to the Service class to retrieve token from cache or call get_token endpoint

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#61126]
## User Story
As a veteran-facing app, I want to be able to call CHIP endpoints through a client so that I can allow Veterans to check in to their appointments.

## Tasks
- [ ] [BE] Add method to call CHIP POST /token endpoint

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
