### ISSUE TITLE
[BE] Create `Exception` class following platform standards

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#61120]
## User Story
As a veteran-facing app, I want to be able to call CHIP endpoints through a client so that I can allow Veterans to check in to their appointments.

## Tasks
- [ ] [BE] Create `Exception` class under chip lib to handle the exceptions and provide Sentry logging and descriptive error messages.

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
