### ISSUE TITLE
[BE] Create `Service` class with initialization code with api key

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#61121]
## User Story
As a veteran-facing app, I want to be able to call CHIP endpoints through a client so that I can allow Veterans to check in to their appointments.

## Tasks
- [ ] [BE] Create `Service` class under chip lib. This class will be the base class that includes methods to call other CHIP endpoints.
- [ ] [BE] Add method to initialize with the api key

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
