### ISSUE TITLE
Contact Center Overview 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#61134]
## Create an At a Glance view of Contact Center

_Clearly define the role of Contact Center within the VFS team and ensure VA.gov User issues are resolved in a timely manner. 

---
## Tasks
- [x] Create a document to house the overview
- [x] Define individual responsibilities for Contact Center
- [x] Define Tier 2 responsibilities  
- [x] Define Tier 3 responsibilities 
- [ X] Define Technical Writer responsibilities 
- [x] Define Engineering responsibilities 
- [X ] Define Data responsibilities _

## Acceptance Criteria
- [ ] _Complete and publish an At A Glance document for Contact Center including responsibilities for each team member. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
**Data Responsibilities**
* Update all relevant DOMO dashboards with Medallia and VA411 data
* Handle all incoming Qualitative Data Requests
* Update monthly CSAT scores for Performance Dashboard
* Act as point person for all Medallia discussions
* Address any DOMO dashboard needs in addition to the regularly maintained dashboards (i.e., dashboard requests)
 
**UX Tasks**
* Perform audits for VFS teams by analyzing Medallia data and qualitative responses
* Point person for any design-related concerns or issues related to Medallia
* Address any UX research needs, including writing Research Plans, Conversation Guides, administering research sessions and analyzing results
* Idea, design and test new feedback mechanisms

**Comment by manalo-soco** [comment]
Young Lee, Tier 2 Support Analyst 

-  Handling Tier 2 Veteran service cases in Salesforce and AVA
-  Guiding Va.gov users and Veterans in dealing with especially challenging service availability issues
-  Working within team SLA to respond to Veterans in Tier 2 tickets and help with case escalations to Tier 3 and EVSS 
-  Documentation of Tier 2 case handling and Veteran feedback regarding resolutions and email templates produced by CC team Content specialist. 


Ervin Pearson, Tier 2 Salesforce Analyst 

- Manage the processing of incoming Tier 2 issues to the Support Desk via Salesforce to ensure courteous, timely and effective resolution of end-user incidents and requests
- Agenda creation and documentation for VA.gov Contact Center team and VEO/ EVSS bi-monthly syncs 
- Report creating in VA Salesforce regarding case closures and escalations for Tier 2 and 3, s  
- Provides support for Va.gov users and Veterans by performing problem diagnosis and guiding users through step-by-step solutions
- Ensure customer service requests (tickets) are handled timely and completely
- Overseeing customer performance analysis, customer network reporting, and SLA compliance (that is set by the VA.gov project team)
- Guiding Va.gov users and Veterans in dealing with especially challenging service availability issues, help with documentation on patterns from Va.gov service outages and website errors

 
Mike Manalo, Tier 2 Support Analyst Back Up

-  Handling Tier 2 Veteran service cases in Salesforce and AVA
-  Guiding Va.gov users and Veterans in dealing with especially challenging service availability issues
-  Working within team SLA to respond to Veterans in Tier 2 tickets and help with case escalations to Tier 3 and EVSS

**Comment by aubreyarcangel** [comment]
Aubrey Arcangel, Frontend engineer, and support analyst 

- Lead engineering efforts for all Contact Center team projects
- Implement and maintain the veteran feedback survey tool
- Update monthly CSAT data and maintain all technical changes for the Performance Dashboard
- Assist tier 2 and tier 3 support in QAing issues from tickets
- Design solutions to reduce tier 1 tickets

**Comment by ATMiddleton** [comment]
Awaiting approval to update Contact Center confluence page.
