### ISSUE TITLE
Completed designs & prototypes for revised 4142

### ISSUE THREAD

**Issue by lydiahooper** [department-of-veterans-affairs/va.gov-team#61150]
Continuation of work started in this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/58793

##Issue Description
When a user selects that they want VA to review private medical evidence, they are forced to select either that they want to upload evidence themselves, or they want VA to get records, but they may want to choose both. Also, for users that choose to upload records themselves, they may be confused by the option to upload a 4142 PDF (which is NOT required for vets that choose to only upload evidence themselves). And there are two relevant pages in 526 currently using the deprecated wizard component, which presents accessibility problems.

This work will NOT be going through collab cycle

## Need to know
- Other prior ticket: https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/57876
- Sketch file: https://sketch.com/s/6ee257e1-d7b5-4879-9110-d083b0383d20
- New URL for standalone: https://staging.va.gov/supporting-forms-for-claims/release-information-to-va-form-21-4142/introduction
- This work runs alongside tech discovery: https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/58753
- Note this ticket from BDD SHA staging to address issues on these pages: https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/59257
- Bug/issue ticket relevant to this redesign: https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/59617

## Tasks
- [x] Review wireframes with Alejandro and revise if needed
- [x] Annotate wireframes for front-end, including for BDD flow and errors
- [x] Create prototypes in case they are needed for research

## Acceptance Criteria
- [x] Annotated wireframes for front-end eng
- [x] Prototypes for research, in case they are needed
