### ISSUE TITLE
Login.gov adoption team: Sprint 24 (7/6-7/19)

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#61162]
## PTO
- Svenja 7/7
- Carolyn 7/7–7/11
- Ksenia 7/7-7/13
- Steve 7/10-7/21
- Dawn 7/21 (Sprint 24) - 7/25 (Sprint 25)

## Sprint 24 Goals (to consider)
Refine our proof of concept into a production-ready comms campaign and further plans for IPP
- Prepare Reactivation email Test B version (Triggered emails sent via VA Notify) for release
- Compile report on Reactivation email Test A version (bulk email sent via GovDelivery)
- Explore GovDeliver platform for future campaigns
- Conduct IPP technical and non-technical discovery

## What we want to demo at the end of the sprint
- Reactivation email Test B version (on prod) @jrjamespdx 
- Reactivation email Test A version report @djmunoz1 
- IPP discovery read-out @skirkman16 
- GovDeliver decision* (ie account setup) @djmunoz1 
- Blog post 3 @CarlDickerson 
- Styleguide for comms @CarlDickerson 

## Sprint 24 Tasks
**Prepare Reactivation email Test B version:**
- [ ] Ticket title #12345
- [ ] Ticket title #12345

**Complete required collab cycle checkpoints:**
- [ ] Ticket title #12345
- [ ] Ticket title #12345

**Compile report on Reactivation email Test A version**
- [ ] Ticket title #12345
- [ ] Ticket title #12345

**Explore GovDeliver platform for future campaigns**
- [ ] Ticket title #12345
- [ ] Ticket title #12345

**Conduct IPP technical and non-technical discovery**
- [ ] Ticket title #12345
- [ ] Ticket title #12345

**Finalize Dashboard 2.0 design and begin implementation**
- [ ] Ticket title #12345
- [ ] Ticket title #12345

**Other:**
- [ ] Ticket title #12345
- [ ] Ticket title #12345

**From [Retro](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1677768711421/aad15b9308afe560c52a1beddefe388840ae239d?wid=0-1682539365898&sender=uaaa67493ae613f0003928743):**
- [ ] Keep forefronting demo prep throughout the sprint
- [ ] Consolidate our documentation
- [ ] Set expectation for providing updates on meetings. Slack vs. Github
- [ ] Firm deadlines
- [ ] Regular 1:1s

-----

## Future Sprint Goals (deferring for now)
- [ ] Dolor sit amet

**Tasks we're deferring for now**
- [ ] Ticket title #12345
