### ISSUE TITLE
Create proposal for Veteran's board

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#61168]
Objective: Develop a Veterans Board to collaborate on feedback and design iteration with Veterans in order to advance the effectiveness of campaign touchpoints (i.e., comms + in-person proofing)

## Tasks
- [x] Check with Identity research team on existing experience with Veteran Boards
- [x] Draft considerations for Veteran Board
- [x] Develop research engagements overview
- [x] Review approach in research office Hour

## Acceptance criteria
- [x] Finalize overview and schedule research office hours to present

**Comment by sleggewie** [comment]
Objective: Develop a Veterans Board to collaborate on feedback and design iteration with Veterans in order to advance the effectiveness of campaign touchpoints (i.e., comms + in-person proofing)

##tasks
- [ ] Check with Identity research team on existing experience with Veteran Boards
- [ ] Draft considerations for Veteran Board
- [ ] Align on key questions within Campaign
- [ ] Develop research engagements overview
- [ ] Craft research brief for first two engagements
- [ ] Review approach in research office Hour
- [ ] Submit plan for review

##acceptance criteria
- [ ] Veteran Board approach verified
- [ ] Research plan overview
- [ ] Submission of first research brief

**Comment by skirkman16** [comment]
[Research Planning doc](https://docs.google.com/document/d/1ZjjmzhpzZd8WV92AejE3TJJsRuZo2fYT2d9rTAk__Dg/edit)
[Proposal slides](https://docs.google.com/presentation/d/1CqpXqu-eQ-CphfkyhRp2RMGpmYzrB6ts/edit#slide=id.g24ef6e6b543_0_22)

**Comment by skirkman16** [comment]
we presented our pitch to Kevin Hoffman and Robyn Singleton. We should refer to this ticket to break down the next steps which will be writing up a research brief, conversation guide, and informed consent for Perigean
