### ISSUE TITLE
Iterate on blog post 3: draft and socialize for production

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#61169]
## Summary 
As a Veteran, I want to understand the current focus on sign-in and the larger context of digital modernization efforts going on at VA. 

### Tasks
- [x]  @CarlDickerson Draft new blog post
- [x]  share for Internal review w/ Svenja
- [x]  share for external review: Danielle Thierry / Sitewide

### Acceptance Criteria
 - [x] Blog drafted
 - [x] Blog Shared with Sitewide for feedback

**Comment by CarlDickerson** [comment]
Blog Post 3 working document: https://docs.google.com/document/d/1wQK7PcO_dn2WLTSNTS_JSCtT12wgP2QgVlp8ltsdP_c/edit?usp=sharing

**Comment by CarlDickerson** [comment]
Sitewide review ticket https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/62310
