### ISSUE TITLE
Implement Dashboard 2.0 per updated design

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#61167]
As an LGA team member, I want to implement the Dashboard 2.0 [as designed](https://app.zenhub.com/workspaces/logingov-adoption-team-632280b31e745000136a61fc/issues/gh/department-of-veterans-affairs/va.gov-team/59101
) in order to align the data we see in Domo with our program's KPIs. 

## Tasks

- [ ] Assess feasibility of Dashboard 2.0 wireframes for implementation
- [ ] Carolyn to Iterate and pair program with Steve to implement design
- [ ] Steve to implement design in Domo

## Acceptance Criteria

- [ ] Dashboard 2.0 wireframe has been implemented in Domo
- [ ] Data can be viewed by Dawn and Anthony
- [ ] Data can be accessed and shared for the next 20th of the month share out

**Comment by djmunoz1** [comment]
deprioritizes
