### ISSUE TITLE
Improve webpack build time 

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#61179]
## Issue Description
- [ ] Investigate what loaders we can replace and improve to optimize efficiency for build time
- [ ] Update web pack configuration files 
- [ ] This will touch many many files, so we need to a ton of unit/testing for these changes 
- [ ] VA may want a manual regression for a change of this nature, since it affects the entire [VA.gov](http://va.gov/) site

## Issue Description
Time box this issue? 

### Acceptance Criteria (Thomas or Fred to complete) 
- [ ]

**Comment by tblackwe** [comment]
@fred-khoury-oddball when you have a moment to breath, can you remind me where we left off with this ticket?

@zack we had this a quality of life improvement for engineers. only tagging you cause I saw your local webpack change :D

**Comment by fred-khoury-oddball** [comment]
Sure with the change I was trying to make I could not get it to work in the preview environment. It kept breaking things causing the header and footer to disappear.

**Comment by tblackwe** [comment]
This was never completed, and Fred left taking the knowledge with him. Closing as abandoned.
