### ISSUE TITLE
Identity Dashboard FE - Adds a11y suite to GHA (CI/CD)

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#61175]
## Description
Integrate the a11y testing suite script into Github actions

## Tasks
- [ ] Add the `script` as part of the CI/CD build process in the Github Actions
- [ ] If the a11y suite fails
  - [ ] AND is a fixable issue without manual intervention, run the automatic fix and continue `build` process
  - [ ] AND is only fixable with manual intervention, prevent the `build` process from running

**Comment by asg5704** [comment]
Work complete
