### ISSUE TITLE
Profile | EVSS>LH Direct Deposit | UAT testing - Conduct Research

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#61170]
## Background 
This ticket is to conduct UAT research w Perigean

We discussed needing two tickets for UAT, 
1 research plan - maybe add in the research plan the [updated CTA from #59728](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59728), conversation guide, and kick off recruitment [see #60942 ]
2 running UAT study **[this current ticket]**

## Tasks 
- [x] complete the research 
- [x] draft the summary 
- [x] Update the [release plan ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/evss-lighthouse-migration/direct-deposit-release-plan.md#results)w the results
- [x] update [Project Outline ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit/evss-lighthouse-migration#key-deliverables) with link to the results

## Acceptance Criteria 
- [ ] research is completed 
- [ ] discuss w PM and PO

**Comment by pamela-drouin** [comment]
@mtcA6 I've completed 3 points (setting things up with Perigean, running the pilot session, making some edits to the script, coordinating to make sure all participants's accounts will access the correct end point). 5 left to go!

**Comment by pamela-drouin** [comment]
[Findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/Research/2023-08-direct-deposit-UAT/2023-08%20UAT%20findings.md) are on Github!
