### ISSUE TITLE
Identity Dashboard (FE) - Fix Header component Chakra UI

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#61176]
## Description
Bug: Fix the Header component from Chakra UI

## Screenshot of Header styling issues (pre Chakra UI)
![Screenshot 2023-06-29 at 2.46.31 PM.png](https://images.zenhubusercontent.com/5f3be621ca5d1e85751d760d/4cb75ba1-63de-4a3f-80fc-24185503ddda)

## Tasks
- [x] Update the stylings from Chakra UI to match the Figma prototype
- [x] The US Govt Header bug is resolved (see below)
  - [x] Sometimes has a margin-bottom (1em I think) and when refreshing it does not
- [x] Ensure the Crisis Line bug is resolved (see below)
  - [x] Sometimes has a transparent background and sometimes does not)

**Comment by acald-creator** [comment]
- Partially done on replacing all relevant generic HTML with Chakra UI
- Adjusted styling to Chakra UI away from VA Design System sass styling
- Updated some of the icons to be replaced with `react-icons` which also has Font Awesome Icons to be used
- Margin-bottom is resolved by adding the 1em to the section


To do - needs to finish the rest of the styling and ensure that it is laid out correctly, instead of beside each other

**Comment by acald-creator** [comment]
Replaced Govt Header with Chakra UI: 

https://github.com/department-of-veterans-affairs/identity-dashboard-fe/pull/55

**Comment by acald-creator** [comment]
Replaced parts of VA Crisis Line, https://github.com/department-of-veterans-affairs/identity-dashboard-fe/pull/56
