### ISSUE TITLE
Transformer knowledge

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#6118]
## Problem Statement
How might write json transformers for 6 new listing pages?

## Goal
Prepare to pair program with CMS team (https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1005)

## Tasks
- [ ] Review existing documentation

## Acceptance Criteria
- [ ] Readiness for pair programming
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
