### ISSUE TITLE
Identity Dashboard (FE) - Migrate FWA dashboard views

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#61185]
## Description
Migrate the FWA dashboard (currently in Vue) into Next.js (`identity-dashboard-fe`) repo.

## Tasks
- [x] Migrate the basic FWA dashboard views into the repo
- [x] Place in the Monitoring page (for now)
- [x] Use details view for each log (for now)

**Comment by aparsley** [comment]
Keep up the good work.
