### ISSUE TITLE
Identity Dashboard (FE) - FWA dashboard search/filtering

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#61189]
## Description
Searching & filtering depends on the FWA dashboard migration

## Tasks
- [x] Add searching and filtering of DD logs
  - [x] Add search bar (sanitize field)
  - [x] Add Start and End Date filtering
- [x] Remove Axios and use React Query instead

**Comment by aparsley** [comment]
Looks good, keep up the good work.
