### ISSUE TITLE
[CHIP] - GET demographic statuses - reporting

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#61194]
## Summary
Add reporting to all areas of function. See existing initiateCheckIn and checkIn endpoints to see what and when to log using the existing `LoggerService` and `MetricsService`

## Tasks
- [ ] [CHIP] add logging

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by lee-delarm6** [comment]
#61192 blocks the rest of this, but will likely be included in the core portion of the ticket
