### ISSUE TITLE
[Discovery] 10-10EZ - Screener pages: Look into alternatives or removing the screener questions for unauthenticated Veterans

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#61198]
## Background
Over the last few years, in almost every research session we have held, there is feedback on the Screener pages that are presented after the Veteran enters their Name, DOB and SSN.  These screener pages (Personal information pages) are redundant and cause confusion, most especially (but not exclusively) for Veterans using screenreaders.

We need to determine if there are alternatives, including removal, of these redundant pages.  This will require engineering input to confirm the alternatives are technically feasible.

<details>
<summary>Screener questions - Screenshots (click to expand)</summary>

![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/ee6a7721-91d9-405d-b973-bcbebf9da56c)

![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/2d90f8a9-1eb6-45e9-99f8-8932d7357b25)

![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/f2020536-e52c-4a1d-bfc9-b301a54ca9d6)

</details>

## Tasks
- [x] Review past research findings to gain an understanding of the cause for confusion/painpoint
     - Recommend looking at Short Form research 
- [x] Determine what technical solutions may be possible
     - I would personally love to remove these pages, but I don't know if that is possible or the best solution
- [x] Touchbase with PMs on recommendation and next steps, if any

## Acceptance Criteria
- A solution (or possible solutions), to reduce or remove the redundancy caused by the Screener questions, are outlined and shared with team/PMs

**Comment by davidakennedy** [comment]
Working [Mural board with links to research, screenshots and more](https://app.mural.co/invitation/mural/departmentofveteransaffairs9999/1688593774816?sender=u773b824999f25f58b8e77486&key=cd6aa8ac-00aa-45ed-9a9b-e6bc8ec5bf3d).

**Comment by davidakennedy** [comment]
I wanted to wrap up this ticket with a few details:

- My recommendation is to remove the screener pages. The Mural board has more details with research to back that recommendation up.
- I added a link in the Mural board to our [technical discussion in Slack](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1688593774816/c44e309b107b8df7e9b8647d385ab4b0c8b7757a?wid=0-1689022292584). There isn't any technical limitations to removing the pages.
- I added screenshots of the review pages in both authenticated and unauthenticated paths. The authenticated path doesn't include information from these pages in the review. The unauthenticated review page does. This is okay from a UX standpoint since people are only reviewing and editing what they enter.
