### ISSUE TITLE
BE | Profile | Direct deposit | Add Production AWS Params

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#61199]
## Background
The following AWS parameters need to be added and configured in `vsp-infra-application-manifests` repo.

Add the following AWS parameters (specific to Direct Deposit):
- /dsva-vagov/vets-api/prod/lighthouse/direct_deposit/host
- /dsva-vagov/vets-api/prod/lighthouse/direct_deposit/access_token/aud_claim_url
- /dsva-vagov/vets-api/prod/lighthouse/direct_deposit/access_token/rsay_key
- /dsva-vagov/vets-api/prod/lighthouse/direct_deposit/access_token/client_id

## Tasks
- [x] Coordinate settings with other VFS teams
- [x] Add prod params to AWS parameter store
- [x] Add prod configuration to `vsp-infra-application-manifests` repo
- [x] Update vets-api setting.yml configuration

## Acceptance Criteria
- [x] Reviewed by platform support team member
- [x] Test in production

**Comment by tpharrison** [comment]
Mobile team is already working on this.  Waiting to hear back from them.

**Comment by tpharrison** [comment]
Spoke with the mobile team and we settled on the naming conventions for the parameters.
