### ISSUE TITLE
[CHIP] - GET demographics statuses - fetch and return demographics object

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#61192]
## Summary
Fetch the demographics for a given patient using the payload from the request. Use the existing `clinicianWorkflowService` to fetch the demographic statuses. Parse the insurance and demographics statuses.  Construct the object to return to the client. 

Determine `needsConfirmation` value by checking the last updated date is within 7 days.

## Tasks
- [x] [CHIP] fetch demo statues
- [x] [CHIP] use last updated field to determine `needsConfirmation` value
- [x] [CHIP] return entire demographics object with fields outlined in https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/full-auth-check-in/chip-design-doc.md
- [x] [CHIP] add tests

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
