### ISSUE TITLE
Increase Speed on persistent volumes

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#61207]
# Description
EFS volumes appear to be quite slow. At the moment, our start script is configured to wipe out the previous build in the same path as the previous build. This process takes a long time to complete, and we have to create an unusual bit of code to accommodate that process --

```echo "Navigate into /app/website/slow"
cd website/slow
echo "Generating timestamp"
TIMESTAMP=$(date +%s)
echo "Timestamp value: " $TIMESTAMP
echo "Moving: " $SOURCE_REF " to " $SOURCE_REF"-"$TIMESTAMP
mv -vf $SOURCE_REF $SOURCE_REF"-"$TIMESTAMP
echo "Removing previous build in background"
rm -rf $SOURCE_REF"-"$TIMESTAMP &
echo "Creating directory: " $SOURCE_REF
mkdir $SOURCE_REF
echo "Navigate into: " $SOURCE_REF
cd $SOURCE_REF
```

# Tasks
- [x] Research the possible approaches to take to speed up our EFS volume use from containers
- [ ] Provide a recommendation for how to speed up our use of EFS volumes in PE

# Acceptance Criteria
- [ ] We have a plan to speed up EFS volume usage

**Comment by holdenhinkle** [comment]
The `rm -rf $SOURCE_REF"-"$TIMESTAMP &` process that running in the background consumes I/O and could impact the performance of other tasks eventually (like when the EFS is being updated regularly).

**Comment by pjhill** [comment]
I asked ChatGPT how to speed up a workload with lots of small files on an EFS volume and it responded with --

EFS (Elastic File System) from AWS is a distributed storage solution designed to be highly durable and scalable. But when it comes to handling many small files, you may encounter some performance issues due to several factors:

1. **Throughput Scaling**: In EFS, the performance is linked to the size of your file system in the standard storage class. The larger your file system, the higher the baseline throughput, and the faster the burst credits recover. If your system mainly consists of small files, your total file system size might be quite small, thus limiting your performance.

2. **I/O Operations**: Operations in EFS are typically at the file level. So, if you are writing or deleting many small files, each one of these operations is a separate operation in EFS. This leads to higher I/O, which can reduce the overall performance.

3. **Network Latency**: EFS is network file system, and its performance can be affected by network latency. If your EFS and EC2 instances are in different availability zones or regions, you may encounter latency issues.

4. **File System Burst Credits**: EFS uses a credit system to determine when file systems can burst above their baseline throughput. If you have many small files, your operations may consume burst credits faster than they can be replenished, resulting in slower performance once those credits are exhausted.

5. **Concurrency**: EFS is designed to scale out, to achieve higher aggregate throughput and IOPS. But when operations are targeted at a small set of directories or files, they can become a bottleneck.

To improve the performance, you could:

1. **Increase File System Size**: Add more data or files to increase the baseline performance of your EFS.

2. **Optimize I/O**: Combine smaller files into larger ones where possible to reduce I/O operations.

3. **Provisioned Throughput**: Instead of relying on the size of your file system to determine throughput, you can set a specific throughput, regardless of the amount of data stored.

4. **Optimize Network**: Make sure your EFS and EC2 instances are in the same availability zone to reduce latency.

5. **Parallelize Operations**: Try to make your file operations as parallel as possible. This works particularly well for EFS, which is designed to handle parallel requests efficiently.

6. **Use EFS Infrequent Access (IA)**: If these files aren't frequently accessed, you might consider using EFS Infrequent Access. IA is cost-effective and offers similar performance to EFS Standard for the majority of workloads.

Remember that your particular use-case and workload characteristics can greatly impact the effectiveness of these potential solutions.

**Comment by holdenhinkle** [comment]
We can't use [EBS](https://aws.amazon.com/ebs/) because it's tied to one EC2 instance.

**Comment by holdenhinkle** [comment]
The performance of AWS EFS is directly tied to the size of the filesystem, but it's important to note that "big" is a relative term when it comes to data.

EFS has two performance modes: General Purpose and Max I/O. In General Purpose mode, which is suitable for most workloads, latency is low, but there's a limit of 7,000 file operations per second. In Max I/O mode, there's virtually no limit on operations per second, but latency is a bit higher.

For throughput, EFS offers two modes: Bursting and Provisioned. In Bursting mode, the rate at which the file system can burst is directly related to its size. AWS uses a "credit" system, where a file system earns credits over time and spends them when it reads or writes data. The bigger the file system, the higher the baseline rate and the faster it accrues burst credits. For a file system in Bursting mode, the relationship between storage and throughput is linear - each GB of storage provides 50 KB/s of throughput, up to a max of 80 MB/s.

In Provisioned mode, you set the throughput regardless of the amount of data stored. This allows you to get higher performance for smaller filesystems, but at a higher cost.

Given that our workload appears to be read-heavy and involves large files, the following performance and throughput modes may be suitable for us:

For the Performance Mode, considering that we're dealing with sizable files, the Max I/O performance mode could be a good choice for us. It's optimized for high levels of aggregate throughput and operations, making it a good fit for large scale, parallelizable workloads. However, it does have slightly higher latencies for file operations, which might not be a problem if our application isn't latency-sensitive.

I'm not sure certain what the Throughput Mode should be. I'm guessing Busting (the less expensive of the two Throughput modes) is fine because we're probably not accessing the data to often.

**Comment by holdenhinkle** [comment]
Apparently, the directory structure in EFS matters quite a bit. EFS is faster when reads and writes are not in the same directory. Here's a proposed directory structure for `content-build` files:

```
/content-builds/
  /2023/
    /07/
      /01/
        /build-10:00:00/
          (build files)
        /build-14:00:00/
          (build files)
      /02/
        /build-09:30:00/
          (build files)
        /build-15:00:00/
          (build files)
      ...
    /08/
      ...
  /2024/
    ...
```

**Comment by holdenhinkle** [comment]
Regarding "Parallelizing Operations":

"Parallelizing operations" in EFS doesn't refer to a setting you can adjust in AWS EFS itself, but rather it's a best practice you can adopt at the application level to optimize performance. This means designing your application in such a way that it can issue multiple read and write operations concurrently, rather than one at a time.

Here are a few ways you can implement this:

1. **Multithreading**: If your application is capable of multithreading, you can design it to read and write files on separate threads.

2. **Multiple instances**: You can increase the number of instances that are reading/writing to the EFS filesystem.

3. **Multiple mount points**: For high levels of throughput, consider mounting the EFS filesystem at multiple points on the same EC2 instance.

Remember to spread out your operations as evenly as possible across your files and directories. AWS EFS performance is optimized when operations are spread across different files and directories because it's designed to provide greater aggregate throughput as you scale out your access patterns.

**Comment by holdenhinkle** [comment]
Good article - https://www.jeffgeerling.com/blog/2018/getting-best-performance-out-amazon-efs

> Monitor EFS Burst Credits
> I'm pretty sure this is one of the most mentioned suggestions in every guide to using EFS I've seen. And it's par for the course with AWS offerings—you can usually start out using the free/cheap tier of a service, but once you start putting production loads on the service, you'll have your first major outage with no discernible cause.
> 
> That is, if you're not monitoring burst credits.
> 
> My team spent over an hour trying to diagnose why MySQL connections were stacking up, application threads were clogged, and extremely few requests were getting responses. Finally, we noticed that file operations were really slow. Really really slow. And then I remembered I had built a dashboard in our monitoring system for EFS, so I looked there, found that our Burst Credits were expired, and our Permitted Throughput went from 50 Mbps to 0.5 Mbps. And this was in the middle of a full EFS backup (more on that later!).
> 
> So, make sure you add alerts in CloudWatch or elsewhere on your BurstCreditBalance. If it starts going down, make sure it doesn't keep going down. And if you need more burst credits, or a higher normal throughput limit, see the next section:

**Comment by holdenhinkle** [comment]
Another article saying that same stuff - https://blog.cloudboost.io/how-to-optimize-your-efs-workloads-9f48c5715f66

# Hack to Increase Xfer Rates

Each new volume starts with a .5MB/s transfer rate. Volumes also start with 7.2 minutes of burst credits that can boost transfer speed to 100MB/s during use. The only way to increase the number of burst credits available to you, or your baseline throughput, is to increase volume size.

The easiest way to increase volume size is to upload large dummy files to volumes after creation. This incurs storage fees but can significantly boost performance. To avoid additional costs make sure not to include dummy files in your backups.

**Comment by pjhill** [comment]
For some reason the EFS volume is  provisioned / detected as quite large already --
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/2cc6b6b4-17f2-4088-9bdc-333fbb20f791)

**Comment by pjhill** [comment]
I think it's 8 exabytes --
`127.0.0.1:/     8.0E  7.5G  8.0E   1% /app/website/slow`

**Comment by holdenhinkle** [comment]
# Recommendations

- Try setting the Performance Mode to "Max I/O"
  - I'm not sure this will help but it might be with a try. The "General Purpose" Performance Mode has the lowest latency out of the two modes and can handle up to 7,000 file operations per second which is probably enough for us, while "Max I/O" mode has virtually no limit on operations per second, but latency is a bit higher.
- Try setting the Throughput Mode to "Provisioned"
- Optimize our directory structure so files are in their own directories. Here are some ideas:

```
/content-builds/
  /2023/
    /07/
      /01/
        /build-10:00:00/
          (build files)
        /build-14:00:00/
          (build files)
      /02/
        /build-09:30:00/
          (build files)
        /build-15:00:00/
          (build files)
      ...
    /08/
      ...
  /2024/
    ...
```

Or keep the structure relatively flat:
```
/content-builds/
  /2023/07/01/build-10:00:00/
    (build files)
  /2023/07/01/build-12:00:00/
    (build files)
  /2023/07/02/build-08:00:00/
    (build files)
  ...
```
