### ISSUE TITLE
Getting import CA certs scripts working

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#61200]
# Description
Other platform teams recommended the use of a CA cert import script used elsewhere on the platform. We have borrowed that script verbatim from `vets-api`. That script is currently in a branch [here](https://github.com/department-of-veterans-affairs/vets-website/blob/pe_slow_content_build/src/platform/utilities/preview-environment/import-va-certs.sh).  Certificates do not appear to be loaded successfully, and yarn install is still failing in the FE container. The certs are loaded in the Dockerfile [here](https://github.com/department-of-veterans-affairs/vets-website/blob/pe_slow_content_build/src/platform/utilities/preview-environment/Dockerfile).

# Tasks
- [ ] Analyze the errors occurring during the loading of the certificates
- [ ] Understand why the certs are not loaded successfully into the image
- [ ] Implement a fix that loads CA certs into the Docker image

# Acceptance Criteria
- [ ] Our FE image contains the CA certs it needs to retrieve yarn dependencies
- [ ] FE image starts a VA.gov instance successfully upon startup

**Comment by rmessina1010** [comment]
Linking for  cross reference: https://github.com/department-of-veterans-affairs/va.gov-team/issues/60685

**Comment by rmessina1010** [comment]
Certificates work and allow yarn to import node modules.
