### ISSUE TITLE
Verify API_URL is configured correctly and FE talks to BE

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#61204]
# Description
Once the issue with the FE pod's dependencies installing correctly and starting up is resolved, we need to run tests to verify that the FE container is able to route API requests to our BE container and receive responses.

# Tasks
- [x] Run basic tests of API requests from our FE container
- [ ] Verify that the mock data repository is being used when necessary

# Acceptance Criteria
- [ ] FE container communicates with BE container via the configured API_URL address

**Comment by pjhill** [comment]
Waiting on a stable FE container / pod to be available in order to verify this configuration works as expected.

**Comment by pjhill** [comment]
Something still seems to be going wrong when attempting to use apps --
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/4545c256-a3c5-4a1e-a61c-56bd4e969108)

**Comment by JoeTice** [comment]
Sprint 32 Update: In Progress - We are continuing to work on this, have made progress but haven't fully resolved the issues yet. Work will continue in Sprint 33

**Comment by JoeTice** [comment]
Re-assigning to @ben-allen-oddball

**Comment by JoeTice** [comment]
Sprint 33 Update: Paused - This task may not be needed based on new information discovered this sprint regarding another team who is looking into improving content-build. Hope to have a definitive answer on this task during this sprint.

**Comment by JoeTice** [comment]
These tickets are OBE as our approach is shifting, closing these tickets to reflect that.
