### ISSUE TITLE
[Design] 10-10EZ - Memorable Date: Look into updating all "date" fields on 10-10EZ

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#61211]
## Background
Over the last few years, in almost every research session we have held, there is feedback on the "date" fields being confusion, and hard to use.  There are reports from Medallia feedback and even Business partners completing testing, that the Month and Day dropdowns 'jump' form their selection to another Month or Day.

To remedy this painpoint, we need to look into the [Memorable Date component](https://design.va.gov/components/form/memorable-date) and determine whether we can use this format, and whether it would truly resolve the issues being experienced today within our form.  We can do this by checking in with other teams using this component and gathering any feedback they may have.

**NOTE: If we decide to implement this component, we may want to look into doing the same for the 10-10CG, if it makes sense to do so.**

## Tasks
- [x] Review the Memorable Date component
- [x] Review other teams' research findings on feedback around using this component
- [x] Determine whether our forms and Veteran applicants may benefit from having this component
- [ ] Touchbase with PMs on recommendation and next steps, if any

## Acceptance Criteria
- A recommendation on either using or not using the Memorable Date component within our form is shared with team/PMs

**Comment by katelyncai** [comment]
**Next steps after discussing with design team on 07/17/23:**

- DK shared [a related accessibility ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1550) (thanks DK!)
- Look into design system updates to v3 (I [reached out on DSVA Slack](https://dsva.slack.com/archives/C01DBGX4P45/p1689706497782709))
- Document desk research thus far (will link here in the ticket when ready)

**Comment by katelyncai** [comment]
I've documented the [date component desk research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZ%20Form/date-component-discovery.md) for this ticket.
Will discuss next steps with @hdjustice .

**Comment by katelyncai** [comment]
Synced up with @hdjustice today. We plan to implement the experimental memorable date component (3.0) on the CG form first. We'd like to wait until the facilities API work is complete, so that we can test both the facilities improvements and the new date component together. Closing this out.
