### ISSUE TITLE
allow for automate merges of vets-api PR's

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#6121]
## User Story or Problem Statement
on vets-api, merging a PR can be tedious.  the PR needs to be up to date with CI passing  before a PR can be merged. At this time, CI takes ~14 minutes (a problem for another issue), which is just long enough for a dev to go do something else, forget for a while and then come back to the original PR only to discover there are new commits on master and the whole cycle will start again. 

## Goal
A vets-api developer should be able to mark a PR ready to merge in some way so that it will be merged as soon as CI passes. 

## Objectives or Key Results this is meant to further
 vets-api developers will be able to merge PR's more quickly and will spend less time returning to PR's 

## Tasks
- [ ] implement something like https://github.com/ridedott/merge-me-action to allow for pr's to be merged as soon as CI passes.

## Acceptance Criteria

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saneshark** [comment]
👍 and THANK YOU! YES, this would be a huge and welcome improvement. Currently waiting 25 minutes and babysitting a PR.

**Comment by johnpaulashenfelter** [comment]
This has been handled by a config change for quite some time.
