### ISSUE TITLE
Content edits for #61156

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#61228]
## Issue Description
Make content updates based on [support request #61156](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61156)

---
## Tasks

- [x] Make content updates per [support request #61156](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61156)
- [x] Prepare the page for deployment (any launch-blocking issues)

## Acceptance Criteria

- [x] Page [Creating a new application](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application) will have content updates made according to support request details.

**Comment by taylojill** [comment]
I made the following updates to the Creating a new application page and sent a PDF export showing the changes to @acrollet 
I'll update the live page after receiving approval/sign-off.

1. Added a step 5 to Update revproxy config...
2. After Manual setup section, added PR merge order section and text

**Comment by taylojill** [comment]
I updated/corrected the Creating a new application page per @acrollet feedback. Page is in place and ready for deployment. No launch-blocking issues.
