### ISSUE TITLE
Add ability to cancel an appointment

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#61224]
## Description 

Veterans are seeing similarities of completing pre-check-in with confirming an appointment via the VeText appt reminder process. 

> "Is there a link that I can go to to change my appointment? For example, change or cancel. Sometimes something comes up and I need to either change or cancel."

If a Veteran is completing pre-check-in for one appt in the web app and they want to complete pre-check-in for another appt within the same session, there options are to either 1) View details, or 2) Confirm the appt. This is identical to the VeText process. Therefore, Veterans asked if they could also cancel their appt too because that's what they typically do in VeText. 

So, adding cancel as an option during the pre-check-in process should be considered. 

Other consideration is whether cancel should be included for appts that have completed pre-check-in. This would be similar to the Appointments web app. So, would need to check how they handle cancelling appts. For now, this ticket does not include this. 

## Tasks

- [ ] Talk to VeText about the flow when a Veteran answers N1 to cancel. What happens then? 
- [ ] Create user flow for cancel
- [ ] Create wireframes 
- [ ] Review with stakeholders, e.g., ux team, product team, VeText, Laura, etc. 

## AC

- [ ] User flow complete
- [ ] Wireframes complete
- [ ] Wireframes have been reviewed 
- [ ] Create ticket for FE to begin work

**Comment by bouayabenmehdi** [comment]
can I work on this task ?
