### ISSUE TITLE
Iteration of script and database

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#61239]
### DEFINITION OF DONE
- [ ] List of products that can be used to verify code inventory
- [ ] Code inventory is verified. Verification is clearly documented
- [ ] Completion of script updates per previous findings
- [ ] Run script 2.0
- [ ] Database has been updated
