### ISSUE TITLE
Code Inventory

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#61233]
### PROBLEM STATEMENT
To begin a project of determining and documenting code ownership of code in vets-api, we need conclusive list (database) of what code lives in vets-api.

### DEFINITION OF DONE
- [x] MVP of script to pull list of code that lives in vets-api
- [x] MVP script has been run
- [x] Code from script is in an MVP database
- [x] Slack channels are linked to teams
- [x] List of files with no recent commit history
- [x] Have conclusive list of OCTO crews

**Comment by laineymajor** [comment]
Summary of progress as of COB 7.7.23:
1. Initial script run
2. @RachalCassity debugged script
3. Ran script again
4. @RachalCassity started with review of modules and models + identification of owners 
5. @rjohnson2011 started with the review of controllers + identification of owners
6. Lainey completed [list](https://docs.google.com/spreadsheets/d/1zRKiiIaZNiUQz3FC69xy1A7HUU2zRBPmZSYYNuDsFQ4/edit#gid=0) of OCTO crews, POs, teams, and their slack channels
7. Meeting to discuss progress on Friday. Decided there needs to be an action item added to the AC that requires some kind of next step in keeping the information fresh.... otherwise we are creating future rework (product directory as reference)

Next steps:
1. Rachal continue working through models; has identified dead code
2. What to do with dead code??
3. Ryan taking a step back and mocking up a structure for this information.... keeping sustainability in mind (doing this with his product directory experience in mind)
4. Lainey working to identify who is on what team
5. Lainey and Lindsey to talk with Bill about adding AC to ensure this work doesn't go stale

**Comment by laineymajor** [comment]
Next steps:
- Likely have most of the inventory. We have a lot of files that do not have owners tho... need to compare Rachal and Lindsey's lib directory work. Whatever remains needs to be completed.
- Build Tables:
VfsTeam: id, name, slack_channel_id, github_team_id, vsa_team_id (maybe)
VsaTeam: id, name, slack_channel, Github team name
GithubTeam table: id, name
SlackChannel table: id, name
File: id, file_name, vfs_team_id
(a vfs team could belong to a vsa team, but we may not need to take it this far, but may be a nice to have)
- Then aside from the db tables, we can make sure that Github teams are up to date and codeowners based on the Github teams, rope this into collab cycle and Github Actions or something and :boom:
- Eric's piece from the teams/crews/owners , how does this
