### ISSUE TITLE
[A11y Maintenance Audit]: Notice of Disagreement - June 2023

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#61234]
### Auditor(s)

@joshkimux

### Automated

- [x] Run axe checks on every page or unique state (required)
- [ ] Run WAVE on every page if time allows. WAVE is more visual than axe or axe-coconut, but offers some excellent ways to identify nested headings and HTML5 landmark tags.

### Manual

- [x] Color contrast checks (recommend using whocanuse.com for beyond compliance reports)
- [x] Color blindness checks
- [x] Zoom layouts to 400% and inspect them for readability. If layouts break at 400%, I will start reducing them until they become stable, and log the zoom ratio when things started breaking.
- [x] Keyboard navigation

### Screen Reader

- [ ] Firefox and NVDA
- [x] Chrome and JAWS
- [x] iOS Safari and VoiceOver (Mobile)
- [ ] Safari and Voiceover (Desktop)
- [ ] Chrome and Talkback

### Staging or Production Link

https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/introduction

### Test Users

```bash
1. vetsgov+test236@id.me
2.
3.
```
