### ISSUE TITLE
[Congressional] V10459564 - Issues with setting up ID.me account Due 7/31/2023 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#61244]
## Issue Description
_Constituent is trying to set up electronic payments as required by VA. Their doctor's office biller set up required an ID.me account and online information, but the site would not accept any of their associated phone numbers that were used in the past._

---
## Tasks
- [ ] _Review congressional correspondence
- [ ] Resolve Issue
- [ ] Notify constituent and Congressional Correspondence channel of solution _

## Acceptance Criteria
- [ ] Constituent issue will be resolved or responded to with final answer to issue.
- [ ] Congressional correspondence will receive details of the resolution_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
Veteran is trying to set up electronic payments as required by VA. Their doctor's office biller set up required an ID.me account and online information, but the site would not accept any of their associated phone numbers that were used in the past._

**Comment by summernight18** [comment]
Hi, just following up to see if anyone has reached out the veteran about issue. This is due 7/31. Thank you!

**Comment by clantosswett** [comment]
@ATMiddleton please make sure to include the links that are shared in the slack message or a link to the slack message so that information can be easily found.

**Comment by clantosswett** [comment]
Escalated to ID.me on 7/18. Will wait to hear back from ID.me's initial investigation before contacting the user.

**Comment by clantosswett** [comment]
Followed up with ID.me on 7/24 and was able to provide a phone number where the Veteran can be reached.

**Comment by summernight18** [comment]
Hi, just following up to see if there is an any update. This is due Monday 7/31. 
Thank you,
Vicki

**Comment by summernight18** [comment]
Good Morning, This is due today by 5 PM. Please provide an update.
Thank you,
Vicki

**Comment by clantosswett** [comment]
Hi Vicki,

I just heard the following from ID.me this morning:

Mark W. (VA Escalations Support) 
Jul 31, 2023, 09:36 EDT 
Hi Chante,

I have not been able to get in contact with this member. They have not attempted to access their account either.
 
I will be closing out the ticket I have with them for inactivity.

**Comment by summernight18** [comment]
Hi Chante,
The Congressional Team provided guidance on what we need to include in the response in order to close this item. Is it possible to obtain the following details from ID.me or maybe you have them already...?
- How and when ID.me contacted the Veteran (example, 3-4 times)
- How ID.me reached out (phone, email, etc.). 
- Include when the ticket was opened and when it was closed because the Veteran hasn't attempted to access their account

Thank you,
Vicki

**Comment by summernight18** [comment]
Hi, We need a response on this please. Thank you
