### ISSUE TITLE
[MIGRATE-DATA] Transfer ERIE, PA - "Mission / Vision" statements from legacy to NEW web pages [FE/PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#6124]
## User Story or Problem Statement
As a Veteran Web user, I want to see the VAMC Mission and Vision, so I best know and utilize services in my local medical system.

## Goal
_Move legacy MC website Mission and Vision statements from legacy websites over to new CMS system_

## Objectives or Key Results this is meant to further
- _Increase overall quality experience by moving existing stories into new format_
- _Reduce Click through count by_Highlighting top stories_

## Tasks
_Complete moves from legacy websites to CMS Stories, News Releases, and Events to include:_
- [ ] Find and consolidate "Mission and Vision" From original source.
- [ ] Move content "Exactly" as is and validate accuracy.
- [ ] Pull and modify any images from original pages if required. 
- [ ] Validate and include in DevDepot preview for respective PAO review.

## Acceptance Criteria

* Find and consolidate "Mission and Vision" From original source.
* Move content "Exactly" as is and validate accuracy.
* Pull and modify any images from original pages if required. 
* Validate and include in DevDepot preview for respective PAO review.
