### ISSUE TITLE
[SW] Mobile Prototype (UXPin)

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#61254]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

Continuation of #60485

---
## Tasks
- [x] _Create UXPin prototype for mobile_
- [x] _Add interactions to UXPin prototype_
- [x] _Test prototype_

## Acceptance Criteria
- [x] _UXPin created and linked here_
- [x] _UXPine tested by team_
---

**Comment by HeatherRienks** [comment]
will rollover to S104.

**Comment by josephrlee** [comment]
Here's the link to the protoype: https://preview.uxpin.com/bee98dfe15974e66ea5958c976cb43a2c08ecabc#/pages/163781737

**Comment by HeatherRienks** [comment]
Per SW mtg, just need confirmation from Denise on approval on content for confirmation page.

**Comment by josephrlee** [comment]
Marking this as closed now that we have #61249 to reference and finalize everything.
