### ISSUE TITLE
Design | Profile | Add dependents and letters to Profile | Mock up MVP

### ISSUE THREAD

**Issue by pamela-drouin** [department-of-veterans-affairs/va.gov-team#61261]
## Background

We recently conducted some [discovery research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2023-06-add-dependents-records-discovery/summary.md) around adding dependents and letters to Profile. Our recommendation is to design an MVP of Profile that includes dependents, letters and ID card.

## Tasks
- [ ] Create mock-ups
- [ ] Review w/ team
- [ ] Get content approved
- [ ] Revise mock-ups as needed
- [ ] Let team know ready for research

## Acceptance Criteria
- [ ] [what should the requirements be?]

**Comment by andaleliz** [comment]
We discussed this in refinement today and are going to pause this work.  It feels premature to do mock-ups, and in the time since we have started this work, have received requests to consider other (probably more impactful) additions to profile (next of kin, emergency contact, financial disclosure info) that we need to consider as we prioritize things.

I started to outline some thoughts around what we might include in each section of profile, and outstanding questions, in [this Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687380110061/bc0745295a632374c4493b307de31a3f56939f36?sender=ub868d471cfdb1c56cc0b4512), which we can pick up again if and when we start this work.

Ultimately, next steps for this would be some IA research **NOT** mock-ups.  One thing that stood out to me as I thought through these things is the items that are currently under Records: letters and ID cards. If we lump them together in profile, are we just re-creating the junk drawer that the records section is today?
