### ISSUE TITLE
Identify Content Review Criteria as a Team

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#61273]
## Issue Description
As a Platform Content Team,
we need to discuss what the SME criteria checklist will be for a content review process,
so that we can document it and discuss our recommendations with Platform leadership and SMEs.

Platform website info sheet: https://docs.google.com/spreadsheets/d/1FKam2tLzZ1utfwnREgsjxOIoapHZ3VsX1pXWsX8EcWI/edit?usp=sharing

---
## Tasks
- [x] Schedule 30 min team meeting to discuss the topic
- [x] Document meeting takeaways
Things to consider:

- The Definition of Done documented in the [project epic card](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/47153)
- Our existing "[How to work with us on bigger projects](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2613772343/Working+with+Platform+Content+Team+on+Bigger+Projects)" instructions

## Acceptance Criteria
- [x] We will have criteria for a Content Review Process documented that will be part of our recommendation to Platform leadership and SMEs
