### ISSUE TITLE
Platform Support Slack-bot Update

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#61279]
## Problem Statement
Platform Support Bot is a powerful tool to field support requests, but key improvements are required to meet current usage

## Overview of Needs

- As a user, I need to see topics listed first, so I can easily find my issue and the issue is routed to the right place
- As a Tier 1 support person, I need the drop down reason to be accurate so that I can find the proper solution
- As the Platform Support team, we need to identify at a granular level what tickets we are receiving to create proper solutions to either get to a quicker solution or eliminate those tickets altogether

## Hypothesis or Bet
**If** _we make these changes_ **then**:

- VFS teams will be able to route their tickets to the appropriate place
- The Platform Support Team will receive the information needed to respond in a timely manner both initially and with a solution
- We can ensure that our analytics are granular and help us make better decisions_.

## OKR
_Improved Response times_
_Increased Awareness of Outstanding Issues_
_Improved Analytics_

## Definition of done
The tasks/issues below are completed.

- [x] [Create Support Bot Satisfaction Survey Auto-Responder](https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/65038) 
- [x] [Ability to Close a Slack Ticket and a GitHub Ticket Simultaneously](https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/65224)
- [x] [Documentation Bot Auto Responder Improvements](https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/64414)
- [x] [Reorganization and Addition of Support Bot Fields](https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/65229)

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by jknipes** [comment]
Correct this response as well: [https://dsva.slack.com/archives/D0566F8588M/p1689623023471159](url)

**Comment by alyssagallion** [comment]
@CBonade Are we good to close this epic out or are we waiting on some more details to be completed?

**Comment by alyssagallion** [comment]
All items completed and demoed. Any other support bot work will be in individual tickets. Closing.
