### ISSUE TITLE
Test for Sidekiq enterpirise

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#6128]
## User Story or Problem Statement
It is possible for a developer to 

## Goal
_What outcome(s) do we want to see?_

## Objectives or Key Results this is meant to further
- _Include references to KPIs we intend to impact_
---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
