### ISSUE TITLE
Test for Sidekiq enterprise

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#6129]
## User Story or Problem Statement
We've seen instances of developers [unintentionally](https://github.com/department-of-veterans-affairs/vets-api/pull/3862) and [intentionally ](https://github.com/department-of-veterans-affairs/vets-api/pull/3624) removing Sidekiq Enterprise/Pro from Gemfile.lock. Therefore, we need to have explicit testing for this.  

## Goal
Tests should not pass on CI if  Sidekiq Enterprise/Pro are removed

## Objectives or Key Results this is meant to further
Platform Stability 

## Tasks
- [ ] add  sidekiq-pro/sidekiq-ent to the test group
- [ ] write a test to validate the presence of sidekiq-pro/sidekiq-ent 
- [ ] make the Sidekiq ent key available to CI
## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
Suggestion from https://github.com/department-of-veterans-affairs/vets-api/pull/3926#issuecomment-590490993

```ruby
it 'has sidekiq enterprise in the bundle' do
  expect { Sidekiq::Limiter }.not_to raise_error(NameError)
end
```


I know that this would make the test fail for devs who don't have the key, but make we could add some  tag to the tests to make them easier to skip?

**Comment by annaswims** [comment]
Ideally, a codeowner would catch this sort of change in review, but we've seen an unintentional  Gemfile.lock change slip through after approval, during a merge.

**Comment by omgitsbillryan** [comment]
WRT making the test not fail for local devs who don't have the key:

```ruby
# .rspec-local file
RSpec.configure do |c|
  c.filter_run_excluding requires_sidekiq_pro: true
end

# spec
it 'has sidekiq enterprise in the bundle', requires_sidekiq_pro: true do
  expect { Sidekiq::Limiter }.not_to raise_error(NameError)
end
```

**Comment by johnpaulashenfelter** [comment]
Can't you just `expect { require 'sidekiq/pro' }.to be_true`?

**Comment by erluti** [comment]
Dangerbot could be a good solution for catching this.  It's possible we could make a custom rubocop.

**Comment by alexpappasoddball** [comment]
Closing this one as it is a duplicate.  New work to track the check will be in dangerbot coming soon:  [New ticket](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/18830)
