### ISSUE TITLE
[PM] My VA Claim Status EVSS > Lighthouse: Internal QA on feature

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#61313]
## Background
We need to prep for and execute internal QA on the claims and appeals section of My VA to make sure that the migration to Lighthouse is working properly before launch.

## Tasks
- [x] Create test case document
- [x] Determine test users (we'll want to create the exact same scenarios for multiple test users to compare UX on staging when connected to EVSS and then also Lighthouse)
- [x] Execute tests and report any issues

## Acceptance Criteria
- [x] QA is complete

**Comment by ajakabcin** [comment]
Testing complete - one issue found having to do with formatting of status: #62397
