### ISSUE TITLE
Resolve Issues with Email/PIV Card Access

### ISSUE THREAD

**Issue by gia-lexa** [department-of-veterans-affairs/va.gov-team#61315]
## Issue Description
This ticket tracks the time spent resolving email and PIV card access.
---
## Tasks
- [x] Determine steps necessary to regain email access via the Help Desk
- [x] As a stop-gap,  temporarily regain entry to email via an extension.
- [x] Work with local PIV office to determine when/how to obtain PIV card.

## Acceptance Criteria
- [x] Regain access to email
- [x] Obtain PIV card
- [x] Confirm PIV card works with own card reader.
---
