### ISSUE TITLE
Collaborate with DevOps Cop to Determine An Approved Implementation Plan

### ISSUE THREAD

**Issue by gia-lexa** [department-of-veterans-affairs/va.gov-team#61312]
## Issue Description

Submit one of the two possible Sentry implementations to platform-devops-cop, collaborate with that team to discuss any issues/questions they may have about it, and determine an approved plan.

---
## Tasks
- [x] Submit implementation plan for approval to #devops-cop for approval/feedback.
 

## Acceptance Criteria
- [x] Confirm with devops-cop that Slack/Sentry integration does not pose any security risks as is.
- [x] Confirm a secure plan with devops-cop to ensure Sentry logs do not contain any sensitive data.
- [x] Approval of an implementation plan.
 
---

**Comment by pjhill** [comment]
Thanks for shopping around your plan -- closing this out!
