### ISSUE TITLE
[PM, FE] My VA Claim Status EVSS > Lighthouse: Launch to 75%

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#61321]
## Background
We confirmed our launch readiness - we are ready to launch the updated claim status endpoint connection to Lighthouse on My VA to 75% of users.

## Tasks
- [ ] Dev to flip feature flag on for 75% of users (`my_va_lighthouse_claims`)
- [ ] PM update [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/claim-status-lighthouse-migration/launch-materials/claim-status-lighthouse-migration-release-plan.md) 
- [ ] PM update [project key dates](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/claim-status-lighthouse-migration#key-dates) with launch details
- [ ] Monitor Analytics post launch

## Acceptance Criteria
- [ ] 75% of signed in VA.gov users in Production have access to the updated claim status endpoint connection to Lighthouse

**Comment by ajakabcin** [comment]
Cancelling - we should be able to go from 50% to all users
