### ISSUE TITLE
[PM, FE] My VA Claim Status EVSS > Lighthouse: Launch to all users

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#61322]
## Background
We confirmed our launch readiness - we are ready to launch the updated claim status endpoint connection to Lighthouse on My VA to all users.

## Tasks
- [x] Dev to flip feature flag on for all users (`my_va_lighthouse_claims`)
- [x] PM update [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/claim-status-lighthouse-migration/launch-materials/claim-status-lighthouse-migration-release-plan.md) 
- [x] PM update [project key dates](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/claim-status-lighthouse-migration#key-dates) with launch details
- [x] Monitor Analytics post launch
- [x] PM to update 3 week [metrics](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/claim-status-lighthouse-migration/README.md#measuring-success) 

## Acceptance Criteria
- [x] All signed in VA.gov users in Production have access to the updated claim status endpoint connection to Lighthouse
