### ISSUE TITLE
Make updates throughout life insurance pages for clarity and actionability

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#6132]
## 

---
## Tasks
- [ ] _Lori and Ruth to call followup meeting to go over edits; Anne to take rewriting/edit pass on affected pages and do rounds of review until they are finalized

## Acceptance Criteria
- [ ] _Final pages will be correct, understandable, and actionable to Veterans who want life insurance of various types.
---

- [ ] **Content** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Parity/Legacy/Rewriting work** Requested by VBA 

TBD list of page URLs affected sections to add to when Ruth finishes her review.

Note from @lunascoop   - related redirect tickets:
We have a life insurance rewriting epic (Ticket #18105). Based on a prelim. view, some of the work might take care of ticket #19032 and #18843.

**Comment by AnneHurley** [comment]
Awaiting followup call and information from stakeholders.

**Comment by AnneHurley** [comment]
@jenniferlee-dsva  and @lunascoop  Should we reach out to the life insurance stakeholders to see what new information might be coming, and when? It's been a week since our meeting.
@AkucherGCIO  FYSA

**Comment by jenniferlee-dsva** [comment]
@AnneHurley - there is no other follow up work for Life Insurance (from Lori Hamilton) that I know of. The updates we needed to have (already) made were:
- update the rates
- update the form link

She sent these things in an email to us (you're on it) - and I'm pretty sure you already made them, but please take a look and confirm. Will forward to you and @AkucherGCIO .

**Comment by jenniferlee-dsva** [comment]
Per email comment - If we have open bandwidth, please feel free to follow up @AnneHurley. However, if we still have redirect tickets that are still open and that need pre-vetting, that would be the higher priority for our team.Per 2020 deck, Legacy/Parity redirects are a top priority to complete in Q1 (I guess now Q2 - but let's def complete in Q2). :-) 
@AkucherGCIO fysa

**Comment by AnneHurley** [comment]
https://www.va.gov/life-insurance/options-eligibility/
https://www.va.gov/life-insurance/options-eligibility/sgli/
www.va.gov/life-insurance/options-eligibility/fsgli/
https://www.va.gov/life-insurance/options-eligibility/tsgli/
https://www.va.gov/life-insurance/options-eligibility/s-dvi/
www.va.gov/life-insurance/options-eligibility/vmli/

If updating these pages is blocking redirects, please check in with them but I’m also inclined to not proactively move this along as we have plenty of other higher priority work – like getting redirect tickets prevetted for Mikki, so we can finish implementing. 

Rates info if needed:
[Life insurance rates updates]
(https://app.zenhub.com/files/133843125/8e8a945a-6eb6-4126-aa07-255ce679d204/download)

**Comment by DanielleThierryUSDSVA** [comment]
**Note:*** I am moving this issue into the Life insurance rewriting epic. We'll be re-kicking off that work and I want to make sure we're starting off in full partnership with SMEs, so will connect with SMEs re: any requests they may have on other pages within this hub as part of that kickoff.
