### ISSUE TITLE
Finalize Implementation for Storing Jobs in Retries for KMS Key Rotation

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#61332]
## Issue Description

As part of our KMS key rotation automation, we need to finalize how we store jobs that are in retries so their associated records can be skipped when grabbing new records to batch to Sidekiq.

## Tasks

- [x] Review the current method for storing jobs in retries.
- [x] Evaluate the effectiveness and efficiency of storing a hash in memory.
- [x] Implement the finalized version for storing jobs in retries, ensuring their associated records can be skipped.

## Acceptance Criteria

- [x] The final implementation for storing jobs in retries is in place, skipping the associated records when grabbing new records to batch to Sidekiq.

**Comment by holdenhinkle** [comment]
This ticket is complete. I'll add notes and close it out tomorrow morning.

**Comment by holdenhinkle** [comment]
We can't query the Sidekiq Retries queue, but we can grab all the jobs in it, iterate through them, and select that jobs based on the class the job belongs to. So we simply look for `KmsKeyRotation::UpdateRecordsJob` jobs, and grab the `model` and the `id` from the job's `args`. When we select new records that need to be updated, we can check to see if the record is in the retries queue by comparing the name of the `model` the record belongs to and its `id` to the jobs in the retries queue. We skip it if it's already in the queue.

We only need to store this retries lookup table momentarily, while we grab new records from the db; it can easily be rebuilt when necessary so it does not need to live for the life of this task like I initially thought it would.
