### ISSUE TITLE
Test KMS Key Rotation on Dev or Staging

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#61334]
## Issue Description

To ensure the effectiveness of our KMS key rotation automation, we need to test it in a controlled environment such as Dev or Staging.

## Tasks

- [ ] Prepare the Dev or Staging environment for testing.
- [ ] Run the KMS key rotation process in the selected environment.
- [ ] Document the results and identify any issues or areas of improvement.

## Acceptance Criteria

- [ ] The KMS key rotation process has been successfully tested in a controlled environment and any issues have been documented.

**Comment by holdenhinkle** [comment]
Holden will work on this with @LindseySaari when he moves to TT1

**Comment by ryan-mcneil** [comment]
Dev ( 38,697 total records):
```
irb(main):001:0> ApplicationRecord.descendants_using_encryption.map(&:name).map(&:constantize).reduce({}) { |hash, model| hash[model.name] 
= model.count; hash }
=> 
{"DecisionReviewEvidenceAttachment"=>0,
 "HCAAttachment"=>39,
 "SupportingEvidenceAttachment"=>15,
 "Form1010cg::Attachment"=>0,
 "Preneeds::PreneedAttachment"=>0,
 "AppealSubmission"=>0,
 "SavedClaim::Burial"=>8305,
 "SavedClaim::DependencyClaim"=>44,
 "SavedClaim::DependencyVerificationClaim"=>0,
 "SavedClaim::EducationCareerCounselingClaim"=>0,
 "SavedClaim::Pension"=>3434,
 "SavedClaim::Ask"=>0,
 "SavedClaim::CaregiversAssistanceClaim"=>1,
 "SavedClaim::CoeClaim"=>0,
 "SavedClaim::DisabilityCompensation::Form526AllClaim"=>55,
 "SavedClaim::DisabilityCompensation::Form526IncreaseOnly"=>0,
 "SavedClaim::EducationBenefits::VA0993"=>0,
 "SavedClaim::EducationBenefits::VA0994"=>2,
 "SavedClaim::EducationBenefits::VA10203"=>5,
 "SavedClaim::EducationBenefits::VA1990"=>0,
 "SavedClaim::EducationBenefits::VA1990e"=>0,
 "SavedClaim::EducationBenefits::VA1990n"=>0,
 "SavedClaim::EducationBenefits::VA1990s"=>0,
 "SavedClaim::EducationBenefits::VA1995"=>0,
 "SavedClaim::EducationBenefits::VA5490"=>0,
 "SavedClaim::EducationBenefits::VA5495"=>0,
 "SavedClaim::VeteranReadinessEmploymentClaim"=>1,
 "EducationStemAutomatedDecision"=>0,
 "Form1095B"=>82,
 "Form526Submission"=>55,
 "Form5655Submission"=>0,
 "GibsNotFoundUser"=>5,
 "InProgressForm"=>10,
 "PersistentAttachments::DependencyClaim"=>0,
 "PersistentAttachments::LgyClaim"=>0,
 "PersistentAttachments::PensionBurial"=>11855,
 "UserCredentialEmail"=>172,
 "AsyncTransaction::VAProfile::AddressTransaction"=>0,
 "AsyncTransaction::VAProfile::EmailTransaction"=>0,
 "AsyncTransaction::VAProfile::InitializePersonTransaction"=>29,
 "AsyncTransaction::VAProfile::PermissionTransaction"=>0,
 "AsyncTransaction::VAProfile::TelephoneTransaction"=>1,
 "AsyncTransaction::Vet360::AddressTransaction"=>0,
 "AsyncTransaction::Vet360::EmailTransaction"=>0,
 "AsyncTransaction::Vet360::InitializePersonTransaction"=>2,
 "AsyncTransaction::Vet360::PermissionTransaction"=>0,
 "AsyncTransaction::Vet360::TelephoneTransaction"=>0,
 "SignIn::OAuthSession"=>1,
 "Veteran::Service::Representative"=>14236,
 "HealthQuest::QuestionnaireResponse"=>0,
 "DebtsApi::V0::Form5655Submission"=>0,
 "CovidVaccine::V0::ExpandedRegistrationSubmission"=>0,
 "CovidVaccine::V0::RegistrationSubmission"=>0,
 "ClaimsApi::AutoEstablishedClaim"=>217,
 "ClaimsApi::EvidenceWaiverSubmission"=>0,
 "ClaimsApi::PowerOfAttorney"=>86,
 "ClaimsApi::SupportingDocument"=>29,
 "AppealsApi::HigherLevelReview"=>8,
 "AppealsApi::NoticeOfDisagreement"=>6,
 "AppealsApi::SupplementalClaim"=>2}
```

Staging (1,172,289 total records)
```
{"DecisionReviewEvidenceAttachment"=>183,
 "HCAAttachment"=>138471,
 "SupportingEvidenceAttachment"=>4726,
 "Form1010cg::Attachment"=>0,
 "Preneeds::PreneedAttachment"=>72,
 "AppealSubmission"=>235,
 "SavedClaim::Burial"=>35,
 "SavedClaim::DependencyClaim"=>16079,
 "SavedClaim::DependencyVerificationClaim"=>5,
 "SavedClaim::EducationCareerCounselingClaim"=>5,
 "SavedClaim::Pension"=>28,
 "SavedClaim::Ask"=>0,
 "SavedClaim::CaregiversAssistanceClaim"=>5,
 "SavedClaim::CoeClaim"=>5109,
 "SavedClaim::EducationBenefits::VA0993"=>28,
 "SavedClaim::EducationBenefits::VA0994"=>3381,
 "SavedClaim::EducationBenefits::VA10203"=>130,
 "SavedClaim::EducationBenefits::VA1990"=>71,
 "SavedClaim::EducationBenefits::VA1990e"=>14,
 "SavedClaim::EducationBenefits::VA1990n"=>14,
 "SavedClaim::EducationBenefits::VA1990s"=>0,
 "SavedClaim::EducationBenefits::VA1995"=>74,
 "SavedClaim::EducationBenefits::VA5490"=>21,
 "SavedClaim::EducationBenefits::VA5495"=>21,
 "SavedClaim::VeteranReadinessEmploymentClaim"=>1419,
 "EducationStemAutomatedDecision"=>22,
 "Form1095B"=>0,
 "Form526Submission"=>1008,
 "Form5655Submission"=>111,
 "GibsNotFoundUser"=>12,
 "InProgressForm"=>212,
 "PersistentAttachments::DependencyClaim"=>70,
 "PersistentAttachments::LgyClaim"=>2335,
 "PersistentAttachments::PensionBurial"=>233,
 "UserCredentialEmail"=>1743,
 "AsyncTransaction::VAProfile::AddressTransaction"=>448,
 "AsyncTransaction::VAProfile::EmailTransaction"=>157,
 "AsyncTransaction::VAProfile::InitializePersonTransaction"=>231,
 "AsyncTransaction::VAProfile::PermissionTransaction"=>0,
 "AsyncTransaction::VAProfile::TelephoneTransaction"=>378,
 "AsyncTransaction::Vet360::AddressTransaction"=>64,
 "AsyncTransaction::Vet360::EmailTransaction"=>1137,
 "AsyncTransaction::Vet360::InitializePersonTransaction"=>16,
 "AsyncTransaction::Vet360::PermissionTransaction"=>0,
 "AsyncTransaction::Vet360::TelephoneTransaction"=>621,
 "SignIn::OAuthSession"=>492,
 "Veteran::Service::Representative"=>14237,
 "HealthQuest::QuestionnaireResponse"=>59,
 "DebtsApi::V0::Form5655Submission"=>111,
 "CovidVaccine::V0::ExpandedRegistrationSubmission"=>30,
 "CovidVaccine::V0::RegistrationSubmission"=>976212,
 "ClaimsApi::AutoEstablishedClaim"=>567,
 "ClaimsApi::EvidenceWaiverSubmission"=>266,
 "ClaimsApi::PowerOfAttorney"=>113,
 "ClaimsApi::SupportingDocument"=>2,
 "AppealsApi::HigherLevelReview"=>32,
 "AppealsApi::NoticeOfDisagreement"=>36,
 "AppealsApi::SupplementalClaim"=>66}
```

**Comment by JoeTice** [comment]
SPRINT 37 UPDATE - In Progress, this work is nearly completed but a small tweak is needed, will be finished in SPRINT 38
