### ISSUE TITLE
Create Plan to Safely Run KMS Key Rotation against Production Database

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#61336]
## Issue Description

In collaboration with DevOps and @LindseySaari, we need to create a plan to safely run the KMS key rotation against the production database.

## Tasks

- [ ] Meet with DevOps and @LindseySaari to discuss the best approach for running the KMS key rotation in production.
- [ ] Draft a plan detailing how the KMS key rotation will be safely run in production.

## Acceptance Criteria

- [ ] A detailed plan is in place, ready to be executed to run the KMS key rotation safely against the production database.

**Comment by holdenhinkle** [comment]
Holden will work on this with @LindseySaari when he moves to TT1

**Comment by ryan-mcneil** [comment]
Total encrypted records in Production: 
```irb(main):001:0> ApplicationRecord.descendants_using_encryption.map(&:name).map(&:constantize).reduce({}) { |hash, model| hash[model.name] 
= model.count; hash }
=> 
{"DecisionReviewEvidenceAttachment"=>112350,
 "HCAAttachment"=>77312,
 "SupportingEvidenceAttachment"=>3720426,
 "Form1010cg::Attachment"=>207,
 "Preneeds::PreneedAttachment"=>5566,
 "AppealSubmission"=>183940,
 "SavedClaim::Burial"=>3577,
 "SavedClaim::DependencyClaim"=>579038,
 "SavedClaim::DependencyVerificationClaim"=>0,
 "SavedClaim::EducationCareerCounselingClaim"=>1502,
 "SavedClaim::Pension"=>2298,
 "SavedClaim::Ask"=>0,
 "SavedClaim::CaregiversAssistanceClaim"=>3,
 "SavedClaim::CoeClaim"=>47489,
 "SavedClaim::DisabilityCompensation::Form526AllClaim"=>2419454,
 "SavedClaim::DisabilityCompensation::Form526IncreaseOnly"=>7869,
 "SavedClaim::EducationBenefits::VA0993"=>13,
 "SavedClaim::EducationBenefits::VA0994"=>14014,
 "SavedClaim::EducationBenefits::VA10203"=>11555,
 "SavedClaim::EducationBenefits::VA1990"=>28045,
 "SavedClaim::EducationBenefits::VA1990e"=>2160,
 "SavedClaim::EducationBenefits::VA1990n"=>0,
 "SavedClaim::EducationBenefits::VA1990s"=>0,
 "SavedClaim::EducationBenefits::VA1995"=>29045,
 "SavedClaim::EducationBenefits::VA5490"=>31871,
 "SavedClaim::EducationBenefits::VA5495"=>6851,
 "SavedClaim::VeteranReadinessEmploymentClaim"=>323510,
 "EducationStemAutomatedDecision"=>10778,
 "Form1095B"=>13890988,
 "Form526Submission"=>2359864,
 "Form5655Submission"=>29166,
 "GibsNotFoundUser"=>4972,
 "InProgressForm"=>428375,
 "PersistentAttachments::DependencyClaim"=>78472,
 "PersistentAttachments::LgyClaim"=>56057,
 "PersistentAttachments::PensionBurial"=>40693,
 "UserCredentialEmail"=>6302421,
 "AsyncTransaction::VAProfile::AddressTransaction"=>178506,
 "AsyncTransaction::VAProfile::EmailTransaction"=>36010,
 "AsyncTransaction::VAProfile::InitializePersonTransaction"=>51761,
 "AsyncTransaction::VAProfile::PermissionTransaction"=>0,
 "AsyncTransaction::VAProfile::TelephoneTransaction"=>91438,
 "AsyncTransaction::Vet360::AddressTransaction"=>1453,
 "AsyncTransaction::Vet360::EmailTransaction"=>1524,
 "AsyncTransaction::Vet360::InitializePersonTransaction"=>7412,
 "AsyncTransaction::Vet360::PermissionTransaction"=>0,
 "AsyncTransaction::Vet360::TelephoneTransaction"=>4382,
 "SignIn::OAuthSession"=>2320156,
 "Veteran::Service::Representative"=>14236,
 "HealthQuest::QuestionnaireResponse"=>2,
 "DebtsApi::V0::Form5655Submission"=>29166,
 "CovidVaccine::V0::ExpandedRegistrationSubmission"=>62094,
 "CovidVaccine::V0::RegistrationSubmission"=>1020960,
 "ClaimsApi::AutoEstablishedClaim"=>130331,
 "ClaimsApi::EvidenceWaiverSubmission"=>122,
 "ClaimsApi::PowerOfAttorney"=>11854,
 "ClaimsApi::SupportingDocument"=>815,
 "AppealsApi::HigherLevelReview"=>118111,
 "AppealsApi::NoticeOfDisagreement"=>18455,
 "AppealsApi::SupplementalClaim"=>49115}
```

**Comment by ryan-mcneil** [comment]
Models where encrypted_kms_key` = `nil` (and # of records/total records):
* `AppealsApi::NoticeOfDisagreement` - 8/18544
* `AppealsApi::HigherLevelReview` - 25855/118465
* `AppealSubmission` - 116722/184956
* `CovidVaccine::V0::ExpandedRegistrationSubmission` - 1/62094
* `SignIn::OAuthSession` - 1521278/2279889
* `Veteran::Service::Representative` - 14236/14236

### More info:

### **AppealsApi::NoticeOfDisagreement - 8/18544**
* nil values between 6/3/2021 - 6/22/2021, while encrypted records are between 4/27/22-10/2/23 (there don't seems to be records created in the 10 months between
* Perhaps the 8 records were tests prior to release?
* NOTE - most records (16927) with the encrypted_kms_key, have nil values for encrypted values (form_data and auth_headers) ***kills theory that nil ciphertext fields get a nil key***

### **AppealsApi::HigherLevelReview - 25855/118465**
* first record from 11-10-20 IS ENCRYPTED, but first record with nil key is 1/20/21
* nil keys between 1/20/21 - 10/21/21
* 
```
> AppealsApi::HigherLevelReview.where('created_at > ? and created_at <= ?','2021-01-20', '2021-10-21').order(:created_at).count
=> 25853

> AppealsApi::HigherLevelReview.where('created_at > ? and created_at <= ?','2021-01-20', '2021-10-21').where(encrypted_kms_key: nil).order(:created_at).count 
=> 25851
```
* the two outliers were created on 6/12/21, about 30 min apart (but updated 12/17/21)
* no obvious pattern with updated_at

### **AppealSubmission - 116722/184956**
* we are CURRENTLY creating data with nil keys
* All nil keys are records with nil `upload_metadata` (supports OG theory)

### **CovidVaccine::V0::ExpandedRegistrationSubmission - 1/62094**
* the one record throws a record when trying to view in ActiveRecord:
```
/usr/local/bundle/cache/ruby/3.2.0/gems/lockbox-1.3.0/lib/lockbox/encryptor.rb:42:in `rescue in block in decrypt': Decryption failed (Lockbox::DecryptionError)
/usr/local/bundle/cache/ruby/3.2.0/gems/lockbox-1.3.0/lib/lockbox/aes_gcm.rb:76:in `fail_decryption': Decryption failed (Lockbox::DecryptionError)
/usr/local/bundle/cache/ruby/3.2.0/gems/lockbox-1.3.0/lib/lockbox/aes_gcm.rb:48:in `final': OpenSSL::Cipher::CipherError
```

### **SignIn::OAuthSession - 1521278/2279889**
* Encryption was implemented on 9/18, so all records before that day have nil values. These only have a life of 90 days, so in 2 months, all of the unencrypted records will be gone

### **Veteran::Service::Representative - 14236/14236**
* Records in Prod are the same as in Dev (potential "Master" data list)
* In all records, the encrypted fields (`dob` and `ssn`) are all null. So perhaps there isn't a key because there's no data to encrypt

**Comment by JoeTice** [comment]
SPRINT 37 UPDATE - In Progress, this work is nearly completed but a small tweak is needed, will be finished in SPRINT 38

**Comment by ryan-mcneil** [comment]
The plan for running in Prod evolved as we iterated on the job to perform the work. We configured it so that the following could be done:
* We have it scheduled (using cron/Sidekiq period jobs), so that it runs nightly, grabbing some predetermined amount of records, and rotating them during off-peak hours. 
* This way, it would rotate some portion of the records every night. The number of days would depend on how efficient we could make the job, and will increase every year as the number of encrypted records in the DB increases.
* It would run nightly, but after the master key gets rotated (Oct 11) and the job manages to catch up, it would find zero records to be encrypted for the rest of the year until it gets rotated again.
* This "predetermined amount of records" is set with a constant, default value. We went in with the intention of setting it to a lower value, then increasing it once we understood how fast it was going.
* We added the ability to override the default, so that we could begin by rotating as little as one record, to confirm things were working as expected before ramping up the desired capacity.
