### ISSUE TITLE
Run KMS Key Rotation Job in Production

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#61337]
## Issue Description

With a safe execution plan in place, we need to run our KMS key rotation rake job in production.

## Tasks

- [ ] Collaborate with DevOps and @LindseySaari to execute the KMS key rotation in the production environment.
- [ ] Monitor the process and note any issues that arise.

## Acceptance Criteria

- [ ] The KMS key rotation script has been successfully run against the production database, with all issues noted and addressed.

**Comment by holdenhinkle** [comment]
Holden will work on this with @LindseySaari  when he moves to TT1

**Comment by ryan-mcneil** [comment]
As of 10/20, we've successfully manually rotated about 1 million of the ~33m encrypted records. We'll push an update on Monday to allow the remainder to get picked up based on the cron/job configuration.

**Comment by ryan-mcneil** [comment]
As of 10/24, around 20 million (/~33 mil) have been rotated. We've deployed an update to the CRON job, setting it run 15 million records each night. As of our last production test yesterday, records were rotating at a rate of about 12 million / hour, so we'd expect the job to finish in around 75 min. I'll post an update if we find something different. We'll consider this closed unless something else comes up
