### ISSUE TITLE
Write Tests for KMS Key Rotation

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#61333]
## Issue Description

To ensure the reliability and accuracy of our KMS key rotation automation, we need to write comprehensive tests.

PR - https://github.com/department-of-veterans-affairs/vets-api/pull/11117

## Tasks

- [x] Identify the areas of the KMS key rotation process that require testing.
- [x] Write unit tests for each identified area.
- [x] Ensure tests cover all possible edge cases.

## Acceptance Criteria

- [x] Comprehensive tests for the KMS key rotation process are written and passing.

**Comment by holdenhinkle** [comment]
I created seed data for the following Models:

- SavedClaim::Burial(id: integer, created_at: datetime, updated_at: datetime, form_id: string, guid: uuid, type: string, form_ciphertext: text, encrypted_kms_key: text, verified_decryptable_at: date, encryption_updated_at: datetime, form: string)
- Form1095B(id: uuid, veteran_icn: string, tax_year: integer, form_data_ciphertext: jsonb, encrypted_kms_key: text, created_at: datetime, updated_at: datetime, encryption_updated_at: datetime, form_data: string)
- AppealsApi::SupplementalClaim(id: uuid, status: string, code: string, detail: string, source: string, pdf_version: string, api_version: string, created_at: datetime, updated_at: datetime, form_data_ciphertext: text, auth_headers_ciphertext: text, encrypted_kms_key: text, evidence_submission_indicated: boolean, verified_decryptable_at: date, veteran_icn: string, metadata: jsonb, encryption_updated_at: datetime, auth_headers: string, form_data: string)

**Comment by holdenhinkle** [comment]
I created seed data for 3 tables that have encrypted fields, and created thousands of new records for each of the 3 tables.

My script successfully updated all the fields in all the tables that need to be updated in batches of up to 1000. When it appeared to be finished I ran the rake task again and no records were picked up that needed to be updated, which is correct. I then created only 11 new records in one of the 3 tables, ran the rake task again, and the task batched only the 11 new records to be updated, which is correct.

I'll write unit tests tomorrow.

**Comment by holdenhinkle** [comment]
I think there's a bug (in Sidekiq?) that calls the `on_complete` `batch` callback sometimes when it shouldn't. I noticed that there are sometimes multiple batches in the queue, when there should only be one batch in the queue at the same time (unless there's a batch that has failures). This means, that there could be jobs in more than one batch that will update the same record. I quickly looked into this, and it seems there is not a way to get a list of the jobs in a batch, we can only get the totals for a batch (pending, completed, failed, etc.). I'll look into this further tomorrow.

**Comment by holdenhinkle** [comment]
Actually, I need to write tests for a couple more things...
1. That the `updated_at` field isn't updated when the key is rotated
2. That the key is rotated

**Comment by holdenhinkle** [comment]
Done.
