### ISSUE TITLE
Finalize Sidekiq Batch Callbacks Implementation for KMS Key Rotation

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#61331]
## Issue Description

We are in the process of implementing an annual KMS key rotation and need to finalize how we use Sidekiq Batch callbacks so that our script continues to loop until all records are updated.

## Tasks

- [ ] Review the current implementation of Sidekiq Batch callbacks.
- [ ] Identify areas for improvement or necessary adjustments in the current implementation.
- [ ] Implement the finalized version of Sidekiq Batch callbacks to ensure the script loops until all records are updated.

## Acceptance Criteria

- [ ] The final implementation of Sidekiq Batch callbacks is in place and verified, ensuring the script loops until all records are updated.

**Comment by holdenhinkle** [comment]
What the `status` object looks like in `Batch` callback:

```
[1] pry(#<KmsKeyRotation::SidekiqBatchCallbacks>)> status
=> #<Sidekiq::Batch::Status:0x000000011a4860f0
13:12:57 job.1       |  @bid="t_dvBLJjmke3AA",
13:12:57 job.1       |  @callbacks=
13:12:57 job.1       |   {"success"=>[{"KmsKeyRotation::SidekiqBatchCallbacks"=>{}}],
13:12:57 job.1       |    "complete"=>[{"KmsKeyRotation::SidekiqBatchCallbacks"=>{}}],
13:12:57 job.1       |    "death"=>[{"KmsKeyRotation::SidekiqBatchCallbacks"=>{}}]},
13:12:57 job.1       |  @completed=0,
13:12:57 job.1       |  @failures=0,
13:12:57 job.1       |  @pending=0,
13:12:57 job.1       |  @props=
13:12:57 job.1       |   {"pending"=>"0",
13:12:57 job.1       |    "created_at"=>"1688414575.541444",
13:12:57 job.1       |    "description"=>"KMS Key Rotation t_dvBLJjmke3AA",
13:12:57 job.1       |    "total"=>"186",
13:12:57 job.1       |    "kids"=>"0",
13:12:57 job.1       |    "callbacks"=>
13:12:57 job.1       |     "{\"success\":[{\"KmsKeyRotation::SidekiqBatchCallbacks\":{}}],\"complete\":[{\"KmsKeyRotation::SidekiqBatchCallbacks\":{}}],\"death\":[{\"KmsKeyRotation::SidekiqBatchCallbacks\":{}}]}"},
13:12:57 job.1       |  @total=186>
```

**Comment by holdenhinkle** [comment]
`on_success` is called before `on_complete`.

**Comment by holdenhinkle** [comment]
This ticket is complete. I'll add notes and close it out tomorrow morning.

**Comment by holdenhinkle** [comment]
We only need to use the `on_complete` callback. Calling `KmsKeyRotation::Batcher.new.batch_records` within it provides us with the loop needed to cycle through all encrypted records.
