### ISSUE TITLE
[Frontend] Select Supplies Order Page 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#6134]
## User Story or Problem Statement

As a  veteran , I need to see what supplies I am eligible and not eligible to reorder so I can select what I wish to order. The reorder items, eligible Y/N flag and eligibility date are contained in the Reorder API. 

## Goal
Provide Veterans clear information of what they can reorder and if they cannot reorder provide date that they can

---
## Tasks
- [ ] _Create page per design for selecting supplies to reorder 
- [ ] _Display information from Reorder API for an authenticated veteran with item description, description of device the item is for, eligibility status, if not eligible, eligibility date, quantity, last order date

## Acceptance Criteria
- [ ] _For a given test user who is authenticated, the correct items and eligibility status will be returned and rendered from API . the user will be able to click to reorder items and UI of 'added to order' will be displayed. 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
