### ISSUE TITLE
Ongoing review of FSR Medallia Satisfaction Survey data

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#61351]
## Issue Description

We are establishing a baseline of satisfaction of the FSR form by assessing Medallia satisfaction data on an ongoing basis. 

Monthly reporting on Medallia satisfaction data. 
Monthly reports can be found in this [folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/combined_fsr/research/medallia_reports)

This is a continuation of ticket #56464.

October 2023 data: ✔
November 2023 data: ✔
December 2023 data: ✔

---
## Tasks
_What work is necessary for this story to be completed?_
- [x] _Request monthly data_
- [x] _Review data reports_
- [x] _Extract meaningful data to include in a report_
- [x] _Document on Github_

## Acceptance Criteria
_What will be created or happen as a result of this story?_
- [x] _Request data reports_
- [x] _Review data reports_
- [x] _Extract meaningful data to include in a report_
- [x] _Report on Github_

**Comment by charlottecesana** [comment]
Please note: the Medallia reports folder has been created in Github and the first report has been posted. 
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/combined_fsr/research/medallia_reports

@denisecoveyduc @HeatherRienks @Tom-Davis

**Comment by HeatherRienks** [comment]
we will create a monthly ticket moving forward.
