### ISSUE TITLE
Design | Profile | Update user flows | Refine user flow for notification settings

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#61356]
## Background

The team determined that the user flow approach piloted in the [notification settings mobile Sketch page](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/p/B5792AF8-87F2-496D-AE7A-DAD1448A6018/canvas) (review MHV on VA.gov section) is helpful across all practice areas, and an improvement over the current high level user flows.

Let's clean up that page and decide on some patterns (e.g. should "no" pathways always go down, "yes" pathways always go right? Should we ever duplicate a screen or always point to a single source of truth) before we apply this to other sections of profile.

## Tasks
- [x] Review flow for opportunities to improve consistency (e.g.  different states are side by side, not up and down, "no" pathways always go down, "yes" pathways always go right or something like that) and clarity
- [x] Review for opportunities to reduce repetition - for example, in an expanded additional info screen, do we need to repeat the whole screen or can we just show the expanded accordion on it's own artboard?
- [x] Review with team and incorporate any feedback.  Make sure to discuss if there is any reason to keep the original [high-level user flow](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/p/7D8690AF-3410-485F-8754-7F5E377807CC/canvas) page.
- [x] If the user flow page got canned, update any use case docs that link to it.

## Acceptance Criteria
- [x] Team is aligned on flow pattern and we can apply to other parts of profile

**Comment by andaleliz** [comment]
@mtcA6 this is going to carry over in the next sprint - 3 points left to do.

**Comment by andaleliz** [comment]
The team is aligned! We decided to delete the high level user flows, so we can do that in the other sketch files we make flows for.  

I also submitted a [design system ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62365) to hopefully get our pattern adopted, so we don't have to maintain separate annotations.
