### ISSUE TITLE
Design | Profile | Update user flows | Map user flow for contact information

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#61358]
## Background
The team determined that the user flow approach piloted in the [notification settings mobile Sketch page](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/p/B5792AF8-87F2-496D-AE7A-DAD1448A6018/canvas) (review MHV on VA.gov section) is helpful across all practice areas, and an improvement over the current high level user flows.

In #61356 we refined that approach and are ready to apply it to other parts of profile. Let's apply this to the mobile pages only, not desktop. It's duplicative to do it in both places, and we are a mobile-first organization.

## Tasks

- [x] Map user flow for contact information, on the mobile page
- [x] Simplify any art boards that are states, so they contain only the state and we don't have to continue maintaining content that is beside the point, and already exists on other art boards.
- [x] Solicit async feedback/review from team. 
- [x] Update any use case docs that link to user flows, especially if we decided to remove the high level user flow page (unknown at the time this ticket is written)

**Comment by andaleliz** [comment]
@mtcA6 I'm adding this to sprint 17 but likely will carry over into sprint 18 too.

**Comment by andaleliz** [comment]
@adamwhitlock1 do we have separate alerts for missing unit number and bad unit number?

In Sketch, I have mock-ups for two different alerts ([missing](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/WKmL09n), [bad](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/QbJeZR7))

However, it looks like in our use case docs, [we combined the bad unit number w/ the address not found alert](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/use-cases/address-validation.md#address-andor-unit-number-cant-be-confirmed-with-us-postal-service-usps-and-a-suggestion-is-not-found).

I'm not sure which one is aligned to what we have in the code. Could you please check and lmk when you have a chance? Thanks!

**Comment by andaleliz** [comment]
@mtcA6 FYI: I'm carrying over 2 points for this into sprint 18

**Comment by adamwhitlock1** [comment]
Looked into these alerts @andaleliz. Here is what we have in the code:

**Bad unit number** 
 > U.S. Postal Service records show that there may be a problem with the
        unit number for this address. Confirm that you want us to use this
        address as you entered it. Or, cancel to edit the address.

**Missing Unit**
> U.S. Postal Service records show this address may need a unit number.
        Confirm that you want us to use this address as you entered it. Or, go
        back to edit and add a unit number.

Then we have the regular alerts for if there is a suggestion or no suggestions that come back from the validation service:

**Suggestion**
> Tell us which of these addresses you’d like us to use.

**No suggestion**
> We can’t confirm the address you entered with the U.S. Postal Service.
        Confirm that you want us to use this address as you entered it. Or, go
        back to edit it.

**Comment by andaleliz** [comment]
Thanks @adamwhitlock1, I've updated the use case docs to reflect that and will be sure Sketch aligns accordingly.

**Comment by andaleliz** [comment]
I've completed the updates - going to review with Pam and Angela on Tuesday, and then the rest of the team later in the day. Moving to validate until then.

**Comment by andaleliz** [comment]
User flow is updated with the feedback received from the team (not including changes to desktop) and the use case docs have been updated.

**Comment by mtcA6** [comment]
Thanks @andaleliz I've loved watching the progression of all of these.
