### ISSUE TITLE
[ENGINEER] Clone-copy of Pittsburgh to BUTLER, PA - "DAV-VANS- Transportation" information from legacy to NEW web pages [Engineer]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#6135]
## User Story or Problem Statement
As a Veteran Web user, I want to see the VAMC DAV-VAN/Transportation page, so I best know and utilize transportation services in my local travel to the VA medical system.

## Goal
_Move legacy MC website DAV VAN information from legacy websites over to new CMS system_

## Objectives or Key Results this is meant to further
- _Increase overall quality experience by moving existing stories into new format_
- _Reduce Click through count by_Highlighting top stories_

## Resources - Tools - Documentation
[Pittsburgh example of DAV Van Information](https://www.va.gov/pittsburgh-health-care/dav-vans-transportation-for-veterans/)

## Tasks
_Complete moves from legacy websites to CMS DAV-VAN Detail page to include:_
- [ ] Find and copy "DAV VAN webPage" From original source.
- [ ] Move content "Exactly" as is and validate accuracy.
- [ ] Pull and modify any images from original pages if required. 
- [ ] Validate and include in DevDepot preview for respective PAO review.

## Acceptance Criteria

* Find and copy "DAV VAN webPage" From original source.
* Move content "Exactly" as is and validate accuracy.
* Pull and modify any images from original pages if required. 
* Validate and include in DevDepot preview for respective PAO review.
