### ISSUE TITLE
Design | Profile | Update user flows | Map user flow for direct deposit

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#61357]
## Background
The team determined that the user flow approach piloted in the [notification settings mobile Sketch page](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/p/B5792AF8-87F2-496D-AE7A-DAD1448A6018/canvas) (review MHV on VA.gov section) is helpful across all practice areas, and an improvement over the current high level user flows.

In #61356 we refined that approach and are ready to apply it to other parts of profile. Let's apply this to the mobile pages only, not desktop. It's duplicative to do it in both places, and we are a mobile-first organization.

## Tasks

- [x] Map [user flow](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/p/837E4048-F554-48CA-B877-2C1007AB5D43/canvas) for direct deposit, on the mobile page
- [x] Solicit async feedback/review from team. 
- [x] Update any use case docs that link to user flows, especially if we decided to remove the high level user flow page (unknown at the time this ticket is written)

**Comment by mtcA6** [comment]
do we have separate files/flows for DD for C&P vs EDU?

**Comment by andaleliz** [comment]
@mtcA6 no, everything is in one Sketch file, linked at the [bottom of the product outline](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/direct-deposit/README.md#design-and-ux)

**Comment by andaleliz** [comment]
Hi @adamwhitlock1 @tpharrison @pamela-drouin @mtcA6 @Samara-Strauss  - I've completed mapping out [the flow for direct deposit](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/p/837E4048-F554-48CA-B877-2C1007AB5D43/canvas) and would love to get your review to be sure I haven't missed anything. This is one of the more complex products in profile with a lot of alerts, and states repeated in both sections. I attempted to simplify it, but hopefully I didn't go too far.  Thanks in advance for taking a look!

**Comment by pamela-drouin** [comment]
I read through it pretty quickly, and the flow makes sense to me! 

Only thing that stood out to me is that these two screens (`Mobile DD - comp and pen unavailable` & `Mobile DD - education unavailable`) have long headings that run into the body text. There just needs to be more spacing between the two text styles.

**Comment by Samara-Strauss** [comment]
Liz, this is incredible. Great work.

**Comment by mtcA6** [comment]
Minor item, in the flow, when linking to other sketch files, is there a way for non-sketch licensed people to copy the text? 

for example, this just shows as an image and I can't access the text
![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/9af0be14-de47-4b0e-9cec-006a5136de30)

**Comment by mtcA6** [comment]
> Liz, this is incredible. Great work.

AGREE, I think this was one of the more complex flows given the different permutations and all the various alerts!

**Comment by tpharrison** [comment]
@andaleliz - no comments, it's awesome!  Sorry for the late response.

**Comment by adamwhitlock1** [comment]
Great work on a complex set of states and flows!

A couple areas that may or may not be worth updating.
- If you do not choose an account type (when initially enrolling) then you will see a validation error on the account type field that includes a message: 'Please select the type that best describes your account'
- We are going to remove the helper text this sprint on the routing number. There are a couple sections that show it as either 'Routing number (Your 9-digit routing number will update your bank’s name)' or 'Routing number (Your bank’s name will appear after you add the 9-digit routing number)'

I know that we are trying to update the states and not necessarily keeping the content parts super up to date on these, but figured I'd throw those out there.

Thanks @andaleliz !

**Comment by andaleliz** [comment]
Thank you everyone for your feedback and taking the time to review! I'm glad that overall the team thinks these are awesome and an improvement 🎉 

@adamwhitlock1 these are great call outs - I'll include the validation error for sure.

These screens actually should reflect what is on production, especially since our use case docs link to them.  Can you lmk the number of that FE ticket? I'll follow along and when it's closed, I'll remove that helper text.  We don't have a great way to keep Sketch in sync w/ prod but I want to try to be better about it.  Sometimes Sketch gets pretty far ahead 😬

**Comment by adamwhitlock1** [comment]
@andaleliz great timing 😸 I just put in the PR, so once it is approved it will go to staging and the daily deploy should also get it to prod since it is just a minor content change.

https://github.com/department-of-veterans-affairs/vets-website/pull/25412

**Comment by andaleliz** [comment]
@adamwhitlock1 I love when that happens. Thank you! I'll go ahead and update the screens now.

**Comment by andaleliz** [comment]
@mtcA6, apologies for not replying to this comment sooner:

>Minor item, in the flow, when linking to other sketch files, is there a way for non-sketch licensed people to copy the text?

Unfortunately, no - Sketch doesn't provide a way to link to an external URL. I swapped it to a `bit.ly` URL that should be a _little_ easier to type in.  Hopefully this is something that could be solved with Figma, if we make that switch.

**Comment by mtcA6** [comment]
Yas! Love the bit.ly
