### ISSUE TITLE
Design | Profile | Update user flows | Map user flow for personal information

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#61359]
## Background
The team determined that the user flow approach piloted in the [notification settings mobile Sketch page](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/p/B5792AF8-87F2-496D-AE7A-DAD1448A6018/canvas) (review MHV on VA.gov section) is helpful across all practice areas, and an improvement over the current high level user flows.

In #61356 we refined that approach and are ready to apply it to other parts of profile. Let's apply this to the mobile pages only, not desktop. It's duplicative to do it in both places, and we are a mobile-first organization.

## Tasks

- [ ] Map user flow for personal information, on the mobile page
- [ ] Solicit async feedback/review from team. 
- [ ] Update any use case docs that link to user flows, especially if we decided to remove the high level user flow page (unknown at the time this ticket is written)

**Comment by andaleliz** [comment]
[User flow updated here](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/p/BE56DBF8-B1BF-4A60-9379-DC9F2C5098BB/canvas)

**Comment by pamela-drouin** [comment]
@andaleliz I am a fan of differentiating behaviors from states, and numbering state types alphanumerically. As someone still learning the intricacies, this makes everything even more clear!

**Comment by aagosto90** [comment]
Hey @andaleliz ! Thanks for tagging me. I love this and will have to use it as a template if I have to do a more complicated user flow. My only suggestion might be to add more arrows from buttons to other states that you're showing because it just takes a little longer to decipher using only numbers and I expect a user flow to show me a quick visual of a user path, which arrows help with. This does work fine though if you take the time to look for the numbers so you can take or leave that feedback tbh. Awesome job; always appreciate you thinking of new and better ways to do things.

**Comment by adamwhitlock1** [comment]
This is really good! I personally like the numbers that match to the 'state rows' instead of arrows, as sometimes the multiple arrows will cross of look confusing at first for me personally. I'd be curious to see what this and other more complex section like direct deposit or contact information would look like with arrows vs without, but I'm totally cool without having them. The .1 incrementing with the state variations is perfect, seems straightforward and understandable to me.

One thing that I did notice that is just probably part of the web viewer based sketch interface is that a lot of time the artboard names overlap with the labels that are added and make it hard to read.

![Screenshot 2023-08-01 at 9 46 39 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/ce1c2fdd-5c24-4435-8b1b-06dc19afa334)

Don't know if there is an easy way for me to turn off the artboard names from being visible or if the labels could be moved slightly?
