### ISSUE TITLE
Design | Profile | Update user flows | Map user flow for connected apps

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#61361]
## Background
The team determined that the user flow approach piloted in the [notification settings mobile Sketch page](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/p/B5792AF8-87F2-496D-AE7A-DAD1448A6018/canvas) (review MHV on VA.gov section) is helpful across all practice areas, and an improvement over the current high level user flows.

In #61356 we refined that approach and are ready to apply it to other parts of profile. Let's apply this to the mobile pages only, not desktop. It's duplicative to do it in both places, and we are a mobile-first organization.

## Tasks

- [x] Map user flow for connected apps, on the mobile page
- [x] Solicit async feedback/review from team. 
- [x] Update any use case docs that link to user flows, especially if we decided to remove the high level user flow page (unknown at the time this ticket is written)

**Comment by andaleliz** [comment]
Completed; not soliciting review because this is so straightforward and simple. I will let the team know it's been completed in Slack
