### ISSUE TITLE
[DATA-LOAD] Load all data collected for "LEBANON, PA" facilities pages into related Facility pages in CMS [Data Tech]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#6136]
## User Story or Problem Statement
As a Veteran Web user, I want to see the local Faculties page, so that it highlights travel, parking, lodging, local amenities, hours of operation, health services, and non-health services offered. 

## Goal
_Highlight the Individual FACILITY'S Page with veteran needed information_

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran traveling to each facility_
- _Reduce Click through count by_Highlighting top stories_

## Tasks
_Complete load of data from spreadsheet to CMS related facilities listed below:_
- [x] Lebanon VA Medical Center
- [x] Berks County VA Clinic
- [x] Cumberland County VA Clinic
- [x] Landcaster County Va Clinic
- [x] Schuylkill County VA Clinic
- [x] Yourk VA Clinic
- * Spreadsheet will highlight the main areas of information, THAT MUST BE TRANSFERRED TO Facilities detail page
- [ ] Parking
- [ ] Transportation
- [ ] Visitor hours and Info
- [ ] Lodging
- [ ] Dining and Retail
- [ ] Special non-health services 
- [ ] Confirm social media accounts (facebook, twitter, etc)

## Acceptance Criteria

* Create accordions, with correct title listed in data.
* Load data from spreadsheet into facility page.
* Preview page is documented.
