### ISSUE TITLE
Design | Profile | Update user flows | Map user flow for military information

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#61360]
## Background
The team determined that the user flow approach piloted in the [notification settings mobile Sketch page](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/p/B5792AF8-87F2-496D-AE7A-DAD1448A6018/canvas) (review MHV on VA.gov section) is helpful across all practice areas, and an improvement over the current high level user flows.

In #61356 we refined that approach and are ready to apply it to other parts of profile. Let's apply this to the mobile pages only, not desktop. It's duplicative to do it in both places, and we are a mobile-first organization.

## Tasks

- [ ] Map user flow for military information, on the mobile page
- [ ] Solicit async feedback/review from team. 
- [ ] Update any use case docs that link to user flows, especially if we decided to remove the high level user flow page (unknown at the time this ticket is written)

**Comment by andaleliz** [comment]
@adamwhitlock1 can you please do me a solid and review the flow on [this page](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/p/D6D40E33-BC4E-4A06-90C7-879C59AD49F4/canvas)? I just want to make sure I haven't misrepresented anything related to why we show those alerts on the page. Thanks!

**Comment by adamwhitlock1** [comment]
This all looks good. 

In looking through the designs, I realized that the code has two separate alerts built out for the 'Not in DEERS' and 'No military history' cases even though they are literally the same content 🤦🏼 I'm guessing it was different in the past and got updated and we didn't consolidate them. I will make a ticket to make them one alert in the code.

**Comment by andaleliz** [comment]
Oh good catch @adamwhitlock1! You're probably right about why there are two. 

Thanks for reviewing it, going to close this one out.
