### ISSUE TITLE
Design | Profile | Update user flows | Map user flow for account security

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#61362]
## Background
The team determined that the user flow approach piloted in the [notification settings mobile Sketch page](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/p/B5792AF8-87F2-496D-AE7A-DAD1448A6018/canvas) (review MHV on VA.gov section) is helpful across all practice areas, and an improvement over the current high level user flows.

In #61356 we refined that approach and are ready to apply it to other parts of profile. Let's apply this to the mobile pages only, not desktop. It's duplicative to do it in both places, and we are a mobile-first organization.

## Tasks

- [x] Map user flow for account security, on the mobile page
- [x] Solicit async feedback/review from team. 
- [x] Update any use case docs that link to user flows, especially if we decided to remove the high level user flow page (unknown at the time this ticket is written)

**Comment by andaleliz** [comment]
@adamwhitlock1, do we show the "Review terms and conditions" process list item to all users in the account security section, or only those that have health care? I can't tell from the logic in any of [these files](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/personalization/profile/components/account-security).  Thanks!

**Comment by adamwhitlock1** [comment]
So, there were some changes made to the profile a while back and that section of the conditional list was removed.

I found this [old ticket where we did the work](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55590), I'll see if I can find the root cause of this, but I think it had to do with the terms and conditions application being deprecated or something along those lines.

**Comment by andaleliz** [comment]
Ah, ok! So we should remove any Sketch files that have the 3rd step, correct?  Thanks!

**Comment by adamwhitlock1** [comment]
Yep, you can remove that 3rd step in design files! Sorry we didn't catch that when we first did the work.
