### ISSUE TITLE
[bug spike] SC Unprocessable Entity Investigation 

### ISSUE THREAD

**Issue by kylesoskin** [department-of-veterans-affairs/va.gov-team#61374]
## Value Statement

**_As a_** veteran submitting a Supplemental Claim
**_I want to_** have the submission go through
**_So that_** it gets to the VA

---
## Background Context
Time boxed spike (1-2 hours). Look into why the submission was rejected. Looks to be a missing address key issue.

## Tasks
- [x] Investigate why the submissions is erroring
- [ ] Make tickets to fix it if a large effort (or fix if small effort)

---
## Definition of Ready 
- [x] Gather infomation

## Definition of Done
- [ ] We know the cause of the error
- [ ] We've defined a solution if needed, and assigned it to the appropriate party
- [ ] We've asked the CC team to reach out and ask the Veteran to resubmit

## Additional info/Context

http://sentry.vfs.va.gov/organizations/vsp/discover/platform-web:46ae007853b24da087c94848df4e8da9/?end=2023-07-06T04%3A59%3A59.000&field=message&name=Supplemental+Claims&project=4&query=url%3Ahttps%3A%2F%2Fwww.va.gov%2Fdecision-reviews%2Fsupplemental-claim%2Ffile-supplemental-claim-form-20-0995%2F%2A+level%3Aerror+message%3A%22vets_server_error%3A+Unprocessable+Entity+Error+%2Fgenerated%2F995-supplemental-claim.entry.js+XMLHttpRequest.%3Canonymous%3E+XMLHttpRequest.%3Canonymous%3E%28generated%2F995-supplemental-claim.entry%29%22&sort=-message&start=2023-06-23T05%3A00%3A00.000&widths=-1

**Comment by kylesoskin** [comment]
This was from a month ago, after investigation, we have not received any additional 422 unprocessable errors.
