### ISSUE TITLE
[Design] Notification Component: Documentation/Sketch updates per staging review guidance

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#61388]
## Background
There were two launch blocking findings from our Notification Component on My VA staging review:
- #61157 
- #61158 

We need to make updates to our documentation and sketch annotations to remove the role="alert" from the component and incorporate an aria label.

## Tasks
Update documentation and sketch annotations to reflect:
- [ ] Remove the `role="alert"` from the component in the library so that it's not immediately announced to screenreaders when the page is loading before anything else (addresses 61157)
- [ ] Incorporate `aria-describedby` label in the component on My VA (addresses 61158)

## Acceptance Criteria
- [ ] Documentation and sketch annotations are updated

**Comment by aagosto90** [comment]
[Sketch annotation here](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/vRE9LdQ)
There is no FE documentation to update for this component.

**Comment by aagosto90** [comment]
The first task to remove `role="alert"` isn't something I would annotate or include in FE documentation but should be covered in Allison's ticket @ajakabcin
