### ISSUE TITLE
Change template ID for test version B

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#61383]
For Reactivation test version B (sent via triggered emails/VA Notify), we will need to point to the updated template that will be set up in VA Notify

## Tasks:
- [ ] (After Product/Design implements the new template as designed - Dependency)
- [x] Insert template ID into API call
- [ ] Ensure that personalization changes are passed along correctly

## Acceptance criteria:
- [ ] Template ID is shared
- [ ] When we run a test, the correct template is applied
- [ ] Personalization appears correctly

**Comment by alevindecanini** [comment]
Template ID: `480270b2-d2c8-4048-91d7-aebc51a2f073`
