### ISSUE TITLE
[FE] Notification Component: a11y updates to component 

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#61399]
## Background
There were two launch blocking findings from our Notification Component on My VA staging review:
- #61157 
- #61158 

We need to make updates to the code to remove the role="alert" from the component in the library, and incorporate an aria label in our implementation on My VA.

## Tasks
Per documentation and [sketch annotation](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/vRE9LdQ) updates in #61388 :
- [x] ~Remove the `role="alert"` from the component in the library so that it's not immediately announced to screenreaders when the page is loading before anything else (addresses 61157)~ [resolved by DST pr](https://github.com/department-of-veterans-affairs/component-library/pull/741)
- [x] Incorporate `aria-describedby` label in the component as implemented on My VA (addresses 61158)
- [x] Tag @aagosto90 for assistance validating
- [x] Let PM know when complete - PM to update and close staging review tickets

## Acceptance Criteria
- [ ] `Role="alert"' is removed from the component in the library
- [ ] `aria-desicribedby` implemented in component on My VA
- [ ] Staging review tickets are closed

**Comment by ajakabcin** [comment]
hey @allisonlu I noticed that Nick from the design system team posted [this](https://github.com/department-of-veterans-affairs/component-library/pull/741) at the end of the week - not sure if that accomplishes what we were aiming for here but wanted to flag in case it conflicts or dupes what you were planning

**Comment by allisonlu** [comment]
@ajakabcin they're exactly the changes that i was planning to make! (for the first task) I checked it off as complete in the description

**Comment by allisonlu** [comment]
@ajakabcin 

Opened a PR for review from the DST this morning!

**Comment by allisonlu** [comment]
@aagosto90 @Adrian-Brewster just verified that the `aria-describedby` label is working for **user 226**! The date and time is also now working. 

<img width="452" alt="Screenshot 2023-07-24 at 8 54 50 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/8542413/64f592c2-016e-4a2a-8316-c73177d46817">

**Comment by aagosto90** [comment]
Awesome - I see it too! @allisonlu

**Comment by ajakabcin** [comment]
Looks great - thanks you @aagosto90 for validating! And thanks @allisonlu for the fix on the date!
