### ISSUE TITLE
[FSR] Remove Combined FSR feature flag

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#61414]
## Issue Description
`combined_financial_status_report` has been true for long enough we can remove references to it and clean out deprecated files/functionality. 

`<env>/flipper/features/combined_financial_status_report`

Some pages that will be deprecated by the removal (not a complete list):
 - debt selection
 - resolution options
 - recreational vehicles
 - Also double check transform functionality. 

[Link to Feature toggle documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles) for removing feature flag

---
## Tasks
- [x] Identify and remove all references to `combined_financial_status_report` feature flag on the frontend 
- [x] Identify and remove deprecated files/functionality from removing the feature flag
- [x] Update/remove unit and e2e tests affected by the removal of feature flag. 
- [x] Remove feature flag from 

## Acceptance Criteria
- [x] `combined_financial_status_report` feature flag & it's references have been removed
- [x] All tests passing
  - [x] Unit
  - [x] e2e
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by OptionSelect** [comment]
Potentially will roll. Ticket is close, just dealing with Tests breaking due to removal of flag.
