### ISSUE TITLE
[FSR] SW - Add feature flag for streamlined waiver

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#61415]
## Issue Description
Add new feature flag for Streamlined Waiver effort. Let's call it `financial_status_report_streamlined_waiver`

[Link to documentation on adding new feature flag](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles)

---
## Tasks
- [x] Add new feature flag for streamlined waiver

## Acceptance Criteria
- [x] New feature flag has been created for streamlined waiver work
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
