### ISSUE TITLE
[FE] [BE] Improve CHIP <-> DynamoDB latency

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#61417]
## Background

Latency between CHIP lambdas and DynamoDB is on the order of 2-300ms greater than between LoROTA and DynamoDB lambdas. See these example traces:

- [chip](https://tevi.ddog-gov.com/apm/resource/chip/aws.lambda/e1831f0cd5f8f613?query=%40_top_level%3A1%20env%3Aprod%20service%3Achip%20operation_name%3Aaws.lambda%20resource_name%3Aproject-chipAPI-shortenUrl-prod&env=prod&event=AgAAAYkmyyYH0c4JegAAAAAAAAAYAAAAAEFZa215M2ZjQUFBelNPMmFlM0t6TTJveQAAACQAAAAAMDE4OTI2Y2ItN2NiNS00ZWYxLThlZDYtYmFmOGI5MjczYTM0&graphType=span_list&shouldShowLegend=true&sort=time&spanID=6977604118198598590&spanType=service-entry&spanViewType=metadata&timeHint=1688572995079&topGraphs=latency%3Alatency%2Chits%3Aversion_count%2Cerrors%3Aversion_count%2CbreakdownAs%3Apercentage&traceID=3632727873667751552&traces=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&start=1688569444701&end=1688573044701&paused=false)
- [lorota](https://tevi.ddog-gov.com/apm/resource/lorota/aws.lambda/e6ce024b9ce2ead9?query=%40_top_level%3A1%20env%3Aprod%20service%3Alorota%20operation_name%3Aaws.lambda%20resource_name%3Aproject-LoROTA-post-prod&env=prod&event=AgAAAYkmwd2QfzHMfwAAAAAAAAAYAAAAAEFZa213ZkpaQUFCQ29wbnFCWFlUbjBKSgAAACQAAAAAMDE4OTI2YzEtZjU2Mi00MzY1LWJmODUtNGFjMDc4MWFlNTFm&graphType=span_list&shouldShowLegend=true&sort=time&spanID=974948211192264698&spanType=service-entry&timeHint=1688572386704&topGraphs=latency%3Alatency%2Chits%3Aversion_count%2Cerrors%3Aversion_count%2CbreakdownAs%3Apercentage&traceID=5278883625047281860&traces=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&start=1688569962231&end=1688573562231&paused=false)

## Implementation

[Using Amazon VPC endpoints to access DynamoDB](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/vpc-endpoints-dynamodb.html)

## Tasks
- [ ] [FE] **_insert frontend work_**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Average CHIP <-> DynamoDB request latency is within 10% of average LoROTA <-> DynamoDB request latency
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
