### ISSUE TITLE
Standardize and improve "Missing ID" messages (aka "Need More Info")

### ISSUE THREAD

**Issue by NB28VT** [department-of-veterans-affairs/va.gov-team#61419]
## Summary

Several surveyed veterans report being prevented from beginning the Form 526 flow for applying for disability benefits because of missing identification information in the VA system.

When this happens, they are prompted to contact a call center and given opaque and incorrect messaging about what to tell a representative to resolve the problem.

![Screenshot 2023-05-26 at 11.22.21 AM.png](https://images.zenhubusercontent.com/647627f92b5e617343beedd1/3c52f6b0-c7f2-46ca-90e0-c7d78f9abdd4)

Moreover, the code driving this in the vets-website repo in particular is duplicative, inconsistent and obscures what data is actually missing.

(This epic is a response to an investigation undertaken in [this ticket](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/56676) and [the resulting report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/526_entry_error_discovery.md).

---

## Acceptance Criteria:
- [ ] Standardize boilerplate messaging language
- [ ] Provide detailed information on what data is missing so the Veteran can report it to the call center
- [ ] Verify call center numbers are correct when certain data is missing (potentially already completed [here](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/57110)
- [ ] Simplify and clean up `vets-website` component code displaying these messages.

---

## Overview:

Based on [research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/526_entry_error_discovery.md) tracing through the vets-api and vets-website codebases, the 526 Form appears to require we have all of the below before allowing a Veteran to begin the Form 526 Flow:

* Date of Birth
* SSN
* BIRLS ID (Beneficiary Identification and Records Locator (Sub)System)
* EDIPI (Electronic Data Interchange Personal Identifier)
* Participant ID

(Whether all of this data is actually required downstream is an open question potentially out of scope for an initial fix; in the immediate term we can improve the existing messaging).

### Current Messages 
At a high level, the current messaging works like this:

1. Date of Birth Missing:

```
We need some information for your application

We’re sorry. We can’t find your date of birth in our records. You won’t
be able to continue your application for disability compensation until
you update your VA account with your date of birth.

Please call us at
CONTACTS.VA_BENEFITS
CONTACTS['711']

We’re here Monday through Friday, 8:00 a.m. to 9:00 9:00 p.m. ET.

```

**(Note this message is accurate and helpful)**

2. Date of Birth present but missing ANY of EDIPI, SSN or Particpant ID:

```
We need more information for your application

We don’t have all of your ID information for your account. We need this
information before you can file for disability compensation. To update your
account, please call the {srSubstitute('MyVA411', 'My V. A. 4 1 1.')}{' '}
main information line at <va-telephone contact={CONTACTS.HELP_DESK} /> (
<va-telephone contact={CONTACTS['711']} tty />) and select 0. We’re here
24 hours a day, 7 days a week.

Tell the representative that you may be missing your EDIPI number or BIRLS ID
```

**(Note this message is inaccurate - BIRLS ID is not considered and SSN isn't mentioned in the error message)**

3. All of the above present, but BIRLS ID still missing:

```
We need some information for your application

We need more information from you before you can file for disability compensation.
. Please call Veterans Benefits Assistance at{' '}
<va-telephone contact={CONTACTS.VA_BENEFITS} /> (
<va-telephone contact={CONTACTS['711']} tty />
), Monday through Friday, 8:00 a.m. to 9:00 p.m. ET to update your
Account.
```

**(Note generic message providing no helpful information)**

### Proposed Change:

I believe we should standardize this to display one boilerplate message at the top:

```
We need some information for your application

We need more information from you before you can file for disability compensation.
. Please call Veterans Benefits Assistance at{' '}
<va-telephone contact={CONTACTS.VA_BENEFITS} /> (
<va-telephone contact={CONTACTS['711']} tty />
), Monday through Friday, 8:00 a.m. to 9:00 p.m. ET to update your
Account.
```

Followed by what information the user is actually missing, (note the change to "we" are missing, I don't think we want to assume the Veteran is responsible for us not having the data):

```
"Tell the representative that we are missing:

* SSN
* DOB
* Participant ID
```

**Comment by NB28VT** [comment]
CC @RakshindaAslam

**Comment by tblackwe** [comment]
Enabled in Production
<img width="1106" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTNsQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a189dff761fb4f5d0f415d175254fb69d41ecb27/image.png" alt="image.png" />
