### ISSUE TITLE
Assess need for additional Q&As on PACT Act page

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#61423]
## Issue Description
Angie sent a request from the Deputy Chief of Staff to add 7 additional Q&A sections on the PACT Act page. We'll need to assess the need for these Q&As using available data. Michael confirmed in the email thread that this request was not driven by any specific data about frequency of calls/questions. 

[https://app.zenhub.com/files/133843125/e70cb09b-6dda-45d8-a989-759025392071/download](https://app.zenhub.com/files/133843125/e70cb09b-6dda-45d8-a989-759025392071/download)

---
## Tasks
- [ ] Assess need for additional Q&As
- [ ] Send suggested approach to partners

## Acceptance Criteria
- [ ] Page is updated with suggested Q&A additions (if needed)

**Comment by laurwill** [comment]
Sent suggested approach to Michael on Friday July 7 (Danielle copied on thread). Will pick up this work when I'm back on 7.17.

**Comment by laurwill** [comment]
Thanks @katherine-fung ! I should have noted more clearly that we don't need to include all 6 scenarios the partners provided, especially with the space constraint in the single Q&A section. 

And we got confirmation that you should reapply for burial benefits if you were previously denied.

A (who I still cannot tag for some reason) is going to take a first pass at reviewing this and then we'll post back. Thank you!

**Comment by aprocik1** [comment]
Hi @chelsealevinson and @megzehn! We've completed part of the updates requested in this ticket. And we've received accuracy reviews from relevant SMEs and stakeholders. But before publishing this update, Danielle needs to send it to OPIA for approval.

Can you copyedit this [Drupal node](https://prod.cms.va.gov/node/47694/latest) by 2:30 pm ET today? That way we can confirm next steps with Danielle at our meeting this afternoon. If that's not doable, we can aim for Wednesday's meeting with Danielle. Thanks!

**Comment by RLHecht** [comment]
@strelichl can you add a task to this to set up the translation work once these changes are published? We'll need tickets for both Tagalog and Spanish.

**Comment by laurwill** [comment]
Just noting this was copyedited and Danielle will share with OPIA for approval.

**Comment by laurwill** [comment]
Hi @DanielleThierryUSDSVA ! Here's that ticket I mentioned in a recent sync — I think the next step was for you to share this [updated Q&A on the PACT Act page](https://prod.cms.va.gov/node/47694/latest) with OPIA. 

- We changed the question about reapplying for DIC to include how to reapply for all 4 relevant types of survivor benefits
- We added specific instructions to select the PACT Act options on the DIC form

Let me know if you need anything else or have any questions about the changes we made here!
