### ISSUE TITLE
Update DIC Q&A on PACT Act page

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#61425]
## Issue Description
Angie sent a request from the Deputy Chief of Staff to update instructions for PACT-related DIC claims. This document has those suggestions, plus a request to add several Q&As that we'll track in a different ticket.
[https://app.zenhub.com/files/133843125/57f4affb-0918-4707-b862-267a7ea3ed65/download](https://app.zenhub.com/files/133843125/57f4affb-0918-4707-b862-267a7ea3ed65/download)
---
## Tasks
- [ ] Make accuracy updates to Q&A 
- [ ] Review
- [ ] Send to partners
- [ ] Copyedit and publish

## Acceptance Criteria
- [ ] DIC Q&A is updated

**Comment by laurwill** [comment]
Incorporating this into ticket [61423](https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/61423). Closing this out.
