### ISSUE TITLE
HLR | Review server error preventing form start

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#61424]
## Value Statement
**_As a_** Veteran encountering a server error while HLR loads contestable issues
**_I want to_** be able to proceed with the form even though no contestable issues were loaded
**_So that_** I won't be blocked from starting the form

---
## Background Context

Any backend server, except a 404 (not found), error will show a message on the HLR introduction page. The error alert replaces the save in progress start/continue form message so the Veteran is not able to do anything.

NOTE: This issue is only appearing in HLR. In our Supplemental Claim & Notice of Disagreement forms, we are also encountering similar server issues, but we _do not_ block the user from starting the form; the contestable issues page shows that no issues were loaded.

## Acceptance Criteria
- [ ] User can complete the form when issues are unavailable
- [ ] User is made aware when issues are unavailable

## Designs and Build Notes
- [DESIGN](https://www.sketch.com/s/96420652-15b7-45bb-80c5-5454dcd4b3c6/a/GoJJpL5)

## Tasks
- [x] Review HLR blocking progression
- [x] Review differences in SC & NOD (server error not shown)
- [x] Review & investigate UX of blocking progression (HLR vs other appeals forms)
- [x] Conduct appropriate research
- [x] Decision made on how to fix this behavior
- [x] Design available

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
After looking at the other forms for treating this pattern, we've determined:
- Users should not be blocked from entering the form if there is an error loading issues
- Error message should be shown to users about not being able to pull up eligible issues (copying the pattern from SC)
- Users should be able to complete the form if they add an issue 

What we have not solved for:
- Including language that lets users know it is a temporary issue (coming back the the form later may/may not resolve the issue) 

Design has been included for immediate fix, but it's recommended to revisit copy that more accurately addresses this error.

**Comment by eileen-coforma** [comment]
Ticket and design is scoped to resolve the problem with HLR not being able to start due to the server errors for contestable issues. I created another ticket to explore the opportunity to clearly notify veterans when there is a server error that can affect their form experience: [Decision Reviews | Warning alert for when parts of the application system is down](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62006)

**Comment by Mottie** [comment]
This is ready for testing in staging... 

- Log into any user
- Go to [HLR intro page](https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996).
- "Block request URL" for `https://staging-api.va.gov/v1/higher_level_reviews/contestable_issues/compensation` endpoint in dev tools (right click on name in network tab)
- Reload the page to see the form continue button (not blocked at this point any more!)
- Navigate to contestable issues page

![hlr-api-error](https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/6b768cd6-e6d1-475b-b423-04357998e48a)

**Comment by eileen-coforma** [comment]
Works as intended on Staging. Looks good to me.

**Comment by Mottie** [comment]
@sade we can close this ticket
