### ISSUE TITLE
[discovery] Look into possible approaches for adding an indicator for SW forms

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#61420]
## Issue Description
As we approach closer to streamlined waiver rollout, the FSR submissions that come in based on SW approved Veterans will need to be identifier by downstream services. We will need a way for this to be identified via the PDF and JSON data that gets sent to VBS

---
## Tasks
- [ ] Determine indicator placement in PDF generation
- [ ] Develop or repurpose field in JSON to contain indicator status

## Acceptance Criteria
- [ ] We are able to develop an indicator for both PDF and JSON versions for streamlined waiver submissions
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
