### ISSUE TITLE
[UX] Submit Translations to the State Department

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#61435]
## Tasks
- [x] Create JSON file with new content to be translated (one for each language)
- [x] Submit JSON file and English screen shots to Randi Hecht for forwarding to the State Department

## Acceptance Criteria
- [x] JSON file has been submitted to Randi Hecht

**Comment by loripusey** [comment]
Submitted [list of new content and screenshots](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/translations/2024_Q1) to Randi on 3/27
