### ISSUE TITLE
[UX] Submit Translations to the State Department

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#61442]
## Tasks
- [ ] Create JSON file with new content to be translated (one for each language)
  - See instructions [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/translations/json-compare/README.md)
  - New content should only include the info on the login page & the updated text message
- [ ] Create English screen shots for context
  - See examples of screenshots [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/translations/spanish-round-3)
- [ ] Submit JSON file and English screen shots to Randi Hecht for forwarding to the State Department

## Acceptance Criteria
- [ ] JSON file and English screen shots have been submitted to Randi Hecht

**Comment by loripusey** [comment]
no longer need
