### ISSUE TITLE
VBA service taxonomy content review

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#61465]
## Issue Description
Sitewide facilities team is migrating VBA location pages to the modernized site. They need content input on new VBA terms for Service Taxonomy. They also need content input on design for a regional office facility page.

See sketch and doc in [intake](https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/58511)

---
## Tasks
- [x] Review sketch design and provide feedback (Laura)
- [x] Copyedit national descriptions for benefit and service types in Excel sheet (Megan)

## Acceptance Criteria
- [x] Feedback provided to facilities team

**Comment by laurwill** [comment]
Megan copyedited the descriptions, I suggested edits to the Sketch design, and I posted feedback in the intake ticket. We may provide more support after testing, but closing this out for now.
