### ISSUE TITLE
EVSS Migration - 526 Submit - Transformation Service - basic framework 

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#61463]
## Issue Description
Currently when a 526 application is submitted from vets-website, it is received by vets-api in a JSON defined in vets-json-schema's 21-526EZ-allclaims/[schema.js](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/568ca2019b787664daec926b4492b196a65590e9/src/schemas/21-526EZ-allclaims/schema.js). This JSON is _further_ [translated](https://github.com/department-of-veterans-affairs/vets-api/blob/9dce77681a181fe7b7afd66141b37f6c033eba95/lib/evss/disability_compensation_form/data_translation_all_claim.rb#L49) into a form that EVSS understands _before_ it is [saved](https://github.com/department-of-veterans-affairs/vets-api/blob/9dce77681a181fe7b7afd66141b37f6c033eba95/app/controllers/v0/disability_compensation_forms_controller.rb#L99) to the database and [submitted](https://github.com/department-of-veterans-affairs/vets-api/blob/9dce77681a181fe7b7afd66141b37f6c033eba95/app/controllers/v0/disability_compensation_forms_controller.rb#L55) to the submission sidekiq [job](https://github.com/department-of-veterans-affairs/vets-api/blob/9dce77681a181fe7b7afd66141b37f6c033eba95/app/models/form526_submission.rb#L76) and [posted to EVSS](https://github.com/department-of-veterans-affairs/vets-api/blob/9dce77681a181fe7b7afd66141b37f6c033eba95/app/workers/evss/disability_compensation_form/submit_form526.rb#L69).

Lighthouse accepts a [different](https://docs.google.com/spreadsheets/d/1e_UoLN31Uzr9_aG4ByCcuQm3kIq844cg_l0IBJYnfLE/edit?usp=sharing) JSON format than EVSS- different enough that it makes more sense to build a new version of it that we can cleanly switch to (then remove the old layer down the road). This also gives us greater flexibility to call this service from wherever makes the most sense, as there is currently some questions around whether or not it's more appropriate to call from vet-api's API layer (submit_all_claim) or the submission job or service layer submit_form526.rb/service.rb

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] The bare minimum framework of a new translation service which adheres (at least initially) to a contract suggested by EVSS::DisabilityCompensationForm::DataTranslationAllClaim (data_translation_all_claim.rb)
- [ ] Stubbed out methods for translate, translate_banking_info, translate_service_pay, translate_service_info, translate_veteran, translate_treatments, translate_disabilities
- [ ] Basic unit tests supporting the barebones structure
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sethdarragile6** [comment]
NOTES from refinement:
- terminology note: name things more like "transform..." than "translate..."
- might make sense to do all this on a feature branch?
