### ISSUE TITLE
General Orientation - July 2023

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#61474]
## User Story
As a Platform team member supporting Platform Orientation, I want to host, record, transcribe and share the General Orientation session so that VFS team members are able to be easily oriented to the VA.gov Platform. 

Assignee: @shiragoodman 
Peer Reviewer:

## Description
Platform is responsible for hosting the Platform Orientation sessions once every quarter. These sessions are recorded w

## Impacted Artifacts
[Orientation Host/Zoom Host Guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2656731745/Orientation+Host+Zoom+Host+Guidance)

## Tasks
_**Note**: if the Zoom host and the Instructor/Session host are the same person, then all below tasks will be performed by the same individual._

### Zoom host
- [x] Ensure Zoom settings are set according to the guidance: [Orientation Host/Zoom Host Guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2656731745/Orientation+Host+Zoom+Host+Guidance) / Before you start your session / Zoom settings
- [x] After the session has been hosted, forward the Zoom recording to the Instructor/Session host
### Instructor/ Session host
- [x] Review the guidance in the [Orientation Host/Zoom Host Guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2656731745/Orientation+Host+Zoom+Host+Guidance) for During your orientation session
- [x] Host the orientation session as scheduled
- [x] Download mp4 and vtt files from Zoom recording
- [x] Clean up the transcript
- [x] Upload recording and transcript to YouTube
- [x] Change visibility of previous recording to Private (if applicable)
- [x] Update video link on Platform Website
- [x] Update video link on Confluence/ Orientation Sessions page

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The live General Orientation for the quarter has taken place
- [x] VFS team members are able to view the latest recording of the orientation session

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer
