### ISSUE TITLE
Domo dataset update errors

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#61471]
## Issue Description
The 'BQ-Standard Forms Funnel' and 'BQ - Standard Forms User Completion' datasets have not updated since the 6/25 weekly update.  We are getting the following error.  We need to determine what is driving this and how we get around.  Does it need a re-write too?  Can we pull more from BQ vs Domo or vice versa. 

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/93597659/20d60ca1-b401-4e96-b15f-d8450a1cd948)

---
## Tasks
-

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
