### ISSUE TITLE
Reschedule Thursday 1:30pm ET Collab Cycle timeslot

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#61473]
## User Story
As a Governance team member, I want to ensure the collab cycle timeslots throughout the week work with everyone's schedule, including our PO, so that there are no conflicts when events are scheduled.

Assignee: @shiragoodman 
Peer Reviewer:

## Description
Matt Dingee recently shared that the Thursday 1:30pm ET timeslot for Collaboration Cycle touchpoints does not work with his schedule. The purpose of this ticket is to find another timeslot on Thursday that will work for Governance team. The timeslot should not occur before 11:00am ET, and should not bump up against the existing 3:30pm ET timeslot (so no 3:00 or 4:00pm ET). If we cannot find a timeslot on Thursday, we will have to explore alternate days of the week.

## Impacted Artifacts
[Collaboration Cycle Calendly guide](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2017034292/Collaboration+Cycle+Calendly+guide)
[Zoom information for Collab Cycle meetings](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2454585540/Zoom+information+for+Collab+Cycle+meetings)

## Tasks
- [ ] Contact Matt to find out what times on Thursday he is available
- [ ] Compare with Governance team members availability
- [ ] Propose times to team on #platform-governance-team Slack channel (or inform team of no available times on Thursday)
   - [ ] Connect with Shira to discuss alternate options if Thursday will not work
- [ ] Once new timeslot is confirmed, work with @allison0034 or @shiragoodman to update Calendly
- [ ] Update the 2 impacted artifacts above to reflect the new date/time
   - [ ] Notify Shira so she can update Zoom. The Zoom info for the 1:30pm ET timeslot will likely be repurposed for the new timeslot.

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Governance team members and the team PO are able to attend all Collab Cycle timeslots throughout the week

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
per 1:1 with @humancompanion-usds on 7/7, Matt will see if his 1:1 with Kevin can be moved to a different date/time

**Comment by shiragoodman** [comment]
@humancompanion-usds any update on whether you'll be able to reschedule your meeting that conflicts with this?

**Comment by humancompanion-usds** [comment]
Kevin moved it. Thanks.
