### ISSUE TITLE
[Research][Content] Create Veteran-facing FAQ for Check-in plus Travel Pay

### ISSUE THREAD

**Issue by kellysmith1008** [department-of-veterans-affairs/va.gov-team#61476]
## Description
With the travel pay pilot, we created a [travel pay FAQ document](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/59722) to share with the Wilkes-Barre MSAs. We would like to create a Veteran-facing FAQ to completing eCheck in plus travel pay. At a minimum, the FAQ should include the answers to the following questions: 

- How do I check in with my phone?
- How can I tell if my check in was successful?
- What if I my information isn't correct?
- Why can't I check in for my appointment? (outside the check in window)
- What if mobile check in isn't enabled for my clinic?
- What if check in doesn't work on my phone?
- How do I submit a claim?
- What type of claim can I submit?
- What do I do if I did not travel from my home address?
- What do I do if I did not use my own vehicle?
- What do I do if I have receipts to submit?
- How do I know if my claim has been submitted?
- How can I find out the status of my claim?
- When will I get my money?
- Can I submit a claim without doing eCheck-in?
- Can I submit a claim later, after my appointment?
- Who can I contact if I have questions or problems with my claim?

It might be possible to reuse most of what we've already written for the MSAs, but might need updating, more Veteran-focused language, and accessibility/DSL checks to make sure we're aligned with VA standards.

NOTE: It might be needed to determine the best answer for these questions in the lens of check-in alone AND check-in with travel pay - for example, do the answers change based on the successful check in happening? If so, how should those differences be documented in the FAQ?

## Tasks
- [x] Create the FAQ guide 
- [x] Run guide by UX, Danielle T, Stephen B, and Martha W
- [ ] Publish to [git](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/product)
- [ ] Send git link to Kay to take to IVC

## Acceptance Criteria
- [x] Content has been created & reviewed
- [ ] Content is published on git
- [ ] Content has been sent to Kay

**Comment by kellysmith1008** [comment]
[Started the document](https://docs.google.com/document/d/1EDagXmyXE55DhH6ChZIFyYTBhvHd2Ekk0XNKVjTBF6Q/edit?usp=sharing), borrowing some from the travel pay FAQ. Hoping to have this wrapped up by Wednesday this week so I can send it out for review by the end of the sprint and published to git.

**Comment by kellysmith1008** [comment]
@loripusey @benbrasso-agile6 I've finished the draft of this in my google doc. I'm going to work today into putting it into a Word document with VA formatting and such to share out tomorrow, but if you wanted to get eyes on it and provide feedback, I'd welcome all of it :)

**Comment by benbrasso-agile6** [comment]
Thanks, Kelly. 

I do think this is valuable, but I also think about the comment we always get from Veterans that, "there are so many posters and pamphlets everywhere." Are we just contributing to the noise? 

Anyways, not something we need to worry about for the moment. Let's keep going with the draft.

**Comment by loripusey** [comment]
It's very cumbersome to be sure, but the MSAs said that once they have someone walk them through how to do these things they often times (not always) do it themselves from then on.

**Comment by benbrasso-agile6** [comment]
Agreed, agreed

**Comment by kellysmith1008** [comment]
Sent an email to Danielle, Stephen, and Martha today (had to send Stephen's separately cause I misspelled his email on the first pass) but I received an automatic reply from him that he's out through Monday, July 31. @benbrasso-agile6 or @loripusey is there someone else you'd like me to share it with in his absence?
