### ISSUE TITLE
Prep for mtg w/ 10-10ezr team

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#61481]
## Purpose
Jessica Stump works on this team and mentioned that they've begun discovery work on digitizing this form.  May want to reach out and get their take at this stage.  

[10-10EZR form](https://www.va.gov/health-care/update-health-information/)

## Tasks
- [x] Setup meeting (@steel36)
- [x] Review [10-10ezr form](https://www.va.gov/find-forms/about-form-10-10ezr/) for familiarity and collect notes and questions [here](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2697396525/10-10ezr+Form+notes?atlOrigin=eyJpIjoiY2EzODg1NTJhODlkNGQ4Njk3MTU2MGE3YzE4YTQ3MDQiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ)
     - [x] @tayism 
     - [x] @twoangstroms 
     - [x] @steel36
 - [x] Review [Usability baseline study](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2697396525/10-10ezr+Form+notes#Usability-study%5BmediaInline%5D)
    - [x] @tayism 
    - [x] @twoangstroms 
    - [x] @steel36 
 
- [x] Review [10-10 team ecosystem doc](https://docs.google.com/document/d/1E2BIbE6uGquxuwbh6FRqUdnL9nTnPHPOOD9wZyrXDNg/edit)
- [x] Review [10-10 team deck](https://docs.google.com/presentation/d/1E6lK7RMJCwzaLWRzz5rbvUIz9fqlMslA-23GsusvQdI/edit#slide=id.g1e1e7467903_0_73)
     - [x] @tayism 
     - [x] @steel36

- [x] Prep [interview guide](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2703949853/10-10+Team+Workshop+Conversation+Guide+-+Forms+Digitization+Research)
- [x] Prep [mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1689353387699/fdf211459ff92ddace01d6112073667c10f476ce?sender=u4f7db1750f2355f805e60296)
- [x] Share mural w/ 10-10 team

## Acceptance Criteria
- [x] Meeting is scheduled
- [x] Guide is ready
- [x] Mural is ready
- [x] Mural is shared out

**Comment by tayism** [comment]
Still awaiting access to the 10-10 team deck
