### ISSUE TITLE
NOD | Prepare hypotheses, metrics, and design experiments

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#61491]
## Value Statement
**_As a_**  designer
**_I want to_** design multiple solutions for the problems found in evaluative research
**_So that_** we can test for ones that make the highest impact

---
## Tasks
- [x] Determine problems and hypotheses for experimentation
- [x] Draft multiple design solutions for opportunities scope
- [x] Review with enablement team
- [ ] Create screen flows and prototypes
- [x] Establish hypothesis and metrics to measure user behavior change against proposed value 

## Hypotheses within scope
- We believe that by providing timely alternative (to physical mail) access to decision letters will decrease missed deadlines and extension requests.
- We believe by providing an area for Veterans to include an explanation of their appeal will decrease the % of late form drop off and increase the % of digital form submissions.
- We believe by providing Veterans with access points to information about different DR options will decrease false starts / early drop-offs, which will increase the usability of our analytics to measure the value of our form.
- We believe that by providing Veterans applying for a DR with access to their decision letter within the form will increase the Veteran's confidence and completion rate of the form.

## Hypotheses to confirm with post release monitoring
- We believe that by changing the way the Veteran navigates back to the in-progress form will decrease the number of abandoned forms.

## Open Questions
- Do we have A/B testing capability?

## Definition of Ready 
- [x] Clear value description
- [x] Reviewable acceptance criteria
- [x] Research findings are complete
- [x] Priorities are scoped

## Definition of Done
- [ ] Designs are approved by PO and ready to test

**Comment by saderagsdale** [comment]
Schedule time with Julie to talk about hypotheses and test approaches @eileen-coforma @saderagsdale

**Comment by saderagsdale** [comment]
@eileen-coforma Yep, closing this one now.
