### ISSUE TITLE
Landing Page Bug - Broken MHV National Portal LP on redirect

### ISSUE THREAD

**Issue by LynneJohnson224** [department-of-veterans-affairs/va.gov-team#61496]
As a veteran who doesn't have access to the new MHV on VA.gov, when I sign in, I want to be directed to myhealth.va.gov/mhv-portal-web/home.

**Acceptance Criteria:**
- [ ] Users without access to the new MHV on VA.gov are able to log in and see the existing my health home page. 

**Tasks:**
- [ ] Using the steps below, replicate the experience.
- [ ] Determine solution
- [ ] Test/verify the solution fixes the issue
- [ ] Implement solution
--------------------------------------------------------------------------------------------------------------------------------------
Unexpected behavior was discovered with va.gov/my-health and the redirect back to the MHV national portal landing page.

**The desired behavior/happy path should be:**
1. user is signed out of all va.gov sessions
2. user navigates to va.gov/my-health
3. user is redirected / sees sign in modal
4. users signs in
5. user is redirected to va.gov/my-health
6. if user meets feature toggle criteria, user sees va.gov/my-health
7. if user does not meet criteria, user sees myhealth.va.gov/mhv-portal-web/home

**The replication steps for the bug are:**
1. make sure you are signed out of all va.gov sessions
2. navigate to va.gov/my-health
3. see the mhv landing page app start loading
4. see redirect to myhealth.va.gov/mhv-portal-web/home happen
5. see broken MHV national portal landing page

Slack Thread: https://dsva.slack.com/archives/C0581MN69TJ/p1688653996826109

**Comment by radavis** [comment]
Verified bugfix has been deployed to va.gov.
