### ISSUE TITLE
EVSS Migration - rateddisabilities deployment release plan and test run

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#61519]
## Issue Description
This ticket covers the discovery and release plan to deploy the migrated endpoint to LH for rateddisabilities. The scope includes:
- Release plan - look at staggered release
   -  Can point to specific user through feature toggle
   -  
- Tasks in the ticket

---
## Tasks
- [x] Get Production Client ID from LH veteran verification API
- [x] Identify a prod user and do a test run
- [x] Test rateddisabilities endpoint using prod credentials from any client
- [x] Place the Client ID and RSA key in AWS parameter store
- [x] Confirm devops repository and K8 manifest repository has references to correct environment variable paths
- [x] Argo CD - Test rateddisabilities endpoint using prod credentials from any client
- [x] Confirm how other teams are batching the release
- [x] Identify acceptance criteria for a successful run
- [x] Establish Comms
- [x] Update [configuration.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/lighthouse/veteran_verification/configuration.rb#L11) with scope for new credentials

## Acceptance Criteria
- [x] Identify acceptance criteria for a successful run
- [x] Figure out how to monitor success(526ez form, submit workflow)
- [x] Release plan
- [x] Create Testrail testplan
- [x] Execute Testrun
- [x] Successful testrun
- [x] Create a ticket for starting the staggered release based on the plan
- [x] Email alerts for thresholds

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
cc @aurora-a-k-a-lightning - do we know the release date for LH?

**Comment by mchae-nava** [comment]
Created a ticket for some pre-launch tasks identified in refinement: https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/62666

Also noting I will amend the plan to include internal users, per discussion

**Comment by mchae-nava** [comment]
Plan doc here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/disability-experience/team-docs/Release%20Plans/DBEX%20Rated%20Disability%20Endpoint%20Migration%20Release%20Plan.md#planning-4

**Comment by RakshindaAslam** [comment]
Refine the plan based on ITF changes

**Comment by mchae-nava** [comment]
Update from Jerek re:prod credentials for rated_disability: https://dsva.slack.com/archives/C04KW0B46N5/p1692213694086909?thread_ts=1692202585.099119&cid=C04KW0B46N5
