### ISSUE TITLE
Research: Importance of the COR Name When Submitting AWS Request in GitHub

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#61515]
**Description**

Investigate the importance of the COR Name section when submitting an AWS request in GitHub. Context here: https://oddball.slack.com/archives/C0459AQ5GBT/p1684868307169719

**Definition of Done**

- All tasks below are complete or all questions below are answered.

**Tasks/Questions to Ask**

- [x]  Why is it important
- [x]  What happens if we remove it
- [x]  Do we have documentation justifying why people need it if it is necessary
- [x]  Misc. factors we may not be considering

**Comment by bdech** [comment]
Providing [link](https://vfs.atlassian.net/wiki/spaces/~71202013aea26098a14ec0a4a43cb8bc9a85b4/pages/edit-v2/2699362892?draftShareId=66d1438a-51ce-42d5-afaf-f12f54742cf5&inEditorTemplatesPanel=auto_closed) to where I'm writing up findings

**Comment by bdech** [comment]
Need to setup a meeting with Clint and discuss if the COR is something we can remove from the AWS access request template

**Comment by alyssagallion** [comment]
Need to talk with Clint to get COR removed for AWS access request. @bdech Can you do that and close? Thanks!

**Comment by bdech** [comment]
Research portion has been completed. Met with Clint and discussed his viewpoints on this change. Closing this sprint objective out as the research has been completed. Will open up a new actionable item for implementing change.

This change is going to be on-hold. Clint mentioned pending meetings/discussions with OCTODE/VA Security. Will follow up with Clint in a week or so for an update.
