### ISSUE TITLE
EVSS Migration - 526 Submit - Transformation Service - Implement top-level/minimal translate

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#61522]
## Issue Description
Once the basic framework of the translation service is in place ([#61463](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/61463)), we can build the basic `transform` method and its supporting infrastructure, i.e. supporting enums, attributes, etc. (see [existing translate](https://github.com/department-of-veterans-affairs/vets-api/blob/9dce77681a181fe7b7afd66141b37f6c033eba95/lib/evss/disability_compensation_form/data_translation_all_claim.rb#L49))

From [LH API spec](https://dev-developer.va.gov/explore/api/benefits-claims/docs?version=current) (Disability section, POST /veterans/{veteranId}/526)

![image.png](https://images.zenhubusercontent.com/61688531a0a844ef1cf9286b/fd6c2f0b-6a85-4a7e-8b39-c3591e80e078)

Sample Lighthouse request JSON (Expected Result)

> {
>   "data": {
>     "type": "form/526",
>     "attributes": {
>       "claimantCertification": true,
>       "claimProcessType": "STANDARD_CLAIM_PROCESS",
>       "claimDate": "2020-12-18",
> ...

- claimDate is optional, and is currently not sent to EVSS
- continue to autopopulate claimantCertification with 'true'

Current format saved in the Form526Submission table
```
{
    "form526": # maps to "data.attributes" {
        "claimantCertification": true, # hardcode/"autopopulate" with true
        "standardClaim": false, # maps to claimProcessType "STANDARD_CLAIM_PROCESS"
        "autoCestPDFGenerationDisabled": false, # n/a - removed
        "applicationExpirationDate": "2024-06-20T22:29:51Z", # n/a - LH populates internally
"overflowText": "VA Form 21-4142/4142a has been completed by the applicant and sent to the PMR contractor for processing in accordance with M21-1 III.iii.1.D.2.", # n/a
        "bddQualified": false, # maps to claimProcessType
        "claimSubmissionSource": "VA.gov", # PENDING - may hardcode or "autopopulate" this value, or not send it at all
...
}

```
Notes:
- path for `claimantCertification` probably does not matter since it is hardcoded
- our current format does not have `claimaintDate`
- need to determine how to map the `claimProcessType` based off of `["form526"]["bddQualified"]` ("BDD_PROGRAM"), ``["form526"]["standardClaim"]` ("STANDARD_CLAIM_PROCESS")
- need to figure out what "FDC_PROGRAM" is derived from for the `claimProcessType` value
```
FDC
 - Fully Developed Claim
    - claims processing
```

## Tasks
- [ ] If possible, resolve open questions re: [claimProcessType](https://docs.google.com/document/d/1Z6Cw6MU5fgsjeJ9vuqrk-4xMEkq3LpQ7NbKUq0KNAyk/edit?disco=AAAA01TwLFQ)/[bddQualified/BDD_PROGRAM](https://docs.google.com/document/d/1Z6Cw6MU5fgsjeJ9vuqrk-4xMEkq3LpQ7NbKUq0KNAyk/edit?disco=AAAA01TwLDo). Confirm that:
- [ ] - claimProcessType = BDD_PROGRAM when bddQualified = true
- [ ] - claimProcessType = STANDARD_CLAIM_PROCESS when standardClaim = true
- [ ] - claimProcessType = FDC_PROGRAM when... none of the above are true? something else? we will operate under this assumption and can iterate if told otherwise
- [ ] - Can bddQualified  and standardClaim  both be true at the same time? if so, what value do we put? does one claimProcessType  take precedence over the other?

## Links
- [ ] [526 Submit Endpoint Discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/evss-to-lighthouse-migration/526-submit-discovery.md)
- [ ] [526 Submit Questions for EVSS/LH](https://docs.google.com/document/d/1Z6Cw6MU5fgsjeJ9vuqrk-4xMEkq3LpQ7NbKUq0KNAyk/edit?usp=sharing) (see comment history)
- [ ] [EVSS/LH Mapping](https://docs.google.com/spreadsheets/d/1e_UoLN31Uzr9_aG4ByCcuQm3kIq844cg_l0IBJYnfLE/edit?usp=sharing)
- [ ] [526 Submission Workflow](https://lucid.app/lucidchart/b93a0b4d-c62b-49b0-8efc-c7e9e4a05d1c/edit?viewport_loc=264%2C2887%2C2742%2C1303%2C0_0&invitationId=inv_a7c98577-e6f5-4ec2-897b-3b0f6212b08d)
- [ ] [526 submit migration development plan](https://lucid.app/lucidchart/da48c5ea-5ea7-4d5f-aeed-2db8232419d1/edit?viewport_loc=-104%2C-1449%2C2219%2C1055%2C0_0&invitationId=inv_99e48cbe-80ff-48b5-a6e7-c864abd29fb0)

## Acceptance Criteria
- [ ] Implementation of basic functionality- output of barebones LH JSON structure
- [ ] Supporting tests
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
