### ISSUE TITLE
 Consolidate our documentation

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#61526]
## Tasks

- [x] Consolidate documentation in Mural
- [x] Consolidate documentation in G-Drive

## Acceptance Criteria
- [x] Share out links with team and attach to ticket

**Comment by skirkman16** [comment]
[IPP Mural Folder](https://app.mural.co/invitation/room/1689002689926?code=8483671e5c914aac8b38dac1172201c6&sender=u99cd1ac4f5c240d8dffd4204)
[IPP Google Drive Folder](https://drive.google.com/drive/folders/1p_0eQu2_D2JlSC6hqIClHaopuQC09S3w?usp=drive_link)
organized IPP related files on Mural and GDrive. currently copying over documentation to Github
