### ISSUE TITLE
Ensure reviewing DST guidance is part of DST Staging Review process

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#61532]
## User Story
As a Governance team member, I want to make sure I am reviewing the guidance alongside the component for DST Staging Reviews so that I can be sure VFS teams are able to follow the guidance easily and consistently. 

Assignee: @allison0034 
Peer Reviewer: @CherylEvans 

## Description
At the DST Staging Review on 6/30/2023, It was recognized that Governance team members have not been consistently reviewing the guidance that supports the actual design system component. Our focus has been on reviewing the component itself. However, it would make sense that the component guidance be reviewed and evaluated alongside the component as the guidance supports the VFS teams use of the component and is critical in ensuring that the component is consistently applied across VFS products.

The purpose of this ticket is to ensure that the Governance team process for completing a DST Staging Review includes a review of the component AND the components supporting guidance.

## Impacted Artifacts
- [How to Request a Design System Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572124196/How+to+Request+a+Design+System+Staging+Review)
- [Staging Review - Design System - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572124161/Staging+Review+-+Design+System+-+Moderator+Responsibilities)
- [How to Document Findings for a Design System Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572189697/How+to+Document+Findings+for+a+Design+System+Staging+Review)

## Tasks
- [x] Update How to Request a Design System Staging Review to include a reminder for guidance, design system, Sketch and storybook.
- [x] Update canned response in Staging Review - Design System - Moderator Responsibilities to include a reminder for guidance, design system, Sketch and storybook. 
- [x] Update How to Document Findings for a Design System Staging Review to look at guidance, design system, Sketch and storybook for that component

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Governance team provides feedback to DST on both the DS component and the components supporting guidance.

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
@shiragoodman we review all links that are included in staging reviews. Shouldn't it be the design system team's responsibility to include the links in the staging review ticket? Perhaps we just update our documentation to remind the person scheduling the review to include all links like we do with VFS teams.

**Comment by shiragoodman** [comment]
@allison0034 yes, that's what I was thinking. On [this page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572124196/How+to+Request+a+Design+System+Staging+Review) we have a code block for Carol to copy/paste into her SR tickets. I think we should break down this step:
`- [ ] All URLs (design system and storybook)`
so that it's more specific to the component and supporting guidance. I would even specify that we need the guidance regardless if it's been changed or not.

**Comment by shiragoodman** [comment]
by supporting guidance, I mean "additional info"

**Comment by allison0034** [comment]
Added tasks

**Comment by allison0034** [comment]
@humancompanion-usds should include reviewing the Sketch file?

**Comment by allison0034** [comment]
I confirmed with Matt to add Sketch to a list of things to check.

**Comment by allison0034** [comment]
@CherylEvans this is ready for your review.
