### ISSUE TITLE
EVSS Migration - 526 Submit - Transform Service - Disabilities

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#61557]
## Issue Description
This story is to implement the LH equivalent of the [translate_disabilities](https://github.com/department-of-veterans-affairs/vets-api/blob/9dce77681a181fe7b7afd66141b37f6c033eba95/lib/evss/disability_compensation_form/data_translation_all_claim.rb#L468) method within our new translation service.

From [LH API spec](https://dev-developer.va.gov/explore/api/benefits-claims/docs?version=current) (Disability section, POST /veterans/{veteranId}/526)
![image.png](https://images.zenhubusercontent.com/61688531a0a844ef1cf9286b/316c2f86-b8e0-4618-a782-48ff84209442)
![image.png](https://images.zenhubusercontent.com/61688531a0a844ef1cf9286b/a5060ad3-d52b-4aea-9df0-a787dcf90b8d)

- specialIssues are being generated internally by LH, and not needed in the request

Lighthouse Sample Request Body JSON 
```
"disabilities": [
        {
          "disabilityActionType": "NEW",
          "name": "Hearing Loss",
          "classificationCode": "3140",
          "serviceRelevance": "Heavy equipment operator in service",
          "approximateDate": "07-1968",
          "isRelatedToToxicExposure": false,
          "exposureOrEventOrInjury": "Noise"
        },
        {
          "disabilityActionType": "INCREASE",
          "name": "Musculoskeletal - Foot",
          "classificationCode": "8994",
          "serviceRelevance": "Service in Vietnam War",
          "approximateDate": "12-1972",
          "ratedDisabilityId": "1234567",
          "diagnosticCode": 9999,
          "isRelatedToToxicExposure": true,
          "exposureOrEventOrInjury": "Agent Orange"
        },
        {
          "disabilityActionType": "NONE",
          "name": "Traumatic Brain Injury",
          "classificationCode": "9020",
          "serviceRelevance": "Explanation of service connection",
          "approximateDate": "11-04-2019",
          "ratedDisabilityId": "1234567",
          "diagnosticCode": 9999,
          "isRelatedToToxicExposure": false,
          "secondaryDisabilities": [
            {
              "name": "Cancer - Musculoskeletal - Elbow",
              "disabilityActionType": "SECONDARY",
              "classificationCode": "249470",
              "serviceRelevance": "Injured left knee when brace on right knee failed",
              "approximateDate": "06-11-2008"
            }
          ]
        }
      ],
```

**Sample of current Form526Submission form data format**
```
"disabilities": [
            {
                "decision_code": "SVCCONNCTED",
                "decision_text": "Service Connected",
                "name": "Diabetes mellitus0",
                "effective_date": "2018-03-27T21:00:41.000+0000",
                "rated_disability_id": "0",
                "rating_decision_id": "63655",
                "rating_percentage": "100",
                "related_disability_date": "2018-03-27T21:00:41.000+0000",
                "disabilityActionType": "INCREASE",
                "special_issues": [
                    {
                        "code": "TRM",
                        "name": "Personal Trauma PTSD"
                    }
                ]
            },
            {
                "name": "string",
                "classificationCode": "string",
                "disabilityActionType": "NEW",
                "specialIssues": [
                    "PTSD/1"
                ],
                "serviceRelevance": "Caused by an in-service event, injury, or exposure\\nstring",
                "secondaryDisabilities": [
                    {
                        "name": "string",
                        "classificationCode": "string",
                        "disabilityActionType": "SECONDARY",
                        "specialIssues": [
                            "PTSD/2"
                        ],
                        "serviceRelevance": "Caused by a service-connected disability\\nstring"
                    }
                ]
            }
        ]
```

---
## Tasks
- [ ] Resolve open question about [isRelatedToToxicExposure](https://docs.google.com/document/d/1Z6Cw6MU5fgsjeJ9vuqrk-4xMEkq3LpQ7NbKUq0KNAyk/edit?disco=AAAA01TwLEw)
- [ ] Confirm that classificationCode comes in from the front end via the `BRD API /disabilities endpoint`. (LH requirement)
- [ ] Ensure these validations are being honored:
- [ ] - "If disabilityActionType is "INCREASE", then "ratedDisabilityId" and "diagnosticCode" are required."
- [ ] - "The diagnosticCode is required if disabilityActionType is NONE and there are secondary disabilities included with the primary. The diagnosticCode must match an existing rated disability if disabilityActionType is NONE and there are secondary disabilities included with the primary."

## Acceptance Criteria
- [ ] Implement the "disabilities" service method
- [ ] Supporting unit tests
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sethdarragile6** [comment]
TODO: create story to:

Confirm that classificationCode comes in from the front end via the BRD API /disabilities endpoint. (LH requirement)
if it DOES, add A.C. to this story to pass classificationCode on to LH
if NOT, add new story to handle implementation of validation against BRD endpoint on our side.
for now, do NOT pass classificationCode onto LH (until the above is resolved) @sethdarragile6
