### ISSUE TITLE
EVSS Migration - 526 Submit - Transform Service - Service Info

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#61554]
## Issue Description
This story is to implement the LH equivalent of the [translate_service_info](https://github.com/department-of-veterans-affairs/vets-api/blob/9dce77681a181fe7b7afd66141b37f6c033eba95/lib/evss/disability_compensation_form/data_translation_all_claim.rb#L203) method within our new translation service.

From [LH API spec](https://dev-developer.va.gov/explore/api/benefits-claims/docs?version=current) (Disability section, POST /veterans/{veteranId}/526)
![image.png](https://images.zenhubusercontent.com/61688531a0a844ef1cf9286b/ef0cede5-9203-4698-a7d8-58665d33492f)
![image.png](https://images.zenhubusercontent.com/61688531a0a844ef1cf9286b/f4f2ef34-739d-4aa5-b257-ba4ff99ab8d7)
![image.png](https://images.zenhubusercontent.com/61688531a0a844ef1cf9286b/68c0c0d4-17b7-4666-ad83-a6398a8094e9)

Sample JSON

>       "serviceInformation": {
>         "servicePeriods": [
>           {
>             "serviceBranch": "Public Health Service",
>             "activeDutyBeginDate": "2015-11-14",
>             "activeDutyEndDate": "2018-11-30",
>             "serviceComponent": "Active",
>             "separationLocationCode": "V01D"
>           }
>         ],
>         "confinements": [
>           {
>             "approximateBeginDate": "06-11-2016",
>             "approximateEndDate": "09-11-2016"
>           },
>           {
>             "approximateBeginDate": "06-2019",
>             "approximateEndDate": "07-2019"
>           }
>         ],
>         "reservesNationalGuardService": {
>           "obligationTermsOfService": {
>             "beginDate": "2016-11-24",
>             "endDate": "2017-11-17"
>           },
>           "unitName": "National Guard Unit Name",
>           "unitAddress": "1243 pine court",
>           "component": "National Guard",
>           "title10Activation": {
>             "anticipatedSeparationDate": "2017-10-03",
>             "title10ActivationDate": "2018-02-11"
>           },
>           "unitPhone": {
>             "areaCode": "555",
>             "phoneNumber": "5555555"
>           },
>           "receivingInactiveDutyTrainingPay": true
>         },
>         "alternateNames": [
>           "John Jacob Jingleheimer-Schmidt",
>           "Johnathon"
>         ],
>         "servedInActiveCombatSince911": false
>       },
> 

**Current Form526Submission formdata format**
```
"serviceInformation": {
            "servicePeriods": [
                {
                    "serviceBranch": "Air Force",
                    "activeDutyBeginDate": "2020-01-01",
                    "activeDutyEndDate": "2023-09-17"
                }
            ],
            "confinements": [
                {
                    "confinementBeginDate": "2019-10-10",
                    "confinementEndDate": "2020-12-31"
                }
            ],
            "alternateNames": [
                {
                    "firstName": "John",
                    "middleName": "Jonny",
                    "lastName": "Johnson"
                }
            ],
            "separationLocationName": null,
            "separationLocationCode": null
        },
```

Implementation note:
1. `separationLocationCode`: 1. this property should only be on the most recent endDate of the `servicePeriods` Form526Submission attribute
2. `serviceComponent`: this is an enum value (`Active, Reserves, National Guard `). our theory is that is it derived from the service Branch Name
3. `reservesNationalGuardService`: look at spreadsheet for sample structure line 83 https://docs.google.com/spreadsheets/d/1e_UoLN31Uzr9_aG4ByCcuQm3kIq844cg_l0IBJYnfLE/edit#gid=0
4. `servedInActiveCombatSince911`: **not required** skip for now since we do not send today. revisit if added to the front-end
5. `reservesNationalGuardService.unitAddress`: **not required**. skip for now since we do not send today. revisit if added to the front-end

---
## Tasks
- [x] Resolve open questions on [serviceComponent and reservesNationalGuardService/component](https://docs.google.com/document/d/1Z6Cw6MU5fgsjeJ9vuqrk-4xMEkq3LpQ7NbKUq0KNAyk/edit?disco=AAAA01TwLE0) and [unitAddress](https://docs.google.com/document/d/1Z6Cw6MU5fgsjeJ9vuqrk-4xMEkq3LpQ7NbKUq0KNAyk/edit?disco=AAAA01TwLE4)
- [x] - is it truly truly optional?
- [x] - If EVSS is autopopulating this on the form, then we might need to replicate this logic on our side
- [x] Resolve open question on [separationLocationCode](https://docs.google.com/document/d/1Z6Cw6MU5fgsjeJ9vuqrk-4xMEkq3LpQ7NbKUq0KNAyk/edit?disco=AAAA01TwLGI) 
- [x] What does vets api internal separation location code look like?

## Acceptance Criteria
- [ ] Implement the "service info" service method
- [ ] Supporting unit tests
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by aurora-a-k-a-lightning** [comment]
@RakshindaAslam 
look into this field: servedInActiveCombatSince911

**Comment by aurora-a-k-a-lightning** [comment]
@RakshindaAslam another missing field that we may want to look into
 `reservesNationalGuardService.unitAddress`
