### ISSUE TITLE
EVSS Migration - 526 Submit - Transform Service - Service Pay

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#61553]
## Issue Description
This story is to implement the LH equivalent of the [translate_service_pay](https://github.com/department-of-veterans-affairs/vets-api/blob/9dce77681a181fe7b7afd66141b37f6c033eba95/lib/evss/disability_compensation_form/data_translation_all_claim.rb#L159) method within our new translation service.

From [LH API spec](https://dev-developer.va.gov/explore/api/benefits-claims/docs?version=current) (Disability section, POST /veterans/{veteranId}/526)
![image.png](https://images.zenhubusercontent.com/61688531a0a844ef1cf9286b/61c0a701-614d-4e3b-a261-add4283d8189)
![image.png](https://images.zenhubusercontent.com/61688531a0a844ef1cf9286b/1299762b-6cb1-43ea-999b-596792c6712e)
![image.png](https://images.zenhubusercontent.com/61688531a0a844ef1cf9286b/8b0a8f45-c5df-46c6-a720-e97a5570e87f)

Sample JSON

>       "servicePay": {
>         "favorTrainingPay": true,
>         "favorMilitaryRetiredPay": false,
>         "receivingMilitaryRetiredPay": false,
>         "futureMilitaryRetiredPay": true,
>         "futureMilitaryRetiredPayExplanation": "",
>         "militaryRetiredPay": {
>           "branchOfService": "Army",
>           "monthlyAmount": 840.75
>         },
>         "retiredStatus": "PERMANENT_DISABILITY_RETIRED_LIST",
>         "receivedSeparationOrSeverancePay": false,
>         "separationSeverancePay": {
>           "datePaymentReceived": "2018-07-31",
>           "branchOfService": "Naval Academy",
>           "preTaxAmountReceived": 379.25
>         }
>       },

---
**Sample of current Form526Submission form data format**
```
 "servicePay": {
            "waiveVABenefitsToRetainTrainingPay": true,
            "waiveVABenefitsToRetainRetiredPay": true,
            "militaryRetiredPay": {
                "receiving": true,
                "payment": {
                    "serviceBranch": "Air Force"
                }
            }
        },
```

---
## Tasks
- [ ] Resolve open question on [receivedDate](https://docs.google.com/document/d/1Z6Cw6MU5fgsjeJ9vuqrk-4xMEkq3LpQ7NbKUq0KNAyk/edit?disco=AAAA01TwLF8) (LH is looking into the "year-only" use case for ApproximateDate types)

## Acceptance Criteria
- [ ] Implement the "service pay" service method
- [ ] Supporting unit tests
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
