### ISSUE TITLE
[Epic/BE] Create Prototype API between ES and VA.Gov profile for Financial Disclosure/Priority Group

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#61558]
**AS: We can break this into multiple stories if needed. A couple of ideas for how to break it out: 1) Send and Receive, 2) By EZR paper form section (income and expenses), 3) a combination of 1 and 2, or another way**

As a Veteran, I would like to view the financial information the VA has for me online, as well as my Priority Group, so that I can make sure I don't have to pay copays if I don't have to.

**Discovery story:**
- [ ] Talk to AE team
- [ ] Find documentation
- [ ] Success: This is possible
------------

Discovery: 3
- Do we have to authenticate the API call and how?
- Is there a local setup?
- Reach out to Tom Harrison or Adam Whitlock?
- Lihan: May need to go into STG or talk to Josh F.
- Josh F. might have API docs

-----------------------

**Receive** 
- Confirm that we can pull the following VES --all are Previous Year(EZR Section IV-V):
- [ ] Gross Annual Income from employment: Veteran, Spouse, All Dependent 
- [ ] Net Income from Farm, Ranch, Property, Business: Veteran, Spouse, All Dependent 
- [ ] Other Income Amounts: Veteran, Spouse, All Dependent 
- [ ] Total non-reimbursed medical expenses paid by Veteran and Spouse
- [ ] Funeral and Burial Expenses
- [ ] College or vocational expenses
- [ ] Create Document for API auth
- [ ] Any other relevant information (AS: I don't know what this would look like, but anything else that catches the eye that might relate to a Veteran's income and/or a Priority Group calculation)
- [ ] 
Questions:

- Do we have to authenticate the API call and how?
- Is there a local setup?
- Reach out to Tom Harrison or Adam Whitlock?
- Lihan: May need to go into STG or talk to Josh F.
- Josh F. might have API docs

 -----------------------------------------------------

**Send**
- Confirm we can send the follow to VES:
- [ ] Gross Annual Income from employment: Veteran, Spouse, All Dependent 
- [ ] Net Income from Farm, Ranch, Property, Business: Veteran, Spouse, All Dependent 
- [ ] Other Income Amounts: Veteran, Spouse, All Dependent 
- [ ] Total non-reimbursed medical expenses paid by Veteran and Spouse
- [ ] Funeral and Burial Expenses
- [ ] College or vocational expenses
- [ ] Any other relevant information (AS: I don't know what this would look like, but anything else that catches the eye that might relate to a Veteran's income and/or a Priority Group calculation)
- [ ] Consent to Copays and receive communications 

---------------------------------------

- [ ] We can receive a Veteran's Priority Group
- [ ] The information we send will be used to update PG (i.e. handled the same as a paper form or other VA.Gov Profile changes)

-----------------------------------
- **Success:** Team confirms or denies that we can send and receive the data necessary to add Financial Disclosure and Priority Group information to the VA.Gov Profile. 
- If denies, team outlines fields that cannot be accessed/sent.

**Comment by emily-brown34** [comment]
@lihanli  this is blocked by/dependent on [61714](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/61714)

we will discuss with @alexseelig  during planning today
