### ISSUE TITLE
EVSS Migration - 526 Submit - Transform Service - Banking Info

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#61552]
## Issue Description
This story is to implement the LH equivalent of the [translate_banking_info](https://github.com/department-of-veterans-affairs/vets-api/blob/9dce77681a181fe7b7afd66141b37f6c033eba95/lib/evss/disability_compensation_form/data_translation_all_claim.rb#L101) method within our new translation service.

From [LH API spec](https://dev-developer.va.gov/explore/api/benefits-claims/docs?version=current) (Disability section, POST /veterans/{veteranId}/526)
![image.png](https://images.zenhubusercontent.com/61688531a0a844ef1cf9286b/81da6e95-feae-479a-8734-aca8299fbb27)

Sample JSON

>       "directDeposit": {
>         "accountType": "CHECKING",
>         "accountNumber": "123123123123",
>         "routingNumber": "123456789",
>         "financialInstitutionName": "Chase",
>         "noAccount": false
>       }

**Current Form526Submission form data format**
```
"directDeposit": {
            "accountType": "CHECKING",
            "accountNumber": "123456789",
            "routingNumber": "123456789",
            "bankName": "string"
        },
```

Implementation notes:
1. in Form526Submission, we could be missing "directDeposit" missing
2. Today, if the directDeposit is missing from the evss format, we do not send it to EVSS either. We plan on doing the same, unless LH says differently.

---
## Tasks
- [ ] Resolve open question on [noaccount](https://docs.google.com/document/d/1Z6Cw6MU5fgsjeJ9vuqrk-4xMEkq3LpQ7NbKUq0KNAyk/edit?disco=AAAA01TwLFI). If EVSS was autopopulating this on the form, then we might need to replicate this logic on our side. 
- [ ] (to Lighthouse: should be also just send no directDeposit node, or a silly directDeposit node with just a noaccount:true. (Rakshinda to followup with Alejandro about business case))

## Acceptance Criteria
- [ ] Implement the banking info (aka direct_deposit) service method
- [ ] Supporting unit tests
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
