### ISSUE TITLE
EVSS Migration - 526 Submit - Transform Service - Treatments

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#61556]
## Issue Description
This story is to implement the LH equivalent of the [translate_treatments](https://github.com/department-of-veterans-affairs/vets-api/blob/9dce77681a181fe7b7afd66141b37f6c033eba95/lib/evss/disability_compensation_form/data_translation_all_claim.rb#L429) method within our new translation service.

From [LH API spec](https://dev-developer.va.gov/explore/api/benefits-claims/docs?version=current) (Disability section, POST /veterans/{veteranId}/526)
![image.png](https://images.zenhubusercontent.com/61688531a0a844ef1cf9286b/a20b3e69-ae36-40ef-9408-8e0e8940e09a)

Sample JSON

>       "treatments": [
>         {
>           "treatedDisabilityNames": [
>             "Hearing Loss",
>             "Traumatic Brain Injury"
>           ],
>           "center": {
>             "name": "Center One",
>             "state": "GA",
>             "city": "Decatur"
>           },
>           "beginDate": "03-1985"
>         },
>         {
>           "treatedDisabilityNames": [
>             "Musculoskeletal - Foot"
>           ],
>           "center": {
>             "name": "Center One",
>             "state": "GA",
>             "city": "Decatur"
>           },
>           "beginDate": "03-1985"
>         }
>       ],

**Sample of current Form526Submission form data format**
```
"treatments": [
            {
                "startDate": {
                    "year": "2019",
                    "month": "10",
                    "day": "10"
                },
                "treatedDisabilityNames": [
                    "string"
                ],
                "center": {
                    "name": "string",
                    "country": "USA",
                    "city": "string",
                    "state": "OR"
                }
            }
        ],
```

- NOTE: there are changes pending to make "center" optional
---
## Tasks
- [ ] Resolve open question about [country](https://docs.google.com/document/d/1Z6Cw6MU5fgsjeJ9vuqrk-4xMEkq3LpQ7NbKUq0KNAyk/edit?disco=AAAA01TwLEc) (LH is looking into the "year-only" use case for ApproximateDate types)

## Acceptance Criteria
- [ ] Implement the "treatments" service method
- [ ] Supporting unit tests
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
