### ISSUE TITLE
EVSS Migration - 526 Submit - Transform Service - Veteran

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#61555]
## Issue Description
This story is to implement the LH equivalent of the [translate_veteran](https://github.com/department-of-veterans-affairs/vets-api/blob/9dce77681a181fe7b7afd66141b37f6c033eba95/lib/evss/disability_compensation_form/data_translation_all_claim.rb#L293) method within our new translation service.

From [LH API spec](https://dev-developer.va.gov/explore/api/benefits-claims/docs?version=current) (Disability section, POST /veterans/{veteranId}/526)
![image.png](https://images.zenhubusercontent.com/61688531a0a844ef1cf9286b/8347e3a4-7542-4d27-9396-ef0ee9323564)
![image.png](https://images.zenhubusercontent.com/61688531a0a844ef1cf9286b/429a801a-7152-4e96-9156-a55e6784b69b)

Sample JSON

>       "veteranIdentification": {
>         "currentlyVaEmployee": false,
>         "mailingAddress": {
>           "numberAndStreet": "1234 Couch Street",
>           "apartmentOrUnitNumber": "22",
>           "city": "Portland",
>           "country": "USA",
>           "zipFirstFive": "41726",
>           "zipLastFour": "1234",
>           "state": "OR"
>         },
>         "serviceNumber": "123456789",
>         "emailAddress": {
>           "email": "valid@somedomain.com",
>           "agreeToEmailRelatedToClaim": true
>         },
>         "veteranNumber": {
>           "telephone": "5555555555",
>           "internationalTelephone": "5555555555"
>         },
>         "vaFileNumber": "AB123CDEF"
>       },
> 

- vaFileNumber is no longer required- LH is autopopulating it on their end
- agreeToEmailRelatedToClaim can be omitted- related to newer version of form

-----
### Current Form526Submission veteran node
```
"veteran": {
            "emailAddress": "string@sdfds.com",
            "currentMailingAddress": {
                "country": "USA",
                "addressLine1": "string",
                "addressLine2": "string",
                "addressLine3": "string",
                "type": "DOMESTIC",
                "city": "string",
                "state": "OR",
                "zipFirstFive": "90210"
            },
            "changeOfAddress": {
                "country": "USA",
                "addressLine1": "string",
                "addressLine2": "string",
                "addressLine3": "string",
                "beginningDate": "2019-10-10",
                "endingDate": "2020-12-31",
                "type": "DOMESTIC",
                "city": "string",
                "state": "OR",
                "zipFirstFive": "92032",
                "addressChangeType": "TEMPORARY"
            },
            "daytimePhone": {
                "areaCode": "619",
                "phoneNumber": "6196199"
            },
            "currentlyVAEmployee": true
        },
```

---
## Tasks
- [x] Resolve open questions on [internationalTelephone](https://docs.google.com/document/d/1Z6Cw6MU5fgsjeJ9vuqrk-4xMEkq3LpQ7NbKUq0KNAyk/edit?disco=AAAA01TwLFg). If EVSS is autopopulating this on the form, then we might need to replicate this logic on our side - _EVSS never populated internationalTelephone. Use concat'd daytime phone, ignore the others_
- [x] Resolve open questions on [pointOfContactNumber](https://docs.google.com/document/d/1Z6Cw6MU5fgsjeJ9vuqrk-4xMEkq3LpQ7NbKUq0KNAyk/edit?disco=AAAA01TwLFo). If EVSS is autopopulating this on the form, then we might need to replicate this logic on our side - _EVSS never populated internationalTelephone. Use concat'd daytime phone, ignore the others_
- [x] Resolve open questions on [type, internationalPostalCode, militaryStateCode and militaryPostOfficeTypeCode](https://docs.google.com/document/d/1Z6Cw6MU5fgsjeJ9vuqrk-4xMEkq3LpQ7NbKUq0KNAyk/edit?disco=AAAA01TwLF0) (as well as their counterparts on the changeOfAddress object) - _LH is ignoring these, discard_
- [x] Confirm treatment of [addressLine3](https://docs.google.com/document/d/1Z6Cw6MU5fgsjeJ9vuqrk-4xMEkq3LpQ7NbKUq0KNAyk/edit?disco=AAAA01TwLFw) - _concat addressLine3 into LH 2nd line of address_
- [x] Confirm with EVSS that [daytimePhone, eveningPhone and cellPhone](https://docs.google.com/document/d/1Z6Cw6MU5fgsjeJ9vuqrk-4xMEkq3LpQ7NbKUq0KNAyk/edit?disco=AAAA01TwLFY) are not needed as separate fields anymore - _confirmed. using daytimePhone only now_
- [x] - Also, we need to choose one of those 3 for the new single telephone number. If a vet has a different number for ANY of those 3 numbers, how should we choose which phone number to send to LH? _daytimePhone_

## Acceptance Criteria
- [ ] Implement the "veteran" service method
- [ ] Supporting unit tests
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
