### ISSUE TITLE
EVSS Migration - 526 Submit - Implement call to BenefitClaims LH submit526 service method from submission service

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#61559]
## Issue Description
Once the BenefitClaims LH submit526 service method has been [implemented](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/62139), as well as the new [transformation service](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/61522) (or at least partially implemented), we need to call out to it before finally posting it to Lighthouse. This will be gated behind the same Flipper flag established in [55953](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/55953) [here](https://github.com/department-of-veterans-affairs/vets-api/blob/c213d2ed6e0184fd6ac1d0732492a66555c5e98d/app/workers/evss/disability_compensation_form/submit_form526.rb#L72)

---
## Tasks
In the job that triggers the form submission, 
- [ ] Call transformation of form 526 submission to LH body
- [ ] Call submit 526 method from benefits claims svc
- [ ] Tests
 

## Acceptance Criteria
- [ ] Implement call to new transform service before sending the request to Lighthouse via the submit526 method
- [ ] Supporting tests
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sethdarragile6** [comment]
NOTE: this will also need to be called from the Form526BackupSubmissionProcess, which [pulls](https://github.com/department-of-veterans-affairs/vets-api/blob/c213d2ed6e0184fd6ac1d0732492a66555c5e98d/lib/sidekiq/form526_backup_submission_process/processor.rb#L54 ) what is (and will continue to be) the EVSS-formatted JSON request from the database submission record. This effort might be better captured in a separate story, since the testing will likely look very different and probably add too much scope to this story.
