### ISSUE TITLE
Github Issues - Add CMS Repo

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#61570]
## Issue Description
The Governance Team needs to add CMS repo data to their Github issues dataset(s) for reporting.  See #58818 for reference to this request.  The new CMS dataset has been created.  We need to combine the 2 into 1 for reporting.  Before bringing into Domo first need to perform ETLs in BQ as doing for current 'vw_governance_github_tickets'.
---
## Tasks
- [ ] Determine best way to combine these 2 datasets so both their auto updates populate into dataset used for reporting
- [ ] Bring into Domo (BQ - Governance Github Tickets) for their [Collab Cycle dashboard](https://va-gov.domo.com/page/1340527018)

## Acceptance Criteria
- [ ] Dataset and dashboard updates complete.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
