### ISSUE TITLE
[Design, FE] 10-10EZ - Improvement: Update on the "Need Help?" footer

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#61574]
## Background
As part of [content feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52920#issuecomment-1615190313) on the Household section feature, it was decided to address the footer update as its own body of work not tied to any feature.  

Content Feedback:
>1. PAGE FOOTER
>https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/aMgPxyA
>- This wasn't part of our initial review, but I noticed that this content isn't aligned with VA style.
>Is this footer component being pulled from someplace else?
>We'd remove the "/" here and refer to this as a form or an application
>![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/22c3ef32-6bc2-4179-b9f6-4e14a2947152)

## Tasks
- [x] Design - Update design to reflect change as described - "remove the "/" here and refer to this as a form or an application"
- [x] Design - Inform Engineers this ticket is ready to pick up and complete
- [x] Engineer - Update content to match updated design - [see comment below](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61574#issuecomment-1642850898)
- [x] Engineer - Validate change in Staging with PM before Prod deployment window
- [ ] PM - Close ticket after validation

## Acceptance Criteria
- "Need Help?" footer content is updated

**Comment by jessicastump** [comment]
The Sketch file has been updated in the [form templates](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/486F6189-77B9-40D1-A130-A4C79B6EA3F5/canvas) page only, not throughout all the footers in the file...

**Comment by longmd** [comment]
@hdjustice / @jessicastump , this is in staging and ready for final sign-off.

**Comment by jessicastump** [comment]
The "form or" can be removed too. It is referred to application elsewhere in the footer so we can keep it consistent with one.

[Sketch File](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/486F6189-77B9-40D1-A130-A4C79B6EA3F5/canvas)
<img width="269" alt="Screenshot 2023-07-25 at 1 47 54 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/26361671-9e8f-4d36-a535-177e4b936f8b">

Staging:
<img width="670" alt="Screenshot 2023-07-25 at 1 48 57 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/9f118581-b7b2-4812-aba1-82adab375f1f">

**Comment by longmd** [comment]
@hdjustice / @jessicastump , this has been further updated and is ready for sign-off.

![Screenshot 2023-07-26 at 2 12 48 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/4d2cb0c1-53e4-444b-8e36-2a3fe517ac36)

**Comment by hdjustice** [comment]
Looks great, thank you Matt!
