### ISSUE TITLE
Print appts list 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#61579]
## Description 

The Appointments/VAOS team is exploring a print feature for the Veteran's appointment list. During the unified check-in research, one Veterans said: 

> "When I check in, I usually ask for a print out of my other appointments. So, this is really helpful and better than getting a piece of paper."

This is also something that was available in Vet Link. 

This Veteran was referring to the process of checking in to their appointment, selecting the "review upcoming appointments" link and then seeing their appt list and wanting to print from their. The Appointments/VAOS team is working on a design for this feature. 

## Tasks

- [ ] Talk to Appointments/VAOS team about their progress and design
- [ ] Create wireframes
- [ ] Document any aria labels that are needed

## AC

- [ ] Wireframes created 
- [ ] Any aria labels that are needed are created
- [ ] Create FE ticket for their work
