### ISSUE TITLE
Remove vanity numbers from several education hub pages and one health care page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#6159]
## User Story or Problem Statement
As a copy editor, I need to remove all vanity numbers from hub pages so VA.gov stays consistent with our style guide.
The following pages still have vanity phone numbers that need to be removed:
- https://www.va.gov/education/about-gi-bill-benefits/montgomery-active-duty/
- https://www.va.gov/education/about-gi-bill-benefits/montgomery-selected-reserve/
- https://www.va.gov/education/how-to-apply/
- https://www.va.gov/health-care/apply/application/introduction (this needs to be done by @ncksllvn)

## Goal
Pages should link just to a regular phone number and not have the vanity one along side it.

## Objectives or Key Results this is meant to further
Style guide consistency

## Tasks
Remove each vanity number on the page in Drupal:
- [x] https://www.va.gov/education/about-gi-bill-benefits/montgomery-active-duty/
- [x]  https://www.va.gov/education/about-gi-bill-benefits/montgomery-selected-reserve/
- [x] https://www.va.gov/education/how-to-apply/
- [x]  https://www.va.gov/health-care/apply/application/introduction (@ncksllvn) 
- [x] Do a search on VA.gov for any other pages still showing vanity numbers and add to this list if more are found.

Update: After searching on VA.gov for other pages, these needed to be corrected too:
- [x] https://www.va.gov/health-care/health-needs-conditions/mental-health/

## Acceptance Criteria
- [x] Live pages show only a regular number and no vanity number.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AkucherGCIO** [comment]
02-27-20 PW Standup
This is likely to be done today.

**Comment by RLHecht** [comment]
@ncksllvn or @kelsonic Do you know where this page lives? https://www.va.gov/health-care/apply/application/introduction

I need to remove the vanity phone number. It's not in Drupal and I don't see it in Github though I might not be looking in the right area. 

I need to delete the 877-222-VETS number as well as the parentheses around the regular phone number shown in this screen shot: ![Screen Shot 2020-02-27 at 12.12.09 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/7058b8a6-15c8-4611-8aca-db68a51443f0)

**Comment by ncksllvn** [comment]
Hey @RLHecht, that content is in the front-end code. The whole form is a React application. I can do that for you if you want to assign me.

**Comment by AkucherGCIO** [comment]
2020-28-02 Standup
Randi is working on searching on vanity numbers and assigned to Nick.

**Comment by ncksllvn** [comment]
@RLHecht I see that VETS number listed in a few places in the Healthcare Application. Should I remove it from only the introduction page, or all areas?

**Comment by ncksllvn** [comment]
Per the acceptance criteria, I removed the vanity number across other areas of the site too. This includes -

1. The "Appeals help sidebar" of the Claims Status app
1. The "unemployment disabilities" section of the All Claims app
1. The downtime message of the HCA
1. The error message of the HCA
1. The subway map of HCA (on intro page)
1. The confirmation page of the HCA
1. The verification alert on the intro page of the HCA
1. The maintenance message of the HCA (likely never used anymore)
1. Some content in Letters that begins with `If you’ve lost your IRS Form 1095-B`
1. The confirmation page of Pre-needs
1. The confirmation page of VRE

**Comment by RLHecht** [comment]
Thanks, @ncksllvn I don't think your list above is including this, but we should leave the vanity number in the right rail  like how it is on the health care hub landing page: 
<img width="457" alt="Screen Shot 2020-03-02 at 11 05 34 AM" src="https://user-images.githubusercontent.com/48728214/75693977-cbe60580-5c75-11ea-9bf0-cbc270ac0b50.png">

**Comment by ncksllvn** [comment]
@RLHecht What about on this page? 

![image](https://user-images.githubusercontent.com/1915775/75694501-9db4f580-5c76-11ea-9ecb-d1cccc2d06a4.png)

I remove the VETS number from the right sidebar already, but I can undo it.

**Comment by RLHecht** [comment]
@ncksllvn I think that needs to stay as the vanity number. Sorry about that. @jenniferlee-dsva Can you confirm this? I know the style guide says to leave the vanity number in the right rail component and for marketing purposes. I believe this qualifies.

**Comment by ncksllvn** [comment]
Thanks @RLHecht, I undid the change

**Comment by ncksllvn** [comment]
Oh wait, ugh, I got mixed up. The screenshot I posted is from dev.va.gov, not my local website. So the sidebar shown there is actually what is currently live. Hm...so then what code did I edit originally? Lol. Looking into this.

**Comment by ncksllvn** [comment]
Looks like I was editing the VHA version of the Appeals sidebar. The screenshot is the VBA version. I don't understand the conditions behind the dynamic behavior but something with the acronym "AOJ." I think I'm just going to leave this code alone.

**Comment by AkucherGCIO** [comment]
- Failing end to end test.

**Comment by jenniferlee-dsva** [comment]
RE march 2 question from @RLHecht 
>@ncksllvn I think that needs to stay as the vanity number. Sorry about that. @jenniferlee-dsva Can you confirm this? I know the style guide says to leave the vanity number in the right rail component and for marketing purposes. I believe this qualifies.

That's right. The 'no vanity number' style is for copy in the body of the page. Right rail components:  because it's sort of the self-promoting escape valve for VA businesses, needs to allow vanity numbers if they have one.

**Comment by RLHecht** [comment]
@ncksllvn Just confirming I can move this to validate and will close ticket once I see the live changes to the health care application page. Wasn't sure if there was more work for you to do on it.

**Comment by ncksllvn** [comment]
Yeah, it's still waiting for a review, but I'll keep you posted. Hopefully it'll be merged today.

**Comment by ncksllvn** [comment]
PR is merged now - should go live today @RLHecht

**Comment by RLHecht** [comment]
All changes validated on live site. Closing ticket. @AkucherGCIO FYSA.
