### ISSUE TITLE
[SPIKE] Is there an issue navigating months on the appt list for screen readers? 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#61604]
## Description 

Determine if the following feedback is and issue that needs to be addressed. For example, isn't there an option for screen readers to tab between headings. And, if so, would this still be an issue? 

> "If there was just a dropdown for the month, that would be better for me. It's a problem using a screen reader. If it was a whole year's worth of appointments, that's a lot of swiping."

## Tasks

- [ ] Meet with Appointments/VAOS to discuss. Bring in a11y team members. 
- [ ] Determine if it's an issue
- [ ] Determine solution
- [ ] Create ticket for next step / implementation 

## AC

- [ ] Determine if it's an issue
- [ ] Determine solution
- [ ] Create ticket for next step / implementation

**Comment by cgednalske** [comment]
@ytsaoca here is the [accessibility feedback](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/2023-04%20Unified%20Check-In%20Experience%20Usability%20Study/accessibility-findings-mhv-pci.md) from the a11y specialists involved in the study - for us to talk through in our meeting today.

**Comment by cgednalske** [comment]
@benbrasso-agile6 @loripusey -- @ytsaoca and I discussed this with a11y folks, the Appointments team designers, and Kristen McConnell. This is something we need to address, but is not launch blocking. Level 3.5 defect. Angela Fowler, Sarah Smith, and SK provided a few different possible solutions. ([notes for more info](https://dsva.slack.com/docs/T03FECE8V/F05KZNLA71U))

Our team needs to discuss with Lori and add this to the backlog, per Kristen’s instructions. Appointments will likely take the lead, with past appointments making most sense as a starting point, but both teams needs to keep this in mind.

**Comment by benbrasso-agile6** [comment]
Cool, sounds like maybe a tech debt ticket for now in our backlog, and wait for Appointments team or direction from Kristen.

**Comment by cgednalske** [comment]
@benbrasso-agile6 let me know that this might still be a bit ambiguous, so definitely let us know if there are questions.

**Comment by cgednalske** [comment]
@benbrasso-agile6 yep! That's really our only action item at the moment 🙂

**Comment by loripusey** [comment]
here's the tech debt [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63121)

**Comment by benbrasso-agile6** [comment]
ty

**Comment by cgednalske** [comment]
Thank you, @loripusey!
