### ISSUE TITLE
Conduct user search expectations research

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#6160]
## User Story
As a Veteran, I need the Facility Locator to return meaningful results to my search so I can select a facility which will meet my need.

## Goals
Learn from Veterans about their search expectations for map interaction, defaults and facility detail information to inform our search iterations.
Learn how expectations for search differ based on geographic area (rural vs urban)
Learn how expectations for search differ based on device (mobile vs desktop)

## Tasks
[ ] Conduct research sessions with 10+ participants representing rural and urban settings, preferably with a mix of mobile and desktop experience.

Acceptance Criteria
[ ] Notes from research sessions to inform synthesis

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Topline Summary is complete: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/FL-Search-march2020/topline-summary.md
