### ISSUE TITLE
Add to my calendar feature

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#61606]
## Description 

On the pre-check-in confirmation page, as well as pre-check-in appt detail pages, add the ability for Veterans to add the appt to their calendar. 

> "Add to my calendar would be nice." 

This is a feature that Appointments/VAOS either has or is working on. 

## Tasks

- [ ] Meet with Appointments/VAOS to discuss implementation and design 
- [ ] Create wireframes
- [ ] Annotate aria labels as needed 

## AC

- [ ] Meet with Appointments/VAOS to discuss implementation and design 
- [ ] Create wireframes
- [ ] Annotate aria labels as needed 
- [ ] Create FE ticket to begin the work
