### ISSUE TITLE
Add street address info to style guide

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#6161]
## User Story or Problem Statement
As a content writer/editor, I need to know how to style street addresses on VA.gov so I can be consistent with our style guide.

PR: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/175

## Goal
Specific information about how to style street addresses added to the abbreviations and acronyms section of the style guide.

## Objectives or Key Results this is meant to further
- Eliminate confusion and make website consistent with style guide
---
## Tasks
- [x] Write style guide entry about street addresses to be added to the dates, times, and phone numbers section. 
- [x] Write sentence in abbreviations and acronyms section explaining that our general approach is aligned with AP Style.

The rule is that we spell out all types of streets (street, road, boulevard, highway etc.) in both running text and as an address block.
When referring to compass points, we defer to what is common locally. Example: Streets in Washington, D.C., are followed by NW, SW, etc. These should be abbreviated. This naming may not be familiar in other locations and therefore it should be spelled out.

## Acceptance Criteria
- [ ] New information added to style guide.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@jenniferlee-dsva I just added the address entry in the dates, times, and phone numbers section. Let me know what you think. I went back and forth on the compass points before a street name since I'm thinking it's usually just north, south, east, or west, and that doesn't look weird spelled out. But if you think it will look off to have something like Northwest 29th Street, I can delete the sentence and stick with the info I say for compass points that come after the address.

**Comment by AkucherGCIO** [comment]
03/04/20 PW Standup
Jen is reviewing the PR and then we will merge it.

**Comment by RLHecht** [comment]
Jen reviewed this PR. Will validate when on the live site later this afternoon. @AkucherGCIO FYSA

**Comment by RLHecht** [comment]
Validated on live site. Closing ticket. @AkucherGCIO FYSA
