### ISSUE TITLE
Add message for video appointments missing link to join

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#61613]
## Task Description
Some facilities have clinics setup for direct scheduling and video visit.  When veterans schedule in these clinics, the video visit is not setup.  The end result is veterans looking at the details of their appointment will not see a link to join the video visit.

## Notes and References
- The engineering team will be creating a filter to prevent veterans from selecting these types of clinics going forward, but in the meant time Kay Lawyer is requesting a message be created to instruct the veterans how to proceed.

## Acceptance Criteria
- [ ] New message is created explaining to veterans how to find the link to their video visit.

## Deliverables
- If appointment is a video visit and no video link is present the veteran with a message on how to proceed.
- [ ] Design of message
- [ ] Creation of text

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
