### ISSUE TITLE
[EPIC] Collaboration Cycle for Sitewide Facilities: Facility Locator Services Autosuggest + Progressive Disclosure

### ISSUE THREAD

**Issue by thejordanwood** [department-of-veterans-affairs/va.gov-team#61610]
### VFS team name

Sitewide Facilities

### Product name

Facility Locator

### Feature name

Improve search, add filters

### GitHub label for product

Facility Locator

<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

May 2023

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Tools, applications and dynamic pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Unsure

### Do you need to capture any additional analytics or metrics?

Unsure

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/README.md

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Notify the Collaboration Cycle team of this ticket in the vfs-platform-support Slack channel.

- [X] I acknowledge that I must notify \#vfs-platform-support after submitting this issue.
- 
[Slack request thread](https://dsva.slack.com/archives/CBU0KDSB1/p1688751112839329)

</details>

### Design Intent - DONE 7/18/24
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- [ ] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [ ] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [ ] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.

**Design Intent artifacts**

See Platform guidance on [Design Intent artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Design Intent meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

- [x] [User flow](https://sketch.com/s/d5e5c924-e8c0-47af-b3e4-994c335d6f31) (required)
- [x] Whiteboard sketch or other lo-fi prototypes or wireframes (Same as user flow Sketch file)
- [ ] Research plan
- [x] [Initiative Brief - Facility Locator Search Improvements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/initiatives/2023-search-improvements/2023-initiative-brief.md)
- [x] [KPIs are defined](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/search%20improvements/2023-initiative-brief.md#relevant-facilities-team-okrs) with baseline analytics pending
  
##### Platform actions
- [x][ Slack request](https://dsva.slack.com/archives/CBU0KDSB1/p1688766453005669)
- [x] Meeting date/time: **Tuesday, July 18 at 11:30AM Eastern**
  
##### Platform actions

- [ ] If you have feedback, create feedback tickets and link to this epic. Once you have completed you review, check the box next to your practice area
  - [x] Accessibility has completed the review
  - [ ] Design has completed the review
  - [ ] IA has completed the review
- [ ] Update this ticket with the Zoom recording
  - Recording URL: [Zoom link](https://oddball-io.zoom.us/rec/share/OFCIARM-cQSCK5J_hBFyDtxPu1rhkoDoQXN8uu_GysuOyWlKESzm0EcXbtHNfg_y.cf74yMTTACt20KXQ)
  - Password: W*eqEf6&
  
##### VFS actions

- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Sitewide Content and IA Intake Request
<details>
  <summary>Toggle Sitewide Content and IA Intake Request</summary>

##### VFS actions
- [ ] Complete the [sitewide content and IA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-Content-and-IA-intake-request.2124906551.html)
- [ ] Link to the Sitewide Content and IA Intake Request ticket below

</details>

### Architecture Intent - SKIPPED no new architecture
<details>
  <summary>Toggle Architecture Intent instructions</summary>

##### VFS team actions
- [ ] Review [Architecture Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/architecture-intent) to understand what this touchpoint involves.
- [ ] Schedule your Architecture Intent (with at least 2 business days lead time from now):
  - Open the [Calendly Architecture intent calendar](https://calendly.com/collaboration-cycle/architecture-intent)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [ ] Link all artifacts in the `Architecture Intent artifacts for review` section below at least two business days before the scheduled Architecture Intent. Please don't add artifacts in the comments section.
  
**Architecture Intent artifacts for review**

[See guidance on Architecture Intent artifacts.](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/architecture-intent#ArchitectureIntent-Whatartifactswillbeneeded?) Feedback is based on the artifacts provided here as well as information provided during the meeting. Please provide links to artifacts **at least two business days** before the scheduled meeting.

Required:
- [ ] Fully completed [Architecture Intent Meeting Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/collab-cycle/architecture-intent-meeting.md)
- [ ] [User data flow diagram](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-create-a-user-data-flow-diagram.md), if your application accepts data from a user.

##### Platform Team actions
- [ ] Meeting date/time:

##### Platform Team actions

- [ ] Update this ticket with the Zoom recording
  - Recording link
  - Passcode:
- Engineering feedback
  - [ ] Feedback ticket attached to milestone
  - [ ] No feedback
- Mobile Engineering feedback
  - [ ] Feedback ticket attached to milestone
  - [ ] No feedback
- Security feedback
  - [ ] Feedback ticket attached to milestone
  - [ ] No feedback  

##### VFS team actions

- [ ] Review feedback tickets. Comment on the ticket if there are any questions or concerns.
</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [ ] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review - DONE 8/17/24

<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [ ] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

**Required artifacts**
- [x] Design prototype or high-fidelity mockup (must include mobile prototype/mockup)
  - Autosuggest: https://www.figma.com/design/GvNVeG9GAXZaBpny7vNxZP/Facility-Locator?node-id=1496-38390&p=f&t=RLLSB7xwcEEeQRik-0
  - Progressive Disclosure: https://www.figma.com/design/GvNVeG9GAXZaBpny7vNxZP/Facility-Locator?node-id=806-27055&p=f&t=RLLSB7xwcEEeQRik-0
- [x] Up to date user flow
  - [Guidance on user flows](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/standards/user-flow-guidance.md)
- [ ] If working with [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request), link to CAIA intake ticket. 

**Not required, but nice to have artifacts**
- [ ] Accessibility annotations included as part of your design
- [ ] Research plan
- Links to specific CAIA artifacts:
  - [ ] IA spec
  - [ ] Content source of truth
- Any other artifacts you have so far
 
##### Platform actions
- [x] [Slack thread with VFS team
](https://dsva.slack.com/archives/C0FQSS30V/p1737469022312389)
- [x] Meeting date/time: 02:00pm - Friday, January 24, 2025 (Eastern Time - US & Canada)

##### Platform actions

* Accessibility
  * [x] Feedback added to milestone
  * [ ] No feedback
* Content
  * [ ] Feedback added to milestone
  * [ ] No feedback
* Design
  * [x] Feedback added to milestone
  * [ ] No feedback
* IA
  * [ ] Feedback added to milestone
  * [x] No feedback
* [x] Update this ticket with the Zoom recording
  - [Midpoint review recording](https://oddball-io.zoom.us/rec/share/SZkgYGQI0kwbyRB8_LQ57dSk7LqHRvXNTZQrvJ7iE8kXqThTwiNwqjpOYXwIvcA.icNH9fUWlaAISUXM)
  - Passcode: `Jh^Z*97s`
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns

</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [ ] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [ ] Link to the Analytics Implementation and QA Request ticket below

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [ ] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [ ] Link to the Contact Center review request ticket below

</details>

### Staging Review

<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [ ] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] If this product contains any [experimental design](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [ ] I confirm the environment is available and test users have been provided.
- [ ] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
 
**Staging Review artifacts**

Links to [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts) must be added to this ticket 4 business days ahead of the scheduled meeting. Please do not make changes to the product or artifacts during the 4-day review period. 

**Required artifacts**
- [ ] **Direct link or instructions on how to access the product**
  - The product should be available on an [approved staging environment](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-environment-guidance-for-vfs-teams). 
  - List screens, sections of screens, and/or user flows impacted by this work.
- [ ] **Generated PDF form** (when applicable)
  - A populated version of the form that will be submitted through the online tool 
- [ ] **Drupal or Staging URL for updated primary entry point:** the main way Veterans will access the tool through site navigation (not search)
  - If the primary entry point is not a page on VA.gov, include information about how to view it. Reach out to `@platform-governance-team-members` on Slack with any questions.
- [ ] **Test users and scenarios** (when applicable)
  - Store [test user information](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md), passwords, and tasks in a .md file in the va.gov-team-sensitive repository. 
  - Make sure all user scenarios can be tested, i.e.: in-progress form, submitted form, new form.
- [ ] **Link to Sitewide CAIA intake ticket**, if applicable.
- [ ] **Completed accessibility testing artifact:** see [instructions and link to accessibility testing template](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).
- [ ] **QA Artifacts:** artifacts that correspond to each of the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
  - [ ] Regression test plan
  - [ ] Test plan
  - [ ] Coverage for References
  - [ ] Summary (Defects) reports
  - [ ] E2E tests
  - [ ] Code coverage
  - [ ] Endpoint monitoring playbook
  - [ ] Logging silent failures
- [ ] Completed **[Engineering and Security Checklist](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/engineering/collaboration-cycle/architecture-intent/checklist/eng-sec-checklist.md)**

**Not required, but nice to have artifacts**
- [ ] **Content source of truth:** link to CAIA Content feedback, such as a content source of truth.
- [ ] **Information Architecture spec:** link to CAIA IA feedback, such as an IA spec.
  
##### Platform actions
- [ ] Slack thread with VFS team
- [ ] Meeting date/time:

##### Platform actions

- [ ] Update this ticket with the Zoom recording
  - Recording link 
  - Password:
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
- [ ] [Complete Collaboration Cycle feedback survey](https://ows.io/qs/gb1dfnkl)

</details>

**Comment by davidmpickett** [comment]
@Agile6MSkinner This epic should remain open. This collab cycle ticket is what we will need to use when we're ready to take the Mobile Map / Autosuggest improvements to Midpoint.

**Comment by jilladams** [comment]
(No open issues in the epic, re: my Zenhub > Github Projects migration process. But: should still stay open til we get to midpoint.)

**Comment by thejordanwood** [comment]
@strelichl Looks like the file was renamed. Here's the [updated link to the initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/initiatives/2023-search-improvements/2023-initiative-brief.md) and I also updated the link in the ticket.

**Comment by jilladams** [comment]
## 2025 update (DRAFT)
This project originally included a variety of updates to the Facility Locator that we intended to ship at once. We have broken that apart and put it back together in a few formations since 2023. Currently, we are working on 3 distinct features that we think will be bundled into 2 research studies: 

## Research study 1
The two features below will be exposed on Staging and researched together.

### Progressive Disclosure 
**Change**: The Services dropdown on https://www.va.gov/find-locations will be updated to only display when it is selectable. Meaning: it will no longer displayed as disabled, if you are filtering by a Facility type that does not have Services.

Epic: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19489


### Services Autosuggest
**Change**: The Services dropdown on https://www.va.gov/find-locations will be updated to allow users to type service terms, and the combo box component will be used to suggest potential Service term matches. 

Epic: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15541

## Research study 2: Facility Locator mobile map
**Change**: We will update the FL mobile map template with a variety of design and usability improvements. This will also be built in Staging, and researched separately. 

Epic: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16001

## Questions for Governance
@shiragoodman questions for you, in light of all that:
1. Is it ok to keep all this stuff in the same CC ticket, or should we start a separate CC process for the Mobile Map work? 
2. We need to schedule Mid Point review of Progressive Disclosure + Services Autosuggest work, and have the designs ready, but do not yet have this work built in Staging as a prototype for research. Should we midpoint before or after the Staging build is ready?

**Comment by shiragoodman** [comment]
Hey @jilladams  - It might be easier for us, and you'll likely get more value from your touchpoints, if the mobile map work is broken out, especially if you're not planning on shipping together. I would recommend you open a new kickoff for that work, and feel free to update the title of this ticket to reflect the current work.

It's up to you whether you'd like to have the Midpoint Review now or wait until the prototype is ready. Our [guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#MidpointReview-Requiredartifacts) states that we require either the prototype or a high-fidelity mockup, but we're pretty flexible. We will only block you from coming to Midpoint if you don't provide anything.

**Comment by jilladams** [comment]
Perfect, thanks. I've renamed this ticket, and we will file a separate one for Mobile Map, when we are ready for that.

**Comment by jilladams** [comment]
@humancompanion-usds FYI that team verified we have already reviewed the 526EZ combo box build and it doesn't meet our need. I filed a new Experimental design ticket with our use cases here: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3742

**Comment by r-bartlett-gsa** [comment]
Closing since all sub-issues are completed and closed

**Comment by shiragoodman** [comment]
@JonathanKatora is this something you can respond to? ^
