### ISSUE TITLE
Update 686c Incapable of Self Support Question

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#61621]
## Issue Description
Many Veterans are misunderstanding and marking their minor children as “incapable of self support” (formerly known as Helpless) when the child does not qualify as "helpless". The way the question is current worded on VA.gov lead the Veteran to mark the child as helpless because the child is under 18 and is a minor. VBA requested that the question be clarified, so vets know it is referring to a disabled child, not minor children.

For reference: [Screenshot of full page in mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687976281975/2a9c6ca9ea6d955afa7977c777bbb72b15280903?wid=226-1687976590186)

Paper 686c checkbox wording: `Child permanently incapable of self-support`
Current question wording on VA.gov: Is this child not capable of self-support? y/n
Suggested language change (from James Landers): Is this child not capable of self-support due to a mental/physical disability?

---
## Tasks
- [x] Check the style guide
- [x] Check with Julie S. for input on recommendation & whether we need CAIA input
- [ ] Make the recommendation and pass off to engineering.

## Acceptance Criteria
- [ ] Design for engineering to action.
---

<img width="549" alt="b-686c-not-capable-of-self-support-addl-info" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/134541644/e1aff764-8949-46b3-95eb-e7e6ad6f3253">
<img width="549" alt="b-686c-not-capable-of-self-support" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/134541644/7229ef74-697f-4e9d-b5bd-8e5409458177">

**Comment by djones2113** [comment]
Based on my understanding, the recommendation, "Is this child not capable of self-support due to a mental or physical disability?" is in line with the style guide. 

@jstrothman do you think that this change requires input from CAIA or others before passing off to engineering?

**Comment by jstrothman** [comment]
@djones2113 
I'd like to make the changes below. One of us should go to CAIA office hours Thurs 3-3:30 pm to see if they recommend any further adjustments. I'll message you on Slack to figure out which of us is available to go. 

Change question to:
"Is this child permanently unable to support themself because of a mental or physical disability?"

Change the additional info component to:
trigger: 

> What does VA mean by unable to support themself?

additional info content: 

> To be considered a **child unable to support themself**, the child must be:
(bullets are unchanged)
To add a child who is unable to support themself, you'll need to provide:
(bullets are unchanged)

Screenshot above in issue has screenshot with bullets that will remain unchanged

**Comment by jstrothman** [comment]
@bethpotts took a look at the content suggestions, and we have content we can move forward with!

Change question to:

> Is this child permanently unable to support themself because of a mental or physical disability?

Change the additional info component to:
trigger:

> What does "unable to support themself" mean?

additional info content:

> We consider a child to be unable to support themself if both of these are true:
> 
> * The child has a diagnosed physical or mental disability that makes them unable to support themself, and
> * The child is permanently disabled
> 
> To add this child as a dependent, you'll need to provide this evidence:
> * Medical evidence that shows a permanent physical or mental disability, and
> * A statement from your child's doctor that shows the type and severity of the child's physical or mental condition

**Comment by sortizsh** [comment]
this is ready for eng

**Comment by steele-lm** [comment]
@tfink419 Checking on Cypress tests.
