### ISSUE TITLE
[Design, FE] 10-10EZ - Household section: Content updates from pre-staging review

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#61632]
## Background
Per the latest [content review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52920#issuecomment-1625940947) in ticket #52920, the following updates need to be implemented:

---

**FINANCIAL INFO YOU WILL NEED PAGE**
[Sketch](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/L40m0nd)
**MUST** Remove references of "your" and add in "annual".

<img width="284" alt="Screenshot 2023-07-07 at 2 03 21 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/12311662-b343-4901-8461-d4c5e6693cdb">

---

**SPOUSE ADDITIONAL INFORMATION PAGE**
https://staging.va.gov/health-care/apply/application/household-information-v2/spouse-additional-information
https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/Eeeqyyd
- **SHOULD** Adjustment to second question to state "Do you currently have the same address as your spouse?"

<img width="413" alt="Screenshot 2023-07-07 at 2 05 53 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/b03c9ac0-0071-4240-919b-609c6785a68a">

---

**SPOUSE FINANCIAL SUPPORT PAGE**
https://staging.va.gov/health-care/apply/application/household-information-v2/spouse-financial-support
https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/ZVVJGwZ

SHOULD
- Add 'additional info component'  

<img width="334" alt="Screenshot 2023-07-07 at 2 08 23 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/e3ad0cac-4311-4b0d-98be-2041d70cf98a">

---

**ADD/REVIEW DEPENDENT PAGES** 
https://staging.va.gov/health-care/apply/application/household-information-v2/dependents
https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/AZxwR8r?annotation=4fa3c0d4-fe3a-4a06-bc58-9c914708a1c8

Changes to **additional info component content** - NOTE this is also used on the Review Dependents page and same updates need to be made there
 
- **MUST** - correcting a potential typo and also adding the school types, because they're on the form
_They're between the ages of 18 and 23 years old and were enrolled as a full-time or part-time student in high school, college, or vocational school in 2022_
- **MUST** - VA site style/style standards uses "years old" after age.

<img width="257" alt="Screenshot 2023-07-07 at 2 09 57 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/05f5078c-430c-452c-a877-7f7e2ea3dd2a">

---
**CANCEL ADDING THIS DEPENDENT MODAL**
https://staging.va.gov/health-care/apply/application/household-information-v2/dependent-information?index=0
https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/bLLq59z
- **MUST** - adjust the content re: the screen that they'll go back to if they cancel adding. Content on this screen needs to match the action if they go back/cancel. 
- **SHOULD** - modal title change - if this can happen after staging, that would be great. This is a pattern being used in secure messaging/health tools work as well).

<img width="348" alt="Screenshot 2023-07-07 at 2 12 07 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/da364f16-e466-4214-8df6-9f67c55f2208">

--- 

**DEPENDENT EDUCATION EXPENSES INFORMATION PAGE** 
[Sketch](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/ZVJ5A13)

SHOULD: full-time or **part-time student** in 2022?

<img width="303" alt="Screenshot 2023-07-07 at 2 13 17 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/3190437a-5117-42f3-b178-a81d624c52b6">

--- 

**DEPENDENT ADDITIONAL INFORMATION PAGE** 
https://staging.va.gov/health-care/apply/application/household-information-v2/dependent-information?index=0
https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/nQQldKk

- **MUST** 
     - Change first question to this (aligning with the dependent additional info component): _Is your dependent living with a permanent disability that happened before they turned 18 **years old?**_ 
  
<img width="303" alt="Screenshot 2023-07-07 at 2 15 52 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/83629463-772c-438c-9b85-c4544f41662f">

---

**DEPENDENT'S SUPPORT PAGE**

- SHOULD - Adjustments to additional info label and content (add dependent content to title and remove spousal support from content)
- 
<img width="347" alt="Screenshot 2023-07-07 at 2 23 22 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/1a0659f0-6c81-4514-bd5b-1a1a014a8364">

---

**DEPENDENT'S INCOME**
https://staging.va.gov/health-care/apply/application/household-information-v2/dependent-information?index=0
https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/WddpxZ0

- **MUST/SHOULD** - getting rid of some of the repetition here. If changes can happen post staging, adjust content then
     - Changes to the field titles – removing the dependent each time
- **MUST/SHOULD** - removed instances of "your" because these screens are for the Veteran and then dependent/spouse information. We should be consistent across the screens
     - Adjustments to the additional info components

<img width="177" alt="Screenshot 2023-07-07 at 2 24 47 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/a53e9340-afd9-4c8a-b3be-2b30d38d02b1">

---

**REMOVE THIS DEPENDENT MODAL** 
https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/dggqLRZ
- **SHOULD** - this can happen post staging
     - Following new content pattern, leading this a question for this confirmation modal 
    
<img width="330" alt="Screenshot 2023-07-07 at 2 36 03 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/7ccd508d-7ae6-48fb-a2fb-e25471ee880f">

---

**INCOME PAGES - VETERAN AND SPOUSE**
https://staging.va.gov/health-care/apply/application/household-information-v2/veteran-annual-income
https://staging.va.gov/health-care/apply/application/household-information-v2/spouse-annual-income
https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/3oKK9zd?annotation=c767b014-309a-4c87-b07e-f41260cf7e0b
https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/r9qq3VK

- **MUST/SHOULD** - similar to dependent income screen, Remove instances of "your" in field notes/text, remove spouse/your from field titles, make sure field labels is where "your spouse' is used. 

VETERAN INCOME: 
<img width="281" alt="Screenshot 2023-07-07 at 2 28 29 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/10dc9cd7-bed1-4f3a-aea4-76eaabcc365d">

<img width="281" alt="Screenshot 2023-07-07 at 2 28 38 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/342be37d-ef4e-456f-b564-a00c54edae26">

<img width="251" alt="Screenshot 2023-07-07 at 2 29 34 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/c982fb4f-3ebf-4b75-87c9-84c2636e4b5e">

SPOUSE INCOME: 
- Change to page header, remove Your
- Spouse's annual income from 2022

<img width="276" alt="Screenshot 2023-07-07 at 2 34 14 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/3ca8c3b7-6696-4f0c-907e-492059e236fa">

<img width="276" alt="Screenshot 2023-07-07 at 2 34 21 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/c4166f15-fac8-489c-81ba-72039012087e">

<img width="276" alt="Screenshot 2023-07-07 at 2 34 35 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/09a0ccd5-2561-441d-b518-d9c3da79bc05">

---

**DEDUCTIBLES**
https://staging.va.gov/health-care/apply/application/household-information-v2/deductible-expenses
https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/JA88E27
- **MUST/SHOULD** - Typo on 'change' to 'changes' in medical expenses additional info component. Additional sentence added after bulleted list.

<img width="330" alt="Screenshot 2023-07-07 at 2 39 51 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/08a97116-00a2-4a30-b265-bf2518e0664c">

----

## Tasks
- [x] Design - update designs per feedback above
- [x] Design - Inform Engineer this ticket is ready to pick up and complete
- [x] Engineer - implement design updates
- [x] Engineer - validate with PM on changes
- [ ] PM - validate and close ticket

## Acceptance Criteria
- Content review designs are updated and code changes are implemented, as described

**Comment by aliyahblackmore** [comment]
Hi @hdjustice and @jessicastump just tracking that were some adjustments to feedback during our call earlier - they're tracked in the Sketch QA comments! 

Summary here: 
- The footer, confirmation screen, and drop down list content/questions will be addressed in a future ticket/work. We documented this on the corresponding sketch screens. And there are tickets that'll be opened for these things.
- All of the other content adjustments on the sketch screens will be added/changes and then engineers will get those through to staging, in time for the staging review artifact deadline.

**Comment by hdjustice** [comment]
Got it, thanks @aliyahblackmore !

**Comment by jessicastump** [comment]
Hi! -
@aliyahblackmore Please make sure that the [Sketch QA page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/12B7255E-72F6-4C6A-83C3-81BF9A1CEBDE/canvas) (MOBILE only for now - I will work on Desktop screens next) should have all MUST/SHOULD content changes made and accounted for. Everything is also in this ticket description and I added screen captures. 

@hdjustice and @longmd - Pending Aliyah's confirmation, all content changes are in this ticket/Sketch QA page.

**Comment by aliyahblackmore** [comment]
Hi @jessicastump! I'll take a look at these later this evening. I'll comment in this ticket if there are any missing changes. 

Thank you!

**Comment by aliyahblackmore** [comment]
Hi @jessicastump! I did a review of all of the screens with your edits to the must/should changes above/in the sketch comments. They look great.

Sharing one last change below, once that's made- this has my confirmation that **everything is accounted for**!

Thanks again for your continued collaboration on this work!

### ONE LAST CHANGE pre-staging:

On the DEPENDENT'S SUPPORT PAGE, since this screen is only being shown if the Veteran has a dependent who is an unmarried child (we clarified in our conversation earlier this afternoon) then we should adjust the additional information header slightly to be this: 

_**What we consider financial support for a dependent child**_

If my understanding here is not accurate re: the flow, there is still one small change to the component header - to put "dependent" after: 

**_What we consider financial support **for a dependent**_**

This edit more closely aligns with the additional info component on the spouse financial support screen. 

I tracked this on the [sketch screen](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/mPPqJ2L). 
<img width="1111" alt="Screen Shot 2023-07-07 at 9 06 25 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/102090263/e5128356-7abc-493f-b685-e6d6f5da3705">

**Comment by jessicastump** [comment]
@longmd - This ticket is ready with the final content must edits. I am working on updating the desktop screens in the Sketch file this am, but the mobile screens and this ticket has everything.

**Comment by longmd** [comment]
@jessicastump , are these only musts? If there are shoulds that we could knock out that are small, we can go ahead with those, too.

**Comment by jessicastump** [comment]
@longmd - Must and shoulds are both included here. The coulds will all be new tickets.

**Comment by longmd** [comment]
@jessicastump , on the cancel modal... do we need to adjust the description for cancelling an edit action to match that of the add action? Currently for edit it says `This will stop editing {dependentName}. You will return to a list of any previously added dependents and your edits will not be applied.`

**Comment by longmd** [comment]
@jessicastump , there is also still one spot where we reference "last year" instead of the actual year number in the dependent section. `If your dependent didn't live with you last year, did you provide financial support?`. Does that need to be changed to the year number, too, to be consistent with the entire rest of the section?

**Comment by jessicastump** [comment]
@longmd - For the cancel modal, yes there is new description text reading: 

> If you cancel adding this dependent, we won’t save their information. You’ll return to a screen where you can add or remove dependents. 

@aliyahblackmore Can you please confirm if we should leave this question as is or change `last year` to `in 2022`:

> If your dependent didn't live with you last year, did you provide financial support?

**Comment by longmd** [comment]
@jessicastump , we have a different description for canceling adding a new dependent and editing an existing dependent. My question is, do we need to change the edit description--listed in my comment above--to more closely match that new description for the add action?

**Comment by jessicastump** [comment]
Thank you for calling this out!

**Comment by longmd** [comment]
@hdjustice / @jessicastump , these have been completed and are ready for your final review and signoff.

**Comment by jessicastump** [comment]
@longmd I went through staging a couple of times and I believe all content changes are accounted for!

**Comment by hdjustice** [comment]
I am good with this.  Thank you both so much for the quick turnaround!
