### ISSUE TITLE
Update wireframes with confirmation status solution 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#61635]
## Tasks

- [ ] Update wireframes with confirmation status solution 
- [ ] Update symbols and annotations, as needed

## AC

- [ ] Update wireframes with confirmation status solution 
- [ ] Update symbols and annotations, as needed

**Comment by benbrasso-agile6** [comment]
Validated, looks good @ytsaoca
