### ISSUE TITLE
Create Issue Template for Tier 1 Support 

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#61637]
## Description 
A github issue template would make creating tickets simpler for the team by giving uniform fields to fill in, so a template will be created! 

---

## Definition of Done
To complete this task, a template must be drafted, approved, and saved to the va.gov-team github and instructions for use should be shared. 

---

## Tasks 
- [x] Confirm template can be created 
- [x] Draft initial template using existing tickets
- [x] Obtain and apply feedback from Platform Support Team 
- [x] Create final template md file. 
- [x] Produce example of usage of live template. 

--- 

## Resources & Additional Info 
N/A

---

**Comment by lindsay-insco** [comment]
Template created and uploaded to issues folder in GH

![Screenshot 2023-07-18 at 2.35.15 PM.png](https://images.zenhubusercontent.com/613a5fe6c2664a3a7db92373/60499f6a-023b-4036-97b7-833c58361d81)
