### ISSUE TITLE
[FE, BE] 10-10EZR - Standalone form: Create diagrams and other engineering documentation for the Privacy, Security and Infrastructure review

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#61646]
## Background
Now that development is done and all connections are made, we can create diagrams and other required documentation for the Privacy, Security & Infrastructure review.

### Required Information
**We must be able to answer these questions:**

* Please describe a plan to monitor this code base after deployment, including the following scenarios (_NOTE: If you don't (yet) have such a plan, or don't know how to get started with one, we can work on this with you!_).
    * The code base is compromised at source- or run-time.
        * How does the code base get disabled in the product?
        * How would you detect a compromise?
        * What process and privilege does the code base execute under?
            * If so, is that process isolated?
            * If so, what additional credentials are available to that process?
        * The code base is infiltrated or ex-filtrated.
    * Links to dashboards that help identify and debug application issues
* Are there any new application endpoints, front- or back-end? If so, please give examples of how any of the endpoints could be abused by unauthorized parties, as well as a plan to mitigate such threats.
* Is there any new logging data being captured?  If so, what data is being captured, how, and where is it stored?
* Is [Personal Health Information/PHI](https://www.hhs.gov/hipaa/index.html), [Personal Identifiable Information/PII](https://www.dol.gov/general/ppii), or any other [Personal Information/PI](https://www.oag.ca.gov/privacy/ccpa) being captured? If so, please answer the following questions:
    * Is the PHI strongly encrypted?
    * Is the PII encrypted?
    * Can the sensitive information be scrubbed?
* Are there any new, modified, or existing Cookies being used?
    * If so, are there any new Cookies?
        * If so, why can’t the existing Cookies be used?
    * If so, are there any modified Cookies?
        * If so, how are the Cookies modified?
    * If so, are there any existing Cookies?
* Is this feature authenticated or unauthenticated?
* Are there any other specific subjects that you want to highlight or focus additional attention on?

## Tasks
* [ ] Create an Architecture Diagram:
    This diagram must go beyond simple boxes and lines. It must clearly indicate which portions of the architecture are within the scope of the review, which portions are dependencies within the product, and which portions are external dependencies.
    This diagram must also illustrate the following specifics.
    * Which implementation of security approaches were considered along with the approach that was chosen and why?
    * If there are any libraries or components that this code base will depend upon that are currently not yet part of the code base? How and why were these selected?
* [ ] Create a Sequence Diagram:
    This diagram must include any authentication steps if this is an authenticated experience.
* [ ] Create a Data Flow Diagram:
    This diagram must illustrate the following specifics.
    * What data is collected or used, and where, including information such as credentials used by this system?
    * Where is the data is stored and how, including information such as any encryption used?
    * How is the data transferred, including information such as any encryption used?
    * Who accesses the data and in what capacity (read or read-write)?
    * What is the audit trail of data access and manipulation?
* [ ] Create an API Endpoint Documentation:
    This may include a link to a Swagger/OpenAPI document. Any new API endpoints introduced by this product or feature must be explicitly identified.
* [ ] Provide answers to the questions above
* [ ] Inform PM of readiness and provide link/location to documentation
 
## Acceptance Criteria
- Required documentation is completed and ready for review by the Platform team

**Comment by hdjustice** [comment]
When there is an opportunity, May I please have an update on where we are with this ticket?

**Comment by lihanli** [comment]
@hdjustice i can work on finishing this, was blocked by the code not being complete

**Comment by lihanli** [comment]
@alexseelig @hdjustice some of these questions apply to the frontend code, a frontend developer will need to answer them

**Comment by hdjustice** [comment]
Yep, I expected that.  I will follow up with Matt on that.

**Comment by lihanli** [comment]
> How does the code base get disabled in the product?

We can disable the feature flag in the backend and the frontend.

> Links to dashboards that help identify and debug application issues

https://vagov.ddog-gov.com/dashboard/p5g-fys-epz/1010-health-apps

> Are there any new application endpoints, front- or back-end? If so, please give examples of how any of the endpoints could be abused by unauthorized parties, as well as a plan to mitigate such threats.

New backend endpoints: POST /v0/form1010_ezrs, GET /v0/in_progress_forms/10-10EZR
The endpoints should not be able to be abused by unauthorized parties, only identity verified users can access the form and they only have access to their own data.

> Is there any new logging data being captured? If so, what data is being captured, how, and where is it stored?

Error messages are logged to the rails logs. PII is not sent to rails logs. When the API has an error, the form is logged to the encrypted PersonalInformationLog table.

> Is [Personal Health Information/PHI](https://www.hhs.gov/hipaa/index.html), [Personal Identifiable Information/PII](https://www.dol.gov/general/ppii), or any other [Personal Information/PI](https://www.oag.ca.gov/privacy/ccpa) being captured? If so, please answer the following questions:
Is the PHI strongly encrypted?
Is the PII encrypted?
Can the sensitive information be scrubbed?

When an API error occurs, the form PII is temporarily stored in the strongly encrypted PersonalInformationLog table. Otherwise, no PII is stored. Rails logs and Sentry logs automatically filter PII.

> Are there any new, modified, or existing Cookies being used?

The existing logged in user cookie is used, only identity verified users are allowed to access the form.

> Is this feature authenticated or unauthenticated?

Authenticated

### Architecture Diagram
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/fba507b1-8f38-4954-8a3c-c43294213db2)

Systems outside the scope of the review are in blue.

> Which implementation of security approaches were considered along with the approach that was chosen and why?

We discussed whether or not we wanted to save the form to the database and decided to not to, one of the reasons why was to prevent PII being leaked in the event of a database breach.

> If there are any libraries or components that this code base will depend upon that are currently not yet part of the code base? How and why were these selected?

No new backend libraries.

### Sequence Diagram
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/3e5e5561-3ed1-47ff-aab2-2c65d680eb96)

Data flow arrows are in the architecture diagram.

> What data is collected or used, and where, including information such as credentials used by this system?

Form data is sent from the frontend to the backend and finally to the enrollment system.

> Where is the data is stored and how, including information such as any encryption used?

We are not storing the form data unless an error occurs, then the data is stored in the encrypted PersonalInformationLog table.

> How is the data transferred, including information such as any encryption used?

Data from vets-website to vets-api is transferred with HTTPS. Data from vets-api to the enrollment system is also transferred with HTTPS with client side certificates.

> Who accesses the data and in what capacity (read or read-write)?

Form submissions can only be accessed by external systems. Error logs in the PersonalInformationLog table can be accessed by developers with production console access.

> What is the audit trail of data access and manipulation?

As far as I know there is no audit trail for access to the PersonalInformationLog table.

> Create an API Endpoint Documentation:

https://staging-api.va.gov/v0/apidocs

New endpoints: POST /v0/form1010_ezrs, GET /v0/in_progress_forms/10-10EZR

**Comment by hdjustice** [comment]
All required information received, thank you @lihanli for all this great work and information!
