### ISSUE TITLE
AMA Updates Launch

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#6165]
**AMA Launch CheckList**
- [x]  Removed  File an appeal link in global flyout menu [see #6182 ] 
- [x]  Updated File an appeal link and breadcrumb to Manage a legacy VA appeal in left nav
- [x]  Removed Board of Veterans' Appeal hearing link in left nav
- [x]  Disability Benefits Hub Changes -  [see #6182 ] 
- [x]  Removed banner on Decision review GitHub page (LW)
- [x]  Removed banner on legacy appeals Drupal page
- [x]  React Wizard Changes on How to file a claim page
- [x]  React Widget Changes 'Check appeal status' on legacy appeal page
- [x]   "After you file a Claim" Changes
- [x]   "Manage a legacy VA appeal" Changes - including META TITLE and META DESCRIPTION
- [x]   "VA decision reviews and appeals" Changes
- [x]  "Higher-Level review" Changes
- [x]   "Request a Board Appeal" Changes
- [x]   "Contested claims" Changes, including META TITLE new page name
- [x]   "Supplement claim" page  Changes
- [x]   "Search.gov" Updates [AFTER GO-LIVE]
- [x]   Redirects [NA THIS RELEASE]
- [x]   Approvals

**Launch Details**
[VA.gov-AMA-Updates-MASTER copydeck 02-26-20.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4256354/VA.gov-AMA-Updates-MASTER.copydeck.02-26-20.docx)

Prior to publishing the pages below, all tasks should be completed, reviewed and checked off. When checking off task boxes, please include your initials in parentheses at the end of task description. 

--**Global Menu**--

- [ ] For launch, remove "file an appeal."  

--**Nav label**--
- [ ] Change "File an appeal" to "Manage legacy VA appeals" to match the revised H1 page title

--**Side nav removal**--
- [ ] Removed "Board of Veterans Appeals hearing from side nav

--**Disability benefits hub**--
Current url: https://www.va.gov/disability/
Preview url: http://preview-prod.vfs.va.gov/preview?nodeId=68
- [x] Under H2 "**Manage your Veterans disability benefits,**" third link, change "File an appeal" to "Manage a legacy VA appeal," link to https://www.va.gov/disability/file-an-appeal/ and change descriptor. (RH)

--**REACT Wizard: "How to file a disability claim"**--
Current url:  https://www.va.gov/disability/how-to-file-claim/
Preview url: unavailable
- [x] Input dates of February 18, 2019 or earlier yield the "You'll need to file a Supplemental Claim" content. (LW got screenshots from Nick)
- [x] Input dates of February 19, 2019 or later yield the "You'll need to request a decision review" content. (LW got screenshots from Nick)

--**REACT widget: Check appeal status**-- 
- [ ] header/copy/button reads as follows:
**Check the status of your legacy appeal or decision review**
If you already filed an appeal or requested a decision review, sign in or create an account to check your status.
Check your claim or appeal status
(Note: See ticket [5648](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5648) re: making button consistent globally.)

--**After you file a claim**--
Current url: https://www.va.gov/disability/after-you-file-claim/
Preview url: http://preview-prod.vfs.va.gov/preview?nodeId=870
- [x] Edits per latest copy deck (attached) have been made (RH)

--**Manage a legacy VA appeal** (currently "File a VA disability appeal")--
Current url: https://www.va.gov/disability/file-an-appeal/
Preview url:  http://preview-prod.vfs.va.gov/preview?nodeId=901
- [ ] Remove "The appeals process has changed" banner
- [x] Edits per latest copy deck (attached) have been made (RH) **(One outstanding question for Jen)**
- [ ] Title tag and page title match and contain keyword (va appeal)
- [ ] Nav link and breadcrumb match the new page title
- [x] Meta description includes keyword (va appeal)
- [ ] Keyword (va appeal) is used 2-5 times on the page **@jenniferlee-dsva this is only showing up as the H1 on the page. Is this OK?**
- [ ] Clear CTAs (should have corresponding goals in Google analytics)
- [ ] Tracking codes have been embedded

--**VA decision reviews and appeals**--
Current url: https://www.va.gov/decision-reviews/
Preview url: https://vagov-content-pr-627.herokuapp.com/decision-reviews/
- [x] Remove "The appeals process has changed" banner (LW)
- [x] Edits per latest copy deck (attached) have been made (LW)
- [x] Title tag and page title match and contain keyword (appeal) (LW)
- [ ] Meta description includes keyword (appeal)
- [x] Keyword (appeal) is used 2-5 times on the page (LW)
- [x] Clear CTAs (should have corresponding goals in Google analytics)(LW)
- [ ] Tracking codes have been embedded

--**Supplemental Claim**--
Current url: https://www.va.gov/decision-reviews/supplemental-claim/
Preview url: https://vagov-content-pr-627.herokuapp.com/decision-reviews/supplemental-claim/
- [x] "Contested claim" referenced correctly
- [x] Subway map #3, 2nd H3, changed "source" to "provider" and "employer" to "hospital"

--**Higher-Level Review**--
Current url: https://www.va.gov/decision-reviews/higher-level-review/
Preview url: https://vagov-content-pr-627.herokuapp.com/decision-reviews/higher-level-review/
- [x] Edits per latest copy deck (attached below) have been made (LW)
- [x] "Contested claim" referenced correctly
- [ ] **NOTE:** Title tag has "VA" in it, but the page title does not. 

--**Request a Board Appeal**--
Current url: https://www.va.gov/decision-reviews/board-appeal/
Preview url: https://vagov-content-pr-627.herokuapp.com/decision-reviews/board-appeal/
- [x] Edits per latest copy deck (attached) have been made (LW)
- [x] "Contested claim" referenced correctly 

--**Contested Claims**--
Current url: https://www.va.gov/decision-reviews/multiple-party-claims/
Preview url: https://vagov-content-pr-627.herokuapp.com/decision-reviews/multiple-party-claims/
- [ ] Update page url from /multiple-party-claims/ to /contested-claims/
- [x] Edits per latest copy deck (attached) have been made (LW)

--**Search.gov Updates**--
Updated so that "decision reviews" page is the top result for a search for "appeal"

--**Redirects**--
- [ ] Internal, server-side redirects coordinated (e.g., "file an appeal" has been redirected to either "decision reviews and appeals" or "manage a legacy va appeal")

--**APPROVALS REQUIRED PRIOR TO PUBLISHING PAGES**--
- [ ] SMEs have approved final preview links
- [ ] Jennifer Lee
- [ ] Randi Hecht

**Comment by jenniferlee-dsva** [comment]
FYI - Some of the above is still TBD - re nav label/changes/URLs. We are meeting with @mnorthuis at 5:30 to solidify and then will update checklist ^ on those related items.

**Comment by RLHecht** [comment]
@jenniferlee-dsva In reviewing the copy changes on the Manage a VA Legacy Appeal page http://preview-prod.vfs.va.gov/preview?nodeId=901 I noticed a slight difference in copy from what's in the comments of the copy deck and what's in Drupal. Just making sure it's correct in Drupal and doesn't need to be changed to what's in the copy deck. Screenshot here: ![Screen Shot 2020-02-26 at 1.48.10 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/a69f837d-9c11-47d2-9b4c-cbc3730b35ba)

The copy deck has this slightly different text: ![image.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/61b13bb6-460d-4aa5-a6a1-e7fb4c9d4bc5)

**Comment by AkucherGCIO** [comment]
@jenniferlee-dsva @lwalsh617 @mnorthuis - I've added a checklist at the beginning for the steps that are being performed during Launch can get checked off.  Please do check it out and let me know what you think.

**Comment by lwalsh617** [comment]
^ looks good, Aruna. Thank you!

**Comment by jenniferlee-dsva** [comment]
@RLHecht - great catch! unf I didn't see your message until today. sorry i am always behind on emails. but it's all good now. Fred also noticed it and emailed us. I updated it in Drupal.

**Comment by jenniferlee-dsva** [comment]
@AkucherGCIO - thank you for the updated checklist. Can we also please... 

Add 'Updated the File an appeal' link on Disability hub menu.
Maybe move out or note somewhere that the Search.gov update is for after go-live?

**Comment by RLHecht** [comment]
@jenniferlee-dsva See my note I tagged you in about the keywords on the Manage a Legacy VA Appeal page. Just making sure this is OK.

**Comment by RLHecht** [comment]
@lwalsh617 I've checked off all of my parts of the launch checklist above and we are good to go with everything launching from Drupal.

**Comment by lwalsh617** [comment]
Thanks, Randi!

**Comment by jenniferlee-dsva** [comment]
Search.gov updates - done. 
![search-top-recommendations-updated-appeals.GIF](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/dc6040f2-f734-4020-9ec2-26df875a4903)

**Comment by ncksllvn** [comment]
@jenniferlee-dsva Thanks for grabbing the search.gov update! Anything left on this?

**Comment by ncksllvn** [comment]
I see some unchecked tasks in the issue description, but IDK if we've kept it completely up to date.
