### ISSUE TITLE
Cutover Plan: eMIS prefill to VAProfile

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#61659]
## Issue Description
Communicate changes to stakeholders (VFS teams and OCTO) about the migration of eMIS to VaProfile. Without doing so, teams wouldn't know what to test, how to proceed, and have proper info/documentation to make sound decisions about their app(s). 

---
## Tasks
- [x] [Communication plan ](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2774008077/EMIS+Deprecation)
- [ ] Testing plan (there is a ticket for testing that will be nested in this epic)
- [x] Rollback plan (just to be safe)
- [ ] Updating documentation (this has its own ticket and will be nested in this epic)

## Acceptance Criteria
- [ ] Communication plan complete
- [ ] Testing plan complete
- [ ] Rollback plan complete
- [ ] Documentation is up to date

**Comment by laineymajor** [comment]
Determine if we even need to disable... we might be able to go straight to migration. Check with Lihan.

**Comment by laineymajor** [comment]
Lindsey to meet with Rebecca about next steps. Document in appropriate ticket(s)....

**Comment by laineymajor** [comment]
Circling back once rebecca is back tomorrow. This will likely carryover to next sprint.

Lindsey and I will meet with Clint to discuss eMIS prioritization.

**Comment by rmtolmach** [comment]
Moving to next sprint. This and #61657 are being actively worked on.

**Comment by laineymajor** [comment]
This is potentially disabled/completed in one of Holden's commits. Need to check with @holdenhinkle

**Comment by laineymajor** [comment]
Potential carryover to next sprint. Will know more once Holden returns.

**Comment by laineymajor** [comment]
@rmtolmach to begin after the manual testing

**Comment by laineymajor** [comment]
Draft cutover plan

# API Cutover Plan

## Objective
The objective of this cutover plan is to smoothly transition from the old API call (referred to as "Old API") to the new API call (referred to as "New API"). This transition is necessary for upgrading our system to take advantage of new features and improvements offered by the New API.

## Scope
This cutover plan focuses on the following aspects:
- Identifying affected systems and stakeholders.
- Preparing the system for the cutover.
- Executing the cutover.
- Verifying the success of the cutover.
- Rollback plan (if needed).

## Cutover Tasks

### 1. Pre-Cutover Preparation
- [ ] Identify all systems and applications that currently use the Old API.
- [ ] Notify stakeholders about the upcoming cutover and its expected impact on their systems or workflows.
- [ ] Communicate the timeline for the cutover, including any maintenance windows or downtime.

### 2. API Integration Development
- [ ] Develop and thoroughly test the integration with the New API to ensure it functions correctly and meets all requirements.
- [ ] Ensure that relevant documentation and guides for using the New API are available to all stakeholders.

### 3. System Testing
- [ ] Set up a testing environment that closely resembles the production environment.
- [ ] Test the integration with the New API in the testing environment, including data transfer, error handling, and performance.
- [ ] Ensure that automated tests are in place to validate the New API integration.

### 4. Cutover Execution
- [ ] Schedule a maintenance window during a low-impact time for the cutover.
- [ ] Disable or phase out the Old API calls in production systems.
- [ ] Enable the New API calls in production systems.
- [ ] Monitor the cutover process for any errors or unexpected behavior.

### 5. Post-Cutover Verification
- [ ] Confirm that the New API calls are functioning correctly in the production environment.
- [ ] Monitor system logs and performance to detect any anomalies.
- [ ] Conduct validation tests and checks to ensure data integrity and consistency.
- [ ] Communicate the successful cutover to stakeholders.

### 6. Rollback Plan (if needed)
- [ ] Document a rollback plan in case critical issues arise during or after the cutover.
- [ ] Ensure that relevant team members are aware of the rollback procedures and responsibilities.
- [ ] Test the rollback plan in a non-production environment to verify its effectiveness.

## Success Criteria
- The transition from the Old API to the New API is completed without major disruptions to business operations.
- The New API functions as expected and meets all requirements.
- All stakeholders are informed about the cutover process and its outcomes.

## Dependencies
- Coordination with all teams and stakeholders using the API.
- Availability of a maintenance window for the cutover.

## Risks
- Unforeseen issues with the New API integration.
- Data discrepancies or loss during the cutover.
- Resistance or difficulties from stakeholders in adapting to the New API.

## Timeline
- [ ] **Notification and Planning:** DD/MM/YYYY - DD/MM/YYYY
- [ ] **API Integration Development:** DD/MM/YYYY - DD/MM/YYYY
- [ ] **System Testing:** DD/MM/YYYY - DD/MM/YYYY
- [ ] **Cutover Execution:** DD/MM/YYYY - DD/MM/YYYY
- [ ] **Post-Cutover Verification:** DD/MM/YYYY - DD/MM/YYYY
- [ ] **Rollback Plan:** DD/MM/YYYY - DD/MM/YYYY

## Communication Plan
- Regularly update stakeholders about the progress of the cutover.
- Provide clear instructions and resources for using the New API.
- Establish a point of contact for support and issue resolution during the cutover.

## Contingency Plan
In case of unexpected issues or failures during the cutover, the rollback plan will be executed to revert systems to the previous state using the Old API. This will minimize disruption to business operations while issues are addressed.

**Comment by laineymajor** [comment]
To do's:
- [ ] Lainey to draft communication plan
- [ ] Rebecca to determine which teams (and forms) need to be tested re prefill
- [ ] Lainey to create a ticket for the rollback plan (which will be a list of PRs that were merged for the changes... so we have a list if they need to be reverted)
- [ ] Rebecca to review documentation audit from Holden --- determine LOE

**Comment by LindseySaari** [comment]
@RachalCassity Going to make a quick fix and @rmtolmach to identify owners for the form_profile_mappings.

**Comment by rmtolmach** [comment]
### Research
I went through all of the files in [config/form_profile_mappings](https://github.com/department-of-veterans-affairs/vets-api/tree/master/config/form_profile_mappings) and pulled out the lines that were calling military_information. 

1010ez
```yaml
lastServiceBranch: [military_information, hca_last_service_branch]
lastEntryDate: [military_information, last_entry_date]
lastDischargeDate: [military_information, last_discharge_date]
discharge_type: [military_information, discharge_type]
postNov111998Combat: [military_information, post_nov111998_combat]
swAsiaCombat: [military_information, sw_asia_combat]
```

0873, FEEDBACK-TOOL
```yaml
  branchOfService: [military_information, last_service_branch]
  serviceDateRange:
    from: [military_information, last_entry_date]
    to: [military_information, last_discharge_date]
```

VIC
```yaml
verified: [military_information, vic_verified]
```

21-526ez
```yaml
servicePeriods: [military_information, service_periods]
reservesNationalGuardService:
  obligationTermOfServiceDateRange: [military_information, latest_guard_reserve_service_period]
```

26-1880. This would cover: 22-0994; 22-1990, 22-1990EZ, 22-1990N; 22-5490, 22-5495 which have a combination of these three attributes
```yaml
periodsOfService: [military_information, tours_of_duty]
currentlyActiveDuty: [military_information, currently_active_duty_hash]
activeDuty: [military_information, currently_active_duty]
```
### Ownership
Checked [Atlas](http://platform-codeowners.vfs.va.gov/product_directory/files?path_scope=config%2Fform_profile_mappings)
| Form     | GitHub Team                           |
| -------------- | ------------------------------------ |
| `1010ez`       | vfs-10-10                            |
| `0873`         | vfs-virtual-agent-chatbot            |
| `FEEDBACK-TOOL`| vfs-authenticated-experience or my-education-benefits |
| `VIC`          | None. Before Platform 😟                   |
| `21-526ez`     | Disability-Experience            |
| `26-1880` | vsa-ebenefits

**Comment by rmtolmach** [comment]
The following items are complete and tickets are made for follow-ups. Closing.

- Communication plan: https://vfs.atlassian.net/wiki/spaces/TT1/pages/2774008077/EMIS+Deprecation
- Testing plan - https://github.com/department-of-veterans-affairs/va.gov-team/issues/66376
- Rollback plan: https://github.com/department-of-veterans-affairs/va.gov-team/issues/66374
- Updating documentation: https://github.com/department-of-veterans-affairs/va.gov-team/issues/64496
