### ISSUE TITLE
Map eMIS military information fields to VaProfile

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#61657]
## Issue Description
As part of disabling eMIS military information, we should map the current information/fields that come from eMIS to VaProfile. The [1010 team has done this here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/form_profile.rb#L209-L226), but **only** for information pertaining to the HCA forms. 

See the  [HCA::MilitaryInformation::PREFILL_METHODS](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/hca/military_information.rb#L7). The approach that the 1010 team took is [to merge](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/form_profile.rb#L234-L236) the [vaprofile military information](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/form_profile.rb#L209-L226) into the military info method. For wider usage, we should migrate the remaining [military info](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/form_profile.rb#L231) over to VaProfile. 

**VA Profile `profile-service` swagger docs**:  https://qa.vaprofile.va.gov:7005/profile-service/swagger-ui/index.html?urls.primaryName=ProfileServiceV3

---
## Tasks
- [x] Make a list of attributes from VA Profile and compare it to the attributes in `PREFILL_METHODS`.
  - [x] Check to see if what we already have (from the 1010 team) gives us access to certain attributes. 
- [x] map prefill methods to VAProfile in `lib/va_profile/prefill/military_information.rb`
- [x] Add tests for above methods in `spec/lib/va_profile/prefill/military_information_spec.rb`
  - [x] Record a VCR cassette for the response to be used in the tests.

## Acceptance Criteria
- [x] eMIS fields are mapped to VA Profile fields.
- [ ] Code is tested on a review instance by platform team
- [ ] PR is merged

**Comment by LindseySaari** [comment]
Question: It appears that we used the eMIS Redis models, but the HCA implementation from the 1010 team just makes a call to eMIS (no caching)

**Comment by LindseySaari** [comment]
The 1010 team has already started on migrating _some_ of the [eMIS information to VaProfile](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/form_profile.rb#L209-L226). We should be able to piggy back off of this work. (see the [HCA military_information prefill_methods](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/hca/military_information.rb)). After chatting with the team about the Redis Caching of the information, it doesn't seem necessary, so we don't need to mimic the EmisRedis caching strategy. I've started some preliminary work on the migration piece [in this branch](https://github.com/department-of-veterans-affairs/vets-api/tree/v1_emis_to_va_profile_migration)

**Comment by rmtolmach** [comment]
handing off progress to @holdenhinkle so we can tag-team this work. latest branch: https://github.com/department-of-veterans-affairs/vets-api/commit/31c5cccca3f2d528aca60079d13e98fca24a78d6

**Comment by laineymajor** [comment]
This will likely carryover to next sprint.

**Comment by rmtolmach** [comment]
The following camelCase attributes are listed in `/v2/details/service-history/{oid}/{idWithAaid}.json` which, "Returns Military Service Episodes associated with the given identity." and probably are connected to the snake_case attribute that already exists in [vets-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/emis_redis/military_information.rb). 

1. `last_service_branch` ➡️ `branchOfServiceText`
2. `currently_active_duty` ➡️ if `periodOfServiceTypeCode` is `"A"`
3. `currently_active_duty_hash` ➡️ if `periodOfServiceEndDate` is nil or in the future. 
4. `service_periods` ➡️ combo of `periodOfServiceBeginDate` and `periodOfServiceEndDate`.
5. `guard_reserve_service_history` ➡️ combo of `periodOfServiceBeginDate` and `periodOfServiceEndDate` within the `guardReserves` array.
6. `latest_guard_reserve_service_period` ⬆️ uses the same info as above.

These are not at the `service-history` endpoint. I will look through the other endpoints to try and find them. 

1. `is_va_service_connected` - This is related to disability
2. `compensable_va_service_connected` - This is related to disability.
3. `va_compensation_type` - This is related to disability.

**Comment by rmtolmach** [comment]
Moving to next sprint. This is being actively worked on.

**Comment by rmtolmach** [comment]
Paired with @holdenhinkle today. I reached out to Tom Harrison who did some similar work last year for the 1010 team and he gave me some great tips! He recommended the Profile Service endpoint (suggested to him by the VAProfile team), which was a different endpoint that what we were originally looking at (Military Personnel).

**This is the Profile Service endpoint:** https://qa.vaprofile.va.gov:7005/military-personnel/swagger-ui/index.html?configUrl=/military-personnel/v3/api-docs/swagger-config#/

Which is where [this info](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/va_profile/models/service_history.rb#L31-L42) is coming from:
```rb
      def self.in_json
        {
          bios: [
            {
              bioPath: 'militaryPerson.militaryServiceHistory',
              parameters: {
                scope: 'all'
              }
            }
          ]
        }.to_json
      end
```

I also asked how they did testing (to get the VCR cassettes) and he wrote up some instructions for us 🎉 [Located in the sensitive repo](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/military_info/vapro_connect_local.md). So things are making a bit more sense now! Next step for this ticket is to run through the testing steps.

**Comment by rmtolmach** [comment]
**Can grab from Profile Service API _Military Person_ Bio**
1. `last_service_branch` - easy
2. `currently_active_duty` - we can get the dates from Profile Service API Military Information Bio Path and figure it out that way, or we can make a separate call to a different bio path. 
3. `currently_active_duty_hash` - same as above
4. `service_periods`  ⭐ need to double check. 
5. `guard_reserve_service_history` ⭐ need to double check. 
6. `latest_guard_reserve_service_period` ⭐ need to double check. 

**We need to make a new call to get these attributes from Profile Service API _Disability_ Bio path.**
1. `is_va_service_connected`
2. `compensable_va_service_connected`
3. `va_compensation_type` - determined by previous two attributes. 

Progress Holden and I made is here on the diff of `v1_emis_to_va_profile_migration` branch: https://github.com/department-of-veterans-affairs/vets-api/compare/master...v1_emis_to_va_profile_migration

**Comment by holdenhinkle** [comment]
The following methods have been implemented
- last_service_branch
- is_va_service_connected
- compensable_va_service_connected
- va_compensation_type

Todo:

- [ ] Finish implementing currently_active_duty
- [ ] Finish implementing currently_active_duty_hash
- [ ] Implement service_periods
- [ ] Implement guard_reserve_service_history
- [ ] Implement latest_guard_reserve_service_period

The write tests...

**Comment by laineymajor** [comment]
should we add veteran_status to the above list?

**Comment by rmtolmach** [comment]
Yesterday Holden and I finished implementing the methods, then we started writing tests. We will continue to write tests today.

**Comment by holdenhinkle** [comment]
Rebecca and I are almost done writing tests. Then we'll be able to close this ticket out.

**Comment by holdenhinkle** [comment]
I finished writing the tests for `lib/va_profile/prefill/military_information.rb`
We’re at 89.86% code coverage. The only way we’re going to get that past 90% is to do some mocking because the response in the VCR cassette were using doesn’t have comprehensive enough data to hit all the conditionals in our methods.

I handled all rubocop issues.

Code is pushed.

It looks like there’s some minor clean up that needs to be done in some other files.

**Comment by holdenhinkle** [comment]
@LindseySaari I had a thought about the tests on vets-website. I think I'm wrong about what I said - "if we successfully map all the emis method all vets-website tests will pass". I think all the requests to vets-api are mocked in vets-website so we wouldn't know if vets-api response is wrong. This makes me wish we had PACT tests still - PACT tests would be perfect for this.

**Comment by holdenhinkle** [comment]
Okay, I did a bit more this afternoon.

I updated `app/models/form_profile.rb`

I took an inventory of all the EMIS methods that need to me mapped, whose values are set in `FormMilitaryInformation` in `app/models/form_profile.rb`:
```
class FormMilitaryInformation
  include Virtus.model

  attribute :post_nov_1998_combat, Boolean
  attribute :last_service_branch, String
  attribute :hca_last_service_branch, String
  attribute :last_entry_date, String
  attribute :last_discharge_date, String
  attribute :discharge_type, String
  attribute :post_nov111998_combat, Boolean
  attribute :sw_asia_combat, Boolean
  attribute :compensable_va_service_connected, Boolean
  attribute :is_va_service_connected, Boolean
  attribute :receives_va_pension, Boolean
  attribute :tours_of_duty, Array
  attribute :currently_active_duty, Boolean
  attribute :currently_active_duty_hash, Hash
  attribute :va_compensation_type, String
  attribute :vic_verified, Boolean
  attribute :service_branches, Array[String]
  attribute :service_periods, Array
  attribute :guard_reserve_service_history, Array[FormDate]
  attribute :latest_guard_reserve_service_period, FormDate
end
```
## Method Inventory

**Methods in VAProfile::Prefill::MilitaryInformation**
The methods listed below are found in VAProfile::Prefill::MilitaryInformation:
- `last_service_branch`
- `currently_active_duty`
- `currently_active_duty_hash`
- `is_va_service_connected`
- `compensable_va_service_connected`
- `va_compensation_type`
- `service_periods`
- `guard_reserve_service_history`
- `latest_guard_reserve_service_period`

**Methods Marked as Done by the 1010 Team**
In `app/models/emis_redis/military_information.rb`, the following methods are documented as 'done by the 1010 team':
- `discharge_type` (String)
- `hca_last_service_branch` (String)
- `last_discharge_date` (String)
- `last_entry_date` (String)
- `post_nov111998_combat` (Boolean)
- `sw_asia_combat` (Boolean)

**Methods Marked as Started by TT1**
The following methods are documented as 'Started by TT1' in `app/models/emis_redis/military_information.rb`, but they are not found in VAProfile::Prefill::MilitaryInformation:
- `service_branches` (Array[String])
- `tours_of_duty` (Array)

**Update**: Both `service_branches` and `tours_of_duty` are located in HCA::MilitaryInformation.

**Unaccounted Methods**
The following methods have not been accounted for:
- `post_nov_1998_combat` (Boolean)
- `receives_va_pension` (Boolean)
- `vic_verified` (Boolean)

**Tasks**
- [ ] Check with Lindsey regarding the following unaccounted methods that are listed in the attributes:
  - `post_nov_1998_combat` (Boolean)
  - `receives_va_pension` (Boolean)
  - `vic_verified` (Boolean)

If these methods are necessary:
- [ ] Implement them.
- [ ] Update the tests for this file.

**Comment by laineymajor** [comment]
might need to carryover to next sprint. large pr... lots of code to review

**Comment by laineymajor** [comment]
reference duplicate if there are questions about the description https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/45122

**Comment by laineymajor** [comment]
Rebecca was able to get extra test coverage for the main file.
This is being carried over to next sprint.

**Comment by rmtolmach** [comment]
`post_nov_1998_combat` can be deleted. Looks like it was a duplicate and was partially removed in https://github.com/department-of-veterans-affairs/vets-api/pull/11858/commits/77031fc849b56a567fdb97f3ff6b5bcef8d65aa5

**Comment by holdenhinkle** [comment]
20 failures left to fix in `spec/models/form_profile_spec.rb`:

Failed examples:

- [ ] rspec './spec/models/form_profile_spec.rb[1:4:5:7:9]' # FormProfile#prefill_form with emis data with a user that can prefill emis returns prefilled 1010ez
- [ ] rspec './spec/models/form_profile_spec.rb[1:4:5:7:5]' # FormProfile#prefill_form with emis data with a user that can prefill emis returns prefilled 22-1995
- [ ] rspec './spec/models/form_profile_spec.rb[1:4:5:7:14]' # FormProfile#prefill_form with emis data with a user that can prefill emis returns prefilled 28-1900
- [ ] rspec './spec/models/form_profile_spec.rb[1:4:5:7:8]' # FormProfile#prefill_form with emis data with a user that can prefill emis returns prefilled 40-10007
- [ ] rspec './spec/models/form_profile_spec.rb[1:4:5:7:15]' # FormProfile#prefill_form with emis data with a user that can prefill emis returns prefilled 26-1880
- [ ] rspec './spec/models/form_profile_spec.rb[1:4:5:7:13]' # FormProfile#prefill_form with emis data with a user that can prefill emis returns prefilled 28-8832
- [ ] rspec './spec/models/form_profile_spec.rb[1:4:5:7:11]' # FormProfile#prefill_form with emis data with a user that can prefill emis returns prefilled FEEDBACK-TOOL
- [ ] rspec './spec/models/form_profile_spec.rb[1:4:5:7:3]' # FormProfile#prefill_form with emis data with a user that can prefill emis returns prefilled 22-1990N
- [ ] rspec './spec/models/form_profile_spec.rb[1:4:5:7:12]' # FormProfile#prefill_form with emis data with a user that can prefill emis returns prefilled 686C-674
- [ ] rspec './spec/models/form_profile_spec.rb[1:4:5:7:6]' # FormProfile#prefill_form with emis data with a user that can prefill emis returns prefilled 22-5490
- [ ] rspec './spec/models/form_profile_spec.rb[1:4:5:7:16]' # FormProfile#prefill_form with emis data with a user that can prefill emis returns prefilled 26-4555
- [ ] rspec './spec/models/form_profile_spec.rb[1:4:5:7:4]' # FormProfile#prefill_form with emis data with a user that can prefill emis returns prefilled 22-1990E
- [ ] rspec './spec/models/form_profile_spec.rb[1:4:5:7:7]' # FormProfile#prefill_form with emis data with a user that can prefill emis returns prefilled 22-5495
- [ ] rspec './spec/models/form_profile_spec.rb[1:4:5:7:2]' # FormProfile#prefill_form with emis data with a user that can prefill emis returns prefilled 22-1990
- [ ] rspec './spec/models/form_profile_spec.rb[1:4:5:7:10]' # FormProfile#prefill_form with emis data with a user that can prefill emis returns prefilled 22-0993
- [ ] rspec ./spec/models/form_profile_spec.rb:1330 # FormProfile#prefill_form with emis data with a user that can prefill emis with a user that can prefill evss without ppiu returns prefilled 21-686C
- [ ] rspec ./spec/models/form_profile_spec.rb:1316 # FormProfile#prefill_form with emis data with a user that can prefill emis with a user that can prefill evss without ppiu when Vet360 prefill is enabled returns prefilled 21-526EZ
- [ ] rspec ./spec/models/form_profile_spec.rb:1290 # FormProfile#prefill_form with emis data with a user that can prefill emis with a user that can prefill evss when Vet360 prefill is disabled returns prefilled 21-526EZ
- [ ] rspec ./spec/models/form_profile_spec.rb:1249 # FormProfile#prefill_form with emis data with a user that can prefill emis with a user with no vet360_id omits address fields in 686c-674 form
- [ ] rspec ./spec/models/form_profile_spec.rb:859 # FormProfile#initialize_hca_military_information when va profile is down in production logs exception and returns empty hash

I commented out all the examples and am fixing them one by one.

**Comment by rmtolmach** [comment]
Putting my Friday afternoon notes here...

`military_information` is not recognized in the tests.

`form_profile.rb` line 193
```rb
  def prefill
    @identity_information = initialize_identity_information
    @contact_information = initialize_contact_information
    @military_information = initialize_military_information. 
## A binding.pry HERE WILL GET HIT, MEANING ☝️ THAT METHOD IS HIT. HOWEVER...
    mappings = self.class.mappings_for_form(form_id)
...
  end

  private

  def initialize_military_information 
## A binding.pry HERE DOESN'T STOP EXECUTION OF THE TEST 😕 
    hca_military_information = initialize_hca_military_information
    va_profile_prefill_military_information = initialize_va_profile_prefill_military_information
    FormMilitaryInformation.new(hca_military_information.merge(va_profile_prefill_military_information))
  end
```

I even tried putting a binding.pry in the `initialize_identity_information` and `initialize_contact_information` methods and that _did_ work i.e. the binding.prys were hit 😑

**Comment by rmtolmach** [comment]
We're stuck on VCR errors in `form_profile_spec.rb` :unamused:

**Comment by laineymajor** [comment]
Discussed ^^ with the BE CoP.. trying a few more things, but no AH HA moment yet.

**Comment by laineymajor** [comment]
Holden 
- refactored and got tests updated
- started writing tests from scratch (now at over 90% coverage for the form profile)
- number of tests we still need to write
- much progress being made with the pivot

Linsdsey
- down to 4 failing tests in the file now

**Comment by laineymajor** [comment]
Lindsey got some of the specs passing on Friday.

Rebecca
- take an inventory of what remains here

Holden
- will circle back to the inventory (per rebecca) tomorrow

**Comment by rmtolmach** [comment]
- **`spec/lib/hca/military_information_spec.rb`**
  - 93% code coverage (of `hca/military_information.rb`). `service_branches` and `tours_of_duty` are untested.
  - [ ] Write these tests
- **`spec/models/form_profile_spec.rb`**
    - `form_profile.rb` has 92% code cov. but the file is still a mess. 
    - [ ] Clean up this file.
- **`spec/models/user_spec.rb`**
  - 87% code cov. (of `users.rb`). Some of our changes are untested.
  - [ ] Write these tests

**Comment by laineymajor** [comment]
Need carryover as testing is not yet complete

**Comment by laineymajor** [comment]
@LindseySaari able to id the issue that was occurring.. missing some fields. And did some stubbing in the tests
- @holdenhinkle  to fact check ^^

Currently, all but 1 test is passing.

**Comment by laineymajor** [comment]
One test remaining! Rebecca to work on this today.

**Comment by laineymajor** [comment]
Using data from the VCR. 
Reworked tests on Friday, and got the final test passing as of yesterday... but now another test failing (likely a bug). 
Looking into new failing test today.

GOAL: get all tests passing in vets-api by COB tomorrow.

**Comment by rmtolmach** [comment]
I ran `bundle exec parallel_rspec spec modules` and got:
`1305 errors, 1320 examples, 19 failures, 2 pendings`

I will look into the 19 failures. 

- [ ] rebase our branch with `master`

**Comment by laineymajor** [comment]
Holden is merging the master branch into the local branch being worked. 800+ changed files currently in our branch.

**Comment by laineymajor** [comment]
@rmtolmach what is being carried over with this ticket to next sprint?

**Comment by rmtolmach** [comment]
One test remaining in form_profile_spec and then any other failures. I ran `bundle exec parallel_rspec spec modules` again and got:
`1343 errors, 1496 examples, 77 failures, 8 pendings`. 

> Holden is merging the master branch into the local branch being worked. 800+ changed files currently in our branch.

Holden completed the rebase. But it didn't end up being 800 files. 24 files changed.

**Comment by laineymajor** [comment]
Decided to write another test. 404 and the 500 case.

**Comment by rmtolmach** [comment]
I pushed my most recent commit to the branch. Commit: https://github.com/department-of-veterans-affairs/vets-api/commit/1b1c1e2d6c9971fba8b70ccbdedbf9cf1c418508. All tests in form_profile_spec are FINALLY passing 🎉  

Next step: I'll look at the CI for that commit and start fixing failures I find there.

**Comment by laineymajor** [comment]
Continuing to work with ryan on common errors.
Ryan will branch off master and see what errors come up.; will work on fixing those errors together.

**Comment by laineymajor** [comment]
Continuing to work with ryan on common errors.
Ryan will branch off master and see what errors come up.; will work on fixing those errors together.

**Comment by LindseySaari** [comment]
More tests are passing, expected to continue into next sprint. We will also need to feature flag this to test in lower environments

**Comment by rmtolmach** [comment]
Now that i'm on Support, I'll need to hand off this work to Gia. Meeting today to discuss.

**Comment by laineymajor** [comment]
determining if some of the failures are related to veteran status... potentially 17 more failures remaining.

**Comment by laineymajor** [comment]
ready for testing
