### ISSUE TITLE
Governance offboarding for Sara Sterkenburg

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#61668]
## User Story
As the Governance team Product Manager, I want to make sure I identify all important tasks for offboarding Sara so that I am able to find proper coverage and ensure no responsibilities are dropped.

Assignee: @sterkenburgsara 
Peer Reviewer: @shiragoodman 

## Description
Sara's last day on Governance team is still TBD, however it is likely between July 28 and August 4. The purpose of this ticket is to identify all work she is contributing to so that we may come up with a plan of action for transitioning. 

## Tasks
- [x] Finish out overall taxonomy mapping for Experience Standards & plan for re-writing standards
   - [x] Shira and Sara to sync to finalize plan
- [x] Sync with Allison on collab cycle user flow diagram
   - Need to define who this is for. Internal flow and PW flow.
   - Shira to deprioritize
- [x] Talk with Shira about who to discuss Domo updates with / who to pass that to
   -  Allison to take over Domo, include Ian as FYI
   - Syncing with Allison & Ian on 7/13
- [x] Add Domo OCTO-DE survey research results & resulting project work to Governance Team research space on Confluence
- [x] Add internal user flows research study to Governance Team research space on Confluence
- [ ] Rewrite "How to complete an information architecture review for Staging Review"
   - comment within doc if no time to rewrite
- [x] Identify places where Sara's name needs to be removed from internal documentation & platform website (replace with Erin White by end of July) - documented in ticket #62189
- [x] Introduce Erin to IA cohort (meeting scheduled for Wednesday 7/26) 
- [x] Transfer ownership of any relevant Mural or Google docs/sheets/etc. to other governance team members
   - Cheryl now owns the Custom Tracks Flow mural
   - If ownership of other Murals is needed, the relevant team member should make a duplicate copy & use that as the source of truth moving forward (more details about that in a comment on this ticket below)
- [ ] ~~Complete platform offboarding ticket~~
   - Andrea will take care of this

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have offboarded Sara from her responsibilities and tasks for Governance team

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
FYI @sterkenburgsara  - if you have time, please feel free an list your ongoing work under the Tasks section of this ticket. We will address tomorrow at our 1:1

**Comment by sterkenburgsara** [comment]
Mural's online support says you can only transfer Mural ownership if you leave a workspace entirely. Since I am still at VA I can't do that. I think this is okay - the only benefits of ownership that I can see are the ability to download and/or export a Mural as a file. If you need to do that, a good workaround is to make a duplicate copy of any Mural I own and you collaborate on. Then you'll be the owner of that version & able to do this. 

The only Mural I own that you'll likely need to download & embed is the Custom Tracks Flow. Yesterday @CherylEvans made a duplicate copy of this, so she's the new owner & that version should be the source of truth moving forward.

**Comment by shiragoodman** [comment]
thanks @sterkenburgsara - I'm sure it won't be an issue. I appreciate you looking into it!

**Comment by sterkenburgsara** [comment]
@shiragoodman fysa - will introduce @erinrwhite to IA cohort in our bi-weekly sync on Wednesday, July 26 1-2pm ET.

**Comment by sterkenburgsara** [comment]
**Update**: will not be able to revise documentation for "How to complete an Information Architecture review for Staging Review" during this sprint. I'll complete async if you want to close this ticket.

**Comment by shiragoodman** [comment]
Task item:

> - [ ]  Rewrite "How to complete an information architecture review for Staging Review"
>    - comment within doc if no time to rewrite

was not able to be completed. @sterkenburgsara will review the doc outside of this ticket and make updates/comments where needed.
