### ISSUE TITLE
Audit Collab Cycle Support process

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#61666]
## User Story
As a Governance team member, I want to identify opportunities for automation within our Collaboration Cycle support process so that I can better utilize my time.

Assignee: @it-harrison 
Peer Reviewer: @CherylEvans 

## Description
The before, during and post steps of each Collab Cycle touchpoint (Kickoff, Design Intent, Midpoint Review and Staging Review) can be cumbersome and time-consuming. At times, steps are forgotten or completed after the preferred timeframe due to the many tasks Governance team members must juggle at once. 

The purpose of this ticket is to audit and evaluate the Moderator Responsibility steps associated with each touchpoint to identify steps that can be deleted completely, transferred to another team member, or automated. There are 4 touchpoints and each (excluding kickoff) has 3 main sections: Scheduling, During Meeting and Post Meeting. The objective should be to streamline and make each section of each touchpoint more efficient. 

### Opportunities
Ideas and suggestions from the team at refinement:
- 1 large code block for all touchpoints (since most VFS teams are recommended the same track)
- gh actions to automate the creation of the "completed" ticket
- no longer post in the #platform-collaboration-cycle Slack channel (tbd re MOU w/ CAIA)
- evaluate the sequence in which steps are completed to reduce context/tab switching
- opportunities for pre-written text so we can just copy/paste (slack shortcuts?)
- remove pipeline step?
- template for "completed" ticket? similar to Jim's "IA feedback" templates
- Remove quotation marks in "completed" ticket guidance
- Script for closing out DI, MPR and SR

## Impacted Artifacts
[Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)
[Design Intent - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Moderator+Responsibilities)
[Midpoint Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Moderator+Responsibilities)
[Staging Review - VFS - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review+-+VFS+-+Moderator+Responsibilities)

## Tasks
- [x] Create a documentation draft to document your proposed changes
- [x] Break the draft into 10 different sections. 1 for kickoff, 1 for DI Scheduling, 1 for DI During Meeting, 1 for DI After Meeting, with the last 3 repeated for MPR and SR
- [x] Audit the document and identify pain points in the process. This could be redundant or duplicate steps, steps that are not very efficient, steps where we could potentially automate (via GH actions or other tools) or introduce more clarity, steps that can be merged, etc.
- [x] Document all of the pain points in the documentation draft and make a proposal for how we can improve the pain point. If you don't have a specific idea for improvement but recognize that the current step is a pain point, feel free to leave the proposed solution blank.
- [x] When you have completed all 10 sections, share the documentation draft with Governance team members on the #platform-governance-team Slack channel and ask for feedback. You should give team members at least 3 days to reply.
- [x] After team has provided feedback, sync with Shira to discuss and finalize changes.
Note: changes to the docs will not take place within this ticket.

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have identified feasible opportunities for reducing the level of effort required for scheduling and completing each collab cycle touchpoint

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
[Draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2721316875/Collab+Cycle+Audit+-+Draft) is in progress.

**Comment by allison0034** [comment]
@it-harrison I spoke to Shira about making the Slack reply for each touchpoint code so we can have the copy icon that we just have to click. Really that would be great if we can do that for anything we have to copy. Can you include this in the ticket please?

**Comment by shiragoodman** [comment]
code block* 

yes, I agree with Allison. Right now we add these lines in manually. It would be helpful if they were included from the beginning. @it-harrison please reach out to @allison0034 if you need clarification.

Ian - I will review your draft soon! Thank you.

**Comment by shiragoodman** [comment]
@CherylEvans would you please review the draft so far and provide comments? Ty!

**Comment by CherylEvans** [comment]
@shiragoodman Will do!

**Comment by CherylEvans** [comment]
@shiragoodman @it-harrison I made my first editing pass.  Please give it a look and let me know what else needs refinement. Thank you!!  Great job, Ian!!

**Comment by allison0034** [comment]
@it-harrison love all the automated things you are doing! Can we make the [Zoom meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2454585540/Zoom+information+for+Collab+Cycle+meetings#Thursday-at-1:30pm-ET) a code block so we can copy/paste that easily?

**Comment by shiragoodman** [comment]
@it-harrison I opened #63309 to implement your suggested changes. Thank you! Closing this out.
