### ISSUE TITLE
Update user qualifications for Reactivation Test

### ISSUE THREAD

**Issue by holytoastr** [department-of-veterans-affairs/va.gov-team#61667]
## Issue Description
Per Anthony:
For Reactivation test Version B, we'd focus on users with DSL & Login.gov
When we release the triggered Reactivation emails to a wider audience later, we'd include users with DSL and/or MHV, and Login.gov or ID.me. We'd send them a different email depending on which modern credential we want them to reactivate.
Still working out how to handle users with both modern credentials.

---
## Tasks
- [x] Remove users who have only an id.me alternate credential from qualification for this test

## Acceptance Criteria
- [x] Users who log in with DSL and have a login.gov credential will receive email
- [x] Users who log in with DSL and have an id.me credential will not receive email
- [x] All other users will not receive email
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
