### ISSUE TITLE
Add in headings to the warning alerts

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#61670]
## Description 

We never finished add the headings into some of the error states: 

![Screenshot 2023-07-10 at 10.56.07 AM.png](https://images.zenhubusercontent.com/62264cddfdd7546d65710eff/5dc2c415-c740-49dd-bedd-fd98d9b97c8a)

## Tasks

- [ ] Review [alert warning documentation](https://design.va.gov/components/alert) 
- [ ] Add headings and check content 
- [ ] Review with Laura, Aliyah, if needed
- [ ] Update the wireframes

## UX deliverable
- Progress and updates are documented in this ticket:
   https://github.com/department-of-veterans-affairs/va.gov-team/issues/61670#issuecomment-1688115772

**Comment by kellysmith1008** [comment]
@zach-park I'll start working on content for this ticket today and through tomorrow - I can pass it off on Friday and I can set something up for next week for us to sync up on it - does that work?

**Comment by zach-park** [comment]
> @zach-park I'll start working on content for this ticket today and through tomorrow - I can pass it off on Friday and I can set something up for next week for us to sync up on it - does that work?

Sounds great. Thank you!

**Comment by kellysmith1008** [comment]
[Created a page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/1D358457-C022-4ABA-9A38-44171F548862/canvas) in the unified design file to work on this - adding in text suggestions today

**Comment by zach-park** [comment]
@benbrasso-agile6 @kellysmith1008 @loripusey , wireframes in this page link are ready for validation: 
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/1D358457-C022-4ABA-9A38-44171F548862/canvas

**Comment by benbrasso-agile6** [comment]
LGTM, I would move them up into the Design page now too. What's our plan to review these with Laura? Actually, let me find out if she'll be at the Wednesday meeting.

**Comment by benbrasso-agile6** [comment]
@zach-park Yeah, let's show them to Laura real quick as an intro tomorrow. Can you get them added into the Design page?

**Comment by zach-park** [comment]
> LGTM, I would move them up into the Design page now too. What's our plan to review these with Laura? Actually, let me find out if she'll be at the Wednesday meeting.

@benbrasso-agile6 , @kellysmith1008 , the design page is now also updated with the header content.

**Comment by benbrasso-agile6** [comment]
Thread is here https://dsva.slack.com/archives/C03CGTDLTFF/p1690907028900849

**Comment by kellysmith1008** [comment]
Looks good to me, @zach-park !

**Comment by benbrasso-agile6** [comment]
Ticket for Laura to review the work is here https://github.com/department-of-veterans-affairs/va.gov-team/issues/63061

**Comment by benbrasso-agile6** [comment]
Waiting for Laura to provide feedback

**Comment by benbrasso-agile6** [comment]
@zach-park I think you can start working on updating these in the feature page https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/1D358457-C022-4ABA-9A38-44171F548862/canvas

based on Laura's feedback

Just let @kellysmith1008 or I know if you need some help with anything or reviewing. I left some replies to Laura's comments.

**Comment by benbrasso-agile6** [comment]
Updates look great, @kellysmith1008 is giving a fine review

**Comment by zach-park** [comment]
@kellylein @benbrasso-agile6 @loripusey art boards are ready for validation now. Thank you!
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/1D358457-C022-4ABA-9A38-44171F548862/canvas

**Comment by benbrasso-agile6** [comment]
K, will take a look tomorrow

**Comment by kellysmith1008** [comment]
Looks good, @zach-park - I have one word of text to updated (this appointment -> your appointment) but I will do that now.

**Comment by zach-park** [comment]
Progress and updates are documented in this ticket: 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/61670#issuecomment-1688115772

**Comment by benbrasso-agile6** [comment]
@zach-park go ahead an move the updates to the alerts from the [feature page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/1D358457-C022-4ABA-9A38-44171F548862/canvas) into the [design page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/0EC89917-F949-4461-A7B3-32A5201FD2A2/canvas) please

**Comment by zach-park** [comment]
> @zach-park go ahead an move the updates to the alerts from the [feature page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/1D358457-C022-4ABA-9A38-44171F548862/canvas) into the [design page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/0EC89917-F949-4461-A7B3-32A5201FD2A2/canvas) please

Wireframes on the design page is updated to reflect the feature page UI changes.

**Comment by benbrasso-agile6** [comment]
Good zach, nice work

**Comment by benbrasso-agile6** [comment]
closing
