### ISSUE TITLE
626c Picklist of Dependents

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#61672]
## Issue Description
When a Veteran fills out either the 527EZ or the 626c, when they go to add or remove a dependent, they are not provided with a list of the dependents already on their profile. They are able to “View dependents,” but are not provided a link from either form to view that list.

As a user filling out 626c, I want to see a list of dependents attached to my profile when I go to add or remove a dependent, so I can choose which ones to add/remove to my benefits.

---
## Tasks
- [ ] Identify best way to address this issue to reduce data entry errors

## Acceptance Criteria
- [ ] Mockup of solution.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
