### ISSUE TITLE
Upgrade vets-website Heroku stack

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#6167]
## Problem Statement
According to https://dashboard.heroku.com/apps/vets-website/settings, the vets-website Heroku stack is on `cedar-14`. In vets-website's [`app.json`](https://github.com/department-of-veterans-affairs/vets-website/blob/master/app.json#L16), it says we're deploying new apps on the `heroku-18` stack.

## Tasks
- [ ] Investigate the discrepancy between what Heroku says on the settings page and what the `app.json` says
    - I expect the difference is that there's some really old instances that are still running `cedar-14`, that need to be removed, but couldn't verify that quickly
- [ ] Upgrade the vets-website Heroku stack to `heroku-18`

## Acceptance Criteria
- [ ] The vets-website Heroku app is upgraded to the latest stack version

**Comment by wyattwalter** [comment]
This was a bunch of old review instance apps on the old stack. I was cleaning up some stuff in Heroku today and just deleted all of them. There's one app left called mock-prescriptions-api that was still on the old stack that I put into maintenance mode for now. I think we can delete that one as it hasn't seen any activity for quite some time.
