### ISSUE TITLE
Bug: BOA letters aren't showing up in staging in DDL

### ISSUE THREAD

**Issue by samcoforma** [department-of-veterans-affairs/va.gov-team#61687]
## Issue Description
Board of Appeals letters are not showing up in the DDL on staging. Possibly due to the use of a constant combined with a feature flag condition for allowed doc types.

---
## Tasks
- [ ] switch from use of a constant to an object method when determining allowed doc types.
- [ ] consider using a parameter store doc type list instead of a feature flag
- [ ] update related RSpec test

## Acceptance Criteria
- [ ] BOA Letters show up on staging
- [ ] RSpec tests pass
