### ISSUE TITLE
[CAIA Intake] Claim status tool updates from Benefits Mgmt Tools

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#61696]
## About your team

- Team name: Benefits Management Tools
-	OCTO-DE product owner: Matt Self
-	Product manager: Jacob Worrell
-	Designer: Skyler Schain
- Accessibility specialist: Josh Kim
- Content writer: 
-	Product/team Slack channel: #benefits-ce-mgmt_tools
 
### What does your team need support for? Check all that apply.
- [ ] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [x] Making revisions to one or more existing VA.gov pages
- [ ] Accessibility review of wireframes and/or prototypes
- [ ] Accessibility issue (general request)
- [ ] Accessibility PDF review request
- [ ] Accessibility user research support ([submit a separate, additional request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name))
- [ ] DST component or pattern 
- [ ] Something else 
 
### Give a brief description of what your team needs support with:

We are working on new designs for the Claim Status Tool home page. We are looking for a content review on a first draft prototype to see if there are any content tweaks we should make to align with VA.gov standards. 
 
 
### Will this new product be released incrementally (for instance 25% of users initially)? 
  - [x] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
### When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*

### When does this work need to be completed?
- Estimated launch date: Early August
- Estimated staging review date: 
- Content, Accessibility, and IA work needed by: ~July 20

### Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

### If no ...
- Skip to the _supporting artifacts_ section, below.
 
#### Please provide the link to your Collaboration Cycle ticket: 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/58828
 
#### Please check all of the phases in the Collaboration Cycle you have completed: 
- [x] Design Intent
- [ ] Midpoint Review
- [ ] Staging
 
##### Design Intent
- [ ] Accessibility
- [x] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed.
- [ ] Unknown at this time.
##### Midpoint
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed.
- [ ] Unknown at this time.
##### Staging
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed.
- [ ] Unknown at this time.
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/CST%20Product/Improved%20Evidence%20Requests%20Initiative.md)
- [Prototype or mockups](https://www.sketch.com/s/98e35645-34eb-40cf-80c1-6c4952943584/prototype/a/252DFC7E-C58A-478F-A521-5C082886DA75)
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/2023-05-Evidence-Submission/research-plan.md)
- [Research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/2023-05-Evidence-Submission/research-findings.md)

#### Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

 **Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.
 
### Accessibility Help in Slack
The [#accessibility-help channel](https://dsva.slack.com/archives/C8E985R32) in the DSVA Slack, is also available to you as a resource. Everyone is welcome to ask questions or get help from our a11y (accessibility) specialists. Tag `@Terry Nichols` to get a11y help asap.

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag `@Terry Nichols`.**

- If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
- If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)
 
 - If you are creating an [experimental design,](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) please [also contact the DST. ](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- If you are requesting [a11y support for user research,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name) please complete this form, next. 

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62735
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/68345
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/68344
```

**Comment by coforma-terry** [comment]
Tagging @megzehn for this one as it's content focused :)

**Comment by skylerschain** [comment]
Just an update here. We are working on some design iterations based on the [feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61470) from the Design Intent review. Would love for some content eyes on this – but keep in mind we will have a newer version of the design probably in a week or so.

**Comment by laurwill** [comment]
Hi @skylerschain , thanks for the update! Your original target date for CAIA work was July 20, but we want to avoid double work if you're making updates based on design intent. Would it make sense to pause this until next week and provide our suggestions based on the updated designs?

**Comment by skylerschain** [comment]
Yes I think that makes sense! I will circle back to this next week with an
updated set of designs.

**Comment by laurwill** [comment]
Hi @skylerschain — documenting some notes from our meeting last week, and also pulling in @kristinoletmuskat to note IA / OOUX considerations. 

This work is moving towards an async midpoint (not yet scheduled). We'll provide content support in stages. The first piece to focus on in our current sprint is the new cards in these 2 Sketch screens. Veterans usually have 2 to 10 of these cards:
- https://www.sketch.com/s/98e35645-34eb-40cf-80c1-6c4952943584/a/ZVKYPrY 
- https://www.sketch.com/s/98e35645-34eb-40cf-80c1-6c4952943584/a/JAP40E0

As part of this ongoing content work, we'll need to resolve these inconsistent word clusters flagged in design intent:
![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/104158104/7067a6ee-386e-42d9-9596-80921837474b)

@skylerschain could you also provide the list of "Recent activity" steps that we'll need descriptions for in that screen? I think you mentioned it would be a long list, so we'll want to make a plan for those.

**Comment by skylerschain** [comment]
Yes, thank you @laurwill! 

As a source of truth, let's use this link: 
https://www.sketch.com/s/98e35645-34eb-40cf-80c1-6c4952943584/v/4LPabm/p/B9C46ABC-36AD-4CA8-9896-55762FC6912E/canvas?posX=-718.5416497737808&posY=-3212.7872891352317&zoom=0.36041006445884705

This has a few minor tweaks from the last one we looked at, but this is the Final Spec I'll be passing off to developers and I'll maintain this with our latest language changes.

As for the "Recent activity" list, those are tracking updates coming from VBMS. The current version of this appears as "updates" in the CST claim status page (see below). I'm not sure where that full list of strings lives, if anywhere, but I'll check with my engineering team. 


<img width="675" alt="Screenshot 2023-08-02 at 9 17 55 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/5a9dd17b-9a8a-409b-9a2e-d546e4a4710b">

**Comment by joshkimux** [comment]
@laurwill adding another small request here! We're looking for some guidance on how to write out our page titles. [I've included context to this in this ticket here.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60900)

We need help determining:
- Can we maintain the conversation h2 "What's happening with your claim" if we can reason it is equivalent to "status"?
- Can we adjust the breadcrumb to the generic h1 in this half step? e.g. Claim for compensation
- Is it a requirement to include "| Veterans Affairs" in the title element? If so, is it ok if we go past the 52 character limit count with Status | Claim for compensation submitted on June 15, 2023 | Veterans Affairs

I'm happy to meet about this if it's easier than working async!

**Comment by mistymg** [comment]
@skylerschain I may give some content feedback in partnership with Laura from a mobile app standpoint, since these changes will affect us as well. Could you give me access to comment in the Sketch files? Thanks!

**Comment by skylerschain** [comment]
Done :)

**Comment by uxgary** [comment]
Hello @kristinoletmuskat 

We have a [separate ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60900) that is dependent on the work here. Per the ticket, we need to update the browser tab titles. As we know it, the browser tab title will be a combination of the breadcrumb, H1, and H2. I'm looking for some help, if you could please provide answers to these questions: 

- What should breadcrumb be?
- What should the browser tab title be?

**Comment by kristinoletmuskat** [comment]
Hey @uxgary -- I was reading through the ticket you connected and looking through Josh Kim's suggestions. It looks like ya'll might have made some decisions based on his feedback? Or have you solidified your H1s with content @laurwill?

Here's some info for your questions, but first we gotta confirm what you've selected for the H1

1. The breadcrumb should ideally match the H1.
2. **General guidance for title tags:**
- the title tag does have to include | Veterans Affairs. It's ok if it gets cut off in the browser tab, it will still show up in search engine results.
- The title tag doesn't have to be <52 characters, just note that's where it will get cut off. 
- The current official pattern is  **H1 | Veterans Affairs**...however, we are starting to do things differently for auth pages.  Based on what we are doing for health, the pattern we are using is specific --> general:  **[H1] - [tool/product name] | Veterans Affairs**. **Ex:  Blood Pressure History - Medical Records | Veterans Affairs**

@skylerschain can you remind me why we can't put the claimed conditions in the H1s? Ex: 'Claim for Headaches, PTSD, left foot condition'

**Comment by skylerschain** [comment]
@kristinoletmuskat Is the H1 you're referring to the "Your compensation claim" title? 

I think putting the claim conditions in the H1 could be tough, because we don't control how many of those there are, and often there are quite a few. So it could lead to really long H1s in a high portion of claims. 

<img width="918" alt="MacBook Air 13  Copy 51" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/b9af2551-7936-47e0-b36d-bd0dbeb053dd">

**Comment by uxgary** [comment]
Thank you for your feedback @kristinoletmuskat the information you've provided is great. One last thing, we wanted to have browser tab unique in the event that a veteran (incl. ones using assistive tech) has two or more claims tab open they can differentiate. 

I wanted to share some ideas that came to mind, I wanted to know what you think or if you could modify these in the way you think is most appropriate. 

**Generic title for the entire page:**
- June 15, 2023 compensation claim | Veterans Affairs

**Tab specific (the page title would update when the user clicks on a tab)**
- Status of your June 15, 2023 compensation claim | Veterans Affairs
- Files for your June 15, 2023 compensation claim | Veterans Affairs
- Overview for your June 15, 2023 compensation claim | Veterans Affairs

**Comment by kristinoletmuskat** [comment]
Chatted with Skylar and we're going to touch base on a call tomorrow.

But I also wanted to mention this! Our title tags are all initial caps which is different from H1s - so the title tag would be "Status Of June 15, 2023 Compensation Claim | Veterans Affairs"

**Comment by skylerschain** [comment]
**Outcomes from the meeting Aug 31, 2023**

1. We will go with Gary's second option for browser tab titles. The only note is to remove "your" to keep it more concise.

2. To make the breadcrumbs more unique for the different parts of the detail page we will update them to: 
- Status of claim
- Files for claim
- Overview of claim

3. Skyler to create mocks reflecting these decisions and will post a link here ASAP for the team's review.

**Comment by skylerschain** [comment]
Update: After discussion with engineering, it's not feasible to have the breadcrumbs say "Status of claim," "Files for claim," etc. because we won't know if it's a claim vs. a decision review type the way that this code is currently written.

As a result we are going with the following for breadcrumbs to keep it claim type-agnostic.

- Status
- Files
- Overview

The [latest mocks](https://www.sketch.com/s/98e35645-34eb-40cf-80c1-6c4952943584/p/B9C46ABC-36AD-4CA8-9896-55762FC6912E/canvas) reflect these changes.

**Comment by skylerschain** [comment]
Nope!
