### ISSUE TITLE
Change icon in the manage appts symbol

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#61708]
## Tasks

- [ ] Change icons to remove the check mark from the icons in the manage appts component on the confirmation pages. E.g., we can't use similar ones that Ya-ching is using for the "your information is updated" statuses. 
- [ ] Make sure symbols and artboards are up to date
- [ ] 

## AC

- [ ] Change icons to remove the check mark from the icons in the manage appts component on the confirmation pages. E.g., we can't use similar ones that Ya-ching is using for the "your information is updated" statuses. 
- [ ] Make sure symbols and artboards are up to date

**Comment by zach-park** [comment]
Based on the latest design decision of the appointment status, this task is no longer necessary. Therefore, closing the ticket. @benbrasso-agile6 @loripusey @ytsaoca
