### ISSUE TITLE
[CONTENT] Research and write BUTLER, PA System Health Services and Program Intro (Extended-Homeless) [CONTENT]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#6171]
## User Story or Problem Statement
As a Veteran Web user, I need a System description of services provided at VAMC, so I can understand and best chose the services and service location for my needs.

## Goal
_Efficient and clear content describing local Health Service provided_
_Efficient plain language for Health Services and Health Service Program Intro_

## Objectives or Key Results this is meant to further
- _Reduced word count and improved plain language._

## Resources - Tools - Documentation
[Butler Health Services Content Playbook](https://docs.google.com/spreadsheets/d/1OuKoxXLml_uZQhmTZoYXIFl0hMIPBUil/edit#gid=631197453)
[Butler Health Services:A-Z](https://www.Butler.va.gov/services/index.asp)
[Pittsburgh Homeless Veteran Service Program Link](https://www.va.gov/pittsburgh-health-care/homeless-veteran-care/)

## Tasks
_Tasks that must be complete using content playbook criteria for the following Health Services, and Health Service Program Intro:_
- [ ] Extended care and rehab
- [ ] Gynecology
- [ ] Hematology_oncology
- [ ] Homeless (Health Service)				
- [ ] Homeless (Health Program)	

## Acceptance Criteria
_Items that must be written and documented in Content Approval Folder under the correct VAMC System folder (i.e. Altoona, Butler)_
* Extended care and rehab
* Gynecology
* Hematology_oncology
* Homeless (Health Service)				
* Homeless (Health Program)
