### ISSUE TITLE
[Frontend] Order Confirmation Page 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#6172]
## User Story or Problem Statement
As a Veteran I need _to have a confirmation page  so I can see what I ordered, order number and what to do if I have issues with my order.

## Goal

_A confirmation page will display order Veteran placed with clear next steps and actions _

## Objectives or Key Results this is meant to further
- _Veterans will see a confirmation of their order selection and have a clear understanding on what happens after their order is placed_
---
## Tasks
- [ ] _Create Review Page_
- [ ] _Display order data from API and selections from previous page 
- [ ] _Order data is captured properly 

## Acceptance Criteria
- [ ] _For a given test user placing a test order the selections will be reflected in confirmation page?_
- [ ]_For a given test user the order confirmation page captured the orders and calls API to transmit data. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
