### ISSUE TITLE
Design | CH36 Form Updates

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#61721]
## Issue Description
- Changes made and new fields added to paper form (see list). Online form only contains critical fields.
  * Moved instructions from the back of the form to the front.
  * Q10A: Added additional military departments. (space force, NOAA, USPHS)
  * Q8: If applicant is attending school or not. (Need to determine if they are attending a vet-success school, if so the application is transferred to a contractor.)
  * Q11: Character of discharge.
  * Q16: Condensed to determine if child or spouse. 
  * Q20: Are they currently attending school.
- Form name changes handled here #62284 
- [Additional Notes ](https://docs.google.com/document/d/1tZejPPUbRaDt162ZETL6_VJ2Ydi0zruV6zpPYlyHWgU/edit?usp=sharing)on form changes and requested enhancements.
---
## Tasks
- [x] Compare the online form against the updated paper form and determine if any existing online form fields need to be updated
- [ ] Create designs for any online form field updates.
- [ ] Create subsequent engineering ticket (if needed)

## Acceptance Criteria
- [ ] Wireframes for CH 36 form updates/additions.

**Comment by jstrothman** [comment]
@steele-lm Per this [Slack thread](https://dsva.slack.com/archives/CE4304QPK/p1689793450066739?thread_ts=1687293546.830659&cid=CE4304QPK) :

1. Sitewide CAIA team updates the  [Find Forms](https://www.va.gov/find-forms/) Ch 36 landing page and updates the pdf which is stored in the CMS
2. Sitewide CAIA team updates the [Ch 36 page](https://www.va.gov/careers-employment/education-and-career-counseling/): which has 3 references to form number; replace linked pdf to updated)
3. Our team updates the [introduction page](https://www.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/introduction) and the rest of the pages in the form flow

I wonder if we can separate out the two issues: 
1. Update the form name changes (including updating the url)
2. Adding additional fields to the form. 

As of today, there will be a mismatch between the form number in search results, [Find Forms](https://www.va.gov/find-forms/), the [Ch 36 page](https://www.va.gov/careers-employment/education-and-career-counseling/) the online form

**Comment by jstrothman** [comment]
@steele-lm Regarding the task list, I think updating the introduction page only involves a CAIA intake request if we need their help in changing the URL. We don't need them to review changes to changing the number of the form.

**Comment by steele-lm** [comment]
@RLHecht Here you go!

**Comment by steele-lm** [comment]
@jstrothman I broke this ticket apart now that we have more info. The form name change ticket is #62284
