### ISSUE TITLE
[SPIKE] Update DDL doc types list to use AWS parameter store

### ISSUE THREAD

**Issue by samcoforma** [department-of-veterans-affairs/va.gov-team#61724]
## Issue Description
We want to migrate from using hard coded doc type lists w/ feature flags in vets-api code to using the AWS parameter store. This ideally should be two separate lists with keys to give independent control to the mobile team. A key could be passed into the service object by each team's controller. No more feature flags for new doc types.

---
## Tasks
- [ ] have conversation about this ticket & revise/update (pros & cons)
- [ ] configure AWS parameter store lists
- [ ] update claim_letters service
- [ ] update claim_letters controller
- [ ] coordinate with mobile
- [ ] remove doc type feature flag

## Acceptance Criteria
- [ ] AWS parameter store has been configured
- [ ] claim_letters service has been updated
- [ ] claim_letters controller has been updated
- [ ] RSpec tests updated and pass
- [ ] Coordination w/ mobile has occurred
- [ ] feature flag for BOA letters removed

**Comment by samcoforma** [comment]
@kjduensing @jerekshoe let's discuss this in the next engineering huddle?
