### ISSUE TITLE
[FE] 10-10EZ - Facility Selection: Technical discovery on level of effort for development

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#61730]
## Background
Before we can begin updating designs and development, we need to verify the level of effort and technical constraints/availability to re-design the facilities selection page along with using the Lighthouse Facilities API to perform a search against.  This includes validating how to pull the correct facility information and ensuring they are only valid medical treatment facilities (as opposed to cemeteries, admin buildings, nursing homes, etc).

## Tasks
- [x] Validate how the search can be done to ensure we are pulling only medical treatment facilities (as described above)
- [x] Verify any technical constraints or requirements needed to be met prior to development
- [x] Determine level of effort to complete the development of the re-design as well as calling the API (the API work was initiated but may need to be adjusted)
- [ ]  Discuss with PM on determination, assist with planning next steps

## Acceptance Criteria
- The development level of effort will be determined and discussed with PM
