### ISSUE TITLE
[FE] 10-10EZ - Facility Selection: Implement Facility Selector components based on previously-created work in the CG application

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#61731]
## Background
To improve the Facility Selection experience, we are implementing new functionality to allow users to input their city, state or postal code and get a list of results from which they can choose. We will need to implement previously-created components for the search input and results list into the custom form page.

### Resources
- [Initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Facility%20Selection/ReadMe.md)
- Sketch designs - TBD

## Tasks
- [ ] Build out Facility Selector on custom form page with components
- [ ] Wire up connection to MapBox Client and Lighthouse API to get results
- [ ] Validate data is being set on selection
- [ ] Ensure all work is implemented behind feature flag and not visible in production

## Acceptance Criteria
- Facility selection page successfully searches & returns results for selection
- Form data is being set on radio list selection

**Comment by hdjustice** [comment]
Closing ticket - feature descoped
