### ISSUE TITLE
[FE] 10-10EZ - Facility Selection: Deploy to Staging for validation

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#61732]
## Background
To improve the Facility Selection page experience on the 10-10EZ, we are going to revise the question being asked, provide additional context on why we are asking it and implement a new search functionality and display (which aligns more with the current facility locator page within VA.gov).

For this ticket, we will deploy all changes to the Staging environment, so that we can validate design and functionality prior to the Midpoint review and Usability testing.

### Resources
- [Initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Facility%20Selection/ReadMe.md)
- Sketch designs - TBD

## Tasks
- [ ] Deploy code to Staging Environment
- [ ] Use Feature Flag/Toggle to ensure the code is available in Staging, but hidden in Production
- [ ] Work with PM/team to validate

## Acceptance Criteria
- Facility selection changes will be deployed to Staging environment and validated by the team
