### ISSUE TITLE
[FE] 10-10EZ - Screener question: Remove the 3 pages following the screener page

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#61746]
## Background
Over the last few years, in almost every research session we have held, there is feedback on the Screener pages that are presented after the Veteran enters their Name, DOB and SSN.  These screener pages (Personal information pages) are redundant and cause confusion, most especially (but not exclusively) for Veterans using screenreaders.

We want to remove the 3 pages that follow the screener page for unauthenticated applicants.

<details>
<summary>Pages that follow the Screener page- Screenshots (click to expand)</summary>

![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/ee6a7721-91d9-405d-b973-bcbebf9da56c)

![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/2d90f8a9-1eb6-45e9-99f8-8932d7357b25)

![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/f2020536-e52c-4a1d-bfc9-b301a54ca9d6)

</details>

## Tasks
- [x] Review [ticket #61198](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61198) for recent research into constraints to remove the pages
- [x] Remove the Veteran Name, SSN and DOB pages that follow the initial screener page (unauthenticated users only)
     - [Screenshot](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1688593774816/c44e309b107b8df7e9b8647d385ab4b0c8b7757a?wid=0-1688744100522) of screener page flowing directly to Place of birth page
- [x] Add the additional fields (Middle name and Suffix) to the current screener page
     - Simlilar to [this page](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/ee6a7721-91d9-405d-b973-bcbebf9da56c)
     - Keep the SSN and DOB fields
- [x] Use feature toggle to keep changes hidden in Production until changes are validated in Staging environment
- [x] Validate changes with PM/team
- [ ] Once approved, deploy to Production

## Acceptance Criteria
- The 3 repetitive, post-screener pages are removed from the EZ application for unauthenticated applicants

**Comment by longmd** [comment]
@hdjustice , this has been completed and is ready for final signoff. Here are some screenshots showing the the data in the ID form, the data set in Redux and the confirmation screen to show successful submission.

![Screenshot 2023-08-03 at 9 34 03 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/a0e32c58-202c-4e26-b517-c0709c75382b)

![Screenshot 2023-08-03 at 9 35 38 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/992249d5-8f24-4cc4-9bc7-6143b258c8d1)

![Screenshot 2023-08-03 at 1 50 33 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/79fac1d4-08f6-4bc9-8ee9-ecd727266993)

I also have a submission under the name David Michael Baker Jr. that we can triple check with Josh F on.

**Comment by hdjustice** [comment]
Validated that unauthenticated user that does not have a VA.gov account can enter their name, DOB and SSN, then be prompted to the rest of the application without being presented with their name, DOB and SSN again.

Also validated that an unauthenticated user who does have a VA.gov account can enter their name, DOB and SSN will be prompted to sign into VA.gov - as expected (tested with user 36).  I also tested without the middle name to be sure the MPI validate would still work, which it did.
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/b5c3f903-2d98-42fd-9442-65efd723cb5f)

**Comment by hdjustice** [comment]
@longmd - I noticed that the name, dob & SSN page is blank if I try to go back from the next page.  
I also noticed that when I enter new data, and hit continue, it does not take me to the next page, even if I enter the same information.  Is there anything we can do there?

**Comment by longmd** [comment]
So, if you go back from the form to that page it will always be blank as it is not actually a part of the form itself. It is a standalone page that just validates you are able to access the actual application. 

We can look at why you may not be able to get back into the application if you enter data again after going back. I suspect that has always existed in this exchange, but will have to do a little debugging on that.

**Comment by hdjustice** [comment]
Ok, thanks.  Let's check on that 2nd issue just to see if we can do anything about it.  I want to say I remember something about that during Short Form validation, not being able to go back to that screen & see data.  I am going to see about traffic going back to that page.  It may not be too much of an issue, but I can see an issue if some folks do go back & can't enter info again.

**Comment by longmd** [comment]
Okay, sweet. Yea, you cannot see data, because there is no data to see. You're not "in the form" at that point. You've essentially started over by going back. 

We should definitely be able to resubmit. I'll jump on that tomorrow and play around with it. We shouldn't have to accept not being able to perform that simple task.

**Comment by longmd** [comment]
All of the user info was on the Review page, because those pages are active in the form. With the pages inactive in the form, there will be no review opportunities for that. 

The one option I suggested when we first started talking about all this was a page after the ID Form that shows the data they input and essentially letting them confirm it at that time. Then once they move on for that, its over and done with. This is identical to what we show for authed users with their name, DOB, etc. 

We really shouldn't want users changing any of that data after it has been verified for enrollment status, MVI, VA.gov account, etc... because that data never gets reverified.

**Comment by hdjustice** [comment]
You are right.  Ok.  Let's spin up a ticket for the re-submission issue.  I will talk with design gang about adding that additional page  with the data input on the ID form.   Let's keep this one on hold until we get the additional page up.  I would feel more comfortable if people were able to review what they entered before moving on.

**Comment by longmd** [comment]
Can we go ahead and close this out, since the requirements for this have been met? Then we can spin up tickets for creating that confirmation page, enabling the feature, and resubmission?

**Comment by hdjustice** [comment]
Closing ticket.  Post-screener pages have been removed from the form flow and the additional fields needed for Middle name and Suffix have been added.  Additional enhancements will be addressed in other tickets.  
- resubmits (#63165) 
- enabling the feature (#63167)
