### ISSUE TITLE
[Tech Discovery] 10-10EZ - Data pre-fill: Technical discovery on Enterprise VA Profile for pre-filling the application

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#61743]
## Background
Today, we query the VA Profile API for Veteran information (name, address, phone, etc) and Service History.  
How might we be able to pre-fill more fields within the application to make it easier for Veterans to review and continue, rather than having to fill out everything?

We need to review what is available within VA Profile, and how that information might be available for us to pre-fill into the application, such as Spouse and Dependents, Income and Deductibles.

## Tasks
- [x] Review documentation available on VA Profile API (must be on VA network)
     - [VA Profile API sharepoint](https://dvagov.sharepoint.com/sites/OITEPMOVAPROPUB/SitePages/Getting-Started.aspx)
     - [Health Benefits Swagger Doc](https://qa.vaprofile.va.gov:7005/health-benefit/swagger-ui/index.html?configUrl=/health-benefit/v3/api-docs/swagger-config)
- [ ] Submit any outstanding questions to the Intake team (email or an intake ticket)
- [x] Gather all discovery information together and discuss with PM

## Acceptance Criteria
- Thorough research is done to determine what data we can query from VA Profile API to pre-fill the EZ application (this may also be useful for the EZR work going on).

**Comment by JoshingYou1** [comment]
Potential data we can pull from **VA Profile** that we might not already use:

### Contact Info
- Email address
### Demographic Info
- Race
- Religion
- Preferred language
- Marital status
### Health Benefits Info
- Healthcare coverage (plan type, company, effective date, etc.)
- Healthcare eligibility (enrollment date, enrollment priority group, income year, eligibility status, etc.)
- Veteran medical benefits (plan name, effective date)
- Healthcare (appoint request date, summary of visits, preferred facility)
### Gender Identity Traits Info
- Preferred name
- Pronoun
- Sexual Orientation
- Gender Identity
### Disability Rating Info
- Disabilities (primary & secondary disability type codes, evaluation history)
- Service-connected
- Unemployable
- housebound
### Military Personnel Data Info
- Summary (active duty status, combat service indicator, number of duty days)
- Medals and awards
- Military occupation
- Pay grade rank
- Retirement info
- Retirement pay
- Separation pay
- Combat pay
- Military service history (branch name, character of discharge, service dates)


**Note:** These were the categories and fields/field sets that jumped out to me. There are a LOT of fields, so if we want to get really granular, feel free to comment here and I can check for the requested fields in the profile API

**Comment by JoshingYou1** [comment]
If anyone is interested, <a href="https://dvagov.sharepoint.com/sites/OITEPMOVAPROPUB/SitePages/VA-Profile-Bio-Graphs.aspx?csf=1&web=1&e=hrFJXe">here's the link</a> to the page that has all of the different schemas within the VA profile API. These are much more readable than trying to dig through the swagger links lol, so hopefully it helps. With this, I think we can close out this ticket. If you do poke around and find something related to dependents and/or spouses, please reach out, because I could not.

**Comment by JoshingYou1** [comment]
Yeah, it doesn't look like the profile API is used for the data on that page. Perhaps the data is being pulled from another API that handles benefits data. It could be something similar to the ES, where, once submitted, a lot of data pertaining to dependents/spouse can be accessed.
