### ISSUE TITLE
[FE] Perform Accessibility Testing & Create Artifact

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#61740]
## Description
As a team, we need to perform accessibility testing so that we can ensure our feature is ready for release. 

## Tasks
- [x] Create an accessibility ticket/artifact using this [template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D)
- [x] Add the HCE-Checkin label to the accessibility ticket
- [x] Associate the accessibility ticket with this [Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61390)
- [x] Associate the accessibility ticket with this [collab cycle Epic ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53488 ) 
- [x] Complete & check-off each test in the accessibility ticket

**Comment by loripusey** [comment]
Since we are not doing Staging Review I guess we can close this one

**Comment by loripusey** [comment]
@wullaski We will need to do this now; re-opening and adding to current sprint

**Comment by wullaski** [comment]
@loripusey Everything looks good https://github.com/department-of-veterans-affairs/va.gov-team/issues/88188
