### ISSUE TITLE
[Frontend] Unit Test - Review Orders Page 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#6174]
## User Story 
As the world's most amazing dev I need to create a unit test for Review order page so that I can see if there are errors in the code 

## Tasks
- [ ] _Create unit test  
- [ ] _Refactor code, if necessary 

## Acceptance Criteria
- [ ] _test does not produce any errors
