### ISSUE TITLE
[FE] 10-10EZ - Print/save/download: Implement updates to Confirmation UI

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#61750]
**ON HOLD/Not Prioritized** - pending solution for adding multiple dependents on PDF

## Background
- We would like to provide an easy way for Veterans to download their application data entry, in an accessible format, for future reference.
- There have been past research findings indicating that Veterans prefer to print and/or save (download) a copy of their application input.
     - [2023 Supplemental Claims - PACT Act](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/Research/1222-PACT-Act/research-findings.md#finding-9)
- There is also historical data on the 10-10CG application that indicates applicants download the completed application just about every time (and sometimes more than once!)
     - Google Analytics - [Submissions and PDF Form downloads](https://analytics.google.com/analytics/web/#/dashboard/u4Zg-ougQpq-87e5dGIH_w/a50123418w177519031p184624291/_u.date00=20230101&_u.date01=20230630/)

<details>
<summary>Current Screenshot of 10-10CG application - Confirmation screen (Click to expand)</summary>

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/1dde92ef-cecf-4973-a338-8436f8c1696e)

</details>

### For this ticket
- We want to update the Confirmation screen UI, per design, to provide a link/button for Veterans to print/save/download their completed, submitted application. 

## Tasks
- [ ] Refer to [Design ticket #61748](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61748) 
- [ ] Refer to [Functionality development ticket #61751](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61751)
- [ ] Update UI to provide option to Veterans for print/save/download
- [ ] Use feature toggle to ensure changes are not visible in production until we are ready to release
- [ ] Validate update with PM

## Acceptance Criteria
- Confirmation Screen UI will be updated to provide option for the Veteran to print/save/download their completed application

**Comment by hdjustice** [comment]
erroneous ticket, no longer needed
