### ISSUE TITLE
[Frontend - Unit Test - Order Confirmation Page 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#6175]
## User Story 
As the world's most amazing dev I need to create a unit test for Select supplies order page so that I can see if there are errors in the code 

## Tasks
- [ ] _Create unit test  
- [ ] _Refactor code, if necessary 

## Acceptance Criteria
- [ ] _test does not produce any errors
