### ISSUE TITLE
FAKE ISSUE Usability Testing Prep - Medical Device Reordering Tool

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#6176]
## Steps to complete Usability Testing Prep: 
- [ ] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [ ] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [ ] Andrea and Megan to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [ ] VSP <> **requesting team** review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled meeting_
- Link to product outline ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md))
- Link to or attach prototype or mockups
- Link to or attach artifact with copy (if separate from prototypes/mockups)
- Link to research plan ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md)) and script ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md))
- Link to regression test plan ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#regression-test-plan)) (if there isn't already a regression test plan for this feature in TestRail) _for QA practice area review_
- Link to test cases/test plan in TestRail ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) (even if just a draft) _for QA practice area review_

## Meeting attendees from **requesting team**
- Product Manager (required): **name**
- DEPO product lead (required): **name**
- Anyone else from your team who significantly contributed to the artifacts provided (required): **names**

## Scheduling
Preferred dates or times: 

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product
