### ISSUE TITLE
[Design, FE] 10-10EZ - Improvement: 

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#61779]
## Background
As part of [content feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52920#issuecomment-1615190313) on the Household section feature, it was decided to address the Confirmation modal update as its own body of work not tied to any feature.  

Content Feedback:
>2. CONFIRM SCREEN
>https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/GomvmqL
>
>- Change "provide" to "share" (MUST - Aligning with use of "share" on previous screens/this should be consistency throughout.
>- And adjusted "Confirm" content and included text ahead of the bulleted list (Let's chat more about this on Friday, but I'm curious about thoughts your thoughts here and if this change would come at a later stage).
>- Question for you @jessicastump does one of the buttons need to go back to the previous screen?

## Tasks
- [ ] Design - Update design to reflect change as described - TBD
- [ ] Design - Inform Engineers this ticket is ready to pick up and complete
- [ ] Engineer - Update content to match updated design
- [ ] Engineer - Validate change in Staging with PM before Prod deployment window
- [ ] PM - Close ticket after validation

## Acceptance Criteria
- Confirm modal content is updated

**Comment by jessicastump** [comment]
We reviewed during the content sync today. We discussed that this is not a destruction action but more of a choice/fork in the road scenario so the decision was made to leave the content as is.

However... on the modal for the short form (we looked at these side by side) we noticed the header "Confirm that you receive service-connected pay for a 50% or higher disability rating." ended in a "." There should be no punctuation for the header in these featured content pieces per content recommendations. 

![FormSection.png](https://images.zenhubusercontent.com/62ed51a5a530e8b926b17214/823dd133-7fd3-4c6e-bd78-62aa9509fe6f)

**Comment by jessicastump** [comment]
[Sketch mockup ](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/B8338B0C-2E32-44D2-8204-66DEFA345FFE/canvas)

**Comment by longmd** [comment]
@jessicastump / @hdjustice , it looks like the period was removed from this title (I think when I was doing some of the unit test work). So If we are going to leave the content as is, we can close this one out.

![Screenshot 2023-08-02 at 10 26 21 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/17a952bd-dfba-42ae-8767-0e90d9882383)

**Comment by jessicastump** [comment]
Awesome! Yes, content had no other changes so it can be closed

**Comment by hdjustice** [comment]
closing ticket, thank you!
