### ISSUE TITLE
Create Veteran archetypes for Debt Resolution Team

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#61776]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

The Debt Resolution UX Research team wants to create **product-specific archetypes of the different types of Veterans that will fill out the FSR / Streamlined Waiver forms.** 

We have identified one such archetype: Veterans experiencing homelessness, as a possible archetype to understand further. 

These archetypes, filled in through past internal research, usability study research, future foundational research, and secondary research, will allow us to quickly follow design recommendations and guidelines based on specific archetypes with specific user needs. We will also be able to account for possible edge cases to consider as we improve the debt resolution experience. These archetypes will be a living, breathing document that will need to be updated and refined in the future as user needs change. 

---
## Tasks
- [x] _What work is necessary for this story to be completed?_
- [x] Review of internal research
- [x] Secondary internal and external research
- [x] Creation of 3-5 Veteran archetypes

## Acceptance Criteria
- [x] _What will be created or happen as a result of this story?_
- [x] A document of 3-5 Veteran archetypes specific to the Debt Resolution products, based on research
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mgleo** [comment]
[Journey of Veterans Map](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/design/va-product-journey-maps/Veteran%20Journey%20Map.pdf)

[Big list of Veteran Journey Maps](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/design/va-product-journey-maps)

**Comment by charlottecesana** [comment]
Update: I have started doing background research and I'm creating a deck to inform our process for this undertaking. I will present it at the sprint review tomorrow. I would like to carry this over to the next sprint when I will be here.  @Tom-Davis @HeatherRienks @josephrlee @mgleo

**Comment by charlottecesana** [comment]
Update: I am still working on the archetypes. 3 points can roll over (this task involves reviewing our prior studies and interviews as well as outside literature, so it's more time-intensive. 4 points might have been too low of an estimate - it's more like a 6 in terms of total effort!) 

@HeatherRienks
