### ISSUE TITLE
[FE] 10-10CG - Facility page: Connect search input to results list with Lighthouse API call

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#61786]
## Background
**Must complete ticket #57860 before this one**
To improve the Facility Selection experience, we are implementing new functionality to allow users to input their city, state or postal code and get a list of results from which they can choose. Using the bounding box coordinates obtained from the connection the MapBox API, we need to query the Lighthouse API and get the list of results to pass into the list component.

For this query, we need to pass the following:
- `bbox[]=` - The bounding coordinates from the MapBox API request
- `type=health`
- `services[]=CaregiverSupport`
- `page=1`
- `per_page=1000` - OR some large number that we don't think we can hit. We are not worried about pagination

Your query should end up looking something like this:
`v1/facilities/va?bbox[]=-83.2084&bbox[]=27.1978&bbox[]=-81.7084&bbox[]=28.6978&type=health&services[]=CaregiverSupport&page=1&per_page=1000`

### Resources
- [Initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/Improve%20Facility%20Selection/Improve%20Facility%20Selection%20-%20Initiative%20Brief.md)
- [Lighthouse API docs](https://developer.va.gov/explore/facilities/docs/facilities?version=current)

## Tasks
- [ ] Get list of coordinates on search from MapBox client
- [ ] Generate query based on coordinates and desired services
- [ ] Pass results to list component for render
- [ ] Ensure all work is implemented behind feature flag and not being ran in production

## Acceptance Criteria
- Connection is successfully established to Lighthouse, with data being returned.
- Results are passed to list component for render

**Comment by patrickvinograd** [comment]
The bounding box approach is totally viable, but just thought I'd point out that we had a similar use case for covid vaccine registration and there's also a `nearby` endpoint in the Lighthouse facilities API that just takes a lat/long and returns the x nearest facilities. You can see where it's used here: https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/covid_vaccine/app/services/covid_vaccine/v0/facility_lookup_service.rb

Note that we were doing a simple mapping from zipcode -> lat/long and then invoking Lighthouse, because zipcode was a required form field in that app - no provision for any kind of fuzzy city/state search or anything like that.

**Comment by hdjustice** [comment]
Removing from in-progress, pending Facilities team work:  LH facilities API v1 is available - but the vets-api proxy code that invokes the LH API is not updated to take advantage of the new feature.

**Comment by hdjustice** [comment]
ticket is no longer needed, work outlined has changed direction
