### ISSUE TITLE
[Design, FE] 10-10EZ - Improvements: Updates to Dependent dropdowns content

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#61780]
## Background
As part of [content feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52920#issuecomment-1615190313) on the Household section feature, it was decided to address the Dependent dropdowns content update as its own body of work not tied to any feature.  

Content Feedback:
>6. DEPENDENT BASIC INFORMATION
>- https://staging.va.gov/health-care/apply/application/household-information-v2/dependent-information?index=0
>- https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/5n2aM5x
>
>- We hadn’t previously seen the options in this drop down list – to better align with the content on the previous screen and to move away from gendered language here, I suggest we use “Child” and Stepchild” instead of “Daughter/Son” or “Stepdaughter/Stepson” (MUST/SHOULD - we should be consistent with the use of "Child" on previous screens. We should change the drop down options, if possible)
>- Remove “Mother” and “Father” here – they aren’t considered dependents (MUST - Mother and father/parents aren't on the paper version of the form, and there was SME feedback on another form that VA doesn't consider parents dependents)

>8. DEPENDENT ADDITIONAL INFORMATION
>- https://staging.va.gov/health-care/apply/application/household-information-v2/dependent-information?index=0
>- https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/nQQldKk
>
>- Noting that we discussed the flow being different depending on the relationship the Veteran selects on the previous screen (Child or Spouse). If they select spouse, they’d only need be shown the “did they live with you” and “did they earn income questions.” From staging, when I select spouse and then child, I got all three questions for both. This may be a note for developers! (SHOULD/COULD - could this be a post staging review change?)

## Tasks
- [ ] Design - Update design to reflect change as described - TBD
- [ ] Design - Inform Engineers this ticket is ready to pick up and complete
- [ ] Engineer - Update content to match updated design
- [ ] Engineer - Validate change in Staging with PM before Prod deployment window
- [ ] PM - Close ticket after validation

## Acceptance Criteria
- Dependent dropdown content is updated

**Comment by hdjustice** [comment]
Need to:
- Confirm with HEC on who is a dependent for purposes of filling out the form
- Confirm with ES if these options change or are removed.
