### ISSUE TITLE
[FE] 10-10EZ - Fix name string validation lengths

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#61799]
## Description
The `maxlength` values currently declared for the name fields in the 1010EZ schema do not match those that are in the downstream ES. We need to update these values to ensure our validation criteria matches. The `maxlength` values should be set for to the following:
- First name: 25
- Middle name: 30
- Last name: 35

## Related issue(s)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/59175

## Tasks
- [x] Update any manually-declared values in any schema declaration or overrides
- [x] Run schema update on `vets-website` when PR has been merged in to `vets-json-schema` repo
- [x] Coordinate with BE engineering and ES to ensure data is correctly validating

## Acceptance Criteria
- Validation values match between FE, BE, Schema & ES

**Comment by longmd** [comment]
[PR #785](https://github.com/department-of-veterans-affairs/vets-json-schema/pull/785) is pending for the Schema updates.

**Comment by longmd** [comment]
@lihanli , the FE changes are in staging. I am going to run a quick test with the schema update under the name "1010 Team". Could you check for that and maybe ping Josh F. to confirm it goes through to him as well?

**Comment by longmd** [comment]
Successfully verified with Josh F. that the test was received. 🚀
