### ISSUE TITLE
[FE] 10-10EZ - Facility Selection: Create connection from search input to MapBox API client

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#61791]
## Background
To improve the Facility Selection experience, we are implementing new functionality to allow users to input their city, state or postal code and get a list of results from which they can choose. In order to successfully query the Lighthouse API using the provided data from the search input (city, state and/or postal code) we need to connect to the MapBox API client. The result from that MapBox API request will be a set of boundary coordinates that we will then use in the API request to Lighthouse.

**NOTE:** We need to determine if we can use the same access token that is used for the CG facility selector for the EZ selector. If not we will need to obtain a new token.

### Resources
- [Initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Facility%20Selection/ReadMe.md)
- [MapBox API docs](https://docs.mapbox.com/)

## Tasks
- [ ] Work with PM to obtain access token for MapBox connection
- [ ] Create MapBox client and set up all necessary actions
- [ ] Test connection to ensure proper coordinates are being returned
- [ ] Ensure all work is implemented behind feature flag and not being ran in production

## Acceptance Criteria
- Connection is successfully established to MapBox client and bounding coordinates are returned.

**Comment by hdjustice** [comment]
Closing ticket - feature descoped
