### ISSUE TITLE
[FE] 10-10EZ - Facility Selection: Connect search input to results list with Lighthouse API call

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#61793]
## Background
To improve the Facility Selection experience, we are implementing new functionality to allow users to input their city, state or postal code and get a list of results from which they can choose. Using the bounding box coordinates obtained from the connection the MapBox API, we need to query the Lighthouse API and get the list of results to pass into the list component.

For this query, we need to pass the following:
- `bbox[]=` - The bounding coordinates from the MapBox API request
- `type=health`
- `page=1`
- `per_page=1000` - OR some large number that we don't think we can hit. We are not worried about pagination

Your query should end up looking something like this:
`v1/facilities/va?bbox[]=-83.2084&bbox[]=27.1978&bbox[]=-81.7084&bbox[]=28.6978&type=health&page=1&per_page=1000`

### Resources
- [Initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Facility%20Selection/ReadMe.md)
- [Lighthouse API docs](https://developer.va.gov/explore/facilities/docs/facilities?version=current)

## Tasks
- [ ] Get list of coordinates on search from MapBox client
- [ ] Generate query based on coordinates and desired services
- [ ] Pass results to list component for render
- [ ] Ensure all work is implemented behind feature flag and not being ran in production

## Acceptance Criteria
- Connection is successfully established to Lighthouse, with data being returned.
- Results are passed to list component for render

**Comment by hdjustice** [comment]
Closing ticket - feature descoped
