### ISSUE TITLE
[SPIKE] Retry new idea for appt statuses

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#61801]
## Description 

At design system meeting, Matt gave some feedback: 

* Status: has 4 variations (you checked in at, you can check in at, confirmed, it's been reviewed) 
* But, we can also try "You checked in at 8:55am" with a checkmark to make that one distinct. 
* And, then we need to make these updates on the detail pages too. 

https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1889

## Tasks

- [ ] Create wires with no status idea(s)
- [ ] Create artboards for each time of day (so they can user flow of the statuses)
- [ ] Represent to DS platform team 

## AC

- [ ] Create wires with no status idea(s)
- [ ] Create artboards for each time of day (so they can user flow of the statuses)
- [ ] Represent to DS platform team 
-
