### ISSUE TITLE
My VA: Sprint 21 (10/11/23 - 10/24/23)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#61803]
## Priorities
_At the end of this sprint, what do we want to have accomplished/delivered?_
1. Make progress on design updates to My VA (white card, "view all", cerner message)
2. Prep for usability study with dot indicator+ (conversation guide)
3. Documentation updates (product guide, FE documentation, etc)
4. BE support and tech debt

PTO
- Allison 10/11 - 10/12
- Samara 10/13
- Angela 10/20

# Onsite Notifications

## Unread Messages Dot Indicator (#63788)
**PM**
- [x] #66540 

**Research & Design**
- [ ] #67353

**FE**
- [ ] #67007 

# My VA

## My VA LOA1 Updates (#63424)
**Research/Design**
- [ ] #64509

## Removing My VA from Unauthenticated Header (#67054)
**FE**
- [ ] #67050

## My VA support of MHV on VA.gov Migration (#62258)
**Research & Design**
- [ ] #67261
- [ ] #67349 

**FE**
- [ ] #67262

## Unit & E2E Test Improvements (#61602)
**FE**
- [ ] #57471 
- [ ] #57472 
- [ ] #57462 

## General (#31611)
**Research& Design**
- [ ] #67372

**FE**
- [x] #62294 (_from previous sprint_) 

## Backend Support (#54241)
**BE**
- [ ] #66447 (_from previous sprint - validation only_)
- [x] #66455 (_from previous sprint_)
- [ ] #67500

### My VA (general)
- [ ] #65504 

### Benefit Application Drafts Enhancements (#60509)
- [x] #64493 

### Claim Status EVSS > Lighthouse (#54403)
- [x] #63291

**Comment by ajakabcin** [comment]
**Order of operations for My VA Sprint 21** ✨ 

**Research and Design** 
@aagosto90 
1. Start on design ideas for [67261](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67261) and [67349](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67349) so going into the conversation with MHV cartography we have designs in mind. _Aiming to have that meeting scheduled for early next week_.
2. While waiting for that discussion after design work, pick up dot indicator conversation guide: #67353 
3. Finalize white card design and documentation: #67372 
4. LOA1 documentation updates: #64509


**Engineers**
@allisonlu 
1. Finish moment.js library transition ticket: #62294
2. Attend MHV cartography meeting with Angela and AJ to understand technical needs around "view all" concept and ramifications of removing the Cerner message: #67262
3. Update unread messages logic on dot indicator: #67007 

@dellerbie 
1. Finish scoping the BE support tickets with Tom: #66455
2. Remove (hide) My VA from unauth header: #67050 (doing this earlier in the sprint to give sitewide time to review and for us to make adjustments if needed)
3. BE support work in [66448](https://github.com/department-of-veterans-affairs/va.gov-team/issues/66448) and [66446](https://github.com/department-of-veterans-affairs/va.gov-team/issues/66446)
