### ISSUE TITLE
My VA: Sprint 22 (10/25/23 - 11/07/23)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#61804]
## Priorities
_At the end of this sprint, what do we want to have accomplished/delivered?_
1. Link to MHV from My VA
2. Wrap up this phase of dot indicator work (finish unread logic, address findings from staging review, etc)
3. Implement white card design

## Team News & Availability
- Samara at DE offsite 10/25 - 10/26
- Tom OOO 10/27, 10/30
- AJ OOO 11/2

# Onsite Notifications

## Unread Messages Dot Indicator (#63788)
**PM**
- [ ] #68361 [PM] Dot Indicator: Submit PSIRR

**Research & Design**
- [x] #68290  [Design] Dot Indicator: Address styling issues in appointments card (dot indicator staging review) 
- [x] #68307 [Design] Dot indicator: Design and documentation updates for a11y findings
- [x] #67353 [Research] Dot Indicator: Create convo guide for usability study

**FE**
- [x] #67007 [FE] Onsite Notifications: Update dot indicator logic to capture all unread messages
- [x] #68293 [FE] Dot indicator: Update appointment card date and time styling (dot indicator staging review) 
- [x] #68309 [FE] Dot indicator: a11y fixes from staging review

## Onsite Notifications MVP(#30611)
**Research & Design**
- [x] #68319 [Design] Onsite Notifications: Update documentation to remove notification section

# My VA

## My VA LOA1 Updates (#63424)
**FE**
- [x] #67012 [FE] My VA LOA1 updates: Post-launch code cleanup

## General Enhancements(#31611)
**Design**
- [x] #67261 [Design] My VA: Designs for "view all" concept on My VA
- [x] #67349 [Design] My VA Health Care: Design alternative solution(s) for handling Cerner users on My VA
- [ ] #67953 [Design] Nametag: Design Space Force logo into Nametag
- [x] #67215 [Design] My VA: Update sketch files to reflect change in unauth header
- [x] #68318 [Design] My VA: Documentation and sketch file review/cleanup

**FE**
- [x] #67789 [FE] My VA: Review & fix disabled E2E tests
- [ ] #68314 [FE] My VA: Implement white card design on My VA 
- [x] #68659 

## Team Business
- [ ] #68317 Off-boarding/transition prep - Angela Agosto

## My VA PM Tasks (varying initiatives)
- [ ] #65504 [PM] Onsite Notifications: Update product documentation
- [x] #64494 [PM] My VA BAD section: Update 2 month stats for hiding "what benefits does VA offer?"

# Waiting on Deployment Issues or Validation
- [x] #67050 [FE] My VA: Remove My VA from unauth header
- [x] #57471 [FE] My VA: Write FE unit test for IconCTALink component
- [x] #57472 [FE] My VA: Write FE unit test for RenderWidgetDowntimeNotification component
- [ ] #66447 (_validation only_) [BE] Backend Support: Improve observability of BE services

**Comment by ajakabcin** [comment]
Order of operations for the sprint

**Design & Research - @aagosto90** 
1. Design and documentation updates for findings from dot indicator staging review: [68307](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68307) and [68290](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68290)
2. Share designs with Samara/team from [67261](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67261) and [67349](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67349)
3. Spaceforce logo for nametag: #67953
4. Transition/offboarding prep: #68317 
5. Documentation and sketch updates/review: [68318](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68318) and [68319](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68319)
6. Unauth header sketch updates: #67215 

FE - @allisonlu 
1. Review flaky E2E tests (get this out of the way in case there are things that will block us): #67789 
2. Finish updates to unread messages logic for dot indicator: #67007 
3. My VA LOA1 post launch code cleanup: #67012 
4. White card updates: #68314 
5. Updates from staging review findings: [68309](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68309) and [68293](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68293)
