### ISSUE TITLE
My VA: Sprint 25 (12/06/23 - 12/19/23)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#61808]
## Priorities
_At the end of this sprint, what do we want to have accomplished/delivered?_
1. We have a "roadmap" for v3 component migration work
2. Feature flag cleanup
3. Review of CST

### Team News & Availability
- _Last full sprint before holiday code freeze (12/22/23 - 1/2/24)_ ([full details here](https://depo-platform-documentation.scrollhelp.site/developer-docs/deployment-policies))

# My VA

## v3 Component Migration (#69482)
**FE**
- [ ] #69483

## My VA Claims and Appeals Improvements (#71287, #54403)
**PM**
- [ ] #71288 

**Research & Design**
- [ ] #71290

**FE**
- [ ] #71289 

**BE**
- [ ] #59817 (_from previous sprint_)

## My VA Sketch > Figma Migration (#72326)
**Research & Design**
- [ ] #72127 

## General (#31611)
**Research & Design**
- [x] #70910 

**FE**
- [ ] #65042 (_from previous sprint_)
- [ ] #68531  (_from previous sprint_)
- [ ] #70041 
- [ ] #66858 
- [ ] #70821 

# PM Tasks (Varying initiatives)
- [x] #65504 
- [ ] #70284
