### ISSUE TITLE
[SPIKE] Retry new idea for appt statuses

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#61802]
## Description 

At design system meeting, Matt gave some feedback: 

* Status: has 4 variations (you checked in at, you can check in at, [confirmed, it's been reviewed](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/nQDYAdl)) 
* But, we can also try "You checked in at 8:55am" with a checkmark to make that one distinct. 
* And, then we need to make these updates on the detail pages too. 

https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1889

In the future: we could add more statuses, e.g., "you can't check in any longer"

## Tasks

- [ ] Create wires with no status idea(s)
- [ ] Create artboards for each time of day (so they can user flow of the statuses)
- [ ] Represent to DS platform team (try to attend first Tuesday meeting)

## AC

- [ ] Create wires with no status idea(s)
- [ ] Create artboards for each time of day (so they can user flow of the statuses)
- [ ] Represent to DS platform team 
-

**Comment by benbrasso-agile6** [comment]
Taking to design system office hours today

**Comment by ytsaoca** [comment]
The platform team approved this version at the office hour.
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/qb8vQk2

**Comment by benbrasso-agile6** [comment]
LG
