### ISSUE TITLE
"File additional forms for your disability claim" work to pull content out of chart and make annual audit edits

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#61810]
## Issue Description
We want to have an accessible page for Veterans to get information about and links to additional forms they may need to fill out for their disability claim. Currently content is in a chart, and we need to present it differently so that it's accessible. 

---
## Tasks
- [x] Rework the page so there's no longer content delivered in chart format. 
- [x] Remove this form since it already lives in Housing hub: **Claiming Specially Adapted Housing or a Special Home Adaptation**
- [x] Remove this form since it now lives on the Supporting forms for VA claims page: **Authorizing the release of your medical records to VA**
- [x] Make edits for the annual audit.

## Acceptance Criteria
- [x] Draft page is up to date and accessible.
- [x] Ready for copyedit.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bethpottsVADEPO** [comment]
**Notes:**
**Claiming Individual Unemployability**
Forms 8940 and 4192 are both linked to from this Disability special claims page: https://www.va.gov/disability/eligibility/special-claims/unemployability/

**Claiming PTSD** / **Claiming PTSD based on a personal assault**
Forms 0781 and 0781a are both linked to from this Disability page: https://www.va.gov/disability/eligibility/ptsd/

**Claiming Specially Adapted Housing or a Special Home Adaptation**
Form 4555 is linked to from this Housing grant page: https://www.va.gov/housing-assistance/disability-housing-grants/how-to-apply/

**Claiming an auto allowance** / **Claiming an auto adaptive-equipment grant**
Forms 4502 and 1394 are both linked to from this Disability special claims page: https://www.va.gov/disability/eligibility/special-claims/automobile-allowance-adaptive-equipment/

**Claiming additional benefits because you or your spouse needs Aid and Attendance** / **Claiming Aid and Attendance because you're in a nursing home**
Forms 2680 and 0779 are both linked to from this Pension page: https://www.va.gov/pension/aid-attendance-housebound/

**Claiming dependents**
Forms 686c is an online application now from the View or change dependents page: https://www.va.gov/view-change-dependents
Form 674 is available from this page too, but only in PDF form.

**Comment by bethpottsVADEPO** [comment]
We may want to consider adding this form that isn't included in the current chart:
https://www.va.gov/disability/eligibility/special-claims/clothing-allowance/
An Application for Annual Clothing Allowance (VA Form 10-8678)
Get VA Form 10-8678 to download
Bring it to the prosthetic representative at your local VA medical center.

For the below type of claim, it's a separate form (below) instead of a disability claim plus an additional form (so this isn't an additional form it's THE form):
https://www.va.gov/disability/eligibility/special-claims/birth-defects/
Application for Benefits for Certain Children with Disabilities Born of Vietnam and Certain Korea Service Veterans (VA Form 21-0304).
Get VA Form 21-0304 to download

**Comment by bethpottsVADEPO** [comment]
Need to confirm which of the above additional forms now are accounted for in the 526 flow. We already have a nod to that in the current chart for:

- PTSD (both 0781 and 0781a)

Need to check on:

- Individual Unemployability
- Auto allowance
- Auto adaptive-equipment grant
- Dependents

**Comment by bethpottsVADEPO** [comment]
This work is complete. Closing.
