### ISSUE TITLE
Decision Reviews | Set up real user monitoring for NOD, HLR, and Supp Claims

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#61817]
## Issue Description

We want to pilot DataDog RUM for our Decision Reviews portfolio. It should be pretty easy to set up for all our forms, in one fell swoop, once we're given access. Steve is working on that now, and it doesn't seem like we'll have a problem getting that access.

---
## Tasks

- [ ] Get access to create RUM
- [ ] Create RUM dashboard for NOD
- [ ] Create RUM dashboard for Supp Claims
- [ ] Create RUM dashboard for HLR

## Definition of Ready
- [ ] Access to create RUM

## Definition of Done
- [ ] Dashboards created.

**Comment by jeremy6d** [comment]
What is the end date and success criteria for the feature flag? This helps us on platform keep track of which flags are in play so we can keep them tidy for all VFS teams. Thanks!

**Comment by Mottie** [comment]
We don't really have an end date since it'll be used for monitoring. Success criteria would be Datadog isn't capturing and displaying PII

**Comment by saderagsdale** [comment]
Will start at 10% of submissions

**Comment by Mottie** [comment]
Set to 10% users with in progress NOD

**Comment by Mottie** [comment]
[Datadog UX monitoring dashboard](https://vagov.ddog-gov.com/rum/sessions?cols=&from_ts=1692029546409&live=true&query=%40application.id%3Acabce133-7a68-46ba-ac9b-68c57e8375eb+%40type%3Asession+env%3Aproduction&to_ts=1692115946409)

**Comment by saderagsdale** [comment]
@Mottie I think you can review this with Rocio and consider it complete. Non-devs may not be able to access this view until Steve gets us access.

**Comment by Mottie** [comment]
Hiding PII is still a WIP... I added a [comment in the public datadog channel](https://dsva.slack.com/archives/C01G6J7UGGH/p1692194411395939)

> I was reviewing a session replay today and noticed a few things:
> - Veteran clicks on a checkbox with an aria-label, it shows the label text (which includes PII) in the events panel.
> - I doesn't look like our web components are rendered
> - Hidden content shifts the page so clicks do not align visually with elements
> - Icons and images are not rendered

The response was once we update Datadog to v4.31.0, it will support web components, but no response about the other issues I noted.

**Comment by Mottie** [comment]
It appears that [override the action name](https://docs.datadoghq.com/real_user_monitoring/session_replay/privacy_options/#override-the-action-name) method _may_ fix the PII issue. Will implement this change soon

**Comment by Mottie** [comment]
Adding `data-dd-action-name` did solve this problem, but now I've discovered that clicking on anything, even DOM that isn't interactive, will record an event with the text content. So we may need to add `data-dd-action-name` to everything.
<img width="1153" alt="Click on date of birth: February 14, 1..." src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/1c467eec-1d30-4c3f-b553-775a8e82986e">

**Comment by HeatherWidmont** [comment]
Eugene to look through a bunch of these reportings & will close the ticket if everything looks good

**Comment by data-doge** [comment]
@Mottie Thank you for your work on this! So close. I could only find one remaining area where PII/PHI was exposed:

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/7520103/18e12685-ad22-44e3-8fbf-fe14c8bba285)

**Comment by Mottie** [comment]
@data-doge Hmmm... I think that PHI is being shown from inside the shadow DOM. The FE can only pass a plain string into the [ va-checkbox `message-aria-describedby` property](https://design.va.gov/storybook/?path=/docs/components-va-checkbox--default)

<img width="723" alt="Screenshot 2023-09-05 at 8 35 23 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/49b202ec-e549-4a70-9f28-0565c6e42bf8">

So, we can either add a `dd-privacy-hidden` class to the `sr-only` class in the shadow DOM (Component library change), or ask Datadog to hide `sr-only` (screen-reader only) content

**Comment by HeatherWidmont** [comment]
@Mottie filed a platform support ticket, blocked until that's taken care of

**Comment by saderagsdale** [comment]
@Mottie Can you post a link to the platform ticket and an update?

**Comment by saderagsdale** [comment]
@Mottie will check for an update in platform thread ([slack thread](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64871)).

**Comment by saderagsdale** [comment]
Followed up with Kerry in the thread today.

**Comment by Mottie** [comment]
I merged in a fix 5 days ago. We're now waiting for the component library to be updated in vets-website

**Comment by HeatherWidmont** [comment]
@Mottie is this finished or are we still waiting on anything?

**Comment by Mottie** [comment]
We're still waiting on the component library to be updated in the vets-website... I can do that now

**Comment by HeatherWidmont** [comment]
Awesome, thank you so much @Mottie!! 

cc @data-doge @saderagsdale

**Comment by Mottie** [comment]
Whelp, this might be blocked... While updating the component library to v21.0.0, a lot of errors around usage of the React pagination component are showing up. I think the static pages are still using it, but the [design system team has removed the deprecated component](https://dsva.slack.com/archives/CBU0KDSB1/p1695064641707189?thread_ts=1695062665.696099&cid=CBU0KDSB1)

**Comment by saderagsdale** [comment]
@Mottie Is the solution approach to ask the platform team to fix something or for us to switch to updated components? Let me know so I can post in if needed. #platform-design-system

**Comment by HeatherWidmont** [comment]
Shouldn't be blocked anymore, we have to wait until staging is updated. This might be able to be finished today as well.

**Comment by Mottie** [comment]
Well, we're blocked again. Updating the component library caused a lot of issues due to completely removing several deprecated components, so they are rolling back the update.

**Comment by Mottie** [comment]
We were unblocked at the end of business yesterday. After testing NOD in staging. [I scanned through this RUM session replay](https://vagov.ddog-gov.com/rum/replay/sessions/249d59dd-f90b-4145-8f0a-436de2a6826b?seed=d789b46a-68bc-40f2-88bb-73919186a516&ts=1695217761369) for my interactions and did not notice any PII/PHI being revealed.
