### ISSUE TITLE
[FSR] SW - Update transform and helpers

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#61839]
## Issue Description
Our final `transform` has gotten a little cluttered with the various feature flags and other general updates. Let's break it up into more manageable chunks. Mostly looking to break out separate feature flag functionality so we can more easily remove them. It could also help to organize by major chapters with comments describing the final pdf location the values will be populated in. 

We also noticed recently that our `helpers.js` has some transform specific functionality in there, but it might be easier to manage if they were separate from generic helper functions. 

---
## Tasks
- [ ] Break out transform functionality by feature flag and chapter level calculations.
- [ ] Update helpers so transform specific functionality is broken out

## Acceptance Criteria
- [ ] Transform feature flag functionality is more manageable. 
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
This is probably best done after **Create example submission objects for BE** [#61843](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/61843) since we can get a good idea of what the shortened input objects are, and we can see how the transform breaks with it

**Comment by amponce** [comment]
Draft pr is up, I'm writing some tests, and will convert to full PR tomorrow

**Comment by amponce** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/25053
