### ISSUE TITLE
[ENGINEER] Confirm and test update of node with Content Block-accordion as used in Facilities pages [Engineer]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#6183]
## User Story or Problem Statement
As a Data Tech, I need an optimized way to set content blocks/accordions into existing pages, so I can reduce time in loading and completing page content in VAMC- Web page/nodes.

## Goal
_Implement required va.gov webpages_

## Objectives or Key Results this is meant to further
- _Increase pages/nodes completed in a quarter_

## Resources - Tools - Documentation
[Pittsburgh Facility Page example](https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/)

## Tasks
_Creation of the following Drupal types/menus and pages_
- [ ] Research to confirm if content can be added to existing node
- [ ] If it is possible to add content, compose script to test in One of the existing Staging Pages with coordination with CMS team.
- [ ] Complete testing and determine results.

## Acceptance Criteria
_Validate outcome of pushing content to existing page_
* Can content be pushed to existing
* Coordination and confirmation with CMS team
* All testing to be complete in Staging environment
