### ISSUE TITLE
Archive #console-services-notifications Slack channel

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#61849]
[#console-services-notification](https://dsva.slack.com/archives/C039HRTHXDH) can be deprecated to reduce the number of channels that need to be watched. At first glance, there are only three items that are sent to that channel. One datadog monitor and two ruby-related notifications. We can move the Datadog monitor to #oncall channel (and let's make it actionable in the process), and the two Ruby notifications to #platform-cop-devops.

### Tasks
- [ ] Change the [Resource mobile::v0::paymenthistorycontroller_index has a high p95 latency on env:eks-prod monitor](https://vagov.ddog-gov.com/monitors/93625) to alert in the oncall channel. It can be edited in the Datadog UI (it's not a monitor created in Terraform)
  - [ ] Edit the message in the alert to be actionable. What does this alert mean and what actions need to be taken to resolve this issue? Link any relevant documentation or dashboards that can help with debugging.
- [ ] **Ruby News** is an app that posts in the channel. We care about this. Move it to #platform-cop-backend.
- [ ] **Rubygems**  - also move this app to post in #platform-cop-backend.
- [ ] Double check that there are no other alerts or anything coming into #console-services-notification and move them as well.
- [ ] Archive #console-services-notification

### Acceptance criteria
- [ ] All tasks are complete.

**Comment by rmtolmach** [comment]
During the Backend CoP meeting on 11/20/23, we decided we want to keep this channel active.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/10993987/02e3ccd7-5af8-4eaa-8967-e9e5d9ff24f8)

✅ Eric updated the channel name to #platform-cop-be-notifications and I updated the channel name in [backend CoP responsibilities confluence](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities)

Closing this ticket.
