### ISSUE TITLE
[FSR] SW - Create example submission objects for BE

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#61843]
## Issue Description
Since streamlined is cutting off some of the form, we need to create examples of submission objects for the different routes so BE can adjust the required fields. Let's see if we can work out specific flags for each path? that way we have established expectations for each and it will hopefully make troubleshooting any problems easier. 

---
## Tasks
- [x] Create example submission objects for each FSR path for streamlined waiver
  - [x] maximal object 
  - [x] minimal object

## Acceptance Criteria
- [x] BE has submission examples for new SW flow.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by amponce** [comment]
Dan Path Minimal Submission Object

{
    "personalIdentification": {
        "ssn": "4437",
        "fileNumber": "4437",
        "fsrReason": ""
    },
    "personalData": {
        "veteranFullName": {
            "first": "Mark",
            "middle": "",
            "last": "Webb"
        },
        "address": {
            "addresslineOne": "1200 Park Ave",
            "addresslineTwo": "c/o Pixar",
            "addresslineThree": "",
            "city": "Emeryville",
            "stateOrProvince": "CA",
            "zipOrPostalCode": "94608",
            "countryName": "US"
        },
        "telephoneNumber": "(510) 922-4444",
        "dateOfBirth": "10/04/1950",
        "married": false,
        "spouseFullName": {
            "first": "",
            "middle": "",
            "last": ""
        },
        "agesOfOtherDependents": [],
        "employmentHistory": []
    },
    "income": [
        {
            "veteranOrSpouse": "VETERAN",
            "monthlyGrossSalary": "0.00",
            "deductions": {
                "taxes": "0.00",
                "retirement": "0.00",
                "socialSecurity": "0.00",
                "otherDeductions": {
                    "name": "",
                    "amount": "0.00"
                }
            },
            "totalDeductions": "0.00",
            "netTakeHomePay": "0.00",
            "otherIncome": {
                "name": "",
                "amount": "0.00"
            },
            "totalMonthlyNetIncome": "0.00"
        },
        {
            "veteranOrSpouse": "SPOUSE",
            "monthlyGrossSalary": "0.00",
            "deductions": {
                "taxes": "0.00",
                "retirement": "0.00",
                "socialSecurity": "0.00",
                "otherDeductions": {
                    "name": "",
                    "amount": "0.00"
                }
            },
            "totalDeductions": "0.00",
            "netTakeHomePay": "0.00",
            "otherIncome": {
                "name": "",
                "amount": "0.00"
            },
            "totalMonthlyNetIncome": "0.00"
        }
    ],
    "expenses": {
        "rentOrMortgage": "0.00",
        "food": "0.00",
        "utilities": "0.00",
        "otherLivingExpenses": {
            "name": "",
            "amount": "0.00"
        },
        "expensesInstallmentContractsAndOtherDebts": "0.00",
        "totalMonthlyExpenses": "0.00"
    },
    "discretionaryIncome": {
        "netMonthlyIncomeLessExpenses": "0.00",
        "amountCanBePaidTowardDebt": "0.00"
    },
    "assets": {
        "cashInBank": "0.00",
        "cashOnHand": "0.00",
        "usSavingsBonds": "0.00",
        "stocksAndOtherBonds": "0.00",
        "realEstateOwned": "0.00",
        "totalAssets": "0.00"
    },
    "installmentContractsAndOtherDebts": [],
    "totalOfInstallmentContractsAndOtherDebts": {
        "originalAmount": "0.00",
        "unpaidBalance": "0.00",
        "amountDueMonthly": "0.00",
        "amountPastDue": "0.00"
    },
    "additionalData": {
        "bankruptcy": {}
    },
    "applicantCertifications": {
        "veteranSignature": "Mark  Webb",
        "veteranDateSigned": "07/24/2023"
    },
    "selectedDebtsAndCopays": [
        {
            "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "pSSeqNum": "1.00",
            "pSTotSeqNum": "1.00",
            "pSFacilityNum": "757",
            "pSFacPhoneNum": null,
            "pSTotStatement": "3.00",
            "pSStatementVal": "0000037953E",
            "pSStatementDate": "05242023",
            "pSStatementDateOutput": "05/24/2023",
            "pSProcessDate": "12102020",
            "pSProcessDateOutput": "12/10/2020",
            "pHPatientLstNme": "HHUFHYULSEHU",
            "pHPatientFstNme": "CDAA",
            "pHPatientMidNme": "A",
            "pHAddress1": "7780 RED MAPLE CT",
            "pHAddress2": null,
            "pHAddress3": null,
            "pHCity": "HUBER HEIGHTS",
            "pHState": "OH",
            "pHZipCde": "45424",
            "pHZipCdeOutput": "45424",
            "pHCtryNme": null,
            "pHAmtDue": "105.24",
            "pHAmtDueOutput": "105.24&nbsp;&nbsp;",
            "pHPrevBal": "103.21",
            "pHPrevBalOutput": "103.21&nbsp;&nbsp;",
            "pHTotCharges": "2.03",
            "pHTotChargesOutput": "2.03&nbsp;&nbsp;",
            "pHTotCredits": "0.00",
            "pHTotCreditsOutput": ".00&nbsp;&nbsp;",
            "pHNewBalance": "105.24",
            "pHNewBalanceOutput": "105.24&nbsp;&nbsp;",
            "pHSpecialNotes": null,
            "pHroParaCdes": "0125304050556065708085",
            "pHNumOfLines": "2.00",
            "pHDfnNumber": "197750.00",
            "pHCernerStatementNumber": "0.00",
            "pHCernerPatientId": "                ",
            "pHCernerAccountNumber": "                ",
            "pHIcnNumber": "                 ",
            "pHAccountNumber": "7570000000197750.00",
            "pHLargeFontIndcator": "0.00",
            "details": [
                {
                    "pDDatePosted": null,
                    "pDDatePostedOutput": "",
                    "pDTransDesc": "INTEREST/ADM. CHARGE (Int:0.10 Adm:1.93 Other:0.00",
                    "pDTransDescOutput": "INTEREST/ADM. CHARGE (Int:0.10 Adm:1.93 Other:0.00",
                    "pDTransAmt": "2.03",
                    "pDTransAmtOutput": "2.03&nbsp;&nbsp;",
                    "pDRefNo": null
                },
                {
                    "pDDatePosted": null,
                    "pDDatePostedOutput": "",
                    "pDTransDesc": "Please refer to previous statement of rights.",
                    "pDTransDescOutput": "&nbsp;&nbsp;&nbsp;Please refer to previous statement of rights.",
                    "pDTransAmt": "0.00",
                    "pDTransAmtOutput": ".00&nbsp;&nbsp;",
                    "pDRefNo": null
                }
            ],
            "station": {
                "facilitYNum": "757",
                "visNNum": "10",
                "facilitYDesc": "CHALMERS P WYLIE VA ACC (757)",
                "cyclENum": "004",
                "remiTToFlag": "L",
                "maiLInsertFlag": "0",
                "staTAddress1": "420 N JAMES RD",
                "staTAddress2": null,
                "staTAddress3": null,
                "city": "Columbus",
                "state": "OH",
                "ziPCde": "432191834",
                "ziPCdeOutput": "43219-1834",
                "baRCde": "*432191834203*",
                "teLNumFlag": "S",
                "teLNum": "1-866-812-0318",
                "teLNum2": null,
                "contacTInfo": null,
                "dM2TelNum": null,
                "contacTInfo2": null,
                "toPTelNum": null,
                "lbXFedexAddress1": null,
                "lbXFedexAddress2": null,
                "lbXFedexAddress3": null,
                "lbXFedexCity": null,
                "lbXFedexState": null,
                "lbXFedexZipCde": null,
                "lbXFedexBarCde": null,
                "lbXFedexContact": null,
                "lbXFedexContactTelNum": null,
                "facilityName": "Chalmers P. Wylie Veterans Outpatient Clinic"
            },
            "debtType": "COPAY"
        }
    ]
}

**Comment by amponce** [comment]
Link to: [presubmit data](https://gist.github.com/amponce/e5cbb0adf68f9374f4e094d839188082#file-03-presubmit-minimal-json)

**Comment by amponce** [comment]
Link to draft PR with saved objects:

https://github.com/department-of-veterans-affairs/vets-website/pull/24979/files

**Comment by amponce** [comment]
# Discovery Notes

## Final Sample Objects for BE

We landed on the convention: long and short for the naming convention

```json
{
  "streamlined": {
    "value": true,
    "type": "short" 
  },
  "streamlined": {
    "value": false,
    "type": "long" 
  }
}
```

### Short:

[Link to Data](https://raw.githubusercontent.com/department-of-veterans-affairs/vets-website/f4ae85cc11c2cd402c657578604b24a430190bb2/src/applications/financial-status-report/tests/e2e/fixtures/data/dan-submissionObject.json)

### Long:

[Link to Data](https://raw.githubusercontent.com/department-of-veterans-affairs/vets-website/f4ae85cc11c2cd402c657578604b24a430190bb2/src/applications/financial-status-report/tests/e2e/fixtures/data/zoey-submissionObject.json)

## Transform Cleanup

We need to make a few adjustments to allow the short forms to make it through our data transform.

1. [utils/transform.js](https://github.com/department-of-veterans-affairs/vets-website/pull/24979/files#diff-bcc375481a9a36c8e85728a9b755da97602946097b2c5f67b2fe11d499b0d2f4)

2. [utils/helpers.js](https://github.com/department-of-veterans-affairs/vets-website/pull/24979/files#diff-85d234c379f741928f6a0aa209d5c27766a4dba1f971e1f08cd52fbb302b1ac2)

## Summary of Work to Improve the Transform Development Experience

- **Large function:** The transform function is quite large and does a lot of things. It would be more maintainable to break it down into smaller, more focused functions. Each function should do one thing and do it well. 

- **Destructuring and default values:** The code is destructuring form data and providing default values at the same time. While this is not necessarily a bad practice, it can lead to confusion when the structure of the form data is complex. 

Maybe it might be clearer to separate these two operations?

- **Error handling:**  It appears that there are instances where the code is trying to read properties of undefined, which I resolved in the PR but this likely means that the data structure is not always consistent. To improve this, you can add null checks or use optional chaining (e.g., `someObj?.someProp`) to prevent runtime errors.

- **Repeated patterns:** There are repeated patterns in the code, like filtering and summing values. These could be extracted into separate helper functions to reduce duplication.

- **Data transformations:** Much of the code is transforming data from one format to another. It may be useful to create a series of small transformation functions that can be composed to create the final data structure. 

- **Modern JavaScript features:** Consider using modern JavaScript features like `async/await`, `map/filter/reduce`, and template literals where appropriate. These can make the code more readable and idiomatic.

- **Comments:** Adding more comments to explain what different parts of the code are doing would also be beneficial. This would especially help any new developers (or even your future self) who might need to understand and work on the code.

**Comment by amponce** [comment]
One possible way to improve the readability of the transform could be through reusable modules and separation of concerns. However, when I attempted this, I ultimately reverted back to the current method, as it seemed less readable in my opinion.

here's en example I was exploring:

```
function calculateGrossSalary(isEnhancedFSRActive, employmentRecords, grossSalaryField) {
  return isEnhancedFSRActive
    ? sumValues(employmentRecords, 'grossMonthlyIncome')
    : sumValues(grossSalaryField, 'grossSalary');
}

function calculateAdditionalIncome(addlIncRecords) {
  return sumValues(addlIncRecords, 'amount');
}

function calculateSocialSecAmt(isEnhancedFSRActive, socialSecurity) {
  return !isEnhancedFSRActive
    ? Number(socialSecurity.socialSecAmt?.replaceAll(/[^0-9.-]/g, '') ?? 0)
    : 0;
}

function calculateBenefits(income) {
  const comp = sumValues(income, 'compensationAndPension');
  const edu = sumValues(income, 'education');
  return comp + edu;
}

function calculateDeductions(isEnhancedFSRActive, employmentRecords, currEmployment) {
  return isEnhancedFSRActive
    ? employmentRecords
        ?.filter(emp => emp.isCurrent)
        .map(emp => emp.deductions)
        .flat() ?? 0
    : currEmployment?.map(emp => emp.deductions).flat() ?? 0;
}
```

```
// veteran
const vetGrossSalary = calculateGrossSalary(enhancedFSRActive, employmentRecords, currEmployment);
const vetAddlInc = calculateAdditionalIncome(addlIncRecords);
const vetSocSecAmt = calculateSocialSecAmt(enhancedFSRActive, socialSecurity);
const vetBenefits = calculateBenefits(income);
const vetDeductions = calculateDeductions(enhancedFSRActive, employmentRecords, currEmployment);

// spouse
const spGrossSalary = calculateGrossSalary(enhancedFSRActive, spEmploymentRecords, spCurrEmployment);
const spAddlInc = calculateAdditionalIncome(spAddlIncome);
const spSocialSecAmt = calculateSocialSecAmt(enhancedFSRActive, socialSecurity.spouse);
const spBenefits = calculateBenefits(benefits.spouseBenefits);
const spDeductions = calculateDeductions(enhancedFSRActive, spEmploymentRecords, spCurrEmployment);
```
