### ISSUE TITLE
[FSR] SW - Implement income limit back end

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#61841]
## Issue Description
Implement income limit threshold back end to fetch limit based on number of dependents and zip code. Store GMT in redux and calculate 150%, 6.5%, and 1.25% of GMT to be used for routing. 

---
## Tasks
- [ ] Implement income limits api calls to fetch GMT based on dependents and zip code
- [ ] Store GMT in Redux with percentage calculations for routing.

## Acceptance Criteria
- [ ] Income limits fetching is implemented and values are stored in redux.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
Closing out now the api requeest is defined. Will implement with **Add new chapter level depends and structures** [#61842](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/61842) work
