### ISSUE TITLE
[FSR] SW - Add new chapter level depends and structures

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#61842]
## Issue Description
Once income limits back end has been implemented we can create new chapter level depends based on [streamlined branching](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1678973946956/6f3bb65fe1ccc2b9d3bc38cd24cd09e74d18d778?sender=u7f58f2afe2ea053d4dea4234). 

---
## Tasks
- [x] Create new chapters for streamlined waiver feature flag
- [x] Add depends to new chapters based on income limit requirements 
- [ ] Create new e2e tests for different branches
  - See mural above for branching and examples (i.e. Dan, Ana, etc)
  - This will probably be a lot to add, so we can break it out in new ticket(s) 

## Acceptance Criteria
- [x] New SW chapters are created with depends
- [ ] Include e2e tests for new flows
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
Can be worked in conjunction with **[FSR] SW - Move marital status and dependents pages [#61862](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/61862)**

**Comment by Dr-Pongo** [comment]
This will roll over into 105

**Comment by Dr-Pongo** [comment]
Closing out now that the PR was merged and streamlined functionality is implemented! e2e tests for new paths are being worked in a separate tikcet
