### ISSUE TITLE
[FSR] SW - New transition pages

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#61844]
## Issue Description
New streamlined waiver functionality includes new transitional pages if the user meets the requirements for a shortened version. We will also need to include a new page specifically for the "Dan" path that asks about cash on hand (separate from the current monetary assets checklist). This page will only show if the user follows this specific path, and everyone else will see the standard question. (We can always break out other new pages into separate tickets)

[uxpin example](https://preview.uxpin.com/6940f648e5994b8fad9550934a5530b4cd73cacb#/pages/163533702/simulate/sitemap?mode=cvhid)

#### Transitional page
![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/5517beae-80c3-4f8b-99a3-12fd5f3c333b)

#### Cash on hand page
![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/0277f0c3-a86a-4a38-b9e1-5c6cb44b0fcc)

---
## Tasks
- [ ] Implement new transitional page(s)
- [ ] Coordinate with design on any new pages or copy changes
  - [ ] Spin new tickets if there will be too much bloat

## Acceptance Criteria
- [ ] New transitional page(s) implemented.
- [ ] (optional) new tickets created for other copy/design changes for SW
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
Moving to in progress since the pages help with work on [Add new chapter level depends and structures#61842](Add new chapter level depends and structures#61842). They are slightly more than just test pages on the branch, so they just need to be fleshed out a little better to match design.

**Comment by HeatherRienks** [comment]
Per @Dr-Pongo, this should be fairly low LOE, and anyone can assist if this isn't able to be completed prior to 8/10
