### ISSUE TITLE
FE Discovery: Google analytics tags in the form components 

### ISSUE THREAD

**Issue by Nyanteea** [department-of-veterans-affairs/va.gov-team#61856]
## Issue Description
The Platform website suggests that there are analytics tags embedded in some of the design/form components. Understanding where those are embedded and how they are triggered may help us better understand how metrics are being tracked/defined. 

[Platform Resource on Components with tracking embedded  ](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/google-analytics-and-google-tag-manager)

[List of tracked interactions](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/google-analytics-data-dictionary)

To help understand -
- What might be triggering "completed" steps vs how we want to count them
- What might be triggering "exit" from a page/form vs how we want to count them
---
## Tasks
- [ ] FE to do discovery into code to identify embedded tags and document 

## Acceptance Criteria
- [ ] Understand where analytics tags are within the form and how they are triggered
- [ ] What custom tracking has been added and possibilities for additional custom tracking
- [ ] FE, UX Product from TREX & Carbs meet to discuss implications 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Nyanteea** [comment]
@christinec-fftc @RakshindaAslam

**Comment by RakshindaAslam** [comment]
cc @austinjprice @juliepedtke @christinec-fftc @Nyanteea 
- Discuss if this is necessary for the first funnel update or can it inform the next iteration?

**Comment by christinec-fftc** [comment]
## Discovery Summary ##

The following findings are the result of going through platform documentation, sifting through 526 front end code, going to analytics office hours, and talking to other FE eng's.

**1) what triggers a completed step?**
![image.png](https://images.zenhubusercontent.com/641341411444ec27c3eb60a4/15bab953-cda5-41bf-b01a-e80776381129)
A step has a step number, title, and page url.  The steps are defined by the team when writing the request to build the funnel. A completed step is when a user moves from one page in the funnel to the next page in the funnel.

For a given page, there may be a number of required fields that would prevent the user from moving to the next step/page, so when a user clicks the Continue button to successfully go to the next page, we know that the user has completed that step.

Doc on [Form completion](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/data-dictionary-va-gov-forms-kpis#Datadictionary:VA.govFormsKPIs-Formcompletion)

**2) what triggers an exit?**
![image.png](https://images.zenhubusercontent.com/641341411444ec27c3eb60a4/ef6d51a9-5e62-4610-905b-cfb7b0f4a732)

An exit is when a user is in the 526 form/application and leaves the funnel altogether. The last page the user was on is noted on the ‘Exit rate by step' report.

Note that going back and forth through the 526 form does not count as an exit.

Doc on [exits](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/data-dictionary-va-gov-forms-kpis#Datadictionary:VA.govFormsKPIs-Formtiming&exits)

**3) what analytics tags are within the form and how are they triggered?**
Each VA component from the component library has an event ‘component-library-analytics’ which tracks the usage of the component. Depending on the component, additional event tracking may also be used, e.g. when a button is clicked or when a form element’s value changes. 

See [storybook](https://design.va.gov/storybook/?path=/story/about-introduction--page) for documentation on each component’s analytics events
See [What is being tracked? ](https://docs.google.com/presentation/d/1VqFTJso8IkatklBSvbW--dc9j51SNLh9nDedoEoTyDU/edit#slide=id.gefa2fe5bca_0_57)

**4) what are the custom analytics uniquely built into the 526 form?**
For record event's, there were 15 instances of custom analytics calls found in all-claims. One was found for the introduction page, two were found for form submissions and the rest were added to subtask pages.

For record event once's, there were 11+ instances. 10 of them were additional info components where user clicks to expand help text. 1 was for a utility function used throughout for missing fields.

See [526 custom analytics events](https://docs.google.com/spreadsheets/d/1LPlEQRhhfOV5zjwB2Sm6qXbhAFcV_YY6jBBnHygII_k/edit?usp=sharing)

**Resources**
[Adswerve plugin](https://docs.google.com/presentation/d/1VqFTJso8IkatklBSvbW--dc9j51SNLh9nDedoEoTyDU/edit#slide=id.gf4da558656_0_14) - used to test analytics tracking for a given page

**Comment by christinec-fftc** [comment]
[Recording](https://drive.google.com/file/d/1hzEcsyec0zzDUAxsAsiKQgiCTtiEvFkC/view?usp=sharing) discussing this discovery ticket's findings
