### ISSUE TITLE
Reorganize and remove content within the Platform Orientation template

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#61857]
## User Story
As a VFS team member, I want to complete the steps for orientation in a logical and meaningful order so that I can understand 1 chunk of information at a time and not be overwhelmed. 

As a VFS team member, I don't want to click broken/dead links and be directed to out of date guidance so that I am not wasting my time and/or energy.

Assignee: @CherylEvans 
Peer Reviewer: @allison0034 @erinrwhite

## Description
The General, Norms and Standards and Working on the Platform checklist items that new VFS team members are asked to complete via the Platform Orientation template are not listed in any meaningful order. VFS teams would benefit from organizing the checklist items to align with the subject matter.

In addition, several links lead to deprecated Github pages. Any link that leads to a deprecated gh page should be completely removed from the template, including the checklist item itself.

Review feedback from [Platform Orientation research study in fall of 2022.](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2431942689/2022-11+Platform+Orientation+Discovery+Research)

## Impacted Artifacts
[Platform Orientation Template gh](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=analytics-insights%2C+analytics-request%2C+governance-team%2C+platform-orientation&template=orientation-epic.md&title=Platform+Orientation+Template+%5BYour+name+here%5D)

## Tasks
- [x] Test all the links in the General, Norms, and Standards, and Working on the Platform checklist sections of the ticket. If the link leads to a deprecated Github page, then delete the line from the checklist
- [x] Of the remaining items, group them based on tasks that require action (watching a video, updating Slack profile, etc.) vs. tasks that require reviewing
- [x] ~Rename section headings as appropriate~ (No section required renaming)

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS team members are asked to complete steps for orientation in a logical, meaningful order.

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
**Situational Awareness**
@allison0034 [Pull request](https://github.com/department-of-veterans-affairs/va.gov-team/pull/62357) created.
@erinrwhite and I collaborated to update the New VFS Team Member Template (proposed change from [ticket 61534](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/gh/department-of-veterans-affairs/va.gov-team/61534) - Platform Orientation Template). We deleted deprecated links and organized the content in a more logical format. We kept the headings the same as we felt no change was needed. However, if you review the PR and think changing the headings makes sense, please let me know. :-) 
This ticket is ready for peer review, but please wait until I finish the remaining tasks on ticket 61534 before conducting your peer review.
Thank you!!

**Comment by CherylEvans** [comment]
@allison0034 @erinrwhite This is ready for your peer review. :-)

**Comment by allison0034** [comment]
@CherylEvans I started the review on this with Erin and have a question: What is the reason behind grouping the "activity"?

**Comment by shiragoodman** [comment]
that's more of a me question. This is just a small, Phase a, change. We are going to make more changes to the template in #52400 but for now, this is a minor change we're making to make it simpler and easier for VFS teams to complete the template.

**Comment by allison0034** [comment]
@shiragoodman ok. I just want to make sure that if we order them that way it does not screw the order up in which they do things. For example, we want them to try to watch the design videos before they attend/watch orientation. The order looks ok for design. I do not know if there is any relevance to the other areas.

@CherylEvans this looks good to me. Can you make a note that you did not rename the sections for tracking?

**Comment by CherylEvans** [comment]
@erinrwhite @allison0034 @shiragoodman Thank you all for your input. I noted in Tasks that the section names will stay the same.
