### ISSUE TITLE
[FSR] SW - Move marital status and dependents pages

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#61862]
## Issue Description
We will need to move these pages to get the data we need for GMT. These page order changes can be applied to all versions of FSR and is not streamlined specific (for clarity). 

This change can be done in conjunction with **[FSR] SW - Add new chapter level depends and structures [#61842](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/61842)**

[Here's the original ticket that noted this change](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/53495)
[Mural with new page flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1678973946956/6f3bb65fe1ccc2b9d3bc38cd24cd09e74d18d778?sender=u7f58f2afe2ea053d4dea4234)

![image.png](https://images.zenhubusercontent.com/61f96bcb96295709970afb65/96c01ea7-ded1-4a01-83a7-2ed9ec7c253c)

---
## Tasks
- [ ] Move dependents page
- [ ] Move Spouse question & name pages
- [ ] Update e2e tests with new order

## Acceptance Criteria
- [ ] Spouse and dependent questions are ordered according to design
- [ ] All tests updated and passing
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
This is handled in #6184- ok to close, per @Dr-Pongo
