### ISSUE TITLE
CANCELED**Verification Support Video - finalize editing

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#61872]
### Finalize and publish IPP verification support videos

Follow-on ticket for work that we'll complete once we secure the blessing to post this video. We'll want to button up certain aspects of the video as well as finalize any specialized aspects that would be specifically for youtube

#### Tasks (to be added to)
- [ ]  Finalize Site wide content approval/ticket - [see slack discussion](https://dsva.slack.com/archives/CBU0KDSB1/p1689183173711569)
- [ ]  Re-edit Computer flow with the updated audio from Amber
- [ ]  Consider pacing on each video
   - [ ]  If need to change, consider and/or look into does it require rerecording audio or does changing space between sentences work or is there a way to change the speed of the audio?
   - [ ]  complete that change
- [ ]  On Error video decide if the section GRX or if the voice over should change so they match
   - [ ]  make that change
- [ ] Add chapter markers for youtube link points on each of the 3 videos
- [ ] video description for each of the 3 videos
- [ ] Link video to VA.gov where it makes sense

#### Acceptance Criteria
- [ ] Reviewed by UX Team
- [ ] Reviewed by PMs
- [ ] Documentation has been updated
- [ ] Put published research in drive

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
