### ISSUE TITLE
IA Tracker: IA Design for Form 21-0779: Verifying nursing home status

### ISSUE THREAD

**Issue by jennymayoco** [department-of-veterans-affairs/va.gov-team#61884]
## Overview
IA support needed for staging review for Form 21-0779. This form is used to verify the status of a nursing home or care facility where a Veteran or surviving spouse is a patient.

### Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

### Links

- [Intake Ticket #61548](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61548)

### Team

- Team Name: Veteran facing forms
- Designer: Jeana Clark
- Product Manager: Tricia Baker
- Slack (_optional_): 

### Timeline
_When does IA review need to be completed by? When is Midpoint Review?_

---

### Work Needed (if applicable)

- IA Spec: **Needed**
- Feedback for product team: **Needed**

### Tasks
Check all that apply.

- [X] Create process ticket draft
- [ ] Watch Design Intent
- [x] Determine IA deliverables
- [x] Collaborate with CAIA
- [x] Ask questions to product team
- [ ] Create IA Spec
- [ ] Mikki reviews IA Spec
- [ ] Share IA Spec with product team
- [ ] Update Site Map and VA.gov Mega IA sheet

## Acceptance Criteria
- [ ] Feedback is shared with product team in Intake Ticket.

**Comment by kristinoletmuskat** [comment]
Update: waiting for the H1 from Megan and Danielle.

**Comment by jennymayoco** [comment]
As per sync with forms team today, this form has dropped in priority. Shifting focus to 10206 form

**Comment by jennymayoco** [comment]
[Draft IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/form-digitization-21-0779.md)

**Comment by jennymayoco** [comment]
Waiting on h1

**Comment by coforma-terry** [comment]
@Jenny, any updates on this ?

**Comment by jennymayoco** [comment]
@coforma-terry checking in with team during this week's content office hours to see where this form is at!

**Comment by jennymayoco** [comment]
Update from team: form has been dropped in priority so leaving this ticket in blocked until we get the okay to continue work on this form

**Comment by kristinoletmuskat** [comment]
Update: paused indefinitely. Team isn't currently working on it.
