### ISSUE TITLE
Update help footer changes on the site

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#61896]
## Issue Description
With input from the Service Design team and our own team, the general Help and Feedback footer on the Platform website has been redesigned to:

- include new service to Submit New Content for the Platform Website
- update the language on the other existing CTAs

It is now time to make the update on the website. We must be careful not to break any links and smoke test the changes shortly after the change has been implemented.

---
## Tasks
- [x] Using the new prototyped language, [update the template page](https://vfs.atlassian.net/wiki/spaces/SUP/pages/1807909029/Page+footer) that creates the Help and Feedback footer for all pages on the Platform website
- [x] Wait for the change to deploy
- [x] After the deploy is reflecting the changes, immediately test the footer links on random pages across the site, to ensure all links are properly working

## Acceptance Criteria
- [x] The Platform website will have an updated Help and Feedback footer on all pages that will include one new CTA and updated language to the existing 3 CTAs
