### ISSUE TITLE
Implement API for BGS vnpProcCreate

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#6189]
## Story
As a Veteran, I need to be able to update my dependents so I can ensure that they are getting the correct benefits.  One of the first BGS steps in submitting the 686 is the BGS `vnpProcCreate` service.

## Goal
- Build an API that communicates with BGS and calls the `vnpProcCreate` service.  This generates a vnpProcID that is needed for the subsequent steps in the 686 submission process. 
- Migrate this functionality from eBenefits to VA.gov so users will no longer have to login to eBenefits to update their dependents.

## Tasks
- [x] Download appropriate WSDL file and test sending a request and receiving a successful response (via SoapUI or Postman) 
- [x] Build and configure a dependents service within `vets-api` that calls the `vnpProcCreate` service from BGS
- [x] Implement the controller, route, and serializer for the dependents service

## Considerations
- This assumes connectivity/access is granted for this particular service
- Determine what values should be passed for static fields (some values previously being passed referencing eBenefits, etc)
- This will be our first time implementing a POST action within `vets-api`, there could be unknown factors to take into consideration

## Acceptance Criteria
- [x] Successfully send a request to the BGS `vnpProcCreate` endpoint and receive a generated `vnpProcID` as part of the response
