### ISSUE TITLE
Propose Auth Solution to AWG

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#61901]
# Description
Research was conducted on evaluating potential approaches to Authentication/Authorization for Preview Environments. A recommendation was made by Joe N of the Identity Team, which we will be proposing to the Architecture Working Group

# Tasks
- [ ] Review findings from the [Research Ticket](https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/61208)
- [ ] Get on the schedule for the AWG meeting
- [ ] Create presentation/documentation in preparation for the AWG
- [ ] Present issue in the AWG
- [ ] Collect & Document feedback

# Acceptance Criteria
- [ ] AWG presentation has been completed
- [ ] Comments/feedback have been documented
- [ ] A path forward has been identified

**Comment by JoeTice** [comment]
This is OBE and no longer seems necessary, will reopen if needed.
