### ISSUE TITLE
Identity Dashboard (FE) - Security Bug - word-wrap

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#61916]
## Description
See how we can fix this medium priority vulnerability with `word-wrap`
https://github.com/department-of-veterans-affairs/identity-dashboard-fe/security/dependabot/2

## Tasks
- [x] Investigate if we can use `resolutions` in `package.json` to use a secure version of `word-wrap`
- [x] Verify if this vulnerability only exists in `yarn.lock` and not in `pnpm-lock.yaml`
- [x] Verify if this vulnerability affects our Docker image

**Comment by aparsley** [comment]
Keep up the good work!
