### ISSUE TITLE
BE - Profile - Name Tag Disability Rating - Add Mock Data for Staging Users

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#61912]
## Background
Lighthouse staging environment is not available for disability ratings.  Mock data will need to be added for the following staging users.

| First Name  | Last Name | DOB        | Address       | Email                       | ICN               | Rated Disability |
| ------------| --------- | ---------- | ------------- | --------------------------- | ----------------- | ---------------- |
| Greg        | Anderson  | 1933-04-05 |  140 Whitehaven Cir Highlands Ranch, CO 80129   | [vets.gov.user+1@gmail.com](mailto:vets.gov.user+1@gmail.com)     | 1012666182V203559  | 50   | 
| Eric        | Bishop    | 1963-07-05 |  234 Test Street Albuquerque, NM 87109  | [vets.gov.user+11@gmail.com](mailto:vets.gov.user+11@gmail.com)   | 1012829228V424035  | Null |
| Oscar       | Jones     | 1948-10-16 | 811 Vermont Ave NW Washington, DC 20420  | [vets.gov.user+80@gmail.com](mailto:vets.gov.user+80@gmail.com)   | 1012666047V544942  | 65   |
| Travis      | Jones     | 1950-09-06 | 4800 Cox Rd Chicago, IL 60647 | [vets.gov.user+81@gmail.com](mailto:vets.gov.user+81@gmail.com)   | 1012845638V677813  | 60   |
| Christopher | Lane      | 1951-07-10 |  None  | [vets.gov.user+82@gmail.com](mailto:vets.gov.user+82@gmail.com)   | 1012829621V733243  | 60   |
| Timothy     | Soto      | 1946-07-15 |  843216 Vermont Ave NW Washington, 4324 United Kingdom  | [vets.gov.user+201@gmail.com](mailto:vets.gov.user+201@gmail.com) | 1012833438V267437 | 70   |
| Johnnie     | Weaver    | 1956-07-10 |  171 Harvest Moon Dr Bolton, Ontario, L7E 2X5 Canada  | [vets.gov.user+226@gmail.com](mailto:vets.gov.user+226@gmail.com) | 1012740600V714187 | 70   |

## Tasks
- [x] Identify list of users
- [x] Create a list (spreadsheet) with user ICNs and disability rating for each user
- [x] Submit request to LH team to have mock data added for users
- [ ] Configure vets-api staging env to point to LH sandbox env

## Acceptance Criteria
- [ ] LH team confirm that mock data is added for users.
- [ ] Test users in staging environment (Profile or My VA pages)

**Comment by tpharrison** [comment]
@mtcA6 I added a list of staging users above.

**Comment by tpharrison** [comment]
Verified rating disability for the users listed;  all have correct mock data except vets.gov.user+82@gmail.com.
