### ISSUE TITLE
Configure container to use cached content-build

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#61958]
# Description
In order to have the FE container use the content-build, we need to refactor the start script to expect that the content-build will be in place a specific path on the EFS volume.

# Tasks
- [x] Remove steps from the start script that clone and build content-build
- [x] Add steps to the start script that navigate to the cached content-build and serve it.

# Acceptance Criteria
- [x] A FE container deployed by ArgoCD into vagov-dev EKS is hosting an instance of va.gov that is communicating with the BE container also in EKS

**Comment by pjhill** [comment]
We can expect the FE files to be available on the EFS volume at this path -- 
```
/app/website/slow/pe_slow_content_build-1689786553/website/
```

**Comment by pjhill** [comment]
Change the start script to navigate to the expected path, watch vets-website, and serve content-build.

**Comment by pjhill** [comment]
Add a sleep command to the start script to hold the container open just in case it fails. This let's us do some troubleshooting about what went wrong.

**Comment by pjhill** [comment]
The start script works to deploy a pre-staged VW and CB.
