### ISSUE TITLE
Generate content-build with API_URL configured

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#61956]
# Description
In order for the content-build to be usable in a PE, it needs to be configured to route requests to an API endpoint URL that we operate in the BE pod.

# Tasks
- [x] Research how we should ship the build to EFS
- [x] Communicate findings and make recommendations
- [x] Do the build with API_URL configured

# Acceptance Criteria
- [ ] Configured content build is available to push to EFS

**Comment by CBonade** [comment]
https://vfs.atlassian.net/wiki/spaces/TT4/pages/2708733956/Moving+build+files+to+EFS confluence document here with documentation and recommendation.

**Comment by pjhill** [comment]
Thanks for writing up those options and generating the build. Now we just need to get it there...
