### ISSUE TITLE
Move content-build into place on EFS

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#61957]
# Description
In order to get the build into EFS for use by the container, we need to figure out a method for manually mounting and copying files into EFS from either our local environment or manually form S3 to EFS.

# Tasks
- [x] Research how to access EFS volume from a local environment
- [x] Copy the build into place on the EFS volume

# Acceptance Criteria
- [x] Configured content-build is available for use in EFS

**Comment by pjhill** [comment]
Helpful commands for manually moving the content-build from your box onto the EFS volume via the EC2 jumpbox --
```
sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 fs-03034113a15d8083a.efs.us-gov-west-1.amazonaws.com:/ /home/ec2-user/efs-mount-point

sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 10.247.96.113:/ /home/ec2-user/efs-mount-point

sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 10.247.96.113:/ /home/ec2-user/efs-mount-point

/app/website/slow/pe_slow_content_build-1689786553/website/content-build

yarn build --use-cached-assets --host="http://vets-website-rework-pe-fronten-dev-platform.vfs.va.gov" --port=80 --api="http://vets-website-rework-pe-fronten-dev-platform-api.vfs.va.gov"

/root/efs/pvc-84434ec1-ed4b-40c3-ba97-796e2dcdf8ad/pe_slow_content_build-1689786553/website

ssh -i "preview-environment.pem" ec2-user@ec2-160-1-129-184.us-gov-west-1.compute.amazonaws.com

sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 10.247.96.113:/ /home/ec2-user/efs-mount-point

tar -zcvf content-build.tar.gz content-build

scp -i preview-environment.pem /app/website/slow/pe_slow_content_build-1689786553/website/content-build.tar.gz ec2-user@ec2-160-1-129-184.us-gov-west-1.compute.amazonaws.com:/home/ec2-user/efs-mount-point/pvc-e1152b04-5303-4190-af20-f83854d530db/pe_slow_content_build-1689786553/website

no hup tar -xvf content-build.tar.gz > content-build.out &
```

**Comment by pjhill** [comment]
We have been able to upload builds to the EC2 jumpbox and move them into place on the EFS volume.

**Comment by pjhill** [comment]
At least one weird configuration bug that we discovered that we have to deal with -- 
1. the URL for some links is showing localhost

**Comment by pjhill** [comment]
FE containers are starting successfully now, and the links appear to be correct.
http://vets-website-rework-pe-fronten-dev-platform.vfs.va.gov/

**Comment by pjhill** [comment]
The manual process to load a configured `content-build` into place on the EFS volume has worked.
