### ISSUE TITLE
Prep for Memorials team

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#61968]
### Team to check with:
Memorials Self-Service Team. PM is Cat Hughes [#54528](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54528)

Per Catherine: "we are revamping a previously digitized form to improve user experience, accuracy of the form, and to integrate it with a new system in the near future."

Things to learn:
What was their experience?
What worked?
What didn't work well?
What were big pain points

Info from Memorials team:
"Name: Pre-Need Determination of Eligibility for Burial in a VA National Cemetery
Number: VA Form 40-10007
[Link](https://www.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/introduction)

## Tasks
- [x] Reach out to schedule workshop
- [x] Draft [interview guide](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2716631041/5th+Workshop+Memorials+Team+Conversation+Guide+-+Forms+Digitization+Research)
- [x] Prep [Mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1690310428717/aea984197a32b3a7712548a411bbcfa6c12dca53?sender=u9ea6bd3ca12795949b606150)
- [x] Share Mural

## Acceptance Criteria
- [x] Meeting is scheduled (7/31 @ 2pm ET)
- [x] guide is ready
- [x] Mural is ready
- [x] Mural is shared
