### ISSUE TITLE
Investigate alternate architectures for onsite notifications

### ISSUE THREAD

**Issue by A6-toma** [department-of-veterans-affairs/va.gov-team#61962]
From Patrick:
I'm not convinced that relying on VA Notify for web-based notifications is the best architecture. I’d like Carlos to review existing architecture, look at some of our use cases (like copayment debt notification or the appointment related ones), and determine if there is an alternative architecture.

### Tasks
- [ ] Review VA Notify notification architecture
- [ ] Explore alternate architectures
- [ ] Make a recommendation on preferred architecture to use

### Acceptance Criteria
Architecture recommendation is documented and presented to the team.
