### ISSUE TITLE
EPIC | Profile | Race/Ethnicity Self-Identification (2025?)

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#61986]
## Current Status 

`PAUSED`
- [see slack thread ](https://dsva.slack.com/archives/C909ZG2BB/p1689953063945229)
- [Agile Six Technologies Mail - RE_ Discussion around DMND0007102 has changed to state Deferred.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/15404715/Agile.Six.Technologies.Mail.-.RE_.Discussion.around.DMND0007102.has.changed.to.state.Deferred.pdf)

May pick up in 2024 but paused for now, VA Profile needs to connect to CXI (formerly CDW) and the design system needs to connect their component to Collibra to ensure they're collecting the latest standards 

### Request from VHA

New item surfaced 7/13/2023 as part of the biweekly standing meeting with VA Profile 

Veterans as part of a standard process w/the 1010EZ provide their race and ethnicity. This isn't uniformly captured and the goal is to have this initial idea is to have this as a manageable field in the profile. 

<details><summary>Initial details shared by the VA Profile Team </summary>
<p>

**Who submitted this request?** The VHA Office of Health Equity (OHE)

**What is the business need?**

- An IT solution that grants Veterans the ability to self-identify their race/ethnicity on VA.gov.  
     - This capability will allow Veterans to manage, enter, and edit their race/ethnicity through VA.gov.
     - This capability will also improve the validity of demographic data and improve the accuracy of health equity determinations based on demographics, further improving the level of service provided to Veterans.
- This request is currently listed as unfunded.   The business is requesting a cost estimate.

**Current Business State**:   Veteran’s race/ethnicity information is collected after the completion of the 10-10EZ, but due to inconsistencies in the way that document is completed, the data’s validity can vary.

 
**Current Request Status:**   
VHA completed requirements and submitted a Demand through BIOS to request SPM Health Intake Team to support Technical Assessment with Cost Estimation.
SPM Health Intake Team received guidance to transition this request to VA Profile Product Line with VA.gov Product Line collaboration.
 
 **Current Request Funding Status:**   Not funded.

</p>
</details> 

<details><summary>Notes from first call w/ VHA folks on 7/14/2023</summary>
<p>

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/6ca07a18-fa86-4801-bb0c-c3e9d14c8ebc)

Goal is for Veterans to enter Race and Ethnicity and data to be linked to Corporate Data Warehouse 

Undersecretary for Health Dr. Shereef Elnahal has 6 priorities, support veterans whole health, ... missed the list > the office of the health equity has two key actions, one of those has a few milestones > one of those milestones is getting users to be able to go through VA.gov to update the information 

This initiative mirrors the work done for gender identity worked on last year. 

**Current process:**
Veterans provide the information through 1010EZ form < this is keyed in by a VA staff member 
Gold standard is for self-entered / self-identified data to avoid errors 

**Outcome Goals** 
would help close healthcare disparities as the VA would be better able to identify. 
Users would be: Veterans, Healthcare researchers, Facilities, policy makers 

**Systems Mentioned**
Vista & CPRS > veterans are not able to see how they've been classified in the system 
Corporate Data Warehouse > OIT Bizzel (???)
Master Veterans Index 

Their current standards for asking the questions ar based on the [**OMB standards.** ](https://orwh.od.nih.gov/toolkit/other-relevant-federal-policies/OMB-standards)

</p>
</details> 

<details><summary>IA Work We Should Consider</summary>
<p>

When we pick up this work we should explore adding a demographics page, we should move things out of personal information and into it's own demographics page, this will impact the hub and might start to make things a bit messy. Given this, we should consider all of the IA implications of the expanding structure of the profile and explore how, between the auth menu and the hub we can respond to the expanding demands on the profile to help veterans find what they need. 

</p>
</details> 

### Governance Standard - Collibra - EDII

<details><summary>EDII Meeting 1/31/2024</summary>

- [EDII Roadmap](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1696008505966/1cbfce0182df346a0b383ea424a019e0bc8496f1?sender=uaa72d11015d3f7c704a64191) 
- [PM Checkins](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1706632469050/315864c1d55e836bf90a133517d6d770cedf95bf?sender=uaa72d11015d3f7c704a64191)

</details> 

<details><summary>edii call 5/14/2024</summary>

- [mural shared during this call](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1715631077942/83d60359b965a05778b9f94a9853b839e49138bc?fromVisitorModal=true&sender=uaa72d11015d3f7c704a64191)
- need to determine requirements in collibra > certain aspects for user forms and interfaces 
- There is a KEY DISTINCTION - we can't mix Customer Experience data with PHI data. So if the R/E info is collected for healthcare it becomes PHI, if it's collected for Customer Experience it is not. So there's a process flow we have to understand and ensure we've captured appropriately. 
- va directive 0900 - collibra - edc portal is where theyre going to define the approved R/E 'questions'/'selections' 
     - John Williams in VEO is responsible for approving
- Jackreece, Timothy T. (b 3 Group, Inc.) is the data engineer for EDC team 
- transcript [USE THIS INVITE va.gov Requirements for RE Collection Standard API_2024-05-14.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/15309618/USE.THIS.INVITE.va.gov.Requirements.for.RE.Collection.Standard.API_2024-05-14.docx)

</details> 

<details open><summary>5/22/2024 call </summary>

### Next steps
- [ ] Matt Dingee's team needs to proceed first with figuring out the Collibra Standards and integrating those in w/the design form 
- [ ] VA Profile- we need to follow up on our next VA Profile call - CDW/CXI are they integrated yet (this blocks the VHA request we have from Kenneth Jones)
- [x] Chante to check in w VEO about the implementation plan for collecting demographic data (was due end of September 2023)

</details> 

### VA Profile 
- [Swagger docs ](https://dvagov.sharepoint.com/sites/OITEPMOVAPROPUB/SitePages/VA-Profile-SwaggerUI-Links.aspx?csf=1&web=1&e=lBdP8h) and [corresponding slack thread about this](https://dsva.slack.com/archives/C909ZG2BB/p1689352705882439)
- [VADIR Master Schema - DoD Ethnicity Table - Dept of Veterans Affairs-External - Confluence](https://confluence.devops.va.gov/pages/viewpage.action?spaceKey=VAExternal&title=VADIR+Master+Schema+-+DoD+Ethnicity+Table)
- [VADIR Master Schema - DoD Race Table - Dept of Veterans Affairs-External - Confluence](https://confluence.devops.va.gov/display/VAExternal/VADIR+Master+Schema+-+DoD+Race+Table)

### Corporate Data Warehouse (CDW)
Data needs to connect to the same systems used for the gender identity data VA.gov/VA Profile already use

## Important Artifacts 
- [demographics research](https://github.com/department-of-veterans-affairs/va.gov-research-repository/tree/master/research-proposals/MCT%20Omnichannel%20Experience/2022-07%20Demographics%20Interviews)
- [OMB Standards](https://orwh.od.nih.gov/toolkit/other-relevant-federal-policies/OMB-standards)

## Tasks

**Comment by Samara-Strauss** [comment]
Next steps:

- Determine what options there are for race and ethnicity, and determine if this meets the needs of the requesting team.
- Determine which backend systems VA Profile connects with for race and ethnicity. I will email VA Profile about this.
- Determine if we need funding for this. I'll ask in an OCTO channel about this.

**Comment by mtcA6** [comment]
Closing for now, will reopen if needed
