### ISSUE TITLE
Present proposal for Veteran's board

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#61988]
## Acceptance criteria
- [x] Share back feedback from sessions

## Tasks
- [x] Share with Kevin Hoffman and learn about potential modifications to be made for Perigean contract (7/14)
- [x] Share with Platform in Research Office Hours (7/14)
