### ISSUE TITLE
Explore moving the VFS Team Roster to GitHub projects

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#61984]
## User Story
_"As a (persona), I (want to), (so that)."_

Assignee:
Peer Reviewer:

## Description
The current VFS Team Roster is a Google Sheet that lives on Oddball's Google Drive. It is not very visible to Platform and VFS teams. By moving the VFS Team Roster to Github projects, there are many steps in the Platform Orientation (the process that populates the VFS Team Roster with new team members) that may be able to be automated, saving time for Platform Team members. 

### Opportunities
standardizing roles across VA.gov
validation of data from the VFS team member
automating steps in the current Platform Orientation process

## Tasks
- [ ] _Placeholder task_

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have defined what our requirements are for the VFS Team Roster

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
closing this ticket as Platform Product team will be introducing a new solution for the VFS Team Roster that is NOT Github projects
