### ISSUE TITLE
Sprint 16 Objectives (Feb26 - Mar10)

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#6199]
# Order of priorities
1. Get address validation launched!
2. Profile 2.0: Copy for profile screens
3. Finish Direct Deposit work (copy+FE work)
4. Profile 2.0: Plan research
5. Profile 2.0: Continue/finish refactoring work
6. Profile 2.0: Start build
7. Monitoring, maintenance, bug fixes, hardening, 508, etc.

# Address validation
- [x] [SCREENREADER, FOCUS MANAGEMENT] While on "Please confirm your address" screen, the content from "Edit mailing address" is read by screen reader #5865
- [x]  [SCREENREADER, KEYBOARD]: Edit address link will not receive keyboard focus #5866
- [x]  E2E tests, running in CI/CD #5005
- [x] Revisit release plan #5085 
- [x] Get/implement production key (note: this is already on its way but not sure what work Lihan has to do once he gets it) #6207
- [x] "Learn and Improve" plan written: KPI measurements, analytics reporting, next phase of features to build #6212
- [ ] Analytics work (not our team) #5895
- [ ] Any analytics-related FE work #6213
- [x] Address Validation: bad handling of 400s from address_validation endpoint #6203

# Profile 2.0

## Design
Submit for update to copy for Profile 2.0 reference Epic #6238
- [x] Profile 2.0 Screen Copy - Military Info #6244
- [x] Profile 2.0 Screen Copy - Direct Deposit - #6245
- [ ] Profile 2.0 Screen Copy - Account Security - #6246
- [x] Profile 2.0 Screen Copy - Personal and Contact Information - #6247
- [x] Create research plan #2585
- [ ] Create conversation guide #2586

## Dev
- [ ] Release new profile forms to production and remove old legacy code #5817 (Erik Refactoring)
- [x] Profile 2.0: Investigate saving contact information #5815
- [x] Use feature flag for SchemaForm-based profile edit modals #6467 (added 5/9/20)

# Bug fixes, Hardening, 508/Accessibility, QA
- [x] [BE] Lihan - Investigate MHV 400 errors #5893
- [ ] [FE] Erik - BUG: non-2FA Direct Deposit users should see "set up 2FA" message #6187
- [x] [FE] - Brad -[SCREENREADER, FOCUS MANAGEMENT] While on "Please confirm your address" screen, the content from "Edit mailing address" is read by screen reader #5865

**Comment by Samara-Strauss** [comment]
@mshea0606 can you please close this out?

**Comment by mshea0606** [comment]
@Samara-Strauss  closed
