### ISSUE TITLE
Change "Call Centers" to "Contact Centers" in GitHub Repo

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#6200]
## User Story or Problem Statement

How might we maintain accuracy and consistency for contact center documentation?

## Goal

Change "Call Centers" to "Contact Centers" on all GitHub documentation.

## Tasks
- [x] Bill to run report identifying all instances of `call center` or `call centers` in `va.gov-team` and `va.gov-team-sensitive`

## Acceptance Criteria
- [x] Identify GitHub Markdown files
- [ ] Identify GitHub Labels
---

**Comment by billfienberg** [comment]
Here is a text file of the instances from `va.gov-team` and `va.gov-team-sensitive` that match `call-center` or `call center`. This should include where it's used in file/folder names, as well as content in files. 

I hope to update the format of the report so it's a little easier to digest. But I at least wanted to give you the raw data as soon as possible. 

[https://app.zenhub.com/files/133843125/c3ea6f06-c795-41ef-be9a-f76787459cb1/download](https://app.zenhub.com/files/133843125/c3ea6f06-c795-41ef-be9a-f76787459cb1/download)

**Comment by Kimberley2019** [comment]
Thank you for the report @billfienberg.  
Are you able to advise how I can change all of the 'call center' items to 'contact center' in the file path naming conventions?

For example:  va.gov-team/platform/**_call-center_**/request-contact-center-review.md

**Comment by Kimberley2019** [comment]
This task has been completed.  
There are some items that have remained as 'call center' due to the fact that it was meeting notes, the actual name of the call center (i.e National Call Center), or dictation taken verbatim.  

@billfienberg are you able to run another report showing the updated 'call center' items now in the repo?

**Comment by meganhkelley** [comment]
Hi @Kimberley2019 ! Sorry for not getting back to you a couple days ago — were you able to figure out how to change the folder names (that is what dictates the file path names)?

**Comment by Kimberley2019** [comment]
Hi @meganhkelley .  No worries.  I was not able to figure out how to update the actual file names, only the actual content within the file.

**Comment by meganhkelley** [comment]
@Kimberley2019 here are instructions for how to rename files: https://help.github.com/en/github/managing-files-in-a-repository/renaming-a-file

Renaming folders (which dictate the file path names) is a bit trickier and I can help with that today or in Sprint 22 (I am OOO next week) if you can please provide a list of folders named `call-centers` (I imagine there are only a couple?)

**Comment by Kimberley2019** [comment]
@billfienberg are you able to run another report showing the updated 'call center' items now in the repo?  If so, can you please advise on when you may be able to do that so I can be on the lookout?

It was a pretty hefty report and I want to ensure that all proper changes have been made.

**Comment by Kimberley2019** [comment]
@meganhkelley Thank you for providing the instructions, however, after reviewing, it does not allow me to change the areas that need to be updated.  

Below are the path locations that need to be updated to Contact Centers from Call Centers.

- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/call-center

- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/rated-disabilities/call-center

- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/call-center

- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/vets-application/product/measurement/recap-of-hca-call-center-meeting.md

- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-rated-disabilities/call-center

-

**Comment by billfienberg** [comment]
@Kimberley2019, here is a PR to update folder names from `call-center` to `contact-center`:
https://github.com/department-of-veterans-affairs/va.gov-team/pull/6929

**Comment by billfienberg** [comment]
I attached the file in [Slack](https://dsva.slack.com/archives/CL181NRJQ/p1584476961100700?thread_ts=1584454764.094100&cid=CL181NRJQ), but I'll post it here, too. After merging the PR to update the folder names from `call-center` to `contact-center`, here are the links that are still using `call-center`. 

___

[platform/README.md](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/README.md)

- 19,103: - [Contact Center](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/call-center)

[platform/contact-center/README.md](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/contact-center/README.md)

- 8,118: - [Contact Center Review Process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/call-center/request-contact-center-review.md)

- 10,120: - [VFS App Bugs Escalation Process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/call-center/tier-3-escalation-process.md)

- 14,148: - [VFS Monthly Contact Center Report](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/insights-analytics/call-center/call-center-data)

- 14,160: - [VFS Monthly Contact Center Report](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/insights-analytics/call-center/call-center-data)

[platform/engineering/frontend/readme.md](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/engineering/frontend/readme.md)

- 9,118: - [Request Contact Center Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/call-center/request-contact-center-review.md)

[platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md)

- 279,165: **VFS Product Manager** follows instructions on the [Contact Center Review page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/call-center/request-contact-center-review.md) to request a Contact Center review.

- 282,133: You bring (refer to [Contact Center Review page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/call-center/request-contact-center-review.md) for further instruction):

[products/claim-appeal-status/appeals-status/product-launch-checklist.md](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/claim-appeal-status/appeals-status/product-launch-checklist.md)

- 21,175: - More notes on [appeals status contact center](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/appeals-status/scripts-call-center.pdf).

- 26,171: - [Appeal Status Guide for Contact Centers](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/appeals-status/scripts-call-center.pdf)

[products/claim-appeal-status/appeals-status/readme.md](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/claim-appeal-status/appeals-status/readme.md)

- 75,153: - [Contact Center guides](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/appeals-status/scripts-call-center.pdf)

- 76,159: - [Contact Center discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/appeals-status/scripts-call-center.pdf)

[products/disability/rated-disabilities/README.md](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/rated-disabilities/README.md)

- 13,88: - Demo video link: https://dsva.slack.com/files/ULW9ZB61X/FRTSAK422/rated-disabilities-call-center-walkthrough.mp4

[products/disability/rated-disabilities/contact-center/README.md](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/rated-disabilities/contact-center/README.md)

- 4,151: - [What is it?](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-rated-disabilities/call-center/product-guide.md#what-is-it)

- 5,151: - [User Access](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-rated-disabilities/call-center/product-guide.md#user-access)

- 6,162: - [Who can access this?](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-rated-disabilities/call-center/product-guide.md#who-can-access-this)

- 7,168: - [How can users access this?](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-rated-disabilities/call-center/product-guide.md#how-can-users-access-this)

- 8,150: - [Navigation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-rated-disabilities/call-center/product-guide.md#navigation)

- 9,144: - [FAQs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-rated-disabilities/call-center/product-guide.md#faqs)

- 10,153: - [Functionality](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-rated-disabilities/call-center/product-guide.md#functionality)

- 11,170: - [Error Handling & Notifications](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-rated-disabilities/call-center/product-guide.md#error-handling-and-notifications)

- 21,143: ![Your-VA-disability rating](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/rated-disabilities/call-center/images/RD-1_clean.png)

- 25,130: ![RD 400 error](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/rated-disabilities/call-center/images/RD-2_clean.png)

- 29,130: ![RD 500 error](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/rated-disabilities/call-center/images/RD-3_clean.png)

- 43,148: ![RD  authenticated landing page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/rated-disabilities/call-center/images/RD_Landing_1A.png)

- 45,150: ![RD  unauthenticated landing page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/rated-disabilities/call-center/images/RD-4_clean.png)

[products/health-care/appointments/va-online-scheduling/product/Product Dev Checklist - VAOS MVP.md](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/product/Product Dev Checklist - VAOS MVP.md)

- 59,161: - [ ][contact centers know how to help users who call in about the feature](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/call-center/request-contact-center-review.md)

[products/platform/documentation-site/research/research-round-2/research-plan.md](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/platform/documentation-site/research/research-round-2/research-plan.md)

- 49,113: - [Contact Center](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/call-center/README.md)

[teams/vsa/teams/ebenefits/features/view-rated-disabilities/contact-center/product-guide.md](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-rated-disabilities/contact-center/product-guide.md)

- 4,151: - [What is it?](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-rated-disabilities/call-center/product-guide.md#what-is-it)

- 5,151: - [User Access](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-rated-disabilities/call-center/product-guide.md#user-access)

- 6,162: - [Who can access this?](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-rated-disabilities/call-center/product-guide.md#who-can-access-this)

- 7,168: - [How can users access this?](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-rated-disabilities/call-center/product-guide.md#how-can-users-access-this)

- 8,150: - [Navigation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-rated-disabilities/call-center/product-guide.md#navigation)

- 9,144: - [FAQs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-rated-disabilities/call-center/product-guide.md#faqs)

- 10,153: - [Functionality](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-rated-disabilities/call-center/product-guide.md#functionality)

- 11,170: - [Error Handling & Notifications](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-rated-disabilities/call-center/product-guide.md#error-handling-and-notifications)

- 21,143: ![Your-VA-disability rating](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/rated-disabilities/call-center/images/RD-1_clean.png)

- 25,130: ![RD 400 error](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/rated-disabilities/call-center/images/RD-2_clean.png)

- 29,130: ![RD 500 error](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/rated-disabilities/call-center/images/RD-3_clean.png)

- 43,148: ![RD  authenticated landing page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/rated-disabilities/call-center/images/RD_Landing_1A.png)

- 45,150: ![RD  unauthenticated landing page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/rated-disabilities/call-center/images/RD-4_clean.png)

[teams/vsp/teams/insights-analytics/contact-center/README.md](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/insights-analytics/contact-center/README.md)

- 3,162: Responsiblities for the Contact Center Lead can be found [HERE](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/triage/call-center/call-center-lead-responsibilities.md)

- 3,174: Responsiblities for the Contact Center Lead can be found [HERE](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/triage/call-center/call-center-lead-responsibilities.md)

[teams/vsp/teams/insights-analytics/contact-center/upload-demo-video-process.md](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/insights-analytics/contact-center/upload-demo-video-process.md)

- 7,248: ideos to the official VA.gov Youtube channel, review the [VA Office of Public Affairs Youtube Requirements document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/call-center/VA%20Office%20of%20Public%20Affairs%20YouTube%20Requirements.docx).

**Comment by Kimberley2019** [comment]
@billfienberg I did send you a slack message moments ago, but wanted to paste here as well.  Some of the links that I have reviewed appear to have broken links.

**Comment by billfienberg** [comment]
PR to fix broken links: https://github.com/department-of-veterans-affairs/va.gov-team/pull/6956

**Comment by Kimberley2019** [comment]
Final changes were made on 3/25/2020.

Megan Kelley  21 minutes ago
hey Kimberley, you will only have the option to "approve" if you're a reviewer on the PR — so, there's no problem with your access here

Megan Kelley  21 minutes ago
we can just ask bill to merge in these changes when he's online if the changes look good to you

Bill Fienberg  12 minutes ago
The PRs been merged, and I have no objection to the ticket being closed.
