### ISSUE TITLE
Mobile design within Collaboration Cycle internal study

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#62003]
## User Story
As a Governance team member, I want to better understand how VFS teams are creating and utilizing mobile designs in their design process, so that I can determine whether my team should introduce practices that better support the mobile-first mentality. 

Assignee: @allison0034 
Peer Reviewer: @briandeconinck @erinrwhite

## Description
At the 7/7 Governance team retro, the following comment was shared:

> Teams not prioritizing mobile lately, which has been surprising. Is there anything we can do to nudge them in the right direction to consider that early in their process?

Similar to the [user flow internal study,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59001) the purpose of this ticket is to set up an internal study within Governance team to asses how many VFS teams are bringing mobile designs to the Design Intent touchpoint. After 10 sessions, we'll review our findings to determine if changes to Design Intent guidance is necessary in order to encourage more VFS teams to design for mobile first.

**7/21**: I decided to expand this to Midpoint review as well. So we will track this for 10 Design Intents and 10 Midpoint reviews.

**8/2**: After speaking with Shira we are going to pivot and instead measure how many teams provided mobile at a Design Intent or Midpoint review and how many issues were found at Staging vs not.

## Impacted Artifacts
- [Research plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2727182373/2023-08+Mobile+design+within+Collaboration+Cycle+internal+study+-+Research+Plan)
- [Survey](https://docs.google.com/forms/d/1IC5dl564tgtcvZwmIFWfyw9MPe7KX0W3Krp0smQiXeI/edit)
~~- [Research plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2712961025/2023-07+Mobile+design+within+Collaboration+Cycle+internal+study+-+Research+Plan)~~
~~- [Google doc](https://docs.google.com/document/d/16SHrzAPFaU1cdRZpd6d6roDyU2rLW-HamQyPzwNGuMg/edit)~~
~~- [Google survey for Design Intent](https://docs.google.com/forms/d/11w54z42gLPa2Xxb1GxwssbyrB3nIdWExYG1D5ATGwwE/edit)~~
~~- [Google survey for Midpoint](https://docs.google.com/forms/d/1WFMaNagwAEDq9z7_v-lkVTW7SiAbYvUD1CtHU7HWQG8/edit)~~

## Tasks
- [x] Aside from "Did the VFS team provide a mobile design?", determine what other questions we want to know the answers to wrt how VFS teams create and utilize mobile designs.
   - For example, Did the VFS team _only_ share a mobile design or did they provide both mobile and desktop? What else? Per Allison, do they have hi-fi or lo-fi wireframes? Would this make more sense to implement at Midpoint Review? Research on mobile designs?
- [x] Solicit any additional questions for inclusion in the survey from governance team members
- [x] Draft an informal research plan for understanding mobile designs with VFS teams
   - [x] Add research plan to [Governance/Research folder](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2297364885/Research)
- [x] Build a form using Google Forms with finalized list of questions

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have implemented an internal study for understanding how VFS teams are utilizing mobile designs in their design process

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
Google doc [Mobile design within Collaboration Cycle internal study#62003](https://docs.google.com/document/d/16SHrzAPFaU1cdRZpd6d6roDyU2rLW-HamQyPzwNGuMg/edit)

**Comment by allison0034** [comment]
Started [Research plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2712961025/2023-07+Mobile+design+within+Collaboration+Cycle+internal+study+-+Research+Plan)

**Comment by allison0034** [comment]
Started [Google survey](https://docs.google.com/forms/d/11w54z42gLPa2Xxb1GxwssbyrB3nIdWExYG1D5ATGwwE/edit)

**Comment by allison0034** [comment]
@shiragoodman just wanted to follow up on this. Per our [Slack convo](https://dsva.slack.com/archives/GNF5GSD9N/p1690295141199979) you were unsure about a couple of things.

1. Should we just look at past DI/MP to try to gather info? I say no. It will take some time to dig thru the repo and find all prototypes and see if they have any mobile or desktop screens. Also, we cannot tell wether or not they actually did the testing during a DI or MP timeframe from their research repo. We can look at dates and make an assumption but that is risky. Design and user testing life cycles vary per team/designer/researcher. Asking during their DI or MP would solve both these problems.
2. Why are we doing this research in the first place? If you review this ticket I think it can explain it but we basically want to gather some foundation on when/if teams are creating mobile designs. I think it is important to measure this against desktop design too.

I have created all the docs, I just need to update the moderator responsibilities but wanted to follow up with you since you had some concerns. Do you think we need to pivot this research?

**Comment by shiragoodman** [comment]
@allison0034 We have a 1:1 today for the VA.gov Exp Stds work, so let's use a few minutes during that meeting to talk about the mobile design study. 

In reviewing your research plan, it feels like something is missing. We're asking all these questions about mobile design to assess where teams are... so we can update our guidance around mobile design? While I agree the research will help us do that, the research plan doesn't address why mobile design is important. Why do we want to encourage it? What are we hoping that teams who prioritize mobile design are accomplishing compared to teams that don't? I think that's what is missing for me wrt your # 2 comment above.

**Comment by allison0034** [comment]
This will be moving into the next sprint and we will be pivoting slightly to get quicker, quantifiable data.

**Comment by allison0034** [comment]
After speaking with Shira we will be pivoting to measure if teams that did not provide mobile have more issues at staging vs not.

**Comment by allison0034** [comment]
Reached out via [Slack](https://dsva.slack.com/archives/GNF5GSD9N/p1691178076430809) for team feedback last week and created a new research plan.

**Comment by allison0034** [comment]
@briandeconinck @erinrwhite this is ready for your review. Artifacts are in the artifacts section. Could you please preview the survey? I created sections to try to keep human error from happening like in our last survey : )

**Comment by erinrwhite** [comment]
thank you @allison0034 reviewing now - the Google Form is saying I don't have permission. Can you share?

**Comment by briandeconinck** [comment]
@allison0034 I think this all looks good!
