### ISSUE TITLE
Decision Reviews | Warning alert for when parts of the application system is down

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#62006]
## Value Statement
**_As a_** Veteran encountering a server error while HLR, Supplemental Claims, and or Board Appeals loads contestable issues
**_I want to_** be notified that it is a server error
**_So that_** I have the choice between trying again later or adding my own issues

---
## Background Context
When we have a backend server error that prevents issues being pulled up In our Supplemental Claim, Notice of Disagreement, or Board Appeal forms, the contestable issues page shows that no issues were loaded. An error alert exists that tells Veterans 'Sorry, we couldn't find any eligible issues'. Further explanation only states that the issue may not have entered the system yet, when in reality, it is a backend server error that could be resolved at a later time.

## Acceptance Criteria
- [x] User can complete the form when issues are unavailable
- [ ] User is made aware when issues are unavailable
- [ ] User is made aware of why issues are unavailable so they can make a choice

## Designs and Build Notes
- [DESIGN](https://www.sketch.com/s/0424c51d-7818-43ea-8821-6de91eb7ab27/a/qbAvv22)

## Tasks
- [ ] Add either a warning alert that informs users ahead of time that parts of the application is not functioning properly
- [ ] Add extra context about the server error to the additional-info dropdown 'Why isn't my issue listed here?
- [ ] Update design files
- [ ] Update CSoT

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Design is approved by enablement team
- [ ] Design is ready for frontend

**Comment by eileen-coforma** [comment]
Added design for error message. Waiting for Julie to validate.

**Comment by jstrothman** [comment]
Comments/questions in Sketch

**Comment by eileen-coforma** [comment]
Updated design file with the following notes (also in Slack):

Since we have the issue summary page, I don’t think there will be an issue if somehow the issues load, and there was the same issue added as a new issue.
However, I do feel the If an issue is missing from the list, you can add it here. language is misleading, and suggest changing it to If you don't see the issue you want us to review, you can add a new issue.
I believe this shift will make it so that ‘adding a new issue’ is for the review, and not trying to supplement or fix something that’s ‘missing’.
I also adjusted the additional info to include adding a new issue with your decision date (a copy change we had done on Supplemental Claim)
