### ISSUE TITLE
Update education accordion in "How to change your legal name on file with VA" article

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#62013]
## Issue Description
Education Service asked us to add QuickSubmit and AVA as ways to submit this request. We'll encourage use of QS, then say something along the lines of "you can also send us your request through Ask VA."

---
## Tasks
- [x] Update education accordion.
- [x] Change header above the accordions since it's not just "addresses" with this update (and see if any other messaging updates are needed along these lines). 
- [x] Create a new ticket to ask the other business lines if they will also accept name change requests through either or both of these tools. (We should publish this EDU request though--don't hold it up while we ask other business lines.)

## Acceptance Criteria
- [x] Page has been updated.
- [x] New ticket has been created.
- [ ] Education Service has been notified that this update is complete and live.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by katherine-fung** [comment]
Hi @megzehn, 

Can you please copy edit and publish these updates on Monday, along with ticket #61267? 

I'll create a new ticket for contacting the other business lines.

**Comment by megzehn** [comment]
Thanks for making these changes, @katherine-fung! I reviewed and published them, along with ticket 61267,

**Comment by laurwill** [comment]
I validated that this is live — closing out. 

@katherine-fung did you notify stakeholders already?
