### ISSUE TITLE
NOD | Update design to match production

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#62016]
## Value Statement
**_As a_**  designer
**_I want to_** work off up-to-date design files
**_So that_** we can ensure the starting point for our recommendations is accurate

---
## Acceptance Criteria
- [x] Design files are reflecting what is currently in production

## Tasks
- [x] Add user flow
- [x] Update introduction
- [x] Update deadline and extension
- [x] Update contested issues
- [x] Updated board review options
- [x] Update submit additional evidence
- [x] Update review application
- [x] Update confirmation

## Definition of Ready 
- [ ] Clear value description
- [ ] Reviewable acceptance criteria

## Definition of Done
- [ ] AC are met

**Comment by eileen-coforma** [comment]
Can @Mottie or @rocio-desantiago double-check the [sketch](https://www.sketch.com/s/0424c51d-7818-43ea-8821-6de91eb7ab27) to make sure I've captured every instance (specifically the errors)?

They should be clearly labeled as CURRENT and ERRORS... ignore the ARCHIVE sections.
