### ISSUE TITLE
SPIKE | Error Logging in 686c

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#62028]
## Issue Description
It's unclear what error logging exists in 686c, if/what errors are being generated, and if additional logging needs to be added.

---
## Tasks
- [ ] Review code for error logging.
- [ ] Identity errors that are being generated.
- [ ] Identify logging that should be added.

## Acceptance Criteria
- [ ] Document existing logging.
- [ ] Ticket list of errors that need to be investigated.
- [ ] Ticket logging that should be added.

**Comment by steele-lm** [comment]
@tblackwe I wanted to get error logging for 686c on the board -- feel free to make adjustments if needed.
