### ISSUE TITLE
Usability Session Readout for 686 Usability Sessions

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#6202]
## Goal
After conducting an in-depth usability study, we want to synthesize the information gathered and distill some recommendations for moving forward in creating the feature that best benefit the Veteran.

## Considerations
- Here is the [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/686-form-gating-0220/686-usability-research-plan.md) for this study.

## Tasks
- [x] Review notes, audio
- [ ] Data analysis
- [x] Report findings of Usability testing of 686 pathfinding, workflow selection and general usability 

## Acceptance Criteria
- [x] Create a presentation to include recommendations in long form of usability testing and key findings, PowerPoint (with pdf supplement) format is probably preferred

**Comment by sporeboy** [comment]
MD doc for research analysis is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/686-form-gating-0220/686-usability-analysis.md

OOT will be uploaded pending clarification on LFS protocol.

**Comment by jason-gcio** [comment]
Link to PPT version: https://dsva.slack.com/archives/CLY6Q69RV/p1583446780067800?thread_ts=1583352659.066300&cid=CLY6Q69RV
