### ISSUE TITLE
Reference Design principles on Design Intent touchpoint page

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#62024]
## User Story
As a Governance team member, I want VFS teams to know that the Collaboration Cycle supports the Design System Design principles, so that VFS teams are building products in line with the Design principles.

Assignee: @CherylEvans 
Peer Reviewer: @it-harrison 

## Description
The current Design Intent touchpoint page makes no reference to the [Design Principles.](https://design.va.gov/about/principles) This was noticed when @shiragoodman and @humancompanion-usds discussed the following comment from the Governance team retro on 7/7:

> Teams not prioritizing mobile lately, which has been surprising. Is there anything we can do to nudge them in the right direction to consider that early in their process?

At this time, we will not be explicitly requiring mobile designs at Design Intent (see ticket #61984), however we should be nudging VFS teams to review the Design principles (since mobile first design is part of the Design principles) and inform them that Design Intent feedback will be in alignment with the Design principles. 

## Impacted Artifacts
[Design Intent touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent)

## Tasks
- [x] Identify where within the touchpoint page it would make sense to reference the Design principles
   - Note: it was suggested by Matt that we could link the Design principles under "Artifacts" however please review the full page to determine the most appropriate location for reference
- [x] Add the design principles link where appropriate. 

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS teams are reminded of the VA Design Principles at the Design Intent touchpoint

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
[Draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2710110209/62024+Cheryl+-+Copy+of+Design+intent) created.

**Comment by it-harrison** [comment]
@CherylEvans looks good!

**Comment by CherylEvans** [comment]
I changed the [source page](https://vfs.atlassian.net/wiki/spaces/CC/pages/1782153235/Design+intent), Artifacts section, below the bulleted list.

**Comment by shiragoodman** [comment]
@CherylEvans the Design Principles aren't on the Platform Website. Please revise your sentence.

**Comment by shiragoodman** [comment]
I also don't think we need to encourage VFS teams to review them. I would just state that all Collaboration Cycle feedback aligns with the Design Principles.

**Comment by shiragoodman** [comment]
It just sounds odd to talk about feedback under artifacts. Maybe artifacts is not the right place for it? Maybe we should list it under Outcome?

**Comment by CherylEvans** [comment]
@shiragoodman Agreed! It belongs in [Outcome](https://vfs.atlassian.net/wiki/spaces/CC/pages/1782153235/Design+intent#Outcome).
"All Collaboration Cycle Design Intent feedback aligns with platform [Design Principles](https://design.va.gov/about/principles)."
It makes a lot more sense living there. :-)

**Comment by CherylEvans** [comment]
Published. Closed.
