### ISSUE TITLE
Design | Remove Pension Form

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#62022]
## Issue Description
The online 527 pension form is so outdated that it cannot be processed. VA stakeholders would like access to the form removed from va.gov and users informed of the proper pathway.

## Possible Use Cases
1. Veteran filling out a pension form to secure benefits for themselves.
2. Proxy filling out a pension form on the Veteran's behalf (POA, VSO, family member, etc.).
3. Others?

## Possible Scenarios
1. Pension claim form has been started online but not finished. Intent is to come back later and finish.
2. Pension claim form has been started online, but abandoned.
   * Can/should we cross-check in-progress online forms against the record of paper submitted forms?
3. Individual looking for information on pension benefits.
4. Others?

---
## Tasks
- [x] Identify any additional use cases
- [x] Identity any additional scenarios 
- [x] Identify areas on va.gov that will need changes
- [x] Design solution for va.gov
- [x] Identify the best approach to communicate the change to Veterans/proxies
- [x] Design solution for comms
- [ ] Collab cycle
- [ ] Arrange notifications to be sent out including frequency

## Acceptance Criteria
  - [x] Website experience wireframe(s)
  - [ ] Communication(s) wireframe(s)

**Comment by steele-lm** [comment]
Total in-progress: 4196
=== 21P-527EZ ===
Number of total open in-progress forms: 2677
{2022-10-01 00:00:00 UTC=>1,
2022-11-01 00:00:00 UTC=>2,
2023-02-01 00:00:00 UTC=>1,
2023-03-01 00:00:00 UTC=>10,
2023-04-01 00:00:00 UTC=>37,
2023-05-01 00:00:00 UTC=>571,
2023-06-01 00:00:00 UTC=>1342,
2023-07-01 00:00:00 UTC=>713}
=== 21P-530 ===
Number of total open in-progress forms: 1520
{2023-02-01 00:00:00 UTC=>1,
2023-03-01 00:00:00 UTC=>1,
2023-04-01 00:00:00 UTC=>7,
2023-05-01 00:00:00 UTC=>365,
2023-06-01 00:00:00 UTC=>729,
2023-07-01 00:00:00 UTC=>417}

* (the date is representing the whole month, IE 2023-06-01 00:00:00 UTC=>729 means there are 729 open that were created in June of 2023)
* each form is coded with an expiration date for in-progress forms. Tech ticket (#62075 )will uncover it.

**Comment by fiorella-io** [comment]
**Updates:**
- Entry points designs are currently being reviewed and will be updated on prod by CAIA
- Email notification is currently being reviewed by CAIA and we are waiting for them to give us feedback. Sent 6/27 
- Yesterday I pinged CAIA on the 527 ticket to content review our solution. We are waiting for them to review to pages and give us feedback on the content.

**Comment by fiorella-io** [comment]
## Review page updates:
- Designed the [pension review page](https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/p/456C1472-4FD3-42A3-A454-D9EB09C37899/canvas) this week to match the exploratory [Review Page V2](https://www.sketch.com/s/dc844743-277e-41d4-81ba-a48fd0743952/p/FDCC7DE3-19E9-4598-A55D-5C1CDFCDE94E/canvas) that the Design Team had created.
- Had an accessibility expert review the page on 8/15. [Here's the doc with their feedback](https://docs.google.com/document/d/1nBioRSUM5vpofNLzUQwGMZ0TwvfhqrLn-EpltAoBjQU/edit?usp=sharing).
- Made the following suggested changes:
    - Change subheaders to match design systems. They mentioned subheaders with underlines may be perceived as links
    - Removed redundant headings. The current review page on prod has repeated headings
    - Added currency formatting for all fields in the Financial Disclosure section of the form
    - Added "None" to empty fields. They mentioned using a dash would read poorly with a screenreader
    - Added content to the Document Upload section
