### ISSUE TITLE
Request a Platform website sitemap

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#62043]
## User Stories
As a Platform Content Team,
we need a Platform Website sitemap with all the pages,
so that we can kick off conversations with leadership on who and how to assign SMEs content sections of the website.

As a Platform Content Team,
we need a sitemap of the Platform website exported as a .csv file that allows us to view all pages **by traffic volume**,
so that we can determine which pages should be prioritized for a content review by SMEs

As a Platform Content Team,
we need a sitemap of the Platform website exported as a .csv file that allows us to view all pages **by the Confluence space it belongs to (this may be able to be done by URL structure?)**,
so that we use this information to identify content SMEs

Sitemap started: https://docs.google.com/spreadsheets/d/1AjXsd8owei1IL8fYe0Xm4WEZ_lPnThMTh24Rj-YO3Zs/edit#gid=0

---
## Tasks
- [x] Request from Analytics team (#platform-analytics) an export of all pages from the Platform website, including:
- Page names/titles
- URL
- Confluence space it belongs to
- Views/user traffic (from beginning of 2023 until now)
- Unique views (from beginning of 2023 until now)
- Any other relevant information about visitor usage of each page (from beginning of 2023 until now)
- [x] Share spreadsheet or upload document as a Google sheet and share with the rest of the team

## Acceptance Criteria
- [x] The Platform Content team will have a sitemap of all the pages of the Platform website that includes:

- Page names/titles
- URL
- Confluence space it belongs to
- Views/user traffic (from beginning of 2023 until now)
- Unique views (from beginning of 2023 until now)
- Any other relevant information about visitor usage of each page (from beginning of 2023 until now)
