### ISSUE TITLE
Prepare for Discovery Session of "My Payment History"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#6205]
## Goal
Before lightweight voice interviews, establish any questions to be asked or functionality that needs to be clarified in order to fully understand how the Veteran uses the "My Payment History" feature.

## Considerations
- This will need to be included in a Research Plan and in a smaller conversation guide.
- All are welcome to contribute.

## Tasks
- [ ] Document in GH a list of preliminary questions about how the Veteran uses the tool now and its pain points
- [ ] Establish what improvements might be made from the Veterans perspective.

## Acceptance Criteria
- [ ] An .md file has been drafted in the discovery folder for this feature.

**Comment by sporeboy** [comment]
Nick W's MD doc is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-payment-history/research-design/design-discovery.md

**Comment by sporeboy** [comment]
MD doc review by JA and some revision forthcoming.
