### ISSUE TITLE
VAMC short name and nickname

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#6206]
## Problem Statement
How might we handle the VAMC short name field, which is currently required? 

**Context:** 
The issue was identified, in part, due to  _H. John Heinz III Department of Veterans Affairs Medical Center_ being truncated [#6625] in some places, due to the 70 character limit on a field which is required. An **example** is seen [on the Health Care page](https://www.va.gov/pittsburgh-health-care/health-services/) under primary care but this is likely to occur in multiple places throughout the site. 

![image](https://user-images.githubusercontent.com/55411834/79002709-44aa6e00-7b0e-11ea-9243-0291d3142b13.png)

## Background
- As noted in the [comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6206#issuecomment-591581654) below, “Nickname for this facility” was previously required for the meta-title. This is no longer the case. It is unclear if  Meta Titles factored into the decision to drop the short name from the UI. 
- We can't just remove it because it will break the front-end build 
- Short name is used for SEO and Display

Information can be found in https://va-gov.atlassian.net/browse/VAGOV-6376

## Goal
**Deprecate use of “Nickname for this facility” and default to always using "Name of Facility"**

## Objectives or Key Results this is meant to further
- Objective 3: Deliver a usable and accessible experience

---
## Tasks
- [x] Find and document all instances of System Short Name field in frontend queries: **see https://github.com/department-of-veterans-affairs/vets-website/pull/12194/files?file-filters%5B%5D=.js**
- [x] Find and document all instances of field_nickname_for_this_facility in front end templates and queries, for either of the two content types VAMC system or VAMC facility: **see https://github.com/department-of-veterans-affairs/vets-website/pull/12194/files?file-filters%5B%5D=.liquid**
- [x] Edit identified templates to remove field_nickname_for_this_facility and replace with Name of Facility
- [ ] Remove nickname as field so that it is no longer available for use:
**This will be performed in CMS after https://github.com/department-of-veterans-affairs/vets-website/pull/12194 is released to prod**
- [ ] Confirm this change also resolves [#6625] 

## Acceptance Criteria
- [ ] field_nickname_for_this_facility is is no longer available for use
- [ ] Occurrences of field_nickname_for_this_facility have been replaced with Name of Facility
- [ ] Front end consumes Facility Name field for name displays
- [ ] Existing functionality is otherwise maintained 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Per Kevin Walsh, 
It was required because it was used in the UI. it’s no longer used in the UI, so it shouldn’t (still) be required. 
The GraphQL query needs to be adjusted so that it doesn’t ask for that field. 

https://dsva.slack.com/archives/CPQFCQKEH/p1582740124062500?thread_ts=1582659667.041900&cid=CPQFCQKEH

**Comment by mmiddaugh** [comment]
Per @davidconlon (3/3/2020) we will need a task to remove the use of "Facility nickname" from use (currently in the front-end views of the service accordion at system level.)
https://dsva.slack.com/archives/C0FQSS30V/p1583248673066900?thread_ts=1578432933.130700&cid=C0FQSS30V
