### ISSUE TITLE
Tech Review | Remove Pension Form

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#62075]
## Issue Description
The online 527 pension form is so outdated that it cannot be processed. VA stakeholders would like access to the form to be removed from va.gov and users informed of the proper pathway.

## Possible Use Cases
1. Veteran filling out a pension form to secure benefits for themselves.
2. Proxy filling out a pension form on the Vet's behalf (POA, VSO, family member, etc.).
3. Others?

## Possible Scenarios
1. Pension claim form has been started online but not finished. Intent is to come back later and finish.
2. Pension claim form has been started online, but abandoned.
   * Can/should we cross-check in-progress online forms against the record of paper submitted forms?
3. Individual looking for information on pension benefits.
4. Others?

## Resources
1. [Pension Mural Board with form flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u0e8ac1d6d7681bb7e1b80558)
2. [Pension Mural Board with ideas for removal](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1689262813123/cb880912d3f71ef79be0d63d0e61e306d1e6ae31?wid=0-1689360929417&sender=u0e8ac1d6d7681bb7e1b80558)
3. [About form 21P-527EZ Pension landing page](https://www.va.gov/find-forms/about-form-21p-527ez/)
   * Includes link to online tool/form
4. [Online form/tool](https://www.va.gov/pension/application/527EZ/introduction)
5. [Online form 21P-530 Burial](https://www.va.gov/burials-and-memorials/application/530/introduction)
6. Pension temporary removal mural: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1689262813123/cb880912d3f71ef79be0d63d0e61e306d1e6ae31?wid=0-1689360929417&sender=u674f33e99d68adb0c1952030

---
## Tasks
- [ ] Review technical aspects of the pension form
- [ ] Identify what is required to remove access to the form
- [ ] Identify options for displaying information for in-progress claims
- [ ] Determine expiration date of each form. Per Kyle Soskin: There is a cutoff/expiration date coded into each type of form. For example, for form 526ez, the in-progress forms "expire" after 1 year. For the pension form, the expiration date seems to be 2 months after the last update the user made to the form.
- [ ] Identify areas on va.gov that will need changes
- [ ] Research creating review page to view form data
- [ ] Research add export form form and partial form data

**Comment by steele-lm** [comment]
Hey @DLarson-Oddball I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/benefits-non-disability-645913c7d909c20011380ae8/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account.
  _Posted using [Zenhub](https://www.zenhub.com)_

**Comment by steele-lm** [comment]
In-progress form query from Kyle Soskin:
form_ids = ["21P-527EZ", "21P-530"]
all = InProgressForm.where(form_id: form_ids);nil
puts "Total in-progress: #{all.count}"
form_ids.each do |id|
  puts "=== #{id} ==="
  puts "Number of total open in-progress forms: #{all.where(form_id: id).count}"
  pp all.where(form_id: id).group("date_trunc('year', created_at), date_trunc('month', created_at)")
.count(:id).sort_by {|k,v| k}.to_h
end

**Comment by steele-lm** [comment]
Which yields:
Total in-progress: 4196
=== 21P-527EZ ===
Number of total open in-progress forms: 2677
{2022-10-01 00:00:00 UTC=>1,
 2022-11-01 00:00:00 UTC=>2,
 2023-02-01 00:00:00 UTC=>1,
 2023-03-01 00:00:00 UTC=>10,
 2023-04-01 00:00:00 UTC=>37,
 2023-05-01 00:00:00 UTC=>571,
 2023-06-01 00:00:00 UTC=>1342,
 2023-07-01 00:00:00 UTC=>713}
=== 21P-530 ===
Number of total open in-progress forms: 1520
{2023-02-01 00:00:00 UTC=>1,
 2023-03-01 00:00:00 UTC=>1,
 2023-04-01 00:00:00 UTC=>7,
 2023-05-01 00:00:00 UTC=>365,
 2023-06-01 00:00:00 UTC=>729,
 2023-07-01 00:00:00 UTC=>417}
 
 * (the date is representing the whole month, IE 2023-06-01 00:00:00 UTC=>729 means there are 729 open that were created in June of 2023)

**Comment by juliepedtke** [comment]
@steele-lm Is is possible to pull/uncover data on when forms were last edited (not just when they were created, and when they will expire)? Then we could align on a definition of abandonment to deprioritize some in-progress forms that haven't been touched in a long time.

**Comment by steele-lm** [comment]
@juliepedtke Kyle confirmed that he can narrow the query by last-edit-date once we align on a definition of abandonment.

**Comment by juliepedtke** [comment]
Last-edit-date would be great to have. I think a definition of abandonment will take some discussion, and doesn't need to be done first. We might decide that we want to slice it some other way, like based on how much info they've filled in, etc.

**Comment by juliepedtke** [comment]
I guess that leads me to another question: can we query by how many pages of the form / what % of form fields were completed?

**Comment by steele-lm** [comment]
Kyle indicated that we can "sort of" determine how many pages were filled out...
Here is an example of a stored IPF (in staging)
#<InProgressForm id: 22641, user_uuid: "c32deef0c41744f8a3b20a6e7f63da97", form_id: "21P-527EZ", created_at: "2023-07-13 20:03:48.232230000 +0000", updated_at: "2023-07-13 23:56:52.040156000 +0000", metadata: {"version"=>3, "return_url"=>"/additional-information/direct-deposit", "saved_at"=>1689292611843, "submission"=>{"status"=>false, "error_message"=>false, "id"=>false, "timestamp"=>false, "has_attempted_submit"=>false}}, expires_at: "2023-09-11 23:56:52.037188000 +0000", form_data: [FILTERED], encrypted_kms_key: "v1:AQICAHjVjGLd4IjSSZNlaxuvYz6L//LLhgOqQTfIbDnXZJS...", verified_decryptable_at: nil, user_account_id: "95224dec-0e77-4bad-a908-ec4effe7b611">

* the metadata.return_url part shows the page the frontend should "take them back to" so, you can use that to see where they LAST left off from. But they could have gone to the very last page, and pressed the back button a bunch to get back to that page, we have no way through the IPF to know that. That is the LAST page they were on, in terms of time, not in terms of the furthest they got on the form.

**Comment by juliepedtke** [comment]
Interesting! cc @fiorella-io @ohgreatkate

**Comment by ohgreatkate** [comment]
luckily I believe we captured the URLs in our form flow Murals so that might not end up as challenging as it sounds!

**Comment by fred-khoury-oddball** [comment]
Here is an in progress list of files ive identified are relating to 527 and 530:
burials and memorials form 530:
- files that will need updates related to 530:
  - lib/pdf_fill/forms/va21p530.rb
  - config/form_profile_mappings/21P-530.yml
  - lib/pdf_fill/forms/pdfs/21P-530.pdf
  - app/models/form_profiles/va_21p530.rb
  - spec/lib/pdf_fill/forms/va21p530_spec.rb
  - spec/models/form_profile_spec.rb
  - spec/support/vcr_cassettes/complex_interaction/internal_interactions.yml
  - app/controllers/v0/claim_documents_controller.rb
  - app/models/form_profile.rb
  - app/models/saved_claim.rb
  - app/models/saved_claim/burial.rb
  - app/workers/structured_data/process_data_job.rb
  - lib/bip_claims/service.rb
  - lib/pdf_fill/filler.rb
  - modules/va_forms/config/test.txt
  - modules/va_forms/config/update_form_tags.yaml
  - spec/controllers/v0/burial_claims_controller_spec.rb
  - spec/factories/burial_claim.rb
  - spec/fixtures/pension/metadata.json
  - spec/fixtures/vba_documents/metadata.json
  - spec/jobs/central_mail/submit_saved_claim_job_spec.rb
  - spec/jobs/structured_data/process_data_job_spec.rb
  - spec/lib/pdf_fill/filler_spec.rb
  - spec/fixtures/pdf_fill/21P-530/
  - lib/evss/disability_compensation_form/form4142_processor.rb

home loan COE form 527:
- files that will need updates related to 527:
  - spec/fixtures/pdf_fill/21P-527EZ/
  - app/controllers/v0/claim_documents_controller.rb
  - app/models/form_profile.rb
  - app/models/saved_claim/pension.rb
  - lib/pdf_fill/filler.rb
  - config/form_profile_mappings/21P-527EZ.yml
  - lib/pdf_fill/forms/va21p527ez.rb
  - spec/controllers/v0/pension_claims_controller_spec.rb
  - spec/factories/pension_claim.rb
  - spec/lib/pdf_fill/filler_spec.rb
  - spec/lib/pdf_fill/forms/va21p527ez_spec.rb
  - spec/models/form_profile_spec.rb
  - spec/requests/claim_documents_spec.rb
  - spec/support/vcr_cassettes/complex_interaction/internal_interactions.yml
  - lib/pdf_fill/forms/pdfs/21P-527EZ.pdf
  - lib/evss/disability_compensation_form/form4142_processor.rb
  - app/models/form_profiles/va_21p527ez.rb
  - config/settings.yml
  - lib/evss/disability_compensation_form/form4142_processor.rb
  - spec/models/saved_claim/pension_spec.rb
  - spec/requests/claim_documents_spec.rb
  - modules/va_forms/config/test.txt
  - modules/va_forms/config/update_form_tags.yaml

**Comment by fred-khoury-oddball** [comment]
links found so far
- 527:
https://www.va.gov/pension/how-to-apply/
https://www.va.gov/find-forms/about-form-21p-527ez/
https://va.gov/pension/
https://va.gov/pension/eligibility/
https://www.va.gov/files/2023-02/vawk-black-and-white.pdf#page=46
https://www.va.gov/files/2023-01/pension-benefits-qsg.pdf#page=2
https://www.va.gov/files/2023-01/aging-veterans-qsg.pdf
https://www.va.gov/files/2023-01/vawk-color.pdf#page=46
 
- 530:
https://www.va.gov/burials-memorials/veterans-burial-allowance/
https://www.va.gov/SURVIVORS/docs/NCAQuickGuideADA.pdf page 17
https://www.va.gov/files/2022-11/HPM%20EOL%20Resource%20Booklet%20(1).pdf#page=21
https://www.va.gov/files/2023-02/vawk-black-and-white.pdf#page=47
https://www.va.gov/files/2023-01/pension-benefits-qsg.pdf#page=2
https://www.va.gov/files/2023-01/vawk-color.pdf#page=47

- Other notes:
There are links to both 527 and 530 in the nav bar.

**Comment by fiorella-io** [comment]
Thank you @fred-khoury-oddball! Adding the page # where the links exist was very helpful!
