### ISSUE TITLE
Total In-Progress Pension and Burial Forms

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#62079]
## Issue Description
In order to remove access to the online pension (527) and burial (530) forms, we need to understand how many in-progress claims exist.

---
## Tasks
- [ ] Leverage script created by Kyle Soskin to determine the number of in-progress forms.

## Acceptance Criteria
- [ ] Total number of in-progress pension (527) forms
- [ ] Total number of in-progress burial (530) forms
