### ISSUE TITLE
[BE] Lihan to get implementation production key 

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#6207]
## Tasks
- [x] Schedule demo with VA stakeholders 
- [x] Acquire API production key
- [x] Test to API key to ensure it works

**Comment by Samara-Strauss** [comment]
According to Michael Bastos, we already had a production key issued through the vets-api repo, so Lihan has made a PR to use that key. We'll come back and test after that PR is merged to see if it worked.
