### ISSUE TITLE
[BE] Modify chip/lib settings to add tenant parameters

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#62080]
## User Story
Modify chip/lib settings to add tenant parameters

## Tasks
- [ ] [BE] **Create tenant_id and store in secure param store**
- [ ] [BE] ** Modify vets-api, devops, vsp-infra-application-manifests to add new config **

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by loripusey** [comment]
duplicate
