### ISSUE TITLE
[Launch] HLR: Prepare Launch Product Video for Higher Level Review

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#6209]
## User Story or Problem Statement
As a veteran, I need to be able to get help from the call center so I can effectively navigate through the request for review process.

This story captures the work for the call center product video for Higher Level Review.

Here is the GitHub documentation on how to do this:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/3717881c2f1a488f5e215f6ee11010e32cf1956c/platform/call-center/request-contact-center-review.md

## Goal
Call center folks 

## Tasks
- [x] Create Product Video
- [x] Prepare for Contact Center Review step 2
- [x] Hold Contact Center Review

## Acceptance Criteria
- [x] Product Video complete
- [x] Review held, approved

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
We should move this to next sprint or when all design changes are reflected in staging. That way we can do a true walkthrough of the staging environment as call center intends, with all the features and screens they see on the video being on the product as well.

**Comment by kevinstachura** [comment]
Update: spoke with Robin yesterday and not all changes to HLR have been added to staging as of yet. Would recommend this be moved into the next sprint or when changes are complete in staging.

**Comment by kevinstachura** [comment]
Following up on this - here is an additional information on call center video creation:

Shawna asked:

>Hi everyone! let's talk Product videos for the call center - are there specific instructions for how these should work and what steps to include? Are there examples of good ones? Who typically creates these? The PMs on the teams, with help from their designers/devs?  Thank you!

Joanne replied:

>Hi Shawna! Thanks for reaching out. We’re working on documentation for you since we’re aware that’s missing and confusing!

>Essentially, what will happen is that when the team is ready to create the product guide and video, reach out to our team to set up a meeting. In this meeting, someone from the product team should walk through the primary user flows of the product and we’ll record the session. It doesn’t need production quality! Just a video version of the product guide

**Comment by luke-gcio** [comment]
We may be able to do this in sprint 29 depending on whether the front end changes get done early in the sprint.

**Comment by kevinstachura** [comment]
@luke-gcio if we're planning on completing this task during this sprint, do you think there's value in your setting up a team meeting with call center so we can intro the product to them and walk them through? Or do you think we should hold off on this ticket until the HLR wizard is complete?

**Comment by kevinstachura** [comment]
Spoke with @luke-gcio about this - we'll need to hold off on this one until the new HLR wizard is all set.

**Comment by luke-gcio** [comment]
We should be able to find time to do this in sprint 31.

**Comment by kevinstachura** [comment]
@luke-gcio I believe we've established a while back that this is primarily simply a meeting with call center. Therefore it should fall as a PM activity to monitor when appropriate to schedule meeting and demo to call center whilst recording our walkthrough.

**Comment by luke-gcio** [comment]
We can 100% do this in sprint 35.  @kevinstachura

**Comment by kevinstachura** [comment]
The product guide for BDD has been created and is located here:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/product/526%20Benefits%20Delivery%20at%20Discharge%20-%20Product%20Guide.docx

However, this ticket still requires a launch video.

**Comment by kevinstachura** [comment]
Edit: disregard my previous comment as it was for BDD's product guide.

**Comment by kevinstachura** [comment]
This has been completed and is now in the call center folder in Github:

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/decision-reviews/higher-level-review/call-center
