### ISSUE TITLE
[BE] Create get_token method in service

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#62095]
## User Story
Create private token method in service

## Tasks
- [ ] [BE] **Call client/token method & cache chip token if no token in redis for tenant_id**
- [ ] [BE] **Return token from redis for the tenant_id if token available in redis**
- [ ] [BE] **rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
