### ISSUE TITLE
[BE] Create Service class with initialize method with a new set of tenant parameters

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#62093]
## User Story
Create Service class with initialize method with a new set of tenant parameters
## Tasks
- [ ] [BE] **Rename existing service class to the client**
- [ ] [BE] **Create initialize method in the client with chip_username & chip_password**
- [ ] [BE] **Create Service class with initialize method with tenant_name, tenant_id, chip_username, chip_password**
- [ ] [BE] **Implement parameter check in initialize method in Service class**
- [ ] [BE] **rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
