### ISSUE TITLE
[UX] Pre-Check-in & Day-of Text Messages: Update the Text Messages

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#62099]
## Release 2 Wireframes
[Wireframes](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/868762F3-8E8F-4E23-B0DA-34C1783F0A03/canvas)

## Tasks
- [ ] Verify that this change needs to happen in the VA Notify templates
- [ ] Submit a ticket for VA Notify to immediately update the Pre-Check-in text message that is sent to the Veteran in respond to a "Y" response to the confirm their appointment text message
- [ ] Submit a ticket for VA Notify to immediately update the Day-of Check-in text message that is sent to the Veteran when they text "check in" to 53079 and are able to check-in
- [ ] Request the changes be for both staging and production 
- [ ] Test in staging

**Comment by loripusey** [comment]
@benbrasso-agile6 do we need this ticket?

**Comment by benbrasso-agile6** [comment]
Yeah, this ticket is out of date. No longer needed.
