### ISSUE TITLE
[BE] Create redis class to store & retrieve cached data

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#62094]
## User Story
Create redis class to store & retrieve cached data

## Tasks
- [ ] [BE] **Implement save method to store token for the tenant_id**
- [ ] [BE] **Implement `get` method to retrieve token for the given `tenant_id`**
- [ ] [BE] **rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
