### ISSUE TITLE
[FE] Create new appointments list (i.e. landing) page with this two-region structure

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#62101]
## User Story
As a Veteran, I would like to understand that I need to review my contact information when I complete the Pre-Check-in workflow so that I will understand what I'm doing and why.

## Wireframes
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/F05730C4-9E76-4B1D-AEA0-63CEC7E61175/canvas
![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/9c42389c-6ec4-4a98-95b2-7b1303d979b8)

## Tasks
- [ ] [FE] **Create new appointments list (i.e. landing) page with this two-region structure
    - Region 1: What to do next
        - Update content when pre-check-in is for a group of appointments
    - Region 2: Upcoming appointments
        - Display all upcoming appointments for today
        - Appointments do not disappear until 12:00 a.m. the next day
        - We will not display any action statuses for pre-check-in
        - Update aria labels
        - Display link to details page for each upcoming appointment**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
