### ISSUE TITLE
[FE] Pre-Check-in & Day-of Details Page: Add for Pre-Check-in & Update Content for Primary Button

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#62102]
## User Story
As a Veteran, I would like to have a standard experience when I complete my tasks for a health appointment so that I don't get confused.

## Release 2 Wireframes
[Wireframes](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/868762F3-8E8F-4E23-B0DA-34C1783F0A03/canvas)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/d6b9a24b-a692-46da-9e27-dc6525df45ba)

## Tasks
- [ ] [FE] **Allow access to the Details Page from Pre-Check-in**
    - Action button has different content from Day-of
    - Link to "back to last screen" will be different based on whether Details page was accessed from Pre-Check-in or Day-of
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/62102?planning-poker) with Zenhub @wullaski
