### ISSUE TITLE
[FE] Pre-Check-in & Day-of Login Page: Update the H1 and supporting content 

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#62100]
## User Story
As a Veteran, I would like to understand that I need to review my contact information when I complete the Pre-Check-in workflow so that I will understand what I'm doing and why.

## Release 2 Wireframes
[Wireframes](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/868762F3-8E8F-4E23-B0DA-34C1783F0A03/canvas)

## Tasks
- [ ] [FE] **Pre-Check-in & Day-of Login Page: Update the H1 and supporting content **
    - NOTE: for Pre-Check-in, this should be the same for in-person and phone appointments 
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
@loripusey / @benbrasso-agile6 These changes are merged in our feature branch. See screenshots here:![localhost_3001_health-care_appointment-check-in_verify.png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/e8a3903c-a1b7-420c-9fe2-fb55750c02cc)![localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (1).png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/e3c7f148-dcf2-4acd-811f-090ff9215da5)

**Comment by loripusey** [comment]
Will validate on review env once things are working

**Comment by benbrasso-agile6** [comment]
@brianseek is the help text for memorable date coming from DS? I think it is. I think platform told us to use "two digits" and "four digits," but I sent Shira that ticket to update on their end. Am I correct about the former?

**Comment by benbrasso-agile6** [comment]
These both LGTM though

**Comment by loripusey** [comment]
closing, I can't get a review env to work
