### ISSUE TITLE
Mockup | 686c Stepchildren Info Not Submitting

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#62106]
## Problem
For the question on 686c form, “Your child’s status (Check all that apply),” when people check “Stepchild,” the form submits WITHOUT that information coming through.

Uncovered in #61673: The form field to determine if the stepchild is a biological child of the spouse does not appear to be in the code. However, the date when the child enters the household is present.

## Tasks
- [x] Create design options (team chooses fidelity of the design options based on situation)
- [ ] Get feedback from appropriate stakeholder(s)
- [ ] Choose the target design solution

## Acceptance Criteria
- [ ] Design solution has been chosen
- [ ] Design solution idea has been vetted and is ready to be implemented (i.e. ready to create the wireframes)
- [ ] Follow-up tickets have been created

**Comment by steele-lm** [comment]
@djones2113 I just found a duplicate (old) ticket for this issue that has some suggestions for design: #35141

**Comment by djones2113** [comment]
I think that @evansmith's suggestions of a radio button makes sense in this instance, with the suggested language:

“Is this Stepchild the biological child of your spouse?” (If needed, we could remove “this” in order to have the copy match the paper form)

Yes
No

If Yes> another field will appear below with the language “Date the child entered veteran’s household”. Example of the UI in the screenshot below:
<img width="458" alt="Screenshot 2023-07-17 at 2 30 24 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/114195359/6223842f-5f93-4bef-9663-119a7034f4d1">

If No > proceed with existing questions

Two outstanding questions on my end: 

1. Is the date that a stepchild becomes a dependent trying to yield the same information as the what date did the stepchild move into the veterans home?
2. What happens if your spouse is not yet on your award vs. if they are on the award? The way that this information is collected (i.e. input the stepchild’s parent’s info rather than selecting from an existing dependent, for example) seems like it could invite errors and/or duplicates. Do we have any information on whether or not this is a standing issue?

**Comment by steele-lm** [comment]
@jstrothman Can you provide any insight into the two questions Daniela raised related to stepchild info and spouses?

**Comment by jstrothman** [comment]
@steele-lm Good questions. I don't have any insight on them--I think reaching out directly to James.Landers@va.gov would be a good way to go.

**Comment by steele-lm** [comment]
1. Is the "date your stepchild became your dependent'' trying to yield the same information as the "date the stepchild entered the Veteran's household "?
_The date the stepchild became a dependent would generally be considered the date in which the vet and the biological parent were married, as that is the date it would be assumed the spouse/child became financially dependent on the Veteran.  VA however does not pay out additional dependency benefits unless the stepchild is also a member of the Veteran’s household, thus the need to know when the child became a member of the household.  The child would be considered a member of the Veteran’s household if they live with the Veteran, or if they live apart due to medical reasons or one of them is incarcerated, attending school, or fulfilling a military service obligation. If the child became a member of the Vet’s household prior to the marriage of the parents, the earliest they could be added to the award is the date of marriage.  If they entered the household after the marriage, then the earliest is the date they entered the household._

2. What happens if your spouse is not yet on your award vs. if they are on the award? The way that the online form information is collected (i.e. input the stepchild’s parent’s info rather than selecting from an existing dependent, for example) seems like it could invite errors and/or duplicates. Is this an existing issue? 
_If the spouse is not on the award, the stepchild MAY still be added to the award if the relationship can be established. 

M21-1 VII.i.3.B.6.e  notes: Add a stepchild to a Veteran’s award even if the stepchild’s biological parent has not yet been added to the Veteran’s award as the Veteran's spouse because, for example, the Veteran has not yet provided the biological parent’s Social Security number.  It is only the establishment of the marital relationship between the biological parent and the Veteran -- not the adding of the parent to the Veteran’s award -- that is required to add the stepchild to the Veteran’s award._

**Comment by djones2113** [comment]
Thanks for getting that info, @steele-lm! Based on James's answers, I'm wondering if it would make sense to let the Veteran know that, if they are unsure of the date that the stepchild became a dependent, they can use the date in which the Veteran and biological parent were married. I say this because I suspect that it may be challenging for many Veterans to provide an answer to "date stepchild became your dependent" and providing this information could make this question significantly less burdensome.

If this is possible, then my suggestion would be as follows:

“Is this Stepchild the biological child of your spouse?” (If needed, we could remove “this” in order to have the copy match the paper form)

Yes
No

If Yes> another field will appear below with the language “Date the child entered Veteran’s household”. Example of the UI in the screenshot below:
Screenshot 2023-07-17 at 2 30 24 PM

Underneath the space where the Veteran would input the date, there is additional information that says something like "How does the VA define the date the child entered Veteran's household?" From there, the Veteran could click to find more information, and this is where we could use James's response:

"The date the stepchild became a dependent would generally be considered the date in which the vet and the biological parent were married, as that is the date it would be assumed the spouse/child became financially dependent on the Veteran." 

Example of the UI in the screenshot below:
<img width="488" alt="Screenshot 2023-07-20 at 2 28 29 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/114195359/23d220d0-f0ac-4e71-b899-7f98b86781a9">


If No > proceed with existing questions


---
We would definitely need someone to review the suggested content (if it's possible to include it at all) but I'm not sure who that would be?

**Comment by jstrothman** [comment]
@djones2113 We'll create a [CAIA intake ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=RLHecht%2C+coforma-terry&labels=sitewide+CAIA%2C+sitewide+content-product+support%2C+Sitewide+IA%2C+sitewide+content&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E) to have it reviewed, but I'd love to take a pass first. Also, as info, we don't have to use the exact wording from the paper form. If we can reduce the additional info by adjusting the wording of the question, that's fine.

**Comment by djones2113** [comment]
Thanks for the additional info Julie!

In that case, instead of asking Veteran's to provide "Date the child entered Veteran's household" I think it would be clearer to ask "Date you married the stepchild's biological parent."

One consideration with this recommendation:
Are there any use cases we know of where the date that a Veteran married the stepchild's biological parent wouldn't be an accurate for the date the stepchild became a dependent?

Looking forward to your thoughts @jstrothman

**Comment by djones2113** [comment]
@jstrothman @sortizsh is helping me find a place on Github for me to put this info so we can collaborate--I will update you when I have that link!

**Comment by djones2113** [comment]
I'm actually thinking it will be easiest to collaborate in Mural, so I added the ideas in this ticket to the [686 form flow Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687976281975/2a9c6ca9ea6d955afa7977c777bbb72b15280903?wid=0-1690309144679) for now. @jstrothman would you be able to make another Mural board, maybe for general collaboration like this related to 686c, and I can migrate this information there?

**Comment by jstrothman** [comment]
@djones2113 Thank you--the Mural was very helpful. I think we go with Option 1. I think it's sufficient to not ask for additional confirmation that they entered the household on that date.  As you quoted above, James indicated
>The date the stepchild became a dependent would generally be considered the date in which the vet and the biological parent were married, as that is the date it would be assumed the spouse/child became financially dependent on the Veteran.

**Comment by djones2113** [comment]
Adding the latest [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1690311086208/96d5f59b299912bc8c69542e6943d5b2213b9c72?sender=u6633b44b9a2da5d288ed7845) that @jstrothman and I are collaborating in for reference

**Comment by djones2113** [comment]
An update to those who weren't involved in the discussion: after getting feedback from CAIA about our approach to addressing the question "date stepchild became your dependent" we decided to table that discussion and proceed with designs that focus on the original ask-- incorporating the question "is this child the biological child of your spouse?" 

Mural board with the latest design is [linked here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1690311086208/96d5f59b299912bc8c69542e6943d5b2213b9c72?wid=0-1692733182259) (suggested changes are highlighted). At this point I think we can pass this off to eng @steele-lm? 

Regarding the discussion around clarifying the household question, I'm not sure if this is something we want to add to the backlog for future research (at this point it's just an assumption that this question may be confusing; I don't think we've come across any past research indicating issues with this specific question).
