### ISSUE TITLE
[FE] Pre-Check-in - Landing Page:  Update content when pre-check-in is for a group of appointments  

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#62105]
## User Story
As a Veteran, I would like to have a standard experience when I complete my tasks for a health appointment so that I don't get confused.

## Wireframes
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/F05730C4-9E76-4B1D-AEA0-63CEC7E61175/canvas

## Tasks
- [ ] [FE] **Pre-Check-in - Landing Page:  Update content when pre-check-in is for a group of appointments **
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
