### ISSUE TITLE
[FE] Day-of - Login Page: Update the H1 and supporting content on the Day-of Login page

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#62128]
## User Story
As a Veteran, I would like to understand that I need to review my contact information when I complete the Pre-Check-in workflow so that I will understand what I'm doing and why.

## Wireframes
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/F05730C4-9E76-4B1D-AEA0-63CEC7E61175/canvas

## Tasks
- [ ] [FE] **Update the H1 and supporting content on the Day-of Login page**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
