### ISSUE TITLE
[FE] Notification Component: Release component on My VA

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#62132]
## Background
Once we've completed release readiness checklist we can proceed with releasing the component on My VA.

## Tasks
- [ ] Set component feature flag to be available to all users on production (Allison can assist)
- [ ] PM/DM to update [Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/update-design-system-component/launch-materials/notification-component-release-plan.md) with launch date
- [ ] PM/DM update [Project Outline key dates](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/update-design-system-component/README.md#key-dates) with launch date

**Comment by allisonlu** [comment]
This ticket is blocked until we figure out how to specify "Dashboard" in GA event name for link clicks in the notification component.

- Implementation ticket (for Analytics team): https://github.com/department-of-veterans-affairs/va.gov-team/issues/62875
- Platform support ticket (Slack): https://dsva.slack.com/archives/CBU0KDSB1/p1690827554288859
- AJ's inquiry for DST (Slack): https://dsva.slack.com/archives/C01DBGX4P45/p1689957926709529
