### ISSUE TITLE
EVSS Migration - 526 Submit - create Lighthouse submit526 method

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#62139]
## Issue Description
A new method `submit526` must be added to the BenefitClaims service [here](https://github.com/department-of-veterans-affairs/vets-api/blob/c213d2ed6e0184fd6ac1d0732492a66555c5e98d/lib/lighthouse/benefits_claims/service.rb#L36) to submit the 526 to Lighthouse.

Gated by the `disability_compensation_lighthouse_submit_migration` Flipper switch, this method will ultimately be called [from the submission service](https://github.com/department-of-veterans-affairs/vets-api/blob/c213d2ed6e0184fd6ac1d0732492a66555c5e98d/app/workers/evss/disability_compensation_form/submit_form526.rb#L72) after calling our new transformation service.

---
## Tasks
- [x] `submit526` method created in BenefitClaims service to submit a 526 form to Lighthouse
- [x] tests created as needed
- [x] Review Test results codes vs LH response (figure out the reason for failures)
- [x] Resolve smaller(relative) issues, if possible

## Acceptance Criteria
- [ ] `submit526` method created in BenefitClaims service to submit a 526 form to Lighthouse
- [ ] tests created as needed
- [ ] Resolve smaller(relative) issues, if possible
- [ ] For larger issues, create tickets for 526/LH, as needed

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
