### ISSUE TITLE
[FE] Pre-Check-in & Day-of Landing Page: Display the Next Task for "What to do next"

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#62138]
## User Story
As a Veteran, I would like to have a standard experience when I complete my tasks for a health appointment so that I don't get confused.

## Description
Create a shared component that can be used by both applications. Note the subtle differences needed for each application. For multiple appointment contexts, show two stacked instances of component. 

Multiple appointments for pre-check-in are defined by the IENs that were used in initatePreCheckIn. For day of multiple appointments are defined by appointments that are check-in-able within the check-in window.

## Release 2 Wireframes
[Wireframes](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/868762F3-8E8F-4E23-B0DA-34C1783F0A03/canvas)

## Tasks
- [ ] Create shared component
- [ ] Add component to page of each application
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/62138?planning-poker) with Zenhub @wullaski

**Comment by loripusey** [comment]
@wullaski is this one done or does it need to roll over?
cc: @anita-halici

**Comment by wullaski** [comment]
@loripusey This is going to roll over I need to finish up work on the dynamic title for the pre check in card when there are grouped appointments.
