### ISSUE TITLE
Decide where and how to display Collaboration Cycle user flows/swim lanes

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#62149]
## User Story
As a VFS team member, I want to understand the flow of the Collaboration Cycle, so that I know how the process works and who is responsible for what parts of the process.

As a Governance team member, I want to have documentation around who is responsible for different touchpoints within the collab cycle, so that I can point VFS teams to the right team.

Assignee:
Peer Reviewer:

## Description
New user flows were created in ticket #60141. We need to decide the best place to display this on internal documentation and Platform website. Things to consider:

- Should we update/remove/keep the image on [Platform website](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/)? Consider how this will display.
- Where should we add the user flow in our [internal documentation](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748860945/Collaboration+Cycle)?

## Impacted Artifacts
- [Swim lanes](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1686676305244/4fb520e97c488d1fd053d93c6497e09ab0880207?sender=aa985651-ad5e-49bb-a7c2-1125dcfecc25)
- [Platform website](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/)
- [Internal documentation](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748860945/Collaboration+Cycle)

## Tasks
- [ ] Update [Platform website](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/) after decisions are made
- [ ] Add to [internal documentation](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748860945/Collaboration+Cycle)

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] VFS teams can refer to a swim lanes user flow to see who is responsible for different touchpoints within the collab cycle.
- [ ] VFS teams know when to move to the next collab cycle touchpoint.

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
@CherylEvans this is ready for your review. The internal doc def needs some help. : )

- [Platform website draft](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2711355393/Copy+of+Collaboration+cycle)
- [Internal doc](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2710864175/Collaboration+Cycle+Swim+Lanes+Diagram)

**Comment by CherylEvans** [comment]
@allison0034 
I made a recommendation for the sentence in the [internal doc](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2710864175/Collaboration+Cycle+Swim+Lanes+Diagram).
Mural Board:
- I recommend using the word "channel" when identifying a specific Slack channel? For example, vfs-platform-support channel vs. vfs-platform-support?

- I would also recommend capitalizing the touchpoints—for example, Midpoint review, Design Intent, and Staging review.
- "If applicable, records issues found per Experience." "Experience" does not need to be capitalized unless you are referring to the "Experience standards," document which should be a proper noun.
- Privacy, Security, Infrastructure Readiness Review should be capitalize as a proper noun name. You can capitalize the first instance and then use PSIRR in all of the other instances.
- I recommend capitalizing Contact Center 
- Analytics should be capitalized in all instances.  Team doesn't need to be capitalized.
- I recommend capitalizing "research" in "research review", but not the word "review." You **don't** need to capitalize research in the sentence: Submit you research for review.
- I recommend capitalizing "research" and "conversation" in the sentence: Do you have a "research" plan and conversation guide.
I will take another look once these changes are made. :-)

**Comment by allison0034** [comment]
Thanks @CherylEvans . The Mural was not for review but I can make those changes anyway.

Ok, I have a stupid question. I see a hand full of "capitalization suggestions. For example, research. But why? If I say research review, it isn't a proper noun so why do I capitalize research?

**Comment by CherylEvans** [comment]
@allison0034 If "research" is used as a proper noun (Research review) it should be capitalized. But if you are using it as a generic noun (I am doing research for my homework assignment.), lowercase is okay. :-)

**Comment by allison0034** [comment]
@CherylEvans thank you! Ready for your final review.

**Comment by CherylEvans** [comment]
@allison0034 This looks great!! Peer review complete. :-)

**Comment by allison0034** [comment]
@shiragoodman please announce in ToT

**Comment by shiragoodman** [comment]
@allison0034 i don't see what change was made to platform website. Can you link the updated page here?
