### ISSUE TITLE
PM | Profile | Telephone Validation | Submit Request to VA Profile to get in their queue

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#62146]
Submit a ticket to VA Profile [here](https://dvagov.sharepoint.com/sites/OITEPMOVAPROPUB) while logged into the VA gateway to get the team in the queue so we can use the new telephone validation tools 

[Draft 2 - VA Profile Intake Request Document - Telephone Validation .docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12442028/VA.Profile.Intake.Request.Document.-.Telephone.Validation.docx)
[~Draft 1 VA Profile Intake Request Document - Telephone Validation .docx~](https://github.com/department-of-veterans-affairs/va.gov-team/files/12372077/VA.Profile.Intake.Request.Document.-.Telephone.Validation.docx)
[~Original Doc VA Profile Intake Request Document.docx~](https://github.com/department-of-veterans-affairs/va.gov-team/files/12242689/VA.Profile.Intake.Request.Document.docx)

## Tasks 
- [x]  collaborate to ensure the form is complete (asking Samara for prior example) 
- [x] update using the example 
- [ ] check in w/Karisa and Barry when the form is complete and submitted 

## Acceptance Criteria 
- [ ]  the form is ready to be uploaded to JIRA

**Comment by mtcA6** [comment]
scheduled a call to review this on 8/25

**Comment by mtcA6** [comment]
@Samara-Strauss 
I completed the intake form as best I could. I wasn't sure how to answer the funding question. Do we need separate funding of some sort for this initiative? 

I reviewed the current draft with Mike and Karisa; Mike asked that I firm up the dates for when we'd like to work on things, it's an important part of their process to know when we think we'll work on this. 

With that in mind, once we've answered that funding question, I can create a spike ticket so Tom can review the swagger docs to get a level of effort. Once he's done that, you and I can discuss when we layer this in with our other items and we'll be ready to submit! 

Side note, I confirmed I have access to their jira intake ticket place when logged in so you won't need to do that!

**Comment by Samara-Strauss** [comment]
> Do we need separate funding of some sort for this initiative?

No, we do not since this is work for something we already manage.

> I can prioritize a https://github.com/department-of-veterans-affairs/va.gov-team/issues/64325so Tom can review the swagger docs to get a level of effort. Once he's done that, you and I can discuss when we layer this in with our other items and we'll be ready to submit!

Sounds good!

**Comment by mtcA6** [comment]
Will submit this once we've determined how our roadmap is going to look now that we've got military information and we've also received a revived request for race and ethnicity information. setting this back to the backlog to pick back up once we've had the necessary product conversations

**Comment by Samara-Strauss** [comment]
You are the best. Thank you for being so on top of things! Agree with this approach completely.

**Comment by Samara-Strauss** [comment]
THANK YOU SO MUCH for not letting this fall off the radar. 100% agree that we do not need to do this -- maybe ever -- if the invalid rate is 0.13%.
