### ISSUE TITLE
[BE] Update CHIP client methods to remove error handling

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#62140]
## User Story
Currently, the CHIP client code is rescue'ing the exceptions and logging the exception message to sentry. This should be done by service so consuming code can determine what to do with the raised error.

## Tasks
- [ ] [BE] remove rescue from CHIP `refresh_precheckin` method and determine if it needs to be handled by the service
- [ ] [BE] remove rescue from CHIP `set_precheckin_started` method and determine if it needs to be handled by the service
- [ ] [BE] remove rescue from CHIP `delete` method and determine if it needs to be handled by the service

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
