### ISSUE TITLE
[CHIP][BE] Handle 404 not found errors from LoROTA

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#62141]
## User Story
There seems to be something running every 5 minutes that is causing LoROTA to throw a not found error. This ticket is to investigate that and to resolve it so we don't throw an error

https://tevi.ddog-gov.com/logs?query=%40lorotaUuid%3A1e9cfa94-26dc-498a-96c2-63db2d8f1b5c%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=desc&viz=stream&from_ts=1689631260000&to_ts=1689634800000&live=false

## Tasks
- [ ] [BE][CHIP] Investigate and resolve periodic errors from LoROTA not found.

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
