### ISSUE TITLE
Sprint 10 IA Support

### ISSUE THREAD

**Issue by A6-toma** [department-of-veterans-affairs/va.gov-team#62153]
Ticket to track IA support work during sprint 10.

## User Story
As a shared support team member, I need to understand IA needs each MHV product team has so I can ensure we align with design system requirements and provide the best user experience possible for Veterans and other users of VA.gov. 

## Description
Any MHV teams including: Secure Messaging, Medical Records, Medications, and also related Appointments & Check-In teams may need to request shared support services for information architecture. Within a given sprint, that work should be articulated through tasks (below) and updates (comments on the ticket) as needed. 

## Tasks
- [x] Advise on a naming structure for downloadable files across MHV products (consult with a11y)
- [x] Gain familiarity with IA sitemaps and Mural documents (namely IA on MHV doc) as well as phased architecture plans for all MHV products in advance of 1:1 consults:
   * Meet with Mikki Northuis on 8/1
   * Meet with Coulton Bunney on 8/1
- [x] Get added to weekly meetings for MHV teams to stay updated on current state
   - [x] Medications
   - [x] SM
   - [x] Medical Records
   - [x] Cross-team sync
- [ ] Get details on Medications planned staging review & prepare to do an IA audit in staging environment.

## Acceptance Criteria
- [ ] _Placeholder AC_

### Planning
- [x] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or epic
- [x] Ticket has been assigned to a Sprint

**Comment by sterkenburgsara** [comment]
Update: this sprint was primarily focused on onboarding with the various MHV teams. I have been added to all team UX meetings and will begin to attend those next week. I also have a number of 1:1 syncs with team leads on the calendar to begin to get an understanding of current IA shared support needs. 

Will likely not get to the friendly IA audit of Medications in staging during this sprint - that work will roll over to the next sprint.
