### ISSUE TITLE
[UX][Design] Create Final Wireframes to Include Appointment List Disclaimer

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#62160]
## Background
We do not currently have access to all of the appointments for a Veteran. Currently we only display in-person and phone appointments, but there are other types of appointments that a Veteran can have, such as video or community care appointments.

Because we don't want to slow down our first release with trying to figure out how to get access to all of the appointments, we want to include a disclaimer so that Veteran know what is included and not in the list of appointments.

[Slack thread w/ Peter](https://dsva.slack.com/archives/CMNQT72LX/p1689628962712179)

## Tasks
- [x] Create content for a disclaimer
- [ ] Pick a design component
- [ ] Create final mockups with callouts that include the disclaimer
- [x] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [x] UI review meeting with product/UX team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.

**Comment by benbrasso-agile6** [comment]
Added @kellysmith1008 to help make an adjustment to the VAOS/Appointment disclaimer 

https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 and I wordsmithed the disclaimer. @ytsaoca this is ready for you!

**Comment by benbrasso-agile6** [comment]
TY. This one is waiting for Laura too @loripusey

**Comment by benbrasso-agile6** [comment]
@ytsaoca this one goes back to you. See laura's comment https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/002582CE-7CC7-479C-89BF-374A2C3E3931/canvas?annotation=4307455d-6d00-4b5f-82aa-65e39914e559

**Comment by benbrasso-agile6** [comment]
Yes, we agreed at last wednesday's meeting that the best approach is to direct them to the Appointments online scheduling too. https://www.va.gov/health-care/schedule-view-va-appointments/

**Comment by benbrasso-agile6** [comment]
Laura said she would tweak her recommendation to avoid mentioning "appointments on VA.gov" to make it more clear that you're not really going to a different tool, even though you are, but we're taking you to view a full list of your appointments. 

So, she'll have another comment hopefully shortly.

**Comment by ytsaoca** [comment]
Updated the wireframes. Used Laura's content and keep the link as it was (Find your VA facility)
Closed - https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/aMkVA4d
Open - https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/8VPOJZx

'cc @benbrasso-agile6

**Comment by ytsaoca** [comment]
Updated the wireframes. Used Laura's content and keep the link as it was (Find your VA facility)
Closed - https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/aMkVA4d
Open - https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/8VPOJZx

'cc @benbrasso-agile6

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 @ytsaoca I agree - let's keep Laura's/Ben's suggested content

**Comment by loripusey** [comment]
@benbrasso-agile6 I'm assuming that this new accordion needs to go in Release 2 because that is where we are introducing the appointment list; I will create a separate FE ticket for this in release 2, please let me know when the wireframes are finalized

**Comment by benbrasso-agile6** [comment]
I would say, it's totally up to you. This problem exists today already at a smaller scale. But, adding it to release 2.0 is fine with me. Or 2.1, doesn't matter. Sure, will tag you when it's ready.

**Comment by ytsaoca** [comment]
@benbrasso-agile6 Sorry, I misunderstood your message. I thought you suggest to keep the old version. Just updated the wireframes.
@kellysmith1008 Thanks for confirming it!

**Comment by ytsaoca** [comment]
@benbrasso-agile6 Sorry, I misunderstood your message. I thought you suggest to keep the old version. Just updated the wireframes.
@kellysmith1008 Thanks for confirming it!

**Comment by benbrasso-agile6** [comment]
I would change that link to 

Go to all your VA appointments

And, then, looks great to me.

**Comment by ytsaoca** [comment]
Fixed it!

**Comment by benbrasso-agile6** [comment]
Looks nice. Do you want to go ahead and move that into the "Design" page now? There should be a bunch of artboards to add it into. https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/0EC89917-F949-4461-A7B3-32A5201FD2A2/canvas

I'm going to help move it into the "Design - Release 2.0", "Design - Release 2.1" and "Design - All releases (draft)" pages in that sketch file?

**Comment by benbrasso-agile6** [comment]
@loripusey Release 2.0 in sketch is updated with this component + annotations - https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/868762F3-8E8F-4E23-B0DA-34C1783F0A03/canvas#Version

I did not add this update into the Epic notes

**Comment by loripusey** [comment]
I created a separate ticket in Release 2 for this new accordion
https://github.com/department-of-veterans-affairs/va.gov-team/issues/63914

**Comment by ytsaoca** [comment]
Updated all the appointment list pages on [Design Page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/0EC89917-F949-4461-A7B3-32A5201FD2A2/canvas). Created [design spect](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/qb9R1x5).

**Comment by kellysmith1008** [comment]
Looks great, @ytsaoca! I'm good to close if Ben and Lori are!

**Comment by loripusey** [comment]
One thing that stood out to me with these 2 accordions, one is written from the VA's perspective (i.e. "what to do if YOU...."), the other is written from the Veteran's perspective (i.e. will VA protect MY...."); is that ok?
cc: @benbrasso-agile6 @kellysmith1008 

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/ed99b2fb-9980-4287-aa2f-aa71323e9fa5)

**Comment by loripusey** [comment]
No need to change, just wondering if it was an oversight or if there was a reason for it. I don't care either way and if they have approved it then let's just move on. Thanks @kellysmith1008

**Comment by benbrasso-agile6** [comment]
Keep it at this point :) Can always change later

**Comment by benbrasso-agile6** [comment]
@ytsaoca tysm for adding to design spec

**Comment by benbrasso-agile6** [comment]
Missed 1 lol, I fixed it. Nice job @ytsaoca ! Closing!
