### ISSUE TITLE
[Development] Original Claims: Update Front-End Flow to Support MVI Integration

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#6216]
## User Story or Problem Statement
As a veteran, I need to be able to start my first claim on VA.gov so I can use have a better experience than eBenefits.

Currently Original Claims are on eBenefits and now  that we have MVI we need to get the FE flow done and be ready for integration with our internal end-point.

## Tasks
- [x] Meet with the design team to understand current flow
- [ ] Update FE flow, update language
- [ ] Stub out integration into end-point being created by back end team (would be really cool if you agreed on an interface)

## Acceptance Criteria
- [ ] FE ready to go
- [ ] Would be nice to get an integration test we can then use for SQA with MVI

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ndsprinkle** [comment]
@luke-gcio Here is the other PR that I mentioned on #6217 : https://github.com/department-of-veterans-affairs/vets-website/pull/11079
That PR removes the gating step in the front end flow to support original claims.

**Comment by ndsprinkle** [comment]
I have connected the final PR to this ticket that removes the staging restriction on this functionality: https://github.com/department-of-veterans-affairs/vets-website/pull/12146

This will not be merged until appropriate testing has been done with the back end team.
