### ISSUE TITLE
[Development] Original Claims: Integrate Front-End with Back End Endpoint for MVI Integration

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#6217]
## User Story or Problem Statement
As a veteran, I need to be able to start my first claim on VA.gov so I can use have a better experience than eBenefits.

Currently Original Claims are on eBenefits and now that we have MVI we need to integrate with our internal end-point.

## Tasks
- [ ] Complete integration with BE endpoint

## Acceptance Criteria
- [ ] Integration test we can then use for SQA with MVI

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ndsprinkle** [comment]
@luke-gcio I just remembered that there are actually two PRs already opened by me for this ticket and the other Original Claims ticket. Here's the one that relates to this: https://github.com/department-of-veterans-affairs/vets-website/pull/11220
Not sure how much will need to be modified with that. I can get together with Silvio to see if anything else needs to be added or changed, but that PR supports the main issue that could still affect veterans who are filing Original Claims. I will post a comment on the other ticket with the other PR that removes the gating in the front end flow.

**Comment by luke-gcio** [comment]
Awesome, thank you.  Ok, let me set up that call I was talking about.

**Comment by ndsprinkle** [comment]
@luke-gcio The pull request I mentioned above needs some tweaking based on recent decisions by the back end team. I will meet with Silvio to work on the updates required to this PR.

**Comment by ndsprinkle** [comment]
I have connected the final PR to this ticket that removes the staging restriction on this functionality: department-of-veterans-affairs/vets-website#12147

This will not be merged until appropriate testing has been done with the back end team.
