### ISSUE TITLE
Incorporate new design elements into non-disability claim list view cards 

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#62179]
## Value Statement

**_As a_** veteran checking the status of a non-disability claim
**_I want ** the claim cards in the list view to match the aesthetic of disability claims cards to the extent it helps me find the content I'm looking for
**_So that_**  these claims don't seem like an afterthought or less important.

## Background Context
- We're making some change to claim card designs for disability claims and we need to think through which elements need to be universally applied to all cards.
- Needs to be merged with other ticket #62179 

## Acceptance Criteria
- [ ] Elements that Design identifies as needing to be universal across cards are implemented for non-disability, STEM claims, and decision review card types

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by skylerschain** [comment]
The Evidence Submission spec is now live in Sketch [here](https://www.sketch.com/s/98e35645-34eb-40cf-80c1-6c4952943584/v/G5kOwv/p/B9C46ABC-36AD-4CA8-9896-55762FC6912E/canvas/#Version).

Mocks for non-disability and decision review cards specifically can be seen in the mobile section. 


![Screenshot 2023-08-01 at 1 21 03 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/ed1a249e-19f1-4648-86a9-856abb5f5601)
