### ISSUE TITLE
[SW] Usability Study Synthesis

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#62174]
## Issue Description
Full Research Findings doc can be completed a sprint after research is completed. Complete Topline summary 48 hours after Perigean has closed the study. 

---
## Tasks
- [x] _Compile/organize findings on Mural board_
- [x] _Create topline summary GH document_
- [x] _Create Research Findings GH document_
- [x] _Complete VA Recruitment Checker for Equality spreadsheet and add screenshot to Research Findings_
- [x] _Add Findings to Research Repo_

## Acceptance Criteria
- [x] _[Topline Summary created](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/streamlined_waiver/research/topline-summary.md)_
- [x] _[Research Findings GH document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/streamlined_waiver/research/research-findings.md)_
- [x] _[Completed VA Recruitment Checker for Equality Spreadsheet](https://docs.google.com/spreadsheets/d/1pq7TSHZonfpzAQBJj6B2geGHlNUwZEs4DzEvxcRgu0o/edit?usp=sharing)_
- [x] _[Findings added to Research Repo](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/334)_

**Comment by mgleo** [comment]
Moved into this sprint, this will begin today. @HeatherRienks @Tom-Davis

**Comment by mgleo** [comment]
@Tom-Davis @HeatherRienks Moved to Validate
