### ISSUE TITLE
Update CTA widget to redirect after login

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#62171]
## Issue Description
Auth Experience updated the sign-in CTA widget so it redirects to the correct destination after login, we need to update the `redirect` property to `true` so the navigation will function correctly. 

Noticed we have two references to `manage-va-debt` while poking around in there. One is named `MANAGE_VA_DEBT` and looks like it was originally in place for the legacy debt portal and can likely be removed. I believe we're using `COMBINED_DEBT_PORTAL` now, but let's use this ticket to confirm that. 

#### Notes:
 - OG discussion on inconsistencies: https://dsva.slack.com/archives/C52CL1PKQ/p1685556476106629?thread_ts=1685556303.394659&cid=C52CL1PKQ
 - Discussion on updating CTA widget:  https://dsva.slack.com/archives/CPE4AJ6Q0/p1689689340892889
 - [OG CDP widget addition PR](https://github.com/department-of-veterans-affairs/vets-website/pull/21493) 
 - Widget location `src/applications/static-pages/cta-widget/ctaWidgets.js`

---
## Tasks
- [ ] Update CTA widget so redirect is true
- [ ] Check to see if we can remove any deprecated widgets

## Acceptance Criteria
- [ ] Widget had been updated and login is redirecting as anticipated
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by andaleliz** [comment]
Hey team - I brought this up to @DanielleThierryUSDSVA, and she passed along a consideration our IA folks brought up once upon a time:

The `/manage-debt` page also includes a separate link to the FSR page, which is an important page.  If a person signs in via the widget, but actually needs the FSR, it's not easy for them to get back to the `/manage-debt` page once they are redirected, and find that FSR link.  I personally think it's unlikely this is the case given that the sign-in CTA widget very clearly states "Sign in to **manage your debt**", but it's still a viable edge case.

The content team is going to do an audit to determine which pages have this scenario (a sign-in CTA but also important links to other pages) and then work with the Auth Exp team to make a recommendation about this should be consistently handled across VA.gov.  Ultimately, it's up to your team how you want to proceed but I wanted to get this on your radar in case you decide you want to hold off on this work until content/auth exp have a chance to sync.

On a related note, I've asked about the possibility of setting up a redirect so the back button would take the person back to where they signed-in from in [this Slack thread](https://dsva.slack.com/archives/CSFV4QTKN/p1689873880153079).

**Comment by OptionSelect** [comment]
Fixed by https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/70029
