### ISSUE TITLE
EVSS Migration - getPDF - Implement call to POST getPDF from Form526BackupSubmissionProcess

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#62170]
## Issue Description
The Form526BackupSubmissionProcess retries failed 526 submissions, pulling the EVSS-formatted request JSON from the database and then resubmitting it via POST getPDF. We now need to call out to our new transformation service (built in [this story](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/61522)) to transform it into a LH-formatted request before resubmitting to POST getPDF.

NOTE: this endpoint is still in development, see [this thread](https://dsva.slack.com/archives/C02CQP3RFFX/p1693267337721269)
---
## Tasks
- [ ] Does it belong in the BenefitsClaims service method? Coordinate with Kyle & Co.
- [ ] There is also a "non-breakered" call to POST getPDF that needs to be better understood, then migrated accordingly

## Acceptance Criteria
- [ ] Insert call to LH transformation service before resubmitting from the Form526BackupSubmissionProcess 
- [ ] Supporting tests

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sethdarragile6** [comment]
@RakshindaAslam I'd forgotten that I had referenced this ticket as being dependent on #63779 (backup submission discovery). Since we don't actually call the submit endpoint from within the backup submission process, I'm going to repurpose this ticket for our getPDF migration.

**Comment by alatempa24** [comment]
Ticket is OBE - Carbs will carry out this work in https://github.com/department-of-veterans-affairs/va.gov-team/issues/82245
