### ISSUE TITLE
Update team operational documents with Erin's information

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#62189]
## User Story
As a governance team member, I want to see Erin White's information in our operational documents, so that I can see and communicate the most current information about our team. 

Assignee:
Peer Reviewer:

## Description
Replace instances of "Sara Sterkenburg" on governance team documentation with "Erin White." 

## Impacted Artifacts
* [Governance Team PO Transition Plan](https://vfs.atlassian.net/wiki/spaces/~624b430af6a26900695fd7f7/pages/2520318008/Governance+Team+PO+Transition+Plan)
* [Contact Us page](https://vfs.atlassian.net/wiki/spaces/CC/pages/1764524036/Contact+us) - _ensure this updates to platform webesite_
* Orientation slide decks
* [Welcome screen used for Design Intent meetings](url)

## Tasks
- [ ] Replace name and image of Sara Sterkenburg in operational docs (listed above) with Erin White's information

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Erin is listed as the IA for Governance team across Platform Website and internal team documentation.

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
@shiragoodman 

1. Do you think we should have Sara attend the reviews for the next couple of weeks until Erin is onboarded?
2. I do not have access to add them to this email:![Screen Shot 2023-07-21 at 1.37.39 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/7de091bf-9a61-43dc-b4ed-2146a11be318)
3. I do not have access to change the [DraftingTemplate](https://docs.google.com/spreadsheets/d/1zabutKbKQnZMb3A2hxs-OaB7q6j8DWw1xcFaCfFDIVw/edit#gid=654390984)

**Comment by shiragoodman** [comment]
> @shiragoodman
> 
> 1. Do you think we should have Sara attend the reviews for the next couple of weeks until Erin is onboarded?

- Sara will attend what she can. If she's unable to attend, she will sync with Erin ahead of time to prepare them. For eample.. the DST staging review on 7/27

> 2. I do not have access to add them to this email:![Screen Shot 2023-07-21 at 1.37.39 PM.png](https://camo.githubusercontent.com/497c3fd8862a99559b503fa7dbde66324b2fd3ecd2e0cb1e1163c7d76130095d/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566376531353534333738326135633165653130663166302f37646530393162662d396136312d343364632d623465642d323134366131316265333138)

- I can add them.

> 3. I do not have access to change the [DraftingTemplate](https://docs.google.com/spreadsheets/d/1zabutKbKQnZMb3A2hxs-OaB7q6j8DWw1xcFaCfFDIVw/edit#gid=654390984)

- I can add them.

> 4. I went ahead and added them to the on support but that is about a month from now, is that ok? Maybe they should shadow someone for a week?

- Maybe let's push to 6 weeks. The Onboarding template says new team members shouldn't be expected to be On Support until 2 months in. Can you push Erin's first rotation out a couple weeks from where it currently is?

**Comment by allison0034** [comment]
I am still seeing Sara, not Erin in the drafting template.

**Comment by shiragoodman** [comment]
I haven't made the change yet. I said I can add them, not I have added them 😝

**Comment by allison0034** [comment]
@shiragoodman any luck on updating the drafting template?

**Comment by shiragoodman** [comment]
Erin has been added to the governance-team distribution list and the baseline DraftingTemplate.

@CherylEvans please give me permission to edit the Forms team - Form 21P draftingTemplate so I can add Erin to the drop down list.

**Comment by allison0034** [comment]
@shiragoodman should you go ahead and remove Sara's name from the [DraftingTemplate](https://docs.google.com/spreadsheets/d/1zabutKbKQnZMb3A2hxs-OaB7q6j8DWw1xcFaCfFDIVw/edit#gid=654390984)?

**Comment by shiragoodman** [comment]
@allison0034 I left her on there for now in case she will be helping out next week. I can remove her later on.

**Comment by allison0034** [comment]
@briandeconinck ready for you review. All artifacts are in the artifact section

**Comment by CherylEvans** [comment]
@allison0034 @erinrwhite The User story and AC have been satisfied. All tasks are complete. Peer review complete. :-)
