### ISSUE TITLE
EPIC | Profile | Authenticated Menu Modifications

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#62186]
## Background

From our [research this year ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2023-06-add-dependents-records-discovery/summary.md)we've noticed a trend of users searching for Letters and Dependents from the profile (and across the broader va.gov website). 

We're looking for a low stakes, low development way to reduce the number of users searching for letters and dependents from the profile and across the broader VA.gov site. Adding Letters and Dependents to the "personalized menu" is potentially a great way to do exactly that. 

### [Authenticated Menu Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/authenticated-menu)
- [Add Dependents and Letters Project Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/authenticated-menu/add-dependents-letter/README.md)
- [GH Directory](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/authenticated-menu)
- [Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/authenticated-menu/add-dependents-letter/release-plan.md) 

## Analytics
Specific KPIs can be found on the project outline linked above
- [Domo](https://va-gov.domo.com/page/1834995012?userId=66061986)
- [GA Dashboard ](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/jTwco5hFRBmuXcjZN9YSPA/a50123418w177519031p176188361/_u.date00=20230806&_u.date01=20230814/)

## Tasks
 
```[tasklist]
### Discovery/Design Intent
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62198
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/63413
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62944
```

```[tasklist]
### Dev
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62940
```

```[tasklist]
### analytics
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/64617
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65406
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/66653
```

```[tasklist]
### Pre-Launch
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/64311
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62185
- [x] Staging Review Scheduled
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65194
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62194
```

```[tasklist]
### Launch
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/64424
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/64430
```

```[tasklist]
### Post Launch
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/70769
``` 

## Artifacts
Some [quick sketches for what this change could look like](https://www.sketch.com/s/113f0ee6-e77d-4b1b-bf02-af27580931fe/p/F06226AA-DBC6-482C-A474-E9585FDF7178/canvas) 
<details><summary>7/25/2023 Notes from Call w/Content/IA #62185 </summary>
<p>

- next steps
     - figure out the kpi's 
     - technical discovery - how does the menu get updated 
     - how to chunk out the menu (refreshed mock up)

Sara Smith's notes [google document](https://docs.google.com/document/d/14sA5NPyXYj_z_TXrwL6N3DLLdqr81pWAtxDX2Q7tLyw/edit)
</p>
</details>

**Comment by mtcA6** [comment]
@Samara-Strauss I'm going to close this epic out even thought these two items are open: 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/0142b191-8061-4cd8-8d66-de342fe2b835)

The QA item would require implementation that isn't our team's code and should be completed by the sitewide public websites team since they own that code. 

I have the analytics request in the backlog in the github project so I wont lose sight of it.
