### ISSUE TITLE
Tech Review | Remove Burial Forms

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#62188]
## Issue Description
The online 530 burial form is so outdated that it cannot be processed. VA stakeholders would like access to the forms removed from va.gov and users informed of the proper pathway.

## Possible Use Cases
1. Veteran filling out a burial form to secure benefits for themselves.
2. Proxy filling out a burial form on the Vet's behalf (POA, VSO, family member, etc.).
3. Others?

## Possible Scenarios
1. Burial claim form has been started online but not finished. Intent is to come back later and finish.
2. Burial claim form has been started online, but abandoned.
   * Can/should we cross-check in-progress online forms against the record of paper submitted forms?
3. Individual looking for information on burial benefits.
4. Others?

## Resources
1. [Pension Mural Board with form flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u0e8ac1d6d7681bb7e1b80558)
2. [Pension Mural Board with ideas for removal](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1689262813123/cb880912d3f71ef79be0d63d0e61e306d1e6ae31?sender=u0e8ac1d6d7681bb7e1b80558)
3. [About form 21P-527EZ Pension landing page](https://www.va.gov/find-forms/about-form-21p-527ez/)
   * Includes link to online tool/form
4. [Online form/tool](https://www.va.gov/pension/application/527EZ/introduction)
5. [Online form 21P-530 Burial](https://www.va.gov/burials-and-memorials/application/530/introduction)

---
## Tasks
- [ ] Review technical aspects of the burial form
- [ ] Identify what is required to remove access to form
- [ ] Identify options for displaying information for in-progress claims
- [ ] Confirm expiration date of each form. Per Kyle Soskin: There is a cutoff/expiration date coded into each type of form. For example, for form 526ez, the in-progress forms "expire" after 1 year. It appears the burial form expires 2 months after the last update a user makes.
- [ ] Identify areas on va.gov that will need changes
