### ISSUE TITLE
Create documentation for Landing Page Research 

### ISSUE THREAD

**Issue by Nyanteea** [department-of-veterans-affairs/va.gov-team#62190]
**Some of this work may be impossible now that 

## Issue Description

Create documentation for landing page research and add to research archive 
**Note some of this work may be difficult or impossible with staff changes

---
## Tasks
- [x] Add to research archive with appropriate tags 
- [x] Convert research presentation to PDF and ask engineering how to upload to Git
- [x] Organize research notes and videos, if possible

## Acceptance Criteria
- [x] Documentation for landing page research is added to Github
- [x] Access to the documentation is available to all

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lydiahooper** [comment]
On Github: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/research/2023-05-526ezLandingPagesRedesign/526%20Landing%20Pages%20Redesign%20Research%20Findings.pdf

In research repository: https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/322
