### ISSUE TITLE
Design | Remove Burial Form

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#62193]
## Issue Description
The online 530 burial form is so outdated that it cannot be processed. VA stakeholders would like access to the form removed from va.gov and users informed of the proper pathway.

## Possible Use Cases
1. Veteran filling out a burial form to secure benefits for themselves.
2. Proxy filling out a burial form on the Vet's behalf (POA, VSO, family member, etc.).
3. Others?

## Possible Scenarios
1. Burial claim form has been started online but not finished. The intent is to come back later and finish.
2. Burial claim form has been started online, but abandoned.
   * Can/should we cross-check in-progress online forms against the record of paper-submitted forms?
3. Individual looking for information on burial benefits.
4. Others?

---
## Tasks
- [x] Identify any additional use cases
- [x] Identity any additional scenarios 
- [x] Identify areas on va.gov that will need changes
- [x] Design solution for va.gov
- [x] Identify the best approach to communicate the change to Vets/proxies
- [x] Design solution for comms
- [x] Send designs for content review through CAIA
- [ ] Collab cycle
- [ ] Arrange notifications to be sent out including frequency

## Acceptance Criteria
  - [x] Website experience wireframe(s)
  - [ ] Communication(s) wireframe(s)

**Comment by fiorella-io** [comment]
## Review page updates:
- Designed the [pension review page](https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/p/C3ED650A-CE7B-4B48-A85D-5E7F41DE25FC/canvas) this week to match the exploratory [Review Page V2](https://www.sketch.com/s/dc844743-277e-41d4-81ba-a48fd0743952/p/FDCC7DE3-19E9-4598-A55D-5C1CDFCDE94E/canvas) that the Design Team had created.
- Had an accessibility expert review the page on 8/15. [Here's the doc with their feedback](https://docs.google.com/document/d/1nBioRSUM5vpofNLzUQwGMZ0TwvfhqrLn-EpltAoBjQU/edit?usp=sharing).
- Made the following suggested changes:
    - Change subheaders to match design systems. They mentioned subheaders with underlines may be perceived as links
    - Removed redundant headings. The current review page on prod has repeated headings
    - Added currency formatting for all fields in the Financial Disclosure section of the form
    - Added "None" to empty fields. They mentioned using a dash would read poorly with a screenreader
    - Added content to the Document Upload section
 
### Things to consider when implementing this solution:
- Recommend against `dl`(definition/description list) for implementation
The Description List is an HTML element that we suspect VA developers might want to use but should stay away from. They read pretty inconsistently on different browser/screenreader combinations and sometimes are very wordy. Stick to semantic headings instead, your normal H1, H2, etc.!
- Be explicit about whether document links open in a new tab
