### ISSUE TITLE
Collaboration Cycle for AE Profile , Authenticated Menu Modifications

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#62194]
### VFS team name

Authenticated Experience - Profile

### Product name

Authenticated Menu

### Feature name

Authenticated Menu Modifications

### GitHub label for product

Profile

## Kickoff questions

<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

Next Sprint 7/19/2023

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

This update is based on recent user research and analytics.

### Will your work involve changes to...

Both

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline

[Project outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/authenticated-menu/README.md)

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Notify the Collaboration Cycle team of this ticket in the vfs-platform-support Slack channel.

- [X] I acknowledge that I must notify \#vfs-platform-support after submitting this issue.

Kickoff Slack Thread with VFS team: [LINK](https://dsva.slack.com/archives/CBU0KDSB1/p1690308725102119)

</details>

 ## Recommended Collaboration Cycle touchpoints

### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- Navigate to reference link: [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent)
- [x] Schedule your Design Intent when ready:
   - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
      - The Governance team is responsible for inviting our team members, including our Product Owner, Product Manager, and practice area specialists. We also notify OCTO-DE practice area leads when we finalize meeting scheduling. 
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [x] Link all artifacts **ONLY** in the Design Intent artifacts section below at least two days before the scheduled Design Intent.  **Do NOT add artifacts to Comments section**
  
**Design Intent artifacts**

See Platform guidance on [Design Intent artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Design Intent meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

- [x] [User flow](https://www.sketch.com/s/113f0ee6-e77d-4b1b-bf02-af27580931fe/p/F06226AA-DBC6-482C-A474-E9585FDF7178/canvas) is available on the linked Sketch page - please see the section labeled "To review for design intent"
- [x] **Whiteboard sketch or other lo-fi prototypes or wireframes:** option 1 ([mobile](https://www.sketch.com/s/113f0ee6-e77d-4b1b-bf02-af27580931fe/a/j4k9MqD), [desktop](https://www.sketch.com/s/113f0ee6-e77d-4b1b-bf02-af27580931fe/a/ZVK3wEG)), option 2 ([mobile](https://www.sketch.com/s/113f0ee6-e77d-4b1b-bf02-af27580931fe/a/dgkKWqm), [desktop](https://www.sketch.com/s/113f0ee6-e77d-4b1b-bf02-af27580931fe/a/AZJA4Em))
- [x] **Research plan:** n/a we are relying on analytics to measure the impacts of this change and not conducting usability research
- [x] **Any other artifacts you have so far:** this [Sketch page](https://www.sketch.com/s/113f0ee6-e77d-4b1b-bf02-af27580931fe/p/F06226AA-DBC6-482C-A474-E9585FDF7178/canvas) contains a section called "Other things we explored" that contain some other ideas we considered for the menu but ruled out for various reasons.  We also considered putting these items in the profile, but decided to start with a low-lift experiment.
  
##### Platform actions
- [x] Design Intent [Slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1690476112364549) with VFS team: 
- [x] Meeting date/time: 08/01/23 at 11:30 AM ET
  
##### Platform actions

- [ ] If you have feedback, create feedback tickets and link to this epic. Once you have completed you review, check the box next to your practice area
  - [x] Accessibility has completed the review
  - [x] Design has completed the review
  - [x] IA has completed the review
- [ ] Update this ticket with the Zoom recording
  - Recording URL: https://oddball-io.zoom.us/rec/share/HNnbCp9EiDsRFFgqYr74qS5pTLlMlguY00pOMAWHlshcecgKTxOv6XiEk5Fo__E.titMmRNP2Hs266sL
  - Password: vSD#X&34
  
##### VFS actions

- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Sitewide CAIA Intake Request
<details>
  <summary>Toggle Sitewide CAIA Intake Request</summary>

##### VFS actions
- [x] Complete and link to [Sitewide CAIA intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62185)

</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>
n/a we're using metrics to monitor this not putting this through a research study

#### VFS actions
- [ ] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>

n/a we're skipping straight to staging review
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [ ] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

Provide links or documents for the following:

- [ ] Finalized design prototype or mockup
- [ ] Specify which pages are included in the review 
- [ ] Research plan
- [ ] Conversation guide
 
**Content artifacts**
  
- [ ] Your product’s content source of truth 
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)

**IA artifacts**

- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) feedback you received, including an IA review document or intake form.

##### Platform actions
- [ ] Midpoint review Slack thread with VFS team:
- [ ] Meeting date/time:

##### Platform actions

- [ ] If you have midpoint review feedback, create feedback ticket and link to this epic. Once you have completed your review, check the box next to your practice area
  - [ ] Design has completed the review
  - [ ] Accessibility has completed the review
  - [ ] IA has completed the review
  - [ ] Content has completed the review
- [ ] Update this ticket with the Zoom recording
  - Recording URL: 
  - Password:
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [x] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [x] [Link to the Analytics Implementation and QA Request ticket below](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63413)

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [ ] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [ ] Link to the Contact Center review request ticket below
n/a 
</details>

### Staging Review
<details open>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [ ] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [ ] ~~If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.~~
- [x] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [x] I confirm the environment is available and test users have been provided. < this is enabled for all users in staging, can use any user you'd like
- [x] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
 
**Staging Review artifacts**
  
See Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts). Platform findings are based solely on the staging URL and test users provided, as reviewed during the four days before the Staging Review meeting. Any test cases not covered or any ongoing work taking place during the review period may not be reflected in those findings.  

**Product artifacts** 
- [x] Staging URL: https://staging.va.gov/   < this can be tested with any logged in staging user
- [x] Specify which pages are included in the review        <the only thing requiring review is the authenticated menu
- [x] Staging test user information < see above, can test w/any user        
  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)

n/a  

**IA artifacts**
- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) of the findings you received, including an IA review document or intake form.

n/a

**QA artifacts**

This is visible w/all users in Staging. There isn't a formal QA process for this initiative 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/87741d4b-1733-4195-b6ee-83394fa97e65)

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [ ] [Regression test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-regression-test-planRegressionTestPlan)
- [ ] [Test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-test-planTestPlan)
- [ ] [Coverage for References](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [ ] [Summary(Defects) reports](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [ ] [E2E tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-e2e-test-participationE2ETestParticipation) (provide a link to the product’s code)
- [ ] [Code coverage](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-unit-test-coverageUnitTestCoverage) (provide a link to the product’s code)  
  
**Accessibility artifacts**
  
- [ ] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D). For details, see [Prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).
 

##### Platform actions
- [x] [Staging review Slack thread with VFS team](https://dsva.slack.com/archives/C909ZG2BB/p1693426063687859)
- [x] Meeting date/time: Friday, September 8, 2023 at 2 p.m. Eastern

##### Platform actions

- [ ] Update this ticket with the Zoom recording
  - Recording URL: 
  - Password:
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [ ] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [ ] Link to the Readiness Review ticket below

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by mtcA6** [comment]
This is launched and in production
