### ISSUE TITLE
UX/Design | Profile | Personalized Menu Modifications | Initial Discovery

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#62198]
## Background 
We're looking to modify the "Personalized Menu" to include links to Dependents and Letters.

See this [slack thread for some context for our initial convo with CAIA](https://dsva.slack.com/archives/C01K37HRUAH/p1689692487393159)
[See this slack thread for the AE conversation](https://dsva.slack.com/archives/C909ZG2BB/p1689606177353799)

## Tasks
- [x] meet with content IA teams to discuss the idea of adding dependents and letters to the menu 
- [x] prep for design intent 

## Acceptance Criteria 
- [x] have artifacts so we can go into design intent 
- [x] ready for design intent

**Comment by mtcA6** [comment]
@pamela-drouin @andaleliz thoughts on sizing here?

**Comment by andaleliz** [comment]
I think it would be more than a day of work, but less than a full week, so I'd give it a 5.

**Comment by adamwhitlock1** [comment]
Here is an example from amazon

![Screenshot 2023-07-21 at 9 38 50 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/52fc174b-4b46-4c60-a755-cac0b98dbc34)

**Comment by mtcA6** [comment]
@adamwhitlock1 that's more for this story here: [Design | Enhanced Personalized Experience | Profile "Hub" discovery to solve H1 Issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60822) #60822  
  
this story is about modifying this list:

![](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/8c3ca032-b537-462e-abaa-fccbe4f1cccc)

**Comment by andaleliz** [comment]
I've done some thinking about this in anticipation of our meeting next week, wanted to share some thoughts. Of course, I will defer to our content and IA folks on final say :)

-  the labels should be "Dependents" and "Letters" since those are the most popular terms people are searching with.  The mobile app menu item says "VA Letters and documents", but when you click through, the h1 says only "letters" so I still feel like letters is right. 
-  dependents should link to the dependents tool va.gov/view-change-dependents/view
-  letters should link to the letters tool (va.gov/records/download-va-letters/letters/, which actually redirects to va.gov/records/download-va-letters/letters/confirm-address so maybe that's better)
- I worked [through some possibilities](https://www.sketch.com/s/113f0ee6-e77d-4b1b-bf02-af27580931fe/p/F06226AA-DBC6-482C-A474-E9585FDF7178/canvas) for how it could be organized in the menu.  I'm leaning toward keeping it as simple as possible without changing anything except adding the two links, so that we're minimizing variables in our experiment
- It looks the personalized menu events in GA are prefixed with `Navigation - User - [link name]` so we should be set up to easily collect data, though not sure if FE has to pass in a parameter or if it'll pick it up automatically.

**Comment by mtcA6** [comment]
Love it, agree the fewer variables we introduce the better. 

Do we have metrics on how many people get to the profile from the personalized menu vs the link on My VA dashboard? Vs some other third way? 

I was clicking around in GA and I simply don't know enough about how the events are structured to be able to find the answer to that.

**Comment by andaleliz** [comment]
Yep, we sure do, @mtcA6! I don't think there is a report set up to do it automatically, but you could do the calculations yourself. There is are event actions you could compare: the My VA link event action is `Dashboard - Navigation - View Link - View Your Profile` and the personalized menu  event action is `Navigation - User - Profile`.

A third way could be deduced possibly by looking at the navigation summary report for `/profile/personal-information` (since that's the entry point) and then you could look on the pages in that report for events.

Attending analytics office hours would be a great way for to learn about how to figure out how events are structured and how you can investigate these things. They're on our AE Shared Calendar in Google if you're interested! 

hope that helps :)

**Comment by andaleliz** [comment]
I got curious and looked into the below reports, for the last week. Navigation events to profile via the personalized menu are slightly higher compared to from My VA (44k vs 39k), and there doesn't appear to be a significant 3rd source we should take into consideration.

- [Report](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184624291/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22RE%22,%22Dashboard%20-%20Navigation%20-%20View%20Link%20-%20View%20Your%20Profile%22,0%5D%5D/) for `Dashboard - Navigation - View Link - View Your Profile`
- [Report](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184624291/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22RE%22,%22Navigation%20-%20User%20-%20Profile%22,0%5D%5D) for events for `Navigation - User - Profile`, along w/ the page they took place on (interesting My VA is a top one) 
- [Navigation summary](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p184624291/explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath:~2Fprofile~2F&_r.tabId=navigationsummary/) for entrance to the profile

**Comment by mtcA6** [comment]
@andaleliz could you share a different link? I can't access this one
>I worked [through some possibilities](https://www.sketch.com/s/113f0ee6-e77d-4b1b-bf02-af27580931fe/p/F06226AA-DBC6-482C-A474-E9585FDF7178/canvas) for how it could be organized in the menu. I'm leaning toward keeping it as simple as possible without changing anything except adding the two links, so that we're minimizing variables in our experiment

**Comment by andaleliz** [comment]
@mtcA6 can you try again? Just updated the settings.

**Comment by andaleliz** [comment]
@Samara-Strauss Pam, Angela and I agree that the following options would be good to bring to design intent to get IA input:
![image.png](https://images.zenhubusercontent.com/5d9def68b6de6d00018d50f2/fa9dd807-0c50-42d9-8695-bbc8fe998c33)

The rationale for each being:
- Option 1 is simple, separating sign out from links to thinks. This introduces the minimal amount of variables to the experiment
- Option 2 groups things that are dashboard-like and can change every time you log in, with things that are managed by users and more tool-like
- Option 3 groups things that are benefit specific and broader personal things


Thoughts? Once we're aligned, I'll make the desktop mock-ups and flow, and close this out.

**Comment by Samara-Strauss** [comment]
Options 1 & 2 make sense to me; even with the rationale, the grouping in option 7 doesn't totally make sense to me. But if you feel strongly about it, then I'm ok bringing all three to design intent. Thanks for the amazingly fast turn-around on this 😄!

**Comment by andaleliz** [comment]
I don't feel strongly about option 7, so I'm fine to nix it.  And you're welcome @Samara-Strauss, I've been itching to do something like this coming out of the logged-in research and am pumped for something we can do quickly. Pending Public Websites :) 

I created desktop versions of both, and a simple flow using one of the desktop versions to provide clarity about where these will link. I think we're ready to schedule design intent!  Everything is on [this page ](https://www.sketch.com/s/113f0ee6-e77d-4b1b-bf02-af27580931fe/p/F06226AA-DBC6-482C-A474-E9585FDF7178/canvas) in our Sketch file.

I feel ready to go into design intent; I'll basically talk through my rationale for these options, which is outlined in the comments above. 

@mtcA6 I can add links to the artifacts in the design intent ticket. Lmk when it's ready.  Thanks!

**Comment by mtcA6** [comment]
@andaleliz #62194 is ready for links whenever. Let me know when you're done linking the artifacts and I can schedule the design intent call for us :)

**Comment by andaleliz** [comment]
@mtcA6 oh thank you - I didn't realize there wasn't a separate ticket for design intent outside of the main collab cycle ticket.  I've added the links in the design intent section (I think in the right place 😬 ).
