### ISSUE TITLE
[Documentation] Determine if va.gov SharePoint can be utilized for sharing of training videos [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#6221]
## User Story or Problem Statement
As a VAMC and associated team member, I need a centralized repository to share across teams and in the va.gov environment, but also protected via permissions for only techs and team members to access if required.

## Goal
_Document and archive templates and training for VAMC deployment_

## Objectives or Key Results this is meant to further
- _Training and template how to documentation_

## Resources - Tools - Documentation
_Va.gov network access only_

## Tasks
_The following tasks must be complete_
- [ ] Create a folder in VAMC SharePoint for Documentation and Training
- [ ] Confirm that CMS team and VAMC Team and all Stakeholders have access to folders
- [ ] Assure there is limited or secure access or permissions based on VAMC Stakeholder provisioning/governance.

## Acceptance
_The following must be complete to provide acceptance that this issue is complete_
* Create a folder in VAMC SharePoint for Documentation and Training
* Confirm that CMS team and VAMC Team and all Stakeholders have access to folders
* Assure there is limited or secure access or permissions based on VAMC Stakeholder provisioning/governance.
