### ISSUE TITLE
[FE] - Create upcoming appointments component

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#62227]
## Description
Create a shared component to be used for both applications that lists upcoming appointments. Take note of the subtle differences needed for each application.

## Release 2 Wireframes
[Wireframes](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/868762F3-8E8F-4E23-B0DA-34C1783F0A03/canvas)

## Tasks
- [x] Create shared upcoming appointments component
- [x] Add component to pages
- [x] Create mock data for component
- [x] Create or update unit tests
- [x] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/62227?planning-poker) with Zenhub @wullaski

**Comment by kellysmith1008** [comment]
@wullaski We've drafted a copy of all our loading states and placed our recommendations for future loading states [in this document](https://docs.google.com/document/d/1meFuLT4AsQpQ70oWIl-VUjlxM0O4R6V_EOIQSD_HIUc/edit). Please let me or @ytsaoca know if you need anything else from us!

**Comment by loripusey** [comment]
@brianseek can you validate & close please? For this Priority, we will also have some testing tickets because of its size, so if you want to just close it that's fine.
