### ISSUE TITLE
[CHIP] Update initateCheckIn to fetch upcoming appointments

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#62229]
## Description
For the new upcoming appointments listing, we need to show today(from 12:00a.m.) and future appointments. Update the initiateCheckIn endpoint to fetch appointments in a span. Check in with Ben on how many days into the future we are needing to fetch. 

The appointments for today are passed in from veTEXT, so we will need to determine the best way to fetch the additional appointments. Will veTEXT make a bigger fetch, or will we fetch and add to the list?

We will display all of the Veteran's VA appointments (regardless of appointment type) that are for today and in the future.

## Tasks
- [ ] Update initiateCheckIn with new data 
- [ ] Create or update tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
no longer need
