### ISSUE TITLE
[CHIP] Update refreshPreCheckIn to fetch upcoming appointments

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#62228]
## Description
For the new upcoming appointments listing, we need to show today(from 12:00a.m.) and future appointments. Update the refreshPreCheckIn endpoint to fetch appointments in a span. Check in with Ben on how many days into the future we are needing to fetch. 

We still need to know the IEN(s) of the appointments that initiatePreCheckIn was called on, so those will need to be identified somehow. We will still throw an error if those appointments are invalid.

We will display all of the Veteran's VA appointments (regardless of appointment type) that are for today and in the future.

## Tasks
- [ ] Update refreshPreCheckIn with new data 
- [ ] Create or update tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by benbrasso-agile6** [comment]
> Also what happened to the month navigation concept?

"Month navigation concept" is assigned to VAOS/Appointments team. We are supposed to follow them based on convo with Kristen McConnell. I do not know a timeline. We would want to message Jeff and Peter in #appointments-team to see where their design is. We don't need to wait for their engineering work. 

> we need to determine how many appointments in the future VAOS and the mobile app we need to fetch and display (what does VAOS & mobile app) do; can you help figure this out?

I can take this if you'd like. From there, I'm sure our engineers can make our own decision. E.g., if VAOS says they show up to 5 years of appts, then we don't necessarily need to follow that. But, we can make a decision together.

**Comment by loripusey** [comment]
Thanks for the reminder on the month navigation. 

There was a discussion amongst the engineers about whether we are "allowed" to show all appointments using a LoROTA model; they have a spike to discuss with Stephen and investigate the effort to get all appointment (right now we only collect appointments for a single station), but it may change how we handle displaying appointments; @benbrasso-agile6 let's discuss when you are free

**Comment by benbrasso-agile6** [comment]
Added in mobile app above

**Comment by loripusey** [comment]
no longer need
