### ISSUE TITLE
BE | Profile | Rated Disabilities | Discovery: VA Profile Rated Disabiilites API

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#62223]
## Background
VA Profile offers a rated disabilities API.  Determine if the API can replace current EVSS functionality for all VFS teams that use it.

## Tasks
- [x] Review API with:
  - Jerek Shoemaker (#benefits-ce-mgmt_tools)
  - Aurora Hampton (#benefits-ce-disability_exp_1)
- [x] Document findings and estimate of work needed

## Acceptance Criteria
- [x] Review with PMs.
