### ISSUE TITLE
Left Nav Discovery

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#6223]
## Problem Statement
How might we become familiar with the VAMC Left Nav enhancement project ?

## Goal
Readiness for development on VAMC Left Nav
---
## Tasks
- [ ] Review [#1874]( https://github.com/department-of-veterans-affairs/va.gov-team/issues/1874) and associated code
- [ ] Review changes available on [staging](https://staging.va.gov/pittsburgh-health-care/) compared to [prod](https://www.va.gov/pittsburgh-health-care/)
- [ ] Review [Product repo]( https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/global/header-footer-and-navigation/page-nav)
- [ ] Review [Usability research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/global/left-nav/research-findings.md)

## Acceptance Criteria
- [ ] Feel prepared to begin pair-coding
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
