### ISSUE TITLE
Draft revised experience standards

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#62236]
## User Story
As a Governance team member, I want to rewrite the VA.gov Experience Standards according to the taxonomy structure so that we can eliminate overly narrow or broad standards and even them out.

As a Governance team member, I want to rewrite the VA.gov Experience Standards so that they will roll up in Domo in a way that is helpful for ourselves and our OCTO-DE leadership.

Assignee: @shiragoodman @sterkenburgsara @it-harrison @allison0034 @CherylEvans @erinrwhite @briandeconinck 

## Description
In ticket #60595 we reorganized the 91 existing experience standards through a series of team affinity mapping workshops. The goal was to redefine new categories for our standards that focus on the end-user experience, rather than reflecting silo-ed practice areas. 

Now that those categories have been established, this ticket will iterate on the work done in the previous ticket. Groups of 2-3 members each will take on auditing the experience standards in the category(ies) they are assigned and re-writing them as needed to eliminate any overly narrow and/or overly broad existing standards. They should also write a 1-2 sentence description for the category itself. 

- [x] Findability/Hierarchy - Sara & Ian & Erin
- [x] Comprehension - Cheryl & Brian & Ian
- [x] Consistency/Predictability - Allison & Shira
- [x] Usability - Allison & Brian
- [ ] ~~Compatibility - Brian & Ian~~ Note: team decided to remove the Compatibility category since compatibility issues were also findability, comprehension, consistency, etc. issues.
- [x] Communication/Credibility - Allison & Cheryl
- [x] Efficiency/Simplicity - Shira & Sara

## Impacted Artifacts
* [Experience Standards Affinity Map](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687405248108/d062ed36c1e5191571492e64cfe61ac87c02c9fc)

## Tasks
- [x] Set up times to work together or async with your category buddy
- [x] Visit the [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687405248108/d062ed36c1e5191571492e64cfe61ac87c02c9fc) & find the area near the bottom with a template for your category. Please work through the template & reach out to @shiragoodman with any questions
    - Consider the "process problems" category that was defined by the team earlier and see if those issues need to be addressed by separate standards in your category
    - Consider the count for each experience standard: how many times was it used? Higher counts should receive more of your time and attention. Lower counts should be candidates for merging into broader standards.
    - Sync with assignees on other categories as needed
- [x] Have team sync and discuss decisions with the group for feedback
   - [x] 8/1
   - [x] 8/8
   - [x] 8/11

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] New experience standard categories have been formed with names & descriptions
- [x] A draft of new standards has been created for each category.

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
Set up a meetings with Brian and Cheryl

**Comment by sterkenburgsara** [comment]
Update: findability/hierarchy buddies @it-harrison and @erinrwhite met today. We are mostly done but still need to draft new standards for ones we marked as "needing to be merged or significantly re-written" - we'll continue that process async and communicate via Slack.

**Comment by sterkenburgsara** [comment]
Update: synced with assigned buddy for efficiency category @shiragoodman and completed our tasks.

**Comment by CherylEvans** [comment]
Met with @it-harrison  and @briandeconinck for the Comprehension category.

**Comment by shiragoodman** [comment]
WRT the process standards that were identified, new ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/62946 has been created. We will address this at a later date. @humancompanion-usds has agreed that the process standards should not live with the experience standards

**Comment by shiragoodman** [comment]
we have come up with our preliminary categories and new standards. We will continue refining the content and definitions for these standards in other tickets.
