### ISSUE TITLE
Design | Profile | Notification settings | Review content in expandable alert

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#62240]
## Background

@adamwhitlock1 brought up a great point about the expandable alert and we need to review this in content office hours:

>Lets say there are several email notifications that a user is ineligible to receive due to their lack of contact email on file. One notification is a ‘Your health care’, another is part of the ‘Payments’ group, and several more are part of ‘Board of Veterans Appeals’ (hypothetically in the future)
Would we expect those unavailable notifications to be chunked out by group in the expandable alert list of notifications?

<img width="272" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/55992116/a933b573-9c0b-4347-99b5-72afafe93a7a">

## Tasks
- [x] Review in content office hours
- [x] Update any Sketch files
- [x] Let team know outcome

**Comment by andaleliz** [comment]
@mtcA6 fyi I have added this ticket for the current sprint starting today (July 19)

**Comment by andaleliz** [comment]
@adamwhitlock1, Danielle and I decided it's best NOT to include the headings, so it can just be a list of the notifications people would get if they added the channel.  If we can keep them in the same order they'd appear in the UI, that feels logical to me.  If not, then alpha order is OK.

We made one change, which can happen anytime - `Appointment reminders` should now be `Health appointment reminders` to align with how we talk about it elsewhere on the site, and provide more context when it's in that list.  

This is ready for FE work! 

FYI @mtcA6

**Comment by mtcA6** [comment]
@andaleliz  want to confirm, are the below the specific locations in the sketch file?   
[desktop](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/v/yAkqz8/p/C9FF1DE2-F54A-4E1F-9847-4A2799011AB8/canvas?posX=-2147.1620092579446&posY=-7001.187238283158&zoom=0.3769318461418152) and [mobile](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/v/yAkqz8/p/B5792AF8-87F2-496D-AE7A-DAD1448A6018/canvas?posX=-2300.96991687576&posY=-6847.345024081017&zoom=0.7735158205032349)

**Comment by andaleliz** [comment]
The update to the appointment reminders text label is across any screen with the health appt reminder on it; there were no changes to the expandable alert for this ticket.

**Comment by mtcA6** [comment]
> We made one change, which can happen anytime - `Appointment reminders` should now be `Health appointment reminders` to align with how we talk about it elsewhere on the site, and provide more context when it's in that list.
> 
> This is ready for FE work!
> 
> FYI @mtcA6


@andaleliz Could you be a bit more specific and provide screenshots detailing what you want changed? In staging right now I see Appointment reminders AND VA Appointment reminders. I want to make sure we're talking about the same things.

What's the difference between a VA Appointment Reminder and a Health appointment reminder?

Your mock:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/6dbc2170-0e02-4b50-a1e4-224eaeba237f)

VS staging:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/30282c76-5fa9-4168-acdc-2fe18852c5ca)

**Comment by andaleliz** [comment]
@mtcA6 Hmmm, I don't know how else to be more specific in a screenshot other than what I've already provided - currently, the text notification has a label that says "Appointment reminders" and it needs to be updated to say "Health appointment reminders"

It looks like staging is showing the MHV notifications coming from VA profile that are still TBD and not released.  Eventually "VA appointment reminders" and "Appointment reminders" should be under one notification item with two channel options,  email and text, as shown in [this mock-up](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/vRLvAZ1).

Does that answer your question?
