### ISSUE TITLE
Review claim status intro page and suggest content edits

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#62248]
## Value Proposition

**As a veteran** landing on the CST intro page, **I want** the language on the page to accurately reflect what the CST can show me and not mislead me about the types of information I'm likely to find if I log in to check the status of various claim types and applications **so that** I don't log in expecting to find information about something that just isn't there. 

## Background

Our team has done a lot of work to create an app map by generating various UI states in staging. It is clear that there are simply not UI states for some of the claim and application types mentioned on the [Intro page](https://www.va.gov/claim-or-appeal-status/). We need to review the intro page and identify any false promises being made to users. We then need to submit to Sitewide Content team an artifact that clarifies what's incorrect on the page. 

## Tasks

- [ ] Review CST Intro page and flag all claim/application types that do not appear to have UI states in CST
- [ ] Create a document that contains the existing language and then annotate the document to highlight incorrect information
- [ ] Submit document to Sitewide Content team

**Comment by skylerschain** [comment]
@laurwill I wonder if you might be able to help us out with this. 

We have identified that at least one of the things listed here in "What types of claims, decision reviews, and appeals can I check in this tool?" is _not_ in fact available. 

<img width="842" alt="Screenshot 2023-08-02 at 2 20 34 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/dca44483-0cc0-41b2-8e93-4a8293f2f586">

I'm wondering if your team might have a paper trail for this page. We are trying to figure out if all this information is still accurate, and there's no record of all the claim types that do in fact show up in CST. 

Would your team be able to help us verify this list and update it to make sure it's accurate?

**Comment by laurwill** [comment]
Hi @skylerschain , 
The list of claim types has been live since this page was migrated into the modernized VA.gov back in 2019 — I'll see if I  can do a bit of digging about the initial content development.

So are you saying that there's nothing in the data you're receiving that identifies the type of benefit a claim is for?

**Comment by skylerschain** [comment]
Well we do have this list from the BGS backend service, but it's a little hard to tell if these terms match what is on the page. 

Administrative Review
Appeal
Appeal for Birth Defects
Appeal for Spina Bifida
Authorization Review
Automobile Adaptive Equipment
Automobile Allowance
Automotive Adaptive Equipment
Award Audit
Birth Defects
Burial
Camp Lejeune Verification
Character of Discharge LGY
Character of Discharge Review
Clothing Allowance
Comp and Pen
Compensation
Compensation and Pension
Compensation Pension
Correspondence
D2D Pre-Discharge Excluded
Death
Dental
Dependency
Dependency Verification - 0538
Discharge for Disability LGY
Due Process
Duplicate Payments
eBenefits BDD
eBenefits Pre-Discharge Excluded
eBenefits Quick Start
Economic Recovery Payment - Entitlement Review
EDU Eligibility Rating
Education
efolder Creation
Eligibility Determination
Fiduciary
Fiduciary Adjustment
Filipino Equity Compensation
Freedom of Information Act / Privacy Act Request
Fugitive Felon Review
Hospitalization Adjustment
Hospitalization Eligibility Review
ID Card
Incarceration Adjustment
Income Verification
Incomplete Application
Insurance
Insurance Eligibility
IVM Matching
Loan Guaranty Eligibility
Medal of Honor Verification
Military Pay in Lieu of Compensation
Month of Death Entitlement Review
NICS Relief Request
Outpatient Treatment Eligibility
Paid and Due
Pay Grade Verification
Pension
PMC - Incomplete Application
PMC Duplicate Payments
PMC Removal of Dependent
Pre-Discharge Compensation
Predetermination
Preference Certificate
Prison Match Review
Quality Control
Quick Pay
Rating Review
Regulatory or Procedural Review
Remand with BVA Grant
Removal of Dependent
Renouncement of Benefits
REPS
Resumption of Compensation
Retired Pay Adjustment
Retired Pay Waiver or Election
Return to Active Duty
Review
Review Due to Hospitalization
Social Security Request
Special Adaptive Housing/Special HSG Adaptation
Special Correspondence
Special Home Adaptation
Specially Adapted Housing
Spina Bifida
Vocational Rehabilitation and Employment
VOW
Waiver Request
Work Item
Work Study
Workers Compensation
Your Whereabouts are Unknown

**Comment by laurwill** [comment]
Hi @skylerschain , unfortunately we don't have the information you're looking for about what types of claims appear in the tool. But we think Julie Strothman may already be looking into this same issue, if you want to connect with her.

When you confirm which claim types are included, we can update the static page with that information.

**Comment by jstrothman** [comment]
@skylerschain @laurwill It's true, Laura, that I'm interested in confirming which types of claims appear in the tool, but I don't have ideas about whom to check with next.

**Comment by laurwill** [comment]
Hi @skylerschain @jstrothman , this question came up again in our work with the Add or change dependents form. Were you ever able to confirm exactly which types of claims appear in the CST? cc @katherine-fung

**Comment by DanielleThierryUSDSVA** [comment]
Hi all. @jstrothman confirmed that we should remove VA health care from this list. We've updated and published, removing health care and updating the intro to note that you can check the status of "certain claims, decision reviews, and appeals." 

cc @laurwill @katherine-fung

**Comment by jacobworrell** [comment]
@laurwill We are now able to track the claim data types coming through in CST in DataDog, so we can do a dedicated analysis of the reality and make some solid recs based on that. I've updated the ticket language to be more targeted and focused on the team's likely activities.

**Comment by jacobworrell** [comment]
@laurwill @DanielleThierryUSDSVA Thank you for your patience waiting for us to investigate this issue thoroughly. The results are in, we've identified the specific claim types that show up in CST and have content edit suggestions in light of those findings. We've run these content suggestions by @jstrothman and VBA SMEs and they approve these suggestions. 

Attached is a word doc that hopefully makes clear what we're proposing as changes to the CST landing page. Please let me know if I should open a separate content request ticket for this (and if that's the case, please point me to the best template for this). 

[Proposed Edits for CST Intro Page - VBA approved.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/15028876/Proposed.Edits.for.CST.Intro.Page.-.VBA.approved.docx)

**Comment by laurwill** [comment]
Hi @jacobworrell , I think the doc you attached is corrupted, could you attach again?
<img width="800" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/104158104/c66d6558-6b8c-4787-96ef-ae1eb3c27167">

**Comment by laurwill** [comment]
Thanks! I made 2 small edits to the list intros in the doc — the first list is now "types of benefits" and the second list is now "types of requests."

Here's a preview in the draft page:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/104158104/eda85f46-0f93-4402-91d4-736668e755e1)

Which VBA SME are you working with? These are pretty minor edits I made, but we usually send a preview for approval before publishing.

**Comment by jacobworrell** [comment]
I'm working with Andrew Gray @laurwill I think those edits look great and doubt we'll get any pushback on them.

**Comment by laurwill** [comment]
Hi @jacobworrell , great, since SME saw the substantive changes and my edits were minor, I went ahead and published. Let us know if you need anything else related to this page!

**Comment by laurwill** [comment]
Hi again @jacobworrell @jstrothman , following up on a recent slack convo about the VR&E form — is there a process to notify product teams that we've removed their forms from the list of things appearing in the CST? Is that something your team would do? I'm thinking that other teams like education, etc, whose forms got removed may still be linking Veterans to the CST to check status.

**Comment by jstrothman** [comment]
@laurwill Thank you for mentioning this--I'll reach out to the teams and suggest they check their confirmation pages and any email notifications for the need to remove links.

**Comment by laurwill** [comment]
Hi again @jacobworrell , we're auditing our static pages for links to the CST that we'll need to remove to align with the updated list, and I had a follow-up question: the education and life insurance hub pages link to the CST, but the text specifies "to track the status of your benefits **appeal**." 

Did VBA SMEs confirm whether the updated list applies only to initial claims/requests for the listed types? Could appeals and decision reviews for life insurance, education, or other benefit types appear in the CST?

**Comment by laurwill** [comment]
Hi @jacobworrell @jstrothman , just checking in on this last question — do decision reviews and appeals for a wider range of VA benefits appear in the CST? Or does the tool only show decision reviews and appeals related to the initial claim types in the updated list?

**Comment by jacobworrell** [comment]
@jerekshoe do we know what type of appeals and decision review information CaseFlow sends back?

**Comment by jerekshoe** [comment]
Caseflow sends us Supplemental Claims, Higher Level Reviews, Appeals and Legacy Appeals. It’s difficult to determine more granularly what types are returned beyond that with the information available to us currently. If we wanted to get more insight into this then we would want to set up tracking in DataDog similar to what we did for benefits claims

**Comment by laurwill** [comment]
@jerekshoe what's the difference between Appeals and Legacy Appeals? Does Appeals = Board Appeals?

I think it would be worthwhile to set up whatever tracking we need to get this more granular information, so that we can avoid directing Veterans to the claim status tool for things that don't show up there. 

We also can't be sure that our page content is accurate if we can't answer this question — the page currently says we get decision reviews and appeals only for the types of initial claims that show up in the tool. If we actually get decision reviews and appeals for all types of claims, we should change this asap.

**Comment by laurwill** [comment]
Hi @jerekshoe @jacobworrell checking to see if we can confirm exactly what types of claims, decision reviews, and appeals appear in CST now — we have an open ticket to update static pages to only send people to the tool when appropriate. Thank you!

**Comment by kirkacrawford-VA** [comment]
@jstrothman @amylai-va This is another issue tagged for BMT2 from the old team's backlog that is currently sitting in 'no status' for us. Is there a need to revisit this work? I've moved it into BMT2's backlog.

**Comment by amylai-va** [comment]
@kirkacrawford-VA We update the [CST intro page](https://www.va.gov/claim-or-appeal-status/) last year to clarify what types of claims, decision reviews, and appeals statuses claimants can find in CST. 

@jstrothman @DanielleThierryUSDSVA are you aware of any open items that still need to be addressed? I'm guessing this ticket became "orphaned" during the zenhub -> github migration and can probably be closed.
