### ISSUE TITLE
[ENGINEER-CMS] Create CRON job to pull down VAMC-update data from Prod into devshop and determine benefits and next steps

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#6225]
## User Story or Problem Statement
As a VAMC Engineer,  I need to know the viability and benefits to creating a daily CRON job to pull down the instance/"MASTER" data from production into Devshop on a daily basis, so I can provide the latest version of all updates, content, pages and will there be benefit if publishing will have to be completed or can this also be automated?

## Goal
_Continued Optimization_

## Objectives or Key Results this is meant to further
- _TBD_

## Resources - Tools - Documentation
_VA.GOV Network access only_
[Devshop](DevShop: devshop.cms.va.gov)

## Tasks
_The following tasks have been requested for consideration:
- [ ] Creation CRON (Scheduled Command) to pull latest data from production to devshop
- [ ] Confirm if this provides benefit dependent on how often pages are published and LOE to publish all pages for all systems.
- [ ] Determine if a CRON can be created to publish all content for VISN 4 in Devshop

## Acceptance Criteria
_Validate outcome of pushing content to existing page_
* Creation CRON (Scheduled Command) to pull latest data from production to devshop
* Present findings PRO and CON of CRON and if CRON can be extended to publish.
* If CRON cannot publish, determine LOE to publish daily
