### ISSUE TITLE
[Design] My VA health: Unread messages design work

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#62255]
## Background
We previously did some work to rethink the unread messages alert in the Health section on My VA ([54813](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54813), [sketch](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/nQmWy1l)). However after talking with the MHV on VA.gov team and seeing what mobile app is doing in this space we want to rethink this.

## Tasks
- [x] Work with MHV on VA.gov designer to come up with a design approach
- [x] Present to POs on both teams

## Acceptance Criteria
- [x] New designs/ideas
- [x] Shared with POs
