### ISSUE TITLE
DI documentation review from perspective of newbie

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#62262]
## Purpose
Let's review the VFS member’s experience as a complete newbie.  Try to step through finding, understanding, and applying the documentation found on Platform.

[Strategy](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2625994753/Design+Intent+research+Initiative+-+discussion+notes?focusedCommentId=2625798167#Bryan%E2%80%99s-suggestion-on-SDT-approach%2C-at-conclusion-of-meeting%3A)

## Tasks
- [x] The team should review the existing (Platform) documentation.  Each member should look for and document:
- pain points
- methods to simplify
- ways to improve absorption
- ways to improve buy in 

## Acceptance Criteria
- The above factors are documented
    - [x] [Bryan](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2725937272/Design+Intent+documentation+analysis+-+Bryan)
    - [x] [Dan](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2726330379/Design+Intent+documentation+analysis+-+Dan)
    - [x] [Taylor](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2726330369/Design+Intent+documentation+analysis+-+Taylor)
