### ISSUE TITLE
Update Product Guide for making VAMC fields optional

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#62260]
## Issue Description
As a Contact Center Support Team, I need an updated version of the Product Guide when there are changes to the veteran facing screens so that I can support them with accurate information.
---
## Tasks
- [ ] Update the Product Guide for VAMC fields

## Acceptance Criteria
- [ ] Product Guide is upto date with VAMC fields being optional
- [ ] The information is shared with Contact Center team
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by christinec-fftc** [comment]
[Product Guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez/product/526ez%20Product%20Guide) has been updated to v2.1

**Comment by christinec-fftc** [comment]
Related [slack thread](https://dsva.slack.com/archives/CNCEXNXK4/p1689270240830839)

**Comment by christinec-fftc** [comment]
We found out additional changes will be needed on the back end and more discovery work is needed. Rolled back the product guide changes for now. Will pick this back up when [#62546](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/62546) is completed
