### ISSUE TITLE
Bring in learnings from Forms research about DI

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#62269]
## Purpose
We've heard related things during our Forms research.  Let's bring those in for our notes/consideration.

## Tasks
- [x] Create a [mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1693445873201/029ccb82a3dcaadc2fa1bbe3555f4f4fb62947e1?sender=u9ea6bd3ca12795949b606150) to capture these
- [x] Locate relevant notes in Forms research
- [x] Pull notes into [common workspace](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2753200165/Research+notes+about+DI) for DI

## Acceptance Criteria
- [x] Mural is created to capture DI data
- [x] Mural is placed in common workspace for DI

**Comment by tayism** [comment]
Ran out of time on this last minute ticket pickup. Will have to close at the start of the next sprint
