### ISSUE TITLE
Add Workflow to 686: "Add a Spouse" - Part 3

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#6226]
## Story
As a veteran, I need to fill out any previous marriages I have, so I can add a spouse to an award via 686c.

## Considerations
- [Mockup here](https://xd.adobe.com/view/ffffe536-2ba5-47c6-4c4b-ac1679179973-89ce/screen/d7efe7ac-c07e-49d4-a73e-3f21e85005f5/Apply-Dependents-Former-Marriages-2)
- This ticket includes page 6 and 7 of the workflow to add a spouse. There are two arrays of data in this section, one to collect a veteran's former spouse names (VFSN) and one to enter information related to a veteran's former marriage information (VFMI)
- This will have the Evidence Uploader as a final step 
  - For awareness, this will be required for certain selections, dependent on dropdown for address (**anything other than US address will make this required**) and/or certain **marriage  types other than ceremonial**

## Tasks
- [ ] Add pages 6 and 7 of the spouse workflow to the codebase for the 686.
- [x] Add and/or remove the necessary schema at the workflow level and ensure there are no validation errors.

## Acceptance Criteria
- [x] A PR has been requested and completed for `vets-website`

**Comment by micahchiang** [comment]
We can discuss at planning, but this work is pretty much a copy and paste job of pages 4&5 with some renaming.

**Comment by micahchiang** [comment]
PR merged.
