### ISSUE TITLE
Create example User Journey for DI user

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#62263]
## Purpose
Let's create a user journey for a team (PM & Designer for sure) engaging w/ DI for first time

## Tasks
- [x] create an [end to end journey](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1693578012474/7436e75dad944614e4622212b8d3403d72b8d86f?sender=u311209e67c8c21a1b37a8167) of a team's experience with DI (Both for current state and proposed state?)
- [x] Ensure that it references:
  - [x] pain points
  - [x] methods to simplify
  - [x] ways to improve absorption
  - [x] ways to improve buy in 

## Acceptance Criteria
- [x] User Journey(s) created

**Comment by gopixelsgo** [comment]
Mural in progress [here] for current state (https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1693578012474/7436e75dad944614e4622212b8d3403d72b8d86f?sender=u311209e67c8c21a1b37a8167)
