### ISSUE TITLE
Forms Library review & submit page accordion error icon removal

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#62278]
## Value Statement
**_As a_** form library user
**_I want to_** remove the extra alert icon within the review & submit page header
**_So that_** it doesn't distract attention away from the alert

## Background Context

Recently, the component library added an icon to all background-only alerts, so the review & submit page alert that appears when there is a form error duplicates the alert icon in the header. [Link to Slack conversation about removing the icon](https://dsva.slack.com/archives/C01DBGX4P45/p1689792491837199?thread_ts=1689790196.244599&cid=C01DBGX4P45)

![accordion header with alert icon (black) and issues for review text with a matching alert below it which also has an alert icon (red) with issues for review needs to be updated alert text](https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/b9563216-1347-4921-a4a9-a169b4fb0514)

## Tasks
- [ ] Remove icon from header
- [ ] Update unit tests

## Acceptance Criteria
- [ ] All tasks complete
- [ ] All tests passing

**Comment by micahchiang** [comment]
@Mottie - can you provide a little more clarity around this:
1. Which icon are you talking about, the black exclamation mark or the red one? 
2. Can you drop a link to the app code in vets-website for where this is happening?

**Comment by Mottie** [comment]
It's the black exclamation mark in the header. The red one is rendered by a va-alert, which we want to keep. At least that's what my understanding was [what Matt Dingee said](https://dsva.slack.com/archives/C01DBGX4P45/p1689790196244599).

Code source: https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/review/ReviewCollapsibleChapter.jsx#L415-L420

**Comment by caw310** [comment]
Stretch item for sprint 35

**Comment by Andrew565** [comment]
@Mottie PR up if you could please review: https://github.com/department-of-veterans-affairs/vets-website/pull/25465
