### ISSUE TITLE
686c | Develop process for reporting 686c metrics to VA stakeholders

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#62275]
## Issue Description

In https://github.com/department-of-veterans-affairs/va.gov-team/issues/57955 I set up metrics for successful and failed 686c submissions. There are two VA stakeholders who would like a weekly report, probably delivered Tuesday mornings, before the 2PM ET IPT meeting.

Brandi Traylor just wants to know the number of successful and failed submission in the past week. That will be very easy to produce. See https://docs.google.com/document/d/1voc1LaQQhWU3Ur9ULNog0qy4i74MGKyhfCTAcl26K34/edit. 

Krystal Connor (who actually processes 686c claims) would like a report showing all failed submissions, and the veteran associated with each, so she can see whether they're catching all these cases. To tie a veteran to a failed submission, we may be able to rely on the saved_claim_id, ICN, or if necessary, SSN. The saved_claim_id and ICN are present in our logs, and neither is PII. I explained to Krystal that we embed the saved_claim_id within the filename of 686c PDFs uploaded to the veteran's eFolder. When I asked Krystal whether saved_claim_id or ICN would allow her to locate veterans in her system, she said, for now, we can send both and she'll let us know if that works. If that doesn't work, we can think about sending SSNs. IIRC, the SSN is present in the `saved_claim`'s encrypted `form` field. Because this is PII, we would have to figure out how to produce these reports and send them to Krystal, compliantly.  

To summarize, the goal of this ticket is to figure out how to put together a report that works for Krystal. We can start sending the reports that Brandi wants, immediately.  (But see https://github.com/department-of-veterans-affairs/va.gov-team/issues/62270, there may be some issues with our reports).

---
## Tasks
- [ ] Produce a report containing ICNs and saved_claim_ids and see if that works for Krystal
- [ ] If not, figure out whether to, or how to, put together and send a report containing SSNs.

## Definition of Ready
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/62270 completed.

## Definition of Done
- [ ] We know how to put together a report that will work for Krystal.
- [ ] Or, in the alternative, we can definitively say that putting together such a report is not possible, or not practicable.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by data-doge** [comment]
Hey @steele-lm ! Here's the other ticket we talked about.

**Comment by steele-lm** [comment]
Dashboard has been set up, but additional discovery needed to determine how to automate sending report.

**Comment by steele-lm** [comment]
The automated send feature is not available in the VA instance of DataDog -- it appears to be an add-on feature ($$). Team is researching alternatives.

**Comment by steele-lm** [comment]
Thomas pulled all available data and provided to Emily to share with VBA.
