### ISSUE TITLE
Support Bot Proposed Changes Document

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#62271]
## Description 
This ticket covers the creation of a document for proposed Support Bot changes. These changes are a result of gathered feedback and operational efficiencies needed to continue enhancing service. 

---

## Definition of Done
Tasks below are complete.

---

## Tasks 

- [ ] Break out features we want to create or update
- [ ] Identify how those features will impact others work and list out implications of these changes on other teams
- [ ] Scope out how long it would take us to implement said changes and identify a plan for execution (i.e. over next however many sprints, how many points is the lift, etc.)

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by jknipes** [comment]
One feature we definitely want:
Topic - PR Review should trigger Bot to suggest [this doc](https://depo-platform-documentation.scrollhelp.site/developer-docs/pull-request-best-practices)

**Comment by alyssagallion** [comment]
Closing. Document here: https://vfs.atlassian.net/wiki/spaces/~7120206d71ac1d51d9451b8aa7b67d7c4b7101/pages/2734587939/Support+Bot+Update+Research+findings
