### ISSUE TITLE
Create wireframe for how to decrease No's to filing for travel

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#62272]
## Description 

Over half of Veterans are answering No that they don't want to file for travel reimbursement. 

[Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1689787982265009?thread_ts=1687781824.917519&cid=C022AC2STBM)

How can we decrease this number? 

There are a variety of reasons why Veterans are saying no: 

"I don't think it's clear to all.  I just mean self-identification of being eligible for BT is likely a subset of those answering NO for those answering it as "I don't want to submit because I've been rejected before for eligibility reasons".  New veterans who aren't clear on eligibility standards existing would not know to self identify.  Certainly some are answering NO because they don't want to at that time, as in are checking in "late" and don't want to make themselves checked in even later."

## Tasks

- [ ] Read through the background and potential solutions in the slack thread
- [ ] Review screenshots from VetLink (Ben has them) on how they handled BT requests
- [ ] Pick one or two solutions to create wireframes
- [ ] Get feedback from CIE team
- [ ] Get feedback from anyone else that is needed, platform design, content, Shawn Adams, etc. 
- [ ] Finalize wireframes

## AC

- [ ] Wireframes have been reviewed 
- [ ] Wireframes finalized 
- [ ] Create f/u ticket for FE. Work with Lori on prioritization of where it goes.

**Comment by benbrasso-agile6** [comment]
Added you @cgednalske so I won't forget

**Comment by benbrasso-agile6** [comment]
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1690814320736/04f9a4290906730ed48ca137b9da3c73ecf8c811?sender=u37bb983bd3fc3cc00c7d3286

https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/697DF8C0-2DF6-4A66-B875-E0594FD8930F/canvas

Will chat with Laura tomorrow and get her feedback

**Comment by benbrasso-agile6** [comment]
Ticket for Laura https://github.com/department-of-veterans-affairs/va.gov-team/issues/63061

**Comment by benbrasso-agile6** [comment]
Think Laura is still working on this one. But, looks simple enough for when she's done.

**Comment by benbrasso-agile6** [comment]
Think I have enough. Will make updates.

**Comment by loripusey** [comment]
So, this is just a content change, correct? If so, I think it is its own release and perhaps we can do it while we are doing UCI release 2.1

**Comment by benbrasso-agile6** [comment]
Yes, sounds good. Moving it into 2.1 in sketch now.

**Comment by benbrasso-agile6** [comment]
This is completed @loripusey 

https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/v/4LDbV3/p/66A06E6C-F76F-4580-8709-DB36B56662D5/canvas/#Version

I did not update the release notes in the epic

**Comment by loripusey** [comment]
I created an epic to address this work; perhaps we can fit it in when we get to UCI release 2.1

https://github.com/department-of-veterans-affairs/va.gov-team/issues/63928
