### ISSUE TITLE
Add streamlined waiver notification to VA Notify portal 

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#62288]
## Issue Description
Create a new notification template in the VA Notify portal for Veterans that complete a streamlined waiver submission for VHA FSR requests with the following copy

> From: U.S. Department of Veterans Affairs
Subject: The Debt Management Center has approved your request
Dear ((name)),
Thank you for completing the Financial Status Report (VA Form 5655) to request help with your VA debt. Your waiver request has been approved and you will also receive a letter from VHA in the mail.
Date submitted: ((date))
To check the status of your VA debt status at any time, sign in to https://www.va.gov/manage-va-debt/
Thank you,
VA.gov
Please do not reply to this email. If you need to contact us, please visit VA.gov.

---
## Tasks
- [x] Login to VA Notify portal via VA Network / PIV
- [x] Add new template to staging (for testing) and production
- [x] Retain newly created template IDs

## Acceptance Criteria
- [x] Notification templates are available in staging and production VA Notify portals 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
