### ISSUE TITLE
[PM, FE] 10-10CG - Spanish translation: Update JSON file

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#62283]
## Background
Per request from State department (via the Content team), the JSON file was not formatted correctly.  It needs to be updated and sent back.

The JSON file did not have the proper key:value pair format, as required for this translation.

## Tasks
- [ ] Update JSON file to include the key:value pairing
- [ ] Validate JSON with Engineer to confirm format and accuracy
- [ ] Send updated file to Content team
 
## Acceptance Criteria
- Updated JSON file is sent back to the State dept (via Content team)

**Comment by mkerns1** [comment]
@hdjustice Moved to Validate column for your review.

**Comment by hdjustice** [comment]
Validated and informed Content team of the update.
