### ISSUE TITLE
Design | CH36 Name Change

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#62284]
## Issue Description
- Form name changed from 28-8832 to 25-8832
 -- Platform team is responsible for making name changes to unauthenticated pages.
-- Forms Manager team is responsible for updating the pdf file on va.gov
- Ticket relates to #61721 
- [Additional Notes ](https://docs.google.com/document/d/1tZejPPUbRaDt162ZETL6_VJ2Ydi0zruV6zpPYlyHWgU/edit?usp=sharing)on form changes and requested enhancements.
---
## Tasks
- [x] Determine where form number appears in form flow. [Introduction page](https://www.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/introduction) is one example.
- [x] Draft language to add to the into page that explains that the form number 28-8832 is no longer available.

## Acceptance Criteria
- [x] Document areas that need the form name updated.
- [ ] Draft engineering ticket.

## Documentation + Designs
- Places and documents where form 28-8832 was mentioned: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1691071311991/35dcc1ac49a00c2c034905342f28643b97b39c26?wid=140-1691071382104
- **Designs:** https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1691071311991/35dcc1ac49a00c2c034905342f28643b97b39c26?wid=118-1691071382104 | [Sketch](https://sketch.com/s/d78c4168-3ef3-46e3-ab64-a674786182cb)

**Comment by fiorella-io** [comment]
Updates: I've identified different pages and documents that mention 28-8832. I've adding the Mural link in this ticket

**Comment by fiorella-io** [comment]
Updates: created designs for all the pages that need the form name update and added to this ticket under "Documentation + Designs"
