### ISSUE TITLE
Send streamlined waiver notification for eligible requests 

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#62290]
## Issue Description
When a Veteran goes through the streamlined waiver flow and completes the form they should receive a streamlined waiver specific notification. 

---
## Tasks
- [x] Add streamline waiver notification templates to devops and vsp-infra-application-manifests repo settings
- [x] Check if submission is streamlined and if feature flag is on and replace notification template with SW specific one
- [x] Add rspec tests for both flows

## Acceptance Criteria
- [ ] When a Veteran completes a streamlined waiver submission, they receive the streamline FSR notification
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Rolled over due to priority of recovering VHA FSR forms
