### ISSUE TITLE
[FE] initiative: Update use of moment.js library to date-fns

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-team#62294]
## Background
As @adamwhitlock1 pointed out in this comment, our codebase is using both the `moment.js` and `date-fns` libraries as dependencies. However, `moment.js` is [now a legacy project, and in maintenance mode](https://github.com/moment/moment/#project-status) but not being actively updated. The contributors recommend choosing a different library. 

We should switch all uses of `moment.js` to `date-fns` (in our `/dashboard/` application folder) for consistency and maintainability. 

---
## Tasks
- [ ] update all import paths of `moment` to `date-fns`
- [ ] update all instances of formatting 

## Acceptance Criteria
- [ ] all dates are still correctly formatted
- [ ] all e2e and unit tests still pass

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ FE
- _How can this work be validated?_ My VA and Notification Center projects still spin up successfully locally, no instances of `moment` appear

## Resources
- [date-fns GitHub repo](https://github.com/date-fns/date-fns)

**Comment by allisonlu** [comment]
keeping point estimate the same (i didn't start this work yet)

**Comment by allisonlu** [comment]
updating remaining point estimate to 3

**Comment by allisonlu** [comment]
I'm so close to opening a PR for this (I've [created the draft](https://github.com/department-of-veterans-affairs/vets-website/pull/26079)), just awaiting some insight from other devs for one failing unit test.

**Comment by allisonlu** [comment]
## To validate:

### for @ajakabcin 
- Log onto staging as Cecil Morgan 
- Under Health care you will notice that the appointment time will be in your local time zone (this will be different depending on your system timezone settings). 

To check different timezones (in Chrome):
1. Open Chrome dev tools. Click the three-dot menu on the right > More tools > Sensors

![Screenshot 2023-10-19 at 9 59 52 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8542413/5e6f76c0-c892-4850-9d74-74e8b3ec7744)

2. A tab at the bottom of the window will show up. Set to the following settings:
Location: **Other...**
Latitude: **40.5853**
Longitude: **-105.0844**
Timezone ID: **America/Denver**
Locale: **en-US**

![Screenshot 2023-10-19 at 10 03 17 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8542413/ef06b478-7984-4e9b-a7f7-1b3cc2aed42d)

---

### for @dellerbie 

- confirm that commit [c26c44](https://github.com/department-of-veterans-affairs/vets-website/commit/c26c44bb01eab2e0dd3af0678c51bc064c4ccdf7) has made it onto staging on the [Deployment dashboard](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/)

**Comment by ajakabcin** [comment]
@allisonlu this is good to go from my perspective, I defer to @dellerbie for dev review and then we can close this!
