### ISSUE TITLE
CT: Caution Flag Content and Profile Enhancements

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#6229]
As a user of the Comparison Tool, I need the Comparison Tool updated to provide current and relevant cautionary and complaint information so that I am provided with complete and accurate information while reviewing my education options.

## Assumptions:
1. The stories linked to this EPIC have been agreed upon by reps from OIT, DEPO and EDU.
2. This work follows the [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#analytics-request).

## Acceptance Criteria
1. All linked stories have been implemented and tested.

## VSP Collaboration Cycle.
- [x] ~Project Kickoff~ - N/A; started this effort before new process.
- [x] ~Design Intent Collaboration~ - N/A; started this effort before new process.
- [x] ~Usability Testing Prep~ - N/A; started this effort before new process.
- [x] ~Research Plan Review~ - N/A; started this effort before new process.
- [x] ~Information Architecture (IA) Request~ - N/A; started this effort before new process.
- [x] Analytics Request - #8001
- [x] ~Contact Center Review~ - N/A
- [x] Staging Review - #7792 
    - [ ] #7970 - Leaving issue open for tracking purposes.  Will not impede closing out of this epic.
       - [ ] #7985 - PDF Review assigned to EDU.
- [x] ~Privacy and Security Review~ - N/A
- [x] Full Accessibility and 508 Office Audit - #8880 
- [x] Post-launch Check-in (Submitted to VSP Platform Channel on Tuesday 6/16 at 3:30PM)

## Supporting Artifacts
1. [Caution Flags Research and Design File Repository](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/education-careers/school-comparison-tool/caution-flags)

**Comment by dneel-bah** [comment]
The following collaboration points were completed during the old discovery and prototype checkpoint process:
 Project Kickoff
 Design Intent Collaboration
 Usability Testing Prep
 Research Plan Review
 Information Architecture (IA) Request

**Comment by dneel-bah** [comment]
Final story was delivered to production on 06/23.  Closing this epic out.
