### ISSUE TITLE
Create single Q&A about identifying legitimate VA emails

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#62301]
## Issue Description
Carnetta reached out looking for pages that describe how to tell if an email from VA is legitimate, in response to phishing scams that target MHV credentials. We'll create a single Q&A with basic, evergreen tips for identifying real VA emails, for teams to link to from blogs and other communications. 

---
## Tasks
- [x] Draft Q&A 
- [ ] Review
- [ ] Send to MHV and VA Notify partners
- [ ] Copyedit and publish

<details>
<summary>Prepublishing checklist</summary>

### Before you begin
- [ ] Confirm that there are no updates in draft by other content authors that aren't ready to be published. Check the revision log and then confirm with the content author who made the previous edits that the page is ready to publish.

### Accessibility standards

- [ ] If your link or button will take the user off VA.gov, confirm that the text for the link or button contains a purpose and a target. The user should be able to tell from the link or button text what the call to action is (the purpose) and where they will end up if they click on the link (the target). The following link is an example of this: <br>[Read more about making links accessible on AccessibilityOz](https://www.accessibilityoz.com/2014/02/links-and-accessibility/)</br> 
**Note:** When you direct the user to another VA.gov page, the link only needs to contain text indicating purpose (the call to action).
- [ ] Confirm all phone numbers are in aria labels. [Learn how to code numbers with aria labels](https://design.va.gov/content-style-guide/dates-and-numbers#phone-numbers)
- [ ] Confirm that the hierarchy of section and subsection titles is correct (H1 to H2 to H3—levels shouldn't be skipped). [Learn more about section titles](https://design.va.gov/content-style-guide/page-titles-and-section-titles)
- [ ] Replace any sighted language ("view," "see," "look") with a word that's inclusive of our screen reader users ("check," "go to," "review").
- [ ] Avoid using other ability-focused language. ("hear back from")

### Link standards

- [ ] Confirm that links work (aren't broken—no error message) and point to the intended page (you pasted in the correct URL or chose the correct node ID).
- [ ] Confirm all link text is 100 characters or less.
- [ ] Check that you've selected a node ID for all links pointing to VA.gov (internal) pages. Only paste in a URL if the page you're linking to doesn't live in our CMS (isn't one of our modernized pages). [Learn how to add node IDs in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/linking-with-node-ids.md) 
- [ ] Check that all anchor/jump links are pointing to a node followed by # and the header identifier (Example: /node/47278/#information-for-survivors). Double check all anchor/jump links post-publish. 

### CMS standards

- [ ] Make sure all apostrophes and quotation marks are curly not straight. (Once this is automatic in Drupal, we can remove this item.)
- [ ] If there are alerts at the top of the Drupal Edit node for broken links, redirected links, or links to unpublished pages, correct the issues. If there's an alert for a broken link but the link is actually working, report the issue to the CMS help desk. [Read more about link alerts in the CMS knowledge base](https://prod.cms.va.gov/help/cms-basics/how-to-fix-broken-links-and-redirects)
- [ ] If publishing a brand-new page, confirm the left nav and url are set up correclty. (If the page is a child page, the section needs to be the same as the parent page in order for the left nav to show.) [Learn how to set up a url and left nav in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/adding-left-nav-and-url.md)
- [ ] Check if the page has a new or updated alert. If so, publish the alert separately. 

### Additional checks for translated articles
- [ ] If we don't have updated translated versions, add the alert that links to the corresponding English page and lets users know that the translated pages aren't up to date. 

</details>

## Acceptance Criteria
- [ ] Single Q&A is live in R&S

**Comment by laurwill** [comment]
Update: @d-beyer drafted content for this, but this request got pulled in to the larger sign-in transition communications, and this type of messaging will be handled in other content. Sorry about the confusion Derek, and thanks for the work you did on this!

@strelichl I'm closing this ticket — if a need for this Q&A reemerges, we can reopen.
