### ISSUE TITLE
How could we help teams ask VFS teams questions in a consistent, successful way?

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#62302]
## Purpose
Teams have asked before about including specific questions in the Survey. ([Lainey asked in particular](https://dsva.slack.com/archives/CPCGRR7F1/p1689858927297649)).  Is that something we should allow for now that there's also a separate Portal for anytime insights?

## Tasks
- [ ] Meet w/ Lainey to get an idea of questions/types
- [ ] Should we instead assist teams w/ how to conduct a short Slack poll/survey? 
- [ ] provide guidance on best practices for that?
- [ ] if these things are formatted and work the same way each time, it will be easier for VFS teams to take, making them more likely to engage.

## Acceptance Criteria
- [ ] Document discussions and decisions

**Comment by tayism** [comment]
Worked on this in a slightly different capacity in previous times.
