### ISSUE TITLE
NOD | Update language for contested claims

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#62314]
## Value statement

**_As a Veteran_** filling out an online Notice of Disagreement form
**_I want to_** have accurate definitions of terms I need to know
**_So that_** I can make an informed decision

## Background Context

The introduction and deadline screen within Board Appeal has ambiguous language about contested claims. In testing, this caused hesitation and misunderstanding about what contested claims are.

## Acceptance Criteria
- [ ] Users see an clear definition of contested claims on the introduction to the form
- [ ] Users see a clear definition of contested claims on the deadline screen of the form
- [ ] Reviewed and approved by product and/or design

## Designs and Build Notes
TBD

## Out of scope
- Additional changes to the introduction or deadline screens

## Tasks
- [ ] Update contested claim language on introduction
- [ ] Update contested claim language on deadline screen

## Definition of Ready (user story)
- [ ] _Clear value description_
- [ ] _Testable acceptance criteria_
- [ ] _Accessibility added to acceptance criteria_
- [x] _Approved designs attached_
- [ ] _Sample data provided where appropriate_
- [ ] _Estimated to fit within the sprint_
- [ ] _Dependencies and blockers linked_

## Definition of Done (user story) 

- [ ] Meets acceptance criteria
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design
---

**Comment by eileen-coforma** [comment]
@saderagsdale I originally had a ticket for language for contested claims, but I've adjusted it to include all of the 'low-hanging' language update opportunities. Let me know if this needs to be further refined.

**Comment by eileen-coforma** [comment]
Dropping by content office hours to get content reviewed (as suggested by Julie)

**Comment by eileen-coforma** [comment]
Converting this ticket to only refer to Contested Claims language, and moving additional language change to NOD Enhancement ticket.
