### ISSUE TITLE
NOD | v2 Endpoint Check NOD frontend <-> Backend Wiring, End to end testing

### ISSUE THREAD

**Issue by kylesoskin** [department-of-veterans-affairs/va.gov-team#62311]
## Tasks
- [ ] Switch backend setting from current schema to new schema endpoint
- [ ] Check if backend supports new schema already
- [ ] If not, make it work
- [ ] Once we think it works, put it in staging
- [ ] Send example submission through
- [ ] Verify and discuss submission/PDF with external stakeholders to ensure it is OK

## Definition of Ready 

- [ ] FE work reasonably done (payload defined)
- [ ] LH endpoint available

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by BVA intake team, product and/or design

**Comment by saderagsdale** [comment]
- The most significant difference is adding three new points of data and changing country name to the country code
- FE will send both and BE will figure out which to use
- Approach will allow them to shift incrementally to the new submission endpoint
- For SIP forms, we can redirect them to either the deadline extension page (robin will add the code for this).

**Comment by saderagsdale** [comment]
Reached out to LH to discuss automation issue.

**Comment by kylesoskin** [comment]
LH has PR in for overlapping text issue. Will resubmit to CMP once it is released.

PR is here: https://github.com/department-of-veterans-affairs/vets-api/pull/13535
