### ISSUE TITLE
CT: Profile "Estimate Your Benefits" Section Enhancements

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#6231]
As a user of the Comparison Tool, I need the "Estimate Your Benefits" section of the Comparison Tool Profile pages updated to be 508 compliant and more user friendly so that all user types can effectively use the tool to review their benefits.

## Assumptions:
1. The stories linked to this EPIC have been agreed upon by reps from OIT, DSVA and EDU.

## Acceptance Criteria
1. All linked stories have been implemented and tested

## VSP Collaboration Cycle.
- [x] Project Kickoff - #7132
- [x] Design Intent Collaboration - #7420
    - [x] #7728
    - [x] #7795 
- [x] Usability Testing Prep - #8675 
- [x] Research Plan Review - #7400 
- [x] ~Information Architecture (IA) Request~ - N/A
- [x] Analytics Request - #9991 
- [x] Contact Center Review - #10166
- [x] Staging Review - #9989
- [x] ~Privacy and Security Review~ - NA
- [x] Full Accessibility and 508 Office #10786
- [x] Post-launch Check-in (Submitted 09/08/2020)

## Supporting Artifacts:
1. [Estimate Your Benefits Research and Design Repository](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/education-careers/school-comparison-tool/estimate-your-benefits)
