### ISSUE TITLE
Enable Rated Disability in production: 1% traffic

### ISSUE THREAD

**Issue by mchae-nava** [department-of-veterans-affairs/va.gov-team#62318]
## Issue Description
This is a timeboxed item to monitor traffic and issues via DataDog after directing 1% of users
Timebox: 1 week

https://vagov.ddog-gov.com/dashboard/zc5-23v-wpq/benefits---dbex---evss-to-lh-rated-disability?from_ts=1689866014643&to_ts=1689869614643&live=true

## Tasks
- [ ] Use DD to monitor for anomalies
- [ ] If no anomalies within the agreed timebox, raise to 5%
- [ ] If any issues, disable feature flag and create ticket to address

## Acceptance Criteria
- [ ] No anomalies and traffic raised to 5%

**Comment by alatempa24** [comment]
Started this rollout at 1%, but experienced some issues. Other teams also were experiencing issues with the RD endpoint. As of 10/5 it seems issues are resolved but due to staffing & not wanting to release on a Friday, team agreed it's best to hold RD release until next week.
