### ISSUE TITLE
STEM: Edith Nourse Rogers STEM Scholarship OMB Form 22-10203 Implementation

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#6232]
As a CH33/FRY Scholar benefit recipient, I need to be able to apply for the STEM Scholarship without having to complete the 1995 form so that I only have to provide relevant information to the application.

As a veteran desiring to update my benefits using the 1995, I need to be able to complete the form and submit without needing to answer irrelevant questions to my need, so that I can complete the form efficiently.

## Assumptions:
1. The stories linked to this EPIC have been agreed upon by reps from OIT, DEPO and EDU.
2. This work follows the [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#analytics-request).

## Acceptance Criteria
1. All linked stories have been implemented and tested

## VSP Collaboration Cycle.
- [x] Project Kickoff - #8089
- [x] Design Intent Collaboration - #8956 
- [x] Usability Testing Prep - #9554 
    - [x] #9699 - Leaving this open until the static page is ready and the breadcrumb can be updated appropriately.
- [x] Research Plan Review - #9465
- [x] Information Architecture (IA) Request - #11284 
    - [x] #10670 - New static content page
    - [x] #12252 - Update related pages to support STEM page
- [x] Analytics Request - #10780
- [x] Contact Center Review - #12670 
- [x] Staging Review - #12084
    - [x] #12288 - Content updates
    - [x] #12307 - IA Feedback - Staging Review - STEM Scholarship
    - [x] #12321 - Staging Accessibility Review: STEM Standalone Form 22-10203
- [x] Privacy and Security Review - [#148](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/148)
- [x] Full Accessibility and 508 Office Audit - #13685 
- [x] Post-launch Check-in

## Supporting Artifacts
1. [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/10203_product_outline.md)
