### ISSUE TITLE
Update SharePoint credentials and resubmit missed submissions

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#62334]
## Issue Description
The SharePoint credentials expired after a default window of 1 year. We need to be issued new credentials, update our config with those and resubmit once the connection has been re-established.

---
## Tasks
- [x] Gather new credentials
- [x] Update parameter store
- [x] Develop script to resubmit missed submissions
- [x] Pass script to platform
- [x] Followup with Ashlie Roy

## Acceptance Criteria
- [x] Submissions have been passed to VBS and we've communicated with Huron
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
