### ISSUE TITLE
Plan a kickoff meeting w/ Perigean

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#62339]
We proposed our longitudinal study to Kevin and Robyn Singleton who provided feedback for our research plan. Robyn recommended arranging a kickoff meeting with Perigean to explain our study design and request.

From Robyn: "would recommend asking for a KO meeting with Perigean to explain the study design and your request of them, including if you wanted them to call and speak with participants ahead of the first group discussion to ensure they understand what is being asked of them. Feel free to include me in that KO meeting given the uniqueness of this design (for Perigean)."

## Acceptance Criteria

- [x] feedback has been implemented into research plan

## Tasks

- [x] contact Brian Moon and Shannon Housel to set up meeting
- [x] define demographics of participants and number of participants per session
- [x] write out questions about the longitudinal study recruitment and format
- [x] outline study timeline and formats

**Comment by skirkman16** [comment]
Met with Perigean and sent follow up questions. Implemented recommendations and feedback for recruitment into our [research plan](https://docs.google.com/document/d/1dc1P_IefjGc9lqSAXHiE-dwb_N17oqQOmdbSPfMh0bQ/edit)
