### ISSUE TITLE
Need better solution to let users know they have actions to complete on confirmation page 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#62347]
## Description 

The solution needs (should strive) to work inside the link collection or with it. Not a new design pattern. 

Need comes out of the research we did. 

Refer to ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/60857 for quotes

More quotes from Veterans on [slides 24-25](https://docs.google.com/presentation/d/1cRijNi6LiRF_lmJs_cb9jliy1CW6u1ybyyAWBBEQ-J4/edit?usp=sharing). Might be some of the same as the above link. 

## Tasks

- [ ] Think through solutions/ideas. Other team was doing [exploration here](https://www.sketch.com/s/98e35645-34eb-40cf-80c1-6c4952943584/p/77BB399A-260E-4192-B1A5-CA5793821F38/canvas). 
- [ ] Create ideas
- [ ] Select idea
- [ ] Run by Laura
- [ ] Finalize wireframe

## AC
 
- [ ] Wireframes updated in unified check in

**Comment by benbrasso-agile6** [comment]
Next steps

1. Look at data once released to see how many are selecting that link 
2. What other research to get feedback after release from Veterans - diary, in person, etc. 

Notes from discussion: 

- Better identify the WHAT we want to change/impact
- Does the link list component have any way to highlight something
- Does the tag component have rules that don't fit within the link list 
- Maybe look at content more, it was mentioned about reintroducing the number of items to complete

**Comment by ytsaoca** [comment]
Ideas: https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/5054CF35-FE05-4FA0-A170-49CADC42843C/canvas

**Comment by ytsaoca** [comment]
Attended the platform office hour. Decision: accordion at bottom
But it seems that Laura is still working on the content.
Wireframes:
Closed - https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/aMkVA4d
Open - https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/8VPOJZx

**Comment by benbrasso-agile6** [comment]
Add that to this ticket @ytsaoca https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/62160

Then go ahead and move it into validate

**Comment by ytsaoca** [comment]
Done. Sorry fro the confusion.

**Comment by loripusey** [comment]
Moving to Priority 3 epic since that is the completion page
