### ISSUE TITLE
VANotify template housekeeping

### ISSUE THREAD

**Issue by holytoastr** [department-of-veterans-affairs/va.gov-team#62349]
## Issue Description
VANotify prefers template configuration be set up a specific way. This card addresses those preferences

---
## Tasks
- [x] In the devops repo, add reactivation template id to settings files. [example](https://github.com/department-of-veterans-affairs/devops/pull/12821/files)
- [x] In the vets-api repo, add key from devops settings file to vets api settings file: config/settings.yml `Settings.vanotify.services.va_gov.template_id`
- [x] In the vets-api repo, for the Acceptable Verified Credential Service, add path to settings file for template

## Acceptance Criteria
- [ ] VANotify will be configured to not throw an error in alternate environments
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
