### ISSUE TITLE
CT: Institution Rating System

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#6234]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/school-ratings/product-outline.md)

## High Level User Story
As a Comparison Tool user, I need to be able to review feedback that other people have provided for an institution so that I can use that information to make an informed decision about where I would like to use my education benefits.

## Assumptions:
1. The stories linked to this EPIC have been agreed upon by reps from OIT, DEPO and EDU.
2. This work follows the [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#analytics-request).

## Acceptance Criteria
1. All linked stories have been implemented and tested

## VSP Collaboration Cycle.
- [x] Project Kickoff - #9627
- [x] Design Intent Collaboration - #10995
- [x] Usability Testing Prep #12607
- [x] Research Plan Review - Completed 8/21/2020
- [x] ~Information Architecture (IA) Request~ - NA
- [x] Analytics Request - #16164
- [ ] Contact Center Review
- [ ] Staging Review
- [ ] Privacy and Security Review
- [ ] Full Accessibility and 508 Office Audit
- [ ] Post-launch Check-in

## Supporting Artifacts

**Comment by dneel-bah** [comment]
Closing this epic as it is being transitioned to the DGIB project.  Transition epic here #29562.
