### ISSUE TITLE
[FSR] - Review Display - Cleanup titles and spacing

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#62361]
## Issue Description
Spacing and title sizes need to be cleaned up and made consistent. 

---
## Tasks
- [x] Fix `h4` display issues
- [x] Added form-system classes to each component 

## Acceptance Criteria
- [x] All titles and review page components are consistent 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
