### ISSUE TITLE
[Initiative] Community Care Provider Selection

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#6236]
# Stakeholder input:

## Who is the target user? 
Eligible community care Veterans who are using VAOS to request community care appointment

## High Level User Story / Problem / Opportunity
As a veteran, I would like the VAOS app to automatically find and display eligible Community Care providers closest to my residential address when booking a Community Care appointment. I also want my selected Community Care provider's information to auto populate any required fields into VAOS so I don't have to manually enter or copy-paste this information.

## Hypothesis or Bet
- We believe that by providing approved CC providers to Veterans during their CC request process in VAOS we will decrease request dropoff for these appointment types and also improve triage/booking time for Request Managers because information for these appointments is easier to find and easier to triage. 

## Outcomes / how will we determine success
- Improve the community care provider selection experience as part of a Veteran's scheduling experience
- Improve understanding of available community care providers (based on CCN) for Veteran's interested in community care
- Decrease dropoff of Community Care requests in VAOS due to confusing and complicated provider information gathering

## Definition of done
- [ ] VAOS app will automatically search for closest community care providers based on my residential address and type of care selected 
    - **Question for stakeholders:** do we limit results to the service-specific drive radius? (30 minutes for primary care, 60 minutes for 1 of the 5 specialty care services)
- [ ] Veteran can select their preferred Community Care providers
    - **Question:** Should results be displayed based on drive time radius based on time, no miles?
- [ ] Automatically populate Community Care provider information for Veteran's Community Care requests
- [ ] **Question:** Should a Veteran be able to enter an alternate address (other than the residential address on file) so Veteran can request appointment with Community Care provider in my current location?
- [ ] **Question:** Has the PACT requirement for community care been resolved with CCE API team/Dave M.?
    - Relates to: Veteran assigned to PACT (confirmed or pending) & they are requesting primary care appointment, VAOS should not display the option to request a CC primary care appt even if CC eligible
- [ ] **Still applicable?** If Veteran moves and their new local site is not CC enabled, Veteran cannot request CC appointment in VAOS (b/c their new site is not CC enabled)
- [ ] VAOS app will inform Veteran if there's a problem with my residential address so I can correct it prior to using community care provider smart selection -- **DONE** _(already part of flow, displays on Type of Care page)_
- [ ] Desirable to be able to display both provider name and group name
   - according to OCC the "ProviderName" isn't always the right name to show to the veteran.
   - For each provider list: First/Last Name, Practice Name, address, city, state, zip, distance (in miles) from veteran's residential address, service(s)
   - For groups we're supposed to show CareSiteName

## What's available today from a data perspective: ([Slack discussion worth reading)](https://dsva.slack.com/archives/CMNQT72LX/p1592940080193700)
- PPMS (Provider Profile Management System (contains the community care providers)
- vets-api
   - vets.gov/va.gov has been making use of PPMS endpoints to pull community care provider information into the facility locator for ~2 years
  - that experience has taught us that there have been performance/latency issues
  - some endpoint have been throwing 500s when under heavy loads
- MAS endpoint for PPMS data - https://veteran.apps.va.gov/ppms/v1/
  - proxies requests on to PPMS 
  - If VAOS does not need to distinguish between provider vs group names this service would work

## Technical notes/questions:
See technical RFC for supporting this feature [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/engineering/request-for-comment/RFC-2020-10-01-CommunityCare-Provider-Selection.md)

## (Optional) Supporting Documentation
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/product-projects/cc-provider-selection.md
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/product-projects/cc-provider-selection.md

## Collaboration Cycle
VSP Collaboration Cycle checkpoints:

- [x] Kick-off #14654

- [x] Analytics Request #18828, #20155

- [x] Contact Center Review #26591

- [x] Staging Review #19430

- [x] Privacy & Security Review [#211](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/211)

- [x] Full Accessibility & 508 Office Audit request submitted #23731

**Comment by lenaecb** [comment]
Note from @lalexanderson-dsva to Judy (2/13)
"DEPO has a team led by Dave Conlon who is working on iterations of the va.gov facility locator and community care. His team is currently addressing the exact same user problem that we are for this backlog item (As a user, I want to see the community care providers for a specific type of care nearest to my address). I plan to support his team in these iterations, and then take advantage of what they’re building, so we’re not doing duplicate work. They are doing some legwork to speed up PPMS (which is right now abysmally slow), and to fix the data syncing problem (45 variations on “podiatry”, for example), but then we can reuse the code in VAOS. Dr. Greenstone and team have been working with Dave, so they are aware of this work, but they may not be aware of our ability on va.gov to take advantage of Dave’s team’s efforts and reuse the code. "

**Comment by lenaecb** [comment]
@rtwell - tagging you in hopes you have some insight. Lauren mentioned that many moons ago you did a provider flow mockup potentially, or at least some research on this? I would love to know what you have! Thanks!

**Comment by rtwell** [comment]
ah, yes yes yes we did explore this back in the day—not so much from a research perspective but from a design perspective. 

found em!

first step, we offered a choice between the method a user would like to book an appointment: **type of care** vs **provider**:

![image](https://user-images.githubusercontent.com/12564977/79175058-a565cf00-7dca-11ea-8c7b-084e2e6059c1.png)

If the user selects **provider**, they would see a list of previously seen providers:

![image](https://user-images.githubusercontent.com/12564977/79175115-cd553280-7dca-11ea-8557-30986021bbfc.png)

We also had some affordances in place for a user to confirm their address so that we could figure out drive time, etc

![image](https://user-images.githubusercontent.com/12564977/79175350-7865ec00-7dcb-11ea-8183-b7bc7007ece1.png)

thats all i can find for now—unless @lalexanderson-dsva has something else in her memory bank (which is highly likely given my goldfish-like memory)

**Comment by lenaecb** [comment]
Currently doing additional discovery on the PMSS data to see how we can find a different path forward.
