### ISSUE TITLE
DR | Investigate Decision Reviews forms refactoring

### ISSUE THREAD

**Issue by rocio-desantiago** [department-of-veterans-affairs/va.gov-team#62362]
## Value Statement

**_As a_** developer
**_I want to_** review the repositories to investigate shared code/components for opportunities of storing repeated code used in our Decision Review Forms into one folder for our 3 appeals forms (HLR, NOD & SC)
**_So that_** tech debt is reduced and so that future developers don't have to make the same change across the same code in HLR, NOD and SC redundantly.

## Background Context

There are numerous places across Decision Reviews that could use refactoring into one folder as these 3 forms share very similar process with often times only having content be the difference. Platform enforces app isolation to reduce complexity across the VA apps. This research will help us share our findings and propose why the exception should be made for the 3 forms in Decision Reviews as it's already being done for COE (form and status apps sharing common folders)

## Out of scope

* Refactoring the code
* Other apps/forms not in Decision Reviews
* ~~Report to present to Platform to advocate for making an exception to app isolation rule~~ It was discovered that since 995, 996 and 10182 are under the Appeals directory - they're already in isolation per Platform's app isolation rule.

## Tasks

- [x] Compile a list of files/folders where potential code can be refactored into a shared folder
- [x] Tickets created, assigned and estimated

## Definition of Ready 

- [x] Have access to decision reviews folder (src/applications/appeals) in vets-website repository 
  > 995 - Supplemental Claims (src/applications/appeals/995)
  > 996 - Higher Lever Review (src/applications/appeals/996)
  > 10182 - Notice of Disagreement (Board Appeal) - (src/applications/appeals/10182)

## Definition of Done

- [ ] Next steps identified
- [ ] Folders/Files identified for next steps

## Next steps

- [ ] Create a folder of shared code/components
- [ ] ~~Report/Presentation to advocate to Platform team to make exception for this code cleanup~~

**Comment by rocio-desantiago** [comment]
From CodeClimate: 
https://codeclimate.com/github/department-of-veterans-affairs/vets-website/code?q=10182&sort=maintainability
https://codeclimate.com/github/department-of-veterans-affairs/vets-website/code?q=995&sort=maintainability
https://codeclimate.com/github/department-of-veterans-affairs/vets-website/code?q=996&sort=maintainability

**Comment by rocio-desantiago** [comment]
Next: Ticker creation to refine during scheduled backlog refinement tomorrow.

**Comment by rocio-desantiago** [comment]
Tickets broken down above for a good starting point to overall refactor.
