### ISSUE TITLE
EPIC | Profile | CICD

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#62378]
## Background 
Isolating our apps should speed up our time to deploy, this should reduce the number of tests we have to run and should make it quicker for development iteration. Right now it take 45min+

## Discovery 

[Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/engineering/discovery/isolated-app-builds.md)

## Tasks
```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/59386
- [ ] #62368
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/64077
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/43066
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65116
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65114
```

**Comment by mtcA6** [comment]
@Samara-Strauss Adam was able to complete the last ticket for this and while we didn't get as much of a reduction as we had hoped it did shave about 15 minutes off of a build. 


See Adam's  [comment:](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65114#issuecomment-1897196910)
> Past commits have taken 47+ minutes to run and this last commit took 29 minutes. Thats certainly better than nothing, but I was really hoping for sub 15 minutes or something... sigh. Oh well I'll take what I can get, we can close this out now.

**Comment by Samara-Strauss** [comment]
That's a huge improvement! I'm so glad we took the time to do this work. Is there anything Adam can do to get the timing lower, or is there not much he can do at this point?

**Comment by mtcA6** [comment]
Asked the same thing he said:

> At this point, I think we are at a decent place. One area we _could_ look into is how to make certain e2e tests faster since they are slower than the unit tests usually, but not sure it's worth it.
> 
> Lets call it good for now, and if I get fed up with long wait times again we can revisit.
