### ISSUE TITLE
Appointments on MHV on VA.gov Phase 2b - UAT

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#62383]
## Task Description
Plan, moderate, and synthesize Usability/ UAT research for the following features:
- The current facility/clinic selection process for direct scheduling
- Provider selection for CC
- The print button
- Breadcrumb and URL updates
- Descriptive back link
- After-visit summary

## Acceptance Criteria
- [x] [Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/2023-08-Usability-UAT/Research-plan.md)
- [x] [Submit study to GH repo board](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/409). 
- [x] Write screener questions (up to 6) for Perigean to include in their calendly sign up. 
- [x] Set up a kick off call with Perigean
- [x] [Conversation guide](https://docs.google.com/document/d/1Z31QycydA1QYgzrrLXk72qNHLvvR9_TUSvt-tmfMRQ8/edit?usp=sharing) (This will be in GH once I am done and put it in MD)
- [x] [Observer sign up](https://docs.google.com/spreadsheets/d/1psKVN-csDpXjvwFOEgGBUAdCzaF9M_Ua27pujRqaNzQ/edit?usp=sharing)
- [x] [Mural board ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1689954776087/f9c46f95011f1ba2bbe090a71496336e8cf98718?sender=uc6180068871478c530ab2434)for note taking
- [x] Schedule debrief sessions
- [x] Affinity diagram notes to identify findings and insights. 
- [x] Research findings report
- [ ] Research findings slide deck
- [ ] Schedule research readout with team and or DSVA design meeting. 
- [x] Add research folder to the VA [research repo](https://github.com/department-of-veterans-affairs/va.gov-research-repository/projects/1)

Use the [VA research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist#3-Participant-recruitment) to submit research for approval

## Deliverables
Research findings:
- [Enjoy HQ](https://app.enjoyhq.com/projects/z9AlkAjrY/overview)
- [Github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/2023-11-mhv-on-va-gov-phase-2b-vaos-uat/research-findings.md)

**Comment by Cieramaddox** [comment]
Waiting until AVS is launched to begin

**Comment by outerpress** [comment]
TBD whether we'll present this at a Monday meeting
