### ISSUE TITLE
Document Discrepancies and Improvements in Vets-API Set-Up Instructions 

### ISSUE THREAD

**Issue by gia-lexa** [department-of-veterans-affairs/va.gov-team#62396]
## Issue Description
There may be discrepancies in the setup instructions located in the [VA Platform Developer Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/running-vets-api-locally) versus those in the [GitHub Readme](https://github.com/department-of-veterans-affairs/vets-api#base-setup). 
In addition, any instructions that could be clarified in any way should also be added to the list of updates.
Once complete, the follow-up ticket will cover completing the listed updates. 

---
## Questions
1. Is there any reason to have and maintain the two sets of docs or can we deprecate the GitHub docs?
2. Is the `clamav` information out of date now that it doesn't run inside of vetes-api (and is instead it's own container)?
3. What does success look like? i.e. how do I tell if vets-api set up is complete? _I think the answer is being able to follow the steps to [run the app](https://github.com/department-of-veterans-affairs/vets-api#running-the-app)._

## Tasks
- [ ] Walk through both sets of documentation to confirm they're providing the same instructions
- [ ] If discrepancies are found, document them (they will be added to a follow-up ticket.)
- [ ] If any instructions are unclear, make note of what those are as well so they can be updated in the follow-up ticket.

## Acceptance Criteria
- [ ] Document that will list out any discrepancies between our two sets of instructions, as well as any instructions that need to be updated for clarity. 
---

**Comment by rmtolmach** [comment]
- ClamAV work will be handled in https://github.com/department-of-veterans-affairs/va.gov-team/issues/64345

**Comment by rmtolmach** [comment]
totally agree this should be done. So much so that I accidentally created another ticket for this work 🤦‍♀. I will close this one in favor of #101709
