### ISSUE TITLE
Staging review for converted components: Text input, Text area, Number input 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#62390]
## Design System Staging Review
This is a request for staging review for converted components: Text input, Text area, Number input 
  
#### Design System actions
- Navigate to reference link: [Design System Staging Review Guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572025931/Design+System+Staging+Reviews)  
- [ ] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the Design System meeting attendees email addresses
      - Invite all relevant Design System team members
   - Click "Schedule Event"
- [ ] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
 
##### Staging Review artifacts
Links to Storybook and Sketch
Text input 
- [ ] Sketch: https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4/p/04A043C5-65CA-43BB-88F2-E17EF8B12D7D/canvas
- [ ] Storybook: https://design.va.gov/storybook/?path=/docs/uswds-va-text-input--default 
- [ ] Guidance (not specific to v3): https://design.va.gov/components/form/text-input

Text area:
- [ ] Sketch: https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4/p/C6340B6C-F41E-423B-BDEA-B340A81C9714/canvas 
- [ ] Storybook: https://design.va.gov/storybook/?path=/docs/uswds-va-textarea--default 
- [ ] Guidance (not specific to v3): https://design.va.gov/components/form/textarea

Number input 
- [ ] Sketch: https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4/p/4C89A45B-E8D8-44ED-B79A-E64F34303F03/canvas#About
- [ ] Storybook: https://design.va.gov/storybook/?path=/docs/uswds-va-number-input--default 
- [ ] Guidance (not specific to v3): https://design.va.gov/components/form/number-input

- [ ] Other links
- [ ] [QA E2E tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-e2e-test-participationE2ETestParticipation) (provide a link to the product’s code)
- [ ] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D). For details, see [Prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).
  
#### Platform actions
- [ ] Staging review Slack thread with VFS team: https://dsva.slack.com/archives/CBU0KDSB1/p1689962471975849?thread_ts=1689962405.177879&cid=CBU0KDSB1
- [x] Meeting date/time: Thursday July 27, 2023 at 3.30 PM ET

#### Platform actions

- [x] Update this ticket with the Zoom recording
  - Recording URL: [LINK](https://oddball-io.zoom.us/rec/share/KXL4f4D8KzO8ULbyoKmqTwPFAlvfS7_D7K_NPEnjZB4j2KeK4c7jEIos875jx8cQ.6QxD7Z1D8ztT8qLR)
  - Password: a7Gq@ihi
  
#### Design System actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] Close ticket

**Comment by allison0034** [comment]
No design feedback : )
