### ISSUE TITLE
Create Single Slide for Platform Orientation

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#62403]
**Description**

Create a single slide for Platform Orientation to point to our video overview (which will use more in-depth slides)

**Definition of Done**

All tasks below are complete.

**Tasks**

- [x] Create slide using slide example provided by Shira
- [x] Edit any information that is relevant
- [x] Add link to our newly recorded video overviewing support
