### ISSUE TITLE
Identity Dashboard (FE) - Create form validations for the Teams Mgmt form

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#62408]
## Description
Validate the form inputs on the Create Teams page (use a form validation library if necessary)

## Tasks
- [ ] Use a form validation library
  - [ ] Create validation for the team name (reach out to backend for max character length)
  - [ ] Create validation for the email

**Comment by acald-creator** [comment]
Would like to review this to see if this is still required.

**Comment by asg5704** [comment]
This is no longer required as the dashboard is dead in the water right now
