### ISSUE TITLE
Update Reporting Documentation: DOMO and Looker

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#62400]
**Description:**

This ticket will house any tasks related to updating our reporting documentation in the Platform Support Confluence section: https://vfs.atlassian.net/wiki/spaces/PTST/overview

**Definition of Done:**

- All tasks listed below are complete.

**Tasks**

- [ ] Create and document the details of the Platform Support DOMO dashboard
- [ ] Create and document the process of the Support Bot in connection to the Looker Dashboard
- [ ] Note that both reporting capabilities should be looked at when reviewing (blurb at top of each page)
- [ ] Verify that the looker information feeds into the Support Bot page here: 
       (https://vfs.atlassian.net/wiki/spaces/SRE/pages/1883340805/Platform+Support+Slack+Bot+Configuration#Google-Sheet-Setup and https://vfs.atlassian.net/wiki/spaces/PTST/pages/2426241154/Support+Best+Practices)

**Comment by alyssagallion** [comment]
Work has been completed:

https://vfs.atlassian.net/wiki/spaces/PTST/pages/2703654967/Looker+Dashboard
https://vfs.atlassian.net/wiki/spaces/PTST/pages/2738946382/Domo+Dashboard+-+Platform+Support

Related ticket will complete the last section of the Looker Dashboard page. Closing.
