### ISSUE TITLE
Identity Dashboard (FE) - Implement Session Management

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#62417]
## Description
Implement session management with active refreshes

## Tasks
- [ ] Add session management with React Context + Provider
- [ ] Ensure `403: Access token is expired` get retried
- [ ] *Attempt to automatically refresh the tokens in the Auth Context Provider

**Comment by asg5704** [comment]
Already completed. Closing
