### ISSUE TITLE
[BE] Update Vets-API to use the newly stored cell phone

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#62438]
## Background
[Slack thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1689876825083059)

## Tasks
- [ ] [BE] **Update Vets-API to use the newly stored cell phone**
- Update CHIP to also store the cell phone in LoROTA (field TBD)
- Update Vets-API to use the newly stored cell phone

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
