### ISSUE TITLE
[CHIP] Update CHIP to also store the cell phone in LoROTA (field TBD)

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#62437]
## Background
[Slack thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1689876825083059)

## Tasks
- [x] [BE] **Update CHIP to also store the cell phone in LoROTA (field TBD)**

## Acceptance Criteria
- [x] Deployed to staging
- [x] Tested on staging

**Comment by brianseek** [comment]
Closing since this has been released to prod
