### ISSUE TITLE
FE | Profile | Direct Deposit | Cancel Modal on Direct Deposit != to Contact Info Modal

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#62464]
## Background

When a user is in the direct deposit screen and they begin to edit their information, if they decide to cancel and navigate away the modal that pops up doesn't match the modal we use on the contact information page. 

This ticket is so we can standardize that modal. 

## Tasks
- [ ] confirm which version of the modal we can use 
- [ ] check with design if we need to have copy reviewed 
- [ ] update the UI to match 
- [ ] get team (PM/Design to test) 

## Acceptance Criteria
- [ ] modals match and are ready for deployment 
- [ ] Complete all unit testing
- [ ] End-to-end tests showing 0 violations
- [ ] Notify Product Manager that the change is ready to be validated on Staging

**Comment by adamwhitlock1** [comment]
I have finished this work and it should be ready to validate on staging. If you compare the modals between contact info and direct deposit when you cancel editing the forms, the modals should match

**Comment by mtcA6** [comment]
Is there a user w/DD that's working? 16 and 202 are usually the ones I use but they're blocked because of the CH33 SOAP issue

**Comment by mtcA6** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/c42d08e1-24f7-4aaf-a09e-283daa093c01)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/485aba90-c191-4b92-ad05-32ee8f173fa9)

should we change the copy now to say "You haven't finished editing and saving the changes to your direct deposit information. If you cancel now, we won't save your changes." so we're no longer referencing the type of account?

**Comment by adamwhitlock1** [comment]
We should when we change to a single form, or I can do it now... idk which one would be better, but this one was kinda just the way the current modal was working was to pass in the section name into the modal component and it was used within the content.

**Comment by mtcA6** [comment]
We can wait I suppose. Has this been deployed to production? if so I can close this out

**Comment by adamwhitlock1** [comment]
It has been deployed to production. 
The daily deployment will push out any code that has been merged to the main branch at 3pm EST.

You can basically assume any code changes that have been merged will be deployed to production unless they are explicitly put behind a feature toggle.
