### ISSUE TITLE
Hold team intro for new team member, Rebecca

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#62467]
## Issue Description

- New team member's first day is Tuesday, August 8.
- We need to meet as a team to introduce ourselves to them.

---
## Tasks
- [x] Schedule 30 min - 1 hour to meet as a team; preferably **not** on their first day
- [x] Do individual introductions
- [x] Run through our team's mission and the services that we provide on a day-to-day basis; use the [Platform Content Team space](https://vfs.atlassian.net/wiki/spaces/CIT/overview) as a starting point.
- [x] Team meetings
- [x] Tools we use (Slack, ZenHub, Confluence, etc.) 
- [x] Show them our main product, Platform website, and our secondary services
- [x] Questions

## Acceptance Criteria
- [x] We will have met with the new team member to do more formal introductions and explain our services at a deeper level.
