### ISSUE TITLE
Create New Github Team

### ISSUE THREAD

**Issue by Midge-dev** [department-of-veterans-affairs/va.gov-team#62474]
## Description
Create new Github team for Umbrella (benefits-non-disability) to track code changes across vets-website and vets-api.

## Task
- [x] Create Team in Github
- [x] Invite all team members
- [x] Set Thomas and Laura as maintainers

**Comment by Midge-dev** [comment]
https://github.com/orgs/department-of-veterans-affairs/teams/benefits-non-disability/members
