### ISSUE TITLE
Collaboration Cycle for Employee Experience Team, 21-526EZ, max claims for increase

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/va.gov-team#62491]
### VFS team name

Employee Experience Team

### Product name

21-526EZ

### Feature name

Max CFIs (our shorthand name for this effort)

### GitHub label for product

n/a

### GitHub label for feature

n/a

## Kickoff questions

<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

June 2023

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Tools, applications and dynamic pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline / other relevant docs
- [Project brief, **condensed version** (slide deck)](https://docs.google.com/presentation/d/1c38hcsSCwEPUVC7xsBuUz0hkIfMKlKVGmbro67IPZ5g/edit?usp=sharing)
- [Project brief (google doc)](https://docs.google.com/document/d/11-L6dbZ7Hah-e2PL3-nfcN5c5T8uAbn3EumLikrEhV4/edit?usp=sharing)
- [Feedback from content team](https://dsva.slack.com/archives/C01BVF2A3V0/p1688999990545149?thread_ts=1688999894.966639&cid=C01BVF2A3V0)
- [Research ticket](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/336)
- [Sketch file](https://www.sketch.com/s/7b704520-bd67-4e58-8187-2164d7616bd4/prototype/a/5CCE9A0B-B19C-4E0C-AFE2-A90821E70893)
- [Analytics ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62370)

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Notify the Collaboration Cycle team of this ticket in the vfs-platform-support Slack channel.

- [X] I acknowledge that I must notify \#vfs-platform-support after submitting this issue.

Kickoff Slack Thread with VFS team: [LINK](https://dsva.slack.com/archives/CBU0KDSB1/p1690235668711919)

</details>

 ## Recommended Collaboration Cycle touchpoints

### Design Intent
<details open>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- Navigate to reference link: [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent)
- [ ] Schedule your Design Intent when ready:
   - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
      - The Governance team is responsible for inviting our team members, including our Product Owner, Product Manager, and practice area specialists. We also notify OCTO-DE practice area leads when we finalize meeting scheduling. 
   - Click "Schedule Event"
- [ ] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [ ] Link all artifacts **ONLY** in the Design Intent artifacts section below at least two days before the scheduled Design Intent.  **Do NOT add artifacts to Comments section**
  
**Design Intent artifacts**

See Platform guidance on [Design Intent artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Design Intent meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

- [ ] User flow (required)
- [ ] Whiteboard sketch or other lo-fi prototypes or wireframes
- [ ] Research plan
- [ ] Any other artifacts you have so far
  
##### Platform actions
- [ ] Design Intent Slack thread with VFS team: 
- [ ] Meeting date/time:
  
##### Platform actions

- [ ] If you have feedback, create feedback tickets and link to this epic. Once you have completed you review, check the box next to your practice area
  - [ ] Accessibility has completed the review
  - [ ] Design has completed the review
  - [ ] IA has completed the review
- [ ] Update this ticket with the Zoom recording
  - Recording URL: 
  - Password: 
  
##### VFS actions

- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Sitewide CAIA Intake Request
<details>
  <summary>Toggle Sitewide CAIA Intake Request</summary>

##### VFS actions
- [ ] Complete the [Sitewide CAIA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-CAIA-intake-request.2124906551.html)
- [ ] Link to the Sitewide CAIA Intake Request ticket below

</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [ ] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [ ] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

Provide links or documents for the following:

- [ ] Finalized design prototype or mockup
- [ ] Specify which pages are included in the review 
- [ ] Research plan
- [ ] Conversation guide
 
**Content artifacts**
  
- [ ] Your product’s content source of truth 
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)

**IA artifacts**

- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) feedback you received, including an IA review document or intake form.

##### Platform actions
- [ ] Midpoint review Slack thread with VFS team:
- [ ] Meeting date/time:

##### Platform actions

- [ ] If you have midpoint review feedback, create feedback ticket and link to this epic. Once you have completed your review, check the box next to your practice area
  - [ ] Design has completed the review
  - [ ] Accessibility has completed the review
  - [ ] IA has completed the review
  - [ ] Content has completed the review
- [ ] Update this ticket with the Zoom recording
  - Recording URL: 
  - Password:
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [x] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [x] Link to the Analytics Implementation and QA Request ticket below

https://github.com/department-of-veterans-affairs/va.gov-team/issues/62370#issuecomment-1691794531

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [x] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [x] Link to the Contact Center review request ticket below

https://github.com/department-of-veterans-affairs/va.gov-team/issues/64605

</details>

### Staging Review
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [ ] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [ ] I confirm the environment is available and test users have been provided.
- [ ] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
 
**Staging Review artifacts**
  
See Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts). Platform findings are based solely on the staging URL and test users provided, as reviewed during the four days before the Staging Review meeting. Any test cases not covered or any ongoing work taking place during the review period may not be reflected in those findings.  

**Product artifacts** 
- [ ] Staging URL
- [ ] Specify which pages are included in the review        
- [ ] Staging test user information         
  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
  
**IA artifacts**
- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) of the findings you received, including an IA review document or intake form.

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [ ] [Regression test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-regression-test-planRegressionTestPlan)
- [ ] [Test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-test-planTestPlan)
- [ ] [Coverage for References](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [ ] [Summary(Defects) reports](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [ ] [E2E tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-e2e-test-participationE2ETestParticipation) (provide a link to the product’s code)
- [ ] [Code coverage](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-unit-test-coverageUnitTestCoverage) (provide a link to the product’s code)  
  
**Accessibility artifacts**
  
- [ ] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D). For details, see [Prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).
  
##### Platform actions
- [ ] Staging review Slack thread with VFS team:
- [ ] Meeting date/time:

##### Platform actions

- [ ] Update this ticket with the Zoom recording
  - Recording URL: 
  - Password:
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [x] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [x] Link to the Readiness Review ticket below

https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1222

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by shiragoodman** [comment]
Governance has communicated to the Employee Experience team that a Staging Review is not required for this initiative. Still awaiting feedback from @jhouse-solvd regarding the Privacy, Security, Infrastructure Readiness Review.

CC @humancompanion-usds

**Comment by jhouse-solvd** [comment]
**Please submit a Privacy, Security, & Infrastructure Readiness Review** [(PSIRR) using this GitHub issue template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=&projects=&template=privacy-and-security-review.md&title=Privacy+and+Security+Review+%5BFeature-Name%5D).

- **This helps us track and evaluate changes made to VA.gov**, _even relatively minor ones_. 
- You can use ‘N/A’ or refer to this issue for any questions that may not apply to the change.
- The Platform Security team will review the ticket and reply as soon as possible.  The review will be completed within about two (2) weeks, depending on the complexity of the change. _If there is an urgent need, please inform your PO so that it can be prioritized and delivered more quickly._

Please feel free visit the team’s office hours on Tuesday and Thursday @ 12:30 ET using [this Zoom link](https://oddball-io.zoom.us/j/84279002816) if you have any follow-up questions.

Please also feel free to share feedback or suggestions. We hope to continue to improve this process! :relaxed:

**Comment by jhouse-solvd** [comment]
Thank you, @amylai-nava! 

I'll check on the ticket to make sure it's assigned properly. 

Someone from our team will follow up soon.

**Comment by jhouse-solvd** [comment]
@amylai-nava - Please disregard my previous comment. 

_I see now that the security review was already completed. :)_

**Comment by amylai-nava** [comment]
## **Progress Summary**
Completed:
- CAIA team feedback via office hours
- Platform Security review

In progress:
- Google Analytics request
- Contact Center review

Not applicable:
- Staging Review (based on the [governance team's recommendation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62491#issuecomment-1658991917))

**Comment by amylai-nava** [comment]
Hi @CherylEvans, although the google analytics request is still open, I believe this ticket can be closed!

**Comment by shiragoodman** [comment]
@amylai-nava you're free to close the ticket. We typically don't close the Collab Cycle request tickets bc we want to make sure the VFS team has everything they might need from it.

**Comment by amylai-nava** [comment]
@shiragoodman ah got it. thanks!
