### ISSUE TITLE
[FE] 10-10EZ - Household: URL migrations & updates

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#62517]
## Background
When we launched the Household section optimization work, we had to maintain the Original and the V2 URLs, since both were live at the same time.  Now that we are fully using the new Household section pages, we need to migrate them to the original URL structure (removing V2).

In ticket #73237, discovery was completed to outline a plan for migrating the household section of the form into the URL format that is consistent with the rest of the form, essentially removing the reference to "v2".

## Tasks

- [x] Remove v1 household component calls from `config/form.js`
- [x] Update the following files and remove -v2 from the url paths
     - [x] config/form.js
     - [x] tests/e2e/hca-household-v2.cypress.spec.js
     - [x] tests/e2e/index.js
     - [x] utils/constants.js 
- [x] Remove `householdInformation` directory and rename the `householdInformationV2` directory to `householdInformation`
- [x] Update `migrations.js `so that the referenced urls are updated on forms currently in progress
- [x] Rename `hca-household-v2.cypress.spec.js` to `hca-household.cypress.spec.js` for E2E testing
- [x] Complete E2E testing to ensure there have not been any conflicts, and that all pages display as expected
- [x] Update Fletcher to run a couple QA Test cases - Ticket #73386

## Acceptance Criteria
- The Household section of the 10-10EZ is consistent with the rest of the form

**Comment by jadon1979** [comment]
Upon completion of https://github.com/department-of-veterans-affairs/va.gov-team/issues/73386, then, per Matt, we should wait until staging has been deployed to prod so we can test during the afternoon and following day.  This way we can address any issues and do a rollback if necessary before it is deployed to prod.

**Comment by jadon1979** [comment]
Yesterday, prior to pushing the v2 migrations, I logged in with multiple users and went through various sections of the v2 household section so that the v2 urls would be saved with the form.  Today, the forms go to their proper household  url when continuing the form.  I've also tested as an unauthenticated user.
