### ISSUE TITLE
VSP Review: VA.gov Forms Sketch Template

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#6251]
## Steps to complete Staging Review: 

- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP <> **requesting team** review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled review meeting_
- Link to template prototype to be reviewed: https://vsateams.invisionapp.com/share/A2W64P7YUG9

## Meeting attendees from **requesting team**
- Product Manager (required): Shawna Hein 
- DEPO product lead (required): N/A
- Anyone else from your team who significantly contributed to the artifacts provided (required): Riley Orr, Jonathan Nelson

## Scheduling
Preferred dates or times: Flexible

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, ~QA~, and optional: ~product, analytics, engineering, information architecture~.

## "Product Outline":
With new members joining the VSA design team recently, a painpoint has been identified around VA.gov form patterns and guidelines. In order to familiarize ourselves with VA.gov form patterns and guidelines, designers often go through the various forms manually many times. This is time consuming and often confusing, as standards change between forms. For the past sprint, members of VSA have collaborated on a Sketch template that will help introduce new designers on VSA to VA.gov form best practices as well as create more consistent, faster design specs amongst VSA designers. This template was informed primarily by forms that exist in production today, so we would like to confirm these or get feedback on how to improve these templates for design use going forward.

**Comment by meganhkelley** [comment]
Review scheduled for Tuesday 3/3 @ 4:30 pm ET

**Comment by 1Copenut** [comment]
@andreahewitt-odd Can we close this one?
