### ISSUE TITLE
[Design] My VA Audit UX Improvements: Make "Learn how to file a claim" link static

### ISSUE THREAD

**Issue by aagosto90** [department-of-veterans-affairs/va.gov-team#62519]
## Background
As detailed in this [slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1690292542217169?thread_ts=1690231844.315009&cid=C909ZG2BB), since people can file more than one claim and have more than one claim going at a time, we've decided to always show the "Learn how to file a claim" link in the "Claims and appeals" section of My VA.

## Tasks
- [x] Update Sketch designs to always show "Learn how to file a claim" link
- [x] Update use case and FE documentation
- [ ] PM to create follow up FE ticket

## Acceptance Criteria
- [ ] Sketch designs and documentation are updated and ready for implementation

**Comment by aagosto90** [comment]
Sketch designs on [desktop ](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/25LlG1l)and [mobile](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/WK72gqw), [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/claims-and-appeals-FE-documentation.md#learn-how-to-file-a-claim-link), and [use case documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/use-cases/claims-and-appeals-use-cases) are all updated to always show the "Learn how to file a claim" link. I'll keep this ticket open til you create the FE ticket for this work @ajakabcin

**Comment by ajakabcin** [comment]
Closing! Created FE ticket for implementation yesterday: #62994
