### ISSUE TITLE
BE | Vets-API | Lighthouse Config Parameters

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#62512]
## Background
The following AWS parameters need to be added and configured in `vsp-infra-application-manifests` repo.

Add the following AWS parameters:

- /dsva-vagov/vets-api/prod/lighthouse/auth/ccg/client_id
- /dsva-vagov/vets-api/prod/lighthouse/auth/ccg/rsa_key

## Tasks
- [x] Add staging params in AWS parameter store
- [x] Add staging configuration in `vsp-infra-application-manifests` repo

## Acceptance Criteria
- [x] Reviewed by platform support team member
- [x] Review with Jason Conigliari
