### ISSUE TITLE
FE | Profile | Direct deposit | Remove helper text from routing number field

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va.gov-team#62527]
## Issue Description
The VA: Health & Benefits mobile app identified that the helper text is unhelpful for the routing number field when a user is editing their direct deposit information. The current copy (Your bank's name will appear after you add the 9-digit routing number) makes the user think their bank's name will show after just typing the routing number. But it doesn't appear until the user selects save button. Beth Potts from CAIA team and Misty Milliron-Grant from VAHB mobile app discussed this and determined the helper text is just not necessary at all and should be removed from both web and mobile app instances.
![Screenshot 2023-07-19 at 9.49.39 AM.png](https://images.zenhubusercontent.com/6266db4f486bbe5e4f5cd2fd/e9e4e4ae-447e-4d09-9c78-ac36380f9b63)

---
## Tasks
- [x] Remove helper text from the routing number field (including the parentheses)
- [ ] when modifying this we should also consider if we can resolve #19961

## Acceptance Criteria
- [x] Routing number field only include the field label (i.e., `Routing number`) and required label
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mtcA6** [comment]
@adamwhitlock1 this looks great in staging, tested w user 202.

**Comment by adamwhitlock1** [comment]
I'm going to close this one out. I'll comment on the other somewhat related issue #19961 as it is kind of blocked I think.
