### ISSUE TITLE
[Design] 10-10EZ - Screener question: Update design to reflect the new screener question page

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#62534]
## Background
Over the last few years, in almost every research session we have held, there is feedback on the Screener pages that are presented after the Veteran enters their Name, DOB and SSN.  These screener pages (Personal information pages) are redundant and cause confusion, most especially (but not exclusively) for Veterans using screenreaders.

We want to remove the 3 pages that follow the screener page for unauthenticated applicants.

<details>
<summary>Pages that follow the Screener page- Screenshots (click to expand)</summary>

![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/ee6a7721-91d9-405d-b973-bcbebf9da56c)

![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/2d90f8a9-1eb6-45e9-99f8-8932d7357b25)

![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/f2020536-e52c-4a1d-bfc9-b301a54ca9d6)

</details>

### Resources
- [Discovery Ticket #61198](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61198) 
- [Dev Ticket #61746](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61746)

## Tasks
- [x] Update design to remove the Veteran Name, SSN and DOB pages that follow the initial screener page (unauthenticated users only)
     - [Screenshot](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1688593774816/c44e309b107b8df7e9b8647d385ab4b0c8b7757a?wid=0-1688744100522) of screener page flowing directly to Place of birth page
- [x] Add the additional fields (Middle name and Suffix) to the current screener page
     - Simlilar to [this page](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/ee6a7721-91d9-405d-b973-bcbebf9da56c)
     - Keep the SSN and DOB fields
- [x] Update Mural board

## Acceptance Criteria
- The design file is updated to reflect 3 repetitive, post-screener pages are removed from the EZ application for unauthenticated applicants, and the screener page is updated to include the 2 additional fields.

**Comment by jessicastump** [comment]
Updated the Sketch source of truth files:
1. [Introduction and Pre-check](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/7E6D84B9-C0DA-43E9-B34F-EA564B30F55B/canvas) pages for both Unauth and Auth

**Comment by jessicastump** [comment]
The [content source of truth file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZ%20Form/10-10EZ-application-content.md) and the [Mural flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687376928311/303a0fbb8ffe1353eedf695ac86a6e069cd2003f?sender=uadf1ed7fe7c76f0914967329) have also been updated.
This ticket can be closed and is completed.
