### ISSUE TITLE
Burial Form Discovery

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#62530]
## Issue Description
Time box 8 hours for Burial 530 form discovery. 

---
## Tasks
- [x] Screenshot page by page of site and form flows 
- [x] Import UX Pin or Sketch screens if available
- [x] Add callouts and start identifying user flows
- [x] Align the format/legend with the [[526 Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686768383603/3f4415dd2ddb71bbd104ebefd92a2c7b553ad792?sender=udbd39c1bbebb4ec4d7d08829)]

## Acceptance Criteria
  - [x] All screens before and after login are captured
  - [x] Error states captured if able to validate
  - [x] Quick wins identified
  - [x] Known pain points acknowledged
  - [ ] a11y issues flagged
  - [x] Areas we want to learn or investigate further highlighted
  - [x] Identify missing fields in the digital form
  - [x] Identify missing content in the digital form

**Comment by fiorella-io** [comment]
Update:
- Created a current flow with screenshots and links to each page
- Created a simplified current state flow
- Compared the paper form and digital form
- Identified missing fields and descriptions in the digital form
- Created a simplified future state flow
