### ISSUE TITLE
Remove online pension form entry point from static page

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#62547]
## Issue Description
We need to temporarily remove the online form entry point content from these static pages:

- [How to apply for VA pension page](https://www.va.gov/pension/how-to-apply/)
- [Eligibility for VA pension](https://www.va.gov/pension/eligibility/)
- [About VA Form ](https://www.va.gov/find-forms/about-form-21p-527ez/)
- [Fully Developed Claims](https://www.va.gov/pension/how-to-apply/fully-developed-claim/) — 2 links in first and last accordions. Note: Product team may not be aware of this entry point.

---
## Tasks
- [ ] Update Drupal pages to remove online form and lead with paper form 
- [ ] Review
- [ ] Send previews to partners for approval
- [ ] Copyedit and publish

## Acceptance Criteria
- [ ] All entry points to online form are down, all pages lead with paper form

**Comment by katherine-fung** [comment]
Eligibility for VA pension
http://preview-prod.vfs.va.gov/preview?nodeId=585 

About VA Form: 
http://preview-prod.vfs.va.gov/preview?nodeId=6120

Fully developed claims: 
http://preview-prod.vfs.va.gov/preview?nodeId=587

**Comment by katherine-fung** [comment]
Eligibility for VA pension
http://preview-prod.vfs.va.gov/preview?nodeId=585 

About VA Form: 
http://preview-prod.vfs.va.gov/preview?nodeId=6120

Fully developed claims: 
http://preview-prod.vfs.va.gov/preview?nodeId=587

**Comment by megzehn** [comment]
Thanks, @katherine-fung! Confirming that I reviewed these changes and they are ready to publish when we get sign-off.

**Comment by katherine-fung** [comment]
In the epic ticket #62445, the product team dev said he found one more entry point for the online pension form. It's on the ["Evidence to support VA pension, DIC, or accrued benefits claims" page.](https://www.va.gov/resources/evidence-to-support-va-pension-dic-or-accrued-benefits-claims/) 

I've removed the entry point: 
http://preview-prod.vfs.va.gov/preview?nodeId=44702

**Comment by katherine-fung** [comment]
In the epic ticket #62445, the product team dev said he found one more entry point for the online pension form. It's on the ["Evidence to support VA pension, DIC, or accrued benefits claims" page.](https://www.va.gov/resources/evidence-to-support-va-pension-dic-or-accrued-benefits-claims/) 

I've removed the entry point: 
http://preview-prod.vfs.va.gov/preview?nodeId=44702

**Comment by katherine-fung** [comment]
Hi @megzehn, 

In preparation for the pension deactivation, which is now moving this forward (target date = end of this week), could you also review the changes on these 2 pages? 

- "Evidence to support VA pension, DIC, or accrued benefits claims": 
I removed the entry point for the online pension form. Here's the inline revision: 
https://prod.cms.va.gov/node/44702/revisions/view/627866/810476/visual_inline

- pension hub page
I removed the entry point for the online pension form. Here's the inline revision: 
https://prod.cms.va.gov/node/73/revisions/view/817836/820949/visual_inline 

Once you've reviewd these changes, the last entry points  to remove will be from the top and left navs. Thank you!!

**Comment by megzehn** [comment]
This work is done for now. HUGE thank you to @katherine-fung for all the collaborating, pivoting, and steering. 

@strelichl, I think we can close this one out. @katherine-fung do you want to confirm, and note the actual? 8?

**Comment by katherine-fung** [comment]
Yes, we can close this @strelichl 

Actual was ~12 because of the amount of re-work, back and forth with product and dev. (I know we don't have a 12 but do with it what you will)
