### ISSUE TITLE
VAMC Switch to Optional Fields - Backend Investigation

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#62546]
## Issue Description
As we were getting ready to begin deploying changes for [58745](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/vets-api/12996), we ran into some concerns regarding backend validation on submission, other validations in the repo for the same relevant fields, and post-deployment verification.

1. Christine ran up against submission errors locally, but is not using local vets-api with schema changes. Need to verify with local vets-api pointed to vets-json-schema feature branch (if possible. i think it is, and looks something like [this ](https://github.com/department-of-veterans-affairs/vets-api/pull/12996/commits/0d79ef47372d1872956d6b0fad9aa72fe55a57ac) and [this](https://github.com/department-of-veterans-affairs/vets-api/pull/12996/commits/8b8ad1895535b563d55cb97c6cd3fca04c99744b), with the revision pointed at the git hash of the feature branch. - Done

2. Some references to these specific validations were found in the repo that might need to be changed and/or investigated
   - [Claims API](https://github.com/department-of-veterans-affairs/vets-api/blob/9b7a7bd3a54fb11e967c37a876e09fe99693041b/modules/claims_api/app/controllers/concerns/claims_api/disability_compensation_validations.rb#L500)
   - [form526_submit_v2.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/9b7a7bd3a54fb11e967c37a876e09fe99693041b/app/swagger/swagger/schemas/form526/form526_submit_v2.rb#L427)
   - in [data_translation_all_claim.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/9b7a7bd3a54fb11e967c37a876e09fe99693041b/lib/evss/disability_compensation_form/data_translation_all_claim.rb#L436)
   - do a find on 'treatedDisabilityNames',etc
   - Do these need to be changed? And that the change will not impact these areas.
3. Need a better way to test for downstream impacts of these changes. Our best advice on this was from Bonnie Craig at the end of this [thread](https://dsva.slack.com/archives/C1VBAHWQL/p1686785454385369), but we need to figure out what that even means...
  
- If these fields come to downstream applications (BGS or VBMS) as null or blank, will they cause a failure? Answer: VBMS does not care what the fields are since it's just storing the submission data as a PDF in the Veteran's eFolder. Balakumar Srinivasan from EVSS confirmed that there is no change on transforming this data to BGS.
  
    - Bonnie (EVSS) shared information regarding the update removing these as required fields [here](https://dsva.slack.com/archives/C1VBAHWQL/p1701266135530009?thread_ts=1701210365.407459&cid=C1VBAHWQL). 
    - Kayla (LH) shared information regarding the update [here](https://dsva.slack.com/archives/C1VBAHWQL/p1701194112849079?thread_ts=1686785454.385369&cid=C1VBAHWQL). LH is investigating to see if they can fix treatedDisabilityNames to allow null (ETA is unknown).
    
 4. Are these fields optional in Lighthouse? Yes but "The treatedDisabilityNames cannot be null [for now], but we have tested with the other related attributes set to null." 
---
## Tasks
- [x] What fields are we making optional? `vaTreatmentCenterAddress/country`; `vaTreatmentFacilities` (entire block); `vaTreatmentFacilities/treatmentCenterName` && `vaTreatmentFacilities/treatedDisabilityNames`
- [x] Are the above fields required in EVSS? this [slack thread](https://dsva.slack.com/archives/C1VBAHWQL/p1686785454385369) and [this confluence page](https://confluence.devops.va.gov/pages/viewpage.action?spaceKey=VAExternal&title=Form526+Validation+Rules) confirms that these fields are optional in EVSS
- [x] Are the above fields required in Lighthouse: No, none are required by [Lighthouse's API](https://dev-developer.va.gov/explore/api/benefits-claims/docs?version=current)
- [x] Are any code changes needed? Yes, in [data_translation_all_claim.rb:458](https://github.com/department-of-veterans-affairs/vets-api/blob/9b7a7bd3a54fb11e967c37a876e09fe99693041b/lib/evss/disability_compensation_form/data_translation_all_claim.rb#L458) we need a safe navigator (`treatment['treatmentCenterName']&.gsub...`) so that the ruby code will not error out if the center name is `null/nil`

## Acceptance Criteria
- [ ] Resolve above questions
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
Work on this ticket after the LH migration so the testing effort is targeted towards LH.

**Comment by RakshindaAslam** [comment]
Check with LH is these fields are optional.

**Comment by tommasina-va** [comment]
We are getting closer to feeling confident that we understand the risks of this change. We're waiting to hear back from Kayla in regards to LH updates which need to be made for treatmentDisabilityNames to be nullable and we're hoping to pair with Balakumar on setting up a Postman request so we can have more insight while testing.

**Comment by tommasina-va** [comment]
We are getting closer to feeling confident that we understand the risks of this change. We're waiting to hear back from Kayla in regards to LH updates which need to be made for treatmentDisabilityNames to be nullable and we're hoping to pair with Balakumar on setting up a Postman request so we can have more insight while testing.

**Comment by tommasina-va** [comment]
Postman request was successful! The Zoom recording and sample request JSON is [here](https://nava.slack.com/archives/C04MJV66ZPC/p1701368448560779). Note that we needed to be in CAG on Postman in order to submit the request. 

Waiting to hear from Kayla on the LH updates.

**Comment by tommasina-va** [comment]
From Kayla: "We confirmed that this is a bug on our side and we are working on the fix now. We are aiming to get this fix deployed early next week." (That would be around December 4-6).
