### ISSUE TITLE
Automation opportunities for adding Github Milestones to Collab Cycle initiatives

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#62561]
## User Story
As a Governance team member, I want to explore opportunities for automating the creation of new Milestones for every Collab Cycle Request gh epic so that we can utilize Milestones within Collab Cycle data quickly and efficiently.

Assignee: @it-harrison 
Peer Reviewer: @briandeconinck 

## Description
Governance team learned that is it not possible to pull the Epic number from the Collab Cycle Staging Review issue tickets to be included in the data set for Domo because Epic is a ZenHub feature, not Github. However, we did learn that Milestone, a feature of GitHub, might be an appropriate alternative. Since applying the same Milestone to a group of issues from the same Staging Review (or same Collaboration Cycle Request ticket) will allow us to pull data into domo and filter by Epic (aka see all the issues from the same Staging Review), the Milestone feature will essentially serve the same purpose as Epic would have.

Governance team has never used the Milestone feature before. We will need to have a Milestone created for every Collaboration Cycle initiative, or every Collaboration Cycle Request ticket. All Collaboration Cycle Request tickets have the `CC-Request` label and as of 7/25, [there are 119](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+label%3ACC-Request+) of them. Once the milestones are created, the Collaboration Cycle Request ticket epic as well as all the child tickets within the epic, will need to be added to the appropriate Milestone.

If this work were to be completed manually, it would take a significant amount of time and would leave room for human error. Instead, Governance team will identify if there is an opportunity to automate this process.

Note: If an opportunity for automation is identified, DO NOT EXECUTE until Governance team has identified a solution for creating and maintaining use of the Milestone feature moving forward. See ticket #62564.

## Tasks
- [ ] Create a draft doc with proposed solutions

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have identified a solution for bulk creation of milestones in va.gov-team
- [ ] We have identified a solution for adding all child tickets to the newly created milestones.

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
Have verified through experiment that by collating data from Github api and Zenhub api it is possible to fulfill this story. Am in the process of writing up this result.

**Comment by it-harrison** [comment]
@briandeconinck  A draft of my findings [is here](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2736193587/62561+-+Automation+Opportunities).

**Comment by briandeconinck** [comment]
@it-harrison All of this makes sense, and the code in your repo looks good!

**Comment by shiragoodman** [comment]
@it-harrison - I added 1 comment to your draft. My only other question is how long this will take to execute? Sounds like it could be pretty simple. Please let me know!
