### ISSUE TITLE
Create a page for all workshop findings

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#62573]
## Purpose
In order to catalog our findings, hypotheses, and recommendations, create a confluence page that can house these insights in a quick-to-digest page

## Tasks
- [x] Create a [confluence page](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2714370091/All+Workshop+Findings)
- [x] Sift through historic data and include on the page

## Acceptance Criteria
- [x] Confluence page is created
- [x] Historic data is collected
