### ISSUE TITLE
SOCKS access for Chris Kim

### ISSUE THREAD

**Issue by chriskim2311** [department-of-veterans-affairs/va.gov-team#62571]
### Your Name

Chris Kim

### Your Email

ckim@kindsys.us

### Your Role and Team

Front-End Engineer Sitewide Public Websites

### Product Manager (PM) name and email

Wes Rowe wesley.rowe@agile6.com

### Product Owner (PO) name and email

Jill Adams jill.adams@agile6.com

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDOdR34QzDcZqEKRa/kSG8giODM3h211h1SAOeXqSNj+JZKm6e0Qa51JcC1Htf8vYAsMKZApDGtZj+cBIXANgnzkO2mzHQIbEdTmwPWHDnU10tqUQ5HZ6hFJg3CIn449+YPR3cRGrl9WU6XSCLkmEA74WHl1m/QwVi8wE3Fk/F7ozXFCiwUAICZTxtSKDoJTeiFqnDM7gYRLGCgXGxEGyK3q00KMuc5KNeTT9VaxddkizH/w5uFHgDv6RbOEJHlTKcbwbLkoecQ13E7t2G5NoMfFzdEkC5Ekvuu2IzY/NzsOGIBeX3/l2E4FCOhvgkyaH4br8DxWz3ICWcKvJ5xnLAP9aL2vNFtkQXPf+TOZOs8m60kuePD/yFuj4wEGIzms4+On07SI7qic0VL4vOV3mblW5cw+npMHqYIqlVWbY0usk5adQU9iCgf1986tYRyRF11hRJELGZjgKxsEzH0pIvQ0inxGpfor9KS09WFjY/Mg1YC00rpdjwmehI1o8unlek= chriskim@Chriss-MacBook-Pro.local

### E-QIP Transmittal Confirmation

![Screenshot 2023-07-25 at 9 38 23 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/42885441/5cad6ca0-a004-4c12-aad5-b5c9bdb904ab)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.
