### ISSUE TITLE
Update Post-9/11 Bill and Fry Scholarship rates (PUBLISH 8/1/23)

### ISSUE THREAD

**Issue by katherine-fung** [department-of-veterans-affairs/va.gov-team#62599]
## Issue Description
We need to update the rates for the Post-9/11 GI Bill and Fry Scholarship ahead of the new rates going into effect on August 1. 

---
## Tasks

- [x] Update future rates pages for Post-9/11 GI Bill and Fry Scholarship (Katherine)
- [x] Update current rates pages for Post-9/11 GI Bill and Fry Scholarship (Katherine)
- [x] Create past rates page for 2022-23 Post-9/11 GI Bill and Fry Scholarship (Katherine)
- [x] Copy edit pages (Megan and Laura)
- [x] Add link for past 2022-23 rates for Post-9/11 GI Bill to left nav (Megan)
- [x] Add link for past 2022-23 rates for Fry Scholarship to left nav (Megan)
- [x] Publish future rates, current rates, and past rates pages (Megan)

**Comment by katherine-fung** [comment]
**Post 9/11 GI Bill** 
Current rates for 8/1/23
http://preview-prod.vfs.va.gov/preview?nodeId=1009 

Past 2022-2023 rates
http://preview-prod.vfs.va.gov/preview?nodeId=59486 

Future rates

**Fry Scholarship**

Current rates
http://preview-prod.vfs.va.gov/preview?nodeId=49549

Past 2022-23 rates
http://preview-prod.vfs.va.gov/preview?nodeId=59519

Future rates

**Comment by laurwill** [comment]
Hi @megzehn , I checked the numbers and dates in these 4 pages. They're ready for final prepub and publishing on 8/1.

@katherine-fung the only change I made was shifting the Fry licensing/exam monthly charge amount to the new rates. 

Thank you both! I'll be online the morning of 8/1 if you run into any issues with these.

**Comment by katherine-fung** [comment]
Thanks @laurwill! 

@megzehn, the stakeholders approved the language for the future rates pages. Can you review these 2? 

Fry Scholarship future rates:
http://preview-prod.vfs.va.gov/preview?nodeId=55729 

Post-9/11 GI Bill future rates: 
http://preview-prod.vfs.va.gov/preview?nodeId=52939 

Thank you!!

**Comment by laurwill** [comment]
@megzehn these are all live, correct? Can we close this out?

**Comment by megzehn** [comment]
@laurwill yep! We can close this. I'll move to validate and make sure it's in the tracker doc.
