### ISSUE TITLE
Medallia - A/B testing for Feedback button

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#62605]
## Issue Description
In order to A/B test the answers for "What is your overall satisfaction with this site?" the Feedback button must accommodate firing two different versions of the VFS survey. 
---
## Tasks
- [x] _Code logic and the button with the ability to choose a survey (1 of 2) 
- [x] Created logic to randomly launch 1 of 2 surveys when the feedback button is engaged. 
- [ ] 
## Acceptance Criteria
- [x] Tests run and complete. _
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by aubreyarcangel** [comment]
A/B test in staging. Will demo this Thursday to Stakeholders.

**Comment by ATMiddleton** [comment]
Will demo 8/10/23 11am

**Comment by ATMiddleton** [comment]
Complete as of  8/14/23
