### ISSUE TITLE
PM | Add Email as a Channel/Default Send/Checkboxes & Editing as a Subtask | create testing spreadsheet

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#62606]
As we prepare for staging review for these two bodies of work:

Email as a channel https://github.com/department-of-veterans-affairs/va.gov-team/issues/61101
Editing as a subtask https://github.com/department-of-veterans-affairs/va.gov-team/issues/49319

~~We need to pull together a testing document that covers the myriad of~~ [~~use cases~~](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-notification-preferences.md#draft-test-cases-to-account-for-when-we-add-email-as-a-channel) < the use cases are for email as a channel proper, not our first release which is focusing on default send/edit as subtask/ checkboxes 

Ensure we double check w VA notify that the default send is correctly reflecting for VA Notify

## Tasks
- [x] draft a[ test spreadsheet ](https://docs.google.com/spreadsheets/d/1-oSUr_kFqyptbSI6jRC3O7wqk3TNDOwaWedmO3eh7FA/edit#gid=1459792507)
- [x] share w team 
- [x] incorporate team feedback 
- [x] create [QA testing artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/default-send/QA/qaPlan.md)
- [x] confirm the browser requirements 
- [x] add in the users to the list
- [x] discuss with PO 

## Acceptance Criteria 
- [x] we have a QA testing document ready for QA

**Comment by mtcA6** [comment]
@Samara-Strauss pulling together the [testing spreadsheet ](https://docs.google.com/spreadsheets/d/1-oSUr_kFqyptbSI6jRC3O7wqk3TNDOwaWedmO3eh7FA/edit#gid=1459792507) and [qa test plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/default-send/QA/qaPlan.md) and I'm unsure about the browser coverage.

Reviewing the developer docs [for browser support policy](https://depo-platform-documentation.scrollhelp.site/developer-docs/browser-support-policy) it mentions the 4 browsers but doesn't mention the devices. The 11 combinations in the qa plan would ensure we're thoroughly testing across all of the browsers since it is a significant update to the UI. However, the number of firefox users is incredibly low, Liz and Pam looked and it was a terribly small fraction of users all year. 

Should we keep the 11 different combinations or should we reduce the list?

**Comment by Samara-Strauss** [comment]
[I asked this in Slack](https://dsva.slack.com/archives/C909ZG2BB/p1691776184667139) and I'm waiting to hear back -- do we know if browsers behave differently on Mac vs. Windows? While I don't want us wasting time checking Firefox if it gets low usage, I still feel a tiny bit uncomfortable totally leaving out a browser that's recommended for testing. I'm wondering if maybe we can test it on one operating system and not both (and maybe if we can test all browsers on one system, not both).

Also, does anyone use Edge on a Mac? I didn't even know you could do that until I looked it up just now.

**Comment by Samara-Strauss** [comment]
[Cross-posting from Slack](https://dsva.slack.com/archives/C909ZG2BB/p1692026514814009?thread_ts=1691776184.667139&cid=C909ZG2BB), these are my testing recs based on analytics ([browser/OS](https://analytics.google.com/analytics/web/?authuser=0#/report/visitors-browser/a50123418w177519031p176188361/_u.date00=20230714&_u.date01=20230813&_.useg=userX-kQMjyLSme9FoFRGfW9fQ&explorer-segmentExplorer.segmentId=analytics.operatingSystem&explorer-table.plotKeys=%5B%5D/) ; [desktop vs. mobile](https://analytics.google.com/analytics/web/?authuser=0#/report/visitors-mobile-overview/a50123418w177519031p176188361/_u.date00=20230714&_u.date01=20230813&_.useg=userX-kQMjyLSme9FoFRGfW9fQ/)). This brings us down from 11 permutations to 8.

**Mac**

- Chrome
- Safari

**Windows**

- Chrome
- Edge
- Firefox (testing on Windows instead of Mac since Windows gets significantly more traffic)

**iOS**

- Chrome
- Safari

**Android**

- Chrome

**Comment by mtcA6** [comment]
@Samara-Strauss thanks for the help making a call here! 

I updated the QA doc and the QA Spreadsheet, now just need users in there and I'll be good to close this out. :)
