### ISSUE TITLE
HLR | Create RUM dashboard for HLR

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#62613]
## Issue Description

We want to set up a RUM dashboard for the HLR form to assist with front-end debugging, and research/design.

Related: https://github.com/department-of-veterans-affairs/va.gov-team/issues/61682

---
## Tasks

- [ ] Create RUM dashboard in DataDog
- [ ] Verify, in staging, that RUM doesn't expose PII in staging.
- [ ] Switch RUM on in production, and collect preliminary results

## Definition of Ready
- [ ] Permission to create RUM
- [ ] Permission to switch sessionReplayRate to 100%

## Definition of Done
- [ ] RUM switched on in production.
- [ ] Demo for team.

**Comment by HeatherWidmont** [comment]
@Mottie waiting on Steve Albers to set up the RUM dashboard (different than the HLR dashboard)

**Comment by saderagsdale** [comment]
@Mottie Did you tag Steve in slack? Can you post a thread to the request?

**Comment by Mottie** [comment]
I tagged Steve [last Thursday](https://dsva.slack.com/archives/C05SGJEAJ65/p1695329550854779), and [again today](https://dsva.slack.com/archives/C05SGJEAJ65/p1695669239022899); but, he mentioned that he was the one that needed to set up the dashboard in a huddle. I think they all might be a bit overloaded this week because of the upcoming HCA deadline on 6/30.
