### ISSUE TITLE
Deliver JSON of resubmitted FSR forms

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#62614]
## Issue Description
We have submitted 451 lost forms to the VBS API and Ashlie has requested that we also send the JSON of the forms to her VA email to confirm their validity

---
## Tasks
- [x] Develop script to get JSON
- [x] Pass script to platform
- [x] Send results to Ashlie

## Acceptance Criteria
- [x] Ashlie has received JSON of recovered forms
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
