### ISSUE TITLE
UX | Default send/checkbox & editing as a subtask | UAT research plan and conversation guide

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#62610]
## Background
For default send, checkbox UI & editing as a sub-task go live, we need to prepare for User Acceptance Testing (UAT).

- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2023-09-UAT-edit-as-subtask-default-send-checkbox-ui/research-plan.md)
- [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2023-09-UAT-edit-as-subtask-default-send-checkbox-ui/conversation-guide.md)

## Tasks
- [x] Review test cases /use cases
- [x] Create UAT research plan
- [x] create UAT conversation guide

## Validation
- [x] Send links to team to let them review asynchronously
- [x] Have another designer review research plan

**Comment by andaleliz** [comment]
@mtcA6 in looking at [your future sprints](https://github.com/orgs/department-of-veterans-affairs/projects/926/views/19), it looks like team QA is slated for sprint 18, which wraps up on 9/12. 

Given that we have to have that complete before we kick off research, I think we can submit the research plan on 9/13.  Then Perigean needs 8 business days for recruiting, so we could run the study 9/25-27, at the very end of Sprint 19 and into Sprint 20.

Does that timeline sound right to you?

**Comment by mtcA6** [comment]
@andaleliz Sounds alright to me! I have it on my list of to-dos to create those UAT tickets. I'll try to get to it today so we can look at that on the board. 

I think since we have to have qa then staging review yet it might shift by a sprint or so but for now what you said makes sense to me.

**Comment by andaleliz** [comment]
Hi @Samara-Strauss - the research plan and conversation guide are ready for your review ([folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/Research/2023-09-UAT-edit-as-subtask-default-send-checkbox-ui)).  A couple of things to note:

- I [talked to Adam via Slack](https://dsva.slack.com/archives/C909ZG2BB/p1692292007266249) and we determined it is not necessary for users to repeat every single task for both _adding_ and _updating_ a mobile number. I've designed the tasks so we validate each piece of functionality through adding their mobile number, and then we just make sure it can be updated.
- The timeline assumes we get internal QA and the staging review complete by the end of the next sprint. We can adjust it if not
- It seems like it'll be tricky to accurately recruit people who have never updated notification settings, to test default send. As a back-up, we'll test internally if it doesn't work out during UAT.

Thanks in advance for your feedback!

**Comment by mtcA6** [comment]
@adamwhitlock1 @andaleliz should we update the QA testing spreadsheet as well to reduce the number of steps set out there?

**Comment by Samara-Strauss** [comment]
Sorry it's taken me so long to get to this with being out all week. Just reviewed, and this looks great. It's ready to submit whenever we're ready to do UAT.

**Comment by andaleliz** [comment]
No problem @Samara-Strauss! we're ahead of the game having this ready anyway. Thanks for taking a look and hope you are all feeling better.
