### ISSUE TITLE
Discovery - User facing occurrences of the words Disability and Condition in the 526ez form on va.gov

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#62619]
## Issue Description
The CAIA Platform team is trying to get consistency around the use of words Disability and Condition.

Condition is what a veteran claims on a claim
Disability is what is service connected and rated for a claim

Disability, Disabilities, Condition and Conditions
---
## Tasks
- [ ] 

## Acceptance Criteria
- [x] List of pages(URLs) with identifying sections and screenshots for where these words are presented to the user
   - Disability
   - Disabilities
   - Condition
   - Conditions
- [x] For each instance make determination if usage is correct or incorrect based Content definition 
- [ ] Flag any instances where change is unclear and get feedback from Content

## Output
- [x] Spreadsheet tracker with each url and each word appearance 
- [x] Screen shot of each in Mural (add to existing form flow)
- [ ] Update tracker with any changes needed
- [ ] Maintain a list of Test Users as needed (e.g. if we need to create a new test user or manipulate data to access a page then document)
   
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
cc @christinec-fftc

**Comment by lydiahooper** [comment]
I have included this work in language audit https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/57117 so should/can we close this ticket?

**Comment by sortizsh** [comment]
@nnicholas7  can you please add a link to the CAIA comments?

**Comment by nnicholas7** [comment]
Please see link to CAIA Ticket in Slack: https://dsva.slack.com/archives/C01K37HRUAH/p1694546631404639

**Comment by nnicholas7** [comment]
After the content review for "disability" and "condition,"  we determine that the words "claim" vs. "application" might be used interchangeably. We created a definition and use case for "claim" vs. "application" and put together a proposal for guidance that was then reviewed with VBA stakeholders who were on board with the approach. This is out of scope for this ticket, but something to consider for future audits.

- **VBA Meeting Minutes** (See September 19, 2023 notes)- https://docs.google.com/document/d/1H9xgYJ-oAj3AWKtnzZxOI3xv_ayQKju03rkc36Emax8/edit#heading=h.wkbkkdt5fl03  
- **Claim vs. Application Definition and Use Case**- https://docs.google.com/document/d/1bWH_CZ3uh-E5088gyEsqEphpLm-rT7UU-GeXSidYmls/edit#heading=h.4f661s8oc008

**Comment by nnicholas7** [comment]
The Disability vs Condition Language Audit was completed and passed on to the engineering team (Micah) to implement.
