### ISSUE TITLE
Upload lost VHA FSR forms to SharePoint

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#62615]
## Issue Description
451 VHA FSRs have been recovered and submitted to the VBS API but we still need to deliver the PDFs to SharePoint. This will require a code change and script to upload the PDFs to SharePoint

---
## Tasks
- [x] Isolate SharePoint and VBS processes
- [x] Create job to call SharePoint process
- [x] Develop script to create jobs for lost submissions
- [x] Pass script to platform

## Acceptance Criteria
- [x] Validate PDFs have been uploaded to SharePoint
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Rolling over. PR awaiting approval then will task platform team with resubmitting PDFs

**Comment by HeatherRienks** [comment]
@ScottyRJames - any update on this?

**Comment by ScottyRJames** [comment]
Uploaded what we were able to. Lost 10 submissions but unable to identify which ones due to lack of argument retention in sidekiq logs
