### ISSUE TITLE
Research | Profile | Direct Deposit EVSS > LH | UAT Synthesis

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#62626]
## Background 
Now that we've completed UAT we need to synthesize our findings 

## Tasks 
- [x] Complete report/summary ([Example of prior UAT research summary)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/uat/Benefit%20Payments%20%26%20Debts%20UAT%20Findings%20Summary.md)
- [x] Have [report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/Research/2023-08-direct-deposit-UAT/2023-08%20UAT%20findings.md) peer reviewed
- [x] ensure any UAT issue tickets have been created/documented 
  

## Acceptance Criteria
- [x] report has been shared with PM/PO

**Comment by pamela-drouin** [comment]
[Findings are here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/Research/2023-08-direct-deposit-UAT/2023-08%20UAT%20findings.md) -- @mtcA6 can you peer review this since Liz is out?

**Comment by aagosto90** [comment]
Hi @pamela-drouin - this looks great! I love the chart you used and will have to snag that next time I conduct UAT.

I would just give this a final proofreading because there are some things that seem leftover from a template or out of place, like "Summary of how you conducted UAT (include method, and number of participants)" in the "Approach" section, and this random sentence in the "Summary of Findings" section: 

> Selects “remember this browser” and it never remembers the 2FA for Firefox browser. Prefers VA app because it uses facial recognition.

I would also get rid of any past-tense language which may be copied and pasted from the research plan. These are all small proofreading updates but the content is there and you've done an amazing job on your first research study! Congrats!!

**Comment by pamela-drouin** [comment]
@aagosto90 Thank you! I went ahead and cleaned up the copy!
