### ISSUE TITLE
redundant redis config

### ISSUE THREAD

**Issue by erluti** [department-of-veterans-affairs/va.gov-team#6262]
## Problem Statement
How might we we consolidate `REDIS_CONFIG`?  `REDIS_CONFIG` is assigned a value in multiple files (mostly initializers) with the same value, `REDIS_CONFIG = Rails.application.config_for(:redis).freeze`.  
## Goal
`REDIS_CONFIG` should be defined in one place and reused wherever `REDIS_CONFIG` is neeeded.

## Objectives or Key Results this is meant to further
- Tech Debt
---
## Tasks
- [ ] Identify places REDIS_CONFIG is defined
- [ ] Choose where REDIS_CONFIG should be defined
## Acceptance Criteria
- [ ] REDIS_CONFIG is defined one time
- [ ] Tests pass for classes that use REDIS_CONFIG
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by erluti** [comment]
The way we initialize it from `config_for` is going to be deprecated in Rails 6.1.  This will also occur int `rakelib/connectivity.rake`.

**Comment by omgitsbillryan** [comment]
This was acting as a blocker to https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/6865 - so I took the time to fix it.
