### ISSUE TITLE
Team QA | Profile | Default Send/Checkboxes & Editing as a Subtask | QA testing

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#62629]
<details><summary>previous example</summary>
<p>
[example ticket #54771](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54771)
</p>
</details> 

```[tasklist]
### Blocked by
- [ ] #62606
```
## Background 
This ticket is where we're going to run QA 

[QA Spreadsheet](https://docs.google.com/spreadsheets/d/1-oSUr_kFqyptbSI6jRC3O7wqk3TNDOwaWedmO3eh7FA/edit#gid=1459792507)

### Slack convo around the use cases 

<details><summary>details</summary>

[Thread here](https://dsva.slack.com/archives/C909ZG2BB/p1692298072900669?thread_ts=1692292007.266249&cid=C909ZG2BB)
>Is it necessary for the participant to validate all the functions (triggering errors, triggering modal, cancel button, etc) both when they are adding a number AND updating a number?

>It is esseentially the same piece of code for either case, and in fact it is really the same piece of code as the contact information page, just slapped into it's own page in isolation for a single field.
I think one or the other would be fine for each participant. If they have a number already then we could have them update it, and if they dont have a mobile on file, then have them add one (then optionally remove it afterwards via the contact info page if they dont want it on file)
>Throughout all the sessions if we could at least have one or two of each, then that would be ideal in my eyes.

</details> 

## Tasks
- [ ] ~group call for the last three use cases focused on Default Send (use this as a dry run to ensure we're good to do this on UAT~  < (we ended up not needing this and completed things asynchronously) 
- [x] test staging users 
- [x] populate spreadsheet 
- [x] add any[ adverse findings to the bottom chart on the QA test document ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/default-send/QA/qaPlan.md)

## Acceptance Criteria
- [x] All tested scenarios completed 
- [x] All corrective tickets have been created:

**Comment by andaleliz** [comment]
Hi @mtcA6 - I completed my testing and _then_ looked at this ticket and I see we were supposed to have a group call before we do testing.  Based on your [Slack message earlier today prompting us to test,](https://dsva.slack.com/archives/C909ZG2BB/p1693932802385819) I thought we were good to go :/ Hopefully, if I need to redo anything, it's just those last 3 test cases we need to have a call about.

I don't have edit permissions on the spreadsheet, so all of my feedback and results are entered as comments. Lmk if you have any questions! And, if I do need to re-test something, can you please reply to the comment? I think that'll help me stay organized.  Thanks!

**Comment by mtcA6** [comment]
@andaleliz im never so prescriptive. If you felt good running the tests (especially those last few) on your own that's TOTALLY ok and you can skip the call. I put the call item on there since I know I want an extra set of eyes looking over my shoulder. Meant to schedule that for tomorrow and the day got away from me. I'll tag you as optional for it :)

**Comment by andaleliz** [comment]
Safari on iOS completed!

**Comment by adamwhitlock1** [comment]
I completed my testing on mac and ios. Same issues as others reported but nothing new came up.

**Comment by mtcA6** [comment]
@pamela-drouin @adamwhitlock1 @andaleliz @tpharrison closing this QA ticket out as we've created all of the necessary tickets to follow up on. Thanks again for such great work!
