### ISSUE TITLE
Copy of Certificate of Eligibility | Display uploaded documents

### ISSUE THREAD

**Issue by Midge-dev** [department-of-veterans-affairs/va.gov-team#62622]
## Value Statement
**_As a_** Veteran applying for a home loan
**_I want to_** see the documents that I shared when applying for my CoE
**_So that_** I can quickly reference them when corresponding with a loan assistant.

---
## Background Context
LGY requested this functionality for us cases when a Veteran needs to quickly see what they shared with a loan assistant, so they can identify missing documents easily. 

## Acceptance Criteria
- [ ] When a Veteran uploads a document, it appears in the appropriate section of the page.
- [ ] When a Veteran clicks on an uploaded document, they can view the contents of the document. 

## Designs and Build Notes
- [Link to previous UX Pin designs](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/140810030/simulate/sitemap)

## Tasks
- [ ] Refine internally (Gary and Eugene to review in staging together)
- [ ] Discuss  use cases with LGY 

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
