### ISSUE TITLE
Add info alert about online form problem to pension page

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#62633]
## Issue Description
Pension online form is not working at this time. We need an info alert to communicate this info:
- Veterans with online forms in process can go to My VA (auth experience) to review info they already filled in
- The form will still allow them to submit the form, but they shouldn't do this
- They need to start over with the PDF form and submit by mail or in person

This info alert won't have a link or button to start — we may want to add a sign in react widget in future to lead people into the auth experience to find their in-process form, but this will be a future step.

So CTA will need to explain in words what to do, but not include a direct link to where to do it. 

Could consider putting this info alert under the How do I apply? H2 or at top of page, whichever makes more sense.

---
## Tasks
- [ ] Draft info alert (Katherine)
- [ ] Review (Laura)
- [ ] Send to partners for review 
- [ ] Copyedit and publish 

## Acceptance Criteria
- [ ] Info alert is live on pension page

**Comment by katherine-fung** [comment]
Hi @laurwill, 

I've drafted the info alert here: http://preview-prod.vfs.va.gov/preview?nodeId=586

**Comment by katherine-fung** [comment]
Hi @bethpottsVAdepo, 

Here's the draft of the info alert: 

[H3] Our online pension form isn't working right now

You can still apply for VA pension benefits. If you started your form online and you didn't submit it, you'll need to send us a PDF form by mail, in person, or with the help of a trained professional instead.   

If you'd like to refer to the information you saved in your online form when you're filling out the PDF form, sign in to My VA to find your form. Select your form under Benefit application drafts. The online form is for your reference only. Don't submit the online form. 

Keep reading for instructions to fill out and submit a PDF form.

**Comment by katherine-fung** [comment]
Here's the final alert copy. We'll hold off on removing the links to the online form until stakeholders give us the ok. 

[H3] Our online pension form isn't working right now

You can still apply for VA pension benefits by mail, in person at a VA regional office, or with the help of a VSO or other accredited representative. Download the PDF form we provide on this page.

**If you started your form online already,** you'll need to start over using a PDF form. But you can still refer to the information you saved in your online form. To do this, sign in to **My VA** to find your form. Select your form under **Benefit application drafts**. You can review your unfinished form, but don't submit it because we won't be able to process it.

**Comment by vbellissimo** [comment]
[Update from Emily via Slack](https://dsva.slack.com/archives/C057W3N9K2S/p1698155981409119) shared on Tuesday, October 24.

**User Stories:**

As a user attempting to apply for Pension benefits online,
I need to know what my options are when choosing to submit via PDF,
so that I can decide whether I want to mail my PDF form or submit it electronically via their system.

As a Pension team,
we need to ensure users attempting to apply for Pension benefits online know about the "quick submit" path to upload a PDF version of their form electronically,
so that they can decide whether they want to use that to submit their claim or not.

**More Info:**

Using "QuickSubmit" would allow a path for Veterans to still submit all-digitally. It already exists, we'd just be helping them find it. It would also allow us to frame "deactivation" as more of a "digital redirect" and give us time to build the updated online submission version of the form.

QuickSubmit is a feature supported by a team in VBA within a product called AccessVA that requires separate login.

**Tasks:**

- Update any verbiage on existing Pension deactivation designs that let veterans know that while the Pension online form is temporarily unavailable, they can still:

- Use "QuickSubmit" as a path where Veterans can still upload the PDF version of the 527 form

- Provide a link to [QuickSubmit](https://eauth.va.gov/accessva/?cspSelectFor=quicksubmit) within the verbiage.

**Acceptance Criteria:**
Any widgets and/or communications already drafted, within the form flows already identified, will be updated to communicate that while Pension form is temporarily unavailable, the veteran has the option to use QuickSubmit as an option to submit a PDF form digitally.

cc @katherine-fung @megzehn @jstrothman

**Comment by katherine-fung** [comment]
I provided updated copy for the info alert in ticket #68257.

**Comment by katherine-fung** [comment]
We provided the content to the team, and it's live on the page. We can close this ticket @strelichl
