### ISSUE TITLE
Implement GitHub Action to Prevent Condensation of settings.local.yml File

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#62648]
## Issue Description
During a recent update, we experienced an issue with the `settings.local.yml` file. It was found that the file was condensed into a string, causing extra characters to be added unintentionally. This not only led to errors but also made the file difficult to read and verify the presence of all environment variables.

To prevent such occurrences in the future, we need to implement a GitHub action that checks if the `settings.local.yml` file gets condensed. The action should ensure the file remains in its original, readable format. In the event of any condensation, the action should block the pull request until the issue is resolved.

Contact @RachalCassity or @holdenhinkle for questions.

---

## Tasks
- [x] Implement a GitHub action that verifies the `settings.local.yml` file is not condensed.
- [x] If the file is condensed, the action should block the pull request.
- [x] The action should provide a clear message to the user explaining the issue and suggesting corrective action.

---

## Acceptance Criteria
- [x] A GitHub action is in place that checks the format of the `settings.local.yml` file.
- [x] Pull requests with condensed `settings.local.yml` files are automatically blocked.
- [x] Users receive clear, instructive messages when a pull request is blocked due to this issue.

**Comment by RachalCassity** [comment]
This [PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2108/files) is an example of how to fix settings.local.yml

**Comment by laineymajor** [comment]
This one will wait until rachal returns

**Comment by rmtolmach** [comment]
@RachalCassity I disabled this action temporarily from the UI. It was failing incorrectly for a lot of PRs and devs were coming to support asking about it. 

Some examples:
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2496
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2494
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2491

It can be re-enabled in the UI: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/actions/workflows/vets-api-trailing-whitespaces.yml
