### ISSUE TITLE
(Brian) Demo/shadow deployment process for Torri

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#62650]
## Tasks
- [x] Coordinate with Torri your demo/shadow day
- [x] Account for additional time to provide her with context

## Acceptance Criteria
- [x] Torri will have shadowed how to do deploy
