### ISSUE TITLE
CH36 Form Name Changes

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#62663]
## Issue Description
- Form number changed from 28-8832 to 25-8832
- Ticket relates to other form updates in #61721 
- [Additional Notes ](https://docs.google.com/document/d/1tZejPPUbRaDt162ZETL6_VJ2Ydi0zruV6zpPYlyHWgU/edit?usp=sharing)on form changes and requested enhancements.

---
## Tasks
- [ ] Update CH36 form flow pages with new form number (from 28-8832 to 25-8832) based on documentation from #62284 
   - Places and documents where form 28-8832 was mentioned: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1691071311991/35dcc1ac49a00c2c034905342f28643b97b39c26?wid=140-1691071382104
   - **Designs:** https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1691071311991/35dcc1ac49a00c2c034905342f28643b97b39c26?wid=118-1691071382104 | [Sketch](https://sketch.com/s/d78c4168-3ef3-46e3-ab64-a674786182cb)
- [ ] Update [introduction page](https://www.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/introduction) with new form number (25-8832).
- [ ] Add language to the intro page stating that form 25-8832 was formerly 28-8832 (see [Sketch](https://www.sketch.com/s/d78c4168-3ef3-46e3-ab64-a674786182cb/p/1C43D9CF-316E-4568-91D9-E153514FB830/canvas))
- [ ] Update [apply pages](https://www.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/introduction) with new form number (25-8832)

## Acceptance Criteria
- [ ] All instances of 28-8832 have been changed to 25-8832 on CH36 intro page
- [ ] All instances of 28-8832 have been changed to 25-8832 on CH36 apply pages
- [ ] Language stating form number change added to intro page

**Comment by DLarson-Oddball** [comment]
Reopening as the redirect is not yet implemented.

**Comment by DLarson-Oddball** [comment]
Redirect is implemented
cleanup PRs: [vets-website](https://github.com/department-of-veterans-affairs/vets-website/pull/25875) & [content-build](https://github.com/department-of-veterans-affairs/content-build/pull/1720)

**Comment by DLarson-Oddball** [comment]
Closing as cleanup PRs are merged.
