### ISSUE TITLE
Enable Rated Disability in production for vets website requests: Pre-launch tasks

### ISSUE THREAD

**Issue by mchae-nava** [department-of-veterans-affairs/va.gov-team#62666]
## Issue Description
There a couple of amendments that will need to happen in order for monitoring the `rated_disability` release to be successful.

1. Saving to the `InProgressForm` suppresses certain errors, so in order for DD/Sentry to catch and report these we will need to add other calls to the `RailsLogger` to bypass this
2. We need to separate the `FEATURE_TOGGLE_RATED_DISABILITIES` Flipper from anything we don't want shipped
3. Logging at factory or provider levels

DD Dashboard here: https://vagov.ddog-gov.com/dashboard/zc5-23v-wpq/benefits---dbex---evss-to-lh-rated-disability?from_ts=1689866014643&to_ts=1689869614643&live=true

## Tasks
- [x] Add logging calls wherever may be useful and can bypass the save to `InProgressForm`
- [x] Separate out anything we don't want shipped to prod currently from the `FEATURE_TOGGLE_RATED_DISABILITIES` Flipper
- [x] Diagram the release plan (see below)

## Acceptance Criteria
- [ ] The DD eVSS graphs catch and display the logs/errors implemented for #1 and #3
- [ ] The feature toggle is for vets website requests only

### Diagram of the release plan

![BDex Diagrams - #62666 Rated Disabilities Feature Flag plan.jpeg](https://images.zenhubusercontent.com/5c1047425e37320ceee743c3/28a4fd5f-fb2f-4850-8a66-8e9fbdc2e7cd)
#### Pros of splitting rated disabilities release
- less points of failure on initial release
- easier to monitor one migration at a time

#### Cons of spilitting rated disabilities release
- potential juggling of two different failing data providers (EVSS + Lighthouse)
- potential differing data results between the frontend website vs. the submit background job

**Comment by RakshindaAslam** [comment]
Need 
- 1 Pre-launch ticket for submit workflow
- 1 Release plan for submit workflow
