### ISSUE TITLE
Research | Profile | Contact information | Investigate analytics around mailing address updates

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#62677]
## Background

Currently, if people update their contact information on the va.gov profile, it updates across _most_ but not all benefits (home loans and life insurance are two that don't). We have an FAQ at the top of the page that addresses this and links to a page with more info about how to update information for other benefits.

A conversation with a veteran and VA stakeholder who had a hard time updating their mailing address online highlighted the fact that we may have an opportunity to make this more clear to people. [slack thread where we discussed this event](https://dsva.slack.com/archives/C909ZG2BB/p1690215946603239)

We're not sure if this is an actual problem, but as a starting point, we can look into analytics and see if we can glean any insights that might tell us whether or not this is something to fix.  Some ideas of what to look into:

- click events on the FAQ compared with overall updates to profile
- click events on the FAQ compared with updates to the mailing address (since this is so critical to VA communications)
- navigation summary from profile to the page linked in the FAQ (http://va.gov/resources/change-your-address-on-file-with-va/#change-your-address-by-contact)
- probably other things I'm not thinking of
- It might also be worth qualitative data like Medallia feedback or call center data 

## Tasks
- [ ] Review data points mentioned above, along with any others not listed that could provide these insights
- [ ] Make a recommendation as to whether or not this is something that needs to be improved
- [ ] Share and align with team

## Acceptance Criteria
- [ ] team is aligned on how to move forward

**Comment by mtcA6** [comment]
There is already a list in the how to update your address page.
