### ISSUE TITLE
Contact #vfs-platform-support for Authorization page GitHub link

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#62678]
## Issue Description

We recently created a team policy on how to handle links on the Platform website that go to deprecated GitHub files under the `/platform` folder. The policy is [listed here](https://vfs.atlassian.net/wiki/spaces/pilot/pages/721420316/Authentication).

One of the reasons we discussed this policy is because during a deployment review of the [Authentication](https://vfs.atlassian.net/wiki/spaces/pilot/pages/721420316/Authentication) page, a link pointing to [this deprecated GitHub file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/backend/vets-api/authorization.md) was discovered.

Nevertheless, because the recent updates made to that page were not about that link, we decided to deploy the page.

Now we need to figure out how to resolve linking to that GitHub file so that the user is not confused if they experience clicking on that link with a deprecation message on it.

---
## Tasks
- [x] On the #vfs-platform-support Slack channel, fill out their support request form; select the "backend support" option
- Ask if there is a subject matter expert that can help us figure out how to resolve the issue of the link pointint to a deprecated GitHub file. Provide links in question. Options could be to:
- remove the reference in the content to the GitHub link; OR
- to update the link to a more appropriate link; OR
- recreate the instructions of the deprecated GitHub file on the Platform website and point to that new page instead.

- [x] make necessary content updates based on alignment with Platform technical SME
- [x] prepare the page for deployment
- [x] Fix the broken link on the [Authorization](https://depo-platform-documentation.scrollhelp.site/developer-docs/authorization) page

## Acceptance Criteria
- [x] The **Authentication** page on the Platform website will no longer have a link to a Deprecated gitHub file 
- [x] The broken link at the bottom of the **Authorization** page will be fixed.
