### ISSUE TITLE
Prep and send Supplemental Claims page for Spanish translation

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#62692]
## Issue Description

As part of our effort to provide multilingual content to Veterans, we need to translate our [Supplemental Claims](https://www.va.gov/decision-reviews/supplemental-claim/) page into Spanish.

We'll use the [checklist for content readiness for translation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/editorial-resources/preparing-content-for-translation-checklist.md) to prepare the content for the translators and then send to them in a Word doc.

**Note:** Be sure to include the metadescription when sending content and add word counts to top of Word doc.

## Tasks
- [ ] Prep content for translation (Ana)
- [ ] Review (Randi)
- [ ] Send to translators (Randi)

## Acceptance Criteria
- [ ] Supplemental claims content has been sent to translators

**Comment by ABeltran77** [comment]
Waiting for translations from State.

**Comment by ABeltran77** [comment]
@RLHecht please review prepped doc w/ word count and Meta description.

**Comment by RLHecht** [comment]
Thanks, Ana! Can you please upload the word doc here so we can track it all in the ticket?

**Comment by RLHecht** [comment]
I sent this to the translation team so we can close this ticket now. @coforma-terry @strelichl you may want to assign a sprint and fill out other sections before closing. We'll also need to create a new ticket to put in the backlog for creating and publishing the new Spanish page once the content comes back to us. If you need help with the tasks required let me know. You could also look at a similar ticket (we should have ones for disability and health care work). These translations should be back in 2 weeks.
