### ISSUE TITLE
Prep and send Report harassment or sexual assault at VA

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#62696]
## Issue Description

As part of our effort to provide multilingual content to Veterans, we need to translate our [Report harassment or sexual assault at VA](https://www.va.gov/report-harassment/) page into Spanish.

We'll use the [checklist for content readiness for translation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/editorial-resources/preparing-content-for-translation-checklist.md) to prepare the content for the translators and then send to them in a Word doc.

**Note:** Be sure to include the metadescription when sending content and add word counts to the Word doc.

## Tasks
- [ ] Prep content for translation (Ana)
- [ ] Review (Randi)
- [ ] Send to translators (Randi)

## Acceptance Criteria
- [ ] Report harassment or sexual assault at VA page has been sent to translators

**Comment by ABeltran77** [comment]
@RLHecht I emailed you the prepped Word doc w/word count & Meta for review.

**Comment by RLHecht** [comment]
Thanks, @ABeltran77 Can you please upload it here so we can track it all in the ticket?

**Comment by ABeltran77** [comment]
[Report harassment or sexual assault at VA_AB.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12468525/Report.harassment.or.sexual.assault.at.VA_AB.docx)

**Comment by RLHecht** [comment]
@strelichl We sent this a while ago to the translation team, so we can close this ticket. I'm setting up a new one now that we've gotten the translations back.
