### ISSUE TITLE
Clean up Welcome page

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#62693]
## Issue Description
Related to [support request #62688](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62688)

---
## Tasks

- [x] Add mission of the Platform to welcome page, as per customer recommendation

- [x] Audit broken links or links to outdated GitHub links

- Working in the open
- Design

- [x] Identify Platform SME for each content section of the [Welcome](https://depo-platform-documentation.scrollhelp.site/getting-started/welcome) page
- See comments below

- [x] Reach out to each SME of content with broken links or links to deprecated Git Hub links for input on whether information is still relevant and/or accurate.
- **Working in the open** (Vicky already asked Erika; pending info from her)
- **Design** (reach out to Carol to ask her if the github link should be replaced to linking to the [Design Intent](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) page instead 

- [x] Make necessary content updates based on alignment with Platform SMEs
- [x] Prepare the new content for deployment (if an existing page, review for any launch-blocking issues)
- [x] Once the new content deploys, close the original customer ticket.

**PLEASE NOTE:** Because this is related to a highly-visible page on the Platform website, please coordinate and make any edits with caution. Avoid putting this page in the Drafts section so it does not get unpublished during content edits.

## Acceptance Criteria

- [x] The content changes on the **Welcome** page will have deployed live on the Platform website.
- [x] The **Welcome** page on the Platform website will not have links to deprecated GitHub files.

**Comment by vbellissimo** [comment]
- Working in the open = Asking Erika Washburn
- Product = Erika Washburn (VA) or Jason Woodman (Oddball)
- Research = Naomi Marcussen
- Design = Carol Wong
- Content = CAIA / Terri Nichols (PM) or Randi
- Information Architecture = CAIA / Terri Nichols (PM) or Randi
- Engineering = Platform support channel?
- Accessibility = Governance Team / Shira Goodman (PM) or Brian DeConnick (Accessibility specialist)
- Analytics and Insights = Michelle Dooley
- QA = Peter Hill?
- ATO = Jesse House
- Security = Jesse House
- Privacy = Jesse House

**Comment by taylojill** [comment]
My updates to the Welcome page are in website drafts...Copy of Welcome 
I'm waiting on feedback to update "Working in the open" section. 
Here's what I did:
1. Reworked the intro to include slide 16 from Platform Orientation slide deck.
2. Moved VA.gov definition to the intro section.
3. Updated links in the Design section.
