### ISSUE TITLE
Define intake process for non-visual prototype requests

### ISSUE THREAD

**Issue by A6-toma** [department-of-veterans-affairs/va.gov-team#62698]
## Issue Description
As a development team, I want to have access to non-visual prototypes for products and features we're building so that the prototypes are accessible to assistive technology users for usability testing.

This ticket is meant to define the process by which a team will make a request to have a non-visual prototype built.

## Tasks
- [ ] Define what data/information we would need from a team to be able to build the non-visual prototype.
- [ ] Define the process a team would use to request a non-visual prototype be built, i.e. flowchart, instruction document, etc.
- [ ] As needed based on the defined intake process, create required artifacts, i.e. intake forms.

## Acceptance Criteria
1. Required data/information to make a request is defined and documented.
2. Request process is defined and documented, including any required artifacts, i.e. intake forms.
