### ISSUE TITLE
INTAKE EPIC | eBenefits Preferences

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#62722]
## Background 
There's a large spreadsheet of eBenefits notifications that are moving over to va.gov 

**eBenefits Early Comms**
They are migrating to [va.gov](http://va.gov/) and their emails need to migrate from EVSS to VADIR + VA Notify. Part of that will be determining what preferences will be needed in [va.gov/VA](http://va.gov/VA) Profile. On the eBen site they were very granular - almost per individual email.

[Slack thread w the full list of preferences from the old site ](https://dsva.slack.com/archives/C010R6AUPHT/p1650997804271029)

## Partners 
VA Profile 
VA Notify (Melanie Jones)

## Related tickets 
- [ ] design ticket/discovery for understanding which notification
- [ ] strategize w/VA Notify on how to convert/group those in the way that makes the most sense

## Acceptance Criteria 
- [ ] preferences are enabled in prod 
- [ ] documentation (including call center items is updated)

**Comment by mtcA6** [comment]
we can reopen this if we need it. closing it out for now as this will likely be handled by the VA Notify team as they're likely to take over the Notification Settings page.
