### ISSUE TITLE
Synch on proposed design changes

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#62723]
## User Story
As a Governance team member working on changes to the Collaboration Cycle dashboard, I want to review the proposed Domo design changes so that I can ensure I have what I need to begin implementing changes.

Assignee: @allison0034 
Peer Reviewer: @it-harrison 

## Description
An updated design for the Collaboration Cycle dashboard was drafted in ticket #59621 by a former Governance team member. This ticket was closed almost 2 months ago. I want to review the proposed design, document any questions I may have for the team, and ensure I have what I need to begin getting started implementing the changes.

## Impacted Artifacts
[Collab Cycle Domo Dashboard - Proposed Updates (Draft)](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686764117069/5e30ad39ba0126a133110af9e4d4864246634bf1?sender=942a4bcd-1ca0-4d35-97fd-c8c52cc9fcf8)

## Tasks
- [x] Review Analytics team [Domo training videos ](https://www.youtube.com/playlist?list=PL0QW9C65TdUVzgPFMASgplGQzfmdZjHSE)
- [x] Review the proposed design changes to the Collaboration Cycle dashboard:
   - [x] [Add highlights section and change dashboard name](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63756)
   - [x] [Modify and make updates to Domo card 1](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63757)
   - [x] [Create Domo card 2](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63758)
   - [x] [Modify and make updates to Domo card 3](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63759)
   - [x] [Modify and make updates to Domo card 4](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63760)
   - [x] [Create Domo card 5](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63761)
- [x] Sync with peer reviewer to address any questions or concerns that arise
- [x] If concerns arise, make changes to design after synching with Shira (Draft 3)

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team is able to move forward implementing the design changes to the Collaboration Cycle dashboard.

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
Began watching videos.

**Comment by allison0034** [comment]
@shiragoodman @humancompanion-usds I noticed Modify and make updates to Domo card 4 nad
 Create Domo card 5 slice data by practice area. Matt, Shira will be chatting with you about an alternative to this as we do not plan to track the new standards by practice area. I added a V3 option in the Mural.
