### ISSUE TITLE
Facility Locator Search Results Improvements

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#6272]
## High Level User Story/ies

1. As a Veteran using the Facility Locator, I need relevant search results returned to me quickly so that I have the information I need to visit the location. 
2. As a Veteran using the Facility Locator, I need to find the location closest to me (whether it is five or fifty miles away) so that I can visit the most convenient location. 

## Hypothesis or Bet

1. **If** we adjust the default number of search results in alignment with user expectations **then** we should meet the user's need **and** improve performance. 
2. **If** we allow Veterans to define search area by interacting with the map **then** we should meet the user's need **and** improve performance. 

## OKR
- Time for delivery of search results will improve by (TBD) by (date) (WIP)

## Definition of done

The following milestones have been successfully completed (or determined to be unnecessary for this work)

 - [ ] Project Kickoff (N/A: this work was already mid-flight when collaboration process rolled out)
 - [ ] Design Intent Collaboration (N/A: this work was already mid-flight when collaboration process rolled out)
 - [ ] Usability Testing Prep
 - [ ] Research Plan Review 
- [ ]  Information Architecture (IA) Request (N/A due to nature of work)
- [ ]  Analytics Request
- [ ] Contact Center Review
- [ ] Staging Review
- [ ] Privacy and Security Review (N/A due to nature of work)
- [ ] Full Accessibility and 508 Office Audit
- [ ] Post-launch Check-in
