### ISSUE TITLE
Partner request to add info to Choosing between urgent and emergency care

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#62731]
## Issue Description
Partners sent requested edits to our Choosing between urgent and emergency care page. We'll review their changes and send our edits for alignment with VA content standards. 

[IVC_COEDWebsiteUpdates_TrackedChanges.docx](https://gcc02.safelinks.protection.outlook.com/ap/w-59584e83/?url=https%3A%2F%2Fdvagov.sharepoint.com%2F%3Aw%3A%2Fs%2FOCCCommunicationsDirectorate%2FEQy9D8U5QJBImel_bw269DoBqd5hIuwoVWzM-HXwoVRHNQ&data=05%7C01%7C%7C6928f0de843346c0b58808db8e8d967c%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638260510989581956%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yKeJIFQZL4bmLJEUPsxkfwoR6JdJdcvZ8ZRjpalV1Zs%3D&reserved=0)

For the eligibility information they added, we'll add this existing approved sentence: "We may be able to provide or cover the cost of your emergency mental health care and up to 90 days of related services—even if you’re not enrolled in VA health care." Then link to [existing information on this page](https://www.va.gov/resources/getting-emergency-care-at-non-va-facilities/#emergency-care-eligibility-req) instead of duplicating here.

---
## Tasks
- [ ] Edit content (Laura)
- [ ] Send to partners for review (Laura)
- [ ] Copyedit and publish (Megan or Chelsea)

## Acceptance Criteria
- [ ] Page updates are live

**Comment by laurwill** [comment]
Noting that I emailed these partners to let them know we'll respond by 8/4.

**Comment by laurwill** [comment]
Update: I sent the draft changes to SMEs for review, with a couple remaining questions. Moving this to blocked till we get a response.

**Comment by laurwill** [comment]
@megzehn , SMEs approved changes. This page is ready to copyedit and publish: http://preview-prod.vfs.va.gov/preview?nodeId=37196

There are several new links and language updates in several sections. See revision history for updates. It would be great to get this live early next week, if possible. Thank you!

**Comment by megzehn** [comment]
Thanks @laurwill. I reviewed and published these changes. 

Heads up that I also updated the Veterans Crisis Line language to reflect the VCL website: added "select 1," removed the [outdated TTY number per this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52331), and tweaked the language on hearing loss to match our updated style guidance.
