### ISSUE TITLE
EVSS Migration - intenttofile deployment release plan and test run

### ISSUE THREAD

**Issue by mchae-nava** [department-of-veterans-affairs/va.gov-team#62747]
## Issue Description
This ticket covers the discovery and release plan to deploy the migrated endpoint to LH for Intent to File. The scope includes:
- Release plan - look at staggered release
   -  Can point to specific user through feature toggle
- Tasks in the ticket

**From 7/26**
- We've determined that pushing for for more testing resources from LH would be unproductive, instead we will shift our focus to testing with mock data and using a longer, close monitoring period in production. Added a task to document risks and how to plan to mitigate
- Adjusting the plan to identify and run a testing session with any internal prod users as the canary instead of 1% traffic

Plan document: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/disability-experience/team-docs/Release%20Plans/DBEX%20Intent%20To%20File%20Endpoint%20Migration%20Release%20Plan.md

---
## Tasks
- [x] Get Production Client ID from LH veteran verification API
- [x] Identify a prod user and do a test run
- [x] Test intenttofile endpoint using prod credentials from any client
- [x] Place the Client ID and RSA key in AWS parameter store
- [x] Confirm devops repository and K8 manifest repository has references to correct environment variable paths
- [x] Argo CD - Test intenttofile endpoint using prod credentials from any client
- [x] Confirm how other teams are batching the release
- [x] Identify acceptance criteria for a successful run
- [x] Establish Comms
- [x] Identify/document risks and mitigation

## Acceptance Criteria
- [x] Identify acceptance criteria for a successful run
- [x] Figure out how to monitor success(526ez form, submit workflow)
- [x] Release plan
- [x] Create Testrail testplan
- [x] Execute Testrun
- [x] Successful testrun
- [x] Create a ticket for starting the staggered release based on the plan
- [x] Risks have been documented

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
