### ISSUE TITLE
Copy of EVSS Migration - rateddisabilities deployment release plan and test run

### ISSUE THREAD

**Issue by mchae-nava** [department-of-veterans-affairs/va.gov-team#62746]
## Issue Description
This ticket covers the discovery and release plan to deploy the migrated endpoint to LH for rateddisabilities. The scope includes:
- Release plan - look at staggered release
   -  Can point to specific user through feature toggle
   -  
- Tasks in the ticket

---
## Tasks
- [x] Get Production Client ID from LH veteran verification API
- [x] Identify a prod user and do a test run
- [ ] Test rateddisabilities endpoint using prod credentials from any client
- [ ] Place the Client ID and RSA key in AWS parameter store
- [ ] Confirm devops repository and K8 manifest repository has references to correct environment variable paths
- [ ] Argo CD - Test rateddisabilities endpoint using prod credentials from any client
- [x] Confirm how other teams are batching the release
- [x] Identify acceptance criteria for a successful run
- [x] Establish Comms

## Acceptance Criteria
- [x] Identify acceptance criteria for a successful run
- [x] Figure out how to monitor success(526ez form, submit workflow)
- [x] Release plan
- [ ] Create Testrail testplan
- [ ] Execute Testrun
- [ ] Successful testrun
- [x] Create a ticket for starting the staggered release based on the plan

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mchae-nava** [comment]
Closing as a duplicated (accidentally created copy)
