### ISSUE TITLE
Present Approach to AuthN/AuthZ to AWG

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#62741]
# Description
Based on our research, and discussions with stakeholders and team members who have done similar work on VA.gov, we have developed a plan for how we would like to approach Authentication and Authorization for the creation of Preview Environments. Since this is a different from what is done elsewhere, we feel it's wise to vet this plan with the Architecture Working Group to ensure there are no unforeseen concerns or issues in this approach.

# Tasks
- [ ] Prepare materials for a presentation to the AWG
- [ ] Review/practice this presentation internally for comments/suggestions
- [ ] Schedule time to present to AWG
- [ ] Present to AWG
- [ ] Feedback/comments from AWG review have been documented

# Acceptance Criteria
- [ ] The plan has been presented to AWG
- [ ] Feedback has been collected

**Comment by JoeTice** [comment]
This task seems OBE, and we believe is no longer necessary, will reopen if that turns out not to be the case
