### ISSUE TITLE
[Design] Eligibility Page - Not eligible | Not in database

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#6275]
## User Story 
As a Veteran who authenticated but is not eligible to reorder because of eligibility date I would like to see the reason I cannot move on order in the forms flow 

## Goal
_Instructions on next steps to be able to reorder medical supplies if no eligible because not in DLC database, lacks eligibility code or no device on record 

---
## Tasks
- [ ] _Directions for how to qualify to reorder are to be provided my DLC
- [ ] _Page with instructions on next steps to be created

## Acceptance Criteria
- [ ] _For a given test user who is not eligible to reorder supplies, instructions on next steps needs to be provided 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by leahkeeler** [comment]
[https://app.zenhub.com/files/133843125/e848c2f7-5040-41a5-9a43-f81df9ba98fd/download](https://app.zenhub.com/files/133843125/e848c2f7-5040-41a5-9a43-f81df9ba98fd/download)

**Comment by rileyorr** [comment]
@mojaray2k & @mr0sari0 The Invision mockup and content can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-introduction-screen.md#use-case---veteran-is-not-eligible-for-the-benefit).
I didn't use the DLC's provided blanket statement because it was not written using plain language guidelines; I'll provide the document to Peggy during content review for her reference. As always, let me know if you have any questions!
