### ISSUE TITLE
Resolve Issues with BE Pod Failing to Start

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#62758]
# Description
The `vets-api` pod is displaying numerous errors such as --
```
FailedMount MountVolume.SetUp failed for volume "pki-tls-private-dir" : secret "vets-website-rework-pe-frontend-pki-tls-private-dir" not found
```
We need to resolve these errors so the BE pod and its resources can start successfully.

# Tasks
- [ ] Understand the root cause of the BE pod failures
- [ ] Describe a fix for the BE pod failures
- [ ] Implement the fix

# Acceptance Criteria
- [x] Preview environment backend pods start up successfully

**Comment by pjhill** [comment]
BE pod is now starting. However, the [status page](http://vets-website-rework-pe-fronten-dev-platform-api.vfs.va.gov/status) is indicated an issue is present --
`{"errors":[{"title":"Bad Request","detail":"\"vets-website-rework-pe-fronten-dev-platform-api.vfs.va.gov\" is not a safe host","code":"110","status":"400"}]}`

**Comment by pjhill** [comment]
Nevertheless, this can probably be closed since the BE pod _is_ starting.

**Comment by pjhill** [comment]
We have a BE pod successfully started `vets-api`. An issue with how `vets-api` is configured persists, but the BE pod is starting and reporting as healthy.
