### ISSUE TITLE
Change content of 'How do I apply?' section on the pension how to apply page

### ISSUE THREAD

**Issue by fred-khoury-oddball** [department-of-veterans-affairs/va.gov-team#62767]
### Issue Description 
Update the content on the pension how to apply page ( /pension/how-to-apply ) to the new content provided.

### Steps to reproduce
- Navigate to pension page ( https://www.va.gov/pension/how-to-apply )
- Observe the text in the 'How do I apply?' section
- There is text that says 'You can apply online right now.'
- There is a button that says 'Apply for Veterans Pensions benefits'
- There is a header that says: 'You can also apply:'

### Acceptance Criteria
- [ ] Remove the text that says 'You can apply online right now.'
- [ ] Remove the button that says 'Apply for Veterans Pensions benefits'
- [ ] Remove the header that says 'You can also apply.'
- [ ] Add an info alert above the 'By Mail' sub-header and beneath the 'How do I apply? ' header that contains and info icon and the following text 'Veterans Pension (VA Form 21P-527EZ) can not be currently completed online. If you started an online Pension application, you can sign in to view the draft. You will need to fill out a new form to apply by mail.'
- [ ] The 'sign in' text in the new info alert should be a link to the sign in modal

### Additional
- new copy text:
  -  Veterans Pension (VA Form 21P-527EZ) can not be currently completed online. If you started an online Pension application, you can sign in to view the draft. You will need to fill out a new form to apply by mail.
- link to mural: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1689262813123/cb880912d3f71ef79be0d63d0e61e306d1e6ae31?wid=0-1690316869607
### Current Result
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135056639/f4716850-03bc-47a3-9e0b-09d979f5cb4e)

### Expected Result
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135056639/d905c21e-239c-4f04-b0c0-f39477efbfd6)
