### ISSUE TITLE
Change content of 'How do I apply?' section on pensions eligibility page

### ISSUE THREAD

**Issue by fred-khoury-oddball** [department-of-veterans-affairs/va.gov-team#62773]
### Issue Description 
Update the content on the pension eligibility page ( /pension/eligibilty ) to the new content provided.

### Steps to reproduce
- Navigate to pension eligibility page ( https://www.va.gov/pension/eligibility/)
- Observe the text in the 'How do I apply?' section
- There is text that says 'You can apply online right now.'
- There is a link that says 'Apply for Veterans Pensions benefits' with a green close carrot icon

### Acceptance Criteria
- [ ] Remove the text that says 'You can apply online right now.'
- [ ] Remove the link that says 'Apply for Veterans Pensions benefits' and the green carrot icon
- [ ] Add an info alert above the 'By Mail' sub-header and beneath the 'How do I apply? ' header that contains and info icon and the following text 'Veterans Pension (VA Form 21P-527EZ) can not be currently completed online. If you started an online Pension application, you can sign in to view the draft. You will need to fill out a new form to apply by mail.'
- [ ] The 'sign in' text in the new info alert should be a link to the sign in modal

### Additional
- info alert copy text:
  - Veterans Pension (VA Form 21P-527EZ) can not be currently completed online. If you started an online Pension application, you can sign in to view the draft. You will need to fill out a new form to apply by mail.
- link to mural: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1689262813123/cb880912d3f71ef79be0d63d0e61e306d1e6ae31?wid=0-1690316870117
### Current Result
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135056639/119b82a8-50a3-4435-a316-d4770057bc1d)

### Expected Result
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135056639/00bba98a-1250-46b3-9cd1-f765f8e4b126)
