### ISSUE TITLE
Meet with MHV to discuss coordinator roles and potential test sites

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#62783]
# Use Case

As a supervisor of MHV coordinators or potential volunteer, I want to understand what the IPP flow is so that I can make an educated decision on whether I want to be part of the pilot.

As a designer for IPP, I want to understand the evironment in which MHV coordinators operate in so I can iterate on the pilot application to meet proofing agent volunteer needs

# Tasks

- [ ] Meet with Susan Haidary to walk through coordinator verification process 
- [ ] Create a journey map based on the coordinator verification process
- [ ] Inquire about MVP sites

#Acceptance Criteria

- [ ] Journey map is created and reflects coordinator process
- [ ] Potential MVP sites identified and connection has been established

**Comment by skirkman16** [comment]
duplicate
