### ISSUE TITLE
Change "feedback is due" language when closing touchpoint meetings

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#62795]
## User Story
As a Governance team member, I want the verbal communication to VFS teams at Collab Cycle touchpoint meetings to remain in a consistent voice so that VFS teams are not confused and/or misled.

Assignee: @CherylEvans 
Peer Reviewer: @erinrwhite 

## Description
Currently we communicate that "feedback is due" by end of next business day at the Design Intent meeting and End of Day at the Midpoint Review meeting. This is communicated out loud by the meeting host. However, this language makes it sound like we are asking the VFS team to provide feedback to us by that time, not that we will have our feedback at that time. The rest of the communication in the meeting is FOR the VFS team while this line is FOR Governance team. The voice has changed.

The purpose of this ticket is to modify the language to communicate the Governance will provide feedback by the specified date. Remove the "due" language.

## Impacted Artifacts
[Midpoint Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Moderator+Responsibilities)
[Design Intent - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Moderator+Responsibilities)

## Tasks
- [ ] TBD

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team no longer communicates "feedback is due" at DI and MPR touchpoints

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
Updated docs (these are links to the diffs):
[Midpoint review moderator docs](https://vfs.atlassian.net/wiki/pages/diffpagesbyversion.action?pageId=1821442052&selectedPageVersions=85&selectedPageVersions=86)
[Design intent moderator docs](https://vfs.atlassian.net/wiki/pages/diffpagesbyversion.action?pageId=1748336706&selectedPageVersions=78&selectedPageVersions=79)

I *think* this is everything - @CherylEvans, ready for your review. I welcome further clarification of this language!

**Comment by CherylEvans** [comment]
@erinrwhite Hi Erin. :-)
Here are my recommendations for the [Midpoint Review Moderator document](https://vfs.atlassian.net/wiki/pages/diffpagesbyversion.action?pageId=1821442052&selectedPageVersions=85&selectedPageVersions=86):

- Asynch review. No meeting will take place.
The Governance team will deliver their feedback by the end of the day today.

- If applicable, ensure that each practice area created feedback tickets and linked them to the Collaboration Cycle Request ticket as child tickets. If a practice area has no feedback, ensure they have checked the appropriate box for "[practice area] has completed the review."
The Governance team feedback is due by the end of the day of the Midpoint Review.

Here are my recommendations for the [Design Intent Moderator document](https://vfs.atlassian.net/wiki/pages/diffpagesbyversion.action?pageId=1748336706&selectedPageVersions=78&selectedPageVersions=79):

- Once everyone has shared, remind everyone that
the Governance team will deliver their feedback by the end of the next business day. Remind teams that they can access the Zoom recording anytime by following the link within the Design Intent section of their collaboration cycle ticket. Then, end the meeting.

- If applicable, ensure that each practice area created feedback tickets and linked them to the Collaboration Cycle Request ticket as child tickets. If a practice area has no feedback, ensure they have checked the appropriate box for "[practice area] has completed the review."
The Governance team feedback is due the day after the Design Intent by the end of the day.

I made a few additional changes to correct existing grammatical errors. I also updated the voice from passive to active.

Let me know if you have any questions or concerns. :-)

**Comment by erinrwhite** [comment]
@CherylEvans this looks awesome! Will incorporate.

**Comment by CherylEvans** [comment]
@erinrwhite That was quick! :-) Thank you, Erin!

**Comment by erinrwhite** [comment]
@CherylEvans I appreciate the quick review!

Changes published:
[Moderator responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Moderator+Responsibilities)
[Design intent moderator responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Moderator+Responsibilities)

**Comment by erinrwhite** [comment]
@CherylEvans Shira just noted that **you** were the assignee on this ticket, not me - I'm sorry to bogart this! Monday brain... 😵‍💫

**Comment by CherylEvans** [comment]
@shiragoodman @erinrwhite I saw that, too, but I didn't want to take the wind out of your sails after doing such a great job with the ticket. Lol. I figured what's done is done. Lol. It's all good. Thank you for being proactive, Erin. It's a rare and appreciated trait.

**Comment by erinrwhite** [comment]
Thank you! 😂 I'm going to close the ticket.
