### ISSUE TITLE
Add "Shadowing" to new Governance team member Onboarding documentation

### ISSUE THREAD

**Issue by CherylEvans** [department-of-veterans-affairs/va.gov-team#62815]
## User Story
As a new Governance team member, I want to shadow the senior team members as they work through their assigned tasks and responsibilities so that I have a more thorough understanding of the Governance team workflow.

Assignee: @CherylEvans 
Peer Reviewer: @erinrwhite 

## Description
We'd like to expand the Onboarding guidance doc to include Shadowing so that new team members know what's to come and what's expected. They're able to get hands-on experience supporting Governance team work.

## Impacted Artifacts

- [Onboarding](https://vfs.atlassian.net/wiki/spaces/PPST/pages/1953169694/Onboarding)

## Tasks
- [x] Create guidelines for new Governance team member "shadowing."
- [x] Determine the best place for these guidelines to live. I recommend placing it as an H2 heading before "Onboarding feedback."

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The Governance team Onboarding document contains guidance for new Governance team members to get them more quickly acclimated to our processes and standards.
- [x] The new Governance team member can manage their expectations more quickly and effectively.

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
@shiragoodman FYSA

**Comment by shiragoodman** [comment]
@erinrwhite FYI - I have added you as the peer reviewer for this ticket. Since you're the newest member of the team, I thought your "fresh eyes" would help us ensure we don't miss anything. Let me or @CherylEvans know if you have any questions.

**Comment by CherylEvans** [comment]
@erinrwhite I am ready for your peer review. Thank you for all of your comments and suggestions. :-)

**Comment by erinrwhite** [comment]
Looking great! Closing the ticket.

**Comment by shiragoodman** [comment]
hey @erinrwhite - heads up, the assignee is the person who is responsible for closing the ticket. not a big deal for this one, but in the future please make sure to not close the ticket if you're the peer reviewer. Thank you!

**Comment by erinrwhite** [comment]
@shiragoodman ah, got it! thanks!
