### ISSUE TITLE
Organize Platform website page data from GA

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#62822]
## Issue Description
We have a way to pull on a spreadsheet:

- all pages on the Platform website
- traffic view count per page
- URL structures

We now need a way to manipulate this data into a way we can visually identify what sections of the website should be prioritized for a content review based on:

- sections of the website (getting stated, developer docs, etc.
- traffic count

---
## Tasks
- [x] Export data into a Google Sheets from [this Google Analytics view](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w224573768p212889364/_u.date00=20230101&_u.date01=20230726&explorer-segmentExplorer.segmentId=analytics.pagePath&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=5000&explorer-table-dataTable.sortColumnName=analytics.pageviews&explorer-table-dataTable.sortDescending=true)
- [x] Organize data so we can filter it based on:
- page traffic since Jan 2023 until now
- which confluence space it falls under (getting started, developer docs, collaboration cycle, etc.)

- [x] Add a column a Subject Matter Expert for each page, leave blank for now

## Acceptance Criteria
- [x] We will have an artifact to show leadership what areas of the Platform website we will recommend as priority for a content review based on traffic count
- [x] We will have a way to identify and document a Subject Matter Expert to each page

## Artifacts

- [Link to Google Sheets](https://docs.google.com/spreadsheets/d/1FKam2tLzZ1utfwnREgsjxOIoapHZ3VsX1pXWsX8EcWI/edit?usp=sharing)
