### ISSUE TITLE
[bug spike] SC | Investigate new 422 unprocessable entity error

### ISSUE THREAD

**Issue by kylesoskin** [department-of-veterans-affairs/va.gov-team#62838]
## Value Statement
**_As a_** Veteran filing for a Supplemental Claim
**_I want to_** not get a 422 error when I try to submit
**_So that_** I can submit the form

---
## Background Context
https://vagov.ddog-gov.com/logs?query=service%3Avets-api%20%40payload.controller%3A%2ASupplemental%2A%20%40http.method%3APOST%20%40http.url_details.path%3A%22%2Fv1%2Fsupplemental_claims%22%20%40http.status_code%3A422%20&cols=%40name%2C%40http.status_code%2C%40payload.user_uuid&index=&messageDisplay=inline&sort=time&stream_sort=%40http.status_code%2Cdesc&viz=stream%201thanksgo-team-ad-hoc3%3A56&from_ts=1690204703275&to_ts=1690809503275&live=true

https://vagov.ddog-gov.com/apm/traces?query=%40_top_level%3A1%20env%3A%22eks-prod%22%20service%3A%22vets-api%22%20resource_name%3A%22V1%3A%3ASupplementalClaimsController%23create%22%20host%3A%22i-0d8adf162a270ba89%22&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&env=eks-prod&graphType=flamegraph&historicalData=true&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=time&spanID=403986048786114918&spanType=service-entry&spanViewType=logs&trace=93126e8c6c8a994b&traceID=2002329138610936373&start=1690651071822&end=1690651131822&paused=true

http://sentry.vfs.va.gov/organizations/vsp/issues/198994/?environment=production&project=3&project=4&query=user.id%3A9b36aa70526c48289cc81549a45dab62&statsPeriod=14d

Save-in-progress ID: `8340222`

## Acceptance Criteria
- [ ] Failures investigated
- [ ] Continued ITF failures should not block starting the form
- [ ] Veterans are not blocked from filing a Supplemental Claim 
- [ ] Monitoring is in place and adequate for catching blocking errors

## Out of scope
- Add here

## Tasks
- [ ] Dig into logs more
- [ ] Ensure appropriate logging & monitoring is in place in Datadog
- [ ] Create ticket to fix bug (or comment/link PR here if it is a quick-fix)

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
While on the phone, the veteran dug through some papers and found the [decision] date. Entered it correctly, and was then able to submit.
