### ISSUE TITLE
[FE] Add Translations

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#62847]
## Translated Content
- [Translated Spanish content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/translations/2023_Q4/LS-2022-0118394-B-SPA-FINAL_Modernized%20check-in%20Spanish.json)
- [Translated Tagalog content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/translations/2023_Q4/LS-2022-0118394-B-TAG-FINAL_Modernized%20check-in%20Tagalog.json)

## Tasks
- [ ] Add Spanish translated content to the appropriate json file
- [ ] Add Tagalog translated content to the appropriate json file
- [ ] Generate screenshots for English 
- [ ] Generate screenshots for Spanish 
- [ ] Generate screenshots for Tagalog
- [ ] Attach screenshots to this [ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64625)

**Comment by loripusey** [comment]
@lee-delarm6 Do we have the requested screen shots? I will need to send them to the State Department for QA purposes.

**Comment by lee-delarm6** [comment]
> @lee-delarm6 Do we have the requested screen shots? I will need to send them to the State Department for QA purposes.

Do they want to see them on the page in use, or in the translation file?
