### ISSUE TITLE
Document missing appts alert

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#62857]
## Task Description
Update our documentation with the "missing appointments" alerts for upcoming, past, and pending.

## References
- [Design file](https://www.figma.com/file/9ZOtrJqv7Ze4ptVHMtE1iJ/Alert-users-when-VAOS-can't-display-appointments?type=design&node-id=13-33&mode=design)
- [User flows](https://www.figma.com/file/xRs9s6QWoBPRhpdYCGc3cV/User-Flow?type=whiteboard&t=Gdd8VFGw69EQe05u-6)
- [Feature reference](https://www.figma.com/file/twogqAIoOL9WAFRqvUbwiS/VAOS-Templates?type=design&mode=design&t=Gdd8VFGw69EQe05u-0) (templates file)

## Acceptance criteria
- [x] User flows are updated
- [x] Feature reference (templates file) is updated
- [x] Copy docs are updated

**Comment by Cieramaddox** [comment]
Cross referenced in [this](https://app.zenhub.com/workspaces/appointments---productdesign-5fff340c2d80a4000fb6f69c/issues/gh/department-of-veterans-affairs/va.gov-team/60437) ticket

**Comment by melissa-lefevre** [comment]
I updated the [feature documentation in GH ](products/health-care/appointments/va-online-scheduling/feature-reference/appointment-lists)with links to the alerts in the [Copy docs ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/homepage.md#past-alert---generic-message-if-any-of-the-systems-are-unavailabe-vsp-vvs-and-hsrm) The content matches the updates designs in the template and user flow.
