### ISSUE TITLE
COE Data Request

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#62862]
## Issue Description
As the LGY Team, we are in the midst of testing a story where we no longer expect to receive data from our EMIS partner. We want to test the behavior from a VA.gov perspective as well to cover as many bases as we can. However, we need fresh, new data in order to do this.

The LGY Team needs 4 **Brand New records created on VA. GOV that have never existed in the LGY system**:
- Active Duty Tour From VADIR/ No Purple Heart data from EMIS (Purple Heart indicator is not set to true)
- Active Duty Tour From VADIR/ With Purple Heart data from EMIS (Purple Heart indicator is set to true)
- Reserve National Guard Active Duty Tour from EMIS/ No Qualifying tour from VADIR
- Reserve National Guard No Qualifying Tour from EMIS/ Qualifying tour from VADIR

The LGY Team also needs a spreadsheet that includes the following data for each record (to help with validation):

- Email and Password
- First name:
- middle name:
- Last name:
- gender:
- SSN: 
- Phone #:
- icn:
- edipi:

---
## Tasks
- [ ] Create 4 new records
    - [ ] Active Duty Tour From VADIR/ No Purple Heart data from EMIS (Purple Heart indicator is not set to true)
    - [ ] Active Duty Tour From VADIR/ With Purple Heart data from EMIS (Purple Heart indicator is set to true)
    - [ ] Reserve National Guard Active Duty Tour from EMIS/ No Qualifying tour from VADIR
    - [ ] Reserve National Guard No Qualifying Tour from EMIS/ Qualifying tour from VADIR
- [ ] Create spreadsheet with requested fields

## Acceptance Criteria
- [ ] 4 new records are created
- [ ] Spreadsheet with Veteran record info is created
