### ISSUE TITLE
Feedback portal log/review

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#62866]
## Purpose
HMW Portal submission --> action?

How/When should we review items submitted to the Feedback Portal?
Update: having an automated Domo dashboard eliminates this, unless team wants to take on addressing issues rather than presenting them

To make good on our bet for continuous feedback, the feedback must reach viable parties continuously as well.  What would be the best way for SDT to review the feedback as it comes in, and where/how should that get shared out?
-Constantly available repository?
-Directed communications to relevant team(s)?
-Who needs to see what? Page [here](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2737700945/Platform+Feedback+Portal+Log+Review).

### Bets:
-Teams are more likely to go to a Domo page (which many teams already use) to view these when they want to
-Seems like a good idea to also include these w/ Platform Satisfaction Survey readout

## Tasks
- [x] Decided on MVP being Airtable to Domo
- [x] decide whether we need to build out the airtable w/ additional functionality or references?
- [x] Get access to Domo Dashboard
- [x] Can hook Airtable data to Domo Dashboard?
- [x] create a test Domo page from Airtable data (many steps to learn [here](https://domo-support.domo.com/s/article/360043427613?language=en_US))
- [x] Prep and share [deck](https://docs.google.com/presentation/d/1DywD_d-YQpemaEbG4LOc7wHm9gPJa26abkhKBahkr9g/edit#slide=id.g243d846b8ce_0_18) for Demo Day
- [x] Get team feedback and revise
- [x] Share at Demo Day
- [x] [Draft Slack announcement](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2763587617/Feedback+Portal+Domo+announcement) to #platform-team
- [x] Share/announce resource

## Acceptance Criteria
- [ ] Resource is created
- [ ] Resource is publicized

**Comment by twoangstroms** [comment]
Took some support for the Analytics team but finally got some things sorted and made my first "card" in Domo (just a test; need to learn how to set up visualizations for what we want to present). I'll need to get y'all to request read access from that team.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFE0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bc35f3b837966e1be07ff1a0e65a4f0141ff227e/Screenshot%202023-08-24%20at%202.36.21%20PM.png)

**Comment by steel36** [comment]
@twoangstroms Can you clarify why there isn't a need to "Evaluate a method and frequency for SDT review" with Domo's use?

**Comment by steel36** [comment]
I see. The thinking this task came from was that we'd discussed we may want to review feedback submissions with some frequency and potentially share specific items w/ relevant teams.

**Comment by twoangstroms** [comment]
This ticket will roll over to the next sprint to rethink how to break out tasks and implement.

**Comment by twoangstroms** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdWRjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--19272cf4ebe5a5ccc3a8ee9744c5eaf10fd4ebd6/Screenshot%202023-08-31%20at%204.24.20%20PM.png)

**Comment by twoangstroms** [comment]
Ticket rolling over to next sprint to cover Demo Day demo
