### ISSUE TITLE
Review page and Confirmation page text updates based on paths

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#62860]
## Issue Description
DRAFT- mockups will be added

Three versions of the review page are needed:
- **Full FSR Path**
     -Keep Statement of Truth as is

- **Long Streamlined Waiver Path (Zoe)** 
  -Remove "My bankruptcy history" from Statement of Truth
  
- **Short Streamlined Waiver Path (Dan)**
  -Remove "My bankruptcy history" from Statement of Truth
  -Remove "and expenses" from "My household assets and expenses" from Statement of Truth

Two versions of the confirmation page are needed:

- **All Paths:**
  -Update [Print this page /Download component](https://design.va.gov/patterns/help-users-to/keep-a-record-of-submitted-information)

- **Full FSR Path**
  -Keep text as is

- **Long Streamlined Waiver Path (Zoe) and** 
- **Short Streamlined Waiver Path (Dan)**
  -Remove "What if I lose my job" blurb

---
## Tasks
- [x] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by amponce** [comment]
Hey, @Dr-Pongo is this work completed in your SW depends branch?  @HeatherRienks mentioned that it might already be completed or marked to be closed

**Comment by Dr-Pongo** [comment]
@amponce Still in progress! Should be marking ready for review shortly!

**Comment by HeatherRienks** [comment]
In progress once @Dr-Pongo's  #61842 ticket is merged.
