### ISSUE TITLE
FE | Profile | Generic Maint | Personal Info Updates to Helper Text

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#62876]
## Background
<details><summary>Originating issue</summary>

```[tasklist]
### Tasks
- [ ] #57097
``` 
</details> 
The Design work for this issue was completed in #57097

We need to complete the FE updates. 

- we will not display any FAQs when the error page loads (so no FE work needed there), and I've updated the Sketch files to reflect that
- we will keep the "fix an error" FAQ above the table, and move the "update legal name" inside the appropriate cell. The sketch files have been updated ([desktop example](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/dlVxdm3), [mobile example](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/4ajJxKZ)) and this is ready for a FE implementation ticket 🎉

## Tasks
- [x] update the FE to match the updated details in the sketch files
- [x] test 
- [x] Notify PM / Team so it can be validated 

## Acceptance Criteria
- [ ] FE is updated and deployed to production

**Comment by mtcA6** [comment]
The updates look good! 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/512c3f8c-2f79-42ed-9c0d-4d7c60575df6)
