### ISSUE TITLE
[FE] My VA: Implement GA event tags in "Benefit application drafts" links

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#62874]
## Background
Once we received guidance from the Analytics team we'll need to implement event tags on the links that live in the expandable/collapsable sub-menu on My VA in the Benefit Application Drafts section:

* Health care (https://staging.va.gov/health-care/ and https://va.gov/health-care/)
* Education and training (https://staging.va.gov/education/ and https://va.gov/education/)
* Disability compensation (https://staging.va.gov/disability/ and https://va.gov/disability/)
* Careers & employment (https://staging.va.gov/careers-employment/ and https://va.gov/careers-employment/)
* Pension (https://staging.va.gov/pension/ and https://va.gov/pension/)
* Housing assistance (https://staging.va.gov/housing-assistance/ and https://va.gov/housing-assistance/)
* Burials & memorials (https://staging.va.gov/burials-memorials/ and https://va.gov/burials-memorials/)
* Life insurance (https://staging.va.gov/life-insurance/ and https://va.gov/life-insurance/)
* Service member benefits (https://staging.va.gov/service-member-benefits/ and https://va.gov/service-member-benefits/)
* Family member benefits (https://staging.va.gov/family-member-benefits/ and https://va.gov/family-member-benefits/)

![Screenshot 2023-07-31 at 2 15 00 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/30c814e2-74ca-46a8-b8e6-8dafa0e6ba61)

## Tasks
- [ ] Implement event tags on the links listed above according to the guidance from the analytics team provided in #62875 
- [ ] Tag the analytics team in that ticket to request review/QA once implemented
- [ ] Move to validate and tag PM for final review

## Acceptance criteria
- [ ] Event tags exist on the links in the "Explore VA.gov" sub section

**Comment by ajakabcin** [comment]
we'll see what the analytics team says next Tuesday but it's possible we may not be able to get to this in this sprint if they're not able to provide the tag guidance as they have a backlog/other team requests ahead of ours.

**Comment by ajakabcin** [comment]
@allisonlu I'm going to pull this out of the sprint - we're going to run an experiment to hide this section for a bit (ultimately aiming to remove it entirely after we monitor search behavior). Going to put this in the backlog for now _in case_ we need to revisit.

**Comment by ajakabcin** [comment]
Closing this - we removed this sub section from My VA
