### ISSUE TITLE
Use Case Discovery - Next of Kin/Emergency Contact

### ISSUE THREAD

**Issue by A6-toma** [department-of-veterans-affairs/va.gov-team#62879]
## Issue Description
Conduct discovery research on migrating _Next of Kin (NOK) and Emergency Contact (EC)_  to VA.gov and determine how these fields might be useful for Veterans and VA staff.  

## Tasks
- [x] How does this field impact a user's experience (ensure we have a full understanding)? 

**Determine who might find these fields useful**
- [x] What problem was this field trying to solve?
- [x] How would a Veteran find these fields useful? 
- [x] How might these fields be used by VA staff/VA? 

**Technical research**
- [x] Where might this data be stored? 
- [x] Can it be accessed by other systems?
- [x] What happens when the data is updated?

**Define Next of Kin/Emergency Contact use cases**

## Acceptance Criteria
Use cases for the Next of Kin/Emergency Contact fields have been defined and documented.

**Comment by carafrissell1** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/tree/59d59574d8ba034f147e89d2537a7b71e80ee461/products/health-care/digital-health-modernization/mhv-to-va.gov/Next%20of%20Kin-Emergency-Contact

**Comment by MikeC-A6** [comment]
would like to understand - When a vet works with a MSA to update their NOK / EC, in what system does the MSA update that information in?  VistA?  Enrollment system?

**Comment by jonathanjnelson** [comment]
[Documenting findings in MD here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/Next%20of%20Kin-Emergency-Contact/overview-notes.md#check-in-experience-team)

**Comment by jonathanjnelson** [comment]
[Please see followup ticket here ](https://app.zenhub.com/workspaces/mhv-on-vagov-top-level-view-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/64873)
