### ISSUE TITLE
Collaboration Cycle for [Non-Disability Experience, Burial 530, Temporary Online Form Deactivation]

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#62889]
### VFS team name

Non-Disability Experience Team

### Product name

Burial 530 Digital Form

### Feature name

Temporary Online Form Deactivation

### GitHub label for product

burial, umbrella

## Kickoff questions

<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

July 2023

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

No

### Will your work involve changes to...

Static pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

No

### Do you need to capture any additional analytics or metrics?

No

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/Initiative%20Brief-527EZ%20and%20530%20Temp%20Deactivation.md

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Notify the Collaboration Cycle team of this ticket in the vfs-platform-support Slack channel.

- [X] I acknowledge that I must notify \#vfs-platform-support after submitting this issue.
Kickoff Slack Thread with VFS team:  https://dsva.slack.com/archives/CBU0KDSB1/p1690834867855249

</details>

### Sitewide CAIA Intake Request
<details>
  <summary>Toggle Sitewide CAIA Intake Request</summary>

##### VFS actions
- [x] Complete the [Sitewide CAIA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-CAIA-intake-request.2124906551.html)
- [x] Link to the Sitewide CAIA Intake Request ticket below
   - [Deactivate Burial](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62448#event-9901396761)

</details>

### Staging Review
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event with scheduled date/time in #vfs-platform-support ([see Slack Workflow User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html))
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [ ] I confirm the environment is available and test users have been provided.
- [x] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
 
**Staging Review artifacts**
  
See Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts). Platform findings are based solely on the staging URL and test users provided, as reviewed during the four days before the Staging Review meeting. Any test cases not covered or any ongoing work taking place during the review period may not be reflected in those findings.  

**Product artifacts** 
- [ ] [Staging URL](https://staging.va.gov/burials-and-memorials/application/530/introduction)
- [ ] Specify which pages are included in the review: Form Summary Page
- [ ] [Staging test user information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/530-staging-test-accounts-accessible.md)         
  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)
   - [Burial | Build Review Page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63627)
  
**IA artifacts**
- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) of the findings you received, including an IA review document or intake form.
   -[[Epic] Burial 530 Deactivation from Benefits and Claims](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62448#top)

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [ ] [Regression test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-regression-test-planRegressionTestPlan)
- [ ] [Test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-test-planTestPlan)
- [ ] [Coverage for References](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [ ] [Summary(Defects) reports](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [ ] [E2E tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-e2e-test-participationE2ETestParticipation) (provide a link to the product’s code)
- [ ] [Code coverage](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-unit-test-coverageUnitTestCoverage) (provide a link to the product’s code)  
  
**Accessibility artifacts**
  
- [ ] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D). For details, see [Prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).
  
##### Platform actions
- [X] [First Slack thread](https://dsva.slack.com/archives/C057W3N9K2S/p1693414347638429), [Reschedule Slack request](https://dsva.slack.com/archives/C057W3N9K2S/p1694722103698889)
- [X] Meeting date/time: ~~September 7, 2023 at 3:30 p.m. Eastern~~ Rescheduled: September 21, 2023 at 3:30pm ET

##### Platform actions

- [x] Update this ticket with the Zoom recording
  - [Recording URL](https://oddball-io.zoom.us/rec/share/Ui3DVoazJU_mHuAeJIkOIZXRE54M_6HHm9M3iryp8ksrZk1qdvhNJVxljTDFaVMt.Rs2bWZGqucE-4Hrf)
  - Password: `9kP^94eA`
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

**Comment by steele-lm** [comment]
@juliepedtke @jstrothman @fiorella-io

**Comment by steele-lm** [comment]
@erinrwhite There are two components to this staging review (pension and burial pages), and I confirmed today that only the burial component will be ready for review on 9/7. Should we hold the 9/7 date to review that component or reschedule for a future date when both components can be reviewed in tandem?

**Comment by erinrwhite** [comment]
@steele-lm No problem. We can proceed with the burial component on 9/7, then review the second component later on. If your team would prefer to have them reviewed together, we can reschedule.

**Comment by shiragoodman** [comment]
thank you for responding @erinrwhite !

@steele-lm  - I'll echo what Erin said - this is perfectly fine! Could I ask you to please confirm that yes, you plan to hold 2 staging reviews? If so, we will want to make sure this ticket get's updated so we can give you space to schedule the 2nd staging review. Thank you!

**Comment by steele-lm** [comment]
@shiragoodman We're going to have to reschedule. Apologies! The GitHub PR issues are slowing things down enough where I'm not confident all the required teams will have a chance to review the PR before the end of the day. How should I go about rescheduling?
