### ISSUE TITLE
[CAIA a11y Research] Streamlined Waiver from Debt Resolution - Supporting AT Sessions (Oct. 24, 2023 start)

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#62881]
## Research Timeframe
Initial Dates: ~October 18-25, 2023~
`Revised Start Date (per Charlotte on 10/16/2023) will be Tues. October 24, 2023`

## CAIA Support
**Support goal:** assist users with assistive technology, should any issues take place, during the sessions. Identify and document any accessibility-related issues encountered in the user testing sessions. 

<details><summary>Toggle to view CAIA Support such as assignees</summary>

- [x] Sara @sara-amanda 
- [x] SK @SarahKay8 
- [x] **`Pending` session times for dates provided:** ~Oct. 18 - 25, 2023 (ballpark)~ **Revised start Oct. 24, 2023** 
- [x] Added date range to the [CAIA Capacity Calendar](https://calendar.google.com/calendar/embed?height=600&wkst=1&bgcolor=%23ffffff&ctz=America%2FNew_York&mode=WEEK&src=Y19mOTgyMzUwZmM3M2E4MTYyYTEwODhhYjE0ZDAwZGQzNzMzNWIyYjU1OWE2MGQ2YjY3ZWI4MDIxNDE2ZjgxYzJhQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20&color=%23616161).
- [x] Adding new date range to reflect new start to the Capacity Calendar on 10/17/2023 (study starts 10/24/2023) The study will run through Nov. 3, 2023. 
</details>

## About the Debt Resolution Team

<details><summary>Toggle to reveal team information</summary>

- Team name: Debt Resolution
-	OCTO-DE product owner:  Denise Coveyduc
-	Product manager: Tom Davis
-	Designer: Megan Gayle, Joseph Lee 
- Researcher: Charlotte Cesana
- Accessibility specialist: N/A
- Content writer: Danielle Thierry has been assisting
-	Slack channel: benefits-debt-resolution
</details>

## CAIA Support Request

<details><summary>Toggle to reveal the full support request</summary>

### Original Ticket 7/31/2023
We’re updating the FSR form and want to confirm we’re doing it correctly and it meets accessibility standards.

### Ticket Adjustments
Because this was to be a research ticket, CAIA will add the `Research Ticket`contents, below.

### General Awareness
The Debt Resolution Streamlined Waiver from Debt Resolution is `skipping Midpoint`.

### Calendar checking
**Description**: Before moving forwards, please [review our capacity calendar for CAIA availability](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/Chicago)
- [ ]  Based on this calendar, confirm we have specialists who can support your study in your desired timeframe
- [ ] Confirm you are filing this support ticket at least 1 week in advance of said timeframe, so we have enough heads up to provide support
### Have you reviewed the CAIA capacity calendar?
**Make sure your research's timeframe occurs when we have time to support y'all**
- [ ] Yes, we have reviewed the CAIA capacity calendar and can confirm specialists are available to support in our research timeframe
### Timeframe
**When is the timeframe for your testing?** 
- ~The 3rd week of August, when a production prototype is ready.~
- **Initial Ballpark Dates**: ~October 18-25, 2023~
    - [Per Charlotte on DSVA Slack 9/12/2023](https://dsva.slack.com/archives/C057UB3TKBJ/p1694533089997389)
- **Revised Dates**: **October 24, 2023 start**
    - 12 p.m. EST to 5 p.m. EST (9 a.m. PST to 2 p.m. PST) 

        > The study has been delayed, because we were waiting for the test staging account to be created. It has been created now, and we are waiting for Shane to kick off the study. We expect that the study will start next week. Does that timeline still work for you guys? - [Charlotte via DSVA Slack on 10/16/2023](https://dsva.slack.com/archives/C057UB3TKBJ/p1697475768468889)

### Supporting artifacts (if any)
**If relevant, please provide supporting artifacts as available**
- [x] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/streamlined_waiver/product_outline.md)
- [x] [User flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1678973946956/6f3bb65fe1ccc2b9d3bc38cd24cd09e74d18d778?sender=u700b91ee9a6e702249787681)
- [x] [Lo-Fi Prototype or mockups](https://www.sketch.com/s/f8f84ed8-16b1-4caa-b88a-19acd400ba7e)
- [ ] **Pending** Production Hi-Fi Prototype for AT testing
- [x]  `RCVD 10/2/2023` [Research plan]([Insert URL here between the parenthesis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/streamlined_waiver/accessibility_research/research-plan.md))
- [x] `RCVD 10/2/2023` [Research conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/streamlined_waiver/accessibility_research/conversation-guide.md)
- [ ] [Epics/issue that may be helpful](Insert URL here between the parenthesis)
- [X] Previous Research Ticket: [CAIA A11y Research]: Debt Resolution, Enhanced Financial Status Report #58211
- [X] Collab Cycle Ticket(#57105) - April 2023

## Research Next Steps
**Complete these after submitting this ticket with your CAIA specialist**
- [x] Post a link to this ticket in the accessibility-help Slack channel and tag Terry Nichols.
- [ ] Provide the research plan, conversation guide and link to prototype being tested in advance of testing.
- [ ] Your team's researchers and observers read through platform guidance on research with assistive technology users
- [ ] CAIA Specialists are assigned to your research, be sure to add the respective a11y specialist(s) to your session invites (include the Zoom or Teams link). 
- [ ] CAIA Specialists review your conversation guide and research plan
- [ ] Provide specialists your participant details like skill level, operating system, assistive tech used, browser
- [ ] CAIA specialists will provide you an optional feedback form to let us know how we can support y'all better into the future.
- [ ] CAIA Specialists create a research notes template
- [ ] CAIA Post research, specialists will add accessibility findings to your research folder
     
### Which are you doing?
- [ ] **Launching a new** page, tool, form, or app
- [X] **Making changes** to an existing page, tool, form, or app - We are updating the flow of the FSR form.

### Types of Support
**What areas does your team need support in? Check all that apply.**
#### Content
- [ ] Collaboration on content written by your team’s dedicated content writer 
- [ ] Collaboration on content if your team does not have a dedicated content writer
#### Accessibility
- [X] **Accessibility review of wireframes and/or prototypes**
- [ ] Accessibility issue (general request)
- [ ] Accessibility PDF review request
- [x] Accessibility user research support (research ticket contents now embedded in this ticket)
- [ ] DST component or pattern 
- [ ] Something else 
#### IA
- [ ] User Flows
- [ ] Page placement
- [ ] Object-Oriented UX (OOUX) support
- [ ] URLs
- [ ] Breadcrumbs and Left Nav placement
- [ ] Redirects
#### Multilingual content
- [ ] Translating content
 
## Timeframe
_We guide and work alongside teams across nearly every OCTO digital product. We also work with partners across VA to lead content migration and manage all unauthenticated content on VA.gov. And we're always working to expand the VA.gov content style guide and our IA and accessibility documentation. We need to prioritize all intake requests based on our overall workload and VA and OCTO priorities._

_Tell us about your product's timeline. And we'll work with you to meet timeline needs as best we can._

### Have you worked with CAIA before? 
  - [X] Yes - this is a continuation of the April 2023 research.
  - [ ] No

### What's your team’s next step and its timing?

- **Our next step is user testing with prototypes (planning to begin on August 2, 2023 - not AT - study is complete)** ....
- **Provide date if available**: Accessibility study testing is planned for September, per Charlotte. 
- Refer to [planning ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/63722)

#### Timing for your next step: 
  - [ ] Next week
  - [ ] This month
  - [x] Next month (**~September~ October*)
  - [ ] This quarter
  - [ ] Next quarter
  - [ ] 6 months
  - [ ] 1 year

### Is this timing related to a specific event or Congressionally mandated deadline?
  - [X] Yes
  - [ ] No

### If you're conducting research, when is that starting? 
**Provide date if available:** ~The third week in August, per Charlotte.~
  - [ ] This week
  - [ ] This month
  - [x] Next month `Revised to October 24, 2023`
  - [ ] This quarter
  - [ ] Next quarter
  - [ ] 6 months
  - [ ] 1 year

### Will you release this new product incrementally (for example, release to 25% of users to start)? 
  - [X] Yes
  - [ ] No
 
**Note**: _If you checked yes, we’ll reach out to discuss details about the content in the react widget (we use these widgets to display entry points for new products to a certain percentage of users who visit our static pages)._
  
### When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
- **We expect to launch our product to 100% of users on:** 08/31/2023
  
### Will this work be going through the Collaboration Cycle?
- [X] Yes 
- [ ] No

### If no ...
- Skip to the _supporting artifacts_ section, below.
 
#### Please provide the link to your Collaboration Cycle ticket: 
- **Ticket (number)**: #57105 
- **Collab. Cycle Ticket Opened (date)**: 04/19/2023
 
#### Please check all of the phases in the Collaboration Cycle you have completed: 
- [X] Design Intent
- [ ] Midpoint Review - 👉 **Note: we opted to skip this optional touchpoint** 👈 
- [ ] Staging
 
##### Design Intent
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [X] Unknown at this time
##### Midpoint - **SKIPPING MIDPOINT**
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [X] Unknown at this time
##### Staging
- [X] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
</details>
  
## Supporting artifacts

<details><summary>Toggle to reveal the supporting artifacts</summary>

*Please provide links to supporting artifacts as available.*
- **Product outline**:https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/streamlined_waiver/product_outline.md
- **User flows**: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1678973946956/6f3bb65fe1ccc2b9d3bc38cd24cd09e74d18d778?sender=u700b91ee9a6e702249787681
- **Prototype or mockups**: https://www.sketch.com/s/f8f84ed8-16b1-4caa-b88a-19acd400ba7e
- **If this is in Sketch, which version or specific page should we focus on?**
- **Content source of truth**:
- **Research plan:** 
- **Any epics/issues that may be helpful**:
- **Link to testing accounts** (please do not paste them in this ticket): 
</details>

## Additional Support

<details><summary>Toggle to reveal additional support available</summary>

#### Have you already worked with someone from OCTO leadership?
- [X] Danielle
- [ ] Beth
- [ ] Mikki
- [ ] Martha

#### How do you plan to work with us on this request?
- [ ] I’ll take this to Beth or Danielle’s office hours.
- [ ] I’d like to schedule time to talk about this.
- [X] Let’s work async and meet as needed.

 
### Accessibility Help in Slack
The [#accessibility-help channel](https://dsva.slack.com/archives/C8E985R32) in the DSVA Slack, is also available to you as a resource. Everyone is welcome to ask questions or get help from our a11y (accessibility) specialists. Tag `@Terry Nichols` to get a11y help asap.

</details>

## Next steps

<details><summary>Toggle to reveal next steps</summary>

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag `@Terry Nichols`.**

- If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
- If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)
 
 - If you are creating an [experimental design,](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) please [also contact the DST. ](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)

- If you are requesting [a11y support for user research,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name) please complete this form, next. 
</details>

```[tasklist]
### CAIA Tasks
- [x] **DRAFT** [CAIA a11y Research] Streamlined Waiver Debt Res.: [Research Deliverable from CAIA a11ys](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/drafts/2023-Oct-Debt-Resolution-Streamlined-Waiver-accessibility-findings.md)
- [x] **DONE** [CAIA a11y Research] Streamlined Waiver Debt Res.: [Review Research Documentation in GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/streamlined_waiver/accessibility_research)
- [x] **DONE** [CAIA A11Y Research] Streamlined Waiver Debt Res.: [Participate in AT Sessions](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62881#issuecomment-1773459258)
- [x] **DONE W/ UPDATES** [CAIA A11y Research] Streamlined Waiver Debt Res.: Update [Capacity Calendar](https://calendar.google.com/calendar/embed?height=600&wkst=1&bgcolor=#ffffff&ctz=America/New_York&mode=WEEK&src=Y19mOTgyMzUwZmM3M2E4MTYyYTEwODhhYjE0ZDAwZGQzNzMzNWIyYjU1OWE2MGQ2YjY3ZWI4MDIxNDE2ZjgxYzJhQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20&color=#616161) with AT Sessions
```

**Comment by sara-amanda** [comment]
## CAIA Update on Ticket Timing

I spoke with @charlottecesana via [Slack](https://dsva.slack.com/archives/C057UB3TKBJ/p1690837954227679) on 7/31/2023
### Prototype Status
- The current prototype is in UX Pin, and does not support screen readers.
- They will be testing the "Streamlined Waiver Experience" with users of Assistive Technology, such as screen readers in future sessions. 
- They would like support on screen reader testing once the full experience is ready in production.
### Timing of Testing
- The full experience is scheduled to become ready in production around the 3rd week of August.
- @charlottecesana, please reach out to us, when you are ready and we will update this ticket accordingly. 
### CAIA Notes
- Placing in our `backlog` for now. 
- Updated `start date` to reflect the 3rd week in August. 
- Pending additional information from the Debt Resolution team. 
- Updating ticket title as well. 

cc: @SarahKay8 @AngelaFowler82 @coforma-terry

**Comment by HeatherRienks** [comment]
Thank you @SarahKay8 - we appreciate it! We are trying to get this on your radar, although we are not ready yet!
cc: @Tom-Davis

**Comment by charlottecesana** [comment]
Thank you, @sara-amanda - we look forward to collaborating in a few weeks!

**Comment by charlottecesana** [comment]
As discussed and confirmed, we plan to prepare for the study in early September. I have spoken to @AngelaFowler82, who might be able to help consult and guide us on this study. I have also spoken to @sara-amanda, who has confirmed she will be available. Please refer to our planning ticket #63722 for more details. 
@denisecoveyduc @HeatherRienks @Tom-Davis @josephrlee @mgleo

**Comment by sara-amanda** [comment]
## CAIA Update

### Next Steps
[c/o Slack thread on 9/5/2023 with Charlotte Cesana](https://dsva.slack.com/archives/C057UB3TKBJ/p1693949150676239)

- [ ] Removing from `backlog` and putting` in progress` 9/6/2023 @coforma-terry 
- [ ] @charlottecesana is writing an adapted study plan and conversation guide. 
- [ ] CAIA Assistance with this study @sara-amanda and @SarahKay8 
- [ ] @charlottecesana will set up a few meetings before the study in order to prepare
- [ ] Links needed to complete an initial accessibility audit, before the user interviews in order to make the most of the sessions (to be completed by @sara-amanda and/or @SarahKay8).

**Comment by sara-amanda** [comment]
## Revised Timeline for Study // CAIA Update

### Study Starting: Oct. 24, 2023

> The study has been delayed, because we were waiting for the test staging account to be created. It has been created now, and we are waiting for Shane to kick off the study. We expect that the study will start next week. Does that timeline still work for you guys?- Charlotte Cesana [10/16/2023 1:02 PM](https://dsva.slack.com/archives/C057UB3TKBJ/p1697475768468889)

> **Update**: Shane approved the research, and the study will being Tuesday 10/24 - Charlotte Cesana [10/16/2023 1:12 PM](https://dsva.slack.com/archives/C057UB3TKBJ/p1697476329845299)

### CAIA Capacity Calendar Holds Updated
@charlottecesana I have updated our [Capacity Calendar](https://calendar.google.com/calendar/embed?height=600&wkst=1&bgcolor=%23ffffff&ctz=America%2FNew_York&mode=WEEK&src=Y19mOTgyMzUwZmM3M2E4MTYyYTEwODhhYjE0ZDAwZGQzNzMzNWIyYjU1OWE2MGQ2YjY3ZWI4MDIxNDE2ZjgxYzJhQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20&color=%23616161) with the start date, and an end date of 10/31/2023. Please advise if that needs to be adjusted.  

### Sessions (Pending)

- [ ] Pending calendar invites
- [ ] Pending CAIA assignees to timeslots 

### Research Artifacts Received

- [Streamlined Waiver Accessibility Research Folder on GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/streamlined_waiver/accessibility_research)
- [Research Plan and Conversation Guide provided via DSVA Slack on 10/2/2023](https://dsva.slack.com/archives/C057UB3TKBJ/p1696282012502519)

^Updates reflected in this ticket.  @charlottecesana @SarahKay8 @AngelaFowler82 @coforma-terry

**Comment by sara-amanda** [comment]
## CAIA Research Support

### Invites Received (10)
**A checkmark indicates slot can be attended for AT/User Research a11y Support.**
- [x] Tuesday, Oct. 24, 2023 from 12-1:30 p.m. Eastern @sara-amanda 
- [ ] Tuesday, Oct. 24, 2023 from 2:30-4:00 p.m. Eastern `AVAILABLE SLOT`
- [ ] Wednesday, Oct. 25, 2023 from 12:30-1:30 p.m. Eastern `AVAILABLE SLOT`
- [x] Wednesday, Oct. 25, 2023 from 2:30-3:30 p.m. Eastern @sara-amanda 
- [ ] Thursday, Oct. 26, 2023 from 3:30-5:00 p.m. Eastern `AVAILABLE SLOT`
- [x] Friday, Oct. 27, 2023 from 3:30-5:00 p.m. Eastern @sara-amanda 
- [x] Monday, Oct. 30, 2023 from 1:00-2:30 p.m. Eastern @sara-amanda 
- [x] Tuesday, Oct. 31, 2023 from 12-1:30 p.m. Eastern @sara-amanda 
- [ ] Wednesday, Nov. 1, 2023 from 2:30-4:00 p.m. Eastern `AVAILABLE SLOT`
- [x] Friday, Nov. 3, 2023 from 1:00-2:00 p.m. Eastern `AVAILABLE SLOT`

### CAIA Availability

Due to an off-site meeting, part of the CAIA Team will be out of the office the week of October 23, 2023, which will impact CAIA availability for Assistive Technology/User Research support. 

Please know that we will do everything that we can to support as many sessions as possible. 

### CAIA Capacity Calendar

The scheduled dates and invite information has been added to the CAIA [Capacity Calendar ](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/Chicago). 

@SarahKay8 @coforma-jamie @coforma-terry @charlottecesana @AngelaFowler82

**Comment by charlottecesana** [comment]
Hi @sara-amanda thank you for the update. Looking forward to the study next week.

**Comment by sara-amanda** [comment]
## CAIA Testing Resources
### Notes and Access
- 📄 [CAIA Raw Note-taking Document](https://docs.google.com/document/d/13VVq1Q_lZRujD6yfjVryUOqrsH1qreX0KkSZJ2p60ek/edit?usp=sharing)
- 🔗  [Staging URL](https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/introduction)
### Debt Resolution Team
- [Conversation Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/streamlined_waiver/accessibility_research/conversation-guide.md)
- [Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/streamlined_waiver/accessibility_research/research-plan.md)
### Platform Resources
- [VA Testing your prototype with assistive technology users](https://depo-platform-documentation.scrollhelp.site/research-design/testing-your-prototype-with-assistive-technology-u)
- [VA Screen Reader Checklist](https://depo-platform-documentation.scrollhelp.site/research-design/screen-reader-checklist)
- [VA Experience Standards](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/va-gov-experience-standards)
- [VA Severity Rubric](https://depo-platform-documentation.scrollhelp.site/developer-docs/accessibility-defect-severity-rubric)
