### ISSUE TITLE
Prep first workshop of Devs to clarify forms system and customization

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#62883]
## Purpose
We seem to be lacking in detailed feedback on how the forms system, design patterns, and customization all come into play.  We could meet w/ devs only to have them lay out their approach to this; the phases and tasks involved.

## Tasks
- [x] Draft and send recruiting message to Frontend Devs we know of
- [x] Draft and send recruiting message to #vfs-frontend
- [x] prepare [Doodle poll](https://doodle.com/meeting/organize/id/ax1wr8qb) to find times to meet
- [x] Schedule workshop
- [x] prepare [questions list](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2727641113/Devs+Workshop+-+questions+topics)
- [x] prepare [conversation guide](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2727182443/6th+Workshop+VFS+FE+Developers+Conversation+Guide+-+Forms+Digitization+Research)
- [x] prepare [Mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1691435133257/e38c858ffbb2e0c28e00774f8d1bd690209664ea?sender=u9ea6bd3ca12795949b606150)

## Acceptance Criteria
- [x] conversation guide is ready
- [x] mural is ready
