### ISSUE TITLE
[Design][FE] 10-10EZ - Update upload discharge paper instructions 

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#62886]
## Issue Description
History:
- [Discovery ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49495) on updating upload pattern to new design system guidance
- Reviewed with content support
- Content recommendations in this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60053#issuecomment-1646122222)

Tasks
---
## Tasks
- [ ] Update Sketch design files and add links/images to this ticket
- [ ] Update staging/production to align with content

## Acceptance Criteria
- [ ] Content used for file upload pattern is using the latest design system and content guidance
---

**Comment by hdjustice** [comment]
Holding on this until we touch base with Aliyah after EZR stuff is "done"

**Comment by hdjustice** [comment]
Component has been updated in DST several times since this ticket. Not needed any longer
