### ISSUE TITLE
[BE] My VA Benefit Application Drafts: Technical discovery on "SiP" process

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#62897]
## Background
Following up from Angela's work on the benefit application drafts section documentation ([60510](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60510)), it was determined that the current process to configure a form be as "save in progress" (SiP) is not as streamlined as it could be. We want to do some technical discovery on how to automate that process so that new forms can easily be added/configured as SiP and therefore seamlessly appear in our section on My VA without any additional heavy lifting.

Comment [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60510#issuecomment-1658652021) for additional context. 

## Tasks
- [ ] Consult with Adam or Allison for additional background on the SIP configuration
- [ ] Create a brief writeup outlining your findings and recommendations ([previous example here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/claim-status-lighthouse-migration/technical-discovery.md)).
- [ ] Share with another dev for review

## Acceptance Criteria
- [ ] We have a technical discovery document outlining findings and recommendations - for now let's put it under My VA engineering docs in GH ([path](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/engineering-docs))

## Resources
- [Platform SiP documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-set-up-save-in-progress-si)

**Comment by ajakabcin** [comment]
@dellerbie this is really great - thank you for diving into this and pulling it all together! I made one minor edit - I formatted your proposed solutions into a table to better compare across the three and added a column for LOE (should we pursue this further).

We can discuss more in refinement this afternoon, but I think my only question is shared by you - how much of an issue is this for folks? Is it more of a matter of people not knowing there's an extra step or is it that difficult? Also, is My VA the only product that leverages SiP?
