### ISSUE TITLE
Research solution to use of build-time variables

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#62904]
# Description
Given that --
1. API_URL must be specified at build time for `vets-website` and `content-build`
2. The symlink to `vets-website` built content is created when the build script for `content-build` is run
3. BASE_URL which affects some of the links on the home page is specified at build time
4. EFS volume File I/O is a significant bottleneck and makes generating the build on container start too slow
5. Input from Kyle and other DevOps SMEs indicates that the AWS Datasync product has significantly higher File I/O capacity
6. CI pipeline currently generates 3 builds each time --
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/400527e9-d00f-4ce6-847d-73bb79a0c750)

We need to research potential methods for generating the `content-build` with these values in place outside of the container start script. Some ideas from past brainstorming are --
1. Generate a 4th build when CI runs and store it in S3 alongside the other builds. Then we can sync that to the EFS volume at the expected path using Datasync
2. Refactor the build scripts to abstract these values to environment variables that are determined at deployment time

# Tasks
- [ ] Brainstorm and discover alternative solutions to the two proposed in this ticket description
- [ ] Research the two alternatives in the ticket description
- [ ] Determine which alternative has the highest likelihood of success in a reasonable timeframe

# Acceptance Criteria
- [ ] A research document is available in the team confluence space
- [ ] A decision log involving key stakeholders has recorded the team's decision for the chosen alternative in the Confluence space

**Comment by JoeTice** [comment]
Pausing this task based on new work being done by another team related to content build, additional conversations will be had with the team and then reassessing.

**Comment by JoeTice** [comment]
These tickets are OBE as our approach is shifting, closing these tickets to reflect that.
