### ISSUE TITLE
Research issue w/ PVC path changes

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#62902]
# Description
It appears that when a preview environment is created or if it is deleted and then re-created from its values file, a new persistent volume claim is created for that PE. When this happens, the PVC appears to create a new directory on the EFS volume. Containers that mount the PVC do not have access to directories outside of this newly created directory. In other words, it appears that this new directory on the EFS volume is root for containers within that preview environment. For example, in the attached image, each of these directories `pvc-blah-blah` has been created when a PE app was created from a values file.

![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/4f61feee-b9db-4141-82c9-ef02c0278c08)

The problem is that when the FE container starts and attempts to navigate to a path that contains the staged `content-build` it can not get there because the root directory for the EFS volume does not contain the build path.  Instead, the build would have been staged in some directory at a lower level then the newly created path for the PE's PVC.

# Tasks
- [ ] Research PVC capabilities
- [ ] Research our implementation of PVC
- [ ] Determine whether we can change how PVCs are operating so that they do not create a new subdirectory on the EFS volume each time
- [ ] If we can't change how PVCs operate then research and propose a workaround that will allow us to operate an automated system

# Acceptance Criteria
- [ ] We have documented a proposed change to how PVCs are configured
- [ ] [OPTIONAL] We have documented a proposed workaround that accommodates the existing configuration of PVCs and allows FE containers to navigate to a staged `content-build` and use it

**Comment by JoeTice** [comment]
These tickets are OBE as our approach is shifting, closing these tickets to reflect that.
