### ISSUE TITLE
Experience a DI meeting (virtually)

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#62929]
## Purpose
Let's review the VFS member’s experience as a complete newbie by watching recorded meeting. 

Be sure to approach it as if it's your own, noting feelings and uncertainties.

## Tasks
- [x] Reach out to Governance to gain [access to representative sessions](https://dsva.slack.com/archives/CJRQ85PQB/p1692291868436479). (Taylor)
- [x] View the session taking note of the following:
-  pain points
-  methods to simplify
-  ways to improve absorption
-  ways to improve buy in 
- [x] Synthesize [here](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2746122282/DI+Meeting+Observations+Synthesis)
- [x] Record findings
- [x] If we think additional learnings are needed, we may want to attend a live session.

## Acceptance Criteria
- [x] The above factors are documented

**Comment by twoangstroms** [comment]
@steel36 You mentioned in standup (7 Sep) that there was a task involving tickets related to the DI, but I'm not sure what you mean, aside from what was documented in the synthesis document?

**Comment by steel36** [comment]
I was referring to Shira's ask in this comment: https://vfs.atlassian.net/wiki/spaces/SDT/pages/2746122282/DI+Meeting+Observations+Synthesis#Section%3A-Feedback-(Governance-%2B-PO)

**Comment by twoangstroms** [comment]
Ah, thanks. I am behind on reviewing the DI docs and comments in Confluence, so I hadn’t gotten to that yet and thought I heard you say it was a task in the ticket. (Testing if replying to emails works)


Dan Turner

Sr. UX Designer II, Ad Hoc
***@***.***

￼

**Comment by steel36** [comment]
I did receive the reply via email.
