### ISSUE TITLE
Resolve FE/BE Communication Issues

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#62922]
# Description
There are some issues with our `vets-api` implementation. Attempting to use applications in the FE results in some defects surfacing in the console.
1. 
```
WebSocket connection to 'ws://localhost:3001/ws' failed: 
WebSocketClient @ WebSocketClient.js:16
initSocket @ socket.js:21
(anonymous) @ index.js:273
(anonymous) @ web-components.entry.js?t=1690566134453:52060
(anonymous) @ web-components.entry.js?t=1690566134453:52100
```
2. 
```
instrument.js:109 [webpack-dev-server] 
Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
isTrusted: true
bubbles: false
cancelBubble: false
cancelable: false
composed: false
currentTarget: WebSocket {url: 'ws://localhost:3001/ws', readyState: 3, bufferedAmount: 0, onopen: ƒ, onerror: ƒ, …}
defaultPrevented: false
eventPhase: 0
returnValue: true
srcElement: WebSocket {url: 'ws://localhost:3001/ws', readyState: 3, bufferedAmount: 0, onopen: ƒ, onerror: ƒ, …}
target: WebSocket {url: 'ws://localhost:3001/ws', readyState: 3, bufferedAmount: 0, onopen: ƒ, onerror: ƒ, …}
timeStamp: 3208.0999999940395
type: "error"
[[Prototype]]: Event
```
3. 
```
GET http://vets-website-rework-pe-fronten-dev-platform.vfs.va.gov:3001/data/cms/vamc-ehr.json net::ERR_NAME_NOT_RESOLVED
```
4.
```
GET http://vets-website-rework-pe-fronten-dev-platform.vfs.va.gov:3001/img/homepage/va-logo-white.png net::ERR_NAME_NOT_RESOLVED
```

5.
```
GET http://vets-website-rework-pe-fronten-dev-platform-api.vfs.va.gov:3000/v0/feature_toggles?&cookie_id=eiy9rllx36u6kd3t1faawh net::ERR_NAME_NOT_RESOLVED
```
# Tasks
- [ ] Determine whether each of these errors present in the console needs to be addressed in order to have a fully functional FE / BE working together
- [ ] Resolve each issue that is required to be addressed (if resolution of any individual issue escalates to/beyond a 3, please notify PM/TL to ensure a ticket is created to reflect it)

# Acceptance Criteria
- [ ] Each error presented in the console has either been categorized as "won't fix" or has been fixed

**Comment by JoeTice** [comment]
These tickets are OBE as our approach is shifting, closing these tickets to reflect that.
