### ISSUE TITLE
[FE] Add plain language statement to explain next of kin

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#62927]
## Description 
Feedback from platform content during unified check-in to add plain language statement to next of kin page to better explain. E.g., "Next of kin is closes living relative." (This is just an example. Develop whatever content is best.) 

## Wireframes
[Wireframe ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59089)

Please note that content is different between the two apps: 

check-in
https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/p/26257414-A4F5-4E5B-9BAF-B012609F7494/canvas

pre-check-in
https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/p/A3E38E50-B10C-4ED2-94FD-8B8C0B7D71CF/canvas#Version

## Tasks
- [ ] [FE] **Add plain language expandable statement to explain next of kin per the wireframe**
- [ ] [FE] **Default expandable statement to closed**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
@wullaski @brianseek FYI, the final sketch file for this is ready although the wireframe ticket has not yet been closed

**Comment by benbrasso-agile6** [comment]
Yes, sorry about that. Needs a bit more time. Hold off on FE work.

**Comment by wullaski** [comment]
@benbrasso-agile6 is this ready to go? I saw that you mentioned it was ready in the blocked by issue but it's still open.

**Comment by loripusey** [comment]
@wullaski based on reading the ticket comments it seems that it is ready for FE to work on, however, I cannot access the link that @benbrasso-agile6 provided, maybe you can reach out to him directly to get a link and add it to this ticket

**Comment by benbrasso-agile6** [comment]
One moment

**Comment by benbrasso-agile6** [comment]
Should be able to view: https://sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f

Yes, this is the check in version, which is ready. I think I saw that @loripusey was thinking adding/changing components should wait to a diff sprint. But, I might be confusing that with her comments about the other demographic pages. 

@loripusey is this okay for them to work on now? 

Also, I noticed @cgednalske didn't get a chance to finish up the pre-check-in wireframe. I'll do that in a few mins here.

**Comment by loripusey** [comment]
I think it's ok to work on now because it was a feedback from "platform"; the link above takes me to the overall workflow and user journey, can you  put in a link to the actual wireframe that has the new component? I see it in Release 2, can I just grab that one?

**Comment by loripusey** [comment]
@wullaski here is the screenshot from the Sketch files for this
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/75436e36-6d13-4e41-a87f-018fad7b586d)

**Comment by benbrasso-agile6** [comment]
Actually, it looks like @cgednalske did add it into pre-check-in: https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/p/A3E38E50-B10C-4ED2-94FD-8B8C0B7D71CF/canvas#Version

@wullaski when you do this work, can you look to see if in our latest code, does the next of kin page have that body paragraph on both pre-check-in and check-in? Or is it just pre-check-in? I feel like maybe our design files our a bit out of date. But, not positive. 

<img width="543" alt="Screenshot 2023-08-22 at 9 43 36 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/101129355/5903b125-28dc-4cdb-85bd-934be40ece3a">

**Comment by benbrasso-agile6** [comment]
> I think it's ok to work on now because it was a feedback from "platform"; the link above takes me to the overall workflow and user journey, can you put in a link to the actual wireframe that has the new component? I see it in Release 2, can I just grab that one?

I edited the link: 

check-in
https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/p/26257414-A4F5-4E5B-9BAF-B012609F7494/canvas

pre-check-in
https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/p/A3E38E50-B10C-4ED2-94FD-8B8C0B7D71CF/canvas#Version

**Comment by benbrasso-agile6** [comment]
Please note the content is different between pre-check-in and check-in

**Comment by benbrasso-agile6** [comment]
That check in sketch file is messed up. I need Zach to help me with it. But, I DM'd the png to John.

**Comment by benbrasso-agile6** [comment]
Should be fixed now: https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/p/26257414-A4F5-4E5B-9BAF-B012609F7494/canvas#Version

^ check in

**Comment by wullaski** [comment]
@benbrasso-agile6 
> @wullaski when you do this work, can you look to see if in our latest code, does the next of kin page have that body paragraph on both pre-check-in and check-in? Or is it just pre-check-in? I feel like maybe our design files our a bit out of date. But, not positive.

It's only on pre-check-in.

**Comment by benbrasso-agile6** [comment]
Yes, I saw that. Thank you.
