### ISSUE TITLE
Add step to MPR and SR operational guidance for when a touchpoint is skipped

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#62931]
## User Story
As a Governance team member, I want to have clear and comprehensive steps to follow if/when a VFS team decides to skip Design Intent, Midpoint Review or both so that I can respond consistently each time it occurs. 

Assignee: @CherylEvans 
Peer Reviewer: @allison0034 

## Description
VFS teams are permitted to skip Design Intent and/or Midpoint Review as they are optional touchpoints. However, it is not always clear if teams are accidentally skipping a touchpoint or if they're intentionally skipping a touchpoint. The purpose of this ticket is to add a step in the MPR and SR operational guidance for Governance team members to check with the VFS team that the choice was intentional before continuing with the scheduling steps.

## Impacted Artifacts
[Midpoint Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Moderator+Responsibilities) (Pre-Scheduling)
[Staging Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review+-+VFS+-+Moderator+Responsibilities#Pre-scheduling) (Pre-Scheduling) 

## Tasks
**Midpoint Review - Moderator Responsibilities:**
- [x] Add a step/instructions (step 3 of pre-scheduling) for Governance team member to validate that a Design Intent was held (if included in the Collaboration Cycle Request ticket)
- [x] Instructions should specify that if a Design Intent was held, proceed to Scheduling
- [x] Instructions should specify that if a Design Intent was not held, Governance should ask the VFS team member to confirm. (It might be nice here to have a standard template/response that we can just copy/paste into the Slack thread)
   - If VFS team member responds that it was intentional, then we should have a standard response letting them know the risks of skipping Design Intent. Then proceed to Scheduling.
   - If VFS team member responds that it was unintentional, ask if they'd like to pivot this meeting to a Design Intent instead. If yes, ask them to update the Design Intent section of the Collaboration Cycle Request ticket. Ensure that the calendar event says Design Intent and not Midpoint Review. Governance team member should then follow the Design Intent- Moderator Responsibility guidance to finish scheduling.

**Staging Review - Moderator Responsibilities:** 
- [x] Add a step/instructions (step 3 of pre-scheduling) for Governance team member to validate that a Midpoint Review and Design Intent was held (if included in the Collaboration Cycle Request ticket)
- [x] Instructions should specify that if a Design Intent and Midpoint Review were held, proceed to Scheduling
Path 1 (only Midpoint Review skipped):
- [x] Instructions should specify that if a Design Intent was held and a Midpoint Review was not held a, Governance should ask the VFS team member to confirm. (It might be nice here to have a standard template/response that we can just copy/paste into the Slack thread)
   - If VFS team member responds that it was intentional, then we should have a standard response letting them know the risks of skipping Midpoint Review. Then proceed to Scheduling.
   - If VFS team member responds that it was unintentional, ask if they'd like to pivot this meeting to a Midpoint Review instead. If yes, ask them to update the Midpoint Review  section of the Collaboration Cycle Request ticket. Ensure that the calendar event says Midpoint Review  and not Staging Review. Governance team member should then follow the Midpoint Review - Moderator Responsibility guidance to finish scheduling.

Path 2 (both Design Intent and Midpoint Review skipped):
- [x] Instructions should specify that if a Design Intent was not held and a Midpoint Review was not held a, Governance should ask the VFS team member to confirm. (It might be nice here to have a standard template/response that we can just copy/paste into the Slack thread)
   - If VFS team member responds that it was intentional, then we should have a standard response letting them know the risks of skipping Design Intent and Midpoint Review. Then proceed to Scheduling.
   - If VFS team member responds that it was unintentional, ask if they'd like to pivot this meeting to a Design Intent. If yes, ask them to update the Design Intent section of the Collaboration Cycle Request ticket. Ensure that the calendar event says Design Intent and not Staging Review. Governance team member should then follow the Design Intent - Moderator Responsibility guidance to finish scheduling.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team members have a process to follow if Design Intent and/or Midpoint Review are skipped in the Collaboration Cycle 

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
[Draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2728984589/62931+-+Cheryl+-+Copy+of+Midpoint+Review+-+Moderator+Responsibilities) MPR Moderator Resposibilities created
[Draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2727182462/62931+-+Cheryl+-+Copy+of+Staging+Review+-+VFS+-+Moderator+Responsibilities) Staging Review Moderator Resposibilities created

**Comment by CherylEvans** [comment]
@allison0034 Hi Allison. I combined the verbiage in the Staging Review Moderator Responsibilities draft because Paths 1 and 2 outlined the same resolution. I might need some verbiage suggestions for the consequences of skipping specific touchpoints. Unless you feel this is sufficient.  Thank you!  Ready for peer revieiw

**Comment by CherylEvans** [comment]
@allison0034 Hey there.  I updated both of my drafts with your recommendation. The accordion idea is amazing!! I will share a link with the team.

**Comment by CherylEvans** [comment]
@allison0034 I think this is ready for your peer review. :-)

**Comment by CherylEvans** [comment]
@allison0034 I added your suggestions to the [Staging Review - VFS - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2727182462/62931+-+Cheryl+-+Copy+of+Staging+Review+-+VFS+-+Moderator+Responsibilities) doc. I am going to transfer over to the source pages, and close the ticket if you're okay with it.
