### ISSUE TITLE
UX/Design | Authenticated Menu | Explore accessibility for modified list

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#62944]
## Background 
During design intent #62194 a concern was raised around accessibility of the menu if we visually group things together 

The examples of the visual grouping: 

| Option 1| Option 2 |
|--------|--------|
| ![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/2559d93a-f7c8-413f-86d8-fe52ca1fa971) | ![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/43b02c05-f0f8-409c-92ff-d1d825d2ac68)| 

<details><summary>See accessibility feedback from design intent #62942</summary>
- **Consider:** No specific recommendation at this time but looking ahead to how this is coded, it's worth spending some time thinking about whether the menu is one list of links, or two/three lists of links that are semantically different.
   
   The current menu is coded as:
   ```
   <div class="va-dropdown-panel " id="account-menu">
      <ul>
         <li><a href="/my-va/">My VA</a></li>
         <li><a class="my-health-link" href="/my-health/">My HealtheVet</a></li>
         <li><a href="/profile">Profile</a></li>
         <li><a href="https://staging-api.va.gov/v1/sessions/slo/new">Sign Out</a></li>
      </ul>
   </div>
   ```
   
   When you navigate into the menu, a screen reader announces that as "list, four items" and then reads out each link.
   
   With the new items being added, both Option 1 and Option 2 contain some kind of visual separator to group links together. Those separators could be just visual decoration to help sighted users, so the new links would just be added to the same list and announced as "list, six item." I think in this situation that's probably fine!
   
   But you could also group them as separate lists, eg.
   ```
   <div class="va-dropdown-panel " id="account-menu">
      <ul>
         <li><a href="/my-va/">My VA</a></li>
         <li><a class="my-health-link" href="/my-health/">My HealtheVet</a></li>
      </ul>
      <ul>
         <li><a href="/profile">Profile</a></li>
         <li><a href="...">Dependents</a></li>
         <li><a href="...">Letters</a></li>
      </ul>
      <ul>
         <li><a href="https://staging-api.va.gov/v1/sessions/slo/new">Sign Out</a></li>
      </ul>
   </div>
   ```
   
   In that scenario, they would be announced as separate lists: "list, two items" then "list, three items" then "list, one item." You might consider labeling these groupings to clarify what each group is, either with a visible label or an `aria-label` for screen reader users.
   
   Thinking about it as I type, that might be overkill for just adding these two links. But it's something to consider if further additions to this menu are on the horizon.
</details> 

### Other Design Intent Feedback Links
[See design feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62939)
[IA Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62976)

## Tasks 
- [x] explore how other sites structure their menus for screen reader users 
- [ ] submit an a11y ticket to review the grouping

## Acceptance Criteria 
- [ ] flow and mocks are updated:
     - [x] [User flow](https://www.sketch.com/s/113f0ee6-e77d-4b1b-bf02-af27580931fe/p/F06226AA-DBC6-482C-A474-E9585FDF7178/canvas) which incorporates the links we'd use
     - [x]  [Mobile](https://www.sketch.com/s/113f0ee6-e77d-4b1b-bf02-af27580931fe/a/dgkKWqm) 
     - [x] [Desktop](https://www.sketch.com/s/113f0ee6-e77d-4b1b-bf02-af27580931fe/a/AZJA4Em))
- [ ] we're ready to pickup  FE #62940

**Comment by mtcA6** [comment]
@andaleliz before sprint planning tomorrow could you point this one?

**Comment by andaleliz** [comment]
@mtcA6 that sounds good to me.

**Comment by andaleliz** [comment]
I checked a variety of other sites with similar personalized menus to what we're proposing, and based on where I have accounts (BofA, Chase, Citibank, Cigna, MyChart, Amazon). There are a lot of ugly, inaccessible things going on (e.g. a collection of `button` elements inside a `div`) that I don't think we should model.  

I recommend we go with option 1, and add the appropriate attributes to the line above the sign out link to hide it from screenreaders and list the role as decorative.

**Comment by andaleliz** [comment]
I checked a variety of other sites with similar personalized menus to what we're proposing, and based on where I have accounts (BofA, Chase, Citibank, Cigna, MyChart, Amazon). There are a lot of ugly, inaccessible things going on (e.g. a collection of `button` elements inside a `div`) that I don't think we should model.  

I recommend we go with option 1, and add the appropriate attributes to the line above the sign out link to hide it from screenreaders and list the role as decorative.

**Comment by andaleliz** [comment]
@mtcA6 I see one of the tasks is to submit an a11y ticket - I'm not sure what you need me to do there. I don't think that's a typical step at this stage but maybe I'm missing something. Feel free to reopen the ticket if there's more for me to do.  

If there are more questions about accessible code implementation, I believe that's more Adam's practice area than mine.

I created high-fi mock-ups and a flow (if you can even call it that, it's so simple) [in a new Sketch file](https://www.sketch.com/s/b1dacba9-064d-4a24-bfa4-ae0da5790f08) dedicated to the authenticated menu.

**Comment by mtcA6** [comment]
@andaleliz no worries, i put it on the list from [our slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1690905432008009?thread_ts=1690904814.778719&cid=C909ZG2BB)
