### ISSUE TITLE
Create formal mapping document for transition of standards

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#62948]
## User Story
As a Governance team member, I want to map the new standards back to the old standards so that I can ensure we have proper coverage for all standards.

Assignee: @erinrwhite 
Peer Reviewer: @allison0034 

## Description
In ticket #62236, Governance team rewrote, archived and merged the VA.gov Experience standards. We need to make sure we map the old standard to the new standard so that we can 1) share with OCTO-DE practice area leads for their review and approval, 2) update all historical tickets appropriately, and 3) have a document to work with moving forward.

What we want to capture in the mapping document:

- old standard category
- old standard definition
- new standard category
- new standard definition
- new category definitions
- unaddressed notes from Mural
- what else?

Notes:
- Not all standards will map to the same new standard. some might have to be handled on a case by case basis
- any standard that is going to be "archived" and has been flagged before will need to map _somewhere_ so we need to make sure we capture that. This could also be a case by case basis.
- any standards that is going to be "archived" that has never been flagged will not need to be mapped to a new standard. However, please do not rely on the count numbers on the mural cards as they may be inaccurate if the standard was flagged over the last 4 weeks
- preserve the link of the historical gh tickets that were linked in the old standard

## Impacted Artifacts
[Experience Standards - Affinity Mapping](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687405248108/d062ed36c1e5191571492e64cfe61ac87c02c9fc?sender=97a625b1-ee10-4923-8db8-482b219b9201) mural

## Tasks
- [x] Bring over old and new standards and relevant comments from Mural document
- [x] Create meaningful way(s) to visualize and parse old vs new standard and category data
- [x] Ensure that each old standard correlates with a new standard
- [x] Create method for Governance Team to write meaningful updates for standards text
- [ ] 

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have mapped our old standards to our new standards
- [ ] We have a document to work with moving forward with the initiative. 

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
Began work on a [Mapping spreadsheet](https://docs.google.com/spreadsheets/d/1q6UGLEd8re94B5o69EFDz2HNMHw6WvdAHl46FHYsA9s/edit#gid=1839428317)!

**Comment by erinrwhite** [comment]
Had a great call with @allison0034 today and chatted with the team today at refinement. We will review the Mapping spreadsheet Tuesday at the initiatives call and gather team feedback as part of the next sprint.

Questions:
- [Mappings](https://docs.google.com/spreadsheets/d/1q6UGLEd8re94B5o69EFDz2HNMHw6WvdAHl46FHYsA9s/edit#gid=628171129): Do the new standards appropriately match the old standards?
- [New standards](https://docs.google.com/spreadsheets/d/1q6UGLEd8re94B5o69EFDz2HNMHw6WvdAHl46FHYsA9s/edit#gid=601221195) Are all the new standards similar granularity? Should some be combined?
- [Categories](https://docs.google.com/spreadsheets/d/1q6UGLEd8re94B5o69EFDz2HNMHw6WvdAHl46FHYsA9s/edit#gid=1499522783) Does it make sense to proceed with our categories? Do the category definitions make sense?

**Comment by erinrwhite** [comment]
Met with the team today to review the [mapping document](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/gh/department-of-veterans-affairs/va.gov-team/62948) and talk about best ways to gather their feedback in the next sprint. Closing.
