### ISSUE TITLE
FE | Authenticated Menu | Update the menu to include links to letters and dependents

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#62940]
## Background 

Design intent for updating the Authenticated Menu was positive 

<details><summary>artifacts from design intent</summary>
<p>

- [User flow](https://www.sketch.com/s/113f0ee6-e77d-4b1b-bf02-af27580931fe/p/F06226AA-DBC6-482C-A474-E9585FDF7178/canvas) which incorporates the links we'd use
- [Mobile](https://www.sketch.com/s/113f0ee6-e77d-4b1b-bf02-af27580931fe/a/dgkKWqm) 
- [Desktop](https://www.sketch.com/s/113f0ee6-e77d-4b1b-bf02-af27580931fe/a/AZJA4Em)

</p>
</details> 

## Blocked by
- #62944 

### use this for dev:
- [Sketch file from 62944](https://www.sketch.com/s/113f0ee6-e77d-4b1b-bf02-af27580931fe/p/F06226AA-DBC6-482C-A474-E9585FDF7178/canvas) we're going to use option1

## Tasks 
- [x] create a feature toggle 
- [x] locate and update the code for the authenticated menu 
- [x] update the list to incorporate letters and dependents 
- [x] if we do break the menu into sections, consider how that's "chunked" for screen reader users < lets get feedback from a11y team once the code is ready to make sure the structure is accessible 
- [x] discuss the code changes with the sitewide content team @vsa-public-websites-frontend  /have them provide a code review ([per guidance received here](https://dsva.slack.com/archives/C909ZG2BB/p1690899326413359), and [also here](https://dsva.slack.com/archives/C52CL1PKQ/p1690918220535279?thread_ts=1690316191.605039&cid=C52CL1PKQ))

## Acceptance Criteria 
- [ ] ready for staging review

**Comment by mtcA6** [comment]
@Samara-Strauss closing the loop here, I've linked to the slack thread in the tasks ensuring we follow up with the right team

**Comment by mtcA6** [comment]
@adamwhitlock1 i forgot to ask for points on this during refinement, could you add them?

**Comment by adamwhitlock1** [comment]
@mtcA6 Public websites team reviewed and approved changes. We can now validate in staging. I turned on the toggle for all users in staging.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcTlMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4859c155ead1c68a27ae78cba528ad15b462dc4f/Screenshot%202023-08-29%20at%2010.26.23%20AM.png)

**Comment by adamwhitlock1** [comment]
Okay, so style tweaks made it to staging, everything looks good to me there @mtcA6 and @Samara-Strauss do we feel good on closing this one out?

**Comment by mtcA6** [comment]
Was just going to ask, should i close or will you! I'm ok w/closing this ticket!
