### ISSUE TITLE
[UX] Add Content to the 45-minutes Check-in Reminder Text for When to Check-in

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#62955]
## User Story
As the VA, we would like to make sure that the Veteran is at the clinic before they attempt to check-in for their appointment so that we don't have Veterans checking-in while they are at home or on the road.

## Background
[Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1690908224286089)

## Tasks
- [ ] Create the content (for both the version w/ the mobile app and the version w/o the mobile app)
- [ ] Update in sketch
- [ ] Run content by Danielle

## Acceptance Criteria
- [ ] Content has been created & reviewed

**Comment by kellysmith1008** [comment]
@zach-park For the version [without the mobile info](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/AZPZPVR) could you mock up the following content:
It's time to check in for your VA appointment on {{Date}} at {{Time}}. When you arrive at the facility, use this link to check in: https://www.va.gov/{{shorturl}} (line break)
If you have trouble with check in, ask a staff member at your VA health facility for help. 
------
Since this is a check in text, and not a confirmation text, we aren't as strictly limited to the 160 character limit - I say this more just for information, there's not anything to do with this information :) 

**For the mobile version, could you direct me to the most current mobile mock up? I imagine this content will remain mostly similar, but I want to make sure I'm looking at the right version first.**

**Comment by loripusey** [comment]
@loripusey update work ticket after this is complete

**Comment by zach-park** [comment]
@kellysmith1008 @benbrasso-agile6 , ready for validation:
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/2E4349E0-BE11-4DFC-8EF4-1C923E5F74D9/canvas

**Comment by kellysmith1008** [comment]
LGTM Zach! Nice work!

**Comment by loripusey** [comment]
So, this new text content is independent of the work to push it out 45-minutes before, so can I use this sketch link for the Release 2 work to update the CI & PCI text messages? @benbrasso-agile6

**Comment by benbrasso-agile6** [comment]
We would move it when ready. We're using feature pages/branches that focus JUST on the feature/task, and then once ready, we'll also move it into the other appropriate pages in sketch.

**Comment by benbrasso-agile6** [comment]
This is the entire board for context: https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/2E4349E0-BE11-4DFC-8EF4-1C923E5F74D9/canvas

But, I'll let @kellysmith1008 speak to how she wrangled the right solution.

**Comment by kellysmith1008** [comment]
@loripusey The suggestion from Kristen did include the "start to" idea, but I removed it for this reason: If we're asking a Veteran to wait until they are at the facility, it seemed more appropriate to just say "check in". That's the action that users take, even though they technically have to "start" the process. It also avoids using a gerund which can be difficult in translations. I also considered that they may have, *technically*, "started" this process by confirming their demographics in pre-check-in, so I just thought removing that "start to" language and going right after the desired action, check in, made the most sense. That having been said, I'm happy to update the text to "When you arrive at the facility, start checking in at:..." if we want to have it in there. I tend to overthink content too much and too often, so happy to update if we want!

**Comment by benbrasso-agile6** [comment]
I think you do a tremendous job at thinking about the content. Don't doubt your process :) 

I'm happy with either direction.

**Comment by loripusey** [comment]
I am good either way

**Comment by kellysmith1008** [comment]
Sounds good, thank you for the discussion! Closing the ticket - and thanks again for the callout about "use this link" Ben, it's good to be mindful!

**Comment by kellysmith1008** [comment]
Yeah, I tagged Kristen on the ticket last week and she shared the ticket in slack: https://dsva.slack.com/archives/CMJ2V70UV/p1691599138213689?thread_ts=1688153443.697539&cid=CMJ2V70UV

**Comment by benbrasso-agile6** [comment]
I added that change to the following sketch pages: 

[Design](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/0EC89917-F949-4461-A7B3-32A5201FD2A2/canvas)

[Design - Release 2.0](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/868762F3-8E8F-4E23-B0DA-34C1783F0A03/canvas)

[Design - All releases (draft)](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/v/79Wx3p/p/F05730C4-9E76-4B1D-AEA0-63CEC7E61175/canvas)
