### ISSUE TITLE
DSVA Slack instructions follow up

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#62979]
## Issue Description
- Document: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/slack-requests.md
- Customer support inquiry from Slack thread: https://dsva.slack.com/archives/CBU0KDSB1/p1689967384194959

---
## Tasks
- [x] Working with product owner to discuss content details
- [x] Make edits to document on site
- [x] Prepare page edits for deploy

## Acceptance Criteria
- [x] [Request Access to Tools](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools) will be updated with instructions on both how to request access to Slack and also how to grant Slack access
