### ISSUE TITLE
Salesforce Reporting Overview - Activities Tracking/Identifiy Trends 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#62984]
## Issue Description
_Create a comprehensive list of available reports that provide a clear view of the Contact Center's activities. _

---
## Tasks
- [x] _Ervin and Sarifa to collaborate to compile a complete list 
- [ ] Sarifa - create an At A Glance chart depicting all available reports 
- [ ] Sarifa - create a weekly/biweekly report of incoming issues, categorized Tier 2//Teir 3/ Teir 3 EVSS and resolution calculations
- [ ]  
- [ ] 

## Acceptance Criteria
- [ ] Per sprint - post the report in recurring issue on Zenhub board  _
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
The team has decided to create a different iteration of this process.  New ticket will be created.
