### ISSUE TITLE
[Research] Notifications: coordinate with MHV on unread messaged notification

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#62995]
## Background
In our previous sprint Angela worked with MHV team members to work through various notification/indicators that could be used on MHV and My VA to indicate new messages (or other "new" content"). They came up with several possible solutions that need to be tested and MHV has decided to proceed with a dot solution. We'll be partnering with them to refine the design to work on My VA as well as MHV and go through the collab cycle with them.

## Tasks
- [x] Work with MHV designer(s) to settle on scope of details of dot design
- [x] Refine designs for My VA and MHV 
- [x] Join MHV's design intent 

## Acceptance Criteria
- [x] We have a proposed design for highlighting new unread messages on My VA
