### ISSUE TITLE
Pension 527EZ Deactivation | About VA Form Page

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#62990]
## Issue Description
- The online pension 527EZ form is too outdated to be processed and must be temporarily deactivated on VA.gov.
---
## Tasks
- [ ] Update the language on the "About VA Form" page to remove access to online form.
- [ ] Add an info box alerting users that the online form is no longer available.
   - [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1689262813123/cb880912d3f71ef79be0d63d0e61e306d1e6ae31?wid=0-1689360929417&sender=u0e8ac1d6d7681bb7e1b80558) with changes highlighted
   - [Sketch](https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6) with style formatting

## Acceptance Criteria
- [ ] No links to online form
- [ ] Info box appears with correct text

**Comment by steele-lm** [comment]
Closing bc CAIA will be making the necessary changes.
