### ISSUE TITLE
Event tracker CTA for Cerner Re-direct - Appointments Homepage

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#62997]
## Description
We will need to add an event tracker for the Cerner re-direct link on the Appointments landing page. 

---

## Acceptance Criteria

- [ ] Given the user is logged into the Appointments tool and is registered at a Cerner site
       When the user clicks on the `Go to My VA Health` on the appointments landing page  
        Then it will trigger the event `vaos-cerner-redirect-appointments-landing-page` in UA 

### Design Assets
Not applicable 

### Out of scope 
Adding the tracking event to GA4. This will be part of #61355. 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ldelacosta** [comment]
Tracker has been added into production UA. Closing out the ticket. cc: @JRRoof @outerpress 
![Screenshot 2023-08-11 at 12.00.42 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/92cde512-f589-4221-8197-0e81e1627370)
