### ISSUE TITLE
Confluence - Support Documentation 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#62993]
## Issue Description
_Review all Contact Center Tier 2/Tier3 documentation

---
## Tasks
- [x] _Review all Confluence documentation 
- [x] Complete and update the Contact Center overview document.

## Acceptance Criteria
- [x] _Acknowledge and review
- [x] Publish a "plain language" version to Confluence.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
Due to vacation and just receiving access to Confluence and the correct ZH board, this has been delayed.  Completing this task by EOS is still possible.

**Comment by starlow00** [comment]
@ATMiddleton Draft for Confluence document attached for review.

[Contact Center Overview SRT 08222023.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbWdxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d030bcb48cfb51ab6e9b6130ad6375798f90b99c/Contact%20Center%20Overview%20SRT%2008222023.docx)

**Comment by starlow00** [comment]
Hi @clantosswett. The draft attached to this ticket (see my last comment) includes the team introduction I could use for our newsletter (which will be a different ticket). You mentioned that you wanted to take a look at it. Once I design the actual newsletter, I will of course let you see it before distribution.

**Comment by clantosswett** [comment]
Thank you @starlow00 I am going to review today and will upload the doc with any feedback or edits.

**Comment by starlow00** [comment]
Will do, @clantosswett

**Comment by starlow00** [comment]
Edits from Chante look good. I posted a couple of questions to the team for clarity in our team Slack channel. Will update once data has been collected.
