### ISSUE TITLE
[FE] My VA Audit UX Improvements: Make "Learn how to file a claim" link static

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#62994]
## Background
As detailed in this [slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1690292542217169?thread_ts=1690231844.315009&cid=C909ZG2BB), since people can file more than one claim and have more than one claim going at a time, we've decided to always show the "Learn how to file a claim" link in the "Claims and appeals" section of My VA. Design and documentation updates were made in #62519, this is the FE implementation ticket.

## Tasks
- [ ] Update logic on the "learn how to file a claim link" in the claims and appeals section to always show for LOA3 users.
- [ ] Update tests
- [ ] Move to validate and tag PM

## Acceptance Criteria
- [ ] Learn how to file a claim link appears for all LOA3 users

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ verify "learn how to file a claim" link is visible for all LOA3 users (will need to verify with staging user of various claim status - i.e. no claim, closed claim, etc.)

## Resources
- [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/claims-and-appeals-FE-documentation.md#learn-how-to-file-a-claim-link)
- sketch [desktop ](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/25LlG1l)
- sketch [mobile](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/WK72gqw)
- [Use case documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/use-cases/claims-and-appeals-use-cases)

**Comment by allisonlu** [comment]
@ajakabcin @aagosto90 ready for validation on staging! I confirmed that the link is displaying for users:
- judy.morrison (open claim)
- 192 (claim closed in last 60 days)

https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myvaaudit.md#claims-and-appeals-section

**Comment by aagosto90** [comment]
Will try validating tomorrow since staging is baaaaarely loading today. Thanks @allisonlu !

**Comment by aagosto90** [comment]
Validated for both users! 
<img width="976" alt="Screenshot 2023-08-10 at 12 35 16 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/97965610/62b970c7-7bb2-4a84-bc93-6c6fd4bdcd48">
