### ISSUE TITLE
Tier 3 Support Training 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#62991]
## Issue Description
_In an effort to have appropriate back up for Tier 3 support.  

---
## Tasks
- [x] Training @aubreyarcangel Tier 3 support 
- [x] Salesforce Access

## Acceptance Criteria
- [x] _Aubrey will have base line knowledge of Tier 3 support responsibilities 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
Due to vacation and the recent issue with EDIPI, this training has been delayed.  However, there should not be any issues with completing this training by EOS.

**Comment by Kimberley2023-CSM** [comment]
Today, @aubreyarcangel and I had an overview of Salesforce Tier 2/Tier 3/Tier 3 EVSS process.
