### ISSUE TITLE
Enable Intent to File(ITF) in production: Canary

### ISSUE THREAD

**Issue by mchae-nava** [department-of-veterans-affairs/va.gov-team#63007]
## Issue Description
This is to track the Canary section from our [ITF release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/disability-experience/team-docs/Release%20Plans/DBEX%20Intent%20To%20File%20Endpoint%20Migration%20Release%20Plan.md)

We'll be scheduling times with users from [this document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/team-veterans.md) and verifying activity is captured properly in our [DataDog dashboard](https://vagov.ddog-gov.com/dashboard/ipg-v6d-c59/benefits---dbex---evss-to-lh-intent-to-file?from_ts=1690907664207&to_ts=1690911264207&live=true)

## Tasks
- [ ] Follow steps in the 'Canary' section of the release plan
- [ ] Record findings and issues in the plan doc

## Acceptance Criteria
- [ ] All boxes checked in the 'Canary' section of the plan doc
- [ ] Any issues/observations recorded in the plan doc
