### ISSUE TITLE
Test to ensure BE/FE Communication works as expected

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#63003]
# Description
With vets-api issues resolved and a working FE, we would like to test and ensure Preview Environments are functioning without issue.

For example, let's compare our instance to the integrated environments and review instances --
[dev.va.gov](http://dev.va.gov)
[staging.va.gov](http://staging.va.gov)
[example RI]

# Tasks
- [ ] Compare PE instance functionality to RI
- [ ] Compare PE instance to dev.va.gov
- [ ] Compare PE instance to staging.va.gov
- [ ] Execute VA.gov smoke tests on the preview environment instance

# Acceptance Criteria
- [ ] Smoke tests pass successfully

**Comment by JoeTice** [comment]
These tickets are OBE as our approach is shifting, closing these tickets to reflect that.
