### ISSUE TITLE
Onboard New Team Members to Preview Environment Effort

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#63004]
# Description
We have new team members starting this sprint, we want to get them up to speed on Preview Environments the work being done, 

# Tasks
- [x] Brief team members on the historical reasoning for the Preview Environment effort
- [x] Brief team on project ticket and discovery effort information
- [x] Brief team members on the current architecture, focus and state of Preview Environments
- [x] Brief team on current and potentially upcoming issues/needs

# Acceptance Criteria
- [x] Team members are comfortable with the effort and ready to begin to get engaged
