### ISSUE TITLE
Review new standards with OCTO-DE Practice Area Leads

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#63014]
## User Story
As a Governance team member, I want to present the revised VA.gov Experience Standards to OCTO-DE for their review and feedback so that we can move forward with implementation with the confidence of OCTO-DE.

Assignee: @erinrwhite 
Peer Reviewer: @shiragoodman 

## Description
Governance team has restructured the VA.gov Experience Standards to include new categories, pivoted the standards/issues to be more broad (and more easily understood by VFS) and have introduced a new level of detail, referencing the sources of truth that already exist across VA.gov. In addition, Governance has drafted proposed criteria for identifying if/when a finding should be launch-blocking, and have created several examples of what the VFS team will see via Github at Staging Revies when a finding is documented.

The purpose of this ticket is to present all of the above information to OCTO-DE practice area leads for their review, input and approval to move forward with our planned rollout to VFS teams. 

## Impacted Artifacts
[Revised Experience Standards](https://docs.google.com/spreadsheets/d/1q6UGLEd8re94B5o69EFDz2HNMHw6WvdAHl46FHYsA9s/edit#gid=500057009)
[Criteria for launch-blocking issues](https://docs.google.com/document/d/1x4gBYxk7PnBcV_8EJy6acscTR66bn2EVh3k-nPcUIQY/edit#heading=h.dc65zrxswq7w)
Original MURAL boards
Any other artifacts that have been created for this initiative 

## Tasks
- [x] [Create a Confluence doc](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2812903593/New+Experience+Standards+-+OCTO+Review) in the Governance Team/Documentation Drafts space that will serve as the main page for OCTO-DE practice area leads to review
   - All Impacted artifacts from above should be listed and available from Confluence
- [x] Document an abbreviated version of the journey we took to get to where we are
   - You can ask Shira for help with this if needed
- [x] Try and include as much information within the Confluence doc as possible. We want OCTO to really only review the information within the Confluence doc, however still have the other artifacts available for reference if needed
- [x] When document is complete, share with Governance team and Matt Dingee via #platform-governance-team Slack channel for review and feedback
- [x] Address all comments/questions from Governance and Matt
- [x] Once Governance team comments are addressed, we need to share with the OCTO-DE practice area leads:
   - [x] Review calendars from a week to 10 days out and find several timeslots where all or most are available
   - [x] Post in #platform-collaboration-cycle channel and tag Beth, Danielle, Mikki, Martha, Matt, Shane and cc @ platform-governance-team-members
   - [x] Also ask for preferred date/time to schedule review meeting
   - [x] Ask leads to review Confluence doc and encourage them to comment and ask questions within the doc 
- [x] Once OCTO-DE leads respond, schedule review meeting with all leads plus Governance team
- [ ] Hold meeting on **December 4, 2023, at 4 p.m. Eastern**
- [ ] Designate the following roles within the review meeting:
   - **Host**: responsible for hosting the meeting, walking through the Confluence doc and soliciting feedback from OCTO leads
   - **Timekeeper**: responsible for keeping track of the the time, so we can ensure everything is covered. Notifies the host if/when we've used up all allotted time for a specific section.
   - **Notetaker:** takes notes in a separate doc, documenting all feedback from OCTO leads (this can be 2 people if necessary)
- [ ] After review meeting, Governance team will reconvene with Matt to discuss any proposed changes and or critical feedback received
   - [ ] Reconvene meeting date/time: ______
- [ ] Any changes agreed upon by the team and Matt will be addressed in a separate ticket

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have prepared a detailed overview document regarding the new VA.gov Experience Standards and have shared with OCTO-DE Practice Area leads
- [ ] We have solicited feedback, comments and questions from the OCTO-DE Practice area leads
- [ ] We have reviewed proposed changes with the team and with our PO and made decisions on whether or not to implement any changes

## Team Notification
- [X] Slack post on #platform-governance-team - notifying team of doc for review, pre-OCTO-DE lead reach out
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
[First draft of Confluence doc started](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2812903593/New+Experience+Standards+-+OCTO+Review+-+63014) needs more refinement before peer review tho!

**Comment by erinrwhite** [comment]
@shiragoodman Ready for your eyes again. I did a lot of restructuring and tried to tighten things up a bit - and am now 😵‍💫 so it's back in your court!

**Comment by erinrwhite** [comment]
Shared with Governance team and Matt Dingee via Slack this afternoon. Deadline for feedback end of day Friday 11/2.

**Comment by erinrwhite** [comment]
Shared with OCTO leads yesterday for review. Meeting scheduled for 12/4 at 4 p.m. Eastern.

**Comment by erinrwhite** [comment]
@shiragoodman I think we've done that can be done on this ticket at this time. We'll want to revisit just ahead of our 12/4 call with OCTO leads. Should the set of tasks related to meeting with the leads and incorporating their feedback move into a new ticket for the backlog, or do we just keep this ticket open? Thank you!

**Comment by shiragoodman** [comment]
@erinrwhite yea, I think that's a good idea. I'm doing some backlog refinement and sprint planning prep today so I will take care of it. You can close this out, and I'll be sure to move any unfinished items to a new ticket. Thank you!

**Comment by erinrwhite** [comment]
@shiragoodman Okay, sounds good. Thanks! Closing this one out.

**Comment by shiragoodman** [comment]
New ticket for following up on OCTO feedback: https://github.com/department-of-veterans-affairs/va.gov-team/issues/69430
