### ISSUE TITLE
Integrate Slack Notifications for 'Merge master -> k8s' Failures in sync-branch GitHub Actions Job

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#63012]
## Issue Description
Currently, our `sync-branch` GitHub Actions job lacks a feature to notify the team on Slack when the 'Merge master -> k8s' step fails. This makes it difficult for the team to promptly address failures in the job and hinders the speed of our development workflow. We need to add a step in the job that sends a notification to our designated Slack channel whenever the 'Merge master -> k8s' step fails.

---
## Tasks
- [ ] Update the `.github/workflows/sync_branch.yml` file to include a step that sends a Slack notification to the appropriate @DSVA Slack channel when the 'Merge master -> k8s' step fails.
- [ ] Test the updated job to ensure the new Slack notification works as expected.
- [ ] Document the changes in the appropriate location so that the team is aware of the new Slack notification functionality.

## Acceptance Criteria
- [ ] When the 'Merge master -> k8s' step in the `sync-branch` job fails, a Slack notification is sent to the appropriate channel.
- [ ] The Slack notification contains all the necessary information about the failure to help the team quickly diagnose and resolve the issue.
- [ ] The team is aware of and understands the new Slack notification functionality.

**Comment by rmtolmach** [comment]
Was this done in https://github.com/department-of-veterans-affairs/va.gov-team/issues/69087?

**Comment by rmtolmach** [comment]
Eric has a PR up for this: https://github.com/department-of-veterans-affairs/vets-api/pull/14911 @ericboehs can you make sure your PR covers the tasks listed in this old ticket? :smile:
