### ISSUE TITLE
deprioritized EPIC | Profile | Plug into VA Profile API

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#63024]
## Background

There are some interesting data points available in the VA profile API that it might be worthwhile 

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/4f2ebe0a-8a4f-404c-b2e8-2dddae6b2693)

**VA Profile Intake Call - 8/15/2023**
Plugging into this wouldn't change our write back service it would make our initial call to the VA Profile data for the read when initiating things. 

We're calling a lot of things and not showing them, it may streamline things and help us pre-load the information in the background which would streamline our other steps. 

Barry highlighted, VA Profile is in the process of building out a Combined Service - Profile V3 on steroids - they should have this available next year. 

Shifting to Profile Service V3 wouldn't be hard for the other items in the VA/gov profile. All of the current calls except for Contact Information would be pretty straight forward. We're on Contact Info v1 and the latest version is different. 

## Tasks
```[tasklist]
### Tasks
- [x] samara submitted a va profile intake
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/63408
- [ ] list out BE steps
```

**Comment by mtcA6** [comment]
i think we can close this out as not-planned for now, we are likely going to get at some of this data with the military information work but the original idea behind this ticket and the corresponding epic was to help us where there were gaps w/LH. We've since found we don't really need this.
