### ISSUE TITLE
BE | Profile | Disability Rating | Verify Authorization Policy

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#63021]
## Background
With the change to Lighthouse, ensure that the verification policy for disability rating is correct.

## Tasks
- [x] Determine policy (authorization rules)
- [x] Update policy (if changes are needed)
- [x] Notify mobile team of any changes (if needed)

## Acceptance Criteria
- [x] Verify in staging

**Comment by mtcA6** [comment]
@tpharrison how can I verify?

**Comment by tpharrison** [comment]
The PR hasn't been approved by the platform yet.  I was planning on testing it with a user that does not have an ICN.  The test will need to verify an error code of `403` is returned from the service history endpoint.
