### ISSUE TITLE
Draft communication plan for launchng E2E allow list merge blocking

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#63040]
## Description
Before we can launch our Merge Blocking Github Actions check based on the Allow List, we need to draft up numerous forms of communication to ensure teams and leadership alike are aware of what changes are coming and how it will impact the involved parties. 

## Tasks
- [ ] Draft Slack Message for #vfs-all-teams and #change-announcements channel
- [ ] Decide on approach for altering the existing or creating a new Slack Notification for the Allow List warnings
- [ ] Decide on approach for altering the vfs-facing confluence allow list page to reflect Allow List warnings
- [ ] Draft text for that page
- [ ] Notate planned communications in [Launch ticket](https://app.zenhub.com/workspaces/frontend-cop-backlog-6452b043f27c8b0011a25236/issues/gh/department-of-veterans-affairs/va.gov-team/63288) as a comment

## Acceptance Criteria
- [ ] A defined plan exists for communications surrounding the allow list merge blocking
- [ ] These planned communications are recorded in the launch ticket linked above for implementation.
