### ISSUE TITLE
Documentation - Standardize expected VFS docs

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#6304]
### User Story

As a VFS team member, I need to know what documentation I am expected to create and maintain, so that I can contribute to the VA.gov documentation ecosystem and assist future iterations on my products.

### Problem Statement

Currently, VFS teams have varying documentation standards — people are keeping their docs in different places (some in the /teams folder, some in the /products folder), sometimes key docs are missing, and there are few concrete guidelines for what VSP’s expectations are. 

How might we standardize the set of documentation that VFS teams are expected to create and maintain? 

## VSP Objective (Q1 & Q2 2020)

O1: Any volume of simultaneous customers have a delightful, self-service, end-to-end experience using the Platform to build on VA.gov.

## Measuring Success (KRs/KPIs)

TBD

## Areas for Discovery

- What docs are different VFS teams currently creating, maintaining? Where? Using what tools?
- What is the minimum set of docs that VSP should require VFS teams to create that will allow teams to operate the way they think is best while still supporting cross-team collaboration and future development on the same products?

## Definition of Done

- [ ] Set of required VFS docs is defined
- [ ] Set of required VFS docs is socialized 
- [ ] MVP governance model for VFS docs is defined 
- [ ] MVP governance model is socialized as applicable

**Comment by vbellissimo** [comment]
Cancelling/old task.
