### ISSUE TITLE
Implement manual trustworthiness and feedback conventions

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#6305]
- [ ] Determine what docs need to have manual trustworthiness metadata
- [ ] Start using "owned by"/"last reviewed"/"expires"
- [ ] Implement manual feedback loop on most crucial docs

**Comment by vbellissimo** [comment]
Cancelling/old task.
