### ISSUE TITLE
Copy Lovell Staging Review tickets to va.gov-team repo

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#63056]
## User Story
As a Governance team member, I want to copy all of the Lovell SR tickets to the va.gov-team repo so that those tickets can be reflected in the Collaboration Cycle dashboard in Domo.

Assignee: @CherylEvans 
Peer Reviewer: @briandeconinck 

## Description
Governance team decided to duplicate the [Lovell VAMC Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52672) accessibility issue tickets into the va.gov-team repo opposed to having the tickets (currently in the CMS repo) pulled into the Collab Cycle dashboard. The purpose of this ticket is to create the new tickets with the right labels and assign them as child tickets to the Lovell VAMC Collaboration Cycle request ticket.

## Impacted Artifacts
all accessibility issue tickets from the [Lovell VAMC Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52672)

## Tasks
- [x] Create new tickets for each CMS-repo accessibility issue that was flagged at the Lovell VAMC SR
- [x] Ensure the labels added to the new tickets are aligned with the [Anatomy of a Staging Review Issue ticket
](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket) guidance
- [x] Comment on the CMS repo issues that this ticket was recreated in the va.gov-team repo and the va.gov-team repo ticket should be closed when the CMS-repo ticket is closed. (Maybe write standard message that can be copy/pasted?)

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The Lovell SR accessibility issue tickets exist in the va.gov-team repo

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Cheryl added as assignee, Brian added as Peer reviewer

**Comment by CherylEvans** [comment]
@shiragoodman @briandeconinck The Lovell SR ticket, [52672](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52672), has only one Accessibility ticket ([54290](https://app.zenhub.com/workspaces/department-of-veterans-affairsvagov-team-62447fb44deeed001392c57f/issues/gh/department-of-veterans-affairs/va.gov-team/54290)) associated with it, or am I missing something? I expected to see more.

**Comment by briandeconinck** [comment]
Do you have time after refinement to chat? I can talk you through the whole sordid story.

**Comment by CherylEvans** [comment]
@briandeconinck Absolutely! :-) Chat soon!

**Comment by shiragoodman** [comment]
thank you for coordinating!

**Comment by CherylEvans** [comment]
@shiragoodman This ticket will carry over into the next sprint.

**Comment by CherylEvans** [comment]
@briandeconinck I think this is ready for your Accessibility expertise. Everything is done for these tickets except refining the accessibility language for the titles on the va.gov-team repo tickets. I would have been guessing which experience standard was the most appropriate.  The labels should all be correct, but you may want to add a few more once you decide on the refined accessibility language for the titles. 
Please let me know if you have any questions or concerns. :-)

**Comment by shiragoodman** [comment]
@CherylEvans @briandeconinck one last thing - tickets that are closed in the CMS repo should also be marked as closed in the va.gov team repo. please verify! thank you

**Comment by CherylEvans** [comment]
@shiragoodman @briandeconinck 

Closed Tickets:

- 64449
- 64844
- 64846
- 64847 Linked to broader ticket # [13804](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13804)
- 64848
- 64849
- 64850 Linked to broader Ticket # [12326](https://app.zenhub.com/workspaces/department-of-veterans-affairsvagov-team-62447fb44deeed001392c57f/issues/gh/department-of-veterans-affairs/va.gov-team/12326)
- 64851

**Comment by CherylEvans** [comment]
@briandeconinck I am ready for your peer review if you are done with your updates. :-)

**Comment by briandeconinck** [comment]
@CherylEvans I have checked the last of the tickets, I think this is good to go!

**Comment by CherylEvans** [comment]
@briandeconinck Thank you so much for finishing this up! :-)
Closing.
