### ISSUE TITLE
Implement Rubocop Linting Check in CI for Every Push to the Codeowners App

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#63057]
## Issue Description
Currently, Atlas doesn't have a Rubocop linting check that runs on every push in CI. This absence may allow code that doesn't adhere to our stylistic and syntactic standards to be merged into our codebase. To ensure code quality and consistency, we should implement a Rubocop check that runs in our CI environment against every push.

Use the same Rubocop config used in vets-api for consistency.

---
## Tasks
- [ ] Implement a Rubocop check that runs against every push in CI pipeline for the Codeowners app.
- [ ] Test the implementation to ensure that the Rubocop check works correctly and fails the build when it encounters linting issues.

## Acceptance Criteria
- [ ] Rubocop check runs automatically against every push to the Codeowners app in CI.
- [ ] The CI pipeline fails if Rubocop detects any linting issues, preventing the merging of substandard code.

**Comment by jennb33** [comment]
@LindseySaari is this work still required?
