### ISSUE TITLE
UX | Profile | Profile hub | Content review

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#63062]
## Background

We need to review the description + links for each section with the content team

## Tasks
- [x] Review content w/ content team during office hours
- [x] Update Sketch files

## Acceptance Criteria
- [x] Approved content is reflected in Sketch files

**Comment by andaleliz** [comment]
Sketch files updated with approved content
