### ISSUE TITLE
Update number of days to complete disability-related claims for July 2023

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#63063]
## Issue Description
We need to update the number of days it takes to complete disability related claims. Sitewide content needs to email Tanekwa Bournes on the first of the month to get the number from the previous month and input into Drupal.

This needs to be done on the following pages:
https://www.va.gov/disability/after-you-file-claim/
https://www.va.gov/disability/how-to-file-claim/
https://www.va.gov/disability/how-to-file-claim-esp/
https://www.va.gov/disability/after-you-file-claim-esp/

## Tasks
- [x] Email Tanekwa for most recent number (Randi)
- [x] Input number and new month into Drupal pages (Randi)
- [x] Review Spanish pages (Ana)
- [x] Review English pages (Megan)
- [x] Publish all 4 pages (Megan)

## Acceptance Criteria
- [ ] Most current number of days is on live site

**Comment by RLHecht** [comment]
@megzehn Since Aliyah and Ana are both out I just updated these pages and they're ready for you to review and publish. FYSA @coforma-terry

**Comment by megzehn** [comment]
Thank you, @RLHecht! I reviewed and published these pages. Moving to validate.
