### ISSUE TITLE
[FE] 10-10EZ - Remove conditional logic for screener question feature

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#63077]
## Description
Once the removal of the duplicate veteran information questions has been adopted for the Health Care Application, we need to remove all conditional logic for the feature and update any form flows affected by the logic.

## Tasks
- [x] Remove Veteran Name & SSN pages from the form config
- [x] Update Veteran DOB conditions in form config to account for only logged in and no DOB in profile data
- [x] Remove duplicate form data from being set on ID Form page
- [x] Remove feature toggle from form data
- [x] Update e2e testing to account for new flow
- [x] Remove feature toggle declaration in both `vets-website` and `vets-api`

## Acceptance Criteria
- Feature successfully functions without conditional logic.

**Comment by longmd** [comment]
Verified feature functions in both authenticated and guest site statuses as intended and without issue.
