### ISSUE TITLE
Document Sidekiq best practices/examples (request from VBA)

### ISSUE THREAD

**Issue by kylesoskin** [department-of-veterans-affairs/va.gov-team#63076]
## Value Statement
**_As a_** developer on VA.gov
**_I want to_** have some information/documentation on sidekiq jobs and how we use them here
**_So that_** I can make sidekiq jobs well

---
## Background Context

This was a request from Steve Albers.

## Out of scope
- Add here

## Open questions
- Where is this document going to live?

## Tasks
- [x] Write documentation with examples
- [ ] Review with Steve
- [x] Put in final living place
- [ ] Make config.yml additions so that this document can be included in backstage (also a request of Steve's)

## Definition of Ready 

It is ready

## Definition of Done

- [x] document created
- [ ] document approved by stakeholders
- [ ] document shows up in LH backstage as expected

**Comment by kylesoskin** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/backend/vets-api/sidekiq-information.md

**Comment by HeatherWidmont** [comment]
@kylesoskin & @data-doge needs to review with @va-albers

**Comment by saderagsdale** [comment]
Note from Steve: Hello Sade!  For this Code Yellow stability project we have a request: provide a list of our sidekiq jobs.

They specifically asked us about the jobs in a couple of tickets, but I think there are others they forgot to assign to us:
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1273
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1268

**Comment by saderagsdale** [comment]
Disregard note above.
