### ISSUE TITLE
Collaboration Cycle for [Login.gov Adoption, VA Profile, Sign in Page]

### ISSUE THREAD

**Issue by MOStudioCarolyn** [department-of-veterans-affairs/va.gov-team#63073]
### VFS team name

Login.gov Adoption

### Product name

VA Profile

### Feature name

Sign in Page

### GitHub label for product

#identity-personalization

### Public DSVA Slack channel for VFS team

va-identity-product-team

## Kickoff questions

<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

ASAP

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Static pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Unsure

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/login.gov-adoption/products/login.gov

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Notify the Collaboration Cycle team of this ticket in your team's public Slack channel.

- [X] I acknowledge that I must notify the Governance team by posting "collab-cycle-kickoff" in my team's Slack channel after submitting this issue.

[Slack thread request](https://dsva.slack.com/archives/C0429DNFN8Y/p1691424023031379)

</details>

### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- [ ] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [ ] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [ ] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.

**Design Intent artifacts**

See Platform guidance on [Design Intent artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Design Intent meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

- [ ] User flow (required)
- [x] Whiteboard sketch or other lo-fi prototypes or wireframes
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/products/login.gov/Screen%20Shot%202023-07-26%20at%2011.09.36%20AM.png
- [ ] Research plan
- [ ] Any other artifacts you have so far
  
##### Platform actions
- [x] [Design Intent Slack thread with VFS team ](https://dsva.slack.com/archives/C0429DNFN8Y/p1691427969793759)
- [x] Meeting date/time: Thursday August 10th 2023 at 3:30pm ET
  
##### Platform actions

- [ ] If you have feedback, create feedback tickets and link to this epic. Once you have completed you review, check the box next to your practice area
  - [x] Accessibility has completed the review
  - [x] Design has completed the review
  - [x] IA has completed the review
- [x] Update this ticket with the Zoom recording
  - [Zoom recording](https://oddball-io.zoom.us/rec/share/oQJ_G8ithKgQHP-Fjpwepdhvs0_RgkZfsDV8pkx8DmNkU6TTgUaaNAEPnOuLn969.vPPK88wg7xkSiHhE)
  - Password: h%KLjb04
  
##### VFS actions

- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Sitewide CAIA Intake Request
<details>
  <summary>Toggle Sitewide CAIA Intake Request</summary>

##### VFS actions
- [ ] Complete the [Sitewide CAIA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-CAIA-intake-request.2124906551.html)
- [ ] Link to the Sitewide CAIA Intake Request ticket below

</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [ ] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [ ] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

Provide links or documents for the following:

- [x] [Finalized design prototype or mockup ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/products/login.gov/Screen%20Shot%202023-08-15%20at%2011.49.48%20AM.png)
- [ ] Specify which pages are included in the review 
- [ ] Research plan
- [ ] Conversation guide
 
**Content artifacts**
  
- [ ] Your product’s content source of truth 
- [ ] Github ticket for any relevant static content page and entry point updates for tool or feature (if applicable)

**IA artifacts**

- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) feedback you received, including an IA review document or intake form.

##### Platform actions
- [x] Midpoint review Slack thread with VFS team: [Slack thread](https://dsva.slack.com/archives/C0429DNFN8Y/p1692127243321609)
- [x] Meeting date/time: **Friday, August 18 11:30am ET - Async**

##### Platform actions

- [x] If you have midpoint review feedback, create feedback ticket and link to this epic. Once you have completed your review, check the box next to your practice area
  - [x] Design has completed the review
  - [x] Accessibility has completed the review
  - [x] IA has completed the review
  - [x] Content has completed the review
- [ ] Update this ticket with the Zoom recording
  - Recording URL: 
  - Password:
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [ ] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [ ] Link to the Analytics Implementation and QA Request ticket below

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [ ] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [ ] Link to the Contact Center review request ticket below

</details>

### Staging Review
<details open>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [ ] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [ ] I confirm the environment is available and test users have been provided.
- [ ] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).

**Staging Review artifacts**

Links to [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts) must be added to this ticket 4 business days ahead of the scheduled meeting. Please do not make changes to the product or artifacts during the 4-day review period. 

#### Required artifacts
  - [ ] **URL(s) to review the product**
    - The product should be available on an [approved staging environment](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-environment-guidance-for-vfs-teams). 
    - List pages, sections of pages, and/or user flows impacted by this work.
  - [ ] **Drupal or Staging URL for updated primary entry point**: the main way Veterans will access the tool through site navigation (not search)
  - [ ] **Test users and scenarios (when applicable)**
    - Store [test user information](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md), passwords, and tasks in a `.md` file in the va.gov-team-sensitive repository. 
    - Make sure all user scenarios can be tested, i.e.: in-progress form, submitted form, new form.
  - [ ] **Link to Sitewide CAIA intake ticket, if applicable.**
  - [ ] **Completed accessibility testing artifact**: [see instructions and link to accessibility testing template](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).
  - [ ] **QA Artifacts**: artifacts that correspond to each of the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
    - [ ] Regression test plan
    - [ ] Test plan
    - [ ] Coverage for References
    - [ ] Summary (Defects) reports
    - [ ] E2E tests
    - [ ] Code coverage
    - [ ] Endpoint monitoring playbook

#### Not required, but nice to have artifacts
  - [ ] **Content source of truth**: link to CAIA Content feedback, such as a content source of truth.
  - [ ] **Information Architecture spec**: link to CAIA IA feedback, such as an IA spec.
##### Platform actions

- [ ] Update this ticket with the Zoom recording
  - Recording URL: 
  - Password:
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [ ] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [ ] Link to the Readiness Review ticket below

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by MOStudioCarolyn** [comment]
![Screen Shot 2023-07-26 at 11.09.36 AM.png](https://images.zenhubusercontent.com/62598d5028d5ea49e32f0d98/2d8ff5a1-6479-4c38-a6fa-1c66e397d504)

**Comment by MOStudioCarolyn** [comment]
![Screen Shot 2023-07-26 at 11.09.36 AM.png](https://images.zenhubusercontent.com/62598d5028d5ea49e32f0d98/b64b45b1-3f10-42eb-9740-dfb263bede26)

**Comment by erinrwhite** [comment]
No IA feedback for the design intent - thanks for bringing this to us!

**Comment by erinrwhite** [comment]
No IA feedback for Midpoint Review - hoping the gradual rollout yields helpful data for the team. Thanks!

**Comment by CherylEvans** [comment]
No Content feedback for the Async MPR. :-)

**Comment by NaomiPMC** [comment]
@shiragoodman this work is no longer relevant and is outdated. This has shifted to the overall identity work. Per Danielle, ticket can be closed.
