### ISSUE TITLE
initiate discovery to get more rapid analysis results on email outreach

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#63103]
# Tasks - Solution for pulling VA.gov and SiS data/metrics and is not dependent on IAM infrastructure.  
(Note: this will not include the roughly 25%+ of the total authentication traffic which flows through SSOe but not VA.gov and SiS)
- [ ] Decide on KPIs based on available data, e.g. daily/weekly snapshots of distinct User/CSP counts
- [ ] Review design alternatives (Also see notes in https://app.zenhub.com/workspaces/logingov-adoption-team-632280b31e745000136a61fc/issues/gh/department-of-veterans-affairs/va.gov-team/63080)

# Tasks based on using SSOe Splunk as a datasource - HOLD
- [x] Create query in splunk to pull recurring user/CSP counts
- [ ] Create script to retrieve data from splunk
- [ ] Create scheduled Domo Workbench job to import into Domo cloud
- [ ] Rerun the test group extracts to also include secid, since 1) splunk records have SECID instead of ICN, 2) many users in MPI dataset don't have ICN associated, and 3) all records in MPI dataset have SECID.
- [ ] Import test groups into Domo with both ICN and SECID (hashed)
- [ ] Create Domo ETL to merge test groups with weekly SSOe authn usage data
- [ ] Create/Update Domo visualizations

# Tasks related to Domo Workbench (will need to move this to another ticket - HOLD
- [ ] Investigate where to host Domo Workbench so it can run scheduled jobs
- [ ] Redeploy Domo Workbench

**Comment by sdickson-gt** [comment]
@djmunoz1 I'm working on pulling daily/weekly snapshots of distinct user/CSP totals. The visualization would show these snapshots updated over time in a view that's similar to our existing CSP unique users report, but limited to users of each test set.  Would this work in terms of addressing effectiveness or did you have anything in mind?
And again, the main technical hurdle is deploying/hosting Domo Workbench such that it can run these scheduled jobs in an ongoing basis. Until then, we can check weekly the Domo Workbench is running but this is a very short term solution.
