### ISSUE TITLE
Document unit test coverage percentage within QA Standards for Staging Review

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#63106]
## User Story
As an OCTO leader, I want to see what percentage of unit test coverage VFS teams are meeting so that I have data to make the necessary changes. 

Assignee: @it-harrison 
Peer Reviewer: @CherylEvans 

## Description
In the QA Standards template for Staging Review, Governance QA only documents if the unit test coverage QA Standard was met or not met. However, since the unit test coverage standard is quantifiable, with a meets expectation of 75%, we want to start documenting the unit test coverage percentage in all future Staging Reviews.

The purpose of this ticket is to update the QA Standards operational process and gh template to document the actual unit test coverage percentage of VFS team products at Staging Review. 

## Impacted Artifacts
[QA Collab Cycle findings for Staging](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-feedback%2C+QA%2C+Staging%2C+qa-standards&projects=&template=collab-cycle-qa-findings-staging.md&title=QA+Standards+-+VFS+Team+-+VFS+Product) template
[How to complete a QA review for the Staging review touchpoint](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2428010558/How+to+complete+a+QA+review+for+the+Staging+review+touchpoint)

## Tasks
- [ ] Modify the template so that there is a dedicated space for documenting the unit test coverage percentage
   - This should be required whether the standard is met or not met
- [ ] Update the operational guidance to add a step for documenting the unit test coverage percentage
   - Question - is this something that's calculated by QA reviewer or is this perceivable someplace else? If it's calculated, be sure to include how to calculate the percentage. thanks!

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] VFS team members are informed of the unit test coverage percentage whether they meet or do not meet the unit test coverage standard
- [ ] Governance team members have a defined process for documenting the unit test coverage percentage

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
@CherylEvans this ticket is ready for review:
* [draft of updated](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2749530113/63106+-+How+to+complete+a+QA+review+for+the+Staging+review+touchpoint) How to Complete a QA review for the Staging Review touchpoint
* [PR](https://github.com/department-of-veterans-affairs/va.gov-team/pull/64338) for updated template

**Comment by CherylEvans** [comment]
@it-harrison, I made a few changes to How to Complete a QA review for the SR touchpoint for grammar punctuation and changed passive to active voice. Great job on this! The PR looks good to merge. Feel free to let me know if you have any questions or concerns. :-)
