### ISSUE TITLE
[FE] Bug -- Formatting in Connected Apps section is busted if logo is too large

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#63112]
## Steps to reproduce

1. Log in to staging with user 1.
2. Go to Profile > Connected apps. You'll see that the second app in the list -- Lighthouse Pivot Codebuild Regression Test -- has a huge VA.gov logo. This appears to be breaking the formatting of the connected apps container.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/34068740/dab58d22-c6d0-4ea7-bea6-767fc5d28a6f)

## Tasks

- [ ] Log in to staging to view bug.
- [ ] Fix formatting issue so that the information in the busted connected apps block fits in its container.
- [ ] Have Travis validate with staging user 1.

**Comment by mtcA6** [comment]
potentially a duplicate of #32963 maybe combine after refinement 8/9

**Comment by Samara-Strauss** [comment]
It probably is a duplicate! Thank you for finding this!

**Comment by mtcA6** [comment]
@Samara-Strauss wasn't a dupe, similar but not a dupe. Our new engineer just fixed it.
