### ISSUE TITLE
Update Helm Templates to Support Multiple Apps

### ISSUE THREAD

**Issue by kingbmike** [department-of-veterans-affairs/va.gov-team#63138]
## Summary
Update our helm templates to support multiple apps.

## Tasks
- [x] Refactor templates in `identity-helm-library`
- [x] update application manifests to use refactored templates
  - [x] deploy api
  - [x] deploy ui
- [x] Update `identity-dashboard-api` deploy pipeline to update image tag in new location
- [x] Update `identity-dashboard-ui` deploy pipeline to update image tag in new location
