### ISSUE TITLE
[CDP] Disable all debt_letters fetching based on feature flag

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#63135]
## Issue Description
Due to privacy concerns the `debt_letters` endpoint has been disabled and a feature flag was created to prevent calls while it's down. It seems as if there may still be some calls being made [based on Sentry errors that have been coming through](https://dsva.slack.com/archives/CPE4AJ6Q0/p1691071147008759?thread_ts=1691071005.079549&cid=CPE4AJ6Q0). 

We should leverage the `debt_letters_show_letters_vbms` to disable any remaining calls while we sort out a solution.

---
## Tasks
- [ ] Identify the `debt_letters` calls still being made and disable them with the feature flag

## Acceptance Criteria
- [ ] No `debt_letters` calls are being made while the feature flag is disabled. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
