### ISSUE TITLE
[spike] NOD | Transition Sentry Monitoring to DataDog

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#63147]
## Issue Description

In https://github.com/department-of-veterans-affairs/va.gov-team/issues/58173, Robin (@Mottie) did an excellent job filtering out noise from our NOD Sentry dashboards. But in doing so, Robin discovered that Sentry has a cap on the number of log filters you can add (400 char max). We can work around that cap for the time being, by cross-referencing a document Robin put together: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits-decision-reviews/monitoring/sentry-filters.md. But, if we're to present a scalable error monitoring solution to VA, we might want a platform with more flexibility. The goal of this spike is to determine whether DataDog could be that platform. If so, then we would rename and update https://github.com/department-of-veterans-affairs/va.gov-team/issues/58172 and https://github.com/department-of-veterans-affairs/va.gov-team/issues/58170 accordingly.

## Tasks
- [ ] Check whether we can create front-end error monitoring dashboards comparable to Sentry's, in terms of the content of each error.
- [x] Check whether DataDog can handle all the filters that we hoped Sentry could handle.
- [ ] If it can, rename and update https://github.com/department-of-veterans-affairs/va.gov-team/issues/58172 and https://github.com/department-of-veterans-affairs/va.gov-team/issues/58170 accordingly.

## Definition of Ready
- [x] Get DataDog write access that would allow us to put together some kind of error monitoring dashboard

## Definition of Done
- [ ] We know whether DataDog can do what we hoped Sentry could do.

**Comment by Mottie** [comment]
I met with Steve Albers today and he suggested we look into the following:
- [Custom metrics](https://docs.datadoghq.com/metrics/custom_metrics/)
- [Synthetic monitoring](https://docs.datadoghq.com/synthetics/)
- [Funnel analysis](https://docs.datadoghq.com/real_user_monitoring/funnel_analysis/)

So that our team can get a better idea of how our apps are performing in production. Once these are set up, additional monitoring can be added so that we can be alerted to problems within the flow.

**Comment by Mottie** [comment]
So far, I've added these to the dashboard:

### NOD RUM page errors powerpack

<img width="1254" alt="Screenshot 2023-11-08 at 2 43 52 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/545b6528-2207-48fa-b272-010021293853">

### NOD filtered frontend errors

<img width="1142" alt="Screenshot 2023-11-08 at 2 44 14 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/c3f52d57-5221-4849-a499-9731d74a7b8d">

Which is filtering out 11 common (global) errors:

```sh
-@error.message:(
  csp_vio* OR # csp_violation: 'blob' blocked by 'worker-src' directive
 *MutationObserver* OR # console error: TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
 *Maximum\ call\ stack* OR # Maximum call stack exceeded
 *isProxied* OR # undefined is not an object (evaluating 'a.isProxied')
 *scrollHeight* OR # console error: TypeError: null is not an object (evaluating 't.scrollHeight')
 *beforeunload* OR # intervention: Blocked attempt to show a 'beforeunload' confirmation pane
 *ChunkLoadError* OR # Chunk load errors (from CMS?)
 *Minified\ React\ error* OR # Minified React error loading 
 *max\ sessionReplay* OR # Reached max sessionReplay events size queued for upload: 3MiB
 *Script\ error* OR # Uncaught "Script error."
 Sheet\ constructor* # CMS error
)
```

### NOD funnel analytics

<img width="1148" alt="Screenshot 2023-11-08 at 2 44 24 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/40ba6125-093f-48b1-a2b3-3d09c75a8597">

**Comment by HeatherWidmont** [comment]
@Mottie to discuss with @data-doge when they get back to see what else needs to be added

**Comment by saderagsdale** [comment]
@Mottie and @data-doge will discuss in Monday's L&M meeting.

**Comment by Mottie** [comment]
It seems that we need to do a bit more work and discovery to get all the same errors in Datadog that we're already seeing in Sentry. We'll need to meet with Steve Albers to discuss what needs to be done. I think we'll need to [initialize Datadog logging on the frontend](https://www.datadoghq.com/blog/monitor-javascript-console-logs/)

**Comment by HeatherWidmont** [comment]
@Mottie meeting with Steve later today so he will bring it up then

**Comment by HeatherWidmont** [comment]
@Mottie to meet with Datadog team in their office hours next Monday to discuss further. @data-doge may attend

**Comment by saderagsdale** [comment]
Need to figure out how to access data in DataDog.

**Comment by saderagsdale** [comment]
Moved to the next sprint to make room for priority work.

**Comment by Mottie** [comment]
@saderagsdale I think this [Notice of Disagreement dashboard](https://vagov.ddog-gov.com/dashboard/tvp-imf-tb7/benefits-notice-of-disagreement?view=spans) work is mostly done. I'm working on https://github.com/department-of-veterans-affairs/va.gov-team/issues/72855 to improve logging within DataDog now, so I think we can close this ticket.

**Comment by saderagsdale** [comment]
@Mottie Coolio. Did you review with the other devs?

**Comment by data-doge** [comment]
@Mottie I think we can close this ticket so long as DataDog (at DD office hours or elsewhere) can confirm that we are getting 100% of javascript errors from our NOD app.

**Comment by saderagsdale** [comment]
@anniebtran @Mottie @shaunburdick @dfong-adh will huddle to check if there's anything we need to capture or learn to look up in Data Dog before closing this ticket.

**Comment by saderagsdale** [comment]
Will review with Shaun tomorrow.
