### ISSUE TITLE
PM | Disability Rating | Phased Release  (10%, 25%, 50%,🚨100%🚨)

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#63159]
## Artifacts 
[Name tag disability rating Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/nametag)
[Initiative Brief](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/nametag/evssMigrationToLH) 

## Monitoring
[GA Dashboard ](https://analytics.google.com/analytics/web/#/dashboard/DRqBrmiyTD6l8L75rei0fw/a50123418w177519031p176188361/)

## Release Plan
[go/no-go prod convo](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63199)
[Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/nametag/evssMigrationToLH/releasePlan.md)

## Tasks

<details><summary>Completed Phases</summary>

```[tasklist]
### 10% rollout
- [x] Update feature flags to make the feature visible in Production for 10% of users
- [x] Track/monitor analytics
- [x] Validate on Prod with PM and PO
```

```[tasklist]
### 25% rollout
- [x] Update feature flags to make the feature visible in Production for 25% of users
- [X] rolled back due to increased errors, GH document from Tom needed. 
- [X] Track/monitor analytics
- [X] Validate on Prod with PM and PO
```

```[tasklist]
### 50% rollout 9/12
- [x] Update feature flags to make the feature visible in Production for 50% of users
- [X] Track/monitor analytics - 97% successful 
- [X] Validate on Prod with PM and PO ( [thread to launch to 100%](https://dsva.slack.com/archives/C909ZG2BB/p1695134342109399) )
```

</details> 

<details open>
<summary>Current Phase</summary>

```[tasklist]
### 100% rollout 9/19
- [ ] Update feature flags to make the feature visible in Production for 100% of users
- [ ] Track/monitor analytics, launched to 100 9/19, saw a spike in errors, rolled it back, but now things are going smoothly
- [ ] Validate on Prod with PM and PO
```
</details>

## Acceptance Criteria
- [ ] feature is fully deployed in production

**Comment by Samara-Strauss** [comment]
Does this still need to be open?
