### ISSUE TITLE
NOD | Update and match SC Review and Submit Error Validation

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#63155]
## Value Statement
**_As a_** veteran
**_I want to_** know exactly what is causing an error in my submission
**_So that_** I can fix the errors and submit my form

---
## Background Context

As it's unclear how the applicant is able to reach the Review and Submit page with errors pending, we are adding validation on the Review and Submit page and notifying veterans if there is an error within the sections they need to fix.

We've done something similar for Supplemental Claims: [[bug] Missing in-line errors for Review and Submit validation #56608](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56608)

<details><summary>Currently on staging</summary>

![Screenshot 2023-08-04 at 10 04 55 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/111457818/0bda228a-6797-41de-946c-c7c47b25c99f)

![Screenshot 2023-08-04 at 10 18 48 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/111457818/980f8df2-511a-4272-ab5d-eac4e78e6b0e)

</details>

## Acceptance Criteria
- [ ] Validation is in place for Review and Submit page to check for errors.
- [ ] In-line errors will show where applicable

## Designs and Build Notes
- [DESIGN](https://www.sketch.com/s/0424c51d-7818-43ea-8821-6de91eb7ab27/v/D5gQdW/a/pY4n3Kk)

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [x] Add in-line error styling to sections with errors/empty fields
- [x] Add missing in-line error for Board Review Option
- [x] Add missing in-line error for hearing Option

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
Asked @Mottie a clarifying question bout inline error styling in Slack.

**Comment by eileen-coforma** [comment]
Confirmed error messaging is there.
