### ISSUE TITLE
[FE] 10-10EZ - Allow for resubmission of ID Form

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#63165]
## Description
After a guest user successfully completes the enrollment verification form (ID form), they are taken to the first form page. If they choose to navigate back to the ID form page, either with the browser or with the back button on the form page, they get stuck without a hard refresh of the page. 

This is being caused by the previous verification data persisting in the Redux state. The page does not reset that data on first render, it simply continually checks for a change in the enrollment status variables, which may only happen the very first time the form is submitted. We need to be able to account for multiple submissions and check the enrollment status data on each submission.

## Steps to Recreate
- Navigate to, fill out and submit ID form
- Once on first form page, use the back button to navigate back to the ID form
- Fill out and submit again (using any data values)

## Tasks
- [x] Update actions and reducers to allow for resetting enrollment status data
- [x] Verify user can advance to the application on each successful submission of the ID form
- [x] Validate ID form data is being set in state on each successful submission

## Acceptance Criteria
- Users can advance to the application on each successful submission of the form, regardless of how many times they submit it.

**Comment by longmd** [comment]
@hdjustice , this has been completed and resubmissions are now available.

**Comment by hdjustice** [comment]
Validated that the initial screener page asking for Name, DOB, and SSN can be resubmitted in the event that a user goes back to that page.  Any data entered in the following pages is still populated.
