### ISSUE TITLE
Content Gap Issues in Pages

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#63173]
## Info
There are big gaps between where content should start on the page and where the text actually begins.

Links to example pages are:

- https://depo-platform-documentation.scrollhelp.site/research-design/
- https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/

## Tasks

- [x] Submitted ticket with k15: https://k15t.jira.com/servicedesk/customer/portal/3/user/login?destination=portal%2F3%2FKS-20443
- [x] Wait for information from k15 regarding issue
- [x] Check to see if issue has been resolved on front end of website
