### ISSUE TITLE
[SW] Add additional info component dependents explainer to dependents pages 

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#63174]
## Issue Description
Dependents pages need an additional info component explaining what a dependent is. 

---
## Tasks
- [x] Add an additional info box explaining what a dependent is to the Dependents pages. 

## Acceptance Criteria
- [x] Additional info box explaining what a dependent is added to the Dependents pages
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by josephrlee** [comment]
Closing this issue as it's a duplicate of #63175
