### ISSUE TITLE
[SW] Add additional info component dependents explainer to dependents pages 

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#63175]
# Issue Description
Dependents pages need an additional info component explaining what a dependent is. 

<a href="https://sketch.com/s/50583485-ba58-4ef8-ae04-2c274a792547/a/g1ZpmMj/play"><img src="https://images.zenhubusercontent.com/63ea96045c6deec1c9a25425/60f030a5-3ddb-4b51-aba3-2634ad46eb89" alt="Screenshot showing additional info component for dependents explainer text"/></a>

---
## Tasks
- [x] Add an additional info box explaining what a dependent is to the Dependents pages. 

## Acceptance Criteria
- [x] Additional info box explaining what a dependent is added to the Dependents pages
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by josephrlee** [comment]
This is done, just waiting for CI stuff to pass before I can merge it!

cc: @HeatherRienks @Tom-Davis

**Comment by HeatherRienks** [comment]
@josephrlee - any update on this one?

cc: @Tom-Davis

**Comment by josephrlee** [comment]
@HeatherRienks , dealing with lots of CI issues, should be able to get it sorted out in the next couple of hours.
