### ISSUE TITLE
[BE] Log additional context to Sentry

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#63171]
## Description
Modify Service class to log additional context to sentry

## Tasks
- [ ] [BE] **Modify service class**
- [ ] [BE] **rspec**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
