### ISSUE TITLE
[SW] Update sign-in alert to use VA Web component

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#63191]
## Issue Description
The [sign-in component](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/financial-status-report/components/shared/UnverifiedPrefillAlert.jsx) on the FSR uses an outdated custom component that needs to be modernized to use the latest [VA web component](https://design.va.gov/storybook/?path=/docs/components-va-alert--sign-in-to-start-your-application).

---
## Tasks
- [ ] Convert '[UnverfiedPrefillAlert.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/financial-status-report/components/shared/UnverifiedPrefillAlert.jsx)' to [VA web component](https://design.va.gov/storybook/?path=/docs/components-va-alert--sign-in-to-start-your-application)

## Acceptance Criteria
- [ ] Old custom component uses new VA web component.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by josephrlee** [comment]
Marking this as closed as it was taken care of by a [platform update](https://github.com/department-of-veterans-affairs/vets-website/commit/7c4fb395bea7d981763e1971665de1cd405f28b0)! 

cc: @HeatherRienks @Tom-Davis
