### ISSUE TITLE
[SW] Update sign-in alert to use VA Web component

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#63192]
## Issue Description
The [sign-in component](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/financial-status-report/components/shared/UnverifiedPrefillAlert.jsx) on the FSR uses an outdated custom component that needs to be modernized to use the latest [VA web component](https://design.va.gov/storybook/?path=/docs/uswds-va-alert--sign-in-to-start-your-application).

---
## Tasks
- [ ] Convert '[UnverfiedPrefillAlert.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/financial-status-report/components/shared/UnverifiedPrefillAlert.jsx)' to [VA web component](https://design.va.gov/storybook/?path=/docs/uswds-va-alert--sign-in-to-start-your-application)

## Acceptance Criteria
- [ ] Old custom component uses new VA web component.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by josephrlee** [comment]
@hdjustice @Tom-Davis , here's the ticket, it just needs to be pointed by FE and groomed!

**Comment by hdjustice** [comment]
I believe this is meant for @HeatherRienks  😃

**Comment by HeatherRienks** [comment]
Thanks @hdjustice! Go Team Heather :)

**Comment by josephrlee** [comment]
Opps, sorry about that @hdjustice!

**Comment by HeatherRienks** [comment]
Will bring into S106.

**Comment by OptionSelect** [comment]
Per convo with Joe this ticket is about replacing the divs with default form classes with VaAlert components with usdws prop.

**Comment by OptionSelect** [comment]
Per convo with Andrew we are not actually in control of component that actually needs updates. It is the SaveInProgressIntro component that needs to be updated on the platform side to reflect the proper CSS. 

Additionally, when compared to other apps that I know are good like Rob's stuff I found he hides it altogether, I searched through other apps but could not get their rootURL's to populate a page locally to verify that this problem exists in their app as well. 

Planning to open platform ticket today.

**Comment by OptionSelect** [comment]
Link to platform support thread: https://dsva.slack.com/archives/CBU0KDSB1/p1702479393212889

**Comment by OptionSelect** [comment]
Per convo in platform support thread next steps are to investigate behavior that we would lose going to va-alert and how we can support it.

**Comment by OptionSelect** [comment]
Per convo with Andrew, need to speak with Rob Garrison about actual LOE to make this conversion due to lack of knowledge in this area and his name is in the component a lot so he seems to be the SME!

**Comment by HeatherRienks** [comment]
@OptionSelect and @Dr-Pongo meeting with Rob Garrison today (1/2/24)

**Comment by OptionSelect** [comment]
This will be fixed by Tze's PR here https://dsva.slack.com/archives/CPE4AJ6Q0/p1704297403922709

https://github.com/department-of-veterans-affairs/vets-website/pull/27243/files#diff-711311ae8ddf6a57d793cd042b5d58eea23c185c45d02b9d288c4dfddee33ef0
