### ISSUE TITLE
Identify discrepancies between current and unreleased 1010-CG

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#6319]
## User Story or Problem Statement

Problem description. How might we ensure that we launch a version of the 1010-CG that matches the form that is currently available, but be ready to switch to the updated version once it's approved by OMB?

---
## Tasks
- [ ] Documented in Github
## Acceptance Criteria

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by psanders86** [comment]
# 10-10CG paper form analysis
Purpose: To identify all discrepancies between the current and unreleased 10-10CG paper forms.

## Issue 1: Preamble
- On page 1, Paragraph 1, the unreleased form deletes the requirement that the VA will perform a clinical assessment of the Veteran before determining their eligibility.

**CURRENT FORM:**
**What is VA Form 10-10CG used for? **
"To assist for VA’s Program of Comprehensive Assistance for Family Caregivers. VA will use the information on this form to assist in determining your eligibility, a clinical assessment will also be required. An eligible Veteran may appoint …”

**UNRELEASED FORM:**
**What is VA Form 10-10CG used for? **
“To assist for VA’s Program of Comprehensive Assistance for Family Caregivers. VA will use the information on this form to assist in determining your eligibility. An eligible Veteran may appoint …”

## Issue 2: Getting help
- On Page 1, Paragraph 2, the unreleased form modifies how an applicant can get assistance in filling out the form.

**CURRENT FORM:**
**Where can I get help filling out the form and answers to questions? **
"You may use ANY of the following to request assistance: Ask VA to help you fill out the form by calling us at 1-877-222-VETS (8367). Access VA’s website at http://www.va.gov and select “Contact the VA. Locate and contact …” 

**UNRELEASED FORM:**
**Where can I get help filling out the form and answers to questions?**
"You may use ANY of the following to request assistance: Ask VA to help you fill out the form by calling us at 1-877-222-VETS (8367). Access VA’s website at http://www.va.gov and select “Contact Us.” Locate and contact …” 

## Issue 3: Caregiver Support Coordinator definition
- The unreleased form removes the capitalization of “Caregivers” and “"Caregiving."

**CURRENT FORM:**
**Caregiver Support Coordinator (CSC):**
“A VA clinical professional who connects Caregivers of Veterans with community resources offering supportive programs and services. Caregiver Support Coordinators are located at every VA medical center and are designated specialists in Caregiving issues.” 

**UNRELEASED FORM:**
**Caregiver Support Coordinator (CSC):**
“A VA clinical professional who connects caregivers of Veterans with community resources offering supportive programs and services. Caregiver Support Coordinators are located at every VA medical center and are designated specialists in caregiving issues.” 

## Issue 4: Representative definition
- In the definition for Representative, the unreleased form changes the language when referring to POA/Representative documentation.

**CURRENT FORM:**
**Representative:**
“Refers to a Veteran’s or Servicemember’s court-appointed legal guardian, Durable POA for Health Care, or other designated health care agent. Copies of documentation regarding representatives are requested on this application.”

**UNRELEASED FORM:**
**Representative:**
“Refers to a Veteran’s or Servicemember’s court-appointed legal guardian, Durable POA for Health Care, or other designated health care agent. Attach POA/Representative documents to the application if applicable.”

## Issue 5: Directions to submit the application
- The unreleased form removes a description of mailing in the form as an “expedited processing” option and rephrases the text in the fourth option to include the Health Eligibility Center.

**CURRENT FORM:**
**Submitting your application.**
1.	Read Paperwork Reduction and Privacy Act information.
2.	The Veteran or an individual delegated as the Veteran’s representative/POA must sign and date the form.
3.	Attach POA/Representation documents to the application, if applicable.
4.	For expedited processing, mail this application to:
**&nbsp&nbsp&nbsp&nbspProgram of Comprehensive Assistance for Family Caregivers**
**&nbsp&nbsp&nbsp&nbspHealth Eligibility Center**
**&nbsp&nbsp&nbsp&nbsp2957 Clairmont Road NE, Ste 200**
**&nbsp&nbsp&nbsp&nbspAtlanta, GA 30329-1647**
If you prefer to present or take this application in person, you may hand carry the printed and signed application to your local VA Medical Center Caregiver Support Coordinator (CSC). To obtain the name of your local CSC, contact the Caregiver Support Line at **1-855-260-3274 or go to http://www.caregiver.va.gov. and use the Find your Local Caregiver Support Coordinator option.**

**UNRELEASED FORM:**
**Submitting your application.**
1.	Read Paperwork Reduction and Privacy Act information.
2.	The Veteran or an individual delegated as the Veteran’s representative/POA must sign and date the form.
3.	Attach POA/Representation documents to the application, if applicable.
4.	Submit the completed form to the Health Eligibility Center using the address below or submit the form to your local VA Medical Center Caregiver Support Coordinator. If you do not know the name and address of your local Caregiver Support Coordinator(s) you can go to http://www.caregiver.va.gov and use the Find Your Local Caregiver Support feature. You may also contact the Caregiver Support Line at 1-855-260-3274
**&nbsp&nbsp&nbsp&nbspProgram of Comprehensive Assistance for Family Caregivers**
**&nbsp&nbsp&nbsp&nbspHealth Eligibility Center**
**&nbsp&nbsp&nbsp&nbsp2957 Clairmont Road NE, Ste 200**
**&nbsp&nbsp&nbsp&nbspAtlanta, GA 30329-1647**
If you prefer to present or take this application in person, you may hand carry the printed and signed application to your local VA Medical Center Caregiver Support Coordinator (CSC). To obtain the name of your local CSC, contact the Caregiver Support Line at **1-855-260-3274 or go to http://www.caregiver.va.gov. and use the Find your Local Caregiver Support Coordinator option.**

## Issue 6: Tax Identification numbers
- The revised form gives the Veteran/Servicemember and the family caregivers the option to use a Tax Identification number in addition to Social Security. The current form just asks for Social Security numbers.
## Issue 7: Telephone numbers
- The revised form asks the Veteran/Servicemember and the family caregivers for their primary phone numbers and alternate phone numbers. The current form asks for “Telephone Number” and “Cell Number.”
## Issue 8: Primary Family Caregiver health information
- The revised goes into greater detail in asking the primary family caregiver for their medical information. 

**CURRENT FORM:**
**Enrolled in Medicaid or Medicare?**
&nbsp&nbsp&nbsp&nbsp [x] yes &nbsp&nbsp&nbsp&nbsp[x] no 
**Other health insurance?**
&nbsp&nbsp&nbsp&nbsp [x] yes &nbsp&nbsp&nbsp&nbsp[x] no 
Name: _______________________________________

**UNRELEASED FORM:**
**Currently enrolled in Medicaid?**
&nbsp&nbsp&nbsp&nbsp [x] yes &nbsp&nbsp&nbsp&nbsp[x] no 
**Currently enrolled in Medicare?**
&nbsp&nbsp&nbsp&nbsp [x] yes &nbsp&nbsp&nbsp&nbsp[x] no 
**Currently enrolled in Tricare?**
&nbsp&nbsp&nbsp&nbsp [x] yes &nbsp&nbsp&nbsp&nbsp[x] no 
**Currently enrolled in CHAMPVA?**
&nbsp&nbsp&nbsp&nbsp [x] yes &nbsp&nbsp&nbsp&nbsp[x] no 
**Other health insurance?**
&nbsp&nbsp&nbsp&nbsp [x] yes &nbsp&nbsp&nbsp&nbsp[x] no 
Name: _______________________________________

**Comment by psanders86** [comment]
Updated this because issue No. 5 was omitted on the first draft of this ticket.
