### ISSUE TITLE
[BE] Remove 1010CG record_submission_success code

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#63214]
## Background
1010CG `record_submission_success` code was used with MuleSoft v1 and Datadog monitoring.  Since we have implemented MuleSoft v2, it appears that the code is no longer being used.

## Tasks
- [ ] Verify the code `record_submission_success` is not being used by any other systems
- [ ] Once verified, remove the code from the backend 10-10CG
- [ ] Validate no errors result from the code removal

## Acceptance Criteria
- The 1010CG `record_submission_success` code has been verified as not being used by any other systems and has been removed from the backend.
