### ISSUE TITLE
Make recommendations for integration from Front End TL; DR; into support documentation

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#63216]
## Description

We constructed our TL;DR; for support and I've sent that over to the support team. The intended plan, is to integrate this into support's documentation that they have running that serves as a reference for all people on support. However, with a lack of engineers on their team, they're unsure of which topics should go into which buckets. We need to make recommendations to them, based on their current documentation structure, of where these topics should exist in their page hierarchy.

Our support TL;DR; : https://vfs.atlassian.net/wiki/spaces/FEC/pages/2689892466/Frontend+Support+TL+DR

Support official documentation: https://vfs.atlassian.net/wiki/spaces/PTST/pages/2630353240/Advanced+Ticket+Support+Best+Practices

## Tasks

- [x] Look over all support topics in our TL;DR; and decide where they would fit in the support documentation as it currently exists.
- [x]  Make recommendations, document them here, and notify @CBonade that they're ready for delivery to the support team prior to closing this ticket.

## Acceptance Criteria

- [ ] Documentation recommendations have been delivered to the support team.

**Comment by rmessina1010** [comment]
**Deployment Failuress**

- Daily deployment failed the validate build status step


Add Tab:  **Test/CI Failures**

- CI Failure: Syntax error: Unexpected token '<single character>' in JSON at position 1


Add Tab:  **Running VA.gov locally**

- Content-Build local setup errors


Add Tab: VFS App
subtab: Setup

- Adding a new application to content-build's registry.json causes CI failure
- Adding a new application to vets-website src/application
- Changing an application's root url


subtab: Errors

- CSRF Token Failures


-
