### ISSUE TITLE
Remove vaccine CLP link on COVID pages 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#63212]
## Issue Description

We took down the COVID-19 vaccines CLP several months ago and did a redirect to our main COVID-19 vaccines page. We currently still have a link on our main vaccines page to the CLP that should be removed. 

Under the H2 "More information about getting your vaccine at VA" the link "Get COVID-19 vaccine advice from Veterans and VA health care providers" should be deleted. We also need to check if we link to it from anywhere else on the page or other COVID-19 pages.

## Tasks
- [x] Remove CLP link on vaccines page in English, Spanish, and Tagalog (Megan)
- [x] Check if the link is on any other pages and remove (Megan)
- [x] Review (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [ ] We're no longer linking to the redirected vaccines CLP

**Comment by megzehn** [comment]
Confirming that I removed this link on the COVID pages, published, and checked for other instances of it. Moving to validate.

**Comment by RLHecht** [comment]
@megzehn I also noticed in Drupal that the vaccines CLP is still set to published. We're now redirecting that page to our main vaccines page so I think we can archive it in Drupal.

**Comment by megzehn** [comment]
Thanks, Randi! The CLP is archived now.
