### ISSUE TITLE
FSR - Update transform and helpers part 2 (Expenses)

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-team#63224]
## Issue Description
Our final `transform` has gotten a little cluttered with the various feature flags and other general updates. Let's break it up into more manageable chunks. Mostly looking to break out separate feature flag functionality so we can more easily remove them. It could also help to organize by major chapters with comments describing the final pdf location the values will be populated in. 

We also noticed recently that our `helpers.js` has some transform specific functionality in there, but it might be easier to manage if they were separate from generic helper functions. 

---
## Tasks
- [x] Break out transform functionality by feature flag and chapter level calculations.
- [x] Update helpers so transform specific functionality is broken out

## Acceptance Criteria
- [x] Transform feature flag functionality is more manageable. 
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
We will plan to address this when @Dr-Pongo and @amponce are both back in the office.

@amponce and @Dr-Pongo has confirmed that this can be done post- MVP launch.

**Comment by amponce** [comment]
Pausing this until after everyone is back in town, the work is complete but changes need to be made to the streamline waiver process to support this change and it's not a good time to do that with everyone gone

**Comment by HeatherRienks** [comment]
@amponce - any update on this ticket? Thanks!

**Comment by Tom-Davis** [comment]
Moving to "ready" and we will validate in Sprint 108 after SW has had some time to be stable.

@HeatherRienks

**Comment by amponce** [comment]
The work is complete; we just need to get it through the review process in order to safely merge the code. Due to shifting priorities and risks during the streamlined waiver releases, we've moved this down the priority list. We want to ensure that the FSR calculations are stable and verified as accurate before introducing additional calculation updates

Once Mike confirms that the new asset calculations are behaving as expected, I'd like to move this back into verification and testing so we can merge the changes. However, I'm uncertain about the timeline at this moment.

**Comment by HeatherRienks** [comment]
@denisecoveyduc - please advise when Mike has confirmed that the new asset calculations are behaving as expected. See @amponce comment above and  we will proceed accordingly. Thanks!

cc: @Tom-Davis

**Comment by denisecoveyduc** [comment]
@HeatherRienks @amponce @Tom-Davis  Mike has confirmed that the current VODA calculations are in alignment with the VHA calculator and decision tree. That said I'd like to understand what additional calculation changes we will see as a result of this change.

**Comment by amponce** [comment]
@denisecoveyduc That's great to hear that everything is aligned!

This work mainly involves code cleanup and abstraction. The current data transformer has been difficult to work with due to its size and complexity. To address this, we've created this ticket to move the existing expense calculation logic to its own helper file. The core calculation logic remains virtually unchanged and is essentially a verbatim copy of the original. The main code updates are in the abstraction and the introduction of a new helper function, which provides us with more granular control over expense calculations.

**Comment by amponce** [comment]
Code review is completed and is currently awaiting merge
