### ISSUE TITLE
[UX][Research] Decide on Metrics to Measure Success for this Release

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#63233]
## Tasks
- [x] Decide on metrics to measure success for this release
- [ ] Determine how we will capture the metrics
- [ ] Create an analytics request, if need help from the Analytics team

**Comment by benbrasso-agile6** [comment]
#### Assumptions

- Any custom (API call) or VA component-based GA events remain as is. 
- We will feature flag these releases (to the extent possible) and do comparisons of success rate from existing experience to unified check in experience. For example, % of LoROTA complete -to- API Request check in success. If % is similar or greater than the existing experience, then we increase VISN rollouts.

#### Questions

- Assuming that any custom (API call) or VA component-based GA events remain as is in the applications, how are we going to distinguish GA events from the existing experience to the unified check in experience release? For example, % of LoROTA complete -to- API Request check in success. How would we be able to tell the difference in GA? Appending a value to GA events? Different page urls?  

#### Pre Check In

- How can we track the [demos don't need to be checked](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/mPEjZRV) scenario? Is that going to be a unique page url? If not, can we somehow fire a pageview event for this scenario? Other option? 
- How can we track a pageview of when there's an [pre-check-in action to complete](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/Go9LA1D)? For example, so we can track it separately from the demos don't need to be checked scenario?   
- Primary action link component click from [Appointments list page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/Go9LA1D)
- Primary action link component click from [Appt detail page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/aMkpY4r)

#### Check In

- How can track a pageview of when there's an [check-in action to complete](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/zyzA9wa)? For example, so we can track it separately from the demos don't need to be checked scenario?   
- Link clicks on the "Back to your appointments" link on all [check in success pages](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/pY4ZOjQ), which I think is built into the VA link component.

**Comment by benbrasso-agile6** [comment]
So, @loripusey, up to you what and when you want to deal with the next steps on this ticket, which requires some FE help. We need someone on FE to review this and think about answers to the questions I posed above. 

We could toss this ticket back in the backlog (knowing that this priority won't happen for a bit) and assign it to engineers when we are ready. That would be my recommendation (vs. bogging them down with it now).

**Comment by benbrasso-agile6** [comment]
Update to compare to previous historical date

**Comment by benbrasso-agile6** [comment]
Updated comment. Closing for now until we get closer to a major UCI release.
