### ISSUE TITLE
Move CC kickoff and touchpoint requests to Slack workflow(s)

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#63241]
## User Story
As a VFS team member I want to notify Governance of new CC kickoffs and touchpoint requests via an easy-to-remember tool in my own team's channel.

As a Governance team member, I want VFS teams to notify Governance of new scheduled CC touchpoints in a consistent format with no missing information.

Assignee: @briandeconinck 
Peer Reviewer: @CherylEvans 

## Description
This is a follow-up to #60853, which moved CC kickoffs and touchpoint scheduling from the #vfs-platform-support channel and into each VFS team's public channel. In that ticket, we set up Slackbot custom responses on certain keywords (`collab-cycle-kickoff`, `collab-cycle-design-intent`, `collab-cycle-midpoint-review`, and `collab-cycle-staging-review`). VFS teams would post the keyword, which would trigger Slackbot to reply with instructions for the VFS team to follow.

That solution turns out to not be viable, as [Slack does not support](https://slack.com/intl/en-gb/help/articles/202026038-An-introduction-to-Slackbot) custom responses in ["Connect" channels](https://slack.com/connect) featuring users from other Slack workspaces (as opposed to users added as DSVA members). Quite a few VFS teams now have at least one person in their public channel that's been added as a "Connect" user, meaning the custom responses will not be triggered in any of those channels. This was discovered when there was an attempted Collab Cycle kickoff in the #va-identity-product-team channel.

A possible alternative approach has been identified in [Slack workflows](https://slack.com/help/articles/16583775096083-What-is-a-Slack-workflow/). Per Slack's documentation, workflows *do* work with "Connect" channels, and the workflow builder may ultimately provide a better user experience than the previous MVP.

## Impacted Artifacts
- New Slack workflow(s) for CC kickoffs and touchpoint schedules
- Slack custom responses (can be removed when workflow(s) launched)
- Moderator Responsibilities for Kickoff
   - operational guidance for Governance team to follow
   - Design Intent, Midpoint Review and Staging Review code blocks
- Moderator Responsibilities for Design Intent
- Moderator Responsibilities for Midpoint Review
- Moderator Responsibilities for Staging Review
- Collaboration Cycle Request yaml template
- On Support Guidance
- Calendly flow for the DI/MPR event and SR event
- Any Platform website pages about the Collab Cycle that reference the old process
- Governance team Onboarding page (add new team members to list of people who can make changes to the workflows)

## Tasks

- [x] Triple-check Slack docs to verify this solution will actually work for all use cases
- [x] Build demo workflow
- [x] Test demo workflow with Governance team members
- [x] Test demo workflow with Carolyn in the #va-identity-product-team channel
   - Note: Tested with Lori in #check-in-experience, but same requirements met 
- [x] Make any necessary changes to the demo workflow to prep it for launch, and/or create additional workflow(s) to cover all use cases
- [x] Write change announcement post
   - [Draft announcements](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2739568739/63241+-+Change+history+change+announcement)
- [x] PR for change to Collab Cycle Request template
   - #63894 
- [x] Post announcement to #vfs-change-announcements
- [x] Write internal guidance on how to update workflows
   - [Draft Managing Slack "slash command" workflows](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2743697575/63241+-+Managing+Slack+slash+command+workflows) 
- [x] Update all documentation with new process
   - [x] [Draft - Collab Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2740486145/63241+-+Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities) 
   - [x] [Draft Moderator Responsibilities for Design Intent](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2741469185/63241+-+Design+Intent+-+Moderator+Responsibilities)
   - [x] [Draft Moderator Responsibilities for Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2741469218/63241+-+Midpoint+Review+-+Moderator+Responsibilities)
   - [x] [Draft Moderator Responsibilities for Staging Review - VFS](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2741469247/63241+Staging+Review+-+VFS+-+Moderator+Responsibilities)
   - [x] [Draft Moderator Responsibilities for Staging Review - DST](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2741469307/63241+-+Staging+Review+-+Design+System+-+Moderator+Responsibilities)
   - [x] [Draft On Support Guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2741469344/63241+-+On-Support+guide)
   - [x] [Calendly copy updates](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2741567489/63241+-+Calendly+update)
   - [x] [Draft Collab Cycle Kickoff (Platform website)](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2741469390/63241+-+Collaboration+cycle+kickoff)
   - [x] [Draft Onboarding](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2741567498/63421+-+Onboarding)
- [x] Remove Slack custom responses

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS teams can notify Governance team of their Collaboration Cycle kickoff and touchpoint requests via their own teams' Slack channel using a Slack workflow
   - [x] Collab Cycle kickoff
   - [x] Design Intent
   - [x] Midpoint Review
   - [x] Staging Review 

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
cc @shiragoodman

**Comment by CherylEvans** [comment]
@briandeconinck @shiragoodman Have the changes been made to the PW CC Kickoff page? If so, have they been published? I ask because I don't see them yet. :-) ![CC Kickoff_PW_Screenshot 2023-08-10 at 2.13.36 PM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/edd6c49a-6add-447a-82bc-74c7f6b1dc0d)

**Comment by shiragoodman** [comment]
good catch @CherylEvans ! Maybe we should do an audit of the Collab Cycle pages on PW to verify that there aren't other pages that need to be modified too. Can someone please add this page to the list of impacted artifacts above? ty!

**Comment by CherylEvans** [comment]
@briandeconinck @shiragoodman I made a few minor tweaks to the On-Support doc.

**Comment by shiragoodman** [comment]
@CherylEvans fyi Brian is still working on this. There's nothing to peer review yet.

**Comment by CherylEvans** [comment]
@briandeconinck @shiragoodman Sorry for jumping the gun! :-)

**Comment by CherylEvans** [comment]
@briandeconinck, That sounds good; let's sync tomorrow. :-)

**Comment by briandeconinck** [comment]
Moving to next sprint. No change in status since yesterday's update, still need to do a run-through with @CherylEvans

**Comment by CherylEvans** [comment]
@briandeconinck I made a few recommendations for consistency and voice. Looks great!
**For the Design Intent workflow, I recommend the following:**
Your review for Test 2 is confirmed. Check off the VFS actions in the ticket, including:

- If needed, add any additional VFS attendees, including accessibility and POs, to the invite on your calendar.

- Link all artifacts **ONLY** in the Design Intent artifacts section at least two days before the scheduled Design Intent. **Do NOT add artifacts to the Comments section.**

- For Design Intent we require user flows.

**Note:** We will reschedule the review if you do not provide artifacts at least two days prior. Please let us know if you have any questions.

**For the Midpoint Review workflow, I recommend the following:**
Your review for Test 3 is confirmed. Please be sure to check off the VFS actions in the ticket, including:

- **[Synchronous reviews]:** If needed, add any additional VFS attendees, including accessibility and POs, to the invite on your calendar.

- **[Asynchronous reviews]:** No meeting will take place. Governance team members will provide feedback by EOD on the scheduled date.

- Link all artifacts **ONLY** in the Midpoint Review artifacts section at least two days before the scheduled Midpoint Review. **Do NOT add artifacts to the Comments section.**

- Specify which pages in the prototype are included or excluded from the review.

- **Note:** We will reschedule the review if you do not provide artifacts or we don't know which pages are included in the review at least two days prior. Please let us know if you have any questions.

**For the Staging Review workflow, I recommend the following:**
Your review for Test 4 is confirmed. Please link all artifacts (including links to guidance, design system, Sketch, and storybook) at least four days before the scheduled Staging Review. **Do NOT add artifacts to the Comments section.**
**Note:** We will reschedule if you do not provide artifacts in the review at least four days prior. 
Please let us know if you have any questions.

**Comment by briandeconinck** [comment]
Working on implementing Cheryl's suggestions and updating critical public-facing docs so we can launch sooner rather than later.

@shiragoodman with Cheryl out today, would you review the [change history post and announcement](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2739568739/63241+-+Change+history+change+announcement)?

**Comment by briandeconinck** [comment]
Friday end-of-day update: I think I've got all of the draft documentation written!

Two pages on Platform website will be updated ([change history post](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2739568739/63241+-+Change+history+change+announcement) and the [Collab Cycle kickoff](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2741469390/63241+-+Collaboration+cycle+kickoff) page). If @CherylEvans can give those a quick look Monday morning we can queue those up for publishing and post the change announcement Monday afternoon!

**Comment by shiragoodman** [comment]
no additional comments!

**Comment by briandeconinck** [comment]
Thank you both!

**Comment by briandeconinck** [comment]
@CherylEvans This is ready for review! Here are all of the [documentation drafts](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2739404918/63241+-+Slack+workflow+documentation+changes). Most just have minor changes.

**Comment by CherylEvans** [comment]
@briandeconinck I reviewed all the documents and updated the specific ones we discussed yesterday. I also reviewed all for spelling, grammar, etc. improvements and made a few changes here and there where applicable, without changing the original context therein. My peer review is complete. :-) 
Big kudos for a tremendous effort!!

**Comment by briandeconinck** [comment]
All internal guidance is updated consistent with those drafts!

**Comment by briandeconinck** [comment]
Marking this as closed 🎉
