### ISSUE TITLE
Streamline Platform Orientation "Orientation Sessions" pages

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#63244]
## User Story
As a Platform Orientation host, I want to follow an efficient process for sharing the Orientation Sessions recordings so that I'm not asked to repeat duplicate steps. 

Assignee: @CherylEvans 
Peer Reviewer: @allison0034 

## Description
In the Asynch Orientation process launched in July 2023, Orientation hosts are asked to update 2 pages with the orientation session recording: 1) The [platform website Orientation Sessions page ](https://vfs.atlassian.net/wiki/spaces/GS/pages/2133393543/Orientation+Sessions) and 2) the [Confluence/operational Orientation Sessions page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2062024864/Orientation+Sessions). In addition to the recordings being duplicated across 2 pages, there's other information that exists in 2 places as well.

2 of the 8 hosts for the orientation sessions did not update the VFS-facing Platform Website page after hosting their orientation sessions. This is likely because they thought they had already updated the Platform Website page (when really they were updating the operational page). 

The purpose of this ticket is to remove the duplicate information from the operational page so that hosts only have to update 1 page when the recording, slide deck, or any changes are made to the orientation session. The operational page will only have internal-facing information NOT shared on the Platform Website page. We will also need to ensure that any Platform team member visiting the operational page know that this page works in tandem with the Platform Website Orientation Sessions page. It may also be helpful to rename the operational page so it doesn't have the same title as the Platform Website page. 

## Impacted Artifacts
[Orientation Host/Zoom Host Guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2656731745/Orientation+Host+Zoom+Host+Guidance)
[Platform website Orientation Sessions page ](https://vfs.atlassian.net/wiki/spaces/GS/pages/2133393543/Orientation+Sessions) 
 [Confluence/operational Orientation Sessions page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2062024864/Orientation+Sessions)
[Roles and Responsibilities for Orientation hosts](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2595094717/Roles+and+Responsibilities+for+Orientation+hosts)

## Tasks
- [x]  Rename the operational doc 
- [x]  Determine which fields should remain VFS-facing (Platform Website) and which fields are operational
- [x]  Modify the operational page to remove duplicate information
- [x]  Update the host guidance to reflect updating the Platform Website page only
- [x]  Review the roles and responsibilities doc to validate that no changes are necessary
    - If necessary changes are found, inform Shira and specify what needs to change
- [x] Notify Platform Orientation hosts via #platform-team Slack channel of updated Orientation Host/Zoom Host Guidance for next round of hosting in October

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Orientation hosts are only asked to update the youtube and/or slide deck information in 1 place
- [x] Information is not repeated across the operational and VFS-facing orientation sessions pages
- [x] The operational orientation sessions page has a new name so it is clear that this is an operational doc
- [x] There is a link/reference to the VFS-facing page from the operational page

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
Created Documentation Drafts

- [Roles and Responsibilities for Orientation hosts](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2742190128/63244+-+Cheryl+-+Copy+of+Roles+and+Responsibilities+for+Orientation+hosts)
- [Orientation Host/Zoom Host Guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2742124545/63244+-+Cheryl+-+Copy+of+Orientation+Host+Zoom+Host+Guidance)
- [Orientation Sessions (Internal/Operational)](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2742190081/63244+-+Cheryl+-+Copy+of+Orientation+Sessions+Internal)
- [Orientation Sessions](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2742124604/63244+-+Cheryl+-+Copy+of+Orientation+Sessions)

**Comment by CherylEvans** [comment]
@allison0034 Hi Allison.  I tagged you in the Drafts for your approval to delete the sections that I identified.  Let me know your thoughts when you have a moment to review them. Thanks again!

**Comment by CherylEvans** [comment]
Announcement for the #platform-team Slack channel:

:change-announcement: Attention: ALL Platform Orientation hosts 
As of 08/28/2023, We want you to know that we updated our Orientation Host/Zoom Host Guidance for the next round of hosting in October. 
Impact:  Hopefully, these updates will make it easier to understand the entire process. 
Documentation: Orientation Host/Zoom Guidance
Questions: Reach out to the Governance team by filing a support request on #vfs-platform-support

**Comment by shiragoodman** [comment]
@CherylEvans can you explicitly call out in the announcement that we've removed duplicate steps re: sharing the recording? Otherwise it's not saying much...

**Comment by CherylEvans** [comment]
@shiragoodman Better?

Announcement for the # platform-team Slack channel:

:change-announcement: **Attention**: ALL Platform Orientation hosts
**As of 08/28/2023**, We want you to know that we updated our guidance for the next round of hosting in October.
**Impact:** 
- We renamed the (Confluence/Operational) Orientation Sessions page to [Operational Guidance for Orientation Sessions](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2062024864/Orientation+Sessions) page.
- We deleted the following from the Operational Guidance for Orientation Sessions page. 
These duplicative fields exist on the Platform website’s [Orientation Sessions](https://vfs.atlassian.net/wiki/spaces/GS/pages/2133393543/Orientation+Sessions) page:
Overview Information
Calendly sign-up link
Slide deck
YouTube recording
- We updated the [Orientation Host/Zoom Host Guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2656731745/Orientation+Host+Zoom+Host+Guidance) page per the changes above.
- We updated the [Roles and Responsibilities for Orientation hosts](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2595094717/Roles+and+Responsibilities+for+Orientation+hosts) page per the changes above.
**Documentation:** Listed above
**Questions:** Reach out to the Governance team by filing a support request on # vfs-platform-support (edited)

**Comment by shiragoodman** [comment]
MUCH more clear. thank you!

**Comment by CherylEvans** [comment]
@allison0034 I am ready for your peer review of my drafts (above). 
The # platform-team Slack channel's announcement is in the comments above. Thank you!!

**Comment by allison0034** [comment]
@CherylEvans looks good! You can announce and close : )
