### ISSUE TITLE
[Rated Disabilities to Lighthouse] Create feature toggle

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#63252]
## Background
We need to create a feature toggle to use to facilitate a staged release of the LH version of the service

## Context
* Feature toggle name: `rated_disabilities_use_lighthouse`

## Tasks
- [x] Create new feature toggle (BE)
- [x] Update platform code and Rated disabilities app to recognize the new Feature toggle (FE)

## Acceptance Criteria
- [x] FE & BE PRs have been created
- [x] Feature toggle is ready to be used on the FE

**Comment by jerekshoe** [comment]
FE PR is approved, BE PR has to be approved and merged before FE PR can be merged
