### ISSUE TITLE
Content considerations for print/download component

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#63264]
## Issue Description
Bobby asked us to draft design system content considerations for the new print/download button component in the MHV medical records tool.
- [Sketch file with new button](https://sketch.com/s/4c2728ff-649d-4212-98d2-04c9b3fff9d4)

---
## Tasks
- [x] Draft content considerations
- [ ] Review
- [ ] Pass to Bobby

## Acceptance Criteria
- [ ] Bobby has content considerations for the new component

**Comment by laurwill** [comment]
@alexiawunder is this still a thing? that i should be doing?

**Comment by alexiawunder** [comment]
No, this can probably be closed. I will reach out to you again if we ever prioritize this again. Thank you!
