### ISSUE TITLE
Create and publish future rates page for MGIB-AD

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#63266]
## Issue Description
The education business line publishes Montgomery GI Bill Active Duty rates (that go into effect in October) in August so that students can have the information ahead of time.

Now that we have the education rates on our modernized pages, we need to create a separate rates page with this information explaining that these are for the future year.

Future rates url: https://www.va.gov/education/benefit-rates/montgomery-active-duty-rates/future-rates/
This should be placed in the left nav in the same position we have the other future rates pages.

Future rates to add to page: 
[FY2024 CH 30 COLA Rates.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/12290724/FY2024.CH.30.COLA.Rates.pdf)

Eventually we'll move these rates to our current rates page and change the information on the future rates page to tell users to check back to this page soon for upcoming rates.

---
## Tasks
- [x] Get future rates from EDU stakeholders (Beth)
- [x] Create Drupal page and input rates (Katherine)
- [x] Review rates (Laura)
- [x] Copyedit and publish (Megan)

## Acceptance Criteria
- [ ] New future rates page is live

**Comment by katherine-fung** [comment]
Hi @laurwill, 

The future rates page for MGIB-AD is ready for your review: 
http://preview-prod.vfs.va.gov/preview?nodeId=60786 

Noting that the PDF shows "BASIC JOB TRAINING RATES FOR PERSONS WITH REMAINING
ENTITLEMENT UNDER CHAPTER 34 OF TITLE 38, U.S.C." We don't put this on rates pages - Cinda says no one uses MGIB-AD this way.

**Comment by aprocik1** [comment]
Hey @megzehn, I've confirmed the future rates added by Katherine. This page is ready for your review. Thanks!

**Comment by megzehn** [comment]
Confirming I published these on Monday 9/11. Thanks all! 

CC @katherine-fung

**Comment by katherine-fung** [comment]
added to capacity tracker and closed
