### ISSUE TITLE
[SW] E2E Testing 

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#63263]
## Issue Description
Complete end to end testing in preparation for Streamlined Waiver launch (ideal release date: August 17, 2023)

---
## Tasks
- [x] Complete e2e tests

## Acceptance Criteria
- [x] We will launch with confidence that the streamlined waiver works as expected.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
