### ISSUE TITLE
[ANALYTICS] Create a VAMC-Upgrade Kick-OFF Package for the upcoming PAO Kick-Off Meeting [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#6327]
## Story
As a Public Affairs Officer, I need to know all of the items and areas of information needed for the upcoming VAMC-Upgrade, so I can easily provide that information to the VAMC-upgrade team.

## Goal
_Provide an easy to understand and easy to fill out/confirm spread sheet to the PAOs to provide pertinent information needed to complete the multiple layers of the VAMC-Upgrade_

## Objectives or Key Results this is meant to further
- _Increase System page completion each quarter_
- _Increase velocity overall through business optimization_

## Resources - Tools - Documentation
[VISN_4_Content_Stack](https://drive.google.com/drive/folders/1f_PRAt67ccYNm5DkJiAKwINsSX_S5_4o)
[VA.gov_Medical_Center_Map_Moqup](https://app.moqups.com/Rnc4BDEKrA/view/page/a9e1a59e9)

## Tasks
_Complete the following tasks for this Story:_
- [ ] Combine all of the data collection points into one Kick off package
- [ ] Make that package able to be broken into easily to follow and digestible sizes for PAO to respond quickly
- [ ] Where possible, try and make areas (Y/N) answers or provide limited work to hasten response
- [ ] Try and link (Automate file) from one worksheet/tab to another if possible. (Caregiver-Health services, etc)

## Acceptance Criteria
_Items that must be complete and provided in order be considered accepted for this story_
* Combine all of the data collection points into one Kick off package
* Make that package able to be broken into easily to follow and digestible sizes for PAO to respond quickly
* Where possible, try and make areas (Y/N) answers or provide limited work to hasten response
* Try and link (Automate file) from one worksheet/tab to another if possible. (Caregiver-Health services, etc)
