### ISSUE TITLE
Create Github Information

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#63289]
## Description 
As a platform support specialist I need clear information on Github access so that I can better serve users.

Github is not always handled by one team our source, and the process to obtain access to different repositories across the platform are unclear due to this. This was brought up as a bigger issue than anticipated when a user needed access to a private repository but couldn't even get access to their team's repository. Some items needed their own team's additional support, some items required Github support. 

In order to best clear this issue, there seems to be value in adding Github information for the support team to work off of. 

---

## Definition of Done
---

## Tasks 
- [ ] Gather list of repositories users who complete platform orientation are automatically granted access to
- [ ] Draft GitHub access policy on Platform side
- [ ] Draft what items go to GitHub support channel
- [ ] Compile clean document
- [ ] Present draft to team
- [ ] Approved by Alyssa, Brandan, and Joe. 
- [ ] Publish to Confluence
--- 

## Resources & Additional Info 
[Escalated Github access request that prompted need for more information
](https://dsva.slack.com/archives/C02RLAUM2LV/p1689965150539589)
---

**Comment by lindsay-insco** [comment]
Received additional information with some more questions and began flowchart for team members to quickly determine need to support or escalate to GitHub_information - will complete

**Comment by lindsay-insco** [comment]
Ticket broken down into 2 major tasks: Create base document and expand document

**Comment by lindsay-insco** [comment]
Published document to Platform Support internal Confluence and added to Launched Enhancements Document
