### ISSUE TITLE
Launch E2E Merge-Blocking Check based on Allow List Warnings

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#63288]
## Issue Description
The Allow List Merge Eligibility check has been merged into the main branch of vets-website. Currently the warnings are refreshing daily to ensure that no merges will be blocked until this is communicated out to all parties that will be impacted by it. Once a communication plan for launch has been drafted, it will need to be sent out along with some code changes to launch this initiative.

---
## Tasks
- [ ] Go/no-go with OCTO completed and given "go" status
- [ ] Communications plan delivered to all appropriate parties as drafted in communication plan ticket
- [ ] Confluence page updated to display warnings on the allow list page
- [ ] Slack notice added or updated to account for warnings
- [ ] Alter warnings code in qa-standards-dashboard-data repo to only apply a new warning if one doesn't exist
- [ ] Change github actions check for merge blocking to a required check to pass

## Acceptance Criteria
- [ ] All changes are communicated out clearly to all impacted parties
- [ ] All code associated with tests that have been disabled more than 90 days are being blocked from merging updates.
