### ISSUE TITLE
<Epic>[Maintenance A11y Audit]: CH36

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#63295]
## Auditor(s)

@joshkimux

## Automated

- [X] Run axe checks on every page or unique state (required)
- [ ] Run WAVE on every page if time allows. WAVE is more visual than axe or axe-coconut, but offers some excellent ways to identify nested headings and HTML5 landmark tags.

## Manual

- [X] Color contrast checks (recommend using whocanuse.com for beyond compliance reports)
- [X] Color blindness checks
- [X] Zoom layouts to 400% and inspect them for readability. If layouts break at 400%, I will start reducing them until they become stable, and log the zoom ratio when things started breaking.
- [X] Keyboard navigation

## Screen Reader

- [ ] Firefox and NVDA
- [X] Chrome and JAWs
- [X] iOS Safari and VoiceOver (Mobile)
- [ ] Safari and Voiceover (Desktop)
- [ ] Chrome and Talkback

## Staging or Production Link

[Staging link](https://staging.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/introduction)

## Test Users

```bash
Use unauthenticated version:
Tab to the form and select "Veteran."
Tab and select "No."
Tab and select "No."
Tab and select "No." You should hear no additional information.
```

## Audit spreadsheet
[Google sheet complex audit](https://docs.google.com/spreadsheets/d/1vvNb4JfDQsBSCAQ-ACvq4DujfEoLN2wJhzJb2KL3tKk/edit?usp=sharing)

**Comment by coforma-jamie** [comment]
This is a duplicate of #63362, closing
