### ISSUE TITLE
[Design] Update Final Wireframes for Confirmation & Demographic Pages

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#63301]
## Description
Add information to demographics pages and confirmation pages to help Veterans understand how to update their information, even if it’s correct at the time of check in

[Research report](https://docs.google.com/presentation/d/1_eZDeffijiFNyAVQWCq59dcs3VoIqTdd/edit?usp=sharing&ouid=108264709911522151146&rtpof=true&sd=true)

## Tasks
- [x] Create final mockups with callouts 
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [ ] UI review meeting with product/UX team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [x] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.

**Comment by ytsaoca** [comment]
Brainstormed on Mural: https://app.mural.co/t/civicactions3117/m/civicactions3117/1691967793005/dff09cffb6e91d717930a94263df32510dc0b5a7?sender=u70b8b2930b03d3ef317d2520

**Comment by cgednalske** [comment]
Thanks @ytsaoca! Do you want to also add your specific component thoughts (additional info vs. accordion) for the demographics screens to the [Sketch feature page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec) so those specifics are all in one place?

**Comment by cgednalske** [comment]
Update: we decided to use body/lead text for next of kin definition work, which allows us to use the additional info component for "how to update information" - component and placement example below ([Slack thread](https://dsva.slack.com/archives/C04J6H2LYUU/p1692124358878549)). We'll also add an accordion to the Check-in confirmation page like the one on the Pre-Check-in confirmation page.

Design solution is mocked up in [this Sketch page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/FC237584-412B-4022-8F41-C5EF958C790C/canvas). We are still working on specific content. 


<img width="334" alt="Screenshot 2023-08-16 at 8 33 11 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/79372956/c271c8ae-f434-45f9-b891-990cb5862c6a">

**Comment by cgednalske** [comment]
**Additional info components "how to update" instructions:** added to demographics pages in the Unified Check-in [Design page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/0EC89917-F949-4461-A7B3-32A5201FD2A2/canvas) (also added to 2.0 release). 

**Accordions with "how to update" instructions:** Added to the confirmation pages in the Unified Check-in [Design page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/0EC89917-F949-4461-A7B3-32A5201FD2A2/canvas). Updates made to Pre-Check-in accordions and new accordions added to Check-in

(only) Next of kin additional info added to Check-in and Pre-Check-in files.

@benbrasso-agile6 @kellysmith1008 ready for validation.

**Comment by loripusey** [comment]
@benbrasso-agile6 @cgednalske I'm not sure that this should be part of release 2; we had planned on making this next-of-kin content a "tech debt" item for this sprint but it seems that it has now become a component as opposed to just text. I think we should move it to its own release (maybe 2.2?); I am trying to keep release 2 just landing page and supporting content
Let's discuss at refinement

**Comment by benbrasso-agile6** [comment]
Taking a look at this now

**Comment by benbrasso-agile6** [comment]
2.2 is good or 3. You tell us which release you'd like it, and then we'll move it. @loripusey 

but, yes, agreed, this does not go WITH the next of kin tech debt release.

**Comment by benbrasso-agile6** [comment]
The things that are being added that we need to account for in releases are: 

1. Content changes to accordions on confirmation page (This should happen during the same sprint that confirmation pages get updated)
2. Add additional info component to contact information page and emergency contact information page. The content is different for pre-check-in vs. check-in. (I would pair this WITH the confirmation page release. So, potentially something else might have to move out of that release to make room for this work.) 

@loripusey

**Comment by benbrasso-agile6** [comment]
Confirming that no other design work needs to take place right now

**Comment by benbrasso-agile6** [comment]
Pulling this back to review a few comments I left in sketch for @cgednalske might need to carryover

**Comment by benbrasso-agile6** [comment]
Also need to update our annotations page in that file

**Comment by benbrasso-agile6** [comment]
Content difference in phone appts for accoridions - https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/a/YZ5jPym

**Comment by loripusey** [comment]
I would put this is Release 3, which is the confirmation page. We can extend to include the demographics pages.
@benbrasso-agile6

**Comment by loripusey** [comment]
done

**Comment by benbrasso-agile6** [comment]
k, Christina and I are gonna finish up one thing on this ticket then close

**Comment by benbrasso-agile6** [comment]
Ben - look at phone variations
Christina - update Design page to use closed accordions and a symbol

**Comment by cgednalske** [comment]
@benbrasso-agile6 Design page has been updated 👍 Symbols also created for those different accordion versions so we have them available.

**Comment by cgednalske** [comment]
Also updated the "how to update" text we discussed yesterday to address Kristen's concern. @benbrasso-agile6 if you want to take a quick look in the Design page flow, then I believe we're all set to close this ticket.

**Comment by benbrasso-agile6** [comment]
@cgednalske I finished with the annotations for accordions - https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/pYAo8vA#Version

It's also updated in the feature page. 

I left you a comment/reply to move your changes down to 1) Design - Release 2.0, and 2) Update your symbols to include the "expand all +"

**Comment by cgednalske** [comment]
"Expand all +" added to all design artboards! Think I got everything! Closing, but if anyone sees anything else let me know 👀
