### ISSUE TITLE
Reorganize Moderator Responsibility docs for Kickoff

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#63307]
## User Story
As a Governance team member, I want to be find the kickoff guidance I need when I need it so that I am able to complete the task at hand quickly and easily.

As a Governance team member, I want to be able to easily understand the kickoff task at hand, so that I'm not spending more time on the task than needed.

Assignee: @briandeconinck 
Peer Reviewer: @erinrwhite 

## Description
Governance team would like to improve the organization of the moderator responsibility docs, starting with Kickoff. The goal of this ticket is to group steps in the kickoff that require modifications to the same tools to avoid context switching (ie Slack, gh ticket), to reorder the steps so that they occur in a logical and meaningful order, and to name the steps so that it is easy to see what goal each step is trying to accomplish.

## Impacted Artifacts
[Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)

## Tasks

[Draft Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2762244097/63307+-+Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)

- [x] There are currently 9 steps in Kickoff. Identify if any steps can be merged due to tools/space where the work is completed (for example if step 11 and 12 both involve updating the gh ticket - obviously not real steps). If identified, merge the steps.
- [x] Review the merged steps and evaluate if the sequence of events can be reordered to be more meaningful. If so, reorder the steps.
- [x] Current steps 7, 8 and 9 have names so it is easy to see at a glance what the goal of each step is. Add names to each other step that is nameless. The name should be short and succinct, when possible.
- [x] Add table of contents to top of page (use Table of contents insert option - do not create manually)
- [x] Once complete, review full document for other areas where efficiency and/or clarity can be introduced. If areas of improvement are identified, list them below and make changes to the document. If no other opportunities for improvement are identified, insert N/A below:
   - Creating the milestone from the CC Request ticket, rather than going to the Milestones page.
   - Grouped edits to the CC Request ticket into two steps -- one for the product info/kickoff questions, one for adding touchpoints.
   - Added a collapsed section with an example of a correctly-formatted product info/kickoff questions section, because the step-by-step instructions don't really give you a sense of what this is supposed to look like.
   - Presenting adding touchpoints as a more straightforward "if X, then Y" construction, with the collapsed sections for code blocks moved to the relevant conditional.
   - Minor content rewrites for consistency/flow.
   - Added color-coded labels to each step indicating what resources are involved.
   - Added an info block at the end of each step to indicate whether it's safe to close the thing you were working on or if you'll still need it.
   - When creating the Kickoff Completed child ticket, moved the note about being in the right workspace up front to just be part of the instructions for that step.
   - Added a more explicit step to be in the right workspace when moving the CC Request ticket to the right pipeline.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have reorganized, merged steps and added clarity to the Collaboration Cycle Kickoff - Moderator Responsibilities guidance 

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Be sure to coordinate with assignee for ticket #64527 since both tickets include updates to Collaboration Cycle Kickoff - Moderator Responsibilities

**Comment by briandeconinck** [comment]
@erinrwhite [Draft kickoff moderator responsibility doc](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2762244097/63307+-+Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities) ready for review!

Please let me know if I missed something in the reorganized version, or if something I did doesn't make sense.

**Comment by erinrwhite** [comment]
@briandeconinck this looks so good! I left a few notes in Confluence - once those are addressed this is good to go. 👍🏻

**Comment by briandeconinck** [comment]
Changes are made and [Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities) is updated! Thank you @erinrwhite!
