### ISSUE TITLE
[Design] 10-10EZ - Screener page: Add read-only page

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#63306]
## Background
To address a major confusion pain-point, we have completed discovery (#61198) and development (#61746) to remove the post-screener pages from the EZ application. 
Now, we would like to add a read-only page after the screener page to display the data input (Name, DOB SSN [Last 4]).  This will allow unauthenticated Veteran applicants to feel confident in their data input and avoid them going all the way back to the screener page where they will have to re-enter their information again for another MPI validation.

This read-only page will be similar to the authenticated experience, screenshot below.

![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/b07f6c8e-3c92-470d-98a7-e27fad9d8f3b)

## Tasks
- [x] Add a new page to be displayed after the Screener (id-form) page, and before the Birth Place page
- [x] Ensure the display shows the name, DOB and a masked SSN with the last 4-digits displayed as readable numbers
- [x] Content review / update Sketch file if needed
- [x] Share with PM and FE

## Acceptance Criteria
- A new read-only page will be designed

**Comment by jessicastump** [comment]
Here is the [Sketch canvas page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/2A9307D5-72E2-4716-B706-9CC5D56B9E3C/canvas) with the updated id-form page with the middle name and suffix fields added as well as the additional read-only confirmation page. 
The intro sentence is new - thoughts on a quick content review needed? 
cc @davidakennedy

**Comment by hdjustice** [comment]
Yeah, I like what you have - simple and to the point. but let's have Content take a quick peek at it.

**Comment by davidakennedy** [comment]
Yeah, I like that direction as well. Content should look at it.

> This will help us fit the application to your specific needs. Please fill out the form below. Then we’ll take you to the VA health care application (10-10EZ).

"Fit" feels a bit off here to me. I wonder if "personalize" would be better?

**Comment by hdjustice** [comment]
"personalize" could be misleading, since if we don't find them in MPI and prompt to log in, there is no other personalization.

**Comment by jessicastump** [comment]
Agreed, that page/content is what is in production and reviewed (I assume by content at some point in time...). The new sentence added to the read only page is: 

> Please confirm your information before you continue.

**Comment by jessicastump** [comment]
Got the convo going for feedback - [DSVA slack message](https://dsva.slack.com/archives/C057JMPLD4J/p1691683723625689)

> We have a minor content review need that came up on the 10-10EZ this week.
> Bkgd: the flow today has this id screener page for unauthenticated visitors. This checks for their info in MPI and if found, presents an alert to sign in. If not, today they have to go through multiple pages seeing the info they just entered again for name, dob and ssn. We want to replace it with [this page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/2A9307D5-72E2-4716-B706-9CC5D56B9E3C/canvas) but want to check in on the content for the intro paragraph that is new.
> NEW PAGE, screener read only ([ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63306))
> Unauth personal info page
> Please confirm your information before you continue.
> Auth personal info page (already in production for reference)
> This is the personal information we have on file for you.
> I wanted to add this here and will be tag-teaming since I am out next week on vaca when we have the content sync, but please feel free to connect with any of the other designers next week or we can review here async too 

Once content review is complete, this can be closed if they don't have any changes.

**Comment by jessicastump** [comment]
Content has reviewed and provided feedback via comments in the [Sketch canvas here](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/2A9307D5-72E2-4716-B706-9CC5D56B9E3C/canvas). Desktop screens have been updated with content recommendations. (labeled with Draft)
Also added the production intro and auth personal info screens to this Sketch canvas to help illustrate the paths to help with final review (labeled with PROD)

**Comment by hdjustice** [comment]
These look great! Thank you!

**Comment by jessicastump** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaUVwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--49c65853fc66f78d9a9d6d95be3e237018a7cc85/PreCheck-Unathenticated-Mobile-%7Bid-form%7D-62534.jpg)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaUlwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--88219df5ffc17cd903e53672af43fbaabad4da04/PreCheckConfirm-Unathenticated-Mobile-%7Bpersonal-information%7D-62534.jpg)
