### ISSUE TITLE
[Research][Content] Adjust Content for Travel Claim Submission Text Message

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#63300]
## Description
Adjust text message response for a successfully submitted travel reimbursement claim to ensure Veterans know they have finished the process and don’t need to fill out the paper form

[Research Report](https://docs.google.com/presentation/d/1_eZDeffijiFNyAVQWCq59dcs3VoIqTdd/edit?usp=sharing&ouid=108264709911522151146&rtpof=true&sd=true)

## Tasks
- [x] Create the content 
- [x] Run content by Danielle
- [ ] Create ticket for VA Notify to update the existing text message content
- [ ] Update the artboards in Sketch

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 Quick question for you - this says to update the text message, but I'm wondering if the "We're processing your travel reimbursement claim" notification would be a better place to update the "you're done" content? Part of me says yes because the Veteran will see it before they see the text message, but then part of me says maybe not because there's a chance they still may have to fill out a form if their claim isn't successfully submitted. Before I start content for the text message, I wanted to get your thoughts - if we want to do both, I want to be sure we're using the same (or similar) language in both.

**Comment by kellysmith1008** [comment]
Starting to throw around some options to share with UX [in a google doc](https://docs.google.com/document/d/1VYeHaK_0fE_bJwQj8M7DgqubTfwHxe0Stg8wkMR3Mhc/edit?usp=sharing) and will continue iterating

**Comment by kellysmith1008** [comment]
Mocked up some additional/updated text messages as a result of the feedback from UX sync and shared with the team. Will leave the voting (option 1-4) open to the UX team through tomorrow, then will decide and finish out this ticket accordingly

**Comment by ytsaoca** [comment]
Wireframe for review: https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/8A901B82-B5FF-4879-8BEA-6DBAEB2B91C6/canvas

'cc @kellysmith1008 @benbrasso-agile6

**Comment by cgednalske** [comment]
I'm very sorry to butt into this, but I'm wondering if we considered having "at this time" after No action needed? Or are we sure they won't need to do anything else at any point? Just thinking of when Kelly had mentioned that earlier, but please ignore me if this is already resolved because it very well might be 🙂

**Comment by kellysmith1008** [comment]
@cgednalske I agree it would be helpful to have "at this time" on there, but unfortunately that doesn't fit within the 160 character limit, so we had to remove it. But I agree it would have been nice :)

**Comment by benbrasso-agile6** [comment]
Mmm hmmm mmm hmmmm. LGTM. I say we're ready to give to Melanie on VA Notify. I don't know if she needs a full ticket for this or not. 

@loripusey @kellysmith1008 everyone good if we move forward?

**Comment by loripusey** [comment]
Yes let's move forward

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 you want this next step, or I can help. Just lemme know.

**Comment by cgednalske** [comment]
@kellysmith1008 ahhh gotcha 👍 I figured you'd already considered that, but I couldn't help my curiosity! Thanks for the info 🙏

**Comment by loripusey** [comment]
@kellysmith1008 I don't know if there is a formal ticket or not, might take a little research.

**Comment by benbrasso-agile6** [comment]
Ask Melanie Jones in Va-notify-public if she prefers a ticket or not for this small edit

**Comment by kellysmith1008** [comment]
Thank you! Just sent her a message in the va notify public channel. Again, sorry for the delay

**Comment by benbrasso-agile6** [comment]
Nice. Hopefully small enough she doesn’t want a ticket. But their intake ticket I believe is pinned to their slack channel.

**Comment by benbrasso-agile6** [comment]
Do we need a prod review on this? Actually, a prod review would be a staging review, so long you have ur phone number set up for that other VistA Do we need to do another one? @loripusey @kellysmith1008

**Comment by benbrasso-agile6** [comment]
Think my vote is "no" and to close this

**Comment by kellysmith1008** [comment]
I think we can close it
