### ISSUE TITLE
[SW] Testing - Automated testing with axe by Deque

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#63302]
## Issue Description
Prepare for accessibility staging review time! 
[Documentation source](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review#Prepareforanaccessibilitystagingreview-AutomatedtestingwithaxebyDequeaxe)

Complete testing and note any issues to be addressed prior to staging review.
---
## Tasks
- [x] Complete testing as detailed in documentation
- [ ] Write up any issues in this ticket that need addressing
- [ ] Categorize any issues that need to be completed prior to staging review

## Acceptance Criteria
- [x] Testing completed 
- [ ] Any issues discovered are documented
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Went through entire form with different SW flows as well as full FSR path and found no axe issues using the Deque tool! Here are a few screens

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/20892803/6865e366-95f5-48aa-a39b-6fa3c64ebaaf)
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/20892803/a4e879e2-3328-4fae-97c5-4444aa8a616a)
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/20892803/901fd2a3-1d3a-486c-90d1-5be4d8d04584)
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/20892803/44409a12-999a-45f9-a910-d8a7e49d60c8)
