### ISSUE TITLE
[Rated Disabilities to Lighthouse] Implement FE changes

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#63310]
## Background
We need to implement the frontend changes associated with using the new LH rated disabilities controller

## Context
* We make 2 separate API calls to EVSS to get all of the data we need to display in the application currently. LH only requires 1 API call to retrieve all of the data
* EVSS endpoints:
  * /v0/disability_compensation_form/rated_disabilities
  * /v0/disability_compensation_form/rating_info
* Lighthouse endpoints:
  * /v0/rated_disabilities

## Tasks
- [x] Configure application to halt rendering until the feature toggles have been loaded
- [ ] Update FE code to use the feature toggle for determining which controller to call (EVSS vs LH)
- [ ] Modify components to work with new attributes returned by LH controller

## Acceptance Criteria
- [ ] Rated disabilities application uses feature toggle to determine whether to call EVSS or Lighthouse for rated disabilities
- [ ] Rated disabilities application is compatible with the new rated disabilities controllers response

**Comment by jerekshoe** [comment]
**Update (12/5):** Still working on writing tests currently. Lighthouse updated their API yesterday though and I am not able to get data back for any of the staging users that were working last week though, so that will slow things down a bit

**Comment by HeatherWidmont** [comment]
Jerek still working on the multiple PRs, should be merged in a couple days

**Comment by SilkeDannVA** [comment]
Jerek getting this ready for pr
