### ISSUE TITLE
[FE] 10-10EZ - Screener page: Add read-only page

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#63312]
## Background
To address a major confusion pain-point, we have completed discovery (#61198) and development (#61746) to remove the post-screener pages from the EZ application. 
With the design completed (#63306), we would like to add a read-only page after the screener page to the EZ form that will display the data input (Name, DOB SSN [Last 4]).  This will allow unauthenticated Veteran applicants to feel confident in their data input and avoid them going all the way back to the screener page where they will have to re-enter their information again for another MPI validation.

- Design link goes here

## Tasks
- [ ] Create a new page to be displayed after the Screener (id-form) page, and before the Birth Place page
     - Design ticket #63306
     - Can the URL still be something like `Profile`? `Personal-Information` is already a URL for this on the Auth side, and I use it for Apps Started counts
- [ ] Ensure the display shows the name, DOB and a masked SSN with the last 4-digits displayed as readable numbers
- [ ] Share with PM for validation

## Acceptance Criteria
- A new read-only page will be designed

**Comment by jessicastump** [comment]
Content has reviewed and recommendations are updated in the [Sketch canvas here](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/2A9307D5-72E2-4716-B706-9CC5D56B9E3C/canvas). 
Design ticket (https://github.com/department-of-veterans-affairs/va.gov-team/issues/63306)

**Comment by longmd** [comment]
@hdjustice , this is ready for review & sign-off. Here are the screenshots with authenticated & guest:

![Screenshot 2023-08-28 at 11 34 21 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/9162b875-6287-4fba-b074-f4ef4c09853e)

![Screenshot 2023-08-28 at 11 35 08 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/baed7295-f995-4884-96bd-c743c1ba72c7)

**Comment by hdjustice** [comment]
This looks great!  Thanks Matt!
I have also tested with various changes and back/forth movements through the application. This page is functioning as expected.
