### ISSUE TITLE
[Rated Disabilities to Lighthouse] Set up mock data

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#63311]
## Background
We need to record some mock data to be used with rated disabilities. This will make local development easier and allow us to mimic common scenarios that we need to be able to test

## Scenarios that should be covered
* [ ] Veteran with service-connected rated disabilities ONLY
* [ ] Veteran with non-service-connected rated disabilities ONLY
* [ ] Veteran with both active service-connected and active non-service-connected rated disabilities ONLY
* [ ] Veteran with service-connected and inactive rated-disabilities ONLY
* [ ] Veterans with both service-connected and non-service-connected disabilities + inactive ratings

## Tasks
- [x] Update betamocks config in `vets-api` to include a mapping between the rated_disabilities endpoint the mocks folder in `vets-api-mockdata`
- [x] Create a new folder in `vets-api-mockdata` for the mocks to be placed in
- [ ] Create new mocks and record them to vets-api-mockdata

## Acceptance Criteria
- [ ] Basic scenarios are covered by mock data
