### ISSUE TITLE
[FE] Update Logic to Prevent User from Seeing Travel Questions

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#63315]
## Background
BTSSS is adjusting their API to receive the appointment time, with that they will now allow the submission of 1 claim per Facility per day for the Veterans appointments. For this first pass, we are going to remove the logic we implemented to present the Veteran from seeing the Travel questions if they have more than 1 appointment in a day.

## Tasks
- NOTE: wrap this in the feature flag
- [ ] [FE] **Update Logic to Prevent User from Seeing Travel Questions only if they have already submitted a claim for that same day and facility**
- [ ] [FE] **Send the appointment time to the BE**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
