### ISSUE TITLE
[BE] Send Appointment Time to BTSSS API

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#63318]
## Background
BTSSS is adjusting their API to receive the appointment time, with that they will now allow the submission of 1 claim per Facility per day for the Veterans appointments. For this first pass, we are going to remove the logic we implemented to present the Veteran from seeing the Travel questions if they have more than 1 appointment in a day.

## Tasks
- [ ] [BE] **Send Appointment Time to BTSSS API**
    - NOTE: wrap this in the feature flag

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
