### ISSUE TITLE
EMIS: Code Deletion

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#63326]
### PROBLEM STATEMENT
After we have migrated from eMIS to VA Profile, eMIS code can be deleted in various repos that the Platform manages. 

## OCTO Objectives:
**Objective:**
This aligns with O1: Our platforms are the best way to deliver products at VA
**OKR**
This aligns with OKR1: Our platforms hit the "elite" level (as defined by DORA) on Deployment Frequency, Lead Time for Changes, Change Failure Rate, and Time to Restore Service.

### ACTION ITEMS
- [x] Rebecca will order the code deletion tickets nested in this epic
- [x] Complete all tickets in this epic

### DEFINITION OF DONE
- [x] All tickets in this epic are complete

**Comment by laineymajor** [comment]
This has been moved to the next sprint as there are still emis bugs to resolve...

**Comment by laineymajor** [comment]
Work will continue on this during our part 2 of the double sprint.

**Comment by rmtolmach** [comment]
This epic is complete ✅ 

There is still work to be done for vets-website and that is tracked in the epic: https://github.com/department-of-veterans-affairs/va.gov-team/issues/75212
