### ISSUE TITLE
NOD | Evaluate & fix save-in-progress renamed value

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#63322]
## Value Statement
**_As a_** developer
**_I want to_** determine why a saved form data variable is being renamed
**_So that_** it can be fixed

## Background Context

In our Notice of Disagreement form, we have a form data variable named `appealingVhaDenial`. The state is saved via the save-in-progress endpoint, but when the save-in-progress is retrieved the data that is loaded has a variable named `appealingVHADenial` with the `VHA` in all caps. It appears that the save-in-progress may be causing this change, but it needs to be investigated. The backend uses "olive branch" to convert the camel-case to snake-case, so this may be part of the issue.

If the backend can't be changed, or isn't the cause of this issue, then we may need to rename the variable on the frontend.

Test as follows:
- Start a new form
- Select either radio choice on the appealing VHA denial page
- Use the "finish this application later" link
- Reload the app
- Return to the appealing VHA denial page
- If the same radio value remains selected, then this fix is confirmed

## Tasks
- [ ] investigate cause of variable renaming
- [ ] Fix variable on BE or FE
- [ ] Add tests

## Acceptance Criteria
- [ ] All tasks complete
- [ ] All tests passing
- [ ] Manually validate renamed option is working by following the "Test as follows" directions

**Comment by saderagsdale** [comment]
@Mottie can you add AC to this?

**Comment by Mottie** [comment]
Added step-by-step instructions on how to validate this in the description

**Comment by data-doge** [comment]
Note from bug triage: Front end fix done, but need to investigate why all caps happens on backend

**Comment by data-doge** [comment]
We know that `VHA` is included in our Rails app's inflections file. Kyle wants to spend some time, to figure out whether we're experiencing any VHA inflection-related issues elsewhere in our portfolio.

**Comment by Mottie** [comment]
[Reported this issue to platform](https://dsva.slack.com/archives/CBU0KDSB1/p1695653828797529). While this may be working as intended, it isn't documented. Also with some additional testing, it appears the 2-letter acronyms, like `VA` do not get "corrected", e.g. `hasVaAppeal` does not get converted to `hasVAAppeal`. I'm going to close this because platform now has ticket #66224 to work from.
