### ISSUE TITLE
Implement Adjustments for DOMO Access 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#63332]
## Issue Description
_Need to fix issues in DOMO to determine why the data is not updating on the dashboard. 

---
## Tasks
- [x ] @aubreyarcangel to work with Ian McCullough to discuss bug - Salesforce data arrives but does not populate the dashboard in DOMO
- [X] Anita will reach out to Ian to coordinate meeting
- [X] Kimberley will request access for Sarifa and Kimberely 

## Acceptance Criteria
- [x] _When data is available and visible in DOMO
- [x] Access is granted to Sarifa and Kimberely
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
@aubreyarcangel met with Ian and identified the issue.  @newworld2616 will continue research and conclude. Tests have been completed.  Currently successful...  @newworld2616 will confirm and close.

**Comment by ATMiddleton** [comment]
@Kimberley2023-CSM will submit request for Sarifa to gain access.

**Comment by Kimberley2023-CSM** [comment]
@Kimberley2023-CSM has created the [ticket](https://dsva.slack.com/archives/CBU0KDSB1/p1692909084996489) in Platform support.

**Comment by ATMiddleton** [comment]
Still data discrepancies... Will create another ticket to address.
