### ISSUE TITLE
Discovery: Adding annotations to Pull Requests containing files associated with merge-block warnings

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#63338]
## Issue Description
Currently, our warnings are displayed as a check in the CI process. While this will place a visible red X in the list of checks, there are many checks and the merge block one is not a requirement yet, therefore may be ignored. Research into annotations for pull requests to see if we can surface some messaging on PRs that are opened that contain changes to files associated with test specs under warning.

---
## Tasks
- [ ] Research annotation feature for Pull Requests
- [ ] Determine if this is able to be customized to fit our purpose
- [ ] Document a planned approach on this ticket.

## Acceptance Criteria
- [ ] We've made a decision to move forward/not move forward with annotations.
- [ ] if we're moving forward, a plan of implementation for annotations is documented here.
---
