### ISSUE TITLE
Event tracker for the Descriptive Back link for Appointment Details and Confirmation Details

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#63331]
## Description
We implemented the descriptive back link initiative on August 2, 2023 and would like to track the number of clicks on the descriptive back link in Universal Analytics (UA) tool. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_descriptive_back_link` toggle is on

- [ ] Given when the user is authenticated to the Appointments application and clicks on `Details` for their upcoming VA appointment 
       When the user clicks on the descriptive back link
       Then it will trigger an event `vaos-upcoming-appointment-details-descriptive-back-link` in UA

- [ ] Given when the user is authenticated to the Appointments application and clicks on `Details` for their pending VA appointment or pending Community Care appointment 
       When the user clicks on the descriptive back link
       Then it will trigger an event `vaos-pending-appointment-details-descriptive-back-link` in UA 

- [ ] Given when the user is authenticated to the Appointments application
       When the user completes a direct scheduling workflow for a VA booked appointment and clicks on the descriptive back link on the confirmation details page 
       Then it will trigger an event `vaos-direct-confirmation-details-descriptive-back-link` in UA

- [ ] Given when the user is authenticated to the Appointments application
       When the user submits a pending VA appointment or a pending Community Care appointment and clicks on the descriptive back link on the confirmation details page 
       Then it will trigger an event `vaos-pending-confirmation-details-descriptive-back-link` in UA 

### Design Assets
Not applicable 

### Out of scope 
Adding the tracking event to GA4. We will migrate the UA events to GA4 in FE ticket #63341 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
As discussed on 08/08/23, we will see if we can eliminate the (*Required) text from the page description and marking some fields as option (see latest [thread](https://adhoc.slack.com/archives/C02UW5AHHEJ/p1691522974960579?thread_ts=1691519773.447029&cid=C02UW5AHHEJ)). Will put this ticket in the `product-pm` backlog. cc: @JRRoof

**Comment by ldelacosta** [comment]
Event tracker has been added into production. No issues to report. Closing out the ticket. cc: @JRRoof [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaUFiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c3403e1cbfd71c9c92ce00bf826c1ffe8bbe0d6d/image%20%286%29.png)
