### ISSUE TITLE
Design | Burial Form 530 Future Flow Mapping

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#63352]
## Issue Description
Map the future form flow for the online burial form 530 and incorporate changes made to the paper form.

---
## Tasks
- [ ] Screenshot page by page of site and form flows 
- [ ] Add callouts and start identifying user flows
- [ ] Align the format/legend with the [[526 Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686768383603/3f4415dd2ddb71bbd104ebefd92a2c7b553ad792?sender=udbd39c1bbebb4ec4d7d08829)]

## Acceptance Criteria
  - [ ] All paper form changes are incorporated into the form flow
  - [ ] Error states captured if able to validate
  - [ ] Known pain points remediated
  - [ ] a11y issues flagged

**Comment by sortizsh** [comment]
@fiorella-io  can you add the actual discovery files to this ticket? TY

**Comment by fiorella-io** [comment]
### Updates:
- Compared the paper form and digital form
- Identified missing fields and descriptions in the digital form
- Created a simplified future state flow linked in this ticket
