### ISSUE TITLE
Configure api_provider_factory and service providers for DataDog

### ISSUE THREAD

**Issue by mchae-nava** [department-of-veterans-affairs/va.gov-team#63354]
## Issue Description
We would like another level of logging within our provider and factory layers.
Our modules need a line added so that they are traceable in DataDog. Additionally, consider what logs we would like to add.

This is for the ITF release, but could also easily include `rated_disability`

---
## Tasks
- [ ] Add configuration to ApiProviderFactory and Services
- [ ] Add desired logging to ApiProviderFactory and Services

## Acceptance Criteria
- [ ] Traffic through ApiProviderFactory and Services are tracked in DataDog
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
Work was bundled in the rateddisabilities prelaunch ticket
