### ISSUE TITLE
Remove education questions on COVID FAQs page

### ISSUE THREAD

**Issue by megzehn** [department-of-veterans-affairs/va.gov-team#63365]
## Issue Description

We need to remove both of the education questions under the "Benefit payments...." heading of the COVID FAQ page (and the Spanish and Tagalog versions). 

- What happens to my GI Bill benefits if my school changes to online classes or temporarily closes?
- What about on-the-job training, apprenticeships, and work study?

Then send an email to Tammy et al just to let them know that we removed the questions since there were 404s on these links: 

- Learn more about how COVID-19 may affect your education benefits
- Learn more about electronic communication for the GI Bill program

---
## Tasks
- [x] Remove the 2 questions on the English page (MZ)
- [x] Remove the 2 questions on the Spanish page (MZ)
- [x] Remove the 2 questions on the Tagalog page (MZ)
- [x] Publish all 3 pages (MZ)
- [x] Alert Tammy and education crew that we took them down due to the broken links (Randi)
 
## Acceptance Criteria
- [x] Education Qs are removed on the live pages

---

**Comment by megzehn** [comment]
Hi @RLHecht, the education questions are removed from all the FAQ pages. Once you alert Tami we can close this. Thank you so much!

**Comment by RLHecht** [comment]
Thanks, @megzehn I sent Tammy an email letting her know so I say we can close this once we validate on prod. Thank you!

**Comment by megzehn** [comment]
Confirming that the changes are live on all the pages. Closing this.
