### ISSUE TITLE
[FE] My VA BAD section: Hide "what benefits does VA offer?" menu and contents

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#63379]
## Background
After reviewing GA data we've decided to remove the submenu "what benefits does VA offer" within the Benefit Application Drafts ("BAD") section on My VA. Before we make this change permanent, we want to temporarily hide this section using a feature flag so we can monitor the impact and then make a more permanent change to remove it all together once we have validation. 

![Screenshot 2023-08-09 at 10 45 43 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/cded22d8-538d-4a07-8489-80387b589777)

## Tasks
- [x] Create a feature flag
- [x]  Hide "what benefits does VA offer?" and contents within it for all users (LOA1 and LOA3)
- [x] Update tests
- [x] Move to validate and tag PM for review
- [ ] Once validated and in production, turn the flag on for all users in production

## Acceptance Criteria
- [ ] The "what benefits does VA offer?" menu no longer appears on My VA for all users (LOA1 and LOA3)

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_
1. Log into staging with any LOA3 user
2. Scroll to the Benefit Application Drafts section on My VA
3. See that the "what benefits does VA offer?" menu is no longer visible
4. Log out
5. Log into staging with any LOA1 user
6. Scroll to the "Apply for VA Benefits" menu
7. See that the "what benefits does VA offer?" menu is no longer visible

**Comment by ajakabcin** [comment]
Looks great @dellerbie! I'm not seeing the menu for LOA3 or LOA1 users on staging

LOA3
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbnBGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b3576b4a5186bf9172fffab1e15af9c912d6b18d/Screenshot%202023-08-28%20at%204.11.21%20PM.png)

LOA1
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbnRGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7329586de663ca107be73028ef399b6e6a118610/Screenshot%202023-08-28%20at%204.10.33%20PM.png)
