### ISSUE TITLE
Making Changes to Content Build for Preview Environments

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#63387]
# Description
Mature documentation and determine options for preview / review environments which mirror prod

# Tasks
- [ ] Document manual build process
- [ ] Document manual test process
- [ ] Define local run pattern
- [ ] Define options for Preview Environments in AWS

# Acceptance Criteria
- [ ] [Describe tasks here]

**Comment by JoeTice** [comment]
Sprint 33 Update: Paused - This task may not be needed based on new information discovered this sprint regarding another team who is looking into improving content-build. Hope to have a definitive answer on this task during this sprint.

**Comment by JoeTice** [comment]
This is a duplicate of other tickets related to content-build for Preview Environments
