### ISSUE TITLE
Design | Draft Verification Emails

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#63389]
## Problem
Individuals are not verifying the dependent information often enough, which leads to an overpayment or underpayment of benefits.

## Tasks
- [x] Draft copy for emails that will be sent to Veterans asking them to verify their dependent information
- [x] Get feedback from appropriate stakeholder(s)
- [x] Submit to CAIA for review

## Acceptance Criteria
- [x] Email copy has been drafted
- [x] CAIA ticket submitted
- [ ] Follow-up tickets have been created

**Comment by djones2113** [comment]
Sharing as an FYI: Here is a Sketch file that @juliepedtke started where we've started drafting copy for the verification emails. The two options are very much still in draft mode but what we have right now represents the two potential directions we've discussed for the email notification:
1. Closely following the existing email notification templates that we've seen and provide recommendations for action in bullet point form
2. Brainstorm what an interactive notification could look like by providing options in the form of buttons

**Comment by djones2113** [comment]
FYI we are working in this [Google doc](https://docs.google.com/document/d/1iSO7jTqeA2wM-7S2sYqjt6sFoJp7h_AtEIaSz_dqTYQ/edit#heading=h.zptou6y925s) as we continue to make edits to the email notification given that the edits are mostly content focused.

**Comment by djones2113** [comment]
@jstrothman before we bring this to CAIA office hours we would love to get your feedback on the [latest version](https://sketch.com/s/149b2ccf-af21-4c71-9ca8-2ef2ae8af9fc) of the dependent verification email notification.

We have a few comments (mainly suggesting alternative language) directly in the file, but attached below is a screenshot of the notification for ease of review here: <img width="395" alt="Screenshot 2023-09-05 at 8 56 01 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/114195359/f2ec8f73-bebc-4793-b677-1b528a2d2850">.

Let me know if you have any questions or comments! cc @steele-lm @juliepedtke

**Comment by jstrothman** [comment]
@djones2113 I added comments in Sketch. Thank you for the opportunity

**Comment by juliepedtke** [comment]
Feedback from CAIA office hours:

- We should submit a CAIA ticket with a general summary
- VA tries not to use sighted language, so "find out" or "learn more about" in place of "view"
- General style to not embed a link within a sentence, but instead on their own line alone so they stand out when scanning. And no period at the end of links.
- Beth will check about if we should capitalize "VA" within a link, eg "VA.gov" or leave it lowercase, but no change needed on this yet

**Comment by sortizsh** [comment]
Submitted official CAIA ticket on 9/8

**Comment by juliepedtke** [comment]
CAIA ticket for reference: https://github.com/department-of-veterans-affairs/va.gov-team/issues/65222

**Comment by juliepedtke** [comment]
Received CAIA feedback, will hold off on implementing until after research so that we can incorporate new findings.
