### ISSUE TITLE
[Design] My VA Healthcare: Documentation updates for phase 1b of MHV migration

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#63399]
## Background
In support of the MHV migration we are making several updates to the Healthcare section on My VA:

1. Updating all instances of the "schedule and manage your appointments" link to connect users to https://va.gov/my-health/appointments when it appears in the appointments card, as a secondary link, and when the appointments API fails in the error message
2. Updating the Cerner alert with a [new design](https://www.figma.com/file/iqjkZx2EbrZu6leL6YfN45/Cerner-Handoff?type=design&node-id=1631-22727&mode=design) created by the appointments team

## Tasks
- [x] Update sketch files
- [x] FE documentation
- [x] Use case documentation

## Acceptance Criteria
- [x] designs and documentation are updated

**Comment by aagosto90** [comment]
[FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/health-care-FE-documentation.md#if-a-user-receives-va-health-care-at-a-cerner-facility)

[Use case documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/use-cases/health-care-use-cases/cerner-user.md)

**Comment by laurwill** [comment]
Hi @aagosto90 , thanks for bringing this to office hours — I just left comments on the Sketch file confirming the content guidance for the Cerner alert. Let me know if you have any questions!
