### ISSUE TITLE
[FE] My VA Healthcare: Update "schedule and manage your appointments" link

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#63401]
## Background
In support of the MHV migration, we need to make updates to three links on My VA in the Healthcare section:

1. the "Schedule and manage your appointments" link within the appointments card:
![Screenshot 2023-08-08 at 3 27 50 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/84f557da-9bd2-41f0-bf1f-4a9a13e6f0f1)

2. the "Schedule and manage your appointments" link when it appears as a secondary link:
![image (9)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/0c6650bc-1b4a-47ff-9840-333c8e8aa21d)

3. the "Schedule and manage your appointments" link in the warning alert:
![Screenshot 2023-08-17 at 4 08 35 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8542413/60f27589-459b-4c93-913b-4d86faf1ebae)

**We'll be placing this work behind the same feature flag that the Appointments team is using for similar updates so that they can all be released together. The feature flag to use is: `va_online_scheduling_breadcrumb_url_update`**

## Tasks
- [ ] Update link in the appointments card to `https://va.gov/my-health/appointments`in vets-website
- [ ] Update secondary link to `https://va.gov/my-health/appointments` in vets-website
- [ ] Update link in warning alert to `https://va.gov/my-health/appointments` in vets-website
- [ ] Place behind same feature flag Appointments team is using:`va_online_scheduling_breadcrumb_url_update`(_reach out to Simi Adebowale in #appointments-team slack with any questions_)
- [ ] Update tests
- [ ] Move to validate and tag PM for review

## Acceptance Criteria
- [ ] The "schedule and manage your appointments" link is updated in the appointments card, when it appears as a secondary link, and in warning alert

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_
1. Log into staging with Cecil Morgan
2. Scroll to the Healthcare section
3. See the appointments card
5. Confirm the "schedule and manage your appointments" link is updated to this url: https://va.gov/my-health/appointments
6. To trigger an API error, enable network request blocking in browser dev tools, and block `staging-api.va.gov/vaos/v2/appointments/*`
7. Confirm the "schedule and manage your appointments" link is updated to this url: https://va.gov/my-health/appointments
8. Log out
9. Log into staging with user 226
10. Scroll to the Healthcare section
11. See the secondary link for "schedule and manage your appointments"
12. Confirm the link is updated to this url: https://va.gov/my-health/appointments

## Resources
- The appointments team can be reached in DSVA slack at `#appointments-team` and @simiadebowale is the lead dev

**Comment by allisonlu** [comment]
I wanted to point out there's one more instance of the "Schedule and manage appointments" link in the error message when the API fails. It's currently linking to `/health-care/schedule-view-va-appointments/appointments`. 

![Screenshot 2023-08-17 at 4 08 35 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8542413/29a6af25-8843-4f49-a2db-c67d74f4509b)

**Comment by ajakabcin** [comment]
Great catch @allisonlu !

**Comment by allisonlu** [comment]
@ajakabcin 

ready for validation! I checked Cecil Morgan and user 226, and can confirm that I see the updated link
