### ISSUE TITLE
[FE] My VA Healthcare: Update Cerner alert

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#63400]
## Background
The appointments team in partnership with the MHV migration team(s) has designed a new Cerner alert. We need to implement this on My VA to display for Cerner users. We'll be placing this work behind the same feature flag that the Appointments team is using for similar updates so that they can all be released together. This assumes it's just a design change, no change in logic to how and when we show the Cerner alert to users.

[FE documentation for Cerner alert](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/my-va-small-initiatives/my-va-support-of-MHV-on-va.gov-migration/FE-documentation/my-va-phase-1b-FE-documentation.md#if-a-user-receives-va-health-care-at-a-cerner-facility)
[Use case documentation for Cerner alert](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/use-cases/health-care-use-cases/cerner-user.md)

## Tasks
- [x] Update with new alert (consult with @aagosto90 for questions)
- [x] Place behind same feature flag Appointments team is using: `va_online_scheduling_static_landing_page` (_reach out to Simi Adebowale in `#appointments-team` slack with any questions_)
- [x] Update tests
- [x] Move to validate and tag PM for review

## Acceptance Criteria
- [x] The cerner alert is updated and specs match provided design

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_
1. Log into staging with any Cerner user
2. Confirm new alert displays

**Comment by ajakabcin** [comment]
hey @dellerbie I believe there's a minor bug that Adam found when validating #62899 - see his [comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62899#issuecomment-1708881337):
