### ISSUE TITLE
Migrate eVSS Calls to Lighthouse for Document Service

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#63417]
## Issue Description
The eVSS is being deprecated and the vets-api utilizes these services to retrieve and post data.
One of these services is the Document service that uploads files via 526 form. 

Check with Andrew Herzberg [#57231](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/57231)
 - If the existing service is the same usecase as ours 
 - When is it going to production
 - channel #va-mobile

---
## Tasks
**Assuming the service exists**:
- [ ] Assess the extant document service
- [ ] Identify Lighthouse migration endpoint - what is the endpoint in existence in LH that replaces this service?
- [ ] Audit all calls to eVSS services within the functionality
- [ ] Call the implemented service
- [ ] Authentication - if another team has used their credentials, then this does not need to be done

## Acceptance Criteria
- [ ] Form 526: no changes to the upload feature on the frontend 
- [ ] Maintain test coverage
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by SamStuckey** [comment]
@RakshindaAslam you mentioned in retro that a large chunk of the actual implementation of this work is done, right?  Do you mean the work done in [this ticket](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/57231)? Or elsewhere?

**Comment by RakshindaAslam** [comment]
@SamStuckey - The endpoint migration typically has work that falls in these categories. For document service endpoint,
1. Abstraction - Completed by DBEX team 1 in #57231
2. Implement the new service provider - competed by another team - POC Andrew Herzberg for more details
3. Call the implemented provider - remaining work for DBEX
4. Release - remaining work for DBEX

We think implementation is completed by another team but not yet live in production. If it's found that the implemented service does not give us the functionality we need, we may need to implement it ourselves.

**Comment by SamStuckey** [comment]
Thanks @RakshindaAslam  : ). to follow up for posterity, the work completed by the other team (as you said) [was submitted in this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/13090)

**Comment by SamStuckey** [comment]
[This document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/document_service_migration_from_evss_to_lh.md) is where collating observations, context, and anything useful related to the impending handoff of this work cc @NB28VT

**Comment by SamStuckey** [comment]
This work is temporarily blocked by ongoing work on the Lighthouse document service objects in vets-api. [For context see this slack thread](https://dsva.slack.com/archives/C04KHCT3ZMY/p1692294169089089).

Action item here is for us to follow up.  Jason is OOO at the moment

**Comment by SamStuckey** [comment]
@austinjprice what should we do with this ticket?

**Comment by austinjprice** [comment]
added to EVSS to LH Document Service Migration for reference. Can keep open until Epic is closed.
