### ISSUE TITLE
[PM] My VA LOA1 updates: Prep for QA

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#63428]
## Background
We need to prep for a very light QA of the LOA1 updates

## Tasks
- [x] Write test cases
- [ ] ~Create spreadsheet~
- [ ] ~Create QA artifacts doc~

## Acceptance Criteria
- [x] Prep for QA is complete
