### ISSUE TITLE
[Design] My VA LOA1 updates: Create design and documentation for updated LOA1 experience

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#63420]
## Background
Now that the streamlined UX experience has been released to users for some time we want to make some updates to the LOA1 experience to be more consistent with LOA3.

We will be updating the LOA1 state to have 5 sections:
1. Verify your identity  - no change
2. Claims and appeals - show the "Learn how to file a claim" link
3. Health care - show the "Apply for VA health care" link
4. Education - show the "learn about applying for education benefits" link
5. Benefit application drafts - match LOA3 behavior: change the title from Apply for VA benefits to "Benefit application drafts" and when no draft applications to show, display "You have no benefit application drafts to show."

## Tasks
- [x] Create new sketch files for desktop and mobile
- [x] Create FE documentation (docs can live under [this](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/my-va-small-initiatives/LOA1-experience-updates) folder)
- [x] Review with team

## Acceptance Criteria
- [x] New documentation and designs exists

**Comment by aagosto90** [comment]
@Samara-Strauss Updated LOA1 designs for your review:

- [Desktop without any apps in progress](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/v/ljq4pO/a/elpRgmq)
- [Desktop with an app in progress](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/Go9PJ1b)
- [Mobile without any apps in progress](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/0AveGPj)
- [Mobile with an app in progress](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/lRzqAmv)

I like this! It looks very clean and I actually think it does a better job of highlighting VA benefits than the current LOA1 experience - plus it'll be much more familiar and less jarring if a Veteran verifies their identity and then sees the LOA3 experience.

**Comment by aagosto90** [comment]
[FE documentation created here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/my-va-small-initiatives/LOA1-experience-updates/LOA1-FE-documentation.md)
Use case documentation will be updated in a subsequent ticket.
