### ISSUE TITLE
[FE] My VA LOA1 updates: Implement changes for updated LOA1 experience

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#63422]
## Background
Now that the streamlined UX experience has been released to users for some time we want to make some updates to the LOA1 experience to be more consistent with LOA3.

We will be updating the LOA1 state to have 5 sections:
1. Verify your identity  - no change
2. Claims and appeals - show the "Learn how to file a claim" link
3. Health care - show the "Apply for VA health care" link
4. Education - show the "learn about applying for education benefits" link
5. Benefit application drafts - match LOA3 behavior: change the title from Apply for VA benefits to "Benefit application drafts" and when no draft applications to show, display "You have no benefit application drafts to show."

## Tasks
- [x] Create a feature flag (i will be utilizing the `my_va_experimental_frontend` toggle)
- [ ] Implement changes to LOA1 state per designs/specs in #63420 
- [ ] Update tests
- [ ] Move to validate and tag PM

## Acceptance Criteria
- [ ] Updated LOA1 experience is available on staging per specs outline above

**Comment by allisonlu** [comment]
@ajakabcin This is ready for validation! I turned on the `my_va_experimental_frontend` feature flag and LOA1 updates are live on staging

**Comment by ajakabcin** [comment]
One minor copy issue found otherwise great - closing!
