### ISSUE TITLE
[bug] 526 | Update ITF alert content

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#63451]
## Value Statement
**_As a_**  Veteran
**_I want to_** be assured that a failed Intent-to-File will still record my date of submission
**_So that_** I know that the ITF date is saved even though I can't start the form 

---
## Acceptance Criteria
- [x] Design of update is available
- [x] Changes are made to 526

## Tasks
- [x] Update ITF error alert content - title & content
- [x] Change ITF alert type to information alert
- [ ] Update tests

## Designs and Build Notes
<details><summary>Design</summary>

![ITF Informational@1x](https://github.com/department-of-veterans-affairs/va.gov-team/assets/111457818/18201c65-edd1-45c6-aba4-9eb9d46a8507)

</details>

## Definition of Ready 
- [x] Clear value description
- [x] Reviewable acceptance criteria

## Definition of Done
- [ ] AC are met

**Comment by saderagsdale** [comment]
@Mottie Let's estimate this.

**Comment by Mottie** [comment]
Done. ZenHub was being finicky.

**Comment by Mottie** [comment]
Changes merged in & available for testing in staging

**Comment by saderagsdale** [comment]
@Mottie is this done? Does it need a look from Emily?

**Comment by Mottie** [comment]
It sounded like [she wanted to verify it](https://dsva.slack.com/archives/CBU0KDSB1/p1691686961893279?thread_ts=1691591736.796649&cid=CBU0KDSB1), and I provided instructions, but she didn't affirm that it was checked.

**Comment by Mottie** [comment]
[Emily replied that we're good to close this ticket](https://dsva.slack.com/archives/C04KW0B46N5/p1691771343498499?thread_ts=1691678510.248049&cid=C04KW0B46N5)
