### ISSUE TITLE
Content edits for #60936

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#63488]
## Issue Description
Content edits based on [support ticket #60936](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60936)

---
## Tasks
On the [Central Mail API](https://depo-platform-documentation.scrollhelp.site/developer-docs/central-mail-api) page: 

- [x] Add to the page title: (Deprecated) 
- [x] Delete existing content
- [x] Add red warning box with the following content:

This API has been deprecated. Please use the Benefits Intake API. (link "Benefits Intake API" to this URL: https://developer.va.gov/explore/api/benefits-intake/docs?version=current)

## Acceptance Criteria
- [x] The Central mail API page will be updated with new API information
