### ISSUE TITLE
Update 'BQ- Governance Github tickets' data set in Domo

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#63501]
## User Story
As a Governance team member, I want to update my data set to include milestone so that I can track each staging review event in my Domo dashboard.

Assignee: @it-harrison 
Peer Reviewer: @allison0034 

## Description
We have created milestones for every Collaboration Cycle request ticket and ensured that the Collaboration Cycle Request ticket,  DI and MPR feedback tickets, SR finding tickets and all "completed" tickets have been added to the milestone.

We now need to ensure that the query for pulling a subset of this data (currently only the SR finding tickets) into Domo has been modified to include the milestone. The name of the data set in Domo is called 'BQ- Governance Github tickets'.

## Tasks
- [x] ~~Submit the [Analytics Product KPI Dashboard - Update Request Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=michelle-dooley&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&projects=&template=analytics-request-update-kpi-dashboard.md&title=Analytics+KPI+dashboard+update+request+for+%5BTeam%5D) ticket to Analytics team. Be sure to CC Backend COP on the request ticket.~~
- [x] ~~Ask for the milestone field to be added to the existing data set~~
- [x] ~~Ask for the data set to be renamed 'BQ - Staging Review issue tickets'~~
- [x] Once complete, validate that data has been added successfully
- [x] Ensure all applicable [data flows](https://va-gov.domo.com/datacenter/dataflows?bucket=all&inputDataSource=6c15f710-418f-4624-94d3-fffa43feda5c&inputDataSourceName=BQ%20-%20Governance%20Github%20Tickets) are modified to include milestone
New tasks as of 8/29:
- [x] Update the 'BQ- Governance Github tickets' Big Query data set to include the milestone field
- [x] Update the name of the 'BQ- Governance Github tickets' data set to 'BQ - Staging Review issue tickets'

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The data set  'BQ- Governance Github tickets' has been renamed 'BQ - Staging Review issue tickets'
- [x] The 'BQ - Staging Review issue tickets' data set includes the milestone field
- [x] All data flows built off of the data set include milestone

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
[Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64328) submitted to Analytics

**Comment by shiragoodman** [comment]
per guidance from Platform leadership at the Platform huddle on 8/29, Governance will be attempting to update the Big Query data set on their own without support from Analytics and Insights team or the Backend CoP. 

Estimate has been increased to 3. This work will continue into the next sprint.

**Comment by it-harrison** [comment]
This ticket is continuing into the next sprint as we await a tweak on the milestone column from Analytics but is otherwise done.

**Comment by it-harrison** [comment]
@allison0034 this can be reviewed; I'm still waiting for Analytics to clean up the milestone column but right now it is is unique for each Staging review and should not block anything.

**Comment by it-harrison** [comment]
> @it-harrison what is the status of this? Are we still waiting on Analytics to clean up the milestone column?

@shiragoodman Yes, I just pinged them again.

**Comment by allison0034** [comment]
We are still waiting on some data to be cleaned up and corrected.

**Comment by it-harrison** [comment]
@allison0034 Analytics has updated the BQ table so you can review

**Comment by it-harrison** [comment]
Analytics added a column `milestone-number` alongside `milestone`. `milestone-number` is the unique number that GH assigns to each milestone.

**Comment by shiragoodman** [comment]
@it-harrison sounds like this is good to close. Thank you!
