### ISSUE TITLE
Update the Drafting Template to reflect new standards

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#63505]
## User Story
As a Governance team member, I want to have an easy and reliable tool for documenting findings for Staging Review so that I don't encounter problems adding time, and stress, to the process of getting Staging Review findings tickets generated.

Assignee: @shiragoodman 
Peer Reviewer: @erinrwhite 

## Description
In order to pilot our new process, we need to update our DraftingTemplate to do the following:
1. Reflect our new standards
2. Reflect our new categories
3. Easily flag the descriptive tags
4. Pivot how practice area labels are added
5. No longer link to the Product tracker for team, product and/or feature label
6. Store the new experience standards and tags within the DT so no need to import data from another source
7. Change how feedback from 2 or more specialists is merged
8. Update markdown for csv download so it aligns to revised gh template
9. Remove fragility if/when possible (such as conditional logic that is row specific)
10. Easily maintained by the full team, if possible.

## Impacted Artifacts
[Shira's DraftingTemplate 2.0](https://docs.google.com/spreadsheets/d/1dOAJNKYIFQOW5NGNtZ3l0PPEy5MNQHOl0zWEB2cl20E/edit#gid=654390984)

## Tasks
- [x] Update DraftingTemplate to meet above specified criteria
- [ ] Test with Governance team members 

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The revised DraftingTempalte meets the needs of the new VA.gov Experience Standards

## Team Notification
- [ ] Slack post on #platform-governance-team
- [x] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@erinrwhite I believe my [draft DraftingTemplate ](https://docs.google.com/spreadsheets/d/1dOAJNKYIFQOW5NGNtZ3l0PPEy5MNQHOl0zWEB2cl20E/edit#gid=727681601)is ready for review. I have locked several columns and tabs so that you all cannot overwrite any formulas that are critical to the Github Upload tab. Some other things you should keep in mind/test for:
- The 3 blue columns (E, F, G) in the Findings tab are intended for your specific findings. If you and Brian (or whomever) both have comments about a specific issue, then your comment need to go in the same cell.
- You should be able to sort and filter the columns in the findings sheet without messing up any of the formulas and without impacting the Github Uplpoad tab
- I'd encourage you to download the Github Upload tab (with your test data) into a CSV so that you can copy/paste the body into a github issue template. Test to see if the markdown is formatted correctly
- Same with the labels. While you can't easily test the labels in github, the labels in teh csv should be ordered with commas in between, no spaces, and there should be no double commas
- If you mess with the sorts in the Descriptive tags tab or the ES tab, the drop down options in the Findings tab will not work. If you need to reset, the Combined column in the ES tab should be sorted A>Z, and the Sort column in the Descriptive tags tab should be sorted Ascending. I acknowledge this makes the Findings tab somewhat vulnerable. Open to suggestions about how we can or should fix this. Maybe just lock the ES and Descriptive tags tabs so you all are unable to apply filters and sorts?
- Feature label is optional, however team label and product label are required. This should be reflected in the body of the github upload and in the labels
- Feel free to try and break it. I made a copy (called "Copy") in the same folder so we should be okay if anything is lost.

Let me know if you have any questions! Once you're done testing on your own, I encourage you to have the other Governance team members test it out as well.

**Comment by erinrwhite** [comment]
@shiragoodman This is looking FANTASTIC! This was literally a joy to use 😂  I was easily able to enter my three findings from last week's Staging Review.

I added the title/body of each ticket but NOT the label:
[Ticket 1 (launch-blocking)](https://github.com/erinrwhite/stagingreview-mods/issues/5)
[Ticket 2](https://github.com/erinrwhite/stagingreview-mods/issues/6)


A couple of small things I noticed:
- **Autofill on first cell:** when I first opened the file, 'A7' was already prefilled with the first item in the dropdown, instead of being blank
- **Comma after launch-blocking label** - it looks like the launch-blocking label needs a comma after it and before the practice area. Here's the output code for my first ticket, which is missing the comma after launch-blocking:
`collab-cycle-feedback,CC-dashboard,,,staging,Usability,va-breadcrumb,context-navigation,launch-blockingIA,exp-std-flow-completion`
- **Need line breaks after/before toggle tags** - on [the second ticket](https://github.com/erinrwhite/stagingreview-mods/issues/6) and [third ticket](https://github.com/erinrwhite/stagingreview-mods/issues/7) the markdown I wrote for the steps to reproduce is just being echoed as text. I've seen this before and think it has to do with needing carriage returns after the `<toggle>` and before the `</toggle>`
- **Placement of high-level issue and category** On looking at this with fresh eyes, it might make more sense to list "High-level issue" and "Category" above "Launch-blocking:" and leave the description section just for the free-text from the reviewer.

**Comment by shiragoodman** [comment]
> - Autofill on first cell: when I first opened the file, A7 was already prefilled with the first item in the dropdown, instead of being blank

Noted. This was likely just me forgetting to clear the cell. Easy fix.

> - Comma after launch-blocking label - it looks like the launch-blocking label needs a comma after it and before the practice area. Here's the output code for my first ticket, which is missing the comma after launch-blocking:
> - collab-cycle-feedback,CC-dashboard,,,staging,Usability,va-breadcrumb,context-navigation,launch-blockingIA,exp-std-flow-completion

Got it! I can fix that. I also notice a triple comma... assuming that was bc you didn't have a VFS team label and VFS product label? I made the assumption that we'll _always_ have those so it always prints the commas. Please lmk!

> - Need line breaks after/before toggle tags - on https://github.com/erinrwhite/stagingreview-mods/issues/6 and https://github.com/erinrwhite/stagingreview-mods/issues/7 the markdown I wrote for the steps to reproduce is just being echoed as text. I've seen this before and think it has to do with needing carriage returns after the <toggle> and before the </toggle>

No problem. Another easy fix. 

> - Placement of high-level issue and category On looking at this with fresh eyes, it might make more sense to list "High-level issue" and "Category" above "Launch-blocking:" and leave the description section just for the free-text from the reviewer.

Ok I can reorder that too!


I won't be able to make these changes until I'm back at work next week. Please feel free to share with the team for their feedback and opinions as well. Other opportunities for improvement that crossed my mind were:

- Reordering the references in the Github ticket so they are in a more logical order (either alphabetically or by practice area..?)
- possibly making the reference titles bolds. For example, **WCAG Success Criteria:** WCAG 3.3.2 Labels or Instructions - Level A
- removing the Link, screenshot or steps to recreate as a heading and instead just making it the toggle title. 

Thanks, @erinrwhite !

**Comment by erinrwhite** [comment]
awesome @shiragoodman !!

> I also notice a triple comma... assuming that was bc you didn't have a VFS team label and VFS product label? 
yes! Sorry, I should have updated that. I added those items in midway through the process. Here's the final list of tags for the launch-blocker:
`collab-cycle-feedback,CC-dashboard,test-team,test-product,test-product-feature,staging,Usability,va-breadcrumb,context-navigation,launch-blockingIA,exp-std-flow-completion`

All of the other opportunities for improvement sound **excellent.**

Tagging in the team.

**Comment by erinrwhite** [comment]
Some more feedback:

- We should consider adding a new descriptive tag - probably a **context** tag - for headings
-

**Comment by erinrwhite** [comment]
Governance team still reviewing and we've identified a few small mods - this ticket will move into the next sprint.

**Comment by rferguson13** [comment]
I'm not sure that listing all the sections of the Content Style Guide is helpful. Being specific about common issues (capitalization, dates/times) is helpful, but some of the sections, like Plain Language, have a bunch of subpages (e.g. use active voice). It might be good to par down some of the options here. One of my issues didn't fit neatly into one specific category, so I ended up having to go broader anyway.

**Comment by shiragoodman** [comment]
@rferguson13 we talked about adding the subpages of the Plain Language section as either a)their own descriptive tag or b) breaking "Plain Language" down into the smaller chunks so "Plain Language - short sentences" and "Plain Language - active voice." Do you see that being more helpful for you when logging the issue, and for OCTO and VFS teams when reviewing the issue?

**Comment by shiragoodman** [comment]
@erinrwhite @rferguson13 I'm working on making changes and have a question for you. Right now, we have the VA.gov Experience Standard listed in the References section, but then also listed in the Findings details section (per changes Erin suggested in [this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63505#issuecomment-1819838222) - 4th bullet). See screenshot below:
<img width="415" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/71330581/a88a0f78-5993-4d00-b9a5-802fb6b57a80">


Do we need to have them listed in 2 places? I'm proposing we remove the VA.gov Experience Standard from the References section, change "high-level issue" in the Findings details section to "VA.gov Experience Standard - issue:", change "Category" to "VA.gov Experience Standard - category:", and include links to the category and/or issue where appropriate - depending on how we structure the revised VA.gov Experience Standards page on Platform Website.

What do you think?

**Comment by erinrwhite** [comment]
@shiragoodman I like it! Good suggestion to keep this ticket streamlined.

**Comment by shiragoodman** [comment]
@erinrwhite @rebeccawalsh ok this is done! or as done as it can be right now. Here's a couple additional things we'll need to do once we're ready to publish:

1. Reorder the references. I wasn't sure what the best order would be, so I left this as-is. However, we can easily change it now if anyone on the team has a preferred order.
2. Provide a link to the VA.gov Experience Standard issue and/or category in the Findings details section (dependent on how we update the current Exp Std page)

**Comment by shiragoodman** [comment]
@erinrwhite @rferguson13 closing this ticket out. If we need to make additional changes, we can do so later via another ticket.
