### ISSUE TITLE
Identify and update Staging Review operational documentation

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#63513]
## User Story
As a Governance team member, I want to review all operational documentation related to the Collaboration Cycle Staging Review to identify what documents need to get updated per our revised Experience Standards and Staging Review process so that I may make the necessary updates.

Assignee: @erinrwhite 
Peer Reviewer: @briandeconinck 

## Description
As we prepare for rollout of the revised VA.gov Experience Standards, we need to ensure that our operational documentation (aka Confluence) has been updated to reflect our new standards and/or our new processes. 

The purpose of this ticket is to review all operational documentation related to the Collaboration Cycle Staging Review to identify which documentation will need to be modified, and then made the necessary modifications. 

## Impacted Artifacts

In the [Platform products and services](https://vfs.atlassian.net/wiki/spaces/PPS?homepageId=1391067357) section:
- [x] [VA.gov Experience Standards](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2001862791/VA.gov+Experience+Standards)
  - [ ] [(WIP) How to maintain the VA.gov Experience Standards](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1941176380/WIP+How+to+maintain+the+VA.gov+Experience+Standards)
- Collaboration cycle touchpoints
  - Staging review
    - [x] [How to document findings for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+findings+for+Staging+Review)
    - [x] [How to Add Images to the Staging Review DraftingTemplate](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2396619099/How+to+Add+Images+to+the+Staging+Review+DraftingTemplate)
    - [x] [How to generate Staging Review issue tickets](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808217924/How+to+generate+Staging+Review+issue+tickets)
    - [x] [DraftingTemplate Outline](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2385248274/DraftingTemplate+Outline)
    - [x] [Staging Review findings - issue template](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2548957608/Staging+Review+findings+-+issue+template)

[Folder of in-progress draft pages](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2866610177/63513+-+Update+operational+docs+for+new+experience+standards)

## Tasks
- [x] Review all Staging Review documentation within the Platform Products and Services space on Confluence
- [x] If any documents need to be modified, please list them above in the Impacted Artifacts section of this ticket
- [x] Create a folder in the Documentation Drafts folder of the Governance Team space for storing copies of all draft documents 
   - Note: please do not edit the live documents as we have not yet launched our new process. We are uncertain when we will launch, so we need to ensure our existing processes are upheld until then.
- [x] Make appropriate updates to the documents. You are encouraged to discuss changes with your peer reviewer.
  - [x] [#63513 - VA.gov Experience Standards](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2866675713/%2363513+-+VA.gov+Experience+Standards)
  - [x] ~~(WIP) How to maintain the VA.gov Experience Standards~~ (Deleted)
  - [x] [#63513 - How to document findings for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2866610252/%2363513+-+How+to+document+findings+for+Staging+Review)
  - [x] [#63513 - How to Add Images to the Staging Review DraftingTemplate](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2866610542/%2363513+-+How+to+Add+Images+to+the+Staging+Review+DraftingTemplate)
  - [x] [#63513 - How to generate Staging Review issue tickets](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2866610576/%2363513+-+How+to+generate+Staging+Review+issue+tickets)
  - [x] [#63513 - DraftingTemplate Outline](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2866610604/%2363513+-+DraftingTemplate+Outline)
  - [x] [#63513 - Staging Review findings - issue template](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2866610629/%2363513+-+Staging+Review+findings+-+issue+template)

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team operational guidance has been updated to reflect the change in our VA.gov Experience Standards

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
Identified guidance, listed in the [impacted artifacts section](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63513#:~:text=the%20necessary%20modifications.-,Impacted%20Artifacts,-In%20the%20Platform), and created a [folder of drafts](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2866610177/63513) in the Governance team space.

**Comment by erinrwhite** [comment]
In progress, but two in-detail pages remain, so this one's moving to the next sprint. I was out a couple days this sprint and it's been a busy time for collab cycle reviews.

**Comment by erinrwhite** [comment]
@briandeconinck I think these are ready for your review. Take your time!

- [#63513 - VA.gov Experience Standards](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2866675713/%2363513+-+VA.gov+Experience+Standards)
- ~~(WIP) How to maintain the VA.gov Experience Standards (Deleted)~~
- [#63513 - How to document findings for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2866610252/%2363513+-+How+to+document+findings+for+Staging+Review)
- [#63513 - How to Add Images to the Staging Review DraftingTemplate](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2866610542/%2363513+-+How+to+Add+Images+to+the+Staging+Review+DraftingTemplate)
- [#63513 - How to generate Staging Review issue tickets](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2866610576/%2363513+-+How+to+generate+Staging+Review+issue+tickets)
- [#63513 - DraftingTemplate Outline](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2866610604/%2363513+-+DraftingTemplate+Outline)
- [#63513 - Staging Review findings - issue template](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2866610629/%2363513+-+Staging+Review+findings+-+issue+template)

**Comment by briandeconinck** [comment]
@erinrwhite these all look good!

**Comment by erinrwhite** [comment]
Thank you @briandeconinck ! Closing this ticket. 👍🏻
