### ISSUE TITLE
Define new naming convention/ID for new standards

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#63511]
## User Story
As a Governance team member supporting Staging Review in the Collaboration Cycle, I want to ensure that the new standards have unique identifiers so that I can easily reference them, label them and track metrics on them.

Assignee: @erinrwhite 
Peer Reviewer: @allison0034 

## Description
Our new revised VA.gov Experience Standards need a naming convention/unique identifier. The naming convention for the new standards should be different than the old naming convention to avoid confusion when mapping the old standards to the new standards. We'd also like to try and provide more transparency in the standard labeling so it's easy for Governance and VFS teams to understand the high level problem right away without having to cross reference the VA.gov Standards page. 

Per @erinrwhite at the 9/7 refinement:

> If we end up using the categories it could be a category-issue naming convention
> Findability-2

Team agreed with the above suggestion!

Note: the IDs we choose will also be the Github label in the va.gov-team repo. They will replace the CCIssue labels for the MVP version of the VA.gov Experience Standards. 

## Tasks
- [x] Develop system and unique for labeling each [new experience standard](https://docs.google.com/spreadsheets/d/1q6UGLEd8re94B5o69EFDz2HNMHw6WvdAHl46FHYsA9s/edit#gid=2089466616)
- [ ] Develop crosswalk for old-to-new labels, where applicable

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have identified IDs for all new VA.gov Experience Standards

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
@allison0034 I've [drafted some options for labeling the new standards](https://docs.google.com/spreadsheets/d/1q6UGLEd8re94B5o69EFDz2HNMHw6WvdAHl46FHYsA9s/edit?usp=sharing) for your review - one using the category name and the other using descriptive text for each standard. Does either of these methods resonate more with you, or should we pursue something else? Thank you for the review. Also hoping to talk with the team about this at our initiative meeting tomorrow.

**Comment by allison0034** [comment]
@erinrwhite which tab do you want me to look at : )

**Comment by erinrwhite** [comment]
@allison0034 oops! [New Standards](https://docs.google.com/spreadsheets/d/1q6UGLEd8re94B5o69EFDz2HNMHw6WvdAHl46FHYsA9s/edit#gid=2089466616).

**Comment by erinrwhite** [comment]
Made some progress here, but want to align this with the new standards in partner ticket #62952 - moving to the next sprint.

**Comment by allison0034** [comment]
Personally I like descriptive text bc I think we all get a little confused by category but maybe we should confirm with the team?

**Comment by erinrwhite** [comment]
@allison0034 cool. I have updated the final [list of standards with their suggested descriptive labels](https://docs.google.com/spreadsheets/d/1q6UGLEd8re94B5o69EFDz2HNMHw6WvdAHl46FHYsA9s/edit#gid=2089466616). Can you give the labels a once-over and see if there are better/clearer labels for any of these standards? thank you!
