### ISSUE TITLE
Define study for measuring consistency of use of standards across Staging Reviews

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#63510]
## User Story
As a Governance team member, I want to measure/capture how the new process for Staging Reviews is working so that I can identify areas where there are challenges and make changes to improve the process.

Assignee: @erinrwhite 
Peer Reviewer: @briandeconinck 

## Description
In the effort to revise the VA.gov Experience Standards and Staging Review process, we recognized that it would be valuable for Governance team to check back in several months after launch to verify that we're applying the new standards consistently. The [research](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3015933954/2023-24+New+Experience+Standards+research) we did prior to launch really only evaluated our experience applying the standards within the boundaries of 1 Staging Review. It is critical that we ensure standards expectations are met across all SRs, which is why we're developing a new Research Plan that will be executed at a later date.

### Notes from team at Refinement

- same questions that we had for the Governance pilot study
   - still easy to apply tags, instances of when we don't know what standards to apply, etc.
- goal is to id areas for improvement to the process
- talk thru some recurring issues (via tracking document/lightweight mechanisms)
- If there are any standards that need to be further defined.
- look at a specific standard from one SR to the next to see if it's been applied consistently
- better timelines on when specific issues should be prioritized 
- Let's measure how quickly teams fix the non-launch blocking issues
   - per CAIA, "we give them the content, but we don't tell them how to put them in"
   - how many issues are being created bc VFS teams didn't interpret CAIA's content guidance correctly? or IA?

## Tasks
- [x] Draft a Research Plan following the [Platform Research guidelines.
](https://vfs.atlassian.net/wiki/spaces/DCP/pages/2480046097/Getting+started+with+research+for+the+Platform)
- [ ] Share with governance team via Slack for their review and input. Tag Matt too.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have drafted a research plan for measuring the consistency of use of standards across Staging Reviews

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
This ticket will be pulled from initiative #45160 as it is intended to be completed several months after launch. This will be moved to the backlog and addressed at a later date.

**Comment by erinrwhite** [comment]
[Started draft of plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3121315853/2024+Experience+standards+Consistency+of+use+research+plan)

**Comment by erinrwhite** [comment]
@briandeconinck can I get your thoughts on [overall direction for this study](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3121315853/2024+Experience+standards+Consistency+of+use+research+plan)? Still some parts to fill in - and I have a couple questions/thoughts in the comments too.

**Comment by briandeconinck** [comment]
Left a few disorganized comments, will think on it more. But I think in general you're heading in the right direction.

**Comment by erinrwhite** [comment]
@briandeconinck I **love** your idea for the consistency check. I baked that in and tied everything together. Can you review again?  I'm also tagging @shiragoodman for her eyes when she's back in next week.

**Comment by shiragoodman** [comment]
@erinrwhite I took a look at this and wrote a couple comments. Solid plan. I appreciate the different methodologies for assessing where we're at 6 months in. Thank you!

**Comment by shiragoodman** [comment]
@erinrwhite I took a look at this and wrote a couple comments. Solid plan. I appreciate the different methodologies for assessing where we're at 6 months in. Thank you!

**Comment by erinrwhite** [comment]
Thank you @shiragoodman! @briandeconinck let me know when you think this one's ready to close. [Research plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3121315853/2024+Experience+standards+Consistency+of+use+research+plan)

**Comment by briandeconinck** [comment]
@erinrwhite this looks good to me!

**Comment by erinrwhite** [comment]
thank you @briandeconinck! Realized I hadn't shared with the team - did that as well, and will plan to close this later today before end of sprint.

**Comment by erinrwhite** [comment]
All set! Closing.
