### ISSUE TITLE
work on Sentry doc per Jill Adams questions

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#63526]
## Info
- Original customer (Jill Adams) inquiry: https://dsva.slack.com/archives/CBU0KDSB1/p1689967384194959
- Lauren's support request for SME: https://dsva.slack.com/archives/CBU0KDSB1/p1691760844399189

## Tasks
- [x] Work with customer and Platform SME on vetting the issue
- [x] Align with customer and Platform SME on how to update content
- [x] Prepare page for deployment

## Acceptance Criteria
- [x] The [Tracking application errors with Sentry](https://depo-platform-documentation.scrollhelp.site/developer-docs/tracking-application-errors-with-sentry#TrackingapplicationerrorswithSentry-MonitoringSlackalerts) page will have content corrected regarding Sentry alerts via Slack
