### ISSUE TITLE
Add user attributes for Sign in Service access token

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#63523]
# Issue Description
In order for clients to be able to more easily use a SiS access token to instantiate a user and session, the access token's payload should be expanded to include several identifying attributes:
* first_name
* last_name
* email

These attributes will be included on an opt-in basis per the client's ClientConfig: a new attribute, `access_token_attributes`, an array of strings specifying which attributes should be included in the access token.

# Tasks
- [x] Add `access_token_attributes` attribute to ClientConfig
- [x] `access_token_attributes` parsing for CSP-derived attributes to include
- [x] update access token with `first_name`, `last_name`, and `email` attributes
- [x] update relevant unit specs
- [ ] update relevant documentation

**Comment by bramleyjl** [comment]
Minor bug has arisen with the introduction of this feature:
* Bug thread: https://dsva.slack.com/archives/C04LW2P19M0/p1695058158360039
* Bugfix thread: https://dsva.slack.com/archives/C04LW2P19M0/p1695059442939229
* Bugfix PR: https://github.com/department-of-veterans-affairs/vets-api/pull/13852

I'm going to wait for the bugfix PR to be merged tomorrow and making sure the issue is taken care of beffore closing this PR.

**Comment by bramleyjl** [comment]
Number of incidents is trending down; will continue to monitor over the next few days.

http://sentry.vfs.va.gov/organizations/vsp/issues/230705/?project=3&query=is%3Aunresolved+%23refresh&statsPeriod=14d

**Comment by bramleyjl** [comment]
Incidents have stopped as of 9/20/23.
