### ISSUE TITLE
Reference CAIA content artifacts at Midpoint and Staging

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#63537]
## User Story
As a VFS team member, I want to have explicit and clear asks from Governance team in the Collaboration Cycle so that I can be sure to share with them what they need to complete their reviews.

Assignee: @CherylEvans 
Peer Reviewer: @allison0034 

## Description
Currently at MPR and SR, we ask the VFS team to provide the CAIA IA artifact, if applicable, however we do not ask the VFS to provide the CAIA content artifact. Our language around the content artifacts is much more vague and should be more clear and direct.

Current Midpoint Review language for content artifacts:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaUpTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6177f4171d661ea0c3a867653c0abf1ffee512b7/image.png)

Current Staging Review language for content artifacts:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaU5TIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--19331a11d4030d2029b1ddf03649ca878d47c11e/image.png)

IA artifact language for both Staging and Midpoint:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaXRTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ee435253b3457c983fe593d838000887ae27b6d6/image.png)

## Impacted Artifacts
[Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities) - codeblocks for Midpoint and Staging Review

## Tasks
- [x] For Midpoint Review, change the "Github ticket for any..." to "Please include a link to any Sitewide CAIA feedback you received, including a content source of truth, any relevant static content page and entry point updates, and the intake form."
- [x] For Staging Review, copy/paste the same verbiage from Midpoint Review
- [x] Ensure "Sitewide CAIA" links to the[ Sitewide CAIA touchpoint page. ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request)
- [x] The Sitewide CAIA link under the IA artifacts is broken, so please fix the link.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS teams are asked to share their CAIA content updates at Midpoint Review and Staging Review

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
@shiragoodman, Will you provide a bit more detail for task #4, please? I am unsure what link you are referring to and where it lives. :-) Thank you!
"The Sitewide CAIA link under the IA artifacts is broken, so please fix the link." There are multiple links [here](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request#SitewideContent,Accessibility,andInformationArchitecture(CAIA)intakerequest-Artifacts) and so I am confused.

**Comment by CherylEvans** [comment]
Draft of [CC Kickoff Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2754707457/63537+-+Cheryl+-+Copy+of+Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities+2) created

**Comment by CherylEvans** [comment]
@allison0034 I think I am ready for our peer review; no rush! :-)

**Comment by allison0034** [comment]
Peer review complete : )
