### ISSUE TITLE
Add EDIPI identifier to user 81 mockdata

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#63531]
## Issue Description
To be consistent with testing, it'd be useful if user 81 had an EDIPI identifier to access copays. This is one of our team's go to users in staging for testing copay data and it would make sense to also be a user we can use locally.

---
## Tasks
- [ ] Add EDIPI to user's mockdata profile

## Acceptance Criteria
- [x] Test and confirm user 81 can access `/medical_copays` route
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
Moving to backlog for now

**Comment by kjsuarez** [comment]
[Relevant conversation](https://dsva.slack.com/archives/CSFV4QTKN/p1709851247285819)

**Comment by kjsuarez** [comment]
Completed as part of #75342
