### ISSUE TITLE
Audit Domo Datasets

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#6356]
## User Story or Problem Statement
How might we clean up the data sets from our MVPs in Domo? How might we determine the path with the best data integrity?

## Goal
Clean up the current Domo sets, and determine which datasets will need to be switched over to BigQuery

## Tasks
- [ ] Document:
  - [ ] Which datasets will need to be switched over to BigQuery
  - [ ] Which datasets will need to be cleaned and in which ways
  - [ ] Which datasets will need to be deprecated
- [ ] Rename datasets via [Domo naming conventions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/domo-data-naming-conventions.md)
- [ ] Reassign any current datasets that Nedie or Joy might still own
- [ ] Stretch: Deprecate relevant datasets
- [ ] Stretch: Clean up relevant datasets

## Acceptance Criteria
- [ ] VSP Analytics & Insights has a clean dataset slate in Domo
- [ ] VSP Analytics & Insights understands which datasets need to be switched over to BigQuery
- [ ] VSP Analytics & Insights understands which datasets need to be cleaned
- [ ] VSP Analytics & Insights understands which datasets need to be deprecated

**Comment by nedierecel** [comment]
@joanneesteban Updates to Domo housekeeping:

1. Ownership - I have transferred the ownership for the Education dashboard to you.
2. Data Sets - For data sets that I own, I deleted ones that were not powering any cards or dataflows. These are marked by "Nothing in Domo uses this dataset"
 
- Data Flow: Education Modernized - Blended Goals - Conversion Rate 
- GA Connector: Education Modernized - Content

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/d604d370-14fc-4ac0-93a6-6b9d2a4ef781)

**Comment by joanneesteban** [comment]
Thank you, @nedierecel . Noting this for https://github.com/department-of-veterans-affairs/va.gov-team/issues/7161.

Moving to the backlog to groom when we can clean up the rest of the datasets.

**Comment by jonwehausen** [comment]
@jonwehausen test integration

**Comment by jonwehausen** [comment]
@jonwehausen test integration2

**Comment by joanneesteban** [comment]
Repurposing this issue to `Audit Domo Datasets` for Sprint 32.

**Comment by bmcgrady-ep** [comment]
Domo Dataset Audit Updates:
Dataset Name | Backup Status | Backfill Status | QA Status  
------------ | ------------- | ------------- | -------------
[Partitioned] VA.gov COVID-Related Page Metrics by Date | ✔️ | ✔️  | ✔️ **PASS**
[Partitioned] COVID FAQ Entrance Data | ✔️ | ✔️  | ✔️ **PASS**
[Partitioned] COVID Navigation Events (Apr 21 - current) | ✔️ | Wasn't needed  | ✔️ **PASS**
[Partitioned] COVID FAQ - No FAQ Question Interactions | ✔️ | ✔️  | ✔️ **PASS**

**Comment by bmcgrady-ep** [comment]
Domo Dataset Audit Updates:
Dataset Name | Backup Status | Backfill Status | QA Status  
------------ | ------------- | ------------- | -------------
[Partitioned] Chatbot Entrance Data | ✔️ | ✔️  | ✔️ **PASS**
[Partitioned] VA.gov COVID-Related Page Metrics by Date | ✔️ | ✔️  | ✔️ **PASS**
[Partitioned] PH & MH Entrance Data | ✔️ | ✔️  | ✔️ **PASS**
[Partitioned] PH & MH Entrance Data | ✔️ | ✔️  | ✔️ **PASS**

**Comment by bmcgrady-ep** [comment]
Here is the DOMO Audt document showing the progress: https://docs.google.com/spreadsheets/d/1GMGXc3fWZ7T5SADib0MhfJFxRpLwj7ZEyEwLZKWU9Ds/edit?usp=sharing

**Comment by joanneesteban** [comment]
Thanks, @bmcgrady-ep ! So it looks like that's the Covid dashboard audit. Do you have documentation for the overall Domo dataset audit?

**Comment by joanneesteban** [comment]
## Final To Do:

- [ ] Update & clean up spreadsheet
- [ ] Consolidate this spreadsheet with the BigQuery audited migration trackers

**Comment by joanneesteban** [comment]
To close out our Domo dataset audit, we'll need to update the spreadsheet with final to do's:

At the end of the day, we're looking to update the naming taxonomy so that each of our datasets clearly show the following:

- What type of data is it (i.e. contact center calls, time to complete, a combination of something)
- Is the data currently being used (i.e. production vs. test vs. archived data)

**OR** have a naming or tagging framework so that we can easily sort and filter the datasets

This isn't urgent, so @jonwehausen @bmcgrady-ep let me know if you'll be able to pick this up this sprint. Otherwise, we can put this in our backlog.

**Comment by jonwehausen** [comment]
Has been done several times since ticket origin, closing.
