### ISSUE TITLE
Research upgrade process for React Router

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#63561]
## Issue Description
React Router on vets-website is 3 full versions behind. Currently, vets-website is using 3, while the current version is 6.15. When upgrading this many versions, there may be substantial changes that are needed to be made and some research will need to be done to see what is going to be involved.

---
## Tasks
- [ ] Research if there is guidance for the process we should follow when upgrading. One version at a time? Jump all the way there? Sometimes the official packages put out upgrade guides themselves as well that tell you what to change.
- [ ] Research exactly what changes are needed and what teams they impact. Syntax changes may apply across most applications in vets-website. A plan will need to be laid out to determine how to approach these changes.
- [ ] Research if there's any way to change over one app at a time, or if they all need to be done together? Will upgrading have breaking changes across the board or is there any backwards compatibility? These concerns may be addressed by the above two tasks.
- [ ] Develop a plan for testing our changes based on the nature of what needs to be done, to be sure we have a way to tell if the update was successful and didn't break anything.

## Acceptance Criteria
- [ ] We have a clear approach for what changes need to be made and who will be completing them.
- [ ] We have a strategy to implement these changes as carefully as possible.
- [ ] We have a testing plan to ensure that we didn't accidentally cause any issues by upgrading.
---
