### ISSUE TITLE
[SW] Convert privacy link component to web component 

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#63598]
## Issue Description
[Privacy policy link](https://github.com/department-of-veterans-affairs/vets-website/blob/77ec575aa682e1d37cff66f9b345362df01f2bed/src/applications/financial-status-report/components/shared/PreSubmitSignature.jsx#L239C7-L249C9) is currently a basic checkbox with custom logic attached to it, but it should be converted to the [VA Privacy agreement component](https://design.va.gov/components/form/privacy-agreement).

---
## Tasks
- [ ] Convert privacy link checkbox to va privacy agreement component
- [ ] Update privacy link logic to work with va privacy agreement component

## Acceptance Criteria
- [ ] Privacy link checkbox has been converted to va privacy agreement component
- [ ] Privacy link logic hs been updated to work with va privacy agreement component
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
@OptionSelect - this is the ticket we discussed in planning that we will bring into S106. I am not sure what the LOE is on this ticket; please feel free to point as you see fit!

Thanks!
