### ISSUE TITLE
Identity Dashboard (FE) - Add Frontend Validation to Teams Pages

### ISSUE THREAD

**Issue by ianmagenta** [department-of-veterans-affairs/va.gov-team#63593]
## Description
Right now, the Register and Edit teams pages lack proper front-end validation for their various input fields.

## Tasks
- [x] On the *Register a new team* page
  - [x] The required fields should be validated (using html pattern validation for now).
- [x] On the "Edit your team" page
  - [x] Same validation as the Registration page.
