### ISSUE TITLE
Organizing Content Review criteria ideas

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#63607]
## Tasks

- [x] Organize ideas we've documented to create a content review process
- [x] Create questions to align as a team on
- [x] Share with the team questions to answer
