### ISSUE TITLE
Burial | Build Review Page

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#63627]
## Issue Description
_Along with deactivating the digital burial form (530), the current review page needs to be updated to remove the ability to edit in-progress information, remind users the digital form is no longer available, and provide users with instructions on how to submit their in-progress claim._

---
## Resources
 - [New Burial Review page](https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/a/bLoZGjJ) 
 - [Experimental design approved by Matt Dingee](https://preview.uxpin.com/97fe1afd9dd5b538d36e48187b4a24133e2a6bed#/pages/150671274/simulate/sitemap?mode=v)

---
## Tasks
- [x] Build redesigned form review page for the digital burial form (530) that aligns to [Sketch file](https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6)
- [x] Work in tandem with accessibility expert to mitigate accessibility issues prior to CAIA staging review
- [x] Build javascript redirect requests behind feature flag

## Acceptance Criteria
- [x] Completed review page
- [x] Redirects built
---

**Comment by sortizsh** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/62022#issuecomment-1684137204
