### ISSUE TITLE
Design | Profile Hub | Research Logistics (kickoff meeting)

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#63621]
## Background
We completed the research plan #63617 and convo guide #63619. This ticket covers the next steps

## Tasks

- [x] Submit research plan
- [x] Meet with Perigean to discuss recruitment criteria
- [x] Confirm recruiting has been kicked off
- [x] Create observer Mural board
- [x] Schedule debrief sessions w/ team
- [x] Complete any other steps needed to prepare while recruiting takes place

**Comment by mtcA6** [comment]
@pamela-drouin mind pointing this one? 

I'm thinking you'll say 5 (with a possibility of an 8 since it's your first time running a VA usability study) but let me know
