### ISSUE TITLE
Pension | Build Review Page

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#63626]
## Issue Description
_Along with deactivating the digital pension form (527), the current review page needs to be updated to remove the ability to edit in-progress information, remind users the digital form is no longer available, and provide users with instructions on how to submit their in-progress claim._

---
## Resources
 - [New Pension Review Page](https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/a/MmLK81w)
 - [Experimental design approved by Matt Dingee](https://preview.uxpin.com/97fe1afd9dd5b538d36e48187b4a24133e2a6bed#/pages/150671274/simulate/sitemap?mode=v)

---
## Tasks
- [x] Build redesigned form review page for the digital pension form (527) that aligns to [Sketch file](https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6)
- [x] Work in tandem with accessibility expert to mitigate accessibility issues prior to CAIA staging review
- [x] - [ ] Build javascript redirect requests behind feature flag

## Acceptance Criteria
- [x] Completed review page
- [x] Redirects built
---

**Comment by sortizsh** [comment]
please refer to CAIA comments on this ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/62022#issuecomment-1684137204

**Comment by steele-lm** [comment]
@fred-khoury-oddball I added the javascript redirect tasks to this ticket (and the related pension ticket)

**Comment by fred-khoury-oddball** [comment]
Thank you. I will sync with @Midge-dev on these changes.

**Comment by Midge-dev** [comment]
Pension review page is now undergoing Peer Review and refinement. Thanks!
