### ISSUE TITLE
UX | Profile Hub | Synthesize research data

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#63623]
## Background 
Now that we've completed our usability testing we need to synthesize our findings 

## Tasks 
- [x] Write [research summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2023-10-profile-hub-usability/research-findings.md)
- [x] kicking the tires of EnjoyHQ!!!! 
- [x] Have the report peer reviewed
- [x] ensure any issue tickets have been created/documented (trav created #69410) 
  

## Acceptance Criteria
- [x] report has been shared with PM/PO
- [ ] ~Results in decisions on design iteration~ <striking this we'll make those decisions in #69410

**Comment by andaleliz** [comment]
@pamela-drouin one thing I typically do with studies like this is create a topline summary. I keep them pretty informal and use it as a way to capture the top of mind findings, with a few bullets to support each.  Then I share w/ the team and ask for quick feedback to make sure we're all in alignment about what to focus on for the deep dive synthesis. 

[here's an example.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/discovery-and-research/usability-study-add-email-jan-2023/topline-summary.md)

I think it's up to the individual research whether or not this is a helpful step, and wanted to mention it so it can be added as a task to this ticket, or a separate one gets created, if you want to do this.

**Comment by pamela-drouin** [comment]
Thank you! I agree doing a topline summary and sharing with the team to ensure alignment is the best way to guide synthesis.

Appreciate you linking to an example! I'd probably include the topline summary in this ticket -- I'll go ahead and add it.

**Comment by pamela-drouin** [comment]
@mtcA6 carrying over all 5 points

**Comment by pamela-drouin** [comment]
The [research summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2023-10-profile-hub-usability/research-findings.md) is ready for peer review! @andaleliz -- I look forward to hearing your feedback.

I still have to fill out the research recruitment checker and update the `Underserved groups we haven’t talked to` but that will be done shortly.

**Comment by andaleliz** [comment]
@pamela-drouin Pam, this is a gold mine of data! It’s clear you put a lot of care and attention into this synthesis. My feedback is below, but as usual, take it or leave it! It’s super solid as it is.

### Overall
- Nice work adding links to relevant docs like the hubless spoke issue. That’s super helpful context for folks who are coming into this brand new.  It might be worth linking to the 2 other initiatives your data supports (personal health care contacts in the additional insights section) and enhanced military info, just for future researchers who might look into these topics. You know they’ll appreciate the trail of breadcrumbs you leave ;) 
- It might be helpful to add a couple more screenshots:
  - of the hub page we tested somewhere early in the doc
  - Finding 2, of the auth menu and the My VA profile link (maybe combined into one image)
### Research questions
In the “if time permits” section, you might want to add a bullet about military info, since we asked so many participants about that.

### Hypothesis
- I have mixed feelings about the table; I personally love it, but I’m not sure if the headings are sufficient to give context to what people are passing/failing. Maybe include a link to the convo guide where the tasks are explained, or it could be included in the appendix, where we can assume people would find it once they’ve familiarized themselves w/ the doc and have more context about the study overall.

> * LIKELY TRUE – No participants mentioned the fact that the sidebar nav appeared alongside sections, but went away after returning to the profile hub. Interestingly, participants didn’t use the sidebar nav for navigation 100% of the time – some participants used the back button, breadcrumbs, or even authenticated menu to return to the profile hub.

I totally forgot about this research question, and this is fascinating! I can’t believe no one used the side bar for nav.

### Findings
- I think you can remove the bullets under finding 3. They read more like details to me, and you could add them to the detail as an elaboration.
- You may want to consider splitting finding 4 into two findings, since one point (deep link) is closely tied to a research goal and the other was related to bonus info.
### Details of Findings
- One thing I do is write my findings as headings, so they can be linked to and make the doc more scannable. I personally love encountering this when I’m writing up a desk research summary and want to link to a particular finding in a markdown file.  It also makes it possible to link to each finding detail in the **key findings section** so reader can easily jump down to the details about something if so inclined.
- You may want to consider a tighter edit of quotes, only so the most impactful ones stand out and really pack a punch. I love a good quote, so I know it’s incredibly hard to cut any of them out. For example, I think the most powerful part of the first quote for finding 4 is the bolded part, and the sentence after.
#### Finding 3
- One thing I think is really interesting about this is that people used the hub page as a navigation tool, rather than just an intro/overview page to the profile. Idk if that has any significance, but I was surprised to see that in the sessions I observed.
- Do you think this implies that people are fine without the side nav? If so, you could add something here to speak to that directly, and tie to more closely to the research questions

#### Finding 4
- Did anyone get confused by leaving the profile and coming back for it after clicking a deep link? If not, I would call that since that was one of the things we wanted to understand.
- I like how you explained your process as a moderator here, that provides some helpful context.

#### Finding 5
The second sentence (starting with `When participants…`) is a little confusing - consider rephrasing to something like “We asked participants questions around dependents and letters to see whether or not…”

#### Finding 6
> Not all participants had dependents, but when asked where P4 would expect to add their forthcoming spouse as their dependent, they initially said they didn’t know, but when probed, they said their profile, since:

This reads a little awkwardly to me; might want to consider breaking it up into 2 sentences.

### Additional insights
- I love the animated gifs! What a great addition.
- “**Breadcrumb home should be My VA**” yaaaaas it should Thank you P2.

### Recommendations
- How are you feeling about the amount of SR participants we got? Curious if you recommend testing with more, though I know you want to discuss as a team too.

**Comment by pamela-drouin** [comment]
@Samara-Strauss & @mtcA6 -- I've incorporated Liz's feedback and the [findings summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2023-10-profile-hub-usability/research-findings.md) is ready for your review! I'm eager to hear both your thoughts!

**Comment by Samara-Strauss** [comment]
This is fantastic @pamela-drouin. No questions/feedback from me beyond this being great work! Thank you so much!

**Comment by mtcA6** [comment]
Agree, this is excellente! I'm sorry you had to wrangle EnjoyHQ. Good job on your first usability testing adventure with the VA! 🎉 

I've created the next ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/69410 since our next step is iteration so we can account for the issues the last screen reader user experienced. Going to close this ticket out!
