### ISSUE TITLE
Phase 3: Merge ds-playground into main in vets-website - Development

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#63632]
## Description
Much of the work to showcase the differences and functionality V3 components have in comparison to current web components has been done in a branch within vets-website called `ds-playground`. This branch has never been checked into `main` and has diverged significantly from the rest of vets-website, being approximately 440 commits behind `main` and 140 commits ahead. Rather than attempt to rebase or resolve merge conflicts when merging `main` into `ds-playground`, it's most likely easier to copy the V3 playground app and the V1 playground app into a fresh branch off `main`, and then submit a PR to check those apps in. Checking these applications into main will give us the benefits of:
1. Not needing to maintain a separate branch
2. Being able to observe how the playgrounds behave in staging, an environment similar to production

## Considerations
- All apps that get checked into `main` in vets-website have a corresponding entry in the [registry.json file](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json) of the `content-build` repository. Entries for each version playground should be added to the content-build registry, with the flag `vagovprod: false` included. This allows us to deploy to staging but keep our applications out of production
- Once this ticket is done, all playground work will be done as regular feature work: PRs will go into `main` instead of a separated, dedicated development branch.

## Tasks
- [ ] Create a new feature branch off the most up to date `main` and add the playground apps to that branch
- [x] Submit a PR into main in vets-website
- [ ] Submit a PR into content-build that adds entries into the registry for each playground
