### ISSUE TITLE
Edit.unit.spec.jsx exhibits flaky results

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#63649]
#### What I expected to happen
Unit tests that are not related to the code being updated, pass as expected since nothing has changed in the code that this test applies to.

#### What actually happened
This test failed during an OOB deployment, however when rerun with no code changes, passed the second time. This indicates that the test is flaky and is testing something that is not consistent, reliable behavior and should either be rewritten, or the unreliable part of the code should be adjusted for consistent behavior. No code related to this test was adjusted in this pull request.

The errors from the test are as follows:
```
  1) <Edit>
       renders form with toggle `profileUseFieldEditingPage` turned ON and valid fieldName query present:
     TestingLibraryElementError: Unable to find an element with the text: Add or update your mobile phone number. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

<body>
  <div>
    <div
      class="sc-bdfBQB bRDNKY vads-u-margin-top--2 vads-u-margin-bottom--3"
    >
      <a
        href="/profile"
      >
        Back to profile
      </a>
    </div>
    <h1
      class="vads-u-font-size--h2 medium-screen:vads-u-margin-top--1p5 vads-u-margin-top--4"
    >
      Edit your profile information
    </h1>
    <p
      class="medium-screen:vads-u-margin-bottom--2 vads-u-margin-bottom--0p5 vads-u-margin-top--0"
    >
      Choose a section to get started:
    </p>
    <ul
      class="vads-u-margin-top--0"
    >
      <li>
        <va-link
          href="/profile/personal-information"

  2) <Edit>
       renders fallback with toggle `profileUseFieldEditingPage` turned ON and invalid returnPath in query params:
     TestingLibraryElementError: Unable to find an element with the text: Add or update your mobile phone number. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

<body>
  <div>
    <div
      class="sc-bdfBQB bRDNKY vads-u-margin-top--2 vads-u-margin-bottom--3"
    >
      <a
        href="/profile"
      >
        Back to profile
      </a>
    </div>
    <h1
      class="vads-u-font-size--h2 medium-screen:vads-u-margin-top--1p5 vads-u-margin-top--4"
    >
      Edit your profile information
    </h1>
    <p
      class="medium-screen:vads-u-margin-bottom--2 vads-u-margin-bottom--0p5 vads-u-margin-top--0"
    >
      Choose a section to get started:
    </p>
    <ul
      class="vads-u-margin-top--0"
    >
      <li>
        <va-link
          href="/profile/personal-information"
          text="Personal information"
        />
      </li>
      <li>
        <va-link
          href="/profile/contact-information"
          text="Contact information"
        />
      </li>
      <li>
        <va-link
          href="/profile/military-information"
          text="Military information"
        />
      </li>
      <li>
        <va-link
          href="/profile/direct-deposit"
          text="Direct deposit information"
        />
      </li>
      <li>
        <va-link
          href="/profile/notifications"
          text="Notification settings"
        />
      </li>
      <li>
        <va-link
          href="/profile/account-security"
          text="Account security"
        />
      </li>
      <li>
        <va-link
          href="/profile/connected-applications"
          text="Connected apps"
        />
      </li>
    </ul>
  </div>
</body>
      at Object.getElementError (node_modules/@testing-library/dom/dist/config.js:37:19)
      at /home/runner/runner1/_work/vets-website/vets-website/node_modules/@testing-library/dom/dist/query-helpers.js:90:38
      at /home/runner/runner1/_work/vets-website/vets-website/node_modules/@testing-library/dom/dist/query-helpers.js:62:17
      at getByText (node_modules/@testing-library/dom/dist/query-helpers.js:111:19)
      at Context.<anonymous> (src/applications/personalization/profile/tests/components/edit/Edit.unit.spec.jsx:75:17)
      at Test.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:129:14)
```

#### Screenshots or Supporting Evidence
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/34250637/91c3a1be-0243-4b1a-8074-35ac93e5e19c)
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/34250637/41aec6d2-be79-4de2-9134-19fbb802df4d)
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/34250637/6fed4245-a903-4fd4-a131-3fe36a41f5d8)

#### Severity of the issue
- [ ] High severity
- [X] Medium severity
- [ ] Low severity

#### Visibility
- [ ] User visible
- [X] Stakeholder visible

## Tasks
- [ ] Locate where the inconsistent results of the test are stemming from.
- [ ] Adjust the test if necessary to test in a more reliable fashion.
- [ ] If the application code itself is producing inconsistent results, adjust the code to provide a more consistent outcome.

## Acceptance Criteria
- [ ] Unit tests should pass every run provided there is nothing broken in the code that is causing it to legitimately fail. 
- [ ] Test should be able to run in a loop at least 20x and not suffer any failures during that process.

**Comment by CBonade** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/25227

@adamwhitlock1 has a PR open here to address this test's flakiness

**Comment by CBonade** [comment]
This PR has been approved and merged. Closing this task.
