### ISSUE TITLE
Remove streamlined indicator from VBA FSRs

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#63658]
## Issue Description
The streamlined data field was also included with pure VBA FSR submissions and the DMC API was not configured to account for it. Remove the indicator and resubmit the affected submissions

---
## Tasks
- [x] Remove the indicator
- [ ] Develop script to resubmit the failed submissions

## Acceptance Criteria
- [ ] The broken and lost VBA submissions have been resolved
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
