### ISSUE TITLE
Create FsrForm class

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#63657]
## Issue Description
We would like to add models that represent our different pieces of data we fetch from external APIs and then transform to pass to the FE

---
## Tasks
- [x] Add a class to handle the FSR transformations that take place before we create FSR submissions.
- [x] Add attributes and types to debt

## Acceptance Criteria
- [x] We have a class in our module that represents the FSR Form
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
Per Sprint Planning on 10/23, @ScottyRJames and @kjsuarez to work on this ticket together.

cc; @Tom-Davis
