### ISSUE TITLE
Add FSR KPIs to Datadog dashboard

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#63653]
## Issue Description
Now that we have a Debt Resolution datadog dashboard in place we need to start porting over KPIs for services we own and this includes our FSR service.

---
## Tasks
- [ ] Add counts to FSR submissions
    - [ ] VHA
    - [ ] VBA
    - [ ] Combined
- [ ] Add external service counts and failure rates (DMC, VBS, SharePoint, VA Notify)
- [ ] Add controller latency graph

## Acceptance Criteria
- [ ] We can refer to Datadog dashboard regarding FSR metrics
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
