### ISSUE TITLE
Add DMC debt KPI tracking to datadog dashboard

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#63652]
## Issue Description
Now that we have a Debt Resolution datadog dashboard in place we need to start porting over KPIs for services we own and this includes our debts product. 

---
## Tasks
- [x] Add count stats for getting DMC debts
- [x] Add failure counts for DMC debts
- [x] Add controller latency for debts endpoints

## Acceptance Criteria
- [x] We can refer to datadog dashboard for debts KPIs
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
