### ISSUE TITLE
[discovery] Investigate how we can add alerts to slack via Datadog

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#63654]
## Issue Description
If something goes wrong with one of the services our team is responsible for we would like to promptly know. This includes things like high pct of error rates and high latency.

---
## Tasks
- [x] Investigate Datadog capabilities and how we can add conditional alerts to our alerting slack channel
- [x] Reach out to other teams that have implemented similar alerts for feedback
- [x] Determine what types of thresholds we want to setup warning/error alerts for
- [ ] Add a Datadog Anomaly Monitor for Submission failure logs: `@message_content:*Form5655Submission?failed*`

## Acceptance Criteria
- [x] We know how to continue regarding setting up alerts for our team
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
Per Sprint Planning on 10/23, @ScottyRJames and @kjsuarez to work on this ticket together.

cc: @Tom-Davis

**Comment by ScottyRJames** [comment]
We have discovered how to use the slack channel for monitor alerts and implemented this logic within this ticket

https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/67194
