### ISSUE TITLE
Update Platform Security PSIRR info on Platform Website

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#63661]
## User Story
As a Platform team member, I want to ensure VFS teams are presented with the correct information for the Privacy, Security, Infrastructure Readiness Review touchpoint so there is no confusion within or amongst teams.

Assignee: @allison0034 
Peer Reviewer: @it-harrison 

## Description
Platform Security recently updated their PSIRR template labels and assignees and need the link updated on the PSIRR page on Platform Website. We also need to update the Platform Security info on the Collaboration Cycle Contact Us page.

FYSA Platform Security opened [this ticket ](https://github.com/department-of-veterans-affairs/platform-security/issues/324)to get the link changed.

New gh link :https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/new?assignees=kaipyroami&labels=security-review%2Cplatform-security%2Cplatform-security-review&projects=&template=privacy-and-security-review.md&title=Readiness+Review+%5BTeam-Name%2C+Feature-Name%5D

## Impacted Artifacts
[Privacy, security, infrastructure readiness review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/privacy-security-infrastructure-readiness-review) touchpoint page
[Contact us ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/contact-us#Contactus-PlatformSecurity)page

## Tasks
- [x] Replace the gh template link on the PSIRR touchpoint page with the link shared above
- [x] Replace "Alyssa Gallion" with "Jesse House" under Platform Security
- [x] Delete Platform Security Engineers line (only include Product Manager)
- [x] Note: when changes are published, comment on [this ticket ](https://github.com/department-of-veterans-affairs/platform-security/issues/324) notifying Jesse that the link has been updated per ticket #63661 and his ticket can be closed

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The correct Platform Security team members are assigned the PSIRR ticket when opened by VFS team members
- [x] The Platform Security Product Manager is listed correctly on the Contact Us page

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@jhouse-solvd can you confirm if this is the correct template link? https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/new?assignees=kaipyroami&labels=security-review%2Cplatform-security%2Cplatform-security-review&projects=&template=privacy-and-security-review.md&title=Readiness+Review+%5BTeam-Name%2C+Feature-Name%5D

**Comment by allison0034** [comment]
@it-harrison this is ready for peer review. Once you review I will let Jesse know.

**Comment by it-harrison** [comment]
@allison0034 everything looks good!

**Comment by allison0034** [comment]
@jhouse-solvd the link has been updated per ticket #63661 and you can close your ticket.

**Comment by jhouse-solvd** [comment]
@allison0034 - Thank you so much! I really appreciate your help. I'll take a look and close out our ticket soon.
