### ISSUE TITLE
Tracking application errors with Sentry deprecated github link

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#63687]
## Info
[Tracking application errors with Sentry](https://depo-platform-documentation.scrollhelp.site/developer-docs/tracking-application-errors-with-sentry) page has a link "Platform user management process" that goes to a  [deprecated Github link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/vsp_user_managment_process.md).

## Tasks

- [x] Look on Platform website to see if there's an equivalent to this document
- [x] If not, reach out to someone that may know if this document is still relevant, as it has not been maintained since 2020. / Inquiring via Slack thread: https://dsva.slack.com/archives/CBU0KDSB1/p1692193022380859
- [x] Reach out to Jason regarding: User Management Approach for VSP

**_Waiting on more information from Jason Woodman; told him Eric Boehs and Lindsey Hattamer could not provide any insight via Slack support chat_**

- [x] Make any content updates as needed.

## Acceptance Criteria

- [x] We will have more insight from a subject matter expert on how to move forward with the content on this outdated GitHub page: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/vsp_user_managment_process.md
- [x] We will have updated the "[Tracking application errors with Sentry](https://depo-platform-documentation.scrollhelp.site/developer-docs/tracking-application-errors-with-sentry)" page so that it no longer points to to the outdated github page listed above from step #1.

**Comment by vbellissimo** [comment]
Waiting on response from Eric Boehs and/or support team.

**Comment by vbellissimo** [comment]
Waiting on response from private DM with Jason Woodman; Follow up with Jason if still no response.

**Comment by jknipes** [comment]
@jwoodman5 would you be able to work with Content Team on this issue in the upcoming sprint beginning 5/9?

**Comment by jwoodman5** [comment]
@jknipes Yes, I will work with you on this in the upcoming sprint.

**Comment by jwoodman5** [comment]
I am working to identify a Sentry SME to get us the answers we need.

**Comment by CherylEvans** [comment]
Thank you, Jason! I appreciate your update!

Cheryl

Cheryl Evans | Consultant



The So Company <http://thesocompany.com/>

We make the government better.

Timezone: CST | GMT - 6

***@***.***

SDVOSB | SBA 8(a) Certified | Digital Services Coalition Founding Member

**Comment by jwoodman5** [comment]
Realizing after diving in, it is actually a GH process link. Tracking it down, regardless.

**Comment by CherylEvans** [comment]
@jwoodman5 Thank you for the update, Jason. What can I assist with, if anything at this time?

**Comment by jwoodman5** [comment]
Hey @CherylEvans - At this point, there isn't anything for you to do. I should have an answer on the relevance (or lack of) of this doc tomorrow morning. If sunsetting or leaving as is (unlikely) makes the most sense, I'll coordinate with you. If updates are needed, I'll coordinate with a SME.

**Comment by jwoodman5** [comment]
@CherylEvans Okay, I shared this doc and talked with the owner of the current GH user management process and this doc can be sunset. Do you need anything else from me to make that happen? 

cc: @jknipes

**Comment by jknipes** [comment]
@jwoodman5 just to confirm, we need to sunset the GitHub document, but **keep** the rest of the Platform Website page, is this correct?

If we are keeping the PW page, is there any guidance on what will replace the GitHub link?

**Comment by jwoodman5** [comment]
@jknipes @CherylEvans We can remove the link and change the wording to something like this, since it already gives an example naming structure. 

'Create a new team based on the following naming and structuring: vfs-[team name here]. If permissions need to be adjusted, [ask for help from the Platform in Slack](https://vfs.atlassian.net/wiki/spaces/SUP/pages/1439138197).'

**Comment by CherylEvans** [comment]
@jwoodman5 @jknipes Edit made to Tracking application errors with Sentry. 'Create a new team based on the following naming and structuring: vfs-[team name here]. If permissions need to be adjusted, go to [Getting Help from the Platform in Slack](https://depo-platform-documentation.scrollhelp.site/support/getting-help-from-the-platform-in-slack).'

**Comment by CherylEvans** [comment]
@jwoodman5 @jknipes Changes to the Platform Website page, [Tracking application errors with Sentry](https://depo-platform-documentation.scrollhelp.site/developer-docs/tracking-application-errors-with-sentry), were updated with today's SVP deployment.

**Comment by jwoodman5** [comment]
Thanks, @CherylEvans
