### ISSUE TITLE
Update Platform Orientation for Slack profile page

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#63686]
## User Story
As a VFS team member, I want to ensure other DSVA Slack team members know who I am and what team I support so that support can be executed seamlessly via Slack.

Assignee: @erinrwhite 
Peer Reviewer: @CherylEvans 

## Description
There is a new [Slack profile ](https://depo-platform-documentation.scrollhelp.site/getting-started/slack-profile)page on Platform Website that replaces the former Slack profile guidance that was included in the Request Access to Tools page. We need to update Platform Orientation docs to ensure that VFS teams are directed to the proper guidance.

## Impacted Artifacts
- [x] [New VFS Team Member template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/orientation-epic.md)
- [x] Automated Slackbot message managed by @naomimarcussen - appears to be new, using new address already 👍🏻  
![Screenshot 2023-08-16 at 4 56 03 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/6ff93f07-9f1d-4270-b808-eaa109a0a5b2)
- [x] [OCTO DE onboarding template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/octo-de-crew-onboarding.yml)

## Tasks
- [x] Update the embedded link for updating Slack profile to the new page in the New VFS Team Member template, OCTO DE onboarding template, and Slackbot message (if applicable)

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS Team members are directed to the appropriate Slack profile guidance on Platform Website.

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
[Pull request](https://github.com/department-of-veterans-affairs/va.gov-team/pull/63796) for New VFS team member template sent to @CherylEvans ! Hunting for other potentially impacted artifacts.

**Comment by erinrwhite** [comment]
@shiragoodman I'm also seeing a link from the [OCTO-DE onboarding template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/83f74397264004847b879164314ef7d3e1f5f84b/.github/ISSUE_TEMPLATE/octo-de-crew-onboarding.yml#L88) which we do not manage. Okay to submit a PR to them?

**Comment by CherylEvans** [comment]
@erinrwhite I reviewed [PR 63796](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63796) and made 1 comment for a change.  Other than that, it looks great. :-)

**Comment by shiragoodman** [comment]
good catch @erinrwhite ! You can submit a pull request for the OCTO-DE template. Looks like @mchelen had been maintaining that template perfidiously, but he's no longer supporting Platform. When you create the PR, assign it to @humancompanion-usds for approval. He can reassign to someone else if needed. (This isn't really our template to manage, which is why the PR is a good call)

**Comment by erinrwhite** [comment]
Thanks @shiragoodman and @humancompanion-usds! Submitted PR #63862 and updated the issue to reflect the new artifact

**Comment by erinrwhite** [comment]
Belated note that I squashed and merged #63796 for New VFS team member template yesterday.

**Comment by CherylEvans** [comment]
@erinrwhite Everything looks great, nice job! :-)

**Comment by erinrwhite** [comment]
@CherylEvans  Awesome. Closing!
