### ISSUE TITLE
[BE] Fix Chip Endpoint Path in Service Library

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#63697]
## Description
Bug identified during test harness setup. Currently, Get/Update Demographics confirmation endpoint interface in Chip service library not having valid path to call chip service.  Modify service interface to include `base_path` in `path` parameter.

## Tasks
- [ ] [BE] **Include base_path in demographics endpoint path parameter**
- [ ] [BE] **rspec**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
