### ISSUE TITLE
Epic | Profile | Alert Consistency 

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#63699]
## Background

We've run an audit of our alerts: 
```[tasklist]
### Origin/Discovery
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/48566
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/64145
```

Using the output of that we need to update our myriad of alerts

### Artifacts: 
- [Pam's Alert Audit Spreadsheet ](https://docs.google.com/spreadsheets/d/1c07vM_RSrCdCBMfyYY8JY33mXM4ZVRT_WCBVv5vqazs/edit#gid=1546631889)

## Items to Review 
- [three different alerts](https://dsva.slack.com/archives/C909ZG2BB/p1692748819412009), one is in the contact center guide the others are not 

## Tasks
Breaking down the tasks for alert updates per section of the profile 

```[tasklist]
### Personal Information
- [ ] add issues
``` 

```[tasklist]
### Direct Deposit
- [ ] #64109
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/64307
```

```[tasklist]
### Contact Information
- [ ] add issues
``` 

```[tasklist]
### Military Information 
- [ ] add issues
``` 

```[tasklist]
### Connected Apps
- [ ] add issues
``` 
```[tasklist]
### Editing as a subtask
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65452
```
