### ISSUE TITLE
Resolve bug with E2E Allow List merge blocking check when Update E2E Allow List isn't run

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#63694]
## Issue Description
The E2E Allow list merge block check expects the allow list to be fetched by the step "Update E2E Allow List". However, if the stress test does not run, that step will not run, leaving the merge blocking check without an allow list. We need to either fetch it in the merge block check, or make it conditional to get it from an earlier check if the stress test does not run and use that one instead.

---
## Tasks
- [x] Determine where the Allow List needs to be pulled from for the Merge Block check.
- [x] Implement either a conditional check for the source of the allow list, or move the fetch to this step.

## Acceptance Criteria
- [x] The E2E Merge Block check now runs even if the stress test does not run.

**Comment by CBonade** [comment]
This bug has been resolved and this is now working correctly.
