### ISSUE TITLE
Update Confirmation page for SW paths

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#63698]
## Issue Description
Update Confirmation page to match mockup will appear for both Streamlined Waiver user paths.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcUlIIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d2c90317250d07c299b93de5d5fbe7e929c8399f/streamlined-waiver-confirmation-page.jpg)

---
## Tasks
- [ ] Green info section is added with updated copy
- [ ] Updated text below green info section is added
- [ ] [Download link](https://design.va.gov/patterns/help-users-to/keep-a-record-of-submitted-information) is added

## Acceptance Criteria
- [ ] _Updates have been made that match mockup attached_

**Comment by HeatherRienks** [comment]
@OptionSelect - is this something you are able to assist with?

cc: @josephrlee

**Comment by OptionSelect** [comment]
Current local as well even though code exists. Very interesting. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbDRNIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--632b1e3786949013bdf7c1b4c0a0ac2deff778f2/image.png)
