### ISSUE TITLE
Deploy PE Stack to New Infra Distro Cluster

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#63703]
As a proof of concept, a platform stack (Vets API/Website/Content Build) should be built and deployed to EKS. This may be easier done by leveraging Infrastructure's work on ephemeral EKS clusters.

## Acceptance Criteria

An ephemeral platform stack can be manually deployed by a member of our team. The stack will be accessible via SOCKS and can communicate internally (e.g. Vets Website can access Vets API).

```[tasklist]
## Tasks
- [ ] Benchmark existing Review Instances' build times (create a PR, time it)
- [ ] Parameterize host value within Content Build (e.g. localhost:3002 -> ENV var)
- [ ] Define more tasks here
```
