### ISSUE TITLE
[CONTENT] Research and write COATESVILLE, PA System Health Services and Program Intro Suicide Prevention-Women's) [CONTENT]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#6370]
## User Story or Problem Statement
As a Veteran Web user, I need a System description of services provided at VAMC, so I can understand and best chose the services and service location for my needs.

## Goal
_Efficient and clear content describing local Health Service provided_
_Efficient plain language for Health Services and Health Service Program Intro_

## Objectives or Key Results this is meant to further
- _Reduced word count and improved plain language._

## Resources - Tools - Documentation
[Coatesville Health Services Content Playbook](https://drive.google.com/drive/folders/1fu1q9yV1HiCEIq_1emfLk0XmanZZ1ep1)
[Coatesville Health Services:A-Z](https://www.coatesville..va.gov/services/index.asp)
[Pittsburgh Caregiver support Service Program Link](https://www.va.gov/pittsburgh-health-care/caregiver-support/)

## Tasks
_Tasks that must be complete using content playbook criteria for the following Health Services, and Health Service Program Intro:_
- [ ] Suicide Prevention (Health Services) 
- [ ] Suicide Prevention (Health Program) 
- [ ] Telehealth
- [ ] Urgent Care
- [ ] Urology
- [ ] Vocational rehabilitation and e
- [ ] Women's health (Health Service)
- [ ] Women's Health (Health Program)

## Acceptance Criteria
_Items that must be written and documented in Content Approval Folder under the correct VAMC System folder (i.e. Altoona, Butler)_
* Suicide Prevention (Health Services) 
* Suicide Prevention (Health Program) 
* Telehealth
* Urgent Care
* Urology
* Vocational rehabilitation and e
* Women's health (Health Service)
* Women's Health (Health Program)
