### ISSUE TITLE
BE | Profile | Direct Deposit | Invalid Night Area Code Error Handling

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#63717]
## Background
Lighthouse returns the following error when making direct deposit update requests:
```
No changes were made. Request was sent to Benefits Gateway Service (BGS), 
but BGS update failed. 

Unknown issue(s). Raw response from BGS: 'Update Failed: Night area number is invalid, 
must be 3 digits'
```

## Tasks
- [ ] Update error parsing code.
- [ ] Write spec to test parsing.

## Acceptance Criteria
- [ ] Unit tested
- [ ] Test in staging

**Comment by tpharrison** [comment]
[Reached out to Lighthouse team in Slack](https://dsva.slack.com/archives/C03P6C3FYMR/p1693928051707899).
