### ISSUE TITLE
Research: Determine what is on BRD

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#63718]
## Description
We need to identify and analyze all the services that are currently residing on the old BRD infrastructure that have not yet been transitioned to our newer EKS infrastructure. This analysis will allow us to plan and prioritize the migration process and ensure a seamless transition for each service.

## Tasks
- [x] Inventory Current Services on BRD: List all services currently hosted on the BRD infrastructure.
Determine Migration Status: For each service, determine its current migration status (e.g., not started, in progress, or completed).
- [ ] Identify Dependencies: Highlight any services that have dependencies or are interlinked which might impact the order of migration.
- [x] Estimate Migration Complexity: For each service, provide an estimation of migration complexity based on factors like data size, service interdependencies, and customization.
- [x] Document Service Owners/Stakeholders: Identify and document the point of contact or owner for each service. This will be crucial for coordination during the migration process.
- [x] Share findings w/ leadership

## Acceptance Criteria
- [x] Comprehensive BRD service list has been created
- [x] Migration status, owners and dependencies have been identified wherever possible
- [x] Complexity of migration has been estimated
- [x] Findings are documented and have been shared with leadership appropriately for guidance/prioritization

**Comment by pjhill** [comment]
Compiling list of potentially BRD processes and components [here](https://vfs.atlassian.net/wiki/spaces/TT4/pages/2739077428/BRD+Research).

**Comment by pjhill** [comment]
Going through the list of assembled BRD items and making an initial assessment [here](https://vfs.atlassian.net/wiki/spaces/TT4/pages/2742288562/Likely+Need+Addressing).  Some items may require additional research.

**Comment by jhouse-solvd** [comment]
@JoeTice @pjhill - This relates to a [POAM for end-of-life (EOL) Amazon Linux Images (AMIs)](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/740) running on the Platform. I've added this issue to that epic for tracking. 

Please let me know if I can provide any more information. 

cc: @kenmayo

**Comment by pjhill** [comment]
Hey @jhouse-solvd -- in the opinion of our security colleagues, should we be stepping through an AL1 --> AL2 phase prior to attempting to move processes out of Jenkins / the BRD paradigm?

**Comment by jhouse-solvd** [comment]
@pjhill - I don't think the expectation is to upgrade machines in BRD before moving them to another paradigm. But rather to upgrade base images while moving them. Does that answer your question?

**Comment by pjhill** [comment]
Ok, gotcha, I think that makes sense!

**Comment by pjhill** [comment]
Reviewed the findings with TLs and Engineering leadership this morning. Noted some additional feedback from that group in the Confluence documents. I also created a [filtered down list](https://vfs.atlassian.net/wiki/spaces/TT4/pages/2749530136/Filtered+List) of items that excludes --
* Pipelines that haven't been executed in the past month
* Pipelines that belong to VFS teams
* Pipelines that belong to CMS

**Comment by pjhill** [comment]
Suggested 3 possibilities for getting started with moving pipelines out of Jenkins -- [here](https://vfs.atlassian.net/wiki/spaces/PRT/pages/2750677044/Recommended+Starting+BRD+Projects)
