### ISSUE TITLE
Forms Dashboard Cards - View Redirect

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#63716]
## Issue Description

In order to be able to more easily add/remove data from Domo datasets we need to create a view of the BQ source data and re-direct all the cards on the dashboard to the new view.  

---
## Tasks
- [ ] Create a WIP - Forms Dashboard (I do not want to mess with the original until we have completed and know it all words as expected)
- [ ] Replicate the cards on the current dashboard on the WIP but use the view data 

## Acceptance Criteria
- [x] All cards have been updated to data view
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelle-dooley** [comment]
@ChristineYoungZA - I'm going to do some work on this first, will let you know when I am ready for you.
