### ISSUE TITLE
[CAIA A11y Audit]: VRE CH31 Maintenance Audit

### ISSUE THREAD

**Issue by ohgreatkate** [department-of-veterans-affairs/va.gov-team#63726]
### Definition of done

1. Review and acknowledge all issues added to this maintenance audit.
2. Fix and/or document decisions made for all issues.
3. A11y specialist will review documented decisions or validating fixes for all tickets.
4. A11y specialist will update the product page on the VA a11y dashboard.
5. A11y specialist will close this ticket.

### Auditor(s)

@ohgreatkate
@SarahKay8 
@coforma-jamie 

### Automated

- [X] Run axe checks on every page or unique state (required)
- [X] Run WAVE on every page if time allows. WAVE is more visual than axe or axe-coconut, but offers some excellent ways to identify nested headings and HTML5 landmark tags.

### Manual

- [X] Color contrast checks (recommend using whocanuse.com for beyond compliance reports)
- [X] Color blindness checks
- [X] Zoom layouts to 400% and inspect them for readability. If layouts break at 400%, I will start reducing them until they become stable, and log the zoom ratio when things started breaking.
- [X] Keyboard navigation

### Screen Reader

- [x] Windows, Chrome, JAWS
- [X] iPhone, iOS Safari, VoiceOver

### Audit sheet link

[VRE CH 31 Audit Sheet](https://docs.google.com/spreadsheets/d/14yXI27kSr5w395e8GJDVi5n81q4cU_eXKvd8eK8IEb4/edit?usp=sharing)

### Staging or Production Link

[Staging Link](https://staging.va.gov/careers-employment/vocational-rehabilitation/apply-vre-form-28-1900/start)

### Prototype Link

[Mural User Flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684161597392/5c1f8869cf5d03b792c8b82cf19b39dc26c486c2?sender=u0e8ac1d6d7681bb7e1b80558)

### Test Users

vets.gov.user+24@gmail.com
[staging test user repository](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)
```[tasklist]
### Audit Tasks
- [x] VRE CH31: Color & contrast
- [x] VRE CH31: Cognitive design burden
- [x] VRE CH31: Heading levels
- [x] VRE CH31: Plain language review
- [x] VRE CH31: Content & rezoom
- [x] VRE CH31: Keyboard navigation
- [x] VRE CH31: Axe scans
- [x] VRE CH31: iOS, Safari, VoiceOver
- [x] VRE CH31: Windows, JAWS
```

```[tasklist]
### Related Defect Ticket
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/64038
```

**Comment by ohgreatkate** [comment]
> ## CAIA Updates
> * Adding to epic 61722 for connectivity to that request
> * We will need to take a looksie and see what connectivity this ticket  63726 has to 61718

63726 (this ticket) is the maintenance audit ticket created based off the 61718 intake request ticket.

**Comment by sara-amanda** [comment]
> 63726 (this ticket) is the maintenance audit ticket created based off the 61718 intake request ticket.
- [61718](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61718) is closed. 
- This appears to be a completed maintenance audit by Kate, @coforma-jamie and @SarahKay8 

@coforma-terry , Jamie or Sk - _ok to close?_

**Comment by coforma-jamie** [comment]
@sara-amanda this has been done for awhile, ok to close as far as I'm concerned

**Comment by sara-amanda** [comment]
@coforma-jamie Closing if you would like to log this on the capacity tracker, if you have not already. Thanks so much!
