### ISSUE TITLE
[SW - PI4/23] Accessibility study [planning] 

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#63722]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

The UX team is planning to run a dedicated accessibility study to understand the usability of the streamlined waiver experience by Veterans that use screen readers. The planning will happen in Sprint 107, and the study will begin in Sprint 108. The UX team will work with an accessibility specialist at VA.gov to help refine the conversation guide with AT-friendly language. The goal is to run the study with 5 participants that use AT. 

---
## Tasks
_What work is necessary for this story to be completed?_

[STEP 1 of 3](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/65357)
- [x]  UX team partners and collaborates with an accessibility specialist to receive guidance on how to develop the conversation guide and become AT-informed for the interview, as well as for a pilot session
- [x]  UXR team does secondary research on screen reader usability testing

[STEP 2 of 3](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/65359)
- [x] UX Research conducts a screen reader accessibility audit of Streamlined Waiver
- [x] UX Research adapts research plan 
- [x] UX Research adapts conversation guide
- [x] UX Research posts materials on Github
- [x] UX Research obtains platform collaboration research cycle approval (2-3 days)
- [x] UX Research writes AT specific recruitment screener
- [x] Note taking spreadsheet and Mural created

[STEP 3 of 3](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/65362)
- [x] Host a pilot session
- [x] Coordinate with Perigean (1 week)
- [x] UX Research coordinates with an accessibility specialist who can be present at each study interview

## Acceptance Criteria
 _What will be created or happen as a result of this story?_
- [x] Secondary research Mural and/or document
- [x] Accessibility study research plan
- [x] Accessibility study conversation guide
- [x] Note taking spreadsheet and Mural created
- [x] Pilot session has taken place
- [x] Research participants confirmed
---

**Comment by HeatherRienks** [comment]
Add into Sprint 107

**Comment by charlottecesana** [comment]
Update 9/6/23: In progress

**Comment by Tom-Davis** [comment]
All work is complete for the planning stage - closing the Epic.
