### ISSUE TITLE
Research solution to flaky unit tests

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#63721]
## Description
Unit test failures have become a common issue in the CI/CD Pipeline, and our understanding is that many of these tests may be flaky based on the behaviors we're observing. Some previous discussion has been done on an approach to this in the past, but since some things have moved and since a number of our team members have shifted, we should reassess the planned approach to determine if that is still the right course of action.

## Tasks
- [x] Determine if the stress test/allow list approach is still the best option
- [x] Research the implementation of this approach to determine what would be best
- [ ] Update implementation tickets to reflect the path forward

## Tasks
- [x] Have defined a path forward
- [ ] All tickets are updated to reflect implementation approach

**Comment by CBonade** [comment]
Some notes from our discussion after standup today:

Two options...

Option A: Implement the same system we have now
Option B: Leverage the `.skip` functionality built into Mocha

A concern was raised around how code coverage would be impacted and if that was different for these two methods. Essentially, the verdict, prior to testing, was that these behaviors should result in the same code coverage result. If a test is skipped via option B, that code they're testing is not covered and should result in a lower coverage. In Option A, it would be the same effect as if the test was never written (or was deleted), which would also result in the same lower coverage number.

Option A carries the benefit of allowing us to retain control of what tests are skipped and which aren't. In Option B, if a skip is added to a test spec directly, it can be removed by any user that decides they want their test to run again. This could easily result in flaky tests getting worked back into a deployment, causing a failure to deploy and evolving into a support situation. Even with the caveat that it would be re-disabled that night, it would increase the difficulty of tracking accurately how long a test has been disabled for.

One benefit of Option B that had been discussed was that the skipped tests would be accurately reported on Mocha reporting. However, upon further discussion it was raised that there are many other uses of the skip function that would be used as part of normal development. Adding our skipped tests into the mix would arguably muck up that number as the skipped tests are mixed with tests deliberately skipped by developers for many reasons. Going with Option A would allow us to keep these concerns tracked separately, and we can easily dashboard these numbers with low effort to get reporting as necessary.

Option A allows us to leverage a lot of systems we have in place already including publishing mechanisms to Confluence that are built around pulling data from BigQuery, Domo dashboarding that's based on BigQuery, and existing processes tied into the testing results generation processes.

I believe, at least at the time of writing, that option A will be the better way to go for this feature. As a "Part 2" of this ticket i'll be tearing apart the unit test scripts to see what extra steps may need to be taken to implement this.

**Comment by CBonade** [comment]
Excluding unit tests seems to be possible following the following process:

1) Fetch allow list
2) Figure out which tests are disabled
3) create a regex for those file names
4) create a glob of tests that are eligible based on matching unit spec file name
5) using grep and a regex of the invalid tests, with --invert appended on the end, will prevent those from being run.
