### ISSUE TITLE
Modify and make updates to Domo card 3

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#63759]
## User Story
As an OCTO team member, I want to see the count of issues that are violated most frequently but with data boundaries so that I can make sense of the data opposed to seeing everything at once.

As an OCTO team member, I want to see the count of issues that are violated most frequently but with an option to toggle by launch-blocking or non-launch-blocking so that I can 

Assignee: @allison0034 
Peer Reviewer: @it-harrison 

## Description
Current card # 3 communicates the count of experience standard violations over all time. The purpose of this card is to add a date filter (consistent with cards 1 and 2 - quarterly) and to add an option to toggle by launch-blocking issues, non-launch-blocking issues or all issues. 

Note: this card has drill down options. Please ensure that those stay in place. We do not want to change those.

## Impacted Artifacts
[Collab Cycle Domo Dashboard - Proposed Updates (Draft)](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686764117069/5e30ad39ba0126a133110af9e4d4864246634bf1?sender=a22c79f3-4c6c-4735-9b32-c5d8fc6923ac) mural

## Tasks
- [x] Modify card # 3 to add a date filter similar to card 1 and 2. Should be a 3 month, or quarter, interval.
- [x] Add option to toggle on launch-blocking, non-launch-blocking or all.
- [x] Set default view to last completed quarter and all issues.

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] The dashboard has a card for most Exp Std violations that is filterable by launch-blocking or non-launch-blocking, and is able to be viewed on quarterly intervals.
 
 
### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
Working with Ian to get the correct data flow.

**Comment by allison0034** [comment]
Ian worked on the data flow but we are having problems adding the filter. I have [reached out to the Analytics team](https://dsva.slack.com/archives/CBU0KDSB1/p1700227948236719).

**Comment by allison0034** [comment]
Ian needs to add a date option so this needs to move into the next sprint.

**Comment by it-harrison** [comment]
@allison0034 I have added a filter in details view to show the quarters: https://va-gov.domo.com/page/1340527018/kpis/details/1670417616

**Comment by allison0034** [comment]
@it-harrison  that works! Can you update the legend? Also can you peak at the numbers and I make I have the data right?

**Comment by it-harrison** [comment]
@allison0034 card updated, numbers look good!
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzRhQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f9e8310dc13c2b11e21b2e4cbea9244fd175136/Screenshot%202023-11-29%20at%2012.45.50%20PM.png)

**Comment by it-harrison** [comment]
@allison0034 looks good - one question, should we mention in the card heading that the user can filter by quarter by entering "details" view?
