### ISSUE TITLE
Add highlights section and change dashboard name

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#63756]
## User Story
As a Governance team member, I want to change the name of the Collaboration Cycle Dashboard so that it is more reflective of the data being displayed.

As a Governance team member, I want to add a highlights section to the dashboard so that current quarter data can be immediately visible and easy to intake within the dashboard.

Assignee: @allison0034 
Peer Reviewer: @it-harrison 

## Description
The purpose of this ticket is to change the name of the  Collaboration Cycle dashboard as it is misleading since it is only Staging Review data, not all of Collaboration Cycle.

The secondary purpose of this ticket is to add a highlights section so that OCTO, Platform and VFS team members can see top level data for the quarter at a glance. Per our [research findings](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2704081311/2023-05+Collaboration+Cycle+Domo+Dashboard+Survey+Research+Findings), OCTO-DE wants to "quickly analyze" and they "want easily digestible information."

## Impacted Artifacts
[Collab Cycle Domo Dashboard - Proposed Updates (Draft)](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686764117069/5e30ad39ba0126a133110af9e4d4864246634bf1?sender=a22c79f3-4c6c-4735-9b32-c5d8fc6923ac) mural

## Tasks
- [x] Rename the dashboard to "Staging Review Dashboard"
- [x] Add the Highlights section per the mural design
- [x] Include Averages per Staging Review touchpoint
- [x] Add % total issues that are launch-blocking
- [x] Add How many staging reviews have taken place

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The dashboard name has been changes to Staging Review Dashboard
- [x] The highlights section has been added to the dashboard and included 3 different metrics

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@allison0034 how is this going? Could you please share a status update?

**Comment by allison0034** [comment]
I have been working with Ian for the last few days trying to learn Domo and create the correct data sets. We are also waiting on analytics to clean up some things. I have added a few cards to the dashboard trying to display the correct thing.

**Comment by allison0034** [comment]
I worked with Ian again this morning on some of the data sets. Some of these will have to be written in SQL so Iam is helping with that. Also, some of the data still seems to be incorrect to Ian is looking into that. Poor Ian : (

**Comment by allison0034** [comment]
This will be continuing to the next sprint, me being new to Domo, some data issues and some more complex math than we realized.

**Comment by allison0034** [comment]
@it-harrison I think I figured out what gauges I need to display the things we want for the highlights section. i spoke to Sara and she was basing the Mural designs off guessing and looking at what other people did. My problem now is I am not sure what you have for data is correct. Can you go in to Domo and edit these cards to make sure i have the right data hooked up?
[Uploading... Screen Shot 2023-10-02 at 11.46.47 AM.png]

**Comment by allison0034** [comment]
Moving along good now. Working with Ian to get the last data in the right spot for the averages.

**Comment by allison0034** [comment]
Update Shira and Matt on changes in [Slack convo](https://dsva.slack.com/archives/GNF5GSD9N/p1696949652574059).
