### ISSUE TITLE
Create Domo card 2

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#63758]
## User Story
As an OCTO team member, I want to see how long it takes VFS teams to resolve launch blocking issues so that I can see how long it takes VFS teams to address launch-blocking issues.

Assignee: @allison0034 
Peer Reviewer: @it-harrison 

## Description
The current card # 1 communicates how long it takes to resolve staging review issue tickets (including launch-blocking). While modified card # 1 will communicate how long it takes teams to resolve non launch-blocking issues, new card # 2 will communicate how long it takes teams to resolve launch-blocking issues. Similar to card # 1, the card will default to display data from the last completed quarter, however anyone viewing the dashboard should have the option to toggle to different quarters.

Note: the data displayed in this card should be tickets that were closed in the applicable quarter.

## Impacted Artifacts
[Collab Cycle Domo Dashboard - Proposed Updates (Draft)](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686764117069/5e30ad39ba0126a133110af9e4d4864246634bf1?sender=a22c79f3-4c6c-4735-9b32-c5d8fc6923ac) mural

## Tasks
- [x] Copy card # 1 and edit it to include launch-blocking issues ONLY
- [x] Edit the card to include a date filter
- [x] Set the date filter to 3 month intervals 
   - Example: July 1 - September 30, 2023 or 07/01/2023-09/30/2023 or FY2023Q4 or CY2023Q3
- [x] Set the date to default to the most recent completed quarter
- [x] Based on data, decide on an appropriate "time to close issue." In card # 1, the scale is 1 month or less, 1-2 months, 3-6 months and 6+ months, however since this is launch-blocking issues it will likely be a much smaller scale - think days and/or weeks

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] The dashboard has a card for time to close launch-blocking issues on a quarterly basis

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
Working with Ian to get the data flows for launch-blocking issues.

**Comment by allison0034** [comment]
Duplicated cards but having a bit of an issues syncing the data set.

**Comment by allison0034** [comment]
Data sets are linked now, we are adjusting the time frames

**Comment by allison0034** [comment]
Matt and Shira [approved](https://dsva.slack.com/archives/GNF5GSD9N/p1698866699560779) the new time frame.

**Comment by allison0034** [comment]
@it-harrison this is ready for your review

**Comment by it-harrison** [comment]
@allison0034 looks good!
