### ISSUE TITLE
Modify and make updates to Domo card 1

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#63757]
## User Story
As an OCTO team member, I want to see how long it takes VFS teams to resolve non-launch blocking issues so that I can see trends over time as new processes/policies are introduced.

Assignee: @allison0034 
Peer Reviewer: @it-harrison 

## Description
The current card # 1 communicates how long it takes to resolve staging review issue tickets (including launch-blocking). Modified card # 1 will only communicate how long it takes teams to resolve non launch-blocking issues. The card will default to display data from the last completed quarter, however anyone viewing the dashboard should have the option to toggle to different quarters.

Note: the data displayed in this card should be tickets that were closed in the applicable quarter.

## Impacted Artifacts
[Collab Cycle Domo Dashboard - Proposed Updates (Draft)](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686764117069/5e30ad39ba0126a133110af9e4d4864246634bf1?sender=a22c79f3-4c6c-4735-9b32-c5d8fc6923ac) mural

## Tasks
- [x] Edit the existing card to remove launch-blocking issues
- [x] Edit the card to include a date filter
- [x] Set the date filter to 3 month intervals 
   - Example: July 1 - September 30, 2023 or 07/01/2023-09/30/2023 or FY2023Q4 or CY2023Q3
- [x] Set the date to default to the most recent completed quarter
- [x] Determine if the "time to close issue" scale is still valid. Current scale is 1 month or less, 1-2 months, 3-6 months and 6+ months.  Be sure to look at data going back to July 2021.

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] The dashboard has a card for time to close non-launch-blocking issues on a quarterly basis

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
This will be continuing to the next sprint, me being new to Domo, some data issues and some more complex math than we realized.

**Comment by allison0034** [comment]
Changed the card title and talking to Ian about the data I need.

**Comment by allison0034** [comment]
This will move into the next sprint while Ian and I work out the data flows needed.

**Comment by allison0034** [comment]
Met with Ian this morning and he is working on the new data flow needed.

**Comment by allison0034** [comment]
Ian provided a data flow, now we are fine tuning it to make sure it is what we need.

**Comment by allison0034** [comment]
Asked Matt and Shira to look at the [new card](https://dsva.slack.com/archives/GNF5GSD9N/p1697736599059419).

**Comment by allison0034** [comment]
Shira and Matt have approved the new data and charts.
