### ISSUE TITLE
[FE] Onsite Notifications: Remove unread messages alert in My VA health section

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#63753]
## Background
In support of conducting a test around a dot indicator on My VA we need to make some changes to the health care section on My VA:

1. remove the "unread messages alert" ("you have n unread messaged")
2. remove conditional logic around "send a secure message" link so that it's ever present
3. change link text to "Visit your inbox" (pending content approval)

## Tasks
- [x] remove the warning alert for unread messages and logic behind that
- [x] make secondary link always display, for all LOA3 users 
- [x] update secondary link with new copy (pending content approval)
- [x] update unit and e2e tests
- [ ] tag dev and PM for validation

## Acceptance Criteria
- [ ] Unread messages alert no longer appears on My VA 
- [ ] Send a secure message (or "Visit your inbox") link appears for all LOA3 users at all times on My VA

**Comment by allisonlu** [comment]
@ajakabcin 

Ready for validation! I can confirm that I see updated copy for Cecil Morgan

**Comment by ajakabcin** [comment]
Looks amazing thank you @allisonlu !
