### ISSUE TITLE
[Design] Onsite Notifications: Finalize experiment design details

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#63751]
## Background
In support of conducting a test around the dot indicator on My VA we need to finalize the design(s) of what we'll be testing. Angela will partner with the MHV designer on this.

## Tasks
- [x] Finalize design(s) for the test
- [x] Determine a11y needs for indicator - specifically screen reader text associated with it
- [x] Meet with a11y as needed for indicator
- [x] Discuss the new verbiage for the inbox link with content 
- [x] Determine placement of indicator

## Acceptance Criteria
- [ ] Finalized designs determined and shared with FE dev

**Comment by aagosto90** [comment]
[Link to design intent feedback convo](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63648)
