### ISSUE TITLE
[Design] Onsite Notifications: Documentation updates for dot indicator in My VA health section

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#63752]
## Background
In support of conducting a test around the dot indicator on My VA we need to make some changes to the health care section on My VA. We need to update our documentation to reflect the following changes:

1. remove the "unread messages alert" ("you have n unread messaged")
2. remove conditional logic around "send a secure message" link so that it's ever present
3. change link text to "Go to your inbox" (suggested by content in office hours)
4. implement aria label for inbox link when there are unread messages

## Tasks
- [x] Update FE documentation
- [x] Update sketch files accordingly
- [ ] ~Update use case documentation~

## Acceptance Criteria
- [x] Documentation is updated

**Comment by aagosto90** [comment]
[FE documentation for unread messages link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/health-care-FE-documentation.md#go-to-your-inbox-link)

**Comment by ajakabcin** [comment]
good call @aagosto90 ! I just created #64258 to cover use case documentation updates 👍
