### ISSUE TITLE
Incorporate the VANotify service into MCP notification worker

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#63766]
##### Datadog metrics make it clear that we cannot continue to rely on vet360 as a source of veteran email addresses. VA Notify provides a service that can, according to Kyle MacMillan, reliably source an email address from an ICN.
---
## Tasks
- [x] Replace `StatementIdentifierService` with a call to `VaNotify::Service`
- [x] Mourn the death of `StatementIdentifierService`

## Acceptance Criteria
- [x] StatsD metrics tracking notification success rate
- [x] MCP Notifications success rate is improved.
