### ISSUE TITLE
Create Domo card 5

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#63761]
## User Story
As an OCTO team member, I want to see the most common VA.gov Experience Standard findings per practice area on a quarterly timeframe so that I can view trends over time.

Assignee: @allison0034 
Peer Reviewer:  @it-harrison 

## Description
In the OCTO research that was completed, OCTO communicated that they'd like to see trends per practice area. In Card # 4 we communicate trends related to launch-blocking issues and practice area. This new card will communicate the top 3 VA.gov Experience standard findings for each practice are on a quarterly basis. The card should be for issues _opened_ in the quarter, not closed. 

## Impacted Artifacts
[Collab Cycle Domo Dashboard - Proposed Updates (Draft)](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686764117069/5e30ad39ba0126a133110af9e4d4864246634bf1?sender=a22c79f3-4c6c-4735-9b32-c5d8fc6923ac) mural

## Tasks
- [x] Create new card for the 3 most common issues per practice area
- [x] Set the date filter to 3 month intervals (similar to cards 1 2 and 3)
- [x] Set the date to default to the most recent completed quarter
- [x] Per Redefine practice area labels, update the legend and/or supporting data in Cards 4 and 5 in the SR Dashboard to link out to the change history post
- [ ] Question: do we just want to display the top issues or do we want to display the count of the top issues? If we do the count, we can make this a bar graph opposed to just an informational table

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The dashboard has a card for top 3 issues by practice area on a quarterly basis

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
@shiragoodman @it-harrison  Same question as the last domo card changes. If we are removing the practice area label from the new experience standards do we still want to track by practice area

**Comment by it-harrison** [comment]
@allison0034 as per Domo launch-blocking card ticket, I think this change makes sense as long as we provide a "substitute" like looking at the category instead of practice area

**Comment by shiragoodman** [comment]
@allison0034 @it-harrison same comment as Card 4... let me talk to Matt. I think both card 4 and 5 are not as high of a priority as the other cards, so let me see what Matt's opinions are on our pivot and I will follow up.

**Comment by allison0034** [comment]
@shiragoodman can we change "Set the date filter to 3 month intervals" to be quarters so we are consistent with the rest of the data?

**Comment by shiragoodman** [comment]
@allison0034 yes

**Comment by it-harrison** [comment]
this will carry over; work was paused due to a request from PO to focus on a [higher priority issue](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/va.gov-team/72286).

**Comment by shiragoodman** [comment]
Allison has been reassigned as assignee and Ian has been reassigned as peer reviewer.

**Comment by shiragoodman** [comment]
Allison has been reassigned as assignee and Ian has been reassigned as peer reviewer.

**Comment by it-harrison** [comment]
@allison0034 a draft of this card is here: https://va-gov.domo.com/page/1340527018/kpis/details/1368137964

**Comment by allison0034** [comment]
@it-harrison I added the card to the [dashboard](https://va-gov.domo.com/page/1340527018). Two things:

1. Can you capitalize Design and Content and make ia IA, also change a11y to Accessibility?
2. Can filter this by quarter, showing the most recent quarter first?

**Comment by it-harrison** [comment]
@allison0034 - changes have been made to dashboard

**Comment by allison0034** [comment]
Getting approval from Shira and Matt via [Slack](https://dsva.slack.com/archives/GNF5GSD9N/p1704724487857329).
