### ISSUE TITLE
Update poster image on How to check in page from Modernized Check In

### ISSUE THREAD

**Issue by kellysmith1008** [department-of-veterans-affairs/va.gov-team#63765]
## About your team

- Team name: Modernized Check In
-	Product manager: Lori Pusey
-	Designer: Zach Park
- Accessibility specialist:
- Content writer: Kelly Smith
-	Slack channel: check-in-experience
 
## CAIA Support Request
We have completed out pilot of the VA poster without the QR code. The [resource page](https://www.va.gov/resources/how-to-check-in-with-your-smartphone-for-some-va-appointments/) needs to be updated to reflect the new poster image and to remove references/language around the QR code.

### Which are you doing?
- [ ] **Launching a new** page, tool, form, or app
- [X] **Making changes** to an existing page, tool, form, or app

### Types of Support
What areas does your team need support in? Check all that apply.
#### Content
- [ ] Collaboration on content written by your team’s dedicated content writer 
- [ ] Collaboration on content if your team does not have a dedicated content writer
#### Accessibility
- [ ] Accessibility review of wireframes and/or prototypes
- [ ] Accessibility issue (general request)
- [ ] Accessibility PDF review request
- [ ] Accessibility user research support ([submit a separate, additional request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name))
- [ ] DST component or pattern 
- [ ] Something else 
#### IA
- [ ] User Flows
- [ ] Page placement
- [ ] Object-Oriented UX (OOUX) support
- [ ] URLs
- [ ] Breadcrumbs and Left Nav placement
- [ ] Redirects
#### Multilingual content
- [ ] Translating content
 
## Timeframe
_We guide and work alongside teams across nearly every OCTO digital product. We also work with partners across VA to lead content migration and manage all unauthenticated content on VA.gov. And we're always working to expand the VA.gov content style guide and our IA and accessibility documentation. We need to prioritize all intake requests based on our overall workload and VA and OCTO priorities._

_Tell us about your product's timeline. And we'll work with you to meet timeline needs as best we can._

### Have you worked with CAIA before? 
  - [X] Yes
  - [ ] No

### What's your team’s next step and its timing?

- **Our next step is** releasing the poster 

#### Timing for your next step: 
  - [ ] Next week
  - [X] This month
  - [X] Next month
  - [ ] This quarter
  - [ ] Next quarter
  - [ ] 6 months
  - [ ] 1 year

### Is this timing related to a specific event or Congressionally mandated deadline?
  - [ ] Yes
  - [X] No

### If you're conducting research, when is that starting? 
**Provide date if available:** xx/xx/xxxx
  - [ ] Next week
  - [ ] This month
  - [ ] Next month
  - [ ] This quarter
  - [ ] Next quarter
  - [ ] 6 months
  - [ ] 1 year

### Will you release this new product incrementally (for example, release to 25% of users to start)? 
  - [ ] Yes
  - [X] No
 
**Note**: _If you checked yes, we’ll reach out to discuss details about the content in the react widget (we use these widgets to display entry points for new products to a certain percentage of users who visit our static pages)._

  
### When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
- **We expect to launch our product to 100% of users on:** end of August, start of September
  
### Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [X] No

### If no ...
- Skip to the _supporting artifacts_ section, below.
 
#### Please provide the link to your Collaboration Cycle ticket: 
- **Ticket (number)**: 
- **Collab. Cycle Ticket Opened (date)**: xx/xx/xxxx
 
#### Please check all of the phases in the Collaboration Cycle you have completed: 
- [ ] Design Intent
- [ ] Midpoint Review
- [ ] Staging
 
##### Design Intent
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
##### Midpoint
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
##### Staging
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
  
## Supporting artifacts
*Please provide links to supporting artifacts as available.*
- **Product outline**:
- **User flows**: https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/55832
- **Prototype or mockups**: https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/60133
- **If this is in Sketch, which version or specific page should we focus on?**
- **Content source of truth**:
- **Research plan:**
- **Any epics/issues that may be helpful**:
- **Link to testing accounts** (please do not paste them in this ticket): 

### Have you already worked with someone from OCTO leadership?
- [ ] Danielle
- [ ] Beth
- [ ] Mikki
- [X] Martha

### How do you plan to work with us on this request?
- [ ] I’ll take this to Beth or Danielle’s office hours.
- [ ] I’d like to schedule time to talk about this.
- [ ] Let’s work async and meet as needed.
- [ ] Schedule a kick-off call with your team and CAIA for your project **(Recommended)**

 
### Accessibility Help in Slack
The [#accessibility-help channel](https://dsva.slack.com/archives/C8E985R32) in the DSVA Slack, is also available to you as a resource. Everyone is welcome to ask questions or get help from our a11y (accessibility) specialists. Tag `@Terry Nichols` to get a11y help asap.

**Comment by kellysmith1008** [comment]
Hey @laurwill - I'm so sorry, somehow I missed this response from you. The new poster is published on the [git page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/visual-collateral/README.md). The content change listed in the ticket are to remove mention of the QR code as it's not on the poster any longer. Thank you!

**Comment by kellysmith1008** [comment]
Content changes - remove any text in bold below:
"The poster will have a number to text **or a QR code to scan** to start the check-in process.
"Text **or scan the QR code** to start your check-in...
"Text check in ... **Or use your smartphone's camera to scan the QR code.**

**Comment by laurwill** [comment]
Thanks @kellysmith1008 ! Are these changes ready to publish now (is the new poster already up at facilities)?

**Comment by kellysmith1008** [comment]
Hey @laurwill! Yep, the changes can be published now! Thanks!

**Comment by aprocik1** [comment]
Hi @kellysmith1008! We've updated the poster image and surrounding content to remove the QR code check-in option. You can review the webpage using this preview link: http://preview-prod.vfs.va.gov/preview?nodeId=44490

We'll publish the page after your review. Thanks!

**Comment by benbrasso-agile6** [comment]
@aprocik1 did you need any png's? Or is your quality looking good?

**Comment by aprocik1** [comment]
Hey @benbrasso-agile6, the quality looks about the same on the [current webpage](https://www.va.gov/resources/how-to-check-in-with-your-smartphone-for-some-va-appointments/#:~:text=Text%20or%20scan%20the%20QR,minutes%20after%20your%20appointment%20time.). I used a screengrab of the PDF Kelly linked [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/visual-collateral/README.md). If you have a PNG, I'm happy to update the page to test quality improvements.

**Comment by kellysmith1008** [comment]
Hey @aprocik1! It looks good to me - @zach-park - would you want to take a look, too, since you worked on this as well?

**Comment by aprocik1** [comment]
Thanks @benbrasso-agile6! I just updated the page with the PNG. I can adjust the size if you'd like. Here's the new preview: http://preview-prod.vfs.va.gov/preview?nodeId=44490

**Comment by benbrasso-agile6** [comment]
Yeah, if you have trouble with the size or what something smaller, just let us know.

**Comment by kellysmith1008** [comment]
Hey y'all! I actually think the poster looks less-pixelated in the first version than the second. I'd like @zach-park to weigh in (he's on west coast) before we make a decision one way or the other. But in my humble opinion (as not a visual designer) I think the poster looks less pixelated in the first version.

**Comment by benbrasso-agile6** [comment]
The images don't render for me in the preview anyways, so I can't even see them lol

**Comment by zach-park** [comment]
Hello, I think that the image looks ok now. 

[A nitpick but fine as is] 
At a glance, it looks like the actual poster image used may be smaller than the size being displayed on the html page. Or if we are using a high-resolution poster image, the image is scaled down by the CMS engine which distorts the image (In this case, we could minimize the distortion by matching closer to the image preview size closer to the resolution of the engine outputs to).

**Comment by aprocik1** [comment]
@zach-park, it's the latter! I resized the PNG from Ben, so that it doesn't overwhelm the webpage. My goal is to keep the image small enough to fit within the step-by-step when scrolling.

@benbrasso-agile6, could you scale the PNG down to 25% the size you provided above? That would match the resize I used in the current preview.

Hopefully that resolves the distortion!

**Comment by benbrasso-agile6** [comment]
@zach-park can you help here pls?

**Comment by aprocik1** [comment]
@benbrasso-agile6, @kellysmith1008: I'm returning to include a screenshot of the current preview, since Ben is unable to see it. Note, the image of the poster is the PDF, not the PNG, since that seemed clearer to Kelly.

![2023 09 14 Smartphone Check-In Poster - Current](https://github.com/department-of-veterans-affairs/va.gov-team/assets/142408200/cadb80e8-1d15-4d19-a1a2-b4daada4e7f2)

Would you like us to publish this page as is? I'm happy to update it again, if there's a smaller image in the future. I don't want to delay the update, if this is time sensitive for your team. Let me know!

**Comment by aprocik1** [comment]
@kellysmith1008, we've completed this request and the updates are now live. Happy Friday!

**Comment by kellysmith1008** [comment]
Nice @aprocik1! It looks great! Happy Friday indeed!!
