### ISSUE TITLE
Modify and make updates to Domo card 4

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#63760]
## User Story
As an OCTO team member, I want to see how launch-blocking issues are broken up over practice area so that I can see what practice areas are likely to find the most critical issues.

Assignee: @allison0034 
Peer Reviewer: @it-harrison 

## Description
The current card # 4 communicates the count how many issues have been found per practice area at Staging Reviews over all time. The information is displayed in a bar graph. This information is not valuable and does not provide any insight to OCTO for decision making. Modified card # 4 will communicate the Governance team practice area, and the percentage of issues within that practice are that have been flagged as launch-blocking. The modified card will be a data table.

## Impacted Artifacts
[Collab Cycle Domo Dashboard - Proposed Updates (Draft)](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686764117069/5e30ad39ba0126a133110af9e4d4864246634bf1?sender=a22c79f3-4c6c-4735-9b32-c5d8fc6923ac) mural

## Tasks
- [x] Edit the existing card to filter to launch-blocking issues only
- [x] Edit the card to pivot from count of issues to percentage of all launch-blocking issues
- [x] Allow the data to be viewed by quarter displaying the most recent quarter.
- [x] Per [Redefine practice area labels](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/gh/department-of-veterans-affairs/va.gov-team/68461), update the legend and/or supporting data in Cards 4 and 5 in the SR Dashboard to link out to the [change history post](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/change-history)
- [ ] Format the card so that it displays in a data table
   - [x] Let's discuss this further. Doesn't necessarily have to be a data table, but a pie chart won't work since the total will not equal 100%

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] The dashboard has a card for percentage of launch-blocking issues by practice area

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
@allison0034 so instead of looking at practice area we would just look at launch-blocking in relation to the new standards/ or category of standards? and that should effectively communicate practice area? I think that could work.

**Comment by shiragoodman** [comment]
@it-harrison @allison0034 Let me talk to Matt about this. This was a card he had a comment on, so i think we should get his buy-in before we pivot directions.

Allison, please confirm in the comments, before closing out this tickets, which cards you're ready to go on, and which cards you have concerns about. It'll be easier for me to trace back. Thanks!

**Comment by allison0034** [comment]
Working with Ian on getting correct dataflow

**Comment by allison0034** [comment]
Ian has supplied data flow so now I will change the card.

**Comment by allison0034** [comment]
Reached out to Shira and Matt [via Slack](https://dsva.slack.com/archives/GNF5GSD9N/p1702486817428759) for their feedback.

**Comment by it-harrison** [comment]
@allison0034 looks good!
