### ISSUE TITLE
Analytics Implementation or QA Support for Profile | Editing as a Subtask

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#63770]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - AE Profile - Editing as a Subtask 
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - This is a new page, we need GA implemented 
    
- **When is the launch date?**
    - Sometime Q3/Q4 

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
---
# **I documented things here:**

**<details open><summary >Steps are in this sheets page </summary>**

[KPI Dashboard Product Details - Profile Editing as a Subtask](https://docs.google.com/spreadsheets/d/1EMEvP5g5wRTnsuz5aqHxbRADKug0KCeaa4nCbkHPDxk/edit#gid=0)

</details> 

---

   - [If this is a funnel, insert each step's URL - pages visible depending on the applicant's answers should be marked accordingly]
    
- [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - I'm going to attend analytics office hours tomorrow 8/17 to discuss and make sure I've submitted this correctly. 

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by mtcA6** [comment]
@michelle-dooley To start, thanks for all the patience y'all have had w/me over the past couple of days. Tagging you because I forget the other person's name who was on the call today. 😶‍🌫️ 

The linked spreadsheet is updated and contains the user w/the toggles flipped and the updated screenshots and step for the modal.

**Comment by michelle-dooley** [comment]
We will review and get back to you with timining.

**Comment by michelle-dooley** [comment]
We will review and get back to you with timing.

**Comment by mtcA6** [comment]
Hey @michelle-dooley checking in here.

**Comment by michelle-dooley** [comment]
Hey @mtcA6 - in reviewing this ticket I do see those sub events tracking, is this what you are looking for with this or is there more to it that I am missing? 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODZTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f2cabdbe60986b6cafc1bd1e85fa7183b81d2c9/image.png)

**Comment by mtcA6** [comment]
Nope I think that's it, I think we simply weren't sure if there was additional event stuff to do. I think we should be ok.
