### ISSUE TITLE
[FE] Onsite Notifications: Implement notification indicator in My VA healthcare

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#63775]
## Background
In support of conducting a test around the dot indicator on My VA we need to make some changes to the health care section on My VA:

1. Implement the notification indicator (dot) next to the "send a secure message" link (which will be changing to "Go to your inbox" link according to content review)
2. Implement notification indicator behind a feature flag

Resources:
- Health care FE documentation - [Go to your inbox section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/health-care-FE-documentation.md#go-to-your-inbox-link)
- [Desktop mockup](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/ZOP0Rqa)
- [Mobile mockup](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/pa393Dr)

## Tasks
- [x] Open PR on `vets-api` to add feature flag (`my_va_notification_dot_indicator `)
- [x] Set up flag on `vets-website`
- [x] Build the dot indicator if user has new messages (conditionally)
- [x] Write unit and e2e tests (e.g. if user has new messages, if user has no new messages)
- [x] Tag dev, designer, and PM for validation

## Acceptance Criteria
- [ ] Notification indicator implemented on inbox link behind a feature flag

## Resources
- [notification dot code](https://github.com/department-of-veterans-affairs/vets-website/pull/24791/files) for MHV landing page (Slack from Patrick)

**Comment by allisonlu** [comment]
@ajakabcin 

Just made minor final changes to the PR and merged it this morning, so just waiting it to get onto staging and confirm for validation. Updated the estimate to 1 point!

**Comment by allisonlu** [comment]
It's on staging for user 41!

**Comment by ajakabcin** [comment]
confirmed with multiple users on staging - we'll turn this on in prod next week for the experiment
