### ISSUE TITLE
Transition the VA Design System to Figma 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#63782]
## Problem Statement 
Currently, designers working on VA applications use Sketch which is not as easy to use in a remote environment. Figma is a popular alternative design tool that is web-based. Here are the advantages to Figma: 

* It is cloud-based, which means that it can be accessed from anywhere with an internet connection. 
* It allows multiple people to work on the same file at the same time. 
* It has a real-time collaboration feature making it easy for team members to stay up-to-date with each other’s work. 
* Designers can develop prototypes from Figma 
* Figma’s online collaboration features make it easy to get feedback in real time. 
 
How might we provide the VA Design System to designers to that they can more easily collaborate and create prototypes using the VADS? 

## Hypothesis or Bet
Transitioning the VA Design System to Figma will make it easier for VFS designers to use the design system to collaborate and create prototypes. 

## We will know we're done when... ("Definition of Done")
The VA Design System components and patterns have been migrated into Figma.
VA Design System foundation is set up in Figma
49 components are in Figma
XXX patterns are in Figma

## Known Blockers/Dependencies 
DST designers need to have licenses to build out the VADS in Figma. 
DST designers need to learn how to use Figma or get more familiar with the tool

## Projected Launch Date
February 2024 

### When you're ready to launch...
- [ ] Configure your communication to teams about your work using the [Change Communication Guide](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2317647873/Change+Communication+Guide)
- [ ] Conduct a [go/no-go](https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic
- [ ] Add this initiative to the [Digital Experience Product Board](https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform) using [these instructions](https://vfs.atlassian.net/wiki/spaces/AP/pages/2120974387/Platform+Initiative+Guidelines+for+Digital+Experience+Product+Board)

**Comment by caw310** [comment]
Closing this initiative as all work needed to transition VA Design System components to Figma has been completed.
