### ISSUE TITLE
Design | Profile | Maintenance | Update mobile header across artboards

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#63784]
## Background

The current mobile header symbol in our auth experience pattern library includes the old version of the header. We need to update it to the latest

## Tasks
- [x] Update the profile mobile header symbol in the AE pattern library
- [x] Update mobile artboards so they look correct in all sections of profile:
  - [x] Account security
  - [x] Connected apps
  - [x] Contact information
  - [x] Direct deposit
  - [x] Notification settings
  - [x] Military info
  - [x] Personal information
  - [x] Edit as a sub task

## Acceptance Criteria
- [x] We have the latest mobile header reflected in our Sketch files
