### ISSUE TITLE
[Design] My VA: Update mobile header across artboards

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#63785]
## Background

The current mobile header symbol in our auth experience pattern library includes the old version of the header. We need to update it to the latest

## Tasks
- [x] Update the my va mobile header symbol in the AE pattern library
- [x] Update mobile artboards so they look correct

## Acceptance Criteria
- [x] We have the latest mobile header reflected in our Sketch files
