### ISSUE TITLE
[Design] 10-10EZR - Standalone form: Edit Veteran Info design

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#63798]
## Background
Now that the decision has been made to build a standalone 10-10EZR form, we need to design page(s) to request Veteran information, inline with the Section I of the paper form (General Information). 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcEVPIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f6afa3fb5f5f0b14db159c90fbda565ccfdbd714/image.png)

## Tasks
- [x] Review Section I of the paper form
- [x] Design Edit pages where the Veteran can update their information
     - The Veteran's name, dob and ssn are not editable, must be displayed as read-only
     - Does not include Preferred name, SIGI, Next of Kin or Emergency Contact (TBD future)
- [ ] Review with the team/PO/PM

## Acceptance Criteria
- Edit Veteran information designs are created and shared with the team

**Comment by IMHieuVo** [comment]
- [Sketch file link](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/F6017C84-ED86-425A-A22C-01E1BDBF9533/canvas)

- The Veteran’s personal information (Name, SSN, DOB, Birth Sex) uses the “[know how their information is updated](https://design.va.gov/patterns/help-users-to/know-how-their-information-is-updated)” pattern which is based on the Notice of Disagreement (VA Form 10182) page (I placed this in the References area)

- The team agrees that the pre-filling alert status should only occur once per section. For the Veteran Information session, that message will occur at the “mailing address” page.

- There is no ‘new’ text/copy within this section. I do not think we’ll need Aliyah to review any content here.

**Comment by jessicastump** [comment]
Added to FE ticket - [link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65119#issuecomment-1743569419) - and closing this ticket
