### ISSUE TITLE
[Design] 10-10EZR - Standalone form: Create User Flow

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#63795]
## Background
As part of the Design Intent review, we must submit a User Flow.  Similar to the wireframes, we need to outline the various screens a user will walk through, the navigation buttons, any other known user interactions. While we don't have a finalized design, we can reference the EZ for this as well.  

The Design intent is a place for us to share how we intend for our design to go, there are always changes that are expected before delivery.

### Resources
- [Platform guidance on User Flow & Navigation](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/va-gov-experience-standards) (Scroll down toward the bottom for all things User Flow related)
- [10-10EZ User Flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687376928311/303a0fbb8ffe1353eedf695ac86a6e069cd2003f?invited=true&sender=u5ad49c107baa41137f271007) (example)
- [10-10CG User Flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687288632872/0728ba8a597b439671741c573fbba777ad0dac16?invited=true&sender=u5ad49c107baa41137f271007) (example)

## Tasks
- [x] Create user flow for the 10-10EZR stand alone form
- [x] Review with PM/Team for feedback
- [x] Finalize and inform PM it is ready for Design Intent review

## Acceptance Criteria
- User Flow is created and ready for Design Intent review

**Comment by IMHieuVo** [comment]
I found this [Slack conversation](https://dsva.slack.com/archives/C0NGDDXME/p1647885582213309) that may be helpful for creating User Flow
[User Flow Design System in Sketch](https://www.sketch.com/s/3b0d625a-ab30-4e83-8084-5987ea5e2bb7).

It looks like the Appointments team has a really cool User Flow in [Figma ](https://www.figma.com/file/xRs9s6QWoBPRhpdYCGc3cV/User-Flow?type=whiteboard&node-id=330%3A19313&t=Herp2BM6TeVZ8g0e-1)
Here is the [Slack conversation](https://dsva.slack.com/archives/C0NGDDXME/p1670951763901459?thread_ts=1670949662.412619&cid=C0NGDDXME).

**Comment by IMHieuVo** [comment]
**Flow A**, Full Form: mimics the 10-10EZ form.

**Flow B**, Subtasks: Breaks each section into a review subtask. For example, in the Household section, the Veteran is able to review if their spouse and dependent information is up-to-date. If it is, they move on to the next section. If not, they're able to edit the pre-fill information. Since this is a new feature, the technical timeframe for development is very long.

**Flow C**, Choose your own adventure: Starts with either a checklist or something similar. The Veteran is directed to sections that they want to update. Afterward, they're brought to a Review page where all the information they just updated is displayed along with all the information VA has on record.

**Flow D**, Review: Starts with a Review page with all the information the VA has on record. They can choose what to edit. This can be very daunting with a heavy frontload. 

**Flow E**, Confirmation: Very similar to Flow B of breaking each section down into a review and edit but leveraging existing patterns to create this flow. The design and dev team thinks this may be the best route, balancing between the stakeholder’s and Veteran’s wants and needs.

Location of the [Sketch file](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/A0C657F6-3318-45A0-93CB-246BA8722E37/canvas).

Also note the flow is also technically a part of the [Wireframe ticket #63037](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63037).
