### ISSUE TITLE
Collaborate with SM & Appointments on landing page updates before launch to Phase 1

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#63802]
## User Story
As a Cartography team member, I want to understand what (if any) changes need to be made to URLs for Appointments and Secure Messaging sections of the MHV landing page, so that I am prepared to launch those updates at the same time the two teams move to Phase 1. 

## Description
Per a conversation with Coulton Bunney & Mikki Northuis on 8/16/23, Sara learned that the SM & Appointments teams plan to move to Phase 1 in October 2023. When this happens, all users in the MHV environment will get broad messaging about trying out the new version of those tools on VA.gov and will be directed there. Once on VA.gov within the new tools, breadcrumbs will be exposed that will direct users to "My HealtheVet" and we will need all of them to be able to access that page. tl;dr: we need to be at 100% at the same time these tools move to Phase 1. 

In light of this information, we should start conversation with both the Appointments & Secure Messaging teams to see if any changes in those sections of the landing page need to take place before the launch of Phase 1 (i.e. URL changes, updates to link text, redirects, etc.).

## Impacted Artifacts
* MHV Landing page 

## Tasks
- [ ] Meet with Appointments team to discuss
- [ ] Meet with SM team to discuss

## Acceptance Criteria
- [ ] Cartography team understands the changes that need to be made to the landing page before each tool launches to Phase 1.
