### ISSUE TITLE
[SW] Regression Test Plan

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#63812]
## Issue Description
Complete a regression test plan under the Test Runs & Results tab of TestRail. See additional guidance from Platform here:
https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-regression-test-planRegressionTestPlan
---
## Tasks
- [ ] Create regression test plan per instructions noted from Platform 

## Acceptance Criteria
- [ ] _Regression Test plan created
- [ ] Testing completed (if applicable)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Tom-Davis** [comment]
Closing as this was done on a per ticket basis and not as a single effort.
