### ISSUE TITLE
Update phone instructions on Report a death page

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#63817]
## Issue Description
The phone option on our [How to report the death of a Veteran to VA page](https://www.va.gov/resources/how-to-report-the-death-of-a-veteran-to-va/) leads to a phone menu option that says "select 5 for burial assistance." We received a comment that this is confusing.

We need to adjust the wording on our page to assure people that selecting 5 is the correct way to report a death by phone. We'll also find out how to suggest an update to the phone menu to say "select 5 for burial assistance or to report a death."

---
## Tasks
- [ ] Update phone option instructions in Drupal (Aliyah)
- [ ] Review (Laura)
- [ ] Copyedit and publish (Megan)
- [ ] Suggest update to phone menu to team that owns this system (Laura)

## Acceptance Criteria
- [ ] Phone instructions on live page are clear and consistent with the phone menu

**Comment by aliyahblackmore** [comment]
Hi @laurwill - ahead of getting my suggested change in Drupal, I gave the telephone number ([800-827-1000](tel:+18008271000) on the How to report a death to VA page a call. 

It seems like the menu option is not up to date and says "for burial assistance or to report the death of a Veteran, press 5."

It seems like we'd no longer need additional content on this page as the initial ask was a result of the call menu previously only saying "For burial assistance, press 5"  and the content would've been to assure users that they can also select 5 to report the death of a Veteran (even though that wasn't stated in the menu).

Let me know if there is a still a need for additional content or adjusted wording on our page - otherwise I think we can close out this ticket.

This is my suggested content, if needed (if you confirm, I'll put this in Drupal): 

**Note**: When you call us, the phone menu option will say “for burial assistance or to report the death of a Veteran, press 5.” This is the correct option to report the death of a Veteran to VA.

**Comment by laurwill** [comment]
Hi @aliyahblackmore , thanks so much for looking into this! I just confirmed that the menu is now listing "report the death of a Veteran" as you said, so no change needed here :) Closing this out.
