### ISSUE TITLE
Update eligibility information on DEA pages due to change in law

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#63819]
## Issue Description
Tammy and Terry from the education business line requested updates to 2 benefits pages due to a change in law. They've asked us to make these changes ASAP, so that they can begin communications about the change and link to the updated web pages. We'll need to edit the suggested text to align with our content standards and site style.

Here's the requested changes in a Word doc:
[Changes to DEA pages.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBajhTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--57682d193d6adfe986285a8ccbd92b66220e7b31/Changes%20to%20DEA%20pages.docx)

---
## Tasks
- [x] Update 2 DEA webpages with new eligibility info (Katherine)
- [x] Review (Laura)
- [x] Send to stakeholders for approval (Laura or Katherine)
- [ ] Copyedit and publish (Megan)

<details>
<summary>Prepublishing checklist</summary>

### Before you begin
- [ ] Confirm that there are no updates in draft by other content authors that aren't ready to be published. Check the revision log and then confirm with the content author who made the previous edits that the page is ready to publish.

### Accessibility standards

- [ ] If your link or button will take the user off VA.gov, confirm that the text for the link or button contains a purpose and a target. The user should be able to tell from the link or button text what the call to action is (the purpose) and where they will end up if they click on the link (the target). The following link is an example of this: <br>[Read more about making links accessible on AccessibilityOz](https://www.accessibilityoz.com/2014/02/links-and-accessibility/)</br> 
**Note:** When you direct the user to another VA.gov page, the link only needs to contain text indicating purpose (the call to action).
- [ ] Confirm all phone numbers are in aria labels. [Learn how to code numbers with aria labels](https://design.va.gov/content-style-guide/dates-and-numbers#phone-numbers)
- [ ] Confirm that the hierarchy of section and subsection titles is correct (H1 to H2 to H3—levels shouldn't be skipped). [Learn more about section titles](https://design.va.gov/content-style-guide/page-titles-and-section-titles)
- [ ] Replace any sighted language ("view," "see," "look") with a word that's inclusive of our screen reader users ("check," "go to," "review").
- [ ] Avoid using other ability-focused language. ("hear back from")

### Link standards

- [ ] Confirm that links work (aren't broken—no error message) and point to the intended page (you pasted in the correct URL or chose the correct node ID).
- [ ] Confirm all link text is 100 characters or less.
- [ ] Check that you've selected a node ID for all links pointing to VA.gov (internal) pages. Only paste in a URL if the page you're linking to doesn't live in our CMS (isn't one of our modernized pages). [Learn how to add node IDs in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/linking-with-node-ids.md) 
- [ ] Check that all anchor/jump links are pointing to a node followed by # and the header identifier (Example: /node/47278/#information-for-survivors). Double check all anchor/jump links post-publish. 

### CMS standards

- [ ] Make sure all apostrophes and quotation marks are curly not straight. (Once this is automatic in Drupal, we can remove this item.)
- [ ] If there are alerts at the top of the Drupal Edit node for broken links, redirected links, or links to unpublished pages, correct the issues. If there's an alert for a broken link but the link is actually working, report the issue to the CMS help desk. [Read more about link alerts in the CMS knowledge base](https://prod.cms.va.gov/help/cms-basics/how-to-fix-broken-links-and-redirects)
- [ ] If publishing a brand-new page, confirm the left nav and url are set up correclty. (If the page is a child page, the section needs to be the same as the parent page in order for the left nav to show.) [Learn how to set up a url and left nav in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/adding-left-nav-and-url.md)
- [ ] Check if the page has a new or updated alert. If so, publish the alert separately. 

### Additional checks for translated articles
- [ ] If we don't have updated translated versions, add the alert that links to the corresponding English page and lets users know that the translated pages aren't up to date. 

</details>

## Acceptance Criteria
- [ ] 2 DEA webpages reflect new eligibility rules

**Comment by katherine-fung** [comment]
Hi @laurwill, 

Here's the program page for DEA benefits: 
http://preview-prod.vfs.va.gov/preview?nodeId=950 

The other page we have to update is the "VA education benefits for survivors and dependents" page. But since we plan to pull the table off this page and have a new "Compare DEA and Fry Scholarship benefits for family members" page, I'm updating the new page instead. 

Here's the new page: http://preview-prod.vfs.va.gov/preview?nodeId=44718

Questions for the stakeholder: 

1. For this bullet point, can we remove the effective date of the rule? 
"The Veteran or service member is in the hospital or getting outpatient treatment for a service-connected permanent and total disability and is likely to be discharged for that disability (effective December 23, 2006)" 

2. We say: "If we rated the Veteran as permanently and totally disabled, with an effective date that’s 3 years after discharge from active duty, you’ll qualify for benefits for 20 years from that effective date. This new policy began on October 10, 2008. **We won’t pay benefits for training you started before this date."**

What does **We won’t pay benefits for training you started before this date."** mean? Does it mean if a spouse was using a different benefit to take classes, and then the Veteran or service member died, the DEA benefits only cover the portion of the classes after the death? Or does it mean if the spouse was taking classes and then the Veteran or service member died, DEA won't cover any of the classes at all because they started before the death?

**Comment by laurwill** [comment]
Hi @katherine-fung ,
Since we don't have SME approval for the new "compare" page yet, I updated the existing table on this page for now.
http://preview-prod.vfs.va.gov/preview?nodeId=984

We'll move ahead with publishing the updated table for now, and then make the same change on the new page. 

I also made some adjustments to the main DEA page. I tried a more straightforward/scannable header "Time limits if you became eligible before August 1, 2023." Even though the text from partners addresses turning 18 or completing high school as separate from "becoming eligible," you can't use benefits before that. So I think this could be a clearer way to distinguish. Could you review the updated draft and see if you agree? 
http://preview-prod.vfs.va.gov/preview?nodeId=950

Then you can send the draft updates to the education SMEs for review, with the 2 questions you called out above. Thank you!

**Comment by katherine-fung** [comment]
Thanks @laurwill! The new subheader looks good to me. 

I'll email stakeholders with the links and questions, and CC you.

**Comment by katherine-fung** [comment]
We got feedback from SMEs yesterday on 9/20. I'm working on incorporating it.

**Comment by megzehn** [comment]
Confirming I published these 2 pages. Thanks, @katherine-fung!

**Comment by megzehn** [comment]
Moving to validate

**Comment by katherine-fung** [comment]
closing this ticket
