### ISSUE TITLE
Google Analytics Filter Review

### ISSUE THREAD

**Issue by nedierecel** [department-of-veterans-affairs/va.gov-team#6382]
In Sprint 21, Analytics-Insights will review existing filters applied to views to ensure they are still accurate and relevant. 

## Goal
Update settings across all views to ensure filters are applied correctly for each product

## Objectives or Key Results this is meant to further
- _Include references to KPIs we intend to impact_
---
## Tasks
- [ ] Review all filters and views
  - [ ] Update RegEx `Global - Add Trailing Slash if missing` in Non-Production, then apply to Production: This does not appear to be adding the trailing slash consistently.
- [ ] Rename filters to be more readable
- [ ] Document within Platform folder

## Acceptance Criteria
- [ ] Outdated filters renamed with "DEPRECATED" prefix or deleted with documentation 
- [ ] Annotations provided when filter changes may impact data within a view
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nedierecel** [comment]
Additional to-do's:
1. Rewrite custom task within Google Tag Manager to strip params
2. Site Search: 
- Review including `name=` as site search query parameter
- Work with @jonwehausen to brainstorm if we'd like to incorporate the education site search into `All VA.gov - Production`

Progress:
1. Created then deleted new test view for benefits.va.gov
2. Renaming filters that are not product specific to include "Global -" as a prefix

**Comment by nedierecel** [comment]
@bsmartin-ep I will hand this task off to you as well. The intent was to do a period cleanup of the filters to ensure that our filters are still relevant. I will share any artifacts or will create new documentation. 

Next steps for you:
1. Initial Review - Within the Production property, please begin combing through the view-level filters to get familiarity.
2. PII Filters - We use View settings and the rewrite filter on Facility Locator URLs to remove PII; however, I think we should pivot to using a GTM custom task to remove PII from URL params. This might need its own task, but something to think through. 

Next steps for me:
1. I'll note where I'd like you to take over specifically in the filter audit.

**Comment by nedierecel** [comment]
@bsmartin-ep I added a subtask for you to please review. 

>Update RegEx Global - Add Trailing Slash if missing in Non-Production, then apply to Production: This does not appear to be adding the trailing slash consistently.

**Comment by bsmartin-ep** [comment]
@nedierecel - 

> This does not appear to be adding the trailing slash consistently.

I _think_ the issue is with the order of the global filters on _All VA.gov Website Data [Production]_.  When the _Global - Append Hostname to URI_ filter rewrites the _Request URI_, the trailing slash regex no longer matches due to the Request URI no longer "starting with" a slash.

If we swap these at the top of the view, it should fix it.

**Comment by nedierecel** [comment]
Thanks @bsmartin-ep 

1. Trailing Slash - Can you test in staging then apply in production? Please annotate after the fix is made.
2. Custom Task for PII - Awesome. This could be spun into its own issue if you think it warrants its own task for a future sprint.

CC: @jonwehausen

**Comment by nedierecel** [comment]
@bsmartin-ep Thanks for sharing your review. I added comments on views and filters for any context/background.

**Comment by bsmartin-ep** [comment]
Thanks @nedierecel for the context.

The trailing slashes look good on staging, though I'm going to keep an eye on it while we accumulate data for today.

One case that doesn't match is when a path is a query-string parameter:

> mhv-syst.myhealth.va.gov/mhv-portal-web/user-login?redirect=**_/mhv-portal-web/home_**

It makes sense to me to keep this as-is though since it is an accurate.  Is this something that should be fixed by development (or networking) to match our trailing slash policy?

**Comment by nedierecel** [comment]
@bsmartin-ep This might be handled by the MHV team, which is outside of VSP and VFS. Do you think it's worth stripping off the redirect parameter altogether?

For situations where there is not a canonical URL on the modernized side, we can bring that up with the dev or IA teams. 

FYI - We're experiencing a high cardinality of rows in GA, which could get fixed with your new order of view filters.

**Comment by bsmartin-ep** [comment]
cc @jonwehausen 

Trailing slash and Append hostname filters swapped in the following views:

**Prod**
All VA.gov Website Data [Production]
va.gov - EBenefits Test View
va.gov - Test View

**Non-Prod**
All Web Site Data - VA.gov Testing Environments
Vets.gov Non-Production - Test Data
WBC - Modernized Content - Testing Environments

**Comment by bsmartin-ep** [comment]
After letting this run for a few days, it LGTM.  No change in overall production traffic and URLs with missing trailing slashes have disappeared.  

I will open a separate ticket to discuss and implement global lowercasing.
