### ISSUE TITLE
NOD | Connect with BVA for content-related questions

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#63829]
## Value Statement
**_As a_**  designer
**_I want to_** understand the form from BVA stakeholders' perspectives
**_So that_** we can create designs with accurate information that result in usable outputs

---
## Tasks
- [x] Meet with BVA legal to review content, and understand legal limitations on what we can tell Veterans
- [x] Meet with or async get answers from intake team to better understand the use of the area of disagreement and additional information

## Designs and Build Notes
- [Github | SME Discovery and Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/design/SME-Discovery-Review.md)

## Definition of Ready 
- [x] Clear value description
- [x] Reviewable acceptance criteria
- [x] Research findings are complete
- [x] Priorities are scoped

## Definition of Done
- [ ] Designs are approved by PO and ready to test

**Comment by eileen-coforma** [comment]
Sent email to BVA team to follow-up questions and set up a meeting.

**Comment by eileen-coforma** [comment]
@rubensun Can we consider this closed, or are there more questions we need to ask the BVA?
