### ISSUE TITLE
[Design] 10-10EZR - Standalone form: Edit Insurance Info design

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#63822]
## Background
Now that the decision has been made to build a standalone 10-10EZR form, we need to design page(s) to allow the Veteran to edit their information, inline with the Section II of the paper form - Insurance Information. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGtTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9c928ca186b1614a4ebd7bdee6f5b62d0a8fe66e/image.png)

## Tasks
- [x] Review Section II of the paper form
- [x] Design pages editing the insurance information
     - Include multiple response component for Insurance policies
- [x] Review with the team/PO/PM

## Acceptance Criteria
- Edit Insurance info page design is created and shared with the team

**Comment by davidakennedy** [comment]
The in-progress [design files are in Sketch](https://sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22).

**Comment by davidakennedy** [comment]
Dropping a [better link to the insurances pages canvas](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/31E4F6F4-F97C-45D9-AAFE-FF20C19E0504/canvas).

Closing out this ticket as complete. Shared with designers/team and content for feedback.
