### ISSUE TITLE
[Design] 10-10EZR - Standalone form: Edit Income information design

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#63824]
## Background
Now that the decision has been made to build a standalone 10-10EZR form, we need to design page(s) to allow the Veteran to edit their Income information, inline with the Section IV of the paper form - Previous year's Income Information. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbnNTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b9c99bbfc47753c94115ded2e24fd8b33f5a2261/image.png)

## Tasks
- [ ] Review Section IV of the paper form
- [ ] Design pages editing the income information
- [ ] Review with the team/PO/PM

## Acceptance Criteria
- Edit Income information designs are created and shared with the team

**Comment by jessicastump** [comment]
[Sketch page](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/3B1847D9-15A8-4526-A264-F00F656EDAC6/canvas) of household information section. This includes spouse, dependents and income/deductible pages.

[Additional artboard](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/w5wOvpp) created to workshop ideas for a simple alert and direction on income prefill/update content.

**Comment by hdjustice** [comment]
Ticket not necessary - included in household ticket
