### ISSUE TITLE
[epic • HCD] DR | Content Investigation — Pathway Discovery & Selection

### ISSUE THREAD

**Issue by rubensun** [department-of-veterans-affairs/va.gov-team#63855]
## Value Statement

**_Activity_** (I want to)
Conduct investigation into content supporting decision pathway discovery & selection

**_Outcomes_** (so that)
The team is better informed about the decision pathway discovery & selection as a topic to support creating content for Veterans that is direct, clear, and concise.

---
## Tasks
- [x] Lit Review - Review notes from past discussions with SMEs to gather existing knowledge and assumptions.
- [x] Secondary Research - Review current sitewide pages for definitions of decision pathways and guidance surrounding pathway selection.
- [ ] Content Review - Conduct plain language audit of existing descriptions. Gather current best definition of decision pathways, assumptions and knowledge gaps.
- [ ] SME Collaboration
> - [ ] Share our intent with both VBA and BVA stakeholders
> - [ ] Connect with VBA and BVA SMEs to gather input
- [ ] Content Synthesis and Shareout
> - [ ] Synthesize input from SMEs
> - [ ] Provide findings and plans of action with BVA and VBA stakeholders to gather feedback.

## Definition of Done
- [ ] Team can review materials for SME discussion and provide input/feedback in advance
- [ ] We've met with SMEs to gather insights into any knowledge gaps relating to decision pathways, and pathway selection
- [ ] Content synthesis supports the in team in understanding how to approach content supporting decision pathway discovery, selection and validation.

**Comment by HeatherWidmont** [comment]
@rubensun to post updates & next steps in this ticket (they're already in Slack)

**Comment by rubensun** [comment]
We Reviewed:

> [Decision Review Current State Submission Journey](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1690387223008/f0a181d0e07ca61332dad63bb0a9794d0437755e?wid=0-1701181729188)
> Theoretical “critical path” of decisions and actions outlining the considerations and decision points involved Veterans go through in determining the most relevant course of action in the face of an “unfavorable” claim decision.
> 
> - Gathering situational awareness about their claim decision
> - Identifying options for recourse and gathering the relevant topical information to make an informed selection about an approach to take
> - Establishing an approach for framing and supporting the disagreement
> - Filing and Submitting a Decision Review / Appeal

> [Decision Review Content Inventory](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1690387223008/f0a181d0e07ca61332dad63bb0a9794d0437755e?wid=0-1701181581290)
> Collection of VA Materials supporting the decision review pathways and the various considerations and decision points
> 
> - Materials on [va.gov](http://va.gov/)
> - Materials on [bva.va.gov](http://bva.va.gov/)
> - Materials on [benefits.va.gov](http://benefits.va.gov/)
> - Supporting materials PDFs, Decision Letter Attachments

 
We discussed:

> - The distinction between matching Veterans to the most relevant use cases (end preventing downstream errors in the decision review / appeals adjudication process) from providing recommendations to gain favorable claim decision outcomes. Our focus is on the former. 
> - Pertinent evidence matching to different decision review / appeal use cases based on the nature of disagreement and how there may be overlap between our efforts of investigation and the efforts put forth by the CST team
> - Distinction between claims and contention decisions (and their related claims / appeals histories), and how that informs an understanding of options to pursue.

Next Steps:
- @eileen-coforma and @saderagsdale to identify potential gaps in the decision review current state decision journey and 
@rubensun to incorporate / iterate
- @eileen-coforma and @rubensun to develop a future state decision tree for a potential guided process
- @rubensun to map decision review decision points and considerations to identify content that best supports the most informed decisions

**Comment by HeatherWidmont** [comment]
Ruben is recording some elements in pre-existing experience journeys & continuing to build out the content map

**Comment by eileen-coforma** [comment]
In a good place with the critical path. Will be focusing on content.

**Comment by rubensun** [comment]
- Continuing to investigate claim eligibility and evidence
- Developed an agenda for an [alignment workshop](https://docs.google.com/document/d/1XjaRPNDdnCahr7Cax9_pFiIzgzlQtnIg3nKfDRowSjY/edit
) with the enablement team for when we return

**Comment by saderagsdale** [comment]
I added this as a topic for tomorrow's product huddle with Julie and Zach.

**Comment by saderagsdale** [comment]
@rubensun Hey there - can you add an update on which tasks are completed and next steps for this ticket?

**Comment by saderagsdale** [comment]
Will update after connecting with Julie.

**Comment by saderagsdale** [comment]
@saderagsdale review agenda. 

@rubensun post agenda.
