### ISSUE TITLE
Compile list of pension (527) and burial (530) form page URLs

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#63863]
## Issue Description
_Ensure our form flows are not missing any hidden state pages._

---
## Tasks
- [ ] Compile a list of all the 527 form urls and replicate this [example from 526](https://docs.google.com/spreadsheets/d/1Bi65N54v2yKCFFR42aStk3SGHBXlHDOCNbchKHb8ddg/edit#gid=0)
- [ ] Compiles a list of all the 530 for urls and replicate above template.

## Acceptance Criteria
- [ ] Completed spreadsheet with list of 527 form URLs and accompanying information provided to @fiorella-io 
- [ ] Completed spreadsheet with list of 530 form URLs and accompanying information provided to Fiorella
---

**Comment by zack** [comment]
[Form 527 (Pensions)](https://docs.google.com/spreadsheets/d/1vJPeZx4zpo7pEEOkWpzTBr0N10Y4SZdpB1UbaN0kjlE/edit#gid=0)

**Comment by zack** [comment]
[Form 530 (Burial)](https://docs.google.com/spreadsheets/d/1caUB2Fc2BcDhbVZEEem4IVzZmIqgKdCsv2hIFc-Ffdc/edit#gid=0)

**Comment by steele-lm** [comment]
@fiorella-io Tagging you here in case you want to review the page urls to see if any are missing from the form flows.
