### ISSUE TITLE
FE | Direct Deposit > EVSS>LH | Payment Address Not Found error handling 

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#63876]
## Background 
If we rollout backend [changes made here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63323) for better error handling, we may need to update the FE to support this. Tom's PR is ready to go but we should discuss impacts and account for the changes with this ticket. 

>Originally, I was seeing some `500 Internal Server Error` errors that were due to `502 Bad Gateway` error responses from Lighthouse that were not being handled properly.
>
>I'm no longer seeing these errors in our logs; instead, I'm seeing `502 Bad Gateway` responses, but with a message of `Payment Address Data Not Found`.
>
>According to the HTTP standard, a `502 Bad Gateway` server error response code indicates that the server, while acting as a gateway or proxy, received an invalid response from the upstream server.  
>
>I think Lighthouse has made a change (possibly on Aug 10th) that will affect the way we handle this type of response.

_Originally posted by @tpharrison in https://github.com/department-of-veterans-affairs/va.gov-team/issues/63323#issuecomment-1679830383_

## Tasks 
- [ ] ensure FE is updated to support the BE changes 
- [ ] Tests are revised/corrected 
- [ ] Confirm GA events/tracking is updated accordingly 

## Acceptance Criteria 
- [ ]  FE is updated to handle the enhanced 500 error information we're seeing

**Comment by adamwhitlock1** [comment]
Tom is getting a PR in for this error to be standardized and then I can use that error code to display an error on GETs for direct deposit.

@mtcA6 did we have a design ticket for what this new alert will look like? I can't remember if there is a sketch file or issue that I can refer to when doing this work.

Regardless this will be carrying over into next sprint.
