### ISSUE TITLE
Update the guidance for experimental design in Collaboration Cycle

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#63885]
## User Story
As a Governance team member, I want to understand how to provide feedback for experimental designs, so that I can correctly label/document them.

Assignee:
Peer Reviewer:

## Description
We previously documented how we can provide feedback on and label experimental designs when we seem them in the collab cycle. Since then we have run into a few issues such as labels not being in the correct repo. The design system team now also has GH projects for tracking. #40385

[Design system page](https://design.va.gov/about/contributing-to-the-design-system/)

## Impacted Artifacts
- [How to document feedback for a Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1945239838/How+to+document+feedback+for+a+Midpoint+Review?focusedCommentId=2739208419)
- [How to document feedback for a Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1934426130/How+to+document+feedback+for+a+Design+Intent)
- [How to document findings for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+findings+for+Staging+Review)

## Tasks
- [ ] Review current documentation (check labels and which repo they are in)
- [ ] Review [GH project](https://github.com/orgs/department-of-veterans-affairs/projects/946/views/3) for experimental requests
- [ ] Reach out to the Governance team to see what makes sense for us to track experimental design
- [ ] Reach out to Matt/Carol to see what makes sense to track experimental design
- [ ] Update documentation

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] As a Governance team member I can complete my reviews and know how to label/document experimental design.

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@allison0034 can you link the VFS-facing guidance on the experimental design process?

**Comment by shiragoodman** [comment]
@caw310 @humancompanion-usds Similar to ticket #55469, Governance team believes this ticket is out of scope for our team. I am going to close the ticket, however I wanted to make you aware of it in case there's any details you'd like to capture. Please let me know if you have any questions or if you'd like to discuss. Thanks.
