### ISSUE TITLE
Updates to Tagalog PACT Act page for end of backdated benefits deadline

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#63947]
## Issue Description

Now that the deadline for Veterans to receive backdated benefits has passed, we made content changes to the English PACT Act page that we also need to apply to the [Tagalog PACT Act](https://www.va.gov/resources/the-pact-act-and-your-va-benefits-tag/) page. We made changes to 2 Q&As within the page as well as created a new banner about the special enrollment period that will need to be added to the Tagalog page.

Content sent to the State Department:

## Tasks
- [ ] Send content to State Department (Randi)
- [ ] Update Drupal page (Ana)
- [ ] Add new banner (Ana)
- [ ] Review changes (Megan)
- [ ] Publish (Megan)

## Acceptance Criteria
- [ ] Tagalog PACT Act page is live with most recent changes

**Comment by RLHecht** [comment]
@ABeltran77 Here's the Tagalog content back from the translators. [LS-2022-0118394-A-TAG-FINAL_PACT Act special enrollment period content.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzFkIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d00efe5e8b62f10aa7ae19b4b590e30ec0f23504/LS-2022-0118394-A-TAG-FINAL_PACT%20Act%20special%20enrollment%20period%20content.docx)

**Comment by ABeltran77** [comment]
@RLHecht @megzehn Updated Tagalog Drupal page. Waiting for permissions/access to create a banner alert.

**Comment by megzehn** [comment]
Confirming I reviewed and published the changes on the bottom of the page!
