### ISSUE TITLE
Updates to Spanish PACT Act page for end of backdated benefits deadline

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#63946]
## Issue Description

Now that the deadline for Veterans to receive backdated benefits has passed, we made content changes to the English PACT Act page that we also need to apply to the [Spanish PACT Act](https://www.va.gov/resources/the-pact-act-and-your-va-benefits-esp/) page. We made changes to 2 Q&As within the page as well as created a new banner about the special enrollment period that will need to be added to the Spanish page.

Content sent to the State Department:

## Tasks
- [ ] Send content to State Department (Randi)
- [ ] Update Drupal page (Ana)
- [ ] Add new banner (Ana)
- [ ] Review changes (Megan)
- [ ] Publish (Megan)

## Acceptance Criteria
- [ ] Spanish PACT Act page is live with most recent changes

**Comment by RLHecht** [comment]
@ABeltran77 Here is the content back from the translation team: [LS-2022-0118394-A-SPA-FINAL_PACT Act special enrollment period content.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanhaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--99279b07e648e767225b0ac9586880a0753a5eb5/LS-2022-0118394-A-SPA-FINAL_PACT%20Act%20special%20enrollment%20period%20content.docx)

**Comment by ABeltran77** [comment]
@RLHecht @megzehn Updated Spanish Drupal page. Waiting for permissions/access to create a banner alert.

**Comment by megzehn** [comment]
Confirming I reviewed and published the pages!
