### ISSUE TITLE
Create Checkbox Button for Order Supplies and Order Accessories Page

### ISSUE THREAD

**Issue by mojaray2k** [department-of-veterans-affairs/va.gov-team#6394]
## User Story or Problem Statement
As a veteran, I need to be able to click on a button so I can indicate that I want to reorder hearing aid batteries or accessories.

## Goal
The Veteran should be able to click on a button to indicate they want to or don't want to reorder supplies. 

## Tasks
- [ ] Create the styles to make a checkbox look like a button

## Acceptance Criteria
- [ ] the user should see two different states if the checkbox button is checked or unchecked. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
