### ISSUE TITLE
Create risk analysis for CMS content release defects

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#6395]
## User Story or Problem Statement
As a VSP QA stakeholder, I need to understand the risks associated with escaped defects from the content teams so I can recommend a quality assurance strategy for output from the content teams.

## Goal
1. A reusable risk analysis template for VSP
1. A completed risk analysis template for CMS defects

## Objectives or Key Results this is meant to further
Ensure that quality assurance standards are being met everywhere on the platform
---
## Tasks
- [x] Create a risk analysis template that fits VSP
- [x] Perform a risk analysis of escaped defects from CMS content teams
- [x] Complete the risk analysis template for escaped defects from CMS content teams
- [x] Create markdown version of the completed risk analysis
- [x] Create markdown version of the template

## Acceptance Criteria
- [x] Risk analysis template created and stored for future use on the platform.
- [x] Risk analysis performed on escaped defects from CMS content teams.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pjhill** [comment]
First draft of template here -- https://drive.google.com/file/d/1Yz0fr2lIdTeMPY0OkarlzkFV-D1NAHd1/view?usp=sharing

**Comment by pjhill** [comment]
Redid this in a spreadsheet instead -- https://docs.google.com/spreadsheets/d/1jkDNTE5zrNLWP5YSbG6dhpMQCme1kfsUA-OIC7ltriw/edit?usp=sharing

**Comment by pjhill** [comment]
Meeting to discuss risk analysis with Trevor and Tze scheduled for 3/11 @ 1pm ET.

**Comment by pjhill** [comment]
Completed risk analysis here -- https://docs.google.com/spreadsheets/d/1HOGFkg5AcGmwzdx8bx-GnkEAP97iZ7XLxh4IKzN5_L4/edit?usp=sharing

**Comment by pjhill** [comment]
Completed risk analysis in markdown -- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/risk-analysis/CMS-escaped-defects-risk-analysis.md

Risk analysis template in markdown -- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/risk-analysis/risk-analysis-template.md
