### ISSUE TITLE
Find all URL's that exist within 686c form flow 

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#63964]
## Issue Description
We need to find all URL's that exist within the 686c form flow to confirm they're captured in the Mural board. https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687976281975/2a9c6ca9ea6d955afa7977c777bbb72b15280903
- [ ] it may also be helpful to review this work Fred completed for Burials/Pension where he looked for all URL redirects https://github.com/fred-khoury-oddball/pup_crawler

---
## Tasks
- [x] Add audit data to shared spreadsheet

## Acceptance Criteria
- [x] We are looking for an output similar to this file (done for 526) https://docs.google.com/spreadsheets/d/1Bi65N54v2yKCFFR42aStk3SGHBXlHDOCNbchKHb8ddg/edit#gid=0
- [ ] we would like to reuse this code on other forms (Pension/Burials) so please ensure it can be reused and is stored in a public location

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sortizsh** [comment]
@zack can you please research this, and add tasks in the ticket above? thank you

**Comment by zack** [comment]
Created a spreadsheet and added it to the Engineering folder in our shared drive!
