### ISSUE TITLE
[Design] 10-10EZR - Standalone form: Create Source of Truth content document

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#63967]
## Background
In an effort to get started on content reviews for the new standalone 10-10EZR form, we need to create a Content Source of Truth document that can be worked on with the Content team, in tandem with the online form design.   This way, we don't have to wait for the designs to be done before the content is reviewed.

### Resources
- [10-10EZ Content Source of Truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZ%20Form/10-10EZ-application-content.md) example
- [10-10EZR paper form](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/EZ(R)%20Update%20Capabilities/VA%20Form%2010-10EZR.pdf)
- [10-10EZR wireframe and user flow](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/A8A73F5C-CD0D-4862-AE2E-71BCE8F00790/canvas)
 
## Tasks
- [x] Create a GitHub document to contain the content for each page of the EZR form
- [ ] Review with team/PM/PO periodically for any concerns or questions
- [ ] Review with CAIA on Content Ticket (#XXX)
 
## Acceptance Criteria
- A Content Source of Truth document is created and used to finalize the content of the 10-10EZR form

**Comment by IMHieuVo** [comment]
The source of truth document is located [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/10-10EZR%20Form).

The main flow is completed but I will constantly revisit to update information as we change content and add new use cases.
