### ISSUE TITLE
Modify the current T&C page (content-build + devops)

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#63988]
## Description
Modify the current Terms and Conditions page so that the URLs and routes (for IA) match for (content-build)

## Tasks
- [x] Update the `terms-and-conditions` application in vets-website
  - [x] Change the `terms-and-conditions` => `terms-of-use`
  - [x] Update routing on
    - [x] vets-website (registry scaffold)
    - [x] content-build (registry scaffold)
  - [x] Ensure breadcrumbs are correct
  - [x] Add a generic route for error page
