### ISSUE TITLE
ToU: Add API call for user actions

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#63995]
## Description
Create a call to the API endpoint to update the Terms of Use criteria

## Tasks
- [x] Add API call to the ToU API
  - [x] User accepts
    - [x] create the fetch with the proper data as required by the BE
    - [x] Work with BE API team to determine requirements (Content-Type, data, etc)
  - [x] User declines
    - [x] Work with BE API team to determine requirements
      - [x] Should there even be an API request?
      - [x] If API request needed, create the fetch with proper data + HTTP method
