### ISSUE TITLE
ToU: Create the ToU page (vets-website)

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#63990]
## Description
Create the Terms of Use page and have it rendered appropriately (in vets-website)

## Tasks
- [x] Create the Terms of Use base page
  - [x] Add the default blocks for each section
  - [x] Parse through the entire Terms of Use content so that it is rendered appropriately with accordions, version, and date
- [x] Create Error Page
  - [x] Matches the Figma
  - [x] Has the ability to re-sign in a user via SignInModal

**Comment by asg5704** [comment]
UPDATE
- Putting back into In Progress (to get actual content) content on this endpoint (https://veteran.apps.va.gov/signup/v1/terms-and-conditions)
