### ISSUE TITLE
BE | Profile | Contact Information | Update Address Line 1 length to 100

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#63997]
## Background
In VA.gov, the maximum value for `AddressLine1` field is currently set to 35.  The maximum length in VA Profile is 100.

See this ticket for more background - https://github.com/department-of-veterans-affairs/va.gov-team/issues/20397.

## Tasks
- [ ] Update the Address Line 1 field to allow up to 100 characters. 
- [ ] confirm there aren't any downstream impacts (ie. VA Profile may accept an address of 100 characters but a downstream system may only allow 35, [i don't think this is actually an issue it seems like it's a profile api problem we need to fix based on Tom and Eric's investigations](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20397#issuecomment-803207577)) 

## Acceptance Criteria
- [ ] Update any existing validation specs.
- [ ] Create new specs to ensure Address Line 1 has a maximum field length of 100.
- [ ] Verify in staging environment

**Comment by mtcA6** [comment]
Lets set this back to the backlog and pick this up when we have less madness going on with the launch errors

**Comment by mtcA6** [comment]
Tom to reach out and confirm with Josh Lindsay to confirm the rule and to test it.

**Comment by tpharrison** [comment]
@mtcA6 The recommendation is to keep our validation length at 35 characters.

Based on the following conversation...

> Lindsey, Joshua: 
> Tom - the 100 input is to enable a consumer to send a longer address line that will then be standardized. after standardization the constraint is 35 characters so given [va.gov](http://va.gov/) is calling address validation, before it is sent, it is appropriate to be 35 chars
---
> Harrison, Thomas P: 
> Thanks Josh!  One more question - will the validation API ever return a suggested addressLine with more than 35 characters in length?  I just want to make sure that the validation response doesn't make an address line suggestion that is longer than what we'll allow the user to save in VA.gov.
---
> Lindsey, Joshua: 
> funny you mention that, i opened an internal issue where i was seeing a few examples of that happening.  Our target is that address validation should be complying  VAPROFILE-2446 as a reference.
---
> Harrison, Thomas: 
> Does VAPROFILE-2446 stipulate address line length?  Not sure what that is.
---
> Lindsey, Joshua: 
> It stiupulates that address-validation is returning candidate addresses that are longer than 35 characters.  If a consumer was to use exactly what came back from it, it will then fail when submitted to contact information.  That is the defect i've raised.
---
> Harrison, Thomas: 
> Ok.  So we have the following options in VA.gov...
>  1. Keep the validation length at 35 and wait until the validation service is updated to only return suggestions of 35 max.
>  2. Increase the validation length.
>
> Based on your previous comment, you're suggesting option 1 right?  Just making sure so I can update our ticket with the right info.
---
> Lindsey, Joshua: 
> i would keep #1 until we can guarantee the Veteran that what we validate works.

**Comment by tpharrison** [comment]
Should we move this to the backlog so we don't forget about it?

**Comment by mtcA6** [comment]
nope, whenever this happens we can create a new ticket, thanks for tracking this down.
