### ISSUE TITLE
ToU: Enable non-USiP Middle auth

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#63993]
## Description
To allow non-USiP applications using SSOe the ability to use middle auth where only a part of the authentication system is enabled.

## Tasks
- [ ] Change `redirect_url` => `ssoeTarget`
- [x] Ensure tests are updated
- [x] Ensure functionality works as expected
