### ISSUE TITLE
Identity Dashboard (FE) - Update the API environment

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#64003]
## Description
When navigating to the Identity Dashboard site (https://identity-dashboard-dev.vfs.va.gov/) when attempting to authenticate the Sign-in Service (SiS) API is pointing to `localhost:3000` instead of the SiS API for staging. Additionally, the Identity Dashboard BE API is pointing to `localhost:4000`.

## Tasks
- [ ] Update SiS hostname based on environment
  - [ ] Dev: `localhost:3000`, Prod: `staging-api.va.gov` (confirm with Riley)
- [ ] Update Identity Dashboard API hostname based on environment
  - [ ] Dev: `localhost:4000`, Prod: `https://identity-dashboard-dev-api.vfs.va.gov` (confirm with Riley)

**Comment by aparsley** [comment]
Keep up the good work!
