### ISSUE TITLE
Identity Dashboard (FE) - BDPR fix monitoring page

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#64000]
## Description
Update the Monitoring page so that it matches the Figma Prototype.
https://www.figma.com/file/rw8kJXf4VKliimoMpsEy4Q/Identity-Dashboard-(initial)

## Tasks
- [x] Add "showing {x} amount of logs"
- [x] Update the logs view
- [x] Update the Search term UI view
- [x] Update the Date Filters to use the following options: 24 hours, 7 days, 14 days, 30 days, and specific dates.
  - [x] Specific dates should open up the Date Picker where a user can select specific dates
  - [x] ^ See Sentry dashboard as an example of what we want to go for
- [x] Fix any outstanding bugs from the previous iteration
