### ISSUE TITLE
DR | Refactor 'MAX_LENGTH'

### ISSUE THREAD

**Issue by rocio-desantiago** [department-of-veterans-affairs/va.gov-team#64009]
## Value Statement

**_As a_** developer
**_I want to_** refactor the MAX_LENGTH so that it's clear which one is unique to HLR & SC and which one is shared.
**_So that_** tech debt is reduced and so that future developers don't have to look at multiple files to figure out which MAX_LENGTH is the correct value to use for an app.

## Background Context
Not all of MAX LENGTH is shared across all 3 apps. 
We previously moved it into a shared constants file but some of the values only apply to HLR. 
In this task, we will be renaming those so that it's clearly labeled `HLR_MAX_LENGTH`, `NOD_MAX_LENGTH`, and `MAX_LENGTH` for what is shared.

- The following files will be refactored:
  > src/applications/appeals/shared/constants.js
  > src/applications/appeals/10182/constants.js
  > src/applications/appeals/996/constants.js
  > src/applications/appeals/995/constants.js

## Out of scope
* Other apps/forms not in Decision Reviews

## Tasks

- [ ] const variables renamed
- [ ] Unit tests updated
- [ ] E2E tests updated
- [ ] Forms functionality has not changed

## Definition of Ready 

- [x] Have access to decision reviews folder (src/applications/appeals/{appName}/utils) in vets-website repository 
  > 995 - Supplemental Claims (src/applications/appeals/995/utils)
  > 996 - Higher Lever Review (src/applications/appeals/996/utils)
  > 10182 - Notice of Disagreement (Board Appeal) - (src/applications/appeals/10182/utils)

## Definition of Done

- [ ] Functionality not changed
- [ ] MAX_LENGTH easier to read for front-end development

**Comment by HeatherWidmont** [comment]
@rocio-desantiago breaking this down into 4 separate PRs. Afterwards @data-doge can review after their class this evening. Thanks team!!

**Comment by saderagsdale** [comment]
@rocio-desantiago Can you confirm if all 4 PRs have been broken down? @data-doge Have you reviewed?

**Comment by Mottie** [comment]
Code has been merged in and verified.
