### ISSUE TITLE
Deploy test ephermal cluster

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#64016]
```[tasklist]
### Tasks
- [ ] Modify existing terraform to spin up new ephemeral cluster
- [ ] Deploy Vets API stack/helm chart
- [ ] Deploy Vets Website to cluster
- [ ] Determine how the shared s3 bucket works
```

**Comment by ben-allen-oddball** [comment]
* vanilla cluster works with new VPC.
* existing Dev VPC tier lacks the required tags (solved)
* existing Dev VPC lacks external accessable subnets
  * Workaround is to annotate the service to internal, however this does not expose the service to the world.

End of Day notes:
* Create a review environment VPC with subnets.
  * Name must match pattern: dsva-vagov-review-vpc
* Create a new tier in platform distro for review
* Deploy test cluster in review tier
* Deploy Ingress Controller to review Tier
* Document

**Comment by ben-allen-oddball** [comment]
Created Cluster Deploy Instructions:
https://github.com/department-of-veterans-affairs/prt-tf-repos/tree/WIP

Created Repo Deployment Terraform:
https://github.com/department-of-veterans-affairs/prt-tf-repos/tree/WIP

Created Terraform State Management for PRT:
https://github.com/department-of-veterans-affairs/prt-tf-state

**Comment by ben-allen-oddball** [comment]
Added github action pipelines which auto plan on tf-state and tf-repos.

**Comment by ben-allen-oddball** [comment]
ToDo:
* Add AWS_ASSUME_ROLE vars to action pipeline
* Setup auto Apply on merge to main
* Setup semantic versioning

**Comment by ben-allen-oddball** [comment]
hand jammed http://vagov-next-ben-cluster.vfs.va.gov:9999/ in.  Need to add to the ALB deploy.

Added PoC for matrix of environments for Github action support of multiple TF workspaces.
https://github.com/department-of-veterans-affairs/prt-tf-preview-clusters/blob/WIP/.github/workflows/tf-plan-pr..yml#L7-L12

**Comment by ben-allen-oddball** [comment]
Future for dynamic matrix https://www.jacobbolda.com/dynamic-matrix-jobs-in-github-actions

**Comment by ben-allen-oddball** [comment]
Need to add default tags.

**Comment by ben-allen-oddball** [comment]
Add default tags to all TF repos.
