### ISSUE TITLE
Stub out an ingress controller

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#64017]
```[tasklist]
### Tasks
- [ ] Stub out an ingress controller
- [ ] Create a load balancer
- [ ] Create dns entries (Route 53)
- [ ] Create an automatic certificate
- [ ] Add inbound ACL for limited IP addresses
```
