### ISSUE TITLE
[UX][Design] Identify and prioritize components for Design System v.3 transition

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#64010]
## Background

Many of the components the VA shares with the USWDS have been synced to the design, styling, and functionality of the US System while retaining elements necessary to the VA. Though there is no deadline for the switch at this point, the Design System team is strongly recommending that teams make the change soon. 

- [Design system library v3](https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4/symbols)
- [Instructions for how to download v3 Sketch library](https://design.va.gov/about/designers/design-libraries#add-the-component-symbol-library-to-your-project)
- [DS website](https://design.va.gov/components/)

_Note: Not all components have new versions yet. Components that have been converted are marked with a badge USWDS V3 at the top of their component page._
<img width="117" alt="Screenshot 2023-08-21 at 3 24 33 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/79372956/cd2ed917-4a69-46b3-be27-71238f8623fa">

**UX steps for the overall transition:**
1. Download library
2. Identify/prioritize components
3. Switch/update components (1 or 2 at a time)
4. After each component is updated, let FE know so they can update that component in code. 

**This ticket covers Step # 2.**

## Tasks
- [ ] Download/add new Sketch library
- [ ] Evaluate Sketch files and symbols to identify components that have new v3 versions and will need to be updated 
- [ ] Determine order of priority for components (will tackle 1 or 2 components at a time)
- [ ] Create f/u tickets for next steps (1st components)

## Acceptance Criteria
- [ ] All components identified and prioritized in this ticket
- [ ] F/u tickets made for first set of components

**Comment by cgednalske** [comment]
@loripusey -- this ticket outlines the steps we'll need to take to transition to version 3 of the Design System, which is mostly on UX to do and can be tackled whenever we're ready. 

After this initial ticket to identify and prioritize the components, they can be updated one or two at a time and spread out however we prefer. No official deadline at the moment, though teams are encouraged to do this soon. 

cc @benbrasso-agile6

**Comment by loripusey** [comment]
I'll add it to the sprint goals and we can refine today

**Comment by zach-park** [comment]
Here is the latest (ongoing) Mural document for the DS V3:
[https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffair[…]589b920bfdb9d21ef43d18077d420?sender=uff786461dfce1a1982aa7640](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1693238858829/38780b4f738589b920bfdb9d21ef43d18077d420?sender=uff786461dfce1a1982aa7640)

**Comment by benbrasso-agile6** [comment]
Don’t forget we have our own simplified header and footer, which we built and I think Matt was iterating on it. Don’t know how far we got yet. E.g., to get the sign in link back out of the header and he wanted to add a section title in the header.

**Comment by cgednalske** [comment]
@benbrasso-agile6 oh that's funny - I JUST asked about this exact thing in our [thread](https://dsva.slack.com/archives/C04J6H2LYUU/p1693510936213889). Sounds like more discussion is needed around this one and it wouldn't be one that's ready to switch yet.

**Comment by benbrasso-agile6** [comment]
Right. I mean, we could switch to it, so long that we edit it again to be simplified versions and resubmit as experimental. Prolly worth chatting with our FE team about header and footer.

**Comment by cgednalske** [comment]
Ya it definitely makes sense to wait for now and have those convos with our team and maybe the DS team to see if they have any intentions for it already! 👍

**Comment by benbrasso-agile6** [comment]
@zach-park @cgednalske is this ticket ready to close?

**Comment by cgednalske** [comment]
I think we'll just need to update the mural board first to reflect what we know about head/footer now 👀  @zach-park other than that, anything else that needs to happen for this ticket before closing?

**Comment by benbrasso-agile6** [comment]
k cool, will leave this in "in progress" then

**Comment by benbrasso-agile6** [comment]
Could you also move that mural into this folder? https://app.mural.co/t/departmentofveteransaffairs9999/r/1675718737504?folderUuid=598500ff-acfd-4470-88cd-b10f59aa46c7

**Comment by zach-park** [comment]
Simplified Header / Footer are captured in the Mural board. And the board is moved to the VA space (VA Rooms > Appointments (UAE) > Check-in- incl. Pre-Checkin > Features > Design system v3 transition).

**Comment by benbrasso-agile6** [comment]
Nice. @cgednalske you want to give it a final look and close?

**Comment by cgednalske** [comment]
I'm still seeing the header/footer in the list of components that were updated and in the priorities list. @zach-park could we update those? Or am I not seeing the right version? 👀

**Comment by zach-park** [comment]
Instead of changing it. I added it to the removed section actually. Also added it to the priority (1) item

**Comment by benbrasso-agile6** [comment]
I thought header/footer is not the priority?

**Comment by cgednalske** [comment]
Ya I think we just need to remove all mention of the header/footer from the board and priority section? I don't think they removed it, just haven't addressed it yet for v3. 
Sounds like there will still be other components/patterns that they'll incorporate, so the Mural board might have to be a work in progress for us that's updated whenever they add new stuff 👀  What do you think, @zach-park

**Comment by zach-park** [comment]
> Could you also move that mural into this folder? https://app.mural.co/t/departmentofveteransaffairs9999/r/1675718737504?folderUuid=598500ff-acfd-4470-88cd-b10f59aa46c7

Here is the direct link to the DS v3 transition mural:  https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1693238858829/38780b4f738589b920bfdb9d21ef43d18077d420

**Comment by zach-park** [comment]
> Ya I think we just need to take out all mention of the header/footer from the board and priority section? I don't think they removed the components, just haven't addressed them yet for v3. Sounds like there will still be other components/patterns that they'll incorporate, so the Mural board might have to be a work in progress for us that's updated whenever they add new stuff 👀 What do you think, @zach-park

Added the above comment in the mural priority table section.

**Comment by cgednalske** [comment]
Sounds good 👍 Thanks @zach-park! I think we can close then.
