### ISSUE TITLE
[FE] My VA Health care: remove instances of feature toggle for Appointments link update

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-team#64024]
## Background
We updated the "Schedule and manage appointments" link from **/health-care/schedule-view-va-appointments/appointments** to **/my-health/appointments** in [this pull request](https://github.com/department-of-veterans-affairs/vets-website/pull/25308).

This work is behind the `va_online_scheduling_breadcrumb_url_update` (i.e. `vaOnlineSchedulingBreadcrumbUrlUpdate`) feature flag (created by the Appointments team). Once the Appointments team launches this to prod, we should clean up and remove instances of this feature flag to prevent code bloat.

---
## Tasks
- [x] remove all instances of `vaOnlineSchedulingBreadcrumbUrlUpdate` and `va_online_scheduling_breadcrumb_url_update` feature toggle within the **/dashboard/** directory only (we don't own this feature toggle)
  - [x] mock server
  - [x] unit and e2e tests
  - [x] within components

## Acceptance Criteria
- [ ] all mentions of the above feature toggles are removed

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ dev or PM
- _How can this work be validated?_ search entire /dashboard/ codebase and make sure no instances of the feature flag shows up

## Resources
- [Pull request](va_online_scheduling_breadcrumb_url_update) to update the appointment link
- Update "schedule and manage your appointments" link [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63401)
- My VA support of MHV migration [epic](https://github.com/department-of-veterans-affairs/vets-website/pull/25308/files)
- [Slack convo](https://dsva.slack.com/archives/CMNQT72LX/p1691599254441649)

**Comment by allisonlu** [comment]
@ajakabcin 

Ready for validation! Since we don't own this feature toggle, we can confirm that the [`va_online_scheduling_breadcrumb_url_update` feature toggle](https://staging-api.va.gov/flipper/features/va_online_scheduling_breadcrumb_url_update) is still on, but we're able to see the new appointment link in the following scenarios:

1. user with appointment - Next appointment card
2. user with no appointment - CTA link
3. error state

**Comment by ajakabcin** [comment]
Thanks @allisonlu !
