### ISSUE TITLE
[Development] Implement HLR redesign

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#6402]
## User Story or Problem Statement

As a front-end developer, I need to update the Higher-Level Review form so it matches the new design.

Design doc: https://vsateams.invisionapp.com/share/W5U21BDFTQK#/screens/404075470

## Goal

Update the front-end implementation to match the design; which was updated to meet the new requirements. This includes removing entries that no longer apply to the form. 

## Objectives or Key Results this is meant to further

- Complete tasks
- Design & implementation match

---
## Tasks
- [x] Update gating wizard (as needed)
- [x] Update introduction page content
- [x] Update contested issue cards (add/remove disposition and/or rating percentage)
- [x] Remove legacy opt-out checkbox
- [x] Remove contest issue additional notes
- Review page
  - [x] Hide empty address line 2 entry
  - [x] Remove review cards
  - [x] Update contested issue title section
  - [x] Combine informal conference times into one line

## Acceptance Criteria

- [ ] All tasks completed & match design
- [ ] Open a ticket to ensure schema changes are in sync

**Comment by Mottie** [comment]
Progression towards completion:
- [x] Remove old HLR redirect - https://github.com/department-of-veterans-affairs/vets-website/pull/11874
- [x] Fix HLR Introduction page reload - https://github.com/department-of-veterans-affairs/vets-website/pull/11893
- [ ] Add `uiSchema` option to hide empty review rows - https://github.com/department-of-veterans-affairs/vets-website/pull/11908
- [ ] Complete redesign update (in progress)
