### ISSUE TITLE
[LH Migration] Set up logging for LH rate limits

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#64027]
## Background
We don't currently have anything in place to alert us when we get close to hitting the LH API rate limit. We need to set up logging to send logs to DD when we are close to hitting the rate limit so that we can request that they increase it.

## Notes
* Each LH API has a different rate limit, so we need to be able to keep track of the limits across the different APIs that we consume (i.e. Benefits Claims has a rate limit of 12000 req/min, Letters Generator has a rate limit of 400 req/min)
* LH sends us headers on every request that indicate the total limit as well as the remaining number of requests before the limit is reached
  * If the limit is 400 and we have made 2 requests since the last time the limit was reset, then the 7 headers would be:
    1) `Ratelimit-Limit`: **400**
    2) `Ratelimit-Remaining`: **393**
  * Based on this, we should be able to determine what percentage of the rate limit has been consumed and log a message to DD whenever our threshold has been exceeded
* Two approaches that we have considered so far:
    1) Create a utility class / function that we can use with all of the different LH services
    2) Abstract the shared logic from the different configurations into a 'base' configuration and then extend the configuration where needed

## Open Questions
1) What is the threshold that we should alert at (90% maybe?)?
2) Does the log message need to have a specific structure in order for us to set up a monitor against it?

## Tasks
- [ ] Update the vets-api code to check the headers for each request and send a log to DD when the threshold has been exceeded

## Acceptance Criteria
- [ ] There is a log being sent to DD whenever we consume a predetermined percentage of our rate limit
- [ ] This log can be used to create a DD monitor so we can be alerted via slack / email
