### ISSUE TITLE
[bug] NOD | Investigate & fix submission error

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#64039]
## Value Statement
**_As a_** Veteran
**_I want to_** submit my Notice of Disagreement form
**_So that_** I can get a decision

## Background Context

While checking Datadog session replays, we encountered a Veteran stuck trying to submit a NOD form. After clicking on the submit button, the button remained gray and according to [Datadog a JS error](https://vagov.ddog-gov.com/rum/replay/sessions/36985d0c-c498-4074-8381-a6cbd33c0426?event=AgAAAYoZoOLDNu8pFwAAAAAAAAAYAAAAAEFZb1pvT1FPQUFBc1NZcENsbmVLdmdBSAAAACQAAAAAMDE4YTE5YTItM2E4OC00YzZmLTljYzYtMjRjYjNmMzI0NWY0&p_tab=attributes&seed=ce3501ce-75e3-4524-90e4-337a5096a7ec&ts=1692644104596) occurred preventing submission of the form. The actual Datadog error was not enlightening, but we were able to get the save-in-progress ID from the replay.

The data itself did not appear to be malformed, so a search for errors in Sentry lead us to an [`e.replace is not a function` error](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?field=message&name=Notice+of+Disagreement&project=4&query=%28+url%3A%2Adecision-reviews%2Fboard-appeal%2Frequest-board-appeal-form-10182%2F%2A+OR+url%3A%2Anotice_of_disagreement%2A+%29+level%3Aerror+AND+message%3A%22e.replace+is+not+a+function+TypeError+%2Fgenerated%2F10182-board-appeal.entry.js+Vx+Vx%28generated%2F10182-board-appeal.entry%29%22&sort=-message&statsPeriod=7d&widths=-1) which may be the culprit.

Further investigation is needed to determine if this is actually the error preventing submission, and which data field may have potentially caused this error and to fix it.

## Tasks
- [ ] Search save-in-progress data (contains PII) for values that may lead to a submission error
- [ ] Fix error
- [ ] Test data submission
- [ ] Add tests

## Acceptance Criteria
- [ ] All tasks complete
- [ ] All tests passing
- [ ] Confirm by sharing mock data for testing in staging

**Comment by saderagsdale** [comment]
Robin is waiting to hear from profile team to complete refinement.

**Comment by Mottie** [comment]
Opened a PR to get around the `e.replace is not a function` error. Still waiting on profile assessment.

**Comment by HeatherWidmont** [comment]
Started on August 20th, 15 errors in 4 days, & then have not seen the problem since
