### ISSUE TITLE
[UX] Update Content to Clarify Travel Eligibility

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#64036]
## Background
After meeting with Megan Hewit, she expressed concern about the verbiage we came up with is going to cause more problems and complaints. She would like us to add this verbiage instead so that the Veteran can determine for themselves if they should file (at least until we can determine programmatically whether they are eligible):

> Who is eligible for BT?
   > Veterans with disabilities rated 30% or more service-connected (SC): travel for care relating to any condition
   > Veterans with disabilities rated less than 30%: travel for care relating to their SC condition(s)
   > Veterans receiving VA pension benefits: travel for care of any condition
   > Veterans with annual income below the maximum applicable annual rate of pension: travel for are of any condition.
   > Veterans traveling in relation to a Compensation and Pension (C&P) Examination

She would rather Veterans not file if they are not eligible and NOT be encouraged to file just to find out they are not eligible.

## Tasks
- [ ] Update the content based on Megan's input
- [ ] Run content by Danielle
- [ ] Run the new wireframe by Megan
- [ ] Attach the new wireframe to the work ticket #63931
