### ISSUE TITLE
[UX] Revisit Content & Wireframes

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#64040]
## Background
After meeting with Megan Hewit, she expressed concern about the verbiage we came up with is going to cause more problems and complaints. She would like us to add this verbiage instead so that the Veteran can determine for themselves if they should file (at least until we can determine programmatically whether they are eligible):

> Who is eligible for BT?
>    - Veterans with disabilities rated 30% or more service-connected (SC): travel for care relating to any condition
>    - Veterans with disabilities rated less than 30%: travel for care relating to their SC condition(s)
>    - Veterans receiving VA pension benefits: travel for care of any condition
>    - Veterans with annual income below the maximum applicable annual rate of pension: travel for are of any condition.	
>    - Veterans traveling in relation to a Compensation and Pension (C&P) Examination

She would rather Veterans not file if they are not eligible and NOT be encouraged to file just to find out they are not eligible.

## Other things that must be true
- You’re traveling for care at a VA health facility or for VA-approved care at a non-VA health facility in your community.
- And at least one of these must also be true:
  - You have a VA disability rating of 30% or higher, or
  - You’re traveling for treatment of a service-connected condition, even if your VA disability rating is less than 30%, or
  - You receive a VA pension, or
  - You have an income that’s below the maximum annual VA pension rate, or
  - You can’t afford to pay for your travel, as defined by our guidelines, or
  - You’re traveling for one of these reasons: A scheduled VA claim exam (also called a compensation and pension, or C&P, exam), to get a service dog, or for VA-approved transplant care

## Tasks
- [ ] Update the content 
- [ ] Update the wireframes
- [ ] Run content by Danielle (most familiar with travel) and/or Laura
- [ ] Run by Mark & Megan Hewitt

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 The content here about eligibility was reviewed by Danielle with the Veteran Program Office like early this year. So, that should all be accurate. Of course, double check with CAIA when you need to.

**Comment by benbrasso-agile6** [comment]
Don't think these are super relavent, but just wanted to share the content that used to be in the kiosks. 

<img width="579" alt="Screen Shot 2022-09-13 at 10 19 09 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/101129355/99dd6de3-7045-4b74-a42f-42079d470e7d">
<img width="620" alt="Screen Shot 2022-09-13 at 10 18 57 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/101129355/eb3e3e06-03df-4e43-aa4c-0b30fe581fb6">
<img width="657" alt="Screen Shot 2022-09-13 at 10 17 47 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/101129355/a1ed5e50-0dfa-45af-9d33-728597a83e6b">
<img width="585" alt="Screen Shot 2022-09-13 at 10 17 19 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/101129355/0b8811c8-f830-4495-b5af-68250e86bde5">
<img width="578" alt="Screen Shot 2022-09-13 at 10 16 44 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/101129355/f443cece-9f2d-4345-9f8b-bf81e2dc06d2">

**Comment by kellysmith1008** [comment]
[I've drafted the first version of the content](https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/p/7E86A6F3-17F3-4807-83FE-C11BCF9E5E07/canvas) - @ytsaoca I left some comments in the file about types of components I think we could use to mock this up. If you want to work on mocking this up today, we can meet later this afternoon, or tomorrow or Monday to go over. Once it's mocked up, we can send it to Danielle, Mark, and Megan to get an initial round of feedback. @loripusey when we get the final approval, do you want us to create a FE ticket for the work or does one already exist?

**Comment by loripusey** [comment]
there is already a [FE ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63931), we just need to add the link to the final sketch file to it

**Comment by loripusey** [comment]
also, when we put the link in the FE ticket, can someone ping @lee-delarm6 to let him know his FE ticket is unblocked? thanks

**Comment by kellysmith1008** [comment]
Oh perfect - I'll make sure we add the link to the FE ticket and ping Lee - thanks!!

**Comment by benbrasso-agile6** [comment]
Nice quick work. Thanks for making this a priority @kellysmith1008

**Comment by ytsaoca** [comment]
@benbrasso-agile6 
I decided to use additional element after discuss with @kellysmith1008 . 
Do we tag 
Here are the wireframes:
Closed - https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/bLoKww0
Open - https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/Wd43zzK

**Comment by benbrasso-agile6** [comment]
Looks great. Nice work @ytsaoca and @kellysmith1008 . And, great job prioritizing this too. I left a couple comments, super minor. Are we planning to toss it in front of Laura or Danielle next?

**Comment by loripusey** [comment]
Sent email to Megan with a screenshot of the "open" one.

**Comment by ytsaoca** [comment]
At the design sync, we decided to put the additional info under the Lead body text content.

**Comment by benbrasso-agile6** [comment]
LGTM ty

**Comment by loripusey** [comment]
@kellysmith1008 is this good to close now?

**Comment by kellysmith1008** [comment]
Yes ma'am - I think we're all set!
