### ISSUE TITLE
[Congressional] V10742207 - Issues with verification of identity for Myhealthvet (Congressman Johnson) Due 9/29/23

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#64043]
## Issue Description
Veteran's sister has been appointed legal guardian to take care of her, and has been trying to get access to her sister's myhealthvet account. The VA instructed her to log into ID.me to verify her sister's identity, and when she did she received a message saying, the email connected belongs to another person.

https://dvagov.sharepoint.com/:f:/s/DigitalExperiencePMOInternalFTC-PrivateOCTO-DEActions/Em4tiwUXyXxOrpLuDQmFgScBF77T3SJr9sNuR2gHT28-dw?e=VF4I6C 
---
## Tasks
- [x] Review congressional correspondence
- [ ] Notify Veteran and congressional correspondence channel of solution. 
- [ ] Veteran issue will be resolved or responded to with final answer to issue.
- [ ] Congressional Correspondence will receive details of the resolution.

## Acceptance Criteria
- [ ] Veteran issue will be resolved or responded to with final answer to issue 
- [ ] Congressional Correspondence will receive details of the resolution 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
@Kimberley2023-CSM reached out to ID.me today to review the case.

**Comment by clantosswett** [comment]
Response from ID.me re: this issue: 

_VA has been attempting to resolve an issue for this Veteran since November 2022. The Veteran has a court appointed legal guardian (Veteran’s sister), who is attempting to get an ID.me account for the Veteran in order to ensure the Veteran has access to VA benefits.

1. The sister (Veteran’s POA) has a verified ID.me account (LOA3).
2. The Veteran has an active, unverified ID.me account.
3. The Veteran has attempted to verify four times, and has been unsuccessful three of those times, and abandoned one attempt.
4. For the Veteran to verify her identity with ID.me, she will need to verify via ID.me’s Trusted Referee process.
5. A family member may assist the Veteran on the call, but will need to be in the same room as the Veteran.

Ask of VA: Is there an internal process for the sister to complete the relevant POA forms in order to access the Veteran’s accounts and benefits with her (Veteran’s POA) own verified ID.me account?_

**Comment by Kimberley2023-CSM** [comment]
@clantosswett have you reached out to you POC from Identity team?  If not, I can contact Joe N.

Also, [update from Slack](https://dsva.slack.com/archives/C02BS78NYRM/p1694095496258969?thread_ts=1692627466.154669&cid=C02BS78NYRM).

**Comment by clantosswett** [comment]
@Kimberley2023-CSM there is not an internal process to give a POA access to a veteran's account. If the user is not able to create their own identity verified account, we do not have a way to establish a myhealthevet account for the user.

**Comment by ATMiddleton** [comment]
@Kimberley2023-CSM @ATMiddleton will create a process to resolve during this sprint.

**Comment by clantosswett** [comment]
We received notification back from MHV that the user's MHV account was upgraded to a premium account and that the POA now has access to it. This does not solve the problem of the user being able to create an ID.me account. It is unlikely that can be fixed because ID.me does not have a process for working with POAs for access to accounts. But we will reach out to double check on the issue given the information received from MHV and see if there is anything that can be done.

**Comment by clantosswett** [comment]
Sent an email to the veteran legal guardian to determine what issues remain.

**Comment by clantosswett** [comment]
We heard back from the veteran's sister and there don't seem to be any remaining issues. She had concerns and issues regarding the process for completing the verification process using ID.me given her sister's condition. I told her I would report that feedback, in addition to checking with the identity team to clarify whether starting in December, users will also need to have an id.me account starting in December. But overall, this issue can be considered closed.
