### ISSUE TITLE
[UX] Create pros and cons of ideas on how to evolve travel

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#64050]
## Purpose
To determine the highest value vs. general feasibility of ideas for how to evolve travel in check-in.

## Description

We've discussed different options for submitting BT and expanding it in the past. Those options have included: 

- Post-visit standalone web app with LoROTA (sort of inspired off of PCI). E.g., maybe accessed through a post-visit text reminder. 
- Standalone web app that can be accessed 24/7 similar to https://www.va.gov/claim-or-appeal-status/. Which, I think this is their sketch file. Might need to double check with Kristen McConnell or Mark Dewey - https://www.sketch.com/s/d8594ef0-5efd-4a48-aa7a-baa3cb056482. Might need to figure out if this should/would want to be full auth vs. LoROTA. 
- Change eCheck-in user flow to check in > complete > want to file for travel? > complete. 
- Change eCheck-in user flow to ask the Veteran if they'd like to file now or immediately after check in is complete. 
- Add BT submission into VSE and/or VSE-CS for MSAs to file on behalf of Veteran. 
- Or, expand on what we have in eCheck-in. E.g., able to submit receipts, able to submit for public transportation, etc. 
- Asynchronous Claim Submission (e.g., no API latency)

## Tasks

- [x] Set up a structure for information about each idea in Mural (make space for insights from past materials)(Christina)
- [x] Review all related materials & add summary in the Mural (Ben)

[Prioritization of features and ideas](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1691694352663/51d6b8bc5d8394bf8466fa0c4523a54a3ad24483?sender=ud3aa760e30b39bcf436d4473 
) (Done)
[User flow options as a result of API latency](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677531401756/f2ecd191cf691044fb11f57fe3398b91ad4dbc82?sender=u37bb983bd3fc3cc00c7d3286) (Done)
[MVP pros and cons presentation](https://docs.google.com/presentation/d/1V1y0JiqRv_wWMqQvmBi4GiMJ0UBwapJknZBpdSI6oAs/edit#slide=id.g892adcb623_0_141) (Recommendation of post-appt experience got nixed because Stephen imagined it would be easier and quicker to market for us to include within the existing eCheck-in flow, which no one disagreed with.) (Done)
[Early user flows that were explored](https://www.sketch.com/s/42a478e7-cb38-49e5-9500-9b21182873da/p/552EBE6C-AE8A-440B-A977-78EAF354D73B/canvas) (Done)
[Review 18F final recommendations presentations](https://drive.google.com/drive/folders/1r2yIMcN7s-iQq0irwViUHlHbiouBzcR_) (Done)
[Discovery conversations and notes in Git](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/discovery/travel-reimbursement) (Done)
[Texas Valley interview notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/discovery/travel-reimbursement/tx-valley-interview-notes.md) (Done)
[Bay Pines interview notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/discovery/travel-reimbursement/bay-pines-interview-notes.md) (Done)

- [x] Drop in ideas into mural and have discussion about which we want to pursue further (all of us, set up a meeting)

- [x] Ask Ben Williams and Daryl Richardson (probably over email or Teams) for rough breakdown % of different types of BT claims. (I'm not sure we have them all documented.) E.g., public transportation. And, ask if any of those types need pre-approval. If so, when and how does that pre-approval work? The goal here is to simply better understand the landscape of BT to help evolve access to easily filing a BT claim. (There might be some information in these documents to help inform the questions we need to ask. Some questions might have already been answered in these documents: [Notes from discussion with Bay Pines travel office](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/discovery/travel-reimbursement/bay-pines-interview-notes.md) and [Notes from Texas Valley travel office](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/discovery/travel-reimbursement/tx-valley-interview-notes.md).) (Does not have a dependency.) (First thing to do, is to draft the questions.) (Ya-ching)

- [x] Talk to After Visit Summary team (Kristen McConnell) about what they've been working on. E.g., user flows, designs, etc. The cross-over with AVS is that travel pay also happens "after the visit." So, we need to check their plans for design and if they're planning to do a post visit text message. For example, it could make sense that AVS and submitting a BT claim are a combined text message (in the future). (Does not have a dependency.) (Ya-ching, set up for all of us.) 

- [x] Select a few ideas to document pros and cons and value vs. feasibility. (Ben first, then have a meeting with everyone)

Document pros and cons of each and identify whether it's inclusive to blind and low vision Veterans. (Probably [similar to this style of presentation](https://docs.google.com/presentation/d/1V1y0JiqRv_wWMqQvmBi4GiMJ0UBwapJknZBpdSI6oAs/edit#slide=id.g892adcb623_0_141).) 

A con could be level of complexity, but we're not looking to dig-in with engineering right now. These are ideas to help OCTO make decisions. Potentially, have 1 or 2 recommendations from that list of ideas to proceed with based on, 1) how many Vets does this impact, 2) ease of use for Veteran (best guess), 3) inclusion of blind and low vision population, etc. Potentially have a column in the pros and cons table to discuss with other teams would need to be involved outside of PCI. Again, we don't know what solutions or teams would work on this. It's a quick analysis to present to OCTO. 

- [x] Run an early draft by Mark Dewey to see if he has anything coming from the BTSSS side that might impact the options or add to them. (Ben to set up, but everyone included.) 

## AC

- [x] Read through previous documentation
- [x] Discussed with Ben Williams and AVS team 
- [x] Create pros and cons presentation 
- [x] Run draft by Mark Dewey

**Comment by zach-park** [comment]
@zach-park

**Comment by benbrasso-agile6** [comment]
Team chatted. Next meeting to review progress is next Tuesday afternoon.

**Comment by benbrasso-agile6** [comment]
@ytsaoca I added two documents in your task above to review that might be helpful

**Comment by ytsaoca** [comment]
@cgednalske @benbrasso-agile6  I drafted some questions for Ben Williams and Daryl Richardson. Feel free to give feedback or edit the document. 
https://docs.google.com/document/d/1TFeDysBH_16IfoV6HEsTwJLz4Z7603CRoxCEXwDR4bQ/edit?usp=sharing

**Comment by benbrasso-agile6** [comment]
@ytsaoca I set up a meeting with Kristen. Hers and my available were sparse this week, so I wanted to get something scheduled quickly.

**Comment by ytsaoca** [comment]
@benbrasso-agile6 , Thanks for setting up the meeting with Kristen. 
I created a document for questions and meeting notes: https://docs.google.com/document/d/1lfhtmi9qCHOF4Wkl5V348W0Ua8tzw88MJDR4U8gFVHM/edit?usp=sharing
Feel free to edit!

**Comment by ytsaoca** [comment]
@benbrasso-agile6 , Thanks for setting up the meeting with Kristen. 
I created a document for questions and meeting notes: https://docs.google.com/document/d/1lfhtmi9qCHOF4Wkl5V348W0Ua8tzw88MJDR4U8gFVHM/edit?usp=sharing
Feel free to edit!

**Comment by benbrasso-agile6** [comment]
Thank you, thank you!

**Comment by benbrasso-agile6** [comment]
@ytsaoca feel free to kick off our meeting with Kristen tomorrow :)

**Comment by benbrasso-agile6** [comment]
Emailing daryl and ben in a moment - https://docs.google.com/document/d/1TFeDysBH_16IfoV6HEsTwJLz4Z7603CRoxCEXwDR4bQ/edit

**Comment by benbrasso-agile6** [comment]
Will work on scheduling with OCTO

**Comment by benbrasso-agile6** [comment]
@loripusey want to validate? https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1692898808732/d9ae369abf85caa6afdc24b2743dba0989171eee?sender=u37bb983bd3fc3cc00c7d3286

**Comment by benbrasso-agile6** [comment]
Sent DM to Kay about presenting

**Comment by loripusey** [comment]
discussed with Ben

**Comment by benbrasso-agile6** [comment]
@loripusey take a look at matrix changes https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1692898808732/d9ae369abf85caa6afdc24b2743dba0989171eee?sender=u37bb983bd3fc3cc00c7d3286
