### ISSUE TITLE
Discuss Cert Renewal Process to Enhance in Future

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#64058]
## Description 
_Have a discussion and document it around cert renewals, how they work, how many we currently have, and how we can improve them in the future._

---

## Definition of Done

- Complete the below tasks

## Tasks 

- [ ] Create a calendar invite to meet with Clint, Jason and Tier 1
- [ ] Document the call and action items
- [ ] Create documentation around Cert Renewal process moving forward
- [ ] Add work to the roadmap

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Resolved in the following thread:

https://oddball.slack.com/archives/C05NSM15WTG/p1692722398704859

No longer the responsibility of Platform Support. Closing.
