### ISSUE TITLE
Remove old public certificate settings

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#64062]
# Issue Description

Cleanup PR for #54884. 

# Tasks

## Devops & VSP Infra
- [x] remove `oauth_public_key` from devops repository
- [x] change `idme:oauth_public_key_url` to a hardcoded string in VSP Infra repository
  - [x] production change 
- [x] remove `idme_oauth_public_key` link from VSP Infra repository
  - [x] production change
 
## AWS PS & Secret removals
- [x] /dsva-vagov/vets-api/dev/idme/oauth_public_key_url
- [x] /dsva-vagov/vets-api/dev/idme/oauth_public_key
- [x] /dsva-vagov/vets-api/staging/idme_oauth_public_key_url
- [x] /dsva-vagov/vets-api/prod/idme/oauth_public_key_url
- [x] "/srv/vets-api/secret/idme_oauth_pub.pem"
- [x] "/srv/vets-api/secret/idme_oauth_prod_pub.pem"

**Comment by bramleyjl** [comment]
ID.me OAuth URL secrets in AWS PS have been removed. [One more PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2213) to remove secrets referencing locally saved ID.me public keys, then those keys themselves can be removed.

**Comment by bramleyjl** [comment]
Currently waiting for approval for https://github.com/department-of-veterans-affairs/devops/pull/13452
Slack thread: https://dsva.slack.com/archives/CBU0KDSB1/p1695652285460979
