### ISSUE TITLE
Update Product Artifacts for Release

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#64060]
## Description
Update various product artifacts, as necessary, based on the feature release.

## Tasks
- [x] Update the Pre-Check-in Product Guide, including content and screenshots, if necessary
- [x] Update the eCheck-in Product Guide, including content and screenshots, if necessary
- [x] Update user flow diagrams, if necessary ([Mural link](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677531124203/5edcfd3ea4b1eaf1ef082d56782a8b3291ef3932?sender=u37bb983bd3fc3cc00c7d3286)) (Ben)
- [ ] Update the Travel & Veteran FAQ
- [x] Send updated screenshots to Danielle Thierry for the Resources & Support (R&S) articles in VA.gov, if necessary
- [x] Create a Contact Center review ticket & schedule a review
    - [x] Put the link to the ticket in the main collab cycle ticket

## Acceptance Criteria
- [ ] Product Guides are up-to-date and ready to be published to Git
- [x] ALL screenshots are of the highest quality possible
- [x] [User flow diagrams are up-to-date](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/3Op54Vm) and ready to be merged in Abstract and pushed to sketch cloud
- [x] R&D articles are up-to-date (or scheduled for publishing)
- [x] Contact Center review has been scheduled

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 I added a link to the mural user flow for travel. If you need help with that one, just let me know.

**Comment by benbrasso-agile6** [comment]
Started to make changes to the [mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677531124203/5edcfd3ea4b1eaf1ef082d56782a8b3291ef3932?sender=u37bb983bd3fc3cc00c7d3286). Have a couple questions (you can see them as comments) out to Brian and Mark.

**Comment by benbrasso-agile6** [comment]
@loripusey take a look at those comments in the [mural user flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677531124203/5edcfd3ea4b1eaf1ef082d56782a8b3291ef3932?sender=u37bb983bd3fc3cc00c7d3286) and let me know what you think. I think Mark will have the answers, but just thought you might have responses too.

**Comment by loripusey** [comment]
Looks good to me

**Comment by benbrasso-agile6** [comment]
Mural updates are complete https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677531124203/5edcfd3ea4b1eaf1ef082d56782a8b3291ef3932?sender=u37bb983bd3fc3cc00c7d3286

**Comment by kellysmith1008** [comment]
Finished the product guide today but haven't published, yet. Will work in the Veteran and travel FAQ today

**Comment by kellysmith1008** [comment]
Ok, [Veteran travel pay FAQ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-guides/Check%20in%20FAQ.md) is updated - let me know if I need to change anything, please, @benbrasso-agile6 or @loripusey . The same (or very similar) information is in the product guides waiting to be published.

**Comment by benbrasso-agile6** [comment]
I left a few comments on your two commits. Let me know if they're too difficult to access and I'll toss them in here. Or.... if something doesn't sense.

**Comment by kellysmith1008** [comment]
Thanks, Ben! I'll take a look and make any changes!

**Comment by kellysmith1008** [comment]
Updated with your suggestions, @benbrasso-agile6

**Comment by benbrasso-agile6** [comment]
LGTM

**Comment by kellysmith1008** [comment]
Hmmm, I don't know if this is in your onedrive- I think we kept it in git so it was available to anyone. Let me check the initial ticket for the work real quick - if there is a onedrive link, it should be in there

**Comment by kellysmith1008** [comment]
Welp, I lied :D Here's the link: https://dvagov-my.sharepoint.com/:w:/g/personal/benjamin_brasso_va_gov/EbWC5IPc3UBIk7I9ZjLB53YBaCciLpuoVyYCPhvB5QmoZQ?e=oNpdic

**Comment by benbrasso-agile6** [comment]
Did you have a PDF version before? If so, I'll take that.

**Comment by benbrasso-agile6** [comment]
Or we might have uploaded it in Word? I'm not sure without jumping on the VA network.

**Comment by kellysmith1008** [comment]
Product guides have been updated. @benbrasso-agile6 We didn't do it in Word, I had started it in a Google doc and then transferred it to the git page. I think we can close this ticket
