### ISSUE TITLE
spike | FE | CICD | Discovery for Isolated App builds

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#64077]
## Background 
We want to reduce some of the complexity of what we've got going on in the profile and reduce the time it takes to build our pipeline and test everything. 

## Tasks 
- [x] review the imports and understand any complexies we'd have to work through 
- [x] for any 'exports' figure out the downstream impacts would be 

## Acceptance Criteria 
- [x] we are ready to pick up #43066 to isolate our app 
- [x] any additional tickets have been created and are ordered/organized (if applicable)
