### ISSUE TITLE
BE | Profile | Rating Info | Lighthouse production configuration

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#64089]
## Background
Ensure that rating-info is configured properly to call Lighthouse in production.

## Tasks
- [x] Verify (and update if necessary) the following production parameters:
  - [x] aud_claim_url
  - [x] rsa_key
  - [x] client_id
  - [x] host

## Acceptance Criteria
- [ ] Review any configuration changes with BE engineer
