### ISSUE TITLE
Document and communicate differences between Governance and CAIA

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#64087]
## User Story
As a VFS team member, I want to know how Platform Governance differs from Sitewide CAIA so that I know how I'm expected to receive support from both teams.

Assignee: @CherylEvans 
Peer Reviewer: @erinrwhite 

## Description
Both Governance and CAIA have received many questions lately asking the difference between CAIA and Governance. More specifically, if Governance provides support for content, IA, and accessibility, and CAIA also provides support for content, IA, and accessibility, then why do VFS teams need to meet with both teams and how does their role differ?

The goal of this ticket is to document Governance teams role vs. CAIA's role, add this information to the FAQ page, and then link the question and response from the CAIA touchpoint page.

## Impacted Artifacts
[Collaboration Cycle FAQ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/faqs) page

## Tasks
- [x] Create a documentation draft 
- [x] The heading should be the question, "What is the difference between Governance and CAIA?"
- [x] Document Governance team's role in a few short sentences, and then document CAIA's role in a few short sentences
- [x] Share with Shira and peer reviewer for review and feedback
- [x] Once Governance is in alignment, share with Terry Nichols and Lily Strelich in the #platform-collaboration-cycle channel on Slack and ask for their review and feedback (both Terry and Lily should have confluence access, however if not, please let Shira know).
- [x] Once CAIA team is in agreement, add question to FAQ page.
- [x] Once published on FAQ page, determine where in CAIA touchpoint doc the question should be linked (possibly under Objective?) Include the full question on the CAIA page and anchor link to question on FAQ page

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS teams understand the differences between Platform Governance and Sitewide CAIA

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
Draft created [Collaboration Cycle FAQ](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2752610305/64087+-+Cheryl+-+Copy+of+Collaboration+Cycle+FAQ) page.

**Comment by CherylEvans** [comment]
@shiragoodman @erinrwhite Please review and provide your comments and feedback. This is only my initial draft. :-)
Draft created: [What is the difference between Governance and CAIA?](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2751564355/64087+-+Draft+-+Cheryl+-+What+is+the+difference+between+Governance+and+CAIA)

**Comment by erinrwhite** [comment]
@CherylEvans I like this. As I was reading, I wondered if a comparison table might be a quick at-a-glance way for VFS teams to understand the differences?

|| Governance | CAIA |
|-|------------|------|
|**Goal**|Ensure that VFS teams are still on course and following VA.gov standards| Provide VFS teams with the information, tools, and resources needed to build exceptional veteran-facing products |
|**Role**| Advisory | Project support |
|**Timing**| Collaboration Cycle touchpoints| Continuous throughout project work|

**Comment by CherylEvans** [comment]
@erinrwhite I like this! A visual representation of the differences is much more effective. Let's run this by @shiragoodman and get her buy-in. :-)

**Comment by erinrwhite** [comment]
@CherylEvans excellent! Sounds like a plan. 👍🏻

**Comment by shiragoodman** [comment]
@CherylEvans @erinrwhite I'm a fan of this as well. It's definitely easier to consume and understand.. MUCH better than a block of text

**Comment by CherylEvans** [comment]
@shiragoodman @erinrwhite I added the table and left the text in [my draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2751564355/64087+-+Draft+-+Cheryl+-+What+is+the+difference+between+Governance+and+CAIA). The text introduces the table nicely.  It looked odd, with only a few lines of text and the table.
What are your thoughts?

**Comment by CherylEvans** [comment]
@shiragoodman @erinrwhite I wanted you both to take a final look at my [draft ](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2751564355/64087+-+Draft+-+Cheryl+-+What+is+the+difference+between+Governance+and+CAIA) before I send it to the CAIA designees.

**Comment by CherylEvans** [comment]
@erinrwhite @shiragoodman I sent Terry and Lily an invitation in the platform-collaboration-channel to view the draft and provide input:
"GM! I am working on a ticket to communicate to VFS team members how Platform Governance differs from Sitewide CAIA so they can better understand how they are expected to receive support from both teams. Here is a brief description of our efforts:
“Governance and CAIA have received many questions lately asking the difference between CAIA and Governance. More specifically, if Governance provides support for content, IA, and accessibility, and CAIA also provides support for content, IA, and accessibility, then why do VFS teams need to meet with both teams, and how does their role differ?
The goal of this ticket is to document the Governance team’s role vs. CAIA’s role, add this information to the FAQ page, and then link the question and response from the CAIA touchpoint page.”
Please review my draft “What is the difference between Governance and CAIA (Content, Accessibility, and Information Architecture)?” and provide your recommendations for improvements.
Let me know if you cannot view the Confluence page, and I will inform Shira. Feel free to let me know if you have any questions or concerns.
Thank you in advance for your input and recommendations! "
I think we are at a good point to receive recommendations and input from them.

**Comment by shiragoodman** [comment]
thanks, Cheryl! Let me know if you don't receive a response and I can give them a nudge.

**Comment by shiragoodman** [comment]
in addition, I also provided some comments on the draft. LMK if you have any questions.

**Comment by CherylEvans** [comment]
@shiragoodman Please give CAIA a nudge on this if you don't mind.  I want to finish this up in this sprint. :-)

**Comment by shiragoodman** [comment]
I did. I spoke to Terry on Friday. He wanted Danielle's opinion so we're waiting for her to take a look. I will nudge tomorrow if we don't hear anything by EOD.

**Comment by CherylEvans** [comment]
@shiragoodman This ticket will carry over into the next sprint

**Comment by CherylEvans** [comment]
@erinrwhite, I need your help, please. :-) For the last task (Once published on FAQ page, determine where in CAIA touchpoint doc the question should be linked (possibly under Objective?) Include the full question on the CAIA page and anchor link to question on FAQ page), 
I don't think the question and link belong in the Objective section. But I don't know what area makes the most sense.  Do you have any suggestions/insight from an IA perspective?

**Comment by erinrwhite** [comment]
@CherylEvans Gooooood question. Perhaps in the [Owner](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request#SitewideContent,Accessibility,andInformationArchitecture(CAIA)intakerequest-Owner) section, below or next to "Sitewide CAIA"?

**Comment by CherylEvans** [comment]
@erinrwhite I updated the [source page](https://vfs.atlassian.net/wiki/spaces/CC/pages/2124906551/Sitewide+Content+Accessibility+and+Information+Architecture+CAIA+intake+request).  What do you think? It is hyperlinked to the FAQ page, as directed in the tasks. This should work fine. Hopefully, @shiragoodman agrees! :-)

**Comment by erinrwhite** [comment]
@CherylEvans That looks good to me. 👍🏻 

I am also seeing one more tiny thing on the [FAQ page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/faqs#CollaborationCycleFAQ-HowcanIfindoutifmyteam%E2%80%99sinitiativeneedstogothroughCollaborationCycle?) that I should've caught when it was in draft: in the answer for the difference between CAIA and Governance, the break between paragraphs appears to be a line break rather than a paragraph break. The spacing above the "Sitewide CAIA partners..." is not the typical spacing that you see above a new paragraph (see the paragraph spacing on the [first answer](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/faqs#CollaborationCycleFAQ-HowcanIfindoutifmyteam’sinitiativeneedstogothroughCollaborationCycle?)).

Paragraph spacing in the Gov vs. CAIA answer:
![Screenshot 2023-09-15 at 1 21 19 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/ba6004cf-1243-4e76-99cd-5a45ca5067e7)

Paragraph spacing in the first answer:
![Screenshot 2023-09-15 at 1 23 55 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/3bdf79d3-4fe6-4284-abda-1e0c6150af6b)

**Comment by CherylEvans** [comment]
@erinrwhite I am trying to figure out how to fix this.  Before it was published, it looked correct. Now, it doesn't. Do you have any tips or tricks I can use to fix the formatting?

**Comment by CherylEvans** [comment]
@erinrwhite This should be good to go now that the spacing issue is resolved. Let me know if I am good to close. :-)

**Comment by erinrwhite** [comment]
@CherylEvans All set! 👍🏻
