### ISSUE TITLE
Update Full FSR UXPin

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#64090]
## Issue Description
Full FSR UXPin is still being used but has not been updated. This ticket ensures the Full FSR UXPin is updates to match staging
Make updates to [Full FSR UXPin](https://preview.uxpin.com/f43733391f52c409c4d3152e9a4b101a392e29df#/pages/161460690/simulate/sitemap)

---
## Tasks
- [ ] _Make relevant text updates that were made on the SW UXPin and staging_
- [ ] _Delete any outdated UXPins if not needed (investigate this)_

## Acceptance Criteria
- [ ] _All pages updated on Full FSR UXPin_

**Comment by HeatherRienks** [comment]
We have Figma now! Yay!
