### ISSUE TITLE
Design | Burial Form Redesign

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#64101]
## Issue Description
Redesign the digital burial 530 form to align with the latest paper version of the form.

---
## Tasks
- [x] Incorporate paper form updates into redesign
- [x] Highlight where changes have been made
- [x] Identify opportunities for improvement

## Acceptance Criteria
  - [x] All paper form changes are incorporated into the redesign
  - [x] Known pain points remediated
  - [x] a11y issues flagged
 
## Flows & Design
- [Burial future state flow (Mural)](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1691512530884/67e3bc6677c8d17cf6fc8848319a6e40ebced1af?wid=0-1694615398728)
- [Burial design (Sketch)](https://www.sketch.com/s/de782a35-e147-4c32-a2a8-ba53071ec8e7/p/61980607-BE54-4442-BC1A-DD3595F695FF/canvas)

**Comment by fiorella-io** [comment]
Added flows and design links

**Comment by fiorella-io** [comment]
Updates on step 2 after meeting with Julie S and Aliyah:

- We need to remove the copy that used to be below the [“Burial dates” title on Step 2](https://www.sketch.com/s/de782a35-e147-4c32-a2a8-ba53071ec8e7/a/OeYZRK2) 
- History of that content: It wasn’t in the existing form as a description. It would appear as a warning alert when someone entered a death year 2 years or more from the current date (see attached screenshot). CAIA wants to avoid conditional alerts on our midpoint review feedback, so they suggested moving that copy under the page title.<br>
<img width="50%" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWZoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2e79b2919068cdcf10b3abefce6e670fe0aa420f/image.png" alt="image.png" />
- After meeting with Julie S and Aliyah, we decided that that copy should live on the [how-to-apply page](https://www.va.gov/burials-memorials/veterans-burial-allowance/) since we link to it on the burial into page. We realized this information only exists on the paper form and nowhere on our info pages. CAIA will look into updating the how-to-apply page soon after our MVP launches since it wasn’t in scope.

**Comment by fiorella-io** [comment]
Aliyah will provide [final content feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68984#issuecomment-1930562909) **tomorrow 2/7**. I'll make any additional edits and move this ticket to "done" once I hear back from her.

**Comment by fiorella-io** [comment]
I made content updates to steps 3 - 6. Content is frozen in those pages. We are still working on the Submission page, both v1 and v2.

**Comment by fiorella-io** [comment]
**Updates:** 
- Content is frozen for the Intro page, and Step 1 - Step 6.
- In progress: 
    - Submission page content updates
    - New Step 1 alert for unauthenticated application

**Comment by fiorella-io** [comment]
On 2/23 [we sent our SMEs a pdf](https://dsva.slack.com/archives/C057W3N9K2S/p1708699712672199) of the entire Burial form designs for feedback. and on 2/26 we got new feedback from our SMEs that impacted the following pages:
- Step 1: Relationship to Veteran:  
     - We learned that depending on the selection, we don't need SSN and DOB. 
     - I adjust the flow, so we ask the Relationship to Veteran first, and then ask for the claimant's personal information. [Updated designs with logic](https://www.figma.com/file/jpJQSCKiGegacdW4RH5uQB/Burial-530-2024-Updates-MVP?type=design&node-id=174%3A43769&mode=design&t=AlydEyH31MeW8IEG-1) 

On 2/27, Evan notified us that the online PDF form was updated. This impacted two pages of our form:
- Step 1: Relationship to Veteran
- Step 2: Type of burial allowance

There's been a lot of back and forth with CAIA and our SMEs regarding the wording of the options.

Changes to these pages:
- Step 1: Relationship to Veteran
- Step 2: Type of burial allowance
     - On 2/28 we got updates from CAIA and kept this question split. Change the first question to multi-select
     - On 3/6 we got feedback from some of our SMEs asking for this question not to be split and match the paper form
     - On 3/8 we got CAIA updates to make this change. **We are awaiting SME's final approval of this change**. 
- Step 2: Veteran death location - Other selection
     - On 2/29 We got confirmation from our SMEs that when "Other" is selected, the claimant must specify the place's name and the city and state.
