### ISSUE TITLE
Federal CIO USA Banner Component

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#64107]
## Description
[Mockups](https://www.sketch.com/s/4558672b-741f-4d59-84f0-796020d3ef57) for the new minimal header include designs for a brand new Federal CIO USA header:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbzBxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--55b2e274a9f82f1ba910ed9cde1b6a6001969541/Screenshot%202023-08-22%20at%204.55.01%20PM.png)

This currently doesn't exist as a web component in UWSDS3. DST will create one with the intention of contributing it back to USWDS3 sometime in the future

## Considerations
- Ryan Thurlwell owns this design, will need to get the red white and blue USA asset from him

## Tasks
- [ ] Review DST backlog for outstanding issues with this component, if necessary
- [ ] Create web component and add to Storybook
- [ ] Write any necessary tests
- [ ] Add Chromatic link to #[add accessibility ticket number] and request review from an accessibility specialist
- [ ] Ping designer for design review
- [ ] Display the appropriate [maturity scale](https://design.va.gov/about/maturity-scale) option in Storybook (once this feature is available)
    - If this is a new component that has not gone through Staging Review, it should be labeled "Use with Caution: Candidate"
- [ ] Merge component
- [ ] Create a new release of component-library
- [ ] Update component-library dependency in vets-design-system-documentation to get the updated component-docs.json

## Acceptance Criteria
- [ ] Component is written and added to Storybook
- [ ] Component has had accessibility and design reviews
- [ ] Design.va.gov has the latest version of component-library
