### ISSUE TITLE
Create main BQ data structure and populate list with Unit Test specs

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#64120]
## Issue Description
Our Unit Test Allow List will be stored in BigQuery as it has been with E2E Tests. We'll need to create this list with the appropriate fields (spec_path, allowed, disallowed_at, warned_at). We'll also need to run an initial job to populate this list with all the specs and set them to initially be allowed. All specs should be contained in this list and just contain a true or false for whether they're currently allowed to run. 

---
## Tasks
- [x] Create a BQ table for the unit test allow list with all appropriate fields
- [x] Initially populate the fields with spec names of every spec in vets-website, along with an allowed status of "true" and null for other values.

## Acceptance Criteria
- [ ] The source of truth for the allow list has been established.
---

**Comment by CBonade** [comment]
Table has been created and specs are currently being populated. The initial population is slow due to the amount of records that need to be placed in. Will verify in the morning that all made it in and this will be done if so.

**Comment by CBonade** [comment]
My local scan of the repo shows 660 unit tests, and at the end of the GHA workflow to populate the table, there are 660 entries in the BQ table. This appears to have been successful!
