### ISSUE TITLE
[ENG, Data] 10-10CG - Performance: Conduct load testing

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#64124]
## Background
Our Health Tools Crew Chief, Lauren Alexanderson, [informed us](https://dsva.slack.com/archives/CMJ2V70UV/p1692798927732039) that the CIO and OIT leadership would like us to demonstrate readiness for up to a 10x spike in submissions between 9/20-9/30. We'll be looking to do some load testing within the next week (Sprint 107 8/23-9/5) on this and other downstream dependencies.

## Tasks

- [ ] Conduct End-to-End load testing
- [ ] Coordinate testing with downstream system (MuleSoft/CARMA)
- [ ] Validate that all services/systems are working as expected
- [ ] Validate that no unexpected errors or failures occur
- [ ] Validate that if there are errors or failures, they are documented and an investigation into the root cause is conducted
     - A separate ticket can be created for this work
- [ ] Validate that the load testing process is clearly documented
     - We need to show the tests we ran, the loads we tested and the results
     - We will need to show any remediation and retesting, in the event of errors or failures

## Acceptance Criteria
- End-to-End Load testing was conducted on the 10-10CG and the results are documented
