### ISSUE TITLE
[FE] Swap LocalStorage for SessionStorage

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#64133]
## User Story
As a Veteran, when I check-in for an appointment at a facility and file a travel claim and then close my browser and come back later and check-in for an appointment at the same facility, I would like to not see the travel questions because I can only submit 1 claim per facility per day.

## Tasks
- [ ] [FE] **Swap LocalStorage for SessionStorage**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
@brianseek is this an appropriate ticket to fix this issue? Please correct if I have used the incorrect terminology or there should be a different solution. Also, can you point it before planning today?

**Comment by brianseek** [comment]
Yes I this works for me. Thanks!

**Comment by brianseek** [comment]
Moving this to closed since the work is merged and there is a separate stage testing ticket
