### ISSUE TITLE
Pension Deactivation Widget

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#64136]
## Issue Description
_CAIA has requested [two widgets](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62445#issuecomment-1679682855) that will alert users on the How to Apply page that the digital pension form is not currently available._

---
## Tasks
- [ ] Create a widget for authenticated users
- [ ] Create a widget for unauthenticated users
- [ ] [Notify CAIA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62445) that the widgets are completed

**For the unauth state**

[H3] Our online pension form isn't working right now

You can still apply for VA pension benefits by mail, in person at a VA regional office, or with the help of a Veterans Service Officer (VSO) or another accredited representative. Download the PDF form we provide on this page.

If you started your form online already, you'll need to start over using a PDF form. But you can still refer to the information you saved in your online form.

[Refer to your saved form](link goes directly to "Review" page)

Screenshot (widget content is in the purple box)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBajR2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f883dd346b6c4c2525020d5556cb7ecc1d8973b9/image.png)

**For the auth state**

[H3] Our online pension form isn't working right now

You can still apply for VA pension benefits by mail, in person at a VA regional office, or with the help of a Veterans Service Officer (VSO) or another accredited representative. Download the PDF form we provide on this page.

If you started your form online already, you'll need to start over using a PDF form. But you can still refer to the information you saved in your online form.

Sign in to refer to your saved form

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa0F2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--526bbeb5142f0e3bd64acf91e76519401cb278a6/image.png)

## Acceptance Criteria
- [ ] CAIA approval of the notification widget for unauthenticated users
- [ ] CAIA approval of the notification widget for authenticated users
---
