### ISSUE TITLE
[FSR] Bug - Date substring error

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#64146]
## Issue Description
Sentry error is popping up for substring being called on undefined. 

[Sentry Error](http://sentry.vfs.va.gov/organizations/vsp/issues/221374/?environment=production&project=4&query=is%3Aunresolved+location%3A%2Fgenerated%2Frequest-debt-help-form-5655.entry.js)

---
## Tasks
- [x] Identify root cause
- [x] Apply fix

## Acceptance Criteria
- [x] Above sentry error is addressed
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
Made ticket to account for time spent yesterday as well! Closing out now that PR is merged!
