### ISSUE TITLE
FE | Profile | Audit Alerts in Code not in Sketch

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#64145]
## Background 

Now that we've completed our audit of the sketch files, we should double check to ensure there aren't alerts that are in the code but missing from our sketch files 

## Tasks 
- [ ] use Pam's spreadsheet from #48566 to search the code for alerts 
- [ ] update the spreadsheet w/any that are missing 
- [ ] discuss w/design and PM so the necessary tickets are created 

## Acceptance Criteria 
- [ ] we're able to move forward with updating the code to refresh our alerts post audit

**Comment by mtcA6** [comment]
we did this w/ USWDS migration (I think)
