### ISSUE TITLE
Update unit test run script to exclude tests that are disallowed by the unit test allow list

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#64147]
## Issue Description
The Unit test script will need to be adjusted to account for tests that are not allowed to run. Currently, the test runs have two options: run all the tests, or run one directory of tests. We'll need to make sure both of these options have the tests removed that are not allowed to run.

---
## Tasks
- [ ] Change the script for running all tests to run 20x if the run is a stress test.
- [ ] Change the script for running a singular app folder to run 20x if the run is a a stress test.
- [ ] Ensure support to interact with this supports both the dedicated stress test workflow and the regular CI workflow.

## Acceptance Criteria
- [ ] The script now has support to run a stress test properly when the workflow for the stress test is executed.
