### ISSUE TITLE
[CONTENT] Research and write ERIE, PA System Health Services and Program Intro (AdviseNurse-Caregiver) [CONTENT]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#6414]
## User Story or Problem Statement
As a Veteran Web user, I need a System description of services provided at VAMC, so I can understand and best chose the services and service location for my needs.

## Goal
_Efficient and clear content describing local Health Service provided_
_Efficient plain language for Health Services and Health Service Program Intro_

## Objectives or Key Results this is meant to further
- _Reduced word count and improved plain language._

## Resources - Tools - Documentation
[Erie Health Services Content Playbook](https://drive.google.com/drive/folders/12r3SWiQPCulkz2xOA06wGywQu5oWPArD)
[Erie Health Services:A-Z](https://www.erie.va.gov/services/index.asp)
[Pittsburgh Caregiver support Service Program Link](https://www.va.gov/pittsburgh-health-care/caregiver-support/)

## Tasks
_Tasks that must be complete using content playbook criteria for the following Health Services, and Health Service Program Intro:_
- [x] Advice Nurse
- [x] Audiology and speech
- [x] Cancer care
- [x] Cardiology
- [x] Caregiver support (Health Service)
- [x] Caregiver Support (Health Program)

## Acceptance Criteria
_Items that must be written and documented in Content Approval Folder under the correct VAMC System folder (i.e. Altoona, Butler)_
* Advice Nurse
* Audiology and speech
* Cancer care
* Cardiology
* Caregiver support (Health Service)
* Caregiver Support (Health Program)
