### ISSUE TITLE
Burial Deactivation Widget

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#64140]
## Issue Description
_CAIA has requested [two widgets](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62448#issuecomment-1688709232) that will alert users on the How to Apply page that the digital pension form is not currently available._

---
## Tasks
- [ ] Create a widget for authenticated users
- [ ] Create a widget for unauthenticated users
- [ ] [Notify CAIA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62448#issuecomment-1688709232) that the widgets are completed

Widget requirements are listed [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62448#issuecomment-1688709232).

## Acceptance Criteria
- [ ] CAIA approval of the notification widget for unauthenticated users
- [ ] CAIA approval of the notification widget for authenticated users
---
