### ISSUE TITLE
526 Submit - Release plan

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#64156]
## Issue Description
This ticket covers the discovery and release plan to deploy the migrated endpoint to LH for submit. The scope includes:
- Release plan - look at staggered release
   -  Can point to specific user through feature toggle
   -  
- Tasks in the ticket

---
## Tasks
- [x] Get Production Client ID from LH Benefits Claims API
- [x] Place the Client ID and RSA key in AWS parameter store 
- [x] Confirm devops repository and K8 manifest repository has references to correct environment variable paths
- [ ] Identify a prod user and do a test run - **Can we do this?** 
     - [ ] Can we get help from Emily and/or David to delete/mark a claim as test?
- [ ] Argo CD - Test submit endpoint using prod credentials from any client  - **Can we do this?** 
    -- [ ] Can we use the validate endpoint?
- [x] Identify acceptance criteria for a successful run
- [x] Establish Comms with the LH PM - Janet
- [x] We are testing all of /submit - not just Toxic Exposure (ie, filing CFI, PTSD flow, one condition vs multi, BDD, etc)
    - [x] We will need to test with new claims & IPF (in progress forms)

## Acceptance Criteria
- [x] Identify acceptance criteria for a successful run
- [x] Figure out how to monitor success(526ez form, submit workflow) - DD Dashboard
- [x] Create the release plan in GitHub (includes timeline and staggered release)
- [ ] Create Test rail test plan
- [ ] Create tickets for starting the staggered release based on the plan (includes timeline)

Out of scope
- Updates to the /submit DD dashboard (create new ticket)
- Slack alerts for thresholds (post release)
- Execute mocked Test Run 
- Successful mocked Test Run

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alatempa24** [comment]
Timebox this effort to 3, if Test Rail credentials and/or any other hiccups with creating test cases comes up, we'll break off Test rail plan into a separate issue.
