### ISSUE TITLE
FE | Profile Hub | Setup Routing to the Profile Page

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#64159]
## Background 
This first step will make use of the "profile" page and will be focused on updating the initial pieces of code needed to create the hub  (Adam you said something really great on refinement and I just butchered it here can you update this?) 

## Tasks 
- [x] make use of the feature flag and update the routing to use the profile web page  
- [x] route for profile goes to placeholder / starter page for hub work when toggle is on
- [x] existing redirects work when toggle is off

## Acceptance Criteria 
- [x]  we're ready for building everything out in staging!  and can pick up #64160

**Comment by adamwhitlock1** [comment]
PR has been approved. Going to merge after the daily deploy and follow up with instruction on how to validate once it's up on staging

**Comment by mtcA6** [comment]
Thanks Adam! Love to see the progress!!

**Comment by adamwhitlock1** [comment]
Well this PR has been merged, but there are unrelated test failures that are preventing this and any other PR merges (across the org) from getting deployed.

I have opened a support request here: https://dsva.slack.com/archives/CBU0KDSB1/p1694562357952859

**Comment by adamwhitlock1** [comment]
@mtcA6 This PR has been deployed to staging. I turned on the toggle for a few users including users 202.

To validate all you really need to do is log in with the user and navigate to the profile, then you will see the placeholder for the profile hub instead of the personal information page at the root `/profile` page.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcnFhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--badeed9d17afc7ec819956a1eebb637cc3205ad9/Screenshot%202023-09-13%20at%2011.32.32%20AM.png)
