### ISSUE TITLE
FE | Profile Hub | Feature Flags

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#64158]
## Background 
Create the feature flags so we can enable the profile hub for testing 

## Tasks 
- [ ] create the feature flag in vets-api
- [ ] create feature flag in vets-website

## Acceptance Criteria 
- [ ] we've got a functioning feature flag and we're ready to pick up #64159

**Comment by mtcA6** [comment]
I see a flipper. I'm okay with closing this 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWw0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0fac9259906a51fd58191be450e468a7dedb8a35/image.png)
