### ISSUE TITLE
[FSR] Installment contract date required tag

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#64162]
## Issue Description
Installment contract "date loan began" field's Required tag is behaving strangely. It is not present until after Minimum monthly payment amount has been edited. 

#### Before editing minimum monthly payment amount:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGd3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--aebf74772718a675d6913caaea6089efccc37e6a/image.png)

#### After editing minimum monthly payment amount:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbHN3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ef81c1d1c8582c9ffdfbe5eafe743dd6515d7035/image.png)

---
## Tasks
- [x] Confirm whether or not the field is required
- [x] Identify and fix why Required is not behaving correctly

## Acceptance Criteria
- [x] "Date the loan began" Required tag is behaving correctly.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by OptionSelect** [comment]
This was pulled in second to last day of sprint so it rolling should not affect metrics! I'm just pulling from the pile!

**Comment by HeatherRienks** [comment]
Got it and noted! TY!
