### ISSUE TITLE
Update unit test script to not run tests that are not allowed

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#64167]
## Issue Description
Our unit test script currently always runs either all, or a single directory of tests. This should be changed to exclude any tests that are not allowed per the allow list. Some early research into this indicates this can be done using a combination of `grep` and `--invert` , wiht a regex for the disallowed specs in the middle, along these lines: 

`mocha './**/tests/*.spec.js' --grep 'exclude1\.spec\.js|exclude2\.spec\.js' --invert`

---
## Tasks
- [x] Alter the unit test script to fetch the allow list and compile a list of tests that are not allowed to run.
- [x] Alter the mocha command to not run the tests that are disabled.
- [x] Test a disabled test (force update the data set if needed) to ensure it doesn't run.

## Acceptance Criteria
- [x] Disallowed tests no longer run in unit test runs.

**Comment by CBonade** [comment]
The logic for this is complete. Cannot merge until we're ready to launch this effort but this stage is ready to go.
