### ISSUE TITLE
[FSR] Mini summary cards for credit cards and installment contracts need more unique keys

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#64161]
## Issue Description
Credit card bill and installment contract mini summary cards are using minimum payment amount and unpaid balance for the keys. This can cause errors if they are ever the same, so we should update them to be more unique. 

Error when having two cards with the same values:
> Warning: Encountered two children with the same key, `undefined12`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

---
## Tasks
- [x] Update credit card mini summary to have more unique keys
- [x] Update installment contract mini summary to have more unique keys

## Acceptance Criteria
- [x] No chance of duplicate keys causing console errors
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by amponce** [comment]
Fixed, writing up PR notes, just changed to use index only instead of the `bill.minPaymentAmount + bill.unpaidBalance`
