### ISSUE TITLE
[a11y-defect-4]: "Follow the steps below" directional language needs to be changed

### ISSUE THREAD

**Issue by coforma-jamie** [department-of-veterans-affairs/va.gov-team#64163]
### Point of contact

Jamie Klenetsky Fay @coforma-jamie

### Severity level

4, Minor. Consider fixing or exploring in 2-4 sprints post-launch.

### Details

While it's not in the content style guide yet, CAIA recommends that you don't use directional language (above, below, left, right). Assistive technology users navigate through a web page in a variety of ways, such as by headings, links, and landmarks, and may tab backwards through a page. Directional language like this can be confusing. 

![Heading with 'Follow the steps below' language](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135633989/65ae175b-ccb2-490c-9a09-623b97fd3983)

### Reproduction steps

1. Go to [the form](https://staging.va.gov/careers-employment/vocational-rehabilitation/apply-vre-form-28-1900/introduction)
2. Scroll down to this heading: "Follow the steps below to apply for Veteran Readiness and Employment benefits."

### Proposed solution or next steps

We recommend changing this heading to "Follow these steps to apply to apply for Veteran Readiness and Employment Benefits."

### References, articles, or WCAG support

Google's [Write accessible documentation](https://developers.google.com/style/accessibility) guide - see "Don't use directional language to orient the reader"

### Type of issue

- [ ] Axe-core
- [X] Screenreader | assistive tech & device support
- [ ] Keyboard
- [ ] Zoom
- [ ] Color, typography, & visual elements
- [ ] Components and pattern standards
- [ ] Content organization
- [ ] Focus
- [ ] Headings
- [ ] Content style guide
- [ ] Link and button labels
- [ ] Semantic HTML
- [ ] Markup and metadata
- [ ] Non-text content and media
- [X] Overall user experience
- [X] Cognitive | user flows & navigating
- [ ] URL standards
- [ ] Something else
```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/68022
```

**Comment by steele-lm** [comment]
@fiorella-io @juliepedtke Can you confirm the wording CAIA suggested to remediate this issue is good-to-go? Thanks!

**Comment by fiorella-io** [comment]
@steele-lm This sounds good and it implicates all forms we'll be enhancing. I'll change the language on my Burial file.

**Comment by steele-lm** [comment]
@fiorella-io Were these changes already incorporated into the updated VRE designs?

**Comment by fiorella-io** [comment]
That section of the form was removed since it's part the old pre-form wizard
