### ISSUE TITLE
Get Credentials for Access to VA Forms Database

### ISSUE THREAD

**Issue by AkucherGCIO** [department-of-veterans-affairs/va.gov-team#6416]
## User Story or Problem Statement
As a Veteran, I need specific form information from the VA Forms Database so I can apply for benefits from the online tools available.

## Goal
Form data should be available to VA.gov Form Landing pages from the VA forms dataase.

## Objectives or Key Results this is meant to further
- _Include references to KPIs we intend to impact_
---
## Tasks
- [ ] _Is there ATO Involved ?

## Acceptance Criteria
- [ ] Access to the Form data from the VA Forms Database.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AkucherGCIO** [comment]
03/04/20 PW Grooming
@AkucherGCIO - set up a call with Andrew Fichter to understand how to push this forward.

**Comment by stephorkandatx** [comment]
@ncksllvn is this safe to close?

**Comment by stephorkandatx** [comment]
I believe this can be closed out, but want to confirm @ncksllvn or @beeyayjay that there are no additional credentials needed

**Comment by stephorkandatx** [comment]
We have been instructed that these are available for us. I am closing this out. If we cannot find or use the available credentials, we will submit a request
