### ISSUE TITLE
Incoming Issues Tracking - Per Sprint 8/27/23 - 9/9/23

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#64165]
## Issue Description
Contact Center will review and track all incoming issues escalated from VEO_

---
## Tasks
- [x] Tabulate incoming issues into categories - Tier 2/Tier 3/Tier EVSS
- [x] Create a grid displaying the number of incoming issues for each category
- [x] Publish report for leadership at the end of each Sprint

## Acceptance Criteria
- [x] Report published for leadership viewing
 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnFGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b55996fa2d2a5430c2f506f32629501e1a01bbbd/image.png)
