### ISSUE TITLE
[FSR] Credit card pdf fields

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#64174]
## Issue Description
Credit cards after the first one seem to be missing Purpose field after the first one on the PDF. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc2N3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--11b478530b5833bfa8c9d7b4144070338a05069a/image.png)

---
## Tasks
- [ ] Update credit card object so it includes a purpose or name label that is filled in on the PDF. 

## Acceptance Criteria
- [ ] All installment contracts and credit card bills have a purpose or name field populated. 
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by amponce** [comment]
<img width="924" alt="Screenshot 2023-08-29 at 1 22 45 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/3916436/3a4abf65-2a6c-4857-b7c2-8c108989fd76">

**Comment by amponce** [comment]
PR created https://github.com/department-of-veterans-affairs/vets-website/pull/25449
