### ISSUE TITLE
[FSR] Move values for pdf fields

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#64170]
## Issue Description
Payroll deductions for Retirement accounts are being added to the 'other' field on the pdf. The values are being calculated and handled correctly, just showing up in the wrong spot, but they are labeled correctly. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBckF3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--79a91fa8f7c6a03c773a89597bfa64d5b4cff825/image.png)

#### Note:
Added this to QA for enhancements for now, can probably move under a new tech debt epic if we make one

---
## Tasks
- [x] Update transform so Retirement accounts values is populated correctly 

## Acceptance Criteria
- [x] Retirement field is populated correctly. 
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by amponce** [comment]
I'm able to get the data for retirement on the correct lines however I see another line with some calculations that need further investigating 

It looks like we’re calculating retirement twice because of how line 14 adds A - D, and line D does some random math that isn't very clear
![Screenshot 2023-09-05 at 5 07 40 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/3916436/762c2998-3432-4946-85c2-7b8f7d0ec2e6)

**Comment by amponce** [comment]
All fixed, verified with SW off, and EFSR off, as well as SW on and EFSR on

![Screenshot 2023-09-06 at 1 58 42 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/3916436/2365f431-fd2c-48f1-843b-9b3efe48a8a7)

**Comment by amponce** [comment]
#64170 has been Merged

@Dr-Pongo has identified an issue where the spouse deductions are not populating in the specified section of column D. Although the values are being added and calculated correctly, it seems we're missing labels. I'm going to open a new spike to review this issue, rather than trying to resolve it in this ticket.
