### ISSUE TITLE
[FSR] Proptype console error on resolution option page

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#64176]
## Issue Description
Getting a failed prop type error in the console for the resolution option page. 

> Warning: Failed prop type: Invalid prop `formContext.pagePerItemIndex` of type `string` supplied to `FieldTemplate`, expected `number`.

---
## Tasks
- [ ] Update prop type for resolution option page

## Acceptance Criteria
- [ ] console is clear of errors navigating through these pages
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
Let's add to S113

**Comment by Dr-Pongo** [comment]
Opened a platform support ticket since the console warning is popping up inside the forms system. Will update when I hear back, hopefully with a path forward, even if it's just updating the proptypes to include a string

**Comment by Dr-Pongo** [comment]
So it looks like using a `ui:widget` in conjunction with `showPagePerItem` is causing `formContext.pagePerItemIndex` to come through as type string instead of type number. The platform component `FieldTemplate` is causing the initial error and we have our internal component `ResolutionOptions` expecting a string. Currently this isn't causing any major issues since we can still access our arrays using the `pagePerItemIndex` as a string. 

Going to close out this ticket since scope is creeping because it was sized thinking it would just be updating Proptypes of a component. Addressing the issue will take more time investigating forms system functionality and since this ticket was created as low priority non-breaking bug fix I think we should leave it as is. Platform teams have been notified, so it could get addressed by another team in the future. 
https://dsva.slack.com/archives/CBU0KDSB1/p1704211825844079
