### ISSUE TITLE
Prep PR with warning behavior swapped out for blocking behavior (Test Stability Review)

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#64179]
## Issue Description
As we reach the end of our soft launch period, we want to have a PR opened ready to go that will change all of our warning logic to blocking. This should include language changes as well as any code changes necessary (shouldn't need much).

---
## Tasks
- [x] Change warning annotations to show error statuses.
- [x] Change all language that outputs in GHA and annotations to reflect blocking instead of warning.
- [x] Open a PR with these changes but do not merge until launch time.
- [ ] Plan approach to merging this PR and making the "Test Stability Review" check a required check to pass (set in the GH Repo settings).

## Acceptance Criteria
- [ ] Warnings have been changed to blocking logic
- [ ] A launch plan has been put in place

**Comment by CBonade** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/26534 PR for annotations and CI Output
https://github.com/department-of-veterans-affairs/qa-standards-dashboard-data/pull/238 PR for slack notice that comes out weekly

**Comment by CBonade** [comment]
Current plan per Joe is to aim for around noon on Monday to give stakeholders an opportunity to review and ask final questions. Once these are merged, the branch protections in vets-website can be changed to mark "Test Stability Review Merge Status" as a blocking check.
