### ISSUE TITLE
[FSR] Console warning navigating away from mini summary pages

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#64178]
## Issue Description
When navigating away from mini summary pages the following warning is populating in the console. 
> Form submission canceled because the form is not connected

---
## Tasks
- [x] Investigate warning
- [x] Confirm it is not causing larger issues or find a way to fix it

## Acceptance Criteria
- [x] No console warnings/errors triggering 
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by OptionSelect** [comment]
Per the wisdom of stackoverflow (https://stackoverflow.com/questions/52834504/react-form-submission-canceled-because-the-form-is-not-connected), when we are using the default goForward function do NOT use the default param submitToContinue in the form navigation buttons to avoid this console error.

This is now also the discovery ticket for the continued effort of removing the remaining instances of this issue.
Pages throwing error:

**Comment by OptionSelect** [comment]
The fix is to remove this submitTocontinue
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0t1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--214720418a121e9db7bfeab74c742251af24aefc/image.png)
