### ISSUE TITLE
[CONTENT] Research and write ERIE, PA System Health Services and Program Intro (Minority-Ophthalmology) [CONTENT]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#6418]
## User Story or Problem Statement
As a Veteran Web user, I need a System description of services provided at VAMC, so I can understand and best chose the services and service location for my needs.

## Goal
_Efficient and clear content describing local Health Service provided_
_Efficient plain language for Health Services and Health Service Program Intro_

## Objectives or Key Results this is meant to further
- _Reduced word count and improved plain language._

## Resources - Tools - Documentation
[Erie Health Services Content Playbook](https://drive.google.com/drive/folders/12r3SWiQPCulkz2xOA06wGywQu5oWPArD)
[Erie Health Services:A-Z](https://www.erie.va.gov/services/index.asp)
[Pittsburgh Minority care Service Program Link](https://www.va.gov/pittsburgh-health-care/minority-veteran-care/)

## Tasks
_Tasks that must be complete using content playbook criteria for the following Health Services, and Health Service Program Intro:_
- [x] Minority Veterans (Health Service)
- [x] Minority Veterans (Health Program)
- [x] MOVE! weight management
- [x] My HealtheVet coordinator
- [x] Nutrition, food, and dietary
- [x] Ophthalmology

## Acceptance Criteria
_Items that must be written and documented in Content Approval Folder under the correct VAMC System folder (i.e. Altoona, Butler)_
* Minority Veterans (Health Service)
* Minority Veterans (Health Program)
* MOVE! weight management
* My HealtheVet coordinator
* Nutrition, food, and dietary
* Ophthalmology
