### ISSUE TITLE
Implement Unit test Allow List Changelog

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#64182]
## Issue Description
Create a separate database table that tracks each time the unit test allow list is updated. This should include spec name, whether it's being enabled, disabled, added+enabled, or added+disabled, and a date/time of the interaction. This allows us to have a source of history to check against for the current state of the list.

---
## Tasks
- [x] Create DB Table in BigQuery for the unit test allow list changelog.
- [x] Implement logic to update this table every time the allow list itself is updated.

## Acceptance Criteria
- [x] A changelog exists to track history of the unit test allow list.

**Comment by CBonade** [comment]
This is functioning as expected and is making updates every time a test spec has its status changed on the allow list.
