### ISSUE TITLE
[Drupal] Create a nightly migration from VA Forms DB into Drupal

### ISSUE THREAD

**Issue by AkucherGCIO** [department-of-veterans-affairs/va.gov-team#6419]
See #8390 [comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8390#issuecomment-630393186)
The foundational work is captured in #8388.

## User Story or Problem Statement
As a Veteran, I would like to see VA Forms data available from a single source of truth so that the validation can be made easier.

## Goal
Nightly Migration set up from VA Forms DB Into Drupal

## Objectives or Key Results this is meant to further
- _Include references to KPIs we intend to impact_
---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _Validate that the VA Forms DB data is available in Drupal daily.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
