### ISSUE TITLE
Staging review - design feedback - DS  Memorable date, Select and Breadcrumbs

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#64200]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

-

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Memorable date
- The Storybook 2 digit month field length does not match what is in Sketch (48 vs 128). Is this because Storybook is V3 and Sketch is V2? Also [Sketch](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/p/F8230127-0500-4C1A-BBBB-821299A5BDFF/canvas) is showing a V2 version, the [design system](https://design.va.gov/components/form/memorable-date#default) has V1 and V3 and [Storybook](https://design.va.gov/storybook/?path=/docs/uswds-va-memorable-date--default) does not mention a version. Can we align the versioning?
- Sketch has a month/year option. That options is not in Storybook or the Design System. Can we add those to both Storybook or the Design System? Is there guidance around using the month/year option?

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/67533
```

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/64200?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010

**Comment by jamigibbs** [comment]
> the [design system](https://design.va.gov/components/form/memorable-date#default) has V1 and V3 and [Storybook](https://design.va.gov/storybook/?path=/docs/uswds-va-memorable-date--default) does not mention a version. Can we align the versioning?

Before anything is changed here, I think as a team we need to align on the naming convention that we're using when we're talking about and communicating what a "USWDS" component variation is. In the past we have called them different things (v1, v3, USWDS v1, USWDS v3, MPV, original component, etc).

**Comment by caw310** [comment]
This will be a design investigation to identify the work that is needed as the feedback here isn't clear. 
@babsdenney @danbrady @LWWright7 will work on this.

**Comment by LWWright7** [comment]
After doing some research into the topic there is no consistency between the 3 places of documentation for  the "Memorable Date" component. 

First of all, let's examine the version with month selection as a dropdown option. 
In Sketch, it is listed as the default version of "Memorable Date":
<img width="431" alt="Screen Shot 2023-10-13 at 9 31 49 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/146852077/1ece9186-40ca-41c0-8049-d4aa568afcb4">
This is consistent in Storybook:
<img width="473" alt="Screen Shot 2023-10-13 at 9 33 21 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/146852077/27971a3e-9569-4424-8c30-6764bcf0a030">
However, in the design system, it shows the version without the month select as the default:
<img width="565" alt="Screen Shot 2023-10-13 at 9 33 57 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/146852077/c7e6c77a-d408-482a-a276-3702d7fe0a7a">


Next, let's look at the naming convention for these different components.
In Sketch, the version without the month select is called V2:
<img width="427" alt="Screen Shot 2023-10-13 at 9 35 52 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/146852077/2782ac4b-cdd8-4911-b226-a46b240bc08c">
In Storybook it is referred to as "without month select":
<img width="522" alt="Screen Shot 2023-10-13 at 9 36 31 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/146852077/d320805f-c3f3-4677-8138-77e839943774">
And for the design system it is shown as the default version:
<img width="565" alt="Screen Shot 2023-10-13 at 9 33 57 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/146852077/af07c68e-46cd-4fd8-b3b0-d018908e400a">


Finally, the design system lists the version with the month selection as V3, instead of the default state as it is shown in both Sketch and Storybook:
<img width="566" alt="Screen Shot 2023-10-13 at 9 40 20 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/146852077/77de6bef-0039-4ca5-b2f0-a1c1638ebcb9">


### Suggested solutions

In order to maintain consistency in all three documented repositories I suggest the following:

- Change the design system default to the month select version that is the default in both Storybook and Sketch.  The documentation at the bottom of the entry on the design system page seems to indicate that after research that this is a preferred and more user friendly version anyway:
<img width="644" alt="Screen Shot 2023-10-13 at 9 45 37 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/146852077/131e5d53-a578-4f21-bd81-4d35c981050a">

-  Change the name in Sketch from "V2" to "Without Month Select" to be consistent with Storybook
-  Change the name in the design system to "Without Month Select" to be consistent with Storybook
- Also, to help avoid any further confusion, the right hand column of design elements / components in Sketch is out of date and should be archived.
<img width="344" alt="Screen Shot 2023-10-13 at 10 09 37 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/146852077/7bf1539b-2452-48a2-b9d7-ae35e2fac718">

**Comment by caw310** [comment]
I think we can close this ticket. The default for v3 is the select box for month on design.va.gov.

**Comment by caw310** [comment]
Reopened as need to remove "v2" from Sketch for memorable date. Use the same title that is in Storybook.
