### ISSUE TITLE
Create 'hello world' of GitHub repo configuration terraform

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#64205]
## Issue Description
Set up a basic terraform configuration in a GitHub repo that demonstrates the infrastructure as code (IaC) practices for our environment.

---

## Tasks
- [ ] Set up a new GitHub repo for the terraform configuration.
- [ ] Write a basic terraform script that sets up a "hello world" level of infrastructure (e.g., a single AWS EC2 instance or similar).
- [ ] Document the setup and how to run the terraform script in the repo's README.

## Acceptance Criteria
- [ ] Terraform script can be run without errors.
- [ ] Infrastructure is set up correctly when the script is run.
- [ ] README provides clear instructions on how to run the script and what it does.
