### ISSUE TITLE
Fix screen reader issues for the memorable date component

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/va.gov-team#64212]
## Description

Some issues were found in the memorable date component that should be looked into and see if there is anything that can be done to alleviate the problem. See the Details section below.

## Details

[Video of Main Version](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/100248909/2f0d0b26-fefa-4690-85dc-166138c96e53)

- Main Version
    - _"Please enter 2 digits for the month and day and 4 digits for the year"_ reads out awkwardly, adding a comma is a little bit better: _"Please enter 2 digits for the month and day, and 4 digits for the year"_
    - It reads the following twice for the *Month* field _"Date of birth Please enter 2 digits for the month and day and 4 digits for the year"_. It may be reading the form group's legend, then reading the `aria-described-by`.
    - It reads the full legend when tabbing to each field, which can be verbose and repetitive. 
    - On validation, focusing the input seems to happen before the error message, so it starts reading the field information for *Month* (which is verbose), then tries to read the error, but often times gets interrupted.
- With Month Select
    - On the version with additional hint text under the input, that additional hint text does not get read out.
    [Video of With Month Select](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/100248909/bea9db6d-851c-4497-b2cd-736cac15ca49)
- Error/Error With Month Select
    - The initial state shows the invalid input styling and error message, but there is no announcement that it is invalid. `aria-invalid=true` isn't applied in this initial state.
        [Video of initial error state not being conveyed](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/100248909/7e8aa86c-69a1-40e9-9ed8-9686e03f70f0)

## Tasks
- [ ] Look into each item and see if the markup or ARIA attributes need to be changed.
- [ ] Test with Mac and VoiceOver.

## Acceptance Criteria
- [ ] Each issue has been looked into to determine if any fixes were needed and if so, those fixes have been implemented.
