### ISSUE TITLE
[FSR] Review page navigation

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#64213]
## Issue Description
Add navigation buttons to review page that return to first pages in chapters

[**Design ticket**](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/60560)

#### Edit section button example:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGsxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--dafb06234be379e8d82e6b16fec5a11ea6560476/image.png)

#### Info alert and link to review example 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdFZNIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f4e94214a7f546232d214a5d363840d851a5911c/first%20-page-review.png)

#### Back to review page on last page
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGRNIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e0a20f3cf4ee26d21e261731d82ae5a5bcade969/last-page-review.png)

#### Green alert on review page post change example
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbDAxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cf4d418fd01d9b7e62b49c162ff2f3718e90de43/image.png)

#### List of final page(s) in chapters that would need return to summary:

* **veteranInformationChapter**:
    * `currentContactInformation`
* **householdIncomeChapter**
    * `dependentRecords` / `dependentAges`
* **householdAssetsChapter**
    * `otherAssetsChecklist` / `otherAssetsSummary`
* **householdExpensesChapter**
    * `otherExpensesChecklist` / `otherExpensesSummary`
* **resolutionOptionsChapter**
    * `resolutionComment` / `resolutionWaiverCheck`
* **bankruptcyAttestationChapter**
    * `bankruptcyHistory` / `enhancedBankruptcyHistoryRecords`

---
## Tasks
- [x] Add "Edit section" buttons per chapter on review page
- [ ] Add slim alert to first page in chapter when navigating from review page
- [x] Add "return to review" link to first page in chapter when navigating from review page
- [x] Add navigation from end of chapter pages to review page
- [ ] Investigate adding green alert to top of review page when changes have been completed

## Acceptance Criteria
- [ ] All automated tests passing
- [x] Navigation edit section buttons available on review page
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mgleo** [comment]
@Dr-Pongo Will get more clarity on this after 3pm today. We're attending Design Office hours to discuss this https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2040

**Comment by mgleo** [comment]
Hi @Dr-Pongo, just updated this tickets so that the designs match what is on [#2040](department-of-veterans-affairs/vets-design-system-documentation#2040).
Is it possible to add analytics so that we have quantitative data on whether this implementation is successful?

**Comment by mgleo** [comment]
We are free to move forward with this design @Dr-Pongo  [#2040](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/department-of-veterans-affairs/vets-design-system-documentation#2040)

**Comment by Dr-Pongo** [comment]
@mgleo Glad to hear it! I can see if we can get new GA tracking set up for this, what are we looking to capture? Just looking for frequency of use?

**Comment by mgleo** [comment]
Hi @Dr-Pongo, we want to track successful use of the review page editing feature.
Can we track:
- Clickthrough rate on Edit buttons on review page?
- Clickthrough rate on "Back to review page" on the first editable page?
- Clickthrough rate on "Continue to review page" on the last editable page?

cc @josephrlee

**Comment by Dr-Pongo** [comment]
Hey! @mgleo I'll look at implementation options for this and see if I can get a support ticket opened with GA to start tracking labels! Feel free to pester me at stand up to help me remember!

**Comment by Dr-Pongo** [comment]
Still in progress! After a quick sync with design last weekend I'm adjusting the text on the buttons to return to the final review page after navigation. 

Roughly two points worth of work (wrapping functionality and creating tests) rolling over into Sprint 108!

**Comment by HeatherRienks** [comment]
@Dr-Pongo - when this ticket is merged, please let @josephrlee know, as it will unblock us on #63714!
Thanks!
cc: @Tom-Davis

**Comment by Dr-Pongo** [comment]
Priority work for [#66245](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/66245) pushed this effort. A number of large changes went in with those asset updates, so I'm working to rebase and resolve any conflicts.

**Comment by HeatherRienks** [comment]
Per SP, @Dr-Pongo will be doing testing today - staying cautious!

**Comment by HeatherRienks** [comment]
Per @Dr-Pongo, he and @amponce have been going through this - they've run into some issues that need addressing. They'll have a more comprehensive understanding and plan of attack tomorrow,10/11

**Comment by Dr-Pongo** [comment]
A lot has been going on with this ticket lately, and I'm dropping some updates for some hopfully decent record keeping. We are going to hide the review navigation features behind a feature flag getting merged in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/26226), CI/CD has been struggling with resources so the tests have not been successful, but[ after a conversation with platform](https://dsva.slack.com/archives/CBU0KDSB1/p1698165340788599) they are allocated more resources and hopefully we can get it merged asap. 

After that, we're breaking [this massive original PR](https://github.com/department-of-veterans-affairs/vets-website/pull/25756) into smaller more managable, more reviewable chunks. [The first one](https://github.com/department-of-veterans-affairs/vets-website/pull/26272) after the feature flag includes just changing the necessary pages into `CustomPages`, so we can add the custom navigation and messaging. The second will include the review header buttons and navigation hiddent behind the feature flag. Finally we are including checks to handle when review navigation breaks streamlined waiver or includes other cross chapter dependencies that could break the form flow or cause unruly errors.

**Comment by HeatherRienks** [comment]
@denisecoveyduc - FYI

**Comment by Dr-Pongo** [comment]
A number of PRs have been tied to this ticket, but the root of it lies in the following two PRs:
- Updating some form pages to be Custom pages which helps us add in the custom navigation back to the review page and add in some alerts at the top
  - [[FSR] 64213 - Updating start/end chapter pages to CustomPages for review page nav #26272](https://github.com/department-of-veterans-affairs/vets-website/pull/26272)
 - Adding buttons and headers inside accordions on the final reveiw page, adding alerts on the tops of each page for review, and including navigating back to the review page at the end of chapters
   - [[FSR] 64213 - Review Navigation addition #26509](https://github.com/department-of-veterans-affairs/vets-website/pull/26509)
  

Closing out this ticket because it's been lingering so long and the bulk of the work is completed. Part of the hold up was issues in CI/CD preventing feature flag PR merge, and cleaning up some flaky tests we had floating around. The PR is still in review, but we want to do some exhaustive testing so moving into **[FSR] Review page navigation testing** [#66330](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/66330) to account for that testing and writing some fun e2e tests. 

After some discussion with design, and testing the flow of this functionality we are adding in some transitional pages that break the reveiw flow and send the user down the remaining form if they made changes that affect other chapters. The two major instances are adding a spouse, and making income/expense/asset change that could affect a streamlined waiver flow. The tickets for addressing those flow updates are here:

- **[FSR] Review Navigation - Spouse status change while editing** [#67575](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/67575)
- **[FSR] Review Navigation - Income status change** [#67584](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/67584)
