### ISSUE TITLE
Update SOCKS GHA to check Atlas

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#64221]
## Description

When a SOCKS access ticket is opened, a Github Action is run to check the roster. Since we will no longer be updating the spreadsheet, we will need to update this GHA to check the database OR disable it for the time being and make it a required manual check. We could add this as a feature during the next iteration.

## Tasks
- [x] Modify socks issue template to require github_handle
- [x] Create new endpoint in Atlas
- [x] Secure endpoint behind an access_key
- [x] Create a GHA svc account policy for ECR - @flooose 
- [x] Encrypt tokens
- [x] Generate an access token for the roster check (wait until atlas is deployed) 
- [x] Store this somewhere in GHA (wait until atlas is deployed) 
- [x] Update the SOCKS GHA/script in devops to account for the new changes with the new endpoint
- [x] Test issue template for successful GHA run

**Comment by rmtolmach** [comment]
@LindseySaari you talking about this?
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/10993987/a6722de3-abc6-41d3-b5fa-b5d13e489924)
(from https://github.com/department-of-veterans-affairs/va.gov-team/issues/64479#issuecomment-1697800888)

The action in SOCKS requests that checks the Platform roster in Confluence and the VFS roster spreadsheet?

If so, here's that action: https://github.com/department-of-veterans-affairs/devops/blob/master/.github/workflows/pst-amt-roster-check.yml which runs [check_roster.rb](https://github.com/department-of-veterans-affairs/devops/blob/master/scripts/pst-access-management/check_roster.rb).

**Comment by LindseySaari** [comment]
This is now working! [Example here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76555#issuecomment-1953046044)
