### ISSUE TITLE
Improve the user experience on how veterans use "how to apply" wizards

### ISSUE THREAD

**Issue by AkucherGCIO** [department-of-veterans-affairs/va.gov-team#6423]
##  Problem Statement
Based on the questions that the Veteran answers in the "how to apply" wizard, they are shown only partial online application or routed to the starting point of the application (not to the specific portion based on their answer)

Examples - this may not be a complete list of pages that have wizards on our site:
https://www.va.gov/disability/how-to-file-claim/
https://www.va.gov/education/how-to-apply/
[In flight - wizard for Add/remove dependents tool][Mikki's IA documentation](https://app.moqups.com/Rnc4BDEKrA/view/page/abd763ecc) may help us find more examples:

## Goal
Move/consolidate these pre-requisite Wizard steps with the application tool landing page in order to:

1/ Make the Veteran experience of starting their online application more seamless. 

2/ Make apply online CTAs from tier 2 content and other content outside of the benefit hubs more clear and direct. Example: from our mvp form detail landing pages or from the modernized mvp form search results.

## Objectives or Key Results this is meant to further
- _Include references to KPIs we intend to impact_
---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] Design User Experience to move / consolidate "how to apply" wizard to Application Landing Pages

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by andaleliz** [comment]
@AkucherGCIO Thanks for creating this! Was this discussed during grooming today? I see it has the `needs grooming` label.  I'm not totally clear on how this is different from what is in the epic itself.

**Comment by AkucherGCIO** [comment]
@andaleliz - We discussed briefly about this ticket in grooming. This ticket is to capture the discovery you are doing to suggest the best design / user experience for the wizards.  I took some of the information from Epic and added it to this story.  If it needs to be tweaked some more, we can sync tomorrow about it.

**Comment by andaleliz** [comment]
Linking to [discovery synthesis doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/discovery/wizards-discovery-synthesis.md) - still in progress as of 3/6/20
