### ISSUE TITLE
ITF for Pension and Burial

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#64244]
## Issue Description
_Along with deactivating the digital burial (530) and digital pension (527) forms, the current review pages need include a link that allows authenticated users to generate an Intent to File (ITF), so they can print and submit the ITF artifact with their paper form._

---
## Resources
 - [Pension Review Page](https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/a/pYAQ8dG)
 - [Burial Review Page](https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/a/j4obPam)

---
## Tasks
- [ ] Add link to generate ITF to review page that aligns to [Sketch file](https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/a/pYAQ8dG)
- [ ] Link generates a page (or pdf) that includes:
   - [ ] Form Header
   - [ ] Name: Veterans Name
   - [ ] I intent to file for: (Pension Benefits or Burial Benefits)
   - [ ] Intent to file date: (earliest save date of in-progress form)

## Acceptance Criteria
- [ ] Link that generates page with data points listed above.
---

**Comment by steele-lm** [comment]
This work is no longer needed. VBA agreed to process the ITFs for burial and pension based on a report we provide.
