### ISSUE TITLE
[FSR] Cash on hand page number of chapters

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#64263]
## Issue Description
**Problem:** Cash on hand streamlined page is showing the limited chapter list when it should have the full length. `isStreamlinedShortForm` is checking the cash on hand value and triggering an true before the value is confirmed. 

**Solution:** Set a cash on hand specific value for `isStreamlinedShortForm` to check when updating the cash on hand value.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbDgzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a131e2bdeafca51f9d5103454cefb3443d0593b3/image.png)

---
## Tasks
- [ ] Update redux with new cash below asset boolean
- [ ] Check new cash on hand below boolean for `isStreamlinedShortForm` dependency

## Acceptance Criteria
- [ ] Cash on hand page shows correct number of chapters given the flow
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
Changes have been merged! Likely won't hit the deploy for prod until next week!
CC: @mgleo
