### ISSUE TITLE
PACT ACT Prep (9.30 deadline)

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#64262]
### PROBLEM STATEMENT
A number of issues occurred during the last PACT Act submission. (Lainey to link threads).
In order to appropriately prepare for the next cohort's submission, the following actions are taken:

### ADDITIONAL INFORMATION
- [Bridge channel in slack](https://dsva.slack.com/archives/C05Q1A58Y1L/p1693398567758559)
- Link to postmortem mural

### Code Yellow (first time this is being done)
- something that needs the attention level of something just below the level of a bridge
- this is for dependent claims
- went from 30% error to less than 1% error
- Bill will keep us posted if they need anything
- does not currently involve us!!!

### *10-10 form & Healthcare special enrollment period
- Endpoints might need to be bulkheaded
- [x] confirm that endpoints from last cohort are still bulkheaded.
- [x] do we need to bulkhead additional endpoints? we should hear from VFS teams over the next week or so about their tests. WE ARE AWARE OF WHAT NEEDS TO BE ISOLATED
- [x] review the scaling of the last cohort to determine if we need to setup additional bulkheads for 1) feature toggles, 2) in progress forms, 3) backend statuses, and 4) user maintenance windows (these endpoints aren't really fully owned by anyone, therefore fall on platform for now)

- We have determined that we do not need to do additional load testing as we have very significant data from the last cohort's submission

- Chris keeping an eye on current 10-10 testing
- [x] any other unowned forms/endpoints? search, etc?
- [x] are we confident that these endpoints can handle the load? or should we load test these endpoints
- [x] review traffic/load patterns, specifically the load error rate for feature toggles and v0/search during the last pact act surge
- [x] determine if we need bulkheads per ^^^ load patterns
- [x] review the in progress forms cleanup jobs
- [x] review current space in postgres *currently at 60% used
- [x] Chris: does postgres have an auto upgrade for when we reach a certain capacity?
- [x] review the monitors/alerts for pager duty
- [x] Identify additional Endpoints on the critical path (e.g. /v0/search)

### HCA endpoints for bulkheading

```
v0/health_care_applications/enrollment_status
v0/hca_attachments
v0/health_care_applications
v0/health_care_applications/rating_info
v0/in_progress_forms/1010ez
```

**Comment by flooose** [comment]
I've gone through the [vets-api endpoints with the highest latencies](https://vagov.ddog-gov.com/apm/services/vets-api/operations/rack.request/resources?env=eks-prod&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap99%29%2CtopN%3A%2110%29%2Cversion%3A%210%29&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A75%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21f%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%29%2Cversion%3A%211%29&start=1694451923120&end=1694455523120&paused=false) and while some of them were rather high, none of them really had spikes (of errors or latency) during the last Pact Act surge. For now there is nothing else that needs to be bulkheaded.

**Comment by LindseySaari** [comment]
An [InProgressFormCleanup](https://github.com/department-of-veterans-affairs/vets-api/blob/20e434c6e36012a5706bf1225aaf5761527d18b6/app/workers/in_progress_form_cleaner.rb#L4) job runs at 2pm daily to clean up old forms! This is important so that we free up space in the PG db and don't leave unnecessary/old forms hanging around after they've been sent for processing and completed. The [logs here](https://vagov.ddog-gov.com/logs?query=%22old%20saved%20forms%22%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=sliding&stream_sort=desc&viz=stream&from_ts=1694624599404&to_ts=1695229399404&live=true) show that this job is successfully running daily to cleanup forms at 2am.

**Comment by laineymajor** [comment]
Potentially adding another endpoint to the forms bulkhead

**Comment by laineymajor** [comment]
we do not have autoscaling for postgres, but it seems like this was a deliberate decision... due to performance issues.

**Comment by LindseySaari** [comment]
We will close this on Thursday
