### ISSUE TITLE
Phased Launch Checklist

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#6426]
## Background Info
Estimated date range: Sprint  17 (March 11 – March 24)
The total number of home/mailing address transactions we see per week is about ~4k-5k. 

## Phased Release Plan:
- [x] Launch behind a feature flag. Test with team.
- [x] Launch to 25% of folks. Observe for 1 week observe any errors/problems.
- [x] Launch to 50% of users. Observe for 48 hours for errors/problems.
- [x] Launch to 100% of users.

## Success Metric: 
99% of users who go through address validation should be able to complete the flow.
