### ISSUE TITLE
[CONTENT] Research and write ERIE, PA System Health Services and Program Intro (Returning-Telehealth) [CONTENT]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#6427]
## User Story or Problem Statement
As a Veteran Web user, I need a System description of services provided at VAMC, so I can understand and best chose the services and service location for my needs.

## Goal
_Efficient and clear content describing local Health Service provided_
_Efficient plain language for Health Services and Health Service Program Intro_

## Objectives or Key Results this is meant to further
- _Reduced word count and improved plain language._

## Resources - Tools - Documentation
[Erie Health Services Content Playbook](https://drive.google.com/drive/folders/12r3SWiQPCulkz2xOA06wGywQu5oWPArD)
[Erie Health Services:A-Z](https://www.erie.va.gov/services/index.asp)
[Pittsburgh Returning Service Member Program Link](https://www.va.gov/pittsburgh-health-care/returning-service-member-care/)
[Pittsburgh Suicide Prevention Service Program Link](https://www.va.gov/pittsburgh-health-care/suicide-prevention/)

## Tasks
_Tasks that must be complete using content playbook criteria for the following Health Services, and Health Service Program Intro:_
- [x] Returning service members (Health Service)
- [x] Returning service members (Health Program)
- [x] Smoking tobacco cessation
- [x] Suicide Prevention (Health Service)
- [x] Suicide Prevention (Health Program)
- [x] Surgery
- [x] Telehealth

## Acceptance Criteria
_Items that must be written and documented in Content Approval Folder under the correct VAMC System folder (i.e. Altoona, Butler)_
* Returning service members (Health Service)
* Returning service members (Health Program)
* Smoking tobacco cessation
* Suicide Prevention (Health Service)
* Suicide Prevention (Health Program)
* Surgery
* Telehealth
