### ISSUE TITLE
Onboarding Tools Access for new Veteran Support Team Member - Megan H. 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#64286]
## Issue Description
_Tracking ticket for tool access for new team members.  Not all team members will need access to all of the tools.  The list below is all-encompassing for Contact Center team members._

---
## Tasks
- [x] Salesforce
- [x] GitHub
- [x] ZenHub
- [x] AVA (Ask VA)
- [x] Citrix/Azure
- [x] MVI Toolkit (VA side)
- [x] VA email address
- [x] Slack
- [x] PIV/PIV Extension

## Acceptance Criteria
- [ ] _Complete list of access to applications for team members. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
Submitted a ticket for Salesforce access on the VA side today for Megan H.

**Comment by Kimberley2023-CSM** [comment]
Salesforce access cannot be provided without PIV access.
TEAMS access needs to be provided by Chante.

**Comment by Kimberley2023-CSM** [comment]
No movement on this as of yet.  PIV is needed to complete access requirements.

**Comment by ATMiddleton** [comment]
@Kimberley2023-CSM I updated the status to "blocked" until Megan obtains her PIV card.

**Comment by ATMiddleton** [comment]
https://dsva.slack.com/archives/C05HRLN85PU/p1695741875482769 

Possible PIV exemption for Megan

**Comment by Kimberley2023-CSM** [comment]
Megan now has her PIV card on 9/28/23.  Salesforce access will be verified before EOS.
