### ISSUE TITLE
Test template 

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#64298]
## Background
Describe the issue background and scope

#  EPIC
When working on UI/design updates
1. designer create mockups (includes review from CAIA practices)
2. FE builds the thing, and then once it’s on prod (or close to it)
3. contact center doc gets updated (minimum screenshots might need to change) 
4. use case docs get updated (possibly nothing needs to change, or could be a lot)
5. Sketch mock-ups get merged into master “source of truth” artboards that are linked to our docs

- [ ] Design | Project | Create mockups (includes review from CAIA practices)
- [ ] FE | Project | builds the thing, and then once it’s on prod (or close to it)
- [ ] PM | Project | contact center doc gets updated (minimum screenshots might need to change)
- [ ] Design | Project | use case docs update (possibly nothing needs to change, or could be a lot)
- [ ] Design | Project | Sketch mock-ups get merged into master “source of truth” artboards that are linked to our docs

# RESEARCH EPIC
For research, there’s a very consistent set of steps:
1. Create research plan
2. Create convo guide
3. Logistics (set up note taking docs/templates, schedule debrief session, maybe hold kick-off w/ Perigean)
4. Run the sessions
5. Create Topline summary (optional)
6. Synthesize findings
7. Create presentation deliverables (optional)

# DISCOVERY 
## Tasks 
- [ ] review previous research 
## Acceptance Criteria 
- [ ] summary and recommendations of research 
- [ ] ready for mock ups / design intent ([artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts)) 

# DESIGN
## Tasks
- [ ] Create mock-ups / update sketch files
- [ ] Review w/ team
- [ ] Get content approved
- [ ] Revise mock-ups as needed
- [ ] Let team know ready for FE

## Acceptance Criteria
- [ ] Ready for FE

# FRONT END TICKET
## Tasks
- [ ] Conduct Unit tests 
- [ ] Run E2E tests covering current code and regression
- [ ] Notify PM if this needs to be deployed to Staging behind feature flag
  
## Acceptance Criteria
- [ ] Complete all unit testing
- [ ] End-to-end tests showing 0 violations
- [ ] All axe checks pass
- [ ] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [ ] Confirm PM has opened a new ticket to deploy changes to Production using feature flag, if needed

# BACKEND TICKET
## Tasks
- [ ] Conduct Unit tests 
- [ ] Run E2E tests covering current code and regression
- [ ] Notify PM if this needs to be deployed to Staging behind feature flag
  
## Acceptance Criteria
- [ ] Complete all unit testing
- [ ] End-to-end tests showing 0 violations
- [ ] All axe checks pass
- [ ] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [ ] Confirm PM has opened a new ticket to deploy changes to Production using feature flag, if needed

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)?
- How can this work be validated?
- What updates need to be made (e.g. product outline, use cases, contact center guide)

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so
