### ISSUE TITLE
[Mocked Auth FE] Feature request from UX

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#64297]
## Description
This describes the body of work that was pointed out during the UX research conducted on Mock Auth workflows. This is all on vets-website for mocked authentication.

## Tasks
- [ ] Update heading 1 to => `Mocked authentication` (see attached image)
- [ ] Update body content (see attached image)
- [ ] Create a better visual hierarchy to state that mocked auth only works in localhost & dev environments
  - [ ] Use a banner that goes across the page (see attached image)

## Quick mockup
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaE04IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--04cad6eee9c7543bf08d9415ebb6c8d47da9363c/Screenshot%202023-08-25%20at%208.53.56%20AM.png)
