### ISSUE TITLE
Strategy on Landing Page - communicate disjointed UX to Veterans who have a Cerner Facility

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#64302]
## User Story
As a user, I want to see content/description about what to expect when I navigate to various health resources from the MHV on VA.gov landing page so that I understand it is a somewhat disjointed experience and can better manage my expectations.

## Description
Per a [conversation on the Cartography team Slack channel ](https://dsva.slack.com/archives/C0581MN69TJ/p1692714626949029)& a related thread [posed on the SM channel,](https://dsva.slack.com/archives/C03ECSBGSKX/p1692907527286749), there is some planning work to be done on the landing page to account for communicating & routing for users who may encounter health products in a disjointed fashion in Phases 1+ of the MHV rollout. 

The Cartography team needs to collaborate and develop a strategyfor how to communicate the possible disjointed experience to end-users (primarily those who may have a Cerner facility) and ensure they are clearly routed to where they need to go with as much clarity as possible in language and user-experience. 

## Impacted Artifacts
* MHV Landing page
* Possible new designs for banner alerts, pop-ups, or other messaging - these designs should be informed by existing designs for routing that occurs at the tool-level (see [Figma file ](https://www.figma.com/file/iqjkZx2EbrZu6leL6YfN45/Cerner-Handoff?type=design&node-id=1631-22883&mode=design&t=Kkr9eceuxPF83YKU-0)here)

## Tasks
- [ ] Cartography team discuss possible solutions & align on best approach
- [ ] Present approach to @batemapf for feedback
- [ ] Document decision & create follow-on ticket for design & engineering

##Acceptance Criteria
- We have a solid plan for communicating the possible disjointed UX to users with a Cerner facility and/or who may not otherwise have a unified experience with tools on VA.gov in initial phases.

**Comment by batemapf** [comment]
f/u from [lichelle in slack](https://dsva.slack.com/archives/C03ECSBGSKX/p1693407229389829?thread_ts=1692907527.286749&cid=C03ECSBGSKX):

 The MHV system checks if a Patient (PI) has 200CRNR PI  and at least one of the five migrated treatment  facilities (Spokane 688, Roseburg 653, White City VA 692, Walla Walla 687, Columbus VA757) then display links to My VA Health.  The developer has not seen any issues or problems with this logic.  The reason we check for the facility is because IAM added the 200CRCR to upcoming migrating facilities such as Boise and Saginaw, which, as you know, never migrated.

**Comment by sterkenburgsara** [comment]
Update: While we have the ability to detect whether a user has a Cerner facility in their profile on the landing page, there was a decision to not gate Cerner users on landing page. They can see the landing page like anyone else, but will see messaging/routing on tool pages.

**Comment by sterkenburgsara** [comment]
Appointments team is spearheading designs ([see Figma file](https://www.figma.com/file/iqjkZx2EbrZu6leL6YfN45/Cerner-Handoff?type=design&node-id=1631-22883&mode=design&t=Kkr9eceuxPF83YKU-0)) as they will be the first product to roll this out (will hit Phase 1a first). Secure Messaging will hit Phase 1 at very similar timeframe and will also need this messaging. I attended Appointments team UX meeting on 8/30 and many cross-team stakeholders in that call agreed to adopt the same messaging/design. See [Slack thread](https://dsva.slack.com/archives/C03CGTDLTFF/p1685564892637439) for details. For questions, contact @kristenmcconnell

**Comment by kristenmcconnell** [comment]
Yes, the last edits to this by the appointments team should be completed very shortly. They are just making updates to the scenario when only one Cerner facility is listed. We are going to remove the bullet and add the facility name in the header. I'll post here when the updates are complete.
