### ISSUE TITLE
FE | Direct Deposit | Changes to Bank fraud alert for better accessibility

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#64307]
## Background 

From our accessibility audit last year we missed a recommendation. We updated the mocks  in #63493 and need to make the FE changes with this ticket by updating the placement of the headings. 

>Both mock-ups are on [this page in Figma](https://www.figma.com/file/takD53OoltCjdlmGBwK3DH/Sketch-Archive---Authenticated-Experience?type=design&node-id=250-11437&mode=design&t=yMeAWrsXz4TofK0C-11). Once they've been validated on the FE, let's make a ticket to update all the DD Figma file to reflect the latest. 
[...]

_Originally posted by @andaleliz in https://github.com/department-of-veterans-affairs/va.gov-team/issues/63493#issuecomment-1692338301_
            

## Tasks 
- [ ] changes have been made 
- [ ] reviewed with PM/PO 
- [ ] Let design know when on production so Sketch files can be merged

## Acceptance Criteria 
- [ ] the updates are deployed to production

**Comment by mtcA6** [comment]
@andaleliz I can no longer access the sketch file referenced here, it asks me to refresh and doesn't load anything. 

Can you confirm this is the correct [figma file ](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=0%3A462&mode=design&t=oTSa5W5n915KrIee-1)to look at? and more specifically, did we carry over

**Comment by andaleliz** [comment]
@mtcA6 I updated the description with the correct Figma file link for Adam to reference.  

Can you clarify what you're referring to about "did we carry over"? I think you didn't get a chance to finish your sentence before posting.

**Comment by mtcA6** [comment]
sorry about that @andaleliz edited my comment, I wanted to make sure the work done in sketch for the prior story wasn't lost in our migration, so I think we're good now w/the updated link to figma!

**Comment by mtcA6** [comment]
Chatted w/Samara, C&P is the only section that has fraud support. We discussed leaving this where it is for now since the page is changing, once the updated ch33 work takes effect, we'll have to submit a 508 review anyway so if there are any issues those  should be captured then.
