### ISSUE TITLE
Schedule CAIA team members (Kate, Jamie, Eli) for orientation

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#64308]
## Description
A Platform website/content orientation is done for every person joining the Platform program. This introduces them to our team, the Platform website, our support services and how to collaborate with us. Here's are some team documents with more information:

- https://vfs.atlassian.net/wiki/spaces/CIT/pages/2477621264/FY2023+Q2+Platform+website+orientations
- https://vfs.atlassian.net/wiki/spaces/CIT/pages/2479325201/Platform+content+orientation+for+Platform+teams

Office Hours Zoom link: https://us06web.zoom.us/j/84651883090?pwd=YmdhM0dDemRmZWpVRUdHVmxRaG1Tdz09

**Targeted Orientation Date:** January 9th, 2024

## Tasks

- [ ]  Determine the best office hours date to have orientation. Targeting _Tuesday, January 9th, 2024._
- [ ]  Determine the date range to send new team member Slack message. Anytime in Sprint 43, but before Tuesday, January 2nd.
- [ ] Message them on Slack to let them know. See #3 in the pre-meeting scheduling process for message template.
- [ ]  Adjust Zoom invite

## Acceptance Criteria

- [ ] Orientation has been scheduled for the following individuals
- [ ] Kate Murphy
- [ ] Jamie Klenetsky Fay
- [ ] Eli Mellen

**Comment by johnny-jesensky-adhoc** [comment]
Reached out to Naomi on this on Tuesday, November 14th. Confirmed their last names, and will look to schedule this session in an upcoming sprint.

**Comment by johnny-jesensky-adhoc** [comment]
After consulting with Vicky and the Content Team, because these individuals are all part of the CAIA Team, and thus not directly part of the Platform Crew, they do not participate in our orientation meetings. As such, we will not be scheduling this, and will be closing this out.

Closing this as _Not Planned_.
