### ISSUE TITLE
VA Notify Trigger

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#64323]
## Issue Description
_The VA Notify team has requested a trigger that will initiate the notification emails we are sending to Veterans with in-progress pension and burial claims. The emails will notify Veterans with in-progress claims that the digital forms have been deactivated and explain the options they have for submitting their claims._

## Resources
- [VA Notify Platform Overview](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/README.md#successes)
- [VA Notify GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-notify)
- [VA Notify Playbook](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/VA%20Notify%20Playbook.pdf)
---
## Tasks
- [ ] Review VA Notify API docs (This [link](https://staging.notifications.va.gov/developer/api_docs) was in the VA Notify Playbook, but it's broken!)
- [ ] Get access to the Self Service Portal
- [ ] Build notification code to call the VA Notify API for the burial and pension forms (separately). We may be able to leverage a trigger that Kyle Sorkin did for 526.
   - [ ] Notification should trigger an email to all users who have an in-progress (started but not submitted) 527 or 530 form.
   - [ ] The default email address should be the email the user entered into the 527 or 530 form. If not email exists within the form, use their MyVA profile email.
- [ ] Test notification by logging into staging with a test user, updating the profile ID to something that sends to you
- [ ] Nice-to-have: Identify universe of users that will be notified, so we can understand:
   - How many in-progress users we expect to notify for pension and for burial (this number will fluctuate)
   - How many users entered an email address into the form.
   - How many users did not enter an email address into the form. We may have to investigate if we can use the email address entered into their MyVA profile as an alternative.

## Acceptance Criteria
- [ ] A notification trigger that sends an email to users with in-progress pension 527 forms.
- [ ] A notification trigger that sends an email to users with in-progress burial 530 forms.

**Comment by steele-lm** [comment]
@fred-khoury-oddball The VA Notify Team (Bev Nelson) [mentioned that](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63614#issuecomment-1699641100) they want to know in advance what time of day we expect the blast to go out, total size of blast, and how often these can be expected so they can make sure there's no conflicts with their largest volume use cases. Typically, they wouldn't want a service to be sending more than 15 requests per second.

**Comment by sortizsh** [comment]
@fiorella-io can you create the template on VA and add the approved copy and sync with Fred?

**Comment by steele-lm** [comment]
I created email templates tickets for [burial](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64680) and [pension](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64679).
