### ISSUE TITLE
Null Claim - 674 - Hours per week in Class

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#64344]
Follow on ticket to action outcome of #64141 

In 674, we ask the Veteran how many hours per week their dependent is in class. If the veteran enters a number that exceeds 999.9, BGS rejects the claim as out of bounds.

## Tasks
- [ ] Implement front-end validation such that the number of hours in class must be less than or equal to 168 (the total hours in a week).
- [ ] Add error message that displays when user enters a number greater than 168 hours: The number of hours you've entered exceeds the total hours in a week.
- [ ] Implement front-end validation such that the number of sessions must be less than or equal to 999
- [ ] Add error message that displays when user enters a number greater than 999: The number of sessions you've entered exceeds 999.

## AC
- [ ] User cannot enter a number greater than 168 total hours in field and submit form
- [ ] If user enters a number greater than 168 total hours in the field the error message appears.
- [ ] User cannot enter a number greater than 999 total sessions and submit form.
- [ ] If user enters a number greater than 999 total sessions in the field the error message appears.

**Comment by steele-lm** [comment]
@juliepedtke Zack's research into this issue uncovered that we need to add validation and an error message to the "hours per week" field in the 674 form. Would you suggested that Ajia reviews the suggested error message with Julie S?

**Comment by zack** [comment]
While we're here, should we add a validation to sessions per week? The database can take up to 999, so we can also validate against that. It's a pretty meaningless number for like "is this a true number" validation, but it will at least prevent a typo from breaking a form submission.

**Comment by zack** [comment]
Validation logic is added but we need to figure out the copy.

**Comment by zack** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcTFzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6cb47dbf502b9b6ba684bdd6d4e5c1edd1878982/image.png)

**Comment by juliepedtke** [comment]
Thanks @jstrothman ! Just [shared with CAIA via Slack](https://dsva.slack.com/archives/C01K37HRUAH/p1694034744314149) for a quick review, and will come back with updates.

**Comment by juliepedtke** [comment]
Summarizing feedback from CAIA (see [Slack thread](https://dsva.slack.com/archives/C01K37HRUAH/p1694034744314149))
- The current style for this type of error/help text would be "Enter a number less than #" so we should drop the "please"
- "Sessions" should be plural in the field label for that item
- Out of scope for this ticket, but should be considered for future updates: The browser default [number input with arrow buttons inside the input](https://www.magentaa11y.com/checklist-web/number-input/) isn't accessible. I would recommend using the [va-number-input web component](https://design.va.gov/storybook/?path=/docs/components-va-number-input--default) instead.

No other design recommendations at this time, so I think we're ready to move forward!

**Comment by sortizsh** [comment]
@evansmith
