### ISSUE TITLE
Research | Profile | Multi-feature UAT | Study logistics

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#64343]
## Background
We completed the research plan and convo guide in #62610. This ticket covers the next steps

## Tasks
- [x] Find pilot participant
- [x] Update availability
- [x] Submit for recruitment
- [x] Create note taking/task tracking document
- [x] Complete any other steps needed to prepare while recruiting takes place

**Comment by andaleliz** [comment]
Research kicked off 10/9.
