### ISSUE TITLE
[Design] Update Next of Kin Wireframes Due to Platform Design Feedback

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#64341]
## Description 

Although the team had a finalized solution for providing an explanation for "next of kin," after later showing the solution to other folks from Platform Design, they recommended that we split up the topics into separate additional info components. E.g., explanation of next and the information about what happens if you answer, "No." 

[Initial finalized wireframe](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/E1C6BC22-9480-4D54-9D6F-C7E3D9D212A2/canvas#Version)

## Tasks
- [x] Create final mockups with content. E.g., one component at top, other at bottom. 
- [x] Review with Brian DeConinck (or other A11y specialist) to discuss any accessibility concerns with the placement of the two components. 
- [x] Make sure there are no A11y issues
- [x] Add to the design page 
- [x] Add to any existing releases for UE

## Acceptance Criteria
- [x] Wireframe available on Sketch Cloud
- [x] Brian DeConinck provided guidance
- [ ] Discuss with Lori where she wants to fit this work in and ensure a FE ticket gets created

**Comment by cgednalske** [comment]
Next of kin accordions are updated in Unified, Pre-check-in, and Check-in Design pages, as well as Priority 1 & Priority 3 and ready for validation. @kellysmith1008 @benbrasso-agile6 
(cc @ytsaoca when you're back)

@loripusey here are the links for the engineers:
[Pre-check-in (in-person)](https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/a/5noYVxd)
[Pre-check-in (telemedicine)](https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/a/1VPLo2n)
[Check-in](https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/MmxbkOm)

(**Note:** some of these files use different artboard sizes, causing slightly different formatting for the additional info component in Sketch)

**Comment by benbrasso-agile6** [comment]
LGTM

@loripusey this could be something the FE engineers implement next sprint, should be a small pointer. Lee worked on it last sprint.

**Comment by loripusey** [comment]
FYI, I went ahead and created an Epic for this work (as it will need multiple tickets) and put this ticket in the Epic

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 you cool with how this turned out? Can close once you reviewed.

**Comment by kellysmith1008** [comment]
LGTM :)

**Comment by loripusey** [comment]
the links above for the final wireframes are all the same, can someone help here?
@benbrasso-agile6 @cgednalske

**Comment by benbrasso-agile6** [comment]
The content of the dropdowns are not different. But the surrounding elements between pre-check-in in person vs. pre-check-in phone vs. check in are different. The next of kin content for the two additional info components are all the same.
