### ISSUE TITLE
Copy of Incoming Issues Tracking - Per Sprint 

### ISSUE THREAD

**Issue by Kimberley2023-CSM** [department-of-veterans-affairs/va.gov-team#64354]
## Issue Description
Contact Center will review and track all incoming issues escalated from VEO_

---
## Tasks
- [x] _Tabulate incoming issues into categories - Tier 2/Tier 3/Tier EVSS
- [x] Create a grid displaying the number of incoming issues for each category
- [x] The grid shall include how many of the existing issues have been resolved 
- [x] The grid shall include the number of unresolved issues for each category
- [x] Publish report for leadership at the end of each Sprint

## Acceptance Criteria
- [ ] Report published for leadership viewing
- [ ] Report shall include quantity of incoming issues, resolved issues and remaining unresolved issues on a biweekly end of Sprint basis 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
