### ISSUE TITLE
Design | Direct Deposit EVSS>LH | Create an alert for 502 errors

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#64357]
## Background 
We're seeing a large number of 502 errors related to stale addresses in a downstream system. In order for users to update their direct deposit information they FIRST need to update their address THEN they'll be permitted to update their direct deposit information. 

On the get, the API is returning an error that we need to display to the user alerting them to a need to update their mailing address before they can modify their direct deposit details ([link to slack thread](https://dsva.slack.com/archives/C03P6C3FYMR/p1692975639948189)) 

      
             [need specifics from tom on the error message on the get]

This alert will need to:
- advise users who have this stale information 
- take users to the contact information in order for them to update their mailing address

[Tom is working on the error handling in the background. ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64364)
Once this ticket is complete we'll need to work on this in the FE

Make sure this covers all of the various use cases. 

## Tasks 
- [ ] content has been confirmed/updated 
- [ ] mocks have been reworked based on content suggestions ([mocks shared by Liz](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/pYAQ1Zo))

## Acceptance Criteria 
- [ ] we're ready for FE development

**Comment by andaleliz** [comment]
@mtcA6 can you provide some more context about what this means?
>We're seeing a large number of 502 errors related to stale addresses in an upstream environment.

- I'm not sure what a 502 error is (though I will Google it when I'm done typing this)
- I don't know what you mean by "stale addresses" Is this the same as the bad address indicator that happens in the contact information section?
- what does "upstream environment" mean?
- Is this related to a mailing address, or home address, or both?

We already have an alert in place if someone doesn't have certain contact info on file ([use case doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/use-cases/validation-address-phone.md)) - can you confirm this is a separate thing?

**Comment by mtcA6** [comment]
We'll have to refine this together on the planning call w/Tom.

**Comment by andaleliz** [comment]
Documenting some questions I need to get answered in order to move forward with this work. Meeting with Tom on 9/5 to discuss.

- Why is editing blocked if there isn't an address on file? This will help us understand if we should also block the read mode for DD
- Does the 502 error would occur if a person’s account has the bad address indicator on the mailing address?  Based on the API response `502 Bad Gateway - Payment Address Data Not Found` it sounds like it is only occurring if the address is _missing_ but need to confirm that.

**Comment by andaleliz** [comment]
[Here's a mock-up](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/RydrYa2) of what I recommend if the following is true:
- This does not impact EDU direct deposit.
- This only happens if the mailing address is _missing_.
- We can't decouple the dependency on mailing address from DD updates.

We could use this approach for users who have DD already set up, and for users who are eligible but haven't set it up (the section would only contain the alert).

**Comment by andaleliz** [comment]
@tpharrison and I met today; he's going to reach out to the LH team to try to get answers to [my questions above](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64357#issuecomment-1703084669), as well as some more information about some flags that could also prevent a user from being able to edit (and possibly read) C+P DD information.

**Comment by tpharrison** [comment]
Slack Thread - https://dsva.slack.com/archives/C03P6C3FYMR/p1692975639948189

**Comment by mtcA6** [comment]
@andaleliz I haven't been on all of the meetings w/you and Tom so I may be missing some details.  But are we sure users are completely missing an address from their profile? I thought the issue was they're missing an address in the downstream database that we're attempting to update but may still have an address in the profile. 

If you're absolutely certain the issue is that the users are missing the data in their profile and therefore downstream this creates an error then the language in this alert you created makes sense.

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/7286f927-02e5-46c4-ad4e-a53ecc7e39da)

However, if there's the possibility they have an address in their profile but they're missing it in some random downstream database then we should use different language requesting they update their address first without mentioning that it's missing from the profile.  Could you create an additional mock with different language? That would allow us to display the alert in both scenarios. 

---

Regarding the following:
> - We can't decouple the dependency on mailing address from DD updates.

I suspect, given the length of the email chain you forwarded about decoupling, this will take not an insignificant amount of time to work through. I think we should move forward with an alert that doesn't depend upon the decoupling piece. cc: @Samara-Strauss my suggestion is we add an alert for users and continue to work on the decoupling as a separate stream. 

I do want to highlight a sentence from that email chain that I found very interesting:
> If their validation fails due to missing data, the EFT update will fail even though that part of the request is correct…This is imposed by the BGS service that was designed for an old eBenefits feature that allowed users to change all this data in one request on the same page.

Liz, you highlighted on the NOK conversation, it can be hard to untangle what is a system requirement and what is actually required by VA. Could this could potentially be a Treasury rule of some kind that was built into the system structure? 

Putting on my old finance hat here, it's not uncommon to require users who are updating account information, in particular sensitive information like wire/ACH account numbers to also have additional barriers to entry like refreshing address or contact information. While it may seem arbitrary, requiring a user to update their address first would trigger an email notification to the user about an address update, followed by another email to alert them to the updated direct deposit information. One of the better practices, if you're not performing a callback verification on the new data, is requiring users to input their old bank account information when entering a new account number. This can be a bit onerous, but it makes it harder, although not impossible, for fraudsters to act since it requires both sets of account details.

**Comment by tpharrison** [comment]
@mtcA6 We think that this error is triggered when a user is missing an address from their profile, but we're not sure and we haven't been able to get very detailed or definitive answers from Lighthouse.  We may need to reach out to BGS on this.

Another option is to add more logging to the update function in vets-api to record more data around this error.  For example, when this error is returned from LH, we can log more data points that tell us if the user has a mailing address, if they have a BAI flag, etc.  We don't need to record any PII data, just whether or not certain data fields are present.  This should help shed some light on the issue and give us some findings to discuss with LH or BGS.

**Comment by andaleliz** [comment]
>I thought the issue was they're missing an address in the downstream database that we're attempting to update but may still have an address in the profile.

@mtcA6 What downstream database are you thinking of?  In the ticket description you said something about an upstream system so I feel a little confused about all the streams involved here  🙃  As far as I know, the systems involved with C+P DD updates all tie back to MPI/VA Profile for addresses.

>Could you create an additional mock with different language?

echoing what Tom said, we're really not sure exactly what the deal is here. Given that, I don't think it's a good use of time to create mock-ups for scenarios we have not validated. I'm honestly not even sure what the language could say since I don't know what the issue is other than the mailing address is missing.

I'd like to hold off on more design work until we get the outstanding questions answered, if that's alright with you.

>this will take not an insignificant amount of time to work through. 

That's true. There's already a ticket created somewhere, so it's possible some work or at least preliminary evaluation has been done. If that's the case, hopefully at least the first few steps of the process are complete.

>I think we should move forward with an alert that doesn't depend upon the decoupling piece.

Good call. I agree that trying to get this decoupled should be something separate from the alert work we have in progress now.

---
>Another option is to add more logging to the update function in vets-api to record more data around this error. For example, when this error is returned from LH, we can log more data points that tell us if the user has a mailing address, if they have a BAI flag, etc. We don't need to record any PII data, just whether or not certain data fields are present. This should help shed some light on the issue and give us some findings to discuss with LH or BGS.

@tpharrison this is a great idea!  Is that a easy thing to do? I wonder if we could even test with staging users to see what's returned and what triggers the error.

**Comment by tpharrison** [comment]
@andaleliz It should be pretty easy to add more logging and we should be able to test in staging.  Actually, we can probably delete a mailing address (or add a BAI) for a staging user and then see what happens when we update their DD info.  I'll run some tests in staging later today.

Also - Lorri Glover is meeting with BGS later today and will hopefully be able to get some answers.
Slack thread - https://dsva.slack.com/archives/C03P6C3FYMR/p1694616584293759

**Comment by mtcA6** [comment]
@andaleliz setting this back to the backlog while we work on getting the answers you need.
