### ISSUE TITLE
BE | Profile | Direct Deposit | Error Handling for Payment Address Data Not Found

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#64364]
## Background
Datadog logs are showing that Direct Deposit `GET` requests are returning `502 Bad Gateway` responses with a message of `Payment Address Data Not Found`.

This response type is due to a patch that Lighthouse released on Aug 10th.

The response to the FE should contain a code that can be used to more easily identify this situation/error.

## Tasks
- [ ] Add BE parsing to parse response with error code.
- [ ] Add BE specs to test response.
- [ ] Make request for mocked response to LH so we can test in staging.
  
## Acceptance Criteria
- [ ] Test in staging.
- [ ] Verify metrics in GA.
