### ISSUE TITLE
Incoming Issues Tracking - Per Sprint #13

### ISSUE THREAD

**Issue by Kimberley2023-CSM** [department-of-veterans-affairs/va.gov-team#64362]
## Issue Description
Contact Center will review and track all incoming issues escalated from VEO_

---
## Tasks
- [x] Tabulate incoming issues into categories - Tier 2/Tier 3/Tier EVSS
- [x]  Create a grid displaying the number of incoming issues for each category
- [x]  The grid shall include how many of the existing issues have been resolved
- [ ]  The grid shall include the number of unresolved issues for each category
- [x]  Publish report for leadership at the end of each Sprint
## Acceptance Criteria
- [x]  Report published for leadership viewing
- [x]   Report shall include quantity of incoming issues, resolved issues and remaining unresolved issues on a biweekly end of Sprint basis

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHdKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6e42fecab263502264010caad9970f4270e0672d/image.png" alt="image.png" />
