### ISSUE TITLE
Support: Mon-Thur Deploy (S35)

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#64367]
## User Stories
As a Platform team member who just contributed to the Platform website,
I need my content published,
so that I can share my content updates with the intended audience.

As a content team,
we need to review any new content changes made on the platform,
so that we can deploy every Tuesday and Thursday of the week.

## Tasks
Someone from our team will use Scroll Viewport to publish changes to the website after 3pm EST on:

- [x] Wednesday (8/30) - Brian/Torri
- [x] Thursday (8/31) - Jill
- Monday (9/4) - LABOR DAY
- [x] Tuesday (9/5) - Brian
- [x] Wednesday (9/6) - Torri
- [x] Thursday (9/7) - Jill
- [x] Monday (9/11) - Lauren
- [x] Tuesday (9/12) - Brian

Temporary Wednesday rotating schedule:
https://vfs.atlassian.net/wiki/spaces/CIT/pages/2405171201/Deployment+rotation+schedule

## Acceptance Criteria

- [x] The Platform website will be deployed Monday-Thursday between 3:30 and 5pm for this sprint.
- [x] Any edits with launch-blocking issues will be announced to their content editors via #platform-content

## Other Info

Data tracking info:
https://vfs.atlassian.net/wiki/spaces/CIT/pages/2282979860/KPIs+-+Content+Support
