### ISSUE TITLE
[CONTENT] Research and write PHILADELPHIA, PA System Health Services and Program Intro (Otolaryngology-Physical_med) [CONTENT]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#6437]
## User Story or Problem Statement
As a Veteran Web user, I need a System description of services provided at VAMC, so I can understand and best chose the services and service location for my needs.

## Goal
_Efficient and clear content describing local Health Service provided_
_Efficient plain language for Health Services and Health Service Program Intro_

## Objectives or Key Results this is meant to further
- _Reduced word count and improved plain language._

## Resources - Tools - Documentation
[Philadelphia Health Services Content Playbook](https://drive.google.com/drive/folders/1pNWn2vZmb8v3dJ0NTdx2VviqHhhjZK8Q)
[Philadelphia Health Services:A-Z](https://www.philadelphia.va.gov/services/index.asp)
[Pittsburgh Patient Advocate Program Link](https://www.va.gov/pittsburgh-health-care/patient-advocates/)

## Tasks
_Tasks that must be complete using content playbook criteria for the following Health Services, and Health Service Program Intro:_
- [ ] Otolaryngology
- [ ] Pain management
- [ ] Patient advocates (Health Service)
- [ ] Patient advocates (Health Program)
- [ ] Pharmacy
- [ ] Physical medicine and rehabilitation

## Acceptance Criteria
_Items that must be written and documented in Content Approval Folder under the correct VAMC System folder (i.e. Altoona, Butler)_
* Otolaryngology
* Pain management
* Patient advocates (Health Service)
* Patient advocates (Health Program)
* Pharmacy
* Physical medicine and rehabilitation
