### ISSUE TITLE
BE | Profile | Datadog Monitoring | Add Service for Profile Controllers

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#64382]
## Background
A Datadog service represents a logical grouping of related resources within the environment. It's a way to organize and categorize components of an application. 

If possible, the Profile team wishes to group Profile related controllers together under a Profile API service. By grouping these resources under a single service, we can analyze the performance of the profile as a whole.

The following controllers support the Profile page:

- V0::DisabilityCompensationForm (just rating_info)
- V0::Profile::Addresses
- V0::Profile::AddressValidation
- V0::Profile::CH33BankAccounts
- V0::Profile::CommunicationPreferences
- V0::Profile::DirectDeposit::DisabilityCompensations
- V0::Profile::EmailAddresses
- V0::Profile::FullName
- V0::Profile::GenderIdentities
- V0::Profile::PersonalInformation
- V0::Profile::PreferredNames
- V0::Profile::ServiceHistory
- V0::Profile::Telephones

## Questions:
- Should multiple services be created.  For example - Profile, Contact Info, Personal Info, Direct Deposit, Military Info, etc.
- Should the service be grouped by endpoint instead of controller?

## Tasks:
- [ ] Open Platform Support Ticket to request help and discuss further.
- [ ] Add Service (if possible)
- [ ] Share service with team

## Acceptance Criteria
- [ ] Review in productcion

**Comment by tpharrison** [comment]
Duplicate
