### ISSUE TITLE
[Rated Disabilities to Lighthouse] Create BE Controller

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#64406]
## Background
We need to create a new controller for Rated disabilities. There is existing code related to another teams efforts to migrate rated disabilities from EVSS to LH, but they stuck very closely to the existing design pattern and we would like to break away from that. The primary example is that LH provides both total rated disability and individual disability ratings in the same API response, whereas EVSS had it split into two different API responses. We would like to get both pieces of info from the same API call, so a new controller is needed to accomplish this

## Tasks
- [x] Create a new controller for rated disabilities
- [ ] Write rspec tests to test the functionality of the new controller

## Acceptance Criteria
- [ ] We are able to get both total disability rating and individual rated disabilities from the same API call
