### ISSUE TITLE
Pension ITF Report for VBA

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#64403]
## Issue Description
_As the VBA team who processes applications for pension, I need the "intent to file" date for each in-progress claim stuck in-progress after the digital pension application is deactivated, so that we can establish the ITF date when the paper claim is submitted._

---
## Tasks
- [ ] The date the 527 form is deactivated, generate a csv report for all in-progress claims that includes the following fields:
   - [ ] SSN
   - [ ] File Number (if available)
   - [ ] date and time of first-saved-date of claim
   - [ ] First Name
   - [ ] Last Name
   - [ ] (If possible) DOB

Helpful thread on 526 ITF report created by Kyle Soskin is [here](https://dsva.slack.com/archives/CBU0KDSB1/p1691617078012779?thread_ts=1691591736.796649&cid=CBU0KDSB1) and [here](https://dsva.slack.com/archives/CBU0KDSB1/p1691672493063519?thread_ts=1691591736.796649&cid=CBU0KDSB1).

## Acceptance Criteria
- [ ] Report is generated and provided to Laura Steele
---

**Comment by vbellissimo** [comment]
This was completed on 11/27/23, but not all the data was shared (we limited it to SSN). Closing this now.
