### ISSUE TITLE
BE | Profile | Datadog | Direct Deposit Dashboard

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#64400]
## Overview
A Datadog dashboard is a visual representation of the data collected and monitored by Datadog. It's a customizable, real-time view that allows you to display relevant metrics, graphs, charts, and other visualizations in one place. Dashboards are essential for monitoring the health, performance, and other aspects of your applications and infrastructure.

Datadog dashboards are composed of widgets that show metrics from various sources, such as application monitoring (response times, error rates), logs, and traces. You can customize the layout of the dashboard, add widgets for different services or components, and create different dashboard views for different teams or purposes.

Goal:

The goal of this dashboard is to display a high-level overview of the health of all Profile: Direct Deposit supporting vets-api controllers.  Some specifics:

- Show visualization of all controllers that support the Profile Direct Deposit feature.
- Display the overall health of each controller and controller action.
- Provide the ability to drill into each controller to get more details about it's health and status.

Possible widgets:

- **Time Series** display one or more metrics or log events for each controller, over time.
- **Pie Chart** display a single dataset with corresponding proportions (success / errors)

## Tasks:
- [ ] Open Platform Support Ticket to request help and discuss further.
- [ ] Add Service (if possible)
- [ ] Share service with team

## Acceptance Criteria

-  [ ] Review in production

**Comment by tpharrison** [comment]
Duplicate ticket.
