### ISSUE TITLE
BE | Profile | Direct Deposit | Update Sentry error logging

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#64408]
## Background
We're not getting enough detailed logs in Sentry.

## Tasks
- [ ] Update Sentry logging to fire off more logs.
  
## Acceptance Criteria
- [ ] Add specs
- [ ] Verify in staging
- [ ] Verify in production
