### ISSUE TITLE
BE | Profile | Datadog | Review Direct Deposit Monitors and Alerts

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#64401]
## Background
For the [Code Yellow Initiative](https://dsva.slack.com/archives/C909ZG2BB/p1699368184205899), Steve Albers created Direct Deposit monitors that when triggered, will send notifications to the [#accountexp-authexp_alerts](https://dsva.slack.com/archives/C02SYJGH8FJ) channel.

##  Tasks
- [x] Review Datadog Monitors
- [x] Make any necessary adjustments

## Acceptance Criteria
- [x] Review any changes with Steve Albers
