### ISSUE TITLE
Update Staging Review findings template

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#64417]
## User Story
As a Governance team member, I want to redesign the template used to communicate findings at SR to VFS teams so that VFS teams are receiving the information they need to know in a clear, reliable and consistent manner, allowing for swift action.

Assignee: @erinrwhite 
Peer Reviewer: @shiragoodman 

## Description
Governance team has written updated VA.gov Experience Standards. Before communicating our updates with OCTO for review and approval, we need to modify the template used to communicate standards violations to VFS teams at Staging Review. The current information captured in the ticket may not be relevant or helpful with the new VA.gov Experience Standards. In addition, we need to ensure we're capturing the tertiary information (at the label level, but possibly within the body of the ticket too). We also want to ensure we're capturing whether the issue is launch-blocking or not within the body of the ticket AND as a label (see comment to this ticket for additional details). 

The information we currently capture in the body of the ticket includes:

- General Information
   - VFS Team Name
   - VFS product name
   - VFS feature name
   - Point of contact/reviewers
- Platform Issue
- Issue Details
- Link, screenshot or steps to recreate
- VA.gov Experience Standard 
- Other References
- Platform Recommendation
- VFS Guidance (this should not need any change)

_Note: some of the information above is likely still relevant and should still be captured, however may benefit from a rename._

The label information we currently capture includes:

- Default labels
   - `collab-cycle-feedback` 
   - `CC-Dashboard`
- Practice area labels ( `accessibility`, `content`, `design`, `IA`, `QA`)
- Collaboration Cycle touchpoint label (`staging`)
- Severity label (`launch-blocking`)
- VA.gov product labels
- VFS Team Labels
- VA.gov Experience Standard label (`CCIssueXX.YY`)
- Accessibility labels (`a11y-defect-0`, `a11y-defect-1`, `a11y-defect-2`, `a11y-defect-3`, `a11y-defect-4`)

## Impacted Artifacts
Drafting Template - Github Upload tab (to be updated in a separate ticket - #63505)
[Staging Review findings - issue template](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2548957608/Staging+Review+findings+-+issue+template) Confluence page
[Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket)
[How to Add Images to the Staging Review DraftingTemplate](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2396619099/How+to+Add+Images+to+the+Staging+Review+DraftingTemplate)

## Tasks
- [x] Design draft of new Staging Review findings issue template 
   - [x] Body of ticket with identified fields
   - [x] Launch-blocking or not
   - [x] Labels assigned to ticket
   - [x] Title of ticket
- [x] Specify which fields will be default and which fields will be custom per Governance team findings
- [x] Share with Governance team for feedback and consensus
- [x] Once team is in agreement, complete the following:
   - [ ] Draft changes to the Anatomy of a Staging Review Issue ticket document (do not publish)
   - [ ] Draft changes to the Staging Review findings - issue template Confluence page (do not publish)
   - [x] Determine if changes need to be made (just a yes/no) to the How to Add Images to the Staging Review DraftingTemplate guidance. If yes, update ticket #63505
   - [x] Convert 2-3 historical issues into the new template to share with OCTO during review

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have redesigned the Staging Review findings issue template in Github
- [ ] We have made changes to our operational and VFS-facing guidance (minus the DraftingTemplate) to reflect the changes to the Staging Review findings issue template

## Team Notification
- [ ] Slack post on #platform-governance-team
- [x] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
This ticket should include the following:
<img width="547" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/71330581/f8721f29-6fc2-4d0c-87e1-59714b0bdb9f">

**Comment by erinrwhite** [comment]
Working on a [google doc draft](https://docs.google.com/document/d/1aXnpOa_U80C-QyBgljofTDrgwtdH3QcdXGJlNUPA1CE/edit) of the issue template.

**Comment by erinrwhite** [comment]
moved over to github - drafting [blank issue template](https://github.com/erinrwhite/stagingreview-mods/issues/1)

**Comment by erinrwhite** [comment]
@shiragoodman can you take a look at this [draft ticket](https://github.com/erinrwhite/stagingreview-mods/issues/1)? I created this in a personal repo to keep it from confusing folks on the `va.gov-team` project but/and can happily move it over.

Would this be an acceptable artifact to share with the team for feedback?

**Comment by erinrwhite** [comment]
On Monday 10/23, reviewed [draft issue template](https://github.com/erinrwhite/stagingreview-mods/issues/2) with team and made adjustments.

Sample tickets with real data:
[Unexpected interaction](https://github.com/erinrwhite/stagingreview-mods/issues/2)
[Necessary flow](https://github.com/erinrwhite/stagingreview-mods/issues/3)

**Comment by erinrwhite** [comment]
Team agreed the new template is looking good! 

In chatting with @shiragoodman we also discussed moving these to-do's to a Post-OCTO ticket:

- Draft changes to the Anatomy of a Staging Review Issue ticket document (do not publish)
- Draft changes to the Staging Review findings - issue template Confluence page (do not publish)

**Comment by shiragoodman** [comment]
Yes, agreed @erinrwhite ! The 2 documentation changes will occur after syncing with OCTO on the new standards. 

This is good to close!

**Comment by erinrwhite** [comment]
Thanks so much @shiragoodman ! Closing...
