### ISSUE TITLE
Reorganize Moderator Responsibilities for Staging Review

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#64433]
## User Story
As a Governance team member, I want to find the Staging Review guidance I need when I need it so that I am able to complete the task at hand quickly and easily.

As a Governance team member, I want to be able to easily understand the Staging Review task at hand, so that I'm not spending more time on the task than needed.

Assignee: @allison0034 
Peer Reviewer: @erinrwhite 

## Description
Governance team would like to improve the organization of the moderator responsibility docs. The goal of this ticket is to split the main sections of the document into separate documents (Pre-schedule, Schedule, Schedule, Generate Staging Review Issue tickets, During Meeting, Post Meeting), group steps in each section that require modifications to the same tools to avoid context switching (ie Slack, gh ticket), reorder the steps within each section so that they occur in a logical and meaningful order, and to name the steps so that it is easy to see what goal each step is trying to accomplish.

In addition, now that we're splitting up this guidance doc into 3 or 4 guidance docs, we no longer need to retain the name "moderator responsibilities." Whatever we rename the docs, they should:

1. Have a consistent naming convention across Design Intent, Midpoint Review and Staging Review.
2. Indicate that this is the responsibility of the host/moderator, and does not need to be referenced by the full team at each touchpoint
3. Be short and succinct. Let's avoid naming our new docs "Design Intent - Moderator Responsibilities - Before meeting". Shorten it up somehow!

Note: since reorganizing Design Intent and Midpoint Review has been completed before this ticket, the Staging Review guidance should follow the same naming convention. 

## Impacted Artifacts
[Staging Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review+-+VFS+-+Moderator+Responsibilities)

## Tasks
- [x] Split doc into separate pages
   - team agreed to merge pre-schedule and schedule, and then delete the pre-meeting section as this is completed at standup
- [x] Rename pages appropriately
- [x] Review steps within each section and identify if any can be merged due to work occurring within the same tool and/or space
- [x] Reorder steps so that events occur in a logical and meaningful order
- [x] Apply names to each steps that explain the high level goal of each step
- [x] Review all documents to identify if there's any other opportunities for improvement. If so, list steps below and make changes to docs. If none are identified, please write N/A:
   - Removing some excess content would be helpful
   - Rewriting the script and making bullet points makes it easier to read

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have split the Staging Review - Moderator Responsibilities guidance into separate guidance docs.
- [x] We have reorganized, merged steps and added clarity to the moderator guidance for Staging Review

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
Pre-PTO update: [Draft for the scheduling instructions started](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2793079112/64433+-+Staging+Review+Moderator+Responsibilites), but not finished -- and the in-meeting and post-meeting instructions haven't been started yet.

But I think I got through some of the staging-specific stuff (eg. all the Drafting Template stuff), so hopefully most of the rest can be easily adapted from the Design Intent and Midpoint Review documents.

Good luck!

**Comment by shiragoodman** [comment]
Brian is on PTO for 3 weeks starting today so this ticket has been reassigned to @allison0034

**Comment by allison0034** [comment]
Moving to the next sprint as I just picked this up.

**Comment by allison0034** [comment]
Made a [during the meeting draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2798780417/64433+-+Staging+Review+-+During+the+meeting).

**Comment by allison0034** [comment]
Finished Brian's Draft for the scheduling instructions draft.

**Comment by allison0034** [comment]
Created [after meeting draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2798944257/64433+Staging+Review+-+After+the+Meeting)

**Comment by allison0034** [comment]
@erinrwhite this is ready for your review. I took the [Staging Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review+-+VFS+-+Moderator+Responsibilities) and broke it out into the following:
[Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2793013665/64433+-+Staging+Review+-+Scheduling)
[Generate Staging review issue tickets](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2800189482/64433+-+Allison+-+Generate+Staging+review+issue+tickets)
[Staging Review - During the meeting](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2798780417/64433+-+Staging+Review+-+During+the+meeting)
[Staging Review - After the Meeting](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2798944257/64433+Staging+Review+-+After+the+Meeting)

**Comment by erinrwhite** [comment]
This is looking great! I had some minor edits to each page. 
- On the [scheduling page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2793013665/64433+-+Staging+Review+-+Scheduling) I clarified the drafting template instructions slightly on the protected ranges section - it's tricky!
- Added a little more about pre-meeting prep on the [during the meeting](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2798780417/64433+-+Staging+Review+-+During+the+meeting) page
- Updated the TOC on the [after meeting page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2798944257/64433+Staging+Review+-+After+the+Meeting).

I think these are ready to roll.

**Comment by shiragoodman** [comment]
great call out, @erinrwhite ! thank you. I'll take a look at the new ticket and get it ready for next sprint.

**Comment by allison0034** [comment]
Perfect! Thanks @erinrwhite I will move these pages to production!
