### ISSUE TITLE
PM | Profile | Auth Menu | Phased Release (🚨 100% 🚨 )

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#64430]
## Monitoring

- [GA Dashboard](https://analytics.google.com/analytics/web/#/dashboard/jTwco5hFRBmuXcjZN9YSPA/a50123418w177519031p176188361/_u.date00=20230901&_u.date01=20231004/)

## Release Plan

- [Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/authenticated-menu/add-dependents-letter/release-plan.md)
- [Prod go/no-go ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64424)
 

## Tasks

```[tasklist]
### 100% rollout
- [x] Update feature flags to make the feature visible in Production for 100% of users
- [x] Track/monitor analytics
- [x] Validate on Prod with PM and PO
```

## Acceptance Criteria
- [ ] feature is fully deployed in production
