### ISSUE TITLE
Reorganize Moderator Responsibilities for Design Intent

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#64431]
## User Story
As a Governance team member, I want to find the Design Intent guidance I need when I need it so that I am able to complete the task at hand quickly and easily.

As a Governance team member, I want to be able to easily understand the Design Intent task at hand, so that I'm not spending more time on the task than needed.

Assignee: @briandeconinck 
Peer Reviewer: @CherylEvans 

## Description
Governance team would like to improve the organization of the moderator responsibility docs. The goal of this ticket is to split the 3 main sections of the document into 3 separate documents (Schedule, During Meeting, Post Meeting), group steps in each section that require modifications to the same tools to avoid context switching (ie Slack, gh ticket), reorder the steps within each section so that they occur in a logical and meaningful order, and to name the steps so that it is easy to see what goal each step is trying to accomplish.

In addition, now that we're splitting up this guidance doc into 3 guidance docs, we no longer need to retain the name "moderator responsibilities." Whatever we rename the docs, they should:

1. Have a consistent naming convention across Design Intent, Midpoint Review and Staging Review.
2. Indicate that this is the responsibility of the host/moderator, and does not need to be referenced by the full team at each touchpoint
3. Be short and succinct. Let's avoid naming our new docs "Design Intent - Moderator Responsibilities - Before meeting". Shorten it up somehow!

## Impacted Artifacts
[Design Intent - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Moderator+Responsibilities)

## Tasks
- [x] Split doc into 3 separate pages - 1 for each section (Prescheduling and Scheduling can be merged) 
   - [Design Intent drafts](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2764242968/64431+-+Design+Intent+Moderator+Responsibilities)
      - [Design Intent - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2763718706/%2364431+-+Design+Intent+-+Scheduling)
      - [Design Intent - During the Meeting](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2763751454/64431+-+Design+Intent+-+During+the+Meeting)
      - [Design Intent - After the Meeting](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2763817045/64431+-+Design+Intent+-+After+the+Meeting)
- [x] Rename pages appropriately
- [x] Review steps within each section and identify if any can be merged due to work occurring within the same tool and/or space
- [x] Reorder steps so that events occur in a logical and meaningful order
- [x] Apply names to each steps that explain the high level goal of each step
- [x] Review all 3 documented to identify if there's any other opportunities for improvement. If so, list steps below and make changes to docs. If none are identified, please write N/A:
   - As applicable, matched the new formatting from the Kickoff documentation (heading structure, resource tags in each section).
   - During the meeting, rephrased some steps to provide explicit sample text for what to say.
      - Example: "Confirm requested attendees are in attendance. If anyone is missing, confirm with the PM if it is okay to start without them. Ask PM if they’re waiting on anyone else." becomes "Ask the VFS PM: Is everyone from your team here? If anyone is missing, ask the VFS PM: Is it okay to start without them?"
   - Moved script out of the misused table cell for accessibility purposes. Using a gray background instead, and matching gray-for-gray with other sample text.
   - Did not change script contents, but did reformat it for readability.
   - Made explicit some things that have always been assumed / learned from experience. Example: When and how to interrupt to keep the meeting moving and ensure everyone gets a chance to provide feedback.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have split the Design Intent - Moderator Responsibilities guidance into 3 separate guidance docs.
- [x] We have reorganized, merged steps and added clarity to the moderator guidance for Design Intent

## Team Notification
- [x] Slack post on #platform-governance-team (for both changed to Kickoff and Design Intent)
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Be sure to coordinate with the assignee for #64527 as both tickets include updates to the Design Intent - Moderator Responsibilities guidance.

**Comment by allison0034** [comment]
@shiragoodman I have a few suggestions. I think we all agree trying to read these scripts, follow the directions and provide feedback is a huge pain point.

1. Consider removing any unnecessary content in the scripts. They are long and boring and after a team has heard them 2/3 times they are pointless. We even had VFS teams comment on "the boring" script.
2. Consider just screen sharing the script at the beginning of the meeting and not reading. It is hard to keep our place in the script and then adjust to follow moderator directions and then adjust again to provide feedback.
3. If we do keep reading the script consider removing the team and initiative part in the script... 
Welcome to the Design Intent for _______ team for ______ initiative. This may seem minor but we have to switch and look what team and initiative this is for and then go back to the script. Also, we originally put this in before we redid our request ticket. Previously we weren't always sure which team the recording was for but now that we have everything in an epic it is not necessary.

**Comment by shiragoodman** [comment]
@allison0034 thank you for sharing this with me! I appreciate the feedback. And I agree that the script is getting a bit stale. I'm 100% on board with a reboot. @erinrwhite had even suggested a while ago that we screenshare the script. [I created a ticket for it.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64088) 

The only objection I have to your proposed changes is that we need to continue to state the name of the review (VFS team and product) at the beginning of each recording. The reason for this is because the recordings titles in Zoom don't state the VFS team or product (they all have generic names - Collab Cycle touchpoint for 3:30pm ET on Tuesday), and when watching a recording, we need assurance that you're watching the RIGHT recording. This was an issue previously, which is why we started saying the team name and product name. 

Since @briandeconinck and @CherylEvans are the assignee and peer reviewer on this ticket, I'd recommend working with them to get your changes implemented. If the team is on board with your script changes, then so am I.

**Comment by shiragoodman** [comment]
@briandeconinck @CherylEvans @allison0034 

In reviewing Service Design teams analysis of our Design Intent meeting, I recognized there's a lot we will likely want to improve in our DI process, including the script. At this time, I ask that we NOT making any changes to our script. The purpose of this ticket is to focus on improving our usability of our guidance, and less on making changes to the processes detailed in our guidance. There will be time for that later on, but it is not the goal of this ticket and it not the goal of the Improve [Operational support process](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/gh/department-of-veterans-affairs/va.gov-team/63309) initiative. 

Please let me know if you have any questions/concerns.

**Comment by briandeconinck** [comment]
Moving this back to planned. I had originally thought I could do this and #63307 in tandem but my brain is having trouble keeping them straight!

**Comment by shiragoodman** [comment]
no worries, @briandeconinck !

**Comment by allison0034** [comment]
@briandeconinck I had to schedule a DI today so I made a few suggestions as far as content. Also, look at [this doc](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2737766401/Rescheduling+and+cancelling+touchpoints) and ask the team if they like this layout better. : )

**Comment by briandeconinck** [comment]
End-of-sprint update: Drafts have been started, aiming to complete early in the next sprint.

**Comment by briandeconinck** [comment]
@CherylEvans This is ready for your review!

**Comment by CherylEvans** [comment]
@briandeconinck Drafts? I probably overlooked them in this thread. :-)

**Comment by CherylEvans** [comment]
@briandeconinck Sorry, I see them up in the Task section.

**Comment by CherylEvans** [comment]
@briandeconinck I made minor grammatical/punctuation changes, but nothing big.  These look great! I will use the same format for MPR. The peer review is complete.

**Comment by shiragoodman** [comment]
can this be closed?

**Comment by briandeconinck** [comment]
Slack announcement posted, closing the ticket!
