### ISSUE TITLE
Reorganize Moderator Responsibilities for Midpoint Review

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#64432]
## User Story
As a Governance team member, I want to find the Midpoint Review guidance I need when I need it so that I am able to complete the task at hand quickly and easily.

As a Governance team member, I want to be able to easily understand the Midpoint Review task at hand, so that I'm not spending more time on the task than needed.

Assignee: @CherylEvans 
Peer Reviewer: @briandeconinck 

## Description
Governance team would like to improve the organization of the moderator responsibility docs. The goal of this ticket is to split the 4 main sections of the document into 3 or 4 separate documents (Schedule-Sync, Schedule-asynch, During Meeting, Post Meeting) (determine whether it makes sense to have schedule sync and schedule asynch in 1 doc or 2), group steps in each section that require modifications to the same tools to avoid context switching (ie Slack, gh ticket), reorder the steps within each section so that they occur in a logical and meaningful order, and to name the steps so that it is easy to see what goal each step is trying to accomplish.

In addition, now that we're splitting up this guidance doc into 3 or 4 guidance docs, we no longer need to retain the name "moderator responsibilities." Whatever we rename the docs, they should:

1. Have a consistent naming convention across Design Intent, Midpoint Review and Staging Review.
2. Indicate that this is the responsibility of the host/moderator, and does not need to be referenced by the full team at each touchpoint
3. Be short and succinct. Let's avoid naming our new docs "Design Intent - Moderator Responsibilities - Before meeting". Shorten it up somehow!

## Impacted Artifacts
[Midpoint Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Moderator+Responsibilities)

## Tasks
- [x] Split doc into 3 or 4 separate pages - 1 for each section (Prescheduling and Scheduling can be merged) 
- [Midpoint Review Drafts](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2773975230/64432+-+Midpoint+Review+Drafts)
      - [Midpoint Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2774335591/64432+-+Midpoint+Review+-+Scheduling)
      - [Midpoint Review - During the Meeting](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2773713265/64432+-+Midpoint+Review+-+During+the+Meeting)
      - [Midpoint Review - After the Meeting](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2773844384/64432+-+Midpoint+Review+-+After+the+Meeting)
- [x] Rename pages appropriately
- [x] Review steps within each section and identify if any can be merged due to work occurring within the same tool and/or space
- [x] Reorder steps so that events occur in a logical and meaningful order
- [x] Apply names to each steps that explain the high level goal of each step
- [x] Review all 3 documented to identify if there's any other opportunities for improvement. If so, list steps below and make changes to docs. If none are identified, please write N/A:
   - {insert opportunities here} 

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have split the Midpoint Review - Moderator Responsibilities guidance into 3 or 4 separate guidance docs.
- [x] We have reorganized, merged steps and added clarity to the moderator guidance for Design Intent

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
Created a working draft of [Midpoint Review Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2767847440/64432+-+Cheryl+-+Copy+of+Midpoint+Review+-+Moderator+Responsibilities+2)

**Comment by CherylEvans** [comment]
@shiragoodman @briandeconinck This ticket will continue into the next sprint.

**Comment by CherylEvans** [comment]
@shiragoodman @briandeconinck My drafts are in the Tasks section. I used the expandable folders to differentiate between MPR and AMPR. A few areas still need tweaking, but these should be mostly complete.  :-)

**Comment by briandeconinck** [comment]
Made a few minor tweaks and caught one weird formatting issue (Confluence being Confluence). Otherwise I think these are good to go! Publishing and closing the ticket!
