### ISSUE TITLE
Account for flat streamlined field in Form5655Submission

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#64459]
## Issue Description
In the `Form5655Submission#streamlined?` method we should check for either flat `"streamlined": true` or the complex type `"streamlined": { "type": "short", "value": true }` since it may be possible to be of either type based on persistence order. 

---
## Tasks
- [ ] Account for flat field

## Acceptance Criteria
- [ ] We can call `Form5655#streamlined?` with confidence
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
No longer needed
