### ISSUE TITLE
Update department FSR form changes prior to persisting

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#64457]
## Issue Description
There are a few changes that happen to the form json prior to VHA and VBA submissions in their `submit_#{type}_fsr` methods. This has led to some discrepancy between submitting through the `user` dependent worker and the `resubmission` worker. It may make sense to make these changes prior to saving in the db. 

---
## Tasks
- [ ] Verify what changes make sense to be persisted
- [ ] Update order of operations that the form changes happen
- [ ] Test changes

## Acceptance Criteria
- [ ] We persist VHA/VBA dependent data
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kjsuarez** [comment]
This ticket's work has been completed as part of #69334 which moves post-submission changes to form data into the FormBuilder class, before submission.
