### ISSUE TITLE
Isolate SharePoint and VBS FSR processing

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#64455]
## Issue Description
Our submit VHA FSR worker is currently processing the SharePoint and VBS upload in a single request. The failure of one could lead to the failure of the entire job. These two don't rely on each other so they should be processed separately.

---
## Tasks
- [x] Separate workers between SharePoint and VBS
- [x] Instantiate both when submitting an FSR
- [x] Test the two processes

## Acceptance Criteria
- [ ] We've isolated the SharePoint PDF upload and VBS API request
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
