### ISSUE TITLE
[Frontend] Select Accessories Order Page- API Integration 

### ISSUE THREAD

**Issue by mojaray2k** [department-of-veterans-affairs/va.gov-team#6447]
As a  veteran , I need to see what accessories I am eligible and not eligible to reorder so I can select what I wish to order. The reorder items, eligible Y/N flag and eligibility date are contained in the Reorder API. 

## Goal
Provide Veterans clear information of what accessories they can reorder and if they cannot reorder provide date that they can

---
## Tasks
- [ ] _Create page per design for selecting accessories to reorder 
- [ ] _Display information from Reorder API for an authenticated veteran with item description, description of device the item is for, eligibility status, if not eligible, eligibility date, quantity, last order date

## Acceptance Criteria
- [ ] _For a given test user who is authenticated, the correct items and eligibility status will be returned and rendered from API . the user will be able to click to reorder items and UI of 'added to order' will be displayed. 

## Def of Done
- [ ] Concrete task that needs to be completed (e.g., Updated error message for error code 001)
- [ ] Testing complete if needed (local, staging, prod)
- [ ] Important info documented in GitHub
