### ISSUE TITLE
Accessibility update: Fix accessibility issues in VA style guide

### ISSUE THREAD

**Issue by coforma-jamie** [department-of-veterans-affairs/va.gov-team#64483]
## Issue Description
A cursory audit revealed accessibility issues in the VA's [content style guide](https://design.va.gov/content-style-guide/) around the proper use of headings, descriptive links, and other "low hanging fruit" that can be fixed quickly.

Fixing these issues will results in a style guide that's more standards-compliant and easier to use by VA employees.

---
## Tasks

"Like this/Not this" issue

- [ ] You'll need to look for these on every page of the style guide. Then, follow the fix listed in [this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59528#issuecomment-1690304106).

[Abbreviations and Acronyms](https://design.va.gov/content-style-guide/abbreviations-and-acronyms)

- [ ] “Exceptions for page titles, headers, and meta title tags” should be an H3

[Bold & italic text](https://design.va.gov/content-style-guide/bold-text)

- [ ] There are a lot of duplicate links here. “See this page,” repeated multiple times, isn’t parsable by someone navigating the site by links using a screen reader. Link text needs to be descriptive and make sense out of context (see [descriptive link text examples](https://www.accessguide.io/guide/descriptive-link-text)).

- [ ] “Use bold text only in these cases” and “don’t use bold in these cases” should be H3

[Bulleted lists](https://design.va.gov/content-style-guide/bulleted-lists)

- [ ]  “Punctuation for bulleted lists” should be H2

[Button labels](https://design.va.gov/content-style-guide/button-labels)

- [ ] There are three “like this” items beneath the bulleted list item “Always take users to the right level of access for the CTA.” These items should be a sub-list/bullets.

- [ ] The three “like this” items have URLs that aren’t link. These should be linked and changed to descriptive text. For example, `<li>…benefits landing page like <a href=“https://www.va.gov/health-care”>VA health care</a>.</li>`

[Dates, times, phone numbers, and addresses](https://design.va.gov/content-style-guide/dates-and-numbers)

- [ ] Under “Dates and years,” “Exceptions” (without a colon) and “Years” should be H3, since they’re acting as headers here.

[System messages](https://design.va.gov/content-style-guide/error-messages/system)

- [ ] The “scheduled downtime notifications” and “unscheduled downtime notifications” tables need to be broken up into 3 tables each: site-wide, in-app, and sign-in page. You can use a table `caption` for each table’s heading: `<caption>Scheduled notifications, site-wide</caption>`

- [ ] This applies to all tables - table heading cells (TH) need a scope, either “row” or “col,” to indicate if it’s a heading for a row or a column. See the [Table accessibility considerations](https://design.va.gov/components/table#accessibility-considerations) for more info.

- [ ] The “maintenance banner link” in the first table sometimes links to “[https://design.va.gov/components/banner#before-maintenance”](https://design.va.gov/components/banner#before-maintenance%E2%80%9D), other times “[https://design.va.gov/components/banner”](https://design.va.gov/components/banner%E2%80%9D). If you’re duplicating link text, that link needs to go to the same place each time. So either 
- Change the link text when the URL is different, or
- Make sure they all link to the same URL

[Form labels](https://design.va.gov/content-style-guide/form-labels)

- [ ] All tables on this page need proper table header cells. The header cells should be TH (not TD), and each needs a scope. See the [Table accessibility considerations](https://design.va.gov/components/table#accessibility-considerations) for more info.

[Government forms](https://design.va.gov/content-style-guide/government-forms)

- [ ] Add a scope to the table headers (as referred to previously)

- [ ] Just a suggestion: would it be helpful to actually link to the forms listed under “Common government forms,” instead of just listing them out? Not sure :)

[Health content](https://design.va.gov/content-style-guide/health-content)

- [ ] Under “3. Avoid abstract language,” “Example 1” and “Example 2” should be H4.

[Links](https://design.va.gov/content-style-guide/links)

- [ ] Under “Embedded text links vs. CTA links,” “Use embedded text links…” and “Use UTA links…” should be H4.

- [ ] Under “Open internal links in the same tab and window…”, the first bullet point has a couple of weird characters in the ‘target=“_blank”’ code block.

[Naming and labels](https://design.va.gov/content-style-guide/naming-and-labels)

- [ ] The bold text “Don’t create new brands” and “Avoid alphabet soup syndrome” should be H3.

[Page titles and section titles](https://design.va.gov/content-style-guide/page-titles-and-section-titles)

- [ ] Under “Page titles,” “Exceptions” (without a colon) should be H3.

[Structure your content](https://design.va.gov/content-style-guide/plain-language/structure-your-content)

- [ ] I think the alt text on your example images should be more descriptive. Instead of “An example of using headers,” maybe it should be something like “An example of properly structured headers on a web page. The page title is H1, the first sub-heading is H2, and sub-headings within that section are H3.”? What do you think?

[Punctuation](https://design.va.gov/content-style-guide/punctuation#em-and-en-dashes-hyphens)

- [ ] Under “Em and en dashes,” “Em dash,” “En dash,” and “Hyphens” should be H3.

[Specific topics and programs](https://design.va.gov/content-style-guide/specific-topics-and-programs/)

- [ ] Under “How to suggest a topic or program entry,” the email address should be linked: `<a href=“mailto:vawebdesign@va.gov”>vawebdesign@va.gov</a>`

[Writing for SEO](https://design.va.gov/content-style-guide/seo)

- [ ] Under “Meta properties,” “Why they’re important” should be H3
- [ ] Under “Title tags,” “Additional guidance,” “Example,” and “Exception…” should be H4

## Acceptance criteria
- [ ] All tasks are complete
- [ ] @megzehn and @coforma-jamie will discuss possibilities for future a11y auditing (such as an auditing schedule)

**Comment by sara-amanda** [comment]
@coforma-jamie did you want to convert this from `medium` status to a `chipper` as you and @megzehn work on this?

**Comment by coforma-jamie** [comment]
@sara-amanda, I'm not the one making the updates, @megzehn is :) So @megzehn, if you'd like to convert this ticket to a `chipper`, let us know :)

**Comment by megzehn** [comment]
I think so, @coforma-jamie and @sara-amanda! The bulk of this work is done, but there are a few pieces that will take a little more coordination and effort. We will get to them as we can. If I understand chipper correctly, then I think that category makes sense :) 

Thanks all!

**Comment by megzehn** [comment]
Noting that I went through this list again and added [N/A] to items that have been revised and are no longer in the content guide. We're good to close this ticket @coforma-jamie!

**Comment by coforma-jamie** [comment]
This is ready for closure review @sara-amanda
