### ISSUE TITLE
[BE] vets-api Chip Library Error Mapping

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#64492]
## Description
Currently, vets-api CHIP service library sends a generic message with `unmapped_service_exception` code to upstream. Modify the service library code exception handling to pass through the chip service specific error messages.

## Tasks
- [ ] [BE] **Modify exception handling in service library**
- [ ] [BE] **Add rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by loripusey** [comment]
@kanchanasuriya this has been in 3 sprints, is there still work to complete?
cc: @anita-halici

**Comment by loripusey** [comment]
If we are still blocked on a PR, can we escalate to Kay?

**Comment by kanchanasuriya** [comment]
This PR is not blocked @loripusey. Opened the PR beginning of this sprint and toward mid of the current sprint, we discussed within the backend team and researched a couple of different approaches to handle the error. 

Currently working on implementing custom middleware for the chip library to pass through the error message from chip.  With new implementation, it will carry over next sprint.

**Comment by anita-halici** [comment]
Is this still 5 pointer then? it's been a 5 pointer eversince created
