### ISSUE TITLE
Patrick Black - Submit eQIP

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#64498]
## Issue Description
The VA requires a background check in order to grant access and credentials to individuals who are joining the org. As part of that, new employees are required to fill out, the process involves providing a significant amount of history and requires collecting that information and then working on getting it all entered properly.

---
## Tasks
- [x] Review eQIP instructions
- [x] Collect eQIP information
- [x] Fill out eQIP form

## Acceptance Criteria
- [ ] eQIP form has been submitted and accepted
