### ISSUE TITLE
[CHIP] Update to v1 facilities API

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#64491]
## Summary
The facilities API is deprecating v0 of the API at the end of February 2024. We need to make sure that our usage of it in CHIP facilitiesService is still valid. We also need to update the `FACILITIES_API_URL` config in each env to use the v1 path.

Link to [release notes](https://developer.va.gov/explore/api/va-facilities/release-notes) (see 8/24 release) 
Link to [slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1693330034021399)

## Tasks
- [x] [CHIP] make sure API usage is correct for v1
- [x] [CHIP] update environment variable for path to be v1
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Tested in staging.
- [ ] deployed on staging
- [ ] Prod validation:
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
