### ISSUE TITLE
[PM] My VA BAD section: Update 2 month stats for hiding "what benefits does VA offer?"

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#64494]
## Background
We need to update stats now that the "what benefits does VA offer" menu within the Benefit Application Drafts ("BAD") section on My VA has been hidden from users for 2 months. 

_Complete this on or after 10/29_

## Tasks
- [x] Update [2 month stats](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/my-va-small-initiatives/benefit-application-drafts-updates#measuring-success)
- [x] Share and discuss with Samara and team
- [x] Determine next steps for menu - do we permanently remove it or unhide it?

## Acceptance Criteria
- [x] Stats are updated
- [x] Decision on future of the menu (permanently hidden/removed or made visible again to all users)

**Comment by ajakabcin** [comment]
[Updated month 2 stats](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/my-va-small-initiatives/benefit-application-drafts-updates/README.md#measuring-success) - team is proceeding with formal removal of section from code.
