### ISSUE TITLE
[PM] My VA BAD section: Update 1 month stats for hiding "what benefits does VA offer?"

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#64493]
## Background
We need to update stats now that the "what benefits does VA offer" menu within the Benefit Application Drafts ("BAD") section on My VA has been hidden from users for a month. 

_Complete on or after 9/29_

## Tasks
- [x] Update [1 month stats](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/my-va-small-initiatives/benefit-application-drafts-updates#measuring-success)
- [ ] Share and discuss with Samara and team

## Acceptance Criteria
- [x] Stats are updated
