### ISSUE TITLE
[Design] My VA LOA1 updates: Update documentation post-implementation

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#64509]
## Background
After implementing the updates to the LOA1 state of My VA we'll need to do a review and update documentation.

## Tasks
- [x] Update use case documentation and user flows
- [x] Review FE documentation and make sure no additional changes are needed 
- [x] Confirm all sketch files are updated

## Acceptance Criteria
- [x] Documentation is updated

**Comment by aagosto90** [comment]
[Updated and created user flow for LOA1 use case documentation here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/use-cases/LOA1-use-cases/README.MD)
