### ISSUE TITLE
Update Design.va.gov and other public certs

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#6451]
## User Story or Problem Statement
Some of our public certs will be expiring soon and we will need to update them before that happens.

https://dsva.slack.com/archives/C37M86Y8G/p1583168202038100

## Goal
_Have certs updated_

---
## Tasks
- [x] _Update design.va.gov cert_

## Acceptance Criteria
- [ ] _All certs are updated and tested_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ricetj** [comment]
@ricetj to update
