### ISSUE TITLE
Add step to add milestone for "completed" tickets

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#64527]
## User Story
As a Governance team member, I want to ensure that the milestone is captured in the "completed" tickets so that I can measure dates touchpoints were completed and time between touchpoints.

Assignee: @erinrwhite 
Peer Reviewer: @CherylEvans 

## Description
Governance team began adding a milestone for each Collaboration Cycle Request initiative. Initially, only the request ticket, feedback tickets and finding tickets were going to be added to the milestone, but we recently realized that by adding the "completed" tickets (used to communicate touchpoint completion in Platform Governance sprint reports), we can measure the date a touchpoint occurred, as well as calculate time between touchpoints. 

The purpose of this ticket is to add a post-touchpoint step to the Moderator Responsibility docs for Design Intent, Midpoint Review and Staging Review so that when the "completed" ticket is created, it's also added to the appropriate milestone. 

Note: no need to create draft docs. Feel free to edit the live guidance.

## Impacted Artifacts
[Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)
[Design Intent - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Moderator+Responsibilities)
[Midpoint Review - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Moderator+Responsibilities)
[Staging Review - VFS - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review+-+VFS+-+Moderator+Responsibilities)
[Staging Review - Design System - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572124161/Staging+Review+-+Design+System+-+Moderator+Responsibilities)

## Tasks
- [x] In the post meeting or after meeting section of the moderator responsibility docs, at the step where the "complete" ticket is created, add a new line to the table for "Milestone" where the value is the VFS teams Collaboration Cycle Request name and ticket number (or Design System teams Staging Review Request name and ticket number). This might need some wordsmithing. 
   - [x] Kickoff   
   - [x] Design Intent
   - [x] Midpoint Review
   - [x] Staging Review - VFS
   - [x] Staging Review - DST

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The touchpoint "completed" tickets are added to the appropriate Collaboration Cycle milestone 

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Be sure to coordinate with assignee for ticket #63307 since both tickets include updates to Collaboration Cycle Kickoff - Moderator Responsibilities

**Comment by shiragoodman** [comment]
In addition, this ticket also has dependencies on ticket #64431 as both tickets include updates to the Design Intent - Moderator Responsibilities.

**Comment by CherylEvans** [comment]
@erinrwhite They look great! I added capitalization to the Design System Staging review draft, but other than that, they are perfect. Once the Team Notification tasks are completed, this is good to close. :-)

**Comment by erinrwhite** [comment]
Thanks much @CherylEvans - closing.
