### ISSUE TITLE
Improve QA & Testing for VAOSR (+VAOS suite)

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#6452]
## Description

There are testing processes that span the new VAOS UX team, VAOS mobile, and VA.gov. These range from test plan coverage for automated and e2e test to full regression testing of the VAOS flow (from user submission to scheduler action in Schedule Manager). 

We need to formalize a shared practice between the 3 groups on how we'll collect and execute our testing processes in the future for VAOS. 

## Desired Outcome
In completing this epic the 3 teams will have a shared understanding and practice for ensure full coverage of VAOS tool. This includes applicable documentation.

## AC
- [x] Adoption of TestRail per the practices of VSP (QA VSP Lead: @pjhill for reference)
- [ ] Standardized practice for managing / documenting UATs moving forward
- [ ] Define process for manual/regression testing from beginning of user flow in VA.gov to end of workflow in Scheduler Manager (need Marcy's assistance with defining shared team practice)
