### ISSUE TITLE
GA4: Web Components

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#64532]
## Issue Description
Reimplement GA4 tracking for reusable web components using GTM while transitioning away from GTAGs 

---
## Tasks
- [ ] Research best way to identify and remove/transition to data layer events existing GTAG events 
- [ ] Remap web components event parameters for GA4
- [ ] Allow Design System team to review GA4 web component mapping 
- [ ] Begin GTM implementation of GA4 web component tracking 

## Acceptance Criteria
- [ ] All web components have been mapped and reviewed
- [ ] Next steps for GTAG removal/transition to data layer events 
---
