### ISSUE TITLE
Configure Closed Testing of Slack/Sentry Integration - Message Formatting

### ISSUE THREAD

**Issue by hgbarreto** [department-of-veterans-affairs/va.gov-team#64537]
## Description
Need to finish configuring the message formatting for the new Slack/Sentry Integration notification channel

## Resources 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/62490

## Tasks
- [x] Determine if this is still needed with Gia or whomever was looking to get this implemented (Kevin Densing was on Benefits team; Jerek Shoemaker is new resource) 
- [x] According to research done in December, the benefits team and the public websites team were both looking for this information. Public websites team found the information they were looking for via DataDog. Slack thread [here](https://adhoc.slack.com/archives/C045LCF8WU8/p1703603388043069)
- [ ] What is the method of integration? 
- [x] If this is determined that it is no longer needed, 

## Acceptance Criteria
- [ ] Get message formatting to an acceptable state
- [x] Have stakeholders verify 

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by hgbarreto** [comment]
Continue trying to work around intercepting the payload. Once a suitable variable is discovered for the fields below, a little sprucing up to make the message readable is in order.
- Title
- Environment

**Comment by hgbarreto** [comment]
Adding @flooose @Kshitiz-devops

**Comment by LindseySaari** [comment]
We should look into using the Slack/Sentry plugin.

**Comment by jennb33** [comment]
We are limited by the current webhook options available to us

**Comment by LindseySaari** [comment]
The team originally requesting this change has withdrawn their request as they’ve found a path forward in Datadog instead. Following discussions with Clint, even minor fixes are not currently a priority as we plan to phase out Sentry in the coming months. While an official integration exists that we might consider, it doesn't really justify prioritization given our strategy to transition all Sentry functionalities, including events, alerts, etc. to Datadog. If we choose to explore this integration in the future, or if plans to deprecate Sentry change, the necessary configuration details are [available here](http://sentry.vfs.va.gov/settings/vsp/integrations/slack/). It appears that the `sentry-vsp app` [was initially set up by a VA administrator](https://dsva.slack.com/apps/A02A15W083G-sentry-vsp?next_id=0) if we choose to pursue this path moving forward (but highly unlikely).
