### ISSUE TITLE
[Design] My VA: Explore white card component on My VA

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#64557]
## Background
The design system/VA ecosystem appears to be moving toward a white card component over the gray card. We want to explore design concepts with that on My VA.

## Tasks
- [x] Mock up white card design component on My VA
- [x] Explore other uses of white card component
- [x] Share with team

## Acceptance Criteria
- [x] White card designs exist and reviewed with team

**Comment by aagosto90** [comment]
[Sketch mockup](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/K0ExOlV)

I propose that we hold onto these mockups knowing however we end up making changes to My VA and/or Profile we will probably utilize something closer to the white card style instead of gray, but no need to implement this now. Would you agree @ajakabcin and @Samara-Strauss ?

**Comment by ajakabcin** [comment]
Great work @aagosto90 - closing this out and good to have this in our back pocket for future consideration
