### ISSUE TITLE
Create documentation for Medallia

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#64562]
## Issue Description
_Update Medallia documentation on Contact Center confluence

---
## Tasks
- [x] _Create Medallia workflow
- [x] Document Medallia features 
- [x] Document all current Medallia surveys
- [x] Document all Medallia Survey questions _
- [x] Audit of existing documentation and then generation of to-do's (i.e. update specific content or create new content).
- [x] Determine where the documentation is going to live. Right now it is on both github and confluence and it's not worth managing it and keeping it up to date in both places. I am fine with either one BUT I am not sure how accessible our confluence page is to teams that aren't on the platform. We should check into that. 
- [x] How can we update the documentation to make it more streamlined when teams want to work with us on surveys?
- [ ] 

## Acceptance Criteria
- [ ] Publish complete Medallia User Guide 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
@aubreyarcangel and @ATMiddleton Maybe you already know this, but we have a bunch of Medallia documentation already available on Github and confluence. This ticket is pretty bare bones so it would be good to put some details around this so we know when this is done. Some things that come to mind for me:

- [ ] Audit of existing documentation and then generation of to-do's (i.e. update specific content or create new content).
- [ ] Determine where the documentation is going to live. Right now it is on both github and confluence and it's not worth managing it and keeping it up to date in both places. I am fine with either one BUT I am not sure how accessible our confluence page is to teams that aren't on the platform. We should check into that. 
- [ ] How can we update the documentation to make it more streamlined when teams want to work with us on surveys?

**Comment by ATMiddleton** [comment]
@aubreyarcangel and @ATMiddleton will collaborate to compile data and engage @starlow00

**Comment by ATMiddleton** [comment]
https://vfs.atlassian.net/wiki/spaces/Contact/pages/1794015358/Medallia+Product

Confluence updated with current Medallia description
