### ISSUE TITLE
[FSR] Update dependent count for gmt fetch to include spouse

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#64586]
### To be completed after staging review tickets are completed
Update API call to income limits back end to include spouse if the `isMarried` question is true. The dependent question content/phrasing needs to be updated by design so it's clear the veteran should not include spouse in the dependent count. 
Example:
 - Veteran selects "is married", and indicates they have two other dependents. The total number of dependents in the api request should be 3. 

---
## Tasks
- [ ] `Design` update dependent question content
- [ ] Update API call with condition for `isMarried`
- [ ] Update dependent question with clarity

## Acceptance Criteria
- [ ] Spouse is now included in the dependent count for income limits calculation
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
@denisecoveyduc - can you please provide clarification on what the approved copy is.
cc: @josephrlee , @mgleo

**Comment by denisecoveyduc** [comment]
9/14 update: Taking this to VHA before we decide to include spouses automatically. Will circle back with confirmation.

**Comment by HeatherRienks** [comment]
Per Design sync on 9/25/23, for VHA, yes we can include spouses automatically.

@denisecoveyduc will check with VBA.

**Comment by josephrlee** [comment]
Here is a screenshot of the dependents page that shows the Additional Info component: 
<img width="746" alt="Screenshot 2023-09-25 at 11 49 12 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/de3b5de3-2253-49a4-bc5d-943c17633bca">

**Comment by mgleo** [comment]
@denisecoveyduc Can you confirm on this ticket that VBA wants spouses included automatically? Thanks!

**Comment by denisecoveyduc** [comment]
Hi @mgleo Yes I did confirm with Melonie Wheeler who reached out the others from VBA. VBA is ok to have spouses included in the count for dependents for the FSR. IF you can let me know when that change goes live I will ensure to notify them so they can watch for those counts to change.

**Comment by HeatherRienks** [comment]
Per Backlog Refinement on 10/18, copy changes have been made in ticket #67622; closing this ticket
