### ISSUE TITLE
Feedback portal review process

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#64583]
## Purpose
HMW Portal submission --> action?

How/When should we review items submitted to the Feedback Portal?
Update: having an automated Domo dashboard eliminates this, unless team wants to take on addressing issues rather than presenting them

To make good on our bet for continuous feedback, the feedback must reach viable parties continuously as well.  What would be the best way for SDT to review the feedback as it comes in, and where/how should that get shared out?
-Constantly available repository?
-Directed communications to relevant team(s)?
-Who needs to see what? Page [here](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2737700945/Platform+Feedback+Portal+Log+Review).

### Bets:
-Teams are more likely to go to a Domo page (which many teams already use) to view these when they want to
-Seems like a good idea to also include these w/ Platform Satisfaction Survey readout

## Tasks
- [ ] Evaluate a method and frequency for SDT review. The goal of this review is to evaluate if it's clear what team can address this (and how severity affects the message to that team), if it's not clear than whether and how SDT might get advice on how it might be addressed, and if not how SDT could communicate content of report to general teams and/or leadership
- [x] Decided on MVP being Airtable to Domo
- [ ] decide whether we need to build out the airtable w/ additional functionality or references?
- [x] Get access to Domo Dashboard
- [x] Can hook Airtable data to Domo Dashboard?
- [x] create a test Domo page from Airtable data (many steps to learn [here](https://domo-support.domo.com/s/article/360043427613?language=en_US))
- [ ] Need to quantify/categorize qual input in Airtable?
- [ ] Share/announce resource
- [ ] Establish review cadence and process for SDT

## Acceptance Criteria
- [ ] Resource is created
- [ ] Resource is publicized

**Comment by twoangstroms** [comment]
Learned that Lainey is building a spreadsheet that should allow anyone to search for terms (such as "ArgoCD") and see what teams are associated with that product, which should help this process considerably. She will share link when it is ready.

**Comment by twoangstroms** [comment]
Ticket rolling over to next sprint to accommodate new thinking and research

**Comment by twoangstroms** [comment]
9/15: Moved back into In Progress to reflect iteration of work needed based on learnings.
