### ISSUE TITLE
Combine duplicate ReviewCardField component

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#6459]
## User Story or Problem Statement
As a front-end developer, I need help reduce overall container size, so I can improve the user experience on the VA website.

## Goal

Specifically, combine the (nearly) duplicate ReviewCardField component from form 526 all-claims & edu-benefits. Combining this code will reduce the overall package size.

These two files:
- https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/all-claims/components/ReviewCardField.jsx
- https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/edu-benefits/components/ReviewCardField.jsx

## Objectives or Key Results this is meant to further

- Reduce code size
- Improve mobile experience

## Tasks

- [ ] Combine duplicate ReviewCardField code
- [ ] Move the file into the `platform/forms-system/src/js/components` (or `platform/forms/components`?) folder

## Acceptance Criteria

- [ ] Combined file moved into platform folder
- [ ] Unit test for all-claims & edu-benefits still pass
- [ ] Move unit tests for the ReviewCardField into the platform test folder

**Comment by Mottie** [comment]
Closed by https://github.com/department-of-veterans-affairs/vets-website/pull/12013
