### ISSUE TITLE
Profile Dashboard Updates - Internals

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#64614]
## Issue Description

Need to make a few more updates to the [Profile dashboard](https://va-gov.domo.com/page/1834995012).

---
## Tasks
[ ] Add card for weekly browser counts similar to Top browser types on Forms dashboard (reduce size of bard chart and place this new card next to it so they can see trends and weekly total)
[ ] Add card for weekly OS counts - same format as described above
[ ] Add card for users counts per page_name, total for the week. table format similar to Top pages viewed before accessing form on the Forms dashboard

[Uploading... image.png]

[Uploading... image.png]

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
