### ISSUE TITLE
Forms Dashboard Updates - Data QA for 5655 & 21P

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#64662]
## Issue Description
This work is to be completed after [Data Prep 5655 & 21P](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/64654) is done.

Once the data has been added to the Domo tables we need to QA them against GA to ensure accuracy. 

The [QA worksheet tracker](https://docs.google.com/spreadsheets/d/1EgqyPVo7aUaRt0N5Yy_yEGmBCDOPQu1-80v-Wqy_8I4/edit#gid=0) has links to the GA reports needed (this is the one I created for last update, please make copy and save for this update).  Create 1 tab for each of the 2 forms. Segments and date ranges will need to updated in the reports for each of the 2 forms.

Resources:
[BQ forms funnel links](https://docs.google.com/spreadsheets/d/12Anw3W1EAf8xY8urxtTaMHla9fHK4sWnONFQnfSwyes/edit#gid=1109167657)
Request ticket for [5655](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/62443)
Request ticket for [21P](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/64026)
[Data Prep ticket](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/64654)
[How to Data QA Domo dashboards](https://vfs.atlassian.net/wiki/spaces/AT/pages/1821900905/How+to+Data+QA+Domo+dashboards)

---
## Tasks
- [x] Updated QA report created
- [x] QA pass/fail has been added for each metric as applicable
- [x] Screen shots GA reports with their respective metrics added for tracking

## Acceptance Criteria
- [x] QA completed as described above.
---

**Comment by ChristineYoungZA** [comment]
@michelle-dooley Here is the Link for the QA document I am working out of. The 21P is not showing up in the filtered menu in Domo. I am not able to produce the Not Submitted numbers it is showing 0 users when I update the Page conditions segment versus 3k in Domo. The successful submissions number differs from Domo. GA is showing 1,275 and Domo is showing 624. The Failures are showing 2 in Domo and GA. Could you take a look and provide feedback for the Not Submit portion to complete the rest of the QA? https://docs.google.com/spreadsheets/d/1DJQt3cnUwJDmfKcbrH2Yj4qNUFiJLq8dn5NxP8QuM48/edit#gid=0

**Comment by michelle-dooley** [comment]
I'm closing this ticket for this sprint. I will open a new ticket for the final QA on the 5655 funnel.
