### ISSUE TITLE
Pension Email Template

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#64679]
## Issue Description
_Draft the email template for the pension form deactivation email._

---
## Tasks
- [x] Add the [email copy](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62445#issuecomment-1695804763), links, and pdf attachment to the VA Notify email template. [Staging](https://staging.notifications.va.gov/) | [Production](https://notifications.va.gov/)
- [x] Test email for formatting issues

## Acceptance Criteria
- [ ] Email template ready for deployment
---

**Comment by fiorella-io** [comment]
Created the email template in staging called "21P-527EZ Pension Deactivation - In progress applications".
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbjViIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0e4ed0160d15598c45fde0f202e9749ed5b818f6/image.png)

**Comment by steele-lm** [comment]
@fiorella-io VA Notify confirmed that the tracking for the link within both the burial and pension deactivation emails [needs to be created within the template generator](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63614#issuecomment-1741315436). Is this something you can do? Once the form for the link is filled out, it will generate a tracking link, and we'll need to replace the existing link within the email with the new tracking link (for both the burial and pension emails). Let me know if you have any questions! cc @fred-khoury-oddball

**Comment by katherine-fung** [comment]
For reference, this is the final & approved email template that went out in November 2023: 

<img width="824" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTh1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8f41b41d7cf23246db192bd67a84e1bc129ee95/image%20%286%29.png" alt="image (6).png" />
