### ISSUE TITLE
Iterate on mid-fi mockups of custom app

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#64681]
As a veteran, I need an application to locate proofing sites and receive a case number to initiate in-person proofing.

As a proofing agent, I need an app that allows me to input veteran information, validate documents, and send encrypted data to Login.gov to tie accounts to closed cases.

## Tasks

- [x] gain access to Login.gov design system on Figma or use USWDS
- [x] confirm how and where to store files
- [x] apply design components to create high fidelity mockups

## Acceptance Criteria

- [x] meet with devs to show screens and receive feedback
- [x] finalize prototype for demo

**Comment by skirkman16** [comment]
No access to Login.gov design system so I referred to the US Web Design System. I finished iterating on all of the screens, so I will present the prototype to the devs this afternoon. There are two screens that require an API so I will be touching base on how to incorporate that.

**Comment by skirkman16** [comment]
Screens are [here](https://www.figma.com/file/PfrWKmxiQ5RjChwx6I18QE/IPP-Prototypes?type=design&node-id=360%3A6586&mode=design&t=o3F0PT6yJm4WOEiL-1) under Prototype 9/21. Clickable prototype is [here](https://www.figma.com/proto/PfrWKmxiQ5RjChwx6I18QE/IPP-Prototypes?page-id=360%3A6586&type=design&node-id=361-6914&viewport=1049%2C-787%2C0.25&t=rqbRPEislhGFCScP-1&scaling=min-zoom&starting-point-node-id=361%3A6914&mode=design)
