### ISSUE TITLE
Research content for veteran facing IPP mockups

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#64682]
As a veteran I need to know what in-person proofing is and how it could benefit me. I also need to know what I need to do to identity proof and why it is important for accessing my healthcare and benefits.

## Tasks

- [x] competitive research for IPP solutions
- [x] Meet to discuss purpose of content for each screen (first three screens of user flow)
- [x] draft content

## Acceptance Criteria

- [ ] share with Unified Comms group and present as draft
- [ ] share content with Login.gov 9/12 (include Carl as optional guest)

**Comment by skirkman16** [comment]
Login.gov will be responsible for the screens that Carl wrote content for. We have shared this content with them and we can continue to come up with content for our upcoming prototypes.
