### ISSUE TITLE
Draft content for veteran facing proofing app

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#64686]
## User Story
As a veteran, I need to understand what proofing is, how in person proofing could benefit me, and what I would need to do to in person proof.

## Tasks
- [ ] Draft content for veteran facing screens only
- [ ] Refer to content from Login.gov and documentation that explains identity verification
- [ ] Share out with stakeholders

## Acceptance criteria
- [ ] content is shared out at demo on updated mockups
