### ISSUE TITLE
Burial Email Template

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#64680]
## Issue Description
_Draft the email template for the burial form deactivation email._

---
## Tasks
- [x] Add the email copy, links, and pdf attachment to the VA Notify email template. [Staging](https://staging.notifications.va.gov/) | [Production](https://notifications.va.gov/)
- [x] Test email for formatting issues

## Acceptance Criteria
- [ ] Email template ready for deployment
---

**Comment by fiorella-io** [comment]
Created the email template in staging called "21P-530EZ Burial Deactivation - In progress applications".
When you log in to staging, sort by day created and the new template will show up.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2xiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cb167685c87d865f9bd5cc7973f874900cc66b2a/image.png)

**Comment by fiorella-io** [comment]
I've tested it an it looks good on outlook

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcHRiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ca9b4458f5c6d472c2dab17611dec04b0ebd004b/image.png)

**Comment by sortizsh** [comment]
Conversation with CAIA happening in this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/63614#issuecomment-1735863460

@steele-lm  can you please find us the UTM tracking ID for the "learn how to apply for a VA burial allowance" link in the email?

**Comment by steele-lm** [comment]
@sortizsh Already done! Thomas had the access needed to go in and generate the link and update the email!
