### ISSUE TITLE
[a11y-defect-4]: Wizard redirect alert when attempting sign in

### ISSUE THREAD

**Issue by ohgreatkate** [department-of-veterans-affairs/va.gov-team#64688]
### Point of contact

@ohgreatkate

### Severity level

4, Minor. Consider fixing or exploring in 2-4 sprints post-launch.

### Details

...
this alert is odd, the wizard information isn't saved anyway... the alert says to finish applying but you answer one more question and then you are required to log in. This creates a very frustrating pattern for the Veteran who wanted to sign in earlier. This should follow the same pattern as [VA form 28-8832](https://www.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/introduction), where you click "Sign in" and go straight to the Log in modal, without a "you'll lose your progress" prompt
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/77993286/bc501cc1-96df-4c10-ac39-0742fe628c8b)

### Reproduction steps

1. Be on wizard screen
2. click log in button
3.
...

### Proposed solution or next steps

...
remove alert prompt and allow users to sign-in even when wizard is partially complete

### References, articles, or WCAG support

1.
2.
3.
...

### Type of issue

- [ ] Axe-core
- [ ] Screenreader | assistive tech & device support
- [ ] Keyboard
- [ ] Zoom
- [ ] Color, typography, & visual elements
- [ ] Components and pattern standards
- [ ] Content organization
- [ ] Focus
- [ ] Headings
- [ ] Content style guide
- [ ] Link and button labels
- [ ] Semantic HTML
- [ ] Markup and metadata
- [ ] Non-text content and media
- [X] Overall user experience
- [X] Cognitive | user flows & navigating
- [ ] URL standards
- [X] Something else
```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/68010
```

**Comment by fiorella-io** [comment]
@ohgreatkate How do I get to this wizard? Whenever I'm on the [apply page](https://staging.va.gov/careers-employment/vocational-rehabilitation/apply-vre-form-28-1900/introduction), I only see a button to sign in. I don't see an option to apply without signing in. 
<img width="616" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/91498500/b4578c1a-0b16-4c29-897f-5b8a4c26ab63">

**Comment by ohgreatkate** [comment]
Hey @fiorella-io great question! It seems that I originally labeled this for the wrong team. This issue is for the [PCPG form 28-8832 ](https://staging.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-25-8832/introduction). Thanks for flagging that label error, let me know if I can add more guidance once you are able to review the other form. Thanks!!
