### ISSUE TITLE
[a11y-defect-4]: If logged in and there is a form in progress, the Veteran should not be directed through the wizard

### ISSUE THREAD

**Issue by ohgreatkate** [department-of-veterans-affairs/va.gov-team#64692]
### Point of contact

@ohgreatkate

### Severity level

4, Minor. Consider fixing or exploring in 2-4 sprints post-launch.

### Details

...
As a Veteran who already has a form in progress, if I navigate to the apply online page, I don't want to see the wizard and need to click through again before finding the alert on the next screen letting me know I can continue an application.

### Reproduction steps

1. sign in
2. navigate to form
3.
...

### Proposed solution or next steps

...
Three options:
1. Get rid of that wizard all together
2. Have the info prompt that there is an application in progress appear on the wizard screen (when logged in)
3. Have veterans directed to the introduction page after the wizard directly if there is a form in progress

### References, articles, or WCAG support

1.
2.
3.
...

### Type of issue

- [ ] Axe-core
- [ ] Screenreader | assistive tech & device support
- [ ] Keyboard
- [ ] Zoom
- [ ] Color, typography, & visual elements
- [ ] Components and pattern standards
- [ ] Content organization
- [ ] Focus
- [ ] Headings
- [ ] Content style guide
- [ ] Link and button labels
- [ ] Semantic HTML
- [ ] Markup and metadata
- [ ] Non-text content and media
- [ ] Overall user experience
- [X] Cognitive | user flows & navigating
- [ ] URL standards
- [X] Something else
```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/68012
```

**Comment by steele-lm** [comment]
@Midge-dev Here is the original CAIA ticket that outlines the issue.
