### ISSUE TITLE
Prepare to PDF the Submitted 686

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#6469]
## Story
As a Veteran submitting the 21-686c, I want a copy saved in my folder as a pdf for my records so that I can retain them as record, validate the submission, or any number of other pdf actions.

## Considerations
- This is a utility that is used throughout the platform and most likely leverages the submitted form schema through a process ending up as a pdf, that might then need to be sent or saved for the Veteran in their eFolder.
- Lighthouse has already built a VBMS uploading function that should help.
- The submission process and the creation of the pdf is most likely independent of each other, not interdependent.
- Can we test this pdf creation, eFolder saving in staging?
- If possible, it would be great to provide this to the user to download after submission
- Kevin M had some work done in this area
- URLs from Steve: 
  - https://github.com/department-of-veterans-affairs/vets-api/tree/master/spec/lib/pdf_fill/forms
  - https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/VA-Systems/VBMS/VBMS%20Web%20Services%20Startup%20Guide.pdf

## Tasks
- [x] Explore the relationship between submitted schemas and pdf creation
- [x] Address the field length, question text, question number, and question suffix recorded for each field

## Acceptance Criteria
- [x] Define and document the relationship between submitted schemas and pdf creation as well as any tasks that need to be addressed.  A proof of concept would be preferable.

## Next step
- [ ] Test pdf creation 
- [ ] Test pdf upload
- [ ] Leverage Lighthouse VBMS upload functions
- [ ] A pdf is found in the users eFolder shortly after submission via VBMS

**Comment by lihanli** [comment]
Filling out the 686 pdf would be pretty complicated and time consuming, it would probably take more than 2 weeks. I worked on the pdf filler library and filling out 21P-527EZ and 21P-530 pdfs. It would be much easier to copy all the questions and put the answers in text format. If that is a possibility then I would recommend doing that instead.

Issues with pdf filling:

- Every text field needs to have the field length, question text, question number, and question suffix recorded. This is because if a user's answers go over the maximum number of characters of the pdf field an additional info page has to be added to the end of the PDF and it has be sorted based on the question number and question suffix. 
- Questions that have an array of answers (e.g. marriages, dependents) are complicated to fill out and require editing the pdf and submission code in a special way.

**Comment by kathleencrawford** [comment]
[https://app.zenhub.com/files/133843125/57ea8fd5-db30-4e3e-8059-844e7a7d32e8/download](https://app.zenhub.com/files/133843125/57ea8fd5-db30-4e3e-8059-844e7a7d32e8/download)

**Comment by jason-gcio** [comment]
Rock. And. Roll!
