### ISSUE TITLE
Onboard product manager 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#647]
# Artifact 
- on boarded product manager

**Comment by rianfowler** [comment]
# Todo 
- [ ] Review current sprint plan 
- [ ] Transfer meetings ownership
- [ ] Review previous retrospective 
- [ ] Overview of site + high level architecture 
- [ ] Overview of engineering practice
