### ISSUE TITLE
NOD | Update analytics product KPI dashboard

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#64704]
## Value Statement
**_As a_** product team member
**_I want to_** request an analytics dashboard update
**_So that_** we can track the pages we've added in our dashboard.

---
## Background Context
We already have a DOMO dashboard, but because we've added new pages to the decision review form, we need to also add them to the dashboard for tracking.

## Acceptance Criteria
- [ ] Dashboard has been updated with new pages

## Tasks
- [ ] Update [this Google Sheet ](https://docs.google.com/spreadsheets/d/1opinCLJ-m60bnnLZQ0NyHj-cbAEXmQRJT9sYt8kyJ8A/edit#gid=0)with new URLs
- [ ] [Make an Analytics Product KPI Dashboard - Update Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=michelle-dooley&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&projects=&template=analytics-request-update-kpi-dashboard.md&title=Analytics+KPI+dashboard+update+request+for+%5BTeam%5D)
---
## Definition of Ready 
- [ ] Know what to include in the dashboard update and when to request

## Definition of Done
- [ ] The final result is reviewed and approved by designer and PM

**Comment by saderagsdale** [comment]
Submitted the Domo changes yesterday, waiting for implementation.
