### ISSUE TITLE
NOD | Update "addIssue" content

### ISSUE THREAD

**Issue by rocio-desantiago** [department-of-veterans-affairs/va.gov-team#64708]
## Value Statement

**_As a_** developer
**_I want to_** refactor the content related to error messages shared across the 3 forms: 995, 996 and 10182 (SC, HLR & NOD)
**_So that_** tech debt is reduced and so that future developers don't have to make the same change across the shared validations in SC, HLR & NOD redundantly.

## Background Context

- While refactoring the date validations, we noticed `errorMessages` (in 995) and `issueErrorMessages` (in 996 and 10182). Content/verbiage updates recommended by the legal team were updated in Supplemental Claims due to a review and HLR and NOD should also reflect those content update requested by the legal team. 
- Related ticket: [HLR | Refactor "addIssue" content into shared file](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65747)
- Content related to error messages in the following files will be refactored into the shared constants or content file:
  > src/applications/appeals/995/constants.js
  > src/applications/appeals/10182/content/addIssue.jsx

## Out of scope

* Other apps/forms not in Decision Reviews

## Tasks

- [ ] One shared file created
- [ ] Unit tests updated
- [ ] E2E tests updated
- [ ] Validate that forms functionality has not changed

## Definition of Ready 

- [ ] [SOURCE OF TRUTH](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/design/sourceofcontenttruth.md#error) has been UPDATED so that this work can begin

## Definition of Done

- [ ] Functionality not changed
- [ ] Reduced files

**Comment by saderagsdale** [comment]
@rocio-desantiago Before refinement tomorrow, can you review the code, list the tasks after review, and confirm if this story needs to be broken into smaller stories so the estimates aren't huge?

**Comment by rocio-desantiago** [comment]
Overall 2 points: 

- First task (1 point): have NOD and SC share the verified SOURCE OF TRUTH

For now only the following files `995` and `10182` (SC & NOD):
`src/applications/appeals/995/constants.js`
`src/applications/appeals/10182/content/addIssue.jsx`

- Second task (1 point):

Upon having content team confirm source of truth content for `996` (HLR), move addIssue content out of `src/applications/appeals/996/content/addIssue.jsx`

**Comment by saderagsdale** [comment]
@rocio-desantiago will split into two tickets and tag Sade

**Comment by saderagsdale** [comment]
@rocio-desantiago can you ping me when this is split?

**Comment by rocio-desantiago** [comment]
> @rocio-desantiago can you ping me when this is split?

Updated title for this one and HLR was separated into a new ticket [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65747).

**Comment by rocio-desantiago** [comment]
@eileen-coforma 
`recentDate: You must add an issue with a decision date that’s less than a year old` is missing from NODs source of truth.
