### ISSUE TITLE
NOD | Update error messages to be consistent with Supplemental Claims

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#64710]
## Value Statement

**_As a_** designer
**_I want to_** update error messages in NOD to match language used in SC
**_So that_** design debt is reduced and there is consistency in error messages for all decision review forms

## Background Context

- While refactoring the date validations, our developers noticed `errorMessages` (in 995) and `issueErrorMessages` (in 996 and 10182) had minor content discrepancies. ([dev issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64708))
- Content/verbiage updates recommended by VA content team were updated in Supplemental Claims because it was reviewed, and HLR and NOD should also reflect those content update suggested by the VA content team. 

## Acceptance Criteria
- [x] On Reason for Extension, check that the error reads 'You must provide a reason if you're requesting an extension.'
- [x] On issue page, check that the following error messages are set for the page in the code and match messages on [CSoT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/design/sourceofcontenttruth.md#error-alerts).
   - [x] Issues are not loading
   - [x] User does not have eligible issues
   - [x] User did not select an issue
   - [x] User tries to add 101 issues
- [x] On Area of Disagreement, add "you must" to error message to maintain consistency
- [x] On Board review option, add "you must" to error message to maintain consistency
- [x] On Conference type, add "you must" to error message to maintain consistency
- [x] On Review and Submit, add "you must" to error message to maintain consistency

## Out of scope

* Other apps/forms not in Decision Reviews

## Tasks

- [x] Update Source of Truth with error messages to match language from 
- [x] Get approval from enablement team

## Design & Build Notes

-[ NOD Content Source of Truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/design/sourceofcontenttruth.md#proposed-errors)

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [x] SOURCE OF TRUTH is updated
- [x] Changes approved by enablement team

**Comment by eileen-coforma** [comment]
Left a[ note for Julie](https://dsva.slack.com/archives/C5AGLBNRK/p1693574861548789) to review. If @rubensun can confirm and follow up on Monday, it'll be great. I've already briefed him on the topic.

**Comment by jstrothman** [comment]
Should the NoD follow the SC SoCT for `User did not select an issue`?

SC SoCT for not adding an issue:
```
#### You'll need to select an issue
You must select at least 1 issue before you can continue filling out your request.
```

NoD SoCT
```
Header: You'll need to add, and select, an issue
Body: You must select at least 1 issue before you can continue filling out your request
```

**Comment by jstrothman** [comment]
For NoD `User tries to enter 101 issues`, use contractions.

Change from:
```
Body: You are limited to 100 selected issues for each Notice of Disagreement request. If you would like to select more than 100,  submit this request and create a new request for the remaining issues.
```
to:
```
Body: You're limited to 100 selected issues for each Notice of Disagreement request. If you'd like to select more than 100,  submit this request and create a new request for the remaining issues.
```

**Comment by jstrothman** [comment]
For NoD `Reason for extension`, use contraction

Change from
```
You must provide a reason if you are requesting an extension
```
to
```
You must provide a reason if you're requesting an extension
```

**Comment by eileen-coforma** [comment]
Updated CSoT to reflect edits that Julie provided. This is ready for pickup in the backlog.

**Comment by saderagsdale** [comment]
@eileen-coforma will add AC so we know where to test

**Comment by saderagsdale** [comment]
@eileen-coforma and @kylesoskin to connect on documentation for responses and errors.

**Comment by eileen-coforma** [comment]
@Mottie pause on this for a second. 

I found this interesting [thread](https://dsva.slack.com/archives/C01K37HRUAH/p1713544348805399) in the CAIA channel that talks about removing "please" altogether without adding "you must". 

I want to make sure what the consensus CAIA has for these error guidelines.

**Comment by eileen-coforma** [comment]
@Mottie We are good to continue with 'You must'. They haven't set the guidelines in stone yet, and Beth mentioned the most important thing is to remove "please" from our error messages.

**Comment by Mottie** [comment]
Actually, the work for NOD has been completed by Rocio. I was using this ticket to add the alert on the introduction page for missing SSN, DoB, first and last name. If any of those are missing, the Veteran can't submit the form; but HLR still needs this update - see #65747

**Comment by Mottie** [comment]
Let's validate after I've finished the work for #65747 - I'm moving all the common error messages into the shared folder

**Comment by eileen-coforma** [comment]
@Mottie I don't see the "you must" in the error message language as listed in the acceptance criteria.

The error language in staging does not match the ones listed in https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/design/sourceofcontenttruth.md#proposed-errors

**Comment by Mottie** [comment]
Updates merged in... may not be available in staging right away.
