### ISSUE TITLE
Encrypted Base AL2

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#64720]
# Description
How difficult will it be to pick up this AL2 image creation where it was left off and get AL1 based pipelines to use it?

# Tasks
- [ ] Determine whether this pipeline can be picked up and continued
- [ ] Should we be building the image outside of Jenkins?
- [ ] Can the pipeline config be picked up out of Jenkins and put into GHA?

**Comment by pjhill** [comment]
http://jenkins.vfs.va.gov/job/builds/job/base-encrypted-al2/

**Comment by pjhill** [comment]
I'm not sure what DVP is (I expects it's a VPC or environment), but this terraform config is using AL2 -- https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/dvp-dev/ec2.tf

**Comment by pjhill** [comment]
Here's packer: https://github.com/department-of-veterans-affairs/devops/blob/master/packer/platform-base/al2/sources.pkr.hcl

**Comment by pjhill** [comment]
CMS is using the AL2 AMI, maybe???
https://github.com/department-of-veterans-affairs/devops/commit/830375b3d4b340d552f4a1d418dd0c914207226f
