### ISSUE TITLE
SC | Update confirmation to more accurately set Veteran expectation for claim tracking

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#64806]
## Value Statement

**_As a_** veteran
**_I want to_** have proper expectations on when I can see my claim tracked
**_So that_** I don't worry or call about it because it's not there when I expect it to be

## Background Context

- A Veteran from the BVA submitted an SC recently, and saw messaging around a 24 hour turnaround time, but that there was no records of their submission on VBMS (and the claim was auto-established like 526).
- The ask to improve the existing message on VA.gov to remove said expectations within the confirmation page.

## Tasks
- [ ] Investigate the misleading messaging
- [ ] Update confirmation page messaging

## Design & Build Notes

TBD

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Content is updated

**Comment by eileen-coforma** [comment]
I don't see the exact language that says there'll be 24-hour turnaround to show up in the Claim Status Tool. If there is anything misleading on our confirmation page, it would be the link to the Claim Status Tool at the end of the page.

Further investigation may be required, maybe there's language in the CST?

**Comment by eileen-coforma** [comment]
Messaging may be in the confirmation email rather than the confirmation page of the form. Reach out to Janet to clarify.
