### ISSUE TITLE
POSTMORTEM: Get information about load testing of Lighthouse endpoints

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#64807]
## Issue Description
As part of the P1 issue of ITF failure in Aug 2023, this ticket is to understand the load testing done for Lighthouse endpoints that are being used for 526ez on va.gov and assess if that is sufficient for peak traffic estimates.

---
## Tasks
- [ ] Check with LH PMs about the outcome of LH load testing or estimated maximum requests it can handle
- [ ]  Compare with metrics around 526 peak traffic and estimated future traffic
- [ ]  Share report of this comparison

## Acceptance Criteria
- Document load test/max requests estimates that can be handled by Lighhouse services 
  - [ ] ITF
  - [ ] Submit
  - [ ] Rateddisabilities
  - [ ] Document Services
  - [ ] getPDF
  - [ ] PPIU
  - [ ] BRD
  - [ ] Claims Service
- Share out a report of comparison of load test results and peak traffic expected
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
cc @alatempa24 @emilytheis
