### ISSUE TITLE
NOD | Fix infinite loop issue

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#64802]
## Issue Description

Many Veterans visiting the NOD form would encounter a frozen screen that would prevent them from interacting with the form. We learned about this issue in [this slack thread](https://dsva.slack.com/archives/C5AGLBNRK/p1693505338029709). The fix (and the cause of this issue) is described in detail, in this PR: https://github.com/department-of-veterans-affairs/vets-website/pull/25490. 

---
## Tasks
- [x] Identify cause
- [x] Push fix

## Acceptance Criteria
- [ ] Veteran with at least one contested issue older than a year can visit the NOD form and not encounter a frozen screen.

## Definition of Ready
- [x] Cause identified.

## Definition of Done
- [ ] We have confirmed that multiple individual Veterans with at least one contested issue older than a year can visit the NOD form, in production, and not encounter a frozen screen.
- [ ] Datadog shows that NOD submissions have risen back up to an expected weekly amount.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
