### ISSUE TITLE
SPIKE | COE Failure Points and Sidekiq Jobs

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#64811]
## Issue Description
_Understand the points at which claims and fail and what remediation is or is not in place to ensure failed claims are submitted and document sidekiq jobs._
- See solution outlined in https://github.com/department-of-veterans-affairs/va.gov-team/issues/64538 for form 686c and 674.
- List of known jobs [sidekiq_jobs_new.csv](https://github.com/department-of-veterans-affairs/va.gov-team/files/12675536/sidekiq_jobs_new.csv)
- Collect as much information as possible, but do not delay if info is incomplete.
---
## Tasks
- [ ] Research failed claim remediation process
- [x] Document the sidekiq jobs
- [ ] Document where code is located
- [ ] Is the job veteran-facing? (yes)
- [x] What happens if it fails? Is the veteran notified? Is so, how?
- [ ] Provide links to existing dashboards, monitors, and alerts for these background jobs.
- [ ] For each job, please note any ways it has failed in the past. (Temporary failures resolved by retries do not need to be included). Can it still fail in this manner?
   - Base failure knowledge on recent history. 

## Acceptance Criteria
- [ ] Claim failure flow diagram similar to https://github.com/department-of-veterans-affairs/va.gov-team/issues/64538 for the COE form.
- [ ] Document all of the cases where the forms use Sidekiq jobs for the COE form in readme within repo and provide to Steve Albers

**Comment by sortizsh** [comment]
reassign to Matt Knight

**Comment by sortizsh** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/65513#issuecomment-1729976515

**Comment by mjknight50** [comment]
The sidekiq documentation has been completed and [merged](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67056)

Reassigning back to Laura

**Comment by steele-lm** [comment]
@mjknight50 Can you share the link to the readme file for COE?

**Comment by mjknight50** [comment]
Link to documentation:
https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/lgy/coe

**Comment by steele-lm** [comment]
Sent documentation to Steve.
