### ISSUE TITLE
UX | Profile | Profile hub | Mock up edge cases

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#64818]
## Background
We used to use the personal info page as a place for important alerts that impact other parts of profile. For example, the [Bad Address indicator (BAI) alert](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/JnRG2qz).  Now that the profile hub will be the new landing page for profile, we need to account for any edge cases or alerts that should be moved over.

Adam looked at the code and [confirmed that there aren't any other alerts on the personal info page that need to be moved over](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64160#issuecomment-1701572619). Are there any other edge cases or alerts we need to consider for the profile hub page?

## Tasks
- [x] Determine whether or not there are any other use cases we need to account for on the hub page. For example, is there a scenario when all parts of profile would fail for a person and we could let them know there? Does having a profile hub impact the behavior of any profile gates we have in place where a person currently is only given access to the account security page?
- [x] Mock up the profile hub with the BAI alert, as well as any other identified scenarios
- [ ] Review any new alerts with content (not necessary if we're just moving existing things from one page to another)
- [x] Move this ticket to validate and let PM know we're ready for FE.

**Comment by andaleliz** [comment]
@adamwhitlock1, when you have a moment, I would love your input on a couple of things:

1. Using our updated user flow pattern, I [added the bad address indicator alert to the profile hub flow](https://www.sketch.com/s/b41a687f-8ab8-4be1-b189-692e5818cffd). It follows the pattern we've been doing for the other parts of profile but somehow this a little odd since this is a brand new thing.   Let me know if you need anything different from this and I'll gladly make it. Side notes on BAI:

  - The BAI alert is a great candidate for the editing subtask flow, and actually makes the UX for that a little cleaner IMO. I've annotated that in the behavior section, and also [mocked-up how that flow would look with an alert](https://www.sketch.com/s/b41a687f-8ab8-4be1-b189-692e5818cffd).  If it's easier to do that piece later, we could keep the alert linked to the contact info page like it is now, until it makes sense to adapt the editing subtask flow to include an alert. What do you think?  
  - I was also thinking about how we might further improve the current UX - it's so reliant on someone reading and understanding the instructions in the alert. Wouldn't it be better if we could say "Is this address correct? `yes` or `no`, and then if `no` they update it (instead of having to hit save to confirm it, without having made any changes. that's not very intuitive).  

2. I've looked through all our use case documentation and I think the bad address indicator is the only thing currently on the personal info page that makes sense to move over to the profile hub.  I think you already stated that too, but if you can think of any I missed, please let me know.

Thanks!

**Comment by adamwhitlock1** [comment]
I didn't have access to the sketch file for some reason, so I requested access.

For the BAI, and the update flow, I agree it makes sense that it would fall under the editing as a subtask flow. My preference would be to get the editing for cell phone launched, and then we can totally start working towards having the address be available in that flow too! Exciting. I don't think there will be a huge amount of new stuff that I would add to support the mailing address, but we will certainly have to make sure the whole address validation flow also works in that new page's context.

The yes/no question to simplify the BAI confirmation alert makes a lot of sense. I'm totally down to experiment with some easier to understand approaches to that alert. Maybe the no button should say something like `no, I would to edit my address`, or something like that to be clear that it takes them somewhere when they click?

Can confirm that that the BAI address alert is the only thing that needs to move over. Great work!

**Comment by andaleliz** [comment]
@adamwhitlock1 you should have access to the Sketch file now - sorry about that! I'll leave this open until you have a chance to check it out.  Glad to know there aren't any other alerts I missed.

Regarding the BAI flow, that sounds good and makes sense to me.  @mtcA6 I think we already have this captured as an opportunity in the feature outline for this; lmk if you want me to make a ticket or something to capture some of the more technical details discussed here.

**Comment by adamwhitlock1** [comment]
Looks great! I like how you added the future behavior for the link taking the user to the edit subtask flow.

One question, on the hub page where would the `Home` breadcrumb take the user when clicked?
![Screenshot 2023-09-12 at 10 37 44 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/4458cfc2-5e33-45e7-87db-a8565300a18b)

**Comment by andaleliz** [comment]
@adamwhitlock1, breadcrumbs on root level pages (like this one) take people to the VA.gov home page. 

Now that we have this hub page, on "spoke" pages like personal information the breadcrumb would be:

Home [va.gov] > Profile [hub page] > Personal Information

**Comment by mtcA6** [comment]
@andaleliz thanks I've added the BAI as a future opportunity to the bottom of the epic as well so when we get ready to wrap up the epic I'll see it there. Not sure I want to create the actual GH ticket just yet but the "[future places to use this feature](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/editing-as-a-subtask#future-places-to-use-this-feature)" is great!

**Comment by andaleliz** [comment]
Sounds good @mtcA6 - this is ready for FE. Feel free to close it out once you've created the ticket, or added to the existing one.

**Comment by mtcA6** [comment]
I've added a section to [#64160](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64160)
