### ISSUE TITLE
[SW] Review page resolution options enhancements

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#64815]
## Issue Description
The current version of the resolution options section on the review page is confusing and should be updated to match the design in Sketch.

Current version:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbXhoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c340fc3923b7e828d816c77951549986902dec20/Screenshot%202023-09-01%20at%2011.59.25%20AM.png)

Proposed version:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbXBoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5271dc9e2c97f1f70cd0bda8d59da7f55fffcd3b/image.png)

The updated version groups the title by the debt and the amount and shows the option and related fields below. Similar to the rest of the review sections (Employment history, Vehcicles, Etc).

---
## Tasks
- [x] Change the layout of the review page so it matches what's in Sketch
- [x] Add the personal statement as its own sub-section

## Acceptance Criteria
- [ ] The resolution options match the design
- [ ] The personal statement section has been added.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
Need LOE from FE team; @Dr-Pongo @OptionSelect @amponce 
This needs to be updated, adding at medium-priority for now... 

cc: @Tom-Davis

**Comment by HeatherRienks** [comment]
Hey FE Team- is this ticket tied to #64213?

Wondering if this needs to be completed BEFORE our Review Page Staging Review?

cc: @josephrlee @mgleo @Tom-Davis

**Comment by josephrlee** [comment]
This is an additional ticket that I added. @HeatherRienks , it's not tied to #64213

**Comment by HeatherRienks** [comment]
Thanks @josephrlee!

**Comment by Dr-Pongo** [comment]
FE didn't get a chance to hop on this ticket with the review page and other current works in progress, so it will be rolling over!

**Comment by Tom-Davis** [comment]
@Dr-Pongo @josephrlee is there an update on this? We need to close out the Epic this is assigned to and this is the last ticket still open.

@HeatherRienks

**Comment by Dr-Pongo** [comment]
@Tom-Davis This hasn't really taken a priority over some of the other work that we've been bringing into sprints. It is ready to be worked, but I think a lot of the focus has been on review navigation

**Comment by Dr-Pongo** [comment]
@Tom-Davis I think it is still needed and 5 seems like a fair estimate imo

**Comment by Tom-Davis** [comment]
@Dr-Pongo OK - let's bump it up the "to do" list so we can close MPV out no later than S117.

**Comment by HeatherRienks** [comment]
FYI - this ticket hasn't been picked up yet, but we are aiming to get it done by end of S117 (1/30/24).  @OptionSelect @amponce
cc: @Dr-Pongo , @Tom-Davis

**Comment by OptionSelect** [comment]
Began work on this on Friday 1/12, still in progress implementing first suggested solution that Andrew and I discussed with a CustomReviewPage for the resolution option and hiding the rest.
