### ISSUE TITLE
Test EKS Cluster Setup & Operation

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#64820]
## Issue Description
Ensure that the EKS cluster can be successfully set up and run in AWS. Patrick will spearhead the initial testing.

---
## Tasks
- [ ] Provision necessary resources in AWS.
- [ ] Setup the EKS cluster.
- [ ] Confirm that the provided AWS credentials give appropriate permissions to interact with the EKS cluster.

## Acceptance Criteria
- [ ] EKS cluster is up and running.
- [ ] Successful interaction with the EKS cluster is confirmed.
