### ISSUE TITLE
[UX][Design] DS v3 #1: Update form components

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#64827]
## Background
Many of the components the VA shares with the USWDS have been synced to the design, styling, and functionality of the US System while retaining elements necessary to the VA. Though there is no deadline for the switch at this point, the Design System team is strongly recommending that teams make the change soon.

Components have been prioritized in the [#64010 Design System v3 ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64010). We will start the transition with form components that affect functionality. All form components need to be completed together. Guidance states that form components should not be mixed and matched with earlier versions on production.

**Form components we need to change:**
- Form text input / required (the size is a bit different)
- Form text input error / required (the size and color is a bit different)
- Memorable date
- Need help?

## Tasks
- [ ] **Update** **Unified check-in**, **Check-in**, and **Pre-Check-in** **files**
    - [x] Form text input / required (the size is a bit different)
    - [x] Form text input error / required (the size and color is a bit different)
    - [x] Memorable date
    - [x] Need help?
    - [x] Identify screens that use these components  
    - [ ] Update the corresponding symbols in these files with the new Component Library Sketch components (see ticket [#64010 Design System v3 ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64010) for more info on setting up the new Sketch library)
    - [ ] Check all boards to make sure they're updated in case of detached symbols
- [ ] **Update any priority pages** that include these components (starting with release 2.1?) 
- [ ] **Sync with FE engineers** to make sure they're all set on toggling these form components to the new version at about the same time
### Validation
- [x] Form text input / required (the size is a bit different)
     - [x] **Update design page** **Unified check-in**
     - [x] **Update design page**  **Check-in**
     - [x] **Update design page** **Pre-Check-in**
- [x] Form text input error / required (the size and color is a bit different)
     - [x] **Update design page** **Unified check-in**
     - [x] **Update design page**  **Check-in**
     - [x] **Update design page** **Pre-Check-in**
- [x] Memorable date
     - [x] **Update design page** **Unified check-in**
     - [x] **Update design page**  **Check-in**
     - [x] **Update design page** **Pre-Check-in**
- [x] Need help?
     - [x] **Update design page** **Unified check-in**
     - [x] **Update design page**  **Check-in**
     - [x] **Update design page** **Pre-Check-in**

## Acceptance Criteria
- [ ] Form components listed above are updated in unified, Check-in, and Pre-Check-in files
- [ ] Relevant release pages are updated
- [ ] FE is set to toggle to v3 of these components

**Comment by loripusey** [comment]
[Design System bugs](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues?q=is%3Aissue+is%3Aopen+label%3Acomponent-bug-v3)

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 We're tracking all the work towards all 3 of these tickets [in this spreadsheet](https://docs.google.com/spreadsheets/d/18U5ScytwsmCTLfEmrZJjJl6iv6vR2eiiOAhjdNu68F0/edit#gid=0) - you can view where we are there. For this specific ticket it looks like we still have telemedicine pre-check-in to complete. (for future reference, we probably should have split these tickets into "Update unified" and "Update PCI/CI" - there's more work here than I think we first imagined)

**Comment by benbrasso-agile6** [comment]
Are we moving forward with memorable date? I thought I remembered that there were a lot of bugs - https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues?q=is%3Aissue+is%3Aopen+label%3Ava-memorable-date

Although, those might be specific to engineering vs. us updating our designs. But, if we do pass form elements on to engineers next sprint, we should figure out if we're passing them memorable date or not.

**Comment by benbrasso-agile6** [comment]
One other consideration here is to potentially use the month dropdown variation. Had you guys discussed that at all? I know @cgednalske had gathered Veteran feedback that that could be better for A11y users. https://design.va.gov/storybook/?path=/docs/uswds-va-memorable-date--default#with-month-select

**Comment by kellysmith1008** [comment]
We did discuss that, but because it's out of the scope of this specific ticket, we decided to create a separate ticket to tackle that work. @cgednalske can correct me if I'm wrong on that.

**Comment by benbrasso-agile6** [comment]
I don't think it has been created yet, but yeah we can wait for Christina https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/64071

**Comment by cgednalske** [comment]
@kellysmith1008 yep, that's right! We wanted to create a separate one to make sure this ticket stayed in scope 🙂 The new one has not been created yet.

**Comment by benbrasso-agile6** [comment]
Cool cool, was I the one that said we should wait? lol, I think it was because there were some bugs for USDWS v3, but it seems like those bugs have been fixed, if I'm looking at the backlog correctly

**Comment by kellysmith1008** [comment]
I don't think you said to wait, I think we made that decision in a meeting over it. But getting the request or suggestion with 2 days left in the sprint doesn't give us enough time to get it done, so a new ticket is the better path forward, in my humble opinion. There's a lot of work already in these tickets but we have a chance to finish this one, in its current scope, by the end of this sprint and can tackle the separate ticket to update to a drop down in a future sprint.

**Comment by benbrasso-agile6** [comment]
Oh def

**Comment by zach-park** [comment]
> @zach-park do you want to help validate the work here?

@benbrasso-agile6 , where should I leave the validation comments? In the sketch file or in the spreadsheet?

**Comment by benbrasso-agile6** [comment]
Leave comments in sketch. But, make the changes you need to.

**Comment by zach-park** [comment]
Validation is complete.
