### ISSUE TITLE
Deploy vets-api via Helm to EKS Cluster

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#64822]
## Issue Description
Test the deployment of Vets-api using Helm from a local setup to the EKS cluster, with support from team members familiar with the application, like Eric.

---
## Tasks
- [x] Collaborate to obtain the necessary Helm charts for Vets-api.
- [x] Configure the local Helm setup with the Vets-api charts.
- [ ] Deploy Vets-api to the EKS cluster using Helm.
- [x] Verify the Vets-api deployment.

## Acceptance Criteria
- [x] Vets-api is successfully deployed to the EKS cluster using Helm.
- [x] Deployment is verified and running as expected.

**Comment by patrick-black-oddball** [comment]
The current helm charts are all written in an "ArgoCD" format. Specifically they utilize the "App of Apps" pattern which has a top level chart (argocd-apps) as the top parent chart. This approach has also been implemented where each environment deployment has a separate helm chart code base - i.e. each environment has a separate directory with a complete copy of the helm chart with a postscript of the version (i.e. vets-api/prod). This means that we would need a preview copy of every helm chart (30 charts). 

This pattern is not sustainable, as preview environments would require separately named and references environment names (i.e. preview-1, preview-2, preview-3, etc) - as we cannot create 30 chart copies with modified values for each of these, we need to modify all 30 helm charts such that they take the environment name as an input - allowing the same helm chart to be used for multiple/different helm chart installs

**Comment by JoeTice** [comment]
Sprint 34 Update - In Progress, A change was needed in how this is being set up that added complexity to the task, work will continue/complete in Sprint 35
