### ISSUE TITLE
Exploration: VAOS in-app notifications

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#64830]
## Task Description
Explore how the appointment list could support two user needs related to the status of an appointment:

**As a user I want to see how my appointments have changed over time**
For example:
- Be notified of appointments that have been canceled or rescheduled (and by who)
- Be notified of appointments that have a new AVS added
- Be notified of appointments, recalls, or referrals that have been scheduled by staff

**As a user I want to complete actions related to my health care appointments**
For example:
-  Confirm that I will attend my appointment
- Join video appointments when window is open
- Check-in to appointments
- Submit travel pay when available

## Notes and References
-

## Acceptance Criteria
- [ ] 

## Deliverables
- [Figma File](https://www.figma.com/file/7QvH8YQvpRdnaHMxNOQgh0/In-app-notification-(EXPLORATION)?type=design&node-id=1501%3A2555&mode=design&t=epjSTTzI6NGV7qaz-1)

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Cieramaddox** [comment]
Notifications work is being done along side the check in team. [Sketch File](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec)
