### ISSUE TITLE
[CONTENT] Research and write WILKES-BARRE, PA System Health Services and Program Intro (Returning-Surgery) [CONTENT]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#6484]
## User Story or Problem Statement
As a Veteran Web user, I need a System description of services provided at VAMC, so I can understand and best chose the services and service location for my needs.

## Goal
_Efficient and clear content describing local Health Service provided_
_Efficient plain language for Health Services and Health Service Program Intro_

## Objectives or Key Results this is meant to further
- _Reduced word count and improved plain language._

## Resources - Tools - Documentation
[Wilkes-Barre Health Services Content Playbook](https://drive.google.com/drive/folders/1lj6_MZ4x6CKxybS3FWicbwYnxFKUvduv)
[Wilkes-Barre Health Services:A-Z](https://www.wilkes-barre.va.gov/services/index.asp)
[Pittsburgh Returning Service Member Program Link](https://www.va.gov/pittsburgh-health-care/returning-service-member-care/)
[Pittsburgh Suicide Prevention Program Link](https://www.va.gov/pittsburgh-health-care/suicide-prevention/)

## Tasks
_Tasks that must be complete using content playbook criteria for the following Health Services, and Health Service Program Intro:_
- [ ] Returning service member care (Health Service)
- [ ] Returning service member care (Health Program)
- [ ] Smoking and tobacco cessation
- [ ] Social Work
- [ ] Spinal cord injury and disorders
- [ ] Suicide prevention (Health Service)
- [ ] Suicide prevention (Health Program)
- [ ] Surgery

## Acceptance Criteria
_Items that must be written and documented in Content Approval Folder under the correct VAMC System folder (i.e. Altoona, Butler)_
* Returning service member care (Health Service)
* Returning service member care (Health Program)
* Smoking and tobacco cessation
* Social Work
* Spinal cord injury and disorders
* Suicide prevention (Health Service)
* Suicide prevention (Health Program)
* Surgery
