### ISSUE TITLE
EPIC | Profile | Enhanced Military Information

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#64861]
## Background

The MVP will consist of surfacing 3 data elements from a list of 8 that VEO has highlighted as being important for applying for PACT act benefits. 

<details><summary>First Call 9/5/2023</summary>
<p>

This initiative has two main parts: 

1. Prior legislation requires granting veterans read access to ILER data. 
2. VEO and OGC don't want to stop at ILER access. The heart/spirit of the PACT act is to get veterans access to military information that may help them with detailing their exposure history and getting care they need/applying for benefits. We should get veterans access to their expanded military information that will assist them with their claims process. 

[BoozAllen ILER project](https://dvagov.sharepoint.com/:w:/r/sites/MCT-BAHILERHCD/Shared%20Documents/General/02-Pre-Discovery/Background/CEDAR%20Intake%20Form_ILER.docx?d=wac73f6853e8a4865b0da25c0dfdae386&csf=1&web=1&e=j64a3Z)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/c2893e65-8dfe-4213-8d92-873e710171b0)

DD214 may really help reduce this, they have to go to DoD and request a DD214, can we prefill a form for a DD214, can we generate a digital DD214 > this is what they get at transition, can we display all of the digital record that encompasses the DD214 and other data. Could generate everything but the comments.  

Our focus should be on the 8 elements and not so much on current state

### What might an MVP look like? 

- surface read fields to the first 6 elements 
- link to ILER PDF 
- send vet to service department for corrections 

</p>
</details> 

## Current State Documentation 
- [use cases](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/military-information/use-cases)
- [user flows](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/p/D6D40E33-BC4E-4A06-90C7-879C59AD49F4/canvas)

## Jan 2023 Prior Research:
- [research epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52006)

## Project Artifacts 
- [project directory](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/military-information/2023-enhanced-military-information)
- [project outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/military-information/2023-enhanced-military-information/README.md)
- [sensitive repo directory (contains stakeholder artifacts)](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/products/identity-personalization/profile/military_info/2023-enhanced-military-information)
- [mural refinement space](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695126310753/6ab8c3953d2eeaa067f666d5a03a754c5ded3d82?sender=uaa72d11015d3f7c704a64191)
- [design mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697125319596/c13810c02c96a58a4b6b72288c6b9a8d617f711a?sender=uaa72d11015d3f7c704a64191)
- [research-readout.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/15391588/research-readout.pdf)

## Tasks/Phases

This epic will comprise our work for an MVP state and this epic will change as we work through our questions and determine what the shape of the product will be as we unearth more information. 

<details><summary>Completed Phases</summary>

```[tasklist]
### Initial Discovery/ Brain Dump
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65894
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65501
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65973
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/66362
- [ ] #67103
```

```[tasklist]
### Design Read Access to Expanded Military Information Data Elements
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/66894
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/66014
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/66012
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/68363
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/68362
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/67101
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/68399
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/69452
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/70085
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/70025
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/71403
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/71889
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/71866
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/70348
```

</details> 

```[tasklist]
### Initial Endpoint Build
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/69973
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/68772
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65974
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/68770
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/68771
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/72799
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76192
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76193
```

```[tasklist]
### Design Intent
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/72571
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/73138
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/73027
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/72997
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/73361
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/72292
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/73492
```

```[tasklist]
### Research/Design Midpoint Prep
- [ ] #73363
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/71060
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/70802
- [ ] #74208
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/74186
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/74187
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/74181
- [ ] #74209
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/75025
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/75581
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/75694
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/78052
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/75211
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/83780
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/83581
```

```[tasklist]
### Post Launch
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/66015
```
```[tasklist]
### ILER Button (phase4)
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/66013
```

```[tasklist]
### Mobile team ticket(s) 
- [ ] #71518  
```

**Comment by andaleliz** [comment]
@mtcA6 what do you think about changing the name of the epic + related tickets from "Enhanced Military Information" to something more specific like "ILER and TERA data points"?  Just thinking ahead to down the road when we have other, unrelated enhancements, or we're looking for something specific to this work.

**Comment by mtcA6** [comment]
@andaleliz Hard no on anything referencing ILER in that way. I'm paraphrasing Melissa "we should not talk about ILER, in VA world we should be focused on 'Military Record Exposure'" 

That's what I was trying to drive home on our mini-refinement call earlier, it's not exclusively about surfacing ILER. Any hard focus on ILER is misplaced. 

OGC said not to narrowly focus on ILER so that's the guidance they've (VEO) passed to us. The narrow letter of the law says we have to get veterans read access to ILER, that's why I've made reference to 'two parts of read access' in that phase 1 solution section of the outline. Read access for ILER and read access to the data elements we're expected to surfaced based on the VBA analysis. VEO cares about the process and WHY veterans are using ILER data not ILER as a telos.

**Comment by mtcA6** [comment]
Samara and I arrived at `Enhanced Military Information`, but if you like `Military Record Exposure` more I'm okay with that.

**Comment by andaleliz** [comment]
@mtcA6 it was just a suggestion, no need to change it if there's a hard no on being specific about what we're working on. I totally understand 😄 and will know to look under this label.

**Comment by mtcA6** [comment]
@clantosswett closing this epic out. We have the period of service text in production.
