### ISSUE TITLE
[Design]: Determine Design Options for "Next of kin" and "Emergency contact"

### ISSUE THREAD

**Issue by jonathanjnelson** [department-of-veterans-affairs/va.gov-team#64873]
[Follow-up to #62879 ](https://app.zenhub.com/workspaces/mhv-on-vagov-top-level-view-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/62879)

## Tasks
- [x] Create design options (team chooses fidelity of the design options based on situation)
- [x] Get feedback from appropriate stakeholder(s)
- [x] Get clarity on VBA's definitions and use of NoK and EC (Liz)
- [x] Choose the target design solution
- [x] Incorporate feedback into solution(s) 

## Acceptance Criteria
- [x] Design solution has been chosen
- [x] Design solution idea has been vetted and is ready to be implemented (i.e. ready to create the wireframes)
- [x] Follow-up tickets have been created

**Comment by LynneJohnson224** [comment]
@jonathanjnelson when you have a minute, can you please add a story point value?

**Comment by jonathanjnelson** [comment]
- Please see[ Mobile designs](https://www.sketch.com/s/99bac82d-4c95-4d4c-9587-2a931ed464de/p/4D215CC1-EBBC-4549-890C-77087DE9E136/canvas) 
- [Desktop designs here ](https://www.sketch.com/s/99bac82d-4c95-4d4c-9587-2a931ed464de/p/06E9DA65-3E2B-467A-B068-2F9551DD0B06/canvas)

**Comment by andaleliz** [comment]
@LynneJohnson224 I still haven't heard back from VBA about their definitions and need to follow up. Is it OK if we leave this ticket open until that's done so I don't forget? 

Also, not sure if you can answer this or perhaps @jonathanjnelson - have we learned more about the user flow for people to get to NoK/EC info in the profile? It's not clear to our team where they'll come from to review this information. 

Thanks!

**Comment by andaleliz** [comment]
We checked with Melissa Rebstock, Michael Napper, and David Reis at VBA about how Nok/EC info is collected or used.  No one is aware of any use case for these data points at VBA:

> EDU does not collect next-of-kin and emergency contact information for benefits purposes. It may be reflected on an application but it’s not tracked for regular benefit usage.

> I am not aware that VBA, at least within disability benefits, is collecting either of these data points. 

cc @mtcA6 and @pamela-drouin for awareness

**Comment by MikeC-A6** [comment]
Thanks @andaleliz - we will go ahead and close this one out cc @LynneJohnson224
