### ISSUE TITLE
BE | Profile | Direct Deposit | Review fraudulent transaction and update logs

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#64875]
## Background
Joe Niquette was alerted to a fraud change that came from VA.gov, but the audit log from the downstream database (Corp Award and Rating Data) reported that it came from "ebenefits" (which no longer allows direct deposit changes).  

Reference doc for logging - https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsp/teams/Identity/BDPR/Required_logging.md

## Tasks
- [ ] Reach out to the LH team to determine if they transmit any data that could give the downstream system the impression that the request originated from "ebenefits"?
- [ ] Joe requested that we add the user's `ICN` and `CSP UUID` to the logs.
- [ ] Create additional ticket for reviewing contact-info related logs.

## Acceptance Criteria
- [ ] Follow up with Lighthouse to determine if there are any reasons for the source being "ebenefits".
- [ ] Update vets-api to include user's `ICN` and `CSP UUID` in Datadog logs.
- [ ] Review logs with Joe Niquette

**Comment by tpharrison** [comment]
[Reached out to Lighthouse here](https://dsva.slack.com/archives/C02CQP3RFFX/p1693927196432129).
