### ISSUE TITLE
Extend Burial Form Expiration

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#64881]
## Issue Description
_Currently, the pension (527) and burial (530) forms expire 60 days after the last edit date. The expiration date should be extended to 365 days FROM THE CLAIM CREATION DATE to allow users more time to submit their claim._

Research for pension ITF date #66958 

Pension form expiration extension is #68648

---
## Tasks
- [ ] Change the burial 530 form data to expire 365 days from creation date.
- [ ] Ensure any front-end components display expiration date appropriately.
- [ ] Ensure any front-end components display the expiration time frame appropriately (12 months vs 2 months)

## Acceptance Criteria
- [ ] Burial 530 form expires 365 days from creation date.
---

**Comment by steele-lm** [comment]
Thomas: Can we use created date to establish start date of 12 month time frame?

**Comment by steele-lm** [comment]
Explore whether front end states 60 days anywhere.

**Comment by steele-lm** [comment]
Align with date capture for 526.
