### ISSUE TITLE
[tech task] NOD | Gather list of affected Veterans from NOD infinite loop bug

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#64896]
## Value Statement
**_As a_** BVA employee responsible for remediating claims that failed to submit through VA.gov
**_I want to_** check the submission times for users who were unable to complete the form
**_So that_** I can preserve their submission date. 

---
## Background Context
Review the [Slack thread](https://dsva.slack.com/archives/C5AGLBNRK/p1693505338029709)

## Out of scope
- Add here

## Open questions
- Can we convert DD info to the format that Zach and BVA needs?

## Tasks
- [x] Get someone at VA to press the rehydrate button, to get DD logs from July 27th to Sept 2nd
- [x] Go through complete logs, assemble a list of unique user_uuids
- [x] Doublecheck exactly what identifying information VA needs for these Veterans
- [x] Ask someone (?) to convert those user_uuids to that identifying information (talk to Kyle for help)
- [x] Go from there.
- [x] Post frequent updates in the [Slack thread](https://dsva.slack.com/archives/C5AGLBNRK/p1693505338029709)

## Definition of Ready 

- [x] Access to re-hydrated logs
- [x] Confirmation that DD info can be used

## Definition of Done

- [ ] Reviewed and approved by VA stakeholder (Zach G.)

**Comment by saderagsdale** [comment]
Waiting for Brent (DD) to confirm that we can access data from re-hydrated logs ([slack thread](https://dsva.slack.com/archives/C01G6J7UGGH/p1693942327412529)).

**Comment by data-doge** [comment]
Quick update that I can expand on later: 

@saderagsdale I sent data to Premal and Zach in Teams. I tagged you in that chat. I'm putting this ticket in Validate, though I suspect it will get kicked back into In Progress, because I was unable to find an EDIPI/ICN for certain Veterans, and Zach may want us to pursue a complete dataset.

**Comment by data-doge** [comment]
Update: still working on this. Going to use MPI to get first name, last name, and SSN -- which BVA has requested. Also going to try to use MPI to get this data for Veterans for which we could not find an EDIPI/ICN.

**Comment by data-doge** [comment]
Update: I've completed the dataset that BVA requested, and sent it to Premal. See [Slack thread](https://dsva.slack.com/archives/C5AGLBNRK/p1694633337838009?thread_ts=1693505338.029709&cid=C5AGLBNRK). Premal will send this data to BVA, who will figure out which Veterans have not yet completed an NOD. BVA will then send that list to us, and we will likely come up with an email template to notify those Veterans, and then notify those Veterans via VANotify. That notification work can be handled in a separate ticket, that I can draft once BVA gets back to us. 

I'm moving this ticket into validate, until Premal confirms that he's sent the data to BVA.

**Comment by data-doge** [comment]
Moving back into in-progress. Premal wants to see if we can work with identity team to get ICNs for a subset of veterans that I could only find an email for. Relevant slack thread here: https://dsva.slack.com/archives/CBU0KDSB1/p1694526969858929

**Comment by data-doge** [comment]
Moving back into validate. It turns out that the aforementioned subset of veterans were unverified and thus could not have experienced the infinite loop bug. I let Premal know that the dataset is ready to send to BVA.

**Comment by data-doge** [comment]
Premal has sent the data to BVA. See https://dsva.slack.com/archives/C5AGLBNRK/p1694803468708989?thread_ts=1693505338.029709&cid=C5AGLBNRK. Closing this ticket 🎉
