### ISSUE TITLE
Update unit test coverage standard on Platform Website

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#64916]
## User Story
As an OCTO Platform lead, I want to increase the unit test coverage QA Standard for VFS teams to adhere to so that I can ensure less errors and bugs are pushed to VA.gov production.

As an OCTO Platform lead, I want to change the severity from warning to launch-blocking if the unit test coverage QA Standard is not met so that VFS teams are held accountable for better code coverage.

Assignee: @erinrwhite 
Peer Reviewer: @it-harrison 

## Description
The QA Standard for Unit test coverage states that a VFS, "Product must have 75% or higher unit test coverage." When this standard is not met at the Collaboration Cycle Staging Review, there is only a warning issued as it is not a launch-blocking issue.

Governance team is proposing that the unit test coverage percentage be modified from 75% to 80% and that the severity of this standard be changed to `launch-blocking`. 

As of 9/5/2023, there have been 14 VFS products (out of 24 )that have not met the unit test coverage standard. [See QA Standards tickets](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+label%3Aqa-standards+is%3Aclosed+label%3Acollab-cycle-feedback ). That's 58.3% of teams not meeting the standard.

## Impacted Artifacts
Platform website - [QA Standards page](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards)

## Tasks
- [x] Create documentation draft page
- [x] Update QA5 to specify 80% coverage
- [x] Update QA5 to have launch-blocking severity (should match language used in E2E standard)
- [x] after peer review, do not publish. all changes will be pushed via ticket #

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The QA Standard for unit test coverage (QA5) has been modified from 75% to 80%
- [x] The severity of the QA Standard for unit test coverage (QA5) has been modified from warning to launch-blocking

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
@it-harrison [Draft QA standards page](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2766471169/QA+standards) ready for your review on the Platform website drafts wiki space.

**Comment by it-harrison** [comment]
@erinrwhite looks good but I would add "Product must have 80% or higher unit test coverage in each category: Lines, Functions, Statements, and Branches." just to head off any confusion VFS teams may have on this point.

**Comment by erinrwhite** [comment]
@it-harrison done!

**Comment by erinrwhite** [comment]
@it-harrison all set to go on this [draft page](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2766471169/QA+standards)? If so I'll close the ticket.

**Comment by it-harrison** [comment]
> @it-harrison all set to go on this [draft page](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2766471169/QA+standards)? If so I'll close the ticket.

@erinrwhite yes, looks good to close!

**Comment by erinrwhite** [comment]
Thanks @it-harrison! Closing.
