### ISSUE TITLE
[FSR] addError sentry notification

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#64913]
## Issue Description
Sentry error is cropping up and should be investigated. 
```e.addError is not a function```

This is likely caused by leveraging a validator in a standard component when the validator was designed to accept a error message from the forms system that contains a function `addError`.

http://sentry.vfs.va.gov/organizations/vsp/issues/223146/?environment=production&project=4&query=is%3Aunresolved+location%3A%2Fgenerated%2Frequest-debt-help-form-5655.entry.js

---
## Tasks
- [ ] Investigate error message and identify issue
- [ ] Apply fix and confirm no similar errors are in place

## Acceptance Criteria
- [ ] Sentry error listed above is no longer triggering. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by OptionSelect** [comment]
Reporting in to say I have yet to discover the issue behind this. Hoping to sync with Andrew today to knock it out.

**Comment by OptionSelect** [comment]
Reporting in to say I have yet to discover the issue behind this. Hoping to sync with Andrew today to knock it out.
