### ISSUE TITLE
Update Looker Documentation with Support Responses Doc Best Practices

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#64924]
## Description 
Document training from Kerry in documentation format to show best practices, dos and don'ts. This will help us ensure the looker dashboard is not broken in the future. 

Updates should be made here at the bottom of the page.

---

## Definition of Done
Complete tasks below.

---

## Tasks 

- [x] Document what each tab is used for
- [x] Document how the support bot data is fed into the spreadsheet
- [x] Note what changes can effect the dashboard 
- [x] Note best practices in the event that the dashboard does break

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Joe reaching out to Kerry.

**Comment by jknipes** [comment]
[Draft here](https://vfs.atlassian.net/wiki/pages/resumedraft.action?draftId=2766013071&draftShareId=65fc3e60-76bc-4157-9785-5ff76f4a2ea5)

**Comment by alyssagallion** [comment]
Reviewed and updated here: https://vfs.atlassian.net/wiki/spaces/PTST/pages/2767093962/Support+Responses+Spreadsheet

With @jknipes for adding missing data.
