### ISSUE TITLE
Gross monthly income calculator

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#64922]
## Issue Description
Create a gross monthly income calculator to help veterans calculate their gross monthly income and their deduction amounts so it's easier for them rather than having them manually do it.

Here's an [example calculator](https://www.freeandclear.com/calculators/monthly-gross-income.html).
<img width="1106" alt="Screenshot 2023-09-05 at 12 49 54 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/66f0228d-a798-4f3a-ab78-e5e4b9316f98">

This is based of feedback from a [prior study](https://docs.google.com/spreadsheets/d/1x8zKY2JwU_3xnmcp6icBsw_yTAknPy0u/edit#gid=1074480362&range=B13) on how to [calculate gross monthly income](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_fsr/research/enhanced_fsr/research-findings.md#key-findings).

---
## Tasks
- [ ] Research calculators and do discovery 
- [ ] Figure out feasibility with FE
- [ ] Design the new flow and see how it will affect the current flow (FE logic needs to be thought thru)
- [ ] Create sketch mockups
- [ ] Update UXPin prototype 

## Acceptance Criteria
- [ ] A veteran will be able to input how much they make on their paycheck to more easily calculate their gross monthly income
- [ ] The flow will be updated and the mockups and prototype will be updated as well
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
Per @Tom-Davis - let's break this ticket up into Design/FE tasks

**Comment by HeatherRienks** [comment]
@josephrlee and @Dr-Pongo - I think we may still need to break this ticket up to create a new ticket (for either FE OR Design tasks). Let's link the new ticket here. Thanks!

cc: @Tom-Davis

**Comment by HeatherRienks** [comment]
Per backlog refinement on 10/18, let's put this on hold for now.

**Comment by HeatherRienks** [comment]
Per Backlog Refinement on 12/13, let's discuss this enhancement in 2024

**Comment by HeatherRienks** [comment]
Per team convo on 4/3/24- the design is not done as of yet. It's a "nice to have" -not a priority at the moment. Will keep in backlog for now.
