### ISSUE TITLE
Platform Support Service Blueprint

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#64926]
## Description 
A document was created in 2021 outlining the Platform Support workflow as it relates to the customer (VFS). It needs to be updated.

Link to original: https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1613414098261/8a345994382dc05be624b8a759fb9bda5f6230b0?sender=u4a53e1dce0d560bb44ea0522

---

## Definition of Done
Below tasks completed.

---

## Tasks 

- [ ] Add any new steps or different steps to the process
- [ ] Share with Erika Washburn and Naomi Marcussen
- [ ] Identify and share to proper channels
--- 

## Resources & Additional Info 
Potential other templates: https://app.mural.co/template/77cc7953-8695-4788-a1a4-c2182d0b5270/5a333319-c85d-4aaf-a4b4-2b362f537d8a

**Comment by alyssagallion** [comment]
Reached out to Naomi Marcussen and Erika Washburn to get access to blueprint.

**Comment by alyssagallion** [comment]
Had a call with Naomi. Going to  use this format instead and the example will be PR Review Process: https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1700158532924/fc73126519e346528965884f1da3a74d4f3bf5f1

Dependency: https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/69069

**Comment by alyssagallion** [comment]
Working out of related tickets. 

https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/73481
https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/73479
