### ISSUE TITLE
Update Service Design Question for Platform Support Section

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#64928]
## Description 
The goal is to update the Platform Support Service Design question to tailor it to our needs for data collection.

---

## Definition of Done
Complete tasks below.

---

## Tasks 

- [x] Rewrite the current question (_It is easy to obtain sufficiently fast and successful support in using or fixing issues with services provided by the VA.gov Platform._)
- [x] Send the question revision to Bryan Ivie (PM for Service Design team)
- [x] Identify how the data is tracked
- [x] Set up a reminder to check on tracked data quarterly

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Platform Design team will complete in Q4. Closing.
