### ISSUE TITLE
Update Communication with teams for Contact Center reviews for Product Updates

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#6493]
## User Story or Problem Statement
How might we update our collab cycle documentation so that VFS teams better understand how to go about requesting and creating contact center guides and videos?

## Goal
Easier communication with contact center reviews.

---

## Tasks
- [x] Create a Github Issue template that mirrors our current Analytics request templates
- [ ] _Stretch_ Adding a blank Word or Google Doc or PDF etc. template (on top of the[ Github template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md))
- [x] @Kimberley2019 @clantosswett @joanneesteban to meet about this process

## Acceptance Criteria
- [ ] VFS teams consistently understand how to request a contact center review

**Comment by Kimberley2019** [comment]
@joanneesteban @clantosswett Please review the template that I have created and provide feedback.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/contact-center-product-guide-review-request-template.md

**Comment by Kimberley2019** [comment]
@joanneesteban @clantosswett Below is the updated template for Contact Center Reviews.  Please advise what additional changes need to be incorporated.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/request-contact-center-review-template.md
