### ISSUE TITLE
[MVP] Pension Log Update for DataDog Dashboard

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#64938]
## Issue Description
We need a way to identify three states of a claim submission. We want to capture when a claim submission begins, when it fails, and when it succeeds. 

## Tasks
- [ ] Refactor worker job to implement wrap_with_logging method
- [x] Update unit tests to test each state of a claim submission and claim attachment upload
- [x] Implement sidekiq_retries_exhausted() for all of the cases where we run sidekiq jobs.  Example [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/sidekiq/decision_review/submit_upload.rb#L18).

## Acceptance Criteria
- [x] Datadog logs exist that capture when a claim submission upload has begun
- [x] Datadog logs exist that capture when a claim submission upload has failed
- [x] Datadog logs exist that capture when a claim submission upload has succeeded
- [ ] Datadog logs exist that capture when a claim attachment upload has begun
- [ ] Datadog logs exist that capture when a claim attachment upload has failed
- [ ] Datadog logs exist that capture when a claim attachment upload has succeeded
- [x] sidekiq_retries_exhausted() implemented for all sidekiq jobs
- [x] All logs include user id and claim submission id.
- [ ] Attachment upload logs should also include the attachment id

**Comment by mjknight50** [comment]
@vbellissimo I am the only one who is likely to have datadog access by the time sprint six starts.  I think we can leave it in the plan, but this is a potential blocker.

**Comment by vbellissimo** [comment]
@mjknight50 Yeah, understandable. Thanks for the heads up.

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/64938?planning-poker) with Zenhub @mjknight50 @TaiWilkin @ToddWebDev

**Comment by steele-lm** [comment]
@mjknight50 I added the requirement Steve Albers mentioned to implement sidekiq_retries_exhausted() for all of the cases where we run sidekiq jobs.

**Comment by mjknight50** [comment]
@TaiWilkin can you please own this one and run with it?

**Comment by mjknight50** [comment]
More context to consider when adding logs:
https://dsva.slack.com/archives/C0547Q0K0LF/p1698872787292049

**Comment by vbellissimo** [comment]
@TaiWilkin , let me know when you have time so we can refine the acceptance criteria for this.

Also, Steve Albers mentioned to reach out to him at any point if you need more insight on any of this.

**Comment by vbellissimo** [comment]
Logs exist that capture:

- when an attachment submission has **begun**
- when an attachment submission has **failed**
- when an attachment submission has **succeeded**

The user ID is logged where possible (outside of the sidekiq job)
