### ISSUE TITLE
NOD | Update appeals research test app

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#64944]
## Value Statement
**_As a_**  developer
**_I want to_** update the appeals testing app
**_So that_** we can further validate our hypotheses in testing

---
## Tasks
- [ ] Update OMB expiration date
- [ ] Hide save in progress links
- [ ] Fix task list links
- [ ] Clear out disagreement selections
- [ ] Fix review edit links

## Designs and related tickets
- [MURAL](https://app.mural.co/t/coforma8350/m/coforma8350/1691785014802/16e7144c246d8d8a18518135f70c7071051c2ba7?sender=udbf574074425980f04c55360)
- [SKETCH](https://www.sketch.com/s/0424c51d-7818-43ea-8821-6de91eb7ab27/p/EFEBDA30-009D-4F17-B82A-2C2F3AF62D0D/canvas)
- [Post-Research Design Enhancements #63828](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63828)
- [Testing app in staging](https://staging.va.gov/decision-reviews/appeals-testing)
- [Update web components](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2078)

## Definition of Done
- [ ] Form updates available for testing in staging
- [ ] Design review of app reports no more changes needed

## Acceptance criteria
- [ ] NOD prototype is ready for user testing
- [ ] Successful user testing

**Comment by Mottie** [comment]
This ticket is in progress while we continue with prototype user testing and make minor adjustments

**Comment by Mottie** [comment]
No more work to do.
