### ISSUE TITLE
Fix broken github stats rake task job

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#6495]
## User Story or Problem Statement
Ops team received a request to help with a scheduled job that was not firing according to its proposed schedule.

## Goal
The desired job firing at the proposed schedule.

## Objectives or Key Results this is meant to further
---
## Tasks
- [x] Figure out why the job is not firing as intended.
- [x] Had to drop the conditional and include the job in a for loop that defines it and other rake tasks.

## Acceptance Criteria
- [x] Original requester's job is running on the desired schedule and is satisfied with the outcome.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment]
Accidentally closed before PR was approved / merged. Reopened.
