### ISSUE TITLE
Discovery for API Migration 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#6497]
### Problem Statement
How might we migrate the VAMC Facility Data Endpoint to the official Lighthouse Facilities API from unofficial beta we currently use on Vets-API?

## Goal
_What outcome(s) do we want to see?_
- [ ] Determine the pathway for moving to the official Lighthouse Facilities API for VAMC Facilities in Facility Locator
- [ ] Zero loss of front-end display data
- [ ] At least status-quo on performance if not improvement on performance for searches

## Objectives or Key Results this is meant to further
- Utilize official Lighthouse API system rather than unofficial, not enhance-able API.

## Tasks
[ ] Document current API pathway
[ ] Determine back end changes needed to switch over to Lighthouse

**Comment by mmiddaugh** [comment]
Discovery showed this is front end effort only since both Vets API and Facilities API use same end point and data source. This work now will be done from the front end api key.

From Patrick Vinograd

> Right now VA is collectively maintaining two similar facilities APIs - so there’s duplicated effort, risk of them getting out of sync, etc. By VA.gov using the lighthouse facilities API, VA can collectively consolidate down to one and reduce maintenance effort.
> They never really should have been forked from one another, it was an expedience that was done at the outset of the lighthouse program to minimize disruption to the (then) Vets.gov project

https://developer.va.gov/explore/facilities/docs/facilities?version=current

**Comment by mmiddaugh** [comment]
@darkbushido please add additional information from your research
