### ISSUE TITLE
Discovery: Should we automate the packaging of the Vets API helm chart

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#64977]
Needs refinement
[Link to slack thread](https://adhoc.slack.com/archives/C045LCF8WU8/p1694003503516649)

### Problem Statement
The current packaging is manual and needs to be automated. Automated packaging with GHAs is needed to automatically repackage charts. 

### Tasks
- [ ] Locking down the parent helm chart branch
- [ ] Require checks and approving review from backend-review-group ^^
- [ ] **Determine last time the helm charts were edited (how often are the charts edited; is this ticket worth the lift?)**
- [ ] How can there be stricter quality standards for helm charts?
- [ ] Run all of this by the devops cop

## Success Metrics
- [ ] ADD SUCCESS METRICS HERE

### Acceptance Criteria
- [ ] First determine if this work is worth the work...

**Comment by LindseySaari** [comment]
This will continue into next sprint. @Kshitiz-devops or @flooose, could you please comment with your latest findings

**Comment by rmtolmach** [comment]
Chris and Kshitiz to meet to discuss.

**Comment by flooose** [comment]
From a best practice perspective, I think it's worth automating the release process of the helm charts. The Lights team is currently doing the same thing and this gives us an opportunity to align our implementation with theirs, to the extent possible, and get ideas and feedback from them if our implementations have to diverge in some capacities.

I think as a first step, we should update a README (probably in vets-api) that points at the [existing documentation in confluence](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2400256031/Parent+Helm+Chart+Setup) and to links to the relevant branch in vets-api, where the charts are hosted.

Since vets-api is a public repo, we can then use the [chart-releaser-action](https://github.com/helm/chart-releaser-action#example-workflow) to automate our release process. In the context of this, I would consider any renaming of branches or folders that are involved to see if we want to align ourselves with naming conventions. See the settings for the github action for examples, or get opinions of other members of the platform. We can also use the [Helm Charts Best Practices](https://vfs.atlassian.net/wiki/spaces/DO/pages/2774040862/Helm+Chart+Best+Practices) from our confluence to consider changes we might want to make.

There was also some concern about people releasing charts who don't know what they are doing and it seems like there may be a way to limit who gets to [run specific actions](https://stackoverflow.com/questions/61383941/make-sure-some-github-action-only-run-by-the-owner), such as admins. I still have to explore this a little more.

**Comment by laineymajor** [comment]
Start giving this a spin! @flooose to meet with Patrick Black

**Comment by jennb33** [comment]
The Helm charts are moving from Index to Containers (CR) moving forward, and the GitHub pages are going to be deprecated, per @RachalCassity and @Kshitiz-devops 
Please add more information based on the Discovery that you learned, Kshitiz.

**Comment by Kshitiz-devops** [comment]
The packaging of helm chart should be automated. Our plan is to use ECR as helm repo which can be used easily for deployment. Once the package of helm chart is automated to ECR the helm chart will be versioned with Semantic versioning which will match with the container version so each helm chart will be deployed with their container version which will be helpful with preview instances in eks.
