### ISSUE TITLE
Pre-Usability Review Medical Device Reordering Tool

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#6499]
## Steps to complete Usability Testing Prep: 
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [ ] VSP <> **requesting team** review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled meeting_
- [Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/product-outline.md)
- Link to or attach prototype or mockups - [All states](https://vsateams.invisionapp.com/share/6MVTG94WNH5), [Walkthrough](https://vsateams.invisionapp.com/share/8NWBZNBFPMV), **we plan to test in staging for this usability study**
- Link to [Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/research/usability-march20/research-plan.md) and [Conversation Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/research/usability-march20/conversation-guide.md)
- Link to regression test plan ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#regression-test-plan)) (if there isn't already a regression test plan for this feature in TestRail) _for QA practice area review_
- Link to test cases/test plan in TestRail ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) (even if just a draft) _for QA practice area review_

## Meeting attendees from Benefits and Memorials 2
- Product Manager (required): Leah Keeler
- DEPO product lead (required): Matt Self
- Anyone else from your team who significantly contributed to the artifacts provided (required): Riley Orr, Rebecca Walsh

## Scheduling
Preferred dates or times: 
As soon as possible  

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product

**Comment by meganhkelley** [comment]
hey @leahkeeler ! please be sure to tag myself and @andreahewitt-odd here and in Slack when you're ready for us to schedule this. we won't take action until then. thanks! 👍

**Comment by leahkeeler** [comment]
Thanks @andreahewitt-odd - we are not quite ready to schedule this - just getting everything organized in our backlog so we can plan! Thanks for the heads up

**Comment by meganhkelley** [comment]
Scheduled for 3/31

**Comment by tlei123** [comment]
@leahkeeler, please ping @pjhill & me on #vsp-product-support when Regression Test Plan is ready for review...

I've added a Regression - MDRT test-cases section to house your Regression Test Cases: https://dsvavsp.testrail.io/index.php?/suites/view/8&group_by=cases:section_id&group_order=asc&group_id=57

Feel free to delegate test-cases development to team members -- share your TestRail VSA-BaM2 team-specific account credentials with them for access.

Once you have all the Test Cases created, you can create a Test Plan, add a Test Run to it, and select your Test Cases for the Test Run.  Ping me as needed for futher help/info.

Thanks much!

**Comment by pjhill** [comment]
If you run into any issues using TestRail and need some help figuring anything out then please contact me through Slack or pose your question in #vfs-platform-support.  I'm happy to help.

Please keep in mind that there are some tutorial write-ups and videos demonstrating various aspects of using TestRail here -- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/quality-assurance/testrail

**Comment by jenstrickland** [comment]
For the Walkthrough prototype link, it is requesting login credentials, but the All States link is not.  Are there credentials to use?

**Comment by pjhill** [comment]
As discussed with @leahkeeler and @tzelei, a regression test plan for this product is not relevant at this time as this is the first version of a newly specified product on VA.gov.  Tze will be delivering a QA test plan with test cases based on the user stories and acceptance criteria for the new product.

**Comment by tlei123** [comment]
@leahkeeler @pjhill , here's my [regular QA Manual-UI (_not_ regression) Test Plan](https://dsvavsp.testrail.io/index.php?/runs/overview/7) for whoever's curious...

The test-cases in this regular Test Plan will be copied over to a Regression Test Plan/Run after my regular QA test-runs against Staging.

**Comment by tlei123** [comment]
> The Product Outline here is for [Debt Letters](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/debt-letters-mvp), @leahkeeler — is there one for MDRT?

@leahkeeler @jenstrickland , i just corrected the Product Outline link.  copied here too: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/product-outline.md

**Comment by leahkeeler** [comment]
Hi @jenstrickland - here is the product outline for medical device reordering https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/product-outline.md. I am not sure I understand your question about logging in. 

Thanks, Leah

**Comment by jenstrickland** [comment]
There are two links in the bullet point above:
> Link to or attach prototype or mockups - All states, Walkthrough, we plan to test in staging for this usability study

The "All states" link works fine. The "Walkthrough" requests login credentials, but mine didn't work. We probably need @rileyorr or @rebeccawalsh to clarify.

**Comment by emilywaggoner** [comment]
@leahkeeler Would you mind linking to where this lives in Staging since that's what you'll be using in the usability study?

**Comment by leahkeeler** [comment]
@emilywaggoner  https://staging.va.gov/hearing-aid-batteries-and-accessories - there is some code that has not been merged yet - we can show you on dev's local if need be. Thanks!

**Comment by mnorthuis** [comment]
My apologies, I thought I had posted a comment here, but  not seeing one.  There is no IA feedback for the purposes of the usability study.  Don't forget to submit the IA request once research is complete to finalize page flow/structure, URLs, breadcrumbs and navigational changes for all impacted pages.
