### ISSUE TITLE
Utility/Vets.gov Bake Instance Cleanup

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#64996]
# Description
Discovery information about this pipeline will be recorded against this ticket.

# Tasks
- [ ] Is this using an AL1 image?
- [ ] How difficult is this to move out of Jenkins?
- [ ] Who knows more about the way this pipeline or its artifacts are used?

**Comment by pjhill** [comment]
Relevant links to files --

- https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/applications/config/blackbox-exporter.yml
- https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/deployment/config/blackbox-exporter
- https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/utility-exporter/blackbox.yml.j2
- https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/blackbox-exporter-ew-utility.yml
- https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/dsva-vetsgov-ew-utility/blackbox.tf
