### ISSUE TITLE
[BE] 10-10EZ - Monitoring & Alerts: Add monitor & alert for failed mailer

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#65001]
## Background
To support the PACT Act enrollment deadline 9/30, we need to add an alert for a failed mailer. 
- Scenario: Submission runs out of retries and mailer fails to notify user.
The alert would feed into our #health-tools-1010-apm channel.

## Tasks
- [x] Set up a monitor to track when a submission fails at the mailer step
- [x] Set up alert to notify #health-tools-1010-apm channel each time a submission fails at the mailer step
- [x] Test alerts, if applicable
 
## Acceptance Criteria
- Submissions with mailer failures are monitored, and alerts are set up and will be sent to the apm slack channel.

**Comment by hdjustice** [comment]
#1 add alert for failed mailer. scenario: submission runs out of retries and mailer fails to notify user.
-- 3

#2 add alert for failed, no retries. we get about 10 of these per month. i want us to be alerted, ticket each one, and then try to chase down the root cause for the failure with the VES team. goal is to understand each failure and explore ways to prevent the same kind in the future. - Log entire form as well
-- 5

#3 understand the health check sensitivity for the various ES downstream services and, if appropriate, tune those health checks so breakers don’t trip as quickly - we may not have this in our code base, check with Platform
-- 

#4 assess the use of a conditional warning message that we can flip on if there are issues
-- DONE

#5 add synthetic datadog health checks in addition to the fwdproxy-based health checks for the downstream ES services. reasoning: much easier to configure/tweak datadog health checks and easier to see why a health check failed. i believe at least one of these was created already by mike chelen. - we may not have this in our code base, check with Platform
--
