### ISSUE TITLE
[BE] Handle the 60-second Limit for the Travel Claim Sidekiq Worker

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#65011]
## Related SPIKE Ticket
[See spike ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64070)

## Tasks
- [ ] [BE] **andle the 60-second Limit for the Travel Claim Sidekiq Worker**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by loripusey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/65011?planning-poker) with Zenhub @randomsync @kanchanasuriya
