### ISSUE TITLE
[CHIP] [BE] POST mobile_check_ins_demographics accepts invalid key in demographic_confirmations

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#65015]
## Description
Request payload for **POST** `mobile_check_ins_demographics` endpoint accepts invalid key in `demographic_confirmation` object.

Instead of sending below payload,
```
{
	"station_no": "500",
	"patient_dfn": "384",
	"demographic_confirmations": {
		"contactNeedsUpdate": false,
		"nextOfKinNeedsUpdate": false,
		"emergencyContactNeedsUpdate": false
	}
}
```
if the endpoint called with
```
{
	"station_no": "500",
	"patient_dfn": "384",
	"demographic_confirmations": {
		"c": false,
		"nextOfKinNeedsUpdate": false,
		"emergencyContactNeedsUpdate": false
	}
}
```

endpoint succeeds setting the demographic confirmations

## Tasks
- [ ] [BE] **Modify api request payload validation to verify demographic_confirmations object**
- [ ] [BE] **Unit tests**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by kanchanasuriya** [comment]
@loripusey Currently, the endpoint succeeds even if called with invalid keys.  As long as the endpoint gets called with valid keys, we will not see this issue.  But this task is to handle the case where the consuming application makes a typo with the keys.  It is not a blocking issue to be closed before launch, but nice to get fixed.

**Comment by loripusey** [comment]
thanks @kanchanasuriya

**Comment by loripusey** [comment]
@kanchanasuriya can you point this ticket when you get a chance? thanks.

**Comment by loripusey** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/65015?planning-poker) with Zenhub @kanchanasuriya

**Comment by loripusey** [comment]
moving this ticket to tech debt so I can close the epic
