### ISSUE TITLE
[Design] 10-10EZR - Standalone form: Create Error message catalogue

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#65013]
## Background
Since the 10-10EZR will be a full form, we need to include all possible error messages that will appear from the Intro page to the Confirmation page.

### Resources
- [10-10EZ Error Audit](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683651181051/e0f47b9aaefbf78a3942df3028525cdc4336caff?sender=ubf5503bf47b6eb1e92730053)

## Tasks
- [x] Review 10-10EZ error audit
- [x] Create Mural board draft of 10-10EZR errors that may be possible based on enrollment status, input errors, submission errors, etc
- [x] Review with team/PM

## Acceptance Criteria
- An Error message catalogue is created and can be used as a future reference for the form, so we will know exactly what errors the Veteran can expect.  These may also be used in the Contact Center guide for customer service representatives to reference.

**Comment by jessicastump** [comment]
This Mural now contains the drafts of the alerts in the Sketch file so far, reviewing with design team via Slack. Will update images and content once alerts are reviewed and finalized.

**Comment by jessicastump** [comment]
[Opened a ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65971) to circle back to all source of truth docs when mvp is ready for production and confirm they are still up to date and complete.
Closing this ticket.
