### ISSUE TITLE
[Design] 10-10EZ Intro page - Already enrolled version page updates

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#65014]
## Issue Description
Update intro page content around EZR options once EZR is live.

[Link to Discovery ticket comment
](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63746#issuecomment-1699962749)

[Sketch link to page as it exists today](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/MyZyrxW)
---
## Tasks
- [ ] Update designs to include accurate / call to action for EZR to make updates
- [ ] Review with content team / CAIA for edits

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---

**Comment by hdjustice** [comment]
@hdjustice - reminding myself to make sure we have this as an FE ticket

**Comment by jessicastump** [comment]
Adding a note that this version was included on [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69447) as well for overall intro page updates needed.
