### ISSUE TITLE
Create Support Bot Satisfaction Survey Auto-Responder

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#65038]
## Description 
The goal is to use the survey created here: https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/65037

We'd ideally like the a survey message to respond automatically to each support ticket when closed. The support message should thank the user for using Platform Support and kindly ask for their feedback, linking them the above survey.

---

## Definition of Done
- [x] An auto response with a link to a survey appears each time a ticket is closed in support. 

---

## Tasks 

- [x] Scope out what it would take to accomplish this
- [x] Add a function that auto-responds with a survey when tickets are closed
- [x] Call this function every time the close button is pressed on a ticket.

---
