### ISSUE TITLE
Create Satisfaction Survey Manual Responder

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#65037]
## Description 
This ticket is for creation of a satisfaction survey to be manually copy and pasted on each completed ticket. In the future, we will have an auto-responder as a part of our Support Bot enhancements here: https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/65038

---

## Definition of Done
Tasks completed below.

---

## Tasks 

- [ ] Create a Google Form Satisfaction Survey to copy and paste to each ticket when completed.
- [ ] Send to Tier 1 Team
- [ ] Add to Support Best Practices

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Google Form: https://docs.google.com/forms/d/1HhTnvEAWJqEvwTxEUCtvoT6Cqkjss30nrOcGOgXB6kU/edit
Responses Spreadsheet: https://docs.google.com/spreadsheets/d/1p6hNaNETjARisSezazWUgyNaskYWTh-byX3MnTN_oqg/edit?usp=sharing

**Comment by alyssagallion** [comment]
In review with Erika.

**Comment by alyssagallion** [comment]
Approved, notified VFS Support channel, closing.
