### ISSUE TITLE
[Research] 10-10EZ - Run Sessions for registration only generative research study

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#65035]
## Issue Description
Conduct interview research sessions for the registration only generative study. There are 2 cohorts with different audience segments. 

---
## Tasks
- [x] [Link to research repo](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/371)
- [x] Link to [transcripts folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/research/2023-06-Registration%20flow%20exploration/transcripts)
- [x] Link to [team notes folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/research/2023-06-Registration%20flow%20exploration/team-notes)
- [x] Maintain and update [Observer sign up sheet on Slack](https://dsva.slack.com/docs/T03FECE8V/F05RF4YRU4U)
- [x] Conduct sessions

## Acceptance Criteria
- [x] Sessions completed and all notes / recordings needed downloaded for synthesis
- [x] Confirm needed information on recruitment tracker with Perigean
---
