### ISSUE TITLE
Document IA problems with sidenav component & needs for an integrated secondary nav

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#65055]
## User Story
As an IA working on VA.gov, I want to document scalability problems with current sidenav component so that build alignment across all teams on the issues . 

As an IA working on VA.gov, I want to document the needs for an integrated secondary navigation that sits across all tools in the MHV to VA.gov transition in order to inform a cohesive solution for the user experience. 

## Description
The existing sidenav component in the Design System has structural and UX limitations, particularly on mobile, that will impede the success of navigation design when the MHV on VA.gov tools are integrated. This ticket is intended to track 1.) documenting problems with the existing component 2.) documenting needs navigation needs for the integrated MHV on VA.gov 3.) designing the currently planned MHV navigation hierarchy using existing VA.gov navigation designs to show the problems in a high-fidelity state (sidenav component & the facilities template).

## Impacted Artifacts
* [Documentation of issues on GH](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/research-and-analytics/health-integrated-navigation.md)
* [Link to sketch file with mock-ups](https://sketch.com/s/047b93a2-fa9d-4b4c-a801-10593e91dcca)

## Tasks
- [x] Document issues with sidenav component (especially mobile) @sterkenburgsara 
- [x] Mock up what MHV on VA.gov secondary nav would look like w/ existing patterns (prove that it is a crappy option) 
  - Existing sidenav component (Desktop & mobile) @jonathanjnelson @fmccaf1 
  - Facilities template (Desktop & mobile) - facilities template not actually in Sketch - this is manual effort @Jenny-yw 
- [x] Document needs for an integrated navigation for MHV on VA.gov @sterkenburgsara 

## Acceptance Criteria
- [x] Problems with existing sidenav component on Desktop are documented
- [x] Problems with existing sidenav component on mobile are documented
- [x] Needs for integrated navigation solution are documented
- [x] Mocks of MHV navigation using existing navigation components have been drawn up & are included in documentation

**Comment by LynneJohnson224** [comment]
@sterkenburgsara can you please add a story point value to this ticket when you get a chance? Thanks!

**Comment by fmccaf1** [comment]
Mock-ups are complete as far as Jonathan and I are aware. I included a [link to the sketch file in the text of the ticket but will also include here](https://sketch.com/s/047b93a2-fa9d-4b4c-a801-10593e91dcca). If anything is missing or you'd like anything else, please let us know whenever you have time to think about it, @sterkenburgsara
