### ISSUE TITLE
[Design] Final revisions to CST Detail Page based on Midpoint Feedback

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#65053]
## Background

After presenting our latest CST work to the platform team at [Midpoint Review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/58828) (9.5.23), the design team needs to make necessary iterations to the design based on "Must" and "Should" feedback.

## Acceptance criteria 

- [x] Update designs based on Design feedback and close out [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64860)
- [x] Update designs based on IA feedback and close out [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64935)
- [x] Update designs based on Content feedback and close out [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64919)
- [ ] Update designs based on A11y feedback and close out [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64936)

**Comment by HeatherWidmont** [comment]
@skylerschain are we good to close this?
