### ISSUE TITLE
Null Claim - Raise error for failed claim

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#65059]
## Issue Description
_If the Central Processing Claim fails for 686/674, we need to raise an error in Sentry/Datadog and attempt to email the Veteran (using the existing DependentsApplicationFailureMailer logic). Example of email text #56291_

Related #64538
---
## Tasks
- [ ] Determine what to do when these alerts are generated.
- [ ] Attempt to email the Veteran notifying them that their claim failed.

[526EZ does this already](https://app.zenhub.com/workspaces/benefits-team-1-6138d7b57a2631001a4b7562/issues/gh/department-of-veterans-affairs/va.gov-team/50111)

Some Notes from Kyle:

>       `CentralMail::Service.new.upload(processor.request_body)`

> does pretty much everything you need and already exists. Just gotta make sure you pass it the right stuff, and that the logic on when to send and when not to is sound. (and rejigger the order, so it only uploads to eFolder if the claim submission is successful instead of doing both at the same time like currently)
> Like right now you do
> 
> `establish_claim.perform() # async job queued`
> `upload_to_eFolder.perform(doc) # async job queued`
> 
> itll need to I think be something like
> 
> `establish_claim.perform() # async job queued`
> 
> and then

> `if claim_established_successful?`
>   `upload_to_eFolder.perform(doc) # async job queued`
> `else`
>   ` send_to_central_mail.perform(doc)`
> `end`

> added into that establish job

## Acceptance Criteria
- [ ] Process documented for post-alert workflow.
- [ ] Veteran receives email notifying them their claim submission failed.
---

**Comment by steele-lm** [comment]
Close as dupe based on error handling already implemented. Create new ticket for dashboard alert base on logs.
