### ISSUE TITLE
SPIKE | Provide claim info to VBA when pdf is missing

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#65062]
## Issue Description
_Determine how to provide the VBA with 686/674 claim information if the pdf fails to generate (e.g, using the json file to generate the pdf)._

---
## Tasks
- [ ] Determine how to pull claim information if pdf fails to generate.
- [ ] Determine how to provide VBA with information for failed claim.
- [ ] Follow on tickets to capture required work

## Acceptance Criteria
- [ ] Process for pulling failed claim information
- [ ] Profess for providing VBA with failed claim information
---

**Comment by tblackwe** [comment]
We've got a request to estimate this ASAP so we can provide timeline to team. I am grabbing the ticket and reviewing it. @tfink419 I may need your help.
