### ISSUE TITLE
Sync with SM to get landing page link updates for phase 1

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#65063]
## User Story
As a Cartography team member, I need to know what links to update and/or what link text to update for the Secure Messages section of the landing page, so that users can be routed to the correct places as seamlessly as possible. 

## Description
Secure Messaging will got to Phase 1 by/around the end of October. At that time, MHV Classic will have messaging that allows all Veterans to "try out" the new SM on VA.gov. 

In advance of that happening, we need to sync with the SM team to see if/what links need to be changed out on the landing page, or if link text needs to be updated to reflect the VA.gov experience instead. Redirects may also need to be put in place for any users who bookmarked old links from our landing page. 

## Impacted Artifacts
* MHV on VA.gov landing page 

## Tasks
- [ ] Sync with Secure Messages UX team
- [ ] Document needed changes
- [ ] Request redirects as necessary
- [ ] Create follow-on ticket to sync timing of PRs with SM launch to Phase 1

## Acceptance Criteria
- [ ] SM Phase 1 changes for the landing page are known and documented

**Comment by sterkenburgsara** [comment]
Whoops, closing - this ticket is a dupe of #63802
