### ISSUE TITLE
SPIKE | Logging Approach

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#65060]
## Issue Description
_Understand best approach for logging in 686 and 674._

---
## Tasks
- [ ] Work with Sam Stucky to understanding if we should implement his approach to logging for 686 and 674.
- [ ] Implement sidekiq_retries_exhausted() for all of the cases where we run sidekiq jobs.  Example [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/sidekiq/decision_review/submit_upload.rb#L18).
- [ ] Document approach logging.
- [ ] Create follow on tickets for implementation.

## Acceptance Criteria
- [ ] Logging documentation
- [ ] Follow on tickets
---
