### ISSUE TITLE
Spike - Document known IAM Issues, Shortcomings and Pain Points

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#65068]
## Issue Description
Our team has identified potential areas of concern with how we approach Identity and Access Management (IAM) processes and procedures. This spike is intended to define what we know about these areas and provide a comprehensive overview of known issues. The findings from this spike will help lay the ground work for further discussions with key stakeholders and potentially identifying and prioritizing improvements in this area.

The primary objective of this spike is to investigate and document in detail the following identified shortcomings:
- Non-Compliant Accounts: There's a significant number of non-compliant accounts. We need to understand why this is the case and what the implications are.
- Ticket Closure: There seems to be a delay or lack of follow-through in closing tickets.
- Documentation: There's a gap in our documentation, which could be leading to ambiguities or inefficiencies.
- Process Enforcement: We lack solid processes for specific requirements like temporary access requests.
- Auditing: Our auditing processes might not be capturing all relevant activities or might be non-existent.
- Transparency: Account naming doesn't seem to have a clear connection to real individuals. This can lead to confusion, with accounts like John.Smith1,2,3,4 potentially referring to any number of people.
- Automation & Approval: The current automation for IAM might not be efficient, and the approval processes are described as weak.

---
## Tasks
- [x] [Review this document](https://vfs.atlassian.net/wiki/spaces/~642ae03222330bdf97ab3248/pages/2749399066/Brainstorming+Access+Expiration+Automation+GitHub+Team+OAuth) written by Ryan McNeil - Provides some background about how access re-validation is being handled in some areas currently
- [x] Detail Documentation of Each Shortcoming - For each of the seven points mentioned above, provide detailed documentation about the current state, why it's a concern, and potential implications.
- [x] Engage Stakeholders - Reach out to Clint and any other necessary stakeholders to gather more context and insights on these shortcomings.
- [x] Collaborate with Team - Collaborate with Ben Allen and any other relevant team members to ensure the documentation is comprehensive and captures all facets of the issues.

## Acceptance Criteria
- [x] Each of the seven identified shortcomings is documented in detail, capturing its current state, implications, and any other relevant information.
- [x] Key internal stakeholders, including Clint and Eric review information, and their feedback/input is incorporated into the documentation. (List of internal stakeholders can be expanded as needed outside of our team - for example: Kyle)
~- [ ] If pending approval/guidance - an epic/list of tickets to be created to begin to quantify the additional work in these areas.~

**Comment by ben-allen-oddball** [comment]
Documentation started here: https://docs.google.com/document/d/1v1vKJPod6x2Lmrl8jWDFQSr30fN4YTwpylX9dqgRIMo/edit

**Comment by ericboehs** [comment]
I'm not able to access that.

**Comment by JoeTice** [comment]
SPRINT 52 STATUS: IN PROGRESS - This task is in progress, but due to some discussions about needing to be careful about how data about potential vulnerabilities is shared, we delayed posting this and marking this ticket as complete. It will be completed in Sprint 53.

SPRINT 53 - 5/9 update, information has been shared, and this task is closed.
