### ISSUE TITLE
FAR Secondary Research - Fact Gathering & Analysis

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#65087]
## Issue Description
Evaluate VA research in the GitHub repository for information on Power of Attorney, Representatives, Claims Process (including initial submit and NODs). As well as secondary sources such as Reddit, Google, VA.gov. This work will inform product, user, and technology requirements for the FAR product.

---
## Tasks
- [x] Analyze secondary sources from [VA GitHub Research Repository](https://github.com/department-of-veterans-affairs/va.gov-research-repository/projects/1)
- [x] Reach out to Slack Channels in both VA and Oddball to connect with employees on previous research
- [x] Answer questions using VA.gov information materials
- [x] Review community feedback using [Reddits Veterans Benefits subReddit](https://www.reddit.com/r/VeteransBenefits/)
- [x] Fill in any remaining gaps using SME interviews and/or Google
- [x] Create ticket for report
---
## Acceptance Criteria
- [x] Consolidated findings for secondary research report
