### ISSUE TITLE
ARM UX Flows

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#65084]
## Issue Description
Create user flows and starting logic for representative search, selection, 21-22 form and submission flow.

---
## Tasks
- [x] Complete search flows
- [x] Complete 21-22 entry flows
---
## Acceptance Criteria
- [x] Completed flow for Mondays brainstorm
