### ISSUE TITLE
[DISCOVERY] Grafana

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#6508]
## User Story or Problem Statement
 How might we document the response problem (rebooting, forwardproxy)?

## Goal
Improved query response performance

## Objectives or Key Results this is meant to further

Objective 1: Enhance the search process
Key result: Time for delivery of results for Community Care searches will improve by (TBD) by (date)

## Tasks
- [ ] Meet with VSP
- [ ] Access Cloudwatch logs
- [ ] Discover how to define Grafana to show response problems which occur between rails and PPSM instances

## Acceptance Criteria
- [ ] Documentation of response logs for VSP triage
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
@tskinn for your visibility.....thanks for your help

**Comment by mmiddaugh** [comment]
This is blocked by need to update logging on VSP side

**Comment by mmiddaugh** [comment]
This issue has been handed to VSP for next steps
