### ISSUE TITLE
FAR Secondary Research - Report

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#65085]
## Issue Description
Evaluate VA research in the GitHub repository for information on Power of Attorney, Representatives, Claims Process (including initial submit and NODs). As well as secondary sources such as Reddit, Google, VA.gov. This work will inform product, user, and technology requirements for the FAR product.

---
## Tasks
- [x] Create final report of secondary findings
- [x] Share-out findings with team
- [x] Discuss next steps + action items with team
---
## Acceptance Criteria
- [x] Final report + next steps
