### ISSUE TITLE
ARM Analytics Request

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#65083]
## Issue Description
Requesting further analytics from VA and VBA on claims to supplement research and product decisions.
---
## Tasks
- [x] Create documentation request for analytics
- [x] Review documentation request with team
- [x] Submit for analytics from VA team
---
## Acceptance Criteria
- [x] Final documented request for analytics submitted to the VA team

**Comment by jfinnerty13** [comment]
@holdenhinkle @oddball-lindsay document for reference and review https://docs.google.com/document/d/1oErdwMh28YCunAY10ewFXfTcTgCuioO2OnSbP0Tv-n8/edit?usp=sharing

Can I get edits by end of week please so I can review with Alex next week? Thanks!

**Comment by oddball-lindsay** [comment]
@jfinnerty13 looks good to me!

**Comment by jfinnerty13** [comment]
Documents submitted by Zach - Request ID: 202341072
https://dsva.slack.com/archives/C05L6HSJLHM/p1695680509980899?thread_ts=1695648171.969579&cid=C05L6HSJLHM

**Comment by jfinnerty13** [comment]
Team has been emailed, Alex responded, waiting on findings.

**Comment by oddball-lindsay** [comment]
There have been some questions around how common it is for Veterans to have more than one representative.  Asked Alex if we can expand the open analytics request to include some numbers around that, proposed:

1. What is the median (or could be average) # of representatives assigned to Veterans
2. What percentage of Veterans have more than 1 representative assigned to their profile?

**Comment by jfinnerty13** [comment]
@oddball-lindsay we received the analytics report - https://dsva.slack.com/archives/C05L6HSJLHM/p1698419548652789

Is there anywhere else you'd like to document this? Thanks!

**Comment by oddball-lindsay** [comment]
Thinking we can store this in our Research folder in Github 

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/accredited-representation-management/research
