### ISSUE TITLE
[FE] 10-10EZR - Standalone form: Create Veteran Info form pages

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#65119]
## Description
For the 10-10EZR standalone form, we need to create the form pages for the Veteran Info section. This section includes information like the Veteran's address(es), contact details, and birth sex. For this section, we will NOT be including fields for Next of Kin, Emergency Contact, Preferred Name or SIGI. The Veteran PII fields (Name, DOB, SSN) will be displayed in a read-only page at the beginning of the section.

## Resources
- [Sketch file](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/F6017C84-ED86-425A-A22C-01E1BDBF9533/canvas)

## Tasks
- [x] Create schema configs using the v3 web component patterns in the forms library
- [x] Populate global form config with page schemas and meaningful, SEO-compliant page routes
- [x] Properly unit test schemas for number of inputs and error handing

## Acceptance Criteria
- Form pages successfully render for review and completion

**Comment by jessicastump** [comment]
@longmd Here is the link to the [Veteran information Sketch page](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/F6017C84-ED86-425A-A22C-01E1BDBF9533/canvas)
