### ISSUE TITLE
Foreign Address Issue Dashboard

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#65127]
## Issue Description
_Understand if the mitigations to fix the foreign address issue are working. Goal: Prevent domestic claims from being sent for processing in Pittsburgh as foreign claims. Related to research in #61193._

---
## Tasks
- [ ] Create a dashboard that shows the number of claims originating from VA.gov where users have indicated that they "live on a military base outside of the U.S." but entered a postal code that does not fall within the codes belonging to an APO, DPO, or FPO as outlined by Zach [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61193#issuecomment-1652366219).
- [ ] The dashboard should show the following information:
   - [ ] The volume of claims
   - [ ] Veteran identifier (e.g., ICN)
   - [ ] Claim identifier (e.g., 686c)
   - [ ] Date claim was submitted
   - [ ] Address entered in claim (street, city, postal code)

## Acceptance Criteria
- [ ] A dashboard that shows the criteria listed above.
---

**Comment by steele-lm** [comment]
BIS implemented the change at the database level, so tracking before/after effects of implementing an address fix is not possible. Closing this ticket.
