### ISSUE TITLE
[FE] 10-10EZR - Standalone form: Populate Introduction page content

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#65123]
## Description
For the 10-10EZR standalone form, we need to populate the Introduction page content. This will include an alert and next steps for users who are not enrolled in VA Health Care and application start button and required documentation for enrolled users that are eligible to complete the form. The OMB information will also be housed on this page.

## Resources
- [Sketch file](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/34F1F294-5E1D-46C1-ADE6-AC6C398E2130/canvas)

## Tasks
- [x] Create individual components to house content for each enrolled scenario
- [x] Populate page with components and conditionals
- [x] Properly unit test all components and branches
- [x] Properly wire up page for e2e testing

## Acceptance Criteria
- Introduction page successfully renders for use

**Comment by jessicastump** [comment]
@longmd The design ticket for this section of the EZR is complete.
- [Github ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63823)
- [Sketch file](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/3B1847D9-15A8-4526-A264-F00F656EDAC6/canvas)

**Comment by longmd** [comment]
@jessicastump , quick question.... Any interest having that initial logged out alert be USWDS styling? I have to create a custom alert, because the content doesn't quite match the default SIP alert, so didn't know if you wanted to update that one or leave as is.

**Comment by jessicastump** [comment]
Had some questions via Slack but adding that [this is the component](https://design.va.gov/components/alert#sign-in-to-start-your-application) advised to use during office hours attended. Is breaking the default if we remove the note only? Both the intro sentence "here's how it helps" and the note about signing in after starting don't apply for the EZR so that was the content removed.

**Comment by jessicastump** [comment]
Summary of the update - components are being updated in the middle of this process too - we will use what is available for v3 components, including moving away from the gray background.
