### ISSUE TITLE
[FE] 10-10EZR - Standalone form: Create Household Info form pages

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#65120]
## Description
For the 10-10EZR standalone form, we need to create the form pages for the Veteran Info section. This section includes information for a spouse, any dependents and income/expenses for the Veteran and any declared household members.

## Resources
- [Sketch File](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/3B1847D9-15A8-4526-A264-F00F656EDAC6/canvas)

## Tasks
- [x] Create schema configs using the v3 web component patterns in the forms library
- [x] Populate global form config with page schemas and meaningful, SEO-compliant page routes
- [x] Properly unit test schemas for number of inputs and error handing

## Acceptance Criteria
- Form pages successfully render for review and completion

**Comment by jessicastump** [comment]
@longmd The design ticket for this section of the EZR is complete.
- [Github ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63823)
- [Sketch file](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/3B1847D9-15A8-4526-A264-F00F656EDAC6/canvas)
