### ISSUE TITLE
[FE] 10-10EZR - Standalone form: Populate Confirmation page content

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#65125]
## Description
For the 10-10EZR standalone form, we need to populate the Confirmation page content. This will include specific views for on-screen & printed rendering.

## Resources
- [Confirmation page sketch link](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/5832D810-94E4-48FE-A8F1-A142424BA072/canvas)
- [Review page sketch link](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/AE6DF9B2-59AA-47A8-A038-DD8F238C92DB/canvas)

## Tasks
- [x] Create individual components to house on-screen and printable content
- [x] Populate page with components and conditionals
- [x] Properly unit test all components and branches
- [x] Properly wire up page for e2e testing

## Acceptance Criteria
- Confirmation page successfully renders for use
