### ISSUE TITLE
[FE] 10-10EZR - Standalone form: Create Insurance Info form pages

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#65121]
## Description
For the 10-10EZR standalone form, we need to create the form pages for the Insurance section. This section includes information like the Veteran's insurance policy information and medicare/medicaid eligibility.

## Resources
- [Sketch file](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/31E4F6F4-F97C-45D9-AAFE-FF20C19E0504/canvas)

## Tasks
- [x] Create schema configs using the v3 web component patterns in the forms library
- [x] Populate global form config with page schemas and meaningful, SEO-compliant page routes
- [x] Properly unit test schemas for number of inputs and error handing
- [x] Create multiple response pattern for insurance policies
- [x] Properly unit test multiple response components

## Acceptance Criteria
- Form pages successfully render for review and completion
