### ISSUE TITLE
Copy of Onboarding Tools Access for new Veteran Support Team Member - John C. 

### ISSUE THREAD

**Issue by Kimberley2023-CSM** [department-of-veterans-affairs/va.gov-team#65158]
## Issue Description
_Tracking ticket for tool access for new team members.  Not all team members will need access to all of the tools.  The list below is all-encompassing for Veteran Support team members._

---
## Tasks
- [x] Salesforce
- [x] GitHub
- [x] ZenHub
- [x] AVA (Ask VA)
- [x] Citrix/Azure
- [x] MVI Toolkit (VA side)
- [x] VA email address
- [x] Slack
- [x] PIV/PIV Extension

## Acceptance Criteria
- [x] _Complete list of access to applications for team members. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
As of 9/28/23 John stated the following:

 Got an email letting me know I have been sponsored for a PIV and to schedule a time to pick it up. It is scheduled for Friday October 6th at 1:00PM EST.  I also called the help desk for a PIV exemption and can now access Citrix.

**Comment by Kimberley2023-CSM** [comment]
AS of 10/5/23, John is due to pick up his PIV on 10/6/23.

**Comment by ATMiddleton** [comment]
Complete
