### ISSUE TITLE
Incoming Issues Tracking - Per Sprint 9/10/23 - 9/23/23

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#65157]
## Issue Description
Contact Center will review and track all incoming issues escalated from VEO.

---
## Tasks
- [x] _Tabulate incoming issues into categories - Tier 2/Tier 3/Tier EVSS	
- [x]  Create a grid displaying the number of incoming issues for each category
- [x]  Publish report for leadership at the end of each Sprint

## Acceptance Criteria
- [ ] Report published for leadership viewing
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdEhRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d151daa824f35a113e7d68a6fdcc49340deb77cc/image.png)
