### ISSUE TITLE
Copy of Incoming Issues Tracking - Per Sprint 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#65156]
## Issue Description
Contact Center will review and track all incoming issues escalated from VEO_

---
## Tasks
- [ ] Tabulate incoming issues into categories - Tier 2/Tier 3/Tier EVSS
- [ ] Create a grid displaying the number of incoming issues for each category
- [ ] Publish report for leadership at the end of each Sprint

## Acceptance Criteria
- [ ] Report published for leadership viewing
 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
Duplicate
