### ISSUE TITLE
Work with VSignals team to setup new Medallia version

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#65169]
## As a Veteran Support Engineer, I need to collaborate with the Medallia team so that Medallia 2.0 upgrade includes attributes of the required styling attributes 
---
## Tasks
- [ ] Collaborate with Medallia team to complete discovery for 2.0 upgrade 
- [ ] Collaborate with Medallia team to determine requirements 
- [ ] Define styling attributes 

## Acceptance Criteria

- [ ] **Scenario 1: Collaborate with Medallia team for discovery**
  - Given that the Medallia team is available for collaboration
  - When the Veteran Support Engineer initiates a discussion with the Medallia team
  - Then the discovery process for the Medallia 2.0 upgrade is completed

- [ ] **Scenario 2: Collaborate with Medallia team to determine requirements**
  - Given that the Medallia team has provided the necessary information
  - When the Veteran Support Engineer collaborates with the Medallia team to determine the requirements
  - Then the requirements for the Medallia 2.0 upgrade are defined

- [ ] **Scenario 3: Define styling attributes**
  - Given the requirements for the Medallia 2.0 upgrade have been determined
  - When the Veteran Support Engineer defines the required styling attributes
  - Then the styling attributes for the Medallia 2.0 upgrade are defined

**Comment by clantosswett** [comment]
@ATMiddleton and @aubreyarcangel is this issue duplicative of what we already have on the board? If yes, we can someone go ahead and close this. Thanks!

**Comment by ATMiddleton** [comment]
Duplicate ticket #76423
