### ISSUE TITLE
Content edits for Datadog Troubleshooting

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#65176]
## Issue Description
This is a continuation of [this ticket's comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61545#issuecomment-1707033291).

The [Troubleshooting Access to Datadog](https://depo-platform-documentation.scrollhelp.site/developer-docs/troubleshooting-access-to-datadog) page on the Platform website needs to be overhauled due to some recent instruction changes.

**Information from Lindsay Insco from the Platform support team:**

- Yes. But [the instructions become] extremely short.
- So if you get a PIV/CAC error you just have to go to the #dots-dsva Slack channel
- So where it says “Click on “Department of Veterans Affairs” under “MAX AGENCY FEDERATED PARTNER”” all of that and below is no longer valid. (Except for the "Additional Support" section).
- You receive an error, please contact the DOTS team at #dots-dsva
- This is the PIV/CAC error users now see. See image attached.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcGVCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1d6a249046fccc3e07164b3236d094262cc3997e/IMG_5151.png)

---
## Tasks
- [x] Revise the content on the [Troubleshooting Access to Datadog](https://depo-platform-documentation.scrollhelp.site/developer-docs/troubleshooting-access-to-datadog) page according to changes listed above
- [x] Reach out to Lindsay Insco to help QA the new version of the page
- [x] Prepare the page for deployment

## Acceptance Criteria
- [x] The [Troubleshooting Access to Datadog](https://depo-platform-documentation.scrollhelp.site/developer-docs/troubleshooting-access-to-datadog) page will have revised instructions after the "Click on “Department of Veterans Affairs” under “MAX AGENCY FEDERATED PARTNER” section.

**Comment by BSmolensky** [comment]
I created a copy of the page and edited that copy in the Draft space. Once completed, I sent the link to the edited page to Lindsay insco and asked for her feedback.  Once I got the thumbs up from her and her team, I transferred the changes to the live doc and updated it. Then I archived the copy. The updated page is now in Scroll Viewport and should get deployed on Wed 9/20/23.

**Comment by BSmolensky** [comment]
Passing on positive feedback: 

Here is what Lindsay had to say about the update: 
"Hello~ Some other team members are saying it looks good! Thanks so much for the hard work putting this info together! It turns out we're indeed getting a lot of questions about it :) so the updates help."
