### ISSUE TITLE
Create documentation for embedding survey on VA.gov 

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#65171]
## Issue Description
Research what options are available to address issues target users would have with embedding a feedback rating/survey when replacing the current rating mechanism.  

---
## Tasks
- [x] _Explore options 
- [x] _Document options 
- [x] Determine and document current issues with existing rating tool
- [x] Define user persona

## Acceptance Criteria
- [x] Publication on Confluence 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
Meeting scheduled. 10/10/23 - 
Performance dashboard is public facing and linked on VA.gov (formerly VA scorecard) – meant for leadership to view User satisfaction https://www.va.gov/performance-dashboard/ aggregate of data collected by all surveys 

Options for Medallia feature – how do you rate your experience – IA team wants to know if Medallia can accommodate users with screen readers 
1.	Embedding a Medallia form – styled to look like VA.gov – We don’t know if Medallia 2.0 can accommodate – launch without the accessibility feature – this will add bulk to the pages and Users may not like it – can slow down page performance – and we don’t know if leadership will approve   
2.	Hitting yes or no would trigger Medallia modal – smallest lift 
3.	Can we use our own html elements and then send data to Medallia – accessibility issues are not issues with this option – but heavier lift – requires DevOps and other teams.

**Comment by ATMiddleton** [comment]
Determination to pursue Option 1. Embedding a Medallia form – styled to look like VA.gov

**Comment by ATMiddleton** [comment]
Option 1 was chosen.  All future surveys will follow the procedure,  

Upon approval of all questions by OMB, for Medallia - Sarkis will upload to the staging environment and upon internal approval they surveys can be deployed.  

Other surveys that require UX designs will complete the collab cycle.
