### ISSUE TITLE
Add Accredited Representation Management to the VA Product Directory

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#65175]
## Issue Description
We are technically a new VFS team and part of the new team onboarding requires our product to be added to the [VFS Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).

I put in a Platform support request for this ([open ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64595)), but there hasn't been any movement.  Opening a ticket specifically for our team, in case @holdenhinkle might be able to assist.

#### Information about our team
- Product Name: Accredited Representation Management
- OCTO Product Owners: Zach Goldfine
- OCTO Crew: Accredited Reps
- VFS PM: Lindsay Li-Smith
- Product folder: [products/accredited-representation-management](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/accredited-representation-management)
---
## Tasks
- [ ] Add a row to the VFS Product Directory including the information above which links to a landing page (next task)
- [ ] Create a landing page for Accredited Representation Management, landing page URL pathway conventions suggests `https://depo-platform-documentation.scrollhelp.site/getting-started/**accredited-representation-management**`

## Acceptance Criteria
- [ ] Accredited Representation Management is included on the VFS Product Directory table
- [ ] There is a landing page for Accredited Representation Management that is accessed through the listing on the VFS Product Directory

**Comment by oddball-lindsay** [comment]
Our team has a new name -- Accredited Representation Management.  Updating to reflect the new name.

**Comment by holdenhinkle** [comment]
This is blocked until we merge the FAR app to master. If this needs to be done ASAP, I can be done, otherwise, I'd rather wait.

**Comment by oddball-lindsay** [comment]
Non-technical person here :) when you say "merge the FAR app to master", is that related to launching our MVP?

**Comment by oddball-lindsay** [comment]
This process has been changed and will need to be done manually by someone on the Platform support team.
