### ISSUE TITLE
Design | Profile | Sketch maintenance | Update numbering pattern for states and behaviors, and update desktop pages to display states

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#65177]
## Background
Now that we've updated the user flow on the mobile pages for our Sketch files, we need to figure out what to do with Desktop. 

## Tasks

- [x] Start with a simple to medium complexity level (account security or Personal info might be a good candidate) and update the desktop screens to reflects states instead of repeating the whole page
- [x] Gain alignment with the team
- [x] Complete this across all desktop sections of profile (list below)
- [x] Update the state and behavior numbering to add the `S-` and `B-` prefixes on all sections except contact info (already done)
- [x] Double check links in use case docs

  - [x] Account security
  - [x] Personal info (on this page, we also need to add BAI as a state to the user flow)
  - [x] contact info
  - [x] direct deposit
  - [x] connected apps
  - [x] notification settings
  - [x] edit as a sub task
  - [x] military information
  - [x] Profile hub

**Comment by andaleliz** [comment]
@mtcA6 FYI I created this ticket and would love to work on it in the next sprint to get this all squared away (if there is nothing higher priority, of course)

**Comment by andaleliz** [comment]
I set up a few Sketch files with the way I propose to do desktop - basically showing states, without annotations. This relies on reading the artboard name to understand what it's showing, if it's not obvious, which is essentially what we're doing when things aren't annotated anyway.  Here's why I think this works:
- I reordered the sketch file so mobile is first, which means if someone just opens the file, they'll see the annotations immediately
- Most times, I think people will come to artboards via links that provide context for what they're looking at.
- The artboard name still tells people what's going on.

Could you all take a look at the desktop page of these Sketch files and let me know if you feel this works? 

- [Personal information](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565)
- [Hub landing page](https://www.sketch.com/s/b41a687f-8ab8-4be1-b189-692e5818cffd)
- [Edit as a subtask](https://www.sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d)

**Comment by pamela-drouin** [comment]
I looked at all three. I really like the decision of having mobile user flows show first! Everything makes sense to me. I think the only thing that stands out after seeing a few user flows in a row is the placement of the Annotations box. It's not consistent -- could be good if it is! It's a minor thing though.

**Comment by adamwhitlock1** [comment]
Everything looks great on these files. I think the artboard name is descriptive enough, and for desktop we are really concerned with content and layout differences between mobile, and this works perfectly for that. I can click into each file if I need to for accessing the inspector, and it should work wonderfully.

One minor thing I noticed on the personal info desktop canvas was that there was this random extra tidbit
![Screenshot 2023-09-18 at 11 50 21 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/7ebef629-c371-4709-8925-a227bd7bdbbe)

Upon closer inspection its for a prescription refill alert
![Screenshot 2023-09-18 at 11 50 31 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/290b4a96-6c29-4972-8184-457a5d158e43)

😄

**Comment by andaleliz** [comment]
All complete. Thanks to all for your feedback!
