### ISSUE TITLE
Discovery: Link to Gravesite Locator 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#6518]
## User Story or Problem Statement
As a Veteran, I need access to the Gravesite Locator so that I can search for the burial locations of veterans and/or family members. 

**Backstory:** From the legacy directory, there is a link to the Gravesite Locator. To reach paroity with the directory before sunsetting, we need to replace that navigation to the Locator. 

![image](https://user-images.githubusercontent.com/55411834/75915819-0bdef100-5e0c-11ea-9e2c-3fbe976c6e94.png)

## Goal
Veterans have a pathway to the Gravesite Locator from the Facility Locator

## Objectives or Key Results this is meant to further
OBJECTIVE 2: Deliver meaningful facility information 
---
## Tasks
- [ ] Determine best way to link to Gravesite Locator from Facility Locator. 
      - Could this be done by connecting to the Gravesite Locator through the NCA Facility Detail Pages?
      - Will Veterans know what Cemetery they should search when looking for a grave?

## Acceptance Criteria
- [ ] Determination of a workflow for Gravesite Locator navigation from facility Locator
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
