### ISSUE TITLE
Fix unknown errors in Post911GIBillStatus API

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#65182]
## Issue Description
The Post911GIBillStatus API is generating several thousand errors per day as shown in this [Sentry issue](http://sentry.vfs.va.gov/organizations/vsp/issues/6197/?project=3&query=is%3Aunresolved+post911&statsPeriod=14d)

1. The proximate cause is that instantiating `InternalServerError` without an argument of type exception (happening on [this line](https://github.com/department-of-veterans-affairs/vets-api/blob/b8cf1eea0cb75b4c004c31ad6fb5cb58e7c46a26/app/controllers/v0/post911_gi_bill_statuses_controller.rb#L50)) is invalid - thus the ArgumentError in sentry. That should be fixed either by changing the error type to something like BadGatewayError, or by passing an argument to that InternalServerError.

3. That's masking what is more concerning which is that we are getting unknown errors back from EVSS. The [GIBillStatusResponse class](https://github.com/department-of-veterans-affairs/vets-api/blob/b8cf1eea0cb75b4c004c31ad6fb5cb58e7c46a26/lib/evss/gi_bill_status/gi_bill_status_response.rb#L84C13-L84C13) has some error processing but the `error_type` method is returning "unknown" here. 

Probably the best way of diagnosiing is in the `initialize` method, if `success?` is false and `error_type` is unknown, we should immediately generate a log message or sentry event that includes the `status` and `response.body`, so that the error processing logic can be updated - perhaps a new error message or status code was introduced at some point in the last several years. 

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] This controller should no longer be generating ArgumentErrors
- [ ] Whatever response is coming back from EVSS should be handled correctly 
- [ ] A VCR cassette and test case for this error scenario should be added to vets-api

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
