### ISSUE TITLE
[SSO-Login] VSP Product Development Checklist for SSOe

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#6519]
Modified/consolidated this VSP Checklist with items pertinent to SSO: https://github.com/department-of-veterans-affairs/va.gov-team/blob/rroueche-patch-1/platform/working-with-vsp/onboarding/Product%20Development%20Checklist.md

Please also see VSP Collaboration Cycle: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf

Ensuring that we have all applicable checks and sign offs to make sure SSOe is:

**Usable**
- [ ] #6523 Document that usability testing indicates the new changes enable users to do what they need to do
- [ ] #6524 Set up 508 accessibility review
- [ ] #6525 End to end manual QA
- [ ] #6526 End to end UAT with real users
- [ ] #6528 Define availability and latency targets (combined ticket with Monitoring and Dashboard/Alerts)

**Compliant:**
- [ ] #6530 ATO (authority to operate)

**Measurable:**
- [ ] #6533 Create phased release plan according to this template
- [ ] #6528 Set up monitoring (combined ticket)

**Secure**
- [ ] #6534 Request and complete Security review with VSP
- [ ] #6535 Confirm 90% unit test coverage
- [ ] #6536 Complete load testing
- [ ] #6537 Request and complete Staging Review with VSP

**Supportable**
- [ ] #6528 Dashboards and alerts for finding and investigating issues (combined ticket)
- [ ] #6539 Make sure points of contact for new backend dependencies are documented in product outline
- [ ] #6538 Contact centers updates

**Marketable**
- [ ] #6540 Conducted a Go/No Go meeting
