### ISSUE TITLE
Update Tier 1 PR Review Best Practices

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#65207]
## Description 
This ticket outlines updates needed to [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcUtBIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0814ed6b14f5fb329e54d89082852bc7e4b159aa/Screenshot%202023-09-08%20at%2010.18.27%20AM.png)
the PR Review Tier 1 Triage document here: https://vfs.atlassian.net/wiki/spaces/~71202013aea26098a14ec0a4a43cb8bc9a85b4/pages/2663186485/PR+Review+Tier+1+Triage

---

## Definition of Done
Complete all of the tasks below.
---

## Tasks 

- [x] Review this documentation and identify if we should combine it with our newest version: https://vfs.atlassian.net/wiki/spaces/PTST/pages/2510194732/Pull+Request+Code+Review+Procedures
- [x] Add how to find out if a PR is frontend, backend, devops
- [x] Add what stipulations of what makes a request urgent
- [x] Add 24 hour policy best practice
- [x] Review for any other tips and tricks needed and add those

--- 

## Resources & Additional Info 
Screenshot for determining if a PR is frontend, backend, devops
[Uploading... Screenshot 2023-09-08 at 10.18.27 AM.png]

**Comment by bdech** [comment]
[Link](https://vfs.atlassian.net/wiki/spaces/~71202013aea26098a14ec0a4a43cb8bc9a85b4/pages/2663186485/PR+Review+Tier+1+Triage#Identifying-PR-Community-of-Practice) for updated PR Tier 1 Triage
