### ISSUE TITLE
Create SLO Reporting User Guide

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#6521]
## User Story or Problem Statement

As a engineer I need to understand how to interpret SLO dashboard and generate an SLO report. 

## Goal
- Any VSP engineer can successfully download a 14day SLO performance report.
- Any VSP engineer can understand the SLO performance dashboard.

## Objectives or Key Results this is meant to further
- Self-service

## Tasks
- [x] Write a succinct user guide to the SLO report product in [va.gov-team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/request-timing(SLO)/request-timing.md) repo. 

## Acceptance Criteria
- [x] VSP engineer can follow instructions and generate report

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LindseySaari** [comment]
User guide here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/request-timing(SLO)/slo-user-guide.md
