### ISSUE TITLE
Create Platform Support SME Directory

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#65210]
## Description 
There has been a need found during retros and PM meetings for a SME directory. Since this would be most useful to the Platform Support team to know who to reach out for certain products, services, tools, and topics. We will be using this document to perform the work: https://vfs.atlassian.net/wiki/spaces/PTST/pages/2757984320/Platform+Support+SME+Directory

This will be an ongoing task.

---

## Definition of Done
All tasks below are complete.

---

## Tasks 

- [ ] Identify categories for SMEs (i.e. products, services, tools, topics)
- [ ] Create columns in tables outlining necessary information
- [ ] Start backfilling with contacts 

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
A recent meeting noted that we shouldn't have SMEs as individual people, they should be groups like Backend, Frontend and DevOps CoPs. Closing for now.

**Comment by alyssagallion** [comment]
Clint has noted that SMEs should not be individuals but CoPs. So we are going to nix this task.
