### ISSUE TITLE
[QA] 10-10EZ - Reg Only: Review Reg Only documentation

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#65225]
## Background
As we pick up Registration Only work, starting research sessions on 9/13/23, we need to review what we know about the Registration Only pathway, how the scenarios work from a staff perspective and how Veterans can be guided through the process.

The Reg Only pathway is different from enrollment, as the Veteran is not enrolled in VA health care, but can receive care for specific reasons/scenarios.  We may be able to utilize the existing Short Form flow, which may allow us to use the existing code and use cases (modifying for new scenarios).

### Resources
- [Short Form folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/Short%20Form)
- [Reg Only GH folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/Registration)
- [HEC stakeholder meeting notes folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/product/Bi-weekly%20Stakeholder%20Mtg%20notes) (some Reg Only convos may have been captured here)
- Our [Reg Only Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684348883203/49fc4ff1bf31f3cabe200663708c1002645b447f?fromVisitorModal=true&wid=0-1688665713769&outline=open&sender=u5ad49c107baa41137f271007)
- VES [Reg Only Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1692390465914/003e966ee44e0ffff814a0635d8cacaffc42db06?wid=0-1692656922282)

## Tasks
- [ ] Review Short Form flow and testing documentation
- [ ] Familiarize yourself with the information we have gathered so far
- [ ] Review the VES team's information
- [ ] Reach out to the team with any questions
- [ ] Attend at least one Research Session (schedule pinned at the top of DSVA team slack channel or ask Jessica)

## Acceptance Criteria
- Familiarized with Short Form, Registration Only (what we know so far) and how we might incorporate our testing.
