### ISSUE TITLE
Collaboration Cycle for [Pension Benefits Team, Pension 527EZ, Form Reactivation]

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#65250]
### VFS team name

Pension Benefits Team (project was initially started by the Non-Benefits Disability Team)

### Product name

Pension Form 527EZ

### Feature name

Pension Form MVP Reactivation

### GitHub label for product

pension

### Public DSVA Slack channel for VFS team

#benefits-pension

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

August 2023

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

No

### Will your work involve changes to...

Both

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Notify the Collaboration Cycle team of this ticket in your team's public Slack channel.

- [X] I acknowledge that I must notify the Governance team by completing the collab cycle kicckoff workflow in my team's Slack channel after submitting this issue. This can be completed by typing "/collab cycle" and selecting the appropriate workflow.

Kickoff Slack Thread with VFS team: https://dsva.slack.com/archives/C057W3N9K2S/p1694204224496169
</details>

### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- [ ] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [ ] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [ ] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.

**Design Intent artifacts**

See Platform guidance on [Design Intent artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Design Intent meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

- [x] User flow (required): [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695069026901/50b83f710f1cd2f1f7f3bb63553c349ef90d402a?sender=u4e1fb0748c58370c03f33409)
- [x] Whiteboard sketch or other lo-fi prototypes or wireframes: [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u4e1fb0748c58370c03f33409)
- [ ] Research plan (None at this time. The focus is on adding the missing components to the current form and relaunching as quickly as possible with the goal of improving the form over time.)
- [ ] Any other artifacts you have so far
  
##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C057W3N9K2S/p1695313459498219)
- [x] Meeting date/time: **Tuesday, September 26, 2023 at 3:30pm ET**
  
##### Platform actions

* Accessibility
  * [x] Feedback ticket attached
  * [ ] No feedback
* Design
  * [ ] Feedback ticket attached
  * [x] No feedback
* IA
  * [x] Feedback ticket attached
  * [ ] No feedback
* [x] Update this ticket with the Zoom recording
  - [Design intent recording](https://oddball-io.zoom.us/rec/share/Np4VDM7bFt4aJlcYHdujjZW_t1F0UPr2Ou0c-38E8-IABRENM6dndVs8bP-oGLo8.b-8TjQba_KIaZfyl)
  - Passcode: H?wQ*2!%
  
##### VFS actions

- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Sitewide CAIA Intake Request
<details>
  <summary>Toggle Sitewide CAIA Intake Request</summary>

##### VFS actions
- [x] Complete the [Sitewide CAIA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-CAIA-intake-request.2124906551.html)
- [x] Link to the Sitewide CAIA Intake Request ticket below: https://github.com/department-of-veterans-affairs/va.gov-team/issues/66578

</details>

### Midpoint Review

<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [ ] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

**Required artifacts**
- [ ] Design prototype or high-fidelity mockup (must include mobile prototype/mockup)
  - Specify which pages are included in the review
- [ ] Up to date user flow
  - [Guidance on user flows](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/standards/user-flow-guidance.md)
- [ ] If working with [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request), link to CAIA intake ticket. 

**Not required, but nice to have artifacts**
- [ ] Accessibility annotations included as part of your design
- [ ] Research plan
- Links to specific CAIA artifacts:
  - [ ] IA spec
  - [ ] Content source of truth
- Any other artifacts you have so far
 
##### Platform actions
- [ ] Slack thread with VFS team
- [ ] Meeting date/time:

##### Platform actions

* Accessibility
  * [ ] Feedback added to milestone
  * [ ] No feedback
* Content
  * [ ] Feedback added to milestone
  * [ ] No feedback
* Design
  * [ ] Feedback added to milestone
  * [ ] No feedback
* IA
  * [ ] Feedback added to milestone
  * [ ] No feedback
* [ ] Update this ticket with the Zoom recording
  - Recording link
  - Passcode: 
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns

</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [ ] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [x] [Link to the Analytics Implementation and QA Request ticket](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/73162)

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [ ] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [x] [Link to the Contact Center review request ticket](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/73112)

</details>

### Staging Review

<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [ ] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] If this product contains any [experimental design](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [ ] I confirm the environment is available and test users have been provided.
- [ ] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
 
**Staging Review artifacts**

Links to [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts) must be added to this ticket 4 business days ahead of the scheduled meeting. Please do not make changes to the product or artifacts during the 4-day review period. 

**Required artifacts**
- [ ] **URL(s) to review the product**
  - The product should be available on an [approved staging environment](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-environment-guidance-for-vfs-teams). 
  - List pages, sections of pages, and/or user flows impacted by this work.
- [ ] **Drupal or Staging URL for updated primary entry point:** the main way Veterans will access the tool through site navigation (not search)
  - If the primary entry point is not a page on VA.gov, include information about how to view it. Reach out to `@platform-governance-team-members` on Slack with any questions.
- [ ] **Test users and scenarios** (when applicable)
  - Store [test user information](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md), passwords, and tasks in a .md file in the va.gov-team-sensitive repository. 
  - Make sure all user scenarios can be tested, i.e.: in-progress form, submitted form, new form.
- [ ] **Link to Sitewide CAIA intake ticket**, if applicable.
- [ ] **Completed accessibility testing artifact:** see [instructions and link to accessibility testing template](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).
- [ ] **QA Artifacts:** artifacts that correspond to each of the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
  - [ ] Regression test plan
  - [ ] Test plan
  - [ ] Coverage for References
  - [ ] Summary (Defects) reports
  - [ ] E2E tests
  - [ ] Code coverage
  - [ ] Endpoint monitoring playbook
  - [ ] Logging silent failures

**Not required, but nice to have artifacts**
- [ ] **Content source of truth:** link to CAIA Content feedback, such as a content source of truth.
- [ ] **Information Architecture spec:** link to CAIA IA feedback, such as an IA spec.
  
##### Platform actions
- [ ] Slack thread with VFS team
- [ ] Meeting date/time:

##### Platform actions

- [ ] Update this ticket with the Zoom recording
  - Recording link 
  - Password:
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
- [ ] [Complete Collaboration Cycle feedback survey](https://ows.io/qs/gb1dfnkl)

</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [ ] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [ ] Link to the Readiness Review ticket below

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by vbellissimo** [comment]
@shiragoodman who should we give document access to? For the artifacts I'm linking to? Should I just provide access to each member of your team for every artifact that requires it?

**Comment by shiragoodman** [comment]
@vbellissimo yes, all our reviewers will require access to your artifacts. Is there a specific artifact you're referring to? Our team members can be found on Platform Website under [Governance team.](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/contact-us#Contactus-Governance)

**Comment by vbellissimo** [comment]
Thanks @shiragoodman. We have an assortment of Google sheets that needed to be shared with your team that I link to from the body of the ticket here. I just added your team members to them to prevent access issues. If you do have any questions or issues, please let me know. Thank you.
