### ISSUE TITLE
 Design | Profile | MHV Notification Migration | Update Use Case Docs Once launched

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#65272]
## Background
Once we've deployed the updates to production we have to update our use case docs to reflect the correct content 

## Tasks 
- [ ] Update use case documentation 
- [ ] Review w/PM and PO 

## Acceptance Criteria 
- [ ] documentation is updated

**Comment by mtcA6** [comment]
the notification settings page documents each of the notifications and lists the channela nd if it's live in production or not
