### ISSUE TITLE
PM | Profile | MHV Notification Settings | Coordinate Label Updates

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#65270]
## Background
Now that we have confirmed the content for the MHV notifications, we need to coordinate updates w/VA Profile 

## Tasks 
- [x] share the updated mocks ( [desktop example](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/AZnL7Wx) and here's [mobile](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/vRLvAZ1). ) with VA Profile ([slack thread](https://dsva.slack.com/archives/C7TE0PFTL/p1694442147374789))
- [x] discuss next steps on the VA Profile/MHV call on 9/13

## Acceptance Criteria
- [ ] VA Profile is ready to pick up the work.

**Comment by mtcA6** [comment]
@Samara-Strauss lost sight of this, how did VA Profile want us to communicate the label updates? Was the end result we need to submit a jira intake ticket?

**Comment by Samara-Strauss** [comment]
I sent an email with the VA Profile updates to Mike (cc'd our team, Carnetta, and Bev) on 9/13. Idk if this is always how they want us to do this, but it seemed to be OK for now.

A few notes:

1. I think we only need to submit Jira tickets for things that require actual build changes. Since this is a copy change which can be implemented quickly, we didn't need to submit a Jira ticket.
2. For future copy updates, they like to have approval from relevant stakeholders (eg. MHV and Carnetta in this case) as well as VANotify. So that's why I cc'd everyone on that email.
3. Next time we need VA Profile to make a copy update, let's ask how they want us to communicate that to them so there's not a confusion issue like this time. I'm sorry that happened in the first place. It wasn't your fault.
