### ISSUE TITLE
BE | Profile | Discovery: Display scheduled maintenance message

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#65277]
## Background
During planned system outages, veterans experience errors or inconsistencies when using Profile features.

We do have some capabilities of informing veterans when parts of our system our down.  The purpose of this ticket is investigate these capabilities and determine what needs to be done to display a maintenance message during these windows.

For example, it would be nice to display an error message stating that "Due to scheduled maintenance, areas of the Profile may not be fully functional between Sat, Sept 9th - Sun, Sept 10th" instead of just having parts of the page not working properly.

## Tasks
- [x] Get access to PagerDuty
- [x] Investigate how this is currently working in VA.gov.
     - [x] [outage window process doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/OnCall/outage-window-process.md)
- [x] Document the findings

## Acceptance Criteria
- [x] Review with Team to determine next steps

**Comment by tpharrison** [comment]
Opened support ticket to request access to PagerDuty - https://dsva.slack.com/archives/CBU0KDSB1/p1702312086205119.

**Comment by tpharrison** [comment]
@adamwhitlock1 Can we discuss this further next week?  I think this will require some FE work, but I'm not sure.

**Comment by tpharrison** [comment]
Encountered some access-related issues - https://dsva.slack.com/archives/CBU0KDSB1/p1703007035914719.

**Comment by tpharrison** [comment]
@mtcA6
I was granted access to add maintenance windows in Pager Duty.  Pager Duty has a list of services that correspond to an external APIs (VA Profile, BGS, EVSS, etc.).  When a service has an outage, we add a maintenance window to the service.

I tested the `Staging: External: Vet360` Pager Duty service.  The following message was displayed for Contact Info and Personal Info in staging...

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/653787/12454fe7-6324-4f7a-a860-4e5630c4b19c)

Next steps...
- Determine which existing services we can use and if we need to create any additional ones.
- Create BE and FE tickets to add services and display appropriate message in Profile for each.
