### ISSUE TITLE
Align On New Content Orientation Roles

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#65284]
## Info
Staffing updates:
- Product manager is transitioning out and new PM starting Oct 11
- Torri leaving team; Backfill is Rebecca Ferguson

With the current staffing updates, team members need to align on how to split up orientation roles for the next orientation.

Ps. The next orientation is still not scheduled. See the backlog column for names of people to onboard next.

[Link to orientation guide](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2481651920/Platform+Content+Team+Orientation+Agenda+Reminder+List)

---

## Tasks

- [x] Decide orientation speaking roles:
- without the product manager (to give them time to onboard)
- with 3 team members (Lauren, Brian, Jill)
- [x] Update our internal orientation guide document: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2481651920/Platform+Content+Team+Orientation+Agenda+Reminder+List

## Acceptance Criteria

- [ ] The team will know how to conduct the next content orientation after September, 2023

**Comment by vbellissimo** [comment]
One team member is out for the remainder of the sprint. There are a lot of staffing changes happening to the team in the near future. This card is going to be de-prioritized so we can complete it as a group.

**Comment by johnny-jesensky-adhoc** [comment]
Team roles have been assigned for our next orientation (targeting November 14, 2023). Tentative speaking parts are as follows:

@Jill Taylor - 1, 2, 3,
@Lauren Conrad - 4, 5, 6
@Brian Smolensky - 7, 8, 9
