### ISSUE TITLE
[UX] Evaluate and update wireframe for no upcoming appts scenario

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#65286]
## Description

We recently added an accordion to all appt list pages to let Veteran's know that all of their upcoming appts might not appear in this list. Example:

https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/002582CE-7CC7-479C-89BF-374A2C3E3931/canvas

However, we have a scenario that we need to solve for now, which is, what should the Veteran see if they select a link from a text message, the link is expired, AND they have no upcoming appts. The problem is that the accordion (above) communicates what a Veteran can do, which is go to Appointments on VA.gov to review their other appointments. However, it's in an accordion that likely won't be viewed. 

Previously, we came up with this solution to solve for this scenario: https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/g10RlnM

Now, we need to make sure that that featured content under the Upcoming Appointments heading is still appropritate, given that we changed the accordion content a couple times with Laura's input. For example, should it be the same content as the accordion? Slightly different content? Or, another option? 

## Tasks

- [ ] Review the two artboards currently for [pre check in](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/v8V43G8) and [check in](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/g10RlnM) 
- [ ] Determine what the content should be for the featured content block under the Upcoming Appointments heading
- [ ] Create those two wireframes in a feature page in the unified check in sketch file
- [ ] Determine if Laura needs to review. E.g., she might not given that she's already approved and reviewed the accordion content. 
- [ ] Once all set, make those changes to the two artboards in the Design page within unified check in sketch file and check/update artboards in Design - Priority 4 page too to see if those need to be updated as well. 

## AC

- [ ] Updated content is written for the featured content area below the Upcoming Appointments heading 
- [ ] Wireframes are updated in the unified check in sketch file

**Comment by kellysmith1008** [comment]
@ytsaoca On a related ticket, I noticed that [VAOS uses the following alert](https://www.figma.com/file/twogqAIoOL9WAFRqvUbwiS/VAOS-Templates?type=design&node-id=2037-34346&mode=design&t=CgnUowPU6kBlYjJf-0) when there are no upcoming appointments. We'd need to rework some of the content as they can't schedule in our app, but I thought at least we could keep the same title for the alert? I feel like we should be consistent across platforms but can be persuaded otherwise:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbDdNIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--905e94f7bd305b9aa875a2676f40e2f275f85c92/image.png)

**Comment by cgednalske** [comment]
@kellysmith1008 came across your comment and have to jump in 🙂 I noticed this as well in the call retrieval error ticket I'm working on! Totally agree looking at this for consistency make sense.

Maybe some additional reasons to look into this: It's not technically not an alert (featured content), so VAOS probably has a better approach by omitting "we're sorry." Also, the other alerts I'm working on for the call failure errors (also based on VAOS) will have "we're sorry" somewhere and likely need more differentiation from this.
@benbrasso-agile6 should we create a ticket for this?

<img width="409" alt="Screenshot 2023-09-25 at 9 44 54 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/79372956/a1af4346-fa36-4b92-8a84-f0961a9932cb">

**Comment by benbrasso-agile6** [comment]
Let's talk about it at UX Sync, because I'm not sure I'm following all the way. 

Also, keep in mind we'll have scenarios like these, that have an alert at the top of the page. What are the guidelines around the default alerts specific to placement on page and how many per page? 

[Selected check in link for appt in the past with no upcoming appts](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/g10RlnM) 

[Selected a pre check in link for appts in the past with no upcoming appts](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/v8V43G8)

**Comment by benbrasso-agile6** [comment]
I don't see any specific guidelines about number of alerts per page upon quick scan. But, I did see that position on the page can vary, which is cool https://design.va.gov/components/alert#alert

**Comment by cgednalske** [comment]
@benbrasso-agile6 ya I was thinking through this as well with the error alerts (back when I thought it was something else 😄). I think that our heading structure is nicely set up now so that the alerts can live within the sections they pertain to and avoid stacking 🎉

**Comment by benbrasso-agile6** [comment]
Yeah, agreed

**Comment by kellysmith1008** [comment]
@ytsaoca Starting work on this content today - should have it ready for you by tomorrow at the latest

**Comment by ytsaoca** [comment]
Wireframe for review: https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/v/wYopyD/a/ZVg2wpv
@benbrasso-agile6

**Comment by benbrasso-agile6** [comment]
LGTM (with Kelly's edit). Nice work all. 

@cgednalske this jibes with your MAP error tickets. So, yeah, good job everyone. 

Feel free to tackle the last task in this ticket: 

> Once all set, make those changes to the two artboards in the Design page within unified check in sketch file and check/update artboards in Design - Priority 4 page too to see if those need to be updated as well.

**Comment by ytsaoca** [comment]
@benbrasso-agile6  Updated the design page. 
About the Design - Priority 4 page, I didn't find no upcoming appts scenario for either check-in or pre-check-in. Do I add that 2 pages or there is no need to update in Design - Priority 4 page?

**Comment by benbrasso-agile6** [comment]
@ytsaoca so, maybe go ahead and add an artboard to the end of each row of boards (pre check in in person, pre check in phone, etc.) that has that "no upcoming appts" featured component in it. So, it's basically copying the first artboard from each row, deleting all the appts, and then adding your featured content component under the Upcoming Appts h2. Does that make sense? If not, I can do one to demonstrate. How's that sound?  

<img width="849" alt="Screenshot 2023-10-02 at 12 57 22 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/101129355/b0d3753d-dc15-43f2-af92-be48029fed44">

**Comment by ytsaoca** [comment]
Hi @benbrasso-agile6 ,
I created  "no upcoming appts" featured component for each row. Please take a look.
Just the last one is somehow strange for me. Do we keen "What to do next" and the white card or delete them?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcFAzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c124f81a79baf4a65886aabcb574edc6e89c7169/Screenshot%202023-10-02%20at%201.53.00%20PM.png)

**Comment by ytsaoca** [comment]
Hi @benbrasso-agile6 ,
I created  "no upcoming appts" featured component for each row. Please take a look.
Just the last one is somehow strange for me. Do we keen "What to do next" and the white card or delete them?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcFAzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c124f81a79baf4a65886aabcb574edc6e89c7169/Screenshot%202023-10-02%20at%201.53.00%20PM.png)

**Comment by benbrasso-agile6** [comment]
We can keep them. That scenario will be very, very unlikely. But, I think everything looks good. Nice job!
