### ISSUE TITLE
GTM Submission Event Tracking - 21-10210 & 21P

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#65282]
## Issue Description
We have/had requests for 2 new forms dashboards that need to have the submission event tracking configured in GTM (similar to what was just completed for Form 21-4142) 

21-10210 Lay/Witness Statement 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBamFIIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--07f4ab0f73ef412b6dfa19394682e91f1e0e7346/image.png)

21P-0847 Substitute Claimant Form 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFNIIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a8a9258304dfb9caf8f27b0019c95fb442bbf5b9/image.png)

---
## Tasks
- [ ] Configure GTM tracking for 21-10210 & 21P-0847
- [ ] Test configuration for each

## Acceptance Criteria
- [ ] Submission tracking is configured and tested.
---

**Comment by jestutt** [comment]
@michelle-dooley 

21P-0847 Substitute Claimant Form confirmed in staging
![Screenshot 2023-09-26 at 4 19 28 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/d7c61846-fb4a-4b61-8194-a89fe5e4417a)


21-10210 Lay/Witness Statement confirmed in production
![Screenshot 2023-09-26 at 4 18 11 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/c6e0c9a4-1cf2-4f11-9f76-760e3e3bc49d)
