### ISSUE TITLE
Update Product Guides based on Feedback

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#65298]
## Background
We got some feedback from Angie Wills and have been asked by our VA PO to make the changes below.

## Tasks
Make the following changes to the Product Guide:
- [x] Noticed in the Patient.Check-in product guide that the poster screenshot is not the latest version of the poster as piloted by VISN 6.
- [x] Mobile phone is used in the document, shouldn’t it state smartphone?
- Overview section:
    -  [x] In the bulleted steps to complete check-in: It is missing the step of checking in
    -  [x] Travel reimbursement claim – Since this functionality is not rolled out nationally to all facilities, I suggest including a note indicating this functionality is available at selected/pilot sites.
    -  [x] Figure 4: Please update to include (*Required) after name
-  [x] Please review all figures to ensure none of the information can be considered PII/PHI.

 

 

Thanks.

 

From: Wilt, Angie R. <Angela.Wilt@va.gov>

**Comment by kellysmith1008** [comment]
Verified a few things for this ticket:
In terms of PII/PHI, I verified with Brian that any screenshots taken from staging or a local instance are free of any PII or PHI, so we're good there (and I'll update the documentation for the product guides to give explicit instructions from where to take the screenshots)
There will be a frontend ticket coming out of this work as some of our chip warnings reference "mobile" instead of smartphone. I'll create that ticket when I'm finished with both product guides.

**Comment by kellysmith1008** [comment]
Product guides are updated with these suggestions. Will publish later today. @loripusey, would you like me to reach out to Angela directly to let her know we've updated them?

**Comment by kellysmith1008** [comment]
Perfect - thank you! Just sent out the email. I'll leave this ticket open throughout today just in case other suggestions come back from that email, but then I'll close it EOB today.

**Comment by kellysmith1008** [comment]
Received feedback that the poster update didn't take - not sure why, but will swap out the poster and then this is complete
