### ISSUE TITLE
IA competitive analysis of secondary navigation solutions

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#65308]
## User Story
As an IA working on VA.gov, I want to do a competitive analysis of other secondary navigation structures and solutions within authenticated portals, so that I can get a sense of other solutions to inform the design of secondary navigation for the integrated VA.gov health portal. 

Assignee: @sterkenburgsara 

## Description
Following on the work of ticket #65055 (Document IA problems with sidenav component & needs for an integrated secondary nav), we will document the secondary side navigation solutions.  

## Impacted Artifacts
* Competitive Analysis [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1694530015144/bb1ff2600f6e417f2c58abe793f158119aaac44a?sender=uf94a77a19aaf687331c09367)

## Tasks
- [x] Conduct competitive analysis
- [x] Document images and description of the navigation solutions found in other auth portals on the web [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1694530015144/bb1ff2600f6e417f2c58abe793f158119aaac44a?sender=uf94a77a19aaf687331c09367)
  - [x] include pros/cons
- [x] Bucket all auth portal nav solutions according to similarities, and prepare to demo the differences to the Cartography team during Sprint demo

## Acceptance Criteria
- [x] We have a sense of secondary navigation patterns that are common for common / large scale authenticated user portals on the web. 
- [x] Create follow-on tickets to continue working toward a better solution for integrated secondary navigation across MHV on VA.gov tools

**Comment by fmccaf1** [comment]
I added myself for ease of finding this ticket later

**Comment by sterkenburgsara** [comment]
cc @coultonbunney-usds @Jenny-yw
