### ISSUE TITLE
MVP: Selection (Step 3 of 5)

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#65325]
## Product Outline
[MVP Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/mvp.md)

## High Level User Story/ies
As a user searching for a representative, I need to select a representative that best fits my needs so I can begin the process of appointing Power of Attorney.

## Definition of done
- [ ] When search results are displayed, ([FAR MVP: Display Search Results (Step 2 of 5)](https://app.zenhub.com/workspaces/find-a-rep-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/65322)) each representative result should have a button to "Select" the representative
- [ ] When the user selects a representative, we should carry this information forward and pre-fill a 21-22 form
- [ ] The selection of a representative should be available and functioning on both desktop and mobile
