### ISSUE TITLE
MVP: Display Search Results (Step 2 of 5)

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#65322]
## Product Outline
[MVP Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/mvp.md)

## High Level User Story
As a user searching for a representative, I need to be able to understand what types of representatives are in my area so I can choose the best fit for my needs.

## Hypothesis or Bet
**If** _our search results have clear indicators of the representative type, include important representative information, and are easily referenced in a map_, **then** _users will be able to select a representative that best fits their needs with regards to location and representative type._

## Definition of done
- [ ] The search results page should include both an interactive map view and a list of results within the map, sorted from closest to furthest
- [ ] If the user is logged in, consider displaying the veteran's existing representative
- [ ] The search results page should be available and functioning on both desktop and mobile
