### ISSUE TITLE
Synthesize Medallia Feedback

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#65331]
## Task Description
Explore ways to synthesize Medallia Feedback

## Notes and References
-
## Acceptance Criteria
- [x] Working within Excel, put all of the spreadsheets into one spreadsheet for Q3
- [x] Begin to analyze data. Count how many 1,2,3,4,5 we get for rating and general trust. 

## Deliverables
- 

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by melissa-lefevre** [comment]
I have started looking into how to best synthesize this. I am working with a researcher to learn what a good approach might be. So far it has been manually counting the quantitative. I will see how it goes for Q3 but it seems like there has to be a better way.

**Comment by melissa-lefevre** [comment]
I finished this and sent it out to the team.
