### ISSUE TITLE
[FSR] Add additional catch for gmt threshold fetch

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#65334]
## Issue Description
We need to add additional catch when fetching gmt data to confirm that the `gmtThreshold` is a valid number. 
There is currently just an error thrown when we receive a invalid response, or error message from the gmt api, but we also need to confirm that the threshold is a number so we can log an appropriate error message. 

Example of a bad response we received:
```
   // inside gmtData object
    "gmtThreshold": {},
    "error": null,
```
If we receive an invalid value like above, we should set the gmt error message accordingly, so we can track bad responses and more easily identify why the veteran was sent down the full fsr path. Let's also take the time to check for this error when performing other gmt related calculations, so we can ensure consistent results. 

---
## Tasks
- [ ] Validate gmt threshold value is a number, and update error message accordingly
- [ ] Identify other locations where we can check the error message to avoid necessary calculations. (this may be non actionable. 

## Acceptance Criteria
- [ ] `gmtData` contains appropriate error messaging if bad data is received. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
@HeatherRienks / @Tom-Davis 
Closing this ticket out since we were able to implement [this change in my last PR](https://github.com/department-of-veterans-affairs/vets-website/pull/25947/files#diff-defc41dfdc1fc70b3e22a752c5828f92913c6c2c0c8e60a71c0691eccd8932e8R27-R30) for the ticket [#66245](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/66245)
