### ISSUE TITLE
[Epic] Form 20-10206 - FOIA Request

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#65348]
## About your team

- Team name: 
-	OCTO-DE product owner: Matthew Dingee
- Product manager:  Tricia Baker
-	Designer: Rachel Shearer
- Accessibility specialist: Jeana Clark
- Content writer: 
-	Slack channel:
 
### Describe what you need in a few sentences:
 - We are digitizing form 20-1026
</br>
</br>

#### Examples
- We’re updating a form and want to confirm we’re doing it correctly.
- We’re launching a new online tool to VA.gov and need support with our user flows.
- We need to make sure the content we’re using in our tool is written in plain language and follows the style guide.

### Which are you doing?
- [x] **Launching a new** page, tool, form, or app
- [ ] **Making changes** to an existing page, tool, form, or app

### Types of Support
What areas does your team need support in? Check all that apply.
#### Content
- [x] Collaboration on content written by your team’s dedicated content writer 
- [ ] Collaboration on content if your team does not have a dedicated content writer
#### Accessibility
- [ ] Accessibility review of wireframes and/or prototypes
- [ ] Accessibility issue (general request)
- [ ] Accessibility PDF review request
- [ ] Accessibility user research support ([submit a separate, additional request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name))
- [ ] DST component or pattern 
- [ ] Something else 
#### IA
- [x] User Flows
- [x] Page placement
- [x] URLs
- [x] Breadcrumbs and Left Nav placement
- [ ] Redirects
#### Multilingual content
- [ ] Translating content
 
## Timeframe
_We guide and work alongside teams across nearly every OCTO digital product. We also work with partners across VA to lead content migration and manage all unauthenticated content on VA.gov. And we're always working to expand the VA.gov content style guide and our IA and accessibility documentation. We need to prioritize all intake requests based on our overall workload and VA and OCTO priorities._

_Tell us about your product's timeline. And we'll work with you to meet timeline needs as best we can._

### Have you worked with CAIA before? 
  - [x] Yes
  - [ ] No

### What's your team’s next step and its timing?

- **Our next step is** ....
- **Provide date if available**: xx/xx/xxxx

#### Timing for your next step: 
  - [x] Next week
  - [ ] This month
  - [ ] Next month
  - [ ] This quarter
  - [ ] Next quarter
  - [ ] 6 months
  - [ ] 1 year

### Is this timing related to a specific event or Congressionally mandated deadline?
  - [ ] Yes
  - [ ] No

### If you're conducting research, when is that starting? 
**Provide date if available:** xx/xx/xxxx
  - [ ] Next week
  - [ ] This month
  - [ ] Next month
  - [ ] This quarter
  - [ ] Next quarter
  - [ ] 6 months
  - [ ] 1 year

### Will you release this new product incrementally (for example, release to 25% of users to start)? 
  - [x] Yes
  - [ ] No
 
**Note**: _If you checked yes, we’ll reach out to discuss details about the content in the react widget (we use these widgets to display entry points for new products to a certain percentage of users who visit our static pages)._

  
### When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
- **We expect to launch our product to 100% of users on:** xx/xx/xxxx
  
### Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

### If no ...
- Skip to the _supporting artifacts_ section, below.
 
#### Please provide the link to your Collaboration Cycle ticket: 
- **Ticket (number)**: 
- **Collab. Cycle Ticket Opened (date)**: xx/xx/xxxx
 
#### Please check all of the phases in the Collaboration Cycle you have completed: 
- [ ] Design Intent
- [ ] Midpoint Review
- [ ] Staging
 
##### Design Intent
- [ ] Accessibility
- [x] Content
- [x] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
##### Midpoint
- [ ] Accessibility
- [x] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
##### Staging
- [ ] Accessibility
- [x] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
  
## Supporting artifacts
*Please provide links to supporting artifacts as available.*
- **Product outline**: [outline](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/20-10206%20FOIA%20PA%20Request/Product%20Outline.md)
- **User flows**: [User flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1694111229625/784141f7f136fcd481b4010e5ec0ca961434e5fe?sender=u2dd1818fc590a5b2e62f8183)
- **Prototype or mockups**: [Sketch](https://www.sketch.com/s/314e6dbf-5b4a-422d-beb1-0ad599fc3af1)
- **If this is in Sketch, which version or specific page should we focus on?**
- **Content source of truth**: [Source of Truth](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/20-10206%20FOIA%20PA%20Request/source-of-truth.md)
- **Research plan:**
- **Any epics/issues that may be helpful**: [Github background & Stakeholder questions](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/20-10206%20FOIA%20PA%20Request/ia-sitewide.md)
- **Link to testing accounts** (please do not paste them in this ticket): 

### Have you already worked with someone from OCTO leadership?
- [x] Danielle
- [ ] Beth
- [ ] Mikki
- [ ] Martha

### How do you plan to work with us on this request?
- [ ] I’ll take this to Beth or Danielle’s office hours.
- [ ] I’d like to schedule time to talk about this.
- [x] Let’s work async and meet as needed.
- [ ] Schedule a kick-off call with your team and CAIA for your project **(Recommended)**

 
### Accessibility Help in Slack
The [#accessibility-help channel](https://dsva.slack.com/archives/C8E985R32) in the DSVA Slack, is also available to you as a resource. Everyone is welcome to ask questions or get help from our a11y (accessibility) specialists. Tag `@Terry Nichols` to get a11y help asap.

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag `@Terry Nichols`.**

- If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
- If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)
 
 - If you are creating an [experimental design,](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) please [also contact the DST. ](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)

- If you are requesting [a11y support for user research,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name) please complete this form, next. 

```[tasklist]
### Content tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/66593
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/68930
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/75266
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/72998
```

```[tasklist]
### IA tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/66281
```

**Comment by jennymayoco** [comment]
Hi @tbaker1026 @rachelshearerux, here is the [IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/form-digitization-20-10206.md#nav) with some of the entry points we have proposed for the this form. We are recommending this form lives in the Records hub with entry points on the hub page and left nav. When someone clicks on it, it will take them directly into the form flow. As mentioned during our sync, @megzehn and I plan to do a Drupal audit that includes this form so the entry points listed in the IA spec may not be exhaustive yet. The spec isn't finalized yet with a confirmed URL, but we have documented breadcrumb path. Let me know if there's any questions! Happy to chat some more.

**Comment by tbaker1026** [comment]
@jennymayoco Do we have the final URL and breadcrumbs for this form?

**Comment by jennymayoco** [comment]
Hi @tbaker1026 @rachelshearerux @megzehn - here is the [finalized IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/form-digitization-20-10206.md). We also added additional guidance for redirects and best bets in the future. Let me know if there's any questions!

**Comment by jennymayoco** [comment]
Hi @tbaker1026 @rachelshearerux , @megzehn and I have added an entry point for this form in the Supporting Forms page and this has been documented in the [IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/form-digitization-20-10206.md). This update is so that we can add a react widget to a static page since the entry point for this form goes directly into the flow. The true home will still be in Records so this doesn't impact URL or breadcrumbs. Let me know if there are any questions!

**Comment by tbaker1026** [comment]
@jennymayoco @megzehn We will first add it to the Supporting Forms page with the react widget on and only add it to the other pages once we are 100% live with the form - right?

**Comment by megzehn** [comment]
Yes, exactly, @tbaker1026

**Comment by scjwalker** [comment]
I confirmed with @tbaker1026 that the form is 100% live, so we can add the additional entry points now.
I've reviewed all planned entry points in [the IA Spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/form-digitization-20-10206.md), and summarized the needed work at the top of the spec. There's two types of work here:
- Entry points 1 and 2 are core navigation, and need to be added to meet the IA definition of done.
- There are many places in va.gov that could link to this form. Entry points 4, 6, and 7 were identified in the IA Spec when Jenny originally created it, and have not yet been added. But it would be great to defer to Content for any modifications/additions of entry points, since va.gov has grown a bit since this work was planned.
