### ISSUE TITLE
Create user flow to show transitions between products when a user begins a subtask

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#65349]
# User story: 
As a designer, I want to create user flows that account for all the paths that users could take when entering a health portal subtask experience, so that I have a full understanding of the journeys and places we need to account for when making routing decisions following sub-task completion.

## Description: 
**Note**: More contextual detail about this work is available in the epic

## Questions:
  * What if users come to a subtask from within a different health tool (i.e. they click a cross-link from care summaries and notes to schedule a new appointment, sending them directly into that flow)? What are the options of where we could send them once they complete that flow?
  * What if users come to the subtask from a cross-link outside of the `/my-health` realm (elsewhere on VA.gov)? What current cross-links would be affected? 

## Tasks:
- [ ] Create user flows to document the different paths a user would take based on where we route them after they complete subtasks:
  * Users who start on the product that the subtask(s) belong to - they can stay where they are
  * Users who begin on a different product than the subtask(s) belong to - do they get routed back to where they were before after completing that form flow? Or do we keep them in the new product area? 
  * Users who begin outside of the health portal - do they get routed back where they were before? Or do we keep them in the new product area? 
  * Users who begin outside of the health portal and click a link to subtask that falls under a health tool they do not have access to
  * Consider whether any scenarios are missing from this list 
- [ ] Link audit on VA.gov (unauth) for links to the subtasks we are aware of today: 
  * scheduling an appointment directly with a facility (only possible for some facilities)
  * requesting a new appointment with a facility
  * cancelling an upcoming appointment
  * sending a secure message

## Acceptance Criteria
- [ ] We understand the various flows that are possible within the health portal experience based on different routing decisions
- [ ] We understand where and how users coming from outside the health portal experience may interact with links to subtasks and what happens in those instances
- [ ] We are prepared to discuss pros and cons of different approaches

**Comment by sterkenburgsara** [comment]
<img width="288" alt="Screenshot 2023-10-27 at 11 29 11 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/115033532/3553f905-623d-4e8b-a399-d6c2a9933208">

**Comment by wesrowe** [comment]
@sterkenburgsara, I noticed that you surfaced this story in the backlog (new labels, etc). Please add any detail that would help the team grasp what this work entails, if you have it.

**Comment by sterkenburgsara** [comment]
@wesrowe will do! I don't think it's incredibly pressing at the moment, but will be important to consider when things are tied to VA.gov and transitions between tools becomes a thing.

**Comment by wesrowe** [comment]
no op
