### ISSUE TITLE
Step 2 of 3: Accessibility study [planning]

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#65359]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

Step 2 of 3 steps/issues for planning and preparation.

The UX team is planning to run a dedicated accessibility study to understand the usability of the streamlined waiver experience by Veterans who use screen readers. The planning will happen in Sprint 107, and the study will begin in Sprint 108. The UX team will work with an accessibility specialist at VA.gov to help refine the conversation guide with AT-friendly language. The goal is to run the study with 5 participants that use AT.
---
## Tasks
- [ ] _What work is necessary for this story to be completed?_
- [x] UX Research conducts a screen reader accessibility audit of Streamlined Waiver
- [x]  UX Research adapts research plan
- [x]  UX Research adapts conversation guide
- [x]  UX Research posts materials on Github
- [x]  UX Research obtains platform collaboration research cycle approval (2-3 days)
- [x]  UX Research writes AT specific recruitment screener
- [x] Create note taking spreadsheet and Mural 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
- [x] Accessibility audit report 
- [x] AT specific recruitment screener
- [x] Study plan
- [x] Conversation guide
- [x] Platform collaboration research cycle approval
- [x] Note taking spreadsheet and Mural created

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by charlottecesana** [comment]
Update 9/30/23 - approval is pending once the test staging user(s) have been created. Shane will approve the research once we have the staging user(s). Everything else has been finalized on our end. @HeatherRienks @Tom-Davis @denisecoveyduc @mgleo @ScottyRJames

**Comment by HeatherRienks** [comment]
Per SP on 10/10, we are awaiting completion of test user account and we can then secure approval/schedule a meeting  with Perigean to launch study.
