### ISSUE TITLE
[SW] Remove extra copy from transition page

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#65365]
## Issue Description
Remove the extra **Next Steps** list on the transition page so it's more clear. This is based on [findings from the SW Usability study](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/streamlined_waiver/research/research-findings.md#key-findings).

---
## Tasks
- [x] Remove **Next Steps** list on transition page 
- [x] Update Sketch/UXpin
- [x] Update code and create PR

## Acceptance Criteria
- [x] Sketch/UXPin updated 
- [ ] PR has been merged 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by josephrlee** [comment]
@HeatherRienks , created the ticket. I can pull this into this Sprint and have it done by tmw. 

cc: @Tom-Davis
