### ISSUE TITLE
STEP 3 of 3: Pilot Session

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#65362]
## Issue Description

The UX team is planning to run a dedicated accessibility study to understand the usability of the streamlined waiver experience by Veterans that use screen readers. The planning will happen in Sprint 107, and the study will begin in Sprint 108. The UX team will work with an accessibility specialist at VA.gov to help refine the conversation guide with AT-friendly language. The goal is to run the study with 5 participants that use AT.

## Tasks
What work is necessary for this story to be completed?
- [ ]  Host a pilot session 
- [ ]  Make any updates to the conversation guide as needed based on pilot session
- [ ]  Coordinate with Perigean (1 week) 
- [ ]  UX Research coordinates with an accessibility specialist who can be present at each study interview

## Acceptance Criteria
What will be created or happen as a result of this story?
- [ ] Pilot session has taken place
- [ ] Updates made to conversation guide (if needed)
- [ ] Perigean secures participant recruits
- [ ] AT specialist attendance is confirmed for each session
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
This is complete- session with Angela Fowler on 10/3/23.
