### ISSUE TITLE
IPP Discovery - Veteran creates/logs into my Login.gov IAL1 account

### ISSUE THREAD

**Issue by porta-antiporta** [department-of-veterans-affairs/va.gov-team#65367]
# Use Case

As a Veteran who goes directly to the IPP application, I am asked to create or login to my Login.gov IAL1 account so that I can enroll in IPP

# Context

This is an enablement story.

From #65300, we now have a hello world application in front of which we want to put IAL1 authentication form Login.gov. What this does is it will mimic receiving a UUID and email from Login.gov that we will use to bind to a case ID for registering for IPP.

By doing so, we aren't bound to having our application being called by Login.gov with UUID and email from their in person proofing flow.

There are two ways to achieve this:

1. Integrated directly with Login.gov's sandbox environment. Instructions on how to do so are at their [developer site](https://developer.login.gov). In order to create a team on their [integration dashboard](https://dashboard.identitysandbox.gov), all we need is a .gov email.

Given that Login.gov will be the entity launching our proofing app for intake, I feel that option 1 would be closer to the actual interface that Login.gov would use (i.e. I think we'd have to validate the signature of the assertion from Login.gov using their public cert.  But open to either if 2 is a much easier mechanism.

Now at a later time, we will need to authenticate the proofing agent. Option 2 would be what we'd use for authenticating  the proofing agent _if SiS will support a flag to authenticate via PIV only_.

# Nominal Flow
1. User is in our "Hello World" app from #65300
2. A sign in button will be added to that app
3. When user clicks on sign in, it launches the user into signing in/creating an IAL1 account in Login.gov's dev (idp.int.identitysandbox.gov) environment.
4. User creates an IAL1 account or signs into IAL1 account.
5. Login.gov dev redirects authenticated user to our application where
6. We will validate the assertion from Login.gov (i.e. signed correctly using their public cert)
7. We will receive the UUID / email of the authenticated user
8. We will persist that UUID / email on our app so that we can use it to bind to a Case ID (future story).

# Acceptance criteria
- [x] Integrated either Login.gov or SiS to our Hello World app in dev
- [x] After an authenticated user is sent to our application, we are saving both the UUID and email of the authenticated user

DEF OF DONE
- [x] create data flow diagram
- [x] connected to login.gov sandbox env
- [x] understanding of blockers documented
- [ ] demonstrating (via Postman) that we can hit the api and make a call via vets-api (vets-api may be tomorrow)

**Comment by porta-antiporta** [comment]
From refinement 
- include detailed steps that should be included (both from a Veteran/user and backend).
- preconditions
- clarify Veteran vs. proofing agent views/screens
- is the ability to save data already available in the Hello world story

**Comment by porta-antiporta** [comment]
@porta-antiporta to get access to the integration channel for Login.gov

**Comment by porta-antiporta** [comment]
I was able to create a team and application configuration entry for us in Login.gov's [onfiguration dashboard](https://dashboard.int.identitysandbox.gov). When time comes for this story, ping me and I can show you how to get around.

**Comment by porta-antiporta** [comment]
This is the [GH repo](https://github.com/18F/identity-oidc-sinatra) of the [sample application](https://int-identity-oidc-sinatra.app.cloud.gov/) that we demo'd. Could be used as a reference we can pull from for our integration.

**Comment by mateoclarke** [comment]
<img width="892" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHhkQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--07c1ee7c443777e3e9a6e85969e17206a6236a6e/Screenshot%202024-02-14%20at%2012.37.29%E2%80%AFPM.png" alt="Screenshot 2024-02-14 at 12.37.29 PM.png" />

**Comment by lmorris3** [comment]
@mateoclarke looks like all stories in this epic are complete. Good to close it?

**Comment by mateoclarke** [comment]
Sounds good, closing now...
