### ISSUE TITLE
Review of Login.gov Adoption Team Call Center Support Document

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#65371]
## Issue Description
The Login.gov adoption team has created a call center support document and are looking for feedback to make sure what they have included is clear. Chante has reviewed an earlier version but it would be great to have @starlow00 review it as well. 

---
## Tasks
- [ ] @starlow00 review call center support document from login.gov adoption team
- [ ] Send back feedback to the login.gov adoption team

## Acceptance Criteria
- [ ] A document with feedback from the Veteran Support Team
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
@starlow00 here is the document for review. 
[Login.gov Adoption Guidance & FAQs v2.0.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFdPIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8b1be03b1ec2e9cd09e33ae4a1050ddf5977409a/Login.gov%20Adoption%20Guidance%20%26%20FAQs%20v2.0.docx)

**Comment by clantosswett** [comment]
@starlow00 I just received new versions of the document I shared here previously. Please review this over the earlier one.

[Login.gov Adoption Guidance & FAQs (1).docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaTJlIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c6d862e50c7eccb80ea2bb0a1abf4f2ff3688374/Login.gov%20Adoption%20Guidance%20%26%20FAQs%20%281%29.docx)

**Comment by starlow00** [comment]
On track to complete this sprint, will share review with Chante.

**Comment by starlow00** [comment]
For reference, I will be reviewing this draft:[Uploading... Login.gov Adoption Guidance & FAQs V3.docx]

**Comment by starlow00** [comment]
[Login.gov Adoption Guidance & FAQs V3.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdHF0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3dbc7ef90e6eaaf05fc41446f394582134679d21/Login.gov%20Adoption%20Guidance%20%26%20FAQs%20V3.docx)

**Comment by starlow00** [comment]
Reviewing v3, just released by Login.gov team today. Will update when review is complete.
[Login.gov Adoption Guidance & FAQs V3.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdCt0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2aac42f8be37cb590088654ed8a5f18a665700c4/Login.gov%20Adoption%20Guidance%20%26%20FAQs%20V3.docx)

**Comment by starlow00** [comment]
Sending attached v3 draft to Login.gov team. A few questions are highlighted in the document for their review when they finalize the material.

[Login.gov Adoption Guidance & FAQs V3 SRT 09182023.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12667129/Login.gov.Adoption.Guidance.FAQs.V3.SRT.09182023.docx)
