### ISSUE TITLE
Review Login.gov Adoption Team Call Center Support Document

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#65370]
## Issue Description
The Login.gov adoption team has created a call center support document. Chante has done an initial review but it has been updates since then so I would like @starlow00 to review and provide and any feedback in the document that can be relayed back to the Login.gov adoption team. 

[Login.gov Adoption Guidance & FAQs v2.0.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanlPIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7b491a5412a80a57ba2ae6b9a153fd90abd46041/Login.gov%20Adoption%20Guidance%20%26%20FAQs%20v2.0.docx)
---
## Tasks
- [ ] Review document and provide comments and feedback
- [ ] Provide to Chante 

## Acceptance Criteria
- [ ] Document is reviewed and comments and feedback are returned back to the Login.gov adoption team

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
Closing this issue because I somehow created a duplicate of it.
