### ISSUE TITLE
[BE/FE] 10-10EZ - Improvement: Update schema to send abbreviation for Mexico provinces

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#65373]
## Background
While monitoring the increased traffic on the 10-10EZ application during the closing of the special enrollment period (Sept 2023), an investigation activity was done on a submission that ultimately failed all retries.  
It was determined that the reason for the failure was due to the Home Address including a province of Mexico, and the value being sent to Enrollment System was the full value (spelled out name) of the province.  We should be sending the common abbreviation for the Mexico provinces.

**Note**: Foreign country provinces/regions outside of Mexico, Canada and US are received as they are entered.  There is no abbreviation needed for those provinces or regions.

After some additional review during PR approvals, it was found that the forms library has a hard-coded country/region/province schema that cannot be updated.
We have determined that we can keep the FE schema as-is, no changes to the spelled-out province names.  We can update the backend to accept the fully spelled-out province name and map it to the abbreviation, passing that abbreviation to the Enrollment system.

<details>
<Summary>Expand for Slack conversation</Summary>

>**Heather Justice**
>@ patrick - Update on Mexico province issue
>We initially thought it would be a simple schema change. However, the forms library has a hard-coded country/region/province schema and it cannot be >updated
>Our options are:
>
>1. Build our own custom library to manage the Mexico provinces, which would require additional maintenance when needed (will take about a week or so >to implement & test)
>2. Keep the FE schema as-is, and update the Backend to accept the full named province, and pass the mapped abbreviation so ES can accept it. (will take >about a week to implement & test) **[SELECTED OPTION]**
>3. Convince ES to make the change that matches everything else
>
>In short, we will not be able to have a solution in place for these last few days of the PACT Act enrollment.  The silver lining is that ES is able to route >those applications to manual processing.
>
>**Heather Justice**
>I am recommending option 2, as it is the quickest and least disruptive (thanks @ Matt Long for the words!)
>
>**Patrick Bateman**
>thanks for the analysis and recommendation. totally good with # 2.

</details>

### Resources

- [10-10EZ JSON](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/dist/10-10EZ-schema.json#L66)

### Mexico Provinces Abbreviation List (Confirmed with Joshua Faulkner)
    { label: 'Aguascalientes', value: 'AGS.' },
    { label: 'Baja California Norte', value: 'B.C.' },
    { label: 'Baja California Sur', value: 'B.C.S.' },
    { label: 'Campeche', value: 'CAM.' },
    { label: 'Chiapas', value: 'CHIS.' },
    { label: 'Chihuahua', value: 'CHIH.' },
    { label: 'Coahuila', value: 'COAH.' },
    { label: 'Colima', value: 'COL.' },
    { label: 'Distrito Federal', value: 'D.F.' },
    { label: 'Durango', value: 'DGO.' },
    { label: 'Guanajuato', value: 'GTO.' },
    { label: 'Guerrero', value: 'GRO.' },
    { label: 'Hidalgo', value: 'HGO.' },
    { label: 'Jalisco', value: 'JAL.' },
    { label: 'México', value: 'MEX.' },
    { label: 'Michoacán', value: 'MICH.' },
    { label: 'Morelos', value: 'MOR.' },
    { label: 'Nayarit', value: 'NAY.' },
    { label: 'Nuevo León', value: 'N.L.' },
    { label: 'Oaxaca', value: 'OAX.' },
    { label: 'Puebla', value: 'PUE.' },
    { label: 'Querétaro', value: 'QRO.' },
    { label: 'Quintana Roo', value: 'Q.ROO.' },
    { label: 'San Luis Potosí', value: 'S.L.P.' },
    { label: 'Sinaloa', value: 'SIN.' },
    { label: 'Sonora', value: 'SON.' },
    { label: 'Tabasco', value: 'TAB.' },
    { label: 'Tamaulipas', value: 'TAMPS.' },
    { label: 'Tlaxcala', value: 'TLAX.' },
    { label: 'Veracruz', value: 'VER.' },
    { label: 'Yucatán', value: 'YUC.' },
    { label: 'Zacatecas', value: 'ZAC.' },

## Tasks
- [ ] Revert FE back to the original state, using spelled-out province names
- [ ] Update backend to map the spelled-out province names to the corresponding abbreviations
     - Abbreviations will be sent with form data, instead of spelled-out province names
- [ ] Complete a few test submissions using different Mexico provinces and confirm with Joshua Faulkner that it was received successfully
     - Including Oaxaca province (one of the failures in September)
- [ ] Release to production

## Acceptance Criteria
- The schema is updated to pass on postal code abbreviations for Mexico provinces, so that application submissions no longer fail due to the value being the full name and not accepted by the Enrollment System

**Comment by longmd** [comment]
@hdjustice , do the codes need to include the periods? We don't have those for any other code.

**Comment by hdjustice** [comment]
@longmd - Yes, these codes, for Mexico only, require the periods.  Joshua F confirmed that as well

**Comment by hdjustice** [comment]
@jadon1979 - Let's check in when you get back online on this item.  The direction has changed.
