### ISSUE TITLE
Update QA operational guidance and QA findings template

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#65388]
## User Story
As a Governance QA specialist, I want to ensure that the guidance I follow for completing a QA review at the Staging Review touchpoint is updated with accurate and up-to-date information so that I can complete a consistent review each time.

As a VFS team member, I want to know that the feedback I get from QA at Staging Review is clear and accurate so that I can take appropriate action for addressing issues. 

Assignee: @it-harrison 
Peer Reviewer: @CherylEvans 

## Description
The unit test coverage percentage and severity is changing. We need to ensure that the operational guidance our QA specialist follows to complete a Staging Review (aka "How to complete a QA review for SR touchpoint") is up to date and accurately reflects the process that is followed. 

The QA Collab Cycle Findings for Staging gh template should also be reviewed and updated to ensure it aligns with the new unit test coverage standard. In addition, the "Platform Directions" that live in the QA findings gh template should instead be incorporated into the How to complete a QA review for SR touchpoint document. All Platform directions in the gh template should be removed. 

**Note from Shira:** the How to complete a QA review for the Staging review touchpoint guidance should really include specific information on how to complete testing and validation for each QA standard, including actions to take if a standard is not met (ie add `launch-blocking` label). Right now, you have to look at the instructions in the gh ticket AND the instructions in the confluence page to understand the full process. 

## Impacted Artifacts
[How to complete a QA review for the Staging review touchpoint](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2428010558/How+to+complete+a+QA+review+for+the+Staging+review+touchpoint)
[QA Collab Cycle Findings for Staging](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-feedback%2C+QA%2C+Staging%2C+qa-standards&projects=&template=collab-cycle-qa-findings-staging.md&title=QA+Standards+-+VFS+Team+-+VFS+Product) gh template

## Tasks
- [x] Create a documentation draft for the How to complete a QA review for the Staging review touchpoint page and a pull request for the changes to the QA Collab Cycle Findings for Staging gh template
- [x] Ensure guidance for unit test coverage includes the new 80% number and instructions for adding the launch-blocking label when applicable.
- [x] Ensure guidance for the E2E testing includes instructions for adding the launch-blocking label when applicable
- [x] Ensure any additional notes, comments etc. for the VFS team is documented in the "Explanation of failure to meet standard (if applicable):" for each applicable standard

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance teams QA Specialist has up to date and correct guidance to follow when completing a QA review for Staging Review
- [x] VFS teams do not see any Platform directions in completed QA Collab Cycle Findings for Staging gh tickets
- [x] VFS teams can get the information they need to know from the completed QA Collab Cycle Findings for Staging gh ticket

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
@shiragoodman @CherylEvans A [draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2772008961/Copy+of+How+to+complete+a+QA+review+for+the+Staging+review+touchpoint) of the changes is ready for review. I don't see any changes that need to be made to the QA Collab Cycle Findings for Staging gh template.

**Comment by CherylEvans** [comment]
@it-harrison The draft you put together must include instructions on completing the QA Standards GitHub ticket. 
The "Platform Directions" listed in the GitHub ticket should instead be in the QA Operational guidance document. 
If you have any questions or need an explanation on correctly addressing each task, please tag @shiragoodman

**Comment by it-harrison** [comment]
@CherylEvans @shiragoodman [updated draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2772008961/Copy+of+How+to+complete+a+QA+review+for+the+Staging+review+touchpoint) to take into account Cheryl's feedback.

**Comment by CherylEvans** [comment]
@it-harrison Hi Ian. I finished reviewing your draft and made small edits based on voice and tone. I also made changes to punctuation and grammar. It looks great! :-)

**Comment by it-harrison** [comment]
all tasks complete; closing
