### ISSUE TITLE
Draft change history post and Slack announcement

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#65387]
## User Story
As a Governance team member, I want to make sure changes to the Collaboration Cycle process are communicated effectively so that there is no confusion for VFS teams.

Assignee: @briandeconinck 
Peer Reviewer: @it-harrison 

## Description
We need to communicate to VFS teams, following the proper channels, that the QA Standard for unit test coverage has changed. 

## Impacted Artifacts
[Change history post](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2779578386/65387+-+Unit+test+coverage+change+history+announcement#Change-history)
[Slack announcement](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2779578386/65387+-+Unit+test+coverage+change+history+announcement#Slack-announcement)

## Tasks
- [x] Draft a change history post communicating what the change is and when it will be enforced at Staging Review (we'll begin enforcing 2 weeks after announcing to VFS teams - confirm with Shira)
   - [Draft change history post](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2779578386/65387+-+Unit+test+coverage+change+history+announcement#Change-history)
- [x] Draft Slack announcement for #vfs-change-announcements channel following Platform Communication Playbook
   - [Draft Slack announcement](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2779578386/65387+-+Unit+test+coverage+change+history+announcement#Slack-announcement) 
- [x] Notify Shira so she can share in Team of Teams
- [x] Once changes approved by Peer Reviewer, publish changes to Platform Website, including:
   - Change history post
   - QA Standards page (per ticket #64916)
 - [x] Once we've published to Platform Website, post the Slack announcement to #vfs-change-announcements, linking the change history post. X-share in #vfs-all-teams

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] VFS teams have been notified of the change in the unit test coverage QA standard
- [ ] VFS teams are aware of when the change to the unit test coverage QA standard will be enforced

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
@it-harrison and @shiragoodman, announcement drafts are linked below. Tried to keep it short and simple, only things missing are the dates. Let me know what changes might be needed, and how/when to proceed with publishing!

- [Change history post](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2779578386/65387+-+Unit+test+coverage+change+history+announcement#Change-history)
- [Slack announcement](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2779578386/65387+-+Unit+test+coverage+change+history+announcement#Slack-announcement)

**Comment by it-harrison** [comment]
@briandeconinck looks good!

**Comment by briandeconinck** [comment]
Carrying over to the next sprint for publishing tasks, but all of the real work is complete.

**Comment by shiragoodman** [comment]
@briandeconinck @it-harrison we should be ready to launch. If we can get the change announcement and Slack post pushed today or tomorrow, we can begin enforcing the changes to the unit test coverage QA standard by Thursday 10/12. 

Please confirm that you both have read this message. LMK if you have any questions/concerns.

**Comment by briandeconinck** [comment]
@shiragoodman @it-harrison Change history post and QA standards page are queued up for publishing to Platform website. I've also updated the date in the Slack announcement and updated the link to the change history post, so that should all be ready to go!

**Comment by shiragoodman** [comment]
Slack announcement posted this morning. This ticket can be closed.
