### ISSUE TITLE
Add state metadata to Form5655Submission

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#65397]
## Issue Description
As far as I know we don't make any meaningful record when a submission fails. Given the importance of these submissions processing correctly, we should be able to tell at a glance if a submission failed to actually submit. 

---
## Tasks
- [x] Add a 'state' field to Form5655Submission
- [x] Add an 'error' field to Form5655Submission
- [x] set state to "in progress" when creating submission
- [ ] use state field to record when a submission succeeds or fails to actually submit
- [ ] record any relevant errors in error field

## Acceptance Criteria
- [ ] It should be reasonably guaranteed that a submission will record success or failure state after it has been created.
