### ISSUE TITLE
UX Research process refinement (research operations)

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#65399]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

Refining the process for the UX Research practice.
2 Goals: 
1) Infuse early testing research in the product cycle
2) Create a simple repository of studies and findings that are actionable and can help inform the roadmap
---
## Tasks
 _What work is necessary for this story to be completed?_
- [ ] Create a new process for UX Research
- [ ] Socialize the new process
- [x] Repository spreadsheet

## Acceptance Criteria
 _What will be created or happen as a result of this story?_
- [ ] A new UXR process document
- [ ] Socialization within team
- [x] [Repository created](https://docs.google.com/spreadsheets/d/1JMWQS4CbSgPrOTcBEe-Qn6gp9mTbz4z_TvbVvfhhkmU/edit?usp=sharing)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mgleo** [comment]
Research spreadsheet link: [https://docs.google.com/spreadsheets/d/1JMWQS4CbSgPrOTcBEe-Qn6gp9mTbz4z_TvbVvfhhkmU/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1JMWQS4CbSgPrOTcBEe-Qn6gp9mTbz4z_TvbVvfhhkmU/edit?usp=sharing)
