### ISSUE TITLE
FE | Editing-as-a -subtask | Conditional H1 Content

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#65407]
## Issue Description
Through [QA testing we discovered a bug](https://docs.google.com/spreadsheets/d/1-oSUr_kFqyptbSI6jRC3O7wqk3TNDOwaWedmO3eh7FA/edit#gid=1459792507&range=P7). 

The h1 on the editing as a subtask page should say "Add your mobile number" instead of "add or update" 

The h1 should reflect whatever the user is doing. Add if null, update if there is already a value. 

## Front end tasks
- Update heading so that it reads Add or Update depending on what data is present for a user's field

## Acceptance Criteria
- [x] The heading is dynamic and shows appropriately 
- [x] Unit tests pass
- [x] E2E tests cover current code and regression
- [x] End-to-end tests show 0 violations.

**Comment by adamwhitlock1** [comment]
@mtcA6 and @Samara-Strauss This is ready to validate in staging. Here are some of the screenshots of the state for when a user has the data present when they do not.

DATA NOT PRESENT
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbC9kIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5a43e28c04ae18a6a4f608be534e99c46300f1f9/Screenshot%202023-09-26%20at%205.21.55%20PM.png)

DATA PRESENT
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbURkIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--de6994bae675a3d8cd98c683ffac8c71d724bcd3/Screenshot%202023-09-26%20at%205.21.12%20PM.png)

**Comment by mtcA6** [comment]
Tested w user 202, looks good!
