### ISSUE TITLE
Pension Reactivation | In-Progress Applications

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#65404]
## Issue Description
_How should we handle claims that are still in-progress at the time of reactivation?_

**Info**
- Claims in progress data is saved on backend. Tying that data to a Veteran can be challenging.

---
## Tasks
- [ ] Determine how to verify if a user has submitted a claim.
- [ ] Determine a solution for in-progress applications (e.g., migrate data to new form).
- [ ] Determine which pages should announce reactivation.
- [ ] Determine how users with in-progress claims should be notified (e.g., via email)

## Acceptance Criteria
- [ ] Workflow of solution
- [ ] Sketch file of solution
- [ ] Any necessary follow-on tickets
---
