### ISSUE TITLE
FE | Authenticated Menu | Fix GA event naming

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#65406]
## Background 

We need to update the one data layer event that is missing for the auth menu: `MyHealtheVet` 

<details><summary>For original specifics see our GA Ticket for Auth Menu</summary>

https://github.com/department-of-veterans-affairs/va.gov-team/issues/64617#issuecomment-1716027182
@mtcA6  When I check today, the only drop-down link missing a data layer event is "My HealtheVet". 

The event should look like the ones in the below screenshot with the "nav-user-section" collecting "my-health" or "my-healthevet". 

![Screenshot 2023-09-12 at 12 03 42 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/f89d3a3e-e23c-438e-a82b-8136e2616260)

</details> 

## Tasks 
- [x] add the correct data layer event (fixed in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/25773))
- [ ] correct the naming ( the event says `MyHealth` and should read `My HealtheVet`)

## Acceptance Criteria 
- [ ] Once updated, [the GA board for this should be updated with the correct naming](https://analytics.google.com/analytics/web/#/dashboard/jTwco5hFRBmuXcjZN9YSPA/a50123418w177519031p176188361/)

**Comment by adamwhitlock1** [comment]
This actually has been updated already by Alexander Garcia a week ago in this PR which uses the onlick to send `my-health` as the event:

https://github.com/department-of-veterans-affairs/vets-website/pull/25773

We can close this out as duplicate.

**Comment by mtcA6** [comment]
Problem is I think it still says `MyHealth` and should read `My HealtheVet` instead of just 'My Health'

**Comment by adamwhitlock1** [comment]
ok ill have to revaluate the ticket then and see about changing that over in the next sprint.

**Comment by adamwhitlock1** [comment]
@Dottifacilities @Samara-Strauss @mtcA6 

The event has been updated to be as follows:

```
{
 event: 'nav-user',
 'nav-user-section': 'my-healthevet'
}
```

To validate, these events should start showing up in GA within the next 24 hours within the authenticated menu dashboard/reports. If they don't then we may need to circle back with the analytics folks to verify that the event is mapped to google tag manager correctly.

**Comment by Samara-Strauss** [comment]
Sounds good! I'll keep an eye out for this in the GA dashboard.

**Comment by adamwhitlock1** [comment]
@Samara-Strauss I will close this out as it looks like we are seeing the event triggered as expected. Here is the slack convo for reference:

https://dsva.slack.com/archives/C909ZG2BB/p1696944828761549
