### ISSUE TITLE
Burial Reactivation | In-Progress Applications

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#65405]
## Issue Description
_How should we handle claims that are still in-progress at the time of reactivation?_

---
## Tasks
- [x] Determine how to verify if a user has submitted a claim.
- [x] Determine a solution for in-progress applications (e.g., migrate data to new form).
- [x] Determine which pages should announce reactivation.
- [x] Determine how users with in-progress claims should be notified (e.g., via email)

## Acceptance Criteria
- [x] Workflow of solution
- [x] Sketch file of solution
- [ ] Any necessary follow-on tickets
---

**Comment by fiorella-io** [comment]
Created flow: [Reactivation flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1696625213786/c43bb9381b9e7f235b822264d89ee338465813ba?sender=u4e1fb0748c58370c03f33409)

**Comment by steele-lm** [comment]
Closing this as the burial form will not be deactivated.
