### ISSUE TITLE
[Research] Create Research Study Report

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#65424]
## Related Documentation
- [MVP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- [Research plan and Conversation Guide]()
- Synthesis for this report completed in [ticket]().

## Description
A research report detailing findings and design recommendations from [research study name].

## Reference Materials
- Platform [research process](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html) and [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)
- [Synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/research/synthesis)

## Tasks
- [x] Create research reports/readout documents of findings. 2 versions needed (Presentation and GitHUB Markup). Use this [report template](https://dsva.slack.com/archives/C0NGDDXME/p1629381608108300) and [GitHub Markup template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/sharing-research/research-findings-template.md)
- [x] Conduct the [inclusive design analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/research/risk-documentation.md)

## Acceptance Criteria
- [x] Post research report to GitHub as presentation and markup document
- [x] Update the [research repo](https://github.com/department-of-veterans-affairs/va.gov-research-repository/wiki/Guidelines).
- [ ] Create necessary issues/tickets that address findings in coordination with Corey and Julie
- Schedule readout sessions with
    - [x] Stakeholders (talk to Patrick about when to do this)
    - [x] Team (either via Slack or Zoom meeting)
    - [ ] [Monday design/research sync](https://depo-platform-documentation.scrollhelp.site/research-design/Weekly-Design-+-Content-+-Research-Sync-Meeting.1938423884.html) (message Naomi Marcussen to get on the schedule)

**Comment by cgednalske** [comment]
@loripusey a heads up that we'll need to carry this one over

**Comment by cgednalske** [comment]
@loripusey Ben reminded me that this is not so helpful without a reason 🤦‍♀️  Apologies for not including that! I fired this off quickly before signing off in my brain fog yesterday. 

We're finishing up making some of the recommendations more direct/specific, so just need more time to shore that up and finish adding the info to the slide deck. Being sick this week hasn't helped 😞, but it's getting close.

**Comment by benbrasso-agile6** [comment]
👍  And, I had moved it into next sprint's goals a day or two ago too, fyi

**Comment by benbrasso-agile6** [comment]
@loripusey once @cgednalske closes this ticket, I think this Epic can be marked as completed. I.e., Kristen asked us to hand off to the BT team to handle next steps. Could circle back around to us in the future.

**Comment by cgednalske** [comment]
Findings synthesis and report have been added to our research folder and [research repo ticket](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/442), and the study has also been added to our team's research table. Think this is good to close out!

**Comment by benbrasso-agile6** [comment]
Do it! Epic can close to I think.
