### ISSUE TITLE
[Design, FE] 10-10EZ - Adding an info/warning message to static page and Intro page

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#65436]
## Background
In preparation of the final week or so before the PACT Act 9/30 enrollment deadline, we want to see what it would take to add a flipper controlled info/warning box to the static page **https://www.va.gov/health-care/how-to-apply/** somewhere around the "Apply for health care" green button.   We would also like to look at putting this alert on the Intro page as well (https://www.va.gov/health-care/apply/application/introduction)

We may be able to [create a widget](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-react-widget) that is pulled into the pages.

## Tasks
- [x] Determine the feasibility of getting a flipper controlled info/warning message displayed on the static page
     - https://www.va.gov/health-care/how-to-apply/ and https://www.va.gov/health-care/apply/application/introduction
- [x] Work with Danielle Thierry & team to create/validate content of the message
- [x] Assist with getting this implemented on the static and Intro pages
- [x] Complete testing to ensure the control is functional
- [x] Validate with PM/PO prior to releasing to production
 
## Acceptance Criteria
- A controlled warning info message can be displayed on the static How to Apply page and the Intro page when we are alerted of system latency or issues that may cause slowness or timeouts for Veterans completing the 10-10EZ application

**Comment by longmd** [comment]
@hdjustice , the content update to remove that link is in staging and will go out with the daily today.
