### ISSUE TITLE
[Design, FE] 10-10EZ - Adding a info/warning message on the application

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#65441]
## Background
In preparation of the final week or so before the PACT Act 9/30 enrollment deadline, we have implemented a flipper controlled info/warning box to the static page **https://www.va.gov/health-care/how-to-apply/** somewhere around the "Apply for health care" green button by creating a widget that is pulled into the static page.

We want to determine whether this is feasible and appropriate to do without the application itself, rather than on the preceding static page.

## Tasks
- [ ] Determine if a flipper-controlled warning info message is **appropriate** to display on the application
- [ ] Determine **feasibility** of getting a flipper controlled info/warning message displayed on the application, and where it should be located (intro page, top of each page, etc)
- [ ] Determine the **level of effort** to implement this flipper controlled info/warning message 
- [ ] Discuss with PM/PO
 
## Acceptance Criteria
- A recommendation of whether a flipper controlled info/warning message should be displayed or not, and whether the LOE is worth the impact to Veterans.
