### ISSUE TITLE
Identity Dashboard (FE) - Add Direct Deposit view to Monitoring

### ISSUE THREAD

**Issue by ianmagenta** [department-of-veterans-affairs/va.gov-team#65445]
## Description
Create a frontend page for the new direct deposit endpoint that's been added to the identity backend.

## Tasks
- [x] Create a display for direct deposit info
  - [x] Add a `monitoring/direct-deposits` page
  - [x] Query the DD endpoint via react query
  - [x] Style query results in a table similar to how logs are done on the Monitoring page
- [x] Update the Log Search component to better utilize times
