### ISSUE TITLE
Implement the "Find a Rep" Widget for Production Deployment

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#65455]
**Issue Description:** 
Now that we have a user-testing prototype of the "Find a Rep" widget, it's time to develop the production-ready version. We already have the designs, the text, and user feedback from the prototype. Let's create a fully functional widget for deployment. 

Remember, ensure that the call to the Lighthouse API is non-blocking.

**Tasks:** 
- [ ] Integrate the Lighthouse endpoint for fetching user's rep data.
- [ ] Refactor and enhance the widget's layout based on the design and feedback from user-testing.
- [ ] Implement dynamic text functionality as per provided copy, ensuring it remains flexible.
- [ ] Ensure the widget can be seamlessly embedded on any va.gov page.
- [ ] Test on multiple pages and for different user states.
- [ ] Ensure all functionalities meet accessibility standards.

**Acceptance Criteria:** 
- [ ] The "Find a Rep" widget is fully functional, rigorously tested, and is deployment-ready.

**Comment by oddball-lindsay** [comment]
This ticket is too general, will create more specific issues in the [ARM: Representative Status Widget v1 (MVP) epic](https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/65453)
