### ISSUE TITLE
Keenan Schouten onboarding

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#65450]
## Issue Description
Keenan Schouten has joined the team and will need to onboard to the platform and our work.

---
## Tasks
- [x] Complete corporate onboarding tasks
- [x] Complete VA Platform onboarding tasks

## Acceptance Criteria
- [x] Onboarding tasks have been completed
