### ISSUE TITLE
Write Copy For Widget

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#65454]
## Issue Description
Craft the dynamic and static text content for the "Find a Rep" widget ensuring clarity, conciseness, and alignment with va.gov's tone and style.

---
## Tasks
- [ ] Understand the different contexts and user states for the widget.
- [ ] Write copy for authenticated users, detailing representative information.
- [ ] Write copy for non-authenticated users with a general message.
- [ ] Ensure copy is adaptive based on the benefits page the widget is on.

## Acceptance Criteria
- [ ] All text content for the widget is clear, concise, and approved.
