### ISSUE TITLE
Update orientation templates to remove roster 

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#65460]
## User Story
As a Platform team member supporting Platform Orientation, I want to update the Product Atlas with new VFS team member information so that the Atlas an be the source of truth for individuals supporting VA.gov.

Assignee: @briandeconinck 
Peer Reviewer: @CherylEvans 

## Description
Platform Product team (fka Tech Team 1) has created a new app called [Atlas](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2760671235/Product+Outline+Atlas+WIP) that helps them identify which team owns which code in vets-api. The team recognized that their product could replace many existing Platform services and products, such as the VFS Team Roster. The VFS Team Roster is currently a Google Sheet spreadsheet that hold all of the names, titles, emails, etc. of VFS team members supporting VA.gov. It is used so Platform is aware and able to track who is using Platform products. 

Since one of the features of Atlas includes the capture of individual and team level information, Platform crew agreed that Atlas could replace the VFS Team Roster.

VFS teams and individuals are added to the VFS Team Roster via the Platform Orientation process. As the Product team prepares to launch Atlas, the Platform Orientation gh tickets will need to be updated to remove references to the VFS Team Roster.

## Impacted Artifacts
New VFS Team gh issue ticket
New VFS Team Member gh issue ticket

## Tasks
- [x] Create pull request
   - [PR #65750](https://github.com/department-of-veterans-affairs/va.gov-team/pull/65750)
- [x] Edit line items in the Platform Checklist to remove references to the VFS Team Roster and replace with Atlas
   - tldr, VFS teams and team members will now need to be added to Atlas
   - No need to add a link to Atlas at this time. We can edit the PR later on if necessary
- [x] Do not merge PR once approved by peer reviewer

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Platform actions for the New VFS Team Member ticket include adding the individual to the Atlas
- [x] Platform actions for the New VFS Team ticket include adding the team to the Atlas
- [x] Platform actions for the New VFS Team Member ticket no longer include adding the individual to the VFS Team Roster
- [x] Platform actions for the New VFS Team ticket no longer include adding the team to the VFS Team Roster

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@briandeconinck what's the status of this? Can you link the Pull request to this ticket? Thanks.

**Comment by briandeconinck** [comment]
Sorry @shiragoodman! Missed that comment. [PR #65750](https://github.com/department-of-veterans-affairs/va.gov-team/pull/65750) now linked in the ticket.

I think this is ready for review @CherylEvans

**Comment by CherylEvans** [comment]
@briandeconinck I reviewed and approved [PR 65750](https://github.com/department-of-veterans-affairs/va.gov-team/pull/65750) Thank you, Brian! :-)
