### ISSUE TITLE
Retire VFS Team Roster

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#65461]
## User Story
As a Platform team member, I want to retire the VFS Team Roster so that we can begin using Atlas in it's place.

Assignee:
Peer Reviewer:

## Description
Atlas will soon replace the VFS Team Roster as the new source of truth for VFS teams and VFS Team members. The purpose of this ticket is to identify the necessary tasks for officially retiring the VFS Team Roster and drafting a change announcement for Slack. We will coordinate with Platform Product team when completing actions to retire the VFS Team Roster and posting the change announcement. 

VFS Team Roster will be retired on Monday 10/2/2023. All Platform Website changes should be published prior to the Thursday 3:30pm ET content publish due date.

## Tasks
- [ ] Identify all of the places on Platform Website where the "VFS Team Roster" or "VFS Roster" is specified. List all urls below:
   - _urls listed here_
- [ ] Of the above URLs determine which can simply be updated to replace "VFS Team Roster" with "Atlas" and which pages require more work. Update with "Atlas" pages"
   - [ ] _urls listed here_
- [ ] Require more work:
   - [ ] _urls listed here_
- [ ] Add note to both tabs of VFS Team Roster spreadsheet, ideally in first row, in big, bold letters specifying that the VFS Team Roster has been retired as of 10/6/2023. Direct VFS teams to new Atlas page on Platform Website.
- [ ] Draft a change announcement for #vfs-change-announcements Slack channel, following the Platform Communication Playbook, detailing that the VFS Team Roster is being retired and will be replaced by Atlas.
   - Note: Platform Product team will draft a change announcement communicating the launch of Atlas. Governance team and Platform Product team will coordinate posting of their change announcements so the VFS Team Roster retirement post can point to the Atlas launch post. 

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have identified all VFS-facing documentation and guidance that references the VFS Team Roster 
- [ ] We have either updated "VFS" Team Roster" with "Platform Atlas" on Platform Website, or we have created a gh ticket for another team to update the applicable page
- [ ] We have announced that the VFS Team Roster is retired as of 10/2/2023
- [ ] Platform team members no longer update the VFS Team Roster as of 10/2/2023

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by laineymajor** [comment]
I'm adding this to my team's backlog if y'all need assistance running some accuracy checks.

**Comment by shiragoodman** [comment]
@laineymajor I got lazy and instead of rewriting and updating this ticket, I just created ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/72361. #72361 is the ticket we'll use for updating VFS-facing guidance. I will likely close ticket #65461 soon since it's no longer needed!

**Comment by shiragoodman** [comment]
@laineymajor also, the one thing I removed was the change announcement. I figured that since your team is launching Atlas, it makes sense that your team announce it. Does that work for you? Let me know if you'd like to chat about it!

**Comment by jennb33** [comment]
Close this ticket and make a new ticket to announce that we are now using Atlas. @LindseySaari will do the announcement, Jennifer will do the new ticket

**Comment by shiragoodman** [comment]
sounds good @jennb33 ! Just want to make sure you saw[ this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65461#issuecomment-1866333222) so you're aware of the work that's already been completed. Let me know if you have any questions!

**Comment by shiragoodman** [comment]
@jennb33 I'm closing this out! Let me know if you have any questions/concerns. Thanks for seeing this through!
