### ISSUE TITLE
File Extraction

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#65464]
## Issue Description
This issue involves creating the backend logic to automatically read and extract the contents from the files that is updated nightly. The extracted data will serve as the basis for further transformation into a new rep table used for search.

This needs to be a Sidekiq job which runs in prod Sunday, Monday, Tuesday, Wednesday and Thursday nights. It needs to be a Sidekiq job (as opposed to a GitHub Actions job, for example) because the script needs to be run in prod so we can update the database.

Page with downloadable files - https://www.va.gov/ogc/apps/accreditation/index.asp

NOTE: We're working on getting direct access to this data, which may or may not happen. For now, let's proceed with downloading each of these files.

The rep data is broken up in to 4 different downloadable ‘lists’:

- Attorneys
- Claims Agents
- VSO Representatives
- VSOs with Reps

Here’s the table header row (so you can see the attribute names) and the first table data row in each list:
### Attorneys;
```
<TR>
   <td>Last Name</td>
   <td>First Name</td>
   <td>Date Accredited</td>
   <td>Registration Num</td>
   <td>POA Code</td>
   <td>City</td>
   <td>State</td>
   <td>Zip</td>
   <td>Phone</td>
</TR>

<TR>
   <TD>Bohn</TD>
   <TD>Craig</TD>
   <TD>4/15/2022</TD>
   <TD>52221</TD>
   <TD>INV</TD>
   <TD>Seattle </TD>
   <TD>WA</TD>
   <TD>'98178</TD>
   <TD>408-318-0781</TD>
</TR>
```

### Claims Agents:
```
<TR>
   <td>Last Name</td>
   <td>First Name</td>
   <td>Date Accredited</td>
   <td>Registration Num</td>
   <td>POA Code</td>
   <td>City</td>
   <td>State</td>
   <td>Zip</td>
   <td>Phone</td>
</TR>

<TR>
   <TD>Abbott</TD>
   <TD>Drew</TD>
   <TD>11/1/2022</TD>
   <TD>53239</TD>
   <TD>IVW</TD>
   <TD>Providence</TD>
   <TD>RI</TD>
   <TD>'02903</TD>
   <TD>774-287-4117</TD>
</TR>
```

### VSO Representatives:
```
<TR>
   <td>Last Name</td>
   <td>First Name</td>
   <td>Registration Num</td>
   <td>City</td>
   <td>State</td>
   <td>Zip</td>
   <td>Phone</td>
</TR>

<TR>
   <TD>Aaron</TD>
   <TD>Christina</TD>
   <TD>51777</TD>
   <TD>Williamsburg</TD>
   <TD>VA</TD>
   <TD>'23185</TD>
   <TD>757-221-1734</TD>
</TR>
```

### VSOs with Reps:
```
<TR>
   <td>Organization Name</td>
   <td>POA</td>
   <td>Org Phone</td>
   <td>Org City</td>
   <td>Org State</td>
   <td>Representative</td>
   <td>Rep City</td>
   <td>Rep State</td>
   <td>Rep Zip</td>
   <td>Registration Num</td>
</TR>

<TR>
   <TD>--- A-X-P-O-W- *no longer recognized*</TD>
   <TD>'065</TD>
   <TD>817-649-2979</TD>
   <TD>Arlington</TD>
   <TD>TX</TD>
   <TD>Roper, Ramona </TD>
   <TD>Athens</TD>
   <TD>GA</TD>
   <TD>'30606</TD>
   <TD>9416</TD>
</TR>
```

---
## Tasks
- [ ] Create a new Sidekiq scheduled/cron job
- [ ] Review the specifications of the nightly updated files.
- [ ] Implement logic to automatically fetch and read each file.
- [ ] Handle errors such as file not found, permission issues, etc.
- [ ] Log the success or failure of the extraction process to Sentry.

## Acceptance Criteria
- [ ] The system successfully reads the nightly updated file with zero manual intervention.
- [ ] Error handling is implemented to gracefully manage and log any issues related to file reading.

**Comment by oddball-lindsay** [comment]
We've discovered that the work has already been done, this ticket is no longer needed.
