### ISSUE TITLE
Error Handling and Notifications

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#65469]
## Issue Description
This issue is concerned with setting up notifications when errors occur during the nightly automated processes of file extraction, data transformation, or table updates.

Log errors to Sentry. Notifications can be configured in Sentry.

VA Platform Developer Docs - https://depo-platform-documentation.scrollhelp.site/developer-docs/tracking-application-errors-with-sentry

---
## Tasks
- [x] Log errors to Sentry.
- [x] Determine the type of notifications needed (e.g., email, Slack alerts).
- [ ] Configure notifications in Sentry.
- [x] Test notification by simulating errors in a controlled environment.

## Acceptance Criteria
- [x] Notifications are sent when an error occurs in any phase of the nightly job.

**Comment by holdenhinkle** [comment]
Errors are logged to Sentry and notifications are sent to the Lighthouse Slack instance, #api-benefits-claims channel:

```ruby
    rescue Faraday::ConnectionFailed => e
      log_message_to_sentry("OGC connection failed: #{e.message}", :warn)
      log_to_slack('VSO Reloader failed to connect to OGC')
    rescue Common::Client::Errors::ClientError, Common::Exceptions::GatewayTimeout => e
      log_message_to_sentry("VSO Reloading error: #{e.message}", :warn)
      log_to_slack('VSO Reloader job has failed!')
```

Slack:
```ruby
    def log_to_slack(message)
      client = SlackNotify::Client.new(webhook_url: Settings.claims_api.slack.webhook_url,
                                       channel: '#api-benefits-claims',
                                       username: 'VSOReloader')
      client.notify(message)
    end
```

**Comment by oddball-lindsay** [comment]
We've discovered that the work has already been done, this ticket is no longer needed.
