### ISSUE TITLE
[FE] Update Content in the Needs Help Section to the Default on All Pre-Check-in and Check-in Pages

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#65479]
## Background
As part of the Unified Check-in design/discovery, it was determined that we need changes to the Needs Help section to reduce Veteran confusion and provide as much information as possible to help the Veteran.
 
## Wireframes
[Priority 8 wireframes](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/6ECDF941-DF3B-4C1E-983D-1BA221ACF65C/canvas)

## Tasks
- [ ] [FE] **Update Content in the Needs Help Section on All Pre-Check-in and Check-in Pages**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by benbrasso-agile6** [comment]
This ticket is good to be worked on, sketch page all set

**Comment by benbrasso-agile6** [comment]
@lee-delarm6 local screenshots or link to a PR with screenshots that I can review?

**Comment by lee-delarm6** [comment]
[Uploading... Screenshot 2023-10-17 at 2.01.15 PM.png]

**Comment by lee-delarm6** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3BGQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8c58951ef2c6de658145780ea54a74ea3839166/Screenshot%202023-10-17%20at%202.01.15%20PM.png)

**Comment by benbrasso-agile6** [comment]
LGTM

**Comment by benbrasso-agile6** [comment]
@lee-delarm6 second paragraph, appointments is misspelled
