### ISSUE TITLE
Copy of [FE] Update Content in the Needs Help Section on All Pre-Check-in and Check-in Pages

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#65478]
## Background
As part of the Unified Check-in design/discovery, it was determined that we need changes to the Needs Help section to reduce Veteran confusion and provide as much information as possible to help the Veteran.
 
## Wireframes
[Priority 8 wireframes](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/6ECDF941-DF3B-4C1E-983D-1BA221ACF65C/canvas)

## Tasks
- [ ] [FE] **Update Content in the Needs Help Section on All Pre-Check-in and Check-in Pages**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
