### ISSUE TITLE
[FE] Update Content in the Needs Help Section on Check-in Travel Pages

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#65477]
## Background
As part of the Unified Check-in design/discovery, it was determined that we need changes to the Needs Help section on Travel pages to reduce Veteran confusion and provide as much information as possible to help the Veteran.
 
## Wireframes
[Priority 8 wireframes](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/6ECDF941-DF3B-4C1E-983D-1BA221ACF65C/canvas)

## Tasks
- [ ] [FE] **Update Content in the Needs Help Section on All  Check-in Travel Pages**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by benbrasso-agile6** [comment]
This ticket is good to be worked on, sketch page all set

**Comment by loripusey** [comment]
@lee-delarm6 I'm very confused, I went to validate this ticket, it looks like you updated the needs help on the travel pages which was actually a different ticket #65479. The scope of this ticket was to implement the default needs help section on all Pre-Check-in and Check-in pages (minus travel pages). What did you intend to do on this ticket?
cc @benbrasso-agile6

**Comment by benbrasso-agile6** [comment]
Travel pages get updated too. I'll take a look here shortly. There's two variations of need help now.

**Comment by loripusey** [comment]
There are 2 tickets, one for the default on all pages except travel and one for the travel pages.

**Comment by loripusey** [comment]
I swapped the titles & content for the 2 tickets so that the checked-in code coincides with the right ticket. I also validated the work but can UX validate as well? We should push to validate tickets as soon as possible after they enter the validate state. @benbrasso-agile6

**Comment by benbrasso-agile6** [comment]
Here's the check in LoROTA page, which should be: https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/Oe2Llb4#Version

<img width="1127" alt="Screenshot 2023-09-26 at 9 42 46 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/101129355/f79d989a-331a-459b-ad10-e0441738a948">

How can I help clarify the ticket? Want to meet?

**Comment by benbrasso-agile6** [comment]
Sorry. Lee messaged me. I will re-validate once the rest of the pages are in staging.

**Comment by benbrasso-agile6** [comment]
K, going to check travel pages now

**Comment by benbrasso-agile6** [comment]
Also, noticed that the links in the Need Help that go to other pages outside our app, such as 

https://www.va.gov/find-locations?_ga=2.81738335.977278912.1695663344-1202240947.1670614976

and 

https://www.va.gov/HEALTHBENEFITS/vtp/beneficiary_travel_pocs.asp?_ga=2.81738335.977278912.1695663344-1202240947.1670614976

Are including a GA parameter? Is that intention? Something new? I don't think I've seen that before. The reason I bring it up is because using https://www.va.gov/find-locations?_ga=2.81738335.977278912.1695663344-1202240947.1670614976 shows a FE validation error, while linking here https://www.va.gov/find-locations does not show the FE validation error. 

Is including those GA parameters something new that exists in active links now?

**Comment by lee-delarm6** [comment]
The links themselves do not include a GA (google analytics) parameter, it is added on by the google tracking tool we use at runtime

**Comment by benbrasso-agile6** [comment]
@lee-delarm6 check your Need Help content on the confirmation pages

https://staging.va.gov/health-care/appointment-check-in/complete/38999-530

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazNyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bb18ccba0349afd004204d51fb909954af1e917c/Screenshot%202023-09-28%20at%203.21.29%20PM.png)

Content AFTER the sentence that finishes with "... emergency room." should be removed. 

Example (just looking at the need help content in this sketch page) - https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/bLomb40

**Comment by benbrasso-agile6** [comment]
The travel Yes and No pages need help content was fine

**Comment by benbrasso-agile6** [comment]
Created bug ticket, closing this ticket 

https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/66618
