### ISSUE TITLE
GA4: Web Component Mapping

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#65488]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [ ] Mapp/re-map web component event parameters
- [ ] Audit current GTAG events to remove/transition to data layer events
- [ ] Prepare to meet with Design System team to review

## Acceptance Criteria
- [ ] When the above tasks have been completed.
---

**Comment by michelle-dooley** [comment]
Will open new ticket for next sprint.
