### ISSUE TITLE
[FE] Change alert on travel pages to additional info component

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#65480]
## Background
As part of the Unified Check-in design/discovery, it was determined that we need changes to the alert  on Travel pages to reduce Veteran confusion .
 
## Wireframes
[Priority 8 wireframes](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/6ECDF941-DF3B-4C1E-983D-1BA221ACF65C/canvas)

## Tasks
- [ ] [FE] **Change alert on travel pages to additional info component**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by benbrasso-agile6** [comment]
This ticket is good to be worked on, sketch page all set

**Comment by loripusey** [comment]
@lee-delarm6 can you point points on this when you get a chance?

**Comment by lee-delarm6** [comment]
The reason I pointed 3 instead of 2 on this is that it requires an additional input value for the component involved, resulting in extra tests needing to be added

**Comment by benbrasso-agile6** [comment]
@lee-delarm6 I can't get your merge ticket to load for me. Did you capture before and after screenshots anywhere? Is it in that merge PR?

**Comment by lee-delarm6** [comment]
<img width="1126" alt="Screenshot 2023-10-17 at 1 46 50 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/135059743/cd4a166a-8863-47bf-98ac-52124ba8a3a3">
<img width="1146" alt="Screenshot 2023-10-17 at 1 46 47 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/135059743/6f049ee4-c0fa-48cf-8a9c-e503448cb300">
<img width="1239" alt="Screenshot 2023-10-17 at 1 46 44 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/135059743/de1142e5-102f-493c-a853-b4ca4a0df909">
<img width="1008" alt="Screenshot 2023-10-17 at 1 46 42 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/135059743/b9c342e7-4922-4a46-8866-3e445bf6f1ad">

**Comment by benbrasso-agile6** [comment]
LGTM
