### ISSUE TITLE
[FE] 10-10EZ: BUG: Endpoint rating_info being used for LOA1 users causing excessive 500 errors

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#65486]
## Background
With the impending Sept 30th deadline for PACT Act special enrollment, there is additional scrutiny on the 10-10EZ performance.  

It was brought to our attention (see post from Patrick Vinograd below) that we are using an endpoint "health_care_application/rating_info to call BGS for LOA1 users.  However, LOA1 users are not fully authorized and would not have a rating to return.
These calls to BGS are causing the endpoint to generate excessive 500 errors, and while there is no impact to the users/Veterans, it is cluttering up logs and making it more difficult to diagnose more impactful errors. 

**Post from Patrick Vinograd**
>Flagging [this Sentry issue that the health_care_application rating_info method is causing](https://sentry.vfs.va.gov/organizations/vsp/issues/203246/events/27c5b7b03db14782b5eee167f1fee442/?project=3&query=is%3Aunresolved) - it looks like the API is trying to look up rating info for loa1 users (and failing, because we don't have an ICN/SSN for loa1 users. But it shouldn't even be attempting to make a call to BGS in this case. Instead there should be a pundit policy on that API method ensuring that the user is loa3 and has an SSN and if not, throw a NotAuthorized 403.
>Is this causing any user impact? Probably not, those users can't see rating info anyway. But this is causing this endpoint to generate a steady rate of 500 errors that will make it hard to diagnose more impactful errors.

## Tasks
- [x] Review Sentry and confirm this finding
- [x] If this is a valid finding, consider options for limiting the endpoint to call BGS for LOA3 authorized users only
- [x] Implement resolution
- [x] Test solution to ensure the existing errors do not occur, and that new errors are not caused by the solution
- [x] Validate with PM
- [x] Release to production

## Acceptance Criteria
- A solution to remedy the excessive 500 errors is implemented.

**Comment by longmd** [comment]
@hdjustice , this would be just a very small adjustment on the FE to knock out. Currently we are firing that fetch for all logged in users, so we can check if logged in and LOA3 and then fire the fetch if both cases are true.

**Comment by hdjustice** [comment]
@longmd We can actually create one ourselves (instructions from Tze)

>you can create an ID.me account and NOT verify your identity on the ID.me side. 
>- just click Create an account with ID.me when you're at Staging's sign-in dialog. 
>- use an email account that you have access to
>- once created, log into Staging with that acct's email and password.

**Comment by longmd** [comment]
@hdjustice , this update has been applied and verified in staging. Here are screenshots of the network calls:

LOA1 User (no call to `rating_info` endpoint):
<img width="1904" alt="Screenshot 2023-09-15 at 9 38 08 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/753d0875-f663-4707-9dde-77915ece3b64">

LOA3 User (has call to `rating_info` endpoint):
<img width="1904" alt="Screenshot 2023-09-15 at 9 41 10 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/1ca67f52-7852-4418-a959-11d1f908cfcc">

Correct response from endpoint (test user has known rating of 100):
<img width="1904" alt="Screenshot 2023-09-15 at 9 41 30 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/e4085933-f32d-40d2-b037-ac7544804de9">

**Comment by hdjustice** [comment]
Looks great!  Thanks @longmd for addressing this so quickly!
