### ISSUE TITLE
[FE] DS v3 #1: Update form components

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#65490]
## Background
The Design System has moved to version 3. We need to move the components we have that use the Design System to use version 3.
  
For the form-related components (which includes Need help), we need to switch those together/in the same ticket. There’s guidance that talks about this in the [governance rules](https://design.va.gov/components/#governance-rules-for-using-v3-based-components).
And here are the [developer instructions](https://design.va.gov/about/developers/using-web-components#uswds-v1-vs-v3-compatibility) in general. 

Includes authentication page form fields and need help component. 

[UX Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64827)

## Tasks
- [ ] [FE] **Update form components to DS v3**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by benbrasso-agile6** [comment]
Confirming this is ready to be worked on

**Comment by loripusey** [comment]
@brianseek @benbrasso-agile6 This ticket will exclude the buttons

**Comment by brianseek** [comment]
We discussed also that this would not include Needs Help component since we don't use it. Also it doesn't have a USWDS 3 element to it.

**Comment by loripusey** [comment]
@brianseek There is a [ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59166)out there (not to be done anytime soon) to go to the now-existing DS needs help component. But yes, this ticket does not include Needs Help component changes.
cc: @benbrasso-agile6

**Comment by loripusey** [comment]
looks the same in staging, assuming that's a good thing, closing
