### ISSUE TITLE
[FE] DS v3 #3: Update slim alerts

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#65493]
## Background
The Design System has moved to version 3. We need to move the components we have that use the Design System to use version 3.

Update all slim alerts to v3 https://design.va.gov/storybook/?path=/docs/uswds-va-alert--slim  

For design reference: 

[In person pre check in](https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/p/6559E321-AF82-42D1-837D-75F9DB19DF15/canvas) 
[Check in](https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/p/0213EBFE-75F9-4C0E-805B-5E77F30A8F04/canvas) 
[Check in with travel enabled](https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/p/A6E73D11-A95C-4EC0-A3B7-792CE5799C59/canvas) 

## Tasks
- [ ] [FE] **Update alerts to DS v3**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
@benbrasso-agile6 / @loripusey this is ready to merge, but holding off until next year because of the code freeze. In the meantime, here are some screenshots to review. Included is every screenshot with an alert.[screenshots with alerts.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2lMQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--acad6c4ac072f3daf1a73d5ec1401866056232b4/screenshots%20with%20alerts.zip)

**Comment by loripusey** [comment]
I don't notice a difference, I guess that's a good thing

**Comment by benbrasso-agile6** [comment]
LGTM, but, on the error pages, are those alerts 296 px width? Or should they be?

**Comment by brianseek** [comment]
@benbrasso-agile6 the alerts are full width rather than a fixed width. They fluctuate based on screen-size. Is that what you were asking?

**Comment by benbrasso-agile6** [comment]
I think maybe it was an optimal illusion that I was seeing when the H1 is highlighted, if that makes sense. I'm good with them all.

**Comment by brianseek** [comment]
this was just merged and should be good to validate on stage shortly

**Comment by benbrasso-agile6** [comment]
Don't you tempt to try reviewing on local env

**Comment by brianseek** [comment]
I think for validation, we want to keep that out on stage

**Comment by benbrasso-agile6** [comment]
Oh like actual validation happen on stg or prod

**Comment by benbrasso-agile6** [comment]
validated on stg
