### ISSUE TITLE
[FE] DS v3 #2: Update accordions

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#65494]
## Background
The Design System has moved to version 3. We need to move the components we have that use the Design System to use version 3.
  
## Wireframes
[See wireframe ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64828)

## Tasks
- [ ] [FE] **Update accordions to DS v3**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
@brianseek I see this is merged, is it done, can we close it?

**Comment by loripusey** [comment]
validated, closing
