### ISSUE TITLE
Update team names on Platform Website/ Collaboration Cycle

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#65499]
## User Story
As a Governance team member, I want to ensure team names and personnel are accurate so that VFS teams have proper guidance. 

Assignee: @CherylEvans 
Peer Reviewer: @erinrwhite 

## Description
Contact Center team has been renamed to Veteran Support. The Collaboration Cycle documentation needs to be updated to reflect this. Note: Only the team name is changing, not the touchpoint name. 

In addition, the Sitewide CAIA personnel list is not correct on the Contact Us page.

## Impacted Artifacts
[Contact Center review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/contact-center-review) touchpoint page
[Contact Us](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/contact-us) page

## Tasks
- [x] On Contact Center touchpoint page, remove Contact Center as Owner and replace with Veteran Support
- [x] On Contact Us page, remove team name Contact Center and replace with Veteran Support.
- [x] On Contact Us page, list the CAIA people as follows:
> Project manager: Terry Nichols
> Scrum master: Lily Strelich
> Accessibility: Sara Smith
> Information architect (IA): Kristin Ouellette Muskat
> Managing editor (Content): Laura Willwerth
- [x] Inform @ATMiddleton for Veteran Support and @coforma-terry for CAIA when changes are published

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS teams are aware of the correct team names for the Contact Center touchpoint
- [x] VFS teams are aware of the appropriate points of contact for CAIA

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
@erinrwhite I made the changes directly to the source pages. Once they publish this afternoon, I will complete the last task, let the CAIA folks know, and provide links to the updated pages. I will let you know once this is done, and you can peer review it when you have time. :-)

**Comment by CherylEvans** [comment]
Once published:

@Anita Middleton @Terry Nichols FYSA
I updated the following:

- On the Contact Center review touchpoint page, I removed Contact Center as Owner and replaced it with “Veteran Support” Team

- On the Contact Us page, I removed the team name Contact Center Team and replaced it with Veteran Support Team.

- On the Contact Us page, I listed the CAIA people as follows:

Project manager: Terry Nichols
Scrum master: Lily Strelich
Accessibility: Sara Smith
Information architect (IA): Kristin Ouellette Muskat
Managing editor (Content): Laura Willwerth
Please let me know if you have any questions or concerns.

**Comment by CherylEvans** [comment]
@erinrwhite This is ready for your peer review. :-)

**Comment by erinrwhite** [comment]
@CherylEvans Only one small edit on the [Contact page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/contact-us) - Kristin Ouellette Muskat's second name starts with an O, not a Q. I have a hard time differentiating this as well!

**Comment by CherylEvans** [comment]
@erinrwhite Thanks for catching that!  I changed it on the source page, and it will appear correctly on Monday since platform content doesn't run the updates on Friday. :-)

**Comment by CherylEvans** [comment]
Everything is now corrected on the PW. I am closing this ticket.
