### ISSUE TITLE
Discovery: Migrate AL1-based Infrastructure to AL2-based

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#65491]
# Description
We will continue to document a more detailed plan to analyze and migrate AL1-based applications to AL2-based images in the below Confluence document. We will also describe potential stumbling blocks caused by key differences in AL1 and AL2 based images.

https://vfs.atlassian.net/wiki/spaces/PRT/pages/2765651969/Plan+to+migrate+AL1-based+instances+to+AL2-based+instances

This might be a good list of all the things that use AL1:
https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/build/roles

## What skills do we need to do this discovery?
- Access to `devops`
- Ability to understand the ansible code that defines the construction of the AL1 images
- Ability to trace devops code across build, release, and deployment steps
- Ability to analyze the difference between AL1 and AL2 based configurations

# Acceptance Criteria
- [x] We have analyzed the significant differences between AL1 and AL2
- [x] For 3 to 5 applications hosted on AL-based images, we understand the likely impact of the changes between AL1 and AL2
- [x] A plan for converting the AL1 applications to AL2 is available in VA.gov-team GitHub

**Comment by pjhill** [comment]
Recording some high-level notes about significant differences between AL1 and AL2 [here](https://vfs.atlassian.net/wiki/spaces/PRT/pages/2768666699/Significant+Differences+Between+AL1+and+AL2).
