### ISSUE TITLE
[FE] Onsite Notifications: Hide Notification section on My VA

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#65503]
## Background
Given that we are no longer pursuing the VA Notify integration for onsite notifications and are pursuing other forms of onsite notifications, we need to hide the Notifications section from My VA. For now this should be done feature flag instead of removing the code/feature entirely, until we a have a better sense of long term strategy around this.

Note: we need to maintain the section and component in staging, while the analytics team works out the issue with GA so that we can test/confirm when they have a fix.

## Tasks
- [x] Open PR on `vets-api` to add new feature flag (name: `my_va_hide_notifications_section`)
- [x] Open PR on `vets-website` to implement ^ feature flag, use Toggler component or useToggleValue hook
- [x] Test with mock data
- [x] Validation

## Acceptance Criteria
- [ ] Notifications section (and all onsite notifications) are no longer visible in production.

**Comment by allisonlu** [comment]
@ajakabcin 

Ready for validation!

Confirmed that Flipper on staging: https://staging-api.va.gov/flipper/features/my_va_hide_notifications_section

And verified that the Notifications section is indeed not appearing for user 11 (who has a lot of notifications)

**Comment by ajakabcin** [comment]
Looks perfect thank you @allisonlu - great job!

**Comment by ajakabcin** [comment]
Closing this out - we'll turn the flag on in production next sprint (#66331) when the product guide is submitted
