### ISSUE TITLE
[FE] My VA Healthcare: Resolve bug in new cerner alert

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#65508]
## Background
While validating #62899, Adam came across a minor bug in the cerner message: the text in the second bullet point is being cut off:
![Screenshot 2023-09-13 at 1 07 44 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/33b8751e-5e3c-46e5-b233-cb01ffea12a1)

See his comment [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62899#issuecomment-1708881337).

## Tasks
- [ ] Fix spacing issue
- [ ] Test
- [ ] Move to validate and tag PM for confirmation

## Acceptance Criteria
- [x] The cerner alert is updated and specs match provided design

**Comment by aagosto90** [comment]
Looks good to me in Chrome 
<img width="654" alt="Screenshot 2023-09-19 at 2 32 25 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/97965610/bd25ac6e-b99f-41d2-acb6-452130a2d769">

**Comment by ajakabcin** [comment]
great! we can close this out then @dellerbie
