### ISSUE TITLE
BE | Profile | Direct Deposit | Add Logging to Direct Deposit Gets

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#65502]
## Background
Adding more data points to our logs should help us better understand the circumstances around when the following error is returned from LH - `Payment address not found`.

## Tasks
- [ ] Add the following boolean flags:
  - [ ] has-mailing-address
  - [ ] has-residential-address
  - [ ] has-bai-flag

## Acceptance Criteria
- [ ] Verify data points are being logged to staging.
- [ ] Verify data points are being logged to prod.

## Blocked 
- Currently waiting on answers from LH

**Comment by tpharrison** [comment]
I don't think this ticket is relevant anymore.  When removing address fields or adding the BAI flag in staging, I wasn't able to reproduce this error, so it doesn't appear related to the fields listed.
