### ISSUE TITLE
Team QA | Profile | Default Send | The default send values in Staging for BVA are different in prod

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#65511]
## Background

There may be a discrepancy between the default send values in staging versus what we see in production that we need to investigate. 

### In staging 
When testing with user 77, both BVA notifications had the checkbox checked, and the default send indicator as `true` and did not have a `communicationPermission` property

### In production 
When testing with Liz's production account, the hearing reminder was unchecked, and the status update was checked. For both, the default send indicator was `true`, and did not have a `communicationPermission property`.

## Tasks 
- [x] confirm the values in staging 
- [x] confirm the values in production 
- [x] compare the values and present the discrepancy to VA Profile 
- [ ] if this proves to be a valid issue log this against the [qa test plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/default-send/QA/qaPlan.md#adverse-findings-summary)

## Acceptance Criteria
- [x] No further action needed, as turned out to be an issues with the differences that radio buttons / the checkbox ui since prod didnt have the checkboxes turned on yet.

**Comment by andaleliz** [comment]
@mtcA6 since I reported this, is it necessary for me to repeat again, or are there different steps you'd like me to take?

**Comment by mtcA6** [comment]
@andaleliz nope I don't want you to test again (unless you want to!), added everyone since it was a tight planning session I added you to make sure I capture the issue correctly when copy pasting/modifying from the spreadsheet, so thank you for editing for clarity. 

I thought I heard both Adam and Tom said they were going to look into this so I added them.
I added Pam since we were working through QA as a team, figured if they have time they could check this in staging/prod if the fancy struck them. 

Thanks for checking in! I've removed you from the list of assignees.

**Comment by mtcA6** [comment]
@adamwhitlock1 thanks for showing me this last week, glad to hear this is because we don't have the same toggles enabled in production that we have in staging, and since we're not using the default send logic we subsequently see values that seem illogical. Thanks for getting to the bottom of this! I'm going to move this to validate, feel free to close this when you're ready.

**Comment by adamwhitlock1** [comment]
Talked with Liz on this and explained the differences as well. Going to close this out now.
