### ISSUE TITLE
[BE] 10-10EZ - Monitoring & Alerts: Add monitor & alert for submission fails with no retries left

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#65517]
## Background
To support the PACT Act enrollment deadline 9/30, we need to add an alert for failed submissions with no retries left. 
We get about 10 of these per month. we should be alerted, ticket each one, and then try to chase down the root cause for the failure with the VES team. 

The goal is to understand each failure and explore ways to prevent the same kind in the future.

## Tasks
- [ ] Set up a monitor to track when a submission fails with no retries left
- [ ]  Set up ability to log entire form so that the data can be accessed after the failure
- [ ] Set up alert to notify #health-tools-1010-apm channel each time a submission fails with no retries
- [ ] Test alerts, if applicable
 
## Acceptance Criteria
- Submission failures with no retries left are monitored, and alerts are set up and will be sent to the apm slack channel.
