### ISSUE TITLE
SPIKE | CH 31 Failure Points and Sidekiq Jobs

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#65513]
## Issue Description
_Understand the points at which claims and fail and what remediation is or is not in place to ensure failed claims are submitted and document sidekiq jobs._
- See solution outlined in https://github.com/department-of-veterans-affairs/va.gov-team/issues/64538 for form 686c and 674.
- List of known jobs [sidekiq_jobs_new.csv](https://github.com/department-of-veterans-affairs/va.gov-team/files/12675536/sidekiq_jobs_new.csv)
- Collect as much information as possible, but do not delay if info is incomplete.

- High priority request for specific jobs outlined in [this request](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1268) and [this request](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1273):
   - VRE::Submit1900Job app/workers/vre/submit1900_job.rb
   - VRE::CreateCh31SubmissionsReportJob in file app/workers/vre/create_ch31_submissions_report_job.rb
   
---
## Tasks
- [x] Document the sidekiq jobs
- [ ] Document where code is located
- [ ] Is the job veteran-facing? (yes)
- [x] What happens if it fails? Is the veteran notified? Is so, how?
- [ ] Provide links to existing dashboards, monitors, and alerts for these background jobs.
- [ ] For each job, please note any ways it has failed in the past. (Temporary failures resolved by retries do not need to be included). Can it still fail in this manner?
   - Base failure knowledge on recent history. 

## Acceptance Criteria
- [ ] Claim failure flow diagram similar to https://github.com/department-of-veterans-affairs/va.gov-team/issues/64538 for Chapter 31 form.
- [ ] Document all of the cases where the forms use Sidekiq jobs for Chapter 31 form in readme within repo and provide to Steve Albers

**Comment by tblackwe** [comment]
providing a sample from our 526 team

-----------
## Please fill out this survey based on the criteria defined below

### Background Job List 
All Jobs should belong to the team(s) assigned to this survey.

- Form526ConfirmationEmailJob
- EVSS::DisabilityCompensationForm::SubmitForm526AllClaim
- EVSS::DisabilityCompensationForm::SubmitUploads
- EVSS::DisabilityCompensationForm::UploadBddInstructions
- CentralMail::SubmitForm4142Job
- EVSS::DisabilityCompensationForm::SubmitForm0781
- EVSS::DisabilityCompensationForm::SubmitForm8940
- EVSS::DisabilityCompensationForm::SubmitForm526Cleanup
- Sidekiq::Form526BackupSubmissionProcess::Submit

---

### Please answer the following Questions:
1. Does your team own all of the Jobs listed in this request? Please list any that you do not believe you own, or suggest missing items that you do.
Yes, we own all of the above

2. Of the jobs listed, which are involved in a veteran-facing workflow?
All of them are critical to a successful 526 submission, which is verteran facing.  

4. For veteran facing jobs, what happens if they fail? Is the veteran notified? If so, how?
If any or all fail, they will retry.  In the event of a catastrophic failure, we have a backup submission flow which will rerun everything (Sidekiq::Form526BackupSubmissionProcess::Submit).  IF this fails we will be alerted and we have a manual paper submission process we will run, with VA stakeholder aproval.

6. Please provide links to any existing dashboards, monitors and alerts for these background jobs

**Dashboards**
- [Form 526 Disability Compensation](https://vagov.ddog-gov.com/dashboard/ygg-v6d-nza/form-526-disability-compensation?refresh_mode=sliding&from_ts=1695135168409&to_ts=1695307968409&live=true)
    - a wholistic health monitor that tracks the following events
      - Intent to file submitted
      - Valid form submitted
        - This event implies that all of our ancillary services (listed above) have worked as expected) **except for the BackupSubmissionProcess job**
      - Submission Accepted by EVSS
        - A failure here can indicate either a problem with our submitted data or an outage with the EVSS submission Endpoint
- [Benefits - 526 Backup Submission](https://vagov.ddog-gov.com/dashboard/u9b-62v-t48/benefits---526-backup-submissions?refresh_mode=sliding&from_ts=1695305477278&to_ts=1695309077278&live=true)
  - Tracks enqueuing and dequeuing of backup submission jobs.
    - No explicit information about success or failure
     
**Monitors & Alerts**
- [Form 526 Backup Submission Error. Investigate](https://vagov.ddog-gov.com/monitors/110156)
  - Watches for a non-zero number of 526 Backup Submission Errors (via logs)
    - ALERTS: kyle.soskin@adhocteam.us, sam.stuckey@oddball.io, Slack benefits-ce-dd-notifications
- [Document Service API slowdown or outage](https://vagov.ddog-gov.com/monitors/159640)
  - Watches for non-completion of requests to our third party Document Service (EVSS)
    - ALERTS: Slack benefits-ce-dd-notifications
- [526 Completion rate is low](https://vagov.ddog-gov.com/monitors/157864)
  - Tracks count of 'cleanup' events executed by the 526 flow (`EVSS::DisabilityCompensationForm::SubmitForm526Cleanup`) per hour.  Alert triggers at less than 2.
    - ALERTS: Slack benefits-ce-dd-notifications
- [526 Backup Submission Errors are high](https://vagov.ddog-gov.com/monitors/158397)
  - Tracks count of 526 Backup Submissions (`Sidekiq::Form526BackupSubmissionProcess::Submit`) with a status of `error` per hour.  Alert triggers at 30 or more.
    - ALERTS: Slack benefits-ce-dd-notifications
- [526 Backup Submission Errors occurred today](https://vagov.ddog-gov.com/monitors/158396)
  - Tracks count of 526 Backup Submissions (`Sidekiq::Form526BackupSubmissionProcess::Submit`) with a status of `error` per day.  Alert triggers at 100 or more.
    - ALERTS: Slack benefits-ce-dd-notifications
   
**WIP additions**
We are in the process of fortifying our monitors with alerts specific to every 3rd party API interaction.  "Document Service API slowdown or outage" listed above was the first of these new monitor / alerts to be added.  [Upcomming additions are documented here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/KPI_alerting_with_datadog.md)

8. For each job, please note any ways it has failed in the past. (Temporary failures resolved by retries do not need to be included) Can it still fail in this manner? 

- [ITF submission debacle postmortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/1227/files#diff-5e2d7e281dff4727596b9726053994005765f72844b3bafe03430e5f09303b09)
  - [slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1691591736796649) for additional context
- [Submission "Black Hole" problem](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/526_failure_batching_and_triage_handoff.md#tldr)
- Other failures
  - EVSS outages often cause failures which are resolved by default retrying
  - [If for some reason our Main submission and Backup submission fail catastrophically, we will execute the following procedure to process these dropped applications (pending VA approval as this is an expensive process for them)](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/playbooks/526-submission-failure-manual-submission.md)

**Comment by DLarson-Oddball** [comment]
## Please fill out this survey based on the criteria defined below

### Background Job List 
All Jobs should belong to the team(s) assigned to this survey.

-   VRE::Submit1900Job app/workers/vre/submit1900_job.rb
-   Form526ConfirmationEmailJob app/workers/form526_confirmation_email_job.rb
-   VRE::CreateCh31SubmissionsReportJob in file app/workers/vre/create_ch31_submissions_report_job.rb
-   CentralMail::SubmitForm4142Job in file app/workers/central_mail/submit_form4142_job.rb
-   CentralMail::SubmitSavedClaimJob in file app/workers/central_mail/submit_saved_claim_job.rb
---

### Please answer the following Questions:
1. Does your team own all of the Jobs listed in this request? Please list any that you do not believe you own, or suggest missing items that you do.
Yes, we own all of the above
	
2. Of the jobs listed, which are involved in a veteran-facing workflow?
	- VRE::Submit1900Job
	- Form526ConfirmationEmailJob 
	- CentralMail::SubmitForm4142Job
	- CentralMail::SubmitSavedClaimJob

3. For veteran facing jobs, what happens if they fail? Is the veteran notified? If so, how?
	- VRE::Submit1900Job
		- A notification is sent to Sentry when a return status code is 400 in sending  a VRE confirmation email
		- Retry logic is likely not in place as exceptions are not raised outside `perform`
	- Form526ConfirmationEmailJob
		- A message is sent to sentry for any error
		- Retry logic is in place for  with a 5xx status_code 
	- VRE::CreateCh31SubmissionsReportJob
		- Retry logic in place for any exception
	- CentralMail::SubmitForm4142Job
		- Retry logic in place for any response received between 201 and 600
	- CentralMail::SubmitSavedClaimJob
		- Submissions have a status field updated upon failure
		- Retry logic in place for any exception

4. Please provide links to any existing dashboards, monitors and alerts for these background jobs

5. For each job, please note any ways it has failed in the past. (Temporary failures resolved by retries do not need to be included) Can it still fail in this manner? 
	- VRE::Submit1900Job
		- VRE Confirmation email has failed to send and is a current team priority to resolve

**Comment by steele-lm** [comment]
@DLarson-Oddball For VRE::Submit1900Job where "A notification is sent to Sentry when a return status code is 400 in sending a VRE confirmation email"...is that the email sent to the Veteran confirming their submission?

**Comment by DLarson-Oddball** [comment]
@steele-lm As I understand it, this email is what notifies the case worker of a new submission which they then retrieve from VBMS and input into CWINRS. So, not sent to the Veteran.

**Comment by fred-khoury-oddball** [comment]
Yo there is a lot of words I am confused. Here is my understanding of the emails that get sent during the VRE::Submit1990Job:
- There are two emails that sent in this process
- One is from VA notify to the veteran and can have one of two body contents
 - This email gets sent from the va notify team but is triggered in the vets-api
 - The contents of this email are 1 of two things:
   1 - 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135056639/79420f40-9f7e-4dd9-8dad-a35c2aa4205b)
  2 -   
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135056639/a445ba9f-e3fa-484f-812a-2882556019d9)
- The second email is sent from the vets-api server using action mailer and should sent and email to the VRE people
  - that is the email mentioned here:
  https://github.com/department-of-veterans-affairs/va.gov-team/issues/65641
   
@DLarson-Oddball  is this what you are seeing .

**Comment by tblackwe** [comment]
That's some good context @fred-khoury-oddball, we can expand the 1900 section. The ask from platform is do we own it, and what happens when it fails. Your research has shown that there are two opportunities for failure. Are those 2 email sends async? or does one failing prevent the other?

**Comment by mjknight50** [comment]
Completed "Document the sidekiq jobs"

**Comment by mjknight50** [comment]
From @danlim715 "If user.participant_id is blank or VBMS upload fails, we send an async central mail confirmation email to user. That seems to be the only notification we send to the veteran. The sentry logging just seems to be purely for internal logging and doesn't send a notification to the veteran, as far as i can tell."
at least for the VRE::Submit1900Job.  For the VRE::CreateCh31SubmissionsReportJob submission report job, there didn't seem to be any error handling. There was one async email that's queued up, but not on error"

**Comment by steele-lm** [comment]
I've transferred the documentation gathered over to https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1268
