### ISSUE TITLE
Update VA 508 Office page on Platform Website for submitting an audit request

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#65510]
## User Story
As a VFS Team member, I want to have clear guidance on how to request support from the VA Section 508 office so that I am meeting expectations.

Assignee: @briandeconinck 
Peer Reviewer: @it-harrison 

## Description
On September 7, @artsymartha68 shared with Governance team on the #platform-collaboration-cycle channel that the VA 508 Office audit results will soon transition to the VA SharePoint side opposed to them sending out Word and Excel docs as they currently do. https://dsva.slack.com/archives/G01DXP10GCA/p1694099023977599

When this change goes live, the VA 508 Office Audit page on Platform Website will need to be updated to reflect the new process. 

In addition, this ticket should included updating the name of the office to "VA Section 508 Office"

**Update 1/19/2024**: Per @artsymartha68, The VA Section 508 Office is now using MS Power Apps. Since this is how the VA Section 508 office delivers feedback, and has nothing to do with the steps for submitting an audit request, this may have to be handled in a separate ticket.

## Impacted Artifacts
[Request support from the VA 508 office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office) page on Platform Website

## Tasks
- [x] Test the audit request process from the VA Section 508 office. Ensure you are documenting all steps.
- [x] Update the Audit Request section of the Request support from the VA 508 office guidance to align it with the actual VA Section 508 process

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] The Audit Request section of the Request support from the VA 508 office guidance on Platform Website provides accurate guidance to VFS teams

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@artsymartha68 following up on this. I know we need to make changes to our page due to Jeana's recent issue with the [guidance not matching ](https://dsva.slack.com/archives/C023ZKDJJK1/p1705074562382969) the actual form from the VA Section 508 Office. If possible, I'd like to address that issue and the SharePoint concerns together.

Do you know if the VA Section 508 office has begun sharing results via SharePoint yet? Please let me know! Thanks

cc @briandeconinck

**Comment by artsymartha68** [comment]
The 508 Office is now using MS Power Apps to track their a11y findings. When you receive the audit report email, there is a "508 Compliance Application" link. [Here is a recent one](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.gov.powerapps.us%2Fplay%2Fe%2Fdefault-e95f1b23-abaf-45ee-821d-b7ab251ab3bf%2Fa%2F5f7da63e-384d-4ce4-8cc7-f3be6c60c363%3FtenantId%3De95f1b23-abaf-45ee-821d-b7ab251ab3bf%26sourcetime%3D2023-08-14%252017%253A50%253A55Z%26RecordID%3D375&data=05%7C02%7C%7Cc40a3c52eca648284b0608dbfbef88d2%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638380778435616543%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CPjznS2oagiYGXSHNJvihM5YGQRfdw%2F%2BwWvK7%2Bh%2FlZw%3D&reserved=0). I just requested access myself. I also verified that anyone who gets the email can register for access.

**Comment by shiragoodman** [comment]
thank you @artsymartha68 . I will work on refining this ticket. We can pick this up as tech debt soon and get the Request support from the VA 508 office page updated. I will follow up!

**Comment by briandeconinck** [comment]
[Draft revisions complete](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2949677057/65510+-+Request+support+from+the+VA+508+office), reached out to Christopher Walker in the Section 508 Office to verify some of the changes I've made.

**Comment by it-harrison** [comment]
@briandeconinck - looks good; I fixed one very small typo and left a comment, which you can handle as you see fit. I think it can launch as is.

**Comment by briandeconinck** [comment]
@it-harrison Made some edits based on your comment. If it looks clear enough I'll queue this up to publish!

**Comment by briandeconinck** [comment]
Carrying over into the next sprint. I have one small edit to make based on Chris Walker's feedback, then hopefully good to go.

**Comment by briandeconinck** [comment]
Final edits made based on Chris Walker's feedback, and queued up to be published on Platform website. Closing this one out!
