### ISSUE TITLE
[BE] 10-10EZ - Monitoring & Alerts: Set up and update health checks for ES downstream services

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#65518]
## Background
To support the PACT Act enrollment deadline 9/30, we need to understand the health check sensitivity for the various ES downstream services and, if appropriate, tune those health checks so breakers don’t trip as quickly

 - we may not have this in our code base, check with Platform

### Resources
- [Original Slack thread](https://dsva.slack.com/archives/C05Q1A58Y1L/p1694029753647579)
- [10-10EZ PACT Act Resiliency dashboard](https://vagov.ddog-gov.com/dashboard/8yz-qzc-bng/10-10ez-pact-act-resiliency?refresh_mode=sliding&from_ts=1694620643717&to_ts=1694707043717&live=true)
- [fwdproxy dashboard, including health check failures](https://vagov.ddog-gov.com/dashboard/ae4-qch-6vw/forward-proxy?refresh_mode=paused&tpl_var_proxy%5B0%5D=es_back&from_ts=1694027127742&to_ts=1694027427742&live=false)
- Full health check path for the Enrollment System - [ves.va.gov/voa/voaSvc?wsdl](http://ves.va.gov/voa/voaSvc?wsdl)
- [Health Check failures widget on Platform dashboard](https://vagov.ddog-gov.com/s/f327ad72-c02a-11ec-a50a-da7ad0900007/sd5-7r5-fns)

- [Synthetic EESummary endpoint](https://vagov.ddog-gov.com/synthetics/details/ve7-u2p-9wh?from_ts=1694636383151&to_ts=1694639983151&live=true)
- [Synthetic VOA endpoint](https://vagov.ddog-gov.com/synthetics/details/wh8-sa4-yhf?from_ts=1694636463469&to_ts=1694640063469&live=true)

## Tasks
- [x] Review the [fwdproxy-based health checks](https://vagov.ddog-gov.com/dashboard/ae4-qch-6vw/forward-proxy?refresh_mode=paused&tpl_var_proxy%5B0%5D=es_back&from_ts=1694027127742&to_ts=1694027427742&live=false) for the downstream ES services. 
- [x] Determine the current thresholds/breakers
- [ ] If needed, adjust the thresholds/breakers levels so they don't trip as quickly as they do currently
- [x] Consider adding alerts for the health checks thresholds to be sent to our #health-tools-1010-apm Slack channel
 
## Acceptance Criteria
- A review of the health checks has been completed, and adjusted to a less sensitive threshold, if needed.

**Comment by luis-simauchi** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXNmQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e8e9639992f44f1f1b7f2831f45d73f1c4a86f5f/DD%20ES%20health%20check.PNG)

Depending on time frame: avg health check failures range from 187 per last 3 months
But a month look back seems more stable at 10.4 avg check failures

**Comment by luis-simauchi** [comment]
current Forward Proxy Health Check Monitor Failure query:
sum(last_5m):sum:haproxy.server.check.failures.total{deployment_env:vagov-prod,proxy:va_mobile_back} by {proxy}.as_count().rollup(sum, 60) > 5

current Platform based - Forward Proxy Health Check Failures
sum(last_5m):avg:haproxy.server.check.failures.total{*} by {proxy,deployment_env}.as_count() > 10

**Comment by luis-simauchi** [comment]
Path way note: The es entry in fwd proxy is for the /voa/voaSvc endpoint and hca_ee entry is for the /esr-ws/spring-ws/getEESummary endpoint, and the health check failures were in the es_back. I'm just trying to look around at anything related

**Comment by luis-simauchi** [comment]
overall what is occurring is:
Health check to ES fails due to network connection error
Health check failure triggers breakers
Controller errors because breakers prevent connection to ES

**Comment by luis-simauchi** [comment]
despite initial review, it looks like the 2s health check is "too chatty" per Faulkner's suggestion, we may need to move it to every 5 mins.

here is the link to the file that would need changing: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/fwdproxy/haproxy.conf.j2
