### ISSUE TITLE
Profile Dataset Update & QA - INTERNAL

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#65519]
## Issue Description
This is an internal ticket to outline the work needed to complete the [Profile direct deposit dataset update ticket](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/63633)

---
## Tasks
- [x] @dorseypa1 Upload the [updated page and event](https://docs.google.com/spreadsheets/d/19WJeYmdpp5Y2JiB5l0DLOph1uoyi62u_Cis4eVE5VGE/edit#gid=0) to vsp_sites_profile dataset in BQ. The first dataset had duplicates for Save started events that should have been successful and failed events. The update worksheet has these changes highlighted in red. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWVZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--25a184bb44353936855197adf4edead4ebd27579/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaktZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2284737e5bebd5a6b94169a5e6c8d52f7ce281cc/image.png)

- [x] @ChristineYoungZA once the revised dataset is uploaded we need to QA the API Retrievals and Saves cards on the dashboard against [GA reports](https://analytics.google.com/analytics/web/#/report/content-event-pages/a50123418w177519031p184624291/explorer-table.filter=~2Fprofile~2F&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.eventAction&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22RE%22,%22~2Fprofile~2F%22,0%5D%5D) to make sure the numbers align (you will need to adjust the GA report filters to align with what is included in the dashboard per the [updated page event dataset](https://docs.google.com/spreadsheets/d/19WJeYmdpp5Y2JiB5l0DLOph1uoyi62u_Cis4eVE5VGE/edit#gid=0)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBalNZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0c7b9a35127a0b503dff6ec5e0423cc076ce49de/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaldZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--69770747d26e602b9d50842a7d33c18ed8b108a5/image.png)

## Acceptance Criteria
- [x] When QA has been completed and approved.
---

**Comment by dorseypa1** [comment]
The Profile table has been updated in BQ and I updated the BQ - Profile Hits Detail Domo dataset and the missing event_action records are showing now  
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/117392065/42c9a6d7-effb-4a12-8dba-36c407431b67)

**Comment by ChristineYoungZA** [comment]
Thanks @dorseypa1

**Comment by ChristineYoungZA** [comment]
Hi @michelle-dooley is there any feedback on the QA document shared over?
