### ISSUE TITLE
BQ - Standard Forms Landing Page Dataset Update

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#65521]
## Issue Description
The dataset has not updated since 8/15/2023. It is set to manual so that would be why but since the set up just loads 'last_week' so we need to change to update back to 8/15 and then change back to 'last_week' and weekly schedule updates..

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbWFZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3d5ea33a72491861c9f3dc212035904b5a4f1b29/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcitZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b141778e47292b4e315e9b1a84a4ee5d0fb6babe/image.png)

---
## Tasks
- [x] update the dataset back to 8/15/23
- [x] then change back to weekly updates on sunday

## Acceptance Criteria
- [x] dataset updated and weekly updates begin again.
---
