### ISSUE TITLE
[Design, FE] 10-10EZ - Update failed state messaging in-application and on Confirmation page

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#65524]
## Background
In preparation of the final week or so before the PACT Act 9/30 enrollment deadline, we want to update the failure state on the Confirmation page and in-application error messaging to include specific instructions for users who are trying to meet the 9/30 deadline.

Danielle Thierry is already working on the content for this, in addition to #65436

❗  **NOTE** - This is a temporary change.  After 9/30, we will need to reset the content back to the original messaging.

## Tasks
- [x] Work with Danielle Thierry & team to create/validate content of the error messages within the application and on the Confirmation page
- [x] Implement the updates to the application
- [x] Complete testing to ensure the errors appear as expected and not appearing when not expected
- [x] Validate with PM/PO prior to releasing to production
 
## Acceptance Criteria
- Failure state error messaging within the 10-10 EZ application, as well as on the Confirmation page, are updated to include specific instructions for Veterans trying to meet the 9/30 PACT Act deadline.

**Comment by longmd** [comment]
@hdjustice / @katelyncai , these content updates are in staging. The performance alert is obviously hidden behind the flipper, which is set to 100% of authenticated users on staging for testing. So if you view the page as a guest, you wont see the alert, but if logged in you will. Here are screenshots of all the content in action:

**Form footer:**
![Screenshot 2023-09-25 at 12 38 53 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/6738544/0f5bc0d2-baf5-4ef2-9a7f-7f4bb4385fdf)

**Submission error:**
![Screenshot 2023-09-25 at 12 52 08 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/6738544/4fdc2a14-259b-4cf9-a15c-a1b9ddc03b9e)

**Performance warning:**
![Screenshot 2023-09-25 at 12 55 33 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/6738544/79b6d175-3ccb-4a35-bd91-b824cb3ecea0)

**Comment by hdjustice** [comment]
Looks great!
