### ISSUE TITLE
Staging User Account for Usability Test

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#65529]
## Issue Description
We will need a staging user account with active copay debt for participants in our accessibility user study (planned for 3rd week of October 2023).

---
## Tasks
- [ ] _Tickets created to request test staging user_
- [ ] _Apply copay to test account_

## Acceptance Criteria
- [ ] _LETT ticket request_ (Scott James to assist)
- [ ] _User has active copay applied to account_
- [ ] _User can submit form without copay disappearing_
---

**Comment by HeatherRienks** [comment]
@ScottyRJames to chat with Identity team about accounts.

**Comment by charlottecesana** [comment]
To clarify: User will need to have copay debt since we will be taking participants through the Streamlined Waiver flow.
