### ISSUE TITLE
Utilize codeblocks for Zoom information for Collab Cycle meetings guidance

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#65528]
## User Story
As a Governance team member, I want to be able to easily copy/paste Zoom information when scheduling collab cycle touchpoints so that the process is quicker/earsier for me to complete. 

Assignee: @erinrwhite 
Peer Reviewer: @allison0034 

## Description
@allison0034 suggested we utilize code blocks for the Zoom information for Collab Cycle meetings guidance so it's easier to copy/paste the zoom info, with just 1 click.

## Impacted Artifacts
[Zoom information for Collab Cycle meetings](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2454585540/Zoom+information+for+Collab+Cycle+meetings)

## Tasks
- [x] Convert "Copy/paste into invite" into a code block for all events

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Zoom information is able to be copied with 1 click

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
@allison0034 ready for your review [in production](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2454585540/Zoom+information+for+Collab+Cycle+meetings).

**Comment by allison0034** [comment]
@erinrwhite peer review complete, looks good!
