### ISSUE TITLE
[BE] 10-10EZ - Monitoring & Alerts: Add synthetic DataDog health checks

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#65522]
## Background
To support the PACT Act enrollment deadline 9/30, we need to add synthetic datadog health checks (in addition to the fwdproxy-based health checks #65518) for the downstream ES services. 
     - **From Patrick**: replicate the health checks for the `hca_ee` and `es` services (and any other 1010ez specific services) in a DD synthetic

Hypothesis: It is much easier to configure/tweak datadog health checks and easier to see why a health check failed. 

### Resources
- [Original Slack thread](https://dsva.slack.com/archives/C05Q1A58Y1L/p1694029753647579)
- [10-10EZ PACT Act Resiliency dashboard](https://vagov.ddog-gov.com/dashboard/8yz-qzc-bng/10-10ez-pact-act-resiliency?refresh_mode=sliding&from_ts=1694620643717&to_ts=1694707043717&live=true)
- [fwdproxy dashboard, including health check failures](https://vagov.ddog-gov.com/dashboard/ae4-qch-6vw/forward-proxy?refresh_mode=paused&tpl_var_proxy%5B0%5D=es_back&from_ts=1694027127742&to_ts=1694027427742&live=false)
- Full health check path for the Enrollment System - [ves.va.gov/voa/voaSvc?wsdl](http://ves.va.gov/voa/voaSvc?wsdl)
- [Health Check failures widget on Platform dashboard](https://vagov.ddog-gov.com/s/f327ad72-c02a-11ec-a50a-da7ad0900007/sd5-7r5-fns)

- [Synthetic EESummary endpoint](https://vagov.ddog-gov.com/synthetics/details/ve7-u2p-9wh?from_ts=1694636383151&to_ts=1694639983151&live=true)
- [Synthetic VOA endpoint](https://vagov.ddog-gov.com/synthetics/details/wh8-sa4-yhf?from_ts=1694636463469&to_ts=1694640063469&live=true)

## Tasks
- [x] Set up synthetic datadog health checks in addition to the fwdproxy-based health checks for the downstream ES services. 
- [x] Set up alert thresholds to notify #health-tools-1010-apm channel when failures occur
- [ ] Test alerts, if applicable
 
## Acceptance Criteria
- Datadog Synthetics are set up with appropriate alerts being sent to the #health-tools-1010-apm Slack channel

**Comment by luis-simauchi** [comment]
locations to ping on the synthetic 
 locations: [
      "pl:eks-prod-89a685eba33cba0af85d34c28ef73dc2",
      "pl:eks-sandbox-f850e8aeb13849507c5b2ce050c03d31",
      "aws:us-gov-west-1",
      "pl:eks-utility-2ad20a19f7f56ed787e56c9d9e2f981d",
      "pl:eks-dev-6edea1b8f6a130b838cab0ca4ac5ec7e",
      "pl:eks-staging-de0ef7aa71a610df09dd3bba03e63d43",

**Comment by luis-simauchi** [comment]
need to decide weather the path for the synthetic is

host: ves.va.gov
check_path: /voa/voaSvc?wsdl  
OR  
/esr-ws/spring-ws/getEESummary/eeSummary.wsdl
