### ISSUE TITLE
EVSS - Submit Dashboard - Monitor Sidekiq jobs

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#65548]
## Issue Description
Create a DD Dashboard to allow us to monitor 526 claim submission migration to LH 

**Scope** of this ticket is to build a widget to monitor identified Sidekiq jobs that need to be monitored for LH migration release for Submit endpoint.

---
## Tasks
- [ ] Writing queries for each of the jobs we want to monitor(similar to DD queries)
- [x] Which types of monitoring would be useful
- [x] Build the monitoring widgets in DD

## Acceptance Criteria
- [ ] The dashboard is able to display sidekiq job APM/Metrics/logs for the identified jobs 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mchae-nava** [comment]
The scope of this is somewhat reduced until we can confirm with a Canary, but otherwise we should have our monitoring and contingency in place

**Comment by mchae-nava** [comment]
https://vagov.ddog-gov.com/dashboard/mqg-msb-htb/benefits---dbex---evss-to-lh-submit?graphType=flamegraph&refresh_mode=sliding&shouldShowLegend=true&sort=time&spanID=2784910811169879703&view=spans&from_ts=1698439503191&to_ts=1699044303191&live=true

Dashboard deliverable

**Comment by mchae-nava** [comment]
Follow-up action items items noted on the dashboard
