### ISSUE TITLE
[SW] Update intro page

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#65540]
## Issue Description
The intro page needs to be updated to the more detailed version in Sketch.

[Updated Intro Page](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdTZZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4934585b39b0503b75afb42486b82f5fc0cd8f55/2.0%20Authenticated%20-%20desktop.png)

---
## Tasks
- [x] Updated Intro page copy based on approved SW copy

## Acceptance Criteria
- [x] Intro page copy has been updated 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
