### ISSUE TITLE
Create DD Dashboard for Submit endpoint

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#65541]
## Issue Description
Create a DD Dashboard to allow us to monitor 526 claim submission migration to LH 

May have dependency on Steve Albers
---
## Tasks
- [ ] Identify Controller activities from Seth's diagram for monitoring
- [ ] Monitor identified Controller activities in DD
- [ ] Identify Sidekiq jobs for monitoring 
- [ ] Monitoring Sidekiq jobs in DD

## Acceptance Criteria
- [ ] The dashboard is able to display submit requests and response to EVSS and LH
- [ ] The dashboard is able to display sidekiq job APM/Metrics
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
Closing this one in lieu of 3 smaller tickets.
