### ISSUE TITLE
SC | Log KPIs

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#65545]
## Value Statement
**_As a_** software developer
**_I want to_** log KPIs for SC
**_So that_** I have the ability to visualize these KPIs in dashboards, generate reports based on those dashboards, and create alerts relevant to these KPIs.

---
## Background Context

In https://github.com/department-of-veterans-affairs/va.gov-team/issues/57491, Kyle identified the important KPIs for the NOD form, and detailed what we need to log for each of these KPIs. 

In the immediate ticket, we will set up the KPI logging specified in https://github.com/department-of-veterans-affairs/va.gov-team/issues/57491.

## Acceptance Criteria

- [ ] The log data includes relevant information (example: IP address, timestamp, and form input data), as defined by https://github.com/department-of-veterans-affairs/va.gov-team/issues/57491.
- [ ] The log data is stored in a secure and scalable manner, and is easily searchable and accessible to authorized personnel.

## Out of Scope

This ticket is _not_ concerned with visualizing these tickets in a dashboard, setting up alerting and reporting around these KPIs. That will be handled in separate tickets:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/65552
https://github.com/department-of-veterans-affairs/va.gov-team/issues/65556

## Tasks

- [x] Confirm whether or not you have access to the right tools to set that up
- [x] Confirm whether or not the infrastructure allows for that setup
- [x] Notify the team of any dependencies on other upstream services
- [x] Add logging points
- [ ] Review setup with the devs before closing

## Definition of Ready 

- [x] There are clearly defined requirements for logging and monitoring, including what data needs to be captured, and how it will be stored and analyzed.
- [x] We've identified the necessary resources and tools needed to implement the logging and monitoring system, including any third-party software or services.
- [ ] We've agreed on a timeline for implementation and testing, as well as any relevant milestones or checkpoints.
- [ ] We've conducted a feasibility study to ensure that the logging and monitoring system can be implemented within the existing infrastructure and architecture of the online application form.
- [ ] We've created a detailed plan for implementation, including tasks and resource allocation.
- [ ] We've conducted a risk assessment and identified potential challenges or obstacles that may arise during implementation, as well as mitigation strategies.

## Definition of Done

- [x] The logging and monitoring system has been fully implemented and tested in a development environment.
- [x] The system has been integrated with the online application form and is successfully capturing and storing all relevant data.
- [ ] Make revisions to the [Logging and Monitoring Framework](https://docs.google.com/document/d/1TqBQmbYGF7Xvjzs_2q83qDuoKd9022n153wVl8V4MmI/edit#heading=h.wb43vjfgcjqq) as needed.
- [ ] The user story has been reviewed and approved by all relevant stakeholders, including product and development.

**Comment by anniebtran** [comment]
The logging updates were deployed to prod earlier today and seem to be coming into the new dashboard widgets I added 😁 so we can probably close this as the logging should be more in line with the way logs are structured in NOD
