### ISSUE TITLE
NOD | Log KPIs

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#65543]
## Value Statement
**_As a_** software developer
**_I want to_** log KPIs for NOD
**_So that_** I have the ability to visualize these KPIs in dashboards, generate reports based on those dashboards, and create alerts relevant to these KPIs.

---
## Background Context

In https://github.com/department-of-veterans-affairs/va.gov-team/issues/57494, Kyle identified the important KPIs for the NOD form, and detailed what we need to log for each of these KPIs. 

In the immediate ticket, we will set up the KPI logging specified in https://github.com/department-of-veterans-affairs/va.gov-team/issues/57494 (except for prefill info KPIs, which will be addressed separately in https://github.com/department-of-veterans-affairs/va.gov-team/issues/66529).

## Acceptance Criteria

- [x] The log data includes relevant information (example: IP address, timestamp, and form input data), as defined by https://github.com/department-of-veterans-affairs/va.gov-team/issues/57494.
- [x] The log data is stored in a secure and scalable manner, and is easily searchable and accessible to authorized personnel.

## Out of Scope

This ticket is _not_ concerned with visualizing these tickets in a dashboard, setting up alerting and reporting around these KPIs. That will be handled in separate tickets.

## Tasks

- [x] Confirm whether or not you have access to the right tools to set that up
- [x] Confirm whether or not the infrastructure allows for that setup
- [x] Notify the team of any dependencies on other upstream services
- [x] Create logging class with benchmarking methods
- [x] Get contestable issues: add KPI logs
- [x] Overall NOD claim submission: add KPI logs
- [x] Evidence upload (before submission): add KPI logs and StatsD metrics.
- [x] Evidence upload retrieval: add KPI logs and StatsD metrics.
- [x] Evidence Uploads: add KPI logs and make existing StatsD metrics specific to the upload action.
- [x] Figure out how to distinguish existing Evidence Uploads StatsD metrics by form (new metric name? or tag?)
- [x] Automated tests
- [x] Review setup with the devs before closing

## Definition of Ready 

- [x] There are clearly defined requirements for logging and monitoring, including what data needs to be captured, and how it will be stored and analyzed.
- [x] We've identified the necessary resources and tools needed to implement the logging and monitoring system, including any third-party software or services.
- [x] We've agreed on a timeline for implementation and testing, as well as any relevant milestones or checkpoints. (technical discovery may be done by end of sprint)
- [x] We've conducted a feasibility study to ensure that the logging and monitoring system can be implemented within the existing infrastructure and architecture of the online application form. (should be easy - will use staging to test this out)
- [x] We've created a detailed plan for implementation, including tasks and resource allocation. 
- [x] We've conducted a risk assessment and identified potential challenges or obstacles that may arise during implementation, as well as mitigation strategies.

## Definition of Done

- [x] The logging and monitoring system has been fully implemented and tested in a development environment.
- [x] The system has been integrated with the online application form and is successfully capturing and storing all relevant data.
- [ ] Make revisions to the [Logging and Monitoring Framework](https://docs.google.com/document/d/1TqBQmbYGF7Xvjzs_2q83qDuoKd9022n153wVl8V4MmI/edit#heading=h.wb43vjfgcjqq) as needed.
  - I would like to hold off on this until our logging and monitoring is in a better place (i.e. KPI logs and alerts across all our DR forms).
- [x] The user story has been reviewed and approved by all relevant stakeholders, including product and development.
- [x] Make revisions to https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/engineering/backend_KPIs.md.
- [x] Create follow up tickets for benchmark logs and prefill info logging.
  - https://github.com/department-of-veterans-affairs/va.gov-team/issues/67946
  - https://github.com/department-of-veterans-affairs/va.gov-team/issues/66529

**Comment by saderagsdale** [comment]
@data-doge when is this slated to begin?

**Comment by data-doge** [comment]
@saderagsdale I plan on starting this today

**Comment by HeatherWidmont** [comment]
Will remain in code review until @kylesoskin can take a look. Thanks Kyle!

**Comment by anniebtran** [comment]
Rocio and I took a look at this on staging this afternoon — neither of us are super familiar/comfortable poking around in Datadog, so we mostly did a smoke test to make sure that we see some logs when submitting an NOD request, and it looked fine to us. @data-doge could you follow up with more thorough testing? I don't think we covered all the cases for the logs you've added
