### ISSUE TITLE
EVSS - Submit Dashboard - Monitor controller activities 

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#65547]
## Issue Description
Create a DD Dashboard to allow us to monitor 526 claim submission migration to LH 

**Scope** of this ticket is to build dashboard widgets for controller activities that need to be monitored for LH migration release for Submit endpoint

May have dependency on Steve Albers

---
## Tasks
- [ ] Duplicate one of the existing dashboards
- [ ] Replace the controller calls with the identified controller

## Acceptance Criteria
- [ ] The dashboard is able to display traffic, logs and status code to submit controller and response to EVSS and LH

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
