### ISSUE TITLE
EVSS - Discovery - Submit Dashboard - Identify controller activities and Sidekiq jobs

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#65546]
## Issue Description
Create a DD Dashboard to allow us to monitor 526 claim submission migration to LH 

**Scope** of this ticket is to identify controller activities and Sidekiq jobs that need to be monitored for LH migration release for Submit endpoint

---
## Tasks
- [ ] Identify  metrics, jobs, Controller activities from Seth's diagram for monitoring
- [ ] Identify Sidekiq jobs for monitoring
- [ ] Check if we need to build something for LH/EVSS separately?

## Acceptance Criteria
- [ ] List of metrics, jobs, controller activities and Sidekiq jobs for monitoring 
- [ ] Write-up/diagram of why we want to monitor the metrics/activities recommended and how they are related to each other

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sethdarragile6** [comment]
added a new "simplified" [diagram](https://lucid.app/lucidchart/b93a0b4d-c62b-49b0-8efc-c7e9e4a05d1c/edit?viewport_loc=227%2C325%2C2219%2C1047%2CrWlxVOZYEya~&invitationId=inv_a7c98577-e6f5-4ec2-897b-3b0f6212b08d) (the second tab (bottom left) of the page). 

This [inventory](https://docs.google.com/spreadsheets/d/1zWSNAwopCGtoHffLe7jmQ8jrvQyginugCbODJkfF7nI/edit#gid=0) of logging/metrics calls follows the general flow of that diagram.
