### ISSUE TITLE
SC | Build dashboards for KPIs

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#65552]
## Value Statement
**_As a_** software developer
**_I want to_** build dashboards for SC KPIs
**_So that_** I can easily track user behavior, identify issues, and optimize performance.

---
## Background Context

In this ticket, we will visualize the KPIs we began logging in https://github.com/department-of-veterans-affairs/va.gov-team/issues/65545 in DataDog dashboards.

## Acceptance Criteria

- [x] A dashboard has been created to display the log data and facilitate analysis and monitoring of user behavior and performance.
- [x] The dashboard allows for easy filtering and aggregation of log data to identify patterns and trends over time.
- [x] The dashboard includes clear visualizations of the data, such as charts or graphs, to facilitate easy interpretation and analysis.
- [ ] The dashboard allows for drill-down into the data to identify specific areas for improvement and track progress at the user or form level.

## Out of scope

Error monitoring dashboards.

## Tasks

- [ ] Determine what you want to see in a dashboard (visuals, alerts, grouping/ungrouping)
- [ ] Confirm whether or not you have access to the right tools to set that up
- [ ] Confirm whether or not the infrastructure allows for that setup
- [ ] Notify the team of any dependencies on other upstream services
- [ ] Review setup with the devs before closing

## Definition of Ready 

- [ ] There are clearly defined requirements for data visualization.
- [ ] We've identified the necessary resources and tools needed to visualize our KPI data, including any third-party software or services.
- [ ] We've agreed on a timeline for implementation and testing, as well as any relevant milestones or checkpoints.
- [ ] We've conducted a feasibility study to ensure that these dashboards can be implemented within the existing infrastructure and architecture of the online application form.
- [ ] We've created a detailed plan for implementation, including tasks and resource allocation.
- [ ] We've conducted a risk assessment and identified potential challenges or obstacles that may arise during implementation, as well as mitigation strategies.

## Definition of Done

- [ ] The dashboard has been created and is successfully displaying relevant data in an easy-to-read and actionable format.
- [ ] Make revisions to the [Logging and Monitoring Framework](https://docs.google.com/document/d/1TqBQmbYGF7Xvjzs_2q83qDuoKd9022n153wVl8V4MmI/edit#heading=h.wb43vjfgcjqq) as needed and report back to Jared/Kevin.
- [ ] The user story has been reviewed and approved by all relevant stakeholders, including product and development.

**Comment by saderagsdale** [comment]
PR out now.

**Comment by anniebtran** [comment]
We already had some widgets in place for Supplemental Claims, but I've added new ones to utilize the updated logging (now structured similarly to the ones for NOD) that I added in #65545. Will review these widgets with the dev team in our DataDog huddle next Tuesday (4/9)

**Comment by anniebtran** [comment]
Closing now that I've reviewed the new widgets with the dev team and removed the old widgets from the dashboard
