### ISSUE TITLE
NOD | KPI and error alerting

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#65554]
## Value Statement
**_As a_** software developer
**_I want to_** set up KPI and error alerting for the NOD form
**_So that_** quickly identify issues with the NOD form, should they arise

---
## Background Context

In this ticket, we will create alerts to inform us when the KPIs we began logging in https://github.com/department-of-veterans-affairs/va.gov-team/issues/65543 are significantly different from what we expect.

## Acceptance Criteria

- [ ] The logging system generates alerts for any errors or unexpected behavior, such as user input that exceeds acceptable limits or failed form submissions.
- [ ] The alerts are sent to relevant team members via email or other appropriate channels, with clear information about the nature of the issue and how to resolve it.

## Out of scope

N/A

## Tasks

- [x] Determine what kind of alerts we want, who we want to send them to, and how we want to send them.
- [x] Confirm whether or not you have access to the right tools to set that up
- [x] Confirm whether or not the infrastructure allows for that setup
- [x] Notify the team of any dependencies on other upstream services
- [ ] Review setup with the devs before closing

## Definition of Ready 

- [x] There are clearly defined requirements for alerting, including what kind of alerts we want, who we want to send them to, and how we want to send them.
- [x] We've identified the necessary resources and tools needed to implement the logging and monitoring system, including any third-party software or services.
- [x] We've agreed on a timeline for implementation and testing, as well as any relevant milestones or checkpoints.
- [x] We've conducted a feasibility study to ensure that the logging and monitoring system can be implemented within the existing infrastructure and architecture of the online application form.
- [x] We've created a detailed plan for implementation, including tasks and resource allocation.
- [x] We've conducted a risk assessment and identified potential challenges or obstacles that may arise during implementation, as well as mitigation strategies.

## Definition of Done

- [ ] The system is generating alerts for any errors or unexpected behavior and relevant team members are being notified in a timely manner.
- [ ] Make revisions to the [Logging and Monitoring Framework](https://docs.google.com/document/d/1TqBQmbYGF7Xvjzs_2q83qDuoKd9022n153wVl8V4MmI/edit#heading=h.wb43vjfgcjqq) as needed and report back to Jared/Kevin.
- [ ] The user story has been reviewed and approved by all relevant stakeholders, including product and development.

**Comment by saderagsdale** [comment]
@data-doge does this need refinement and estimation or can we remove the labels?

**Comment by data-doge** [comment]
Notes for these coming alerts

Action | Alert type | Alert metric
-- | -- | -- | --
Get Contestable Issues | Low traffic | `decision_review.form_10182.get_contestable_issues.success`
Get Contestable Issues | Error | `decision_review.form_10182.get_contestable_issues.failure`
Overall NOD Claim Submission | Low traffic | `decision_review.form_10182.overall_claim_submission.success`
Overall NOD Claim Submission | Error | `decision_review.form_10182.overall_claim_submission.failure`
Evidence Upload (before submission) | Low traffic | `decision_review.form_10182.evidence_upload_to_s3.success`
Evidence Upload (before submission) | Error | `decision_review.form_10182.evidence_upload_to_s3.failure`
Evidence Upload Retrieval | Low traffic | `decision_review.form_10182.evidence_upload_retrieval.success`
Evidence Upload Retrieval | Error | `worker.decision_review.submit_upload.error`
Get LH Upload URL | Low traffic | `decision_review.form_10182.get_lighthouse_evidence_upload_url.success`
Get LH Upload URL | Error | `worker.decision_review.submit_upload.error`
Evidence Uploads | Low traffic | `decision_review.form_10182.evidence_upload_to_lighthouse.success`
Evidence Uploads | Error | `worker.decision_review.submit_upload.error`


One note for the Get Contestable Issues Error alert, right now we get a lot of noisy errors (401s, 403s, 404s) on this endpoint, which I think is in part due to our calling this endpoint at the start of the form, rather than on the relevant step only. That will be resolved in https://github.com/department-of-veterans-affairs/va.gov-team/issues/66954, and until then, I think we will want to avoid alerting on this metric and instead rely on the low traffic one

**Comment by saderagsdale** [comment]
Eugene will review evidence upload issue related to failures w/ Central Mail Portal. May result in changes.

**Comment by saderagsdale** [comment]
@data-doge  will finish later today. Wants to setup anomaly detection alerts to catch errors sooner.

**Comment by data-doge** [comment]
Reviewed with devs, closing.
