### ISSUE TITLE
[UX][Design] DS v3 #4: Update additional info components

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#65566]
## Background
Additional info components also need to be updated as part of the v3 switch. Design System v3 Components have been prioritized in the [#64010 Design System v3 ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64010). 

## Tasks
- [ ] Update the Design pages of the Unified check-in, Check-in, and Pre-Check-in files
    - [ ] Identify screens that use additional info components
    - [ ] Update the corresponding symbols in these files with the new Component Library Sketch component (see ticket [#64010 Design System v3 ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64010) for more info on setting up the new Sketch library)
    - [ ] Check all Design page boards to make sure they're updated in case of detached symbols
- [ ] **Sync with FE engineers** to make sure they're all set on toggling the additional info component to the new version

## Acceptance Criteria
- [ ] Additional info components are updated in unified, Check-in, and Pre-Check-in Design page files
- [ ] FE is set to toggle to v3 of this component

**Comment by cgednalske** [comment]
@benbrasso-agile6 @ytsaoca here's the additional info ticket. Let me know if I missed anything! I'll do a button one separately, unless we prefer they're combined?

**Comment by benbrasso-agile6** [comment]
Looks good to me, @loripusey do you want to replace this ticket for [this alerts ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64829#issuecomment-1718332813) in our sprint goals?

**Comment by loripusey** [comment]
So, you mean take out the alerts ticket and replace it with this one?

**Comment by benbrasso-agile6** [comment]
Yes please

We have to wait on doing the alerts because we can’t have some v2 and some v3 in the application

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/65566?planning-poker) with Zenhub @cgednalske @kellysmith1008 @ytsaoca @zach-park

**Comment by ytsaoca** [comment]
@zach-park The unified part is ready for review: https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/E4F79FDB-972A-4FA1-9F0D-3D79A76ACBFA/canvas

Working on other files

**Comment by ytsaoca** [comment]
Wireframes are ready for review:

- The unified -  https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/E4F79FDB-972A-4FA1-9F0D-3D79A76ACBFA/canvas
- Pre-check-in - https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/p/619C8F80-605B-4E41-964F-3C17D5010D12/canvas
- Check-in - https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/p/A815478C-BC20-4F8B-8F97-E82777608C5D/canvas

**Comment by zach-park** [comment]
Hi @Ya-ching, Unified and Check-in are validated. 
As for the Pre-check-in, I had a question about it. I think it's due to the DS component bug. Anyhow, I left some comments, so please look into it if you would. Thank you!

**Comment by zach-park** [comment]
Pre-check-in is also validated.

**Comment by ytsaoca** [comment]
Updated the design pages
