### ISSUE TITLE
Contact Center Review - Create Product Guide 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#6557]
### Step 1: Create the Product Guide

*If you're building a brand new service*:

  1. Create a Product Guide that covers all the functionality, the main user flow(s), any error conditions, and how the user can resolve those errors.
  1. The Product Guide must be a Word document or a PDF.
  1. Create a new folder in your team's Product folder called ```Contact Center.``` Store the Product Guide there.

*If you're building new features for an existing service*:

  1. You'll need to update the existing Product Guide.
      * If you can't find the existing Product Guide on Github, ask your Contact Center POC to find it for you.
  1. Store the updated Product Guide in its original location.

*Examples*:

[Example Product Guide 1](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/templates/sample-product-guide-1.pdf)

[Example Product Guide 2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/templates/sample-product-guide-2.pdf)

## Tasks
- [x] Create product guide
- [x] Create happy path video
- [x] Create common errors video
- [x]  Create transcripts of the videos

**Comment by mr0sari0** [comment]
[Here](https://docs.google.com/document/d/1GnNWLn5UKsD2U_WYIoOmq3JcXdg38xGGG4BL6FZOE3o/edit?usp=sharing) is the product guide.

 [Here](https://slack-files.com/T03FECE8V-F015MP02MQ8-91b6d71908) is the happy path video walkthrough.

[Here](https://github.com/department-of-veterans-affairs/va.gov-team/files/4765260/Happy.Path.Video.Transcript.docx) is the happy path video transcript.

[Here](https://slack-files.com/T03FECE8V-F01504H5K9U-072a312ac8) is the common errors/ alt experiences video.

[Here](https://github.com/department-of-veterans-affairs/va.gov-team/files/4765276/Common.Alt.Errors.and.Experiences.Video.Transcript.docx) is the common errors/ alt experiences video transcript.

**Comment by mr0sari0** [comment]
Updated Github with the product guide doc.
