### ISSUE TITLE
Evaluate Lighthouse API for Existing Representative Info

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#65577]
### Issue Description

We need to evaluate the capabilities of Lighthouse's existing API to see if it can return the last active Power of Attorney (POA) for a veteran. This is crucial for displaying existing representative information to authenticated users.

See https://developer.va.gov/explore/api/benefits-claims/docs?version=v1#operations-Power_of_Attorney-post2122 

---
### Tasks
- [ ] Review Lighthouse API documentation related to POA information.
- [ ] Search the va.gov codebase to see if the Lighthouse API is already used somewhere
- [ ] Conduct initial tests to assess the API's ability to fetch POA data.
- [ ] Compile findings in a technical document.

### Acceptance Criteria
- [ ] A document is produced outlining the capabilities of the Lighthouse API with regard to fetching POA data, and recommendations on its integration into our system.

**Comment by oddball-lindsay** [comment]
No longer needed
