### ISSUE TITLE
Implement Representative Type Selection

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#65588]
### Issue Description
To help users find the most suitable representatives, we need to allow them to select the type of representative they're looking for.  Options include:

1. Veteran Service Organization (VSO)
2. Representative in a Veteran Service Organization
3. Attorney (Lawyer)
4. Claims agent

---
### Tasks
- [ ] Create a UI radio button list to allow users to select the type of representative.
- [ ] Implement backend logic to filter search results based on the selected type.
- [ ] Write unit tests to ensure that the type selection filters the search results correctly.

### Acceptance Criteria
- [ ] Users can select the type of representative they're looking for, and the search results are filtered accordingly.
- [ ] The feature is covered by unit tests confirming its functionality.

**Comment by holdenhinkle** [comment]
This work is implied in another ticket. Closing this one.
