### ISSUE TITLE
Error traces should show up in Datadog

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#65585]
## Issue Description
Right now the [Datadog Error Tracking](https://vagov.ddog-gov.com/apm/error-tracking) view is very sparse compared to Sentry - meaning there's no easy way to see an overview of current errors happening on the backend. 

Per [this discussion](https://dsva.slack.com/archives/C05644VUZ6X/p1694614299509259), it looks like because the vets-api application controller catches exceptions and renders JSON errors, but does not re-raise those exceptions, they are invisible to Datadog. 

---
## Tasks
- [ ] Update vets-api to set error tags on the Datadog Span object for errors that we wish to report (basically the same set as we are currently reporting to Sentry in the application controller level. 

## Acceptance Criteria
- [ ] Error traces will show up in the Datadog Error Tracking view. 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
