### ISSUE TITLE
Implement Default Search Radius

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#65586]
### Issue Description
To streamline the user experience, we need to implement a default search radius that will be used when users search for representatives by location.

The default search radius should be 50 miles, but if no results are found within 50 miles, expand the search radius (incrementally by mile) until users have at least 10 results.

NOTE: This could very well have been handled already in [Implement Location-based Search for Representatives#65583](https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/65583)

---
### Tasks
- [ ] Add a default radius setting in the backend logic for searching representatives.
- [ ] Display the default radius on the frontend, allowing users to see the range of their search.
- [ ] Write unit tests to ensure the default radius is correctly applied in search results.

### Acceptance Criteria
- [ ] When a user performs a location-based search, the system automatically uses a default radius (e.g., 50 miles).
- [ ] The default radius is clearly displayed to the user.
- [ ] The feature is covered by unit tests confirming its functionality.

**Comment by oddball-lindsay** [comment]
This implementation is essentially implied with the development for search - do not need a specific ticket
