### ISSUE TITLE
Implement Tooltips for Representative Definitions

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#65589]
### Issue Description
To assist users in making informed decisions, we need to display definitions for different types of representatives. Tooltips will be used for this purpose and be connected to the issue: [Implement Representative Type Selection #65588](https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/65588).

---
### Tasks
- [ ] Work with the team to gather definitions of the representative types (Veteran Service Organization (VSO), Representative in a Veteran Service Organization, Attorney (Lawyer), Claims agent).
- [ ] Design and implement tooltips next to each representative type on the selection list.
- [ ] Populate tooltips with the definitions for each type of representative.
- [ ] Write unit tests to verify that the tooltips display the correct information.

### Acceptance Criteria
- [ ] Definitions for Veteran Service Organization (VSO), Representative in a Veteran Service Organization, Attorney (Lawyer), and Claims agent should be easily accessible to the user via tooltips.
- [ ] Tooltips should display when hovered over and disappear when not in focus.
- [ ] The feature is covered by unit tests confirming its functionality.

**Comment by oddball-lindsay** [comment]
We are no longer moving forward with the tool tip concept, as it's tough for accessibility.
