### ISSUE TITLE
Implement 'Use My Location' Feature in Search

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#65584]
### Issue Description
To enhance user experience, we will add a 'Use My Location' feature that populates the location input field automatically based on the user's current location.

Discovery for this was done here: https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/65579

---
### Tasks
- [x] Implement the 'Use My Location' button next to the location input field.
- [x] Integrate geolocation API to fetch the user's current city, state, and zip code.
- [x] Loading spinner while geolocation in progress
- [x] Populate the location input field with the retrieved data when 'Use My Location' is clicked.

### Acceptance Criteria
- [ ] The 'Use My Location' feature is fully functional and populates the location input field with accurate data.

**Comment by oddball-lindsay** [comment]
Mapbox is not working as expected, could be related to the URL

**Comment by oddball-lindsay** [comment]
Still need unit tests

**Comment by holdenhinkle** [comment]
The "Populate the location input field with the retrieved data when 'Use My Location' is clicked." task is not complete. Moving it back to in-progress.

**Comment by oddball-lindsay** [comment]
Updated to use the environment variable that the Facilities Locator is using.  Also added a loading indicator and alert.
