### ISSUE TITLE
Implement Location-based Search for Representatives

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#65583]
### Issue Description
We need to implement a search functionality where users can input their location to find representatives. The location will be a single consolidated field that accepts various components of an address (address 1, city, state, zip code).

Discovery for this was done here: https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/65578

---
### Tasks
- [ ] Create a UI component for the location input field.
- [ ] Implement backend logic to search for representatives based on the location information provided.
- [ ] Integrate this search functionality with the Facility Locator service, if applicable.
- [ ] Write unit tests to ensure the new search functionality works as expected.

### Acceptance Criteria
- [ ] Users can input their location in a single consolidated field.
- [ ] Based on the location entered, a list of representatives near that location is displayed.
- [ ] The feature is covered by unit tests confirming its functionality.

**Comment by oddball-lindsay** [comment]
Break into smaller pieces: getting the data, adding latitude/longitude, adding job to validating addresses, looking for changes in addresses

**Comment by holdenhinkle** [comment]
This ticket is too general. Other tickets have been written in its place. Closing...
