### ISSUE TITLE
Research In-Progress Forms on vets-website

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#65581]
### Issue Description
We need to explore how in-progress forms are managed in the `vets-website` frontend. This information will guide the implementation of our frontend application for saving and resuming form submissions when searching for representatives.

---
### Tasks
- [ ] Investigate existing code and practices for managing in-progress forms on `vets-website`.
- [ ] Understand any existing frontend conventions or libraries used for saving forms.
- [ ] Document the technical details, limitations, and recommendations in a report.

### Acceptance Criteria
- [ ] A document is available outlining the frontend practices for managing in-progress forms on `vets-website`, and it includes recommendations on how to implement this feature in our search for representatives application.

**Comment by cosu419** [comment]
**Configure naming/messaging options in the form config**
- `formId`: Key is used to save form data in vets-api. It’s usually set to the VA form number associated with the paper form.

- `saveInProgress`: An object containing several options, the most commonly used configuration option being messages. For a full list of available settings check out the `formConfig` options page.

- `savedFormMessages`: Messages sent to the SiP component.

**Make the SiP form retrievable on the User Profile page**

1. Add the form ID to the `VA_FORM_IDS` object in the `/platform/forms/constants` file

2. In the personalization dashboard helpers file, form information found in the `formConfig` should be added to the following objects:

- `formBenefits` - property name imported from the `VA_FORM_IDS` object with a string value 

- `formLinks` - property name imported from the `VA_FORM_IDS` object with a value that calls the function getAppUrl. The parameter passed to `getAppUrl` is the entryName of the application specified in the registry.json file in the content-build repository. Example: [VA_FORM_IDS.FORM_21_686C]: `${getAppUrl('686C-674')}/

- `trackingPrefixes` - property name imported from the `VA_FORM_IDS` object with a string value that’s identical to the trackingPrefix property found in the `formConfig` of the form being worked on. 
- Example: [VA_FORM_IDS.FORM_21_526EZ]: 'disability-526EZ-' and corresponding trackingPrefix property in formConfig

- `sipEnabledForms` - property name imported from the `VA_FORM_IDS` object

**Configuring prefill**
1. Add a key in the `formConfig` object called `prefillEnabled`

2. Hook the `formConfig` setting by passing it to the SaveInProgress component. The property `prefillEnabled` has to be set using the `true` value from the `formConfig` object above.

3. In the VA Forms Library there are also some helper functions created around pre-fill that could be useful to better organize pre-fill data. One of those helpers is a `prefillTransformer`, which can be used to take in a pre-filled form data object, restructure it, and return the new object to be used in the form.
