### ISSUE TITLE
Research In-Progress Forms on vets-api

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#65580]
### Issue Description
We need to understand how in-progress forms are created, managed and saved in the `vets-api`. This will allow us to develop a robust mechanism for users to save and resume their form submissions when searching for representatives.

We suspect the `vets-api` system may be using something like the following to save form information:

- Create table
  - user_id foreign key
  - With columns, type bool, for the following form questions
      - Section 19: Authorization for representative’s access to records protected by Section 7332, Title 38, U.S.C. (checkbox)
    - Section 20: Limitation of consent (checkboxes)
      - Drug abuse
      - Alcoholism or alcohol use problems
      - Human immunodeficiency virus
      - Sickle cell anemia
    - Section 21: Authorization to change claimant’s address (checkbox)
  - With selected rep identifier
 
Here's the related frontend ticket - https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/65581

---
### Tasks
- [ ] Examine the existing codebase and database schema for managing in-progress forms in `vets-api`.
- [ ] Perform test scenarios to understand how data is saved and retrieved.
- [ ] Consider the specific requirements for creating a table with boolean columns to store information about form questions
- [ ] Document the technical details, limitations, and recommendations in a report.

### Acceptance Criteria
- [ ] A comprehensive document is available that describes how in-progress forms are managed in vets-api, including technical requirements for implementing this feature in the representative search application.
- [ ] The document should specifically address the feasibility of creating a table with boolean

**Comment by cosu419** [comment]
The majority of the vets-api work here is configuring pre-fill, which is a simple API call to populate pre-existing form data. Here are the steps involved:

1. Add application pre-fill to the ALL_FORMS object in the form_profile file
2. In the same file, adjust the FORM_ID_TO_CLASS object and map our new pre-fill application to its corresponding FormProfile
3. Create FormProfile file that defines a metadata object that holds the version, the pre-fill boolean, and the returnUrl
4. Create a Form_Profile_Mapping file for the data that should be pre-filled
5. In the Vets-API settings.yml file, update relevant pre-fill boolean settings
6. Add a test which includes the list of prefilled IDs
