### ISSUE TITLE
Implement Display of Existing Representative for Authenticated Users

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#65582]
### Issue Description
For users who are authenticated and have an existing representative (POA), we need to display this information. The data for the existing representative will be fetched using the Lighthouse API.

Discovery for this issue was handled here: https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/65577

---
### Tasks
- [ ] Integrate the Lighthouse API to fetch the existing representative (POA) information.
- [ ] Implement the frontend logic to display the existing representative if one is found.
- [ ] Add an informational section on how to change the existing representative.
- [ ] Write unit tests to ensure the new functionality works as expected.

### Acceptance Criteria
- [ ] If a user is authenticated and has an existing representative, that information is correctly displayed.
- [ ] An option or guidance is available on how to change the existing representative.
- [ ] The feature is covered by unit tests confirming its functionality.
