### ISSUE TITLE
[UX][Design] Create Lo-Fi Wireframe Structure for Past Appointments

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#65594]
While we work on [scope discovery](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65592) and [back-end user flows](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65593) for travel reimbursement for past appointments, we need to understand what parts of the userflow (Veteran-facing) screens we already have a handle on, in the form of complete or proposed designs, and begin to construct a low-fi wireframe flow with the available screens.

[Link to 18F designs]

## Tasks
- [ ] Create lo-fi wireframes for discovery purposes
- [ ] Identify what design work will still need to be done 
- [ ] Share with Kristen and UX
- [ ] Work with Kristen to determine what design work should be done by PCI or Appointments team
- [ ] Create f/u tickets

## AC
- [ ] Initial lo-fi wireframe structure created
- [ ] PCI vs. Appointments team roles have been clarified for next design steps 
- [ ] F/u tickets created

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/65594?planning-poker) with Zenhub @cgednalske @kellysmith1008 @ytsaoca @zach-park

**Comment by loripusey** [comment]
@cgednalske does this need to rollover or is it done?
@benbrasso-agile6

**Comment by benbrasso-agile6** [comment]
We pulled the research plan out midsprint, as a result of the meeting about travel with Kay and Kristen. Then, pulled this ticket in as a result. Rollsover.

**Comment by loripusey** [comment]
I remember now, thanks for the refresher.

**Comment by cgednalske** [comment]
Initial user flow is complete ([Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695774555765/73dec2c323f80ae6cb2a6e0a646221e2aeb680c4?sender=ua2ec2e34eb6128f3375e0207)) and we met with Sara Sterkenburg to go over it. Meeting with Kristen tomorrow to review. 

@benbrasso-agile6 the user flow itself is ready for validation, but does the ticket need to wait for validation until we've completed the other tasks above surrounding team roles?

**Comment by benbrasso-agile6** [comment]
That's fine. We can complete the other tasks tomorrow after chatting with Kristen. Nice work.

**Comment by benbrasso-agile6** [comment]
**Next steps from talking with Kristen**

Complete as part of this ticket: 

- [ ] @benbrasso-agile6 message Mark in slack about address logic
- [ ] @cgednalske to add back in Notifications path(s), e.g., to help other teams make the case that in app notifications could be helpful to Veterans
- [ ] @benbrasso-agile6 to set up some time to meet with Lauren and Misty to share our work and collab. More informational sharing and Vet experience alignment. (Just toss something on the calendar.) 
- [ ] @cgednalske to finish up research plan questions. Which questions could fit in Liz's broader research? Which questions are more specific to check in and Auth experience? 
- [ ] @benbrasso-agile6 set up meeting with Appointments design team to introduce them to our work and begin to brainstorm a bit on roles and responsibilities (e.g., who's doing design? who's doing prototype? who's doing research plan? and later on, who's moderating research sessions?) 
- [ ] After we've spoke to the Appointment designers, then we loop in Lori, Kay, and Kristen to discuss how roles and responsibilities align with each teams' existing priorities. E.g., ux team on check in might have more bandwidth, so maybe we take on more of the work. So, @benbrasso-agile6 to set up that meeting later. 
- [ ] @benbrasso-agile6 message Liz S on Mobile to have a meeting to understand what they're thinking about for a research study, e.g., do we have similar questions to answer? is there something we're curious about that's better fit to be included in her study? 

Potential tickets for next sprint (but have some dependencies on the above) (I'm not going to create the tickets quite yet, but I guess we might need to for planning. @cgednalske which of these do you think we'd want to prioritize and are likely for us to work on vs. Appointments for next sprint?)

- Would we want to start something in CodePen?
- Would we want to start wireframing in parallel with CodePen? (Would it be LoROTA, full auth or both?) 
- Draft research plan 
- Prepare and schedule design intent (but, this could be through the Appts team)
- Looks like the collab cycle changed a bit, we might need to more officially [prepare and schedule CAIA intake ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request), even though we met with Sara S already. So, maybe prepare and submit CAIA intake ticket. (But, again, we need to work with Appts team.)

cc @loripusey

**Comment by benbrasso-agile6** [comment]
Messaged Mark, waiting for response

**Comment by cgednalske** [comment]
Notifications added back into the [userflow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695774555765/73dec2c323f80ae6cb2a6e0a646221e2aeb680c4?sender=ua2ec2e34eb6128f3375e0207) on MyVA and MHV pages

**Comment by benbrasso-agile6** [comment]
Yeah, that looks good

**Comment by benbrasso-agile6** [comment]
From Mark: 

>Q: If a Veteran enters an address that is not their home address that we have on file, what happens to the claim?
>A: The rules engine will throw an error and the claim will go into manual review. The Mileage expense record is checked against the home address and the Facility of the claimant.

So, we're covered, re: changing the address, so long that it can be async saved to Profile.

**Comment by loripusey** [comment]
What do you mean by "enter an address"? Nowhere do we have the Veteran enter an address. I'm not understanding the context of Mark's question.

**Comment by benbrasso-agile6** [comment]
Kristen had a question about how BTSSS checks the traveled from address. What Mark was confirming is that, if and so long that we change the home address in Profile async with or before submitting a BT claim, there should be no issues when the claim gets reviewed by the BTSSS logic rules.

**Comment by benbrasso-agile6** [comment]
@cgednalske, I set up meeting with Misty and Lauren. I think the agenda I added sets the stage for what we want to discuss. Start to think about what we should cover with them during our info-sharing... it'll be a short meeting. E.g., where do we have specific questions or user flow decisions that we'd like them to provide feedback on or validate? Might be helpful to point out some specific decisions of ours to them to help narrow in on the feedback we're looking for.

**Comment by benbrasso-agile6** [comment]
@cgednalske i'm going to see if we have a few moments to connect today to prep for refinement tomorrow, re: https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/65594#issuecomment-1739996814

**Comment by benbrasso-agile6** [comment]
@kristenmcconnell
