### ISSUE TITLE
Implement Frontend Logic for In-Progress Forms

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#65591]
### Issue Description
For enhanced user experience, the frontend needs to support in-progress form saving functionality. This will allow users to resume their search for a representative without losing previously entered information.

Discovery for this was done here: https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/65581

---
### Tasks
- [ ] Implement frontend logic to save the form's current state when the user chooses to do so.
- [ ] Create a UI prompt that informs users their form can be saved and resumed later.
- [ ] Write unit tests to verify that the form's state is correctly saved and can be resumed.

### Acceptance Criteria
- [ ] Users should be able to save and resume in-progress forms.
- [ ] A UI prompt is displayed, guiding users on how to save and resume their form.

**Comment by oddball-lindsay** [comment]
Leaning on one form IDs for Save In Progress, as there will be "Finish this form later" before we know what form we need to fill out.

Multiple IDs have been created, but we can just ignore what we don't need.
