### ISSUE TITLE
[FE] DS v3 #5: Update buttons

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#65597]
## Background
The Design System has moved to version 3. We need to move the button components we have that use the Design System to use version 3.

Switch to button pair for Yes and No buttons - https://design.va.gov/storybook/?path=/docs/uswds-va-button-pair--default

Switch to primary button for single buttons, such as "Check In Now" - https://design.va.gov/storybook/?path=/docs/uswds-va-button--primary
  
## Tasks
- [ ] [FE] **Update buttons for DS v3**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
@benbrasso-agile6 perhaps submit some bug tickets to DS?

**Comment by benbrasso-agile6** [comment]
@loripusey this ticket is good to go for FE, whenever they're ready

**Comment by brianseek** [comment]
The va-button-pair was unable to be used to to issues with translation and button text. Tickets with DS filed:
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2362
&
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2364

**Comment by loripusey** [comment]
I'm going to put this back in the backlog and we'll check on the DS progress at a later time

**Comment by loripusey** [comment]
Was there work done on the primary (non-pair) buttons? @brianseek

**Comment by loripusey** [comment]
I added a ticket to the backlog and our tech debt epic for switching the button pairs; included Brian's note with the links to the 2 DS tickets
https://github.com/department-of-veterans-affairs/va.gov-team/issues/73079

**Comment by brianseek** [comment]
I also added a ticket in the backlog to do some additional component swapping on unified: https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/73122

**Comment by brianseek** [comment]
@benbrasso-agile6 / @cgednalske / @ytsaoca / @zach-park / @kellysmith1008 
This isn't merged yet, but I wanted you to get a chance to see the button component in place before merging, just to make sure it all looked correct. Attached are screenshots of the pages with buttons. Also if you wanted to see this on your local instance you can do the following steps:

 - Open vscode to the check-in directory
 - open a new terminal and type `git checkout check-in/65597/v3-buttons`
 - type `git status` and make sure it says
``` 
On branch check-in/65597/v3-buttons
Your branch is up to date with 'origin/check-in/65597/v3-buttons'.
nothing to commit, working tree clean 
```
 - run the local mocks command
 - in another terminal, run the start app command
 - now your local should showing the buttons branch
 [screenshots-with-buttons.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU9xQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--33574569b0b84b3aa8359cbf48b4c3bf4caae8a6/screenshots-with-buttons.zip)

**Comment by brianseek** [comment]
actually in reviewing the screenshots, there is a weird spacing thing on the full width single buttons. I have a fix, I'm going to try and will upload new screenshots

**Comment by brianseek** [comment]
ok screenshots link has been updated

**Comment by benbrasso-agile6** [comment]
<img width="640" alt="Screenshot 2024-01-09 at 8 19 41 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/101129355/03034682-e6f6-4fd8-ac7b-f86711b37755">

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 Before you type Brian's commands above, when you're in the check-in directory, run `git pull` - that'll get you any updates. Then run Brian's commands - worked for me that way

**Comment by benbrasso-agile6** [comment]
Nice, I got it :) TY

**Comment by benbrasso-agile6** [comment]
@brianseek Did you want to change the Refresh button on the, I think, /details/ page

**Comment by benbrasso-agile6** [comment]
I think I reran the same commands when that failed and it worked the next time I did it @kellysmith1008 but I got a similar error too. Eventually, got it running.

**Comment by brianseek** [comment]
@kellysmith1008 / @benbrasso-agile6 I am going to PL a next steps with local env. to figure out a meeting time to discuss some more of this in person. But sometimes when you see weird errors like that, you will need to run a new `yarn install`

@benbrasso-agile6 the refresh button is updated, its just not using the big button variation. Do you think it should?

**Comment by benbrasso-agile6** [comment]
Hmmm, I feel like the "button pairs" _and_ our refresh button should be the same variation. @cgednalske @ytsaoca @kellysmith1008 @zach-park Thoughts?

**Comment by cgednalske** [comment]
Agreed! (assuming we're referring to the fact that the refresh looks smaller right now)

**Comment by benbrasso-agile6** [comment]
Yes, that's exactly what I was referring to.

**Comment by brianseek** [comment]
that makes sense to me. I'll update it. It didn't get that treatment in this update because the old button wasn't the big variant.

**Comment by brianseek** [comment]
is everyone good with this getting merged after that update?

**Comment by brianseek** [comment]
you should be able to see the update in your locals if you do a `git pull` command

**Comment by benbrasso-agile6** [comment]
<img width="634" alt="Screenshot 2024-01-09 at 11 07 41 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/101129355/4bbfa5ee-7859-489e-89a6-15a17a6ba9ea">

**Comment by benbrasso-agile6** [comment]
_Running local kinda slick_

I say after working on this contract for 2 year

**Comment by brianseek** [comment]
local development is pretty neat, I'm glad its working out for you all. So does this look good to go?

**Comment by brianseek** [comment]
code is merged, moving to closed since this was pre-validated by UX. Thanks all!
