### ISSUE TITLE
[UX] Create visual back-end userflow for past appointments

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#65593]
The team is interested in moving towards allowing Veterans to file for travel reimbursement for past appointments. To fully understand any blockers and dependencies, UX and Mark Dewey will create a low-fi visual userflow to clarify how this will work for past appointments. 

Should be able to complete this agnostic of within the context of PCI and/or Appointments/VAOS (at least, I think). 

[Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1694530929649/38caa40c4c6f70516ff2c784b4ff1b5514490e75?sender=ua2ec2e34eb6128f3375e0207)

## Tasks
- [ ] Decide whether to use mural, sketch or both (mural might be better for other teams to access)
- [ ] Create visual back-end userflow
- [ ] Share with team
- [ ] Create f/u tickets

## AC

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/65593?planning-poker) with Zenhub @cgednalske @kellysmith1008 @ytsaoca @zach-park
