### ISSUE TITLE
Implement Backend Logic for In-Progress Forms

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#65590]
### Issue Description
For enhanced user experience, the backend needs to support in-progress form saving functionality. This will allow users to resume their search for a representative without losing previously entered information.

Discovery for this was done here: https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/65580

Platform also has some instructions to be referenced here: https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-set-up-save-in-progress-si
Any questions about this can be asked in the #accountexp-authexp Slack channel

---
### Tasks
- [ ] Design the database schema to store in-progress forms with the necessary fields.
- [ ] Implement backend logic to save the form's current state, including selected representative type and location.
- [ ] Write unit tests to verify that the form's state is correctly saved and can be resumed.

### Acceptance Criteria
- [ ] Able to save, update, and fetch in-progress forms with the necessary fields.

**Comment by holdenhinkle** [comment]
Link to Google Doc with notes from Josh Fike - https://docs.google.com/document/u/1/d/1oov4DnxeaPcY66e4eVsLJ7zkcggv06PBx7Ve0BfguKI/edit#heading=h.mb22ieextc8v

**Comment by oddball-lindsay** [comment]
Plan is to do a small test to confirm that the frontend manages in-progress forms.

**Comment by opticbob** [comment]
Test

**Comment by oddball-lindsay** [comment]
No longer needed, will implement on the frontend.
