### ISSUE TITLE
DR | Set up basic dashboards and alerts for SC, HLR, and NOD

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#65605]
## Issue Description

In the wake of https://github.com/department-of-veterans-affairs/va.gov-team/issues/64802, Steve and our team agreed to set up basic dashboards and alerts for our DR forms, to catch and alert on wide variations in submissions that may be caused by bugs undetectable through traditional error monitoring.

Steve is going to create template dashboards/alerts for us, and it will be our job to configure them specifically for our forms.

## Out of Scope

This ticket isn't about creating full-fledged, comprehensive dashboard and alerts for each of our forms. It is only concerned with a _baseline_ level of dashboards and alerts that will specifically inform us of wide variations in form submissions, so that we aren't blindsided by bugs like the infinite loop bug going forwards.

In the future, we're planning to build comprehensive (and not just baseline-level) dashboards and alerting for our forms. See https://github.com/department-of-veterans-affairs/va.gov-team/issues/57505#issuecomment-1718313854, https://github.com/department-of-veterans-affairs/va.gov-team/issues/57502#issuecomment-1718314652, and https://github.com/department-of-veterans-affairs/va.gov-team/issues/57501#issuecomment-1718315352.

## Tasks
- [x] Steve creates template dashboards / alerts in DataDog
- [x] Eugene configures dashboards specifically for our forms
- [x] Engineers agree on an alert threshold and team agrees on a list of folks to alert.
- [x] Eugene configures alerts accordingly.
- [x] Eugene gets Steve's review and approval of dashboards / alerts

## Acceptance Criteria
- [x] Dashboards track number of form submissions for each form
- [x] Dashboards trigger alert to relevant team members
- [x] Engineers and Steve agree with configuration

## Definition of Ready
- [x] Steve creates template dashboards / alerts in DataDog for us
- [x] Steve gives me DataDog write access

## Definition of Done 
- [x] Everything in acceptance criteria done
- [x] Eugene sets up schedule to check in on dashboards and alerts twice a week until we receive our first alert confirming that alerting does indeed work as expected.

**Comment by saderagsdale** [comment]
@va-albers Hey Steve, are the templates in DD ready for us to customize them?

**Comment by data-doge** [comment]
Steve provided the templates! Thank you Steve.

I'll start posting the completed dashboards here:
- [NOD Dashboard](https://vagov.ddog-gov.com/dashboard/tvp-imf-tb7/benefits---notice-of-disagreement?refresh_mode=sliding&from_ts=1694440303027&to_ts=1695045103027&live=true)

**Comment by data-doge** [comment]
Steve says that he doesn't need to review our dashboards/alerts for us to move forward, he just wants to do a check-in and some point to see how things are going. I'll schedule that.

**Comment by data-doge** [comment]
Added Form 4142 and ITF dashboards and alerts. Updated comment above with links. Moving this ticket to "Validate"

**Comment by data-doge** [comment]
Marking this closed. Alerts are being sent to all engineers (except ITF, which will only be sent to me until, in future tickets, we parse out DR ITF traffic from 526 ITF traffic).
