### ISSUE TITLE
NOD | Notify Veterans about form error

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#65606]
## Value Statement
**_As a_** Veteran who attempted to submit an NOD while the infinite loop bug was in production
**_I want to_** know the outcome of my failed attempt to submit an appeal
**_So that_** I can take action on my appeal

---
## Background Context
Part of the remediation effort involves sending notifications to veterans, so they understand exactly how the infinite Loop bug affected their attempt to submit an appeal. Because the bug took place during a PACT deadline, the VA wants veterans to know what their options are going forward.

Some users may not have verified their profiles, thus no ICN. They could not have submitted the form. 

## Acceptance Criteria
- [ ] Passes UAT before going to real users
- [ ] Given that a list of Veterans is provided, when the email is triggered, they receive a message with the expected copy (linked below)
- [ ] Given that an email is provided, when the email is triggered, it is delivered to the expected recipient
- [ ] Logs are generated for each trigger activation and that errors or issues are promptly reported

## Designs and Build Notes
- [Doc for drafting the NoD notification](https://dvagov.sharepoint.com/sites/vaabdvro/_layouts/15/doc.aspx)
- [VA Notify ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65509)

## Open questions
- Any specific conditions or event triggers we want to call out in AC?
- Can VA Notify track status callbacks?

## Tasks
- [x] Get answers to questions from Beverly
- [ ] Build in lower environment first
- [ ] Setup test cases for different types of Veteran data (with and w/o ICN and EDIPI)
- [ ] _Task_

## Definition of Ready 

- [ ] List of affected Veterans is approved by VA
- [ ] Content is approved by VA
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by saderagsdale** [comment]
@data-doge FYI for refinement

**Comment by saderagsdale** [comment]
@data-doge will refine AC, waiting to hear back from VA Notify.

**Comment by saderagsdale** [comment]
@data-doge Answers from VA Notify:

Can we test in a lower environment? (I think the answer is yes but wanted to check)

> Yes. When you are ready you can point your lower env to our staging environment. We need to send you an api key, through encrypted email, so let me which of your engineers should receive the api key

Does VA Notify throw an error for undelivered emails?

> We don't throw an error but we provide a delivery status for each email. You can find out more [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/README.md)

Can we track email status after sending (similar to how Survey Monkey works)?

> You can track open rates thru GA. If the content will contain a link to a page on va.gov, we can track click throughs from the email to the page using Domo. Not sure if this answers your questions. If not, can you elaborate more on email status?

When the copy is ready, should we send it directly to you via email or this ticket?

> We have a SSUI where you can enter your copy. Let me know which team members need access and we can set you up.

**Comment by saderagsdale** [comment]
@data-doge Assuming there is a web hook for the statuses. Wants to ensure that if an email isn't delivered we are aware.

**Comment by data-doge** [comment]
I'm passing this work off to @kylesoskin (who has done similar work before), so I can focus on logging/monitoring. We have a hand-off meeting scheduled for Monday morning.

**Comment by data-doge** [comment]
Notes from Kyle convo:
- Will need to pull email from VA Profile using identifiers.  VANotify may even do this automatically.
- VANotify has a GET notification status endpoint.
- BVA will have that short-list early this week. Urgency around this.
- Need to know whether BVA will give us emails along with the short-list, before we can provide estimate.
- Sprint hygiene steps: 1) finish whatever technical discovery remains, 2) update tasks, acceptance criteria, DoR, DoD, 3) add estimate to ticket, 4) remove labels (e.g. needs-estimate, needs-grooming), and 5) add estimate to sprint doc

**Comment by saderagsdale** [comment]
@data-doge Should we flag bullet #4 for Premal or has he already requested it from BVA?

@kylesoskin Can you tag me when bullet #5 is complete? When do you think it that be done?

**Comment by data-doge** [comment]
@saderagsdale I think it makes sense to flag bullet 4 for Premal. @kylesoskin I'll leave that to you - thank you!

**Comment by HeatherWidmont** [comment]
@kylesoskin to ask Premal in the public decision review channel if the list will contain emails (@saderagsdale will send Kyle the previous slack thread)

**Comment by HeatherWidmont** [comment]
@kylesoskin heard back from Premal - will not have emails. He will change it to support looking up veterans email addresses. Will start working on that today.

**Comment by kylesoskin** [comment]
Testing this today in staging.

**Comment by HeatherWidmont** [comment]
Currently waiting on Premal to provide a list. Kyle can work on testing & error logging in the meantime

**Comment by kylesoskin** [comment]
```ruby
secret_key = '<from VA Notify>'
service_id = '<from VA Notify>'
api_key    = "va-gov-686-notification-#{service_id}-#{secret_key}"
template_id = '<from VA Notify>'
notify_client = VaNotify::Service.new(api_key)
ret = notify_client.send_email(
   recipient_identifier: {
            id_value: icn,
            id_type: 'ICN'
          },
  template_id: ,
  personalisation: {
    'first_name' =>  firstname
  }
)
pp ret
```

```

**Comment by saderagsdale** [comment]
- Waiting for content approval
- This will happen after the form updates are released (as discussed with Premal)

**Comment by saderagsdale** [comment]
We will send this email after the new version of the NOD release is at 100%. Still waiting for BVA approved content.
