### ISSUE TITLE
[Design] Create Wireframe for Messages when there is a MAP VAOS Retrieval Failure

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#65616]
## User Story
We need to plan for these unlikely scenarios:
- The call to MAP VAOS fails
- The call to MAP VAOS returns no upcoming appointments for the Veteran even though there is an appointment for which the Veteran has a task to complete

## Tasks
- [x] Check to see what VAOS is doing. Either look at Figma files or ask Peter Russo (or Melissa, because Peter's on vacation). [VAOS figma file](https://www.figma.com/file/xRs9s6QWoBPRhpdYCGc3cV/User-Flow?type=whiteboard&node-id=0-1&t=vQDdBdsjZf1n7gDE-0). Screenshot in comments for what they're using. Also, [here is another place that their content resides](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/homepage.md). 
- [x] Create final mockups with callouts (i.e., content and proper alert component). Include check in and pre check in, if needed. For example, content might be the same.  
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [ ] UI review meeting with product/UX team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/65616?planning-poker) with Zenhub @cgednalske @kellysmith1008 @ytsaoca @zach-park

**Comment by benbrasso-agile6** [comment]
<img width="881" alt="Screenshot 2023-09-18 at 12 58 10 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/101129355/eee6124f-dfba-44bb-93f4-52e6a2a7ee80">

**Comment by benbrasso-agile6** [comment]
No, next sprint. I've just been trying to use the poker pointer to get points ahead of time.

**Comment by loripusey** [comment]
k, fyi, here is the related frontend [ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65825)for the work

**Comment by benbrasso-agile6** [comment]
@cgednalske I'm good with those artboards. I know Danielle has been talking about overhauling alerts with Appointments and Mobile app, but I might suggest we move forward with the content you have and just watch for conversations about errors in our cross team channels for updates, which I don't think will happen for a while. 

Go ahead and move those into the unified check in Design board and drop those 3 artboard links in here for Lori and John. 

Nice work

**Comment by benbrasso-agile6** [comment]
And, we _shouldn't_ ever have a scenario that has this because if the MAP service fails to fetch appts, then we wouldn't know that there's no upcoming appts: 

`Appointments`
`Upcoming appointments`
`We're sorry. We've run into a problem. (alert)`
`We're sorry. You have no upcoming appts (featured content component)`

^ The `We're sorry. You have no upcoming appts` content/component is the ticket that Kelly and Ya-ching are working on - https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/65286

**Comment by cgednalske** [comment]
@benbrasso-agile6 I added those to the unified design page (below the other appointment list screens for both Pre-Check-in and Check-in). Are new arrows and yes/no scenarios needed to show how Veterans would get to those? If you want to let me know what those would be, I can add them.

@loripusey @wullaski here are those screens:
- [Pre-Check-in: Arrived on appointment list but call to MAP VAOS failed - tasks to complete](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/8VAj17R)
- [Check-in: Arrived on appointment list but call to MAP VAOS failed - tasks to complete](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/MmGVZP3)
- Both Pre-check-in and Check-in: [Completed a task and then returned to appts list page (did not arrive from a text message link), but the call to MAP VAOS failed - no tasks to complete](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/27GqARQ)

**Comment by loripusey** [comment]
Looks good to me

**Comment by benbrasso-agile6** [comment]
@cgednalske might as well, so we keep our workflow up to date. when you have time, thanks

**Comment by benbrasso-agile6** [comment]
Added them into the workflow in the [Design page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/0EC89917-F949-4461-A7B3-32A5201FD2A2/canvas)

@cgednalske you ready to close or you still dealing with those alert annotation specific to this ticket?

**Comment by cgednalske** [comment]
@benbrasso-agile6 I will add in the role="alert" annotation for error messages to our annotations page, but that should just take a second. Otherwise ready to close.

**Comment by cgednalske** [comment]
Ok, added to the alert annotations board. If that looks good this is read to close.
<img width="459" alt="Screenshot 2023-09-29 at 11 26 22 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/79372956/7abfa588-294e-4697-8dde-13a4381d5c85">

**Comment by benbrasso-agile6** [comment]
Cool. @cgednalske you should give some instructions (or a link) here for Lori to add to the FE ticket so they see this, i.e., if it's not already crystal clear. Close this when you're ready.

**Comment by cgednalske** [comment]
@benbrasso-agile6 👍 I updated my comment above to include a link to the annotations page. That should be all that's needed! @loripusey @wullaski

**Comment by loripusey** [comment]
@cgednalske the 2nd and 3rd link above throw an error that the artboard does not exist, can you fix?
cc: @benbrasso-agile6

**Comment by benbrasso-agile6** [comment]
fixed (think I might have updated the artboard names, sorry about that)

- [Pre-Check-in: Arrived on appointment list but call to MAP VAOS failed - tasks to complete](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/8VAj17R)
- [Check-in: Arrived on appointment list but call to MAP VAOS failed - tasks to complete](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/VEKgKbl)
- Both Pre-check-in and Check-in: [Completed a task and then returned to appts list page (did not arrive from a text message link), but the call to MAP VAOS failed - no tasks to complete](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/K04p4qV)
- [Relevant annotations for screen reader considerations](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/x00YA1l) (use role="alert")

**Comment by loripusey** [comment]
@benbrasso-agile6 @cgednalske where is the wireframe for the scenario where there were no appointments retrieved?
