### ISSUE TITLE
PR Review Policies and Process Documentation on Platform Site

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#65625]
## Description 
The goal of this ticket is to create external facing documentation to the VFS team to both overview our policy on PR reviews but also clearly document the process to ensure there is no confusion. We have the process for reviewing them, but it is not documented from the submission of the ticket to the very last step (i.e. approved and notifying the VFS user).

Source of feedback:

_I feel like pull request review should be priority. Teams have work to move through the pipeline and expectations from our stakeholders. Because I had to wait for a review, I missed the production deploy right before the sprint ended, and my tickets carried over. Plus, they're still not deployed because the content-build production deploy failed several times yesterday and no one from Platform helped to push it through that I'm aware of.

It seems like there needs to be a dedicated person or persons assigned to doing pull request reviews (if there isn't already) to help teams move. Otherwise this is an unnecessary bottleneck as I already had approvals from the people who had knowledge of the code I was changing._

---

## Definition of Done
All tasks below are completed.
---

## Tasks 

- [x] Identify the PR Review Request policy
- [x] Document the policy
- [ ] Identify the PR Review Request process
- [ ] Document the process 

--- 

## Resources & Additional Info 
Internal documentation: https://vfs.atlassian.net/wiki/spaces/~71202013aea26098a14ec0a4a43cb8bc9a85b4/pages/2663186485/PR+Review+Tier+1+Triage
https://vfs.atlassian.net/wiki/spaces/PTST/pages/2510194732/Pull+Request+Code+Review+Procedures

External Existing Documentation: https://depo-platform-documentation.scrollhelp.site/developer-docs/submitting-pull-requests-for-approval
---

**Comment by jknipes** [comment]
[PR Review Request Policy](https://depo-platform-documentation.scrollhelp.site/support/support-overview#SupportOverview-PullRequestReviewResponseTime)

**Comment by alyssagallion** [comment]
Duplicate ticket. Closing!
