### ISSUE TITLE
Add "Accredited Representation Management" Team to VFS Product Directory

### ISSUE THREAD

**Issue by harshil1793** [department-of-veterans-affairs/va.gov-team#65623]
### Description
Request to add a new team and their corresponding product to the [VFS Product Directory.](https://vfs.atlassian.net/wiki/spaces/~842400322/pages/2528641037/VFS+Product+Directory) The team is responsible for the "Accredited Representation Management" product.

### Tasks
- [ ] Add the new team to the internal directory.
- [ ] Update the OCTO crew affiliation to "Accreditation Reps".
- [ ] Add the Product Owners and VFS PM details.
- [ ] Include the product name "Accredited Representation Management" to the product list in the directory.
- [ ] Since there are no live products, please note this in the directory entry.

### Acceptance Criteria
- [ ] The "Accredited Representation Management" team is listed in the VFS Product Directory.

### Additional Notes
Requested by Lindsay Li-Smith

**Comment by oddball-lindsay** [comment]
Our team has a new name, updated the information above to reflect that.

While we don't have any live products, we do have a product folder in GH if that's worth referencing: [products/accredited-representation-management](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/accredited-representation-management)
