### ISSUE TITLE
Meet w/ Lighthouse about api creation

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#65644]
## Purpose
What can we learn about api creation for a forms team from Lighthouse's perspective?

Contact:  Mike Compton?

## Tasks
- [x] reach out to learn who is best to contact
- [x] Prep [questions doc](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2773057537/Getting+a+Form+over+to+VA+for+processing)
- [x] set up a meeting (w/ Michael Hobson of the Banana Appeals team)
- [x] meet w/ contact (3pm ET for 9/21)
- [x] capture learnings

## Acceptance Criteria
- [x] document learnings
