### ISSUE TITLE
Design | Editing-as-a-subtask | In line validation error message

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#65645]
## Background 
We discovered during QA testing for our editing as a subtask work, that the phone number fields accept letters and there isn't a validation running to prevent the letters from being input. We're working on handling the validation on ticket #65410. FE needs support determining the best language to use when the alert fires, this ticket is so we can provide that support. 

### The problem
If a user is adding a new number or editing an old number the form allows letters and simply drops letters without alerting the user. 

### The current alert 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/35e32e5d-27d6-4e59-aa5e-9bb99827a307)

### The question
What should the language be on the alert to account for latest and greatest validation rules we're creating for the field?
We're allowing `-` and `(` `)`
Would it be as simple as changing the current error message to say: "Enter a valid 10-digit U.S. phone number. Letters and symbols are not allowed."

_note from Travis: The problem I see with that verbiage as structured above is that we will allow dashes and parenthesis, but not sure of a better way to phrase it_ 

## Tasks 
- [x] craft an error message to display and review w/content IA folks 
- [x] share with FE once approved 

## Acceptance Criteria 
- [x] we've got approved content for the error message and it has been shared w/the FE engineer

**Comment by mtcA6** [comment]
[Slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1694719962942909) where Adam located a component in the design system library. 

LIz is going to take to content team

**Comment by andaleliz** [comment]
The content guidance is to simply say "Enter a 10-digit phone number" for inline validation on this field.  We're updating design system documentation too.  Ready for FE!
