### ISSUE TITLE
DR | Research inconsistent onBlur error messages while editing a date

### ISSUE THREAD

**Issue by rocio-desantiago** [department-of-veterans-affairs/va.gov-team#65647]
## Value Statement

**_As a_** developer
**_I want to_** confirm the content related to error messages shared across the 3 forms: 995, 996 and 10182 (SC, HLR & NOD)
**_So that_** the expected errors are being displayed when a Veteran is editing a date in any of the 3 forms.

## Background Context

- While working on [DR | Refactor date error messages](https://github.com/department-of-veterans-affairs/vets-website/pull/25467), we noticed that the date error messages change when you click away from the date input field (onBlur).
- Related ticket: Robin mentioned this pattern should have been fixed in this ticket: [Memorable date, old date bug, NVDA bug, and validation bug #1593](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1593).
- Component's original content is found [here](https://github.com/search?q=repo%3Adepartment-of-veterans-affairs%2Fcomponent-library%20please%20enter%20a%20complete%20date&type=code). 

## Out of scope

* Fixing the bug

## Tasks

- [ ]  Research what the message should be (content & design team collab). Answer: Do we still need to use this file for the default error [messages](https://github.com/search?q=repo%3Adepartment-of-veterans-affairs%2Fcomponent-library%20please%20enter%20a%20complete%20date&type=code) of the used component.
- [ ]  Determine if this is a fix that should be sitewide (POC: ?)
- [ ] Next steps identified (new ticket created if applicable) (Can we fix this within our forms or does component need updating?)

## Definition of Ready 

- [ ] [SOURCE OF TRUTH](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/design/sourceofcontenttruth.md#error)
- [ ] Teams/POC to collaborate with have been identified

## Definition of Done

- [ ] Error messages has been confirmed 
- [ ] Answers result in next steps
- [ ] If applicable, estimate technical ticket to fix this

## Explanation/Visual
  > Login to staging
  > For this example: Start or continue a board appeal application 
  > Navigate to the decision date for an issue
  > Perform a variation of the following: 
      > Leave any of the fields blank, and click away
      > Leave entire date, and click away
      > Partially fill out date to notice custom error message for month, day and year

  > https://github.com/department-of-veterans-affairs/va.gov-team/assets/37054305/d3a82897-4c92-4757-8abb-df9492c25aba

**Comment by eileen-coforma** [comment]
@rocio-desantiago 

If the user tries to continue the form with the date fields blank, use the language we set ie. 'you must enter a decision date'

If the user is filling out the form, and clicks away, it should default to whatever is set by component library when focused for the field, which is the language specific to month, date, year because there is validation for those values.

Let me know if you we need to hash more details out.

**Comment by anniebtran** [comment]
Note from Robin: Design system/web components issue, not sure how much the lift will be

**Comment by Mottie** [comment]
I didn't make much progress on this. The `va-memorable-date` web component has internal validation that is called on component blur that _always_ overrides the external error message - I think we may need to add a validate callback function to ensure that only the error messages we want the web component to show. I'll continue to mess with the code and see if I can get it to work as we want it to.

**Comment by Mottie** [comment]
Ok, this is definitely going to be more work than I anticipated:
- The built in validation is deeply integrated, and over-writes the external error message
- Adding external validation would likely only be a patch that would block all internal validation until the external error message is removed; and right now it won't work because the code won't call the (overall) date blur when there's an error message.
- We can't rely solely on the internal validation work because the min year is hard-coded to 1900 and max year is hard-coded to this year + 100
- Also updating the default error messages can not easily get done because it includes translations to Spanish and Tagalog

My remaining idea would be to add a `minDate` and `maxDate` property to the web component, and have it use these dates to process this validation and show error messages internally. But that would also require new error messages and translation work.

I'm leaning toward stopping work on this and moving this ticket into the backlog, or reassigning it to the DST

**Comment by Mottie** [comment]
The design system team has [merged in a fix for this](https://github.com/department-of-veterans-affairs/component-library/pull/1208)! They have added custom error messages for each field.

**Comment by eileen-coforma** [comment]
@Mottie  This might be normal behavior, but wanted to double check. Should it be popping into single field focus for onblur if the full field error is resolved?

https://github.com/department-of-veterans-affairs/va.gov-team/assets/111457818/ea2dacdb-f4eb-4513-b655-62f8b3b04fd0

**Comment by Mottie** [comment]
I feel like this is expected behavior. The web component won't show any of the built-in errors until the external error message is removed, and the external error message is only updated when the entire component is blurred.

**Comment by eileen-coforma** [comment]
Validated
