### ISSUE TITLE
CH 31 | Missing pID Emails

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#65641]
## Issue Description
_PA&I reached out to Linda Ritchie from VR&E to share that between 10/1/2022 and 8/23/2023  2,573 Ch 31 applications were not processed. They want to determine if this is a workload issue or a technical problem._

Background:
- Ch 31 applications go to VBMS, but VR&E didn't used to be notified when that would happen, so at some point it was established that "they" get a "pID email" so they know to go retrieve the application.
- When the user submits a VA.gov Ch 31 claim, the jurisdiction office gets email saying “you have a 1900” with a pID, which alerts them that there is a Chapter 31 application. (Open SHARE system to find out who the Veteran is, then go into VBMS).
- When any of the systems is down for a moment, it can cause us to not get email notification w/pID. There’s no way to know unless the Veteran calls and asks why they haven’t heard anything
- **Linda/VR&E would like to know if we can check if those pID emails are being sent.**
   - If they were, what email did they go to. Linda says that during the time period in question, regional offices have received pID emails
   - They're sending us the list of Veterans whose applications weren't processed
   - They did a spot-check of 30 of the applications: 25 were from VA.gov
---
## Tasks
- [ ] Investigate to determine if VA.gov sends the pID emails
- [ ] If yes, where are the emails being sent

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---

**Comment by jstrothman** [comment]
I got a forwarded copy of an example of a "pID" email

>From: [va-notifications@public.govdelivery.com](mailto:va-notifications@public.govdelivery.com) <[va-notifications@public.govdelivery.com](mailto:va-notifications@public.govdelivery.com)> 
Sent: Saturday, October 15, 2022 2:26 AM
To: VAVBAWIN/RO/VRC <[VRC.VBAWIN@va.gov](mailto:VRC.VBAWIN@va.gov)>
Subject: [EXTERNAL] VR&E Counseling Request Confirmation

>Submitted Application
Veteran's PID: [removed]
Type of Form Submitted: 28-1900
Submitted Date: 10/15/2022
Sent from: VA.gov
Note: This is an automated message sent from an unmonitored email account.

**Comment by steele-lm** [comment]
From Jill Konek, Technical Implementation Team Lead at Granicus systems: Based on what our teams have determined, it appears that your program is sending these messages through one of several TMS accounts belonging to VA. The most direct route for obtaining reporting on messages sent through TMS is to use API calls to retrieve the message data. Typically, agencies set up their systems to pull in this reporting on a regular basis, but it sounds like this may not have been configured in your case. I can work with the team to identify the account to pull the reporting from, and can support them in grabbing the sent message data for the applicable dates.

**Comment by steele-lm** [comment]
From Emily: I think we may have found a potential culprit for missing emails, which is a specific email address that is not receiving the notifications. The address is [VRE.VBACO@va.gov](mailto:VRE.VBACO@va.gov).

**Comment by steele-lm** [comment]
From Granicus on 11/20/23:
Without systemic reporting set up, here’s the process we have to follow to get a list of failed recipients for a historical time period:

- Get a list of all TMS message IDs for the given time period
- Take each message ID and run a request to determine the list of recipients the individual message was sent to
- Take each recipient ID from that list and run a request to determine whether the recipient received the message

This account is sending a high volume of messages, and has a low failure rate; statistically, we would have to do the process above over 400 times to find a single failed message. We did manually run the process 100 times, and none of those messages came back with a failed status. To find a pattern in recent failed messages, we would need to manually complete the process above thousands of times.

**Comment by steele-lm** [comment]
Ticket created to add additional monitoring to VRE emails: #70335
