### ISSUE TITLE
[Design] Wireflows Exploration for Registration Only Path

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#65659]
## Issue Description
Explore possible wireframe directions where the 10-10EZ can flow to allow for a registration only path.

[Sketch file started here
](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/3A794692-52FC-4B73-A8FE-2BBA2E61FC3F/canvas)

Based on the research findings and recommendations from the registration only generative study, revise and determine which wireflows are in alignment with research.

Create a wireflow based on [VES teams registration and priority determination business logic mural ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1692390465914/003e966ee44e0ffff814a0635d8cacaffc42db06?wid=0-1692656922282&sender=uadf1ed7fe7c76f0914967329)

---
## Tasks
- [x] Create a wireflow based on business logic diagram
- [x] Explore possible wireframe directions and refine to a few options based on research findings
- [x] Review with Team/PM/PO
- [x] Determine pros/cons/feasibility matrix of these options and next steps 

## Acceptance Criteria
- [x] Wireframe direction(s) and next steps determined
---

**Comment by jessicastump** [comment]
A list to start the conversation :) 

For reference
1. [Existing short form flow - UNauthenticated](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/byyAe5/a/oML8LZn)
2. [Existing short form flow - authenticated](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/Ry9l9EQ)



**Wireflows drafted**
1. Short form expanded to 30-40% disability ratings: [Unuthenticated flow](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/zyQWed4) and [Authenticated flow](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/MmG5jjw)
2. [Business Logic Version Exploration](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/kKLVGao)
3. [Registration as a Process plus Eligibility Determination](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/qbMzO4n)
4. [Mental health use case version](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/oMLjJVL)
5. Paper w/ plain language updates - [Version before Veteran information](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/g1b9q9M) and [Version after Veteran information](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/g1b9q9M)


[Full working Sketch page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/3A794692-52FC-4B73-A8FE-2BBA2E61FC3F/canvas)

**Comment by jessicastump** [comment]
@hdjustice Tagging you here after we chatted today :)

Next steps are to go over this in the next weekly design sync with Kristen and narrow down wireflow directions
Review recommendations in the next PO sync (one after tomorrow 10/10? or a specific meeting sooner?)
**Close this ticket when decisions on which flow(s) to explore are made**
Open Collab and Content tickets (you did this already!) 
Once we have narrowed direction, we will be ready to prepare for design intent (I can open this as a new ticket) and the research planning ticket (another new ticket I can open)

**Comment by jessicastump** [comment]
Link to the [matrix table](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1696891719955/7e17ac86124fb9dcc6322be634ccdc4e8eb00a0a?sender=uadf1ed7fe7c76f0914967329) of options to use in narrowing down discussions

**Comment by jessicastump** [comment]
Recap of Friday's meeting and next steps: research planning for an IA (tree test/card sort) based on Registration Reasons tasks, possible second study of intro page/instructions for registration and enrollment benefits table. 
Will open a new ticket for research planning. 

[New mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697236808091/d46ade25165c13764b7f8334ade21f20eed61038?sender=uadf1ed7fe7c76f0914967329)
