### ISSUE TITLE
Develop low-fidelity design proposals for an improved secondary navigation component

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#65676]
## User Story
As a UX practitioner working on the MHV to VA.gov transition and overall experience, I want to lean on the results of the competitive analysis and documentation of problems with existing navigation to inform an improved design for health portal secondary navigation.

## Description
In previous tickets, the team evaluated the existing side navigation/ secondary navigation patterns on VA.gov and documented issues they present for the MHV on VA.gov health portal. We also conducted a competitive analysis of other side navigation patterns that can inform a direction for an improved, redesigned secondary navigation. 

Now, we need to abstract the best layouts and interaction patterns from the competitive analysis (keeping in mind the documented problems with previous components & needs for this experience) to give some structural guidance to designers to then come up with several proposals for an improved navigation component. 

## Tasks
- [ ] IA should analyze results of previous tickets and provide structural guidance for an improved secondary navigation component
- [ ] IA & design collaborate to draw up some lo-fidelity examples using IA's structural guidance
- [ ] Get design team feedback on these components
- [ ] Take to Design System Council (DSC)

## Acceptance Criteria
- The team has design proposal(s) that incorporate findings from navigation research analysis & competitive analysis
