### ISSUE TITLE
PR Review Policy Communications

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#65681]
## Description 
The purpose of this ticket is to communicate the 24 hour PR Policy to applicable channels. The tickets listed at the end of this ticket encompass the updates we've made to documentation that will be made in that communication.

---

## Definition of Done
All tasks below are complete.

---

## Tasks 

- [x] Formulate a message related to the PR Review policy and add context as to why things seemed to have changed despite the policy being 24 hours all along
- [x] Post announcement in #vfs-platform-support
- [x] Post in #vfs-change-announcements
- [x] Add to Team of Teams Slide

--- 

## Resources & Additional Info 
Tickets with documentation we are updating:

- https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/65637
- https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/65625

---

**Comment by alyssagallion** [comment]
Scheduled out messages, added to Team of Teams slide and ran all by Erika Washburn (PO). Closing!
