### ISSUE TITLE
[CHIP] - Update dependencies

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#65691]
## Summary
There are a number of Critical and High [Dependabot alerts](https://github.com/department-of-veterans-affairs/chip/security/dependabot) for the CHIP repo.  We need to review these and either (1) resolve them or, (2) if we will not be addressing them, add a short description of why we think we do not need to address them.  

[Slack thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1697202877725959)

We have a bunch of dependbot PRs open for CHIP: https://github.com/department-of-veterans-affairs/chip/pulls

We should evaluate and update as we see fit.

## Tasks
- [ ] [CHIP] - evaluate PRs 
- [ ] [CHIP] - merge PRs that look good
- [ ] [CHIP] - create a candidate release
- [ ] [CHIP] - regression test in stage
- [ ] Create or update unit tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
@lee-delarm6 / @wullaski This is ready for validation. 

Here is the release: https://github.com/department-of-veterans-affairs/chip/releases/tag/v3.4.1

It is deployed on stage. To test, you can hit endpoints in insomnia or use the scheduling tool and stage.

**Comment by wullaski** [comment]
@brianseek Tested everything with the scheduling tool and completed pre-check-in and check-in on staging. Everything looks good!
