### ISSUE TITLE
Looker Dashboard Communications

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#65700]
## Description 
_Please include a brief description of the purpose of this ticket._

---

## Definition of Done
All tasks below are complete.
---

## Tasks 

- [x] Respond to string about broken Looker Dashboard with the new Support Responses Doc created https://vfs.atlassian.net/wiki/spaces/PTST/pages/2767093962/Support+Responses+Spreadsheet
- [x] Send update in #platform-tech-team-support
- [x] Send update to Kerry Powell/Curt Bonade

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Messages Sent:

Hey folks! This is a follow up on the thread below from June. TL;DR, there were two issues:

The Looker Dashboard broke
We didn't know enough about the Support Bot

Since then we have:

Backfilled the data so we don't lose the history
Ensured we completely know how the Support Bot works (note: there are still some things that no one knows and we are working on filling in the gaps)
We have documented how the specific connection between Support Bot > Spreadsheet > Looker Dashboard flow works.

The belief was that it was documented somewhere but it wasn't, now it is. :slightly_smiling_face:  Here are the newest documents to cover the gaps:

Support Responses Spreadsheet: This document outlines how the connection between the Slack Bot, the spreadsheet and the Looker Dashboard functions.
Looker Dashboard: This page overviews the purpose of the Looker Dashboard.
Domo Dashboard: This page overviews the purpose of the Domo Dashboard.
Platform Support Bot Update: This page is not owned by our team but we included additional information on how the reporting works for the Support Bot (same content as the Support Responses Spreadsheet document above but ensures no matter where someone searches they find the info). 

Note: All documentation is a work in progress and is constantly being updated, but we wanted to at least get down how things work right now to avoid any future misunderstandings.

Link to string: https://oddball.slack.com/archives/C0459AQ5GBT/p1695835203831719
