### ISSUE TITLE
Collaboration Cycle for Accredited Representation Management: Find a Representative MVP (round 1 of 2)

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#65707]
## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### VFS team name

Accredited Representation Management Team

### Product name

Find a Representative (MVP)

### Feature name

Find a Representative

### GitHub label for product

accredited-representation-management-team

### GitHub label for product

find-a-representative

### Public DSVA Slack channel for VFS team

#benefits-representation-management

### When did/will you start working on this product/feature?

We began discovery for this product on 8/14/2023 and we defined our MVP on 9/7/2023

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Tools, applications and dynamic pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

No

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-outline.md

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Notify the Collaboration Cycle team of this ticket in your team's public Slack channel.

- [X] I acknowledge that I must notify the Governance team by completing the collab cycle kicckoff workflow in my team's Slack channel after submitting this issue. This can be completed by typing "/collab cycle" and selecting the appropriate workflow.
[Slack request](https://dsva.slack.com/archives/C05L6HSJLHM/p1694811345641459)
</details>

### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- Navigate to reference link: [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent)
- [x] Schedule your Design Intent when ready:
   - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
      - The Governance team is responsible for inviting our team members, including our Product Owner, Product Manager, and practice area specialists. We also notify OCTO-DE practice area leads when we finalize meeting scheduling. 
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event by using the `/Collab Cycle Design Intent` "slash-command" in your team channel. Provide information as prompted by the Slack workflow.
- [ ] Link all artifacts **ONLY** in the Design Intent artifacts section below at least two days before the scheduled Design Intent.  **Do NOT add artifacts to Comments section**
  
**Design Intent artifacts**

See Platform guidance on [Design Intent artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Design Intent meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

- [x] [User flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1692888741111/2474c0612887653142ab991d234898b6968dbf0e?sender=ud8fb439cf1516edb66c71635) (required)
- [x] [Wireframes](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1692888741111/2474c0612887653142ab991d234898b6968dbf0e?sender=ud8fb439cf1516edb66c71635)
- [ ] Research plan
- [ ] Any other artifacts you have so far
  
##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C05L6HSJLHM/p1695076422458999)
- [x] Meeting date/time: **9/25/2023 at 3:30pm ET**
  
##### Platform actions

* Accessibility
  * [x] Feedback ticket attached
  * [ ] No feedback
* Design
  * [x] Feedback ticket attached
  * [ ] No feedback
* IA
  * [x] Feedback ticket attached
  * [ ] No feedback
* [x] Update this ticket with the Zoom recording
 - [Design intent recording](https://oddball-io.zoom.us/rec/share/x9lA-35Pug2Kw8nSinSMeUI5dlPUycleMkPho7N5gt9rClx4hzr4pxZp5eNmlLIK.zWZdelgTZC8jBF_y)
 - Passcode: E.w+n8mF
  
##### VFS actions

- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Sitewide CAIA Intake Request
<details>
  <summary>Toggle Sitewide CAIA Intake Request</summary>

##### VFS actions
- [x] Complete the [Sitewide CAIA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-CAIA-intake-request.2124906551.html)
- [x] Link to the Sitewide CAIA Intake Request ticket below

https://github.com/department-of-veterans-affairs/va.gov-team/issues/65809

</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [ ] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [x] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [x] Notify the Collaboration Cycle team of this event by using the `/Collab Cycle Midpoint Review` "slash-command" in your team channel. Provide information as prompted by the Slack workflow.
- [x] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

Provide links or documents for the following:

- [x] [Finalized design prototype or mockup](Updated designs, ready for Midpoint review: https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/p/3C666192-27DA-40CE-B314-BA779A8C8BD4/canvas#About)
- [x] Specify which pages are included in the review - all, please also consider open comments -- would love your input!
- [x] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/research/2023-10-ARM-MVP-usertest/research-plan.md)
- [x] [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/research/2023-10-ARM-MVP-usertest/conversation-guide.md)
 
**Content artifacts**
  
- [x] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including a content source of truth, any relevant static content page and entry point updates, and the intake form.

From the Design Intent:
1. [Design Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/66388)
2. [IA Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/66301)
3. [Accessibility Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/66297)
4. [Additional Accessibility Notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/drafts/accredited-rep-management.md)

**IA artifacts**

- [x] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) feedback you received, including an IA review document or intake form.

1. Information Architecture ideation is stored in our [User Flow Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1692888741111/2474c0612887653142ab991d234898b6968dbf0e?sender=ud8fb439cf1516edb66c71635) (on the left) 

##### Platform actions
- [x] [Slack request](https://dsva.slack.com/archives/C05L6HSJLHM/p1696877499236529)
- [x] Meeting date/time: October 17th, 2023 at 11:30am ET

##### Platform actions

* Accessibility
  * [x] Feedback ticket attached
  * [ ] No feedback
* Content
  * [x] Feedback ticket attached
  * [ ] No feedback
* Design
  * [x] Feedback ticket attached
  * [ ] No feedback
* IA
  * [x] Feedback ticket attached
  * [ ] No feedback
* [X] Update this ticket with the Zoom recording
  - [Midpoint review recording](https://oddball-io.zoom.us/rec/share/yS4KcFeZeOnppcN7qZFm8Vw9MBP2XjmRylW7Q1rXZt6afgXqvkPdOF10LTDNr67m.uXaB-5p0wAYezX7-)
  - Passcode: &=w#=pS5
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [x] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [x] Link to the Analytics Implementation and QA Request ticket below

https://github.com/department-of-veterans-affairs/va.gov-team/issues/69230

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [x] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [x] Link to the Contact Center review request ticket below

https://github.com/department-of-veterans-affairs/va.gov-team/issues/69435

</details>

### Staging Review
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event by using the `/Collab Cycle Staging Review` "slash-command" in your team channel. Provide information as prompted by the Slack workflow.
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [x] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [x] I confirm the environment is available and test users have been provided.
- [x] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory) -- [Ticket has been submitted to add Find a Representative to the VFS Product Directory](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68492)

**Staging Review artifacts**
  
See Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts). Platform findings are based solely on the staging URL and test users provided, as reviewed during the four days before the Staging Review meeting. Any test cases not covered or any ongoing work taking place during the review period may not be reflected in those findings.  

**Product artifacts** 
- [x] Staging URL https://staging.va.gov/get-help-from-accredited-representative/find-rep/
- [x] Specify which pages are included in the review  - all pages which includes the initial search parameters and related search results
- [x] Staging test user information - no test users are needed, as this experience does not require authentication
 
**Content artifacts**
- [x] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including a content source of truth, any relevant static content page and entry point updates, and the intake form.

- Midpoint content feedback: https://github.com/department-of-veterans-affairs/va.gov-team/issues/67740
- CAIA content recommendations for Find a Representative: https://docs.google.com/document/d/1C3up542aM1XsqmyEq7UMZWFrODH1QtDOBXeRzXhlQqo/edit
- All CAIA content recommendations for the ARM team: https://drive.google.com/drive/folders/1Z4-nv20Pk2NmyXVhcCrR3otJTSnzGqAu
  
**IA artifacts**
- [x] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) feedback you received, including an IA review document or intake form.

- Midpoint IA feedback: https://github.com/department-of-veterans-affairs/va.gov-team/issues/67848
- CAIA IA plan: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/manage-accredited-representative.md
- CAIA IA notes: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1692888741111/2474c0612887653142ab991d234898b6968dbf0e?wid=0-1697577855912

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [ ] [Regression test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-regression-test-planRegressionTestPlan)
- [ ] [Test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-test-planTestPlan)
- [ ] [Coverage for References](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [ ] [Summary(Defects) reports](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [x] [E2E tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-e2e-test-participationE2ETestParticipation) (provide a link to the product’s code) - https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/representative-search
- [x] [Code coverage](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-unit-test-coverageUnitTestCoverage) (provide a link to the product’s code) - https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/representative-search
  
**Accessibility artifacts**
  
- [x] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D). For details, see [Prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review). 

- ARM accessibility testing for Find a Rep: https://github.com/department-of-veterans-affairs/va.gov-team/issues/70616
- CAIA Accessibility feedback: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/CAIA/accessibility/Deliverables/Benefits%20Representation%20Management
- Additional CAIA Accessibility feedback: https://dsva.slack.com/archives/C05L6HSJLHM/p1699884825790079
  
##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C05L6HSJLHM/p1700865330692189)
- [x] [Reschedule Slack thread](https://dsva.slack.com/archives/C05L6HSJLHM/p1701305324580779)
- [x] Meeting date/time: ~Friday, December 1, 2023 at 2:00PM ET~ Rescheduled: December 7th at 3:30pm ET

##### Platform actions

- [x] Update this ticket with the Zoom recording
  - [Recording link](https://oddball-io.zoom.us/rec/share/WdcPFkpP2tYRRPc8ovhWyPOODCuYYwQOVAjcXCcvRiYT7KbcHuH4Lyh8NjJXft5b.VTNgjIyzS_Tlfp53) 
  - Password: `y2RwAv=4`
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [x] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [x] Link to the Readiness Review ticket below

https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1339

#### Platform actions
- [x] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by oddball-lindsay** [comment]
After the midpoint review, we have decided to split into two releases:
1. Find a Representative
2. Appoint a Representative + Representative Status Widget

This ticket has been re-purposed to cover the Find a Representative MVP.

Down the line, we will be entering additional rounds of the Collaboration Cycle for:
1. Find a Representative v2
2. Appoint a Representative + Representative Status Widget MVP
