### ISSUE TITLE
[UX][DESIGN] Add artboards to the Design page in unified check in for pre check in phone and grouped warning alerts

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#65709]
We do not have all new error message for Unified Check-in (such as expired link errors) versioned out for phone appointments and grouped appts in the Design page. 

Phone appts that need to be moved into Design page
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/RydD1ly
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/1VL1KxO
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/4o9Y293

Grouped appts that need to be moved into Design page
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/OenGOnw
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/mPO3EO7
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/DE03n0j

For the grouped appts accordions, take a look if those need to be updated. In some of our other sketch files, there are different content for those accordions for grouped appts. If we feel the content should still be different for this scenario, then let's add those versions to our Annotations page. [Sketch comment here](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/DE03n0j?annotation=ffdd954a-75f0-4577-93b4-1eeb6149fb75), but I'm pretty sure we have the content in our pre-check-in sketch files. 

## Tasks
- [ ] Pull over artboards into Design page and add arrows, as needed
- [ ] Check pre-check-in sketch files and determine if we need to version out different accordion content for grouped appts. If so, add those to [Annotations page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/qb9R1x5)

## AC
- [ ] Artboards are pulled over into Design page for unified check in sketch file
- [ ] Annotations are updated, as needed
