### ISSUE TITLE
Build, edit, and publish VA Survivors Pension page in Spanish

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#65725]
## Issue Description

As part of our ongoing effort to have more multilingual content on our site, we need to publish the core Pension pages in Spanish. This includes [VA Survivors Pension](https://www.va.gov/pension/survivors-pension/).

We need to build the page in Drupal, review, and publish.

Content from translation team: [LS-2022-0118394-G-SPA-FINAL_Pension content for Spanish translation Batch 1 (1).docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcXVyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0c0bd2bcc924ad027ec97ed8203936cb01d7162a/LS-2022-0118394-G-SPA-FINAL_Pension%20content%20for%20Spanish%20translation%20Batch%201%20%281%29.docx)

## Tasks
- [x] Build Drupal page (Ana)
- [x] Review (Megan/Chelsea)
- [x] Publish (Megan/Chelsea)
- [x] Send live page to State Department for QA (Randi)
- [x] Input any changes (Victoria)
- [x] Review (Sara T.)
- [x] Publish with Spanish toggle (Sara T)

<details>
<summary>Prepublishing checklist</summary>

### Before you begin
- [ ] Confirm that there are no updates in draft by other content authors that aren't ready to be published. Check the revision log and then confirm with the content author who made the previous edits that the page is ready to publish.

### Accessibility standards

- [ ] If your link or button will take the user off VA.gov, confirm that the text for the link or button contains a purpose and a target. The user should be able to tell from the link or button text what the call to action is (the purpose) and where they will end up if they click on the link (the target). The following link is an example of this: <br>[Read more about making links accessible on AccessibilityOz](https://www.accessibilityoz.com/2014/02/links-and-accessibility/)</br> 
**Note:** When you direct the user to another VA.gov page, the link only needs to contain text indicating purpose (the call to action).
- [ ] Confirm all phone numbers are in aria labels. [Learn how to code numbers with aria labels](https://design.va.gov/content-style-guide/dates-and-numbers#phone-numbers)
- [ ] Confirm that the hierarchy of section and subsection titles is correct (H1 to H2 to H3—levels shouldn't be skipped). [Learn more about section titles](https://design.va.gov/content-style-guide/page-titles-and-section-titles)
- [ ] Replace any sighted language ("view," "see," "look") with a word that's inclusive of our screen reader users ("check," "go to," "review").
- [ ] Avoid using other ability-focused language. ("hear back from")

### Link standards

- [ ] Confirm that links work (aren't broken—no error message) and point to the intended page (you pasted in the correct URL or chose the correct node ID).
- [ ] Confirm all link text is 100 characters or less.
- [ ] Check that you've selected a node ID for all links pointing to VA.gov (internal) pages. Only paste in a URL if the page you're linking to doesn't live in our CMS (isn't one of our modernized pages). [Learn how to add node IDs in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/linking-with-node-ids.md) 
- [ ] Check that all anchor/jump links are pointing to a node followed by # and the header identifier (Example: /node/47278/#information-for-survivors). Double check all anchor/jump links post-publish. 

### CMS standards

- [ ] Make sure all apostrophes and quotation marks are curly not straight. (Once this is automatic in Drupal, we can remove this item.)
- [ ] If there are alerts at the top of the Drupal Edit node for broken links, redirected links, or links to unpublished pages, correct the issues. If there's an alert for a broken link but the link is actually working, report the issue to the CMS help desk. [Read more about link alerts in the CMS knowledge base](https://prod.cms.va.gov/help/cms-basics/how-to-fix-broken-links-and-redirects)
- [ ] If publishing a brand-new page, confirm the left nav and url are set up correclty. (If the page is a child page, the section needs to be the same as the parent page in order for the left nav to show.) [Learn how to set up a url and left nav in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/adding-left-nav-and-url.md)
- [ ] Check if the page has a new or updated alert. If so, publish the alert separately. 

### Additional checks for translated articles
- [ ] If we don't have updated translated versions, add the alert that links to the corresponding English page and lets users know that the translated pages aren't up to date. 

</details>

## Acceptance Criteria
- [ ] Page is live with Spanish toggle

**Comment by megzehn** [comment]
Thanks, @coforma-terry. You can just tag Ana and me (and maybe Randi?) for translation tickets for now. @chelsealevinson is covering a lot of other stuff, so I'll unassign her from here!

**Comment by ABeltran77** [comment]
@RLHecht @strelichl Page has been built but missing one teaser as noted in yellow highlight in the last page of the attached Word doc. Also, I have a question about the acronyms in the Link Teaser URL's. I did add "por sus siglas en inglés" in a couple Link Summaries. @RLHecht Let's discuss when we meet next. 

[LS-2022-0118394-G-SPA-FINAL_Pension content for Spanish translation Batch 1 (1) (5).docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/13169761/LS-2022-0118394-G-SPA-FINAL_Pension.content.for.Spanish.translation.Batch.1.1.5.docx)

@megzehn If you want to get a jump start on the review or wait until we have the missing Link Teaser...up to you.

**Comment by RLHecht** [comment]
Thanks @ABeltran77 . I'm not seeing the highlighted teaser when I open that word doc. Is this something you can translate and we can have State QA when we send them the live link?

**Comment by ABeltran77** [comment]
Hi @RLHecht it's this teaser: •	[Report the death of a Veteran to VA](https://www.va.gov/resources/how-to-report-the-death-of-a-veteran-to-va)
Learn how to contact us to report a death so you can avoid debt from benefit overpayments. 

Yes, I can translate it.

**Comment by ABeltran77** [comment]
@RLHecht @strelichl Teaser is translated and added to page.

**Comment by RLHecht** [comment]
This page shouldn't be blocked anymore and can be ready to be worked on. I think the next step is for Megan to review and publish but @ABeltran77 can you confirm since it's been a while since we've been in this page?

**Comment by megzehn** [comment]
Hi @RLHecht,

There was one change from December that we don't have translation for. Should I ask Victoria?

> - Vietnam War era for Veterans who served in the Republic of Vietnam (November 1, 1955, to May 7, 1975)
> - Vietnam War era for Veterans who served outside the Republic of Vietnam (August 5, 1964, to May 7, 1975)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/72934749/7ab673de-b83a-4bea-85f5-bc0b45f8ec0d)

Otherwise, the page looks good! I can publish after we get this update in there.

**Comment by megzehn** [comment]
Also, dropping a link to the translated page in this ticket for easier access: http://preview-prod.vfs.va.gov/preview?nodeId=62563

**Comment by megzehn** [comment]
Update: @saratorres2 stepped in to translate these 2 bullet points (thank you Sara for the translation and helpful explanation!)

@RLHecht, confirming that I published the [Spanish version of Survivors Pension](https://prod.cms.va.gov/pension/survivors-pension-esp) and added it to our list of translated pages. It's ready for QA!

**Comment by RLHecht** [comment]
Thanks, Megan. I sent this to State for QA today. I'll post here with any changes.

**Comment by megzehn** [comment]
Hi @RLHecht, did QA have any changes for this one? Just wondering if we're good to move it forward to get the Spanish toggle.

**Comment by RLHecht** [comment]
Thanks for flagging this, @megzehn I don't believe we ever got it back. i just sent another email following up.

**Comment by RLHecht** [comment]
Nope, I sent another email asking earlier this week.

**Comment by RLHecht** [comment]
Posting in here to say that State came back with no changes to this page so we can now move forward with next steps. Thank you!

**Comment by moviedosoco** [comment]
@RLHecht Thank you, Randi. I made some updates to match the English page, and for consistency according to our style guide and glossary (for example, word "guerra" in lower case, or the addition of "Opción 1, 2, 3, 4" in _¿Cómo solicito una pensión para sobrevivientes?_ copy). 

@saratorres2 The update of the **Pensión de VA para sobrevivientes** page is ready to be reviewed and published. Let me know if you have any questions. Thank you!
Preview: https://preview-prod.vfs.va.gov/preview?nodeId=62563
Prod: https://prod.cms.va.gov/node/62563/latest

**Comment by juliana-jara** [comment]
@RLHecht I am done reviewing this translation. The only issue I found is that the first link you find is meant to take you to an H2 in the same page, not to a different page. In this case, not only this would need to be fixed, but also the wording "(en inglés)" would need to be removed.

![Image](https://github.com/user-attachments/assets/39d6001e-893f-4ca6-8dfc-235ca4922c2e)

**Comment by RLHecht** [comment]
Thanks for this! Can you update that jump link in Drupal? Here's documentation on how to do it but you can let me know if you get stuck: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/linking-with-node-ids.md#how-to-add-jump-links-with-node-ids

**Comment by juliana-jara** [comment]
@RLHecht Unfortunately I am gonna need help with this one. I tried to use the jump link instructions but I think I may be doing something wrong or I am missing something.

**Comment by RLHecht** [comment]
These changes are live. Closing ticket.
