### ISSUE TITLE
BE | Profile | Maintenance Period Alerts| BGS Service Unstable Error (parsing HTML)

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#65746]
## Background
During a Lighthouse maintenance window, the following errors showed in our logs for both GETs and PUTs.

```ruby
  "status"=>502, 
  "title"=>"Required Backend Connection Error", 
  "detail"=>"Backend Connection Error - BGS Ebenefits Address Update Service Unstable"
```

```ruby
:status=>502, 
:body=>"<html>\r <head><title>502 Bad Gateway</title></head>\r <body>\r <center><h1>502 Bad Gateway</h1></center>\r </body>\r </html>\r "
```

## Tasks
For each error:
- [ ] Add BE parsing that results in an intuitive error code.
- [ ] Add specs to test each.

## Acceptance Criteria:
- [ ] Figure out why this even happened and review with FE
- [ ] Verify in staging

**Comment by tpharrison** [comment]
I am no longer seeing this error and if it does occur, I expect it to be during a maintenance window, in which case, we should have a notification present and the feature disabled.
