### ISSUE TITLE
[spike] HLR | Investigate unprocessable entity errors

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#65745]
## Value Statement
**_As a_**  developer
**_I want to_** determine why a Veteran is unable to submit an HLR
**_So that_** we can fix and notify the Veteran that there was a problem so that they can submit

## Background Context

In our weekly review of Sentry errors, we noticed 6 instances of [unprocessable entity errors](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?field=message&name=Higher-Level+Review&project=4&query=url%3Ahttps%3A%2F%2Fwww.va.gov%2Fdecision-reviews%2Fhigher-level-review%2Frequest-higher-level-review-form-20-0996%2F%2A+level%3Aerror+message%3A%22vets_server_error%3A+Unprocessable+Entity+Error+%2Fgenerated%2F0996-higher-level-review.entry.js+XMLHttpRequest.%3Canonymous%3E+XMLHttpRequest.%3Canonymous%3E%28generated%2F0996-higher-level-review.entry%29%22&sort=-message&statsPeriod=7d&widths=-1) in the HLR dashboard. It appears that all 6 instances are from one Veteran, but further investigation is needed to determine that, discover the cause and eventually fix it.

## Tasks
- [x] Investigate issue leading to the unprocessable entity error. Timebox to 2 hours.
- [x] Share result with team
- [x] Fix issue
- [ ] Notify Veteran via help desk

## Definition of Done
- [x] Determine cause of error
- [x] Issue has been fixed
- [ ] Veteran has submitted HLR

## Acceptance criteria
- [x] All tasks complete
- [ ] Veteran notified of issue and/or Veteran is able to submit HLR
- [ ] Issue fixed so that it doesn't occur again

**Comment by data-doge** [comment]
Another instance: https://vagov.ddog-gov.com/logs?query=service%3Avets-api%20%40payload.controller%3A%2AHigherLevelReviews%2A%20-%40http.status_code%3A200%20env%3Aeks-prod%20&cols=host%2Chttp.status_code%2Cservice%2C%40payload.controller%2C%40http.url_details.path%2C%40payload.user_uuid&index=&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=time%2Cdesc&viz=stream&from_ts=1695664755609&to_ts=1695665812808&live=false 

Veteran tried to submit 6 times. All failed with 422.

**Comment by data-doge** [comment]
Another instance: https://vagov.ddog-gov.com/logs?query=service%3Avets-api%20%40payload.controller%3A%2AHigherLevelReviews%2A%20-%40http.status_code%3A200%20env%3Aeks-prod%20&cols=host%2Chttp.status_code%2Cservice%2C%40payload.controller%2C%40http.url_details.path%2C%40payload.user_uuid&index=&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=time%2Cdesc&viz=stream&from_ts=1695421141830&to_ts=1695422329860&live=false

Veteran tried to submit 3 times. All failed with 422.

**Comment by data-doge** [comment]
User UUID: 89b75cba7bf6407d8abc6ee09ba3aeec

**Comment by data-doge** [comment]
@Mottie Since I'm out tomorrow, so I'm going to assign this to you. Curious to know what you think of the missing address error in the previous comment 🤔. My guess is that this Veteran started the form in 2019, and LH's form schema has changed since then, so now LH throws an error. What I don't know is what specific field is missing. Sentry redacts that information.

**Comment by Mottie** [comment]
I just verified that, on submission, the frontend code is passing a `zipCode5` value of `'00000'` when an `internationalPostalCode` is provided, but from the data it looks like both the `zipCode` AND the `internationalPostalCode` are `nil`. So I'm not sure what to do in this case. I'll update the front end code to ensure that the `'00000'` string is submitted.

**Comment by Mottie** [comment]
Fix has been merged in, we can test in staging by:
- Log into any user
- On the contact page, remove the zipCode from the address
- Change the country to anything other an "United States"
- Remove any postal code
- Save address
- Upon submission, check submitted data. It must include a `zipCode5` set to `00000`

**Comment by data-doge** [comment]
Thanks @Mottie! Once this is confirmed as resolved in staging (by reconstructing the data in https://github.com/department-of-veterans-affairs/va.gov-team/issues/65745#issuecomment-1734466300 and submitting the form with it), could you figure out how to notify the Veteran with user_uuid `0a9c6f99e3d74cc99c461fa791dcbf18` that they should try to re-submit now? At that point, I think we could close this ticket.

**Comment by HeatherWidmont** [comment]
@Mottie to reach out to Kyle for call center contact to follow-up with veteran

**Comment by saderagsdale** [comment]
@Mottie @kylesoskin Can you add a link to the thread for the contact center reaching out to the Veteran?

**Comment by data-doge** [comment]
I've reached out to Kimberley with the Veteran's contact info, in Teams. We can close this ticket once we get confirmation from Kimberley that the Veteran has successfully re-submitted.

**Comment by HeatherWidmont** [comment]
Keeping open for another week for the veteran to say it doesn't work or give any other type of feedback

**Comment by data-doge** [comment]
@data-doge will check in with Kimberley today to see if things are all fixed on Veteran's end

**Comment by data-doge** [comment]
Looks like this Veteran submitted their HLR successfully this morning! See [Datadog](https://vagov.ddog-gov.com/logs?query=%40payload.user_uuid%3A%220a9c6f99e3d74cc99c461fa791dcbf18%22%20&cols=host%2Cservice&event=AgAAAYsZIFgWkV_6SQAAAAAAAAAYAAAAAEFZc1pJRi1lQUFCTkxka0NIM3VYdFFBVAAAACQAAAAAMDE4YjE5NzAtOGY4Yi00NDQ4LThlM2EtOTQwZWJkYjdiZjM5&index=%2A&messageDisplay=inline&refresh_mode=paused&stream_sort=desc&viz=stream&from_ts=1696915889548&to_ts=1696957696000&live=false). And Kimberley says that the Veteran has not reached out to her. 

Closing this ticket.
