### ISSUE TITLE
HLR | Update and Refactor "addIssue" content 

### ISSUE THREAD

**Issue by rocio-desantiago** [department-of-veterans-affairs/va.gov-team#65747]
## Value Statement

**_As a_** developer
**_I want to_** refactor the content related to error messages shared across the 3 forms: 995, 996 and 10182 (SC, HLR & NOD)
**_So that_** tech debt is reduced and so that future developers don't have to make the same change across the shared validations in SC, HLR & NOD redundantly.

## Background Context

- While refactoring the date validations, we noticed `errorMessages` (in 995) and `issueErrorMessages` (in 996 and 10182). Content/verbiage updates recommended by the legal team were updated in Supplemental Claims due to a review and HLR and NOD should also reflect those content update requested by the legal team. 
- Related ticket: [NOD | Refactor "addIssue" content into shared file](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64708)
- Content related to error messages in the following files will be refactored into the shared constants/content file:
  > src/applications/appeals/996/content/addIssue.jsx

## Out of scope

* Other apps/forms not in Decision Reviews

## Tasks

- [ ] Added to existing shared directory
- [ ] Unit tests updated
- [ ] Validate that forms functionality has not changed

## Definition of Ready 

- [ ] SOURE OF TRUTH updated

## Definition of Done

- [ ] Functionality not changed
- [ ] Reduced files

**Comment by rocio-desantiago** [comment]
This one is pending content update confirmation to align all 3 forms with the same language as requested for Supplemental Claims.

**Comment by Mottie** [comment]
Ready for validation in staging

**Comment by eileen-coforma** [comment]
This funky thing is happening with the page title when there's an error. Is this the same thing as the NOD issue, where it goes blank if it's the only page and it has the same name? It shows back up as long as there's another page under it.

![Screenshot 2024-04-24 at 2 36 04 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/111457818/1c00ca4a-bf96-425e-8c8f-0c5e8aa20fda)

Also, this ticket is just for the refactor work for HLR. Are we including the updated error messages (specific to HLR) in here too? I see it's already updated (with exception of contact information errors).

**Comment by Mottie** [comment]
Yes, this was a refactor ticket for HLR, but in refactoring, I moved all the in-common error message from HLR, NOD & SC into the shared folder. I'll take a look at this page header soon - I forgot about it!

**Comment by saderagsdale** [comment]
@eileen-coforma @Mottie is this one good to close, or does the AC need to be updated and tested to reflect the discussion above?

**Comment by Mottie** [comment]
The remaining issue was fixed in [#29397](https://github.com/department-of-veterans-affairs/vets-website/pull/29397) (screenshots in PR) - so it should be ready for validation, then closing.

**Comment by eileen-coforma** [comment]
@Mottie is there anything for me to validate on the frontend for this ticket?

**Comment by eileen-coforma** [comment]
Validated the PR. Ready to close.
