### ISSUE TITLE
How might we solve for auto-hyperlinking VA.gov on website?

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#65748]
## Info
VA.gov is automatically hyperlinked on Confluence. This ticket is to determine how to prevent this from happening. 

## Task Ideas:

- [X] Submit a support request to Confluence on how to prevent this from happening. UPDATE: Support ticket not needed, this was discovered after a quick Google Search.
- [ ] Recording findings in this ticket on if it's possible to resolve this issue.

## Acceptance Criteria:

- [X] Answer has been documented on this ticket.

## Findings: 
Answer covered on Friday, November 17th. It was discovered that you can unlink the auto-URL functionality with a simple Command-Z on a Mac (Control+Z on a PC), after it's been posted in Confluence. I tested this in our Sandbox Org, and provided an image into how it appears on the Platform Website.

Information has been shared with the team. The next step will be to identify where we can document this process on our own Confluence space to maintain this knowledge.

**Comment by johnny-jesensky-adhoc** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/65748?planning-poker) with Zenhub @taylojill @BSmolensky @laucon @rferguson13

**Comment by johnny-jesensky-adhoc** [comment]
Played around with this earlier today - discovered you can unlink the auto-URL functionality with a simple Command-Z (on a Mac), after it's been posted in Confluence. Tested this in our Sandbox Org, and provided an image into how it appears on the Platform Website. 

Likely will look to pull this into the current sprint, as it meets most of the AC.

Can figure out the best place to document this so we maintain this knowledge.

  [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0xwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--93d78d53d0db3346acc2ee654cd051bcfbe58cb1/Screenshot%202023-11-17%20at%204.07.48%E2%80%AFPM.png)

FYI @laucon, @taylojill, @BSmolensky
