### ISSUE TITLE
[spike] DR | Investigate Sentry form errors

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#65758]
## Value Statement
**_As a_**  developer
**_I want to_** determine if the listed Sentry errors are blocking Veterans from submitting forms
**_So that_** we can fix the bug & remove blockers

## Background Context

In our weekly review of Sentry errors, the following Sentry errors:

- All apps: [Cannot read properties of undefined (reading 'version') TypeError](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?field=message&name=Supplemental+Claims&project=4&query=level%3Aerror+message%3A%22Cannot+read+properties+of+undefined+%28reading+%27version%27%29+TypeError%2A%22&sort=-message&statsPeriod=7d&widths=-1) (41.5k started 9/14)
- All apps: [e is undefined TypeError](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?field=message&name=Supplemental+Claims&project=4&query=level%3Aerror+message%3A%22e+is+undefined+TypeError+%2A%22&sort=-message&statsPeriod=7d&widths=-1) (2.1K started 9/14)
- All apps: [undefined is not an object (evalutating 'e.version') TypeError](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?field=message&name=Supplemental+Claims&project=4&query=level%3Aerror+message%3A%22undefined+is+not+an+object+%28evaluating+%27e.version%27%29+TypeError%2A%22&sort=-message&statsPeriod=7d&widths=-1) (25.2k started 9/14)
- All apps (mostly static pages?) [undefined is not an object (evaluating 'ceCurrentVideo.currentTime') TypeError](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?field=message&name=Supplemental+Claims&project=4&query=level%3Aerror+message%3A%22undefined+is+not+an+object+%28evaluating+%27ceCurrentVideo.currentTime%27%29+TypeError%2A%22&sort=-message&statsPeriod=7d&widths=-1) (195, ongoing)
- Unknown apps (seen with SC): [null is not an object (evaluating 't.blacklistC') Error](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?field=message&name=Supplemental+Claims&project=4&query=level%3Aerror+message%3A%22null+is+not+an+object+%28evaluating+%27t.blacklistC%27%29+Error+%2A%22&sort=-message&statsPeriod=7d&widths=-1) (103, ongoing)
- Unknown apps (seen in HLR): [undefined is not an object (evaluating '(a=Oe(r)).then') TypeError](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?field=message&name=Notice+of+Disagreement&project=4&query=level%3Aerror+AND+message%3A%22undefined+is+not+an+object+%28evaluating+%27%28a%3DOe%28r%29%29.then%27%29+TypeError%2A%22&sort=-message&statsPeriod=7d&widths=-1) (7, ongoing)

## Tasks
- [ ] Investigate cause of these errors
- [ ] Report platform owned fixable errors to platform
- [ ] Fix team-owned fixable errors
- [ ] Log third party (unfixable) errors

## Definition of Done
- [ ] Determine cause of each error
- [ ] Create tickets for fixable errors
- [ ] Tickets for platform reported to them

## Acceptance criteria
- [ ] All tasks complete

**Comment by saderagsdale** [comment]
Duplicate of #66883
