### ISSUE TITLE
ARM: General UX Research 

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#65753]
## Product Outline
[MVP Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/mvp.md)

## High Level User Story/ies
As a product team looking to build an MVP, we need to outline details of what we're building, create designs and conduct a usability test, so we can develop an informed MVP with the user experience in mind.

## Definition of done
Product:
- [x] The MVP has been outlined
Design:
- [x] There is a working user flow that the team agrees upon
- [x] The user flow has been translated into wireframes
- [ ] The wireframes have been translated into a working prototype that can be used to guide development and an initial usability test plan
- [ ] Additional design screens have been created to guide development
Research:
- [x] A user test plan has been outlined
- [ ] The test plan has been updated with any team feedback
- [ ] The test plan has been approved in Research Review
- [ ] Findings from the usability test have been shared with the team
