### ISSUE TITLE
Design | Dependent Verification Email Template

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#65761]
## Issue Description
_Draft the email template for the dependency verification email. See [prototype](https://www.sketch.com/s/149b2ccf-af21-4c71-9ca8-2ef2ae8af9fc)._

---
## Tasks
- [x] Draft email copy and obtain CAIA and OCTO stakeholder approval
- [x] Add the [email copy](https://docs.google.com/document/d/1iSO7jTqeA2wM-7S2sYqjt6sFoJp7h_AtEIaSz_dqTYQ/edit#heading=h.zptou6y925s), links, and pdf attachment to the VA Notify email template. [Staging](https://staging.notifications.va.gov/) | [Production](https://notifications.va.gov/)
- [ ] Final check on email content with Brandi
- [ ] Test email for formatting issues

## Acceptance Criteria
- [x] Email copy signed off on by CAIA and stakeholders
- [ ] Email template ready for deployment
---

**Comment by juliepedtke** [comment]
CAIA completed their review and I've updated the Sketch file. I'd like to review the final copy with Brandi during our sync on Monday. Then we should be ready for handoff! @steele-lm would testing fall under a separate FE engineering ticket?
