### ISSUE TITLE
VA Notify Dependency Verification Email Trigger

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#65760]
## Issue Description
_The VA Notify team has requested a trigger that will initiate the emails we are sending to Veterans encouraging them to verify their depenedents._

## Resources
- Fred Khoury on Team Umbrella. He wrote VA Notify triggers for the pension and burial form deactivation project.
- [VA Notify Platform Overview](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/README.md#successes)
- [VA Notify GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-notify)
- [VA Notify Playbook](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/VA%20Notify%20Playbook.pdf)
---
## Tasks
- [ ] Review VA Notify API docs (This [link](https://staging.notifications.va.gov/developer/api_docs) was in the VA Notify Playbook, but it's broken!)
- [ ] Get access to the Self Service Portal
- [ ] Build notification code to call the VA Notify API for Veterans with dependents on their benefits.
   - [ ] The default email address should be the email the user entered into the 686 form. If no email exists within the form, use their MyVA profile email.
   - [ ] The email should be sent once every 12 months.
- [ ] Test notification by logging into staging with a test user, updating the profile ID to something that sends to you
- [ ] Identify how many emails will be sent and notify VA Notify Team. Not to exceed 15 emails per second.

## Acceptance Criteria
- [ ] A notification trigger that sends an email to Veterans with dependents on their benefits once every 12 months.

**Comment by steele-lm** [comment]
This work is on hold until a discussion between VA.gov and VBA confirms the approach to this (and who owns sending the email).
