### ISSUE TITLE
ARM UX Flow Revisions

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#65768]
## Issue Description
Update user flows and starting logic for representative search, selection, 21-22 form and submission flow.

---
## Tasks
- [x] Meet with team
- [ ] Update based on feedback and send inputs to team
---
## Acceptance Criteria
- [ ] Completed flow for Wednesdays brainstorm

**Comment by jfinnerty13** [comment]
User Flow Updates
1. Removed VSO Rep and additional steps
2. Added Branch of Service to unauthenticated flow as it was missing
3. Found Relationship to Borrower widget, added into Claimant section
4. Removed Terms & Conditions as it’s own page and added into the review page

Open User Flow Questions
1. Should we allow edits to personal information to update the Veterans profile on VA.gov?
2. Can claimants have authentication? Do we have data stored on claimants?

Future Pages
1. Informational Page
    1. Team discussed recommending updating information on VA.gov https://www.va.gov/disability/get-help-filing-claim/ to reflect representative information
        1. Recommend cross referencing: https://www.benefits.va.gov/vso/
2. Profile Integration
    1. Need to identify the team we should be collaborating with for profile integration for:
        1. Viewing current representative
        2. Viewing previous 21-22 forms
        3. Notifications pertaining to representatives
3. Navigation Integration
    1. Are we anticipating integration into the navigation? Or keeping the form where it lives today?

User Questions
1. Thoughts on the different types of representatives?
2. Thoughts on attorney vs lawyer?
3. Where would users go to find a representative on VA.gov today?

VSO/VA Questions
1. To ask OGC & VSO/ How often is VSO Representative option used on PoA?
    1. Why is it typically used?
    2. In the meantime remove VSO Representative from flow as it causes increased complications by removing VSO access.
2. What is insurance information used for on PoA? What should Veterans put here?
3. What information can Veterans NOT edit online?
    1. Need to know about SSN, VA file number, service number and branch of service
    2. Name and date of birth cannot be edited online
        1. https://www.va.gov/resources/managing-your-vagov-profile/
