### ISSUE TITLE
Pivot from Airtable to Optimal Workshop for feedback 

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#65771]
## Purpose
We recently learned that Airtable wasn't allowed behind the VA network wall.  Survey Monkey is supposed to be. BUT then we learned that is not; our available option is Optimal Workshop, which allows surveys ([called Questions](https://support.optimalworkshop.com/en/collections/1524596-questions) for some reason).

We need to learn is this is true, and how to access the account if the Platform has one, so that we can transfer the survey mechanisms to OW.

Documentation on OW access [here](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-OptimalWorkshop) and use Platform.

## Tasks
- [x] Gain access to OW account
- [x] Set up [test survey page](https://dj540s05.optimalworkshop.com/questions/kib72wnb) from OW
- [x] Transfer Feedback Portal to OW?
- [x] Find method for getting OW data to Domo?
- [x] [Draft comms](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2791866882/Comms+for+new+Portal+page+and+link) to share out change and new link
- [x] Team review of comms
- [x] Edit all pathways to Portal with new link 
- [x] Send out comms

## Acceptance Criteria
- [ ] Portal is available to VFS teams
- [x] Edit automated messages about Portal via Slack (vfs-all-teams, vfs-platform-support) (Taylor)
- [x] Edit bookmarked messages about Portal (vfs-platform-support) (Taylor)

**Comment by twoangstroms** [comment]
Rolling over to next sprint. Delayed due to injury; play will resume shortly.

**Comment by twoangstroms** [comment]
From Naomi – what, if any, database or spreadsheet could be used to store data (and get it to Domo).

Cannot use Google Sheets, cannot use Airtable. Can only use Microsoft products. 

This is currently in discussion and may be a blocker (see Naomi).

**Comment by twoangstroms** [comment]
THOUGH: Using [File Upload Connector](https://domo-support.domo.com/s/article/360043436573?language=en_US), it might be possible to download OW data to a CSV file and manually create cards from that file?
