### ISSUE TITLE
[Eng] 10-10EZ - Update process for LOA3 users not found in BGS

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#65772]
## Background
With the impending Sept 30th deadline for PACT Act special enrollment, there is additional scrutiny on the 10-10EZ performance.  
We addressed the  issue of receiving excessing 500 errors when calling BGS with a LOA1 user (ticket #65406), which was to stop calling BGS.

Now we need to look at the process to call BGS, and what returns when we have an MPI record found for the LOA3 user, but they are not in BGS. 

If the user is found in MPI, but no SSN is returned, then do not call BGS.

**Original post from Patrick Vinograd 9/18/2023**
>If you have a LOA3 account, you are in MPI - the act of signing in to [VA.gov](http://va.gov/) creates a record for you in MPI if one did not already exist
>And your SSN is recorded there, as received from the credential provider (ID.me/Login.gov).
>You' won't be in BGS or have a rating, obviously. Ideally we should be getting at 4xx error from BGS and mapping that through correctly, but I don't know if that's the case now.

**Additional post from Patrick Vinograd 11/10/2023**
>I was noticing the 500 errors on rating_info as I was perusing datadog - I think it would be semantically more accurate if vets-api returned a 404 for those requests, assuming it is expected/normal for some users to not have any rating info. And you can mark them as not counted against your error rate using the `IgnoreNotFound` controller concern in vets-api.
If that's true (no data expected for some users) this would clean up some noise in datadog if it was resolved.

## Tasks
- [ ] Update the logic to return a 4xx (403 or 404 suggested above) for users that do not have a disability rating in BGS
     - Currently returns 500 error, causing noise in Datadog and triggering additional reviews that are unnecessary 
- [ ] Validate in testing
- [ ] Release to production
- [ ] Validate in prod and monitor error logs

## Acceptance Criteria
- The error returned from rating_info request should be 403 or 404 for users who do not have a disability rating.

**Comment by jadon1979** [comment]
@longmd

**Comment by hdjustice** [comment]
Re-opening ticket - still seeing a lot of 500 errors on rating_info endpoint requests.  See Patrick Vinograd's message below:

> I was noticing the 500 errors on rating_info as I was perusing datadog - I think it would be semantically more accurate if vets-api returned a 404 for those requests, assuming it is expected/normal for some users to not have any rating info. And you can mark them as not counted against your error rate using the IgnoreNotFound controller concern in vets-api.
> If that's true (no data expected for some users) this would clean up some noise in datadog if it was resolved.

**Comment by hdjustice** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/f69a4227-e5c3-47f8-8968-097ce83fae8c)

[Datadog Performance dashboard](https://vagov.ddog-gov.com/dashboard/8yz-qzc-bng/1010ez-vagov-performance?fullscreen_end_ts=1701179467379&fullscreen_paused=false&fullscreen_refresh_mode=sliding&fullscreen_section=overview&fullscreen_start_ts=1701006667379&fullscreen_widget=3141102492295084&refresh_mode=sliding&from_ts=1701006620515&to_ts=1701179420515&live=true)
