### ISSUE TITLE
Design | Pension Reactivation - Communication

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#65785]
## Issue Description
_Determine how to communicate the re-launch of the pension form._

---
## Tasks
- [ ] Determine what pages on VA.gov need to communicate the relaunch.
- [ ] Determine what pages that were updated as part of the deactivation need to have changes rolled back (e.g. redirects)
- [ ] Determine how to communicate the pension form's reactivation to Veterans (e.g., email).

## Acceptance Criteria
- [ ] Sketch file for any design elements.
- [ ] Copy for any Veteran-related communication
---
