### ISSUE TITLE
Update DataDog Alerts to Remove Burial/Pension Notifications

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#65780]
## Issue Description
_Alert in DataDog are currently set to trigger when forms are unavailable. When the pension and burial forms are temporarily removed, the alerts should be temporarily disabled._

---
## Tasks
- [ ] Temporarily disable DataDog alerts for pension and burial forms that are triggered when forms are not available.

## Acceptance Criteria
- [ ] Datadog alert for pension form availability is temporarily deactivated.
- [ ] Datadog alert for burial form availability is temporarily deactivated.
---

**Comment by steele-lm** [comment]
No longer needed bc burial form was not deactivated.
