### ISSUE TITLE
ARM MVP Search + Select User Test Kick-off

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#65788]
## Issue Description
User test for ARM MVP experience covering representative:
1. Search
2. Select
3. 21-22 digital form
4. 21-22 PDF generation
---
## Tasks
- [ ] Create workshop materials
- [ ] Run workshop
- [ ] Send next steps
- [ ] Create planning ticket
---
## Acceptance Criteria
- [ ] Clear next steps to create research plan

**Comment by jfinnerty13** [comment]
Kick-off complete: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695048973902/e0d3a50f8566e744ae0e07c606b254064a3e8c05?sender=u1d7fe27ad03a782e135e8404
