### ISSUE TITLE
Design | Pension Reactivation - Process for In-progress Applications

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#65784]
## Issue Description
_Determine an approach for how to handle in-progress applications when the pension form is reactivated._

---
## Tasks
- [ ] Determine how to figure out if users with an in-progress digital claim submitted a paper claim during the digital form deactivation period.
- [ ] Determine how to handle in-progress applications that have not been submitted. Do we transition their data to the new form and notify them?

## Acceptance Criteria
- [ ] User flow for reactivation.
- [ ] Sketch file for any design elements
---
