### ISSUE TITLE
HLR | Refactor "focusRadioH3" util into shared file

### ISSUE THREAD

**Issue by rocio-desantiago** [department-of-veterans-affairs/va.gov-team#65798]
## Value Statement

**_As a_** developer
**_I want to_** refactor the common utils shared across the 3 forms: 995, 996 and 10182 (SC, HLR & NOD)
**_So that_** tech debt is reduced and so that future developers don't have to make the same change across the shared utils in SC, HLR & NOD redundantly.

## Background Context

- Research was completed with the assistance of GitHub codeclimate.
- Related ticket: [DR | Refactor utils into shared directory](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63133)
- The following files will be refactored into one shared utils directory:

**focus**

> [src/applications/appeals/996/utils/focus.js](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/996/utils/focus.js)
  - `focusRadioH3`

## Out of scope

* Other apps/forms not in Decision Reviews

## Tasks

- [ ] Function moved into existing shared file
- [ ] Unit tests updated (if applicable)
- [ ] Monitor Datadog and Sentry to confirm changes don't cause unforeseen errors in forms submission activity.

## Definition of Ready 

- [x] Identify functions to be refactored: `focusRadioH3`
- [x] Have access to decision reviews folder (src/applications/appeals/{appName}/utils) in vets-website repository 
  > 995 - Supplemental Claims (src/applications/appeals/995/utils)
  > 996 - Higher Lever Review (src/applications/appeals/996/utils)
  > 10182 - Notice of Disagreement (Board Appeal) - (src/applications/appeals/10182/utils)

## Definition of Done

- [ ] Functionality not changed
- [ ] Reduced files
- [ ] CodeClimate warnings go away and duplication in the PR is marked as fixed

**Comment by rocio-desantiago** [comment]
Related: 
The React Scroller `scrollTo` function doesn't accept class names, so we need to target something with a name attribute above the link - the bug is that a a class selector was passed in
