### ISSUE TITLE
[Epic] Claim Status Tool big redesign IA/a11y/content audit and workshopping

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#65808]
**Background:**
The claim status tool team is considering a large-scale redesign in the coming quarters to address navigation, IA, and experience issues with the tool. We want to work closely with them at the foundation of the project to influence IA/a11y/content.

**CAIA Goal:**
As part of that work, let's come together to 
1. Audit the claim status tool for issues from a CAIA perspective
2. Start working towards a taxonomy of the main objects in the claim ecosystem: claim, decision review, request, letter, and document. 
3. Experiment with and share IA design for the tool that eliminates current IA/a11y concerns.

**Current work plan:**
- [ ] Prep for workshop with CST team on Tuesday 9/19
- [ ] Workshop with CST team tuesday 9/19
- [ ] Create next steps post workshop, and create tickets as needed for that work

**Comment by kristinoletmuskat** [comment]
Object map location: https://github.com/orgs/department-of-veterans-affairs/projects/1098/views/1

**Comment by kristinoletmuskat** [comment]
And here is the original CST OOUX discovery mural: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1685651799860/5650343beef05a9a54338afb385bef5cdd189485?sender=ua67f17f1c416a96ea04d2476
