### ISSUE TITLE
DR | Refactor "submit" functions into shared file

### ISSUE THREAD

**Issue by rocio-desantiago** [department-of-veterans-affairs/va.gov-team#65802]
## Background Context

- Research was completed with the assistance of GitHub codeclimate.
- Related ticket: [DR | Refactor utils into shared directory](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63133)
- The following file will be refactored into the existing shared helpers file:`src/applications/appeals/shared/utils/helpers.js`

**submit**

> [src/applications/appeals/996/utils/submit.js](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/996/utils/submit.js)
> [src/applications/appeals/10182/utils/submit.js](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/10182/utils/submit.js)
> [src/applications/appeals/995/utils/submit.js](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/995/utils/submit.js)
  - Functions to be refactored: 
    - `getContestedIssues`
    - `addIncludedIssues`
    - `getPhone`
    - `createIssueName` 
    - `removeEmptyEntries`

> ~[src/applications/appeals/10182/utils/helpers.js](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/10182/utils/helpers.js)~ **Already completed in NOD work** ✅ 

## Out of scope

* Other apps/forms not in Decision Reviews

## Tasks

- [ ] Function moved into existing shared file
- [ ] Unit tests updated (if applicable)
- [ ] Monitor Datadog and Sentry to confirm changes don't cause unforeseen errors in forms submission activity.

## Definition of Ready 

- [x] Identify functions to be refactored
- [x] Have access to decision reviews folder (src/applications/appeals/{appName}/utils) in vets-website repository 
  > 995 - Supplemental Claims (src/applications/appeals/995/utils)
  > 996 - Higher Lever Review (src/applications/appeals/996/utils)
  > 10182 - Notice of Disagreement (Board Appeal) - (src/applications/appeals/10182/utils)

## Definition of Done

- [ ] Functionality not changed
- [ ] Reduced files
- [ ] CodeClimate warnings go away and duplication in the PR is marked as fixed

**Comment by rocio-desantiago** [comment]
So far:
getContestedIssues
addIncludedIssues
getPhone
createIssueName
~removeEmptyEntries~

**Comment by rocio-desantiago** [comment]
Not able to take out from 10182:
`getContestedIssues`, `addIncludedIssues` or `createIssueName` because data name is `Contestable` vs `Contested`

**Comment by rocio-desantiago** [comment]
`getPhone` different in 995, should we update all with that format?

**Comment by rocio-desantiago** [comment]
Moved `getPhone` for 996 and 10182 only because they're the same while 995 remains different and keeps `getPhone` separately.
