### ISSUE TITLE
HLR | Refactor "disagreement" function into shared file

### ISSUE THREAD

**Issue by rocio-desantiago** [department-of-veterans-affairs/va.gov-team#65803]
## Background Context

- Research was completed with the assistance of GitHub codeclimate.
- Related ticket: [DR | Refactor utils into shared directory](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63133)
- The following file will be refactored into the existing shared helpers file:`src/applications/appeals/shared/utils/areaOfDisagreement.js`
 
**disagreement**

> ~[src/applications/appeals/10182/utils/disagreement.js](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/10182/utils/disagreement.js)~ Already completed in NOD work ✅
> [src/applications/appeals/996/utils/disagreement.js](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/996/utils/disagreement.js) 
  - 995 Functions to be refactored: 
    - `copyAreaOfDisagreementOptions `

## Out of scope

* Other apps/forms not in Decision Reviews

## Tasks

- [ ] Function moved into existing shared file
- [ ] Unit tests updated (if applicable)
- [ ] Monitor Datadog and Sentry to confirm changes don't cause unforeseen errors in forms submission activity.

## Definition of Ready 

- [x] Identify functions to be refactored
- [x] Have access to: 996 - Higher Lever Review (src/applications/appeals/996/utils)

## Definition of Done

- [ ] Functionality not changed
- [ ] Reduced files
- [ ] CodeClimate warnings go away and duplication in the PR is marked as fixed
