### ISSUE TITLE
Bulkhead Pattern Implementations Moving Forward

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#65826]
**Description:** 

The team has identified that our current implementation of the bulkhead pattern in certain services may not be necessary or could be optimized better post PACT Act submissions. This issue tracks the task of analyzing and potentially tearing down these implementations.

**Background:**

The bulkhead pattern has been previously implemented to isolate failures (or potential failures) in parts of the system so that they don't cascade. However, there are areas where the pattern might not be delivering the expected benefits, or where it might be adding unnecessary complexity.

**Tasks:**

1. **Analysis:** 
    - Review all services that use the bulkhead pattern.
    - Identify the benefits and drawbacks in each implementation.
    - Document any areas where the pattern might be causing performance issues or other unintended consequences.
    
2. **Recommendations:** 
    - For each service, recommend whether to retain, adjust, or remove the bulkhead pattern.
    
3. **Teardown/Adjustments:** 
    - For services where teardown is recommended, execute the removal in a way that doesn't compromise system reliability.
    - For services where adjustments are recommended, execute the modifications accordingly.
    
4. **Testing:**
    - Ensure thorough testing post modifications to confirm system stability and performance improvements.
    
5. **Documentation:**
    - Update architecture documentation to reflect any changes.
    - Document reasons for removal or modifications for future reference.

**Acceptance Criteria:**

- [x]  All services reviewed and decisions made regarding the continuation, modification, or removal of the bulkhead pattern.
- [x] Any changes implemented are tested thoroughly.
- [x] Documentation is updated accordingly.

**Comment by LindseySaari** [comment]
We've decided that moving forward, we'd like to reduce the minReplica count for the bulkheads involved in the PACT Act. They are severely over provisioned. Having multiple bulkheads will help to isolate logs to a confined set of pods amongst general resilience benefits for the deployment as a whole. While bulkheaded, services/endpoints will be isolated making it more resilient and easier to debug. Bulkheading also improves stability, scacability and increases performance

**Comment by LindseySaari** [comment]
I've scaled down the pods to 2 minReplicas and things are still looking good and healthy (running the minimum across the board). I've updated documentation as well in the Vets API on EKS doc. See [bulkhead deployment pattern](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2452193284/Vets+API+on+EKS#Bulkhead-Deployment-Pattern) and example with image (titled: See bulkhead image below)
