### ISSUE TITLE
[FE] Display Message when there was an Error Retrieving Appointments

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#65825]
## Wireframes
- [Pre-Check-in: Arrived on appointment list but call to MAP VAOS failed - tasks to complete](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/8VAj17R)
- [Check-in: Arrived on appointment list but call to MAP VAOS failed - tasks to complete](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/VEKgKbl)
- Both Pre-check-in and Check-in: [Completed a task and then returned to appts list page (did not arrive from a text message link), but the call to MAP VAOS failed - no tasks to complete](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/K04p4qV)
- [Relevant annotations for screen reader considerations](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/x00YA1l) (use role="alert")

## Tasks
- [ ] [FE] **Display an error message when there was an error retrieving upcoming appointments**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
@benbrasso-agile6 @cgednalske where is the wireframe for the scenario where there are no appointments retrieved

**Comment by cgednalske** [comment]
It is [this one](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/v8V43G8) without the yellow alert. I don't think we have a board representing it on it's own. Will this work (to ignore the yellow alert) or would you like me to whip up one without it?

<img width="440" alt="Screenshot 2023-10-10 at 1 16 35 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/79372956/055b0965-5224-49e0-9775-334e3c4c5b59">

**Comment by loripusey** [comment]
I think we can work with this one, thanks @cgednalske

**Comment by loripusey** [comment]
I think I've gotten it straightened out
- [Ticket for MAP error](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65825) - i.e. this ticket
- [Ticket for no appointments were found in MAP](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67257)

@cgednalske can you take a look and make sure I have the right wireframe links on the right tickets?
thanks

**Comment by cgednalske** [comment]
@loripusey in the second ticket, might want to remove "error" from the first task so it reads "Display **a message** when there were no appointments that were found in MAP for the Veteran." It's not technically an error, so that might help keep them straight. Otherwise, all looks good to me!

**Comment by loripusey** [comment]
done, thanks @cgednalske

**Comment by brianseek** [comment]
@wullaski didn't you already complete this work?

**Comment by brianseek** [comment]
OH right! Sorry my brain was in a much state by this time on Friday
