### ISSUE TITLE
Partner Newsletter MVP

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#65820]
## Product Outline
[Partner Newsletter MVP Product Outline](https://vfs.atlassian.net/wiki/spaces/Contact/pages/2769944671/Product+Outline+Partner+Newsletter+MVP)

## High Level User Story/ies
As a VA or external contact center manager I need timeline and relevant information regarding VA.gov products and plans so I can inform and train my contact center employees and they can provide correct answers and handling to users calling in about VA.gov products. 

## Hypothesis or Bet
Our bet is that by providing consistent and relevant information to our partners, we will improve the overall experience of getting answers to questions about VA.gov products and tools and create a more collaborative environment for future coordination. 

## OKR
_Which Objective / Key Result does this epic push forward?_

### What must be true in order for you to consider this epic complete? 

- [ ] Identify what partners need in terms of information from the Veteran Support Team
- [ ] Develop an email list that includes key groups and high impact POCs for those groups
- [ ] Identify method for delivery of contact center
- [ ] Create template design to facilitate easy review and comprehension of information

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
