### ISSUE TITLE
[FE] Pre-Check-in: Tell Veteran that a Check-in Reminder will be Texted to Them 45-minutes before their Appointment

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#65832]
## NOTE
Needs to go behind the feature flag

## Wireframes
- [Sketch page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/0D0F05D2-2122-4599-9378-E03EEE32DB88/canvas)
- [Wireframe](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/uuid/A39E82E6-D3C4-4D3A-AF3D-DFE249533B96)

## Tasks
- [ ] [FE] **Display message on Pre-Check-in confirmation page to let the Veteran know that a Check-in reminder will be texted to them 45-minutes before their appointment**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by benbrasso-agile6** [comment]
@lee-delarm6 same thing here, can't get that PR ticket to load for me. Any screenshots of before/after to review?

**Comment by benbrasso-agile6** [comment]
LGTM
