### ISSUE TITLE
[FE] Pre-Check-in: Add Message to Confirmation Page to Let Veteran know a Check-in Reminder will be Sent 45-minutes before Appointment

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#65831]
## Wireframes
- 
## Tasks
- [ ] [FE] **Add Message to Pre-Check-in Confirmation Page to Let Veteran know a Check-in Reminder will be Sent 45-minutes before Appointment**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
