### ISSUE TITLE
FE-BE | Profile | Discovery: Real User Monitoring (RUM) in Datadog

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#65835]
## Background
Datadog’s Real User Monitoring (RUM) gives you end-to-end visibility into the real-time activity and experience of individual users. RUM solves four types of use cases for monitoring web and mobile applications

More details: https://docs.datadoghq.com/real_user_monitoring/

Platform Analytics Documentation - [Setup Real-User Monitoring (RUM) Dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/setup-real-user-monitoring.md#setup-real-user-monitoring-rum-dashboard)
## Tasks
- [ ] Meet with engineers that are already using this feature to understand how it's being used and how we can use it.
- [ ] Create tickets to implement feature.

## Acceptance Criteria
- [ ] Create tickets
- [ ] Review with team

**Comment by mtcA6** [comment]
Given the shift in personnel I think we should close this out for now. If we want to implement this we can at a later time and focused on a specific item.
