### ISSUE TITLE
[FE] Day-of Check-in: Update Content for Next-of-Kin 

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#65846]
## Wireframes
[Check-in](https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/MmxbkOm)

## Tasks
- [ ] [FE] **update content & design for next-of-kin for day-of check-in**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
