### ISSUE TITLE
BE | My VA | Onsite Notifications | Check table size

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#65848]
## Background
Onsite notifications are stored in the database, but are not purged.  We may need to create a job to keep the number of records from becoming too large.

## Tasks
- [ ] Determine number of records in onsite notifications table.
- [ ] Discuss a plan to cap the number if necessary
- [ ] Create a ticket for the work

## Acceptance Criteria
- [ ] Review findings with team and create any necessary tickets.
