### ISSUE TITLE
[FE] Pre-Check-in & Day-of Check-in: Update Content for Next-of-Kin 

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#65844]
## Wireframes
[Pre-check-in](https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/a/5noYVxd)
[Check-in](https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/0A4LJrV)

## Tasks
- [ ] [FE] **update content & design for next-of-kin information for in-person appointment**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
LGTM

**Comment by benbrasso-agile6** [comment]
LGTM

**Comment by loripusey** [comment]
@wullaski so this is in production now, correct?

**Comment by wullaski** [comment]
@loripusey Nope but I'll merge it now. I wanted to make sure it looked alright before it was pushed to prod.

**Comment by loripusey** [comment]
validated, closing
