### ISSUE TITLE
Update Design Artifacts for Release

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#65852]
## Description

Make sure that the production sketch file has the newest next of kin artboard. 

- Production - precheckin - in person appt page
- Production - precheckin - phone appt page
- Production - check in page
- Production - check in - travel reimbursement page 

## Tasks
- [x] Validate that final sketches (and/or poster) match what we are pushing to production. For example, a wireframe or content may have gotten out of date. 
     - [x] If sketch files aren't up to date and what engineering is pushing to production is correct, update sketch files to match what we're going to release to production with
     - [x] Notify FE if they missed something in that's in sketch that's supposed to be in production. Create a ticket and post it in Slack to notify them. 
- [x] Prepare [production prototype links](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/product#production-wireframes-in-va-sketch-cloud)

**Comment by benbrasso-agile6** [comment]
This is all set per my comment here - https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/65864

Sorry, I didn't realize that this ticket was assigned to you, but I just figured I'd knock it out and get it out of the way so we don't have to deal with it early next week. 

@ytsaoca you want to validate? https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744

**Comment by ytsaoca** [comment]
@ben-allen-oddball Looks good! I'll close this ticket.

**Comment by benbrasso-agile6** [comment]
TY!
