### ISSUE TITLE
Upgrade Sidekiq/Sikekiq Ent gems to tackle CVE-2023-26141

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#65858]
### Description
A new vulnerability in Sidekiq 6.5.7, CVE-2023-26141 was raised yesterday and blocked ALL PRs into vets-api. After attempting a simple upgrade of the `sidekiq` gem to the recommended version (7.1.3+), we quickly found that it required upgrading the `sidekiq-ent` gem, both of which introduced a slew of errors.

### Tasks
- [x] Temporarily ignore the vulnerability so that we can allow users to merge PRs - done, PR [here](https://github.com/department-of-veterans-affairs/vets-api/pull/13860)
- [ ] Upgrade Sidekiq to protect from the vulnerability - in progress [here](https://github.com/department-of-veterans-affairs/vets-api/pull/13853)
- [ ] #76737

### Acceptance Criteria
- [ ] [This PR](https://github.com/department-of-veterans-affairs/vets-api/pull/13853) is merged, upgrading the gems and removing lines ignoring the CVE

**Comment by ryan-mcneil** [comment]
Lowering priority on this upgrade for now. I'll hopefully get back to this next sprint.

Keeping a few resources handy:
* [Sidekiq changelog](https://github.com/sidekiq/sidekiq/blob/main/Changes.md)
* [Sidekiq 7.0](https://github.com/sidekiq/sidekiq/blob/main/docs/7.0-Upgrade.md)
* [Middleware changes](https://github.com/sidekiq/sidekiq/blob/main/docs/middleware.md)
* [More helpful Sidekiq upgrade info](https://www.mikeperham.com/2022/10/27/introducing-sidekiq-7.0)

**Comment by ericboehs** [comment]
We'll come back to this once we upgrade Rails to 7.x. It's our current understanding that we need to do that first.

**Comment by stevenjcumming** [comment]
Sidekiq 7 requires [redis-client](https://rubygems.org/gems/redis-client) gem instead of [redis](https://rubygems.org/gems/redis). redis-client is only compatible with Redis 6+. So we cannot upgrade sidekiq until we upgrade Redis. 

But if we upgrade Redis that will break [fakeredis](https://rubygems.org/gems/fakeredis) which doesn't support Redis 6+. 

However removing fakeredis may cause issues with [parallel_tests](https://github.com/grosser/parallel_tests)
