### ISSUE TITLE
[Design] Update content in background alert on pre-check-in confirmation page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#65869]
## Tasks

- [x] On the [pre-check-in confirmation page](https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/a/1V4bEok), we need to update the content in the background alert to the following: 

> Remember to check in on the day of your appointment and bring your insurance cards with you.

> When it’s time to check in, we’ll send you a text. 

Use this page - Design - [Send out 45 min check in text](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/0D0F05D2-2122-4599-9378-E03EEE32DB88/canvas#Version)

- [x] Also, create a feature page with this update in the pre-check-in sketch file

## AC

- [x] Sketch files completed 
- [x] Validate with UX team 
- [x] Ping Lori when complete so she can add it to FE team

**Comment by benbrasso-agile6** [comment]
@loripusey not sure which Epic this might belong to, can figure out at refinement

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/65869?planning-poker) with Zenhub @cgednalske @kellysmith1008 @ytsaoca @zach-park

**Comment by loripusey** [comment]
since it references the 45 minute reminder, I'm putting it with that epic

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 I'm confused on this ticket as to where the work is to be done: it states the pre-check-in confirmation page, but the "put it here" link links to the Unified experience. Am I doing this work for pre-check-in and unified? Or just unified? Sorry for the confusion on my part!

**Comment by kellysmith1008** [comment]
For now, I've put it in the [pre-check-in file under a feature page](https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/a/1Vemb4p) as instructed in the top of the ticket. I did rearrange the wording a bit - please let me know what you think. We may want to check the spacing with a VXer as it did require making the alert larger. If you approve of the content and design, I can also add it to the unified 45-minute design page as well.

**Comment by benbrasso-agile6** [comment]
I'll take a look

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 how's this look? 

https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/0D0F05D2-2122-4599-9378-E03EEE32DB88/canvas#Version

**Comment by kellysmith1008** [comment]
I just need to change some of the content - right now it says "bring your cards with you to you" - I originally had removed the "to your appointment" because I feel it's implied and we could reduce some of the content there by eliminating it. But we can add it back in. Let me update those two mock ups - mine and yours, and I'll ping you when it's ready.

**Comment by kellysmith1008** [comment]
Okie dokie - should be good to go now.

**Comment by benbrasso-agile6** [comment]
I was probably working at the same time you were. Can you drop a comment in here what you want it to say? Because, we also have to update in a bunch of other places.

**Comment by kellysmith1008** [comment]
This is the new content:
Remember to bring your insurance cards with you. On the day of the appointment, we’ll send you a text when it’s time to check in.
Thanks!

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 @loripusey The content for this artboard is complete and appears in the sketch files and just above. It's ready for frontend.

**Comment by benbrasso-agile6** [comment]
Agreed, ready to close

**Comment by loripusey** [comment]
Looks good, I like the "if ... has been implemented..."; closing

**Comment by benbrasso-agile6** [comment]
@loripusey I made a quick update to this page knowing that it's very likely 45 mins work becomes before more unified check in work. 

[Includes VEText and pre-check-in confirmation page changes](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/0D0F05D2-2122-4599-9378-E03EEE32DB88/canvas#Version)

[Just the VEText change for Rob, etc.](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/g1bYDVj#Version)
