### ISSUE TITLE
Identity reduced F & AV

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#65874]
## Description
In order to help reduce fraud and attack vectors within vets-website we need to document (dismiss or create issues) all items in the Security tab on Github

## Tasks
- [ ] Go through all items in the Security tab
  - [ ] Dismiss all unit/spec files that are displayed
  - [ ] Create issues for production code
- [ ] Create a document/report/demo of all items that display how much we've reduced the attack vectors

**Comment by parkerbees** [comment]
Moved to Jira. Closing.
