### ISSUE TITLE
Consider how best to combine Feedback Portal data and Survey

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#65884]
## Purpose
Prepare artifacts associated with the synthesis of the survey.  Our goal w/ the updated Survey is to be able to track changes qtr-over-qtr, and make these results easily accessed and absorbed by Leadership and Platform teams.

Need to move away from current manual methods toward standardized direction, particularly w/ Domo use.

Communicating these on Demo Day and a SDT Confluence space will help:
1) Communicate data to Leadership & Platform teams
2) Tell the story over time of progress or not

## Notes
- Important to relay info in a way that Leadership understands its significance, and hopefully is actionable for them as well when it comes to prioritization.

## Tasks
- [ ] Consider how best to [present the data](https://vfs.atlassian.net/wiki/spaces/AP/pages/2616164361/Metrics+for+Q1+2023+Platform+Satisfaction+Survey) in an interesting and quarter-over-quarter way
- [ ] Look into how Domo can help us present survey data

## Acceptance Criteria
- [ ] Domo's viability is evaluated as a tool for presenting survey data
- [ ] An updated display of survey data is ready to view

### Pivot:
This ticket's work has been address or modified by recent work and upcoming plans
