### ISSUE TITLE
Design | Update CH 31 Form

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#65899]
## Issue Description
_The Chapter 31 digital form is generating a pdf using an old version of the form. The digital form needs to be updated to align with the most recent version of the paper form._

[Old pdf](https://www.knowva.ebenefits.va.gov/img/vre/VAF%2028-1900.pdf)
[New pdf](https://www.vba.va.gov/pubs/forms/vba-28-1900-are.pdf)

### Staging or Production Link
[Staging Link](https://staging.va.gov/careers-employment/vocational-rehabilitation/apply-vre-form-28-1900/start)

### Prototype Link
[Mural User Flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684161597392/5c1f8869cf5d03b792c8b82cf19b39dc26c486c2?sender=u0e8ac1d6d7681bb7e1b80558)

### Test Users
vets.gov.user+24@gmail.com
[staging test user repository](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)

---
## Tasks
- [ ] Update digital form to include:
   - [ ] New form title
      - [ ] From: APPLICATION FOR VOCATIONAL REHABILITATION FOR CLAIMANTS WITH SERVICE-CONNECTED DISABILITIES
      - [ ] To: APPLICATION FOR VETERAN READINESS AND EMPLOYMENT FOR CLAIMANTS WITH SERVICE-CONNECTED DISABILITIES
   - [ ] Remove purpose (if included -- it was removed from the paper form)
   - [ ] Update instructions if needed
   - [ ] Add international number field
   - [ ] Add receive electronic communication opt in box
- [ ] Obtain CAIA approval

## Acceptance Criteria
- [ ] Wireframes for updated digital form that includes
   - [ ] new form fields
   - [ ] new form title
   - [ ] updates to instructions
- [ ] Add sketch file link to #65900

---
