### ISSUE TITLE
CH 31 Update Form

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#65900]
This ticket may need to be split apart.

## Issue Description
_The Chapter 31 digital form is generating a pdf using an old version of the form. The digital form needs to be updated to align with the most recent version of the paper form and the new fields need to be added to the json payload._

[Old pdf](https://www.knowva.ebenefits.va.gov/img/vre/VAF%2028-1900.pdf)
[New pdf](https://www.vba.va.gov/pubs/forms/vba-28-1900-are.pdf)

Sketch file (tbd)

---
## Tasks
- [ ] Update digital form to include:
   - [ ] New form title
      - [ ] From: APPLICATION FOR VOCATIONAL REHABILITATION FOR CLAIMANTS WITH SERVICE-CONNECTED DISABILITIES
      - [ ] To: APPLICATION FOR VETERAN READINESS AND EMPLOYMENT FOR CLAIMANTS WITH SERVICE-CONNECTED DISABILITIES
   - [ ] Remove purpose (if included -- it was removed from the paper form)
   - [ ] Update instructions if needed
   - [ ] Add international number field
   - [ ] Add receive electronic communication opt in box
- [ ] Update json payload to include the new fields:
   - [ ] internationalNumber
   - [ ] recieveElectronicCommunication
- [ ] Update generated pdf to include the new fields:
   - [ ] internationalNumber
   - [ ] recieveElectronicCommunication

## Acceptance Criteria
- [ ] Digital form updated to include
   - [ ] new form fields
   - [ ] new form title
   - [ ] updates to instructions
- [ ] json file updated to contains new fields
- [ ] generated pdf updated to include new fields
---

**Comment by emilytheis** [comment]
noted in email to VR&E that this should be done by Jan. RE: VA.gov 28-1900 inquiry
