### ISSUE TITLE
Initial meeting with Lighthouse API team to present needs

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#65911]
## Issue Description
We have a future goal of allowing veterans to submit their 21-22/21-22a forms to representatives digitally, and allowing representatives to accept/reject this submission. We currently do not have endpoints from Lighthouse API to support this, so we will be connecting with the Lighthouse team to further define our needs and how they can be of assistance.

---
## Tasks
- [x] Setup a meeting connecting our team with key players in Lighthouse
- [x] Define a path forward that everyone agrees on
- [x] Document the needs and the plan of action, including next steps

## Acceptance Criteria
- Notes from the initial meeting are documented
- A future meeting has been set to further define technical requirements

**Comment by oddball-lindsay** [comment]
Initial discussion was on 9/21, follow up for a deeper technical dive is scheduled for 10/10.

Notes stored in a Slack canvas: https://dsva.slack.com/docs/T03FECE8V/F05TTMJ9WG1
