### ISSUE TITLE
IA Tracker: 10-10EZR Form

### ISSUE THREAD

**Issue by jennymayoco** [department-of-veterans-affairs/va.gov-team#65919]
### Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

The team is digitizing the 10-10EZR form for updating health benefits information. The form can only be completed when signed in and only if currently enrolled in VA health care. The team will need a new URL, in addition to other IA feedback.

### Links

- [Intake Ticket #64095](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64095)

### Team

- Team Name: 10-10 Health Apps
- Designer: Hieu Vo
- Product Manager: Alex Seelig, Heather Justice
- Slack (_optional_): 1010-health-apps

### Timeline
_When does IA review need to be completed by? When is Midpoint Review?_

The 1010 team will need to have designs (including content, IA, and accessibility feedback) to their engineers by September 29.

Two main focus areas for the MVP due date are:
1. Any content, IA, or accessibility changes or feedback needed to keep a Veteran from getting blocked during the experience
2. Focusing in on the intro and confirmation pages since those are new and unique to this form
---

### Work Needed (if applicable)

- IA Spec: **Needed**
- Feedback for product team: **Needed**

### Tasks
Check all that apply.

- [ ] Create process ticket draft
- [ ] Watch Design Intent
- [ ] Determine IA deliverables
- [ ] Collaborate with CAIA
- [ ] Ask questions to product team
- [ ] Create IA Spec
- [ ] Mikki reviews IA Spec
- [ ] Share IA Spec with product team
- [ ] Update Site Map and VA.gov Mega IA sheet

## Acceptance Criteria
- [ ] Feedback is shared with product team in Intake Ticket.

**Comment by jennymayoco** [comment]
Here is the [working Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1694187967183/741f1aae088c1fa5892c6ee53eccec2e4c0342b5?sender=u79ee90295fdb006d7f463212) where we are exploring user flows, URLs, and site map/page placement

**Comment by kristinoletmuskat** [comment]
Updated the mural after convo with Sara and Aliyah, we're going to review it with the team tomorrow, and then I will create the IA spec

**Comment by kristinoletmuskat** [comment]
IA Spec doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/10-10ezr-online-form.md
