### ISSUE TITLE
Create a Design Document for AL2 Image Creation/Use - PRT

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#65934]
## Description ##
We need a Design Document for the Platform Reliability Team's work on AL2 Image Creation/Use. This document will serve as a way to collect and communicate our approach to this work. This document will contain details of the technical aspects, design/approach considerations and architectural decisions of the work.

Reference:
[Design Document Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/design-docs/design-doc-template.md)
NOTE: This template format can be used as a start point and customized as needed for our work.

---

## Tasks ##
- [x] Gather and consolidate all known requirements related to the AL1/AL2 work.
- [x] Outline the user flow, detailing how users interact with the AL1/AL2 work and any expected outcomes.
- [x] Document the system architecture, including relevant diagrams or flowcharts.
- [x] Detail any integration points, dependencies, and external interactions.
- [x] Seek peer review for the document and incorporate feedback.

## Acceptance Criteria ##
- [ ] The Design Document provides a clear and comprehensive overview of the AL1/AL2 work design and functionality.
- [ ] User flows and system interactions are well-documented with supporting visuals where needed.
- [ ] Integration points, dependencies, and external interactions are clearly enumerated.
- [ ] The Design Document has been reviewed by at least two peers and necessary changes have been incorporated.

**Comment by pjhill** [comment]
I started a draft of a design document here -- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/design-docs/2023-09-20-al1-to-al2-migration-process.md

**Comment by pjhill** [comment]
The design document has a draft in place, but I need to have a more detailed discussion with ben in order to hash out some of the details.

**Comment by pjhill** [comment]
I've solicited feedback and questions from the reliability team as well as everyone in the PEWS (Platform Engineering Work Stream) channel.

**Comment by pjhill** [comment]
I've poked people for feedback a few times. At this point, I think it might be a good idea to close this ticket, and if any feedback comes in then we can incorporate the feedback at that time.
