### ISSUE TITLE
Create AWS inventory Job for EC2 Instances

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#65933]
## Description ##
We need an automated job that fetches and maintains an inventory of our AWS EC2 instances. This will aid in keeping track of our infrastructure and ensuring we're in line with our resource and cost management goals.

---

## Tasks ##
- [ ] Design the mechanism to retrieve EC2 instance details from AWS.
- [ ] Implement a scheduled job (could be a Lambda function, EC2 instance with cron, etc.) to periodically fetch EC2 details.
- [ ] Store the fetched details in a structured format (e.g., in an S3 bucket or a database).
- [ ] Provide logging for the job execution and any errors.

## Acceptance Criteria ##
- [ ] EC2 instances in our AWS account(s) are listed and stored in a structured format.
- [ ] The job runs periodically without manual intervention.
- [ ] Errors during job execution are logged and can be easily reviewed.

## Stretch Goal ##
- [ ] Some view of the structured data is available for general Platform users

**Comment by JoeTice** [comment]
Not necessary to have a repeatable job running for this - can rerun periodically as a separate task.
