### ISSUE TITLE
NOD | Post-usability next steps

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#65948]
## Value Statement
**_As a_**  designer
**_I want to_** prioritize enhancements using the feedback from research findings 
**_So that_** we can work on designs that Veterans feel have the highest impact

---
## Background
The NOD enhancements validations research has been completed. Based on Veteran feedback, a majority of the enhancements require some form of revision, and a second round of research is recommended.

## Tasks
- [x] Review research findings
- [x] Prioritize design enhancements
- [ ] Find supporting quant data for prioritization
- [ ] Iterate on design based on Veteran feedback

## Artifacts
- [SKETCH](https://www.sketch.com/s/0424c51d-7818-43ea-8821-6de91eb7ab27/p/EFEBDA30-009D-4F17-B82A-2C2F3AF62D0D/canvas)
- [Notetaking / Synthesis Board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1694783805827/712f2f751c90535c85c3667f6f7cb5bf48b8ef0b?sender=u66cdae33e9ad6f7626739036)

## Revisions to prioritize
- Adding additional information: Major, but needs revision on approach
- Updating introduction: Major, needs revision on approach, may extend beyond NOD updates
- Adding links to DLD: Minor, inconclusive results for impact, but did not cause friction in research
- Detailed issue summary: Impact inconclusive in research
- Personalized disagreement selection: Impact inconclusive in research

### Possible additions to research
- Notifications design: Technology spike is complete, we could revisit opportunities
- Decision review pathway: As an extension of the work done on the introduction, could be a something we look into 

### Experimental design (to share with Forms team)
- Improved header: Major, positive response from Veterans
- Task list: Mixed, for those who used it, it was useful, for those who didn’t, it was unnecessary. - Needs revision on approach.
- Summary page: Major, negative response from Veterans to editing by section.

## Out-of-scope
- What should we take out?
- What should we continue to revise and move forward?

## Definition of Ready 
- [ ] Clear value description
- [ ] Reviewable acceptance criteria
- [ ] Research findings are complete
- [ ] Priorities are scoped

## Definition of Done
- [ ] Designs are approved by PO and ready to implement

**Comment by eileen-coforma** [comment]
Met with Sade for prioritization and established the following steps:
- Gather analytics / quant data to further prove out inconclusive / weaker signals. Sade will go to analytics OH today
- Email BVA to ask for the use case of ‘additional information’ on NOD (whether it adds to the processing time, and if it helps or hurts the Veteran’s decision)
- Pass on information about enhanced header and summary pages to the Forms team
- Figure out how to tackle areas in design where more investigation is needed.

**Comment by eileen-coforma** [comment]
There was one other finding/recommendation that I can’t tell if it’s a strong/weak signal.

> Several Veterans confused “add new issue” with adding additional contentions not yet claimed

- Effort to change the language is low.
- Impact to Veteran experience is not high or low. It prevents friction from entering a page they don’t need to, but it won’t impact their claim since they can’t move forward without a decision date.
- Could impact analytics data (decrease bounce rate on first add new issue)
- Could be carried over to other decision review forms where we use the same pattern.

**Comment by eileen-coforma** [comment]
Sent email to John & intake team

1. When and how are the ‘additional information’ attachments processed?
2. Does including an ‘additional information’ attachment impact processing time in any way?
3. What is the quality of responses for these ‘additional information’? Do Veterans normally attach a personal anecdote or is it a formal legal brief?
4. On average, does it increase or decrease the likelihood of favorable outcomes for the claim?
5. Is there any language we can use to clarify or direct Veterans on the use of the ‘additional information’ attachment, such as examples? The instructions on the current form is a bit vague.

1. Staff will do their best to determine if the additional information is pertinent to the 10182. If it is, then it stays with the 10182 and is either uploaded when docketed, or sent with the packet after pre-docketing to the appropriate business line for the evidence to be gathered. Once we get it back, then it is uploaded with the 10182 upon docketing. If the additional information is clearly unrelated, we’ll split the packet and send the info to VBA for processing.
2. Only to the extent of the time that it consumes for the staff member (and perhaps the supervisor) to analyze the information to determine what to do with it. Normally it will be processed at the same time as the 10182 – so the impact is that it decreases how many cases the staff can process in a given day.
3. Its all over the map. The most common is letters from the appellant or lay statements, copies of evidence, new evidence, VA correspondence, other VA Forms and POA briefs/argument.
4. Unanswerable – case by case
5. There is, but that would take some thought/discussion. It is not helpful for them to attach VA forms, especially something they’ve already submitted. Same for duplicate evidence. It MAY be helpful if they attach NEW evidence and they selected the evidence submission lane and it is definitely unhelpful if they submit evidence but selected the direct lane because the judge cannot consider it.

**Comment by eileen-coforma** [comment]
@saderagsdale I just realized I've been leaving comments on this ticket without tagging or assigning you...

**Comment by saderagsdale** [comment]
@eileen-coforma I'm keeping an eye on it lol

**Comment by saderagsdale** [comment]
@rubensun will work on qualitative approach to identifying signal strength.

**Comment by rubensun** [comment]
Previous content, posted below for archival purposes:

---

## Value Statement
**_As a_**  designer
**_I want to_** prioritize enhancements using the feedback from research findings 
**_So that_** we can work on designs that Veterans feel have the highest impact

---
## Background
The NOD enhancements validations research has been completed. Based on Veteran feedback, a majority of the enhancements require some form of revision, and a second round of research is recommended.

## Tasks
- [x] Review research findings
- [x] Prioritize design enhancements
- [ ] Find supporting quant data for prioritization
- [ ] Iterate on design based on Veteran feedback

## Artifacts
- [SKETCH](https://www.sketch.com/s/0424c51d-7818-43ea-8821-6de91eb7ab27/p/EFEBDA30-009D-4F17-B82A-2C2F3AF62D0D/canvas)
- [Notetaking / Synthesis Board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1694783805827/712f2f751c90535c85c3667f6f7cb5bf48b8ef0b?sender=u66cdae33e9ad6f7626739036)

## Revisions to prioritize
- Adding additional information: Major, but needs revision on approach
- Updating introduction: Major, needs revision on approach, may extend beyond NOD updates
- Adding links to DLD: Minor, inconclusive results for impact, but did not cause friction in research
- Detailed issue summary: Impact inconclusive in research
- Personalized disagreement selection: Impact inconclusive in research

### Possible additions to research
- Notifications design: Technology spike is complete, we could revisit opportunities
- Decision review pathway: As an extension of the work done on the introduction, could be a something we look into 

### Experimental design (to share with Forms team)
- Improved header: Major, positive response from Veterans
- Task list: Mixed, for those who used it, it was useful, for those who didn’t, it was unnecessary. - Needs revision on approach.
- Summary page: Major, negative response from Veterans to editing by section.

## Out-of-scope
- What should we take out?
- What should we continue to revise and move forward?

## Definition of Ready 
- [ ] Clear value description
- [ ] Reviewable acceptance criteria
- [ ] Research findings are complete
- [ ] Priorities are scoped

## Definition of Done
- [ ] Designs are approved by PO and ready to implement

**Comment by rubensun** [comment]
[Notetaking / Synthesis Board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1694783805827/712f2f751c90535c85c3667f6f7cb5bf48b8ef0b?sender=u66cdae33e9ad6f7626739036) mural link added to the body of the ticket.

**Comment by rubensun** [comment]
Working statement on aim, approach, and outcomes for this effort:

### Aim (`what`):
> Establish greater confidence surrounding the importance and rationale behind some of the opportunities identified.

### Approach (`how`)
> **Rough-sizing the import of Insights**
> Establish proxy-signals to rough size to identify `who` is impacted by different product hypotheses and insights 
> - Breakout of participants by archetype — learners vs doers.
> - Identify which insights are associated with which participant archetype by % makeup
> - Qualify limitations of the proxy signals based on the method of research

> **Developing a theory of impact**
> Further hypothesis establishing the criticality and severity of that impact between insights and how it shapes outcomes for users and the business.

>  **Hypothesis and Experimentation Framing**
> - Ideate following actions with stronger signals
> - Ideate following avenues of investigation with weaker or inconclusive signals

### Outcome (`why`)
> - The team has a more solid understanding of what bets stand to yield a more significant positive impact. 
> - Identify what additional areas of insight are required to inform our next set of delivery-oriented design and research initiatives.

**Comment by saderagsdale** [comment]
- Aim: Enable the team to check qualitative findings against quantitative data, to inform direction. 
- Approach: Establish a measure of signal strength. 
- Outcome: Identify 1) which findings are good candidates for comparison to quantitative data, and 2) which findings are too scant to be useful in measuring our hypotheses and require more digging (or a pivot).

**Comment by rubensun** [comment]
I’ll be tallying up how many respondents have supported or refuted our hypothesis and findings as a proxy for qual, and provide commentary on how importance may vary depending on the research method or type of insight.

Going into next week, we should find some time to review some of this work and discuss what qual data we could get to bolster our findings further.

**Comment by rubensun** [comment]
> > Several Veterans confused “add new issue” with adding additional contentions not yet claimed

The language change here is probably sufficient. (`Add issue` in place of `Add new issue`)
Worth us actioning on since the adjustment here is minor while the potential and consequence for it being misconstrued is great.

**Comment by HeatherWidmont** [comment]
@rubensun scheduled time on Monday (10:30am ET) to discuss what he's tallied

**Comment by HeatherWidmont** [comment]
Next step - Ruben, Eileen, DK finalize decisions & summarize in a thread

**Comment by rubensun** [comment]
- [Slack thread](https://dsva.slack.com/archives/C05FCEH2NRG/p1699977673797799?thread_ts=1699896221.213719&cid=C05FCEH2NRG) discussing next steps

Next steps as described in sprint review:

**Select and Validate Decision Review Pathway**
- Identified a desire for a more direct explanation of pathway use cases and rationale: We’ll be doing some desk research and consultation with VBA SMEs to develop better content
- Identified challenges with providing context through lengthy pages: 
We’re seeking to explore alternate interaction models for pathway selection and validation

**Gather Additional Information about the Appeal**
- Identified areas of confusion between additional information, other reason for disagreement and additional evidence: We’re exploring ways to reorganize form flow and language to provide greater clarity.

**Comment by saderagsdale** [comment]
I think this ticket served its purpose. Closing.
