### ISSUE TITLE
EVSS - Release Plan for PPIU

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#65954]
This ticket covers the discovery and release plan to deploy the migrated endpoint to LH for PPIU endpoint. The scope includes:

Release plan - look at staggered release
Can point to specific user through feature toggle
Tasks in the ticket

---
## Tasks
- [x] Send email to LH production team that we are using Production Client ID from Authenticated Exp team
- [x] Place the Client ID and RSA key in AWS parameter store
- [x] Confirm K8 manifest repository has references to correct environment variable paths https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests
- [x] Confirm how other teams are batching the release
- [x] Identify acceptance criteria for a successful run
- [ ] Establish Comms: put message out in evss migration slack channel -> [MOVING] to the Canary Launch ticket
- [x] Identify/document risks and mitigation
- [x] Build the dashboard for monitoring traffic for LH/EVSS

## Acceptance Criteria
- [x] Identify acceptance criteria for a successful run
- [x] Figure out how to monitor success(526ez form prefill, submit workflow)
- [x] Release plan; add to here https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/disability-experience/team-docs/Release%20Plans
- [x] Create Testrail testplan
- [x] Execute Testrun
- [x] Successful testrun
- [x] Create a ticket for starting the staggered release based on the plan
- [x] Risks have been documented
- [x] Built the dashboard for monitoring traffic for PPIU for LH/EVSS

## Release Plan Link
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/disability-experience/team-docs/Release%20Plans/DBEX%20PPIU-DirectDeposit%20Service%20Endpoint%20Migration%20Release%20Plan.md

## for testing in ArgoCD
```
# provider level
require './lib/disability_compensation/providers/ppiu_direct_deposit/lighthouse_ppiu_provider.rb'
icn = '1012740600V714187'
current_user = OpenStruct.new({icn:})
provider = LighthousePPIUProvider.new(current_user)
provider_data = provider.get_payment_information
```

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mchae-nava** [comment]
Just in case:
Release plans for templates: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/disability-experience/team-docs/Release%20Plans
Submit Dash as example: https://vagov.ddog-gov.com/dashboard/mqg-msb-htb/benefits---dbex---evss-to-lh-submit?refresh_mode=sliding&from_ts=1698949801846&to_ts=1699554601846&live=true
AE Dash for some existing queries: https://vagov.ddog-gov.com/dashboard/gra-npe-h52/authenticated-experience-cp-direct-deposit?refresh_mode=sliding&from_ts=1698938432258&to_ts=1699024832258&live=true

ACs may need some updating. I just realized they're from before we had templates going

**Comment by tommasina-va** [comment]
Canary Launch ticket [here](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/69391)
