### ISSUE TITLE
Content edits for #65742

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#65956]
## Info
Content edits according to [support ticket #65742](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65742)

## Tasks

- [x] Review [support ticket #65742](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65742) in detail
- [x] Determine solution for the request; We discussed idea of adding it to [this page](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-tools), but open to other suggestions.
- [x] Align on solution with Shira Goodman
- [x] Make content updates to the website accordingly

## Acceptance Criteria

- [x] Platform website will have somewhere that explains the following:

- Platform almost never uses email for sending/sharing information. Platform mostly uses email for event scheduling as needed.
