### ISSUE TITLE
Strategy Roadmap Contracted Team Review Process

### ISSUE THREAD

**Issue by SophiaPhilipMO** [department-of-veterans-affairs/va.gov-team#65958]
Context
As a contracted team, I need to know how I can give input on the CEDAR Identity strategy roadmap to ensure clarity of what each team is delivery and when

Acceptability Criteria
- [x] Process flow developed in PO sync
- [x] Confirm what LGA is responsible for in getting contracted team input
- [x] Confirm what OCTO is responsible for in getting contracted team input

Definition of Done
- [x] Initial outreach POC identified who leads strategy roadmap viewing and gathers feedback from contracted teams

**Comment by SophiaPhilipMO** [comment]
Resolved during 9/28 PO Sync, Tom will initiate contact
