### ISSUE TITLE
(Review comments section) Add page footers to pages missing it within Developer Docs

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#65955]
## Info

During our recent content review of Developer Documentation pages, the team has discovered pages with missing page footers, including parent pages with mostly sub-page navigation links.

Example: https://depo-platform-documentation.scrollhelp.site/developer-docs/code-and-build

## Tasks

- [x] Identify the number of pages we audited with a missing page footer. [Audit spreadsheet](https://docs.google.com/spreadsheets/d/1PPhlba7PiCTWkJUWKHxH36rck0lfKtBSjSpqrCCBxv0/edit?usp=sharing) for info.
- [x] Add the missing page footer **(19)** to these pages from Brian and Jill's sections (Lauren and Torri's have been completed).

## Acceptance Criteria

- [x] All pages audited within the Developer Docs section will have a page footer, including parent pages with mostly sub-page navigation links.

**Comment by BSmolensky** [comment]
All of the docs on my list that were missing a footer were also parent pages. Therefore, @laucon fixed all of mine already.

**Comment by rferguson13** [comment]
10/17: Added footers to all that needed them. Did not update anything else on the page.
