### ISSUE TITLE
[FSR] deprecate dmc/fsr service

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#65964]
## Issue Description
With the debts_api engine in prod for multiple weeks I think it's safe to start removing duplicate code living in debt_management_center
---
## Tasks
- [ ] deprecate fsr service
- [ ] deprecate specs
- [ ] deprecate form5655Submission model
- [ ] anything else?

## Acceptance Criteria
- [ ] FSR continues to function without deprecated code
- [ ] If work cannot be completed in Sprint, spin up another ticket.
---

**Comment by HeatherRienks** [comment]
Per BE Sync, let's add this to Sprint 110 (Oct 11 -24)

cc: @Tom-Davis

**Comment by kjsuarez** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/14133/
