### ISSUE TITLE
Setup boards for DI research w/ VFS teams

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#65966]
## Purpose
Setup the User Journey boards for use in the DI workshops, including instructions for teams to get a head start on the boards before their scheduled session.

## Tasks
- [x] Prep board for novice team
- [x] Prep two boards for experienced teams
- [x] Prep board for uninitiated team

## Acceptance Criteria
- [x] UJ boards are ready
- [x] Instructions are clear
