### ISSUE TITLE
Update Product Artifacts for Cancelled Appointment Message Change

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#65962]
## Description
Update various product artifacts, as necessary, based on this feature release: https://github.com/department-of-veterans-affairs/va.gov-team/issues/59639

## Tasks
- [x] Update the Pre-Check-in Product Guide, including content and screenshots, if necessary
- [ ] Update the eCheck-in Product Guide, including content and screenshots, if necessary
- [ ] Update user flow diagrams, if necessary
- [ ] Create a Content ticket with updated screenshots for changes to the Resources & Support (R&S) articles in VA.gov, if necessary
- [ ] Create a Contact Center review ticket & schedule a review
    - [ ] Put the link to the ticket in the main collab cycle ticket

## Acceptance Criteria
- [x] Product Guides are up-to-date and ready to be published to Git
- [x] ALL screenshots are of the highest quality possible
- [ ] [User flow diagrams are up-to-date](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/3Op54Vm) and ready to be merged in Abstract and pushed to sketch cloud
- [ ] R&D articles are up-to-date (or scheduled for publishing)
- [ ] Contact Center review has been scheduled

**Comment by benbrasso-agile6** [comment]
@loripusey does this ticket have a dependency on https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/59639

Or, should I just update the product guides based on the completion of https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/51866

**Comment by loripusey** [comment]
I am really confused by this whole cancelled appt thing. I thought we had decided to remove the message completely and that 51866 was no longer applicable. I'm going to schedule some time to touch base so that we can all get on the same page.

**Comment by benbrasso-agile6** [comment]
Could you join first part of UX Office hours at 2pm ET? It's on the CIE team calendar.

**Comment by loripusey** [comment]
yep, was planning to

**Comment by benbrasso-agile6** [comment]
Oh, Brian is OOO today.

**Comment by loripusey** [comment]
I have a SPIKE ticket for FE to determine if there is still an issue that needs to be resolved. I can't tell from the slack threads.
https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/59639

**Comment by benbrasso-agile6** [comment]
Thanks. I'll move forward with updating the product guide for now, related to #65962, which was implemented a while ago by engineeers.

**Comment by benbrasso-agile6** [comment]
Completed, up on git 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-guides/README.md
