### ISSUE TITLE
BE | Military Information | Data Schema for:  military occupational specialties

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#65978]
## Background 
Investigate what the backend data looks like for military occupational specialties in VA Profile.

## Tasks 
- [x] identify data structures and relationships
     - [x] eg. max and min values  
     - [x] field length and types
- [x] identify lookup values 
- [ ] share with researchers and get their thoughts 

## Acceptance Criteria 
- [ ] researchers feel comfortable with the documentation 
- [ ] we're ready to make steps on some lo-fi mocks for this section/key data element

**Comment by tpharrison** [comment]
Document - https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/military_info/va-profile-military-occupations.md
