### ISSUE TITLE
BE | Military Information | Data Schema for: units with which the Veteran or Service member served

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#65976]
## Background 
need to investigate what the backend data looks like for military information in VA Profile as it relates to units with which the veteran served. .

## Tasks 
- [x] identify data structures and relationships
     - [x] eg. max and min values  
     - [x] field length and types
- [x] identify lookup values 
- [x] share with researchers and get their thoughts 

## Acceptance Criteria 
- [x] reviewed by researchers

**Comment by andaleliz** [comment]
@mtcA6 I noticed the product outline states:
>According to VEO stakeholders, VA owns an API that can generate a PDF/text version of a veteran’s ILER record.

Will investigating this API be part of this discovery effort, or a separate effort in a different sprint?

**Comment by mtcA6** [comment]
@andaleliz Nope, that is not part of this/the data element tickets. I want the BE data element tickets focused on the data and not on ILER.

We can discuss this in more detail on Wednesday's refinement where I want to work as a team on a LOE. I'll have more set out in the mural board for Wednesdays call to help us with that (might snag 25 min w/you, if I can find time, to pick your brain ahead of Wednesday). 

I haven't written a ticket specific to ILER export access as I've been working on the side with Melissa to get us contacts and some more details. Currently, VBA has access/the ability and permission from DoD to generate PDFs of a veteran's ILER data. Melissa was working on confirming if VA.gov will need its own separate permission/authorization from the DoD or if we can use what has already been granted to VBA.

**Comment by pamela-drouin** [comment]
I read through it, and though it's technical, it's quite readable. I was able to follow along. Having answers to the outstanding questions you listed will be helpful as well.

**Comment by andaleliz** [comment]
@tpharrison I agree with @pamela-drouin, this is very readable and I feel like I was able to follow along too.  It'll be really interesting to see the example data that comes back. It _seems_ like the schema has more data points than are probably useful to surface on the FE, based on what I see here. Do both of you have that same sense?

**Comment by tpharrison** [comment]
@andaleliz Yes - we'd only be using a subset of the available fields.  Let's discuss this further when we get a chance.
