### ISSUE TITLE
BE | Military Information | Data Schema for: deployment locations and start and end dates of deployments

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#65977]
## Background 
need to investigate what the backend data looks like for military information in VA Profile

## Tasks 
- [ ] identify data structures and relationships
     - [ ] eg. max and min values  
     - [ ] field length and types
- [ ] identify lookup values 
- [ ] share with researchers and get their thoughts 

## Acceptance Criteria 
- [ ] researchers feel comfortable with the documentation 
- [ ] we're ready to make steps on some lo-fi mocks for this section/key data element

**Comment by tpharrison** [comment]
Documentation is here - https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/military_info/va-profile-military-history.md#lookups

**Comment by andaleliz** [comment]
@tpharrison do you know if we have access to a parent value that would give us a "deployment name" for each of these locations? One Veteran I talked to said they remember things by the deployment.

**Comment by tpharrison** [comment]
Is it the `deploymentProjectCode` and `deploymentProjectText` fields in the [Deployment Project](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/military_info/va-profile-military-history.md#deployment-project) dataset?

**Comment by andaleliz** [comment]
@tpharrison yes, I think so! Thank you for pointing me in that direction.
