### ISSUE TITLE
[Design] 10-10EZR Update Source of Truth Docs Post Staging Review

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#65971]
## Issue Description

Make sure the various source of truth documents are all updated with any final changes. 
Sketch file should be aligned but make sure source of truth and wireflow pages are up-to-date. 

---
## Tasks
- [x] Confirm sketch file is up-to-date
- [x] Update [Mural User Flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1694028488812/91947e4f4f9f8536af5a6609e54fced964d3505f?sender=uadf1ed7fe7c76f0914967329)
- [x] Update [Mural Alerts Audit](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1694028526633/a5d8eba28e3acaba46de92e99fb8013fd1a56d3d?sender=uadf1ed7fe7c76f0914967329)
- [x] Update [GitHub Content Source of Truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZR%20Form/10-10EZR-application-content.md)
- [x] Update [GitHub Alerts Matrix](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZR%20Form/10-10EZR-ErrorMatrix.md)

## Acceptance Criteria
- [x] All EZR source of truth docs align with MVP launch 
---

**Comment by jessicastump** [comment]
The alerts Mural board and github doc have been updated to align with changes/additions made for mvp.
