### ISSUE TITLE
BE/FE | Military Information | Discovery - find the data and map it

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#65974]
## Background 

Discovery ticket to track all of our "8 key data elements" we're only looking at the first 6 while the other two are being defined.

https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/military_info/data_structures.md

To support UX work, we really need to know the data structure, possible values, and any example data (if possible) for the [ data points requested by stakeholders for our MVP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/military-information/2023-enhanced-military-information/README.md#integrate-the-following-data-into-vagov).

1. dates of, and branches of, service (already supported)
2. units with which the Veteran or Service member served
3. deployment locations and start and end dates of deployments
4. military occupational specialties
5. training courses
6. military awards and decorations

Additionally, the following data would eventually be required, but VA leadership is currently determining requirements around this. This would not be MVP, but it might be efficient to look into them now as part of this discovery.
1. non-military deployment data
2. a registry that verifies participation in a TERA

```[tasklist]
### 6 data elements we need to investigate
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65975
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65976
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65977
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65978
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65979
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65980
```

**Comment by mtcA6** [comment]
@andaleliz moved your copy here
