### ISSUE TITLE
BE | Military Information | Data Schema for: dates of, and branches of, service (already in the profile)

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#65975]
## Background 
need to investigate what the backend data looks like for military information in VA Profile

## Tasks 
- [x] identify data structures and relationships
     - [x] eg. max and min values  
     - [x] field length and types
- [x] identify lookup values 
- [x] share with researchers and get their thoughts 

## Acceptance Criteria 
- [ ] Confirm that military info data we are looking for exists or not
- [x] The info found is posted in the team sensitive info repo in GitHub

**Comment by tpharrison** [comment]
@mtcA6 This dataset has been documented in the [VA Profile: Military History](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/military_info/va-profile-military-history.md) document.

I'm going to close it out and pull #65979 into this sprint.

**Comment by andaleliz** [comment]
@tpharrison this is so helpful, thanks for putting this all together! One bit o' feedback:

I noticed in the [diagrams here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/military_info/va-profile-military-history.md#what-does-the-data-model-look-like) some of the data types are listed as `ref` but in the [unit assignment doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/military_info/va-profile-military-unit-assignments.md#what-does-the-data-model-look-like), similar combos (text and codes) are listed as `string(ref)`.  Are they the same thing in both docs? If so, I think it'd be helpful to make an update so they're represented consistently across all the docs.

**Comment by tpharrison** [comment]
I update them all to `string(ref)`.  Thanks!
