### ISSUE TITLE
BE | Military Information | Data Schema for: military awards and decorations (check in late Nov 2023)

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#65979]
## Background 
need to investigate what the backend data looks like for military information in VA Profile

## Tasks 
- [ ] identify data structures and relationships
     - [ ] eg. max and min values  
     - [ ] field length and types
- [ ] identify lookup values 
- [ ] share with researchers and get their thoughts 

## Acceptance Criteria 
- [ ] researchers feel comfortable with the documentation 
- [ ] we're ready to make steps on some lo-fi mocks for this section/key data element

**Comment by tpharrison** [comment]
The `Military Personnel API` provides an endpoint for medals and awards data, but we use the `Profile v3 API` for retrieving military information.

I'm not sure how to get this data using the Profile v3 API.

I reached out to Mike Richard.

**Comment by tpharrison** [comment]
Michael Richard responded...
> Tom, Medals-awards is not there yet.  Expected in VADIR in November and VA Profile in December-ish.  Waiting on DOD feed to VADIR. 

> If you want to look at the BIO's early, they are in INT  and you can look at them here [https://int.vaprofile.va.gov:7005/profile-service/swagger-ui/index.html?configUrl=%2Fprof[…]-docs%2Fswagger-config&urls.primaryName=ProfileServiceV3](https://int.vaprofile.va.gov:7005/profile-service/swagger-ui/index.html?configUrl=%2Fprofile-service%2Fv3%2Fapi-docs%2Fswagger-config&urls.primaryName=ProfileServiceV3#/Profile-v3/getProfile)  under the MedalsAndAwardsBio.   Remember, it may be subject to Change.  You need to be on VA network with PIV.

**Comment by tpharrison** [comment]
@mtcA6 Do you want me to move this to the backlog or to blocked?

**Comment by mtcA6** [comment]
@tpharrison i think backlog
if we were to look for this data somewhere else, do we know where that might be?

**Comment by tpharrison** [comment]
Ok - I'm not sure.

**Comment by mtcA6** [comment]
not needed
