### ISSUE TITLE
BE | Military Information | Data Schema for:  training courses

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#65980]
## Background 
Investigate and document what VA Profile data looks like for military training courses.

## Tasks 
- [ ] Identify data fields,  relationships, and types

## Acceptance Criteria 
- [ ] Post documentation to va.gov-team-sensitive repository.
- [ ] Share link with team members to review.

**Comment by mtcA6** [comment]
not needed right now
