### ISSUE TITLE
EVSS - Monitor Benefits Claims Service Dashboard 

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#65986]
## Issue Description
Create a DD Dashboard to allow us to monitor 526 Benefits claim service requests to LH 

**Scope** of this ticket is to identify and build ways to monitor activities that need to be monitored for LH migration release for Claims Service endpoint.
.
https://dev-developer.va.gov/explore/api/benefits-claims/docs?version=current
---
## Tasks
- [ ] Identify how to monitor failures for these
- [ ] Make changes to log/monitoring

## Acceptance Criteria
- [ ] The dashboard is able to display traffic, logs and status code to benefits claims requests and responses in sidekiq jobs for EVSS and LH

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
