### ISSUE TITLE
Create Write Access Documentation 

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#65988]
## Description 
To document the write access process in all necessary places (both internally for support and externally for VFS teams). 
---

## Definition of Done
All tasks below are complete.
---

## Tasks 

- [x] Update the Advanced Support Best Practices Doc with the steps that our team follows to prep for sending to Clint. Additionally we should outlined the process Clint follows so we have transparency.(https://vfs.atlassian.net/wiki/spaces/PTST/pages/2761326593/Advanced+Ticket+Support+Best+Practices+Tier+1#PR-Review-Requests)
- [x] Update the VFS Platform Site page "[What We Can Help With](https://depo-platform-documentation.scrollhelp.site/support/what-we-can-help-with-platform-support)" in the DataDog section (clarify that we grant write access not read only access) 
- [x] Notify Alyssa when both have been updated
- [ ] Alyssa will communicate to #vfs-platform-support
- [ ] Alyssa will communicate to Team of Teams
- [ ] Alyssa will follow up in any related Slack threads

--- 

## Resources & Additional Info 
N/A

---

**Comment by lindsay-insco** [comment]
Hey~ I don't mind finishing this up - so for context we already made a quick change to the DataDog information in confluence because Rebecca ran into the news while I was working on the initial change, so I'll go ahead and pop the rest of the information in I asked Clint to set up a few minutes to chat anyways~

**Comment by lindsay-insco** [comment]
Updated "What we can help with" page in Confluence with Datadog role example and verbiage https://vfs.atlassian.net/wiki/spaces/SUP/pages/2692612097/What+We+Can+Help+With+-+Platform+Support

**Comment by alyssagallion** [comment]
Update recommendations:

- Add "Initial" to "DataDog Access" in "What We Don't Do Column" and link to documentation with a similar title to "for more information" and the link that already exists there
- Add write access to "Standard Access" under DataDog "What We Can Do" column

CC: @lindsay-insco

**Comment by lindsay-insco** [comment]
Updated language!
