### ISSUE TITLE
[BE] 10-10EZ - BUG: Determine root cause of Submission retry failure when a subsequent retry was successful

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#65993]
## Background
During the PACT Act enrollment period in September 2023, we were tasked to investigate all submissions that failed retries.  One of these investigations uncovered an issue with submission timing, as well as reporting it as failing retries when it had in fact been retried and successful.

This ticket is going to address the submission retry failure issue.

<details>
<Summary>EXPAND - Slack conversation with Joshua Faulkner</Summary>

**Heather Justice**
Hi Joshua.  We are investigating a submission that failed all retries on Saturday around 10:47pm ET.  The message we got is "Invalid format for Last Service Discharge Date."  We do not allow discharge dates more than 365 days in the future, and the fields are very specific (two dropdowns and a freeform numeric year).  We do not yet log the data so we cannot be sure of what the date might have been.
My questions are:
- Is there a way to tell if this submission made it to ES?
- What is the format for Last Service Discharge date that is required for ES?

**Joshua Faulkner**
checking, do you have the last name by chance or just the time?

**Heather Justice**
Just the time, we did not capture the user data
i have a [sentry log](http://sentry.vfs.va.gov/organizations/vsp/issues/213757/events/4db33e82608e48068de5fe4c34f7772b/?environment=production&project=3&query=is%3Aunresolved+job%3A%22HCA%3A%3AEncryptedSubmissionJob%22&statsPeriod=14d) (needs SOCKS running) showing the error but i dont know if that helps

**Joshua Faulkner**
the end date is in the future is the problem, when there is a future end date the discharge type needs to be absent, i have seen some of these before in the past where the end date is coming as the very next day, but still in the future. My guess is a timezone issue like we had with the application date a while back.

<ns0:militaryServiceEpisode>
                     <ns0:endDate>09/17/2023</ns0:endDate>
                     <ns0:serviceBranch>4</ns0:serviceBranch>
                     <ns0:startDate>09/18/2018</ns0:startDate>
                     <ns0:dischargeType>1</ns0:dischargeType>
                  </ns0:militaryServiceEpisode>

that was sent on the evening of 9/16 with end date of 9/17
**a retry was sent at 9/17/2023 10:12:12 PM CT and was processed successful**, so probably two different things we need to clear up, it shouldn't be showing as failed all retries, nor should it be failing in the first place.

**Heather Justice**
Joshua - If any submission with a future discharge date also has a discharge type (assuming that means character), then they would all fail ES, is that right?
FYI - We have had 733 submissions with future discharge dates in September so far, and all would have a character/type, as the field is currently required.

**Joshua Faulkner**
it gets stripped out before it gets sent; you can't have a character of discharge if you have not been discharged yet
looks like:
<ns0:militaryServiceEpisode>
                     <ns0:endDate>10/06/2023</ns0:endDate>
                     <ns0:serviceBranch>4</ns0:serviceBranch>
                     <ns0:startDate>10/07/2019</ns0:startDate>
                  </ns0:militaryServiceEpisode>

**Heather Justice**
ah i see, so this could only happen if the timing was so close, like the one that failed

**Joshua Faulkner**
right, i am pretty sure this is timezone issue; we had a problem with application date showing up as the next day but only when submissions were in the night/evening, that was fixed some time ago but i think these dates have same issue if they select today as their discharge date

</details>

## Tasks
- [x] Determine why a submission that was successfully retried would show as failing all retries
- [ ] Determine if there is a solution to ensure we are not logging submissions failing retries when they are not
- [ ] Review with Team/PM to ensure there are no conflicts in implementing this solution (if applicable)
- [x] New ticket(s) can be created for the solution implementation

## Acceptance Criteria
- We are able to determine what is causing the issues, and have documented viable solutions, if applicable

**Comment by lihanli** [comment]
this application was not retried, it was manually submitted again by the veteran. it shows up as "state: failed" in the database, if it was retried and successfully submitted the state would be "success"

**Comment by lihanli** [comment]
solution ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/66254

**Comment by hdjustice** [comment]
Got it, thank you for looking into this Lihan!
