### ISSUE TITLE
BE | Auth Exp | Update Team in vets-api codeowners file

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#66007]
## Background
The codeowners file in vets-api is referencing the `vfs-authenticated-experience` team.  This team contains more than just BE engineers so non-engineers keep getting email notifications.  I created a `vfs-authenticated-experience-backend` team for just the BE engineers and updating the codeowner file to use this team instead. 

## Tasks
- [x] Verify approach with platform support ([See ticket](https://dsva.slack.com/archives/CBU0KDSB1/p1695238304230529))
- [ ] Update vets-api codeowners file with new team

## Acceptance Criteria
- [ ] Ensure auth-exp engineers are still receiving vets-api notifications (Adam, Derrick, and myself).
- [ ] Ensure auth-exp non-engineers are not receiving vets-api notifications.
