### ISSUE TITLE
[Research] 10-10EZR Planning for MVP Usability Study

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#66001]
## Issue Description
- Create needed documents to prepare for research studies on the MVP release of the 10-10EZR health benefits update form. 
- Download templates needed from the [Platform site](https://depo-platform-documentation.scrollhelp.site/research-design/research-at-va)
- Work with team to determine research goals and questions.

---
## Tasks
- [x] Create folder with naming conventions in [research root folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/research)
- [x] Create [research plan](url)
- [x] Create [conversation guide](url)
- [x] Review with team/changes needed
- [x] Confirm dates
- [x] Kickoff ticket with Perigean

## Acceptance Criteria
- [x] Submit for research review and recruitment

**Comment by jessicastump** [comment]
This study has been submitted to the [research repo here](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/427) and the kickoff call with Perigean has happened. 
Next tasks are in Conducting Sessions ticket
