### ISSUE TITLE
Setup individual conversation guides for DI research w/ VFS teams

### ISSUE THREAD

**Issue by gopixelsgo** [department-of-veterans-affairs/va.gov-team#66011]
## Purpose
Novice, experienced, and uninitiated teams will have some variation in their User Journey Mural boards, so their conversation guides will vary too. This is about aligning the tasks to those differences for consistency and accuracy.

## Tasks
- [x] Prep novice team conversation guide to match tasks for their board
- [x] Prep experienced teams conversation guides (targeting 2 teams for this) to match tasks for their board
- [x] Prep uninitiated team conversation guide to match tasks for their board

## Acceptance Criteria
- [x] Conversation guide tasks align with each team's UJ Mural board

**Comment by gopixelsgo** [comment]
This ticket will roll over to the next sprint to complete its acceptance criteria.
