### ISSUE TITLE
Identify contracted team engagement process for strategy roadmap input

### ISSUE THREAD

**Issue by SophiaPhilipMO** [department-of-veterans-affairs/va.gov-team#66026]
Context
As a participating contracted team on the CEDAR Identity contract that is in charge of creating the strategy roadmap, I need to know who is in charge of ensuring other contracted teams input their information into the strategy roadmap and what is the process.

AC:
- [x] Meet with Tom Black and discuss process during PO Sync
- [x] Identify who should send out strategy roadmap and who is in charge of collecting input 

Definition of Done:
- [x] Defined process for collecting feedback
- [x] Tom Black has identified who the ask will come from when getting other contracted teams to provide input

**Comment by lmorris3** [comment]
Tom confirmed in meeting 9/28 that he would like to be the one to circulate the roadmap. Instead of asking other teams to collaborate on it, he will circulate it as the vision for Identity and will ask for feedback, rather than direct input. We will not ask teams to add their work to separate swim lanes, but rather, add the major milestones (like Ebenefits sunset, MHV, etc.) to the roadmap to show the changes in relation to the Identity work going on.

**Comment by lmorris3** [comment]
Thanks @djmunoz1 - I agree with that clarification.
