### ISSUE TITLE
Review The VA Forms Library in relation to the Find A Rep Prototype

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#66038]
## Issue Description
Get acquainted with the [VA Forms Library](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-overview) used on vets-website.

---
## Tasks
- [x] Review all Forms Library documentation
- [x] Review the forms code in the FAR prototype
- [x] Review how in-progress forms work
- [x] Review how form pre-fill works
- [x] Review how the "review" page works
- [x] Review how "Continue your application" works
- [x] Review how sign-in works with FAR widget and search

## Acceptance Criteria
- [x] A thorough review of the VA Forms Library has been completed
- [x] Certain findings have been shared with the team
