### ISSUE TITLE
[CST] Log claim types to DD

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#66043]
## Background
It would be beneficial for us to be able to keep track of the claim types as they come through the CST. The main two benefits that we have identified so far are as follows:
* We would be able to get a better idea of the claim types that appear in CST
* We could create metrics on the types of claims that come through the CST (things like what 80% of claims are of type 'Compensation') for instance

## Open questions
* Do we want to find some way to uniquely identify claims (some sort of hash or something)
    * This might prevent the data from getting skewed if Veterans with certain types of claims check the CST more often than others

## Tasks
- [x] When we get the list of claims from LH, log the claim type to DD
- [x] When we get the list of claims from LH, log the number of contentions to DD
- [x] When we get the list of claims from LH, log the EP codes

## Acceptance Criteria
- [x] Claim types are logged to DD
- [x] Numbers of contentions per claim are logged in DD
- [x] EP codes are logged to DD
- [ ] We have an "easy" way to determine which EP codes are associated with each claim type.

**Comment by HeatherWidmont** [comment]
PR is coming today, Sam is currently helping Jerek on another ticket

**Comment by HeatherWidmont** [comment]
@samcoforma will create a dashboard today & sync with @jerekshoe about the open question stated above

**Comment by samcoforma** [comment]
@HeatherWidmont this is done, so I'll close it. @jerekshoe made the dashboard already: https://vagov.ddog-gov.com/dashboard/p2a-9ii-9hz?refresh_mode=sliding&view=spans&from_ts=1705595098805&to_ts=1705598698805&live=true
