### ISSUE TITLE
DR | Increment StatsD error for evidence uploads, only when retries have expired

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#66046]
## Issue Description

We have a DataDog alert configured to tell us when evidence uploads fail. This alert references a StatsD counter that is incremented every time a `DecisionReview::SubmitUpload` job fails due to an error. However, sometimes these errors are transient and cured by a retry. In such cases, we will log a false positive error that clutters up our error notifications for NOD and SC. We have gotten 3 false positive notifications for 7 false positive errors in the past two days.
 
To resolve this issue, we will need to increment the StatsD counter only when the job reaches the max retry amount and fails permanently. That is the aim of this ticket.

---
## Tasks
- [x] Increment StatsD counter only when retries have expired.

## Acceptance Criteria
- [x] StatsD counter only gets incremented when retries have expired.

## Definition of Ready
- [x] N/A

## Definition of Done
- [x] StatsD counter only gets incremented when retries have expired.

**Comment by anniebtran** [comment]
Adding some investigation notes — 

Looks like we can achieve this by using the [`sidekiq_retries_exhausted` hook](https://dev.to/morinoko/sidekiq-s-sidekiqretriesexhausted-hook-3d0e) and defining a block where the `StatsD` incrementing occurs. There are lots of examples of this hook in the `vets-api` repo (e.g. [this instance that logs and increments a metric](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/workers/central_mail/submit_form4142_job.rb#L37-L43)).

Doesn't seem like it would be too difficult to implement but maybe a little hard to test? (Seeing a few comments to the effect of: `# This callback cannot be tested due to the limitations of Sidekiq::Testing.fake!`) So depending on how much we care about testing this before it deploys, I'd estimate it at about a 1 or 2.
