### ISSUE TITLE
 Implement Find a Rep Search Feature

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#66042]
## Issue Description
To allow users to search for a representative in their area, we need to implement the Find a Rep search feature.

---
## Tasks
- [ ] Design the search interface based on prior research.
- [ ] Use existing mock data to populate search results.
- [ ] Ensure that the map does not display results (as per the requirements).
- [ ] Allow users to select a representative from the search results.

## Acceptance Criteria
- [ ] A fully implemented, non-functional "Find a Rep" search feature ready for user testing.

**Comment by holdenhinkle** [comment]
This ticket isn't needed. It's basically the same as the MVP: Search epic we're putting tickets under. Closing this.
