### ISSUE TITLE
Implement Find a Rep Search Feature

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#66044]
## Issue Description
To allow users to search for a representative in their area, we need to implement the Find a Rep search feature.

The map does not have to display search results.

---
## Tasks
- [ ] Design the search interface based on prior research.
- [ ] Use existing mock data to populate search results.
- [ ] Allow users to select a representative from the search results.

## Acceptance Criteria
- [ ] A fully implemented, non-functional "Find a Rep" search feature ready for user testing.

**Comment by cosu419** [comment]
Moving this ticket to "Done" for being somewhat vague/redundant with the Search Page epic. The Search page currently returns mock data and allows for selecting a representative.
