### ISSUE TITLE
Resolve nil FSR records sent from newline error

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#66086]
## Issue Description
A code change was merged on 9/14 that updated the FSR logic for removing new line characters as well as potential delimiters. This functioned on values of type string but boolean values (i.e. true/false) were transformed to nil. This only affected VHA submissions.

---
## Tasks
1. We (VODA) discovered issue when prying into an example record
2. VBS sent email informing us about the presence of nil records
3. We rolled back the causing commit that went out at the standard deploy 3pm EST (9/15)
4. Tracked affected form IDs (73 in total)
5. Once deploy went out VBS deleted the affected records and sent over the IDs
6. We cross matched to make sure the IDs lined up
7. Updated nil boolean fields with accurate true/false on the records
8. Re-processed the records to be submitted to the VBS API again

## Acceptance Criteria
- [x] Records have been updated and resent to VBS API
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
@ScottyRJames - I think this one is done, per your update earlier today. Closing out (only since it's the last day of the sprint!), but please let me know if needs to be moved back to "Done." Thanks!
