### ISSUE TITLE
Feedback Mechanism - User testing feedback 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#66095]
## Issue Description
Create timeline for recruiting participants to collect feedback plan for timeline for deployment (when to start recruiting for participants – need 1-2 weeks – get feedback and then include the feedback in next steps – review and make changes before participants can provide feedback 
Folder for visibility 

---
## Tasks
- [x] Create a timeline for participant recruitment 
- [x] Recruit participants
- [x] collect User testing feedback

## Acceptance Criteria
- [x] QA feedback collection is complete 
- [ ] Implement User testing feedback
- [ ] Present to Governance team for final design
- [ ]  Schedule Contact Center Review 
- [ ] 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by UXCamG** [comment]
We have conducted user testing with  P1,P2, P3, P7. We have had 3 no shows. Perigean will recruit more participants or reschedule the no shows.

**Comment by ATMiddleton** [comment]
Still conducting User testing

**Comment by UXCamG** [comment]
User testing wrapped up 11/16/. We had 9 veterans to participate in our study. Currently, I am working on synthesizing the findings and I will plan a readout with the Veterans support team .

**Comment by UXCamG** [comment]
Our next steps are to recruit participants with assistive technology to add on to our findings. I will team up with CAIA to complete 3 remaining sessions.

**Comment by UXCamG** [comment]
[User testing ](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/384) is finalized . We are in the analytics phase of the collaboration cycle. I have started the [ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70604). Our next steps are to plan a second phase of research, implement V2 of Medallia, and prepare a staged environment.

**Comment by ATMiddleton** [comment]
QA feedback complete
