### ISSUE TITLE
Sketches for Vision within Strategy Roadmap

### ISSUE THREAD

**Issue by SophiaPhilipMO** [department-of-veterans-affairs/va.gov-team#66092]
Context
As a Veteran, I want to know that my experience as a Veteran is central to the strategy roadmap so that I know my needs are what inform and shape the strategy.

Acceptability Criteria
Each member of design team offers an interpretation of the vision to ensure diverse perspectives to inform and merge into one visual
- [x] Each member creates a sketch or multiple sketch pulling from key features mentioned in 10/17 brainstorm session and features in [Mural](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1695041576761/a482dba6ff5d97bc0af7bbcd8893ba41dcea3f03?sender=u8b2bd1f5eec8aeeb5ca99521)
- [x] Each member uploads sketch to Mural prior to 10/20 meeting

Definition of Done
- [x] Each teammate presents sketch on 10/20 meeting and team identifies key features to merge
