### ISSUE TITLE
Collaboration Cycle for Core Identity, Sign in Service, Sign out all devices

### ISSUE THREAD

**Issue by charlye-bluetiger** [department-of-veterans-affairs/va.gov-team#66109]
### VFS team name

Identity

### Product name

Sign in Service

### Feature name

Sign Out of All Devices

### GitHub label for product

N/A

### Public DSVA Slack channel for VFS team

#identity-research

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

March 2023

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Tools, applications and dynamic pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Unsure

### Do you need to capture any additional analytics or metrics?

Unsure

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Product%20Briefs/Sign%20in%20Service.md

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Notify the Collaboration Cycle team of this ticket in your team's public Slack channel.

- [X] I acknowledge that I must notify the Governance team by completing the collab cycle kicckoff workflow in my team's Slack channel after submitting this issue. This can be completed by typing "/collab cycle" and selecting the appropriate workflow.
- Kickoff Slack Thread with VFS team: [Kickoff thread](https://dsva.slack.com/archives/C04S98PE8FK/p1695999124560409)
</details>

### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- [ ] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [ ] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [ ] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.

**Design Intent artifacts**

See Platform guidance on [Design Intent artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Design Intent meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

- [x] User flow (required) - [Mural for User Flow](https://app.mural.co/t/oddball4265/m/oddball4265/1694188194725/8b8d5007a442ec71eabcd36941e819eb97dc8968?wid=0-1696604536497)
- [x] Whiteboard sketch or other lo-fi prototypes or wireframes [Placement](https://app.mural.co/t/oddball4265/m/oddball4265/1694188194725/8b8d5007a442ec71eabcd36941e819eb97dc8968?wid=0-1696604536497)
- [x] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Research/2023-09%20Manage_Devices/Research_Plan.md)
- [x] Any other artifacts you have so far - [Product Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Product%20Briefs/Sign%20in%20Service.md) | [Product Write-Up about Manage Devices](https://docs.google.com/document/d/1v-bPF-_aOD1bOIMW9B1d76G4XzO0U9aTcuxBFmcmCoY/edit)
  
##### Platform actions
- [ ] Slack thread with VFS team: https://dsva.slack.com/archives/C04S98PE8FK/p1696346875154279
- [ ] Meeting date/time: October 10, 2023 at 3:30 ET
  
##### Platform actions

* Accessibility
  * [ ] Feedback ticket attached
  * [x] No feedback
* Design
  * [x] Feedback ticket attached
  * [ ] No feedback
* IA
  * [ ] Feedback ticket attached
  * [x] No feedback
* [x] Update this ticket with the Zoom recording
  - [Recording link](https://oddball-io.zoom.us/rec/share/0K0ldiK2OwURa-4H3HF4mjy-TLfPEbhuDjVKc-BSuxcRvKnkPv-15tDH0xu8g_8h.1BXBktadeSNZK-e5)
  - Passcode: Rn%5KWC$
  
##### VFS actions

- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Sitewide CAIA Intake Request
<details>
  <summary>Toggle Sitewide CAIA Intake Request</summary>

##### VFS actions
- [ ] Complete the [Sitewide CAIA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-CAIA-intake-request.2124906551.html)
- [ ] Link to the Sitewide CAIA Intake Request ticket below

</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [ ] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [ ] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

Provide links or documents for the following:

- [ ] Finalized design prototype or mockup
   - [Desktop width](https://www.figma.com/proto/gHOZKVka8PnVblchp0dZbJ/Logout-Device?type=design&node-id=1301-140&t=qruKbF1Z413n4Hlt-0&scaling=scale-down&page-id=0%3A1&starting-point-node-id=319%3A274)
   - [mobile width](https://www.figma.com/proto/gHOZKVka8PnVblchp0dZbJ/Logout-Device?type=design&node-id=1311-79&t=qruKbF1Z413n4Hlt-0&scaling=scale-down&page-id=0%3A1&starting-point-node-id=319%3A274)
- [ ] Specify which pages are included in the review 
   - CF - 11 - Profile - Account security
   - Mobile - LAD - 07 - Account Security
- [ ] [Research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Research/2023-09%20Manage_Devices)
- [ ] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/1abe303565b28c7df8b78f3f69a0560ccfc44321/products/identity/Research/2023-09%20Manage_Devices/2023-09%20Manage%20Devices%20Research%20Plan.md)
- [ ] [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/a340cbfe76b3356c4b70efded24be0f1daa39c40/products/identity/Research/2023-09%20Manage_Devices/2023-09%20Manage%20Devices%20Conversation%20Guide.md) (not finalized)
 
**Content artifacts**
  
- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including a content source of truth, any relevant static content page and entry point updates, and the intake form.

**IA artifacts**

- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) feedback you received, including an IA review document or intake form.

##### Platform actions
- [x] [Slack thread ](https://dsva.slack.com/archives/C04S98PE8FK/p1698420085093729)
- [x] Meeting date/time: October 31 at 3:30pm ET

##### Platform actions

* Accessibility
  * [x] Feedback ticket attached
  * [ ] No feedback
* Content
  * [ ] Feedback ticket attached
  * [ ] No feedback
* Design
  * [x] Feedback ticket attached
  * [ ] No feedback
* IA
  * [x] Feedback ticket attached
  * [ ] No feedback
* [x] Update this ticket with the Zoom recording
  - [Recording link](https://oddball-io.zoom.us/rec/share/yGuw3hBgZIluPHWpFXq2mF1w8sXJ6rVZw6zpstksgmKOMdSuO4DFvjg-TaxV33yP.zKyZGVJAZ4Bxj3SU)
  - Passcode: e0d%.1Aw
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [ ] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [ ] Link to the Analytics Implementation and QA Request ticket below

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [ ] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [ ] Link to the Contact Center review request ticket below

</details>

### Staging Review

<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [ ] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] If this product contains any [experimental design](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [ ] I confirm the environment is available and test users have been provided.
- [ ] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
 
**Staging Review artifacts**

Links to [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts) must be added to this ticket 4 business days ahead of the scheduled meeting. Please do not make changes to the product or artifacts during the 4-day review period. 

**Required artifacts**
- [ ] **Direct link or instructions on how to access the product**
  - The product should be available on an [approved staging environment](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-environment-guidance-for-vfs-teams). 
  - List screens, sections of screens, and/or user flows impacted by this work.
- [ ] **Generated PDF form** (when applicable)
  - A populated version of the form that will be submitted through the online tool 
- [ ] **Drupal or Staging URL for updated primary entry point:** the main way Veterans will access the tool through site navigation (not search)
  - If the primary entry point is not a page on VA.gov, include information about how to view it. Reach out to `@platform-governance-team-members` on Slack with any questions.
- [ ] **Test users and scenarios** (when applicable)
  - Store [test user information](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md), passwords, and tasks in a .md file in the va.gov-team-sensitive repository. 
  - Make sure all user scenarios can be tested, i.e.: in-progress form, submitted form, new form.
- [ ] **Link to Sitewide CAIA intake ticket**, if applicable.
- [ ] **Completed accessibility testing artifact:** see [instructions and link to accessibility testing template](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).
- [ ] **QA Artifacts:** artifacts that correspond to each of the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
  - [ ] Regression test plan
  - [ ] Test plan
  - [ ] Coverage for References
  - [ ] Summary (Defects) reports
  - [ ] E2E tests
  - [ ] Code coverage
  - [ ] Endpoint monitoring playbook
  - [ ] Logging silent failures
- [ ] Completed **[Engineering and Security Checklist](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/engineering/collaboration-cycle/architecture-intent/checklist/eng-sec-checklist.md)**

**Not required, but nice to have artifacts**
- [ ] **Content source of truth:** link to CAIA Content feedback, such as a content source of truth.
- [ ] **Information Architecture spec:** link to CAIA IA feedback, such as an IA spec.
  
##### Platform actions
- [ ] Slack thread with VFS team
- [ ] Meeting date/time:

##### Platform actions

- [ ] Update this ticket with the Zoom recording
  - Recording link 
  - Password:
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
- [ ] [Complete Collaboration Cycle feedback survey](https://ows.io/qs/gb1dfnkl)

</details>

**Comment by charlye-bluetiger** [comment]
[Design Intent Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67253)

**Comment by shiragoodman** [comment]
@Samara-Strauss - following up on this one too. It's been 2 years since the Midpoint Review. Is this work still in progress? Should we expect a Staging Review still or can this ticket be closed?

**Comment by Samara-Strauss** [comment]
This work is not happening. Good to close!
