### ISSUE TITLE
Chapter 2: Implement the 'edit' view (as opposed to the 'enter') for the Veteran Contact Information Page [Authenticated Users]

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#66103]
## Issue Description
The MVP requires a ' Veteran Contact Information' page.  There will be two states in this step for **Authenticated** users:
1. User can see the information on file, with an option to click `Edit`
2. User can edit the information on file, with an option to `Enter` which will save any changes

This issue is to tackle the 1st state -- the 2nd state is handled in #66157 . 

Designs for this 1st, `Edit` state are [here](https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/v/xElE8A/p/3C666192-27DA-40CE-B314-BA779A8C8BD4/canvas?posX=-13914.359044300276&posY=-1384.0933588041617&zoom=0.4692396819591522).

---
## Tasks
- [ ] Create the 'edit' Personal Information page according to the new wireframes.
- [ ] Incorporate mock data for display.
- [ ] Ensure fidelity of the user interface.

## Acceptance Criteria
- [ ] A non-functional 'edit' Personal Information page that mirrors the new wireframes
