### ISSUE TITLE
Chapter 1: Implement the Veteran Name and Date of Birth Page [Unauthenticated Users]

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#66102]
## Issue Description
If a user is not signed in (i.e. unauthenticated), we will not have any personal information on file to display, and will need the user to enter their name and date of birth as the first page of Chapter 1 for **Unauthenticated** users.

---
## Tasks
- [x] Create the 'enter' Veteran Name and Date of Birth page for unauthenticated users based on the new wireframes.
- [x] Ensure accurate representation of the user interface.

## Acceptance Criteria
- [x] A non-functional 'enter' Veteran Name and Date of Birth page for unauthenticated users exists with the new wireframes

**Comment by holdenhinkle** [comment]
Pics:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzB2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--669543e7cec7fd8efce83d8b2d70a4a91a422059/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzR2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c4d1090dc27a1723bf557cbf19470bcf44e2c62/image.png)

Here’s the link to the sketch file - https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/prototype/09027814-467C-4625-9E14-904D2A9A0FBB/a/09027814-467C-4625-9E14-904D2A9A0FBB

Here are some comments about the Sketch file:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEF2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e8a01f86c282dfde6de941ee8bcf658b734c127e/image.png)

Also, the breadcrumbs are different but can easily be changed.

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-website/pull/26161

**Comment by holdenhinkle** [comment]
QA check convo - https://dsva.slack.com/archives/C05L6HSJLHM/p1697139479614359

Merged.
