### ISSUE TITLE
Chapter 3: Implement Claimant Contact Information Page

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#66105]
## Issue Description
When the Claimant is not the Vetaran, we will first ask for Claimant Personal Information ([#66104](https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/66104)) and then proceed to this page where we ask for the Claimant Contact Information.  Here are the designs for [the Claimant Contact Information page](https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/v/RqgbGe/p/3C666192-27DA-40CE-B314-BA779A8C8BD4/canvas?posX=-21741.93484050283&posY=-833.9492562826835&zoom=0.44297313690185547).

After the user inputs the Claimant Contact Information, the "Continue" button should route to the next Chapter 3 page: Claimant Mailing Address which will be implemented with [#67742](https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/67742).

---
## Tasks
- [ ] Create the Claimant Contact Information page with the design linked above
- [ ] Ensure the user interface is in alignment with design expectations.

## Acceptance Criteria
- [ ] A non-functional Claimant Contact Information page has been implemented, matching the design linked above.
