### ISSUE TITLE
Claimant Personal Information

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#66104]
## Issue Description

The Claimant Personal Information page will be available to:
1. Non-Veteran users ONLY
2. Authenticated users and unauthenticated users
3. 21-22 and 21-22a forms.

Content is dynamic based on:
   1. If the user selects a **VSO** for representation, they will see "VA Form 21-22" at the top of the page.  If the user selects an **attorney/claims agent** for representation, they will see "VA Form 21-22a" at the top of the page.
   2. **Authenticated** users.  
      ~1. If the auth user has **all of the required information** (first name, last name, date of birth) in their profile show the **authenticated design**~ (Saving this for https://github.com/department-of-veterans-affairs/va.gov-team/issues/90986)
      2. If the auth user has **some of the required information**, show the **unauthenticated design** and **prefill** any text inputs when possible
      3. If the auth user has **none of the required information**, show the **unauthenticated design** with empty text inputs
   3. If the user is **unauthenticated**, show the **unauthenticated design** with empty text inputs

The information collected on this page will be routed to the forms as follows:
- [21-22](https://www.vba.va.gov/pubs/forms/VBA-21-22-ARE.pdf):
   - Field 10: Claimant's Name (First, Middle Initial, Last)
   - Field 11a: Claimant's Date of Birth (MM-DD-YYYY)
 - [21-22a](https://www.vba.va.gov/pubs/forms/vba-21-22a-are.pdf):
    - Field 10: Claimant's Name (First, Middle Initial, Last)
    - Field 11: Claimant's Date of Birth (MM-DD-YYYY)

**URL**: `/claimant-personal-information`

**Previous paths**: 
1. `/claimant-relationship` 

**Next paths**: 
1. ~`/claimant-contact` (non-Veteran auth with all required info on file)~  (Saving this for https://github.com/department-of-veterans-affairs/va.gov-team/issues/90986)
2. `/claimant-contact-phone-email` (all other non-Veteran users)

[MVP Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)

## "Auth" Designs (Prefill)
[Prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1475-134715&t=76HE35X9xQ4MyVIC-0&scaling=min-zoom&page-id=1475%3A128342&starting-point-node-id=1500%3A153719&show-proto-sidebar=1), [Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1475-214235&t=76HE35X9xQ4MyVIC-4), [Annotations](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=2194-153447&t=76HE35X9xQ4MyVIC-4)

**Disclaimer**: We only designed the authenticated experience for a Veteran user.  In a case where we have a non-Veteran claimant that sees this authenticated experience, we'd only need to display the first name, last name and date of birth.  SSN, Branch of Service and VA File Number are not required in the Claimant section of the 21-22 and 21-22a.

<details><summary>Screenshots</summary>

<img width="221" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmYrQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b26cdb08031919b25ec08eb96b67d00567509a7a/image.png" alt="image.png" />

<img width="998" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmorQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--12c6e5a5963b28cbe0da22b6eb5517d131ebf7c1/image.png" alt="image.png" />

</details> 

## "Unauth" Designs (Input fields)
[Prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=455-145773&t=9jmpeh45oeJzgf9k-0&scaling=min-zoom&page-id=455%3A76935&starting-point-node-id=455%3A148692&show-proto-sidebar=1), [Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=455-145773&t=iX3l7pOA3Uyiyxa2-0)

<details><summary>Screenshots</summary>

<img width="226" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMm4rQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d64c63db2c40657d1c8e395019e332bddd52a478/image.png" alt="image.png" />

<img width="842" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnIrQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--300511ab980b558d6a085918f530b10340dadf52/image.png" alt="image.png" />

</details> 

---
## Tasks
- [ ] Create the Claimant Personal Information page based on the designs above
- [ ] Set up the proper logic for displaying the page, as well as the content within
- [ ] Set up routing to the proper form fields

## Acceptance Criteria
- [ ] A Claimant Personal Information page has been implemented, with the specs outlined above.

**Comment by cosu419** [comment]
Can't really test the auth state without prefill configured on vets-api - @mtri can you check the unauth state?

**Comment by mtri** [comment]
Unauth state looks good.

**Comment by oddball-lindsay** [comment]
Awaiting the ability to pre-fill when possible

**Comment by cosu419** [comment]
8/8 update: part of an active PR with CI checks that need to be addressed. Also pending the [prefill functionality vets-api ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83555).

**Comment by cosu419** [comment]
8/12 update: CI checks passing, PR pending review

**Comment by cosu419** [comment]
Looking into the prefill response - expecting the auth state to be triggered for users with profile information available.

**Comment by cosu419** [comment]
Rendering the auth state is wrapped up in the same issue as Claimant Contact Information. Need to figure out why `formData.veteran` is empty for test users.

**Comment by oddball-lindsay** [comment]
I ran out of time today -- to do for me: create a similar ticket that focuses on the prefill pattern and carry over Colin's notes above.  Then link that ticket here for continuity and close this ticket out.

**Comment by oddball-lindsay** [comment]
Here's the ticket for the prefill pattern, which will be in Product Backlog for a future time https://github.com/department-of-veterans-affairs/va.gov-team/issues/90986.
