### ISSUE TITLE
Chapter 4: Implement Authorization for Record Access Page

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#66106]
## Issue Description
Integrate the Authorization for Record Access page.  Here is the design for [the Chapter 4 page](https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/v/RqZqdW/p/3C666192-27DA-40CE-B314-BA779A8C8BD4/canvas?posX=-24612.74275326265&posY=-1418.68279668262&zoom=0.4456486701965332).

There is a "Terms and Conditions" link which should trigger [this modal](https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/v/RqZqdW/p/3C666192-27DA-40CE-B314-BA779A8C8BD4/canvas?posX=-26383.195696950435&posY=-1515.1713601535641&zoom=0.4456486701965332).

---
## Tasks
- [ ] Create the Authorization for Record Access page based on the design linked above.
- [ ] Link the "Terms and Conditions" to reveal a modal with the full T&C content
- [ ] Confirm the user interface mirrors design expectations.

## Acceptance Criteria
- [ ] A non-functional Authorization for Record Access page in line with the design linked above
