### ISSUE TITLE
Chapter 5: Implement Authorization for Address Change Page

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#66107]
## Issue Description
The tool needs an Authorization for Address Change page.  Here is the design for [the Chapter 5 page](https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/v/RqZqdW/p/3C666192-27DA-40CE-B314-BA779A8C8BD4/canvas?posX=-27092.27444245784&posY=-1131.4610263505078&zoom=0.4456486701965332).

There is a "Terms and Conditions" link which should trigger [this modal](https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/v/RqZqdW/p/3C666192-27DA-40CE-B314-BA779A8C8BD4/canvas?posX=-28665.2624190423&posY=-1275.071911516564&zoom=0.4456486701965332).

---
## Tasks
- [ ] Create the Authorization for Address Change page as per the design linked above.
- [ ] Link the "Terms and Conditions" to reveal a modal with the full T&C content
- [ ] Ensure the user interface matches design goals.

## Acceptance Criteria
- [ ] A non-functional Authorization for Address Change page that matches the design linked above

**Comment by oddball-lindsay** [comment]
Will tackle in #83966
