### ISSUE TITLE
Domo Dashboard Data Issue Resolution 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#66100]
## Issue Description
_Reconcile data from both Salesforce and Domo 

---
## Tasks
- [x] _Validate data from Domo
- [x] Validate data from Salesforce 
- [x] Compare data sets for validation 
- [x] Design and generate charts 
- [ ] 
## Acceptance Criteria
- [ ] _Reconcile the difference between data sets
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
@newworld2616 - Sarifa should pick up PIV card today 9/21/23

**Comment by ATMiddleton** [comment]
Acceptance criteria has been met.
