### ISSUE TITLE
Chapter 6: Implement Final Review Page

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#66108]
## Issue Description
The updated designs requires a Final Review page.  Here are the designs for the different states in the Chapter 6 page:
1. [Collapsed state](https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/v/RqZqdW/p/3C666192-27DA-40CE-B314-BA779A8C8BD4/canvas?posX=-30505.276885232393&posY=-1611.6599236245083&zoom=0.4456486701965332)
2. [Expanded state](https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/v/RqZqdW/p/3C666192-27DA-40CE-B314-BA779A8C8BD4/canvas?posX=-32125.387183511968&posY=-2414.0897984470244&zoom=0.4456486701965332)
3. [Expanded state with editing](https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/v/RqZqdW/p/3C666192-27DA-40CE-B314-BA779A8C8BD4/canvas?posX=-32991.54033466974&posY=-1601.4894215984925&zoom=0.4456486701965332) 

At the bottom there are two checkboxes -- the first one has a "Terms and Conditions" link which should trigger [this modal](https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/v/RqZqdW/p/3C666192-27DA-40CE-B314-BA779A8C8BD4/canvas?posX=-34800.139919729765&posY=-1291.8284504591836&zoom=0.4456486701965332).

---
## Tasks
- [ ] Create the Final Review page, with collapsed sections, according to the design linked above (# 1).
- [ ] Create the Final Review page, with expanded sections, according to the design linked above (# 2). 
- [ ] Create the Final Review page, with expanded sections and the ability to edit, according to the design linked above (# 3).
- [ ] Link the "Terms and Conditions" to reveal a modal with the full T&C content
- [ ] Ensure the user interface is as per design specifications.

## Acceptance Criteria
- [ ] A non-functional Final Review page in line, according to all design states mentioned above
