### ISSUE TITLE
Implement PoA Confirmation Page for Prototype

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#66101]
## Issue Description
For the updated prototype, we need to implement the Power of Attorney (PoA) Confirmation page based on the new wireframes.

---
## Tasks
- [x] Create the PoA Confirmation page according to the new wireframes.
- [x] Populate the page with mock data as it won't be functional.
- [x] Ensure the user interface reflects the intended user experience.

## Acceptance Criteria
- [x] A non-functional PoA Confirmation page that matches the new wireframes and is ready for user testing.

**Comment by holdenhinkle** [comment]
Draft PR - https://github.com/department-of-veterans-affairs/vets-website/pull/25946

**Comment by holdenhinkle** [comment]
If the rep has a PO Box address the Google Map link doesn't appear.

If the rep does not have a PO Box address it does appear.


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0x4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--57eb787c21bd243713919be94c55d9309262b53e/Screen%20Recording%202023-09-29%20at%203.02.00%20PM.mov)

**Comment by holdenhinkle** [comment]
There's a circular dependency which needs to be cleaned up with the following in `src/applications/representatives/search-representative/config/chapters/appoint-representative/transitionPageDescription.jsx`:

```js
import {
  createPageList,
  createFormPageList,
} from 'platform/forms-system/src/js/helpers';
```

Which is needed to create:
```js
  const formPages = createFormPageList(formConfig);
  const pageList = createPageList(formConfig, formPages);
```

For the `SaveInProgressIntro` component:
```js
      <SaveInProgressIntro
        buttonOnly
        unauthStartText="Sign in and search for a representative"
        prefillEnabled={formConfig.prefillEnabled}
        messages={formConfig.savedFormMessages}
        formConfig={formConfig}
        pageList={pageList}
        downtime={formConfig.downtime}
      />
```

I'll fix this after we get the prototype updated and handed off to Janelle for user-testing.

**Comment by holdenhinkle** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcEh4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--40bbc8d970eba443ebe81f6545f735885fbce703/image.png)

**Comment by holdenhinkle** [comment]
I just realized I have to add some additional text to this page:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0x4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c3846ad77b575fda6142457b0a2c6a11c62724cd/image.png)
