### ISSUE TITLE
[FE] 10-10EZ - BUG: Investigate Invalid Veteran Date of Birth issue

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#66118]
## Background
During the PACT Act enrollment period in September 2023, we were tasked to investigate all submissions that failed retries.  Two of these investigations uncovered an error returned as "Invalid Veteran Date of Birth".
When confirmed with Joshua Faulkner, he stated that the data came through with a DOB year of 1865, instead of 1965. 
However, we have Frontend validation on the Veteran DOB field to ensure the date input is between 1900 and 2023.

- This happened again on 12/7/2023

This ticket is to determine how the application data can include the Veteran DOB year of 1865, even though we have validations in place to prevent it, and whether there is a viable solution.

<details>
<Summary>EXPAND - Slack conversation with Joshua Faulkner</Summary>

**Heather Justice**
We are investigating some more of the submission failures (ultimate retry fails) and there were 5 with that Future date issue, and 2 with an "Invalid Veteran Date of Birth".
Do you know what would cause us to get the date of birth issue?
We have numeric validations and it must be between 1900 and 2023.  We don't do any other validations on the form. Does ES validate the DOB against service dates or marriage dates maybe?
Also, would this be a case where it might go to HEC for manual processing?

**Joshua Faulkner**
<ns0:dob>08/13/1865</ns0:dob>
its a similar validation on ES side, dob has to be after 1900, not sure how those ones are getting in if the front end is enforcing the same thing
for that particular record the real dob is 8/13/1965, but came in as 8/13/1865
yes, all the failures get pulled into the HEC manual resub work

</details>

## Tasks
- [x] Determine how the application data might circumvent the Frontend validation, and pass a DOB outside of the current restriction (1900-2023)
     - [x] I believe this happens if the Veteran is authenticated, and we are puling the data from VA Profile, and VA Profile has an incorrect DOB
- [x] Determine if there is a solution to prevent applications from being submitted with a DOB outside of the current restrictions
- [x] Review with Team/PM to ensure there are no conflicts in implementing the solution (if applicable)
- [x] New ticket(s) can be created for the solution implementation

## Acceptance Criteria
- We are able to determine what is causing the issue, and have documented viable solutions, if applicable

**Comment by jadon1979** [comment]
After closer evaluation, modifying the necessary code on the backend would impact all forms using the InProgressController.  The fix needs to happen on the FE.  @longmd is going to handle that update.
