### ISSUE TITLE
EPIC | Profile | USWDS v3 Component Updates 

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#66116]
> [!Important]
> 3/15/2024 Opt out date 
> v1 components depreciated May 3 

## Background
We learned in [this slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1695320888067059) that there are updated USWDS v3 components available for use in Sketch and in our FE components. 

The way I see this, there are 3 layers, FE, Design/Sketch, Contact Center Guides

### FE
From a FE perspective, the recommendation is to slowly add these components in as we work on new items to uncover any potential bugs.

### Design/Sketch
~~From the design side of things, we'll have to update our sketch files (there are many!) and we'll need to consider how we go about this to ensure production and sketch stay in step.~~
Given the need to migrate from sketch to Figma, we're opting to update to the new components in Figma. We're doing the migration work here:
- #71836

### Contact Center Guides
Similarly to sketch as we update to the new components we should update any impacted contact center guides. 

## Tasks 

```[tasklist]
### Discovery
- [ ] #69483
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/69667
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/72277
```

```[tasklist]
### Page by Page
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/72076
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/73847
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/74799
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/74800
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/74801
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/74802
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/74803
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/74804
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/75732
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/75892
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/81160
```

```[tasklist]
### Analytics team
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/73743
``` 

## Acceptance Criteria 
- [x] figma is updated 
- [ ] FE is reflecting the latest and greatest set of components and we've removed the old ones from the code 
- [ ] Contact center guide is matching FE

**Comment by mtcA6** [comment]
@adamwhitlock1 @pamela-drouin @andaleliz consulted with AJ and for a similar initiative in the past they didn't create an outline/initiative brief. With that in mind, can you take a look at the background and let me know your thoughts (add in things you feel are missing). 

I don't want is to run through a BUNCH of design tickets and get things updated and then we're playing catch up with FE and Contact Center guides. I'm open on ideas on how to best collaborate on this but I want us to try to keep all three of those areas called out in the background as in-step as possible. 

Thoughts on the approach? I'm really trying to consider the issue you've called out before Liz of how we don't have the strongest way of managing the differences that exist in sketch/staging before we've rolled them out to production fully.

**Comment by mtcA6** [comment]
That's exactly what I'm saying, it's an idea i'm tossing out there, maybe it's page by page, maybe we do all the updates all at once! Per team of teams there are ~19-20 components out there. 

I want us to work in a way that juggles all three corners of the triangle (FE,Design,Contact) so we keep all three things in step. This was my initial thought on how to do that!

However we approach it I don't want a ton of design tickets completed while we're stalled waiting for Adam or me to update contact center guides, seeing a wall of design tickets completed and a growing number of FE tickets is kind of daunting since we only have one FE engineer. Even trying to organize those into future sprints is a little soul crushing from the PM side because we have to juggle our other initiatives as well.

**Comment by andaleliz** [comment]
What if we took this approach:

- FE makes the updates
- During staging validation, the person doing the validation takes a screenshot and updates the contact center guide
- Once the updates are on production, design can update the Sketch files

The Sketch files have the least amount of visibility and utility to teams/Veterans so I think they could be the last things to update.

**Comment by mtcA6** [comment]
New order of operations given the urgency to prepare for a Sketch sunset with the migration to Figma:

- design can update the Sketch files to ensure we're ready for the Figma migration 
- FE makes the updates
- During staging validation, the person doing the validation takes a screenshot and updates the contact center guide
