### ISSUE TITLE
[SW] Discovery - sending VHA determination calculations for Veterans who selected VBA debts

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#66112]
## Issue Description
The way the streamlined waiver experience is currently set up, Veterans who select a VBA overpayment debt or a VHA medical copayment that is over $5000 are not eligible for the streamlined process. Those Veterans instead are required to complete VA Form 5655 (FSR) in its entirety. 

Currently VODA is sending VHA an "FSR Reason" of 'waiver'  (not 'automatically approved' and when they are processing the data through the calculator they are seeing that the Veteran should have been approved. This discrepancy is causing them to think that there is an error. 

Can VODA use the data from the completed FSR to send VHA a determination for Veterans who have selected VBA debts? (not for copays over $5000 as those will still need to go through the manual review process. 

Other Notes from Team Convos about this:
https://dsva.slack.com/archives/CPE4AJ6Q0/p1694471819017509

---
## Tasks
- [x] Define questions, next steps involved and work required for implementation. 

## Acceptance Criteria
- [ ] Implementation tickets have been established to progress this work forward. 
---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
Per BE team, would be best to break this ticket into 2; a FE ticket and a BE ticket. Need to discuss as a team.

cc: @Tom-Davis

**Comment by HeatherRienks** [comment]
BE & FE to sync on this discovery ticket; will need follow up tickets to implement.

**Comment by Dr-Pongo** [comment]
Hey @denisecoveyduc / @HeatherRienks / @Tom-Davis !
FE just had a quick sync, and I think we can break this into three smaller steps:

1. (LoE ??) For the time being BE can send back at least a flag that says something like "this VHA submission was a part of a combo submission, so the streamlined calculations were not completed", so there's no confusion there. 
2. (LoE 3pt) FE to run calculations, but not alter form flow, for combo forms where VBA debts are also selected. 
  a. **NOTE:** We should also make it clear that these users did not see the streamlined specific questions for "cash in hand" & "cash in bank", and we will need to filter this data from the existing monetary assets checklist question.
3. (LoE ??) FE & BE collab to determine how to best communicate that info and relay it to VHA. Do we just say streamlined yes/no, or also include info as to why they did/didn't qualify like "assets exceeded threshold " or "discretionary income exceeded threshold", it could be helpful to include for troubleshooting purposes.

**Comment by denisecoveyduc** [comment]
Hi team! Thank @Dr-Pongo (please tag/share with other team members)

re #1 - When you say "flag" I am curious if that would cause code changes which would therefore impact VBA and Huron downstream? There was some discussion of just adding indication of a combo submission to the additional info  field.  Which route would be faster to implement? I ask because I think this would add a lot of clarity for the VHA reviewers who continue to question these combo submissions. 

^^ This is the highest priority as it would offer some immediate value to the reviewers as they examine the 'new submissions coming in with the calculation changes that are about to go live. [ FYSA @Tom-Davis @HeatherRienks 

Re#2  Agreed we don't want to alter the form flow and calculating cash in bank and cash in hand need to be extracted from the form date entered by the Veteran.  I don't anticipate we can do #2 without #3. 

Re#3  I would love to keep it "Streamlined No" as the Veteran did not go thru the Streamlined process.  Maybe we go back to the work Kevin did include a "null" value on that field [need to work with VBS to ensure they can accept these code changes]  

I'd bump the next question to #4 - "qualification comment" [not necessary but very helpful if the team can generate this]. Assuming it is possible to include a comment that outlines why a Veteran's submission did not meet the calculation requirements that would be helpful for troubleshooting purposes. Where would that information would _live_ in the file?

**Comment by Dr-Pongo** [comment]
Added FE work ticket:
**[FSR] Streamlined waiver calculations for combined submissions** [#67217](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/67217)

**Comment by kjsuarez** [comment]
Added backend work ticket
[#67239](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/67239)

**Comment by HeatherRienks** [comment]
@Tom-Davis -now that both FE and BE tickets have been added, and it appears discovery work has been completed. should this ticket be closed?

cc:  @denisecoveyduc

**Comment by Tom-Davis** [comment]
@HeatherRienks yes - this was discovery and ticket creation only. Closing as the new tickets cover the new work.
