### ISSUE TITLE
Identify/Send Submission Confirmations from VA Notify maintenance window on 10/1/23

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#66139]
## Issue Description
**VA Notify is planning for service downtime in Production on Sunday, 10/1/2023. The maintenance window is from 12am - 2am ET**

**What this means for our team:** We will need to resend confirmation emails to Veterans who submitted FSR's during this maintenance window **ASAP on Monday, 10/2/23.** 

**Maintenance Detail:**
_VA Notify usage has greatly increased over the past year (yay!). We've been dedicating team focus to enhance our platform ahead of more volume growth. As part of that initiative, we're increasing our database instance sizes and upgrading postgres to v15.3 to stay current. This does require some database downtime within a maximum 2 hour maintenance window. We aim to complete this quickly and will bring the service back up as soon as the upgrades are done. However, in the future we'll be working to shift to a global database cluster so we can reduce (hopefully eliminate) downtime in situations like these._

*Please refer to **va-notify-public** Slack channel for real time updates/questions

 
---
## Tasks
- [x] Identify failed VA Notify jobs from actual maintenance window (currently scheduled on 9/24/23 from 12am - 2am ET)
- [x] Resend submission confirmation emails to Veterans when VA Notify is back up and running
- [x] Share out details with team :)

## Acceptance Criteria
- [ ] Veterans will be informed via email a few hours after their FSR submission (if submitted during the maintenance window). FSR's that are started, but not submitted will not be affected.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
FYI - Maintenance window moved from 9/24/23 to 10/1/23. This ticket will rollover to the next sprint

**Comment by kjsuarez** [comment]
There were 3 relevant submissions, all completed successfully and all have been notified successfully.
