### ISSUE TITLE
Torri Dev Docs Editing #3

### ISSUE THREAD

**Issue by torrirosine** [department-of-veterans-affairs/va.gov-team#66149]
Based on the Dev Docs review and notes, revisit the existing table to implement any edits possible from the content team perspective. 

Link to spreadsheet: https://docs.google.com/spreadsheets/d/1PPhlba7PiCTWkJUWKHxH36rck0lfKtBSjSpqrCCBxv0/edit?usp=sharing

## Tasks

- [ ] Update pages lacking a footer
- [ ] Edit any additional content that can be edited from our end

**Comment by torrirosine** [comment]
- [ ] Update pages lacking a footer
- [ ] Add intro statement to list pages
- [ ] Edit any additional content that can be edited from our end

**Comment by vbellissimo** [comment]
Removing "add intro statement to list of pages" from the scope of this card.
