### ISSUE TITLE
[Dataload] Clone PHILADELPHIA, PA "POLICIES" web page into "New" plain language Web Page [CONTENT]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#6615]
## User Story or Problem Statement
As a Veteran Web user, I need a need a plain language description of the medical center "Policies" web page, so I will know and abide by the medical center regulations on my health care journey.  

## Goal
_Efficient and clear content describing local System Policies_

## Objectives or Key Results this is meant to further
- _Reduced word count and improved plain language._

## Resources - Tools - Documentation
[Policy_Page_Template](https://drive.google.com/drive/folders/1LyTF9Dug-ZT5enrM7RWCof0SJ0VQ_d_4)
[Required WebPage  Drupal Example](https://drive.google.com/drive/folders/1UcW6l99Ldj1tI81oRD2yTIqZcMyulJWU)
_ Legacy Pages:_
[Patient Information](https://www.Philadelphia.va.gov/patients/index.asp)
[Patient Rights "National"](https://www.va.gov/health/rights/patientrights.asp)
[Patient information](https://www.Philadelphia.va.gov/patients/advance.asp)
[Family Member Rights "National"](https://www.va.gov/health/rights/familyrights.asp)
[Visitor Information](https://www.Philadelphia.va.gov/visitors/index.asp)
[Visiting Hours/information](https://www.Philadelphia.va.gov/visitors/visiting.asp)
[Customer Services](https://www.Philadelphia.va.gov/patients/customerservice.asp)
_ New Page:_
[NEW Pittsburgh, Policy Page](https://www.va.gov/pittsburgh-health-care/policies/)

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] Completed Content is written in Word Document format (Template provided above) and is saved referencing Medical Facility Name & Web Page Name, Content writer's initials, separated by a period "e.g. Butler-Health-Care.Work_With_US.(sg)"
_Review and consider the following areas:__
- [ ] Privacy and patient rights
- [ ] Family rights
- [ ] Visitation
- [ ] Advance directives
- [ ] Report patient quality of care concerns
- [ ] Page must be saved in Content folder on Google Drive under Page reference name "Policies"

## Acceptance Criteria
* Completed Content is written in Word Document format and is saved referencing Facility Name & Page Name_
* Page must be saved in Content folder on Google Drive under Page reference name "Policies"
* Privacy and patient rights
* Family rights
* Visitation
* Advance directives
* Report patient quality of care concerns
