### ISSUE TITLE
Chapter 2: Implement the 'enter' view (as opposed to the 'edit') for the Veteran Contact Information Page [Authenticated Users]

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#66157]
## Issue Description
The MVP requires a ' Veteran Contact Information' page.  There will be two states in this step for **Authenticated** users:
1. User can see the information on file, with an option to click `Edit`
2. User can edit the information on file, with an option to `Enter` which will save any changes

This issue is to tackle the 2nd state -- the 1st state is handled in #66103. 

While we don't have designs yet for this 2nd, `Enter` state, you can view the designs for the 1st `Edit` state [here](https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/v/xElE8A/p/3C666192-27DA-40CE-B314-BA779A8C8BD4/canvas?posX=-13914.359044300276&posY=-1384.0933588041617&zoom=0.4692396819591522) for context.

---
## Tasks
- [x] Create the Veteran Personal Information page according to the new wireframes.
- [x] Ensure the user interface is as per design specifications.

## Acceptance Criteria
- [x] A Veteran Personal Information page in line with the new wireframes.

**Comment by oddball-lindsay** [comment]
@holdenhinkle share what you have with me here and I'm happy to check that against designs! 😊

**Comment by holdenhinkle** [comment]
Weird - is there a duplicate? This is the one I was working off of - https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/66102

**Comment by oddball-lindsay** [comment]
that's my bad!  i misunderstood which page you wanted to review and left this comment before you shared materials over in slack.

**Comment by holdenhinkle** [comment]
Done!

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-website/pull/26216
