### ISSUE TITLE
Evaluate edge-case user scenarios for users who have a health record, but no healthcare & users w/o a health record

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#66154]
## User Story
As a signed-in veteran who has never received VA health care or applied for care, I want to understand why i cannot access MHV on VA.gov health tools (e.g., va.gov/my-health, va.gov/my-health/secure-messages, va.gov/my-health/medical-records, etc…) and what I can do to get access, so I can get the care that I’m seeking.

## Background
We can handle the case where a non-signed in user is trying access authenticated content/apps (see `isLoggedIn` and `RequiredLoginView`). but with the health portal, two conditions need to be true: (1) they need to be signed in; and (2) they need to have a health record.

### Problem
We don’t have a standardized way across the apps to determine the second part of the criteria. and we don’t have a standardized way to handle the case where a user doesn’t meet the second part of the criteria.

### Description:
See related [Slack thread here](https://dsva.slack.com/archives/C0581MN69TJ/p1695391053834219).

Review all potential scenarios outlined in [this document](https://dvagov.sharepoint.com/:x:/s/HealthApartment/EWoc2IEogl1FnPQ4Xta7SCIBIudz7hIHPV2oEsSzNbFIkQ?e=wdA3Qi) (must be logged onto VA Network to access).

* Develop understanding of the needs of each of the apps in determining existence of a health record - is it just a binary “has health record?“, or is there more nuance like “has health record and has received care in last x months ?”
* Determine the value of shared FE components/functions that all apps depend on.
* Determine IA decisions for where a signed user who does not have a health record should go. If this place does not exist, we should create recommendation on where/what it should be. 

**Note**: We should approach this body of work with the mindset that we should be as permissive as possible when it comes to allowing users to access even a tiny tiny health record (as is their right).

**Note**: A good starting place for this is appointments team, who has been handling this situation for a long time.

## Impacted Artifacts
* Documentation of technical feasibility + constraints
* User flows - [Mural link TBD]

## Tasks

- [x] Connect with appointments team to get as much background as possible
- [x] Map out technical feasibility + constraints (are they different for each tool?)
  - [x] What criteria determines who has a health record? 
  - [x] What should we do when a logged-in user doesn't have a health record at all?  
- [x] Create user flows for all scenarios where a signed-in user does or does not have a health record

## Acceptance Criteria
- [x] We have recommendations for how to handle all user scenarios outlined above
- [ ] These recommendations are backed by technical documentation & user flows to illustrate the plan
- [ ] Create follow-on ticket to design communications for various users scenarios based on findings in this ticket

**Comment by sterkenburgsara** [comment]
cc @mnorthuis @batemapf

**Comment by LynneJohnson224** [comment]
@keithcheung828 can you please add a story point value to this ticket?

**Comment by keithcheung828** [comment]
Overview of user scenarios is found [here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695833467472/08b3d18f7829fb5d9f18bb80716f9ef2336fd6ca)

**Comment by LynneJohnson224** [comment]
@keithcheung828 @carlosfelix2 when you get a chance, can you please add a story point to this ticket? Thanks!

**Comment by MikeC-A6** [comment]
**Unauthenticated:** Should a user see the MyHealth header link.  If so, is there an unauth landing page? _break out into separate story_

**Authenticated, healthcare registration history, without access to all tools**: _break out into separate story_

**Authenticated, no healthcare registration history:** Create recommendation in this sprint, and create follow-on story to design this experience

**Comment by MikeC-A6** [comment]
@fmccaf1 flagging the task to write up _why should there be an experience designed for an authenticated user who does not have a healthcare registration history?_

**Comment by fmccaf1** [comment]
User type: Authenticated user with no health care registration history
Solution: Due to the possibility that this user type may be incorrectly categorized (in that they do in fact have a health care registration history MHV is unaware of), this user type should have an opportunity to uncover and remedy the error made by our system(s). One way to offer this opportunity is by allowing this type of user to see active links to MHV on VA.gov (such as the MHV link in the VA.gov header) AND to see a version of the MHV landing page that includes an explanation for why their access to MHV tools is limited AND to see information for actions they can take if they believe they do in fact have a health care registration history.

Unanswered question(s):
Can we estimate (or know) how many users are likely to encounter a situation of having a health care registration history but for whatever reason, we have characterized them as not having a health care registration history?

**Comment by LynneJohnson224** [comment]
Will create follow on stories with clear path forward
