### ISSUE TITLE
Update SiS Documentation with ClientConfig & access_token user_attributes

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#66164]
## Issue Description
The [SiS documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Sign-In%20Service) needs to be updated to include instructions on new features such as the creation and management of `ClientConfig`s and the ability to include CSP attributes in SiS access_tokens

---
## Tasks
- [x] Update SiS public documentation with a ClientConfig page
  - PR: https://github.com/department-of-veterans-affairs/vets-api/pull/12690
  - [x] include section on access_token user_attributes
- [x] Add Private Key JWT auth documentation page 
- [x]  update main SiS readme to reference and link to all 4 flows
- [x]  Add references to ClientConfig in:
  - [x] Private Key JWT flow
  - [x]  web OAuth flow
  - [x]  mobile OAuth flow
- [x]  update `/token` with access_token user_attributes section
- [x]  update `/refresh` with access_token user_attributes section
- [x] reorganize `auth_flows`: web_oauth, mobile_oauth, private_key_jwt, service_account
## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
