### ISSUE TITLE
IA Tracker: Accredited Representative Mgmt

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#66163]
## Overview
- help them get a prototype ready for testing, and do IA spec doc

### Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

### Links

- [Intake Ticket #]

### Team

- Team Name:
- Designer:
- Product Manager:
- Slack (_optional_): 

### Timeline
_When does IA review need to be completed by? When is Midpoint Review?_

## IA Support
- IA Spec Doc
- Flows

### Work Needed (if applicable)

- IA Spec: **[Needed / Not Needed]**
- Feedback for product team: **[Needed / Not Needed]**

### Tasks
Check all that apply.

- [ ] Create process ticket draft
- [ ] Watch Design Intent
- [ ] Determine IA deliverables
- [ ] Collaborate with CAIA
- [ ] Ask questions to product team
- [ ] Create IA Spec
- [ ] Mikki reviews IA Spec
- [ ] Share IA Spec with product team
- [ ] Update Site Map and VA.gov Mega IA sheet

## Acceptance Criteria
- [ ] Feedback is shared with product team in Intake Ticket.

**Comment by kristinoletmuskat** [comment]
Ticket processing doc: https://docs.google.com/document/d/1T1eB6_mzlEExnweVYxOHEqwrxiZ9-ckxVwhcyIkrTFQ/edit

**Comment by kristinoletmuskat** [comment]
Working with the team in their mural space here: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1692888741111/2474c0612887653142ab991d234898b6968dbf0e?sender=ua67f17f1c416a96ea04d2476
