### ISSUE TITLE
Add Cash in Bank Question to FSR

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#66166]
## Issue Description
Add Cash in Bank page to FSR and remove Savings and Checking account from _Your household assets_ selection page.
---
## Tasks
- [ ] _Cash in bank (savings, checking account) page added_
- [ ] _Cash, Saving, Checking account should not appear on _Your household assets_ checklist page_

## Acceptance Criteria
- [ ] _Copy is finalized_
- [ ] _Design is finalized_
- [ ] Design is passed to frontend (add front end items here or create new ticket

**Comment by amponce** [comment]
@mgleo is the logic to remove the Cash, Savings and Checking checkboxes only for the SW waiver flow or is this change part of full FSR in general?

**Comment by josephrlee** [comment]
@amponce, I believe this logic change will also apply to the full FSR flow. Right @denisecoveyduc?

cc: @mgleo

**Comment by mgleo** [comment]
@amponce Cash, Savings and Checking checkboxes should be removed for all users (full fsr) as all users will see the Cash on hand page and the cash in bank page before the financial assets pages with checkboxes.

**Comment by amponce** [comment]
Perfect! thanks all!

**Comment by mgleo** [comment]
@Tom-Davis @HeatherRienks Moved to Validate
