### ISSUE TITLE
Research Form Pre-Fill Functionality in vets-api for Forms 21-22 & 21-22a

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#66168]
### Issue Description:
The goal of this ticket is to understand the form pre-fill capabilities present within vets-api and how to set it up and utilize it for our specific forms (21-22 & 21-22a) regarding Appoint a Rep.

---

### Tasks:
- [x] Research Form Pre-Fill Functionality in vets-api for Forms 21-22 & 21-22a
- [x] Document in a comment below how to implement pre-fill for our 21-22 and 21-22a forms, also note anything we may need to consider outside of the defaults for pre-fill.

### Acceptance Criteria:
- [x] We have a clear understanding of the pre-fill functionality and how it relates to our forms.
- [ ] We understand if we need to do anything outside of the defaults.

**Comment by holdenhinkle** [comment]
Here's the pre-fill documentation - https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-work-with-pre-fill#VAFormsLibrary-HowtoworkwithPre-Fill-Vets-APIWork

**Comment by opticbob** [comment]
Form pre-fill for the `vets-api` backend is thoroughly explained here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/engineering/prefill_setup.md.  An example PR that runs through all the necessary additions is here: https://github.com/department-of-veterans-affairs/vets-api/pull/5391.

### We will need:

- Two prefill classes, one each for 21-22 and 21-22a.  These prefill classes need a metadata method that includes that we want to enable prefill, a version, and a return URL.  The return URL is the first page of the form.  Example: https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/form_profiles/va_0993.rb.
- Two form profile mappings that define what fields we want prefilled and where that data comes from.  Example: config/form_profile_mappings/28-1900.yml.
- Add the two forms to `app/models/form_profile.rb`.  They need to be defined under `ALL_FORMS` and `FORM_ID_TO_CLASS`.
- Add a definition of our form with `prefill: true` to `config/settings.yml`
- Add two tests to `spec/models/form_profile_spec.rb` to cover each form

### Outstanding questions:

1. Are our form URLs already determined?
2. Do we already have form names that map to our form numbers like `vre_readiness: ['28-1900']`?
