### ISSUE TITLE
Accessibility Orientation - October 2023

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#66175]
## User Story
As a Platform team member supporting Platform Orientation, I want to host, record, transcribe and share the Accessibility Orientation session so that VFS team members are able to be easily oriented to the VA.gov Platform. 

Assignee: @briandeconinck @erinrwhite 
Peer Reviewer:

## Description
Platform is responsible for hosting the Platform Orientation sessions once every quarter. These sessions are recorded and shared on Platform Website.

The Accessibility Orientation for FY24-Q1 is October 6 at 3:00pm ET.

## Impacted Artifacts
[Orientation Host/Zoom Host Guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2656731745/Orientation+Host+Zoom+Host+Guidance)

## Tasks
_**Note**: if the Zoom host and the Instructor/Session host are the same person, then all below tasks will be performed by the same individual._

### Zoom host
- [x] Ensure Zoom settings are set according to the guidance: [Orientation Host/Zoom Host Guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2656731745/Orientation+Host+Zoom+Host+Guidance) / Before you start your session / Zoom settings
- [x] After the session has been hosted, forward the Zoom recording to the Instructor/Session host
### Instructor/ Session host
- [x] Review the guidance in the [Orientation Host/Zoom Host Guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2656731745/Orientation+Host+Zoom+Host+Guidance) for During your orientation session
- [x] Host the orientation session as scheduled
- [x] Download mp4 and vtt files from Zoom recording
- [x] Clean up the transcript
- [x] Upload recording and transcript to YouTube
- [x] Change visibility of previous recording to Private (if applicable)
- [x] Update video link on Platform Website

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] The live Accessibility Orientation for the quarter has taken place
- [ ] VFS team members are able to view the latest recording of the orientation session

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
Session hosted, handing off to @erinrwhite to complete all of the post-session tasks while I'm on PTO.

I talk too much so there's a lot to clean up in the transcript... Let me know if there's a souvenir I can send you from Paris!

**Comment by erinrwhite** [comment]
@shiragoodman Good morning! Can you share the link to the zoom recording for Friday's accessibility orientation?

**Comment by shiragoodman** [comment]
@erinrwhite I forwarded you the Zoom recording email I received. Let me know if you didn't receive it!

**Comment by erinrwhite** [comment]
All set!

[New video on YouTube](https://www.youtube.com/watch?v=vZAmnpI7enk)
[Updated Platform orientations page](https://vfs.atlassian.net/wiki/spaces/GS/pages/2133393543/Orientation+Sessions)
