### ISSUE TITLE
[PM] My VA LOA1 updates: Submit PSIRR

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#66180]
## Background
We need to prep for, submit/complete our Privacy, Security, Infrastructure Readiness (PSIR) Review for the updates we're making to the My VA LOA1 experience.

## Tasks
- [x] Compile documentation outlined [here](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/privacy-security-infrastructure-readiness-review)
- [x] Submit [ticket](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/new?assignees=td-usds%2C+troymosher&labels=security-review&template=privacy-and-security-review.md&title=Readiness+Review+%5BTeam-Name%2C+Feature-Name%5D)
- [ ] Complete any follow up tasks

## Acceptance Criteria
- [x] Documentation prepped, ticket submitted

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)_ NA
- _How can this work be validated?_ NA

**Comment by ajakabcin** [comment]
Submitted [1293](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1293)

**Comment by ajakabcin** [comment]
Closing this out - will open separate tickets if there are findings from our PSIRR
