### ISSUE TITLE
[BE] 10-10CG - Sign as a Rep BUG: Update document_type value to match update from CARMA

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#66189]
## Background
It was discovered that since Sept 11th, some 10-10CG applications that included files uploaded, to support a legal representative to sign on behalf of the Veteran, were not being received by CARMA as expected.
The root cause is:
>The root cause of the issue seems to be from the CARMA_Document_Type__c value that is currently set as 'POA' for files that are attached for 'Sign as Representative' scenarios.
>
>CARMA had a change deployed to rename the type value  'POA' to 'Legal Representative' and we missed the impact it had for the vets-api.

We need to update the Document_type to match CARMA

## Tasks
- [x] Update the CARMA_Document_Type__c value from "POA" to "Legal Representative"
- [x] Once in Staging, coordinate with PM and CARMA team (Ranga Balasubramanian) to complete end-to-end testing
- [x] After successful testing, deploy to production

## Acceptance Criteria
- Document_type has been updated and files uploaded with 10-10CG applications are being received as expected.

**Comment by hdjustice** [comment]
This ticket is complete, right? @lihanli

**Comment by lihanli** [comment]
@hdjustice no, i made the change in a PR, then talked to marla clayton about testing it, turns out the mulesoft API is broken in the staging environment, so i'm waiting on the mulesoft team to fix it

**Comment by hdjustice** [comment]
Oh no!  Ok, thank you for the update!
