### ISSUE TITLE
IA Tracker: Request/schedule a burial

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#66196]
## Overview
When a Veteran or the family member of a Veteran passes away, they'll be able to request the interment for the deceased person without having to call into the NCSO (National Cemetery Scheduling Office) agents or having a third party like a funeral home do so for them to get a case started. Currently, users are directed on this page on what to do: https://www.va.gov/burials-memorials/schedule-a-burial/

### Description
- Need an IA spec doc

### Links

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/64903

### Team

- Team Name: Burials
- Designer:
- Product Manager:
- Slack (_optional_): 

### Timeline
_When does IA review need to be completed by? When is Midpoint Review?_

---

### Work Needed (if applicable)

- IA Spec: **[Needed / Not Needed]**
- Feedback for product team: **[Needed / Not Needed]**

### Tasks
Check all that apply.

- [ ] Create process ticket draft
- [ ] Watch Design Intent
- [ ] Determine IA deliverables
- [ ] Collaborate with CAIA
- [ ] Ask questions to product team
- [ ] Create IA Spec
- [ ] Mikki reviews IA Spec
- [ ] Share IA Spec with product team
- [ ] Update Site Map and VA.gov Mega IA sheet

## Acceptance Criteria
- [ ] Feedback is shared with product team in Intake Ticket.

**Comment by kristinoletmuskat** [comment]
IA Spec completed here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/schedule-burial-form-40-4962.md
