### ISSUE TITLE
Update vets-website Codeowners to give platform FE group ability to merge on only one approval

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#66195]
## Issue Description
Currently, if a platform effort touches any code of a VFS team, it requires that VFS team's approval to merge the code into the main branch. There are many platform initiatives where platform will have to do this and these approvals can be slow to obtain and hold up workflows. The codeowners file should be set up where a platform approval automatically clears a branch to be merged on its own, as is the case currently with vets-api.

---
## Tasks
- [ ] Update codeowners to have VA Platform COP Frontend as a qualifying reviewer for all directories.
- [x] Test to ensure that a PR opened on a VFS team's code will be satisfied by an approval from the Frontend COP only

## Acceptance Criteria
- [ ] COP frontend can approve all PRs as a sole required reviewer.
