### ISSUE TITLE
[task] DR | Update CODEOWNERS files.

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#66191]
## Issue Description

VA recently introduced a CODEOWNERS file for vets-api which ties specific directories/files to teams, so that proposed changes to files trigger a notification to their corresponding teams. This already existed on vets-website.

I've created a benefits decision reviews team https://github.com/orgs/department-of-veterans-affairs/teams/benefits-decision-reviews so that we can update the vets-api CODEOWNERS to our liking.

We should also update the CODEOWNERS file in vets-website, so that proposed changes to decisions reviews files get sent to us, but not to the benefits-management-tools team (who, like us, now have their own Github team).

I've created child teams: https://github.com/orgs/department-of-veterans-affairs/teams/benefits-decision-reviews-be/ and https://github.com/orgs/department-of-veterans-affairs/teams/benefits-decision-reviews-fe/ for vets-api and vets-website, respectively.

We should also deprecate the https://github.com/orgs/department-of-veterans-affairs/teams/benefits-team-1 team (unless there's a good reason not to), and remove any references to it across vets-api and vets-website's CODEOWNER's files.

---
## Tasks
- [x] Update Teams with recent changes, removing Rocio and Eugene
- [x] Update CODEOWNERS file on vets-api
- [x] Update CODEOWNERS file on vets-website
- [x] Deprecate https://github.com/orgs/department-of-veterans-affairs/teams/benefits-team-1.

## Definition of Ready
N/A

## Acceptance Criteria
- [x] Teams reflect current roster
- [x] CODEOWNERS file on vets-api updated
- [x] CODEOWNERS file on vets-website updated
- [x] https://github.com/orgs/department-of-veterans-affairs/teams/benefits-team-1 deprecated.

## Definition of Done
- [x] Teams reflect current roster
- [x] CODEOWNERS file on vets-api updated
- [x] CODEOWNERS file on vets-website updated
- [x] https://github.com/orgs/department-of-veterans-affairs/teams/benefits-team-1 deprecated.

**Comment by saderagsdale** [comment]
@saderagsdale add to icebox

**Comment by shaunburdick** [comment]
Removed Rocio and Eugene from the DR Teams. Updated description to point to correct DVSA Slack Channel

**Comment by saderagsdale** [comment]
@shaunburdick good to close this?

**Comment by anniebtran** [comment]
I've updated the DR related files in vets-api, but just wanted to raise that `Benefits-Team-1` is also listed as codeowner for files we don't touch like ones related to [`SavedClaim`](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.github/CODEOWNERS#L300), [gids](https://github.com/department-of-veterans-affairs/vets-api/tree/master/.github#L40), [BGS](https://github.com/department-of-veterans-affairs/vets-api/tree/master/.github#L40), etc

**Comment by saderagsdale** [comment]
@anniebtran will follow-up with other teams then close this ticket out.

**Comment by saderagsdale** [comment]
@anniebtran is this one good to close?

**Comment by anniebtran** [comment]
Update: Talked to Shaun and Thomas, they both suggested just removing `Benefits-Team-1` since it doesn't really exist anymore and posting in the benefits-engineering channel with the PR to see if anyone wants to claim the files that I cleaned up the owners for
