### ISSUE TITLE
Investigate pre-commit hook preventing commit adjusting white space

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#66199]
## Issue Description
An issue came up when a file was flagged as changed for auto-formatted whitespace changes. Due to this not being intentional, the original file was checked out from main to replace the one on the local branch and "reset" the file. However, the commit was not allowed to be made as the pre-commit hook flagged this as an empty commit due to it only containing whitespace changes. The local branch clearly showed uncommited changes, therefore this hook was inappropriately firing.

---
## Tasks
- [ ] Determine if this hook is necessary at all
- [ ] If so, figure out how to reconfigure it to allow for the above mentioned commit when whitespace changes exist.

## Acceptance Criteria
- [ ] The pre-commit hook does not prevent a case of replacing a file with its version from main.
---
