### ISSUE TITLE
Linting discovery: Why are there so many rules and why is spacing and other formatting included?

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#66197]
## Issue Description
Our collection of linting rules has inflated to quite a large size. This has caused the check in GitHub actions that runs against main to take longer than our site does to build, as well as caused many conflicts with developer work streams.

---
## Tasks
- [ ] Look through linting errors and our linting rule list to see what linting rules may not need to be present
- [ ] Make recommendations to smooth out the amount of time linting takes to run
- [ ] Consider recommendations to change some errors into warnings, to avoid work streams being blocked over insignificant issues like formatting and spacing.
- [ ] Put recommendations in a ticket for implementation.
- [ ] Schedule a discussion around the rule adjustments that include relevant parties (Likely Clint, Joe, and key front end people).

## Acceptance Criteria
- [ ] A new ticket exists with recommendations for linting adjustments.
- [ ] A meeting is scheduled to come to a consensus on the path forward.
---
