### ISSUE TITLE
Autoformatter Discovery: Conflicts with linting

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#66198]
## Issue Description
In a typical setup for an autoformatter, we would have a prettierrc file that is committed to the repository. This config file would be used by developers and/or pre-commit hooks to ensure consistent formatting of code and everything would be kept in line. However, we have had cases where the autoformatted code is failing linting in GitHub actions, when using code that was formatted regardless of a developer's behavior.

---
## Tasks
- [ ] Review autoformat configuration.
- [ ] Make note of any configurations that don't seem to have a significant purpose.
- [ ] Figure out where the disconnects are between the auto formatter and linting process.
- [ ] Note recommendations for improvement in a new ticket for implementation.
- [ ] Schedule a discussion with Clint, Joe and key front end personnel to discuss implementation.

## Acceptance Criteria
- [ ] Suggestions for improvement to the autoformatter config are in a ticket.
- [ ] A discussion is scheduled to agree on an implementation strategy.
---
