### ISSUE TITLE
Support: Mon-Thur Deploy (S37)

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#66204]
## User Stories
As a Platform team member who just contributed to the Platform website,
I need my content published,
so that I can share my content updates with the intended audience.

As a content team,
we need to review any new content changes made on the platform,
so that we can deploy every Tuesday and Thursday of the week.

## Tasks
Someone from our team will use Scroll Viewport to publish changes to the website after 3pm EST on:

- [x] Wednesday (9/27) - **Torri (last deploy)**
- [x] Thursday (9/28) - **(Brian filling in for Jill)**
- [x] Monday (10/2) - Lauren
- [x] Tuesday (10/3) - Brian
- [x] Wednesday (10/4) - **(Brian rotation)**
- [x] Thursday (10/5) - **(Lauren filling in for Jill)**
- Monday (10/9) - Holiday/cancelling deploy on this day
- [x] Tuesday (10/10) - Lauren

--- Next sprint
- [ ] Wed (10/11) - Lauren
- [ ] Thur (10/12) - Brian

Temporary rotating schedule:
https://vfs.atlassian.net/wiki/spaces/CIT/pages/2405171201/Deployment+rotation+schedule

## Acceptance Criteria

- [x] The Platform website will be deployed Monday-Thursday between 3:30 and 5pm for this sprint.
- [x] Any edits with launch-blocking issues will be announced to their content editors via #platform-content

## Other Info

Data tracking info:
https://vfs.atlassian.net/wiki/spaces/CIT/pages/2282979860/KPIs+-+Content+Support
