### ISSUE TITLE
Content edits for #65507

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#66208]
## Info
Content edits according to [support ticket #65507](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65507)

## Tasks

- [x] Review [support ticket #65507](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65507) in detail
- [x] Add disclaimer to the Process instructions that "if you do not already have access to DOTS Okta, please request this from your VA Manager".
- [x] Make content updates to the website accordingly

## Acceptance Criteria

- [x] Platform website will improved instructions on the [Get Access to Datadog](https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog) page that avoids the "hoopsnake" referred to the customer in the 2 identified steps on that page.
