### ISSUE TITLE
[FSR] Work history bugs

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#66217]
## Issue Description

There are 2 work history bugs that have been identified by UX.

#1 **User should not be able to add an End date that occurs before the Start date**

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbjNSIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0f618c3bce6bb4bce1cfd18509e357ce03b1066c/work-history-past-bug.png)

#2 **User should only see "Add employment record" button before returning to the Work History summary page.**

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb1hSIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0578518c4489b96752893b963f6a724ef352ae2b/Screenshot%202023-09-25%20at%209.43.39%20AM.png)

- **If the user is still adding work history information and not returning to the Summary page, they should see back/continue buttons**

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb25SIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5029c7a844a74f0f74889e46334bf6adfe089d97/back-continue.png)

---
## Tasks
- [ ] _Prevent users from adding an End date that occurs before the Start date_
- [ ] _Appropriate buttons are added through Work History flow_
## Acceptance Criteria
- [ ] _Bugs have been fixed_

**Comment by HeatherRienks** [comment]
Per Design sync on 9/25/23 - Do we need to add in info from past 2 years? 
@denisecoveyduc confirmed with Melonie Wheelerthat we do not need to add this info

**Comment by mgleo** [comment]
Removing information about salary info on past since it is not needed. Bugs related to date validation and buttons still need to be fixed.

**Comment by denisecoveyduc** [comment]
As per Melonie Wheeler (DMC) Past employment info is only added to ensure Veterans are keeping a job consistently. Asking financial information about their former employment is not required. Only current income needs to be captured.

**Comment by OptionSelect** [comment]
FWIW: Continue/Add button portion of ticket has been handled by my previous PR: https://github.com/department-of-veterans-affairs/vets-website/pull/27265

<img width="1221" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXEyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2bef2cdfcd48331665b265c12de808c6c04d392e/image.png" alt="image.png" />

**Comment by OptionSelect** [comment]
Still in progress for the work date validation prevention! Worth noting this was added halfway through 117!

**Comment by HeatherRienks** [comment]
Thanks!
