### ISSUE TITLE
[Frontend] Ship to Address | Permanent, Temporary - Rework

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#6621]
## User Story or Problem Statement
As a Veteran I can have two addresses that are stored in DLC database. I need the ability to be able to update both my permanent and temporary address and chose the address I want my order shipped to. The data is populated form DLC Reorder API endpoint

Design - https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/408098735 

This came from changing requirements from DLC to display both records and have the ability to update both records - the initial design had one address

## Goal
The veteran should be able to see, update both addresses and chose the address to ship order to

## Tasks
- [ ] _Modify FE design to display both addresses from API 
- [ ] _If the veteran edits address, the FE passes information to API 

## Acceptance Criteria
- [ ] _If a test user has only has a permanent address that should be displayed, the temporary address box is empty with option to 'add' 
- [ ] _If a test user has permanent and temporary address, both must be displayed and be editable
- [ ] _If a test user changes permanent or temporary address the change has to be passed in API 
- [ ] _Test user must be able to select either permanent or temporary address as the ship to address but not both 
- [ ] _The selected address must be stored and displayed on confirm order page 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mr0sari0** [comment]
This issue is connected to this PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12211

This has been completed.
