### ISSUE TITLE
Sprint 17 Objectives

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#6622]
## Priorities
1. Sprint 16 overflow
2. Address validation launch and monitoring
3. Profile 2.0: Design
4. Profile 2.0: Build
5. Refactor Vet360 Profile form components
6. Monitoring, maintenance, bug fixes, hardening, 508, etc. 

## Address validation
- [x] Any analytics-related FE work #6213
    - Analytics work (not our team) #5895
- [x] [SCREENREADER]: Focus is not being returned to the Edit mailing address button on Cancel from confirmation modal #6470
- [x] Address Validation - Add spinner when selecting a suggested address #6715
- [x] Address Validation modal does not handle failure to create address save transaction #6696
- [x] Address Validation: Go/No Go #6725
- [x] Launch to 25% #6426
- [x] [FE] Address validation: Analytics fix #7054

## Profile 2.0 Design
- [ ] Profile 2.0 Screen Copy - Account Security - #6246
  - [Design] Connected accounts updates #6731 (Carey Otto)
  - [Design] Connected Accounts UI copy #6748 (Carey Otto)
  - [ ] [Design] Tressa to make "Connected Accounts" design/copy changes #6676 
- [x] [Design] - "Personal Contact Info" : Modal to Edit-in-Place: Desktop #6739
- [x] [Design] - "Personal Contact Info" : Modal to Edit-in-Place: Mobile #6741
- [x] [Design] - "Direct Deposit" : Modal to Edit-in-Place: Desktop #6740
- [x] [Design] - "Direct Deposit" : Modal to Edit-in-Place: Mobile #6742
- [ ] Create conversation guide #2586
- [x] Matt/Tressa to prepare use cases for Pre-Usability Testing (regression test) #6628
- [x] Pre-Usability Testing Design Review #6253 

## Profile 2.0 Build
 - [x] [Matt] - Determine what can happen this sprint and the build strategy #6726 
- [x] Create feature flag to gate Profile 2.0 work #6269 
- [x] Discovery: Profile 2.0 badge/logos #6328
- [x] Ramp up profile forms to 50% #6781
- [x] Ramp up profile forms to 100% #6782
- [ ] Implement extended "Save" state on the modal #6981

## Refactor Vet360 Profile form components
- [x] FE] Erik- Release new profile forms to production and remove old legacy code #5817 (Refactoring)

## Monitoring, maintenance, bug fixes, hardening, 508, etc
 - [x] FE] Add direct deposit error for people who have fiduciary/are deceased #6090
- [x] [BE] - Change response codes for contact info transactions #6774 (Lihan)
- [x] [BE] Remove duplicate code in swagger documentation for contact information API #6002 (Lihan)
- [ ] Design - Hide Direct Deposit information if the user is incompetent or has a fiduciary #6094
- [x] [Matt] - Curate Profile 2.0 Epic #6682
- [x] [FE] BUG: non-2FA Direct Deposit users should see "set up 2FA" message #6187 (waiting for validation) (Erik)
- [ ] Clean up "dashboard" references in code throughout repo #2270 (Brad)
- [ ] Update the Health Care Application (HCA) to use new endpoint behavior #6466 (Brad)

**Comment by Samara-Strauss** [comment]
Can we close this out?

**Comment by mshea0606** [comment]
@Samara-Strauss closed.
