### ISSUE TITLE
Check what rep attributes are available for each rep in daily rep reload job

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#66223]
## Issue Description
Check if additional rep attributes, like zip-code and address 1, are available for each representative when the Veteran::VSOReloader job is executed. 

---

## Tasks
- [x] Make a list of all rep attributes available for each rep type in the daily rep reload job.

## Acceptance Criteria
- [x] Additional rep attributes, specifically zip-code and address 1, have been identified.
- [x] A comprehensive list of all rep attributes from each response is documented.

**Comment by holdenhinkle** [comment]
I confirmed that rep data being downloaded from `https://www.va.gov/ogc/apps/accreditation/` (the base URL for the `post` request) is the EXACT data made available to the public by download the files from this page - https://www.va.gov/ogc/apps/accreditation/

Only the zip-code attribute is available and needs to be added to the `veteran_representatives`.

Furthermore, the `veteran_representatives` does not contain `ssn_ciphertext` or `dob_ciphertext` values for any reps:

Here's the table info:

```
irb(main):004:0> Veteran::Service::Representative.column_names
=> 
["representative_id",                                                                               
 "first_name",                                                                                      
 "last_name",                                                                                       
 "email",                                                                                           
 "phone",                                                                                           
 "created_at",                                                                                      
 "updated_at",                                                                                      
 "poa_codes",                                                                                       
 "user_types",                                                                                      
 "ssn_ciphertext",                                                                                  
 "dob_ciphertext",                                                                                  
 "encrypted_kms_key",                                                                               
 "verified_decryptable_at",                                                                         
 "middle_initial",                                                                                  
 "encryption_updated_at"]
```

```
irb(main):008:0> Veteran::Service::Representative.where.not(ssn_ciphertext: nil).count
2023-09-25 11:01:27.054881 D [34198:59700 log_subscriber.rb:126] ActiveRecord::Base --    (18.3ms)  SELECT COUNT(*) FROM "veteran_representatives" WHERE "veteran_representatives"."ssn_ciphertext" IS NOT NULL                                                    
=> 0                                                                                                                  
irb(main):009:0> Veteran::Service::Representative.where.not(dob_ciphertext: nil).count
2023-09-25 11:01:32.235761 D [34198:59700 log_subscriber.rb:126] ActiveRecord::Base --    (2.8ms)  SELECT COUNT(*) FROM "veteran_representatives" WHERE "veteran_representatives"."dob_ciphertext" IS NOT NULL                                                     
=> 0   
```

To replicate my findings:

Update the #method in `modules/veteran/app/workers/veteran/base_reloader.rb` to the following:
```
    def fetch_data(action)
      page = Faraday.new(url: BASE_URL).post(action, id: 'frmExcelList', name: 'frmExcelList').body
      doc = Nokogiri::HTML(page)
      file_name = action.sub('.asp', '.html')

      File.open(Rails.root.join(file_name), 'w') do |file|
        file.write(doc)
      end

      headers = doc.xpath('//table/tr').first.children.map { |child| child.children.text.scrub }
      doc.xpath('//table/tr').map do |line|
        row = line.children.map { |child| child.children.text.scrub }
        headers.zip(row).to_h.delete_if { |k, _v| k.blank? } unless headers == row
      end.compact.uniq
    end
```

Start a Rails Console session and run `Veteran::VSOReloader.new.perform`.

The contents of the files created are identical to the files that the public can download.

Also, while the beginning of the error message that's logged in Sentry when a `Faraday::ConnectionFailed` exception occurs in `Veteran::VSOReloader` `#perform` is "OGC connection failed", the request is NOT made to OGC. I believe that error message is misleading:

```
    def perform
      array_of_organizations = reload_representatives

      # This Where Not statement is for removing anyone no longer on the lists pulled down from OGC
      Veteran::Service::Representative.where.not(representative_id: array_of_organizations).each do |rep|
        # These are test users that Sandbox requires.  Don't delete them.
        next if rep.first_name == 'Tamara' && rep.last_name == 'Ellis'
        next if rep.first_name == 'John' && rep.last_name == 'Doe'

        rep.destroy!
      end
    rescue Faraday::ConnectionFailed => e
      log_message_to_sentry("OGC connection failed: #{e.message}", :warn)
      log_to_slack('VSO Reloader failed to connect to OGC')
    rescue Common::Client::Errors::ClientError, Common::Exceptions::GatewayTimeout => e
      log_message_to_sentry("VSO Reloading error: #{e.message}", :warn)
      log_to_slack('VSO Reloader job has failed!')
    end

    def reload_attorneys
      fetch_data('attorneyexcellist.asp').map do |attorney|
        find_or_create_attorneys(attorney) if attorney['Registration Num'].present?

        attorney['Registration Num']
      end
    end
```

## Available Attributes

attorneyexcellist attributes:
```
<tr>
   <td>Last Name</td>
   <td>First Name</td>
   <td>Date Accredited</td>
   <td>Registration Num</td>
   <td>POA Code</td>
   <td>City</td>
   <td>State</td>
   <td>Zip</td>
   <td>Phone</td>
</tr>
```

caexcellist attributes:
```
<tr>
   <td>Last Name</td>
   <td>First Name</td>
   <td>Date Accredited</td>
   <td>Registration Num</td>
   <td>POA Code</td>
   <td>City</td>
   <td>State</td>
   <td>Zip</td>
   <td>Phone</td>
</tr>
```

orgsexcellist attributes:
```
<tr>
   <td>Organization Name</td>
   <td>POA</td>
   <td>Org Phone</td>
   <td>Org City</td>
   <td>Org State</td>
   <td>Representative</td>
   <td>Rep City</td>
   <td>Rep State</td>
   <td>Rep Zip</td>
   <td>Registration Num</td>
</tr>
```
