### ISSUE TITLE
Define how we define a launch-blocking issue

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#66226]
Assignee: @erinrwhite 
Peer Reviewer: @allison0034 

## Description
The MVP for the VA.gov Experience Standards had pre-determined launch-blocking issues, and issues that were "Depends" were determined to be launch-blocking or not based on the Governance team members professional opinion. In the revised standards, all identified issues will be determined to be launch-blocking or not on a case by case basis. 

### Potential criteria for launch blocking

- not being able to complete a task
- information is incorrect
- contradicting information
- does not match style guide?

## Impacted Artifacts
[How do document findings for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+findings+for+Staging+Review)
Note: no updates will be made to this guidance within this ticket. Once launch-blocking criteria is approved by OCTO, we will need to incorporate into SR documentation via ticket #63513

## Tasks
- [x] Propose criteria for how we determine if a specific finding is deemed launch-blocking
- [x] Document in new draft doc
   - Will be included in review with OCTO
- [x]  Share with Governance team via Slack for feedback/consensus 

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have proposed criteria for how we deem a Staging Review finding to be launch-blocking or not

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
I reviewed the [most recent 100 launch-blocking findings](https://github.com/department-of-veterans-affairs/va.gov-team/issues?page=3&q=label%3Alaunch-blocking+is%3Aclosed) and noted some themes:

These types of issues were found multiple times:
- Page elements that weren't accessible by keyboard, or weren't perceptible for screen reader users.
- Standard page elements that were missing or not in alignment (i.e. navigation items, URLs)
- User flows that had dead ends - either because of broken component functionality, broken links, unclear CTAs, or lack of wayfinding elements; or, because there were no implemented entry points.
- QA standards not met

These types of issues were less frequent:
- Health concerns - specifically motion/scrolling
- New patterns that hadn't been tested yet
- Destructive actions with no confirmation
- Incorrect information

**Comment by shiragoodman** [comment]
@erinrwhite a lot of the current VA.gov ES have a depends severity. Meaning they could be launch-blocking, but it depends on the context of the issue. One of my go-to examples of this in General Orientation is current VA.gov ES 05.02 - "The content has spelling, punctuation, or typo errors." One missing apostrophe or close parentheses will be documented as an issue, but it will not be launch-blocking. However, if there's 50 typos on 1 page, then yes, we'll block you from launch until it's resolved.

I don't think it's wise for us to list every specific, niche scenario that could occur that would make an issue launch-blocking. That could be 73 different issues (based on the current VA.gov ES - everything that is either Depends or Launch-blocking severity). 

I'm struggling to think of a better way to do this without providing a detailed list. Any suggestions?

**Comment by erinrwhite** [comment]
@shiragoodman. Heard. Maybe we go far more broad and hedge a bit, since there are so many factors. We could say something like:

> A Staging Review finding can be launch-blocking if the product keeps a user from completing a task, does not account for necessary user flows, or is too far out of alignment with design system standards.

**Comment by shiragoodman** [comment]
@erinrwhite yes, that is what I was thinking we could do. Maybe cover the extremes of each category instead of listing specifics.

**Comment by erinrwhite** [comment]
@shiragoodman Okay, cool. I'm fleshing this out a bit in a [google doc](https://docs.google.com/document/d/1x4gBYxk7PnBcV_8EJy6acscTR66bn2EVh3k-nPcUIQY/edit). Do you think it's ready for team review, or does it need more work? Thanks for the back and forth this week!

**Comment by shiragoodman** [comment]
hey @erinrwhite. Yes, this is ready. I have some comments but I'll wait until you share out with the team. Thank you!

**Comment by erinrwhite** [comment]
Updated our [launch-blocking criteria draft document](https://docs.google.com/document/d/1x4gBYxk7PnBcV_8EJy6acscTR66bn2EVh3k-nPcUIQY/edit#heading=h.dc65zrxswq7w) using categories as a guide, and shared with team for feedback on slack.

**Comment by shiragoodman** [comment]
thank you, @erinrwhite ! Echoing what I said on Slack.. This is exactly what we're looking for... enough detail to communicate what could be launch-blocking, but not too much where it's overwhelming and/or difficult to consume.

This can be closed!

**Comment by erinrwhite** [comment]
Thanks so much for the conversation and guidance on this one! 👍🏻
