### ISSUE TITLE
[Design] Sketch spacing and typography clean up 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#66233]
## Descriptions

Some design debt clean up of sketch files and components, but not to the extent of pixel perfection. 

- This only affects the Check-in sketch file ([change list](https://docs.google.com/spreadsheets/d/1Fx5djj3eVuiTgbOqkRjFKNGIDth3TMXkynFP45s1u54/edit#gid=0))
- Spacing should be based of Unified check-in sketch file.

Note: worth with UX team to ensure this ticket's work doesn't impact other work. For example, do we want to plan "freezes" on specific sketch files when these updates are being made? Work together as a team to discuss the plan.

Also, assume this should happen AFTER [change to 320 pixels](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/65448).  

## Tasks
 - [ ] Fix and clean up Production sketch file artboards 
     - Spacing - All artboards, but focus on fixing big flaws, e.g., not focusing on pixel perfection for every component's spacing, borders and margins 
     - Typography - Check same artboards for the check in artboards listed above 
     - Fix and clean up component layouts on the same artboards listed above for pre-check-in (in production Sketch file)
     - Fix and clean up component layouts on the same artboards listed above for check in (in production Sketch file)
     
- [ ] Create a ticket to determine what we want to review and compare in the codepen/storybook.

# AC

- [ ] Somehow from UX team validate the work 
- [ ] Give Lori new ticket for codepen comparison work

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/66233?planning-poker) with Zenhub @zach-park

**Comment by loripusey** [comment]
Will point next refinement

**Comment by benbrasso-agile6** [comment]
I set up meeting with team to discuss it

**Comment by zach-park** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/66233?planning-poker) with Zenhub @ytsaoca @cgednalske @kellysmith1008 @benbrasso-agile6

**Comment by benbrasso-agile6** [comment]
@zach-park how's this ticket coming along? This is our very last priority for this sprint. You good with working on this on Monday and Tuesday next week?

**Comment by zach-park** [comment]
> @zach-park how's this ticket coming along? This is our very last priority for this sprint. You good with working on this on Monday and Tuesday next week?

Yes, I'm starting on this ticket today. :)

**Comment by zach-park** [comment]
@benbrasso-agile6 , @cgednalske @ytsaoca (cc: @loripusey ), ready for validation: 
https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/v/pyMxjp/p/A6E73D11-A95C-4EC0-A3B7-792CE5799C59/canvas

**Comment by benbrasso-agile6** [comment]
Given the announcement about moving to Figma, does the team agree to skip this task for now? 

> Create a ticket to determine what we want to review and compare in the codepen/storybook.

Or, are we still looking to complete this task as part of this ticket?

**Comment by benbrasso-agile6** [comment]
Spacing and typography LGTM on each page of that file

**Comment by cgednalske** [comment]
I'm seeing some differences between this file and unified, mostly the space between different "sections" (60px in unified) and the space after the H1 before the lead text (noticeably a bit different), but I'm unsure how much of that we are trying to match knowing that we haven't compared unified to the actual code yet. Also, the annotations page in the unified Sketch file seems to have disappeared ☹️

**Comment by benbrasso-agile6** [comment]
The spacing artboard I moved much lower on the Annotations page like an hour ago because I thought we weren't using it. If that's what you're referring to.

**Comment by benbrasso-agile6** [comment]
@zach-park this one is for you to finish up based on christina's feedback please. Does it need to be addressed or not? 

> I'm seeing some differences between this file and unified, mostly the space between different "sections" (60px in unified) and the space after the H1 before the lead text (noticeably a bit different), but I'm unsure how much of that we are trying to match knowing that we haven't compared unified to the actual code yet. 

I honestly don't think we need to be comparing to code right now. But, being consistent with spacing across our files is a good goal.

**Comment by zach-park** [comment]
@benbrasso-agile6 @cgednalske, spacing is updated and ready for re-validation.
