### ISSUE TITLE
Usability Testing Prep -- Benefits Delivery at Discharge only form 526ez

### ISSUE THREAD

**Issue by chrvalla** [department-of-veterans-affairs/va.gov-team#6623]
## Steps to complete Usability Testing Prep: 
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP <> **requesting team** review meeting completed
- [x] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [x] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [x] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - 
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/9150bf79b341250cc13bbf80f49a385ef439be61/products/disability/disability-compensation-claim/bdd/product-outline.md)
- Link to or attach [prototype] (https://vsateams.invisionapp.com/share/Z8W8ACWN3UG) 
- Link to [research plan](products/disability/disability-compensation-claim/bdd/BDD Research/Initial-usability-March2020/BBD-Research-Plan.md) 
- Link to [coversation guide](products/disability/disability-compensation-claim/bdd/BDD Research/Initial-usability-March2020/BDD conversation guide.md) 

-We are in a hurry to get testing started, reach out to Luke for QA artifacts. 

## Meeting attendees from **requesting team**
- Product Manager (required): **Luke Majewsky**
- DEPO product lead (required): **Andrea Schneider**
- Anyone else from your team who significantly contributed to the artifacts provided (required): **Christian Valla, Shawna Hein**

## Scheduling
Preferred dates or times: March 6th or 9th

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product

**Comment by andreahewitt-odd** [comment]
Scheduled for 3/10

**Comment by pjhill** [comment]
@luke-gcio Are there any QA artifacts available for perusal?  Do you need help creating a test plan based on user stories and acceptance criteria?

**Comment by tlei123** [comment]
> @luke-gcio Are there any QA artifacts available for perusal? Do you need help creating a test plan based on user stories and acceptance criteria?

@luke-gcio, can you confirm that BDD is brand-new to va.gov please?  I don't think there's any need for Regression Test Plan, but just want to make sure.  Product outline says this is being migrated from eBenefits site.

Please let us know.  Thanks much!

cc @pjhill

**Comment by pjhill** [comment]
> > @luke-gcio Are there any QA artifacts available for perusal? Do you need help creating a test plan based on user stories and acceptance criteria?
> 
> @luke-gcio, can you confirm that BDD is brand-new to va.gov please? I don't think there's any need for Regression Test Plan artifact since it's a new va.gov product, but just want to make sure. Product outline appears to describe migrating this functionality from eBenefits site.
> 
> Please let us know. Thanks much!
> 
> cc @pjhill

@tzelei Thanks for digging in!  Even when we are creating a "new" product on the platform, it may be prudent to identify the functionality being duplicated from "old" products as part of the baseline functionality that makes the "new" product minimally viable.  Whether we identify that initial suite of tests as "regression" or as a new "suite of functional tests" doesn't matter too terribly much, but we do need to do the work of creating those test scenarios.

**Comment by 1Copenut** [comment]
VSP accessibility comments:

**⚠️ Should**
* https://vsateams.invisionapp.com/share/Z8W8ACWN3UG#/screens/407963718 && https://vsateams.invisionapp.com/share/Z8W8ACWN3UG#/screens/407963725 should have a view that shows the typeahead in action. Testing this paradigm is always a good idea.
* https://vsateams.invisionapp.com/share/Z8W8ACWN3UG#/screens/407963730 has the bullet points spaced quite far apart. This seems out of the standard black bullet point styling.

**✔️ Consider**
* https://vsateams.invisionapp.com/share/Z8W8ACWN3UG#/screens/407963580 would benefit from a view where users answer "No" on the anticipated separation date. It's worth testing the redirect message.
* https://vsateams.invisionapp.com/share/Z8W8ACWN3UG#/screens/407963524 The What other ways can I file my disability claim section could benefit from a reusable pattern where we include a few items:

```html
<h3>By mail</h3>
/* This is a React component that could be used to offer a bit more information */
<Learn more />
<a href="#">Learn more about filing by mail</a>
```

**Comment by joanneesteban** [comment]
**VSP Analytics Comments/Questions**

Thanks for including your OKRs in the product outline! Are the KPIs for this initiative the metrics from the KRs? Or are those separate?

**Comment by tlei123** [comment]
@chrvalla / @luke-gcio , a couple quick questions...

1.  Is 526ez on ebenefits site a web-based form (submitted online)?
1.  IF yes to above, can I get a test-account to see the current (baseline) functionality?

Please let me know.  Thanks much!

**Comment by chrvalla** [comment]
All of the research and documentation complete. Please find the research documentation here:  https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/disability-compensation-claim/bdd/BDD%20Research/Initial-usability-March2020
