### ISSUE TITLE
[discovery] NOD | Investigate ability to notify Veterans of NOD deadlines

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#66238]
## Issue Description

I'm breaking off "Use Case 2" ("Veteran wants to know when their filing deadline is approaching so they can take action") from https://github.com/department-of-veterans-affairs/va.gov-team/issues/62597 into this smaller discovery ticket.

There is a possibility that we can hook into decision events (when an unfavorable decision is made) via VRO, who integrates with the BIE/BIP event bus. The question is whether the events that VRO does currently offer contain the information we need (e.g. decision date, Veteran info) to schedule notifications about deadlines. If they don't, the question is how long it would take for VRO to offer what we need.

---
## Tasks
- [ ] Read https://github.com/department-of-veterans-affairs/abd-vro/wiki/BIE-Kafka-Client to see if VRO offers the event and information we need.
- [ ] If not clear from the docs, ask VRO engineers (#VRO-ENG in the VRO support channel).
- [ ] If not currently offered, ask VRO how long it would take to offer.
- [ ] Figure out high-level implementation details of a potential VRO integration.

## Acceptance Criteria
- [ ] We know whether we could, with a reasonable amount of effort (and likely through VRO), schedule NOD deadline notifications for Veterans.

## Definition of Ready
- [x] We know who to reach out to at VRO

## Definition of Done
- [ ] We know whether we could, with a reasonable amount of effort (and likely through VRO), schedule NOD deadline notifications for Veterans.
- [ ] We've relayed this information to design for their follow-up.

**Comment by data-doge** [comment]
@saderagsdale @HeatherWidmont I reviewed the [BIE docs](https://github.com/department-of-veterans-affairs/abd-vro/wiki/BIE-Kafka-Client). `bie-events-contention-updated` is the event we're hoping represents a decision date being set on a contention. I couldn't easily find any details about this event in their docs though, so I've reached out for assistance in their slack channel. See https://dsva.slack.com/archives/C01Q7979Z7D/p1695672069101509. Marking this ticket as blocked until we get a response.

**Comment by data-doge** [comment]
It's possible that a `RatingFinalizedEvent` may be the event we need. Sade reached out to Karla Leal to figure out whether that may be the case. See slack thread linked above. It may also be possible that the `bie-events-contention-updated`, mentioned above, will work as well. Diana created a ticket in VRO's sprint to look into whether that may be the case. See same slack thread. 

I'm leaving this ticket in "blocked" until we get a response.

**Comment by data-doge** [comment]
Just a note: in https://github.com/department-of-veterans-affairs/va.gov-team/issues/66251 we learned that we don't send decision letters by email. We could start sending decision letters via email (or notifying Veterans to their presence in CST) upon receiving the relevant event from VRO.

**Comment by HeatherWidmont** [comment]
@saderagsdale to follow up with Diana's team to see if they have finished investigation into the work

**Comment by saderagsdale** [comment]
Followed up with Diana in the [slack thread](https://dsva.slack.com/archives/C01Q7979Z7D/p1695672069101509) today. Waiting for her input on a path forward to find the event data we want.

**Comment by saderagsdale** [comment]
Update from Diana:

> Following up here — I did not find any event topics in the BIE documentation that currently include PRMLGN_DT. I will double check this finding with the BIE team when we meet on Friday.
> However, I noticed a couple of promising event topics planned for future development, which don’t yet have a full list of included fields defined:
> [Subdomain: Correspondence](https://confluence.devops.va.gov/display/VAExternal/Subdomain%3A+Correspondence)
> currently on the BIE roadmap for FY24Q2
> Includes event topic [CorrespondenceSentEvent](https://confluence.devops.va.gov/display/VAExternal/CorrespondenceSentEvent)
> [RatingFinalizedEvent](https://confluence.devops.va.gov/display/VAExternal/RatingFinalizedEvent) (which Yang referenced above)

currently on the BIE roadmap for FY24Q3

**Comment by saderagsdale** [comment]
- Waiting to hear from Karen on demo for their prototype
- Backup is to request this event formally form BIE team

**Comment by saderagsdale** [comment]
Followed up with Karen again.

**Comment by HeatherWidmont** [comment]
Karen got back to @saderagsdale, now we're just waiting on Karen to send the invitation for the demo

**Comment by saderagsdale** [comment]
Karen gave a demo and noted that the current event structure is slightly different from what we need. I've [asked for an LOE ](https://dsva.slack.com/archives/C5AGLBNRK/p1700669468453859)to understand what would need to be changed.

**Comment by saderagsdale** [comment]
Update from Karen:

Here's what we found out from BIP about the PI Planning outcome for this:

- Correspondence Events are slated for the first half of the PI.
- Note that initial info and research on these pages in Confluence ([DirectCommunicationEvent](https://confluence.devops.va.gov/display/VAExternal/DirectCommunicationEvent) and [CorrespondenceSentEvent](https://confluence.devops.va.gov/display/VAExternal/CorrespondenceSentEvent)was)) was compiled in 2021 and hasn’t been touched since.
- Data design is subject to change, and it is unknown at this time if Claim Letter Date will or won’t be an available piece of data in either of these events.
- Research on this is starting in this sprint, and BIP should know more by the end of the sprint.
- We'll ask in next week's sync call if they have research results to share.

**Comment by saderagsdale** [comment]
Update from Karen:

- Research is still in progress, BIP should have info on this at the end of the sprint (2/9).
- Later than anticipated because the person doing the work got sick.
- An initial set of Database Properties have been identified to populate the events. Further refinement of the initial set is required and is dependent on the communication with the identified points of contact.
- We won't get a link to the ticket, we can potentially get a 1-2 sentence summary of the scope of the research work done.
- Outcome of the research should be an understanding on if this can be done soon.
- When the research is completed, the status for the [DirectCommunicationEvent](https://confluence.devops.va.gov/display/VAExternal/DirectCommunicationEvent) and the [CorrespondenceSentEvent](https://confluence.devops.va.gov/display/VAExternal/CorrespondenceSentEvent) on the [Event Catalog page for Correspondence Events](https://confluence.devops.va.gov/display/VAExternal/Subdomain%3A+Correspondence) will change from Draft to In Dev.

**Comment by saderagsdale** [comment]
This week's update:

- A possible source of data has been found, but it's complicated.
- More research is needed.
- Systems that BIP would pull data from have three dates: the date that the letter is generated by the system, the date on the letter itself (this is the next mailing day; holidays and weekends are excluded), and the date that the letter actually goes into an envelope and is mailed (there is no way to know this).
- Don’t know which of the two dates that can be known will end up on one of these events.
- Correspondence Sent Event may be a misleading name, given that there is no way to know the date when the letter actually goes in the mail.

**Comment by saderagsdale** [comment]
Karen provided this update on 3/15:

> We chatted with the BIP folks about this again yesterday. Status:
> 
> - Had to descope the research/implementation from this PI to replace it with a critical item.
> - Now preparing for the upcoming PI and don’t expect to have capacity to pick this back up.
> - No Further ETA, and unclear if this will be considered in the next PI.
> - cc 
> - [@Alan Werner](https://dsva.slack.com/team/U05U87EN613)
> -  (Alan is the product manager for the Event Bus Outreach and Support team who is tracking this on our side).
