### ISSUE TITLE
[Design] Sketch spacing and typography clean up 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#66232]
## Descriptions

Some design debt clean up of sketch files and components, but not to the extent of pixel perfection. 

Note: worth with UX team to ensure this ticket's work doesn't impact other work. For example, do we want to plan "freezes" on specific sketch files when these updates are being made? Work together as a team to discuss the plan.

Also, assume this should happen AFTER [change to 320 pixels](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/65448).  

## Tasks

- [ ] Fix and clean up Pre check in sketch file artboards 
     - Spacing - All artboards, but focus on fixing big flaws, e.g., not focusing on pixel perfection for every component's spacing, borders and margins 
     - Fix and clean up component layouts on the following artboards: 
          - https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/a/bLao5rj#Inspect
          - https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/a/uuid/BF1CC921-8177-4277-ABEC-50B85F99F6AE
          - https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/a/uuid/C6CA0793-EDAD-4B86-AA9B-8DD41A41AF80
          - https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/a/uuid/80387136-298A-4A89-9D19-54DB995F00C4
          - https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/a/uuid/62A062A5-4334-4675-95FC-C57C9431F48A
          - https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/a/uuid/C1B6FB6F-2AC5-488F-A3CA-05A57750174A
          - https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/a/uuid/5947B75A-200E-48DA-B871-D2854104857A
          - https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/a/uuid/457FCD99-60D8-4A10-BA26-98444B24CF9F
          - https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/a/uuid/CE54F504-B413-4680-9BFF-48F9FFC12934
          - https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/a/uuid/67EA19A1-C4D2-4C77-B0D0-9510DA0025A6
 - [ ] Fix and clean up Check in sketch file artboards 
     - Spacing - All artboards, but focus on fixing big flaws, e.g., not focusing on pixel perfection for every component's spacing, borders and margins 
     - Typography - Fix on the following artboards: 
          - https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/uuid/36DFEC66-1913-4A7E-A290-ADC1B4C5B734
          - https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/uuid/59322C8C-5437-458E-97B0-9CA506F83873
          - https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/uuid/E44E6C27-CCAA-4B8B-A22B-64693127F1C6
          - https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/uuid/8A3725A9-F1D1-4AA1-AAC9-D83CD6707D40
          - https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/uuid/00EF1EC2-E2BB-463D-9F0C-9F93B7419C30
          - https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/uuid/86BA1B5A-9BCC-4CBE-9DBF-1F53BD7CD10C
     - Fix and clean up component layouts on the following artboards: 
          - https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/uuid/3105EBC1-585B-49B0-B85D-CE91F0A90104
          - https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/uuid/240EBCC2-AD7B-447B-A3CC-5FDFDA8D2E23
          - https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/uuid/E608AE80-7494-4EB5-A7C7-567A3396C843
          - https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/uuid/6C0C9C0D-7DE5-4D62-A01B-5561007BA63E
          - https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/uuid/BDF63D5B-95E0-42E9-A26D-8AFD3EE47AB0
          - https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/uuid/A64302C2-DE85-46DF-A8A0-66948D41033F
          - https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/uuid/45320963-62BD-49CF-AEDF-E021B9DCF00C
          - https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/uuid/90EF733B-0C0B-4187-A996-3995A7B1C86F
          - https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/uuid/40A32ED0-467A-4AB1-B950-5D76BEAF20FD
          - https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/uuid/2EC4CEFF-117C-40CD-B0FC-2BD5659F4CF6
          - https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/uuid/FB52EF82-15CB-4EF4-B1A0-D7865CC13B7D
          - https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/uuid/0847DABF-ABAD-4BE3-8174-812CEE62C147
          - https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/uuid/A233C821-5D5F-491A-B169-EBEF81C3CE6C
          - https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/uuid/4A2C4DCB-E4FF-4E6B-9FB9-2A2F17D23E6C
          - https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/uuid/DD188C8A-C087-4287-A96B-A76FA600C4C7
          - https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/uuid/DCD98AAE-9F01-45F7-BC3F-77E9FD371880
 - [ ] Fix and clean up Production sketch file artboards 
     - Spacing - All artboards, but focus on fixing big flaws, e.g., not focusing on pixel perfection for every component's spacing, borders and margins 
     - Typography - Check same artboards for the check in artboards listed above 
     - Fix and clean up component layouts on the same artboards listed above for pre-check-in (in production Sketch file)
     - Fix and clean up component layouts on the same artboards listed above for check in (in production Sketch file)

# AC

- [ ] Somehow from UX team validate the work

**Comment by benbrasso-agile6** [comment]
dupe, closing
