### ISSUE TITLE
[discovery] NOD | Can we get the exact decision date of contestable issues absent from "Issues for review" page.

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#66231]
## Issue Description

I'm breaking off "Use Case 1" ("A Veteran wants to know the exact decision date when adding a new issue") from https://github.com/department-of-veterans-affairs/va.gov-team/issues/62597 into this smaller discovery ticket. Also, as a note, in that previous spike ticket, I got off track with design's expressed need, which I'll articulate now as: "Helping Veterans get the exact decision date for a manually added issue that did not appear in the 'Issues for review' page."

The underlying problem here is that the issue in question didn't appear on the "Issues for review" page. We get these issues from LH's contestable issues endpoint. LH says this endpoint is intended to return a complete list of contestable issues, both disability and non-disability. But occasionally the endpoint times out and no issues are displayed. In that case, the Veteran can "add a new issue" and manually indicate the issue and decision date. But, the Veteran may not know the decision date. In the NOD prototype that design is currently testing, there is a link to the claim status tool, where Veterans would be able to find this information. So, in a way, this problem is already resolved.

If there is a way to get contestable issues and their decision dates from an alternative source when LH times out or otherwise fails, we could pursue that. I can talk to Jerek about that to see if he's aware of such a source. If he's not, then I think we should just rely on the link to the CST, which is already in place in the NOD prototype.

On a separate but related note, the decision dates we get from LH are "approximate," but it's unclear how approximate. We ought to know what the range is, as it could warrant a disclaimer. According to Lighthouse, "This is the actual decision date in most cases, but I'll also follow up with Caseflow to see what the range is." https://dsva.slack.com/archives/CKUCFQAHJ/p1693357390891949.

## Tasks
- [ ] See if Jerek is aware of an alternate source for contestable issues and decision dates.
- [ ] Figure out how approximate LH's decision date is.

## Acceptance Criteria
- [ ] We know whether there is an alternate source for contestable issues and decision dates.
- [ ] We know how approximate LH's decision date is.

## Definition of Ready
- [x] Confirm with design whether this is the right inquiry and whether this information is useful.

## Definition of Done
- [ ] Acceptance criteria fulfilled.
- [ ] We've relayed this information to design for their follow-up.

**Comment by Mottie** [comment]
After speaking with Jerek about decision letters in the eFolder, I learned the following:
- There isn't an "official" decision date. There is a [date at the top of a decision letter](https://drive.google.com/file/d/1C6XH9iOqq7MpYjiW2mKDaNERaskXG-R8/view) of when it was written, but it may not show up in the eFolder until the following day. Maybe they batch upload letters?
- If a Veteran submits multiple issues with an appeal, the VA (Board, regional office, or whomever) may not make a decision on all the issues at once. For example:
  - If 6 issues were appealed, the VA may make a decision on 3 and defer the remaining 3.
  - A letter would still go out that a decision was made, but it won't apply to all 6 issues.
  - Once the remaining 3 issues have a decision, then the appeal will be closed and a final decision is made, and another decision letter is sent out
  - Our front end won't display deferred issue, so the Veteran may be trying to add a deferred issue
- We can coordinate with squad 1 on getting decision letters, and then display them to the Veteran
- Alternatively, we may need to check the rated disability endpoint to find decision dates

**Comment by Mottie** [comment]
I spoke with Jerek again, Rated Disabilities is the only app showing disabilities. They use the same controller that 526 uses, which currently comes from EVSS, and soon to be coming from Lighthouse.

**Comment by data-doge** [comment]
Thanks @Mottie! I'll close this ticket then. EVSS isn't an alternative source of data that I think we should try to rely on.
