### ISSUE TITLE
Add cash in bank page and combine calculations with cash on hand

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-team#66245]
## Issue Description
Per Cash on Hand team huddle on 9/25/23, we need to make the following changes:

1- Add Cash in Bank page to FSR and remove Savings and Checking account from _Your household assets_ selection page.

This is the Frond End ticket to put in place the design work from #[66166](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/66166)

2- Remove non-monetary calcs from long form and add new monetary questions (cash in bank and cash on hand) 

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description
- [x] Add Labels
- [x] Attach to an Epic
- [ ] Estimate Points
- [x] Testing defined
- [x] Acceptance criteria
</details>

---
## Tasks
- [x] _Cash in bank (savings, checking account) page added_
- [x] _Cash in bank (savings, checking account) question added to review page_
- [x] _Cash, Saving, Checking account should not appear on _Your household assets_ checklist page_

## Acceptance Criteria/Testing
- [x] Cash in Bank and Cash on Hand calculations should be combined
- [x] Unit tests pass
- [x] E2E tests cover current code and regression
- [x] End-to-end tests show 0 violations.
- [x] The data returned matches API response (for given user or scenario)
- [x] All axe checks pass
- [x] All color contrast checks pass
- [x] All zoom testing passes
- [x] All keyboard checks pass 
- [x] All screenreader checks pass

| Cash in Bank | Updated Checklist | Review page view |
| -------- | ------- | ------- |
| <img width="320" alt="1 0 Monetary assets - cash in a bank (dan userflow only) - mobile" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/5553542/4424d8fa-6c09-43ef-9f3e-54e8a8a571dc">  | <img width="320" alt="2 0 Monetary assets - checkboxes - mobile" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/6e3f91f6-ac24-4b5e-b3d4-6c5dca7191a5"> | <img width="457" alt="Screenshot 2023-09-22 at 10 43 16 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/7ab90162-cffb-4f86-bf9c-1747a8649d74"> |

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

**Comment by mgleo** [comment]
For reference: 
- [Design ticket #66166](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/66166)
-  Useflows ([Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1678973946956/6f3bb65fe1ccc2b9d3bc38cd24cd09e74d18d778?sender=ua78f969c4cddcbfe56b27885)) 
-  Wireflows ([Sketch](https://www.sketch.com/s/f8f84ed8-16b1-4caa-b88a-19acd400ba7e))

**Comment by denisecoveyduc** [comment]
Quick clarifying question. Does this ticket encompass removing the assets from the calculation or are we spinning up a separate ticket for that?
@HeatherRienks @Tom-Davis

**Comment by HeatherRienks** [comment]
@denisecoveyduc - great question! Let's confirm with FE team (on the AC, it's noted that the Cash in Bank and Cash on Hand calculations should be combined, but we did not note to remove the assets from the calculation.

We could prob add that to the acceptance criteria for this ticket? @Dr-Pongo, @amponce, @OptionSelect - what are your thoughts?

**Comment by amponce** [comment]
@denisecoveyduc 

Slack thread regarding your question :) https://dsva.slack.com/archives/CPE4AJ6Q0/p1695829129643279

**Comment by Dr-Pongo** [comment]
@denisecoveyduc @HeatherRienks @Tom-Davis 

Just wanted to drop an update here so everyone is in the loop! 
We need to move these asset changes (cash in hand & cash in bank) behind a feature flag because we're changing the definition of 'assets' for streamlined waiver after the feedback from vha. This could potentially break in progress forms because veterans could potentially be further along than they need to be based on the new requirements, and that would cause form breaking issues.

Example: a veteran who was kicked to the full FSR after being dq'd because of assets made it down to resolution options, they save for later and then come back and try to hit continue, but our streamlined calculations with the new definitions would run and they would try to hit a page that we are disabling and it would just kick them to the beginning, or do some other unexpected behavior. 

Aaron made the following ticket, and added the new feature flag, and we are gong to work on adjusting our changes with that! **Add new feature flag for Streamlined Waiver Calculations [#66505](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/66505)**

Just wanted to add another note, once we make these changes we should be able to just flip this flag to true, and then we should start seeing any _new_ submissions come through with the adjusted requirements, so like with any change to the FSR there will be a lag in submissions with the new changes.

**Comment by Dr-Pongo** [comment]
Looks solid to me! If anyone has questions let us know!

**Comment by HeatherRienks** [comment]
Really appreciate all the great updates!

**Comment by Tom-Davis** [comment]
I second that - this all looks excellent!

**Comment by Dr-Pongo** [comment]
Cash in bank update has been completed and is now in the staging environment. Going to do some more testing before flipping the feature flag to true tomorrow 10/3!

**Comment by Dr-Pongo** [comment]
Started a new PR to address some bugs found during stating testing! Fixing question content, and review page display. [Link to slack thread with more info](https://dsva.slack.com/archives/CPE4AJ6Q0/p1696276453881359)

**Comment by amponce** [comment]
@Dr-Pongo has merged the bugfixes 🎉
