### ISSUE TITLE
<Content Support> VA Chatbot: Prescription Skill Feature

### ISSUE THREAD

**Issue by coforma-terry** [department-of-veterans-affairs/va.gov-team#66249]
## CAIA Content Assignees
-	@strelichl 
- @laurwill 

## VA Chatbot Team

- Team name: VA Chatbot
-	OCTO-DE product owner:  Nathalie Rayter
-	Product manager:  Joy Elizabeth
-	Designer: Matt Terwilliger
- Accessibility specialist:
- Content writer: 
-	Slack channel: va-virtual-agent-public
 
## About this Product

This Rx feature is an external feature being ported into the chatbot. The content is coming from another vendor called RAIN group, which is a sub to Iron Bow. This Rx feature is a project of the Office of Connected Care at VHA.

</br>
</br>

### VA Chatbot Sync 

- [x] Sync Chatbot [Google Doc: 9/19/2023 Notes - **READ ME**](https://docs.google.com/document/d/1oXWhIEdNweu35oizOGdG-CRNIFT8F0HrAXqNgaj74ok/edit?usp=sharing)
- [ ] Sync: Chatbot Content (Internal) **9/25/2023 NOON EST** (@coforma-terry or @strelichl can you 🔗 to notes?)
- [ ] Sync: RAIN, CAIA, and Chatbot team members needed to discuss the VA.gov standards for content **9/25/2023 at 1 p.m. EST** (@coforma-terry or @strelichl can you 🔗 to notes?)

## Product next steps
* **Staging Review Date**: Oct. 5, 2023
* **Launching**: Plan is the first week of October
* **Research**: One more round of testing (third round) in progress around the voice control options. (Feedback on research findings requested in intake/EPIC #64157]

## CAIA Content Assistance

```[tasklist]
### Tasks
- [ ] TBD
- [ ] TBD
- [ ] TBD
```

**Comment by coforma-terry** [comment]
Will update tasks after Thursday's meeting with team.

**Comment by laurwill** [comment]
Update: I worked with Danielle to provide initial feedback on the chatbot feature content. 

Collab cycle flagged a content issue in staging review, so we can leave this open until that's resolved.
