### ISSUE TITLE
[discovery] NOD | Figure out whether/how Veterans get decision letters by email

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#66251]
## Issue Description

I'm breaking off "Use Case 3" ("A Veteran wants to have to have their decision letter delivered via email, because decision letters don't always arrive in the mail") from https://github.com/department-of-veterans-affairs/va.gov-team/issues/62597 into this smaller discovery ticket.

In a perfect world, Veterans would always receive decision letters via email, so they wouldn't have to wait for snail mail that could arrive after the appeal deadline, or never arrive. I don't know whether emails are always sent to every Veteran when a decision is made on a claim (disability OR non-disability). The questions here are: 1) do we send emails for all decisions, and 2) if we don't, what would it take to do so?

Things to consider:
- It's possible that people can elect to receive emails or not receive emails.
- VANotify has an inventory list of all the emails that they send out. That would be a good thing to find and check.
- It's possible that each individual form team is responsible for notifications regarding their form. For instance, maybe 526ez sends email notifications about decision dates, but not COE.
- It's possible that the reason that some Veterans haven't gotten emails is because emails weren't built yet (and the email notification problem is now resolved, because it was built). It would be good to know, if these emails exist, when that email notification feature was launched.
- Disability is the priority for NOD. We can treat notifications for non-disability claims a second priority, and shouldn't get into any deep rabbitholes there.

---
## Tasks
- [ ] Figure out whether we send emails for all decisions to all Veterans
- [ ] If we don't, figure out what it would take to do so

## Acceptance Criteria
- [ ] See Tasks

## Definition of Ready
N/A

## Definition of Done
- [ ] Acceptance criteria met.
- [ ] We've relayed this information to design for their follow-up.

**Comment by Mottie** [comment]
After [chatting with Beverly Nelson](https://dsva.slack.com/archives/C5AGLBNRK/p1695664859693439) is DSVA Slack, we now know that no decision letters are sent via email. The VES Event Bus team is working on delivering benefit claim decision letters with a plan to send an email directing the Veteran to the Claim Status Tool.

Our team will need to contact the VES Event Bus team in `#ves-event-bus` channel about decision review letters.
