### ISSUE TITLE
Review Medallia Survey Data 

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#66257]
## Issue Description
Team 1 and Team 2 would like to collaborate to review written survey feedback from veterans about their experience with 526ez form in order to understand their pain points and where to focus our efforts for improvement.

Scope of this ticket is to:
-become more familiar with on-site survey data
-develop a process for reviewing survey data going forward
-analyze a segment of the data TBD

This work does not require a research plan because user recruitment is not needed.

This work will be followed by creating a report that summarizes findings from the survey data.

Note: [Analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/research/MedalliaSurvey-032023.md) has already been done on feedback submitted on intro/start pages only

---
## Tasks
- [x] Request Medallia survey data
- [x] Clean data and remove PII
- [x] Identify which pages to focus on
- [x] Migrate data into Mural and tag responses
- [x] Synthesize data by page
- [x] Synthesize data by feedback type
- [x] Draft findings in Mural alongside relevant responses

## Acceptance Criteria
- [x] Findings are ready to be summarized in report

**Comment by juliepedtke** [comment]
Data request has been completed! Starting to clean the data in a collaborative file in SharePoint.

**Comment by evelynhilbrichdavis** [comment]
Data is cleaned and organized in Sharepoint. We decided to focus on Feedback/Intercept entries for March 2023 as a way to focus our efforts. We have tagged all comments by type as well as reason for leaving feedback. We are moving  data (scrubbed of PII) into Mural for further affinity mapping. Team 2 will continue synthesis work next week while I am on company retreat.

**Comment by evelynhilbrichdavis** [comment]
This ticket will wrap up this sprint; reporting will be completed in the following.

**Comment by evelynhilbrichdavis** [comment]
Mural synthesis board: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1696525694420/4791b8ce60aeec63df3dc1dee348728050f530b3?sender=u9f3830b1ee3516bdcf2e2000

**Comment by evelynhilbrichdavis** [comment]
Synthesis is complete, moving onto reporting.

**Comment by evelynhilbrichdavis** [comment]
Plan for research: https://docs.google.com/document/d/16LiaPs2TyUUUcXIgAjlaz2ujjrau4yRXaav63pzxu3Q/edit
