### ISSUE TITLE
Offboarding for Cheryl Evans

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#66270]
## User Story
As the Governance team Product Manager, I want to make sure I identify all important tasks for offboarding Cheryl so that I am able to find proper coverage and ensure no responsibilities are dropped.

Assignee: @CherylEvans 
Peer Reviewer: @shiragoodman 

## Description
Cheryl's last day is September 29. The purpose of this ticket is to identify all work she is contributing to so that we may come up with a plan of action for transitioning. 

## Tasks
- [x] Review "How to complete a content review for Staging Review"
- [x] Review "How to complete a content review for Midpoint Review"
   - comment within doc where changes may need to be made
- [x] Identify places where Cheryl's name needs to be removed from internal documentation & platform website (replace with TBD) - documented in ticket #62189
     - [ ] [Governance Team PO Transition Plan](https://vfs.atlassian.net/wiki/spaces/~624b430af6a26900695fd7f7/pages/2520318008/Governance+Team+PO+Transition+Plan)
   - [x] [Contact Us page](https://vfs.atlassian.net/wiki/spaces/CC/pages/1764524036/Contact+us)
   - [x] [Orientation slide decks](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions)
   - [x] [Design Intent slide for beginning of meeting](https://docs.google.com/presentation/d/1c1U0FMX1Efbr7Rs2RfikLKdbTVWEH4n28aGZoVas4jE/edit#slide=id.g23db8d1d252_0_248)
   - [x] [Governance team homepage on Confluence](https://vfs.atlassian.net/wiki/spaces/PPST/overview)
   - [x] [DraftingTemplate](https://docs.google.com/spreadsheets/d/1zabutKbKQnZMb3A2hxs-OaB7q6j8DWw1xcFaCfFDIVw/edit#gid=654390984)
   - [x] [On Support document](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2454093924/On-Support+guide)
   - [x] Design Intent distribution list
   - [x] Midpoint Review distribution list
   - [x] Staging Review distribution list
   - [x] Collaboration Cycle Calendar
   - [x] Governance team distribution list (for auto-forwarding Zoom recordings)

- [x] Introduce Brian to content community of collaboration
- [ ] ~~Complete platform offboarding ticket~~
   - Andrea will take care of this
- [x] Uninvite Cheryl from:
   - [x] Governance standup
   - [x] Planning
   - [x] Retro
   - [x] Refinement
   - [x] Weekly Initiative Meeting
   - [x] Collab Cycle timeblocks
   - [x] CC office hours
## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have offboarded Sara from her responsibilities and tasks for Governance team

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by CherylEvans** [comment]
@shiragoodman GM. This is ready for your peer review. 
Here is my message the content-community-collaboration:
"Good morning, everyone! :sunshine: As some of you may know, I am transitioning from the Governance team to a non-VA project. My temporary replacement is 
@Brian Smolensky, from the Platform Content team. Brian will cover both teams until my permanent replacement is on board. He will primarily cover the Collaboration Cycle touchpoint reviews. I don’t think he is a member of this channel, so I invited him to join. It’s been a pleasure working with and collaborating with you all. :slightly_smiling_face:  Please contact me with any additional questions, comments, or concerns. Thanks again! "

**Comment by shiragoodman** [comment]
message sounds good, @CherylEvans !

I did move this back to In Progress because I want to keep it open until we have you removed from the identified lists, groups etc.

**Comment by shiragoodman** [comment]
this ticket will likely remain open through next week as several of the changes need to occur after your last day. I will take responsibility for completing it.

**Comment by CherylEvans** [comment]
@shiragoodman, I understand. Thank you! :-)
