### ISSUE TITLE
Review Debt Portal for instances of the DMC Ops Box (Due by: 10/23/23)

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#66279]
## Issue Description
DMC is removing an email box from circulate. As such we have been asked to review the debt portal and identify any instances where Veterans are directed to email:

> DMCOPS.VBASPL@va.gov

**Note:** Veterans will need to be asked to reach out via ASKVA (AVA) by **October 24, 2023**

---
## Tasks
- [x] Review debt portal and identify any instances where Veterans are directed to reach out via the above email address. 
- [ ] Pair with backed to see if email is being used anywhere
- [x] Attach screenshots of those instances
- [x] Update to the new AVA contact

## Acceptance Criteria
- [x] All instances (if any) have been identified and documented. Notify @denisecoveyduc 

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by josephrlee** [comment]
Here are all the instances of it showing up:
<img width="629" alt="Screenshot 2023-09-26 at 10 16 52 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/cd751f70-cc95-41ff-b66c-ce7a68d2419e">

**Comment by josephrlee** [comment]
@denisecoveyduc, can you confirm that this is the correct link for Ask VA? https://ask.va.gov/

**Comment by denisecoveyduc** [comment]
Hi @josephrlee  Yep that is the correct email address.  I confirmed with the new AVA team and they will have redirects set up once they migrate over to va.gov so we are good to integrate when we replace this DMC Ops email box. Thx

**Comment by josephrlee** [comment]
@denisecoveyduc So to recap, we just need to replace these instances with the AskVA link and update the verbiage where it currently says to email to click on Ask VA instead?

**Comment by denisecoveyduc** [comment]
Yes @josephrlee  That is correct!  Now that you have identified that we do indeed have many instances of this email. We need to update the verbiage to point Veterans to Ask VA instead of [DMCOPS.VBASPL@va.gov](mailto:DMCOPS.VBASPL@va.gov) Once that has been done I will notify them and they will deprecate the email address entirely.

**Comment by josephrlee** [comment]
Also, [based on this discussion](https://dsva.slack.com/archives/CPE4AJ6Q0/p1695675700248559), the links will open in the same window and not a new tab to keep the same pattern as the rest of the site.

**Comment by josephrlee** [comment]
cc: @HeatherRienks @Tom-Davis this ticket is all done and has been closed out!

**Comment by denisecoveyduc** [comment]
Thanks @josephrlee  for your work on this! 
@HeatherRienks @Tom-Davis I will close this out with the DMC Team as well so they can officially depreciate the old email address. Our changes were the final step in their process.

**Comment by josephrlee** [comment]
@denisecoveyduc, here is a sample of the changes that were made:

<img width="536" alt="Screenshot 2023-10-05 at 12 39 19 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/cad73e1f-bf24-4dcd-9267-54aabf663267">
<img width="579" alt="Screenshot 2023-10-05 at 12 39 14 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/022664aa-d5f7-4af5-91cc-74ffce253ad1">

The same change was made to all the different instances of the email.

**Comment by denisecoveyduc** [comment]
Thank you @josephrlee  I passed it on the the DMC folks for their awareness. I appreciate the quick work on this.
