### ISSUE TITLE
[FSR] Update file name tracking

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#66277]
## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description
- [x] Add Labels
- [x] Attach to an Epic
- [ ] Estimate Points
- [x] Testing defined
- [x] Acceptance criteria
</details>

## Description

This is a housekeeping ticket to update the content on this [documentation page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/fsr_field_names.md). 

## Testing
- [X] N/A if non development work
- [ ] Testing passed and documented in this ticket

Testing procedure:

## Acceptance criteria

- [ ] The [documentation page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/fsr_field_names.md) is current.
