### ISSUE TITLE
Matt/Tressa to prepare use cases for Pre-Usability Testing (regression test)

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#6628]
## Background
A Regression Test is required as part of the Pre-Usability Test checkpoint for the VSP Collaboration cycle. The Regression Test requires use cases/user stories for the product/feature in the current state as a baseline. 

## Regression Test Plan
Note: If you already have a regression test plan for your product's baseline in TestRail you can forego this step. However, as your changes are integrated you will need to continue to update your regression test plan to reflect the new baseline.

Regression test plans should represent a basic suite of test scenarios that cover the baseline functionality of your product prior to changes from your current development effort.

## Tasks
- [x] Define user stories for each component of the Account and Profile sections
- [x] Review with Samara
- [x] Submit use cases to Peter Hill in order to build Regression Test baseline

## Additional Info
We already have use case information prepared for Direct Deposit and Address Validation.

**Comment by mshea0606** [comment]
Use cases/acceptance criteria have been created and forwarded to @pjhill for the creation of the Regression Test baseline

**Comment by mshea0606** [comment]
@mshea0606  Regression test updates needed:
- connected accounts
- delete contact information
