### ISSUE TITLE
[BE] 10-10EZ: Encryption library does not support large strings

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#66291]
## Background
During the PACT Act enrollment period, we noticed an increase in validation errors:

validation error detected: Value at 'plaintext' failed to satisfy constraint: Member must have length less than or equal to 4096

We confirmed these are not coming from ES.
The root cause is that the encryption library we are using does not support large strings.

We need to change the encryption library

---
## Tasks
- [ ] Determine using a different encryption library
- [ ] Add new encryption key in devops
- [ ] Add new submission jobs

## Acceptance Criteria
- There are no further errors due to encryption library restrictions on large strings
