### ISSUE TITLE
Create AL2-based SOCKS Proxy

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#66292]
# Description
Now that we have some understanding of how the SOCKS proxy is built and deployed as well as a paradigm for taking a step toward GHA and EKS orchestration, we need to implement the plan with SOCKS.

# Tasks
- [ ] Create a new repository for the SOCKS configuration
- [ ] Create a Terraform configuration in the new SOCKS repository that builds a SOCKS instance using the hardened AL2-based image
- [ ] Deploy the new SOCKS build side by side with the existing SOCKS build
- [ ] Point some subset of traffic at the new SOCKS instance
- [ ] Test
- [ ] Resolve defects

# Acceptance Criteria
- [ ] A new SOCKS instance based on AL2 hardened image is up and running

**Comment by pjhill** [comment]
_Recommendation:_
In a post-MVP ticket, once the AL2 hardened image is available, we should alter the configuration to use the hardened version being worked [here](https://app.zenhub.com/workspaces/platform-lights-team-633efe4ca5a428e5294d7ade/issues/gh/department-of-veterans-affairs/va.gov-team/65935).

**Comment by pjhill** [comment]
Here's the SOCKS repository -- https://github.com/department-of-veterans-affairs/pso-tf-socks-proxy
