### ISSUE TITLE
Create AL2-based Prometheus

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#66296]
# Description
Now that we have some understanding of how the Prometheus is built and deployed as well as a paradigm for taking a step toward GHA and EKS orchestration, we need to implement the plan for Prometheus.

# Tasks
- [ ] Create a new repository for the Prometheus configuration
- [ ] Create a Terraform configuration in the new Prometheus repository that builds a Prometheus instance using the hardened AL2-based image
- [ ] Deploy the new Prometheus build side by side with the existing Prometheus build
- [ ] Point some subset of traffic at the new Prometheus instance
- [ ] Test
- [ ] Resolve defects

# Acceptance Criteria
- [ ] A new Prometheus instance based on AL2 hardened image is up and running
