### ISSUE TITLE
Create AL2-based Jumpbox

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#66295]
# Description
Now that we have some understanding of how the Jumpbox is built and deployed as well as a paradigm for taking a step toward GHA and EKS orchestration, we need to implement the plan for the Jumpbox.

# Tasks
- [ ] Create a new repository for the Jumpbox configuration
- [ ] Create a Terraform configuration in the new Jumpbox repository that builds a Jumpbox instance using the hardened AL2-based image
- [ ] Deploy the new Jumpbox build side by side with the existing Jumpbox build
- [ ] Point some subset of traffic at the new Jumpbox instance
- [ ] Test
- [ ] Resolve defects

# Acceptance Criteria
- [ ] A new Jumpbox instance based on AL2 hardened image is up and running
