### ISSUE TITLE
ARM MVP - User Test - Planning

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#66293]
## Issue Description
User test for ARM experience including Veteran representative engagement questions as well as VA.gov representative experiences of:
1. Search
2. Select
3. 21-22 digital form
4. 21-22 PDF generation
---
## Tasks
- [x] Analyze kick-off themes
- [x] Create GitHub research plan
- [x] Define screener questions
- [x] Create GitHub conversation guide
- [x] Submit all materials to team for review
---
## Acceptance Criteria
- [ ] All materials complete and ready for team review

**Comment by jfinnerty13** [comment]
Research folder: https://github.com/department-of-veterans-affairs/va.gov-team/tree/e5a83e2095ed14c3b7478db4021da697e24d9419/products/accredited-representation-management/research/2023-10-ARM-findarep-usertest-1
