### ISSUE TITLE
[FE] Terms of Use - Second iteration of feedback

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#66309]
## Description
Update the content from the feedback

## Tasks
- [ ] Update the terms of use pages to reflect the feedback from Content/IA in regards to the 2nd iteration of ToU UX/Content feedback session
    - [ ] Updates the content in the va-alert
        - [ ] Removes "in person" for generic
        - [ ] Updates va-alert paragraph to be more generalized (aka removes "websites" in favor of "online services")
    - [ ] Decline page ([update all content from what was suggested](https://github.com/orgs/department-of-veterans-affairs/projects/929/views/1?filterQuery=terms+of+use&pane=issue&itemId=35282278))
