### ISSUE TITLE
BE | Profile | Direct Deposit | Business Transaction Rule Error (fraud flag?)

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#66315]
## Background
Lighthouse returns the following error when making direct deposit update requests:
```
PUT	400	Bad Request

No changes were made. 
Request was sent to Benefits Gateway Service (BGS), but BGS update failed.
Unknown issue(s). Raw response from BGS: 'Update Failed: 
GUIE50041&FABusnsTranRule(CFABUSNS_TRAN) Failed with Exception!! FILE: 
FABTInterfaceCreator.cpp LINE: 354This update is being elevated for additional review due to 
an Incident Flash associated with this Beneficiary: - An unexpected error was encountered. 
Please contact the System Administrator. Error is: 
GUIE50041&FABusnsTranRule(CFABUSNS_TRAN) Failed with Exception!! FILE: 
FABTInterfaceCreator.cpp LINE: 354This update is being elevated for additional review due to 
an Incident Flash associated with this Beneficiary:'-enroll
```

Turns out this might actually be caused by a fraud error. [Slack thread where Tom advised that BGS responded to our email saying it's fraud related](https://dsva.slack.com/archives/C909ZG2BB/p1696340808029559?thread_ts=1696255535.694939&cid=C909ZG2BB).  

Samara emailed a contact about fraud counts to see just how many users we have that have a fraud flag since this error is driving some volume of our errors we're seeing.

## Tasks
- [x] Update error parsing code.
- [x] Write spec to test parsing.

## Acceptance Criteria
- [ ] Unit tested
- [ ] Test in staging

**Comment by tpharrison** [comment]
I need a bit more time to look into some questions that came up from the VSP Identity team around logging.
