### ISSUE TITLE
Implement/fix Stress Test reporting

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#66313]
## Issue Description
In order for teams to have all the tools they need at their disposal to fix their broken tests, we need to ensure our reporting gives a clear picture of what's wrong. The E2E Stress tests generate reports, however, the failure videos don't work. Additionally, the unit test stress test currently produces no reports. Reporting will provide teams the tools they need to correct their failing tests.

---
## Tasks
- [ ] Fix E2E Stress Test report videos so they show up when there's an e2e failure.
- [ ] Implement reporting for Unit Test stress test

## Acceptance Criteria
- [ ] All stress test reporting functions as intended.
---

**Comment by CBonade** [comment]
Unit test stress test reports working in CI. The standalone Unit Test Stres Test that runs overnight has too many tests that run and results in the javascript heap running out of memory. We may be able to adjust some settings on the runners etc to solve for this, but as of right now this does not seem feasible. Moving on to E2E Tests CI report. The overnight E2E Stress Test report will likely have the same issue.

**Comment by CBonade** [comment]
E2E CI Stress test reporting implemented. Code cleaned up. PR is running CI will be done first thing in the morning and up for approval.

**Comment by CBonade** [comment]
Creating another ticket to address the overnight checks and their memory issue when running. The part of this ticket that's in scope to resolve is open in a PR just awaiting approval and has cleared CI with 0 errors. Moving this ticket to review.
