### ISSUE TITLE
[SPIKE] [DESIGN] Questions to consider for reducing design overhead 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#66318]
## Questions to answer 

How might we...

1. Reduce design overhead as it relates to the following scenario (or other similar scenario): "Need Help?" components (which is being shipped to production quite quickly) need updates across unified check in, pre-check-in, check-in and production sketch files. One solution that was suggested was, what would be the impact if we stopped using pre-check-in and check-in sketch files? And, just manage the unified check in sketch file and the production file. A question would remain, where would "feature" work be added if it was specific to production, and therefore, would need to be updated in the production and unified check in sketch files? 
2. Explore other methods to document different states of components as a means to reduce design overhead work. For example, [va.gov Profile](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c) uses annotations in their artboards and connects them to the different states (e.g., collapsed, expanded, etc.) all in the same artboard. Though this exact method may not work for us because we have a more complex userflow. Christina has played around with versions of this approach a bit in this [Playground Sketch page](https://www.sketch.com/s/845dc4de-d3ec-4dab-a14a-f89d79c47de5/p/36A43BC7-2B5C-4992-A6AE-331AFAD4CA32/canvas#Version), which we can review and discuss. 
**Questions to keep in mind if we move towards a version of states:** Are we replacing our Annotations page? Is one method better than the other? Is one method better than the other in specific scenarios? If so, what's the protocol for determining the solution in order to be consistent?

## Tasks

- [x] Hold 2 1-hour meetings (w/o preparation) and answer the above questions
- [x] Create f/u tickets for next steps, as needed based on answers

## AC

- [x] Questions are answered
- [x] F/u tickets for next steps are created, as needed

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/66318?planning-poker) with Zenhub @cgednalske @kellysmith1008 @ytsaoca @zach-park

**Comment by benbrasso-agile6** [comment]
I'll assign myself for now to set up these meetings

**Comment by benbrasso-agile6** [comment]
Meeting 1: 
We created new instructions for contributing to sketch files [published here](https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/p/6AC919C2-7027-4BCE-ACE6-53D727E010DE/canvas). 

Create f/u ticket for where to move "old" feature pages in unified check in sketch file. (I'll do this later.)

**Comment by cgednalske** [comment]
We looked at the [design trial page in the Playground file](https://www.sketch.com/s/845dc4de-d3ec-4dab-a14a-f89d79c47de5/p/36A43BC7-2B5C-4992-A6AE-331AFAD4CA32/canvas). We have more questions around symbols and how content approach factors into this. Set up another meeting for next Tuesday to give folks a chance to think through things.

**Meeting notes:**

- Team likes the idea of continuing down this path (continue to simplify design page and keep annotations page)
- Zach brought up great questions about accordions and how to show all the states for some of these more challenging
- Ya-ching mentioned the same for confirmation pages and accordions and suggested turning the annotations page into more of a table
- Ya-ching also mentioned further simplifying the design page (in trial) - Highlight the difference by getting rid of the buttons too (anything repeated) 

**Team consensus:**
- Continue to simplify design page and keep annotations page
  - Key artboard + Use case artboards that simplify by not repeating any components and only showing differences
  - These should still be separate artboards so we can always link to individual artboards for engineers
- Also continue to consider the best way to hand off to devs

**Next steps:**
- Think through symbols (Zach) and content (Kelly)
  - Kelly continue thinking through content and how it works into this
  - Zach think through accordions to provide an example
- Ya-ching (and Zach) think through ways to continue streamlining the design page trial 
- Everyone think through the questions + dev handoff process

**Comment by benbrasso-agile6** [comment]
@ytsaoca can you drop a link or screenshot in here on the format that we decided on? Then, let's everyone give a thumbs up/validate. 

No new tickets needed. @loripusey I'm going to get rid of that placeholder ticket that UX had.

**Comment by loripusey** [comment]
closing, @ytsaoca don't forget to drop that link/screenshot in here (see above)
