### ISSUE TITLE
[FE] Onsite Notifications: Release hiding of notifications section

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#66331]
## Background
Once the product guide is updated we can hide the notifications section on My VA. We'll do this by turning the flag on - so that when `my_va_hide_notifications_section` is turned _on_ the section is not visible on production.

## Tasks
- [x] Flip feature flag on 
- [x] PM to update project outline

## Acceptance Criteria
- [x] Notifications section is not visible on My VA in production
