### ISSUE TITLE
[FSR] Review page navigation testing

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#66330]
## Issue Description
Complete tests for review page navigation. This includes adding tests to confirm review navigation toppers are not interfering with normal page flow. 

---
## Tasks
- [x] Manually test [review nav pr](https://github.com/department-of-veterans-affairs/vets-website/pull/26509) to sus out any weird edge case bugs
- [ ] Write e2e tests for review page navigation
- [ ] Write/update e2e tests to confirm review page navigation is not interfering with existing functionality 

## Acceptance Criteria
- [ ] e2e tests for review page navigation is complete
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
This might roll into 112 with just a single point's worth of effort left in the PR that's tied to it currently. Just running through tests and fixing some bugs we found

**Comment by Dr-Pongo** [comment]
General navigation is looking solid, doing some remaining checks for detecting spouse changes before PR is ready to rock!
