### ISSUE TITLE
Document user experience of the allow list

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#66332]
## Issue Description
We need user-facing documentation explaining how the allow list works and how it impacts teams.

---
## Tasks
- [x] Write up a user-facing document that outlines how the allow lists work.
- [x] Move it to a location that makes sense in platform website.

## Acceptance Criteria
- [x] An approved user-facing document exists on platform website
---

**Comment by CBonade** [comment]
https://vfs.atlassian.net/wiki/spaces/pilot/pages/2776858625/Test+Stability+Review
