### ISSUE TITLE
[Design] Create Wireframe for Current Text Message to Add "When you arrive at the facility....."

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#66338]
## Description

At one of the clinics at Pittsburg VAMC University Drive, MSAs and staff are finding that some Veterans check in, but are at the mall (close by) or still at home. And, staff call them back before their appt time, but then mark as a No Show because they're not there.

What can we edit to the [existing text message](https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/WdnnwRq) to let Veterans know to be at the facility and wait in the waiting room. 

We can probably draw inspiration from the [content work done in the 45 min text message](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/g1bYDVj). 

## Tasks
- [ ] Create wireframe
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?
- [ ] When ready, update wireframe across appropriate sketch files and pages

## Acceptance Criteria
- [ ] Wireframes available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.

**Comment by loripusey** [comment]
The ticket referenced above was for the 45-minute reminder, I thought the intent of this ticket was to add the same messaging to the current text that a Veteran receives when they text "check in" to 53079. I thought we had not done that work yet. Maybe I'm wrong. cc @benbrasso-agile6 @kellysmith1008

**Comment by kellysmith1008** [comment]
Ope - you're 100% correct, @loripusey - I didn't realize that when I first read the ticket. Sorry about that!

**Comment by kellysmith1008** [comment]
@zach-park I'm going to work on the content today (should be fairly simple) and then I'll let you know here when it's ready for mock up.

**Comment by kellysmith1008** [comment]
@zach-park I mocked up the content and tagged you on it in the sketch file - please check for spacing and such.

**Comment by loripusey** [comment]
LGTM

**Comment by benbrasso-agile6** [comment]
LGTM great job all

**Comment by kellysmith1008** [comment]
Looking good, @zach-park! Thanks!

**Comment by benbrasso-agile6** [comment]
@loripusey this goes to either Rob or us/CHIP. I'm going to close this ticket assuming you have the next step. 

https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/uuid/F1A91500-3443-471D-B9EF-71A76BAB9360

We'll just want to know what it is released.
