### ISSUE TITLE
Toxic Exposure Data Mapping Discovery

### ISSUE THREAD

**Issue by alatempa24** [department-of-veterans-affairs/va.gov-team#66349]
## Issue Description
We want to review the current Lighthouse contract against the current Toxic Exposure mocks to identify where we might be able to put the data. 

https://www.sketch.com/s/c353146f-eceb-4626-9918-7603c693417f/p/E0A782B2-E693-4BF0-97E1-F1502DB0593F/canvas

---
## Tasks
- [ ] Make a document with the findings / issues to share in the migration channel
- [ ] Discuss with stakeholders

## Acceptance Criteria
- [ ] Make a document with the findings / issues to share in the migration channel
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lydiahooper** [comment]
See bottom of final wireframes page in Sketch file for instructions on where to put the data that the user enters in digital 526 on the downstream 526 PDF that will be in VBMS: https://www.sketch.com/s/c353146f-eceb-4626-9918-7603c693417f

**Comment by sethdarragile6** [comment]
Made a wiki page [Toxic Exposure Data Mapping Discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/toxic_exposure_data_mapping_discovery.md) to generally consolidate all our docs, threads and questions around this. The conversation is still in progress...
