### ISSUE TITLE
Burial form deactivation launch

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#66340]
## Issue Description

This is a draft order of operations for the deactivation of the burial allowance form next Wednesday. 

---
## Tasks 
Leading up to launch (work started in [Remove online burial form entry points from static pages #62552](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62552))
- [ ] Remove links to form from how to apply for a burial allowance static page 
- [ ] Remove form intro page from left nav
- [ ] Redirect any other links to form to "how to apply" page

Launch
- [ ] Add widgets

## Acceptance Criteria
- [ ] Burial page deactivated
---

**Comment by katherine-fung** [comment]
Closing this ticket after an update from Emily Theis on Tuesday, 10/24: 

"We confirmed after looking at some sample cases of 530 (burial), we will not deactivate this form. Although it is out of date and there are general quality concerns, sample cases were processed by pension automation as expected. Updating the form remains a priority. apologies to all who spent time on the deactivation work here. we'll retrospect on this whole process to make sure we capture lessons learned."
