### ISSUE TITLE
Copy of Add "decision reviews" to claim status tool

### ISSUE THREAD

**Issue by katherine-fung** [department-of-veterans-affairs/va.gov-team#66352]
## Issue Description
Shireen asked us to incorporate decision reviews into the [Check your VA claim or appeal status](https://www.va.gov/claim-or-appeal-status/) landing page and online tool. 

We'll need to coordinate with the product team(s) currently working with this tool content, and with Mikki/Joni on IA considerations for changing the H1. 

**Update:** This ticket is for the work in the tool and we'll open a separate ticket to update the landing page.

---
## Tasks
- [x] Do SEO research on "decision reviews" (Laura)
- [x] Review tool and suggest updates to headers and other instances of "claims and appeals"
- [x] Pass to product team

## Acceptance Criteria
- [x] Tool content updated

**Comment by katherine-fung** [comment]
closing duplicate issue
