### ISSUE TITLE
Incident Commander Toolkit Updates 

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#66357]
## Description 
This ticket will house updates to the IC toolkit page here (add screenshots, etc.): https://vfs.atlassian.net/wiki/spaces/PTST/pages/2652504280/Incident+Commander+toolkit

---

## Definition of Done
All the tasks below are finished.

---

## Tasks 
- [x] Mural created [here](https://app.mural.co/t/vetext2737/m/vetext2737/1697212271178/b21c1adc29846e51c74f77bf56f385a170ac66b4?sender=u3c33a098fbf4a56a2e489741)
- [x] Team is able to contribute any notes to Mural 
- [ ] Meeting held to discuss IC process 
- [ ] Flowchart created in mural
- [ ] Updated list of IC resources created
- [ ] Run flow of IC by Clint 
- [ ] Update Confluence 

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by lindsay-insco** [comment]
Meeting moved to 10/31 (Halloween!) to collaborate with team as a whole.

**Comment by alyssagallion** [comment]
Putting on hold because there is a much bigger conversation happening at the VA level (Erika/Apurna). Per conversation on PO Sync on 11/2.
