### ISSUE TITLE
Copy of Review PDF to determine missing info from VA claim exam page

### ISSUE THREAD

**Issue by katherine-fung** [department-of-veterans-affairs/va.gov-team#66351]
## Issue Description

Tanekwa asked us to review a PDF about C&P exams to determine if there is any information that isn't already on our [VA claim exam (C&P exam)](https://www.va.gov/disability/va-claim-exam/) page. The team creating the PDF worked with Danielle already to make sure it was written in plain language. 

PDF to review: [https://app.zenhub.com/files/133843125/3afe4819-a4d9-4ef1-9349-dfe198c0ac19/download](https://app.zenhub.com/files/133843125/3afe4819-a4d9-4ef1-9349-dfe198c0ac19/download) 

## Tasks
- [ ] Compare PDF to VA.gov page (Katherine)
- [ ] Let Tanekwa know what information is missing (Katherine/Randi)
- [ ] Create ticket for follow up work if needed (Randi)

## Acceptance Criteria
- [ ] PDF reviewed and missing info determined

**Comment by katherine-fung** [comment]
closing duplicate
