### ISSUE TITLE
Update decision reviews page based on research findings

### ISSUE THREAD

**Issue by katherine-fung** [department-of-veterans-affairs/va.gov-team#66353]
## Issue Description
Benefits Team 1 shared [user research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/2022-11-Decision-Reviews/research-findings.md) about decision reviews. We need to review their findings and iterate on the ["Choosing a decision review" page](https://www.va.gov/resources/choosing-a-decision-review-option/). 

For Board Appeals specifically, a participant thought there was a discrepancy for the timeline for Board Appeals under ‘How long does a decision review take?’ They said it was misleading to see 365 days (1 year) only to see that submitting evidence and hearings can take up to 730 days (2 years).

---
## Tasks
- [ ] Review research findings and decide what we can incorporate into the "Choosing a decision review" page
- [ ] Update "Choosing a decision review" page
- [ ] Update "Board Appeals" page

## Acceptance Criteria
- [ ] Updates to "Choosing a decision review" page will address some of the pain points that came up in user research
- [ ] Time frame will be more clear to users on "Board Appeals" page 
---

**Comment by aprocik1** [comment]
@bethpotts and @katherine-fung, I've reviewed the team's content-related [finding](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/2022-11-Decision-Reviews/research-findings.md#2-when-faced-with-a-decision-review-scenario-the-decision-review-options-page-showed-mixed-results-in-helping-veterans-confidently-choose-a-decision-review-option) and [recommendation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/2022-11-Decision-Reviews/research-findings.md#recommendations). They'd like us to "provide more relevant, tailored" content on this page. What do you think of my suggestion below?

## Suggestion
I think we could focus our response to the first H2, "Which decision review option is right for me?" Here are my suggestions:
- Remove information about filing each decision review option, since we link to each decision review page
- Add eligibility information from each decision review page, outlined in the featured content box

For example, this is how the first H3 would read (after removing filing information, but before adding eligibility information):
>### If you have new evidence
>File a **Supplemental Claim** if you have new and relevant evidence that we didn’t consider before. We can help you gather any new evidence you identify (such as medical records) to support your claim.
>
>A reviewer will decide if this new evidence changes the decision.
>
>[Learn more about Supplemental Claims and how to file](https://www.va.gov/decision-reviews/supplemental-claim/)
>
>**Note:** You can also submit new evidence with certain types of Board Appeals. Keep reading on this page to learn about Board Appeals.

## Note
After reviewing our decision review pages, I'm left with this out of scope, but related reflection: I think there's a larger audit and update needed to make all our decision review content more clear and concise. The pages below present very similar content in slightly different ways.

We could consider merging these two resources and support pages:
- [Choosing a decision review option](https://www.va.gov/resources/choosing-a-decision-review-option/)
- [Decision reviews FAQs](https://www.va.gov/resources/choosing-a-decision-review-option/)

We could consider standardizing the presentation of content on each of these decision review pages:
- [Supplemental Claims](https://www.va.gov/decision-reviews/supplemental-claim/)
- [Higher-Level Reviews](https://www.va.gov/decision-reviews/higher-level-review/)
- [Board Appeals](https://www.va.gov/decision-reviews/board-appeal/)

We could consider merging these two "after" pages:
- [After a Board Appeal decision](https://www.va.gov/decision-reviews/board-appeal/after-board-appeal-decision/)
- [After you request a decision review](https://www.va.gov/decision-reviews/after-you-request-review/)
