### ISSUE TITLE
Atlas App Documentation 

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#66361]
## Description 
This ticket will house documentation updates to 
https://dsva.slack.com/archives/C02RLAUM2LV/p1695747253189549

---

## Definition of Done
All of the tasks below are complete. 

---

## Tasks 

- [x] Track down all of the places
- [x] PR to update links in va.gov-team repo (might need engineer to help with this?)
- [x] Update links in confluence
- [x] Alyssa notifies in proper external channels (Product CoP, Team of Teams, and Lainey/Lindsay Hattamer's team)

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by bdech** [comment]
Markdown and YAML files that need to be updated https://github.com/search?q=repo%3Adepartment-of-veterans-affairs%2Fva.gov-team+%22VFS+Roster%22&type=code

**Comment by bdech** [comment]
GitHub va.gov-team mentions and access requests templates that need to be updated

https://github.com/department-of-veterans-affairs/va.gov-team/blob/5ab2971f8b17f39e7c6d304d1b2563396d8e916d/teams/vsp/teams/insights-analytics/gtm-ga-customer-support-guide.md?plain=1#L51

https://github.com/department-of-veterans-affairs/va.gov-team/blob/5ab2971f8b17f39e7c6d304d1b2563396d8e916d/products/platform/research/planning-resources/how-vsp-does-research.md?plain=1#L163

https://github.com/department-of-veterans-affairs/va.gov-team/blob/5ab2971f8b17f39e7c6d304d1b2563396d8e916d/.github/ISSUE_TEMPLATE/vetsapi-flipper-ui-access.yaml#L11

https://github.com/department-of-veterans-affairs/va.gov-team/blob/5ab2971f8b17f39e7c6d304d1b2563396d8e916d/.github/ISSUE_TEMPLATE/socks-access-request.yml#L10

https://github.com/department-of-veterans-affairs/va.gov-team/blob/5ab2971f8b17f39e7c6d304d1b2563396d8e916d/.github/ISSUE_TEMPLATE/aws-access-request.yml#L10

https://github.com/department-of-veterans-affairs/va.gov-team/blob/5ab2971f8b17f39e7c6d304d1b2563396d8e916d/.github/ISSUE_TEMPLATE/vetsapi-sidekiq-ui-access.yaml#L11

https://github.com/department-of-veterans-affairs/va.gov-team/blob/a286e0699490633193cd72f63d3c60a789b41cba/.github/ISSUE_TEMPLATE/vetsapi-argo-terminal-access.yaml#L10

**Comment by bdech** [comment]
PR to update vets-api-flipper access template
https://github.com/department-of-veterans-affairs/va.gov-team/pull/67067

**Comment by bdech** [comment]
PR to update all docs and access request templates in va.gov-team repo
https://github.com/department-of-veterans-affairs/va.gov-team/pull/67082

**Comment by bdech** [comment]
The following confluence docs have been updated:

https://vfs.atlassian.net/wiki/spaces/PPST/pages/2583658517/Steps+for+completing+Platform+tasks+on+a+Platform+Orientation+ticket

**Comment by alyssagallion** [comment]
Moving to backlog until further notice. VFS Roster still in place.

**Comment by jknipes** [comment]
@alyssagallion and @bdech we will be ready to take over Atlas during this sprint 12/20-1/3

**Comment by flooose** [comment]
Hey everyone, I was in contact with Brandon about this and he had provided me with a PR for the work he had previously done, but then been forced to revert because Atlas wasn't really _quite_ ready.

Unfortunately, in the context of my support work, I forgot about this and started [my own PR for these updates](https://github.com/department-of-veterans-affairs/va.gov-team/pull/72569). 

Let me know how you'd like to move forward with this.

**Comment by alyssagallion** [comment]
FYI we are creating documentation in [this ticket](https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/73715). Closing this ticket.
