### ISSUE TITLE
Identify Code Owners for Static CMS Content Page

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#66363]
## Description

Tammy Hurley maintains an old static page for education on va.gov and has no team to assist with PR approval and merging. The team needs to find a home for Tammy's work and define a process for the future. 

---

## Definition of Done
All of the tasks below are complete.
---

## Tasks 

- [x] Identify GovCIO education team and codeowners 
- [x] Reach out and begin discussion about ownership of Tammy's work 
- [ ] Decide on process 
- [x] Communicate with Erika and possibly Tammy

--- 

## Resources & Additional Info 
- Original Request: https://dsva.slack.com/archives/CBU0KDSB1/p1695406075718529
- Internal thread: https://dsva.slack.com/archives/C02RLAUM2LV/p1695408750210129

---

**Comment by lindsay-insco** [comment]
I was able to reach out to the GovCIO team that works in education and benefits but they are also unable to assist at this moment. Their product owner's name has been passed on to Erika and the issue will be discussed between them. Unfortunately this leads to no resolution for us in the immediate moment, but the appropriate parties have been communicated with.
