### ISSUE TITLE
Research | Profile | Military Information | Desk Research 

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#66362]
## Background

We've been given quite a bit of background information from our VEO stakeholders and need to work through understanding it. 

## Tasks 
- [x] Review [updated project outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/military-information/2023-enhanced-military-information/README.md)
- [x] Review past research
- [x] Review ILER documentation
- [x] Write summary doc

## Acceptance Criteria
- [x] Summary doc is complete
- [x] Ready to start #65973

**Comment by mtcA6** [comment]
@pamela-drouin @andaleliz could you add some points to this before planning? 
I think you said it earlier as a 3 or 5 Liz but my memory is failing

**Comment by andaleliz** [comment]
I'll give it a 5 for now based on what we know - Pam, feel free to change that if you disagree!

@mtcA6 can you let us know when the markdown version of the product outline is updated from the google doc? It'll be way easier to review when it's free of the markdown markup (e.g. ugly URLs) in the google doc.

**Comment by mtcA6** [comment]
@andaleliz updated, still have some additional changes to incorporate but the latest and greatest is in there now.

**Comment by mtcA6** [comment]
Hoping to regroup with @Samara-Strauss, tomorrow to work through the remaining open items on the google doc. 

However, how permanent do you view these documents? I view a project outline in the discovery phase as a very much living breathing document, as we learn more it necessarily needs to expand or shrink as we progress through things.

**Comment by Samara-Strauss** [comment]
> However, how permanent do you view these documents? I view a project outline in the discovery phase as a very much living breathing document, as we learn more it necessarily needs to expand or shrink as we progress through things.

Agreed.

**Comment by pamela-drouin** [comment]
5 points makes sense to me as well.

**Comment by mtcA6** [comment]
@andaleliz was able to catch up w/Samara this morning and I'll update the last couple of items that I hadn't resolved yesterday. Likely will be in there by EOD as I'm working on getting things ready for planning!

**Comment by mtcA6** [comment]
@pamela-drouin @andaleliz uploaded the latest version. Should be ready for you all! 

I'll rework the legislation section with a graph as I mentioned in the comments ASAP, but I don't think that shouldn't block you at this point.

**Comment by pamela-drouin** [comment]
@mtcA6 thank you for the update! It's great to see this taking shape. I have a number of clarifying questions to help me get on the same page (bear with me 😅 )

> Section 803(b)(2) requires VA to promulgate a regulation defining the “evidence considered necessary.” 

 - Pam Q: Is there a sense of when VA might promulgate a regulation defining the evidence required to update a record?

> **It is important to note that ILER is not an authoritative data source**, there is an API for generating text/pdf exports of the data but ILER is owned by DoD not the VA. 

 - Pam Q: What does ILER not being an authoritative data source have to do with VA having an API to generate text/PDF exports of ILER data?

> We should not generate a full scale replica of ILER on VA.gov and will focus on granting read access. 

 - Pam Q: What is meant by "full scale replica?" Is this what the Booz Allen ILER team had been proposing, but was either out of scope or technically unfeasible?

> user experience by aiding veterans in their benefits application process by supplying them 

 - Pam Q: How do we envision this user experience? Enabling a printable page that a veteran can consult alongside filling out a form? Having two windows open? Exposing key data points within forms themselves for veterans to select 
      to fill out those forms?

> key data/information from their military record. 

 - Pam Q: Key data/information from veterans' military record: DD214, ILER, or both?

> Veterans seem to be using both to support their benefits application process 

- Pam Q: Is this an assumption or proven out by existing research? Do we verify in desk research?

> memory tool 

- Pam Q: What does this mean? Is this meant as shorthand for describing this finding: [Veterans are not able to memorize all the service history information they'd need to apply for common VA benefits.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/military-information/discovery-and-research/2023-military-info-discovery/findings-summary.md#veterans-are-not-able-to-memorize-all-the-service-history-information-theyd-need-to-apply-for-common-va-benefits)

> The MVP datapoints VA leadership is interested in adding to the VA.gov profile 

- Pam Q: Extracted from DD214, ILER, or both? Something else?

> expanded military information in the VA.gov Profile would be accessible to pre-fill forms on other parts of the VA.gov website 

- Pam Q: How is this different than bullet 1?

> Get veterans read access to as many of the key data elements as possible (currently 6 of 8) 
    - Pam Q: The outcome above lists 8.

**Comment by mtcA6** [comment]
Answers @pamela-drouin, that was hard, I wish it had been in the google doc. 
---
> Section 803(b)(2) requires VA to promulgate a regulation defining the “evidence considered necessary.” 
 - Pam Q: Is there a sense of when VA might promulgate a regulation defining the evidence required to update a record?
- TravC: not yet, no, hence the focus on read only to start

---
> **It is important to note that ILER is not an authoritative data source**, there is an API for generating text/pdf exports of the data but ILER is owned by DoD not the VA. 

 - Pam Q: What does ILER not being an authoritative data source have to do with VA having an API to generate text/PDF exports of ILER data?
- Travis A:  Good call out not super clear what I wanted to get at there. That is from the section of the profile titled “What is ILER?” Where I attempted to give the reader a rundown of what ILER is, I’ve updated the wording. 
see slide titled [“ILER as ADS”]( https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/military_info/2023-enhanced-military-information/stakeholder-artifacts/ILER%20Issue%20Summaryv2%20(1).pptm) for what it means that it isn't authoritative 
---
> We should not generate a full scale replica of ILER on VA.gov and will focus on granting read access. 

 - Pam Q: What is meant by "full scale replica?" Is this what the Booz Allen ILER team had been proposing, but was either out of scope or technically unfeasible?
- Travis A: The Booz Allen ILER stuff is a replica of the ILER data AND it gives a lot of context around the data contained in ILER. In reading through their(Booz Allen) documents, they were tasked with looking into getting veterans access to the ILER data and making that ILER data make sense (see [this]( https://dvagov.sharepoint.com/:w:/r/sites/MCT-BAHILERHCD/Shared%20Documents/General/02-Pre-Discovery/Background/CEDAR%20Intake%20Form_ILER.docx?d=wac73f6853e8a4865b0da25c0dfdae386&csf=1&web=1&e=j64a3Z)). That’s not our task, that's why it's being called `Enhanced Military Information` and not something like `ILER Data Exposure`. 

---

> user experience by aiding veterans in their benefits application process by supplying them 

 - Pam Q: How do we envision this user experience? Enabling a printable page that a veteran can consult alongside filling out a form? Having two windows open? Exposing key data points within forms themselves for veterans to select to fill out those forms?
- Travis A: (jumping up and down excited about these questions) I would love to talk about this in more detail.  In the mural board, that’s what I wanted us to talk through in the [use cases section](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695126310753/6ab8c3953d2eeaa067f666d5a03a754c5ded3d82?wid=0-1695126907898). Would it be helpful if we schedule a call to talk use cases? 
 
You all seemed keen to not approach the use cases until you had more research time. I’m all for working through them as a thought experiment to help generate questions to ask of our stakeholders. 
In my “Things we need to uncover” section on #65973 I had said:
> We know that most people access va.gov using a mobile device, how do we make read access to the 8 key data elements useful to our users

I know now I should have said roughly half of our users, but the spirit of that item is this: I wanted us to think through the process of using the info. As we head into the stakeholder interview I'm very curious to know about the process of things. Your line of questioning is where my brain was going in the original copy on that ticket. If I access the data on mobile and the intention is to apply for benefits how do I even do that!? << with this in mind I already created this ticket:
- #66014
Now the ticket ONLY has the title, I didn't fill in anything else yet because I think this is a good thing to discuss during refinement. 

----
> key data/information from their military record. 

 - Pam Q: Key data/information from veterans' military record: DD214, ILER, or both?
- Travis A: Try not to focus on the documents, we should focus on the data elements themselves and not the documents. Veterans are using the documents because they contain military history information that they need. VBA/VEO analyzed things and said, the 8 data elements are what is needed when applying for benefits, lets expand the information in a user’s profile to encompass these elements to start AND while lets meet our legislative mandate to grant read access to ILER while we work on figuring out the specifics around the update process. See this [section of the outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/military-information/2023-enhanced-military-information/README.md#where-does-this-leave-us), where I tried to make it clear that we start with the documents, but these aren’t all encompassing.  It’s not DD214 nor is it ILER focused and placing too much emphasis on those would be contrary to the task we have, we want to make military information more available to help make applying for benefits easier.

---

> Veterans seem to be using both to support their benefits application process 

- Pam Q: Is this an assumption or proven out by existing research? Do we verify in desk research?
- Travis A: DD214 is proven based on reading Florence’s research, I don’t have a link to an ILER specific finding so if you find one during desk research that would be great to link to. Based on this slide: “[VBA CS Military Exposures Team Analysis]( https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/military_info/2023-enhanced-military-information/stakeholder-artifacts/ILER%20Issue%20Summaryv2%20(1).pptm)” I do suspect their research details something similar

---
> memory tool 

- Pam Q: What does this mean? Is this meant as shorthand for describing this finding: [Veterans are not able to memorize all the service history information they'd need to apply for common VA benefits.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/military-information/discovery-and-research/2023-military-info-discovery/findings-summary.md#veterans-are-not-able-to-memorize-all-the-service-history-information-theyd-need-to-apply-for-common-va-benefits)
- Travis A: Yes, would you prefer I say memory aid? 
---
> The MVP datapoints VA leadership is interested in adding to the VA.gov profile 

- Pam Q: Extracted from DD214, ILER, or both? Something else?
- Travis A: See “[VBA CS Military Exposures Team Analysis](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/military_info/2023-enhanced-military-information/stakeholder-artifacts/ILER%20Issue%20Summaryv2%20(1).pptm)”
----
> expanded military information in the VA.gov Profile would be accessible to pre-fill forms on other parts of the VA.gov website 

- Pam Q: How is this different than bullet 1?
- Travis A: Read access in the profile, to ME, doesn’t imply the data is ready for auto-fill. Maybe that’s incorrect but I do think it’s important to call out auto-fill SEPARATELY so we can announce to the myriad of forms teams that there is new data available to use. 

---
> Get veterans read access to as many of the key data elements as possible (currently 6 of 8) 

- Pam Q: The outcome above lists 8.
- Travis A: You’re right. I’ve added an additional phase, hope that adds clarity/strengthens the internal logic of the document.

**Comment by pamela-drouin** [comment]
@mtcA6 Thanks Travis! I found the markdown formatting difficult to parse in Google docs. I know it's not ideal but it's nice to have a conversation on the ticket as an open record as well. I will think on your responses -- I very much appreciate them.

**Comment by mtcA6** [comment]
I had to restart my computer at the end of writing it all out and need to circle back on this one, there's more I want to say: 

The MVP datapoints VA leadership is interested in adding to the VA.gov profile
Pam Q: Extracted from DD214, ILER, or both? Something else?
Travis A: See “VBA CS Military Exposures Team Analysis”

**Comment by mtcA6** [comment]
@pamela-drouin edited yesterday's comment in two spots. Not sure edits send emails so wanted to let you know, i've added "**edit**" where I made the updates

**Comment by pamela-drouin** [comment]
@mtcA6 

I have read the ILER Issue Summaryv2 deck multiple times and it’s a bit opaque, so I think the questions I have aren’t really answered by that deck – I believe stakeholder interviews and technical discovery will answer them though!

Re: use cases – let’s definitely talk use cases after @andaleliz  and I have completed the review of past research! 

Re: the journey map – as part of desk research, we can look into whether any other teams have mapped how veterans use their military information. There’s the current state (how things are done now) vs a future state (that envisions how using this data might bring value to veterans). I’m not sure how we would map the current state without more research, but a testing hypothetical future state is a possibility. Though storymapping could be an alternative. 

It’s hard for me to let go of not considering where the data elements we need to expose actually come from, whether it’s ILER, DD214, or even MPI (which I didn’t consider until yesterday when Liz mentioned that as a possibility). But I expect technical discovery will answer this question. 

Re: memory tool vs memory aid. In re-reading Florence’s findings summary, it’s really more a combination of these two findings:
- Veterans are not able to memorize all the service history information they'd need to apply for common VA benefits.
- Veterans use service history information such as dates and locations to piece together timelines, which assist with applying for benefits to cover service-related injuries or to piece together the dates and locations of other events.

I think I’d say “We know from our research that veterans are not able to memorize all the service history information they’d need to apply for many benefits, so they use the DD214 to piece together timelines” but that’s just my preference for how to encapsulate the meaning without losing much detail.

Thanks for the back-and-forth, this is fun stuff to dig into!

**Comment by mtcA6** [comment]
@pamela-drouin 
RE: use cases post desk research sounds good💃 

RE: agree, story mapping is probably better and would be helpful in thinking through a LoE

RE: backend, we know most of the data points are available in VA Profile and they're plugging into VADIR for that. Tom pulled up the VADIR data dictionary and some of the most recent edits included the addition of military awards. Looking at this and thinking toward a stakeholder interview, it would make sense to reconfirm if VADIR, or something else, is the definitive data source we should be using. 

RE: the memory tool, ok adjusted

**Comment by andaleliz** [comment]
Thanks to both of you for the thoughtful and helpful conversation, I learned a lot through that! I have never heard of storymapping and had to google it - looks like it could be useful for sure. Page 17 of that discovery research summary PDF might be something we can use as we get started with whatever mapping we do.

I've reviewed all the documents and [created a summary here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/military-information/discovery-and-research/2023-09-enhanced-military-info-mvp/desk-research-summary.md).   I want to share a little about my approach so we're all on the same page:

There's a lot of good info across all these docs, some of which I found challenging to draw meaning from as it relates to our MVP. I attempted a succinct, plain-language summary of our work at the top of my doc:
>In this MVP, our goals are to:
> - Provide Veterans with access to a PDF of their ILER, so they can get this PDF anytime they need it.
> - Make it easier for Veterans to apply for VA benefits by surfacing military service information that is requested in benefit application forms.

And focused my desk research around these two things.  I feel like that left me with a solid list of questions for stakeholder interviews.   Some of the questions may be more for our team than stakeholders, but we can figure that out together.

Pam, please feel free to add to this doc as you see fit. I'm sure you have plenty of other questions I didn't capture, and probably other summary points that stood out to you.  

I would love to have a list that reflects both of our questions by Wednesday (mid-sprint) in hopes that we could complete the stakeholder interviews by the following week.  Does that sound do-able to you @pamela-drouin? If not, let me know what feels more reasonable.  Once we have a goal date set, I'll reach out to Melissa to schedule an initial convo. We may want to talk to the other researchers but I think we should hold off until we talk to Melissa.

**Comment by mtcA6** [comment]
Excited to read this Monday morning. 

Heads up regarding timelines, if the government shutdown occurs, Melissa advised that, unfortunately, she and her team would be furloughed.

**Comment by Samara-Strauss** [comment]
> How best can I help with the stakeholder research plan and convo guide?

Unless you feel it's absolutely necessary to your process, I don't think we need a formal research plan like we usually create. A less-formal list of questions/convo guide for Melissa should work since this is a stakeholder interview and not user research. Also, Melissa is great and will probably talk to us as much as we need, so it's OK if we can't fit everything into a single call.

**Comment by mtcA6** [comment]
I think the only thing that stood out to me was this question:

>In the research summary, we saw that 12 of 15 Veterans interviewed stated they'd expect to find this information with their health records. How was it decided this should go in the VA.gov profile, which is counterintuitive based on the research, rather than on My HealtheVet, or MHV on VA.gov?

Can you expound upon what 'this information" means? 

I suspect "this information"  in the study was focused on ILER data which is veterans exposure data. The study findings make sense for a project/initiative providing users with context around their ILER data. However, the ask we've received is to expose military information of which ILER is one component, I want us to be careful about leaning too heavily on that finding.

**Comment by andaleliz** [comment]
@mtcA6 "this information" is referenced earlier in the doc, where it clarifies that it is exposure information as you suspected. Hope that helps!

**Comment by andaleliz** [comment]
>Unless you feel it's absolutely necessary to your process, I don't think we need a formal research plan like we usually create. A less-formal list of questions/convo guide for Melissa should work since this is a stakeholder interview and not user research. Also, Melissa is great and will probably talk to us as much as we need, so it's OK if we can't fit everything into a single call.

@Samara-Strauss that's great to know Melissa will probably talk to us as much as we need! That definitely takes some of the pressure off. I had already created a research plan, so we'll go ahead and use it. I do think it's good for thoroughness and for Future Us when we go back in a year and try to remember what we did.  I'll share links to that + the convo guide later today for a once over before I reach out to Melissa to schedule.

**Comment by Samara-Strauss** [comment]
@mtcA6 just want to confirm that you are ok with us conducting a stakeholder interview (or interviews) with Melissa while you're out. We can record them if you think you might go back and listen. If possible, I don't want to have to wait another couple weeks to talk to her.

**Comment by mtcA6** [comment]
No need to hold off on my account! Go ahead had conduct the interview(s), recording would be great (but if you forget don't sweat it!).

**Comment by andaleliz** [comment]
@Samara-Strauss or @mtcA6 do either of you have insight into this question?

>Based on the documents we reviewed, it looks like the BAH team was handling this as recently as September 2023. Is this getting transferred to us simply because their contract ended, or is there more to the story?

**Comment by Samara-Strauss** [comment]
@andaleliz I am not sure of any details with the BAH contract, but it was always likely that VA.gov would be responsible for building a solution. I'm not sure why this didn't start with us a few months ago, but I'm glad it's here now.
