### ISSUE TITLE
Wrap up KMS Rotation Job and Local Testing

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#66360]
## Issue Description

Take the result of Holden's previous work and that of discussions between Eric, Lindsey and myself, and iterate to prepare the Sidekiq worker classes for deployment.

## Tasks

- [x] Deep dive into [Holden's previous work](https://github.com/department-of-veterans-affairs/vets-api/pull/11117) for understanding of KMS, kms_encrypt gem, Lockbox, Sidekiq::Batch, etc
- [x] Discuss strategies with Holden, Eric, and Lindsey
- [x] Create new PRs with the result of learnings
- [x] Test Locally

## Acceptance Criteria

- [ ] PR has been merged so that testing can begin in deployed environments.
