### ISSUE TITLE
Review Devops Examples and Research

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#66373]
# Description
Get familiar with some of the key DevOps tools relevant to the work that we're currently doing.

---

# Tasks
_Tasks are listed in order of priority_

- [x] Research and suggest courses on - GitHub Actions (GHA) - Choose ONE:
   - [x] 1. GitHub Actions: Continuous Integration, Deployment & Automation (Udemy):
Start with this course if you're new to GitHub Actions or need a comprehensive understanding of how it works and how to use it effectively. 
   - [x] 2. Introduction to DevOps on AWS with GitHub Actions (Pluralsight):
If you're primarily working in an AWS environment and want to integrate GitHub Actions into your AWS-based projects, consider this course.
- [x] Research and suggest courses on - Kubernetes (K8s)
   - [x] 3. *Kubernetes with HELM: Kubernetes for Absolute Beginners CKA*: -Certified Kubernetes Administrator (CKA) | GKE & CKA Deep Dive | Production grade K8s with HELM from Scratch
   - [ ] 4. Learn DevOps: Advanced Kubernetes Usage: -Covering Authentication, Authorization, Logging, Helm, Deploying with Spinnaker, Prometheus, Scheduling, and more
- [x] Research and suggest courses on - Terraform
   - [ ] 5. Terraform - Getting Started (Pluralsight): - If you need to work with infrastructure as code using Terraform, consider taking this course. It's particularly relevant if you're dealing with AL2 infrastructure.
- [ ] Research and suggest courses on - Other
   - [ ] 6. GitHub Learning Lab (GitHub): Use this resource as needed to practice and reinforce your GitHub Actions and Git skills. It's a flexible, hands-on platform.

- [ ] Review the following DevOps Examples/Resources:
   - [ ] GHA Workflows
       - [ ] This workflow is the CI pipeline for the front-end of the va.gov platform: https://github.com/department-of-veterans-affairs/vets-website/blob/main/.github/workflows/continuous-integration.yml 
       - [ ] This workflow is the CI pipeline for the static content build for va.gov: https://github.com/department-of-veterans-affairs/content-build/blob/main/.github/workflows/continuous-integration.yml
       - [ ] The collection of "How do I" articles here are very helpful for various DevOps tasks.
       - [ ] Get familiar with _[the list of resources as this page:](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593968/How+do+I...)_ 

**NOTE** - Courses/training work beyond a 32-40 hour timebox will be moved to the backlog and prioritized for future sprints

# Acceptance Criteria
- [ ] 32-40 hours have been invested in learning the courses listed above in order of priority
- [ ] Platform Devops examples have been reviewed
- [ ] Additional notes and questions have been reviewed with other Devops engineers

**Comment by pjhill** [comment]
Here are some GitHub Actions workflows to review --
This workflow is the CI pipeline for the front-end of the va.gov platform: https://github.com/department-of-veterans-affairs/vets-website/blob/main/.github/workflows/continuous-integration.yml
This workflow is the CI pipeline for the static content build for va.gov: https://github.com/department-of-veterans-affairs/content-build/blob/main/.github/workflows/continuous-integration.yml

**Comment by pjhill** [comment]
With regard to potential future support rotation work these are good resources --
* The collection of "How do I" articles [here ](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593968/How+do+I...)are very helpful for various DevOps tasks.
