### ISSUE TITLE
Expand Terraform w/ RDS creation and routing

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#66385]
### Description:
Expand the Terraform configurations to support RDS creation and routing for preview environments.

### Tasks:
- [x] Update Terraform scripts to handle RDS creation.
- [x] Update Terraform scripts to handle routing for the newly created RDS.

### Acceptance Criteria:
- [x] Triggering the 'create' environment workflow will run the RDS terraform, creating a new RDS instance.
- [x] Triggering the 'destroy' environment workflow will run the RDS terraform destroy, removing the RDS instance and the associated terraform state file.
