### ISSUE TITLE
Extend Terraform configuration to support helm installation

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#66387]
### Description:
Extend the Terraform configurations for preview environments to support Helm installations.

### Tasks:
- [x] Modify the "create" workflow to include a Helm installation of a specific version of the vets-api Helm chart.
- [x] Modify the "destroy" workflow to remove the Helm installation.

### Acceptance Criteria:
- [x] Triggering the "create" workflow results in a successful Helm installation.
- [x] Triggering the "destroy" workflow successfully removes the Helm installation.
- [x] Namespaces are properly created and destroyed during this process.
