### ISSUE TITLE
Research backlog

### ISSUE THREAD

**Issue by djones2113** [department-of-veterans-affairs/va.gov-team#66381]
### Background Context
The goal of creating the research backlog is to compile all questions that have come out of reviewing project materials as well as initial discussions with the shaping team and other project stakeholders. We will use this document to generate next steps for R&D.

[Link to the backlog here](https://docs.google.com/spreadsheets/d/1xLprjSMvXaGm9dXpnVANvbjiF6gQqaYi7rXMh8SMIEM/edit#gid=997340249).

### Tasks
- [x] Compile all questions from product and R&D in one place
- [x] Reconcile any duplicates
- [x] Add tags to questions (i.e. priority, question type, notes, est effort)
