### ISSUE TITLE
Create manual trigger & display mechanism

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#66383]
### Description:
Implement a mechanism to manually trigger preview environments and display the current set of environments.

### Tasks:
- [x] Set up DynamoDB with capabilities to upgrade from GitHub workflow.
- [x] Develop a simple UI that can trigger "add environment" and "delete environment" calls via GitHub actions.

### Acceptance Criteria:
- [x] The UI displays the current environments as listed in the DynamoDB table.
- [x] The UI provides the capability to add a new environment and delete an existing one from the list.
