### ISSUE TITLE
Modify vets-api repo to publish containers & helm charts

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#66386]
### Description:
Modify the vets-api repository to support publishing containers and Helm charts based on specific servers.

### Tasks:
- [x] Develop a method to create a HELM CHART for each build. Consider creating a separate ECR location for the container.
- [x] Establish a Helm chart repository location.
- [x] Implement functionality to publish containers and Helm charts with every code PUSH.

### Acceptance Criteria:
- [x] A HELM CHART is created for each build.
- [x] Containers and Helm charts are successfully published with every code PUSH.
