### ISSUE TITLE
[bug] NOD | Save in Progress data is not deleted after submission

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#66407]
## Value Statement
**_As a_** Veteran
**_I want to_** be sure I submitted my Notice of Disagreement form
**_So that_** I do not resubmit the same form

## Background Context

When doing NOD v2 release validation testing. We ran into an error on staging where save-in-progress data was not being deleted after submission. This could cause issues with Veterans since it'll lead them to believe their form wasn't properly submitted.

### Replicate the issue
- On staging, log into user 236 (or any decision reviews user such as 228 or 223
- Go through Board Appeal form and submit
- Return to Board Appeal form
- Save-in-progress box shows up with the last saved time being the time of submission
- Go through form, and see all data's been saved, even though the user starts at the beginning of the form again

## Acceptance Criteria
- [ ] When in staging, after a form is submitted the SIP data does not appear to the user
- [ ] When in production, after a form is submitted the SIP data does not appear to the user
- [ ] Confirm by sharing mock data for testing in staging

## Tasks
- [ ] Attempt a local submission and confirm that the call to remove the in-progress form is being made
- [ ] If yes, look for frontend caching or in-memory database problems that could cause the issue
- [ ] If related to Redis, add code to clear out in-progress form data
- [ ] If no, add call to remove in-progress form from the database upon submission
- [ ] Find reason for save-in-progress data not deleting after submission
- [ ] Fix error 

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by saderagsdale** [comment]
@anniebtran and @eileen-coforma will discuss before estimating

**Comment by anniebtran** [comment]
The overall issue seems to be some lost functionality when migrating from the NoticeOfDisagreementsController V0 => V1. There's a `.submit_nod` method on the `AppealSubmission` model that was [used in V0](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/notice_of_disagreements_controller.rb#L6) that [makes the call to destroy the InProgressForm when it's called](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/appeal_submission.rb#L30) but in the new V1 controller, we just [create the `AppealSubmission` directly](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v1/notice_of_disagreements_controller.rb#L19-L22) (without using the special `.submit_nod` method or any InProgressForm cleanup)

The other form controllers ([HLR](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v1/higher_level_reviews_controller.rb#L19-L24) and [SC](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v1/supplemental_claims_controller.rb#L100-L112)) use a transaction to create the AppealSubmission and destroy the InProgressForm, and that's what I would've recommended here anyway, so seems like the pattern has already been set, we just need to apply it to NOD 😄 

Doesn't look like there are any controller specs written around this for any of the forms, so if we're cool with making the change without adding tests, I'd estimate this as a 1. If we're trying to add more test coverage for all of them, probably at least a 2.

**Comment by eileen-coforma** [comment]
Validated. Works for Charde user 236. SIP data no longer shows after submission in Board Appeal introduction or on My VA.
