### ISSUE TITLE
FE | Profile | Hub | Finalize prototype

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#66403]
## Background
We completed a lot of work for the Hub here in #64160 creating the prototype in staging. There are some final revisions/tweaks that we need to work through 

## Tasks
- [ ] Finalize prototype (adam please add the tasks that you need)
- [ ]  let PM and PO know to check things out when finished 

## Acceptance Criteria
- [ ] Ready for usability testing

**Comment by adamwhitlock1** [comment]
This is ready to validate. 
The main thing to validate would be styling on mobile (just making sure that everything looks good)
The other item that we would validate in this ticket would be that the bad address indicator alert should only display on the Hub and not show on the Personal information page.

I couldn't track down a staging user that has the Bad address alert showing, so I will get tom to trigger one of the users and update this ticket tomorrow with the user we can test this with.

**Comment by adamwhitlock1** [comment]
I have validated this in staging with staging user 226, that the BAI alert shows up on the Hub, but is not displayed on the personal information page anymore.

@Dottifacilities If you can check on that, then we can close this out.

**Comment by Dottifacilities** [comment]
Validated!
