### ISSUE TITLE
Creation of Custom Surveys for VFS Teams

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#66409]
## Product Outline
[Medallia User Surveys](https://vfs.atlassian.net/wiki/spaces/Contact/pages/1794015358/Medallia+Product+Outline)
[How to Request a Survey](https://vfs.atlassian.net/wiki/spaces/Contact/pages/1793556578/How+to+request+a+Medallia+survey)

## Hypothesis or Bet

- If we provide user surveys for VA.gov pages, then users of VA.gov will submit feedback which we can use to better understand user satisfaction.

## OKR
Objective: Streamline customized survey creation with goal of implementing surveys within 6 weeks of initial request

- [x] Implement Ask VA Custom Survey on VA.gov and current Ask VA Portal
- [x] Implement FSR Custom Survey for VA.gov Debt Resolution Team
- [ ] Document process for custom survey creation with goal of completion within 3 sprints

### What must be true in order for you to consider this epic complete? 
- [x] Survey Intake form finalized
- [ ] Intake form available for use
- [ ] Intake form tested
- [ ] Intake form operational and in use 
- [ ] Receive request for custom survey from VFS team 
- [x] Launch custom survey 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

## Acceptance Criteria

- [ ] **Scenario 1: Implement Ask Custom Survey on VA.gov and current Ask VA Portal**
  - [ ] The issue is labeled with Team (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
  - [ ] The issue is labeled with Practice Area (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

- [ ] **Scenario 2: Implement FSR Custom Survey for VA.gov Debt Resolution Team**
  - [ ] The issue is labeled with Team (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
  - [ ] The issue is labeled with Practice Area (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

- [ ] **Scenario 3: Document process for custom survey creation with goal of completion within 3 sprints**
  - [ ] The issue is labeled with Team (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
  - [ ] The issue is labeled with Practice Area (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by clantosswett** [comment]
Work completed. Closing.
