### ISSUE TITLE
[Frontend] Address Page - Modify Schema for International Addresses

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#6640]
## User Story or Problem Statement
As a Veteran who lives overseas I need to have medical supplies shipped to my overseas address whether it is permanent or temporary 

## Goal
_Modify schema to accommodate international ship to addresses passed through API and when a Veteran adds and/or modifies address in forms. 

## Tasks
- [ ] _Modify address schema

## Acceptance Criteria
- [ ] _International addresses can be both displayed and added on address forms page
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
