### ISSUE TITLE
[UX][Content] Create Content for 45-minute Error Message when Veteran Needs to Review their Insurance

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#66404]
## Description
[Slack thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1695763109688929?thread_ts=1695738433.612699&cid=C02G6AB3ZRS)

When a Veteran texts "check in" to 53079 but needs to review their insurance information, we send the following message to them to let them know that they will need to check in with a staff member. However, when we push a 45-minute check-in link to them, we need different content that fits this scenario, otherwise receiving the message below would feel like unwarranted, out of the blue, text from VA. 

> const ERROR_INSURANCE_VALIDATION = 'We\'re sorry. We can\'t check you in online. We need to review your health insurance information with you. Ask a staff member for help.';

We want to make it clear to Rob this is a new message, not a replacement for the above message. 

## Tasks
- [x] Create the content for this scenario
- [x] Add into https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/0D0F05D2-2122-4599-9378-E03EEE32DB88/canvas
- [x] Run content by Laura
- [x] Run content by POs (Lori, Kay, Kristen, Stephen)
- [ ] Forward the content to @robertdurkin 
    - NOTE: whose work is it to implement this message? (I think Rob needs to know if we/CHIP need any appt variables, but then we create the template via CHIP.)

## Acceptance Criteria
- [ ] Content has been created & reviewed
- [ ] Content has been forwarded to Rob Durkin

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/66404?planning-poker) with Zenhub @cgednalske @kellysmith1008 @ytsaoca @zach-park

**Comment by kellysmith1008** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanpqIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3ffa5fd6b29e46c45b815e8cd55eac8b0d608029/image.png)
[Slack thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1695738433612699)

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 I wouldn't prioritize this work for this current sprint, BUT if you and the rest of the UX team have finished all of our current sprint goals, this would be a ticket to potential start early. We don't have to, and I'm not encouraging extra work/time... but, just wanted to throw that out there in case you find yourself finished with your work for this sprint. That was probably a longer explanation than it needed to be :)

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 Hahahah - this is the best comment I've read all week!! There's a good chance I will be able to get to this during this sprint, but I appreciate the candor in that it doesn't have to be completed this sprint. Thanks!!

**Comment by kellysmith1008** [comment]
Suggestion from Rob Durkin in slack - I can work with this - just putting here so I remember 
Sample Needs insurance Verification Message (will replace with official template when available):
When you arrive at the VA health facility for your appointment on SEP 28 at 14:00, please ask a staff member for help checking in.

**Comment by kellysmith1008** [comment]
Also include a snippet about them not being able to check in online as well because they need to update insurance information

**Comment by kellysmith1008** [comment]
@loripusey, @klawyer @kristenmcconnell  The content is ready for your approval, and we're waiting on approval from Laura W. Once I get both, I'll forward the content to Rob Durkin.

Content: 
- It’s almost time for your VA appointment on {{Date}} at {{Time}}. We need to review your insurance with you, so you can’t check in online. 
When you arrive at the facility, a staff member at the clinic can help update your insurance and check you in. 

[Mockup](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/YZn4rgM)

**Comment by loripusey** [comment]
LGTM

**Comment by benbrasso-agile6** [comment]
LGTM

**Comment by benbrasso-agile6** [comment]
Me too, me too. It's all very thoughtful and intentional.

**Comment by kristenmcconnell** [comment]
Agree. It is very thoughtful.

**Comment by benbrasso-agile6** [comment]
Was looking through our tickets under validate, @kellysmith1008 @loripusey are we ready to close this ticket? I'm not sure if this is Rob's work or our/CHIP work. @brianseek https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/YZn4rgM

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 I was waiting for a response from Laura around "a staff member at the clinic" vs "a staff member in the clinic" but since she wasn't strongly opposed to us using both facility and clinic, I think we're ok to close it with the mockup we have now, which includes "a staff member in the clinic" wording.

**Comment by loripusey** [comment]
@robertdurkin Rob, we need to implement this error message. I'm assuming this is work you will need to do. Is there anything else you need from our end?
cc: @benbrasso-agile6 @kellysmith1008

**Comment by loripusey** [comment]
closing this ticket as our work is complete

**Comment by robertdurkin** [comment]
I've updated the 'need insurance check' message template for check-in reminders in VEText Dev/Staging to @kellysmith1008 's content.

The only changes I made are adding a new line after the first sentence, so that the message is composed of three lines, and substituting the 'fancy' apostrophes (Unicode U+2019)  with regular single quotes (Unicode U+0027):

```
It's almost time for your VA appointment on %APPOINTMENT_DATE% at %APPOINTMENT_TIME%. 

We need to review your insurance with you, so you can't check in online.

When you arrive at the facility, a staff member in the clinic can help update your insurance and check you in.
```

The additional new line may help readability on a mobile device, as multiple sentences on a single line can make it more difficult to read on a small screen.

The fancy apostrophes would make this message UCS-2 encoded (i.e. a MMS message) which costs more than an SMS (GMS-7 encoded) message.

**Comment by loripusey** [comment]
Thanks for the quick response @robertdurkin !!

**Comment by benbrasso-agile6** [comment]
And helpful explanation for those changes

**Comment by benbrasso-agile6** [comment]
Added into sketch production file, figured we're close enough now https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/p/0213EBFE-75F9-4C0E-805B-5E77F30A8F04/canvas
