### ISSUE TITLE
Remove Google Sheet Plugin from Analytics page

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#66411]
## Info
On this page: https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/getting-started-with-platform-analytics-insights

There is a Google Sheets plug-in widget that previews the link to the Google Sheet listed.

The problem is that VA stakeholders are restricted form Google tools and the preview image breaks on their end. See comment below for example.

## Tasks

- [x] Document the URL the google slide widget is pointing to
- [x] Remove the widget
- [x] Replace the widget with a link that has the title of the slide and points to the Google Slide, instead; **Be sure to add a disclaimer that says something like: (Limited access if using the VA network)**
- [x] Prepare the page for deployment - If any launch blocking issues, resolve with Michelle Dooley

## Acceptance Criteria

- [x] The [Getting started with Platform Analytics & Insights](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/getting-started-with-platform-analytics-insights) page on the Platform website will have the google slide widget replaced with a simple hyperlink that points to the same URL.
