### ISSUE TITLE
(Brian) Demo/shadow deployment for Cheryl

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#66416]
## Tasks
- [x] Coordinate with Cheryl your demo/shadow day
- [x] Account for additional time to provide her with context

## Acceptance Criteria
- [x] Cheryl will have shadowed how to do deploy

**Comment by BSmolensky** [comment]
Cherly shadowed me today during deployment. This ticket can be closed.

**Comment by jknipes** [comment]
Tasks completed and Acceptance Criteria met, moving to _Done_
