### ISSUE TITLE
Update Custom Survey Request Issue Template

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#66419]
## Issue Description
Currently, our [custom survey request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=ATMiddleton&labels=VSP-contact-center%2Ccc-survey-request&projects=&template=request-custom-survey.yml&title=Request+Custom+Survey) has some incorrect information on it. This should be updated so that the information we ask for is clear and accurate.  
---
## Tasks
- [x] Remove PRA Approval question from the template
- [x] Remove bullet two under the "Follow Up and Timeline" section

## Acceptance Criteria
- [x] _Updated template that allows Users to request multiple data sets from Medallia 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
@newworld2616 @UXCamG @ATMiddleton will complete discovery this Sprint.

**Comment by ATMiddleton** [comment]
Discovery meeting scheduled 10/9/2023

**Comment by ATMiddleton** [comment]
Form updated 10/10/23
All tasks completed.
