### ISSUE TITLE
PRA Approval for FSR Custom Survey

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#66426]
[FSR Intercept Survey Questions Update.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3BiQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a4a7e5aae8a7d3f6e2eedd74d4de6ad2dfd9ddfa/FSR%20Intercept%20Survey%20Questions%20Update.xlsx)
[FSR Urls and Pages 10202023.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3RiQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--43acdf2707a1157dbec9d176711c862e7532b17b/FSR%20Urls%20and%20Pages%2010202023.xlsx)

[FSR Intercept Survey Questions Update (2).xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWk5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e723944fc4d74197c837141557c52ed0569b6cfd/FSR%20Intercept%20Survey%20Questions%20Update%20%282%29.xlsx)

[FSR Intercept Survey Questions Update (3).xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMi9VQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1a689a769489e1365f61024fb0ff3618bba1631d/FSR%20Intercept%20Survey%20Questions%20Update%20%283%29.xlsx)

## Issue Description
Debt Portal Intercept Survey

- Desired launch date: Before Thanksgiving 2023
- Proposed use case: 6 question survey that would be shown to a subset of users once that have completed and submitted the VA Form 5655 - Financial Status Report. This form is required if a Veteran wants to request a waiver for their debt.
- Proposed Questions: See attached FSR Intercept Survey Questions

---
## Tasks
- [x] Send PRA approval request to VEO 
- [x] Receive expedited PRA approval from VEO

## Acceptance Criteria
- [x] A PRA approved survey
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
Evan's team postponed meeting in preparation of possible Government shutdown.  

I've sent Evan my availability for the week of 10/9 - awaiting response.  Will meet to level set.

**Comment by ATMiddleton** [comment]
Sent another email to Evan with availability for next week.  Awaiting response.

**Comment by ATMiddleton** [comment]
Awaiting invitation from Evan.  I've included @denisecoveyduc @UXCamG @aubreyarcangel @newworld2616  on the follow up email in anticipation of the meeting.

**Comment by ATMiddleton** [comment]
Attended the VA.gov Debt Portal and Ask VA meeting 
Takeaways - updated link to intercept survey questions (above) 
Obtain from Denise which urls the survey should deploy
Confirmed standard targeting rules with Sarkis 

Next Steps - forward questions to Brian and team for OMB approval - Done 10/18/23

Sarkis will inform when present in staging environment for testing

**Comment by ATMiddleton** [comment]
[FSR Intercept Survey Questions Update.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2hiQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dd9af1f8ca2d46256ba30eda91a0aab1ee6a7fb7/FSR%20Intercept%20Survey%20Questions%20Update.xlsx)
[FSR Urls and Pages 10202023.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2xiQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e8e5aa8b2dd1255f8b7852960fa3bbbb017aa1fb/FSR%20Urls%20and%20Pages%2010202023.xlsx)

Forwarded email to distro list including Urls and questions.  Awaiting OMB approval.

**Comment by ATMiddleton** [comment]
Inquired about OMB approval status.  Awaiting feedback.

**Comment by ATMiddleton** [comment]
Continuation meeting 10/30/23

**Comment by ATMiddleton** [comment]
Awaiting @denisecoveyduc to submit updated questions.

**Comment by ATMiddleton** [comment]
@denisecoveyduc will forward updated question and send to Brian for OMB approval process.

**Comment by ATMiddleton** [comment]
Awaiting feedback from Brian...

Coveyduc, Denise V.
Wed, Nov 8, 12:51 PM (19 hours ago)
to Brian, Sarkis, me, aubrey@thesocompany.com, Becky, Camille

Hi Brian, 
Thanks for your patience regarding the questions for the debt portal survey for the FSR.  I took another look and have narrowed it down to these 4 questions. I'd love to get your thoughts on them and we can refine again if needed. 
Thanks, 
Denise

 

FSR Survey Questions

Veteran Answers
1. Please tell us whether you agree or disagree with the following statement: 
I was able to easily complete this form online.

Strongly Agree
Agree
Neutral/Unsure
Disagree
Strongly Disagree 

2. Did you find any section of the form confusing or unclear? Please select all that apply
Veteran information
Income
Assets
Expenses
Relief Options
Bankruptcy History
Final Review

3. What changes, if any, would you like to see in the form to make it more user-friendly and easier?

*Text Area*

4. Would you recommend completing this form online to another Veteran?

Strongly Agree
Agree
Neutral/Unsure
Disagree
Strongly Disagree

**Comment by ATMiddleton** [comment]
@ATMiddleton updated FSR questions per Slack thread with @denisecoveyduc  and forwarded updated questions to Brian.Brown3@va.gov to forward progress.

**Comment by starlow00** [comment]
Awaiting information from shareholder.

**Comment by ATMiddleton** [comment]
@denisecoveyduc will provide updated list of final URLs today.  
Denise will also be grated access to the staging area
@aubreyarcangel will review styling

**Comment by denisecoveyduc** [comment]
@ATMiddleton  FYI  I just emailed the list of URLs to Yassine and team to update what is in staging. Please let me know if you need anything else. The debt team is excited to see this in production soon. @aubreyarcangel if you need any help reviewing in staging please let me know the FSR is quite a lengthy experience and the dev team has a few tricks to navigate through it.

**Comment by ATMiddleton** [comment]
Staging environment active and survey is being tested.

**Comment by ATMiddleton** [comment]
We have updated our targeted links to encompass the links below, however we were not able to access user #81 to test it in VA’s staging environment. At this point we have everything we need to proceed with the launch; however, we will feel more comfortable if we test the links in the staging environment.  

@denisecoveyduc has schedule a meeting 12/15 to review and confirm launch date

**Comment by ATMiddleton** [comment]
The decision was made to make the survey a link that will appear at the conclusion of the survey.  The survey will launch post code freeze 1/4/24.

**Comment by ATMiddleton** [comment]
Updated decision to deploy the survey as intercept.  Survey was updated in staging to reflect the "Give Feedback" button - only load/show on manage-va-debt/request-debt-help-form-5655/confirmation.  

Pending launch date.

**Comment by ATMiddleton** [comment]
Approval to update staging environment has been received.  Yassine at Medallia is completing the update and testing will begin.  Estimated date of deployment is Friday, January 12th.

**Comment by ATMiddleton** [comment]
Update on Debt portal survey: Yassine has republished the code survey. I tested it yesterday evening and found a bug, which triggered the survey on page load. I let Andrew Rodiek (engineer w/ dept portal team) and he’s currently working on a fix.

**Comment by ATMiddleton** [comment]
Bug is fixed and the survey be migrated to production - estimated time line is 1/17

**Comment by ATMiddleton** [comment]
Debt portal survey is in production and functioning as expected
