### ISSUE TITLE
Ask VA Intercept and Feedback Survey PRA Approval 

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#66428]
## Issue Description

Ask VA Intercept and Feedback Survey PRA Approval 

- Desired launch date: January 2024
- Proposed use case: Ask VA is currently a customer support inquiry tool that is not built on the VA.gov modernized platform. An team within the Office of the CTO is migrating the functionality over to the VA.gov platform in the coming months and would like to gather some baseline customer feedback numbers that can then be compared to the numbers for the new experience. In both cases, these will be small, intercept surveys that use the same set of questions.
- Proposed questions: See attached Ask VA Medallia Surveys

[Ask VA Medallia surveys.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0hoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0dd9434b9ec9f9281fd4b01f9949e133e489a248/Ask%20VA%20Medallia%20surveys.docx)

---
## Tasks
- [x] Send PRA approval request to VEO 
- [x] Obtain expedited PRA approval from VEO
- [ ] Launch PRA approved survey
---

## Acceptance Criteria
- [x] **Scenario 1: Send PRA approval request to VEO**
  - [ ] Verify that the PRA approval request is sent to VEO.
  - [ ] Ensure that the request includes all necessary information and attachments.
  - [ ] Confirm that the request is successfully delivered to VEO.

- [x] **Scenario 2: Obtain expedited PRA approval from VEO**
  - [ ] Validate that the PRA approval is obtained from VEO.
  - [ ] Verify that the approval is expedited as requested.
  - [ ] Ensure that the approval includes any necessary conditions or requirements.

- [x] **Scenario 3: Launch PRA approved survey**
  - [ ] Confirm that the PRA approved survey is launched.
  - [ ] Verify that the survey is accessible to users.
  - [ ] Ensure that the survey questions match the attached Ask VA Medallia Surveys document.

- [ ] **Scenario 4: Configure issue**
  - [ ] Verify that the issue is attached to a milestone.
  - [ ] Ensure that the issue is attached to an epic.
  - [ ] Confirm that the issue is labeled with the appropriate team(s).
  - [ ] Verify that the issue is labeled with the appropriate practice area(s).
  - [ ] Ensure that the issue is labeled with the appropriate type(s).

**Comment by ATMiddleton** [comment]
Included in 66426 - both survey projects will be addressed together.

**Comment by beckyphung** [comment]
Here is an updated link to our intercept survey questions and feedback button survey questions that need PRA approval from OMB - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ask-va/products/medallia-feedback-surveys.md#intercept-survey-questions

**Comment by ATMiddleton** [comment]
Sent questions to Brian Brown for OMB approval.

**Comment by beckyphung** [comment]
Per Brian via email, these questions actually didn't need approval and are good to go.

**Comment by starlow00** [comment]
(cc @ATMiddleton) See comment above.

**Comment by ATMiddleton** [comment]
Awaiting launch of Medallia 2.0

**Comment by clantosswett** [comment]
It seems like this issue can be closed since this was specifically about PRA approval for the survey. I'm going to go ahead and close this.
