### ISSUE TITLE
Profile Event Dataset Update - Internal

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#66421]
## Issue Description
Requirements for [Profile dashboard update](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/63633) have changed a bit. Instead of limiting Retrieval events to specific profile pages we are going to track them for all va.gov/profile/ pages. 

---
## Tasks
- [ ] Update V2 tab so the Retrieval event urls stop at profile/ (not profile/contact-information for example).  Including those with postlogin=true, next=loginmodal) - Christine
- [ ] Upload updated table to BQ & re-run for previous 2 weeks - Phil
- [ ] Upload to Domo - Phil
- [ ] QA dataset - Christine

## Acceptance Criteria
- [ ] _Profile api counts are more inclusive of all profile/ pages and better match their [GA dashboard](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/DRqBrmiyTD6l8L75rei0fw/a50123418w177519031p176188361/)

**Comment by michelle-dooley** [comment]
Sprint update: This work will continue into next sprint.

**Comment by michelle-dooley** [comment]
https://docs.google.com/spreadsheets/d/116yFranccIgZ0-SscSKL2za0m943PZaWMgbnaf3hXuU/edit#gid=0
