### ISSUE TITLE
MyVA API dataset update - Internal

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#66439]
## Issue Description

With the migration from EVSS to Lighthouse we need to pull in new API Request - GET events per this [MyVA request ticket](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/65061).  

---
## Tasks
- [x] Update BQ vw-myva_api_requests_v2 dataset to include new Benefit event actions [GA report](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/DRqBrmiyTD6l8L75rei0fw/a50123418w177519031p176188361/_u.date00=20230815&_u.date01=20230821/) - Phil

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBamppIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7ed2d2859ab883c348e0eb66c8fde19757683953/image.png)

Regex used in their GA report 'API Request.*EVSS claims|API Request.*Lighthouse claims'

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2ppIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--058e7483b46830f1424c113947f0d95492f41c5e/image.png)

- [x] new events are added to dataset and uploaded to Domo - Phil
- [x] QA - Christine

## Acceptance Criteria
- [x] new events added and Domo is aligning with GA
---

**Comment by michelle-dooley** [comment]
@dorseypa1 these new event actions fall under the api_type claims for your query.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaDdyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--62a509aab72b842fde90357ba9d984a05abe592b/image.png)

**Comment by michelle-dooley** [comment]
@dorseypa1 these new event actions fall under the api_type claims for your query.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaDdyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--62a509aab72b842fde90357ba9d984a05abe592b/image.png)

**Comment by dorseypa1** [comment]
> @dorseypa1 these new event actions fall under the api_type claims for your query. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaDdyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--62a509aab72b842fde90357ba9d984a05abe592b/image.png)

Looks like I don't have permission to view the Private Zenhub Image

**Comment by dorseypa1** [comment]
The additional event_actions have been added to the BQ VIEW and tested in BQ.  All 4 events are returned from the code in the image below.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/117392065/aaf9ba27-2542-4a78-b944-da54ec0c863c)

**Comment by dorseypa1** [comment]
@ChristineYoungZA , on Monday you can begin testing the Domo cards and dashboard for this request (the scheduled weekend refresh will ensure the data is available in Domo).

**Comment by ChristineYoungZA** [comment]
Thanks @dorseypa1. I will start work on Monday and follow up if I have any questions.

**Comment by ChristineYoungZA** [comment]
The QA for the MyAPI claims is linked below. The numbers match exactly Domo vs. GA. https://docs.google.com/spreadsheets/d/1u_z3goY-DmPotSrD0DRlr2YE1R2lyxdIblnxRs_Ht0U/edit#gid=0

**Comment by michelle-dooley** [comment]
@ChristineYoungZA - numbers look good but can we do something to the formatting so the label readyhs "Lighthouse Claims" and "EVSS Claims" instead of the link with backslashes. Similar to what we do for VA Notify landing pages 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcHYrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6cda0ab070091212d6602ef9a3cae6a9a67e5890/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcDcrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--27a5fcbf22442cda987bd059ee9e51b1f6713e55/image.png)
