### ISSUE TITLE
 VAOS-R Redirects & MHV Switchover

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#6644]
## Need
Once VAOS is rolled out 100% to VA.gov without critical bugs or performance concerns, we will then need to start redirecting various access points to the new VAOS-R tool on VA.gov. 

## Goal
- [ ] Redirect users from key unauth access points to new VAOS-R 
- [ ] Utilize the work completed by the SSOe team to enable bidirectional authentication from MHV to VAOS
- [ ] Once this is enabled, we can start the process of sunsetting legacy VAOS (will need action plan created to support this)

## (Optional) Additional Implementation Notes / Questions
- [x] Develop proposed plan for redirects & confirm plan with stakeholders
- [ ] Confirm unauth access points:
    - [x] Launch Pad
    - [x] Mobile Store (https://www.mobile.va.gov/)
    - [x] eBenefits ? -- need to confirm from where?
- [ ] Traffic from MHV to legacy VAOS for past 6 months

> Year | Month | Distinct Users to VAOS from MHV
> 2019 | Oct |     52,750                          
> 2019 | Nov |    60,996                   
> 2019 | Dec |    65,228
> 2020 | Jan |    84,036 
> 2020 | Feb |    71,731
> 2020 | Mar |   75,156

## Stories to create:
- [ ] Redirect unauth access points
- [ ] Redirect auth access points (specifically MHV but also maybe eBenefits?)

**Comment by lalexanderson-dsva** [comment]
Added @chrisj-usds  to this issue b/c he may still have the presentation we made in 2017 highlighting all the places where we redirected users to VAOS 3 years ago. My computer was wiped and files went with it unfortunately. 

-  Ebenefits redirects from the home page, column 3, Manage Care. 
- Other places to redirect - from MHV's logged out article on scheduling appointments. 
- ALL of the VAMC sites.
