### ISSUE TITLE
[FE] Nametag banner: Implement GA tracking on disability rating

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#66441]
## Background
Once we have guidance from the analytics team we'll need to implement tagging on the disability rating link in the nametag banner on My VA and Profile.

## Tasks
- [ ] Attend office hours on Thursday to see if there are any questions about our request
- [ ] Implement tagging
- [ ] Request review from Analytics team via #66434 
- [ ] Tag PM for review/validation as well

## Acceptance Criteria
- [ ] Click tracking exists on the disability rating link in the nametag
