### ISSUE TITLE
[BE] Backend Support: Improve observability of BE services

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#66447]
## Background
Ticket to improve observability into BE services (Datadog dashboard and monitoring).

Provide high level health stats for My VA and Profile APIs. We want to know, without much effort, the health of the services that we support.

## Tasks
- [x] Create high level dashboards for the API endpoints for My VA (successful request rate non 4xx-5xx status codes, failure rate 4xx-5xx, response time percentiles)
- [x] Create high level dashboards for the API endpoints for Profile (successful request rate non 4xx-5xx status codes, failure rate 4xx-5xx, response time percentiles)
- [x] Can drill in to dashboards to see individual endpoint performance

## Acceptance Criteria
- [x] In Datadog, we can get easily see the health of all the API endpoints that support My VA
- [x] In Datadog, we can get easily see the health of all the API endpoints that support Profile

## Validation
- @tpharrison can validate the technicalities while a PM should be able to see and understand the dashboards

**Comment by ajakabcin** [comment]
hey @tpharrison is this ready to close? thanks!
