### ISSUE TITLE
[bug] NOD | Issues not loading

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#66444]
## Value Statement
**_As a_** Veteran
**_I want to_** be sure I submitted my Notice of Disagreement form
**_So that_** I do not resubmit the same form

## Background Context
When doing NOD v2 release validation testing. Eileen ran into an error where issues are not loading on the issue screen.
We want to make sure that issues do load, and when issues load all issues load (no longer gated to be within a year).

### Replicate the issue
- On staging, log into user 236
- Go through Board Appeal form 
- Get to issues screen
- See if issues load
- If issues do not load, hard refresh

## Tasks
- [ ] Validate if this is a one-off issue, or persistent issue
- [ ] Fix error 

## Acceptance Criteria
- [ ] All tasks complete
- [ ] All tests passing
- [ ] Confirm by sharing mock data for testing in staging
- [ ] Issues load on issues pages, and not gated to issues within the year

**Comment by eileen-coforma** [comment]
I think this has been fixed. I can't reproduce it.
