### ISSUE TITLE
[BE] Backend Support: Technical discovery, improving BE mocks for FE testing

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#66448]
## Background
We need to do some technical discovery to improve mocking the BE.

## Tasks
- [x] Review the current solution using Betamocks with Tom
- [x] Suggest ways to improve
- [ ] ~Work with Tom and AJ to create subsequent tickets~

## Acceptance Criteria
- [ ] There are ticket(s) to do the improvement work

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ BE dev
- _How will we know this is done?_ there are additional tickets for improvements

## Resources
- [Betamocks Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/betamocks)

**Comment by tpharrison** [comment]
@DanielMiller-agile6 I'm on PTO this week, so let's sync up next week and start working on this.

**Comment by ajakabcin** [comment]
@DanielMiller-agile6 and @tpharrison I'm going to bump this to next sprint per Tom's comment!

**Comment by tpharrison** [comment]
Met with Daniel on Friday to discuss plans for facilitating running local setups with mock data.

**Comment by tpharrison** [comment]
@DanielMiller-agile6 Is it okay if I keep this ticket open and update with the next set of tasks based on our discussion.

cc/ @ajakabcin
