### ISSUE TITLE
Looker Dashboard: Identify Fields and How Data is Sourced

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#66452]
## Description 
In this document, we have some missing fields where we need to identify the source of them (any items that are blank or have brackets around them).

---

## Definition of Done
All tasks are complete below.

---

## Tasks 

- [x] Identify any fields or columns that can have a clearer definition and provide it
- [x] If unable to find definition, ask Kerry if he knows who may know the answer
- [x] If unable to find a definition, see if Clint has the information by sending a group chat to Alyssa and Clint

--- 

## Resources & Additional Info 
[Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2767093962/Support+Responses+Spreadsheet) 

---

**Comment by jknipes** [comment]
@alyssagallion missing information has been filled in. Please review for completeness

**Comment by alyssagallion** [comment]
Looks good, closing!
