### ISSUE TITLE
GA Cost Anaysis - Discovery

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#66463]
## Issue Description

Google Analytics is per unit pricing based on billable hits. We generally stay in budget (what is the monthly budget?) for GA but with the GA4 migration and running the UA & GA4 in tandem for some time we need to forecast any cost implications that may occur and how to mitigate. 

Andrea to provide more detail on costs/contract

---
## Tasks
- [x] Will GA4 tracking put us over our monthly threshold, if so how to manage?
- [ ] Find or create a forecast budget report to alert us when we are getting near threshold

## Acceptance Criteria
- [x] Discovery work complete.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
