### ISSUE TITLE
BQ Cost Analysis - Discovery

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#66464]
## Issue Description
We need to better identify cost drivers and a way to better forecast when those drivers may exceed budget as occurred in August 2023. 

BQ costs are based on usage per month. The average monthly threshold amount is $3,600 (some months slightly over, some slightly under). August was significantly higher at $26k,  It looks like September will also be over budget ~$12k, much less than August but still higher than budgeted. In August we had to re-run many large datasets in BQ so we could update Domo (Domo does not have ability to purge data so we must re-run in order to remove history). Need to determine if there is a better way to access the data through BQ without directly connecting/storing in Domo so we do not need to process every time we need to purge.  Or we need to break each year into quarters and re-run updates in Domo not query when we need to purge a quarter of data. What are other optioins?

Cost reports from GCM are somewhat limited in their detail. We know the primary cost driver is BQ/Analysis which is driven by query processing time (and what else?)

See [email from SD](https://mail.google.com/mail/u/0/popout?ver=1elefj35ogq8q&search=inbox&th=%23thread-f%3A1777480323308447167&cvid=1) with more pricing details. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVRwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fdd3a18a26d1ca2a7ddcdde354ee1c4200bda8b3/image.png)

[1] https://cloud.google.com/bigquery/pricing#analysis_pricing_models
[2] https://cloud.google.com/bigquery/pricing#on_demand_pricing
[3] https://cloud.google.com/bigquery/pricing#capacity_compute_analysis_pricing
[4] https://cloud.google.com/skus?currency=USD&filter=1DF5-1F98-1DD1
[5] https://cloud.google.com/bigquery/docs/reservations-intro
[6] https://cloud.google.com/bigquery/docs/best-practices-costs
[7] https://cloud.google.com/bigquery/docs/reference/auditlogs

[Create dashboards, charts, and alerts](https://cloud.google.com/bigquery/docs/monitoring-dashboard)

Additional resources from GCM Billing Reports:

[Billing Account Overview report](https://console.cloud.google.com/billing/010266-08C856-8D78A0?project=vsp-analytics-and-insights)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaXJwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c419027ebb23db06948e20a26b0c6b9c008df990/image.png)

[Costs by Service](https://console.cloud.google.com/billing/010266-08C856-8D78A0/reports;timeRange=CUSTOM_RANGE;from=2023-06-01;to=2023-09-28;projects=vsp-analytics-and-insights?project=vsp-analytics-and-insights)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXpvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--498bdec25ccef91e1d39493d2921097a7262c87c/image.png)

[Costs by SKU](https://console.cloud.google.com/billing/010266-08C856-8D78A0/reports;timeRange=CUSTOM_RANGE;from=2023-01-01;to=2023-09-28;grouping=GROUP_BY_SKU;timeGrouping=GROUP_BY_MONTH;projects=vsp-analytics-and-insights?project=vsp-analytics-and-insights)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdi9vIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b90e839bcf5f3604492e6ea63cd6ca399fefc726/image.png)

[Metrics explorer report](https://console.cloud.google.com/monitoring/metrics-explorer;startTime=2023-06-01T14:01:00.000Z;endTime=2023-09-19T14:01:45.000Z?project=vsp-analytics-and-insights&pageState=%7B%22xyChart%22:%7B%22constantLines%22:%5B%5D,%22dataSets%22:%5B%7B%22plotType%22:%22STACKED_BAR%22,%22targetAxis%22:%22Y1%22,%22timeSeriesFilter%22:%7B%22aggregations%22:%5B%7B%22crossSeriesReducer%22:%22REDUCE_SUM%22,%22groupByFields%22:%5B%22metric.label.%5C%22table%5C%22%22,%22resource.label.%5C%22dataset_id%5C%22%22%5D,%22perSeriesAligner%22:%22ALIGN_RATE%22%7D%5D,%22apiSource%22:%22DEFAULT_CLOUD%22,%22crossSeriesReducer%22:%22REDUCE_SUM%22,%22filter%22:%22metric.type%3D%5C%22bigquery.googleapis.com%2Fstorage%2Fuploaded_bytes_billed%5C%22%20resource.type%3D%5C%22bigquery_dataset%5C%22%22,%22groupByFields%22:%5B%22metric.label.%5C%22table%5C%22%22,%22resource.label.%5C%22dataset_id%5C%22%22%5D,%22minAlignmentPeriod%22:%2260s%22,%22perSeriesAligner%22:%22ALIGN_RATE%22%7D%7D%5D,%22options%22:%7B%22mode%22:%22COLOR%22%7D,%22y1Axis%22:%7B%22label%22:%22%22,%22scale%22:%22LINEAR%22%7D%7D%7D) shows uploaded bytes billed has not changed.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaTdwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2cad5678807d86c0456e9edc20accb05f2e69f5f/image.png)

---
## Tasks
- [x] Determine best way to manage BQ costs in support of Domo data purge and updates
- [ ] Create tracking report to forecast monthly costs and be alerted ahead when we may go over budget and implement a pause in processing (if possible) to stop the increase

## Acceptance Criteria
- [x] Discovery work complete
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelle-dooley** [comment]
https://docs.google.com/document/d/1Osq1ibA4ts3VBMLCqonYdRUtC90YL80c-teiwv-Lojo/edit#heading=h.ls7vladss0mf

**Comment by michelle-dooley** [comment]
https://docs.google.com/spreadsheets/d/18hhkStmupVb7pK1UAEt0lzmJ-C7Tr6y1/edit#gid=1349399106
