### ISSUE TITLE
GA4 Migration - gtags and mapping

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#66465]
## Issue Description
Continue work on event mapping and gtag configs. Prepare for meeting with Design System team.

---
## Tasks
- [ ] additional events mapped
- [ ] gtag analysis complete

## Acceptance Criteria
- [ ] GA4 project progress as defined
- [ ] 
---
