### ISSUE TITLE
Domo Cost Analysis - Discovery

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#66462]
## Issue Description

Our current Domo pricing model is per unit pricing driven by row counts. In Spring 2023 we went through an exercise to purge historical data b/c dataset sizes were becoming too large and were going to impact pricing. We need to implement an ongoing governance on how to manage the growing size of datasets.  The challenge is Domo does not allow you to purge a subset of data from a dataset (i.e. year 2020). You must re-create the entire dataset. We tried to mitigate this by creating views that could filter out data to be viewed in dashboards but to truly purge that data from Domo this solution does not solve that problem.

We need to determine a better way to manage Domo dataset updates. Can we connect directly to BQ and no longer store data in Domo? Can we break our larger datasets into quarters and purge on quarterly basis (this will still require re-running dataset but could be contained within Domo and not hit BQ and incur those costs. Do we need to move a different pricing model (credit based as presented by team - how will costs change and what will we get for that.

---
## Tasks
- [x] Do we have to store data in Domo? Can we direct connect and what will that do to processing time?
- [x] How do we better manage Domo data storage it so we can purge but not re-run history from BQ to replace (break into quarters?)
- [ ] Determines costs/benefits of staying with current pricing model vs moving to new credit based model (talk to Mason)

## Acceptance Criteria
- [x] Discovery complete
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
