### ISSUE TITLE
Pivot from Airtable to Optimal Workshop for quarterly survey?

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#66467]
## Purpose
We recently learned that Airtable wasn't allowed behind the VA network wall.  Survey Monkey is supposed to be. BUT then we learned that is not; our available option is Optimal Workshop, which allows surveys ([called Questions](https://support.optimalworkshop.com/en/collections/1524596-questions) for some reason).

What would be involved in, and how could we, use Optimal Workshop for the quarterly Platform Satisfaction Survey and get the data into a tool such as Domo for actionable data visualizations?

Documentation on OW access [here](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-OptimalWorkshop) and use Platform.

## To learn
- [x] Could we set up the quarterly survey on OW?
- [x] Could we get OW data to Domo?
- [x] Would the use of Domo save SDT time and effort in understanding and presenting data to Platform?

## Tasks
- [x] Gain access to OW account
- [x] Set up an acceptable Quarterly Survey test in OW
- [x] Create a way to get the Survey data to OW

## Acceptance Criteria
- [x] Initial setup of data visualizations and Domo are ready
