### ISSUE TITLE
DR | Set up continuous deployment for appeals forms

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#66471]
## Value Statement
**_As a_**  developer
**_I want to_** set up [continuous deployment (CD)](https://depo-platform-documentation.scrollhelp.site/developer-docs/continuous-deployment)
**_So that_** we can speed up our iterative process for implementing changes & fixes

## Background Context

With the VA adding more apps and increasing test coverage, the continuous integration (CI) time will increase. More flaky test will likely be exposed and cause delays. With a switch to continuous deployment, our apps will be isolated and only need to run tests associated with the app. Release to production is also performed. We won't need to wait for the daily deploy cycle.

Pros:
- Quicker CI
- Can opt-out of CD if we want
- Don't have to wait for deployment schedule
- Delivery won't be limited by flaky tests from other apps

Cons:
- Bugs will be deployed and effect Veterans in production almost instantly after merging in a code change (BUT, again, we can opt-out of CD if we want)
- Feature flags will need to be used for any significant changes

## Tasks
- [x] Review [continuous deployment set up instructions](https://depo-platform-documentation.scrollhelp.site/developer-docs/continuous-deployment)
- [x] Check for app isolation
  > ```json
  > {
  >   "appeals": {
  >     "appsThatThisAppImportsFrom": {
  >       "static-pages": {
  >         "filesImported": [
  >           {
  >             "importer": "src/applications/appeals/996/wizard/WizardContainer.jsx",
  >             "importee": "src/applications/static-pages/wizard"
  >           }
  >         ]
  >       }
  >     },
  >     "appsThatImportFromThisApp": {},
  >     "platformFilesThatImportFromThisApp": [
  >       "src/platform/forms/tests/sub-task/basic-2-page.unit.spec.jsx"
  >     ]
  >   }
  > }
  > ```
- [ ] HLR: [Switch deprecated wizard to subtask](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57821) (fixes app isolation)
- [ ] SC: Copy subtask pages into platform test (fixes app isolation)
- [ ] Add appeals to allow list
- [ ] Educate team members on the impact of this change
- [ ] Test minor change in CD cycle
- [ ] Notify stakeholders about this change

## Definition of Done
- [ ] Continuous deployment in place
- [ ] All team members are aware of the impact of these changes
- [ ] Implementation has been shared with all team members & stakeholders

## Acceptance criteria
- [ ] All tasks complete

**Comment by saderagsdale** [comment]
@kylesoskin @data-doge need some input on how we know when this work is ready to pick up and what the exact tasks are, including any gate checks with stakeholders or the platform team.

**Comment by saderagsdale** [comment]
Need to confirm if this is properly groomed before committing.

**Comment by saderagsdale** [comment]
Questions:

- Is the pipeline already setup correctly for our app? Any configurations needed?
- Is version control setup?
- What E2E, unit, and integration tests do we need?
- Do we need a build script and deployment script for automation?
- How is this connected to monitoring?
- What is the rollback procedure?
- What documentation is needed?
- Do we need to define security and access control or is this predefined by platform?
- Are there any regulatory requirements from OCTO?

**Comment by saderagsdale** [comment]
@Mottie can we close this?

**Comment by Mottie** [comment]
Not yet, let's discuss with Shaun

**Comment by shaunburdick** [comment]
Hold on this ticket until the HLR and SC form updates have been release.

**Comment by shaunburdick** [comment]
Once preview environment is in place, we can test everything in the PR and we wouldn't need this ticket.

**Comment by Mottie** [comment]
Platform has already implemented this for our apps. Closing as completed
