### ISSUE TITLE
[bug] NOD | Fix load error alert visibility on reload

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#66478]
## Value Statement
**_As a_**  Veteran
**_I want to_** be confident that my contestable issues loaded properly
**_So that_** I don't get confused by the load error alert showing up

## Background Context

If the contestable issues fail to load on the introduction page, a recent change attempts to load in the contestable issues on the contestable issue page; but the load error alert remains visible at the top of the page. This can be easily tested by performing a hard browser reload on the contestable issues page for NOD form. HLR doesn't have this issue because it is not reloading issues & Supplemental Claims doesn't have this issue because of the Intent-to-File intermediate page showing up.

![NOD load error alert showing along with loaded issues](https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/97921171-8580-4cb8-ac6d-c8842e9309a5)

## Acceptance Criteria
- [ ] If contestable issues load as expected on the contestable issues page, the load error does not appear. 
- [ ] If there are no available issues, the appropriate error message appears
- [ ] If contestable issues are not loading, the appropriate error message appears

## Tasks
- [ ] Determine cause of load error alert visibility even after issues are successfully loaded
- [ ] ~Fix alert visibility in HLR~
- [ ] Fix alert visibility in NOD
- [ ] Add unit tests

## Definition of Ready 
- [ ] We know why the error alert appears even when contestable issues are loading as expected
- [ ] We know how to direct the Veteran if the issues do not load

## Definition of Done
- [ ] Load error alert only appears if the second load issue attempt fails
- [ ] Veteran has an actionable error message
- [ ] All tests passing
- [ ] Fix implementation verified

**Comment by HeatherWidmont** [comment]
Once its available in staging Robin will tag Eileen & Sade to review

**Comment by saderagsdale** [comment]
@Mottie Is there another way to test this for HLR? 

@eileen-coforma Can you clarify what's wrong with the error message and post a snapshot of it?

**Comment by eileen-coforma** [comment]
![Screenshot 2023-10-04 at 1 34 43 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/111457818/3d494870-3216-462e-bbd7-a61299400406)

What's currently displaying is the new error message we created for when there is a problem loading the issues endpoint.

For HLR, I don't think we aren't able to load issues from the endpoint, but that there are no eligible issues (since it's gated to the last year). If that's the case, the original error message should display, which is the following:

> Sorry, we couldn't find any eligible issues
> 
> If you'd like to add an issue for review, select "Add a new issue" to get started.

**Comment by Mottie** [comment]
Hmmm, actually, I just tested this for HLR locally, and it's still broken... let me fix it real quick 😞

**Comment by Mottie** [comment]
Removed references to HLR in this ticket

**Comment by Mottie** [comment]
@saderagsdale I think we can close this ticket now

**Comment by saderagsdale** [comment]
@Mottie so the scope of the fix is just NOD now?

**Comment by saderagsdale** [comment]
@Mottie for HLR, does the correct error message now appear if there are no contestable issues?
