### ISSUE TITLE
Support & Resources links: direct to classic MHV or new MHV / VA.gov?

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#66484]
## User Story
As a MHV user, I want to stay on the same website and have a consistent experience when I click links in the Support & Resources area of the MHV landing page as opposed to getting sent to sites such as the old MHV site. 

## Description
Some of the links in the Support & Resources area of the landing page direct users to old MHV classic pages. We need to:
- determine the content strategy for these links
- fix the links to point to different pages or decide to let them stay as-is for now

## Impacted Artifacts
* MHV on VA.gov landing page

## Tasks
- [ ] Reach out to Danielle or Miki about what has been decided about the types of links that live on the landing page

## Acceptance Criteria
- [ ] We have either implemented new links on the landing page, or
- [ ] We have learned that these links are to stay as-is for now
