### ISSUE TITLE
Investigate if CorpDB provides "Address 1" for representatives

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#66503]
## Issue Description
In [#66223](https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/66223) we identified that a representative's `zip code` is available from the file that the "daily rep reload job" pulls, however `Address 1` is not.

We do see `Address 1` data when doing a representative search on eBenefits.  Where is that information coming from?

`Address 1` is a critical piece for the Attorney and Claims Agent representative types, as it is required for the 21-22a form. 
 This ticket is to investigate if CorpDB -- which gets data directly from OGC -- includes the `Address 1` field that we need.

---
## Tasks
- [x] Work with the VA PO and enablement team to get access to CorpDB data
- [x] Review CorpDB data
- [x] Verify if CorpDB data contains `Address 1` and for what representative types

## Acceptance Criteria
- [x] CorpDB data has been reviewed for the presence of `Address 1`
- [x] The team has been informed of findings

**Comment by oddball-lindsay** [comment]
Notes from Holden:
> We do need access to the CorpDB data because it gives us the addresses for the Claims Agents and Attorneys which are needed for the Form.
The VSO data we currently have seems to be more complete than the local/regional, state and national org data in CorpDB. And we only have the city, state and zip for each VSO location. 

The next step would be to get production access to the CorpDB data.

**Comment by oddball-lindsay** [comment]
After a discussion with Zach in Sprint 3 Demo, we will see if we can proceed with direct OGC data instead of the CorpDB export (which ultimately pulls from OGC)
