### ISSUE TITLE
[discovery] DR | Upgrade to newest Lighthouse APIs

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#66514]
## Issue Description

Lighthouse's Decision Reviews APIs are on v2, but NOD is using v1. HLR is likely also using v1. I'm not sure about SC. V1 is deprecated, so we should upgrade.

---
## Tasks
- [ ] Figure out where we need to upgrade to LH's v2 APIs.
- [ ] Draft tickets for that work.

## Acceptance Criteria
- [ ] Tasks done.

## Definition of Ready
N/A

## Definition of Done
- [ ] Acceptance criteria met.
