### ISSUE TITLE
IPP Roadmap through August 2024

### ISSUE THREAD

**Issue by rdvyas** [department-of-veterans-affairs/va.gov-team#66516]
Context
An updated IPP roadmap is needed to distinguish what user stories will be satisfied for the pilot and what will be the focus following pilot through 8/17/2024

AC
- [x] List of user stories that will happen for pilot
- [x] List of user stories that will happen after pilot or before 8/17/2024
- [x] Calendar with activities that enable user stories to be satisfied mapped out across time until 8/17/2024
DEF OF DONE
- [x] Lists shared with SSiT team
- [x] Calendar shared with SSiT team

[Storymapping Mural](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1701783746829/228091c21f215974c47e8610e999f05729cd5124?sender=u8b2bd1f5eec8aeeb5ca99521)

[IPP Roadmap](https://docs.google.com/spreadsheets/d/1GjsA1RtBevn3yBUyHEb-LNUq9FeebUDMdIdCk1hLc00/edit#gid=0)

**Comment by lmorris3** [comment]
@sdickson-gt @rdvyas is this a copy of a ticket that's been completed? Or is this work that still needs to be pulled in?

**Comment by skirkman16** [comment]
Updated roadmap is captured in [this spreadsheet](https://docs.google.com/spreadsheets/d/1GjsA1RtBevn3yBUyHEb-LNUq9FeebUDMdIdCk1hLc00/edit#gid=0)
