### ISSUE TITLE
DR | Remove PII from Evidence Upload Logs in DataDog

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#66510]
## Issue Description

In our evidence upload logs, we show the title of uploaded documents as `payload.params.decision_review_evidence_attachment`, which may contain PII. See [example](https://vagov.ddog-gov.com/logs?query=%40payload.controller%3A%22V0%3A%3ADecisionReviewEvidencesController%22%20%40payload.status%3A422%20&cols=host%2Cservice%2C%40payload.user_uuid&event=AgAAAYrXbqabthD6awAAAAAAAAAYAAAAAEFZclhicmdHQUFCb1pzTVlGeEY0VGdBMQAAACQAAAAAMDE4YWQ3N2MtOGYzNi00NmFiLWFhMDEtNDg2Mzg3ZDcyZTM3&index=%2A&messageDisplay=inline&refresh_mode=sliding&stream_sort=desc&viz=stream&from_ts=1695302779499&to_ts=1695907579499&live=true). We want to redact this information from our logs.

---
## Tasks
- [ ] Redact filename from logs.

## Acceptance Criteria
- [ ] Filename redacted from logs.

## Definition of Ready
N/A

## Definition of Done
- [ ] Acceptance criteria met.
- [ ] Talk with platform about removing PII from existing/archived logs, and possibly create follow up ticket for that work.
