### ISSUE TITLE
Audit and edit Collaboration Cycle email distribution lists

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#66523]
## User Story
As a Governance team member, I want to ensure the people invited by default to Collaboration Cycle touchpoints absolutely need to be invited and/or in attendance so that the meetings do not get overwhelming for VFS teams.

Assignee: @erinrwhite 
Peer Reviewer: @allison0034 

## Description
The number of people included in the Design Intent, Midpoint Review and Staging Review distribution lists has grown since the lists were originally created. As there are alternate paths for becoming aware of a Collab Cycle touchpoint and then attending it, and since not every member of the lists attends regularly, Governance team has decided to audit the lists and then remove the individuals that are no longer necessary to include. 

## Impacted Artifacts
[Design Intent distribution list](https://groups.google.com/a/oddball.io/g/va.gov-design-intent/members)
[Midpoint Review distribution list](https://groups.google.com/a/oddball.io/g/va.gov-midpoint-review/members)
[Staging Review distribution list](https://groups.google.com/a/oddball.io/g/va.gov-staging-review/members)

## Tasks
- [x]  Audit each list. Create a draft for tracking changes in Confluence
- [x]  Propose who should remain on the list and who should be removed
- [x]  Share with Shira and Matt for review and approval
- [x]  For those that are being removed, inform them via Slack (preferable #platform-collaboration-cycle channel if all are included) that they've been removed and that all Collaboration Cycle events are open and anyone is able to join if they choose. All event information can be found in the [Collaboration Cycle calendar](https://calendar.google.com/calendar/u/0/embed?src=c_7iurst2mk3hdhfuto5u7lemgbk@group.calendar.google.com&ctz=America/New_York)

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] The Collaboration Cycle distribution lists only include the critical people
- [ ] All individuals removed from the distribution list have been informed and have been given an alternate path for attending Collaboration Cycle touchpoints, if they so choose

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
@shiragoodman Does the draft need to live in Confluence, or can it be a spreadsheet? I started a sheet, but can easily port it over.

**Comment by shiragoodman** [comment]
no it doesn't need to be in Confluence @erinrwhite . Just make sure Matt and I have access when you share it with us. Same with your peer reviewer.

**Comment by erinrwhite** [comment]
@shiragoodman @allison0034 @humancompanion-usds Hi folks - here's a [spreadsheet of membership in each touchpoint's email list](https://docs.google.com/spreadsheets/d/1Z3o5hIiJexFSwaUJkuUSgBKSSz4BnWMlfeWAPmSyBPE/edit#gid=0) along with my recommendations for removal and/or asking folks if they'd still like to be on the list. Comments/edits welcome, thanks!

**Comment by shiragoodman** [comment]
thank you @erinrwhite . I just took a quick look. To summarize, it looks like we'll keep all Governance folks (duh), ask all the CAIA folks, and remove everyone else. I'm mostly on board with that. For CAIA, I'd prefer if we removed everyone who's not an OCTO PO, yet still ask the POs if they'd like to stay on the list. We currently don't invite the full CAIA team, and I'm not sure why we have some people included but not others (for example, for a11y we have Sara Smith and SK, but not Eli, Jamie or Kate). I think just removing all of them and directing all CAIA folks to our calendar as an alternate path for attending would be easiest.

LMK what you think.

**Comment by erinrwhite** [comment]
@shiragoodman Let's do that! It seems strange to me too that some non-OCTO CAIA folks are on this list and some aren't. I've [updated the spreadsheet](https://docs.google.com/spreadsheets/d/1Z3o5hIiJexFSwaUJkuUSgBKSSz4BnWMlfeWAPmSyBPE/edit#gid=0) - do I have our OCTO contacts correctly classified?

**Comment by shiragoodman** [comment]
looks good @erinrwhite - thank you!

feel free to go ahead and reach out to everyone we're removing from the list or asking if they'd like to stay on the list. This is likely low priority for Matt, so I don't expect him to chime in or push back on our decision.

**Comment by shiragoodman** [comment]
update per standup: Shira will handle all of the unsubscribe folks on the list. Erin will handle all of the CAIA folks.

**Comment by erinrwhite** [comment]
[posted in collab cycle channel](https://dsva.slack.com/archives/G01DXP10GCA/p1706133016863739) on Slack and followed up with OCTO CAIA folks and Shane. Keeping the list updated as I hear back.

**Comment by erinrwhite** [comment]
@shiragoodman Randi isn't on any of our lists. Should she be?

**Comment by shiragoodman** [comment]
that's a great question @erinrwhite . I will follow up in the post you made in the collab cycle Slack. Thanks!

**Comment by shiragoodman** [comment]
I let Kevin know yesterday. I will let Ray know today.

@allison0034 should have edit access. since she is the PR, I would prefer id she made the updates to the google groups. if she is unable to, let me know and I can complete it.

**Comment by allison0034** [comment]
@erinrwhite the lists should be updated, please double check :)
