### ISSUE TITLE
[CST] Claims showing as completed in timeline

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#66535]
## Background
We noticed an issue where the timeline could indicate that a claim had been completed even though it was on a different step in the process. The timeline still indicates the correct step in the process but we should look into 

## Impact
<img src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/13838621/f162ea3f-bc99-4ce1-98e4-b0005bdc098f" width="500">

## Preliminary Technical Discussion
This is an issue with the Lighthouse (LH) version of the claim components. It's possible to discern this because the "We closed the notice for " text indicates that the notice was "Secondary Action Required". If this was the EVSS version, the text would be something like "We closed the notice for Request 1" instead.

Components involved:
* [ClaimTimeline](https://github.com/department-of-veterans-affairs/vets-website/blob/2b65964/src/applications/claims-status/components/ClaimTimeline.jsx)
* [ClaimStatusPage](https://github.com/department-of-veterans-affairs/vets-website/blob/2b65964/src/applications/claims-status/containers/ClaimStatusPage.jsx)

[Suspected offending code](https://github.com/department-of-veterans-affairs/vets-website/blob/2b65964/src/applications/claims-status/containers/ClaimStatusPage.jsx#L93-L99)
```jsx
if (claim.attributes.closeDate !== null) {
  phases.push({
    type: 'complete',
    phase: 8,
    date: claim.closeDate,
  });
}
```

## Technical findings
Components involved:
* [ClaimStatusPage](https://github.com/department-of-veterans-affairs/vets-website/blob/2b65964/src/applications/claims-status/containers/ClaimStatusPage.jsx)

[Offending code](https://github.com/department-of-veterans-affairs/vets-website/blob/f40d4a816e18de7e8ca007bb69000fffbc3aced4/src/applications/claims-status/containers/ClaimStatusPage.jsx#L101)
```jsx
return phases.filter(isEventOrPrimaryPhase);

function isEventOrPrimaryPhase(event) {
  if (event.type === 'phase_entered') {
    return event.phase <= 3 || event.phase >= 7;
  }

  return !!getItemDate(event);
}
```

## Tasks
- [x] Determine what is causing the timeline events to display this way
- [ ] Update the code to rectify the issue

## Acceptance Criteria
-  [ ] Events do not show up in the timeline for later phases than the phase the claim is currently in
