### ISSUE TITLE
Probable bug with FileField.jsx

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#66536]
## Issue Description
An issue was brought to the attention of platform support. As the original issue was filed in Jira, going to include a screenshot of the issue, a link to the support thread, a link for testing, and some additional context.

I was able to reproduce this issue by following the instructions they had in their Jira ticket. Essentially, this combination of actions causes data that had been entered in the form, to wipe after the fact and have to be re-entered. 

Original Support Thread: https://dsva.slack.com/archives/CBU0KDSB1/p1695904667408639

Url of where this can be tested: https://staging.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/supporting-documents

Original Jira task with steps to reproduce:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBblBxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--89ead98d85572fdd469689e39d07d361c8a9f932/image.png)

---
## Tasks
- [ ] Investigate into cause for the data being dropped out.
- [ ] Determine the best route for a fix (require files to be fully filled out before moving on to the next, stop the data from being dropped, etc).
- [ ] Implement a fix

## Acceptance Criteria
- [ ] The user experience is smoothed out to where users can no longer lose entered form data unexpectedly.
---

**Comment by MichelleDieudonne** [comment]
@ndsprinkle Is there a timeline for this fix?  Our customer is asking for a status for their records.  Thank you!

**Comment by MichelleDieudonne** [comment]
@HeatherWidmont I see you made some pipeline changes.  Are you able to give a status for when this is expected to be worked?  Thank you!

**Comment by MichelleDieudonne** [comment]
@ndsprinkle Do we have an ETA for this work? Thanks!
