### ISSUE TITLE
Collaboration Cycle for Authenticated Experience My VA - dot indicator on health care unread messages 

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#66544]
### VFS team name

Authenticated Experience My VA

### Product name

My VA

### Feature name

dot indicator

### GitHub label for product

my-va-dashboard

### GitHub label for feature

onsite-notifications

### Public DSVA Slack channel for VFS team

accountexp-authexp

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

August 2023

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Unsure

### Will your work involve changes to...

Other

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

No

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/dot-indicator/create-dot-indicator/README.md

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Notify the Collaboration Cycle team of this ticket in your team's public Slack channel.

- [X] I acknowledge that I must notify the Governance team by completing the collab cycle kickoff workflow in my team's Slack channel after submitting this issue. This can be completed by typing "/collab cycle" and selecting the appropriate workflow.

Kickoff Slack Thread with VFS team: [Kickoff thread](https://dsva.slack.com/archives/C909ZG2BB/p1695920595485569)
</details>

### Staging Review
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [ ] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [ ] I confirm the environment is available and test users have been provided.
- [ ] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).

**Staging Review artifacts**
  
See Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts). Platform findings are based solely on the staging URL and test users provided, as reviewed during the four days before the Staging Review meeting. Any test cases not covered or any ongoing work taking place during the review period may not be reflected in those findings.  

**Product artifacts** 
- [x] Staging URL: staging.va.gov/my-va
- [x] Specify which pages are included in the review: the "Go to your inbox" link within the Health Care section on My VA     
- [x] Staging test user information          any of the following: [41, 226](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv), [Cecil Morgan](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-vaos.md)
  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**
- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including a content source of truth, any relevant static content page and entry point updates, and the intake form: _NA - see [MHV CC ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60663) for reference_
  
**IA artifacts**
- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) feedback you received, including an IA review document or intake form: _NA - see [MHV CC ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60663) for reference_

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [x] [QA artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications/dot-indicator/create-dot-indicator/qa-dot-indicator) 
- [x] all of My VA E2E tests [here](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/personalization/dashboard/tests/e2e)
- [x] [Code coverage](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/personalization/dashboard/tests/components)  
  
**Accessibility artifacts**
  
- [x] Completed accessibility testing artifact - [67204](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67204)

##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C909ZG2BB/p1697224630119359)
- [x] Meeting date/time: October 24, 11:30am ET

##### Platform actions

- [ ] Update this ticket with the Zoom recording
  - Recording link: https://oddball-io.zoom.us/rec/share/PRB7GklFvW63AkCWJjKBwMnc4K_ZbHbCAOiXulEfv9tzkib-5vfsC90CV0HK-QHb.ywTjByYX7MtwPyic
  - Password: vZ0*9Vuq
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [x] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [x] Link to the Readiness Review ticket below: [1319](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1319) 

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by ajakabcin** [comment]
hi @shiragoodman I'm trying to do some deep backlog cleanup before my leave and noticed this is still open, however all of the remaining open issues are not within scope of the Authenticated Experience team but instead pertain to the legacy secure messaging tool. Is it possible to close this out since my understanding is that work on the legacy tool is not being prioritized over the new version on VA.gov? Thank you!

**Comment by shiragoodman** [comment]
@ajakabcin yes, you can close this out. Once the ticket is past Staging Review, it can be closed (even if there's open findings tickets since this is just the _tracking_ ticket).  For the 9 open findings tickets, it looks like they're missing a team and product label. I see I removed your teams labels a while back. 

Are you saying @bryan-riley-va and the MHV Secure Messaging team is responsible for fixing the findings?

**Comment by ajakabcin** [comment]
@shiragoodman thanks! I don't know how much emphasis/prioritization is being placed on the legacy MHV SM tool, but I believe @bryan-riley-va  and/or @janieTC-USDS would be the points of contact for the new tool and would make sense at least for them to be aware of these issues on the legacy tool
