### ISSUE TITLE
Create documentation on setting up RUM for apps

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#66547]
## Value Statement
**_As a_**  developer
**_I want to_** have clear instructions on how to set up Real-User Monitoring for an app
**_So that_** we can get clear direction on now to set up RUM and prevent PII/PHI exposure

## Background Context

Setting up RUM isn't as simple as copy/pasting the initialization code. We need to consider feature flags, adding class names to hide PII/PHI and extra work needed for the review & submit page

## Tasks
- [ ] Write up RUM set up documentation
- [ ] Engineers experienced with RUM setup to review
- [ ] Share with Steve Albers for final review

## Definition of Done
- [ ] Document created
- [ ] Reviews complete

## Acceptance criteria
- [ ] All tasks complete

**Comment by Mottie** [comment]
Done - [documentation added to VA.gov-team PR](https://github.com/department-of-veterans-affairs/va.gov-team/pull/66986/files?short_path=a8c3f20#diff-a8c3f204035bb3952c4bfb993e0787c245908867ec921db896b0bb8f54f11f33)
