### ISSUE TITLE
Provide claim info to VBA when pdf is missing

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#66551]
## Issue Description
_Provide the VBA with 686/674 claim information if the pdf fails to generate (e.g, using the json file to generate the pdf)._

---
## Tasks
- [ ] Pull claim information if pdf fails to generate.
- [ ] Provide VBA with information for failed claim.

## Acceptance Criteria
- [ ] If the pdf fails to generate when the claim is submitted, a pdf is generated and sent to ??
---
