### ISSUE TITLE
CANCELED**Research: Non-veteran user roles

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#66552]
### Description of UX Tasks

A veteran may need to designate another user to make changes in or manager their VA account. We should explore the needs and desires of users in order to come up with solution(s) to how the MVP of this new product could take shape.

This work should not focus on potential other non-veteran roles like: family, dependent, etc.

We need to understand use cases, barrier to entry, and potential needed features. We need to decide what, if any, further research our team should do on this topic, and where, if at all, we should collaborate with one of the representative auth teams. One of those is representative facing and another veteran facing.

- Accredited Representation Management team (this is the veteran facing team) 
   - PM Lindsay Li-Smith, UX Janelle Finnerty (an Oddball contract also with Danielle B as Program Manager)
   - [Their team folder in GH](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/accredited-representation-management)
- Representative facing team 
   - contact Alex Prokop (note: his Slack profile reflects a previous contract/position as of 1/4/23)
   - [possible relevant slack convo](https://dsva.slack.com/archives/CSFV4QTKN/p1697558078225259)
   - [another possibly relevant slack convo](https://dsva.slack.com/archives/CSFV4QTKN/p1697049401329139)
   - as I recall from meeting with them, at the time they plan to build out an entirely different page for representative sign in with no access to the user's own VA information (if applicable). This would reduce confusion for those who are both veteran's and now Representatives

**Tasks**
- [ ] Review previous discover research
- [ ] Figure out Core Identity's place in this work

#### Documentation
- [User role discovery](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Research/user-roles/discovery)
- [Product brief (currently WIP)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/Product%20Briefs/Non-Veteran%20Experience.md)
- [Accredited Representation Management GH folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/accredited-representation-management)
- [Flow for Delegate Access future state](https://dsva.slack.com/archives/C05L6HSJLHM/p1699032748051269)
- [Notes from Oct meeting](https://dsva.slack.com/docs/T03FECE8V/F0610FU20GM) that included some of these other folks and Core Identity

#### Acceptance Criteria
- [ ] Reviewed by UX Team
- [ ] Reviewed by PMs
- [ ] Documentation has been updated
- [ ] Put published research in drive

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by charlye-bluetiger** [comment]
What are the technical limitations of having non-veteran roles e.g. how do we set up "user" roles on the back-end?  

Are we going to butt up against IAM team's space?

**Comment by charlye-bluetiger** [comment]
[VSO Current/Future State Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1701101229797/15c7e1a5a9d426a998eb634408ff1dd3f4f9bdd1?sender=u653bd2f97cddb10e8a797832)

**Comment by charlye-bluetiger** [comment]
[Notes from prior meeting with VRO team](https://dsva.slack.com/archives/C04MM3WJN1E/p1705956505341749)

**Comment by charlye-bluetiger** [comment]
Paused to focus on new team structure and priorities.
