### ISSUE TITLE
Implement New Medallia Version

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#66559]
## Product Outline
[Medallia Product Outline](https://vfs.atlassian.net/wiki/spaces/Contact/pages/1794015358/Medallia+Product+Outline)

|Form name                                 |In Staging|In Production|
|------------------------------------------|----------|-------------|
|VFS Questionnaire                         |          |             |
|VFS Search Questionnaire                  |          |             |
|VFS Chatbot Quesstionnaire                |          |             |
|Debt portal                               |X         |             |
|VFS A11y Questionnaire(intercept)         |          |             |
|VA.gov A11 VHA Questionnaire(intercept)   |X         |             |
|External Website Survey (ORMDI)(intercept)|          |             |
|Internal Website Survey (ORMDI)(intercept)|          |             |
|After Visit Summary                       |          |             |
|School Administrator                      |          |             |

## Hypothesis or Bet
**If** we update to the latest Medallia version, veteran feedback surveys will have latest functionality and resolve many remaining accessibility issues. 

### What must be true in order for you to consider this epic complete? 

- [ ] VA.gov implementation of Medallia updated to newest version.
- [ ] Remaining accessibility issues are resolved and any remaining ones have a plan for tackling. 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by UXCamG** [comment]
The Medallia team provided this update.  Once staging is cleared (Debt Portal is launched). We will work with Medallia Resources and Your team to release the Medallia Version 2 design to reassess our surveys in 508

**Comment by ATMiddleton** [comment]
Medallia Version 2.0 (updated sandbox) has been completed and in actively in use.

**Comment by clantosswett** [comment]
I am thinking that we should be good to close this epic out but let's discuss later this morning.
