### ISSUE TITLE
UX | Profile | Personal information | Update FAQs on personal information

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#66577]
## Background
In conversations with Sylvia Palmer (MHV contact center lead), we heard some feedback about our personal information page

### Gender identity
- when a veteran changes their GI in their profile, they expect this to be populated across VA systems
- they’re still getting gender-specific health emails from VA health facilities (e.g. wellness check reminders) related to a former gender they no longer identify with
- this is understandably disturbing and triggering

### Preferred name
- the HRC Help Desk (aka MHV Help Desk) does not access VA records on every call inquiry so therefore a Veteran may not be referred to by their preferred name in their MHV Help Desk interaction. However the profile page indicates their preferred name will be honored during “health care team” transactions. If they don't access the records, HRC will refer to the VA patient by their legal name when trouble shooting their technical issue.

We should discuss these scenarios with the content folks and make any updates we can to the FAQ to address this situation. The current language suggests this is a VA-wide update.

## Tasks

- [x] Gather any available documentation about this
- [x] Draft content changes
- [x] Review proposed changes w/ content folks
- [x] Update Sketch and Figma mock-ups
- [ ] Tell mobile team

## AC
- [x] Ready for FE - mockup/copy is available:
- [Figma](https://www.figma.com/file/qfyUmEOVawplgrEKYKFp0f/Profile---Personal-information?type=design&node-id=0-17&mode=design&t=JjkBzaQ1qv4vzErj-11) 
- [Sketch](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/5n1mDYp)

**Comment by mistymg** [comment]
@andaleliz When you review these changes with the web's content team, could you include me in that meeting/Slack exchange so I can chime in to make sure it works for mobile app, too? Thank you!

**Comment by andaleliz** [comment]
@mtcA6 what do you think about pulling this into the current or next sprint, as sort of "as time allows" work? I don't think it's a ton of work and it could make a very positive impact.

**Comment by andaleliz** [comment]
Ah, @mistymg I totally forgot to add you to the meeting today 🤦‍♀️ I'm so sorry. I jumped in kind of last minute because a UAT session was cancelled and I found myself with extra time.  Here's what I've proposed to Sylvia:

**Preferred name**
I can't find the reference to "health care team" that Sylvia mentioned, so I've asked her to clarify.  In the meantime, I propose we update existing language:
>Share this information if you'd like us to use a first name that's different from your legal name when you come in to VA. 

to clarify it's applicable to VA _locations_:
>Share this information if you'd like us to use a first name that's different from your legal name when you come in to a VA location. 

**Gender identity**

We'd like to split out the content to be bulleted, and let folks know how they can correct things if they're still getting emails related to their former gender. This is what we want to review w/ Sylvia to be sure it's accurate:

>Sharing your gender identity in your VA.gov profile is optional. If you get health care at VA, this information can help your care team better assess your health needs and risks. 
>Here's what else to know about sharing your gender identity in your VA.gov profile:
>	• 	**If you want to share your gender identity in your health records only, talk with your health care team.** Any information you share in your profile goes into your VA records beyond health care. VA staff outside of the health care system may be able to read this information. We follow strict security and privacy practices to keep your personal information secure. 
>	• 	**Some systems may not update your gender identity based on your profile.** If you receive communications about gender-specific health care that you wish to stop receiving, contact your VA health care facility and ask them to update your preferences. [Find your VA health care facility's contact information].

Let me know if you have any questions, and again, apologies that I didn't give you a heads up that I'd be joining the office hours today.

**Comment by andaleliz** [comment]
@mistymg FYI, I'm still going back and forth via email with some folks to verify that those are the actual steps a veteran  can take to stop receiving those emails.

Also, as it turns out, we don't need to make any changes to preferred name. There are some updates coming to the MHV support staff systems to make it easier for them to see preferred name when speaking to veterans, and there is a directive stating staff should use preferred name when speaking with veterans.

**Comment by andaleliz** [comment]
I got clarity on this from Lexi, who is with the LGBTQ+ health program. She explained that all systems _should_ have access to GI, and those health communications are based on birth sex.  That means our updated FAQ should inform Veterans about that and how to go about changing that.  I've drafted a new version that I'll run by @DanielleThierryUSDSVA , and then via email with Lexi and her team.  

---

**Proposed draft**

Sharing your gender identity in your VA.gov profile is optional. If you get health care at VA, this information can help your care team better assess your health needs and risks.

Here's what else to know about sharing your gender identity in your VA.gov profile:
• **If you want to share your gender identity in your health records only**, talk with your health care team. Any information you share in your profile goes into your VA records beyond health care. VA staff outside of the health care system may be able to read this information. We follow strict security and privacy practices to keep your personal information secure.
• **Some systems send communications based on the birth sex on your original birth certificate**. To change your birth sex from what was listed on your original birth certificate, you'll need to complete a form with your facility VA Privacy Officer. You'll also need two types of supporting documents, one of which can be a letter from your provider. You can contact your local LGBTQ+ Veteran Care Coordinator or local Patient Advocate to assist you with the process. 
[Find your VA health care facility's contact information].

--- 

I'll try to get feedback from Danielle via this ticket, but will review in office hours on 10/26 if that's not possible. FYI @mistymg in case you'd like to join the convo.

**Comment by andaleliz** [comment]
Actually, Danielle will not be available during office hours on 10/26, so we're going to do an async review.

**Comment by andaleliz** [comment]
@mtcA6 I'll need to carry over 2 points into the next sprint for this one.

**Comment by andaleliz** [comment]
Moving this to blocked as I'm waiting for feedback

**Comment by mistymg** [comment]
Hey @andaleliz! Was the new copy for this ever approved by CAIA? Will you let me know when it is and I get put a ticket in our backlog to implement where appropriate in the mobile app. Thanks!

**Comment by andaleliz** [comment]
Thanks for following up @mistymg - it hasn't been approved yet. Still waiting for @DanielleThierryUSDSVA to provide async feedback.

**Comment by mistymg** [comment]
No worries, @andaleliz! I know Danielle's always swimming on content requests, so whenever you get approval, just send me a ping :)

**Comment by andaleliz** [comment]
Status update: [sent follow-up to Danielle in Slack today.](https://dsva.slack.com/archives/C01K37HRUAH/p1700581611979239)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @andaleliz. Thanks for following up on this. As we chatted about in slack, I'd thought we'd left off with Sylvia providing some more accuracy info. But looking at the above, I have 1 big question to start with: The info on changing birth sex seems to apply only to Veterans with VA health care. Have you looked into how to change this beyond health care? I can help you do that, but wanted to ask first.

**Comment by andaleliz** [comment]
@DanielleThierryUSDSVA I haven't looked into that 😢 and would very much welcome your help. Since this all came up in the context of wellness reminder emails, I didn't reach out to anyone outside of the health side of the house.  Thank you for being so thorough and thinking of this!

**Comment by andaleliz** [comment]
@DanielleThierryUSDSVA I'd love to make progress on this ticket. You mentioned you could help me look into how to change this information beyond healthcare - it'd be super helpful if you could give me some contacts to reach out to to start the inquiry. I can cc you on any messages I send.  Thanks!

**Comment by andaleliz** [comment]
@DanielleThierryUSDSVA, based on the PDF I found (sent via teams, not sharing here since it's on sharepoint), I propose we make this update. My changes are italicized so you can spot them better, though I don't propose we actually italicize them in the copy.

**Some VA health care systems send communications based on the birth sex on your original birth certificate.** To change your birth sex from what was listed on your original birth certificate for health communications, you'll need to complete a form with your VA health facility's privacy officer. You'll also need 2 types of supporting documents. _One of these documents can be a current government issued photo ID.  The other can be an amended birth certificate, court order, or signed letter from your physician._ You can contact your local LGBTQ+ Veteran care coordinator or local patient advocate to help you with the process.
[Find your VA health care facility's contact information]

**Comment by DanielleThierryUSDSVA** [comment]
@andaleliz Thank you for looking into that more! This looks great. 2 tiny tweaks:

- add a hyphen in "government-issued"
- Tweaks to shorten last sentence just a bit and change "local" to "facility's" - Contact your facility's LGBTQ Veteran care coordinator or patient advocate for help with the process.

**Comment by mtcA6** [comment]
Should the language be more in line with the fact sheet published within [this article](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6590954/)? (the fact sheet is from the VA and was tested with Veterans) 

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/443910de-1bd6-4429-bdd6-7e81a8d24f50)

I feel the verbiage isn't adequately explaining to veterans what updating birth sex means in terms of the health care implications. They certainly have the right to make this change, but as explained in the article, this should be an informed decision process. 

Take a second to read the case examples in the article I shared above, or ideally the entire article, there is nuance here that doesn't feel fully reflected in the copy.

**Comment by andaleliz** [comment]
@mtcA6, I love that you're thinking about being thorough with this sensitive topic. IMO, helping Veterans evaluate whether or not to update their birth sex in their health records feels out of scope for the FAQ on the personal information page of the profile. I think anyone wanting to make this change has likely put a LOT of thought and research into their sex and gender identity, and the call to action for them to reach out to an LGBTQ+ coordinator to start the process will set them on the right track.

Of course, that's just my opinion. @DanielleThierryUSDSVA I'm curious what you think about Travis's question.

**Comment by Samara-Strauss** [comment]
Hi all -- I am going to email Lexi and ask for their thoughts on the copy. They'll be able to guide us on appropriate level of detail. I'll cc everyone for transparency.

**Comment by DanielleThierryUSDSVA** [comment]
Hi there. Catching up on this thread and wanted to add my perspective here. 

- I don't think the profile is the right place for us to offer health safety guidance. Our job with this content is to make sure folks understand how we use the information, who has access to it, and how to change it in other places if they need and want to. This is an impactful decision for all the reasons noted in the article. But we're not offering people the ability to change their birth sex in their records here in the profile. We're simply pointing them to the process for doing so, and the experts who can help them make the decision.

I'd also like to get Lexi's perspective here. But, if they do think we should provide health safety information about the actual decision around changing birth sex, I don't think the solution is to try to add that information here. I could see 2 potential ways of addressing this:

1. Pull our content back even more and simply connect folks to their LGBTQ+ Veteran coordinator so that they can discuss this very personal decision with a dedicated health care provider. So something like this:

- **Some VA health care systems send communications based on the birth sex on your original birth certificate.** If you'd like to discuss changing your birth sex from what was listed on your original birth certificate for health communications, contact your VA health facility's LGBTQ+ Veteran care coordinator. They can help you understand the process.

2. Or, link out to more information about changing your birth sex in your health records that lives within a health-specific space and is available should someone want to read more. To Pam's point, we should default to assuming that people are making decisions about their own gender and records carefully. We can offer links to more information should someone need or want it. But we shouldn't assume we're sharing information that they don't already know.

Hope this is helpful!

**Comment by Samara-Strauss** [comment]
I'm so glad we checked in with Lexi,. They had the following response, one which I don't think any of us were expecting:

> Unfortunately, these instructions are only true for Veterans at facilities that use CPRS – it’s very different at Cerner facilities. I like linking them to local resources to help them figure out the process! We haven’t updated our fact sheet on this because our office recently chaired a work group on Birth Sex and Gender Identity across the enterprise, so expect that the guidance will change soon. 

I've sent along this copy of Danielle's to Lexi for review. I think it might be best to refer people to their local facilities since processes could be different depending on where they are:

> **Some VA health care systems send communications based on the birth sex on your original birth certificate**. If you'd like to discuss changing your birth sex from what was listed on your original birth certificate for health communications, contact your VA health facility's LGBTQ+ Veteran care coordinator. They can help you understand the process.

**Comment by DanielleThierryUSDSVA** [comment]
Agree! Thanks, @Samara-Strauss!

**Comment by mistymg** [comment]
Following along with this as it affect mobile app. @andaleliz Where will this new content live? Is it going to be in addition to the content in this expandable section:

**Comment by andaleliz** [comment]
@mistymg it will replace the content in the FAQ. Here's the full text so far, pending Lexi's review.

@Samara-Strauss I'm going to reply to the email you sent to Lexi with this full text, so it's clear.

---

Sharing your gender identity in your VA.gov profile is optional. If you get health care at VA, this information can help your care team better assess your health needs and risks.

Here's what else to know about sharing your gender identity in your VA.gov profile:
- **If you want to share your gender identity in your health records only**, talk with your health care team. Any information you share in your profile goes into your VA records beyond health care. VA staff outside of the health care system may be able to read this information. We follow strict security and privacy practices to keep your personal information secure.
- **Some VA health care systems send communications based on the birth sex on your original birth certificate.** If you'd like to discuss changing your birth sex from what was listed on your original birth certificate for health communications, contact your VA health facility's LGBTQ+ Veteran care coordinator. They can help you understand the process. 
[Find your VA health care facility's contact information].

**Comment by andaleliz** [comment]
@mistymg I'm sorry - we call that an FAQ. It not different than the screenshot you shared above and the content in the additional info component will change to what I pasted in my earlier comment (assuming Lexi is good with it).

**Comment by Samara-Strauss** [comment]
Latest update: Lexi has asked that we wait for Anna to come back next week to review the copy.

**Comment by andaleliz** [comment]
I haven't heard any more on this, which isn't surprising given the holidays. I set a reminder to follow-up on the email chain on 1/9, when I'm back, if this hasn't moved forward when I get back.

**Comment by andaleliz** [comment]
Update: we've heard from Anna, and I met with Danielle today to review another revision of the content.   She is going to spend some more time with it tomorrow, and hopefully provide us a version we can use to update the content ASAP.

As a longer term solution, we're going to create a resources and support page with this content, and shorten what's in the FAQ. Then, we'll include a link to the R&S page in the FAQ. 

The current guidance is already pretty long, and we still need to get info about how veterans can update this on the VBA side of the house so it will continue to grow.

I'm hoping we'll have updated FAQ content from Danielle before the end of the sprint so we can close this ticket and send it to FE for implementation.

**Comment by mtcA6** [comment]
@andaleliz could you make sure to share that in the cross team sync on the 22nd.

**Comment by andaleliz** [comment]
@mtcA6 if I attend, I surely will! I can't always make it to those meetings. Misty, from the mobile team, is following along with this ticket so I know she will get the update.

Anyone can post updates in the #cross-team-sync channel outside of meetings too, fwiw.

**Comment by mistymg** [comment]
Yepp! I'm lurking here ;) @andaleliz You let me know when Danielle has approved of final copy and I can spin up a ticket for mobile app.

**Comment by andaleliz** [comment]
Danielle provided updated copy to go into the FAQ on the profile page. It's long, but I'm ok with that knowing we're moving to an R&S page down the road.

I've sent to to Anna and Lexi and I think we are good to go assuming they don't have any serious concerns. I'll leave this ticket open for another day while we wait to hear back from them.

I've updated the mock-ups in [Figma](https://www.figma.com/file/qfyUmEOVawplgrEKYKFp0f/Profile---Personal-information?type=design&node-id=0-17&mode=design&t=JjkBzaQ1qv4vzErj-11) and [Sketch](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/5n1mDYp) (not sure exactly which one Adam wants to work from)

Here's the content, @mistymg. Once you see this ticket closed, that'll be your cue that this is good to go.

It’s your choice whether or not to share your gender identity in your [VA.gov](http://va.gov/) profile. Here’s what to know before you share:

- **If you get health care at VA**, knowing your gender identity can help your care team better assess your health needs and personalize your care.
- **Any information you share in your profile goes into VA records that non-health care staff may also have access to**. We follow strict security and privacy practices to keep your personal information secure. But VA staff outside of the health care system may be able to read this information.
- **If you want to share your gender identity in your health records only,** don’t add this information to your [VA.gov](http://va.gov/) profile. Talk with your health care team instead.
- **Some VA health care systems send communications and make recommendations based on the birth sex on your original birth certificate**. If you’d like to discuss changing your birth sex from what was listed on your original birth certificate for health communications, contact your VA health facility’s LGBTQ+ Veteran care coordinator. They can help you understand the process.
[Find your VA health care facility’s contact information]

**Comment by mtcA6** [comment]
@andaleliz  I think we've taken this ticket as far as we can, but I want to highlight, we've had and [R&S article request ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36751)out there for 3 weeks shy of 2 years. 

Veterans have already mentioned the need for additional info on the gender identity field [as mentioned in this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36751#issuecomment-1222517397). Any thoughts on how to get momentum on #36751?

**Comment by DanielleThierryUSDSVA** [comment]
@mtcA6  That request was part of a different conversation and has been on hold because this is a complex and sensitive topic and there are broader considerations there. This request that we're talking about in this ticket is coming out of a consideration around the amount of information in this Q&A. Thanks.

**Comment by mtcA6** [comment]
@DanielleThierryUSDSVA so should be break down 36751 into component parts, some of that revised personal information page did launch. Sexual orientation and Pronouns being paused probably shouldn't block the launching of a R&S page for everything else, of which, gender identity formed a part.

**Comment by DanielleThierryUSDSVA** [comment]
@mtcA6 I'll assess the ticket when we can look at this more.

**Comment by andaleliz** [comment]
@mtcA6 we can move this ticket to validate for FE work, and then you can close it out once you've done what you need on your end to get the FAQ updated on the page.  I added a comment to the open R&S request about this just to link it all together. I trust Danielle and her team to worth with us to figure out what all we need to do for R&S pages once they have a chance to get to this.

**Comment by Samara-Strauss** [comment]
Regrouped with Danielle in Slack to make sure we are clear on next steps re: a Resources & Support article:

- We should leave [this existing ticket open for now](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36751). Danielle would like it to remain as-is for later review. We do not need to break down the ticket at this point in time.  
- Nothing else is needed from the auth exp team at this time.

**Comment by mtcA6** [comment]
#74837 follow on ticket
