### ISSUE TITLE
[CAIA Super Epic] Pension 527EZ Form Updates from Benefits & Claims | Non-Disability Experience

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#66578]
## About your team

- Team name: Benefits and Claims | Lifestage Benefits Crew | Non-Disability Experience
- OCTO-DE product owner: Emily Theis
- Product manager: Laura Steele
- Designer: Fiorella Glavez
- Accessibility specialist: none
- Content writer: none
- Slack channel: benefits-non-disability
 
### Describe what you need in a few sentences:
- We are updating the 527EZ pension form to align to the most recent version of the paper form. 
- This includes adding missing fields and removing depreciated fields. 
- **The current online form** will be (or has been) deactivated to prevent Veterans from submitting claims online that cannot be processed without additional development.
- **So there is a sense of urgency in getting the updated version of the form back online**.

### Future CAIA Support Needed
A task has been created @coforma-terry relating to the future CAIA support that will be needed [based on @steele-lm 's note in DSVA Slack on 10/5/2023](https://dsva.slack.com/archives/C01K37HRUAH/p1696526168989509?thread_ts=1695933581.165529&cid=C01K37HRUAH).

> For some additional context, after the initial updates are released, I anticipate that the new team that is taking over the pension form will be updating all the outdated form components, improving form flow, and addressing outstanding accessibility issues on old pages, so there will most likely be additional CAIA review cycles in the future.

**(New 10/5/2023) Pension Product Lead:** Vicky Bellissimo, Platform/Platform Content - Product Manager [Ad Hoc]

### Which are you doing?
- [ ] **Launching a new** page, tool, form, or app
- [x] **Making changes** to an existing page, tool, form, or app

### Types of Support
What areas does your team need support in? Check all that apply.
#### Content
- [ ] Collaboration on content written by your team’s dedicated content writer 
- [x] Collaboration on content if your team does not have a dedicated content writer
#### Accessibility
- [x] Accessibility review of wireframes and/or prototypes
- [ ] Accessibility issue (general request)
- [ ] Accessibility PDF review request
- [ ] Accessibility user research support ([submit a separate, additional request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name))
- [ ] DST component or pattern 
- [ ] Something else 
#### IA
- [x] User Flows
- [ ] Page placement
- [ ] URLs
- [ ] Breadcrumbs and Left Nav placement
- [ ] Redirects
#### Multilingual content
- [ ] Translating content
 
## Timeframe
_We guide and work alongside teams across nearly every OCTO digital product. We also work with partners across VA to lead content migration and manage all unauthenticated content on VA.gov. And we're always working to expand the VA.gov content style guide and our IA and accessibility documentation. We need to prioritize all intake requests based on our overall workload and VA and OCTO priorities._

_Tell us about your product's timeline. And we'll work with you to meet timeline needs as best we can._

### Have you worked with CAIA before? 
  - [x] Yes
  - [ ] No

### What's your team’s next step and its timing?
- **Our next step is** implementing the feedback from Design Intent and finalizing wireframes.
- **Provide date if available**: 10/04/2023

#### Timing for your next step: 
  - [x] Next week
  - [ ] This month
  - [ ] Next month
  - [ ] This quarter
  - [ ] Next quarter
  - [ ] 6 months
  - [ ] 1 year

### Is this timing related to a specific event or Congressionally mandated deadline?
  - [ ] Yes
  - [x] No

### If you're conducting research, when is that starting? Research to improve the Veteran-facing experience will be conducted after the form is back online and functioning.
**Provide date if available:** xx/xx/xxxx
  - [ ] Next week
  - [ ] This month
  - [ ] Next month
  - [ ] This quarter
  - [ ] Next quarter
  - [ ] 6 months
  - [ ] 1 year

### Will you release this new product incrementally (for example, release to 25% of users to start)? 
  - [ ] Yes
  - [x] No
 
**Note**: _If you checked yes, we’ll reach out to discuss details about the content in the react widget (we use these widgets to display entry points for new products to a certain percentage of users who visit our static pages)._

  
### When do you expect to launch your product to 100% of users?
- **We expect to launch our product to 100% of users on:** ASAP, December 2023 at the latest
  
### Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No
 
#### Please provide the link to your Collaboration Cycle ticket: 
- **Ticket (number)**: #65250 
- **Collab. Cycle Ticket Opened (date)**: 09/08/2023
 
#### Please check all of the phases in the Collaboration Cycle you have completed: 
- [x] Design Intent
- [ ] Midpoint Review
- [ ] Staging
 
##### Design Intent
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [x] Already completed, no assistance needed
- [ ] Unknown at this time
##### Midpoint
- [x] Accessibility
- [x] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
##### Staging
- [x] Accessibility
- [x] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
  
## Supporting artifacts
*Please provide links to supporting artifacts as available.*
- **Product outline**: [Pension Online Form Reactivation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- **User flows**: [Mural of user flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695069026901/50b83f710f1cd2f1f7f3bb63553c349ef90d402a?sender=u4e1fb0748c58370c03f33409) | [Mural of form flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u0e8ac1d6d7681bb7e1b80558)
- **Prototype or mockups**: [Pension redesign](https://www.sketch.com/s/75b363db-6be8-4b7e-8655-8f12f1ea5554) | [Pension entry points](https://sketch.com/s/42d1dd07-4ed9-4330-b732-c2a8f183e6f3)
- **Content source of truth**: [21P-527EZ paper form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- **Research plan:** N/A
- **Any epics/issues that may be helpful**: [Update Pension 527 Online Form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63349)
- **Link to testing accounts** (please do not paste them in this ticket): [527EZ test accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)

### Have you already worked with someone from OCTO leadership?
- [ ] Danielle
- [ ] Beth
- [ ] Mikki
- [ ] Martha

### How do you plan to work with us on this request?
- [ ] I’ll take this to Beth or Danielle’s office hours.
- [ ] I’d like to schedule time to talk about this.
- [x] Let’s work async and meet as needed.
- [x] Schedule a kick-off call with your team and CAIA for your project **(Completed 10/3/2023)**
 
### Accessibility Help in Slack
The [#accessibility-help channel](https://dsva.slack.com/archives/C8E985R32) in the DSVA Slack, is also available to you as a resource. Everyone is welcome to ask questions or get help from our a11y (accessibility) specialists. Tag `@Terry Nichols` to get a11y help asap.

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag `@Terry Nichols`.**

- If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
- If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)
 
 - If you are creating an [experimental design,](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) please [also contact the DST. ](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)

- If you are requesting [a11y support for user research,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name) please complete this form, next. 

```[tasklist]
### a11y Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/67037
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/67293
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/66842
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/77464
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/67343
- [ ] [a11y support] Staging Prep Assistance: Pension 527EZ Form Updates from Benefits & Claims | Non-Disability Experience
```

```[tasklist]
### CAIA General Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/66832
- [ ] [CAIA Support] Terry to share deliverable and mark this task done as a test in GitHub Beta Tasklists
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/67037
```

```[tasklist]
### Content Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/67006
```

```[tasklist]
### IA Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/67800
```

```[tasklist]
### Related Collab Cycle Ticket(s)
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65250
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/73379
```

**Comment by steele-lm** [comment]
@fiorella-io @vbellissimo @sortizsh @aplatt-coforma

**Comment by katherine-fung** [comment]
Hi @vbellissimo @mayacoforma, 

I'm reviewing the Sketch file for the entry points for pension reactivation. There are a few other entry points that we plan to deactivate, and will need to reactivate, which aren't in the Sketch file. We have an updated IA spec to share with your team: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/pension-form-reactivation.md#nav 

We'll need to restore items #7, 8, 9 under the section "Entry points" when we reactivate the pension form. We don't need to change the copy from what's currently live/the screenshots in the IA spec. On reactivation, the copy should change back to what it is now.

**Comment by vbellissimo** [comment]
@katherine-fung , thanks for that heads-up. Can you provide a link the Sketch file you are referring to?

**Comment by katherine-fung** [comment]
@vbellissimo this is the Sketch: https://sketch.com/s/42d1dd07-4ed9-4330-b732-c2a8f183e6f3

**Comment by jennymayoco** [comment]
Hi @vbellissimo, referencing [IA tracker ticket #67800](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67800) here.

**Comment by jennymayoco** [comment]
Hi @vbellissimo - we had additional IA feedback relating to the base URL`https://www.va.gov/pension/application/527EZ`. As part of an IA audit https://github.com/department-of-veterans-affairs/va.gov-team/issues/58341 we've recently done on the Pensions hub page, we've identified that the form URL isn't up to standards. The reactivation phase could be an opportunity to get this URL up to date. This is something that we could document in the [current IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/pension-form-reactivation.md). What are your thoughts? Apologies for not flagging this earlier

**Comment by vbellissimo** [comment]
Hi @jennymayoco Yes, please. I'd love to learn and document how we can fix this for when we're ready to relaunch. Thank you for the heads-up.

**Comment by jennymayoco** [comment]
@vbellissimo awesome! For context, the standard for form URLs is typically 2-3 words followed by the form number, so something like `name-name-name-form-number`. An example of this can be `www.va.gov/supporting-forms-for-claims/lay-witness-statement-form-21-10210/`.

So I'm aware of timelines, by when should we share a proposed URL?

**Comment by vbellissimo** [comment]
@jennymayoco Got it. If you have a recommendation by the end of this sprint or next, I think that would work for us!

**Comment by jennymayoco** [comment]
@vbellissimo thank you for this info! Our OCTO lead Mikki is currently at an offsite so we might not get feedback on this in time for this sprint. What is the end date for the next sprint?

**Comment by vbellissimo** [comment]
@jennymayoco, the end of our next sprint is Dec 6. I'd also like to touch base with our OCTO lead, Emily Theies, as well, to decide whether this would be considered part of our MVP or not. Depending on the LOE for our engineering team, we may have to take the recommendation as a fast-follow after we relaunch the form. We're expected to relaunch the form by January 2024.

**Comment by jennymayoco** [comment]
@vbellissimo totally understandable! We agree this can be a change made in the next version if not within scope for the MVP. Let me know next steps and I'll keep https://github.com/department-of-veterans-affairs/va.gov-team/issues/67800 open in the meantime to track updates for this version

**Comment by jennymayoco** [comment]
Hi @vbellissimo! I wanted to check in and see if there were any updates on the URL timeline before the end of this upcoming sprint so we can be sure to provide the proposed URL in case it's in scope for the MVP.

**Comment by vbellissimo** [comment]
Hi @jennymayoco, I've been speaking with our VA enabling team about this. Due to our MVP relaunch timeline coming up soon (Jan 2024), we will likely not be able to incorporate the URL structure recommendations in time by then. However, we would love to get a head start on **knowing** what the recommendations actually are so we can plan for it right after our relaunch. With that said, we welcome your recommendation plan. Does this context help your timeline to provide this information? In other words, we won't need the URL structure recommendation between now and early January 2024, but perhaps later in January or February would be ideal to have.

**Comment by jennymayoco** [comment]
@vbellissimo thank you for your thorough response! Yes, this makes total sense and we are onboard with updating the URL until the next version. I've documented the proposed URL in the [IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/pension-form-reactivation.md#urls-and-breadcrumbs). Once the team is ready to move forward with updating the URL, we can connect to confirm the proposed URL and then work with PW to implement redirects so that folks don't get an error page if using the old URL. Let me know if there's any questions! Happy to chat closer to the next version to confirm next steps.

**Comment by vbellissimo** [comment]
Excellent, putting this on our radar. Thank you @jennymayoco
