### ISSUE TITLE
Draft and Revise OKRs for Strategy Roadmap

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#66600]
## Context:

We have a number of OKRs for Login.gov Adoption that have been drafted over the past few months. We need to refine them as we work on the Strategy Roadmap and figure out how to share them externally. Some questions to ask as we complete this:
- Should we present our OKRs in the roadmap? Or just the Objectives? Should we keep it higher-level?
- Should we break out OKRs for each phase? Include training and support objectives?

## Acceptance Criteria/Def of Done

DEF of DONE:

- [x] Revise current OKRs for both Campaign and IPP
- [x] Draft OKRs for each phase of Login.gov Adoption project
- [x] Review with Leads
