### ISSUE TITLE
(Johnny) Present audit findings of Dev Docs to Product team for SME mapping

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#66620]
## Info

- [Spreadsheet of pages audited](https://docs.google.com/spreadsheets/d/1PPhlba7PiCTWkJUWKHxH36rck0lfKtBSjSpqrCCBxv0/edit?usp=sharing) under the Developer Docs section of the Platform website.

## Tasks

- [x] Familiarize yourself with the audit/spreadsheet
- [x] Schedule meeting with Lainey Trahan, PM of Platform Product team
- [x] Present her with our Developer docs audit findings, spreadsheet above.
- [x] Request her team's help to map out SMEs to [each of the pages on the spreadsheet](https://docs.google.com/spreadsheets/d/1PPhlba7PiCTWkJUWKHxH36rck0lfKtBSjSpqrCCBxv0/edit?usp=sharing).

## Acceptance Criteria

- [x] Content PM will have reviewed the audit findings with the Platform Product team.

**Comment by johnny-jesensky-adhoc** [comment]
Next step on this - Johnny and Lainey to meet on Thursday, November 9th to outline criteria for prioritizing these pages, and delicate them out to engineers on other teams.
