### ISSUE TITLE
[bug] Look into VA900 errors on SharePoint request

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#66630]
## Issue Description
The most common error we see when submitting the FSR is a VA900 (generic API error) with the title `Common::Exceptions::BackendServiceException` from the SharePoint file upload. We should check to see if this is something we can resolve or better handle.

Link to sentry issue: http://sentry.vfs.va.gov/organizations/vsp/issues/223914/?environment=production&project=3&query=is%3Aunresolved+sharepoint&statsPeriod=14d

---
## Tasks
- [ ] Attempt to replicate issue or identify cause
- [ ] Review options regarding issue

## Acceptance Criteria
- [ ] Draft ticket for future plan to resolve or better handle this error 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
