### ISSUE TITLE
ARM Nav & Search - User Test - Collab Cycle + Recruit

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#66661]
## Issue Description
User test for ARM experience including Veteran representative engagement questions as well as VA.gov representative experiences of:
1. Navigation
2. Search
---
## Tasks
- [x] Request research review
- [x] Update user test to reflect collab cycle edits
- [x] Kick-off with Perigean
- [x] Set-up Enjoy HQ project
- [x] Create notetaker template
- [x] Kick-off with notetakers
- [x] Conduct pilot session
- [x] Kick-off with observers
- [x] Create interview Zenhub ticket
---
## Acceptance Criteria
- [x] Interviews scheduled

**Comment by jfinnerty13** [comment]
@oddball-lindsay this will move to the next sprint - thanks!

**Comment by jfinnerty13** [comment]
Research request approved - waiting on Perigean kick-off and recruitment.

**Comment by jfinnerty13** [comment]
Created observer and notetaker guidelines for upcoming study
https://docs.google.com/document/d/1SxNZtxHmZSb4HiKENurCH3xBA1LDyiJSsl12rkg0Hh8/edit?usp=sharing
https://docs.google.com/document/d/1zaVUM-bPtYVHZvWkv7j3aPPlJS6iKfHWA-9QghAE_jI/edit?usp=sharing

Kick-off with Perigean and got the thumbs up - recruitment in progress

Created sign-up sheet/ https://dsva.slack.com/canvas/C063S3ZFELT

**Comment by jfinnerty13** [comment]
Kicked off with notetakers, launched sign up sheet in private Slack channel, and added in Zenhub ticket for interview week
