### ISSUE TITLE
Implement CAIA changes on Pension Review Page and Widget 

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#66663]
## Issue Description
_Stakeholders have requested some additional copy changes to the widget that will appear on the "how to apply" and form review page for the pension form deactivation. There is new copy on each page, no updated design or functionality. See Fiorella with questions. Original work on the pension widget was done in #64136 and review page in #63626._

CAIA changes are located within the Sketch files for the Review pages and Widget: 
- Review Page (authenticated) https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/a/JAvlVl9
- Review Page (no draft claim) https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/a/vR1dAd3
- Widget How to apply (authenticated) https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/a/9lxzZLM
- Widget How to apply (unauthenticated) https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/a/y95jwGo

---
## Tasks
- [x] Update copy in pension "how to apply" widget
- [x] Update copy in pension "review page" widget

## Acceptance Criteria
- [ ] Copy updates appear in pension "how to apply" widget
- [ ] Copy updates appear in pension "review page" widget
- [ ] Fiorella signs off on design implementation

**Comment by fiorella-io** [comment]
The last time we met with CAIA (some weeks ago), they had a concern that when we flip the switch, and make the digital form unavailable, and before the redirects to the new page, some people could be on any of the entry points pages, and click on the digital form link and not work. Fred suggested applying some logic to the widget, and here's the design link for that interim state for [Pension](https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/a/Oe272Gv) and [Burial](https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/a/Oe279l4)

**Comment by fiorella-io** [comment]
And [here's the thread](https://dsva.slack.com/archives/C057W3N9K2S/p1696440712254349?thread_ts=1696440434.480739&cid=C057W3N9K2S) of Katherine from CAIA providing feedback

**Comment by zack** [comment]
Hi @fiorella-io, sorry I'm quite confused. Is that related to this ticket? I thought we talked about this ticket just being copy changes to the 2 pages across different states. Where does redirect logic for 404 pages come into this ticket?

**Comment by fiorella-io** [comment]
@zack It was during a meeting we had with CAIA's content team. They had a concern regarding the order we were going to take of the deactivation of Pension and Burial and the redirection of the traffic from all the entry points to the How to apply page for each. Fred suggested he could add some logic to the widget to show the link to the digital form for Pension and Burial and whenever we pulled the plug to deactivate the forms, it would switch back to the designs linked in this tickets. So the new state for the widget is what I linked on my first comment. @steele-lm can clarify if I missed anything. 

Pension and Burial and becoming unavailable. 

Let me know if it makes sense. I'm also free to connect




 Pension and Burial, when we deactivate
