### ISSUE TITLE
Bugfix: Unit test stress test runs all tests when no tests are selected related to files in PR

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#66672]
## Issue Description
The goal of the unit test stress test is to only run when there are tests related to the code being pushed. If non-app code is pushed, the unit test stress test should skip. Right now, however, it runs ALL the tests instead of a select batch.

---
## Tasks
- [ ] Diagnose why the unit test stress test runs all tests when no tests are selected
- [ ] Implement a fix to correct this behavior.

## Acceptance Criteria
- [ ] The unit test stress test correctly skips when no files are needing to be stress tested.

**Comment by CBonade** [comment]
This is in a PR that's already approved just awaiting a passing CI run. Rebased from main should fix the current issues it was having getting through. Once merged will move this to review.
