### ISSUE TITLE
Call Center Integration with development teams

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#667]
## High Level User Story
As a member of the triage team, I need need to know when the call center report an issue so I can create an internal ticket to be prioritized and fixed within the development team.

## Hypothesis/(es)
If we create an intake process for issues logged in the call center system, we expect the development teams to be able to resolve issues reported by users of va.gov directly.

## Goals
We want to see a communication line open (back and forth) between the triage team and the call centers in order to resolve tier 2/3 issues.

## Objectives
- [ ] Document the call center process
- [ ] Document what tools the call centers are using
- [ ] Provide a recommendation for an "integration" to resolve tier 2/3 issues

## Definition of Done
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Epic`**
