### ISSUE TITLE
Spanish translation for PACT Act 9/30 changes 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#66706]
## Issue Description
We made changes to the [PACT Act and your VA benefits](https://www.va.gov/resources/the-pact-act-and-your-va-benefits/) page in connection with the 9/30 deadline. We need to make these same changes on our Spanish page.
 
## Tasks
- [ ] Create Word doc of changes (Ana)
- [ ] Send to State Department (Randi)
- [ ] Update Drupal page (Ana)
- [ ] Review (Megan)
- [ ] Publish (Megan)
- [ ] Send to State Department for QA (Randi)

## Acceptance Criteria
- [ ] Changes are live on the Spanish PACT Act page

**Comment by RLHecht** [comment]
@ABeltran77 Here is the content back from the translators. Thanks!

[LS-2023-0118394-SPA-FINAL_PACT Act 9.30 deadlines changes.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12831537/LS-2023-0118394-SPA-FINAL_PACT.Act.9.30.deadlines.changes.docx)

**Comment by ABeltran77** [comment]
@RLHecht @megzehn Content has been added to Spanish page.

**Comment by megzehn** [comment]
Thanks, @ABeltran77! Confirming I reviewed and published these changes.

**Comment by megzehn** [comment]
@RLHecht this page is ready for you to send to the QA team.

**Comment by RLHecht** [comment]
@ABeltran77 Here's the QA back from the State Department. Please make these changes today. Thanks!

[LS-2022-0118394-A-LQA notes-v1-PACT Act special enrollment period content and 9.30 deadlines.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12884226/LS-2022-0118394-A-LQA.notes-v1-PACT.Act.special.enrollment.period.content.and.9.30.deadlines.docx)

**Comment by ABeltran77** [comment]
@RLHecht Two changes have been made as there is nothing to change due to page not having a banner alert. Also, i see the reference they ussed for the correct dollar amount. This is always a point of confusion, unfortunately.  I'll keep the reference for further use.

**Comment by RLHecht** [comment]
Thanks so much @ABeltran77. We don't want to risk introducing inaccuracies or confusion, so if there's ever anything that may be a point of confusion—or if you have any hesitation at all about any content they sent back—please flag it for the state department and ask before changing.

**Comment by megzehn** [comment]
Thanks, @ABeltran77! Confirming I reviewed and published these changes.

**Comment by ABeltran77** [comment]
@RLHecht Will do! Thanks @megzehn
