### ISSUE TITLE
Tagalog translation for PACT Act 9/30 changes

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#66709]
## Issue Description
We made changes to the [PACT Act and your VA benefits](https://www.va.gov/resources/the-pact-act-and-your-va-benefits/) page in connection with the 9/30 deadline. We need to make these same changes on our Tagalog page.
 
## Tasks
- [ ] Create Word doc of changes (Ana)
- [ ] Send to State Department (Randi)
- [ ] Update Drupal page (Ana)
- [ ] Review (Megan)
- [ ] Publish (Megan)
- [ ] Send to State Department for QA (Randi)

## Acceptance Criteria
- [ ] Changes are live on the Tagalog PACT Act page

**Comment by ABeltran77** [comment]
@RLHecht 
[ThePACTActandyourVAbenefits_Tagalog_AB.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12784732/ThePACTActandyourVAbenefits_Tagalog_AB.docx)

**Comment by RLHecht** [comment]
@ABeltran77 Here is the content back from the translation team.

[LS-2022-0118394-TAG-FINAL_PACT Act 9.30 deadlines changes.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12831546/LS-2022-0118394-TAG-FINAL_PACT.Act.9.30.deadlines.changes.docx)

**Comment by ABeltran77** [comment]
@RLHecht @megzehn Content has been added to Tagalog page.

**Comment by megzehn** [comment]
Thanks, @ABeltran77! Confirming I reviewed and published these changes.

**Comment by megzehn** [comment]
@RLHecht this page is ready for you to send to the QA team.

**Comment by RLHecht** [comment]
@ABeltran77 we got back the QA for this page and they have a few changes. Could you please make these and Megan can publish? Thanks!



[LS-2022-0118394-LQA Notes-v1-TAG__PACT Act 9.30 deadlines changes.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/13228683/LS-2022-0118394-LQA.Notes-v1-TAG__PACT.Act.9.30.deadlines.changes.docx)

**Comment by ABeltran77** [comment]
@RLHecht changes have been made, thank you @megzehn ...ready to review and publish
