### ISSUE TITLE
Validate BQ - Staging Review issue tickets

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#66700]
## User Story
As a Governance team member, I want to the data that feeds the team's Domo dashboard cards to have been validated so that I can accurately interpret the value that the cards have.

Assignee: @it-harrison  
Peer Reviewer: @allison0034 

## Description
Governance team is working to add cards to its Domo dashboard that rely on milestone data. The milestone data was added programmatically and from preliminary Domo visualizations it seems that some tickets did not receive milestones. We need to make sure that the data is complete to facilitate Domo work and to ensure that the final results are accurate and useful to those who visit the Dashboard.

## Impacted Artifacts
The Domo dataset "[BQ - Staging Review issue tickets](https://va-gov.domo.com/datasources/6c15f710-418f-4624-94d3-fffa43feda5c/details/overview)"

## Tasks
- [ ] make sure all tickets in the BQ table have the proper milestone
- [ ] make sure all epics are in the BQ table

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] The BQ dataset is accurate

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
@allison0034 I have looked at all Staging Reviews from Q3 2023 and compared with the data in Domo. Here are my findings:

* DST Staging Reviews are not represented, I believe because the child tickets do not have "Staging" labels
* there was [a Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60829) that had no child tickets because no issues were found and therefore simply does not appear in the Domo data-set
* there was [an extra Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52672) from the Lovell review included due to the fact that issues were copied over from a different repo so there was a mismatch between the open date and the actual date when the Staging Review was held.

There might be other one-off issues like the Lovell review, but without going through all the data it will be hard to find. I think the more important points are DST tickets and Staging Reviews with no issues. Adding labels to the DST issues should be fairly easy, although I need to talk to Analytics to make sure that the "Staging" label is all that needs to be added. As for the Staging Reviews with no issues we might need to brainstorm a solution - it might be necessary to include the Collab Cycle Kickoff Ticket so that we can determine which ones have no child tickets.

@shiragoodman it wont be possible to fix all these issues by end of sprint; can we close this ticket and address them in another ticket?

**Comment by allison0034** [comment]
Thank you @it-harrison

**Comment by shiragoodman** [comment]
Thanks for the updates, @it-harrison . Yes, we can close this ticket today and address the issues in new tickets. 

For DST Staging Reviews, it sounds like the simplest solution is to add the `Staging` label. Do you agree? 

For Staging Reviews that have 0 findings identified, I think there might be a few different solutions. We have our weekly initiative meeting at 2pm ET today - maybe we can discuss ideas then.

and Re Lovell, yes... that ones going to be off. I'm not sure how to handle that one.. any ideas? Maybe we can discuss today as well.

**Comment by shiragoodman** [comment]
@it-harrison actually, I'm having 2nd thoughts on adding the Staging label to DST Staging Review tickets.. we don't document our findings for DST SR's in alignment with the VA.gov Experience Standards, so I'm not sure what value we would get (at this time) from bringing in that data. Let's discuss at today's meeting.

**Comment by shiragoodman** [comment]
Notes from 10/10:

> - DST Staging Reviews are not represented, I believe because the child tickets do not have "Staging" labels 

- Team agreed to not make any changes at this time since DST findings are not in alignment with the Exp Stds

> - there was a Staging Review that had no child tickets because no issues were found and therefore simply does not appear in the Domo data-set

- Many different solution options discussed. Trying to find the path of least resistance. Ideally, the easiest path would be to include a new ticket that could be pulled in with the existing data set that signified "No issues found". We would need to create a unique label and ensure that the ticket is created on the date that the Staging Review took place, so it's incorporated into our Post-Meeting Staging Review process.


> - there was an extra Staging Review from the Lovell review included due to the fact that issues were copied over from a different repo so there was a mismatch between the open date and the actual date when the Staging Review was held.

- per Ina, limitation of relying on the "open date" as a source of truth for when things' happened.
