### ISSUE TITLE
Troubleshoot inconsistencies between E2E Allow list dataset and published page on platform website.

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#66729]
## Issue Description
The published E2E disallowed specs list is not in sync with the actual dataset. There's numerous examples cited in a support thread where deleted specs are still appearing and specs that have been re-enabled are still showing disallowed on the list. These lists must be in sync so the users understand what is needing to be fixed. We also need to correct this before launching the unit test list that uses the same script, to avoid doubling the problem.

Support thread for context and examples: https://dsva.slack.com/archives/CBU0KDSB1/p1696263748763819
---
## Tasks
- [x] Investigate why disallowed specs that are reenabled are not showing their correct status after being reenabled.
- [x] Investigate why deleted specs are not cleaning up even though a cleanup script has run.

## Acceptance Criteria
- [ ] The published allow list is in sync with the dataset.

**Comment by CBonade** [comment]
I believe this has been resolved by the overhauls to the E2E selection process as I can no longer find any inconsistencies. The only inconsistencies left that I see are related to publishing time of platform website vs real time updates.
