### ISSUE TITLE
Community pharmacy label

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#6673]
## Goal
_What outcome(s) do we want to see?_
Label change for Community care pharmacies

![image](https://user-images.githubusercontent.com/55411834/76236269-aa42cc00-61e9-11ea-81ec-b05139704431.png)

## Tasks
- [ ] Change Facility Type label from Community pharmacies (in VA's _network)_ to read _Urgent care pharmacies (in VA's network)_, per the Office of Community Care

## Acceptance Criteria
- [ ] User can select Urgent care pharmacies (in VA's network) under Facility type
- [ ] No Service type is available when Urgent care pharmacies (in VA's network) is selected as Facility type

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
