### ISSUE TITLE
Copy Updates to Burial and Pension Widgets

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#66731]
## Issue Description
_Stakeholders have requested some additional copy changes to the widgets that will appear on the "how to apply" and form review pages for when the pension and burial forms are deactivated. Original work on the pension widget was done in #64136 and burial widget was done in #64140._

---
## Tasks
- [ ] Update copy in burial "how to apply" widget
- [ ] Update copy in burial "review page" widget
- [ ] Update copy in pension "how to apply" widget
- [ ] Update copy in pension "review page" widget

## Acceptance Criteria
- [ ] Copy updates appear in burial "how to apply" widget
- [ ] Copy updates appear in burial "review page" widget
- [ ] Copy updates appear in pension "how to apply" widget
- [ ] Copy updates appear in pension "review page" widget
---

**Comment by zack** [comment]
@steele-lm do we have the copy for this?

**Comment by steele-lm** [comment]
@zack Not yet! Hoping to have final copy within the next 1-2 days.
