### ISSUE TITLE
[FE] 10-10EZR: Add entry in Content Build registry for the React Application

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#66739]
## Description
In order to get the React Application for the 10-10EZR to build on the appropriate page template, we need to register it in the Content Build Repo. We need to take the following information and correctly input it in the registry entry:
- App Name - `10-10EZR Update health benefits info form`
- Entry Name - `ezr`
- root URL - `/my-health/update-benefits-information-form-10-10ezr`
- Breadcrumbs - `My Health -> Update your VA health benefits information`

## Tasks
- [x] Get approved path and breadcrumbs from IA
- [x] Add entry in Content Build repo based on IA & vets-website scaffolded values
- [x] Ensure the feature flag (`vagovprod`) is initially set to false

## Acceptance Criteria
- Application is successfully scaffolded for dev & staging use in content build
