### ISSUE TITLE
(Lauren) Demo/shadow deployment for new team member, Rebecca

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#66751]
## Tasks
- [x] Coordinate with new team member your demo/shadow day
- [x] Account for additional time to provide her with context

## Acceptance Criteria
- [x] New team member will have shadowed how to do deploy
