### ISSUE TITLE
Add logger  

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#6675]
## User Story or Problem Statement
How might we identify spikes in latency and quantify performance issues for VSP?

## Goal
Identify and convey factors contributing to latency

## Objectives or Key Results this is meant to further
OBJECTIVE 1: Enhance the search process
KEY RESULT: Time for delivery of results for Commmunity Care searches will improve by (TBD) by (date

---
## Tasks
- [ ] Add logger to show where spikes are occurring

## Acceptance Criteria
- [ ] Qualitative data for performance conversations
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
@darkbushido can you please add an estimate for this effort?
