### ISSUE TITLE
Content review of Benefit Taxonomy MVP

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#66768]
## Issue Description

Content review and testing of Benefit Taxonomy MVP in Drupal, to gather feedback for Public Websites team:
- populating content
- adding and editing terms
- feedback on model and on editor experience
- think about what we will use this for

From the team:
The tool is in prod now, they've updated it so we can make terms ourselves.

Tool: https://prod.cms.va.gov/admin/structure/taxonomy/manage/va_benefits_taxonomy/overview

[Video of Laura's overview of the tool](https://github.com/department-of-veterans-affairs/va.gov-team/assets/140766198/953edf41-fb87-4ef1-b93c-e9bb28837838)

---
## Tasks
- [ ] CAIA content workshop to test drive the tool (Lily)
- [ ] Feedback and questions compiled (Lily)
- [ ] Review shared with stakeholders (Lily)

## Acceptance Criteria
- [ ] Tool tested and feedback provided

---

**Comment by laurwill** [comment]
I think OCTO was working on this before bringing us in, but I honestly can't remember — maybe check with Danielle and Randi whether there's still work for us to do here
