### ISSUE TITLE
[UX] Wireframe UI solution for communication of BT claim statuses 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#66762]
## Tasks

How might we design a BT claim status UI that communicates to Veterans their claim status for each appt, what it means and/or what to do next? And, while making sure it "fits" with our existing pre-check-in and check-in statuses in unified check in. For example, although the statuses won't ever be presented together, should they look different, look similar or use different icons, etc.? 

[BTSSS claim statuses](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/discovery/travel-reimbursement/submitted-claim-statuses.md)

[Related Slack thread](https://dsva.slack.com/archives/C05Q9HH47PS/p1696005901410659)

[Past appts BT claims Mural (that shows possible positioning on the page)](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695774555765/73dec2c323f80ae6cb2a6e0a646221e2aeb680c4?sender=u37bb983bd3fc3cc00c7d3286)

[Other content artifacts about claim rejections and next steps](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/discovery/travel-reimbursement/assets#content-artifacts)

**NOTE: does not include developing the content; Misty et. al. are doing research on the content & we don't want to duplicate their efforts**

- [x] Get update from Skylar (or Matt) on the Benefits team about what Matt Dingee wanted him to use for statuses. ([Sketch file](https://www.sketch.com/s/98e35645-34eb-40cf-80c1-6c4952943584/p/CEE34D8F-F5D3-46B7-85F8-8724BCBB5C76/canvas)) (Hard to tell in their Sketch file what the most recent solution/version is.)
- [x] Wireframe UI solution for communication of BT claim statuses on appt list and appt detail page
- [ ] Consider when to run solutions by Mobile App team (who is working on this now) and Appointments (VAOS) team, including Kristen McConnell 
- [x] Present solution to Matt Dingee and get feedback

## AC

- [x] Wireframe UI solution for appt list page and appt detail page. For example, it's just a component that we need to design. Or, one version for the appt list page and another version for appt detail page. 
- [ ] Sign off from involved stakeholders

**Comment by benbrasso-agile6** [comment]
@loripusey pull into sprint

**Comment by benbrasso-agile6** [comment]
This is a great place to start reviewing, as far as where claim status is positioned on the appt list and detail pages [Past appts BT claims Mural (that shows possible positioning on the page)](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695774555765/73dec2c323f80ae6cb2a6e0a646221e2aeb680c4?sender=u37bb983bd3fc3cc00c7d3286)

And, mobile app started some work too. But, I'd treat this more as a reference. Our UI's (i.e., mobile app vs web) each have some nuances, so I think the Mural above is a better place to start from. 

[Main screen flow (1).pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjRSQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--78f9f0675024654dcf913065399dbcc28377dcca/Main%20screen%20flow%20%281%29.pdf)
[Dispersed task (1).pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjhSQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4737e4bcd4bc27d14ff85ef5808222ef7da0a024/Dispersed%20task%20%281%29.pdf)

And, then, since they will be past appts (past appts detail pages), we'll probably want to use something close to what the Appointments team uses to show that it's an appt in the past (status)... https://www.figma.com/file/xRs9s6QWoBPRhpdYCGc3cV/User-Flow?type=whiteboard&node-id=2884-13385&t=frQysnfh6bHoIXhu-0

Hopefully that's a good place to start from.

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 as mobile app will be dialing back a bit on travel pay past appts, I'm going to spin off a separate ticket specific to content needs. Probably have it for next sprint. cc @cgednalske

**Comment by benbrasso-agile6** [comment]
Info from Misty that I think makes sense: 

`I do know that we (mobile app) won't link to BTSSS because the whole portal is not mobile-friendly at all. If we can't change the claim status definitions and aren't going to add the full status definitions, we (me and web content) likely will want to give some clarity via copy around some statuses. For example: Like for Denied, we could say something like "We denied your claim. We mailed you a letter about why."`

**Comment by ytsaoca** [comment]
Created [several version for discussion](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/1238ECAD-399B-44ED-BEFF-F6F523D5CFE6/canvas). Will talk at the ux sync today.

And @benbrasso-agile6  started adding some screenshots off to the side with some background info and can write out the different scenarios we need to solve for. 
According to @ben-allen-oddball It may carry over to next sprint, because we'll also want to start having Kelly help with content.

**Comment by ytsaoca** [comment]
Created [several version for discussion](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/1238ECAD-399B-44ED-BEFF-F6F523D5CFE6/canvas). Will talk at the ux sync today.

And @benbrasso-agile6  started adding some screenshots off to the side with some background info and can write out the different scenarios we need to solve for. 
According to @ben-allen-oddball It may carry over to next sprint, because we'll also want to start having Kelly help with content.

**Comment by benbrasso-agile6** [comment]
@loripusey Yes, we'll probably need to carry this ticket over, due to some cross-team collab updates

**Comment by cgednalske** [comment]
@benbrasso-agile6 re Misty's info on not including a link to BTSSS, does this change at all (or create new considerations) knowing the Appointments version would be mostly desktop?

**Comment by benbrasso-agile6** [comment]
Um, trying to figure out how to answer your question...

1) I am documenting with numbers, what different states we need in [sketch](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/v/zYoeYa/p/1238ECAD-399B-44ED-BEFF-F6F523D5CFE6/canvas/). I'm not quite completed yet. 
2) I stubbed out this [one ticket for content for the details pages](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67165) for Kelly. And, I'll do a similar one for content we need for different states for the appt list page. 

That at all answer your question or comment?

**Comment by benbrasso-agile6** [comment]
I think some of the information I originally noted in this ticket has changed (from cross-team collabs), so I'm trying to document the needs better now from the first bullet in my previous comment

**Comment by cgednalske** [comment]
Hmm I'm not sure, but it's probably fine if I just hold my question for later 🙂

**Comment by benbrasso-agile6** [comment]
Now that I look at your question more... yeah, some things have changed through conversations. I don't know if mobile is still sticking to that. But, I do not think that Appointments and check in would want to exclude the link.

**Comment by benbrasso-agile6** [comment]
I'll take a look at this work today. @kellysmith1008, will want to sync with you at some point this week.

**Comment by benbrasso-agile6** [comment]
Ready for review @kellysmith1008 @cgednalske @zach-park 

@zach-park when you get a moment, can you check my spacing, as well as my fonts, components, and anything else that you would want to clean up? TYSM

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2xxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--39c28fa44c561e394e52ca642e62279ea63495a5/Screenshot%202023-10-24%20at%206.09.24%20PM.png)

https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/1238ECAD-399B-44ED-BEFF-F6F523D5CFE6/canvas#Version

@kellysmith1008 this is more or less the design, feel free to add comments to these artboards in relation to your content ticket about these

**Comment by benbrasso-agile6** [comment]
Added headings

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGhxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f318e2bf7276a8172444c3b812731f3d6dc6937a/Screenshot%202023-10-24%20at%206.34.35%20PM.png)

**Comment by benbrasso-agile6** [comment]
Made some tweaks and added another scenario

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3R1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe45c2df449922c9e2569b49703ea2a6cbf1d85e/Screenshot%202023-10-25%20at%2010.06.07%20AM.png)

https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/1238ECAD-399B-44ED-BEFF-F6F523D5CFE6/canvas

**Comment by benbrasso-agile6** [comment]
Relocated explorations into [Playground file](https://www.sketch.com/s/845dc4de-d3ec-4dab-a14a-f89d79c47de5/p/4FFC60E2-57A3-4237-B19B-C507A0732C6F/canvas#Version)

**Comment by benbrasso-agile6** [comment]
Pulling this back to in progress to include the appt list

**Comment by benbrasso-agile6** [comment]
Added appt list page with task card for validation @cgednalske @kellysmith1008 - https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/v/GrLGOD/p/73EE914F-7B6C-490B-84E0-F8E344E64201/canvas#Version

**Comment by benbrasso-agile6** [comment]
Pushing this into Validate (minus whatever decision is made about actions in the appt list) 

[Appt list and task card](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/v/GrLGOD/p/73EE914F-7B6C-490B-84E0-F8E344E64201/canvas#Version)

[Appt detail pages](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/1238ECAD-399B-44ED-BEFF-F6F523D5CFE6/canvas)

**Comment by benbrasso-agile6** [comment]
@ytsaoca this is a good ticket to start validating when you're back

**Comment by zach-park** [comment]
> @zach-park when you get a moment, can you check my spacing, as well as my fonts, components, and anything else that you would want to clean up? TYSM

Hi @Ben, I validated the spacing. Thank you!

**Comment by ytsaoca** [comment]
@benbrasso-agile6 and @zach-park Validated the mockups. I just fixed some small bugs where the component size was not an integer. Otherwise, they looks great!

**Comment by ytsaoca** [comment]
@benbrasso-agile6 and @zach-park Validated the mockups. I just fixed some small bugs where the component size was not an integer. Otherwise, they looks great!

**Comment by benbrasso-agile6** [comment]
Thanks! I was in the process of making it match the [VAOS spacing](https://www.figma.com/file/RcDljBwThbwVDkNrDH2xiA/Appointment-Details-Redesign?type=design&node-id=2237-84511&mode=design&t=DNfh1RkTHcxrepJJ-0), but I know exactly which one you mean. TY

**Comment by benbrasso-agile6** [comment]
Gonna make some edits based on slack convos

**Comment by benbrasso-agile6** [comment]
Posted everything in this [Slack thread](https://dsva.slack.com/archives/C05Q9HH47PS/p1698244799132289) for @ytsaoca @kellysmith1008 @zach-park @cgednalske Kristen, Ciera and Peter to validate

**Comment by loripusey** [comment]
@ytsaoca @kellysmith1008 @zach-park @cgednalske please validate ASAP and close before planning

**Comment by benbrasso-agile6** [comment]
I think we can close, any feedback from collab cycle office hours meeting, I can address if it's quick, or if it's a lot, we'll open a new ticket
