### ISSUE TITLE
Secondary Nav feedback gathering and product team alignment

### ISSUE THREAD

**Issue by LynneJohnson224** [department-of-veterans-affairs/va.gov-team#66770]
## User story
As a product owner on MHV on VA.gov, I want to be confident that the MHV on VA health tool teams are aligned on a proposed redesign of the secondary navigation so that we can confidently move forward with creating a high-fidelity prototype for user testing.

## Description
Based on work done in previous tickets #65677 (low fidelity design ideation), #65055 (documentation of issues with existing nav patterns), & #65308 (competitive analysis), we want to compile the best 1-3 ideas and share them with stakeholders in the MHV on VA.gov space. 

## Tasks
Share low fidelity designs with various groups to get feedback & iterate as needed after each sync. Meetings should happen in the following order:
  - [x] 1. @coultonbunney-usds @mnorthuis 
  - [ ] 2. Accessibility specialists
  - [ ] 3. ~~Design office hours (if valuable)~~

## Acceptance Criteria

- [x] Key MHV UX stakeholders have had a chance to provide feedback on into proposed design option(s)
- [x] Follow-on ticket has been created to build high fidelity prototype for user testing established based on that feedback

**Comment by sterkenburgsara** [comment]
Update: Met this afternoon with @fmccaf1 @Jenny-yw @coultonbunney-usds to discuss secondary navigation low fidelity design and have alignment on three designs to take forward to user research. 

@mnorthuis is OOO today, but I have shared with her via the secondary navigation channel on Slack and will incorporate her feedback next week (if applicable). Robyn Singleton is aware of the planned user research approach  with 2-3 lightweight prototypes (preference for CodePen or UX Pin prototypes) and is guiding the development of our research plan alongside @Jenny-yw.

@fmccaf1 & @AngelaFowler82 will meet next Tuesday 10/10 to run through a11y concerns with low-fidelity designs prior to prototyping.
