### ISSUE TITLE
[Design] Make Final HLR Design Changes

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#6680]
## User Story or Problem Statement
We need to ensure that certain design aspects of the form are consistent with other form patterns on VA.gov and to create designs for different states that the front end developers may need to implement properly in code.

This story captures the work for the call center product guide for Higher Level Review.

Here is the Invision prototype link to HLR:

https://vsateams.invisionapp.com/share/W5U21BDFTQK

## Goal
To make sure that the design is consistent with known form patterns on VA.gov.

## Tasks
- [x] Info page - Update to show 2 question gating
- [x] Intro page - Remove 'things to consider' list and replace with the single thing to consider
- [x] Intro page - remove forwarding address mention
- [x] Contact info - make language sections consistent with profile update info
- [x] Contact info - make error states consistent with design system (no gray field bg, etc)
- [x] Contested Issues - Work in 'required' at the top somewhere to indicate to users that they must select at least 1 contested issue
- [x] Same Office - eliminate page and make this a checkbox option on the contested issues screen instead
- [x] Review page - Make contested issues edit section consistent with button placement on other forms
- [x] Review page - Show contested issues edit section state (what does it look like when user is editing/de/reselecting contested issues

## Acceptance Criteria
- [ ] All tasks above have been implemented into the Invision prototype link referenced above

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
All changes can be found here: https://vsateams.invisionapp.com/share/W5U21BDFTQK
