### ISSUE TITLE
Research: Connect Platform Support VFS Survey to DOMO

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#66806]
## Description 
We would like to connect [this survey](https://dj540s05.optimalworkshop.com/questions/c0bb406d1eea3f7f8f4abd153a13d8a2) to our DOMO dashboard [here](https://va-gov.domo.com/page/835197588).

---

## Definition of Done
Tasks below are complete.

---

## Tasks 

- [x] Speak with Michelle Dooley to identify what the lift would be to accomplish this task
- [x] Identify who is responsible for the work
- [x] Create a ticket for the work to be completed

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Verified with Naomi that we need to export the spreadsheet and upload it. Identifying if that uploading will fall on our team or the Platform Analytics team.

**Comment by alyssagallion** [comment]
Scheduled a phone call with @michelle-dooley  to overview the export process for Optimal Workshop and to show us how we can upload it to DOMO.

**Comment by alyssagallion** [comment]
The Platform Support team will own this process. There is a ticket located here where the work will be performed: https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/69269
