### ISSUE TITLE
Lighthouse API Endpoint Requirements 

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#66810]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-outline.md)

## High Level User Story/ies
To allow Veterans to request Power of Attorney online through VA.gov, I need endpoint support from Lighthouse API so I can make sure representatives receive the digital submissions and can act on (approve/reject) these requests for Power of Attorney.

## Definition of done
- [x] Setup a meeting connecting our team with key players in Lighthouse
- [ ] Define a path forward that everyone agrees on
- [ ] Document the needs and the plan of action, including next steps

**Comment by oddball-lindsay** [comment]
Lighthouse will be scoping this work and creating/assigning user stories, so we no longer need this epic.
