### ISSUE TITLE
Technical Dive for Lighthouse API Endpoint Support

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#66811]
## Issue Description
We met with product folks from Lighthouse to present our needs, and now need to do a deep dive into technical requirements.  

---
## Tasks
- [x] Setup a meeting connecting our team with key players in Lighthouse
- [x] Define a path forward that everyone agrees on
- [x] Document the needs and the plan of action, including next steps

## Acceptance Criteria
- Notes from the initial meeting are documented
- Next steps are clearly defined and agreed upon
- A future meeting has been set to continue the discussion (if needed)

**Comment by oddball-lindsay** [comment]
Notes are stored here: https://dsva.slack.com/docs/T03FECE8V/F05TTMJ9WG1

A biweekly meeting has been setup for continued discussion; scheduled for Mondays at 3:30p ET
