### ISSUE TITLE
Potential issues with configuration handling in settings.yml and settings.local.yml

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#66823]
### Description:

The current configuration setup uses both `settings.yml` and `settings.local.yml` for storing and overriding settings. However, there's a potential problem when a setting is defined in `settings.yml` and NOT in `settings.local.yml`. This can result in unintentional configurations being applied in production, especially when changes are made to the default settings in `settings.yml`.

### Details:

The way that it’s implemented right now, this can happen pretty easily:
- Developer creates functionality and adds a setting in settings.yml (for example, adds a betamocks definition for an existing service, and the setting to enable it being service.mock = true)
- Developer merges PR
- Production is now unintentionally using the betamocks definition defined on the vets-api settings.yml file, because infra repository was not updated first with service.mock = false
  
- The [config gem](https://github.com/railsconfig/config) merges settings in the following order:
  1. `settings.yml`
  2. `settings/#{environment}.yml`
  3. `settings.local.yml`
  4. `settings/#{environment}.local.yml`
  5. Custom config files (if any)

  Subsequent files will overwrite the previous ones if there are conflicts.

### Potential Solutions:

1. Consider overwriting `settings.yml` in live environments using volume mount configurations, thereby eliminating two sources of truth.
2. Consider treating `settings.yml` as the base configuration, with `settings.local.yml` taking precedence and overriding values.
3. Ensure that every configuration in `settings.yml` has a corresponding default or override in `settings.local.yml`.

### Comments from Team:

- The current understanding is that `settings.yml` is the 'default', with values overridden in `settings.local.yaml` files. There's caution to ensure that a `settings.local.yml` includes every value in `settings.yml`.
  
- The configuration in `settings.yml` for production contains unintentional settings, which poses risks.

### Action Items:

1. Review and discuss the best practice for managing settings in `settings.yml` and `settings.local.yml`.
2. Determine if the risk of unintentional configurations warrants an overhaul or a change in best practices.
3. Update documentation and guidelines based on conclusions drawn from discussions.

### Tasks
- [ ] Add staging.local.yml to staging manifests and remove extra vsp_environment vars
- [ ] Add sandbox.local.yml to sandbox manifests and remove extra vsp_environment vars
- [ ] Add production.local.yml to production manifests and remove extra vsp_environment vars
- [ ] Confirm all environments work
- [ ] Update vets-api add_local_config to apply to every env, not just dev.
- [ ] Update GHA
- [ ] Update documentation

⚠️ **_Written by Chat GPT based on [this conversation and thread](https://dsva.slack.com/archives/C0460N83Y9G/p1696273248048139). Edited by @rmtolmach._**

**Comment by rmtolmach** [comment]
I think this came out a misunderstanding of `settings.local.yml` vs `settings.yml`. `settings.local.yml` is actually overwriting `settings.yml`. 

@rmtolmach to review this and see if we can close or change acceptance criteria to make this less confusing. Start with dev.

**Comment by RachalCassity** [comment]
The config gem loads settings based on the Rails.env. Tried to use vsp_environment, which is different for each environment. Looking into another way to go about this. May not be possible because Rails.env is set to production for dev, staging, sandbox, and production.

**Comment by RachalCassity** [comment]
Reloading the Settings removes some authentication files, in regards to SAML files. settings.local.yml will remain the settings file for all environments.

settings-local-yml configuration will be moved out of values.yml

**Comment by laineymajor** [comment]
Removing values and condensing secrets (this will reduce human error).
- Rachal will be sending PRs soon for review

**Comment by RachalCassity** [comment]
Pushed to Prod. This ticket will be closed once prod deploys today (12/18)
