### ISSUE TITLE
Set up Insights artifact and add needed columns

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#66825]
## Purpose
We want to create the initial Insights resource.  It should contain all relevant data and links to appropriate resources for more detail.

Desirable features we've identified:   https://vfs.atlassian.net/wiki/spaces/SDT/pages/2968322421/Considering+Conf.+Databases+for+our+Big+Board+of+Insights#Identified-desirable-features-or-outcomes%3A
Tool breakdown of desired features:  https://vfs.atlassian.net/wiki/spaces/SDT/pages/2968322421/Considering+Conf.+Databases+for+our+Big+Board+of+Insights#What-do-various-existing-tools-offer-that-we%E2%80%99d-like-to-have%3F
Additional considerations:  https://vfs.atlassian.net/wiki/spaces/SDT/pages/3101720782/Discussion+How+we+might+use+Confluence+Database+as+the+Insights+tool#Variables-to-report%2Ftrack-in-the-Customer-Insights-database%3A

## Tasks
- [x] Create a [duplicate version](https://vfs.atlassian.net/wiki/spaces/SDT/database/3120759313) of the artifact that Naomi has begun, within the SDT space for now.  (it will be moved to Research Repo once ready)
- [x] Evaluate whether all of the features we've identified as important from discovery work exist ([see this aggregate of features and considerations](https://www.figma.com/board/E7UXXdhC4Z2NygJhf63uZ6/Customer-Insights-database-inventory-checklist?node-id=13-115&t=n3l5i8M2EvJ1IGog-0))
- [x] create/modify columns and rows to accomplish inclusion of the desired features

## Acceptance Criteria
- [x] Artifacts contains columns for each type of metric data identified as desirable
