### ISSUE TITLE
ARM 21-22 Form - User Test - Planning

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#66824]
## Issue Description

Veteran user test of 21-22 form flow.

## Tasks
- [x] Create GitHub research folder
- [x] Create research plan
- [x] Define screener questions
- [x] Create conversation guide
- [x] Submit all materials to team for review
- [x] Create ZenHub ticket for revisions

## Acceptance Criteria
- [ ] All materials complete and ready for team review

**Comment by jfinnerty13** [comment]
@oddball-lindsay what Epic should I use for this?

**Comment by jfinnerty13** [comment]
Created GitHub folder
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/accredited-representation-management/research/2023-12-ARM-appointarep-usertest

And GDrive folder
https://drive.google.com/drive/folders/1uwJYxglqTTLY87l4YDYsCw3bT0qdtHUO?usp=drive_link

**Comment by jfinnerty13** [comment]
First draft of documents created - holding to submit to team for review until prototype is complete @mtri @oddball-lindsay
