### ISSUE TITLE
va-modal component should support an icon in title only for crisis line modal

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#66829]
## Description 
The current va crisis line modal includes an icon positioned to the left of the header: 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclgrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0ed6542f994bb38b4dd9c77aba84c7e8db7ce3d9/image.png)

Currently our va-modal component only accepts string values in the title prop. Since the crisis line modal is the only place where an icon will be used with the title, we should extend the va-modal component to only include the icon shown above if a specific, undocumented prop is provided to it. 

## Tasks
- [ ] Extend the va-modal component to conditionally include the icon shown above 

## Acceptance Criteria
- [ ] tasks have been completed
- [ ] storybook documentation has been updated.
