### ISSUE TITLE
[Business Automation] Create Health Service Content Library for Localized Health Service Content [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#6683]
## User Story or Problem Statement
As a VAMC and associated team member, I need a centralized repository of localized Health Service intros, content, and services provided, so I can quickly pull from edited and approved content to future Health Service pages. 

## Goal
_Complete approved library of content for all 95 Health Service Types_

## Objectives or Key Results this is meant to further
- _Increase velocity of system creation per quarter_

## Resources - Tools - Documentation
[Health_Service_Library_Doc](https://drive.google.com/drive/folders/1UIS7kL2oAdwJ7fd5ghN0U_AMpyFQEBlI)

## Tasks
The following tasks must be complete
- [ ] Creation of Health Service Document
- [ ] Load all Existing Content created for 95 health services
- [ ] List 95 health services. 

## Acceptance
_The following must be complete to provide acceptance that this issue is complete_
* Creation of Health Service Document
* Load all Existing Content created for 95 health services
* List 95 health services.
