### ISSUE TITLE
Controller for Representative Search

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#66847]
#### Issue Description
Develop a controller to facilitate the search of representatives and organizations based on various parameters.

---

#### Tasks
- [x] Create a new representative search controller.
- [x] Implement an index endpoint for the search controller.
- [x] Define search parameters: Rep type, Base location data, etc.
- [x] Enable searching and building collections of representatives.
- [x] Enable searching and building collections of organizations.
- [x] Add the new endpoint to routes.
- [x] Develop a serializer for representatives.
- [x] Develop a serializer for organizations.
- [x] Consult with Colin on the final data shape.

---

#### Acceptance Criteria
- [x] A fully functional search controller for representatives and organizations is available.
- [x] The controller supports all outlined search parameters.
- [x] Serializers for representatives and organizations are in place and working.

**Comment by jvcAdHoc** [comment]
things remaining:
- write unit tests
- refactor code to dry/simplify things
- write rep serializer
- write org serializer

**Comment by jvcAdHoc** [comment]
EOD update:
- refactor complete
- working on serializers
  -trying to get distance as part of serialization - use db vs rgeo?

**Comment by jvcAdHoc** [comment]
eod update:
- serializers and their specs are done
- distance calculation done in db and included in serialization
- controller spec remains

**Comment by jvcAdHoc** [comment]
We're choosing to extract the database's distance calculation to pass through to the front end. This will eliminate edge cases where the databases's sort order is different than that a distance approximation would imply. This means we won't need to use rgeo or the front end's distance approximation used for facility locator.

**Comment by jvcAdHoc** [comment]
eod update:
split the work into 2 prs that are both ready for review:
- [serializers and fixups](https://github.com/department-of-veterans-affairs/vets-api/pull/14400)
- [controller](https://github.com/department-of-veterans-affairs/vets-api/pull/14320)

**Comment by jvcAdHoc** [comment]
eod update:
- updated serializer pr with Holden's feedback
- will update controller pr tomorrow

**Comment by jvcAdHoc** [comment]
eod update:
- waiting for platform to review the serializer pr
- the controller pr depends on the serializer pr, so waiting to make changes until ^ is merged
