### ISSUE TITLE
Migrations/Model/Data for Organizations

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#66846]
#### Issue Description
Implement and manage address data for organizations, mirroring the modifications made for representatives (#66845).

---

#### Tasks
- [x] Add address columns to the organizations table.
- [x] Determine if there's a need for an index on the “location” for organizations.
- [ ] Update the organization model to handle address data.
- [ ] Modify the factory to include new address data/columns for organizations.
- [ ] Add index for name

---

#### Acceptance Criteria
- [ ] Address columns are added to the organization table.
- [ ] Organization model and factory are updated to handle address data.
