### ISSUE TITLE
Align Pension ITF Approach with 526

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#66844]
## Issue Description
Currently, the pension 527 form uses form submission date as the ITF date. 

---
## Tasks
- [ ]  Add the same flow used on 526, where the benefit claims API is called to check for ITF, and to write a new ITF if needed

## Acceptance Criteria
- [ ] Design should match the existing design of 526
- [ ] An ITF should be written
---

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/66844?planning-poker) with Zenhub @mjknight50 @TaiWilkin @ToddWebDev

**Comment by mjknight50** [comment]
@aplatt-coforma Dan has been doing the discovery on this and hasn't finished that yet.

**Comment by mjknight50** [comment]
![Screenshot 2023-11-06 at 4 59 42 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/3513353/3888ea30-9e75-43d6-81f6-fde44c861957)

**Comment by mjknight50** [comment]
Closing this ticket in favor of this one:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/75583
