### ISSUE TITLE
[FE] My VA Health Care: Clean up code for timezones

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-team#66858]
## Background
While working on #62294, Allison discovered some duplicates in the /dashboard/ application folder:
- /dashboard/utils/timezone.js is a duplicate of /vaos/utils/timezone.js
- /dashboard/utils/timezones.json is an old duplicate of /vaos/utils/timezones.json (which is now being generated by a script automatically)
- /dashboard/utils/vaos-timezone.js is a duplicate of the current /vaos/utils/timezone.js

I'm thinking maybe there's room for refactoring in /dashboard/utils/timezone.js. However, a lot of these functions are being used in /personalization/appointments/actions/utils.js so we'll have to be careful and set up unit tests when we update.

---
## Tasks
- [x] consolidate helper files into the date-formatting folder 
- [x] remove dependencies on startsAt 
- [x] check if /vaos/v2/appointments/ API provides information we are producing in dashboard/utils/timezone.js 
- [x] update appt mock data (see Network data for Cecil Morgan) 
- ~[ ] check if we can refactor or consolidate timezones.json and vaos-timezones.json~ 
- ~[ ] create date-fns-tz.js to repalce moment-tz.js?~

## Acceptance Criteria
- [ ] we have unit tests for timezone.js 
- [ ] timezone.js is improved

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ FE, BE
- _How can this work be validated?_

## Resources
- related ticket: #21395

**Comment by allisonlu** [comment]
@ajakabcin 

I created this ticket while working on https://github.com/department-of-veterans-affairs/va.gov-team/issues/62294. I pointed it as a 4, but kept the needs-refinement label in case you wanted to bring this up for tomorrow's refinement! It's also not urgent (just tech debt maintenance) so we can also talk about it Friday

**Comment by allisonlu** [comment]
updated point estimate to 0 for sprint 27! it was in a PR and approved, just merged it this morning and [it's already on staging](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/).

@adamwhitlock1 reviewed my PR, can you help validate?

**Comment by allisonlu** [comment]
spoke too soon in the comment above 😔  a change that I made caused a spike in errors on the VAOS appointment side and required an out-of-band deployment, so going to move this back into In Progress and update points to 2.

context for awareness: 
- [Slack thread in #vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1/p1704315634375599) 
- [OOB deployment request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72880)
- [Postmortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/my-va-allison-lu-appts-postmortem/Postmortems/2024/2024-01-03-%20My%20VA%20-%20appointments%20date%20parsing%20error.md) (sensitive repo)
- [PR for postmortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/1383) (with stakeholders as reviewers)

**Comment by allisonlu** [comment]
new PR awaiting for review. updating the estimate for sprint 28 to **0**

**Comment by allisonlu** [comment]
@ajakabcin 

updating this ticket to 1 point for sprint 29 - just need validation. 

@DanielMiller-agile6 @adamwhitlock1 can you help me confirm that you can see the same test coverage as below after running 
```
yarn test:coverage --app-folder personalization/dashboard --coverage-html
```

**Comment by ajakabcin** [comment]
Confirmed in slack this is good to close
