### ISSUE TITLE
Develop prototypes for secondary nav user testing

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#66855]
## User story
As a Cartographers team member, I want to create high-fidelity prototypes for proposed secondary navigation consistent with research objectives and participants, so that the study can arrive at a clear design for production.

## Notes
* Team previously aligned on CodePen as the prototyping platform best suited to efficient development and assistive technology.

**Related documents:**
* [Draft - navigation research plan with tasks](https://docs.google.com/document/d/1af-5X2nk9qlLIOn7AArtRKy1fk7GJC-pC2JiPyqQY14/edit#heading=h.uulssig0kpdv)
* [User flow diagram](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1703733197192/681451fa506f1df2e76079a7b8fa491984a37a10?sender=uf94a77a19aaf687331c09367) - articulating what screens are needed in prototypes

## Acceptance Criteria
- [ ] Prototypes are based on designs and enable participants to complete planned research tasks
- [ ] Prototypes have been approved by team's a11y specialist

## Tasks
- [x] Meet with Florence to review designs
- [x] Determine if we have developer access for prototyping work
- [ ] Check nav prototype user flow to account for all screens that will need to be built out/enabled in prototypes (@sterkenburgsara)
- [ ] Develop prototypes
- [ ] #73798

**Comment by LynneJohnson224** [comment]
Deprioritized and removed from Sprint 16 due to change in user research direction.

**Comment by wesrowe** [comment]
@jzucadi, a note on mobile breakpoint – re [this slack thread](https://agilesix.slack.com/archives/C05PH6V3MJL/p1703869777545799), we may want to use a different breakpoint for the mobile layout in the prototypes (e.g., something very wide like <768px) than we currently intend to use in the final product (XS screens only, ie <390px). Rationale: we need to test the "mobile design" on any mobile device a participant happens to bring to their session.

**Comment by coforma-jamie** [comment]
## CAIA Accessibility Review of Navigation Options

I'll work on this and get results to you by the end of the week. I'll tag you when it's complete!


### [Prototype A](https://codepen.io/figaro/project/live/AMVvEP)
- [ ] Run axe checks on every page or unique state (required)
- [ ] Color contrast checks
- [ ] Color blindness checks
- [ ] Zoom layouts to 400% and inspect them for readability. If layouts break at 400%, I will start reducing them until they become stable, and log the zoom ratio when things started breaking.
- [ ] Keyboard navigation
- [ ] Windows, Chrome, JAWS
- [ ] iPhone, iOS Safari, VoiceOver

#### Results and recommendations

(text goes here)

### [Prototype B](https://codepen.io/figaro/project/live/AqoeoW)
- [ ] Run axe checks on every page or unique state (required)
- [ ] Color contrast checks
- [ ] Color blindness checks
- [ ] Zoom layouts to 400% and inspect them for readability. If layouts break at 400%, I will start reducing them until they become stable, and log the zoom ratio when things started breaking.
- [ ] Keyboard navigation
- [ ] Windows, Chrome, JAWS
- [ ] iPhone, iOS Safari, VoiceOver

#### Results and recommendations

(text goes here)

**Comment by coforma-jamie** [comment]
Update - I've completed my review of your prototypes! You can view it [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/Deliverables/MHV%20Cartography%20Team/Jan24-new-nav-Design-Review.md).
