### ISSUE TITLE
PM | Profile | Contact Center Guide Refresh

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#66861]
[VAgov.Profile.v7.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/13795144/VAgov.Profile.v7.docx)

## Background 
A lot of the contact center guide has not been updated to stay in step with dev work 

## Tasks 
- [x] [review the template ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md)
- [x] update each profile product to have the sections detailed in the template 
     - [x] User Access (some sections mention LOA3 others do not, make LOA1 and LOA3 for all products, add a blocked user section as well) 
     - [x] Navigation
     - [x] Functionality 
     - [x] Major Issues and Error Messages 
- [x] update the screen grabs 
     - [x] edit as a subtask section  
- [x] check each navigation section for reference to the hub 
     - [x] Personal Info 
     - [x] Contact Info 
     - [x] Military Info 
     - [x] Direct Deposit
     - [x] Notification Settings 
     - [x] Account Security 
     - [x] Connected Apps

## Acceptance Criteria 
- [x] the contact guide is ready to be submitted for review
- [x] create a separate ticket to confirm each "major issues and error messages" sections are up to date
- [x] submitted https://github.com/department-of-veterans-affairs/va.gov-team/issues/72702
