### ISSUE TITLE
DR | Characterize LH 504 and 503 errors as 5xx errors in our logs

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#66874]
## Issue Description

In https://github.com/department-of-veterans-affairs/va.gov-team/issues/65839, we discovered that when Lighthouse returns 504 errors as HTML, rather than JSON. This causes our HTTP client code to error, and reclassify the error as a 400 error in our logs. This muddies our DataDog logs and alerts, as it forces us to investigate what we believe is a permanent client-side error but what is actually a transient server-side error message, that renders [an appropriate error message](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65839#issuecomment-1731749502) asking the Veteran to try again later.

The goal here is to characterize these 504s as 5xx errors in our logs to make alert triage easier. I have some ideas for that here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/65839#issuecomment-1731845292. I recommend first asking Lighthouse if they can return their 504s as JSON and not HTML, and preemptively rescuing the HTML error somewhere in our service code, and parse, raise/return, and log a 504 error from there. Whatever implementation we pursue, we need to ensure that the error message linked above still renders.

Update: similar to the above, it appears that 503 errors are being mischaracterized as 422s. See [Sentry](http://sentry.vfs.va.gov/organizations/vsp/discover/platform-api:1a55900934154547b78347d7f77256e1/?field=title&field=release&field=environment&field=user.display&field=timestamp&name=Common%3A%3AExceptions%3A%3ASchemaValidationErrors%3A+Validation+error+%28Common%3A%3AExceptions%3A%3ASchemaValidationErrors%29&project=3&query=issue.id%3A239836+user.id%3A%22644a7180ad26d66a115736%22&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1).

**Additional update — After looking into it further, it seems like the issue is not actually the HTML response, but the way we're handling errors. See comments below for further details**

---
## Tasks
- [ ] Fix error handling to properly catch 504s and 503s(see comment [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/66874#issuecomment-2043654690) for more context)

## Acceptance Criteria
- [ ] Our logs don't flag LH 504s as 400s.
- [ ] Our logs don't flag LH 503s as 422s.
- [ ] The current error messaging for these errors remains unchanged.

## Definition of Ready
Should be ready to pick up

## Definition of Done
- [ ] App is registering the same type of error as the backend
- [ ] Developers know how to diagnose the cause or the error
- [ ] Error messaging to Veteran is accurate and actionable
- [ ] Approved by product

**Comment by saderagsdale** [comment]
@data-doge I updated the DOD. Can you think about the estimate?

**Comment by saderagsdale** [comment]
@anniebtran and @data-doge to review then estimate.

**Comment by anniebtran** [comment]
Link to thread in slack channel: https://dsva.slack.com/archives/CKUCFQAHJ/p1697144395984589

Since I don't have access to logging, I can't see how big of an impact/how frequent the 504s are on our end, so will follow up when I can chat a little more with Eugene or something who might have more context

**Comment by saderagsdale** [comment]
Will estimate after talking to LH

**Comment by anniebtran** [comment]
Just wanted to leave some notes here before I started the [estimating process](https://docs.google.com/spreadsheets/d/1ae9fpz_ThZycIWjmBBMSEuGRGqsvRSz3/edit#gid=1440877167).

After speaking with Eugene and floating an idea to the Lighthouse team about shortening the timeout for the endpoints that we're specifically using, seems like it's not realistic to go that route as it could [result in returning more frequent timeouts and could interfere with future 3rd party consumers of the API](https://dsva.slack.com/archives/CKUCFQAHJ/p1698960975080799?thread_ts=1697144395.984589&cid=CKUCFQAHJ), so I think we'll have to parse the HTML we get back and make sure we raise/log the correct error code.

I haven't triple checked that this is what _every_ 504 => 400 error has looked like, but the ones I have seen appear to be raised [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/common/client/base.rb#L125) as a [`Common::Client::Errors::ParsingError`](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/common/client/base.rb#L118). Seems like it's happening because somewhere in the code above it, there is some JSON parsing has failed so a ParsingError gets raised and caught here. To make sure we raise the correct error, somewhere around this code, we'll probably want to parse the response body as HTML and check if there's an HTML element with `504 Gateway Timeout` in its content and make sure we raise the appropriate error if that is the case.

**Comment by HeatherWidmont** [comment]
@saderagsdale to review & if it needs any further refinement we will discuss it in tomorrow's backlog refinement

**Comment by data-doge** [comment]
This error occurs with LH 503 errors as well (i.e. 503s miscategorized as 422s when our code attempts to parse HTML 503 response). See [Sentry](http://sentry.vfs.va.gov/organizations/vsp/discover/platform-api:1a55900934154547b78347d7f77256e1/?field=title&field=release&field=environment&field=user.display&field=timestamp&name=Common%3A%3AExceptions%3A%3ASchemaValidationErrors%3A+Validation+error+%28Common%3A%3AExceptions%3A%3ASchemaValidationErrors%29&project=3&query=issue.id%3A239836+user.id%3A%22644a7180ad26d66a115736%22&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1).

**Comment by anniebtran** [comment]
Coming back to this with fresh eyes, it seems like the HTML response may be a red herring and the issue might be something else? 

In [this example](http://sentry.vfs.va.gov/organizations/vsp/issues/256220/events/8b5cc2e9b35a4be0838a8e3d7820ad11/?project=3), it looks like the error response is actually coming back with a `status` of 504 (scroll down and under Additional Data, you'll see a `status` key with `504` as its value) and the `errors` key says it's an "unmapped_service_exception" which led me to this [yaml file](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/locales/exceptions.en.yml#L2086-L2126) where our exceptions are defined — note that there's no `DR_503` or `DR_504`. 

Assuming the error response truly does have a 503/504 `status`, it seems that our [error handling code is trying to pass in `DR_503`/`DR_504`](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/decision_review_v1/service.rb#L408-L409) to the exception service but because they're not defined keys in the yaml, it's getting [recharacterized](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/decision_review_v1/service_exception.rb#L20-L24) as an unmapped_service_exception with a 400 as defined in that yaml

**Comment by saderagsdale** [comment]
@anniebtran Awesome description! Would you say this is in a good state to translate your findings into an updated list of tech tasks in the user story?

**Comment by anniebtran** [comment]
@saderagsdale Done!

**Comment by anniebtran** [comment]
Just merged this — don't think we can really test this once it deploys, so we could probably close this and monitor our alerts to see if it worked

**Comment by anniebtran** [comment]
Closing as this we haven't seen any of these errors since it's been deployed. If we encounter this issue again, we can reopen/create a new ticket
