### ISSUE TITLE
DR | Consolidate info on FE errors and send to Platform

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#66883]
## Issue Description

In our bug triage board, we have a number of tickets for FE errors we believe are platform-wide. Here are those tickets: (1) https://github.com/department-of-veterans-affairs/va.gov-team/issues/65758, (2) https://github.com/department-of-veterans-affairs/va.gov-team/issues/60474, (3) https://github.com/department-of-veterans-affairs/va.gov-team/issues/59998, (4) https://github.com/department-of-veterans-affairs/va.gov-team/issues/60471, (5) https://github.com/department-of-veterans-affairs/va.gov-team/issues/60475. We have raised many of these tickets in a Slack thread with Platform: https://dsva.slack.com/archives/CBU0KDSB1/p1686946267419029, in addition to a ticket not listed in our bug triage board: (6) https://github.com/department-of-veterans-affairs/va.gov-team/issues/60670.

At this stage, it would be worth filtering and consolidating these several issues and re-raising them with Platform. Now that we have RUMs set up for our DR forms, we should be able to tell which errors are **blocking** vs. which ones are harmless JavaScript noise. 

Please see tasks below for detail.

---
## Tasks
- [x] Assemble a consolidated list of every error described within all 6 tickets above.
- [x] For each error, use RUM to see whether it is a blocking error or harmless noise.
- [ ] Assemble a short-list of blocking errors. Disregard the other errors for all subsequent tasks in this list.
- [ ] For each error in that short-list, check how many forms produce the error.
- [x] For each error that appears to stem from DR forms only, create a ticket in our DR bug triage board.
- [x] For all other errors, briefly (< 30 minutes) look into the error to see whether you can provide any recommendations or guidance for a fix.
- [ ] Send this short-list of non-DR-specific, blocking errors, along with our recommendations, to Platform for follow-up.
- [ ] Consider looping Zach and Cory into that communication.
- [ ] Clean up our bug triage board.

## Acceptance Criteria
- [ ] Tasks above done.
- [ ] Platform fully aware of FE errors and their potential impact.
- [ ] Our team satisfied with the hand-off.

## Definition of Ready
N/A

## Definition of Done
- [ ] Acceptance criteria met.

**Comment by Mottie** [comment]
I haven't shared this document with platform yet, but this is what I've put together (no short list)

-------

# JS Error Investigation

## isProxied [#60474](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60474)

### Sentry link

- [`undefined is not an object (evaluating 'a.isProxied')`](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?display=top5&field=title&field=count%28%29&field=count_unique%28user%29&field=project&name=isProxied+Errors&query=event.type%3Aerror+isProxied&sort=-count&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1) - over 200k in past 90 days

### Investigation results

- No associated start date within the past 90 days.
- Errors are seen _globally_, not specific to decision review forms
- This error appears to occur within seconds after navigating
- Console messages examples (different instances with a sample size of 10)
  - Very common: Start with chunk load error x2, then `a.isProxied` TypeError. ([Sentry](http://sentry.vfs.va.gov/organizations/vsp/discover/platform-web:7b4b46af39dc45ccacd299781104e22c/?display=top5&field=title&field=user&field=project&name=isProxied+Errors&query=event.type%3Aerror+isProxied+title%3A%22TypeError%3A+undefined+is+not+an+object+%28evaluating+%27a.isProxied%27%29%22+project%3Aplatform-web&sort=-title&statsPeriod=1h&widths=-1&widths=-1&widths=-1))
  - Uncommon: Start with `TypeError: o[e] is not a function.`, then `a.isProxied` TypeError, then chunk load error x4. App path `/records/get-veteran-id-cards/vic/` ([Sentry](http://sentry.vfs.va.gov/organizations/vsp/discover/platform-web:f14e93fc05d7418ca33265a548367fe7/?display=top5&field=title&field=user&field=project&name=isProxied+Errors&query=event.type%3Aerror+isProxied+title%3A%22TypeError%3A+undefined+is+not+an+object+%28evaluating+%27a.isProxied%27%29%22+project%3Aplatform-web&sort=-title&statsPeriod=1h&widths=-1&widths=-1&widths=-1))
  - Rare: "Foresee WebSDK detected its embed code ran more than once.", then "This is a serious problem, please contact support.", then a loading chunk failed error followed by `a.isProxied` TypeError. App unknown ([Sentry](http://sentry.vfs.va.gov/organizations/vsp/discover/platform-web:365f28a31d2348a8973ad5f1de293fd3/?display=top5&field=title&field=user&field=project&name=isProxied+Errors&query=event.type%3Aerror+isProxied+title%3A%22TypeError%3A+undefined+is+not+an+object+%28evaluating+%27a.isProxied%27%29%22+project%3Aplatform-web&sort=-title&statsPeriod=1h&widths=-1&widths=-1&widths=-1))
- This error appears to intermittently block user interactions ([RUM sessions](https://vagov.ddog-gov.com/rum/sessions?query=-%40error.source%3Anetwork%20%40session.type%3Auser%20env%3A%28eks-prod%20OR%20prod%20OR%20production%20OR%20vagov-prod%29%20version%3A1.0.0%20-%40error.message%3Acsp_violation%2A%20%40error.message%3A%2AisProxied%2A%20%40type%3Aerror&cols=&index=%2A&refresh_mode=paused&type=rum&viz=stream&from_ts=1695933685890&to_ts=1697143285890&live=true))
- This error appears to be related to a third party library


## Version error [#65758](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65758)

### Sentry links

- [`Cannot read properties of undefined (reading 'version') TypeError`](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?end=2023-09-30T04%3A59%3A59&field=message&name=version&project=4&query=level%3Aerror+message%3A%22Cannot+read+properties+of+undefined+%28reading+%27version%27%29+TypeError%2A%22&sort=-message&start=2023-09-11T05%3A00%3A00&utc=false&widths=-1) - over 156k in time period
- [`undefined is not an object (evaluating 'e.version') TypeError`](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?end=2023-09-30T04%3A59%3A59&field=message&name=version&project=4&query=level%3Aerror+message%3A%22undefined+is+not+an+object+%28evaluating+%27e.version%27%29+TypeError%2A%22&sort=-message&start=2023-09-11T05%3A00%3A00&utc=false&widths=-1) - over 83k in time period
- [` e is undefined TypeError`](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?end=2023-09-30T04%3A59%3A59&field=message&name=version&project=4&query=level%3Aerror+message%3A%22e+is+undefined+TypeError+%2A%22&sort=-message&start=2023-09-11T05%3A00%3A00&utc=false&widths=-1) (temporally related) - over 7k in time period

### Investigation results

- Errors started & spiked at over 25k events/day between 9/14/2023 and 9/22/2023
- After 9/23/2023 events dropped to below 50 events/day; now below 20 events/day
- From looking at where in the code the error is occuring, it may be related to [authentication](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/user/authentication/utilities.js#L330) - the `verify` or `redirect` functions may be involved; but it's unclear
- Errors are seen _globally_, not specific to decision review forms
- Difference in time between last event and this error ranges from seconds to more than 40 minutes.
- We can't verify, but it does appear to be blocking user interactions
- Unable to find any corresponding RUM events


## Current time [#65758](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65758)

### Sentry link

- [`undefined is not an object (evaluating 'ceCurrentVideo.currentTime') TypeError`](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?field=message&name=currentTime&project=4&query=level%3Aerror+message%3A%22undefined+is+not+an+object+%28evaluating+%27ceCurrentVideo.currentTime%27%29+TypeError%2A%22&sort=-message&statsPeriod=90d&widths=-1) - almost 2.5k in past 90 days

### Investigation results

- No observable start date for these errors
- Errors are seen _globally_, not specific to decision review forms
- Difference in time between last event appears to mostly within seconds of the last event. One event had a 20 second event time difference
- More than one site has set up a filter to ignore this error
  - https://github.com/jchw-forks/allbadcards/blob/master/client/src/index.tsx#L64
  - https://github.com/bhavinv821/Search-Engine/blob/master/WebPages/BarkBox.html#L67
- Unable to find any corresponding RUM events
- We can't verify, but it does appear to be blocking user interactions
- [Stackoverflow question about the source](https://stackoverflow.com/q/72379068) - no solution.

## Blacklist C [#65758](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65758)

### Sentry link

- [`null is not an object (evaluating 't.blacklistC') Error`](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?field=message&name=blacklist&project=4&query=level%3Aerror+message%3A%22null+is+not+an+object+%28evaluating+%27t.blacklistC%27%29+Error+%2A%22&sort=-message&statsPeriod=90d&widths=-1) - 529 events in past 90 days

### Investigation results

- No observable start date for these errors, but there appears to be an increase in events after September 12.
- Errors are seen _globally_, not specific to decision review forms
- Most of the time there doesn't seem to be an associated last event. When there is one, it's usually a fetch of the `vamc-ehr.json`. Most have some Google analytics posts associated, but no user interaction.
- Unable to find any corresponding RUM events
- We can't verify, but it does NOT appear to be blocking user interactions
- I wonder if this error occurs _after_ the login timeout event
- Google & GitHub searches for '.blacklistC' were not helpful

## Undefined a=Oe(r) [#65758](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65758)

### Sentry link

- [`undefined is not an object (evaluating '(a=Oe(r)).then')`](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?field=message&name=undefined+aoer&project=4&query=level%3Aerror+AND+message%3A%22undefined+is+not+an+object+%28evaluating+%27%28a%3DOe%28r%29%29.then%27%29+TypeError%2A%22&sort=-message&statsPeriod=90d&widths=-1)

### Investigation results

- Start date appears to be around August 2, 2023 with 49 events from that date to Oct 12, 2023.
- Errors are seen _globally_, not specific to decision review forms
- This error appears to occur within seconds after navigating
- At lease one event was seen after an `.isProxied` error
- Unable to find any corresponding RUM events
- We can't verify, but it this type of error would block user interactions
- This error appears to be related to the web component distribution file

## Invalid regular expressions [#59998](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59998)

### Sentry link

- [`SyntaxError: Invalid regular expression: unrecognized character after (?`](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?display=top5&field=title&field=count%28%29&field=count_unique%28user%29&field=project&name=Invalid+regular+expressions&query=event.type%3Aerror+Invalid+regular+expression&sort=-count&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1) and `SyntaxError: Invalid regular expression: invalid group specifier name` - almost 1.6k in past 90 days

### Investigation results

- No observable start date for these errors
- Errors are seen _globally_, not specific to decision review forms
- This error is due to older browsers attempting to run unsupported RegExp.
- Unable to find any corresponding RUM events
- We can't verify, but this type of error would block user interactions
- There is no known solution, as I don't think there are any poly-fills for regular expression groups

## Modify anchor tag [#59998](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59998)

### Sentry link

- [`ReferenceError: Can't find variable: SymBrowser_ModifyAnchorTagWithTarget`](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?display=top5&field=title&field=count%28%29&field=count_unique%28user%29&field=project&name=Modify+anchor+tag&query=event.type%3Aerror+SymBrowser_ModifyAnchorTagWithTarget&sort=-count&statsPeriod=24h&widths=-1&widths=-1&widths=-1&widths=-1) - almost 1.9k in past 90 days

### Investigation results

- No observable start date for these errors
- Errors are seen _globally_, not specific to decision review forms
- Unable to find any corresponding RUM events
- This error is due to older browsers attempting to run **AppleMail Browser**.
- There is no known solution

## Get Computer Style [#59998](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59998)

### Sentry link

- [`TypeError: Argument 1 ('element') to Window.getComputedStyle must be an instance of Element`](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?display=top5&field=title&field=count%28%29&field=count_unique%28user%29&field=project&name=getComputedStyle&query=event.type%3Aerror+Window.getComputedStyle&sort=-count&statsPeriod=90d&widths=711&widths=-1&widths=-1&widths=-1) - 103 in past 90 days

### Investigation results

- No observable start date for these errors
- Errors are seen _globally_, not specific to decision review forms
- Unable to find any corresponding RUM events
- This error is only seen in **Mobile Safari browsers**
- There is no known solution

## Query [#59998](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59998)

### Sentry link

- [`Cannot read property 'query' of undefined TypeError`](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?display=top5&field=title&field=count%28%29&field=count_unique%28user%29&field=project&name=Query&query=event.type%3Aerror+%27query%27&sort=-count&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1) - almost 1.4k in past 90 days

### Investigation results

- No observable start date for these errors
- Errors are seen _globally_, not specific to decision review forms
- Unable to find any corresponding RUM events
- This error appears to be from a third party library `history/modules/useQueries.js`
- There is no known solution

## Matches is not a function [#60471](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60471)

### Sentry link

- [`TypeError: n.matches is not a function`](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?display=top5&field=title&field=count%28%29&field=count_unique%28user%29&field=project&name=matches+not+a+function&query=event.type%3Aerror+matches&sort=-count&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1)

### Investigation results

- Indeterminant start date for these errors. Error rates prior to September 1, 2023 were much higher, around 20-40 events/day. After September 1, levels dropped significantly to around 1-2 events/week
- Errors are seen _globally_, not specific to decision review forms
- Unable to find any corresponding RUM events
- This error is rarely seen now. We don't know what happened on September 1.
- There is no known solution

## SchemaError [#60475](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60475)

### Sentry link

- [`SchemaError: Expected `schema` to be an object or boolean`](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?display=top5&field=title&field=count%28%29&field=count_unique%28user%29&field=project&name=Schema+error&query=event.type%3Aerror+schema+object+or+boolean&sort=-count&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1)

### Investigation results

- Indeterminant start date for these errors. There have been 230 events in the past 90 days. 50 backend events `data/0/attributes/aod` linked to a Lighthouse error; [issue reported to Lighthouse](https://dsva.slack.com/archives/CKUCFQAHJ/p1697574669799729) - these only appear to be happening in staging.
- Errors are seen _globally_, not specific to decision review forms
- Unable to find any corresponding RUM events
- This error is very rarely seen now. I don't know what happened after June 16 when this was first noticed with 31 events/90 days. We're now seeing 2 events in the past 90 days.

## Remove child [#60677](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60670)

### Sentry link

- [`NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?display=top5&field=title&field=count%28%29&field=count_unique%28user%29&field=project&name=remove+child+error&query=event.type%3Aerror+removeChild&sort=-count&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1)

### Investigation results

- Indeterminant start date for these errors. There have been 4 events in the past 90 days.
- Errors are seen _globally_, not specific to decision review forms
- Unable to find any corresponding RUM events
- These errors started increasing around May 15, 2023
- This error is rarely seen now. I don't know what happened on September 1.
- Source of error appears to be from a [vap-svc component](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/user/profile/vap-svc/components/base/VAPServiceEditModalErrorMessage.jsx#L15). A team member was notified.

## t.some is not a function (no ticket)

### Sentry link

- [`t.some is not a function. (In 't.some((function(t){return e.has(t.code)}))', 't.some' is undefined) TypeError`](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?field=message&name=some+not+a+function&query=level%3Aerror+AND+message%3A%22t.some+is+not+a+function%2A%22&sort=-message&statsPeriod=90d&widths=-1)

### Investigation results

- Indeterminant start date for these errors. There have been 4 events in the past 90 days.
- Errors are seen _globally_, not specific to decision review forms
- This error is rarely seen now. I don't know what happened on September 1.
- [RUM event](https://vagov.ddog-gov.com/rum/sessions?query=%40type%3Aerror%20-%40error.source%3Anetwork%20%40session.type%3Auser%20env%3A%28eks-prod%20OR%20prod%20OR%20production%20OR%20vagov-prod%29%20version%3A1.0.0%20-%40error.message%3Acsp_violation%2A%20%40error.message%3A%2Asome%2A&cols=&index=%2A&refresh_mode=paused&type=rum&viz=stream&from_ts=1695933685890&to_ts=1697143285890&live=true); but replays are not available
- Source of error appears to be from a [vap-svc component](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/user/profile/vap-svc/components/base/VAPServiceEditModalErrorMessage.jsx#L15). A team member was notified.



## Not investigated

- `Maximum call stack size exceeded. RangeError`
- `Cannot read properties of undefined (reading 'version') TypeError`
- `Blocked 'worker-src' from 'blob:'`
- `Blocked 'media' from 'data:' media-src`
- `NotAllowedError: Sheet constructor document doesn't match`
- `null is not an object (evaluating 'pB.scrollLeft') TypeError`
- `null is not an object (evaluating 'g.readyState') TypeError`
- `null is not an object (evaluating 'this.closeControl.addEventListener') TypeError`

**Comment by saderagsdale** [comment]
Team will review before bug triage.

**Comment by saderagsdale** [comment]
Need to look at the list together and confirm it's ready before sending it to platform.

**Comment by saderagsdale** [comment]
@data-doge can you add the document here? @Mottie and I will review.

**Comment by Mottie** [comment]
[Word doc to be shared](https://docs.google.com/document/d/1Q3P5RsAUEb573cCKAW5X1Y9lG2BmVv9ZhrzX1lh9Dmk/edit#heading=h.lx2rf1j8yuy6)

**Comment by HeatherWidmont** [comment]
Waiting to hear back from Zach - platform leadership's weigh in
