### ISSUE TITLE
686/674 to Lighthouse API

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#66905]
## Issue Description
The 686/674 form is currently using a depreciated API to submit claims, and they need to be migrated to the new Lighthouse API.

Short term fix: 
We need to modify `app/sidekiq/central_mail/submit_central_form686c_job.rb` to leverage
`Form526BackupSubmission::Service` 
rather than 
`CentralMail::Service`

@kylesoskin shared these code snippets and approach

> lighthouse_service = Form526BackupSubmission::Service.new

> def submit_to_lh_claims_intake_api(form526_doc, attachments)
>         log_info(message: 'Uploading single fallback payload to Lighthouse', upload_type: FORM_526_DOC_TYPE,
>                  uuid: initial_upload_uuid)
>         lighthouse_service.upload_doc(
>           upload_url: initial_upload_location,
>           file: form526_doc[:file],
>           metadata: form526_doc[:metadata].to_json,
>           attachments:
>         )
>         log_info(message: 'Uploading single fallback payload to Lighthouse Successful', upload_type: FORM_526_DOC_TYPE,
>                  uuid: initial_upload_uuid)
>         @submission.update!(backup_submitted_claim_id: initial_upload_uuid)
>       end

and refactor request to match

> upload_url: initial_upload_location,
>           file: form526_doc[:file],
>           metadata: form526_doc[:metadata].to_json,
>           attachments:

see `lib/sidekiq/form526_backup_submission_process/processor.rb` for reference

---
## Tasks
- [ ] Migrate form submission to Lighthouse API

## Acceptance Criteria
- [ ] Validate that 686-only submission is successfully received by LH API
- [ ] Validate that 674-only submission is successfully received by LH API
- [ ] Validate that 686+674 submission is successfully received by LH API
- [ ] Validate that a 686 + Attachment submission is successfully received by LH API
- [ ] Validate that a 686 + 674 + Attachment submission is successfully received by LH API
---

**Comment by steele-lm** [comment]
@tblackwe Feel free to refine if needed.
