### ISSUE TITLE
Confirm Accepted Claim for 686/674

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#66912]
## Issue Description
We need to confirm acceptance of the 686 and 674 forms by downstream systems. Example: VBMS sends back a claim ID or success response, so we can validate the claim was accepted.

---
## Tasks
- [ ] Identify how to confirm accepted receipt of 686-only claims.
- [ ] Identify how to confirm accepted receipt of 674-only claims.
- [ ] Identify how to confirm accepted receipt of 686_674 claims.
- [ ] Identify how to notify if confirmation is not received for any claim type.
- [ ] Document solutions
- [ ] Create dashboard to track confirmed claims.

## Acceptance Criteria
- [ ] Dashboard that tracks acceptance of the following VA.gov claims by their final end-point:
   - [ ] 686-only claims from VA.gov
   - [ ] 674-only claims from VA.gov
   - [ ] 686+674 claims from VA.gov
- [ ] Raise notification if confirmation is not received with xx time period

---

**Comment by steele-lm** [comment]
@tblackwe Does this capture the request to confirm acceptance of claims? If so, I'll use this template for all the non-disability forms.

**Comment by tblackwe** [comment]
For acceptance Criteria: is a datadog monitor/dashboard required? Or simply documenting how we would do it?

**Comment by steele-lm** [comment]
@tblackwe I'm anticipating that we will need to build a dashboard. Would you prefer to split this ticket into two (research/documentation and dashboarding). We may also want to consult with Michael Taylor to confirm what the end-to-end tracking process should include.

**Comment by steele-lm** [comment]
@mjknight50 This is an old ticket. With all the ZSF work, do we still need it?
