### ISSUE TITLE
Yellow Ribbon Tool project launch checklist

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#6691]
_**Working draft**_
**Note: this list does not include tasks covered in the VSP Collaboration Cycle**

**NOTE** Staging link: https://staging.va.gov/education/yellow-ribbon-participating-schools/

**Design**
- [x] Schedule "Kick the tires" usability session with Education stakeholders
- [x] Conduct "Kick the tires" usability session with Education stakeholders

**IA**
- [x] New URL: va.gov/education/yellow-ribbon-participating-schools [IA Structure, URLs and Breadcrumbs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-yellow-ribbon.md#ia-structure-urls-and-breadcrumbs-)

**Content** 
Note: ticket for these at #8677 8677
- [x] Content to create content and prompts to guide users
- [x] Pull in search results currently living on legacy benefit.va.gov pages, and linked to from accordions on main YR page
- [x] Remove state accordions from [Yellow Ribbon page (https://www.va.gov/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/)](https://www.va.gov/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program)
- [x] Update verbiage on URL at the bottom of the `Do I qualify...` box on the   [YR page (https://www.va.gov/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/)](https://www.va.gov/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program)
- [x] Link to tool with contextual content where the accordions are
- [x] Add to left navigation on Education pages
Include link and contextual content to tool on:
- [x] GI Bill Benefit page
- [x] ~~GI Bill Comparison Tool landing page~~ Request sent to Matt Self's team. Crossing off our checklist (05/26/2020 Stephanie)
- [x] Add link and contextual content under `More information + resources` on [va.gov/education](https://va.gov/education)
- [x] Apply redirects listed in #4975 

**Dev**
- [x] Swagger docs for new `gibct-data-service` endpoint https://github.com/department-of-veterans-affairs/va.gov-team/issues/6653
- [x] Create `vets-api` proxy endpoint https://github.com/department-of-veterans-affairs/va.gov-team/issues/5608
- [x] Use new `vets-api` endpoint in `vets-website` https://github.com/department-of-veterans-affairs/va.gov-team/issues/5599
- [x] Update `vets-website` with new design spec https://github.com/department-of-veterans-affairs/va.gov-team/issues/6668
- [x] Update design to be mobile responsive https://github.com/department-of-veterans-affairs/va.gov-team/issues/7106
- [x] Update list of countries in dropdown https://github.com/department-of-veterans-affairs/va.gov-team/issues/7128
- [x] Use production YR CSV data for all envs to ensure what we're building will work exactly as planned on prod.
- [x] Show `degreeLevel` and `divisionProfessionSchool` key-value pairs for each YRP.
- [x] Add e2e tests (https://github.com/department-of-veterans-affairs/va.gov-team/issues/7297)
- [x] Resolve a11y concerns. (https://github.com/department-of-veterans-affairs/va.gov-team/issues/7642 and https://github.com/department-of-veterans-affairs/va.gov-team/issues/7133)
- [x] (**Moved to backlog, deemed not needed for MVP**) Update 'No results' messaging (https://github.com/department-of-veterans-affairs/va.gov-team/issues/7709)
- [x] Confirm that we do not need historical YR data for YR MVP (https://github.com/department-of-veterans-affairs/va.gov-team/issues/7465)
- [x] Add analytics - #7199 
- [x] Investigate duplicate YRPs https://dsva.slack.com/archives/C52CL1PKQ/p1585220145027400

**Questions to finalize before launch:**
On benefits.va.gov links:
- What is the process to retire them, other than redirects?
**Answer:**
- Who manages that process that we need to notify, once the redirects are in place?
**Answer**
- What steps do we need to take to ensure smooth transition to Tammy/Lucas/VBA to begin updating info in the tool and not on legacy pages?
**Answer:**

**Epic:**
https://github.com/department-of-veterans-affairs/va.gov-team/issues/3703

**Related tickets:**
https://github.com/department-of-veterans-affairs/va.gov-team/issues/4614
https://github.com/department-of-veterans-affairs/va.gov-team/issues/4893
https://github.com/department-of-veterans-affairs/va.gov-team/issues/2612
https://github.com/department-of-veterans-affairs/va.gov-team/issues/4881

**Comment by AnneHurley** [comment]
From @mnorthuis : I have talked with BAH and the Education stakeholders will determine if a link to that page needs to be added to the school administrators hub page - either way, that content will not be impacted here as it is not Veteran content.

**Comment by AnneHurley** [comment]
[Anne working copy updates to put into Drupal]
(https://app.zenhub.com/files/133843125/95f5100c-ed99-4286-ad95-a7cdb753dcaa/download)

**Comment by MickinSahni** [comment]
@kelsonic @AnneHurley @andaleliz 
hey team, can you confirm the status of the checklist items above within your respective areas of expertise? 
I just checked off the box for url per Mikki's guidance.

**Comment by kelsonic** [comment]
@MickinSahni `Dev` is now updated! 🙂

**Comment by andaleliz** [comment]
@MickinSahni and @jenniferlee-dsva - I'm thinking of our `kick the tires` session w/ stakeholders as a form of UAT, and that we need to wait until we have prod data.  Also, I would like to put together a plan/checklist for those sessions.

Is that how you're thinking of it too? If we're on the same page, I'll open an issue for creating that plan and work on it this sprint.

**Comment by jenniferlee-dsva** [comment]
Yes. I don't think it needs to be as formal as a real UAT process, but a checklist would be helpful for them (and ensure they don't start redesigning). Thank you @andaleliz

**Comment by andaleliz** [comment]
Checking off outstanding design tasks on this issue.

**Comment by kelsonic** [comment]
Could we update the content items here if any can be updated? 🙂

**Comment by AnneHurley** [comment]
@kelsonic  Thanks for the reminder. Updated all except:
1. The GI Bill Comparison tool link and content; this is with Matt Self's team
2. Redirects - @lunascoop @mnorthuis  - can one of you check off what's done?
3. The Questions and Answers about processes going forward - @stephorkandatx  or @andaleliz  - Not sure who added those. Could one of you take a look and see if they can be updated/closed, or whether they should be moved to the Yellow Ribbon part 2/post launch ticket?

**Comment by stephorkandatx** [comment]
Thank @AnneHurley I've updated the ticket description

I think those questions were older, here are Answers
On benefits.va.gov links:

What is the process to retire them, other than redirects?
Answer: We are applying redirects. Will follow up to see if additional work would be needed as post-mvp launch
Who manages that process that we need to notify, once the redirects are in place?
Answer: Jen Lee and Selina have notified
What steps do we need to take to ensure smooth transition to Tammy/Lucas/VBA to begin updating info in the tool and not on legacy pages?
Answer: They are using GIDS now
