### ISSUE TITLE
CH 36 | Confirm Accepted Claim

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#66913]
## Issue Description
We need to confirm acceptance of the Chapter 36/PCPG/25-8832 online claims by downstream systems. Example: Central Mail sends back a claim ID or success response, so we can validate the claim was accepted.

---
## Tasks
- [ ] Identify how to confirm accepted receipt of Chapter 36 claims
- [ ] Document the solution
- [ ] Create dashboard to track confirmed claims

## Acceptance Criteria
- [ ] Dashboard that tracks acceptance of Chapter 36 VA.gov claims by the final end-point.
---
