### ISSUE TITLE
Surface failure information about disallowed tests on published page

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#66922]
## Issue Description
We need to inform users of why their test failed and when. This should be done via either linking the GHA workflow, outputting the failure text itself, or both, right on the published page in platform website.

---
## Tasks
- [ ] Attempt to output the workflow failure on the published platform website pages for the disallowed tests lists.
- [ ] Attempt to add the failure text to the same pages.

## Acceptance Criteria
- [ ] Users have a quick way to diagnose why their tests were disallowed.

**Comment by CBonade** [comment]
The workflow link was an easy add and the failure text is contained within the workflow so would be redundant clutter on the page. This should be enough for anyone that needs to troubleshoot their issues. 

Note: It will not retroactively apply (there's no way to accomplish this) so will only apply to new pass/fail states on the allow list.
