### ISSUE TITLE
[SW] Accessibility Usability Study Sythesis

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#66921]
## Issue Description
Full Research Findings doc can be completed a sprint after research is completed. 

---
## Tasks
- [ ] _Compile/organize findings on Mural board_
- [ ] _Create Research Findings GH document_
- [ ] _Complete VA Recruitment Checker for Equality spreadsheet and add screenshot to Research Findings_
- [ ] _Add Findings to Research Repo_

## Acceptance Criteria
- [ ] _[Research Findings GH document]()_
- [ ] _[Completed VA Recruitment Checker for Equality Spreadsheet]()_
- [ ] _[Findings added to Research Repo]()_

**Comment by charlottecesana** [comment]
Moved to validate, study is complete! @Tom-Davis @HeatherRienks
