### ISSUE TITLE
[Design] Eligibility Page- Not Eligible - Deceased

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#6693]
## User Story 
As a user who authenticated but is not eligible to reorder because the person of record is deceased.

## Goal
_Information on non eligibility state

---
## Tasks

- [ ] _Page with instructions on next steps to be created

## Acceptance Criteria
- [ ] _For a given test user who is not eligible to reorder supplies, instructions on next steps needs to be provided 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by rileyorr** [comment]
@mojaray2k & @mr0sari0 The Invision mockup and content can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-introduction-screen.md#use-case---veteran-is-deceased). If you would like an example of functionality for this use case, try to [apply for VA healthcare](https://staging.va.gov/health-care/apply/application/introduction) (10-10EZ) while signed into **vets.gov.user+228**

**Comment by rileyorr** [comment]
@leahkeeler The contact information I included is based off research I did surrounding who Veterans should contact if their record is incorrectly displaying their deceased. I am unsure who could validate that it's the correct contact info we should be providing.

**Comment by leahkeeler** [comment]
@rileyorr Would the business folks at DLC be able to verify this? or be the first pass?

**Comment by rileyorr** [comment]
@leahkeeler I think we can certainly ask if they can verify that it's the correct information!
