### ISSUE TITLE
Remove Unused verified_decryptable_at column 

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#66933]
## Issue Description

Upon deploying the new KMS Key Rotation job, we can remove an old column, `verified_decryptable_at`, from 21 models across the app, as it's no longer used

## Tasks

- [x] In separate PR (and separate release cycle), add line (`self.ignored_columns += ['verified_decryptable_at']`) to `ApplicationRecord` - PR [here](https://github.com/department-of-veterans-affairs/vets-api/pull/14041)
- [x] Run migration removing said column - PR [here](https://github.com/department-of-veterans-affairs/vets-api/pull/14039)
- [x] Remove line ignoring column (may or may not need to be separate PR from the second task. TBD)

## Acceptance Criteria

- [x] `verified_decryptable_at` has been successfully removed from all databases, and extra line has been deleted from app code.

**Comment by JoeTice** [comment]
SPRINT 37 UPDATE - In Progress, this work is nearly completed but a small tweak is needed, will be finished in SPRINT 38

**Comment by JoeTice** [comment]
SPRINT 38 UPDATE - In Progress, task is nearly complete, expect it will be completed in Sprint 39

**Comment by ericboehs** [comment]
I confirmed this has been removed from production yesterday. Closing.
