### ISSUE TITLE
[Design] Eligibility Page - Not eligible - Outside date range 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#6694]
## User Story 
As a Veteran who authenticated but is not eligible to reorder because of eligibility date I would like to see the reason I cannot order and move forward  in the forms flow 

## Goal
_Instructions on next steps to be able to reorder medical supplies if no eligible because the record is outside of reorder window 

---
## Tasks
- [ ] _Directions for how to qualify to reorder are to be provided my DLC
- [ ] _Page with instructions on next steps to be created

## Acceptance Criteria
- [ ] _For a given test user who is not eligible to reorder supplies, instructions on next steps needs to be provided 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by rileyorr** [comment]
@mojaray2k & @mr0sari0 The Invision mockup and content can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-introduction-screen.md#use-case---no-items-are-available-for-resupply).
Please note that this alert applies if **all** the hearing aid batteries _and_ accessories a Veteran is eligible for are unavailable for resupply due to the 5 month ordering timeframe restriction. As always, let me know if you have any questions!
