### ISSUE TITLE
[bug] Veteran submitted streamlined waiver with compromise option

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#66940]
## Issue Description
On 9/26 a Veteran was able to submit an FSR form that was qualified for the streamlined short flow but they also selected the resolution option to be compromise with a specified dollar amount. It's believed that Veterans should only be able to submit streamlined submissions with the waiver resolution option. 

---
## Tasks
- [x] Pull data to validate submission (compromise + streamlined) to make sure it's not a data issue
- [x] Attempt to identify cause
- [x] Replicate in lower environment
- [ ] Draft future work to resolve scenario (if needed)

## Acceptance Criteria
- [ ] Future work is created to address this scenario
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Able to replicate this scenario by going through the FSR form in a non-streamlined flow then selecting compromise amount and later going back to update income/assets (e.g. put annual income and needed to update to monthly) then qualifying for the streamlined short flow. Since the compromise resolution option was selected previously and persisted this remained intact with the form. 

Unable to validate if that's how this specific submission encountered this due to PII filtering in logs but their form includes data from a non-streamlined flow (expenses, resolution comment, additional info) and then ended up submitting a form that was approved for streamlined short.

**Comment by ScottyRJames** [comment]
Rolled over due to requiring follow-up work ticket. Created ticket to address this [here](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/67399)
