### ISSUE TITLE
DR | Rewrite & move contestable issues component to shared 

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#66954]
## Value Statement
**_As a_**  Developer
**_I want to_** be rewrite the contestable issues widget component
**_So that_** we can have a consistent interaction across our appeals forms

## Background Context

The contestable issue widget should load contestable issues from the API endpoint in all our appeals forms. Currently only NOD has this functionality. We plan to convert this widget into a custom page component to allow greater flexibility. The new component must include this functionality:

- Load contestable issues on this page
- Replace outdated issues & check update of area of disagreement entries
- Show alert when API fails
- Show API-loaded contestable issues
- Show manually added issues
- Adjust decision date validation for each form (100 years max for Supplemental Claim & NOD v2, 1 year max limit for NOD v1 & HLR)
- Show add issue action link
- Show edit link for manually added issues
- Allow deleting manually added issues
- Allow selecting & unselecting issues
- Show alert/validation issue when no issues selected after trying to continue
- Show error message if a manually added issue is missing a title or has an invalid date
- Properly update form data
- Thorough unit & e2e testing

## Tasks
- [ ] Rewrite contestable issue widget into component
- [ ] Remove contestable issue API call in form app
- [ ] Includes all mentioned functionality
- [ ] Ensure altered issues are updated for follow up questions (area of disagreement for HLR & NOD)
- [ ] Update unit tests
- [ ] Update e2e tests

## Acceptance Criteria
- [ ] All tasks complete
- [ ] All tests passing
- [ ] Contestable issue page UX for each app is unchanged  
- [ ] Contestable issue API call only occurs on the contestable issues page

## Definition of Ready 
- [ ] Identify needed changes
- [ ] Note differences between app implementations (varied decision date requirements)

## Definition of Done
- [ ] Functionality of each form remains the same
- [ ] API-loaded contestable issues only occurs on contestable issues page
- [ ] Internal code reviewed
- [ ] Tested in staging

**Comment by Mottie** [comment]
Duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/69305 - worked completed
