### ISSUE TITLE
Update Platform Survey launch documentation

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#66952]
## Purpose
The pivot to a new tool for the Survey means that the way it needs to be launched must be changed, and the documentation updated.

## Tasks
- [x] Update [documentation](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1445724309/How-to+Launch+the+Platform+Satisfaction+Survey)

## Acceptance Criteria
- [x] Team review steps
- [x] User can follow guidance to successfully update/launch Survey
