### ISSUE TITLE
Plan out IPP Pilot Research Workshop

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#66963]
After meetings with Login.gov and Tom and Robyn, we need to plan out our research activities so that we can move forward with our research plan, conversation guide, and recruitment meetings

## Tasks
- [x]  Create an interactive session in a mural
- [x] Cover objectives and format for each research activity
- [x]  Gather feedback from internal team

## Acceptance Criteria
- [x] Session is completed on 10/11 with IPP team during IPP Weekly Meeting
