### ISSUE TITLE
[PI4-23] Oct/Nov/Dec Epic Planning tracker

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#66964]
## Description

Enter a detailed description of the work - gherkin syntax below is acceptable.

Scenario: In common language describe the work or issue

Given: The Epics for PI4 are listed
When: Epics are written, groomed and prioritized
Then: Stories/Tickets can be written for all epics and if there is an Epic needed to segment out the work those are noted in the Super Epic

## Tasks
- [x] Create a shell for every Super Epic that we plan on working in the PI
- [SW - PI4/23] Streamlined Waiver Accessibility Study #66914
- [FSR - PI3/23] FSR Review Page 2.0 #67965
- [FSR - PI4/23] Wizard Work (VHA) #48133
- [SW 2.0 - PI4/23] Streamlined Waiver 2.0 #67964
- [DMS - PI4/23] Document Management System #67130
- [IA - PI4/23] Information Architecture Redesign #67970
- [ ] Groom and refine the Super Epic so that they are complete with descriptions, requirements and acceptance criteria
- [x] Define the priority of the Super Epics
- The priority is noted [here ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1688172078819/27f5e6bb75d4ba2321ab4d2d06ee57f114570112?sender=uda7b949f12db6669f4466715)(May change over time)

## Acceptance criteria

- [ ] All the Super Epics are fully written and ready to be worked

## Testing
- [X] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [X] Description written
- [X] Tasks defined
- [X] Acceptance criteria written
- [X] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by Tom-Davis** [comment]
[PI4-23-Epics.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMllNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1dba487401a196956d9588dbef6dba28599ced88/PI4-23-Epics.xlsx)
