### ISSUE TITLE
Ask Platform teams for preferable Survey questions for their space

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#66969]
## Purpose
We could ask the Platform teams what questions would be most helpful for us to ask/report on/track in the Survey

## Tasks
- [x] [Create a research plan](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3192127523/Ask+Platform+teams+for+preferable+Survey+questions+for+their+space)
- [x] [Create a space](https://vfs.atlassian.net/wiki/spaces/SDT/whiteboard/3192520741) to collect insights/data
- [x] Ask each team to see what phrasing would be most helpful to their team concerning questions about their area in the Survey.

## Acceptance Criteria
- [x] Asks are made of Platform teams, with follow up clarity provided as needed
