### ISSUE TITLE
Filter and transform content  (Copy of CMS #1034)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#6698]
**This issue is a copy** of CMS issue [#1034](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1034) so that we can track this work on the VA.gov board. 
Please see also CMS Epic [#1005](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1005)

Work with CMS (Ethan Teague)

# Problem Statement
The data from the CMS export is raw and needs to be filtered and transformed before it can be used in the templates.

# For each ticket in this epic
This list comes from logging out all unique content model names while building out the entity trees of all `node`s in our current tome-sync output (which reflects the all CMS content on VA.gov when it was exported).
For each of these, we need to do the following.

## Task
- [ ] Create a pre-transformation JSON schema at `process-cms-exports/schemas/raw/${content-model-type}.json`
- [ ] Find the test CMS export data and the corresponding bit in the GraphQL response
- [ ] Copy this chunk of the response to `process-cms-exports/tests/transformed-entities/${content-model-type}.json`
- [ ] Create a post-transformation JSON schema at `process-cms-exports/schemas/transformed/${content-model-type}.json`
- [ ] Create a transformation function to map the raw CMS export data to the GraphQL response counterpart

## Goal
The content models after transformation match the result from the GraphQL query.

## Acceptance Criteria
- [ ] The content model shapes after transformation match that of their GraphQL counterpart in `pages.json`
- [ ] Pre- and post-transformation JSON schemas are used to validate the data 
- [ ] The transformation function is unit tested using known-good data

**Comment by mmiddaugh** [comment]
Per Kevin Walsh: 

> We need to do some further content model refactoring (and associated GraphQL refactoring) before we start the transformer work, so that is on pause. I hope that will be complete as soon as next Friday, after which Neil can take on the first transformer work (picking up where Ethan left off) and then do a knowledge transfer with Gibran. I would guess that it would be sometime in the week of March 30 or April 6.

**Comment by mmiddaugh** [comment]
Closing as duplicate
