### ISSUE TITLE
[CST] Address 422s on txt file submissions

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#66994]
### Background
When uploading claims documents to EVSS, we run a series of validations on the uploaded file before we attempt to send it to EVSS. These checks are for things like making sure that PDFs are unencrypted and checking that the encoding used is allowed. The check for encoding seems to be having issues with txt files, but from looking at the code it seems that txt files should be ignored by the check. We should identify what the intent of the check and if it is working as expected. If not, we should fix it

## Conclusions
The assumption that TXT files should be ignored was erroneous, they are the only file types that this validation should be ran against. The check is probably working as intended, but the error messaging is unhelpful and we currently don't have a way to reproduce the error. These are two things that we can definitely work on in our efforts to provide a better experience to end users

### Tasks
- [x] Identify what the intent of the failing check is
- [x] If there is an issue with the check, fix the code

### Acceptance Criteria
- [x] We have determined if there is an issue with the existing checks and if there are, we have fixed them

**Comment by HeatherWidmont** [comment]
This will require more work than originally anticipated, @jerekshoe will continue to investigate. cc @jacobworrell
