### ISSUE TITLE
CH 31 | Confirm Accepted Claim

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#67000]
## Issue Description
We need to confirm acceptance of the Chapter 31/VRE/28-1900 online claims by downstream systems. Example: Central Mail sends back a claim ID or success response, so we can validate the claim was accepted.

---
## Tasks
- [ ] Identify how to confirm accepted receipt of Chapter 31 claims
- [ ] Document the solution
- [ ] Create dashboard to track confirmed claims

## Acceptance Criteria
- [ ] Dashboard that tracks acceptance of Chapter 31 VA.gov claims by the final end-point.
---

**Comment by sortizsh** [comment]
@tblackwe  and @tfink419 can you build out the tasks for this?

**Comment by steele-lm** [comment]
We're waiting for the new RES endpoint to add success confirmation.
