### ISSUE TITLE
Project Kickoff for "View my payment history"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#6700]
## Steps to complete Project Kickoff
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan will schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] VSP <> **requesting team** kickoff meeting completed
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please bring the following to the kickoff meeting_
- Link to rough draft of [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-payment-history) 
- Explanation of the problem space
- Any other artifacts you have so far
- You **do not** need to prepare a presentation

## Meeting attendees from **requesting team**
- Product Manager (required): **Jason Wolf - jwolf@governmentcio.com**
- DEPO Product Lead (required): **Steve Kovacs - steven.kovacs@va.gov**
- Entire VFS team (recommended): **James Adams - jadams@governmentcio.com**
**Jesse Cohn** - jesse.cohn@adhocteam.us
**Micah Chiang** - micah@adhocteam.us
**Kathleen Crawford** - kcrawford@governmentcio.com
**Derek Dyer** - ddyer@governmentcio.com
**Nick Wygonik** - nwygonik@governmentcio.com

## Scheduling
Preferred dates or times: 
Afternoons to accommodate Pacific time, preferably not on demo or planning/grooming days

**Comment by meganhkelley** [comment]
Scheduled for 3/19 @ 1:30 pm ET

**Comment by joanneesteban** [comment]
@jason-gcio if you have KPIs set for this feature, could you add them or link them to your product outline?

**Comment by jason-gcio** [comment]
@joanneesteban - here are some but they may change or have more added as we get closer to final development
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-payment-history#okrs

**Comment by vbellissimo** [comment]
Cancelling/old task.
