### ISSUE TITLE
[FE] Onsite Notifications: Update dot indicator logic to capture all unread messages

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#67007]
## Background
The secure messaging team has determined that the current way we (and MHV) are determining if a user has unread messages may mean that unread messages in folders are missed. We need to make sure we're taking into account all unreads to return a dot or not.

Start [here](https://dsva.slack.com/archives/C909ZG2BB/p1696523257898719) in our thread for the context of the ask from Samara, which links off to a [thread with secure messaging](https://dsva.slack.com/archives/C03ECSBGSKX/p1696521023876209?thread_ts=1696513301.642959&cid=C03ECSBGSKX). It's not short but provides a lot of context and explanation.

It's important that the way in which we determine whether to render the dot or not is consistent with MHV and SM's logic for determining unreads. For reference,[ MHV's logic for how they render the dot](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/mhv/landing-page/utilities/data/index.js#L22) 

## Tasks
- [x] Conduct technical discovery to determine best solution for whether we should render the dot or not on the frontend
- [x] Confirm approach with Secure Messaging team (dev to check this with is Oleksii Morgun/Alex Morgun)
- [x] Implement change to dot indicator logic
- [x] Test
- [x] Move to validate
 

## Acceptance Criteria
- [x] Dot indicator logic looks for all unreads not just the inbox

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ We'll need to work with SM team to have unread messages placed in folders (and none in the inbox alone) to make sure the dot still renders

**Comment by allisonlu** [comment]
## determining unread messages 

### My VA logic

1. check if user state includes "messaging" backend service
2. if yes, then [fetch unread messages](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/actions/messaging.js#L21-L39)

we are grabbing the `unread_count` value from one folder only (`/v0/messaging/health/folders/0`)

### MHV landing page logic

1. check [folder list for current user](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/mhv/landing-page/utilities/api/index.js#L10-L19) from `/my_health/v1/messaging/folders` endpoint (with parameters `?page=1&per_page=999&useCache=false`)
2. [go into each folder](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/mhv/landing-page/utilities/data/index.js#L22-L33), and if there is unreadCount, then add it to the total

they are going through *every* folder and accumulating the `unreadCount` from each folder

### other notes
- `/my_health/v1/messaging/folders` endpoint is not thread-centric (according to [Oleksii Morgun's Slack message](https://dsva.slack.com/archives/C03ECSBGSKX/p1696519497805509?thread_ts=1696513301.642959&cid=C03ECSBGSKX))
- a response from the `/my_health/v1/messaging/folders` endpoint includes objects of all folders with a total count and a count of unread for each folder

### possible issues
- i'm not familiar with this `/my_health/v1/messaging/folders/` endpoint and not sure where to find documentation on it 
  - tbd - contacted AE devs, and will ask Oleksii by eod if i don't have a clear answer
- is My VA using an outdated endpoint?

### relevant files
- [My VA fetchUnreadMessagesCount function](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/actions/messaging.js#L21-L39)
- [MHV landing page countUnreadMessages function](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/mhv/landing-page/utilities/data/index.js#L22-L33)
- [Secure Messaging product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/760ea466c20622c684fda266c749c1d00e2fbbc2/products/va-mobile-app/features/secure-messaging/Product)

**Comment by allisonlu** [comment]
@ajakabcin 
ready for validation! i logged onto staging as Cecil Morgan and was able to see that unread messages are fetching from the new endpoint:

![Screenshot 2023-10-27 at 1 38 58 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8542413/2ad3b8af-60b5-40a7-8032-6da01eb0aa4e)

@adamwhitlock1 can you confirm that you can see it too?

**Comment by adamwhitlock1** [comment]
I tried a couple random test users and they didnt hit that api endpoint, probably because they didn't need to or something like that.

What are some test user email addresses that would qualify to hit that endpoint @allisonlu? I also looks for Cecil Morgan in the test user spreadsheet but didnt see them.

**Comment by allisonlu** [comment]
@adamwhitlock1 

users 41 and 225 should have unread messages!

**Comment by adamwhitlock1** [comment]
Can confirm also in staging that we are hitting the V1 endpoint now, and unread messages dot indicator is showing as expected. Good to close it out! Thanks

**Comment by ajakabcin** [comment]
@allisonlu and @adamwhitlock1  thank you both! I also reached out to secure messaging team for a test user who has unreads only in folders for an additional layer of validation, but I think we're good to close this for now and if we get that additional test user great, if not this is still sufficient!
