### ISSUE TITLE
[FE] My VA LOA1 updates: Post-launch code cleanup

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#67012]
## Background
We used the `my_va_experimental_frontend` feature flag for implementation of the LOA1 updates. Now that those updates are live in production to all users we need to clean up the flag code so that the feature flag can be used for other iniatives.

## Tasks
- [x] remove `myVaUseExperimentalFrontend` Toggler component from `Dashboard.jsx`
- [x] remove instances of `myVaUseExperimentalFrontend` from `loa1.cypress.spec.js`

## Acceptance Criteria
- [ ] all LOA1 updates are removed from behind the `my_va_experimental_frontend` feature flag
- [ ] `my_va_experimental_frontend` flag is not being utilized anymore, and ready to be used for next experiment

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Dev - @dellerbie 
- _How can this work be validated?_

**Comment by allisonlu** [comment]
@ajakabcin 

I added more details to the description and a point estimate of 2!

**Comment by allisonlu** [comment]
@ajakabcin 

ready for validation!

1. log in as any loa1 user
2. note that the loa1 UX updates are showing
3. turn off [`my_va_experimental_frontend` feature toggle](https://staging-api.va.gov/flipper/features/my_va_experimental_frontend)
4. make sure loa1 UX updates are still showing

**Comment by ajakabcin** [comment]
Confirmed! thanks for this really appreciate the steps for validation!
