### ISSUE TITLE
Toxic Exposure: Add to Product Guides

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#67024]
## Overview
Add Toxic Exposure to [526EZ Product Guide ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez/product/526ez%20Product%20Guide)and [526 BDD Product Guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez/product/526%20Benefits%20Delivery%20at%20Discharge%20-%20Product%20Guide)

[Product Guide guidelines](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)

## Tasks
- [x] Use screenshots from staging of new Toxic Exposure pages
- [x] Add any context that would be useful for Contact Center to understand what the page is being used for
- [x] Add any error context - document process a Veteran could take to get around the error

## Acceptance Criteria
- [x] New versions of both docs are uploaded to github
- [x] Doc is reviewed by design
- [ ] ~Notify Contact Center team, linking doc on contact center review ticket~ moved this to #67022

Note - 
- If we have any further changes with the release for IPF forms we may need to make additional product guide updates in a separate ticket.

**Comment by mengA6** [comment]
In the [Product Guide guidelines](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review) link, I'm not seeing anything related to the product guide - just info on staging review. Am I missing it?

**Comment by christinec-fftc** [comment]
Thanks @mengA6. Link has been updated.

**Comment by christinec-fftc** [comment]
Met with @mengA6 and @Kate-allbee and got some great feedback and suggestions. Internal draft has been updated. We're all done with this ticket. Once we get closer to launch we can do final prep with #67022
