### ISSUE TITLE
IA Tracker - Breadcrumbs on VAMC Events / Outreach Events cal

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#67025]
## About your team

- Team name: Sitewide Public Websites
  -	OCTO-DE product owner: Dave Conlon
  -	Product manager: Wes Rowe & Fran Cross (starting 10/10, VA access will take a bit)
  -	Designer: Jordan Wood
- Accessibility specialist: Laura Flannery
- Content writer: N/A
-	Slack channel: #sitewide-public-websites
 
### Describe what you need in a few sentences:

IA consult regarding breadcrumbs for a VAMC Event that can also be featured in the Outreach Events calendar. 
Currently: an Event can only be featured in one location. Regional events that get featured on Outreach Events listing must be duplicated. For COPE purposes, we are creating a Single source of truth, and allowing Editors to publish to their VAMC, and _also_ to the Outreach Events calendar. 

In our draft implementation: 
* The Event will always create a URL based on the single selection within the Event Listing dropdown. 
  * Breadcrumbs for Events are built from the Event URL.
  * If event is published to the Outreach Events listing in the dropdown, it will have Outreach URL / crumbs.
  * If the event is published to a VAMC listing (even if the National checkbox is checked): it will have a VAMC URL and breadcrumbs
    * Where a VAMC event is promoted to Outreach Events, the OE listing will point the user to the Event at the VAMC URL with VAMC breadcrumbs.
    * Lovell events in the Outreach Events calendar will always point to the Lovell VA version of the event page, rather than Tricare.

Laura Flannery has signed off from a11y perspective. We are hoping to review this with IA for any concerns, required changes.

### Which are you doing?
- [ ] **Launching a new** page, tool, form, or app
- [x] **Making changes** to an existing page, tool, form, or app

### Types of Support
What areas does your team need support in? Check all that apply.
#### Content
- [ ] Collaboration on content written by your team’s dedicated content writer 
- [ ] Collaboration on content if your team does not have a dedicated content writer
#### Accessibility
- [ ] Accessibility review of wireframes and/or prototypes
- [ ] Accessibility issue (general request)
- [ ] Accessibility PDF review request
- [ ] Accessibility user research support ([submit a separate, additional request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name))
- [ ] DST component or pattern 
- [ ] Something else 
#### IA
- [ ] User Flows
- [ ] Page placement
- [ ] URLs
- [x] Breadcrumbs and Left Nav placement
- [ ] Redirects
#### Multilingual content
- [ ] Translating content
 
## Timeframe
Ultimately hoping to launch for Veterans Day, if not earlier. IA help would be needed very quickly, in order to implement recommendations in time. Apologies for fire drill.

### Have you worked with CAIA before? 
  - [x] Yes
  - [ ] No

### What's your team’s next step and its timing?

- **Our next step is**: Implementation 
- **Provide date if available**: Happening now

#### Timing for your next step: 
  - [ ] Next week
  - [x] This month
  - [ ] Next month
  - [ ] This quarter
  - [ ] Next quarter
  - [ ] 6 months
  - [ ] 1 year

### Is this timing related to a specific event or Congressionally mandated deadline?
  - [x] Yes - specific event = Veterans Day
  - [ ] No

### Will you release this new product incrementally (for example, release to 25% of users to start)? 
  - [ ] Yes
  - [x] No
  
### When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
- **We expect to launch our product to 100% of users on:** No later than 11/9/2023
  
### Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## Supporting artifacts
*Please provide links to supporting artifacts as available.*
- **Product outline**: 
- **User flows**: 
- **Prototype or mockups**: Included in ticket comment / write up of the scenario here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13532#issuecomment-1749251166
- **If this is in Sketch, which version or specific page should we focus on?**
- **Content source of truth**:
- **Research plan:**
- **Any epics/issues that may be helpful**: A11y notes in more detail if useful: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13532#issuecomment-1749622450
- **Link to testing accounts** (please do not paste them in this ticket): 

### Have you already worked with someone from OCTO leadership?
- [ ] Danielle
- [ ] Beth
- [ ] Mikki
- [ ] Martha

### How do you plan to work with us on this request?
- [ ] I’ll take this to Beth or Danielle’s office hours.
- [ ] I’d like to schedule time to talk about this.
- [x] Let’s work async and meet as needed.
- [ ] Schedule a kick-off call with your team and CAIA for your project **(Recommended)**

 
### Accessibility Help in Slack
The [#accessibility-help channel](https://dsva.slack.com/archives/C8E985R32) in the DSVA Slack, is also available to you as a resource. Everyone is welcome to ask questions or get help from our a11y (accessibility) specialists. Tag `@Terry Nichols` to get a11y help asap.

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag `@Terry Nichols`.**

**Comment by jilladams** [comment]
Additional context re: how the CMS functionality works (incl screenshot): https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13532#issuecomment-1749251166

A11y notes in more detail if useful: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13532#issuecomment-1749622450

**Comment by kristinoletmuskat** [comment]
Thanks @jilladams , the screenshot is especially helpful. This makes sense to me, but I'll check with Mikki tomorrow during our 1:1 and see if she has any flags.

**Comment by kristinoletmuskat** [comment]
Hey @jilladams, it turns out that we do have some concerns about this approach, and would love to chat with @laflannery about her perspective. Laura do you mind if I grab some time on your calendar to chat? I can do some work in advance as well to bring some other options for us to consider.

**Comment by laflannery** [comment]
Yes @kristinoletmuskat go right ahead - tomorrow (Friday) I am free anytime after 1:30 est. I will also share my calendar with you so you can look at times next week as well

**Comment by jilladams** [comment]
Thanks, and feel free to add me if useful. @davidconlon for awareness. 

One note Dave brought up yesterday is that we may ask CAIA to consider an iterative approach where we could launch for Veterans Day, and iterate the breadcrumbs / IA to meet standards after the fact. A "Must / Should / Consider" framework would be helpful as you all think through your stance and suggest alternate paths.

**Comment by kristinoletmuskat** [comment]
@jilladams totally, that makes sense. And I'll set something up for tomorrow and invite you as well, Jill.

**Comment by kristinoletmuskat** [comment]
We did some thinking on the IA side about different options, documented in this mural here: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695321619292/8c3bdcb8a5e55c95c74f42d9a722d34d2b4f4c14?wid=0-1697139491251

**Comment by jilladams** [comment]
From the **[Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695321619292/8c3bdcb8a5e55c95c74f42d9a722d34d2b4f4c14?wid=0-1697139491251&sender=u0b235d03cbd64f7f93673243)**:

* Option 2 is preferred
  * Current implementation is approved for the handling of Breadcrumbs & URLs
* Changes needed [**SHOULD**]:  (needs to be ticketed if this route is approved) 
  * Remove current "See more events" link
  * Replace with 2 links: 
    * 1 specifically pointing to VAMC events.  (Will not appear on Outreach Events.)
    * 1 pointing to the Outreach Events calendar
      * Need to confirm if the Outreach Events calendar link here shoudl appear only on VAMC events that have been promoted to Natl, or can appear on all VAMC events

![Screenshot 2023-10-13 at 12 59 27 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/85581471/fa98a94f-c6fe-490a-949f-abce2e710b0b)
![Screenshot 2023-10-13 at 1 01 49 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/85581471/59f0acc2-2300-4a59-b9c0-6a0738e85f95)


2 other IA notes: 
1. They'd like Public Websites to prioritize [Update Events listings to simplify moving to first, last, or other pages #15680](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15680), to make Events listings put the page number in the URL, so browser back takes you to the page of results you were looking at.
2. They flagged: Outreach Events currently shows some local events that can't be attended nationally, which is weird. We intend to let VHA DM & VEO work out that governance and enforcement.


### Next steps: 
* Kristin to close loop with @mnorthuis to finalize plan / approval
* Jill to do same with @davidconlon.

**Comment by jilladams** [comment]
Notes from today's meeting.
 
### **Attendees:** 
* Sitewide: Laura F, DaveC, Randi, Fran, Jill
* CAIA: Mikki, Martha W
* DS: Matt Dingee 

### Smart breadcrumbs
Smart breadcrumbs exist in the MyHealth space: 
* Appointments Team
* Secure Messaging teams 

It's already A11y reviewed via Collab Cycle for those 2 projects. 

### For this launch
* Our current implementation is approved.

### For future / smart breadcrumbs / Events
* Smart breadcrumbs: Mikki to take smart breadcrumbs to experimental design with DS for more review / expanded use
* Events:
  * may move to IIR team
  * Breadcrumbs for Events need to be overhauled in general, and especially in the context of COPE usage and the future potential for Events at multiple VAMCs

**Comment by jilladams** [comment]
@kristinoletmuskat closeable, you think?

**Comment by kristinoletmuskat** [comment]
@jilladams ya let's do it
