### ISSUE TITLE
EVSS Migration - 526 Submit - Military Service and International Addresses

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#67033]
## Issue Description
Map the military service address to the singular address used in Lighthouse's 526 submit endpoint request JSON (within `mailingAddress` and `currentAddress`. Specifically:
`militaryPostOfficeTypeCode` --> `city` (ex. 'APO', 'DPO', 'FPO')
`militaryStateCode` --> `state` (ex. 'AA', 'AE', 'AP')
This is a literal, direct mapping- as awkward as that sounds. The paper form will literally be populated with 'AA', 'AE' or 'AP' for state, and 'APO', 'DPO', or 'FPO' for city.

and for international zipcodes,
`internationalPostalCode` --> `zipFirstFive`

**NOTE**: this should be done in [Form526ToLighthouseTransform](https://github.com/department-of-veterans-affairs/vets-api/blob/faab1e18197800f34dbe29def33c1d68fc687591/lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb#L7) (our new LH transformation service), as opposed to [DataTranslationAllClaim](https://github.com/department-of-veterans-affairs/vets-api/blob/faab1e18197800f34dbe29def33c1d68fc687591/lib/evss/disability_compensation_form/data_translation_all_claim.rb#L364). This automatically will put the code behind the flipper flag for 526 submit, as well as keep with our general plan of keeping the JSON produced in DataTranslationAllClaim in a stable, baseline state (at least until post-migration, when it can then be safely migrated away from or moved to the new transform service)

## Links
- [LH API spec](https://dev-developer.va.gov/explore/api/benefits-claims/docs?version=current) (`Disability POST /veterans/{veteranId}/526`)
- [slack thread](https://dsva.slack.com/archives/C02CQP3RFFX/p1697068906280869)

---
## Tasks
- [ ] Map it, yo

## Acceptance Criteria
- [ ]  Map the military service address to the singular address used in Lighthouse's 526 submit endpoint request JSON
- [ ]  Cover with unit tests

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sethdarragile6** [comment]
Merged to main. Although the code is not testable (until submit migration is complete), I did a test submission in staging to make sure all was well. It was. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEo5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--18045af0c1cd35b02ddaa4f6fbc15144498a9bd0/image.png)
