### ISSUE TITLE
Publish new accredited rep landing page

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#67034]
## Description

<details>
<summary>Background</summary>

The accredited representation management (ARM) team is designing these new products:

- **Representative status widget (RSW):** This will help Veterans check if they have an accredited representative.
- **Find a representative (FAR) tool:** This will help Veterans find attorneys, claims agents, and Veteran Service Officers (VSO) that serve as accredited representatives. After using this tool, Veterans will need to contact the attorney, claims agent, or VSO to ask if they're available and willing to representative them.
- **Appoint a representative (AAR) tool:** This will help Veterans appoint an attorney, claims agent, or VSO as their accredited representative by pre-filling their Form 21-22 or Form 21-22a. After using this tool, Veterans will need to print and sign their form. Then the accredited representative will need to sign and submit the form online, by mail, or in person.

</details>

<details>
<summary>Resources</summary>

- [Draft landing page](https://prod.cms.va.gov/get-help-from-a-va-accredited-representative-or-vso) (Drupal)
- [Content source of truth folder](https://dvagov.sharepoint.com/:f:/s/SitewideCAIA/EpKqFTllvlxOkDwz2iFgveAB9PjkKVIrJu_TUAkQPbsU0g?e=F7yosj) (SharePoint)
- [Entry point tracker](https://dvagov.sharepoint.com/:x:/s/SitewideCAIA/Efw_1hHtqzJNu77pL8FkKLIBXjboL59fsRmC5-9sY-7adg?e=gaDop7) (SharePoint)
- [Redirect plan](https://docs.google.com/document/d/1Wxue2bQWHXY2fUGTTvRE-WKOUSJkUvUN5avpCooImc0/edit) (Google)

</details>

## Tasks

<details>
<summary>Phase 1: FAR landing page</summary>

- [x] Product team: Collect stakeholder feedback on landing page for staging review
- [x] AP: Update landing page for staging review
- [x] CL: Copyedit landing page for staging review
- [x] AP: Update landing page with react widget
- [x] MZ: Copyedit landing page with react widget
- [x] Product team: Go / no go decision
- [x] MZ: Publish landing page with react widget
- [x] Product team: Manage react widget for staged roll out
- [x] AP: Update landing page without react widget
- [x] MZ: Copyedit and publish landing page without react widget

</details>

<details>
<summary>Phase 2: RSW landing page</summary>

- [x] AP: Update landing page with react widget
- [x] MZ: Copyedit landing page with react widget
- [x] Product team: Go / no go decision
- [x] MZ: Publish landing page with react widget
- [x] Product team: Manage react widget for staged roll out
- [x] AP: Update landing page without react widget
- [x] MZ: Copyedit and publish landing page without react widget

</details>

<details>
<summary>Phase 3: AAR landing page</summary>

- [x] AP: Update landing page with react widget
- [x] MZ: Copyedit landing page with react widget
- [x] Product team: Go / no go decision
- [x] MZ: Publish landing page with react widget
- [x] Product team: Manage react widget for staged roll out
- [x] AP: Update landing page without react widget
- [x] MZ: Copyedit and publish landing page without react widget

</details>

## Criteria
- [x] The FAR landing page is published without the react widget
- [x] The RSW landing page is published without the react widget
- [x] The AAR landing page is published without the react widget

**Comment by aprocik1** [comment]
Hi @chelsealevinson! [This page](https://prod.cms.va.gov/get-help-from-a-va-accredited-representative-or-vso) is ready for your copyedit. Please don't publish it. Thanks!

The engineer is still working on the react widget for this page. After I receive and add it, you'll need to copyedit a small portion of the page again, since the content will change. And then we can publish it after the product team gives us the greenlight. That should be on Tuesday 12/12.

**Comment by chelsealevinson** [comment]
Confirming I copy edited this page and left it in draft form. I'll be on the lookout for the next round. Thanks AP!

**Comment by aprocik1** [comment]
Update: The product team paused the launch of this tool until after the holidays. Reference this [Slack thread](https://dsva.slack.com/archives/C05L6HSJLHM/p1702410884299129) for more information.

**Comment by aprocik1** [comment]
Update: This is the ARM team's new timeline for the work in this ticket:

- **2/27:** FAR tool staging review
- **3/5:** Go / no go decision
   - **3/5:** If go, publish FAR landing page with react widget
   - **3/5-3/18:** Staged rollout
   - **3/18:** Publish FAR landing page without react widget
   - **3/18:** IA redirects the accredited representative [disability hub page](https://www.va.gov/disability/get-help-filing-claim/) and [decision reviews hub page](https://www.va.gov/decision-reviews/get-help-with-review-request/)
   - **3/18:** Content begins updating entry points

**Comment by aprocik1** [comment]
Update: I removed the link to the FAQ page, since we're no longer publishing that page at the same time.

**Comment by megzehn** [comment]
Hi @aprocik1, thank you for organizing this ticket so well! I reviewed the [Get help from a VA accredited representative or VSO](https://prod.cms.va.gov/get-help-from-a-va-accredited-representative-or-vso) landing page and made some minor edits. [Here's a link with the changes.](https://prod.cms.va.gov/node/62667/revisions/view/846810/847538/visual_inline) 

One note: I added a line before the options for submitting the PDF--to better match our pattern. Do you mind reviewing to make sure I'm not mucking up any future react widget language plans? Let me know if there are any concerns. Thanks!

**Comment by aprocik1** [comment]
Thanks for copyediting, @megzehn! I updated the sentence you added to make it clear that a Veteran or accredited representative can submit the form. And a note about language: We're always keeping "accredited" before "representative" on these pages. Here's [the revisions log comparison](https://prod.cms.va.gov/node/62667/revisions/view/847538/847542/visual_inline). I updated the content source of truth documents to reflect these changes.

**Comment by aprocik1** [comment]
@megzehn, the product team isn't launching today. They still hope to launch this sprint, so I'll likely follow up with their updated publish date this week or next. Thanks for your flexibility!

**Comment by oddball-lindsay** [comment]
@megzehn we have found a solution to our launch-blocking issue.  We hope to verify the fix tomorrow, which means we could be ready to launch either late 3/6 or early 3/7.  I''ll know more tomorrow afternoon and will report back!

**Comment by oddball-lindsay** [comment]
I'm back a bit sooner than "tomorrow afternoon" -- given the progress of review today, we think it's safest to not rush things and proceed with the Monday start date.  Here's our updated staged rollout schedule ([full details here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/find-a-representative/release-plan-find-a-representative-2.0.md#staged-rollout-details))

1. Stage A: 10% of users on 3/11 (Monday)
2. Stage B: 25% of users on 3/13 (Wednesday)
3. Stage C: 50% of users on 3/18 (Monday)
4. Stage D: 100% of users on 3/20 (Wednesday) - monitor for any issues through 3/25 EOD (Monday)
   1. On 3/21 (Thursday) CAIA will implement the redirects and search result "best bets", as well as begin updating the entry points
   
I can confirm on 3/20 that we're still on track, after which you should have the green light for removing the react widget and starting the entry point work the following next day (3/21).

@aprocik1 @megzehn let me know if you have any questions!

**Comment by aprocik1** [comment]
@megzehn, the product team confirmed that we're ready to publish the landing page. Thanks for your support on this!

**Comment by oddball-lindsay** [comment]
@aprocik1 @megzehn After realizing that users aren't getting to our landing page easily to make effective use of our % ramp up, we are changing our approach to increasing visibility.  Below is what I hope to be our last update to the schedule:

Stage A: 10% of users on 3/11 (Monday) [complete]
Stage B: 100% of users on 3/13 (Wednesday) + launch best bets for an initial boost to visibility
Stage C: Implement [redirects](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69952) on 3/18 (Monday) for an added boost to visibility
Stage D: Begin entry point work on 3/20 (Wednesday) for max visibility
_The landing page can be re-published without the react widget anytime after 3/20._

I know this thread is getting quite long, so I also added some date mentions to the main ticket summary up top for quick reference.  Thank you both for your patience as we work through the details of this first rollout!  Appreciate you!

**Comment by oddball-lindsay** [comment]
@aprocik1 @megzehn checking in on the timing for the removal of the react widget and entry point work -- do you have an estimate of when those two pieces will be completed?

**Comment by aprocik1** [comment]
@oddball-lindsay, thanks for following up on this. We need to update this page to:

- Remove the react widget
- Match the content that SMEs approved for the FAQ page
- Match the content design that we've drafted for Appoint 1.2

Ideally, we'd make all these updates at one time. That way Megan can copyedit and publish the updated page once. And ideally, we'd publish this page at the same time as your team updates the Find tool in production.

Before then, I need to update the content sources of truth for this page and the Find tool. Do you have a sense of when your team will have time to update the Find tool in production? That would help me figure out when I need to update all the content by and align with Megan on a copyedit / publish date.

**Comment by oddball-lindsay** [comment]
Thanks @aprocik1!  We're flexible on our end -- I wouldn't want to disrupt the current sprint, but can slot in copy updates to the Find tool for the very next sprint.  I'd just need to know a day before that sprint starts.    

We just planned our Sprint 17, but could do this as early as our next Sprint 18 which spans 4/16-4/29.

**Comment by aprocik1** [comment]
Update: The product team and I have aligned the timeline here.

The week of 4/15, we’ll make these updates to the landing page:

- Align content to [final-state source of truth](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/EUgSr7Fu0MlBuyDQVyv4fdYBsERsAUPlpATfw-Ev-1yFDQ?e=uIaFQw)
- Align content to FAQ page, if it’s published by then
- Add a link to FAQ page, if it’s published by then
- Add "rep status" react widget (note: we'll need to copyedit this, which means we'll need Colin to toggle it on and off for us to review both states)
- Add "find a rep" static content
- Remove "find a rep" react widget

The week of 5/6, we'll publish all the updates above to the landing page. The product team will manage the staged rollout for the "rep status" react widget. We'll likely remove the react widget when we make updates to add the "appoint a rep" react widget.

**Comment by aprocik1** [comment]
Update: Megan published this page without the Find a Rep react widget. Here's are the next updates we'll copyedit the week of 4/15:

- Align content to FAQ page, if it’s published by then
- Add a link to FAQ page, if it’s published by then
- Add "rep status" react widget (note: we'll need to copyedit this, which means we'll need Colin to toggle it on and off for us to review both states)

The week of 5/6, we'll publish the updates above. The product team will manage the staged rollout for the "rep status" react widget. We'll likely remove the react widget when we make updates to add the "appoint a rep" react widget.

**Comment by aprocik1** [comment]
Update: The product team decided to stage their Rep Status Widget incremental launch on the [Find a Rep page](https://www.va.gov/get-help-from-accredited-representative/find-rep/). Megan and I have copyedited the content and widget added to that page in staging.

After the incremental launch, we'll publish these updates to the static landing page:
- Add link to FAQ page
- Add "check your rep" H2 and content
- Add Rep Status Widget

**Comment by oddball-lindsay** [comment]
@aprocik1 triple-checking after this pivot -- do you and Megan need anything additional from ARM for those three updates?

**Comment by aprocik1** [comment]
Thanks for following up, @oddball-lindsay. This is what we'll need from your team:
- The RSW ID code (which we've already added and tested in Drupal)
- The date that the RSW goes live to 100% of users
- Confirmation on that date that the RSW has gone live to 100% of users
- Removal of this content in the RSW on the [Find a Rep page](https://www.va.gov/get-help-from-accredited-representative/find-rep/):

> [H2] Check if you already have an accredited representative
> 
> We don’t automatically assign you an accredited representative, but you may have appointed one in the past.
> 
> If you appoint a new accredited representative, they will replace your current one.

**Comment by oddball-lindsay** [comment]
> The RSW ID code (which we've already added and tested in Drupal)

^ I'm not sure if I'm interpreting this correctly.  If you've already added/tested in Drupal, do you still need this ID code?

> Removal of this content in the RSW on the [Find a Rep page](https://www.va.gov/get-help-from-accredited-representative/find-rep/)

^ Curious about how closely we need to coordinate on this.  Would you want the content to be removed from Find a Rep around the same time the landing page is updated with this content?  Or would it be acceptable to remove the content on Find a Rep before or after the landing page updates?

**Comment by aprocik1** [comment]
@oddball-lindsay, we already have the ID code--we don't need anything additional from you or your team. We should coordinate on removing the content from the Find a Rep page and adding it to the landing page. It's not a problem if the both pages have the content for a short amount of time, but we definitely want the Find a Rep page to be updated so that it's less content-heavy for users.

**Comment by aprocik1** [comment]
@megzehn, I added the appropriate content and widget to this page in Drupal: https://prod.cms.va.gov/node/62667/latest

Feel free to copyedit the additions whenever you have time. This page should be published on 5/20.

**Comment by megzehn** [comment]
Confirming I reviewed and published this page, @aprocik1! Thank you for all the coordination!

**Comment by oddball-lindsay** [comment]
I see it on the landing page, thank you for your help @aprocik1 and @megzehn!  🚀 

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/142453186/72042fb6-7c28-4413-bcd5-dee6eb446671)

**Comment by aprocik1** [comment]
Update: The product team plans on launching AAR V1 on January 6, 2025. Here's the tentative timeline:

- 12/9 (or sometime that week): The product team will share the react widget code with CAIA. Then, CAIA will add the react widget to the page.
- 12/17: The product team and CAIA will meet from 10:30-11 am ET to test and copyedit both states of the react widget.
-  1/6: The product team will launch and QA the online form. They will confirm for CAIA that they've done so. Then, CAIA will publish the page with react widget.
- 1/6-1/13: The product team will manage the staged rollout.
- 1/13: The product team will release the online form to 100% of users. They will confirm for CAIA that they've done so. Then, CAIA will publish the entry points to the online form on these pages:
  - [About VA Form 21-22](https://www.va.gov/find-forms/about-form-21-22/)
  - [About VA Form 21-22a](https://www.va.gov/find-forms/about-form-21-22a/)
  - [Get help from a VA accredited representative or VSO](https://www.va.gov/get-help-from-accredited-representative/) (CAIA will remove the react widget and publish the static entry point on this page)

**Comment by oddball-lindsay** [comment]
> 12/17: The product team and CAIA will meet from 10:30-11 am ET to test and copyedit both states of the react widget.

@aprocik1 is there a meeting already on the books for this, or do we need to schedule one? 
I'll be out of office that week, but happy to help schedule something if needed.

**Comment by RLHecht** [comment]
The three pages above are now live on production with the updates and Mikki is setting up the best bets. I think this ticket should be good to close but let me know if there's anything more @oddball-lindsay !

**Comment by oddball-lindsay** [comment]
I think we're good 🎉 Thanks for confirming @RLHecht!
