### ISSUE TITLE
Content edits for #66911

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#67041]
## Info
Content edits according to [support ticket #66911](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/66911)

## Tasks

- [x] Review [support ticket #66911](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/66911)
- [x] Incorporate suggestions provided by customer content related to the [Daily accessibility scan](https://depo-platform-documentation.scrollhelp.site/developer-docs/daily-accessibility-scan-for-va-gov-static-content#Pagefooter-Helpandfeedback) page. Options:
- Remove the page entirely; OR
- Add a notice/update on the page to indicate that it is currently not running. Something similar to: **For technical reasons within content-build, the daily accessibility scan has been temporarily turned off. A new, more stable scan is being built and will be available once completed.**
- [x] Make content updates to the website accordingly
- [x] Prepare page for deployment

## Acceptance Criteria

- [x] Platform website will have improved documentation about the [Daily Accessibility Scan for VA.gov static content](https://depo-platform-documentation.scrollhelp.site/developer-docs/daily-accessibility-scan-for-va-gov-static-content#Pagefooter-Helpandfeedback) being temporarily turned off while a more stable scan is being built.

**Comment by vbellissimo** [comment]
I reviewed support ticket and added a note in blue information box. I sent a pdf copy of the change to Laura Flannery.

**Comment by taylojill** [comment]
Thanks @vbellissimo Laura Flannery approved the update. I'll prepare the page for deployment today.

**Comment by taylojill** [comment]
Paged updated, checked for launch blocking issues. Ready for deployment.
