### ISSUE TITLE
Enforce regression test plan and test plan standards as launch-blocking

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#67042]
Assignee: @shiragoodman 
Peer Reviewer: @it-harrison 

## Description
At the 9/29 and 10/6 meetings with OCTO and Platform leadership, it was decided that VFS teams must present their regression test plan and their test plan at Staging Review or they will not be permitted to launch. The purpose of this ticket is to change the severity of the regression test plan QA standard and the Test Plan QA standard both from warnings to launch-blocking, and to notify VFS teams of the change.

## Impacted Artifacts
[QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards)
[How to complete a QA review for the Staging review touchpoint](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2428010558/How+to+complete+a+QA+review+for+the+Staging+review+touchpoint)
Change history post
Slack announcement

## Tasks
- [x] Edit the QA Standards page on Platform Website to change the warning severity to launch-blocking for both Regression Test Plan and Test Plan - [QA Standards draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2799599665/67042+-+QA+standards)
- [x] Edit the QA Standards operational guidance  - [operational guidance draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2800484353/67042+-+How+to+complete+a+QA+review+for+the+Staging+review+touchpoint+2)
- [x] Draft a change history post communicating what the change is and when it will be enforced at Staging Review (enforcement date: ~~10/26~~11/1) - [change history + Slack announcement](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2800517121/67042+-+change+history+Slack+announcement)
- [x] Draft Slack announcement for #vfs-change-announcements channel following Platform Communication Playbook
- [x] Notify Shira so she can share in Team of Teams
- [x] Once changes approved by Peer Reviewer, publish changes to Change history and QA standards page to Platform Website
- [x] Once we've published to Platform Website, post the Slack announcement to #vfs-change-announcements, linking the change history post. X-share in #vfs-all-teams

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have changed the severity of the Regression test plan standard from warning to launch-blocking
- [x] We have changed the severity of the Test plan standard from warning to launch-blocking
- [x] VFS teams have been notified of the changes to the regression test plan and test plan QA standards
- [x] VFS teams are aware of when the change to the regression test plan and test plan QA standards will be enforced

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@it-harrison this is ready for peer review. All artifacts for review are linked in the Tasks section above. Thanks!

**Comment by it-harrison** [comment]
@shiragoodman the changes look good!

**Comment by shiragoodman** [comment]
@it-harrison the change history and QA standards pages on Platform Website are awaiting publishing. The QA operational guidance page has been updated. Announcement is ready for ToT.

I plan to post to Slack tomorrow once PW is up to date.

**Comment by shiragoodman** [comment]
posted in #vfs-change-announcements today. closing!
