### ISSUE TITLE
Modify content-build repo to publish containers & helm charts

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#67053]
### Description:
Modify the content-build repository to support publishing containers and Helm charts based on specific servers.

### Tasks:
- [ ] Develop a method to create a container image / publishable zip for each build. Consider creating a separate ECR location for the container.
- [x] Establish a Helm chart repository location.
- [x] Implement functionality to publish containers and Helm charts with every code PUSH.

### Acceptance Criteria:
- [ ] A container image or published zip file is created for each build.
- [ ] Containers and Helm charts or publishable zip are successfully published with every code PUSH.

**Comment by JoeTice** [comment]
SPRINT 38 UPDATE - IN PROGRESS. Task is in progress, it required more research/discovery work than anticipated, but is progressing. Currently anticipate it will be completed in Sprint 39

**Comment by patrick-black-oddball** [comment]
For content build and vets-website - a generic nginx container will be used instead of build/versioned container encapsulating the web files. As a result, there is no need for separate helm charts and containers.
