### ISSUE TITLE
Data Automation for Performance Dashboard 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#67059]
## Issue Description
_As a performance dashboard user, I want to view data from both Domo and Google analytics included in a comprehensive format. 

---
## Tasks
- [x] _Define scope of work
- [x] Meet with IRR team to review code
- [x] Identify data to include on dashboard - [Domo/Google Analytics]
- [ ] Testing
- [ ] Implement Automation 

## Acceptance Criteria
- [ ] _Google Analytics and Medallia data visible on Performance Dashboard
- [ ] Automation of data using DOMO as the source of truth  
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
@aubreyarcangel meeting with IRR team 10/6/23 noon.

**Comment by ATMiddleton** [comment]
Dependency on IRR team - @aubreyarcangel is consulting.

**Comment by ATMiddleton** [comment]
Awaiting @newworld2616 to get GFE  and getting access to the S3 bucket.  Awaiting next steps from IIR team.

**Comment by ATMiddleton** [comment]
Still waiting...

**Comment by ATMiddleton** [comment]
IIR team currently has a PR to pull CSAT scores from DOMO.  Still determining how to automate data

**Comment by ATMiddleton** [comment]
@aubreyarcangel and @newworld2616 will meet with Mason and Sarkis to identify all viable options.

**Comment by starlow00** [comment]
Awaiting information from stakeholder. Teammates also OOO. Extending.
