### ISSUE TITLE
[FE] My VA: Remove My VA from unauth header

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#67050]
## Background
The original purpose of having "My VA" in the unauth header on VA.gov was to let users know that there is personalized content once they log in. But now that we reroute from the homepage to My VA at login, we don't need it, so we're going to remove "My VA" from the unauth header (as seen below):

![Screenshot 2023-10-06 at 11 16 29 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/5509e957-0e08-4ee5-b0cc-7a0556c4c6bb)

[Slack thread with sitewide](https://dsva.slack.com/archives/C52CL1PKQ/p1696536173735169)

Information about the [injected header](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite)

## Tasks
- [x] Remove "My VA" from the unauth header using a feature flag to hide it
- [x] Request code review from a dev on the sitewide team (#sitewide-public-websites slack)
- [x] Update tests
- [x] Move to validate and let PM know 

## Acceptance Criteria
When a user is authenticated
- [ ] My VA link _is_ in the header no matter what state the feature flag is set to

When the user is unauthenticated
- [ ] My VA link _isn't_ in the header if the feature flag `my_va_show_header_link` is `false` (Off)
- [ ] My VA link _is_ in the header if the feature flag `my_va_show_header_link` is `true` (On)

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ 
     1. Go to staging.va.gov
     2. See that "My VA" does not appear in the unauthenticated header
     3. Log in with any staging user
     4. Confirm that My VA still appears in the header after signing in

**Comment by Samara-Strauss** [comment]
Looks like there are some bugs with this issue. The unauthenticated nav looks fine, but when I log into staging, this is what I am seeing:

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/34068740/06854b32-527f-4284-a342-e2ddbfbb6490)

The authenticated nav should look like this (this is production currently): 

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/34068740/e3041f77-cffe-4d20-8b56-d35c7eefb6be)

**Comment by ajakabcin** [comment]
@dellerbie I moved this back in progress while you de-bug thanks!

**Comment by ajakabcin** [comment]
Confirmed My VA appears in the auth header (user 192):
![Screenshot 2023-10-25 at 2 50 00 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/e2b8fb01-4d49-4770-a468-257c2e9318fe)

Confirmed My VA does _not_ appear in the unauth header:
![Screenshot 2023-10-25 at 2 50 59 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/d6cc8cf5-0e84-4f74-9384-7e4c51b79bf6)

**Comment by ajakabcin** [comment]
Turned the flag off in production which removes My VA from the unauth header. 
![Screenshot 2023-10-27 at 12 15 14 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/1f8cafec-ebce-4292-b9cf-886d0fc395ed)


And with the fix that went out this week, confirmed My VA still appears in the auth header in production.
![Screenshot 2023-10-27 at 12 02 34 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/8e9b9505-1184-4e83-828e-ddf9e4d17f0b)

**Comment by Samara-Strauss** [comment]
YAY! So excited to see this. I've validated this in production. We should be good to close.
