### ISSUE TITLE
Collect sample of submissions with new asset calculations

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#67060]
## Issue Description
Mike Dewey from VHA has requested 55 examples of recent submissions that went through with the new asset feature flag turned on. He has requested the full submission objects to be sent encrypted over VA email.

---
## Tasks
- [x] Collect 55 example submissions from ArgoCD
- [x] Send over encrypted VA email

## Acceptance Criteria
- [x] Mike has received the 55 transaction IDs from VODA
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
Closing this issue- Scott sent transaction IDs to Mike Dewey.
