### ISSUE TITLE
Research Shadowing Feasibility - Discovery

### ISSUE THREAD

**Issue by alatempa24** [department-of-veterans-affairs/va.gov-team#67063]
## Issue Description
Related to [Team 2's Perigean research options story](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/66260). This ticket will capture Evelyn's unplanned work during the sprint to contribute to the Veteran Shadowing research effort.

---
## Tasks **(in collaboration with Team 2)**
- [x] Review platform to see how recruitment process works
- [x] Meet with Brian Moon from Perigean - what does it mean to find participants that have never filed for 526?
- [x] Identify length of research, what we need to participate, etc
- [x] Meet with CC team to align on their research

## Acceptance Criteria
- [x] Sense of whether research with participants that are new to 526 is possible, and what constraints there are
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by evelynhilbrichdavis** [comment]
Learned the process of recruitment and screener writing. Typically there is a one week lead time to get a study recruited; if we are worried about the complexity of the recruit we can extend lead time. We can also:
1. Slow down the study and take on participants as they qualify/are sourced from Perigean
2. Expand our pool to include Veterans who are experiencing new parts of the flow (claim for increase, supplemental claim, etc).
