### ISSUE TITLE
[CST] Caseflow returning unexpected `aoj`

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#67062]
### Background
Caseflow sometimes returns us appeals that have a aoj of 'unidentified'. This is not an expected value for the `aoj` field, so we have started a conversation with Caseflow in order to determine what is happening with these appeals

### Tasks
- [ ] Create an incident ticket for Caseflow to look into this

### Acceptance Criteria
- [ ] We have provided Caseflow with everything the need in order for them to look into this issue
- [ ] We have a better understanding of why this happens, and if this should be happening

**Comment by jerekshoe** [comment]
Update: on Friday (10/6) I sent Caseflow the SSNs for the Veterans associated with the 2 appeals we were seeing issues with. There was another appeal ID that managed to slip into the mix as well, but at this point I'm unable to find a way to get the `user_uuid` out of DataDog

**Comment by HeatherWidmont** [comment]
We've given Caseflow all the information we have right now. Until they reach out with an update or a request for more information, there's not much we can do.

**Comment by jacobworrell** [comment]
@jerekshoe did Caseflow ever respond? Also did we reach out via email?

**Comment by jerekshoe** [comment]
@jacobworrell I added the YourIT ticket to the description

**Comment by HeatherWidmont** [comment]
Jacob reached out to Marquitte Rivera for an update on the IT ticket. On 12/5/23 she said she would review to see if there was an update not posted in the support ticket & will get back to us to let us know. This conversation is happening on VA email with Jerek, Zach Goldfine, & myself cced.

**Comment by HeatherWidmont** [comment]
Still no response or updates on the IT ticket. @jacobworrell is going to bring it up in the Weekly Product Sync on Monday 2/12

**Comment by pmclaren19** [comment]
No updates from the IT team

**Comment by pmclaren19** [comment]
Moving out of Blocked status and into Sprint Backlog since its not getting much movement.
