### ISSUE TITLE
 🟠 OCTO Product Strategy

### ISSUE THREAD

**Issue by dmkosko** [department-of-veterans-affairs/va.gov-team#67076]
## What are we building
We are looking to align the Product CoP's goals and objectives with those of leadership here at OCTO. 

## Why are we pursuing this opportunity/problem
We feel the teams are working on a wide range of initiatives. We want to meet with leadership to understand their top 3 priorities and align the Product CoP's goals with theirs. This will by default help teams prioritize work, work collaboratively with other crews (when needed), and ensure what they're working on aligns with the organization. 

---
## Tasks
- [ ] Lorem

---
## Definition of Done
- [ ] identify existing versions of each item within the various components of OCTO (ask everyone in product ops to weigh in and then put out a question with list we have in the #product channel.
- [ ] use CoP meetings to review status and get feedback or competing version from product people
- [ ] identify the processes and docs in place that use existing versions
- [ ] identify any work currently underway to update related docs or processes
- [ ] coordinate with the product ops team to create a single, OCTO version of each item
- [ ] update doc links, archive old docs, and update processes to direct users to the new version
- [ ] ensure the new version is listed in onboarding docs and processes

---
## How to configure this issue
- [ ] **Review issue** with the Product Ops team
- [ ] **Prioritize**  
  - label accordingly: 
    - Low Priority - 🟢
    - Medium Priority - 🟠
    - High Priority - 🔴
- [ ] **Add Assignees** (who will do this work?)

**Comment by dmkosko** [comment]
MM from September 28th

Alpa mentioned that funding is a challenge, OCTO unable to line up resources because there is no bucket of dollars (leadership actively working through that, but been a challenge for many years). Matt recently spoke to Kurt and he mentioned that the majority of the budget comes from OIT with a sliver coming from VBA, VHA, etc. 
There does not appear to be a cohesive product strategy at OCTO, we haven’t defined what that focus is. It’s important the business outcomes are in sync with the stakeholder’s business/expectations. We need to work with those in DE to define product strategy across OCTO (Angela’s work may be an outlier). 
We want to get away from teams being/feeling "silohed" and having them collaborate (when possible) about more of a problem-solving approach. What problems exist in your scope that would contribute to solving a problem? These shared objectives would make people/teams feel engaged and give them ownership of the goals. 
Matt has framework already for a product strategy doc (similar to a QBR which is about 6 pages, written narrative/reflection establishing the reasoning and strategy you’re going to propose). Understand the lessons learned, propose next year’s goals (based on reflection and lessons learned), set strategic themes on how you intend to achieve it (do we have the resources in our team or in OCTO to meet these needs). At some point, the teams need to communication to leadership how their work syncs with the goals and how they’re going to achieve it. Gov’t teams will set this. It’s also important to understand each team’s rationale for tracking success; did we succeed, stay the same, or not hit the objective.   
Rely on the teams to define their most related objective to the overall OCTO priority(ies), but not the KR (would need designer input from this group on what will be "reduced", "increased", etc.) Contractor teams set the KRs, it’s beneficial to get them to buy in and help which increases engagement, gives us a way to hold them accountable.
Regarding the Intake and Prioritization sprint, consider it a success, put a pin in it (Alpa to inform the team in the channel)
ACTIONS
Dan to set up a follow-up call between the three of us to discuss 
Dan to schedule a call with us and Charles to understand what his top 3 outcomes are 
After the meeting with Charles, Dan to set up meetings with us and the Portfolio Leads to discuss their top 3 outcomes
Matt to share his version of what a product strategy document could look like and how it can apply OCTO-wide
All: to think about what the document should include 
Dan to determine best ways to communicate to initiative and in which mediums
Alpa to inform the intake and prioritization sprint team that the discovery work was considered a success
