### ISSUE TITLE
FE | Profile | Maintenance | Update validation when phone number is entered with a country-code prefix

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#67070]
## Background
When a user attempts to save a valid 10 digit phone number and includes the `1` country code prefix, a generic system error is returned. We should update the validation to more specifically address the issue and help the user fix the problem.

A valid 10-digital number with the prefix is 11 digits, so it seems that the field validation error should be triggered and save attempt shouldn't be allowed.  That's what happened on an education benefits form, so there's precedent for that elsewhere on the site. Although, this particular message doesn't say exactly what the problem is.
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/55992116/d9ff8703-9ce2-41c7-811c-a6befb0b50ed)

The [pattern guidance on design.va.gov](https://design.va.gov/patterns/ask-users-for/phone-numbers#how-this-pattern-works) says we should allow a format like this `1+703-333-3333` but I can't find any form fields that allow this. And that seems like an uncommon format for a person to enter naturally anyway.

I (Liz) also thought about stripping the `1` if a person enters 11 digits, but that's based on an assumption that the rest of the number is correct and feels like it could risk accuracy of the data.

### Example
Two videos demonstrate the issue

https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/e85f490a-6c5a-4663-afbb-e95bd5915733

https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/d124cda0-538f-4d9e-a501-995202545e13

### VA.gov Experience Standard
[Category Number 00, Issue Number 00](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

## Tasks
- [ ] Determine what makes the most sense to improve validation
- [ ] Update the code

## AC

- [ ] It's clear to the user how they can correct their entry if they enter the US country code prefix and we don't strip it out.

**Comment by andaleliz** [comment]
@it-harrison is it possible for you to include some screenshots, or a video example of this? I don't think you were able to demonstrate it during the midpoint review if I remember correctly and I want to be sure we're all on the same page about the issue. I just tried saving a valid 10 digit number on staging and had no issue. I also observed someone successfully update their phone number in production today.

**Comment by shiragoodman** [comment]
@erinrwhite FYI - I think you had experienced this issue too. Do you know if we captured a video example?

**Comment by erinrwhite** [comment]
@shiragoodman @andaleliz Hi folks! I just created a couple of videos. Basically, including the 1 country code results in a system error rather than a validation error. I'm including videos of editing the phone number from within the new editing subtask and using the form on the contact information page. Same error in both places: "Alert:
We’re sorry. We can’t update your information right now. We’re working to fix this problem. Try again later."


https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/e85f490a-6c5a-4663-afbb-e95bd5915733


https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/d124cda0-538f-4d9e-a501-995202545e13

**Comment by andaleliz** [comment]
@erinrwhite thank you so much! That is incredibly helpful. I'll add some clarifying information to the description.

**Comment by erinrwhite** [comment]
The plot thickens. It looks like this is happening if any # of digits over *or under* 10 is entered in the field. This is also happening on the home and work phone fields.

**Comment by adamwhitlock1** [comment]
I actually have a PR open for the validation to be updated for the cases of under or over 10 digits, as we recently updated our validation rules for letters and introduced that bug. As soon as I can get tests passing that will be reviewed and merged.

**Comment by andaleliz** [comment]
@adamwhitlock1 I updated the description for more clarity around this - it's very similar to [the issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67378) we saw yesterday, but not exactly. Not sure how you want to approach the two but lmk if I can help at all.

**Comment by mtcA6** [comment]
we added validation rules that requires only 10 digits, this should solve for the issue highlighted here.
