### ISSUE TITLE
Redirect Request | Chapter 36 Form

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#67075]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [x] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live?
Choose one:
- [ ] On a specific date, connected to a program or publishing requirement. **DATE:**
- [ ] Any day prior to a deadline/latest possible date. **DEADLINE:** 
- [ ] Any day after an earliest possible date. **EARLIEST DATE:**
- [ ] During a specific date range: ***EARLIEST DATE TO LATEST DATE:***
- [x] No hard timing requirements, publish when possible.

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
[https://www.vba.va.gov/pubs/forms/VBA-28-8832-ARE.pdf](https://www.vba.va.gov/pubs/forms/VBA-28-8832-ARE.pdf) | [https://www.vba.va.gov/pubs/forms/VBA-25-8832-ARE.pdf](https://www.vba.va.gov/pubs/forms/VBA-25-8832-ARE.pdf)

**Link to campaign landing page request issue:**

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [ ] IA: Request is vetted and documented and implementation plan is clear 
- [ ] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by steele-lm** [comment]
@DLarson-Oddball

**Comment by mnorthuis** [comment]
Hi @steele-lm, Unfortunately we do not implement redirects on documents.

**Comment by jilladams** [comment]
Slack convo about whether Public Websites will be able to make this redirect: https://dsva.slack.com/archives/C52CL1PKQ/p1697475759732439?thread_ts=1697141856.745119&cid=C52CL1PKQ

**Comment by jilladams** [comment]
Email sent to VBA Forms managers to ask them to help follow up, cced Jenny Mayo and Mikki.

The PDFs noted here live on VBA file servers that are tied to the Forms DB. We in Sitewide / Platform do not have dominion over the Forms DB, or the VBA TeamSite (www.vba.va.gov). We think that means this redirect will either have to happen: 
* Within the Forms DB somehow? 
* Within the TeamSite, managed by a TeamSite administrator.
 
Redirect documentation implies this case falls into the [TeamSite Subdomain > TeamSite subdomain redirect pattern](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/redirect-implementation-strategy.md#5-redirects-from-subdomains-subdomainvagov--to-subdomains-subdomainvagov-). The client side redirect option listed there won't work in this case, because the original PDF has already been removed and returns a 404. So we'll have to see what Forms DB folks say.

**Comment by jennymayoco** [comment]
Hi @steele-lm, unfortunately we won't be able to move forward with this redirect request since the PDF doesn't live on our servers.

[Slack thread with PW team's update on request](https://dsva.slack.com/archives/C52CL1PKQ/p1698096534402779?thread_ts=1697141856.745119&cid=C52CL1PKQ)

**Comment by jennymayoco** [comment]
Update from Kevin Reid via email: *We found a POC at PITC who could put the redirect in place. It is redirecting now.*

Checked the [28-8832 PDF link](https://www.vba.va.gov/pubs/forms/VBA-28-8832-ARE.pdf) and it redirects to 25-8832. @jilladams @FranECross does this need to be moved to your repo for final validation or is this good to close?

**Comment by steele-lm** [comment]
@jennymayoco Great news! Thank you!

**Comment by FranECross** [comment]
@jennymayoco I'll need to lean on @jilladams to answer your question. 😁

**Comment by jilladams** [comment]
Validated in prod that the "from" link resolves to the "to" link. Closing!
