### ISSUE TITLE
NoK/EC Complete read-only integration with API

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#67088]
## User story

As a user, I want the NOK/EC page at `va.gov/profile/contacts` to be populated with live data from my account, so that I feel confident that VA has the correct information about my personal health care contacts.

### Notes
- If we haven't yet gotten permission to access the read/write endpoint in #69061, the data we need is available from a read-only endpoint that vets-api already has access to. (Profile v3 Service)
- [vets-api Endpoint Tutorial](https://depo-platform-documentation.scrollhelp.site/developer-docs/backend-endpoint-tutorial)
- [vets-api Adding an External Service Integration](https://depo-platform-documentation.scrollhelp.site/developer-docs/adding-a-new-external-service-integration)
- [vets-api VA Profile Integration](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-profile)
- [vets-api Record VCR Cassette](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/tutorials/record_vcr.md)
- [VA Profile APIs](https://dvagov.sharepoint.com/sites/OITEPMOVAPROPUB)
- `profile_contacts` feature flag

## Acceptance criteria

- A user visiting Profile sees a Personal health care contact link in the side navigation
- A user with existing personal health care contacts in VES (Veteran Enrollment System) can view their current data under Profile and can easily determine how to update the information
- A user without existing personal health care contacts in VES can easily see that there are no personal health care contacts in the system, and how to get them added
- ~Multiple NOK/ECs displayed~ Moved to ticket ticket: #72549 
- ~Success/failure of the API request is monitored and reported~ Moved to ticket: #76239

## Tasks
- [x] Verify that we have read access
- [x] Request write access for @department-of-veterans-affairs/vfs-mhv-integration team on `vets-api` repo
- [ ] Determine user accounts for manual testing of feature. (Needs icn in MPI, correlated Health Record in Enrollment System)
- [x] QA: create test cases in TestRail
- [x] QA: confirm deployment to stage
- [ ] QA: test feature/report bugs
- [ ] QA: Regression test (if bugs found/fixed)

**Comment by wesrowe** [comment]
Notes from refinement:
- Profile is moving to a "hub" design pattern with cards, still undergoing research

**Comment by radavis** [comment]
Recommendation from VA Profile team is to use the existing Profile-v3 integration to read Health Benefit/Associated Persons information, potentially saving 0.5s or so compared to making a separate request.

**Comment by dcloud** [comment]
Here are [selectors in the profile FE code](https://github.com/department-of-veterans-affairs/vets-website/blob/d2c10f8eb3ff3891b71cbc3520092aec5b0f4dc0/src/applications/personalization/profile/selectors.js#L166-L182) that filter contacts by emergency contact or next of kin. Essentially, filtering contacts on `contactType` using regular expressions matches.

**Comment by dcloud** [comment]
Right now the v3 VA Profile endpoint is only pulling military info, per: https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/va_profile/profile/v3/service.rb#L21. Probably want to update this to pull health benefit info, but do we want to do that in the same request?

**Comment by dcloud** [comment]
Prior art for FE here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/66602#issuecomment-1745076405 (screenshots, links to designs)

Remember to check/run the vets-api mocks for personalization when checking locally

**Comment by radavis** [comment]
Questions/Talking points for next meeting with VAPRO team:

- Test user data for integration server: Do user records need to be created in MPI's development instance? If not, which OID/idWithAaid (aka - user ids) should we be using?
- Creation of associatedPerson records for a test user in source systems (Vista/ES), or mocking of data at the VAPRO integration server?
- Follow-up on email question about relationship-type data access from health benefit service.

**Comment by fbonds** [comment]
Test cases created (previously)

https://dsvavsp.testrail.io/index.php?/suites/view/1883&group_by=cases:section_id&group_order=asc&display_deleted_cases=0

On profile page I see EC/NoK info and instructions at top regarding how to edit them.  

Questions:  @wesrowe @radavis 

- At this point is this live data being pulled from vet record or static data?  
- Nothing else appears directly actionable on this screen. Should I be able to edit these directly?
- If live data, how may I create/edit an existing user such that they don't have EC/NoK to verify that path?    

<img width="679" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG9XQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bee4f850d4046c5dec7213fef22253fd936e266f/image.png" alt="image.png" />

**Comment by LynneJohnson224** [comment]
@fbonds we have not started on edit functionality. This data should be read only.

**Comment by radavis** [comment]
Note that staging.va.gov will continue to serve static data until department-of-veterans-affairs/vets-api#15132 is merged.

**Comment by wesrowe** [comment]
Richard found test users:
> Logging in w/ [vets.gov](http://vets.gov/).[user+11@gmail.com](mailto:user+11@gmail.com) and visiting /profile/contacts will show you an Emergency Contact, [vets.gov](http://vets.gov/).[user+14@gmail.com](mailto:user+14@gmail.com) will show a Next of Kin. Let me know if you don't have access to [tud.vfs.va.gov](http://tud.vfs.va.gov/) to get the passwords for these accounts.

**Comment by wesrowe** [comment]
user 11 has one NoK (not EC...):
<img width="325" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/4054752/98bf53e9-56ca-44ff-9533-decf969e18e8">

user 14: Jerry doesn't have either one?
<img width="416" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/4054752/4aeeada7-5d19-41b3-97fe-6f05960d9ff5">

**Comment by radavis** [comment]
@wesrowe Thanks for the feedback. The api changes from department-of-veterans-affairs/vets-api#15418 have not yet been deployed, hence, what you're seeing.

**Comment by wesrowe** [comment]
can this close? I saw a slack thread yesterday with both an NoK and EC in the screenshot.

**Comment by radavis** [comment]
@wesrowe The frontend work has not yet been merged. The ACs here would need to change in order to close.
