### ISSUE TITLE
Identity Dashboard FE - Fix sign-in

### ISSUE THREAD

**Issue by ianmagenta** [department-of-veterans-affairs/va.gov-team#67084]
## Description
Right now sign-in fails when clicking the login button. We need sign-in to function correctly and also properly maintain the user's session.

## Tasks
- [x] Ensure sign-in works as intended
  - [x] Change backend url from `https` to `http`
  - [x] Remove cookie timer from `layout.js`
  - [x] Update `requestToken` return type
  - [x] Fix problems with `AuthCallback` component
- [x] Update `layout.js` be a server-side component that enforces authentication
- [x] Add route cache invalidation
