### ISSUE TITLE
[Research] Team Research Ops Resources 

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#67095]
## Issue Description
Team research ops task: to create useful and centralized tools to help with our research practice. 

The goal of the landscape Mural document is to be a single source of truth reference for the team on all things research process. This includes links to helpful resources and templates on the Platform site, outlines for our team to use when creating tickets and anything else needed in one visual landscape resource.

The goal of the synthesis Mural template is to have a template with all the parts and pieces we have been using in recent Mural boards synthesis work. Create a blank template to build on and copy from. 

---
## Tasks
- [x] Create a research landscape Mural document 
- [x] Create a research synthesis Mural template

## Acceptance Criteria
- [x]  Refinement to team research resources 
---

**Comment by jessicastump** [comment]
A start of a list/resource can be found [here on github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/README.md), will need to update this page/link to new resources as part of this work too :)

**Comment by IMHieuVo** [comment]
[Reference - Research Landscape](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697039977149/b8a5ea90748703093cdcb405b84463e515cfea2a?sender=ubf5503bf47b6eb1e92730053): This mural has all the helpful links that one would use for research, set up in a water-themed landscape. Beach = Research Prep, Ocean = During Session, Pier = Research Synthesis.

[Template - Research Synthesis](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1696943969535/ebeb7ce2f9bb547e6652d68ee6dd2e8b8f3fb55e?sender=ubf5503bf47b6eb1e92730053): The UX team has been using the Mural as a research synthesis/organization area. This Mural is a clean template with all the labels and tools they typically use in the synthesis.
