### ISSUE TITLE
Caching documentation

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#67112]
### Summary
We don't have any "Caching in Vets-API" documentation. There was recently a [support question](https://dsva.slack.com/archives/CBU0KDSB1/p1696600908316889?thread_ts=1696436842.377339&cid=CBU0KDSB1) that could possibly have been avoided if we'd had some documentation. This will also help Platform backend devs learn about caching in vets api.

### Tasks
- [x] Create documentation in Confluence (in Tech Team 1 section or in your personal space. somewhere where it won't get published to Platform Website yet)
- [x] Get documentation reviewed
- [x] Move doc to a spot in the [Developer docs](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886289964/Backend+developer+documentation) section of Confluence so it gets published to Platform Website.

### Acceptance Criteria
- [x] doc is reviewed and published to [Platform Website](https://depo-platform-documentation.scrollhelp.site/developer-docs/backend-developer-documentation).

**Comment by LindseySaari** [comment]
This has been moved to the Developer Doc section here: https://vfs.atlassian.net/wiki/spaces/pilot/pages/2806775890/How-to+Guide+Caching+with+Redis-Namespace+in+Vets+API
