### ISSUE TITLE
Incoming Issues Tracking - Per Sprint #15

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#67116]
## Issue Description
Contact Center will review and track all incoming issues escalated from VEO_
---
## Tasks
- [ ] Tabulate incoming issues into categories - Tier 2/Tier 3/Tier EVSS
- [ ]  Create a grid displaying the number of incoming issues for each category
- [ ]  The grid shall include how many of the existing issues have been resolved
- [ ]  The grid shall include the number of unresolved issues for each category
- [ ]  Publish report for leadership at the end of each Sprint

## Acceptance Criteria
- [ ]  Report published for leadership viewing
- [ ]   Report shall include quantity of incoming issues, resolve issues and remaining unresolved issues on a biweekly end of Sprint basis

## Acceptance Criteria

- [ ] **Scenario 1: Tabulate incoming issues into categories**
  - Given a set of incoming issues
  - When the issues are categorized into Tier 2, Tier 3, and Tier EVSS
  - Then the issues should be tabulated into their respective categories

- [ ] **Scenario 2: Create a grid displaying the number of incoming issues for each category**
  - Given the categorized incoming issues
  - When a grid is created to display the number of issues for each category
  - Then the grid should accurately show the quantity of incoming issues for each category

- [ ] **Scenario 3: Include resolved issues in the grid**
  - Given the categorized incoming issues
  - When the grid is created
  - Then the grid should include the number of resolved issues for each category

- [ ] **Scenario 4: Include unresolved issues in the grid**
  - Given the categorized incoming issues
  - When the grid is created
  - Then the grid should include the number of unresolved issues for each category

- [ ] **Scenario 5: Publish report for leadership at the end of each Sprint**
  - Given the end of a Sprint
  - When a report is published for leadership viewing
  - Then the report should be available for leadership to view

- [ ] **Scenario 6: Report includes quantity of incoming, resolved, and unresolved issues**
  - Given a published report for leadership viewing
  - When the report is accessed
  - Then the report should include the quantity of incoming issues, resolved issues, and remaining unresolved issues on a biweekly end of Sprint basis

- [ ] **Scenario 7: Configure issue attachment to a Milestone**
  - Given the issue configuration settings
  - When the issue is attached to a Milestone
  - Then the issue should be marked as completed based on the specified Milestone

- [ ] **Scenario 8: Configure issue attachment to an Epic**
  - Given the issue configuration settings
  - When the issue is attached to an Epic
  - Then the issue should be associated with the specified Epic as part of the overall body of work

- [ ] **Scenario 9: Configure issue labels with Team**
  - Given the issue configuration settings
  - When the issue is labeled with a specific Team (e.g., `product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
  - Then the issue should be categorized under the corresponding Team

- [ ] **Scenario 10: Configure issue labels with Practice Area**
  - Given the issue configuration settings
  - When the issue is labeled with a specific Practice Area (e.g., `backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
  - Then the issue should be categorized under the corresponding Practice Area

- [ ] **Scenario 11: Configure issue labels with Type**
  - Given the issue configuration settings
  - When the issue is labeled with a specific Type (e.g., `bug`, `request`, `discovery`, `documentation`, etc.)
  - Then the issue should be categorized under the corresponding Type
  - 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
<img width="526" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTFuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4af9238e7023dcaece2dd6baae6ee11b21234e48/image.png" alt="image.png" />
