### ISSUE TITLE
Review eBenefits Research Findings from 2020

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#67122]
## Issue Description
[Additional research from the eBenefits flow](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/ebenefits/view-update-POA/research-design) from 2020 has been uncovered.  How might this affect our MVP?

---
## Tasks
- [ ] Review research
- [ ] Discuss relevant findings with affected team members and determine path forward
- [ ] Add summarized findings to existing [Secondary Research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/research/2023-09-secondary-research/2023-09-secondary-research-accredited-representation-management.md)

## Acceptance Criteria
- [ ] Research has been discussed with the team
- [ ] Summarized findings have been added to the Secondary Research report

**Comment by oddball-lindsay** [comment]
Next steps from @jfinnerty13 

1. Research change: recommending reducing the amount of participants with disability claims in appeals to get a more diverse audience
2. Veterans found the legal copy confusing and unhelpful. How can we reduce/simplify it for easier understanding? Is there someone in legal we can work with?
3. Veterans wanted more context around the purpose of the form and what steps they're going through. Recommending updating or incorporating a page that explains what the 21-22 is + PoA
   1. Do we create a new page or repurpose the existing one? https://www.va.gov/disability/get-help-filing-claim/
5. Veterans were looking for distance and location when finding a rep which confirms our hypothesis on locations importance
   6. Some other info Veterans were looking for; gender, claims 'won', rep specialty, rep rating system, hours + availability
   7. Veterans also wanted to see rep info in a table format
8. Veterans didn't understand insurance; recommend providing explanations on what and why
9. Veterans couldn't find PoA on VA.gov
   10. Recommend revisiting where it lives under disability and retesting
   11. Recommend updating search terms so it shows under search with PoA searched
12. Veterans were looking for a way to mark MST on the form
13. Research recommended having an option to search VSO or representative name so Veterans can search per referrals or word of mouth
14. Veterans commented that VA Number + SSN request was redundant/confusing. Provide context on when/which are needed
15. Participants with fewer results wanted to see remote/further rep options - recommend to expand search until they get a rep to work with

**Comment by jfinnerty13** [comment]
Still WIP

**Comment by jfinnerty13** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/research/2023-09-secondary-research/2023-09-secondary-research-accredited-representation-management.md
