### ISSUE TITLE
[Design] Confirmation Screen - v.02

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#6712]
## User Story 
As a designer, I need to update the _Confirmation screen_ to align with the MVP and feedback received from VSP

## Goal
Create a second iteration of the MDT's _Confirmation Screen_ incorporating VSP feedback and MVP requirements.

---
## Tasks
- [x] Remove the "Order history" CTA and associated content from the current Order Confirmation screen
- [ ] (Optional) Add a new CTA that redirects the veteran from the Order Confirmation screen once they've reviewed all content and/or printed the page for their records 
- [x] Update "Qty" to "Quantity" to align with VA.gov content recommendation
- [x] Upload updated design to Invision and mark initial focus point
- [x] Link updated documentation to this ticket

## Acceptance Criteria
- [ ] The "Order history" CTA is no longer part of the MDT ordering flow 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by rileyorr** [comment]
@mr0sari0 & @mojaray2k the updated prototypes and content can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-confirmation-screen.md). 
We explored adding a "Return to VA.gov" button at the bottom of the screen, but I couldn't find consistency across forms' confirmation screens so I am going to bring it up to VSP at our next review. Adding a button linking back to VA.gov's homepage shouldn't be a big deal if we get feedback that it should be added.
