### ISSUE TITLE
Update form detail pages for 21-0845 and 21-0972 with link to online form

### ISSUE THREAD

**Issue by megzehn** [department-of-veterans-affairs/va.gov-team#67129]
## Issue Description

2 online forms are now live to 100% of users. We need to make a some small adjustments to these pages to reflect this update:

- Supporting forms
- About form 21-0972
- About form 21-0845

---
## Tasks
- [X] Remove widget copy from Supporting forms page and replace with link to online form (MZ)
- [X] Add online form link to form detail pages (MZ) 
- [ ] Copy edit changes to supporting forms page (Chelsea) 
- [ ] Copy edit and publish form detail page (Chelsea) 
- [ ] Copy edit and publish form detail page (Chelsea) 

Note that I'm also updating the supporting forms page with more details on how to submit, so at this time we should hold on publishing that page. 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by megzehn** [comment]
@chelsealevinson, I made the changes on the 2 form detail pages. If you can review the links and publish them tomorrow that would be awesome! Let me know if you have any questions.

**Comment by megzehn** [comment]
I'm going to go ahead and close this one out since we can track copy edits for the supporting forms page in this ticket: https://github.com/orgs/department-of-veterans-affairs/projects/929/views/11?filterQuery=assignee%3Amegzehn&pane=issue&itemId=36682582
