### ISSUE TITLE
Update Orientation instructions - After uploading your recording

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#67128]
Assignee: @erinrwhite 
Peer Reviewer: @shiragoodman 

## Description
The current [Orientation Host/Zoom Host Guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2656731745/Orientation+Host+Zoom+Host+Guidance) guidance instructs Platform to set the old orientation video to "private" before the new orientation video has been published to Platform Website. This means that if anyone tries to access the video before the page is published (a ~24 time period) they won't be able to since they're attempting to access a private video. 

The purpose of this ticket is to reorganize the Orientation host/Zoom host guidance so that hosts aren't setting the old video to Private until the Platform Website page is published. A step should also be included for the host to verify the page has been published with the latest orientation recording.

## Tasks
- [ ] Update the guidance so the old recording is set to private AFTER the Platform Website page is published with the new recording

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] VFS team members are no longer trying to access recordings set to Private
- [ ] Platform orientation hosts check to ensure that the recording link updated correctly

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
@shiragoodman I went ahead and [updated the page in production](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2656731745/Orientation+Host+Zoom+Host+Guidance#After-uploading-your-recording). Can you do a quick read to see if any of the wording is wonky? Thank you!

**Comment by shiragoodman** [comment]
@erinrwhite yes, this looks great to me. However, going to pull in @rmtolmach as she experienced this issue first hand.

Rebecca - would you be able to take a look at the updated Orientation guidance Erin linked above to see if that's a better process for us to follow? Please let us know if there's any concerns. This should take approx. 3 minutes.

**Comment by rmtolmach** [comment]
@erinrwhite @shiragoodman LGTM!! 🚀

**Comment by erinrwhite** [comment]
@rmtolmach @shiragoodman woo hoo! Closing 😄
