### ISSUE TITLE
App is not running locally

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#67139]
## Issue Description
Colin created our new new app in the `src/applications/representatives` directory in `vets-website` and it worked for him locally. When I pull his branch none of the routes worked for me but all other vets-website apps worked for me. We spent several hours trying to figure out what was going on. We finally decided that I would recreate the app in `src/applications/representative` (singular - we decided that would be better than `representatives` because a vet can only have one rep) and get it running locally. When I was done, he pulled my branch and it wouldn't work on his machine. We were stumped.

---
## Tasks
- [x] Pairing sessions between Holden and Colin
- [x] Figure out how to get the app running on both of our machines locally
- [x] Create app in `src/applications/representative`

## Acceptance Criteria
- [x] Developers are able to deploy the app locally

**Comment by holdenhinkle** [comment]
It turns out we needed to add the following json to the `src/applications/registry.json` file in the `content-build` repo:

```
  {
    "appName": "Find a Local Representative",
    "entryName": "representative-app",
    "rootUrl": "/representative",
    "productId": "decb6c85-abcd-44b5-b722-550905f48dd7",
    "template": {
      "vagovprod": false,
      "layout": "page-react.html"
    }
  }
```

... and `appName`, `entryName`, `rootUrl` and `productId` had to match the values in the `src/applications/representative/manifest.json` in `vets-website`.

Here's are the resulting PRs:

- vets-website - https://github.com/department-of-veterans-affairs/vets-website/pull/26074
- content-build - https://github.com/department-of-veterans-affairs/content-build/pull/1740
- devops - https://github.com/department-of-veterans-affairs/devops/pull/13561
