### ISSUE TITLE
Document Management System

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#67130]
### Description
VHA stakeholders have requested that we relocate the PDF version of all electronic submissions to DMS (Document Management System) instead of SharePoint

## Definition of Done

- [ ] Establish contact with focal from DMS
- [ ] Determine timeline and DMS requirements to accept PDFs
- [ ] Establish service to DMS 
- [ ] Work with DMS to test PDF delivery
- [ ] Notify VAPO who will contact stakeholder for downstream testing and validation
- [ ] Once approved, connect with SharePoint to stop sending PDFs and remove relevant code.

### Collab Cycle Touchpoints
- [ ] **Kickoff**  (Collab Cycle Ticket) ENTER TICKET #
- [ ] **Design Intent** ENTER DATE & TIME / ENTER TICKET #
- [ ] **Sitewide Content & Information Architecture (IA) Intake Request** ENTER TICKET #
- [ ] **Research Plan Review** ENTER TICKET #
- [ ] **Analytics Request** - (Submit once KPI's are determined) ENTER TICKET #
- [ ] **Midpoint Review** Scheduled for ENTER DATE & TIME
- [ ] **Contact Center Review** (Submit tix 2 weeks prior to launch) ENTER TICKET #
- [ ] **Staging Review**  (Reminder: Staging Reviews require a 4 day lead time)_Scheduled for ENTER DATE & TIME
- [ ] **Privacy and Security, & Infrastructure Review** ENTER TICKET #

**Comment by Tom-Davis** [comment]
Denise will add her current understanding of this ask and then we will work with Kevin to align with DMS and create the tickets for that.

**Comment by denisecoveyduc** [comment]
UPDATE: As of April 24 VHA has decided to maintain the current process and structure for PDF document storage and reference. At this time the debt team can consider this work no longer required and all tickets, epics and this super epic can be closed. @Tom-Davis Could you close out and notify the BE team?

**Comment by Tom-Davis** [comment]
Closing as this effort is no longer needed at this time per @denisecoveyduc .
