### ISSUE TITLE
Pension Team Sprint 5 Plan: 10/11/2023—10/24/2023

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#67136]
## Sprint 5: 10/11/2023—10/24/2023

- Outages (PTO, holiday, or unplanned): 

## Sprint themes:

- Continue access and onboarding for newest team members
- Continue knowledge transfer for all practice areas & progress in our knowledge transfer of current state of Pension deactivation activities

## Notes:

- [Link to temporary task tracking](https://docs.google.com/document/d/1RNaiFAjCijw3YKw8-IoDoG0dvgWAUIaJgONnOvzUQFU/edit?usp=sharing) for team members without access to Zenhub yet.

## Goal(s):
**General/continued access onboarding**

- [ ] New VFS Team Member Template [Tai Wilkin] #65134
- [ ] New VFS Team Member Template [Todd Rizzolo] #64168
- [ ] Platform Orientation Template [Matt Knight] #63641
- [ ] New VFS Team Member Template [Jamie Jansson] #66582
- [ ] New VFS Team Member Template [Maya Carroll] #66064

**Design/Research**

- [ ] Start research of past Pension-related documentation #67211
- [ ] Re-create & reorganize Fiorella's file and do some VA design system audits. #67011
- [ ] Incorporate additional design, a11y feedback from CAIA #66966 - **Pending CAIA feedback**

**Engineering**

- [ ] Research ITF date for Pension #66958
- [ ] Research transition from Central Mail API to Lighthouse for Pension #66956
- [ ] SPIKE | COE Failure Points and Sidekiq Jobs #64811
- [ ] SPIKE | Pension 527 Failure Points and Sidekiq Jobs #65402
- [ ] SPIKE | Burial 530 Failure Points and Sidekiq Jobs #65403
- [ ] CH 31 Form Payload Redirect #65386
- [ ] Environment save issue with Pension form #66531
