### ISSUE TITLE
[FE / DESIGN] FE help with CodePen Template Setup

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#67142]
## Issue Description
Creating an accessible prototyping tool to have ready when wanting to run usability tests with Veterans.

This is a ticket to make sure the templates / style sheets / header/footer are ready to go for future needs. This work will need to be done as some working sessions with Designer/FE and setting up the CodePen account (VA Applications Workspace via Ad Hoc) for quick future prototyping. 

[Platform documentation link](https://depo-platform-documentation.scrollhelp.site/research-design/accessible-prototyping-with-codepen)

---
## Tasks
- [ ]  Review linked stylesheets created by other teams
- [ ]  Determine if our Collection has the correct templates and parts needed
- [ ]  Review [Ad Hoc resource doc](https://docs.google.com/document/d/1V2kibgoyeo5K3PL5QCVSNiNgJOboe9Plxm38iSo2kFU/edit)
- [ ] Review  [Getting started doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/a597d435436a866472d2d002b32bebb5adb0f661/products/identity-personalization/discovery-research/codepen-prototyping.md)
- [ ] Create/adjust any CodePen templates needed
- [ ] Create any documentation for future use by team 

## Acceptance Criteria
- [ ] CodePen template page and form stylesheets are setup and ready to use for future quick prototyping needs

---

**Comment by jessicastump** [comment]
@mkerns1 Here are all the Pens created in the Ad Hoc pro account / Health enrollment collection:

- [Copy VA Design System](https://codepen.io/team/VA-gov-Applications/pen/wvRYmZr)
- [Copy General Template](https://codepen.io/team/VA-gov-Applications/pen/vYvVRqX)
- [EZR intro page](https://codepen.io/team/VA-gov-Applications/pen/xxmyWvK)
- [EZR - Veteran info - personal information](https://codepen.io/team/VA-gov-Applications/pen/vYvVrpQ)
- [EZR - Veteran Info - Mailing address](https://codepen.io/team/VA-gov-Applications/pen/dywgKqg)
- [Test - Full Footer](https://codepen.io/team/VA-gov-Applications/pen/KKbrYqB)
- [Need help health footer](https://codepen.io/team/VA-gov-Applications/pen/PoXxWMp)

**Comment by hdjustice** [comment]
Codepen is not being used.
