### ISSUE TITLE
Create Test Accounts for User Accessibility Testing

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#67150]
## Issue Description
After our MVP launches, we will want to run a user accessibility test to ensure our MVP provides a good experience for all types of users.  We want to avoid users using their personal logins for security reasons, so we will need test logins to conduct this type of study.

Some requirements for creating test accounts:

1.  Test data should be sufficiently random, almost entirely mocked, and when something real is necessary, reviewed thoroughly for de-identification issues
2.  Passwords should be reset between sessions

Source: [Slack discussion in #research-ops](https://dsva.slack.com/archives/C0216PL32HJ/p1687889620296049?thread_ts=1686072877.922199&cid=C0216PL32HJ)

---
## Tasks
- [ ] Create test accounts with random data
- [ ] Ensure test account passwords are reset between sessions

## Acceptance Criteria
- [ ] Test accounts are created with random data
- [ ] Test account passwords are reset between sessions
