### ISSUE TITLE
Create Prototype Helm Chart for vets-api

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#67154]
### High-Level User Story ###
_As a DevOps engineer, I need a prototype Helm chart for vets-api so that the application can be managed and deployed seamlessly in Kubernetes._

### Tasks ###
- [ ] Conduct a discovery phase to understand the unique requirements of vets-api for Kubernetes deployment.
- [ ] Review any existing Helm charts related to vets-api and determine the need for modifications or the creation of a new Helm chart.
- [ ] Design and develop the prototype Helm chart for vets-api.
- [ ] Extend the existing Terraform scripts to support RDS creation tailored for vets-api.
- [ ] Modify the vets-api repository to automate the publishing of both the application's container images and the associated Helm chart.
- [ ] Expand the Terraform configurations to enable Helm-based deployment of vets-api.
- [ ] Implement a manual trigger and display mechanism for Helm deployments (if not already existing from previous Helm charts).

### Acceptance Criteria ###
- [ ] A Helm chart for vets-api is available and tested for deployment in a Kubernetes environment.
- [ ] Terraform scripts successfully create an RDS instance suitable for vets-api.
- [ ] Upon pushing changes to the vets-api repository, a container image and Helm chart are automatically published.
- [ ] Vets-api can be successfully deployed in Kubernetes using the Helm chart.
- [ ] (If applicable) The manual trigger and display mechanism works seamlessly for Helm deployments of vets-api.
