### ISSUE TITLE
Create a Preview Environment to support a WASA Scan

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#67158]
### High-Level User Story ###
_As a DevOps engineer, I need a Preview Environment that is ready to support a WASA scan, so we can submit the request, and begin the next step of approval in making these publicly accessible.

### Tasks ###
- [ ] Develop prototype Helm charts for the core components:
  - [ ] vets-api
  - [ ] vets-website
  - [ ] content build
- [ ] Automate the collection of helm charts into a single flow
- [ ] Create UI to create/destroy instances of va.gov
- [ ] Conduct internal testing
- [ ] Information for the request is collected

### Acceptance Criteria ###
- [x] Prototype Helm charts for vets-api, vets-website, and content build are successfully deployed within the Preview Environment.
~~- [ ] The Preview Environment has successfully passed the WASA scan without any critical vulnerabilities.~~
~~- [ ] The VA's ESECC Review Board has reviewed and approved the Preview Environment based on the WASA scan results.~~

Note - We've moved submitting the WASA Scan, and the support of that process to Milestone 2, so it doesn't block production while we navigate that process, as a result, the last two AC have been moved to the next milestone.
