### ISSUE TITLE
Create Prototype Helm Chart for vets-website

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#67155]
### High-Level User Story ###
_As a DevOps engineer, I need a prototype Helm chart for vets-website so that the website can be managed and deployed effortlessly in Kubernetes._

### Tasks ###
- [ ] Undertake a discovery phase tailored for vets-website to gauge its Kubernetes deployment prerequisites.
- [ ] Examine existing Helm charts pertaining to vets-website, deciding on modifications or the inception of a fresh Helm chart.
- [ ] Craft and formulate the prototype Helm chart for vets-website.
- [ ] Adjust the vets-website repository to facilitate the automatic publication of its container images and the Helm chart.
- [ ] Enrich the Terraform configurations to ensure the Helm-driven deployment of vets-website.

### Acceptance Criteria ###
- [x] A functioning Helm chart for vets-website is crafted and validated for Kubernetes deployment.
- [x] Pushing updates to the vets-website repository results in the auto-publishing of the container image and the Helm chart.
- [x] Vets-website is successfully deployed in a Kubernetes cluster employing the Helm chart.
