### ISSUE TITLE
Create a Preview Environment to support Usability & User Acceptance Testing

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#67159]
### High-Level User Story ###
_As a DevOps engineer, I need a Preview Environment that is ready to support numerous rounds of user testing. This process will help us refine the Preview Environment solution closer to a state that it can support Usability and User Acceptance Testing.

### Tasks ###
- [ ] Submit WASA Scan Request
- [ ] Support any changes requested as a result the WASA scan process, and report updates as necessary
- [ ] Develop complete Helm charts for the core components:
  - [ ] vets-api
  - [ ] vets-website
  - [ ] content build
- [ ] Conduct internal testing
- [ ] Information for the request is collected

### Acceptance Criteria ###
- [ ] The Preview Environment has successfully passed the WASA scan without any critical vulnerabilities.
- [ ] The VA's ESECC Review Board has reviewed and approved the Preview Environment based on the WASA scan results.
- [ ] (Stretch) Preview Environments are available on a public URL
