### ISSUE TITLE
[UX][Design] Update aria labels in appt list for details link in Priority 1 Sketch page

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#67169]
## Background
The Appointments team has a slightly different aria labels for their appointment list. We need to make sure that we're aligned (if/where appropriate). 

Current approach we plan to follow:
<img width="888" alt="Screenshot 2023-10-10 at 8 48 25 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/79372956/7fe0d197-0b8c-4d8b-b6d0-22d1f5cc5efc">

## Tasks
- [ ] Double check with John (currently working on this) and Appointments team to decide on aria labels
- [ ] Update Priority 1 Sketch page with new aria labels for both Pre-Check-in and Check-in (Appointment list only) 
- [ ] Make sure Annotations page has aria labels up to date

## AC
- [ ] We're aligned with engineers and Appointments team on aria label approach
- [ ] Priority 1 Sketch page is updated with new aria labels for both Pre-Check-in and Check-in (Appointment list only) 
- [ ] Annotations page has aria labels up to date

**Comment by benbrasso-agile6** [comment]
@cgednalske pls include @ytsaoca in conversations and help with sketch documentation, if needed

**Comment by benbrasso-agile6** [comment]
Reassigned to ya-ching since I invited her to the meeting

**Comment by cgednalske** [comment]
Details link aria labels updated in Priority 1 and on Annotations page to include care type and doctor 👍  @benbrasso-agile6 this is ready for validation

<img width="617" alt="Screenshot 2023-10-24 at 2 24 25 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/79372956/b44b708c-73d7-4e2d-90fc-9bd4c8791ca5">

**Comment by benbrasso-agile6** [comment]
LGTM. Could you double check the Design page? There might be one on there. Could update it or just delete it, since you updated Annotations page.

**Comment by cgednalske** [comment]
Not seeing anything there, so I think we're good 👍
