### ISSUE TITLE
[UX] [Research] Create Card Sort Activity

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#67163]
## Background
We need to create a card sort for past appointment travel research to pair with our usability study. We might not be able to access Optimal Sort until a certain point before our study, so we'll need to time the completion of this ticket accordingly.

Note: This will be a **closed card sort**

### Process:
- We’ll ask participants to identify which are most important and sort into categories
- As they sort, we’ll ask them what those terms mean to them (and if anything is confusing). 
- In addition, if any terms are confusing, we can prompt participants to tell us what they feel would be more helpful (instead of having them create new categories - to help with time)

### **Categories:**
- Very important 
- Somewhat important
- Not very important
- Not at all important
- I don’t know what this means

### **Terms (cards):**
1. Incomplete
2. Saved
3. Claim Submitted
4. In Manual Review
5. Approved for Payment
6. Submitted for Payment
7. Claim Paid
8. On Hold
9. Denied
10. Payment Canceled
11. Fiscal Rescinded

### **Structure example:**
<img width="775" alt="Screenshot 2023-10-06 at 12 58 07 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/79372956/81282f6c-20bd-4a33-8379-eaf125607c1c">

## Tasks
- [x] Get access credentials for Optimal sort (believe we use Shane's account)
- [ ] Create Card Sort 
- [ ] Go over with mobile app and Appointments researchers
- [ ] Review with team

## AC
- [ ] Card sort created
- [ ] Card sort reviewed with mobile app and Appointments researchers
- [ ] Card sort reviewed with UX/team

**Comment by loripusey** [comment]
pointed at 2

**Comment by benbrasso-agile6** [comment]
@cgednalske can you drop the doc in here that has the card sort? @ytsaoca when you're back, we can cowork on this one.

**Comment by cgednalske** [comment]
@benbrasso-agile6 @ytsaoca here's the [doc with the research info](https://docs.google.com/document/d/15OVAEQ0jguxlmny5Y_ACcV24l0-UFXx2UKwVVnfCwtM/edit), but also added the info to the ticket background.

**Comment by benbrasso-agile6** [comment]
Ya-ching is getting started, created the study in optimal workshop

**Comment by benbrasso-agile6** [comment]
I think this is ready for validation by @cgednalske. All finished @ytsaoca ?

**Comment by ytsaoca** [comment]
Yes, finished.

**Comment by cgednalske** [comment]
Hi @ytsaoca! I think we'll be changing the categories a bit. Could you update the study to have the following three categories (in that order)?

1. Important 
2. Not Important
3. Confusing

**Comment by ytsaoca** [comment]
@cgednalske Updated. 
<img width="1268" alt="Screenshot 2023-10-27 at 10 41 24 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/90633685/4993a0ee-85d4-466b-bd2f-009bc0137326">

**Comment by benbrasso-agile6** [comment]
This is going to be cool to show during Sprint Review :)

**Comment by benbrasso-agile6** [comment]
Should we close this ticket?

**Comment by cgednalske** [comment]
Yep! Looks great 👍

**Comment by benbrasso-agile6** [comment]
Yay
