### ISSUE TITLE
Add content about past appointments and encouraging users to find those in MHV

### ISSUE THREAD

**Issue by lalexanderson-dsva** [department-of-veterans-affairs/va.gov-team#6716]
## User Story or Problem Statement
As a Veteran, I need to know that I can go to MHV to find my past appointments. 

## Goal
_We want Veterans to easily know where to look to find past appointments._

## Objectives or Key Results this is meant to further
- _Enable use of self-service tools, such as online scheduling._
---
## Tasks
- [ ] _We need to add some content on the VAOS landing page explaining to Veterans to go to MHV to find past appointments for now. (This will be changed in the future when past appointments are added in to va.gov.) _

## Acceptance Criteria
- [ ] _Content plus link will show on the vaos landing page. _
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by peggygannon** [comment]
Hello, @lalexanderson-dsva  @rtwell I have a few followup questions: 

1.  I wanted to confirm what we refer to the VAOS landing page: 

Are we referring to the authenticated static Appointments page or the first screen inside the VAOS tool? 

2. also, should this language be added to the modal that pops up for users going to VAOS?

**Comment by lalexanderson-dsva** [comment]
1. I'm talking about https://www.va.gov/health-care/schedule-view-va-appointments/appointments

2. And yes, that's a good idea.

**Comment by peggygannon** [comment]
Please see updated content about past appointments for:



1. Updated copy on VA appointment landing page (https://www.va.gov/health-care/schedule-view-va-appointments/appointments)

@lalexanderson-dsva @jbalboni @rtwell Updated content to let users know they can view past appointments in MHV. 

New copy will go under the *Upcoming appointments header

**Upcoming appointments**
 To view past appointments you’ve made through My HealtheVet, [go to the old appointments tool]( https://veteran.mobile.va.gov/var/v4/).


![2020-02-27.png](https://images.zenhubusercontent.com/59b0414bb0222d5de476aa22/a289d8f3-2c0e-4f82-bcef-1db396228dee)


------

2. Updated copy for Modal

**Welcome to the new VA.gov online scheduling tool**

The VA appointments tool has been redesigned based on feedback from Veterans like you. You can now view, schedule, and cancel all your appointments in one place on VA.gov.

To view your past appointments, you can go back to the old appointments tool. You’ll find a link to it at the bottom of the page in the new tool.

{button} Continue to your VA appointments(https://www.va.gov/health-care/schedule-view-va-appointments/appointments)

**Comment by jbalboni** [comment]
I made these changes, then reverted them in vets-website. We're confusing a couple things:

1. The old VA mobile tool (https://veteran.mobile.va.gov/var/v4/)
2. The appointments page on MHV

We currently have a link to 1 in the footer of the app. However, past appointments are only available at 2.

**Comment by lenaecb** [comment]
1. Update copy VA appointment landing page -- also need to update MHV link ( @jbalboni  is going to find the right link)

2. For modal -- Remove reference to past appointments copy inside of modal

**Comment by peggygannon** [comment]
Hello, @lenaecb @jbalboni per our sync today, here are revisions to this content. 



1. Upcoming appointments landing page

To view past appointments you've made, [go to My HealtheVet](link TK from jeff). 

2. Reverted copy for  Modal
**Welcome to the new VA.gov online scheduling tool**

The VA appointments tool has been redesigned based on feedback from Veterans like you. You can now view, schedule, and cancel all your appointments in one place on VA.gov.

If you want to go back to the old appointments tool, you’ll find a link to that scheduling tool at the bottom of the page in the new tool.

{button} Continue to your VA appointments(https://www.va.gov/health-care/schedule-view-va-appointments/appointments)
