### ISSUE TITLE
Move "old" feature pages in unified check in sketch file to {where} (f/u from 66318)

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#67167]
## Tasks

We determined as part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/66318 to move "old" feature pages out of unified check in sketch file. 

- [ ] Decide where to move them. E.g., Playground file or create a new file for older feature pages to be stored. 
- [ ] Move those pages to the sketch file
- [ ] Delete those pages in the unified sketch file (but keep any Feature pages that are still relatively new)

## AC

- [ ] Review decision with UX team
- [ ] Files are moved

**Comment by loripusey** [comment]
@benbrasso-agile6 we need to add details for this ticket

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/67167?planning-poker) with Zenhub @cgednalske @kellysmith1008 @ytsaoca @zach-park

**Comment by benbrasso-agile6** [comment]
@loripusey for consideration for next sprint, i.e., if you're seeing there's room. If not, no big deal. This isn't urgent at all.

**Comment by loripusey** [comment]
@ytsaoca is this one done?
cc: @anita-halici

**Comment by benbrasso-agile6** [comment]
She pinged for validation. Let me look.

**Comment by benbrasso-agile6** [comment]
LGTM, but would like to see the other UXer's chime in 

https://dsva.slack.com/archives/C04J6H2LYUU/p1698789210939249

@cgednalske @zach-park @kellysmith1008

**Comment by loripusey** [comment]
It should be in the validate column if it is awaiting validation, it was in the "in progress" column

**Comment by loripusey** [comment]
@cgednalske @zach-park @kellysmith1008 please validate ASAP and close before planning

**Comment by kellysmith1008** [comment]
Looks good, Ya-ching!

**Comment by cgednalske** [comment]
Added my comment in the [slack thread](https://dsva.slack.com/archives/C04J6H2LYUU/p1698789210939249). Groupings look great! Wonder if we can remove [Page] from the Page titles to bring more attention to the page titles themselves?

**Comment by zach-park** [comment]
Validated... LGTM!
