### ISSUE TITLE
[UX] [Design] Complete Prototype to Test with End Users

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#67164]
## Tasks
- [x] Complete prototype (includes ~10 screens)
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [ ] UI review meeting with product/UX team for feature capabilities

**Comment by benbrasso-agile6** [comment]
@cgednalske please pull that list into this ticket or as a comment for easier access and validation. TY

**Comment by cgednalske** [comment]
## CodePen screens:
(as of 10/17)
[CodePen Collection (started)](https://codepen.io/collection/bNmzEz)

### Prototype screens for full auth from email 
- **[ ]** = unsure if needed/depends on remaining prototype questions

1. Start - Email 
2. Auth representation
3. Appointments list (with card)
4. Detail page with CTA (includes AVS)
5. Detail page with CTA (includes AVS) for second appointment on the same day
6. Detail pages with travel status (“Claim filed” or other appropriate claim status from API)
7. Travel flow screen 1
8. Travel flow screen 2
9. Travel flow screen 3
10. Review screen
11. Submission success screen (with success alert component) 
12. Appointment list (return to list) - no success status but can file another claim from the list
13. Detail page with updated status after filing - with success status
14. Generic detail page
	
### Prototype screens for full auth from MyVA or MHV
Should pick one/ask OCTO (this part isn't really up to us to test). Most are repeats from above. 
- Bold = new screens 
- Italics = repeats that do not need to be replicated 
- **[ ]** = unsure if needed/depends on remaining prototype questions

1. **[Start](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/JnEYQJr) MyVA and/or MHV (imagine you've already logged in) with appt-specific notification**
2. **Appointment list without card** 
3. _Detail page with CTA (includes AVS)_
4. _Detail page with CTA (includes AVS) for second appointment on the same day_
5. _Detail pages with travel status (“Claim filed” or other appropriate claim status from API)_
6. _Travel flow screen 1_
7. _Travel flow screen 2_
8. _Travel flow screen 3_
9. _Review screen_
10. **Submission feedback screen: failure**
11. **Appointment list (return to list) - different status than email path**
12. **Detail page with updated status after filing - with [failure](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/67165) status**
13. _Generic detail page_

**Comment by cgednalske** [comment]
Prototype is set up ([starting screen](https://codepen.io/team/va-cie/live/bGOmjGe)) but will need to be carried over into next sprint and updated to reflect the recent design changes + accurate email content to come.

**Comment by loripusey** [comment]
@cgednalske is this ready to close? I think any future work on the prototype should get new tickets

**Comment by cgednalske** [comment]
Agree as well! 👍 

Here is the [link to the start of the prototype](https://codepen.io/team/va-cie/live/bGOmjGe)
