### ISSUE TITLE
[UX][Content] Create Content for Claim Status on Appt Details page

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#67165]
## Description 

No wireframing on this ticket. Will use a separate ticket.

Create content for the following scenarios: 

## Tasks
- [ ] Appt detail page - file for travel reimbursement component. E.g., heading, description, action link (button). 
- [ ] Appt detail page - already submitted component. E.g., heading, claim number, default description (something like "check your claim status by signing in to BTSSS"), link text to BTSSS sign in. 
- [ ] Appt detail page - denied claim status. E.g., heading, claim number, short description of what the Veteran can expect next (based off of what we know happens next - [there are two letters here to read](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/discovery/travel-reimbursement/submitted-claim-statuses.md#vet-facing-information-in-btsss) and this is what Misty worked with Danielle on, "We mailed you a letter explaining why we denied your travel claim and how to appeal this decision." We could also include a link to the [VA form](https://www.va.gov/find-forms/about-form-10-0998/), knowing that someone could be at home near a printer.), default description (something like "check your claim status by signing in to BTSSS"), link text to BTSSS sign in. 
- [ ] Review with Danielle (Misty has been working with Danielle so far) or Laura
- [ ] Review with Appointments team (Ciera, Peter, Kristen) (most important group)
- [ ] Review with Misty from Mobile App team 

## Acceptance Criteria
- [ ] Content has been created & reviewed
- [ ] Content provided to Christina and Ya-ching

## More Information 

[Sketch file](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/1238ECAD-399B-44ED-BEFF-F6F523D5CFE6/canvas) 

<img width="668" alt="Screenshot 2023-10-16 at 10 33 42 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/101129355/88bb91ef-aff4-4154-a498-40cee380bc95"><br/><br/>

<img width="1243" alt="Screenshot 2023-10-16 at 10 26 56 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/101129355/68ee1826-096e-449c-8ea5-1cec3cdfe0bf">

**Comment by loripusey** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/67165?planning-poker) with Zenhub @kellysmith1008

**Comment by kellysmith1008** [comment]
@loripusey I'm not totally clear on what this ticket needs. Is there a link to the mobile app content already? Or am I writing content first and then sending it to the mobile team? What claim statuses do we need? Is this in response to travel pay, like the text messages? Or is it something else?

**Comment by loripusey** [comment]
@benbrasso-agile6 created the ticket so I would get with him for clarification

**Comment by benbrasso-agile6** [comment]
It's just a placeholder ticket right now. I'll write it out when I'm back in.

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/67165?planning-poker) with Zenhub @cgednalske @ytsaoca @zach-park

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 I updated the description, if you need to repoint

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 I was looking at the tasks for this ticket, and I think we can reuse the content we've already done for past in-person appointments (BT claim statuses on appt detail page #66762 in the unified sketch file) - especially since we just ran this content past Peter, Mark, and Cara yesterday. I'm going to look at it today and I'll mock up the current in-person appointment pages for any changes, but I think this could work and will make the whole appointment details list uniform, regardless of if it's today's appointment or an appointment in the past.

**Comment by benbrasso-agile6** [comment]
I think you've completed this ticket already :)

**Comment by kellysmith1008** [comment]
Hahahaha - okie dokie - that's what I thought! I'll close this one. Thanks!
