### ISSUE TITLE
[UX] Add Disclaimer to the Product Guides that they DO NOT Contain any PHI/PII

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#67175]
## Background
Cherly Wills requested that we add a disclaimer to our Product Guides that state that they DO NOT contain any PHI/PII. Kay agrees we should add this.

Also, For the product guide update- can you add in the check-in # for the Philippines? Request from IVC :slightly_smiling_face:. [Slack from Kay](https://dsva.slack.com/archives/C022AC2STBM/p1697648003557249)

## Tasks
- [x] Add Disclaimer to the Product Guides that they DO NOT Contain any PHI/PII
- [x] Add Philippines number (or image of poster)
- [ ] Run content by Danielle
- [x] Publish the Product Guides

## Acceptance Criteria
- [ ] Content has been created & reviewed
- [x] Product Guides have been published

**Comment by loripusey** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/67175?planning-poker) with Zenhub @kellysmith1008

**Comment by benbrasso-agile6** [comment]
not much to validate, but from a process standpoint, someone pls double check @loripusey @kellysmith1008 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-guides/README.md
