### ISSUE TITLE
[spike] SC | Determine expected ITF codes

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#67184]
## Value Statement
**_As a_**  member of benefits portfolio
**_I want to_** know the all the statuses of an Intent-to-File API call
**_So that_** we can determine when we should create and ITF and when to log an error

## Background Context

Currently when we check for an ITF and it doesn't exist for a Veteran, Lighthouse returns a 404 error. The frontend doesn't distinguish the different error statuses and automatically attempts to create an ITF based on the failure. It also logs _all_ errors to Sentry, when it might not need to. When an ITF call is successful (200 status), the FE looks for an active, non-expired ITF. If no active ITF is found, the create ITF endpoint is called. 

We first need to investigate the [different BE errors](https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/form_526/getIntentToFile) - swagger docs only show a `200` and `401` status.

[Slack discussion](https://dsva.slack.com/archives/C05FCEH2NRG/p1696949127542939?thread_ts=1696944760.711329&cid=C05FCEH2NRG)

Basic details from our backend:

- 200 response - success
  - if active, do not try to file ITF, allow user to continue to form
  - if no active or empty array, attempt to file new ITF
  - FE says you already have an ITF or that one was file and user can move on
- 401 - unauthorized
  - redirect to login page
- 403 - forbidden
  - redirect to login page
- 404 response - not found
  - assumed no ITFs, attempt to file one, nothing shown to the user this is all behind the scenes
  - if successfully creates, allow user to continue, if not, block and dont allow user to continue, shows user an error message
- 500 response - internal server error
  - assumed no ITFs, attempt to file one, nothing shown to the user this is all behind the scenes
  - if successfully creates, allow user to continue, if not, block and dont allow user to continue, shows user an error message
- 503/504 - timeout response
  - assumed no ITFs, attempt to file one, nothing shown to the user this is all behind the scenes
  - if successfully creates, allow user to continue, if not, block and dont allow user to continue, shows user an error message
- Any other response
  - assumed no ITFs, attempt to file one, nothing shown to the user this is all behind the scenes
  - if successfully creates, allow user to continue, if not, block and dont allow user to continue, shows user an error message

## Tasks
- [ ] List of responses we get back
- [ ] Definition for each response
- [ ] Action the FE takes
- [ ] Message the Veteran is shown (including any missing messages we should add)
- [ ] Discuss with Lighthouse any changes that might need to be made to improve this interaction

## Definition of Done
- [ ] Determine action for each response
- [ ] Create tickets for any FE or BE work to be done

## Acceptance criteria
- [ ] All tasks complete

**Comment by saderagsdale** [comment]
Separate: talk to Austin about business rules for ITF

**Comment by anniebtran** [comment]
After reading thru the slack thread in the description, I'm wondering how relevant this ticket is now, given a few new developments since it was first opened:
- [We've already done the work](https://github.com/department-of-veterans-affairs/va.gov-team/pull/80049) to add documentation around all the FE/BE interactions
- [Lighthouse's ITF documentation](https://developer.va.gov/explore/api/benefits-claims/docs?version=current) seems to have more status code documentation than there was before (based on what I gathered from the thread)
- We [no longer block a Veteran from submitting](https://github.com/department-of-veterans-affairs/vets-website/pull/29644) a Supplemental Claim if their ITF fails to get created

With all that under consideration, do the goals of this ticket change? What do we ultimately want to solve or understand with this spike?
