### ISSUE TITLE
[bug] SC | Form submission failed because missing zipcode

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#67187]
## Background Context
On 10/9/2023,  around 8:45PM ET, user with uuid `ce182ffd-0705-401b-b9c9-a129645da494` tried to submit a SC form, unsuccessfully, three times. Form submission failed because of a missing address field. See [Sentry](http://sentry.vfs.va.gov/organizations/vsp/issues/198994/?environment=production&project=3&query=user.id%3A%22ce182ffd-0705-401b-b9c9-a129645da494%22&statsPeriod=14d). Veteran's `InProgressForm` showed a domestic address, with a missing zip code. Slack thread associated with error here: https://dsva.slack.com/archives/C05UPRR0HK3/p1696898720686679.

## Acceptance Criteria

- [ ] All tasks complete
- [ ] Veterans will be alerted to invalid profile address fields on the contact info page
- [ ] Veterans will be alerted to invalid profile address fields on the review & submit page
- [ ] Veterans will be blocked from submitting invalid address fields 

## Tasks

- [ ] Update platform profile to use uiSchema required & validation settings
- [ ] Update CustomPage to pass in uiSchema & schema on review & submit page
- [ ] Add profile address validation to appeals forms 
- [ ] Add unit tests

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by data-doge** [comment]
One idea, if missing from profile, would be missing from form data. But we should be validating that complete address there. Recently switched to platform's address definition, which may be related to this issue.

**Comment by data-doge** [comment]
Few updates here:
- Veteran has not tried re-submitting since the last failed re-submission
- I pinged Kimberley again this morning to reach out to the Veteran.

**Comment by eileen-coforma** [comment]
@anniebtran @rocio-desantiago please review

**Comment by data-doge** [comment]
Update: Kimberley called and emailed Veteran and is awaiting a response.

**Comment by saderagsdale** [comment]
Fix was merged. Waiting for it to be available for testing in staging. Robin will tag Sade and Eugene.

**Comment by saderagsdale** [comment]
Robin is making updates to the PR, need to discuss how to handle international addresses. We should look at this use case holistically (including email, zipcode, address).

**Comment by HeatherWidmont** [comment]
@Mottie will merge after deploy today
