### ISSUE TITLE
Add datadog monitors for FSR service

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#67194]
## Issue Description
As part of the code yellow we need to establish monitors for both lower bound and error rates for our FSR service to track that  everything is processing smoothly.

---
## Tasks
- [ ] Develop query and monitor to check for lower bound (limited) submissions that might prove to be an issue with the API 
- [ ] Develop query and monitor to check error percentages over period of time
- [ ] Attach `debt-alerts` to monitors to ping our team

## Acceptance Criteria
- [ ] We have monitors setup for our FSR service
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
