### ISSUE TITLE
Add input allowing veterans to search by rep name/organization

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#67203]
## Issue Description
The current app allows veterans to input their location to find nearby representatives. We are adding a new input that allows users to search for representatives by name or organization. For now this ticket pertains to work being done on the frontend prototype (ie mock data). 

---
## Tasks
- [ ] Implement a search input field for users to input representative names or organizations using mock data
- [ ] Ensure the search results are displayed to the user in a clear and organized manner.

## Acceptance Criteria
- [x] Users can input a representative's name or organization in the new search input field.
- [x] The search results are presented in a user-friendly format, allowing users to easily identify and select a representative.

**Comment by cosu419** [comment]
The inputs are present so I'm marking this done. Created a separate issue for continued work on simulating user behaviors.
