### ISSUE TITLE
Add Character Limit to Middle Name

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#67214]
## Issue Description
_The Veteran middle name field in the 686 and 674 forms does not have a character limit, but the BIS system only allows 30 characters in that field. When the field exceeds the BIS limit, the claim is rejected. See #64342 for similar implementation on Addresses_
Error seen in Datadog: 
ORA-12899: value too large for column "CORPPROD"."VNP_PERSON"."MIDDLE_NM" (actual: 34, maximum: 30) : {:icn=>"1012593499V692493"}

First and Last name have the same limitation. Updating Task/AC to match

---
## Tasks
- [ ] Add a character limit to First/Middle/Last fields on 686 claims
- [ ] Add a character limit to First/Middle/Last fields on 674 claims
- [ ] Display an error message to the user if the limit is exceeded.

## Acceptance Criteria
- [ ] First/Middle/Last name field in the 686 form accepts 30 or less characters
- [ ] When user reaches 30 characters in First/Middle/Last name field in 686, data is no longer able to be inputed
- [ ] Veteran First/Middle/Last name field in the 674 form only accepts 30 or less characters
- [ ] When user reaches 30 characters in First/Middle/Last name field in 686, data is no longer able to be inputed
---
