### ISSUE TITLE
[FSR] Streamlined waiver calculations for combined submisisons

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#67217]
## Description
Currently FE is **_not_** running streamlined waiver calculations for combined submissions since the users won't be eligible for the shortened path since VBA debts still need to collect all of the data on the FSR. 

Let's continue to run those calculations as long as _any_ VHA copay is selected, but do not alter the form flow if any VBA debt is selected.

Developer notes:
- `isEligibleForStreamlined` can probably be the variable we leverage to continue to run the calculations, but prevent the page navigation changes.
- **Cash in hand and cash in bank** (Liquid assets) - these new pages / calculations will definitely be a pain point. We will need clarification from stakeholders on how we want to calculate these values based on the checklist since we won't be asking them directly with the new pages. 
- We should be able to implement this live without affecting in progress users since the calculations will run in the background. **Tricky edge case** is we only fetch the GMT data once at the start of work history, so in progress forms past that won't have GMT data; we could fetch again on the final review page and run all the calculations at the very end? 

Given: We do not run SW calculations for combo submissions
When: A user selects both VBA and VHA relief (combo submission)
Then: Calculations for SW should be completed without altering page flow

## Tasks
- [ ] Get clarification on Liquid assets calculations.
  - [ ] Update streamlined waiver asset threshold calculation & comparison (6% of GMT vs Liquid assets).
- [ ] Get clarification on if we should run these calculations for VHA debts that exceed $5,000
  - **NOTE:** This may not be necessary, but better to be proactive. 
- [ ] Update streamlined waiver calculations so they run if _any_ VHA is selected without altering the flow if there's a VBA debt also selected.
- [ ] Sync with BE to determine best way to relay this information.
  - [ ] Update transform accordingly 

## Acceptance criteria

- [ ] Streamlined waiver calculations are completed if a VBA debt is also selected in the FSR
- [ ] Form flow is unaltered (no streamlined path) if VBA debt is selected.
- [ ] Calculation results are communicated to BE

## Testing
- [ ] Test Streamlined calculation with VBA and VHA selection
  - [ ] Verify flow is unaltered
- [ ] Test Streamlined calculation with only VHA selection
  - [ ] Verify streamlined flow is unaltered
- [ ] Test Streamlined calculation with only VBA selection (should _not_ run)
  - [ ] Verify flow is unaltered
- [ ] Test submission object and verify calculation data is transmitted to BE
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by denisecoveyduc** [comment]
@HeatherRienks @Tom-Davis I am looking to understand when we might be able to slot this one into our sprint schedule.

**Comment by HeatherRienks** [comment]
@denisecoveyduc - with regard to priority; would you be ok with adding this into our next sprint (119: Feb 14- 27, 2024)?

**Comment by denisecoveyduc** [comment]
Hey @HeatherRienks Totally!! I think that would be great if the team has some bandwidth. Once complete it would be great to understand what and where the calculation will appear. 

- _What_ - meaning what phrase with VHA see on the VODA file. 
- _Where_ - meaning for combined submissions where will VHA see this information on the VODA File? (I'm guessing a phrase will appear in the additional info - field 37B?)  Thanks team!

**Comment by denisecoveyduc** [comment]
Adding a quick update to this one to boost the currency factor ;P 
As of today 3/12/24- my understanding is we are notifying VHA when a submission is a combined submission. That tells them that the data was not processed through the "VHA streamlined waiver calculator" because VBA required the Veteran to complete the entire FSR. That Veteran may still be approved for the streamlined process though. To expedite VHA process we would like to take the data we have collected from a Veteran during the submission process and update the message to VHA that says it has been approved if it meets the criteria.
