### ISSUE TITLE
Create AL2-based Utility Exporter

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#67219]
# Unknown
We don't know all use cases for these instances. What we do know is that the Jenkins deploy pipeline spins up an EC2 instance (or set of EC2 instances managed by an Auto Scaling Group) using a previously built AMI. The AMI will be found either using a git commit hash or a git release tag. Only git release tags are allowed for production.

# Description
Let's apply the same process from the SOCKS and JumpBox migration process to the Utility Exporter deployment. At the time of survey on 10/10/2023, there were 2 instances of utility exporter.

# Tasks
- [ ] Create a new repository for the Utility Exporter configuration
- [ ] Create a Terraform configuration in the new Utility Exporter repository that builds a Utility Exporter instance using the hardened AL2-based image
- [ ] Deploy the new Utility Exporter build side by side with the existing Utility Exporter build
- [ ] Point some subset of traffic at the new Utility Exporter instance
- [ ] Test
- [ ] Resolve defects

# Acceptance Criteria
- [ ] A new Utility Exporter instance based on AL2 hardened image is up and running
