### ISSUE TITLE
Project Kickoff Debt Letters MVP

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#6721]
## Steps to complete Project Kickoff
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan will schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] VSP <> **requesting team** kickoff meeting completed
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please bring the following to the kickoff meeting_
- Link to rough draft of product outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/readme.md
- You **do not** need to prepare a presentation

## Meeting attendees from **requesting team**
- Product Manager (required): Leah Keeler
- DEPO Product Lead (required): Matt Self 
- Entire VFS team (recommended): Amen Ra, Mahariel Rosario, Riley Orr, Becca Walsh, Cameron Testerman

## Scheduling
Preferred dates or times: Week of 3/16

**Comment by andreahewitt-odd** [comment]
Scheduled for 3/17
