### ISSUE TITLE
[PM] 10-10EZR - Standalone form: Create & submit Contact Center guide

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#67220]
## Background
Now that Frontend development, QA and last minute changes are done, we need to create and submit the [Contact Center guide for review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html).

## Tasks

- [x] Create Contact Center guide in a .docx format
     - Use the 10-10EZ guide as a template, since both forms share screens/fields
- [x] Use screenshots from Staging environment
- [x] Submit [request ticket for Contact Center Guide review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jwoodman5%2C+kimberley2019&labels=contact+center%2C+collaboration+cycle%2C+collab-cycle-review&template=request-contact-center-review-template.md&title=Contact+Center+Review+for+%5BTeam+Name+-+Feature+Name%5D), with document attached
  

## Acceptance Criteria
- Contact Center guide draft will be updated and submitted for review
     - Ticket #70045 submitted
