### ISSUE TITLE
[QA] 10-10EZR - Standalone form: Complete QA on EZR form

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#67228]
## Background
As development wraps up, we need to begin QA on the 10-10EZR.

### Resources
- [Use cases](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-1010EZR-Update-health-care-benefits.md)
- [Staging Review preparation guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)
- [QA Standards guidance](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards)
- [TestRail Test Runs](https://dsvavsp.testrail.io/index.php?/suites/view/11&group_by=cases:section_id&group_order=asc&display_deleted_cases=0)

## Tasks
- [x] Coordinate QA schedule
- [x] Use TestRail to perform QA, using test cases/test runs to track and document results
- [x] Communicate any defects found to the team for resolutions
     - May need create tickets for these
- [x] Generate the following artifacts (after defect resolutions and retesting):
     - 10-10EZR Test plan
     - Coverage for References
     - Summary(Defects) reports
     - E2E tests (provide a link to the product’s code)
          - These are the engineer's End-to-end testing,
     - Code coverage (provide a link to the product’s code)
     - [Unit Test Coverage report](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report)

## Acceptance Criteria
- QA is fully completed before Staging review

**Comment by fbonds** [comment]
New test run utilizing new test cases
https://dsvavsp.testrail.io/index.php?/runs/view/4976&group_by=cases:section_id&group_order=asc

**Comment by fbonds** [comment]
I've run through a variety of test scenarios corresponding to the Use Cases, but I'm hesitant to mark any of the testrail test cases as passed until I'm actually able to submit the EZR.  Per MattL, we should have the submit patch in Stage by tomorrow afternoon.  At which point I can start marking tests as passed and QA should proceed quickly from there.
@hdjustice @alexseelig

**Comment by fbonds** [comment]
I've run through all the test cases, but have not marked any of them as passed as I remain unable to see the final step complete (Submit) in any scenario.

**Comment by hdjustice** [comment]
Thank you Fletcher.  We both can try to keep up with Lihan, Matt L and Josh D on the fixes and test ASAP

**Comment by hdjustice** [comment]
@alexseelig @emily-brown34 -  FYI on the blocker to testing, still pending the submission/confirmation page tests.  Any QA findings have corresponding tickets already.

**Comment by fbonds** [comment]
Summary of Defects
https://dsvavsp.testrail.io/index.php?/reports/view/557

**Comment by fbonds** [comment]
Coverage of References:
https://dsvavsp.testrail.io/index.php?/reports/view/559
