### ISSUE TITLE
[PM] 10-10EZR - Standalone form: Submit Privacy, Security and Infra review ticket

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#67223]
## Background
Now that FE and BE work has been completed, connections made and diagrams completed, we can submit a ticket for the [Privacy, Security, & Infrastructure Readiness Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/privacy-security-infrastructure-readiness-review).

## Tasks
- [x] Gather all required artifacts
- [x] Submit [ticket to Privacy, Security & Infrastructure team](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1335) with details
- [x] Add ticket number to [CC Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63773) under Privacy, Sec, Infra section

## Acceptance Criteria
- Privacy, Security and Infrastructure review ticket has been submitted with all required artifacts

**Comment by hdjustice** [comment]
[Privacy, Security & Infrastructure review ticket](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1335) has been submitted
@alexseelig @emily-brown34
