### ISSUE TITLE
[PM] 10-10EZR - Standalone form: Schedule Midpoint review

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#67225]
## Background
Once FE development has been completed, we need to ensure all artifacts are gathered and ready for the [Midpoint Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review).

## Tasks
- [ ] Gather all required artifacts for the Midpoint Review
- [ ] Update Midpoint Review section from [CC ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63773)
- [ ] Scheduled Midpoint Review using Calendly link in [CC ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63773)

## Acceptance Criteria
- All artifacts are ready and Midpoint Review has been scheduled.
     - Scheduled for XXXXX
