### ISSUE TITLE
Create AL2-based Fwdproxy

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#67233]
# Description
Let's apply the same process from the SOCKS and JumpBox migration process to the Fwdproxy build and deployment. When surveyed, there were 17 active instances of fwdproxy across different environments.

# Tasks
- [ ] Create a new repository for the Fwdproxy configuration
- [ ] Create a Terraform configuration in the new Fwdproxy repository that builds a Fwdproxy instance using the hardened AL2-based image
- [ ] Deploy the new Fwdproxy build side by side with the existing Fwdproxy build in a lower environment
- [ ] Point one of the lower environments to the new Fwdproxy instances
- [ ] Test
- [ ] Resolve defects
- [ ] Add in additional lower environments one by one and test until defects are resolved

# Acceptance Criteria
- [ ] New Fwdproxy instance based on AL2 hardened image is up and running in a lower environment
