### ISSUE TITLE
Convey to downstream services when a vha submission was derived from a combined submission

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#67239]
## Issue Description
We want to convey to downstream services when a vha submission was derived from a combined submission. This is relevant because a vha submission cannot be streamlined it it came from a combined submission even if it qualifies for SW on paper.

---
## Tasks
- [x] Store 'combined' field on public metadata
- [x] "We would like to make it apparent when a vha submission originated from a combined FSR submission, how would you like us to convey this information? Via the PDF?" -> raise this question at the next vbs sync meeting
- [x] Based on answer from above, incorporate the 'combined' data on some given pdf field, or within the form json.

## Acceptance Criteria
- [ ] Downstream services VBS and Huron can tell when a VHA submission is 'combined'
---

**Comment by HeatherRienks** [comment]
-Per VODA | VBS sync on 10/13/23, we let Mike Dewey know that we can work on this effort during this sprint, or the next (111) and we will keep him posted on progress. 
-Varun confirmed that additional comments are available in the workflow and Mike D. confirmed that this would be ok
-Varun thinks character limit is around 1,000

**Comment by HeatherRienks** [comment]
@kjsuarez - the FE ticket for this effort (#67217) is still in our backlog, but we can let Mike Dewey know that 50% of the work has been completed! ;)

cc: @Tom-Davis @denisecoveyduc

**Comment by kjsuarez** [comment]
PR https://github.com/department-of-veterans-affairs/vets-api/pull/14196
