### ISSUE TITLE
[Wizard] VBA and VHA paths for feedback

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#67232]
## Description
Create one userflow artifact for VBA and one for VHA in order to receive feedback from each team.

## Tasks
- [x] Create Artifact for VBA path
- [x] Create Artifact for VHA path

## Acceptance criteria
- [x] Artifact for VBA path created
- [x] Artifact for VHA path created

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by mgleo** [comment]
[VHA-wizard-paths.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDlqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--882d880e8794de27cb4161219dd57e201fe3c171/VHA-wizard-paths.pdf)

**Comment by HeatherRienks** [comment]
@denisecoveyduc - yes, the meeting is scheduled for Friday, November 3 at 12pmET.

**Comment by HeatherRienks** [comment]
@denisecoveyduc - any questions for us on this?

**Comment by mgleo** [comment]
@HeatherRienks @Tom-Davis Can be closed

**Comment by mgleo** [comment]
[additional-paths-fsr-wizard.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGphQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ba60fab47aeb708025103e173b53c4d2e35d6db/additional-paths-fsr-wizard.pdf)
