### ISSUE TITLE
Define process for 0 findings at Staging Review

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#67237]
## User Story
As an OCTO lead, I want to see the Staging Review dashboard reflect the accurate count of staging reviews that took place from quarter to quarter, including when 0 findings were documented, so that I can rely on the metrics from the dashboard for future work and/or reporting.

Assignee: @allison0034 @it-harrison 
Peer Reviewer: @it-harrison 

## Description
In the[ Staging Review dashboard](https://va-gov.domo.com/page/1340527018?userId=1646566899) in Domo, we are currently unable to capture when a Staging Review results in 0 VA.gov Experience Standards findings identified.  There's no way to see within the data set if/when a SR has 0 findings since the data set is only inclusive of the findings tickets. 

After discussing possible solutions with Governance team members on 10/10/23, the team determined that the easiest and simplest solution would be to create a gh ticket that has the same labeling as the current data set (so it can be captured in the existing query). This new gh ticket would be created if/when a VFS team has 0 findings at SR. This is ideal bc the new ticket will also have meta data showing the open date (ideally the SR date) so we can count the SR as having taken place in the appropriate quarter. The new ticket will include unique labels that will allow us to know that 0 findings were documented for the VFS team/product at the SR on this specific date.

The purpose of this ticket is to define a new process for how the new "no findings" ticket will be created, what labels will be included and ensure the process is integrated into the Post-Meeting tasks at Staging Review. 

Note: Governance team will not be retroactively creating the "no findings" ticket for prior Staging Reviews as the date on the ticket will be incorrect and may skew our data.

## Impacted Artifacts
[Staging Review - After the Meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808447023/Staging+Review+-+After+the+Meeting)

## Tasks
- [x] Create new label `exp-std-no-findings` in the va.gov-team repo
- [x] Add a conditional step to the Staging Review - After the Meeting guidance that should be completed if/when 0 VA.gov Experience Standards were documented. 
- [x] The step should include the creation of a dummy gh ticket that includes the following criteria:
   - [x] `exp-std-no-finding`, `CC-Dashboard`, `collab-cycle-feedback`, the VFS team label, and the VFS team product label have all been added to the ticket
   - [x] The ticket has been included in the Collab Cycle Request epic and milestone
   - [x] The body of the ticket includes information similar to the "completed" ticket - this ticket is for tracking purposes only and no VFS action is needed
   - [x] The title of the ticket includes the VFS team name, the Collab Cycle Request initiative, and that no Va.gov Exp Std findings were documented
- [x] The guidance should direct the Governance team member to close the ticket the same time/day they open it

**Note:** At this time, we will not be completing any steps to update Domo. Since we're not retroactively creating the "no findings" tickets for previously held Staging Reviews, there would be no data to validate that our changes in Domo are accurate. Instead, please add a note to the SR- After the Meeting guidance asking whomever is completing the section to notify Governance team when our first "no findings" SR takes place. At that time, we'll draft a ticket for updating Domo to pull in the data.
- [x] Add note to SR guidance for new ticket to be created when our first "no findings" SR occurs

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Governance team members have a process to follow if/when 0 VA.gov Exp Std findings are documented for the Staging Review

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@allison0034 i removed this from the current sprint, but I will get it refined and ready for the next sprint beginning 11/9

**Comment by shiragoodman** [comment]
@allison0034 this ticket is now ready. I re-added it to the current sprint.

**Comment by allison0034** [comment]
@it-harrison this is ready for your review

**Comment by shiragoodman** [comment]
Review new step 3 in the SR - After meeting guidance.

**Comment by it-harrison** [comment]
@allison0034 looks good!

@shiragoodman I realized during review of this ticket that I could leverage the code I have already written to automate the ticket creation here.

**Comment by shiragoodman** [comment]
@it-harrison do you mean the code you wrote for the SR "completed" tickets? Like it could check to see if there's any findings?

**Comment by it-harrison** [comment]
> @it-harrison do you mean the code you wrote for the SR "completed" tickets? Like it could check to see if there's any findings?

@shiragoodman I mean the code for "completed tickets" could be used with slight modifications - it would be triggered by adding the `exp-std-no-finding` label to the CC Request ticket.

**Comment by shiragoodman** [comment]
I'm not sure I'm following completely @it-harrison . Would the CC Request ticket become part of the issue tickets data set?

**Comment by allison0034** [comment]
This will move into the next sprint as Ian can automate this ticket creation as well.

**Comment by shiragoodman** [comment]
Ian to work on leveraging the existing h actions code. Once complete, Allison will update the Collab Cycle operational guidance.

**Comment by it-harrison** [comment]
@allison0034 @shiragoodman  is it important to add the team and product labels to the zero issue ticket? doing so isn't that simple because parsing the ticket body is not a reliable way to get team/product label names. 

I can add all the labels that are on the CC-Request ticket as well as `CC-Dashboard`, `exp-std-no-findings`, and `collab-cycle-feedback` (if they are not already on the CC-Request ticket) but then there will be some extra labels too like `design-intent`.

**Comment by shiragoodman** [comment]
@it-harrison yes, it would be nice to have the team and product labels. It should have all the same labels a SR issue ticket would have if/when applicable. 

Since this is an extreme edge case, and the likelihood of a Staging Review with 0 findings is very rare, I don't think we need to have the ticket creation automated. Sorry Ian. I know you put some work in already on this, but I think we're overengineering this a bit. We do not need to automate something that happens so infrequently. 

Ian - could you please make sure to undo any work you've done and peer review (if you haven't already) the documentation updates @allison0034 has made? Let me know if you have any questions or want to discuss further.

**Comment by it-harrison** [comment]
@allison0034 in light of @shiragoodman's comment above this issue is good to go, you can publish your update to the doc.
