### ISSUE TITLE
[Wizard] VBA Make updates based on stakeholder feedback

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#67234]
## Description
Open this ticket once VBA has sent feedback. We will make updates based on their feedback.

## Tasks
- [x] Update VBA path

## Acceptance criteria
- [x] VBA path updated 

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by HeatherRienks** [comment]
@denisecoveyduc has sent for VBA review. Stay tuned!

**Comment by mgleo** [comment]
@HeatherRienks @Tom-Davis 
VBA sent feedback on 11/13/23 and updates were made to Sketch: 
- [**Sketch file (navigate to "1.1 Complete a sub task" to view all paths)**](https://www.sketch.com/s/50583485-ba58-4ef8-ae04-2c274a792547)
Moved to Validate

**Comment by Tom-Davis** [comment]
Closing as complete - updates are linked in the ticket.
