### ISSUE TITLE
[PM, QA] 10-10EZR - Standalone form: Engage HEC team/Josh F for E-2-E testing

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#67230]
## Background
Internal QA has been completed.  We need to have End-to-End testing completed to ensure that the Enrollment system can receive the data with no issues.
**Note** - Confirmed ES team will not perform their own QA.  We will continue with this ticket. 

### Details on testing
- We will use the same [use cases](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-1010EZR-Update-health-care-benefits.md)
- Authentication Data details:
     - You can test Authenticated ([Users 11, 12, 15, 38 or 228](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)) or Unauthenticated
     - We can work with Joshua Faulkner to change the Test User status between "enrolled" and "pending:mt"
- Expected Results:
     - We are able to submit the form successfully
     - We confirm with Joshua Faulkner that the Enrollment System has received the application and all data successfully
          - We will provide him with the Name used in the Form

## Tasks
- [ ] Perform E-2-E test runs
- [ ] Confirm successful transmission of data from test runs has been completed
- [ ] Once all E-2-E testing is successful, reach out to Jessica Soza and Simone Gully on testing (HEC Stakeholders)

## Acceptance Criteria
- End-to-end testing is completed successfully

**Comment by hdjustice** [comment]
Running a test with Joshua Faulkner to confirm receipt of EZR form with no errors.  Will update here once test has been done - Include response from Joshua confirming successful transmission

**Comment by hdjustice** [comment]
Refer to #70627 for more details on testing, as we have encountered some challenges.  This ticket is no longer needed
