### ISSUE TITLE
[Wizard] VHA Make updates based on stakeholder feedback

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#67235]
## Description
Open this ticket once VHA has sent feedback. We will make updates based on their feedback.

## Tasks
- [x] Update VHA path

## Acceptance criteria
- [x] VHA path updated

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by HeatherRienks** [comment]
Need to meet with VHA before pointing

**Comment by mgleo** [comment]
Updates to make:

- Path: **Request a hardship determination and copay exemption to stop paying future copays**
  - Contains information about 1010HS. Add information about 1010EZ which ceases medical prescription copays. Add information letting them know if needs to be filled out every year.
- Path: **Ask VA to reconsider the decision on my waiver request**
  - Condense this two way path into one and it should instruct user to Call HRC.
- Path: **Pay my copay bill**
  - Investigate how or if we can add their account number to this path.

**Comment by mgleo** [comment]
@denisecoveyduc Updated mockup for 
Path: **Ask VA to reconsider the decision on my waiver request**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenVvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce334cc06445343f87295a2db81107656ce30928/Screenshot%202023-11-06%20at%201.02.27%20PM.png)

**Comment by mgleo** [comment]
@Dr-Pongo 
Is is possible to display the user's account number on a Wizard page if they are logged in? It would need to appear above the "Pay your copay bill at Pay.gov" action link seen below.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenlvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b1eab654e48c08ecd5c4ddbc82efcded8afed238/Screenshot%202023-11-06%20at%201.03.51%20PM.png)

**Comment by denisecoveyduc** [comment]
Quick note about the request to add the account number onto the page if a Veteran is logged in. While this is certainly helpful let's balance against other priorities as it is on our roadmap to better integrate with pay.gov in the future. Adding the account number has always been a short term solution so if the level of effort is too high no need to proceed. FYSA: @Tom-Davis

**Comment by mgleo** [comment]
CAIA ticket for updates to /health-care: [#69414](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69414)

**Comment by mgleo** [comment]
@HeatherRienks @Tom-Davis Updates have been made based on 11/03/23 meeting. 

@denisecoveyduc shared the [following information on 11/08](https://dsva.slack.com/archives/CPE4AJ6Q0/p1699462846337499?thread_ts=1699462840.502099&cid=CPE4AJ6Q0) from VHA stakeholders. :

1. It flows nicely.
2. For a monthly repayment plan we do not use the VA Form 1100. We use a newer form, the VA Form 10-323, copy attached. That form may, in some instances, have to be partially completed by VHA Revenue staff, but even so it would be nice if you could provide a link for a person to get a copy of that form.
3. What is the difference between a reconsideration of a decision and an appeal of a decision. (In our mind, they are effectively the same so why separate actions?
4. For the dispute of a copay bill – or, for that matter, any bill – we tell the Veteran that the 5655 is not the form they need. Some could interpret that to mean that there is a form, but the 5655 is not it. Can we tell them that a form is not necessary as we direct them to the link (to call the HRC)?

#2 and #4 are new information and CAIA is now aware the of new 10-323 form update as the CAIA ticket has been updated: [#69414](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69414)
Response below:
2. We’ll also need to update any reference to 1100 and replace it with 10-323. I updated the CAIA ticket to note that. It would also be nice to place a note on the old 1100 form page that it is outdated and route them to a 10-323 about page, currently there is a PDF but not an about page.
3. This was discussed during the meeting and we are going to route them to one single page (not 2 paths) that will instruct them to call HRC.
4. We’re directing them to https://www.va.gov/health-care/pay-copay-bill/dispute-charges/ to dispute a copay bill. Is there anything on this page that CAIA needs to update as well?

**Comment by mgleo** [comment]
@HeatherRienks @Tom-Davis Moved to validate
