### ISSUE TITLE
Add duplicate pruning to allow list cleanup job

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#67245]
## Issue Description
The allow list has a small number of duplicates that are appearing over time (not many) and there's not been any clear link to why. It only happens to some specs, seemingly at random time intervals. After discussing the options, we felt the easiest way to solve this, since it's infrequent, is to add a function to the cleanup script to remove duplicates from the BQ table.

---
## Tasks
- [x] Add function to the cleanup script for the allow list to remove duplicates from the allow list.
- [x] Decide on a cadence of how often this should be run and adjust accordingly.
- [x] Add an additional instance of cleanup before the allow list is published, to ensure the published version has no duplicates.

## Acceptance Criteria
- [x] Duplicates are regularly cleaned up from the allow list.

**Comment by CBonade** [comment]
Duplicate pruning is implemented on my branch and working correctly. Not scoped was the deleting of records as it pertains to files being on the allow list that no longer exist in vets-website being expanded to cover unit tests as well (being handled in the same script). The work on this piece has already made substantial progress and will wrap tomorrow morning.
