### ISSUE TITLE
Update Yeoman app generator to remove auto-generated code that does not pass linting

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#67252]
## Issue Description
The [Yeoman app generator](https://github.com/department-of-veterans-affairs/generator-vets-website) auto generates code that does not comply with our current linting standards. There are deprecated imports among other code warnings that are thrown which are requiring teams to do extra work on spinning up an app. We need to do a pass through the generated code and make sure the code that's being generated complies with our current linting standards. 

---
## Tasks
- [x] Verify that Yeoman is still a candidate to work with Node 22 before doing any other steps.
- [x] Generate a sample app and open a PR against vets-website for it
- [x] Make note of all linting errors on the PR
- [x] Correct those errors in the auto-generated code
- [x] Delete the original app and close the PR. Create a new app and open a new PR
- [x] If any linting errors still exist, repeat the process until there either are none, or the only ones left are not able to be solved. If any are not able to be solved, we should open tickets to either address why they can't be solved or why the linting rule exists if it's too strict. 
- [x] Evaluate Yeoman as a viable solution

## Acceptance Criteria
- [x] Newly generated apps using the app generator do not come out of the box with linting errors.
---
