### ISSUE TITLE
[FE] Display Message when there are no Appointments that were found in MAP for the Veteran

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#67257]
## Wireframes
It is [this one](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/v8V43G8) without the yellow alert. I don't think we have a board representing it on its own. Will this work (to ignore the yellow alert) or would you like me to whip up one without it?

<img width="440" alt="Screenshot 2023-10-10 at 1 16 35 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/79372956/055b0965-5224-49e0-9775-334e3c4c5b59">

## Tasks
- [ ] [FE] **Display a message when there were no appointments that were found in MAP for the Veteran**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
@benbrasso-agile6 do we have a wireframe for this scenario?

**Comment by benbrasso-agile6** [comment]
I think you and @cgednalske are confusing things. Christina showed it to you in the other ticket. The one she showed was not a map service error.

**Comment by wullaski** [comment]
@benbrasso-agile6 do we have figma files for this scenario? It's when the api call works but there are no upcoming appointments.

**Comment by loripusey** [comment]
is the wireframe that is in the ticket description not the correct one? because I thought we provided a wireframe.

**Comment by benbrasso-agile6** [comment]
https://www.figma.com/file/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-Check-in?type=design&node-id=0-1206&mode=design&t=dWzYPl0mCaWHY87U-4

**Comment by wullaski** [comment]
@benbrasso-agile6 do you think we need GA tracking on those links?

**Comment by benbrasso-agile6** [comment]
I think we just leave those as is. E.g., if we keep them as the link-component, then I think there will be a GA event, but it just won't have "check-in" appended to its value. 

And, I recommend this because of the unknowns about GA4. So, I don't want to keep doing too much "custom" GA work now. 

@loripusey sound right?

**Comment by loripusey** [comment]
sounds as reasonable as anything knowing that we really don't know anything right now about how we will interact with GA4 going forward
