### ISSUE TITLE
Transition Redis to Serverless

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#67267]
### Description
Transition from an AWS Elasticache dedicated to serverless solution for vets-api redis caches for preview environments

### Tasks
- [x] Create terraform in [prt-preview-manifest](https://github.com/department-of-veterans-affairs/prt-preview-manifest)
- [x] Test Vets Api with serverless Redis

### Acceptance Criteria
- [x] New Preview Environment builds have serverless Redis
