### ISSUE TITLE
[FE] My VA: Technical discovery for My VA health care updates

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#67262]
## Background
In support of [67261](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67261) and [67349](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67349), it's likely we'll need some precursory technical validation on the solutions from the work and conversations that come out of those design tickets. This ticket is to cover any technical discovery/research needed to validate the following solutions:

- handling the "view all" concept on My VA (health care and claims, where it makes sense)
- understanding what changes are needed, if any for how we identify health care users and/or Cerner users as a subset

### Helpful to know:
- New MHV landing page is at 100% for phased launch
- Users can see the MHV landing page if they are registered at a VA facility (which is part of the VA health care enrollment process, but note that a user can be registered at a VA facility but not be enrolled in VA health care as well)
- The health care applications handle Cerner users individually within each - so a Cerner user sees the new MHV landing page and clicks on appointments, messages, prescriptions, etc and is then directed accordingly based on Cerner status - _which means we could potentially also do away with the Cerner message on My VA_

## Tasks
- [x] Meet with MHV folks to do some knowledge sharing on "enrolled in healthcare" and Cerner patient logic (FE, Design and PM)
- [x] Identify technical changes needed to our logic for handling either, specifically we need to whether `is patient` and `is registered` are effectively the same (i.e. are we identifying "health care users" the same way as MHV)
- [x] Discuss with team/share findings with MHV as needed
- [ ] Work with PM for implementation tickets as needed

## Resources
- [Slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1696948394667719)
- Something to note: Cerner users make up less than 2% of users enrolled in VA health care (~150k Cerner users of 9 million enrolled in VA health care)

**Comment by ajakabcin** [comment]
Linking the [Mural](https://app.mural.co/t/test51728/m/test51728/1696602856977/9092eb5a210f6759b1c7c54987492850c590019b?sender=5e984b7f-926e-44cb-a787-e2784fce7896) Carlos created during the call yesterday for reference @allisonlu

**Comment by allisonlu** [comment]
## mhv landing page logic

for a user to see the MHV landing page, the following criteria must be met:
1. must be logged in
2. feature toggle `mhvLandingPageEnabled` must be turned on
3. the facilities attribute in `user` state is greater than 0

to determine #3 above, cartography team uses a [selector that checks what facilities exist is associated with the user](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/user/cerner-dsot/selectors.js), and whether or not the facilities are Cerner. (looks like this file is maintained by the public websites team)

## is this the same as our logic?
- tbd - contacted AE engineers how isVAPatient determined on the backend

## possible issues
- tbd

## relevant files
- [MHV landing page's logic to determine whether or not user sees the landing page](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/mhv/landing-page/selectors/isLandingPageEnabledForUser.js#L21-L32)
- [selector to get user's facilities](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/user/cerner-dsot/selectors.js)
- [selector to check if user is a VA patient](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/user/selectors.js#L7)

**Comment by ajakabcin** [comment]
@allisonlu thank you for this update! That's odd about the third criterion - I thought cerner status was not a factor for seeing the MHV page?

**Comment by allisonlu** [comment]
@ajakabcin you're right, i added too much info. Cerner status is NOT a factor for seeing the MHV page.

**Comment by ajakabcin** [comment]
Thank for digging into this @allisonlu! If I'm understanding correctly then we do not need to make a change to our logic?

**Comment by ajakabcin** [comment]
[Shared our findings with MHV in their team channel](https://dsva.slack.com/archives/C04GDQSHD1R/p1698248191355239)
