### ISSUE TITLE
[Matt] - Determine what can happen this sprint and the build strategy

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#6726]
## Tasks
- [x] Ensure all design tickets are in
- [x] Finalize Profile 2.0 Build Tickets
- [x] Determine time requirements for completion of Pre-Usability Review
- [x] Determine what can happen this sprint
