### ISSUE TITLE
Setting up Satisfaction Survey Dashboards in Domo

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#67281]
## Purpose
We recently learned that Airtable wasn't allowed behind the VA network wall.  Survey Monkey is supposed to be. BUT then we learned that is not; our available option is Optimal Workshop, which allows surveys ([called Questions](https://support.optimalworkshop.com/en/collections/1524596-questions) for some reason).

What would be involved in, and how could we, use Optimal Workshop for the quarterly Platform Satisfaction Survey and get the data into a tool such as Domo for actionable data visualizations?

Documentation on OW access [here](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-OptimalWorkshop) and use Platform.

## Tasks
- [x] Set up collaborative session to learn from preexisting Feedback Portal dashboards
- [x] Reference GT's domo dashboards for inspiration
- [x] Create useful data visualization cards in Domo

## Acceptance Criteria
- [x] Satisfaction Survey Domo dashboards are drafted

**Comment by tayism** [comment]
Rolling over to next sprint for continued work

**Comment by tayism** [comment]
Splitting this ticket as it grew larger due to the need for team review, as well as providing enough space for octo/leadership review.
