### ISSUE TITLE
Testing for eMIS Military Info fields to VaProfile

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#67283]
### Summary
- This ticket is for testing the non-prefill changes made as part of #61657. AND for getting the military info emis changes across the finish line.

### Tasks
- [x] identify non-prefill changes
- [x] split disability into its own PR
    - [x] Manifest repo PR for disability settings
    - [x] PRs are merged
- [x] come up with a testing plan
- [x] identify test users (list for disability users - [EDIPI column in the sensitive repo](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv))
- [x] test
- [x] make edits per feedback
- [x] wrap it in a flipper (do not include disability)
- [x] get the PR tested

### Acceptance criteria
- [ ] All tasks are complete
- [x] Testing passes or tickets are made to follow up on failing tests

**Comment by rmtolmach** [comment]
### Non prefill changes:
File: `app/models/id_card_attributes.rb` has two methods, `branches_of_service` and `discharge_types` that use the new military information. There are unit tests for these, but just as an additional check, we can manually test them. Steps for that:
1. Open up the rails console
2. create a test user:
```
require 'ostruct'

user = OpenStruct.new(
  edipi: "123456789",
  first_name: "John",
  last_name: "Doe",
  address: { street: "1234 Elm St", city: "Anytown", state: "ST", postal_code: "12345" },
  email: "john.doe@example.com",
  home_phone: "555-555-5555",
  veteran_status: OpenStruct.new(title38_status: "VETERAN"),
  military_information: OpenStruct.new(
    service_episodes_by_date: [
      OpenStruct.new(
        branch_of_service_code: "F",
        discharge_character_of_service_code: "HON"
      )
    ]
  )
)
```
3. `id_card_attributes = IdCardAttributes.for_user(user)`
4. `id_card_attributes.traits` should return a full hash. In particular, the last three keys should have values
In terms of testing in the UI, I'm not sure where a user would hit the ID card attributes controller... but we might not need to test that if we're testing in the rails console.

**Comment by laineymajor** [comment]
Rebecca is on support today (subbing for Rachal)... will begin testing tomorrow.

**Comment by rmtolmach** [comment]
- PR to vets-api for the disability portion: https://github.com/department-of-veterans-affairs/vets-api/pull/14205
    - PR to Manifest repo (1 of 2): https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2345
- PR to vets-api for the rest: https://github.com/department-of-veterans-affairs/vets-api/pull/14184 (:x: Note: tests will be failing in this branch until the disability PR is merged!)

**Comment by laineymajor** [comment]
From meeting with Tom 
https://developer.va.gov/explore/api/veteran-service-history-and-eligibility

^lighthouse API that calls out to VaProfile that gets all the info we need

**Comment by rmtolmach** [comment]
Gia and I added more tests to https://github.com/department-of-veterans-affairs/vets-api/pull/14205. It's ready for review.

**Comment by rmtolmach** [comment]
### Non Prefill changes testing
To get a user (steps from Trevor):
1. Log in with a user through [staging.va.gov](http://staging.va.gov/) (for this I’m assuming you’re logging in with an idme user)
2. Take the ICN for that user, and do: UserAccount.find_by(icn: <icn>).user_verifications.where.not(idme_uuid: nil).last.idme_uuid
3. Take that idme_uuid, and do: User.find(<idme_uuid>) and you’ll have a user object you can do stuff with

For step 1, I logged in with `vets.gov.user+16@gmail.com`.
Steps 2 and 3:
```
irb(main):006:0> UserAccount.find_by(icn: "1012849574V585256").user_ve
rifications.where.not(idme_uuid: nil).last.idme_uuid
=> "dc1781484dea4ff6a2b0b068bc56f98c"
irb(main):007:0> a =User.find("dc1781484dea4ff6a2b0b068bc56f98c")
=> 
#<User:0x00007f80c4b1d608
```
Making sure these commands worked:
```
irb(main):008:0> @disability_service = VAProfile::Disability::Service.
new(a)
=> 
#<VAProfile::Disability::Service:0x00007f80ba0e57a8
...
irb(main):009:0> @military_personnel_service = VAProfile::MilitaryPers
onnel::Service.new(a)
=> 
#<VAProfile::MilitaryPersonnel::Service:0x00007f80b9dbeac0
```
And then I took user `a` and ran the steps below to test that all the values were returned. They were 🎉 
```
irb(main):012:0> id_card_attributes = IdCardAttributes.for_user(a)
=> 
#<IdCardAttributes:0x00007f80b853fd50
...
irb(main):014:0> id_card_attributes.traits
{"host":"vets-api-web-6c98d68988-wv7pw","application":"vets-api-server","environment":"production","timestamp":"2023-10-26T22:11:54.249743Z","level":"info","level_index":2,"pid":321,"thread":"59700","file":"/app/lib/va_profile/veteran_status/service.rb","line":45,"named_tags":{"dd":{"trace_id":"0","span_id":"0","env":"eks-staging","service":"vets-api","version":""},"ddsource":"ruby"},"name":"Rails","message":"VaProfile title38: V1"}
=> 
{"edipi"=>"1005123832",
 "firstname"=>"Jim",
 "lastname"=>"Byrd",
 "address"=>"810 VERMONT AVE NW",
 "city"=>"WASHINGTON",
 "state"=>"DC",
 "zip"=>"20420-0001",
 "email"=>"vets.gov.user+16@gmail.com",
 "phone"=>"(202)366-8900",
 "title38status"=>"V1",
 "branchofservice"=>"ARMY,ARMY",   <--- This is what I'm checking to make sure returned
 "dischargetype"=>"DVN,DVN"}   <--- This is what I'm checking to make sure returned
```

**Comment by LindseySaari** [comment]
Ran into an issue with missing attributes not being wrapped in a feature toggle. Step 1) Wrapping in a FT 2) Researching the data mismatch

**Comment by rmtolmach** [comment]
1. Feature toggle work done in https://github.com/department-of-veterans-affairs/vets-api/pull/14327. Need a review from Identity team.

**Comment by rmtolmach** [comment]
### Character of discharge code
**Background**
When we merged PR https://github.com/department-of-veterans-affairs/vets-api/pull/14205 without wrapping the `discharge_types` code from `id_card_attributes.rb` in the feature flipper, that code was in production for about 24 hours. During that time, some veterans reported that they were getting the wrong character of discharge code for the VIC form. This was reported [in this Slack thread](https://dsva.slack.com/archives/C03LT909K1A/p1698431721264129).

**Research notes**
- In eMIS, the attribute is `discharge_character_of_service_code`
- In VA Profile, the attribute is `character_of_discharge_code`
- In both of them, the attribute lives inside an array of military service episodes sorted by date aka `service_episodes_by_date`. That means a veteran can have multiple character of discharge codes. 
- What are the options for what the discharge code can be for VA Profile and for eMIS?

VA Profile
| Code | Name                                             | Honorable Service Indicator |
| ---- | ------------------------------------------------ | --------------------------- |
| A    | Honorable                                        | Y                           |
| B    | Under honorable conditions (general)             | Y                           |
| D    | Bad conduct                                      | N                           |
| E    | Under other than honorable conditions            | N                           |
| F    | Dishonorable                                     | N                           |
| H    | Honorable (Assumed) - GRAS periods only          | Y                           |
| J    | Honorable for VA Purposes                        | Y                           |
| K    | Dishonorable for VA Purposes                     | N                           |
| Y    | Uncharacterized                                  | Z                           |
| Z    | Unknown                                          | Z                           |
| DVN  | DoD provided a NULL or blank value               | Z                           |
| DVU  | DoD provided a value not in the reference table  | Z                           |
| CVI  | Value is calculated but created an invalid value | Z                           |
| VNA  | Value is not applicable for this record type     | Z                           |

eMIS

**Comment by rmtolmach** [comment]
On the call with VIC team this morning, we learned that the text of a character of discharge code ("Honorable" for "A", for example) is returned on their end. HOWEVER, Gia and I can't find anywhere in our code bases (vets-api and vets-website) where we're doing any manipulation of data that would return the text of a code to the VIC application.

**Comment by rmtolmach** [comment]
PR is merged. Closing.
- New ticket to research character of discharge code mismatch: https://github.com/department-of-veterans-affairs/va.gov-team/issues/69312
- Ticket to test form 1880: https://github.com/department-of-veterans-affairs/va.gov-team/issues/69260
