### ISSUE TITLE
Create Introduction Page

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#67310]
## Issue Description
Create new "Introduction" page veterans per the [most recent design](https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/p/3C666192-27DA-40CE-B314-BA779A8C8BD4/canvas#Version). 

---
## Tasks
- [ ] Implement the necessary React components and styles for the page
- [ ] /representative route should land on Intro page

## Acceptance Criteria
- [ ] Find a Representative loads properly styled Introduction page in staging

**Comment by holdenhinkle** [comment]
This ticket is not currently in an epic because it doesn't belong in the search or form epics.

**Comment by cosu419** [comment]
10/12 update: Created new component, added text content, set up routing.

**Comment by oddball-lindsay** [comment]
Consider converting this to epic, with breakouts into more specifics for this page

**Comment by cosu419** [comment]
Moving this to "Done" considering the page is create/ displaying in staging - all "Home Page" tasks going forward will be associated with the [MVP: Home page](https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/67705) epic
