### ISSUE TITLE
GA4 - Web Components & Gtags

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#67332]
## Issue Description

Continue work on web components event mapping and gtags. Prepare to meet with Design System team.

---
## Tasks
- [ ] List of gtags and status - keep, remove, add, change, etc
- [ ] Who do we need to share gtag updates with (if anyone)?
- [ ] Review list of web components and current mapping/tracking status
- [ ] Schedule meeting with Design System team to provide status update and next steps.
- [ ] Provide project updates to leadership

## Acceptance Criteria
- [ ] Above items completed.
