### ISSUE TITLE
Identity Dashboard BDPR branch isolation

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#67340]
## Issue Description
The BDPR features of the Identity Dashboard are not likely to be used in the near future; they should be removed into a Github branch so that they can be restored to `main` at a later date if need be.

---
## Tasks

- [x] create `bdpr_isolation` Github branch for VA Identity Dashboard
- [ ] Datadog querying removal
- [ ] Credential index/lock/unlock removal
