### ISSUE TITLE
[Design] My VA Health Care: Design alternative solution(s) for handling Cerner users on My VA

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#67349]
## Background
Before we decide to do away with the message entirely, we need to identify some design options for handling Cerner users (if different from non-Cerner) and discuss pros and cons.

### Helpful to know:
- New MHV landing page is at 100% for phased launch
- Users can see the MHV landing page if they are registered at a VA facility (which is part of the VA health care enrollment process, but note that a user can be registered at a VA facility but not be enrolled in VA health care as well)
- The health care applications handle Cerner users individually within each - so a Cerner user sees the new MHV landing page and clicks on appointments, messages, prescriptions, etc and is then directed accordingly based on Cerner status - _which means we could potentially also do away with the Cerner message on My VA_

## Tasks
- [x] Meet with MHV folks to do some knowledge sharing on Cerner patients (FE, Design and PM)
- [x] Create design option(s) (as needed) for eliminating Cerner message
- [x] Discuss with team

## Acceptance Criteria
- [x] Knowledge share with MHV occurs
- [x] Design option(s) for solution without Cerner message reviewed and discussed

## Resources
- [Slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1696948394667719)
- Something to note: Cerner users make up less than 2% of users enrolled in VA health care (~150k Cerner users of 9 million enrolled in VA health care)
-

**Comment by aagosto90** [comment]
Discussed design concepts with team on 10/27/23.
We decided to just show all health care links for Cerner users, which will include a new link to My HealtheVet on VA.gov.
[Desktop mockup](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/VradRV8)
[Mobile mockup](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/YGlJVpL)
