### ISSUE TITLE
Duplicate Submissions

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#67356]
## Issue Description
VHA has found a few duplicate submissions where it appears that a second submission immediately followed the first. 

TransactionId	Timestamp
37d42220-468d-42cb-9744-0dbbe5148cca	10/3/2023 20:33
bb5b735a-eb82-451a-829a-eca3f80861af	10/3/2023 20:33

b06f03fd-5a4b-4b27-86e4-8ef73d53dc17	10/3/2023 20:57
cf7b1a8a-80e6-48b0-a5bd-80778833157e	10/3/2023 20:57

23ece900-50a9-4139-9472-1bd1cb035630	10/3/2023 22:33
1aae920d-a294-4858-8b30-850844e17984	10/3/2023 22:33

155ff594-fe55-4823-87a5-68cd7170c1ad	10/4/2023 17:48
d700a2fb-fafb-4caf-8b96-a51b27522615	10/4/2023 17:48

6de90091-9d2a-43b8-869b-572cd511f811	10/4/2023 17:49
71231667-eeca-410b-94f9-8f1a1630927c	10/4/2023 17:49

---
## Tasks
- [x] Determine the cause and next steps. 

## Acceptance Criteria
- [x] Next steps have been documented
- [x] Notes have been added to ticket describing cause (please tag Denise)
---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kjsuarez** [comment]
When creating VHA 5655 submissions we break FSR applications up by facility number. This has been the case long before the introduction of the Streamlined Waiver. All of the supposed duplicate submissions had different facility numbers. As far as I can tell FSR submission logic is behaving as usual. This is a feature, not a bug.
```
"37d42220-468d-42cb-9744-0dbbe5148cca" vs "bb5b735a-eb82-451a-829a-eca3f80861af"
"facilityNum"=>"689", "facilityNum"=>"631"

"b06f03fd-5a4b-4b27-86e4-8ef73d53dc17" vs "cf7b1a8a-80e6-48b0-a5bd-80778833157e"
"facilityNum"=>"516", "facilityNum"=>"538"

"23ece900-50a9-4139-9472-1bd1cb035630" vs "1aae920d-a294-4858-8b30-850844e17984"
"facilityNum"=>"648", "facilityNum"=>"459"

"155ff594-fe55-4823-87a5-68cd7170c1ad" vs "d700a2fb-fafb-4caf-8b96-a51b27522615"
"facilityNum"=>"515", "facilityNum"=>"610"

"6de90091-9d2a-43b8-869b-572cd511f811" vs "71231667-eeca-410b-94f9-8f1a1630927c"
"facilityNum"=>"620", "facilityNum"=>"528"
```

**Comment by denisecoveyduc** [comment]
Thank you @kjsuarez I have passed this on to our VHA partners.  Crisis averted.. _no bugs here_! 
@Tom-Davis @HeatherRienks  ok to close this one out.
