### ISSUE TITLE
[Research] Dot Indicator: Create convo guide for usability study

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#67353]
## Background
Angela completed the draft research plan for dot indicator options last sprint (in [66479](https://github.com/department-of-veterans-affairs/va.gov-team/issues/66479)), now we need to write up the convo guide for the study.

## Tasks
- [x] Draft conversation guide for usability study
- [x] Review with another designer/researcher as needed
- [ ] Share with PO and PM

## Acceptance Criteria
- [ ] Draft conversation guide exists in Github

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ Convo guide exists and is reviewed

## Resources
- [Draft research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/dot-indicator/research/dot-indicator-research-plan.md)

**Comment by andaleliz** [comment]
Hi @aagosto90! Thanks for asking me to take a look at these docs, what a treat! Well done 👏  my comments are all pretty minor. Lmk if you have any questions!

## Both convo guides
- I love that you have the link to the Sketch file in at the top, clearly called out as a back up plan. Smart thinking.
- In the intro you state "Today we're going to be reviewing a feature on VA.gov that helps Veterans identify unread or unseen things after logging into the website." and I wonder if that's priming them to answer some of the first questions about what they think the indicator means. I might leave that out of the intro and just say you're going to get their feedback on some new features being considered for the site or something more vague.
- I'm pretty sure the page people are supposed to be reviewing is My VA, but I don't think it specifies that in either guide or in the research plan. I'd specify that in the docs so it's crystal clear what page was tested for this research.

## Sighted user convo guide
### Main section
>If they don't mention the indicators Did you notice the red dot or the red notification badge with the number in it?

Just in case you need a backup moderator, I would add "If they **are not colorblind, and** don't mention the indicators" since the next prompt is only for colorblind participants

## SR user convo guide
### Intro
- Since one of your research goals is to determine the accessibility of the indicators, you might want to verify their SR technology in the intro portion, before you get started. Would you end the session if it turns out they don't use a screenreader, or they are a fully sighted person who uses a screen reader only to enhance their experience on websites (we had a participant like this in the hub study)?

### Main section
There are a couple of questions framed as "What would you expect to see" and you might want to update that to remove the reference to vision.

## Research plan
I know you didn't ask for feedback on the research plan, but I needed to look at that to understand the guides and have a couple of comments:  
- One suggestion I'd make is to consider recruiting some folks with cognitive considerations. This could help ensure there's clarity between the dot with and without the numbers, and if people can remember what they mean as they go through the site completing tasks. 
- I haven't used the recruitment ticket format before for criteria, so I'm not totally sure how it works. Do you need to specify which pieces of info you want on the roster (e.g. "has colorblindness")?
- I don't think this matters so much based on how you have the SR convo guide written, but wanted to call this out: 
  - I'm 99% sure if a participant joins from an iPhone and uses VoiceOver, you won't be able to hear the screen reader. It can still work but it's awkward to facilitate and you have to rely on the user being able to narrate a lot. 
  - If that sounds undesirable, you might want to get more specific w/ the SR/mobile criteria and say "SR desktop or Android only" or something like that. I'm not sure how VoiceOver works on an iPad with zoom.

**Comment by Samara-Strauss** [comment]
Sorry, this fell off my radar. All materials look good to go for when we're ready to run this study. Thank you for leaving things in great shape, Angela!
