### ISSUE TITLE
Form Template Update 

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#67357]
## Issue Description

Please update the template worksheet for the 2 new form products to be added to forms dashboard. 

[update instructions](https://vfs.atlassian.net/wiki/spaces/AT/pages/1510408350/How+to+-+Loading+a+new+funnel+to+the+Forms+KPI+Dashboard)

[21-0972](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/66744)

[21-0845](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/66742)

---
## Tasks
- [x] template created (Christine) https://docs.google.com/spreadsheets/d/18h4dkwkJGjbaz8_wrETvDGYeeVZ18ehM5NIRexhS5mI/edit#gid=1109167657
- [x] template uploaded to BQ (Phil)

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelle-dooley** [comment]
@dorseypa1 the [template](https://docs.google.com/spreadsheets/d/18h4dkwkJGjbaz8_wrETvDGYeeVZ18ehM5NIRexhS5mI/edit#gid=1109167657) is complete and ready to load.
