### ISSUE TITLE
Knowledge download from Kyle Soskins

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#67369]
## Issue Description
Ticket to make the work visible for learning and recording/documenting information from Kyle Soskins on 526.

Note: Sam already has a lot of info documented on a wiki page 
---
## Tasks
- [ ] Record/document information as part of these sessions
- [ ] Reaching out to Team 2, Kyle
- [ ] Coming up with items we want to learn about

## Acceptance Criteria
- [ ]Artifacts/recordings of these sessions

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
