### ISSUE TITLE
Unit Test Allow List: ensure specs exist before stress testing

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#67379]
## Issue Description
If a test is deleted in a branch, it will be registered as a "Change" and try and stress test a deleted test. We should check that the tests exist before flagging a file for stress testing.

---
## Tasks
- [x] Implement a step that checks if a spec file exists as part of the filter for selecting tests to stress test.

## Acceptance Criteria
- [x] A deleted test spec will no longer try and run in the stress test.
- [x] If a deleted spec is the only change, then the stress test skips.
---

**Comment by CBonade** [comment]
All set here!
