### ISSUE TITLE
[Design] My VA: White card design refinement + documentation

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#67372]
## Background
From Angela's My VA design discovery over the last few sprints we've determined we'd like to move forward with the white card component implementation. This ticket is to capture the work related to any additional refinements to the white card designs, FE documentation and review/discussion with the devs.

## Tasks
- [x] Finalize white card designs
- [x] FE documentation for implementation of white card designs ([new version My VA small initiatives folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/my-va-small-initiatives/my-va-white-card-component))
- [x] Review with devs for any questions they have about implementation

## Acceptance Criteria
- [x] Designs are ready for implementation
- [x] FE documentation is written
- [x] PM has created subsequent FE implementation ticket(s)

**Comment by aagosto90** [comment]
[FE documentation is here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/22b86d2816eec79d3bf5f73975ae27adc8f1b716/products/identity-personalization/my-va/my-va-small-initiatives/my-va-white-card-component/white-card-component-FE-documentation.md)
