### ISSUE TITLE
Unit Test Allow List: **Launch Blocking** Flaky NEW test should not block full app via allow list

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#67382]
## Issue Description
Right now, any test that fails the stress test gets listed on the allow list and becomes merge blocking. A new test, however, should only fail the feature branch and not get listed on the allow list. If a new test is blocked and never merged, there's no reason to block the rest of the app work while that test is worked out.

---
## Tasks
- [ ] Separate new tests logic from existing tests getting stress-tested.
- [ ] Ensure that new tests that fail the stress test don't get added to the allow list with a disallowed status.

## Acceptance Criteria
- [ ] New tests do not become merge blocking if never merged into main.
---
