### ISSUE TITLE
Successfully run vets-api CI on CircleCI

### ISSUE THREAD

**Issue by johnpaulashenfelter** [department-of-veterans-affairs/va.gov-team#6738]
We need to try running the CI suite for vets-api on CircleCI.

The front-end team has moved their build process to CircleCI thanks to @bkjohnson and the upcoming plan for the operations team is to move all of CI from Jenkins to CircleCI to keep with @nathanhruby plan.

This issue is a home for all the steps involved in moving CI to CircleCI. 

Key success criteria:

- [x] Pass `rake ci` on CircleCI *using a fork of the repo*
- [ ] Update CodeClimate from circleci

Stretch Goals
- [ ] Verify specs run faster/slower

**Comment by johnpaulashenfelter** [comment]
This is really important -- all of the work here initially needs to be done on a fork of the repo. Any failing check in GitHub will break review instances and related parts of Jenkins that require all checks to pass. Found that out in vets-api#3940

**Comment by johnpaulashenfelter** [comment]
Big thanks to @bkjohnson for getting this started in https://app.circleci.com/pipelines/github/bkjohnson/vets-api?branch=circleci-project-setup

**Comment by johnpaulashenfelter** [comment]
Now that we have success, updated a lot of the goals
