### ISSUE TITLE
[Design] 10-10EZ - Reg Only: Exploration on Intro page updates

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#67390]
## Background
As part of integrating the Registration Only pathway into the 10-10EZ application, we want to explore update the Introduction page to include details on scenarios including specific cases such as **mental health** and **future discharge dates** (accounts for 8-10% of monthly submissions), Veteran and non-Veteran, etc.  
We need to also consider adding something in here to **reference the EZR** (for those enrolled already). 

## Tasks
- [x] Explore what kind of information would be useful on the Intro page that would assist Veterans to complete the application, even if they are not sure what benefits they can get or if they 'qualify'
- [x] Draft content to incorporate that information
- [ ] Include an encouragement to apply even if they have a future discharge date
     - [Resource VA Page](https://www.va.gov/health-care/eligibility/active-duty/#enhanced-eligibility-for-retur:~:text=center%20near%20you-,Getting%20started%20with%20VA%20health%20care,-Can%20I%20apply)

## Acceptance Criteria
- We will have some ideas on how to update the existing Introduction page to include information for the scenarios that may not have been included before.

**Comment by hdjustice** [comment]
Added reference to adding something for EZR for those already enrolled, and to update the signed-in alert style.  I received some feedback from Shira/Allison that our alert style is not up to date with the Design System.

**Comment by jessicastump** [comment]
Based off of the recent registration v2 discussions - an early exploration of the intro page is started - [Figma link here](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=8277-114092&p=f&t=RwwuupjEh9EQwh6X-0). These mocks are starting with the unauthenticated and mobile designs. 
@hdjustice - added to agenda for the registration early am meeting and the weekly design sync, but we can chat more beforehand if needed

**Comment by jessicastump** [comment]
@hdjustice - Another ticket that maybe should be closed this sprint per updated priorities? This one was never moved into "in-progress" officially but was worked on and drafted in Figma --- just never discussed with content/attended office hours

**Comment by hdjustice** [comment]
Yep, I think we can close this one too.
