### ISSUE TITLE
Only allow waiver FSR reason for streamlined submissions

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#67399]
## Issue Description
There was an instance of a Veteran submitting an FSR form with the FSR reason of compromise. We should only allow for streamlined submissions to be waivers
---
## Tasks
- [ ] Discuss with design / engineering teams best way to handle this edge case
- [ ] Implement updates to only allow waiver

## Acceptance Criteria
- [ ] Streamlined submissions can only come across as waiver
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
Bring up at VBS Sync on 12/15/23 @kjsuarez, @Tom-Davis.

**Comment by asmithgovcio** [comment]
I created a pull request for this https://github.com/department-of-veterans-affairs/vets-api/pull/14988
