### ISSUE TITLE
[FSR] Distinguishing between Vista and Cerner Submissions

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#67409]
## Description

Mike Dewey (VHA) sent over a test case which prompted questions about lines 16 and 17 of the business requirements which read as follows:

For Line 16 the business case reads:  
_"As a Veteran Services Technician, I need VODA to provide an indicator to Huron when a Veteran submits a debt relief request through the VODA portal to indicate if the debt is at "VistA", "CERNER", or "VistA & Cerner" systems, so that I can ensure I review all of a Veteran's debt"_

For line 17 the business case reads:
_"As a Veteran Services Technician, I need VODA to provide Huron a unique ID (SSN) to the Veteran when CERNER debt is present, so that I can ensure quickly search for the Veteran in CERNER."_

Currently VODA isn't differentiating between Vista and Cerner submissions in what we are sending across.  VODA is however sending the facility number.

Per Mike, this indicator was captured as a requirement because some Veterans at a station that has moved to Cerner might still have debt within VistA, or as additional sites move over to Cerner, we need a way downstream to know what system to look into and need to know for automation within Huron.

Scenario: VODA needs to include an indicator in the 

Given: (The beginning state of the scenario)
When: (Specific action that the user takes)
Then: (Testable outcome that can be captured in the testing section, usually caused by the action in When)

## Tasks
- [ ] Task one to complete the work in the description
- [ ] Task two to complete the work in the description
- [ ] Task three to complete the work in the description

## Acceptance criteria

- [ ] Item one from the description performs as described in the description
- [ ] Item two from the description performs as described in the description

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by HeatherRienks** [comment]
Need to discuss with VBS team - will add to agenda for 10/20/23.

**Comment by ScottyRJames** [comment]
To add further context from this, we do have areas within our services that check specifically if a statement is cerner. For example in the file `/app/services/medical_copays/vbs/response_data.rb` we have the function

```
 ##
 # Custom cerner account number to match PDF
 #
 # @return [Hash]
 #
 def calculate_cerner_account_number(statement)
   return unless account_number_present?(statement['pH_CERNER_ACCOUNT_NUMBER'])

   facility_id = statement['pS_FACILITY_NUM']
   patient_id = statement['pH_CERNER_PATIENT_ID']
   offset = 15 - (facility_id + patient_id).length
   padding = '0' * offset if offset >= 0

   statement['pH_CERNER_ACCOUNT_NUMBER'] = "#{facility_id}1#{padding}#{patient_id}"
 end
```
checking for existence of  cerner account number.

**Comment by HeatherRienks** [comment]
Discuss in VODA - VBS Agenda on 1/5/24

**Comment by HeatherRienks** [comment]
Added this as an agenda item to VBS | VODA Sync agenda on 1/5/24.

**Comment by kjsuarez** [comment]
There are some questions to be answered between Mike Dewey and Mike McDougall before we can act on this ticket.

**Comment by HeatherRienks** [comment]
This was discussed at length in the 1/19/24 VBS| VODA sync with Mike Dewey, Mike McDougall and team.
Summary:
-Kevin can add an indicator (for Vista or Cerner) and he will communicate with Varun Uppa (Huron) before making the change. 
-Per Varun's request, Kevin will add indicator at the end AND Kevin will send a test file in advance.

**Comment by HeatherRienks** [comment]
Per Kevin, info needed from VBS on how to distinguish between Cerner and Vista statements

**Comment by kjsuarez** [comment]
As of 2/23/2024 VBS sync, Huron is reviewing a test file with the new attribute. We're just waiting for the approval now.

**Comment by kjsuarez** [comment]
Code change [merged](https://github.com/department-of-veterans-affairs/vets-api/pull/15790/) and released. Relevant parties (VBS, Huron) notified via email.
