### ISSUE TITLE
Discovery Meeting for "Limitation of Consent" bug

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#67403]
## Issue Description
We have uncovered a bug [The "Limitation of Consent" is calling a job that no longer exists](https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/65925) that will affect our future goal of digital submission for the 21-22 and 21-22a forms.

This ticket is for an initial discovery meeting with Lee DeBoom, who is a Tech Lead with the VetsAPI team.  Hoping to more about the implications around this bug, and to start outlining some ideas for resolution.

---
## Tasks
- [x] Schedule meeting with Lee DeBoom
- [ ] Discuss the bug, related implications, and potential steps to resolution
- [ ] Document findings for future reference

## Acceptance Criteria
- [x] Meeting with Lee has been held
- [ ] Notes from the meeting are documented

**Comment by oddball-lindsay** [comment]
Holden and Jonathan will be meeting with Lee on Monday 10/16

**Comment by oddball-lindsay** [comment]
vets-website isn't using this, but some other teams are using these vets-api endpoints.

Lee started a thread with Holden to explore more, including what services are using these endpoints.

**Comment by oddball-lindsay** [comment]
Closing out as the meeting was held -- @holdenhinkle if there are any notes or slack threads worth referencing, please share here for future reference!

**Comment by oddball-lindsay** [comment]
Ticket to address bug is here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/65925
