### ISSUE TITLE
VHA Manual Test File Validation

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#67416]
## Issue Description
Mike Dewey (VHA) has reported that within the 55 submissions we sent him to test manually Varun (Huron) was not able to match several transaction IDs to submission data. I asked him to send them to us so we could provide some level of understanding. Here is a list of the transaction IDS he was not able to find submission data for

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1lzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--132fc4a4b7298a369a6b3d05dd62b8f97c641ac7/image.png)

---
## Tasks
- [ ] Determine why Huron could not find submission data for these transactions
- [ ] Summarize findings on ticket and notify @denisecoveyduc 

## Acceptance Criteria
- [ ] Clarity has been provided and any next steps/further action items have been documented (if applicable)

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Pulled both records up from our database and both instances have a successful state of `submitted` with no error message from either VBS or SharePoint API requests. Have validated that they do indeed contain copay data making them VHA submissions.

**Comment by denisecoveyduc** [comment]
@ScottyRJames Is it possible to get the facility number for each of these submissions?

**Comment by denisecoveyduc** [comment]
10/13/23 - Need to discuss this on the call today across VODA/ VBS/Huron. When VODA sent 55 transaction IDs, Varun was not able to find the submission data for these. Scott confirmed and according to VODA the files were processed as expected and no errors were found.  

Initial discussion questions 
- When were these submissions sent to VBS from VODA? Ie file dates.
- Was there a breakdown between VBS and Huron? Any identified errors?
- Can the files be found in SharePoint?
- etc…

**Comment by ScottyRJames** [comment]
>Is it possible to get the facility number for each of these submissions?

Yes!

`25c932a2-064a-45ac-816c-78629972b24b`

Facility Number: 548
Submission Date: 10/05/2023

`175fda71-610f-4933-97a5-12fbec5fcd66`

Facility Number: 516
Submission Date: 10/05/2023

**Comment by HeatherRienks** [comment]
I shared these with Mike Dewey and Scott confirmed that the 2 transaction ID's noted below, were combined submissions (containing VBA debt). 

25c932a2-064a-45ac-816c-78629972b24b
3158e664-ef16-4968-9751-d950ed083d26

The follow up question from Mike is; _"Just to confirm, the fix to allow the calculator to still run on those even with a VBA debt is on the queue?"_

**Comment by HeatherRienks** [comment]
@ScottyRJames - I forgot to tag you on this; any updates would be great!

cc: @denisecoveyduc @Tom-Davis

**Comment by ScottyRJames** [comment]
@Heather Rienks Yes that is still in our plans. For the immediate future we're looking at adding combination FSR status in additional comments field. We've outlined some future work for this too in [#66112](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/66112)

**Comment by HeatherRienks** [comment]
@ScottyRJames 

There is one more request from Mike to look into a transaction id (from the second batch that Denise sent). After this is confirmed, let's close this ticket out and any additional requests will be in a new ticket.

From Mike:
"Reviewed the recent 65 sent over and this one was a non-auto-approved… I assume it was also a dual (VBA and VHA) debt… however, can your team confirm?"
e2f0f10e-e847-4e0c-85da-0c07beef2a4d

**Comment by ScottyRJames** [comment]
@HeatherRienks This transaction id was eligible for streamlined (only VHA, flag on, copay amount under $5000) but it's one of those instances where the GMT Data we got back from the income thresholds endpoint was an empty object

cc: @Dr-Pongo @OptionSelect @amponce

**Comment by HeatherRienks** [comment]
Per @Dr-Pongo there is a fix in place to prevent empty objects from appearing. (see ticket #xxx)
