### ISSUE TITLE
[SW] Change from VES to HUD for Income thresholds (Discovery)

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#67426]
## Description

Scenario: If we were to move from using VES data to HUD data for Income limit thresholds, we need to define the LOE for the development work.

In scope: Research, estimates
Out of scope: Any development work, ticket creation

Given: We are asked to estimate this change
When: We define the steps to change from VES to HUD data for income limit thresholds
Then: We can provide the LOE of the work so we can plan how much time is needed and lead times if the change is formally requested

## Tasks
- [ ] Define how we would receive HUD data
- [ ] Define what on our code needs updated and where
- [ ] Define the LOE/Number of tickets/Points to complete the work

## Acceptance criteria

- [ ] We have listed the LOE/Number of tickets/Points to complete the work

## Testing
- [X] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [X] Description written
- [X] Tasks defined
- [X] Acceptance criteria written
- [X] Testing defined
- [X] Add Labels
- [X] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by HeatherRienks** [comment]
Per @denisecoveyduc - let's put this on hold for now.

**Comment by denisecoveyduc** [comment]
This ticket is no longer required, closing it out as a result.
