### ISSUE TITLE
[FE] My VA: Implementation of changes to Cerner handling

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#67432]
## Background
As outlined in #67349 we are simplifying the way we handle Cerner users on My VA by eliminating the "Cerner alert" message and instead opting to show them a link to the new MHV landing page as well as all the tool links in the link list.

Updated designs:
- [desktop](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/VradRV8)
- [mobile](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/YGlJVpL)

## Tasks
- [x] Open PR to add feature flag on `vets-api` – name: `my_va_remove_cerner_message`
- [x] Put the following changes behind a feature flag on `vets-website`
  - [x] Remove cerner message
  - [x] Implement logic to show "link list" per designs
- [x] Update tests
- [x] Let PM know this is ready for validation

## Acceptance Criteria
- [ ] Cerner users see a the list of health care tool links as follows:
<img width="445" alt="Screenshot 2023-10-27 at 4 02 41 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/8ae74a3d-a451-4477-924d-6c0d7a49b634">

## Validation
- _Who can validate this ticket?_ any team member
- _How can this work be validated?_
1. Log into staging with a cerner user 
2. Confirm health care link list appears on My VA

**Comment by allisonlu** [comment]
@ajakabcin 

Two questions!

1. Should these changes be behind a feature flag?
2. Is this the only Cerner message we're removing?

![Screenshot 2023-11-14 at 5 42 18 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8542413/1f859a28-d55f-462c-a5e4-b75597fe86f6)

**Comment by ajakabcin** [comment]
@allisonlu 
1. Yes :) 
2. We should get rid of the bottom image all together in the code. It's old. We should keep the top image in the code/available via feature flag in case for some reason we need to roll these changes to Cerner experience back. That way we have this message as an option.

Thank you!

**Comment by allisonlu** [comment]
@ajakabcin 

according to the frontend deployment dashboard, these changes should be on staging! but i'm not sure what user has Cerner. 

here's the feature flag when you find a user:  https://staging-api.va.gov/flipper/features/my_va_remove_cerner_message

**Comment by ajakabcin** [comment]
Confirmed on staging with user 36!
![Screenshot 2023-11-16 at 4 20 55 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/3e62ee25-668d-4a78-bc4c-c5ed7c9f27ae)

**Comment by ajakabcin** [comment]
Hmm something seems different today - now seeing text about appointments for the same user. Allison is investigating.
![Screenshot 2023-11-17 at 1 09 12 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/482cfca6-e3c3-4d94-ac32-d2f5a5b3f3f6)

**Comment by allisonlu** [comment]
@ajakabcin 

the copy is now not appearing for user 36! can you confirm this too?

**Comment by ajakabcin** [comment]
Confirmed and reviewed by Samara as well! We can discuss when we want to put this out to users in huddle today

**Comment by ajakabcin** [comment]
Complete! We'll turn the flag on in prod on 11/28 (after the holiday) via #70309
