### ISSUE TITLE
Add intros and/or footers to 5 parents pages

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#67437]
## Tasks

Add either intros or footers or both to the following parent pages:
- [x] [Standards](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1827897612/Standards)
- [x] [Tools](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1828913296/Tools)
- [x] [EKS](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2451963907/EKS)
- [x] [Quality Assurance (QA)](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1847820556/Quality+Assurance+QA)
- [x] [Accessibility](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1255931908/Accessibility)

Use this intro template to write all the intros:

This page contains links to documents that will help you better understand [Insert Page Title]. These linked documents contain information and guidelines that will assist you in improving VA.gov.

**Comment by vbellissimo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/67437?planning-poker) with Zenhub @rferguson13 @laucon @taylojill
