### ISSUE TITLE
DR | Remove release feature flags

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#67435]
## Value Statement
**_As a_**  developer
**_I want to_** remove feature toggles for 100% released apps
**_So that_** we don't need to perform unnecessary checks

## Background Context

Feature flags for our decision reviews used upon release still exist within the vets-website & vets-api code base and should now be removed:
- NOD: `form10182_nod`
- SC: `supplemental_claim`

HLR feature toggles have been completely removed

## Tasks
- [ ] Clean up NOD feature toggles
- [ ] Clean up Supplemental Claim feature toggles
- [ ] Remove work in progress alert & associated code
- [ ] Update unit & e2e tests

## Definition of Done
- [ ] Feature toggles removed
- [ ] Work-in-progress messages removed

## Acceptance criteria
- [ ] All tasks complete
