### ISSUE TITLE
Update 674 Form

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#67456]
## Issue Description
_The online 674 form is out-of-date with the paper form and needs to be updated._

Sketch file
---
## Tasks
- [ ] Remove old fields
- [ ] Add new fields
- [ ] Update version of form pdf that is generated

## Acceptance Criteria
- [ ] 674 form generates a complete version of the most recent form pdf
- [ ] PDF successfully submits to downstream system
---

**Comment by ajialeilani** [comment]
Income question added back to Step 3: Remove divorced spouse.

[Figma](https://www.figma.com/design/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?node-id=2758-112211&t=9Ty4uYYt4iQYVM33-1)

cc @Midge-dev @steele-lm
