### ISSUE TITLE
Capture FSR Transaction IDs for VHA manual review

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#67455]
## Issue Description
Need a second bath of transaction IDs for VHA manual testing to verify Streamlined Waiver calculation changes. 

---
## Tasks
- [ ] Extract 125 transaction IDs that meet the following criteria. Add them to the ticket and tag @denisecoveyduc 

**_Criteria:_**
- include the recent calculation changes (include cash in bank in cash calculation; removal of assets from calculations)
- Does not include any VBA debts
- Does not include any copay debts over $5000

## Acceptance Criteria
- [ ] 125 transaction IDs have been added to ticket 
- [ ] @denisecoveyduc has been tagged
---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by HeatherRienks** [comment]
@denisecoveyduc -  I think this has been validated and is no longer needed. Please confirm and this ticket can then be closed.

**Comment by denisecoveyduc** [comment]
Great catch @HeatherRienks this one slipped thru the cracks but yes these transactions IDs were validated by Mike (VHA) and we are all set.
