### ISSUE TITLE
Capture FSR Transaction IDs for VHA manual review

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#67458]
## Issue Description
Need a second bath of transaction IDs for VHA manual testing to verify Streamlined Waiver calculation changes. 

---
## Tasks
- [x] Extract 125 transaction IDs that meet the following criteria. Add them to the ticket and tag @denisecoveyduc 

**_Criteria:_**
- include the recent calculation changes (include cash in bank in cash calculation; removal of assets from calculations)
- Does not include any VBA debts
- Does not include any copay debts over $5000

## Acceptance Criteria
- [ ] 125 transaction IDs have been added to ticket 
- [ ] @denisecoveyduc has been tagged
---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by ScottyRJames** [comment]
Here are 125 transaction IDs that match that criteria (i.e. `is_eligible_for_streamlined_waiver` and `streamlined_waiver_asset_update` turned on)

```
"98ed227e-0ed1-4c33-81ce-5eb52a6d3729",
 "4baf2f98-72f0-4ce0-b82a-fb14085fdd5e",
 "daa5a35d-67b6-4665-aa06-5d3ab8657f6e",
 "50c39386-1e79-47db-b73c-d44409b55b95",
 "81a01fd7-8958-48cc-8415-db84c84d56a7",
 "456b5eaf-0218-48f3-bff7-00c471a13771",
 "33eda6f2-32a7-4ebc-8256-e19f679e96f6",
 "bfbb80ab-d45c-4da5-a78f-f9f248c5440b",
 "ff8d62f8-1909-466d-85cd-a4b61bf63f6d",
 "2103fd2b-bfc0-45bb-b6fe-1f07e2cbd704",
 "9121f953-3719-48ce-afcc-496b3411a8b3",
 "df5d1230-8c9b-497c-a0e8-f253a32fb411",
 "2e0d939b-7c73-4492-9bf8-9db9f9b56a8e",
 "2c8d5f4f-dcc8-47c9-afbc-2e8823ca6e25",
 "0b613922-22bd-4314-9841-e5d7852c080a",
 "ae04a74e-43a0-45ed-8139-6e88fba92fa7",
 "a393f675-6bac-43bd-82ce-ad64c605b4cd",
 "45f4c319-aa1e-4688-b0f9-e020e34bd889",
 "684c3868-ae71-437b-85bb-9877a60e8528",
 "e5712326-088b-4fcf-bd76-d6dbb8dafa47",
 "64c05823-fd30-43c4-94ca-a82168757e0e",
 "fa61102e-df8f-4f09-901a-0d71bbd9d906",
 "7c30d949-5827-4b84-b747-608adbb09ce2",
 "e124d9e8-e7dd-4e29-8e90-8630aac1259b",
 "1d0cdc16-0617-4453-a864-e3c8963f140e",
 "2b48caea-c116-4d4e-8cbf-a730dbd31ea4",
 "fb22a223-a117-4d80-bacd-cf3a15be8135",
 "7fe49841-e11e-4b52-bf34-030d96a6b26c",
 "42da4ca5-2b12-4a7a-99c4-4e67ccaeea5c",
 "f36f016b-39a6-4fb5-9596-d90d9867892c",
 "44289b5b-dd27-4f53-be22-ebf7fb36719d",
 "fe28e214-7b98-4dab-82c7-bed9f8a8ab91",
 "5e45af45-2d55-4caa-ac5b-fbf5da284093",
 "3ea25a12-e73b-4a5c-8bdb-62fe3078aeb8",
 "3359078b-fd24-47ea-86f3-24aa3cbdf4a9",
 "a42422e7-fa58-4bce-93af-7f50df403b4a",
 "281ddc30-592a-4a36-a428-71e66bacd5ab",
 "e03474a6-2895-4e8d-87fd-58630727f4a0",
 "1c728de7-197a-4c0e-8aee-b573710fb2df",
 "726f5903-155a-49a3-ae03-2ab9204c6825",
 "0565421d-79ba-45f9-8537-b6f5ef27506d",
 "2b711916-94e6-4d57-8944-00ade9347eb6",
 "866c6803-8954-4f80-a7a5-089dcf5c4a86",
 "3b7168ee-eb9c-4bc5-adf8-f577ea32a0e9",
 "b05275be-f68b-444b-8db2-2556290dba8f",
 "6b235409-9820-4952-818e-0d909a9ccdaa",
 "99d2ff02-4286-4d45-a567-9a1e61a874de",
 "939a8668-c181-47a2-8028-6423e003036b",
 "84e57434-1a3d-49ad-a005-eb604e83937c",
 "8e1f286f-56da-4767-b5b4-9e82a33b4bd9",
 "acfce674-377d-454c-9f80-9685d42d7d1e",
 "951a5dc6-f3f4-43c2-960b-5d11d4fb258e",
 "7b450abf-b712-43a3-bf3a-1f8d7abe1ed0",
 "f60faea0-7ab3-4bf2-95e1-8cba3dabac9b",
 "d3e2409d-0054-4691-a658-ea640f3ae516",
 "db2c1b71-3581-48bd-9dbe-76c11d07105b",
 "323f234d-e882-4ff6-8c9b-e7670ec295ce",
 "d4d9fd9a-8943-4a6f-af8b-715b33885746",
 "2d3ab086-6b89-49c2-8a24-51743533d4ed",
 "7290b8b5-7dfd-476c-8565-0391a35e32fd",
 "e920d64b-a8a2-4f25-bee2-0006e0e72470",
 "696f9291-4679-43c0-925a-2d272c7aedac",
 "b87bc36c-56bf-4815-a58a-92d00ac13cf5",
 "ee604312-98e1-41ba-9869-15b630af8b34",
 "3dff2e06-1e62-434c-bd20-b267c449988f",
 "5ab6dd32-767d-4a12-acc7-70fcb0af19e1",
 "65d9ab8d-0db4-4867-bceb-fc6dbb9b73ef",
 "3febf80a-16ee-4982-a07f-17aff9b551d7",
 "5ef5ec5a-132d-439a-95ea-eabfd4493a6b",
 "92b6a662-c360-40d2-b9ee-6e1124354068",
 "06500492-f8ba-4cb7-85ef-c576d904cb56",
 "629563b9-a8ec-4b00-9735-3fb202c16a14",
 "0a288d10-dc2a-4c27-b43f-740f3670ce8c",
 "1ea657a1-0f5a-435f-a41d-15cd65d2866d",
 "7bbae3b3-fe58-407e-be5e-9a055e7c99c3",
 "a82774f8-813e-40ba-a1cc-892a3142c515",
 "bb635dd6-7ad5-42fd-bb97-bfcc8259871b",
 "744b3c9f-1abd-45b5-b5e1-438ad4f26cae",
 "48527d0d-b6a2-4e2f-a640-101d0adfdb64",
 "9d50c320-89b3-450d-8d64-d81d35629a00",
 "6d767df7-7529-46ad-bfe9-752a2e471b5c",
 "55e13349-2cea-449e-9f89-e5e2208c66f1",
 "2a2fe299-3661-48df-910c-13ad619fad14",
 "306d9fbd-e74b-4dc7-b91c-f607017d2801",
 "dfc0f543-6d9b-42ce-a2f1-dbcfe5948611",
 "376d55d9-04dd-47b4-9a17-1502e558ca9d",
 "e2f0f10e-e847-4e0c-85da-0c07beef2a4d",
 "25d08fe9-e82f-45d1-bc4e-0759d4400607",
 "187c2328-38c1-4bac-aa1c-03ba79a948bb",
 "5f9afa2a-b7f9-466b-9812-eaeda19572fe",
 "e9c94b62-ed3e-4f9a-996b-ac56e28ac726",
 "37832f5f-38c9-4181-aca9-329f4e546cdf",
 "3f2fa1d0-eb2e-4189-9dcb-54e4b505e6f0",
 "ca3da2df-a43e-424b-822e-2d631ae0fa7b",
 "a59b6ae3-64e6-4d03-b888-b48820604fd7",
 "5b9e7c82-563c-4ef9-95f5-1ea761b82757",
 "42a80005-9b4f-45d4-9061-75954a797094",
 "77c13d0f-16bf-4a74-b61c-6b64ca162d61",
 "5faaf23f-193d-4821-b724-fb5f7ed8a3ab",
 "1287df15-3964-4754-98e8-39bdb8b09ba3",
 "235ed142-ba8b-496c-bdb1-aabf3e66c0a8",
 "3a5e2f4a-7966-41e4-986f-a9c034772e63",
 "13ee6a2d-da36-4572-aea2-b0c769abd808",
 "a490894e-d7a1-4695-973a-d8fde1a1f03c",
 "939c8440-c2d2-45c4-b3d0-58b54c2a0f49",
 "8e8e7acf-c67e-44fe-9c23-d18b5465cea8",
 "b7dc0e0c-28e8-43c2-84cc-12731f3b124b",
 "43bcc1d2-d185-42db-9e64-a974546d9da0",
 "ee661037-7452-4676-9e93-12fe63b0c304",
 "61b5a2ec-74dd-4b3a-bec1-ae255788a404",
 "0b0ee01e-c40e-4937-9d09-40c10c5c7db5",
 "fec8d014-b339-48ef-80fe-16d5f34091ac",
 "c775926a-0472-4668-8261-2468b2e5ad8e",
 "68711ea9-9747-4028-a963-ac5e1c4da53d",
 "816bab3b-f350-4bb5-9939-3c12cca1d717",
 "3d2d603c-0ab9-4535-a353-690f4b96f767",
 "bc476633-225c-48bb-b821-f64e6e03f5ec",
 "0144090b-347e-4136-9733-7b418c7a4a45",
 "0916d119-b145-4bdd-b164-b8d4951358eb",
 "92f4fa63-e9c8-42af-a6f5-10ad9fb868fc",
 "6ffc5f80-80f0-49c4-862a-4f434e830519",
 "3b4bbea9-f8ca-45ad-bb4d-ea50f28244e5",
 "7cd4a8aa-22c3-4f16-943a-65e5ae74f258",
 "7bf9ae20-a0ea-4bd3-8cda-d32a38bc23b7",
 "c7eb8490-31f3-4b77-9825-7645077eba90"
```

**Comment by HeatherRienks** [comment]
@denisecoveyduc - Mike Dewey mentioned on today's VBS|VODA sync that he has only received the first batch of 60 transaction ids. We let him know that you would be sending over the additional 65 records.

cc: @Tom-Davis
