### ISSUE TITLE
(Jamie) Document areas of research for Pension

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#67464]
## Issue Description
As a new Pension team,
we need to identify areas of research for Pension and forms-related experiences,
so we can have an understanding of work to prioritize

---
## Tasks
- [x] Document area of research for Pension
- Incorporate outcome/metrics that correspond to each effort
- [x] Incorporate rubric for prioritization
- [x] Meet to discuss with PM & Design Lead
- [x] Reach out to with VA stakeholders for input

## Acceptance Criteria
- [x] We will have an understanding of different research areas to work on and initiated communication with VA stakeholder about findings
