### ISSUE TITLE
Research | Dependency Research Prep

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#67469]
## Issue Description
_Prepare materials for upcoming dependency research session with Veterans._

---
## Tasks
- [x] Schedule pilot sessions
- [x] Follow-up with Shane on any feedback and ensure ticket is passed onto Perigean
- [x] Kickoff with Perigean
- [x] Prepare notetaking templates
- [x] Prepare sign-up sheet
- [ ] Communicate with Perigean on how recruitment is going, and adjust criteria as necessary to meet our deadline

## Acceptance Criteria
- [x] We are ready to run our first research session with Veterans
---
