### ISSUE TITLE
Draft survey for Veteran Onsite Testing

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#67476]
At the end of the Pilot, we'd like to survey Veterans to ask about their perception ease of the service, preparedness of VA staff, understanding of the changes that occurred/benefits gained, ability to locate proofing agent within facility, feedback on anti-fraud letter (and educational materials?), comfort with environment (privacy, confidence in staff, etc)

Acceptance Criteria
- [x] Word doc created
- [x] Thank you message at top for participation and how it will inform improvements to service and support for Veterans like you
- [x] Question asking about how easy was it to complete IPP, likert scale with text box to explain
- [x] Question about their perception of preparedness of VA staff, 5pt likert scale with text box to explain
- [x] Question about confidence in VA staff to ensure this is a secure process, 5pt likert scale with text box to explain
- [x] Question about how much they understand changes that occurred/benefits gained, 5pt likert scale with text box to explain
- [x] Question on ability to locate PA within facility, how easy 5pt likert scale with text box to explain
- [x] Question on comfort with environment, did it feel private 5 pt likert scale
- [x] Open text, feedback on anti-fraud letter
- [x] Open text, feedback on educational material
- [x] Any additional thoughts open text

Notes:
- do we need feedback on educational materials?
- how long/how many questions? 9 questions total, all optional

**Comment by SophiaPhilipMO** [comment]
[Veteran Survey](https://docs.google.com/document/d/1kUt6HKhiMGsH0pLzi0WHGFdRzgNTnl2PVnE4TU0J5lY/edit)

**Comment by SophiaPhilipMO** [comment]
@lmorris3 ready to check out

**Comment by SophiaPhilipMO** [comment]
Edits completed
