### ISSUE TITLE
DR | Move Container into shared file

### ISSUE THREAD

**Issue by rocio-desantiago** [department-of-veterans-affairs/va.gov-team#67478]
## Background Context

- Research was completed with the assistance of GitHub codeclimate to identify potential refactoring to reduce tech debt. As a result, the goal is to bring the ratings to A - to make code more manageable.
- The following functions will be refactored into a shared container file
  - `const issues` in 995/996/10182
- The Confirmation Page container has a Code Climate Rating of C
  - [src/applications/appeals/10182/containers/ConfirmationPage.jsx](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/10182/containers/ConfirmationPage.jsx)
  - [src/applications/appeals/995/containers/ConfirmationPage.jsx](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/995/containers/ConfirmationPage.jsx)
  - [src/applications/appeals/996/containers/ConfirmationPage.jsx](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/996/containers/ConfirmationPage.jsx)

## Out of scope

* Other apps/forms not in Decision Reviews
* Content changes

## Tasks

- [ ] Function moved into a new shared container file
- [ ] Unit tests updated (if applicable)
- [ ] Monitor Datadog and Sentry to confirm changes don't cause unforeseen errors in forms submission activity.

## Definition of Ready 

- [x] Identify functions to be refactored
- [x] Have access to decision reviews folder (src/applications/appeals/{appName}/utils) in vets-website repository 
  > 995 - Supplemental Claims (src/applications/appeals/995/containers)
  > 996 - Higher Lever Review (src/applications/appeals/996/containers)
  > 10182 - Notice of Disagreement (Board Appeal) - (src/applications/appeals/10182/containers)

## Definition of Done

- [ ] Functionality not changed
- [ ] Reduced files
- [ ] CodeClimate warnings go away and duplication in the PR is marked as fixed

**Comment by saderagsdale** [comment]
Eileen will look at content and confirm if the language is as intended @eileen-coforma @rocio-desantiago

**Comment by rocio-desantiago** [comment]
@saderagsdale
@eileen-coforma confirmed the language.
We should be matching Supp Claims ‘Date you filed your claim’

**Comment by rocio-desantiago** [comment]
**In progress:** Need to update HLR & NOD's _"Issues submitted"_ to _"You've selected these issues for review"_

**TODO:** I'd like to create a new ticket to address other subtle differences between the forms, @eileen-coforma can you peek these side by side and confirm if we can update HLR and NOD to reflect Supplemental Claim's version of a Confirmation Page?
| HLR | NOD | SC |
| ------- | ------ | ----- |
| <img width="600" alt="HLR confirmation page" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/37054305/a0539378-e137-499c-a320-468cb40f570e"> | <img width="600" alt="NOD confirmation page" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/37054305/2aea91e7-449d-4b75-bca1-ff0e268ddce7"> | <img width="600" alt="SC confirmation page" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/37054305/f6b73c88-c36a-40d1-b2f1-5b6c9f6cd0f0"> |

**Comment by HeatherWidmont** [comment]
@eileen-coforma & @rocio-desantiago to discuss in today's parking lot

**Comment by eileen-coforma** [comment]
Discussed it with the devs. Settled to separate changes to copy from changes to code. That way design also has a step to update documentations for changes.

**Comment by rocio-desantiago** [comment]
Logged into Staging and validated with @eileen-coforma
