### ISSUE TITLE
List of file numbers for pension and burial forms

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#67487]
## Issue Description
_We are seeking clarification from the VBA on what is communicated to Veterans who submit online 527 and 530 forms, so we can determine if Veterans are being asked to start over with paper forms or if they are being asked to simply provide the information that is missing from their claim._

---
## Tasks
- [x] File numbers and dates of submission for FIVE 527 claims submitted within the last 2-3 months
- [x] File numbers and dates of submission for FIVE 530 claims submitted within the last 2-3 months

## Acceptance Criteria
- [x] List of file numbers and dates provided to Emily Theis
---

**Comment by tblackwe** [comment]
delivered via Teams
