### ISSUE TITLE
Discovery of EVSS Reporting 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#67498]
## Issue Description
_Internal discovery of EVSS reporting documenting internal data to be included in per Sprint cases reporting 
---
## Tasks
- [x] Review Salesforce data 
- [x] Reviewing DOMO data 
- [x] Analyze multiple scenarios

## Acceptance Criteria
- [x] _Determine categorization of transferred cases per sprint 
- [x] Determine closed cases per sprint
- [x] Ability to report accurate data each sprint
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
