### ISSUE TITLE
VFS Roster Transition from Platform Governance/Analytics to Platform Support

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#67495]
## Description 
This EPIC ticket will house the work related to transitioning management of the VFS Roster to the Platform Support Team. Historically, it was joint managed by the Platform Governance and Platform Analytics teams.

---

## Definition of Done
All tasks below are complete.

---

## Tasks 

Below are the tasks we should complete. Each one has been broken out into individual tickets to make the work digestible.

- [ ] Identify a way for the Platform Support Team to be notified when they need to add someone to the VFS roster
- [ ] Identify the best practice for granting Vets.gov-write access (i.e. SOCKS access required, etc. chat with Shira/Bill Chapman about next steps)
- [ ] Document the process for adding someone to the VFS Roster (talk to Ian about the current process and add in any changes we make)
- [ ] Alyssa to add process to the Service Design Blueprint (if necessary)

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by EWashb** [comment]
I would suggest scoping this ticket down to just being a transfer of current roster state and that process to our support team. That will alleviate the immediate issue I was looking to solve which is reassigning support-types tasks from other Platform teams to our support team. Those tasks should be Tier 1 level items such access, documentation, etc.

Typically I prefer not assigning sprints to tickets with large dependencies on other teams. With that in mind, what can be reasonably accomplished by our internal team within the sprint boundaries? 

I think another epic or other issue should be create for the second task of the vet.gov-write access since that is dependent upon another team and other POs. cc: @alyssagallion

**Comment by alyssagallion** [comment]
Duplicate ticket. This ticket has been broken out into two others:

- [Add Step to Governance Offboarding Ticket](https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/70208)
- [VFS Roster: Identify the Best Practice for Granting Vets.gov-write Access](https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/67613)
