### ISSUE TITLE
Design | Validation for Spouse File Number

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#67494]
## Issue Description
_Currently, there is no field validation in place for a Veteran's Spouse's File Number. The downstream database only accepts up to 9 characters, and claims that exceed that limit are rejected. Validation needs to be added to the spouse file number field to eliminate this error._

Things to consider:
- The Veteran may not know their spouse's file number and may currently enter their service number which is 10-12 digits.
- The Veteran can enter a spouse's file number or social security number in the file number field.
- The field can be left blank
- The error or info messaging should guide the Veteran to enter the correct number.
- 9 digits for ssn, 8 digits for file number

---
## Tasks
- [ ] Draft error messaging to display when the spouse file number is equal to 8 characters OR their ssn number is 9 characters
- [ ] If needed, draft info messaging to guide Veteran in entering spouse file number
- [ ] Obtain CAIA approval of error message

## Acceptance Criteria
- [ ] CAIA-approved wireframe
---

**Comment by tblackwe** [comment]
We already have good requirements in the design system; I was just unaware of them.

https://design.va.gov/patterns/ask-users-for/social-security-number

will be handled in ticket #67213
