### ISSUE TITLE
Spike | Confirm moving CH 36, CH 31, COE, burial to LH

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#67499]
## Issue Description
_We need to understand if the Ch 36, Ch31, Burial, and COE endpoints should be moved to LightHouse._

---
## Tasks
- [ ] Confirm any negative downstream impacts
- [ ] Confirm migrating endpoints is approved by Emily Theis and/or Steve Albers

## Acceptance Criteria
- [ ] Decision on migrating endpoint
---

**Comment by tblackwe** [comment]
Validated approach. Moving forward with Benefits Intake API submission tickets
