### ISSUE TITLE
[BE] Backend support: Get vets-api localhost setup to connect to staging servers

### ISSUE THREAD

**Issue by dellerbie** [department-of-veterans-affairs/va.gov-team#67500]
## Tasks
- [ ] Get AWS access
- [ ] Connect to the forward proxies that connect to staging

## Acceptance Criteria
- [ ] Can successfully connect to staging servers locally

**Comment by ajakabcin** [comment]
@tpharrison Derrick suggested this a good starter ticket for when his replacement arrives, to work with you to get AWS access and then localhost setup. Just fyi!
