### ISSUE TITLE
Project Kickoff [Left Nav]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#6751]
**NOTE: This kickoff request is not for a new project, it is for a "recalibration" meeting for a project which has changed teams several times and is already in flight.The goal of this request is to review where this project is, how it got here and which reviews/milestones will be required from here.**

The left nav was built as part of the VAMC page enhancement for Pittsburgh. It was tested in November/December 2019. There was a plan to incorporate the left nav globally so changes were initiated by the Public Websites team. Those changes were pushed only to staging at this point. When a decision was made not to roll it out globally, it came to the Facilities team. 

[Feature Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/product/vamc-left-nav-enhancement-feature-brief.md)
[Usability Research readout](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/global/left-nav/research-findings.md#findings-by-hypothesis)
[Staging](https://www.va.gov/pittsburgh-health-care/)

## Steps to complete Project Kickoff
- [ ] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [ ] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan will schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] VSP <> **requesting team** kickoff meeting completed
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please bring the following to the kickoff meeting_
- [Feature Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/product/vamc-left-nav-enhancement-feature-brief.md)
- Explanation of the problem space
- Any other artifacts you have so far
    - [Here are Ryan's latest designs for the left nav](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1874#issuecomment-595797269)
- You **do not** need to prepare a presentation

## Meeting attendees from **requesting team**
- Product Manager (required): **Michelle Middaugh**
- DEPO Product Lead (required): **Dave Conlon**
- Entire VFS team (recommended): **Aricka Lewis, Gibran Rodriguez, Lance Sanchez,**
- Extended team members: **Kevin Hoffman, Ryan Thurlwell**

## Scheduling
Preferred dates or times: A Friday at noon ET is an existing meeting for the Facilities team. I can look for other dates and times if needed.

**Comment by meganhkelley** [comment]
Scheduled for 3/19

**Comment by jenstrickland** [comment]
@mmiddaugh @rtwell Do you have links or screenshots of the latest left nav designs? The latest aimed to address the accessibility issues identified in the one audited, and usability tested, at the end of 2019.

**Comment by jenstrickland** [comment]
From @mmiddaugh Here are the latest designs for the side nav: https://github.com/department-of-veterans-affairs/va.gov-team/issues/1874#issuecomment-595797269

**Comment by jenstrickland** [comment]
@rtwell Do you have a link to the mobile designs so it can be added to this review epic?

**Comment by jenstrickland** [comment]
Please note @rtwell mobile designs for the left nav were added to https://github.com/department-of-veterans-affairs/va.gov-team/issues/1874#issuecomment-601907235, and are available for review now.

**Comment by jenstrickland** [comment]
I updated VSA Accessibility feedback based on the mobile design.
