### ISSUE TITLE
SPIKE | Duplicate Veteran Record Error

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#67529]
## Tasks
- [ ] Research the root cause of Duplicate Veteran Record: Duplicate Veteran Records found on Corporate

## Acceptance Criteria
- [ ] Root cause documented
- [ ] Follow-on ticket created

**Comment by sortizsh** [comment]
error hasn't happened in the last 3 months. closing
