### ISSUE TITLE
SPIKE | Invalid Characters in Address

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#67522]
## Tasks
- [ ] Research root cause of Invalid Characters in Address: insertBenefitClaim: AddressLine1 has invalid character(s)
- [ ] Reproduce issue in Staging or Development

[Sample Error](https://vagov.ddog-gov.com/logs?query=%40named_tags.request_id%3A09f7606f-bef1-4c97-bfa2-4d710415313c&cols=%40payload.icn%2C%40payload.centralmail_uuid%2C%40payload.saved_claim_id&index=&messageDisplay=inline&refresh_mode=paused&storage=online_archives&stream_sort=time%2Cdesc&viz=stream&from_ts=1689272880000&to_ts=1697221200000&live=false)

## Acceptance Criteria
- [ ] Root cause documented
- [ ] Follow-on ticket created
