### ISSUE TITLE
Update rotate_keys_job.rb to Handle File Attachments and test through Dev/Staging envs

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#67532]
## Issue Description

Upon running the KMS Key Rotation in Dev (ticket [here](https://app.zenhub.com/workspaces/reliability-team-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/61334)), it was found that certain records could not be rotated successfully due to having encrypted attachments. After poking around we found that `kms_encrypt#rotate_kms_key!` does not work on File Attachments. In a note in the gem's README, we found:

```Note: This method does not rotate encrypted files, so avoid calling rotate_kms_key! on models with file uploads for now.```

So, while we can still run the job as is and re-encrypt all _other_ files, we need to iterate on this job to handle this case.

## Tasks

- [ ] Research other ways to encrypt attachments and confirm it can work in conjunction with kms_encrypted
- [ ] Run against Dev/Staging and confirm records are re-encrypted successfully

## Acceptance Criteria

- [ ] All records in dev/staging have been re-encrypted successfully

**Comment by ryan-mcneil** [comment]
Improved efficiency from less than 1000 rec/min, to about 13000/min! 

To achieve this, we updated the initial batching query to only grab IDs/primary keys, because pulling back anything related to KMS would trigger a POST request, that was very costly (time&money)
