### ISSUE TITLE
Re-run updated KMS Key Rotation in Production

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#67534]
## Issue Description

Assuming that the KMS Key Rotation job was ran an initial time for [this](https://app.zenhub.com/workspaces/reliability-team-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/61337) ticket, run it again with the added functionality introduced [here](https://app.zenhub.com/workspaces/reliability-team-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/67532).

## Tasks

- [ ] Merge to Production, and allow scheduled job to pick up records that initially failed to be re-encrypted
- [ ] Confirm all records were re-encrypted

## Acceptance Criteria

- [ ] All records in production have been re-encrypted successfully

**Comment by ryan-mcneil** [comment]
Will not implement - We'll only run once - in this [ticket](https://app.zenhub.com/workspaces/reliability-team-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/61337)
