### ISSUE TITLE
Discovery for Updating/Replacing vets-api Gem Dependencies for Rails 7 Compatibility

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#67538]
## Issue Description

Before upgrading to Rails 7, we must confirm all of our gems are compatible. This will likely require updating some of them, and potentially replacing some of them with comparable gems if they are deemed incompatible.

Documentation located [here](https://vfs.atlassian.net/wiki/spaces/PRT/pages/2797601179/Rails+7+Upgrade+Notes)

## Tasks

- [x] Create a list of list of gems that will need to be updated
- [x] Determine if any gems need to be replaced, and document information such which files/teams are affected by it

## Acceptance Criteria

- [x] [Documentation](https://vfs.atlassian.net/wiki/spaces/PRT/pages/2797601179/Rails+7+Upgrade+Notes) (In confluence, so that it can be used to track progress and as future reference) has been created listing all gems that will require updates/replacements, with any notes on estimated effort/implications
