### ISSUE TITLE
SPIKE | Parent Key Not Found Error

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#67556]
Info from Michael Taylor: Parent key not found - the parent key needed for VnP participant address is related to country type - to me, this means we allowed input of a non-recognized country.

## Tasks
- [x] Research the root cause of "parent key not found for address" error in 686 and 674

## Acceptance Criteria
- [ ] Root cause documented
- [ ] Follow-on ticket created

**Comment by steele-lm** [comment]
@tblackwe I added a spike for this. Do you know if this error is for 686 or 674?

**Comment by tblackwe** [comment]
It can be both 686 and 674

**Comment by tblackwe** [comment]
checking a small set of claims, they do all involve foreign addresses

**Comment by tblackwe** [comment]
Was able to reproduce the issue in staging by copying a university address from a prod claim.

**Comment by tblackwe** [comment]
INC29290855 created to research

**Comment by tblackwe** [comment]
We've identified the issue is due to the character code to country name converter `IsoCountryCodes` does not match the database key in all instances. Conditional logic was added for Great Britain a few months ago. My plan is to implement the additionally missing countries in same conditional for the short term

Long term plan is to update front end to leverage API for country name list.
