### ISSUE TITLE
SPIKE | Foreign Key Error

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#67559]
Info from Michael Taylor: Foreign Key FK2_VNP_PTCPNT_ADDRS(CNTRY_TYPE_NM) references CNTRY_TYPE (CNTRY_TYPE_NM)

## Tasks
- [ ] Research the root cause of "foreign key" error

## Acceptance Criteria
- [ ] Root cause documented
- [ ] Follow-on ticket created

**Comment by tblackwe** [comment]
Likely related to https://app.zenhub.com/workspaces/benefits-dependents-experience-6459139e7d64bf0015f6af13/issues/gh/department-of-veterans-affairs/va.gov-team/67556

**Comment by tblackwe** [comment]
INC29290855 created to research

**Comment by steele-lm** [comment]
@tblackwe to check and see if error persists.
