### ISSUE TITLE
SPIKE | School Address Too Long Error

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#67560]
Info from Michael Taylor: School address too long - length is 35 characters found [here](http://bepcert.vba.va.gov/VbaDaMetadata/metadata/common/schemaObjectWait.action?tableName=VNP_CHILD_STUDNT&dbName=PPRD3&schemaName=CORPPROD).

## Tasks
- [ ] Research root cause of School Address Too Long Error

## Acceptance Criteria
- [ ] Root cause documented
- [ ] Follow-on ticket created

**Comment by tblackwe** [comment]
resolved by https://app.zenhub.com/workspaces/benefits-dependents-experience-6459139e7d64bf0015f6af13/issues/gh/department-of-veterans-affairs/va.gov-team/64342
