### ISSUE TITLE
Update ATO POC in New VFS Team template and on Platform Website

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#67565]
## User Story
As a VFS team member, I want to request an ATO orientation from Platform Security team so that my team can complete Platform Orientation.

Assignee: @erinrwhite 
Peer Reviewer: @allison0034 

## Description
Faith Arthur has been the point of contact for the ATO Orientation. However, she is currently on maternity leave meaning that VFS teams aren't getting a response when they DM her on Slack.

Instead, new VFS Teams will be directed to the #Platform-security channel opposed to being told to contact Faith directly. 

## Impacted Artifacts
[ATO Orientation section of Orientation Sessions page](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-ATOOrientation)
[New VFS Team gh template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=analytics-insights%2C+governance-team%2C+platform-orientation&projects=&template=new-vfs-team.md&title=New+VFS+Team+%5BInsert+team+name+here%5D)

## Tasks
- [x] Edit the "How do people sign up" prompt of the ATO Orientation section of the Orientation Sessions page to remove, "Direct message Faith Arthur to schedule per directions in the New VFS Team ticket" and replace with
   - Post in the #platform-security Slack channel (wordsmith please?)
- [x] Edit the ATO (Authorization to Operate) orientation section of the New VFS Team gh template to remove, "Reach out to Faith Arthur on Slack" and replace with the same messaging

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] New VFS Teams are directed to reach out to the Platform Security team via the #platform-security Slack channel for their ATO Orientation

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@kenmayo @jhouse-solvd FYSA - we are planning to pick this work up this sprint

**Comment by allison0034** [comment]
Looks great!

**Comment by erinrwhite** [comment]
Squashed and merged [ATO section of new VFS team template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/new-vfs-team.md#ato-authorization-to-operate-orientation), ready for final review @allison0034 !

**Comment by allison0034** [comment]
Both items look good!

**Comment by erinrwhite** [comment]
Updated:
- [ATO section of new VFS team template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/new-vfs-team.md#ato-authorization-to-operate-orientation)
- [Platform website orientation page](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions)

Closing. Thanks @allison0034 for the review!
