### ISSUE TITLE
Separate Address and Contact Info Sections

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#67568]
## Issue Description
_Address and contact information field are currently on the same page, but they should be moved to separate pages to improve user experience._

---
## Tasks
- [ ] Separate address and contact info sections into two pages based on this [Sketch file](https://www.sketch.com/s/870d13d5-a465-48a3-acc2-32682ba8f780)

## Acceptance Criteria
- [ ] Address and contact info sections appear on separate pages
- [ ] Fiorella signs off on design in staging
---

**Comment by steele-lm** [comment]
Closing. This will be addressed in new designs.
