### ISSUE TITLE
Implement CAIA changes on Burial Review Page and Widget 

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#67566]
## Issue Description
_Stakeholders have requested some additional copy changes to the widget that will appear on the "how to apply" and form review page for the burial form deactivation. There is new copy on each page, no updated design or functionality. See Fiorella with questions. Original work on the pension widget was done in #64140 and review page in #63627._

CAIA changes are located within the Sketch files for the Review pages and Widget: 
- [Review Page (authenticated)](https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/a/4oEQqQJ)
- [Review Page (no draft claim)](https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/a/elb5Y52)
- [Widget How to apply (authenticated)](https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/a/DEVOlOk)
- [Widget How to apply (unauthenticated)](https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/a/mPM2J2V)

---
## Tasks
- [ ] Update copy in burial "how to apply" widget
- [ ] Update copy in burial "review page" widget

## Acceptance Criteria
- [ ] Copy updates appear in burial "how to apply" widget
- [ ] Copy updates appear in burial "review page" widget
- [ ] Fiorella signs off on design implementation

**Comment by steele-lm** [comment]
@fiorella-io Can you add the links to the specific Sketch file pages to this ticket? Thanks!

**Comment by Midge-dev** [comment]
This will need test coverage updates added - currently at 3/4 categories passing (80+ %)
We can create a separate ticket for that since it has to do with `ConfirmationPage.jsx` and not the Review page / Widget.

cc: @steele-lm @tblackwe 

![Screenshot from 2023-10-24 09-06-25](https://github.com/department-of-veterans-affairs/va.gov-team/assets/57480791/be32ec5d-f85f-4658-a3b6-8f9f2d90758e)

**Comment by steele-lm** [comment]
@Midge-dev and @tblackwe, I [drafted a ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68587) for the additional test coverage.

**Comment by steele-lm** [comment]
Closing. Burial form was not deactivated.
