### ISSUE TITLE
[FSR] Review Navigation - Debt selection removal on review navigation

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#67588]
## Description
Adding/removing selected debts while using review navigation can lead to a great number of issues for navigation, and streamlined calculations, so it's safer to remove it from the flow when in review navigation mode. 

Given: A veteran completes a form
When: A veteran uses review navigation to edit the form
Then: Debt selection page should be hidden from flow when in review nav

## Tasks
- [x] Update depends for debt selection page to include consideration for `reviewNavigation`

## Acceptance criteria

- [x] debt selection page is hidden from flow when in review navigation mode
- [x] current functionality is unaffected. 

## Testing
- [x] Ensure debt selection is hidden when in review navigation mode
- [x] Current functionality is unaffected

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by amponce** [comment]
PR is ready for review:

https://github.com/department-of-veterans-affairs/vets-website/pull/27188

@Dr-Pongo @OptionSelect
