### ISSUE TITLE
[FSR] Review Navigation - Income status change

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#67584]
## Description
While using review page navigation a veteran can adjust their income, assets, and expenses that could disqualify/qualify them for the automatic approval for streamlined waiver. If a user completed a shortened form, but during review navigation they disqualify based on new data we plan to send them down the full form with a transitional page at the end of the chapter to inform them we need to collect more information. If a user completed the full FSR an then made adjustments that qualified them for the automatic approval we should show the existing transition page and then send them to the final review/submit

Given: A veteran completes the form down one path (streamlined/full FSR)
When: A veteran uses the review navigation to make changes to the form
Then: They should be directed based on the new values that have been changed 

## Tasks
- [x] Exit review mode (set flag to false) if while editing we break streamlined waiver conditions, and continue down full FSR
- [x] Ensure this doesn't affect current SW flow
- [ ] Get clarification on if we need to remove excess data if a user completed the full FSR and then got approved for SW

## Acceptance criteria

- [x] Review navigation changes that affect SW are accounted for 
  - [x] Completed SW - needs to complete full FSR after changes 
  - [x] Completed full FSR - made changes that sends them down a SW path
- [ ] Existing functionality is unaffected by changes

## Testing
- [x] Manual testing for the following
  - [x] Completed SW - needs to complete full FSR after changes 
  - [ ] Completed full FSR - made changes that sends them down a SW path
- [ ] Existing SW functionality is unaffected

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by amponce** [comment]
@HeatherRienks @Dr-Pongo This issue is related to the fix implemented in the [spouse review navigation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67575), which was merged this morning. Essentially, the logic examines the previous state of the streamlined waiver and toggles the review navigation on or off if a change is detected in the streamlined eligibility. This is done instead of monitoring income directly. This fix should satisfy the requirements of this ticket, but further validation is needed.
