### ISSUE TITLE
Refine 686 Mockup Content

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#6760]
## Goal
Now that we have received feedback from various places, we need to insert those recommendations in to the mockups.

## Considerations
- There may be some guidance coming on how mailing addresses are handled
  - e.g., Accomodation for international, APOs addresses
- Note the messaging for 674 (individual students)
  - If we can gather multiples in one instance, this will change

## Tasks
- Implement the recommendations from the usability sessions
- Refine and revise the content for the intro screen, the form workflows, inline guidance and confirmation page.
- Have the changes reviewed by Peggy
- Gain clarification (in the form of a .md file in GH) from stakeholders on specific instructions/requirements

## Acceptance Criteria
- [x] Mockups have been updated
- [x] Peggy has been updated for review
- [x] A list of the changes are noted in a .MD file in GH

**Comment by sporeboy** [comment]
Text revisions tracked here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/screen-text

**Comment by sporeboy** [comment]
Peggy G. notified; she may wait for stakeholder feedback to review.
