### ISSUE TITLE
Discovery for setting up alerting of failed submissions

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#67605]
## Issue Description
As a new pension team,
we need to understand more about the Pension form's data submission process,
so that we can brainstorm a solution to create a failed submission backup solution for both the VBA and veterans.

---
## Task ideas
- [x] Reach out to Laura Steele
- [x] Reach out to Thomas Blackwell
- [x] Set up meeting with Steve Albers about his recommended best practices
- [x] Attend the meeting and document any ideas, insights shared by our technical leaders at the VA

## Acceptance Criteria

- Understand what kind the kind of backup alert process the VA technical stakeholders recommend to set up for Pension relaunch

**Comment by aplatt-coforma** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/67605?planning-poker) with Zenhub @mjknight50

**Comment by mjknight50** [comment]
Meeting is set for Wednesday, November 1⋅2:00 – 3:00pm EST

**Comment by vbellissimo** [comment]
### Meeting takeaways:

- Emily suggests backup and emergency failsafe paths. Check this Mural board out for details! https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697740873991/4be42fcadc013be6b3d65bd620522ee68e8e0faf?sender=u9189a8b68ad6598602620927
    - When Central Mail fails, extract raw for field data from va.gov database, get it to VBA in a claim document so the claim can be established/worked
    - We should build “re-tries” / when things failed, we didn’t have “re-tries” to make sure we know what to get to the VBA
        - Enabling re-tries is not as simple as we think; 1) we don’t want to accidentally create multiple claims; 2) we want to make sure veteran claim data sticks around beyond 24 hours
        - We don’t know if we can implement re-tries for unauthenticated form submissions
        - But... Sidekiq should not care if they are unauthenticated; we think re-try should work for unauthenticated form submissions
    - Stage 3 are most likely to fail
    - Stage 2 are a different kind, but less likely to fail than Stage 3
- To go to stage 3, it would take almost a year to migrate to VBMS
- Benefit to moving from Central Mail API to Lighthouse Benefits Intake API has a lot great support from maintenance team
- Sidekiq is supposed to be the queue system, there’s examples of how to get to Stage 0
- We need to know what might break within validation for this service for Stage 2/ submitted as a PDF package
    - Let’s assume we’re not owning the PDF generation service / we don’t know if we own it now
- We want to use the Lighthouse Intake API = accepts a package of documents rather than structure database


**Protocols for the following scenarios:**
* **Errors** - This will be in Datadog as notifications, there’s examples already; let’s set up a separate slack channel for this!
* **Lack of submissions/ anomalies in traffic** - Same as above
* **Using sidekiq: Failed queue submissions** - There’s examples of this, but let’s register this as a unique message name; have some place where we can find this and figure out what our Stage 0

**General to-do’s**
- Steve will provide write access to Datadog for Matt and team
- Matt will shadow Thomas creating a dashboard for his team
- Investigate PDF service, where is it - Pension team will take this on
- Implementing re-tries, signaling when exhausted
- Switch to benefits intake api
- Stage 0 - Emily things we 
- Matt to get intro to Datadog and review exiting logs and monitors


cc @mjknight50 This are some of my "takeaway" notes but feel free to modify based on anything I either misunderstood or missed.
