### ISSUE TITLE
Update form navigation to use new v3SegmentedProgressBar

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#67600]
## Issue Description
There is a new v3 progress bar that has been tested and is ready for use.  

Navigation currently in use:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzAxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b778d9cca08449f005131705e26b75c37680b492/image.png)

New v3 design:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzQxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c305b4df0c65dfc397873d2566a5afc145b725a/image.png)

---
## Tasks
- [x] Locate the v3 design in the codebase
- [x] Apply the v3 design to our forms

## Acceptance Criteria
- [x] Form navigation has been updated to use the v3 design

**Comment by oddball-lindsay** [comment]
The v3 design system is located in `src/platform/forms-system/src/js/components/FormNav.jsx`

>  const v3SegmentedProgressBar = formConfig?.v3SegmentedProgressBar;
>   // show progress-bar and stepText only if hideFormNavProgress is falsy.
>   return (
>     <div>
>       {!hideFormNavProgress && (
>         <va-segmented-progress-bar
>           total={chaptersLengthDisplay}
>           current={currentChapterDisplay}
>           uswds={v3SegmentedProgressBar}
>           heading-text={chapterName ?? ''} // functionality only available for v3
>           {...(v3SegmentedProgressBar ? { 'header-level': '2' } : {})}
>         />
>       )}
>       {!v3SegmentedProgressBar &&
>         !hideFormNavProgress && (
>           <div className="schemaform-chapter-progress">
>             <div className="nav-header nav-header-schemaform">
>               {showHeader ? (
>                 <h2
>                   id="nav-form-header"
>                   data-testid="navFormHeader"
>                   className="vads-u-font-size--h4"
>                 >
>                   {stepText}
>                   {inProgressMessage}
>                 </h2>
>               ) : (
>                 <div data-testid="navFormDiv" className="vads-u-font-size--h4">
>                   {stepText}
>                   {inProgressMessage}
>                 </div>
>               )}
>             </div>
>           </div>
>         )}
>     </div>
>   );

A few other forms are also using this v3 design:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/142453186/1cf9a5f2-3af8-4292-8d2e-225c2ee6a08b)

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-website/pull/26178
