### ISSUE TITLE
Notifications for VFS Roster Additions

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#67612]
## Description 
Each time a user needs to be added to the VFS roster, we should be notified. This will ensure we don't lose track of tickets. 
---

## Definition of Done
Complete tasks below.

---

## Tasks 

- [x] Identify a way for the Platform Support Team to be notified when they need to add someone to the VFS roster
- [x] Set up a follow up call to discuss with Shira, Alyssa, and any other necessary parties 
- [x] Create a ticket for the work necessary to implement the best practice and make sure to add "Add to Documentation" as a task in the ticket 

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Pending if we are using the new VA structure in DataDog or continuing with VFS Roster/Atlas App.

**Comment by alyssagallion** [comment]
@bdech It seems we can use GitHub actions to notify ourselves in our Slack channel when a new VFS roster ticket comes our way. Shira noted she can help if we need it, they have done this before!

**Comment by bdech** [comment]
I was approaching this attempting to create a GitHub Action, but ran into so many issues. Rebecca had pointed out that I could use something like GitHub integrations to achieve this task.

Considering I don't have admin permissions to modify or post in #platform-infrastructure-alerts, I decided to create our own channel for these notifications. Here is the new channel I created. https://dsva.slack.com/archives/C06CY71PCAX

I think creating a separate channel for this is a good idea as it will separate our notifications from general infrastructure notifications. Help reduce noise in the other channel as well

**Comment by bdech** [comment]
Had a discussion with Clint regarding having these notifications post to vfs-platform-support. His thought process is to avoid having these notifications post in the support channel. A couple reasons such as it creates a bunch of unnecessary noise. Also, the notifications are only utilized by our team, and should be kept out of the platform support channel.

**Comment by bdech** [comment]
ticket for this work. https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/73221

**Comment by bdech** [comment]
A suggestion was made to have these notifications post to the vfs-platform-support channel. I had a discussion with Clint about this topic. He suggested we send the notifications to the channel that was created for a couple reasons. First, we don't want to introduce more noise into the channel. Second, the purpose of the notifications only serve our team.
