### ISSUE TITLE
Broken form link on Presidential Memorial Certificates page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#6761]
## User Story or Problem Statement
As a Veteran's family member, I need to be able to download Form 40-0427 so I can apply for a Presidential Memorial Certificate.

This link on the [Presidential Memorial Certificates](https://www.va.gov/burials-memorials/memorial-items/presidential-memorial-certificates/) page is not currently working.![Screen Shot 2020-03-11 at 10.58.55 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/eb458f5c-04ec-4f5c-a14f-40d5a2f0d90d)

## Goal
The link to Form 40-0427 in the "By Mail" section works.

---
## Tasks
- [ ]  Update link

## Acceptance Criteria
- [ ]  Link working on live site
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
This form link was updated. Moving to validate and will close when live after deploy.

**Comment by RLHecht** [comment]
This is now live on the site. closing ticket. FYSA @AkucherGCIO @jenniferlee-dsva
