### ISSUE TITLE
Identify the Best Practice for Granting Vets.gov-write Access

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#67613]
## Description 
Each time a user needs to be added to the VFS roster, we should make sure they have proper access to Vets.gov-write access. We need to outline the requirements for getting access to Vets.gov-write (i.e. SOCKS access, etc.)

### _Note: This ticket is aimed to improve the process moving forward. The time sensitive items have been placed in [this ticket](https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/68417) to expedite the transition from Governance/Analytics to the Platform Support Team._
---

## Definition of Done
Complete tasks below.

---

## Tasks 

- [x] Discuss potential options with Shira, Alyssa and Bill (follow up with Shira if we have not heard back from her by 10/26)
- [x] Outline the steps in documentation in the Platform Support space in Confluence here: https://vfs.atlassian.net/wiki/spaces/PTST/pages/edit-v2/2798846283?draftShareId=677684af-f143-4ba8-a989-57ba5982d174
- [x] Send to Alyssa/Shira to review the Confluence doc
- [x] Alyssa to announce in proper communication channels/slide decks, etc.

---

**Comment by alyssagallion** [comment]
Alyssa to break out into two tickets (one for owning the transition and one for vets.gov-write access requirements).

**Comment by alyssagallion** [comment]
Followed up with @shiragoodman since Brandon is out of office today and tomorrow.

**Comment by alyssagallion** [comment]
Content has been added here: https://vfs.atlassian.net/wiki/spaces/PTST/pages/2860384263/Granting+Vets.gov-write+Access

**Comment by alyssagallion** [comment]
Work complete. Closing.
