### ISSUE TITLE
[FSR] Dependent definition update

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#67622]
## Description

The dependent definition must be updated to remove the financial language and update the spouse definition. 

[Depedents Count Page](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1UyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--44c1ca3319d689f731ee656bbe7d5181db5c2a89/Screenshot%202023-10-13%20at%203.17.43%20PM.png)

[Depdendents Input Page](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1kyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e20a563f9ff153f522267ca8836da20d510f48bd/Screenshot%202023-10-13%20at%203.17.54%20PM.png)

## Tasks
- [x] Update additional info components on dependent count and dependent input pages
- [x] Add updated hint text to both pages

## Acceptance criteria

- [x] Additional info and hint text has been updated and added to both pages.

## Testing
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by mgleo** [comment]
@amponce @josephrlee @HeatherRienks @Tom-Davis @denisecoveyduc 
We need to note when this is live on production to track whether an increased amount of users are including their spouse on the dependent section.

**Comment by josephrlee** [comment]
@mgleo, this should go live this afternoon! I'll confirm when it's merged!

**Comment by josephrlee** [comment]
@mgleo just merged it! Changes should be live in production this afternoon!
