### ISSUE TITLE
Salesforce Redesign - Requirements 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#67629]
## Issue Description
_Determine all requirements for Salesforce VRM redesign 

---
## Tasks
- [ ] _Collaborate with VEO and Salesforce development and other stakeholders to determine functional requirements for redesign
- [ ] _Collaborate with VEO and Salesforce development and other stakeholders to determine nonfunctional requirements for redesign 
- [ ] Prioritize stakeholders feature functionality 
- [ ] Create user stories 
- [ ] Create Use cases
- [ ] Create features list (customer, developer, quality, security) 
- [ ] Create workflow 
- [ ] Develop prototype designs 
- [ ] Estimate time to completion

## Acceptance Criteria
- [ ] _Target development start date 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
