### ISSUE TITLE
Salesforce Redesign Product Messaging 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#67630]
## Issue Description
_Create product messaging and training materials for Salesforce redesign

---
## Tasks
- [ ] Create training materials
- [ ] Create product messaging
- [ ] Develop internal training schedule 
- [ ] Develop external training schedule

## Acceptance Criteria
- [ ] Complete training documents
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

- [ ] - [ ]
