### ISSUE TITLE
NOD | Redirect Veterans to new v2 questions

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#67645]
## Value Statement

**_As a_** Veteran
**_I want to_** get redirected to the new NOD v2 questions
**_So that_** I can extend and see my older conditions when I already have a save-in-progress

---
## Background Context

To ensure that Veterans that got stuck my the infinite loop bug are able to see that new v2 questions are available, we will redirect Veterans with an existing save-in-progress back to the extension request question. This ensures that Veterans can take advantage of the new questions and seeing contestable issues more than a year in the past

## Tasks

- [ ] Use NOD v2 feature flag AND form migrations to check if a save-in-progress (SiP) exists
- [ ] If the SiP is on or past the contestable issues page, redirect to request extension page
- [ ] If the SiP is on or before the filing deadlines page, do not redirect
- [ ] Add an alert message after a redirect has occurred, so the Veteran knows why they are on a different page
- [ ] Add unit tests

## Acceptance Criteria

- [x] If a user is returning to a save-in-progress form from the SIP widget AND is past the contestable issues page before the new version is released, they are prompted to go to the new "request an extension" page
- [x] If a user is returning to a save-in-progress form from the SIP widget AND is before the filing deadlines page before the new version is released, they are not prompted to go to the new "request an extension" page
- [x] User sees an alert notifying them to view the "request an extension" page
- [x] SIP data is not lost when the new pages are introduced

# Design & Build Notes
- [Slim notification alert](https://www.sketch.com/s/0424c51d-7818-43ea-8821-6de91eb7ab27/a/JAWb2a5)

## Definition of Ready 
- [ ] Needed changes identified

## Definition of Done
- [ ] Acceptance criteria met
- [ ] Redirect successfully tested in staging

**Comment by eileen-coforma** [comment]
Added design file for slim notification alert.

**Comment by eileen-coforma** [comment]
Separated out bug found into another ticket #67795. We should retest this along with that when that bug fix is merged.

**Comment by saderagsdale** [comment]
@eileen-coforma @Mottie Crisped up the AC

**Comment by saderagsdale** [comment]
The method we're using to check the feature flag isn't reliable - it's also why the link from my-va doesn't work.

**Comment by Mottie** [comment]
This work is ready for validation. I've set up these 3 mock users to have a save-in-progress to return to the contestable issues page while the feature flag was disabled:
- vetsgov+test233@id.me
- vetsgov+test234@id.me
- ~vetsgov+test235@id.me~ skipped; was asking for ID upload while verifying
- vetsgov+test236@id.me

To preserve this state until testing is done, don't modify any form fields or use the "Finish this application later" link.
