### ISSUE TITLE
[Development] HLR: Work with LightHouse Team on Initial JSON Schema for Validation Support

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#6764]
## User Story or Problem Statement
As a veteran, I need to be able to file HLR through VA.gov so I can get access to the updated decision review process.

Problem description: We need a JSON schema to support the validations we are losing by no longer hitting Caseflow.  We will work with Ed from LH team on this.  The prework done by @SMLuthi for the front end is apparently the starting point.

## Goal
JSON schema takes into account missing validations (need more detail here, please Ed/Silvio add it)

## Tasks
- [ ] JSON schema

## Acceptance Criteria
- [x] LightHouse accepts the work
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by SMLuthi** [comment]
The json schema changes have been finalized and merged in. All that is left to do is write ticket(s) that will make changes on the vets-api side for adopting the schema changes that were made.
