### ISSUE TITLE
[task] DR | Document interactions between frontend and vets-api backend

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#67648]
## Value Statement

**_As a_** product team member
**_I want to_** see all of the different front/backend interactions and results
**_So that_** I can easily reference decisions made and error messages for each interaction

---
## Background Context

Kyle started a list of front/backend interactions, redirects, and screenshots of error messages for Supplemental Claims. We need to organize it into a table for easier referencing & duplicate for the other two decision review forms.

## Tasks
- [ ] Organize data for SC into scannable table
- [ ] Duplicate and differentiate for NOD and HLR

## Acceptance Criteria
- [ ] All tasks complete and URLs listed

## Documentation
- SC: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/engineering/SC_frontend_backend_interactions.md
- NOD: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/engineering/NOD_frontend_backend_interactions.md
- HLR: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/higher-level-review/engineering/HLR_frontend_backend_interactions.md

## Definition of Ready 
- [x] Kyle & Eileen touch base and hand-off complete

## Definition of Done
- [ ] Acceptance criteria met
- [ ] Developers can understand documentation

**Comment by saderagsdale** [comment]
Note from DK: Add design component to the documentation.

**Comment by saderagsdale** [comment]
@eileen-coforma Can you add an update to the comments in this ticket so we know next steps?

**Comment by eileen-coforma** [comment]
@saderagsdale @data-doge
I've drafted MD pages for each product, with the initial tables set up, and filled out as much as I could.

**Next steps**
- Double-check that these are the right list of interactions
- Fill in any missing information (currently a -)
- Identify the specific errors that occur in these interactions (currently grouped in label as 'Any other')
- Identify whether there are errors we convert ourselves in to trigger message (ie. 500 > 400)

Eugene, let me know when you and @anniebtran have a time to chat to kick-off, or we can use today's parking lot.

**Comment by saderagsdale** [comment]
Asked Michael Hobson if they have any data flow or sequence diagrams. Waiting to hear back.

**Comment by eileen-coforma** [comment]
There seemed to be a mismatched error message for #65839 . Remember to investigate to see where it triggers and if we can consolidate.

**Comment by anniebtran** [comment]
Updates for NOD documentation (so far, I'll continue to update as needed):

- [Prefill Veteran Information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/engineering/NOD_frontend_backend_interactions.md#prefill-veteran-information) and [Prefill Veteran Contact Information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/engineering/NOD_frontend_backend_interactions.md#prefill-veteran-contact-information) — No changes as of now, circling back to this because it's a little trickier to trigger errors for these ones

- [Get Contestable Issues](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/engineering/NOD_frontend_backend_interactions.md#get-contestable-issues) — I specifically tried 404, 502, 403, 504 and got the same "Can't load issues right now" message as is currently documented, and I would assume other error codes would lead to the same messaging as well. User needs to manually enter an issue before they can proceed and submit the form

- [Evidence Upload (before submission)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/engineering/NOD_frontend_backend_interactions.md#evidence-upload-before-submission) — This one can be pretty varied depending on the error. You can find some of the frontend logic for error handling [here](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/actions.js#L214-L389) and [here](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/validation.js#L569-L584)


  If it's an error raised on the backend that has some kind of messaging of its own attached to it and it's structured in a specific way, the frontend will display that. An example error that I manually raised inside of the existing code displayed this to the user:
  
  <img width="653" alt="Screenshot 2023-11-13 at 4 06 49 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14334046/e419a46c-d48d-46bc-9c49-b51c675183f0">

  If it doesn't come with its own messaging, it will display this no matter what the error code is:
  <img width="593" alt="Screenshot 2023-11-13 at 12 04 10 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14334046/f0cf3e0c-0ea5-4111-8bdc-48006ee5ebbf">
  Something I noticed is if there's an error, if doesn't remove it, logs out, and returns to the upload page with the previously loaded file, it will display the error again. Not sure if that's expected behavior or not but thought I'd call it out.

- [Overall Board Appeal Submission](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/engineering/NOD_frontend_backend_interactions.md#overall-board-appeal-submission) — This one was a little off too. I wasn't able to get the 403 error noted in the table to display. The one that's in the table seems to, codewise at least, [only exist in Supplemental Claims](https://github.com/search?q=repo%3Adepartment-of-veterans-affairs%2Fvets-website%20Your%20decision%20review%20request%20didn%E2%80%99t%20go%20through&type=code) (specifically [here](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/appeals/995/content/submissionError.jsx#L37)), but the following is what I saw when I triggered a 403 Forbidden error on submission:
  <img width="841" alt="Screenshot 2023-11-13 at 4 41 15 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14334046/4d884d95-4f86-4e16-ae7b-e348bf800b38">
  Also haven't been able to trigger the other error yet, but I can keep digging into that one. Generally an error here will result in the submission not going through and the user will need to try again somehow/sometime depending on what the issue is. 

- [Evidence Uploads (after submission)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/engineering/NOD_frontend_backend_interactions.md#evidence-uploads-after-submission) — If it's an asynchronous job, we probably won't be able to do error handling with the way that the app is currently structured.

- [Save In Progress](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/engineering/NOD_frontend_backend_interactions.md#save-in-progress) — A few updates here:
  - On the veteran details page, if there's an error returned (e.g. `403`, `404`, `401`, `504`) from a `GET` request to the `InProgressForms` controller, then that's where we will see the missing "last 4" info (e.g. last 4 SSN). This does *not* block submission if the user finishes the form in one go.
  - As the user progresses through the form, if they run into a `400`, `504`, `403`, `404`, `401`, etc. error, they'll see the generic error message that warns them that they can continue but the data won't be automatically saved:
    <img width="707" alt="Screenshot 2023-11-02 at 3 26 28 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14334046/85b993f5-9983-471f-9c10-7e803c0f1021">
      - The error will continue to persist on subsequent pages (I assume it'll disappear once the request returns a `200 OK` response code, but hard to test given the dev setup)
      - This issue doesn't block submission, but obviously the data isn't getting saved automatically so they'll have to fill things in all over again if they don't submit the form during this session
      - The "Finish this request later" button updates the error message to be:
        <img width="668" alt="Screenshot 2023-11-03 at 3 08 29 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14334046/d4543049-46bc-48cd-8221-108726af6995">

**Comment by saderagsdale** [comment]
Heather scheduling time for the team to connect.

**Comment by eileen-coforma** [comment]
**Action items:**
- Robin: Backlog ticket to update error messaging for submission error to match NOD and HLR to SC.
- Eileen: Update Pre-fill sections with error message that’s triggered in introduction.
- Annie: Check historical error codes in Datadog to see if there’s missing. Continue to check error messaging for SC and HLR.
- Sade: Ask Lighthouse about error codes related to evidence upload.

**Comment by saderagsdale** [comment]
@anniebtran Noodle on ticket for investigation of our backend

**Comment by anniebtran** [comment]
Updates for SC documentation:

[Prefill Veteran Information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/engineering/SC_frontend_backend_interactions.md#prefill-veteran-information) — no changes here

[Prefill Veteran Contact Information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/engineering/SC_frontend_backend_interactions.md#prefill-veteran-contact-information) — I did some hacky things to get this to happen, so I'm not entirely sure how plausible the actual error I triggered is, but here are the steps to locally recreate what I did:
- Update [this line](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/components/ContactInfo.jsx#L83) in vets-website to have `!environment.isLocalhost()` so that we don't always return mock data no matter what the status of the API call is
- Add a `raise` to [this method](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/va_profile_redis/contact_information.rb#L56) in vets-api to simulate an error
- Sign in as a user
  - You should see this in the Redux store if you have the dev tools open: 
    <img width="304" alt="Screenshot 2023-11-28 at 2 51 05 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14334046/9114c59b-83f5-473d-9f67-3c500feeed2c">
- Start the supplemental claims form and get to the contact info page:
  - This is what you will see:
     <img width="719" alt="Screenshot 2023-11-28 at 2 31 46 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14334046/3a15a8c3-4879-4453-be26-a5a4af2d6f1f">
  - If you try to continue:
    <img width="604" alt="Screenshot 2023-11-28 at 2 52 57 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14334046/43a745e6-bbaa-4914-bb6d-f0ddc5861076">
  - Can't even edit the fields as the message instructs:
     <img width="757" alt="Screenshot 2023-11-28 at 2 32 05 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14334046/3f3a7b3e-2eb6-412d-a500-102391c605bf">
     
[Get Contestable Issues](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/engineering/NOD_frontend_backend_interactions.md#get-contestable-issues) — 

[Evidence Upload (before submission)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/engineering/NOD_frontend_backend_interactions.md#evidence-upload-before-submission) —

**Comment by anniebtran** [comment]
### Updates for HLR documentation (still working on adding to this):

[Start Higher Level Review Form](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/higher-level-review/engineering/HLR_frontend_backend_interactions.md#start-higher-level-review-form) —

[Prefill Veteran Information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/engineering/SC_frontend_backend_interactions.md#prefill-veteran-information) — 

[Prefill Veteran Contact Information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/engineering/SC_frontend_backend_interactions.md#prefill-veteran-contact-information) — 
     
[Get Contestable Issues](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/engineering/SC_frontend_backend_interactions.md#get-contestable-issues) — 

**QUESTION**: I haven't looked at HLR yet, but does HLR even have evidence uploads? I thought it was the only one that didn't 🥴 
[Evidence Upload (before submission)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/higher-level-review/engineering/HLR_frontend_backend_interactions.md#evidence-upload-before-submission) — 

[Overall Higher Level Review Submission](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/higher-level-review/engineering/HLR_frontend_backend_interactions.md#overall-higher-level-review-submission) —

[Save in Progress](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/higher-level-review/engineering/HLR_frontend_backend_interactions.md#save-in-progress) —

**Comment by eileen-coforma** [comment]
@anniebtran 

You are correct. HLR does not do evidence uploads.

**Comment by saderagsdale** [comment]
Hope to have done today.

**Comment by Mottie** [comment]
Updated documentation is ready for review:

- [List of Supplemental Claims Frontend/Backend Interactions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/engineering/SC_frontend_backend_interactions.md)
- [List of Notice of Disagreement Frontend/Backend Interactions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/engineering/NOD_frontend_backend_interactions.md)
- [List of Higher-Level Review Frontend/Backend Interactions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/higher-level-review/engineering/HLR_frontend_backend_interactions.md)

**Comment by saderagsdale** [comment]
@saderagsdale add doc links to main product page.
