### ISSUE TITLE
Platform Support Taking On Zenhub Access Process 

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#67655]
## Description 
This ticket will outline the tasks needed to port over the responsibility of granting Zenhub Access to anyone who needs it. That being said, we will _not_ be owning Zenhub troubleshooting.

---

## Definition of Done
All tasks below are completed.

---

## Tasks 

- [ ] Outline the current process for granting access including any pre-requisites required to get it
- [ ] Identify any external documents that need to be updated (i.e. pages on the Platform Site)
- [ ] Add the list of documents to update as tasks below 
- [ ] Identify any internal documents that need to be updated (i.e. Confluence pages for the Platform Support Team)
- [ ] Add the list of documents to update as tasks below 
- [ ] Alyssa to communicate to Team of Teams
- [ ] Alyssa to communicate to #vfs-change-announcements
- [ ] Alyssa to communicate in Platform Demo

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by EWashb** [comment]
Update: work on this is currently blocked as we look into funding for our enterprise. I am working with Josh C and the TAC to get this funded before the 12/31/23 end date.

**Comment by alyssagallion** [comment]
No longer applicable. Zenhub is going away. Closing!

CC: @EWashb

**Comment by EWashb** [comment]
@alyssagallion zenhub isn't going away. We will have it for another year. Funding was approved.
