### ISSUE TITLE
Add New Tasks to the Tier 1 Support Ticket Template to Communicate to Relevant Parties

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#67653]
## Description 
Please add the below task to the Tier 1 template to ensure we are always communicating updates!

- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)

---

## Definition of Done
All tasks below are complete

---

## Tasks 

- [x] Add the two above tasks to the template.

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by lindsay-insco** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTFyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--56b27a403c1b0988665e97fde3d8c3b60ae8f52b/Screenshot%202023-10-24%20at%2010.35.40%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTVyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ad78f52fdbc93ccdad7a0b52959aced8ea60159/Screenshot%202023-10-24%20at%2010.35.33%20PM.png)
Template will now always add these 2 items to the task list!!
