### ISSUE TITLE
Finish eQIP Submission

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#67651]
### Description:
All team members are required to submit their eQIP details to ensure a seamless onboarding process and gain necessary permissions and access. Completing this promptly is essential to ensuring all team members have the tools and permissions needed for their roles.

---

### Task:

- [ ] Log into the eQIP system.
- [ ] Review all sections for accuracy and completeness.
- [ ] Ensure that all required documents have been uploaded.
- [ ] Submit the eQIP for review.
- [ ] Modify based on any feedback/requests you receive
- [ ] Confirm submission with the HR or onboarding team.

### Acceptance Criteria:
- [ ] All eQIP sections are filled out completely.
- [ ] Required documents are attached and uploaded.
- [ ] eQIP has been successfully submitted
- [ ] An email or notification confirming the submission has been received
