### ISSUE TITLE
Update Spotlight links on MHV landing page

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#67658]
## User story

As a user visiting the MHV landing page, I want to see the most up-to-date links in the Spotlight list, so that I can access relevant and new information and have an impression that the landing page is being kept fresh.

## Details

From Rebekah Putera:
* [Pain? Try yoga](https://www.myhealth.va.gov/mhv-portal-web/ss20211012-pain-yoga-may-help)
* [Where are my labs and test results?](https://www.myhealth.va.gov/mhv-portal-web/ss20180716-where-are-va-lab-test-results)
* [Heart health with diabetes](https://www.myhealth.va.gov/mhv-portal-web/ss20220415-diabetes-and-a-healthy-heart)

## Tasks 
- Implementation of updated links @carlosfelix2 
- Capturing the current process for how these links are governed @sterkenburgsara 

## Related artifacts
- [GH file capturing the current state process for link governance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/link-governance.md)

## Acceptance criteria

- [ ] Design has been consulted on link display
- [ ] Spotlight links on MHV landing page are updated to the list above
- [x] Process/flow for these links is documented: people, system(s), governance/intentions around frequency

**Comment by wesrowe** [comment]
@dcloud has some context to provide.

**Comment by sterkenburgsara** [comment]
@wesrowe Do you have thoughts on my pulling out the spotlight link governance process into a separate ticket? It feels tangential but unrelated to the implementation of these updates to me, but curious to get your thoughts.

**Comment by wesrowe** [comment]
@sterkenburgsara, is it clear that we're just trying to capture _existing_ process/governance? I got the sense from you in standup that you might think this meant changing/designing governance. I could be wrong on both points...

**Comment by sterkenburgsara** [comment]
@wesrowe got it - thanks! Updated this ticket with a link to .md file that captures the existing process.

**Comment by sterkenburgsara** [comment]
@wesrowe admittedly, I have not thought about that yet! I thought I'd reconfigure once we had something to move toward that complicates or challenges this structure?

I can take a stab at more headings / less nested bullets, but if you have edits please feel free to jump in!
