### ISSUE TITLE
Add Link to apply online to 530 Find a Form Tool

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#67665]
## Issue Description
_The existing ["Find a Form" page for 530EZ](https://www.va.gov/find-forms/about-form-21p-530ez/) is missing the apply online option. This link should be added AFTER the burial form is updated. This might be a CAIA task._

See [527EZ page](https://www.va.gov/find-forms/about-form-21p-527ez/) for an example.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3c4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fff502e61626d5a23cb8f079a974e6563bc15296/image.png)

---
## Tasks
- [ ] Determine which team is responsible for adding the "go to the online tool" link.
- [ ] Assign work as appropriate.
- [ ] Follow-up to ensure link is added.

## Acceptance Criteria
- [ ] The "go to the online tool" link appears on the ["Find a Form" page for 530EZ](https://www.va.gov/find-forms/about-form-21p-530ez-0/)
---

**Comment by steele-lm** [comment]
@fiorella-io Flagging this old burial ticket as well. I think Julie S flagged this before we started the redesign.

**Comment by fiorella-io** [comment]
@steele-lm That link didn't work. This is the new [About form 530 link.](https://www.va.gov/find-forms/about-form-21p-530ez/). It looks like we need to add a link to the online form. The example in the ticket does not have an online link to the form. Anyhow, this has to be a CAIA content request. We can't update that page.

**Comment by steele-lm** [comment]
@fiorella-io Thanks! I updated the about form link in the body of the ticket.

**Comment by steele-lm** [comment]
@aliyahblackmore I wanted to flag this for you/CAIA as a post-launch update that's needed to a static page. What is the best way to move this ticket into CAIA's backlog?

**Comment by aliyahblackmore** [comment]
Thanks @steele-lm. I'll check in with our PM about what's best here. And I'll add this item to my content ticket for the other static page updates.
