### ISSUE TITLE
Discovery spike: High-level user types for MHV landing page

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#67679]
### User story

As a Cartographers team member, I want to _begin_ to systematically understand the various types of users who visit the MHV National Portal and/or MHV on VAgov and what characteristics define them, so that I can more effectively prioritize, design and build functionality for them.

### Related artifacts
[Link to word doc](https://docs.google.com/document/d/1RqBUNmtjbynDTWpSsNyECX2_eN0bGp0SL3c_YLwSzto/edit)
[Possible user type data fields - Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1699380640123/50db0eabbcc3e40bb9bee48d20c3d1ee763f3816?sender=uf94a77a19aaf687331c09367)

### Notes

- This ticket has been modified to be a first pass at the problem, rather than a full analysis; the team will iterate on the output over time
- The stopping point for this initial exploration is: identifying key defining characteristics that are:
  - Significant from the user's p.o.v., e.g., impacting their UX journey or context
  - Impactful on the data available to the landing page
  - ...?

## Acceptance criteria

- Documented for future analysis the various types of users who can visit the MHV landing page or will in the future, and the the real-life use cases that differentiate them
- Prioritized the "key" user types which are most useful as an input to other work in this sprint

---
## Tasks
- [ ] Ticketed any further discovery story(s) that are identified as useful to iterate on this story's outcomes [team+Wes]
- [ ] Helping to determine what datapoints are available for a User/Veteran, allowing categorization [@radavis]
- [ ] [documenting data points for user segmentation based on feasibility](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/analytics-user-segmentation.md) (value x level of effort) [@sterkenburgsara and @jzucadi]

**Comment by AngelaFowler82** [comment]
I created this document to start the process of documenting user types.
https://docs.google.com/document/d/1RqBUNmtjbynDTWpSsNyECX2_eN0bGp0SL3c_YLwSzto/edit

**Comment by sterkenburgsara** [comment]
@radavis @jzucadi Can you explore data segmentation in GA & Datadog by whether users are a Veteran or Non-Veteran? Based on documentation [in this spreadsheet](https://dvagov.sharepoint.com/:x:/r/sites/HealthApartment/Shared%20Documents/MHV%20on%20VA.gov/health-portal-access-user-scenarios.xlsx?d=w81d81c6a8228455d9cf4385ed6bb4822&csf=1&web=1&e=W9MaIO) (requires VA Network access to view) it looks like Lighthouse has API w/ a binary field "is Veteran?" Y/N

**Comment by radavis** [comment]
If we want to know if a user is, or is not, a Veteran, this information is populated in redux state on the front-end after sign in. `user.profile.veteranStatus.isVeteran`. 

We would then need include this data in the data that is sent to analytics.

**Comment by wesrowe** [comment]
@radavis, do you already have an idea of how to get demographic user data into GA in a way that we could leverage for user-type segmentation? I wrote a ticket for the future about getting something like that in place, but I don't have any idea yet about what it really means.

**Comment by radavis** [comment]
> do you already have an idea of how to get demographic user data into GA...

Yes, `recordEvent` would allow us to send this information along. 

> ... in a way that we could leverage for user-type segmentation?

No. I would need to experiment with GA, `recordEvent`, and writing queries to extract this information from GA.

**Comment by wesrowe** [comment]
Thanks. FYSA, here's the future ticket that covers that deeper dive into mapping user data into GA: https://github.com/department-of-veterans-affairs/va.gov-team/issues/69696.

**Comment by LynneJohnson224** [comment]
Will create a follow on story that addresses application of user types to the MHV tools and exposes documentation on GitHub.
