### ISSUE TITLE
Implement landing page for user without a facility registration

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#67673]
## User story

As a user who has no record of being registered at a VAMC, who is authenticated in VA.gov and has landed on VA.gov/my-health, I want to understand why I cannot access the my-health page so that I can take appropriate actions.

Follow-on ticket for #67089.

## Acceptance criteria

- User who has no record of being registered at a VAMC, who is authenticated in VA.gov and has landed on VA.gov/my-health, sees the solution from #67089
- 

## Tasks

- [x] Assist with unit/e2e test creation and code review @radavis
- [x] [Create CAIA request ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68294) @fmccaf1
- [x] Attend health content office hours this Thursday 10/26 @fmccaf1 @jonathanjnelson 
- [x] Evaluate whether it makes sense to include additional content links (3 columns) on page for users who cannot see or use health tools @sterkenburgsara 
- [x] Update w/ content suggestions and [update CAIA ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68294) @fmccaf1

**Comment by wesrowe** [comment]
note from refinement:
- a form for creating an MHV account was unexpectedly uncovered in the current flow for this category of user. Wes to schedule a meeting to discuss implications.

**Comment by fmccaf1** [comment]
During content office hours today, Laura Wilworth recommended we use a similar style to: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk4yQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--40a86744e69acf5ebd748f2c272aee6109c4e0e7/image.png)

**Comment by fmccaf1** [comment]
Thanks @carlosfelix2 ! If you have any questions or feedback to share, let me know :) 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjEzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e6f93f987f8e0432ed3f3d6e7a2cc36e6e5a2dd1/VA-MHV-Home-LP%20no%20HR%20Copy.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjUzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc9237f6305bd17179739746fcb9947518ec8a9a/VA-MHV-Home-Mobile.png)

**Comment by fmccaf1** [comment]
[Feedback from CAIA on content](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68294) asks us to offer untrue info to user (in a way that I don't think is helpful...).

**Comment by sterkenburgsara** [comment]
Update on 3 columns of links: I am not sure it's helpful to have these here, but CAIA and our team feel there is almost no risk to keeping these links exposed. Shipping the design with those intact feels like the best choice for the MVP iteration of this page. We should monitor clicks and iterate on this over time.

**Comment by fmccaf1** [comment]
Yet again, the final (fingers crossed) design:

![VA-MHV-Home-LP no HR Copy](https://github.com/department-of-veterans-affairs/va.gov-team/assets/106624475/a5ea248e-1937-46f0-bcad-d36e504518c0)

**Comment by fmccaf1** [comment]
Hi @carlosfelix2 sorry to ruin your life with yet another content change. This comes from CAIA and changes are pretty small; I think this is the last of changes at least for this sprint, but likely also beyond this sprint. [Here's the CAIA ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68294#issuecomment-1788029255) in case grabbing the text from there is easier on you.

![VA-MHV-Home-LP no HR Copy](https://github.com/department-of-veterans-affairs/va.gov-team/assets/106624475/a08431d2-0656-4a41-a8c3-0e6b17b9da58)
