### ISSUE TITLE
Implement Download 21-22 Form Page

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#67678]
## Issue Description
After a user completes their 21-22 form fill, they will be presented with a link to download the form with instructions around next steps.

Here is the design [for the final download page](https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/v/gyxZMd/p/3C666192-27DA-40CE-B314-BA779A8C8BD4/canvas?posX=-36734.71598889581&posY=-1254.1241884404014&zoom=0.3474983870983124).

There are some links on the page to consider:
1. [Upload to VA.gov Claim Status Tool](https://www.va.gov/claim-or-appeal-status/)
2. [Upload to Access VA Quick Submit Tool](https://eauth.va.gov/accessva/?cspSelectFor=quicksubmit)
3. [Review your form status on MyVA](http://va.gov/my-va)
4. [Go back to VA.gov](https://www.va.gov/)

---
## Tasks
- [ ] Create the download page based on the design linked above.
- [ ] Ensure the document generated by the download link is accessible (i.e. intelligible and navigable for screen reader users)
- [ ] Ensure the downloaded document does not open in a browser
- [ ] Include links as specified above
- [ ] Confirm the user interface mirrors design expectations.

## Acceptance Criteria
- [ ] A download page is created to match the design linked above
