### ISSUE TITLE
Identify Potential Tools to Use for a KB Support Integration

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#67674]
## Description 
Alyssa had a conversation with Erika Washburn about using a tool that would create a better KB option for both VFS engineers and our Platform Teams. In the future we'd like to use Zendesk KB/Support integration but it is not budgeted. Alyssa will investigate options provided on the Va.Gov marketplace: https://digital.va.gov/marketplace/?redirect=1

---

## Definition of Done
Complete all tasks below.

---

## Tasks 

- [ ] Review tool options 
- [ ] Outline benefits of each and document in Confluence
- [ ] Present to PO

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Working with @johnny-jesensky-adhoc on creating an integrated solution. Pending future conversations.

**Comment by jknipes** [comment]
Mural board will inform this work

**Comment by alyssagallion** [comment]
We are only owning support and content deployment (checking links and deploying each day). Closing.
