### ISSUE TITLE
Copy of [Project] Title of the work (Due date if requested)

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#67690]
## Description

Enter a detailed description of the work - gherkin syntax below is acceptable.

Scenario: In common language describe the work or issue

Given: (The beginning state of the scenario)
When: (Specific action that the user takes)
Then: (Testable outcome that can be captured in the testing section, usually caused by the action in When)

## Tasks
- [ ] Task one to complete the work in the description
- [ ] Task two to complete the work in the description
- [ ] Task three to complete the work in the description

## Acceptance criteria

- [ ] Item one from the description performs as described in the description
- [ ] Item two from the description performs as described in the description

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>
