### ISSUE TITLE
Allow Applications to have Oncall

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#6770]
## User Story or Problem Statement
As of right now, we don't have a way to allow application teams to have oncall. In order to follow the self-service and empowering teams to own their work, we need to give them the ability to have oncall so they can respond to incidents on their application.

Ref: https://dsva.slack.com/archives/CBU0KDSB1/p1583185436362100
Ref: https://dsva.slack.com/archives/CJYRZK2HH/p1583191642174500 

ref example: https://dsva.slack.com/archives/CBU0KDSB1/p1595969497216100

## Goal
_Have a model for App teams to have their own oncall_

## Acceptance Criteria
- [ ] _??_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ricetj** [comment]
May need to make into an epic.

**Comment by ricetj** [comment]
We will need GH teams process in place before we can do this.

**Comment by jhouse-solvd** [comment]
@dginther - can you verify that this capability now exists for application teams?

**Comment by jhouse-solvd** [comment]
This can be marked as done. Relevant ticket regarding oncall team structure can be found here: 

https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/14994
