### ISSUE TITLE
Retry Claims that Fail Central Mail

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#67710]
## Issue Description
_Once the submission API is moved to LightHouse, the claims that failed the backup submission process need to be retried to see if they are successful or if additional mitigation measures are necessary._

Claim IDs
2023-10-10T19:20:17.743128Z - 7867735 - Resubmitted Successfully
2023-10-14T23:11:09.082296Z - 7889911 - Missing veteran-information
2023-10-25T05:59:56.872673Z - 7941666 - Missing veteran-information
2023-10-25T09:02:59.966758Z - 7941801 - Missing veteran-information

---
## Tasks
- [ ] Retry failed claims
- [ ] Track success/failure
- [ ] If failure, document reason and next steps.

## Acceptance Criteria
- [ ] Claims are resent to Central Mail via LightHouse API
---

**Comment by evansmith** [comment]
Updating from earlier this week. The saved claim from 10/10 was re-run successfully. The saved claim from 10/14 was not able to be re-run due to missing veteran-information in its form data.

Two more issues appeared on 9/25 with similar veteran-information issues. Exploring the cause further.

**Comment by tblackwe** [comment]
@evansmith can you confirm the date on the 2 new failures with veteran info missing? Can you add the claim ids on the issues we are tracking to this ticket?

**Comment by evansmith** [comment]
@tblackwe Both new ones were on 10/25. I'll add the four claim ids into the description
