### ISSUE TITLE
Front end code ownership

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#6772]
## Problem Statement
How might we improve the PR process?

## Goal
Faster development and more autonomy

---
## Tasks
- [ ] Follow documentation: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/codeowners.md
- [ ] Create a GitHub team under the Department of Veteran Affairs GitHub organization
- [ ] Assign that team as a code owner of application folders. 
- [ ] Follow the conventions in the CODEOWNERS configuration file to assign the team to an application folder. 
- [ ] Request approval to CODEOWNERS configuration by frontend-review-group 

## Acceptance Criteria
- [ ] New GitHub teams is added to vets-website repository 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
