### ISSUE TITLE
[UX] [Design] Create content and wireframe for Review Your Travel Claim page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#67735]
## Tasks

How might we create a new page for Review Your Travel Claim page before the completion page? During eCheck-in we didn't use one because the time to complete check in is limited. [VA Form pattern](https://design.va.gov/templates/forms/review) for reference. 

It's referenced in a [Mobile App conversation at the 14 min mark](https://dsva.slack.com/archives/C04J6H2LYUU/p1697210321088529). 

- [ ] Create wireframe with content for Review Your Travel Claim page. Mobile App started this work in [Figma](https://www.figma.com/file/ZIHY63cFlD7pFjqQLA5rFN/%F0%9F%94%8D-Appointments-2.0---Working---VAMobile?type=design&node-id=1611-156&mode=design&t=BmqXwNhCjVztuobl-0), and we probably want to include the check box. I believe there is a design pattern for this in the VA library. Christina might know where it is. 
    - Take into account how this may look under LoROTA restrictions

## AC

- [ ] Review with Appointments (and Kristen)
- [ ] Review with Danielle and/or Laura

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 I went to look at the "mobile app conversation at the 14 minute mark" link, and it just opened into a chat in slack, not a recording, and it's just the team slack. I think my slack is messed up and not letting me access the right thing. Is there any way you could share it in a different format? If not, it's not a big deal, I can look at the figma file too to get up to speed. 
Thanks!

**Comment by kellysmith1008** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHhWQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--587c3d6121f650c4fa1f5b2b68f9326bc83cbc4b/image.png)
Placing this here - gives me an idea of content we can use, though we need consistency through "confirm/review" - I'll make sure to include that guidance with my content draft

**Comment by benbrasso-agile6** [comment]
Zoom video - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/demo/2023-10-11%2014.10.11%20Sprint%2081%20Demo.mp4

**Comment by kellysmith1008** [comment]
Thanks, Ben! I don't know what's going on with my slack, but I appreciate you posting it again!
@zach-park I think we can use the same content as above, but I want to get Ben's and your feedback on our guidelines for review, confirm, and verify:

When to use "review": When you're simply looking at the information but not necessarily taking any action on it.
- In this instance, I believe it's fine to use "review" in the heading

When to use "confirm": When you need to take an action to confirm something, but not necessarily provide new information.
- In this instance, I think it's fine to use "confirm" for the body text

When to use "verify": When you have to provide information, like your date of birth for identity verification.
- In this artboard, I don't feel we need to use "verify" as they aren't providing information here.

The only change I'd make is in the answer to "How you traveled" I would want to update that body text to "In your own vehicle"

Zach, do you want me to try and mock this up or can you use the image above and the content for your work? I'm happy to mock something up if it helps!

**Comment by kellysmith1008** [comment]
Placing [Mark's "I agree to these terms" conversation](https://dsva.slack.com/archives/C022AC2STBM/p1697811766776369) here for future reviewing when Ben is back

**Comment by benbrasso-agile6** [comment]
Yeah, that's the pattern that I think @cgednalske knows what other teams use for web and, therefore, what we might consider using too.

**Comment by cgednalske** [comment]
@kellysmith1008 @benbrasso-agile6  Here's the [review pattern in the design system](https://design.va.gov/templates/forms/review#example). And here's what it would look like for us ([CodePen rough structure](https://codepen.io/team/va-cie/pen/ZEVdNVo?editors=1010) - first image below). But it doesn't work so well for us because the answers in our accordions are super short.

Wondering if we can go to platform and see about using the structure we have in our demo pages, like in the second image below ([CodePen example](https://codepen.io/team/va-cie/pen/poGzRaV?editors=1000))? It's a similar structure to mobile's design (and they also started from the design system pattern) and [gov.uk's in-progress review page](https://task-list-workshop-done-1fd3e73a6a54.herokuapp.com/check-your-answers).

(Btw ignore any weird little things that might be wrong on those CodePen screens - just a quick starting point at the moment)

<img width="364" alt="Screenshot 2023-10-23 at 7 38 33 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/79372956/2e665db9-2868-4474-b686-e774dcfc7eef">

<img width="358" alt="Screenshot 2023-10-23 at 7 35 17 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/79372956/04c062aa-e94c-493e-b46c-2619e24a97c1">

**Comment by benbrasso-agile6** [comment]
Yeah, I don't think accordions are appropriate here. Let me see if I can find what some other teams are doing. The screenshot on the right is more appropriate, imo.

**Comment by benbrasso-agile6** [comment]
Weird, 1010, which is getting designed now is using accordions, wonder if there's any examples of smaller forms for our reference

https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/5A0793CD-192B-4BB9-8752-E2AF5BA24A45/canvas

**Comment by benbrasso-agile6** [comment]
Maybe drop a note into #veteran-facing-forms and also tag Matt

**Comment by benbrasso-agile6** [comment]
Guess I should look for experimental tickets real quick...

**Comment by benbrasso-agile6** [comment]
Don't see anything in experimental open/closed backlog, fyi

**Comment by cgednalske** [comment]
Agreed 💯  that the accordions wouldn't really work for us, but it would make sense to follow our demographics pattern, which is a review pattern in itself. It's very likely we're the first team to encounter this...I can't think of any other "form-like" flows that are as short as this.

Happy to help take this to platform office hours tomorrow if needed.

**Comment by benbrasso-agile6** [comment]
Yeah, which one is tomorrow, design?

**Comment by benbrasso-agile6** [comment]
Does VA Profile have a pattern of edit > review > success? Or, I think they're mostly, edit > success.

**Comment by benbrasso-agile6** [comment]
@cgednalske I'm going to sign us up for design platform hours, since you're prolly still walking the doggies and what not. I'll forward to you and Kelly.

**Comment by zach-park** [comment]
@kellysmith1008 @benbrasso-agile6 @cgednalske , here is the draft link to the wireframe: 
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/6517BA8C-BADD-478E-9380-4F59F467423F/canvas

Please let me know what you think.

**Comment by benbrasso-agile6** [comment]
Actually, the breadcrumb would probably [back to past appointments](https://www.figma.com/file/xRs9s6QWoBPRhpdYCGc3cV/User-Flow?type=whiteboard&node-id=2884-13385&t=vKwbtATQwiRwyezJ-0)

**Comment by zach-park** [comment]
@benbrasso-agile6 @kellysmith1008 @cgednalske , I updated the links in the comment above to add the default state wireframe. Thank you!

**Comment by kellysmith1008** [comment]
I responded to the Cancel button in sketch, but basically the short version is it should say "Back" instead of cancel, per Matt D. We'll need to make sure we let engineers know where "back" goes to, but yeah, past that the content is approved.

**Comment by benbrasso-agile6** [comment]
I'd close this @zach-park. Post the updated link here and then close it out.

**Comment by zach-park** [comment]
Here is the validated "Review Your Travel Claim" page:
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/MmWYmm7
