### ISSUE TITLE
[UX] [Design] Create content and wireframe for Completion page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#67736]
## Background
We need to create a completion page wireframes for the Appointments application.

How might we create a new Completion/Successful page? [VA Form pattern](https://design.va.gov/templates/forms/confirmation) for reference. 

[Appointments team design](https://www.figma.com/file/xRs9s6QWoBPRhpdYCGc3cV/User-Flow?type=whiteboard&node-id=2899-14287&t=7Kwxz3vEE13DN4YN-0), but keep in mind we need to design this through the design lens of the [Appointments Past Appointments](https://www.figma.com/file/xRs9s6QWoBPRhpdYCGc3cV/User-Flow?type=whiteboard&node-id=2884-13385&t=7Kwxz3vEE13DN4YN-0).

[Mobile App content and design](https://www.figma.com/file/ZIHY63cFlD7pFjqQLA5rFN/%F0%9F%94%8D-Appointments-2.0---Working---VAMobile?type=design&node-id=1648-11140&mode=design&t=BmqXwNhCjVztuobl-0) for reference. 

## Tasks
- [ ] Create wireframe with content for Completion/Success page for the Appointments application. 
    - Take into consideration how LoROTA restrictions may affect this page when we implement in in the eCheck-in application 

## AC

- [ ] Review with Appointments (and Kristen)
- [ ] Review with Danielle and/or Laura

**Comment by loripusey** [comment]
here's the [18f diagram ](https://www.sketch.com/s/f055a969-7909-4a63-9bb8-1dcbed216a42/a/4aQJwAx)

**Comment by cgednalske** [comment]
Here is a bare bones start from an earlier userflow outline that might be helpful. It shows the inspiration from 18F and our check-in completion page.

<img width="619" alt="Screenshot 2023-10-17 at 10 24 22 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/79372956/d273dbfd-0ff9-414e-89f5-3796fb72e1a1">

**Comment by benbrasso-agile6** [comment]
I moved this to @zach-park since @ytsaoca is out for a few days. But, when Ya-ching is back in the office, we can decide if we want to switch it back to Ya-ching.

**Comment by kellysmith1008** [comment]
Starting this one today - meant to start it yesterday but was out sick

**Comment by kellysmith1008** [comment]
@zach-park I like the content @cgednalske shared in the screenshot above with a few changes:
Heading: You've submitted your travel reimbursement claim
Body: No need to do anything else. You'll receive an email or text message with more details on your claim.
The links are good, except remove the part in parentheses from the first link. It should read "Submit another claim"

**Comment by zach-park** [comment]
@kellysmith1008 , @cgednalske @benbrasso-agile6 the wireframe is ready for review:
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/v/7rmAqZ/a/5nDvKz7

**Comment by benbrasso-agile6** [comment]
Left a few comments to think about. TY

**Comment by zach-park** [comment]
> Left a few comments to think about. TY

Updated the wireframes per comments:
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/183C7619-93C9-4D22-B638-74991CA8C711/canvas

**Comment by benbrasso-agile6** [comment]
@zach-park can you drop in the sketch link, we'll validate on Wednesday at design platform meeting

**Comment by zach-park** [comment]
Here is the link:
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/v/ay9M4z/a/el82YJW

**Comment by loripusey** [comment]
I'm assuming a thumbs up means validated; closing
