### ISSUE TITLE
[FSR] Review Navigation - Spouse status change transition page

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#67732]
## Description

To support the ability to edit a section on the review page, we need to add a transition screen that gives an alert to a veteran after they add a spouse in the review mode. 

This is part of the additional work that needs to be taken into account in adding the ability to edit information from the review and submit page. It will satisfy the development work in #67575 

Given: Veteran wants to click edit on review and submit page
When: Veteran changes marital status and adds a spouse
Then: The veteran will see a transition page notifying them there are more fields to be added and click to continue adding spouse income and employment history 

## Tasks
- [x] Update userflow for editing flow for spouse section
- [x] Create new transition screen notifying veteran of extra information needed
- [x] Design error message highlighting review and submit page.

## Acceptance criteria

- [x] Veteran is notified they need to complete more information if marital status is changed to true while in review navigation mode.
- [x] Attempting to submit the form without the spouse income information results in an error, and a highlighted accordion

## Testing
- [ ] N/A if non development work
---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by josephrlee** [comment]
@HeatherRienks @Tom-Davis Not sure what Epic this should go on, but I pointed it and added the rest of the details.

**Comment by josephrlee** [comment]
@HeatherRienks, moving this to validate now!

**Comment by denisecoveyduc** [comment]
@josephrlee You are absolutely right adding a spouse is likely to happen and a situation we have to account for. I think the flow and content on the page make sense the only thing I question is if we should to give the Veteran more context as to why we would be asking about the spouse's income and employment so they aren't put off. Could be something simple like adding to the end....... " You will now be asked additional questions about your spouse's income and employment **to get a clear picture of your household income.**"   [or something like that]

**Comment by josephrlee** [comment]
@denisecoveyduc, I like the extra verbiage. I think that's a great idea. Will update the mocks and show FE the new transition page now!

**Comment by josephrlee** [comment]
Here is the updated Transition page to use:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTFwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--87c1b4259dabff1e910e5143d450789b586ef327/image.png)

@OptionSelect On this ticket is the flow and the Transition page you'll need. Let me know if you have any questions!
