### ISSUE TITLE
Document process for adding categories to Feedback Portal data

### ISSUE THREAD

**Issue by twoangstroms** [department-of-veterans-affairs/va.gov-team#67739]
## Purpose
A useful iteration on using the Feedback Portal for more actionable information and data would be the SDT parsing each entry (both past and as they come in) and placing each entry into categories that will normalize with categories used by the quarterly Platform Satisfaction Survey.

Documentation [here](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2800746503/How+to+add+categories+to+Feedback+Portal+data).

## Tasks
- [x] Document process in Confluence

## Acceptance Criteria
- [x] Documentation is available in Confluence
- [x] Team review to test access and completeness
