### ISSUE TITLE
Claimant Relationship

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#67741]
## Issue Description

The Claimant Relationship page will be available to:
1. Non-Veteran users ONLY
2. Authenticated users and Unauthenticated users
3. 21-22 and 21-22a forms

Content is dynamic based on:
1. If the user selects a VSO for representation, they will see "VA Form 21-22" at the top of the page. If the user selects an attorney/claims agent for representation, they will see "VA Form 21-22a" at the top of the page.

The information collected on this page will be routed to the forms as follows:
- [21-22](https://www.vba.va.gov/pubs/forms/VBA-21-22-ARE.pdf):
   - Field 11b: Relationship to Veteran 
 - [21-22a](https://www.vba.va.gov/pubs/forms/vba-21-22a-are.pdf):
    - Field 12: Relationship to Veteran 

**URL**: `/claimant-relationship`

**Previous paths**: 
1. `/representative-contact` 

**Next paths**: 
1. `/claimant-personal-information` 

[MVP Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)

## Designs
[Prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1848-229391&t=23Wigz7X7PSKDgF8-0&scaling=min-zoom&page-id=5138%3A422026), [Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1848-229392&t=23Wigz7X7PSKDgF8-4)

<details><summary>Screenshots</summary>

<img width="292" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlgrQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c119d588382f953a9b77288ba0f4b7dc712e53f/image.png" alt="image.png" />

</details> 

---
## Tasks
- [ ] Create the Claimant Relationship page based on the designs above
- [ ] Set up the proper logic for displaying the page, as well as the content within
- [ ] Set up routing to the proper form fields

## Acceptance Criteria
- [ ] A Claimant Relationship page has been implemented, with the specs outlined above.

**Comment by cosu419** [comment]
@mtri this is ready for review

**Comment by mtri** [comment]
- If a claimant selects "We don't have a relationship that's listed here" that should show an open input field. This functions similarly to the Other field in the report modal.
[Figma comp here](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=455%3A76935&node-id=1147-89539&viewport=8908%2C9800%2C1&t=qSoZmTaocwEwh5sT-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=455%3A148692)

Other than this functionality, looks good!

**Comment by oddball-lindsay** [comment]
Good catch @mtri!  

I don't expect PII to come through this open field because of the surrounding context, but technically it's possible and given our incident with the report modal I wonder if we need to encrypt anything.  @holdenhinkle?

**Comment by oddball-lindsay** [comment]
Remove the "I am the Veteran's accredited representative".

**Comment by cosu419** [comment]
8/8 update: part of an active PR with CI checks that need to be addressed.

**Comment by cosu419** [comment]
This is ready for re-review @mtri

**Comment by mtri** [comment]
Looks good!
