### ISSUE TITLE
Chapter 3: Implement Claimant Mailing Address Page

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#67742]
## Issue Description
When the Claimant is not the Vetaran, we will first ask for Claimant Personal Information ([#66104](https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/66104)) and Claimant Contact Information ([#66105](https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/66105)).  The last piece of Claimant information we need for Chapter 3 is the mailing address.  Here are the designs for [the Claimant Mailing Address page](https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/v/RqgbGe/p/3C666192-27DA-40CE-B314-BA779A8C8BD4/canvas?posX=-23647.242250118947&posY=-1280.9289566428627&zoom=0.44297313690185547).

After the user inputs the Claimant Mailing Address the "Continue" button should route to Chapter 4 ([#66106](https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/66106)).

---
## Tasks
- [ ] Create the Claimant Mailing Address page with the design linked above
- [ ] Ensure the user interface is in alignment with design expectations.

## Acceptance Criteria
- [ ] A non-functional Claimant Mailing Address Information page has been implemented, matching the design linked above.
