### ISSUE TITLE
Chapter 1: Implement the Veteran Identification Information Page [Unauthenticated Users]

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#67753]
## Issue Description
If a user is not signed in (i.e. unauthenticated), we will not have any personal information on file to display, and will need the user to enter their identification information as the second page of Chapter 1 for **Unauthenticated** users.

Here is the design for the [Veteran Identification Information Page for unauthenticated users](https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/v/RqgbGe/p/F4F26E94-D362-4807-AE5B-34D385B66539/canvas?posX=-2433.3019160099384&posY=-248.01440661348954&zoom=0.5921485424041748)

---
## Tasks
- [ ] Create the 'enter' Veteran Identification Information page for unauthenticated users based on the design linked above.
- [ ] Ensure accurate representation of the user interface.

## Acceptance Criteria
- [ ] A non-functional 'enter' Veteran Identification Information page for unauthenticated users exists with the design linked above.

**Comment by holdenhinkle** [comment]
This is 95% done. Ran into some issues with Branch of Service validation and formatting. See this Slack convo for more details - https://dsva.slack.com/archives/C05L6HSJLHM/p1697503707105209

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-website/pull/26216

**Comment by oddball-lindsay** [comment]
Some chapter adjustments and validation left before wrapping this up

**Comment by oddball-lindsay** [comment]
Is there a better way to implement the checkboxes?  

Validations are not working as expected -- coded something, but the user wasn't notified.

There are a couple other checkbox options in the code that could be helpful
