### ISSUE TITLE
Chapter 2: Implement the Veteran Mailing Address Page [Unauthenticated Users]

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#67752]
## Issue Description
If a user is not signed in (i.e. unauthenticated), we will not have any contact information on file to display, and will need the user to enter the Veteran's Mailing Address as the second page of Chapter 2 for **Unauthenticated** users.  

The design for the Unauthenticated Veteran Mailing Address Page is still being finalized.

---
## Tasks
- [x] Create the Veteran Mailing Address page for unauthenticated users, with the design linked above
- [x] Ensure the user interface is in alignment with design expectations.

## Acceptance Criteria
- [x] A non-functional Veteran Mailing Address page for unauthenticated users has been implemented, matching the design linked above.

**Comment by holdenhinkle** [comment]
Done!

**Comment by holdenhinkle** [comment]
Done!

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-website/pull/26216
