### ISSUE TITLE
Chapter 2: Implement the Veteran Contact Information Page [Unauthenticated Users]

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#67751]
## Issue Description
If a user is not signed in (i.e. unauthenticated), we will not have any contact information on file to display, and will need the user to enter Contact Information (phone and email) as the first page of Chapter 2 for **Unauthenticated** users.  

The design for the Unauthenticated Veteran Contact Information Page is still being finalized.

---
## Tasks
- [x] Create the Veteran Contact Information page for unauthenticated users, with the design linked above
- [x] Ensure the user interface is in alignment with design expectations.

## Acceptance Criteria
- [x] A non-functional Veteran Contact Information page for unauthenticated users has been implemented, matching the design linked above.

**Comment by holdenhinkle** [comment]
Done!

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-website/pull/26216
