### ISSUE TITLE
Veteran Personal Information

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#67755]
## Issue Description

The Veteran Personal Information page will be available to:
1. Authenticated and unauthenticated Veterans 
2. Authenticated and unauthenticated non-Veterans
3. 21-22 and 21-22a forms

Content is dynamic based on:
   1. If the user is a **Veteran**, the `h2` should reference "Chapter 2".  If the user is a **non-Veteran** the `h2` should reference "Chapter 3".
   2.  If the user selects a **VSO** for representation, they will see "VA Form 21-22" at the top of the page.  If the user selects an **attorney/claims agent** for representation, they will see "VA Form 21-22a" at the top of the page.
   3. **Input fields designs**
      1. Auth Veterans, prefill fields if information exists in their profile.  The `h3` should read "**Your** name and date of birth". 
      4. Unauth Veterans.  The `h3` should read "**Your** name and date of birth". 
      6. non-Veterans (auth and unauth).  The `h3` should read "**Veteran's** name and date of birth". 

The information collected on this page will be routed to the forms as follows:
- [21-22](https://www.vba.va.gov/pubs/forms/VBA-21-22-ARE.pdf):
   - Field 1: Veteran's Name (First, Middle Initial, Last)
   - Field 4: Veteran's Date of Birth (MM-DD-YYYY)
 
 - [21-22a](https://www.vba.va.gov/pubs/forms/vba-21-22a-are.pdf):
    - Field 1: Veteran's Name (First, Middle Initial, Last)
    - Field 4: Veteran's Date of Birth (MM-DD-YYYY)

URL: `/veteran-personal-information`

Previous paths: 
1. `/representative-contact` (Veteran users) 
2. `/claimant-contact-mailing` (non-Veteran users)  

Next paths: 
1. `/veteran-contact-phone-email`

[MVP Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)

## "Unauth" (Input fields) Designs
[Prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=455-145594&t=jNm8jaVBDzkk75ek-0&scaling=min-zoom&content-scaling=fixed&page-id=455%3A76935&starting-point-node-id=455%3A148692&show-proto-sidebar=1), [Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=455-145594&t=jNm8jaVBDzkk75ek-4)

<details><summary>Screenshots</summary>

<img width="238" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3gxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5290042ec012460ebf27a569913769b4ef6ab8a0/image.png" alt="image.png" />

<img width="709" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzExQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c49d93f38e0695cc2e7c2a4e344e86db46b35203/image.png" alt="image.png" />

</details> 

---
## Tasks
- [ ] Create the Veteran Personal Information page based on the designs above
- [ ] Set up the proper logic for displaying the page, as well as the content within
- [ ] Set up routing to the proper form fields

## Acceptance Criteria
- [ ] A Veteran Personal Information page has been implemented, with the specs outlined above.

**Comment by oddball-lindsay** [comment]
This ticket has been updated to focus only on the text input pattern.  We are saving the prefill pattern work for later - https://github.com/department-of-veterans-affairs/va.gov-team/issues/90904.

**Comment by mtri** [comment]
**- "Use your legal name as it appears on your government documentation." / "Use the veteran’s legal name as it appears on their government documentation." does not need to be displayed. [VADS example without that copy referenced in our content SOT](https://staging.va.gov/mock-form-patterns/name-and-date-of-birth)**


**- The progress stepper chapter H2 should change based on non-Veteran vs Veteran**
Veteran: "Your information"
Non-veteran: "Veteran's information"

**Comment by cosu419** [comment]
8/29 update for all in review tickets - Will create a PR addressing QA by EOD @LisaLindsey

**Comment by LisaLindsey** [comment]
Thanks! @cosu419

**Comment by cosu419** [comment]
8/30 update - updating the progress stepper is not working as expected, so will need one more day to resolve. Applies to all in review tickets.

**Comment by cosu419** [comment]
9/4 update - PR pending approval

**Comment by cosu419** [comment]
Ready for review @mtri

**Comment by mtri** [comment]
Looks good!
