### ISSUE TITLE
[Design] Hearing aids content page mockup

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#6776]
## User Story or Problem Statement
As an eligible Veteran, I need to see content and directions about ordering hearing aid batteries and accessories on VA.gov so I can access the the benefit via the online form.

## Goal
_What outcome(s) do we want to see?_
- Create an informative page to help Veterans understand and access the resupply benefit

## Tasks
- [x] Finalize content for the hearing aid Drupal content page
- [x] Create a mockup of the hearing aid Drupal content page

## Acceptance Criteria
- [x] Mockup uploaded to Invision

**Comment by rebeccawalsh** [comment]
Documentation for this page can be found in GH here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-drupal-pages.md 

Unauthenticated: https://vsateams.invisionapp.com/share/6MVTG94WNH5#/410077289_Content_Page_-_Unauthenticated_-_Desktop

Authenticated: https://vsateams.invisionapp.com/d/main?origin=v7#/console/19309480/410077290/preview?scrollOffset=3908.800048828125

**Comment by rebeccawalsh** [comment]
I will be getting this document reviewed by VSP / Content prior to converting it to markdown in GH.
