### ISSUE TITLE
Investigate Medallia loading error

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#67775]
## Issue Description
[Patrick Bateman pointed out ](https://dsva.slack.com/archives/C52CL1PKQ/p1687279637305909)that Medallia fails to load at least 7% of the time according to a [Datadog synthetic test](https://vagov.ddog-gov.com/synthetics/browser/recorder/t9s-8bx-6r2
).
---
## Tasks
- [ ] _QA load test 
- [ ] Confirm fail rate 
- [ ] Coordinate with Medallia to investigate
- [ ]  Identify fix
- [ ]  Implement fix 
- [ ]  Decrease synthetic test failure

## Acceptance Criteria
- [ ] **Scenario 1: QA load test**
  - [ ] Confirm that Medallia fails to load at least 7% of the time according to the synthetic test
  - [ ] Verify the failure rate with the QA load test
  - [ ] Ensure that the synthetic test failure is decreased

- [ ] **Scenario 2: Coordinate with Medallia to investigate**
  - [ ] Contact Medallia to investigate the loading error issue
  - [ ] Collaborate with Medallia to identify the cause of the failure
  - [ ] Work with Medallia to implement a fix for the loading error

- [ ] **Scenario 3: Identify and implement fix**
  - [ ] Analyze the loading error to identify the root cause
  - [ ] Develop a fix for the loading error
  - [ ] Implement the fix to resolve the loading error

- [ ] **Scenario 4: Decrease synthetic test failure**
  - [ ] Ensure that the synthetic test failure rate is decreased
  - [ ] Verify that the fix implemented has effectively decreased the failure rate

- [ ] **Scenario 5: Configuration of the issue**
  - [ ] Attach the issue to a milestone indicating the completion date
  - [ ] Attach the issue to an epic to indicate the body of work it is a part of
  - [ ] Label the issue with the appropriate team (e.g., `product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
  - [ ] Label the issue with the relevant practice area (e.g., `backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
  - [ ] Label the issue with the appropriate type (e.g., `bug`, `request`, `discovery`, `documentation`, etc.)

- [ ] **Scenario 6: Acceptance Criteria**
  - [ ] Ensure that the synthetic test failure is decreased as per the acceptance criteria
  - [ ] 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
Completed

**Comment by ATMiddleton** [comment]
There is a new Medallia team.  Veteran Support will meet with the team to establish a schedule to coordinate efforts.

**Comment by clantosswett** [comment]
@ATMiddleton and @aubreyarcangel curious if this issue is still relevant? If yes, we can keep in the backlog but didn't know if this issue had resolved itself or if we need dive back into this at some point.

**Comment by ATMiddleton** [comment]
Mimicking a user on a mobile device - script that runs as a mobile device - need to be validated - currently 5% of users experience an error....  Want to test in production.

**Comment by ATMiddleton** [comment]
Working on a fix to migrate to staging.  3 loading issues.  Still in progress -
