### ISSUE TITLE
Research | Profile | Profile Hub Study | Topline Summary

### ISSUE THREAD

**Issue by pamela-drouin** [department-of-veterans-affairs/va.gov-team#67773]
## Background

The Authenticated Experience Profile team is evaluating including a hub page for user profiles in order to help veterans complete common tasks and reduce the need for search by keyword. More details can be found in the [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2023-10-profile-hub-usability/research-plan.md). 

## Tasks
- [x] Write [topline summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2023-10-profile-hub-usability/topline-summary.md)
- [x] Review with team and ensure alignment on themes

## Acceptance Criteria
- [x] Ready to begin synthesis

**Comment by pamela-drouin** [comment]
@mtcA6 carrying over 1 point

**Comment by mtcA6** [comment]
@pamela-drouin this is great, I'm disappointed most of these sessions were completed while I was away or at times I couldn't join! 

Finding 6, for me feels like one of the most important for iterating on the hub. I think we could combine the link and the description together in most cases which, I think, would eliminate the issue we saw with that screen reader user. For cards where there are two links like the two below, I think we could still smash the first link with the description. 

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/ed76e7da-3456-4527-93b5-c2c14e4e3bb6)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/d854d377-c3b2-433a-ac5a-af30f0d2e71f)

Even visually it's very repetitive to have the description followed by the link and they're saying VERY similar things in all cases. I think if we have the link off of the description that'll reduce some noise. 

I don't see anything missing from your topline summary, I'm excited to see the more detailed synthesis 🎉

**Comment by mtcA6** [comment]
For finding 5, similar to how we added the links to the auth menu with little ado, I think we should add links to letters and dependents to the personal information card since we've seen MANY users simply miss the auth menu entirely ([slack thread about how desktop users mostly rely on primary nav whereas mobile users rely on auth menu](https://dsva.slack.com/archives/C909ZG2BB/p1695934248774929?thread_ts=1695926343.027809&cid=C909ZG2BB)).

**Comment by pamela-drouin** [comment]
Thanks, @mtcA6! I'm so glad you added your comments here, it'll be great to return to them once we discuss the summarized findings. 

Do you have any questions about the preliminary findings above? I will be digging more into the recordings to shore up notes and quotes, so if there is anything you are wondering about, I can take a closer look. Same goes for @andaleliz -- anything you can think of that I can dig a bit deeper into, let me know!

**Comment by mtcA6** [comment]
@pamela-drouin Nope, not anything additional that immediately comes to mind for the prelim findings. 

For the hub, things feel really strong; I'm interested to hear your recommendations for incremental changes. 

For the other things you tested, I'm most interested in hearing more about the military information and specific feedback from that part of this research, especially, since the hub has generally tested well for most users. I feel those bonus questions/areas are going to be the true gold from this research.
