### ISSUE TITLE
Collaboration Cycle for [BAH-MBS-SelfServ, Time of Need Self Service, Time of Need modernization and CaMEO Integration]

### ISSUE THREAD

**Issue by CatherineHughes202** [department-of-veterans-affairs/va.gov-team#67774]
### VFS team name

BAH-MBS-SelfServ

### Product name

Current - Time of Need Self-Service

### Feature name

Time of Need modernization and CaMEO Integration

### GitHub label for product

time-of-need

### Public DSVA Slack channel for VFS team

va-gov-mbs

## Kickoff questions

<details><summary>Toggle kickoff questions</summary>
### When did/will you start working on this product/feature?

Discovery began 07/01/2023 - development start date TBD

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Both

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

No

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/burials-memorials/time-of-need/research/readme.MD

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Notify the Collaboration Cycle team of this ticket in your team's public Slack channel.

- [X] I acknowledge that I must notify the Governance team by completing the collab cycle kicckoff workflow in my team's Slack channel after submitting this issue. This can be completed by typing "/collab cycle" and selecting the appropriate workflow.
- [Kickoff Slack Thread with VFS team](https://dsva.slack.com/archives/C03QC459M0C/p1697555584736609)
</details>

### PO Sync
<details open>
  <summary>Toggle PO Sync instructions</summary>

##### OCTO Product Owner
- [ ] Review [PO Sync Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/po-sync) to understand what this sync involves.
- [ ] Schedule your PO Sync (with at least 2 business days lead time from now):
  - Open the [Calendly PO Sync calendar](https://calendly.com/collaboration-cycle/po-sync)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Schedule Event"
- [ ] Link all artifacts in the `PO Sync artifacts for review` section below at least two business days before the scheduled PO Sync. Please don't add artifacts in the comments section.

**PO Sync artifacts for review**
[See guidance on PO Sync artifacts.](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/po-sync#POSync-Whatartifactswillbeneeded?) Please provide links to artifacts **at least two business days** before the scheduled meeting.

Required:
- [ ] Product outline

Optional:
- [ ] Any other artifacts you have so far

##### Governance Team actions
- [ ] Meeting date/time:

##### OCTO Design Leads
- [ ] If the initiative receives OCTO alignment to proceed, add the PO-Sync-approved label to this ticket.
- [ ] If the initiative does not receive OCTO alignment to proceed, comment and close this ticket. 

</details>

### Design Intent

<details>
  <summary>Toggle Design Intent instructions</summary>

##### VFS team actions
- [ ] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [ ] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [ ] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.
  
**Design Intent artifacts for review**

[See guidance on Design Intent artifacts.](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts) Governance Team feedback is based on the artifacts provided here as well as information provided during the meeting. Please provide links to artifacts **at least two business days** before the scheduled meeting.

Required:
- [ ] User flow

Not required, but nice to have:
- [ ] Wireframes (if provided, must include mobile wireframes)

Optional:
- [ ] Research plan
- [ ] Any other artifacts you have so far
  
##### Governance Team actions
- [ ] Design Intent Slack thread with VFS team
- [ ] Meeting date/time:
  
##### Governance Team actions

- [ ] Update this ticket with the Zoom recording
  - Recording link
  - Passcode:
- Accessibility
  - [ ] Feedback ticket attached
  - [ ] No feedback
- Design
  - [ ] Feedback ticket attached
  - [ ] No feedback
- IA
  - [ ] Feedback ticket attached
  - [ ] No feedback
  
##### VFS team actions

- [ ] Review feedback tickets. Comment on the ticket if there are any questions or concerns.
  

</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [ ] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [ ] Link to the Readiness Review ticket below

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by CatherineHughes202** [comment]
This effort has been put on pause and is slated for future work.  Will revisit when prioritized at the top of the backlog for the team

**Comment by shiragoodman** [comment]
@CatherineHughes202 If it's okay with you, we would prefer if you close this ticket if this work is no longer in progress. We track open tickets. If/when you pick this work back up, it is recommended that you submit a new Collab Cycle kickoff.

**Comment by CatherineHughes202** [comment]
Happy to @shiragoodman Closed, since this effort has been reprioritized for future work and placed at the bottom of our backlog.
