### ISSUE TITLE
[Design] Discovery project brief & planning

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#6778]
## User Story or Problem Statement
As a designer, I need a brief and plan for debt letters discovery work so that I can communicate and complete work effectively within agreed timeframes.

## Goal
_What outcome(s) do we want to see?_
A plan for discovery and design work for debt letters

## Tasks
- [ ] Complete project brief
- [ ] Complete work proposal

## Acceptance Criteria
- [ ] Project brief completed and in GH
- [ ] Work proposal linked in this ticket

**Comment by rebeccawalsh** [comment]
Markdown doc has been created and filled with the template: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/discovery/project-brief.md

**Comment by rebeccawalsh** [comment]
- [Completed project brief template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/discovery/project-brief.md)
- [Mural of proposed discovery/design timelines](https://app.mural.co/t/vsa8243/m/vsa8243/1585159698067/146df14aec21be75e9a9e9c3466c432d556b3f77)
