### ISSUE TITLE
Veteran Shadowing Research Plan

### ISSUE THREAD

**Issue by evelynhilbrichdavis** [department-of-veterans-affairs/va.gov-team#67788]
## Issue Description
Teams DBEX and Carbs are collaborating on a research plan for veteran shadowing of the 526. This research will help identify key features for redesign as well as guide prioritization efforts.

---
## Tasks **(in collaboration with Team 2)**
- [x] Research design workshop to align on research questions and approaches
- [x] Share draft with Shannon and respond to her questions
- [ ] Make final edits as needed before uploading to Github research folder

## Acceptance Criteria
- [x] Complete research plan (ready to submit for review)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by evelynhilbrichdavis** [comment]
Draft shared with Shannon on Thursday 11/2, awaiting feedback (likely early next week as she is out tomorrow)

**Comment by evelynhilbrichdavis** [comment]
https://docs.google.com/document/d/1uhwAano45WJpSMkAkqbue04bNCWLRYMXK9RzwHSGBYo/edit#heading=h.c9q65b2w3v74

**Comment by evelynhilbrichdavis** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/research/2023-11-Shadowing-Research/Research-Plan.md
