### ISSUE TITLE
Report findings for Medallia research

### ISSUE THREAD

**Issue by evelynhilbrichdavis** [department-of-veterans-affairs/va.gov-team#67782]
## Issue Description
This ticket is to create a report of findings and recommendations from the Medallia research exploration completed by Teams DBEX-CARBS. 

NOTE: We are still determining format of the final report. Historically, research created a white paper for Medallia learnings. For reference, here is that report: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/research/MedalliaSurvey-032023.md

And here is the template for report of Github: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/sharing-research/research-findings-template.md

---
## Tasks
- [x] Determine the format of report
- [x] Upload research report to Github
- [x] Create findings page on GitHub 
- [x] Update research repo board
- [x] Schedule meeting to share findings with team and stakeholders, 

---
## Acceptance Criteria
- [x] Developed report
- [x] Scheduled report out
- [x] Ask developers to add report PDF to Github

**Comment by evelynhilbrichdavis** [comment]
We will plan to report out once CARBS is back from their offsite the week of 10/30.

**Comment by evelynhilbrichdavis** [comment]
This is shared work, but I am working on it independently while Coforma is out at their offsite.

**Comment by evelynhilbrichdavis** [comment]
Readout scheduled for 11/8 and 11:30 EST.

**Comment by evelynhilbrichdavis** [comment]
Reason we couldn't close with the sprint: Must post all documentation on Github. Readout complete, etc.

**Comment by evelynhilbrichdavis** [comment]
[Medallia Research findings and deck](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez/research/Medallia%20Research)

**Comment by evelynhilbrichdavis** [comment]
[Added to research repo ](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/439)
