### ISSUE TITLE
Unauthenticated Designs (Desktop + Mobile)

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#67790]
## Issue Description
We have completed the high fidelity designs for the authenticated MVP flow.  This ticket is to follow up with the unauthenticated designs for our MVP flow.

The unauthenticated pages we need designs for are outlined in our [MVP document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/mvp.md#appoint-a-representative).

---
## Tasks
- [ ] Add in additional high fidelity **desktop** designs for the unauthenticated flow as outlined in the MVP document above
- [ ] Add in additional high fidelity **mobile** designs for the unauthenticated flow as outlined in the MVP document above

## Acceptance Criteria
- [ ] Desktop and mobile designs for the unauthenticated MVP flow are added to our Sketch canvas
- [ ] Designs are ready for an async Midpoint review
