### ISSUE TITLE
[bug] NOD | Redirect not happening from MyVA

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#67795]
## Value Statement
**_As a_** Veteran
**_I want to_** know that the NOD form was updated on my saved form
**_So that_** I can provide my most up-to-date answers

## Background Context

When doing #67645 validation testing. We ran into an error on staging where continuing the form from my MyVA saved form widget does not redirect the form to the new pages, as they're suppose to in the AC for that ticket.

### Replicate the issue
- On staging, log into user 228
- Scroll down to bottom where there's saved forms
- Continue on saved form
- See if it redirects to the extension page with a slim alert mentioning that the form has been updated

https://github.com/department-of-veterans-affairs/va.gov-team/assets/111457818/92d62747-5738-4d05-8ac7-0f13b7215902

## Acceptance Criteria

- [x]  If a user is returning to a save-in-progress form from MyVA AND is past the contestable issues page before the new version is released, they are prompted to go to the new "request an extension" page
- [x]  If a user is returning to a save-in-progress form from MyVA AND is before the filing deadlines page before the new version is released, they are not prompted to go to the new "request an extension" page
- [x]  User sees an alert notifying them to view the "request an extension" page
- [x]  SIP data is not lost when the new pages are introduced

## Tasks
- [ ] Confirm if this is a platform code issue
- [ ] Decide if it's a launch blocker

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
@Mottie will you be picking this up or are you working on contestable issues and need someone else to?

**Comment by Mottie** [comment]
This looks like a problem within the platform form library resume an application code. I'll look into it, and if it's something straight-forward, I can work on it.

**Comment by saderagsdale** [comment]
the method we're using to check the feature flag isn't reliable.

**Comment by Mottie** [comment]
This work is ready for validation. I've set up these 3 mock users to have a save-in-progress to return to the contestable issues page while the feature flag was disabled:
- vetsgov+test233@id.me
- vetsgov+test234@id.me
- ~vetsgov+test235@id.me~ skipped; was asking for ID upload while verifying
- vetsgov+test236@id.me

To preserve this state until testing is done, don't modify any form fields or use the "Finish this application later" link.

**Comment by eileen-coforma** [comment]
Validated that 233 works for the following ACs:
- If a user is returning to a save-in-progress form from MyVA AND is past the contestable issues page before the new version is released, they are prompted to go to the new "request an extension" page
- User sees an alert notifying them to view the "request an extension" page
-  SIP data is not lost when the new pages are introduced

**Comment by eileen-coforma** [comment]
Validated that 238 works for the following AC:
- If a user is returning to a save-in-progress form from MyVA AND is before the filing deadlines page before the new version is released, they are not prompted to go to the new "request an extension" page
