### ISSUE TITLE
[bug] NOD | API loaded contestable issues not showing up

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#67796]
## Value Statement

**_As a_** Veteran
**_I want to_** see all of my API-loaded contestable issues
**_So that_** I don't have to manually add issues

---
## Background Context

During testing, we noticed that when starting a new form, all API-loaded contestable issues are over-written by the save-in-progress data. So when the Veteran arrives at the contestable issues page, there are no issues, and no alert stating that the contestable issues didn't load.

## Tasks

- [ ] Update contestable issues after save-in-progress overwrites the form data
- [ ] Add unit tests, as needed

## Acceptance Criteria

- [ ] All tasks complete
- [ ] All tests passing

## Definition of Ready 
- [ ] Needed changes identified

## Definition of Done
- [ ] Acceptance criteria met
- [ ] API-loaded contestable issues appear as expected in staging

**Comment by eileen-coforma** [comment]
@Mottie who needs to do the code review?

**Comment by Mottie** [comment]
Code review is done, now it CI to pass then I can merge it

**Comment by eileen-coforma** [comment]
Validated that API issues load on first instance on user 239 (Medge)
