### ISSUE TITLE
IA Tracker - Pension Reactivation

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#67800]
### Overview
Intake ticket #66578 

#### Description
To document pension entry points for the reactivation phase for the MVP, which launches in January 2024.

```[tasklist]
### Tasks
- [x] Review team's documentation
- [x] Create IA spec with new plan
- [x] Kristin reviews IA spec
```

**Comment by kristinoletmuskat** [comment]
Link to team's really well-documented entry points plan: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695069026901/50b83f710f1cd2f1f7f3bb63553c349ef90d402a?sender=ua67f17f1c416a96ea04d2476

**Comment by jennymayoco** [comment]
@juliepedtke @vbellissimo @ maya (will update with GH username) as per Slack, we have the [IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/pension-form-reactivation.md) with the entry points only. This doc will adjust as we move through the pension benefits redesign phase. Let me know if there's any questions in the meantime.

cc @katherine-fung

**Comment by jennymayoco** [comment]
Moving to validate as final entry points feedback has been shared with team

**Comment by vbellissimo** [comment]
@jennymayoco may I add our team's tag to this card, as well? So it shows up on our board, it's on my radar?

**Comment by jennymayoco** [comment]
Of course! I can also share the IA spec in the team's intake ticket so it's there for reference as well. Is there a ticket I could add this doc to?

**Comment by vbellissimo** [comment]
Thank you! @jennymayoco , I believe it was this one, started by Laura Steel's team, who my team is inheriting this work from: https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/66578

**Comment by jennymayoco** [comment]
Moving this ticket to in progress in case a URL update is within scope for the MVP. As per most recent update from team https://github.com/department-of-veterans-affairs/va.gov-team/issues/66578#issuecomment-1811176822, they are connecting with their OCTO lead to get confirmation on possible next steps for MVP or possibly for post launch if not within scope at this moment. Next sprint ends 12/6 and MVP launches in January 2024.

**Comment by jennymayoco** [comment]
Moving this ticket to validate as there isn't any additional IA work for the MVP relaunch. The team okay'd a URL update for the next version and so we will connect then to confirm the proposed URL and create a redirect ticket so folks don't get an error page if trying to access the old link.
