### ISSUE TITLE
[FSR] Review Page - Display error when missing information

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#67811]
## Description

If a user edits information on the form, they may need to fill out additional fields before submitting the form. This error on the Review Page will let users know they will need to go back to a specific area of the form to provide more information

This is part of the additional work that needs to be taken into account in adding the ability to edit information from the review and submit page. It will satisfy the development work in #67584 

**Example of Review page error message that has been implemented:**
- [Review & submit validation error links #21252](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21252)
   - [PR #16431](https://github.com/department-of-veterans-affairs/vets-website/pull/16431)
  ![image](https://user-images.githubusercontent.com/136959/73964336-9ac52000-48d7-11ea-9a84-677ff866870d.png)

Given: Veteran has updated information and additional question will need to be filled out (example, they made a typo when filling out income and are no longer eligible for the SW and must fill out the full FSR form).
When: Veteran changes information and needs to fill out additional fields
Then: Ideally, Veteran will see errors upon viewing the review page and be directed to which sections need to be filled out

## Tasks

- [x] Mockup showing error message on review page

## Acceptance criteria

- [x] Mockup and content created

## Testing
- [x] N/A if non development work
---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [ ] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by josephrlee** [comment]
Here is the [proposed error page mockup](https://sketch.com/s/50583485-ba58-4ef8-ae04-2c274a792547/a/kK80MRD/play) for the review page that happens on submit:

<img width="1280" alt="C7P1: Review application - Error messaging" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/990a7011-2c2b-4e61-8196-f364c2c2bba1">

From a feasibility standpoint, it still needs to be validated by FE, but I think we can close this ticket out for now.

**Comment by denisecoveyduc** [comment]
Hi Team, @HeatherRienks asked me to review and provide some feedback on this ticket. Is there something specific you wanted to call out or discuss?  I wasn't sure.

Overall I like the direction, one thing that stood out to me.  When we say **_"Your request wasn't submitted because you are missing information"_** ...to me that sounds as though we are telling the Veteran they did something wrong. 

If I am understanding correctly this information is missing because they made some changes and now we are required to ask 'new' questions  of the Veteran. Could we instead say **_"Your request wasn't submitted because information is missing_** or  **_because more information is required_**   That may help to remove any feeling the Veteran may have that they did something wrong.
FYSA @josephrlee @mgleo @charlottecesana

**Comment by josephrlee** [comment]
@denisecoveyduc, thanks for taking a look at this! We just wanted your eyes on this from a copy/voice standpoint. 

Yes, you understand it correctly. The adjusted language sounds better! I can update the design to reflect the new copy.

**Comment by josephrlee** [comment]
Here is the updated version:
<img width="1280" alt="C7P1: Review application - Error messaging" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/d18c36cc-a7ef-4fda-aad8-b5cfab0fea65">

@Dr-Pongo, here is the updated messaging for reference for #67584

**Comment by Dr-Pongo** [comment]
[FE ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/69352)
