### ISSUE TITLE
Consolidate and Playbook findings from recent knowledge shares

### ISSUE THREAD

**Issue by mchae-nava** [department-of-veterans-affairs/va.gov-team#67813]
## Issue Description
Outcome from the monitoring meeting. The scope includes both our notes from the brain dump with Kyle, and notes from ongoing info shares between Kyle and Team 2
- Manual backup submissions
- Others
- Include some writeups for things related to monitoring rollout, for when Mark is out in November
---
## Tasks
- [ ] Compile notes and consolidate playbooks

## Acceptance Criteria
- [x] Compiled notes
- [ ] Playbooks for anything actionable as part of KT with Kyle
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
