### ISSUE TITLE
Release AL2-based SOCKS Proxy

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#67820]
# Description
In order to replace the existing AL1 SOCKS proxy, we need to release the hardened AL2-based version for use. There is a single [deploy pipeline](http://jenkins.vfs.va.gov/job/deploys/job/va-socks-utility/) for the SOCKS proxy as there is only one instance required.

# Tasks
- [ ] Create documentation describing build and deploy process as well as dependencies and design
- [x] Create a release plan
- [ ] Integrate SOCKS proxy access process with new AL2-based version

**Comment by pjhill** [comment]
Tentative high level release plan is https://vfs.atlassian.net/wiki/spaces/PRT/pages/2810019949/SOCKS+and+JumpBox+Release+Plan.

**Comment by pjhill** [comment]
The workflow for the SOCKS issue creation is [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/workflows/pst-amt-sock-kickoff.yml).

**Comment by pjhill** [comment]
It looks like the flow goes --
1. Issue is created in va.gov-team and kicks off this workflow: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/workflows/pst-amt-sock-kickoff.yml
2. That runs a workflow in the devops repo that checks for the user's presence on the roster: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/workflows/pst-amt-sock-kickoff.yml
3. If the user is on the roster then that workflow dispatches another workflow in devops that creates a PR giving SOCKS access: https://github.com/department-of-veterans-affairs/devops/blob/master/.github/workflows/socks-access.yml. This flow creates the authorized key file that is required to be stored in the devops repo and updates the socks config to include the new key.
4. Once the PR is created, it needs to be manually approved by a member of the devops team.

**Comment by pjhill** [comment]
In order to route these configs into AL2 version of SOCKS seamlessly we might be able to update the workflows to simultaneously update the SOCKS configuration in two places. Both in `devops` and in `pso-tf-socks-proxy`.

https://github.com/department-of-veterans-affairs/pso-tf-socks-proxy/tree/ba-66378

**Comment by pjhill** [comment]
Ben is out on PTO at the moment, but I believe he also has in his notes somewhere an alternative workflow for processing SOCKS access requests that involves Terraform.

**Comment by pjhill** [comment]
Latest per a brief convo with Ben --
We are encountering rate limit issues with GitHub. It may be impractical to create a new system that scans GH user profiles for their latest keys. Instead, it may be a better plan to adapt the existing SOCKS access flows.

**Comment by pjhill** [comment]
Unable to release SOCKS for now as it requires additional work to be in a release ready state. Additionally, changes to Ansible that configures Review Instances will have effects on SOCKS / JumpBox that need to be addressed.
