### ISSUE TITLE
Pension 527EZ | Fix Flaky Tests

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#67822]
## Issue Description
_Beginning 11/6/2023 merges will be blocked to any products that have flaky Unit/E2E tests. They need to be resolved before 11/5 to avoid blocked merges._

- [Flaky Unit Tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/currently-disallowed-unit-test-specs-on-va-gov)
- [Flaky E2E Tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/currently-disallowed-cypress-test-specs-on-va-gov)

For more information - please refer to: [VA all-teams post](https://dsva.slack.com/archives/CE4304QPK/p1697562278492779)
For questions/concerns - please contact the [platform-reliability-team](https://oddball.slack.com/archives/C044Z57LS2Y)

---
## Tasks
- [ ] Fix this unit test for 527: src/applications/pensions/tests/pensions.cypress.spec.js
- [ ] Check lists of unit and E2E tests for any additional 527 tests that need to be fixed.

## Acceptance Criteria
- [ ] 527EZ form no longer uses flaky tests
---

**Comment by vbellissimo** [comment]
The online 527 Pension form was deactivated in Nov 2023 and is set to relaunch in January 2024. This team has since recreated unit tests as part of Staging Review completed in January. Closing this ticket as it's no longer relevant.
