### ISSUE TITLE
ARM Nav & Search - User Test - Plan Revisions v3

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#67839]
## Issue Description
User test for ARM experience including Veteran representative engagement questions as well as VA.gov representative experiences of:
1. Navigation
2. Search
---
## Tasks
- [x] Update research plan
- [x] Update convo guide
- [x] Update GitHub recruitment request
---
## Acceptance Criteria
- [x] All materials complete and ready for research review

**Comment by oddball-lindsay** [comment]
Blocked at the moment - need to understand what our future path forward is (to split or not split MVP?)

**Comment by oddball-lindsay** [comment]
We are moving forward with splitting the MVP.

**Comment by jfinnerty13** [comment]
Documents updated and transferred to GitHub, waiting on prototype to submit to research review
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/accredited-representation-management/research/2023-11-ARM-search-nav-usertest
