### ISSUE TITLE
Copy of Update Find a Representative designs based on feedback from CAIA Content, Midpoint Review and OGC Legal Review

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#67837]
## Issue Description
[High fidelity designs for our MVP were created](https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/66347) and presented to a few different parties for feedback, as we prepare for user testing.  Feedback will be coming from:
1. Midpoint review (governance team)
2. CAIA content specialists (A Procik and Katherine Fung)
3. Office of General Counsel reviewer identified for the accredited representative legal language (specific person TBD) 

We will need to update designs according to feedback from the parties above, with an emphasis on screens that will be used for the upcoming user test.

---
## Tasks
- [ ] Review feedback
- [ ] Update prototype with feedback in mind -- (address Must and Should at a minimum)
- [ ] Share the updated prototype with Research (Janelle) so she can update the research test plan accordingly
- [ ] Update non-prototype designs with feedback in mind -- (address Must and Should at a minimum)

## Acceptance Criteria
- [ ] Prototype has been updated
- [ ] Prototype has been shared with Research
- [ ] Non-prototype designs have been updated

**Comment by oddball-lindsay** [comment]
Prototype flow: https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e

**Comment by oddball-lindsay** [comment]
Updated with AB test options for full legalese vs. friendlier interpretation

https://dsva.slack.com/archives/C05L6HSJLHM/p1699896050527929?thread_ts=1699376606.550909&cid=C05L6HSJLHM

**Comment by oddball-lindsay** [comment]
Designs have been created along with a clickable prototype.  Upcoming edits:
1. [Update designs with CAIA content recommendations](https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/70631)
2. Implement design pattern for authorization steps, according to Design's recommendations - ticket and guidance TBD
