### ISSUE TITLE
Pension | Trigger Deactivation Email

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#67849]
## Issue Description
_Once the pension 527EZ form is deactivated, the VA notify trigger created [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64323) needs to be activated to send an email to users with in-progress forms informing them that they can no longer submit their pension form online._

Sending a list of intent to file (ITF) dates to the VBA will be a tandem activity. See ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/64403

---
## Tasks
- [ ] Activate VA Notify trigger
- [ ] Confirm successful email distribution

## Acceptance Criteria
- [ ] Users with in-progress 527EZ forms receive the email
---

**Comment by steele-lm** [comment]
@vbellissimo This is the original ticket I ha stubbed out to send the deactivation email.
