### ISSUE TITLE
Create a summary section for Veteran Information - Proofing Agent Flow

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#67854]
## User Story
As a Proofing Agent, I need to be able to confirm the information I captured in the intake form before I verify this information in the IAM toolkit so I know the info I entered is accurate.

## Tasks

- [x] Build out summary section with Login.gov design system components
- [x] Write out content for section
- [x] Confirm that user flow is valid with team internally

## Acceptance Criteria
Scenario: A Proofing Agent has completed the intake form in the IPP flow
GIVEN A Proofing Agent has filled in all required fields of the Veteran intake form
**WHEN they click 'Continue'
THEN they will see a screen showing all of the information they entered**
AND they can click 'Continue' to go to the next screen (should it be 'Confirm'? 'Information is correct'?)

Scenario: A Proofing Agent needs to edit a field
WHEN a Proofing Agent needs to edit one of the fields
THEN they can (click a pencil icon? click edit? What is the pattern?)
AND that field will become editable (should the entire form become editable?)
WHEN they click (Save?)
THEN the change will be saved and they will return to the summary view

Notes/Questions:
- how will they edit from the summary view?
- can they edit multiple fields at once?
- how do they continue from the summary view a) if they've made edits and b) if they haven't made edits?

## Def of Done

- [ ] Section has been reviewed by internal team
- [ ] Section has been added into prototype flow

**Comment by lmorris3** [comment]
@MOStudioCarolyn I think you're working on this screen so I wanted to tag you that I added Acceptance Criteria and some notes/questions. Feel free to edit this as you create the designs (this is just a starting point).

**Comment by skirkman16** [comment]
Sharing out summary screen in design dev sync today 11/7

**Comment by skirkman16** [comment]
Reviewed summary box with team. Intention, flow and content were well understood and agreed upon by all team members (Design, dev, product). Next step is to determine masking for sensitive information
