### ISSUE TITLE
Next iteration of Veteran journey Gantt sketch

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#67855]
## User story
As a UX Designer, I need to drive empathy and motivation by visualizing how our roadmap translates into a representative user journey.

## Tasks 
[User journey Gantt sketch](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEpIQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--05906d368bc277eea1402dfa92d8204144f55557/Screenshot%202023-10-17%20at%203.10.58%20PM.png)

- [x] Iterate on this sketch by spacing out the scenes and adding more detail
- [x] Add the assist phase
- [x] Share out internally

## Acceptance Criteria

- [x] Feedback is implemented ahead of next PO sync on Thursday 10/19
- [x] Updated sketch is shared with Tom in PO sync

**Comment by skirkman16** [comment]
[Uploading... 2023 CEDAR Identity Strategy Roadmap_2023-10-19_20-12-17.png]

**Comment by skirkman16** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnhWQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ce226cee223749df84f592b35139c952e8ab663/2023%20CEDAR%20Identity%20Strategy%20Roadmap_2023-10-19_20-12-17.png)
