### ISSUE TITLE
Update IPP intake screens with new design system

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#67852]
We have access to Login.gov's design system and now we can apply its components to the IPP prototype. Using Login.gov's design system will ensure easier integration for Login.gov in the future.

## Tasks
- [x] Collaborate with devs to ensure they have documentation for building
- [x] Apply design system to all intake screens
- [x] improve microinteractions according to feedback

## Acceptance criteria
- [x] Intake screens are up to date with Login.gov design system
- [x] Share out new prototype internally

**Comment by skirkman16** [comment]
@SophiaPhilipMO

**Comment by SophiaPhilipMO** [comment]
@CarlDickerson
