### ISSUE TITLE
Reorganize Moderator Responsibilities for Design System Team Staging Review

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#67867]
## User Story
As a Governance team member, I want to find the Staging Review guidance I need when I need it so that I am able to complete the task at hand quickly and easily.

As a Governance team member, I want to be able to easily understand the Staging Review task at hand, so that I'm not spending more time on the task than needed.

Assignee: @briandeconinck 
Peer Reviewer: @erinrwhite 

## Description
Governance team would like to improve the organization of the moderator responsibility docs. The goal of this ticket is to split the main sections of the document into separate documents (Schedule, During Meeting, Post Meeting), group steps in each section that require modifications to the same tools to avoid context switching (ie Slack, gh ticket), reorder the steps within each section so that they occur in a logical and meaningful order, and to name the steps so that it is easy to see what goal each step is trying to accomplish.

The Design System Team Staging Review guidance should follow the same naming convention and framework as the Staging Review guidance. See ticket #64433.

## Impacted Artifacts
[Staging Review - Design System - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572124161/Staging+Review+-+Design+System+-+Moderator+Responsibilities)

## Tasks
- [x] Split doc into separate pages - 
   - team agreed to merge pre-schedule and schedule, and then delete the pre-meeting section as this is completed at standup
   - [Design System Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2823323763/67867+-+Design+System+Staging+Review+-+Scheduling)
   - [Design System Staging Review - During the Meeting](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2823258245/67867+-+Design+System+Staging+Review+-+During+the+Meeting)
   - [Design System Staging Review - After the Meeting](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2823356523/67867+-+Design+System+Staging+Review+-+After+the+Meeting)
- [x] Rename pages appropriately
- [x] Review steps within each section and identify if any can be merged due to work occurring within the same tool and/or space
- [x] Reorder steps so that events occur in a logical and meaningful order
- [x] Apply names to each steps that explain the high level goal of each step
- [x] Review all documents to identify if there's any other opportunities for improvement. If so, list steps below and make changes to docs. If none are identified, please write N/A:
   - Removing some excess content would be helpful
   - Rewriting the script and making bullet points makes it easier to read

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have split the Design System Staging Review - Moderator Responsibilities guidance into separate guidance docs.
- [x] We have reorganized, merged steps and added clarity to the moderator guidance for Staging Review

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
@erinrwhite This is ready for peer review! The design system staging review instructions are a bit of a mix of stuff from kickoff, midpoint, and staging for VFS teams, but hopefully it reads consistently with the other documents. (And hopefully I caught everywhere I copied/pasted from one of those places!

- [Design System Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2823323763/67867+-+Design+System+Staging+Review+-+Scheduling)
- [Design System Staging Review - During the Meeting](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2823258245/67867+-+Design+System+Staging+Review+-+During+the+Meeting)
- [Design System Staging Review - After the Meeting](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2823356523/67867+-+Design+System+Staging+Review+-+After+the+Meeting)

**Comment by erinrwhite** [comment]
Awesome @briandeconinck! I am gonna look at this first thing Monday when I have some more brain cells available 😂

**Comment by erinrwhite** [comment]
@briandeconinck I went through and made a couple of small edits to replace "VFS" with "DST" - looking good to go!

**Comment by briandeconinck** [comment]
[Design System Staging Review guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572025931/Design+System+Staging+Reviews) is updated, and announcement is posted to Slack. Closing as complete!
