### ISSUE TITLE
Support: Mon-Thur Deploy (S39)

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#67862]
## User Stories
As a Platform team member who just contributed to the Platform website,
I need my content published,
so that I can share my content updates with the intended audience.

As a content team,
we need to review any new content changes made on the platform,
so that we can deploy every Tuesday and Thursday of the week.

## Tasks
Someone from our team will use Scroll Viewport to publish changes to the website after 3pm EST on:

- [x] Wednesday (10/25) - **Jill & Rebecca swap day**
- [x] Thursday (10/26) - **Jill & Rebecca swap day/Rebecca's first deploy day**
- [x] Monday (10/30) - Lauren
- [x] Tuesday (10/31) - Brian
- [x] Wednesday (11/1) - Rebecca
- [x] Thursday (11/2) - Jill
- [x] Monday (11/6) - Lauren
- [x] Tuesday (11/7) - Brian

--- NEXT SPRINT
**- Discuss updating deployment rotation schedule for next sprint 7 beyond**

## Acceptance Criteria

- [x] The Platform website will be deployed Monday-Thursday between 3:30 and 5pm for this sprint.
- [x] Any edits with launch-blocking issues will be announced to their content editors via #platform-content

## Other Info

Data tracking info:
https://vfs.atlassian.net/wiki/spaces/CIT/pages/2282979860/KPIs+-+Content+Support

Temporary rotating schedule:
https://vfs.atlassian.net/wiki/spaces/CIT/pages/2405171201/Deployment+rotation+schedule

**Comment by johnny-jesensky-adhoc** [comment]
Platform website deployments completed for this sprint, moving this to _Done._
