### ISSUE TITLE
[bug] VHA FSR confirmation emails not sending since 10/10

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#67875]
## Issue Description
Beverly from the VA Notify team has brought to our attention

>VA Notify is working on a new tool that lets us know when notifications have stop sending for a few days.  Two of your notifications came on the list today, as they have no sends since 10/10:
Debt: FSR Confirmation - VHA
Debt: FSR Confirmation - Streamlined

We need to look into this and resolve it as soon as possible.

---
## Tasks
- [x] Identify reason for confirmation emails not sending
- [x] Replicate locally
- [x] Add fix 

## Acceptance Criteria
- [x] We have resolved the confirmation emails sending
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
