### ISSUE TITLE
<Intake> SAMPLE TEST TICKET <CAIA>

### ISSUE THREAD

**Issue by coforma-terry** [department-of-veterans-affairs/va.gov-team#67870]
## About your team

- Team name:  
- OCTO-DE product owner:  
- Product name: 
- Product manager:  
- Slack channel: 
- Dedicated content writer on your team (if you have one):
- Dedicated a11y specialist on your team (if you have one):
 
## About your request
**Describe what you want CAIA to collaborate on** 
For example, you may need content collaboration to ensure a form is plain language or guidance to plan accessibility testing on a new tool. 

</br>
</br>
</br>

## Collaboration timeframe

We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

**Your timeline** 
- [ ] Is this request tied to a Congressional mandate or timeline? (Check if yes) 

Describe where you are in your project's timeline. For example, you may be drafting content, planning or synthesizing research, waiting on an SME review, or scheduling your MVP launch date. Add dates for any upcoming milestones.
</br>
</br>
</br>

## Collaboration cycle
If you’re going through the collaboration cycle with the governance team, link to the ticket:

If you’re not going through the collaboration cycle, or you’re unsure, check here and we can follow up: 
- [ ] Not going through collab cycle 

Note: We ask that you partner with us before scheduling your midpoint review, to ensure we can agree on a deliverable and that there's time for your team to make changes.  
</br>
  
## Supporting artifacts
Please provide links to any supporting artifacts we might need to begin work. This can include your product outline, user flows, mockups and prototypes, draft content, etc.

<br>
<br>
<br>

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag `@Terry Nichols`.**

A member of the CAIA team will aim to respond to your Slack message within 24 hours to acknowledge receipt - should we need any additional information regarding your request we will reach out to you to confirm.

From here we'll reach out to set up a kickoff meeting with your team - these are usually conducted every 2 weeks on Wednesday afternoon between 12 - 1PM ET.

<br>

## TASKS

<br>

```[tasklist]
### a11y
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/67921
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/68979
```

```[tasklist]
### Content
```

```[tasklist]
### IA Tasks
- [ ] Jenny does a quick audit of all the things
```

```[tasklist]
### CAIA Ops
- [x] Set up kickoff meeting - Terry/Lily
```
