### ISSUE TITLE
Copy of Flaky e2e test - all-claims-keyboard-only.cypress.spec.js

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#67874]
This keyboard test is showing up on the flaky tests report and has been auto disabled. Investigate root cause and put in a fix to make this test reliable.
![image.png](https://images.zenhubusercontent.com/641341411444ec27c3eb60a4/36bb0375-4949-422c-a8c3-a29a16edab81)

[report](https://depo-platform-documentation.scrollhelp.site/developer-docs/currently-disallowed-cypress-test-specs-on-va-gov)

[documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/flaky-test-management-in-cypress)

## Task
- [x] Understand what is being tested
- [x] Manually test
- [x] Determine if the test is useful or should be removed
- [ ] Provide fix (application / test)

## Acceptance Criteria
- [ ] Fix committed for the bug
- [ ] Test is re-enabled and reliably passes (i.e. no longer on the flaky report)

**Comment by NB28VT** [comment]
Did we receive any guidance re: what "removing" actually means? I see three options:
1. Delete the file (we should be able to get it back later with Git when we want to revisit it)
2. Using the [`skip` method Cypress has](https://www.browserstack.com/guide/cypress-skip-test) (I think this is preferred and we use it elsewhere)
3. Commenting out the file.

I think we should do 2 if we plan on revisiting this test which we should (more below)

**Comment by NB28VT** [comment]
Note removing this test for now is effectively preventing a critical test of the form flow for users who can only use a keyboard. If this test is passing enough I might suggest pushing back on the platform team about making an exception, but it's unlikely we'd be granted one.

This is probably the most important test in our codebase regarding accessibility from what I can tell.

**Comment by austinjprice** [comment]
This test is currently disallowed for the last 260 days correct? So i believe we aren't losing anything by "removing" if I am understanding correctly. @tblackwe any suggestions on implementation Nathan mentions above?

**Comment by NB28VT** [comment]
> This test is currently disallowed for the last 260 days correct? So i believe we aren't losing anything by "removing" if I am understanding correctly. @tblackwe any suggestions on implementation Nathan mentions above?

Oh interesting what does disallowed mean? Is that a config in our CI that skips the test or something?

**Comment by austinjprice** [comment]
As per discussion lets remove. @austinjprice to add reference for recreation

**Comment by NB28VT** [comment]
> As per discussion lets remove. @austinjprice to add reference for recreation

Just a quick reminder to create a ticket to re-do this test (it's probably a fair amount of work)

**Comment by NB28VT** [comment]
> Backlogged ticket added here https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/68612

Awesome, I'll add a link to the commit when it merges that removes the test (so whoever rewrites it can find the old test code I'm deleting as guidance"

**Comment by NB28VT** [comment]
Sam skipped the test [here](https://github.com/department-of-veterans-affairs/vets-website/pull/26309/files#diff-14892775e0e3fef8e426c0a2a08889cba026b8b6c2c4c3743e6c51f03b97a2abR22) and according to Christine this is preferred to deleting the file (so folks can still run it locally if they wish). So closing this out.
