### ISSUE TITLE
CH 36 Log Update for DataDog Dashboard

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#67879]
## Issue Description
We need a way to identify three states of a claim submission. We want to capture when a claim submission begins, when it fails, and when it succeeds. 

Documentation on failure points: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1268

## Tasks
- [ ] Refactor worker job to implement wrap_with_logging method
- [ ] Update unit tests to test each state of a claim submission and claim attachment upload
- [ ] Implement sidekiq_retries_exhausted() for all of the cases where we run sidekiq jobs.  Example [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/sidekiq/decision_review/submit_upload.rb#L18).

## Acceptance Criteria
- [ ] Datadog logs exist that capture when a claim submission upload has begun
- [ ] Datadog logs exist that capture when a claim submission upload has failed
- [ ] Datadog logs exist that capture when a claim submission upload has succeeded
- [ ] Datadog logs exist that capture when a claim attachment upload has begun
- [ ] Datadog logs exist that capture when a claim attachment upload has failed
- [ ] Datadog logs exist that capture when a claim attachment upload has succeeded
- [ ] sidekiq_retries_exhausted() implemented for all sidekiq jobs
- [ ] All logs include user id and claim submission id.
- [ ] Attachment upload logs should also include the attachment id
