### ISSUE TITLE
Implement Lighthouse Service for BGS vnpPtcpntAddrsCreate

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#6788]
## Goal
One of the first BGS steps in submitting the 686 is the BGS `vnpPtcpntAddrsCreate` service.
- Build an API that communicates with BGS and calls the `vnpPtcpntAddrsCreate` service.  
- Migrate this functionality from eBenefits to VA.gov so users will no longer have to login to eBenefits to update their dependents.

## Tasks
- [x] Build and configure a dependents service within `lighthouse-bgs` that calls the `vnpPtcpntAddrsCreate` service from BGS
- [x] Submit a PR to update the lighthouse-bgs gem version in `vets-api` (_may wait until all are compiled together_)

## Considerations
- This assumes connectivity/access is granted for this particular service
- There will be more of these as they relate to the different vnp tables

## Acceptance Criteria
- [x] Successfully send a request to the BGS `vnpPtcpntAddrsCreate` endpoint and receive a response from BGS
