### ISSUE TITLE
COE Log Update for DataDog Dashboard

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#67880]
## Issue Description
We need a way to identify three states of a claim submission. We want to capture when a claim submission begins, when it fails, and when it succeeds. 

Documentation on failure points: https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/lgy/coe

## Tasks
- [ ] Refactor worker job to implement wrap_with_logging method
- [ ] Update unit tests to test each state of a claim submission and claim attachment upload
- [ ] Implement sidekiq_retries_exhausted() for all of the cases where we run sidekiq jobs. Example [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/sidekiq/decision_review/submit_upload.rb#L18).

## Acceptance Criteria
- [ ] Datadog logs exist that capture when a claim submission upload has begun
- [ ] Datadog logs exist that capture when a claim submission upload has failed
- [ ] Datadog logs exist that capture when a claim submission upload has succeeded
- [ ] Datadog logs exist that capture when a claim attachment upload has begun
- [ ] Datadog logs exist that capture when a claim attachment upload has failed
- [ ] Datadog logs exist that capture when a claim attachment upload has succeeded
- [ ] sidekiq_retries_exhausted() implemented for all sidekiq jobs
- [ ] All logs include user id and claim submission id.
- [ ] Attachment upload logs should also include the attachment id

**Comment by DLarson-Oddball** [comment]
@tblackwe I used [this view](https://vagov.ddog-gov.com/logs?cols=host%2Cservice&ff_display=a%2Cb&index_a=%2A&index_b=%2A&messageDisplay=inline&query_a=%22COE%20claim%20submitted%20to%20LGY%22&query_b=%22COE%20application%20submission%20failed%20with%20http%20status%22&refresh_mode=sliding&stream_sort=desc&viz=timeseries&from_ts=1698338417862&to_ts=1698943217862&live=true) in Datadog to visualize the submission and failure rates for coe claim submissions. Digging into the failure logs, all failures indicated we receive a 403 when trying to send the claim to lgy.
