### ISSUE TITLE
Pension Team Sprint 6 Plan: 10/25/2023—11/07/2023

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#67890]
## Sprint 6: 10/25/2023—11/07/2023

- Outages (PTO, holiday, or unplanned): 
-- October 25, 26, 27: Coforma team members out for company event.
-- Nov 7: Coforma holiday (Election Day)
- [Temporary task tracking](https://docs.google.com/document/d/1RNaiFAjCijw3YKw8-IoDoG0dvgWAUIaJgONnOvzUQFU/edit?usp=sharing) for team members without access to Zenhub yet.

## Sprint themes:

- Identifying research efforts and analytics opportunities
- Incorporating design feedback from CAIA into designs for Pension form MVP relaunch
- Kickoff collaboration efforts between design and engineering for Pension form MVP relaunch
- Engineering discovery into setting up alerting processes for VA.gov and VBA

## Goal(s):
**Product**
- [x] Discovery to prepare for collaboration cycle mid-point review #67635

**Research/Design**
- [x] (Jamie) Collaborate with VA on research priorities #67961
- [x] (Jamie) Inquire with Platform about desired Pension analytics #67634
- [x] (Jamie) Discovery to identify stakeholders involved in claim processing & roles #67008
- [ ] (Maya) Incorporate additional design, a11y feedback from CAIA #66966 **- rolling into Sprint 7**
- [x] (Maya/Vicky) Schedule/hold Pension MVP design demo for Engineering #67632

**Engineering**
- [x] Become familiar with current Pension form schema & upcoming form component updates #68382 
- [x] Discovery for setting up alerting of failed submissions #67605
- [ ] Discovery for setting up alerting and monitoring in Datadog #66512 **- rolling into Sprint 7**
- [ ] Pension Log Update for DataDog Dashboard #64938 **- rolling into Sprint 7**
- [x] Review findings regarding ITF and define next steps #68346
- [x] Research use of Lighthouse Benefits Intake API on 526 Form #68483
- [ ] (Matt) Review findings regarding Lighthouse & determine transition value for MVP relaunch #68306

## Added to sprint post planning
**Engineering**
- [ ] [MVP] Step 1 Claimant/Vet Info: Add new question, Add VA File Number #68553 **- Mostly done but pending answers to questions raised by Maya/Todd**

**Research/Design**
- [x] (Maya) Draft copy changes for Pension deactivation including QuickSubmit #68731

**Comment by aplatt-coforma** [comment]
@vbellissimo - I noted that #67631 is backlogged due to sprint reprioritization. Should we take it off of the list altogether?

**Comment by vbellissimo** [comment]
@aplatt-coforma Yes. In an effort to clean this up from last week, I removed it from this list. Thank you.
