### ISSUE TITLE
SPIKE | Unable to find_regional_offices Error

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#67902]
## Tasks
- [ ] Research the root causes of: `Unable to find_regional_offices: <detail>`
- [ ] Reproduce error in Development or Staging

[Sample Error](https://vagov.ddog-gov.com/logs?query=%40message_content%3AUnable%5C%20to%5C%20find_regional_offices%2A%20&cols=%40payload.icn%2C%40payload.centralmail_uuid%2C%40payload.saved_claim_id&index=&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=time%2Casc&viz=stream&from_ts=1695059705640&to_ts=1697651705640&live=true)

## Acceptance Criteria
- [ ] Root cause documented
- [ ] Follow-on ticket created

**Comment by tfink419** [comment]
This appears to be due to network/server error similar to https://app.zenhub.com/workspaces/benefits-dependents-experience-6459139e7d64bf0015f6af13/issues/gh/department-of-veterans-affairs/va.gov-team/67525
