### ISSUE TITLE
[Design] Create Registration Presentation for HEC

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#67928]
## Issue Description
Create a presentation / visual story to help with the conversation around registration reasons and eligibility reasons overlap for the registration impact for Veterans on the 10-10EZ.

---
## Tasks
- [x] Create a presentation telling a story/stories from the Veteran perspective of the various registration/enrollment reasons overlap
- [x] Draft the presentation and review with the team
- [x] Make any adjustments as needed

## Acceptance Criteria
- [x] Present during bi-weekly meeting with stakeholders
---

**Comment by jessicastump** [comment]
Working Google slides doc - [link here](https://docs.google.com/presentation/d/1mF9TZU68cgHZas8KB1CBmxeAaB7jnJEijaCLGdbh7qk/edit?usp=sharing)

**Comment by jessicastump** [comment]
Here is the [link to the updated file](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698095358009/d0ef13cb91a187b43d2826b2d058d41d143866ef?sender=uadf1ed7fe7c76f0914967329) - we decided to use Mural to present to HEC

**Comment by jessicastump** [comment]
[Registration - October 25 Walkthrough_2023-10-25_18-37-52.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1Z4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--db492be471c4c5b2dbf49f67075251e48f8996d2/Registration%20-%20October%2025%20Walkthrough_2023-10-25_18-37-52.pdf)
This was sent to those emails on HEC meeting invite as follow up.
