### ISSUE TITLE
[bug spike] HLR | Invalid timezone 422 error

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#67940]
On Oct 18, 2023, we saw a 422 error on the HLR submission endpoint. [Sentry](http://sentry.vfs.va.gov/organizations/vsp/discover/platform-api:cdaa0a372866443087f9cd8a4e50fd78/?environment=production&field=title&field=release&field=environment&field=user.display&field=timestamp&name=Common%3A%3AClient%3A%3AErrors%3A%3AClientError%3A+the+server+responded+with+status+422&project=3&query=issue.id%3A197180&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1) shows the following error message: `America/Ciudad_Juarez' is not an available option` with `source.pointer: data/attributes/veteran/timezone`

## Tasks
- [ ] Determine root cause of error
  - [ ] Probably need to bring this to the attention of Lighthouse, who may need to update their list of timezones to match what browsers currently list which we fetch with `Intl.DateTimeFormat().resolvedOptions().timeZone`.
- [ ] Create plan for resolution
- [ ] Think about whether short-term intervention is necessary/feasible
- [ ] After discovery complete, add estimate, remove `needs-refinement` and `needs-estimate` labels, remove `[bug spike]` prefix in the title of this PR, and update these tasks and AC, DoR, and DoD below.

## Acceptance Criteria
- [ ] Root cause of error is known
- [ ] Can reproduce 422 error locally (and if possible, on staging)
- [ ] Bugfix complete and works locally (and if possible, on staging)
- [ ] Bugfix deployed

## Definition of Ready
- [ ] Root cause of error is known

## Definition of Done
- [ ] Acceptance criteria met
- [ ] Veteran has been notified of bugfix by contact center.

**Comment by Mottie** [comment]
[Reported to Lighthouse in Slack](https://dsva.slack.com/archives/CKUCFQAHJ/p1698236733888439?thread_ts=1698083531.827299&cid=CKUCFQAHJ)

**Comment by Mottie** [comment]
Lighthouse is still [actively looking into fixing this issue](https://dsva.slack.com/archives/CKUCFQAHJ/p1698434572130629?thread_ts=1698083531.827299&cid=CKUCFQAHJ).

**Comment by Mottie** [comment]
Lighthouse now has a [PR to update their list of timezones](https://github.com/department-of-veterans-affairs/vets-api/pull/14328)

**Comment by data-doge** [comment]
May need to update NOD schema that may use LH's old timezone schema. @Mottie

**Comment by data-doge** [comment]
LH's PR merged today. After today's deploy, we can test whether it works locally / staging (if we can set intl.timezone really easily), and if that works, then we can reach out to the affected Veteran via Kimberley.

**Comment by data-doge** [comment]
Closing in favor of #70429
