### ISSUE TITLE
[spike] DR | Benchmark logging for KPIs

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#67946]
## Issue Description

Eventually, it would be nice to include benchmark logging for our KPIs, that measure how long requests to our third party services take. This ticket is a spike ticket to figure out how best to do that.

---
## Tasks
- [ ] Perform technical discovery and determine best way to implement benchmark logging for our KPIs.
- [ ] Create follow-up development ticket.

## Acceptance Criteria
- [ ] Other engineers agree with proposal for benchmark logging.
- [ ] Follow-up development ticket created

## Definition of Ready
N/A

## Definition of Done
- [ ] Acceptance criteria met.
