### ISSUE TITLE
[BE] 10-10CG - eMIS Deprecation: Remove unused code referencing eMIS

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#67941]
## Background
eMIS is being deprecated, and any teams that call eMIS for Military information will need to migrate to using VA Profile.  Any code that calls eMIS needs to be updated to call VA Profile.
Since our work migrated to VA Profile earlier this year, we have no further changes to make.  However, we do have some unused code referencing eMIS for the 10-10CG.

Lindsey Hattamer suggested:
>I believe the only change you will have to make is [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/services/form1010cg/service.rb#L211) to reference the [new VaProfile service](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/va_profile/veteran_status/service.rb)

## Tasks
- [ ] Make updates to the Dev environment
- [ ] Make updates to the Staging environment
- [ ] Complete any testing needed to ensure a successful update
- [ ] Tag Lainey Trahan, Lindsey Hattamer and Heather Justice, once the updates and testing is completed
- [ ] Deploy changes to Prod

## Acceptance Criteria
- Updates to Dev and Staging have been made and testing is completed successfully

**Comment by alexseelig** [comment]
Alex follow up with Lindsey Hattamer and Lainey Major

**Comment by hdjustice** [comment]
After some additional review and a question from Rebecca/Platform team about some emis comments on the file, Lihan determined there are some more changes we can make to remove emis references.
Re-opening ticket for future effort.
