### ISSUE TITLE
[Design] Nametag: Design Space Force logo into Nametag

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#67953]
## Background
We have received a logo to use for the Space Force seal within the Nametag. We need to create a design for this.

- Space Force does not have a round emblem like the other branches. 
- We have been instructed to use the delta logo against a dark background. 
- We'll likely use the one with the USSF abbreviation.

(Logo images attached below)

## Tasks
- [x] Create design incorporating guidance from Samara and mobile team
- [x] Review with PO
- [ ] ~Share with Design System team via [2214](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2214)~ Samara removed this as a requirement 
- [x] Samara to share with DoD contact

## Acceptance Criteria
- [ ] Design exists for nametag that incorporates the Space Force logo and is consistent for VA.gov and mobile

## Logo images
USSF Vertical W (click to view)
![USSF_Vertical_W](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/b1c3ce82-e783-487d-a167-d53f3c474091)

Space Force Vertical W (click to view)
![SpaceForce_Vertical_W](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/f816affe-2803-4212-b78a-ddbc26c9037b)

**Comment by Samara-Strauss** [comment]
I've actually asked DoD for a few other versions of the logo for Angela to play with. I'll share those once I have them.

**Comment by Samara-Strauss** [comment]
@aagosto90 here are the additional logos to play with.

![SpaceForce_Vertical_Gradient_RGB](https://github.com/department-of-veterans-affairs/va.gov-team/assets/34068740/5b6d73b0-b92b-40b6-bf34-5982441b7024)
![USSF_Vertical_Gradient_RGB](https://github.com/department-of-veterans-affairs/va.gov-team/assets/34068740/bec10034-2548-4a0a-be4a-964f757bcf46)
![SpaceForce_Vertical_Flat_RGB](https://github.com/department-of-veterans-affairs/va.gov-team/assets/34068740/dbe3d1dc-d9d5-4e55-9af0-98a5515173fd)
![USSF_Vertical_Flat_RGB](https://github.com/department-of-veterans-affairs/va.gov-team/assets/34068740/196a8505-2343-46f2-8ada-42f4860b25a4)

**Comment by Samara-Strauss** [comment]
Once we decide which version of the Space Force logo to use, [we need to share it with the design system team in this ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2214).

**Comment by aagosto90** [comment]
Hey @Samara-Strauss ! Excited to finally be getting around to this.
Here's a [Sketch file](https://www.sketch.com/s/225eebbb-fb9a-42db-8655-75c30a9dc935/p/F3726C96-BBFF-4F08-BB3C-EACB9F8C5FFB/canvas) where I've mocked up a bunch of options. I tried each logo that you provided on a black background and then the color logos on a white background too. The 2 alt and 3 alt options look barely different than the other 2 and 3 options but they're using a very dark blue color from the Space Force seal instead of black as a background. For VA.gov on mobile, we would just write out the branch as shown but for the app, we may want to consider how tiny the font will be for options where the branch is spelled out instead of abbreviated. However, we use the official seals for all other branches and those aren't really legible at a small size either so I think the most important thing here is using the correct official graphic and it being recognizable to Veterans.

Now for my recommendation! Since we're using seals for the other 4 branches, I really think it's preferable to use the Space Force seal if we're allowed to here. I found guidance on the [USSF website](https://www.spaceforce.mil/About-Us/About-Space-Force/USSF-Symbols/) that the seal is only to be used for authorized official use so we definitely need approval (maybe from your DoD contact?) but since we're using the seals for the other branches and we are VA.gov I would assume this is an appropriate application for the seal.

Let me know your thoughts @Samara-Strauss and @ajakabcin ! CC @andaleliz @pamela-drouin 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMCtEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1a279c232ffc0c1df16b8af60acb74ec822b2fac/Screenshot%202023-10-30%20at%2011.29.36%E2%80%AFAM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUtEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--896aae9225dc52b2b3e504a1f5181201c97e2726/Seal_of_the_United_States_Space_Force.svg.png)

**Comment by Samara-Strauss** [comment]
@aagosto90 can you send a public link for that Sketch file? I'm getting a message that I don't have permission to view.

> ![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/34068740/3dfcaa37-d509-4182-b1d9-e6092e6f921a)

So this gets into very annoying nuances between a seal, an emblem, and a logo. To my understanding, this is how the DoD uses those terms:

- A seal is an official symbol for a branch that can only ever be used in an official capacity by DoD.
- An emblem looks similar to a seal, but it is allowed to be used outside of official capacity by DoD. On the VA website, we are using emblems -- not seals -- for the other four branches.
- A logo is, well, a logo.

The problem here is that Space Force has an official seal -- which we are not allowed to use -- and a logo, which is what I attached above. Unfortunately, they do not have a circular emblem, hence why we're playing around with logo treatments.

>  tried each logo that you provided on a black background and then the color logos on a white background too.

Can you mock this up in the nametag? If it's not possible because the logo doesn't work because it's not circular, let me know. We might have to forego a logo in that case.

**Comment by aagosto90** [comment]
Oh wow, thanks so much for the explanation Samara and the doc! I had no idea and this is super helpful.

Try the [Sketch file link](https://www.sketch.com/s/225eebbb-fb9a-42db-8655-75c30a9dc935/p/F3726C96-BBFF-4F08-BB3C-EACB9F8C5FFB/canvas) again - I think I've updated the sharing permissions so you should be able to see it now but let me know if you have any trouble. So knowing what I know now, I wonder if a Space Force emblem is in the works, and if so we should probably replace the logo with that in the future.

As for a design for the nametag, I would probably recommend option 5 alt which is the white circle with the color USSF logo because that one will be easiest to read and I assume most recognizable to Veterans. Generally my graphic design rule of thumb is to use a full color logo whenever possible and only use the grayscale version when necessary. What do you think @Samara-Strauss?

**Comment by Samara-Strauss** [comment]
> I wonder if a Space Force emblem is in the works, and if so we should probably replace the logo with that in the future.

It's not, from what I understand.

> I would probably recommend option 5 alt which is the white circle with the color USSF logo

Agreed. This looks great.

One favor: Can you take out the exploration with the official seal? Once you do that, I want to run this decision by Ryan Thurlwell.

**Comment by aagosto90** [comment]
@Samara-Strauss Done! And [here's a direct link to the option that we both like best](https://www.sketch.com/s/225eebbb-fb9a-42db-8655-75c30a9dc935/a/mPwL2vg).

**Comment by Samara-Strauss** [comment]
@rtwell @timwright12 @jessicawoodin @drjecker can I ask for your review of Angela's proposal for the Space Force logo?

- This is our recommendation -- [the full color logo placed on a white circle](https://www.sketch.com/s/225eebbb-fb9a-42db-8655-75c30a9dc935/a/mPwL2vg).
- If you do not like this option [here are her other iterations](https://www.sketch.com/s/225eebbb-fb9a-42db-8655-75c30a9dc935/p/F3726C96-BBFF-4F08-BB3C-EACB9F8C5FFB/canvas).

Please let us know what feedback you have, and thank you!

**Comment by ajakabcin** [comment]
Moving to "validate" while we wait for feedback from @rtwell @timwright12 @jessicawoodin @drjecker

**Comment by rtwell** [comment]
@Samara-Strauss & co — I'm good with the option you proposed (although i dont mind the inverted version you made as well).

**Comment by Samara-Strauss** [comment]
Thanks, @rtwell!

@ajakabcin -- I'm going to send this over to DoD to see if they are OK with the treatment Angela came up with. I'll keep you posted. If they are OK with it, we'll need a file of the logo in the white circle to send over to the design system folks.

**Comment by Samara-Strauss** [comment]
Good news! My contact at DoD approved @aagosto90's mockup. 

Next steps:

1. @ajakabcin this is ready to go into build!
2. I actually don't think we need to post anything in [2214](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2214) at this time. [Once the Space Force logo has been added to here](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/site/assets/img), we should give Matt Dingee and the mobile team a heads-up.

Let me know if you have any questions!

**Comment by ajakabcin** [comment]
[I let Matt Dingee know that the emblem is available ](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2214#issuecomment-1815283611) so I believe we can close this!
