### ISSUE TITLE
[Sprint Goal] IPP - Prepare LHDI Environments for Application Deployment

### ISSUE THREAD

**Issue by porta-antiporta** [department-of-veterans-affairs/va.gov-team#67957]
# Scope

Deploy an application (intake application) to an LHDI environment

# Context 

As part of our AoA on where our proofing application(s) will live we need to better understand (discovery) on LHDI. 

# Tasks (to be made into tickets)

- [ ] Gain an account to LHDI
- [ ] Create a repo in VA org for our application
- [ ] Decide FE architecture of app to be deployed
- [ ] Decide whether to create a "Hello world" application, or choose the Intake or Proofing Agent application to deploy to a LHDI QA environment
- [ ] Update repo with readme
- [ ] Case ID can be either hardcoded, random number generated etc.

# Acceptance criteria
- [ ] Active in LHDI slack
- [ ] Establish points of contact for LHDI owners

# Demo goal

- Pipeline deployment on LHDI

**Comment by porta-antiporta** [comment]
- Tasks made into tickets
- Some tasks updated/OBE based on what was in the LHDI onboarding manual

**Comment by rdvyas** [comment]
All tasks are closed for LHDI deployment. Closing this EPIC.
