### ISSUE TITLE
[Research] Create TreeTest to use in Registration Reasons Study

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#67963]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

Documentation:
[Optimal Workshop login credentials](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/design/tools/optimal-workshop.md) (now stored in the sensitive repo) - Use Health Experience Research Account
[Getting access to Optimal Workshop](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-OptimalWorkshop) on the Platform website will be updated with instructions

- [Mural room](https://app.mural.co/t/departmentofveteransaffairs9999/r/1672351979079) - VA.gov Information Architecture

- [Research Folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/research/2023-11-Registration%20Reasons%20Tree%20Test)

---
## Tasks
- [x] Have tree for VA.gov created in Optimal Workshop
- [x] Create introduction facing content 
- [x] Write tasks for test
- [x] Create follow up questions for each tasks
- [x] Test internally and review for any adjustments
- [x] Launch test

## Acceptance Criteria
- [x] The tree test is ready when submitting plan to Research Review/recruitment
---

**Comment by jessicastump** [comment]
[First link](https://dj540s05.optimalworkshop.com/treejack/io60v1go) for proofing / testing the tree to use. Includes first draft of tasks.

**Comment by jessicastump** [comment]
Tree test approved and launched, ready to submit to repo.
