### ISSUE TITLE
Fix InProgressForm `not_submitted` scope

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#67968]
## Description
The `not_submitted` scope on the InProgressForm model is broken, it doesn't work. Fix it.

## Tasks
- [ ] Fix it.

## Acceptance criteria

- [ ] Running `InProgressForm.not_submitted.length` on a prod console should actually work, and not break.

## Testing
- [ ] Confirm Acceptance criteria manually 
- [ ] Adjust existing specs if present

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>
