### ISSUE TITLE
[SW 2.0 - PI4/23] Streamlined Waiver 2.0

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#67964]
### Description
As part of the President's initiative to support Veterans experiencing financial hardship we are simplifying the process for claiming medical debt forgiveness by streamlining the request process and offering instant determination for Veterans who meet the criteria.

The 2.0 work will consist of the discovery items identified in the MVP research that was not included in the MVP release.

### Scope of release:

All current identified work not included for the MVP release.

### Out of Scope:

Newly identified work that comes out of current research and enhancement requests. All that should still be collected and placed under a 3.0 Epic.

### Additional Details/Notes (optional):
*Any other relevant information about this project not already listed above*

### Artifacts
-Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/streamlined_waiver/product_outline.md

### Collab Cycle Touchpoints
- [ ] **Kickoff**  (Collab Cycle Ticket) ENTER TICKET #
- [ ] **Design Intent** ENTER DATE & TIME / ENTER TICKET #
- [ ] **Sitewide Content & Information Architecture (IA) Intake Request** ENTER TICKET #
- [ ] **Research Plan Review** ENTER TICKET #
- [ ] **Analytics Request** - (Submit once KPI's are determined) ENTER TICKET #
- [ ] **Midpoint Review** Scheduled for ENTER DATE & TIME
- [ ] **Contact Center Review** (Submit tix 2 weeks prior to launch) ENTER TICKET #
- [ ] **Staging Review**  (Reminder: Staging Reviews require a 4 day lead time)_Scheduled for ENTER DATE & TIME
- [ ] **Privacy and Security, & Infrastructure Review** ENTER TICKET #

**Comment by Tom-Davis** [comment]
Closing as all work is complete.
