### ISSUE TITLE
DR | Fix disabled unit & e2e tests

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#67960]
## Value Statement
**_As a_** developer
**_I want to_** know that our unit & end-to-end tests are being run in CI
**_So that_** I can be sure that test coverage is maintained

## Background Context

Platform has set up CI to run stress tests on e2e tests to determine if a test is flaky. Once flagged as flaky, the test is added to a "disallowed" list and the e2e test is then skipped in CI. A [list of disallowed tests is maintained](https://depo-platform-documentation.scrollhelp.site/developer-docs/currently-disallowed-cypress-test-specs-on-va-gov) in the developer documentation, and periodically announced in the `#vfs-all-teams` Slack channel.

Starting 11/6/2023, [PRs with disallowed unit & e2e tests will be blocked from being merged](https://dsva.slack.com/archives/CE4304QPK/p1697562278492779).

## Acceptance Criteria

- [ ]  Fix unit tests shown on the [disallowed unit test page](https://depo-platform-documentation.scrollhelp.site/developer-docs/currently-disallowed-unit-test-specs-on-va-gov)
- [ ] Fix e2e tests shown on the [disallowed e2e test page](https://depo-platform-documentation.scrollhelp.site/developer-docs/currently-disallowed-cypress-test-specs-on-va-gov)
- [ ] All tests passing

## Tasks
- [ ] Review disallowed unit tests page
- [ ] Fix unit tests or manually skip flaky unit tests
- [ ] Review disallowed e2e tests page
- [ ] Fix e2e tests

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
- Work to get the 3 e2e tests that are on the disallowed list have been completed, but the disallowed list isn't updating. I've reached out to platform and they have pushed out some fixes. We need to [wait until Oct 31](https://dsva.slack.com/archives/CBU0KDSB1/p1698424585368959?thread_ts=1698419766.515439&cid=CBU0KDSB1) to see if the tests have been removed.
  > Lets hold until the overnight scan runs Monday and let it do its updating as expected. If those tests are fixed, they should get reenabled by the process automatically
- Work to fix the flaky unit test is awaiting code review.
- Work to add Supplemental Claim keyboard-only e2e tests are in progress

**Comment by Mottie** [comment]
* The flaky unit test has been removed from the disallowed list 🎉 
* The Supplemental Claim e2e test appear to continue to fail the stress tests 😿 
* For the keyboard only tests, we're still waiting on [this test to finish it's overnight run](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/6701148417/job/18208377336) (going on 13+ hours now) before the disallowed list is updated

**Comment by saderagsdale** [comment]
@anniebtran @Mottie any update on the failing tests?

**Comment by anniebtran** [comment]
@saderagsdale the PR above has been approved and just needs to be merged, i think. not sure if it'll re-enable the flaky test but seems to be passing cleanly on the branch

**Comment by Mottie** [comment]
The PR has just been merged. I think we need to wait until the daily run (I think at 5 PM daily) before the test is removed from the disallowed list

**Comment by Mottie** [comment]
Today is the deadline, and I'm not seeing any of our apps on the disallowed [e2e](https://depo-platform-documentation.scrollhelp.site/developer-docs/currently-disallowed-cypress-test-specs-on-va-gov) and [unit test](https://depo-platform-documentation.scrollhelp.site/developer-docs/currently-disallowed-unit-test-specs-on-va-gov) lists 🎉

**Comment by saderagsdale** [comment]
Woot!!! 🎉🤸😝
