### ISSUE TITLE
(Jamie) Collaborate with VA on research priorities

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#67961]
## Issue Description
As a Pension team with documented areas of research efforts,
we need to share our findings and recommendations with VA stakeholders,
so that we can collaborate to align on our research priorities.

---
## Tasks
- [x] Reach out to VA stakeholders via Slack
- [x] Set up call with VA enabling team to present the identified areas for research; meeting with VA on Oct 25
- [x] Collect, document any feedback provided to us by them

## Acceptance Criteria
- Pension team will have met with VA stakeholders to present identified areas for research and documented next steps based on feedback provided by them.
