### ISSUE TITLE
Document Steps to Record Betamocks Responses

### ISSUE THREAD

**Issue by gia-lexa** [department-of-veterans-affairs/va.gov-team#67978]
## Issue Description
In response to this [recent ticket](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/67430), it was determined that our documentation needs to be updated to include further details explaining how to record an API response using Betamocks.

---
## Tasks
- [x] Walk through of existing steps found in Betamocks Readme, create a list of clarifying questions
- [x] Reach out to experienced user 

## Acceptance Criteria
- [x] Create accurate, actionable instructions that will allow us to record Betamocks responses
- [x] Ensure they're added to the Betamocks Readme

**Comment by LindseySaari** [comment]
On hold temporarily but checking with Tom Harrison.

**Comment by laineymajor** [comment]
Reaching out to tom today..

**Comment by laineymajor** [comment]
Closing. Thanks @gia-lexa !
