### ISSUE TITLE
Design Intent - Design Feedback - Benefits Non-Disability, Burial 530, Form Reactivation

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#67982]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Matt Dingee: Kudos for adding the form fields rather than disabling the form. Would love to know how this goes.
- Matt Dingee: There is an [API](https://hub.lighthouse.va.gov/catalog/default/API/veteran-service-history-and-eligibility-v2/api-spec) that may allow users to get the DD214 info instead of having them upload it. It may not have complete information so double check that.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

-

**Comment by fiorella-io** [comment]
Thank you for bringing up the API. We'll explore how we can connect with the API and there will be a engineering spike ticket created to explore how to do that.
