### ISSUE TITLE
Design Intent - Accessibility Feedback - Benefits Non-Disability, Burial 530, Form Reactivation

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/va.gov-team#67984]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Everything looked good. It's great to hear that you incorporated feedback from a previous design intent and are moving towards the "one thing per page" pattern. That is just reiterated in the feedback here as a "should", but it sounds like the team is on the right track.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Should:** Wherever possible, try to use a "one thing per page" approach (which you mentioned you are doing, so that is good to see) rather than any sort of conditional display of information or form fields. There are a handful of situations where conditionally revealing new things makes sense, but usually breaking things into separate pages helps with cognitive load (keeps focus on a particular task) and avoids some tricky assistive technology interactions.
        - As mentioned in the meeting, some small ones that are tightly coupled together are usually fine. And as Matt said, when it does come time for coding, you will want to make sure any new information is correctly announced for assistive technology users.
