### ISSUE TITLE
Design | CH 36 | Replace Wizard Pattern

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#67999]
## Issue Description
_CAIA #63702 recommended that the depreciated wizard pattern be replaced by the following suggested solution:_

Ch 31 has the same issue (see #68008).

### Staging or Production Link
- [Staging Link](https://staging.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-25-8832/introduction)

### Prototype & Designs
- [Mural User Flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1691434304975/3f0c405c820c184d21393b3bbd76324a5ee7c677?sender=u0e8ac1d6d7681bb7e1b80558)
- [Ch 36 PCPG designs](https://www.figma.com/file/DEnVQXRrNvwJ3UkKkYYJ1Q/Ch-36-Redesign?type=design&node-id=1%3A4&mode=design&t=niClq2OBhoN1NUXl-1)

### Test Users
- vets.gov.user+24@gmail.com
- [staging test user repository](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)

### Long-term solution
As mentioned in the Design System [wizard pattern](https://design.va.gov/patterns/wizards) page, the [Wizard pattern is now deprecated](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/399) and replaced by the the [help users complete a sub-task pattern](https://design.va.gov/patterns/help-users-to/complete-a-sub-task). 

There are many accessibility defects related to the wizard pattern, as described [here](https://design.va.gov/patterns/wizards#retrofit-this-pattern).

We highly recommend that you use the sub-task pattern instead of the wizard pattern to avoid this accessibility issue and reduce the user's cognitive load.

## References, articles, or WCAG support

1. [Focus management example](https://staging.va.gov/decision-reviews/supplemental-claim/file-supplemental-claim-form-20-0995/start)
2. Reduce cognitive load by having [one thing per page](https://www.gov.uk/service-manual/design/form-structure#start-with-one-thing-per-page)
3. [How to retrofit the wizard pattern, if you absolutely must keep it](https://design.va.gov/patterns/wizards#research-and-accessibility-rationale)
---
## Tasks
- [x] Create design solution to replace the depreciated wizard element
- [ ] Obtain CAIA approval

## Acceptance Criteria
- [x] Sketch file of solution
- [ ] Assign to Laura who will create follow-on engineering ticket
---

**Comment by fiorella-io** [comment]
We need to design a whole new experience for this issue. If we're using T-shirt size, I would say this issue is a Medium, if we're using Fibonacci it'll be a 6

**Comment by fiorella-io** [comment]
I created new designs linked in this story
