### ISSUE TITLE
Documentation Style Guide + Training

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#67993]
## Description 
This ticket will house the task of creating documentation explaining how to make organized and easy-to-read documentation. 

---

## Definition of Done
Tasks below are complete.

---

## Tasks 

- [x] Write documentation around best practices for Confluence
- [x] Training with team on how to present documentation in Confluence
- [x] Send to team to review
- [x] Publish 
- [x] Communicate through proper channels and demo

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Set to demo 12/6. Closing!
