### ISSUE TITLE
Design | CH 31 | Wizard Redirect Alert

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#68010]
## Issue Description
_CAIA feedback on this issue is in #64688._

### Staging or Production Link
- [Staging Link](https://staging.va.gov/careers-employment/vocational-rehabilitation/apply-vre-form-28-1900/start)

### Prototype Link
- [Mural User Flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684161597392/5c1f8869cf5d03b792c8b82cf19b39dc26c486c2?sender=u0e8ac1d6d7681bb7e1b80558)

### Test Users
- vets.gov.user+24@gmail.com
- [staging test user repository](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)

### Details
This alert is odd, the wizard information isn't saved anyway... the alert says to finish applying but you answer one more question and then you are required to log in. This creates a very frustrating pattern for the Veteran who wanted to sign in earlier. This should follow the same pattern as [VA form 28-8832](https://www.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/introduction), where you click "Sign in" and go straight to the Log in modal, without a "you'll lose your progress" prompt
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/77993286/bc501cc1-96df-4c10-ac39-0742fe628c8b)

### Reproduction steps
1. Be on wizard screen
2. click log in button

### Proposed solution or next steps
Remove alert prompt and allow users to sign-in even when wizard is partially complete.

---
## Tasks
- [ ] Design solution to remove alert prompt and allow users to sign-in even when wizard is partially complete.
- [ ] Obtain CAIA approval.

## Acceptance Criteria
- [ ] Sketch file of design.
- [ ] Assign to Laura Steele to create follow-on engineering ticket
---

**Comment by juliepedtke** [comment]
Copying over a comment from Laura: I was taking a closer look at the CH 31 wizard and form, and there does not appear to be an option to fill out the form unauthenticated (only the wizard), so I think we can follow CAIA's suggestion and remove the alert prompt entirely.

I (Julie) agree with this approach!

@Midge-dev to take a look to see if this is easy to remove!

**Comment by fiorella-io** [comment]
@steele-lm This doesn't need design. We just need to remove this modal when someone has started or is midway into this wizard and decides to click  "sign in" at the top of the page. I've updated the design of the wizard but even if they are halfway through the new wizard design, we still need to remove this behavior from happening.

**Comment by fiorella-io** [comment]
@steele-lm This doesn't need design. We just need to remove this modal when someone has started or is midway into this wizard and decides to click  "sign in" at the top of the page. I've updated the design of the wizard but even if they are halfway through the new wizard design, we still need to remove this behavior from happening.
