### ISSUE TITLE
CH 31 | Link URL

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#68014]
## Issue Description
_CAIA issue description #64122._

### Details
In the Privacy Act Statement, there's a URL that isn't linked:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135633989/c91e50cb-9168-4568-9d35-ffb4e7f22119)

URLs need to be actionable and tell the user where the link is taking them, according to the [content style guide](https://design.va.gov/content-style-guide/links#linking-to-external-sites).

### Reproduction steps
1. Go to [this page](https://staging.va.gov/careers-employment/vocational-rehabilitation/apply-vre-form-28-1900/introduction)
2. Click on "Apply for Veteran Readiness and Employment with VA Form 28-1900"
3. Scroll to the bottom and click on "Privacy Act Statement"
4. A modal will open - look for the unlinked URL

### Proposed solution or next steps
Change the sentence that begins "Valid OMB control numbers can be...."

to 

"Valid OMB control numbers can be located on the [OMB Internet Page (opens in new tab)](http://www.reginfo.gov/public/do/PRAMain)."

### References, articles, or WCAG support
1. [content style guide](https://design.va.gov/content-style-guide/links#linking-to-external-sites)

---
## Tasks
- [ ] Change the sentence that begins "Valid OMB control numbers can be...." to "Valid OMB control numbers can be located on the [OMB Internet Page (opens in new tab)](http://www.reginfo.gov/public/do/PRAMain)."

## Acceptance Criteria
- [ ] Link is updated
- [ ] Text is updated
- [ ] Designer reviews and signs off in staging

**Comment by Midge-dev** [comment]
Commented here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/64122
