### ISSUE TITLE
CH 31 | YouTube iframe embeds are larger than VA minimum breakpoint 

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#68025]
## Issue Description
_CAIA feedback on issue is in #64211._

### Details

In the VR&E Orientation slideshow, there are a few slides with embedded YouTube videos.

Those videos' width are set, inline, as 325px. The [VA's minimum breakpoint]
(https://design.va.gov/foundation/breakpoints) is 320px. At 320px, the video overflows off of the screen.  This is an especially big issue for users that zoom in to 400%. Those users would need to scroll horizontally to see the full video. While it's only off by a few pixels, something could still be cut off for these users.

![Screenshot 2023-08-17 at 4 34 46 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135633989/5433113f-af24-4f0b-9470-3e1b11635033)

### Reproduction steps
1. Go to [the form](https://staging.va.gov/careers-employment/vocational-rehabilitation/apply-vre-form-28-1900/start)
2. In the Wizard component, select "Veteran > Yes > Yes"
3. Scroll down to see the "VR&E Orientation" slideshow
4. Click the "Start VR&E orientation slideshow" button
5. Click "Next slide" until you get to slide 5, where you'll see an embedded YouTube video
6. Resize your browser to 1280px, then zoom in to 400%

### References, articles, or WCAG support
1. [Height and width utility classes](https://design.va.gov/foundation/utilities/height-and-width#responsive-prefixes)
2. [Video links](https://design.va.gov/components/link/#video)
3. [WCAG 1.4.10: Reflow](https://www.w3.org/TR/WCAG21/#reflow)

---
## Tasks
- [ ] Make the video responsive by:
   - [ ] removing the height and width from each embed
   - [ ] adding [height and width utility classes](https://design.va.gov/foundation/utilities/height-and-width#responsive-prefixes) to make the embed auto-size with the container or viewport

## Acceptance Criteria
- [ ] Video is responsive when viewed at the [VA's minimum breakpoint](https://design.va.gov/foundation/breakpoints) of 320px. At 320px.
- [ ] Designer signs-off in staging environment
---

**Comment by steele-lm** [comment]
@zack I created a new ticket that outlines the preferred approach for this issue.
