### ISSUE TITLE
BE | Profile | Direct Deposit | Update Direct Deposit Metrics

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#68028]
## Background
Update logging for the disability controller so that direct deposit updates can be easily identified in Datadog.

Log message should be...
`V0::Profile::DirectDeposits::DisabilityCompensationController#update request completed` 

## Tasks
- [x] Update logging message
- [x] Have someone from vsp-identity team review code.

## Acceptance Criteria
- [ ] Confirm stats in staging environment.
- [ ] Have Joe Niquette review logs in prod and confirm he has what he needs.
