### ISSUE TITLE
Ask VA reporting December 2023

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#68049]
## Issue Description
Ask VA reporting

---
## Tasks
- [ x] _What work is necessary for this story to be completed?_
Compile team reporting data from AVA for December 2023.
## Acceptance Criteria
- [ x] _What will be created or happen as a result of this story?_
Reports will be made available here. Once our team finalizes our AVA reporting requirements with OCTO, reporting numbers/images will appear in a different format.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x ] **Attached to an Epic** (what body of work is this a part of?)
- [x ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by starlow00** [comment]
Have conducted AVA reporting for [September](https://app.zenhub.com/workspaces/contact-center-62cdd9546ec1530018209672/issues/zh/76) and [October](https://app.zenhub.com/workspaces/contact-center-62cdd9546ec1530018209672/issues/zh/147) 2023.

Meeting with Kimberley and Sarifa next week to discuss AVA reporting and possible inclusion of DOMO.

**Comment by starlow00** [comment]
Will compile report for December 2023.

**Comment by starlow00** [comment]
December 2023 reporting for the VACO VA.gov Tech Support team:

<img width="1717" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0NyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82c8ab451dcf36e27b7f7fa99f328e807b882205/Inquiry%20and%20Employee%20Performance2.png" alt="Inquiry and Employee Performance2.png" />

**Comment by starlow00** [comment]
<img width="1717" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1dyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1b5488ff457ed9b81834df8f01d5563b980b791c/Inquiry%20and%20Employee%20Performance2.png" alt="Inquiry and Employee Performance2.png" />

**Comment by starlow00** [comment]
<img width="1717" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2FyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f0f04f897eeb63583b459031ea80efe4b34f1e02/Correspondence%20Items.png" alt="Correspondence Items.png" />
