### ISSUE TITLE
Establish an organized categorization and resolution process for RFIs

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#68041]
## Issue Description
Establish an organized categorization and resolution process for RFIs

---
## Tasks
- [x] _Identify all RFI templates 
- [x] Categorize according to inquiry 
- [x] Create templates with appropriate fields
- [ ] 

## Acceptance Criteria
- [x] _Create folder and store in public repository _
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
