### ISSUE TITLE
Create at a glance reporting for case response time metrics

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#68048]
## Issue Description
_Create at a glance reporting for case response time metrics

---
## Tasks
- [ ] Create and review spreadsheet - 

# Acceptance Criteria
- [ ] Support team approval of the document and posted in confluence
- [ ] 
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by starlow00** [comment]
Meeting with Kim and Sarifa Tuesday 11/7 re. AVA reporting

**Comment by starlow00** [comment]
Met with Kim and Sarifa, pending further review.

**Comment by starlow00** [comment]
AVA reporting process first steps have been defined.

**Comment by ATMiddleton** [comment]
@Kimberley2023-CSM will add documentation.

**Comment by Kimberley2023-CSM** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmJ1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3e6ccf202414b42d94204dec30eeda144eb2b20/MicrosoftTeams-image.png)
