### ISSUE TITLE
Create Outlook Folders for Daily Case Review

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#68047]
## Issue Description
Create definitive folders in shared mailbox: VAVeteransSupport@va.gov.  
As a Veteran Support Representative, I need to have a way to sort and save incoming/reply emails from Veterans seeking assistance via VEO/Salesforce

---
## Tasks
- [x] Determine folder labels
- [x] Create folders
- [x ] Create Outlook rules to direct incoming emails to appropriate folders

## Acceptance Criteria
- [x] Identified Users have access to folders
- [x ] Identified folders are operational
- [x] Outlook rules are operational for incoming emails 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
All email folders have been created and are operational.
