### ISSUE TITLE
Improved time to address or escalate cases

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#68040]
## Issue Description
_Daily, cases are escalated to Veteran Support from VEO via Salesforce.  Veteran Support needs to improve the time it takes to address and close all incoming cases.  The goal is to reduce the amount of time it takes to close cases from the previous baseline of 30 days 

As a Veteran Support representative, I need a procedure to review/route/escalate and track incoming cases so that a record of case journey can be documented and referenced when required.  
---
## Tasks
- [x] _Establish a tracking spreadsheet 
- [x] Create and document daily case review procedure 
- [x] Draft Excel spreadsheet example 

## Acceptance Criteria
- [ ] _Finalize and publish document to Confluence. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
@Kimberley2023-CSM @starlow00 @ATMiddleton met and drafted the Case Review, case responsibility, mail merge example and case journey/flow. 

[Salesforce Flow Chart.pptx]
(https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHpRQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1099dd9579925f85e70e3a3e9e06542a88083b51/Salesforce%20Flow%20Chart.pptx)

[Case Review and Responsibility Final.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDdRQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d83325cd7c50b449e23f264b980b7a73e94202d7/Case%20Review%20and%20Responsibility%20Final.xlsx)
