### ISSUE TITLE
Design a successful Veteran outreach/response email cadence

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#68042]
## Issue Description
_Design a successful Veteran outreach/response email cadence
---
## Tasks
- [x] _Create flowchart describing incoming case journey from arrival to closed status 
## Acceptance Criteria
- [x] _Publish flowchart to support team
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
[Salesforce Flow Chart.pptx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWVNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--79a0f0dbfd00234058a619b3dd445bc17283bc99/Salesforce%20Flow%20Chart.pptx)
