### ISSUE TITLE
Successful procedures for transitioning cases from Tier II to Tier III

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#68043]
## Issue Description
Create Successful procedures for transitioning cases from Tier II to Tier III
---
## Tasks
- [x] _Define the work (discovery) 
- [x] Create a workflow for escalating cases from Tier II to Tier III
- [x] Determine and document criteria (case categories) for Tier II cases 
- [x] Document procedure for escalation 

## Acceptance Criteria
- [ ] Publish finished procedural document in Confluence 
- [ ] 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
[Support TierII Tier III.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXJvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--81fd600c56e145ed566dcab1a081962c4b446bcf/Support%20TierII%20Tier%20III.docx)
