### ISSUE TITLE
Establish a standard process of creating and deploying feedback and intercept surveys

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#68054]
## Issue Description
Establish a standard process of creating and deploying VA style compliant user-friendly feedback and intercept surveys

---
## Tasks
- [ ] _Create the intake form.

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
@aubreyarcangel and @ATMiddleton will define and confirm steps to deploy intercept surveys in Medallia.

**Comment by ATMiddleton** [comment]
Combined with #74517
