### ISSUE TITLE
Clarify call-out to OCTO at DI and MPR

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#68068]
Assignee: @allison0034 
Peer Reviewer: @shiragoodman 
## Description
At the Design Intent and Midpoint Review, after the VFS team has presented their product and/or updates to their product, we ask OCTO-DE representatives to speak up if they have feedback for the VFS team. This is intended to be for [OCTO-DE practice area leads](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/contact-us#Contactus-OCTOPracticeAreaLeads), not just any OCTO-DE representatives. However, Governance team hosts have asked OCTO-DE representatives of the VFS team (ie the VFS product owner). 

The purpose of this ticket is to clarify our guidance so Governance team members know that this is for practice area leads only.

## Impacted Artifacts
[Design Intent - During the meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2775973945/Design+Intent+-+During+the+Meeting)
[Midpoint Review - During the meeting
](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2790424639/Midpoint+Review+-+During+the+Meeting+Synchronous)

## Tasks
- [x] Under Step 5: Practice area feedback, clarify that this isn't _any_ OCTO-DE representative, but just our practice area leads

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Governance team members are only asking OCTO-DE practice area leads for their feedback during Design Intents and Midpoint Reviews

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@it-harrison I have removed you as peer reviewer and added myself instead!

**Comment by shiragoodman** [comment]
@allison0034 this looks good - you can close!
