### ISSUE TITLE
Check Veteran status of potential non-eligible FSR Veteran

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#68066]
## Issue Description
Mike Dewey from VHA is concerned about a potential non-Veteran proceeding with our FSR form. We need to pull the Veteran's status from VA Profile to validate.

The transaction ID is `06f160fe-2a88-440d-97f6-31e72320b821`

---
## Tasks
- [x] Generate query to pull Veteran status from VA Profile without user object
- [x] Check status and followup with stakeholders

## Acceptance Criteria
- [x] We have passed along the status of the impacted submission
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
For this submission the Veteran has a status of "V3" otherwise known as "Military Person, not Title 38 Veteran, NOT DoD-Affiliated"

**Comment by HeatherRienks** [comment]
@denisecoveyduc - is there any additional information needed, or can this ticket be closed out?

**Comment by denisecoveyduc** [comment]
Thanks @HeatherRienks This ticket can be closed out. It has been determined that the Veteran's status isn't what will drive a change in our process so new tickets will likely be coming once we better understand what is needed. But this one can be closed.
