### ISSUE TITLE
Case Handling Workflow

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#68064]
## Issue Description
Create a complete case handling workflow document 
---
## Tasks
- [x] _Powerpoint workflow_

## Acceptance Criteria
- [ ] _Support team lead approval_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
Kimberley will provide Salesforce screenshots and Anita will compile a PowerPoint.

**Comment by ATMiddleton** [comment]
[Veteran Support Onboarding.pptx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXY3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c6595903740e2d932fbfdfecdbd93b10e2ee136e/Veteran%20Support%20Onboarding.pptx)
