### ISSUE TITLE
[FE] Create Review Page in eCheck-in flow

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#68085]
## Release
Once this has been validated and tested, we should be able to release it; please coordinate with UX and product before releasing

## User Story
As a Veteran, when I choose to submit a travel reimbursement claim, I must agree to the VA terms before I am allowed to submit my claim.

[Userflow](https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/p/0157CB5C-B33B-4324-B375-AC686EFA3B4A/canvas#Version)
[Wireframes](https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/p/B528AED2-D251-4879-9081-673DEAFDB0F1/canvas#Version)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNExpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4886b3b048cf54c81ff1b5c80ebc5332f584c47f/Screenshot%202023-11-16%20at%204.21.58%20PM.png)

## Tasks
- [ ] **Create Review Page in eCheck-in flow**  
- [ ] Expand agreement text  when they click the expander
- [ ] Show validation message
- [ ] Navigate to different pages based on which button is clicked. If "file later" button is selected, check-in is successful, show [You're Checked In page with informational alert](https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/a/g1orPxJ). 
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by benbrasso-agile6** [comment]
@loripusey this was designed to fit the userflow for unified check in priority 1, which we discussed this morning is still a few sprints out. We need to discuss if Mark wants this sooner. If so, UX would need to have a new ticket to adjust the wireframe, specifically the content. Because the content is written based on the assumption that the action will check you in + submit your claim, which would not be the case if we added this into production now. I.e., there would be one more screen to "check in." Would be small content tweaks, I assume.

**Comment by loripusey** [comment]
I still feel like we are taking a simple task (i.e. letting staff know that I am ready for my appointment) and making it immensely more complicated. I am still in favor of moving the travel claim WF to after I have actually checked in, that way I can do it while I am sitting in the waiting room. Also, now that we are adding a way to submit the claim as NOT part of check-in then this makes more sense anyway. Interested to see what @mdewey thinks about all of this.

**Comment by benbrasso-agile6** [comment]
Added correct userflow to ticket

**Comment by benbrasso-agile6** [comment]
@brianseek @loripusey added wireframes link in ticket description. Zach needs to fix the button-pair component width, but you can proceed. Brian, you'll know what I mean when you look at the button-pair component. I logged a ticket for that sketch symbol with platform design yesterday. They fixed it in Figma, lol. But, Zach knows how to hack it up.

**Comment by benbrasso-agile6** [comment]
@loripusey there's no RTP ticket for this work, but FYI, I moved this design file into the Sketch production file a bit early. Just getting it out of the way.

**Comment by benbrasso-agile6** [comment]
@brianseek I know we've talked about this before, i.e., it's the padding on the component, but can we create more spacing between the "Beneficiary travel agreement" additional info component and the checkbox? Or, would we be going down a path where we're no longer being consistent across our code?

**Comment by benbrasso-agile6** [comment]
LGTM though

**Comment by benbrasso-agile6** [comment]
GA events are created by default on those buttons?

**Comment by brianseek** [comment]
@benbrasso-agile6 that's my bad on the spacing, I can bump that down a bit. Yes the buttons will be picked up in GA as yes/no for the travel-review page

**Comment by benbrasso-agile6** [comment]
Cool. Gtg then for me.

**Comment by loripusey** [comment]
Validated, looks great! @brianseek please go ahead and release this when you are ready; @kellysmith1008 will publish the product guides and I'll put out the release notes when you are done.
cc: @benbrasso-agile6 @anita-halici

**Comment by loripusey** [comment]
Sorry @brianseek , forgot you hadn't merged yet LOL
