### ISSUE TITLE
Regular Updates to Support Pages on Platform Website

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#68080]
## Issue Description
Support team should regularly update verbiage on Support pages on Platform Website to increase clarity for VFS Teams and offer consistent adherence to language standards 

---
## Tasks
- [ ] Review [pages](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/design-system-components) from Analytics section of Platform Website for examples
- [ ] Choose 1-2 changes per week or sprint
- [ ] Review with Support Team for accuracy of information
- [ ] Get OK from management
- [ ] submit update to Content Team to update Platform Website

## Acceptance Criteria
- [ ] New/Updated content uploaded to Platform Website
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alyssagallion** [comment]
This is an ongoing process and does not need a ticket for now, closing.
