### ISSUE TITLE
Spike | Burial | Integrate Veteran Service API into Burial Form

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#68092]
## Issue Description
_The burial 530EZ form currently requires users to upload a copy of their DD214 Veteran Service Record document. Matt Dingee mentioned that there is an API that can import DD214 information directly into forms._

---
## Tasks
- [ ] What is the API?
- [ ] How much of an effort would it be to integrate it with the Burla form?

## Acceptance Criteria
- [ ] Document how to connect to API
- [ ] Connect with Laura Steele to define follow-on tickets
---

**Comment by tblackwe** [comment]
I assume it is this API, will need to check further
https://developer.va.gov/explore/api/veteran-service-history-and-eligibility

**Comment by steele-lm** [comment]
@Midge-dev There is a military history API that we may be able to leverage to pull in a Veteran's service history into the burial form, but there are some open questions on if/how we could use it. Ideal case: When an unauthenticated user enters the Veteran's identifying info (e.g., ssn), the service history would auto fill based on the information already entered for the Veteran (ssn). If the user authenticates using the deceased Veteran's account, the service history would also auto fill. One open question @fiorella-io might be able to explore with our SMEs is whether or not a DD214 has to be submitted with the burial form even if the data is auto-filled. If that's the case, maybe we could explore dynamically generating the DD214 at submission (assuming the API provides the required info).

**Comment by micahaspyr** [comment]
In the BenefitsEducation::Service the get_gi_bill_status 

This is the data that can be pulled from the Service History API from a Veteran who is logged in
```
{
  "data": [
    {
      "id": "2305d238-dee4-5c98-858a-f912e3c059f8",
      "type": "service-history-episodes",
      "attributes": {
        "first_name": "Jessie",
        "last_name": "Price",
        "branch_of_service": "Air Force",
        "service_type": "Active Duty",
        "start_date": "1991-05-29",
        "end_date": "2011-06-30",
        "pay_grade": "E07",
        "component_of_service": "Air Force",
        "discharge_status": "honorable",
        "separation_reason": "SUFFICIENT SERVICE FOR RETIREMENT",
        "service_episode_combat_pay": false,
        "deployments": [
          {
            "start_date": "1948-10-10",
            "end_date": "1949-10-09",
            "location": "KOR"
          }
        ]
      }
    }
  ],
  "militarySummary": {
    "first_name": "Jessie",
    "last_name": "Price",
    "active_duty_status": "N",
    "combat_service_indicator": true,
    "duty_status_code": "02",
    "duty_status_text": "Not on active duty: ",
    "total_number_of_regular_active_duty_days": 444,
    "total_number_of_reserve_active_duty_days": 90,
    "total_number_of_guard_active_duty_days": 60,
    "total_number_of_training_days": 10
  }
}
```

**Comment by micahaspyr** [comment]
This POST /service_history endpoint provides a Veteran's detailed service history including all military service episodes with the first and last name of the Veteran, the branch of service, start and end dates, paygrade, discharge status, and separation reason. It also provides start and end dates and locations for each deployment within each episode of service.

Required information to search for a Veteran:

First Name
Last Name
Date of Birth
Street Address
City
State
Country
Zipcode
Optional information:

Middle Name
Gender

**Comment by steele-lm** [comment]
@fiorella-io I think the only fields that are not in the service history API are service number, place of entry/exit, and unit. Burial seems to be the only form that asks for entry/exit location, so I wonder if we can have a convo with our SMEs (down the road) to see if those fields are still needed if VA.gov is auto-filling the service history. Also, I believe Thomas mentioned before that we can convert ssn on the front end to ICN on the backend, so we should be able to look up service history of a user inputs the Veteran's ssn in the burial form or if the Veteran authenticates when willing out COE or PCPG/CH36.

**Comment by sortizsh** [comment]
Micah write up a more detailed plan for this ticket (in a new ticket) @micahaspyr

**Comment by fiorella-io** [comment]
@micahaspyr Out of all the required information listed on 4/18 what is the minimum number of information required to search for a Veteran? I'm assuming it could be FN + LN + DOB as a minimum. 
How come SSN or VA file number is not one of them?

**Comment by micahaspyr** [comment]
@fiorella-io You're correct that FN + LN + DOB is essential to this.  As to why SSN or VA File number isn't one of the options, I have no idea. This paragraph from the docs below has some recommendations

Tips for finding a match:

- First and Last Name, Address and DOB are often essential to uniquely identifying a Veteran.
- Home Address is recommended, but it may be beneficial to retry the search with additional addresses if they are available and the first attempt is not confirmed.
- To find a match, it can help to retry with different demographic information, such as alternate last names or addresses.
- It can also help to remove special characters, hyphens, apostrophes, or spaces in a name prior to matching.

**Comment by steele-lm** [comment]
@micahaspyr Can we use ICN (which we can get from the Veteran's ssn) to identify the service history record through the GET /service_history endpoint. That would allow us to auto fill the service history as long as the Veteran's social was entered or on their profile, right? cc @fiorella-io
