### ISSUE TITLE
Hide pharmacy searches

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#6809]
## User Story or Problem Statement
As a Veteran, I need accurate information about where to fill my urgent care prescription so I can avoid out of pocket cost. 

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/b22de473-00cf-43cb-83d8-d25374243644)

## Goal
- Prevent display of misleading or inaccurate pharmacy information 

## Objectives or Key Results this is meant to further
OBJECTIVE 2: Deliver meaningful facility information 

---
## Tasks
- [ ] _Temporarily_ prevent Urgent care pharmacies (in VA's network) from being displayed in the VA facility type drop down

## Acceptance Criteria
- [ ] Veterans  are unable to select Urgent care pharmacies (in VA's network) from the VA facility type dropdown  on Facility Locator.
- [ ] A feature flag allows this to be quickly turned on/off
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
