### ISSUE TITLE
[Rated Disabilities] Pending disabilities are being returned by LH

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#68101]
## Background
As we have started our migration to LH Veteran Service History & Eligibility API for rated disabilities data, we have identified an issue with the values being returned in comparison to what we are currently getting from EVSS. This issue was identified by the Mobile team as they started rolling their integration with LH out to production and received reports of discrepancies between what they were seeing on VA.gov and the mobile app

## Tasks
- [x] Reach out to the call center to see if we can get info on production users that experienced this issue
- [x] Collect a few production cases of this happening and send them to the LH team to investigate 

## Acceptance Criteria
- [x] We have given the LH team as much information as possible to help them debug / solve this issue

**Comment by jerekshoe** [comment]
**Update:** I'm hoping to see if Kimberley can dig up any call center cases related to this issue so that we can find an example of this happening in prod as we can't currently reproduce in staging. There is a meeting with LH on Tuesday (10/24) to discuss this issue. I'm hopeful I can get an example of a real Veteran that saw this issue by then.

**Comment by jerekshoe** [comment]
**Update (10/23):** LH meeting was pushed to tomorrow (10/24) afternoon instead of tomorrow morning. I still haven't heard anything from Kimberley in regards to seeing if there were any call center cases that we can use to verify that this is an issue affecting LH Veteran Verification and not some edge case that affects both EVSS and LH Veteran Verification.

**Comment by jerekshoe** [comment]
**Update (10/25):** Had a meeting with LH this morning. The outcome was that LH would reach out to SMEs at BGS to see if they could determine what fields to use to deal with these cases. I may try to find an alternative solution to find some instances of this in production

**Comment by jerekshoe** [comment]
**Update (10/26):** Found a way to log instances of this happening in prod to DataDog. Planning on setting up some prod console time with Steve to double check my approach and verify that everything looks correct

**Comment by jerekshoe** [comment]
**Update (10/30):** Sent emails to Michael Harlow and Lorri Glover from Lighthouse with the 10 production cases that I found of this happening. Waiting for them to check the responses from BGS so we can see what is happening
