### ISSUE TITLE
Remove Form app code from Search app code

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#68107]
(putting this on hold until we solidify decisions on URL, breadcrumbs, navigation flow between Find-a-Rep and Appoint-a-Rep)

## Issue Description
As part of our new two-app approach, we'll need to separate the "Appoint a Representative" application, form pages, etc from the "Find a Representative" application.  

---
## Tasks
- [x] Generate new "Appoint a Representative" app
- [x] Enable new app in content-build repo
- [x] Add client-side routing to devops repo
- [x] Update manifest.json for "Find a Representative" app in a way that's specific to the Search functionality
- [x] Move all state, component, and routing references from "Find a Representative" to "Appoint a Representative"

## Acceptance Criteria
- [x] Front end "Appoint-a-Rep" (Form) code is removed from front end "Find-a-Rep" (Search) code
---

**Comment by holdenhinkle** [comment]
It might be a good idea to update the appName and entryName in the manifest.json file to better reflect the functionality of this app (just rep search).
