### ISSUE TITLE
Add "asynch" to title of event for asynch MPRs

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#68114]
## User Story
As an invitee of a Midpoint Review, I want to be able to see easily if their is no meeting for the review so that I can better use my time throughout the day.

Assignee: @allison0034 
Peer Reviewer: @it-harrison 

## Description
VFS teams have the option to have an asynchronous Midpoint Review, meaning no Zoom meeting takes place and instead, feedback is just delivered via Github ticket. However, there is still an event on the Collaboration Cycle calendar so that Governance team bandwidth throughout the week is appropriately managed.

Although the body of the asynch MPR event states the following:

> Asynch review. No meeting will take place. The Governance team will deliver their feedback by the end of the day today.

It's not always immediately clear that the review is asynchronous. This has caused several Governance team members to follow up asking about the Zoom info. 

The purpose of this ticket is to ensure "Asynch" is added to the event title to serve as a more visible indicator to all parties that there is no actual meeting for this event.

## Impacted Artifacts
[Midpoint Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Scheduling)

## Tasks
- [ ] Add a step in the Midpoint Review - Scheduling doc to specify that if the review is asynchronous, that the title of the calendar event should state asynchronous 

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Asynchronous Midpoint Reviews state that they are asynchronous in the title of the calendar event

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
After looking at the documentation, we already account for this, it was just missed. Closing ticket.
