### ISSUE TITLE
No pharmacy search results

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#6812]
## User Story or Problem Statement
As a Veteran, I need accurate information about where to fill my urgent care prescription so I can avoid out of pocket cost. 

**Business Rationale: The appropriate pharmacy for a given Veteran depends on the Region the Veteran lives in and where the Veteran has received urgent care services. Due to this criteria and the ability to segregate this data, we have determined that the best solution is to prevent pharmacy searches within the Facility Locator. We are removing the ability to search for community pharmacies in [#6808] and updating text in [#6829].** 

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/b22de473-00cf-43cb-83d8-d25374243644)

## Goal
- Prevent display of misleading or inaccurate pharmacy information 

## Objectives or Key Results this is meant to further
OBJECTIVE 2: Deliver meaningful facility information 

---
## Tasks
- [ ] _Temporarily_ prevent the display of Urgent care pharmacies (in VA's network) search results

## Acceptance Criteria
- [ ] Veterans see an error message that no results are found for Urgent care pharmacies (in VA's network) searches
- [ ] A feature flag allows this to be quickly turned on/off
---
