### ISSUE TITLE
Request Outlook Folder Creation 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#68124]
## Issue Description
_Veteran Support needs to have unique ID shared folders created in Outlook. 
---
## Tasks
- [ ] _Request VA IT support to create shared folder for Outlook
- [ ] Create folder rules 

## Acceptance Criteria
- [ ] _Operational shared folders in Outlook on VA.gov 
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
Submitted IT request 10/20/23

**Comment by ATMiddleton** [comment]
Shared Outlook folders already exist.
