### ISSUE TITLE
Allow List Cleanup 1

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#68125]
## Issue Description
Cleanup and small tasks that need to be completed for launch

---
## Tasks
- [x] Remove leftover code related to "warnings"
- [ ] Pass through workflows and documentation for language consistency
- [x] Add count of specs disallowed back to disallowed pages and/or slack notice 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by JoeTice** [comment]
Stretch goal for Sprint 39
