### ISSUE TITLE
[Tech Debt] 526 Errors: Discovery Around Error Reporting/Logging

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#6813]
## User Story or Problem Statement
Problem description: How might we improve our use of Sentry data or update our error logging to make it easier to identify when a veteran gets an error from the VA.gov website.

## Goal
Plan for greatly simplified digging and searching through error report data. How do we correlate non-PII data in the logs to an actual veteran (ie: is UUID actually PII?).

## Tasks
- [x] Explore improvements to error reporting/handling from our end.
- [x] Explore ways to improve our Sentry reporting (scripts to parse through the logs, weekly report generation (automated), etc)

## Acceptance Criteria
- [ ] Moar better logging/error reporting
- [ ] Document current error logging process, tooling, "architecture"

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
VSP is in the middle of upgrading Sentry (https://github.com/department-of-veterans-affairs/va.gov-team/issues/6769), which hopefully will leave us with better search.  Also it will make the slack integration work better and a [variety of other upgrades ](https://blog.sentry.io/2020/01/07/self-hosted-sentry-10-is-ready-to-serve-get-it-while-its-hot)

**Comment by SarahJaine** [comment]
Problem 1: Bug tickets originating from the Help Desk often lack the context we need to investigate and resolve the issue. The logging and monitoring systems do not contain PII or other information that would help us find the exact transaction or exception that the user is experiencing.  Oftentimes, the only information we use to search the logs is a general time of day or an error message; search terms that yield thousands of results.

Proposed solution: 
All errors that are reported to the user with help text directing the user to contact the service desk include an identifier unique to that user session and directs the user to include the report the identified to the help desk. The identifier is logged in Sentry, thereby allowing developers to find the exact error quickly. There are several ids peppering the logs that are possible candidates to be the id used for this: request_id, request_uuid, and transaction_id.  We need to investigate which one is most appropriate to this purpose, standardize its use, and communicate its renewed purpose to VSP. This change will need investigation and buy in from design/research, frontend and backend developers, and VSP.

**Comment by SarahJaine** [comment]
Problem: It is tedious and time intensive for developers to review Sentry for errors and determine which are under our team's purview. Sentry is not pro actively reviewed by developers. Bugs are often surfaced and corrected after they negatively affect the users.

Proposed solution:
Filtering rules are added to Sentry to identify errors related to our team's code. As a second step, it may be prudent for those alerts to be surfaced in a platform developers check regularly, Slack.

**Comment by annaswims** [comment]
The #vfs-sentry-alerts slack channel should be monitored by a VSP engineer.

**Comment by jholton** [comment]
> Proposed solution:
> Filtering rules are added to Sentry to identify errors related to our team's code. As a second step, it may be prudent for those alerts to be surfaced in a platform developers check regularly, Slack.

One way to do this (we did this on a team pre-VSP):
If a team "owns" a controller, in that controller:
```ruby
before_action :tag_team
...
def tag_team
  Raven.tags_context(team: '526_team')
end
```

Now any error that occurs anywhere in the stack for requests that come through that controller will be tagged in Sentry.  You can then filter in Sentry on the 'team' attribute.

**Comment by SarahJaine** [comment]
> > Proposed solution:
> > Filtering rules are added to Sentry to identify errors related to our team's code. As a second step, it may be prudent for those alerts to be surfaced in a platform developers check regularly, Slack.
> 
> One way to do this (we did this on a team pre-VSP):
> If a team "owns" a controller, in that controller:
> 
> ```ruby
> before_action :tag_team
> ...
> def tag_team
>   Raven.tags_context(team: '526_team')
> end
> ```
> 
> Now any error that occurs anywhere in the stack for requests that come through that controller will be tagged in Sentry. You can then filter in Sentry on the 'team' attribute.

Thanks for the suggestion! This is way better way to do this than the tedious path and url based sentry rules I was adding- by controller is what I wanted to do originally.
