### ISSUE TITLE
[CST] Dependents are unable to submit 5103s

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#68133]
## Background
We have found out that dependents are unable to submit 5103s to the LH Benefits Claims API. We will probably need to pass the sponsors ICN as well as the dependents ICN when calling that route

## Relevant files
- `app/controllers/v0/benefits_claims_controller.rb` <- Controller
- `lib/lighthouse/benefits_claims/service.rb` <- Service that controller above uses to interact with the Lighthouse Benefits Claims API

## Tasks
- [x] Add logic in vets-api to send the sponsors ICN when the current user is a dependent and they are submitting a 5103
- [x] Send a log to DD when we are submitting a 5103 for a dependent with the claim ID so we can verify our solution is working

## Acceptance Criteria
- [ ] Dependents are able to submit 5103s without getting an error
- [ ] Logs are sent to DD so that we can verify our solution

**Comment by jerekshoe** [comment]
**Update (10/23):** I met with Alex and Kayla from the LH Benefits Claims team to discuss a path forward for this issue. At this point I believe that we don't have a clear enough understanding of all of the edge cases that we may encounter when dealing with the Dependent / Veteran relationship, especially when dealing with cases where Dependents may be Veterans themselves. We also need to figure out what the best solution is (ie. using a header, query parameter, field in the request body, or something else entirely.) They have a meeting with their engineering lead on Wednesday (10/25) afternoon and will discuss with them to determine if their API standards can provide clear guidance on the best option. I'd like to see if I can find a generic way to implement this that can be applied across other LH APIs as well, as this is the second LH API where we have had to try to demystify the Dependent / Veteran relationship and how EVSS handles it.

**Comment by HeatherWidmont** [comment]
@jerekshoe waiting on vets API reclone

**Comment by HeatherWidmont** [comment]
Will not be merged before sprint review later today, but this is close to being done

**Comment by HeatherWidmont** [comment]
@jerekshoe is currently testing this

**Comment by HeatherWidmont** [comment]
Blocked by Lighthouse at the moment

**Comment by jerekshoe** [comment]
#### Update
Pushed out the changes needed for the suggested workaround yesterday (i.e. passing the SSN in place of the BIRLS ID for users that don't have one) and found that it didn't seem to have any effect over the previous implementation. At this point we are waiting on Lighthouse Benefits Claims to update their API to work for these users so that we can switch to it

**Comment by jerekshoe** [comment]
#### Update (2/13)
Going to close this for now. Lighthouse will prioritize this work in the next few sprints so we will worry about things then. At the moment there are no changes expected from us, just changes on their end
