### ISSUE TITLE
Update Product Documentation to reflect MVP Split

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#68134]
## Issue Description
The midpoint feedback has helped us to understand that we may be fitting too much into one product and the team has decided to split our MVP into two separate launches:

1. Find a Rep
2. Appoint a Rep + Representative Status Widget

---
## Tasks
- [x] Breakout the MVP into three MVP documents (Find a Rep, Appoint a Rep, Rep Status Widget)
- [x] Breakout the Product Outline into three
- [x] Share the Product Outlines with the team for feedback
- [x] Update the Product Outlines according to team feedback

## Acceptance Criteria
- [x] Updated MVP documents have been uploaded to Github
- [x] Updated Product Outlines have been uploaded to Github

**Comment by oddball-lindsay** [comment]
I've split the MVP outline into three, respective to their individual products.

1. Find a Representative MVP
2. Appoint a Representative MVP
3. Representative Status Widget MVP

Find a Rep will ship first, Appoint a Rep is scheduled to ship with the Representative Status Widget as those connect together nicely for a cohesive experience.

**Comment by oddball-lindsay** [comment]
Shared a draft in a [Product Outlines canvas](https://dsva.slack.com/docs/T03FECE8V/F062ULB462C) requesting team feedback by EOD Monday 10/30

https://dsva.slack.com/archives/C05L6HSJLHM/p1698092345562349

**Comment by oddball-lindsay** [comment]
Incorporated feedback from team, all MVP and Product Outline documents live in our Github product folder: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/accredited-representation-management
