### ISSUE TITLE
[Research] 10-10 Research Planning

### ISSUE THREAD

**Issue by joaquin1121** [department-of-veterans-affairs/va.gov-team#68138]
## Issue Description
- Create needed documents to prepare for research studies.
- Download templates needed from the [Platform site](https://depo-platform-documentation.scrollhelp.site/research-design/research-at-va)
- Work with team to determine research goals and questions.

---
## Tasks
- [ ] Create folder with naming conventions in [research root folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/research)
- [ ] Create [research plan](url)
- [ ] Create [conversation guide](url)
- [ ] Review with team/changes needed
- [ ] Confirm dates
- [ ] Kickoff ticket with Perigean

## Acceptance Criteria
- [ ] Submit for research review and recruitment
