### ISSUE TITLE
ATLAS MVP

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#68139]
### PROBLEM STATEMENT
The Platform Product Team (fka Platform Tech Team 1) has been working to ensure code ownership data is accurate and up to date. This was work that resulted from determining _who owns what code in vets-api_ but we grew the scope to include all of va.gov. In order for this information (who owns what code) to remain accurate, we need to focus our MVP of Atlas to working with the Platform Governance team to ensure information that was previously kept in the roster spreadsheet, will be stored in Atlas. This sets the foundation for many potential future feature requests/enhancements to Atlas, but before moving forward, we need to ensure the foundation information is accurate AND _remains_ accurate.

### ADDITIONAL INFO
[Product outline WIP for Atlas
](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2760671235/Product+Outline+Atlas+WIP)

### ACTION ITEMS
- [x] Atlas DB Design updates
- [x] Codeowners verification list
- [x] File deletion automation
- [x] Host Atlas in prod cluster
- [x] Documentation: How to use Atlas (as an MVP)

### DEFINITION OF DONE
- [ ] Atlas app is deployed and handed off to the Governance team to begin using to record information previously stored in the roster spreadsheet (add link for spreadsheet)
