### ISSUE TITLE
[UX] Create New Content

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#68146]
## Background
When Veteran submit a travel reimbursement claim via the BTSSS portal, they must agree to the following terms before they are allowed to submit their claim. We need to add this to the eCheck-in workflow and possibly consider moving the travel portion to after the Veteran has completed check-in so that it does not continue to add to the time it takes for them to check-in.

[Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1697811766776369)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/07ed5aeb-6a3d-42e4-bbbb-2348486d1d65)

## User Story
As a Veteran, I need to be able to agree to the terms for submitting a travel reimbursement claim so that I can understand what is required of me in order to submit the claim.

## Tasks
- [x] Get the content from the BTSSS portal/team
- [ ] Verify the content doesn't need to be tweaked
- [ ] Run content by Danielle

## Acceptance Criteria
- [ ] Content is available & has been reviewed

**Comment by benbrasso-agile6** [comment]
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698872826836/7e242e73ef37ecc7d6b398b550a7a3943e1b95fa?sender=u37bb983bd3fc3cc00c7d3286

Review page that will need some content and/or button tweaks that we're using for past appts (for reference) - https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/6517BA8C-BADD-478E-9380-4F59F467423F/canvas

**Comment by benbrasso-agile6** [comment]
Content of BT Agreement

https://www.sketch.com/s/50c13762-b34d-44df-a657-6a75872faf82/a/QbdyGa8

**Comment by kellysmith1008** [comment]
Created a [mockup of a proposed version](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/6517BA8C-BADD-478E-9380-4F59F467423F/canvas) and shared it with UX team. Once we finish final tweaks, I'll run it past Danielle

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 FYI - I see you closed this - content is ready. It hasn't been run past Danielle or Laura yet - you may want to reach out to them per the task in the ticket

**Comment by benbrasso-agile6** [comment]
Sorry about that. Thought it was all set. I thought we just pulled the Agreement over. 

Oh and, they're about to see it (in the form of past appts) as part of the CAIA ticket.

Want me to reopen?

**Comment by kellysmith1008** [comment]
No need as long as they're going to see it. Just wanted to make sure they got eyes on it - thanks!
