### ISSUE TITLE
SPIKE | No Last Name Error

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#68141]
## Tasks
- [x] Research the root causes of: `last_nm cannot be empty or nil.` error
- [x] Reproduce error in Development or Staging

[Sample Error](https://vagov.ddog-gov.com/apm/trace/2871152850858379597?colorBy=service&env=eks-prod&graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=2913789214458548303&spanViewType=logs&timeHint=1697906489380.3389&view=spans)

## Acceptance Criteria
- [x] Root cause documented
- [ ] Follow-on ticket created

**Comment by evansmith** [comment]
At first glance it looks like "?" was entered for a Veteran's previous spouse's last name. Investigating further.

**Comment by evansmith** [comment]
Confirmed error in staging here: http://sentry.vfs.va.gov/organizations/vsp/issues/235209/?environment=staging&query=is%3Aunresolved

@tblackwe @steele-lm We could validate for symbols in the last name on the FE or perhaps validate on submit. Thoughts?

**Comment by tblackwe** [comment]
There is already a method 'normalize_names_and_addresses' that we can update to include question marks. https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/sidekiq/bgs/job.rb

Called from Line 39 in https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/sidekiq/bgs/submit_form686c_job.rb
and Line 38 in https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/sidekiq/bgs/submit_form674_job.rb

**Comment by evansmith** [comment]
@tblackwe agreed, we should go this route.

**Comment by sortizsh** [comment]
closing this spike since we opened a ticket
