### ISSUE TITLE
FE | Auth Exp | Nametag | Exploration to provide support for multiple middle initials

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#68144]
## Background
In a recent research session, a Veteran with two middle initials pointed out that their name was "wrong" in the nametag because the second initial wasn't capitalized. Can we support multiple capital middle initials in the nametag?

@adamwhitlock1 observed the session and made some comments in [this Slack thread](https://dsva.slack.com/archives/C40B45NJK/p1697732926761489?thread_ts=1697730831.439149&cid=C40B45NJK):

- the middle initial comes back as it's own property from the api, so the assumption is the the middle name is probably coming to the FE as `G m` so not sure there would be much we could do since multiple middle names aren't really supported.
- maybe we could do some pattern matching to see if their middle name data includes spaces and capitalize based on that

## Tasks

- [ ] See if we can support 2 middle initials in the nametag
- [ ] Provide a recommendation on how to proceed in the comments of this ticket
- [x] Work with PM (and/or other devs as needed) to create tickets for implementation (if deemed possible)

## AC
- [x] We've determined whether or not this can be implemented
- [x] If it can be implemented, subsequent ticket(s) are created

**Comment by ajakabcin** [comment]
Thanks @andaleliz I'll have my team take a look at this next refinement

**Comment by DanielMiller-agile6** [comment]
test

**Comment by andaleliz** [comment]
@DanielMiller-agile6 I hear you! Loud and clear!

**Comment by DanielMiller-agile6** [comment]
I did some preliminary investigation, not sure of an ideal way to handle this, but we do have some options.

Looks like our model only stores first, middle, and last names for a user. So for user with more than 3 legal names a single middle supports spaces spaces.  Without updating our model to support more than 1 middle name, we could handle formatting a multi-word middle name or middle initials on the client (as stated by @adamwhitlock1 in slack thread).

We might be able to handle this with css (i.e. text-transform: capitalize), although maybe there could be cases where we don't want to capitalize a middle iinitial or surname (e.g. toponymic names like "de Rosas" or other types of names I'm unaware of), so maybe transforming in JS will allow for more control.

Looks like our NameTag component uses the format name global util internally:
https://github.com/department-of-veterans-affairs/vets-website/blob/b9c1e80b8df03223f53377ae40912439f4952d60/src/applications/personalization/common/helpers.js#L93

No sure if we'd want to update this within the utiil, or only handle this in the NameTag component?
https://github.com/department-of-veterans-affairs/vets-website/blob/c5aa3483f29ffcce73ad98f7ded2931e38e83d8b/src/applications/personalization/components/NameTag.jsx#L98

**Comment by adamwhitlock1** [comment]
Thanks for looking into this @DanielMiller-agile6.

I'd say the helpers.js file would be a good place to make this change. It is scoped a little wider than just the NameTag component, but is still scoped down to just the personalization applications so should be fine. It is used in the NameTag.jsx and LegalName.jsx so that would cover all our use cases AFAIK.

The css route could also work and might be a bit less invasive, but might require changes/additions to custom scss which may or may not be as maintainable. I'd leave the decision up to you.

**Comment by ajakabcin** [comment]
Great work on this @DanielMiller-agile6 and @adamwhitlock1 - thank you!

@DanielMiller-agile6 when you guys are settled on a path forward, we'll make a separate ticket for the implementation. We can work on that in refinement on Wednesday!

**Comment by DanielMiller-agile6** [comment]
Thanks Adam & AJ!  I like the approach for changing this in the helper JS file.  That would resolve this issue, along with any occurrences in the LegalName component as well.  We could do this in the JS with a RegExp or string parsing so that we can ensure that single-letter initials in names are always capitalized, while still supporting any user-defined surnames that might require lower-case initial letters in multi-word names. Thoughts?

**Comment by ajakabcin** [comment]
Created a ticket for implementation of Daniel's recommended solution: #70821
