### ISSUE TITLE
[Epic] Connected Apps Updates 

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#6814]
## Background
With connected accounts, Veterans can authorize a third-party app or site to access their sensitive data (like health records, veteran confirmation, etc.) in order to use the app or service. A Veteran authorizes access through the app flow, but must come here to VA.gov at a later date in order to revoke that access. None of the apps/sites can change a Veteran's data, but some may copy it over to their own servers or the Veteran's device. (Various use cases.) Disconnecting an account, doesn't mean a Veteran's account with the third-party app or site will be deleted. We want to message this as well, without scaring anyone too much.

## Tasks
- [x] [Design] Connected accounts design updates #6731 (AE)
- [x] [Copy] Connected Accounts UI copy #6748 (Carey Otto/Peggy)
- [ ] [URL] Copy and IA help from Lighthouse API for connected accounts #6838 (Public Websites)
- [x] [URL] Lighthouse team to provide FAQ URL [#6864 ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6864)(Public Websites)
- [x] [URL] Lighthouse team to provide List of Apps URL [#6866](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6866) (Public Websites)
- [x] [Research] Lighthouse team to provide up to 5 minutes of user research questions - [Conversation Guide for Profile 2.0](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Research/Profile-2.0-Conversation-Guide.md), [Comments ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/2586#issuecomment-602846192)(Carey Otto)

**Comment by Samara-Strauss** [comment]
Thanks for creating this, @mshea0606!!

**Comment by mshea0606** [comment]
Updates per Carey on 3/24/20:  
- Rough drafts of FAQs and App Directory are complete and on GitHub
- Meeting with Public Websites team to kick-off their help with this tomorrow
- VSP got wind and want to talk to me about whether we can incorporate this into your future collab cycle meetings or not — I will need to get their design/copy blessing on these extra piece. 
- Hopefully the App Directory and FAQ can be launched with Profile 2.0

**Comment by Samara-Strauss** [comment]
Can we close this out?
