### ISSUE TITLE
Deprecate/remove Prometheus 

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#68154]
## Status
| Date | Status | Launch Date (see above) | Notes |
| ----- | ------ | ------------------------- | ------ |
| 2/10/25 | On-Hold | No updates, effort has been deprioritized. |
| 1/20/25 | On-Hold | No new updates. Team has been focusing on other priorities. |
| 1/6/25 | In-Progress | On-Track | No new updates. Team continues to work through tickets. |
| 12/9/24 | In-Progress | On-Track | Team continues to work through ticketed work needed for deprecation. |
| 11/25/24 | In-Progress | On-Track | Team is working on Migrating alerts and Disabling releases. |
| 10/28/24 | On Hold | Off-Track | No new updates and is on hold. |
| 9/23/24 | In-Progress | On-Track | Grafana has been fully decommissioned, but Prometheus and Loki are still running. |
| 9/9/24 | On Hold | Off-Track | Team has been focusing on FwdProxy and EKS work, so no progress made here.. |

## Problem Statement 
VA.gov Platform has migrated to Datadog as the solution for monitoring and logging. Legacy systems such as Prometheus, Loki, and Grafana should be removed.

## Hypothesis or Bet
This will reduce the number of builds and deploys, lowering the surface area for security-related issues.

## We will know we're done when... ("Definition of Done")
- [x] Grafana has been decommissioned
  - [x] Grafana has been removed from EKS (utility)
  - [x] Grafana Build jobs have been removed from Jenkins
  - [x] Grafana Release jobs have been removed from Jenkins
  - [x] Grafana Deploy jobs have been removed from Jenkins
- [x] Prometheus has been decommissioned
  - [x] Prometheus has been removed from EKS (dev, staging, utility, sandbox, prod)
  - [x] Prometheus Build jobs have been removed from Jenkins
  - [x] Prometheus Release jobs have been removed from Jenkins
  - [x] Prometheus Deploy jobs have been removed from Jenkins
  - [x] Promotheus monitors have been migrated to Datadog
- [x] Loki has been decommissioned
  - [x] Loki has been removed from EKS (dev, staging, utility sandbox, prod)
  - [x] Loki Build jobs have been removed from Jenkins
  - [x] Loki Release jobs have been removed from Jenkins
  - [x] Loki Deploy jobs have been removed from Jenkins

## Known Blockers/Dependencies 
- Some container runtimes still point at Grafana Loki. If we remove the aggregator before the logs stop flowing, this can cause systems to get bogged down or halt completely as the local disks fill with logs waiting to be sent

## Projected Launch Date
- TBA

**Comment by ph-One** [comment]
Created Milestone https://github.com/department-of-veterans-affairs/va.gov-team/milestone/1337 to attach issues to

**Comment by kflow85** [comment]
Grafana has been fully decommissioned, but Prometheus and Loki are still running.
