### ISSUE TITLE
[CHIP] - Record check-in started timestamp

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#68163]
## Summary
Record a timestamp in LoRota during initiate check-in. Only record if setting eCheckInStarted, so this excludes a 45 minute text call. 

## Tasks
- [ ] [CHIP] Write timestamp to a new field in LoRota for check-in started
- [ ] [CHIP] When check-in completed, do delta between check-in completed and check-in started and log in DataDog
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Deployed to dev/staging.
- [ ] Tested on dev/staging

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch on dev/stage
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
@lee-delarm6 this can get validated during your spike work

**Comment by loripusey** [comment]
@lee-delarm6 can you validate this before sprint review?

**Comment by lee-delarm6** [comment]
This one is not complete, it is the second part after the spike work which just finished yesterday. Completing this will not take a huge amount of time, as the other work was done in parallel to the spike. The finish portions to be completed are logging the CORRECT "seconds to completion" for the various queries requested. Currently we are logging fake data and the switchover should be a small project for a day, two at most if something goes weird to do this:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL25aQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2aac0d4be276b53c57cd7e9531836b1a45c62087/Screenshot%202023-11-14%20at%205.47.18%20PM.png)

**Comment by loripusey** [comment]
Moving back to in progress and rolling over
