### ISSUE TITLE
[Design] HLR Design Changes from AMO 

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#6816]
## User Story or Problem Statement
As a UX designer, I need to implement the changes we were given from AMO in our most recent meeting (Tuesday March 10)

## Tasks
- [x] Legacy issue gating - link the words 'legacy appeal' on the gating question (https://www.va.gov/disability/file-an-appeal/)
- [x] Remove the '5 business days' sentence from the submission screen
- [x] Remove the disposition from the contested issues screen and replace with disability rating percentage
- [x] Refactor the 'don't see your issue here' content. Make the 'see all issues' button an HLR download button or link instead

## Acceptance Criteria
- [x] the above tasks have been completed
- [x] the above tasks are reflected in the HLR Invision prototype

**Comment by kevinstachura** [comment]
The link with the changes can be found here: https://vsateams.invisionapp.com/share/W5U21BDFTQK
