### ISSUE TITLE
Spike on Scroll Viewport Sandbox Environment (Sprint 40 Demo Slide Deck)

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#68161]
## Tasks

- [x] Connect with Jason to determine what demo idea would be most impactful

- [x] Create PPT to introduce demo. [Use this template](https://docs.google.com/presentation/d/1SUQp7RPCz8-hZx5jj3sW0ZeLx2x6MWVFhADbhZdONnA/edit?usp=sharing).

- UPDATE: Demo and spike consisted of playing around with Scroll Viewport functionality in our Sandbox environment. The results from the spike included an understanding of functionality that can be applied for landing pages, footers, headers, and general navigation and IA. Specific findings will be presented at the demo.

## Demo
- Outline Viewport out-of-the-box functionality that can be leveraged to support future IA initiatives. 

## Acceptance Criteria

- [X] Member of the content team will lead a demo at the next sprint demo (Wednesday, November 22nd), scheduled to be @johnny-jesensky-adhoc.
UPDATE: The demo for November 22nd was canceled due to the Thanksgiving Holiday. As a result, this demo will be performed at the next one, on **Wednesday, November 5th**.

- [x] Slide deck has been created to serve as the outline for the demo.

## Findings & Artifacts
- https://docs.google.com/presentation/d/1msWXluyavbTLmPHbe5r-WgzNu2esNTPc4THbluHrdRg/edit#slide=id.p

**Comment by johnny-jesensky-adhoc** [comment]
Look to reference old demo cards.

**Comment by BSmolensky** [comment]
I am OOO that day. Sorry. 
--
Brian Smolensky | Content Strategist
 

The So Company <http://thesocompany.com/> 
We make the government better.
Timezone: EST | GMT -4:00
802-356-0146 | ***@***.*** ***@***.***>  
SDVOSB | SBA 8(a) Certified | Digital Services Coalition Founding Member

**Comment by johnny-jesensky-adhoc** [comment]
Artifact from this task - https://docs.google.com/presentation/d/1msWXluyavbTLmPHbe5r-WgzNu2esNTPc4THbluHrdRg/edit#slide=id.g293d268576c_0_13

**Comment by johnny-jesensky-adhoc** [comment]
Artifact from this task - https://docs.google.com/presentation/d/1msWXluyavbTLmPHbe5r-WgzNu2esNTPc4THbluHrdRg/edit#slide=id.g293d268576c_0_13
