### ISSUE TITLE
[BE] - Pass contextual data to CHIP

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#68166]
## Description
As part of the time to check-in measuring work, we will be sending new pieces of data during check-in that will need to be forwarded to CHIP during check-in. 

New data:
 - isTravelEnabled (bool)
 - travelSubmitted (bool)

## Tasks
- [ ] [BE] Pass new data to chip.

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
