### ISSUE TITLE
[FE] Send context data during check-in

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#68165]
## Description
This work is to support the time to completion measuring effort. Send the following contextual data during the check-in api call: 
- isTravelEnabled (bool)
- travelSubmitted (bool)

## Tasks
- [ ] [FE] Send additional data to vets-api
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [x] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by wullaski** [comment]
@brianseek @loripusey @benbrasso-agile6  What should define isTravelEnabled?
Should it be true if they are presented with the questions(feature flag is on, it's in pilot, and no other claim filed that day), or should it be true if it is enabled in the clinic/station and the feature flag is on?

**Comment by benbrasso-agile6** [comment]
Do we need the isTravelEnabled? Knowing that we're only trying to measure when travelSubmitted?  

E.g., in the Epic assumptions: 

> Count only Vets who get a successful completion of check-in (i.e. failures or abandonments are not counted)

**Comment by benbrasso-agile6** [comment]
I guess I see your point. Um.... the first choice

> true if they are presented with the questions(feature flag is on, it's in pilot, and no other claim filed that day)

**Comment by wullaski** [comment]
@loripusey after reviewing this for demo prep I think the logic needs to be adjusted slightly to take into account whether or not the claim was filed that day. 
> true if they are presented with the questions(feature flag is on, it's in pilot, and no other claim filed that day)
