### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#68188]
## Issue Description
Writing unit tests to ensure that components behave as expected and to catch any regressions or issues that might arise.

For the unit tests, please note the [Unit Test Coverage](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-unit-test-coverageUnitTestCoverage) section of VA Platform's QA Standards, which states:
> Visit the [Unit Test Coverage Report of the Frontend Dashboard](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report/) and find your product in the table. If your product is not yet listed, you can generate the code coverage report locally by running the following command within `vets-website`: `yarn test:coverage-apps`.
>
> To run coverage report and open the report in the browser for an individual app from `src/applications`:
> `vets-website`: `yarn test:coverage-app {app-name}`

---
## Tasks
- [ ] Create unit test cases for each function and component of Search Controls.
- [ ] Create unit test cases for each function and component of Search Results.
- [x] Create unit tests for reducers (SearchQuery and SearchResults)
- [ ] Create unit tests for helper methods (eg phone number parsing)
- [ ] Generate a coverage report for Find a Representative in the [Unit Test Coverage Report of the Frontend Dashboard](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report/)

## Acceptance Criteria
- [ ] All unit tests must pass without any failures.
- [ ] Unit tests should be added to the project's testing suite and run as part of the CI/CD pipeline.
- [ ] Unit Test Coverage Report has been created for Find a Representative

**Comment by cosu419** [comment]
[11/6 update] Currently working through Pagination and SearchControls tests

**Comment by oddball-lindsay** [comment]
Added Unit Test Coverage information to the ticket description and created one additional task and acceptance criteria to account for this need.

**Comment by cosu419** [comment]
Test coverage report as of 11/16:

- 93.79% Statements 121/129
- 83.33% Branches 70/84
- 94.11% Functions 16/17
- 93.65% Lines 118/126
