### ISSUE TITLE
Demo:  VFS research approach for Design Intent learnings

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#68183]
[##](url) Issue Description
Discuss the thinking, meetings, and Mural used to generate learnings about challenges and improvements for the Design Intent touchpoint:

Framing:
Governance Team has long been interested in making the DI touchpoint a better experience, and has worked to that end.  In their wisdom, they realize that they're close to it, so they asked for an assist from SDT.
Act 1 was for us to review all of the documentation, analyzing it from the user's experience and making recomendations
Act 2 was to actually meet w/ VFS teams who have gone through DI, or are about to, and learning directly from them.

## Tasks
- [x] Created [deck](https://docs.google.com/presentation/d/1aGuYnTh8RYpdDAQOKFnKaLFRHftC3odpACIlAtd3Qjs/edit#slide=id.p1)
- [x] prep [Mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1698171106168/443a7df5db212e62531831504763087c7ea35e1e?wid=0-1698176054290&sender=u311209e67c8c21a1b37a8167)
- [x] Share at Demo day

## Acceptance Criteria
- [x] Change has been communicated in Demo Day
