### ISSUE TITLE
[Design] Mapping of Original Claims Flow

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#6818]
## User Story or Problem Statement
As a UX designer, I need to map the different possible paths/flows in the original claims process so we have that documentation moving forward.

## Tasks
- [ ] Map out each screen and possible path a user could take in an original claims experience

## Acceptance Criteria
- [x] A Mural document has been completed that documents all possible flows/paths
- [ ] A PDF version has been completed and uploaded to Github that documents all possible flows/paths

**Comment by kevinstachura** [comment]
This ticket has been satisfied except for the PDF generation. Was advised from Mural support that the file was too large which was preventing from the email PDF to be sent to email. Mural support further advised to break down into smaller parts so we can export it in pieces. Have decided to close out this ticket and create a new one for the exportation process - the documentation itself has been completed.
