### ISSUE TITLE
[FSR Wizard] Add URLs to wizard complete a subtask pages

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#68211]
## Description

Moving to one thing per page for the wizard rework pages requires creating new URLs.

Given: A veteran starts the FSR
When: A veteran clicks on the wizard subtask
Then: A veteran will be able to click through to the different pages to get the outcome they need

## Tasks
- [x] Add URLs to mockups
- [x] Get feedback from CAIA team 
- [x] Get feedback from FE 

## Acceptance criteria

- [x] Signoff from PO and CAIA team

## Testing
- [x] N/A if non development work

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by josephrlee** [comment]
@HeatherRienks @Tom-Davis, I just added the Wizard URLs ticket!

cc: @mgleo @charlottecesana

**Comment by josephrlee** [comment]
Need to create a CAIA intake request for this, but we still need VBA feedback on the new updated flow before we do that. We already have updated feedback from VHA, but I wanted to wait on submitting a ticket until we have all the wizard copy content reviewed from SMEs and our PO so we can ask for feedback from CAIA on the entirety of it. 

cc: @mgleo @HeatherRienks @Tom-Davis

**Comment by HeatherRienks** [comment]
@denisecoveyduc - please see above. :) We would prefer to submit one CAIA request (with VHA and VBA feedback).Thanks!

**Comment by mgleo** [comment]
VBA and VHA Wizard paths with URLs in purple: [https://www.sketch.com/s/50583485-ba58-4ef8-ae04-2c274a792547/p/9CF1004F-FE5E-4451-BBED-D6EDB294B0C6/canvas](https://www.sketch.com/s/50583485-ba58-4ef8-ae04-2c274a792547/p/9CF1004F-FE5E-4451-BBED-D6EDB294B0C6/canvas)

**Comment by HeatherRienks** [comment]
@denisecoveyduc - please let us know if Melonie has any feedback. Thank you!

**Comment by HeatherRienks** [comment]
@josephrlee @mgleo - any updates on this ticket that you are aware of?

**Comment by josephrlee** [comment]
Just created the CAIA request for this ticket:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/71331

**Comment by HeatherRienks** [comment]
@josephrlee or @mgleo - any feedback on this?

**Comment by josephrlee** [comment]
@HeatherRienks, am following up with CAIA now! 

cc: @mgleo

**Comment by josephrlee** [comment]
@HeatherRienks this is now unblocked and moving back into In Progress! 

cc: @mgleo

**Comment by josephrlee** [comment]
New URLs have been added to the [Figma file](https://www.figma.com/file/ea8baIDr09ncgr1P4Rfh8i/Financial-Status-Report-(VA5655)---Streamlined-Waiver?type=design&node-id=24-25440&mode=design&t=Wd0help1zoMVL5qA-11) [based on CAIA feedback](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1682537441750/a9937e9953d80c221c5165131f611026e0419c7b?sender=u64758e17a18c4eb2bea93888).

**Comment by josephrlee** [comment]
@Tom-Davis  and @HeatherRienks, I'm moving this to closed as I believe this is done for now.

cc: @mgleo @charlottecesana
