### ISSUE TITLE
[FSR] Review Page - Competitive analysis for review page editing flow

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#68212]
## Description

Perform a brief competitive analysis of what other products do when creating an editing flow from the review page to create the best review/editing experience possible for the FSR.

Given: A veteran reviews information before submitting the FSR
When: When a veteran wants to edit information from the review page of the FSR
Then: A veteran will have an easy and intuitive way to review and edit their information with error messaging that's helpful 

## Tasks
- [x] Create a Mural board and document different review/edit flows
- [ ] Note the constraints of the Form System
- [ ] Share out with rest of team

## Acceptance criteria

- [ ] A couple of solid review/edit flows have been documented
- [ ] Team has a better understanding to create a more ideal review/edit flow

## Testing
- [ ] N/A if non development work

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by josephrlee** [comment]
@HeatherRienks @Tom-Davis Just added this ticket I was talking about.

**Comment by Tom-Davis** [comment]
@josephrlee this is the last ticket in this epic with work remaining - any updates on the analysis?

**Comment by mgleo** [comment]
Mural board created for [Review page comparative analysis](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698094552223/5a9caf732ca67f2dca2c36f9e92ce45d4e1c65cf?sender=ua78f969c4cddcbfe56b27885)

Platform's direction has been away from modals to edit fields and more towards taking the user back into the form to edit.
