### ISSUE TITLE
Update Mochawesome to Latest Version in `content-build`

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#68229]
# Description
`content-build` is currently configured to use Mochawesome version 6.3.1 The current version of Mochawesome is 7.1.3 which was published about 2 years ago.

We should update `content-build` to use the latest version of Mochawesome in order to have the latest bug fixes and feature support. We can reasonably expect this change to have some effect on CI as Mochawesome reports are part of how we parse and report test results.

# Tasks
- [x] Upgrade Mochawesome locally
- [x] Run through the unit and e2e tests locally and look for errors
- [x] Resolve errors
- [x] Create a branch / PR for the updated version
- [x] Verify that CI completes successfully with the updated version
- [x] Verify that the report generation part of CI does not contain regressions
- [x] Merge the PR

**Comment by pjhill** [comment]
PR here -- https://github.com/department-of-veterans-affairs/content-build/pull/1796

**Comment by pjhill** [comment]
Merged
