### ISSUE TITLE
Update Cypress to Latest Version in `content-build`

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#68227]
# Description
`content-build` is currently configured to use Cypress version 10.8. As of the writing of this ticket, the [current version](https://docs.cypress.io/guides/references/changelog) of Cypress is 13.3.3 which was published on 10/24/2023.

We should update `content-build` to use the latest version of Cypress in order to have the latest bug fixes and feature support.

It may be necessary to step through several versions of Cypress. Consult the migration guide available [here](https://docs.cypress.io/guides/references/migration-guide).

# Tasks
- [x] Upgrade Cypress locally
- [x] Run the E2E tests locally and look for errors
- [x] Resolve errors
- [x] Create a branch / PR for the updated version
- [x] Verify that CI completes successfully with the updated version
- [x] Merge the PR

**Comment by pjhill** [comment]
Reviewed migration guides 11,12,13 for Cypress here -- https://docs.cypress.io/guides/references/migration-guide

There don't appear to be breaking changes for how we are using Cypress in `content-build`.

I will try upgrading straight to Cypress 13.5. branch here -- https://github.com/department-of-veterans-affairs/content-build/tree/68227-update-cypress

**Comment by pjhill** [comment]
Cypress tests are passing locally with Cypress 13.5 installed.

**Comment by pjhill** [comment]
Here's the error --
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNi9NQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc1c92bb689c90e49b1355f85f3c5523f714afae/image.png)

**Comment by pjhill** [comment]
Here's the error --
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNi9NQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc1c92bb689c90e49b1355f85f3c5523f714afae/image.png)

**Comment by pjhill** [comment]
^ trials and tribulations of a picky CI process. Re-creating the change in a new branch from scratch resulted in a passing CI.

Waiting on a review to get this PR merged -- https://github.com/department-of-veterans-affairs/content-build/pull/1793

**Comment by pjhill** [comment]
Merged
