### ISSUE TITLE
[Tech Debt] Claims: Old 526 Submission Flow Cleanup 

### ISSUE THREAD

**Issue by SMLuthi** [department-of-veterans-affairs/va.gov-team#6822]
## Problem Statement
There is an initial implementation of an asynchronous job flow for 526 submissions that had been worked on. It was piggy backing on the work async work vets 360 did at the time. This was deprecated in favor of a custom implementation that fit our needs better. The old code still lives on in the repository, though, and needs to be removed as it is causing confusion.

## Goal
Remove the old unused code from repository and remove the unused table from the schema and the database.

Note: It looks like Charley Stran has done some changes to the tables in the last 9 months. Its very important we investigate that these tables and their associated models are not being used by another team before we rip them out.

---
## Tasks
- [x] Remove file defining `VA526ezSubmitTransaction` Class
- [x] Remove all test files/specs pertaining to `VA526ezSubmitTransaction` Class
- [x] Remove `migrate_dry_run` and `migrate_data` rake tasks from `form526.rake` file
- [x] Investigate if its possible to remove `DisabilityCompensationSubmission` and `DisabilityCompensationJobStatus` models and their associated test specs
- [x] Investigate if we can removed unused tables (`disability_compensation_job_statuses` and `disability_compensation_submissions`), which are associated with the above models, from schema and migrate database

## Acceptance Criteria
- [ ] Clean up repository by removing unused form526 code and database tables

**Comment by SarahJaine** [comment]
Working branch https://github.com/department-of-veterans-affairs/vets-api/compare/sj-remove-VA526ez-vgt6822
