### ISSUE TITLE
Rename the Platform Satisfaction Survey

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#68236]
## Purpose
Is the name clear enough?  I've seen the Support team create the VFS Satisfaction Survey, and it's unclear who's being asked and what they're satisfied about.

Can we employ our SD principles and rename this thing based on what the User thinks it means instead of long-held internal nomenclature?

Based on recent guidance:  Quarterly Platform Satisfaction Survey?
## Tasks
- [x] Utilize our published guidance to Rename it
- [x] Alter survey
- [x] Alter supporting literature
- [x] Publicize it

## Acceptance Criteria
- [x] Name is changed
- [x] New name is publicized
