### ISSUE TITLE
[UX][Design] Create Final Wireframes

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#68244]
## User Story
As a Veteran, I want to know why you keep asking me to verify my information so that I will be less pissed off.

## Tasks
- [ ] Create final wireframes
     - [ ] create a Page in Playground (since this will be for both pre-check-in and check-in)
     - [ ] copy into Unified Design page
- [ ] Give Sketch links to Lori for FE ticket

## Acceptance Criteria
- [ ] Does CAIA need to review? 
- [ ] Does platform design need to review? 
- [ ] Does UX team review? 
- [ ] Does check in team need to review via Slack?  
- [ ] Do VA OCTO PO's need to approve? 
- [ ] Does Lori need link for FE?

**Comment by benbrasso-agile6** [comment]
@loripusey FYI, the solution is looking to be to, 1) edit the pre-check-in default text notification, and 2) add a second pre-check-in text notification that is sent immediately after the first one. As a product team, if we wind up agreeing with this approach, this will be VeText work (pretty simple; they should be able to squeeze it in if we explain that we're looking to impact the drop-offs in the 45MR) and, therefore, we wouldn't need this FE ticket or Design ticket.

**Comment by benbrasso-agile6** [comment]
not needed
