### ISSUE TITLE
[CHIP] Configure CodeQL

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#68253]
## Note
This includes CHIP, LoROTA, and the staging tool.

## Description
Our repo got auto flagged for not having this setup, https://github.com/department-of-veterans-affairs/chip/pull/1862

Automated source code scanning for potential security issues using CodeQL, Dependabot, and Secret Scanning is required for all repositories in the VA GitHub Enterprise Cloud.

There are steps that you will need to take to configure your repository to enable CodeQL code scanning. Dependabot and Secret Scanning will be automatically configured.

The steps that you will need to take to configure your repository to enable CodeQL code scanning will be different depending on whether you are using GitHub CI tools or the external Jenkins CI tool:
- [Start here if you're using GitHub CI](https://department-of-veterans-affairs.github.io/ois-swa-wiki/docs/ghas/codeql-usage/how-to-enable-codeql-github-ci/)
- [Start here if you're using Jenkins CI](https://department-of-veterans-affairs.github.io/ois-swa-wiki/docs/ghas/codeql-usage/how-to-enable-codeql-jenkins-ci/)

Additional resources that you will need when you are configuring your repository to enable CodeQL using the guidance provided in the above-linked technical notes include the following:
- [Software Assurance System ID Catalog](https://github.com/department-of-veterans-affairs/.github-internal/blob/main/swa/emass.xls)
- [Edit CodeQL Analysis Workflow](https://github.com/department-of-veterans-affairs/chip/blob/ghas-enforcement-codeql/.github/workflows/codeql-analysis.yml)
- [Add Excluded Languages List](https://github.com/department-of-veterans-affairs/chip/tree/ghas-enforcement-codeql/.github)
- [Update Production Branch](https://github.com/department-of-veterans-affairs/chip/blob/ghas-enforcement-codeql/.github/workflows/codeql-analysis.yml)
- [Remove Pull Request Trigger](https://github.com/department-of-veterans-affairs/chip/blob/ghas-enforcement-codeql/.github/workflows/codeql-analysis.yml)
- [Create Custom Build Script](https://github.com/department-of-veterans-affairs/chip/tree/ghas-enforcement-codeql/.github)

To request technical support:
- [Please book a meeting with OIS ISO SAVD Software Assurance](https://outlook.office365.com/owa/calendar/OISSoftwareAssurance@DVAGOV.onmicrosoft.com/bookings/)

## emass details
```
CIE eMASS ID: 1963
CIE eMASS System Name: Check-in Experience
CIE Information System Owner (ISO): Christopher Johnston
CIE Information System Owner (ISO) email address: Christopher.Johnston2@va.gov
```

## Tasks
- [ ] [CHIP] implement a first pass at CodeQL
- [ ] [CHIP] close PR https://github.com/department-of-veterans-affairs/chip/pull/1862
- [ ] Update relevant documentations (readme and use cases)

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
codeQL is now configured for all three repos. The scheduling tool does have a high level alert as well as some high level dependbot alerts, that I will tackle as part of this ticket:
https://github.com/department-of-veterans-affairs/cie-staging-scheduler/security/code-scanning

**Comment by brianseek** [comment]
High and critical alerts are taken care of. Moving this to closed
