### ISSUE TITLE
BE | Profile | New Profile Permissions Endpoint

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#68254]
## Background
Currently, the `v0/user` endpoint returns user permissions (used to call these user claims see #66899 where we referred to them as claims, moving forward we're going to call "permissions").  It would be cleaner and more efficient to create a user-permissions endpoint for the Profile so that the FE can determine which Profile endpoints it is authorized to call on behalf of the user.

## Tasks
- [x] Create a Profile User-Permissions endpoint.
- [x] Return user-permissions for all Profile-related endpoints.
- [x] Add a feature flag for this controller endpoint.

## Acceptance Criteria
- [x] Add related specs and ensure proper code coverage.
- [ ] Verify functionality in staging to ensure we've reduced unnecessary traffic between FE andBE .
