### ISSUE TITLE
PM | Hub | Launch (100%)

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#68251]
## Background 
This ticket is for our phased rollout for the profile hub

## Testing Artifacts
- [QA Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/hub/mvp/QA/hub-qa-plan.md)

## Monitoring

- [Domo](https://va-gov.domo.com/page/1834995012/kpis/details/203579416?userId=1539186973)
- [metrics](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/hub/mvp#measuring-success)
- [GA report](https://analytics.google.com/analytics/web/?authuser=0#/analysis/a50123418w177519031p176188361/edit/_K1zzMjpQ2qxlfcC--aNiw)

## Release Plan

- [Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/hub/mvp/hubReleasePlan.md)
## Tasks

```[tasklist]
### 100% rollout
- [x] Update feature flags to make the feature visible in Production for 100% of users
- [x] Track/monitor analytics
- [x] Validate on Prod with PM and PO
- [x] 1st week metrics [12/19-12/26/2023]
- [x] 2nd week metrics [12/27/2023-1/2/2024]
- [x] 3rd week metrics [1/3-1/9/2024]
- [x] 4th week metrics [1/10-1/16/2024]
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/72041
- [x] follow up w GA team about fixing the reporting #72339
- [x] check in w/contact center about #72702
- [x] 508 review completed - audit number 40684 - completed 1/31/2024 no defects
```

## Acceptance Criteria
- [ ] feature is fully deployed in production 
- [ ] documentation has been updated post launch
