### ISSUE TITLE
[UX] Create wireframe w/ content for 'something went wrong' error page (wireframe for echeck-in, not full auth exp) [bene travel past appts]

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#68279]
## Description 

How might we take the[ full-auth design of the error scenario](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/98CB31ED-7EE2-4BFD-84A2-87826FCEECA8/canvas#Version) and iterate it to conform to some of the nuances of PCI, specifically within the unified check in experience (Sketch file). For example, does content on page overlap with content in our Need Help component? Are we using different components? For example, have we switched to USWDS v3 alert component yet or not? 

## Tasks
- [ ] Create wireframe with content
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [ ] UI review meeting with product/UX team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.
