### ISSUE TITLE
Replace multi-selectable checkboxes with radio buttons

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#68276]
## Issue Description
Design has replaced representative checkbox inputs to a radio button. These radio buttons should conditionally update the representative search input label. This change will require modifications to the Redux logic, as well as adjustments to the frontend API request logic since the representative type is no longer an array of options but limited to one option.

---

## Tasks
- [ ] Replace checkbox inputs with radio buttons.
- [ ] Implement conditional label updates for the representative search input.
- [ ] Modify Redux logic to accommodate the new radio button inputs.
- [ ] Update frontend API request logic to handle the changed representative type.

## Acceptance Criteria
- [ ] Radio inputs with conditional rendering of representative input label
- [ ] Representative type is no longer of type array in state + API logic
