### ISSUE TITLE
[UX] [Design] Create wireframes for canceled appts

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#68281]
## Tasks

- [x] Create an appt, cancel it, then use the pre-check-in link to see the experience 
- [x] Create an appt, cancel it, then use the check-in link to see the experience 
- [x] Create alert wireframe needed for displaying when an appt has been cancelled for pre-check-in
- [x] ~~Create wireframes (or components) needed for displaying when an appt has been cancelled for checking in~~ 
- [x] Create wireframe that shows the design pattern for a cancelled appointment in the appointment list. [VAOS uses a strikethrough](https://www.figma.com/file/xRs9s6QWoBPRhpdYCGc3cV/User-Flow?type=whiteboard&node-id=155%3A30914&t=1S8UkB6pnfapt9VY-1). [Here's another example](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?type=design&node-id=5359%3A89369&mode=design&t=yozlwtRFGx4A5Uk9-1). 
- [x] Create detail page wireframe for an upcoming cancelled appt. [VAOS cancelled appt](https://www.figma.com/file/RcDljBwThbwVDkNrDH2xiA/Appointment-Details-Redesign?type=design&node-id=2237%3A84511&mode=design&t=yozlwtRFGx4A5Uk9-1). Ask them what the options are for Canceler. 
- [ ] Add wireframes into Unified Design and Design Priority 1 Pages 
- [ ] Create any needed markup into Sketch Page(s) for heading annotations, aria label values or link paths

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by loripusey** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/68281?planning-poker) with Zenhub @benbrasso-agile6

**Comment by benbrasso-agile6** [comment]
K, I'll edit the Tasks then

**Comment by kellysmith1008** [comment]
Of course! I can get that together first thing tomorrow morning

**Comment by benbrasso-agile6** [comment]
Hmmmmm, oh, you know what? Would you mind retrying but text "check in" to... gosh let me find the staging number.

**Comment by benbrasso-agile6** [comment]
Try 2542782622

Because I think for check in, it might be a text to ensure the content feels correct.

**Comment by kellysmith1008** [comment]
Makes sense - trying now

**Comment by benbrasso-agile6** [comment]
You might actually need to do the same for pre check in too. Because it's possible that VeText won't give you a link to start pre check in if it's been cancelled.

**Comment by benbrasso-agile6** [comment]
Updated content ticket, which is in next sprint https://github.com/department-of-veterans-affairs/va.gov-team/issues/70820

**Comment by ytsaoca** [comment]
Had some ideas for the detail page and appointment status icon with questions for discussion in the [Sketch page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/04C2CEC7-895F-4D1E-93A8-6BA0F1B97FED/canvas). Feel free to come up with other ideas or decide the direction to move forward to. @zach-park

**Comment by benbrasso-agile6** [comment]
Thanks Ya-Ching! Will check tomorrow!

**Comment by benbrasso-agile6** [comment]
[Alert design](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/04C2CEC7-895F-4D1E-93A8-6BA0F1B97FED/canvas) - passed this to Kelly's ticket for next sprint

**Comment by benbrasso-agile6** [comment]
@zach-park tagged you on a couple comments for appt list page and detail page

**Comment by benbrasso-agile6** [comment]
Added these to Kelly's ticket for next sprint for content review:

https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/04C2CEC7-895F-4D1E-93A8-6BA0F1B97FED/canvas#Version

https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/4BACBAC3-9221-4B54-BCAC-3E2424DD408B/canvas#Version

**Comment by benbrasso-agile6** [comment]
Validated
