### ISSUE TITLE
Copy of Copy of [UX] Create wireframe w/ content for 'claim already filed' error page (wireframe for echeck-in, not full auth exp) [bene travel past appts]

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#68280]
## Tasks
- [ ] Create wireframe with content
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [ ] UI review meeting with product/UX team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.

**Comment by loripusey** [comment]
duplicate
