### ISSUE TITLE
[FE] Dot indicator: Update appointment card date and time styling (dot indicator staging review)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#68293]
## Background
From the dot indicator staging review there were two content issues found in the appointments card related to styling of dates and times.

- #68264 (styling of dates, 4th > 4)
- #68263  (missing periods in a.m./p.m.)

Angela made the design and documentation updates in #68290 , this ticket is to make the changes in the code.

## Tasks
- [x] Update date and time scheduling in code
- [x] Test
- [x] Tag designer for validation

## Acceptance Criteria
- [ ] Date and time formats are updated to match style guidance from content feedback tickets

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ 
1. Log into staging with a test user with an upcoming appointment
2. Scroll to health care section and locate appointment card
3. Confirm that ordinals are not used and that periods are included in a.m./p.m.

**Comment by ajakabcin** [comment]
@allisonlu Angela updated the [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/health-care-FE-documentation.md#next-appointment-card) in case you need it for reference!

**Comment by allisonlu** [comment]
@ajakabcin @aagosto90 

ready for validation! Cecil has an upcoming appointment where this update is visible 😃

**Comment by aagosto90** [comment]
Looks perfect to me. Thanks @allisonlu

**Comment by ajakabcin** [comment]
Ditto - thanks @allisonlu !
