### ISSUE TITLE
Prototype Discovery

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#68297]
## Issue Description
_This issue consists of all the discovery needed to start building a high-fidelity prototype that meets VA standards._

---
## Tasks
- [ ] _Review documentation on prototype/VA design standards._
- [ ] _Review forms prototypes from other teams._
- [ ] _Do discovery research on VA Sketch workflow._
- [ ] _Consolidate form components in Sketch to prepare for creation._

## Acceptance Criteria
- [ ] _Sketch for prototype is created with access to proper VA components._
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by StevenStraily** [comment]
Part of this task will be blocked by our continued exploration into the possibility of using Figma.

It would make more sense to change the actionables here to get things set up in Figma once that decision has been finalized.
