### ISSUE TITLE
[FE] 10-10EZR - Add Identity Verification Alert to Introduction Page

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#68292]
## Description
For the Introduction page, we need to limit access to the API calls and form start button for users who have an account status of LOA1 on VA.gov. LOA1 users have created their account, but have not verified their identity by providing documentation to the authentication provider. For this we need to add an alert that will take the place of the Save-In-Progress components that control form entry and enrollment status verification.

## Tasks
- [x] Create alert component and populate with appropriate content
- [x] Update authentication selector to include LOA1 status
- [x] Conditionally add alert to introduction page
- [x] Unit test all components & conditional logic

## Acceptance Criteria
- LOA1 users must verify their identity before gaining access to the form
- LOA3 or guest users will see the traditional SIP components rendered
