### ISSUE TITLE
[Design] Dot Indicator: Address styling issues in appointments card (dot indicator staging review)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#68290]
## Background
From the dot indicator staging review there were two content issues found in the appointments card related to styling of dates and times.

- #68264 (styling of dates, 4th > 4)
- #68263  (missing periods in a.m./p.m.)

## Tasks
- [x] Update sketch file designs to correct date and time styling
- [x] Update FE documentation as needed
- [ ] Hand-off to FE dev for implementation

## Acceptance Criteria
- [x] Sketch files and documentation updated

**Comment by aagosto90** [comment]
Sketch file was up to date; made [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/health-care-FE-documentation.md#next-appointment-card) more clear re: formatting rules.
