### ISSUE TITLE
[Design] Dot indicator: Design and documentation updates for a11y findings

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#68307]
## Background
Staging review for the dot indicator turned up two a11y findings that require some design and FE documentation updates:

- #68258
- #68259  

## Tasks
- [x] Update sketch files with corrections
- [x] Update documentation to reflect corrections
- [x] Hand of to FE for implementation in code

## Acceptance Criteria
- [x] Sketch and documentation updates are complete

**Comment by aagosto90** [comment]
No update was needed to Sketch file annotation but I clarified a11y feedback with Ryan Smith [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68258#issuecomment-1779982201) and updated [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/dot-indicator/create-dot-indicator/documentation/my-va-health-care-inbox-dot-indicator-FE-documentation.md). We should link both of these in the FE implementation ticket @ajakabcin
