### ISSUE TITLE
Housing expenses (Mortgage/Rent) and Other expenses updates

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#68302]
### Housing expenses (Mortgage/Rent) 
Users will enter the total of their mortgage and/or rent expenses in a numeric input field instead of the checkbox > summary page list loop.
_Text:_ 
> What is the total amount you pay for rent and/or mortgage payments each month?(*Required) 
> Mortgage can include homeowners insurance, property tax, private mortgage insurance (PMI), and Community Development District (CDD) fees.

Current version:
<img width="348" alt="monthly-housing-current" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/5553542/2907fc6e-a1f5-40cb-8bd5-c08158161e73">

Proposed version:
<img width="352" alt="housing--expenses (1)" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/5553542/b24a1e89-8acf-463b-ad2a-adeda0439e9f">

### Other expenses updates

_The following fields would be removed from the Monthly Housing expenses section and added to the Other Living Expenses section of the form:_ 
>  - Homeowner’s Association fees (HOA)
>  - Renters insurance
>  - Transportation and car expenses (including insurance)

Current version:
<img width="353" alt="other-living-current" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/5553542/1efdfaff-bc1a-42c4-ae5d-fe299d527ea9">

Proposed version:
<img width="377" alt="other--living-expenses (1)" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/5553542/4ced8e5c-1d2b-48b2-86c0-cf35e17ff98f">

## Tasks
- [ ] Remove checkboxes and summary for Housing expenses (Mortgage/Rent)e expense section and replace with numeric input
- [ ] Updated Other expenses checkbox list 
## Acceptance criteria

- [ ] Housing expenses (Mortgage/Rent) is replaced with numeric input
- [ ] Other expenses checkbox list has been updated

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description
---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [ ] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by HeatherRienks** [comment]
Per FE Sync, this is a significant change; let's add into S113 (Nov 22 -12/5). We will need a FF for this work.
Is there anywhere else on the form where we want to apply this? Need to discuss with the team.

**Comment by HeatherRienks** [comment]
@Tom-Davis -let's discuss this in Standup on 11/15/23.

**Comment by HeatherRienks** [comment]
@Tom-Davis -Not sure if we will be able to bring this into S113; let's discuss with team in Planning on 11/21/23.

**Comment by denisecoveyduc** [comment]
@mgleo @josephrlee Can you confirm that we still want to do this? IF so are there designs you can drop here for a visual? I am struggling to follow what is written here to understand the change.

**Comment by mgleo** [comment]
Hi @denisecoveyduc, here is a Slack thread where this first was brought up: [https://dsva.slack.com/archives/CPE4AJ6Q0/p1680100304721589](https://dsva.slack.com/archives/CPE4AJ6Q0/p1680100304721589)
It sounds like this was requested because of how the paper form is set up. This was before the announcement that forms should be digital first, should we still proceed? 

This section of the form currently features the checkbox list loop: 
<img width="377" alt="other--living-expenses (1)" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/5553542/f6ccd973-6833-427a-bef8-2dee77a35c23">


The update would update it from a checkbox list loop pattern to asking for a numeric input of 
<img width="352" alt="housing--expenses (1)" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/5553542/d405b3ea-a5ce-40e8-b756-8f9134d2061e">

I just updated the content of this ticket with more images as well.

**Comment by Dr-Pongo** [comment]
Hiding these changes behind a new feature flag `financial_status_report_expenses_update`

**Comment by HeatherRienks** [comment]
Per Mikki with CAIA, we will need to submit a CAIA ticket for support of our new page.

FYI @Tom-Davis

**Comment by Dr-Pongo** [comment]
The feature flag we'll use to control these changes have been merged! Continuing local development, but running into some local environment issues, so this ticket is definitely rolling into spring 125!

**Comment by Dr-Pongo** [comment]
This ticket is super straight forward, but I'm taking a little extra time to read up on implementing [web component patterns](https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-use-web-component-patterns) so we can eventually move away from the heavily customized pages we've implemented so far. Utilizing these standards will make our app more consistent with the rest of the forms on the VA.

**Comment by HeatherRienks** [comment]
CAIA ticket #83006 created for IA help

**Comment by Dr-Pongo** [comment]
Thanks for the resource @josephrlee ! It doesn't appear that there is a component field or pattern for currency at the moment, so I've been investigating alternative options

**Comment by josephrlee** [comment]
@Dr-Pongo, I see. It looks like the DST team is [still working on adding the currency support](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2105#issuecomment-1997945062) to the `va-text-input`.

**Comment by Dr-Pongo** [comment]
@josephrlee yup! Need to make sure that gets into the field mapping as well so all of the props are happy for the `ui:webComponentField` (which I believe [is getting added to the task list](https://dsva.slack.com/archives/C01DBGX4P45/p1715799334446909?thread_ts=1715796782.682509&cid=C01DBGX4P45) for that ticket now). I may pivot and leave the dollar sign out until it's properly supported by platform to avoid any messy css customization. I noticed even the spouse benefits information section does not have the dollar sign in the input box and is relying on a classname that we don't have defined

**Comment by josephrlee** [comment]
@Dr-Pongo, Oh interesting, I wonder if that undefined class was deprecated during the platform cleanup for the v3 stuff.

**Comment by Dr-Pongo** [comment]
@josephrlee I only found one reference not in a specific app, and it was implemented seven years ago, so I'm guessing it's probably deprecated lol there is a custom `v3` one that's been defined in a specific app, but that's about it. Going to see if we can keep a pulse on the platform updates so we know hwen currency is available for us to use

**Comment by Dr-Pongo** [comment]
@josephrlee included some screenshot in my PR below!
department-of-veterans-affairs/vets-website#29829

**Comment by Dr-Pongo** [comment]
Created follow on ticket to write some robust tests for new data structure 
- [FSR] Housing expenses testing [#83576](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/83576)

**Comment by Dr-Pongo** [comment]
Changes have been merged!
