### ISSUE TITLE
[FE] Dot indicator: a11y fixes from staging review

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#68309]
## Background
Staging review for the dot indicator turned up two a11y findings that require some design and FE documentation updates:

- #68258 
- #68259  

See resources below for updated documentation and guidance from a11y on implementation.

## Tasks
- [x] Implement changes outlined in the feedback tickets
- [x] Test
- [ ] Request validation from designer

## Acceptance Criteria
- [ ] Link text is included in aria label
- [ ] Aria label is hidden for icon
- [ ] No aria label when there are no unread messages 

## Resources
- [Guidance from Ryan Smith for aria label change](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68258#issuecomment-1779982201)
- [Updated FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/dot-indicator/create-dot-indicator/documentation/my-va-health-care-inbox-dot-indicator-FE-documentation.md)

**Comment by allisonlu** [comment]
@ajakabcin @aagosto90 

Ready for validation! If you log on as Cecil Morgan, inspect the "Go to your inbox" link, and verify that you see the attributes in the **After** screenshot:

| Before | After |
 | ------ | ----- |
 |      ![Screenshot 2023-11-03 at 3 35 07 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/8542413/60fee032-8a88-490b-928b-282f95c336c4)  |     ![Screenshot 2023-11-03 at 3 34 38 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/8542413/e2436feb-3484-46fc-acf8-fb419ed6f9b2)  |

**Comment by aagosto90** [comment]
Validated in staging! Thanks @allisonlu !
