### ISSUE TITLE
Remove Flippers used for eMIS/VA Profile work

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#68316]
### Summary
Once the VA Profile work is tested and flippers have been enabled in all environments, we can consider the feature tested and can delete the flippers. We might want to do this in multiple PRs. Remove `:military_information_vaprofile` in its own PR, since I think it will be the largest. 

### Tasks
- From vets-api, remove the following flippers and any code that is unused from removing these flippers: 
  - [x] `military_information_vaprofile`. Among other things, this will make `initialize_military_information_vaprofile` in form_profile unused and I believe `lib/hca/military_information.rb` and its tests can also be removed. (For context, we originally removed that file, but then added it back in when we wrapped everything in the `military_information_vaprofile` flipper.)
  - [x] `military_information_vaprofile_vic`
  - [x] `veteran_status_updated`
- [x] After the code is deployed, go into the rails console in an Argo pod in each environment and delete the flipper using the command: `Flipper.remove(:feature_name)`. (Please also remove  the`military_information` flipper. When I renamed this one, the old name stuck around and I never went back and deleted it 😄)

### Validation
- [x] go to the flipper UI for each env and make sure `military_information_vaprofile`, `military_information_vaprofile_vic`, `military_information`,  and `veteran_status_updated` are not there.
    - [x] https://api.va.gov/flipper/features
    - [x] https://dev-api.va.gov/flipper/features
    - [x] https://staging-api.va.gov/flipper/features
    - [x] https://sandbox-api.va.gov/flipper/features

**Comment by laineymajor** [comment]
This needs to wait until after the code freeze

**Comment by laineymajor** [comment]
Work will continue on this during our part 2 of the double sprint.

**Comment by jennb33** [comment]
Per @rjohnson2011, this work carried over to the 1/18-1/30 Sprint because after his first pass on the recreate prometheus breakers charts in datadog ticket, @LindseySaari requested modifications as well as another dashboard dealing with latency. The latency metrics were not 'out of the box' in DD and had to be manually recreated which took an extra couple days. Those were days Ryan was going to be working on the Flippers ticket but ended up doing additional work to finish up the DD dashboard one.

**Comment by jennb33** [comment]
There were some spec failures on 1/17, but @rjohnson2011 worked it out and plans on having a PR to send to @rmtolmach on 1/18

**Comment by jennb33** [comment]
@rmtolmach reviewed this and has some changes to be made. We need to make changes to another file when @rjohnson2011 is back on 1/25.

**Comment by rmtolmach** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/68438 is also being covered in the flipper removal work. @rjohnson2011 make sure the tasks in that ticket are also covered.

**Comment by jennb33** [comment]
@rjohnson2011 is waiting for final approval from Trevor or @rmtolmach, then a final step in Argo. Ticket should be closed by the end of the Sprint.
