### ISSUE TITLE
Investigate utilizing EFS storage with an EKS service for hosting content-build and vets-website static content for preview environments

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#68310]
## Description
Investigate utilizing EFS storage with an EKS service for hosting content-build and vets-website static content for preview environments

---
### Tasks
- [x] Understand how EFS connects to a helm pod
- [x] Understand how to use Traefik to route URI's inside a namespace
- [x] Understand the methods of getting content to EFS
- [x] Test various EFS populating methods

### Acceptance Criteria
- [x] Architecture diagram of computing solutions
- [ ] Decision Made on whether to use EFS and EKS or a hosted S3 bucket
