### ISSUE TITLE
[Design] Onsite Notifications: Update documentation to remove notification section

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#68319]
## Background
Since we have removed the notification section from My VA we need to update our documentation and designs to reflect this change.

## Tasks
- [x] Update documentation to remove notifications section
- [x] Update sketch files to remove notifications section from designs

## Acceptance Criteria
- [x] Notifications section removed from documentation and designs

**Comment by aagosto90** [comment]
Didn't see this in any other documentation besides docs specific to notifications. I did make a bunch of updates to the health care FE documentation and reviewed all other FE documentation ([most of which is currently living here](- [Desktop mockup](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/VradRV8)
- [Mobile mockup](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/YGlJVpL))) to check for accuracy.
