### ISSUE TITLE
Off-boarding/transition prep - Angela Agosto

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#68317]
## Background
Prep for Angela's transition off the auth experience My VA team.

## Tasks
- [x] Prep a "hand-off" doc with resources for new designer (links to latest designs, helpful docs etc)
- [x] Review [onboarding ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35751) and provide feedback to PM for any updates to make for new team member
- [x] Share any other helpful transition materials with PM, PO, and DM

**Comment by aagosto90** [comment]
[Transition doc for Matt is here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/team/My-VA-UX-designer-transition-doc.md)

**Comment by aagosto90** [comment]
@ajakabcin The onboarding ticket linked will need obvious updates since it's almost 2 years old but I think a recent project to add to it for the next designer to check out would be the My VA audit. I think the Platform onboarding docs include anything else I haven't included in my transition doc.
