### ISSUE TITLE
[FE] My VA: Implement white card design on My VA

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#68314]
## Background
The design system has moved toward a white card component design over the gray cards we've been using on My VA. Angela completed design and documentation updates in [67372](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67372) so now we need to make the change in our code.

## Tasks
- [x] Implement white card design on My VA behind a feature flag
- [x] Test (update tests as needed)
- [x] Let PO, PM and designer know when ready for validation

## Acceptance Criteria
- [x] White card design implemented on My VA

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member_
- _How can this work be validated?_ sign in to My VA with any test user and review white card design implementation

**Comment by allisonlu** [comment]
@ajakabcin @aagosto90 

I turned [on the feature flag](https://staging-api.va.gov/flipper/features/my_va_experimental_frontend), so the white cards should be showing for all users! 

Cards to check: 
- Claims and appeals > Claim
- Claims and appeals > Appeal
- Health care > Next appointment
- Outstanding debts > Debt
- Outstanding debts > Copay
- Benefit payments
- Benefit application drafts > Application in progress
- would probably be beneficial to check a user who has multiple application drafts (**user 41** has four!)

**Comment by aagosto90** [comment]
Looks good to me, thank you @allisonlu !!
