### ISSUE TITLE
Investigate requirements for WASA scan

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#68313]
### Description
Research and gather the specific requirements needed to successfully conduct a WASA scan.

Reference: [Link](https://vfs.atlassian.net/wiki/spaces/PSEC/pages/1972895799/Web+Application+Security+Assessment+WASA)

---
### Tasks
- [x] Discuss WASA scan context and background w/ @pjhill 
- [ ] Identify the primary objectives for the WASA scan.
- [ ] Research documentation or specifications related to WASA scans.
- [ ] Document the requirements and recommended preparation steps for the scan.

### Acceptance Criteria
- [ ] A clear and comprehensive list of requirements for the WASA scan has been produced.
- [ ] Recommendations and preparations for the WASA scan have been documented.

**Comment by pjhill** [comment]
I sent Patrick a bunch of emails inside the VA network (VA email to VA email). I'm a little concerned about declaring all the values that we will need to submit to request a WASA scan as I'm not sure how sensitive each of the bits of information is.  I did start a Confluence page here with the beginnings of the values that will be required --
https://vfs.atlassian.net/wiki/spaces/PRT/pages/edit-v2/2823127163?draftShareId=9b62db19-6d75-4daf-93d8-379e2b1e91aa
