### ISSUE TITLE
[bug] SC | Email validation 422 error

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#68323]
On October 24th, we saw two subsequent failed submissions from user_uuid `4b8628b44aee4489a126b94a16d06a86`. See [Sentry](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?environment=production&field=title&field=release&field=environment&field=user.display&field=timestamp&name=Common%3A%3AClient%3A%3AErrors%3A%3AClientError%3A+the+server+responded+with+status+422&project=3&query=issue.id%3A234860+user.id%3A%224b8628b44aee4489a126b94a16d06a86%22&sort=-timestamp&statsPeriod=24h&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1).  The submissions fail with the following error:

```json
{
  "errors": [
    {
      "code": "142",
      "detail": "'' did not fit within the defined length limits",
      "meta": {
        "max_length": 255,
        "min_length": 6
      },
      "source": {
        "pointer": "/data/attributes/veteran/email"
      },
      "status": "422",
      "title": "Invalid length"
    },
    {
      "code": "149",
      "detail": "'' did not match the defined format",
      "meta": {
        "format": "email"
      },
      "source": {
        "pointer": "/data/attributes/veteran/email"
      },
      "status": "422",
      "title": "Invalid format"
    }
  ]
}
```

Interestingly, the Veteran's SIP form_data does not specify the Veteran's email. So, it is possible that we somehow failed to require the Veteran's email on the front-end. Perhaps this is related to https://github.com/department-of-veterans-affairs/va.gov-team/issues/67187.

## Tasks
- [ ] Determine root cause of error
- [ ] Create plan for resolution
- [ ] Think about whether short-term intervention is necessary/feasible
- [ ] After discovery complete, add estimate, remove `needs-refinement` and `needs-estimate` labels, remove `[bug spike]` prefix in the title of this PR, and update these tasks and AC, DoR, and DoD below.

## Acceptance Criteria
- [ ] Root cause of error is known
- [ ] Can reproduce 422 error locally (and if possible, on staging)
- [ ] Bugfix complete and works locally (and if possible, on staging)
- [ ] Bugfix deployed

## Definition of Ready
- [ ] Root cause of error is known

## Definition of Done
- [ ] Acceptance criteria met
- [ ] Veteran has been notified of bugfix by contact center.

**Comment by Mottie** [comment]
Hmm, please check what email was submitted. If it less than 6 characters or empty emails, the Veteran will be blocked from submission. I don't know this got past the frontend validation and was submitted.

| Invalid email | Missing email |
|---|---|
| <img width="671" alt="review & submit accordion showing error in header with email of 1@1.z" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/0581f1d8-95fb-41de-acd6-a7b30141221d"> | <img width="665" alt="review & submit accordion showing error in header & missing email message in line with email entry" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/0017b989-b2e2-429d-ab6d-33bcfb2d647b"> |

**Comment by Mottie** [comment]
Work on this may be fixed by [adding validation to all contact info fields in this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/26426).

**Comment by rocio-desantiago** [comment]
saw this again with
user.id: 4b8628b44aee4489a126b94a16d06a86
icn: 1034681029V240416

**Comment by saderagsdale** [comment]
This will be solved by work on #67187

**Comment by data-doge** [comment]
This issue will be resolved going forward by https://github.com/department-of-veterans-affairs/vets-website/pull/26426. As for the particular Veteran affected here, because VA profile returned no email, we have no email to give to Kimberley to follow up. I am also unable to get an email via `MPI::Service#find_profile_by_identifier`. I don't have any workarounds yet, but just wanted to note what I've already tried.
