### ISSUE TITLE
[BE] Cache setECheckInCalled to log metrics for 45-minute Text reminder

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#68333]
## Description

Cache setECheckInCalled to log metrics to capture,
- How many Veterans used the 45-minute reminder & completed check-in
- How many Veterans used the 45-minute reminder and did NOT completed check-in
- How many Veterans used the text "check in" & completed check-in
- How many Veterans used the text "check in" and did NOT completed check-in 

## Tasks
- [x] [BE] **Cache setECheckInCalled in redis in PatientCheckInsController GET**
- [x] [BE] **Add logs in PatientCheckInsController GET to get number of veterans using 45-minute text reminder feature**
- [x] [BE] **Read setECheckInCalled in redis in PatientCheckInsController POST**
- [x] [BE] **Add logs in PatientCheckInsController POST to get number of veterans completing check in with setECheckInCalled**
- [x] [BE] **rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by loripusey** [comment]
@kanchanasuriya where are we with this one?
cc: @anita-halici

**Comment by loripusey** [comment]
@randomsync can you help @kanchanasuriya move this one along?

**Comment by randomsync** [comment]
merged and released to prod
