### ISSUE TITLE
Create GFE SOCKS configuration documentation 

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#68339]
## Description 
Brandon and I have both come across requests for SOCKS access on a GFE now in the support channel, and a user has alerted me that other team members will also need that same access. It has come to our attention that to access Review Instances, even on a GFE you need to have SOCKS access because they are behind VPCs and not just behind the VA Network. This is a pretty rare situation typically as all other things we seem to need SOCKS for is to just access tools that are accessible by default on the VA-side (CAG/Azure/WVD/GFE). 

GFEs are locked down a lot for understandable reasons, and you cannot put SOCKS on them using the methods in our current documentation, you have to use Git Bash or run Ubuntu in a VM to run it as an admin which is crucial on a Windows machine. This is actually documented in the old way SOCKS was configured and also resurrected in a recent thread with Patrick Bateman. 

In order to support one existing user and further support any incoming requests for this odd occasion, the team needs to have a process in place. 
---

## Definition of Done
All tasks below must be completed 

---

## Tasks 
- [x] Confirm steps to install SOCKS on GFE with Tier 2 / possibly Clint 
- [x] Find someone to help gather screenshots or configure on CAG possibly?
- [x] Walk user through SOCKS request and configuration on GFE 
- [x] Document experience to improve steps
- [x] Create Confluence documentation 
- [x] Walk team through it
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
[Patrick Bateman always has a fix](https://dsva.slack.com/archives/CBU0KDSB1/p1677864497170029?thread_ts=1677172794.605499&cid=CBU0KDSB1)

---

**Comment by lindsay-insco** [comment]
Reached out to Clint for info on GFE permissions.

**Comment by lindsay-insco** [comment]
Rough draft of GFE configuration created in Google Document and feedback received from Hector Barreto https://docs.google.com/document/d/1tblyy_GtQt1aFQtjprAL5NFcMz3jAFDuDw13rQg2f30/edit

So far user has been able to get through grabbing their SSH keys and getting their request in. Will verify final configuration when they return to the conversation.

**Comment by lindsay-insco** [comment]
Confluence draft crafted and sent to Hector Barreto for review first : https://vfs.atlassian.net/l/ce/znQpNKJZ

So far the process is working for a user who needs a bit more concise communication. Draft will evolve as process finalizes with current user and then go to Clint for review before final draft is posted in support Confluence space.

**Comment by lindsay-insco** [comment]
Published to internal Platform Support Confluence Document and added to Launched Support Enhancements Document!
