### ISSUE TITLE
Review findings regarding ITF and define next steps

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#68346]
## Issue Description

**User stories**

As a veteran filling our the Pension claim form,
I want to make sure that the online form is capturing my Intent to File (ITF) when I first start the form (and not when I submit),
So that when my benefits are awarded, they can backdate them to this date and my claim can be processed as fairly as possible.

As a new Pension team,
we need to understand how to set up an Intent to File (ITF) date to the VBA,
so that veterans can have their benefits backdated to the date when they first started to fill out to the form (and saved) without having to finish it.

As a new Pension team,
we need to understand if we can change the ITF date from the submission_date to the creation_date ASAP,
so that veterans can have their benefits backdated to the date when they first started to fill out to the form (and saved) without having to finish it.

How might we start transitioning the Pension form's ITF date captured from "submission" to "create"?

**This is a follow on task from #66958**

## Research Findings

**Tasks:**
- Researched if there is an existing mechanism for providing the specific ITF date to VBA, and if not, what it would take to build one.
- Research whether and how we can submit a create date rather than submit date as part of the new form

**Findings:**

- It looks like there already exists a mechanism to fetch existing ITFs as well as create new ITFs.
- However, **ITF info isn't stored in our system**, so it invokes either Lighthouse or EVSS APIs to fetch or create.
- There is a ClaimsApi::IntentToFile table in our system database, but it looks like it's only used for reporting purposes to track the daily success/failure number of ITFs submitted to the BGS.
- **We don't have any routes or endpoints for modifying an existing ITF**, but we can view a list of all past ITFs so we may be able to track down the ITF date when the claim was first created.
- Also, I'm unsure if attempting to create a new ITF when there's currently an active ITF will auto deprecate the old one, or if it'll just error out. Seems like it might error out, since **I see some logic in our application with conditionals stating things like "if there is no active ITF and createITF hasn't already been called, submit a new ITF".**
- **It doesn't look like we can pass in a specific date when creating a new ITF**. And it might also be a bit tricky to consistently figure out the "create date" for veterans who have already filed a claim to try and backdate their benefits.

---
## Tasks
- [x] Review research findings regarding the current state of an Intent to File mechanism on the existing Pension form
- [x] Determine **whether we need to transition to Lighthouse Benefits API** in order to create an Intent to File based on the date the form was "created" or "started".
- [x] **Determine next steps to create an Intent to File** based on the date the form was "created" or "started" by the veteran.

## Acceptance Criteria
- We will have an understanding on whether we need to transition the existing Pension form to Lighthouse Benefits Intake API or rely on another mechanism to create an Intent to File date.
- We will have a rough plan created to determine next steps to do this with the goal to create an Intent to File based on the date the form was "created" or "started".

**Comment by vbellissimo** [comment]
Tagging @mjknight50 so you're aware

**Comment by mjknight50** [comment]
This is completed.  I have reviewed the findings and created two tickets to track next steps.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/69273
https://github.com/department-of-veterans-affairs/va.gov-team/issues/66844
