### ISSUE TITLE
Add step to New VFS Team Member ticket to complete New VFS Team ticket

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#68347]
## User Story
As a new PM and/or DM on a new VFS team (not an existing team), I want to make sure I'm getting all orientation steps completed, including New VFS Team orientation, so that I am not held accountable for missing anything critical. 

Assignee: @erinrwhite 
Peer Reviewer: @allison0034 

## Description
The New VFS Team Member ticket is well known and completed by most new VFS team members (as far as we can tell). However, the New VFS Team template is not as well known and has not been completed by several of the new teams joining VA.gov. In order to remedy this, Governance team will be adding a step to the New VFS Team Member ticket, specifically under Product Managers & Delivery Managers, for them to open the New VFS Team ticket _if they are on a new VFS team._

## Impacted Artifacts
[New VFS Team Member template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=analytics-insights%2C+analytics-request%2C+governance-team%2C+platform-orientation&projects=&template=orientation-epic.md&title=New+VFS+Team+Member+Template+%5BYour+name+here%5D)

## Tasks
- [x] Add a checklist item to the Product Managers & Delivery Managers section, under "Request PM intro with Shira" step. Checklist item should say:
   - If you are on a new VFS team, please complete the [New VFS Team](https://depo-platform-documentation.scrollhelp.site/getting-started/guidance-for-new-teams-and-team-members#Guidancefornewteamsandteammembers-NewVFSteams) ticket as well as there are important team-specific tasks that Platform requires. This step is not necessary if you're a new Product Manager or Delivery Manager on an existing VFS team. (feel free to wordsmith!)

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] New Product Manager and New Delivery Managers are directed to open a New VFS Team ticket during their Platform Orientation

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
[Pull request for new VFS team member ticket](https://github.com/department-of-veterans-affairs/va.gov-team/pull/68434) no rush @allison0034

**Comment by allison0034** [comment]
This looks good also!

**Comment by erinrwhite** [comment]
Thank you @allison0034 - squashed and merged! 

Final issue template [Product Manager and Delivery Manager](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/orientation-epic.md#product-managers--delivery-managers) section ready for final review.

**Comment by shiragoodman** [comment]
@erinrwhite could you please update the link to the New VFS Team ticket to link out to Platform Website instead of the actual gh ticket? The reason for this is so we don't have to update the url to the gh ticket in more than 1 place. If we add new assignees and/or labels to the gh ticket, then the link has to be updated to several places. However, if we always link out to Platform Website, we can guarantee that they're creating a new gh ticket from the same link everytime.

**Comment by erinrwhite** [comment]
aye, @shiragoodman thanks for pointing this out to me! The link in the issue template is now updated to point to Platform website. @allison0034

**Comment by allison0034** [comment]
Looks good!

**Comment by erinrwhite** [comment]
Updated:
- [Product Manager and Delivery Manager section of new VFS team member template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/orientation-epic.md#product-managers--delivery-managers)

Closing. Thanks @allison0034 for the review!
