### ISSUE TITLE
Add unique labels to New VFS Team and New VFS Team Member tickets

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#68348]
## User Story
As a Platform team member, I want to have unique gh labels on the new vfs team tickets and new vfs team member tickets so that I can easily query them within github to report metrics.

Assignee: @erinrwhite 
Peer Reviewer: @allison0034 

## Description
Both new vfs team and new vfs team member tickets to not have unique labels, meaning it is difficult to find them in gh if/when needed.

The purpose of this ticket is to add the labels `new-vfs-team` and `new-vfs-team-member` to the appropriate gh tickets.

## Impacted Artifacts
[Guidance for new teams and team members](https://depo-platform-documentation.scrollhelp.site/getting-started/guidance-for-new-teams-and-team-members)
New VFS Team Member template
New VFS Team template

## Tasks
- [x] Create the labels `new-vfs-team` and `new-vfs-team-member` in the [va.gov-team Labels](https://github.com/department-of-veterans-affairs/va.gov-team/labels) space
- [x] Add the `new-vfs-team` label to the New VFS Team template
- [x] Add the `new-vfs-team-member` to the New VFS Team Member template
- [x] Create pull requests for both and ensure the label is populating correctly
- [x] Merge pull requests once approved
- [x] Edit the urls on the Guidance for new teams and team members page on Platform Website

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] New VFS teams and New VFS team members are opening orientation tickets with the correct labels assigned
- [x] Platform is able to easily search and query for these tickets

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
[Pull request for new VFS team ticket](https://github.com/department-of-veterans-affairs/va.gov-team/pull/68433)
[Pull request for new VFS team member ticket](https://github.com/department-of-veterans-affairs/va.gov-team/pull/68434)

**Comment by erinrwhite** [comment]
- Label listed at [top of new VFS team member template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/orientation-epic.md) has new-vfs-team-member tag
- Label listed at [top of new VFS team template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/new-vfs-team.md) has new-vfs-team tag
- Links updated on [Guidance for new teams and team members page](https://vfs.atlassian.net/wiki/spaces/GS/pages/2132803700/Guidance+for+new+teams+and+team+members) on Platform website

Ready for review @allison0034

**Comment by allison0034** [comment]
I see the labels!

**Comment by erinrwhite** [comment]
Updated:
- Label listed at [top of new VFS team member template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/orientation-epic.md) has new-vfs-team-member tag
 - Label listed at [top of new VFS team template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/new-vfs-team.md) has new-vfs-team tag
- Links on [Guidance for new teams and team members page](https://depo-platform-documentation.scrollhelp.site/getting-started/guidance-for-new-teams-and-team-members) on Platform website

thanks for the assist @allison0034! Closing.

**Comment by shiragoodman** [comment]
@alyssagallion @jknipes FYI - per my comments in the VFS Team Roster draft, we've added unique labels to both the New VFS Team and New VFS Team Member templates. Any new tickets created from those templates beginning today onward will have unique labels, meaning you no longer have to rely on the `governance-team` label or the 2 analytics labels.
