### ISSUE TITLE
Profile Datasets - Update/Clean Up

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#68357]
## Issue Description

As part of the Profile dashboard updates we created a new dataset that supports all the cards on the dashboard. We need to update the BQ & Domo views to updated weekly on Sundays same as other datasets. Also clean up working datasets from BQ.

---
## Tasks
- [x] Update BQ view to update weekly same as standardized dashboards (weekly append not replace as it was before)
- [x] Change name in BQ remove 'Test3'
- [x] Remove test datasets in BQ (highlighted in yellow, want to keep api request and hits details a little longer in case we need to go back)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1J2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6a4ed9fc935cd94b76ba06ccbad8195493958950/image.png)

## Acceptance Criteria
- [ ] Updates above completed.
---
