### ISSUE TITLE
CI: Address concurrency issues where old CI will still run processes after cancelling unless cancelled multiple times

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#68351]
## Description

CI continues to run even when cancelled. The QA Merge Status step in particular, is unable to be cancelled and must finish regardless of the steps prior to it having been cancelled. It should immediately abort the entire workflow when this happens instead of forcing the user to wait for this step to run.

## Tasks

- [ ] Diagnose why the QA Merge Status continues to run when a run is cancelled
- [ ] Ensure no other steps follow this same behavior
- [ ] Correct all corresponding steps

## Acceptance Criteria

- [ ] All CI runs when cancelled immediately cancel all steps of the workflow.
