### ISSUE TITLE
MyVA Dashboard Update - INTERNAL

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#68367]
## Issue Description

This is an internal ticket outline the work needed for the [MyVA dashboard update](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/66654). They would like to add page views and user count cards same as we did for My Profile. The dataset already exists in Domo 'BQ - All MyVA Users and Pageviews' we just need to create and QA cards. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWR2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--660adcd102633887dfbba6eb09688e6a88a52b61/image.png)

---
## Tasks
- [ ] Create User Count by Page card
- [ ] Create Pageviews by Page card
- [ ] QA against [GA Report](https://analytics.google.com/analytics/web/#/my-reports/95VYfSvWTaqdX54kdnA7sw/a50123418w177519031p184624291/_u.date00=20231001&_u.date01=20231025&334-table.filter=my-va~2F&334-table.plotKeys=%5B%5D) 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkJ2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd97ea88c4c579a788f5c774920406210263d536/image.png)

## Acceptance Criteria
- [ ] Each task above completed and handed off to MyVA team.
