### ISSUE TITLE
Design / Research | Military Info | Lo-fi mock-ups

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#68362]
## Background

BE has completed some research into what is available in VA Profile:

- #65976 
- #65977 
- #65978 
- #65975 (added this after planning as it was completed the next day)

We need to sleuth through this and ask any questions we might have to make sure we have a understanding of the data point available. 

## Tasks 

- [x] Review military unit assignment data
- [x] Review deployment data
- [x] Review MOS data
- [x] Review dates/BOS data
- [x] Review with team and confirm which pieces of data we feel belong in the MVP mock ups
- [x] Create lo-fi mock-ups

## Acceptance Criteria 
- [x] we have a mock up that can help further the conversations we're having with different teams (VEO, benefits disability team)

**Comment by Samara-Strauss** [comment]
My thoughts for where to start:

**Comment by Samara-Strauss** [comment]
My thoughts for where to start:

1. Units
2. Deployment locations and dates
3. Military occupational specialty

Why: The first two are being added to the digital 526EZ; all three are on the paper form.

@mtcA6 @andaleliz @pamela-drouin any thoughts?

**Comment by andaleliz** [comment]
@Samara-Strauss that sounds reasonable to me, and those are exactly the data points Tom has finished looking into (maybe by design?).  I think we asked about this in the call but I can't remember the response - are there plans to add MOS to the digital form too?

**Comment by mtcA6** [comment]
I'd recommend we take it just a slice farther since several veterans commented on the active vs. inactive and I think i recall one person mentioning the discharge type. 

As part of the branches and dates of service section, can we incorporate the discharge type and active vs inactive duty? 

In Tom's first diagram he documented that [the military service episodes ](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/military_info/va-profile-military-history.md) seems to have additional information around the period of service type. And it also seems to have details around the discharge type.

**Comment by Samara-Strauss** [comment]
> are there plans to add MOS to the digital form too?

I don't remember if we asked about this or not. Will you ask the team? They are #benefits-disability in Slack.

> As part of the branches and dates of service section, can we incorporate the discharge type and active vs inactive duty?

- From Liz's comment above, it sounds like inactive/active is an essential part of the unit data, so let's include that.
- I am torn on discharge status. It doesn't meet the metric of "asked for in the 526", BUT I know [it can impact the ability to receive health and benefits](https://www.benefits.va.gov/benefits/character_of_discharge.asp). Let's add it to the list. If for some reason we get into the design and decide it's causing more trouble than it's worth (I don't anticipate this), we can always change course.

**Comment by andaleliz** [comment]
@Samara-Strauss yep, I posted a question in their Slack channel

>From Liz's comment above, it sounds like inactive/active is an essential part of the unit data, so let's include that.

The way I'm planning to approach this is to evaluate the data schema Tom has documented, and make recommendations about what to include and leave out based on what we know about the 526EZ + what we've heard in research, and then review with the team. From my perspective, anything in the schema is essential right now until it isn't :) 

>It doesn't meet the metric of "asked for in the 526"

Knowing that is a metric is super helpful, thank you. Are there any other specific metrics that we're targeting now? The [project outline still has "leave blank for now" in that section](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/military-information/2023-enhanced-military-information#objective-1) and I think it'd help drive the direction of the mock-ups, and help the team feel more grounded in this work, if we captured any specific metrics you have in mind.

As a side note, if I were to add "holding off on surfacing ILER PDF" to the key decision list, does that sound right to you? The project outline puts a lot of emphasis on that so it feels important to capture we're not doing that now.

**Comment by andaleliz** [comment]
Status update:

- I'm working in[ a mural board ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697125319596/c13810c02c96a58a4b6b72288c6b9a8d617f711a?sender=ub868d471cfdb1c56cc0b4512)to make sense of everything.

- I've reviewed all the docs for each set of data and left my thoughts/questions about each data point and how they relate to our profile work. To view this work, [start here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697125319596/c13810c02c96a58a4b6b72288c6b9a8d617f711a?wid=0-1698333489553), and work your way **down** the mural board. I need access to the VADIR confluence docs and/or someone who knows more than me to get those questions answered. I'm going to move forward with what I know for now and we can fill in the gaps later.
- I pulled out the data points I think it makes sense to expose in the UI. To review those focused data points, [start here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697125319596/c13810c02c96a58a4b6b72288c6b9a8d617f711a?wid=0-1698426362828) and work your way to the **left**.
- I'm reaching out to some veterans to see how far off track I am with [this initial approach](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697125319596/c13810c02c96a58a4b6b72288c6b9a8d617f711a?wid=0-1698426432497) to organizing the data.

**Comment by Samara-Strauss** [comment]
@andaleliz this is INCREDIBLE work. Seriously. It was so easy to follow this Mural, and you've done an amazing job at making sense of this all and figuring out how the frontend maps to the backend. Absolutely outstanding.

Obviously keep us updated on everything, but I am especially curious to hear what the initial feedback is from the veterans you're talking to.

Great work!

**Comment by andaleliz** [comment]
@Samara-Strauss thank you! I'm delighted the Mural was easy for you to follow.  More updates now that it's nearly noon on Monday:

I've spoken with 3 veterans and gotten 3 different answers in terms of how this data would be meaningful for them 🙃  A couple specific differences that keep coming up is that seems like each branch of service has a different lexicon in terms of "unit", and that there are differences in how people think about `assigned` vs `attached` units.  

Despite all that, I've been able to work out some different options that feel like a reasonable starting point to organize the information:

1. Prioritizing assigned unit ([example](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697125319596/c13810c02c96a58a4b6b72288c6b9a8d617f711a?wid=5-1698675471892))
2. Prioritizing dates ([example](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697125319596/c13810c02c96a58a4b6b72288c6b9a8d617f711a?wid=3-1698675843537))
3. A third option could be prioritizing deployments - one Veteran said that's primarily how he thinks about his career, and that dates alone might be muddy in people's memories.  I think we'd need `deployment name` data for this to work though, and afaik right now, we don't have that.

I've also thought through the various options we have in the design system for presenting this information, and am leaning toward a component that can show/hide detailed information. This makes sense to me because we're dealing with an unknown quantity of dynamic data (Mike R. from VA Profile let me know the dataset is dynamic and not controlled. DoD makes changes/adds codes, sends to VADIR), and could help prevent people from feeling overwhelmed by seeing a wall of text as soon as the page loads.  After evaluating the current design system options, I think a button to reveal/close a section makes the most sense (as opposed to an accordion or something else), and mocked that up here.
- [Collapsed](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/a/mPwDY3k)
- [Expanded](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/v/8rGz4R/a/DE8ma32) (ignore the data structure you see here, I don't think this does a good enough job of correlating dates, location, and unit)

I'm at a point where I'm not sure how to move forward. I've created a new section on the Mural board with [outstanding questions](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697125319596/c13810c02c96a58a4b6b72288c6b9a8d617f711a?wid=0-1698676348292), and two critical questions for me right now are:
1. What are our MVP product goals, other than the metric of "asked for in the 526"?
2. What further convos do we need to have with the 526 team to continue working toward our MVP? I know @mtcA6 wanted these mock-ups to further conversations with that team, and VEO. Knowing the outstanding questions we want to get answered from them could help me figure out where to go from here.

Thanks and I look forward to further thoughts from the team!

**Comment by pamela-drouin** [comment]
The granularity and particularity of military data is so confusing, and I’m honestly amazed (but not surprised!) at how much you have gotten done with untangling the data, @andaleliz. I love the initial mock-ups. I do think there is a good point in information being triggering for some… it'll be fun to explore all the options with veterans whenever we're at that point, and I think you're headed in the right direction already.

It would be good to clear up Liz's outstanding questions so next steps can be determined!

**Comment by Samara-Strauss** [comment]
Liz, this is incredible. Thank you so much for digging through this incredibly complex space and starting to make sense of it. You've done amazing work.

When you get back, let's regroup on your outstanding questions so we can figure out how to move this work forward. I know @mtcA6 mentioned being able to pull Tom into this work more now that direct deposit work is calming down, so hopefully he can get us more information on what kind of data we get back and answer any data structure questions.

> What are our MVP product goals, other than the metric of "asked for in the 526"?
> What further convos do we need to have with the 526 team to continue working toward our MVP? I know @mtcA6 wanted these mock-ups to further conversations with that team, and VEO. Knowing the outstanding questions we want to get answered from them could help me figure out where to go from here.

Let me talk about this with Travis, and I'll get back to you.

**Comment by Samara-Strauss** [comment]
> What are our MVP product goals, other than the metric of "asked for in the 526"?

Hey Liz -- coming back to this. After talking to Travis, we decided on the following. The product goals are slightly different depending on what level of zoom we're looking at this work. 

If we are thinking of the entire expanded military effort, the product goal is:

- To meet the congressional mandates around elevating toxic exposure data in a way that is holistic and matches veterans' mental models.

If we are thinking of this MVP portion of this effort, the product goal is:

- To holistically support the addition of toxic exposure fields into the 526.  

For the MVP, our work does this by:

- Making it easier for a 526 developer to incorporate these fields into prefill because we will have completed the original integration of this data into `vets-api`.
- Giving this data a permanent place on [VA.gov](http://va.gov/) for veterans to review this information.

Please le me know what questions you have, or if you feel like this is missing something.

**Comment by andaleliz** [comment]
Thanks for your responses @Samara-Strauss!  A few comments:

>When you get back, let's regroup on your outstanding questions so we can figure out how to move this work forward.

I found a time that works for everyone tomorrow. Woot woot!

>For the MVP, our work does this by:
> - Making it easier for a 526 developer to incorporate these fields into prefill because we will have completed the original integration of this data into vets-api.
> - Giving this data a permanent place on [VA.gov](http://va.gov/), so veterans can easily review this information.

This is very helpful framing and gives me a better sense of what we need to do in the near term to move forward. I don't think anything is missing.  Looking forward to our convo tomorrow!

**Comment by andaleliz** [comment]
After our meeting today, I don't think any further work is needed for this particular ticket. Future work will be covered in new tix :)
