### ISSUE TITLE
Add Slackbot to cover common Identity troubleshooting steps

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#68374]
# Description
Design a Slack bot to answer common questions that many different people come to #vsp-identity Slack channel for. This Slack-bot should encapsulate domain knowledge from John, Trevor, Riley, Joe, and Alex on the typical questions we (the Identity team) ask of developers & people who can't sign in.

# Tasks
- create `identity-bot` [slack app with the bolt/Javascript framework](https://api.slack.com/start/building/bolt-js) & enable it in a development channel on DSVA slack
- add `sign in help` logic that prompts the user with a series of questions designed to guide them through troubleshooting their local authentication.
```
### Global
1. Which environment did the error occur in? Local, development, staging, or production? Or review instances?
2. Which user did you use to sign in? Which Credential Service Provider you attemtped?
3. Can you provide a screenshot of the error page? Include the screen and DevTools console.
4. Can you provide an error code, timestamp, and/or request ID?
5. Have you tried clearing your browser cache, cookies, or attempted to sign in incognito?
6. Have you tried changing browsers?

```
- add `documentation` route that links to documentation maintained by Identity
  - SiS integration
  - mock data
  - mocked auth
  - user creation 

# Definition of Done
- [ ] slackbot exists that can be called in #vsp-identity channel with `/tbd-command`
- [x] slackbot provides guide form to help users troubleshoot sign in & local development build issues
- [x] slackbot contains links to Identity team's currently maintained documentation on its products

**Comment by asg5704** [comment]
This Slack-bot should encapsulate domain knowledge from John, Trevor, Riley, Joe, and Alex on the typical questions we (the Identity team) ask of developers & people who can't sign in.  Some examples:

1. Do you have the latest pulled from `vets-website`, `vets-api`, (depending on context `vets-api-mockdata` and/or `content-build`)?
2. Which user did you use to sign in? Which Credential Service Provider you attemtped?
3. (Local) Can you provide logs of the `vets-api`
4. Can you provide a screenshot of the `vets-website` error page?
5. Can you provide an error code, timestamp, and request ID?
6. Have you built `vets-website` before building `content-build`?
7. (Local) Have you confirmed your user has the appropriate mocked user in `vets-api-mockdata`
8. (Local) Have you confirmed the `vets-api-mockdata` and `vets-api` are in the same global directory?
9. (Local) Can you provide logs for the `log/development.log`?

Feel free to add questions @rileyanderson @bosawt @joeniquette

**Comment by joeniquette** [comment]
Lets add one in there for what is your method of running local.

These questions are all I can think of for now. Once we get answers to how to perform each of those I think we should be in good shape. Will be interesting what capabilities we have to prompt users to answer those questions...maybe even start recording stats around the responses

**Comment by bramleyjl** [comment]
How exactly do we want to present these troubleshooting questions? Are we envisioning a form that they fill out all at once, or a process where they read & answer one question at a time and then submit the form to us when they've gone through all of the steps?

**Comment by bramleyjl** [comment]
I've begun development of a Slackbot leveraging the slack_bolt Python framework. The initial connectivity took some troubleshooting, and I'm now working on building out the multipart form.

Development is occuring in [this new repository](https://github.com/department-of-veterans-affairs/identity-slackbot/tree/master). Given that both the VA.gov product team project & the SiS onboarding projects will most likely make use of a Slackbot for answering questions and generating github issues I plan on continuing to develop this when I have the time and/or pass it off to another engineer to continue.

**Comment by bramleyjl** [comment]
This is the slack workspace I created to test the bot, link should work for 30 days:|

https://join.slack.com/t/testidentitybotapp/shared_invite/zt-2btv2kw9c-Mda2uuBLzhmxD9K0ebvyeg

**Comment by bramleyjl** [comment]
Moved the localhost questions to #76022 as a post-MVP goal.

**Comment by bramleyjl** [comment]
Request to create an "Identity Slackbot" Github app under the VA organization and install it on va.gov-teams repository:
https://github.com/department-of-veterans-affairs/github-user-requests/issues/20511

**Comment by bramleyjl** [comment]
Moving to close this as this ticket is dragging on; remaining items are present in other tickets.
