### ISSUE TITLE
Forms Dashboard Updates 5655- INTERNAL

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#68370]
## Issue Description

This is an internal ticket for 2 dashboard updates 

[Dec Reviews Board Appeal 10182 dashboard update](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/67363) - V2
 

Please follow the [update instructions](https://vfs.atlassian.net/wiki/spaces/AT/pages/1510408350/How+to+-+Loading+a+new+funnel+to+the+Forms+KPI+Dashboard)

---
## Tasks
- [x] Update template  - Christine
- [x] Review & Approve template before hand off to Phil - Michelle & Joe
- [x] Upload to BQ - Phil
- [x] QA updated dashboard - Christine

## Acceptance Criteria
- [ ] All tasks above completed and handed off to team.
