### ISSUE TITLE
Change PM/DM intro sign up within Platform Orientation

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#68373]
## User Story
As a new VFS PM or DM, I want to know who Shira is and why I'm reaching out to her so that I can prepare any questions I may have.

As a PM on Governance, I want to automate the scheduling of the PM/DM intro so that I can spend less time coordinating with new folks via Slack.

Assignee: @briandeconinck 
Peer Reviewer: @shiragoodman 

## Description
Currently in the new VFS Team Member gh ticket for Platform Orientation, new VFS PMs or DMs are asked to contact Shira via Slack to set up a synch. There is currently no information listed in the gh ticket about who Shira is or why this sync is requested.

The purpose of this ticket is to add Shira's role and team to the GH ticket. The 2nd purpose of this ticket is to remove the request for the new PM/DM to reach out to Shira via Slack, and instead provide a Calendly sign up link.

## Impacted Artifacts
[New VFS Team Member gh template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=analytics-insights%2C+analytics-request%2C+governance-team%2C+platform-orientation%2C+new-vfs-team-member&projects=&template=orientation-epic.md&title=New+VFS+Team+Member+Template+%5BYour+name+here%5D)
[PM Intro ](https://calendly.com/collaboration-cycle/product-manager-intro)event in Calendly

## Tasks
- [x] Create a pull request for the new VFS Team Member ticket
   - PR #70064 
- [x] Edit the first checklist item in the Product Managers & Delivery Managers section to new language and include link to Calendy PM Intro
- [x] Peer review pull request

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] VFS PMs and DMs learn who Shira is before they meet with her
- [ ] VFS PMs and DMs can schedule a meeting directly with Shira

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
@shiragoodman This is ready for review, PR #70064. I wasn't sure if you wanted just your role or both name and role. Went with name + role but I'm happy to change!

**Comment by shiragoodman** [comment]
@briandeconinck looks good to me! There's info about my role in Calendly too, so I think this should cover it.
