### ISSUE TITLE
GA4: Web Components & Gtags - Mapping & Testing (cont.)

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#68380]
## Issue Description

We need to continue work on locating web components still needed to be configured/mapped for GA4 migration. 

---
## Tasks
- [ ] Identify [location of remaining web components for testing](https://docs.google.com/spreadsheets/d/1R0I5_dglyXEXYl0uESUTsSfsyIcBAk2lr7DVrRsx3qY/edit?pli=1#gid=0) - Joe & Michelle
- [ ] Provide GTM and gtag details about findings - Joe & Michelle
- [ ] Complete mapping and configurate remaining web components - Jamie
- [ ] Complete gtag audit and determine next steps (keep, remove, redirect) - Jamie
- [ ] Complete gap analysis of [VFS custom events](https://docs.google.com/spreadsheets/d/1R0I5_dglyXEXYl0uESUTsSfsyIcBAk2lr7DVrRsx3qY/edit?pli=1#gid=343262001) and what can be replaced with web/form/global components.

## Acceptance Criteria
- [ ] All task above completed
