### ISSUE TITLE
Design | Profile | Military Information | Research how surfacing military info might help the claims adjudication process

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#68399]
## Background

We have a lot of information available to us that could help us understand the claims adjudication process and how the data we surface in the VA.gov profile can be helpful. Let's dig in with a service design lens.   It's possible some of the documents linked below are duplicative of each other.

Since we're not sure what this will uncover, we can't be sure what, if any deliverables, should be expected from this ticket. Probably a summary doc at a minimum

## Tasks 

- [x] Review the [Benefits Employee Experience Maps](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684520740516/f4a5857ab93a177bbcf0144581e2eb1486730dd1?sender=uaa72d11015d3f7c704a64191)
- [x] Review the [Map of Maps](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1691694705068/f167df3bf00da9473559b70daef763ae41c2aeaa?wid=0-1691696025874&sender=uaa72d11015d3f7c704a64191) 
- [x] Review [the claims onboarding deck](https://dsva.slack.com/archives/C018V2JCWRJ/p1683903410672449?thread_ts=1683903181.607549&cid=C018V2JCWRJ)
- [x] Review [the claims process GH documentation](https://github.com/department-of-veterans-affairs/VES/blob/master/research/Event%20Bus/Claims%20Process%20Information/The%20VA%20Claims%20Process.md)
- [x] Review [the claims adjudication process GH documentation](https://github.com/department-of-veterans-affairs/VES/blob/master/research/Event%20Bus/Claims%20Process%20Information/Claims%20Adjudication%20at%20VA.md)
- [ ] Review [Demo of VBMS core](https://dvagov.sharepoint.com/:v:/s/vaabdvro/ER0c7KTurDlEn4XJiY745IoBFQlItjrmzeHD8g0cJ8JzwQ?e=icRwh1)( Sharepoint access required)
- [ ] Create summary doc? @pamela-drouin, curious if you think this is needed after going through these docs - Liz

## Acceptance Criteria 
- [ ] understand which data points would ease or expedite the claims adjudication process

**Comment by andaleliz** [comment]
@pamela-drouin I added you to this ticket too in case you have a chance/bandwidth to look through some of these things while I'm out.  I've also added a bunch of links to the description.

**Comment by mtcA6** [comment]
@andaleliz is the entire ticket rolling to next sprint?

**Comment by andaleliz** [comment]
@mtcA6 this will definitely carry over into next sprint since Pam isn't here this week. I'm not sure how far she's gotten with reviewing any of this information (or how much she wants to review) so it's hard to estimate points to carry over. I think leaving it as-is with 5 points is a safe bet for now.  

I'll complete my portion of the work within this sprint though.

**Comment by pamela-drouin** [comment]
@andaleliz I’m finished reviewing everything (except for the VBMS demo, I am not sure how to get Sharepoint access, the link wanted me to log in once I opened it in CAG). I too am not sure where to go from here. I have a deeper understanding of the claims process from the points of view of the veteran and an adjudicator…

**Comment by andaleliz** [comment]
@pamela-drouin awesome! Let's chat about it in our 1:1 later this week, since we don't have that other meeting until 12/6.

I honestly wouldn't worry about watching the VBMS demo, I didn't find it that useful as it pertains to what we're working on.  But, for Sharepoint access, I think you just need to enter your VA.gov email address and it automatically logs you in from there. A redundant step, I know.

**Comment by mtcA6** [comment]
@andaleliz could you invite me to the call? I don't see it on my calendar and would love to listen in

**Comment by andaleliz** [comment]
@mtcA6 you're on the invite, and have accepted as going - it's 12/6 at 2:30pm ET

**Comment by mtcA6** [comment]
oops I'm a doofus and totally didn't see it there! Thanks!
