### ISSUE TITLE
Create architectural diagram for VA.gov Topology, deployment design and build workflows

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#68408]
### Description
Create a detailed architectural diagram that visualizes the topographic flow of both the production build process and the Preview Environment topology.

Build process - From go to a deployable entity (helm chart or container or zip of static content)
Deploy process - how to create an instance of va.gov (production or preview)
Topology - the component and access flow for va.gov running in an environment

---
### Tasks
- [x] Gather necessary details on the current production topology
- [x] Draft a preliminary architectural diagram for production topology
- [ ] Review with team for feedback & revisions
- [ ] Finalize and publish the architectural diagram

### Acceptance Criteria
- [x] Architectural diagram has been created that accurately depicts the planned preview environment va.gov topology.
- [x] Architectural diagram has been created that accurately depicts the current production va.gov topology.
- [x] Architectural diagram has been created that accurately depicts current & planned build flows for vets-api, website and content-build
- [x] Architectural diagram has been created that accurately depicts current production deployment process for a va.gov instance
- [x] Architectural diagram has been created that accurately depicts planned deployment process for preview environments
- [ ] Obtain buy-in from @JoeTice @ericboehs @pjhill @CBonade @ben-allen-oddball @Mandalorian-Oddball and Kyle
