### ISSUE TITLE
VFS Roster: Identify Current Process and Document It

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#68417]
## Description 
This ticket will house the task of identifying the current process for adding folks to the VFS Roster and documenting said process. 

---

## Definition of Done
All tasks are created below.

---

## Tasks 

- [x] Identify the current process for adding folks to the VFS roster
- [x] Identify what existing documentation is out there from Governance and Analytics already
- [x] Document the process and combine it with the above existing documentation (only keep the parts that are relevant to our team) here: [VFS Roster Management](https://vfs.atlassian.net/wiki/spaces/PTST/pages/edit-v2/2798846283?draftShareId=677684af-f143-4ba8-a989-57ba5982d174)
- [x] Send to Shira to review to ensure the process is accurate
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Add item to the [What We Can Help With Doc](https://depo-platform-documentation.scrollhelp.site/support/what-we-can-help-with-platform-support)
- [x] Point to the documentation in our [Advanced Support Best Practices Tier 1 Document](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2761326593/Advanced+Ticket+Support+Best+Practices+Tier+1#Sentry-access)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 

Existing Documentation:
[New VFS Team Members ](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2041086016/New+VFS+team+members)

---

**Comment by jknipes** [comment]
- Platform Analytics: [New Team Members](https://vfs.atlassian.net/wiki/spaces/AT/pages/2189590618/Platform+Orientation). Process routinely handled by Christine Young - Analytics Team, AdHoc

- Governance: [New VFS Teams](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2061959315/New+VFS+Teams)
- Governance: [Steps for completing Platform tasks on a Platform Orientation ticket](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2583658517/Steps+for+completing+Platform+tasks+on+a+Platform+Orientation+ticket)
- Governance: [Customer Facing Documentation](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-orientation)
- [ZenHub Platform Governance Board](https://app.zenhub.com/workspaces/platform---product-support-5f85b91c14d8df0018fac414/board?repos=133843125,154174777&showEstimates=false&showMilestones=false&showEpics=false&showReleases=false&showDependencies=false)
- [VFS Roster Google Sheet](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)

**Comment by alyssagallion** [comment]
@jknipes Can you run this by @shiragoodman ? I want to be sure the process is documented. If she already reviewed and said it is good, we can push live and you can close this ticket. Thanks!

**Comment by jknipes** [comment]
@alyssagallion Shira Goodman has given final review and I have updated with final improvements, added to Launched Support Enhancements Confluence Doc

**Comment by alyssagallion** [comment]
Updated information on [this doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2798846283/VFS+Roster+Management) with the comments left by Shira and Michelle. In review with @laineymajor

**Comment by alyssagallion** [comment]
No need to communicate out to VFS Teams as the process isn't changing for them. Thanks!
