### ISSUE TITLE
Platform Support Confluence Section Clean Up

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#68414]
## Description 
This ticket will house the task of cleaning up the section here: https://vfs.atlassian.net/wiki/spaces/PTST/overview

---

## Definition of Done
All tasks below are complete

---

## Tasks 

- [ ] Archive any duplicate or unnecessary pages (make sure any relevant information is transferred to the pages where it makes more sense)
- [ ] Organize any pages into more specific buckets where necessary to avoid having a long list of articles (i.e. Operations, etc.)
- [ ] Notify the team when this has been done in the #platform-tech-support-channel

--- 

## Resources & Additional Info 
N/A
---

**Comment by alyssagallion** [comment]
Duplicate ticket. We performed this work in [this ticket](https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/74378).
