### ISSUE TITLE
[FE] 10-10EZR - Add enrollment status fetch to the Introduction page

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#68413]
## Description
In the scaffolding of the 10-10EZR application, the fetch action for the enrollment status was put in place but never wired up to be called. We need to add this to the introduction page in order to get the status for appropriate users.

## Tasks
- [x] Adjust the fetch action to allow for mocked responses when running in local environments
- [x] Add the fetch action to the intro page (or child component thereof)
- [x] Ensure the fetch action executes ONLY if the user is logged in and of LOA3 status
- [x] Properly unit test all affected components

## Acceptance criteria
- Fetch action executes properly to get the users enrollment status
