### ISSUE TITLE
Test Stability Review: Query invalid based on : character (bug)

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#68410]
## Issue Description
This [workflow](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/6644020067/job/18054409484?pr=26367) was linked to us by support of an error that took place with an invalid query. It's currently unknown under what circumstances a query would contain a colon, and all queries have been tested and appear to be working prior. We need to figure out how this error happened.

---
## Tasks
- [ ] Investigate the cause of this error.
- [ ] If the error was not due to user's actions, implement a fix to avoid this happening in the future.
- [ ] Test the same scenario with the fix in place to ensure the correct execution of the workflow job.

## Acceptance Criteria
- [ ] This bug no longer appear under the same circumstances.

**Comment by CBonade** [comment]
Have this bug solved in my current branch. It was an unintended byproduct of adding the workflow links to the queries as some of them were not coded entirely correctly therefore the colons were breaking the queries. Code is not yet merged, but primary work is complete.
