### ISSUE TITLE
Design Prototype & Content for Address Validation

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#6841]
## User Story or Problem Statement
As a user, I  need to ensure that my address was entered correctly so I can ensure that communication from the Caregiver program will reach me.

## Goal
Users can receive an error message with possible corrections if their address is entered incorrectly.

## Objectives or Key Results this is meant to further
Note - can we put together a metric on address validation?
---
## Tasks
- [x] Work with backend to figure out when in the process we could run the address check, and if the service will propose corrections
- [x] Define business logic for: What happens if the address can't be confirmed?
- [x] Design screens for address suggestion
- [x] Design screens for address error

---
