### ISSUE TITLE
[bug spike] SC | Missing address 422 error

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#68423]
On 10/25/23, we saw a 422 error for a failed SC submission. 

Here's the error in [Sentry](http://sentry.vfs.va.gov/organizations/vsp/issues/234860/?environment=production&project=3&query=user.id%3A%225920c16f-10c9-45eb-8661-961490033636%22&statsPeriod=1h) (dig into older instances to find the 10/25/23 one for this Veteran):
```json
{
  "errors": [
    {
      "code": "145",
      "detail": "One or more expected fields were not found",
      "meta": {
        "missing_fields": [
          "addressLine1",
          "[Filtered]",
          "[Filtered]"
        ]
      },
      "source": {
        "pointer": "/data/attributes/veteran/address"
      },
      "status": "422",
      "title": "Missing required fields"
    }
  ]
}
```

Strangely, the Veteran's SIP form does not contain an address object. See SIP #9275687. To be clear:
`JSON.parse(InProgressForm.find(9275687).form_data)["veteran"]["address"]` returns `nil`.

## Tasks
- [ ] Determine root cause of error
- [ ] Create plan for resolution
- [ ] Think about whether short-term intervention is necessary/feasible
- [ ] After discovery complete, add estimate, remove `needs-refinement` and `needs-estimate` labels, remove `[bug spike]` prefix in the title of this PR, and update these tasks and AC, DoR, and DoD below.

## Acceptance Criteria
- [ ] Root cause of error is known
- [ ] Can reproduce 422 error locally (and if possible, on staging)
- [ ] Bugfix complete and works locally (and if possible, on staging)
- [ ] Bugfix deployed

## Definition of Ready
- [ ] Root cause of error is known

## Definition of Done
- [ ] Acceptance criteria met
- [ ] Veteran has been notified of bugfix by contact center.

**Comment by Mottie** [comment]
Work on this may be fixed by [adding validation to all contact info fields in this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/26426).

**Comment by saderagsdale** [comment]
Associated with a PR that's already in progress
