### ISSUE TITLE
Refactor: Move `military_information` out of User model

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#68438]
Trevor brought it to our attention that the `military_information` method doesn't need to live in `user.rb`. It can be removed. The method in `user.rb`:
```ruby
  def military_information
    @military_information ||= if Flipper.enabled?(:military_information_vaprofile)
                                FormProfile.new(form_id: nil, user: self).initialize_military_information
                              else
                                EMISRedis::MilitaryInformation.for_user(self)
                              end
  end
```
`initialize_military_information()` in `form_profile.rb`:
```ruby
  def initialize_military_information
    return {} unless user.authorize :va_profile, :access?

    FormMilitaryInformation.new(initialize_va_profile_prefill_military_information)
  end
```

### Tasks
- [x] Remove relevant code from user.rb
- [x] Remove relevant tests from user_spec.rb
- [x] If the flipper is still needed, make sure to include it in the appropriate spot.
- [x] Determine if something similar needs to happen to `veteran_status()` in user.rb

**Comment by rjohnson2011** [comment]
`military_information` has been removed from user.rb in a prior PR. `initialize_military_information()` in form_profile appears unrelated to emis, so keeping this for the time being after discussing with @rmtolmach
