### ISSUE TITLE
[Tech Debt] centralize page scroll code

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#6844]
## Description

In the vets-website, there is abundant duplication of scroll code:

Searching for:

* `scrollToTop =` returns 35 results in 35 files
* `scrollTo(` returns 65 results in 60 files; most of which include the same scroll options

   ```js
    {
      duration: 500,
      delay: 0,
      smooth: true,
    }
   ```

  but some use default options stored in `window.VetsGov.scroll` or `window.Forms.scroll` (used during testing)
* There is a `getScrollOptions` function (located in two separate files) that should be used instead of repeating the scroll options
* Other miscellaneous function that probably need to be cleaned up include:
  - `scrollToError`
  - `scrollToFirstError`
  - `scrollToRow`
  - `scrollToFile`
  - `scrollToAlert`
  - `scrollToEnrollment`
* The scroll function that is used should also be consistent `Scroll.scroller` vs `Scroll.animateScroll`
* Eventually we'll need to adhere to the OS accessibility setting where the user may set a "prefers reduced motion" setting which will **disable smooth scrolling**.  See #6701

## Goal

- Centralize common scroll functions & settings
- Ideally split up scroll & focus code out into separate files
 
## Objectives or Key Results this is meant to further

Reduce code & make it behave consistently across the site

## Tasks

- Centralize common scroll functions
  - [ ] Move it all to the `src/platform/utilities/ui/` folder (shorter path).
  - [ ] Remove repeated  code in the `src/platform/forms-system/src/js/utilities/ui/index.js` file.
- The `getScrollOptions` function
  - [ ] Should be centralized & used everywhere
  - [ ] Ensure scrolling is disabled in testing environments while still allowing custom settings - included because I ran into an issue where using lodash merge wasn't including my custom `offset` setting.
- [ ] Split up scroll & focus code into separate files (the `ui/index.js` file has too much code in it already

## Acceptance Criteria

- All tasks have been addressed

**Comment by vhenry07** [comment]
Work completed by the Frontend Tools team.
