### ISSUE TITLE
Document KMS Key Rotation Changes

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#68447]
## Issue Description
Based on the work done on KMS Key Rotations, we want to update documentation for VFS teams and engineers. Since the 

---
## Tasks
- [x] Draft documentation update
- [x] Conduct documentation review
- [x] Post documentation update to Platform Website

## Acceptance Criteria
- [x] Revised documentation for KMS Key Rotations have been uploaded to platform website
