### ISSUE TITLE
Investigate KMS records that failed to rotate

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#68448]
## Issue Description
In the process of rotating the KMS records, some records may not have been successfully rotated. We want to investigate whether that did occur, 

## Tasks
- [ ] Investigate how many records may not have rotated successfully
- [ ] Determine why those records didn't rotate as planned
- [ ] Resolve any issues and get remaining records rotated.

## Acceptance Criteria
- [ ] Records have been rotated successfullly
