### ISSUE TITLE
Use Sidekiq 7's Capsules for KMS Key Rotation Job

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#68466]
As configured, our `KMSBatchIntiator` Job enqueues and rotates 15 million records at a time (at a rate of about 2000 records per second). This is run every night until all records are rotated (2-3 days per year). Unfortunately, this large number of key rotations exceeds Amazon's rate limit for KMS calls.

Each record rotation makes two API calls to KMS. [Amazon's apparent rate limit](https://docs.aws.amazon.com/kms/latest/developerguide/requests-per-second.html) is 5500 rq/s. On average, we were consuming around 4k rq/s but our periodic burst must have gone over the limit.

We will soon be upgrading to Sidekq 7 which introduced the concept of [Capsules](https://github.com/sidekiq/sidekiq/blob/main/docs/7.0-Upgrade.md#capsules)—a way to limit queues to a certain number of threads (concurrency).

```tasklist
## Tasks
- [ ] In k8s/helm, add a "batch" queue (or perhaps "bulk"/"time-insensitive") to the list of queues that are watched by our Sidekiq processes
- [ ] In the KMS job classes, specify they are to use the "batch" queue
- [ ] In our Sidekiq initializer, configure a Sidekiq capsule to run an appropriate amount of concurrency (we were running 512 threads when we hit the rate limit).
```

```tasklist
## Acceptance Criteria
- [ ] The yearly KMS key rotation does not constrain our resources or rate limits.
```

## Prerequisites

Upgrade to Sidekiq 7
