### ISSUE TITLE
Create list of all third party dependencies in vets-website for security team

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#68464]
## Issue Description
The Security Team should have a list of all third party dependencies that are in use in vets-website as well as any relevant information about them (primarily, a link to information about the dependency). This should include full-repo dependencies as well as any individual packages being loaded by apps that continuously deploy.

---
## Tasks
- [ ] Create list of all third party dependencies in vets-website
- [ ] Send to Security Team (at the request of Ken Mayo).

## Acceptance Criteria
- [ ] A comprehensive list of all third party dependencies has been sent to the security team for vets-website.

**Comment by AshleyGuerrant** [comment]
@CBonade & @JoeTice - I'm just doing a bit of backlog cleanup. Is this ticket still relevant?

**Comment by AshleyGuerrant** [comment]
@CBonade & @JoeTice - Is this ticket still relevant?

**Comment by AshleyGuerrant** [comment]
@CBonade & @JoeTice - I'm closing out this ticket because it is stale, it can be reopened if necessary.
