### ISSUE TITLE
Update resolveParamsWithUrl method

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#68480]
## Issue Description
Need to update the frontend's method for constructing the URL to make API requests. 

---
## Tasks
- [x] resolveParamsWithUrl method needs params for lat, long, name, page, per_page, sort, type
- [x] Update front end bindings to object of APIs

## Acceptance Criteria
- [ ] resolveParamsWithUrl method has params for lat, long, name, page, per_page, sort, type
