### ISSUE TITLE
Move vets.gov-team content to va.gov-team repo

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#685]
## User Story
As someone working on va.gov, I need all of the information in a public repo so I can contribute to the project.

## Goal
_Have everything in the va.gov-team repo_

## Acceptance Criteria
- [ ] _Everything still pertinent to the project is moved from vets.gov-team to va.gov-team or va.gov-team-sensitive_

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
