### ISSUE TITLE
Renew Fwdproxy SSL Client Certs for ES

### ISSUE THREAD

**Issue by tskinn** [department-of-veterans-affairs/va.gov-team#6850]
## User Story or Problem Statement
The SSL certificate used as a client cert to connect to the Enrollment Service are expiring.

## Goal
Replace the expiring certificates with new VA issued certs and get folks at ES to approve new certs.

## Tasks
- [x] Get new certs issued from VA
- [x] Get certs in devops repo and keys in credstash
- [x] Send certs to ES contact to update accepted client certs
- [x] dev
- [x] staging
- [x] prod

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ricetj** [comment]
Ref: https://dsva.slack.com/archives/CQHBJ5U06/p1584475056213000

**Comment by ricetj** [comment]
Done
