### ISSUE TITLE
Tech Discovery - 526EZ Test for EMIS to VaProfile migration

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#68521]
## Issue Description
EMIS to VaProfile migration is ready to be tested for a **deprecation around Thanksgiving 2023**. The impacted teams need to test the military information prefill functionality in staging.

https://dsva.slack.com/archives/C04KW0B46N5/p1698418315648029

The scope of this ticket is to identify all locations for testing for the military information prefill functionality in the 526EZ flow. The effort includes but is not limited to the occurrence identified in the ticket - [Prep VFS Teams Test Forms #64879 ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64879)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHQ4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5a26fbea359514f833ff06294638b76d17394cf9/image.png)

---
## Need to Know
- [ ] For questions, tag @Rebecca Tolmach, Lainey Trahan in the #-emis-deprecation channel
- [ ] Military_information_vaprofile is the FT and it's turned on in both dev and staging
- [ ] There is an urgency associated with this testing request as the migration is being planned by ~~the week of Thanksgiving~~ mid-December
---
## Tasks
- [ ] Check what pages/locations the migrated endpoint is used in the 526ez flow

## Acceptance Criteria
- [ ] List of occurrences for testing
- [ ] Create a ticket for testing

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by christinec-fftc** [comment]
Additional (front end) notes from the discovery...

### Local debugging
Set breakpoints for prefill transformer. Breakpoint is hit on the /start and /introduction pages when starting a new form. If user has a save in progress form, the prefill transformer does not appear to run again when logging in and returning to the form. Any previously edited service history is retained.

Note 11/8/23: ran git pulls, and response has since changed 🙃 -> servicePeriods and reservesNationalGuardService data is now empty

Example response from `/v0/disability_compensation_in_progress_forms/21-526EZ`. Relevant sections are `servicePeriods` and `reservesNationalGuardService`
```
{
    "formData": {
        "veteran": {
            "mailingAddress": {
                "country": "USA",
                "city": "APO",
                "state": "AE",
                "zipCode": "09028",
                "addressLine1": "123 MAIN ST",
                "addressLine2": "BEN FRANKLIN VILLAGE"
            },
            "primaryPhone": "4445551212",
            "emailAddress": "test2@test1.net"
        },
        "disabilities": [
            {
                "name": "Hypertension",
                "ratedDisabilityId": "0",
                "ratingDecisionId": "63655",
                "diagnosticCode": 7101,
                "decisionCode": "SVCCONNCTED",
                "decisionText": "Service Connected",
                "ratingPercentage": 30
            },
            {
                "name": "Diabetes mellitus0",
                "ratedDisabilityId": "0",
                "ratingDecisionId": "63655",
                "diagnosticCode": 5238,
                "decisionCode": "SVCCONNCTED",
                "decisionText": "Service Connected",
                "ratingPercentage": 100
            },
            {
                "name": "Diabetes mellitus1",
                "ratedDisabilityId": "1",
                "ratingDecisionId": "63655",
                "diagnosticCode": 5238,
                "decisionCode": "SVCCONNCTED",
                "decisionText": "Service Connected",
                "ratingPercentage": 100
            }
        ],
        "servicePeriods": [
            {
                "serviceBranch": "Air Force Reserve",
                "dateRange": {
                    "from": "2001-03-21",
                    "to": "2014-07-21"
                }
            }
        ],
        "reservesNationalGuardService": {
            "obligationTermOfServiceDateRange": {
                "from": "2007-05-22",
                "to": "2008-06-05"
            }
        },
        "bankAccountType": "Checking",
        "bankAccountNumber": "*********1234",
        "bankRoutingNumber": "*****2115",
        "bankName": "Comerica"
    },
    "metadata": {
        "version": 0,
        "prefill": true,
        "returnUrl": "/veteran-information"
    }
}
```

**How this data is populated in the redux store**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnZVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4a8e161cdc3f253450a9c2864b63ab38ad9f6ab5/image.png)

**Relevant Pages (2)**
military-service-history
/disability/file-disability-claim-form-21-526ez/review-veteran-details/military-service-history

reserves-national-guard
/disability/file-disability-claim-form-21-526ez/review-veteran-details/military-service-history/reserves-national-guard

### Stage testing
Initial testing was not successful. We were getting completely different service history for the same users when the toggle was on vs off. We heard this was due to a VADIR bug (https://dsva.slack.com/archives/C03LT909K1A/p1699470000620169). We're waiting to hear if this will be fixed on staging so we can retest. However, feedback we heard was good and that prefill itself is working as expected.

**User 54**
_Toggle off_
Service history is not pre-filled since no service information returned from the api. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1hVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d64c2052f4a41209bfba83889560d32f2eff23c9/image.png)

526 submission was successful
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2JVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4eb6e09db8d2750c74608b3f9fa821a740bdbe8e/image.png)

_Toggle on_
- Service history displays successfully
- Reserves-national-guard page does not display. This is expected since the user does not have any reserves or national guard service history.
- Nothing of note on the review-and-submit page
- After evss team cleared things out, submission was successful!

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM25VQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a12acff798dd0843d09816eeff75c2562f5392a/image.png)

**User 228**
_Toggle off_
Results: Military history is pre-populated on the military-service-history page
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzdVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--86b12e79cf948b119e84f33f8dbff76875fdb083/image.png)

_Toggle On_
Results: (Different) Military history is pre-populated on the military-service-history page
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNExVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e6839f50ddc45cbe26f8f06517327ea10784b878/image.png)

Reserves-national-guard page displays as expected. Obligation start and end date are set on the reserves-national-guard page
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFRVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9f6bd3027682fc275527a3f2e6126ccba21c369c/image.png)

Submission was successful

**Comment by sethdarragile6** [comment]
From the backend perspective, we confirmed that the prefill is using the `/v0/disability_compensation_in_progress_forms/21-526EZ` endpoint, which then grabs the service periods and obligation start dates from EMIS/VaProfile. The endpoint checks the database for a pre-existing InProgressForm record, and if it finds one, prefill is NOT called- hence the need to start a new application to test.

Nowhere else in the system is calling this endpoint, nor the EMIS military info endpoint.

**Comment by christinec-fftc** [comment]
Synced up with Seth and we agreed work on this ticket is complete.

Once the VADIR issue is fixed, we can retest in [#69437](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/69437)
