### ISSUE TITLE
Move isolated VHA FSR jobs to sidekiq namespace

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#68539]
## Issue Description
The following two jobs still live under the `workers` namespace even though the project has shifted over to using `/sidekiq` as the job name spacing standard.

- `modules/debts_api/app/workers/debts_api/v0/form5655/vha/sharepoint_submission_job.rb`
- `modules/debts_api/app/workers/debts_api/v0/form5655/vha/vbs_submission_job.rb`

---
## Tasks
- [ ] Transfer jobs to `/sidekiq` folder
- [ ] Update any namespacing necessary

## Acceptance Criteria
- [ ] All of our jobs live within the `/sidekiq` directory
- [ ] Tests pass
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by JunTaoLuo** [comment]
The PR has been merged and the work is complete.
