### ISSUE TITLE
[FE] My VA: Post launch code cleanup on removing My VA from unauth header

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#68531]
## Background
The work to remove My VA from the unauthenticated header involved a feature flag: `my_va_show_header_link`. We need to do a standard post-launch cleanup and remove the flag from code. 

This may involve code review from public websites team?

## Tasks
- [x] Determine which files are involves
- [x] Remove toggler component
- [x] Check tests
- [x] Move to validation and tag dev for validation

## Acceptance Criteria
- [ ] Feature toggle removed from code
- [ ] Feature toggle removed toggle manager
- [ ] Feature still functioning as intended

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_  Dev
- _How can this work be validated?_

## Resources
- [proxy-rewrite](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite) 
- #67050 
- relevant PR for reference: [26295](https://github.com/department-of-veterans-affairs/vets-website/pull/26295)

**Comment by adamwhitlock1** [comment]
I can confirm that this is working as expected. 

I remember that their is a specific process to remove the toggle entry from the database table of toggles that is required to be run from the ruby REPL thingy.

@tpharrison is that something you can run to remove the `my_va_show_header_link` from staging/prod or do we need to put in a platform support request for that?

**Comment by ajakabcin** [comment]
spoke with @tpharrison he's going to take care of this via https://github.com/department-of-veterans-affairs/va.gov-team/issues/71967 - closing this as complete thanks all!

**Comment by tpharrison** [comment]
@allisonlu @ajakabcin The `my_va_show_header_link` toggle has been removed from dev, staging, and prod.
