### ISSUE TITLE
[bug] Update betamocks default sharepoint responses to point to right location

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#68543]
## Issue Description
We have SharePoint mock responses setup in our `vets-api-mockdata` repo but it appears the services config has an issue with pointing to them. The services config currently is structured like so:

```
- :name: 'VHA'
  :base_uri: <%= "#{URI('https://' + Settings.vha.sharepoint.sharepoint_url).host}:#{URI('https://' + Settings.vha.sharepoint.sharepoint_url).port}" %>
  :endpoints:
  - :method: :post
    :path: <%= "/#{Settings.vha.sharepoint.base_path}/_api/Web/GetFolderByServerRelativeUrl('#{Settings.vha.sharepoint.base_path}/Submissions')/Files/*" %>
    :file_path: "vha/sharepoint/create"
  - :method: :post
    :path: <%= "/#{Settings.vha.sharepoint.base_path}/_api/Web/Lists/GetByTitle('Submissions')/items/*" %>
    :file_path: "vha/sharepoint/create"
  - :method: :get
    :path: "/_api/Web/*"
    :file_path: "vha/sharepoint/show"
```

The end goal is for the file path defaults to point to the path of `vha/sharepoint/create/default.yml` within our mockdata repo since we have these files [created](https://github.com/department-of-veterans-affairs/vets-api-mockdata/blob/master/vha/sharepoint/create/default.yml)

However, we are getting the error `IOError: Betamocks default response requested but none exist. Please create one at: [/app/config/vets-api-mockdata/vha/sharepoint/default.yml].`

It looks like betamocks is attempting to read from the parent sharepoint directory rather than the specified create/show paths.

Sentry issue for context: http://sentry.vfs.va.gov/organizations/vsp/issues/222690/?environment=staging&project=3&query=is%3Aunresolved+job%3ADebtsApi%3A%3AV0%3A%3AForm5655%3A%3AVHA%3A%3ASharepointSubmissionJob&statsPeriod=14d

---
## Tasks
- [ ] Identify cause of reading wrong default mockdata file path
- [ ] Update services config to correctly point to default mockdata file

## Acceptance Criteria
- [ ] SharePoint submission jobs correctly process through the betamocks flow
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by asmithgovcio** [comment]
I'm unable to reproduce this issue locally, blocked until I can get access to staging and test there.

**Comment by asmithgovcio** [comment]
I wasn't able to reproduce this exact issue in the staging environment however I do see warnings in the staging sidekiq log for an authenticate.yml file which is different from the default.yml file listed here.

`[2024-01-16T14:48:58.922282 #1]  WARN -- Betamocks: Mock response not found: [/app/config/vets-api-mockdata/vha/sharepoint/authenticate.yml]
`

I do not know what authenticate.yml is supposed to look like, inside the mock data repo there is a folder containing another default.yml file which is located at `app/config/vets-api-mockdata/vha/sharepoint/authenticate/default.yml` but I'm not sure if this is the same issue or not. From the task description it's looking for a default.yml file not an authenticate.yml file. I could copy the authenticate/default.yml contents into a file and name it authenticate but I honestly have no idea if that is the right thing to do or not. We need someone who is more familiar with the beta mocks repo and how it all works to take a look at this, I don't think I'll be much more help on this.

**Comment by HeatherRienks** [comment]
@kjsuarez - any suggestions on who might be able to assist?

@Tom-Davis

**Comment by asmithgovcio** [comment]
@HeatherRienks looking at who reviews pull requests on that repo I came across this individual @aaronyoung-tw but I'm not sure his contact information other than GitHub username

**Comment by asmithgovcio** [comment]
@HeatherRienks I reached out to Aaron and he said he isn't the right person for this, he gave me the contact for Rebecca Tolmach and I sent a message on slack, hopefully we will hear back soon.

**Comment by HeatherRienks** [comment]
Ok, I am wondering if there is a Slack channel that might be a good place to post.... let's pose to our team and maybe 
they can provide an idea for a larger forum... Just not sure what the best Eng channel is for this :)

**Comment by HeatherRienks** [comment]
@asmithgovcio to create new ticket when he speaks w Rebecca  for newly discovered issue.

**Comment by asmithgovcio** [comment]
I spoke with Rebecca Tolmach and she pointed me to another repo that handles config files for our environments, this repo is called `vsp-infra-application-manifests` and there is a config file for our staging environment that contains the following.

`vha:
              sharepoint:
                sharepoint_url: <%= ENV['VHA_SHAREPOINT_URL'] %>
                client_id: <%= ENV['VHA_SHAREPOINT_CLIENT_ID'] %>
                client_secret: <%= ENV['VHA_SHAREPOINT_CLIENT_SECRET'] %>
                tenant_id: <%= ENV['VHA_SHAREPOINT_TENANT_ID'] %>
                resource: <%= ENV['VHA_SHAREPOINT_RESOURCE'] %>
                service_name: "VHA-SHAREPOINT"
                base_path: <%= ENV['VHA_SHAREPOINT_BASE_PATH'] %>
                authentication_url: <%= ENV['VHA_SHAREPOINT_AUTHENTICATION_URL'] %>
                mock: true`


Evidently the beta mocks repo is only supported for local/development environments and is not meant to be used in staging environments according to Rebecca, we will have to change this line `mock: true` to `mock: false` to disable these warnings/errors in staging. I can make the change quickly however I found out I don't have write access to the repo so I made a ticket with platform support, once they approve my write access I can push up the change however I do not know how often that repo gets deployed when new changes are made.

**Comment by asmithgovcio** [comment]
The pull request appears to have resolved the issue, after running the task in staging I am no longer seeing warnings about beta-mocks configuration files.
