### ISSUE TITLE
[discovery] Investigate how our portal might know FSR dependency is down

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#68540]
## Issue Description
We have alerting in place to let us know if we are seeing failures with one of our downstream dependencies but is there a way to check their health status from the frontend automatically without manually adding a pager duty maintenance window?

This seems plausible given the health checks that are performed by the haproxy for each of our external services. Here's an example of a [graph](https://vagov.ddog-gov.com/dashboard/8yz-qzc-bng/10-10ez-pact-act-resiliency?fullscreen_end_ts=1694027508767&fullscreen_paused=true&fullscreen_section=overview&fullscreen_start_ts=1694027011901&fullscreen_widget=4603743711033938&graphType=flamegraph&historicalData=true&index=&shouldShowLegend=true&sort=time&spanViewType=logs&from_ts=1694027011901&to_ts=1694027508767&live=false) that checks status via DataDog. We should be able to check our dependency status using `min:haproxy.backend.status{environment:prod,proxy:vbs_back}`. In this example `vbs_back` could be replaced with `debts_back` to check for DMC status. 

Can this proxy status be read from the UI? 

---
## Tasks
- [ ] Investigate potential locations of proxy service status either on the API or UI
- [ ] Discuss with platform potential solutions and/or pitfalls

## Acceptance Criteria
- [ ] We have a determination for reading proxy status 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
