### ISSUE TITLE
[a11y Support] Ask VA Team (Phase 1)

### ISSUE THREAD

**Issue by sara-amanda** [department-of-veterans-affairs/va.gov-team#68565]
## a11y Assignee(s)
- @eli-oat (collaboration)
- @sara-amanda (research)
- @coforma-jamie `(?)` CAIA Team Member for Additional Support (optional)

## About the AVA Team

<details><summary>Toggle to view AVA team info.</summary>

- **Team name:** Ask VA (AVA)
- **OCTO-DE product owner:** @clantosswett
- **Product manager:** @ruchishah29
- **Designer:** @t-michaud @beckyphung @tygindraux
- **FE engineer:**
- **Accessibility specialist:**
- **Content writer:**
- **Product/team Slack channel**: [#ask-va-public](https://dsva.slack.com/archives/C05A2F6DEAE)
- **Related Epic from the Collaboration Cycle:** #60696
</details>

## Requesting a11y Support for Phase 1
- Accessibility review of wireframes and/or prototypes
- Accessibility user research support
- Collaboration Cycle Accessibility Support (all stages)

## Background Information
Overview information collected during the kickoff meeting held in July of 2023.
### Some Initial A11y Considerations:
- Mobile Focus (per Martha)
- Removing tables and reserving them for data only.
- One-item per page for cognition optimization.
- SR research (Jan. 2024)

<details><summary>Toggle to access background info. on this project</summary>

- **This is an existing product:**
    - There are apparently a lot of issues with the tool as it exists now.
- **Initial goals:**
- "**Quickly lift and shift (with a facelift)** on Ask Va to bring the functionality over to [Va.gov](http://va.gov/) and forward thinking about it more strategically as a larger support ecosystem within the va and [va.gov](http://va.gov/)."
    - "**Our Phase 1** will have brought the current Ask VA up to [VA.gov](http://va.gov/) design and **accessibility standards**, updated the content to **make it more intuitive for our submitters**, and sunset the existing front-end portal of AVA."
    - **AKA P1 Focus:**
        - "**Phase 1 - exclusively focusing on** the web form experience, as well as the ability to look up your inquiry and see the status of it."
    - **Longer-Term Goals:**
        - **Accurately answer submitters' questions:**
             - "Submitters should feel it is easy and intuitive to submit their issues and receive adequate updates and information that results in a final resolution.
             - Ultimately, we want AVA to feel part of a cohesive and submitter-centered approach to support."
    - **Collab Cycle**:
        - We shared a slew of resources in the doc and they implemented our recommendations prior to design intent.
        - **Midpoint Review:**` Nov. 14 at 11:30 a.m. Eastern` ([via Zoom](https://oddball-io.zoom.us/j/81600041855?pwd=ejZrVW9jNXp4Qmx4Mzc0VjNCVHREZz09))
</details>

## Resources

<details><summary>Toggle to review the AVA resources</summary>

- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ask-va/products/Ask-VA-MVP-1-Product-Outline.md)
- User flows: [Health Category User Flow](https://www.sketch.com/s/6a75d0a2-e484-4f1e-8675-ad5747a1a871)
- [IA Spec Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/AskVA-MVP.md) c/o Kristin on 8/8/2023.
- Prototype or mockups: [Sketch link as of 10/15/2023](https://www.sketch.com/s/6a75d0a2-e484-4f1e-8675-ad5747a1a871)
    - If this is in Sketch, which version or specific page should we focus on?
- Content source of truth: [Content Flow Spreadsheet](https://docs.google.com/spreadsheets/d/1B8aGHO07RFTxi9QkCktjHWwV_COPIg1BJDBf7S80QX8/edit#gid=0) and [proposed content categories, topics and sub-categories](https://docs.google.com/spreadsheets/d/1aCei8pmLBBkWPeDye4YSmUqRkD0yCfTeLEqwdL-329M/edit#gid=0)
- [**Content Label Spreadsheet**](https://docs.google.com/spreadsheets/d/1aCei8pmLBBkWPeDye4YSmUqRkD0yCfTeLEqwdL-329M/edit?usp=sharing) to document the current names and proposed revisions 
    - **Blocker**: Per Tyler 9/8/2023: Still limited right now in our MVP (Phase 1) stage, where we're not able to merge, add or remove categories, topics or subtopics.
    - #67626
-  [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ask-va/research/Submit%20and%20review%20an%20inquiry/Research%20plan.md)
-  [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ask-va/research/Submit%20and%20review%20an%20inquiry/Conversation%20guides/Veteran%20guide.md)
- Research Ticket:  #66774
</details>

```[tasklist]
### A11y Tasks
- [x] **Collaborate with CAIA Content** (Derek - @d-beyer) [per Laura - @laurwill](https://oddball.slack.com/archives/C04JVQGEK8F/p1698438947764939?thread_ts=1698438557.329279&cid=C04JVQGEK8F) as they work on #67626 (@eli-oat) **11/2/2023 10:30 AM EASTERN**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/68938
- [x] **Prepare for Midpoint Nov. 14:** Consulting Approach with AVA Team (@eli-oat) [Sketch File](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68565#issuecomment-1791246733) Review [Deliverable](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/Deliverables/Ask%20VA/2023-11-02-Ask-VA-design-review-notes.md) from Eli and Jamie in ticket 68938
- [x] **Intake Request Included:** Accessibility user research support #66774 (@sara-amanda)
- [x] **NO LONGER NEEDED** Support for Staging Prep (Requested via Intake Ticket)
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/81692
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/80535
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89026
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89027
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89028
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/87480
```

**Comment by tygindraux** [comment]
Hiya, I reached out to @sara-amanda but then I noticed that she's out of the office.

I'm wondering if we can/should set up an accessibility review with y'all, before we go to our midpoint review on November 14? We set up one with the content team (review [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67626)). Should we do the same with you?

**Comment by sara-amanda** [comment]
## CAIA Update
Howdy, @tygindraux! Sorry I missed you today, when I stepped out for a bit.  **_Yes! We can help!_**  Can you confirm the links we should be referencing? I will post those below. 

### CAIA A11ys 
- **Assignees**: Specifically, @eli-oat and @coforma-jamie are likely going to be assisting on this one from the CAIA a11y side. 
- **Meeting**: They have a meeting scheduled with **CAIA's Content Team** (Derek and A) this week, to discuss **Ask VA**.
- **Ticket**: We can track our Midpoint Prep Work in a11y Ticket #68938 

### Midpoint Prep Assistance Requested
- **Midpoint Review Date:** Nov. 14, 2023 `Scheduled`
- **Artifacts c/o the Collab Cycle Ticket #62304 on 11/1/2023**
    -  **Finalized design mockup:** [Sketch - Ask VA Form - C - VA Health Care [WIP]](https://sketch.com/s/6a75d0a2-e484-4f1e-8675-ad5747a1a871)
    -  **Specific page to review:** [V3 - C - VA Health Care Flow](https://www.sketch.com/s/6a75d0a2-e484-4f1e-8675-ad5747a1a871/p/4E7790A9-059D-4A3B-A184-45F1E9434CDB/canvas)
- [Background information can be found in this ticket.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68565#:~:text=Toggle%20to%20access%20background%20info.%20on%20this%20project)

**Comment by tygindraux** [comment]
Thanks @sara-amanda!

**Awesome news** that CAIA A11ys will meet with CAIA content folks this week. If there's anything you need from us before, during, after, let us know.

The links you have posted above are all correct. Although, we did have a chat with Jamie and Eli [on Slack](https://dsva.slack.com/archives/C05A2F6DEAE/p1698939529683969) about the Sketch file being too big. So we're working on breaking it into smaller files, and when we have those links I'll circle back here too.

**Comment by coforma-jamie** [comment]
The Sketch files (thanks @tygindraux!)

- Chapters 1-3: [Ask VA - VA Health ch.1-3 [WIP]](https://sketch.com/s/07932590-56d9-44bd-bfc0-713545e56793)
- Chapter 4:
    - General question: [Ask VA - VA Health ch.4.01 [WIP]](https://sketch.com/s/093b0c99-a0bd-44a5-be35-9c13016bab91)
    - About me, the Veteran: [Ask VA - VA Health ch.4.02 [WIP]](https://sketch.com/s/1eb36285-725b-4f81-90e5-4ac9ad7e2374)
    - For the dependent of a Veteran: [Ask VA - VA Health ch.4.03 [WIP]](https://sketch.com/s/e53743f7-6bf9-4922-a44d-8c3321a6978f)
    - On behalf of a Veteran: [Ask VA - VA Health ch.4.04 [WIP]](https://sketch.com/s/ef34449f-4386-4a89-a8b4-03ce94a753f9)
- Chapter 5: [Ask VA - VA Health ch.5 [WIP]](https://sketch.com/s/9df59eaa-82e7-4804-8ce4-7a7586075783)

**Comment by eli-oat** [comment]
[Notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/Deliverables/Ask%20VA/2023-11-02-Ask-VA-design-review-notes.md) of sketch file review.

**Comment by sara-amanda** [comment]
# Ask VA Research
_Ask VA: [User Research Overview Table](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/ask-va/design/User%20research)_

## Old Research Ticket: Submit an Inquiry
- `BACKLOG` - Removed from the backlog and moved to closed on 4/10/2024 per Tyler's ok in Slack.
- `CLOSED` - Work not needed on [original research ticket: 66774 ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/66774) for _Submit an Inquiry_.

## New Research: Progress Bar
- `COMING SOON` - Research ticket, c/o Tyler on 4/11 or 4/12/2024 for _progress bar research_
    - [ ] When ticket arrives, link in this ticket's task list under a11y, please. 
    - [x] Holds on CAIA Capacity Calendar
- **AT Type:** Screen Mag. 
- **Pilot**: Recommending a pilot session with CAIA A11ys. 
    - **Date of note:** _The Ask VA team has [a pilot internally slated for 4/18 it appears,](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ask-va/design/User%20research/04-2024%20Progress%20bar/Research%20plan.md#timeline) if we could try to collaborate at that time as well._
- **Research begins:** 4/23/2024. 
    - The [research plan shows ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ask-va/design/User%20research/04-2024%20Progress%20bar/Research%20plan.md)they are only having a few AT sessions. 
    - > **At least 2**: Use screen magnification, like, ZoomText, ZoomText Fusion, Magnifier (Windows), Zoom (Apple)

### Important Dates

#### Source of Truth
_[Table data current as of 4/10/2024: Taken from Ask VA Research Plan.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ask-va/design/User%20research/04-2024%20Progress%20bar/Research%20plan.md) - which is the source of truth. This information below will not be updated and is to be used as reference only._

#### Timeline

|Date|Milestone|
|:--|:--|
|Friday, April 12|Research review|
|Thursday, April 18|Prototypes are ready|
| ⭐ Thursday, April 18|Pilot session|
| ⭐ Tuesday, April 23 - Friday, April 26|Research sessions|
|Monday, April 29 - Wednesday, May 1|Synthesis|
|From Thursday, May 2|Share findings|

#### Timeslots

|Date|Timeslots (EST)|
|:--|:--|
|Tuesday, April 23|9-10am, 10:30am-11:30am, 12-1pm, 2-3pm, 3:30-4:30pm|
|Wednesday, April 24|9-10am, 10:30am-11:30am, 12-1pm, 2-3pm, 3:30-4:30pm|
|Thursday, April 25|9-10am, 10:30am-11:30am, 12-1pm, 2-3pm, 3:30-4:30pm|
|Friday, April 26|9-10am, 10:30am-11:30am, 12-1pm, 2-3pm, 3:30-4:30pm|

#### Participant Criteria

|# of participants|Criteria|
|:--|:--|
|Exactly 10|Are Veterans|
|Exactly 10|Have contacted VA online or over the phone in the past year|
|Exactly 10|Have signed in to VA.gov in the past year|
|Exactly 5|Are willing to join from a mobile device|
|Exactly 5|Are willing to join from a desktop device|
|At least 5|Have a cognitive disability or consideration|
|At least 5|Are over 55 years old|
|At least 3|Identify as Black, Hispanic, Asian or Native|
|At least 2|Identify as a gender other than male|
|At least 2|Identify as LGBTQ+|
| ⭐ At least 2|Use screen magnification, like, ZoomText, ZoomText Fusion, Magnifier (Windows), Zoom (Apple)|

_[Table data current as of 4/10/2024: Taken from Ask VA Research Plan.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ask-va/design/User%20research/04-2024%20Progress%20bar/Research%20plan.md)_

**Comment by coforma-jamie** [comment]
After discussing the team's needs with Tyler, we determined the following:

### Now
- Tyler will run a screen magnification pilot with a CAIA a11y using the team's Figma prototypes. 
- The team will run its study without AT users, and without CAIA support.

We are NOT going to attend the two screen magnification sessions, as listed above


### Later
- The team will create a coded prototype in Codepen or Staging.
- Tyler will run two screen reader pilots with CAIA a11ys - one on mobile, one on desktop.
- The team will run a new study with AT users - magnification and screen reader - with CAIA support.

**Comment by coforma-jamie** [comment]
I'll be the CAIA a11y on the pilot on April 30.
