### ISSUE TITLE
Re-enable and consolidate scorecard Jenkins jobs

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#6856]
## User Story or Problem Statement
As a developer, I need to re-enable Jenkins jobs for the scorecard so I can confirm the functionality works properly in advance of go-live.

## Goal
_What outcome(s) do we want to see?_

All three Jenkins jobs enabled
All three Jenkins jobs in the same folder
Permissions to start/restart Jenkins jobs granted to members of the ThoughtWorks github team who have SOCKS access

## Objectives or Key Results this is meant to further
- _Include references to KPIs we intend to impact_

n/a

---
## Tasks
- [ ] Consider merging these three jobs into one folder:
http://jenkins.vfs.va.gov/job/testing/job/vets.gov-status/
http://jenkins.vfs.va.gov/job/deploys/job/scorecard-automerge/
http://jenkins.vfs.va.gov/job/utility/job/scorecard-update/

Because the scorecard manages its updates differently (for now) than other parts of va.gov, it would make more sense for these jobs to be centralized in one folder for tracking purposes, vs being spread across three folders. This will also make it easier to control who has access to then.
- [ ] Update permissions so members of the ThoughtWorks team on github can view and kick off builds in any of these three jobs
- [ ] Enable these two jobs
http://jenkins.vfs.va.gov/job/deploys/job/scorecard-automerge/
http://jenkins.vfs.va.gov/job/utility/job/scorecard-update/
Note: These jobs should be set to be manually triggered, vs triggered daily, until our testing is complete.

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by wyattwalter** [comment]
Yeah, I think this makes sense. Let's drop them in `/scorecard`, I'd say.
