### ISSUE TITLE
Final Sketch for Vision within Strategy Roadmap

### ISSUE THREAD

**Issue by SophiaPhilipMO** [department-of-veterans-affairs/va.gov-team#68577]
Context
As a Veteran, I want to know that my experience as a Veteran is central to the strategy roadmap so that I know my needs are what inform and shape the strategy.

Acceptability Criteria
- [x] A final version is drafted
- [x] Final version shared with design team for refinement
- [x] Shared with product lead

Definition of Done
- [x] Final model for presentation to PO

**Comment by SophiaPhilipMO** [comment]
Update with Line 1 weight

**Comment by skirkman16** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEcvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e74545901ff817abe4f26973a55185f7afc2cc18/CEDAR_Vision_Sketch_4.png)

**Comment by SophiaPhilipMO** [comment]
@lmorris3 @porta-antiporta @djmunoz1, please review. Use will be in kick off modern credential presentation for introducing the strategy roadmap and gantt chart

**Comment by djmunoz1** [comment]
we should use a graphic that will connect across multiple audiences -- our message is about improving identity by way of the line items mentioned in the image so would like us to pivot to something that speaks to identity as the subject matter (padlocks, thumbprints, etc). The tree doesn't resonate. If we're at a loss I'd say remove it altogether.

**Comment by lmorris3** [comment]
I'm curious about the use of the word, "Protection." Is that another word for "Security"? I have some connotations with the word Protection that may be unique to me, but would want to vet this more thoroughly.

Also curious about the line, "Optimize testing and analytics" - what does that refer to?

**Comment by SophiaPhilipMO** [comment]
Created identity related icons to replace tree [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTNnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--33fcf37c93d346a39090bc08baa9de75e0c1fd5b/image.png)

**Comment by SophiaPhilipMO** [comment]
@lmorris3, protection was chosen given that is what VA is providing for Veterans' data. Security focuses on the external threats while protection focuses on the internal needs. Optimize testing and analytics; a more general way to acknowledge the work related to Datadog and the dashboards created across not just LGA to monitor user activity and ensure the goals are met.
