### ISSUE TITLE
Prepare for Privacy, Security, Infrastructure Readiness Review | Find a Representative MVP

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#68572]
## Issue Description
As part of the collaboration cycle, we will need to go through a [Privacy, Security, Infrastructure Readiness Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/privacy-security-infrastructure-readiness-review) to ensure our Find a Representative MVP meets Platform's privacy and security standards.  

It is recommended that we go through this process at the stage where we're writing tests and preparing for launch.

Regarding artifacts:
- The Security team prefers artifacts to be attached directly to the ticket, as opposed to linked out (often linking breaks and they have issues finding the artifacts).  
- Suggestion is to be as detailed as possible with our information flows, to save back and forth
- We can upload all artifacts as a combined PDF, just need to reference in the ticket sections that the info is in the combined PDF
- For non-applicable sections, please note "N/A" instead of leaving it blank, so the team knows that we haven't just missed that section

---
## Tasks
- [x] Create an Architecture Diagram
- [x] Create an Incident Response Plan
- [x] ~Create a Sequence Diagram~ (not applicable - arm search doesn't require authentication)
- [x] Create a Data Flow Diagram
- [x] Create API Endpoint Documentation
- [x] Create a Product Playbook
- [x] Ensure Product Outline contains Incident Response info 
- [x] Submit a [Privacy, Security, & Infrastructure Readiness Review ticket](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/new?assignees=kaipyroami&labels=security-review%2Cplatform-security%2Cplatform-security-review&projects=&template=privacy-and-security-review.md&title=Readiness+Review+%5BTeam-Name%2C+Feature-Name%5D)

## Acceptance Criteria
- [x] All supporting artifacts are uploaded to Github
- [x] A Privacy, Security, & Infrastructure Readiness Review ticket has been submitted, with artifacts attached

**Comment by oddball-lindsay** [comment]
Adding Holden as I will need technical support for a lot of the tasks

**Comment by oddball-lindsay** [comment]
@holdenhinkle here are some active Readiness Review tickets for examples of artifacts! 

1. https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1319 (artifacts are linked in the lower section of the ticket)
2. https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1301 (artifacts are in the comments of the ticket)
3. https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1293 (artifacts are linked in the lower section of the ticket)

**Comment by holdenhinkle** [comment]
Copying the review ticket here for easier reference:

## Guidance

- VFS Lead engineer or product manager: using this template, create issue in `va.gov-team-sensitive` and answer the questionnaire in its entirety.
* Do _**NOT**_ put any PII, PHI, or other Potentially Sensitive Data into the Issue contents.
* The Platform Security Team will review this issue and **conduct all conversations and follow-ups through this issue** (**ex**cluding PII/PHI/Potentially Sensitive Data).
    * As a requester: complete any follow-up action items and provide all requested information in this issue.
* Do _**NOT**_ close this issue, Security Reviews may only be closed by a member of the Platform Security Team. The Platform Security Team will update the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) upon closure.

## Stakeholders from the **requesting team**
- Lead engineer: **name**
- Product manager: **name**
- OCTO-DE product lead: **name**
- Anyone else on your team whose presence is needed to speak to the technical architecture and security concerns: **names**

## Questions to be Answered

The following product or feature descriptions may be answered with a reference link to the team’s documentation. However, the provided links must be specific to the request.

* Please describe what problem this product or feature solves.
* Please describe a plan to monitor this code base after deployment, including the following scenarios (_NOTE: If you don't (yet) have such a plan, or don't know how to get started with one, we can work on this with you!_).
    * The code base is compromised at source- or run-time.
        * How does the code base get disabled in the product?
        * How would you detect a compromise?
        * What process and privilege does the code base execute under?
            * If so, is that process isolated?
            * If so, what additional credentials are available to that process?
        * The code base is infiltrated or ex-filtrated.
    * Links to dashboards that help identify and debug application issues
* Provide your [**Release Plan**](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md) with the "Planning" sections completed (in each section: Phase I, Phase II, Go Live)
* Are there any new application endpoints, front- or back-end? If so, please give examples of how any of the endpoints could be abused by unauthorized parties, as well as a plan to mitigate such threats.
* Is there any new logging data being captured?  If so, what data is being captured, how, and where is it stored?
* Is [Personal Health Information/PHI](https://www.hhs.gov/hipaa/index.html), [Personal Identifiable Information/PII](https://www.dol.gov/general/ppii), or any other [Personal Information/PI](https://www.oag.ca.gov/privacy/ccpa) being captured? If so, please answer the following questions:
    * Is the PHI strongly encrypted?
    * Is the PII encrypted?
    * Can the sensitive information be scrubbed?
* Are there any new, modified, or existing Cookies being used?
    * If so, are there any new Cookies?
        * If so, why can’t the existing Cookies be used?
    * If so, are there any modified Cookies?
        * If so, how are the Cookies modified?
    * If so, are there any existing Cookies?
* Is this feature authenticated or unauthenticated?
* Are there any other specific subjects that you want to highlight or focus additional attention on?

## Artifacts

Please provide the following documentation as attachments.
* [ ] Architecture Diagram:
    This diagram must go beyond simple boxes and lines. It must clearly indicate which portions of the architecture are within the scope of the review, which portions are dependencies within the product, and which portions are external dependencies.
    This diagram must also illustrate the following specifics.
    * Which implementation of security approaches were considered along with the approach that was chosen and why?
    * If there are any libraries or components that this code base will depend upon that are currently not yet part of the code base? How and why were these selected?
* [ ] Incident Response Plan, including Points of Contact for your system and dependent VA back-ends.
    * If a security vulnerability is discovered or reported in this code base, what is the plan and timeline for rolling out the fix?
* [ ] Sequence Diagram:
    This diagram must include any authentication steps if this is an authenticated experience.
* [ ] Data Flow Diagram:
    This diagram must illustrate the following specifics.
    * What data is collected or used, and where, including information such as credentials used by this system?
    * Where is the data is stored and how, including information such as any encryption used?
    * How is the data transferred, including information such as any encryption used?
    * Who accesses the data and in what capacity (read or read-write)?
    * What is the audit trail of data access and manipulation?
* [ ] API Endpoint Documentation:
    This may include a link to a Swagger/OpenAPI document. Any new API endpoints introduced by this product or feature must be explicitly identified.
* Product Specifics:
    * [ ] A link to the [**Release Plan**](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md) with the "Planning" sections completed (in each section: Phase I, Phase II, Go Live)
    * [ ] A link to the [**Product Outline**](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)
    - Ensure Product Outline contains **Incident Response** info, including:
        - Points of contact for your system and dependent VA back-ends
        - Links to dashboards that help identify and debug application issues
    * [ ] Is there a playbook included in your product outline, for investigating and handling likely failure modes? If so, link to your [Product Playbook](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/Product_Playbook_Security.md)

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Privacy and Security Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html) on Platform website for more information about the Collaboration Cycle.

**Comment by holdenhinkle** [comment]
Architecture Diagram - https://docs.google.com/presentation/d/129c-zH_gsyBQ5csyC3kzln4PnggB-nqYYdQK6Kl327I/edit?usp=sharing

**Comment by oddball-lindsay** [comment]
Adding @jvcAdHoc to the efforts for the API Endpoint Documentation piece
> This may include a link to a Swagger/OpenAPI document. Any new API endpoints introduced by this product or feature must be explicitly identified.

**Comment by holdenhinkle** [comment]
Create a Sequence Diagram - not applicable - arm search doesn't require authentication - marked as done

**Comment by holdenhinkle** [comment]
Flow Diagrams - https://docs.google.com/presentation/d/1BJ6-6CfbcTBmWMCf-y7E6au6lWZVNWT8bsFR1_dTVUM/edit#slide=id.g297cbbb085d_0_82

**Comment by holdenhinkle** [comment]
I'm about halfway done with the Flow Diagrams task.

**Comment by holdenhinkle** [comment]
Flow document is ready for review - https://docs.google.com/document/d/1UpXv4RA3B_cqhHuZQfN3BxB7qnDzpzwLHbqWCUhiB-g/edit#heading=h.xj5ykzfwe90a

**Comment by jvcAdHoc** [comment]
eod update: There are several patterns I've seen in vets-api around swagger docs. I'm going to mimic the [check_in module's implementation](https://github.com/department-of-veterans-affairs/vets-api/pull/8462) as it's the simplest I've seen.

**Comment by oddball-lindsay** [comment]
@holdenhinkle could we repurpose our rollback process to also be an incident response plan?  or are those two separate concepts?

> The rollback process is:
> 
> 1. Turn off the feature toggle
>     1. Submit a PR
> 2. Alert the team in #benefits-representation-management that the rollback process has been initiated
>     1. Comment on the initial Slack alert thread, also sending the message to the channel (checkbox)
>     2. Tag relevant teammates (Holden, Jonathan, Colin, Lindsay, Michael, Janelle, Zach, Lesley, Alex, Steve)
> 3. Create a ticket to document: 
>     1. A summary of what caused the rollback process
>     2. Confirmation that the feature toggle has been turned off (or that a PR has been submitted)
>     3. Next step ideas for solving the rollback trigger
>     4. Other relevant links/images
>     5. Link to initial Slack alert for reference
> 4. Follow up in the Slack alert thread with a link to the ticket 
>

**Comment by oddball-lindsay** [comment]
Pending **backend** questions:
- Are there any new application endpoints, front- or back-end? If so, please give examples of how any of the endpoints could be abused by unauthorized parties, as well as a plan to mitigate such threats.

Pending **frontend** questions:
- Are there any new, modified, or existing Cookies being used?
  - If so, are there any new Cookies?
  - If so, why can’t the existing Cookies be used?
  - If so, are there any modified Cookies?
  - If so, how are the Cookies modified?
  - If so, are there any existing Cookies?

Pending questions for **all**:
- Is there any new logging data being captured? If so, what data is being captured, how, and where is it stored?
- Please describe a plan to monitor this code base after deployment, including the following scenarios (NOTE: If you don't (yet) have such a plan, or don't know how to get started with one, we can work on this with you!).
  - The code base is compromised at source- or run-time.
    - How does the code base get disabled in the product?
    - How would you detect a compromise?
    - What process and privilege does the code base execute under?
      - If so, is that process isolated?
      - If so, what additional credentials are available to that process?
    - The code base is infiltrated or ex-filtrated.
- Links to dashboards that help identify and debug application issues

@holdenhinkle ^

**Comment by cosu419** [comment]
re: **frontend** questions

No new, modified, or existing cookies being used. This could change if we ever implement "Select" in Find-a-Rep @oddball-lindsay

**Comment by jvcAdHoc** [comment]
new endpoints:
- `v0/apidocs`
- `/v0/accredited_representatives`


`v0/apidocs`:
This doesn't exist yet, but will serve our swagger docs using a static yaml file. The controller has no other functionality, so the only abusive behavior I can think of is someone hammering the endpoint with 1000s of requests. I don't see other apidoc controllers worrying about this.

`/v0/accredited_representatives`:
This is an unauthenticated controller that interacts with the database and could be abused.
- the params that get included in the sql query are protected from sql injection:
  -   using bound params + rails' strong params will automatically escape parameters
  -   we wrapped our select statement string in `ActiveRecord::Base.sanitize_sql_array()` in addition to using bound parameters within the method call
- there is validation on most of the params:
  - `lat` must be a number in the range (-90..90) or an error will be raised
  - `long` must be a number in the range (-180..180) or an error will be raised
  - `type` must be in `[attorney, claim_agents, organization]` or an error will be raised
  - `sort` must be `[distance_asc, distance_desc, name_asc, name_desc]` for organization search or `[distance_asc, distance_desc, first_name_asc, first_name_desc, last_name_asc, last_name_desc]` for rep search or an error will be raised
- there is the `find_a_rep` feature flag that can be used to disable the endpoint at any time if needed
- The information returned for a valid request does not contain PII and is already publicly available
- I made a [ticket to add a rate limit on the endpoint](https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/69679)

**Comment by jvcAdHoc** [comment]
eod update: still working on swagger docs. Should be ready by eod tomorrow.

**Comment by jvcAdHoc** [comment]
eod update: swagger docs have been merged

**Comment by holdenhinkle** [comment]
Docs where just merged to main:

- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/find-a-representative/launch-materials/arm-architecture-diagrams.pdf
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/find-a-representative/launch-materials/arm-data-flow.md
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/find-a-representative/launch-materials/product-playbook.md

**Comment by oddball-lindsay** [comment]
ticket has been submitted - phew! https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1339
