### ISSUE TITLE
[SPIKE] [UX] Determine if we're ready to update font styles, icons and color palette

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#68602]
## Tasks
- [x] Task 1: Ask Platform design team about their thoughts on delaying updating Sketch files to DS v. 3 knowing the migration to Figma is coming
- [x] Task 2: Create frontend ticket that details the work necessary to make changes to font styles, icons, & color palette

## AC 
- [x] Create frontend ticket

**Comment by zach-park** [comment]
Christina: task 1
Zach: task 2

**Comment by benbrasso-agile6** [comment]
Did @cgednalske get a chance to post about Task 1? If not, I might try to today, based on what she had told me... so @zach-park can complete Task 2 within the sprint.

**Comment by benbrasso-agile6** [comment]
I don't think she has, I'll try to.

**Comment by benbrasso-agile6** [comment]
Asked question here https://dsva.slack.com/archives/C01DBGX4P45/p1699545982861369

**Comment by zach-park** [comment]
Hi @benbrasso-agile6 , I think that UX team do our portion apart from the FE team. If so, here are possible tasks:
- Check (and update if necessary) all font styles used in the sketch file(s) are linked to the DSv.3 
- Also validate the icons & color palette with the DSv.3
- Update following sketch file(s): Unified and production

**Comment by benbrasso-agile6** [comment]
But, this ticket is for us to create a ticket for FE. So, could you list out what tasks we want FE to do (on production)?

**Comment by zach-park** [comment]
Hi Ben, I didn't think there was anything for FE to do because there isn't any component change (e.g., storybook). @cgednalske , could you please confirm if my assumption is right (or correct me if not right)?

**Comment by benbrasso-agile6** [comment]
So, based on the convo in [Slack](https://dsva.slack.com/archives/C01DBGX4P45/p1699545982861369), I don't quite understand what we were looking to accomplish with this ticket. It seems that "font styles, icons, & color palette" are specific to components, and not our css as a whole. So, when Christina gets back, let's figure out: 

1) Does design have any more components or icons to change? 
2) Do we have any components or icons that we want engineers to change next? 

Zach, you may have answers to these questions as well.

**Comment by benbrasso-agile6** [comment]
Created a bunch of tickets to complete task 2: 

[Design - switch to button pair component](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/69841)

[FE - switch to button pair component](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/65597)

[Design - switch text to v3 and icons in Production file](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/69832)

[Design - switch text to v3 and icons in Unified file Design page](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/69831)

[FE - switch headings, typography and icons](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/69829)

[FE - switch slim alerts to v3](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/65493)

[Design - switch slim alerts in Production sketch file](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/64829)

**Comment by benbrasso-agile6** [comment]
@cgednalske that look right?

**Comment by zach-park** [comment]
> @zach-park @cgednalske that look right?

Yes. Thahk you!
