### ISSUE TITLE
Default Rep-type to VSO

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#68614]
## Issue Description
A discussion with UX determined that the representative type should be required for the Find a Representative search, that the radio selections should default to "Veteran Service Organization".  

[Updated designs to reflect this](https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/v/Drp91k/p/E271113A-1668-4843-A299-C9CB4346AB46/canvas?posX=-2741.3444040757236&posY=-398.73052148496174&zoom=0.34911155700683594).

The thought process was:
We don't support multi-rep searches and need the user to select a rep type to perform an accurate/successful search, hence the requirement.  as for the pre-select, most radio-button systems do have a pre-select and we chose VSO because the analytics we received last week indicate VSO is by far the most common representative type.

---
## Tasks
- [x] Require representative type
- [x] Default representative type to Veteran Service Organization

## Acceptance Criteria
- [x] The rep requirement and default has been updated to match the updated designs

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-website/pull/26470
