### ISSUE TITLE
[FE/QA] 10-10EZR - Standalone form: Create e2e test suite

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#68620]
## Description
For the EZR application, we need to create the end-to-end test suite to ensure our application is functioning as intended. The tests should include a minimum dataset test for only the required fields in the form, a maximum dataset test that fills out all fields in the form, and then any other dataset tests that would identify specific test cases.

## Tasks
- [x] Create mock data and fixtures for testing use
- [x] Utilize form tester utility to create test suite for minimum, maximum and and specific tests that have been identified
- [x] Ensure that axe check is being properly utilized for accessibility testing
- [x] Remove EZR app from list of applications without e2e testing

## Acceptance Criteria
- All tests pass utilizing identified data paths
