### ISSUE TITLE
Change MPR feedback due date to EOD next business day

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#68625]
## User Story
As a Governance team member, I want to ensure I have enough time to adjust and/or update my feedback after a Midpoint Review so that I am not rushing to complete my feedback by same day.

Assignee: @allison0034 
Peer Reviewer: @erinrwhite 

## Description
Currently, Governance team provides written feedback for a VFS team at the Midpoint Review by EOD same day as the review. However, there are several scenarios where more time would be valued, including:

- If a team skips a DI we may need more time after to hear their explanation
- If things change drastically from a DI
- The later in the day meetings make it hard to change feedback after the meeting

Because of these reasons, Governance team would like to change our feedback due date to end of day the next business day, same as the Design Intent process.

## Impacted Artifacts
[Midpoint Review touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)
[How to document feedback for a Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1945239838/How+to+document+feedback+for+a+Midpoint+Review)
[Midpoint Review - During the Meeting (Synchronous)](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2790424639/Midpoint+Review+-+During+the+Meeting+Synchronous) - Step 6: wrap up
Slack reminders on #platform-governance-team

## Tasks
- [x] Update the following operational guidance and VFS-facing guidance to reflect the new date/time when feedback will be be available
- [x] For the Slack reminders on #platform-governance-team channel, contact Shira if you are unable to fix on your own
- [x] Draft a change history and Slack announcement post detailing the change 
- [ ] After peer review, publish the changes to Platform Website and the change history post
- [ ] Once PW is up to date, post slack announcement on #vfs-change-announcements Slack channel
- [ ] notify Shira for announcement at Team of Teams

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Governance team members now have an additional day for providing Midpoint Review feedback to VFS teams
- [ ] VFS teams are informed that Midpoint Review feedback will now be delivered no later than end of next business day

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Planned for Nov 9 - 21 sprint, however never picked up by team. Moving to next sprint.

**Comment by allison0034** [comment]
@erinrwhite can you peak at my [change history content](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2852421633/Copy+Change+history) please and let me know if it is ok?

**Comment by erinrwhite** [comment]
@allison0034 All documentation, including change history content, is looking good from here!

**Comment by allison0034** [comment]
@erinrwhite you can check the Slack updates by typing "/remind list" in. our Slack channel. Basically MPRs should be the same at DIs.

**Comment by allison0034** [comment]
@erinrwhite thank you! I believe all are fixed now.

**Comment by erinrwhite** [comment]
Slack reminders are looking great! This one's good to go.

**Comment by shiragoodman** [comment]
@allison0034 @erinrwhite We also need to update the automated responses within the Midpoint Review Slack workflow. Brian has put together some guidance on how to do that: https://vfs.atlassian.net/wiki/spaces/PPST/pages/2750677091/Managing+Slack+slash+command+workflows

**Comment by allison0034** [comment]
@briandeconinck can you review to see if the workflow updated to reflect EOD next business day?

**Comment by allison0034** [comment]
Brian reviewed and approved!

**Comment by shiragoodman** [comment]
hey there - minor piece of feedback that I'm hoping we can update/change on Slack and in the change history post. The language " feedback will be due EOD" is very confusing for me. We had pivoted our language a while ago to remove the word "due" since that is an action for our team, and not an action for VFS team. Feedback will be _provided_ EOD next business day. 

@allison0034 @erinrwhite would you be able to change the Slack announcement today and update the PW change history post so it updates tomorrow?

**Comment by shiragoodman** [comment]
you can keep this ticket closed. no need to reopen
