### ISSUE TITLE
Update KPIs for LGA for email outreach and USiP page

### ISSUE THREAD

**Issue by sdickson-gt** [department-of-veterans-affairs/va.gov-team#68635]
## Issue Description
_As the team is preparing to start the email campaign back up and ramp up comms with the USiP page, we need to revisit and agree on OKRs and KPIs. We need to determine if we can track the KPIs we've identified or if we'll need to write new queries, ask for info from other teams, or get engineering's help to log data.

Questions we want the data to answer:

- How effective are the drip campaigns?
- How frequently should we send emails?
- Which Veteran segments are most responsive to email campaigns?

- How often are Veterans starting and then abandoning modern credential account creation without completing?

- How often are Veterans completing IAL2 verification with their modern credentials?
- How often are Veterans failing remote identity verification?

- Are the numbers of call center support requests increasing after emails are distributed? 
- After the USiP updated? 
- With the interstitial page release? 
- With the direct mailout?
- If so, are the increases login.gov/id.me related?

---
## Tasks
- [x] _Review prior OKR and KPI documentation_
- [x] _Understand what data can be obtained from various sources_

## Acceptance Criteria
- [ ] _Documented OKRs and KPIs for email comms and USiP page._
- [ ] Update Domo Dashboard with the following data points (where possible):
- [ ] Metrics:
1. No. of Veterans who complete in-person identity proofing 
2. No. of failed verifications
3. No. of Login.gov accounts created
4. No. of legacy credential sign-ins
5. No. of ID.me accounts created
6. No. of Login.gov accounts verified
7. No. of Login.gov sign-ins
8. No. of ID.me sign-ins
9. First app the user logs into after creating modern credential
10. First app the user logs into after signing into modern credential 
11. Number of GovDelivery emails delivered
12. Number of GovDelivery emails opened
13. Number of login.gov links clicked from emails
14. Number of call center support requests 
15. Numbers of call center support requests related to login.gov/ID.me
16. Number of link clicks from USiP banner (from segment who saw it)
17. Number of login.gov account creations initiated
18. Number of ID.me account creations initiated
19. Number of login.gov account creations completed (vs. abandoned before completing)
20. Number of ID.me account creations completed (vs. abandoning before completing)

**Comment by sdickson-gt** [comment]
@lmorris3 I suggest we sync up on this to review which metrics from govdelivery (e.g. delivered, opened, clicks) and in general which metrics to track, e.g. accounts created and Login.gov usage.

**Comment by lmorris3** [comment]
@sdickson-gt I updated this story with the metrics and data questions we discussed in our meeting earlier.

**Comment by sdickson-gt** [comment]
1.	No. of Veterans who complete in-person identity proofing
BLUF: Low effort dependent on selection of users within segment.

For emails, the in-person ID proofing is N/A.  We are tracking the number of accounts created per email segment, thus completion of id-proofing.

2.	No. of failed verifications
BLUF: Insight into incompleted verifications can be inferred from available data with low effort with some manual steps for integrating with govdelivery.  Login.gov provides a high level report of where users are failing within proofing funnel. To get that specifically for the test segment will require development in VA.gov and Login.gov.


What sort of failed verifications are we looking for? I suspect we primarily want to know how many “fail to complete” the verification process.
But I’m not aware of how to get this information specifically for our test segments.  Login.gov does provide a monthly report of their proofing funnel (and it may not even be specific to VA partner). It provides an aggregate view of where users are dropping off.

What we can know is:
•	Total of users in segment who initiate the proofing flow based on clicking the email
o	govdelivery provides clickthrough. 
o	We can also query datadog for authentications initiated from govdelivery, but datadog won’t indicate which campaign.
•	Total of users in segment who have created a Login.gov account

Caveats:
•	Can’t distinguish the users who initiated account creation based on 1) the email versus 2) some other means such as organically visiting VA.gov.
o	For #2, prior to account creation, since users are not logged in, we can’t tell who they are and if they are in a test segment group

DataDog reports are also reporting the total authentication abandonments, but only Login.gov can provide what percentage of these users initiated and abandoned the Login.gov account creation process.

If we decide to pursue more granular data from Login.gov, it would likely involve development by both VA and Login.gov to track by test segments.

3.	No. of Login.gov accounts created
BLUF: Assuming we are only we concerned about verified account creation, this is a low effort dependent on selection of users within segment.

We have access to this currently and have reported for prior emails
•	Total accounts created from monthly data export from MPI
•	Can infer account creation from authentication transactions
o	From SSOe splunk, but requires a manual task to initiate job as needed. Does not include SiS transactions.
o	From DataDog.  Can be fully automated to include all USiP transactions.  Does not include non-VA.gov SSOe transactions.  (Note, It is still TBD to get unique data from DataDog for a specified timeframe.  For example, DataDog will break a request for unique authentications in the past year into a set of unique authentications by day.) 

4.	No. of ID.me accounts created
Same as #3

5.	No. of Login.gov accounts verified
Same as #3

6.	No. of Login.gov sign-ins
BLUF: Assuming we are only concerned with "unique authentications", this is a low effort dependent on selection of users within segment.

Prior requests have been to focus on distinct users who sign-in by day/week/month.  We can get total if desired.
We have access to this currently and have reported for prior emails
•	From DataDog.  Can be fully automated to include all USiP transactions.  Does not include non-VA.gov SSOe transactions.  
•	This could also be done using SSOe splunk to include SSOe authentications not originating from VA.gov, but we prior guidance was to focus on VA.gov.

7.	First app the user logs into after creating modern credential
BLUF: This is of little value in the context of email campaigns, since all users will be directed to VA.gov


The emails will always direct users to VA.gov, so in the context of our email campaigns, this is not very useful.
If we wanted to look into this in general, there are a couple considerations
•	SSOe splunk provides this but the SSOe logs will indicate USiP without insight into which application USiP is federating the request to
•	Alternatively, it will require some discovery to get this information from DataDog logs for USiP (SSOe and SiS)

8.	First app the user logs into after signing into modern credential
Essentially same as #7.

9.	Number of GovDelivery emails delivered
BLUF: Low effort with some manual steps for integrating with govdelivery

We can get this from GovDelivery reports.
Caveat: There is no current connector between Domo and GovDelivery for a streamlined automated process.  Further, GovDelivery doesn’t currently offer an API for the reports.  Workaround is to manually run report and do a CSV export and then import into Domo using Domo Workbench.  

10.	Number of GovDelivery emails opened
See #9

11.	Number of login.gov links clicked from emails
See #9

12.	Number of call center support requests
This is very broad.  Will need specifics beyond #13 below.

13.	Numbers of call center support requests related to login.gov/ID.me
BLUF: If this is a priority, I will need a task assigned to do deeper discovery work.

This will require some discovery into granularity and quality of call center support requests, and access to data/API.
•	The Domo Salesforce Issues (MVP) dashboard has filters for: 
o	Login.gov, ID.me, DS Logon and MHV:  with sub-categories of forgotten password and identity verification issues
o	There are are also filters for Identity and Account Sign In: with sub-categories of navigation issues and security

Would potentially include development and process changes within call center to track call to the test segment.

14.	Number of links clicked from USiP banner (from segment who saw it)
Data analytics will depend on development implementation of a log entry.  

15.	Number of login.gov account creations initiated
And will need to implement a means to correlate link clicks by a non-authenticated user with subsequent account login or creation.

16.	Number of login.gov account creations completed (vs. abandoned before completing)
See #15
