### ISSUE TITLE
How might Pension engineers help with Deactivation FE efforts? 

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#68633]
## Issue Description

**User Stories:**
As a user attempting to apply for Pension benefits online,
I need to know what my options are when choosing to submit via PDF,
so that I can decide whether I want to mail my PDF form or submit it electronically via their system.

As a Pension team,
we need to ensure users attempting to apply for Pension benefits online know about the "quick submit" path to upload a PDF version of their form electronically,
so that they can decide whether they want to use that to submit their claim or not.

**More Info:**

Using "QuickSubmit" would allow a path for Veterans to still submit all-digitally. It already exists, we'd just be helping them find it. It would also allow us to frame "deactivation" as more of a "digital redirect" and give us time to build the updated online submission version of the form.

QuickSubmit is a feature supported by a team in VBA within a product called AccessVA that requires separate login.

**Tasks:**

- Update any verbiage on existing Pension deactivation designs that let veterans know that while the Pension online form is temporarily unavailable, they can still:

- Use "QuickSubmit" as a path where Veterans can still upload the PDF version of the 527 form

- Provide a link to QuickSubmit within the verbiage.

**Goals**

Any widgets and/or communications already drafted, within the form flows already identified, will be updated to communicate that while Pension form is temporarily unavailable, the veteran has the option to use QuickSubmit as an option to submit a PDF form digitally.

**Tickets CAIA is working from:**

- [Pension page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62633)
- [Email copy changes](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62878)

**Other reference tickets the Non-Disability Benefits team had created:**

- Implement CAIA changes on Pension Review Page and Widget #66663
- Pension Email Template #64679

---
## Tasks

- [x] Send recap of changes to Maya/create tickets
- [x] Run priority by Emily
- [x] Create task for Maya
- [x] Maya to draft email copy and Pension page
- [ ] Work with Julie Strothman
- [ ] Loop in CAIA/Governance team via office hours or via Github tickets
- [ ] Todd to draft on staging environment
- [ ] Access to Flipper for Todd for access to anything below Staging (Matt will also need access to Flipper)
- [ ] Engineer will need to trigger notification widget

**In progress claims:**
365 days (from 60 days form start day)
Duplicate ticket for Burial

VA Notify 

## Acceptance Criteria

- [ ]

**Comment by vbellissimo** [comment]
This card is cancelled. Pension deactivation is already underway.
