### ISSUE TITLE
Add CODEOWNERS section PR Triage Doc

### ISSUE THREAD

**Issue by bdech** [department-of-veterans-affairs/va.gov-team#68630]
## Description 
The objective of this ticket is to add a new section to the PR Tier 1 Triage Confluence document, which will contain relevant information regarding Vets-API CODEOWNERS.

[PR Review Tier 1 Triage](https://vfs.atlassian.net/wiki/spaces/~71202013aea26098a14ec0a4a43cb8bc9a85b4/pages/2663186485/PR+Review+Tier+1+Triage)
---

## Definition of Done
All tasks below are completed.

---

## Tasks 
- [x] Explain CODEOWNERS
- [x] Outline the current process for maintaining Vets-API CODEOWNERS
- [x] Breakdown how CODEOWNERS file works
- [x] Include 'Exception' section, and explain exceptions to this rule
- [x] Have Rachal Cassity review changes

--- 

## Resources & Additional Info 
_https://dsva.slack.com/archives/C02RLAUM2LV/p1697637577604029_

**Comment by bdech** [comment]
Requested Rachal to look over the additions and provide feedback.
