### ISSUE TITLE
Discovery spike: Identify audience for full-MHV ux-health analytics dashboard and hypotheses/KPIs to monitor

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#68631]
### User story

As a Cartographers team member, I want to document how user flows from the MHV landing page to and among the health tools will change during the transition from the MHV National Portal to VAgov, so that we can define an MVP analytics dashboard that helps stakeholders monitor the health of user flows.

### Notes
- Integration with Cerner has been delayed till Phase 2
- Traffic to MHV landing page will be light until Ph2, when all tools will have links back to LP (e.g., breadcrumbs)
- Some of the key hypotheses or KPIs may have already been identified by tool teams or leadership
- The team has an older, [related ticket](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698851732983/a6a9d0c6c1ed10d7ec010d6e5c9950292e185b85?wid=0-1699400058186) that may contain some useful ideas
- MarciM has created some documentation in github (need to find)
- Cartographers will want to know what's happening between and across products, in line with our secondary nav work – leadership will certainly want aggregation above the tool level also

## Acceptance criteria

- Identified the stakeholders who would need such a top-level dashboard – i.e., above the tool-specific level – and learned whether there are similar efforts underway
- Identify what data we and the identified stakeholders would want to monitor to ensure the health of the health experience and tools across platforms, with rationale
- Technical recommendation documented for how platforms could be leveraged to gather and present data in a dashboard for the identified stakeholders

## Tasks

- [x] Create [mural with screen shots](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698851732983/a6a9d0c6c1ed10d7ec010d6e5c9950292e185b85?wid=0-1699400058186) of MHV National Portal
- [x] Get access to MHV NP analytics, for purpose of baselining user behaviors
- [ ] Look at user types (from other story) and follow each one into Ph2 thinking
- [ ] Write follow-on user stories

**Comment by wesrowe** [comment]
completed first two tasks. others replaced by #70573. closing.
