### ISSUE TITLE
Create a job to fetch and update the lat/long for each rep/org record

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#68641]
## Issue Description
Create a job to fetch and update the lat/long for each rep/org record.

---
## Tasks
- [ ] Confirm the Lighthouse Address Validator API can validate an address with just city, state and zip.
- [ ] If the Lighthouse Address Validator API cannot validate an address with just city, state and zip, look into using MapBox instead
- [ ] Write pseudo-code for this job
- [ ] Code up the job
- [ ] Write tests

## Acceptance Criteria
1. **Lighthouse Address Validator API Validation:**
   - [ ] Verify that the Lighthouse Address Validator API can successfully validate an address using only city, state, and zip.
   - [ ] If the Lighthouse Address Validator API does not support validation with just city, state, and zip, confirm the compatibility with MapBox.
2. **Pseudo-code:**
   - [ ] Review and approve the pseudo-code for the job functionality.
   - [ ] Ensure the pseudo-code is clear, concise, and accurately represents the logic for fetching and updating lat/long for each rep/org record.
3. **Job Implementation:**
   - [ ] Implement the job according to the approved pseudo-code.
   - [ ] Ensure the job runs without errors and successfully fetches and updates the lat/long for each rep/org record.
4. **Testing:**
   - [ ] Develop comprehensive tests for the job functionality.
   - [ ] Ensure tests cover various scenarios, including successful lat/long updates and handling of invalid addresses.
   - [ ] Confirm that tests provide sufficient coverage for potential edge cases.

**Comment by holdenhinkle** [comment]
`Veteran::BaseReloader#find_or_initialize `
retrieves the current rep or org, or creates it if it does not exist. 
adds the poa code to `poa_codes` unless it already exists
sets `phone`
returns `rep`

set `raw_address` in this method (city, state, and zip)

***

In the `find_or_create_` methods, add the following:

if `current zip_code` is `nil` or `current_zip_code` doesn't equal `previous_zip_code`
  `#validate_city_state_zip` which returns Lighthouse Address Validation response
  `# set_address` if address is valid
save rep

***

Continue reading the address validation code in VAProfile::AddressValidation::Service which uses the Lighthouse Address Validator API (I'll need to write something similar.)

**Comment by holdenhinkle** [comment]
Lighthouse address validator api - https://developer.va.gov/explore/api/address-validation/

**Comment by oddball-lindsay** [comment]
Backup approach could be to use Mapbox if the Lighthouse address validator requires Address 1

**Comment by holdenhinkle** [comment]
Without address 1, 2, or 3 (invalid address):
```
nonroot@vets-api-wnonroot@vets-api-web-6db9b47bdb-5n6kv:~$ curl -X POST 'https://sandbox-api.va.gov/services/address_validation/v2/candidate' \
--header 'apikey: removed' \
--header 'Content-Type: application/json' \
--header 'accept: application/json' \
--data-raw '{
  "requestAddress": {
    "stateProvince": {
      "code": "VT"
    },
    "addressPOU": "RESIDENCE/CHOICE",
    "zipCode4": "",
    "zipCode5": "05495",
    "requestCountry": {
      "countryCode": "US"
    },
    "addressLine1": "",
    "addressLine2": "",
    "city": "Williston",
    "addressLine3": ""
  }
}'
{"messages":[{"code":"ADDRVAL203","key":"InvalidRequestStreetAddress","text":"One of addressLine1, addressLine2 or addressLine3 must be provided","severity":"ERROR"}]}nonroot@vets-api-web-6db9b47bdb-5n6kv:~$ 
```

With address 1 (valid address):
```
nonroot@vets-api-web-6db9b47bdb-5n6nonroot@vets-api-web-6db9b47bdb-5n6kv:~$ curl -X POST 'https://sandbox-api.va.gov/services/address_validation/v2/candidate' \
--header 'apikey: removed' \
--header 'Content-Type: application/json' \
--header 'accept: application/json' \
--data-raw '{
  "requestAddress": {
    "stateProvince": {
      "code": "VT"
    },
    "addressPOU": "RESIDENCE/CHOICE",
    "zipCode4": "",
    "zipCode5": "05495",
    "requestCountry": {
      "countryCode": "US"
    },
    "addressLine1": "346 Zephyr Rd",
    "addressLine2": "",
    "city": "Williston",
    "addressLine3": ""
  }
}'
{"candidateAddresses":[{"address":{"addressLine1":"346 Zephyr Rd","city":"Williston","zipCode5":"05495","zipCode4":"1720","county":{"name":"Chittenden","countyFipsCode":"50007"},"stateProvince":{"name":"Vermont","code":"VT"},"country":{"name":"United States","code":"USA","fipsCode":"US","iso2Code":"US","iso3Code":"USA"}},"geocode":{"calcDate":"2023-11-17T20:11:57Z","locationPrecision":32.0,"latitude":44.453428,"longitude":-73.105133},"usCongressionalDistrict":"At Large","addressMetaData":{"confidenceScore":100.0,"addressType":"Domestic","deliveryPointValidation":"CONFIRMED","residentialDeliveryIndicator":"RESIDENTIAL","validationKey":-2059306827}}]}
```

If we need lat/long for just city, state, and zip, we'll have to use MapBox.

**Comment by holdenhinkle** [comment]
Thoughts:

The ClaimsApi has never saved/used the city/state/zip for reps/orgs. Those fields were added by our team - https://github.com/department-of-veterans-affairs/vets-api/commit/7f38afe530976cea72be3ffd09465b320aa3f21d

I want to confirm that all of the reps that are referenced in the OGC `orgsexcellist` list are in the `Representatives` .xls file. If they are, then we'll have addresses for both reps and orgs.

TODO:

- [ ] confirm that all of the reps that are referenced in the OGC `orgsexcellist` list are in the `Representatives` .xls file

**Comment by oddball-lindsay** [comment]
This might not be necessary -- identified ~50 records that 

25 instances where the local rep does not exist within the Reps file, because the data that we have is not in sync.  We're getting new reps daily which is represented in the data we're getting from the OGC tool every day, but we're not getting daily spreadsheets from Randy (this is sent weekly).

Possibly explore a script to manually update any records that are affected by this disconnected timing.

**Comment by oddball-lindsay** [comment]
After discussing at demo today, it does not sound like we need to pursue the Mapbox solution for the 5-25 potentially impacted records.
