### ISSUE TITLE
[Design, FE] 10-10EZR - Standalone form: MUST feedback - Review page Agreement section needs to be updated

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#68644]
## Background
During the Midpoint review for the 10-10EZR form, we received some MUST feedback on the [content](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68507) and [IA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68542) of the Review page - agreement verbiage.

>#### Review Page
>- Inaccurate information 1, >Agreement - The Second bullet the user must agree to does not accurately represent the application options. The application explicitly says that phone and email contact information are optional. Please reword the second bullet to accurately reflect the application process.
>- Inaccurate Information 2, >Agreement - The third bullet is not accurate. A veteran with a disability rating of 50% or more does not incur any charges for care or medication regardless of whether those services are related to their disability or not. >Please reword the third bullet to reflect the reality of all veterans seeking care and not just those who have certain disability ratings. [Consult this webpage for more info](https://benefits.va.gov/benefits/derivative_sc.asp). 
>
>Review page link to privacy policy 
>- The link to the privacy policy should open in a new window in order to keep users in the flow. Please use a visual and ARIA indicator to let users know that the privacy policy link opens in new window. The [privacy agreement design component](https://design.va.gov/components/form/privacy-agreement) is a good model for this.

This ticket is to make the three necessary updates to the content.  All changes are outlined below:
- EXISTING:
You agree that we can contact you at the email, home phone number, and mobile phone number you gave us in the application.
     - UPDATE:
You agree that we can contact you at the address and any email or phone number you gave us in this application.

- EXISTING:
You agree to the assignment of benefits so we can bill your other health insurance or other responsible party for charges of nonservice-connected VA medical care or services.
     - UPDATE:
You agree to the assignment of benefits so we can bill your other health insurance or other responsible party for any charges for non-service-connected VA medical care or services that may apply.

- Add an icon and aria label as used in the Design System's [privacy agreement design component](https://design.va.gov/components/form/privacy-agreement)

## Tasks
- [x] DESIGN - Update Review page designs with content changes
- [x] FE - Update Review page UI with content and IA changes
- [ ] Validate with PM for quick review

## Acceptance Criteria
- The Review page Content and IA changes from the Midpoint review are addressed.

**Comment by jessicastump** [comment]
The agreement section of the [Sketch file](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/JAvME97) has been updated. I believe this is still with HEC/stakeholders for review
cc @alexseelig

**Comment by hdjustice** [comment]
Received approval from Simone Gully on 11/1 via email

**Comment by longmd** [comment]
@hdjustice , here is the screenshot with the requested updates.

<img width="468" alt="Screenshot 2023-11-09 at 12 26 06 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/3debc5d2-1718-4973-a326-de9d2cabc13a">

**Comment by hdjustice** [comment]
Looks great!, thank you @longmd
