### ISSUE TITLE
[MVP] Extend Pension Form Expiration

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#68648]
## Issue Description
_Currently, the pension (527) and burial (530) forms expire 60 days after the last edit date. The expiration date should be extended to 365 days FROM THE CLAIM CREATION DATE to allow users more time to submit their claim._

Research for pension ITF date #66958 

Ticket for burial form expiration date is #64881.

Related Slack thread for reference: https://dsva.slack.com/archives/C05MS96P6P2/p1701352479831879

---
## Tasks
- [ ] Change the pension 527 form data to expire 365 days from creation date.
- [ ] Ensure any front-end components display expiration date appropriately.
- [ ] Ensure any front-end components display the expiration time frame appropriately (12 months vs 2 months)

## Acceptance Criteria
- [ ] Pension 527 form expires 365 days from first creation date.
---

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/68648?planning-poker) with Zenhub @mjknight50 @danlim715 @wayne-weibel @TaiWilkin

**Comment by vbellissimo** [comment]
Closing this task, as it was covered by these other tasks:

- Change ITF expiration date #71079
- [MVP] Apply for Veterans Pension Page: Update copy from 60 days to "one year" #71647
