### ISSUE TITLE
[FE] Dot indicator: Create Frontend technical documentation

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#68650]
## Background
In the project outline for the dot indicator implementation on unread health messages there is a section for Frontend documentation. This refers to the technical implementation. We need to create a short explanation of the technical logic for how we show the dot indicator in this scenario - i.e. how do we determine unread health messages.

Previous example of technical documentation: [onsite notifications MVP (depreciated)](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications#frontend)

## Tasks
- [x] Create technical write up [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/dot-indicator/create-dot-indicator/README.md#frontend)
- [x] Tag PM for review

## Acceptance Criteria
- [ ] Documentation is updated

**Comment by allisonlu** [comment]
@ajakabcin 

Documentation ready for review 🤠 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/dot-indicator/create-dot-indicator/README.md#frontend

**Comment by ajakabcin** [comment]
This is great thank you!!
