### ISSUE TITLE
Implement Deep Linking for search 

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#68658]
## Issue Description
When a user navigates directly to a search link with query params, the React application should parse the query params and make an immediate request to `vets-api` to retrieve and display the results. This feature will allow users to share search links that automatically show the search results when clicked.

---

## Tasks
- [x] Utilize the `useLocation` hook from `react-router-dom` to access the current URL's query parameters upon component mount.
- [x] Parse the URL to extract search query parameters (if they exist).
- [x] Implement a function to make an immediate GET request to `vets-api` using the extracted query parameters.

## Acceptance Criteria
- [x] Navigating directly to a URL with search query parameters (e.g., `/search?query=userInput`) automatically triggers a search request to `vets-api`.
