### ISSUE TITLE
Make swimlane diagram more visible

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#68657]
## User Story
As a VFS team member, I want to know how best to flow through the various touchpoints of the Collaboration Cycle so that my team can plan ahead and meet expectations.

Assignee: @allison0034 
Peer Reviewer: @rferguson13 

## Description
On the [Collaboration Cycle homepage](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/) on Platform Website, Governance team currently links out a Swimlane diagram of the full collaboration cycle that was created in MURAL. This diagram shows how a VFS team should flow through the various Collaboration Cycle touchpoints, as well as the various actions non-VFS teams who support the Collaboration Cycle take. 

The current link is not very visible to VFS teams. When VFS teams are made aware of the link, they find the swimlane diagram extremely helpful. How might we make the swimlane diagram more visible to VFS teams?

## Impacted Artifacts
[Collab Cycle page](https://vfs.atlassian.net/wiki/spaces/CC/overview)

## Tasks
- [x] Link "series of touchpoints"
- [x] Put a break between the paragraph and "To see a more in-depth understanding, open the swim lanes Mural"
- [x] Any other improvements

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] VFS team members can easily see the preferred Collaboration Cycle flow (aka the swimlane diagram)

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by rferguson13** [comment]
@allison0034 What about adding a link on the [Touchpoints](https://vfs.atlassian.net/wiki/spaces/CC/pages/1768423528/Touchpoints) page? Maybe "Collaboration Cycle touchpoints" in the first paragraph?

**Comment by allison0034** [comment]
@rferguson13 love it! It will update the next time the page is published.

**Comment by shiragoodman** [comment]
@it-harrison I am removing you as the peer reviewer for this ticket.

**Comment by shiragoodman** [comment]
@allison0034 I just had a thought - can we change the name of the "swimlane diagram" to name it what it actually is? Maybe the Collaboration Cycle touchpoint flow? Or something that says specificalyl what you'd be looking at. Swimlane diagram is not clear.

**Comment by rferguson13** [comment]
@shiragoodman I really like that. "Swimlane diagram" isn't the clearest description.

**Comment by allison0034** [comment]
@shiragoodman done!

**Comment by shiragoodman** [comment]
@allison0034 please be sure to link the pages you have changed (drafts or live) for @rferguson13 and I to peer review. Thanks!

**Comment by allison0034** [comment]
@shiragoodman there were no drafts since this was such a quick change (less than 5 min). She already completed the peer review with the exception of your request. I will ping her again when it is live.

**Comment by shiragoodman** [comment]
The change looks good @allison0034 however I still have concerns that the existence of this image:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelh1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--051ce33e69746003c3e7c235141cc8180ad07de3/image.png)
...may be doing more harm than good. I'm okay with moving forward with this change for now, but I think we may want to seriously consider redesigning this whole page (at some point) and incorporating more useful graphics and images. Would be happy to discuss this further!
