### ISSUE TITLE
Update Support Best Practices with Ownership Changes

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#68663]
## Description 
Update these pages with updates to the process of completing tickets:

- https://vfs.atlassian.net/wiki/spaces/PTST/pages/2630353240/Advanced+Ticket+Support+Best+Practices+Tier+2
- https://vfs.atlassian.net/wiki/spaces/PTST/pages/2426241154/Support+Best+Practices

---

## Definition of Done

- All tasks below are complete

---

## Tasks 
_Steps to reach definition of done._ 

- [x] Add updates to each document
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
Context: https://dsva.slack.com/archives/C02RLAUM2LV/p1698690871505009

---

**Comment by alyssagallion** [comment]
Add how to find help section for both Tier 1 and Tier 2:

Tier 1

- [ ] Search Slack channel
- [ ] Ask questions in #platform-support-channel or during standup
- [ ] Ask CoP if no answers found

Tier 2

- [ ] Search Slack channel
- [ ] Ask questions in #platform-support-channel or during standup
- [ ] Ask CoP if no answers

**Comment by alyssagallion** [comment]
Updated documentation on a call with Brandon today. Closing.
