### ISSUE TITLE
Content updates to Funding Fee and Loan Closing Costs page

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#68667]
## Issue Description

The home loans team has updates they would like made to [VA Funding Fee And Loan Closing Costs | Veterans Affairs](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.va.gov%2Fhousing-assistance%2Fhome-loans%2Ffunding-fee-and-closing-costs%2F%23other-loan-closing-costs&data=05%7C01%7C%7C58be7002b12d47cd85ba08dbd9424e3b%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638342651022051529%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SCkkVGrc8h6sZB90fSeVRJ39pT32kVf5ttgIj9En%2BRk%3D&reserved=0)

Changes and explanation captured in track changes in this document: [fees-changes-v2.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/13209409/fees-changes-v2.docx)

We will need the stakeholders to review before we can publish the changes, so Derek can work with A and reach out with any clarifying questions beforehand. Then sending the preview link or screen shots of the changes once they're in Drupal.

---
## Tasks
- [x] Updates added to page (Derek)
- [x] Review updates (A)
- [x] Share screenshots/preview link with stakeholders (Derek)
- [ ] Update Drupal draft with stakeholder feedback (Derek)
- [ ] Copyedit (Chelsea)
- [ ] Publish (Chelsea)

## Acceptance Criteria
- [ ] Updated language is live on the site
---

**Comment by d-beyer** [comment]
Hey @aprocik1 -- I've implemented the requested changes in [draft in drupal](prod.cms.va.gov/node/748/latest).

I only made one significant divergence from the requested changes: I revised the new "note" text they added at the end. Interested if you have any further improvements on this.

Additionally, I have only one question: They cut three sentences because they "imply the Veteran would be able to include other loan costs into a purchase transaction". I get that the sentences are apparently misleading, but are we removing an important warning? Should we try to find another way to include it without the misinformation they're concerned about?

**Comment by aprocik1** [comment]
Update: On 11/9, Derek emailed the stakeholder with our recommendations and a few questions. We're waiting for their feedback before finalizing, copyediting, and publishing.

**Comment by d-beyer** [comment]
Update: I emailed the stakeholder again to check in on 11/29 and got no reply.

**Comment by aprocik1** [comment]
Update: On 1/2, Derek emailed the stakeholder with our recommendations and a few questions. We're waiting for their feedback before finalizing, copyediting, and publishing.

**Comment by mistymg** [comment]
I reviewed this page in Drupal. The former contract team had made edits in Drupal in 2023. But since then there've been updates published to this page by Randi and Beth (some of which include the suggestions the former contract team made in this ticket). Closing this ticket.
