### ISSUE TITLE
Request Staging Review for Find a Representative MVP

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#68661]
## Issue Description
To prepare for the Staging review, we will need to provide a link of artifacts (listed below in Tasks) in our [Collaboration Cycle ticket for Find a Rep MVP](https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/65707).

---
## Tasks
- [x] Link Product artifacts
- [x] Link Content artifacts
- [x] Link IA artifacts
- [x] Create QA artifacts 
- [ ] Link QA artifacts
- [x] Link Accessibility artifacts
- [x] Schedule staging review for early Sprint 8
- [x] Invite team members to staging review
- [x] Notify the Collaboration Cycle in Slack

## Acceptance Criteria
- [ ] All artifacts have been linked in the Collaboration Cycle ticket
- [x] Staging review has been scheduled
- [x] Collaboration Cycle has been notified

**Comment by cosu419** [comment]
Here are potential error states that come to mind for the accessibility staging review. Tagging @holdenhinkle and @jvcAdHoc

**UI errors:**
- Empty city/state/zip input
- Invalid city/state/zip input (entering gibberish into facility locator prevents searching, but doesn’t indicate what’s wrong). 
- Geolocation failure (user denied "Allow location?" browser request, or their system permissions blocks it)

**Non-UI errors:**
- Geolocation failure (eg, Mapbox API unavailable)
- Geocode failure (also Mapbox)
- VA server error, db error, timeout etc. 
 
Looking at the frontends of existing prod apps, they tend to handle HTTP errors generically, displaying a message like: "We’re sorry. Something went wrong on our end. Check in with a staff member." regardless of the status code. I'm inclined to do the same for non-UI errors.

**Comment by oddball-lindsay** [comment]
Thanks @cosu419 !  Some questions about the UI errors:

> Geolocation failure (user denied "Allow location?" browser request, or their system permissions blocks it)

In these cases, would the user experience anything?  Right now if I try to search without inputting a location the page will highlight the location field.  Perhaps this would also be the experience when there's a geolocation failure?


> Invalid city/state/zip input (entering gibberish into facility locator prevents searching, but doesn’t indicate what’s wrong).

What's the expected user experience for this?  If I put in a unexpected location in Staging ("3"), there are results returned.  Is this a bug I should report?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0tUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0473330fedff3e1eddeb84f4a04886d703132649/image.png)

**Comment by cosu419** [comment]
@oddball-lindsay In Facility Locator, if the user clicks "Get My Location" and then blocks location access, there should be an alert like below. This component exists in FAR but isn't currently enabled... another small change that I'll add to the Use My Location task list, which is once again marked "In Progress" until we get our own Mapbox API token. I'm drafting a support request for that now.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWFUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc09932a6a7e6402ff5768571af498e2af63e7c6/image.png)

Regarding the results getting returned despite invalid search input - the front end validation is only checking for the presence of an address string. So long as there's any search text at all, it hands off the search query to Mapbox for geocoding, then sends the resulting coordinates to our backend. The mock data is currently skipping the last two steps (pending the Mapbox token + connecting to backend), so it displays data regardless. Not a bug but we'll want to revisit this to confirm the error is being displayed.

**Comment by oddball-lindsay** [comment]
Thanks @cosu419!  I'll add the location error to the Contact Center Product Guide for now and can add in the later when everything is connected.

**Comment by oddball-lindsay** [comment]
aiming for 11/30 staging review, could push to 12/1 if we need more time

**Comment by oddball-lindsay** [comment]
Staging Review scheduled for 12/1 at 2pm ET, which was the first available time.  Checking with Zach to see if he's available, as his presence is required but this time goes against our working agreement of avoiding Friday meetings.

Left a note for Governance that we're still working through the QA artifacts.  There are a couple code links I'll need to include which maybe @holdenhinkle or @cosu419 you can help me with:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2tIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a1bc849b1e68a6c06ec18289c3f218ddb8f1b8fb/Pasted%20Graphic%201.png)

**Comment by oddball-lindsay** [comment]
Was notified that we needed to complete an accessibility test - completed https://github.com/department-of-veterans-affairs/va.gov-team/issues/70616

**Comment by cosu419** [comment]
Hey @oddball-lindsay - [here is a code link](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/representative-search) for the E2E tests + code coverage.

**Comment by oddball-lindsay** [comment]
Rescheduled Staging Review to 12/7 at 3:30pm ET

**Comment by oddball-lindsay** [comment]
Staging Review happened today -- they called out the missing QA artifacts, but we're fine to proceed with completing those on our own and can then head right into production.
