### ISSUE TITLE
[FE] - Unified e2e test - define paths

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#68683]
## Summary 
With the new flow of unified, we removed all of our e2e tests. Now we need to re-imagine the tests. This ticket is to define our new e2e format and tests needed. Make sure to note where to add screenshots.

Examples: 
 - Day-of check-in, on-time appointment, no demographics
 - Day-of check-in, expired appointment

## Tasks
- [x] [FE] determine tests needed
- [x] [FE] create tickets to create the actual tests

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
We also decided to exclude screenshot considerations for now, and then evaluate how we want to handle those after new tests are in place.

**Comment by brianseek** [comment]
@loripusey Here are the resulting tickets from this ticket. The plan is to start with day-of tests, and then do pre-check-in after so we can set the style and consistency first.

day-of:
[70319](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/70319)
[70320](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/70320)
[70321](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/70321)
[70322](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/70322)
[70323](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/70323)
[70324](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/70324)
[70325](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/70325)
[70326](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/70326)
