### ISSUE TITLE
Additional form fields to reflect 21-22/21-22a form updates

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#68694]
## Issue Description
As of October 27, the 21-22 and 21-22a forms have been updated!  It looks like the [forms on VA.gov](https://www.va.gov/find-forms/about-form-21-22/) have been updated to reflect these changes.

[21-22 form](https://www.vba.va.gov/pubs/forms/VBA-21-22-ARE.pdf) update:
1. Field 11a "Claimant's Date of Birth" in Section II has been added

[21-22a form](https://www.vba.va.gov/pubs/forms/vba-21-22a-are.pdf) update:
1. Field 11 "Claimant's Date of Birth" in Section II has been added
2. Field 19 "Authorization for Disclosure to Affiliated Personnel" has been added to allow additional authorization for
   1.  All associate attorneys, claims agents and support staff affiliated with the representative
   2.  Individually named administrative employees of the representative

To reflect these updates we'll need to:
1. Add in the Claimant's Date of Birth field (this could be in the [Claimant's Personal Information page](https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/v/nMy9b0/p/57E87DC8-237D-48A7-98D2-A08F1738F615/canvas?posX=-51315.20729061784&posY=-19542.132637120976&zoom=0.4683416187763214))
2. Add in an additional authorization step for the individual representative flow (this could be the first authorization step to match the 21-22a form) 

---
## Tasks
- [x] Add in field to capture Claimant's Date of Birth
- [x] Add in additional page to capture Authorization for Disclosure to Affiliated Personnel

## Acceptance Criteria
- [x] Claimant's Date of Birth has been added
- [x] A page for Authorization for Disclosure to Affiliated Personnel has been added

**Comment by mtri** [comment]
Determining actual language of authorization step and choices based on clarification from advisors next Tuesday.
[Relevant Slack thread](https://dsva.slack.com/archives/C05L6HSJLHM/p1698856124380209)
