### ISSUE TITLE
[FSR] Feature flag fetching on form restart

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#68714]
## Description
A while back we included a change to update the feature flags when a user restarted their form using "Finish this request later..." flow (_not_ by refreshing). It looks like the `/feature_flag*` call is only happening on the initial app load, so even if we do grab the 'latest' flag status when the user restarts the form without refreshing they are only seeing what values were most recently fetched. It's not likely a user will choose to restart in between us flipping a flag from true to false, but let's do some manual testing to confirm this won't cause any unexpected behavior. 

[Here](https://github.com/department-of-veterans-affairs/vets-website/blob/55ed7ce2fb4efd4d6b635a5fefcda57e3f12f964/src/applications/financial-status-report/containers/App.jsx#L130-L149)'s the `useEffect` we should confirm handles the changes

Given: A feature flag has changed states since a veteran started an FSR
When: A veteran chooses to restart the form w/o refreshing
Then: The new FSR they start contains the latest feature flag status

## Tasks
- [ ] Confirm feature flag changes are properly loaded when restarting form
- [ ] Clean up `useEffect` as necessary
- [ ] (optional) Generate new tickets if there's significant effort involved

## Acceptance criteria

- [ ] Feature flag changes are being loaded as expected
- [ ] (optional) New ticketed work is created to address any issues

## Testing
- [x] N/A 

Testing procedure:
 - Start FSR with feature flags set one way
 - Save form
 - Change feature flags
 - 'Continue' form
 - Restart form
 - Confirm changes are reflected

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by Dr-Pongo** [comment]
Closing out as a duplicate since [this ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/69313) will capture the same/similar effor
